### PR TITLE
make sure UWP app can run

### LINKED ISSUE #25718: Add UWP smoketest to CI
It would be nice to avoid problems like #25683 in the future. @ferjm You mentioned you were able to launch the UWP app from the command line in the past; could you explain how you did that so we can see if we can replicate it in CI?

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #25718

This includes https://github.com/servo/servo/pull/25661 with some minor tweaks (certificate file reference was missing, and its id was wrong) and a python script.

Still need to hook that to our CI.

### CODE REVIEW

**Comment by paulrouget** [comment]
> Cannot import the key file 'ServoApp_TemporaryKey.pfx'. The key file may be password protected. To correct this, try to import the certificate manually into the current user's personal certificate store.
> A certificate with thumbprint 'DC99ACEDA24EBA00BFB07A3986BB6892B0DE278B' that is specified in the project cannot be found in the certificate store. Please specify a valid thumbprint in the project file.> The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.

**Comment by paulrouget** [comment]
I managed to make it work. But I’m not sure how:

- I’ve updated Windows
- I’ve updated VS2017
- I installed VS2019
- I’ve updated the Windows 10 SDK

Something fixed it.

**Comment by paulrouget** [comment]
(closed the wrong issue)

**Comment by paulrouget** [comment]
> Administrator permissions are needed to use the selected options.  Use an administrator command prompt to complete these tasks.

Damn.

**Comment by paulrouget** [comment]
Is it possible to install the certificate into the taskcluster CI?

**Comment by paulrouget** [comment]
From IRC:

```
@SimonSapin │ We might need to do that when building the VM image                                                                                         By adding something in https://github.com/servo/taskcluster-config/blob/master/config/windows-first-boot.ps1                                      │
and running https://github.com/servo/taskcluster-config#mach-new-ami-creating-a-new-vm-image-for-windows-workers         
this script is a bit fragile and annoying to debug, and requires access to our AWS account. I could do the rebuild if you’d like            │
If you provide a PowerShell script to run as admin                                                   
```

**Comment by paulrouget** [comment]
This has to be useful: https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps#install-your-app-package-using-an-install-script

**Comment by paulrouget** [comment]
And https://stackoverflow.com/questions/39951545/powershell-install-add-appdevpackage-ps1-package-fail-can-not-find-any-package/42136370#42136370

**Comment by paulrouget** [comment]
And https://docs.microsoft.com/en-us/windows-hardware/drivers/install/installing-test-certificates

**Comment by paulrouget** [comment]
`FileNotFoundException`, but the file appears to exist. According to [this](https://docs.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting?redirectedfrom=MSDN) it could be:

- The package is unsigned.
- The publisher name doesn't match the signing certificate subject.
- The file:// prefix is missing or the package couldn't be found at the specified location.

**Comment by paulrouget** [comment]
```
3/2/2020 9:02:17 AM       603          Started deployment Add operation on a package with main parameter:              
                                       ServoApp_1.0.0.0_x64_Debug.msixbundle and Options: 0. See                       
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app           
                                       deployment issues.                                                              
3/2/2020 9:02:17 AM       164          The app bundle signature was validated for core content of the app bundle       
                                       published by CN=Allizom. App packages won't be validated until they are read.   
3/2/2020 9:02:17 AM       465          error 0x8007007B: Opening the package from location                             
                                       ServoApp_1.0.0.0_x64_Debug.msixbundle failed.                                   
3/2/2020 9:02:17 AM       403          error 0x8007007B: Failure to get staging session for: file:///C:/Users/task_1583
                                       133144/repo/support/hololens/AppPackages/ServoApp/ServoApp_1.0.0.0_Debug_Test/Se
                                       rvoApp_1.0.0.0_x64_Debug.msixbundle.                                            
3/2/2020 9:02:17 AM       404          AppX Deployment operation failed for package  with error 0x80073CF0. The        
                                       specific error text for this failure is: error 0x8007007B: Opening the package  
                                       from location ServoApp_1.0.0.0_x64_Debug.msixbundle failed.  
```

**Comment by paulrouget** [comment]
CI reports:

```
Thumbprint                                Subject                                                                      
----------                                -------                                                                      
39865B3C3FABE20A6EA79E7E76C662E5EFABE683  CN=Allizom                                                                   
   PSParentPath: Microsoft.PowerShell.Security\Certificate::CurrentUser\My
Thumbprint                                Subject                                                                      
----------                                -------                                                                      
39865B3C3FABE20A6EA79E7E76C662E5EFABE683  CN=Allizom                                                                   
   PSParentPath: Microsoft.PowerShell.Security\Certificate::LocalMachine\Root
Thumbprint                                Subject                                                                      
----------                                -------                                                                      
39865B3C3FABE20A6EA79E7E76C662E5EFABE683  CN=Allizom                                                                   
```

Which looks good to me. I have the exact same configuration locally.

**Comment by paulrouget** [comment]
Get-AuthenticodeSignature returns:

```
SignerCertificate                         Status                                 Path                                  
-----------------                         ------                                 ----                                  
                                          UnknownError                           ServoApp_1.0.0.0_x64_Debug.msixbundle 
```

Which is wrong. Locally I get:

```
SignerCertificate                         Status                                                        Path
-----------------                         ------                                                        ----
CA7DDD8EA130091D6EB5F0A752AE3B221901C5C2  Valid                                                         ServoApp_1.0.0.0_x64_Debug.msixbundle
```

**Comment by paulrouget** [comment]
Adding more logs to make sure sideloading is allowed, and getting more details about the signing error.

**Comment by paulrouget** [comment]
`Get-AuthenticodeSignature` on the msi says:

```
The form specified for the subject is not one supported or known by the specified trust provider
```

**Comment by paulrouget** [comment]
The msi looks valid here. Adding more logs to see if at least Windows can find the thumprint of the certificate in the package.

@bors-servo try=windows

Maybe sideloading is not allowed on the machine. Checking `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock` 
 from the registry returns `ERROR: The system was unable to find the specified registry key or value.`

Which, I believe, means that developer mode is not set.

On the other hand, if the dev mode was indeed not set, `Add-AppxPackage` would have said so.

Getting more logs, then maybe we can try to set dev mode.

**Comment by paulrouget** [comment]
Note:

To set the machine in dev mode see:

- `reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"`

We'll try that if that last logs do not shine any light on the issue.

**Comment by paulrouget** [comment]
I think the issue might be related to the fact that installing the dependencies only works if the Windows Store is available/enabled.

I'm seeing similar error messages in that issue: https://github.com/microsoft/terminal/issues/2369

**Comment by paulrouget** [comment]
Installing VCLibs.

@bors-servo try=windows

**Comment by paulrouget** [comment]
Ok - finally confirmed by trying to install the dependencies:

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFF, To install this application you need either a Windows 
developer license or a sideloading-enabled system.
```

@SimonSapin do you mind adding this command to the install script:

```
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"
```

**Comment by paulrouget** [comment]
@jdm Simon is on PTO, can you help with that ^

**Comment by jdm** [comment]
Looks like the new error is:
```
SignerCertificate      : 
TimeStamperCertificate : 
Status                 : UnknownError
StatusMessage          : The form specified for the subject is not one supported or known by the specified trust 
                         provider
Path                   : C:\Users\task_1583259487\repo\support\hololens\AppPackages\ServoApp\ServoApp_1.0.0.0_Debug_Tes
                         t\ServoApp_1.0.0.0_x64_Debug.msixbundle
SignatureType          : None
IsOSBinary             : False


Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF0, Package could not be opened.
error 0x8007007B: Opening the package from location ServoApp_1.0.0.0_x64_Debug.msixbundle failed.
NOTE: For additional information, look for [ActivityId] 2760e5f7-f188-0007-bff1-602788f1d501 in the Event Log or use 
the command line Get-AppxLog -ActivityID 2760e5f7-f188-0007-bff1-602788f1d501
At line:1 char:1
+ Add-AppxPackage -Path C:\Users\task_1583259487\repo\support\hololens\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (C:\Users\task_1...ebug.msixbundle:String) [Add-AppxPackage], FileNotFoundExc 
   eption
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

**Comment by paulrouget** [comment]
Skipping compilation. Just more logs:

@bors-servo try=windows

**Comment by jdm** [comment]
@paulrouget What did we learn from the most recent set of logs?

**Comment by paulrouget** [comment]
The CI doesn't appear to even be able to parse the final bundle and extract the certificate thumbprint. I've downloaded the bundle and tried locally, it finds the certificate. The logs tell me that my local configuration and the CI configuration are very similar (just the Windows version appears to differ), but I'm getting different results.

`Add-Appxpackage` fails with:

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF0, Package could not be opened.
error 0x8007007B: Opening the package from location ServoApp_1.0.0.0_x64_Debug.msixbundle failed.
NOTE: For additional information, look for [ActivityId] 9055b432-f109-0002-0fc8-559009f1d501 in the Event Log or use 
the command line Get-AppxLog -ActivityID 9055b432-f109-0002-0fc8-559009f1d501
At line:1 char:1
+ Add-AppxPackage -Path C:\Users\task_1583205089\repo\support\hololens\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (C:\Users\task_1...ebug.msixbundle:String) [Add-AppxPackage], FileNotFoundException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

Apparently "FileNotFoundException" is not always about the file being missing, and I doubled checked and the file exist and the path is right.

Running `Get-AuthenticodeSignature` shows that, indeed, Windows can't find any certificate thumbprint from the package:

```
SignerCertificate      : 
TimeStamperCertificate : 
Status                 : UnknownError
StatusMessage          : The form specified for the subject is not one supported or known by the specified trust provider
Path                   : C:\Users\task_1583205089\repo\support\hololens\AppPackages\ServoApp\ServoApp_1.0.0.0_Debug_Test\ServoApp_1.0.0.0_x64_Debug.msixbundle
SignatureType          : None
IsOSBinary             : False
```

Locally, on the same file, it works (not getting `UnkownError`).

Googling around leads me to think that it's an issue with the Windows store not being "activated". I don't really know what that means.

I believe the next step might be to try to understand what these commands actually do:

- https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-winapps/error-code-0x80073cf0-on-microsoft-store-windows/a19d7f60-2d34-4b78-b618-048d724b9f92
- https://github.com/microsoft/terminal/issues/2369#issuecomment-521789440

I'm planning to look at this again early next week.

**Comment by jdm** [comment]
Would it be worth landing the signing-related work separately from the UWP testing work? That would at least give us usable nightly builds once again, right?

**Comment by paulrouget** [comment]
> Would it be worth landing the signing-related work separately from the UWP testing work?

#25925

**Comment by paulrouget** [comment]
I'm getting suspicious that we are hitting a bug in Windows Server Build 14393 (2016):

- Using the `Add-AppDevPackage.ps1` script created by VS, we get an error: "The package or bundle is not digitally signed or its signature is corrupted" while it works on more recent versions of Windows
- https://stackoverflow.com/a/53770534 with a similar errors says that an update fixed it
- Build 14393 doesn't have all the App Install capabilities, see https://docs.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues

There are still more things I'd like to try, but I was wondering how difficult it would be to upgrade to a more recent build (at least 1809?).

**Comment by jdm** [comment]
I have pushed a new AMI that's based on Windows Server 2019 using the 1909 build. Retrying after fixing merge conflicts should yield new results.

**Comment by jdm** [comment]
I had to undeploy the changes in https://github.com/servo/taskcluster-config/pull/23.

**Comment by paulrouget** [comment]
Making progress!

With a recent version of Windows, we do not get the unknown error, the archive is considered valid and the certificate can be properly identified.

Installation does not work though because the dependencies can not be installed because the Microsoft Store is not available on Windows Server. But I think it's something we can work around.

Investigating…

**Comment by paulrouget** [comment]
I managed to install and run the application on the Windows Server 2019 instance without the dependencies issue (see last commit).

@jdm: can we disable the intermittent tests for a day, switch to 2019, and see how far we can go with this PR?

**Comment by paulrouget** [comment]
Disabled building. More logs.

@bors-servo try=windows

**Comment by paulrouget** [comment]
We made some good progress. I believe installation was successful.

Getting an error at startup:

```
+ start fxr://http://localhost:56012
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

Trying to figure out what went wrong.

**Comment by paulrouget** [comment]
Trying an alternative way to start the app, hoping for a more verbose output:

@bors-servo try=windows

**Comment by paulrouget** [comment]
I guess using `fxr://` doesn't work if the app has never ran before?
Trying to pass an argument with `Start-Process` now…

**Comment by paulrouget** [comment]
Installation and starting the process works, but getting a timeout. Maybe waiting 20 seconds is too short.

@bors-servo try=windows

**Comment by paulrouget** [comment]
Same script runs successfully on the RDP-connected machine, with a non-admin user. No timeout.

Here the HTTP request is never received by the server, even after 120 seconds.

- Timeout could be caused by Servo not being able to reach localhost, but `checknetisolation` is supposed to take care of that.
- Maybe the application shuts down early for any reason (we're not getting logs from Servo here)

The next step will be to make sure that the app is properly running. `Start-Process` is very silent. I'll need to figure out how to get some logs out of this.

**Comment by jdm** [comment]
One option to check if it's running would be to start the devtools on a specific port and see if you can connect to it.

**Comment by paulrouget** [comment]
Can't find the ServoApp process after calling Start-Process. There's a startup error I'm not catching.

**Comment by paulrouget** [comment]
Because it's an UWP app, it doesn't look like we can get back the process object out of Start-Process (option `-PassThru`).

@jdm at the moment, in the RDP instance, I create a tmp user, and run a few scripts. And it appears to work. But I'm not reproducing exactly what the TC scripts do. As in, I do not compile or run the task_cluster scripts. How do I setup the RDP instance in a way that it runs whatever TC is running?

**Comment by jdm** [comment]
I have not figured out a way to do that. TC relies on the geneic-worker service to orchestrate everything.

**Comment by paulrouget** [comment]
Going to change strategy: to iterate faster, I will make the task download a prebuild package and run a powershell script instead of python.

**Comment by paulrouget** [comment]
The app starts sandboxed, so we can't just run the exe. Getting the process info (stdout/stderr) out of `Start-Process` or `start` doesn't work because of this issue :https://github.com/PowerShell/PowerShell/issues/10996

**Comment by paulrouget** [comment]
Waiting on MS to get back to me, but I think the next step is to strip the app to its minimum (no servo, no dependency) and see if it launches.

**Comment by paulrouget** [comment]
> I think the next step is to strip the app to its minimum (no servo, no dependency) and see if it launches.

No - next step is to get the same logs that VS prints.

If, in the future, the UWP app doesn't run (which is the reason of this smoketest), we will want logs.

**Comment by paulrouget** [comment]
```
TimeCreated  : 3/27/2020 11:09:59 AM
ProviderName : Microsoft-Windows-DistributedCOM
Id           : 10010
Message      : The server MozillaFoundation.FirefoxReality_1.0.0.0_x64__k8h5m1m6r2tyc!App did not register with DCOM 
               within the required timeout.
```

**Comment by paulrouget** [comment]
I'm suspecting a security restriction on TC. I've contacted some people in the hope we'll get more details about how the temporary user is created.

**Comment by paulrouget** [comment]
Fascinating: running Servo from a RDP session, connected as the task user, it doesn't work. If I connected as admin, launch `cmd` as the task user, it works.

**Comment by paulrouget** [comment]
Same machine. Installing the app exactly the same way. 2 different accounts: one create by the task, one created manually replicating the TC user [creation script](https://github.com/taskcluster/taskcluster/blob/4181d042349a2c36efb1830da51096942a65a3ed/workers/generic-worker/runtime/runtime_windows.go#L21-L48), the user manually created can run the app. The user created by TC cannot.

**Comment by paulrouget** [comment]
This is how I manually create a user:

```
net user tmp1 "foo'bar43_A" /add /expires:never /passwordchg:no /y
wmic useraccount where name='tmp1' set passwordexpires=false
net localgroup "Remote Desktop Users" /add tmp1
```

This is the script I run:

```
$(Get-AppxPackage MozillaFoundation.FirefoxReality)| Remove-AppxPackage
$url = "https://community-tc.services.mozilla.com/api/queue/v1/task/a5TVjKpZTk-Df-uZcQFhxw/runs/0/artifacts/public/ServoApp_1.0.0.0_Debug_Test.zip"
Invoke-WebRequest -Uri $url -OutFile tc.zip
Expand-Archive tc.zip
Set-Location -Path tc\servo\
Add-AppxPackage -Path Dependencies\x64\Microsoft.VCLibs.x64.Debug.14.00.appx
Add-AppxPackage -Path ServoApp_1.0.0.0_x64_Debug.msixbundle
$fam = Get-AppxPackage MozillaFoundation.FirefoxReality | select -expandproperty PackageFamilyName
Start-Process shell:AppsFolder\$fam!App
```

With a task user, the app opens for a second and closes.
With a manually created user, the app stays open.

**Comment by paulrouget** [comment]
Maybe a clue: the user created by the task can't open the Windows menu.

**Comment by paulrouget** [comment]
Filed a taskcluster issue. Hopefully someone with a better understanding of TC & Windows can help: https://bugzilla.mozilla.org/show_bug.cgi?id=1627906

**Pull request closed without merging**
