### PR TITLE
Update WR, and copy new shaders.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13843)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* infra

**Comment by KiChjang** [comment]
```

---- gecko_bindings::structs::bindgen_test_layout_nsIDocument stdout ----
	thread 'gecko_bindings::structs::bindgen_test_layout_nsIDocument' panicked at 'assertion failed: `(left == right)` (left: `952`, right: `944`)', /home/servo/buildbot/slave/linux-rel-css/build/components/style/gecko_bindings/structs_release.rs:3165
stack backtrace:
   1:     0x7fbaa9094f39 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x7fbaa9098eac - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x7fbaa9098084 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x7fbaa90987e8 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x7fbaa9098642 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x7fbaa90985b0 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x7fbaa9054797 - style::gecko_bindings::structs::bindgen_test_layout_nsIDocument::ha6b566dd1eada7ac
   8:     0x7fbaa905f98b - _<F as alloc..boxed..FnBox<A>>::call_box::hd5b7ed3c754c2638
   9:     0x7fbaa9058c4f - std::panicking::try::do_call::h63a911edf59441a1
  10:     0x7fbaa90a0996 - __rust_maybe_catch_panic
  11:     0x7fbaa905f34a - _<F as alloc..boxed..FnBox<A>>::call_box::h3db4d78fb37007ad
  12:     0x7fbaa9096d92 - std::sys::thread::Thread::new::thread_start::h4c0ad33b336bc6ea
  13:     0x7fbaa8a02183 - start_thread
  14:     0x7fbaa851937c - clone
  15:                0x0 - <unknown>
```
This shouldn't happen with this PR, what's going on?

**Comment by KiChjang** [comment]
@bors-servo retry
* #13847

**Comment by KiChjang** [comment]
```
Tests with unexpected results:
  ▶ TIMEOUT [expected CRASH] /webgl/conformance-1.0.3/conformance/more/functions/uniformiBadArgs.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ Unexpected WebGL error: 0x502 (1282) (thread <unnamed>, at /Users/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/master/webrender_traits/src/webgl.rs:361)
  │ stack backtrace:
  │    0:        0x10787236e - backtrace::backtrace::trace::h6ac07ced1b846a59
  │    1:        0x10787265c - backtrace::capture::Backtrace::new::h1d3339ed08c7f861
  │    2:        0x106475a54 - servo::main::_{{closure}}::hce6009c73746ec98
  │    3:        0x107d30403 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
  │    4:        0x107d302d4 - std::panicking::begin_panic::hf6c488cee66e7f17
  │    5:        0x107d301f2 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
  │    6:        0x10792a1f3 - webrender::internal_types::GLContextWrapper::apply_command::hb03853e445f7712c
  │    7:        0x107930aab - webrender::render_backend::RenderBackend::run::h6ff7e190567c35e0
  │    8:        0x1078ff012 - std::panicking::try::do_call::heddaf6f30dc507a3
  │    9:        0x107d3142a - __rust_maybe_catch_panic
  │   10:        0x107909b26 - _<F as alloc..boxed..FnBox<A>>::call_box::h65068d2bdde4e620
  │   11:        0x107d2f334 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  │   12:     0x7fff93411059 - _pthread_body
  │   13:     0x7fff93410fd6 - _pthread_start
  │ ERROR:servo: Unexpected WebGL error: 0x502 (1282)
  │ Pipeline failed in hard-fail mode.  Crashing!
  │ thread panicked while processing panic. aborting.
  │ servo(15884,0x7fff7b2d2300) malloc: *** error for object 0x7fa460d3d3b8: incorrect checksum for freed object - object was probably modified after being freed.
  │ *** set a breakpoint in malloc_error_break to debug
  │ thread panicked while processing panic. aborting.
  └ thread panicked while processing panic. aborting.
```

**Comment by emilio** [comment]
@bors-servo: retry
 * https://github.com/servo/servo/issues/13861

**Comment by emilio** [comment]
@bors-servo: p=1

 * Blocking other PRs

**Pull request merged**
