### PR TITLE
Support OffscreenCanvas as CanvasImageSource

### LINKED ISSUE #24269: Support OffscreenCanvas as CanvasImageSource
Code:
* https://github.com/servo/servo/blob/4fe8238b14d535f7ca94a36effda06624b73ecbe/components/script/dom/webidls/CanvasRenderingContext2D.webidl#L15
* https://github.com/servo/servo/blob/4fe8238b14d535f7ca94a36effda06624b73ecbe/components/script/dom/canvasrenderingcontext2d.rs#L335-L350
* https://github.com/servo/servo/blob/4fe8238b14d535f7ca94a36effda06624b73ecbe/components/script/dom/canvasrenderingcontext2d.rs#L359-L419

Tests:
* `./mach test-wpt tests/wpt/web-platform-tests/offscreen-canvas/drawing-images-to-the-canvas` should report [newly passing tests](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations)

We'll want to generalize draw_html_canvas_element to support offscreen canvases as well, since the majority of the code is applicable to both. An enum argument is probably the best way to do that.

### PR DESCRIPTION
**Pull request by bblanke**
Added methods to canvas_data to support drawing an offscreen canvas onto another canvas
Bug fix: Swapped OffscreenCanvas width and height parameters to match Mozilla spec
Tests: Updated metadata for 866 tests

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24269 (GitHub issue number if applicable)

- [x] These changes do not require tests because they are covered by existing tests

### CODE REVIEW

**Comment by bblanke** [comment]
Is there any way to see more fine-grained details of the failure in TC? I don't see build or test errors on my local machine (though test-tidy through an error saying the manifest needed updating, but then continued successfully).

Also, now that I've updated the manifest, can I just git commit --amend and force push?

**Comment by bblanke** [comment]
Nevermind; I read the docs :)

**Comment by jdm** [comment]
The try reported two missing changes:
```
  â–¶ Unexpected subtest result in /offscreen-canvas/text/2d.text.draw.fill.maxWidth.fontface.worker.html:
  â”” PASS [expected FAIL] fillText works on @font-face fonts


  â–¶ Unexpected subtest result in /offscreen-canvas/text/2d.text.draw.fill.maxWidth.fontface.html:
  â”” PASS [expected FAIL] fillText works on @font-face fonts
```

**Review by jdm — CHANGES_REQUESTED** [review]

**Comment by bblanke** [comment]
Fixed!

**Comment by jdm** [comment]
@bors-servo retry
* #25112

**Comment by CYBAI** [comment]
@bors-servo retry

- #25113

**Pull request merged**
