### PR TITLE
Event src element

### LINKED ISSUE #22880: Implement historical srcElement attribute for Event interface
https://dom.spec.whatwg.org/#event contains a `srcElement` attribute which should behave exactly the same as the `target` attribute per [the spec](https://dom.spec.whatwg.org/#dom-event-srcelement).

Code: `components/script/dom/webidls/Event.webidl`, `components/script/dom/event.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/dom/event` and then [update the expected results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations).

### PR DESCRIPTION
**Pull request by stephenmuss**
This builds on top of the work done in https://github.com/servo/servo/pull/22918

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22880
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24144)

### CODE REVIEW

**Comment by jdm** [comment]
Looks like a few more successful test results need to have their ini files updated.

**Comment by jdm** [comment]
```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: attribute srcElement", 
    "test": "/dom/idlharness.any.worker.html", 
    "line": 102898, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: new Event(\"foo\") must inherit property \"srcElement\" with the proper type", 
    "test": "/dom/idlharness.any.worker.html", 
    "line": 102925, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: new CustomEvent(\"foo\") must inherit property \"srcElement\" with the proper type", 
    "test": "/dom/idlharness.any.worker.html", 
    "line": 102961, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: attribute srcElement", 
    "test": "/dom/idlharness.window.html?exclude=Node", 
    "line": 146796, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: document.createEvent(\"Event\") must inherit property \"srcElement\" with the proper type", 
    "test": "/dom/idlharness.window.html?exclude=Node", 
    "line": 146823, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: new Event(\"foo\") must inherit property \"srcElement\" with the proper type", 
    "test": "/dom/idlharness.window.html?exclude=Node", 
    "line": 146848, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Event interface: new CustomEvent(\"foo\") must inherit property \"srcElement\" with the proper type", 
    "test": "/dom/idlharness.window.html?exclude=Node", 
    "line": 146884, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

**Comment by stephenmuss** [comment]
Sorry about the missed passing tests @jdm. Should be ok now.

**Comment by stephenmuss** [comment]
Looks like that wasn't everything 😞 
Think I have a better idea how to verify now. I'll be back with an update shortly.

**Comment by jdm** [comment]
Hum, I would be very surprised if these changes actually caused those tests to change their result. They might be intermittent errors.
@bors-servo try=wpt

**Comment by jdm** [comment]
Yep, looking closely those failures are completely unrelated to this change.

**Comment by stephenmuss** [comment]
Ok, that's good. Once I started digging I noticed the errors were quite different than previously.

**Comment by stephenmuss** [comment]
Looks like retry didn't kick off?

**Pull request merged**
