### PR TITLE
layout: Implement `text-align: justify` and `text-justify` per

### LINKED ISSUE #213: Implement justified text with 'text-align'
This seems to require implementation of `letter-spacing` and/or `word-spacing`.

Spec:
* http://dev.w3.org/csswg/css3-writing-modes/#text-orientation0
* http://www.w3.org/TR/CSS2/text.html#propdef-text-align

### PR DESCRIPTION
**Pull request by pcwalton**
CSS-TEXT-3 § 7.3.

`text-justify: distribute` is not supported.

The behavior of `text-justify: none` does not seem to match what Firefox
and Chrome do, but it seems to match the spec.

Closes #213.

r? @mbrubeck

### CODE REVIEW

**Comment by jdm** [comment]
Is there anything of #1638 that we can use?

**Comment by pcwalton** [comment]
@jdm I don't think so, other than the test case. Most of the logic of that PR basically duplicates this one, although this one also adjusts the glyph advances to account for hyphenation (which seems more correct to me, although perhaps it isn't necessary). That PR is also based on the inline layout code before `word-break`, `overflow-wrap`, and `text-overflow` went in, which is significantly different; any attempt to salvage it would basically constitute a rewrite of much of it.

**Comment by mbrubeck** [comment]
Some minor questions/suggestions on Critic.

**Comment by pcwalton** [comment]
Issues addressed. re-r? @mbrubeck

**Comment by mbrubeck** [comment]
r+, can squash and land.

**Comment by jdm** [comment]
```
9:02.29 TEST_START: Thread-TestrunnerManager-5 (u'/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped.html', u'==', u'/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped-ref.html')
 9:02.58 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) Full command: /home/servo/buildbot/slave/linux2/build/components/servo/target/servo --cpu --hard-fail --exit --output=/tmp/tmpT9Kvv_/a6d48fd2-7e21-452f-8c51-c43e7c84e8cc http://localhost:8000/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped.html
(pid:3524) "thread 'LayoutWorker worker 1/4' panicked at 'index 63 and/or 68 in `a > ב >>>                                                  ג > d... ` do not lie on character boundary', /home/larsberg/rust/src/libcore/str/mod.rs:1244"
 9:02.58 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "stack backtrace:"
 9:02.75 TEST_END: Thread-TestrunnerManager-6 FAIL
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "   1:     0x7f083c801b90 - sys::backtrace::write::h2d33c3c7ed646e34Czt"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "   2:     0x7f083c816ca0 - failure::on_fail::h973a98f343057a4eaPz"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "   3:     0x7f083c7e5090 - rt::unwind::begin_unwind_inner::h1ff3dff6fb4b069d2tz"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "   4:     0x7f083c7e5a60 - rt::unwind::begin_unwind_fmt::hcf879ec796a75e03zsz"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "   5:     0x7f083c816bc0 - rust_begin_unwind"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "   6:     0x7f083c843d50 - panicking::panic_fmt::h0e234d8452ec3c73pfl"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "   7:     0x7f083c8477c0 - str::slice_error_fail::h2846c77bfe2af10610s"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "   8:     0x7f083b29bee0 - str::str.StrExt::slice::h526a0f0ab54d4656t8s"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "   9:     0x7f083b29be10 - str::StrExt::slice::h11012849033361702004"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  10:     0x7f083b297fe0 - fragment::Fragment::calculate_split_position_using_breaking_strategy::h3326921792250121216"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  11:     0x7f083b297ac0 - fragment::Fragment::calculate_split_position::h8a053b4cb1302211wXi"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  12:     0x7f083b360f20 - inline::LineBreaker::append_fragment_to_line_if_possible::h670ad39a15641829wam"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  13:     0x7f083b35e6b0 - inline::LineBreaker::reflow_fragments::h10410425506683268625"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  14:     0x7f083b35d760 - inline::LineBreaker::scan_for_lines::hafc9faf0d4c6a413IEl"
 9:02.76 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  15:     0x7f083b1e2770 - inline::InlineFlow.Flow::assign_block_size::h395ce802ef37bb61VSm"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  16:     0x7f083b372860 - traversal::AssignBSizesAndStoreOverflow<'a>.PostorderFlowTraversal::process::h4ada01b448e5a770d8q"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  17:     0x7f083b3724b0 - parallel::ParallelPostorderFlowTraversal::run_parallel::h4682296339473026798"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  18:     0x7f083b36feb0 - parallel::assign_block_sizes_and_store_overflow::h30f75ca4c2d64d6ceUn"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  19:     0x7f083b36f730 - parallel::AssignISizes<'a>.ParallelPreorderFlowTraversal::run_parallel::h66db6a8aeae06058bQn"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  20:     0x7f083b36fe00 - parallel::assign_inline_sizes::h6dad8b766f058d9awTn"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  21:     0x7f083b31b870 - workqueue::WorkerThread<QueueData, WorkData>::start::h11029279781400536087"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  22:     0x7f083b31b6c0 - workqueue::WorkQueue<QueueData, WorkData>::new::unboxed_closure.29740"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  23:     0x7f083b31b330 - task::spawn_named::unboxed_closure.29733"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  24:     0x7f083b31b200 - thunk::Thunk<(*, R>::new::unboxed_closure.29729"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  25:     0x7f083b31b080 - thunk::F.Invoke<A, R>::invoke::h7714793004502108553"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  26:     0x7f083b25b360 - thunk::Thunk<A, R>::invoke::h1016083932946779603"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  27:     0x7f083b25c0a0 - thread::Builder::spawn_inner::unboxed_closure.26720"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  28:     0x7f083b25c030 - rt::unwind::try::try_fn::__rust_abi::h10194110208251398120"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  29:     0x7f083b25bff0 - rt::unwind::try::try_fn::h10194110208251398120"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  30:     0x7f083c821400 - rust_try_inner"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  31:     0x7f083c8213f0 - rust_try"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  32:     0x7f083b25b400 - rt::unwind::try::h9706511056470083512"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  33:     0x7f083b259e10 - thread::Builder::spawn_inner::unboxed_closure.26616"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  34:     0x7f083b25d180 - thunk::Thunk<(*, R>::new::unboxed_closure.26743"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  35:     0x7f083b25d030 - thunk::F.Invoke<A, R>::invoke::h13287614453333291924"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  36:     0x7f083c805d30 - sys::thread::thread_start::hbedaacef8efea660qrw"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  37:     0x7f083a9f30c0 - start_thread"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  38:     0x7f0839efaf89 - __clone"
 9:02.77 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:3524) "  39:                0x0 - <unknown>"
 9:13.44 TEST_END: Thread-TestrunnerManager-5 TIMEOUT, expected FAIL
```
```
test linebreak_inline_span_a.html == linebreak_inline_span_b.html ... FAILED
```

**Comment by jdm** [comment]
```
 2:04.82 TEST_START: Thread-TestrunnerManager-4 /dom/traversal/TreeWalker-currentNode.html
 2:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) Full command: /Users/servo/buildbot/slave/mac1/build/components/servo/target/servo --cpu --hard-fail -z http://localhost:8000/dom/traversal/TreeWalker-currentNode.html
(pid:53738) "thread 'LayoutWorker worker 4/6' panicked at 'un-normalized split result', inline.rs:622"
 2:04.98 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "stack backtrace:"
 2:04.99 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "   1:        0x1079e4375 - sys::backtrace::write::habdc320444a07b69lCt"
 2:04.99 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "   2:        0x1079f9149 - failure::on_fail::h518a2e1bba17c9c90Hz"
 2:04.99 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "   3:        0x1079c884a - rt::unwind::begin_unwind_inner::h85e4f9f71209d373Qpz"
 2:04.99 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "   4:        0x10669d8ed - rt::unwind::begin_unwind::h265305328139259614"
 2:04.99 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "   5:        0x10688f9d9 - inline::LineBreaker::append_fragment_to_line_if_possible::hc39eda65aaf1d417wam"
 2:04.99 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "   6:        0x10688c0af - inline::LineBreaker::reflow_fragments::h14157098575044911859"
 2:04.99 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "   7:        0x10688b302 - inline::LineBreaker::scan_for_lines::h5e2c460c8a141985IEl"
 2:04.99 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "   8:        0x106710817 - inline::InlineFlow.Flow::assign_block_size::ha64036fd549e6c51VSm"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "   9:        0x10689ff57 - traversal::AssignBSizesAndStoreOverflow<'a>.PostorderFlowTraversal::process::hb8e4e70c025bc26ad8q"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  10:        0x10689fbe1 - parallel::ParallelPostorderFlowTraversal::run_parallel::h4183159357836460945"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  11:        0x10689d57e - parallel::assign_block_sizes_and_store_overflow::h73353025c643dce9eUn"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  12:        0x10689cfe5 - parallel::AssignISizes<'a>.ParallelPreorderFlowTraversal::run_parallel::h67d40c4c61b2c7acbQn"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  13:        0x10689d4ce - parallel::assign_inline_sizes::hc1d606f46552ad73wTn"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  14:        0x1068494d0 - workqueue::WorkerThread<QueueData, WorkData>::start::h13953068100590035187"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  15:        0x106848da3 - workqueue::WorkQueue<QueueData, WorkData>::new::unboxed_closure.29766"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  16:        0x1068489c1 - task::spawn_named::unboxed_closure.29759"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  17:        0x106848894 - thunk::Thunk<(*, R>::new::unboxed_closure.29755"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  18:        0x10684875d - thunk::F.Invoke<A, R>::invoke::h2941064529486351787"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  19:        0x1067888c1 - thunk::Thunk<A, R>::invoke::h17519471995157628435"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  20:        0x10678960a - thread::Builder::spawn_inner::unboxed_closure.26750"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  21:        0x10678958f - rt::unwind::try::try_fn::__rust_abi::h10271911819457074663"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  22:        0x10678952a - rt::unwind::try::try_fn::h10271911819457074663"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  23:        0x1079fac19 - rust_try_inner"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  24:        0x1079fac06 - rust_try"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  25:        0x106788a10 - rt::unwind::try::h9435424722377060331"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  26:        0x10678763d - thread::Builder::spawn_inner::unboxed_closure.26645"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  27:        0x10678a739 - thunk::Thunk<(*, R>::new::unboxed_closure.26773"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  28:        0x10678a621 - thunk::F.Invoke<A, R>::invoke::h16423848229469789720"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  29:        0x1079e8204 - sys::thread::thread_start::h1ff6fbf82b65b913drw"
 2:05.01 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:53738) "  30:     0x7fff8d83a772 - _pthread_start"
 2:19.83 TEST_END: Thread-TestrunnerManager-4 TIMEOUT, expected OK
```

**Comment by pcwalton** [comment]
Tests should be fixed now. Going to ask for review again, since this version of the patch redoes the way whitespace stripping worked. r? @mbrubeck

**Pull request merged**
