### PR TITLE
script: Fix remaining bugs from Range.deleteContents

### PR DESCRIPTION
**Pull request by emilio**
This makes all the `Range.deleteContents` tests pass.

I changed some `try!()`s for `unwraps()` because those calls are actually infallible.

r? @nox

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9795)

### CODE REVIEW

**Comment by nox** [comment]
I was going to say something about making a new iterator, but then I realised it is also used in nodeiterator.rs.

@bors-servo r+

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9795#-:-KBcvhtN0tnPV1cpoZkX:-617737820)*

**Comment by KiChjang** [comment]
@bors-servo retry
* #8120

**Pull request merged**
