### PR TITLE
Bug 1398957 - Make LRUCache use a linked list to reduce memmoves.

### PR DESCRIPTION
**Pull request by mbrubeck**
https://bugzilla.mozilla.org/show_bug.cgi?id=1398957

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18466)

### CODE REVIEW

**Comment by bholley** [comment]
This looks great at a high level, thanks! I'm really swamped this week, so I'll defer the careful review to Simon.

r? @SimonSapin

**Comment by SimonSapin** [comment]
r+ with `&mut self` changed to `&self` in `iter`.

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/cache.rs, line 85 at r1](https://reviewable.io:443/reviews/servo/servo/18466#-Ku0K4rInWkmHr9uW1_m:-Ku0K4rInWkmHr9uW1_n:bkw02h8) ([raw file](https://github.com/servo/servo/blob/34460ac0f66a8413105999f2a1ed25193566d45c/components/style/cache.rs#L85)):*
> ```Rust
>     /// Iterate over the contents of this cache, from more to less recently
>     /// used.
>     pub fn iter(&mut self) -> LRUCacheIterator<T, A> {
> ```

Why `&mut self` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18466#-:-Ku0UrPEjNY_ZmDP0o1z:b-5xpyy0)*

**Pull request merged**
