### PR TITLE
removing unnecessary clones

### LINKED ISSUE #7485: Unnecessary clones in HttpRequestFactory::create
In `Request::with_connector`, we don't need to clone `url` and `method` as they are not used again.

Code: components/net/http_loader.rs

### PR DESCRIPTION
**Pull request by psdh**
Fixes #7485

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7489)

### CODE REVIEW

**Comment by psdh** [comment]
@jdm I think `url` is used in line 203, hence the clone.

**Comment by Ms2ger** [comment]
You're correct. You could remove the clones on lines 203/212 though.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for the PR!

**Comment by psdh** [comment]
no squashing, that's new :)

**Pull request merged**
