### PR TITLE
Have shorthand parsing functions not return Option for their longhands

### PR DESCRIPTION
**Pull request by upsuper**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15761)

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
r=me

**Comment by jdm** [comment]
```
 ▶ Unexpected subtest result in /cssom/CSSStyleRule.html:
  │ FAIL [expected PASS] CSSStyleRule: style property
  │   → assert_equals: expected "1px solid" but got "1px solid currentColor"
  │ 
  │ @http://web-platform.test:8000/cssom/CSSStyleRule.html:22:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  └ @http://web-platform.test:8000/cssom/CSSStyleRule.html:13:3
```

**Comment by canaltinova** [comment]
Btw,  after this PR we are unable to determine which sub-longhands are specified in a shorthand, right?
I once filed an issue about what to do with the unspecified sub-longhand serialization(#14832) because some shorthands were printing unspecified sub-longhands and some shorthands weren't. I guess now all of them are printing initial values. If so, is it a right approach?

**Pull request merged**
