### PR TITLE
Update mozjs to 88

### PR DESCRIPTION
**Pull request by sagudev**
https://github.com/servo/rust-mozjs/pull/541

### CODE REVIEW

**Comment by sagudev** [comment]
@jdm could you ran bors try

**Comment by sagudev** [comment]
> 
> 
> ☀️ Test successful - [status-taskcluster](https://community-tc.services.mozilla.com/tasks/groups/V-nrSpcHQhqnGO8nQh51gw)
> State: approved= try=True

Note: Windows build on GitHub Actions is still running. Weird.

**Comment by sagudev** [comment]
Depends on: https://github.com/servo/webxr/pull/197

I have also prepared updating bindgen for style component in other branch. Will probably merge in this branch later, because all bindgen updates needs to come simultaneously.

**Review by jdm — APPROVED** [review]

**Comment by sagudev** [comment]
Ready for merge!

**Pull request merged**
