### PR TITLE
Switch to external deque crate

### LINKED ISSUE #9539: Switch to the deque crate from crates.io
It may have better performance via more precise memory ordering semantics, and it would let us remove about 400 lines of highly unsafe code from the tree.

### PR DESCRIPTION
**Pull request by gmorenz**
Fixes #9539

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9679)

### CODE REVIEW

**Comment by KiChjang** [comment]
@gmorenz Please communicate with us before working on an issue. I really don't want any duplicated efforts from contributors.

**Comment by gmorenz** [comment]
@KiChjang Sorry about that. I hope this didn't waste anyones time.

**Comment by jdm** [comment]
Note that we'll need to update ports/cef/Cargo.lock and ports/gonk/Cargo.lock as well. This can be done with `./mach build-cef` and `GONKDIR=/tmp ./mach build-gonk`, and cancelling them both when the actual "Compiling" lines start appearing.

**Comment by gmorenz** [comment]
Also `ports/geckolib/Cargo.lock`?

**Comment by jdm** [comment]
I don't think that lock file includes the layout crate.

**Comment by gmorenz** [comment]
It doesn't, but it includes the util crate, which is what I added a dependency to.

**Comment by nox** [comment]
> Note that we'll need to update ports/cef/Cargo.lock and ports/gonk/Cargo.lock as well. This can be done with ./mach build-cef and GONKDIR=/tmp ./mach build-gonk, and cancelling them both when the actual "Compiling" lines start appearing.

Or just do `./mach update-cargo -p util` instead.

**Comment by jdm** [comment]
@bors-servo: retry
* #8120

**Comment by mbrubeck** [comment]
@bors-servo retry

* #9746

**Pull request merged**
