### PR TITLE
Implement new WebGL interfaces and methods

### PR DESCRIPTION
**Pull request by emilio**
This commit implements:
- WebGLFramebuffer
- WebGLRenderbuffer
- WebGLTexture

And adds the following methods to `WebGLRenderingContext`:
- create{Texture,Framebuffer,Renderbuffer}
- bind{Texture,Framebuffer,Renderbuffer}
- destroy{Buffer,Texture,Framebuffer,Renderbuffer}

Fixes:
- WebGLUniform location shouldn't inherit from WebGLObject.

Known Issues:
- WebGL objects have to be destroyed on drop, we may want to keep a reference to the context, or maybe a clone of the renderer to achieve this

Also refactors a huge part of the current implementation, to allow
failing on creation of different WebGL objects.

Blocked on https://github.com/servo/gleam/pull/22

A reftest for most of the added functionality is not doable right now,
we need a few more functions in order to upload a texture, for example.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6293)

### CODE REVIEW

**Comment by nox** [comment]
Are there any interfaces extending WebGLObject that won't have a get_id() helper? If not, could it be moved there?

-S-awaiting-review +S-awaiting-answer +S-needs-code-changes 

---

Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- components/canvas/lib.rs @ r1
- components/canvas/webgl_paint_task.rs @ r1
- components/canvas_traits/lib.rs @ r1
- components/script/dom/mod.rs @ r1
- components/script/dom/webglframebuffer.rs @ r1
- components/script/dom/webglrenderbuffer.rs @ r1
- components/script/dom/webglrenderingcontext.rs @ r1
- components/script/dom/webgltexture.rs @ r1
- components/script/dom/webgluniformlocation.rs @ r1
- components/script/dom/webidls/WebGLFramebuffer.webidl @ r1
- components/script/dom/webidls/WebGLRenderbuffer.webidl @ r1
- components/script/dom/webidls/WebGLRenderingContext.webidl @ r1
- components/script/dom/webidls/WebGLTexture.webidl @ r1

---

<sup>**[components/canvas/webgl_paint_task.rs, line 258 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6293#-Jr4wLBS9Vcg-Axxdyyb)** ([raw file](https://github.com/servo/servo/blob/c8638d05bd0082ac36c23be94687163e09ab2203/components/canvas/webgl_paint_task.rs#L258)):</sup>
"compliant".

Any harm in not including it, if it's not spec-compliant?

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6293#-Jr3Svq5EDY1H67b6TSn)** ([raw file](https://github.com/servo/servo/blob/c8638d05bd0082ac36c23be94687163e09ab2203/components/script/dom/webglrenderingcontext.rs#L139)):</sup>
Is there more harm in not supporting it at all than making it return 0 unconditionally?

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 402 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6293#-Jr5-FuIRkqmVklZwK7A)** ([raw file](https://github.com/servo/servo/blob/c8638d05bd0082ac36c23be94687163e09ab2203/components/script/dom/webglrenderingcontext.rs#L402)):</sup>
This looks like a gratuitous rewrite, I prefer the version without potentially-panicking calls (the unwrappings)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6293)

**Comment by ecoal95** [comment]
Actually not, there's no interface extending `WebGLObject` that doesn't implement a method like that, but at this point I'm a bit sceptical about it, I don't know why neither Firefox/Chromium expose it to the window, and I'd prefer not to add functionality there until I discover why.

**Comment by ecoal95** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/canvas/webgl_paint_task.rs, line 258 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6293#-Jr4wLBS9Vcg-Axxdyyb)** ([raw file](https://github.com/servo/servo/blob/c8638d05bd0082ac36c23be94687163e09ab2203/components/canvas/webgl_paint_task.rs#L258)):</sup>
This call is not *totally* spec compliant (yet), since we should ensure all the shaders conform with GLES Shading Language 1.00. Right now we don't do that check, but I think removing shaders from our WebGL implementation, even if it's temporary, is a too high price.

I'd prefer to keep them, and add the sanity check after it, instead of removing the shader calls and rewrite them again later. 

```
 A WebGL implementation must only accept shaders which conform to The OpenGL ES Shading Language, Version 1.00 [GLES20GLSL], and which do not exceed the minimum functionality mandated in Sections 4 and 5 of Appendix A. In particular: 
```

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6293#-Jr3Svq5EDY1H67b6TSn)** ([raw file](https://github.com/servo/servo/blob/c8638d05bd0082ac36c23be94687163e09ab2203/components/script/dom/webglrenderingcontext.rs#L139)):</sup>
Well, that call is spec'd, and is totally legal not to have extension support, but I'll remove it if you want/

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 402 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6293#-Jr5-FuIRkqmVklZwK7A)** ([raw file](https://github.com/servo/servo/blob/c8638d05bd0082ac36c23be94687163e09ab2203/components/script/dom/webglrenderingcontext.rs#L402)):</sup>
We check before and early return if any of those is `None`, it's safe to call `unwrap` there. I'll change it if you want, but I think it's cleaner this way.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6293)

**Comment by nox** [comment]
I didn't mean exposing it as a DOM method, but as a helper on WebGLObject directly, to avoid duplicating the field and the Rust method everywhere.

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 402 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6293#-Jr5-FuIRkqmVklZwK7A)** ([raw file](https://github.com/servo/servo/blob/c8638d05bd0082ac36c23be94687163e09ab2203/components/script/dom/webglrenderingcontext.rs#L402)):</sup>
The code flow is made less obvious and doesn't follows the shape of the Option type anymore. Pinging @Manishearth to decide because he like to discuss bikeshed paint.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6293)

**Comment by ecoal95** [comment]
Yes, I supposed so, but what I was trying to say (sorry), is that gecko for example doesn't even have the interface (they have a base class for them, but not a DOM binding).

Anyways: The WebGL2 spec does spec some objects without `id`, like queries, so I think that even if now it could make sense to move it there, that change will have to be rolled back in the future.

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6293)

**Comment by ecoal95** [comment]
I updated the tests and corrected the typo :)

**Comment by SimonSapin** [comment]
Review status: 12 of 14 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 402 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6293#-Jr5-FuIRkqmVklZwK7A)** ([raw file](https://github.com/servo/servo/blob/c8638d05bd0082ac36c23be94687163e09ab2203/components/script/dom/webglrenderingcontext.rs#L402)):</sup>
I also prefer the previous code, fwiw. Another option is to use the [`unwrap_or_return!`](https://github.com/reem/rust-mac/blob/6316d3f4663756180fd236b126a84e245e978765/src/lib.rs#L33-L35) macro from the `mac` crate. (That crate is already used by some of Servo’s dependencies.)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6293)

**Comment by nox** [comment]
Perfect, no other tests because we need to integrate Khronos test suite, right?

-S-awaiting-answer -S-awaiting-review 

Update the bikeshed snippet and it can be merged.

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/canvas/webgl_paint_task.rs @ r2
- tests/wpt/mozilla/tests/mozilla/interfaces.html @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6293)

**Comment by ecoal95** [comment]
Reverted the changes then :P

You're right, I can't do reftests with this until I implement the texParameter* set of functions, and making simple html tests when we have to integrate more serious tests is not worth it I think.

**Comment by ecoal95** [comment]
By the way it's still blocked on https://github.com/servo/gleam/pull/22, I don't know if you can review it.

**Comment by nox** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/script/dom/webglrenderingcontext.rs @ r3

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6293)

**Comment by nox** [comment]
#6305

**Comment by nox** [comment]
@bors-servo: r+

-S-blocked-on-external 

#6305 got merged.

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6293)

**Comment by ecoal95** [comment]
@nox Thanks for taking the time to update gleam and merge this, I'm in my final exams period so I couldn't take the time :)

**Comment by nox** [comment]
@ecoal95 Thanks for your contribution, I hope you'll have good marks. :)

**Pull request merged**
