### PR TITLE
Remove Rc<T> usage from Range

### PR DESCRIPTION
**Pull request by nox**
I initially used this to correctly handle ranges when their respective containers
are mutated, to get weak references of Range objects. I now realise that the weak
references should be handled at a lower level, closer to the JS-managed object.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8091)

### CODE REVIEW

**Comment by eefriedman** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 123 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8091#-K1FugfB-FuFlwkC6KWy)** ([raw file](https://github.com/servo/servo/blob/a4cd9fb76ec3cd22af72e91f9df91e4dba6fd639/components/script/dom/range.rs#L123)):</sup>
Are you sure `self.start > self.end` is correct, as opposed to `!(self.start <= self.end)`?  (I would hope that the WPT tests cover this... but please add a test if they don't.)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8091)

**Comment by jdm** [comment]
@eefriedman is reviewing this PR.

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 123 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8091#-K1FugfB-FuFlwkC6KWy)** ([raw file](https://github.com/servo/servo/blob/a4cd9fb76ec3cd22af72e91f9df91e4dba6fd639/components/script/dom/range.rs#L123)):</sup>
Why would one be correct and not the other? I'm not sure I understand.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8091)

**Comment by eefriedman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 123 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8091#-K1FugfB-FuFlwkC6KWy)** ([raw file](https://github.com/servo/servo/blob/a4cd9fb76ec3cd22af72e91f9df91e4dba6fd639/components/script/dom/range.rs#L123)):</sup>
`self.start > self.end` is equivalent to `self.start.partial_cmp(self.end) == Some(Ordering::Greater)`.  The original code checks for `None | Some(Ordering::Greater)`.  The difference is relevant if the two nodes aren't part of the same tree.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8091)

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 123 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8091#-K1FugfB-FuFlwkC6KWy)** ([raw file](https://github.com/servo/servo/blob/a4cd9fb76ec3cd22af72e91f9df91e4dba6fd639/components/script/dom/range.rs#L123)):</sup>
Oh, good catch. I'll check that the tests fail and will fix the code accordingly.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8091)

**Comment by nox** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/range.rs, line 123 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8091#-K1FugfB-FuFlwkC6KWy)** ([raw file](https://github.com/servo/servo/blob/a4cd9fb76ec3cd22af72e91f9df91e4dba6fd639/components/script/dom/range.rs#L123)):</sup>
Half the tests in `/dom/ranges/Range-set.html` were failing without this  change, indeed.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8091)

**Comment by eefriedman** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/range.rs, line 124 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8091#-K1H0rs2k9_cRu0MttX8)** ([raw file](https://github.com/servo/servo/blob/f3a8e749cef3d86fc2437ff4fa3e0b7f5e781b6e/components/script/dom/range.rs#L124)):</sup>
The comment is confusing.  If you think the algorithm needs to be described, say a bit more, like "if the current end is before the start or in another document, set the end to the same point as the start".  If you think `!(a<=b)` needs to be clarified, just change it to call `bp_position` or `partial_cmp` directly.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8091)

**Comment by nox** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/range.rs, line 124 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8091#-K1H0rs2k9_cRu0MttX8)** ([raw file](https://github.com/servo/servo/blob/f3a8e749cef3d86fc2437ff4fa3e0b7f5e781b6e/components/script/dom/range.rs#L124)):</sup>
I removed the comment, I already spent too much time on this patch. :)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8091)

**Comment by eefriedman** [comment]
OK.

r=me.

**Comment by nox** [comment]
@bors-servo r=eefriedman

Thanks for the review!

**Pull request merged**
