### PR TITLE
Implement flexbox reordering

### PR DESCRIPTION
**Pull request by dlrobertson**
Add style property for `order` and implement reordering by this property
in flex flow. Based on previous work by @zentner-kyle.

Fixes: #9957

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10178)

### CODE REVIEW

**Comment by danlrobertson** [comment]
#9117 attempted to also correctly implement `column-reverse` and `row-reverse`. Implementing reverse will take a bit more work. I plan to submit a separate PR for it. Is anyone else working on `FlexFlow`? I'd like to continue working on it, but I don't want to step on anyone's toes.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/layout/flex.rs, line 72 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10178#-KDeLd1nK810AFFKT0GC:-KDeLd1nK810AFFKT0GD:716339396) ([raw file](https://github.com/servo/servo/blob/f56062b0698addf17d8077f11e3c12a7e3a3cb8b/components/layout/flex.rs#L72)):*
I find it more readable to remove these, but could be swayed to think otherwise :smile:

---

*[components/layout/flex.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10178#-KDeLyzJ87NtrFaF0GOS:-KDeLyzKcOfj6Kv30bMc:1854588370) ([raw file](https://github.com/servo/servo/blob/05874aba24d2d94634fde29a3ee9e3ad5474f356/components/layout/flex.rs#L81)):*
I really don't like that a sort is used each time this is called.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10178#-:-KDeMa8ly1biyyOioXxO:-1363304422)*

**Comment by jdm** [comment]
Nobody else is working on FlexFlow. Step away!

**Comment by danlrobertson** [comment]
Sweet! Thanks!

**Comment by danlrobertson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/layout/flex.rs, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10178#-KDeZ6jSP7zdVTkewcBU:-KDeZ6jUVUNgdY5xyd7j:573615279) ([raw file](https://github.com/servo/servo/blob/05874aba24d2d94634fde29a3ee9e3ad5474f356/components/layout/flex.rs#L76)):*
Per the failure, `as_block` should not be used like this. My current thought is to patter match on `Flow::class`. If you know of a better way, just let me know.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10178)*

**Comment by jdm** [comment]
```
  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_computedstyle_order-inherit.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_computedstyle_order-invalid.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_computedstyle_order-integer.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_computedstyle_order-negative.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_computedstyle_order.htm
```

**Comment by danlrobertson** [comment]
Woohoo! More passing tests!

**Comment by stshine** [comment]
Since the flex items of a container need to be iterated for multiple times by order, IMO a collection of FlexItemInfo is really needed to decrease sorting overheads and furthermore retain states between passes.

**Comment by danlrobertson** [comment]
@stshine Agreed. I did my best to address this in my latest commit.

Adding a method to `FlowList` seemed less than ideal, but it was the only workaround I could see to avoid adding lifetime specifiers to all the things. Please let me know if you agree or have critiques.

---

Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/layout/flex.rs, line 65 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10178#-KDl4JFgiHtP_I5WSrMT:-KDl4JFh1Zj5XDxREDup:-797350275) ([raw file](https://github.com/servo/servo/blob/056a0b92539901476c088579581eed70d95229d0/components/layout/flex.rs#L65)):*
A single `Vec<FlexItem>` works for now, but eventually I'd like to use something like `layout::inline::Line`. It would help once we implement `wrap`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10178#-:-KDl4i2vUca4C_M6tAQi:228886727)*

**Comment by SimonSapin** [comment]
r=me modulo your `as_block` comment.

---

Reviewed 2 of 4 files at r1, 5 of 5 files at r4, 1 of 2 files at r5, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/layout/flex.rs, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10178#-KDeZ6jSP7zdVTkewcBU:-KF5nhR-hAdC1G8p1VBO:-2046918618) ([raw file](https://github.com/servo/servo/blob/05874aba24d2d94634fde29a3ee9e3ad5474f356/components/layout/flex.rs#L76)):*
Sorry I don’t understand this and I don’t see what failure this refers to.

---

*[components/layout/flex.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10178#-KDeLyzJ87NtrFaF0GOS:-KF5mkbbA0fRJ1I4GriP:519405152) ([raw file](https://github.com/servo/servo/blob/05874aba24d2d94634fde29a3ee9e3ad5474f356/components/layout/flex.rs#L81)):*
There could be a "dirty" flag that indicates that `FlexFlow::items` need to be re-created and sorted. It would need be set when a flex item is added or removed or when their `order` value changes. This sounds non-trival, so it can be later follow-up.

---

*[components/style/properties.mako.rs, line 4928 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10178#-KF5NWACkGWGdVToDQ6v:-KF5NWACkGWGdVToDQ6w:-40338198) ([raw file](https://github.com/servo/servo/blob/b293f9476b9516af6e74a26e72313c32634be3cd/components/style/properties.mako.rs#L4928)):*
`input.try` is not necessary in this case (since you don’t go on to parse something else when it returns `Err`), `parse_integer` can be called directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10178#-:-KF5nwgiCQZWT01xcmVQ:896754260)*

**Comment by danlrobertson** [comment]
r=@SimonSapin

---

Review status: 8 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/layout/flex.rs, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10178#-KDeZ6jSP7zdVTkewcBU:-KF5sZgvbxhT9PN_4fFy:-1215401912) ([raw file](https://github.com/servo/servo/blob/05874aba24d2d94634fde29a3ee9e3ad5474f356/components/layout/flex.rs#L76)):*
This was an old comment before I realized that I forgot to implement `as_block` for `FlexFlow` (See the diff a little further down), so there was a test that hit a panic. If there was a flex box that was an item to a flex box, we would hit a panic here. This has been resolved.

---

*[components/layout/flex.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10178#-KDeLyzJ87NtrFaF0GOS:-KF5tA5SoGnaMrOJpn3U:-1713030076) ([raw file](https://github.com/servo/servo/blob/05874aba24d2d94634fde29a3ee9e3ad5474f356/components/layout/flex.rs#L81)):*
Ah! That is a good idea. It is probably more important now that we store a sorted `Vec` of `FlowRef`s in the `FlexFlow`. I'll add a issue for this.

---

*[components/style/properties.mako.rs, line 4928 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10178#-KF5NWACkGWGdVToDQ6v:-KF61CBVV_NX08zLK45p:2108904557) ([raw file](https://github.com/servo/servo/blob/b293f9476b9516af6e74a26e72313c32634be3cd/components/style/properties.mako.rs#L4928)):*
Awesome, good catch. I'll make the update shortly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10178#-:-KF666t96s6ianypsMkA:-826116671)*

**Comment by SimonSapin** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/layout/flex.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10178#-KDeLyzJ87NtrFaF0GOS:-KF6DOOWvZf1Qzqgy0_O:-965020768) ([raw file](https://github.com/servo/servo/blob/05874aba24d2d94634fde29a3ee9e3ad5474f356/components/layout/flex.rs#L81)):*
For future readers: https://github.com/servo/servo/issues/10531

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10178)*

**Pull request merged**
