### PR TITLE
Test Android x86 on CI

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes https://github.com/servo/servo/issues/21124

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21166)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
./mach clean-cargo-cache --keep 3 --force
[…]
"/home/servo/buildbot/slave/android-x86/build/python/_virtualenv/bin/python2.7" "-m" "pip" "install" "-I" "-r" "/home/servo/buildbot/slave/android-x86/build/tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt" failed with error code -11:
Output:
Collecting html5lib==1.0.1 (from -r /home/servo/buildbot/slave/android-x86/build/tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
[…]
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]==1.22->-r /home/servo/buildbot/slave/android-x86/build/tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt (line 5))
Installing collected packages: webencodings, six, html5lib, mozfile, mozinfo, blessings, mozterm, mozlog, mozdebug, idna, pycparser, cffi, enum34, asn1crypto, ipaddress, cryptography, pyOpenSSL, certifi, urllib3
Successfully installed asn1crypto-0.24.0 blessings-1.7 certifi-2018.4.16 cffi-1.11.5 cryptography-2.2.2 enum34-1.1.6 html5lib-1.0.1 idna-2.7 ipaddress-1.0.22 mozdebug-0.1 mozfile-1.2 mozinfo-0.10 mozlog-3.7 mozterm-1.0.0 pyOpenSSL-18.0.0 pycparser-2.18 six-1.11.0 urllib3-1.23 webencodings-0.5.1
Error:
program finished with exit code 1
elapsedTime=3.951225
```

:/

**Comment by jdm** [comment]
Pip segfaulting has been a problem on other linux build machines before. I've not yet figured out how to avoid it properly; upgrading pip made it go away but broke some other part of the build that I can't recall right now.

**Comment by SimonSapin** [comment]
This segfault is very reproducible on that machine:

```
$ gdb --args "/home/servo/buildbot/slave/android-x86/build/python/_virtualenv/bin/python2.7" "-m" "pip" "install" "-I" "-r" "/home/servo/buildbot/slave/android-x86/build/tests/wpt/web-platform-tests/tools/wptrunner/requirements.txt"
[…]
(gdb) where
#0  0x000000000049d684 in visit_decref () at ../Modules/gcmodule.c:360
#1  0x000000000049d805 in dict_traverse () at ../Objects/dictobject.c:2144
#2  0x000000000049c137 in subtract_refs () at ../Modules/gcmodule.c:385
#3  collect.lto_priv () at ../Modules/gcmodule.c:925
#4  0x00000000004f9b3e in PyGC_Collect () at ../Modules/gcmodule.c:1440
#5  0x00000000004f8e0f in Py_Finalize () at ../Python/pythonrun.c:448
#6  0x000000000051dc18 in Py_Exit (sts=sts@entry=0) at ../Python/pythonrun.c:1783
#7  0x000000000051b1b7 in handle_system_exit () at ../Python/pythonrun.c:1151
#8  0x000000000051aadd in PyErr_PrintEx () at ../Python/pythonrun.c:1161
#9  0x0000000000519a53 in RunModule.lto_priv.1256 () at ../Modules/main.c:194
#10 0x0000000000493b06 in Py_Main () at ../Modules/main.c:587
#11 0x00007ffff7810830 in __libc_start_main (main=0x4934c0 <main>, argc=7, argv=0x7fffffffe5a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe598) at ../csu/libc-start.c:291
#12 0x00000000004933e9 in _start ()

**Comment by SimonSapin** [comment]
Looks like https://bugs.python.org/issue27542, but it’s closed as "works for me". The work-around proposed at https://bugs.python.org/issue27542#msg280612 does not help.

**Comment by SimonSapin** [comment]
Removing the virtualenv on the worker seems to fix this.

@bors-servo retry

**Comment by SimonSapin** [comment]
```
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: This user doesn't have permissions to use KVM (/dev/kvm)
```

However, SSH’ing into the builder and running the same command does suceed. Adding some logging for permissions.

@bors-servo try

**Comment by SimonSapin** [comment]
Oh, the buildbot process had not been restarted since the user was added to the group…

@bors-servo try

**Comment by SimonSapin** [comment]
And the new job is green! http://build.servo.org/builders/android-x86/builds/10

@bors-servo try-

**Comment by SimonSapin** [comment]
@jdm r?

**Comment by jdm** [comment]
r=me with these tidy fixes:
```
./etc/ci/bootstrap-android-and-accept-licences.sh:1: missing blank line after shebang
./etc/ci/bootstrap-android-and-accept-licences.sh:1: incorrect license
./etc/ci/bootstrap-android-and-accept-licences.sh:1: script does not have shebang "#!/usr/bin/env bash"
./etc/ci/bootstrap-android-and-accept-licences.sh:2: script is missing options "set -o errexit", "set -o nounset", "set -o pipefail"
./etc/ci/bootstrap-android-and-accept-licences.sh:2: variable substitutions should use the full "${VAR}" form
```

**Comment by SimonSapin** [comment]
Ah, I had left the change from `/bin/sh` to `/usr/bin/env bash` uncommitted.

@bors-servo r=jdm

**Comment by SimonSapin** [comment]
Disabled `pipefail` for the `yes` program, despite what tidy might think.

@bors-servo r=jdm

**Comment by SimonSapin** [comment]
I love you too, tidy.

@bors-servo r=jdm

**Pull request merged**
