### PR TITLE
Make Event's isTrusted attribute unforgeable

### LINKED ISSUE #8956: Make Event's isTrusted attribute unforgeable
#7988 added support for the `[Unforgeable]` WebIDL attribute. We should use this in `Event.webidl`, according to the [specification](https://dom.spec.whatwg.org/#event). This should fix some [tests](https://github.com/servo/servo/blob/master/tests/wpt/metadata/dom/interfaces.html.ini) that currently fail.

Code: `components/script/dom/webidls/Event.webidl`
Test: `./mach test-wpt tests/wpt/web-platform-tests/dom/interfaces.html`

The tests that show up as newly passing should be removed from the ini file linked earlier.

### PR DESCRIPTION
**Pull request by Aesthetikx**
Three failure expectations were able to be removed from `tests/wpt/web-platform-tests/dom/interfaces.html`. This is my first commit to servo and my first time with rust, hopefully I didn't overlook anything.

Fixes #8956.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8963)

### CODE REVIEW

**Comment by jdm** [comment]
Looks great! Thank you!

**Comment by KiChjang** [comment]
@bors-servo retry
* Shell timed out? Probably a buildbot error

**Pull request merged**
