### PR TITLE
stylo: Support system fonts

### PR DESCRIPTION
**Pull request by Manishearth**
r=xidorn https://bugzilla.mozilla.org/show_bug.cgi?id=1349417

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16517)

### CODE REVIEW

**Comment by emilio** [comment]
It'd be nice to have a comment somewhere that explains why all this complexity is needed.

Using the `computed::Context` as a place to stash cached values seems also quite inelegant to me, but oh well...

**Comment by emilio** [comment]
Could you file an issue to at least move all those fields we stash to a common struct?

**Comment by Manishearth** [comment]
Sorry, didn't see your comment, crappy wifi.

Will do.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/issues/16518

**Comment by Manishearth** [comment]
@bors-servo try

will try to land later :|

**Comment by heycam** [comment]
@Manishearth sorry, backing this out in #16524 for the heap write hazard failures reported here, which probably weren't a quick fix: https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=49c8dc08ff6429622a961109b836914b133c8d85&filter-searchStr=Linux%20x64%20debug%20Executed%20by%20TaskCluster%20hazard-linux64-haz%2Fdebug%20tc(H)&selectedJob=92567967

**Comment by Manishearth** [comment]
(It's just outparam annotations, but no worries, I should be able to get these landed today)

**Pull request merged**
