### PR TITLE
Make use of Servo's border-spacing in Stylo

### PR DESCRIPTION
**Pull request by ghost**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] These changes have been tested manually

screenshot

r? @Manishearth

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13450)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* #13509

**Comment by KiChjang** [comment]
@bors-servo retry
* #12654

**Comment by Wafflespeanut** [comment]
Wat.

  error: internal compiler error: unexpected panic

  note: the compiler unexpectedly panicked. this is a bug.

  note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

  note: run with `RUST_BACKTRACE=1` for a backtrace

  thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [0, 0, 0, 0, 80, 229, 116, 100], error: Utf8Error { valid_up_to: 5 } }', ../src/libcore/result.rs:799
  stack backtrace:
     1:     0x7fa03a6b2b12 - std::sys::backtrace::tracing::imp::write::h4b09e6e8c01db097
     2:     0x7fa03a6cbead - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
     3:     0x7fa03a6c0f9e - std::panicking::default_hook::h96c288d728df3ebf
     4:     0x7fa03a6c1688 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
     5:     0x7fa03a6c1522 - std::panicking::begin_panic::hfbeda5aad583dc32
     6:     0x7fa03a6c1460 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
     7:     0x7fa03a6c13e1 - rust_begin_unwind
     8:     0x7fa03a71c82c - core::panicking::panic_fmt::h4395919ece15c671
     9:     0x7fa0391a24ec - core::result::unwrap_failed::h5b769ce1a31159ca
    10:     0x7fa03929782c - rustc_metadata::loader::get_metadata_section::he6ca41a4f59a14be
    11:     0x7fa039294aeb - rustc_metadata::loader::Context::extract_one::h486b361d1c05bc7d
    12:     0x7fa0392921d5 - rustc_metadata::loader::Context::find_library_crate::h1b17d74a9a885f1a
    13:     0x7fa03927cbc9 - rustc_metadata::creader::CrateReader::load::h03b51b732e53ef57
    14:     0x7fa03927bff6 - rustc_metadata::creader::CrateReader::resolve_crate::h28377323c8e6b2d4
    15:     0x7fa0392a3077 - rustc_metadata::creader::CrateReader::resolve_crate_deps::{{closure}}::ha8b611a19f65d09d
    16:     0x7fa039199118 - <std::collections::hash::map::HashMap<K, V, S> as core::iter::traits::FromIterator<(K, V)>>::from_iter::hc901eff2585c101a
    17:     0x7fa03927a03b - rustc_metadata::creader::CrateReader::register_crate::h59c678713636e5c2
    18:     0x7fa039280e6c - rustc_metadata::creader::CrateReader::read_macros::h43d8594e6a862f38
    19:     0x7fa03929857c - <rustc_metadata::macro_import::MacroLoader<'a> as rustc::middle::cstore::MacroLoader>::load_crate::h6fa2255f1cfc3b33
    20:     0x7fa038ccbcbb - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::load_crate::hd78c506a5dcdac99
    21:     0x7fa0336095ac - <syntax::ext::expand::InvocationCollector<'a, 'b> as syntax::fold::Folder>::fold_item::h0fe28be5da841c1a
    22:     0x7fa0334ed54a - syntax::fold::noop_fold_mod::hfc874acebc47b78f
    23:     0x7fa0334dfb0c - syntax::fold::noop_fold_item_kind::h585a43546386a7ee
    24:     0x7fa0334f1633 - syntax::fold::noop_fold_item_simple::h3d4554c855dc58e0
    25:     0x7fa033609ab2 - <syntax::ext::expand::InvocationCollector<'a, 'b> as syntax::fold::Folder>::fold_item::h0fe28be5da841c1a
    26:     0x7fa033669276 - syntax::ext::expand::Expansion::fold_with::h4b15544e975800a7
    27:     0x7fa0336070db - syntax::ext::expand::MacroExpander::collect_invocations::h394c2a558f484088
    28:     0x7fa033603bb9 - syntax::ext::expand::MacroExpander::expand::h959b262d25638add
    29:     0x7fa033602eef - syntax::ext::expand::MacroExpander::expand_crate::h08dcfa5db99b42c9
    30:     0x7fa03360d21d - syntax::ext::expand::expand_crate::hc240d93cfea63653
    31:     0x7fa03aac82c1 - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::h2d39fc9f02dd8655
    32:     0x7fa03aa7a2a8 - rustc_driver::driver::phase_2_configure_and_expand::hb41c4aa3b639bda4
    33:     0x7fa03aa73e7e - rustc_driver::driver::compile_input::hc0edbed7edb3eb18
    34:     0x7fa03aaa3521 - rustc_driver::run_compiler::h22d678d32fb7c300
    35:     0x7fa03a9dcea3 - std::panicking::try::do_call::h4d040997e2efdaf3
    36:     0x7fa03a6d3da6 - __rust_maybe_catch_panic
    37:     0x7fa03a9fbef9 - <F as alloc::boxed::FnBox<A>>::call_box::hba0b436c79e56b23
    38:     0x7fa03a6bf9d0 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
    39:     0x7fa03298b183 - start_thread
    40:     0x7fa03a30437c - clone
    41:                0x0 - <unknown>

  Build failed, waiting for other jobs to finish...
  error: Could not compile `selectors`.

**Pull request merged**
