### PR TITLE
Consistently name enum members in `dom::bindings::error::Error`

### LINKED ISSUE #5521: dom::bindings::error::Error constructors are not consistently named
Some constructors (NamespaceError, NoModificationAllowedError, TypeError) include the word "Error" while all others don't.

### PR DESCRIPTION
**Pull request by ehegnes**
Fixes #5521

### CODE REVIEW

**Comment by jdm** [comment]
Thanks!

**Comment by ehegnes** [comment]
You're welcome. :) Does anything need to be done on my end in order to help merge this PR?

**Comment by jdm** [comment]
No, we're just having some CI infrastructure problems.

**Comment by ehegnes** [comment]
Oh, I didn't realize. Thanks for letting me know.

**Pull request merged**
