### PR TITLE
Remove many explicit reflow calls

### LINKED ISSUE #33063: assertion failed: !GetCurrentRealmOrNull(*cx).is_null() when browsing w3schools.com
Screenshot from 2024-08-15 10-25-53
**Describe the bug:**
A clear and concise description of the bug.
When looking at w3schools.com, it starts out fine and then crashes

**To Reproduce:**
Steps to reproduce the behavior.
Open server, view w3schools.com
**Platform:**
Specify OS, distribution, and hardware platform.
Pop-OS Linux, Asus PN41. Current servo as of today

### PR DESCRIPTION
**Pull request by jdm**
Most of these reflow calls were added back before we had a catch-all reflow mechanism. They should be unnecessary if there is not explicit dirtying present, while any code that explicitly dirties nodes can use the pending reflow mechanism instead.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #33063
- [x] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
Nice! Can #23118 be closed in favor of this PR?

**Comment by jdm** [comment]
> Nice! Can #23118 be closed in favor of this PR?

Ha, I knew this work felt familiar. Closed!

**Review by mrobinson — APPROVED** [review]
All tests are passing!

**Comment by mrobinson** [comment]
The only thing missing here is sign off.

**Pull request merged**
