### PR TITLE
Removing recursion from ComplexSelector

### LINKED ISSUE #16019: ComplexSelector to_css should probably not do recursion
Currently it does:

        if let Some((ref next, ref combinator)) = self.next {
            next.to_css(dest)?;
            combinator.to_css(dest)?;
        }

which will run into crashes due to running out of stack; see https://bugzilla.mozilla.org/show_bug.cgi?id=475215

### PR DESCRIPTION
**Pull request by tictakk**
Using a smallvec instead of recursively calling to_css for ComplexSelector to handle running out of stack.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #16019  (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16347)

### CODE REVIEW

**Review by emilio — COMMENTED** [review]
Looks good, modulo that one last nit, sorry for the delay here!

**Comment by tictakk** [comment]
I'm not sure what "modulo that one last nit means." I don't see a mod in the original code. I did fix the format error you suggested though. If I'm meant to do something else, lemme know!

**Comment by jdm** [comment]
It means "with the exception of that single review comment".

**Pull request merged**
