### PR TITLE
Handle type parameters in unused_must_root

### LINKED ISSUE #6651: Static analysis doesn't catch `RefCell<Option<DOMException>>`
cc @Manishearth

### PR DESCRIPTION
**Pull request by Manishearth**
fixes #6651

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6688)

### CODE REVIEW

**Comment by jdm** [comment]
This makes sense and is a big help! Thanks!

**Comment by nox** [comment]
Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/browsercontext.rs, line 33 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6688#-JuplQLa4FDVuwEmT0J1)** ([raw file](https://github.com/servo/servo/blob/fda3eb632703a3b11fe586516fe03c5e05a73a45/components/script/dom/browsercontext.rs#L33)):</sup>
#[dom_struct]?

---

<sup>**[components/script/dom/node.rs, line 331 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6688#-JupexYPmxls2xin9j_b)** ([raw file](https://github.com/servo/servo/blob/511e3337fb3b1839ac00039d56ef6861762ed5d1/components/script/dom/node.rs#L331)):</sup>
before.GetPreviousSibling()

---

<sup>**[components/script/dom/node.rs, line 346 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6688#-JupeznxFEz6I6INdxS2)** ([raw file](https://github.com/servo/servo/blob/511e3337fb3b1839ac00039d56ef6861762ed5d1/components/script/dom/node.rs#L346)):</sup>
self.GetLastChild()

---

<sup>**[components/script/dom/node.rs, line 368 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6688#-Jupf0H7tR7uFVY2nTue)** ([raw file](https://github.com/servo/servo/blob/511e3337fb3b1839ac00039d56ef6861762ed5d1/components/script/dom/node.rs#L368)):</sup>
child.GetPreviousSibling()

---

<sup>**[components/script/dom/node.rs, line 377 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6688#-JupfBRbFtDQU7Ro9R6a)** ([raw file](https://github.com/servo/servo/blob/511e3337fb3b1839ac00039d56ef6861762ed5d1/components/script/dom/node.rs#L377)):</sup>
child.GetNextSibling()

---

<sup>**[components/script/dom/node.rs, line 1479 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6688#-JupfDaofhkqPI0BVhuh)** ([raw file](https://github.com/servo/servo/blob/511e3337fb3b1839ac00039d56ef6861762ed5d1/components/script/dom/node.rs#L1479)):</sup>
node.GetParentNode()

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6688)

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/browsercontext.rs, line 33 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6688#-JuplQLa4FDVuwEmT0J1)** ([raw file](https://github.com/servo/servo/blob/fda3eb632703a3b11fe586516fe03c5e05a73a45/components/script/dom/browsercontext.rs#L33)):</sup>
Nope. `#[dom_struct]` is only for those which have a corresponding webidl thingie (even if all of its implied attributes are needed, because we may add more dom_struct magic in the future)

It also implies `#[_generate_reflector]` which we don't want here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6688)

**Comment by nox** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6688)

**Comment by jdm** [comment]
Squash away!

**Comment by Manishearth** [comment]
@bors-servo r=jdm

Oops, forgot to fix tidy

**Comment by jdm** [comment]
```
3.00s$ ./mach test-tidy

components/plugins/lints/unrooted_must_root.rs:29: trailing whitespace
```

**Pull request merged**
