### PR TITLE
Add `./mach build --features layout-2020`

### PR DESCRIPTION
**Pull request by SimonSapin**
… with corresponding `layout` and `layout_thread` crates, which for now do nothing.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23646)

### CODE REVIEW

**Comment by jdm** [comment]
`./mach test-tidy` complains that the licenses are missing/wrong in the new files that were added.

**Comment by jdm** [comment]
@bors-servo retry
* https://github.com/servo/intermittent-failure-tracker/issues/5

**Comment by nox** [comment]
This should have been made to build Servo in a different target dir like for geckolib, I may do that later this week.

**Comment by jdm** [comment]
Why?

**Comment by nox** [comment]
Back in the day not doing different target dirs in a similar fashion as here was leading to spurious rebuildings, but Simon just checked locally and nothing gets rebuilt anymore, disregard my comment.

**Pull request merged**
