### PR TITLE
Fix all Windows warnings

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11208)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r=mbrubeck

Silly typo introduced just before committing...

**Comment by mbrubeck** [comment]
```
components\profile\mem.rs:359:16: 359:22 warning: unused import, #[warn(unused_imports)] on by default
components\profile\mem.rs:359:24: 359:29 warning: unused import, #[warn(unused_imports)] on by default
components\profile\mem.rs:359:31: 359:37 warning: unused import, #[warn(unused_imports)] on by default
components\profile\mem.rs:359:39: 359:45 warning: unused import, #[warn(unused_imports)] on by default
components\compositing\constellation.rs:29:30: 29:46 warning: unused import, #[warn(unused_imports)] on by default
components\compositing\constellation.rs:57:5: 57:13 warning: unused import, #[warn(unused_imports)] on by default
components\compositing\constellation.rs:182:5: 182:39 warning: struct field is never used: `child_processes`, #[warn(dead_code)] on by default
```

**Comment by nox** [comment]
@bors-servo r=mbrubeck

The previous failure is #11212 and I've fixed the last few warnings.

**Pull request merged**
