### PR TITLE
Add css twitter fail whale html test & update ellipse_to_bezier comment

### PR DESCRIPTION
**Pull request by bjwbell**
cgaebel had a TODO for a css twitter fail whale reftest, which depended on elliptical border-radius support.
I didn't see any feasible way other than a reference image for border_twitter_fail_whale_b.html.

r? @pcwalton

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7679)

### CODE REVIEW

**Comment by bjwbell** [comment]
It might be better to add the fail whale to tests/html/ instead of as a reftest.

**Comment by pcwalton** [comment]
Yeah, this is definitely cute and should at least go in `tests/html` but let's not gate the build on it :)

**Comment by bjwbell** [comment]
@pcwalton  moved to `tests/html.`

**Pull request merged**
