### PR TITLE
Make TopTypeId an untagged union

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13224)

### CODE REVIEW

**Comment by nox** [comment]
```rust
#[derive(Copy)]
pub union TopTypeId {
    /// ID used by abstract interfaces.
    pub abstract_: (),
    /// ID used by interfaces that are not castable.
    pub alone: (),
    /// ID used by interfaces that derive from Blob.
    pub blob: BlobTypeId,
    /// ID used by interfaces that derive from DOMPointReadOnly.
    pub dompointreadonly: DOMPointReadOnlyTypeId,
    /// ID used by interfaces that derive from DOMRectReadOnly.
    pub domrectreadonly: DOMRectReadOnlyTypeId,
    /// ID used by interfaces that derive from Event.
    pub event: EventTypeId,
    /// ID used by interfaces that derive from EventTarget.
    pub eventtarget: EventTargetTypeId,
    /// ID used by interfaces that derive from HTMLCollection.
    pub htmlcollection: HTMLCollectionTypeId,
    /// ID used by interfaces that derive from NodeList.
    pub nodelist: NodeListTypeId,
    /// ID used by interfaces that derive from TestBinding.
    pub testbinding: TestBindingTypeId,
    /// ID used by interfaces that derive from WebGLObject.
    pub webglobject: WebGLObjectTypeId,
}

impl Clone for TopTypeId {
    fn clone(&self) -> Self { *self }
}

impl EventTarget {
    pub fn type_id(&self) -> &'static EventTargetTypeId {
        unsafe {
            &get_dom_class(self.reflector().get_jsobject().get())
                .unwrap()
                .type_id
                .eventtarget
        }
    }
}
```

**Comment by nox** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/textures/default-texture.html:
  │ FAIL [expected PASS] WebGL test #0: at (0, 0) expected: 0,0,0,255 was 0,255,0,255
  │   → assert_true: at (0, 0) expected: 0,0,0,255 was 0,255,0,255 expected true got false
  │ 
  │ reportTestResultsToHarness/<@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:88:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ reportTestResultsToHarness@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:87:7
  │ testFailed@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:153:5
  │ checkCanvasRectColor@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1047:9
  │ checkCanvasRect@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1073:3
  │ checkCanvas@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1096:3
  └ @http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/textures/default-texture.html:15:1
```

That's #11618.

**Comment by Ms2ger** [comment]
Seems fine, but I'm not sure it's worth it.

r? @jdm

**Comment by jdm** [comment]
Thought about it some more, and convinced myself that it's fine. This can merge after a rebase.

**Comment by nox** [comment]
@jdm r?

**Comment by Ms2ger** [comment]
```


Tests with unexpected results:
  ▶ TIMEOUT [expected CRASH] /css-multicol-1_dev/html4/multicol-br-inside-avoidcolumn-001.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ assertion failed: self.block_flow.base.children.len() == 1 (thread LayoutWorker worker 2/6, at /Users/servo/buildbot/slave/mac-rel-css/build/components/layout/multicol.rs:149)
  │ stack backtrace:
  │    0:        0x10c11b0de - backtrace::backtrace::trace::h0e60ef08c7c34e9f
  │    1:        0x10c11b3cc - backtrace::capture::Backtrace::new::h8bf319c36d8f5d1b
  │    2:        0x10be27e74 - servo::main::_{{closure}}::h8c06f3f8650b0061
  │    3:        0x10d71cc53 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
  │    4:        0x10bfd6fb4 - std::panicking::begin_panic::h0914615a412ba184
  │    5:        0x10c0237ee - _<layout..multicol..MulticolFlow as layout..flow..Flow>::assign_block_size::h04801996ffa09f36
  │    6:        0x10c02455f - _<layout..traversal..AssignISizes<'a> as layout..parallel..ParallelPreorderFlowTraversal>::run_parallel::h778902546d71fe1c
  │    7:        0x10c0249d9 - layout::parallel::assign_inline_sizes::h2227b862ea935cab
  │    8:        0x10bf8a92f - _<std..panic..AssertUnwindSafe<F> as core..ops..FnOnce<()>>::call_once::h1446c482998a66c1
  │    9:        0x10bf326f4 - std::panicking::try::do_call::h7d24ea05c0eeb441
  │   10:        0x10d71df5a - __rust_maybe_catch_panic
  │   11:        0x10bf5afe1 - _<F as alloc..boxed..FnBox<A>>::call_box::he7038aa8c8acae23
  │   12:        0x10d71bb74 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  │   13:     0x7fff92796059 - _pthread_body
  │   14:     0x7fff92795fd6 - _pthread_start
  └ ERROR:servo: assertion failed: self.block_flow.base.children.len() == 1
```

**Comment by jdm** [comment]
@bors-servo: retry
* #13613

**Comment by jdm** [comment]
@bors-servo: retry
* #13613

**Pull request merged**
