### PR TITLE
layout_2020: Fix divide by zero error when resolving flexible lengths

### LINKED ISSUE #29852: Infinite loop with flexbox in layout-2020
This causes an infinite loop:

```html
<div style="display: flex; width: 0px">
  <div style="flex: 1 1 0px; margin: 1px"></div>
</div>
```

The reason is that the spec is not avoiding a `0 / 0` division, so servo ends up with NaN lengths and the algorithm doesn't advance as expected. See https://github.com/w3c/csswg-drafts/issues/8928

### PR DESCRIPTION
**Pull request by stshine**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #29852 (GitHub issue number if applicable)

- [x] There are tests for these changes OR

### CODE REVIEW

**Comment by stshine** [comment]
A previous work can be seen at #12754 .

**Comment by stshine** [comment]
WHAT?

@bors-servo retry

**Comment by stshine** [comment]
seems it works, but the code looks ugly. Maybe we should remove `hypothetical_main_size`.

**Comment by Loirooriol** [comment]
Yeah, your 1st patch would freeze items too aggressively.
The current version may be fine, I saw that layout-2013 does something similar: https://github.com/servo/servo/blob/ac09fdf0c72844e6ddd4e7463f8917b0abbdf4a5/components/layout/flex.rs#L278-L281

But this doesn't match the spec so I will need to think whether it's equivalent.

**Comment by stshine** [comment]
The layout 2013 one is also done by me :)

**Comment by Loirooriol** [comment]
This doesn't solve the problem for

```html
<div style="display: flex; width: 0px">
  <div style="flex: 1 1e-40 1e-40px; margin: 1px"></div>
</div>
```
`1e-40px` is greater than 0px so it's not affected by the change, but then `1e-40 * 1e-40px` ends up becoming zero.
#29863 seems a more robust solution.

**Pull request closed without merging**
