### PR TITLE
Implement IsBuffer, IsFramebuffer and IsRenderbuffer for WebGLRenderingContext

### LINKED ISSUE #11357: Implement WebGLRenderingContext.{isBuffer, isFramebuffer, isRenderbuffer}()
cc #10209

### PR DESCRIPTION
**Pull request by ddefisher**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [X] These changes fix #11357 
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11426)

### CODE REVIEW

**Comment by emilio** [comment]
Looks good to me, modulo those nits, let's see which tests are affected :-)

@bors-servo: try

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/webglframebuffer.rs, line 20 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11426#-KIdSzTnMAiRZfFJDw3T:-KIdQr_lpxBtdMKH4Xw_:1482523598) ([raw file](https://github.com/servo/servo/blob/e40616c05c6154eaaa71ab41559664b8b16fe003/components/script/dom/webglframebuffer.rs#L20)):*
> ```Rust
>     webgl_object: WebGLObject,
>     id: u32,
>     target: Cell<Option<u32>>,
> ```

Please add a comment saying that this can only be `gl::FRAMEBUFFER` at the moment. I'd like to convert it into a `bool`, but WebGL2 allows having `gl::{READ, WRITE}_FRAMEBUFFER`, so probably not worth it.

---

*[components/script/dom/webglrenderbuffer.rs, line 31 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11426#-KIdRdJcUtZAmOosET8V:-KIdRdJcUtZAmOosET8W:1683498807) ([raw file](https://github.com/servo/servo/blob/e40616c05c6154eaaa71ab41559664b8b16fe003/components/script/dom/webglrenderbuffer.rs#L31)):*
> ```Rust
>             webgl_object: WebGLObject::new_inherited(),
>             id: id,
>             target: Cell::new(None),
> ```

Same here, a renderbuffer can only be bound to the constant `gl::RENDERBUFFER`. In this case it might make more sense to use a bool, or at least adding a comment explaining it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11426#-:-KIdSeeaFZq0-d8w5Tg_:-241792399)*

**Comment by jdm** [comment]
I thought reflection-embedded was disabled on mac now :<

**Comment by emilio** [comment]
Thanks for doing this!

It seems you'll need to update the test expectations for `/webgl/conformance-1.0.3/conformance/more/conformance/quickCheckAPI-B2.html` (that failed in the try run).

r=me with that and the nits addressed :)

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 3 files at r3.
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/webglframebuffer.rs, line 20 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11426#-KItrDFwpTDV3vFIzNi9:-KItrDFwpTDV3vFIzNiA:1544584378) ([raw file](https://github.com/servo/servo/blob/c424026356fe559bf015cabad679c7865828ab89/components/script/dom/webglframebuffer.rs#L20)):*
> ```Rust
>     webgl_object: WebGLObject,
>     id: u32,
>     ///target can only be gl::FRAMEBUFFER at the moment 
> ```

nit: space after the comment start

---

*[components/script/dom/webglrenderbuffer.rs, line 20 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11426#-KItrIsLTT-K7PB7d56D:-KItrIsMrLYn1zD1Av5Y:-1898879808) ([raw file](https://github.com/servo/servo/blob/c424026356fe559bf015cabad679c7865828ab89/components/script/dom/webglrenderbuffer.rs#L20)):*
> ```Rust
>     webgl_object: WebGLObject,
>     id: u32,
>     target: Cell<bool>,
> ```

can you rename this to `ever_bound`? It would feel kind of weird having this called `target`.

---

*[components/script/dom/webglrenderbuffer.rs, line 74 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11426#-KItrTkJ48dBoBEmVr-d:-KItrTkJ48dBoBEmVr-e:-469765787) ([raw file](https://github.com/servo/servo/blob/c424026356fe559bf015cabad679c7865828ab89/components/script/dom/webglrenderbuffer.rs#L74)):*
> ```Rust
>     }
> 
>     pub fn target(&self) -> bool {
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11426#-:-KItrWT_PaDZkcO6Vr-C:-1488454566)*

**Comment by emilio** [comment]
Neat, thanks for doing this @DDEFISHER! :)

@bors-servo: r+

**Pull request merged**
