### PR TITLE
Fix a few incorrect Element interfaces

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7614)

### CODE REVIEW

**Comment by nox** [comment]
@frewsxcv Nice catches! I see 7 additions but 8 more passing tests though, any idea why?

**Comment by frewsxcv** [comment]
Hm. It looks like a few of them (blockquote, blink, multicol) didn't cause any test changes. I'll look into regression testing I guess

**Comment by frewsxcv** [comment]
@nox A couple of the ones I added in this PR were previously not stated in the `match` expression, so they were already creating `HTMLUnknownElement`s, and doing the right thing. I still think it's good to explicitly state that they *should* create `HTMLUnknownElement`s instead of just leaving them out

**Comment by nox** [comment]
@bors-servo r+

@frewsxcv I see, ok!

**Comment by frewsxcv** [comment]
http://build.servo.org/waterfall

```
remoteFailed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
]
```

**Pull request merged**
