### PR TITLE
Implement console#time and console#timeEnd methods

### PR DESCRIPTION
**Pull request by tschneidereit**
These methods are unspecified right now, but implemented in all major engines and fairly simple. The most complicated part is storing the timers on the document. The implementation works, but I don't know if it's optimal.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6646)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/console.rs, line 96 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6646#-JuhC_6JAvHLzJ52rhaj)** ([raw file](https://github.com/servo/servo/blob/878944d5c7e7ea6ec8678ac54fb37178d2edfcce/components/script/dom/console.rs#L96)):</sup>
Remove this, please.

---

<sup>**[components/script/dom/console.rs, line 108 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6646#-JuhChiRWWW8hGXI0LCe)** ([raw file](https://github.com/servo/servo/blob/878944d5c7e7ea6ec8678ac54fb37178d2edfcce/components/script/dom/console.rs#L108)):</sup>
Why not call `self.Log(msg)` here instead?

---

<sup>**[components/script/dom/console.rs, line 134 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6646#-JuhCtj9hglO9rzsg5lZ)** ([raw file](https://github.com/servo/servo/blob/878944d5c7e7ea6ec8678ac54fb37178d2edfcce/components/script/dom/console.rs#L134)):</sup>
Same here.

---

<sup>**[components/script/dom/document.rs, line 115 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6646#-JuhCyisQvFjMATKKY78)** ([raw file](https://github.com/servo/servo/blob/878944d5c7e7ea6ec8678ac54fb37178d2edfcce/components/script/dom/document.rs#L115)):</sup>
I don't think it's worth interning the timer names here. Let's just use DOMString.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6646)

**Comment by tschneidereit** [comment]
r? @jdm

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/console.rs, line 96 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6646#-JuhC_6JAvHLzJ52rhaj)** ([raw file](https://github.com/servo/servo/blob/878944d5c7e7ea6ec8678ac54fb37178d2edfcce/components/script/dom/console.rs#L96)):</sup>
All the console logging methods contain a `println!` instead of just forwarding the message, so it seems like it'd be inconsistent to leave it out here.

---

<sup>**[components/script/dom/console.rs, line 108 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6646#-JuhChiRWWW8hGXI0LCe)** ([raw file](https://github.com/servo/servo/blob/878944d5c7e7ea6ec8678ac54fb37178d2edfcce/components/script/dom/console.rs#L108)):</sup>
Because `Log` takes a `Vec<DOMString>`, so I'd have to wrap the message into a `Vec` for that.
I did look into moving the `println!` into `propagate_console_msg` and calling `propagate_console_msg(someLogLevel, msg)` in all the various logging methods, but that's not straight-forward because of `Assert`: that includes a prefix `"Assertion failed: "` in the `println'`d message, where all the others don't. I guess I could include a prefix and leave it empty for the other methods. Or perhaps it'd make sense to have prefixes `"Warning: "`, `"Error: "`, etc, too?

---

<sup>**[components/script/dom/document.rs, line 115 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6646#-JuhCyisQvFjMATKKY78)** ([raw file](https://github.com/servo/servo/blob/878944d5c7e7ea6ec8678ac54fb37178d2edfcce/components/script/dom/document.rs#L115)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6646)

**Comment by jdm** [comment]
Sorry about the delay!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/console.rs, line 108 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6646#-JuhChiRWWW8hGXI0LCe)** ([raw file](https://github.com/servo/servo/blob/878944d5c7e7ea6ec8678ac54fb37178d2edfcce/components/script/dom/console.rs#L108)):</sup>
I don't have any problem with the vec wrapping. I'd much rather reduce the duplication between these methods and have the timing functions be in charge of setting up the timer and shell out the display to the regular display methods. If we call Console::Log here we get to remove both the println and the call to propagate_console_msg :)

---

<sup>**[components/script/dom/document.rs, line 473 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6646#-JvGcM70zl3HJ_9nnL0Q)** ([raw file](https://github.com/servo/servo/blob/a71eb2f5d6ba376e9d9f087e5eb600d3b259b704/components/script/dom/document.rs#L473)):</sup>
Is this necessary?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6646)

**Comment by nox** [comment]
@tschneidereit Ping?

**Comment by frewsxcv** [comment]
Maybe we should close this and open an Issue linking to this effort?

**Comment by frewsxcv** [comment]
https://github.com/servo/servo/issues/9325

**Pull request closed without merging**
