### PR TITLE
Various fixes for cleaning up iframes, compositor layers, pipelines and threads.

### PR DESCRIPTION
**Pull request by glennw**
This allows most of the jquery test suite to run without exhausting thread resources.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5890)

### CODE REVIEW

**Comment by pcwalton** [comment]
The compositor and painting code looks good.

**Comment by jdm** [comment]
Reviewed files:
- components/compositing/compositor.rs @ r1
- components/compositing/compositor_layer.rs @ r1
- components/compositing/compositor_task.rs @ r1
- components/compositing/constellation.rs @ r1
- components/compositing/lib.rs @ r1
- components/compositing/pipeline.rs @ r1
- components/gfx/paint_task.rs @ r1
- components/msg/compositor_msg.rs @ r1
- components/msg/constellation_msg.rs @ r1
- components/script/dom/htmliframeelement.rs @ r1
- components/script/script_task.rs @ r1

---

<sup>**[components/compositing/constellation.rs, line 495 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5890#-JoA5IwlfoIQ29wG6wMn)** ([raw file](https://github.com/servo/servo/blob/ff9cedbe8a49919f0c37addebf2eefee4c5f18de/components/compositing/constellation.rs#L495)):</sup>
I feel like the map here isn't really necessary, we could just use *pipeline_id below.

---

<sup>**[components/compositing/constellation.rs, line 776 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5890#-JoA5_35fjo7Vqxm9IAq)** ([raw file](https://github.com/servo/servo/blob/ff9cedbe8a49919f0c37addebf2eefee4c5f18de/components/compositing/constellation.rs#L776)):</sup>
I don't think the map adds much.

---

<sup>**[components/compositing/constellation.rs, line 1004 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5890#-JoA7y1DKNThHF_U2kl1)** ([raw file](https://github.com/servo/servo/blob/ff9cedbe8a49919f0c37addebf2eefee4c5f18de/components/compositing/constellation.rs#L1004)):</sup>
Why rposition? Maybe comment on this?

---

<sup>**[components/script/script_task.rs, line 1368 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5890#-JoA8c0gqNo38iZhE3su)** ([raw file](https://github.com/servo/servo/blob/ff9cedbe8a49919f0c37addebf2eefee4c5f18de/components/script/script_task.rs#L1368)):</sup>
s/exis/exits/

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5890)

**Comment by glennw** [comment]
<sup>**[components/compositing/constellation.rs, line 495 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5890#-JoA5IwlfoIQ29wG6wMn)** ([raw file](https://github.com/servo/servo/blob/ff9cedbe8a49919f0c37addebf2eefee4c5f18de/components/compositing/constellation.rs#L495)):</sup>
It's needed to avoid a borrow check error (as mut_pipeline takes &mut self).

---

<sup>**[components/compositing/constellation.rs, line 776 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5890#-JoA5_35fjo7Vqxm9IAq)** ([raw file](https://github.com/servo/servo/blob/ff9cedbe8a49919f0c37addebf2eefee4c5f18de/components/compositing/constellation.rs#L776)):</sup>
It's needed to avoid a borrow check error (as mut_pipeline takes &mut self).

---

<sup>**[components/compositing/constellation.rs, line 1004 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5890#-JoA7y1DKNThHF_U2kl1)** ([raw file](https://github.com/servo/servo/blob/ff9cedbe8a49919f0c37addebf2eefee4c5f18de/components/compositing/constellation.rs#L1004)):</sup>
Not needed - fixed.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5890)

**Comment by jdm** [comment]
-S-awaiting-review 

---

Reviewed files:
- components/compositing/constellation.rs @ r2
- components/script/script_task.rs @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5890)

**Comment by glennw** [comment]
Squashed and rebased.

**Comment by glennw** [comment]
Let's hold off on merging this while I do a bit more testing - I'm seeing occasional hangs in the reftests, but I'm not sure if it's related to this patch or something else yet.

**Comment by glennw** [comment]
@jdm Rebased this after https://github.com/servo/servo/pull/6031 landed and I'm not seeing any intermittent reftest failures now.

**Pull request merged**
