### PR TITLE
Implement TextEncoder (fixes #4768).

### LINKED ISSUE #4768: Implement TextEncoder.
Spec: <https://encoding.spec.whatwg.org/#interface-textencoder>.

This includes enabling the relevant tests by adding
```ini
[encoding]
  skip: false
```
to `tests/wpt/include.ini`.

This may also include updating the `mozjs` and `rust-mozjs` dependencies to ensure we can work with typed arrays.

### PR DESCRIPTION
**Pull request by yodalee**
This PR need modification, but I think some review is fine.
I run the wpt test, there are some issues:
- The textencoder constructor test will fail, because it return `IndexError` instead of `RangeError` in spec.
- Other fail I cannot understand why....

### CODE REVIEW

**Comment by jdm** [comment]
What are the other failures you see?

**Comment by yodalee** [comment]
hmm, there are so many, most of them are decoder fail. Here is the link to log summary. 
https://dl.dropboxusercontent.com/u/3192346/log.txt
* There is other error like `USVString` handling, since `USVString` is not supported now.
* Another error is ` Non-UTF encodings supported only for decode, not encode`, which... is weird. I don't thine I support Non-UTF encoding.
btw, can I run wpt-test `encoding` section only, run all wpt-test really takes many time.

**Comment by jdm** [comment]
Yes, `./mach test tests/wpt/web-platform-tests/path/to/dir --processes=N` should work.

**Comment by jdm** [comment]
Ah. My recommendation with the failures is to make a PR that enables the `encoding` directory and following the steps at http://mxr.mozilla.org/servo/source/tests/wpt/README.md#71 to save the default failures that occur without any other changes. Then you can apply your other changes on top of that and see which failures go away.

**Comment by yodalee** [comment]
I see, let me try this and give you a clear log.

**Comment by jdm** [comment]
I've left comments on Critic :)

**Comment by yodalee** [comment]
I rebase the branch to newest. Also, I found that only 4 tests being passed after the textencoder added T_T

**Comment by jdm** [comment]
Yeah, I suspect the tests are relying on things like document.inputEncoding and TextDecoder, unfortunately.

**Comment by yodalee** [comment]
rebase to newest master and solve datatype issue. Though I think it still cast usize to u32 and causing some loss.

**Comment by jdm** [comment]
I believe there's just one nit left here, based on the Critic review - there should be a space before the { on `struct TextEncoder{`.

**Comment by yodalee** [comment]
I didn't notice the new issue, should be fixed now.

**Comment by yodalee** [comment]
wait a second, push wrong.

**Comment by yodalee** [comment]
I didn't notice the new issue, should be fixed now.

**Comment by jdm** [comment]
Thanks!

**Comment by jdm** [comment]
```
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:172:13: 177:14 error: conflicting implementations for trait `dom::bindings::trace::JSTraceable` [E0119]
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:172             impl JSTraceable for $ty {
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:173                 #[inline]
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:174                 fn trace(&self, _: *mut JSTracer) {
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:175                     // Do nothing
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:176                 }
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:177             }
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:169:1: 188:3 note: in expansion of no_jsmanaged_fields!
/home/servo/buildbot/slave/linux2/build/components/script/dom/bindings/trace.rs:82:1: 82:35 note: expansion site
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:172:13: 177:14 note: note conflicting implementation here
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:172             impl JSTraceable for $ty {
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:173                 #[inline]
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:174                 fn trace(&self, _: *mut JSTracer) {
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:175                     // Do nothing
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:176                 }
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:177             }
/home/servo/buildbot/slave/linux2/build/components/script/dom/macros.rs:169:1: 188:3 note: in expansion of no_jsmanaged_fields!
/home/servo/buildbot/slave/linux2/build/components/script/dom/textencoder.rs:35:1: 35:35 note: expansion site
error: aborting due to previous error
```

**Comment by yodalee** [comment]
Sorry about error, I have to dig into this problem for a while.

**Comment by jdm** [comment]
textencoder.rs:35 and trace.rs:82  have conflicting implementations of JSTraceable for a type. Presumably duplicate no_jsmanaged_fields or something?

**Comment by yodalee** [comment]
I found that textencoder not necessary to be related to `JSTracable` object. I remove the related code and it can be compiled now.

**Comment by yodalee** [comment]
It says that TextEncoder is exposed to all webpages in the test `tests/content/test_interface.html`. Should I allow it?

**Comment by jdm** [comment]
Yep!

**Comment by yodalee** [comment]
Added. I have to ask since the test warns me to get your review XD.

**Comment by jdm** [comment]
```
/encoding/api-surrogates-utf8.html
----------------------------------
CRASH [Parent]
/encoding/textencoder-utf16-surrogates.html
-------------------------------------------
CRASH [Parent]
```
The other failure in http://build.servo.org/builders/linux2/builds/998/steps/shell_1/logs/stdio is a new intermittent failure.

**Comment by jdm** [comment]
That being said, the single-byte-decoder failures are super weird and probably not your fault:
```
 0:23.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:16602) Full command: /Users/servo/buildbot/slave/mac2/build/components/servo/target/servo --cpu --hard-fail -z http://localhost:8000/encoding/single-byte-decoder.html
(pid:16602) "thread 'PaintTask' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:23.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:16602) "stack backtrace:"
 0:23.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:16602) "thread 'ResourceManager' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:23.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:16602) "thread 'LayoutTask' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:23.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:16602) "thread 'ScriptTask' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:23.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:16602) "thread 'Constellation' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
```
The other ones:
```
 0:22.76 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) Full command: /Users/servo/buildbot/slave/mac2/build/components/servo/target/servo --cpu --hard-fail -z http://localhost:8000/encoding/textencoder-utf16-surrogates.html
(pid:16611) "ERROR:js::rust: Error at http://localhost:8000/encoding/resources/shared.js:1: SyntaxError: invalid label"
 0:22.76 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) ""
 0:22.77 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "thread 'ScriptTask' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf16Error(())', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:22.77 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "stack backtrace:"
 0:22.79 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "   1:        0x1106a4c27 - sys::backtrace::write::h084c3267f5afd4a3hvy"
 0:22.79 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "   2:        0x1106bab93 - failure::on_fail::hc5ca3b9ac2e803f33NF"
 0:22.79 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "   3:        0x1106880b8 - rt::unwind::begin_unwind_inner::h6a7a87805596eb8avvF"
 0:22.80 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "   4:        0x110688821 - rt::unwind::begin_unwind_fmt::h1fd6919e00fae1f31tF"
 0:22.80 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "   5:        0x1106ba58e - rust_begin_unwind"
 0:22.80 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "   6:        0x1106dd0e7 - panicking::panic_fmt::hd22743a6fa1fac27zow"
 0:22.80 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "   7:        0x10f553529 - result::Result<T, E>::unwrap::h5852254708684733233"
 0:22.81 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "   8:        0x10f5532f9 - dom::bindings::conversions::jsstring_to_str::h520f3aa2e46c05d3Qid"
 0:22.82 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "   9:        0x10f55396d - dom::bindings::conversions::DOMString.FromJSValConvertible::from_jsval::h85c19365a87f6fd5skd"
 0:22.82 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  10:        0x10f7e071d - dom::bindings::codegen::Bindings::TextEncoderBinding::encode::__rust_abi"
 0:22.82 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  11:        0x10f7e05c4 - dom::bindings::codegen::Bindings::TextEncoderBinding::encode::h75ee900af9b78993H9O"
 0:22.83 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  12:        0x1106e47ec - CallJitMethodOp"
 0:22.83 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  13:        0x10f7e0f48 - dom::bindings::codegen::Bindings::TextEncoderBinding::genericMethod::__rust_abi"
 0:22.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  14:        0x10f7e0c58 - dom::bindings::codegen::Bindings::TextEncoderBinding::genericMethod::h4e358f67e1b00021DbP"
 0:22.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  15:        0x10fc9ee73 - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE"
 0:22.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  16:        0x10fc99aca - _ZN2js9InterpretEP9JSContextPNS_10StackFrameENS_10InterpModeE"
 0:22.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  17:        0x10fc929d7 - _ZN2js9RunScriptEP9JSContextP8JSScriptPNS_10StackFrameE"
 0:22.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  18:        0x10fc9ee3a - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE"
 0:22.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  19:        0x10fc71810 - _Z12js_fun_applyP9JSContextjPN2JS5ValueE"
 0:22.85 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  20:        0x10fc9ee73 - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE"
 0:22.85 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  21:        0x10fc99aca - _ZN2js9InterpretEP9JSContextPNS_10StackFrameENS_10InterpModeE"
 0:22.85 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  22:        0x10fc929d7 - _ZN2js9RunScriptEP9JSContextP8JSScriptPNS_10StackFrameE"
 0:22.86 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  23:        0x10fc9ee3a - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE"
 0:22.86 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  24:        0x10fc43834 - _ZL13array_forEachP9JSContextjPN2JS5ValueE"
 0:22.86 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  25:        0x10fc9ee73 - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE"
 0:22.86 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  26:        0x10fc99aca - _ZN2js9InterpretEP9JSContextPNS_10StackFrameENS_10InterpModeE"
 0:22.86 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  27:        0x10fc929d7 - _ZN2js9RunScriptEP9JSContextP8JSScriptPNS_10StackFrameE"
 0:22.87 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  28:        0x10fc9f610 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeEPNS_10StackFrameEPS9_"
 0:22.87 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  29:        0x10fc9f755 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE"
 0:22.87 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  30:        0x10fc383ee - _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKtmPNS_5ValueE"
 0:22.88 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  31:        0x10fc3862d - JS_EvaluateUCScript"
 0:22.88 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  32:        0x10f9e52b5 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::closure.86854"
 0:22.89 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  33:        0x10f9e50d8 - rust::with_compartment::h2106550434568717654"
 0:22.89 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  34:        0x10f9e4ff1 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::h3205811575285501871"
 0:22.89 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  35:        0x10f9e42e9 - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::execute::hf96c2ac8cc987799m9u"
 0:22.89 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  36:        0x10f9e0d49 - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::prepare::h9d8a3711dbd9b57cr2u"
 0:22.89 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  37:        0x10fb1054a - parse::html::servohtmlparser..Sink.TreeSink::complete_script::closure.90125"
 0:22.90 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  38:        0x10fb104dc - option::Option<T>::map::h6794621019830840209"
 0:22.90 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  39:        0x10fa4ca26 - parse::html::servohtmlparser..Sink.TreeSink::complete_script::hb7172face2b6a4f2FJH"
 0:22.90 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  40:        0x10fa2e346 - tree_builder::rules::super..TreeBuilder<Handle, Sink>.TreeBuilderStep<Handle>::step::h9719100868359659082"
 0:22.91 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  41:        0x10fa1fff7 - tree_builder::TreeBuilder<Handle, Sink>::process_to_completion::h535777617112562528"
 0:22.91 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  42:        0x10fa1ea89 - tree_builder::TreeBuilder<Handle, Sink>.TokenSink::process_token::h16534827277814084458"
 0:22.91 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  43:        0x10fa1dc7d - tokenizer::Tokenizer<Sink>::process_token::h15945808271211698616"
 0:22.92 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  44:        0x10fa56976 - tokenizer::Tokenizer<Sink>::emit_current_tag::h1173704353908690555"
 0:22.92 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  45:        0x10fa173cd - tokenizer::Tokenizer<Sink>::step::h7665221103902331267"
 0:22.92 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  46:        0x10fa1482c - tokenizer::Tokenizer<Sink>::run::h7554921016820684585"
 0:22.92 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  47:        0x10fa14673 - tokenizer::Tokenizer<Sink>::feed::h12601154835379012461"
 0:22.92 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  48:        0x10fa144d5 - dom::servohtmlparser::ServoHTMLParser.Parser::parse_chunk::h9d638819ad0c11fctUB"
 0:22.92 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  49:        0x10f9429cb - parse::html::parse_html::hc66ea55918d878085KH"
 0:22.93 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  50:        0x10fb5a529 - script_task::ScriptTask::load::h77c50465fe30aaf3s4I"
 0:22.93 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  51:        0x10fb54dba - script_task::ScriptTask::handle_page_fetch_complete::h433cf7b79122182fy0I"
 0:22.93 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  52:        0x10fb51fe8 - script_task::ScriptTask::handle_msg_from_script::h97fa173793b72baftLI"
 0:22.94 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  53:        0x10fb2d925 - script_task::ScriptTask::handle_msgs::h52b2e318e630e83cFCI"
 0:22.94 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  54:        0x10fb2c272 - script_task::ScriptTask::start::h24e352e8b910ab99vCI"
 0:22.94 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  55:        0x10eec6f21 - script_task::ScriptTask.ScriptTaskFactory::create::closure.10281"
 0:22.94 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  56:        0x10eec62e2 - task::spawn_named_with_send_on_failure::closure.10268"
 0:22.94 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  57:        0x10eec61ec - thunk::Thunk<(), R>::new::closure.10264"
 0:22.95 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  58:        0x10eec60e7 - thunk::F.Invoke<A, R>::invoke::h3751873631010024537"
 0:22.95 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  59:        0x10edf9be1 - thunk::Thunk<A, R>::invoke::h2931109715816121355"
 0:22.95 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  60:        0x10edfa91a - thread::Builder::spawn_inner::closure.5332"
 0:22.95 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  61:        0x10edfa89f - rt::unwind::try::try_fn::__rust_abi::h17727766377029117438"
 0:22.95 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  62:        0x10edfa83a - rt::unwind::try::try_fn::h17727766377029117438"
 0:22.95 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  63:        0x1106bc579 - rust_try_inner"
 0:22.98 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  64:        0x1106bc566 - rust_try"
 0:22.98 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  65:        0x10edf9d2c - rt::unwind::try::h6324110442275320212"
 0:22.98 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  66:        0x10edf8a6f - thread::Builder::spawn_inner::closure.5184"
 0:22.98 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  67:        0x10edfb959 - thunk::Thunk<(), R>::new::closure.5356"
 0:22.98 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  68:        0x10edfb841 - thunk::F.Invoke<A, R>::invoke::h5289457463171441058"
 0:22.98 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  69:        0x1106a8653 - sys::thread::thread_start::h8d91e5be653c10c05CB"
 0:22.98 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "  70:     0x7fff8e0db772 - _pthread_start"
 0:22.98 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:16611) "Pipeline failed in hard-fail mode.  Crashing!"
 0:23.02 CRASH: Thread-TestrunnerManager-3 pid:16560. Test:None. Minidump anaylsed:False. Signature:[/encoding/textencoder-utf16-surrogates.html]
```

**Comment by yodalee** [comment]
Seems both occur in `encode` method, I think I will give it a look.

**Comment by yodalee** [comment]
There is problem on `DOMString.FromJSValConvertible::from_jsval` after call `encode` method. Maybe it's related to that we change `USVString` to `DOMString` ?

**Comment by jdm** [comment]
Yes, the failing result from String::from_utf16 is the problem bit here. @Ms2ger What do you think we should do when it fails instead of unwrapping?

**Comment by Ms2ger** [comment]
I implemented `USVString` in #5208; maybe it's easiest to rebase once that lands.

**Comment by yodalee** [comment]
I modify `DOMString` to `USVString` in commit:
https://github.com/yodalee/servo/commit/c1a70b8f932487478b66a9f7034f212da14f5188
The test won't crash now, and pass another test.

**Comment by Ms2ger** [comment]
Looks great; could you squash the commits?

**Comment by yodalee** [comment]
Done. I squash it into three commits: constructor, implement method, and enable testings

**Comment by jdm** [comment]
Thanks!

**Comment by yodalee** [comment]
I cannot reproduce the crash result of `/encoding/single-byte-decoder.html`, it end normally at my local test OAO

**Comment by jdm** [comment]
Yeah, that looks kind of like resource exhaustion on the builder machine. It's weird that it's happening for this test in particular :/

**Comment by yodalee** [comment]
@jdm 
on my local computer, I change the `async_test` into `test` in `single-byte-decoder.html`. Passed subtest increase to 334 from 158. Maybe we can try this on remote test?

**Comment by Ms2ger** [comment]
You mean you made the test not test anything.

**Comment by yodalee** [comment]
oops, I think I misunderstand the meaning of async_test and test.

**Comment by jdm** [comment]
The good news is that I can reproduce the failure locally:
```
godot2:servo jdm$ ./mach test tests/wpt/web-platform-tests/encoding/single-byte-decoder.html
 0:03.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) Full command: /Users/jdm/src/servo/components/servo/target/servo --cpu --hard-fail -z http://localhost:8000/encoding/single-byte-decoder.html
(pid:72816) "thread 'PaintTask' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:03.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread 'LayoutTask' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:03.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread 'PaintTask' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:03.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread 'LayoutTask' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:03.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread 'Constellation' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:03.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread 'PaintTask' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:03.60 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread 'ScriptTask' panicked at 'failed to spawn native thread: 35', /Users/larsberg/rust/src/libstd/sys/unix/thread.rs:229"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread 'LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread 'LayoutWorker worker 3/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "thread '<unnamed>thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/larsberg/rust/src/libcore/result.rs:743"
 0:03.61 PROCESS_OUTPUT: Thread-TestrunnerManager-2 (pid:72816) "fatal runtime error: Could not unwind stack, error = 5"
```

**Comment by jdm** [comment]
Wow, that test actually does spawn an incredible number of tasks for some reason.

**Comment by jdm** [comment]
So it's the async_test that creates a lot of iframes that is doing us in, specifically. For the purposes of this PR, I suggest just annotating that a crash is expected from this test, and we can file another bug for improving our thread creation eagerness and making this test not crash.

**Comment by metajack** [comment]
@mbrubeck Assigned to you to figure out next steps.

**Comment by mbrubeck** [comment]
I moved these patches to a new PR #5469 and added the suggested test change, so we can hopefully land them.  Thank you, @yodalee!

**Pull request closed without merging**
