### PR TITLE
Implement --pref in test-wpt

### PR DESCRIPTION
**Pull request by nox**
Needed to test GC zeal.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11211)

### CODE REVIEW

**Comment by nox** [comment]
Seems like there are no more failures with a correct implementation of `--pref`, @larsbergstrom any idea these tests fail at all, without or without zeal, in these specific runs?

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/servo/testing_commands.py, line 45 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11211#-KHzWQOcUlHYt8iMRzfQ:-KHzWQOeIgLj8GlR6u0D:-385014759) ([raw file](https://github.com/servo/servo/blob/429c82bdf1f6742af14542bf197954e9bea36213/python/servo/testing_commands.py#L45)):*
> ```Python
>     parser.add_argument('--chaos', default=False, action="store_true",
>                         help="Run under chaos mode in rr until a failure is captured")
>     parser.add_argument('--pref', default=[], action="append", dest="prefs",
> ```

I would much prefer this to be implemented at the wptrunner level so that we could also set per-run prefs for gecko. But OK for now I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11211)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11211)*

**Pull request merged**
