### PR TITLE
Fix: #4260. Click event is now a MouseEvent

### PR DESCRIPTION
**Pull request by liamzdenek**

### CODE REVIEW

**Comment by jdm** [comment]
Thanks for the change, and I'm sorry it took so long for us to review it! I've left stylistic nit in the Critic review, and then this will need to be rebased on top of a recent master revision.

**Comment by jdm** [comment]
@liamzdenek Are you planning to continue working on this?

**Comment by liamzdenek** [comment]
@jdm Sorry, I don't have the time.

**Comment by jdm** [comment]
That's fine; thanks for your help!

**Comment by saneyuki** [comment]
I'll pick up this.

**Pull request closed without merging**
