### PR TITLE
Fix iter_arith warning when running ./mach build-cef

### LINKED ISSUE #12855: Fix iter_arith warning when running ./mach build-cef
```
warning: this feature has been stable since 1.11.0. Attribute no longer needed, #[warn(stable_features)] on by default
 --> lib.rs:9:12
  |
9 | #![feature(iter_arith)]
  |            ^^^^^^^^^^
```

Files:
 * ports/cef/lib.rs

### PR DESCRIPTION
**Pull request by Coder206**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12855 (github issue number if applicable).
- [x] There are tests for these changes (./mach build-cef)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12860)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
@bors-servo r+

Thanks! :)

**Comment by Coder206** [comment]
@Wafflespeanut My pleasure :)

**Comment by notriddle** [comment]
@bors-servo retry

*  #11574
* #11561

**Pull request merged**
