### PR TITLE
geckolib: use a global thread pool for styling

### PR DESCRIPTION
**Pull request by froydnj**
By having a single thread pool, rather than one per document, we use less memory.  This addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1324250.

This may be obvious to an experienced Rust programmer, but I went with raw pointers because trying to use `Option` global variables resulted in complaints about turning on feature flags in nightly Rust.  Since this is for stylo, nightly features are not appropriate here.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15535)

### CODE REVIEW

**Comment by bholley** [comment]
What nightly-only features were required?

In general, Rust doesn't have a way of verifying our guarantee that Servo_Initialize will always be called. My general instinct is that we should have a global AtomicRefCell<Option<GlobalStyleData>>, and put the thread pool in there. This will incur an extra atomic operation per traversal, but I think the safety is worth it.

**Comment by emilio** [comment]
Why not just `AtomicPtr`, or `AtomicUsize`, like we did for the style structs?

**Comment by froydnj** [comment]
> What nightly-only features were required?

Something about drop implementations on global variables; I don't remember the exact error right now.

> Why not just AtomicPtr, or AtomicUsize, like we did for the style structs?

Sure!  I am completely ignorant of what was done for the style structs, though. ;)

**Comment by bholley** [comment]
> Why not just AtomicPtr, or AtomicUsize, like we did for the style structs?

That's pretty similar to what Nathan's patch does now, right? It still requires an unsafe deref.

But yeah, the Drop thing is a problem, hm.

**Comment by bholley** [comment]
So lazy_static basically encapsulates the same unsafe code we're talking about writing here (using a |Once| to make it sound). So I think we should just use a lazy_static for our GlobalStyleData.

We can get away with that single atomic op until we need to put something mutable in there, in which case we'll need to make it a lazy_static AtomicRefCell<GlobalStyleData>, and pay two atomic operations whenever we need to access it.

**Comment by froydnj** [comment]
OK, updated to use `lazy_static!` for the thread pool.  I couldn't figure out how to shut the thread pool down in `Servo_Shutdown`, though.  I also wasn't sure what @bholley's GlobalStyleData reference was pointing at--grep was unhelpful in finding something.

r? @emilio, I guess?

**Comment by bholley** [comment]
My suggestion was that GlobalStyleData would be something that you'd add, so that we don't have to keep solving this problem in the future. Could you do that, and put both the number of threads and the thread pool in there? That way the lazy_static could just invoke GlobalStyleData::new().

**Comment by froydnj** [comment]
> Could you do that, and put both the number of threads and the thread pool in there?

Ah, OK.  I'll just add a separate commit unifying the `lazy_static!` for `NUM_THREADS` and the thread pool, rather than redoing the current commits, if that's OK?

**Comment by bholley** [comment]
Sure, though I'll probably just review the squashed diff in that case.

**Comment by froydnj** [comment]
New commit up with `GlobalStyleData`.

**Comment by bholley** [comment]
lgtm, thanks!. Please do a linux64-stylo try push on mozilla-central before landing.

@bors-servo delegate!

**Comment by bholley** [comment]
er,

@bors-servo delegate+

**Comment by bholley** [comment]
Also, pro tip: I'd recommend developing stylo-affecting changes against m-c and getting review on bugzilla, so that you can do try pushes the normal way. Once everything is good to go, just export the patch and PR it to servo.

**Comment by froydnj** [comment]
Let's try this again:

@bors-servo r=bholley

**Comment by froydnj** [comment]
Ah, no, bors probably doesn't like that another commit got pushed after delegation.  So...

r? @bholley

**Pull request merged**
