### PR TITLE
style: Iterate the LRU cache contents from back to front.

### PR DESCRIPTION
**Pull request by emilio**
This is on top of #15888. Only the second commit needs review.

We put the more recently used item last, so iterating then from left to right is
pointless.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15891)

### CODE REVIEW

**Comment by bholley** [comment]
File an E-Easy for converting this cache to a VecDeque to avoid memmoving each time we need to pop the least-recently-used entry?

@bors-servo delegate+

**Comment by emilio** [comment]
> File an E-Easy for converting this cache to a VecDeque to avoid memmoving each time we need to pop the least-recently-used entry?

I don't think that happens a lot of times since we clear it often, but sure.

**Comment by emilio** [comment]
@bors-servo retry

 * Subpixel difference near a border corner, huh

**Comment by emilio** [comment]
WTF, those are the same exact tests... :(

Will look into them tomorrow.

**Comment by emilio** [comment]
wtf

That's the diff fwiw. I don't know how this could change it, except races, which would be unlikely...

**Comment by bholley** [comment]
Presumably because we've got two entries in the cache which collide (which is a bug), and the two entries have different ComputedValues (which is an even worse bug), and changing the iteration order causes us to get one instead of the other. :-(

**Comment by emilio** [comment]
Explanation for the failures at https://bugzilla.mozilla.org/show_bug.cgi?id=1346062#c2.

**Comment by emilio** [comment]
Last commit fixes the reftests failures, I've asked @mbrubeck to take a look.

**Comment by mbrubeck** [comment]
r=mbrubeck for the layout fix

**Pull request merged**
