### PR TITLE
Replace catch-all experimental flag with fine-grained boolean prefere…

### PR DESCRIPTION
**Pull request by jdm**
…nces initialized from a JSON document.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7391)

### CODE REVIEW

**Comment by Ms2ger** [comment]
```
   Compiling style_tests v0.0.1 (file:///home/servo/buildbot/slave/linux1/build/components/servo)
/home/servo/buildbot/slave/linux1/build/tests/unit/style/viewport.rs:28:5: 28:43 error: unresolved name `util::opts::set_experimental_enabled` [E0425]
/home/servo/buildbot/slave/linux1/build/tests/unit/style/viewport.rs:28     ::util::opts::set_experimental_enabled(true);
                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux1/build/tests/unit/style/viewport.rs:28:5: 28:43 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/buildbot/slave/linux1/build/tests/unit/style/viewport.rs:175:5: 175:43 error: unresolved name `util::opts::set_experimental_enabled` [E0425]
/home/servo/buildbot/slave/linux1/build/tests/unit/style/viewport.rs:175     ::util::opts::set_experimental_enabled(true);
                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux1/build/tests/unit/style/viewport.rs:175:5: 175:43 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 2 previous errors
```
```
failures:
    flex_column_direction.html == flex_column_direction_ref.html
    flex_row_direction.html == flex_row_direction_ref.html
    iframe/size_attributes_vertical_writing_mode.html == iframe/size_attributes_vertical_writing_mode_ref.html
    vertical-lr-blocks.html == vertical-lr-blocks_ref.html
    viewport_rule.html == viewport_rule_ref.html
```

**Comment by jdm** [comment]
Rebased and test failures addressed.

**Comment by jdm** [comment]
@Ms2ger Fixed that comment.

**Pull request merged**
