### PR TITLE
[Do not merge] Run try on multiple past commits without merging them to current master

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
Alright! It looks like https://community-tc.services.mozilla.com/tasks/groups/CvCvx9NHRESFPokJbQkQag has started as intended.

In this PR the decision task schedules testing not for that same PR but for two older commits (that I picked at semi-random) whose SHAs are near the top of `etc/taskcluster/decision_task.py`, without merging them with `master`. This can hopefully help bisect the regression that causes https://github.com/servo/servo/issues/24726.

Builds are indexed/cached as usual (for a week), but indexing of WPT tasks is disabled.

@jdm you should be able to take this branch, change the set of commits to test, then either:

* (Force-)push to this branch and give Homu a command like `try=wpt` again in this PR, or
* (Force-)push directly to the `try-wpt` branch and find tasks in https://treeherder.mozilla.org/#/jobs?repo=servo-try

Another thing you can tweak is `total_chunks` in the `linux_wpt` function: more chunks gives results sooner but more log files to look at.

**Comment by jdm** [comment]
The following script has made my life significantly better when I want to retrigger a set of tasks a large number of times:
```bash
export TASKCLUSTER_ROOT_URL=https://community-tc.services.mozilla.com/
eval $(taskcluster signin)
times=$1
shift
for task in $@
do
    for (( i = 1 ; i < $times; i++ ))
    do
        taskcluster task retrigger $task
    done
done
```

**Comment by jdm** [comment]
@simonsapin Let's say I have pushed branches testA and testB to the servo/servo remote. Will using commits from those branches in the commits list of the decision task work? If not, what else needs modifying?

**Comment by SimonSapin** [comment]
I’ve added a commit that makes sub-tasks fetch all branches from github.com/servo/servo, which should allow that.

@bors-servo try=wpt

**Comment by SimonSapin** [comment]
I’ve cancelled the builds but the git parts worked as intended:

* https://community-tc.services.mozilla.com/tasks/IjP0iAMiRyutlGMdDfxqDg/runs/0/logs/live/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FIjP0iAMiRyutlGMdDfxqDg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L539
* https://community-tc.services.mozilla.com/tasks/NYEB9_AgT8CFgn9GnPDt3g/runs/0/logs/live/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FNYEB9_AgT8CFgn9GnPDt3g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L537

**Comment by SimonSapin** [comment]
I believe this has served its purpose.

**Pull request closed without merging**
