### PR TITLE
stylo: update bindings

### PR DESCRIPTION
**Pull request by heycam**
Update bindings for https://treeherder.mozilla.org/#/jobs?repo=stylo&revision=3cefc3d84bae6c9ae9d591bb26d98a8f6fc51d47.

r? @bholley

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14667)

### CODE REVIEW

**Comment by bholley** [comment]
Looks WR related:

  ▶ CRASH [expected OK] /html/browsers/browsing-the-web/navigating-across-documents/javascript-url-query-fragment-components.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) } (thread <unnamed>, at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:837)
  │ stack backtrace:
  │    0:     0x7fb3e2fe2e3d - backtrace::backtrace::trace::h7c3311890fb811f9
  │    1:     0x7fb3e2fe34d2 - backtrace::capture::Backtrace::new::h023332005d95d7ee
  │    2:     0x7fb3e2f0e73d - servo::main::_{{closure}}::hdf04f97b4a2ecfbe
  │    3:     0x7fb3e4d038e4 - std::panicking::rust_panic_with_hook
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:554
  │    4:     0x7fb3e4d037a4 - std::panicking::begin_panic<collections::string::String>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
  │    5:     0x7fb3e4d036c9 - std::panicking::begin_panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
  │    6:     0x7fb3e4d03657 - std::panicking::rust_begin_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
  │    7:     0x7fb3e4d30b0d - core::panicking::panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
  │    8:     0x7fb3e30ac53b - core::result::unwrap_failed::h0206fc1f464e719e
  │    9:     0x7fb3e30f1d86 - webrender::render_backend::RenderBackend::run::hc4d5b186fa3be790
  │   10:     0x7fb3e309e9f5 - std::panicking::try::do_call::h3afc7379fc990a65
  │   11:     0x7fb3e4d0a82a - panic_unwind::__rust_maybe_catch_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  │   12:     0x7fb3e30b7264 - _<F as alloc..boxed..FnBox<A>>::call_box::h10a4783a0ed5b87a
  │   13:     0x7fb3e4d02584 - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
  │                          - std::sys_common::thread::start_thread
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  │   14:     0x7fb3e0dea183 - start_thread
  │   15:     0x7fb3e090137c - clone
  │   16:                0x0 - <unknown>
  │ ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) }
  └ Pipeline failed in hard-fail mode.  Crashing!

@glennw Should this be filed as a normal intermittent, or is this a test that just got unlucky?

**Comment by heycam** [comment]
Is this #14323?

**Pull request merged**
