### PR TITLE
Fix sccache failure when rustc generates thousands of warnings

### LINKED ISSUE #24714: sccache consistently errors on CI since Rust nightly-2019-11-07
https://community-tc.services.mozilla.com/tasks/NvN6U22bQ-C626hsVGu4fA

```
error: failed to execute compile
caused by: error reading compile response from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
error: could not compile `script`.
```

The error message is the same as in https://github.com/servo/servo/issues/24510, but setting `SCCACHE_IDLE_TIMEOUT` to zero does not help.

Merges in the regression range of `nightly-2019-11-06` to `nightly-2019-11-07` https://github.com/rust-lang/rust/compare/1423bec54...38048763e:

* Auto merge of https://github.com/rust-lang/rust/pull/65728 - ecstatic-morse:promotion-const-proj
* Auto merge of https://github.com/rust-lang/rust/pull/65134 - davidtwco:issue-19834-improper-ctypes-in-extern-C-fn
* Auto merge of https://github.com/rust-lang/rust/pull/65830 - Quantumplation:master
* Auto merge of https://github.com/rust-lang/rust/pull/66143 - Centril:rollup-qmzuex0
* Rollup merge of https://github.com/rust-lang/rust/pull/66139 - euclio:pluralize
* Rollup merge of https://github.com/rust-lang/rust/pull/66133 - alexcrichton:update-wasi-libc
* Rollup merge of https://github.com/rust-lang/rust/pull/66103 - smaeul:patch/thumb-musl
* Rollup merge of https://github.com/rust-lang/rust/pull/66092 - niacat:master
* Rollup merge of https://github.com/rust-lang/rust/pull/66086 - RalfJung:smallvec
* Rollup merge of https://github.com/rust-lang/rust/pull/66062 - smaeul:patch/pic-level
* Rollup merge of https://github.com/rust-lang/rust/pull/66015 - popzxc:refactor-librustc_parser
* Rollup merge of https://github.com/rust-lang/rust/pull/65973 - eddyb:caller-location-panic
* Rollup merge of https://github.com/rust-lang/rust/pull/65776 - nnethercote:rename-LocalInternedString-and-more
* Auto merge of https://github.com/rust-lang/rust/pull/66141 - Centril:rollup-n2fcvp9
* Rollup merge of https://github.com/rust-lang/rust/pull/66115 - eddyb:global-meta-what
* Rollup merge of https://github.com/rust-lang/rust/pull/66106 - JOE1994:master
* Rollup merge of https://github.com/rust-lang/rust/pull/66101 - estebank:break-tail-e0308
* Rollup merge of https://github.com/rust-lang/rust/pull/66098 - estebank:path-asciption-typo
* Rollup merge of https://github.com/rust-lang/rust/pull/66093 - estebank:fmt-ice
* Rollup merge of https://github.com/rust-lang/rust/pull/66081 - RalfJung:ptr-offset
* Rollup merge of https://github.com/rust-lang/rust/pull/66068 - euclio:null-emitter
* Rollup merge of https://github.com/rust-lang/rust/pull/66054 - petrochenkov:delspan
* Rollup merge of https://github.com/rust-lang/rust/pull/66027 - Mark-Simulacrum:panic-handler-query
* Rollup merge of https://github.com/rust-lang/rust/pull/66014 - dkadashev:47319-type-param-def-location
* Rollup merge of https://github.com/rust-lang/rust/pull/65892 - pnkfelix:trim-special-derives

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes https://github.com/servo/servo/issues/24714

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo p=1

To fix the daily task with Rust Nightly whose failures create IRC notifications.

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by jdm** [comment]
@bors-servo retry
* #24622

**Comment by jdm** [comment]
@bors-servo retry
#13480

**Pull request merged**
