### PR TITLE
Enable find_element and related wdspec tests

### PR DESCRIPTION
**Pull request by georgeroman**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes OR

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23550)

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ TIMEOUT [expected OK] /webdriver/tests/find_element/find.py
```

**Comment by georgeroman** [comment]
The test suite for the `find_element` and related commands contains a lot of tests (if I recall correctly, there are 38 tests for the `find_element` command). Since they won't complete in the 30 seconds default timeout threshold in `wptrunner`, the tests are ended prematurely and are wrongly reported as timed out. I had the same issue locally where I fixed it by running the test runner with a `--timeout-multiplier=3` argument, which basically increases the timeout threshold to 90 seconds. I thought this was not going to be an issue in the CI servers since I saw somewhere in the test command some argument `timeout=1200`, but it looks like this is not the same timeout as the one in the test runner. I could add the same timeout increase argument in the CI servers but I think this would unnecessarily increase the testing time, since the wdspec tests are ran together with the majority of the `wpt` tests. It would be great if there would be some way to specify the timeout just for some selected tests, but I am not sure if such a method exists.

**Comment by jdm** [comment]
@jgraham Does such a mechanism exist for pytests?

**Comment by jgraham** [comment]
No mechanism to increase the timeout for specific tests, but you could run the wdspec tests in a different job to the other tests? That's what we do for gecko and upstream.

**Pull request closed without merging**
