### PR TITLE
Address upstream WPT test harness changes

### PR DESCRIPTION
**Pull request by jdm**
https://github.com/web-platform-tests/wpt/pull/19449 and https://github.com/web-platform-tests/wpt/pull/19993 caused some of our proprietary tests to silently start to fail. This addresses all of the breakage.

### CODE REVIEW

**Review by asajeffrey — APPROVED** [review]
LGTM

**Comment by CYBAI** [comment]
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "", 
    "stack": "step@http://web-platform.test:8000/_mozilla/mozilla/window_requestAnimationFrame2.html:18:17\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1931:25\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1956:35\n", 
    "subtest": "Test throwing an error inside requestAnimationFrame callback", 
    "test": "/_mozilla/mozilla/window_requestAnimationFrame2.html", 
    "line": 196908, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Comment by jdm** [comment]
@bors-servo treeclosed=10
mac3 is broken and ruining everything (#24755)

**Comment by SimonSapin** [comment]
mac3 should be out of the pool now https://github.com/servo/taskcluster-config/pull/5#issuecomment-554617521

@bors-servo treeclosed-

**Comment by jdm** [comment]
@bors-servo retry
#13480

**Pull request merged**
