### PR TITLE
Include non-shadowdom children of shadow hosts in style calculation

### LINKED ISSUE #33495: Crash when attempting to proceed through Cloudflare Verification
**Describe the bug:**
When trying to access a site that uses Cloudflare Verification, the "Verifying you are a human" process causes a panic stemming from here https://github.com/servo/servo/blob/main/components/script/layout_dom/element.rs#L746, I believe when it's trying to attach the Cloudflare Turnstile. Unsure if this is because the Shadow DOM implementation is incomplete or something else

**To Reproduce:**
`./mach run https://rateyourmusic.com --pref dom.shadowdom.enabled`

**Platform:**
Windows 10

### PR DESCRIPTION
**Pull request by simonwuelker**
Currently `ServoLayoutElement::traversal_children` fails to account for children outside the shadow DOM if the element is a shadow host:
https://github.com/servo/servo/blob/c73e4baca206c172802be145c1fb8d110c1be863/components/script/layout_dom/element.rs#L151-L157

Stylo doesn't know about those children, so they are never assigned a style. Trying to access the style data causes crashes as seen in #33495.

There are no tests for these changes, because we don't run `shadow-dom` web platform tests. Perhaps we should consider changing that?

[try run](https://github.com/simonwuelker/servo/actions/runs/11925266716)

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #33495

### CODE REVIEW

**Comment by jdm** [comment]
>There are no tests for these changes, because we don't run shadow-dom web platform tests. Perhaps we should consider changing that?

I'm actually putting together a PR for that right now.

**Review by mrobinson — COMMENTED** [review]
Looks good to me, but I guess we this can be rebased on top of #34299 to see if any tests pass?

**Comment by simonwuelker** [comment]
Seems like many tests ran into this crash :eyes: 
(of course, most of them still fail for other reasons)

**Review by mrobinson — APPROVED** [review]
Great work!

**Comment by simonwuelker** [comment]
Apologies, I should have done a full try run.

**Comment by simonwuelker** [comment]
https://github.com/simonwuelker/servo/actions/runs/11938987284

**Pull request merged**
