### PR TITLE
Add test to constellation to avoid writing reftest image if there are pending frames.

### PR DESCRIPTION
**Pull request by glennw**
This changes several tests that contain <iframe></iframe> from FAIL to TIMEOUT. This is correct
since there is a bug that prevents these iframes from ever rendering.

~~~There are also a few previous FAILs that changed to OK. These may be intermittents or they
may genuinely be fixed by this change.~~~

<!-- Reviewable:start -->

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/servo/8612)

<!-- Reviewable:end -->

### CODE REVIEW

**Comment by glennw** [comment]
@jdm I didn't do any timing, but it felt like this make the wpt tests take a lot longer to execute. Unfortunately it's necessary so there's not much we can do about that anyway.

**Comment by glennw** [comment]
@jdm I expect this will also fix some of our remaining intermittent failures.

**Comment by jdm** [comment]
That panic is #8614.

**Comment by jdm** [comment]
@bors-servo: r+
Good find!

**Comment by jdm** [comment]
iframe/hide_layers2.html timed out.

**Comment by glennw** [comment]
Ahh, I have another patch in my WR branch that will fix this - I was going to do it as a follow up separate commit. I'll add it as a commit to this change.

**Comment by glennw** [comment]
@jdm I tried to reproduce this locally for quite some time and was unable to. I then looked at the patch I have in WR that I thought would fix this and convinced myself it's no longer required on master.

At that point I went back to the raw log and found that hide_layers2 did pass, and it's actually hide_layers1 that is missing from the list.

There is a known intermittent for hide_layers1 - https://github.com/servo/servo/issues/8284. So I think this may have actually just hit another intermittent and can be retried?

**Comment by jdm** [comment]
Well, the difference with #8284 is that the test fails in that case. In this test run, it timed out.

**Comment by jdm** [comment]
It seems super plausible to me that this change could introduce a timeout in an iframe test if our code that updates the list of pending frames isn't quite correct, is what I'm saying :)

**Comment by glennw** [comment]
Yep, it's definitely possible. The code certainly looks correct to me, but it's possible there's a subtle race condition that I'm unable to reproduce here.

**Comment by glennw** [comment]
I'll try a few more things here to repro it, and then ssh into the builders to see if I can make it occur there.

**Comment by glennw** [comment]
@jdm OK, updated to include what we discussed - marking the document as active earlier. All tests appear to run as expected, and this fixes a number of failures on the webrender branch. r?

Also be good to get @pcwalton to take a look, to see if I'm missing anything in the painting changes.

**Comment by glennw** [comment]
@jdm Rebased

**Comment by pcwalton** [comment]
This looks good to me.

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8612#-:-K4OuH5-smZG01urIawr:-317921516)*

**Comment by KiChjang** [comment]
```
Ran 6932 tests finished in 803.0 seconds.
  • 6931 ran as expected. 8 tests skipped.
  • 1 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected TIMEOUT] /css21_dev/html4/root-box-003.htm
  └   → /css21_dev/html4/root-box-003.htm d9d9e489bc5b4508c01b06c7ff92f19dcc2ece3c
```

**Comment by jdm** [comment]
Huh, I suspect this is a legitimate test result change, since the test involves styling the root element as `display: none`.

**Comment by glennw** [comment]
Hmm, I don't think that occurred when I ran the tests locally - but perhaps something has changed since then. I'll run them again locally and see if it happens here.

**Comment by glennw** [comment]
Verified that test is showing the same result locally and updated expectations.

**Comment by KiChjang** [comment]
```
Ran 3717 tests finished in 424.0 seconds.
  • 3716 ran as expected. 711 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /_mozilla/css/iframe/hide_layers2.html
  │ 
  │ thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
  │ stack backtrace:
  │    1:     0x559001ea0b80 - sys::backtrace::tracing::imp::write::h064b2475ee0d772cxXt
  │    2:     0x559001ea3ab5 - panicking::log_panic::_<closure>::closure.40992
  │    3:     0x559001ea3530 - panicking::log_panic::h29f8d24759545d7862x
  │    4:     0x559001e8c7e3 - sys_common::unwind::begin_unwind_inner::hdadcc96a1ecb24974Ps
  │    5:     0x559001e8ce98 - sys_common::unwind::begin_unwind_fmt::h9442bd88fc02b35caPs
  │    6:     0x559001ea01e1 - rust_begin_unwind
  │    7:     0x559001ed0c4f - panicking::panic_fmt::h2f3428e3725b99d6VFK
  │    8:     0x55900081a626 - constellation::_<impl>::handle_request::handle_request::h15417826861356379188
  │    9:     0x5590007fc897 - sys_common::unwind::try::try_fn::try_fn::h9046109789883446552
  │   10:     0x559001ea0028 - __rust_try
  │   11:     0x559001e9c3fb - sys_common::unwind::try::inner_try::hb6fbb19d6020cb51CMs
  │   12:     0x5590007feb0a - boxed::_<impl>::call_box::call_box::h18414290108468040276
  │   13:     0x559001ea2413 - sys::thread::_<impl>::new::thread_start::h51b5333730e2e1a3I5w
  │   14:     0x7f45cafc7181 - start_thread
  │   15:     0x7f45cb7e147c - __clone
  └   16:                0x0 - <unknown>
```

**Comment by KiChjang** [comment]
```

Ran 6932 tests finished in 1194.0 seconds.
  • 6930 ran as expected. 8 tests skipped.
  • 2 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected FAIL] /css-flexbox-1_dev/html/flexbox-basic-iframe-vert-001.htm

  ▶ TIMEOUT [expected FAIL] /css-flexbox-1_dev/html/flexbox-basic-iframe-horiz-001.htm
```

**Comment by jdm** [comment]
Independent of the test failure here, reading over the spec again I see "After creating the Document object, but before any script execution, certainly before the parser stops, the user agent must update the session history with the new page." Given that we're calling this in `handle_parsing_complete`, let's move the notification into ScriptTask::load, and invoke that before starting parsing instead.

**Comment by jdm** [comment]
The test failure is #8769.

**Comment by glennw** [comment]
@jdm Updated based on your comments - it now happens as soon as the Document object has been created.

**Comment by glennw** [comment]
This seems to have made the intermittent failures here https://github.com/servo/servo/issues/7787 happen all the time :( I'll investigate it and find out what's causing them to timeout.

**Comment by glennw** [comment]
@jdm OK, I can see the canvas timeout issue.

* The constellation synchronously queries the script task in handle_is_ready_to_save_image() (this is only done in reftest mode of course).
* The script task does a synchronous call to the constellation to create the canvas (see https://github.com/servo/servo/blob/master/components/script/dom/canvasrenderingcontext2d.rs#L124)

Which means deadlock :)

There is a comment in compositor.rs that says:

```
/// NB: Never block on the constellation, because sometimes the constellation blocks on us.
```

I could *probably* fix this by making the handle_is_ready_to_save_image() function call the script task via the event loop rather than synchronously (I haven't checked but it sounds reasonable).

However, it feels like we need more guidelines / architecture details on which threads (if any) can ever be called synchronously - knowing this would make it easier to know what the correct fix is here.

At the moment it seems like it's mostly luck that we don't hit these more often. I suspect fixing this will probably fix most of our intermittent canvas timeouts, at least.

**Comment by jdm** [comment]
I agree that it would be nice not to play whack a mole with this. Sounds like a discussion worth having next week, along with figuring out if there's a way we can disallow introducing potential deadlocks like this at build time.

**Comment by jdm** [comment]
-S-awaiting-review -S-needs-rebase +S-needs-code-changes 

---

Reviewed 6 of 6 files at r2, 1 of 1 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/window.rs, line 988 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8612#-K5fhBjPYp4fQOIczA2a:-K5fhBjPYp4fQOIczA2b:1458888542) ([raw file](https://github.com/servo/servo/blob/0abf6b3bc56133e75a053fea77df4d390554dd83/components/script/dom/window.rs#L988)):*
We lost the check about waiting until the load event here. This looks like it could be problematic for tests that never use `reftest-wait`, since an initial reflow could take place that doesn't encompass the fully-parsed page, then we could dispatch the "load" event, and the compositor would think that everything is ready to snapshot.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8612#-:-K5fhszmGqACTaMdU8fZ:904062486)*

**Comment by glennw** [comment]
@jdm This fixes most of the new intermittents - but I still typically see 1-2 new intermittents per wpt run. I'll see if I can track that down today.

**Comment by jdm** [comment]
This design makes me worried about cases where we don't properly trigger reflow. I wonder if the following would work better:
* the compositor assumes each frame is `pending`
* when the compositor reaches the state where it needs to know if a frame is ready:
  * if the frame is marked `pending`, it sends an async message to the script thread and updates the frame state to `awaiting reply`
  * if the frame is marked `awaiting reply`, the compositor is not ready to take a screenshot
* when the script thread receives the message, it sends an async message to the compositor based on the document ready state and the presence of `reftest-wait`
* when the compositor receives the message, it updates the state of the relevant frame based on the contents of the message (ie. the frame is no longer marked `awaiting reply`)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/dom/window.rs, line 1004 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8612#-K5h7Lg3LQQ4qCZS7Bow:-K5h7Lg3LQQ4qCZS7Box:1807948990) ([raw file](https://github.com/servo/servo/blob/3f7edc55a4fd0651b3327fd05562982e4581b869/components/script/dom/window.rs#L1004)):*
Let's have a comment that explains this block.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8612#-:-K5h7Wj5Dy25FuNNSUvs:1458266033)*

**Comment by jdm** [comment]
Good catch! I have no more comments here; this is ready to merge if it passes tests repeatably :)
-S-awaiting-review 

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8612#-:-K5hWqtR_EeWDCKrVXgI:720680904)*

**Comment by glennw** [comment]
@jdm Try build succeeded, squashed down to 1 commit.

**Pull request merged**
