### PR TITLE
font-variant-caps should accept all-small-caps and all-petite-caps

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16821)

### CODE REVIEW

**Comment by Manishearth** [comment]
http://searchfox.org/mozilla-central/source/layout/style/nsCSSProps.cpp#1609

**Comment by Manishearth** [comment]
try @ https://treeherder.mozilla.org/#/jobs?repo=try&revision=cfe1fc634ee2c0699aed066ced0db9e562ee0fcd

**Comment by Manishearth** [comment]
Test expectation update

```patch
diff --git a/layout/reftests/font-features/reftest.list b/layout/reftests/font-features/reftest.list
index 4c7d478..88bc34c 100644
--- a/layout/reftests/font-features/reftest.list
+++ b/layout/reftests/font-features/reftest.list
@@ -60,7 +60,7 @@ HTTP(..) == annotations.html annotations-ref.html
 # test for specific features being on and others off, based on prop values
 # (debug problems with font-variant-debug.html which displays all props)
 fails-if(stylo) HTTP(..) == font-variant-alternates.html font-variant-alternates-ref.html
-fails-if(stylo) HTTP(..) == font-variant-caps.html font-variant-caps-ref.html
+HTTP(..) == font-variant-caps.html font-variant-caps-ref.html
 HTTP(..) == font-variant-east-asian.html font-variant-east-asian-ref.html
 HTTP(..) == font-variant-ligatures.html font-variant-ligatures-ref.html
 HTTP(..) == font-variant-numeric.html font-variant-numeric-ref.html
@@ -99,14 +99,14 @@ random-if(!winWidget&&!cocoaWidget) fails-if(winWidget||cocoaWidget) HTTP(..) ==
 HTTP(..) != caps-fallback-smallcaps1.html caps-fallback-default.html
 HTTP(..) != caps-fallback-smallcaps2.html caps-fallback-default.html
 HTTP(..) != caps-fallback-petitecaps.html caps-fallback-default.html
-fails-if(stylo) HTTP(..) != caps-fallback-allsmallcaps.html caps-fallback-default.html
-fails-if(stylo) HTTP(..) != caps-fallback-allpetitecaps.html caps-fallback-default.html
+HTTP(..) != caps-fallback-allsmallcaps.html caps-fallback-default.html
+HTTP(..) != caps-fallback-allpetitecaps.html caps-fallback-default.html
 # -- normal or fallback rendering
 HTTP(..) == caps-fallback-smallcaps1.html caps-fallback-smcp.html
 HTTP(..) == caps-fallback-smallcaps2.html caps-fallback-smcp.html
 HTTP(..) == caps-fallback-petitecaps.html caps-fallback-smcp.html
-fails-if(stylo) HTTP(..) == caps-fallback-allsmallcaps.html caps-fallback-smcpc2sc.html
-fails-if(stylo) HTTP(..) == caps-fallback-allpetitecaps.html caps-fallback-smcpc2sc.html
+HTTP(..) == caps-fallback-allsmallcaps.html caps-fallback-smcpc2sc.html
+HTTP(..) == caps-fallback-allpetitecaps.html caps-fallback-smcpc2sc.html
 
 # font-variant-position fallback
 random-if(cocoaWidget||Android) HTTP(..) == subsuper-fallback.html subsuper-fallback-ref.html # bug 1139269
diff --git a/layout/style/test/stylo-failures.md b/layout/style/test/stylo-failures.md
index f7bf802..2126bee 100644
--- a/layout/style/test/stylo-failures.md
+++ b/layout/style/test/stylo-failures.md
@@ -123,7 +123,7 @@ to mochitest command.
     * test_align_shorthand_serialization.html [8]
   * font-variant-{alternates,east-asian,ligatures,numeric} properties servo/servo#15957
     * test_property_syntax_errors.html `font-variant-alternates` [2]
-    * test_value_storage.html `font-variant` [176]
+    * test_value_storage.html `font-variant` [167]
     * test_specified_value_serialization.html `bug-721136` [1]
 * Properties implemented but not in geckolib:
   * font-feature-settings property servo/servo#15975
```

**Comment by jdm** [comment]
@bors-servo: retry
* #16644

**Pull request merged**
