### PR TITLE
style: Sync changes from mozilla-central, and update euclid

### PR DESCRIPTION
**Pull request by emilio**
See individual commits for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23827)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r=emilio,manishearth

(Manish took a look at the euclid update)

**Comment by emilio** [comment]
@bors-servo r=emilio,manishearth

 * Small cargo.lock update for azure which was missing when removing `[patch]` entries.

**Comment by emilio** [comment]
@bors-servo r=emilio,manishearth

 * Removed some now-dead code in unit tests.

**Comment by emilio** [comment]
@bors-servo r=emilio,manishearth

 * Rebase due to conflicts with #23568 in servo-tidy.toml

**Comment by emilio** [comment]
@bors-servo r=emilio,manishearth p=1

 * Rebased.

**Comment by CYBAI** [comment]
<details>
<summary>More PASS tests!</summary>

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['opacity'] = \"-100%\" should set the property value", 
    "test": "/css/css-color/parsing/opacity-valid.html", 
    "line": 135099, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['opacity'] = \"50%\" should set the property value", 
    "test": "/css/css-color/parsing/opacity-valid.html", 
    "line": 135103, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['opacity'] = \"300%\" should set the property value", 
    "test": "/css/css-color/parsing/opacity-valid.html", 
    "line": 135106, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['background-image'] = \"radial-gradient(at center left 1px, red, blue)\" should not set the property value", 
    "test": "/css/css-images/parsing/gradient-position-invalid.html", 
    "line": 137917, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['background-image'] = \"radial-gradient(at center top 2px, red, blue)\" should not set the property value", 
    "test": "/css/css-images/parsing/gradient-position-invalid.html", 
    "line": 137918, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['background-image'] = \"radial-gradient(at right 3% center, red, blue)\" should not set the property value", 
    "test": "/css/css-images/parsing/gradient-position-invalid.html", 
    "line": 137920, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['background-image'] = \"radial-gradient(at left 4px top, red, blue)\" should not set the property value", 
    "test": "/css/css-images/parsing/gradient-position-invalid.html", 
    "line": 137921, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['background-image'] = \"radial-gradient(at right top 5px, red, blue)\" should not set the property value", 
    "test": "/css/css-images/parsing/gradient-position-invalid.html", 
    "line": 137922, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['background-image'] = \"radial-gradient(at bottom 6% center, red, blue)\" should not set the property value", 
    "test": "/css/css-images/parsing/gradient-position-invalid.html", 
    "line": 137923, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['background-image'] = \"radial-gradient(at bottom 7% left, red, blue)\" should not set the property value", 
    "test": "/css/css-images/parsing/gradient-position-invalid.html", 
    "line": 137924, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['background-image'] = \"radial-gradient(at bottom right 8%, red, blue)\" should not set the property value", 
    "test": "/css/css-images/parsing/gradient-position-invalid.html", 
    "line": 137925, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['perspective-origin'] = \"center left 1px\" should not set the property value", 
    "test": "/css/css-transforms/parsing/perspective-origin-parsing-invalid.html", 
    "line": 138307, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['perspective-origin'] = \"center top 2px\" should not set the property value", 
    "test": "/css/css-transforms/parsing/perspective-origin-parsing-invalid.html", 
    "line": 138308, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['perspective-origin'] = \"right 3% center\" should not set the property value", 
    "test": "/css/css-transforms/parsing/perspective-origin-parsing-invalid.html", 
    "line": 138309, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['perspective-origin'] = \"left 4px top\" should not set the property value", 
    "test": "/css/css-transforms/parsing/perspective-origin-parsing-invalid.html", 
    "line": 138310, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['perspective-origin'] = \"right top 5px\" should not set the property value", 
    "test": "/css/css-transforms/parsing/perspective-origin-parsing-invalid.html", 
    "line": 138311, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['perspective-origin'] = \"bottom 6% center\" should not set the property value", 
    "test": "/css/css-transforms/parsing/perspective-origin-parsing-invalid.html", 
    "line": 138312, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['perspective-origin'] = \"bottom 7% left\" should not set the property value", 
    "test": "/css/css-transforms/parsing/perspective-origin-parsing-invalid.html", 
    "line": 138313, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "e.style['perspective-origin'] = \"bottom right 8%\" should not set the property value", 
    "test": "/css/css-transforms/parsing/perspective-origin-parsing-invalid.html", 
    "line": 138314, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Property opacity value '-100%' computes to '0'", 
    "test": "/css/css-color/parsing/opacity-computed.html", 
    "line": 294726, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Property opacity value '50%' computes to '0.5'", 
    "test": "/css/css-color/parsing/opacity-computed.html", 
    "line": 294727, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

</details>

**Comment by emilio** [comment]
@bors-servo r=emilio,manishearth

 * Updated wpt expectations.

**Comment by jdm** [comment]
A bunch of raqote code needs to be updated now, unfortunately:
```
error[E0107]: wrong number of type arguments: expected 2, found 1
  --> components\canvas\raqote_backend.rs:27:82
   |
27 |     fn size_from_pattern(&self, _rect: &Rect<f32>, _pattern: &Pattern) -> Option<Size2D<f32>> {
   |                                                                                  ^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
  --> components\canvas\raqote_backend.rs:27:41
   |
27 |     fn size_from_pattern(&self, _rect: &Rect<f32>, _pattern: &Pattern) -> Option<Size2D<f32>> {
   |                                         ^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
  --> components\canvas\raqote_backend.rs:61:39
   |
61 |     fn create_drawtarget(&self, size: Size2D<u64>) -> Box<dyn GenericDrawTarget> {
   |                                       ^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 3, found 1
   --> components\canvas\raqote_backend.rs:123:22
    |
123 |         _transform: &Transform2D<f32>,
    |                      ^^^^^^^^^^^^^^^^ expected 3 type arguments

error[E0107]: wrong number of type arguments: expected 3, found 1
   --> components\canvas\raqote_backend.rs:128:70
    |
128 |     pub fn contains_point(&self, _x: f64, _y: f64, _path_transform: &Transform2D<f32>) -> bool {
    |                                                                      ^^^^^^^^^^^^^^^^ expected 3 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:138:34
    |
138 |     fn clear_rect(&self, _rect: &Rect<f32>) {
    |                                  ^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:145:18
    |
145 |         _source: Rect<i32>,
    |                  ^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:146:23
    |
146 |         _destination: Point2D<i32>,
    |                       ^^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:165:17
    |
165 |         _size: &Size2D<i32>,
    |                 ^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:173:16
    |
173 |         _size: Size2D<i32>,
    |                ^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:181:16
    |
181 |         _dest: Rect<f64>,
    |                ^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:182:18
    |
182 |         _source: Rect<f64>,
    |                  ^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:191:17
    |
191 |         _dest: &Point2D<f32>,
    |                 ^^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:193:19
    |
193 |         _offset: &Vector2D<f32>,
    |                   ^^^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:202:33
    |
202 |     fn fill_rect(&self, _rect: &Rect<f32>, _pattern: Pattern, _draw_options: Option<&DrawOptions>) {
    |                                 ^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:208:27
    |
208 |     fn get_size(&self) -> Size2D<i32> {
    |                           ^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 3, found 1
   --> components\canvas\raqote_backend.rs:211:32
    |
211 |     fn get_transform(&self) -> Transform2D<f32> {
    |                                ^^^^^^^^^^^^^^^^ expected 3 type arguments

error[E0107]: wrong number of type arguments: expected 3, found 1
   --> components\canvas\raqote_backend.rs:220:39
    |
220 |     fn set_transform(&self, _matrix: &Transform2D<f32>) {
    |                                       ^^^^^^^^^^^^^^^^ expected 3 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:237:17
    |
237 |         _start: Point2D<f32>,
    |                 ^^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:238:15
    |
238 |         _end: Point2D<f32>,
    |               ^^^^^^^^^^^^ expected 2 type arguments

error[E0107]: wrong number of type arguments: expected 2, found 1
   --> components\canvas\raqote_backend.rs:247:17
    |
247 |         _rect: &Rect<f32>,
    |                 ^^^^^^^^^ expected 2 type arguments

error: aborting due to 21 previous errors
```

**Comment by jdm** [comment]
Also embedding code:
```
error[E0432]: unresolved imports `servo::euclid::TypedPoint2D`, `servo::euclid::TypedRect`, `servo::euclid::TypedScale`, `servo::euclid::TypedSize2D`, `servo::euclid::TypedVector2D`
  --> ports/libsimpleservo/api/src/lib.rs:18:21
   |
18 | use servo::euclid::{TypedPoint2D, TypedRect, TypedScale, TypedSize2D, TypedVector2D};
   |                     ^^^^^^^^^^^^  ^^^^^^^^^  ^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^^^^^ no `TypedVector2D` in `euclid`
   |                     |             |          |           |
   |                     |             |          |           no `TypedSize2D` in `euclid`
   |                     |             |          no `TypedScale` in `euclid`
   |                     |             no `TypedRect` in `euclid`
   |                     no `TypedPoint2D` in `euclid`
```

**Comment by jdm** [comment]
And there's a use of euclid in ports/libmlservo.

**Comment by emilio** [comment]
@bors-servo r=emilio,manishearth

 * Updated raquote and co, fixed usage in layout_thread_2020 and libsimpleservo.

**Comment by emilio** [comment]
@bors-servo r=emilio,Manishearth

 * Update libmlservo too.

**Comment by emilio** [comment]
@bors-servo r=emilio,manishearth p=1

 * Rebase

**Comment by emilio** [comment]
(Hopefully the shameless p=1 here is ok :))

**Pull request merged**
