### PR TITLE
style: Don't unconditionally generate Calc values when converting background-size from Gecko.

### PR DESCRIPTION
**Pull request by emilio**
Bug: 1385140
MozReview-Commit-ID: ERwq50WSvLV

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17906)

### CODE REVIEW

**Comment by hiikezoe** [comment]
Nice find!  r=me with a try run.  There might be test cases that rely on the previous behavior.

**Comment by birtles** [comment]
Thanks Emilio!

**Comment by emilio** [comment]
Try was green.

@bors-servo r=hiro,birtles

**Pull request merged**
