### PR TITLE
Implement 'url!(..)' macro

### PR DESCRIPTION
**Pull request by frewsxcv**
https://github.com/servo/rust-url/issues/136

https://github.com/servo/rust-url/pull/137

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8622)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo r+

Thanks!

**Comment by frewsxcv** [comment]
@bors-servo r-

Tidy...

**Comment by jdm** [comment]
Lockfiles need updating.

**Comment by frewsxcv** [comment]
Lockfiles for cef and gonk have been added

**Comment by eefriedman** [comment]
```
/home/servo/buildbot/slave/linux-dev/build/tests/unit/plugin/url_plugin.rs:8:21: 8:23 error: relative URL without a base
/home/servo/buildbot/slave/linux-dev/build/tests/unit/plugin/url_plugin.rs:8                url!("").to_string());
                                                                                                 ^~
/home/servo/buildbot/slave/linux-dev/build/tests/unit/plugin/url_plugin.rs:8:16: 8:24 note: in this expansion of url! (defined in /home/servo/buildbot/slave/linux-dev/build/tests/unit/plugin/lib.rs)
/home/servo/buildbot/slave/linux-dev/build/tests/unit/plugin/url_plugin.rs:7:5: 8:38 note: in this expansion of assert_eq! (defined in <std macros>)
```

**Comment by frewsxcv** [comment]
Ah yeah. I reverted that usage locally but apparently forgot to commit it. Without my computer right now so I'll have to fix it later.

**Comment by frewsxcv** [comment]
Removed it in the latest force push

**Pull request merged**
