### PR TITLE
Backed out changeset dd834d38eaab for Windows debug build bustage

### PR DESCRIPTION
**Pull request by moz-servo-sync**
Backed out changeset dd834d38eaab for Windows debug build bustage

Backs out https://github.com/servo/servo/pull/19133

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19143)

### CODE REVIEW

**Comment by KiChjang** [comment]
#bors-servo treeclosed-

**Comment by upsuper** [comment]
@indygreg It doesn't seem to me this backout is reasonable. Judging from the log, it seems the bustage happened on the original push was just some infra intermittent, and the bustage on your push after that one was some sccache issue. The original push also doesn't touch anything we build in Gecko at all...

**Comment by indygreg** [comment]
It looks like I made a mistake. Sorry for the mix-up.

Please re-land at your earliest convenience,

**Comment by upsuper** [comment]
We should not land anything else before backout finishes... which is part of why a servo backout sucks. But making the two repos unsync only makes things suck more.

**Comment by upsuper** [comment]
#19145
#19146

These two seem to be the same issue, though, from `"Connection reset by peer"`.

**Pull request merged**
