### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23017)

### CODE REVIEW

**Comment by CYBAI** [comment]
Failure in Travis 👀

```
Checking files for tidiness...
./components/style_derive/to_css.rs:154: missing space after ,
./components/style_derive/to_css.rs:230: missing space after ,
```

and maybe need to set this as `PASS`

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Testing 'word-spacing'.", 
    "test": "/css/css-variables/variable-presentation-attribute.html", 
    "line": 126984, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

**Comment by emilio** [comment]
@bors-servo r+

Thanks as always @CYBAI <3

**Comment by jdm** [comment]
```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "computed style revert", 
    "test": "/css/css-variables/variable-definition-keywords.html", 
    "line": 167433, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "specified style revert", 
    "test": "/css/css-variables/variable-definition-keywords.html", 
    "line": 167437, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

**Comment by CYBAI** [comment]
Oops, there're some tests also passed I didn't notice! 👀

these @jdm mentioned and this one!

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Property word-spacing has initial value 0px", 
    "test": "/css/css-text/inheritance.html", 
    "line": 57763, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

**Comment by emilio** [comment]
Gah, I see that my WPT changes got synced right before this on the queue, dangit! :)

**Comment by nox** [comment]
This PR made `LengthOrAuto` be a type alias for `LengthPercentageOrAuto`. This is complicating the new layout's code *a lot* because in there we are quite disciplined about when we resolve percentages, when we set auto values etc, and not having two separate types is making things more confusing.

**Comment by nox** [comment]
Oh never mind, I only now noticed that it's the same type, just with a `LengthPercentage` variant that doesn't necessarily stores a `LengthPercentage`. Makes me wonder why the name of this enum isn't just `AutoOr` or something like that.

**Pull request merged**
