### PR TITLE
Update various dependencies

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15479)

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css-backgrounds-3_dev/html4/background-repeat-repeat-x.htm
  └   → /css-backgrounds-3_dev/html4/background-repeat-repeat-x.htm d07514bd9bfd00a1169d8d303ec25528f529c8d6
/css-backgrounds-3_dev/html4/reference/background-repeat-repeat-x.htm d0a3ab0a8082667af83497084c20c18b60f5f2d1
Testing d07514bd9bfd00a1169d8d303ec25528f529c8d6 == d0a3ab0a8082667af83497084c20c18b60f5f2d1

  ▶ FAIL [expected PASS] /css-backgrounds-3_dev/html4/background-repeat-repeat-y.htm
  └   → /css-backgrounds-3_dev/html4/background-repeat-repeat-y.htm 99cb0bda426e10cebd828f7d33b45bc29d040bf3
/css-backgrounds-3_dev/html4/reference/background-repeat-repeat-y.htm 33b6708fbdf3f800567b0a187991e3671d106a03
Testing 99cb0bda426e10cebd828f7d33b45bc29d040bf3 == 33b6708fbdf3f800567b0a187991e3671d106a03

  ▶ PASS [expected FAIL] /css21_dev/html4/attribute-token-selector-002.htm

  ▶ FAIL [expected PASS] /css21_dev/html4/background-repeat-repeat-x.htm
  └   → /css21_dev/html4/background-repeat-repeat-x.htm d07514bd9bfd00a1169d8d303ec25528f529c8d6
/css21_dev/html4/reference/background-repeat-repeat-x.htm d0a3ab0a8082667af83497084c20c18b60f5f2d1
Testing d07514bd9bfd00a1169d8d303ec25528f529c8d6 == d0a3ab0a8082667af83497084c20c18b60f5f2d1

  ▶ FAIL [expected PASS] /css21_dev/html4/background-repeat-repeat-y.htm
  └   → /css21_dev/html4/background-repeat-repeat-y.htm 99cb0bda426e10cebd828f7d33b45bc29d040bf3
/css21_dev/html4/reference/background-repeat-repeat-y.htm 33b6708fbdf3f800567b0a187991e3671d106a03
Testing 99cb0bda426e10cebd828f7d33b45bc29d040bf3 == 33b6708fbdf3f800567b0a187991e3671d106a03

  ▶ FAIL [expected PASS] /css21_dev/html4/c5525-fltwidth-003.htm
  └   → /css21_dev/html4/c5525-fltwidth-003.htm 1ecb930193cd88ea91e7b9f6f80d55b2b2300cb6
/css21_dev/html4/reference/c5525-fltwidth-003-ref.htm 8fc6b1e9725f1b190757e0ff5607157a714f8152
Testing 1ecb930193cd88ea91e7b9f6f80d55b2b2300cb6 == 8fc6b1e9725f1b190757e0ff5607157a714f8152

  ▶ PASS [expected FAIL] /css21_dev/html4/floats-028.htm
```

**Comment by nox** [comment]
@jdm The unexpected fails are Linux-only and my guess is that they come from the app_units bump.

**Comment by nox** [comment]
On macOS:

```
Tests with unexpected results:
  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flexbox_direction-row-reverse.htm

  ▶ TIMEOUT [expected PASS] /css-text-decor-3_dev/html/text-emphasis-style-property-010Cn.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ assertion failed: glyphs[0] != 0 (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at /Users/servo/buildbot/slave/mac-rel-css/build/components/gfx/platform/macos/font.rs:263)
  │ 2017-02-09 20:16:07.183 servo[82108:379239158] Metadata.framework [Error]: couldn't get the client port
  │ stack backtrace:
  │    0:        0x1056b53be - backtrace::backtrace::trace::h2fa1e3cabcda37c4
  │    1:        0x1056b5afc - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
  │    2:        0x10534e6e4 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h73309b19504a18d1
  │    3:        0x106e8cec4 - std::panicking::rust_panic_with_hook::h8943f907023b7818
  │    4:        0x1058214f4 - std::panicking::begin_panic::h1331614050b1aded
  │    5:        0x10583de57 - _$LT$gfx..platform..macos..font..FontHandle$u20$as$u20$gfx..font..FontHandleMethods$GT$::glyph_index::ha2e8bfe1059ed70e
  │    6:        0x1057a6da7 - _$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$::position::_$u7b$$u7b$closure$u7d$$u7d$::h58314eecaeef45af
  │    7:        0x105804d81 - layout::text::TextRunScanner::scan_for_runs::hab3a8107c181c511
  │    8:        0x10574a1ba - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$GT$::build_flow_for_block_starting_with_fragments::h70cea679bd4e944c
  │    9:        0x105748781 - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$GT$::build_flow_for_block_like::heff4ec8c059ad536
  │   10:        0x105747d0b - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$GT$::build_flow_for_block::heea8ca646c6cfd07
  │   11:        0x1056edf0e - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$u20$as$u20$layout..traversal..PostorderNodeMutTraversal$LT$ConcreteThreadSafeLayoutNode$GT$$GT$::process::h0a49651377fc6a5d
  │   12:        0x1056d3dd4 - _$LT$layout..traversal..RecalcStyleAndConstructFlows$u20$as$u20$style..traversal..DomTraversal$LT$E$GT$$GT$::process_postorder::hff4cb56dc218dfe1
  │   13:        0x105723123 - style::sequential::traverse_dom::doit::h0d23da632f6469c4
  │   14:        0x105723103 - style::sequential::traverse_dom::doit::h0d23da632f6469c4
  │   15:        0x105723103 - style::sequential::traverse_dom::doit::h0d23da632f6469c4
  │   16:        0x105762f80 - layout_thread::LayoutThread::handle_reflow::hb761664f1dc97131
  │   17:        0x10575c75a - layout_thread::LayoutThread::handle_request_helper::h2351449f9e6ddc58
  │   18:        0x10575902a - layout_thread::LayoutThread::handle_request::h144258cc6bbf24c7
  │   19:        0x10575570a - _$LT$layout_thread..LayoutThread$u20$as$u20$layout_traits..LayoutThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::hece779e04dbd3c16
  │   20:        0x1057037e7 - std::panicking::try::do_call::h0e6ef841af569849
  │   21:        0x106e8ddda - __rust_maybe_catch_panic
  │   22:        0x10571d268 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h97e3ae9709fce73c
  │   23:        0x106e8be44 - std::sys::imp::thread::Thread::new::thread_start::h4ad0b40513420e9c
  │   24:     0x7fff8655c059 - _pthread_body
  │   25:     0x7fff8655bfd6 - _pthread_start
  │ ERROR:servo: assertion failed: glyphs[0] != 0
  │ called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:868)
  │ stack backtrace:
  │    0:        0x1056b53be - backtrace::backtrace::trace::h2fa1e3cabcda37c4
  │    1:        0x1056b5afc - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
  │    2:        0x10534e6e4 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h73309b19504a18d1
  │    3:        0x106e8cec4 - std::panicking::rust_panic_with_hook::h8943f907023b7818
  │    4:        0x106e8cd54 - std::panicking::begin_panic::h946820df60a04b85
  │    5:        0x106e8ccc2 - std::panicking::begin_panic_fmt::h5face8a00b51b583
  │    6:        0x106e8cc27 - rust_begin_unwind
  │    7:        0x106eb65f0 - core::panicking::panic_fmt::h7546ee796899c522
  │    8:        0x105d7d750 - core::result::unwrap_failed::hfe648aed52e0e7f9
  │    9:        0x1060264bc - script::dom::window::Window::force_reflow::hd58bd8e1531c654b
  │   10:        0x10607d9bd - script::script_thread::ScriptThread::handle_event::h4ed5e400f79d391d
  │   11:        0x10605a637 - script::script_thread::ScriptThread::handle_msgs::h54af8131eff50a13
  │   12:        0x105c6bec7 - std::panicking::try::do_call::h6509f1646a477057
  │   13:        0x106e8ddda - __rust_maybe_catch_panic
  │   14:        0x105da532a - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hf30f11b50a85c76b
  │   15:        0x106e8be44 - std::sys::imp::thread::Thread::new::thread_start::h4ad0b40513420e9c
  │   16:     0x7fff8655c059 - _pthread_body
  │   17:     0x7fff8655bfd6 - _pthread_start
  └ ERROR:servo: called `Result::unwrap()` on an `Err` value: "SendError(..)"

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-input-017.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-input-018.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/attribute-token-selector-002.htm
```

The timeout is #14378.

**Comment by nox** [comment]
This is definitely a rounding issue:

capture d ecran 2017-02-10 a 12 09 35

**Comment by nox** [comment]
```
  ▶ FAIL [expected PASS] /css-backgrounds-3_dev/html4/background-repeat-repeat-x.htm
  └   → /css-backgrounds-3_dev/html4/background-repeat-repeat-x.htm d07514bd9bfd00a1169d8d303ec25528f529c8d6
/css-backgrounds-3_dev/html4/reference/background-repeat-repeat-x.htm d0a3ab0a8082667af83497084c20c18b60f5f2d1
Testing d07514bd9bfd00a1169d8d303ec25528f529c8d6 == d0a3ab0a8082667af83497084c20c18b60f5f2d1

  ▶ FAIL [expected PASS] /css-backgrounds-3_dev/html4/background-repeat-repeat-y.htm
  └   → /css-backgrounds-3_dev/html4/background-repeat-repeat-y.htm 99cb0bda426e10cebd828f7d33b45bc29d040bf3
/css-backgrounds-3_dev/html4/reference/background-repeat-repeat-y.htm 33b6708fbdf3f800567b0a187991e3671d106a03
Testing 99cb0bda426e10cebd828f7d33b45bc29d040bf3 == 33b6708fbdf3f800567b0a187991e3671d106a03

  ▶ FAIL [expected PASS] /css-transforms-1_dev/html/transform-input-017.htm
  └   → /css-transforms-1_dev/html/transform-input-017.htm 3a1c32bba9645166af12e18f41ccaf2eaa922d86
/css-transforms-1_dev/html/reference/transform-input-017-ref.htm 93f59025cd7b4f15deca3a75fef61c7561a5867c
Testing 3a1c32bba9645166af12e18f41ccaf2eaa922d86 == 93f59025cd7b4f15deca3a75fef61c7561a5867c

  ▶ FAIL [expected PASS] /css-transforms-1_dev/html/transform-input-018.htm
  └   → /css-transforms-1_dev/html/transform-input-018.htm 4eb0b443a9eb65a0164372e6c4e4df1945a51352
/css-transforms-1_dev/html/reference/transform-input-018-ref.htm d1b8f57ff844e331004d71064d3654ea8997d6e9
Testing 4eb0b443a9eb65a0164372e6c4e4df1945a51352 == d1b8f57ff844e331004d71064d3654ea8997d6e9

  ▶ FAIL [expected PASS] /css21_dev/html4/background-repeat-repeat-y.htm
  └   → /css21_dev/html4/background-repeat-repeat-y.htm 99cb0bda426e10cebd828f7d33b45bc29d040bf3
/css21_dev/html4/reference/background-repeat-repeat-y.htm 33b6708fbdf3f800567b0a187991e3671d106a03
Testing 99cb0bda426e10cebd828f7d33b45bc29d040bf3 == 33b6708fbdf3f800567b0a187991e3671d106a03

  ▶ FAIL [expected PASS] /css21_dev/html4/background-repeat-repeat-x.htm
  └   → /css21_dev/html4/background-repeat-repeat-x.htm d07514bd9bfd00a1169d8d303ec25528f529c8d6
/css21_dev/html4/reference/background-repeat-repeat-x.htm d0a3ab0a8082667af83497084c20c18b60f5f2d1
Testing d07514bd9bfd00a1169d8d303ec25528f529c8d6 == d0a3ab0a8082667af83497084c20c18b60f5f2d1

  ▶ FAIL [expected PASS] /css21_dev/html4/c5525-fltwidth-003.htm
  └   → /css21_dev/html4/c5525-fltwidth-003.htm 1ecb930193cd88ea91e7b9f6f80d55b2b2300cb6
/css21_dev/html4/reference/c5525-fltwidth-003-ref.htm 8fc6b1e9725f1b190757e0ff5607157a714f8152
Testing 1ecb930193cd88ea91e7b9f6f80d55b2b2300cb6 == 8fc6b1e9725f1b190757e0ff5607157a714f8152
```

The tests transform-input-017.htm and transform-input-018.htm now pass on macOS but still fail on Linux. :(

**Comment by emilio** [comment]
```
  ▶ PASS [expected FAIL] /_mozilla/css/border_radius_elliptical_a.html

  ▶ FAIL [expected PASS] /_mozilla/css/inline_block_overflow_hidden_a.html
  └   → /_mozilla/css/inline_block_overflow_hidden_a.html 7cbcaad2862c9c8a9cc7c4e2f28d727a4db30cdf
/_mozilla/css/inline_block_overflow_hidden_ref.html 84f6e84616988e3389b2929cd7f5617e4d61668b
Testing 7cbcaad2862c9c8a9cc7c4e2f28d727a4db30cdf == 84f6e84616988e3389b2929cd7f5617e4d61668b

  ▶ FAIL [expected PASS] /_mozilla/css/input_selection_a.html
  └   → /_mozilla/css/input_selection_a.html a4b9c2a874be2bf577324f155e1678805ace21f4
/_mozilla/css/input_selection_ref.html a3cd80997f8e2f8cad0a425f0997565a2f13ac1b
Testing a4b9c2a874be2bf577324f155e1678805ace21f4 == a3cd80997f8e2f8cad0a425f0997565a2f13ac1b

  ▶ FAIL [expected PASS] /_mozilla/css/position_fixed_a.html
  └   → /_mozilla/css/position_fixed_a.html cdda74fb1d41a76d413cdd5259ec00200509eb22
/_mozilla/css/position_fixed_b.html bf4079efd49f6860c34e45048b8cecca2e4f5b72
Testing cdda74fb1d41a76d413cdd5259ec00200509eb22 == bf4079efd49f6860c34e45048b8cecca2e4f5b72

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] Sniffed font is loaded and applied
  │   → assert_not_equals: got disallowed value 16
  │ FAIL [expected PASS] Sniffed font with xml is not loaded
  │   → assert_not_equals: got disallowed value 16
  │ FAIL [expected PASS] Sniffed font with xhtml+xml is not loaded
  │   → assert_not_equals: got disallowed value 16
  │ 
  │ checkFontLoaded@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:80:5
  │ Test.prototype.step_timeout/<@http://web-platform.test:8000/resources/testharness.js:1467:20
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1433:20
```

**Comment by nox** [comment]
@bors-servo try

I marked the tests as expected failures. :(

**Comment by nox** [comment]
```
Tests with unexpected results:
  ▶ CRASH [expected PASS] /_mozilla/css/iframe/simple_inline_min.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ index 8 out of range for slice of length 0 (thread RenderBackend, at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:578)
  │ stack backtrace:
  │    0:     0x7fac4ad9588d - backtrace::backtrace::trace::h976012eed768c7ff
  │    1:     0x7fac4ad95d72 - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
  │    2:     0x7fac4aabb367 - servo::main::{{closure}}::h039ba3c803113243
  │    3:     0x7fac4c925c28 - std::panicking::rust_panic_with_hook
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:556
  │    4:     0x7fac4c925af4 - std::panicking::begin_panic<collections::string::String>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
  │    5:     0x7fac4c925a19 - std::panicking::begin_panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
  │    6:     0x7fac4c9259a7 - std::panicking::rust_begin_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
  │    7:     0x7fac4c95316d - core::panicking::panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
  │    8:     0x7fac4c953269 - core::slice::slice_index_len_fail
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:578
  │    9:     0x7fac4c773b9f - webrender_traits::display_list::<impl webrender_traits::AuxiliaryLists>::glyph_instances::h5a81b20fe6b1f452
  │   10:     0x7fac4acf2862 - webrender::frame_builder::FrameBuilder::cull_layers::h6e2a3d3f0a0d544f
  │   11:     0x7fac4acf4c67 - webrender::frame_builder::FrameBuilder::build::h1d21ebee065eb551
  │   12:     0x7fac4ad23ac6 - webrender::render_backend::RenderBackend::render::hfdf7b1702f480fa7
  │   13:     0x7fac4ad13d3f - webrender::render_backend::RenderBackend::run::h806d46e08283bc83
  │   14:     0x7fac4acbb0bc - std::panicking::try::do_call::hd7e19225919acf8c
  │   15:     0x7fac4c92cb6a - panic_unwind::__rust_maybe_catch_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  │   16:     0x7fac4acd2a57 - <F as alloc::boxed::FnBox<A>>::call_box::h3728fcc574e67b7f
  │   17:     0x7fac4c9248b4 - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:623
  │                          - std::sys_common::thread::start_thread
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  │   18:     0x7fac48989183 - start_thread
  │   19:     0x7fac484a037c - clone
  │   20:                0x0 - <unknown>
  │ ERROR:servo: index 8 out of range for slice of length 0
  └ Pipeline failed in hard-fail mode.  Crashing!
```

These are #14806 and #15239.

**Comment by nox** [comment]
On macOS:

```
Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /css-text-decor-3_dev/html/text-emphasis-style-property-010Cn.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ assertion failed: glyphs[0] != 0 (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at /Users/servo/buildbot/slave/mac-rel-css/build/components/gfx/platform/macos/font.rs:263)
  │ 2017-02-10 09:02:24.443 servo[58319:386429855] Metadata.framework [Error]: couldn't get the client port
  │ stack backtrace:
  │    0:        0x10efa43be - backtrace::backtrace::trace::h2fa1e3cabcda37c4
  │    1:        0x10efa4afc - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
  │    2:        0x10ec3d6e4 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h73309b19504a18d1
  │    3:        0x11077bec4 - std::panicking::rust_panic_with_hook::h8943f907023b7818
  │    4:        0x10f1104f4 - std::panicking::begin_panic::h1331614050b1aded
  │    5:        0x10f12ce57 - _$LT$gfx..platform..macos..font..FontHandle$u20$as$u20$gfx..font..FontHandleMethods$GT$::glyph_index::ha2e8bfe1059ed70e
  │    6:        0x10f095da7 - _$LT$core..slice..Iter$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$::position::_$u7b$$u7b$closure$u7d$$u7d$::h58314eecaeef45af
  │    7:        0x10f0f3d81 - layout::text::TextRunScanner::scan_for_runs::hab3a8107c181c511
  │    8:        0x10f0391ba - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$GT$::build_flow_for_block_starting_with_fragments::h70cea679bd4e944c
  │    9:        0x10f037781 - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$GT$::build_flow_for_block_like::heff4ec8c059ad536
  │   10:        0x10f036d0b - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$GT$::build_flow_for_block::heea8ca646c6cfd07
  │   11:        0x10efdcf0e - _$LT$layout..construct..FlowConstructor$LT$$u27$a$C$$u20$ConcreteThreadSafeLayoutNode$GT$$u20$as$u20$layout..traversal..PostorderNodeMutTraversal$LT$ConcreteThreadSafeLayoutNode$GT$$GT$::process::h0a49651377fc6a5d
  │   12:        0x10efc2dd4 - _$LT$layout..traversal..RecalcStyleAndConstructFlows$u20$as$u20$style..traversal..DomTraversal$LT$E$GT$$GT$::process_postorder::hff4cb56dc218dfe1
  │   13:        0x10f012123 - style::sequential::traverse_dom::doit::h0d23da632f6469c4
  │   14:        0x10f012103 - style::sequential::traverse_dom::doit::h0d23da632f6469c4
  │   15:        0x10f012103 - style::sequential::traverse_dom::doit::h0d23da632f6469c4
  │   16:        0x10f051f80 - layout_thread::LayoutThread::handle_reflow::hb761664f1dc97131
  │   17:        0x10f04b75a - layout_thread::LayoutThread::handle_request_helper::h2351449f9e6ddc58
  │   18:        0x10f04802a - layout_thread::LayoutThread::handle_request::h144258cc6bbf24c7
  │   19:        0x10f04470a - _$LT$layout_thread..LayoutThread$u20$as$u20$layout_traits..LayoutThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::hece779e04dbd3c16
  │   20:        0x10eff27e7 - std::panicking::try::do_call::h0e6ef841af569849
  │   21:        0x11077cdda - __rust_maybe_catch_panic
  │   22:        0x10f00c268 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h97e3ae9709fce73c
  │   23:        0x11077ae44 - std::sys::imp::thread::Thread::new::thread_start::h4ad0b40513420e9c
  │   24:     0x7fff8655c059 - _pthread_body
  │   25:     0x7fff8655bfd6 - _pthread_start
  │ ERROR:servo: assertion failed: glyphs[0] != 0
  │ called `Result::unwrap()` on an `Err` value: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:868)
  │ stack backtrace:
  │    0:        0x10efa43be - backtrace::backtrace::trace::h2fa1e3cabcda37c4
  │    1:        0x10efa4afc - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
  │    2:        0x10ec3d6e4 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h73309b19504a18d1
  │    3:        0x11077bec4 - std::panicking::rust_panic_with_hook::h8943f907023b7818
  │    4:        0x11077bd54 - std::panicking::begin_panic::h946820df60a04b85
  │    5:        0x11077bcc2 - std::panicking::begin_panic_fmt::h5face8a00b51b583
  │    6:        0x11077bc27 - rust_begin_unwind
  │    7:        0x1107a55f0 - core::panicking::panic_fmt::h7546ee796899c522
  │    8:        0x10f66c750 - core::result::unwrap_failed::hfe648aed52e0e7f9
  │    9:        0x10f9154bc - script::dom::window::Window::force_reflow::hd58bd8e1531c654b
  │   10:        0x10f96c9bd - script::script_thread::ScriptThread::handle_event::h4ed5e400f79d391d
  │   11:        0x10f949637 - script::script_thread::ScriptThread::handle_msgs::h54af8131eff50a13
  │   12:        0x10f55aec7 - std::panicking::try::do_call::h6509f1646a477057
  │   13:        0x11077cdda - __rust_maybe_catch_panic
  │   14:        0x10f69432a - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hf30f11b50a85c76b
  │   15:        0x11077ae44 - std::sys::imp::thread::Thread::new::thread_start::h4ad0b40513420e9c
  │   16:     0x7fff8655c059 - _pthread_body
  │   17:     0x7fff8655bfd6 - _pthread_start
  └ ERROR:servo: called `Result::unwrap()` on an `Err` value: "SendError(..)"

  ▶ FAIL [expected PASS] /css21_dev/html4/floats-028.htm
  └   → /css21_dev/html4/floats-028.htm 4e22a01280212424c194ab88e8e0b0aa3a54c0e5
/css21_dev/html4/reference/floats-028-ref.htm 092d0b18a0a72a804cdaaed137cc02ea6e18c359
Testing 4e22a01280212424c194ab88e8e0b0aa3a54c0e5 == 092d0b18a0a72a804cdaaed137cc02ea6e18c359
```

Timeout is still #14378, while floats-028.htm seems to be a new intermittent failure.

**Comment by nox** [comment]
Err no, floats-028.htm just fails on macOS only now.

**Comment by nox** [comment]
On macOS:

```
Tests with unexpected results:
  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] Sniffed font is loaded and applied
  │   → assert_not_equals: got disallowed value 16
  │ FAIL [expected PASS] Sniffed font with xml is not loaded
  │   → assert_not_equals: got disallowed value 16
  │ FAIL [expected PASS] Sniffed font with xhtml+xml is not loaded
  │   → assert_not_equals: got disallowed value 16
  │ 
  │ checkFontLoaded@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:80:5
  │ Test.prototype.step_timeout/<@http://web-platform.test:8000/resources/testharness.js:1467:20
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1433:20
```

On Linux:

```
Tests with unexpected results:
  ▶ FAIL [expected PASS] /css21_dev/html4/c5525-fltwidth-003.htm
  └   → /css21_dev/html4/c5525-fltwidth-003.htm 1ecb930193cd88ea91e7b9f6f80d55b2b2300cb6
/css21_dev/html4/reference/c5525-fltwidth-003-ref.htm 8fc6b1e9725f1b190757e0ff5607157a714f8152
Testing 1ecb930193cd88ea91e7b9f6f80d55b2b2300cb6 == 8fc6b1e9725f1b190757e0ff5607157a714f8152
```

**Comment by nox** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] Sniffed font is loaded and applied
  │   → assert_not_equals: got disallowed value 16
  │ FAIL [expected PASS] Sniffed font with xml is not loaded
  │   → assert_not_equals: got disallowed value 16
  │ FAIL [expected PASS] Sniffed font with xhtml+xml is not loaded
  │   → assert_not_equals: got disallowed value 16
  │ 
  │ checkFontLoaded@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:80:5
  │ Test.prototype.step_timeout/<@http://web-platform.test:8000/resources/testharness.js:1467:20
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1433:20
```

Seems like this broke for real in this PR? Why? :'(

**Pull request merged**
