### PR TITLE
Update Rust nightly

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17149)

### CODE REVIEW

**Comment by nox** [comment]
@jdm Does that ring a bell?

**Comment by jdm** [comment]
No.

**Comment by nox** [comment]
This is ok to land now, right?

**Comment by nox** [comment]
@SimonSapin I think you said we shouldn't raise minimum version to 1.17 or something like that?

**Comment by SimonSapin** [comment]
Firefox's mach currently checks for 1.15.1+:

http://searchfox.org/mozilla-central/rev/20963d7269b1b14d455f47bc0260d0653015bf84/build/moz.configure/rust.configure#58

This is changed by filing a bug like https://bugzilla.mozilla.org/show_bug.cgi?id=1337153 and CCing @rillian. I don't know if there's a policy for how long we want to support a release before raising the requirement.

**Comment by rillian** [comment]
Firefox's only policy is that release Firefox be build with stable Rust. Otherwise I've just tried to balance the interests of those wanting new features vs those wanting less churn in their dev environment.

**Comment by nox** [comment]
I removed the Rust stable commit given mozilla-central forces us to stay in the past.

**Pull request merged**
