### PR TITLE
refactor parse_html param

### PR DESCRIPTION
**Pull request by creativcoder**
Hi, made the changes for Url to the param_html parameters and in the argument of a call to it.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8032)

### CODE REVIEW

**Comment by nox** [comment]
Given `Url` isn't Copy, do all the call sites actually compile?

**Comment by nox** [comment]
```
/build/components/script/dom/domparser.rs:66:45: 66:49 error: mismatched types:
 expected `url::Url`,
    found `&url::Url`
(expected struct `url::Url`,
    found &-ptr) [E0308]
/build/components/script/dom/domparser.rs:66                 parse_html(document.r(), s, &url, ParseContext::Owner(None));
                                                                                         ^~~~
/build/components/script/dom/domparser.rs:66:45: 66:49 help: run `rustc --explain E0308` to see a detailed explanation
/build/components/script/parse/html.rs:303:37: 303:41 error: mismatched types:
 expected `url::Url`,
    found `&&url::Url`
(expected struct `url::Url`,
    found &-ptr) [E0308]
/build/components/script/parse/html.rs:303     parse_html(document.r(), input, &url, ParseContext::Fragment(fragment_context));
                                                                               ^~~~
/build/components/script/parse/html.rs:303:37: 303:41 help: run `rustc --explain E0308` to see a detailed explanation
/build/components/script/script_task.rs:1651:47: 1651:57 error: mismatched types:
 expected `url::Url`,
    found `&url::Url`
(expected struct `url::Url`,
    found &-ptr) [E0308]
/build/components/script/script_task.rs:1651         parse_html(document.r(), parse_input, &final_url,
                                                                                           ^~~~~~~~~~
/build/components/script/script_task.rs:1651:47: 1651:57 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 3 previous errors
```

**Comment by nox** [comment]
```
/build/components/script/parse/html.rs:303:37: 303:40 error: mismatched types:
 expected `url::Url`,
    found `&url::Url`
(expected struct `url::Url`,
    found &-ptr) [E0308]
/build/components/script/parse/html.rs:303     parse_html(document.r(), input, url, ParseContext::Fragment(fragment_context));
                                                                               ^~~
/build/components/script/parse/html.rs:303:37: 303:40 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
```

**Comment by creativcoder** [comment]
Hi, resolved the errors. Sorry i am unable to build and test servo myself, the dependencies like llvm is taking a lot of time to download, as am on a slow network.

**Comment by jdm** [comment]
Hi @creativcoder! Sorry, there was a mixup and someone else also submitted a PR for #8028 while this one was open, and it got merged first. I also can't recommend that you continue to work on Rust issues for Servo if you aren't able to compile or test them locally, unfortunately, since that's a pretty important part of the process :)

**Comment by creativcoder** [comment]
Ok. i understand that.

**Pull request closed without merging**
