### PR TITLE
Fix parse_length 0 values, implement <hr> 'width'

### PR DESCRIPTION
**Pull request by frewsxcv**
Follow-up to https://github.com/servo/servo/issues/8424

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8526)

### CODE REVIEW

**Comment by frewsxcv** [comment]
The `<hr>` `width` addition was added for testing the `parse_length` utility

**Comment by frewsxcv** [comment]
Note that I intentionally did **not** test floating point values for the `width` param because right now we do integer parsing for non-percentage values, so if a float is passed, we get a parse error and return `Auto`. Unless there is a trivial solution for this, I'd rather just open this as a follow-up issue

**Comment by eefriedman** [comment]
Reviewed 5 of 5 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/util/str.rs, line 370 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8526#-K35uUqS9ikc_vkgCCq_)** ([raw file](https://github.com/servo/servo/blob/793ffa54835f0b738930efb051c4ef5e53da3bbb/components/util/str.rs#L370)):</sup>
I think if you change this from `from_px` to `from_f64_px`, fractions just work.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8526)

**Comment by frewsxcv** [comment]
Fixed.

**Comment by eefriedman** [comment]
Oops, I should have spotted that; you need to update the wpt test expectations for the width attribute.

**Comment by frewsxcv** [comment]
Test expectations updated.

**Pull request merged**
