### PR TITLE
Require FormDataEventInit dictionary

### LINKED ISSUE #22670: Dictionaries with required members that need rooting break codegen
The design for dictionaries that contain rooted members is that an empty dictionary value is created and then each member is set individually. This doesn't work when the WebIDL type specifies `required`, like the `FormDataEvent`:
```
error[E0599]: no function or associated item named `empty` found for type `dom::bindings::codegen::Bindings::FormDataEventBinding::FormDataEventInit` in the current scope
   --> /Users/cybai/codespace/mozilla/servo/target/debug/build/script-59d4418593395066/out/Bindings/FormDataEventBinding.rs:857:95
    |
259 | pub struct FormDataEventInit {
    | ---------------------------- function or associated item `empty` not found for this
...
857 |             crate::dom::bindings::codegen::Bindings::FormDataEventBinding::FormDataEventInit::empty()
    |             ----------------------------------------------------------------------------------^^^^^
    |             |
    |             function or associated item not found in `dom::bindings::codegen::Bindings::FormDataEventBinding::FormDataEventInit`
```
Addressing this probably means figuring out the precise issue that the current design is addressing.

### PR DESCRIPTION
**Pull request by saschanaz**
Should probably wait until https://github.com/whatwg/html/issues/5064 be fixed.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix __ (#22670 mentions `FormDataEvent` but the codegen itself still has a problem, in e.g. `PromiseRejectionEventInit`)

- [x] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
whatwg/html#5064 merged.

**Comment by jdm** [comment]
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: wrong value for FormDataEvent.length expected 1 but got 2", 
    "stack": "IdlInterface.prototype.test_self/<@https://web-platform.test:8443/resources/idlharness.js:1697:13\nTest.prototype.step@https://web-platform.test:8443/resources/testharness.js:1931:25\ntest@https://web-platform.test:8443/resources/testharness.js:544:30\nsubsetTestByKey@https://web-platform.test:8443/common/subset-tests-by-key.js:70:14\nIdlInterface.prototype.test_self@https://web-platform.test:8443/resources/idlharness.js:1677:9\nIdlInterface.prototype.test@https://web-platform.test:8443/resources/idlharness.js:1550:14\nIdlArray.prototype.test@https://web-platform.test:8443/resources/idlharness.js:888:28\nidl_test/</<@https://web-platform.test:8443/resources/idlharness.js:3387:31\n", 
    "subtest": "FormDataEvent interface object length", 
    "test": "/html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*)", 
    "line": 2070, 
    "action": "test_result", 
    "expected": "PASS"
}
```
This may be corrected upstream; we haven't successfully synced with WPT in several days.

**Comment by saschanaz** [comment]
Hmm yes, and probably blocked by https://github.com/web-platform-tests/wpt/pull/20304 this time.

**Comment by CYBAI** [comment]
@bors-servo try=wpt

- The web-platform-tests/wpt#20304 test has been merged into Servo at [ #24847](https://github.com/servo/servo/pull/24847/files#diff-ac9a5f910e0330b4d9419bcfc504f110R1169-R1172)

**Comment by CYBAI** [comment]
@bors-servo  retry

- #21696

**Comment by jdm** [comment]
@bors-servo retry
* #22276

**Pull request merged**
