### PR TITLE
Add gstreamer instructions for windows.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21437)

### CODE REVIEW

**Comment by kryptan** [comment]
Looks like it also [requires](https://github.com/sdroege/gstreamer-rs#gstreamer-binaries-1) pkg-config.

**Comment by kryptan** [comment]
I still can't build it, even after installing pkg-config. pkg-config is working:

```
>pkg-config --libs  gstreamer-player-1.0
-Lc:/gstreamer/1.0/x86_64/lib -lgstplayer-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lintl
```

But build fails with the same error.

**Comment by ferjm** [comment]
> But build fails with the same error.

@kryptan I believe you need to set LIB and LIBPATH to point to GStreamer libs like [this](https://github.com/servo/servo/blob/master/appveyor.yml#L57) as well.

Hopefully this won't be needed once we update to the latest pkg-config-rs version in #21515

**Pull request merged**
