### PR TITLE
Add support for webxr cubemap and spherical 360 rendering

### PR DESCRIPTION
**Pull request by asajeffrey**
Part of rendering webxr content as 360 video

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it's back-end rendering

### CODE REVIEW

**Comment by asajeffrey** [comment]
The matching webxr PR is https://github.com/servo/webxr/pull/181

**Review by Manishearth — APPROVED** [review]

**Comment by asajeffrey** [comment]
Screenshot from 2020-07-09 11-44-07

**Comment by jdm** [comment]
@bors-servo retry
* #27225

**Pull request merged**
