### PR TITLE
Update rust-webvr

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22338)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo retry

 - https://github.com/servo/servo/issues/21893

**Comment by Manishearth** [comment]
@bors-servo

 - server crashed?

**Comment by Manishearth** [comment]
screenshot_20181201-085757 2

Can't debug this from my phone whilst on a train.

**Comment by jdm** [comment]
That's https://github.com/servo/intermittent-failure-tracker/issues/5.

**Pull request merged**
