### PR TITLE
Persuading devtools to communicate with the workers; r=jdm

### PR DESCRIPTION
**Pull request by ghost**
For now, this just gives some purpose to the abandoned receiver and later selects over the two receivers (for #6767). (oh wait, forgot to check the local build - there are still a few errors)...

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6829)

### CODE REVIEW

**Comment by jdm** [comment]
Good start! Now we just need to fix the build errors ;)
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/devtools.rs, line 28 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvOmrnDS5u1zBoRH753)** ([raw file](https://github.com/servo/servo/blob/3bb73a0ecc2fc2a49fafb070a0f07e21755a27f7/components/script/devtools.rs#L28)):</sup>
Let's file an issue about this and add the issue number here.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvOn55zxn7_61gmioNP)** ([raw file](https://github.com/servo/servo/blob/3bb73a0ecc2fc2a49fafb070a0f07e21755a27f7/components/script/dom/dedicatedworkerglobalscope.rs#L114)):</sup>
This should be a DevtoolScriptControlMsg receiver instead, since it's going to be receiving messages sent by the devtools.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 233 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvOng978fVuUI89mvOb)** ([raw file](https://github.com/servo/servo/blob/3bb73a0ecc2fc2a49fafb070a0f07e21755a27f7/components/script/dom/dedicatedworkerglobalscope.rs#L233)):</sup>
This should use unwrap here, or it will break in cases where we don't use the devtools.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 238 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvOnkDKP84FNRseFI2p)** ([raw file](https://github.com/servo/servo/blob/3bb73a0ecc2fc2a49fafb070a0f07e21755a27f7/components/script/dom/dedicatedworkerglobalscope.rs#L238)):</sup>
Use an `if let` on the devtools_port Option value.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 246 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvOo9YEtChsMmgPggjh)** ([raw file](https://github.com/servo/servo/blob/3bb73a0ecc2fc2a49fafb070a0f07e21755a27f7/components/script/dom/dedicatedworkerglobalscope.rs#L246)):</sup>
We shouldn't use unwrap on these calls; we can use Ok/Err in the match still.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 254 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvOo1rv8OpoRdqdqeah)** ([raw file](https://github.com/servo/servo/blob/3bb73a0ecc2fc2a49fafb070a0f07e21755a27f7/components/script/dom/dedicatedworkerglobalscope.rs#L254)):</sup>
// TODO: process messages from the devtools as appropriate

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6829)

**Comment by Wafflespeanut** [comment]
This still requires some code changes...

**Comment by jdm** [comment]
-S-awaiting-review

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/trace.rs, line 48 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvQP2Fotyl__5GcATm7)** ([raw file](https://github.com/servo/servo/blob/b1d19e9ddf2f2f85b34b7cb3584b243a10cd2b3b/components/script/dom/bindings/trace.rs#L48)):</sup>
This change seems out of place without an accompanying change.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 17 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvQPMZXdQxV0KCLX2IF)** ([raw file](https://github.com/servo/servo/blob/b1d19e9ddf2f2f85b34b7cb3584b243a10cd2b3b/components/script/dom/dedicatedworkerglobalscope.rs#L17)):</sup>
This seems to be unused.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 233 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvOng978fVuUI89mvOb)** ([raw file](https://github.com/servo/servo/blob/3bb73a0ecc2fc2a49fafb070a0f07e21755a27f7/components/script/dom/dedicatedworkerglobalscope.rs#L233)):</sup>
Sorry, shouldn't.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6829)

**Comment by Wafflespeanut** [comment]
@jdm That was not meant to be reviewed...

**Comment by jdm** [comment]
Sorry, I tend to leap on things labelled "S-awaiting-review".

**Comment by Wafflespeanut** [comment]
Please don't review it yet! We still gotta process the messages from devtools.

**Comment by Wafflespeanut** [comment]
@jdm A few questions regarding my changes (and r?)...

---

Review status: 1 of 7 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/devtools.rs, line 163 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvXvLNFynDN0Q0Cujl4)** ([raw file](https://github.com/servo/servo/blob/3d5047724fc6dd2f046cfd5919fc2762ff27415e/components/script/devtools.rs#L163)):</sup>
I guess I'm wrong here, because the worker has no actual use in this function.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 193 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvXw04qAIaBVfllkp-n)** ([raw file](https://github.com/servo/servo/blob/3d5047724fc6dd2f046cfd5919fc2762ff27415e/components/script/dom/dedicatedworkerglobalscope.rs#L193)):</sup>
I decided to `unwrap` here because there's no reason for `devtools_ipc_port` to come up with an error, and that's because we're just sending a newly created `ipc::channel`.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 255 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvXw_ay6kDrvrcEyLK6)** ([raw file](https://github.com/servo/servo/blob/3d5047724fc6dd2f046cfd5919fc2762ff27415e/components/script/dom/dedicatedworkerglobalscope.rs#L255)):</sup>
I'm not sure how we should go for an error, because if I leave it with a `debug!`, then the loop never stops and the code below becomes unreachable. That's why I decided to `break` (for both the errors).

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 271 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvXxFWZ8-aWGAjY0sSG)** ([raw file](https://github.com/servo/servo/blob/3d5047724fc6dd2f046cfd5919fc2762ff27415e/components/script/dom/dedicatedworkerglobalscope.rs#L271)):</sup>
Am I right that the pipeline ID won't have any use in the worker?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6829)

**Comment by jdm** [comment]
Great! Looks like it will still fail when creating a worker and the devtools aren't attached, so that's important to fix :)
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/devtools.rs, line 32 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvYzsfqGt4RMJhuCrPf)** ([raw file](https://github.com/servo/servo/blob/3d5047724fc6dd2f046cfd5919fc2762ff27415e/components/script/devtools.rs#L32)):</sup>
Add this method to GlobalRef and use the ScriptHelpers trait to call it on both the window and worker: http://mxr.mozilla.org/servo/source/components/script/dom/window.rs#615

---

<sup>**[components/script/devtools.rs, line 163 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvXvLNFynDN0Q0Cujl4)** ([raw file](https://github.com/servo/servo/blob/3d5047724fc6dd2f046cfd5919fc2762ff27415e/components/script/devtools.rs#L163)):</sup>
It actually means that we should add this functionality to GlobalRef as well as WorkerGlobalScope (just duplicate http://mxr.mozilla.org/servo/source/components/script/dom/window.rs#141). We can either do that here or file a follow easy issue.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 193 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvXw04qAIaBVfllkp-n)** ([raw file](https://github.com/servo/servo/blob/3d5047724fc6dd2f046cfd5919fc2762ff27415e/components/script/dom/dedicatedworkerglobalscope.rs#L193)):</sup>
In that case we shouldn't be taking an Option value :)

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 241 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvOo9YEtChsMmgPggjh)** ([raw file](https://github.com/servo/servo/blob/3bb73a0ecc2fc2a49fafb070a0f07e21755a27f7/components/script/dom/dedicatedworkerglobalscope.rs#L241)):</sup>
Sorry, I obviously wasn't looking at the model code in script_task.rs when I made this comment :/

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 255 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvXw_ay6kDrvrcEyLK6)** ([raw file](https://github.com/servo/servo/blob/3d5047724fc6dd2f046cfd5919fc2762ff27415e/components/script/dom/dedicatedworkerglobalscope.rs#L255)):</sup>
We just unwrap result of recv() in the script task. I'd say follow that example.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 271 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvXxFWZ8-aWGAjY0sSG)** ([raw file](https://github.com/servo/servo/blob/3d5047724fc6dd2f046cfd5919fc2762ff27415e/components/script/dom/dedicatedworkerglobalscope.rs#L271)):</sup>
That is correct.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6829)

**Comment by Wafflespeanut** [comment]
@jdm r?

**Comment by Wafflespeanut** [comment]
@jdm I've fixed the conflicts. r?

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 5 of 5 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/workerglobalscope.rs, line 62 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvaSDLaEYmebktVABgj)** ([raw file](https://github.com/servo/servo/blob/04b7f38f5fa9e58d8349e9c6dfe4c2e13a812d52/components/script/dom/workerglobalscope.rs#L62)):</sup>
Not processing, but sending them to the devtools server.

---

<sup>**[components/script/dom/workerglobalscope.rs, line 66 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6829#-JvaSN04G__KBAO5lKOl)** ([raw file](https://github.com/servo/servo/blob/04b7f38f5fa9e58d8349e9c6dfe4c2e13a812d52/components/script/dom/workerglobalscope.rs#L66)):</sup>
There's an extra 's' on "exist".

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6829)

**Comment by jdm** [comment]
```
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:345:1: 350:2 error: conflicting implementations for trait `dom::bindings::trace::JSTraceable` [E0119]
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:345 impl<T> JSTraceable for IpcReceiver<T> where T: Deserialize + Serialize {
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:346     #[inline]
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:347     fn trace(&self, _: *mut JSTracer) {
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:348         // Do nothing
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:349     }
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:350 }
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:345:1: 350:2 help: run `rustc --explain E0119` to see a detailed explanation
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:373:1: 378:2 note: note conflicting implementation here
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:373 impl<T> JSTraceable for IpcReceiver<T> where T: Deserialize + Serialize {
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:374     #[inline]
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:375     fn trace(&self, _: *mut JSTracer) {
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:376         // Do nothing
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:377     }
/home/servo/buildbot/slave/android/build/components/script/dom/bindings/trace.rs:378 }
error: aborting due to previous error
```

**Comment by Wafflespeanut** [comment]
*sigh*, the `IpcReceiver` has already been implemented (**Moral:** Don't be so cocky!) -_-

**Comment by SimonSapin** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6829)

**Comment by Wafflespeanut** [comment]
Hmm, there's something wrong with the `script_task`. All the tests in the log show a few lines of `script_task` in their backtrace. And, the crashes are a result of an `unwrap` somewhere.

**Comment by jdm** [comment]
Guh, I was sure I left a comment about this at one point and then couldn't find it in reviewable: https://github.com/servo/servo/pull/6829/files#diff-91ad86111bfa2f963e7769c3edf5a28fR100

This is broken in the case when we don't launch with devtools. I thought I asked you to test this case?

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 2 of 2 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6829)

**Pull request merged**
