### PR TITLE
style: Switch to FxHash for the style system.

### PR DESCRIPTION
**Pull request by emilio**
This improves stylist rebuild times by a pretty neat amount, see [bug 1386443](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=1386443).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17946)

### CODE REVIEW

**Comment by emilio** [comment]
(also, @bzbarsky may want to review)

**Comment by mbrubeck** [comment]
It looks like the only use of `fnv` in Stylo is now in the `selectors` crate. Should we convert that too, and reduce the number of crates in the Stylo build?

**Comment by bzbarsky** [comment]
The patch seems pretty straightforward.  My question is where the free lunch comes from.

That is, given the assumption that FnvHash is competently written, if it's this much slower that must be because it's able to do something that FxHash doesn't do.  Presumably we don't care about that something, but do we know what it is and why we don't care about it?

**Comment by bholley** [comment]
Is it just that the hashing algorithm is faster? I thought we mostly didn't use the hashing algorithm, since we have precomputed hashes on nsIAtom. Unless we have significant traffic on non-atom-keyed hashmaps? If so, what are they?

As for selectors, seems like we should either remove or compile out the dependency on FnvHash, since we don't actually use the codepath in stylo (we use precomputed hash). That could be a followup E-Easy bug though.

**Comment by emilio** [comment]
> Is it just that the hashing algorithm is faster? I thought we mostly didn't use the hashing algorithm, since we have precomputed hashes on nsIAtom. Unless we have significant traffic on non-atom-keyed hashmaps? If so, what are they?

We're still hashing that hash, afaict.

And re @bzbarsky's questions, I think I'd rather point to https://github.com/rust-lang/rust/pull/37229, which has already pretty much all the discussion I can imagine :)

**Comment by emilio** [comment]
I'm working on something better than this :)

**Pull request closed without merging**
