### PR TITLE
Implement compact/type attributes for HTMLUListElement

### PR DESCRIPTION
**Pull request by simonwuelker**
Implement
* https://html.spec.whatwg.org/multipage/#dom-ul-compact
* https://html.spec.whatwg.org/multipage/#dom-ul-type

[try run](https://github.com/Wuelle/servo/actions/runs/10683958384)

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
Does changing the values of these attributes visually affect the content in other browsers?

**Comment by Wuelle** [comment]
Both firefox and chrome seem to ignore the `compact` attribute but change the marker based on `type`

**Comment by Wuelle** [comment]
We already do that: https://github.com/servo/servo/blob/e857cdf022f319ae3fbd54e10e279ab43485995b/resources/presentational-hints.css#L26-L29

**Comment by jdm** [comment]
Oh, excellent!

**Review by jdm — APPROVED** [review]

**Pull request merged**
