### PR TITLE
Bound sampler buffer, add length feedback message, fix intermittence in test

### LINKED ISSUE #23109: Intermittent failure in sampling profiler test
```
     Running target/debug/deps/hang_monitor_tests-d7bcb6b01769dde1
running 3 tests
Enabling profiler.
test test_hang_monitoring_unregister ... ok
Disabling profiler.
Resolving 1/1
test test_sampler ... FAILED
test test_hang_monitoring ... ok
failures:
---- test_sampler stdout ----
thread 'test_sampler' panicked at 'assertion failed: data.len() > 1', components/background_hang_monitor/tests/hang_monitor_tests.rs:49:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:209
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:482
   5: core::ptr::real_drop_in_place
             at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:412
   6: hang_monitor_tests::test_sampler
             at components/background_hang_monitor/tests/hang_monitor_tests.rs:49
   7: hang_monitor_tests::test_sampler::{{closure}}
             at components/background_hang_monitor/tests/hang_monitor_tests.rs:16
   8: core::ops::function::FnOnce::call_once
             at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libcore/ops/function.rs:231
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at src/libtest/lib.rs:1513
             at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libcore/ops/function.rs:231
             at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/liballoc/boxed.rs:749
  10: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  11: test::run_test::run_test_inner::{{closure}}
             at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:276
             at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
failures:
    test_sampler
test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```
This is a test I added in #23080 which appears to fail nondeterministically despite my attempts to write in ways that would discourage that.

### PR DESCRIPTION
**Pull request by gterzian**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #23109 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23139)

### CODE REVIEW

**Comment by gterzian** [comment]
@jdm I think this should fix the intermittent issue in the tests, and I hope this isn't just extra code to support the tests, since one can also imagine the extra message later becoming useful to show feedback on the sampling process in devtools and the likes, a little bit like the performance feature show below...

Screen Shot 2019-03-30 at 1 37 23 PM

**Comment by jdm** [comment]
Sending the constellation a message after every single sample for each thread seems excessive :) to fix the other ntermittency of the test, I think we should just check that >0 samples were taken and wait for 100ms.

For the bounding, a VecDeque is a good idea, but 100 is a really small number of samples. It should be configurable via the enabling message, and we should try to bound it by time, rather than number of samoles, defaulting to 10s.

**Comment by gterzian** [comment]
@jdm Ok, I've added an attempt to limit the sampling in time. 

Re checking the number of samples in the test, it appears to me that an issue there is that we only receive the data after having stopped the sampling, so we could do another round if not enough have been taken, and it would seem to make the test too complicated(we would also have to limit the number of tries, and decide on what to do in the case that all tries resulted in not enough frames having been sampled). 

I've just increased the sleep to 100ms, which hopefully reduces the chance of sampling less than 2 rounds to something close to zero(I get 8 or 9 samples taken on a few test runs locally).

**Comment by jdm** [comment]
@bors-servo r+
Nuce!

**Pull request merged**
