### PR TITLE
[WIP] Use rustup to manage toolchains

### LINKED ISSUE #11361: Use rustup to get nightly rust
Since every time build servo will use nightly rust compiler, is it a good idea to use rustup and overload servo path to build servo with nightly rustc? I mean, since there is a rust version manager, why not just use it?

### PR DESCRIPTION
**Pull request by shinglyu**
[DO NOT MERGE]
This is an early prototype of using rustup to replace our rustc/cargo download logic. I'd like to collect some feedback before I start working on other platforms.

I'd also love to hear your opinion on how to approach the following issues:
* Windows/OSX build: any special rustup tricks?
* Android build: Should we use rustup at all? 
* Cross compiling: What kind of use cases are there?

ping @metajack 

---

- [x] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #11361 .

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17927)

### CODE REVIEW

**Comment by SimonSapin** [comment]
* `rust-toolchain` should replace `rust-commit-hash`. If we have both they’ll get out of sync. We can [parse e.g. `https://static.rust-lang.org/dist/2017-08-01/channel-rust-nightly.toml` and `https://api.github.com/repos/rust-lang/rust/commits/37c7d0ebb` to go from a nightly date to a full SHA1 hash](https://github.com/servo/servo/blob/dc244ad9e93cf606352594176987aa73ce4ed74c/python/servo/devenv_commands.py#L273-L279).
* I’d like to have a solution or work-around for https://github.com/rust-lang-nursery/rustup.rs/issues/1099 before this is merged, so that compilation times do not regress by 15~50%.
* For nigthly vs stable Rust, perhaps it’d work out to have both use `./rust-toolchain` and the root of the repository and `./ports/geckolib/rust-toolchain`? The `./mach build-geckolib` command already uses `with cd(path.join("ports", "geckolib"))`.

**Comment by shinglyu** [comment]
@SimonSapin: Thanks for the first two comments! As for the nightly vs stable issue, is geckolib the only case we use stable rust? If so would it be safe to remove (at least part) of the `stable` flags and use `rust-toolchain` to control this instead?

**Comment by shinglyu** [comment]
Also if not using `master-alt` will hurt the performance badly, I can land the rustup feature prefed-off. Because the only people who need this eagerly is the people working on embedding, so I guess pref-on rustup for them is not a big deal.

**Comment by SimonSapin** [comment]
Yes, geckolib is the only case where we use stable Rust. "Stable Rust version" in the context of Servo really means "minimum version that Firefox wants to support". (Search for "Mozilla-central can use" in https://wiki.mozilla.org/Rust_Update_Policy_for_Firefox.)

And, indeed, LLVM assertions are already disabled in official stable channel builds, so "alt" toolchains are not relevant there.

-----

I think it’s fine to require that `rustup` is available for building Servo. Eventually I’d like to entirely remove our code for downloading tarballs and setting `$PATH` environment variables, and leave that job to rustup. I’m not sure what’s the best way to handle alt toolchains until they’re natively supported by rustup, though.

**Comment by metajack** [comment]
@shinglyu I believe the plan is that rustup will have access to alt toolchains soon.

**Comment by shinglyu** [comment]
OK! I'll  keep an eye on the alt-toolchains support for rustup

**Comment by paulrouget** [comment]
> I believe the plan is that rustup will have access to alt toolchains soon.

Is there any issue/PR we can look at?

**Comment by SimonSapin** [comment]
https://github.com/rust-lang-nursery/rustup.rs/issues/1099 and https://internals.rust-lang.org/t/disabling-llvm-assertions-in-nightly-builds/5388 still need a decision on what’s the plan exactly.

**Comment by SimonSapin** [comment]
Done in https://github.com/servo/servo/pull/19395.

**Pull request closed without merging**
