### PR TITLE
Upgrade to rustc 1.22.0-nightly (c6884b12d 2017-09-30)

### PR DESCRIPTION
**Pull request by SimonSapin**
A new `AddAssign` impl in the standard library made inference ambiguous.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18693)

### CODE REVIEW

**Comment by nox** [comment]
Wait, that's not a Rust regression…?

**Comment by nox** [comment]
What is the new `AddAssign` impl that causes this issue?

**Comment by SimonSapin** [comment]
`impl<'a> AddAssign<&'a usize> for usize` https://github.com/rust-lang/rust/pull/41336

**Comment by nox** [comment]
@bors-servo r+ 

https://github.com/rust-lang/rust/pull/41336#issuecomment-333381539

**Pull request merged**
