### PR TITLE
Update num_cpus, libc, openssl, threadpool, smallvec, string_cache, gleam, gl_generator, x11

### PR DESCRIPTION
**Pull request by mbrubeck**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12294)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
What has happened here?!!

    Traceback (most recent call last):
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/executors/base.py", line 149, in run_test
        result = self.do_test(test)
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/executors/executorservo.py", line 133, in do_test
        self.proc.kill()
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 749, in kill
        self.proc.kill(sig=sig)
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 165, in kill
        send_sig(signal.SIGTERM)
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 152, in send_sig
        os.killpg(pid, sig)
    OSError: [Errno 1] Operation not permitted

**Comment by KiChjang** [comment]
@bors-servo retry
* #InfraOnFire

**Comment by mbrubeck** [comment]
@bors-servo retry

* infra

**Pull request merged**
