### PR TITLE
Add size_of tests for geckolib selectors

### PR DESCRIPTION
**Pull request by SimonSapin**
First step of https://bugzilla.mozilla.org/show_bug.cgi?id=1364148

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16870)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r+

Thanks for doing this :). Can't wait this to bitrot my patches though ;)

**Comment by emilio** [comment]
Well, should the other size_of/align_of tests also be converted to the use new crate? Feel free to file an E-easy about it, or r- this and address it.

**Comment by SimonSapin** [comment]
The ones in `script` and `style` are not `#[test]`, so they can’t easily use the same macro.

**Comment by SimonSapin** [comment]
Fixed unit tests

@bors-servo r=emilio

**Comment by SimonSapin** [comment]
Rebased.

@bors-servo r=emilio

**Pull request merged**
