### PR TITLE
Bump app_units; use from_f64_au

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18413)

### CODE REVIEW

**Comment by wafflespeanut** [comment]
error[E0277]: the trait bound `f32: std::ops::Mul<i32>` is not satisfied
       --> /home/servo/buildbot/slave/linux-dev/build/components/style/values/specified/length.rs:357:32
        |
    357 |         au_from_f32_round(inch * physical_inch)
        |                                ^ no implementation for `f32 * i32`
        |
        = help: the trait `std::ops::Mul<i32>` is not implemented for `f32`

    error: aborting due to previous error(s)

    error: Could not compile `style`.

**Comment by Manishearth** [comment]
@bors-servo retry

 - https://github.com/servo/servo/issues/18388

**Comment by Manishearth** [comment]
@bors-servo retry

 - still the position-sticky tests

**Comment by Manishearth** [comment]
@mrobinson can we disable the position-sticky tests? They've been causing intermittents all week.

**Pull request merged**
