### PR TITLE
Fix parsing of invalid perspective property values.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9301)

### CODE REVIEW

**Comment by eefriedman** [comment]
It's probably also worth testing `perspective: 0;` and `perspective: calc(0px);`.

**Comment by eefriedman** [comment]
Also, `perspective:1px; perspective: calc(0px);` doesn't seem to behave the same way comparing Chrome vs. Firefox.

**Comment by Ms2ger** [comment]
@bors-servo r-

Spec bug: https://lists.w3.org/Archives/Public/www-style/2016Jan/0020.html

**Comment by glennw** [comment]
@Ms2ger The current behaviour results in a divide by zero, which doesn't match any browser or spec, and is breaking browser.html in WR. What would you prefer to solve this for now?

**Comment by SimonSapin** [comment]
I suggest opening an issue to fix this per spec once it’s settled on the spec side, and in the mean time so something that seems sensible to avoid the division by zero (which panics, right?) The www-style thread suggests treating zero as either `none` or some small value like `1px`.

**Pull request closed without merging**
