### PR TITLE
Make it possible to reset options

### PR DESCRIPTION
**Pull request by paulrouget**
We want to be able to reset the options after servo gets deinitialized (in FxR for example).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22245)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I think that with a `RwLock<Opts>` in a `static` or `lazy_static`, you could return `RwLockReadGuard<'static, Opts>` instead of `&'static Opts`.

**Comment by paulrouget** [comment]
@SimonSapin thanks. It works.

**Comment by paulrouget** [comment]
It was initially impossible to initialize the options twice. This lifts this contrain.

**Comment by SimonSapin** [comment]
Diff looks good to me but this is not quite about shutdown anymore, is it? r+ with the PR title and description updated to what you think is appropriate.

**Comment by paulrouget** [comment]
Updated description and title.

@bors-servo r=SimonSapin

**Pull request merged**
