### PR TITLE
Substituing quickersort with pdqsort

### LINKED ISSUE #15244: Replace quickersort with pdqsort
The [style::stylist] module uses the [quickersort] crate, which provides a fast, unstable sort algorithm.  The new [pdqsort] crate provides an even faster (in almost all cases) unstable sort.  We can easily replace quickersort with pdqsort:

* In the `components/style` directory, update `Cargo.toml`, `lib.rs`, and `stylist.rs` to refer to pdqsort instead of quickersort.
* Build the code.  This should update the `Cargo.lock` file automatically.

[style::stylist]: https://github.com/servo/servo/blob/88cd8a3cf0d299a4dc066059d454fdbc395dbfeb/components/style/stylist.rs#L828-L831
[quickersort]: https://crates.io/crates/quickersort
[pdqsort]: https://crates.io/crates/pdqsort

### PR DESCRIPTION
**Pull request by Maaarcocr**
I have been working on issue number #15244. I have substituted quickersort with pdqsort in the style component. The changes I made affect: Cargo.toml, stylist.rs and lib.rs (all of them are in /components/style).

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15244 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because both library expose the same functionality, they differ in permance.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15269)

### CODE REVIEW

**Comment by emilio** [comment]
Looks good to me, but you have an extra merge commit that should go away before merging.

**Comment by Maaarcocr** [comment]
@emilio should there be just one commit? If so, does this mean that I need to create a new pull request with this change? (Sorry for being such a newbie)

**Comment by emilio** [comment]
Yes, there should be just one commit, but no need for a new pull request, you can just force-push to the same branch.

And no problem! Everyone has been a newbie some time ago :)

**Comment by Maaarcocr** [comment]
@emilio I hope I have squashed everything to one commit!

**Comment by emilio** [comment]
@bors-servo r+

Looks great! Thanks @Maaarcocr :)

**Pull request merged**
