### PR TITLE
Update Rust to 1.12.0-nightly (1deb02ea6 2016-08-12)

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12846)

### CODE REVIEW

**Comment by nox** [comment]
Silly me... Blocked on https://github.com/Manishearth/rust-tenacious/pull/19.

**Comment by jdm** [comment]
r+ when that's merged.

**Comment by nox** [comment]
Actually rust-tenacious will never be correct anymore with MIR, and we don't actually use it anymore anyway since @eddyb removed our uses of return_address.

**Comment by nox** [comment]
@jdm Feel free to r+, not doing it on your behalf because I removed rust-tenacious.

**Comment by nox** [comment]
Blocked on compiletest-rs being updated.

**Comment by nox** [comment]
compiletest just had to be updated to 0.2, should be ok now.

**Pull request merged**
