### PR TITLE
Report memory usage from LayoutThreadData Stylist [#7038]

### PR DESCRIPTION
**Pull request by pkondzior**
@jdm PTAL I'm not sure what is the approach of updating cargo components here, I've made a pull request https://github.com/servo/heapsize/pull/54 but it has to be landed first before merge and version bump.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10088)

### CODE REVIEW

**Comment by ecoal95** [comment]
You should be able to update heapsize using:

```
./mach cargo-update -p heapsize
```

Hopefully you don't run into any version number conflicts.

**Comment by pkondzior** [comment]
@ecoal95 fixed, thanks!

**Comment by ecoal95** [comment]
This looks good to me :)

@bors-servo: r+

**Comment by larsbergstrom** [comment]
@bors-servo retry
- infra

**Pull request merged**
