### PR TITLE
android: Rename the Android app to reflect servo.org ownership and `servoshell`

### LINKED ISSUE #32538: Update Servo's Android apps `org` name
The android (java) app still is named `org.mozilla.servo`. Since (as far as I know) servo is no longer affiliated with the mozilla org, the package name should probably be updated to not reference mozilla anymore and instead be `org.servo.servoapp` or similar.

### PR DESCRIPTION
**Pull request by mrobinson**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #32538.
- [x] These changes do not require tests because they don't really change behavior.

### CODE REVIEW

**Comment by mrobinson** [comment]
I still need to test this in the emulator.

**Comment by jschwe** [comment]
Can all the `.java` files really be deleted, or did you perhaps forget to commit the renamed files?

**Comment by mrobinson** [comment]
> Can all the `.java` files really be deleted, or did you perhaps forget to commit the renamed files?

Yep, I forgot to commit them. It's surprising that the build succeeded anyway.

**Review by mukilan — APPROVED** [review]

**Comment by mrego** [comment]
Should we change the version number of the Android app to something like 0.1, or 0.0.1 (right now it's 1.0 which might be confusing).

**Pull request merged**
