### PR TITLE
Refactor FormControl trait

### PR DESCRIPTION
**Pull request by aopicier**
The trait is now implemented for HTMLFooElement instead of
&HTMLFooElement and does no longer require an impl body.

Suggested by @Manishearth

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7801)

### CODE REVIEW

**Comment by jdm** [comment]
This is great!

**Comment by Manishearth** [comment]
You need to alphabetize the use statements:

```./components/script/dom/htmlformelement.rs:12: use statement is not in alphabetical order
	expected: dom::bindings::codegen::InheritTypes::EventTargetCast
	found: dom::bindings::codegen::InheritTypes::{ElementBase, ElementCast}
./components/script/dom/htmlformelement.rs:13: use statement is not in alphabetical order
	expected: dom::bindings::codegen::InheritTypes::HTMLDataListElementCast
	found: dom::bindings::codegen::InheritTypes::EventTargetCast
./components/script/dom/htmlformelement.rs:14: use statement is not in alphabetical order
	expected: dom::bindings::codegen::InheritTypes::HTMLElementCast
	found: dom::bindings::codegen::InheritTypes::HTMLDataListElementCast
./components/script/dom/htmlformelement.rs:15: use statement is not in alphabetical order
	expected: dom::bindings::codegen::InheritTypes::HTMLFormElementCast
	found: dom::bindings::codegen::InheritTypes::HTMLElementCast
./components/script/dom/htmlformelement.rs:16: use statement is not in alphabetical order
	expected: dom::bindings::codegen::InheritTypes::HTMLFormElementDerived
	found: dom::bindings::codegen::InheritTypes::HTMLFormElementCast
./components/script/dom/htmlformelement.rs:17: use statement is not in alphabetical order
	expected: dom::bindings::codegen::InheritTypes::HTMLInputElementCast
	found: dom::bindings::codegen::InheritTypes::HTMLFormElementDerived
./components/script/dom/htmlformelement.rs:18: use statement is not in alphabetical order
	expected: dom::bindings::codegen::InheritTypes::{ElementBase, ElementCast}
	found: dom::bindings::codegen::InheritTypes::HTMLInputElementCast
```

(This can be verified with `./mach test-tidy`)

Other than that, r=me

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Comment by aopicier** [comment]
Now it crashes in `dom/nodes/Document-createElement-namespace.html`. I can reproduce this crash on master without my changes. Here is what I see:

 `0:03.45 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:12994) "thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /home/ph/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:166"`

**Comment by jdm** [comment]
@bors-servo: retry
* #7731

**Pull request merged**
