### PR TITLE
Fix #7093

### LINKED ISSUE #7093: to_owned() should be used instead of to_string() in hosts.rs
/home/boghison/Projects/servo/components/net_traits/hosts.rs:54:35: 54:63 error: str.to_owned() is more efficient than str.to_string(), please use it instead, #[deny(str_to_string)] on by default
/home/boghison/Projects/servo/components/net_traits/hosts.rs:54                 host_table.insert(token.to_owned().to_string(), address.clone());

### PR DESCRIPTION
**Pull request by cuzbog**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7094)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Calling `to_owned()` twice doesn't make sense; once should be sufficient.

**Comment by boghison** [comment]
@Ms2ger Don't you think I would've tried? It doesn't work

**Comment by marcusklaas** [comment]
You're iterating over `&&str` here, I think. Maybe iterating over `ip_host.iter().skip(1).cloned()` or calling `host_table.insert((*token).to_owned(), address.clone());` will work as well. Those could just compile down to the same thing, though.

**Comment by boghison** [comment]
I changed it to (*token), as to_owned().to_owned() sounds a little weird

**Pull request closed without merging**
