### PR TITLE
Update mp3-metatada and thus audio-video-metadata

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18581)

### CODE REVIEW

**Comment by KiChjang** [comment]
Rebase and r=me.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by GuillaumeGomez** [comment]
```
command timed out
```

**Comment by jdm** [comment]
@bors-servo: retry
* timeout

**Pull request merged**
