### PR TITLE
Implementing blur filter.

### PR DESCRIPTION
**Pull request by Adenilson**

### CODE REVIEW

**Comment by pcwalton** [comment]
You are also going to need to adjust the overflow regions, or else display list optimization might clip out the edges of a blurred object (for example, if a blurred object is off the screen, but the edges of the blur are slightly on the screen). See how `BLUR_INFLATION_FACTOR` is used for an example.

**Comment by metajack** [comment]
@Adenilson Planning on addressing these soon?

**Comment by Adenilson** [comment]
Yep, I was busy last week with the placeholder feature #5330 but will resume work on it.

**Comment by metajack** [comment]
Assigning @SimonSapin since he did the review.

**Comment by SimonSapin** [comment]
Move to #5496.

**Pull request closed without merging**
