### PR TITLE
script: Make most of 2D canvas and WebGL run over IPC.

### PR DESCRIPTION
**Pull request by pcwalton**
To actually make the multiprocess communication work, we'll need to
reroute the task creation to the pipeline or the compositor. But this
works as a first step.

r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6616)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Please wait for #6607 and fix the local file paths.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes +S-blocked-on-external 

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[components/canvas/canvas_paint_task.rs, line 175 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCerHc48kuwN0GpBqx)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/canvas/canvas_paint_task.rs#L175)):</sup>
Add a TODO to share these among all canvases for the same script task.

---

<sup>**[components/canvas/Cargo.toml, line 34 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCYRqyn4VIAl4B4pDz)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/canvas/Cargo.toml#L34)):</sup>
Let's move back to crates.io.

---

<sup>**[components/canvas/webgl_paint_task.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCfAmEGr0pWiwYi_SV)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/canvas/webgl_paint_task.rs#L150)):</sup>
Add a TODO to share this among all canvases for the same script task.

---

<sup>**[components/canvas_traits/Cargo.toml, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuC_QVwLksD_2UwQ0en)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/canvas_traits/Cargo.toml#L26)):</sup>
Revert?

---

<sup>**[components/canvas_traits/lib.rs, line 45 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuC_dvyYPrFAv0zXEpb)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/canvas_traits/lib.rs#L45)):</sup>
Let's call it FromLayout.

---

<sup>**[components/canvas_traits/lib.rs, line 61 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuC_sfYT7VqSaFk2Hlj)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/canvas_traits/lib.rs#L61)):</sup>
Add a TODO to split CanvasMsg into InternalCanvasMsg and ExternalCanvasMsg, with only InternalCanvasMsg deriving Deserialize/Serialize.

---

<sup>**[components/layout/wrapper.rs, line 979 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCfcI5czHmhUFh6jTe)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/layout/wrapper.rs#L979)):</sup>
I don't believe this is used.

---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCfgt0pX8w6ArPYSXV)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/script/dom/htmlcanvaselement.rs#L112)):</sup>
I don't think this is used.

---

<sup>**[components/util/logical_geometry.rs, line 170 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCegptInQ9OKeGo5ww)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/util/logical_geometry.rs#L170)):</sup>
Why is this change necessary?

---

<sup>**[components/util/task_state.rs, line 14 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCejrv8oFtWXuVdu1T)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/util/task_state.rs#L14)):</sup>
?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6616)

**Comment by pcwalton** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[components/util/logical_geometry.rs, line 170 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCegptInQ9OKeGo5ww)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/util/logical_geometry.rs#L170)):</sup>
I honestly don't know. I suspect a rustc bug.

---

<sup>**[components/util/task_state.rs, line 14 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCejrv8oFtWXuVdu1T)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/util/task_state.rs#L14)):</sup>
I honestly have no idea why this was working before, but it seems to be required now. rustc bug maybe?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6616)

**Comment by pcwalton** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[components/layout/wrapper.rs, line 979 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCfcI5czHmhUFh6jTe)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/layout/wrapper.rs#L979)):</sup>
It is used in `CanvasFragmentInfo::new()`.

---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCfgt0pX8w6ArPYSXV)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/script/dom/htmlcanvaselement.rs#L112)):</sup>
It is used in `CanvasFragmentInfo::new()`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6616)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/layout/wrapper.rs, line 979 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCfcI5czHmhUFh6jTe)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/layout/wrapper.rs#L979)):</sup>
Right, but CanvasFragmentInfo.ipc_renderer does not appear to be used anywhere.

---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuCfgt0pX8w6ArPYSXV)** ([raw file](https://github.com/servo/servo/blob/baf4ea437e6b5928fd8e73de77f1dd33e90db115/components/script/dom/htmlcanvaselement.rs#L112)):</sup>
Transitively, same as above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6616)

**Comment by pcwalton** [comment]
Rebased and removed `get_ipc_renderer` and friends. r? @jdm

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-rebase +S-needs-code-changes 
There's still a local file path to serde remaining in a toml file.

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6616)

**Comment by pcwalton** [comment]
@jdm I'll fix that up once @erickt reviews my PR. I had to put it in there to build at all because Cargo overrides don't work when you're adding new feature flags—you have to directly hardcode a local path in your Cargo.toml.

**Comment by pcwalton** [comment]
(Or I could fork serde—which I'm about to do anyway since I can't contact @erickt.)

**Comment by pcwalton** [comment]
Rebased.

**Comment by pcwalton** [comment]
Rebased.

**Comment by jdm** [comment]
-S-awaiting-review +S-awaiting-answer 

---

Reviewed 1 of 8 files at r3, 11 of 11 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[components/canvas/canvas_paint_task.rs, line 173 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuRQaP9B1ek3yradzFo)** ([raw file](https://github.com/servo/servo/blob/48022c806393d933bd97c0c33aa3bbcab8976521/components/canvas/canvas_paint_task.rs#L173)):</sup>
Any chance we can have a sugary function that just takes the appropriate receiver and sender and hides these details?

---

<sup>**[components/canvas/canvas_paint_task.rs, line 174 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuRQPqXLXdkxLnc9xZV)** ([raw file](https://github.com/servo/servo/blob/48022c806393d933bd97c0c33aa3bbcab8976521/components/canvas/canvas_paint_task.rs#L174)):</sup>
What's the drop here for?

---

<sup>**[components/canvas/webgl_paint_task.rs, line 147 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6616#-JuRQoEviWsA_QCHZnv3)** ([raw file](https://github.com/servo/servo/blob/48022c806393d933bd97c0c33aa3bbcab8976521/components/canvas/webgl_paint_task.rs#L147)):</sup>
Same as previous.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6616)

**Comment by pcwalton** [comment]
Updated `ipc-channel` to add the requested sugar.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-rebase +S-blocked-on-external 

We still need to wait for #6607.

---

Reviewed 15 of 15 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6616)

**Comment by jdm** [comment]
@bors-servo: r-
$ ./mach test-tidy
```
components/canvas_traits/Cargo.toml:26: found asterisk instead of minimum version number
components/canvas_traits/Cargo.toml:35: found asterisk instead of minimum version number
```

**Comment by jdm** [comment]
@bors-servo: r-
```
$ ./mach test-tidy

components/canvas_traits/Cargo.toml:35: found asterisk instead of minimum version number
```

**Comment by jdm** [comment]
```
/_mozilla/mozilla/canvas/drawimage_html_image_11.html
-----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_10.html
-----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_1.html
----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_12.html
-----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_2.html
----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_3.html
----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_4.html
----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_5.html
----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_6.html
----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_7.html
----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_8.html
----------------------------------------------------
FAIL [Parent]
```

**Comment by pcwalton** [comment]
I have rewritten much of this patch to be sandbox-safe by having the script task ask the constellation to create the canvas renderers instead of doing it itself. In the process, those WPT failures now seem fixed.

This introduces the notion of a "canvas ID", which is currently unused, but will be used when we stop doing readback. It allows the layout task to uniquely refer to a canvas so that the paint task will know where to get the native surfaces from.

r? @jdm

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 36 of 36 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6616)

**Comment by jdm** [comment]
These same tests failed on the last two runs:
```
/2dcontext/the-canvas-state/2d.state.saverestore.stackdepth.html
----------------------------------------------------------------
TIMEOUT [Parent]
/dom/ranges/Range-insertNode.html
---------------------------------
TIMEOUT [Parent]
/dom/ranges/Range-mutations.html
--------------------------------
TIMEOUT [Parent]
/dom/ranges/Range-surroundContents.html
---------------------------------------
TIMEOUT [Parent]
```

**Comment by pcwalton** [comment]
I suspect the timeout issue is not having #6705, and I wouldn't be surprised if the problem with the range tests is that the bots are running out of file descriptors due to too many iframes. @larsbergstrom, do you have a way I can test this theory?

**Comment by larsbergstrom** [comment]
I'm a little surprised that there's nothing in the logs - typically, if we run out of file descriptors, there's a low-level failure that turns into a `panic!` and gets reported in the logs. That said, I'm fine with #6707 to increase our fd limits from the default 1024.

**Comment by pcwalton** [comment]
OK, I believe that #6707 plus the WPT release builds will make this get through WPT.

**Comment by jdm** [comment]
```
/html/semantics/embedded-content/the-img-element/relevant-mutations.html
------------------------------------------------------------------------
FAIL expected TIMEOUT src removed
PASS expected TIMEOUT inserted into picture
PASS expected TIMEOUT removed from picture
PASS expected TIMEOUT parent is picture, previous source inserted
PASS expected TIMEOUT parent is picture, previous source removed
PASS expected TIMEOUT parent is picture, previous source has srcset set
PASS expected TIMEOUT parent is picture, previous source has srcset changed
PASS expected TIMEOUT parent is picture, previous source has srcset removed
PASS expected TIMEOUT parent is picture, previous source has sizes set
PASS expected TIMEOUT parent is picture, previous source has sizes changed
PASS expected TIMEOUT parent is picture, previous source has sizes removed
PASS expected TIMEOUT parent is picture, previous source has media set
PASS expected TIMEOUT parent is picture, previous source has media changed
PASS expected TIMEOUT parent is picture, previous source has media removed
PASS expected TIMEOUT parent is picture, previous source has type set
PASS expected TIMEOUT parent is picture, previous source has type changed
PASS expected TIMEOUT parent is picture, previous source has type removed
FAIL crossorigin state not changed: absent, removeAttribute
FAIL crossorigin state not changed: empty to anonymous
FAIL crossorigin state not changed: anonymous to foobar
FAIL crossorigin state not changed: use-credentials to USE-CREDENTIALS
FAIL inserted into picture ancestor
FAIL removed from picture ancestor
FAIL ancestor picture has a source inserted
FAIL ancestor picture has a source removed
FAIL ancestor picture; previous sibling source inserted
FAIL ancestor picture; previous sibling source removed
FAIL parent is picture, following sibling source inserted
FAIL parent is picture, following sibling source removed
FAIL parent is picture, following sibling source has srcset set
FAIL media on img set
FAIL type on img set
FAIL class on img set
FAIL alt on img set
FAIL src on previous sibling source set
FAIL class on previous sibling source set
FAIL inserted/removed children of img
FAIL picture is inserted
FAIL picture is removed
FAIL parent is picture, following img inserted
FAIL parent is picture, following img removed
FAIL parent is picture, following img has src set
FAIL parent is picture, following img has srcset set
FAIL parent is picture, following img has sizes set
/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm
------------------------------------------------------------
TIMEOUT expected FAIL [Parent]
/2dcontext/building-paths/canvas_complexshapes_beziercurveto_001.htm
--------------------------------------------------------------------
TIMEOUT expected FAIL [Parent]
```

**Comment by pcwalton** [comment]
I think we may need canvas shmem to avoid a timeout. Also can I just update the test expectations for that image onload stuff, @jdm?

**Comment by pcwalton** [comment]
Homu seems to refuse to pick up canvas shmem.

**Comment by jdm** [comment]
@pcwalton Sure.

**Pull request merged**
