### PR TITLE
Fix radial gradients for html canvas element

### PR DESCRIPTION
**Pull request by pylbrecht**
The latest version of raqote provides a fix for properly handling boundary conditions for TwoCircleRadialGradients.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #25331

- [x] There are tests for these changes

### CODE REVIEW

**Comment by pylbrecht** [comment]
@jrmuizel fixed https://github.com/jrmuizel/raqote/issues/118, which should make some tests pass.

**Comment by jdm** [comment]
```
9 unexpected results that are NOT known-intermittents:
  ▶ Unexpected subtest result in /html/canvas/element/drawing-images-to-the-canvas/drawimage_canvas.html:
  └ PASS [expected FAIL] Test scenario 10: sx = 0, sy = 0, sw = 50, sh = 50, dx = 0, dy = 0, dw = 200, dh = 200 --- Pixel 20,20 should be black.
  ▶ Unexpected subtest result in /html/canvas/element/drawing-images-to-the-canvas/drawimage_canvas.html:
  └ PASS [expected FAIL] Test scenario 10: sx = 0, sy = 0, sw = 50, sh = 50, dx = 0, dy = 0, dw = 200, dh = 200 --- Pixel 20,99 should be black.
  ▶ Unexpected subtest result in /html/canvas/element/drawing-images-to-the-canvas/drawimage_canvas.html:
  └ PASS [expected FAIL] Test scenario 10: sx = 0, sy = 0, sw = 50, sh = 50, dx = 0, dy = 0, dw = 200, dh = 200 --- Pixel 99,20 should be black.
  ▶ Unexpected subtest result in /html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.cone.beside.worker.html:
  └ PASS [expected FAIL] 2d
  ▶ Unexpected subtest result in /html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch3.worker.html:
  └ PASS [expected FAIL] 2d
  ▶ Unexpected subtest result in /html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch1.worker.html:
  └ PASS [expected FAIL] 2d
  ▶ Unexpected subtest result in /html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch2.html:
  └ PASS [expected FAIL] OffscreenCanvas test: 2d.gradient.radial.touch2
  ▶ Unexpected subtest result in /html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.cone.beside.html:
  └ PASS [expected FAIL] OffscreenCanvas test: 2d.gradient.radial.cone.beside
  ▶ Unexpected subtest result in /html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch1.html:
  └ PASS [expected FAIL] OffscreenCanvas test: 2d.gradient.radial.touch1
  ▶ Unexpected subtest result in /html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch2.worker.html:
  └ PASS [expected FAIL] 2d
  ▶ Unexpected subtest result in /html/canvas/offscreen/fill-and-stroke-styles/2d.gradient.radial.touch3.html:
  └ PASS [expected FAIL] OffscreenCanvas test: 2d.gradient.radial.touch3
```

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
