### PR TITLE
Add a "mach test-wpt --chaos" mode for reproducing intermittent failures using rr

### PR DESCRIPTION
**Pull request by mbrubeck**
This adds a new `--chaos` flag to the `test-wpt` and `test-css` commands.  This will run a test repeatedly until it fails, recording it with the rr debugger in chaos mode. Requires a recent master build of rr.

```
./mach test-wpt --chaos test.html
```

is shorthand for:

```
./mach test-wpt --repeat-until-unexpected \
                --debugger rr \
                --debugger-args "record --chaos" \
                --include test.html
```

This PR currently includes changes to wptrunner which were also submitted upstream as w3c/wptrunner#170.  We should not merge this until that upstream PR is merged. CC @jgraham

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9607)

### CODE REVIEW

**Comment by jdm** [comment]
FYI: the wptrunner changes should be upstreamed, too.

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/servo/testing_commands.py, line 349 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9607#-KAGja-Anm44oOa2kR2Y:-KAGja-Anm44oOa2kR2Z:-827991477) ([raw file](https://github.com/servo/servo/blob/1aadb67e8ac6750a97f5bfd0da27c4249dc31709/python/servo/testing_commands.py#L349)):*
Maybe pop this argument since it doesn't exist further down the chain.

I guess it's OK for these to overwrite any user-supplied options?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9607)*

**Comment by mbrubeck** [comment]
@bors-servo r=jgraham

-S-awaiting-review

> FYI: the wptrunner changes should be upstreamed, too.

Done.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/servo/testing_commands.py, line 349 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9607#-KAGja-Anm44oOa2kR2Y:-KAGlOiqU_vcdxxdEF70:-499146009) ([raw file](https://github.com/servo/servo/blob/1aadb67e8ac6750a97f5bfd0da27c4249dc31709/python/servo/testing_commands.py#L349)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9607#-:-KAGlQVyeh87ffwZsQqw:-1817244323)*

**Comment by jdm** [comment]
@bors-servo: retry
* #8191

**Comment by jdm** [comment]
@bors-servo: retry
* git problem?

**Pull request merged**
