### PR TITLE
Add attributes for canvas shadows.

### PR DESCRIPTION
**Pull request by hyowon**
The first step of the implementation for shadows in canvas.
r? @nox @jdm 
cc @yichoi

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6337)

### CODE REVIEW

**Comment by nox** [comment]
Isn't it weird to just support the attributes but not actually do anything with them? Is the next step more significant to implement and that's why you submitted that part for now?

Apart from that and a few nits, I'll happily r+ it.

-S-awaiting-review +S-awaiting-answer +S-needs-code-changes 

---

Review status: all files reviewed, 9 unresolved discussions, all commit checks successful.
Reviewed files:
- components/canvas/canvas_paint_task.rs @ r1
- components/canvas_traits/lib.rs @ r1
- components/script/Cargo.toml @ r1
- components/script/dom/canvasrenderingcontext2d.rs @ r1
- components/script/dom/webidls/CanvasRenderingContext2D.webidl @ r1
- components/script/lib.rs @ r1
- tests/wpt/metadata/2dcontext/shadows/2d.shadow.attributes.shadowBlur.initial.html.ini @ r1
- tests/wpt/metadata/2dcontext/shadows/2d.shadow.attributes.shadowColor.initial.html.ini @ r1
- tests/wpt/metadata/2dcontext/shadows/2d.shadow.attributes.shadowColor.valid.html.ini @ r1
- tests/wpt/metadata/2dcontext/shadows/2d.shadow.attributes.shadowOffset.initial.html.ini @ r1
- tests/wpt/metadata/2dcontext/the-canvas-state/2d.state.saverestore.shadowBlur.html.ini @ r1
- tests/wpt/metadata/2dcontext/the-canvas-state/2d.state.saverestore.shadowColor.html.ini @ r1
- tests/wpt/metadata/2dcontext/the-canvas-state/2d.state.saverestore.shadowOffsetX.html.ini @ r1
- tests/wpt/metadata/2dcontext/the-canvas-state/2d.state.saverestore.shadowOffsetY.html.ini @ r1
- tests/wpt/metadata/html/dom/interfaces.html.ini @ r1

---

<sup>**[components/canvas/canvas_paint_task.rs, line 175 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZTEZAdEnSaaVTnOhT)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/canvas/canvas_paint_task.rs#L175)):</sup>
Wouldn't it help in the future if these two properties were a Point2D<f64> value?

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1069 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU07knWVfxHPaWkfx)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1069)):</sup>
Link to spec.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1073 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU1Eyqsj_DWxQ0Pfp)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1073)):</sup>
Ditto.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1078 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU20SUXi4_B_d0Axt)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1078)):</sup>
Ditto.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1082 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU2OwM1E-_qsnRSle)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1082)):</sup>
Ditto.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1087 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU2qJrLGw6RpePR0Z)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1087)):</sup>
Ditto.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1091 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU3HqlmgQpR5oxc3G)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1091)):</sup>
Ditto.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1096 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU3fVcBP1AzhWDrTM)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1096)):</sup>
Ditto.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1102 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU44vWuoqeMbrWcsQ)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1102)):</sup>
Ditto.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6337)

**Comment by hyowon** [comment]
I'll soon open a next pull request for actually drawing shadows.
I'm sorry if my separate PRs bother you.

---

Review status: all files reviewed, 9 unresolved discussions, all commit checks successful.

---

<sup>**[components/canvas/canvas_paint_task.rs, line 175 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZTEZAdEnSaaVTnOhT)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/canvas/canvas_paint_task.rs#L175)):</sup>
I think using individual x, y variables looks fine.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1069 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU07knWVfxHPaWkfx)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1069)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1073 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU1Eyqsj_DWxQ0Pfp)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1073)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1078 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU20SUXi4_B_d0Axt)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1078)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1082 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU2OwM1E-_qsnRSle)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1082)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1087 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU2qJrLGw6RpePR0Z)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1087)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1091 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU3HqlmgQpR5oxc3G)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1091)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1096 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU3fVcBP1AzhWDrTM)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1096)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 1102 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6337#-JrZU44vWuoqeMbrWcsQ)** ([raw file](https://github.com/servo/servo/blob/154f36884044f30d5db79ae4bbb9cba7a2e854ba/components/script/dom/canvasrenderingcontext2d.rs#L1102)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6337)

**Comment by nox** [comment]
@bors-servo: r+

No problem, given many things are unimplemented anyway everywhere it doesn't matter much whether the thing is complete or not.

-S-awaiting-answer -S-awaiting-review +S-awaiting-merge 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/script/dom/canvasrenderingcontext2d.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6337)

**Comment by hyowon** [comment]
I couldn't reproduce /css21_dev/html4/absolute-replaced-height-014.htm fail on my linux desktop.
It's weird because the reported failure doesn't seem to be related with my commit.

**Comment by nox** [comment]
@bors-servo: retry

#6342

**Pull request merged**
