### PR TITLE
XMLHttpRequestEventTarget should not be [NoInterfaceObject].

### LINKED ISSUE #4941: XMLHttpRequestEventTarget should not be [NoInterfaceObject]
Blocks #2525.

* Spec: <https://xhr.spec.whatwg.org/#xmlhttprequesteventtarget>.
* Code: `components/script/dom/webidls/XMLHttpRequestEventTarget.webidl`.
* Test: `/XMLHttpRequest/interfaces.html`.

This was changed in <https://www.w3.org/Bugs/Public/show_bug.cgi?id=27823>.

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
Fix #4941

### CODE REVIEW

**Comment by jdm** [comment]
```
thread '/Users/servo/buildbot/slave/mac2/build/tests/content/test_interfaces.html' panicked at 'ALERT: TEST-UNEXPECTED-FAIL | XMLHttpRequestEventTarget is in [object Object]: If this is failing: DANGER, are you sure you want to expose the new interface XMLHttpRequestEventTarget to all webpages as a property on the window? Do not make a change to this file without review from jdm or Ms2ger for that specific change!', /Users/servo/buildbot/slave/mac2/build/tests/contenttest.rs:122
```

**Comment by saneyuki** [comment]
@jdm oops! I forgot it... I pushed the additional fixup.

**Comment by jdm** [comment]
Go ahead and squash and merge :)

**Comment by saneyuki** [comment]
squashed!

**Pull request merged**
