### PR TITLE
Use a statically-linked libressl, instead of whatever system OpenSSL.

### PR DESCRIPTION
**Pull request by notriddle**
The next step will be creating a libtls-sys to wrap the new-style API...

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9613)

### CODE REVIEW

**Comment by jdm** [comment]
```
--- stderr

configure: WARNING: unrecognized options: --with-ccache

configure: WARNING: unrecognized options: --with-ccache

/home/travis/build/servo/servo/support/rust-libressl-static/libressl/missing: line 81: aclocal-1.15: command not found

WARNING: 'aclocal-1.15' is missing on your system.

         You should only need it if you modified 'acinclude.m4' or

         'configure.ac' or m4 files included by 'configure.ac'.

         The 'aclocal' program is part of the GNU Automake package:

         <http://www.gnu.org/software/automake>

         It also requires GNU Autoconf, GNU m4 and Perl in order to run:

         <http://www.gnu.org/software/autoconf>

         <http://www.gnu.org/software/m4/>

         <http://www.perl.org/>

make[1]: *** [/home/travis/build/servo/servo/support/rust-libressl-static/libressl/aclocal.m4] Error 127

make: *** [all] Error 2

thread '<main>' panicked at 'assertion failed: result.success()', /home/travis/build/servo/servo/support/rust-libressl-static/build.rs:13
```
Looks like we need automake in travis or something.

**Comment by notriddle** [comment]
I know what the tidy problem is (I had forgotten to update rust-libressl-static; it would pass if I re-ran the build).

**Comment by larsbergstrom** [comment]
Is the use of git submodules instead of Cargo dependencies just temporary so that you can introduce top-level overrides (until we get https://github.com/rust-lang/cargo/issues/942) for testing until we can land a feature or something else upstream in rust-openssl? I mainly ask because we've had a lot of problems with git submodules and have tried to move away from them on the whole.

I'd also want @metajack involved if we're talking about changing from OpenSSL to another SSL library, as decisions on that front can be both technical and organizational (e.g., which library do we have maintainers for here at Mozilla that can help us if there is a 0day?).

**Comment by notriddle** [comment]
Yes and yes.

**Comment by larsbergstrom** [comment]
Perfect - thanks much!

**Comment by jdm** [comment]
@notriddle Is this ready for review?

**Comment by notriddle** [comment]
Yes, it is.

**Comment by larsbergstrom** [comment]
@metajack I'd defer to you on a decision related to switching SSL libraries :-) Based on previous conversations, there are folks on Mozilla's security team we need to talk to before we can sign off on such a move.

@notriddle By ready for review, I assume you mean for that call? Because it's still got GH submodules and `paths` overrides, which we would prefer not to have in Servo, as mentioned above.

**Comment by notriddle** [comment]
Yeah, ready for the consideration would probably be a better way to
describe it...

**Comment by larsbergstrom** [comment]
@notriddle Great, thanks! Just wanted to make sure :-)

**Pull request closed without merging**
