### PR TITLE
Update crates to use bitflags 0.5

### PR DESCRIPTION
**Pull request by saurvs**
Part of https://github.com/servo/servo/issues/10077

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10396)

### CODE REVIEW

**Comment by nox** [comment]
I don't see any `Cargo.lock` changes so this is incomplete. Please use `./mach cargo-update -p` on bitflags and probably the crates that depend on it.

**Comment by metajack** [comment]
@bors-servo r+

Looks like the Cargo.lock's got updated.

**Comment by metajack** [comment]
@bors-servo r-

This adds new dependencies but doesn't remove the old ones. There should be only one dependency on bitflags or there should be an explanation here as to why we need 2 or 3 versions of it.

**Comment by saurvs** [comment]
After I updated all the crates to use bitflags 0.5, I ran `./mach build` and then `./mach update-cargo`. I guess the old versions of bitflags still remain in some files because the crates that aren't a part of Servo still use an older version of bitflags? If so, they need to be updated for Servo to completely depend on 0.5, and that'll take some more time.

**Comment by nox** [comment]
Superseded by #11191.

**Pull request closed without merging**
