### PR TITLE
layout: Load Web fonts asynchronously.

### LINKED ISSUE #7343: Don't eagerly, serialially download fonts.
cc @mbrubeck 

I was testing [hoverbear.org](http://hoverbear.org/) in Servo and noticed it loaded extremely slow (~17s). @mbrubeck and I did a bit of digging using `RUST_LOG=net` on the page and noticed that many web requests were being made to the server to download [KaTeX](https://khan.github.io/KaTeX/) fonts, which are fetched lazily in Firefox.

Firefox fetches zero KaTeX related fonts on the frontpage, and only 3 on [lcis](http://hoverbear.org/2014/11/15/lcis/) which has Math on it.

These bits of code are relevant:
[1](https://github.com/servo/servo/blob/master/components/gfx/font_cache_task.rs#L321)
```rust
    pub fn add_web_font(&self, family: Atom, src: Source) {
        let (response_chan, response_port) = channel();
        self.chan.send(Command::AddWebFont(family, src, response_chan)).unwrap();
        response_port.recv().unwrap();
    }
```

[2](https://github.com/servo/servo/blob/master/components/layout/layout_task.rs#L297-L303)
```rust
fn add_font_face_rules(stylesheet: &Stylesheet, device: &Device, font_cache_task: &FontCacheTask) {
    for font_face in stylesheet.effective_rules(&device).font_face() {
        for source in &font_face.sources {
            font_cache_task.add_web_font(font_face.family.clone(), source.clone());
        }
    }
}
```

To reproduce:

```bash
./mach build --release
RUST_LOG=net ./mach run http://hoverbear.org
```

### PR DESCRIPTION
**Pull request by pcwalton**
Improves page load times significantly.

Closes #7343.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7596)

### CODE REVIEW

**Comment by jdm** [comment]
I think I'd prefer this to use the [official async network request API](http://mxr.mozilla.org/servo/source/components/net_traits/lib.rs#217), rather than the ad-hoc version it currently does.

**Comment by pcwalton** [comment]
Updated to use the API suggested by @jdm.

**Comment by pcwalton** [comment]
@jdm Did you have any more comments on this? I don't recall if we discussed anything more on IRC.

**Comment by jdm** [comment]
My preference would be to integrate the network requests with some existing thread's event loop, rather than spawning two new threads per requested font.

**Comment by pcwalton** [comment]
I eliminated one thread by using the router and the other one by integrating into the layout task event loop. r? @mbrubeck

**Comment by jdm** [comment]
Thanks!

**Comment by mbrubeck** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/gfx/font_cache_task.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7596#-JzTfkNER9FjM2DMcu5M)** ([raw file](https://github.com/servo/servo/blob/7d77a5ee56a1014ada17a5827e7ed02660fa5635/components/gfx/font_cache_task.rs#L158)):</sup>
This should check whether the `ResponseComplete` message contains an `Err` status.

---

<sup>**[components/gfx/font_cache_task.rs, line 358 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7596#-JzToJNJu8MbuR4pcDxE)** ([raw file](https://github.com/servo/servo/blob/7d77a5ee56a1014ada17a5827e7ed02660fa5635/components/gfx/font_cache_task.rs#L358)):</sup>
This result isn't read anywhere. Should we remove it and just send and empty message?

---

<sup>**[components/layout/layout_task.rs, line 481 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7596#-JzTnfHsR9mdk6A2kjs1)** ([raw file](https://github.com/servo/servo/blob/7d77a5ee56a1014ada17a5827e7ed02660fa5635/components/layout/layout_task.rs#L481)):</sup>
Could we switch these to use descriptive names?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7596)

**Comment by pcwalton** [comment]
Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/layout/layout_task.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7596#-JzTnfHsR9mdk6A2kjs1)** ([raw file](https://github.com/servo/servo/blob/7d77a5ee56a1014ada17a5827e7ed02660fa5635/components/layout/layout_task.rs#L0)):</sup>
Hmm, Reviewable didn't seem to save the context here. Could you specify which names you're referring to?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7596)

**Comment by pcwalton** [comment]
Rebased and comments addressed except for the naming one. r? @mbrubeck

**Comment by jdm** [comment]
If you click on the link in the comment on github you'll see the right context.

**Comment by mbrubeck** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/layout/layout_task.rs, line 481 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7596#-JzTnfHsR9mdk6A2kjs1)** ([raw file](https://github.com/servo/servo/blob/7d77a5ee56a1014ada17a5827e7ed02660fa5635/components/layout/layout_task.rs#L481)):</sup>
port1, port2, port3, port4

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7596)

**Comment by pcwalton** [comment]
@mbrubeck Addressed the naming comment. r?

**Comment by mbrubeck** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7596)

**Pull request merged**
