### PR TITLE
Backport several style changes from Gecko (3)

### PR DESCRIPTION
**Pull request by Loirooriol**
This continues https://github.com/servo/servo/pull/29772.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by Loirooriol** [comment]
These are the extra changes that I had to do: 212733900 8eb5fa21f 32b3cb291 9822db5d3 93fb8861a f063308e3 f351d955a a6f9a364d 4f193fbf4 35bf5f0b0 2a1146091 4de990e41 7d8a87cd0 3d54b27a5 5c861b90c c204f3a96 2d8866d6c 40b7d87bb 3a2359808 5f46c027e b3e40479f 7cfbaf37f 2c8f33031 d669ab9a7

**Review by mrobinson — APPROVED** [review]
Great work.

**Pull request merged**
