### PR TITLE
Upgrade jni to 0.21.1

### PR DESCRIPTION
**Pull request by delan**
Split from #31278.

Co-authored-by: Martin Robinson <mrobinson@igalia.com>
Co-authored-by: Mukilan Thiyagarajan <mukilan@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they do not change functionality.

### CODE REVIEW

**Comment by mrobinson** [comment]
Here's my attempt as fixing these issues: https://github.com/servo/servo/commit/41bde5279866347c4e7da2688cf9c28b24bb893b

I'm stuck fighting with the borrow checker. It's unclear how to create a JValue from a Rust string and pass it to `JNIEnv::call_method` without requiring a double mutable borrow of `JNIEnv`.

**Comment by mukilan** [comment]
With [these](https://github.com/mukilan/servo/commit/d55eed82867fa34488f212054c298465d95a9248) changes on top of @mrobinson 's commit, I was able to get the android build to succeed and do a test run on my device.

The major change is the addition of the `<'local>` lifetime parameter to the JNI methods and methods that take both `&mut JNIEnv` and a some subtype of `&JObject`.  I only needed to add them to the methods that actually used both arguments, but I've added them to all JNI methods even where on the `env` parameter was used and the rest were ignored.

**Comment by mrobinson** [comment]
@mukilan Would you mind pushing your changes to @delan's branch so we can land them?

**Comment by mukilan** [comment]
@mrobinson I've rebased and pushed all the changes in a single commit. Please review whenever you get a chance.

**Review by mukilan — APPROVED** [review]

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
Nice!

**Pull request merged**
