### PR TITLE
Shutdown player when HTMLMediaElement is dropped

### LINKED ISSUE #22931: Removing iframe with video is causing Servo to crash
HTML:
```
<!DOCTYPE html>
<html>
    <body>
        <iframe id="iframe" src="http://player.vimeo.com/video/60897896?autoplay=1" width="800" height="450"></iframe>
        <br>
        <button type="button" id="close" onclick="document.getElementById('iframe').remove();">Remove iframe</button>
    </body>
</html>
```
Steps to reproduce:
 - Load HTML file
 - Wait till video starts playing
 - click on "Remove iframe" button

Backtrace:
```
ondrej@RYZEN3:~/apps/servo$ ./servo test.html 
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the -global-isel-abort option: may only occur zero or one times!
called `Result::unwrap()` on an `Err` value: () (thread <unnamed>, at src/libcore/result.rs:997)
[2019-02-24T13:39:55Z ERROR servo] called `Result::unwrap()` on an `Err` value: ()
called `Result::unwrap()` on an `Err` value: RecvError (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at src/libcore/result.rs:997)
called `Result::unwrap()` on an `Err` value: RecvError (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at src/libcore/result.rs:997)
Unexpected script channel panic in constellation: RecvError (thread Constellation, at src/libcore/result.rs:997)
[2019-02-24T13:39:55Z ERROR servo] called `Result::unwrap()` on an `Err` value: RecvError
[2019-02-24T13:39:55Z ERROR servo] called `Result::unwrap()` on an `Err` value: RecvError
[2019-02-24T13:39:55Z ERROR servo] Unexpected script channel panic in constellation: RecvError
called `Result::unwrap()` on an `Err` value: Io(Custom { kind: ConnectionReset, error: StringError("All senders for this socket closed") }) (thread StorageManager, at src/libcore/result.rs:997)
[2019-02-24T13:39:55Z ERROR servo] called `Result::unwrap()` on an `Err` value: Io(Custom { kind: ConnectionReset, error: StringError("All senders for this socket closed") })
called `Result::unwrap()` on an `Err` value: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) (thread <unnamed>, at src/libcore/result.rs:997)
[2019-02-24T13:39:55Z ERROR servo] called `Result::unwrap()` on an `Err` value: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })
fatal runtime error: failed to initiate panic, error 5
Redirecting call to abort() to mozalloc_abort

Stack trace
stack backtrace:
   0:     0x55900ee741cd - backtrace::backtrace::trace::h764507ebeb31a659
   1:     0x55900ee73022 - backtrace::capture::Backtrace::new::h861a5879c2a14db9
   2:     0x55900cbbe9e7 - servo::install_crash_handler::handler::h5c1ab76b9163f044
   3:     0x55900f20d78d - WasmFaultHandler
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/js/src/wasm/WasmSignalHandlers.cpp:1494
   4:     0x7f04f43a0dcf - <unknown>
   5:     0x55900f355d4e - _Z14mozalloc_abortPKc
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/memory/mozalloc/mozalloc_abort.cpp:33
   6:     0x55900f355d1f - abort
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.6/mozjs/memory/mozalloc/mozalloc_abort.cpp:80
   7:     0x55900fbbf3b6 - std::sys::unix::abort_internal::h47b1aab785740ad4
   8:     0x55900fbb3d04 - abort
                        at src/libstd/sys_common/util.rs:19
   9:     0x55900fbb504d - rust_panic
                        at src/libstd/panicking.rs:529
  10:     0x55900fbb4f15 - rust_panic_with_hook
                        at src/libstd/panicking.rs:498
  11:     0x55900fbb4961 - continue_panic_fmt
                        at src/libstd/panicking.rs:385
  12:     0x55900fbb4845 - rust_begin_unwind
  13:     0x55900fbd419c - panic_fmt
                        at src/libcore/panicking.rs:85
  14:     0x55900dde2182 - core::result::unwrap_failed::h933bb530a367bdc7
  15:     0x55900ddb2cff - servo_media_gstreamer::player::PlayerEventObserverList::notify::h7cee81ea583271f7
  16:     0x55900dde35b0 - servo_media_gstreamer::player::GStreamerPlayer::setup::{{closure}}::hd2f465fdab422e0b
  17:     0x55900ddf5c6e - gstreamer_app::app_sink::trampoline_new_sample::h9eda8be931efd296
  18:     0x7f04f466a7a1 - <unknown>
  19:     0x7f04f4aa3b1d - <unknown>
  20:     0x7f04f4aa4bff - <unknown>
  21:     0x7f04f49a5c39 - <unknown>
  22:     0x7f04f49aded1 - gst_pad_push
  23:     0x7f04f4993cca - gst_proxy_pad_chain_default
  24:     0x7f04f49a5c39 - <unknown>
  25:     0x7f04f49aded1 - gst_pad_push
  26:     0x7f04f4aaedfc - <unknown>
  27:     0x7f04f49a5c39 - <unknown>
  28:     0x7f04f49aded1 - gst_pad_push
  29:     0x7f04f4aaedfc - <unknown>
  30:     0x7f04f49a5c39 - <unknown>
  31:     0x7f04f49aded1 - gst_pad_push
  32:     0x7f04f4aaedfc - <unknown>
  33:     0x7f04f49a5c39 - <unknown>
  34:     0x7f04f49aded1 - gst_pad_push
  35:     0x7f04f4aaedfc - <unknown>
  36:     0x7f04f49a5c39 - <unknown>
  37:     0x7f04f49aded1 - gst_pad_push
  38:     0x7f04f4993cca - gst_proxy_pad_chain_default
  39:     0x7f04f49a5c39 - <unknown>
  40:     0x7f04f49aded1 - gst_pad_push
  41:     0x7f04a81ccb06 - <unknown>
  42:     0x7f04f49daf40 - <unknown>
  43:     0x7f04f4834ad2 - <unknown>
  44:     0x7f04f4834134 - <unknown>
  45:     0x7f04f4396163 - start_thread
  46:     0x7f04f3b34dee - __clone
  47:                0x0 - <unknown>
ondrej@RYZEN3:~/apps/servo$ 
```

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22931
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22944)

### CODE REVIEW

**Comment by ferjm** [comment]
@bors-servo retry

- https://github.com/servo/saltfs/pull/944

**Comment by ferjm** [comment]
@bors-servo retry

- I deployed https://github.com/servo/saltfs/pull/944/commits/b0cb5e9fe69d76db48621754099fda7051cf79c2

**Comment by ferjm** [comment]
Had to restart buildbot-master

@bors-servo retry

**Comment by ferjm** [comment]
@bors-servo retry

- highstated servo-master1 as well

**Comment by jdm** [comment]
Yay, we need to update the gstreamer installed on windows I guess:
```
          libgstreamer_gl-a547d0f11911795b.rlib(gstreamer_gl-a547d0f11911795b.gstreamer_gl.aqwxiywq-cgu.14.rcgu.o) : error LNK2019: unresolved external symbol gst_gl_display_egl_new_with_egl_display referenced in function _ZN12gstreamer_gl14gl_display_egl66_$LT$impl$u20$gstreamer_gl..auto..gl_display_egl..GLDisplayEGL$GT$20new_with_egl_display17h36b04c849a6462abE
          libgstreamer_gl-a547d0f11911795b.rlib(gstreamer_gl-a547d0f11911795b.gstreamer_gl.aqwxiywq-cgu.14.rcgu.o) : error LNK2019: unresolved external symbol gst_gl_display_egl_get_from_native referenced in function _ZN12gstreamer_gl14gl_display_egl66_$LT$impl$u20$gstreamer_gl..auto..gl_display_egl..GLDisplayEGL$GT$15get_from_native17hac030f78854aa964E
          libgstreamer_gl-a547d0f11911795b.rlib(gstreamer_gl-a547d0f11911795b.gstreamer_gl.aqwxiywq-cgu.14.rcgu.o) : error LNK2019: unresolved external symbol gst_gl_display_egl_new referenced in function _ZN12gstreamer_gl4auto14gl_display_egl12GLDisplayEGL3new17h1e9a06f88c028722E
          libgstreamer_gl-a547d0f11911795b.rlib(gstreamer_gl-a547d0f11911795b.gstreamer_gl.aqwxiywq-cgu.14.rcgu.o) : error LNK2019: unresolved external symbol gst_gl_display_egl_get_type referenced in function _ZN92_$LT$gstreamer_gl..auto..gl_display_egl..GLDisplayEGL$u20$as$u20$glib..types..StaticType$GT$11static_type17h21682e6c7f1ac7ddE
          C:\Users\task_1551289890\repo\target\debug\deps\servo-02b662513f2499a7.exe : fatal error LNK1120: 4 unresolved externals
```

**Comment by ceyusa** [comment]
Mmmh... I guess I would need a Windows machine to check it out, since EGL symbols are only exposed if target os is linux:

https://github.com/servo/media/blob/master/backends/gstreamer/Cargo.toml#L48

**Comment by jdm** [comment]
Update: I have successfully reproduced the same failure on our Windows CI machine over RDP.

**Comment by jdm** [comment]
I believe the problem is that https://gitlab.freedesktop.org/gstreamer/gstreamer-rs-sys/blob/e274b5495bb1698cd9fe48de40ab5f9f2b0e1faa/gstreamer-gl-sys/Cargo.toml#L26-28 does not have a `default = []` entry.

**Comment by jdm** [comment]
Ok, it is definitely more subtle than that. I have reproduced this same issue in a minimal testcase, and Cargo appears to be merging the features for my test crate despite these lines:
```
[target.'cfg(target = "linux")'.dependencies]
b = { path = "../b", features = ["egl"] }

[target.'cfg(not(target = "linux"))'.dependencies]
b = { path = "../b" }
```
Cargo happily resolves a call to b::do_egl() that is gated on `#[cfg(feature = "egl")]` inside the `b` crate, even when I build on macOS.

**Comment by jdm** [comment]
Oops, this is an unsupported feature in Cargo right now: https://github.com/rust-lang/cargo/issues/1197

**Comment by jdm** [comment]
@ferjm It looks like you have encountered this problem in the past, so I'm going to let you deal with it from here.

**Comment by ferjm** [comment]
```
ferjm> slomo: hey! I am trying to understand the reason of these link errors https://ci.appveyor.com/project/servo/servo/builds/22687001 I see that this functions are available since 1.12 and that Windows has a 1.14.1. Is it because these methods are not exposed in Windows?
12:12:55 <slomo> ferjm: yes, windows has no EGL
12:12:56 <ferjm> it seems that all the gl stuff is part of gst-plugins-base, so I assume that we are not missing a plugin
12:13:06 <slomo> ferjm: the GL stuff that vjaquez wrote only works on linux right now
12:14:42 <ferjm> ok. Yeah, and unfortunately, we are using an unsupported cargo feature to control that atm https://github.com/servo/servo/pull/22944#issuecomment-468827420
12:15:30 <slomo> shouldn't be too difficult to add support for windows, macos, etc
12:15:55 just needs someone on those platforms to add the missing pieces for their GL APIs
12:16:28 it will basically work the same as with EGL, just using WGL or CGL instead
12:17:56 <ferjm> we would still be requiring to set crate features based on the platform, right?
12:18:14 <slomo> yes
12:20:25 <ferjm> ok
12:20:57 given that cargo is missing the ability to set features based on the target https://github.com/rust-lang/cargo/issues/1197
12:21:10 could we split gstreamer-rs-gl in different crates?
12:21:39 <slomo> i'm glad you ask, i was proposing to do the same thing with the C library for the same reason
12:21:48 it's bad to have different APIs on different platforms
12:22:26 i wouldn't want to split the bindings in different crates just for working around cargo though, but if that split is done consistently also with the C library then that's fine
12:22:55 maybe start a discussion for that https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/issues/new
12:23:41 otherwise, it would seem better to fix cargo instead
12:24:20 have to leave for a while now
12:27:21 <ferjm> ok. Given that this currently blocks updating servo-media on servo, I think I'll start with the faster workaround (at least for someone with no knowledge of cargo and/or gst-gl like me), which is wrapping all the gl stuff in servo-media an intermediate crate. ttyl
```

**Comment by ferjm** [comment]
https://github.com/servo/media/pull/219 should fix the gstreamer related build errors on Windows. However, updating servo-media is still blocked as there is a new crash using the current master:

```
❯ ./mach run -d ../web-api-tests/video/index.html
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }"
stack backtrace:
   0:        0x108c507b4 - __ZN9backtrace9backtrace5trace17h9f3458ac04360c1aE
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:        0x108c4b15c - __ZN9backtrace7capture9Backtrace14new_unresolved17h21921a7295046aa9E
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:        0x108c4b0be - __ZN9backtrace7capture9Backtrace3new17h18226acc03ed089aE
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:        0x102a530a1 - __ZN5servo21install_crash_handler7handler17h67b3575ac2481d96E
                        at /Users/ferjm/dev/mozilla/servo/ports/servo/non_android_main.rs:54
   4:     0x7fff5daf2b3c - __sigtramp
   5:        0x105fa8073 - __ZN41_$LT$std..sync..mutex..Mutex$LT$T$GT$$GT$4lock17hf232e10817045172E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/sync/mutex.rs:220
   6:        0x105fa8a07 - __ZN11servo_media10ServoMedia3get17h4340161b0ee8a9d2E
                        at /Users/ferjm/.cargo/git/checkouts/media-c23a3cd5aa97076a/9d9f557/servo-media/src/lib.rs:44
   7:        0x10443d0cb - __ZN6script3dom16htmlmediaelement16HTMLMediaElement13new_inherited17h9bc978a093c1a35cE
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/htmlmediaelement.rs:270
   8:        0x104dde9f2 - __ZN6script3dom16htmlvideoelement16HTMLVideoElement13new_inherited17hbe544b74552d985eE
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/htmlvideoelement.rs:67
   9:        0x104ddeb8e - __ZN6script3dom16htmlvideoelement16HTMLVideoElement3new17h25793a96015d2922E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/htmlvideoelement.rs:83
  10:        0x105875592 - __ZN6script3dom6create26create_native_html_element17h1967e731f594df07E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/create.rs:364
  11:        0x10586ecdc - __ZN6script3dom6create19create_html_element17h62d6bc7e19f97414E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/create.rs:193
  12:        0x105875a98 - __ZN6script3dom6create14create_element17h5b31384904b33d79E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/create.rs:381
  13:        0x105034c0c - __ZN6script3dom7element7Element6create17hcb830b1aea3cbadeE
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/element.rs:258
  14:        0x103715846 - __ZN6script3dom11servoparser24create_element_for_token17ha0a665bd39cf1bc4E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:1171
  15:        0x103713ad1 - __ZN97_$LT$script..dom..servoparser..Sink$u20$as$u20$markup5ever..interface..tree_builder..TreeSink$GT$14create_element17h06509bd0db6daa34E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:951
  16:        0x1048edcfe - __ZN11markup5ever9interface12tree_builder14create_element17h10874824dcaa360eE
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/markup5ever-0.7.5/interface/tree_builder.rs:125
  17:        0x10543da0f - __ZN71_$LT$html5ever..tree_builder..TreeBuilder$LT$Handle$C$$u20$Sink$GT$$GT$14insert_element17hced86062f1712de4E
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tree_builder/mod.rs:1177
  18:        0x105448335 - __ZN71_$LT$html5ever..tree_builder..TreeBuilder$LT$Handle$C$$u20$Sink$GT$$GT$18insert_element_for17h766918ca347e60f8E
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tree_builder/mod.rs:1212
  19:        0x10547d520 - __ZN71_$LT$html5ever..tree_builder..TreeBuilder$LT$Handle$C$$u20$Sink$GT$$GT$4step17hdbe86ca366b895c2E
                        at /Users/ferjm/dev/mozilla/servo/target/debug/build/html5ever-2ed85ea03e77c713/out/rules.rs:768
  20:        0x105453178 - __ZN71_$LT$html5ever..tree_builder..TreeBuilder$LT$Handle$C$$u20$Sink$GT$$GT$21process_to_completion17h11b6362ded026e03E
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tree_builder/mod.rs:314
  21:        0x105433af7 - __ZN125_$LT$html5ever..tree_builder..TreeBuilder$LT$Handle$C$$u20$Sink$GT$$u20$as$u20$html5ever..tokenizer..interface..TokenSink$GT$13process_token17h1e99b7b9be8f50a7E
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tree_builder/mod.rs:476
  22:        0x103bc531f - __ZN52_$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$13process_token17h346230277ade1233E
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tokenizer/mod.rs:232
  23:        0x103bc738e - __ZN52_$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$16emit_current_tag17h35168b7263ff9a82E
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tokenizer/mod.rs:425
  24:        0x103bd817f - __ZN52_$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$4step17h5b64bbe2e3ae2cecE
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tokenizer/mod.rs:627
  25:        0x103bcb054 - __ZN52_$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$3run17h09c067c57bdb9424E
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tokenizer/mod.rs:361
  26:        0x103bcb943 - __ZN52_$LT$html5ever..tokenizer..Tokenizer$LT$Sink$GT$$GT$4feed17had18fdb8b2cff652E
                        at /Users/ferjm/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tokenizer/mod.rs:219
  27:        0x105c1193a - __ZN6script3dom11servoparser4html9Tokenizer4feed17h15a6c5e8050e06edE
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/html.rs:80
  28:        0x10371009c - __ZN6script3dom11servoparser9Tokenizer4feed17h6749aeca068f6d26E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:603
  29:        0x10469f4be - __ZN6script3dom11servoparser11ServoParser13do_parse_sync28_$u7b$$u7b$closure$u7d$$u7d$17h2102619581fbe044E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:481
  30:        0x10469f624 - __ZN6script3dom11servoparser11ServoParser8tokenize17h6dbc61932392e40fE
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:519
  31:        0x10370f844 - __ZN6script3dom11servoparser11ServoParser13do_parse_sync17ha174ff0cf7ae1148E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:481
  32:        0x10469f457 - __ZN6script3dom11servoparser11ServoParser10parse_sync28_$u7b$$u7b$closure$u7d$$u7d$17h28ae30bfb6c7c721E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:463
  33:        0x104aa12a6 - __ZN14profile_traits4time7profile17hf0d429894aa7b734E
                        at /Users/ferjm/dev/mozilla/servo/components/profile_traits/time.rs:142
  34:        0x10370f4d2 - __ZN6script3dom11servoparser11ServoParser10parse_sync17hde151c4a1c1cef61E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:455
  35:        0x10370fbb5 - __ZN6script3dom11servoparser11ServoParser17parse_bytes_chunk17h24e5b28ec97639fcE
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:506
  36:        0x10371272b - __ZN93_$LT$script..dom..servoparser..ParserContext$u20$as$u20$net_traits..FetchResponseListener$GT$22process_response_chunk17h264450cab17a7876E
                        at /Users/ferjm/dev/mozilla/servo/components/script/dom/servoparser/mod.rs:790
  37:        0x10346f1dc - __ZN6script13script_thread12ScriptThread18handle_fetch_chunk17hc4b14d6fef0550c3E
                        at /Users/ferjm/dev/mozilla/servo/components/script/script_thread.rs:3372
  38:        0x103456611 - __ZN6script13script_thread12ScriptThread29handle_msg_from_constellation17h3780db7973ff5244E
                        at /Users/ferjm/dev/mozilla/servo/components/script/script_thread.rs:1613
  39:        0x104a6a5f3 - __ZN6script13script_thread12ScriptThread11handle_msgs28_$u7b$$u7b$closure$u7d$$u7d$17ha0e9a13f7cadea5cE
                        at /Users/ferjm/dev/mozilla/servo/components/script/script_thread.rs:1345
  40:        0x104a6dc2c - __ZN6script13script_thread12ScriptThread13profile_event17hfb495a310c7b0458E
                        at /Users/ferjm/dev/mozilla/servo/components/script/script_thread.rs:1581
  41:        0x10345409c - __ZN6script13script_thread12ScriptThread11handle_msgs17hd4b3ae07c6dd55afE
                        at /Users/ferjm/dev/mozilla/servo/components/script/script_thread.rs:1339
  42:        0x103451a0c - __ZN6script13script_thread12ScriptThread5start17h0113e65d38d2ebcfE
                        at /Users/ferjm/dev/mozilla/servo/components/script/script_thread.rs:1176
  43:        0x104a676f4 - __ZN90_$LT$script..script_thread..ScriptThread$u20$as$u20$script_traits..ScriptThreadFactory$GT$6create28_$u7b$$u7b$closure$u7d$$u7d$28_$u7b$$u7b$closure$u7d$$u7d$17h75aadeb6c8fccedcE
                        at /Users/ferjm/dev/mozilla/servo/components/script/script_thread.rs:731
  44:        0x105c2457a - __ZN14profile_traits3mem12ProfilerChan25run_with_memory_reporting17hab359eea2be4829dE
                        at /Users/ferjm/dev/mozilla/servo/components/profile_traits/mem.rs:88
  45:        0x104a67cd8 - __ZN90_$LT$script..script_thread..ScriptThread$u20$as$u20$script_traits..ScriptThreadFactory$GT$6create28_$u7b$$u7b$closure$u7d$$u7d$17ha043e89c483d7af5E
                        at /Users/ferjm/dev/mozilla/servo/components/script/script_thread.rs:729
  46:        0x1059d1692 - __ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17he77cea1d396489a8E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/sys_common/backtrace.rs:136
  47:        0x104db0832 - __ZN3std6thread7Builder15spawn_unchecked28_$u7b$$u7b$closure$u7d$$u7d$28_$u7b$$u7b$closure$u7d$$u7d$17h0410f191cb9c3628E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/thread/mod.rs:469
  48:        0x1033ce1e2 - __ZN101_$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$9call_once17h6e53cd73a3248613E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panic.rs:309
  49:        0x104fcd382 - __ZN3std9panicking3try7do_call17hedf1a58647843e46E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:297
  50:        0x10a10ec5e - ___rust_maybe_catch_panic
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libpanic_unwind/lib.rs:87
  51:        0x104e76f44 - __ZN3std9panicking3try17h62e23f8a07c0829fE
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panicking.rs:276
  52:        0x10341a8c2 - __ZN3std5panic12catch_unwind17h641e70aa34f58971E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/panic.rs:388
  53:        0x104db00db - __ZN3std6thread7Builder15spawn_unchecked28_$u7b$$u7b$closure$u7d$$u7d$17hcb08b18a63479bc1E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/thread/mod.rs:468
  54:        0x104db1823 - __ZN50_$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$8call_box17ha3c911f6599b91d6E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/liballoc/boxed.rs:749
  55:        0x10a10e08b - __ZN3std3sys4unix6thread6Thread3new12thread_start17hb65474f74178fcb3E
                        at /rustc/0ea22717a1e01fa535534b85a5347a7e49fc79de/src/libstd/sys_common/thread.rs:14
  56:     0x7fff5dafb338 - __pthread_body
  57:     0x7fff5dafe2a6 - __pthread_start
Servo exited with return value 11
```

**Comment by ferjm** [comment]
The crash is likely because we now require a call to `ServoMedia::init` before `ServoMedia::get`.

**Comment by jdm** [comment]
R=me, but Travis is unhappy.

**Comment by ferjm** [comment]
Ugh, Travis is happy now, but Windows builds continue failing.

**Comment by jdm** [comment]
Mmmm. I suspect we end up running into the same feature unification problem from this block:
```
https://github.com/servo/media/blob/9d9f557fc7bfa78075b83edd822557548c9d4344/backends/gstreamer/Cargo.toml#L51-L56
```

**Comment by ferjm** [comment]
That seems to be the case :_(

```
rustc --crate-name gstreamer_gl C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\gstreamer-gl-0.13.0\src\lib.rs --color never --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"egl\"" --cfg "feature=\"gstreamer-gl-sys\"" -C metadata=077b7760541d8b30 -C extra-filename=-077b7760541d8b30 --out-dir C:\projects\servo\target\debug\deps -L dependency=C:\projects\servo\target\debug\deps --extern bitflags=C:\projects\servo\target\debug\deps\libbitflags-98d4c4bf4f9203ea.rlib --extern byteorder=C:\projects\servo\target\debug\deps\libbyteorder-ac0189214359f309.rlib --extern glib=C:\projects\servo\target\debug\deps\libglib-bfa4e6e2557614e2.rlib --extern glib_sys=C:\projects\servo\target\debug\deps\libglib_sys-4a947a7b6c8f1302.rlib --extern gobject_sys=C:\projects\servo\target\debug\deps\libgobject_sys-648bf0a6f6a91f33.rlib --extern gstreamer=C:\projects\servo\target\debug\deps\libgstreamer-a2ab9bcb327be7c6.rlib --extern gstreamer_base=C:\projects\servo\target\debug\deps\libgstreamer_base-0991ad66723fffcc.rlib --extern gstreamer_base_sys=C:\projects\servo\target\debug\deps\libgstreamer_base_sys-04f1a31c40efb7b0.rlib --extern gstreamer_gl_sys=C:\projects\servo\target\debug\deps\libgstreamer_gl_sys-59c597262feac294.rlib --extern gstreamer_sys=C:\projects\servo\target\debug\deps\libgstreamer_sys-3be2c4a5a8d3acbe.rlib --extern gstreamer_video=C:\projects\servo\target\debug\deps\libgstreamer_video-13efe55689623e89.rlib --extern gstreamer_video_sys=C:\projects\servo\target\debug\deps\libgstreamer_video_sys-bab771ccf03d8d2a.rlib --extern lazy_static=C:\projects\servo\target\debug\deps\liblazy_static-b7b5d33c1b9c52b7.rlib --extern libc=C:\projects\servo\target\debug\deps\liblibc-eac93b1f7d3e1363.rlib --cap-lints allow -Dwarnings -W unused-extern-crates -L native=C:/gstreamer/1.0/x86_64/lib -L native=C:/gstreamer/1.0/x86_64/lib -L native=C:/gstreamer/1.0/x86_64/lib -L native=C:/gstreamer/1.0/x86_64/lib -L native=C:/gstreamer/1.0/x86_64/lib -L native=C:/gstreamer/1.0/x86_64/lib`
```

I cannot think of an alternative workaround for servo-media at the moment. We might need to split `gstreamer-gl` in different crates.

cc @sdroege @ceyusa

**Comment by jdm** [comment]
@ferjm maybe we could re-export everything we need from gstreamer-gl in media-gl-egl?

**Comment by ferjm** [comment]
@jdm I am not sure I am understand what you are suggesting. Wouldn't we still need to enable the 'egl' feature for gstreamer-gl based on the target, so we can re-export the egl related stuff?

**Comment by jdm** [comment]
That's true. I wonder if this would work:
* media-gl depends on gstreamer-gl without the egl feature, reexports all of gstreamer-gl
* media-gl-egl depends on gstreamer-gl with the egl feature, reexports all of gstreamer-gl

On linux we could depend on media-gl-egl, and on other platforms we could depend on media-gl.

**Comment by jdm** [comment]
Still there:
```
`rustc --crate-name gstreamer_gl C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\gstreamer-gl-0.13.0\src\lib.rs --color never --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"egl\"" ...
```

**Comment by ferjm** [comment]
I am [temporarily disabling GL functionality](https://github.com/servo/media/pull/223) in servo-media for now. I filed https://github.com/servo/media/issues/224 to track the work required for the new workaound.

**Comment by ferjm** [comment]
@bors-servo retry
- #13480

**Pull request merged**
