### PR TITLE
Update truetype

### PR DESCRIPTION
**Pull request by IvanUkhov**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

### CODE REVIEW

**Comment by IvanUkhov** [comment]
I don’t have access to a Windows machine and are not able to test. Would anybody be able to help?

**Comment by jdm** [comment]
I've asked for assistance in testing this change in https://servo.zulipchat.com/#narrow/stream/263398-general/topic/Testing.20a.20Windows.20change .

**Comment by IvanUkhov** [comment]
@jdm, thank you! Do you know what I should do regarding the last two items? There seem to be relevant tests here:

https://github.com/servo/servo/tree/master/components/gfx/tests

And they seem to be active for Windows.

**Comment by IvanUkhov** [comment]
I have been changing blindly, as I cannot run the tests myself. Mostly likely, `Cargo.lock` would have to be updated.

**Comment by jdm** [comment]
Out of curiosity, why did you make this change if you don't actually use Windows?

**Comment by IvanUkhov** [comment]
Well, I’m the one maintaining `truetype`, and it is unfortunate to see used like that, especially in a project that is of great importance for the Rust ecosystem. The crate had limitations when it was first introduced in Servo many years ago, and I recently was working on and improved that part. It is also a way for me to promote the corresponding family of pure-Rust, platform-independent crates for dealing with fonts. It made sense to update, in other words.

**Comment by IvanUkhov** [comment]
Failed because of `Cargo.lock`. Pushed an update to fix that.

**Comment by jdm** [comment]
Windows unit tests failed:
```
---- test_font_fallback stdout ----
thread 'test_font_fallback' panicked at 'assertion failed: `(left == right)`
  left: `"csstest-ascii"`,
 right: `"fallback"`: a fallback font should be used if there is no matching glyph in the group', components\gfx\tests\font_context.rs:216:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:65
   2: core::fmt::Arguments::new_v1
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\fmt\mod.rs:398
   3: core::panicking::assert_failed_inner
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:238
   4: core::panicking::assert_failed
   5: hashbrown::raw::RawTable<T,A>::insert
   6: core::ops::function::FnOnce::call_once
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_font_group_find_by_codepoint stdout ----
thread 'test_font_group_find_by_codepoint' panicked at 'assertion failed: `(left == right)`
  left: `"csstest-ascii"`,
 right: `"csstest-basic-regular"`', components\gfx\tests\font_context.rs:188:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:65
   2: core::fmt::Arguments::new_v1
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\fmt\mod.rs:398
   3: core::panicking::assert_failed_inner
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:244
   4: core::panicking::assert_failed
   5: hashbrown::raw::RawTable<T,A>::insert
   6: core::ops::function::FnOnce::call_once
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_font_template_is_cached stdout ----
thread 'test_font_template_is_cached' panicked at 'called `Option::unwrap()` on a `None` value', components\gfx\tests\font_context.rs:242:17
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:65
   2: core::panicking::panic
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:114
   3: hashbrown::raw::RawTable<T,A>::insert
   4: core::ops::function::FnOnce::call_once
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_font_fallback
    test_font_group_find_by_codepoint
    test_font_template_is_cached
```

**Comment by jdm** [comment]
```
---- test_font_fallback stdout ----
thread 'test_font_fallback' panicked at 'assertion failed: `(left == right)`
  left: `"csstest-ascii"`,
 right: `"fallback"`: a fallback font should be used if there is no matching glyph in the group', components\gfx\tests\font_context.rs:216:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:65
   2: core::fmt::Arguments::new_v1
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\fmt\mod.rs:398
   3: core::panicking::assert_failed_inner
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:238
   4: core::panicking::assert_failed
   5: hashbrown::raw::RawTable<T,A>::insert
   6: core::ops::function::FnOnce::call_once
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_font_group_find_by_codepoint stdout ----
thread 'test_font_group_find_by_codepoint' panicked at 'assertion failed: `(left == right)`
error: test failed, to rerun pass `-p gfx --test font_context`
  left: `"csstest-ascii"`,
 right: `"csstest-basic-regular"`', components\gfx\tests\font_context.rs:188:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:65
   2: core::fmt::Arguments::new_v1
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\fmt\mod.rs:398
   3: core::panicking::assert_failed_inner
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:244
   4: core::panicking::assert_failed
   5: hashbrown::raw::RawTable<T,A>::insert
   6: core::ops::function::FnOnce::call_once
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- test_font_template_is_cached stdout ----
thread 'test_font_template_is_cached' panicked at 'called `Option::unwrap()` on a `None` value', components\gfx\tests\font_context.rs:242:17
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:65
   2: core::panicking::panic
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\panicking.rs:114
   3: hashbrown::raw::RawTable<T,A>::insert
   4: core::ops::function::FnOnce::call_once
             at /rustc/c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b/library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_font_fallback
    test_font_group_find_by_codepoint
    test_font_template_is_cached
```

**Comment by IvanUkhov** [comment]
Thank you so much for the help! I now know how to proceed. I have created a reduced setup in my fork and reproduced the error:

https://github.com/IvanUkhov/servo/actions/workflows/main.yml

I will then debug there and update this PR as soon as I resolve it.

**Comment by IvanUkhov** [comment]
The problem seems to be in CSSTest. The naming table in `csstest-basic-regular`, which is one of the two fonts used in the tests, is rejected upon parsing as it does not follow the specification. The previous implementation was very primitive, without checking for anything, while the new one provides support for more encodings and does it properly.

I have opened an issue here:

https://github.com/web-platform-tests/wpt/issues/37713

**Comment by IvanUkhov** [comment]
@jdm, could you please approve to run the workflows?

**Comment by jdm** [comment]
Looking good! I think those failures are just tests that are intermittently passing.

**Comment by IvanUkhov** [comment]
Yes, they look unrelated, but please let me know if I should do something about it. Thank you!

**Pull request merged**
