### PR TITLE
Implement WebGL::GetShaderPrecisionFormat

### LINKED ISSUE #13985: Unexpected WebGL error: 0x506 (1286)
Unexpected WebGL error: 0x506 (1286)
### Servo Version:

Servo 0.0.1-b611e5c
### Backtrace:

```

WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: FIXME: </script> not fully implemented
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) } got script tick after closure.
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) } got layout tick after closure.
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) }>: stop_parsing not implemented, full speed ahead!
WARNING: <Constellation>: Removed forward history after pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) } closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) } closed.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) } closed.
WARNING: <WebGLThread>: Initial context creation failed, falling back to readback: CGLCreateContext
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) } got script tick after closure.
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) } got layout tick after closure.
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) } got script tick after closure.
WARNING: <Constellation>: Pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) } got layout tick after closure.
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }>: Mozbrowser event after iframe PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }/PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(2) } closed.
WARNING: <Constellation>: No frame associated with pipeline PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(9) }
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: WebGL error: InvalidEnum, previous error was None
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: WebGL error: InvalidEnum, previous error was Some(InvalidEnum)
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(8) }>: WebGL error: InvalidEnum, previous error was Some(InvalidEnum)
WARNING: <WebGLThread>: Panic hook called.
ERROR: Unexpected WebGL error: 0x506 (1286)

stack backtrace:
   0:        0x11097369e - backtrace::backtrace::trace::h6ac07ced1b846a59
   1:        0x11097398c - backtrace::capture::Backtrace::new::h1d3339ed08c7f861
   2:        0x10f859515 - constellation::constellation::log_entry::hc92ce9b47dde5c21
   3:        0x10f8583e2 - _<constellation..constellation..FromCompositorLogger as log..Log>::log::h27ef5afa70002f0a
   4:        0x1110a5861 - log::__log::hf7539da7e3bbacdb
   5:        0x10f7499e0 - servo::main::_{{closure}}::h70a6b1b48115735a
   6:        0x111104043 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   7:        0x111103f14 - std::panicking::begin_panic::hf6c488cee66e7f17
   8:        0x111103e32 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   9:        0x1109be17c - canvas::webgl_paint_thread::GLContextWrapper::apply_command::h814dfb89530c0033
  10:        0x1109a8819 - std::panicking::try::do_call::h91fafc08ee77b214
  11:        0x11110506a - __rust_maybe_catch_panic
  12:        0x1109afdf3 - _<F as alloc..boxed..FnBox<A>>::call_box::h455836191b9c8045
  13:        0x111102ef4 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  14:     0x7fff8dbc199c - _pthread_body
  15:     0x7fff8dbc1919 - _pthread_start
```

This report was generated by the browser.html issue reporter.

### PR DESCRIPTION
**Pull request by MortimerGoro**
Implement WebGL::GetShaderPrecisionFormat. See https://github.com/servo/gleam/pull/119 && https://github.com/servo/webrender/pull/1127

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13985 (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16544)

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/context/methods.html:
  │ FAIL [expected PASS] WebGL test #3: Property either does not exist or is not a function: getTexParameter
  │   → assert_true: Property either does not exist or is not a function: getTexParameter expected true got false
  │ FAIL [expected PASS] WebGL test #4: Property either does not exist or is not a function: getUniform
  │   → assert_true: Property either does not exist or is not a function: getUniform expected true got false
  │ FAIL [expected PASS] WebGL test #5: Property either does not exist or is not a function: getVertexAttribOffset
  │   → assert_true: Property either does not exist or is not a function: getVertexAttribOffset expected true got false
  │ FAIL [expected PASS] WebGL test #6: Property either does not exist or is not a function: isContextLost
  │   → assert_true: Property either does not exist or is not a function: isContextLost expected true got false
  │ 
  │ reportTestResultsToHarness/<@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:88:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ reportTestResultsToHarness@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:87:7
  │ testFailed@http://web-platform.test:8000/webgl/conformance-1.0.3/resources/js-test-pre.js:159:5
  │ assertFunction@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/context/methods.html:193:7
  └ @http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/context/methods.html:211:11

  ▶ OK [expected ERROR] /webgl/conformance-1.0.3/conformance/glsl/bugs/constant-precision-qualifier.html

  ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/glsl/bugs/constant-precision-qualifier.html:
  └ PASS [expected NOTRUN] Overall test

  ▶ OK [expected ERROR] /webgl/conformance-1.0.3/conformance/glsl/misc/shader-precision-format-obeyed.html

  ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/glsl/misc/shader-precision-format-obeyed.html:
  └ PASS [expected NOTRUN] Overall test
```

**Comment by MortimerGoro** [comment]
It should be fixed now. I also added the code to fix shader compilation with highp qualifiers into this PR because it's required by one of the getShaderPrecisionFormat conformance tests

**Pull request merged**
