### PR TITLE
[Do not merge] Rustc bisect

### PR DESCRIPTION
**Pull request by SimonSapin**
I could not reproduce locally the assertions failures in #18420, so I’ll try bisecting compiler versions on try CI.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18445)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
  ▶ FAIL [expected PASS] /_mozilla/css/css-position-3/position-sticky-table-th-right.html
  └   → /_mozilla/css/css-position-3/position-sticky-table-th-right.html e9b9d42d83d50f68d193d258f7b8e977d06a08b7
/_mozilla/css/css-position-3/position-sticky-table-th-right-ref.html 8a37208e44c1426c46cd704a1051120fa696710f
Testing e9b9d42d83d50f68d193d258f7b8e977d06a08b7 == 8a37208e44c1426c46cd704a1051120fa696710f
```

Looks like `assertion failed: distance_to_stack_bottom <= max_allowable_distance` did *not* occur with Nightly 2017-09-04.

Trying 2017-09-06 now:

@bors-servo try

**Comment by SimonSapin** [comment]
2017-09-06 and 2017-09-07 are "good" (did not produce that assertion failure in one try run each) too. Trying 2017-09-08 now, same as in #18420.

@bors-servo try

**Comment by SimonSapin** [comment]
`assertion failed: distance_to_stack_bottom <= max_allowable_distance` spotted on 2017-09-08. Trying 2017-09-07 again in case the previous run was a coincidence.

@bors-servo try

**Comment by SimonSapin** [comment]
Alright, I think it’s fairly safe to say that something in https://github.com/rust-lang/rust/compare/368122087...d93036a04 is causing this assertions to be triggered.

**Comment by SimonSapin** [comment]
Now with some `mach` hacking to use per-PR builds from Rust CI instead of Nightly.

@bors-servo try

**Comment by SimonSapin** [comment]
Tidy is unhappy, but other jobs look green enough to call https://github.com/rust-lang/rust/commit/05e3c96d36b5281e969b5e79b92d671c7872bf83 "good".

Trying https://github.com/rust-lang/rust/commit/d7d75eff30ff03f607ff0656a50f4be768cfdbc9 now:

@bors-servo try

**Comment by jdm** [comment]
```
ERROR:servo: assertion failed: distance_to_stack_bottom <= max_allowable_distance
```

**Comment by SimonSapin** [comment]
Thanks Josh. Trying https://github.com/rust-lang/rust/commit/a6a9d4c5fd214cb8110482dee2017607e23ccc7b, last run to pin this to a single Rust PR.

@bors-servo try

**Comment by SimonSapin** [comment]
Oops, it works better if I don’t forget `git push`.

@bors-servo try

**Comment by SimonSapin** [comment]
Looks like homu didn’t get the memo, but buildbot jobs are all green. This leaves https://github.com/rust-lang/rust/pull/43931 as responsible (though possibly indirectly).

**Pull request closed without merging**
