### PR TITLE
Removed an unused function and minor cleanup

### LINKED ISSUE #11679: tidy warns about problems even in quoted strings inside attributes
In particular, the quoted string `"__TEXT,__info_plist"` causes tidy to fail complaining about the lack of a space before the comma. This impacts #11646.

### PR DESCRIPTION
**Pull request by ghost**
fixes #11679

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11755)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11755#-:-KKO7d6PcyXui3nRz6LV:1236647940)*

**Comment by Wafflespeanut** [comment]
@nox Thanks! :)

**Comment by jdm** [comment]
There was no test for the fix for #11679...

**Comment by Wafflespeanut** [comment]
I thought it was a minor bug. Sorry, will add a test now :)

**Pull request merged**
