### PR TITLE
Use Utf8LossyDecoder instead of IncompleteUtf8

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22362)

### CODE REVIEW

**Comment by jdm** [comment]
What is the effect of this change?

**Comment by nox** [comment]
The API of `Utf8LossyDecoder` is the same as `LossyDecoder`, which is what I'll use for supporting different encodings once `html5ever` is made to use `encoding_rs`.

**Pull request merged**
