### PR TITLE
Ensure readonly files can be removed on Windows.

### PR DESCRIPTION
**Pull request by jdm**
This is based off of https://bugs.python.org/issue19643. At worst, it makes our deletion function more robust and doesn't help with the ongoing windows CI problems.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20244)

### CODE REVIEW

**Comment by jdm** [comment]
Hey, it actually made clear-cargo-cache work properly on Windows!

**Comment by SimonSapin** [comment]
r=me with the "missing import" commit squashed into the commit that uses that import.

**Pull request merged**
