### PR TITLE
Update to cssparser 0.19, count line numbers during tokenization

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/servo/rust-cssparser/pull/177

Also simplify the `ParseErrorReporter` trait a bit.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18025)

### CODE REVIEW

**Review by emilio — APPROVED** [review]
r=me

**Comment by emilio** [comment]
Oh, or r=jdm, I guess :)

**Comment by jdm** [comment]
```
error[E0412]: cannot find type `UrlExtraData` in this scope
  --> /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/style/media_queries.rs:25:28
   |
25 |                     _url: &UrlExtraData,
   |                            ^^^^^^^^^^^^ not found in this scope
   |
help: possible candidate is found in another module, you can import it into scope
   |
29 | use style::stylesheets::UrlExtraData;
   |

error[E0412]: cannot find type `SourceLocation` in this scope
  --> /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/style/media_queries.rs:26:32
   |
26 |                     _location: SourceLocation,
   |                                ^^^^^^^^^^^^^^ did you mean `SourcePosition`?
   |
help: possible candidate is found in another module, you can import it into scope
   |
29 | use cssparser::SourceLocation;
   |

error[E0412]: cannot find type `UrlExtraData` in this scope
  --> /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/style/rule_tree/bench.rs:22:27
   |
22 |                     url: &UrlExtraData,
   |                           ^^^^^^^^^^^^ not found in this scope
   |
help: possible candidate is found in another module, you can import it into scope
   |
5  | use style::stylesheets::UrlExtraData;
   |

error[E0412]: cannot find type `SourceLocation` in this scope
  --> /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/style/rule_tree/bench.rs:23:31
   |
23 |                     location: SourceLocation,
   |                               ^^^^^^^^^^^^^^ did you mean `SourcePosition`?
   |
help: possible candidate is found in another module, you can import it into scope
   |
5  | use cssparser::SourceLocation;
   |

error[E0412]: cannot find type `UrlExtraData` in this scope
   --> /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/style/stylesheets.rs:274:27
    |
274 |                     url: &UrlExtraData,
    |                           ^^^^^^^^^^^^ not found in this scope
    |
help: possible candidate is found in another module, you can import it into scope
    |
37  | use style::stylesheets::UrlExtraData;
```

**Comment by SimonSapin** [comment]
Fixed.

@bors-servo r=jdm

**Pull request merged**
