### PR TITLE
Emit markers for all events, not just UI events.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7628)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/eventdispatcher.rs, line 57 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7628#-JzBhqWu6VWBSNKZcyIO)** ([raw file](https://github.com/servo/servo/blob/f8891937e13a6fe6085cb02a37c45a6a8c80b2d0/components/script/dom/eventdispatcher.rs#L57)):</sup>
Let's invert this and return early.

---

<sup>**[components/script/dom/eventdispatcher.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7628#-JzBhgsDRuZuDcU0snwU)** ([raw file](https://github.com/servo/servo/blob/bc8e7239a5ee1922b05bbe9fd6a17151087b3cda/components/script/dom/eventdispatcher.rs#L90)):</sup>
Does this need to be public?

---

<sup>**[components/script/dom/eventdispatcher.rs, line 101 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7628#-JzBhkAEuuMzM80X1P1t)** ([raw file](https://github.com/servo/servo/blob/bc8e7239a5ee1922b05bbe9fd6a17151087b3cda/components/script/dom/eventdispatcher.rs#L101)):</sup>
nit: while you're here, can you remove this TODO?

---

<sup>**[components/script/dom/window.rs, line 1221 \[r7\]](https://reviewable.io:443/reviews/servo/servo/7628#-JzBiMDPXtsDb2S7B_nX)** ([raw file](https://github.com/servo/servo/blob/97710f0739410e7b464591f482c2dc117e528bbe/components/script/dom/window.rs#L1221)):</sup>
nit: let's restore this newline

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7628)

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/eventdispatcher.rs, line 123 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7628#-JzBhgsDRuZuDcU0snwU)** ([raw file](https://github.com/servo/servo/blob/bc8e7239a5ee1922b05bbe9fd6a17151087b3cda/components/script/dom/eventdispatcher.rs#L123)):</sup>
Yes, it's called from eventtarget.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7628)

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for doing this work!

---

Reviewed 2 of 2 files at r8, 1 of 1 files at r9.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7628)

**Comment by jdm** [comment]
```
/dom/events/Event-propagation.html
----------------------------------
FAIL After stopPropagation()
/dom/events/Event-initEvent.html
--------------------------------
FAIL Calling initEvent must unset the stop propagation flag.
```
These look like actual new failures introduced by these changes.

**Comment by jdm** [comment]
Looks good to me, but I suspect an r+ will just bounce off #7625 right now.
-S-awaiting-review 

---

Reviewed 2 of 2 files at r10.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7628)

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 2 of 2 files at r11.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7628)

**Pull request merged**
