### PR TITLE
WIP: unrevert border snapping code to investigate test failures

### PR DESCRIPTION
**Pull request by Gankra**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17297)

### CODE REVIEW

**Comment by Gankro** [comment]
@bors-servo try

(checking if this is deterministic or not)

**Comment by Gankro** [comment]
Hrm, race conditions...

**Comment by Gankro** [comment]
Notes about new expect-fails:

* 45-degree transformation tests: snapping adds another row of pixels. a 45 degree 3D rotation doesn't need to be that precise.

* text underline test: spec'ing unspecified behaviour (position/size of underlines). Snapping adds another row of pixels. Also subpixel text AA blurs around the edges in gecko.

In both of these cases, we seem to agree with gecko, which seems more desirable than meeting the seemingly arbitrary expectations of these tests.

**Comment by Gankro** [comment]
All tests pass, but the initial revert was motivated by non-deterministic failures. These 3 runs all had the same results afaict. Gonna do a few more tries just to see.

**Comment by Gankro** [comment]
Unrelated failure. Or: God help us all if border pixel snapping affected `/html/semantics/embedded-content/media-elements/networkState_during_progress.html`

**Comment by Gankro** [comment]
Ok that's 5 deterministic in a row!

**Comment by glennw** [comment]
Closing in favor of https://github.com/servo/servo/pull/17389

**Pull request closed without merging**
