### PR TITLE
Enable flexbox for flexbox tests

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9113)

### CODE REVIEW

**Comment by nox** [comment]
```
Tests with unexpected results:
  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/css-flexbox-column-reverse.htm
  └   → /css-flexbox-1_dev/html/css-flexbox-column-reverse.htm 39ec664cb74dd2ce28ee2195ca38cd663d4a0317
/css-flexbox-1_dev/html/reference/css-flexbox-column-ref.htm 4c1c7da7e7b20df6ec20c20364127cf1cdf82ca6
Testing 39ec664cb74dd2ce28ee2195ca38cd663d4a0317 == 4c1c7da7e7b20df6ec20c20364127cf1cdf82ca6

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flex-flexitem-percentage-prescation.htm
  └   → /css-flexbox-1_dev/html/flex-flexitem-percentage-prescation.htm 549dc2995e7de786feb6065fc8fc76b53746d920
/css-flexbox-1_dev/html/reference/flex-flexitem-percentage-prescation-ref.htm 516cbcf7b447cf7d5a568a4f8b57f030555e6525
Testing 549dc2995e7de786feb6065fc8fc76b53746d920 == 516cbcf7b447cf7d5a568a4f8b57f030555e6525
```

@jdm :(

**Comment by zentner-kyle** [comment]
Yeah, flexbox is still really far from working correctly. I'd expect at least 95% of the tests to fail.

**Comment by jdm** [comment]
@zentner-kyle Right, but currently every test fails because we don't enable the flexbox-related support in the engine. When we do, a certain number of tests start passing.

**Comment by nox** [comment]
@jdm Do you think there are other lurking intermittent failures, or should I only mark these two as such?

**Comment by jdm** [comment]
No idea, unfortunately. I'd just go ahead on the assumption that these are the only ones.

**Comment by jdm** [comment]
Dealing with this in #9766.

**Pull request closed without merging**
