### PR TITLE
Make transform property animatable for stylo

### PR DESCRIPTION
**Pull request by hiikezoe**
This is the servo side fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1332657

Reviewed by @heycam and @Manishearth. 
Thanks!

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because this is for stylo.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15363)

### CODE REVIEW

**Comment by heycam** [comment]
@hiikezoe can you adjust the commit messages here, so that they don't seem too Gecko-specific?  I think "Implement clone_transform." and "Make transform property animatable." would be sufficient (i.e., without the bug/part number and r= bits).

**Comment by Manishearth** [comment]
You need to commit the generated bindings changes, too.

**Comment by hiikezoe** [comment]
Oops,  I did totally forget about it since auto bindgen struff works perfectly these days.

**Pull request merged**
