### PR TITLE
Extract user_agent from global opts and allow embedder to provide user agent string

### LINKED ISSUE #25646: Allow embedders to provide user agent string
It should be up to the embedder to decide what user agent to report in network requests, rather than deep in the engine in https://github.com/servo/servo/blob/8e0d037ee82da747fa9c13234d5c3677f930e690/components/config/opts.rs#L480 (and #25372 would have exacerbated this). We should add a method to the EmbedderMethods trait that returns the default user agent string, so that we can pass that to [the new network thread](https://github.com/servo/servo/blob/8e0d037ee82da747fa9c13234d5c3677f930e690/components/servo/lib.rs#L861) when we're [creating an instance of Servo](https://github.com/servo/servo/blob/8e0d037ee82da747fa9c13234d5c3677f930e690/components/servo/lib.rs#L324).

### PR DESCRIPTION
**Pull request by utsavoza**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #25646
- [x] These changes do not require tests because these are refactoring changes and I'm assuming that existing tests cover these changes.

### CODE REVIEW

**Comment by jdm** [comment]
r? @paulrouget 
Continuation of #25672.

**Comment by paulrouget** [comment]
This is great!

r=me once rebased.

**Comment by utsavoza** [comment]
Ok, rebased @paulrouget

**Comment by jdm** [comment]
@bors-servo retry
* #26129

**Comment by jdm** [comment]
@bors-servo retry
* intermittent filter server error

**Pull request merged**
