### PR TITLE
Fix canvas wpt test "path-objects/2d.path.end.1.html"

### PR DESCRIPTION
**Pull request by pylbrecht**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #25331

- [x] There are tests for these changes

### CODE REVIEW

**Comment by pylbrecht** [comment]
Unfortunately rebasing messed up `Cargo.lock` and I'm not sure how to fix it without creating a bigger mess:
```
./Cargo.lock:1: duplicate versions for package `lyon_geom`
        The following packages depend on version 0.14.0 from 'crates.io':
        The following packages depend on version 0.15.0 from 'crates.io':
./Cargo.lock:1: duplicate versions for package `core-graphics`
        The following packages depend on version 0.17.3 from 'crates.io':
        The following packages depend on version 0.19.0 from 'crates.io':
./Cargo.lock:1: duplicate versions for package `dirs`
        The following packages depend on version 1.0.2 from 'crates.io':
        The following packages depend on version 2.0.2 from 'crates.io':
./Cargo.lock:1: duplicate versions for package `core-foundation`
        The following packages depend on version 0.6.2 from 'crates.io':
        The following packages depend on version 0.7.0 from 'crates.io':
./Cargo.lock:1: duplicate versions for package `core-text`
        The following packages depend on version 13.2.0 from 'crates.io':
        The following packages depend on version 15.0.0 from 'crates.io':
./Cargo.lock:1: duplicate versions for package `core-foundation-sys`
        The following packages depend on version 0.6.2 from 'crates.io':
        The following packages depend on version 0.7.0 from 'crates.io':
./Cargo.lock:1: duplicate versions for package `rand_core`
        The following packages depend on version 0.3.1 from 'crates.io':
        The following packages depend on version 0.4.2 from 'crates.io':
        The following packages depend on version 0.5.1 from 'crates.io':
```

**Comment by pylbrecht** [comment]
?r @jdm

**Review by jdm — APPROVED** [review]
This looks fine, but it will require adding the new duplicated crates to the list of allowed duplicates in servo-tidy.toml.

**Comment by jdm** [comment]
This needs a build to start with `--features layout-2020` to ensure the Cargo.lock is up to date.

**Comment by pylbrecht** [comment]
Is this something I need to do? Because building locally with `--features layout-2020` did not create a diff.

**Comment by jdm** [comment]
Any chance you have uncommitted or staged changes to cargo.lock locally?

**Comment by pylbrecht** [comment]
I'll check that as soon as I'm home.

**Comment by jdm** [comment]
A bunch of extra test results:
```
10 unexpected results that are NOT known-intermittents:
  â–¶ Unexpected subtest result in /2dcontext/path-objects/2d.path.bezierCurveTo.ensuresubpath.2.html:
  â”‚ FAIL [expected PASS] If there is no subpath, the first control point is added
  â”‚   â†’ assert_equals: Red channel of the pixel at (50, 25) expected 0 but got 255
  â”‚ 
  â”‚ _assertPixel@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:38:5
  â”‚ @http://web-platform.test:8000/2dcontext/path-objects/2d.path.bezierCurveTo.ensuresubpath.2.html:29:1
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  â”‚ _addTest/</<@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:66:15
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  â”” _addTest/<@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:63:11


  â–¶ Unexpected subtest result in /2dcontext/path-objects/2d.path.closePath.nextpoint.html:
  â”” PASS [expected FAIL] Canvas test: 2d.path.closePath.nextpoint


  â–¶ Unexpected subtest result in /2dcontext/path-objects/2d.path.rect.zero.4.html:
  â”‚ FAIL [expected PASS] Canvas test: 2d.path.rect.zero.4
  â”‚   â†’ assert_equals: Red channel of the pixel at (50, 25) expected 0 but got 255
  â”‚ 
  â”‚ _assertPixel@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:38:5
  â”‚ @http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.zero.4.html:29:1
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  â”‚ _addTest/</<@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:66:15
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  â”” _addTest/<@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:63:11


  â–¶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.closePath.nextpoint.html:
  â”” PASS [expected FAIL] OffscreenCanvas test: 2d.path.closePath.nextpoint


  â–¶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.bezierCurveTo.ensuresubpath.2.worker.html:
  â”‚ FAIL [expected PASS] If there is no subpath, the first control point is added
  â”‚   â†’ assert_equals: Red channel of the pixel at (50, 25) expected 0 but got 255
  â”‚ 
  â”‚ _assertPixel@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:38:5
  â”‚ @http://web-platform.test:8000/offscreen-canvas/path-objects/2d.path.bezierCurveTo.ensuresubpath.2.worker.js:26:1
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  â”” @http://web-platform.test:8000/offscreen-canvas/path-objects/2d.path.bezierCurveTo.ensuresubpath.2.worker.js:14:3


  â–¶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.closePath.nextpoint.worker.html:
  â”” PASS [expected FAIL] 2d


  â–¶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.rect.zero.4.html:
  â”‚ FAIL [expected PASS] OffscreenCanvas test: 2d.path.rect.zero.4
  â”‚   â†’ assert_equals: Red channel of the pixel at (50, 25) expected 0 but got 255
  â”‚ 
  â”‚ _assertPixel@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:38:5
  â”‚ @http://web-platform.test:8000/offscreen-canvas/path-objects/2d.path.rect.zero.4.html:30:1
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  â”” @http://web-platform.test:8000/offscreen-canvas/path-objects/2d.path.rect.zero.4.html:18:3


  â–¶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.rect.end.1.worker.html:
  â”” PASS [expected FAIL] 2d


  â–¶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.rect.zero.4.worker.html:
  â”‚ FAIL [expected PASS] 2d
  â”‚   â†’ assert_equals: Red channel of the pixel at (50, 25) expected 0 but got 255
  â”‚ 
  â”‚ _assertPixel@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:38:5
  â”‚ @http://web-platform.test:8000/offscreen-canvas/path-objects/2d.path.rect.zero.4.worker.js:26:1
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  â”” @http://web-platform.test:8000/offscreen-canvas/path-objects/2d.path.rect.zero.4.worker.js:14:3


  â–¶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.bezierCurveTo.ensuresubpath.2.html:
  â”‚ FAIL [expected PASS] If there is no subpath, the first control point is added
  â”‚   â†’ assert_equals: Red channel of the pixel at (50, 25) expected 0 but got 255
  â”‚ 
  â”‚ _assertPixel@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:38:5
  â”‚ @http://web-platform.test:8000/offscreen-canvas/path-objects/2d.path.bezierCurveTo.ensuresubpath.2.html:30:1
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  â”” @http://web-platform.test:8000/offscreen-canvas/path-objects/2d.path.bezierCurveTo.ensuresubpath.2.html:18:3

  ▶ FAIL [expected PASS] /2dcontext/building-paths/canvas_complexshapes_beziercurveto_001.htm
  │   → /2dcontext/building-paths/canvas_complexshapes_beziercurveto_001.htm 9fe025348d5fcd3ecb1516ddfa710191645febee
  └   → /2dcontext/building-paths/canvas_complexshapes_beziercurveto_001-ref.htm 20daf1bfa1c3ac14ae492aabd8f112f4ac94de07
```

**Comment by pylbrecht** [comment]
Thanks for pointing that out. I started a build && test-wpt && update-wpt and will push the updated metadata first thing tomorrow morning.

**Comment by pylbrecht** [comment]
Just out of curiosity, why are those css tests failing? And why don't we care about them failing?

**Comment by CYBAI** [comment]
> Just out of curiosity, why are those css tests failing? And why don't we care about them failing?

@pylbrecht they are #24726 and because they are intermittent failures which is not related to this PR, we don't need to care about them for now. 👀

**Comment by pylbrecht** [comment]
Ah ok, I thought the intermittents are filtered out, that's why I wondered. I assume these intermittent failures have not yet been added to the filter then, correct?

**Comment by CYBAI** [comment]
@bors-servo retry

- #24762 (I think it's this one, right 👀?)

**Pull request merged**
