### PR TITLE
Snap to screen pixels instead of px

### LINKED ISSUE #7904: Using a transform breaks subpixel positionning
If an element has a transform (`transform:scale(1)` for example), its coordinates are rounded (`top:11.5px` becomes `top:12px`).

```html
<div id='d1'></div>
<div id='d2'></div>

<style>
  div {
    position: absolute;
    top: 11.5px;
    width: 100px;
    height: 100px;
  }

  #d1 {
    left: 100px;
    background: green;
  }

  #d2 {
    left: 200px;
    background: red;
    transform: scale(1);
  }

</style>
```

Note the green div is a bit higher than the red div:

screen shot 2015-10-07 at 12 53 11

### PR DESCRIPTION
**Pull request by paulrouget**
Fixes #7904

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7909)

### CODE REVIEW

**Comment by glennw** [comment]
@paul This looks like a good fix, thanks! However, we have some CI related issues with pixel-ratio=2 tests at the moment, and I'm a little concerned merging this now will create a lot of intermittent failures (unrelated to your fix).

@jdm Thoughts on the above? Shall we hold off on merging this for now? Merge it with the test marked as flaky?

**Comment by jdm** [comment]
If we have a plan to tackle the pixel snapping test failure, then let's hold off. Otherwise merging with flaky is acceptable.

**Comment by glennw** [comment]
I just checked the reftest.rs code and the assert in question will fire even if the test is marked as flaky. I could update reftest.rs to not assert here if marked as flaky (as a temporary workaround), or we may have to just disable this test for now - thoughts @jdm?

**Comment by jdm** [comment]
I would extend the flaky check to include the image size for now.

**Comment by glennw** [comment]
OK, I'll change the reftest code today and then we'll be able to merge this. @paulrouget could you update this PR to mark your new test as flaky in the meantime?

**Comment by paulrouget** [comment]
As recommended by @mbrubeck I set `resolution=300x300` to avoid the giant window (which I guess it's why the test is flaky)

**Comment by glennw** [comment]
@bors-servo r+

Thanks!

**Comment by mbrubeck** [comment]
@bors-servo retry

#7870

**Pull request merged**
