### PR TITLE
Upgrade ipc-channel to diagnose #8961.

### PR DESCRIPTION
**Pull request by jdm**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9450)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* #9448

**Comment by KiChjang** [comment]
Not this again

**Comment by jdm** [comment]
@bors-servo: retry
* mac infra bustage

**Comment by jdm** [comment]
@bors-servo: retry
* #9063

**Pull request merged**
