### PR TITLE
Implement obsolete IDL attributes for <font> element

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7472)

### CODE REVIEW

**Comment by frewsxcv** [comment]
If this is desire and gets approved, I'll go ahead and implement the rest in 

https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/html/dom/reflection-obsolete.html

https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/dom/reflection-obsolete.html.ini

**Comment by Ms2ger** [comment]
Out of curiosity, why'd you pick those in particular?

**Comment by frewsxcv** [comment]
I don't remember why I picked this set of attributes. If implementing these obsolete IDL attributes is desired, I'm open to closing this and just opening a new one that implements a bunch all at once

**Comment by Ms2ger** [comment]
No, this is fine, just curious.

**Comment by nox** [comment]
It's fine to implement missing IDL attributes, but I'm not too sure about doing that without implementing what they actually do, like the color attribute. See HTMLFontElement::get_color() and Element::synthesize_presentational_hints_for_legacy_attributes().

**Comment by frewsxcv** [comment]
Sounds good. I'll implement those, but to avoid conflicts, going to wait a day or so to see if #7452 merges

**Comment by nox** [comment]
@frewsxcv Thanks. :)

**Comment by nox** [comment]
Stealing review since I commented.

**Comment by nox** [comment]
@metajack This is blocked on #7452, to avoid unnecessary rebases.

**Comment by nox** [comment]
@frewsxcv #7452 landed.

**Comment by frewsxcv** [comment]
Alright cool. I'm on traveling for a few more days, then I'll look into this

**Comment by frewsxcv** [comment]
I'm just going to close this for now. I haven't gotten around to updating this so no point in keeping it around

**Pull request closed without merging**
