### PR TITLE
Reduce size of layout::fragment::Fragment struct

### PR DESCRIPTION
**Pull request by mbrubeck**
This reduces the size of the SpecificFragmentInfo enum from 48 to 24.

r? @pcwalton

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10255)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Maybe we could also switch from `Box<str>` back to `String` now that it doesn't add to the size of `Fragment`.

**Comment by Ms2ger** [comment]
Should we add a unit test for the size of those types?

**Comment by nox** [comment]
@mbrubeck I'm not sure there is any point in doing this, we never change the length of the string right?

**Comment by nox** [comment]
`IframeFragmentInfo` can be unboxed in `SpecificFragmentInfo` now that it fits an `u64`.

**Comment by mbrubeck** [comment]
> Should we add a unit test for the size of those types?

Done.

> `IframeFragmentInfo` can be unboxed in `SpecificFragmentInfo` now that it fits an `u64`.

Done.

**Comment by mbrubeck** [comment]
The long poles are now InlineBlockFragmentInfo and InlineAbsoluteHypotheticalFragmentInfo. They each contain a FlowRef, which is a fat pointer.

**Comment by pcwalton** [comment]
@bors-servo: r+

Nice!

**Comment by emilio** [comment]
This still needs a rebase it seems.

**Pull request merged**
