### PR TITLE
Send display lists over IPC in multiprocess mode.

### PR DESCRIPTION
**Pull request by pcwalton**
This patch set introduces the `--multiprocess` (`-M`) switch. Right now, all it does it cause display lists to be serialized, but eventually it will cause actual processes to be spawned.

r? @metajack

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6795)

### CODE REVIEW

**Comment by metajack** [comment]
-S-awaiting-review +S-awaiting-answer 

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, 4 of 4 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/pipeline.rs, line 197 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGSSbFi3pVEHLcXqwi)** ([raw file](https://github.com/servo/servo/blob/e0aed04369c8382f740d5fbce60908f598ade2d6/components/compositing/pipeline.rs#L197)):</sup>
Not sure why you changed `let _ = ` to `drop()`. The original reason for it was so it was clear we were ignoring the return value. I don't think there is a hidden drop here we are trying to make visible.

---

<sup>**[components/compositing/pipeline.rs, line 202 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGSdm9YnIxqthMmT5H)** ([raw file](https://github.com/servo/servo/blob/e0aed04369c8382f740d5fbce60908f598ade2d6/components/compositing/pipeline.rs#L202)):</sup>
Same as above.

---

<sup>**[components/compositing/pipeline.rs, line 291 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGTlUFRMRHKgNFyXNE)** ([raw file](https://github.com/servo/servo/blob/e0aed04369c8382f740d5fbce60908f598ade2d6/components/compositing/pipeline.rs#L291)):</sup>
Are these layout_to_paint things used anywhere? I can't seem to find where.

---

<sup>**[components/gfx/paint_task.rs, line 206 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGU_tCRlKgkNRRXKaO)** ([raw file](https://github.com/servo/servo/blob/e0aed04369c8382f740d5fbce60908f598ade2d6/components/gfx/paint_task.rs#L206)):</sup>
Shouldn't this be `layout_to_paint_handle`?

---

<sup>**[components/gfx/paint_task.rs, line 207 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGUe5PNx1ThZyzdiKZ)** ([raw file](https://github.com/servo/servo/blob/e0aed04369c8382f740d5fbce60908f598ade2d6/components/gfx/paint_task.rs#L207)):</sup>
Ditto above.

---

<sup>**[components/gfx/platform/macos/font_template.rs, line 72 \[r5\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGWB1HeRod00j8wQ48)** ([raw file](https://github.com/servo/servo/blob/601dca7a5fd6c739f3db76fa37f43ad719e1fae4/components/gfx/platform/macos/font_template.rs#L72)):</sup>
Why is this necessary now? Or was it a bug that this didn't have it originally?

---

<sup>**[components/util/ipc.rs, line 32 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGQDWQYvbaeJUGdCgt)** ([raw file](https://github.com/servo/servo/blob/fcc9793dbabef372e9b89123918906638f0d7c8b/components/util/ipc.rs#L32)):</sup>
Throwing away errors seems wrong. Can you give some explanation for this? Does IPC not have any error semantics on send?sx

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6795)

**Comment by pcwalton** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/pipeline.rs, line 293 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGTlUFRMRHKgNFyXNE)** ([raw file](https://github.com/servo/servo/blob/e0aed04369c8382f740d5fbce60908f598ade2d6/components/compositing/pipeline.rs#L293)):</sup>
Yes, they're used in the invocations of `LayoutTaskFactory::create()` and `PaintTask::create()` in the two methods below.

---

<sup>**[components/gfx/platform/macos/font_template.rs, line 72 \[r5\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGWB1HeRod00j8wQ48)** ([raw file](https://github.com/servo/servo/blob/601dca7a5fd6c739f3db76fa37f43ad719e1fae4/components/gfx/platform/macos/font_template.rs#L72)):</sup>
It should have been there before. We need the mutex so that if two threads try to instantiate the `CachedCTFont` at the same time they won't interfere with one another.

---

<sup>**[components/util/ipc.rs, line 32 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6795#-JvGQDWQYvbaeJUGdCgt)** ([raw file](https://github.com/servo/servo/blob/fcc9793dbabef372e9b89123918906638f0d7c8b/components/util/ipc.rs#L32)):</sup>
IPC senders' error codes are OS-specific and different from OS to OS. At the moment `ipc-channel` does not attempt to abstract over Mach vs. POSIX error codes, as Servo doesn't try to deal with errors in sending on a fine-grained level anyway.

This doesn't actually throw away the error—it just throws away the error *description*.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6795)

**Comment by pcwalton** [comment]
Review comments addressed. r? @metajack

**Comment by metajack** [comment]
@bors-servo r+

-S-awaiting-answer -S-awaiting-review +S-awaiting-merge 

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6795)

**Comment by jdm** [comment]
@pcwalton I'm not convinced that these are just intermittent failures that are suddenly appearing for the first time:
```
/css21_dev/html4/absolute-replaced-height-026.htm
-------------------------------------------------
TIMEOUT expected FAIL [Parent]
/css21_dev/html4/absolute-replaced-height-025.htm
-------------------------------------------------
TIMEOUT expected FAIL [Parent]
/css21_dev/html4/float-replaced-height-004.htm
----------------------------------------------
TIMEOUT expected FAIL [Parent]
/css21_dev/html4/inline-replaced-height-005.htm
-----------------------------------------------
TIMEOUT [Parent]
```
A bunch of similar replaced-height CSS tests failed on the last round too.

**Comment by pcwalton** [comment]
I couldn't reproduce the same set of failures.

**Comment by jdm** [comment]
```
/css21_dev/html4/absolute-replaced-height-026.htm
-------------------------------------------------
TIMEOUT expected FAIL [Parent]
/css21_dev/html4/absolute-replaced-height-033.htm
-------------------------------------------------
TIMEOUT expected FAIL [Parent]
/css21_dev/html4/block-replaced-height-005.htm
----------------------------------------------
TIMEOUT expected FAIL [Parent]
```
No more retries allowed until at least one line of code is changed :)

**Comment by pcwalton** [comment]
(I landed a fix for what I believe to be the problem here)

**Pull request merged**
