### PR TITLE
Partial fix for 12415

### PR DESCRIPTION
**Pull request by scotttrinh**
Fix interface exposure for Bluetooth, which ended up pulling a longer thread of other interfaces into it. Per @jdm just went ahead and did all of the interfaces that `./mach build -d` errored on, so there are a lot of interfaces here.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix (partially) #12415 

- [x] These changes do not require tests because they only removed code

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13803)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Woo!

**Comment by scotttrinh** [comment]
On it!

**Comment by KiChjang** [comment]
Neat!

@bors-servo r=jdm

**Comment by KiChjang** [comment]
@bors-servo retry
* #10473

**Pull request merged**
