### PR TITLE
Update web-platform-tests to revision fab2c513bffb2bd19600d23b495264d123df092f

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11048)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo retry

* servo/saltfs#363

**Comment by larsbergstrom** [comment]
@bors-servo retry
 - https://github.com/servo/saltfs/pull/365

**Comment by Ms2ger** [comment]
@bors-servo retry
* #10473

**Comment by jdm** [comment]
@bors-servo: retry
* ##10473

**Comment by KiChjang** [comment]
@bors-servo retry
* The annoying git

**Pull request merged**
