### PR TITLE
 	layout: Make the stacking context take into account the children transform when calculating overflow areas.

### LINKED ISSUE #12842: Incorrect clipping of nested stacking contexts.
Found while writing a test for #12841.

Should render the two equal-sized rectangles, but actually the inner one is clipped incorrectly:

```html
<!doctype html>
<style>
  .outer-sc {
    transform: translate(-50px, -50px);
    position: absolute;
    width: 250px;
    height: 250px;
    top: 250px;
    left: 250px;
    background: blue;
  }
  .outer-sc:hover {
    background: red;
  }
  .inner-sc {
    transform: translate(50px, 50px);
    position: absolute;
    width: 250px;
    height: 250px;
    top: 250px;
    left: 250px;
    background: green;
  }
  .inner-sc:hover {
    background: yellow;
  }
  html, body { margin: 0; padding: 0; }
</style>
<div class="outer-sc">
  <div class="inner-sc">
  </div>
</div>
```

### PR DESCRIPTION
**Pull request by emilio**
This is a potential fix for #12842. I have done only the math to handle simple transforms because it's three AM, but I'd like @pcwalton to verify my approach, or suggest an alternative.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes partially fix #12842 (github issue number if applicable).

- [x] There are tests for these changes.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12843)

### CODE REVIEW

**Comment by emilio** [comment]
r? @pcwalton 

Doesn't deal with every possible transform, so I'd add that before landing this, but I'd like to verify the approach looks good to you.

Also...
@bors-servo: try

**Comment by emilio** [comment]
I forgot to update the manifest, the rest of tests seem to be passing, but I'll double-check.

@bors-servo: try

**Comment by glennw** [comment]
Reviewed 4 of 5 files at r1, 5 of 5 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/gfx/display_list/mod.rs, line 703 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12843#-KPKIFkSO2ajDL02QB62:-KPKIFkSO2ajDL02QB63:b-dmt82d) ([raw file](https://github.com/servo/servo/blob/6f1fd46860c9aac1f008b1727581931541f79a05/components/gfx/display_list/mod.rs#L703)):*
> ```Rust
>                                                        0.0)
>                                            .mul(&self.transform);
>         let transform_2d = Matrix2D::new(transform.m11, transform.m12,
> ```

This doesn't look like it will work with perspective transforms?

I think it's fine to merge without that, since it seems like a net improvement, but perhaps add a TODO comment.

In particular, browser.html uses a perspective transform with a translateZ to zoom the content in and out. Does this handle that case?

---

*[tests/wpt/mozilla/meta/MANIFEST.json, line 3963 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12843#-KPKHaSuhzmgdfn7Jrqu:-KPKHaSuhzmgdfn7Jrqv:bujjoyz) ([raw file](https://github.com/servo/servo/blob/6f1fd46860c9aac1f008b1727581931541f79a05/tests/wpt/mozilla/meta/MANIFEST.json#L3963)):*
> ```JSON
>           }
>         ],
>         "css/overflow_transformed_sc_rotate_ref.html": [
> ```

This seems like an extra entry?

---

*[tests/wpt/mozilla/meta/MANIFEST.json, line 13207 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12843#-KPKHfusA-5T5GaGShEE:-KPKHfusA-5T5GaGShEF:buo9nmt) ([raw file](https://github.com/servo/servo/blob/6f1fd46860c9aac1f008b1727581931541f79a05/tests/wpt/mozilla/meta/MANIFEST.json#L13207)):*
> ```JSON
>         }
>       ],
>       "css/overflow_transformed_sc_rotate_ref.html": [
> ```

Same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12843)*

**Comment by glennw** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12843)*

**Comment by emilio** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/gfx/display_list/mod.rs, line 703 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12843#-KPKIFkSO2ajDL02QB62:-KPKPh0LqKnROdO1tM2B:by6ck54) ([raw file](https://github.com/servo/servo/blob/6f1fd46860c9aac1f008b1727581931541f79a05/components/gfx/display_list/mod.rs#L703)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary>
> This doesn't look like it will work with perspective transforms?
> 
> I think it's fine to merge without that, since it seems like a net improvement, but perhaps add a TODO comment.
> 
> In particular, browser.html uses a perspective transform with a translateZ to zoom the content in and out. Does this handle that case?
> 
</details>
Yep, you're right. Added a TODO comment.

It handles at least as many transformations as before, since we're only increasing the overflow area. Just in case, just checked and it works fine with this patch applied.

---

*[tests/wpt/mozilla/meta/MANIFEST.json, line 3963 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12843#-KPKHaSuhzmgdfn7Jrqu:-KPKXbNAkYw03p6yXMzO:b-dlr2of) ([raw file](https://github.com/servo/servo/blob/6f1fd46860c9aac1f008b1727581931541f79a05/tests/wpt/mozilla/meta/MANIFEST.json#L3963)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary>
> This seems like an extra entry?
</details>
Yep, forgot to remove the `<link rel=match>` from the reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12843)*

**Comment by glennw** [comment]
@emilio r=me with those fixes

**Pull request merged**
