### PR TITLE
Implement mouseevent.which (needed for enyojs sampler).

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6691)

### CODE REVIEW

**Comment by Ms2ger** [comment]
There appears to be another change in this commit that isn't covered by the commit message. It seems like you should have two distinct commits in this PR.

**Comment by glennw** [comment]
@Ms2ger split into two commits.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/document.rs, line 653 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6691#-JumqSb0VTUvKyNh0slu)** ([raw file](https://github.com/servo/servo/blob/2a2c7e18c00920e9c943e5fca33b593a2a7f76fa/components/script/dom/document.rs#L653)):</sup>
This should use the button method argument instead.

---

<sup>**[components/script_traits/lib.rs, line 48 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6691#-Jumqn-Ij_n83UnPUMfc)** ([raw file](https://github.com/servo/servo/blob/2e074ce452e3c9ffcf9accbb6455130272a857ad/components/script_traits/lib.rs#L48)):</sup>
Why's this necessary?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6691)

**Comment by glennw** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/document.rs, line 653 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6691#-JumqSb0VTUvKyNh0slu)** ([raw file](https://github.com/servo/servo/blob/2a2c7e18c00920e9c943e5fca33b593a2a7f76fa/components/script/dom/document.rs#L653)):</sup>
I'm not sure I understand what you mean? This is making the default detail field closer to the spec, which says "indicates the current click count incremented by one. For example, if no click happened before the mousedown, UIEvent.detail will contain the value 1"

---

<sup>**[components/script_traits/lib.rs, line 48 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6691#-Jumqn-Ij_n83UnPUMfc)** ([raw file](https://github.com/servo/servo/blob/2e074ce452e3c9ffcf9accbb6455130272a857ad/components/script_traits/lib.rs#L48)):</sup>
I was finding it useful when debugging hit tests and figured it's useful to have - I can remove from this commit if you'd prefer.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6691)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/document.rs, line 653 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6691#-JumqSb0VTUvKyNh0slu)** ([raw file](https://github.com/servo/servo/blob/2a2c7e18c00920e9c943e5fca33b593a2a7f76fa/components/script/dom/document.rs#L653)):</sup>
Please add a `let clickCount = 1` and pass that instead, in that case.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6691)

**Comment by glennw** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/document.rs, line 653 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6691#-JumqSb0VTUvKyNh0slu)** ([raw file](https://github.com/servo/servo/blob/2a2c7e18c00920e9c943e5fca33b593a2a7f76fa/components/script/dom/document.rs#L653)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6691)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6691)

**Pull request merged**
