### PR TITLE
Enable XR WPT tests

### PR DESCRIPTION
**Pull request by Manishearth**
This enables the tests. Most still fail, I plan to go through the
failures more soon.

xrFrame_getPose's failure seems to indicate we have broken matrix math.
I'm not sure what, the bug seems to not come from a simple matrix
inversion/ordering mishap.

This does add empty stubs for session ending since the test infra relies on these existing for almost every test (https://github.com/servo/servo/issues/23788). We will need to add support for this from the webxr repo side. We also need to add support for user activation (https://github.com/servo/servo/issues/23787).

r? @asajeffrey

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23786)

### CODE REVIEW

**Review by asajeffrey — COMMENTED** [review]
@bors-servo r+

**Comment by CYBAI** [comment]
```
+ ./mach test-tidy --no-progress --all
[36m 0:05.29(B[m [34mINFO(B[m Diffing old and new manifests /repo/tests/wpt/mozilla/meta/MANIFEST.json
[36m 0:05.36(B[m [34mINFO(B[m Diffing old and new manifests /repo/tests/wpt/webgl/meta/MANIFEST.json
[36m 0:05.58(B[m [34mINFO(B[m Diffing old and new manifests /repo/tests/wpt/metadata/MANIFEST.json

Checking the config file...

Checking the wpt manifest file...

Checking directories for correct file extensions...

Running the WPT lint on ./tests/wpt/web-platform-tests/...

Running the WPT lint on ./tests/wpt/mozilla/tests/...

Checking files for tidiness...

[94m./components/script/dom/xrtest.rs[0m:[93m168[0m: [91mmethod declared in webidl is missing a comment with a specification link[0m

[94m./components/script/dom/xrtest.rs[0m:[93m173[0m: [91mmethod declared in webidl is missing a comment with a specification link[0m

Running the dependency licensing lint...
```

**Pull request merged**
