### PR TITLE
Remove unused imports in the Python files

### PR DESCRIPTION
**Pull request by frewsxcv**
Found using flake8

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6235)

### CODE REVIEW

**Comment by frewsxcv** [comment]
It'd be great if flake8 would run on the Python files as part of the tidy process

**Comment by metajack** [comment]
@bors-servo: r+

-S-awaiting-review +S-awaiting-merge 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- python/mach/mach/commands/settings.py @ r1
- python/mach/mach/main.py @ r1
- python/mach/mach/test/common.py @ r1
- python/mach/mach/test/providers/throw.py @ r1
- python/mach/mach/test/test_entry_point.py @ r1
- python/mozlog/mozlog/structured/handlers/statushandler.py @ r1
- python/servo/build_commands.py @ r1
- python/servo/post_build_commands.py @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6235)

**Comment by metajack** [comment]
@frewsxcv You should file a bug for that. Sounds like a great feature.

**Comment by frewsxcv** [comment]
> You should file a bug for that.

Filed: #6236

**Pull request merged**
