### PR TITLE
rewrite of mime_classifier.rs to use more iterators

### PR DESCRIPTION
**Pull request by tafia**
Rewrite few parts of the file to use more iterators.

Note that I have **no idea** what the code is actually doing functionally, I just tried to mimic exactly what was being done. All tests are ok

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7227)

### CODE REVIEW

**Comment by tafia** [comment]
I don't really understand the error. I doesn't seem to be linked with my changes (I don't use setuptools).

```
Error running mach:

    ['test-tidy']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

ImportError: No module named setuptools

  File "/home/johann/projects/servo/python/servo/testing_commands.py", line 222, in test_tidy
    return tidy.scan()
  File "./python/tidy.py", line 288, in scan
    errors = list(itertools.chain(errors, r_errors))
  File "./python/tidy.py", line 248, in collect_errors_for_files
    for error in check(file_name, contents):
  File "./python/tidy.py", line 133, in check_flake8
    from flake8.main import check_code
  File "./python/dependencies/flake8-2.4.1-py2.py3-none-any.whl/flake8/main.py", line 6, in <module>
```

**Comment by Ms2ger** [comment]
```
components/net/mime_classifier.rs:93: trailing whitespace
components/net/mime_classifier.rs:178: trailing whitespace
components/net/mime_classifier.rs:194: trailing whitespace
components/net/mime_classifier.rs:200: trailing whitespace
components/net/mime_classifier.rs:205: trailing whitespace
components/net/mime_classifier.rs:352: trailing whitespace
components/net/mime_classifier.rs:372: trailing whitespace
components/net/mime_classifier.rs:383: trailing whitespace
components/net/mime_classifier.rs:385: trailing whitespace
components/net/mime_classifier.rs:393: trailing whitespace
components/net/mime_classifier.rs:399: trailing whitespace
components/net/mime_classifier.rs:400: trailing whitespace
components/net/mime_classifier.rs:402: trailing whitespace
components/net/mime_classifier.rs:403: trailing whitespace
```

**Comment by tafia** [comment]
How did you get this ? Is there a command to check for all the trailing whitespaces ?

**Comment by Ms2ger** [comment]
Yes, that's what `./mach test-tidy` is supposed to do, but in this case, I just copied from the Travis log.

**Comment by tafia** [comment]
Ok thanks. Just pushed removing said whitespaces.

I can't run rust-tidy on my side (cf my previous message).
Should I fill a separate issue for that ?

**Comment by tafia** [comment]
And rebased

**Comment by Ms2ger** [comment]
Yeah, please do file that.

**Comment by tafia** [comment]
rebased again

**Comment by jdm** [comment]
Sorry, I started reviewing this and got interrupted. I'll finish it up today.

**Comment by jdm** [comment]
Thanks for doing this work! I have some comments that I think should make the code more clear for future readers, but I appreciate this effort :)
-S-awaiting-review 

---

Review status: 0 of 1 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

<sup>**[components/net/mime_classifier.rs, line 128 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxgGPXkT8Zrm2lf0aMu)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L128)):</sup>
Why `s` and `m`?

---

<sup>**[components/net/mime_classifier.rs, line 131 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxfDhT73Kd0jKbb9jeN)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L131)):</sup>
nit:
```rust
let result = self.clone().zip(...);
if result {
    self.nth(matches.len());
}
result
```

---

<sup>**[components/net/mime_classifier.rs, line 153 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxfCMEvujY1BaEm8vxl)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L153)):</sup>
Does `.zip(&self.pattern).zip(&self.mask)` work?

---

<sup>**[components/net/mime_classifier.rs, line 154 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxfCV7BWxHcs9dDOnE_)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L154)):</sup>
`all(|((&data, &pattern), &mask)| (data & mask) == (pattern & mask))`

---

<sup>**[components/net/mime_classifier.rs, line 205 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxWfEyU_2Veugdmrur3)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L205)):</sup>
nit: extra space after =

---

<sup>**[components/net/mime_classifier.rs, line 209 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxWgKQuBe3G1bg20aHb)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L209)):</sup>
I suspect this could be `data[16..box_size].chunks(4).any(|chunk| chunk.starts_with(&mp4))`.

---

<sup>**[components/net/mime_classifier.rs, line 348 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxfBcyI11TYh4i4tH97)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L348)):</sup>
Can we make this return a more descriptive enum instead of what is effectively a tri-state bool? Something like DidNotMatch, MatchedStart, MatchedStartAndEnd?

---

<sup>**[components/net/mime_classifier.rs, line 350 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-Jxf4gNAoFwnIoPbXNwa)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L350)):</sup>
Let's invert this condition and return early instead.

---

<sup>**[components/net/mime_classifier.rs, line 352 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxWkCnH5b0JGmq8jECZ)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L352)):</sup>
find(...).is_some()

---

<sup>**[components/net/mime_classifier.rs, line 353 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxWkITv-4zKejPEav0U)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L353)):</sup>
nit: no need for an `else` after a `return`

---

<sup>**[components/net/mime_classifier.rs, line 357 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-Jxf5FjEI2kV4a2k-32w)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L357)):</sup>
I think I'd prefer:
```rust
while !matcher.matches(end) {
    if match.next().is_none() {
        return Some(false);
    }
}

Some(true)
```

---

<sup>**[components/net/mime_classifier.rs, line 383 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-Jxf96sLU__Lq0BLDmIh)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L383)):</sup>
nit:
```rust
if ... {
    ...
}
```

---

<sup>**[components/net/mime_classifier.rs, line 394 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-Jxf91JqFN4fWJlJMvws)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L394)):</sup>
I would prefer
```rust
if ... {
   ...
}
```
rather than all on one line for these.

---

<sup>**[components/net/mime_classifier.rs, line 396 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxfBBl1bS-1b_KA2tc-)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L396)):</sup>
I would prefer `while matcher.next().is_some() {`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by tafia** [comment]
<sup>**[components/net/mime_classifier.rs, line 128 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxgGPXkT8Zrm2lf0aMu)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L128)):</sup>
`s`elf and `m`atches ... but we could change that

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by tafia** [comment]
<sup>**[components/net/mime_classifier.rs, line 131 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxfDhT73Kd0jKbb9jeN)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L131)):</sup>
yep

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by tafia** [comment]
<sup>**[components/net/mime_classifier.rs, line 153 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxfCMEvujY1BaEm8vxl)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L153)):</sup>
I think I tried and it didn't at that time. I'll try again tonight or tomorrow night

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by tafia** [comment]
<sup>**[components/net/mime_classifier.rs, line 154 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxfCV7BWxHcs9dDOnE_)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L154)):</sup>
ok

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by tafia** [comment]
<sup>**[components/net/mime_classifier.rs, line 205 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxWfEyU_2Veugdmrur3)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L205)):</sup>
yes ... we should have it in `./mach test-tidy`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by tafia** [comment]
<sup>**[components/net/mime_classifier.rs, line 209 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxWgKQuBe3G1bg20aHb)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L209)):</sup>
nice! 
Didn't think of chunk for `step_by` replacement

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by tafia** [comment]
<sup>**[components/net/mime_classifier.rs, line 348 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7227#-JxfBcyI11TYh4i4tH97)** ([raw file](https://github.com/servo/servo/blob/7b9b791e289e152fd41f51599d9304bb92ca9f8d/components/net/mime_classifier.rs#L348)):</sup>
sure ...

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by tafia** [comment]
Thanks for the review!
I'll try to address them all as soon as possible.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by jdm** [comment]
One note for the future - Reviewable allows making multiple comments and publishing all at once :)

**Comment by tafia** [comment]
Rebased and made all the changes

> One note for the future - Reviewable allows making multiple comments and publishing all at once :)

Sorry ... :smile:

**Comment by jdm** [comment]
Go ahead and squash these into a single commit :) I think it's ready to merge, assuming the tests still pass!
-S-awaiting-review -S-needs-rebase 

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7227)

**Comment by tafia** [comment]
Here you go
All unit tests are ok.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks a lot!

**Comment by tafia** [comment]
Thanks for the review!

**Pull request merged**
