### PR TITLE
Use clang-cl for Windows builds

### PR DESCRIPTION
**Pull request by jdm**
Depends on https://github.com/servo/mozjs/pull/178.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23256)

### CODE REVIEW

**Comment by jdm** [comment]
This passed appveyor and taskcluster without any issues, which was a delightful surprise.

**Comment by asajeffrey** [comment]
LGTM, you can r=me, or wait until someone with a windows machine can test it.

**Comment by jdm** [comment]
I tested this on my windows laptop and it worked better than the MSVC build, since that one could not actually complete \o/

@bors-servo r=asajeffrey

**Pull request merged**
