### PR TITLE
FIFO unrooting failure with dictionaries #5107

### PR DESCRIPTION
**Pull request by gurobokum**
cross order of declaration and implementation Bindings/

### CODE REVIEW

**Comment by jdm** [comment]
Thanks for solving this @JIoJIaJIu! However, I think the solution here is not guaranteed to always work; it just happens to work due to the names of the fields involved. Fields of structures are destructed in source order from first to last, so I think we can organize our generated code in the proper way if we move the initialization of the `parent` field to follow all of the other members. Does that make sense?

**Comment by Ms2ger** [comment]
Note that the spec defines the order in which those properties should be read.

**Comment by jdm** [comment]
@Ms2ger Got a pointer to that logic?

**Comment by jdm** [comment]
Ok, step 4 in https://heycam.github.io/webidl/#es-dictionary negates my idea. I need to think about this more.

**Comment by jdm** [comment]
We could try reversing the declaration of the structure fields but leaving the instantiation in the order it is today. That would make them be destroyed in LIFO order as expected.

**Comment by JIoJIaJIu** [comment]
Mb it's better way to implement counter-checker on base HashMap in ROOTS_COLLECTION? Not stack?

**Comment by jdm** [comment]
No, the stack is important to preserve the last-in first-out property that SpiderMonkey requires.

**Comment by JIoJIaJIu** [comment]
> We could try reversing the declaration of the structure fields but leaving the instantiation in the order it is today

I did it, declaration in one order and implementation in another. It's no good?

**Comment by jdm** [comment]
Oh, hmm. Apparently I didn't read closely enough. I'll take another look at this PR.

**Comment by metajack** [comment]
@jdm Still intending to look at this or shall I pick somone to assign it to?

**Comment by jdm** [comment]
My fault. I'll look at it.

**Comment by larsbergstrom** [comment]
Please rebase this PR and then reopen. It has been temporarily closed to avoid generating excessive work for GitHub's servers.

**Pull request closed without merging**
