### PR TITLE
Reduce node.unique_id size

### PR DESCRIPTION
**Pull request by vegayours**
#8360

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8589)

### CODE REVIEW

**Comment by eefriedman** [comment]
Please squash the commits.  Otherwise looks good.

**Comment by vegayours** [comment]
>Please squash the commits. 

done

**Comment by vegayours** [comment]
I'm not sure how to deal with this.

Should I manually add uuid to gonk and cef  (?glutin) Cargo.lock files in /ports/?

**Comment by eefriedman** [comment]
Sorry, I should have spotted that.

You can use something like `./mach update-cargo -p uuid`, I think.  (Not 100% sure that's the right command.)

**Comment by vegayours** [comment]
It will bump uuid to 0.1.18. Is it ok?

**Comment by eefriedman** [comment]
Yes, that's fine.

**Comment by vegayours** [comment]
up

**Pull request merged**
