### PR TITLE
Add optional ANGLE support to glutin port

### PR DESCRIPTION
**Pull request by jdm**
Supporting ANGLE in Servo has two important benefits:
* we can actually run Servo instances on our Windows CI machines, which gives us more confidence that we're not breaking it
* we can continue to use OpenGL on devices like the Hololens, rather than creating platform-specific graphical backends

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22856)

### CODE REVIEW

**Comment by jdm** [comment]
```
  = note: libmozjs_sys-6b3e033fa04d5c95.rlib(Unified_cpp_js_src26.obj) : error LNK2005: DllMain already defined in libmozangle-63c01c32ef560396.rlib(global_state.o)
```

**Comment by atouchet** [comment]
It would be nice to update gl_generator in mozangle first so that this doesn't end up re-adding old duplicate dependencies.

**Comment by jdm** [comment]
```
Traceback (most recent call last):
  File "c:/Users/task_1551299964/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/c815382/mozjs/js/src/../../configure.py", line 127, in <module>
    sys.exit(main(sys.argv))
  File "c:/Users/task_1551299964/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/c815382/mozjs/js/src/../../configure.py", line 34, in main
    return config_status(config)
  File "c:/Users/task_1551299964/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/c815382/mozjs/js/src/../../configure.py", line 122, in config_status
    return config_status(args=[], **encode(sanitized_config, encoding))
  File "c:\Users\task_1551299964\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\c815382\mozjs\python\mozbuild\mozbuild\config_status.py", line 147, in config_status
    the_backend.consume(definitions)
  File "c:\Users\task_1551299964\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\c815382\mozjs\python\mozbuild\mozbuild\backend\base.py", line 126, in consume
    for obj in objs:
  File "c:\Users\task_1551299964\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\c815382\mozjs\python\mozbuild\mozbuild\frontend\emitter.py", line 195, in emit
    objs = list(self._emit_libs_derived(contexts))
  File "c:\Users\task_1551299964\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\c815382\mozjs\python\mozbuild\mozbuild\frontend\emitter.py", line 285, in _emit_libs_derived
    contexts[lib.objdir])
mozbuild.frontend.reader.SandboxValidationError: 
==============================
FATAL ERROR PROCESSING MOZBUILD FILE
==============================
The error occurred while processing the following file or one of the files it includes:
    c:/Users/task_1551299964/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/c815382/mozjs/config/external/nspr/moz.build
The error occurred when validating the result of the execution. The reported error is:
    The static "nspr" library is not used in a shared library or a program, but USE_LIBS contains the following shared library names:
        nspr4
        plc4

```

**Comment by jdm** [comment]
```
C:\Users\task_1551404782\repo>mach smoketest 
Servo exited with return value -1073741515
```
Sigh.

**Comment by jdm** [comment]
When I build and run on servo-windows3 I get: `Couldn't create ANGLE context: OpenGlVersionNotSupported`

**Comment by jdm** [comment]
I got farther by making gl_version() return GlThenGles; now the failure is EGL_BAD_SURFACE returned from eglSwapBuffers.

**Comment by jdm** [comment]
Wrench runs with Angle on the same machine, so at least I'm not trying to do something completely hopeless.

**Comment by jdm** [comment]
These changes made Servo successfully run:
```diff
diff --git a/ports/servo/glutin_app/window.rs b/ports/servo/glutin_app/window.rs
index 761e6803e5..2aff72f86d 100644
--- a/ports/servo/glutin_app/window.rs
+++ b/ports/servo/glutin_app/window.rs
@@ -259,13 +259,20 @@ impl Window {
         };
 
         fn init<Context: glutin::GlContext>(context: &Context) -> Rc<dyn gl::Gl> {
-            match gl::GlType::default() {
-                gl::GlType::Gl => unsafe {
+		unsafe {
+                    context
+                        .make_current()
+                        .expect("unable to make context current!");
+}
+
+            match context.get_api() {
+                Api::OpenGl => unsafe {
                     gl::GlFns::load_with(|s| context.get_proc_address(s) as *const _)
                 },
-                gl::GlType::Gles => unsafe {
+                Api::OpenGlEs => unsafe {
                     gl::GlesFns::load_with(|s| context.get_proc_address(s) as *const _)
                 },
+				Api::WebGl => unreachable!(),
             }
         };
 
@@ -436,7 +443,10 @@ impl Window {
 
     #[cfg(not(any(target_arch = "arm", target_arch = "aarch64")))]
     fn gl_version() -> GlRequest {
-        return GlRequest::Specific(Api::OpenGl, (3, 2));
+        GlRequest::GlThenGles {
+			opengl_version: (3, 2),
+			opengles_version: (3, 0),
+		}
     }
 
     #[cfg(any(target_arch = "arm", target_arch = "aarch64"))]
```

**Comment by jdm** [comment]
Just waiting on https://github.com/servo/mozjs/pull/170 to fix the first commit, but this is ready for review otherwise.

**Comment by paulrouget** [comment]
The changes look good to me. r=me. But can you clarify something for me:

It's not what I thought it would look like. The fact we have to copy egl.rs from glutin and create the whole context manually is a bit sad. I'm surprised there is not an "easier" way. I don't know much about Angle and I haven't look at Glutin's EGL support much, but from what I understand, Angles provides a gles library and allows a creation of a EGL surface out of a native window. I thought that would be enough for Glutin to use Angle's EGL implementation transparently.

**Comment by jdm** [comment]
As far as I can tell, this is the state of the world:
* mozangle builds a static library
* glutin fetches EGL symbols from [DLLs](https://github.com/tomaka/glutin/blob/fad332c6bda7d84f6523118554f75e120a4ef99f/src/api/egl/mod.rs#L34-L43)
* adding ANGLE support to glutin would be straightforward if mozangle produced a DLL

With the current mozangle setup, our choices are forking all of glutin in order to add explicit static library support for mozangle (which I don't expect would be upstreamable), or ignoring glutin and forking the EGL code in particular (which this current PR does).

I'm going to spend a bit more time looking into what it would take to produce a DLL from mozangle.

**Comment by jdm** [comment]
Bleah, this is complicated by the fact that we already rely on ANGLE for our shader validation.

**Comment by jdm** [comment]
Ah, if mozangle produced a DLL named libEGL.dll then glutin would probably Just Work without any changes.

**Comment by jdm** [comment]
I made mozangle produce the right DLL in https://github.com/servo/mozangle/pull/15. @paulrouget I think you will be much happier about the changes now!

**Comment by paulrouget** [comment]
Great! r=me for the Servo changes.

**Comment by CYBAI** [comment]
Error in Travis and AppVeyor 👀

```
error[E0599]: no function or associated item named `gl_version` found for type `glutin_app::window::Window` in the current scope
   --> ports/servo/glutin_app/window.rs:812:38
    |
141 | pub struct Window {
    | ----------------- function or associated item `gl_version` not found for this
...
812 |                     .with_gl(Window::gl_version())
    |                              --------^^^^^^^^^^
    |                              |
    |                              function or associated item not found in `glutin_app::window::Window`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0599`.
error: Could not compile `servo`.
```

**Comment by jdm** [comment]
Those are weird errors, since that code does not exist in the branch that it claims to be compiling :/

**Comment by jdm** [comment]
Oops. I had not rebased over #22953.

**Comment by CYBAI** [comment]
@bors-servo retry

- #22955

**Comment by CYBAI** [comment]
Ahh, I see. I thought it failed with `could not read file` 😓

```
C:\Users\task_1552340808\repo>mach smoketest --angle 
Servo exited with return value -1073741515
[taskcluster 2019-03-11T22:52:44.514Z]    Exit Code: 3221225781
[taskcluster 2019-03-11T22:52:44.514Z]    User Time: 0s
[taskcluster 2019-03-11T22:52:44.514Z]  Kernel Time: 0s
[taskcluster 2019-03-11T22:52:44.514Z]    Wall Time: 987.2872ms
[taskcluster 2019-03-11T22:52:44.514Z]       Result: FAILED
[taskcluster 2019-03-11T22:52:44.514Z] === Task Finished ===
[taskcluster 2019-03-11T22:52:44.514Z] Task Duration: 36m16.449888s
```

**Comment by jdm** [comment]
Sigh, still the same error:
```
[taskcluster 2019-04-01T21:46:53.340Z] Executing command 10: mach smoketest --angle
C:\Users\task_1554151120\repo>mach smoketest --angle 
Servo exited with return value -1073741515
```

**Comment by jdm** [comment]
@bors-servo retry
* #23360

**Pull request merged**
