### PR TITLE
Use software rendering when running servo in headless mode

### LINKED ISSUE #13515: Use software rendering for headless mode
Using Ubuntu 14.04 in a VMWare instance, when I try to run using `./mach run tests/html/about-mozilla.html -z` I get this:

```
Could not open dynamic library `OsMesa` (thread main, at ../src/libcore/option.rs:707)
stack backtrace:
   0:     0x555559ac2081 - backtrace::backtrace::libunwind::trace
                        at /home/jdm/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:82
                         - backtrace::backtrace::trace<closure>
                        at /home/jdm/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x555559ac2d00 - backtrace::capture::{{impl}}::new
                        at /home/jdm/servo/./.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/lib.rs:96
   2:     0x555555a1e06b - servo::main::{{closure}}
                        at /home/jdm/servo/components/servo/main.rs:121
   3:     0x55555abf3315 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   4:     0x55555abf31e2 - std::panicking::begin_panic::hfbeda5aad583dc32
   5:     0x55555abf3120 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   6:     0x55555abf30a1 - rust_begin_unwind
   7:     0x55555ac2fb6c - core::panicking::panic_fmt::h4395919ece15c671
   8:     0x55555ac2fbe5 - core::option::expect_failed::h5dd2c705a513d3b5
   9:     0x555555a9b623 - core::option::{{impl}}::expect<&osmesa_sys::OsMesa>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:293
  10:     0x555555a9f70c - osmesa_sys::{{impl}}::get_static_ref
                        at /home/jdm/servo/./.cargo/git/checkouts/osmesa-rs-24b69bbfee7f092a/master/lib.rs:29
  11:     0x555555a9fd94 - osmesa_sys::OSMesaCreateContextAttribs
                        at /home/jdm/servo/./.cargo/git/checkouts/osmesa-rs-24b69bbfee7f092a/master/lib.rs:29
  12:     0x555555a77e57 - glutin_app::window::{{impl}}::new
                        at /home/jdm/servo/ports/glutin/window.rs:129
  13:     0x555555a78453 - glutin_app::window::{{impl}}::new
                        at /home/jdm/servo/ports/glutin/window.rs:229
  14:     0x555555a7fb3d - glutin_app::create_window
                        at /home/jdm/servo/ports/glutin/lib.rs:49
  15:     0x555555a139aa - servo::main
                        at /home/jdm/servo/components/servo/main.rs:138
  16:     0x55555abfbc96 - __rust_maybe_catch_panic
  17:     0x55555abf241b - std::rt::lang_start::haaae1186de9de8cb
  18:     0x555555a1e3c3 - main
  19:     0x7ffff5a22ec4 - __libc_start_main
  20:     0x5555558d3759 - <unknown>
  21:                0x0 - <unknown>
[Inferior 1 (process 1099) exited with code 0145]
```

cc @glennw

### PR DESCRIPTION
**Pull request by kimsnj**
Properly setting environment to use OsMesa in headless mode.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13515

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because I manually ran: `./mach run -d tests/html/about-mozilla.html -z`

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14379)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
This looks great; thanks!

**Comment by KiChjang** [comment]
@bors-servo retry
* 403 Forbidden (but is very not so)

**Comment by KiChjang** [comment]
@bors-servo retry
* Still forbidden

**Comment by KiChjang** [comment]
@bors-servo retry
* #13776

**Comment by kimsnj** [comment]
The intermittent issues that impacted the build so far:
- #14026 
- #14229
- #14317
(plus the one cited above by KiChJang)

The most surprising is the call to: https://www.joshmatthews.net/intermittent-tracker/query.py?name=%2Fhr-time%2Ftest_cross_frame_start.html (obtained by running `filter-intermittents` with the same input in local) that properly works in the browser but not on these builds…

**Comment by Wafflespeanut** [comment]
Yes, we can ignore that. It got [landed very recently](https://github.com/servo/servo/pull/14331), and we're experiencing some issues with it (which will be fixed soon, hopefully).

**Comment by KiChjang** [comment]
@bors-servo retry
* #14229

**Pull request merged**
