### PR TITLE
CI: run WPT tests on macOS

### LINKED ISSUE #28284: Run WPT tests (macOS)

### PR DESCRIPTION
**Pull request by delan**
This patch uncomments and fixes the mac-wpt job in the main workflow, with a few changes:

* we downgrade python3 and pip3 to 3.9, because inspect.getargspec was [removed in 3.11](https://docs.python.org/3/whatsnew/3.11.html#removed)
    * we should apparently move to [inspect.getfullargspec](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec)
* we download the real Servo artifact, rather than the fake Servo for testing

We also align the rest of the job (other than `--timeout-multiplier`) to be as close as possible to linux-wpt, based on the assumption that linux-wpt is more up to date. This includes:

* setting strategy.fail-fast to false
* adding a failure() condition to the “Archive logs” step
* adding the chunk id to log filenames

There are some failing WPT tests, so for now the job is not required to succeed.

Example run: <https://github.com/delan/servo/actions/runs/3837530905>

---

- [ ] ~~`./mach build -d` does not report any errors~~
- [ ] ~~`./mach test-tidy` does not report any errors~~
- [x] These changes fix #28284 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they affect the CI configuration

### CODE REVIEW

**Comment by delan** [comment]
oops, hit ctrl+enter by accident, but i’ve finished the description now!

**Comment by andreubotella** [comment]
>       * we should apparently move to [inspect.getfullargspec](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec)

For the record, `mach` only ever seems to use the `args` property of `inspect.getargspec()`, and that is unchanged in `inspect.getfullargspec()`. In fact, in Python 3.10 [`getargspec` is implemented as a wrapper](https://github.com/python/cpython/blob/3.10/Lib/inspect.py#L1211) over `getfullargspec` that passes through a number of its properties, including `args`. So updating `mach` to support Python 3.11 should be trivial.

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
Yikes.

**Pull request merged**
