### PR TITLE
Fix animation serialization 15398 pt2

### LINKED ISSUE #15398: Serialization of animation and transition shorthand is wrong
Each longhand of animation shorthand is a list, and `animation` shorthand should be serializable only when all the lists have the same length. And the serialization should be a list of each animation, rather than a list of lists for each longhand.

For example,
```css
animation-name: bounce, roll;
animation-duration: 1s, 200ms;
animation-timing-function: ease-in, linear;
animation-delay: 0s, 1s;
animation-direction: normal, reverse;
animation-fill-mode: forwards, backwards;
animation-iteration-count: infinite, 2;
animation-play-state: paused, running;
```
should be serialized to something like
```css
animation: 1s ease-in 0s normal forwards infinite paused bounce, 200ms linear 1s reverse backwards 2 running roll;
```
not
```css
animation: 1s, 200ms ease-in, linear 0s, 1s normal, reverse forwards, backwards infinite, 2 paused, running bounce, roll;
```

The relevant code is https://github.com/servo/servo/blob/master/components/style/properties/shorthand/box.mako.rs#L310-L335

(Maybe an easy issue? cc @Manishearth)

### PR DESCRIPTION
**Pull request by absoludity**
Fixes animation serialization so that an animation shorthand is serialized only when the value lists have the same length (part of #15398)

There are two commits here - the first is a refactoring to update PropertyDeclarationBlock::to_css to match the spec (please see the full commit message for perhaps too many details).

The second commit utilizes the changes in the first, and updates the animation serialization itself to write an empty serialization if the longhand value lists have different lengths, as per the original issue.
Interestingly, the refactoring of the first commit simplified quite a lot more than the fix for this bug, in particular, the special case of 'overflow' shorthand serialization is handled by default, without the extra special case code (now removed).

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15398 (github issue number if applicable).
- [X] There are tests for these changes OR

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15685)

### CODE REVIEW

**Comment by absoludity** [comment]
@upsuper I think this looks like a better way to go for fixing #15398 - actually fixing the algorithm to match the spec, which had some pleasant surprises :) Let me know if you think the direction is correct - I can update background and transition similarly to the 2nd smaller commit here.

**Comment by upsuper** [comment]
Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/style/properties/declaration_block.rs, line 347 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcMt7b9UasX2GfLTiO:-KdcMt7b9UasX2GfLTiP:bko6cql) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L347)):*
> ```Rust
>                     // Substep 5 - Let value be the result of invoking serialize a CSS
>                     // value of current longhands.
>                     let mut value = String::from("");
> ```

`String::new()` is enough.

---

*[components/style/properties/declaration_block.rs, line 352 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcU7TR9RiUQcva16Sr:-KdcU7TR9RiUQcva16Ss:bb1i5u4) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L352)):*
> ```Rust
>                         Some(appendable_value) => {
>                             // Also demo test of overflow with important - I think it'll not
>                             // be correct.
> ```

I don't quite get what did you mean here. And I guess it isn't a comment suitable to be put in code.

---

*[components/style/properties/declaration_block.rs, line 358 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcMjqd7PVLHUDlVo-_:-KdcMjqeyl7oI1DDGLJV:b-1k2asa) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L358)):*
> ```Rust
> 
>                     // Substep 6
>                     if value == "" {
> ```

`value.is_empty()` is probably better.

---

*[components/style/properties/declaration_block.rs, line 363 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcSJTFfKvnGgpZETbq:-KdcSJTFfKvnGgpZETbr:b-bm355k) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L363)):*
> ```Rust
> 
>                     // Substeps 7 and 8
>                     try!(append_serialization::<W, Cloned<slice::Iter< &PropertyDeclaration>>, _>(
> ```

I suspect whether we really need to specify types for the generic parameters... Could you try removing them?

---

*[components/style/properties/declaration_block.rs, line 447 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcWU-aqkhEaJjTSceg:-KdcWU-aqkhEaJjTSceh:be248eh) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L447)):*
> ```Rust
> {
>     match appendable_value {
>         // Should be able to use this enum to pass the already serialized css?
> ```

So `AppendableValue::Css` is currently used by `get_shorthand_appendable_value` to store value of shorthand with variable reference. I think it is fine to reuse it for appending serialized shorthand directly, but please change the comment to mention these two usages.

We probably need to distinguish between the two cases eventually, because shorthand with variable reference should actually be serialized with no whitespace after `:` in `append_serialization`. But that should be a separate issue.

---

*[components/style/properties/declaration_block.rs, line 489 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcXTy5M3Chs2D9BIYI:-KdcXTy6PCFpsK_YIfFj:b766jd7) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L489)):*
> ```Rust
>             }
>          },
>          &AppendableValue::DeclarationsForShorthand(..) => try!(write!(dest, " "))
> ```

It seems to me it is no longer possible to have `AppendableValue::DeclarationsForShorthand` anymore at this point. Probably consider making this branch `unreachable!()` with a comment that `DeclarationsForShorthand` should have been serialized to `Css` before calling this?

---

*[components/style/properties/properties.mako.rs, line 524 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcaHjBFkpm25B9_yz9:-KdcaHjC8TKFDJ6DN0XG:bv1d4qr) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/properties.mako.rs#L524)):*
> ```Rust
>     }
> 
>     /// Find an return an appendable value for the given declarations.
> ```

"Find**s** **and** return**s**".

---

*[components/style/properties/shorthand/box.mako.rs, line 300 at r2](https://reviewable.io:443/reviews/servo/servo/15685#-KdceOAPpAQDuQLcYMHV:-KdceOAPpAQDuQLcYMHW:b-b1o3u7) ([raw file](https://github.com/servo/servo/blob/9e30c43e2ff66abb79f1412cb3734decdf03847f/components/style/properties/shorthand/box.mako.rs#L300)):*
> ```Rust
>             % for name in "duration timing_function delay direction fill_mode iteration_count play_state name".split():
>                 let ${name} = if let DeclaredValue::Value(ref arr) = *self.animation_${name} {
>                     arr.0.get(i)
> ```

I think you can use `arr.0[i]` directly and make the other branch `unreachable!()` since the logic above should have ensured that you will get a value here. And then the None check below would be unnecessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15685)*

**Comment by upsuper** [comment]
The commits look fine overall. Thanks for working on this! I think I can r+ with the comments above addressed.

**Comment by absoludity** [comment]
Great, thanks @upsuper for the help. Details below.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/style/properties/declaration_block.rs, line 347 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcMt7b9UasX2GfLTiO:-KddgEk9g4eldP7N_8uh:b-896fix) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L347)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

`String::new()` is enough.
</blockquote></details>

Done.

---

*[components/style/properties/declaration_block.rs, line 352 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcU7TR9RiUQcva16Sr:-Kddgl5tLYdYy_U3cyen:boxp0jb) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L352)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

I don't quite get what did you mean here. And I guess it isn't a comment suitable to be put in code.
</blockquote></details>

Sorry, that was a note-to-self that I missed deleting.

---

*[components/style/properties/declaration_block.rs, line 358 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcMjqd7PVLHUDlVo-_:-Kddgow6qjm1IwzmpOec:b-896fix) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L358)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

`value.is_empty()` is probably better.
</blockquote></details>

Done.

---

*[components/style/properties/declaration_block.rs, line 363 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcSJTFfKvnGgpZETbq:-Kddg9YerIkUXqC3DdwX:b-snsl1j) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L363)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

I suspect whether we really need to specify types for the generic parameters... Could you try removing them?
</blockquote></details>

Yep, I was able to do s/&PropertyDeclaration/_/ , but that was all.

---

*[components/style/properties/declaration_block.rs, line 447 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcWU-aqkhEaJjTSceg:-KddhOQu9jRCCYGAOD2_:b-896fix) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L447)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

So `AppendableValue::Css` is currently used by `get_shorthand_appendable_value` to store value of shorthand with variable reference. I think it is fine to reuse it for appending serialized shorthand directly, but please change the comment to mention these two usages.

We probably need to distinguish between the two cases eventually, because shorthand with variable reference should actually be serialized with no whitespace after `:` in `append_serialization`. But that should be a separate issue.
</blockquote></details>

Done.

---

*[components/style/properties/declaration_block.rs, line 489 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcXTy5M3Chs2D9BIYI:-KddmA8NXHqEFOmJOjgi:bb6un1j) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/declaration_block.rs#L489)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

It seems to me it is no longer possible to have `AppendableValue::DeclarationsForShorthand` anymore at this point. Probably consider making this branch `unreachable!()` with a comment that `DeclarationsForShorthand` should have been serialized to `Css` before calling this?
</blockquote></details>

Done

---

*[components/style/properties/properties.mako.rs, line 524 at r1](https://reviewable.io:443/reviews/servo/servo/15685#-KdcaHjBFkpm25B9_yz9:-KddmV7yxWcDgzJcZbuJ:b-896fix) ([raw file](https://github.com/servo/servo/blob/1f88f9918ff80b2d620a10b6898aaf38854b5980/components/style/properties/properties.mako.rs#L524)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

"Find**s** **and** return**s**".
</blockquote></details>

Done.

---

*[components/style/properties/shorthand/box.mako.rs, line 300 at r2](https://reviewable.io:443/reviews/servo/servo/15685#-KdceOAPpAQDuQLcYMHV:-KdeAk80YnAYysnmnn1i:bpcvhge) ([raw file](https://github.com/servo/servo/blob/9e30c43e2ff66abb79f1412cb3734decdf03847f/components/style/properties/shorthand/box.mako.rs#L300)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

I think you can use `arr.0[i]` directly and make the other branch `unreachable!()` since the logic above should have ensured that you will get a value here. And then the None check below would be unnecessary.
</blockquote></details>

I made the other branch unreachable!(), but couldn't find a way to use arr.0[i] without getting:

```
59168 |                     arr.0[i]
      |                     ^^^^^^^^ cannot move out of indexed content
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15685#-:-Kddn7g2WVMfVXX8eRDM:b5r1leh)*

**Comment by upsuper** [comment]
Review status: 1 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[components/style/properties/shorthand/box.mako.rs, line 300 at r2](https://reviewable.io:443/reviews/servo/servo/15685#-KdceOAPpAQDuQLcYMHV:-Kdel-IdyA06vtIttaA5:bcsjsnd) ([raw file](https://github.com/servo/servo/blob/9e30c43e2ff66abb79f1412cb3734decdf03847f/components/style/properties/shorthand/box.mako.rs#L300)):*
<details><summary><i>Previously, absoludity (Michael Nelson) wrote…</i></summary><blockquote>

I made the other branch unreachable!(), but couldn't find a way to use arr.0[i] without getting:

```
59168 |                     arr.0[i]
      |                     ^^^^^^^^ cannot move out of indexed content
```
</blockquote></details>

Probably `&arr.0[i]`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15685)*

**Comment by absoludity** [comment]
Review status: 1 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[components/style/properties/shorthand/box.mako.rs, line 300 at r2](https://reviewable.io:443/reviews/servo/servo/15685#-KdceOAPpAQDuQLcYMHV:-KdgVv51B1cRWR2y0LYK:b-ccsftt) ([raw file](https://github.com/servo/servo/blob/9e30c43e2ff66abb79f1412cb3734decdf03847f/components/style/properties/shorthand/box.mako.rs#L300)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Probably `&arr.0[i]`?
</blockquote></details>

OK. Done that removed the now unnecessary `if let Some(${name}) = ${name} {`. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15685)*

**Comment by upsuper** [comment]
Review status: 1 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[components/style/properties/declaration_block.rs, line 446 at r4](https://reviewable.io:443/reviews/servo/servo/15685#-KdhbJmlKvSYuCofUrcv:-KdhbJmlKvSYuCofUrcw:blxdi6c) ([raw file](https://github.com/servo/servo/blob/bc0dfc60bdd6ed82176b9fbc1c88168506552eac/components/style/properties/declaration_block.rs#L446)):*
> ```Rust
> {
>     match appendable_value {
>         // Should be able to use this enum to pass the already serialized css?
> ```

Then I guess you should probably remove this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15685)*

**Comment by upsuper** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15685)*

**Comment by upsuper** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15685)*

**Comment by absoludity** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/style/properties/declaration_block.rs, line 446 at r4](https://reviewable.io:443/reviews/servo/servo/15685#-KdhbJmlKvSYuCofUrcv:-KdhdVfTVLx5OoVlWIbR:b-896fix) ([raw file](https://github.com/servo/servo/blob/bc0dfc60bdd6ed82176b9fbc1c88168506552eac/components/style/properties/declaration_block.rs#L446)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Then I guess you should probably remove this comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15685)*

**Comment by upsuper** [comment]
The failure doesn't look relevant.

@bors-servo retry

**Comment by upsuper** [comment]
@bors-servo retry

* #15718
* #15719

**Pull request merged**
