### PR TITLE
Don't load all font faces sources

### PR DESCRIPTION
**Pull request by nox**
We stop at the first one we manage to load.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11702)

### CODE REVIEW

**Comment by metajack** [comment]
r=me after answering the .rev() question

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/1505)
</details>


---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/font_face.rs, line 70 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11702#-KJvqBnOaaD65UujqNV3:-KJvqBnOaaD65UujqNV4:-618063388) ([raw file](https://github.com/servo/servo/blob/615f4aa24f401eef407d5703261517fe94962a5c/components/style/font_face.rs#L70)):*
> ```Rust
>     /// least "truetype" or "opentype".
>     pub fn effective_sources(&self) -> EffectiveSources {
>         EffectiveSources(self.sources.iter().rev().filter(|source| {
> ```

Why do we reverse the list here?x

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11702#-:-KJvqUrrZHtHZLJxYVMB:993717993)*

**Comment by nox** [comment]
-S-awaiting-review -S-tests-failed +S-needs-code-changes 

The unit tests fail.

<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> r=me after answering the .rev() question
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/font_face.rs, line 70 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11702#-KJvqBnOaaD65UujqNV3:-KJvqiMdHVwRD92gW4P0:862090691) ([raw file](https://github.com/servo/servo/blob/615f4aa24f401eef407d5703261517fe94962a5c/components/style/font_face.rs#L70)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> Why do we reverse the list here?x
</details>
We reverse the list because the only method on EffectiveSources is the `Iterator` implementation which just pops element from the inner vector. This lets us send less and less data on every `AddWebFont` loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11702#-:-KJvqtTz9sIKpdfSMKyf:-1370965595)*

**Comment by nox** [comment]
Fixed the unit tests and Jack ACK'd my answer on IRC.

@bors-servo r=metajack

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11702#-:-KJvrlKvnCdjPMOMxI0b:-896817307)*

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #11719

**Pull request merged**
