### PR TITLE
No need for paint layer in stacking context to be an arc.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6988)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@bors-servo r+

(I'd never dare to review such a change in unfamiliar code in C++. Yay Rust!)

**Comment by metajack** [comment]
@bors-servo retry

- infra issues

**Comment by metajack** [comment]
Merging by hand because it passed but homu was looking for linux3 build results.

**Pull request merged**
