### PR TITLE
Replace use of callbacks in webxr by channels

### PR DESCRIPTION
**Pull request by asajeffrey**
Use senders rather than callbacks in webxr.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because it's an internal change

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23848)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Depends on #23847 and https://github.com/servo/webxr/pull/29

**Review by Manishearth — APPROVED** [review]

**Comment by jdm** [comment]
```
./components/canvas/Cargo.toml:39: no newline at EOF
```

**Comment by asajeffrey** [comment]
Sigh, added a newline. @bors-servo r=Manishearth

**Comment by asajeffrey** [comment]
So #23777 really did a number on this PR. It's now back in a state that can be merged, though it does need a patched version of webxr (with https://github.com/servo/webxr/pull/33).

**Comment by asajeffrey** [comment]
@Manishearth, I think there are enough changes that it'd be nice if you or @jdm glanced over it again.

**Comment by CYBAI** [comment]
> bors-servo retry

Note that it's #23290 intermittent failure.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23220

**Pull request merged**
