### PR TITLE
Update mozjs 0.14.1

### LINKED ISSUE #27617: Update crate mozjs
The mozjs crate has had a few updates.

1. Unsafe Handle::new() is now private.
2. NewProxyObject accepts 6 input parameters instead of 4 (new fields: classp and singleton).
3. CompileOptionsWrapper accepts &str as std::ptr.

References: https://github.com/servo/rust-mozjs/issues/518, 
https://github.com/servo/rust-mozjs/issues/519
https://github.com/servo/rust-mozjs/pull/521

### PR DESCRIPTION
**Pull request by sudarshan-reddy**
This update pulls in improvements on mozjs that now removes the need to
pass pointers to CompileOptionsWraper::new(), allows NewProxyObject to
now accept a Singleton bool and JSClass and removes an unsafe
Handle::new usage.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #27617 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they are changes in parameters that existing tests cover.

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by sudarshan-reddy** [comment]
@jdm I see one macos build failing because of an ascii decode error but I'm unsure if the changes causes this.

**Comment by jdm** [comment]
No, that's https://github.com/servo/servo/issues/25233. The actual failure is https://community-tc.services.mozilla.com/tasks/bcTUkIDrT8Gj7BVkOH0g9w/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FbcTUkIDrT8Gj7BVkOH0g9w%2Fruns%2F0%2Fartifacts%2Fpublic%2Ffiltered-wpt-errorsummary.log, but that's https://github.com/servo/servo/issues/27342. I will retry the failed CI job.

**Comment by jdm** [comment]
@bors-servo retry
* #27342

**Pull request merged**
