### PR TITLE
Tweak gecko bindings

### PR DESCRIPTION
**Pull request by bholley**
A few changes as discussed.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10293)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo: r+

Glad to see the bindings working fine across platforms! :)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10293#-:-KE7zCQc6TSwvWjwWzp8:-1449140785)*

**Comment by bholley** [comment]
@bors-servo r-

There's another failures that only reproduces after rebasing:

gecko_style_structs.rs:1818:5: 1818:56 error: the trait `core::clone::Clone` is not implemented for the type `[i8; 39]` [E0277]
gecko_style_structs.rs:1818     pub mStringBytes: [::std::os::raw::c_char; 39usize],
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gecko_style_structs.rs:1816:16: 1816:21 note: in this expansion of #[derive_Clone] (defined in gecko_style_structs.rs)
gecko_style_structs.rs:1818:5: 1818:56 help: run `rustc --explain E0277` to see a detailed explanation
gecko_style_structs.rs:1818:5: 1818:56 help: the following implementations were found:
gecko_style_structs.rs:1818:5: 1818:56 help:   <[T; 0] as core::clone::Clone>
gecko_style_structs.rs:1818:5: 1818:56 help:   <[T; 1] as core::clone::Clone>
gecko_style_structs.rs:1818:5: 1818:56 help:   <[T; 2] as core::clone::Clone>
gecko_style_structs.rs:1818:5: 1818:56 help:   <[T; 3] as core::clone::Clone>
gecko_style_structs.rs:1818:5: 1818:56 help: and 29 others
gecko_style_structs.rs:1818:5: 1818:56 note: required by `core::clone::Clone::clone`

**Comment by bholley** [comment]
@emilio any idea what's going on with that failure?

**Pull request merged**
