### PR TITLE
Adding warning to properties.mako.rs regarding the Mako parser mangling

### PR DESCRIPTION
**Pull request by craftytrickster**
https://github.com/servo/servo/issues/9564#issuecomment-183765401

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9634)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+ rollup

Thanks!

**Comment by Manishearth** [comment]
@bors-servo retry

network/git issues

**Comment by Manishearth** [comment]
```
Cloning into '.'...
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
fatal: bad object c416b33345c2923f569f3f78604fbf512b85857e
error: wrong index v2 file size in /Users/servo/buildbot/slave/mac-dev-unit/build/.git/objects/pack/pack-2ae90a5428c30ca4ce86d2e16f73c6c5f54b66b5.idx
fatal: remote did not send all necessary objects
```

Looks like it needs an fsck.

**Comment by Manishearth** [comment]
@larsbergstrom It seems like the mac password has changed, could you run a `git fsck` on `servo-mac1` when you get the chance?

**Comment by larsbergstrom** [comment]
@Manishearth Directory is empty.

Also, the updated password is in the "seekrits" google doc. You should be able to ssh in as root@. There's been a bit of back-and-forth on the salt side about whether we should ssh in as root@ or administrator@ to the macs. After the next highstate, all macs should be administrator@ again.

**Comment by Manishearth** [comment]
@bors retry

Nah, it needed an fsck in the git dir for that builder.

root@ fixed it. I don't think I have access to seekrits though. Thanks!

**Comment by KiChjang** [comment]
@Manishearth THIS. IS. SERVO!!!!!!

@bors-servo retry

**Comment by jdm** [comment]
@bors-servo: retry
* #9488 #7791

**Comment by KiChjang** [comment]
@bors-servo retry
* #9033, #9092

**Pull request merged**
