### PR TITLE
Add `rust-media` as a dependency of script, in preparation for audio and video tag support

### PR DESCRIPTION
**Pull request by pcwalton**
This does not actually use the library; it's just here to prevent
bitrotting.

r? @metajack @glennw

### CODE REVIEW

**Comment by jdm** [comment]
This is missing changes from the other Cargo.lock files, but otherwise looks totally fine to me.

**Comment by pcwalton** [comment]
Issue addressed. r? @metajack

**Comment by jdm** [comment]
```
Unable to update https://github.com/pcwalton/rust-media#8a428094
```

**Comment by jdm** [comment]
No real point in keeping this open; it's super simple to redo from scratch.

**Pull request closed without merging**
