### PR TITLE
Refactor more stuff in preparation for special handling for restyling using the style attribute

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15288)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0271]: type mismatch resolving `<std::vec::IntoIter<(style::rule_tree::StyleSource, style::properties::Importance)> as std::iter::Iterator>::Item == (style::rule_tree::StyleSource, style::rule_tree::CascadeLevel)`
  --> /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/style/rule_tree/bench.rs:65:15
   |
65 |     rule_tree.insert_ordered_rules(rules.into_iter())
   |               ^^^^^^^^^^^^^^^^^^^^ expected enum `style::properties::Importance`, found enum `style::rule_tree::CascadeLevel`
   |
   = note: expected type `(style::rule_tree::StyleSource, style::properties::Importance)`
              found type `(style::rule_tree::StyleSource, style::rule_tree::CascadeLevel)`

error[E0061]: this function takes 3 parameters but 1 parameter was supplied
   --> /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/style/stylist.rs:116:29
    |
116 |     map.get_universal_rules(&mut decls);
    |                             ^^^^^^^^^^ expected 3 parameters
```

**Comment by emilio** [comment]
Whoops, forgot to run unit tests.

@bors-servo try

**Comment by emilio** [comment]
Now it should be ready.

@bors-servo try

**Comment by SimonSapin** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/script/dom/cssstyledeclaration.rs, line 60 at r4](https://reviewable.io:443/reviews/servo/servo/15288#-KbkGc6exCOYSG8R-Ejc:-KbkGc6fi0Mhbejtg8-w:b-xcv3ln) ([raw file](https://github.com/servo/servo/blob/0ae787cdd09eff7241ef95388e50164338f0e951/components/script/dom/cssstyledeclaration.rs#L60)):*
> ```Rust
>                 //
>                 // TODO(emilio): This is not clear (no pun intended) by the HTML
>                 // spec, see: https://github.com/whatwg/html/issues/2306
> ```

https://github.com/whatwg/html/issues/2306 is closed now. It looks like we shouldn’t clear (which simplifies this code a bit).

---

*[components/script/dom/document.rs, line 2152 at r3](https://reviewable.io:443/reviews/servo/servo/15288#-KbkFEZP2tsGAGxh06Mt:-KbkFEZQoBimPgqlHIim:bqr75w8) ([raw file](https://github.com/servo/servo/blob/7811a8627da0c4d45813f99bfa18c35780b75ea6/components/script/dom/document.rs#L2152)):*
> ```Rust
> 
>     pub fn element_attr_will_change(&self, el: &Element, attr: &Attr) {
>         // FIXME(emilio): Kind of a shame we have to duplicate this.
> ```

Maybe change `ensure_snapshot` to return `entry`, so that only `entry.snapshot.as_mut().unwrap()` will be duplicated? (Tough it’ll be duplicated in two places.)

Alternatively, now that `ensure_snapshot` only has one caller, maybe inline it?

---

*[components/style/attr.rs, line 49 at r4](https://reviewable.io:443/reviews/servo/servo/15288#-KbkIUX1dO0nGRh8S2Lc:-KbkIUX1dO0nGRh8S2Ld:b-8j6yeg) ([raw file](https://github.com/servo/servo/blob/0ae787cdd09eff7241ef95388e50164338f0e951/components/style/attr.rs#L49)):*
> ```Rust
>     Dimension(String, LengthOrPercentageOrAuto),
>     Url(String, Option<ServoUrl>),
>     Declaration(String,
> ```

If I understand correctly, unlike other variants, this variant is only used transiently (in `attribute_mutated`) and never kept in `Element::attrs`. It’s probably worth a comment.

---

*[components/style/data.rs, line 206 at r8](https://reviewable.io:443/reviews/servo/servo/15288#-KbkPcGerFl6-i7gOaSv:-KbkPcGfPVLcWcjIICRn:b4ereio) ([raw file](https://github.com/servo/servo/blob/f30bdd3e1e2a1aec22416da799d79b91f5cd4e0d/components/style/data.rs#L206)):*
> ```Rust
>         debug_assert!(!hint.contains(RESTYLE_LATER_SIBLINGS), "Caller should apply sibling hints");
>         StoredRestyleHint {
>             restyle_self: hint.contains(RESTYLE_SELF) || hint.contains(RESTYLE_STYLE_ATTRIBUTE),
> ```

Re commit message: why is this temporary? Should that be a code comment or an issue rather than just a commit message?

---

*[components/style/stylist.rs, line 219 at r5](https://reviewable.io:443/reviews/servo/servo/15288#-KbkLdUHBddnsPWLpNGH:-KbkLdUHBddnsPWLpNGI:bllzesh) ([raw file](https://github.com/servo/servo/blob/e84b88b5f078218865fd27e91a6d2d1dfbcca472/components/style/stylist.rs#L219)):*
> ```Rust
>                 map.user_agent.get_universal_rules(&mut declarations,
>                                                    CascadeLevel::UserNormal,
>                                                    CascadeLevel::UserImportant);
> ```

s/`User`/`UA`/ ?

---

*[components/style/stylist.rs, line 530 at r5](https://reviewable.io:443/reviews/servo/servo/15288#-KbkKGSWH_clXg4_b4dU:-KbkKGSXZW5S4vUkLYMb:bmk49o3) ([raw file](https://github.com/servo/servo/blob/e84b88b5f078218865fd27e91a6d2d1dfbcca472/components/style/stylist.rs#L530)):*
> ```Rust
> 
>         // Step 2: Presentational hints.
>         let length = applicable_declarations.len();
> ```

Nit: while you’re at it, please rename this `length` variable to something like `length_before_preshints`.

---

*[components/style/stylist.rs, line 534 at r5](https://reviewable.io:443/reviews/servo/servo/15288#-KbkJahhquO6wqnpoXDT:-KbkJahhquO6wqnpoXDU:b-t16txg) ([raw file](https://github.com/servo/servo/blob/e84b88b5f078218865fd27e91a6d2d1dfbcca472/components/style/stylist.rs#L534)):*
> ```Rust
>         if applicable_declarations.len() != length {
>             if cfg!(debug_assertions) {
>                 for i in length..applicable_declarations.len() {
> ```

Why not `for d in applicatble_declarations[length..]` ?

---

*[components/style/rule_tree/mod.rs, line 180 at r5](https://reviewable.io:443/reviews/servo/servo/15288#-KbkLye-_Kafdzsh-iXS:-KbkLye0LAudeIjuYdSE:bnzbgar) ([raw file](https://github.com/servo/servo/blob/e84b88b5f078218865fd27e91a6d2d1dfbcca472/components/style/rule_tree/mod.rs#L180)):*
> ```Rust
> 
> /// The cascade level these rules are relevant at.
> #[repr(u8)]
> ```

Do you use this `repr(u8)` to cast a `CascadeLevel` to `u8` somewhere? If so please add a comment saying:

The order of variants declared here is significant, and must be in *ascending* order of precedence. Note that https://drafts.csswg.org/css-cascade/#cascade-origin specifies in *descending* order of precedence.

---

*[tests/wpt/mozilla/tests/mozilla/style_remove_prop.html, line 11 at r7](https://reviewable.io:443/reviews/servo/servo/15288#-KbkP7GzReiYhgT2tuh8:-KbkP7H0Hhi7e_aIomiL:bb01uw2) ([raw file](https://github.com/servo/servo/blob/237d68a0ac8f08d17475defcd63ffec968be7df7/tests/wpt/mozilla/tests/mozilla/style_remove_prop.html#L11)):*
> ```HTML
>   var div = document.querySelector('div');
>   div.style.color = "";
>   assert_true(!div.hasAttribute('style') || div.getAttribute('style') === '');
> ```

https://github.com/whatwg/html/issues/2306 is resolved, this change should be removed (reverted).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15288)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/script/dom/cssstyledeclaration.rs, line 60 at r4](https://reviewable.io:443/reviews/servo/servo/15288#-KbkGc6exCOYSG8R-Ejc:-KbkbfqC9HRB-4cmkefk:b-7tyfeh) ([raw file](https://github.com/servo/servo/blob/0ae787cdd09eff7241ef95388e50164338f0e951/components/script/dom/cssstyledeclaration.rs#L60)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

https://github.com/whatwg/html/issues/2306 is closed now. It looks like we shouldn’t clear (which simplifies this code a bit).
</blockquote></details>

Right, I'll add a comment on the code.

---

*[components/script/dom/document.rs, line 2152 at r3](https://reviewable.io:443/reviews/servo/servo/15288#-KbkFEZP2tsGAGxh06Mt:-KbkafRS1RUQnPKQRHg8:bdy3sm) ([raw file](https://github.com/servo/servo/blob/7811a8627da0c4d45813f99bfa18c35780b75ea6/components/script/dom/document.rs#L2152)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Maybe change `ensure_snapshot` to return `entry`, so that only `entry.snapshot.as_mut().unwrap()` will be duplicated? (Tough it’ll be duplicated in two places.)

Alternatively, now that `ensure_snapshot` only has one caller, maybe inline it?
</blockquote></details>

Yup, I'll inline it. I'll probably try to get rid of all this PendingRestyle table eventually, it's quite dumb ATM.

---

*[components/style/attr.rs, line 49 at r4](https://reviewable.io:443/reviews/servo/servo/15288#-KbkIUX1dO0nGRh8S2Lc:-Kbkao_m0S7Pprh4p7sH:bku6qpn) ([raw file](https://github.com/servo/servo/blob/0ae787cdd09eff7241ef95388e50164338f0e951/components/style/attr.rs#L49)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

If I understand correctly, unlike other variants, this variant is only used transiently (in `attribute_mutated`) and never kept in `Element::attrs`. It’s probably worth a comment.
</blockquote></details>

Right, commented.

---

*[components/style/data.rs, line 206 at r8](https://reviewable.io:443/reviews/servo/servo/15288#-KbkPcGerFl6-i7gOaSv:-KbkaqCPpabzjjYPi2Op:bhhdwod) ([raw file](https://github.com/servo/servo/blob/f30bdd3e1e2a1aec22416da799d79b91f5cd4e0d/components/style/data.rs#L206)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Re commit message: why is this temporary? Should that be a code comment or an issue rather than just a commit message?
</blockquote></details>

It's temporary because the whole purpose of these changes is optimizing this, but right now we still need to run selector matching to get the correct styling results.

---

*[components/style/stylist.rs, line 219 at r5](https://reviewable.io:443/reviews/servo/servo/15288#-KbkLdUHBddnsPWLpNGH:-KbkaU0FQplNJtmU6MFb:b-xiszjd) ([raw file](https://github.com/servo/servo/blob/e84b88b5f078218865fd27e91a6d2d1dfbcca472/components/style/stylist.rs#L219)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

s/`User`/`UA`/ ?
</blockquote></details>

Good catch :). Not that it mattered specially in this case though.

---

*[components/style/stylist.rs, line 530 at r5](https://reviewable.io:443/reviews/servo/servo/15288#-KbkKGSWH_clXg4_b4dU:-KbkayXT0IDoNgg5WrKd:bb6un1j) ([raw file](https://github.com/servo/servo/blob/e84b88b5f078218865fd27e91a6d2d1dfbcca472/components/style/stylist.rs#L530)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Nit: while you’re at it, please rename this `length` variable to something like `length_before_preshints`.
</blockquote></details>

Done

---

*[components/style/stylist.rs, line 534 at r5](https://reviewable.io:443/reviews/servo/servo/15288#-KbkJahhquO6wqnpoXDT:-KbkazYEWK5o5Nfhuw4b:b8t6q9s) ([raw file](https://github.com/servo/servo/blob/e84b88b5f078218865fd27e91a6d2d1dfbcca472/components/style/stylist.rs#L534)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Why not `for d in applicatble_declarations[length..]` ?
</blockquote></details>

Whoops, much nicer :)

---

*[components/style/rule_tree/mod.rs, line 180 at r5](https://reviewable.io:443/reviews/servo/servo/15288#-KbkLye-_Kafdzsh-iXS:-KbkbBPUmKzfoec4z4hr:bfuscv8) ([raw file](https://github.com/servo/servo/blob/e84b88b5f078218865fd27e91a6d2d1dfbcca472/components/style/rule_tree/mod.rs#L180)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Do you use this `repr(u8)` to cast a `CascadeLevel` to `u8` somewhere? If so please add a comment saying:

The order of variants declared here is significant, and must be in *ascending* order of precedence. Note that https://drafts.csswg.org/css-cascade/#cascade-origin specifies in *descending* order of precedence.
</blockquote></details>

I plan to use it to replace rules in the rule tree, but until that happens it's not used.

I added that comment :)

---

*[tests/wpt/mozilla/tests/mozilla/style_remove_prop.html, line 11 at r7](https://reviewable.io:443/reviews/servo/servo/15288#-KbkP7GzReiYhgT2tuh8:-KbkbNgBkyZA_9lx1C1-:b-896fix) ([raw file](https://github.com/servo/servo/blob/237d68a0ac8f08d17475defcd63ffec968be7df7/tests/wpt/mozilla/tests/mozilla/style_remove_prop.html#L11)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

https://github.com/whatwg/html/issues/2306 is resolved, this change should be removed (reverted).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15288)*

**Comment by SimonSapin** [comment]
r=me with one last change

---

Reviewed 1 of 3 files at r10, 1 of 1 files at r11, 3 of 4 files at r12, 5 of 6 files at r13, 1 of 1 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/rule_tree/mod.rs, line 180 at r5](https://reviewable.io:443/reviews/servo/servo/15288#-KbkLye-_Kafdzsh-iXS:-Kbl3hl7phqngH-Dryem:b-pwliw8) ([raw file](https://github.com/servo/servo/blob/e84b88b5f078218865fd27e91a6d2d1dfbcca472/components/style/rule_tree/mod.rs#L180)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

I plan to use it to replace rules in the rule tree, but until that happens it's not used.

I added that comment :)
</blockquote></details>

Please also include the spec link as above in the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15288#-:-Kbl43LHa8096Gvk5Jha:b-ze6kma)*

**Comment by emilio** [comment]
@bors-servo r=SimonSapin

Thanks for the review Simon :)

**Pull request merged**
