### PR TITLE
Implement <font> 'face' attribute

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7619)

### CODE REVIEW

**Comment by nox** [comment]
```
./components/script/dom/element.rs:65: use statement is not in alphabetical order
	expected: style::properties::longhands::font_family
	found: style::properties::longhands::{self, background_image, border_spacing}
./components/script/dom/element.rs:66: use statement is not in alphabetical order
	expected: style::properties::longhands::{self, background_image, border_spacing}
	found: style::properties::longhands::font_family
```

**Comment by frewsxcv** [comment]
Ah, thanks. Missed that

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1, 7 of 8 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/element.rs, line 66 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzAhDHJYRlturfBwf9v)** ([raw file](https://github.com/servo/servo/blob/a47a12f6ff09338dca50533641cb100275230b7d/components/script/dom/element.rs#L66)):</sup>
Just do only one import from longhands to keep tidy happy.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 26 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzAhqRBWXpfdSLPJnkO)** ([raw file](https://github.com/servo/servo/blob/a47a12f6ff09338dca50533641cb100275230b7d/components/script/dom/htmlfontelement.rs#L26)):</sup>
`DOMRefCell<Option<DOMString>>` would be better here, IMO.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzAhIsB8HBxmAcLykz8)** ([raw file](https://github.com/servo/servo/blob/a47a12f6ff09338dca50533641cb100275230b7d/components/script/dom/htmlfontelement.rs#L86)):</sup>
Should do `value.as_string().clone()`, there is no reason this attribute should be something else than `AttrValue::String`.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 108 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzAhnrslfm9gQ2jccAI)** ([raw file](https://github.com/servo/servo/blob/a47a12f6ff09338dca50533641cb100275230b7d/components/script/dom/htmlfontelement.rs#L108)):</sup>
Store the string only if non-empty.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by nox** [comment]
Reviewed 1 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzAhIsB8HBxmAcLykz8)** ([raw file](https://github.com/servo/servo/blob/a47a12f6ff09338dca50533641cb100275230b7d/components/script/dom/htmlfontelement.rs#L86)):</sup>
There is no `as_string` method on `AttrValue`. Should I add one?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzAhIsB8HBxmAcLykz8)** ([raw file](https://github.com/servo/servo/blob/a47a12f6ff09338dca50533641cb100275230b7d/components/script/dom/htmlfontelement.rs#L86)):</sup>
Yes. I guess there are none because you can just Deref to &str, but I would rather have it panic if it's not a string. These things aren't supposed to change their variant after they are set for the first time.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by frewsxcv** [comment]
How do those changes look?

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by nox** [comment]
-S-awaiting-review -S-fails-tidy +S-needs-code-changes 

One last remark.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzD-kDey4uwngNmPAIc)** ([raw file](https://github.com/servo/servo/blob/7b8f6cedb99046a24cf15567ade2c1f10489f49b/components/script/dom/htmlfontelement.rs#L86)):</sup>
No need for the deref here, AFAICT.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzD-kDey4uwngNmPAIc)** ([raw file](https://github.com/servo/servo/blob/7b8f6cedb99046a24cf15567ade2c1f10489f49b/components/script/dom/htmlfontelement.rs#L86)):</sup>
You are right. Fixed in the latest force push

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzD2JATveZ8V6Cb4EeN)** ([raw file](https://github.com/servo/servo/blob/600753e15e28431b9f159d790c94a01b9cd79396/components/script/dom/htmlfontelement.rs#L86)):</sup>
Mmmh, actually, I'm sorry, I didn't notice the attribute value was ultimately converted to an Atom when pushing the presentational hint. Could you implement the virtual method `parse_plain_attribute()`, make that return an `AttrValue::Atom` for the font attribute, and then clone that atom into the `face` field here? If you need more information on how to do this, feel free to ask me questions; and if you don't, that can also be filed as a follow-up.

Sorry for not noticing this earlier.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzD2JATveZ8V6Cb4EeN)** ([raw file](https://github.com/servo/servo/blob/600753e15e28431b9f159d790c94a01b9cd79396/components/script/dom/htmlfontelement.rs#L86)):</sup>
> Sorry for not noticing this earlier.

No reason to be sorry :)

Yeah, I think I understand all of that. I'm on a train right now and my laptop is about to die, but I'll try to get to it tonight

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzD2JATveZ8V6Cb4EeN)** ([raw file](https://github.com/servo/servo/blob/600753e15e28431b9f159d790c94a01b9cd79396/components/script/dom/htmlfontelement.rs#L86)):</sup>
Cool!

I'll have a thought for your laptop. Poor laptop. RIP.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzD2JATveZ8V6Cb4EeN)** ([raw file](https://github.com/servo/servo/blob/600753e15e28431b9f159d790c94a01b9cd79396/components/script/dom/htmlfontelement.rs#L86)):</sup>
Should the `face` field on the HTMLFontElement struct continue to be a String or should it be changed to an Atom?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 86 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7619#-JzD2JATveZ8V6Cb4EeN)** ([raw file](https://github.com/servo/servo/blob/600753e15e28431b9f159d790c94a01b9cd79396/components/script/dom/htmlfontelement.rs#L86)):</sup>
Atom too.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7619)

**Comment by nox** [comment]
@bors-servo retry

#7422

**Pull request merged**
