### PR TITLE
Moved ScriptToCompositorMsg enum and EventResult enum to script_traits

### PR DESCRIPTION
**Pull request by kimumetal**
Moved ScriptToCompositorMsg enum and EventResult enum to script_traits
resolving issue #8835.
(Need to be checked)
Variants in ScriptToCompositorMsg enum and EventResult enum had no doc
comment. I found some with grep command and copied it, and others I
wrote some doc comments manually to pass the build system. It needs to
be checked whether the doc comment is proper or not.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8912)

### CODE REVIEW

**Comment by KiChjang** [comment]
@vwvww Is something wrong?

**Comment by vwvww** [comment]
@KiChjang I was trying to pass the test-tidy test, but working on the problem, my github branch screwed up... I thought I could try from another branch but it seems to be wrong.

**Comment by KiChjang** [comment]
As a tip, you can run test-tidy locally. Simply run `./mach test-tidy` on your machine, and it'll work as intended.

**Comment by vwvww** [comment]
@KiChjang ,Thank you for your comment! That was also a problem, but the biggest was merging problem and I think I cannot handle it.
I am willing to not reopen this pull request, and rather make a new branch and a new pull request for the issue. Is it okay to leave this pull request closed?

**Comment by KiChjang** [comment]
Yes it is totally fine. I just wanted to know if there's anything we can do to help you contribute!

**Pull request closed without merging**
