### PR TITLE
Run our reftests with wptrunner rev3

### PR DESCRIPTION
**Pull request by initsecret**
moved tests from ref to wpt, to enable use of wptrunner.
#5618

Thanks,

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6914)

### CODE REVIEW

**Comment by Manishearth** [comment]
This looks good to me. Might want to squash all of the "added link" commits?

@Ms2ger have any thoughts?

**Comment by s142857** [comment]
ill have to do it

**Comment by jdm** [comment]
@s142857 Have you run the `--manifest-update` command and run the tests to make sure they pass?

**Comment by s142857** [comment]
nope, i will do it

**Comment by s142857** [comment]
no new erros cuz of me

**Comment by s142857** [comment]
i ran it

**Comment by s142857** [comment]
come on, why does it need to be squashed

**Comment by s142857** [comment]
could you squash it into a 100 bits or atleast 50

**Comment by jdm** [comment]
@s142857 I don't see any MANIFEST.json changes included in this PR. Could you commit them and push them, please? They should have appeared automatically when running `--manifest-update`.

**Comment by s142857** [comment]
im really sorry

**Comment by jdm** [comment]
Hmm, something's wrong. There should be many more additions to that file due to all of the new tests being moved...

**Comment by s142857** [comment]
i ran only 15 tests

**Comment by s142857** [comment]
./mach test-wpt --include _mozilla/css --manifest-update
ran only 15 tests

**Comment by jdm** [comment]
Oh, I see one problem - the `<link>` syntax is incorrect. `<link rel=match href"filter_sepia_ref.html">` is missing a "=" between the href attribute and value.

@s142857 I'm really sorry, but can I suggest that we go about this is an easier way? Let's start from scratch and just move one test, then make sure it's running and everything else is correct. Then we can work on others, rather than iterating on all 250 tests each time.

**Comment by jdm** [comment]
I would really like to see a new PR with just the changes for one test. It will be much easier to make sure everything is correct in that case.

**Pull request closed without merging**
