### PR TITLE
Embedding rebase rage

### PR DESCRIPTION
**Pull request by zmike**
This updates all the CEF interface stuff to the current CEF codebase.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5955)

### CODE REVIEW

**Comment by zmike** [comment]
@larsbergstrom

**Comment by larsbergstrom** [comment]
Reviewed files:
- ports/cef/cookie.rs @ r4
- ports/cef/interfaces/cef_app.rs @ r1
- ports/cef/interfaces/cef_auth_callback.rs @ r1
- ports/cef/interfaces/cef_browser.rs @ r1
- ports/cef/interfaces/cef_browser_process_handler.rs @ r1
- ports/cef/interfaces/cef_callback.rs @ r1
- ports/cef/interfaces/cef_client.rs @ r1
- ports/cef/interfaces/cef_command_line.rs @ r1
- ports/cef/interfaces/cef_context_menu_handler.rs @ r1
- ports/cef/interfaces/cef_cookie.rs @ r1
- ports/cef/interfaces/cef_dialog_handler.rs @ r1
- ports/cef/interfaces/cef_display_handler.rs @ r1
- ports/cef/interfaces/cef_dom.rs @ r1
- ports/cef/interfaces/cef_download_handler.rs @ r1
- ports/cef/interfaces/cef_download_item.rs @ r1
- ports/cef/interfaces/cef_drag_data.rs @ r1
- ports/cef/interfaces/cef_drag_handler.rs @ r1
- ports/cef/interfaces/cef_find_handler.rs @ r1
- ports/cef/interfaces/cef_focus_handler.rs @ r1
- ports/cef/interfaces/cef_frame.rs @ r1
- ports/cef/interfaces/cef_geolocation.rs @ r1
- ports/cef/interfaces/cef_geolocation_handler.rs @ r1
- ports/cef/interfaces/cef_jsdialog_handler.rs @ r1
- ports/cef/interfaces/cef_keyboard_handler.rs @ r1
- ports/cef/interfaces/cef_life_span_handler.rs @ r1
- ports/cef/interfaces/cef_load_handler.rs @ r1
- ports/cef/interfaces/cef_menu_model.rs @ r1
- ports/cef/interfaces/cef_navigation_entry.rs @ r1
- ports/cef/interfaces/cef_origin_whitelist.rs @ r1
- ports/cef/interfaces/cef_parser.rs @ r1
- ports/cef/interfaces/cef_path_util.rs @ r1
- ports/cef/interfaces/cef_print_handler.rs @ r1
- ports/cef/interfaces/cef_print_settings.rs @ r1
- ports/cef/interfaces/cef_process_message.rs @ r1
- ports/cef/interfaces/cef_process_util.rs @ r1
- ports/cef/interfaces/cef_render_handler.rs @ r1
- ports/cef/interfaces/cef_render_process_handler.rs @ r1
- ports/cef/interfaces/cef_request.rs @ r1
- ports/cef/interfaces/cef_request_context.rs @ r1
- ports/cef/interfaces/cef_request_context_handler.rs @ r1
- ports/cef/interfaces/cef_request_handler.rs @ r1
- ports/cef/interfaces/cef_resource_bundle_handler.rs @ r1
- ports/cef/interfaces/cef_resource_handler.rs @ r1
- ports/cef/interfaces/cef_response.rs @ r1
- ports/cef/interfaces/cef_scheme.rs @ r1
- ports/cef/interfaces/cef_ssl_info.rs @ r1
- ports/cef/interfaces/cef_stream.rs @ r1
- ports/cef/interfaces/cef_string_visitor.rs @ r1
- ports/cef/interfaces/cef_task.rs @ r1
- ports/cef/interfaces/cef_trace.rs @ r1
- ports/cef/interfaces/cef_urlrequest.rs @ r1
- ports/cef/interfaces/cef_v8.rs @ r1
- ports/cef/interfaces/cef_values.rs @ r1
- ports/cef/interfaces/cef_web_plugin.rs @ r1
- ports/cef/interfaces/cef_xml_reader.rs @ r1
- ports/cef/interfaces/cef_zip_reader.rs @ r1
- ports/cef/interfaces/mod.rs @ r1
- ports/cef/regen_interface_mod_rs.sh @ r6
- ports/cef/request_context.rs @ r4
- ports/cef/types.rs @ r3
- ports/cef/urlrequest.rs @ r4
- ports/cef/values.rs @ r4
- ports/cef/window.rs @ r5
- ports/cef/wrappers.rs @ r1

---

<sup>**[ports/cef/interfaces/cef_browser.rs, line 784 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodOLc_3qwWngt4QS4q)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_browser.rs#L784)):</sup>
nit: trailing space on line

---

<sup>**[ports/cef/interfaces/cef_browser.rs, line 813 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodOeuzuuBmEPyCo2hZ)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_browser.rs#L813)):</sup>
This no longer works (objects are not zero'd at drop, but are filled in if you use the filling_drop feature with a special value) and needs to instead be similar to the code at:
https://github.com/servo/servo/blob/master/components/layout/flow_ref.rs#L185-L188

Also will need:
#![feature(unsafe_no_drop_flag, filling_drop)]

---

<sup>**[ports/cef/interfaces/cef_browser.rs, line 828 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodPRRsrAmrv-wgPLfF)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_browser.rs#L828)):</sup>
Similar

---

<sup>**[ports/cef/interfaces/cef_browser.rs, line 842 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodPWDkEnvZC1DUqGDP)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_browser.rs#L842)):</sup>
Similar

---

<sup>**[ports/cef/interfaces/cef_browser.rs, line 850 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodPdr_YpAwt1r_6UNf)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_browser.rs#L850)):</sup>
Similar

---

<sup>**[ports/cef/interfaces/cef_browser.rs, line 853 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodPeZqTiEkmtio-BUR)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_browser.rs#L853)):</sup>
Similar

---

<sup>**[ports/cef/interfaces/cef_cookie.rs, line 644 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodQU87B6Uh67RljcVH)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_cookie.rs#L644)):</sup>
Similar, throughout this file, on the need to use filling_drop if you want to be able to check if an object has already been dropped.

---

<sup>**[ports/cef/interfaces/cef_download_handler.rs, line 213 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodQoSJPxLr7V7PTBPo)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_download_handler.rs#L213)):</sup>
nit: Is this a `()` that has been split across two lines? Can it not be split like that?

---

<sup>**[ports/cef/interfaces/cef_download_handler.rs, line 219 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodQwsRsq1kjZMiDlE6)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_download_handler.rs#L219)):</sup>
nit: similar

---

<sup>**[ports/cef/interfaces/cef_find_handler.rs, line 81 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodR9yZXYnsxruCjGaf)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_find_handler.rs#L81)):</sup>
nit: I hate myself, but I'm going to bring up that space-at-end-of-line thing again :-)

---

<sup>**[ports/cef/interfaces/cef_find_handler.rs, line 110 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodRGUhNDAW3vJYK7t6)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/cef_find_handler.rs#L110)):</sup>
Similar: filling_drop stuff.

---

<sup>**[ports/cef/interfaces/mod.rs, line 1 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodSSNhSochGDDM5AC8)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/interfaces/mod.rs#L1)):</sup>
Lost the MPL copyright header.

---

<sup>**[ports/cef/regen_interface_mod_rs.sh, line 1 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5955#-JodSZYot9l3_U_xzZLS)** ([raw file](https://github.com/servo/servo/blob/ad91db7224bf5d3cb016e51ab9959ce0fb7a0a43/ports/cef/regen_interface_mod_rs.sh#L1)):</sup>
Needs a copyright header

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5955)

**Comment by larsbergstrom** [comment]
Mostly looks good! The biggest issue to resolve is whether the change from zeroing to filling drop is going to require changes in the code.

**Comment by zmike** [comment]
All comments addressed except for ')' character on next line; this is how cef outputs functions from the translator and I'm not going to rewrite their line wrapping code just to fix this.

**Comment by larsbergstrom** [comment]
Reviewed files:
- ports/cef/interfaces/cef_app.rs @ r9
- ports/cef/interfaces/cef_auth_callback.rs @ r9
- ports/cef/interfaces/cef_browser.rs @ r9
- ports/cef/interfaces/cef_browser_process_handler.rs @ r9
- ports/cef/interfaces/cef_callback.rs @ r9
- ports/cef/interfaces/cef_client.rs @ r9
- ports/cef/interfaces/cef_command_line.rs @ r9
- ports/cef/interfaces/cef_context_menu_handler.rs @ r9
- ports/cef/interfaces/cef_cookie.rs @ r9
- ports/cef/interfaces/cef_dialog_handler.rs @ r9
- ports/cef/interfaces/cef_display_handler.rs @ r9
- ports/cef/interfaces/cef_dom.rs @ r9
- ports/cef/interfaces/cef_download_handler.rs @ r9
- ports/cef/interfaces/cef_download_item.rs @ r9
- ports/cef/interfaces/cef_drag_data.rs @ r9
- ports/cef/interfaces/cef_drag_handler.rs @ r9
- ports/cef/interfaces/cef_find_handler.rs @ r9
- ports/cef/interfaces/cef_focus_handler.rs @ r9
- ports/cef/interfaces/cef_frame.rs @ r9
- ports/cef/interfaces/cef_geolocation.rs @ r9
- ports/cef/interfaces/cef_geolocation_handler.rs @ r9
- ports/cef/interfaces/cef_jsdialog_handler.rs @ r9
- ports/cef/interfaces/cef_keyboard_handler.rs @ r9
- ports/cef/interfaces/cef_life_span_handler.rs @ r9
- ports/cef/interfaces/cef_load_handler.rs @ r9
- ports/cef/interfaces/cef_menu_model.rs @ r9
- ports/cef/interfaces/cef_navigation_entry.rs @ r9
- ports/cef/interfaces/cef_origin_whitelist.rs @ r9
- ports/cef/interfaces/cef_parser.rs @ r9
- ports/cef/interfaces/cef_path_util.rs @ r9
- ports/cef/interfaces/cef_print_handler.rs @ r9
- ports/cef/interfaces/cef_print_settings.rs @ r9
- ports/cef/interfaces/cef_process_message.rs @ r9
- ports/cef/interfaces/cef_process_util.rs @ r9
- ports/cef/interfaces/cef_render_handler.rs @ r9
- ports/cef/interfaces/cef_render_process_handler.rs @ r9
- ports/cef/interfaces/cef_request.rs @ r9
- ports/cef/interfaces/cef_request_context.rs @ r9
- ports/cef/interfaces/cef_request_context_handler.rs @ r9
- ports/cef/interfaces/cef_request_handler.rs @ r9
- ports/cef/interfaces/cef_resource_bundle_handler.rs @ r9
- ports/cef/interfaces/cef_resource_handler.rs @ r9
- ports/cef/interfaces/cef_response.rs @ r9
- ports/cef/interfaces/cef_scheme.rs @ r9
- ports/cef/interfaces/cef_ssl_info.rs @ r9
- ports/cef/interfaces/cef_stream.rs @ r9
- ports/cef/interfaces/cef_string_visitor.rs @ r9
- ports/cef/interfaces/cef_task.rs @ r9
- ports/cef/interfaces/cef_trace.rs @ r9
- ports/cef/interfaces/cef_url.rs @ r10
- ports/cef/interfaces/cef_urlrequest.rs @ r9
- ports/cef/interfaces/cef_v8.rs @ r9
- ports/cef/interfaces/cef_values.rs @ r9
- ports/cef/interfaces/cef_web_plugin.rs @ r9
- ports/cef/interfaces/cef_xml_reader.rs @ r9
- ports/cef/interfaces/cef_zip_reader.rs @ r10
- ports/cef/interfaces/mod.rs @ r10
- ports/cef/lib.rs @ r9
- ports/cef/macros.rs @ r9
- ports/cef/README.md @ r11
- ports/cef/regen_interface_mod_rs.sh @ r7
- ports/cef/request_context.rs @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5955)

**Pull request merged**
