### PR TITLE
Run unit tests on appveyor

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10238)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/unit/net/cookie.rs, line 113 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10238#-KDxk6QoA8ogLeQ8-bfr:-KDxk6QoA8ogLeQ8-bfs:11990611) ([raw file](https://github.com/servo/servo/blob/6f42363689e7698610c9c27e734233dfa9a0c580/tests/unit/net/cookie.rs#L113)):*
Can we put this stuff in functions that are in a `cfg` marking them as Windows-only? I worry about adding sleep calls to other platforms and people cargo-culting the sleep into future cookie tests without knowing why they were added.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10238)*

**Comment by jdm** [comment]
This is ready for review. All tests passed on the last appveyor run.

**Comment by larsbergstrom** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10238)*

**Pull request merged**
