### PR TITLE
Update WR (dual-source subpixel text optimizations, clip-out segment builder).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19614)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone

**Review by emilio — APPROVED** [review]

**Comment by glennw** [comment]
There is a new box shadow pass, but also a new failure in ```transform_3d_from_outside_viewport.html```. @mrobinson any ideas on what may have caused that? Otherwise I'll try to narrow it down today.

**Comment by glennw** [comment]
re-r? @jdm or @emilio

**Comment by jdm** [comment]
@bors-servo retry
* #19495

**Pull request merged**
