### PR TITLE
Invalidate node style after style property removed

### LINKED ISSUE #9377: Resetting style property via elt.style.xxx doesn't work
Here is an example. The `div` should turn transparent. It doesn't.

```html
<div style="width:200px;height:200px;border:2px solid red;background:blue"></div>

<script>

  setTimeout(() => {
    document.querySelector("div").style.background = "";
  }, 1000);

</script>
```

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #9377

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9378)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r-

I'm pretty sure this is the wrong fix. You should make CSSStyleDeclaration change the `style` attribute of the element, and then `Element::attribute_mutated` will call `Document::content_changed` for you.

**Comment by paulrouget** [comment]
> I'm pretty sure this is the wrong fix. You should make CSSStyleDeclaration change the style attribute of the element, and then Element::attribute_mutated will call Document::content_changed for you.

I just reproduced what `setProperty` and `setPropertyPriority` do.

`Element::remove_inline_style_property` and `Element::update_inline_style` apparently don't trigger `attribute_mutated`. Because of #9307 I guess.

**Comment by nox** [comment]
`setProperty` and `setPropertyPriority` look wrong to me too.

**Comment by paulrouget** [comment]
> setProperty and setPropertyPriority look wrong to me too.

Right. I'm expecting PR #9307 to remove all the calls to `content_changed`.

**Comment by paulrouget** [comment]
@nox, do you mind if we land this while waiting for PR #9410?

This is breaking browser.html HTML pretty badly, and `RemoveProperty` will eventually be fixed along `setProperty` and `setPropertyPriority` in PR #9410.

**Comment by KiChjang** [comment]
@bors-servo r+

@nox please don't hurt me.

**Comment by KiChjang** [comment]
```
Ran 9335 tests finished in 1138.0 seconds.
  • 9333 ran as expected. 55 tests skipped.
  • 2 tests passed unexpectedly

Tests with unexpected results:
  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/perspective-containing-block-dynamic-1a.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-containing-block-dynamic-1a.htm
```
wat

**Comment by KiChjang** [comment]
Oh ok, the test failures aren't intermittents - it's a new pass after the changes made in this PR. @paulrouget you'll have to update the test expectations.

**Comment by nox** [comment]
@paulrouget @KiChjang Sounds reasonable. :)

**Pull request merged**
