### PR TITLE
Move Epoch to gfx_traits

### LINKED ISSUE #9222: Move Epoch type to gfx_traits
It's defined in msg but used in a bunch of places that all depend on gfx_traits, and it's a gfx-related concept.

Code: `components/msg/compositor_msg.rs`, `components/gfx_traits/lib.rs`

### PR DESCRIPTION
**Pull request by Aesthetikx**
Resolves #9222. Moved Epoch from components/msg/compositor_msg to
components/gfx_traits/lib. Updated use statements to reflect the move.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9230)

### CODE REVIEW

**Comment by KiChjang** [comment]
Please try not to work on issues without first claiming them. We don't want duplication of efforts among developers.

**Comment by Aesthetikx** [comment]
Sorry about that, I'll make sure to claim next time.

**Comment by jdm** [comment]
Thanks for doing this!

**Comment by jdm** [comment]
@bors-servo: r-
Unfortunately this doesn't pass `./mach test-tidy` yet:
```
./components/compositing/constellation.rs:26: use statement is not in alphabetical order

	expected: gfx_traits::PaintMsg as FromPaintMsg

	found: gfx_traits::Epoch

./components/gfx/paint_task.rs:18: Line is longer than 120 characters
```

**Comment by Aesthetikx** [comment]
Indeed, I'll get that sorted out.

**Comment by KiChjang** [comment]
@bors-servo retry
* #9163

**Pull request merged**
