### PR TITLE
Copy updated WR shaders.

### PR DESCRIPTION
**Pull request by glennw**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12832)

### CODE REVIEW

**Comment by glennw** [comment]
@nox @larsbergstrom This needs to land after https://github.com/servo/servo/pull/12828 (see https://github.com/servo/servo/pull/12828#issuecomment-239538128)

**Comment by larsbergstrom** [comment]
r=me after that lands.

**Pull request merged**
