### PR TITLE
Fix ./mach run on Windows

### PR DESCRIPTION
**Pull request by adamncasey**
This branch also includes the commit being reviewed in https://github.com/servo/servo/pull/9408 . Is it OK to just wait for that one to merge, or should I separate them?

This patch adds the BIN_SUFFIX to the servo executable name when doing ./mach run. 

However just doing this caused subprocess to error due to some unicode symbols in PATH.

To fix this, I pulled a peice of code from mozilla-central which fixes this problem there. Source: https://dxr.mozilla.org/mozilla-central/source/python/mach/mach/mixin/process.py#108

Revisiting this now (originally developed this a few weeks ago), perhaps we should be using https://github.com/servo/servo/blob/master/python/mach/mach/mixin/process.py instead of subprocess to give us all of this crossplatform process execution support. I think that should be a nice to have though - this patch at least gets a necessary development command working on windows.

Tested on Windows and Ubuntu.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9415)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@adamncasey We can close #9408 and I'll just review and test this one as a whole, if that works for you.

Thanks for all your work on Windows - I really appreciate it!

**Comment by larsbergstrom** [comment]
Hrm, when I run with `./mach run http://www.lars.com`, I get "Servo exited with return value 127". `target/debug/servo http://www.lars.com` works, though.

Also, on the first commit, I think we would need to install virtualenv for the mingw64 python in order for this to work.

**Comment by larsbergstrom** [comment]
Aha, I've managed to get this working locally - user error on my part. I'll also land the other python-related fix because it works with the current instructions.

I suspect what's needed to make the "mingw64 python" work is installing virtualenv/easy_install for mingw64.

@bors-servo r+

**Comment by adamncasey** [comment]
Looks like a reftest failed. Is this a known intermittent failure?

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #9033

**Pull request merged**
