### PR TITLE
Remove tidy blacklist for 'script/dom/bindings/*'

### PR DESCRIPTION
**Pull request by frewsxcv**
Recently, I found myself reading through the Python codegen scripts that
live in 'components/script/dom/bindings/*' and noticed that there were
many tidy violations: unnecessary semicolons, weird spacing, unused
variables, lack of license headers, etc. Considering these files are now
living in our tree and mostly maintained directly by contributors of
Servo (as opposed to being from upstream), I feel these files should not
be excluded from our normal tidy process. This commit removes the
blacklist on these files and fixes all tidy violations.

I added these subdirectories to the blacklist because they appear to be
maintained upstream somewhere else:
- "components/script/dom/bindings/codegen/parser/*",
- "components/script/dom/bindings/codegen/ply/*",

Also, I added a few '# noqa' comments which tells us to ignore the
flake8 errors for that line; they are mostly for unused/undefined
variables. I chose to ignore these (instead of fixing them) to make the
work for this commit simpler for me.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6580)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Most of the code you're touching is old imported code from Gecko; I'd much rather remove it than make stylistic changes. (They are so out of date by now that they're pretty much useless, IMO.) @jdm didn't want to remove them last time I suggested it, though, but maybe he's changed his mind by now. 

CC @michaelwu @Manishearth as well

**Comment by michaelwu** [comment]
I didn't find the old imported code useful when I was doing the smup. It's probably even less useful now with a modern spidermonkey. *.h, *.cpp, and Codegen.py can probably all be removed. If someone finds them useful though, leaving them in doesn't bother me either.

**Comment by jdm** [comment]
I agree with everyone else.

**Comment by frewsxcv** [comment]
Removing unused files: :+1: :smile_cat:  :+1: 

Opened a new PR that removes the files mentioned above: #6581

**Comment by frewsxcv** [comment]
#6581 has merged; just rebased this off master

**Pull request merged**
