### PR TITLE
add etc/shell.nix for nix/nixOS and instructions - fixes #10468

### LINKED ISSUE #10468: Build on NixOS
I am trying to build Servo on NixOS, with Nix version 1.11.2. I installed the following packages — `bzip2, cmake, freeglut, freetype, glib, gperf, mesa, which, xorg.libX11, xorg.libXcursor, xorg.xrandr` — although these might not be all dependencies. Anyway, 

```
Error running mach:

    ['build', '--dev']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory

  File "/home/sindikat/progs/servo/python/servo/build_commands.py", line 235, in build
    env=env, cwd=self.servo_crate(), verbose=verbose)
  File "./python/servo/command_base.py", line 69, in call
    return subprocess.call(*args, shell=sys.platform == 'win32', **kwargs)
  File "/nix/store/awbf3jh262m1k16hxgbgngdmxv66gd79-python-2.7.11/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/nix/store/awbf3jh262m1k16hxgbgngdmxv66gd79-python-2.7.11/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/nix/store/awbf3jh262m1k16hxgbgngdmxv66gd79-python-2.7.11/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
```

I have no idea, how to continue from that.

### PR DESCRIPTION
**Pull request by mkg20001**
This adds instructions for building servo on nixOS and the required shell.nix to prepare the environment

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [x] These changes fix #10468 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they relate to adding a new build environment, not any servo code

### CODE REVIEW

**Comment by est31** [comment]
@petabyteboy is it okay if this shell.nix [based on your shell.nix](https://github.com/servo/servo/issues/10468#issuecomment-643855330) is merged into servo which is MPL 2.0 licensed?

**Comment by petabyteboy** [comment]
Sure! Mine was based on others as well, but I doubt there is still significant portions after our changes.

**Comment by est31** [comment]
I've tried out this PR locally, and got the following error:

```
 --- stderr
  /nix/store/v53g549ji2vhsywqrfr63w9f5d275i1a-clang-wrapper-7.1.0/bin/as: invalid option -- 'N'
  make[4]: *** [/home/user/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/de147f0/mozjs/config/rules.mk:671: icu_data.o] Fehler 1
  make[3]: *** [/home/user/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/de147f0/mozjs/config/recurse.mk:72: config/external/icu/data/target-objects] Fehler 2
  make[3]: *** Es wird auf noch nicht beendete Prozesse gewartet....
  make[2]: *** [/home/user/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/de147f0/mozjs/config/recurse.mk:34: compile] Fehler 2
  make[1]: *** [/home/user/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/de147f0/mozjs/config/rules.mk:355: default] Fehler 2
  make: *** [/home/user/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/de147f0/makefile.cargo:183: all] Fehler 2
  thread 'main' panicked at 'assertion failed: result.success()', /home/user/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/de147f0/build.rs:172:5
```

Any ideas?

**Comment by petabyteboy** [comment]
I think we should figure out why the `--pure` thing is failing, as this might lead to inconsistencies between systems. Also, we should pin a nixpkgs commit in the shell file.

**Comment by mkg20001** [comment]
@petabyteboy In my particular case rustup was failing to download some things. I'm not sure what could have caused this.

@est31 I also got this error. I assumed it was working fine since it almost finished build.

**Comment by mkg20001** [comment]
@est31 Fixed the error, AS=as was causing the problem (was using gcc linker instead of clang)

Note: You need to clear out the failed build using `rm -rf target/release/build/mozjs*`. After that rebuild should work

**Comment by mkg20001** [comment]
Now build works

Getting this when running target/release/servo
```
Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" }) (thread main, at /home/maciej/.cargo/git/checkouts/winit-c2fdb27092aba5a7/4192d04/src/platform_impl/linux/mod.rs:611)
```

Servo doesn't seem to directly link against this library. Not sure if LD_LIBRARY_PATH should be used here or if something about linking should be changed...

**Comment by est31** [comment]
@mkg20001 excerpt from a private shell.nix of mine that I use for rust graphics application development:

```nix
  APPEND_LIBRARY_PATH = with pkgs; stdenv.lib.makeLibraryPath [
    vulkan-loader
    xlibs.libXcursor
    xlibs.libXi
    xlibs.libXrandr
    xlibs.libX11
    xlibs.libXi
    xlibs.libXxf86vm
    libGL
    mesa
  ];
  shellHook = ''
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$APPEND_LIBRARY_PATH";
  '';
```
Maybe parts of that can be integrated into this shell.nix?

**Comment by mkg20001** [comment]
@est31 I took some parts of this and added it to shell.nix. I only added the libraries that were missing, seems like the other ones are linked against. Otherwise feel free to comment if you get an error.

**Review by est31 — APPROVED** [review]
@mkg20001 I've tried out this version and could successfully compile & run it. :+1: from me!

**Pull request merged**
