### PR TITLE
Unbust stylo

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16774)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo p=1

 * stylo build is red

**Comment by emilio** [comment]
cc @fitzgen

**Comment by emilio** [comment]
@bors-servo r=Manishearth

 * Missed one that wasn't compiled with test-stylo, shrug

**Comment by upsuper** [comment]
I don't quite understand the change to sugar `nsCOMPtr`. Why do we need an extra unused type parameter for `raw` method?

**Comment by emilio** [comment]
So we can call them the same way from release and debug builds. Removing NSCAP_FEATURE_USE_BASE (https://bugzilla.mozilla.org/show_bug.cgi?id=1363754) would prevent this, though.

**Pull request merged**
