### PR TITLE
Ak 18468

### LINKED ISSUE #18468: assertion failed: RUST_JSID_IS_STRING(id)
Found on 101xp.com, 100% reproducible (currently reducing a testcase).

```gdb
assertion failed: RUST_JSID_IS_STRING(id) (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /shared/dev/rust/servo/components/script/dom/bindings/conversions.rs:144)
stack backtrace:
   0:     0x558367ec92e4 - backtrace::backtrace::libunwind::trace
                        at /shared/dev/rust/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /shared/dev/rust/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x558367ec386f - backtrace::capture::{{impl}}::new
                        at /shared/dev/rust/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x5583635f6ccc - servo::main::{{closure}}
                        at /shared/dev/rust/servo/ports/servo/main.rs:130
   3:     0x55836a8dd316 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:612
   4:     0x5583660282d6 - std::panicking::begin_panic<&str>
                        at /checkout/src/libstd/panicking.rs:572
   5:     0x558365a98a21 - script::dom::bindings::conversions::string_jsid_to_string
                        at /shared/dev/rust/servo/components/script/dom/bindings/conversions.rs:144
   6:     0x558367ad5808 - script::dom::bindings::codegen::Bindings::StorageBinding::StorageBinding::delete::{{closure}}
                        at /shared/dev/rust/servo/target/debug/build/script-d00ee28330b6ecd4/out/Bindings/StorageBinding.rs:990
   7:     0x55836763163f - core::ops::function::FnOnce::call_once<closure,()>
                        at /checkout/src/libcore/ops/function.rs:223
   8:     0x5583672d4e75 - std::panic::{{impl}}::call_once<bool,closure>
                        at /checkout/src/libstd/panic.rs:296
   9:     0x5583661c0d94 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,bool>
                        at /checkout/src/libstd/panicking.rs:480
  10:     0x55836a8e43bc - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  11:     0x558366106bd5 - std::panicking::try<bool,std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:459
  12:     0x558367504749 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,bool>
                        at /checkout/src/libstd/panic.rs:361
  13:     0x5583673ab292 - js::panic::wrap_panic<std::panic::AssertUnwindSafe<closure>,bool>
                        at /shared/dev/rust/servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/panic.rs:22
  14:     0x55836724056f - script::dom::bindings::codegen::Bindings::StorageBinding::StorageBinding::delete
                        at /shared/dev/rust/servo/target/debug/build/script-d00ee28330b6ecd4/out/Bindings/StorageBinding.rs:989
  15:     0x558368111d29 - _ZNK22ForwardingProxyHandler7delete_EP9JSContextN2JS6HandleIP8JSObjectEENS3_I4jsidEERNS2_14ObjectOpResultE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/3de4ff3/src/jsglue.cpp:410
  16:     0x55836866a4a7 - _ZN2js5Proxy7delete_EP9JSContextN2JS6HandleIP8JSObjectEENS4_I4jsidEERNS3_14ObjectOpResultE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/proxy/Proxy.cpp:160
  17:     0x55836866c6ea - _ZN2js20proxy_DeletePropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_I4jsidEERNS2_14ObjectOpResultE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/proxy/Proxy.cpp:602
  18:     0x5583684fc972 - _ZN2js14DeletePropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_I4jsidEERNS2_14ObjectOpResultE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsobjinlines.h:225
  19:     0x558368766aff - Interpret
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2502
  20:     0x55836875c055 - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  21:     0x55836875c4a2 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:471
  22:     0x55836875c6fa - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  23:     0x55836875c78c - _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
  24:     0x55836856e384 - _ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:1325
  25:     0x55836878df7b - _ZN2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  26:     0x55836875c3d3 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  27:     0x55836875c6fa - InternalCall
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:498
  28:     0x55836875c724 - _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
  29:     0x55836814b880 - DoCallFallback
                        at /shared/dev/rust/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jit/BaselineIC.cpp:5970
  30:     0x7f6fa993fe23 - <unknown>
ERROR:servo: assertion failed: RUST_JSID_IS_STRING(id)
Pipeline failed in hard-fail mode.  Crashing!
```

### PR DESCRIPTION
**Pull request by toidiu**
**WIP**

We panic in function `string_jsid_to_string`  if HandleId is not a string. This PR attempts to fix this by testing if the id is not a string prior to calling the function.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #18468 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18546)

### CODE REVIEW

**Comment by toidiu** [comment]
@jdm  three things:
- I couldn't use match because then I was having problems with scope created by the match block.
- Currently this doesnt actually fix the issue!! I have a few println statements that show the data that is causing the error(posted below).
- I think a better way to check is to simply call `if !RUST_JSID_IS_STRING(id)` since thats where the assertion fails. I am going to make a PR to show this and wondering if there is anything wrong with this approach.

```
jsid_to_string(cx, id).is_none() is true for all of these cases.

**GOOD SCENARIO**
Some(DOMString("hasAttribute", PhantomData))
Some(DOMString("jQuery2130307340275337905872", PhantomData))
**BAD SCENARIO**
Some(DOMString("0", PhantomData))

```

**Comment by toidiu** [comment]
commit 7ccd2c7 uses `RUST_JSID_IS_STRING` of the if condition and fixes the panic. 

We still cant successfully load `http://101xp.com`, servo just seems to hang. However, I dont think that is within the scope of this issue so I am going to proceed with this fix and write tests for this.

**Comment by KiChjang** [comment]
I believe #18543 solves the same issue as well.

**Comment by toidiu** [comment]
@KiChjang so currently the in the upstream change we will panic with an `except`. Do we instead want to `return false`? Let me know if this issue is still valid or if it can be closed.

**Comment by emilio** [comment]
@toidiu we can't return false because it'll stop the execution of the script. Instead we need to figure out from where is it arriving with a non-string JSID, and see what the correct behavior should be.

We can do it on this bug, let me know if you need any help, happy to try helping :)

**Comment by emilio** [comment]
In particular, this comes from `CGDOMJSProxyHandler_delete`.

This should implement the following: https://heycam.github.io/webidl/#legacy-platform-object-delete

So there seems to be some stuff missing. In particular:

 * Indexed properties check (you can skip this from this PR and just leave a FIXME).
 * A `STRING` / `INT` check before calling `CGProxyNamedDeleter(self.descriptor).define()`. This is what causes the crash.

**Comment by emilio** [comment]
Also, this of course needs a test-case.

**Comment by emilio** [comment]
So, here's a test-case, and now I'm no longer sure adding that is the correct fix.

In particular, looks to me that we should just be handling atoms JSIDs...

```html
<script>
  delete window.localStorage[Symbol()];
</script>
```

**Comment by toidiu** [comment]
Sry my productivity drops during the week because of my job but I am keeping an eye on this.

**Comment by KiChjang** [comment]
@tobbi Merge commits are not accepted. Please rebase against master instead.

**Comment by toidiu** [comment]
@emilio I can't get the latest servo to crash anymore.. 

`RUST_BACKTRACE=1; ./mach run http://101xp.com` doesnt crash. Dont know what I am fixing at this point.

**Comment by emilio** [comment]
Doesn't running the test-case above (a file `test.html`, with the content I pasted) cause the crash?

**Comment by KiChjang** [comment]
@toidiu Have you tried solving the test case that @emilio has commented?

**Comment by wafflespeanut** [comment]
Closing due to inactivity.

**Pull request closed without merging**
