### PR TITLE
Implemented webdriver SetWindowSize.

### LINKED ISSUE #10467: Add a web driver test for resizing a web page

### PR DESCRIPTION
**Pull request by asajeffrey**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #10467 (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because the new tests are in https://github.com/w3c/web-platform-tests/pull/3024

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11179)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Must remember to update #8623 if/when this merges.

**Comment by jgraham** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/webdriver_handlers.rs, line 302 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11179#-KHtVaoKK0RlfhFKNFQt:-KHtVaoLbsrxyIHcVnYo:-35766315) ([raw file](https://github.com/servo/servo/blob/a0743210e3144832b1aa3c038f8937da72d8ffd4/components/script/webdriver_handlers.rs#L302)):*
> ```Rust
>     let untyped = size.to_untyped();
>     // TODO: when window puts in security checks for resize, we will need to rewrite this
>     window.ResizeTo(untyped.width as i32, untyped.height as i32);
> ```

This is async; I think the webdriver spec currently expects the resize to be synchronous.

---

*[components/webdriver_server/lib.rs, line 375 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11179#-KHtVAzqq3mnEbZzMAsK:-KHtVAzr1WdKSuyKcFaj:2059137365) ([raw file](https://github.com/servo/servo/blob/a0743210e3144832b1aa3c038f8937da72d8ffd4/components/webdriver_server/lib.rs#L375)):*
> ```Rust
>     fn handle_set_window_size(&self, params: &WindowSizeParameters) -> WebDriverResult<WebDriverResponse> {
>         let (sender, receiver) = ipc::channel().unwrap();
>         let size = Size2D::from_untyped(&Size2D::new(params.width as f32, params.height as f32));
> ```

What happens if the size is greater than the size of the screen?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11179)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/webdriver_handlers.rs, line 302 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11179#-KHtVaoKK0RlfhFKNFQt:-KHuW4cPATkawpyQd_uc:2018908478) ([raw file](https://github.com/servo/servo/blob/a0743210e3144832b1aa3c038f8937da72d8ffd4/components/script/webdriver_handlers.rs#L302)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> This is async; I think the webdriver spec currently expects the resize to be synchronous.</details>
Hmm, true. This is going to be a bit painful to implement, as resizing in the compositor is async. How wedded is the spec to synchronous resize?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11179)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/webdriver_handlers.rs, line 302 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11179#-KHtVaoKK0RlfhFKNFQt:-KHuZ72uMnDp3oFlm9QY:14144071) ([raw file](https://github.com/servo/servo/blob/a0743210e3144832b1aa3c038f8937da72d8ffd4/components/script/webdriver_handlers.rs#L302)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Hmm, true. This is going to be a bit painful to implement, as resizing in the compositor is async. How wedded is the spec to synchronous resize?</details>
Well, it wold be nice, but I guess I can argue that on some platforms it might not be possible to implement in a sync way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11179)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/webdriver_handlers.rs, line 302 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11179#-KHtVaoKK0RlfhFKNFQt:-KHuZiCol9DP7ZL8wyBY:41558544) ([raw file](https://github.com/servo/servo/blob/a0743210e3144832b1aa3c038f8937da72d8ffd4/components/script/webdriver_handlers.rs#L302)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Well, it wold be nice, but I guess I can argue that on some platforms it might not be possible to implement in a sync way.</details>
So how to proceed? I can reimplement this as sync, but it's going to be quite a bit of rewiring, which I'd rather not do if we think we're going to rewrite the spec.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11179)*

**Comment by asajeffrey** [comment]
I made SetWindowSize wait for a resize event before responding.

**Comment by asajeffrey** [comment]
Added a timeout to SetWindowSize.

**Comment by asajeffrey** [comment]
Rebased.

**Comment by jgraham** [comment]
Reviewed 3 of 8 files at r4, 2 of 6 files at r5, 3 of 4 files at r6.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/webdriver_server/lib.rs, line 226 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11179#-KIDLltz8FHlVsZaHHq4:-KIDLlu-sEHTt6XIWLUN:-1724916146) ([raw file](https://github.com/servo/servo/blob/0737990ea8b09374321de18e060f30b9433d845c/components/webdriver_server/lib.rs#L226)):*
> ```Rust
>             script_timeout: 30_000,
>             load_timeout: 300_000,
>             resize_timeout: 30_000,
> ```

I think this should be much smaller like a few hundred ms?

---

*[components/webdriver_server/lib.rs, line 368 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11179#-KIDQ_hSLQotjYo30ANZ:-KIDQ_hTvUXJ6lCHMdIX:-647198917) ([raw file](https://github.com/servo/servo/blob/0737990ea8b09374321de18e060f30b9433d845c/components/webdriver_server/lib.rs#L368)):*
> ```Rust
> 
>         let window_size = receiver.recv().unwrap();
>         let vp = window_size.visible_viewport;
> ```

I think this is wrong per spec, as it is supposed to include the window border &c. I am not particularly worried about that at this time (I am also not sure that the spec is really right here).

---

*[components/webdriver_server/lib.rs, line 393 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11179#-KIDVRA_KH0ZbEDWh5UC:-KIDVRA_KH0ZbEDWh5UD:734152393) ([raw file](https://github.com/servo/servo/blob/0737990ea8b09374321de18e060f30b9433d845c/components/webdriver_server/lib.rs#L393)):*
> ```Rust
>                 Ok(WebDriverResponse::WindowSize(window_size_response))
>             },
>             None => Err(WebDriverError::new(ErrorStatus::Timeout, "Resize timed out")),
> ```

I think in this case we should return the current window size.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11179)*

**Comment by asajeffrey** [comment]
Rebased and fixed.

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :umbrella: The latest upstream changes (presumably #11274) made this pull request unmergeable. Please resolve the merge conflicts.
</details>


---

Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/webdriver_server/lib.rs, line 226 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11179#-KIDLltz8FHlVsZaHHq4:-KIDYKXf3NI9PSRFi8eZ:-153203398) ([raw file](https://github.com/servo/servo/blob/0737990ea8b09374321de18e060f30b9433d845c/components/webdriver_server/lib.rs#L226)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I think this should be much smaller like a few hundred ms?
</details>
Changed it to 500.

---

*[components/webdriver_server/lib.rs, line 393 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11179#-KIDVRA_KH0ZbEDWh5UC:-KIDa19om2StiudACN20:-499146009) ([raw file](https://github.com/servo/servo/blob/0737990ea8b09374321de18e060f30b9433d845c/components/webdriver_server/lib.rs#L393)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I think in this case we should return the current window size.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11179#-:-KIDcGm9h827SD-vGOF4:-2040099256)*

**Comment by jgraham** [comment]
Reviewed 1 of 6 files at r8, 1 of 4 files at r9, 5 of 5 files at r10.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11179)*

**Comment by jgraham** [comment]
Reviewed 1 of 6 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11179)*

**Comment by asajeffrey** [comment]
Oops, this should have been squashed before merging.

**Comment by jgraham** [comment]
Ah, sorry :(

**Comment by asajeffrey** [comment]
No biggie.

**Pull request merged**
