### PR TITLE
Rebase and rustup of brson's cleanup work

### PR DESCRIPTION
**Pull request by larsbergstrom**
All of the commits by brson have been reviewed. Just the android fixups and Rustup one (which also cleans up some of the duplication due to a complete rewrite of code that had been moved in the original PR).

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5489)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Replaces https://github.com/servo/servo/pull/5026

**Comment by larsbergstrom** [comment]
@Ms2ger can you please reply to replies on the critic issues you opened?

**Comment by metajack** [comment]
Ready for squash!

**Pull request merged**
