### PR TITLE
convert match to if let for location header check #7969

### PR DESCRIPTION
**Pull request by creativcoder**
@jdm Hi, very eager for my first pull request to Servo. Please review the changes.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7973)

### CODE REVIEW

**Comment by jdm** [comment]
Looking good! Just a couple stylistic changes required, and an opportunity to improve the code a little more!
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[components/net/http_loader.rs, line 639 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7973#-K0MPuZEOHr-d10d4tyI)** ([raw file](https://github.com/servo/servo/blob/2c69d6aacdf6bef01366038f19eba3c3a908ca7a/components/net/http_loader.rs#L639)):</sup>
Everything inside this `if let` block should be unindented by four spaces.


---

<sup>**[components/net/http_loader.rs, line 641 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7973#-K0MQ0GH51L3fwHyOc5c)** ([raw file](https://github.com/servo/servo/blob/2c69d6aacdf6bef01366038f19eba3c3a908ca7a/components/net/http_loader.rs#L641)):</sup>
Want to make this an `if let` as well?


---

<sup>**[components/net/http_loader.rs, line 682 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7973#-K0MQ2I1SLTeFYNWz6Cr)** ([raw file](https://github.com/servo/servo/blob/2c69d6aacdf6bef01366038f19eba3c3a908ca7a/components/net/http_loader.rs#L682)):</sup>
nit: these trailing spaces are reported as an error by `./mach test-tidy`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7973)

**Comment by creativcoder** [comment]
Hi, made a commit after making the 3 changes you asked for. Please review.

**Comment by jdm** [comment]
Great! Please [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) these commits into one and then they're good to merge :)
-S-awaiting-review +S-needs-squash 


---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7973)

**Comment by creativcoder** [comment]
Hi, the two commits have been squashed into one.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Pull request merged**
