### PR TITLE
Put the docs task into its own builder until it learns to behave

### PR DESCRIPTION
**Pull request by Manishearth**
The latest rust update regressed rustdoc performance on servo a lot (6min to 37min), and now the tidy+unit+docs builder keeps timing out.

This splits out the doc task into its own thing until we can fix this.

r? @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22954)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r=jdm

forgot to actually create the task

https://treeherder.allizom.org/#/jobs?repo=servo-auto&selectedJob=230850047

**Comment by SimonSapin** [comment]
I think this is the right call here (to avoid increasing the total cycle time) but raising the timeout is also an option:

https://github.com/servo/servo/blob/de3d2f74951bf0c0834dfda8837d934b3e88aff2/etc/taskcluster/decision_task.py#L538

**Pull request merged**
