### PR TITLE
chore: upgrade the Rust toolchain to `nightly-2022-10-13`

### PR DESCRIPTION
**Pull request by yvt**
---
- [x] `./mach build -d` does not report any errors (prerequisite: #29009)
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

---
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they are not functional changes

### CODE REVIEW

**Comment by yvt** [comment]
<https://github.com/servo/servo/actions/runs/3254764130/jobs/5343384416#step:5:957>:

```
failures:

---- size_of::test_size_of_selector_parse_error stdout ----
error: test failed, to rerun pass `-p style_tests --lib`
thread 'size_of::test_size_of_selector_parse_error' panicked at 'Your changes have decreased the stack size of SelectorParseError from 56 to 48. Good work! Please update the expected size in tests/unit/style/size_of.rs.', tests/unit/style/size_of.rs:41:1
...

---- size_of::test_size_of_style_traits_parse_error stdout ----
thread 'size_of::test_size_of_style_traits_parse_error' panicked at 'Your changes have decreased the stack size of ::style_traits::ParseError from 72 to 64. Good work! Please update the expected size in tests/unit/style/size_of.rs.', tests/unit/style/size_of.rs:42:1
...

---- size_of::test_size_of_value_parse_error stdout ----
thread 'size_of::test_size_of_value_parse_error' panicked at 'Your changes have decreased the stack size of ::style_traits::ValueParseError from 56 to 48. Good work! Please update the expected size in tests/unit/style/size_of.rs.', tests/unit/style/size_of.rs:47:1
...
```

<https://github.com/yvt/servo/actions/runs/3254752996/jobs/5343621043>: A large number of tests are failing by timeout.

**Comment by yvt** [comment]
> https://github.com/yvt/servo/actions/runs/3254752996/jobs/5343621043: A large number of tests are failing by timeouts.

The timeouts are caused by an expired WPT certificate (last updated by #28700).

**Comment by yvt** [comment]
> The timeouts are caused by an expired WPT certificate (last updated by #28700).

Opened <https://github.com/servo/servo/pull/29015>.

**Review by jdm — APPROVED** [review]
Thank you! This looks ready to merge as soon as we update the media dependency.

**Pull request merged**
