### PR TITLE
Add support for 'font-stretch' in geckolib

### PR DESCRIPTION
**Pull request by ghost**
---

- [x] `./mach build-geckolib` does not report any errors
- [x] `./mach test-tidy` does not report any errors

r? @Manishearth

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13570)

### CODE REVIEW

**Comment by Manishearth** [comment]
r=me if screenshots work

(fwiw screenshots don't count as tests 😄, the PR text is talking about automated tests. For stylo it's okay to not have tests since many of the reftests fail due to unrelated reasons)

**Comment by Manishearth** [comment]
Try push @ https://treeherder.mozilla.org/#/jobs?repo=try&revision=265ad818cd8640a9e29e261709462a429744291e

**Comment by Wafflespeanut** [comment]
@Manishearth Yeah, but we don't have any other tests :smile:

**Comment by Wafflespeanut** [comment]
screenshot

@bors-servo r=Manishearth

**Comment by Manishearth** [comment]
@bors-servo retry
 - filing

**Pull request merged**
