### PR TITLE
Generalize layout to operate on arbitrary DOMs

### PR DESCRIPTION
**Pull request by bholley**
This gets us to where we need to be in order to write a Gecko implementation of the layout wrapper and have things Just Work.

Note that this is somewhat more than we need for just running the style system. But there wasn't a clean place to cut, and I thought it was a good idea to just do a complete job on it now, which may save us effort and mismatches in the long run.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8669)

### CODE REVIEW

**Comment by bholley** [comment]
Addressed all the comments thus far, I think.

I re-did the first patch to use UFCS for note_restyle_hint instead of hoisting it into the impl, since I realized the issue was caused by a compiler bug, and that I need the method to be in the trait to avoid duplicating it in the Gecko impl.

**Comment by pcwalton** [comment]
This looks OK other than those couple of things

**Comment by bholley** [comment]
rust-up did indeed fix the UFCS issue. \o/

Addressed everything else. @pcwalton r?

**Pull request merged**
