### PR TITLE
 Use active uniforms data to implement gl.uniform* checks

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21184)

### CODE REVIEW

**Review by jdm — DISMISSED** [review]
This looks good, but there's also a lot of duplication of checks. It would be good to file a followup issue to figure out way to reduce the duplication, similar to https://searchfox.org/mozilla-central/source/dom/canvas/WebGLContextGL.cpp#1964-2061.

**Comment by jdm** [comment]
```
error: unused import: `WebGLResult`
 --> components/script/dom/webgluniformlocation.rs:6:44
  |
6 | use canvas_traits::webgl::{WebGLProgramId, WebGLResult};
  |                                            ^^^^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`
error: aborting due to previous error
error: Could not compile `script`.
```

**Comment by nox** [comment]
I reduced the duplication a tad bit but I'll file an issue later about that.

I also fixed the various boolean uniforms that were missing.

**Comment by jdm** [comment]
```
  ▶ CRASH [expected OK] /_mozilla/webgl/conformance-1.0.3/conformance/ogles/GL/gl_FragCoord/gl_FragCoord_001_to_003.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.1.0-devel
  │ DESCRIPTION: WebGL GLSL conformance test: gl_FragCoord_001_to_003.html
  │ 
  │ test: gl_FragCoord_xy_frag.test.html
  │ loading: ../default/default.vert
  │ loading: gl_FragCoord_xy_frag_ref.frag
  │ loading: ../default/default.vert
  │ loading: gl_FragCoord_xy_frag.frag
  │ loaded: gl_FragCoord_xy_frag_ref.frag
  │ loaded: ../default/default.vert
  │ 
  │ loaded: ../default/default.vert
  │ loaded: gl_FragCoord_xy_frag.frag
  │ 
  │ PASS images are the same
  │ PASS getError was expected value: NO_ERROR : there should be no errors
  │ 
  │ test: gl_FragCoord_z_frag.test.html
  │ loading: gl_FragCoord_z_frag_ref.vert
  │ loading: gl_FragCoord_z_frag_ref.frag
  │ loading: ../default/default.vert
  │ loading: gl_FragCoord_z_frag.frag
  │ loaded: gl_FragCoord_z_frag_ref.vert
  │ loaded: gl_FragCoord_z_frag_ref.frag
  │ 
  │ assertion failed: location >= 0 (thread WebGLThread, at components/canvas/webgl_thread.rs:1120)
  │ stack backtrace:
  │    0:     0x7fd2ef19241c - backtrace::backtrace::trace::h48eb2921f133e389
  │    1:     0x7fd2ef192252 - <backtrace::capture::Backtrace as core::default::Default>::default::h00deb8ea10633b85
  │    2:     0x7fd2ef192298 - backtrace::capture::Backtrace::new::h6d1048ca147e297d
  │    3:     0x7fd2ec4e2728 - servo::main::{{closure}}::h343b2e747a03b7e2
  │    4:     0x7fd2ef1bbad3 - std::panicking::rust_panic_with_hook::hf121af3526fe4125
  │                         at libstd/panicking.rs:479
  │    5:     0x7fd2ee00a476 - std::panicking::begin_panic::h06fa6a45cd442aff
  │    6:     0x7fd2ee0206ad - canvas::webgl_thread::WebGLImpl::apply::haa471dfb2c5427b9
  │    7:     0x7fd2ee01cc48 - <canvas::webgl_thread::WebGLThread<VR, OB>>::handle_msg::h4a10c052a0820ae4
  │    8:     0x7fd2ee009e25 - std::sys_common::backtrace::__rust_begin_short_backtrace::h817ad4c5b5af86ee
  │    9:     0x7fd2ee00a4d8 - _ZN3std9panicking3try7do_call17hd4ba12f5477611fcE.llvm.15623415505575742723
  │   10:     0x7fd2ef1cd499 - __rust_maybe_catch_panic
  │                         at libpanic_unwind/lib.rs:105
  │   11:     0x7fd2ee0120f6 - <F as alloc::boxed::FnBox<A>>::call_box::h67a22db4f56cc3f6
  │   12:     0x7fd2ef1a66fa - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::haf969131982fb97c
  │                         at /checkout/src/liballoc/boxed.rs:650
  │                          - std::sys_common::thread::start_thread::hcbfc448db5968f29
  │                         at libstd/sys_common/thread.rs:24
  │   13:     0x7fd2ef1a4985 - std::sys::unix::thread::Thread::new::thread_start::ha4b2330dc32d1193
  │                         at libstd/sys/unix/thread.rs:90
  │   14:     0x7fd2eb3bd183 - start_thread
  │   15:     0x7fd2e9c8403c - clone
  │   16:                0x0 - <unknown>
```

**Comment by nox** [comment]
Needed to check for `gl_` prefix.

@bors-servo r=jdm

**Pull request merged**
