### PR TITLE
Use presentation hints correctly for the dimensions of `<img>`.

### PR DESCRIPTION
**Pull request by jdm**
Mostly straightforward; includes some extra fixes to make `<canvas>`
work the same way as `` for reflow.

Rebase of #8531.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9743)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo retry
* #9012

**Comment by KiChjang** [comment]
@bors-servo retry
* #9550

**Comment by Wafflespeanut** [comment]
waaat?

    Tests with unexpected results:
      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-001.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-002.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-003.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-006.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-007.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-008.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-009.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-010.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-014.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-018.htm

      ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/background-022.htm

**Pull request merged**
