### PR TITLE
style: Add a comment about the weird setup for justify-items.

### PR DESCRIPTION
**Pull request by emilio**
And derive ToCss while at it.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20210)

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
:( :( r+

**Comment by emilio** [comment]
Thanks for the review :)

**Comment by emilio** [comment]
@bors-servo r=Manishearth

 * Fixed the unused imports, whoops.

**Pull request merged**
