### PR TITLE
Update WR (ellipse border-radius, preserve-3d, rayon thread pool).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16801)

### CODE REVIEW

**Comment by glennw** [comment]
@bors-servo r=mbrubeck
 * Added some new test passes.

**Comment by jdm** [comment]
@bors-servo: retry
* #16803

**Comment by jdm** [comment]
```
  ▶ TIMEOUT [expected FAIL] /css-backgrounds-3_dev/html4/border-radius-clipping.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  └ Shutting down the Constellation after generating an output file or exit flag specified
```

**Comment by glennw** [comment]
@bors-servo try
 * Testing if the timeouts are consistent.

**Comment by glennw** [comment]
Superseded by https://github.com/servo/servo/pull/16775

**Pull request closed without merging**
