### PR TITLE
Update browserhtml version to 0.1.15

### PR DESCRIPTION
**Pull request by Gozala**
Update browserhtml version to 0.1.15

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] ~~These changes fix #__ (github issue number if applicable).~~

- [ ] ~~There are tests for these changes OR~~
- [x] These changes do not require tests because it just updates dependency

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12302)

### CODE REVIEW

**Comment by Gozala** [comment]
I doubt my changes are a reason for that test failure. @ConnorGBrewster what should I do next to get this inn ?

**Comment by ConnorGBrewster** [comment]
@Gozala we are having some infra issues, hopefully we should be up and running again soon. Nothing wrong here.

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #12314

**Pull request merged**
