### PR TITLE
Optional backtraces for JS errors and WebGL errors

### PR DESCRIPTION
**Pull request by jdm**
This adds two new build-time features to enable useful debugging tools when investigating why JS and WebGL content isn't working. They're optional because they're quite heavyweight.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they're optional developer features.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21825)

### CODE REVIEW

**Comment by jdm** [comment]
@nox I have added configuration flags to servobuild.example that describe what they do. Does that address your concerns?

**Comment by nox** [comment]
Yes!

**Comment by jdm** [comment]
@bors-servo retry
* oom

**Pull request merged**
