### PR TITLE
Remove our copy of Utf16Encoder in favor of the built-in equivalent (fixes #4725).

### LINKED ISSUE #4725: Remove our copy of Utf16Encoder.
In `ports/cef/wrapper.rs`.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by hgentry** [comment]
Is there anything I need to do?

**Comment by jdm** [comment]
Nope! @Ms2ger rebased your change on a recent revision and now it will be merged.

**Comment by Ms2ger** [comment]
Looks like bors isn't happy. I'll close this for now. @metajack, can you check what's up?

**Comment by larsbergstrom** [comment]
It looks like @hgentry does not have an e-mail address associated with their GitHub account, which makes bors unhappy.

**Comment by hgentry** [comment]
But I do? It shows up on my profile.

**Comment by larsbergstrom** [comment]
@hgentry It looks right now - previously, the commit did not show as associated with you. Let's reopen and retry!

**Pull request closed without merging**
