### PR TITLE
Remove unused dependencies from the msg crate.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9249)

### CODE REVIEW

**Comment by nox** [comment]
Good catch. How did you notice that?

@bors-servo r+

**Comment by ecoal95** [comment]
Nice! This will also help with @bholley's geckolib target

**Comment by nox** [comment]
@bors-servo r+

Should be on first line?

**Comment by KiChjang** [comment]
@bors-servo retry
* #9163

**Comment by bholley** [comment]
> Nice! This will also help with @bholley's geckolib target

I actually have a patch to remove the dependency of style on msg entirely.

**Comment by ecoal95** [comment]
@bholley Well, nvm then. Sorry for the noise :/, hopefully bors won't be too anoying

**Pull request merged**
