### PR TITLE
Makes Node::remove recursively remove all descendants of removed node from the doc.

### PR DESCRIPTION
**Pull request by pgonda**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5972)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you! I left a few small comments at <https://critic.hoppipolla.co.uk/r/4928>; please push another commit with the changes.

**Comment by nox** [comment]
What's the rationale for not doing this in node_removed()?

**Comment by pgonda** [comment]
That makes a lot of sense as it already traverses the descends. Thanks I
missed that method!

**Comment by jdm** [comment]
node_removed not always called, so it's less clear how to integrate it effectively.

**Comment by nox** [comment]
It is always called at some point, be it right now or later (otherwise Servo or the specs has a bug, AFAICT).

But to go further, I think that to conflate mutation observers and node_removed() is a bad idea. There is some book-keeping that needs to be done always, whether observers are suppressed or not, like setting the IS_IN_DOC flag right here, or improving how the document's title is handled, or caching things in HTMLTableElement (things like caption, tHead, tFoot…).

**Comment by pgonda** [comment]
So the change should be made?  I am confused about what you mean conflating observers and node_removed?

**Comment by nox** [comment]
@pgonda: @jdm mentioned that the move to the method node_removed() should not be done because node_removed() is called only if observers are not silenced. I'm arguing that it either doesn't matter (because it is eventually called for each concerned node anyway) or that it should even be called unconditionally because there are many book-keeping things to be done unconditionally on node removal.

**Comment by jdm** [comment]
Reading https://dom.spec.whatwg.org/#concept-node-remove , I think we should modify Node::remove to call node_removed unconditionally . @nox is right as usual!

**Comment by nox** [comment]
@jdm But I could see us abusing mutation observers to optimise things when invalidating or updating DOM caches. For example, when [https://dom.spec.whatwg.org/#concept-node-replace-all](replacing all children) from a table element, if the virtual method knows that all nodes were replaced, caches can be handled in a more clever way.

**Comment by nox** [comment]
But given node_removed doesn't currently do anything useful anywhere in the code, it's safe to just call it unconditionally for now.

**Comment by pgonda** [comment]
alright thanks!  I'll update this

**Comment by jdm** [comment]
It will be used in the future for steps 6-7, so just rename it to _suppress_observers to inhibit the warning.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: 1 of 2 files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- tests/wpt/web-platform-tests/dom/nodes/Document-getElementById.html @ r3

---

<sup>**[components/script/dom/node.rs, line 308 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5972#-JpqmSNxx1tcrumhpkSj)** ([raw file](https://github.com/servo/servo/blob/7e938a5b334ddec5cd9f63ebc0558685baaf5434/components/script/dom/node.rs#L308)):</sup>
Let's set this before calling unbind_from_tree.

---

<sup>**[components/script/dom/node.rs, line 1670 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5972#-JpqmNlvbMIGT53P6gYj)** ([raw file](https://github.com/servo/servo/blob/7e938a5b334ddec5cd9f63ebc0558685baaf5434/components/script/dom/node.rs#L1670)):</sup>
No need for this any more, since traverse_preorder includes the root node.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5972)

**Comment by jdm** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- components/script/dom/node.rs @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5972)

**Comment by jdm** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/script/dom/node.rs @ r6

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5972)

**Comment by jdm** [comment]
Go ahead and squash it all together!

**Comment by jdm** [comment]
Whoops, there's a submodule update that snuck in here. Closing the PR to make sure it doesn't get merged.

**Comment by jdm** [comment]
Please undo the change to the android-glue submodule :)

**Comment by mukilan** [comment]
Since node_removed is now unconditionally called and not conflated with mutation observers, shouldn't these two be removed as well? 
https://github.com/servo/servo/blob/master/components/script/dom/node.rs#L1762-L1765
https://github.com/servo/servo/blob/master/components/script/dom/node.rs#L2263

**Comment by jdm** [comment]
Good point. File an issue about it?

**Pull request merged**
