### PR TITLE
clippy: Fix `default_constructed_unit_structs` warnings in `components`

### PR DESCRIPTION
**Pull request by oluwatobiss**
Remove `default()` calls to fix the `default_constructed_unit_structs` warnings.

**ref:** https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes are part of #31500
- [X] These changes do not require tests because they only resolve clippy warnings. They do not change functionalities.

### CODE REVIEW

**Comment by mrobinson** [comment]
Seems that there is a build failure:

```
error[E0423]: expected value, found struct `FontContextHandle`
   --> components/gfx/font_cache_thread.rs:500:35
    |
500 |                       font_context: FontContextHandle,
    |                                     ^^^^^^^^^^^^^^^^^ help: use struct literal syntax instead: `FontContextHandle { ctx: val }`
    |
   ::: components/gfx/platform/freetype/font_context.rs:99:1
    |
99  | / pub struct FontContextHandle {
100 | |     // WARNING: FreeTypeLibraryHandle contains raw pointers, is clonable, and also implements
101 | |     // `Drop`. This field needs to be Rc<> to make sure that the `drop` function is only called
102 | |     // once, otherwise we'll get crashes. Yuk.
103 | |     pub ctx: Rc<FreeTypeLibraryHandle>,
104 | | }
    | |_- `FontContextHandle` defined here

error[E0423]: expected value, found struct `FontContextHandle`
   --> components/gfx/font_context.rs:68:22
    |
68  |           let handle = FontContextHandle;
    |                        ^^^^^^^^^^^^^^^^^ help: use struct literal syntax instead: `FontContextHandle { ctx: val }`
    |
   ::: components/gfx/platform/freetype/font_context.rs:99:1
    |
99  | / pub struct FontContextHandle {
100 | |     // WARNING: FreeTypeLibraryHandle contains raw pointers, is clonable, and also implements
101 | |     // `Drop`. This field needs to be Rc<> to make sure that the `drop` function is only called
102 | |     // once, otherwise we'll get crashes. Yuk.
103 | |     pub ctx: Rc<FreeTypeLibraryHandle>,
104 | | }
    | |_- `FontContextHandle` defined here

For more information about this error, try `rustc --explain E0423`.
error: could not compile `gfx` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
      Timing report saved to /home/runner/work/servo/servo/target/cargo-timings/cargo-timing-20240322T153431Z.html
Failed in 0:06:30
Warning:  Could not generate notification: No module named 'dbus'
Error: Process completed with exit code 101.
```

**Comment by oluwatobiss** [comment]
Hmm, let me check that.

**Comment by mrobinson** [comment]
@oluwatobiss That makes sense. The code that is failing to build is for the FreeType build which isn't used in Windows. I think you just need to revert the changes that affect `FontContextHandle`, which isn't a unit struct for the FreeType build. Instead, you probably need to add an `allow` directive for those lines.

**Comment by oluwatobiss** [comment]
Ah, I see. Thank you for explaining.

**Review by mrobinson — APPROVED** [review]

**Pull request merged**
