### PR TITLE
Documentation of inheritance in type ids

### PR DESCRIPTION
**Pull request by wilcus**
Aditional documentation about this issue https://github.com/servo/servo/issues/7205

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7337)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Looks good, thanks! See above for some minor proof-reading.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/mod.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7337#-Jy3sLP0JafslQxlFHW8)** ([raw file](https://github.com/servo/servo/blob/452bc40660b085eb0e8b4a07938c1082ca5e0ee5/components/script/dom/mod.rs#L57)):</sup>
"apply" should be "applies"

---

<sup>**[components/script/dom/mod.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7337#-Jy3sNl3eLGVL4pAUX6w)** ([raw file](https://github.com/servo/servo/blob/452bc40660b085eb0e8b4a07938c1082ca5e0ee5/components/script/dom/mod.rs#L57)):</sup>
There should be a period or colon after "typeids," and the following "the" should start a new sentence.

---

<sup>**[components/script/dom/mod.rs, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7337#-Jy3sVdxfXe_YvFc7eD0)** ([raw file](https://github.com/servo/servo/blob/452bc40660b085eb0e8b4a07938c1082ca5e0ee5/components/script/dom/mod.rs#L58)):</sup>
typo: "additional"

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7337)

**Comment by mbrubeck** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7337)

**Comment by jdm** [comment]
@bors-servo: retry
* #7422

**Pull request merged**
