### PR TITLE
Add a border to the logo to differentiate from background color.

### PR DESCRIPTION
**Pull request by jdm**
By @zmike from https://github.com/servo/servo/pull/11473#issuecomment-223118097.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11814)

### CODE REVIEW

**Comment by jdm** [comment]
cc @Coder206

**Comment by Coder206** [comment]
@jdm @zmike There still isn't much visibility of this icon on a Windows 10 system, see below:
servo_b
Initial:
servo

Perhaps making the border slightly thicker?

**Comment by Coder206** [comment]
Take a look at the last logo found here: http://imgur.com/a/JkclL
I find it really makes the border more visible. I am not a fan of the background color nor the low resolution but maybe reworking the logo just a bit might pay off for Windows 10. 

In Windows 10, you can change the task bar color but I think black is the default.

I do realize there has already been a decision here...

**Comment by jdm** [comment]
@bors-servo: retry
* #11693

**Pull request merged**
