### PR TITLE
Add `@keyframes` and `animation-*` support.

### PR DESCRIPTION
**Pull request by emilio**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes

This adds support for parsing `@keyframes` rules, and animation properties. Stylo will need it sometime soonish, plus I want to make animations work in Servo.

The remaining part is doin the math and trigger the animations correctly from servo. I don't expect it to be _that_ hard, but probaby I'll need to learn a bit more about the current animation infra (e.g. why the heck is the `new_animations_sender` guarded by a `Mutex`?).

I'd expect to land this, since this is already a bunch of work, this is the part exclusively required by stylo (at least if we don't use Servo's machinery), the media query parsing is tested, and the properties land after a flag, but if you prefer to wait until I finish this up it's fine for me too.

r? @SimonSapin 

cc @pcwalton @bholley

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11766)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo: retry

* I/O failure building openssl, wtf?

**Comment by emilio** [comment]
@bors-servo: retry

 * Android random failure again (?) cc @larsbergstrom

**Comment by jdm** [comment]
The android builder is out of space. We won't be able to merge anything until that's fixed.

**Comment by emilio** [comment]
@pcwalton: Do you know if there's a specific reason to have `new_animations_sender` guarded by a `Mutex`? We only lock it for sending...

**Comment by jdm** [comment]
I assume because it can be used from multiple worker threads, and Sender's aren't Sync.

**Comment by emilio** [comment]
@jdm: but you can clone it and move it, right?

**Comment by emilio** [comment]
The last commit won't pass tidy, but it's a large-ish refactor of how computed properties are calculated, so I thought it could be worth it to push it for now, since I won't be able to work on it more today.

**Comment by emilio** [comment]
The latest commits actually get keyframes working to a decent extent \o/.

Probably part of the approach could/should be reviewed by @pcwalton.

Regarding the `Mutex`, it's because it's inside of `SharedLayoutContext` that can't just be cloned. This can be solved splitting the context, but that's another patch.

There are a few known shortcomings that must be solved before merging, read the last commit for details, but I think this approach is decent enough that I can get some feedback on it.

Also, a huge cleanup is needed, but with the following html file:

```html
<!doctype html>
<meta charset="utf-8">
<style>
  @keyframes foo {
    from { transform: scale(0.5); }
    to { transform: scale(1.5) }
  }

  div {
    animation-name: foo;
    animation-duration: 1.5s;
    animation-timing-function: ease;
    animation-iteration-count: infinite;
    border-radius: 100px;
    width: 200px;
    height: 200px;
    line-height: 200px;
    margin: 100px;
    background-color: red;
    text-align: center;
    font-family: sans-serif;
    font-weight: bold;
    color: white;
  }

  /* See the last commit message to see why */
  div:hover { }
</style>
<div>Hello Servo!</div>
```

This is the output (after hovering the element), and sorry for the bad quality of the gif:

anim

**Comment by emilio** [comment]
Ok, so solved the restyle bug (which was dumb btw).

This still has a few bugs related to where animations are retriggered. Basically, when we expire an animation, we actually remove all the state, so when a restyle happens we apply all the state unconditionally.

So I think we'll have to keep the state and, to avoid leaking, don't send just an `Animation` to the `new_animations_sender`, but either a `AnimationBatch(OpaqueNode, Vec<(Atom, State)>)` or a `Transition`, and just expire those who doesn't appear on the batch.

I think the quirks are fixable, but I'd also like a review from @pcwalton for the general approach if possible :-)

**Comment by pcwalton** [comment]
I'll review this tomorrow

**Comment by SimonSapin** [comment]
Partial review, mostly for parsing.

---

Reviewed 1 of 24 files at r66, 2 of 12 files at r67, 1 of 5 files at r71, 3 of 11 files at r72, 1 of 4 files at r73, 2 of 4 files at r77, 3 of 8 files at r81, 1 of 5 files at r84.
Review status: 14 of 25 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/style/keyframes.rs, line 19 \[r87\]](https://reviewable.io:443/reviews/servo/servo/11766#-KLGoPkfOxjWJrCJ94na:-KLGoPkfOxjWJrCJ94nb:-684563769) ([raw file](https://github.com/servo/servo/blob/d017450a03e7c3110687929c08e1bd71522e09c6/components/style/keyframes.rs#L19)):*
> ```Rust
> ///     width: 100%;
> /// }
> pub fn parse_keyframe_list(context: &ParserContext, input: &mut Parser) -> Result<Vec<Keyframe>, ()> {
> ```

 https://drafts.csswg.org/css-animations/#keyframes defines the grammar with `<rule-list>`, so this should use `cssparser::RuleListParser`:

```rust
pub fn parse_keyframe_list(context: &ParserContext, input: &mut Parser) -> Vec<Keyframe> {
    RuleListParser::new_for_nested_rule(input, KeyframeListParser { context: context })
        .filter_map(Result::ok)
        .collect()
}

struct KeyframeListParser<'a> {
    context: &'a ParserContext<'a>,
}

enum Void {}
impl<'a> AtRuleParser for KeyframeListParser<'a> {
    type Prelude = Void;
    type AtRule = Keyframe;
}

impl<'a> QualifiedRuleParser for KeyframeListParser<'a> {
    type Prelude = KeyframeSelector;
    type QualifiedRule = Keyframe;

    fn parse_prelude(&self, input: &mut Parser) -> Result<Self::Prelude, ()> {
        let start = input.position();
        match input.parse_comma_separated(|input| KeyframePercentage::parse(input)) {
            Ok(percentages) => Ok(KeyframeSelector(percentages)),
            Err(()) => {
                let message = format!("Invalid keyframe rule: '{}'", input.slice_from(start));
                log_css_error(input, start, &message, self.context);
                Err(())
            }
        }
    }

    fn parse_block(&self, prelude: Self::Prelude, input: &mut Parser)
                   -> Result<Self::QualifiedRule, ()> {
        Ok(Keyframe {
            selector: prelude,
            // FIXME: needs parsing different from parse_property_declaration_list:
            // https://drafts.csswg.org/css-animations/#keyframes
            // Paragraph "The <declaration-list> inside of <keyframe-block> ..."
            declarations: parse_property_declaration_list(self.context, input).normal,
        })
    }
}
```

---

*[components/style/keyframes.rs, line 26 \[r87\]](https://reviewable.io:443/reviews/servo/servo/11766#-KLHAudevTAqdHwvzjtb:-KLHAudevTAqdHwvzjtc:352994645) ([raw file](https://github.com/servo/servo/blob/d017450a03e7c3110687929c08e1bd71522e09c6/components/style/keyframes.rs#L26)):*
> ```Rust
> 
>     if keyframes.len() < 2 {
>         return Err(())
> ```

Is that really what should happen? I couldn’t find it in the spec. On the contrary, https://drafts.csswg.org/css-animations/#ref-for-typedef-keyframe-selector-2 says how keyframes for 0% and 100% are synthesized if they’re not specified, which could make it useful to only specify one keyframe.

---

*[components/style/keyframes.rs, line 60 \[r87\]](https://reviewable.io:443/reviews/servo/servo/11766#-KLGw5WgBDlw_xEHdPvx:-KLGw5WgBDlw_xEHdPvy:1476370911) ([raw file](https://github.com/servo/servo/blob/d017450a03e7c3110687929c08e1bd71522e09c6/components/style/keyframes.rs#L60)):*
https://drafts.csswg.org/css-animations/#ref-for-typedef-keyframe-block-3
> Values less than 0% or higher than 100% are invalid and cause their <keyframe-block> to be ignored.

This code should check for this and return `Err(())` for invalid values. As it stands, it’ll trigger the `debug_assert!` above and panic in debug mode.

---

*[components/style/parallel.rs, line 61 \[r87\]](https://reviewable.io:443/reviews/servo/servo/11766#-KLGpODpuyoVlggu8dWX:-KLGpODpuyoVlggu8dWY:677194780) ([raw file](https://github.com/servo/servo/blob/d017450a03e7c3110687929c08e1bd71522e09c6/components/style/parallel.rs#L61)):*
> ```Rust
>     let context = C::new(proxy.user_data(), unsafe_nodes.1);
> 
>     let mut discovered_child_nodes = vec![];
> ```

Why?

---

*[components/style/stylesheets.rs, line 507 \[r87\]](https://reviewable.io:443/reviews/servo/servo/11766#-KLH-zdkWo65xh3u38j7:-KLH-zdlOZmyAS2Jxknv:-1642560539) ([raw file](https://github.com/servo/servo/blob/d017450a03e7c3110687929c08e1bd71522e09c6/components/style/stylesheets.rs#L507)):*
> ```Rust
>             },
>             "keyframes" => {
>                 let name = try!(input.expect_ident());
> ```

https://drafts.csswg.org/css-animations/#typedef-keyframes-name

```rust
                let name = match input.next() {
                    Ok(Token::Ident(ref value)) if value != "none" => Atom::from(&**value),
                    Ok(Token::QuotedString(value)) => Atom::from(&*value),
                    _ => return Err(())
                };
                Ok(AtRuleType::WithBlock(AtRulePrelude::Keyframes(name)))
```

---

*[components/style/properties/data.py, line 20 \[r87\]](https://reviewable.io:443/reviews/servo/servo/11766#-KLGpvyccu5yIw4NwDaO:-KLGpvyccu5yIw4NwDaP:-1662110734) ([raw file](https://github.com/servo/servo/blob/d017450a03e7c3110687929c08e1bd71522e09c6/components/style/properties/data.py#L20)):*
> ```Python
> 
> # https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties
> def is_known_animatable_property(name):
> ```

I’m somewhat against out-of-band data like this is it’s easy to let it go out of sync. I’d prefer to have this info in `components/style/properties/longhand/*.mako.rs` alongside the rest of property definitions. This PR already introduces an `animatable` parameter to the `Longhand` python class constructor, let’s use it. Maybe that parameter should even be mandatory to make sure we don’t forget to set it.

Also, when implementing please don’t use documentation (MDN) instead of normative specifications.

---

*[components/style/properties/longhand/box.mako.rs, line 607 \[r87\]](https://reviewable.io:443/reviews/servo/servo/11766#-KLGt8RIblKliod5pefl:-KLGt8RIblKliod5pefm:327154327) ([raw file](https://github.com/servo/servo/blob/d017450a03e7c3110687929c08e1bd71522e09c6/components/style/properties/longhand/box.mako.rs#L607)):*
> ```Rust
>                         try!(dest.write_str(", "));
>                     }
>                     // NB: to_string() needed due to geckolib backend.
> ```

Do both `Atom` types implement `Display`? If so, please use `try!(write!(dest, "{}", name))`. If not, please file a follow up issue to implement it and do that.

`Display` can be implemented on Gecko atoms without allocating, but decoding `char` code points from UTF-16 one at a time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11766#-:-KLHDl47g7MScf10L12o:1212602133)*

**Comment by pcwalton** [comment]
The layout code looks fine to me.

**Comment by SimonSapin** [comment]
Let’s call it r=SimonSapin+pcwalton with a rebase.

**Comment by emilio** [comment]
Ok, rebased and squashed wip commits.

@bors-servo: r=SimonSapin,pcwalton

**Comment by emilio** [comment]
@bors-servo: r=SimonSapin,pcwalton

Fixed geckolib build that was complaining after the rustup for a private type alias in a public member:

```
data.rs:34:39: 34:48 error: private type in public interface [E0446]
data.rs:34     pub new_animations_sender: Sender<Animation>,
                                                 ^~~~~~~~~
data.rs:34:39: 34:48 help: run `rustc --explain E0446` to see a detailed explanation
data.rs:35:43: 35:52 error: private type in public interface [E0446]
data.rs:35     pub new_animations_receiver: Receiver<Animation>,
                                                     ^~~~~~~~~
data.rs:35:43: 35:52 help: run `rustc --explain E0446` to see a detailed explanation
data.rs:36:64: 36:73 error: private type in public interface [E0446]
data.rs:36     pub running_animations: Arc<RwLock<HashMap<OpaqueNode, Vec<Animation>>>>,
                                                                          ^~~~~~~~~
data.rs:36:64: 36:73 help: run `rustc --explain E0446` to see a detailed explanation
data.rs:37:64: 37:73 error: private type in public interface [E0446]
data.rs:37     pub expired_animations: Arc<RwLock<HashMap<OpaqueNode, Vec<Animation>>>>,
                                                                          ^~~~~~~~~
data.rs:37:64: 37:73 help: run `rustc --explain E0446` to see a detailed explanation
error: aborting due to 4 previous errors
error: Could not compile `geckoservo`.

**Pull request merged**
