### PR TITLE
Update to cargo 0.19.0-nightly (994e552 2017-04-25)

### PR DESCRIPTION
**Pull request by SimonSapin**
This should be unblocked now: https://github.com/servo/servo/pull/15852#issuecomment-296379226

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16601)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
error: compile-fail/privatize.rs:8: unexpected "error": '8:1: 8:33: multiple matching crates for `deny_public_fields` [E0464]'

error: compile-fail/privatize.rs:8: unexpected "error": '8:1: 8:33: can't find crate for `deny_public_fields` [E0463]'
```

I can reproduce locally, and `mach clean` works around the issue. I wonder if we should run that on the builders and move on, or try to find a proper fix…

**Comment by SimonSapin** [comment]
This is because compile tests use rustc with `-L target/debug and -L target/debug/deps` and rely of finding dependencies in these directories by name, whereas Cargo uses `--extern name=path/to/something.rlib` with exact file names. When upgrading Cargo, some hash changes, new .rlib files are created, and old ones are not removed by default.

Finding the proper paths to use with `--extern` in compile test seems like a lot of work and not worth it. So it’s got with the exceptional `clean`. I’d rather not SSH into each builder to do that and hope that homu and buildbot’s scheduling will work in my favor, and at the same time I’d rather not go back to cleaning on every single build.

So it sounds like we need something like Gecko’s `CLOBBER` file. `./mach clean` would be run automatically as part of build jobs if the `CLOBBER` file has changed since the last build.

**Comment by jdm** [comment]
@bors-servo: retry
#16644

**Pull request merged**
