### PR TITLE
Update WR - includes a number of optimizations, bsd build fixes, tidy ups.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13900)

### CODE REVIEW

**Comment by emilio** [comment]
r=me if it passes, given the individual shader bits have been reviewed upstream

**Comment by emilio** [comment]
I wonder if this is caused by the shader change in https://github.com/servo/webrender/pull/446 and if that might also change the expectations in #13870.

**Comment by glennw** [comment]
@emilio Yea, in the failing test one of the image results is (0,0,0) in color and the other is (1/255, 0, 0) so it's off by 1 bit. I'll look at the shader change today and see if I can change the float operations to get them both back to output (0,0,0).

**Comment by glennw** [comment]
r? @pcwalton 

I have updated the text expectations - 10 new passes and 1 new fail. The failure is due to what appears to be a rounding error in mesa softpipe. The test in question outputs a color of (1,0,0) instead of (0,0,0) when the float color before scaling to u8 range is 0.499999. All the real GPUs I've tested it on produce the correct result of (0,0,0) for that filter / contrast test. We still have coverage of contrast filter in the other WPT tests.

**Comment by pcwalton** [comment]
@bors-servo: r+

Nice!

**Comment by glennw** [comment]
@bors-servo retry
 * #13887

**Pull request merged**
