### PR TITLE
Update WR (gradient features).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16252)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
▶ OK [expected TIMEOUT] /webgl/conformance-1.0.3/conformance/context/context-creation-and-destruction.html

      ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/context/context-creation-and-destruction.html:
      └ PASS [expected NOTRUN] Overall test

@bors-servo retry

**Comment by jdm** [comment]
```
  ▶ PASS [expected FAIL] /compositing-1_dev/html/mix-blend-mode-parent-with-border-radius.htm
```

**Comment by emilio** [comment]
r=me with the new pass taken into account, thanks!

**Comment by glennw** [comment]
@bors-servo r=emilio

* Added a new PASS.

**Pull request merged**
