### PR TITLE
Use MSVC toolchain if PLATFORM is defined

### PR DESCRIPTION
**Pull request by mati865**
`VSInstallDir` exists only when Visual Studio is installed.
`VS140COMNTOOLS` is defined by installing either Visual Studio or [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)

It will allow to build MSVC based Servo without having to install whole Visual Studio (few GiB).

EDIT: Another (maybe cleaner) solution would be reverting https://github.com/servo/servo/commit/63ec96a57d4772a961bea63111c927ccd7c85a91

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because `VS140COMNTOOLS` variable is already used in [mach.bat](https://github.com/servo/servo/blob/master/mach.bat)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14346)

### CODE REVIEW

**Comment by mati865** [comment]
After applying likewise modifications to https://github.com/servo/mozjs Servo build successfully without Visual Studio.

**Comment by larsbergstrom** [comment]
This looks good to me. cc @vvuk @UK992

**Comment by UK992** [comment]
This change break Windows GNU build.
It would be better check if ``PLATFORM`` environment variable exists, since is required to determinate build type for MSVC.

Overall something like:
```python
if os.getenv("PLATFORM") is not None:
    os_type = "pc-windows-msvc"
elif os.getenv("MSYSTEM") is not None:
    os_type = "pc-windows-gnu"
else:
    os_type = "unknown"
```

**Comment by mati865** [comment]
@UK992 applied your suggestion with small modification and it detected both toolchains properly.

If it is accepted I'll rebase it into one commit.

**Comment by UK992** [comment]
Please change to msvc first then gnu, so it wont cause problems building from mozilla-build, otherwise looking good.

**Comment by mati865** [comment]
@UK992 it caused MinGW build to fail https://ci.appveyor.com/project/servo/servo/build/1.0.11336/job/gymhg1821802l7ty (I amended those changes to first commit).

Maybe something like this?
```
        if os.getenv("PLATFORM") is not None and os.getenv("MSYSTEM") is None:
             os_type = "pc-windows-msvc"
        elif os.getenv("MSYSTEM") is not None:
             os_type = "pc-windows-gnu"
        else:
            os_type = "unknown"
```

**Comment by UK992** [comment]
Well in this case removing `platform: -x64` from appveyor.yml should fix it.

**Comment by mati865** [comment]
@UK992 It fixed build indeed.

**Comment by Wafflespeanut** [comment]
What's the status of this?

@UK992 Is this good to go?

**Comment by UK992** [comment]
@Wafflespeanut yes

**Comment by jdm** [comment]
@bors-servo: r=UK992,larsberg
Thanks @mati865!

**Pull request merged**
