### PR TITLE
Update app_units to 0.4.1

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16914)

### CODE REVIEW

**Comment by Manishearth** [comment]
r=jryans

(will r+ when the queue is emptier, currently doing a try run to ensure there aren't any broken /now-fixed csstests)

Gecko side expectations update is https://github.com/servo/app_units/pull/26#issuecomment-301931183

**Comment by Manishearth** [comment]
ok this has like a million servo failures. hm

**Comment by Manishearth** [comment]
@bors-servo try

some layout fixes necessary

**Comment by jdm** [comment]
@bors-servo: retry
* cargo failure

**Comment by Manishearth** [comment]
@bors-servo p=5

needs test updates on gecko side

**Pull request merged**
