### PR TITLE
Make use of FromStr and Default traits in lib canvas

### LINKED ISSUE #7517: Use FromStr in canvas_traits
canvas_traits/lib.rs contains a lot of `fn from_str(&str) -> Option<Self> {}`-like methods.

These should all implement [`FromStr`](http://doc.rust-lang.org/std/str/trait.FromStr.html)

In other words,

```rust
impl Foo {
 fn from_str(&str) -> Option<Foo> {
   match str {
      ..... => Some(...),
      ..... => Some(...),
      ..... => None
   }
 }
}
```

should become

```rust
impl FromStr for Foo {
 type Err = ()
 fn from_str(&str) -> Result<Foo,()> {
   match str {
      ..... => Ok(...),
      ..... => Ok(...),
      ..... => Err(()),
   }
 }
}
```

Some code may need to be updated to make uses of this compile again with `Result`.

(An additional task you can do while here is making the implementation of `default()` for `CompositionOrBlending` use [`Default`](http://doc.rust-lang.org/std/default/trait.Default.html) instead

### PR DESCRIPTION
**Pull request by thiagopnts**
fixes #7517

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7522)

### CODE REVIEW

**Comment by Manishearth** [comment]
```
./components/canvas_traits/lib.rs:40: use statement is not in alphabetical order

	expected: std::default::Default

	found: std::sync::mpsc::Sender

./components/canvas_traits/lib.rs:42: use statement is not in alphabetical order

	expected: std::sync::mpsc::Sender

	found: std::default::Default

./components/script/dom/canvasrenderingcontext2d.rs:48: use statement is not in alphabetical order

	expected: std::str::FromStr

	found: std::sync::mpsc::channel

./components/script/dom/canvasrenderingcontext2d.rs:49: use statement is not in alphabetical order

	expected: std::sync::mpsc::channel

	found: std::str::FromStr
```

Fails tidy

**Comment by thiagopnts** [comment]
@Manishearth fixed

**Comment by Manishearth** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
