### PR TITLE
Run unit tests in ci

### LINKED ISSUE #8856: Make travis run the unit tests
They're often forgotten when updating code. We should see if we can run them on Travis as well. It should only require adding a `./mach test-unit` entry to our `.travis.yml` file in the root directory.

### PR DESCRIPTION
**Pull request by mike-zorn**
Fixes #8856.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8873)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+ 

Thanks!

**Comment by Manishearth** [comment]
@larsbergstrom Does New Travis have a time limit or anything?

**Comment by KiChjang** [comment]
```
Ran 6932 tests finished in 254.0 seconds.
  • 6931 ran as expected. 8 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/c414-flt-fit-002.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ was ready to save, resetting ready_to_save_state
```

**Comment by Manishearth** [comment]
@bors-servo retry

 - Maybe https://github.com/servo/servo/issues/6644

**Comment by Manishearth** [comment]
@bors-servo retry

 - Buildbot brokenness, kicked

**Pull request merged**
