### PR TITLE
Upgrade to rustc 1.38.0-nightly (dddb7fca0 2019-07-30)

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23870)

### CODE REVIEW

**Comment by SimonSapin** [comment]
This fixes https://tools.taskcluster.net/groups/BGErxtTPTf-Xb_3fRNlAqA/tasks/Kg28gBoAQDaSyJQpisKKog/runs/0/logs/public%2Flogs%2Flive.log, but is blocked on a Nightly that has rustfmt.

**Comment by SimonSapin** [comment]
@nox Thanks for the review, but tidy will fail because this toolchain does not have rustfmt. https://github.com/rust-lang/rust/pull/63041 is a first step toward fixing that…

**Comment by SimonSapin** [comment]
Next is https://github.com/rust-lang/rustfmt/pull/3707, then presumably updating the gitsubmodule in `rust-lang/rust`.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Pull request merged**
