### PR TITLE
Move PaintMsg enum to gfx_traits #8844

### LINKED ISSUE #8844: Move PaintMsg enum to gfx_traits
It's defined in `components/msg/constellation_msg.rs`, but it's only used by `components/compositing/constellation.rs` and `gfx/paint_task.rs`. It belongs in `components/gfx_traits/lib.rs` instead.

### PR DESCRIPTION
**Pull request by Manishearth**
re-PR of https://github.com/servo/servo/pull/9007, because homu seems stuck

Fixes #8844.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9022)

### CODE REVIEW

**Comment by KiChjang** [comment]
```

Ran 7097 tests finished in 259.0 seconds.
  • 7096 ran as expected. 8 tests skipped.
  • 1 tests passed unexpectedly

Tests with unexpected results:
  ▶ PASS [expected FAIL] /css21_dev/html4/quotes-036.htm
```
Is this expected?

**Comment by nox** [comment]
@KiChjang #7846.

**Comment by Manishearth** [comment]
The build is still running! http://build.servo.org/builders/linux-rel/builds/1047

**Comment by Manishearth** [comment]
7f77546945f948560cdc26b12b99d5ccd390c2e39d2849d3423ae7608dac066a

**Pull request merged**
