### PR TITLE
script: Implement enough 2D canvas support to render basic SVGs such as the tiger

### PR DESCRIPTION
**Pull request by pcwalton**
r? @jdm 

Depends on servo/rust-geom#65 and servo/rust-azure#130

### CODE REVIEW

**Comment by pcwalton** [comment]
Rebased and issues addressed. re-r? @jdm

**Comment by jdm** [comment]
Critic'd.

**Comment by pcwalton** [comment]
Issues addressed. re-r? @jdm

**Comment by jdm** [comment]
Squash and rebase!

**Comment by jdm** [comment]
```
   Compiling canvas v0.0.1 (file:///home/servo/buildbot/slave/linux1/build/components/servo)
canvas_paint_task.rs:7:50: 7:57 error: unresolved import `azure::azure_hl::Pattern`. There is no `Pattern` in `azure::azure_hl`
canvas_paint_task.rs:7 use azure::azure_hl::{ColorPattern, PathBuilder, Pattern};
                                                                        ^~~~~~~
error: aborting due to previous error
```

**Comment by mmatyas** [comment]
Hi, what's the status of this patch? I would like to use it for further development.

**Comment by jdm** [comment]
@pcwalton needs to rebase it and fix the build error.

**Comment by jdm** [comment]
Rebased in #5016.

**Pull request closed without merging**
