### PR TITLE
Support synchronous about:blank loads

### LINKED ISSUE #3924: iframes should load about:blank by default
https://html.spec.whatwg.org/multipage/embedded-content.html#process-the-iframe-attributes

In particular, this load must cause contentWindow to be non-null. https://hsivonen.fi/about-blank/ is good reading.

### PR DESCRIPTION
**Pull request by jdm**
@Ms2ger, I would appreciate your thoughts on this design. It leverages the existing synchronous API support for the network load (the same way that sync XHR works), and introduces a one-off channel for the constellation's frame creation notification message when necessary.

Resolves #3924.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8600)

### CODE REVIEW

**Comment by jdm** [comment]
```
  • 14 tests crashed unexpectedly
  • 7 tests timed out unexpectedly
  • 16 tests unexpectedly okay
  • 30 tests had unexpected subtest results
```
Exciting!

**Comment by Manishearth** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 48 of 48 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[components/script/dom/browsercontext.rs, line 117 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4J_ZVgOvIhsyzRSVLH:-K4J_ZVgOvIhsyzRSVLI:556208889) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/browsercontext.rs#L117)):*
Can't we just make this `MaybeRemoteRef<T>` and `MaybeRemoteField<T>`? Less dupilication that way

---

*[components/script/dom/browsercontext.rs, line 119 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JgQIWpMd_erlnMonS:-K4JgQIWpMd_erlnMonT:-1677583755) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/browsercontext.rs#L119)):*
I don't see this being used in this PR. What's this going to be used for?

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 99 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8600#-K48kYaeDtE9MK3wuQV6:-K48kYaeDtE9MK3wuQV7:143590326) ([raw file](https://github.com/servo/servo/blob/41097ce4b3c41945b68bafc14c88ce0763e0a885/components/script/dom/dedicatedworkerglobalscope.rs#L99)):*
I think we can just stick try! here? Not necessary though.

---

*[components/script/dom/htmliframeelement.rs, line 506 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4CZyvDjGb3SmV0xy-9:-K4CZyvDjGb3SmV0xy-A:924776182) ([raw file](https://github.com/servo/servo/blob/acad2db1023b9c2003764b8798f059a3500e5b1a/components/script/dom/htmliframeelement.rs#L506)):*
nit: spec link (https://html.spec.whatwg.org/multipage/#iframe-load-event-steps)

---

*[components/script/dom/htmliframeelement.rs, line 71 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JcC8MvzNHuulmQR68:-K4JcC8MvzNHuulmQR69:987981943) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/htmliframeelement.rs#L71)):*
:heart: 

---

*[components/script/script_task.rs, line 600 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JdMuy996k18i346TX:-K4JdMuy996k18i346TY:566289099) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/script_task.rs#L600)):*
Should have documentation that mentions that it can only be called from the script thread.

(Most other script-thread-only functions require you to have an existing JS object with you, which is  hard to get off-thread. This one only needs a PipelineId, which can be found on any thread.)

---

*[tests/wpt/metadata/dom/nodes/Element-matches.html.ini, line 58 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JhCJoehdCwl7ncwsL:-K4JhCJoehdCwl7ncwsM:166874) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/tests/wpt/metadata/dom/nodes/Element-matches.html.ini#L58)):*
?

---

*[tests/wpt/metadata/dom/nodes/ParentNode-querySelector-All.html.ini, line 250 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JhG8bADRMCLvdidOx:-K4JhG8ccP0YVn348QB4:166874) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/tests/wpt/metadata/dom/nodes/ParentNode-querySelector-All.html.ini#L250)):*
?

---

*[tests/wpt/metadata/dom/ranges/Range-surroundContents.html.ini, line 0 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JhvkuxXxGQ78mcy6M:-K4JhvkuxXxGQ78mcy6N:-499318459) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/tests/wpt/metadata/dom/ranges/Range-surroundContents.html.ini#L0)):*
Ditto

---

*[tests/wpt/metadata/html/browsers/browsing-the-web/read-text/load-text-plain.html.ini, line 8 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JiQiDgQoRBpt5wFbb:-K4JiQiDgQoRBpt5wFbc:-499318459) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/tests/wpt/metadata/html/browsers/browsing-the-web/read-text/load-text-plain.html.ini#L8)):*
Ditto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8600)*

**Comment by Manishearth** [comment]
Design looks good to me; though Ms2ger should still have a look at it IMO.

**Comment by Ms2ger** [comment]
Idle musing, not to be taken as a suggestion that I understand the design yet: should `as_local` return an `Option`?

**Comment by jdm** [comment]
I don't think so. It's meant as a hack right now to make it clear what the choke points in the API are.

**Comment by Ms2ger** [comment]
Reviewed up to "Flesh out the iframe attribute processing steps."

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmliframeelement.rs, line 189 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4X7WTZqxa3wyykT_f4:-K4X7WTZqxa3wyykT_f5:129482338) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/htmliframeelement.rs#L189)):*
This doesn't match the spec: `get_url()` returns `None` for an attribute whose value is the empty string, but condition in the spec is "if the element has no src attribute specified".

---

*[components/script/dom/htmliframeelement.rs, line 190 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4XB5AiDvfXZGT9LHpz:-K4XB5AiDvfXZGT9LHq-:284814466) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/htmliframeelement.rs#L190)):*
`main_thread_script_chan` would avoid a virtual call here.

---

*[components/script/dom/htmliframeelement.rs, line 191 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4XAvrZLapPXhQF-Atp:-K4XAvrZLapPXhQF-Atq:-1786335868) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/htmliframeelement.rs#L191)):*
Can this fail? If so, in what circumstances, and is it okay to just drop the message in those cases?

---

*[components/script/dom/htmliframeelement.rs, line 496 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4XBR0Po0YHo4Rn58iR:-K4XBR0Po0YHo4Rn58iS:1287603323) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/htmliframeelement.rs#L496)):*
Do you know if we have a test for this change (removing the `src` attribute) specifically?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8600#-:-K4XM1rXvkac9hBNk7Kn:505944163)*

**Comment by Ms2ger** [comment]
I don't quite understand what's going on in `constellation.rs`, would appreciate some more explanation about that.

---

Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[components/compositing/constellation.rs, line 787 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K5pM3K5w-PhiLZ7Z5pe:-K5pM3K5w-PhiLZ7Z5pf:649159059) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/compositing/constellation.rs#L787)):*
`unwrap_or_else`, I think.

---

*[components/compositing/pipeline.rs, line 177 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K5pMsub5cuDLxByFLgF:-K5pMsucu-Q36iAv-9uU:-878975945) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/compositing/pipeline.rs#L177)):*
Should this message not be sent on the replacement sender?

---

*[components/script/script_task.rs, line 995 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K5pOH2vjA6C79WQdxrY:-K5pOH2wupy4LMQLvZN6:-1892572541) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/script_task.rs#L995)):*
Looks like there's two callers to `handle_msg_from_constellation` now: one that always passes `AttachLayout`, and one that never does. Should we split `AttachLayout` out of the enum?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8600#-:-K5pMJHt7V0ELwCfaWCm:63060141)*

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmliframeelement.rs, line 230 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K5pQITadh9IXlmeMVwj:-K5pQITadh9IXlmeMVwk:1840548519) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/htmliframeelement.rs#L230)):*
Just now, an algorithm with actual steps materialized behind that link. Could you add step numbers as appropriate?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8600)*

**Comment by jdm** [comment]
Only rebased; no comments addressed.

**Comment by jdm** [comment]
Review status: 19 of 35 files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[components/compositing/pipeline.rs, line 177 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K5pMsub5cuDLxByFLgF:-K7Y74Kx81bRnkQVaed-:1046127303) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/compositing/pipeline.rs#L177)):*
No; the replacement sender is the one which will replace the sender after the initial AttachLayout message, ie. the regular script thread channel.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 99 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8600#-K48kYaeDtE9MK3wuQV6:-K7Y7MgB2EAKGUo8f5ip:-1207223074) ([raw file](https://github.com/servo/servo/blob/41097ce4b3c41945b68bafc14c88ce0763e0a885/components/script/dom/dedicatedworkerglobalscope.rs#L99)):*
Doesn't compile.

---

*[components/script/dom/htmliframeelement.rs, line 506 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4CZyvDjGb3SmV0xy-9:-K7YXRJIKdllU9DDAK_i:1445594643) ([raw file](https://github.com/servo/servo/blob/acad2db1023b9c2003764b8798f059a3500e5b1a/components/script/dom/htmliframeelement.rs#L506)):*
I think this is confusing since this doesn't implement those steps.

---

*[components/script/dom/htmliframeelement.rs, line 190 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4XB5AiDvfXZGT9LHpz:-K7YFxdfFyiELQY-8Fnd:-1372246055) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/htmliframeelement.rs#L190)):*
This now reflects the intention of the spec, so the virtual call can't be avoided.

---

*[components/script/dom/htmliframeelement.rs, line 496 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4XBR0Po0YHo4Rn58iR:-K7YX15o10dS9bSJ97DA:-1033313544) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/htmliframeelement.rs#L496)):*
I wrote a test and both Firefox and Chrome failed it.

---

*[components/script/script_task.rs, line 995 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K5pOH2vjA6C79WQdxrY:-K7YXwsvUC6azaxDdqxg:-756026115) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/script_task.rs#L995)):*
On the surface this makes sense, but it means creating a separate channel for these messages and losing guaranteed message ordering due to the use of select.

---

*[tests/wpt/metadata/dom/nodes/Element-matches.html.ini, line 58 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JhCJoehdCwl7ncwsL:-K7YYVVr_f6qbTe6UiXh:1109262965) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/tests/wpt/metadata/dom/nodes/Element-matches.html.ini#L58)):*
There's an async_test in this file that does stuff with iframes. It's now able to report new failures due to these changes.

---

*[tests/wpt/metadata/dom/nodes/ParentNode-querySelector-All.html.ini, line 250 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JhG8bADRMCLvdidOx:-K7YYlSAhhDHeZYLvqNQ:1012262075) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/tests/wpt/metadata/dom/nodes/ParentNode-querySelector-All.html.ini#L250)):*
This runs the exact same test in an iframe that fails in Element-matches.html.

---

*[tests/wpt/metadata/dom/ranges/Range-surroundContents.html.ini, line 0 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JhvkuxXxGQ78mcy6M:-K7Y_C66PIX4Q_-5nQM3:510855340) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/tests/wpt/metadata/dom/ranges/Range-surroundContents.html.ini#L0)):*
This is caused by the onload event firing for the about:blank, when the test doesn't expect that. This is potentially an error in my implementation. I've filed https://github.com/whatwg/html/issues/490 because the spec's description doesn't match any existing browser behaviour.

---

*[components/script/dom/browsercontext.rs, line 117 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4J_ZVgOvIhsyzRSVLH:-K7XxE3W0i3dOr6Yjtgx:87697548) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/browsercontext.rs#L117)):*
This limits the potential exposure of cross-origin objects by being more explicit.

---

*[components/script/dom/browsercontext.rs, line 119 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JgQIWpMd_erlnMonS:-K7Xx8QVWSieTya-sVO_:-1536196062) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/components/script/dom/browsercontext.rs#L119)):*
Cross-origin contentDocument.

---

*[tests/wpt/metadata/html/browsers/browsing-the-web/read-text/load-text-plain.html.ini, line 8 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8600#-K4JiQiDgQoRBpt5wFbb:-K7Yiek9ZY4O1adhNO6n:-160418888) ([raw file](https://github.com/servo/servo/blob/05786d62ad2299baa48e47778a695479c3075f3e/tests/wpt/metadata/html/browsers/browsing-the-web/read-text/load-text-plain.html.ini#L8)):*
Confusing why the test claims to pass now, but this is exacerbated by the load event confusion I mentioned earlier.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8600)*

**Comment by jdm** [comment]
I verified your previous rebase, then rebased it again.

**Comment by jdm** [comment]
I think I meant to include the test in https://github.com/w3c/web-platform-tests/issues/2615 with this PR, but I should double check.

**Comment by jdm** [comment]
@Ms2ger What would make this easier to review? I'm getting a bit tired of the status quo.

**Comment by notriddle** [comment]
@jdm What's the status on this?

**Comment by jdm** [comment]
@notriddle The status is unchanged - @Ms2ger is on the hook to review it.

**Comment by jdm** [comment]
Actually, if @Ms2ger is looking for something to occupy the rest of this quarter...

**Comment by jdm** [comment]
```
08:08 Ms2ger: jdm, I had another look at your about:blank PR, and tried to rewrite it without the sync sender dance, but got stuck on the PaintThread
08:09 * jdm wonders how PaintThread is involved
08:09 Ms2ger: jdm, though hopefully wr will land soon, and the paint thread will be gone...
08:09 jdm: ooh, interesting point
08:09 Ms2ger: jdm, I'm trying to create the layout thread without talking to the constellation
08:10 jdm: right, that sounds familiar
08:10 Ms2ger: So I'm hoping we could make it work once wr lands
```
Webrender has landed, but I don't think we've gotten rid of the non-WR code yet. It is not clear to me how valuable it is to spend time reviewing these changes until we get a chance to see how to post-webrender world affects the design space.

**Comment by Ms2ger** [comment]
The code I was working on is in https://github.com/Ms2ger/servo/tree/my-loadexperiments

I'm getting confused why the nested event loop in `start_page_load` is necessary; I'll try to look at that soonish.

**Comment by jdm** [comment]
Do you mean `start_page_load_about_blank`? That's necessary to process the network notifications for fetching about:blank, right?

**Comment by jdm** [comment]
Redesigned in #13996.

**Pull request closed without merging**
