### PR TITLE
Implemented Document.currentScript

### PR DESCRIPTION
**Pull request by luniv**
Implements https://github.com/servo/servo/issues/5057 (Document.currentScript)

### CODE REVIEW

**Comment by jdm** [comment]
Exciting! There are comments on the Critic review; make sure to click the 'sign in' link so you get future updates by email.

**Comment by luniv** [comment]
Just realized that I have the wrong email in the commits (defaulted to my work email). Is there a way to to rewrite & push the commits without breaking the code review?

**Comment by jdm** [comment]
Nope. Just leave it until the review is complete, and then you can force push with the amended author.

**Comment by Ms2ger** [comment]
@luniv: good to go; please squash the two commits and update your email address.

**Comment by luniv** [comment]
Done!

**Comment by Ms2ger** [comment]
@luniv: I'm afraid it needs a rebase too

**Comment by luniv** [comment]
Rebased.

**Comment by luniv** [comment]
Looks like I forgot to remove some expected fails from html/dom/interfaces.html.

Do I update the commit and just push it again?

**Comment by jdm** [comment]
Yep, just amend the commit and force push.

**Comment by luniv** [comment]
Done.

**Comment by Ms2ger** [comment]
\o/ Thanks!

**Pull request closed without merging**
