### PR TITLE
Add window icon on X11 and Windows

### LINKED ISSUE #20761: Servo icon does not appear in application window
A generic icon is shown instead of the Servo icon.

Window icon

Tested in Windows 10.

### PR DESCRIPTION
**Pull request by UK992**
---

- [X] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #20761

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21087)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by CYBAI** [comment]
```
Checking files for tidiness...

./Cargo.lock:1: duplicate versions for package `wayland-protocols`
	The following packages depend on version 0.12.5 from 'crates.io':
		wayland-window
		winit
	The following packages depend on version 0.20.10 from 'crates.io':
		smithay-client-toolkit

./Cargo.lock:1: duplicate versions for package `core-graphics`
	The following packages depend on version 0.13.0 from 'crates.io':
		cocoa
		core-text
		gfx
		glutin
		webrender
		webrender_api
		winit
	The following packages depend on version 0.14.0 from 'crates.io':
		cocoa
		glutin
		winit

./Cargo.lock:1: duplicate versions for package `winit`
	The following packages depend on version 0.11.3 from 'crates.io':
		glutin
	The following packages depend on version 0.15.0 from 'crates.io':
		glutin
		servo

./Cargo.lock:1: duplicate versions for package `tempfile`
	The following packages depend on version 2.2.0 from 'crates.io':
		wayland-window
	The following packages depend on version 3.0.2 from 'crates.io':
		smithay-client-toolkit

./Cargo.lock:1: duplicate versions for package `inflate`
	The following packages depend on version 0.3.3 from 'crates.io':
		png
	The following packages depend on version 0.4.2 from 'crates.io':
		png

./Cargo.lock:1: duplicate versions for package `core-foundation`
	The following packages depend on version 0.5.1 from 'crates.io':
		core-graphics
		core-text
		gfx
		glutin
		io-surface
		offscreen_gl_context
		webrender
		webrender_api
		winit
	The following packages depend on version 0.6.0 from 'crates.io':
		core-graphics
		glutin
		winit

./Cargo.lock:1: duplicate versions for package `wayland-sys`
	The following packages depend on version 0.12.5 from 'crates.io':
		wayland-client
		wayland-protocols
	The following packages depend on version 0.20.10 from 'crates.io':
		wayland-client
		wayland-commons
		wayland-protocols

./Cargo.lock:1: duplicate versions for package `png`
	The following packages depend on version 0.11.0 from 'crates.io':
		image
	The following packages depend on version 0.12.0 from 'crates.io':
		image

./Cargo.lock:1: duplicate versions for package `core-foundation-sys`
	The following packages depend on version 0.5.1 from 'crates.io':
		core-foundation
	The following packages depend on version 0.6.0 from 'crates.io':
		core-foundation

./Cargo.lock:1: duplicate versions for package `wayland-scanner`
	The following packages depend on version 0.12.5 from 'crates.io':
		wayland-client
		wayland-protocols
	The following packages depend on version 0.20.10 from 'crates.io':
		wayland-client
		wayland-protocols

./Cargo.lock:1: duplicate versions for package `glutin`
	The following packages depend on version 0.13.1 from 'crates.io':
		servo-skia
	The following packages depend on version 0.16.0 from 'crates.io':
		servo

./Cargo.lock:1: duplicate versions for package `image`
	The following packages depend on version 0.18.0 from 'crates.io':
		compositing
		net_traits
		script
		webdriver_server
		webrender
	The following packages depend on version 0.19.0 from 'crates.io':
		winit

./Cargo.lock:1: duplicate versions for package `wayland-client`
	The following packages depend on version 0.12.5 from 'crates.io':
		glutin
		wayland-kbd
		wayland-protocols
		wayland-window
		winit
	The following packages depend on version 0.20.10 from 'crates.io':
		glutin
		smithay-client-toolkit
		wayland-protocols
		winit

./Cargo.lock:1: duplicate versions for package `cocoa`
	The following packages depend on version 0.14.0 from 'crates.io':
		glutin
		winit
	The following packages depend on version 0.15.0 from 'crates.io':
		glutin
		winit

./Cargo.lock:1: duplicate versions for package `gif`
	The following packages depend on version 0.10.0 from 'crates.io':
		image
	The following packages depend on version 0.9.1 from 'crates.io':
		image

Running the dependency licensing lint...
```

**Comment by UK992** [comment]
updated "servo-skia" need to be published, to reduce number of duplicated packages.

**Comment by atouchet** [comment]
@UK992 would it be possible to update straight to winit 0.16/glutin 0.17? That would help fix a couple of additional issues (see: https://github.com/servo/servo/issues/20505#issuecomment-401513634, https://github.com/servo/servo/pull/21094#issuecomment-401447878).

**Comment by UK992** [comment]
Updated to winit 0.16 and glutin 0.17, I cherry-picked API changes commits from @kwonoj.

**Comment by UK992** [comment]
@asajeffrey there is a patch to link `servo-skia` to my fork

**Comment by SimonSapin** [comment]
```
error[E0119]: conflicting implementations of trait `platform::platform::x11::util::format::Formattable` for type `u8`:
  --> /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.16.0/src/platform/linux/x11/util/format.rs:54:1
   |
53 | impl Formattable for c_char { const FORMAT: Format = Format::Char; }
   | --------------------------- first implementation here
54 | impl Formattable for c_uchar { const FORMAT: Format = Format::Char; }
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `u8`
```

**Comment by SimonSapin** [comment]
`c_char` probably needs to be `c_schar` instead, in https://github.com/tomaka/winit/blob/v0.16.0/src/platform/linux/x11/util/format.rs#L53-L54

**Comment by asajeffrey** [comment]
Oops, hadn't noticed the servo-skia patch. Can we remove that?

**Comment by UK992** [comment]
I will removed it, its only for passing tidy, Im waiting for latest servo-skia to be published.

**Comment by paulrouget** [comment]
> Im waiting for latest servo-skia to be published.

I just published it.

**Comment by atouchet** [comment]
winit 0.16.1 is now out.

**Pull request merged**
