### PR TITLE
Stop storing CSS errors on the Document.

### PR DESCRIPTION
**Pull request by Ms2ger**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy --faster` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because removing dead code

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. 

They are never read.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11366)

### CODE REVIEW

**Comment by jdm** [comment]
The reason this cache exists is to report them when a devtools client connects. I'd rather not remove this just to re-add it at some point in the future.

**Comment by nox** [comment]
Honestly we will have no idea when that will happen, and in which shape the information will be presented. IIRC you are first supposed to send a list of sources, and then use their IDs to communicate errors happening in them. This code will probably need to be rewritten, so I'm not sure there is any point into keeping them.

**Comment by nox** [comment]
And I'm pretty sure the errors should be stored in the console server itself, from where they will be presented if any remote debugging connection is opened.

**Comment by SimonSapin** [comment]
r=me on the diff

**Comment by jdm** [comment]
OK, I won't fight this.

**Comment by mbrubeck** [comment]
@bors-servo retry

* infra

**Pull request merged**
