### PR TITLE
add a new command line flag --profile-dir [path] that stores path and creates directory if it does not exist

### PR DESCRIPTION
**Pull request by ddefisher**
For the Implement HTTP authorization UI and persistent sessions student project.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10084)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes +S-needs-squash 
Good work! I've made some suggestions to improve code clarity, but otherwise this looks like what I expected :) Please also [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) all the commits into one, along with the changes I've requested.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/util/opts.rs, line 191 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10084#-KDAtdCXYUqXggW_M7YK:-KDAtdCXYUqXggW_M7YL:-1982729920) ([raw file](https://github.com/servo/servo/blob/5c7983afbd2386ad4293e21fcea03ee6e24b6ca3/components/util/opts.rs#L191)):*
`/// Directory path for persistent session`

---

*[components/util/opts.rs, line 197 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10084#-KDAt_GGM5JnZroriX4M:-KDAt_GGM5JnZroriX4N:1034887602) ([raw file](https://github.com/servo/servo/blob/5c7983afbd2386ad4293e21fcea03ee6e24b6ca3/components/util/opts.rs#L197)):*
nit: remove these extra spaces.

---

*[components/util/opts.rs, line 554 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10084#-KDAu0u8wc6ILFpR7QOf:-KDAu0u8wc6ILFpR7QOg:-117499168) ([raw file](https://github.com/servo/servo/blob/5c7983afbd2386ad4293e21fcea03ee6e24b6ca3/components/util/opts.rs#L554)):*
This should be `optopt` instead, since we always need an argument.

---

*[components/util/opts.rs, line 569 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10084#-KDAtk2BtpgmUbmDNagW:-KDAtk2BtpgmUbmDNagX:115176163) ([raw file](https://github.com/servo/servo/blob/5c7983afbd2386ad4293e21fcea03ee6e24b6ca3/components/util/opts.rs#L569)):*
`if let Some(ref profile_dir) = opt_match.opt_str("profile-dir") {
    if let Err(why) = fs::create_dir_all(profile_dir) {
        error!("Couldn't create/open {:?}: {:?}", Path::new(profile_dir).to_string_lossy(), why);
    }
}`

---

*[components/util/opts.rs, line 769 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10084#-KDAv4dwk5c7NEHPf-5T:-KDAv4dxpkRawtp0aCJ3:1612688214) ([raw file](https://github.com/servo/servo/blob/5c7983afbd2386ad4293e21fcea03ee6e24b6ca3/components/util/opts.rs#L769)):*
`opt_str`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10084#-:-KDAv8OLATqVG5veUEWw:-1015892559)*

**Comment by KiChjang** [comment]
@DDEFISHER Why is this closed?

**Comment by DDEFISHER** [comment]
Sorry I closed the pull request I was having a hard time squashing the commits together because I made a mistake of pulling in the middle of them so I had a giant merge between them.  I was just going to refork servo and make the changes again since they are small.  Sorry again.

**Comment by KiChjang** [comment]
No need to close next time. `git reset --hard` should do the trick.

**Comment by DDEFISHER** [comment]
I will remember that. Thanks.

**Pull request closed without merging**
