### PR TITLE
Replace Syntax with TypeError in bluetoothuuid.rs

### PR DESCRIPTION
**Pull request by zakorgy**
1. Replacing `SyntaxError` with `TypeError` in `bluetoothuuid.rs` due to the specification change.
This indicates changes in the existing tests.
The error strings are from the chromium implementation.
2. We missed out a `$` character from the end of the `VALID_UUID_REGEX` global variable.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes OR

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14429)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
One failure was #14380, but there's two other...

      ▶ Unexpected subtest result in /_mozilla/mozilla/bluetooth/getDescriptor/blocklisted-descriptor.html:
      │ FAIL [expected PASS] The descriptor is blocklisted.
      └   → assert_throws: function "function () { throw e }" threw object "TypeError: Invalid Descriptor name : '07711111-6104-0970-7011-1107105110aaa'.
    It must be a valid UUID alias (e.g. 0x1234), UUID (lowercase hex characters e.g. '00001234-0000-1000-8000-00805f9b34fb'),
    or recognized standard name from https://developer.bluetooth.org/gatt/descriptors/Pages/DescriptorsHomePage.aspx
    e.g. 'gatt.characteristic_presentation_format'." that is not a DOMException SecurityError: property "code" is equal to undefined, expected 18

      ▶ Unexpected subtest result in /_mozilla/mozilla/bluetooth/getDescriptors/blocklisted-descriptors-with-uuid.html:
      │ FAIL [expected PASS] The descriptor is blocklisted. Should reject with SecurityError.
      └   → assert_throws: function "function () { throw e }" threw object "TypeError: Invalid Descriptor name : '07711111-6104-0970-7011-1107105110aaa'.
    It must be a valid UUID alias (e.g. 0x1234), UUID (lowercase hex characters e.g. '00001234-0000-1000-8000-00805f9b34fb'),
    or recognized standard name from https://developer.bluetooth.org/gatt/descriptors/Pages/DescriptorsHomePage.aspx
    e.g. 'gatt.characteristic_presentation_format'." that is not a DOMException SecurityError: property "code" is equal to undefined, expected 18

**Comment by dati91** [comment]
It seems like the regex fix brought out a typo where a uuid's last part is 13 char length instead of 12.
I will send a fix first thing in the morning.

**Pull request merged**
