### PR TITLE
Disable LLVM assertions by default, on supported platforms

### LINKED ISSUE #15548: Use rustc builds without asserts
The Rust team is making these builds available in the s3 bucket, so we need to modify the mach bootstrap command to fetch the appropriate URL to retrieve them. This is blocked until https://github.com/rust-lang/rust/pull/39754 is merged.

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/servo/servo/pull/15559#issuecomment-280003926

> With an empty incremental compilation cache (or, presumably, with incremental compilation disabled), LLVM assertions add 16% to the compilation time in debug mode, 53% (!) in release mode.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15548 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15564)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I think we should do this, but have a `.servobuild` for *some* CI jobs that enables LLVM assertions back, since these assertions can help find rustc bugs. Maybe for debug CI builds, but not the release ones which could use the speed improvement.

CC @jdm @mbrubeck @nox

**Comment by SimonSapin** [comment]
What about an environment variable? We could have `python/servo/*.py` decide the default based on that.

**Comment by SimonSapin** [comment]
@metajack suggets a command-line flag, I’ll try that.

**Comment by SimonSapin** [comment]
That’s annoying because the default config (and the path to the rustc directory) is set before `mach` parses the command line. So I used the `env` command in `buildbot_steps.yml` for the `linux-dev` builder to set an environment variable. I’d have done the same for the `mac-dev` builder, but we don’t have one. I don’t know if `env` (or equivalent) exists on Windows.

@bors-servo try

**Comment by SimonSapin** [comment]
```
Download failed (404): Not Found - https://s3.amazonaws.com/rust-lang-ci/rustc-builds-alt/025c328bf5ab336ff708e62a59292298dc1bc089/rustc-nightly-x86_64-pc-windows-gnu.tar.gz
```

https://github.com/rust-lang/rust/pull/39754
> This commit adds three new builders, one OSX, one Linux, and one MSVC, 

@bors-servo try

**Comment by SimonSapin** [comment]
> I’d have done the same for the mac-dev builder, but we don’t have one.

Oh, wait, we do. It’s called `mac-dev-unit`. (I was grepping for `dev:` in the YAML file.)

**Comment by SimonSapin** [comment]
`host_platform()` vs `host_triple()`

@bors-servo try

**Comment by SimonSapin** [comment]
Before this PR, `mac-rel-css` is the longest build at 52~55 minutes. With this PR `mac-rel-css` is still the longest, but now takes 43 minutes.

r? @metajack

**Comment by Ms2ger** [comment]
@bors-servo r+

I don't like env variables, but I guess this is fine...

**Pull request merged**
