### PR TITLE
[do not merge] Trial changes for improving CSS test stability

### PR DESCRIPTION
**Pull request by jgraham**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6244)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@homu: try

**Comment by Manishearth** [comment]
```
Submodule 'support/android-rs-glue' (https://github.com/tomaka/android-rs-glue) registered for path 'support/android-rs-glue'
Cloning into 'support/android-rs-glue'...
Submodule path 'support/android-rs-glue': checked out '34f588aace4d05ce42f4ca605d5470df8fdd236e'
Unknown flag: '--dev'

Usage:
    cargo build [options]
Build completed in 0.05s
program finished with exit code 1
elapsedTime=2.858621
```

**Comment by jdm** [comment]
I wonder if that's a result of #6232?

**Comment by Manishearth** [comment]
It's the result of homu deciding to merge PRs from January

**Pull request closed without merging**
