### PR TITLE
stylo: make fill-opacity animatable

### PR DESCRIPTION
**Pull request by chenpighead**
This is just the servo part change. The test part will be landed in gecko directly.

Gecko bug: [Bug 1369624](https://bugzilla.mozilla.org/show_bug.cgi?id=1369624)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17227)

### CODE REVIEW

**Comment by chenpighead** [comment]
stylo try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=f4ff527bff7c

**Comment by jdm** [comment]
That is #17230.

**Pull request merged**
