### PR TITLE
Implement window.parent for iframes.

### PR DESCRIPTION
**Pull request by glennw**

### CODE REVIEW

**Comment by glennw** [comment]
@jdm or @Ms2ger I'm just trying to find my way around the DOM code. Is this patch a reasonable approach or is there a much better way to implement window.parent?

**Comment by jdm** [comment]
This design seems reasonable, although it's tempting to look for ways to store a parent browser context, rather than a parent window.

**Comment by jdm** [comment]
Squash!

**Comment by glennw** [comment]
Squashed and rebased!

**Pull request merged**
