### PR TITLE
mozbrowsericonchange event (Browser API)

### LINKED ISSUE #8347: Support mozbrowsericonchange event (Browser API)

### PR DESCRIPTION
**Pull request by paulrouget**
fixes #8347

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8449)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 4 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmllinkelement.rs, line 129 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lfF6njb8vV0ggvrEd)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L129)):</sup>
We should use `attr.value()` instead of href.


---

<sup>**[components/script/dom/htmllinkelement.rs, line 133 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lg5-LhyU8Za6ZZPqu)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L133)):</sup>
Should this be sizes?


---

<sup>**[components/script/dom/htmllinkelement.rs, line 136 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lfz7uWg98kd5PjT9w)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L136)):</sup>
This can be `if let`.


---

<sup>**[components/script/dom/htmllinkelement.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lg7b0xZZBY4OphJrf)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L139)):</sup>
Let's use `attr` :)


---

<sup>**[components/script/dom/htmllinkelement.rs, line 239 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lgNhy3rXFg682xsKx)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L239)):</sup>
These should be `&str` instead of `&String`; callers will probably need `&*`.


---

<sup>**[components/script/dom/htmllinkelement.rs, line 248 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lgUvir1owEfWgP5v2)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L248)):</sup>
Please replace this with a call to `document.trigger_mozbrowser_event`.


---

<sup>**[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsericonchange_event.html, line 24 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lhVVcHKHI8RV2PH_C)** ([raw file](https://github.com/servo/servo/blob/fa2106034696b09e12359fae44f893f51f1dd1d6/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsericonchange_event.html#L24)):</sup>
Use `t.step_func(function ...)`.


---

<sup>**[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsericonchange_event.html, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lhLw2qx8gC7de0tWI)** ([raw file](https://github.com/servo/servo/blob/fa2106034696b09e12359fae44f893f51f1dd1d6/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsericonchange_event.html#L34)):</sup>
I don't understand this - don't we want to test that the events appear in the order we expect?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by jdm** [comment]
```
/home/travis/build/servo/servo/components/script/dom/htmllinkelement.rs:128:58: 128:72 error: Unknown static atom sizes

/home/travis/build/servo/servo/components/script/dom/htmllinkelement.rs:128                     let sizes = get_attr(self.upcast(), &atom!("sizes"));

                                                                                                                                     ^~~~~~~~~~~~~~

/home/travis/build/servo/servo/components/script/dom/htmllinkelement.rs:138:66: 138:80 error: Unknown static atom sizes

/home/travis/build/servo/servo/components/script/dom/htmllinkelement.rs:138                             let sizes = get_attr(self.upcast(), &atom!("sizes"));

                                                                                                                                             ^~~~~~~~~~~~~~

/home/travis/build/servo/servo/components/script/dom/htmllinkelement.rs:172:44: 172:58 error: Unknown static atom sizes

/home/travis/build/servo/servo/components/script/dom/htmllinkelement.rs:172             let sizes = get_attr(element, &atom!("sizes"));

                                                                                                                       ^~~~~~~~~~~~~~

error: aborting due to 3 previous errors
```
We can use `Atom::from_slice("sizes")` instead of the `atom!` macro.

**Comment by Ms2ger** [comment]
And you should add `sizes` to <https://github.com/servo/string-cache/blob/master/shared/static_atom_list.rs>. Pulling that change into Servo is a bunch of work, so feel free to file a followup to actually use the static atom here, rather than blocking this PR on it.

**Comment by paulrouget** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmllinkelement.rs, line 136 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lfz7uWg98kd5PjT9w)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L136)):</sup>
how so? by checking `is_some()` later and unwrap?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by paulrouget** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmllinkelement.rs, line 136 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lfz7uWg98kd5PjT9w)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L136)):</sup>
Oh, I think I got it. `if let Some() = …`. This will work. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by paulrouget** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmllinkelement.rs, line 239 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lgNhy3rXFg682xsKx)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L239)):</sup>
`get_attr` returns a `Option<String>`. `MozBrowserEvent` are made of `String` (looking at `MozBrowserEvent::TitleChange` and `MozBrowserEvent::LocationChange`) and eventually converted to `DOMString`. Can you explain when `str` should be used and why it should be used here? 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmllinkelement.rs, line 239 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lgNhy3rXFg682xsKx)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L239)):</sup>
`&String` is the useless cousin of `&str`, since it requires an extra pointer dereference to reach the actual string value and doesn't provide any different interface since it's not mutable. `&*some_String_value` yields `&str` due to the `Deref` implementation for `String`. `String` means "I own this string's data", `&str` means "I am borrowing this string's data", and "&String" means "I am borrowing this string's data inefficiently".


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmllinkelement.rs, line 239 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lgNhy3rXFg682xsKx)** ([raw file](https://github.com/servo/servo/blob/e060ba25baea8138f64c9655820308bc738adf0f/components/script/dom/htmllinkelement.rs#L239)):</sup>
It's the same as vectors - `Vec<T>` is ownership, `&[T]` is a slice, and `&Vec<T>` is pointless, since it's partway to a slice and can't be mutated.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by paulrouget** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsericonchange_event.html, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8449#-K2lhLw2qx8gC7de0tWI)** ([raw file](https://github.com/servo/servo/blob/fa2106034696b09e12359fae44f893f51f1dd1d6/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsericonchange_event.html#L34)):</sup>
You're right.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by paulrouget** [comment]
https://github.com/servo/string-cache/pull/120


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by jdm** [comment]
Thanks for doing this work!

**Comment by larsbergstrom** [comment]
@paulrouget My apologies for breaking the builder and leaving you stuck with another rebase after other stuff landed ahead of you!

**Comment by paulrouget** [comment]
```
htmliframeelement.rs:147:34: 147:43 error: cannot invoke tuple struct constructor with private fields [E0450]
htmliframeelement.rs:147                 let event_name = DOMString(event.name().to_owned());
                                                          ^~~~~~~~~
htmliframeelement.rs:248:31: 248:40 error: cannot invoke tuple struct constructor with private fields [E0450]
htmliframeelement.rs:248                     rel: Some(DOMString(rel)),
                                                       ^~~~~~~~~
htmliframeelement.rs:249:32: 249:41 error: cannot invoke tuple struct constructor with private fields [E0450]
htmliframeelement.rs:249                     href: Some(DOMString(href)),
                                                        ^~~~~~~~~
htmliframeelement.rs:250:33: 250:42 error: cannot invoke tuple struct constructor with private fields [E0450]
htmliframeelement.rs:250                     sizes: Some(DOMString(sizes)),
```

**Comment by paulrouget** [comment]
I see: https://github.com/servo/servo/pull/8477

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8449)

**Comment by jdm** [comment]
@bors-servo: retry
* #8487

**Pull request merged**
