### PR TITLE
Remove mozjs dep from malloc_size_of.

### PR DESCRIPTION
**Pull request by jdm**
This makes making local changes to mozjs_sys much more frustrating than it should be, and blocks merging #22130.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23299)

### CODE REVIEW

**Comment by CYBAI** [comment]
```rust
error[E0277]: the trait bound `mozjs_sys::jsgc::Heap<*mut js::jsapi::JSObject>: malloc_size_of::MallocSizeOf` is not satisfied
  --> components/script/dom/xrrigidtransform.rs:22:1
   |
22 | #[dom_struct]
   | ^^^^^^^^^^^^^ the trait `malloc_size_of::MallocSizeOf` is not implemented for `mozjs_sys::jsgc::Heap<*mut js::jsapi::JSObject>`
   |
   = note: required by `malloc_size_of::MallocSizeOf::size_of`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0277`.
error: Could not compile `script`.
To learn more, run the command again with --verbose.
The command "./mach test-unit" exited with 101.
```

**Comment by jdm** [comment]
Fixed.

**Pull request merged**
