### PR TITLE
Update servo-media

### PR DESCRIPTION
**Pull request by asajeffrey**
Update the servo-media crate and its dependencies.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it's updating a dependency

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24236)

### CODE REVIEW

**Comment by CYBAI** [comment]
@bors-servo retry

- this looks like intermittent failure to me 🤔

```
  ▶ Unexpected subtest result in /css/cssom-view/offsetTopLeft-border-box.html:
  │ FAIL [expected PASS] container: 0
  │   → assert_equals: offsetTop expected 2 but got 0
  │ FAIL [expected PASS] container: 1
  │   → assert_equals: offsetTop expected 2 but got 0
  │ 
  │ onload/</<@http://web-platform.test:8000/css/cssom-view/offsetTopLeft-border-box.html:55:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  │ onload/<@http://web-platform.test:8000/css/cssom-view/offsetTopLeft-border-box.html:53:5
  └ onload@http://web-platform.test:8000/css/cssom-view/offsetTopLeft-border-box.html:52:40
```

**Comment by asajeffrey** [comment]
Yes, I tried and failed to find an appropriate issue.

**Comment by CYBAI** [comment]
> Yes, I tried and failed to find an appropriate issue.

Let me file one then :D

**Comment by CYBAI** [comment]
#24237

**Pull request merged**
