### PR TITLE
layout: Modify styles for replaced content as appropriate during incremental flow construction.

### PR DESCRIPTION
**Pull request by pcwalton**
Fixes jumpiness on lots of Web sites.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6492)

### CODE REVIEW

**Comment by jdm** [comment]
This looks like insert-inline-in-blocks-n-inlines-end-001.htm was incorrectly marked as passing now...

**Comment by jdm** [comment]
```
/css21_dev/html4/insert-inline-in-blocks-n-inlines-end-001.htm
--------------------------------------------------------------
PASS expected FAIL [Parent]
```
So maybe it intermittently passes now. That's fun.

**Comment by pcwalton** [comment]
@jdm Maybe platform specific? Can I set platform specific test expectations?

**Comment by jdm** [comment]
Not as far as I know.

**Comment by pcwalton** [comment]
I believe I have fixed that WPT problem.

r? @jdm (or whoever)

**Comment by pcwalton** [comment]
Just the "round out when snapping rects" and "make the output of flow tree dumping easier to read" commits need review.

**Comment by pcwalton** [comment]
@bors-servo: r=mbrubeck

(gw reviewed this on IRC)

**Comment by jdm** [comment]
```
/css21_dev/html4/position-relative-035.htm
------------------------------------------
FAIL [Parent]
```

**Comment by jdm** [comment]
Eep.
```
/css21_dev/html4/block-in-inline-001.htm
----------------------------------------
FAIL [Parent]
/css21_dev/html4/block-in-inline-002.htm
----------------------------------------
FAIL [Parent]
```

**Comment by pcwalton** [comment]
Platform specific failure again, I guess?

**Comment by pcwalton** [comment]
I started ignoring the failing tests. They seem to depend on the height above the baseline being equal to the ascent of the font in order to avoid a pixel or two of red showing through. This is not always the case in Gecko or Servo, so they fail in these two browsers. I believe the problem is with the test.

I think they were passing before because the incorrect rounding of rects just happened to make them pass, though the logic that they were testing was never correct—another reason to ignore them.

r? @mbrubeck

**Comment by mbrubeck** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 23 of 23 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6492)

**Pull request merged**
