### PR TITLE
Never blockify display: none

### PR DESCRIPTION
**Pull request by upsuper**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15056)

### CODE REVIEW

**Comment by emilio** [comment]
Oh, wow, that's nasty.

@bors-servo r+

**Comment by emilio** [comment]
@bors-servo r-,

Actually, could you write a simple test for this?

**Comment by upsuper** [comment]
A "simple" test for this single case is easy, but I guess we really want a more complete test to cover all blockify cases and all display values, which is harder :/

**Comment by upsuper** [comment]
Gecko has "layout/style/test/test_flexbox_child_display_values.xhtml" for blockifying behavior inside flexbox, which can probably be migrated to wpt. But there are other cases, e.g. floating, absolutely-positioning, which also need blockifying.

**Comment by emilio** [comment]
I guess... Probably there are some tests for this already? I added some for display: contents on absolutely positioned elements and similar stuff to CSSWG, but of course we don't support them yet so that's kinda useless...

Let's see:

@bors-servo try

If it's blocking you hard or something, feel free to r=me directly, and file an issue for the test. Shouldn't be hard and could be a good easy issue?

**Comment by upsuper** [comment]
It's not blocking me. I just feels silly to file an issue for this trivial code change and ask other people to fix, given I've found how to fix it. But well, I didn't consider the cost of adding test... so I probably should have filed an issue instead of a pr :)

**Comment by upsuper** [comment]
Looks like @bors-servo doesn't recognize r- after r+... or there is some bug.

**Pull request merged**
