### PR TITLE
Add some SSH keys to tc-mac workers

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23412)

### CODE REVIEW

**Comment by CYBAI** [comment]
Travis and TC complained about tidy 👀

```
Checking files for tidiness...
./etc/taskcluster/macos/modules/pillar/ssh_keys.py:7: E302 expected 2 blank lines, found 1
```

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
