### PR TITLE
Multiple concurrent top-level browsing contexts

### PR DESCRIPTION
**Pull request by delan**
This patch improves support for multiple top-level browsing contexts aka “webviews”.

We add several messages that allow the embedder to show, hide, move, and resize webviews in the compositor, focus and unfocus webviews in the constellation, and notify the embedder when painting order and focus changes.

These changes can be used to create a multiple-document interface, like we do in #30785.

Parts of this patch have been broken out into:

- [x] #30767
- [x] #30840
- [x] #30841
- [x] #30842
- [x] #31417

<details><summary>Original todo list</summary>

- [x] painting
    - [x] egui then servo, naïve
    - [x] ~~egui then servo or servo then egui, with [stencil](https://learnopengl.com/Advanced-OpenGL/Stencil-testing)~~ — may need egui and webrender modifications
    - [x] interleave egui and servo
    - future: separate webrender documents and partial present?
- [ ] rework:
    - [x] IOCompositor.root_content_pipeline
    - [x] Constellation.active_browser_id
    - [x] servoshell Browser.browser_id
    - [x] {EmbedderEvent,ConstellationMsg}::ChangeBrowserVisibility
    - [ ] use FramebufferPixel in EmbedderCoordinates for flipped coordinates
- [x] fix navigating tlbcs other than the tlbc most recently opened
- [x] independent tlbc:
    - [x] show, hide, raise to top
    - [x] focus, unfocus
    - [x] viewport size
    - [x] viewport location
- [x] closing a tlbc:
    - [x] update IOCompositor.root_content_pipelines
    - [x] update IOCompositor.pipeline_details
    - [x] focus next-most-recently-focused browser
- [x] on click (servoshell):
    - [x] focus tlbc
    - [x] raise tlbc to top
- [x] notify the embedder:
    - [x] when a tlbc is focused
    - [x] when a tlbc is unfocused
    - [x] when the painting order changes
- [x] figure out what to do about handle_is_ready_to_save_image
- [x] ~~fix closing initial tlbc after navigation (other tlbcs are ok)~~
    - this is because is_script_closable is false for same-origin popups
    - same behaviour on main branch
- [x] fix compositor target under --no-minibrowser
</details>

The current design of this feature, after being split and reviewed, is as follows.

## limitations
- desktop-style page zoom is still global
- browsers with transparent or translucent content will misbehave
- sending ShowWebView and HideWebView for one webview at a time can be inefficient
- if too many webviews are shown at once, the compositor can get stuck in a laggy state with pending epoch warnings (to reproduce, try [#31545](https://github.com/servo/servo/pull/31545) with [4.html](https://bucket.daz.cat/work/igalia/servo/4.html) and click “_blank” six or seven times)

## compositor ([#31417](https://github.com/servo/servo/pull/31417))
- WebViewManager (new) manages webview-related storage and painting order
    - it allows the compositor to store arbitrary data for each webview id
    - it keeps track of which webviews are visible, and what order to paint them in
- we now use the iframe-in-dummy-root-pipeline technique to composite the webviews together, not just when we have a non-unity pinch zoom

## constellation
- WebViewManager (new) manages webview-related storage and focus order
    - it allows the constellation to store arbitrary data for each webview id
    - it keeps track of which webview is focused, or whether no webview is focused
    - it can refocus the last-focused webview when a webview is removed (currently unused)
- we now send WebViewClosed directly when a webview is closed rather than relying on script to do it, so that the event gets sent even if the webview was not closed by script

## servoshell ([#31417](https://github.com/servo/servo/pull/31417))
- WebViewManager (was WebView) keeps a copy of the webview rects, focus, and painting order
- but for now, we always focus and show the newest webview only

## messages
embedder → compositor (no ipc) ([#31417](https://github.com/servo/servo/pull/31417))
- WindowResize (was Resize) no longer affects the viewport of individual webviews
- Zoom (existing) no longer affects the viewport of individual webviews
- ResetZoom (existing) no longer affects the viewport of individual webviews
- MoveResizeWebView (new) updates a webview’s rect, and sends new viewport to script in descendant pipelines
- ShowWebView (new) adds a webview to painting order, and notifies embedder of the new painting order
- HideWebView (new) removes a webview from painting order, and notifies embedder of the new painting order
- RaiseWebViewToTop (new) moves a webview to the top of the painting order, and notifies embedder accordingly

embedder →\* constellation
- FocusWebView (new) makes a webview focused for keyboard events ([#30842](https://github.com/servo/servo/pull/30842))
- BlurWebView (new) makes no webview focused for keyboard events ([#30842](https://github.com/servo/servo/pull/30842))
- ForwardEvent (existing) also notifies embedder when an event was hit-tested to a webview ([#30841](https://github.com/servo/servo/pull/30841))
- **SetWebViewThrottled (was WindowVisibility)** has been reworked to be less confusing ([#31815](https://github.com/servo/servo/pull/31815), [#31816](https://github.com/servo/servo/pull/31816))

constellation → compositor ([#31417](https://github.com/servo/servo/pull/31417))
- CreateOrUpdateWebView (was SetFrameTree) now adds or updates a webview without clobbering others
- RemoveWebView (new) removes a webview from .webviews and .pipeline_details
- MoveResizeWebView (new) updates a webview’s rect, and sends new viewport to script in descendant pipelines
- ShowWebView (new) adds a webview to painting order, and notifies embedder of the new painting order
- HideWebView (new) removes a webview from painting order, and notifies embedder of the new painting order
- RaiseWebViewToTop (new) moves a webview to the top of the painting order, and notifies embedder accordingly

embedder ← constellation ←\* compositor
- ReadyToPresent (existing) now takes a vec of the ids of all visible webviews in painting order ([#31417](https://github.com/servo/servo/pull/31417))

embedder ← constellation
- AllowOpeningWebview (was AllowOpeningBrowser) behaves as before ([#30842](https://github.com/servo/servo/pull/30842))
- WebViewOpened (was BrowserCreated) notifies embedder that a webview was opened ([#30842](https://github.com/servo/servo/pull/30842))
- WebViewClosed (was CloseBrowser) notifies embedder that a webview was closed ([#30842](https://github.com/servo/servo/pull/30842))
- WebViewFocused (new) notifies embedder that a webview gained focus for keyboard events ([#30842](https://github.com/servo/servo/pull/30842))
- WebViewUnfocused (new) notifies embedder that all webviews lost focus for keyboard events ([#30842](https://github.com/servo/servo/pull/30842))
- EventDelivered (new) notifies embedder that an event was hit-tested to a webview ([#30841](https://github.com/servo/servo/pull/30841))

\* all of these are in the same enum ConstellationMsg (components/shared/compositing/constellation_msg.rs), which is a very confusing design that conflates the embedder with the compositor

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes are related to #30593

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by delan** [comment]
- /_mozilla/css/pixel_snapping_position_a.html is reproducible locally
    - but the test and match hashes are identical (2909abcd9e0b0c116b755850c498eb2d9dfeb9f9)
    - both hashes are also 2909abcd9e0b0c116b755850c498eb2d9dfeb9f9 on CI
- /css/css-backgrounds/background-clip-content-box-002.html is not reproducible locally
    - the match was completely blank on CI, so this may be a new or existing flake
- /css/css-transforms/transform-percent-008.html also unexpected-passes locally without this patch
    - both in #30767 and on main (1d905e28f45cd2ff89f5812c26ab54f9aad5938c)
    - needed to remove notref and mach update-manifest to see it in [reftest analyzer](https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer-structured.xhtml)
- /html/semantics/embedded-content/the-iframe-element/sandbox-top-navigation-escalate-privileges.tentative.sub.window.html is reproducible locally
- /html/semantics/embedded-content/the-iframe-element/sandbox-top-navigation-grandchild.tentative.sub.window.html is reproducible locally
    - it only failed in layout 2020 on CI, but it failed on both locally
    - looks like a new flake caused by this patch

**Comment by delan** [comment]
fixable by feature-gating behaviour changes in compositor:

- /_mozilla/css/pixel_snapping_position_a.html
- /html/semantics/embedded-content/the-iframe-element/sandbox-top-navigation-escalate-privileges.tentative.sub.window.html
- /html/semantics/embedded-content/the-iframe-element/sandbox-top-navigation-grandchild.tentative.sub.window.html

**Comment by mrobinson** [comment]
This is looking pretty good, though I haven't had a chance to look at things in great detail. Thanks so much for splitting this out into multiple PRs. The only overall comment I have is that "Browser" typically means the entire browser application. I would stick with industry standard terminology here ie "WebView." A browser contains multiple web views.

**Comment by wusyong** [comment]
Sorry for being inactive on this feature for a while.
@delan  I can start testing again. If you are busy, I can take on the PR as well.
"WebView" does seem to be more common when people are discussing this topic.

Another question I have is how does this interact with multiple windows in the future?
More specifically, how does one browsing context move from one window to another window?

**Comment by mrobinson** [comment]
Can this be closed in favor of #31417?

**Pull request closed without merging**
