### PR TITLE
update readme for ubuntu build

### LINKED ISSUE #19351: gecko-media v0.1.0 build failed in Ubuntu 16.04
#19252 did not fix it.
```
sudo apt install libpulse-dev
```

Log:
```
tigercosmos@cook-190:~/servo$ ./mach build -d
   Compiling gecko-media v0.1.0 (https://github.com/servo/gecko-media.git#4417372d)
   Compiling hyper-openssl v0.2.6
   Compiling influent v0.4.0
   Compiling webdriver v0.32.0
error: failed to run custom build command for `gecko-media v0.1.0 (https://github.com/servo/gecko-media.git#4417372d)`
process didn't exit successfully: `/home/tigercosmos/servo/target/debug/build/gecko-media-ced88898ad69a8fd/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/tigercosmos/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/4417372/." "-DCMAKE_INSTALL_PREFIX=/home/tigercosmos/servo/target/debug/build/gecko-media-f56d23f3ebe44183/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tigercosmos/servo/target/debug/build/gecko-media-f56d23f3ebe44183/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
[  8%] Built target stagefright
[  9%] Built target ffvpx
[ 10%] Built target ffmpeg57
[ 11%] Built target speex_resampler
[ 12%] Built target tests
[ 13%] Built target cubeb
[ 13%] Built target ogg
[ 46%] Built target opus
[ 86%] Built target gecko_core
[ 91%] Built target vorbis
[ 96%] Built target theora
[ 99%] Built target soundtouch
[100%] Built target gecko_media_cmake
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /home/tigercosmos/servo/target/debug/build/gecko-media-f56d23f3ebe44183/out/libgecko_media_cmake.a
cargo:root=/home/tigercosmos/servo/target/debug/build/gecko-media-f56d23f3ebe44183/out
cargo:rustc-link-search=native=/home/tigercosmos/servo/target/debug/build/gecko-media-f56d23f3ebe44183/out
cargo:rustc-link-lib=static=gecko_media_cmake
cargo:rustc-link-lib=stdc++
cargo:rustc-link-lib=dl

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### PR DESCRIPTION
**Pull request by tigercosmos**
Fix Ubuntu build

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix  #19351 (github issue number if applicable).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19356)

### CODE REVIEW

**Comment by jdm** [comment]
#19353 does not add clang packages for ubuntu.

**Comment by tigercosmos** [comment]
Ops.. Sorry!

**Comment by tigercosmos** [comment]
It would be OK now

**Pull request merged**
