### PR TITLE
Replace all uses of the `heapsize` crate with `malloc_size_of`.

### PR DESCRIPTION
**Pull request by nnethercote**
Servo currently uses `heapsize`, but Stylo/Gecko use `malloc_size_of`.
`malloc_size_of` is better -- it handles various cases that `heapsize` does not
-- so this patch changes Servo to use `malloc_size_of`.

This patch makes the following changes to the `malloc_size_of` crate.

- Adds `MallocSizeOf` trait implementations for numerous types, some built-in
  (e.g. `VecDeque`), some external and Servo-only (e.g. `string_cache`).

- Makes `enclosing_size_of_op` optional, because vanilla jemalloc doesn't
  support that operation.

- For `HashSet`/`HashMap`, falls back to a computed estimate when
  `enclosing_size_of_op` isn't available.

- Adds an extern "C" `malloc_size_of` function that does the actual heap
  measurement; this is based on the same functions from the `heapsize` crate.

This patch makes the following changes elsewhere.

- Converts all the uses of `heapsize` to instead use `malloc_size_of`.

- Disables the "heapsize"/"heap_size" feature for the external crates that
  provide it.

- Removes the `HeapSizeOf` implementation from `hashglobe`.

- Adds `ignore` annotations to a few `Rc`/`Arc`, because `malloc_size_of`
  doesn't derive those types, unlike `heapsize`.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix https://bugzilla.mozilla.org/show_bug.cgi?id=1409255

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because testing is on the Gecko side.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18938)

### CODE REVIEW

**Comment by nnethercote** [comment]
r? @SimonSapin 

This fixes all the issues identified in https://github.com/servo/servo/pull/18920:
- VecDeque
- Windows kernel32-sys errors
- `size_of_is_0!` has been renamed as `malloc_size_of_is_0!`
- The out-of-date comment about `Rc` has been removed.

**Comment by SimonSapin** [comment]
Looks great, thanks you!

@bors-servo r+

---

Reviewed 269 of 269 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18938#-:-Kwj4LpzjP0IYKk_C0S4:b36c0aw)*

**Comment by jdm** [comment]
@bors-servo r-
Appveyor is failing

**Comment by SimonSapin** [comment]
`extern crate malloc_size_of;` in `components/gfx/lib.rs` should be `#[cfg_attr(target_os = "windows", macro_use)] extern crate malloc_size_of;`

**Comment by SimonSapin** [comment]
@bors-servo r+

BTW @nnethercote, github doesn’t notify when an amended commit is pushed to a PR, I only saw your update by change. You may want to comment after pushing, to let the reviewer know.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18938#-:-KwjRdFw7ftubhnm6u1W:b-kwu4t5)*

**Pull request merged**
