### PR TITLE
Add UWP port

### PR DESCRIPTION
**Pull request by jdm**
This adds two new components to the build - a `./mach build --uwp` mode which enables the appropriate settings to generate a usable libsimpleservo DLL, and a new Visual Studio project which makes use of the generated build artifacts. This is still quite experimental, but the goal is to start running these changes through CI to figure out if they break any non-UWP build configurations.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23658)

### CODE REVIEW

**Comment by jdm** [comment]
Depends on https://github.com/servo/rust-offscreen-rendering-context/pull/139.

**Comment by jdm** [comment]
Verified locally that building with --uwp after fetching the VS project's NuGet package yielded a working UWP app.

**Comment by jdm** [comment]
@paulrouget This is ready to merge once it's reviewed :)

**Comment by paulrouget** [comment]
Some of the commits include the author "a" instead of jdm.

Don't we want to upstream the webrender changes first?

I still have a few things I need to figure out before merging this, also, servo's hl branch has changed a bit in the past few days.

**Comment by paulrouget** [comment]
> also, servo's hl branch has changed a bit in the past few days.

I've introduced a `--hololens` mach option, but your `--uwp` does more.

I'm testing locally, renaming the `<a>` author, and I think we'll be good to go.

**Comment by jdm** [comment]
I want to use the webrender fork right now because the PR to upgrade webrender to a more recent revision is blocked on a PR to the upstream WPT infrastructure and all the reviewers for it are on vacation.

**Comment by paulrouget** [comment]
Closing in favor of #23696

**Pull request closed without merging**
