### PR TITLE
stylo: Avoid using InterpolateMatrix as a fallback for matched transform function pair

### PR DESCRIPTION
**Pull request by chenpighead**
In the current implementation, if there is any interpolation error in a matched
transform function pair, we fall-back to use InterpolateMatrix unconditionally.
However, the error could be caused by:

1. mismatched transform function pair
2. matched transform function pair within at least one undecomposable matrix.

Using InterpolateMatrix for case 1 makes sense, however, using InterpolateMatrix
for case 2 does not. According to the spec, we should just report error for
case 2, and let the caller do the fallback procedure. Using InterpolateMatrix
for case 2 will go through more unnecessary code path, and produce more memory
usage and calculation cost, which should be avoidable.

In this patch, we add an extra pass to check if a transform function pair have
matched operations in advance. With this information, we can easily tell whether
the interpolation error in a equal-length transform function pair is caused by
case 1 or case 2. So, we can avoid the unnecessary cost.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix [Bug 1399049](https://bugzilla.mozilla.org/show_bug.cgi?id=1399049)
- [X] These changes do not require tests because the change is for some performance gain, and we have tests to ensure that we won't regress the existing behavior already.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18966)

### CODE REVIEW

**Comment by chenpighead** [comment]
This patch has been reviewed by @hiikezoe in [Bug 1399049](https://bugzilla.mozilla.org/show_bug.cgi?id=1399049) already.

**Comment by chenpighead** [comment]
@bors-servo r=hiro
gecko try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=265c74cd2886334aa79a07d472ff4a363613414a

**Comment by chenpighead** [comment]
@bors-servo r=hiikezoe
I probably should use github account to avoid unnecessary issue assignment.

**Comment by BorisChiou** [comment]
wow. awesome @chenpighead

**Pull request merged**
