### PR TITLE
Refactor winit key handling

### LINKED ISSUE #17146: Key events involving the control key don't work as expected
We realized that no keybindings on Windows work (the "reload"/Ctrl-R binding doesn't work for example).

This is because Glutin sends 2 things:
- the character matching the keyboard layout (`ReceivedCharacter(ch)`)
- the key code and modifiers (`KeyboardInput`)

But the character that is sent when the Ctrl key is pressed is a different unicode character.
For exemple, Ctrl-L will send the ["Form Feed" `\u{c}` character](https://en.wikipedia.org/wiki/Page_break#Form_feed), not L.

A possible approach is to map the key code to the character. This is what is done in the DOM code here: https://github.com/servo/servo/blob/985050d3645382d5c2cc6bd6819ab05f9b843331/components/script/dom/keyboardevent.rs#L169

But this is wrong because the event's `key` property is not localized.

Another approach is to map the combo unicode character to its original key. For example:

```
'\u{c}' => 'l',
'\u{12}' => 'r',
…
```

Both the ports/glutin/window.rs and components/script/dom/keyboardevent.rs need this.

### LINKED ISSUE #21161: Keybindings don't work on Linux and maybe windows
Maybe because of #21087

### PR DESCRIPTION
**Pull request by paulrouget**
This should improve keys input on Linux and Windows.
Should fix #17146 and fix #21161

Tested Mac, Windows and Linux. Basic typing works, combo work, text navigation works. I hit some strange issues where sometimes the text would be displayed late, but I believe it is unrelated to this PR.

If we land that now, we will hit a regression on Mac, we need a winit update that includes https://github.com/tomaka/winit/pull/610.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21250)

### CODE REVIEW

**Comment by paulrouget** [comment]
I basically recorded all the winit events when doing this: https://github.com/servo/servo/issues/21161#issuecomment-407773493

Linux and Windows behave the same way. Mac has extra ReceivedCharacter events.

I figured that the logic is to only send release events on KeyboardInput and send press events on ReceivedCharacter only if the character is printable (see the code comments).

**Comment by dorfsmay** [comment]
The sticky control key is still there.

I checked that I'm on the right branch (checked the line in the files), and also:

    $ git branch -v
    * fixkeys 3c7bb87 Refactor winit key handling
    master  4c5a7ea Auto merge of #21246 - servo:webgl, r=emilio

But, it's not worse, so if this PR fixes other things it's worth merging, and we can investigate the Linux ctrl key further later.

**Comment by dorfsmay** [comment]
Correct that sequence works fine, but this one shows the stickiness of the control key:

* ./mach run --dev
* move mouse to servo and give focus
* press the R key - nothing happens - good, as expected
* press ctrl-R - nothing happens - bad, should reload
* press ctrl-R - reloads content
* press R - reloads content!! - bad, shows that the ctrl state is stuck
* press ctrl-R (or anything) - reloads
* press R - nothing happens, shows that the ctrl state is gone now

If this PR fixes other issues, I think it's worth merging, and we can keep working on the sticky control separately.

**Review by jdm — APPROVED** [review]
These changes seem like a reasonable improvement.

**Comment by paulrouget** [comment]
@dorfsmay sadly I cannot reproduce your steps. Works fine here on Ubuntu. `ctrl-R` reloads on first hit. Can you check with `xev` the events you got on `Ctrl-R` and gather as many info about this bug in a different issue? We will also need to understand which version of Linux you use, your keyboard layout, and if possible, some winit logs.

**Comment by atouchet** [comment]
I will make sure to test this on Windows when it's merged.

**Comment by CYBAI** [comment]
@bors-servo retry
- #JustInfraThings

**Comment by jdm** [comment]
@bors-servo retry
* cleared out the builder

**Pull request merged**
