### PR TITLE
Issue19183

### LINKED ISSUE #19183: Move overflow-y outside of Mako
I think that this should be an easy property to start with. This is a sub issue of #19015.

### PR DESCRIPTION
**Pull request by olmanz**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #19183 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19448)

### CODE REVIEW

**Comment by emilio** [comment]
There's no way this passes `./mach build-geckolib`, right?

**Comment by emilio** [comment]
To elaborate on my previous comment (sorry, didn't want to be mean, was just on a rush).

We compile the style system in two different modes, a mode for Servo and a mode for Firefox.  One is built normally, with `./mach build -d`, and the other is built as a static library with `./mach cargo-geckolib build`.

The key here is that there is a bunch of custom functionality for the `overflow` longhands for Firefox (like the `custom_consts`, `gecko_constant_prefix`, etc. That was my "this is extra-tricky" comment from the issue.

So fixing this implies figuring out a good way of adding the functionality equivalent to those attributes, but without duplicating much code. As of right now, the code likely fails to build in Gecko mode (which is what I mentioned above).

I'm happy to help you fix this and discuss different ways to approach it, if you want, this is a tough nut to crack! :P

**Comment by olmanz** [comment]
@emilio 
> To elaborate on my previous comment (sorry, didn't want to be mean, was just on a rush).
No problem, I understand that. I'm often on a rush myself. ;-)

> We compile the style system in two different modes, a mode for Servo and a mode for Firefox. One is built normally, with ./mach build -d, and the other is built as a static library with ./mach cargo-geckolib build.
> 
> The key here is that there is a bunch of custom functionality for the overflow longhands for Firefox (like the custom_consts, gecko_constant_prefix, etc. That was my "this is extra-tricky" comment from the issue.
> 
> So fixing this implies figuring out a good way of adding the functionality equivalent to those attributes, but without duplicating much code. As of right now, the code likely fails to build in Gecko mode (which is what I mentioned above).
> 
> I'm happy to help you fix this and discuss different ways to approach it, if you want, this is a tough nut to crack! :P 

As I'm still a Rust newbie, I do appreciate every help and would be glad about any suggestions of how to solve this problem. :-)

**Comment by jdm** [comment]
@olmanz Are you still working on this?

**Comment by olmanz** [comment]
Hello @jdm,
sorry, but I couldn't do anything for the last couple of weeks because exams at my university are coming closer and closer and this is stressing me at the moment.
Exams will be over around mid-February, from that on I can surely continue to work on this issue. If this is too late for you, I don't have anything against someone else taking on this issue.

**Comment by jdm** [comment]
In that case, I'm going to close this PR. If you find time to continue working on it, feel free to reopen it!

**Pull request closed without merging**
