### PR TITLE
WebBluetooth API classes

### PR DESCRIPTION
**Pull request by dati91**
Basic implementation of WebBluetooth API
API spec.: https://webbluetoothcg.github.io/web-bluetooth/

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9838)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I don't believe we should take this PR given that most of the API will need to be rewritten once we have Promise support.

r? @jdm

**Comment by jdm** [comment]
I, on the other hand, am not particularly concerned about that, and believe that it will give us a nice testbed for the actual Promise support when it's time to start implementing it.

**Comment by jdm** [comment]
```
Traceback (most recent call last):

  File "/home/travis/build/servo/servo/components/script/dom/bindings/codegen/GlobalGen.py", line 76, in <module>

    main()

  File "/home/travis/build/servo/servo/components/script/dom/bindings/codegen/GlobalGen.py", line 51, in main

    parser.parse(''.join(lines), fullPath)

  File "/home/travis/build/servo/servo/components/script/dom/bindings/codegen/parser/WebIDL.py", line 6501, in parse

    self._productions.extend(self.parser.parse(lexer=self.lexer, tracking=True))

  File "/home/travis/build/servo/servo/components/script/dom/bindings/codegen/ply/ply/yacc.py", line 263, in parse

    return self.parseopt(input,lexer,debug,tracking,tokenfunc)

  File "/home/travis/build/servo/servo/components/script/dom/bindings/codegen/ply/ply/yacc.py", line 792, in parseopt

    tok = self.errorfunc(errtoken)

  File "/home/travis/build/servo/servo/components/script/dom/bindings/codegen/parser/WebIDL.py", line 6432, in p_error

    raise WebIDLError("invalid syntax", [Location(self.lexer, p.lineno, p.lexpos, self._filename)])

WebIDL.WebIDLError: error: invalid syntax, /home/travis/build/servo/servo/components/script/dom/webidls/BluetoothRemoteGATTCharacteristic.webidl line 13:47

  BluetoothRemoteGATTDescriptor? getDescriptor(/*BluetoothDescriptorUUID* descriptor/);

                                               ^
```
and please run `./mach test-tidy`, too.

**Comment by dati91** [comment]
Oh there was a typo, sorry about that!

The tidy test will fail on the following lines:
`./components/script/dom/bluetoothremotegattcharacteristic.rs:7: Line is longer than 120 characters`
`./components/script/dom/bluetoothcharacteristicproperties.rs:6: Line is longer than 120 characters`

but if I use multi-lines:
`./components/script/dom/bluetoothremotegattcharacteristic.rs:7: use statement spans multiple lines`
`./components/script/dom/bluetoothcharacteristicproperties.rs:6: use statement spans multiple lines`

Any suggestions about that?

**Comment by nox** [comment]
Make the line shorter, don't write use statements spanning multiple lines. :)

**Comment by larsbergstrom** [comment]
@nox These lines only have a single identifier that is more than 120 characters long (e.g., `use dom::bindings::codegen::Bindings::BluetoothRemoteGATTCharacteristicBinding::BluetoothRemoteGATTCharacteristicMethods;`).

At the risk of sounding dumb, none of the obvious things I tried (creating an alias with `as`, using a line continuation character, etc.) worked. We could of course use a wildcard instead, but it seems like this will be a problem for any IncrediblyVerboseDOMNameOfThingsThatWereAgreedByCommittees :-) I didn't see any others in the dom/ directory, but there were many that just happened to fit at 115 or so characters.

Am I missing something obvious?

**Comment by larsbergstrom** [comment]
Poor rustfmt also can't help here:
```
[larsberg@lbergstrom dom]$ ~/servo/.cargo/bin/rustfmt bluetoothremotegattcharacteristic.rs 
Rustfmt failed at bluetoothremotegattcharacteristic.rs:6: line exceeded maximum length (sorry)
Rustfmt failed at bluetoothremotegattcharacteristic.rs:56: line exceeded maximum length (sorry)
Rustfmt failed at bluetoothremotegattcharacteristic.rs:76: line exceeded maximum length (sorry)
Rustfmt failed at bluetoothremotegattcharacteristic.rs:82: line exceeded maximum length (sorry)
[larsberg@lbergstrom dom]$ 
```
CC @nrc

**Comment by KiChjang** [comment]
Maybe we can tell tidy to not check use statements?

**Comment by nox** [comment]
We shouldn't check the length if there are no braces, that's a good way to see if it's a single import or not, no?

**Comment by KiChjang** [comment]
Filed #9864.

**Comment by SimonSapin** [comment]
@larsbergstrom 
>     use dom::bindings::codegen::Bindings::BluetoothRemoteGATTCharacteristicBinding::BluetoothRemoteGATTCharacteristicMethods;

You can have whitespace in a path:

```rust
use dom::bindings::codegen::Bindings::BluetoothRemoteGATTCharacteristicBinding::
    BluetoothRemoteGATTCharacteristicMethods;
```

(Rearrange to whatever feels less ugly.)

**Comment by larsbergstrom** [comment]
@SimonSapin Thanks for the tip!

@dati91 Please rearrange per that advice :-)

@jdm @nox Are there any other issues with this PR other than the formatting one?

**Comment by dati91** [comment]
@larsbergstrom Done, but this will still cause a "use statement spans multiple lines" error.

**Comment by larsbergstrom** [comment]
Should have a better fix in #9871 shortly!

**Comment by larsbergstrom** [comment]
#9871 landed!

**Comment by jdm** [comment]
Good work! Apologies for the delay in reviewing it; I was on vacation last week.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 19 of 24 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 32 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bluetoothadvertisingdata.rs, line 34 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMRbU_OwXae41txo_a:-KCMRbU_OwXae41txo_b:1034361585) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothadvertisingdata.rs#L34)):*
nit: indent this line and the previous two by four spaces, please.

---

*[components/script/dom/bluetoothdevice.rs, line 21 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMRlzvqOfSI-7OroBh:-KCMRlzvqOfSI-7OroBi:1191696217) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothdevice.rs#L21)):*
Please use `MutHeap<JS` instead of `DOMRefCell`.

---

*[components/script/dom/bluetoothdevice.rs, line 27 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMRqWcCSAw3UJ2sRpJ:-KCMRqWcCSAw3UJ2sRpK:-1045866338) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothdevice.rs#L27)):*
Same as previous.

---

*[components/script/dom/bluetoothremotegattcharacteristic.rs, line 21 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMSVH4ie6aOHSRgqP7:-KCMSVH5cKlQKMdd7v71:-1199768709) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothremotegattcharacteristic.rs#L21)):*
MutHeap.

---

*[components/script/dom/bluetoothremotegattcharacteristic.rs, line 23 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMSWpSQaSIlAV8RD8b:-KCMSWpSQaSIlAV8RD8c:-1199768709) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothremotegattcharacteristic.rs#L23)):*
MutHeap.

---

*[components/script/dom/bluetoothremotegattcharacteristic.rs, line 47 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMSYzKNB-LLIT_nmeU:-KCMSYzKNB-LLIT_nmeV:1351043838) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothremotegattcharacteristic.rs#L47)):*
Let's remove code that isn't used.

---

*[components/script/dom/bluetoothremotegattdescriptor.rs, line 18 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMSfDR8HYP5HXBbgel:-KCMSfDR8HYP5HXBbgem:-1199768709) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothremotegattdescriptor.rs#L18)):*
MutHeap.

---

*[components/script/dom/bluetoothremotegattdescriptor.rs, line 39 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMSh--0AAglassVAxa:-KCMSh--0AAglassVAxb:-2069948267) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothremotegattdescriptor.rs#L39)):*
Let's remove unused code.

---

*[components/script/dom/bluetoothremotegattserver.rs, line 52 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMSo2phtho_iyPsj7h:-KCMSo2phtho_iyPsj7i:-292204891) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothremotegattserver.rs#L52)):*
nit: add a newline above this

---

*[components/script/dom/bluetoothremotegattservice.rs, line 20 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMSw62Y4h09-wm78sk:-KCMSw62Y4h09-wm78sl:931129107) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothremotegattservice.rs#L20)):*
MutHeap

---

*[components/script/dom/bluetoothuuid.rs, line 28 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMT4nucs2uu-HLuUPb:-KCMT4nucs2uu-HLuUPc:-774181415) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L28)):*
nit: unindent this line.

---

*[components/script/dom/bluetoothuuid.rs, line 56 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMTtzaOJzPwdhp5vVe:-KCMTtzbBp-0rrKZX3d0:-1189542012) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L56)):*
No need for the `let canonicalized_uuid =`. We can return the DOMString::from expression instead.

---

*[components/script/dom/bluetoothuuid.rs, line 64 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMTnxAVqq4P7GLwbuO:-KCMTnxAVqq4P7GLwbuP:1818960394) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L64)):*
nit: indent these arguments by one space.

---

*[components/script/dom/bluetoothuuid.rs, line 67 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMU1XxSSBllBvMtjHw:-KCMU1XxSSBllBvMtjHx:-949740966) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L67)):*
nit: move this to the previous line, please.

---

*[components/script/dom/bluetoothuuid.rs, line 70 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVKaKdI2AQ6bzdS2M:-KCMVKaKdI2AQ6bzdS2N:-1406392872) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L70)):*
This should be able to return the resolved value directly once the WebIDL is appropriately updated (see later comments).

---

*[components/script/dom/bluetoothuuid.rs, line 77 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVwKddNtgdIyLNHGR:-KCMVwKddNtgdIyLNHGS:690885429) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L77)):*
nit: indent these lines to match the `globalref`.

---

*[components/script/dom/bluetoothuuid.rs, line 79 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVtaAdbZuoGyDN7KB:-KCMVtaAdbZuoGyDN7KC:-327860532) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L79)):*
nit: indent these arguments to match the first.

---

*[components/script/dom/bluetoothuuid.rs, line 82 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVs54Xk6N0029oSoi:-KCMVs54Xk6N0029oSoj:2015302646) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L82)):*
nit: move this to the previous line

---

*[components/script/dom/bluetoothuuid.rs, line 85 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVXOe8yBbtRlUuZNA:-KCMVXOe8yBbtRlUuZNB:-1406392872) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L85)):*
This should be able to return the resolved value directly once the WebIDL is appropriately updated (see later comments).

---

*[components/script/dom/bluetoothuuid.rs, line 95 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVl9p6kX3Frk8TySl:-KCMVl9p6kX3Frk8TySm:-1313386584) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L95)):*
nit: indent these arguments to match the first one, please.

---

*[components/script/dom/bluetoothuuid.rs, line 98 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVnIjEcb3tphrXrID:-KCMVnIjEcb3tphrXrIE:-1950127368) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L98)):*
nit: move this to the previous line.

---

*[components/script/dom/bluetoothuuid.rs, line 101 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVYJdvji4Bf1XXFK7:-KCMVYJdvji4Bf1XXFK8:-1406392872) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L101)):*
This should be able to return the resolved value directly once the WebIDL is appropriately updated (see later comments).

---

*[components/script/dom/bluetoothuuid.rs, line 109 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVEtmW7AgI8NK3NgR:-KCMVEtmW7AgI8NK3NgS:508546630) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L109)):*
nit: indent these arguments to match the first one.

---

*[components/script/dom/bluetoothuuid.rs, line 110 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMUILKWa4qRuLrySo4:-KCMUILKWa4qRuLrySo5:916585839) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L110)):*
I would use `Fallible<DOMString>` instead, which is an alias for `Result<DOMString, dom::error::Error>`.

---

*[components/script/dom/bluetoothuuid.rs, line 110 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMVCdlQl7m_QryjAsE:-KCMVCdlQl7m_QryjAsF:-915087068) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L110)):*
nit: move the ) to the previous line

---

*[components/script/dom/bluetoothuuid.rs, line 112 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMV_Y01UnURZT2EN31:-KCMV_Y01UnURZT2EN32:-298679471) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L112)):*
We can annotate the parts of this function with comments like `// Step 1` to make the relationship with the spec clearer.

---

*[components/script/dom/bluetoothuuid.rs, line 118 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMUbQEEgVfuIfqlcBT:-KCMUbQFJ2-q9BjyT1QV:-1950127368) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L118)):*
nit: move this to the previous line.

---

*[components/script/dom/bluetoothuuid.rs, line 126 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMUv7mY00j33vuJhZT:-KCMUv7mY00j33vuJhZU:-1407226765) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L126)):*
`Some((_, alias)) => Ok(BluetoothUUID::CanonicalUUID(globalref, alias))`

---

*[components/script/dom/bluetoothuuid.rs, line 127 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMV3bmsuvz8fLQOu64:-KCMV3bmsuvz8fLQOu65:-1045267810) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/bluetoothuuid.rs#L127)):*
`Err(SyntaxError)`

---

*[components/script/dom/navigator.rs, line 18 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMW8UOIxtqJfmMBGHp:-KCMW8UPpl84iRNVs7h9:659271514) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/navigator.rs#L18)):*
Let's use MutNullableHeap and create the Bluetooth object lazily.

---

*[components/script/dom/navigator.rs, line 71 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMWFRFF2W4QLU5Nla4:-KCMWFRFF2W4QLU5Nla5:-468416983) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/navigator.rs#L71)):*
nit: add a newline above this.

---

*[components/script/dom/webidls/BluetoothUUID.webidl, line 9 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCMW_155w8prgSZrMBK:-KCMW_155w8prgSZrMBL:511368198) ([raw file](https://github.com/servo/servo/blob/820903a824a7c2513c3b18d3cb6d6abd6d27465e/components/script/dom/webidls/BluetoothUUID.webidl#L9)):*
Anything that calls `resolve_uuid_name` should be marked `[Throws]`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9838#-:-KCMWvjX0mwvlZByvI9M:-1075894097)*

**Comment by jdm** [comment]
You'll also need to update tests/wpt/mozilla/tests/mozilla/interfaces.html with the new interfaces (run it with `./mach test-wpt tests/wpt/mozilla/tests/mozilla/interfaces.html`).

**Comment by jdm** [comment]
Looking good! One thing I noticed though - there's a lot of `MutHeap<JS<T>>` now, but the actual values aren't mutated at all. We should just use `JS<T>` until mutation is required instead.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 14 of 14 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bluetoothcharacteristicproperties.rs, line 6 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCZ_cB7ZZsmq_UDrSlQ:-KCZ_cB8xIu7ZRpCzFr8:92802527) ([raw file](https://github.com/servo/servo/blob/ea9c3688577c80b0ce167f1544a18280e2ede691/components/script/dom/bluetoothcharacteristicproperties.rs#L6)):*
`./mach test-tidy` doesn't like this.

---

*[components/script/dom/bluetoothuuid.rs, line 104 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCZaqY314JF0asbS0f2:-KCZaqY314JF0asbS0f3:-1408699882) ([raw file](https://github.com/servo/servo/blob/ea9c3688577c80b0ce167f1544a18280e2ede691/components/script/dom/bluetoothuuid.rs#L104)):*
nit: indent this to match the next line, please.

---

*[components/script/dom/navigator.rs, line 74 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCZbCTRmCSzNcuMc66h:-KCZbCTRmCSzNcuMc66i:-1449376442) ([raw file](https://github.com/servo/servo/blob/ea9c3688577c80b0ce167f1544a18280e2ede691/components/script/dom/navigator.rs#L74)):*
This match can be replaced with `self.bluetooth.or_init(|| Bluetooth::new(self.global().r()))`.

---

*[components/servo/Cargo.lock, line 1654 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCZbXfcnYAYeBrrX_Mj:-KCZbXfcnYAYeBrrX_Mk:900375455) ([raw file](https://github.com/servo/servo/blob/ea9c3688577c80b0ce167f1544a18280e2ede691/components/servo/Cargo.lock#L1654)):*
This needs to be updated to 0.1.55 or the build fails. We also need to run `./mach cargo-update -p script` to ensure that the other Cargo.lock files are updated appropriately.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9838#-:-KCZbjz-BgqPkYxwcxb-:67468931)*

**Comment by jdm** [comment]
I'm still concerned that the other Cargo.lock files haven't updated. Please run `./mach build-cef` and `GONKDIR=/tmp ./mach build-gonk` - you can cancel the builds as soon as you start seeing "Compiling [name]" messages. The lockfiles should have been changed after that happens.
-S-awaiting-review -S-fails-tidy +S-needs-code-changes 

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/navigator.rs, line 74 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9838#-KCZbCTRmCSzNcuMc66h:-KCasEIQoDU8QOkxhHZr:-1191004743) ([raw file](https://github.com/servo/servo/blob/ea9c3688577c80b0ce167f1544a18280e2ede691/components/script/dom/navigator.rs#L74)):*
I mean that the entire function can be
```rust
fn Bluetooth(&self) -> Root<Bluetooth> {
    self.bluetooth.or_init(|| Bluetooth::new(self.global().r())))
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9838#-:-KCat-VhJrkLDbmMhQHv:1679132086)*

**Comment by jdm** [comment]
You can go ahead and squash all the changes together into one commit, as well!

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9838#-:-KD-07SY8LPyoTOWTWrU:-1746383326)*

**Pull request merged**
