### PR TITLE
get_image_pixels() implementation for video element

### LINKED ISSUE #21995: Support HTMLVideoElement as texture image source
The code in `get_image_pixels` that handles various texture sources throws an exception when an HTMLVideoElement is encountered. We will need to fix this to match https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.11 if we want to support 180/360º videos in webgl. This will require obtaining the pixels from gstreamer as efficiently as possible.

### PR DESCRIPTION
**Pull request by ceyusa**
Implements the webgl's get_image_pixels() call for video element

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #21995 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24233)

### CODE REVIEW

**Comment by ceyusa** [comment]
This implementation covers when the video rendering is not using gl textures (aka hardware accelaration), because servo-media provides textures.

For this case I see these implementations options:

1. Use gl().get_tex_image() in the script thread -- I don't think this is an option
2. Pass the GL texture ID to webgl and add a new code path for this case
3. And this a kind of a hack: when the video tag has the 'hidden' attributes, disable the hwaccel in that player

I have tested this patch with [Simple360Player](https://github.com/gbentaieb/simple360Player) on my X11/GLX linux box (on Wayland/EGL, webgl doesn't work because the GL context is not grabbed correctly).

Strangely, with debug builds, I saw frames when the mouse point is not moved, otherwise the video flickers with black frames; but with release builds I only see black frames.

A behavior I observe, is webgl calls `get_image_pixels()` way before the servo-media starts to send decoded frames. I wonder if webgl calls `get_image_pixels()` certain amount of times before it bails.

**Comment by jdm** [comment]
Yes, I think adding a new code path where we send a texture ID to the WebGL thread and use something like glBlitFramebuffer or glCopySubTexImage2D to copy the texture data to the destination texture will make the most sense.

**Comment by jdm** [comment]
Ah, I think we have the various directories that involve tests for video textures disabled:
* https://github.com/servo/servo/tree/master/tests/wpt/webgl/meta/conformance/textures/video
* https://github.com/servo/servo/blob/master/tests/wpt/webgl/meta/conformance/textures/misc/texture-corner-case-videos.html.ini
* https://github.com/servo/servo/blob/master/tests/wpt/webgl/meta/conformance/textures/misc/texture-npot-video.html.ini
* https://github.com/servo/servo/blob/master/tests/wpt/webgl/meta/conformance/extensions/oes-texture-float-with-video.html.ini
* https://github.com/servo/servo/blob/master/tests/wpt/webgl/meta/conformance/extensions/oes-texture-half-float-with-video.html.ini

**Comment by ceyusa** [comment]
I guess it is required a WPT resync.

**Comment by jdm** [comment]
If we delete all of those ini files in this PR, we'll get real results from those tests.

**Comment by ceyusa** [comment]
I'm trying to figure out why webgl/conformance/textures/misc/texture-npot-video.html fails. But, I can't understand. Two items in the test fails:

```
FAIL [expected PASS] WebGL test #6: shouldBe 0,0,0 at (4, 40) expected: 0,0,0 was 0,255,0
 → assert_true: shouldBe 0,0,0

FAIL [expected PASS] WebGL test #5: shouldBe 0,0,0 at (4, 4) expected: 0,0,0 was 255,0,0
 → assert_true: shouldBe 0,0,0
```

I've dump every frame fetched, and all of the are the same. I wonder if there's a webgl bug around.

**Comment by jdm** [comment]
Yeah, that one particular case failing (flipY, linear, repeat) when all of the others pass does suggest that something is wrong with our webgl implementation:
```
0:04.87 pid:89377 requestAnimationFrame
 0:04.87 pid:89377 Testing texImage2D with flipY=true
 0:04.87 pid:89377 size: 304x176
 0:04.87 pid:89377 bad min filter
 0:04.87 pid:89377 bad clamp
 0:04.87 pid:89377 generate mips
 0:04.87 pid:89377 PASS getError was expected value: INVALID_OPERATION : should be INVALID_OPERATION
 0:04.87 pid:89377 Checking lower left corner
 0:04.87 pid:89377 PASS shouldBe 0,0,0
 0:04.87 pid:89377 Checking upper left corner
 0:04.87 pid:89377 PASS shouldBe 0,0,0
 0:04.87 pid:89377
 0:04.87 pid:89377 Testing texImage2D with flipY=true
 0:04.87 pid:89377 size: 304x176
 0:04.87 pid:89377 bad min filter
 0:04.87 pid:89377 good clamp
 0:04.87 pid:89377 Checking lower left corner
 0:04.87 pid:89377 PASS shouldBe 0,0,0
 0:04.87 pid:89377 Checking upper left corner
 0:04.87 pid:89377 PASS shouldBe 0,0,0
 0:04.87 pid:89377
 0:04.87 pid:89377 Testing texImage2D with flipY=true
 0:04.87 pid:89377 size: 304x176
 0:04.87 pid:89377 good min filter
 0:04.87 pid:89377 bad clamp
 0:04.87 pid:89377 Checking lower left corner
 0:04.87 pid:89377 FAIL shouldBe 0,0,0
 0:04.87 pid:89377 at (4, 4) expected: 0,0,0 was 255,0,0
 0:04.87 pid:89377 Checking upper left corner
 0:04.87 pid:89377 FAIL shouldBe 0,0,0
 0:04.87 pid:89377 at (4, 40) expected: 0,0,0 was 0,255,0
 0:04.87 pid:89377
 0:04.87 pid:89377 Testing texImage2D with flipY=true
 0:04.87 pid:89377 size: 304x176
 0:04.87 pid:89377 bad min filter
 0:04.87 pid:89377 bad clamp
 0:04.87 pid:89377 Checking lower left corner
 0:04.88 pid:89377 PASS shouldBe 0,0,0
 0:04.88 pid:89377 Checking upper left corner
 0:04.88 pid:89377 PASS shouldBe 0,0,0
 0:04.88 pid:89377
 0:04.88 pid:89377 Testing texImage2D with flipY=true
 0:04.88 pid:89377 size: 304x176
 0:04.88 pid:89377 good min filter
 0:04.88 pid:89377 good clamp
 0:04.88 pid:89377 Checking lower left corner
 0:04.89 pid:89377 PASS shouldBe 255,0,0
 0:04.89 pid:89377 Checking upper left corner
 0:04.89 pid:89377 PASS shouldBe 0,255,0
 0:04.89 pid:89377
 0:04.89 pid:89377 Testing texImage2D with flipY=false
 0:04.89 pid:89377 size: 304x176
 0:04.89 pid:89377 good min filter
 0:04.89 pid:89377 good clamp
 0:04.89 pid:89377 Checking lower left corner
 0:04.90 pid:89377 PASS shouldBe 0,255,0
 0:04.90 pid:89377 Checking upper left corner
 0:04.90 pid:89377 PASS shouldBe 255,0,0
 0:04.90 pid:89377
 0:04.90 pid:89377 Testing texSubImage2D with flipY=true
 0:04.90 pid:89377 size: 304x176
 0:04.90 pid:89377 good min filter
 0:04.90 pid:89377 good clamp
 0:04.90 pid:89377 Checking lower left corner
 0:04.91 pid:89377 PASS shouldBe 255,0,0
 0:04.91 pid:89377 Checking upper left corner
 0:04.91 pid:89377 PASS shouldBe 0,255,0
 0:04.91 pid:89377
 0:04.91 pid:89377 Testing texSubImage2D with flipY=false
 0:04.91 pid:89377 size: 304x176
 0:04.91 pid:89377 good min filter
 0:04.91 pid:89377 good clamp
 0:04.91 pid:89377 Checking lower left corner
 0:04.92 pid:89377 PASS shouldBe 0,255,0
 0:04.92 pid:89377 Checking upper left corner
 0:04.92 pid:89377 PASS shouldBe 255,0,0
 0:04.92 pid:89377
 0:04.92 pid:89377 PASS getError was expected value: NO_ERROR : should be no errors
 0:04.95 pid:89377 PASS successfullyParsed is true
 0:04.95 pid:89377 TEST COMPLETE
```

**Comment by ceyusa** [comment]
Regarding `/_webgl/conformance/textures/video/tex-2d-rgb-rgb-unsigned_short_5_6_5.html` I found that the stream fails to play with GStreamer. I cooked a simple patch and opened a [merge request](https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/merge_requests/437)

**Comment by jdm** [comment]
@bors-servo r+
Let's merge this and file a followup for supporting GL video textures.

**Comment by ceyusa** [comment]
I've updated the expect files according with the found issues

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
