### PR TITLE
Fix `linear_gradients_lengths_a.html` and fix Servo's use of "background-clip" to actually make it work.

### PR DESCRIPTION
**Pull request by pcwalton**
See the commit messages for details.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9171)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9171)*

**Comment by mbrubeck** [comment]
test failure was #8769

**Comment by jdm** [comment]
@bors-servo: retry
* #8769

**Comment by larsbergstrom** [comment]
@bors-servo: retry

Infrastructure failure; tests were running forever on one builder and had to be aborted manually.

**Comment by Manishearth** [comment]
```

Tests with unexpected results:
  ▶ CRASH [expected PASS] /css21_dev/html4/outline-width-070.htm
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:741
  │ stack backtrace:
  │    1:        0x10a7065f8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x10a7086bf - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x10a708162 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x10a6f3f76 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x10a6f435e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
  │    6:        0x10a705c17 - rust_begin_unwind
  │    7:        0x10a72ad20 - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:        0x109d61137 - mem::_<impl>::send::hd6c9795b44f9deb8Bea
  │    9:        0x1099103f0 - sys_common::unwind::try::try_fn::try_fn::h5497073048065211827
  │   10:        0x10a705a38 - __rust_try
  │   11:        0x10a702b3e - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   12:        0x1099114c1 - boxed::_<impl>::call_box::call_box::h2152788446713078593
  │   13:        0x10a70794d - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   14:     0x7fff8416a059 - _pthread_body
  │   15:     0x7fff84169fd6 - _pthread_start
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
  │ stack backtrace:
  │    1:        0x10a7065f8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x10a7086bf - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x10a708162 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x10a6f3e74 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x10a6f435e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
  │    6:        0x10a705c17 - rust_begin_unwind
  │    7:        0x10a72ad20 - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:        0x10a72b01c - panicking::panic::hbe2e3a5159c3d178iEK
  │    9:        0x1094a34c9 - page::_<impl>::window::h1f665daea1edfa7cyx4
  │   10:        0x10990d4c4 - script_task::_<impl>::drop::h59485e417d6389d3zU5
  │   11:        0x109910f08 - sys_common::unwind::try::try_fn::try_fn::h5497073048065211827
  │   12:        0x10a705a38 - __rust_try
  │   13:        0x10a702b3e - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   14:        0x1099114c1 - boxed::_<impl>::call_box::call_box::h2152788446713078593
  │   15:        0x10a70794d - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   16:     0x7fff8416a059 - _pthread_body
  │   17:     0x7fff84169fd6 - _pthread_start
  └ thread panicked while panicking. aborting.
```

**Comment by jdm** [comment]
@bors-servo: retry
* #8961

**Comment by jdm** [comment]
@bors-servo: retry
* #9124 #8769 #7791

**Comment by KiChjang** [comment]
@bors-servo retry
* #9163

**Comment by KiChjang** [comment]
@bors-servo retry
* #9124

**Pull request merged**
