### PR TITLE
servoshell: Update gilrs version, enable gamepad pref by default

### PR DESCRIPTION
**Pull request by msub2**
Now that the latest version of gilrs has released with the force feedback completion event included, we can finally unpin the commit and track regular releases. This also enables the gamepad pref by default now, as the feature should be stable going forwards.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because functionality should be equivalent to prior version.

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by msub2** [comment]
@jdm Should I try and upgrade the core-foundation deps in this PR as well or open a separate one?

**Comment by msub2** [comment]
Alternatively I guess I could update servo-tidy.toml with a note about it for now

**Comment by jdm** [comment]
That's going to be a long tail of other crates that depend on the older version, so go ahead and update the toml file.

**Comment by msub2** [comment]
Hmm, there was a failed check but it hasn't been removed from merge queue yet for some reason. Check is from a gamepad extension interface, I'll update that in a bit

**Comment by msub2** [comment]
@jdm I still need to update this one, waiting on the webxr ref space reset event one merging first since both of these modify interfaces.html

**Pull request merged**
