### PR TITLE
Geckolib: Implement Margin, Padding, font-size, and has_class

### PR DESCRIPTION
**Pull request by bholley**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10938)

### CODE REVIEW

**Comment by bholley** [comment]
Also note that I had to manually derive PartialEq on nsStyleUnit in order to be able to compare the values. @emilio, can you add that to the bindgen TODO?

**Comment by emilio** [comment]
Looks good to me after a quick look at it, will review more carefully this afternoon.

Re. bindgen: Sure, deriving `Eq`, `PartialEq` and `Hash` should be ok for all enums indeed.

**Comment by emilio** [comment]
Looks good to me, just added the bindgen changes, so feel free to regenerate the bindings now or `r=me` as-is.

I left a few comments, but they're just nits.

-S-awaiting-review

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ports/geckolib/gecko_style_structs.rs, line 4156 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10938#-KGbiwhbMMcRakfZm26i:-KGbiwhbMMcRakfZm26j:1178869682) ([raw file](https://github.com/servo/servo/blob/3849d603d1fcedbb86f3a8b46b02a2d1ea5c06c4/ports/geckolib/gecko_style_structs.rs#L4156)):*
This is now autogenerated by bindgen, so you can regenerate bindings if you want, or merge as-is for now and update the bindings in another moment.

---

*[ports/geckolib/properties.mako.rs, line 384 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10938#-KGbjJCz9TuqrIOoFkOh:-KGbjJCz9TuqrIOoFkOi:22282113) ([raw file](https://github.com/servo/servo/blob/3849d603d1fcedbb86f3a8b46b02a2d1ea5c06c4/ports/geckolib/properties.mako.rs#L384)):*
nit: This could probably use list comprehension + join or some python thing like that, even be moved to a function that takes a format string if this is going to be widely used.

Nontheless is readable as-is, so I won't insist.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10938#-:-KGbk9wYXfwsIPrWNXEe:-120963713)*

**Comment by bholley** [comment]
Thanks for the review!

@bors-servo r=emilio

**Pull request merged**
