### PR TITLE
Increase BFC root height to contain floats

### LINKED ISSUE #29823: Layout 2020: Block formatting context with floats should be big enough to contain their floating content
This is a followup to #29757. When a block formatting context has floating content, it should be big enough to contain all of it's floating content, which normally isn't counted in content size as it's not true in flow content. This could probably be implemented as finding the clearance for one more "clear: both" object at the end of the block formatting context layout.

cc @Loirooriol

### PR DESCRIPTION
**Pull request by Loirooriol**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #29823
- [X] There are tests for these changes

### CODE REVIEW

**Comment by Loirooriol** [comment]
@bors-servo try=wpt-2020

The flex test is still failing locally...

**Comment by Loirooriol** [comment]
Nevermind, it's passing now, previously I must have done something wrong.

**Review by mrobinson — APPROVED** [review]
Very nice.

**Pull request merged**
