### PR TITLE
compositing: Make `ScriptListener` and `LayoutControlChan` messages go over IPC.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6596)

### CODE REVIEW

**Comment by pcwalton** [comment]
I *think* this one doesn't depend on any outstanding PRs, so it can be merged right away.

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 10 of 14 files at r1, 16 of 16 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6596)

**Comment by jdm** [comment]
```
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:32: 119:32 error: the trait `serde::ser::Serialize` is not implemented for the type `euclid::point::Point2D<f32>` [E0277]
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119 #[derive(Deserialize, Serialize)]
                                                                                                           ^
<std macros>:1:1: 6:48 note: in expansion of try!
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:23: 119:32 note: expansion site
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:23: 119:32 note: in expansion of #[derive_Serialize]
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:23: 119:32 note: expansion site
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:32: 119:32 help: run `rustc --explain E0277` to see a detailed explanation
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:21: 119:21 error: the trait `serde::de::Deserialize` is not implemented for the type `euclid::point::Point2D<f32>` [E0277]
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119 #[derive(Deserialize, Serialize)]
                                                                                                ^
<std macros>:1:1: 6:48 note: in expansion of try!
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:10: 119:21 note: expansion site
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:10: 119:21 note: in expansion of #[derive_Deserialize]
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:10: 119:21 note: expansion site
/Users/servo/buildbot/slave/mac2/build/components/msg/compositor_msg.rs:119:21: 119:21 help: run `rustc --explain E0277` to see a detailed explanation
```
Depends on upgrading euclid, unfortunately.

**Comment by jdm** [comment]
Presumably you didn't update Cargo.lock?

**Pull request merged**
