### PR TITLE
Add DateTime string attribute to Time

### PR DESCRIPTION
**Pull request by chajath**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix part of #12967, content parsing will come as a separate PR.

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14086)

### CODE REVIEW

**Comment by KiChjang** [comment]
@chajath We usually only accept PRs that implement the full set of features as described by the HTML spec, rather than exposing interfaces to incomplete functionalities. You can either close this PR, or add more commits to it so that it conforms with the spec.

**Comment by nox** [comment]
@KiChjang What is the rest of the functionality?

**Comment by KiChjang** [comment]
Parsing the input string into a machine-readable equivalent. Are there any WPT tests for this?

**Comment by nox** [comment]
> Parsing the input string into a machine-readable equivalent. Are there any WPT tests for this?

Where do you find this needed in the spec? The spec just says that the IDL attribute reflects the content attribute, AFAICT.

**Comment by KiChjang** [comment]
See https://github.com/whatwg/html/issues/1702.

**Comment by nox** [comment]
That's for authors, not UAs, AFAICT. At the very least the current spec doesn't say to parse anything in the dateTime setter.

**Comment by ConnorGBrewster** [comment]
Sorry about being late on a review for this... This looks good to me, unless the datetime does need to be parsed, but I don't see exactly where the spec would be saying that. I think if that is the case, it would be ok to implement that in a followup PR.

Lets see what tests now pass
@bors-servo try

**Comment by chajath** [comment]
That's odd. Tests run fine on my local machine. Should we try again?

**Comment by KiChjang** [comment]
```
Checking files for tidiness...

./components/script/dom/htmltimeelement.rs:5: trailing whitespace
```

**Comment by chajath** [comment]
I'm having trouble finding where we specify that we expect tests to pass or fail in wpt. Can anyone help please?

**Comment by chajath** [comment]
nvm I figured its under tests/wpt/metadata. I think we can now remove time element specific metadata now that we expect all tests to pass

**Comment by ConnorGBrewster** [comment]
Lets go ahead and squash these commits and then I will r+ this.

**Comment by ConnorGBrewster** [comment]
There are still some test expectations that need updated.
You should not need to do this by hand. Refer to [Updating Test Expectations](https://github.com/servo/servo/tree/master/tests/wpt#updating-test-expectations).
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to ""

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to " \\0\\x01\\x02\\x03\\x04\\x05\\x06\\x07 \\b\\t\\n\\v\\f\\r\\x0e\\x0f \\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17 \\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f  foo "

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to undefined

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to 7

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to 1.5

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to true

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to false

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to object "[object Object]"

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to NaN

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to Infinity

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to -Infinity

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to "\\0"

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to null

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to object "test-toString"

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: setAttribute() to object "test-valueOf"

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to ""

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to " \\0\\x01\\x02\\x03\\x04\\x05\\x06\\x07 \\b\\t\\n\\v\\f\\r\\x0e\\x0f \\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17 \\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f  foo "

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to undefined

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to 7

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to 1.5

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to true

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to false

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to object "[object Object]"

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to NaN

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to Infinity

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to -Infinity

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to "\\0"

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to null

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to object "test-toString"

  ▶ Unexpected subtest result in /html/dom/reflection-text.html:
  └ PASS [expected FAIL] time.dateTime: IDL set to object "test-valueOf"
```

**Pull request merged**
