### PR TITLE
stylo: Use namespaces in the bindings.

### PR DESCRIPTION
**Pull request by emilio**
This allows us to incrementally remove both bindgen hacks and stylo hacks.

r? @heycam

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14472)

### CODE REVIEW

**Comment by emilio** [comment]
Updated to work around a bindgen bug that generated too many tests, and also published the relevant gecko bug, that is https://bugzilla.mozilla.org/show_bug.cgi?id=1322446

**Review by heycam — APPROVED** [review]
Output looks good!  I'm not sure about having to have this top level `root` module but maybe that's something rust-bindgen can optionally leave out.

**Comment by emilio** [comment]
Hmm... I don't think we can optionally leave that out, given we need to have a canonical way to reach the bindings. Maybe we can do something like `use super as root`, though we'd need to special-case everything generated under the root module to _not_ do that, which seems slightly annoying for the relatively low benefit.

Effectively unwrapping the module would be doing something like `pub use root::*;`. I'm fine leaving that line to avoid that extra level of indirection in most cases.

@bors-servo r=heycam

**Comment by emilio** [comment]
Superseded by https://github.com/servo/servo/issues/14492

**Pull request closed without merging**
