### PR TITLE
Don't double-apply transform and other effect styles for text (fixes #11300)

### LINKED ISSUE #11300: Text within rotated div is displayed incorrectly
rotate

```
<!DOCTYPE html>
<html><body style="font-size: 4em; padding: 1em;">
    <div style="transform: rotateZ(45deg); border: 1px solid red; display: inline-block;">Servo</div>
</body></html>
```

### PR DESCRIPTION
**Pull request by nox**
Rebase of #11421.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14078)

### CODE REVIEW

**Comment by nox** [comment]
Cc @pcwalton 

The failing test does:

capture d ecran 2016-11-05 a 01 47 22

Rounding issue somewhere?

**Comment by emilio** [comment]
@bors-servo r=emilio,pcwalton

Let's see if OSMesa in testing has improved that situation.

**Comment by nox** [comment]
> Let's see if OSMesa in testing has improved that situation.

That won't work, I did the screenshot locally.

**Comment by nox** [comment]
@pcwalton Any idea for the rounding issue?

**Comment by pcwalton** [comment]
Check display lists with `-Z dump-display-list`. If the DL is correct, then just mark the test as failing with an issue filed. This is usually what I do for rounding related bugs that are entirely in WR.

**Comment by nox** [comment]
I'm confused. If the two display lists are the same, why would WR not render them the same way?

**Comment by nox** [comment]
@pcwalton Also I can't really mark as failing the very test that is supposed to validate that we fixed that issue...

**Comment by nox** [comment]
```
± diff -u ref not-ref
--- ref	2016-11-09 09:20:01.000000000 +0100
+++ not-ref	2016-11-09 09:19:17.000000000 +0100
@@ -2,11 +2,13 @@
 │  ├─ Items
 │  │  ├─ PushStackingContext(StackingContext at TypedRect(984px×740px at (0px,0px)) with overflow TypedRect(984px×740px at (0px,0px)): StackingContextId(0)) StackingContext: StackingContextId(0)
 │  │  ├─ SolidColor rgba(0, 0, 0, 0) @ TypedRect(984px×740px at (20px,0px)) ClippingRegion::Max StackingContext: StackingContextId(0)
-│  │  ├─ SolidColor rgba(0, 0, 0, 0) @ TypedRect(944px×104.13333333333334px at (40px,40px)) ClippingRegion::Max StackingContext: StackingContextId(0)
-│  │  ├─ PushStackingContext(StackingContext at TypedRect(100px×100px at (40px,40px)) with overflow TypedRect(100px×100px at (0px,0px)): StackingContextId(4977705696)) StackingContext: StackingContextId(4977705696)
-│  │  ├─ SolidColor rgba(0, 0.5019608, 0, 1) @ TypedRect(100px×100px at (0px,0px)) ClippingRegion::Max StackingContext: StackingContextId(4977705696)
-│  │  ├─ PopStackingContext(StackingContextId(4977705696) StackingContext: StackingContextId(4977705696)
-│  │  ├─ PushStackingContext(StackingContext at TypedRect(100px×100px at (140px,40px)) with overflow TypedRect(100px×100px at (0px,0px)): StackingContextId(4977705840)) StackingContext: StackingContextId(4977705840)
-│  │  ├─ SolidColor rgba(0, 0.5019608, 0, 1) @ TypedRect(100px×100px at (0px,0px)) ClippingRegion::Max StackingContext: StackingContextId(4977705840)
-│  │  ├─ PopStackingContext(StackingContextId(4977705840) StackingContext: StackingContextId(4977705840)
-│  │  └─ PopStackingContext(StackingContextId(0) StackingContext: StackingContextId(0)
\ No newline at end of file
+│  │  ├─ SolidColor rgba(0, 0, 0, 0) @ TypedRect(944px×100px at (40px,40px)) ClippingRegion::Max StackingContext: StackingContextId(0)
+│  │  ├─ PushStackingContext(StackingContext at TypedRect(100px×100px at (40px,40px)) with overflow TypedRect(100px×100px at (0px,0px)): StackingContextId(4885431440)) StackingContext: StackingContextId(4885431440)
+│  │  ├─ SolidColor rgba(0, 0, 0, 0) @ TypedRect(100px×100px at (0px,0px)) ClippingRegion::Max StackingContext: StackingContextId(4885431440)
+│  │  ├─ Text @ TypedRect(100px×99.98333333333333px at (0px,0px)) ClippingRegion::Max StackingContext: StackingContextId(4885431440)
+│  │  ├─ PopStackingContext(StackingContextId(4885431440) StackingContext: StackingContextId(4885431440)
+│  │  ├─ PushStackingContext(StackingContext at TypedRect(100px×100px at (140px,40px)) with overflow TypedRect(100px×100px at (0px,0px)): StackingContextId(4885431632)) StackingContext: StackingContextId(4885431632)
+│  │  ├─ SolidColor rgba(0, 0, 0, 0) @ TypedRect(100px×100px at (0px,0px)) ClippingRegion::Max StackingContext: StackingContextId(4885431632)
+│  │  ├─ Text @ TypedRect(100px×99.98333333333333px at (0px,0px)) ClippingRegion::Max StackingContext: StackingContextId(4885431632)
+│  │  ├─ PopStackingContext(StackingContextId(4885431632) StackingContext: StackingContextId(4885431632)
+│  │  └─ PopStackingContext(StackingContextId(0) StackingContext: StackingContextId(0)
```

**Comment by jdm** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
