### PR TITLE
Update web-platform-tests

### PR DESCRIPTION
**Pull request by nox**
This updates web-platform-tests to a46616a5b18e. It also removes our local copy of wptrunner in favour of the upstream one that we can modify and sync more easily. Carried from #17416.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18756)

### CODE REVIEW

**Comment by nox** [comment]
I updated the expectations as per https://github.com/servo/servo/pull/17416#issuecomment-334338038.

@bors-servo r=jgraham p=10

**Comment by jdm** [comment]
The test is intermittent. File an issue.

**Comment by nox** [comment]
> The test is intermittent. File an issue.

It never fails locally though.

**Comment by nox** [comment]
SORRY FOR NOT TRUSTING YOU JOSH

@bors-servo retry #18762

**Pull request merged**
