### PR TITLE
style: Sync changes from mozilla-central

### PR DESCRIPTION
**Pull request by emilio**

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by emilio** [comment]
@bors-servo r=jdm

 * Tweaked commit messages to remove bug numbers, and removed backed-out patches to avoid noise.

**Comment by jdm** [comment]
```
error: unreachable expression
  --> components/style/values/specified/box.rs:46:5
   |
40 | /         return servo_config::prefs::pref_map()
41 | |             .get("layout.flexbox.enabled")
42 | |             .as_bool()
43 | |             .unwrap_or(false);
   | |_____________________________- any code following this expression is unreachable
...
46 |       true
   |       ^^^^ unreachable expression
   |
   = note: `-D unreachable-code` implied by `-D warnings`
error: aborting due to previous error
error: could not compile `style`.
```

**Comment by emilio** [comment]
@bors-servo r=jdm

 * avoid the silly warning.

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
