### PR TITLE
[WIP] Move asynchronous network loads to the fetch stack and remove unused code.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13714)

### CODE REVIEW

**Comment by Manishearth** [comment]
I need spec links on each of the `RequestInit` ctors.

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 2 of 2 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/net/image_cache_thread.rs, line 536 at r8](https://reviewable.io:443/reviews/servo/servo/13714#-KTsInG7YF3aI03SCzlw:-KTsInG8pMQXLdEeF0V9:b4nzlcv) ([raw file](https://github.com/servo/servo/blob/cd8fb59a9a3637c2da2e78ceb2f9f67b4211195f/components/net/image_cache_thread.rs#L536)):*
> ```Rust
>                                 FetchResponseMsg::ProcessRequestEOF => return,
>                                 FetchResponseMsg::ProcessResponse(meta_result) => {
>                                     ResponseAction::HeadersAvailable(meta_result.map(|m| {
> ```

Do we need ResponseAction anymore? We can just proxy the FetchResponseMsg through

---

*[components/net/image_cache_thread.rs, line 228 at r13](https://reviewable.io:443/reviews/servo/servo/13714#-KTsJf2qQn6E5KAtJ-hR:-KTsJf2rYp-EF_xCAuyr:b-l2mqp6) ([raw file](https://github.com/servo/servo/blob/fdfde8a3b5d3c9a267daa0b769c45ded37d35a9c/components/net/image_cache_thread.rs#L228)):*
> ```Rust
> }
> 
> /// Data for passing between threads/processes to indicate a particular action to
> ```

If we're not removing this, make this comment reflect what specifically this is used for here

---

*[components/script/dom/servoparser/mod.rs, line 345 at r3](https://reviewable.io:443/reviews/servo/servo/13714#-KTsGeTXdOjBC52HsE38:-KTsGeTYCjOMR9GvGDKb:b-6ocgzh) ([raw file](https://github.com/servo/servo/blob/85fa12d0de2c03dc20643b0c5480960c69be8841/components/script/dom/servoparser/mod.rs#L345)):*
> ```Rust
>             Ok(meta) => {
>                 Some(match meta {
>                     FetchMetadata::Unfiltered(m) => m,
> ```

might be useful as a convenience method, `FetchMetadata.unwrap_ufiltered()` or something

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13714#-:-KTsJlKxmsgAt-p2viLZ:brrel9m)*

**Comment by Ms2ger** [comment]
@bors-servo r-

Apparently not

**Comment by Ms2ger** [comment]
Looks like I'll need to support blob URLs. I'll check tomorrow if I can land some parts of this PR independently.

**Comment by Ms2ger** [comment]
Currently, this is hitting a timeout in `tests/wpt/mozilla/tests/mozilla/mime_sniffing_font_context.html`; if I understand correctly, that's because there is sniffing code in the old networking stack that isn't in the fetch stack. I'd argue it would be better to break the test for now, for two reasons in particular. First, it really isn't the networking stack's job to sniff bytes; the consumer should ignore the metadata rather than expecting the networking layer to mess with it. Second, I'd generally prefer not to add too much code to the fetch stack before the old stack is gone, and we've been able to simplify the fetch code a little.

I'll leave it to @jdm to decide whether that's a good idea.

**Comment by KiChjang** [comment]
Perhaps it makes sense to open a tracking issue for this?

**Comment by jdm** [comment]
I reviewed these commits by accident in #13961.

**Pull request closed without merging**
