### PR TITLE
layout: Fix radius percentage resolution.

### LINKED ISSUE #16764: Incorrect values in calc-border-radius-1.htm test.
I started seeing a failure in ```calc-border-radius-1.htm``` when I was testing locally with the elliptical border radius support in https://github.com/servo/webrender/pull/1209.

I logged out the Servo-side display list values for the test case, and it shows:

```
clip ClippingRegion(Complex=[ComplexClippingRegion { rect: TypedRect(512px×256px at (8px,16px)), radii: BorderRadii { top_left: 21px×11px, top_right: 6px×32px, bottom_right: 12px×10px, bottom_left: 29px×3px } }])
```

```
clip ClippingRegion(Complex=[ComplexClippingRegion { rect: TypedRect(512px×256px at (8px,16px)), radii: BorderRadii { top_left: 21px×5px, top_right: 6px×16px, bottom_right: 12px×10px, bottom_left: 29px×3px } }])
```

Note that the border radii for the y-radius in the top left and top right corners don't match.

I haven't looked into it yet at all - but perhaps this is something simple in the ```calc``` support code or parser? cc @emilio in case you have any ideas :)

### PR DESCRIPTION
**Pull request by emilio**
Fixes #16764

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16766)

### CODE REVIEW

**Comment by emilio** [comment]
(or anyone else really)

**Comment by glennw** [comment]
@emilio Ah, that makes sense. Thanks for looking into it so quickly! r=me once try completes.

**Comment by emilio** [comment]
@bors-servo retry

 * That android failure again?

**Pull request merged**
