### PR TITLE
script: Remove 'pending reflow' concept and some explicit reflows

### PR DESCRIPTION
**Pull request by mrobinson**
The `pending reflow` concept isn't necessary now that *update the
rendering* is taking care of triggering reflows at the correct time.
`Window::reflow` already avoids reflows if the page is not dirty, so
pending reflows is now just an extraneous check as long as *update the
rendering* runs properly.

This change also removes some explicit reflows, which now wait until the
appropriate moment during *update the rendering*. This should remove
some extra reflows that are not necessary.

Servo needs some way to track that resizing the web view needs to
re-layout due to the initial containing block changing. Move handling
of `Document::needs_paint` to the script thread and use this, expanding
the rustdoc to explain what it is for a bit more clearly.

This is part of #31242 and an important part of removing
`note_rendering_opportunity` from Servo.

Signed-off-by: Martin Robinson <mrobinson@igalia.com>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes are part of #31242.
- [x] There changes are covered by existing WPT tests.

### CODE REVIEW

**Comment by gterzian** [comment]
Part of https://github.com/servo/servo/issues/31871

**Comment by mrobinson** [comment]
It seems that these changes fix two CSS tests.

**Comment by jdm** [comment]
I've seen some of those timeouts in other PRs, so they aren't caused by these changes.

**Comment by mrobinson** [comment]
> I've seen some of those timeouts in other PRs, so they aren't caused by these changes.

Oh, thanks for the info. I thought these sudden timeouts seemed a bit suspicious.

**Review by gterzian — APPROVED** [review]
Great, thank you. The last PR's were very good progress towards fixing our event-loop, and it shows that this required more interaction between people working on script and people working on layout.

**Pull request merged**
