### PR TITLE
Added the final step for event dispatcher `invoke`

### PR DESCRIPTION
**Pull request by ghost**
r? @nox

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10069)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I'm not sure we should implement this in isolation from the rest of the webkit-prefixed animation stuff.

In any case, I want a boatload of tests.

**Comment by nox** [comment]
See existing tests in [/tests/wpt/web-platform-tests/dom/events](https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests/dom/events).

**Comment by nox** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/eventdispatcher.rs, line 195 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10069#-KDIHjzZUT9foLk1xaC5:-KDIHjzZUT9foLk1xaC6:-219438443) ([raw file](https://github.com/servo/servo/blob/88ca8dc7c969e9333949e55d720af3163dcd07dc/components/script/dom/eventdispatcher.rs#L195)):*
Nit: `original_event_type`.

---

*[components/script/dom/eventdispatcher.rs, line 195 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10069#-KDIHt8jOAy_UPyGr48w:-KDIHt8jOAy_UPyGr48x:-205976928) ([raw file](https://github.com/servo/servo/blob/88ca8dc7c969e9333949e55d720af3163dcd07dc/components/script/dom/eventdispatcher.rs#L195)):*
Nit: "Step 5.1."

---

*[components/script/dom/eventdispatcher.rs, line 196 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10069#-KDII0_Ztq-KVqEk3M1e:-KDII0_Ztq-KVqEk3M1f:-205975967) ([raw file](https://github.com/servo/servo/blob/88ca8dc7c969e9333949e55d720af3163dcd07dc/components/script/dom/eventdispatcher.rs#L196)):*
Nit: "Step 5.2."

---

*[components/script/dom/eventdispatcher.rs, line 204 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10069#-KDII3WKTeekBqxeG0vl:-KDII3WKTeekBqxeG0vm:-205975006) ([raw file](https://github.com/servo/servo/blob/88ca8dc7c969e9333949e55d720af3163dcd07dc/components/script/dom/eventdispatcher.rs#L204)):*
Nit: "Step 5.3."

---

*[components/script/dom/eventdispatcher.rs, line 205 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10069#-KDII4bCLAyF6vpZ0c7A:-KDII4bCLAyF6vpZ0c7B:-205974045) ([raw file](https://github.com/servo/servo/blob/88ca8dc7c969e9333949e55d720af3163dcd07dc/components/script/dom/eventdispatcher.rs#L205)):*
Nit: "Step 5.4."

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10069)*

**Comment by nox** [comment]
@Wafflespeanut Ping?

**Comment by nox** [comment]
Still needs tests.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/dom/eventdispatcher.rs, line 212 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10069#-KFcTeisFlg-dwWwxx_Q:-KFcTeisFlg-dwWwxx_R:-877407994) ([raw file](https://github.com/servo/servo/blob/57abae9505315d146d16d9c3d517e5dd6604e7f8/components/script/dom/eventdispatcher.rs#L212)):*
Still a typo in `original_event_type`, that doesn't compile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10069#-:-KFcTkgHqt_PwFyd5lRw:-977347255)*

**Comment by Wafflespeanut** [comment]
Oh, that's just plain stupid. I'm sorry :)

**Comment by Wafflespeanut** [comment]
@nox I'm sorry. I don't think I'll be able to finish this off anytime soon - I'll close this.

**Pull request closed without merging**
