### PR TITLE
Use `#![register_tool]` instead of `Registry::register_attribute` 

### PR DESCRIPTION
**Pull request by SimonSapin**
CC https://github.com/rust-lang/rust/pull/66344, https://github.com/rust-lang/rust/issues/66079

### CODE REVIEW

**Comment by SimonSapin** [comment]
This requires a compiler upgrade which was blocked by https://github.com/servo/servo/issues/24684, but is not longer blocked since https://github.com/rust-lang/rust/pull/66378.

**Comment by SimonSapin** [comment]
@bors-servo treeclosed=100

Deploying https://github.com/servo/taskcluster-config/pull/4

**Comment by SimonSapin** [comment]
@bors-servo retry

```
  ▶ FAIL [expected PASS] /css/CSS2/tables/border-collapse-dynamic-cell-001.xht
  └   → /css/CSS2/tables/border-collapse-dynamic-cell-001.xht 9565d734a7fc1b3d50a261d4a24bd5a950ac2f7d
/css/CSS2/tables/border-collapse-dynamic-cell-001-ref.xht 54a9df64f1476dd12020019d7cf22ac34d727bc0

**Comment by jdm** [comment]
That's #24726.

**Pull request merged**
