### PR TITLE
(Do not merge) Test orbit.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11110)

### CODE REVIEW

**Comment by Ms2ger** [comment]
CC @nikomatsakis @eddyb

**Comment by metajack** [comment]
@Ms2ger Can you link to some docs about what orbit is? My google-fu is failing.

**Comment by Ms2ger** [comment]
It enables MIR

**Comment by metajack** [comment]
Do you intend to land this change? I assume the only benefit of this right now is potentially faster executables and more feedback on MIR for the Rust team.

**Comment by Ms2ger** [comment]
Not particularly intending to land it; eddyb mentioned on IRC that he wanted to check if this found any bugs.

**Comment by eddyb** [comment]
@Ms2ger Confirmed that rust-lang/rust#33239 fixes the crashes observed here.

**Comment by eddyb** [comment]
cc @nikomatsakis

**Comment by eddyb** [comment]
This *could* be missing drops for `File` or some other thing holding onto a file description.

**Comment by eddyb** [comment]
Then again, it's just *one* single test, when I had the missing drop problem, all the run-pass tests past a certain point would start failing because `compiletest` itself wasn't dropping the individual test `File`s it was opening.

**Comment by samlh** [comment]
Looks like a known intermittent failure: https://github.com/servo/servo/issues/11100

**Comment by eddyb** [comment]
Thanks everyone, this was one of the last attempts to find bugs in MIR trans before we turn it on by default (pending several performance improvements landing).
And the results look great! :smile:

**Pull request closed without merging**
