### PR TITLE
update regex

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by jdm** [comment]
Verified that https://github.com/rust-lang/regex/commit/e040c1b06397a254cccd3506ee80dbe042360afd is the commit that triggers the regression.

**Comment by jdm** [comment]
I have not been able to reproduce the issue in mozjs or rust-mozjs, strangely (https://github.com/servo/rust-mozjs/pull/537 and https://github.com/servo/mozjs/pull/274)

**Comment by BurntSushi** [comment]
This should be fixed by `regex 1.4.5`.

**Pull request closed without merging**
