### PR TITLE
Correctly determine text selection direction

### LINKED ISSUE #21891: Assertion begin <= self.edit_point fails in text selection code
```text
assertion failed: begin <= self.edit_point (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/textinput.rs:308)
```

Steps to reproduce:

1. Open https://google.com (or any other document with text input)
2. Focus text input
3. Press <kbd>a</kbd>, <kbd>b</kbd>, <kbd>c</kbd>
4. Hold <kbd>Shift</kbd> and press <kbd>←</kbd> 3 times
5. Hold <kbd>Shift</kbd> and press  <kbd>→</kbd>

Expected: text is "abc" and "bc" selected
Observed (on debug build): assertion failure

### PR DESCRIPTION
**Pull request by pyfisch**
Add some debug! output.

Closes #21891

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #21891 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21975)

### CODE REVIEW

**Comment by pyfisch** [comment]
@bors-servo retry

I don't see how `/css/cssom-view/elementFromPoint-001.html` should be affected.

**Comment by pyfisch** [comment]
@bors-servo retry

A different test fails.

**Comment by jdm** [comment]
@bors-servo retry
* oom

**Pull request merged**
