### PR TITLE
Upgrade to rustc 1.20.0-nightly (ab91c70cc 2017-07-14), use non-"alt" std

### PR DESCRIPTION
**Pull request by SimonSapin**
<s>Possibly</s> fixes https://github.com/servo/servo/pull/17604

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17727)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@MortimerGoro Does this indeed fix https://github.com/servo/servo/pull/17604 for you in a clean checkout?

**Comment by MortimerGoro** [comment]
@SimonSapin still the same problem.

**Comment by MortimerGoro** [comment]
edit: I tried a wrong branch

@SimonSapin it works!

**Comment by SimonSapin** [comment]
Since https://github.com/rust-lang/rust/pull/43167, "alt" and "non-alt" standard libraries should be the same.

**Comment by SimonSapin** [comment]
```
  ▶ CRASH [expected PASS] /css-flexbox-1_dev/html/flexbox_item-bottom-float.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread main, at /checkout/src/libcore/result.rs:860)
  │ stack backtrace:
  │    0:     0x7f53536a5fec - backtrace::backtrace::trace::h3c531980b444c01c
  │    1:     0x7f53536a6142 - backtrace::capture::Backtrace::new::hde1afc496271e12d
  │    2:     0x7f5351512a10 - servo::main::{{closure}}::hea7a430fb8634f2b
  │    3:     0x7f53536edf36 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:612
  │    4:     0x7f53536edd54 - std::panicking::begin_panic_new<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:553
  │    5:     0x7f53536edcc9 - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:521
  │    6:     0x7f53536edc5a - std::panicking::rust_begin_panic
  │                         at /checkout/src/libstd/panicking.rs:497
  │    7:     0x7f535371ceb0 - core::panicking::panic_fmt
  │                         at /checkout/src/libcore/panicking.rs:92
  │    8:     0x7f535350c1bb - core::result::unwrap_failed::h885434233510212d
  │    9:     0x7f5353511834 - webrender_api::api::RenderApiSender::create_api::hcec500bbf9e117fa
  │   10:     0x7f53515113fd - servo::main::h2116398fe0b38126
  │   11:     0x7f53536f4fec - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:98
  │   12:     0x7f53536ee61b - std::panicking::try<(),closure>
  │                         at /checkout/src/libstd/panicking.rs:458
  │                          - std::panic::catch_unwind<closure,()>
  │                         at /checkout/src/libstd/panic.rs:361
  │                          - std::rt::lang_start
  │                         at /checkout/src/libstd/rt.rs:59
  │   13:     0x7f534ec2bf44 - __libc_start_main
  │   14:     0x7f53514dd928 - <unknown>
  │   15:                0x0 - <unknown>
  │ Unexpected compositor channel panic in constellation: RecvError (thread Constellation, at /checkout/src/libcore/result.rs:860)
  │ stack backtrace:
  │    0:     0x7f53536a5fec - backtrace::backtrace::trace::h3c531980b444c01c
  │    1:     0x7f53536a6142 - backtrace::capture::Backtrace::new::hde1afc496271e12d
  │    2:     0x7f5351512a10 - servo::main::{{closure}}::hea7a430fb8634f2b
  │    3:     0x7f53536edf36 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:612
  │    4:     0x7f53536edd54 - std::panicking::begin_panic_new<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:553
  │    5:     0x7f53536edcc9 - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:521
  │    6:     0x7f53536edc5a - std::panicking::rust_begin_panic
  │                         at /checkout/src/libstd/panicking.rs:497
  │    7:     0x7f535371ceb0 - core::panicking::panic_fmt
  │                         at /checkout/src/libcore/panicking.rs:92
  │    8:     0x7f53515acf55 - core::result::unwrap_failed::ha066bfe87601d9ee
  │    9:     0x7f53515cd79d - <constellation::constellation::Constellation<Message, LTF, STF>>::handle_request::h7066ea6d8c0956a5
  │   10:     0x7f535157bc67 - std::sys_common::backtrace::__rust_begin_short_backtrace::he9bc2f6e599a9b5e
  │   11:     0x7f535157d5d7 - std::panicking::try::do_call::h47fa0100c0fb4584
  │   12:     0x7f53536f4fec - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:98
  │   13:     0x7f53515ad802 - <F as alloc::boxed::FnBox<A>>::call_box::hb89954f3298bedc9
  │   14:     0x7f53536ecbab - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /checkout/src/liballoc/boxed.rs:661
  │                          - std::sys_common::thread::start_thread
  │                         at /checkout/src/libstd/sys_common/thread.rs:21
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:84
  │   15:     0x7f534f1f1183 - start_thread
  │   16:     0x7f534ed07ffc - clone
  │   17:                0x0 - <unknown>
  │ IpcSelectionResult::unwrap(): channel 1 closed (thread ResourceManager, at /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.8.0/src/ipc.rs:308)
  │ stack backtrace:
  │    0:     0x7f53536a5fec - backtrace::backtrace::trace::h3c531980b444c01c
  │    1:     0x7f53536a6142 - backtrace::capture::Backtrace::new::hde1afc496271e12d
  │    2:     0x7f5351512a10 - servo::main::{{closure}}::hea7a430fb8634f2b
  │    3:     0x7f53536edf36 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:612
  │    4:     0x7f53536edd54 - std::panicking::begin_panic_new<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:553
  │    5:     0x7f53536edcc9 - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:521
  │    6:     0x7f53536bc019 - ipc_channel::ipc::IpcSelectionResult::unwrap::h7945a1170478d134
  │    7:     0x7f535182094e - std::sys_common::backtrace::__rust_begin_short_backtrace::h1833e161fb301bd8
  │    8:     0x7f535182899f - std::panicking::try::do_call::hb97759491c0b91fb
  │    9:     0x7f53536f4fec - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:98
  │   10:     0x7f535185d58e - <F as alloc::boxed::FnBox<A>>::call_box::he6f7a87e12fbc4b1
  │   11:     0x7f53536ecbab - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /checkout/src/liballoc/boxed.rs:661
  │                          - std::sys_common::thread::start_thread
  │                         at /checkout/src/libstd/sys_common/thread.rs:21
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:84
  │   12:     0x7f534f1f1183 - start_thread
  │   13:     0x7f534ed07ffc - clone
  │   14:                0x0 - <unknown>
  │ called `Result::unwrap()` on an `Err` value: RecvError (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /checkout/src/libcore/result.rs:860)
  │ stack backtrace:
  │    0:     0x7f53536a5fec - backtrace::backtrace::trace::h3c531980b444c01c
  │    1:     0x7f53536a6142 - backtrace::capture::Backtrace::new::hde1afc496271e12d
  │    2:     0x7f5351512a10 - servo::main::{{closure}}::hea7a430fb8634f2b
  │    3:     0x7f53536edf36 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:612
  │    4:     0x7f53536edd54 - std::panicking::begin_panic_new<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:553
  │    5:     0x7f53536edcc9 - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:521
  │    6:     0x7f53536edc5a - std::panicking::rust_begin_panic
  │                         at /checkout/src/libstd/panicking.rs:497
  │    7:     0x7f535371ceb0 - core::panicking::panic_fmt
  │                         at /checkout/src/libcore/panicking.rs:92
  │    8:     0x7f53516a3b00 - core::result::unwrap_failed::h459529adb5243b7b
  │    9:     0x7f53516f9a28 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::hee754477a3249214
  │   10:     0x7f5351672697 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha9db9098e1099950
  │   11:     0x7f53516732d7 - std::panicking::try::do_call::h1b67198a27f4a239
  │   12:     0x7f53536f4fec - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:98
  │   13:     0x7f53516a4712 - <F as alloc::boxed::FnBox<A>>::call_box::h476bdc666fa1afd9
  │   14:     0x7f53536ecbab - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /checkout/src/liballoc/boxed.rs:661
  │                          - std::sys_common::thread::start_thread
  │                         at /checkout/src/libstd/sys_common/thread.rs:21
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:84
  │   15:     0x7f534f1f1183 - start_thread
  │   16:     0x7f534ed07ffc - clone
  │   17:                0x0 - <unknown>
  │ thread panicked while processing panic. aborting.
  └ thread panicked while processing panic. aborting.
```

I can’t reproducing this locally, filing a new intermittent

@bors-servo retry #17755

**Pull request merged**
