### PR TITLE
Update mozjs (includes fix for py3.12)

### PR DESCRIPTION
**Pull request by sagudev**
Includes https://github.com/servo/mozjs/pull/426

Fixes mac failures.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they just fix the build.

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Comment by sagudev** [comment]
Oh no:
```
  /Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/edb271a/mozjs-sys/mozjs/python/mozbuild/mozbuild/shellutil.py:38: SyntaxWarning: invalid escape sequence '\$'
    special="\$",
  /Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/edb271a/mozjs-sys/mozjs/python/mozbuild/mozbuild/util.py:1255: SyntaxWarning: invalid escape sequence '\$'
    VARIABLES_RE = re.compile("\$\((\w+)\)")
  /Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/edb271a/mozjs-sys/mozjs/python/mozbuild/mozbuild/configure/__init__.py:931: SyntaxWarning: invalid escape sequence '\.'
    RE_MODULE = re.compile("^[a-zA-Z0-9_\.]+$")
  Traceback (most recent call last):
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/edb271a/mozjs-sys/mozjs/js/src/../../configure.py", line 343, in <module>
      sys.exit(main(sys.argv))
               ^^^^^^^^^^^^^^
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/edb271a/mozjs-sys/mozjs/js/src/../../configure.py", line 115, in main
      _activate_build_virtualenv()
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/edb271a/mozjs-sys/mozjs/js/src/../../configure.py", line 330, in _activate_build_virtualenv
      mach_site.activate()
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/edb271a/mozjs-sys/mozjs/python/mach/mach/site.py", line 370, in activate
      with self._metadata.update_current_site(
    File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
      return next(self.gen)
             ^^^^^^^^^^^^^^
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/edb271a/mozjs-sys/mozjs/python/mach/mach/site.py", line 227, in update_current_site
      import pkg_resources
    File "/Users/runner/work/servo/servo/python/_virtualenv3.12/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  cat: config.log: No such file or directory
  make: *** [maybe-configure] Error 1
  thread 'main' panicked at 'assertion failed: result.success()', /Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/edb271a/mozjs-sys/build.rs:246:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
     2: core::panicking::panic
               at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:114:5
     3: build_script_build::build_jsapi
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
      Timing report saved to /Users/runner/work/servo/servo/target/cargo-timings/cargo-timing-20231101T112327Z.html
Failed in 0:14:32
```

It is different error and I assume it has something to do with servo's virtualenv.

**Comment by sagudev** [comment]
Relevant links:
https://pythontest.com/posts/2023/2023-10-02-py312-impimporter/
https://ubuntuhandbook.org/index.php/2023/10/fix-broken-pip-python-312-ubuntu/

**Comment by mrobinson** [comment]
> Ah we need to get py3.12 mac runner

Or maybe just select Python 3.12 using the `setup-python` GitHub action as a temporary testing measure.

**Comment by sagudev** [comment]
It does not work: https://github.com/sagudev/servo/actions/runs/6720279699/job/18263494668

**Comment by sagudev** [comment]
Replaced by: https://github.com/servo/servo/pull/30685

**Pull request closed without merging**
