### PR TITLE
Implement the ch unit as 0.5em

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7463)

### CODE REVIEW

**Comment by pcwalton** [comment]
This is spec compliant, right?

**Comment by SimonSapin** [comment]
Thanks!

@bors-servo r+

**Comment by SimonSapin** [comment]
@pcwalton 

https://drafts.csswg.org/css-values-3/#font-relative-lengths
> In the cases where it is impossible or impractical to determine the measure of the "0" glyph, a value of 0.5em must be assumed.

Let’s call it impractical for us until we figure out how to query font metrics from the `style` crate. #7462 is about doing it (and `ex`) properly.

**Comment by nox** [comment]
@Ms2ger Why did you close and reopen that?

**Comment by Ms2ger** [comment]
Was poking at buildbot

**Pull request merged**
