### PR TITLE
Update the url crate to 2.0

### PR DESCRIPTION
**Pull request by SimonSapin**
Blocked on:

* [x] https://github.com/housleyjk/ws-rs/pull/283 + undoing corresponding `[patch.crates-io]` entry

Soft-blocked on: (we could add to the crate duplication allow-list instead)

* [x] ~https://github.com/rust-windowing/winit/pull/1066~
  - [x] https://github.com/rust-windowing/winit/pull/1076
* [x] https://github.com/servo/media/pull/288
* [ ] https://github.com/servo/webrender/pull/3720
* [x] https://github.com/gobwas/influent.rs/pull/22
* [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1568540
  - [x] https://github.com/seanmonstar/warp/pull/260
  - [ ] https://github.com/abonander/multipart/pull/121

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23838)

### CODE REVIEW

**Comment by atouchet** [comment]
url ended up being duped in #23853.

**Comment by SimonSapin** [comment]
In that case let’s not wait more to land this, the full dedup can come later.

r? @Manishearth

**Comment by jdm** [comment]
Taskcluster reports build errors.

**Comment by SimonSapin** [comment]
This duplicates the `ws` crate, which is fixed by https://github.com/servo/webrender/pull/3720

**Comment by Manishearth** [comment]
@bors-servo r+

https://www.youtube.com/watch?v=h6Uht69h8Is

**Comment by Manishearth** [comment]
merge when ready

**Comment by SimonSapin** [comment]
Oh, was that about “WIP” in the title?

@bors-servo r=Manishearth

**Comment by jdm** [comment]
```

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <https://x/>.host = '\xdf' IDNA Nontransitional_Processing

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <https://x/>.host = '\xdf' IDNA Nontransitional_Processing
  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <https://fa\xdf.ExAmPlE/> against <about:blank>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://host/?'> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-origin-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing origin: <https://fa\xdf.ExAmPlE/> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-origin.html:
  └ PASS [expected FAIL] Parsing origin: <https://fa\xdf.ExAmPlE/> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element.html:
  └ PASS [expected FAIL] Parsing: <https://fa\xdf.ExAmPlE/> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element.html:
  └ PASS [expected FAIL] Parsing: <http://host/?'> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing: <https://fa\xdf.ExAmPlE/> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing: <http://host/?'> against <about:blank>

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] aa-- (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] aa-- (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] aa-- (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] aa-- (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] aa-- (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] aa-- (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] aa-- (using <area>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] a\u2020-- (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] a\u2020-- (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] a\u2020-- (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] a\u2020-- (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] a\u2020-- (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] a\u2020-- (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] a\u2020-- (using <area>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x (using <area>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -\u2020 (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -\u2020 (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -\u2020 (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -\u2020 (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -\u2020 (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -\u2020 (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -\u2020 (using <area>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.xn--nxa (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.xn--nxa (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.xn--nxa (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.xn--nxa (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.xn--nxa (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.xn--nxa (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.xn--nxa (using <area>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.\u03b2 (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.\u03b2 (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.\u03b2 (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.\u03b2 (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.\u03b2 (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.\u03b2 (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] -x.\u03b2 (using <area>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.xn--nxa (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.xn--nxa (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.xn--nxa (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.xn--nxa (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.xn--nxa (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.xn--nxa (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.xn--nxa (using <area>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.\u03b2 (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.\u03b2 (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.\u03b2 (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.\u03b2 (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.\u03b2 (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.\u03b2 (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] x-.\u03b2 (using <area>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0dc1\u0dca\u200d\u0dbb\u0dd3 (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0dc1\u0dca\u200d\u0dbb\u0dd3 (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0dc1\u0dca\u200d\u0dbb\u0dd3 (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0dc1\u0dca\u200d\u0dbb\u0dd3 (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0dc1\u0dca\u200d\u0dbb\u0dd3 (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0dc1\u0dca\u200d\u0dbb\u0dd3 (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0dc1\u0dca\u200d\u0dbb\u0dd3 (using <area>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0646\u0627\u0645\u0647\u200c\u0627\u06cc (using URL)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0646\u0627\u0645\u0647\u200c\u0627\u06cc (using URL.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0646\u0627\u0645\u0647\u200c\u0627\u06cc (using URL.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0646\u0627\u0645\u0647\u200c\u0627\u06cc (using <a>)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0646\u0627\u0645\u0647\u200c\u0627\u06cc (using <a>.host)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0646\u0627\u0645\u0647\u200c\u0627\u06cc (using <a>.hostname)

  ▶ Unexpected subtest result in /url/toascii.window.html:
  └ PASS [expected FAIL] \u0646\u0627\u0645\u0647\u200c\u0627\u06cc (using <area>)

  ▶ Unexpected subtest result in /url/url-origin.html:
  └ PASS [expected FAIL] Origin parsing: <https://fa\xdf.ExAmPlE/> against <about:blank>
```

**Comment by SimonSapin** [comment]
Updated expectations for `/url`.

@bors-servo r=Manishearth

**Comment by jdm** [comment]
```

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <https://x/>.host = '\xdf' IDNA Nontransitional_Processing

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <https://x/>.host = '\xdf' IDNA Nontransitional_Processing

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <https://fa\xdf.ExAmPlE/> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element.html:
  └ PASS [expected FAIL] Parsing: <https://fa\xdf.ExAmPlE/> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing: <https://fa\xdf.ExAmPlE/> against <about:blank>


  ▶ Unexpected subtest result in /url/url-origin.html:
  └ PASS [expected FAIL] Origin parsing: <https://fa\xdf.ExAmPlE/> against <about:blank>
```

**Comment by SimonSapin** [comment]
Not sure how those expectations weren’t updated in the previous run…

@bors-servo r=Manishearth

**Pull request merged**
