### PR TITLE
Assorted SpiderMonkey GC-related fixes

### PR DESCRIPTION
**Pull request by jdm**
These changes combined allow running a debug-mozjs Servo build with JS_GCZEAL=2,20 (ie. perform a GC every 20 allocations).

r? @Ms2ger

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6180)

### CODE REVIEW

**Comment by jdm** [comment]
@glennw These changes made the jQuery test suite hum along without incident for me.

**Comment by glennw** [comment]
@jdm Fantastic! Thank you for looking into it! :)

**Comment by michaelwu** [comment]
If https://github.com/servo/servo/pull/6150 can also run the jQuery test suite, I would prefer avoiding these changes. RootedVecs are fixed a bit differently and the issue with the global is part of a deeper issue that affects *all* dom objects being created/wrapped. The dom object being wrapped needs to be rooted while the wrapper is being setup because the dom object might point to other dom objects that aren't rooted.

**Comment by Ms2ger** [comment]
So when is `Void::reflector` called?

**Comment by nox** [comment]
@Ms2ger AFAIK, in the loop over dom_collections in RootedCollectionSet::trace().

**Comment by Ms2ger** [comment]
If we're going to do this, I'd like to split up `Void` into one for storing in `RootedVec` and one for `JS`.

**Comment by metajack** [comment]
After discussion with @jdm he split off #6247 for the stuff that makes jquery test suite work. This will remain open for now until after the SM upgrade lands and we can look at what's still useful.

**Comment by Ms2ger** [comment]
Please rebase on master.

**Comment by metajack** [comment]
JS upgrade landed. Is any of this still useful?

**Comment by jdm** [comment]
I suspect no.

**Pull request closed without merging**
