### PR TITLE
Remove util::vec::Comparator

### LINKED ISSUE #9696: Remove util::vec::Comparator
This fixes the following FIXME from @pcwalton:

```rust
/// FIXME(pcwalton): Workaround for lack of unboxed closures. This is called in
/// performance-critical code, so a closure is insufficient.
```

Unboxed closures landed a long time ago, so we can just use [`Vec::binary_search`](http://doc.rust-lang.org/std/vec/struct.Vec.html#method.binary_search) and [`Vec::binary_search_by`](http://doc.rust-lang.org/std/vec/struct.Vec.html#method.binary_search_by).

The following items need to go away from the module:
 * `Comparator`
 * `BinarySearchMethods`
 * `FullBinarySearchMethods`
 * `DefaultComparator`

In module `gfx::text::glyph`, calls to `binary_search_index` need to be replaced by calls to `Vec::binary_search` in `DetailedGlyphStore::detailed_glyphs_for_entry` and `DetailedGlyphStore::detailed_glyph_with_index`.

In module `gfx::text::text_run`, struct `CharIndexComparator` needs to be replaced by a closure passed to `Vec::binary_search_by` in `TextRun::index_of_first_glyph_run_containing`.

Files:
 * components/gfx/text/glyph.rs
 * components/gfx/text/text_run.rs
 * components/util/vec.rs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @nox 

Fixes #9696

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9792)

### CODE REVIEW

**Comment by nox** [comment]
```
   Compiling util_tests v0.0.1 (file:///home/servo/buildbot/slave/linux-dev/build/components/servo)
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:6:5: 6:35 error: unresolved import `util::vec::BinarySearchMethods`. There is no `BinarySearchMethods` in `util::vec` [E0432]
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:6 use util::vec::BinarySearchMethods;
                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:6:5: 6:35 help: run `rustc --explain E0432` to see a detailed explanation
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:12:41: 12:55 error: no method named `binary_search_` found for type `&[T]` in the current scope
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:12         assert!(test_match(&arr[i], arr.binary_search_(&arr[i])));
                                                                                                             ^~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:12:9: 12:67 note: in this expansion of assert! (defined in <std macros>)
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:21:23: 21:37 error: no method named `binary_search_` found for type `&[T]` in the current scope
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:21         let res = arr.binary_search_(&misses[i]);
                                                                                           ^~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:23:45: 23:59 error: no method named `binary_search_` found for type `&[T]` in the current scope
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:23         assert!(!test_match(&misses[i], arr.binary_search_(&misses[i])));
                                                                                                                 ^~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-dev/build/tests/unit/util/vec.rs:23:9: 23:74 note: in this expansion of assert! (defined in <std macros>)
error: aborting due to 3 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `util_tests`.
```

You need to update the unit tests, or maybe remove them given you removed that feature.

**Comment by nox** [comment]
Please squash.

**Comment by Ms2ger** [comment]
The most plausible issue here is that we need to reverse the `Ordering` values.

**Comment by nox** [comment]
@Ms2ger is right, seems like our own `binary_search_index_by` does the opposite of `Vec::binary_search_by`.

Please reverse the comparison function and we are good to go.

**Comment by GuillaumeGomez** [comment]
@nox: Done.

**Pull request merged**
