### PR TITLE
Avoid bloom filter churn.

### PR DESCRIPTION
**Pull request by nnethercote**
When a cached bloom filter is found during traversal, there are two
cases, both of which currently do unnecessary allocations. This patch
avoids these allocations. In the process, it renders correct two
previously-incorrect comments, and moves one of those comments into a
better spot.

While scrolling moderately fast all the way through the "Guardians of
the Galaxy" Wikipedia page, this patch (a) avoids 1.2 million calls to
`clone()` and (b) replaces 111,000 `BloomFilter::new()` calls with
`clear()` calls.

### CODE REVIEW

**Comment by nnethercote** [comment]
I tested locally that this change passes `./mach test-ref --kind=cpu`.

**Comment by pcwalton** [comment]
Oy, what an awful bug. Is that the cause of the memory bloat you saw?

**Comment by nnethercote** [comment]
At first I thought this was causing the bloat but when I fixed it the bloat was still there. That makes sense because the old bloom filter should be reclaimed each time when the new one replaces it in the thread-local storage. So I think this just causes lots of heap churn.

**Comment by nnethercote** [comment]
It would have been nice to squash the two commits before landing, but I guess bors' eagerness makes that difficult.

**Comment by brson** [comment]
Sweet wins!

**Pull request merged**
