### PR TITLE
rust-geom API changes

### PR DESCRIPTION
**Pull request by frewsxcv**
Shouldn't be merged until these have merged:

https://github.com/servo/rust-geom/pull/81

https://github.com/ecoal95/rust-offscreen-rendering-context/pull/13

https://github.com/servo/rust-layers/pull/178

~~I'll also need to update the Cargo lock files once they merge~~

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6349)

### CODE REVIEW

**Comment by nox** [comment]
Servo also needs servo/rust-geom#77 for #6237.

**Comment by nox** [comment]
```
/home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_egl/utils.rs:24:42: 24:62 error: unresolved name `egl::EGL_PBUFFER_BIT`
/home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_egl/utils.rs:24         egl::EGL_SURFACE_TYPE as EGLint, egl::EGL_PBUFFER_BIT as EGLint,
                                                                                                                                                                     ^~~~~~~~~~~~~~~~~~~~
```

-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 32 files reviewed, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6349)

**Comment by frewsxcv** [comment]
@nox I just `cargo update`d egl since I think it needed an upgrade. Can I get a retry?

**Comment by jdm** [comment]
This might overlap with #6356.

**Comment by frewsxcv** [comment]
Merge conflicts addressed

**Comment by frewsxcv** [comment]
Ah okay now it looks like there actually compilation issues. Will address those now

**Comment by frewsxcv** [comment]
Okay, hopefully I got everything now (had to rebase to pick up a few changes)

**Comment by frewsxcv** [comment]
Missing import in cef, just fixed it

**Pull request merged**
