### PR TITLE
style: Unbox a bunch of color properties.

### PR DESCRIPTION
**Pull request by emilio**
This builds on https://github.com/servo/rust-cssparser/pull/118.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15518)

### CODE REVIEW

**Comment by jdm** [comment]
The linux builder suddenly does not like osmesa, apparently :<

**Comment by SimonSapin** [comment]
Reviewed 25 of 25 files at r1, 1 of 1 files at r3.
Review status: 24 of 37 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/properties/helpers/animated_properties.mako.rs, line 523 at r1](https://reviewable.io:443/reviews/servo/servo/15518#-KcsOs_v_nyfTnl2LFfA:-KcsOs_wibnYFX_NJE2k:b-ixwf9y) ([raw file](https://github.com/servo/servo/blob/eda923ba1980a1668bf90724ca3ed5e112879910/components/style/properties/helpers/animated_properties.mako.rs#L523)):*
> ```Rust
>                                    .interpolate(&(other.green() * other.alpha()), progress))
>                                    * 1. / alpha);
>             let blue = clamp(try!((self.blue() * self.alpha())
> ```

I think `clamp` can be removed here, `RGBA::from_floats` already clamps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15518)*

**Comment by SimonSapin** [comment]
I can reproduce on Linux:
```rust
	thread 'animated_properties::test_rgba_color_interepolation_out_of_range_2' panicked at 'assertion failed: `(left == right)` (left: `RGBA(RGBA { red: 0, green: 152, blue: 0, alpha: 76 })`, right: `RGBA(RGBA { red: 0, green: 154, blue: 0, alpha: 77 })`)', /home/simon/servo/tests/unit/style/animated_properties.rs:33
	thread 'animated_properties::test_rgba_color_interepolation_alpha' panicked at 'assertion failed: `(left == right)` (left: `RGBA(RGBA { red: 66, green: 133, blue: 0, alpha: 150 })`, right: `RGBA(RGBA { red: 67, green: 133, blue: 0, alpha: 150 })`)', /home/simon/servo/tests/unit/style/animated_properties.rs:17
	thread 'animated_properties::test_rgba_color_interepolation_out_of_range_1' panicked at 'assertion failed: `(left == right)` (left: `RGBA(RGBA { red: 152, green: 0, blue: 0, alpha: 76 })`, right: `RGBA(RGBA { red: 154, green: 0, blue: 0, alpha: 77 })`)', /home/simon/servo/tests/unit/style/animated_properties.rs:26
```

**Comment by emilio** [comment]
@bors-servo try

Yeah, those were adjustments I had to do before due to the floating point round errors that are no longer so severe.

**Comment by emilio** [comment]
Ouch, these are legit, even though I believe we should be using the stored value? huh. 

```
  ▶ Unexpected subtest result in /cssom/serialize-values.html:
  │ FAIL [expected PASS] background-color: rgba(5, 7, 10, 0.5)
  │   → assert_equals: background-color raw inline style declaration expected "rgba(5, 7, 10, 0.5)" but got "rgba(5, 7, 10, 0.502)"
  │ FAIL [expected PASS] border-top-color: rgba(5, 7, 10, 0.5)
  │   → assert_equals: border-top-color raw inline style declaration expected "rgba(5, 7, 10, 0.5)" but got "rgba(5, 7, 10, 0.502)"
  │ FAIL [expected PASS] border-right-color: rgba(5, 7, 10, 0.5)
  │   → assert_equals: border-right-color raw inline style declaration expected "rgba(5, 7, 10, 0.5)" but got "rgba(5, 7, 10, 0.502)"
  │ FAIL [expected PASS] border-bottom-color: rgba(5, 7, 10, 0.5)
  │   → assert_equals: border-bottom-color raw inline style declaration expected "rgba(5, 7, 10, 0.5)" but got "rgba(5, 7, 10, 0.502)"
  │ FAIL [expected PASS] border-left-color: rgba(5, 7, 10, 0.5)
  │   → assert_equals: border-left-color raw inline style declaration expected "rgba(5, 7, 10, 0.5)" but got "rgba(5, 7, 10, 0.502)"
  │ FAIL [expected PASS] color: rgba(5, 7, 10, 0.5)
  │   → assert_equals: color raw inline style declaration expected "rgba(5, 7, 10, 0.5)" but got "rgba(5, 7, 10, 0.502)"
  │ FAIL [expected PASS] outline-color: rgba(5, 7, 10, 0.5)
  │   → assert_equals: outline-color raw inline style declaration expected "rgba(5, 7, 10, 0.5)" but got "rgba(5, 7, 10, 0.502)"
  │ 
  │ run_individual_test/<@http://web-platform.test:8000/cssom/serialize-values.html:234:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  │ run_individual_test@http://web-platform.test:8000/cssom/serialize-values.html:230:7
  │ test_property@http://web-platform.test:8000/cssom/serialize-values.html:245:14
  └ @http://web-platform.test:8000/cssom/serialize-values.html:593:7
```

**Comment by emilio** [comment]
Of course those properties still use `cssparser::Color` instead of the one that preserves serialization, sigh.

**Comment by emilio** [comment]
Hhmm... Or maybe I'm wrong, huh

**Comment by emilio** [comment]
The reason this works in Gecko: http://searchfox.org/mozilla-central/source/layout/style/nsStyleUtil.cpp#702

**Comment by emilio** [comment]
@SimonSapin, Gecko rounds `a * 255` instead of flooring `a * 256`. I believe our behavior is better though, but worth keeping in mind. cc @upsuper.

**Comment by SimonSapin** [comment]
Interesting. I do think we should copy Gecko’s behavior of rounding to 2 decimal digits if that round-trips to the same `u8` value, falling back to 3 if not. Wanna do the cssparser change?

**Comment by SimonSapin** [comment]
To be clear, the above is only for serialization, not for gfx APIs that use floats.

**Comment by emilio** [comment]
Sure, makes sense

**Comment by SimonSapin** [comment]
```
  ▶ CRASH [expected OK] /navigation-timing/nav2_test_open_data_uri.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ ERROR:script::dom::bindings::error: Error at data:text/html;charset=utf-8,%3C%21DOCTYPE%20html%3E%0D%0A%3Ctitle%3Edata%20URL%20source%20for%20navigation-timing%2Fnav2_test_open_data_uri.html%3C%2Ftitle%3E%0D%0A%3C%21--%20NB%3A%20this%20file%20isn%27t%20actually%20used%20any%20where%21%20--%3E%0D%0A%3Clink%20rel%3D%22author%22%20title%3D%22Google%22%20href%3D%22http%3A%2F%2Fwww.google.com%2F%22%20%2F%3E%0D%0A%3Cscript%3E%0D%0Avar%20observer%20%3D%20new%20PerformanceObserver%28%0D%0A%20%20%20%20function%20%28entryList%29%20%7B%0D%0A%20%20%20%20%20%20%20%20parent.postMessage%28%22observed%22%2C%20%22%2A%22%29%3B%0D%0A%20%20%20%20%20%20%20%20observer.disconnect%28%29%3B%0D%0A%20%20%20%20%7D%29%3B%0D%0Aobserver.observe%28%7BentryTypes%3A%20%5B%22navigation%22%5D%7D%29%3B%0D%0A%3C%2Fscript%3E%0D%0A:6:5 PerformanceObserver is not defined
  │ called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) } (thread RenderBackend, at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:868)
  │ stack backtrace:
  │    0:     0x7fb6b65ebd7d - backtrace::backtrace::trace::h976012eed768c7ff
  │    1:     0x7fb6b65ec262 - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
  │    2:     0x7fb6b4f64617 - servo::main::{{closure}}::h039ba3c803113243
  │    3:     0x7fb6b6dd06f8 - std::panicking::rust_panic_with_hook
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:556
  │    4:     0x7fb6b6dd05c4 - std::panicking::begin_panic<collections::string::String>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
  │    5:     0x7fb6b6dd04e9 - std::panicking::begin_panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
  │    6:     0x7fb6b6dd0477 - std::panicking::rust_begin_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
  │    7:     0x7fb6b6dfdc3d - core::panicking::panic_fmt
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
  │    8:     0x7fb6b66349cd - core::result::unwrap_failed::h4e1dafabda202b02
  │    9:     0x7fb6b6689a9e - webrender::render_backend::RenderBackend::run::h806d46e08283bc83
  │   10:     0x7fb6b66263dc - std::panicking::try::do_call::h7d57ef86fec8f13f
  │   11:     0x7fb6b6dd763a - panic_unwind::__rust_maybe_catch_panic
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  │   12:     0x7fb6b663dfc7 - <F as alloc::boxed::FnBox<A>>::call_box::h232db978e3695021
  │   13:     0x7fb6b6dcf384 - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:623
  │                          - std::sys_common::thread::start_thread
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  │   14:     0x7fb6b2e32183 - start_thread
  │   15:     0x7fb6b294937c - clone
  │   16:                0x0 - <unknown>
  │ ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }) }
  └ Pipeline failed in hard-fail mode.  Crashing!

**Comment by emilio** [comment]
That is #14323, the rest seems green

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 19 of 19 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15518#-:-Kcy3cGn1VlS2SREFDBA:bkg9nno)*

**Pull request merged**
