### PR TITLE
resource: Remove the duplicated config from pref.json

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because
  - just clean up.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12205)

### CODE REVIEW

**Comment by saneyuki** [comment]
@Ms2ger @frewsxcv should we sort members in this file?

**Comment by ConnorGBrewster** [comment]
Could we do this on package-prefs.json as well?

**Comment by frewsxcv** [comment]
@bors-servo r-

> Could we do this on package-prefs.json as well?

Yeah, would be good to get rid of the duplicate there too.

> @Ms2ger @frewsxcv should we sort members in this file?

Would be nice. If you do it in this PR, please make it a separate commit.

**Comment by aneeshusa** [comment]
Can we also add a test for duplicates? This can be done with Python's `json` module [with a custom `object_pairs_hook`](https://docs.python.org/2/library/json.html#repeated-names-within-an-object). We could also file a follow-up E-easy for that, if we don't want to do it now.

**Comment by aneeshusa** [comment]
Refreshed and saw the extra comments about sorting; a custom `object_pairs_hook` could also check for sorting.

**Comment by saneyuki** [comment]
If we have some duplicate check, I think we don't have to add a sort checker.

**Comment by jdm** [comment]
Sorting is useful for other reasons than just detecting duplicates.

**Comment by frewsxcv** [comment]
Sorry I didn't make it clearer with my earlier comment, I was waiting for the change to package-prefs.json before r+ing this.

**Comment by saneyuki** [comment]
@frewsxcv 

Sorry, I missed the comment about `package-prefs.json`. I updated the patch.

**Pull request merged**
