### PR TITLE
Edge-distance anti-aliasing for transformed rectangles

### PR DESCRIPTION
**Pull request by mrobinson**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12786)

### CODE REVIEW

**Comment by mrobinson** [comment]
@glennw r?

**Comment by emilio** [comment]
@mrobinson: I think the PR should be against https://github.com/servo/webrender, and make a WR update. IIRC the shaders in `resources/` are just a copy of the ones in WR.

**Comment by glennw** [comment]
@mrobinson Yep the general changes look fine, but this PR can be made against servo/webrender in the master branch now (wr2 has been landed). I abstracted some of the transform code into a common function, but I don't think it will be too hard to rebase over (let me know if you have any issues).

**Comment by mrobinson** [comment]
Ah! Thanks for the pointer. I've moved this PR here: https://github.com/servo/webrender/pull/334

**Pull request closed without merging**
