### PR TITLE
Improve decisions in compositor over when to draw a frame.

### PR DESCRIPTION
**Pull request by glennw**
This patch fixes a couple of issues in the compositor:

1) Remove the delayed composition code. Previously, this would schedule
   a composite for 12ms in the future. This doesn't really make any sense
   with WR. There's no point in doing a composite unless WR has provided
   a new frame to be drawn. This fixes issues in several benchmarks where
   we were doing multiple composite / renders per rAF, which is a waste
   of CPU time. This *does* make the framerate slower in some cases (such
   as a slow rAF callback) but it's more correct - otherwise we were just
   compositing the same frame multiple times for no real benefit.

2) Inform the window of the current animation state of the compositor.
   Specifically, if an animation (or rAF) is currently active, the
   window system switches to use event polling, and does not block on
   the OS-level event loop. In the case of active animation, we just
   assume that we want to be running as the vsync interval and not
   blocking. This means the compositor thread only sleeps on vsync
   during animation, which reduces OS scheduling and results in much
   smoother animation.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17398)

### CODE REVIEW

**Comment by glennw** [comment]
r? @pcwalton 

I think the above comments are all correct, and this certainly results in smoother results and "correct" frame rates based on rAF, from what I've tested is. Nonetheless, changing things like this is quite subtle, and I might be missing something - so this could do with a careful look over!

**Comment by glennw** [comment]
Thread profile before this change (showing multiple composites per rAF etc):

servo

Thread profile after this change - the parallelism is what I would expect to see, given the threads involved:

correct

**Comment by glennw** [comment]
cc @asajeffrey and @cbrewster since I think you've been working in this area and may have comments.

**Comment by glennw** [comment]
Fixed tidy error.

**Comment by jdm** [comment]
```
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/canvas/buffer-offscreen-test.html", "line": 293680, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/canvas/buffer-offscreen-test.html", "line": 293685, "message": null, "expected": "OK"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/canvas/buffer-preserve-test.html", "line": 293797, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/canvas/buffer-preserve-test.html", "line": 293803, "message": null, "expected": "OK"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/canvas/framebuffer-bindings-unaffected-on-resize.html", "line": 294028, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/canvas/framebuffer-bindings-unaffected-on-resize.html", "line": 294039, "message": null, "expected": "OK"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/canvas/texture-bindings-unaffected-on-resize.html", "line": 294263, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/canvas/texture-bindings-unaffected-on-resize.html", "line": 294268, "message": null, "expected": "OK"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/extensions/oes-texture-float-with-canvas.html", "line": 296324, "message": null, "expected": "ERROR"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/extensions/oes-texture-half-float-with-canvas.html", "line": 296357, "message": null, "expected": "ERROR"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/extensions/webgl-compressed-texture-size-limit.html", "line": 296389, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/extensions/webgl-compressed-texture-size-limit.html", "line": 296391, "message": null, "expected": "OK"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/state/state-uneffected-after-compositing.html", "line": 325840, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/state/state-uneffected-after-compositing.html", "line": 325842, "message": null, "expected": "OK"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-canvas-rgb565.html", "line": 328225, "message": null, "expected": "ERROR"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-canvas-rgba4444.html", "line": 328235, "message": null, "expected": "ERROR"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-canvas-rgba5551.html", "line": 328717, "message": null, "expected": "ERROR"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-canvas.html", "line": 328853, "message": null, "expected": "ERROR"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas-rgb565.html", "line": 329648, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas-rgb565.html", "line": 329651, "message": null, "expected": "OK"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas-rgba4444.html", "line": 329820, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas-rgba4444.html", "line": 329823, "message": null, "expected": "OK"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas-rgba5551.html", "line": 329841, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas-rgba5551.html", "line": 329845, "message": null, "expected": "OK"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas.html", "line": 329970, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas.html", "line": 329973, "message": null, "expected": "OK"}
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/texture-size-limit.html", "line": 330387, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/texture-size-limit.html", "line": 330451, "message": null, "expected": "OK"}
{"status": "TIMEOUT", "stack": null, "subtest": "Concurrent requestAnimationFrame loops are deterministic", "action": "test_result", "test": "/_mozilla/mozilla/deterministic-raf.html", "line": 340405, "message": "Test timed out", "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/_mozilla/mozilla/deterministic-raf.html", "line": 340406, "message": null, "expected": "OK"}
```

**Comment by glennw** [comment]
Removing the delayed compositor timer exposed a bug in how we handle rAF callbacks that don't mutate the DOM. Added a second commit to handle that.

r? @jdm

**Comment by glennw** [comment]
(or anyone else who knows the DOM code well enough to review that).

**Comment by glennw** [comment]
@bors-servo r-

I'm seeing a few demos not animating correctly locally. I need to investigate more to see if it's related to this change.

**Comment by glennw** [comment]
Added a follow up commit that addresses an issue I ran into.

r? @jdm

**Comment by jdm** [comment]
@bors-servo: retry
* servo-mac5 timed out on a bunch of builds but seems to be working fine now

**Pull request merged**
