### PR TITLE
Introduce a PropertyId enum and use it instead of strings of property names

### PR DESCRIPTION
**Pull request by SimonSapin**
* `LonghandId` and `ShorthandId` are C-like enums
* `Atom` is used for the name of custom properties.
* `PropertyDeclarationId` is the identifier for `PropertyDeclaration`,
  after parsing and shorthand expansion. (Longhand or custom property.)
* `PropertyId` represents any CSS property, e.g. in CSSOM.
  (Longhand, shorthand, or custom.)

CC @upsuper 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14535)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@upsuper I’ve added a first pass at `PropertyId::from_nscsspropertyid`, but it’s not pretty.

**Comment by mbrubeck** [comment]
r=mbrubeck with this `test-unit` error fixed:

```
   Compiling style_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/style)
error: no rules expected the token `"top"`
   --> /home/travis/build/servo/servo/tests/unit/style/stylist.rs:104:51
    |
104 |     assert_eq!(1, selector_map.id_hash.get(&atom!("top")).unwrap()[0].source_order);
    |                                                   ^^^^^
error: Could not compile `style_tests`.
```

**Comment by mbrubeck** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 5 of 5 files at r1, 10 of 10 files at r2, 7 of 7 files at r3, 8 of 8 files at r4, 6 of 6 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/14535#-:-KYa1bdmBPYblOlHsbvt:bo47p9t)*

**Comment by SimonSapin** [comment]
Fixed.

@bors-servo r=mbrubeck

**Pull request merged**
