### PR TITLE
Finish the implementation of the HTMLMediaElement canPlayType method

### LINKED ISSUE #22299: Implement HTMLMediaElement canPlayType()
Spec: https://html.spec.whatwg.org/multipage/media.html#dom-navigator-canplaytype

### PR DESCRIPTION
**Pull request by georgeroman**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22299 

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23229)

### CODE REVIEW

**Review by ferjm — APPROVED** [review]
r=me, once Travis and CI are happy. Thanks!

As a follow-up, it would be nice to move [the OGG exception](https://github.com/servo/servo/blob/master/components/script/dom/htmlmediaelement.rs#L1664) to servo/media.

**Comment by georgeroman** [comment]
Yeah, sure, I'll do it it!

**Comment by georgeroman** [comment]
It looks like the `parse` method of the `mime` crate fails with a `FromStrError { inner: MissingEqual }` error if given a parameter without an associated equal sign and this makes [this](https://github.com/web-platform-tests/wpt/blob/0a4f439934918ec5820c5232cf3366c5694a4b64/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html#L64) test fail.

**Comment by ferjm** [comment]
```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "audio/webm; codecs=\"opus\" (optional)", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201212, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "audio/webm; codecs=\"vorbis\" (optional)", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201213, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: expected true but got false", 
    "stack": "type_codecs_test/<@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:111:5\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1587:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\ntype_codecs_test@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:109:3\n@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:118:1\n", 
    "subtest": "audio/webm with and without codecs", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201215, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "video/webm; codecs=\"opus\" (optional)", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201244, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "video/webm; codecs=\"vorbis\" (optional)", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201245, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "video/webm; codecs=\"vp8\" (optional)", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201246, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "video/webm; codecs=\"vp8.0\" (optional)", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201247, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "video/webm; codecs=\"vp9\" (optional)", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201248, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "video/webm; codecs=\"vp9.0\" (optional)", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201249, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: expected true but got false", 
    "stack": "type_codecs_test/<@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:111:5\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1587:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\ntype_codecs_test@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:109:3\n@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:122:1\n", 
    "subtest": "video/webm with and without codecs", 
    "test": "/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html", 
    "line": 201253, 
    "action": "test_result", 
    "expected": "PASS"
}
```

There are also some tests passing now.

This is going to be slightly tricky, as it depends on which plugins are installed on CI. So I guess you will have to manually change the test expectations if your local GStreamer setup does not match the one we have on CI.

**Comment by ferjm** [comment]
@bors-servo try retry

* https://github.com/servo/intermittent-failure-tracker/issues/5

**Comment by ferjm** [comment]
Ugh, I missed the Magic Leap error. It seems that the Magic Leap build is not ready for https://github.com/servo/media/commit/c9cee94e1003cb01d0460017ea05748a4dc79259 yet.

**Comment by georgeroman** [comment]
I'll wait until the the Magic Leap is ready. Also, building servo with the latest servo-media fails due to the changes in https://github.com/servo/media/commit/2aafa4bc79c40ab92ba8a35ca73ab1e1d4c818c7.

**Comment by jdm** [comment]
https://github.com/servo/servo/issues/23242 is the right way to deal with that issue, and will avoid similar ones in the future.

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:
  │ FAIL [expected PASS] audio/webm with and without codecs
  │   → assert_equals: expected true but got false
  │ 
  │ type_codecs_test/<@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:111:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1587:20
  │ test@http://web-platform.test:8000/resources/testharness.js:544:21
  │ type_codecs_test@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:109:3
  └ @http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:118:1

  ▶ Unexpected subtest result in /html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:
  │ FAIL [expected PASS] video/webm with and without codecs
  │   → assert_equals: expected true but got false
  │ 
  │ type_codecs_test/<@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:111:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1587:20
  │ test@http://web-platform.test:8000/resources/testharness.js:544:21
  │ type_codecs_test@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:109:3
  └ @http://web-platform.test:8000/html/semantics/embedded-content/media-elements/mime-types/canPlayType.html:122:1
```

**Comment by ferjm** [comment]
@georgeroman it seems that we need to tune the test expectations a little bit more

**Comment by ferjm** [comment]
Thanks @georgeroman !

**Pull request merged**
