### PR TITLE
Remove SubpageId.

### PR DESCRIPTION
**Pull request by glennw**
This changes PipelineId to be a UUID and removes the concept of SubpageId.

Iframes are now able to generate their own pipeline ID during navigation which simplifies a lot of logic in other parts of the code.

Other parts of the code, such as the compositor and layout only ever deal with pipeline ids.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7792)

### CODE REVIEW

**Comment by glennw** [comment]
@jdm @Ms2ger What are your thoughts on this change?

I thought I'd prototype this and I think it worked out OK. All the ref, wpt and css tests pass, and real web sites I've tested seem to work OK.

I haven't been able to test with servo-shell yet, as it's broken in other ways at the moment.

But I wanted to get your thoughts on whether this was a reasonable approach, and if so I'll do a bit more testing before I get you to review it.

**Comment by jdm** [comment]
I admit that this change makes me nervous due to the possibility of UUID collision, but I don't actually know how concerned I should be about that.

**Comment by glennw** [comment]
The last two paragraphs of https://en.wikipedia.org/wiki/Universally_unique_identifier#Random_UUID_probability_of_duplicates are informative.

**Comment by jdm** [comment]
True! That being said, I am also concerned about multiprocess Servo where each content process is using a different seed, which the article does call out as a separate problem.

**Comment by glennw** [comment]
@jdm What about something like the last commit? PipelineId becomes a tuple of (namespace id, index) and there is a namespace per script thread (plus the constellation). I'm not sure about the naming of the structs, but the concept seems reasonable to me. Thoughts?

**Comment by Ms2ger** [comment]
I don't have a good mental model of what these are used for. Could an attacker gain anything by causing collisions?

**Comment by glennw** [comment]
I'm not sure - perhaps - but I prefer the changes in the last commit anyway, which remove the reliance on UUIDs and guarantee a unique pipeline ID.

**Comment by glennw** [comment]
Removing in favour of doing this in small increments - first step is #7807

**Pull request closed without merging**
