### PR TITLE
Refactor FormData code to match updated spec

### PR DESCRIPTION
**Pull request by KiChjang**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9049)

### CODE REVIEW

**Comment by KiChjang** [comment]
Haven't written tests for `formdata.set()` yet.

**Comment by KiChjang** [comment]
Tests for `formdata.set()` has been committed, I think this is  ready to be reviewed.

**Comment by eefriedman** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/formdata.rs, line 129 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9049#-K6KTvx3bm8RZz3nr_j5:-K6KTvx8lt4nc-mP71Xh:-824718312) ([raw file](https://github.com/servo/servo/blob/51e7bbe2ab33ac451732d55513632e163738b0ea/components/script/dom/formdata.rs#L129)):*
`is_none()` then `unwrap()` is an anti-pattern.  Use match instead.

---

*[components/script/dom/webidls/FormData.webidl, line 22 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9049#-K6KSGQyM1PNC9Fyee4n:-K6KSGQzIt9ECzikwY-g:2093699396) ([raw file](https://github.com/servo/servo/blob/51e7bbe2ab33ac451732d55513632e163738b0ea/components/script/dom/webidls/FormData.webidl#L22)):*
Hmm... implementing iterable is going to be kind of awkward with the hashtable representation.  Not something that needs to be fixed in this patch.

---

*[tests/wpt/metadata/XMLHttpRequest/formdata-set.htm.ini, line 5 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9049#-K6KTYvShfKkL-m5a6ue:-K6KTYvShfKkL-m5a6uf:1302058304) ([raw file](https://github.com/servo/servo/blob/51e7bbe2ab33ac451732d55513632e163738b0ea/tests/wpt/metadata/XMLHttpRequest/formdata-set.htm.ini#L5)):*
Do you know why these tests are failing?  They don't obviously depend on any unimplemented functions.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9049)*

**Comment by KiChjang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/wpt/metadata/XMLHttpRequest/formdata-set.htm.ini, line 5 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9049#-K6KTYvShfKkL-m5a6ue:-K6L5RAFgswFd6grmgjV:145364347) ([raw file](https://github.com/servo/servo/blob/51e7bbe2ab33ac451732d55513632e163738b0ea/tests/wpt/metadata/XMLHttpRequest/formdata-set.htm.ini#L5)):*
testFormDataSetEmptyBlob actually does depend on the constructor for File objects, which we don't support yet.

As for "Passing a String object to FormData.set should work", it depends on the implementation of XHR responseText and onload.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9049)*

**Comment by eefriedman** [comment]
r=me after squash.

**Comment by jdm** [comment]
@bors-servo: retry 
* #9112

**Pull request merged**
