### PR TITLE
Validate MIME pattern checking

### PR DESCRIPTION
**Pull request by jongiddy**
The MIME detector for a HTML file contains an additional byte in the mask.  While it doesn't hurt, it is not used in the byte matching code (since it is zipped with the `pattern` iterator).

I'm not clear how to test this within the `servo` code. The fix doesn't change any externally visible behavior. A test to validate the `ByteMatcher` structures would require the private ByteMatcher structures to be visible to the test. I could use a sub-module, as described at https://doc.rust-lang.org/book/testing.html#the-tests-module but this pattern doesn't appear anywhere else in the `servo` code.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9631)

### CODE REVIEW

**Comment by jdm** [comment]
I'd like to try to find a way to continue using the exact string specified in the [specification](https://mimesniff.spec.whatwg.org/#supplied-mime-type-detection-algorithm) if possible.

**Comment by jdm** [comment]
I wonder if the code actually checks for tag-terminating bytes properly right now?

**Comment by jongiddy** [comment]
All the other patterns have dropped the mask byte for the tag-terminating byte, as it is detected separately after the main match without using the mask - see https://github.com/servo/servo/blob/c929dbe2530f979ce6e84d5a25ea47318ff0910e/components/net/mime_classifier.rs#L311

The code is tested with trailing spaces or `<` terminators. A test could also be added that fails on an invalid tag-terminating byte, to check that the code works as expected.

**Comment by jongiddy** [comment]
Another advantage of adding internal unit tests for `ByteMatcher` would be that as well as checking that mask length is equal to pattern length, it would be possible to check that `pattern & mask == pattern`, allowing this to be eliminated from https://github.com/servo/servo/blob/c929dbe2530f979ce6e84d5a25ea47318ff0910e/components/net/mime_classifier.rs#L288

Again, not really sure how private scope objects are unit tested here.

**Comment by jdm** [comment]
Currently they're made public and added to the tests under tests/unit :)

**Comment by jongiddy** [comment]
I have added a `validate` function to check that each MIME checker is sane. The unit test uses this function, allowing other objects to remain private.  I've done this because unit tests and visibility are complementary methods for ensuring correctness and making future change easier, so I don't like to compromise one to support the other.

Later, other validations can be added to this function. For example, checking that `pattern & mask == pattern` as described above.

**Comment by jdm** [comment]
These changes are really great! Thank you for being so thorough in looking through this code :)

**Pull request merged**
