### PR TITLE
When webdriver is getting a pipeline id, it should wait for the pipeline document to be ready

### LINKED ISSUE #11117: Webdriver panics when there isn't a root page
Running webdriver test https://github.com/w3c/web-platform-tests/blob/master/webdriver/navigation.py#L115 on Servo causes panic:
```
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "stack backtrace:"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "ERROR:compositing::constellation: Panic: called `Option::unwrap()` on a `None` value"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "ERROR:compositing::constellation: Backtrace:"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #0  - 0x000055e6bb6d9db8 - backtrace::backtrace::libunwind::trace"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/backtrace-0.2.1/src/backtrace/libunwind.rs:54"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               - backtrace::backtrace::trace<closure>"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/backtrace-0.2.1/src/backtrace/mod.rs:70"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #1  - 0x000055e6bb6d9c6a - backtrace::capture::{{impl}}::new"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/target/debug/build/backtrace-bb3ee46349d51739/out/capture.rs:79"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #2  - 0x000055e6ba1b927c - util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfb85bd26ec8873e5"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #3  - 0x000055e6ba1bb8ed - extern $u22$rust.call$u22$$u20$fn$LP$$u5b$closure$SP$DefId$u20$$u7b$$u20$krate.$u20$45$C$$u20$node.$u20$DefIndex$LP$2975$RP$$u20$$u7d$$u20$0.ipc_channel..ipc..IpcSender$LT$$LP$core..option..Option$LT$msg..constellation_msg..PipelineId$GT$$C$$u20$std..string..String$C$$u20$std..string..String$RP$$GT$$C$$u20$1.core..option..Option$LT$msg..constellation_msg..PipelineId$GT$$u5d$$C$$u20$$LP$$RF$$u27$static$u20$core..any..Any$u20$$u2b$$u20$$u27$static$C$$RP$$RP$::once_shim.164427::h3fbae899f360275b"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #4  - 0x000055e6ba1bb89c - alloc::boxed::{{impl}}::call_box<(&Any),closure>"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ ../src/liballoc/boxed.rs:541"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #5  - 0x000055e6bb6662dc - util::panicking::initiate_panic_hook::{{closure}}::{{closure}}::{{closure}}"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/util/panicking.rs:44"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #6  - 0x000055e6bb665e89 - std::thread::local::{{impl}}::with<core::cell::RefCell<core::option::Option<util::panicking::PanicHandlerLocal>>,closure,()>"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ ../src/libstd/thread/local.rs:211"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #7  - 0x000055e6bb665d0a - util::panicking::initiate_panic_hook::{{closure}}::{{closure}}"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/util/panicking.rs:41"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #8  - 0x000055e6bc154553 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #9  - 0x000055e6bc155f98 - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #10 - 0x000055e6bc1662f1 - rust_begin_unwind"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #11 - 0x000055e6bc1a589f - core::panicking::panic_fmt::h257ceb0aa351d801"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #12 - 0x000055e6bc1a5b78 - core::panicking::panic::h4bb1497076d04ab9"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #13 - 0x000055e6ba224bb2 - core::option::{{impl}}::unwrap<&alloc::rc::Rc<script::page::Page>>"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ ../src/libcore/macros.rs:21"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #14 - 0x000055e6ba0bae60 - script::script_thread::{{impl}}::root_page"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:597"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #15 - 0x000055e6ba25a09e - script::script_thread::{{impl}}::handle_webdriver_msg"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:995"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #16 - 0x000055e6ba2564ed - script::script_thread::{{impl}}::handle_msg_from_constellation"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:901"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #17 - 0x000055e6ba254b15 - script::script_thread::{{impl}}::handle_msgs::{{closure}}"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:766"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #18 - 0x000055e6ba254760 - script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:858"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #19 - 0x000055e6ba227078 - script::script_thread::{{impl}}::handle_msgs"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:759"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #20 - 0x000055e6ba1cec5c - script::script_thread::{{impl}}::start"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:617"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #21 - 0x000055e6ba1ceb30 - script::script_thread::{{impl}}::create::{{closure}}::{{closure}}"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:469"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #22 - 0x000055e6ba1ce821 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>>"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/profile_traits/mem.rs:59"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #23 - 0x000055e6ba1bc059 - script::script_thread::{{impl}}::create::{{closure}}"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ /home/ajeffrey/github/asajeffrey/servo/components/script/script_thread.rs:468"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #24 - 0x000055e6ba1b8bb6 - util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::h153e74df3e754d9f"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #25 - 0x000055e6ba1b83f3 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hdf1a857f1b00da32"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #26 - 0x000055e6ba1b8368 - std::sys_common::unwind::try::try_fn<closure>"
 0:04.18 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ ../src/libstd/sys/common/unwind/mod.rs:127"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #27 - 0x000055e6bc16627b - __rust_try"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #28 - 0x000055e6bc16620d - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #29 - 0x000055e6ba1b82a5 - std::sys_common::unwind::try<closure>"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ ../src/libstd/sys/common/unwind/mod.rs:123"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #30 - 0x000055e6ba1b80e1 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h4f3ea0e65664ee46"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #31 - 0x000055e6ba1b8da7 - alloc::boxed::{{impl}}::call_box<(),closure>"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "                               @ ../src/liballoc/boxed.rs:541"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #32 - 0x000055e6bc16ccd4 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #33 - 0x00007f99892bb6a9 - start_thread"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #34 - 0x00007f9988dd9e9c - clone"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "frame #35 - 0x0000000000000000 - <unknown>"
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) ""
 0:04.19 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:6697) "ERROR:compositing::constellation: Pipeline failed in hard-fail mode.  Crashing!"
```
The root cause is https://github.com/servo/servo/blob/master/components/script/script_thread.rs#L995, which calls `self.root_page()` when a webdriver message arrives, generating a panic if there isn't a root page yet. (Navigation can cause a fresh script thread to be created, with root page initialized at `None`.)

cc @jgraham

### PR DESCRIPTION
**Pull request by asajeffrey**
Thank you for contributing to Servo! Please add an `X` inside each `[ ]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11117 (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they only impact webdriver

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11140)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/compositing/constellation.rs, line 1397 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11140#-KHWr6BinDhANnSC6qJj:-KHWr6BinDhANnSC6qJk:-1387044704) ([raw file](https://github.com/servo/servo/blob/00a8efe9fd223fc2a0fd24443655b7a6efd61d92/components/compositing/constellation.rs#L1397)):*
> ```Rust
>             .and_then(|frame_id| self.frames.get(&frame_id))
>             .map(|frame| frame.current);
>         let current_pipeline_id_loaded = current_pipeline_id
> ```

I think you should just merge this into the previous line like `.map(|frame| (frame.current, true))`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11140)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/compositing/constellation.rs, line 1397 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11140#-KHWr6BinDhANnSC6qJj:-KHX-ajmj7wS4ORUm-W8:16128244) ([raw file](https://github.com/servo/servo/blob/00a8efe9fd223fc2a0fd24443655b7a6efd61d92/components/compositing/constellation.rs#L1397)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I think you should just merge this into the previous line like `.map(|frame| (frame.current, true))`</details>
We use `current_pipeline_id` later on in `.find(|x| x.old_pipeline_id == current_pipeline_id)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11140)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[components/compositing/constellation.rs, line 1397 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11140#-KHWr6BinDhANnSC6qJj:-KHYXzRtjteHC_om6pVp:-946531349) ([raw file](https://github.com/servo/servo/blob/00a8efe9fd223fc2a0fd24443655b7a6efd61d92/components/compositing/constellation.rs#L1397)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> We use `current_pipeline_id` later on in `.find(|x| x.old_pipeline_id == current_pipeline_id)`.</details>
Well I can't read. I guess that doesn't preclude it, but sure, this is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11140)*

**Comment by Ms2ger** [comment]
That was #8815

**Pull request merged**
