### PR TITLE
Focus events

### PR DESCRIPTION
**Pull request by j3parker**
This is my first pass at #7981 

Looking for some early feedback. I'm not sure that what I'm doing in `commit_focus_transaction` is 100% correct and I'm still trying to wrap my head around the spec (focusing/unfocusing/focus update steps.) I'm only doing `focus`/`focusout` at the moment while I try to understand what's going on.

When I combine this with what I have in #7757 things seem to work. What would be the best way of adding tests for something like this independent of that other issue?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7985)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/document.rs, line 523 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7985#-K0SRbqXVOpbPHMq3oKD)** ([raw file](https://github.com/servo/servo/blob/740ce3fe8653fdb572821fb0ff86aeb7b3fdb0a5/components/script/dom/document.rs#L523)):</sup>
This TODO comment should be updated.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7985)

**Comment by j3parker** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/document.rs, line 523 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7985#-K0SRbqXVOpbPHMq3oKD)** ([raw file](https://github.com/servo/servo/blob/740ce3fe8653fdb572821fb0ff86aeb7b3fdb0a5/components/script/dom/document.rs#L523)):</sup>
Got it - thanks!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7985)

**Comment by Manishearth** [comment]
Reviewed 4 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/document.rs, line 989 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7985#-K0Ta28ncQnMQtqPZOzk)** ([raw file](https://github.com/servo/servo/blob/4db5c188533faa9cae9fb4a5132671b505a6b16f/components/script/dom/document.rs#L989)):</sup>
We should leave comments here with a FIXME that this is incomplete (doesn't handle related targets)

ditto to where its called


---

<sup>**[components/script/dom/document.rs, line 999 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7985#-K0TWZvTKp2CbUg0qehV)** ([raw file](https://github.com/servo/servo/blob/4db5c188533faa9cae9fb4a5132671b505a6b16f/components/script/dom/document.rs#L999)):</sup>
spec says "to not bubble"

https://html.spec.whatwg.org/multipage/interaction.html#fire-a-focus-event


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7985)

**Comment by Manishearth** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7985)

**Comment by Manishearth** [comment]
Looks good so far.

I think web-platform-tests should already have tests for this, really. Try running `./mach test-wpt --log-raw tmp.log` (this takes a long time, adding `--processes 4` makes it faster), followed by `./mach update-wpt tmp.log` will update test expectations.

**Comment by j3parker** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/document.rs, line 989 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7985#-K0Ta28ncQnMQtqPZOzk)** ([raw file](https://github.com/servo/servo/blob/4db5c188533faa9cae9fb4a5132671b505a6b16f/components/script/dom/document.rs#L989)):</sup>
Done - I pre-emptively made it an argument on `fire_focus_event`.
It seems to me we'd have to be careful implementing this because of iframe security etc. (not wanting to pass a node from a different-origin iframe on a focus event up to the parent when focus leaves the iframe.) Does that sound right?


---

<sup>**[components/script/dom/document.rs, line 999 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7985#-K0TWZvTKp2CbUg0qehV)** ([raw file](https://github.com/servo/servo/blob/4db5c188533faa9cae9fb4a5132671b505a6b16f/components/script/dom/document.rs#L999)):</sup>
D'oh, thanks


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7985)

**Comment by Manishearth** [comment]
Still needs a lot of the other things from the issue being implemented. Though I am fine with landing this as-is so we can work on it incrementally. (@jdm ?)

Also needs test expectation updates to land.


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7985)

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/document.rs, line 989 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7985#-K0Ta28ncQnMQtqPZOzk)** ([raw file](https://github.com/servo/servo/blob/4db5c188533faa9cae9fb4a5132671b505a6b16f/components/script/dom/document.rs#L989)):</sup>
Yes, that does. The spec should have a provision for that, though.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7985)

**Comment by j3parker** [comment]
There were some more changes to WPT expectations that don't seem relevant that I split over here: https://github.com/j3parker/servo/commit/061c7991503c35a9051a7d906e271e5e54072c70

I haven't had time to triage them yet - hopefully tonight after work.

**Comment by Manishearth** [comment]
One of those failures is related, we should add `FocusEvent` to https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/interfaces.html#L72

**Comment by j3parker** [comment]
Thanks - I'll look through the rest tonight (EST)

**Comment by Manishearth** [comment]
Any updates?

**Comment by frewsxcv** [comment]
@j3parker have any ideas how close this is to completion? No problem if you're too busy, just let us know

**Comment by paulrouget** [comment]
@j3parker are you still working on this bug?

**Comment by jdm** [comment]
@paulrouget Seems safe to say no, given the multiple months with no reply after previous queries.

**Comment by frewsxcv** [comment]
@j3parker Thanks for the effort! Feel free to reopen if you want to want to work on it again and it's not already done!

**Comment by j3parker** [comment]
Oh wow I'm sorry!

I set up email filtering on Github (because we've been using it at my workplace more) and long story short these didn't get to my email and I forgot otherwise.

Happy to see it's been picked up though :) Cheers.

**Pull request closed without merging**
