### PR TITLE
 Cascade: skip duplicated properties before rather than after a virtual call

### PR DESCRIPTION
**Pull request by SimonSapin**
This is a subset of #15721. It fixes part of #15558, and refactors a couple things along the way.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15745)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo r=emilio

This is #15721, without the parts still being discussed.

**Comment by SimonSapin** [comment]
Found the bug. I moved code like `if seen.get${maybe_physical}_${property.ident}(${maybe_wm})` to a place that was not in a Mako loop for the `property` variable. The only reason this compiled is that Python’s variables are scoped to functions rather than blocks, so for-loop variables "leak" after the loop.

This means that the mapping from logical property ID to physical based on the writing mode now needs to be done at runtime. In retrospect this makes sense: we moved this code to before the virtual dispatch to property-specific functions.

This has some runtime cost (a `match` expression on the `LonghandId` C-like enum), but hopefully that is compensated by doing fewer virtual calls.

I also did a bunch of drive-by clean-up. (5 last commits)

r? @emilio or @Manishearth

**Comment by SimonSapin** [comment]
@bors-servo try

(tidy)

**Comment by emilio** [comment]
@bors-servo r+

Awesome :)

**Comment by SimonSapin** [comment]
My guess is that the merge commit for the last try run of this PR is still ahead of master, so homu thinks there is no need to make a new build. And since there is not successful non-try build, homu doesn’t merge either.

I’ll merge manually on the basis that the earlier try is still valid, since nothing has been merged to master since.

**Pull request merged**
