### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22641)

### CODE REVIEW

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1518045

**Review by mbrubeck — COMMENTED** [review]
83f0286cb75b08feaf116ac424e1db00db799f21 looks good to me.

**Comment by emilio** [comment]
I guess that meant to go to #22645 :)

**Comment by emilio** [comment]
(Also, thanks!)

**Pull request merged**
