### PR TITLE
clippy: Fix several warnings in components/devtools

### PR DESCRIPTION
**Pull request by eerii**
Fixes several clippy warnings in the `components/devtools` directory. It is part of #31500.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes are part of #31500.
- [x] These changes do not require tests because they do not modify functionality, they only fix lint errors.

### CODE REVIEW

**Comment by mrobinson** [comment]
@eerii Nice work. This change looks excellent. One thing you might need to do is to run `./mach fmt` before uploading it.

**Comment by eerii** [comment]
> @eerii Nice work. This change looks excellent. One thing you might need to do is to run `./mach fmt` before uploading it.

Thanks! I forgot about it last time.

- Now that there was a redundant match removed from `components/devtools/actors/emulation.rs`, `msg_type` is unused. Should I remove it and fix the function invocations or leave it and just mark it with an underscore?
- For clippy warnings about functions with too many arguments, should I add `#[allow(clippy::too_many_arguments)]` or leave the warning?

**Comment by mrobinson** [comment]
>     * Now that there was a redundant match removed from `components/devtools/actors/emulation.rs`, `msg_type` is unused. Should I remove it and fix the function invocations or leave it and just mark it with an underscore?

I think you should leave the argument as that function is implementing a trait. Simply prefix it with an underscore like the other unused arguments.

>     * For clippy warnings about functions with too many arguments, should I add `#[allow(clippy::too_many_arguments)]` or leave the warning?

Yes, I think that's a reasonable approach.

Thank you!

**Comment by eerii** [comment]
Thank you! I will do that and make sure everything works, and then I'll update the pr

**Review by mrobinson — APPROVED** [review]
Nice work!

**Pull request merged**
