### PR TITLE
Adding window.onstorage event handler

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
Not so sure about the corresponding code changes in the rust file. Mimicked the onunload for now!

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7999)

### CODE REVIEW

**Comment by jdm** [comment]
Did you compile these changes? I would expect a build error in htmlbodyelement.rs, which also implements WindowEventHandlers.

**Comment by martiansideofthemoon** [comment]
No, setup in progress. What sort of changes would I need in the Rust file?

**Comment by jdm** [comment]
I would expect changes that mirror the way Onunload is implemented in that file.

**Comment by martiansideofthemoon** [comment]
@jdm Well it failed the first check. Couldn't really figure out the reason as there wasn't any reference to .rs files. Where am I going wrong?

**Comment by jdm** [comment]
```
./components/script/dom/htmlbodyelement.rs:99: method declared in webidl is missing a comment with a specification link

./components/script/dom/htmlbodyelement.rs:104: method declared in webidl is missing a comment with a specification link
```

**Comment by jdm** [comment]
You can also see those locally by running `./mach test-tidy`.

**Comment by jdm** [comment]
Please also include the changes that result from these commands:
```
./mach test-wpt tests/web-platform-tests/tests/webstorage --log-raw >/tmp/wpt.log
./mach update-wpt /tmp/wpt.log
```
This will update the expected output of the tests related to the changes we're making, as described in [the readme](http://mxr.mozilla.org/servo/source/tests/wpt/README.md#71).

**Comment by martiansideofthemoon** [comment]
@jdm Getting these errors while building servo (./mach build --dev) [THIS] (https://gist.github.com/martiansideofthemoon/04ba38f7617e03e5119a)

**Comment by jdm** [comment]
That's... odd. I don't see anything in the changes in this PR that should cause that error.

**Comment by jdm** [comment]
FWIW I made the same changes locally and don't see any errors. Maybe look if there are any changes in your working directory that are not pushed?

**Comment by martiansideofthemoon** [comment]
@jdm I did a `git diff my-code-fix..master` and got the same changes as in the PR

**Comment by jdm** [comment]
I have not seen local builds that fail while the remote build succeeds before :/ Travis agrees with me that the changes build successfully. I would try `git reset --hard 715d285c9cebb0f0de88bb1aa0569c015042c9e5; ./mach build --dev` and see if anything changes.

**Comment by martiansideofthemoon** [comment]
@jdm :- Doesn't help :/ Could making a different branch affect it in any way?

**Comment by jdm** [comment]
Not that I can see, no.

**Comment by martiansideofthemoon** [comment]
@jdm Should I file an issue?

**Comment by jdm** [comment]
I'd rather ensure that you're able to compile and test the changes you've made here :) Could you try starting from the master branch and ensuring that it compiles correctly?

**Comment by martiansideofthemoon** [comment]
@jdm :- The build completed successfully on my master branch :smile: Could it be because I carried out changes without building it first?

**Comment by jdm** [comment]
I'll try pulling your branch and seeing if the error reproduces.

**Comment by martiansideofthemoon** [comment]
Okay thanks, and what of the log file ^^ ?

**Comment by jdm** [comment]
I'm pretty sure the test expectation changes get committed automatically, so they wouldn't be in 'git diff'.

**Comment by martiansideofthemoon** [comment]
Yeah you are right I am not able to commit / push. 

Do let me know if I need to do any further work on this PR / Issue, and the results you obtain on pulling my branch :D

**Comment by jdm** [comment]
I admit, I am extremely confused. This branch builds fine for me :/

**Comment by jdm** [comment]
Do you want to try recreating your changes based on master again and see if the situation improves?

**Comment by martiansideofthemoon** [comment]
@jdm Yeah I guess I will do that. Should I keep this PR, or start afresh on a new branch and a new PR?

**Comment by jdm** [comment]
A new one might make sense.

**Pull request closed without merging**
