### PR TITLE
Support variadic interface arguments (fixes #8159)

### LINKED ISSUE #8159: Error in generated binding for variadic argument of type that needs rooting
The following WebIDL (where `Touch` is as defined in #7204):

```webidl
partial interface Document {
      TouchList createTouchList(Touch... touches);
};
```
causes this compile error:
```
DocumentBinding.rs:2184:61: 2184:64 error: no method named `r` found for type `collections::vec::Vec<dom::bindings::js::Root<dom::touch::Touch>>` in the current scope
DocumentBinding.rs:2184     let result: Root<TouchList> = this.CreateTouchList(arg0.r());
                                                                                    ^~~
```

The generated trait method signature is:
```rust
    fn CreateTouchList(&self, touches: Vec<&Touch>) -> Root<TouchList>;
```

and the generated binding is:

```rust
unsafe extern fn createTouchList(cx: *mut JSContext, _obj: HandleObject, this: *const Document, args: *const JSJitMethodCallArgs) -> bool {
    let this = &*this;
    let args = &*args;
    let argc = args._base.argc_;
    let arg0: Vec<Root<Touch>> = if 0 < argc {
        let mut vector: Vec<Root<Touch>> = Vec::with_capacity((argc - 0) as usize);
        for variadicArg in 0..argc {
            let slot: Root<Touch> = if args.get(variadicArg).get().is_object() {
                match native_from_handlevalue(args.get(variadicArg)) {
                    Ok(val) => val,
                    Err(()) => {
                        throw_type_error(cx, "value does not implement interface Touch.");
                        return false;
                    }
                }
            } else {
                throw_type_error(cx, "Value is not an object.");
                return false;
            };
            vector.push(slot);
        }
        vector
    } else {
        Vec::new()
    };
    let result: Root<TouchList> = this.CreateTouchList(arg0.r());

    (result).to_jsval(cx, args.rval());
    return true;
}
```

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8197)

### CODE REVIEW

**Comment by nox** [comment]
```rust

unsafe extern fn passVariadicInterface(cx: *mut JSContext, _obj: HandleObject, this: *const TestBinding, args: *const JSJitMethodCallArgs) -> bool {
    let this = &*this;
    let args = &*args;
    let argc = args._base.argc_;
    let mut arg0 = RootedVec::new();
    *arg0 = Vec::with_capacity((argc - 0) as usize);
    for variadicArg in 0..argc {
        let slot: *const Blob = if args.get(variadicArg).get().is_object() {
            match native_from_handlevalue(args.get(variadicArg)) {
                Ok(val) => val,
                Err(()) => {
                    throw_type_error(cx, "value does not implement interface Blob.");
                    return false;
                }
            }
        } else {
            throw_type_error(cx, "Value is not an object.");
            return false;
        };
        arg0.push(JS::from_ref(&*slot));
    }
    let result: () = this.PassVariadicInterface(arg0.r());

    (result).to_jsval(cx, args.rval());
    return true;
}
```

**Comment by nox** [comment]
#8159

**Comment by Ms2ger** [comment]
Not sure I'm a big fan of the branching

**Comment by nox** [comment]
I have no idea what your remark is about, @Ms2ger.

**Comment by jdm** [comment]
@bors-servo: r+
This looks ok to me and is necessary for #8225. I'll double back and do a thorough post-merge review.

**Comment by jdm** [comment]
@bors-servo: r-
The pressure's off. I'll review this properly.

**Comment by jdm** [comment]
Generally looks good! I'd just like to make sure that we're thinking through the changes to the types carefully.
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 10 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 761 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oMRlgsqdZXe8Ur1_Q)** ([raw file](https://github.com/servo/servo/blob/859a41ef6ae8aa6b16fdbdb4471ebb5b770d4635/components/script/dom/bindings/codegen/CodegenRust.py#L761)):</sup>
memberType appears to be unused now. We should remove it if that's the case.


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 1209 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oLN33xlIwo9EZ2r2s)** ([raw file](https://github.com/servo/servo/blob/859a41ef6ae8aa6b16fdbdb4471ebb5b770d4635/components/script/dom/bindings/codegen/CodegenRust.py#L1209)):</sup>
We lost this check; is that a problem? For example, could that end up causing underflow in the earlier subtraction?


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 108 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oIP9-my1AnEoZyZE0)** ([raw file](https://github.com/servo/servo/blob/88bf688d711f51857fbbe16c1878d174780f44f1/components/script/dom/bindings/codegen/CodegenRust.py#L108)):</sup>
"Returns a string of the Rust expression..."


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 764 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oMmUiIQh5jdp_hOz4)** ([raw file](https://github.com/servo/servo/blob/88bf688d711f51857fbbe16c1878d174780f44f1/components/script/dom/bindings/codegen/CodegenRust.py#L764)):</sup>
I guess this else block is why we continue rooting members of dictionaries after this change. I'm concerned that this is both non-obvious and confusing.


---

<sup>**[components/script/dom/bindings/codegen/Configuration.py, line 166 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oLnevUvwwbWMKmmYb)** ([raw file](https://github.com/servo/servo/blob/88bf688d711f51857fbbe16c1878d174780f44f1/components/script/dom/bindings/codegen/Configuration.py#L166)):</sup>
I'm slightly concerned that this could make us no longer root dictionary members or something? What's the effect of modifying this and the next line?


---

<sup>**[components/script/dom/bindings/conversions.rs, line 756 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oN3NokkSLFVGvRYN6)** ([raw file](https://github.com/servo/servo/blob/88bf688d711f51857fbbe16c1878d174780f44f1/components/script/dom/bindings/conversions.rs#L756)):</sup>
Let's not make this public if it doesn't need to be. The fewer things expose unsafe pointers the better.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8197)

**Comment by nox** [comment]
-S-needs-rebase +S-awaiting-answer 


---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 761 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oMRlgsqdZXe8Ur1_Q)** ([raw file](https://github.com/servo/servo/blob/859a41ef6ae8aa6b16fdbdb4471ebb5b770d4635/components/script/dom/bindings/codegen/CodegenRust.py#L761)):</sup>
Done.


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 1209 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oLN33xlIwo9EZ2r2s)** ([raw file](https://github.com/servo/servo/blob/859a41ef6ae8aa6b16fdbdb4471ebb5b770d4635/components/script/dom/bindings/codegen/CodegenRust.py#L1209)):</sup>
The number of arguments can never be less than the offset where variadic arguments start, when that code is executed. No underflow can thus happen.


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 108 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oIP9-my1AnEoZyZE0)** ([raw file](https://github.com/servo/servo/blob/88bf688d711f51857fbbe16c1878d174780f44f1/components/script/dom/bindings/codegen/CodegenRust.py#L108)):</sup>
Done.


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 764 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oMmUiIQh5jdp_hOz4)** ([raw file](https://github.com/servo/servo/blob/88bf688d711f51857fbbe16c1878d174780f44f1/components/script/dom/bindings/codegen/CodegenRust.py#L764)):</sup>
So what do you want me to do?


---

<sup>**[components/script/dom/bindings/codegen/Configuration.py, line 166 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oLnevUvwwbWMKmmYb)** ([raw file](https://github.com/servo/servo/blob/88bf688d711f51857fbbe16c1878d174780f44f1/components/script/dom/bindings/codegen/Configuration.py#L166)):</sup>
None apart from letting me distinguish variadic interface arguments from variadic union arguments, etc. Dictionary members stay rooted AFAIK. What codegen result do you want me to paste to convince you?


---

<sup>**[components/script/dom/bindings/conversions.rs, line 756 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oN3NokkSLFVGvRYN6)** ([raw file](https://github.com/servo/servo/blob/88bf688d711f51857fbbe16c1878d174780f44f1/components/script/dom/bindings/conversions.rs#L756)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8197)

**Comment by jdm** [comment]
-S-awaiting-review -S-awaiting-answer +S-needs-code-changes 


---

Reviewed 14 of 14 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 764 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8197#-K2oMmUiIQh5jdp_hOz4)** ([raw file](https://github.com/servo/servo/blob/88bf688d711f51857fbbe16c1878d174780f44f1/components/script/dom/bindings/codegen/CodegenRust.py#L764)):</sup>
I think my confusion stems from two parts:
* there's no block that explicitly deals with `isMember != "Variadic"`
* we rely on returnType being `Root` for things that are not conceptually return types
I would be happy with an elif for the first  point that uses returnType but has a comment explaining our reasoning.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8197)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8197)

**Pull request merged**
