### PR TITLE
Use TimerHandler IDL union type

### LINKED ISSUE #20700: Support functions in `timerhandler` WebIDL unions
https://html.spec.whatwg.org/multipage/#timerhandler

### PR DESCRIPTION
**Pull request by saschanaz**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #20700

- [x] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
Review ping @nox.

**Comment by nox** [comment]
Nice.

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #24762

**Pull request merged**
