### PR TITLE
Avoid some rooting in parsing.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8935)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/parse/html.rs, line 43 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8935#-K5GVNDn65ueqdbTdYwI:-K5GVNDn65ueqdbTdYwJ:1795268377) ([raw file](https://github.com/servo/servo/blob/14acf1616e46a7e312d6398f3c7e1c3e83ad1f31/components/script/parse/html.rs#L43)):*
How come this doesn't need `#[allow(unrooted_must_root)]`? There is a `JS<Node>` passed by value in there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8935#-:-K5GVUaC6AAvwl_4zH_b:453359453)*

**Comment by Ms2ger** [comment]
@Manishearth ?

**Comment by Manishearth** [comment]
@bors-servo r+

cc @asajeffrey

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/parse/html.rs, line 43 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8935#-K5GVNDn65ueqdbTdYwI:-K5HLzu0HLgFpW0Xtb1O:-1751489719) ([raw file](https://github.com/servo/servo/blob/14acf1616e46a7e312d6398f3c7e1c3e83ad1f31/components/script/parse/html.rs#L43)):*
The lint is turned off in this file because we do far worse.

But. I wonder if we can pass in an &JS<Node>. It's safe at the moment though, so r=me if we don't want to.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8935)*

**Comment by Ms2ger** [comment]
I don't think we can.

**Comment by Manishearth** [comment]
'kay

@bors-servo r+

**Pull request merged**
