### PR TITLE
Fix unused crate warning in script_tests

### PR DESCRIPTION
**Pull request by mbrubeck**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11382)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Pushed another commit with more warning fixes. r? @nox

**Comment by ConnorGBrewster** [comment]
This fails tidy

**Comment by KiChjang** [comment]
@bors-servo r-

Let's fix that tidy issue first.

**Comment by mbrubeck** [comment]
@bors-servo r=nox

* Fixed whitespace issue found by tidy.

**Comment by mbrubeck** [comment]
@bors-servo retry

mac1

**Pull request merged**
