### PR TITLE
Decode UTF-8 code points across network packets

### PR DESCRIPTION
**Pull request by SimonSapin**
<s>Depends on https://github.com/servo/html5ever/pull/272</s>

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16989)

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /html/browsers/history/the-location-interface/location-protocol-setter.html:
  │ FAIL [expected PASS] %E2%80%A0x (percent-encoded) is not a scheme
  │   → assert_throws: function "() => { location.protocol = val }" did not throw
  │ 
  │ @http://web-platform.test:8000/html/browsers/history/the-location-interface/location-protocol-setter.html:89:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:497:9
  │ @http://web-platform.test:8000/html/browsers/history/the-location-interface/location-protocol-setter.html:88:5
  └ @http://web-platform.test:8000/html/browsers/history/the-location-interface/location-protocol-setter.html:87:4
```
I think this ends up matching the rest of the failing tests in that file now?

**Comment by SimonSapin** [comment]
Forgot the EOF case.

@bors-servo try

**Comment by SimonSapin** [comment]
Removed `[replace]`, this is ready to land.

**Comment by Manishearth** [comment]
buildbot reached an invalid state

**Comment by SimonSapin** [comment]
Rebased.

@bors-servo r=nox

**Pull request merged**
