### PR TITLE
Remove unnecessary lifetimes from layout/parallel.rs

### PR DESCRIPTION
**Pull request by Manishearth**
cc @bholley

(Each commit individually compiles, I split them up for you to get a better idea of how the lifetimes work here)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9085)

### CODE REVIEW

**Comment by Ms2ger** [comment]
You commit messages suck :)

**Comment by bholley** [comment]
@bors-servo r-

I removed this in #9103, so this patch will just bitrot that. I would rebase over it but homu seems stalled. :\

**Comment by bholley** [comment]
This is subsumed by #9103. Thanks for the the tip though @Manishearth!

**Pull request closed without merging**
