### PR TITLE
Improve layer tree debugging output

### PR DESCRIPTION
**Pull request by mrobinson**
Add an option to dump the layer tree, which activates the previously
unused layer tree debugging code. Also improve the output using the
PrintTree struct.

Previous output:

```
Layer tree:
Layer 7f63b45b2010: RefCell { value: CompositorData { pipeline_id: PipelineId(0), id: 0-FragmentBody, wants_scroll_events: WantsScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(4), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: None } } @ Rect(Length(800, PhantomData)×Length(600, PhantomData) at (Length(0, PhantomData),Length(0, PhantomData))) masks to bounds: true establishes 3D context: true
  Layer 7f63b45b2290: RefCell { value: CompositorData { pipeline_id: PipelineId(0), id: 140065919922672-FragmentBody, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(5), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: None } } @ Rect(Length(800, PhantomData)×Length(650, PhantomData) at (Length(0, PhantomData),Length(0, PhantomData))) masks to bounds: false establishes 3D context: true
    Layer 7f63b45b3410: RefCell { value: CompositorData { pipeline_id: PipelineId(0), id: 140065919923248-FragmentBody, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: FixedPosition, requested_epoch: Epoch(5), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: None } } @ Rect(Length(50, PhantomData)×Length(50, PhantomData) at (Length(18, PhantomData),Length(10, PhantomData))) masks to bounds: false establishes 3D context: false
    Layer 7f63b45b3190: RefCell { value: CompositorData { pipeline_id: PipelineId(0), id: 140065919923872-FragmentBody, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: FixedPosition, requested_epoch: Epoch(5), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: None } } @ Rect(Length(50, PhantomData)×Length(50, PhantomData) at (Length(93, PhantomData),Length(10, PhantomData))) masks to bounds: false establishes 3D context: false
    Layer 7f63b45b2f10: RefCell { value: CompositorData { pipeline_id: PipelineId(0), id: 140065919924496-FragmentBody, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(5), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: Some((PipelineId(0), SubpageId(0))) } } @ Rect(Length(50, PhantomData)×Length(50, PhantomData) at (Length(168, PhantomData),Length(10, PhantomData))) masks to bounds: false establishes 3D context: false
      Layer 7f63b45b3b90: RefCell { value: CompositorData { pipeline_id: PipelineId(1), id: 0-FragmentBody, wants_scroll_events: WantsScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(3), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: Some((PipelineId(0), SubpageId(0))) } } @ Rect(Length(50, PhantomData)×Length(50, PhantomData) at (Length(0, PhantomData),Length(0, PhantomData))) masks to bounds: true establishes 3D context: true
        Layer 7f63b45b3e10: RefCell { value: CompositorData { pipeline_id: PipelineId(1), id: 140065901048256-FragmentBody, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(4), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: None } } @ Rect(Length(50, PhantomData)×Length(58, PhantomData) at (Length(0, PhantomData),Length(0, PhantomData))) masks to bounds: false establishes 3D context: true
    Layer 7f63b45b2c90: RefCell { value: CompositorData { pipeline_id: PipelineId(0), id: 140065919925168-FragmentBody, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(5), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: Some((PipelineId(0), SubpageId(1))) } } @ Rect(Length(50, PhantomData)×Length(50, PhantomData) at (Length(243, PhantomData),Length(10, PhantomData))) masks to bounds: false establishes 3D context: false
      Layer 7f63b45b2790: RefCell { value: CompositorData { pipeline_id: PipelineId(2), id: 0-FragmentBody, wants_scroll_events: WantsScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(3), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: Some((PipelineId(0), SubpageId(1))) } } @ Rect(Length(50, PhantomData)×Length(50, PhantomData) at (Length(0, PhantomData),Length(0, PhantomData))) masks to bounds: true establishes 3D context: true
        Layer 7f63b45b2510: RefCell { value: CompositorData { pipeline_id: PipelineId(2), id: 140065880076736-FragmentBody, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(5), painted_epoch: Epoch(4), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: None } } @ Rect(Length(50, PhantomData)×Length(58, PhantomData) at (Length(0, PhantomData),Length(0, PhantomData))) masks to bounds: false establishes 3D context: true
    Layer 7f63b45b3910: RefCell { value: CompositorData { pipeline_id: PipelineId(0), id: 140065919925168-FragmentBody-companion, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(5), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: None } } @ Rect(Length(800, PhantomData)×Length(650, PhantomData) at (Length(0, PhantomData),Length(0, PhantomData))) masks to bounds: false establishes 3D context: false
    Layer 7f63b45b2a10: RefCell { value: CompositorData { pipeline_id: PipelineId(0), id: 140065919924064-FragmentBody, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(5), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: None } } @ Rect(Length(50, PhantomData)×Length(50, PhantomData) at (Length(103, PhantomData),Length(30, PhantomData))) masks to bounds: false establishes 3D context: false
    Layer 7f63b45b3690: RefCell { value: CompositorData { pipeline_id: PipelineId(0), id: 140065919924064-FragmentBody-companion, wants_scroll_events: DoesntWantScrollEvents, scroll_policy: Scrollable, requested_epoch: Epoch(5), painted_epoch: Epoch(0), scroll_offset: (Length(0, PhantomData),Length(0, PhantomData)), subpage_info: None } } @ Rect(Length(800, PhantomData)×Length(650, PhantomData) at (Length(0, PhantomData),Length(0, PhantomData))) masks to bounds: false establishes 3D context: false
```

New output:

```
┌ Layer tree
│  ├─ Root Layer (pipeline=0) (0-FragmentBody) (800,600 at 0,0) (masks children) (3D context)
│  │  ├─ Layer (140279059771888-FragmentBody) (800,650 at 0,0) (3D context)
│  │  │  ├─ Layer (140279059772464-FragmentBody) (50,50 at 18,10) (fixed)
│  │  │  ├─ Layer (140279059773088-FragmentBody) (50,50 at 93,10) (fixed)
│  │  │  ├─ Layer (140279059773712-FragmentBody) (50,50 at 168,10)
│  │  │  │  ├─ Root Layer (pipeline=1) (0-FragmentBody) (50,50 at 0,0) (masks children) (3D context)
│  │  │  │  │  └─ Layer (140278833279472-FragmentBody) (50,58 at 0,0) (3D context)
│  │  │  ├─ Layer (140279059774384-FragmentBody) (50,50 at 243,10)
│  │  │  │  ├─ Root Layer (pipeline=2) (0-FragmentBody) (50,50 at 0,0) (masks children) (3D context)
│  │  │  │  │  └─ Layer (140279013634496-FragmentBody) (50,58 at 0,0) (3D context)
│  │  │  ├─ Layer (140279059774384-FragmentBody-companion) (800,650 at 0,0)
│  │  │  ├─ Layer (140279059773280-FragmentBody) (50,50 at 103,30)
│  │  │  └─ Layer (140279059773280-FragmentBody-companion) (800,650 at 0,0)
```

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7879)

### CODE REVIEW

**Comment by mrobinson** [comment]
cc @glennw

**Comment by jdm** [comment]
```
/home/servo/buildbot/slave/linux-dev/build/components/compositing/compositor.rs:1772:49: 1772:67 error: attempted tuple index `0` on type `msg::constellation_msg::PipelineId`, but the type was not a tuple or tuple struct
/home/servo/buildbot/slave/linux-dev/build/components/compositing/compositor.rs:1772             format!("Root Layer (pipeline={})", data.pipeline_id.0)
                                                                                                                                     ^~~~~~~~~~~~~~~~~~
<std macros>:2:26: 2:57 note: in this expansion of format_args!
/home/servo/buildbot/slave/linux-dev/build/components/compositing/compositor.rs:1772:13: 1772:68 note: in this expansion of format! (defined in <std macros>)
error: aborting due to previous error

```

**Comment by mrobinson** [comment]
Oddly enough I cannot reproduce this build failure locally, but I can try to work around it nonetheless.

**Comment by glennw** [comment]
@mrobinson I suspect if you rebase your PR against master you'll see the build failure locally - there were some changes to PipelineId I made that merged late yesterday.

**Comment by mrobinson** [comment]
@glennw Thanks for the tip! I've rebased the patch and switched to using a normal format argument for the PipelineId, now that it has the capability. Does it look okay to you?

**Comment by mrobinson** [comment]
@bors-servo retry

This failure seems to be: #7730.

**Pull request merged**
