### PR TITLE
Add WebGL conformance 2.0.0 tests

### PR DESCRIPTION
**Pull request by MortimerGoro**
This PR includes WebGL conformance 2.0.0 tests. For now I have disabled three folders in the new suite:
- `Conformance`: Tests WebGL 1.0 API like the current 1.0.3 suite we are using, but it includes a lot more tests and many expectations have to be updated. This is better to do in a separate PR because it will require to update github intermittent paths again and maybe detect new intermittents.
- `Conformance2\textures`: It causes a lot of timeouts because of using videos, svgs, and other complicated formats.
- `deqp`: It's a extra GPU testing suite included in the Khronos 2.0.0 suite. Disabled for now because it causes some timeouts.

So in a nutshell, it uses part of the 2.0.0 suite to test webgl 2.0 and keeps using 1.0.3 in order to test WebGL 1.0. It's good enough to enable TDD for the new WebGL 2.0 features

We can create follow-up issues for the next steps:
* deprecate 1.0.3 and use the new 'conformance' folder in 2.0.0 in order to test WebGL 1.0
* Enable `conformance2/textures` and  'deqp' tests once WebGL 2.0 implementation is more advanced or the timeouts are monitored in more detail.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19091)

### CODE REVIEW

**Comment by jdm** [comment]
There are some stray `.orig` files that go added to the manifest, unfortunately. You'll need to remove them and update the manifest again.

**Comment by jdm** [comment]
There are a lot of crashes like this one, too:
```
▶ CRASH [expected ERROR] /_mozilla/webgl/conformance-2.0.0/conformance2/renderbuffers/framebuffer-test.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ ERROR:script::dom::bindings::error: Error at http://web-platform.test:8000/_mozilla/webgl/conformance-2.0.0/conformance2/renderbuffers/framebuffer-test.html:52:3 gl.getFramebufferAttachmentParameter is not a function
  │ DESCRIPTION: This tests framebuffer/renderbuffer-related functions
  │ PASS gl = wtu.create3DContext(canvas, undefined, 2) is non-null.
  │ 
  │ Checking framebuffer/renderbuffer stuff.
  │ FAIL successfullyParsed should be true (of type boolean). Was undefined (of type undefined).
  │ TEST COMPLETE
  │ assertion failed: thread_state::get().is_script() (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }, at /home/servo/buildbot/slave/linux-rel-wpt/build/components/script/dom/bindings/root.rs:351)
  │ stack backtrace:
  │    0:     0x7f66a79a992c - backtrace::backtrace::trace::h3049d3b23f5565ad
  │    1:     0x7f66a79a9962 - backtrace::capture::Backtrace::new::h48230b597774155d
  │    2:     0x7f66a7717415 - servo::main::{{closure}}::hef0a65f3722a6416
  │    3:     0x7f66a9ac88c6 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7f66a7f8afba - std::panicking::begin_panic::h42c8e2074ac9d6ce
  │    5:     0x7f66a85bc52f - <script::dom::bindings::root::LayoutDom<script::dom::htmlcanvaselement::HTMLCanvasElement> as script::dom::htmlcanvaselement::LayoutHTMLCanvasElementHelpers>::data::he27c277139cb84b7
  │    6:     0x7f66a864942a - <script::dom::bindings::root::LayoutDom<script::dom::node::Node> as script::dom::node::LayoutNodeHelpers>::canvas_data::h836ec9a95f386abe
  │    7:     0x7f66a7ebff44 - <layout::construct::FlowConstructor<'a, ConcreteThreadSafeLayoutNode>>::build_fragment_for_block::hde9c964b1e683c83
  │    8:     0x7f66a7e3811e - <layout::construct::FlowConstructor<'a, ConcreteThreadSafeLayoutNode> as layout::traversal::PostorderNodeMutTraversal<ConcreteThreadSafeLayoutNode>>::process::h6439282ce11ddaa0
  │    9:     0x7f66a7e970a1 - style::traversal::DomTraversal::handle_postorder_traversal::h20595771a4f893e6
  │   10:     0x7f66a7efd585 - layout_thread::LayoutThread::handle_reflow::h1ca06ddd6bcb1fda
  │   11:     0x7f66a7eed520 - layout_thread::LayoutThread::handle_request_helper::hdddf3a781309b021
  │   12:     0x7f66a7ee8e40 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::h08c7d62806bbbb70
  │   13:     0x7f66a7e4b565 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9ff407256452b79e
  │   14:     0x7f66a7e4dc95 - std::panicking::try::do_call::h614ee1b62dc1e685
  │   15:     0x7f66a9acfa0c - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:99
  │   16:     0x7f66a7e83222 - <F as alloc::boxed::FnBox<A>>::call_box::h3c9387aa64dab84a
  │   17:     0x7f66a9ac75db - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /checkout/src/liballoc/boxed.rs:772
  │                          - std::sys_common::thread::start_thread
  │                         at /checkout/src/libstd/sys_common/thread.rs:24
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   18:     0x7f66a5618183 - start_thread
  │   19:     0x7f66a4f26ffc - clone
  │   20:                0x0 - <unknown>
  │ ERROR:servo: assertion failed: thread_state::get().is_script()
  │ Pipeline failed in hard-fail mode.  Crashing!
  └ thread panicked while processing panic. aborting.
```
http://build.servo.org/builders/linux-rel-wpt/builds/6751

**Comment by MortimerGoro** [comment]
`There are some stray .orig files that go added to the manifest, unfortunately. You'll need to remove them and update the manifest again.`

Fixed!

`There are a lot of crashes like this one, too:`

Ok, I'll check that crash path

**Comment by MortimerGoro** [comment]
@jdm Fixed the crashed tests:

- The expectations are now generated with debug assertions enabled
- Fixed that debug assertion crash. It was caused by a missing to_layout() call in layout related code.

**Pull request merged**
