### PR TITLE
Update taskcluster for new Servo mpk name

### LINKED ISSUE #23991: Magicleap Nightly upload is failing
https://tools.taskcluster.net/groups/S88iUG-fSCSfQNavuWdQyA/tasks/c1KKBRXoT1q3rVL341-dPw/runs/0/logs/public%2Flogs%2Flive.log

> `[taskcluster:error] Uploading error artifact public/Servo2D.mpk from file repo/target/magicleap/aarch64-linux-android/release/Servo2D.mpk with message "Could not read file '/Users/worker/tasks/task_1566036862/repo/target/magicleap/aarch64-linux-android/release/Servo2D.mpk'", reason "file-missing-on-worker" and expiry 2019-08-24T10:13:54.179Z`

CC @asajeffrey

### PR DESCRIPTION
**Pull request by asajeffrey**
Updates taskcluster with the new Servo magicleap mpk filename.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23991
- [x] These changes do not require tests because it's fixing the build

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23992)

### CODE REVIEW

**Comment by asajeffrey** [comment]
```
  ▶ CRASH [expected OK] /html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_access_details.sub.html
  │ 
  │ 
  │ 
  │ 
  │ 
  │ (servo:83251): GStreamer-WARNING **: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
  │ 0:00:00.023116296 83251 0x5633a7248730 WARN      GST_PLUGIN_LOADING gstplugin.c:793:_priv_gst_plugin_load_file_for_registry: module_open failed: libmms.so.0: cannot open shared object file: No such file or directory
  │ 
  │ (servo:83251): GStreamer-WARNING **: Failed to load plugin '/home/servo/gst/lib/gstreamer-1.0/libgstmms.so': libmms.so.0: cannot open shared object file: No such file or directory
  │ 0:00:00.023368607 83251 0x5633a7248730 WARN      GST_PLUGIN_LOADING gstplugin.c:793:_priv_gst_plugin_load_file_for_registry: module_open failed: libfaad.so.2: cannot open shared object file: No such file or directory
  │ 
  │ (servo:83251): GStreamer-WARNING **: Failed to load plugin '/home/servo/gst/lib/gstreamer-1.0/libgstfaad.so': libfaad.so.2: cannot open shared object file: No such file or directory
  │ Failed to receive a response from live font cache (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/gfx/font_cache_thread.rs:543)
  │ stack backtrace:
  │    0: servo::main::{{closure}}::h57fd09ddb4c56540 (0x5633a0b0681f)
  │    1: std::panicking::rust_panic_with_hook::hec63884fa234b28d (0x5633a3f1e705)
  │              at src/libstd/panicking.rs:481
  │    2: std::panicking::begin_panic::h3d102371269c33bd (0x5633a2dcebd4)
  │    3: <gfx::font_cache_thread::FontCacheThread as gfx::font_context::FontSource>::font_template::h56c3b985dfbd705d (0x5633a2dc1f5f)
  │    4: gfx::font_context::FontContext<S>::font::h9c172a8914ae3f73 (0x5633a2969505)
  │    5: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}::hb97e2f76844bb1cb (0x5633a290550c)
  │    6: gfx::font::FontGroup::first::h654c5ae5d29db378 (0x5633a2906f8f)
  │    7: layout::text::font_metrics_for_style::h9defa9cd642bd67a (0x5633a28e21e4)
  │    8: layout::inline::InlineFlow::minimum_line_metrics_for_fragments::h33bd715e5554524a (0x5633a28d944e)
  │    9: std::thread::local::LocalKey<T>::with::h17b850ecac3fb57a (0x5633a0f63d11)
  │   10: layout::construct::FlowConstructor<ConcreteThreadSafeLayoutNode>::build_flow_for_block_starting_with_fragments::h4a633d9c91be86cb (0x5633a0f77171)
  │   11: layout::construct::FlowConstructor<ConcreteThreadSafeLayoutNode>::build_flow_for_block_like::h5fb7f366d0558f95 (0x5633a0f73c64)
  │   12: layout::construct::FlowConstructor<ConcreteThreadSafeLayoutNode>::build_flow_for_block::h139e9cefd5cf6fed (0x5633a0f732d7)
  │   13: <layout::construct::FlowConstructor<ConcreteThreadSafeLayoutNode> as layout::traversal::PostorderNodeMutTraversal<ConcreteThreadSafeLayoutNode>>::process::h1446cd6b6dc05ecd (0x5633a0f5a35f)
  │   14: style::traversal::DomTraversal::handle_postorder_traversal::h5e911e1ddc32348a (0x5633a0f2a7ef)
  │   15: style::driver::traverse_dom::hf5191e6329176661 (0x5633a0f71701)
  │   16: profile_traits::time::profile::ha568695a60371d61 (0x5633a1072add)
  │   17: layout_thread::LayoutThread::handle_reflow::hcfd875c3336aa353 (0x5633a0f4d7ae)
  │   18: profile_traits::time::profile::hc310d21117030265 (0x5633a1072c70)
  │   19: layout_thread::LayoutThread::handle_request_helper::h86ee791b2558dd49 (0x5633a0f46109)
  │   20: layout_thread::LayoutThread::start::h60c6f72ec36cd231 (0x5633a0f44b11)
  │   21: profile_traits::mem::ProfilerChan::run_with_memory_reporting::hd1952fb09db228f9 (0x5633a0fa7023)
  │   22: std::sys_common::backtrace::__rust_begin_short_backtrace::h1c31d28ecf3edadd (0x5633a10100f7)
  │   23: _ZN3std9panicking3try7do_call17h852b732890116b1bE.llvm.11713165585705072715 (0x5633a0fcb725)
  │   24: __rust_maybe_catch_panic (0x5633a3f283a9)
  │              at src/libpanic_unwind/lib.rs:80
  │   25: core::ops::function::FnOnce::call_once{{vtable.shim}}::ha46ace096b381f88 (0x5633a10111d5)
  │   26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h82a57145aa4239a7 (0x5633a3f0cdee)
  │              at /rustc/dddb7fca09dc817ba275602b950bb81a9032fb6d/src/liballoc/boxed.rs:770
  │   27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h167c1ef971e93086 (0x5633a3f276cf)
  │              at /rustc/dddb7fca09dc817ba275602b950bb81a9032fb6d/src/liballoc/boxed.rs:770
  │       std::sys_common::thread::start_thread::h739b9b99c7f25b24
  │              at src/libstd/sys_common/thread.rs:13
  │       std::sys::unix::thread::Thread::new::thread_start::h79a2f27ba62f96ae
  │              at src/libstd/sys/unix/thread.rs:79
  │   28: start_thread (0x7f0a8a62c6b9)
  │   29: clone (0x7f0a88ec741c)
  │   30: <unknown> (0x0)
  │ [2019-08-18T01:24:59Z ERROR servo] Failed to receive a response from live font cache
  │ Pipeline failed in hard-fail mode.  Crashing!
  └ thread panicked while processing panic. aborting.
```
@bors-servo retry #21067

**Comment by asajeffrey** [comment]
```
  ▶ FAIL [expected PASS] /css/css-flexbox/flexbox_flex-N-N-N.html
  └   → /css/css-flexbox/flexbox_flex-N-N-N.html a19a3136898180e0d49e954a63a28fe179d5e0be
/css/css-flexbox/flexbox_flex-N-N-N-ref.html 3fa48df5414931a4b646b3e6f5383eebf0333718
```
Hmm, that looks like it might be #21932? @bors-servo retry

**Comment by jdm** [comment]
More likely to be #23290 on Mac. The vast majority of intermittent reftest failures on Mac are caused by that one.

**Comment by asajeffrey** [comment]
TIL

**Pull request merged**
