### PR TITLE
Make the fetch target non-optional.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14465)

### CODE REVIEW

**Comment by Ms2ger** [comment]
r?

**Comment by KiChjang** [comment]
```
Ran 7917 tests finished in 883.0 seconds.
  • 7915 ran as expected. 1890 tests skipped.
  • 1 tests failed unexpectedly
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/mozilla/simple_scroll_to_fragment.html
  └   → /_mozilla/mozilla/simple_scroll_to_fragment.html 1a9f5b056d9d5c7e985e172701179543d007e367
/_mozilla/mozilla/simple_scroll_to_fragment_ref.html 111b0141f71ae09366d1ce49dcece7c79df65484
Testing 1a9f5b056d9d5c7e985e172701179543d007e367 == 111b0141f71ae09366d1ce49dcece7c79df65484

  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-iframe-element/iframe-allowfullscreen.html:
  └ PASS [expected FAIL] iframe-noload-noallowfullscreen

  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-iframe-element/iframe-allowfullscreen.html:
  └ PASS [expected FAIL] iframe-noload-allowfullscreen
```

**Pull request merged**
