### PR TITLE
Add another layer of rAF to avoid intermittent failures.

### LINKED ISSUE #22445: Intermittent failure in /_mozilla/mozilla/animation-removed-node.html
```
{"status": "FAIL", "group": "default", "message": "assert_equals: expected 0 but got 1", "stack": "window.onload</<@http://web-platform.test:8000/_mozilla/mozilla/animation-removed-node.html:23:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1566:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1590:20\n", "subtest": "Animations are no longer active when a node can't be animated.", "test": "/_mozilla/mozilla/animation-removed-node.html", "line": 149673, "action": "test_result", "expected": "PASS"}
```
Maybe two requestAnimationFrame calls will do the trick :<

### PR DESCRIPTION
**Pull request by jdm**
Hopefully fixes #22445.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22447)

### CODE REVIEW

**Comment by ferjm** [comment]
We are missing a `./mach update-manifest` here.

**Comment by CYBAI** [comment]
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: elementFromPoint should get outer element expected Element node <div id=\"outer\" style=\"background:yellow\">\n  <div id=\"inn... but got Element node <html><head><meta charset=\"utf-8\">\n<title>cssom-view - el...", 
    "stack": "window.onload/<@http://web-platform.test:8000/css/cssom-view/negativeMargins.html:18:6\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1566:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\nwindow.onload@http://web-platform.test:8000/css/cssom-view/negativeMargins.html:17:4\n", 
    "subtest": "cssom-view - elementFromPoint and elementsFromPoint dealing with negative margins", 
    "test": "/css/cssom-view/negativeMargins.html", 
    "line": 65018, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Pull request merged**
