### PR TITLE
Use attribute getter/setter macros for misc DOM attributes.

### PR DESCRIPTION
**Pull request by eefriedman**
This fixes a few minor bugs.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8245)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +C-needs-test +S-needs-code-changes 


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/script/dom/htmltablecellelement.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8245#-K1nPkvvBJg5q3BxzjJz)** ([raw file](https://github.com/servo/servo/blob/87de3659c3412cdb06fa5e0b2cfd356213fb2401/components/script/dom/htmltablecellelement.rs#L56)):</sup>
We should have a test for this.

Make one that sets it to 0 or a very large integer through this method, and which then checks the attribute value through getAttribute.

The following things might help:

 * https://html.spec.whatwg.org/multipage/infrastructure.html#reflecting-content-attributes-in-idl-attributes:idl-unsigned-long
 * fedad2af1f7c8b36f4ed76e79ebde5516721b11f


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8245)

**Comment by eefriedman** [comment]
Added test.  (The modified test will test the setters for all known attributes for a bug like the colspan bug.)

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes +S-needs-squash 

One last nit and it's good to go. Don't forget to squash the commits together when you are done.


---

Reviewed 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[tests/wpt/web-platform-tests/html/dom/reflection.js, line 144 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8245#-K22TrCoUxsfbcBK4ZYf)** ([raw file](https://github.com/servo/servo/blob/285e29c06637f31a8b8a27c2e454468717924ebd/tests/wpt/web-platform-tests/html/dom/reflection.js#L144)):</sup>
Please explain that `null` means an exception is thrown if there is no default value.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8245)

**Comment by eefriedman** [comment]
Clarified the comment in reflection.js.

**Comment by nox** [comment]
@bors-servo r+

-S-needs-squash 


---

Reviewed 1 of 1 files at r2, 4 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8245)

**Pull request merged**
