### PR TITLE
Update to cargo 0.21.0-nightly (eb6cf012a 2017-07-02)

### PR DESCRIPTION
**Pull request by SimonSapin**
Cargo binaries are now produced on Rust’s CI, not Cargo’s. Remove cargo-commit-hash and find Cargo based on rust-commit-hash.

Unfortunately, Cargo binaries are not available for every Cargo PR anymore: https://github.com/rust-lang/cargo/pull/4123#issuecomment-316201869

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17780)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
error: failed to run custom build command for `libz-sys v1.0.13`
process didn't exit successfully: `c:\buildbot\slave\windows-msvc-dev\build\target\debug\build\libz-sys-4abfd0d9bb7613d5\build-script-build` (exit code: 1)
--- stdout
running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\nmake.exe" "/nologo" "/f" "c:\\buildbot\\slave\\windows-msvc-dev\\build\\target\\debug\\build\\libz-sys-d0b3a110f6f2f1d0\\out\\build/win32/Makefile.msc" "zlib.lib"


command did not execute successfully, got: exit code: 2



--- stderr

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1065: invalid option '-'
Stop.
```

I’m a bit surprised that updating Cargo would cause this… let’s see if it’s intermittent:

@bors-servo retry

**Comment by SimonSapin** [comment]
Same.

**Comment by SimonSapin** [comment]
@alexcrichton, any idea why we’d get `NMAKE : fatal error U1065: invalid option '-'` when compiling libz-sys on Windows after updating Cargo?

I’ll try bisecting Cargo tomorrow. The initial range is 2233f51 2017-05-17 to eb6cf012a 2017-07-02.

**Comment by SimonSapin** [comment]
> I’ll try bisecting Cargo tomorrow. The initial range is 2233f51 2017-05-17 to eb6cf012a 2017-07-02.

… except I don’t have access to a Windows dev environment, and bisecting through AppVeyor sounds like a pain.

**Comment by alexcrichton** [comment]
I believe that corresponds to https://github.com/rust-lang/cargo/issues/4156 which should be fixed on master branches of things, but I think Cargo may not have been updated? You can also update `libz-sys` as well to fix that (and likely a few other `*-sys` dependencies)

**Comment by SimonSapin** [comment]
> You can also update libz-sys

Let’s try this.

@bors-servo r=nox,SimonSapin

**Comment by SimonSapin** [comment]
Thanks for your help Alex!

**Pull request merged**
