### PR TITLE
Make external script sources load asynchronously, yet still block furthe...

### PR DESCRIPTION
**Pull request by jdm**
...r parsing. Hook up document loading to async networking events.

Relies on https://github.com/servo/html5ever/pull/107, so we'll likely need to backport it rather than wait for the next rustc upgrade.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5727)

### CODE REVIEW

**Comment by jdm** [comment]
@Ms2ger do you feel like reviewing this?

**Comment by mbrubeck** [comment]
Review status: 23 of 30 files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- tests/wpt/metadata/html/semantics/scripting-1/the-script-element/async_006.htm.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/015.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/015a.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/017.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/020.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/022.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/023.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/024.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/038.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/046.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/047.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/049.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/050.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/051.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/053.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/069.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/076.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/078.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/095.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/105.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/123.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/126.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/134.html.ini @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5727)

**Comment by mbrubeck** [comment]
Review status: 27 of 30 files reviewed, 1 unresolved discussion, some commit checks failed.
Reviewed files:
- components/script/dom/document.rs @ r1
- components/script/dom/domparser.rs @ r1
- components/script/dom/htmlscriptelement.rs @ r1
- components/script/parse/mod.rs @ r1

---

<sup>**[components/script/dom/htmlscriptelement.rs, line 177 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5727#-JphBZtmvpYUG0bMrfc2)** ([raw file](https://github.com/servo/servo/blob/3d22625b6f5272aea53ba8d32c56f6a67e0f9b53/components/script/dom/htmlscriptelement.rs#L177)):</sup>
This could use `Vec::append` instead of `extend` to do this more efficiently.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5727)

**Comment by mbrubeck** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/net_traits/lib.rs @ r2
- components/script/document_loader.rs @ r2
- components/script/dom/document.rs @ r2
- components/script/dom/domparser.rs @ r2
- components/script/dom/htmlscriptelement.rs @ r2
- components/script/dom/servohtmlparser.rs @ r2
- components/script/parse/html.rs @ r2
- components/script/script_task.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5727)

**Comment by mbrubeck** [comment]
I just noticed in testing that servo-shell is broken in this branch, for some reason.

**Comment by jdm** [comment]
Good catch; thanks.

**Comment by jdm** [comment]
Turns out I had already fixed this locally and forgot to push.

**Comment by mbrubeck** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/script/document_loader.rs @ r3
- components/script/dom/htmlscriptelement.rs @ r3
- tests/wpt/metadata/html/semantics/scripting-1/the-script-element/async_008.htm.ini @ r3
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/081.html.ini @ r3
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/082.html.ini @ r3
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/092.html.ini @ r3
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/122.html.ini @ r3
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/125.html.ini @ r3
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/130.html.ini @ r3
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/134.html.ini @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5727)

**Pull request merged**
