### PR TITLE
Fixing some style related issues in WebGPU.

### PR DESCRIPTION
**Pull request by imiklos**
Changed the Requests/Response from tuples to named struct variants and also sorted in alphabetical order.
Replaced the ID generator functions from `globalscope` with a single function, which returns a `RefMut` and can call the appropriate method to generate resource IDs.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

cc @kvark @jdm @zakorgy

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Nice improvements!

**Comment by imiklos** [comment]
I've used the wrong `RefMut` type. I will update the pull request with this fix.

**Comment by jdm** [comment]
@bors-servo retry
* network issues

**Pull request merged**
