### PR TITLE
Support None and NotSet for the fallback type of SVGPaint.

### PR DESCRIPTION
**Pull request by kuoe0**
We didn't set None and NotSet for the fallback type of SVGPaint, and it caused the fallback color is wrong when fallback color is empty or keyword `none`. So, we add the None and NotSet support for it.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix [Bug 1380590](https://bugzilla.mozilla.org/show_bug.cgi?id=1380590)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because of the test cases already in Gecko.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18376)

### CODE REVIEW

**Comment by chenpighead** [comment]
This has been reviewed by @upsuper in [Bug 1380590](https://bugzilla.mozilla.org/show_bug.cgi?id=1380590)

**Comment by chenpighead** [comment]
#18374....:(

**Comment by jdm** [comment]
This can be retried now.

**Pull request merged**
