### PR TITLE
Expose DOMHighResTimeStamps at lower res

### LINKED ISSUE #21276: Intermittent pass in /performance-timeline/webtiming-resolution.any.worker.html
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Verifies the resolution of performance.now() is at least 20 microseconds.", "test": "/performance-timeline/webtiming-resolution.any.worker.html", "line": 41625, "action": "test_result", "expected": "FAIL"}
```

### LINKED ISSUE #25296: Intermittent failure in /performance-timeline/webtiming-resolution.any.html
```
  ▶ Unexpected subtest result in /performance-timeline/webtiming-resolution.any.html:
  └ PASS [expected FAIL] Verifies the resolution of performance.now() is at least 5 microseconds.
```

### LINKED ISSUE #25656: Coarsen the granularity of timing functions exposed to DOM
https://www.w3.org/TR/hr-time-2/#clock-resolution

#25296 and #21276 are because we're not doing this, so the apparent granularity depends on randomly how far apart the consecutive performance.now() calls are.

### PR DESCRIPTION
**Pull request by pshaughn**
As explained in https://www.w3.org/TR/hr-time-2/#clock-resolution and tested in a few WPT tests, we're not supposed to show Javascript the full resolution of OS timestamps. This fixes that on all the DOMHighResTimeStamp interfaces that weren't already limiting themselves to integer milliseconds.

The specific choice of how to coarsen the resolution is extremely bikesheddable; I commented the reasoning for my arbitrary choice but I admit it's arbitrary.

A couple tests of timing resolution still fail, but because they're seeing undefined and NaN values due to unimplemented attributes (#25658).

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25656 fix #25296 fix #21276 

- [X] There are tests for these changes

### CODE REVIEW

**Comment by pshaughn** [comment]
```1 unexpected results that are NOT known-intermittents:
  ▶ Unexpected subtest result in /_mozilla/mozilla/window_performance.html:
  │ FAIL [expected PASS] window_performance
  │   → assert_greater_than: expected a number greater than 298.19 but got 298.19
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/window_performance.html:33:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  │ test@http://web-platform.test:8000/resources/testharness.js:548:30
  └ @http://web-platform.test:8000/_mozilla/mozilla/window_performance.html:9:1
```

I'll look into what this test is asking; my guess is that it's a bad test that expects behavior the HR-Time spec is specifically telling us not to have.

**Comment by pshaughn** [comment]
I think I understand what that test wanted to do, and with this change it should be able to keep doing it.
@bors-servo try=wpt

**Comment by pshaughn** [comment]
There we go, down to the CSS reftest roulette now.

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Pull request merged**
