### PR TITLE
Implement currentColor for Canvas colors

### PR DESCRIPTION
**Pull request by dzbarsky**
I made addColorStop throw for currentColor, which matches Firefox.  It's easy enough to change the behavior to fetch the color from the canvas, which is what Chrome and Safari do. I'll file a spec bug to decide what to do here.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7120)

### CODE REVIEW

**Comment by Ms2ger** [comment]
> It's easy enough to change the behavior to fetch the color from the canvas

It actually isn't: these objects are not bound to one particular canvas.

**Comment by dzbarsky** [comment]
Simon found the spec text in https://github.com/servo/servo/issues/7106 and I updated the PR to match. It doesn't check whether the canvas is actually being rendered, I'll do that in a followup since I'll need to add a new message and some layout code.

**Comment by dzbarsky** [comment]
The second commit checks if the canvas is rendered before grabbing the used color for currentColor.
With it, we pass the following testcase:
```
     var canvas = document.getElementById('canvas');
    var ctx = canvas.getContext('2d');
    canvas.style.color = 'red';
    canvas.style.display = 'none';
    canvas.offsetTop;
    ctx.fillStyle = 'currentColor';
 canvas.style.display = 'inline';
  ctx.fillRect(0, 0, 100, 50);
```
However, Firefox, Chrome, and Safari all display a red rect instead of a black one, so I think this requirement isn't actually necessary.

**Comment by Ms2ger** [comment]
I don't see that test case in the PR? ;)

**Comment by dzbarsky** [comment]
I didn't want to spend effort making it an actual reftest in case we decided not to land the second patch. If you think we should follow the spec here instead of changing it to match browsers, I can add the test.

**Comment by Ms2ger** [comment]
I'd probably stick with matching current browsers and filing issues. I still want the test, though, with the colours swapped.

**Comment by dzbarsky** [comment]
Ok, I changed the test a little and added it.

**Comment by dzbarsky** [comment]
I've already rebased this a few times so I'll hold off on rebasing again until it's reviewed.

**Comment by metajack** [comment]
@ms2ger review ping

**Comment by Ms2ger** [comment]
I thought I'd redirected this… r? @SimonSapin

**Comment by SimonSapin** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/canvasgradient.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7120#-K-J7FHIL9KGyNxMpVLv)** ([raw file](https://github.com/servo/servo/blob/0bc7ad9b08d3ae978be4a95687025f00cfcff312/components/script/dom/canvasgradient.rs#L53)):</sup>
Is this function still used at all? If not, please remove it.


---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 426 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7120#-K-J6yKxg3BaVNjlcvF3)** ([raw file](https://github.com/servo/servo/blob/6725e8ab9d9995b34de5316b2ba4fae702ef588f/components/script/dom/canvasrenderingcontext2d.rs#L426)):</sup>
This seems wasteful: it serializes an RGBA struct to a string just to parse it again. Could this code access the `ComputedValues` struct directly, rather than use `GetComputedStyle`?


---

<sup>**[tests/wpt/web-platform-tests/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.notrendered.html, line 2 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7120#-K-J8AwXay5pxN0iQCh7)** ([raw file](https://github.com/servo/servo/blob/6725e8ab9d9995b34de5316b2ba4fae702ef588f/tests/wpt/web-platform-tests/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.notrendered.html#L2)):</sup>
I don’t see this file upstream. @Ms2ger, would it be removed at the next sync? Should it go to `tests/wpt/mozilla` instead?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7120)

**Comment by frewsxcv** [comment]
@dzbarsky Any updates on this?

**Comment by dzbarsky** [comment]
Didn't realize this got reviewed, I'll fix it up.

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[components/script/dom/canvasgradient.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7120#-K-J7FHIL9KGyNxMpVLv:-K3fbg25R3AjlY8oYYCu:666998949) ([raw file](https://github.com/servo/servo/blob/0bc7ad9b08d3ae978be4a95687025f00cfcff312/components/script/dom/canvasgradient.rs#L53)):_
which function? parse_color is still used in canvasrenderingcontext2d.

---

_[components/script/dom/canvasrenderingcontext2d.rs, line 426 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7120#-K-J6yKxg3BaVNjlcvF3:-K3fah0zvlxELXVstPMk:-1867788954) ([raw file](https://github.com/servo/servo/blob/6725e8ab9d9995b34de5316b2ba4fae702ef588f/components/script/dom/canvasrenderingcontext2d.rs#L426)):_
It seems like we need a TSLayounNode to access ComputedStyles and I'm not even sure if that's ok to create from script. The complexity doesn't seem worth it for this edge case.

---

_[tests/wpt/web-platform-tests/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.notrendered.html, line 2 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7120#-K-J8AwXay5pxN0iQCh7:-K3fWXcyDRKE9426L599:-1191549338) ([raw file](https://github.com/servo/servo/blob/6725e8ab9d9995b34de5316b2ba4fae702ef588f/tests/wpt/web-platform-tests/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.notrendered.html#L2)):_
I believe it gets added for WPT (as opposed to CSS tests)

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7120)_

**Comment by jdm** [comment]
The computed styles question sounds very similar to #7267.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7120#-:-K3ohkYH1hbVjmboKoGr:1236647940)_

**Comment by frewsxcv** [comment]
```
./components/script/dom/canvasrenderingcontext2d.rs:444: missing space after ,
```

**Pull request merged**
