### PR TITLE
Add 'appearance' property to Stylo (with '-webkit-appearance' alias)

### PR DESCRIPTION
**Pull request by Manishearth**
r=me from https://bugzilla.mozilla.org/show_bug.cgi?id=1333482

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16110)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo delegate=MatsPalmgren

Please use `@` `bors-servo r=Manishearth` in a comment to land this PR

**Comment by bholley** [comment]
Oh, looks like this is missing a checked-in binding update, and won't compile. :-(

@bors-servo r-

**Comment by bholley** [comment]
I uploaded a new PR in #16112.

**Pull request closed without merging**
