### PR TITLE
Implement ChildNode::before & ChildNode::after

### PR DESCRIPTION
**Pull request by frewsxcv**
Continued from #6536

The current implementations of `ChildNode::before` and
`ChildNode::after` do not match the WHATWG spec. This commit updates the
implementations to match the spec.

Our current implementation of `ChildNode::after` passes all the WPT
tests. So I made sure to add a regression test that failed with the
current implementation. There are a few other unit tests I added
to exhaust other corner cases I encountered.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6800)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/utils.rs, line 983 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIjudsBlz56Pjg5pl6)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/components/script/dom/bindings/utils.rs#L983)):</sup>
I think I' prefer keeping this in `node.rs`.

---

<sup>**[components/script/dom/bindings/utils.rs, line 987 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIlSldEkT5yyt4zCWH)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/components/script/dom/bindings/utils.rs#L987)):</sup>
How about
```rust
nodes.find(|node| {
    not_in.iter().all(|n| {
        match n {
            &NodeOrString::eNode(ref n) => *n != node,
            _ => true,
        }
    })
})
```
?

(I like my iterator methods.)

---

<sup>**[components/script/dom/node.rs, line 818 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIlhYGtUnDvqVXrL1k)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/components/script/dom/node.rs#L818)):</sup>
`.map(|s| s.root())` should be just `.root()`

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/ChildNode-after.html, line 110 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIjfJ6YE24oJuXfkjh)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/tests/wpt/web-platform-tests/dom/nodes/ChildNode-after.html#L110)):</sup>
Ditto

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html, line 110 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIjMaKTfrzjqoO5_oe)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html#L110)):</sup>
"all siblings" doesn't seem to be true.

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIjSzkCbl2pauuuXeG)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html#L112)):</sup>
You seem to have forgotten
```js
var parent = document.createElement("div")
var x = parent.appendChild(document.createElement("a"));
var y = parent.appendChild(document.createElement("b"));
var z = parent.appendChild(document.createElement("c"));
var u = parent.appendChild(document.createElement("d"));
parent.appendChild(child);
child.before(z, u);
```
from <https://github.com/servo/servo/pull/6536#issuecomment-121596314>.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Comment by frewsxcv** [comment]
<sup>**[tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIjSzkCbl2pauuuXeG)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html#L112)):</sup>
Out of curiosity, what is being tested in the codeblock you pasted that's not already being tested?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/node.rs, line 818 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIlhYGtUnDvqVXrL1k)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/components/script/dom/node.rs#L818)):</sup>
`OptionalRootable` (which presumably made this method on `Option` possible) was removed in https://github.com/servo/servo/pull/6150

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Comment by frewsxcv** [comment]
<sup>**[tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIjSzkCbl2pauuuXeG)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html#L112)):</sup>
I just added it in into the latest force push

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Comment by frewsxcv** [comment]
Addressed all the comments in the latest force push, with exception to the `OptionalRootable`.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Comment by Ms2ger** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 818 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIlhYGtUnDvqVXrL1k)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/components/script/dom/node.rs#L818)):</sup>
Bah. File an issue to bring it back.

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/ChildNode-after.html, line 111 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvOijMIOylBheiVwNbq)** ([raw file](https://github.com/servo/servo/blob/e785a4bcbbaefcfc2281526265e81078293d30e5/tests/wpt/web-platform-tests/dom/nodes/ChildNode-after.html#L111)):</sup>
Separate test

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html, line 111 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvOi7KgiylS3OyZTEAy)** ([raw file](https://github.com/servo/servo/blob/e785a4bcbbaefcfc2281526265e81078293d30e5/tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html#L111)):</sup>
Separate test?

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html, line 126 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIjSzkCbl2pauuuXeG)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html#L126)):</sup>
The viable sibling not being the first child, iirc

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/node.rs, line 818 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIlhYGtUnDvqVXrL1k)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/components/script/dom/node.rs#L818)):</sup>
https://github.com/servo/servo/issues/6833

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Comment by frewsxcv** [comment]
<sup>**[tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6800#-JvIjSzkCbl2pauuuXeG)** ([raw file](https://github.com/servo/servo/blob/ae2ca781149ad284941df0776fb2b9885c248abf/tests/wpt/web-platform-tests/dom/nodes/ChildNode-before.html#L112)):</sup>
Ah, good point. That makes sense

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Comment by frewsxcv** [comment]
The latest force push addresses the second round of comments

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Comment by Ms2ger** [comment]
Thank you for your PR.

-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6800)

**Pull request merged**
