### PR TITLE
Add a reusable sheets parameter to Servo_StyleSheet_FromUTF8Bytes.

### PR DESCRIPTION
**Pull request by bradwerth**
MozReview-Commit-ID: DdMQpUY1WcJ

https://bugzilla.mozilla.org/show_bug.cgi?id=1387933
https://reviewboard.mozilla.org/r/171308/

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18207)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r=xidorn

 * You should probably get added to the `operators` list in servo/saltfs

**Comment by jdm** [comment]
That's #15227; you can retry.

**Pull request merged**
