### PR TITLE
Script: ensure child JS runtimes are dropped before parent

### LINKED ISSUE #24168: Crash after checking google reCAPTCHA
While accessing https://codepen.io/davidkpiano/pen/aNKxeo , I was asked to confirm I'm not a robot. 

But, after clicking the recaptcha checkbox, it just hanged for a while and then crash into unexpected scheme.

image

```
→ ./mach run https://codepen.io/davidkpiano/pen/aNKxeo
assertion failed: `(left == right)`
  left: `2`,
 right: `1`: This runtime still has live children. (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(3) }, at /Users/cybai/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/92136c0/src/rust.rs:371)
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized::h40e4195d9ed0871f (0x10ab0769d)
   1: backtrace::backtrace::trace::h91e46b16eaa624ee (0x10ab07623)
   2: backtrace::capture::Backtrace::create::hbfce518757b8ffcb (0x10aaf6297)
   3: backtrace::capture::Backtrace::new::hb9268a49cde77588 (0x10aaf61d6)
   4: servo::main::{{closure}}::h02bf8385eaabe81f (0x102f77aa2)
   5: std::panicking::rust_panic_with_hook::h099fe3773ce1a793 (0x10b2a45f2)
   6: std::panicking::continue_panic_fmt::h8a4b76634870b383 (0x10b2a405d)
   7: std::panicking::begin_panic_fmt::hd8effa78bdafa918 (0x10b2a3fbe)
   8: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop::ha77e6fc5bb2ad588 (0x106cd4b7a)
   9: core::ptr::real_drop_in_place::h131afef99a7c5ff4 (0x104ceae05)
  10: core::ptr::real_drop_in_place::h9af35cbe64f80de5 (0x104d55097)
  11: core::ptr::real_drop_in_place::hbf5bfabd356df2d2 (0x104d71fbe)
  12: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::hf3b449128d421963 (0x1058b2c8e)
  13: core::ptr::real_drop_in_place::h5afdeb3415187ccc (0x104d236d5)
  14: core::ptr::real_drop_in_place::h46c90f9a53db27e5 (0x104d141de)
  15: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::hdfdac7e64255f05b (0x106347b1d)
  16: std::sys_common::backtrace::__rust_begin_short_backtrace::h042b2ce54b0f5bed (0x103ed0253)
  17: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h80b0f5a81ea723de (0x1069bbfe3)
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7d69a1ef1908ebf7 (0x104ad4e43)
  19: std::panicking::try::do_call::h64eb6f0b577f6c7a (0x104a2c505)
  20: __rust_maybe_catch_panic (0x10b2ac9af)
  21: std::panicking::try::h2b5c1fedeff81527 (0x10483d6d5)
  22: std::panic::catch_unwind::h86f80d6d3cdb7d12 (0x104b2af53)
  23: std::thread::Builder::spawn_unchecked::{{closure}}::h4248ae127b2483cb (0x1069bab2c)
  24: core::ops::function::FnOnce::call_once{{vtable.shim}}::h7ec2ee8ea567f224 (0x104c7d875)
  25: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb03304ace7f89c63 (0x10b293b4e)
  26: std::sys::unix::thread::Thread::new::thread_start::hd2d570f25bb299f3 (0x10b2abebe)
  27: _pthread_body (0x7fff734b92eb)
  28: _pthread_start (0x7fff734bc249)
[2019-09-10T04:53:34Z ERROR servo] assertion failed: `(left == right)`
  left: `2`,
 right: `1`: This runtime still has live children.
^CServo exited with return value -2
```

Built with 6ed204d692 on macOS 10.14.6

### LINKED ISSUE #25729: Panic logging into bandcamp
```
[2020-02-11T16:27:00Z ERROR script::dom::bindings::error] Error at :0:0 SecurityError: The operation is insecure.
11:27:07.832:
executing invisible recaptcha (scrollTopBeforeExecute = 0)
assertion failed: `(left == right)`
  left: `2`,
 right: `1`: This runtime still has live children. (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(3) }, at /Users/jdm/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/9b0d063/src/rust.rs:410)
stack backtrace:
[2020-02-11T16:27:11Z ERROR script::dom::bindings::error] Error at :0:0 SecurityError: The operation is insecure.
   0: backtrace::backtrace::libunwind::trace
             at /Users/jdm/.cargo/git/checkouts/backtrace-rs-96ebaf1bcb788384/91a0aa4/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/jdm/.cargo/git/checkouts/backtrace-rs-96ebaf1bcb788384/91a0aa4/src/backtrace/mod.rs:66
   1: <servo::backtrace::Print as core::fmt::Debug>::fmt
             at ports/glutin/backtrace.rs:49
   2: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   3: std::io::Write::write_fmt
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libstd/io/mod.rs:1426
   4: servo::backtrace::print
             at ports/glutin/backtrace.rs:17
   5: servo::main::{{closure}}
             at ports/glutin/main2.rs:152
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   7: rust_begin_unwind
             at src/libstd/panicking.rs:380
   8: std::thread::local::fast::Key<T>::try_initialize
   9: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop
             at /Users/jdm/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/9b0d063/src/rust.rs:410
  10: core::ptr::real_drop_in_place
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libcore/ptr/mod.rs:184
  11: core::ptr::real_drop_in_place
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libcore/ptr/mod.rs:184
  12: core::ptr::real_drop_in_place
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libcore/ptr/mod.rs:184
  13: core::ptr::drop_in_place
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libcore/ptr/mod.rs:174
      <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/liballoc/rc.rs:1102
  14: core::ptr::real_drop_in_place
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libcore/ptr/mod.rs:184
  15: core::ptr::real_drop_in_place
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libcore/ptr/mod.rs:184
  16: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
             at components/script/script_thread.rs:816
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libstd/sys_common/backtrace.rs:129
  18: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libstd/thread/mod.rs:475
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libstd/panic.rs:318
  20: std::panicking::try::do_call
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libstd/panicking.rs:305
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  22: std::panicking::try
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libstd/panicking.rs:281
  23: std::panic::catch_unwind
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libstd/panic.rs:394
  24: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libstd/thread/mod.rs:474
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/libcore/ops/function.rs:232
  26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/liballoc/boxed.rs:1015
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/3291ae33907f2a866ea6cea89113200555038d06/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  28: <unknown>
  29: <unknown>
[2020-02-11T16:27:13Z ERROR servo] assertion failed: `(left == right)`
  left: `2`,
 right: `1`: This runtime still has live children.
```

### LINKED ISSUE #26778: Panic after loading a codesandbox page
```
→ ./mach run -Z replace-surrogates https://tsdxi.csb.app/
[2020-06-04T05:30:10Z ERROR script::dom::bindings::conversions] Found an unpaired surrogate in a DOM string. If you see this in real web content, please comment on https://github.com/servo/servo/issues/6564
The above error occurred in the <circle> component:
    in circle (at App.js:8)
    in svg (at App.js:7)
    in div (at App.js:6)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
Error in sandbox:
TypeError: style is undefined
assertion failed: `(left == right)`
  left: `4`,
 right: `1`: This runtime still has live children. (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /Users/cybai/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/dbb9bee/src/rust.rs:424)
   0: backtrace::backtrace::libunwind::trace
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/mod.rs:66
   1: <servo::backtrace::Print as core::fmt::Debug>::fmt
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/backtrace.rs:49
   2: core::fmt::write
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libcore/fmt/mod.rs:1069
   3: std::io::Write::write_fmt
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/io/mod.rs:1537
   4: servo::backtrace::print
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/backtrace.rs:17
   5: servo::main::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/ports/winit/main2.rs:150
   6: std::panicking::rust_panic_with_hook
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:481
   7: rust_begin_unwind
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:385
   8: std::panicking::begin_panic_fmt
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:339
   9: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop
             at /Users/cybai/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/dbb9bee/src/rust.rs:424
  10: core::ptr::drop_in_place
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
  11: core::ptr::drop_in_place
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
  12: core::ptr::drop_in_place
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
  13: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/rc.rs:1150
  14: core::ptr::drop_in_place
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
  15: core::ptr::drop_in_place
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:178
  16: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
             at /Volumes/Transcend/codespace/mozilla/servo/components/script/script_thread.rs:806
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130
  18: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:318
  20: std::panicking::try::do_call
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:297
  21: ___rust_try
  22: std::panicking::try
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  23: std::panic::catch_unwind
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/panic.rs:394
  24: std::thread::Builder::spawn_unchecked::{{closure}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /Users/cybai/.rustup/toolchains/nightly-2020-05-15-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/liballoc/boxed.rs:1034
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/liballoc/boxed.rs:1034
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/sys/unix/thread.rs:87
  27: __pthread_body
  28: __pthread_start
[2020-06-04T05:35:58Z ERROR servo] assertion failed: `(left == right)`
      left: `4`,
     right: `1`: This runtime still has live children.
```

### LINKED ISSUE #28357: Invalid datachannel (thread <unnamed>, at /root/.cargo/git/checkouts/media-c23a3cd5aa97076a/b23e722/backends/gstreamer/datachannel.rs:87)
this crash on 
```
./servo  --pref dom.svg.enabled  --pref dom.webrtc.enabled https://vrland.io/openspace
```

fedora Linux
libnice-gstreamer1-0.1.17-3.fc33.x86_64  

```
./servo  --pref dom.svg.enabled  --pref dom.webrtc.enabled https://vrland.io/openspace
%ccore:schema:warn %cDefault value `false` does not match type `number` in component `layout`%c  color: orange color: inherit color: orange
%ccore:schema:warn %cDefault value `null` does not match type `string` in component `hud-share-indicator`%c  color: orange color: inherit color: orange
%ccore:schema:warn %cDefault value `null` does not match type `string` in component `hud-share-indicator`%c  color: orange color: inherit color: orange
%ccore:schema:warn %cDefault value `null` does not match type `string` in component `media-loader`%c  color: orange color: inherit color: orange
%ccore:schema:warn %cDefault value `null` does not match type `string` in component `media-loader`%c  color: orange color: inherit color: orange
%ccore:schema:warn %cDefault value `16711680` does not match type `string` in component `box-rounded`%c  color: orange color: inherit color: orange
%ccore:schema:warn %cDefault value `16711680` does not match type `string` in component `box-rounded-text`%c  color: orange color: inherit color: orange
%ccore:schema:warn %cDefault value `null` does not match type `string` in component `emit-scene-event-on-remove`%c  color: orange color: inherit color: orange
%ccore:component:warn %cThe component name `preventDefaultKeys` contains uppercase characters, but HTML will ignore the capitalization of attribute names. Change the name to be lowercase: `preventdefaultkeys`%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `hiref` for component/system `undefined`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `enable` for component/system `undefined`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `enable` for component/system `undefined`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `metalness` for component/system `material`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `roughness` for component/system `material`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `enable` for component/system `wasd-to-analog2d`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `clientid` for component/system `networked-scene`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `screenShare` for component/system `reaction`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `shareCam` for component/system `reaction`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `enable` for component/system `avatar-actions`.%c  color: orange color: inherit color: orange
%ccore:schema:warn %cUnknown property `enable` for component/system `preventDefaultKeys`.%c  color: orange color: inherit color: orange
Invalid datachannel (thread <unnamed>, at /root/.cargo/git/checkouts/media-c23a3cd5aa97076a/b23e722/backends/gstreamer/datachannel.rs:87)
[2021-04-11T18:27:28Z ERROR servo] Invalid datachannel
called `Result::unwrap()` on an `Err` value: RecvError (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /root/.cargo/git/checkouts/media-c23a3cd5aa97076a/b23e722/webrtc/thread.rs:73)
[2021-04-11T18:27:28Z ERROR servo] called `Result::unwrap()` on an `Err` value: RecvError
assertion failed: `(left == right)`
  left: `2`,
 right: `1: This runtime still has live children.` (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /root/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/ef63e56/src/rust.rs:420)
[2021-04-11T18:27:28Z ERROR servo] assertion failed: `(left == right)`
      left: `2`,
     right: `1: This runtime still has live children.`
thread panicked while panicking. aborting.
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }"
   0: servo::backtrace::print
   1: servo::crash_handler::install::handler
```

### LINKED ISSUE #30124: Intermittent CRASH in /streams/readable-streams/crashtests/strategy-worker-terminate.html
This happens in layout 2020 

```
Shutting down the Constellation after generating an output file or exit flag specified
assertion failed: `(left == right)`
  left: `2`,
 right: `1`: This runtime still has live children. (thread Script(1,1), at /home/mukilan/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/8216870/rust-mozjs/src/rust.rs:411)
   0: servo::backtrace::print
   1: servo::main::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
   7: core::panicking::assert_failed_inner
   8: core::panicking::assert_failed
   9: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop
  10: core::ptr::drop_in_place<mozjs::rust::Runtime>
  11: core::ptr::drop_in_place<script::script_runtime::Runtime>
  12: core::ptr::drop_in_place<script::script_thread::ScriptThread>
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/sys/unix/thread.rs:108:17
  16: start_thread
  17: __clone3
mozilla::detail::MutexImpl::~MutexImpl: pthread_mutex_destroy failed: Device or resource busy
Caught signal 11 thread panicked while processing panic. aborting.
Redirecting call to abort() to mozalloc_abort
```

### PR DESCRIPTION
**Pull request by gterzian**
Remove the annoying `This runtime still has live children.` that keeps showing up. 

Many issues that contain that backtrace as opposed to the actual underlying problem: 

FIX https://github.com/servo/servo/issues/30124 
FIX https://github.com/servo/servo/issues/24168 
FIX https://github.com/servo/servo/issues/25729 
FIX https://github.com/servo/servo/issues/28357 
FIX https://github.com/servo/servo/issues/26778

Marking them as fixed, because it appears to me that the original panic is already filed in other issues(i've pointed it out in each issue). 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by mrobinson** [comment]
Looks like this is just failing due to a tidy issue. It should be fixed with `./mach fmt`.

**Comment by gterzian** [comment]
See https://github.com/servo/servo/issues/30124#issuecomment-1864013277 for an exaplanation, and I think the conclusion is that every time script crashes, we drop the "top" runtime as part of `clear_js_runtime_for_script_deallocation`, which gives us another panic in case there are outstanding children. 

See https://github.com/servo/servo/blob/205d52a0c912a8418cbaf70bb82af3e182decc1d/components/script/script_thread.rs#L755

Compare with the "clean" version which is followed on orderly shutdown of a pipepline: https://github.com/servo/servo/blob/205d52a0c912a8418cbaf70bb82af3e182decc1d/components/script/script_thread.rs#L2984

**Comment by gterzian** [comment]
@mrobinson r?

**Comment by gterzian** [comment]
Ok so this required different fixes, because each linked-to issues was actually hitting a different problem. All are covered now. 

@mrobinson r?

**Review by sagudev — APPROVED** [review]

**Review by jdm — APPROVED** [review]
This makes sense! My only question is whether we should use an object with a Drop impl that could replace the manual calls in the dedicated worker code?

**Comment by sagudev** [comment]
> This makes sense! My only question is whether we should use an object with a Drop impl that could replace the manual calls in the dedicated worker code?

`std::mem::forget` is safe and we might be relaying on drops too much already.

**Comment by jdm** [comment]
I'm not concerned about safety, just avoiding any other early return branches where the same fix should be applied but might be missed.

**Comment by gterzian** [comment]
> use an object with a Drop impl that could replace the manual calls in the dedicated worker code?

It appears to not work for now,`drop` of the `WorkerGlobalScope` seems to not be called and the error comes back, so I've filed https://github.com/servo/servo/issues/30971

Have also added a manual branch to the `ServiceWorkerGlobalScope`.

**Comment by sagudev** [comment]
note to self: use `./mach test-wpt tests/wpt/mozilla/tests/mozilla/service-workers/service-worker-registration.https.html` to enter_realm

**Comment by gterzian** [comment]
@jdm I gave the temporary drop object a quick try and the "runtime has live children" problem resurfaced, so I propose we keep it as a follow-up in https://github.com/servo/servo/issues/30971 and merge this as is, how does that sound?

**Comment by mrobinson** [comment]
I'll send this to the merge queue since I think all issues are resolved now.

**Pull request merged**
