### PR TITLE
Add support for running W3C CSS tests.

### PR DESCRIPTION
**Pull request by jgraham**

### CODE REVIEW

**Comment by jdm** [comment]
What's the process for upgrading mozlog/wptrunner/etc?

**Comment by jdm** [comment]
Looks like this finally obsoletes #4085. You won't be so lucky next time @Ms2ger.

**Comment by jgraham** [comment]
For wptrunner I usually just locally init a git repo in tests/wpt/harness with the remote pointing at a wptrunner repo. I'm not sure if that's a terrible idea or a great idea, but it does make it rather convenient to change the upstream when needed.

I don't have a good suggestion for mozlog.

**Comment by jdm** [comment]
How was the mozlog import done?

**Comment by jgraham** [comment]
By copying the files from m-c.

**Comment by metajack** [comment]
I promise @jdm was next on the random assignment :)

**Comment by Manishearth** [comment]
Taking over since @jdm did all the reviews last week :P

**Comment by Manishearth** [comment]
(I'm unable to open the review pages for the large commits from my connection, will finish up in a couple of days.)

**Comment by Manishearth** [comment]
r=me with one nit and rebase

**Comment by larsbergstrom** [comment]
@jgraham Failed with:
http://build.servo.org/builders/linux2/builds/1267/steps/shell_1/logs/stdio

```
Error running mach:

    ['test-wpt', '--processes', '4']

The error occurred in the implementation of the invoked mach command.

This should never occur and is likely a bug in the implementation of that
command. Consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

ImportError: No module named blessings

  File "/home/servo/buildbot/slave/linux2/build/python/servo/testing_commands.py", line 226, in test_wpt
    self.ensure_wpt_virtualenv()
  File "/home/servo/buildbot/slave/linux2/build/python/servo/testing_commands.py", line 300, in ensure_wpt_virtualenv
    import blessings
```

**Comment by jgraham** [comment]
Does that commit do enough?

**Comment by Manishearth** [comment]
Why not just add `blessings` to `requirements_servo.txt`?

But yeah, that should work.

**Comment by larsbergstrom** [comment]
Two issues. 
1) Test failure in http://build.servo.org/builders/linux2/builds/1281/steps/shell_1/logs/stdio:
```
Unexpected Results
==================

/2dcontext/shadows/canvas_shadows_002.htm
-----------------------------------------
```
2) Error codes are inverted:
http://build.servo.org/builders/linux2/builds/1281/steps/shell_1/logs/stdio has a failure but returns 0
http://build.servo.org/builders/mac1/builds/1496/steps/shell_2/logs/stdio succeeds but returns 1

**Comment by jgraham** [comment]
I fixed the exit codes. I'm not sure what to do about the failure given I see (on the rebased branch) some locally, but not that one.

**Comment by Manishearth** [comment]
Larsbors strikes again! :smile:

**Pull request merged**
