### PR TITLE
Update WR and the whole macOS crate stack

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19314)

### CODE REVIEW

**Comment by nox** [comment]
This fails to compile with:

```
error[E0407]: method `new_frame_ready` is not a member of trait `webrender_api::RenderNotifier`
   --> components/compositing/compositor.rs:332:5
    |
332 | /     fn new_frame_ready(&self) {
333 | |         self.compositor_proxy.recomposite(CompositingReason::NewWebRenderFrame);
334 | |     }
    | |_____^ not a member of trait `webrender_api::RenderNotifier`

error[E0407]: method `new_scroll_frame_ready` is not a member of trait `webrender_api::RenderNotifier`
   --> components/compositing/compositor.rs:336:5
    |
336 | /     fn new_scroll_frame_ready(&self, composite_needed: bool) {
337 | |         self.compositor_proxy.send(Msg::NewScrollFrameReady(composite_needed));
338 | |     }
    | |_____^ not a member of trait `webrender_api::RenderNotifier`

error[E0046]: not all trait items implemented, missing: `wake_up`, `new_document_ready`
   --> components/compositing/compositor.rs:327:1
    |
327 | / impl webrender_api::RenderNotifier for RenderNotifier {
328 | |     fn clone(&self) -> Box<webrender_api::RenderNotifier> {
329 | |         Box::new(RenderNotifier::new(self.compositor_proxy.clone()))
330 | |     }
...   |
338 | |     }
339 | | }
    | |_^ missing `wake_up`, `new_document_ready` in implementation
    |
    = note: `wake_up` from trait: `fn(&Self)`
    = note: `new_document_ready` from trait: `fn(&Self, webrender_api::DocumentId, bool, bool)`

error: aborting due to 3 previous errors
```

Still, I wanted to push it because I assume @glennw, @pcwalton or whoever will do the code changes will appreciate having the Cargo changes ready anyway.

**Comment by glennw** [comment]
@nox Thanks! I'll pick up work on this today.

**Comment by glennw** [comment]
@nox I've rebased this and added the necessary API changes patch. 

The only remaining issue I know of is a ```test-tidy``` failure:

```
./Cargo.lock:1: duplicate versions for package `foreign-types`
	The following packages depend on version 0.2.0 from 'crates.io':
		openssl
	The following packages depend on version 0.3.0 from 'crates.io':
		core-graphics
		core-text
  Progress: 100% (5/5)
```

**Comment by glennw** [comment]
@nox Looks like the most recent version of ```openssl``` still uses foreign-types 0.2.0, so I guess we'll need to land a patch upstream for that?

**Comment by nox** [comment]
I squashed everything and added `foreign-types` to the tidy exceptions. It's a small crate and it's not a issue.

**Comment by glennw** [comment]
@nox Thanks, this is ready to go now then, I think. r? @jdm

**Comment by jdm** [comment]
```
error[E0308]: mismatched types
  --> components/gfx/platform/macos/font_template.rs:64:64
   |
64 |                     let fontprov = CGDataProvider::from_buffer(bytes);
   |                                                                ^^^^^ expected struct `std::sync::Arc`, found reference
   |
   = note: expected type `std::sync::Arc<std::vec::Vec<u8>>`
              found type `&std::vec::Vec<u8>`

```

**Comment by nox** [comment]
I will fix this.

**Pull request merged**
