### PR TITLE
view-source protocol and text/plain handling

### PR DESCRIPTION
**Pull request by doublec**
Implements view-source protocol by having a view-source handler, and modifying the content type to be text/plain if that is used. 

Implements text/plain handling. This allows view-source content to display as plain text.

Example usage:

```
./mach run http://cd.pn/x.txt
./mach run view-source:http://tinyvid.tv/
```

This fixes issue #4181. Issue #3649 includes "support text/plain" so this possibly fixes some of that issue as well.

### CODE REVIEW

**Comment by jdm** [comment]
Critic'd!

**Comment by jdm** [comment]
Go ahead an squash!

**Comment by doublec** [comment]
Should I squash these two commits into one, or is it fine just squashing the review comments?

**Comment by jdm** [comment]
Just squashing the review comments is preferable, I think.

**Comment by jdm** [comment]
```

/html/browsers/browsing-the-web/read-text/load-text-plain.html
--------------------------------------------------------------
PASS expected FAIL Checking DOM for text file
```

**Comment by jdm** [comment]
http://mxr.mozilla.org/servo/source/tests/wpt/metadata/html/browsers/browsing-the-web/read-text/load-text-plain.html.ini will need modifications. Might be worth checking why the other tests are still failing, too.

**Comment by doublec** [comment]
Thanks, looking now.

**Comment by doublec** [comment]
This changes the test that was an unexpected pass to be an expected pass. It adds a fix for setting the document content type to "text/plain" and enables that test to be expected to pass. The last failing test fails because we use the workaround of having a `<plaintext>` in the DOM whereas the text expects data to be directly under `<pre>`. I've left that as expected fail.

**Comment by doublec** [comment]
Thanks, I've removed them in the latest commit pushed just now.

**Comment by jdm** [comment]
Looks great! Squash and we'll merge again :)

**Comment by doublec** [comment]
Thanks, squashed and pushed!

**Comment by doublec** [comment]
Is the failure:

    --output=/tmp/tmpO7t5kJ/233aedab-add7-4303-aa26-8f5e58b87309 http://localhost:8000/2dcontext/shadows/canvas_shadows_002-ref.htm
    (pid:22284) "ERROR:js::rust: Error at http://localhost:8000/2dcontext/shadows/canvas_shadows_002-ref.htm:8: TypeError: ctx.drawImage is not a function"
     9:08.67 PROCESS_OUTPUT: Thread-TestrunnerManager-5 (pid:22284) ""
     9:09.18 TEST_END: Thread-TestrunnerManager-5 FAIL, expected PASS

I'm having trouble working out how that happened.

**Comment by jdm** [comment]
Just a known intermittent reftest failure.

**Pull request closed without merging**
