### PR TITLE
Why aren't these tests run?

### PR DESCRIPTION
**Pull request by pyfisch**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19700)

### CODE REVIEW

**Comment by CYBAI** [comment]
Failed with #19495

**Comment by emilio** [comment]
cc @jdm

**Comment by jdm** [comment]
@bors-servo: r+
The try build reports success. That's mysterious.

**Comment by pyfisch** [comment]
@jdm Do you have an idea why these tests marked as "FAIL" in the .ini files are never run? Neither on my machine nor on the builder?

I skimmed over the folder contents and noticed these tests where marked as failing but could not find a reason why they should be and removed the files. But they are not executed even if I try only to run a single test.

**Comment by jdm** [comment]
It looks like it might be because border-bottom-left-radius-003.xht uses border-bottom-left-radius-004.xht as a reference, and border-bottom-left-radius-004.xht uses border-bottom-left-radius-003.xht as a radius, and I think the manifest just becomes confused?

**Comment by jdm** [comment]
I am writing a lint for web-platform-tests that detects these cases and forbids them. We'll start running these tests once that PR is merged upstream and we sync Servo's copy.

**Pull request closed without merging**
