### PR TITLE
Kill test processes whenever any error occurs

### LINKED ISSUE #21822: Test processes that receive errors from a different test don't get counted as an error and don't kill the process
I found this process present on a builder after the test run finished:
```
servo     80834  0.2  1.4 6282940 457680 ?      Sl   17:09   0:01 /home/servo/buildbot/slave/linux-rel-css/build/target/release/servo --hard-fail -u Servo/wptrunner -Z replace-surrogates -z http://web-platform.test:8000/html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-main-frame-navigation.sub.html --user-stylesheet /home/servo/buildbot/slave/linux-rel-css/build/resources/ahem.css --certificate-path /tmp/tmpHYlhql/cacert.pem
```
I looked at the log for that test run and found this output:
```
{"source": "web-platform-tests", "thread": "Thread-TestrunnerManager-33", "time": 1538068199806, "action": "log", "message": "new state: running", "level": "DEBUG", "pid": 82479}
{"source": "web-platform-tests", "thread": "Thread-TestrunnerManager-33", "time": 1538068199806, "action": "log", "message": "Dispatch run_test", "level": "DEBUG", "pid": 82479}
{"source": "web-platform-tests", "test": "/html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-main-frame-navigation.sub.html", "thread": "Thread-TestrunnerManager-33", "time":
1538068199806, "action": "test_start", "pid": 82479}
{"source": "web-platform-tests", "thread": "Thread-TestrunnerManager-33", "time": 1538068199873, "action": "log", "message": "Got command: u'log'", "level": "DEBUG", "pid": 82479}
{"thread": "Thread-TestrunnerManager-33", "process": "80834", "pid": 82479, "source": "web-platform-tests", "command": "/home/servo/buildbot/slave/linux-rel-css/build/target/release/servo --hard-fail -u S
ervo/wptrunner -Z replace-surrogates -z http://web-platform.test:8000/html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-main-frame-navigation.sub.html --user-stylesheet /home/
servo/buildbot/slave/linux-rel-css/build/resources/ahem.css --certificate-path /tmp/tmpHYlhql/cacert.pem", "time": 1538068199873, "action": "process_output", "data": "VMware, Inc."}
{"source": "web-platform-tests", "thread": "Thread-TestrunnerManager-33", "time": 1538068199873, "action": "log", "message": "Got command: u'log'", "level": "DEBUG", "pid": 82479}
{"thread": "Thread-TestrunnerManager-33", "process": "80834", "pid": 82479, "source": "web-platform-tests", "command": "/home/servo/buildbot/slave/linux-rel-css/build/target/release/servo --hard-fail -u S
ervo/wptrunner -Z replace-surrogates -z http://web-platform.test:8000/html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-main-frame-navigation.sub.html --user-stylesheet /home/
servo/buildbot/slave/linux-rel-css/build/resources/ahem.css --certificate-path /tmp/tmpHYlhql/cacert.pem", "time": 1538068199874, "action": "process_output", "data": "softpipe"}
{"source": "web-platform-tests", "thread": "Thread-TestrunnerManager-33", "time": 1538068199874, "action": "log", "message": "Got command: u'log'", "level": "DEBUG", "pid": 82479}
{"thread": "Thread-TestrunnerManager-33", "process": "80834", "pid": 82479, "source": "web-platform-tests", "command": "/home/servo/buildbot/slave/linux-rel-css/build/target/release/servo --hard-fail -u S
ervo/wptrunner -Z replace-surrogates -z http://web-platform.test:8000/html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-main-frame-navigation.sub.html --user-stylesheet /home/
servo/buildbot/slave/linux-rel-css/build/resources/ahem.css --certificate-path /tmp/tmpHYlhql/cacert.pem", "time": 1538068199874, "action": "process_output", "data": "3.3 (Core Profile) Mesa 18.1.0-devel"
}
{"source": "web-platform-tests", "thread": "Thread-TestrunnerManager-33", "time": 1538068200102, "action": "log", "message": "Got command: u'log'", "level": "DEBUG", "pid": 82479}
{"source": "web-platform-tests", "thread": "Thread-TestrunnerManager-33", "time": 1538068200102, "action": "log", "message": "Traceback (most recent call last):\n  File \"/home/servo/buildbot/slave/linux-
rel-css/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py\", line 162, in run_test\n    result = self.do_test(test)\n  File \"/home/servo/buildbot/slave/linux-rel-css/build/te
sts/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py\", line 110, in do_test\n    result = self.convert_result(test, self.result_data)\n  File \"/home/servo/buildbot/slave/linux
-rel-css/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py\", line 69, in __call__\n    (result_url, test.url))\nAssertionError: Got results from /html/browsers/browsing-the-w
eb/history-traversal/support/window-name-test.sub.html?shouldhavename=true&sendmessage=false, expected /html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-main-frame-navigation
.sub.html\n", "level": "WARNING", "pid": 82479}
{"source": "web-platform-tests", "thread": "Thread-TestrunnerManager-33", "time": 1538068200103, "action": "log", "message": "Got command: 'test_ended'", "level": "DEBUG", "pid": 82479}
{"status": "ERROR", "thread": "Thread-TestrunnerManager-33", "extra": {"test_timeout": 10}, "pid": 82479, "source": "web-platform-tests", "test": "/html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-main-frame-navigation.sub.html", "time": 1538068200103, "action": "test_end", "message": "Got results from /html/browsers/browsing-the-web/history-traversal/support/window-name-test.sub.html?shouldhavename=true&sendmessage=false, expected /html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-main-frame-navigation.sub.html\nTraceback (most recent call last):\n  File \"/home/servo/buildbot/slave/linux-rel-css/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py\", line 162, in run_test\n    result = self.do_test(test)\n  File \"/home/servo/buildbot/slave/linux-rel-css/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py\", line 110, in do_test\n    result = self.convert_result(test, self.result_data)\n  File \"/home/servo/buildbot/slave/linux-rel-css/build/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py\", line 69, in __call__\n    (result_url, test.url))\nAssertionError: Got results from /html/browsers/browsing-the-web/history-traversal/support/window-name-test.sub.html?shouldhavename=true&sendmessage=false, expected /html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-main-frame-navigation.sub.html\n"}
```

### PR DESCRIPTION
**Pull request by georgeroman**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #21822 

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22272)

### CODE REVIEW

**Comment by nox** [comment]
```
0:22.20 ERROR Manifest /home/travis/build/servo/servo/tests/wpt/webgl/meta/MANIFEST.json is outdated, use |./mach update-manifest| to fix.
```

**Comment by jdm** [comment]
Oops. Sorry for overlooking this; it would have saved so much time dealing with #22271.

**Pull request merged**
