### PR TITLE
Update WR (text-shadow improvements, iframe + image clips, depth buffer sharing)

### PR DESCRIPTION
**Pull request by mrobinson**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17771)

### CODE REVIEW

**Comment by mrobinson** [comment]
This was #17765. I'm opening a new PR in order to land the rebase of that PR.

**Comment by jdm** [comment]
```
error[E0412]: cannot find type `ServoComputedValues` in this scope
    --> /home/servo/buildbot/slave/linux-dev/build/components/layout/display_list_builder.rs:1875:41
     |
1875 |         let build_local_clip = |style: &ServoComputedValues| {
     |                                         ^^^^^^^^^^^^^^^^^^^ did you mean `ComputedValues`?

   Compiling constellation v0.0.1 (file:///home/servo/buildbot/slave/linux-dev/build/components/constellation)
error: aborting due to previous error

error: Could not compile `layout`.
```

**Comment by mrobinson** [comment]
I did the typical thing which is to fix the rebase locally but forget to commit the changes. I will update this branch.

**Pull request merged**
