### PR TITLE
Update WR (CPU text optimizations, image format renames).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17352)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone

**Comment by glennw** [comment]
@Eijebong FYI, this PR brings WR up to date in Servo. In case it doesn't land before your serde 1.0 changes are ready to go, you can use this as a base for the required WR API changes.

**Comment by emilio** [comment]
Looks good, though I'd expect some WebGL tests to fail... Let's see.

@bors-servo r+

**Comment by glennw** [comment]
@emilio Tests should be OK - it's just a rename of the format to match the actual layout. There's no actual byte ordering changes.

**Pull request merged**
