### PR TITLE
Compute attribute name atoms at compile-time.

### PR DESCRIPTION
**Pull request by eefriedman**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8703)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* #8616

**Comment by Ms2ger** [comment]
I'm not happy with this duplication at all; we have managed to have those go out of sync before.

**Comment by Swatinem** [comment]
With this change the to_upper and to_lower macros are unused and it might be a good idea to remove them completely?

**Pull request merged**
