### PR TITLE
Introduce nsStaticAtom.

### PR DESCRIPTION
**Pull request by nnethercote**
It's a sub-class of nsAtom, useful for cases where you know you are dealing
exclusively with static atoms. The nice thing about it is that you can use
raw nsStaticAtom pointers instead of RefPtr<>. (In fact, the AddRef/Release
implementations ensure that we'll crash if we use RefPtr<nsStaticAtom>.)

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix https://bugzilla.mozilla.org/show_bug.cgi?id=1411893

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because tested on the Gecko side.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19035)

### CODE REVIEW

**Review by emilio — APPROVED** [review]
* `impl From<*mut nsStaticAtom> for Atom` should re-use `Atom::from_static` (though not sure it's used).

* `as_static_ptr` seems unused.

Those two things fixed, then r=me

**Comment by nnethercote** [comment]
>   impl From<*mut nsStaticAtom> for Atom should re-use Atom::from_static (though not sure it's used).

True. (And it does have a use.)

>   as_static_ptr seems unused.

You're right, I will remove that.

**Pull request merged**
