### PR TITLE
ScriptTask::mouse_over_targets is not traced #4985

### PR DESCRIPTION
**Pull request by gurobokum**

### CODE REVIEW

**Comment by jdm** [comment]
Great! I've left a couple comments on Critic, but this looks like what I expected :)

**Comment by jdm** [comment]
```
/Users/servo/buildbot/slave/mac1/build/components/script/script_task.rs:113:1: 113:15 error: conflicting implementations for trait `dom::bindings::trace::JSTraceable` [E0119]
/Users/servo/buildbot/slave/mac1/build/components/script/script_task.rs:113 #[jstraceable]
                                                                            ^~~~~~~~~~~~~~
note: in expansion of #[jstraceable]
/Users/servo/buildbot/slave/mac1/build/components/script/script_task.rs:113:1: 113:15 note: expansion site
/Users/servo/buildbot/slave/mac1/build/components/script/dom/macros.rs:172:13: 177:14 note: note conflicting implementation here
/Users/servo/buildbot/slave/mac1/build/components/script/dom/macros.rs:172             impl JSTraceable for $ty {
/Users/servo/buildbot/slave/mac1/build/components/script/dom/macros.rs:173                 #[inline]
/Users/servo/buildbot/slave/mac1/build/components/script/dom/macros.rs:174                 fn trace(&self, _: *mut JSTracer) {
/Users/servo/buildbot/slave/mac1/build/components/script/dom/macros.rs:175                     // Do nothing
/Users/servo/buildbot/slave/mac1/build/components/script/dom/macros.rs:176                 }
/Users/servo/buildbot/slave/mac1/build/components/script/dom/macros.rs:177             }
/Users/servo/buildbot/slave/mac1/build/components/script/dom/macros.rs:169:1: 188:3 note: in expansion of no_jsmanaged_fields!
/Users/servo/buildbot/slave/mac1/build/components/script/script_task.rs:129:1: 129:38 note: expansion site
error: aborting due to previous error
```

**Comment by jdm** [comment]
Looks like you forgot to take out the `no_jsmanaged_fields` line :)

**Comment by JIoJIaJIu** [comment]
My bad(

**Pull request closed without merging**
