### PR TITLE
Use raw handles to create surfman contexts

### PR DESCRIPTION
**Pull request by wusyong**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it only changes how winit port create surfman contexts.

It's amazing to see many activities on Servo recently. I would like to look into building it as a library crate again.
But I think it's best I could start something small to prevent getting stuck.
I hope it can accept any kind of window libraries and frameworks, with something like winit as fallback.
There will be people using various tools like gtk, UI kit, glazier (window crate from druid community).
Exposing API to accept raw window and display handle should do the work.
And I think this can start with chaning internal use first.
However, `Connection::from_raw_display_handle` isn't included in version 0.6, so I have to patch it.
Could it release another version for this?

### CODE REVIEW

**Comment by jdm** [comment]
I have published surfman 0.7.0.

**Comment by wusyong** [comment]
Thanks for updating it. I think webxr also need to update the dependencies.
But since servo use it from git, it doesn't need to publish anytime soon.
I opened a PR there: https://github.com/servo/webxr/pull/204

**Comment by wusyong** [comment]
It looks like the `sm-raw-window-handle` feature implementation in surfman isn't correct on Windows.
I opened a PR there: https://github.com/servo/surfman/pull/253

**Comment by CYBAI** [comment]
Windows build failed and wait for https://github.com/servo/surfman/pull/253.

**Comment by jdm** [comment]
Interesting; the windows smoke test failed.

**Comment by wusyong** [comment]
Sorry I'm still triaging issues when I build servo on Windows.
Could bors try the CI with temprory patch commit I just pushed?
I'll revert it once this can be passed.

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
I rebased this and pushed a few minor style fixes. I'll send it to the MQ.

**Comment by mrobinson** [comment]
This is failing the Windows smoketest:

```
Failed to create native widget: UnsupportedOnThisPlatform (thread main, at ports\winit\headed_window.rs:136)
   0: servo::backtrace::print
   1: core::fmt::write
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\core\src\fmt\mod.rs:1232
   2: std::io::Write::write_fmt
   3: servo::backtrace::print
   4: webxr_api::registry::MainThreadRegistry<GL>::register
   5: alloc::boxed::impl$47::call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\alloc\src\boxed.rs:2002
   6: std::panicking::rust_panic_with_hook
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\panicking.rs:692
   7: std::panicking::begin_panic_handler::closure$0
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\panicking.rs:579
   8: std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\sys_common\backtrace.rs:137
   9: std::panicking::begin_panic_handler
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\panicking.rs:575
  10: core::panicking::panic_fmt
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\core\src\panicking.rs:64
  11: core::result::unwrap_failed
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\core\src\result.rs:1790
  12: servo::app::App::run
  13: webxr_api::registry::MainThreadRegistry<GL>::register
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: std::rt::lang_start::{{closure}}
  16: core::ops::function::impls::impl$2::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\core\src\ops\function.rs:287
  17: std::panicking::try::do_call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\panicking.rs:483
  18: std::panicking::try
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\panicking.rs:447
  19: std::panic::catch_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\panic.rs:140
  20: std::rt::lang_start_internal::closure$2
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\rt.rs:148
  21: std::panicking::try::do_call
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\panicking.rs:483
  22: std::panicking::try
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\panicking.rs:447
  23: std::panic::catch_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\panic.rs:140
  24: std::rt::lang_start_internal
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library\std\src\rt.rs:148
  25: main
  26: invoke_main
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  27: __scrt_common_main_seh
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  28: BaseThreadInitThunk
  29: RtlUserThreadStart
Servo exited with non-zero status 101
Error: Process completed with exit code 1.
```

**Comment by wusyong** [comment]
@mrobinson Sorry I forgot to update status of this PR, because I'm still busing moving house.
We need surfman to publish another patch version to merge this PR.
The [fix](https://github.com/servo/surfman/commit/28f9cc417d5413ef6125f865d6f1937fd0b7a64f) for that error hasn't been published yet

**Comment by mrobinson** [comment]
@wusyong Thanks for the heads up. I've published a new version of surfman and updated this PR.

**Pull request merged**
