### PR TITLE
Removed sources of panic from piepline.rs.

### LINKED ISSUE #10422: Harden pipeline.rs
The constellation directly calls code in pipeline.rs, which can panic:
```
  ▶ TIMEOUT [expected OK] /dom/nodes/CharacterData-deleteData.html
  │ 
  │ thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }', ../src/libcore/result.rs:746
  │ stack backtrace:
  │ thread 'http_loader for http://web-platform.test:8000/resources/testharness.js' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }', ../src/libcore/result.rs:746
  │    1:     0x56301aff2140 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
  │    2:     0x56301aff708f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
  │    3:     0x56301aff6d08 - panicking::default_handler::h4e73712d1e927dfeH0z
  │    4:     0x56301afe0aac - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
  │    5:     0x56301afe1a58 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
  │    6:     0x56301aff1441 - rust_begin_unwind
  │    7:     0x56301b02ea8f - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
  │    8:     0x56301a01b76e - result::unwrap_failed::h4728466288999790990
  │    9:     0x56301a02ef23 - pipeline::Pipeline::force_exit::h3bf41af4342939b3mNg
  │   10:     0x56301947effc - constellation::Constellation<LTF, STF>::close_pipeline::h13839808115884682247
  │   11:     0x56301947e2e0 - constellation::Constellation<LTF, STF>::handle_failure_msg::h4514637126930078128
  │   12:     0x563019447d3a - constellation::Constellation<LTF, STF>::handle_request::h15438543091044643319
  │   13:     0x56301943b6dc - sys_common::unwind::try::try_fn::h14027539136705566302
  │   14:     0x56301aff13cb - __rust_try
  │   15:     0x56301aff135d - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  │   16:     0x56301943cb9a - boxed::F.FnBox<A>::call_box::h9531561132886985394
  │   17:     0x56301aff5659 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  │   18:     0x7f671a7096a9 - start_thread
  │   19:     0x7f671a227e9c - clone
  │   20:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by asajeffrey**
Fixes #10422.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10423)

### CODE REVIEW

**Comment by emilio** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/compositing/pipeline.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10423#-KEc58ygKIBL8yL0Enip:-KEc58ygKIBL8yL0Eniq:1472033058) ([raw file](https://github.com/servo/servo/blob/643f1b62c8e5e186104e3b02bba7a188c355b16a/components/compositing/pipeline.rs#L135)):*
nit: "Pipeline layout"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10423)*

**Comment by asajeffrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/compositing/pipeline.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10423#-KEc58ygKIBL8yL0Enip:-KEcNlOiB3kZWM8aqaNw:-499146009) ([raw file](https://github.com/servo/servo/blob/643f1b62c8e5e186104e3b02bba7a188c355b16a/components/compositing/pipeline.rs#L135)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10423)*

**Comment by jdm** [comment]
@bors-servo: r-
I'd prefer to see this squashed first.

**Comment by Wafflespeanut** [comment]
Oops, sorry, didn't notice :)

**Comment by asajeffrey** [comment]
Squashed.

**Comment by asajeffrey** [comment]
@bors-servo: retry
* #10457

**Pull request merged**
