### PR TITLE
Clean up dependencies.

### PR DESCRIPTION
**Pull request by metajack**
Overlaps a bunch with #6288. Putting this here so @frewsxcv can take a look and we can figure out how to merge our work together.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6295)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Doesn't make a difference to me really which one we use. Merge conflicts aside, I think we can just go with yours, unless you see any reason to use mine

**Comment by metajack** [comment]
Before this lands, we need https://github.com/ecoal95/rust-offscreen-rendering-context/pull/9 and cargo.lock updates.

**Comment by metajack** [comment]
@frewsxcv Ok, I think I incorporated everything from your branch into my changes. Can you look this over?

**Comment by frewsxcv** [comment]
Everything looks good to me :shipit:

**Comment by metajack** [comment]
Ok, offscreen_gl_context changes are in. This is ready to go.

**Comment by metajack** [comment]
@bors-servo: r=frewsxcv,metajack

Putting my name in as self review only because @frewsxcv isn't yet on bors' list.

**Comment by frewsxcv** [comment]
I opened an issue for that fail: https://github.com/aweinstock314/rust-clipboard/issues/4

**Comment by metajack** [comment]
Wonderful. That bug is my fault.

**Comment by frewsxcv** [comment]
This can get retried now that https://github.com/aweinstock314/rust-clipboard/issues/4 has been fixed

**Comment by metajack** [comment]
Only change was updating clipboard to the latest version which fixes the linux build error.

**Comment by frewsxcv** [comment]
:shipit:

**Comment by frewsxcv** [comment]
Merge conflicts FYI

**Comment by metajack** [comment]
Updated layers.

**Comment by metajack** [comment]
This needs https://github.com/servo/rust-layers/pull/171

**Comment by metajack** [comment]
@bors-servo: r=frewsxcv

servo/rust-layers#171 landed and I've updated the Cargo.locks.

**Pull request merged**
