### PR TITLE
Make textarea scrollable

### LINKED ISSUE #10058: textarea - no scrolling on rows overflow
if the textarea overflows in rows, there's also no scrolling.

textarea problem2

code to reproduce:

```html
<textarea cols="20" rows="5">This
is
a
sentence
that
is
more
than
5
rows,
showing
this
is
a
real                                           
problem.</textarea>       
```

### PR DESCRIPTION
**Pull request by kilobtye**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #10058 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12364)

### CODE REVIEW

**Comment by kilobtye** [comment]
Textarea still does not scroll if it is clicked(insertion point is shown) without -w.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by kilobtye** [comment]
Seems changing \<input\> from overflow:hidden to overflow:auto makes the tests fail.

transform-input-001.htm:
screenshot from 2016-07-13 20-00-19
ref:
screenshot from 2016-07-13 19-54-55

Should I make the change apply to \<textarea\> only? Any suggestions, @jdm ?

**Comment by jdm** [comment]
Yes, let's do that and file a new issue about fixing the problem with for input elements too.

**Pull request merged**
