### PR TITLE
Add 'appearance' property to Stylo (with '-webkit-appearance' alias) (take 2)

### PR DESCRIPTION
**Pull request by bholley**
Replacement for #16110.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16112)

### CODE REVIEW

**Comment by jdm** [comment]
`./components/style/properties/longhand/box.mako.rs:2020: Line is longer than 120 characters`

**Comment by bholley** [comment]
tiddddyyyy

@bors-servo r=Manishearth

**Comment by bholley** [comment]
#14323

**Pull request merged**
