### PR TITLE
preflight_fetch steps comments out of date with spec #8941

### LINKED ISSUE #8941: preflight_fetch steps comments out of date with spec
https://github.com/servo/servo/blob/d6708a2fea41f3078b33e1297a29aac192f5765d/components/script/cors.rs#L180-L181

Busy right now so I can't go too specific, but the steps in the code don't seem to match the spec

### PR DESCRIPTION
**Pull request by jinwooahn**
Fix comments. Resolves #8941

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8967)

### CODE REVIEW

**Comment by jdm** [comment]
Thank you for doing this work!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/cors.rs, line 201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8967#-K5VtRpSbJJIpa3zV5sv:-K5VtRpSbJJIpa3zV5sw:-1189703087) ([raw file](https://github.com/servo/servo/blob/f2f5e7c87b76bd0a73b46b6db9a9dac66d933482/components/script/cors.rs#L201)):*
This comment isn't correct; the line starting with `let response = match stream.send()` is our implementation of step 6.

---

*[components/script/cors.rs, line 204 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8967#-K5VuDuk6fDCxYAJblHf:-K5VuDuk6fDCxYAJblHg:1439668126) ([raw file](https://github.com/servo/servo/blob/f2f5e7c87b76bd0a73b46b6db9a9dac66d933482/components/script/cors.rs#L204)):*
Let's move these comments above `match response.status.class()`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8967#-:-K5VuMuGwN2QsuVRuMue:-86824970)*

**Comment by jinwooahn** [comment]
Thank you for review!

**Comment by jdm** [comment]
Great! Please squash these commits and I'll merge them!
-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8967#-:-K5Yp8mW37FBlg4vruc-:1472971367)*

**Comment by frewsxcv** [comment]
@jinwooahn I'm sorry for opening and closing so many times! Our bot that watches GitHub comments (@bors-servo) has been having some issues lately and gets stuck sometimes. Unfortunately, it's getting stuck on this pull request, and in order to keep the build queue moving, I have to reopen this pull request. You might have luck doing `git commit --amend; git push --force` to get a new git commit hash for these changes and seeing if that remedies this issue

**Comment by jinwooahn** [comment]
Thank you

**Pull request merged**
