### PR TITLE
Fix CSSStyleDeclaration::setPropertyPriority and some refactoring

### PR DESCRIPTION
**Pull request by SimonSapin**
r? @Ms2ger

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6741)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 4 of 4 files at r3, 4 of 4 files at r4.
Review status: 4 of 9 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 80 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOJNI9Pi1o8nxxMgnn)** ([raw file](https://github.com/servo/servo/blob/2bb26752d01b320046108b48710cdee2de1241f2/components/script/dom/cssstyledeclaration.rs#L80)):</sup>
… so this didn't work out?

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 81 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOIOpqhCKWNBdWzRyP)** ([raw file](https://github.com/servo/servo/blob/2862d6e67327de38f696cffaa4457327fcb01618/components/script/dom/cssstyledeclaration.rs#L81)):</sup>
We prefer implementing for `&T` (or `T`, perhaps).

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 81 \[r5\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOQvYYBEhZJ1J3QPl2)** ([raw file](https://github.com/servo/servo/blob/9b3f7ce96ef61afb1caf2b9cc53f1d810e1d5760/components/script/dom/cssstyledeclaration.rs#L81)):</sup>
Seriously?

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 160 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOIbEenE9xBd_adgWc)** ([raw file](https://github.com/servo/servo/blob/2862d6e67327de38f696cffaa4457327fcb01618/components/script/dom/cssstyledeclaration.rs#L160)):</sup>
Why the `result` local?

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 235 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOIhnfzRU8-mEhB6Gf)** ([raw file](https://github.com/servo/servo/blob/2862d6e67327de38f696cffaa4457327fcb01618/components/script/dom/cssstyledeclaration.rs#L235)):</sup>
I guess modern Rust would drop the `.into_iter()` entirely.

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 271 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOHIrXQn27jJwncpXo)** ([raw file](https://github.com/servo/servo/blob/3fc40a24f5e4d33b926b48cc1926917c2c6592cb/components/script/dom/cssstyledeclaration.rs#L271)):</sup>
Can you find someone who knows this code?

---

<sup>**[components/style/build.rs, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOEgM3-BflJI-XTEsR)** ([raw file](https://github.com/servo/servo/blob/a40de7015088bae0b5ff496fddbfd19fe522117b/components/style/build.rs#L26)):</sup>
One import per line

---

<sup>**[components/style/properties.mako.rs, line 6186 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOGNw573JtIE10Hb2x)** ([raw file](https://github.com/servo/servo/blob/3fc40a24f5e4d33b926b48cc1926917c2c6592cb/components/style/properties.mako.rs#L6186)):</sup>
Spurious space after `<`

---

<sup>**[tests/ref/basic.list, line 280 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOGbEwxS5ujzbuQT8K)** ([raw file](https://github.com/servo/servo/blob/3fc40a24f5e4d33b926b48cc1926917c2c6592cb/tests/ref/basic.list#L280)):</sup>
I'd really rather you added this under `tests/wpt/mozilla/tests/css/`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6741)

**Comment by SimonSapin** [comment]
Review status: 4 of 9 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 81 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOIOpqhCKWNBdWzRyP)** ([raw file](https://github.com/servo/servo/blob/2862d6e67327de38f696cffaa4457327fcb01618/components/script/dom/cssstyledeclaration.rs#L81)):</sup>
Done.

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 81 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOJNI9Pi1o8nxxMgnn)** ([raw file](https://github.com/servo/servo/blob/2bb26752d01b320046108b48710cdee2de1241f2/components/script/dom/cssstyledeclaration.rs#L81)):</sup>
This was a messed up cherry-pick. I rewrote the whole branch to clean this up.

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 160 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOIbEenE9xBd_adgWc)** ([raw file](https://github.com/servo/servo/blob/2862d6e67327de38f696cffaa4457327fcb01618/components/script/dom/cssstyledeclaration.rs#L160)):</sup>
To work around dropck being too conservative. https://github.com/rust-lang/rust/issues/22252 I’v added a FIXME comment.

---

<sup>**[components/script/dom/cssstyledeclaration.rs, line 234 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOIhnfzRU8-mEhB6Gf)** ([raw file](https://github.com/servo/servo/blob/2862d6e67327de38f696cffaa4457327fcb01618/components/script/dom/cssstyledeclaration.rs#L234)):</sup>
Done

---

<sup>**[components/style/build.rs, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOEgM3-BflJI-XTEsR)** ([raw file](https://github.com/servo/servo/blob/a40de7015088bae0b5ff496fddbfd19fe522117b/components/style/build.rs#L26)):</sup>
Done.

---

<sup>**[components/style/properties.mako.rs, line 6194 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOGNw573JtIE10Hb2x)** ([raw file](https://github.com/servo/servo/blob/3fc40a24f5e4d33b926b48cc1926917c2c6592cb/components/style/properties.mako.rs#L6194)):</sup>
This space works around what seems to be a Mako bug. I’ve added a comment.

---

<sup>**[tests/ref/basic.list, line 280 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6741#-JvOGbEwxS5ujzbuQT8K)** ([raw file](https://github.com/servo/servo/blob/3fc40a24f5e4d33b926b48cc1926917c2c6592cb/tests/ref/basic.list#L280)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6741)

**Comment by SimonSapin** [comment]
I had done something wrong when cherry-picking commits before submitting this PR, so I rebased/squashed/cherry-picked/massaged the whole thing again.

r?

**Comment by metajack** [comment]
@ms2ger ping

**Comment by SimonSapin** [comment]
Rebased.

**Comment by Ms2ger** [comment]
Reviewed 4 of 4 files at r5, 2 of 2 files at r6, 12 of 12 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6741)

**Comment by Ms2ger** [comment]
@pcwalton or @jdm do either of you feel comfortable reviewing the interaction with style?

**Comment by jdm** [comment]
I could if necessary and with some time spent re-acquainting myself with the code.

**Comment by SimonSapin** [comment]
Rebased.

**Comment by SimonSapin** [comment]
I didn’t remember why `PartialEq` was derived on stylesheets. Turns out, it was for unit tests. Carrying @pcwalton’s r+ to the same branch with the last commit removed, reproduced below for posterity.

@bors-servo r=pcwalton 06ba62b

```diff
commit 0b3e3bc3e9477e617ba784c4bb9e5b32482d0d04
Author: Simon Sapin <simon.sapin@exyr.org>
Date:   Sat Jul 25 00:43:27 2015 +0200

    Remove PartialEq from CSS stylesheets, rules, and declarations.
    
    We shouldn’t be doing deep comparison of such large objects.

diff --git a/components/style/properties.mako.rs b/components/style/properties.mako.rs
index 5d15cd1..8b2d635 100644
--- a/components/style/properties.mako.rs
+++ b/components/style/properties.mako.rs
@@ -5522,7 +5522,7 @@ mod property_bit_field {
 
 /// Declarations are stored in reverse order.
 /// Overridden declarations are skipped.
-#[derive(Debug, PartialEq)]
+#[derive(Debug)]
 pub struct PropertyDeclarationBlock {
     pub important: Arc<Vec<PropertyDeclaration>>,
     pub normal: Arc<Vec<PropertyDeclaration>>,
@@ -5669,7 +5669,6 @@ impl<T: ToCss> DeclaredValue<T> {
     }
 }
 
-#[derive(PartialEq)]
 pub enum PropertyDeclaration {
     % for property in LONGHANDS:
         ${property.camel_case}(DeclaredValue<longhands::${property.ident}::SpecifiedValue>),
diff --git a/components/style/stylesheets.rs b/components/style/stylesheets.rs
index 3093f8e..d77980d 100644
--- a/components/style/stylesheets.rs
+++ b/components/style/stylesheets.rs
@@ -38,7 +38,7 @@ pub enum Origin {
 }
 
 
-#[derive(Debug, PartialEq)]
+#[derive(Debug)]
 pub struct Stylesheet {
     /// List of rules in the order they were found (important for
     /// cascading order)
@@ -47,7 +47,7 @@ pub struct Stylesheet {
 }
 
 
-#[derive(Debug, PartialEq)]
+#[derive(Debug)]
 pub enum CSSRule {
     Charset(String),
     Namespace(Option<String>, Namespace),
@@ -57,7 +57,7 @@ pub enum CSSRule {
     Viewport(ViewportRule),
 }
 
-#[derive(Debug, PartialEq)]
+#[derive(Debug)]
 pub struct MediaRule {
     pub media_queries: MediaQueryList,
     pub rules: Vec<CSSRule>,
@@ -70,7 +70,7 @@ impl MediaRule {
     }
 }
 
-#[derive(Debug, PartialEq)]
+#[derive(Debug)]
 pub struct StyleRule {
     pub selectors: Vec<Selector>,
     pub declarations: PropertyDeclarationBlock,
```

**Comment by SimonSapin** [comment]
@bors-servo retry

```
/css21_dev/html4/z-index-012.htm
--------------------------------
TIMEOUT expected FAIL [Parent]
```
https://github.com/servo/servo/issues/6892

**Pull request merged**
