### PR TITLE
Merge generic funs to share them across all bindings (fixes #2684)

### LINKED ISSUE #2684: Consider merging the generic getters/setters/methods
Gecko did this in <https://bugzilla.mozilla.org/show_bug.cgi?id=956806> for a nice codesize win; it's probably worth investigating if it would be a win for us too.

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6223)

### CODE REVIEW

**Comment by nox** [comment]
I am pretty sure GetProtoObject() can be shared too.

**Comment by jdm** [comment]
I'd like to hold off on merging these changes until after #6150.

**Comment by nox** [comment]
Why? Don't you want to review again 175 files after I bitrot them? Agreed. :)

**Comment by metajack** [comment]
Assigning to @ms2ger since @jdm will be out by the time #6150 lands.

**Comment by nox** [comment]
@Ms2ger Split as requested.

**Comment by Ms2ger** [comment]
Please rebase on master.

**Comment by nox** [comment]
@michaelwu r?

**Comment by Ms2ger** [comment]
Reviewed 2 of 2 files at r1, 3 of 4 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 2699 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6223#-JsGQXy9gaxEEDtq326j)** ([raw file](https://github.com/servo/servo/blob/9f753563a58e6755bf26a99c62a64e8ac1c0459f/components/script/dom/bindings/codegen/CodegenRust.py#L2699)):</sup>
We should be able to kill this now.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4586 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6223#-JsGQvQoEgYcS1_Fu9Uv)** ([raw file](https://github.com/servo/servo/blob/9f753563a58e6755bf26a99c62a64e8ac1c0459f/components/script/dom/bindings/codegen/CodegenRust.py#L4586)):</sup>
Remove those too?

---

<sup>**[components/script/dom/bindings/conversions.rs, line 575 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6223#-JsGRerXJNlaVETDsfTD)** ([raw file](https://github.com/servo/servo/blob/9f753563a58e6755bf26a99c62a64e8ac1c0459f/components/script/dom/bindings/conversions.rs#L575)):</sup>
How does this not break proxy objects?

---

<sup>**[components/script/dom/bindings/conversions.rs, line 589 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6223#-JsGRnH-BfMp-_5b1ut5)** ([raw file](https://github.com/servo/servo/blob/9f753563a58e6755bf26a99c62a64e8ac1c0459f/components/script/dom/bindings/conversions.rs#L589)):</sup>
Why mut obj?

---

<sup>**[components/script/dom/bindings/utils.rs, line 694 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6223#-JsGR8w6Jz8W6bJzGyIk)** ([raw file](https://github.com/servo/servo/blob/9f753563a58e6755bf26a99c62a64e8ac1c0459f/components/script/dom/bindings/utils.rs#L694)):</sup>
There's a bunch of duplicated code in all those; could you share some more?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6223)

**Comment by Ms2ger** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/bindings/utils.rs, line 678 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6223#-JsRU43hI3cZIh0SKT-y)** ([raw file](https://github.com/servo/servo/blob/0dbcda480067dbb744dd299bbfface52f27779a5/components/script/dom/bindings/utils.rs#L678)):</sup>
Perhaps `get_this()`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6223)

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6223)

**Comment by michaelwu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/bindings/utils.rs, line 691 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6223#-JsOgUgHo4U--THNBsul)** ([raw file](https://github.com/servo/servo/blob/0dbcda480067dbb744dd299bbfface52f27779a5/components/script/dom/bindings/utils.rs#L691)):</sup>
I usually wouldn't expect this to work. The rooters for GC things (`Rooted<T>`) usually can't be moved, so returning them is generally a bad idea unless that's the only thing you're returning and you use the special constructor that allows for this - `Rooted::new_with_addr`. If the assertion at https://github.com/servo/rust-mozjs/blob/master/src/rust.rs#L286 doesn't catch it though.. it's probably ok. The callers might be moving it to the right place if it works.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6223)

**Comment by nox** [comment]
@Ms2ger Your turn again!

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6223)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6223)

**Pull request merged**
