### PR TITLE
ci: Sign off commits by WPT importer

### PR DESCRIPTION
**Pull request by mrobinson**
This will be important to enforce signing off commits in the project.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they only change CI behavior.

### CODE REVIEW

**Comment by jschwe** [comment]
Is the person behind `josh+wptsync@joshmatthews.net` still affiliated with servo? Perhaps we can get a more bot-like email, perhaps pointing to the noreply github email address of the bot?

**Comment by mrobinson** [comment]
Oh, excellent question. We should likely update the address for this GitHub account perhaps to refer to a servo.org address. @jdm @mrego Do you see any issues with this? I assume we'd just use a new address like wpt@servo.org that would forward to the same mailbox as the other servo.org addresses.

**Comment by mukilan** [comment]
We have @servo-bot that we already use for dependabot PR approvals and nightly releases. We could use that for import as well.  @servo-bot uses the email 'ghbot@servo.org' which forwards to infra at servo.org. We also have support for using `ghbot+<tag>@servo.org` if we need to just switch @servo-wpt-sync's email.

**Review by mukilan — APPROVED** [review]

**Comment by jdm** [comment]
No concerns with updating the email, but we should update the email of the GitHub account as well.

**Pull request merged**
