### PR TITLE
More cleanup of the servo entry points

### PR DESCRIPTION
**Pull request by brson**
Just cleanup.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6010)

### CODE REVIEW

**Comment by pcwalton** [comment]
Looks good to me, but maybe @michaelwu should take a look too.

**Comment by michaelwu** [comment]
Don't worry about the gonk port - it's too late for that. The port was broken when webgl was landed. If I need that file back I can just restore it when I get back to fixing that port.

**Comment by pcwalton** [comment]
Looks good then, feel free to squash.

**Pull request merged**
