### PR TITLE
Update RemoveIFrame to use pipeline id rather than subpage.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7921)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/htmliframeelement.rs, line 438 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7921#-K04VSx4vbstW4o2cQd4)** ([raw file](https://github.com/servo/servo/blob/69cb9634b48c932af1f7eb884ea4761f1141abed/components/script/dom/htmliframeelement.rs#L438)):</sup>
We should clear the pipeline here too, right?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7921)

**Comment by glennw** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/htmliframeelement.rs, line 438 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7921#-K04VSx4vbstW4o2cQd4)** ([raw file](https://github.com/servo/servo/blob/69cb9634b48c932af1f7eb884ea4761f1141abed/components/script/dom/htmliframeelement.rs#L438)):</sup>
It's not actually needed (yet) since none of the constellation logic has been updated to make use of the pipeline id here yet - but I've added it anyway, so it's not forgotten in follow up PRs.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7921)

**Comment by jdm** [comment]
Squash this last commit with the previous, please.
-S-awaiting-review +S-needs-squash 


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7921)

**Comment by jdm** [comment]
@bors-servo: retry
* #7931

**Comment by jdm** [comment]
Rebase error?
```
/home/servo/buildbot/slave/gonk/build/components/script/dom/htmliframeelement.rs:434:41: 434:54 error: no method named `pipeline_id` found for type `&dom::htmliframeelement::HTMLIFrameElement` in the current scope
/home/servo/buildbot/slave/gonk/build/components/script/dom/htmliframeelement.rs:434         if let Some(pipeline_id) = self.pipeline_id() {
                                                                                                                             ^~~~~~~~~~~~~
/home/servo/buildbot/slave/gonk/build/components/script/dom/htmliframeelement.rs:434:9: 449:10 note: in this expansion of if let expansion
/home/servo/buildbot/slave/gonk/build/components/script/dom/htmliframeelement.rs:434:41: 434:54 help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `pipeline_id`, perhaps you need to implement it:
/home/servo/buildbot/slave/gonk/build/components/script/dom/htmliframeelement.rs:434:41: 434:54 help: candidate #1: `dom::htmliframeelement::HTMLIFrameElementLayoutMethods`
```

**Comment by jdm** [comment]
Oh, this was bitrotted by #7925 :P

**Comment by glennw** [comment]
unbitrotted

**Comment by jdm** [comment]
-S-needs-rebase -S-awaiting-review +S-awaiting-answer 


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/htmliframeelement.rs, line 439 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7921#-K0PEWv-r_DArnvrqad3)** ([raw file](https://github.com/servo/servo/blob/f4c323877c6cc451f960a25b0b3d08acbea7e4ff/components/script/dom/htmliframeelement.rs#L439)):</sup>
Why undo this change?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7921)

**Comment by glennw** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/htmliframeelement.rs, line 439 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7921#-K0PEWv-r_DArnvrqad3)** ([raw file](https://github.com/servo/servo/blob/f4c323877c6cc451f960a25b0b3d08acbea7e4ff/components/script/dom/htmliframeelement.rs#L439)):</sup>
A rebase mistake - good catch!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7921)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-answer 


---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7921)

**Comment by Ms2ger** [comment]
@bors-servo retry
* #7870

**Comment by Ms2ger** [comment]
@bors-servo retry
* #7787

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Pull request merged**
