### PR TITLE
Update Rust to 1.10.0-nightly (cd6a40017 2016-05-16)

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11231)

### CODE REVIEW

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/985086501a721fa90c7b3591fb60849557ff7256/components/script/dom/dedicatedworkerglobalscope.rs#L238, j'accuse!

**Comment by nox** [comment]
@jdm Do you mean that you don't think it's an intermittent failure?

**Comment by nox** [comment]
Arguably, CRASH is better than TIMEOUT anyway. :P

**Comment by nox** [comment]
Restarted that build to see if it fails again: http://build.servo.org/builders/mac-rel-wpt/builds/1061

**Comment by nox** [comment]
The failure was #11234.

**Pull request merged**
