### PR TITLE
Update to rustc 1.25.0-nightly (bacb5c58d 2018-01-26)

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20454)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/getBoundingClientRect.html:
  │ FAIL [expected PASS] Untitled 1
  │   → assert_equals: expected 62 but got 60.35
  │ 
  │ test_rect@http://web-platform.test:8000/_mozilla/mozilla/getBoundingClientRect.html:59:7
  │ @http://web-platform.test:8000/_mozilla/mozilla/getBoundingClientRect.html:86:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1494:20
  │ test@http://web-platform.test:8000/resources/testharness.js:511:9
  └ @http://web-platform.test:8000/_mozilla/mozilla/getBoundingClientRect.html:82:5

**Comment by SimonSapin** [comment]
```

  ▶ CRASH [expected ERROR] /referrer-policy/unsafe-url/http-rp/cross-origin/http-https/img-tag/generic.swap-origin-redirect.http.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ called `Result::unwrap()` on an `Err` value: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) (thread main, at libcore/result.rs:945)
  │ ERROR 2018-03-29T13:46:01Z: script::dom::bindings::error: Error at :0:0 SecurityError: The operation is insecure.
  │ ERROR 2018-03-29T13:46:01Z: script::dom::bindings::error: Error at :0:0 SecurityError: The operation is insecure.
  │ ERROR 2018-03-29T13:46:01Z: script::dom::bindings::error: Error at :0:0 SecurityError: The operation is insecure.
  │ ERROR 2018-03-29T13:46:01Z: script::dom::bindings::error: Error at :0:0 SecurityError: The operation is insecure.
  │ ERROR 2018-03-29T13:46:01Z: script::dom::bindings::error: Error at :0:0 SecurityError: The operation is insecure.
  │ stack backtrace:
  │    0:     0x7f94461458cc - backtrace::backtrace::trace::heb9efa3021143bc0
  │    1:     0x7f9446144c52 - backtrace::capture::Backtrace::new::hd20e533c9c999e36
  │    2:     0x7f944314669c - servo::main::{{closure}}::h96f2fd035380f7d9
  │    3:     0x7f9446154465 - std::panicking::rust_panic_with_hook::h489260a27605eec3
  │                         at libstd/panicking.rs:577
  │    4:     0x7f944615427e - std::panicking::begin_panic::h76e4e10033758ab0
  │                         at libstd/panicking.rs:537
  │    5:     0x7f94461541ea - std::panicking::begin_panic_fmt::h89311252f4057b32
  │                         at libstd/panicking.rs:521
  │    6:     0x7f9446154182 - rust_begin_unwind
  │                         at libstd/panicking.rs:497
  │    7:     0x7f944618ad40 - core::panicking::panic_fmt::h742dc08d23c8d154
  │                         at libcore/panicking.rs:71
  │    8:     0x7f94458a9ced - core::result::unwrap_failed::he5b4c8ef88d0cfcf
  │    9:     0x7f94458968b9 - webrender_api::api::RenderApi::get_scroll_node_state::h0e7fc5ec325096a2
  │   10:     0x7f9443166d5a - <compositing::compositor::IOCompositor<Window>>::send_viewport_rects::h92f4b62c465645f2
  │   11:     0x7f9443168120 - _ZN60_$LT$compositing..compositor..IOCompositor$LT$Window$GT$$GT$22handle_browser_message17hd3068794eb6fe2a5E.llvm.91EDB212
  │   12:     0x7f94431657c7 - <compositing::compositor::IOCompositor<Window>>::receive_messages::hce9c94c6e243783d
  │   13:     0x7f944313672b - <servo::Servo<Window>>::handle_events::h5362d2967f3a7429
  │   14:     0x7f9443152453 - servo::main::{{closure}}::h4bcb822908160ac8
  │   15:     0x7f944314c4e8 - servo::glutin_app::window::Window::run::hc4dad2185b3d5142
  │   16:     0x7f944314580e - servo::main::h77e7a2d85e964b56
  │   17:     0x7f9443146a82 - std::rt::lang_start::{{closure}}::h17fcc6030673dc3b
  │   18:     0x7f94461540e7 - std::rt::lang_start_internal::{{closure}}::h3b2f04b904715533
  │                         at libstd/rt.rs:59
  │                          - std::panicking::try::do_call::h982938453be85532
  │                         at libstd/panicking.rs:479
  │   19:     0x7f944617dafe - __rust_maybe_catch_panic
  │                         at libpanic_unwind/lib.rs:102
  │   20:     0x7f94461613f3 - std::panicking::try::h0137c31626fca698
  │                         at libstd/panicking.rs:458
  │                          - std::panic::catch_unwind::hb39d856d498e31e1
  │                         at libstd/panic.rs:358
  │                          - std::rt::lang_start_internal::h3578ac5ff98f3d4e
  │                         at libstd/rt.rs:58
  │   21:     0x7f9443146943 - main
  │   22:     0x7f9440822f44 - __libc_start_main
  │   23:     0x7f9443103da3 - <unknown>
  │   24:                0x0 - <unknown>
  └ ERROR 2018-03-29T13:46:02Z: servo: called `Result::unwrap()` on an `Err` value: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })
```

**Comment by jdm** [comment]
@bors-servo: retry
* #13479

**Pull request merged**
