### PR TITLE
M1501: R​eport CSS errors to the devtools, both stored and live

### PR DESCRIPTION
**Pull request by GauriGNaik**
Define a new trait called ParseErrorReporter in
components/style_traits/lib.rs with an appropriate method to report an error, and add a error_reporter member to ParserContext that uses this

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8210)

### CODE REVIEW

**Comment by jdm** [comment]
Looks good! We just need to address these style issues reported by `./mach test-tidy`:
```
./components/style/parser.rs:21: Line is longer than 120 characters

./components/style/parser.rs:9: use statement is not in alphabetical order

	expected: style_traits::ParseErrorReporter

	found: stylesheets::Origin

./components/style/parser.rs:10: use statement is not in alphabetical order

	expected: stylesheets::Origin

	found: url::{Url, UrlParser}

./components/style/parser.rs:11: use statement is not in alphabetical order

	expected: url::{Url, UrlParser}

	found: style_traits::ParseErrorReporter

./components/style_traits/lib.rs:30: no newline at EOF
```

**Comment by jdm** [comment]
From test-tidy again: `./components/style/parser.rs:21: trailing whitespace`
However, more importantly, these don't appear to compile. Did you build them locally?

**Comment by GauriGNaik** [comment]
To build successfully, it requires changes to be made to properties.mako.rs, selector_matching.rs, stylesheets.rs and viewport.rs. I have made changes to these files but still the build fails due to properties.rs and properties.rs gets generated on building servo.

I have tried but I have not been able to figure out what other changes I need to make in order to build servo successfully.

**Comment by GauriGNaik** [comment]
Once, we are clear on how to proceed we will resolve the checkstyle errors thrown by ./mach test-tidy in the next commit.

**Comment by jdm** [comment]
I propose changes that should make it easier to build correctly:
* store a `Box<ParseErrorReporter + Send>` value in the struct
* take `Box<ParseErrorReporter + Send>` arguments everywhere necessary
There should be no need to add `<'a>` or `&'a` anywhere with these changes.

**Comment by jdm** [comment]
Please also use [git rebase](http://rypress.com/tutorials/git/rebasing) instead of merging changes from master, too. It results in much cleaner lists of commits.

**Comment by GauriGNaik** [comment]
Even after making the proposed changes, build fails because of properties.rs. Tried making changes to properties.rs according to the errors it throws. Managed to eliminate some of the errors. But it is getting too complicated to make changes to properties.rs. Could you please suggest some way out of this problem so that we can build servo successfully ? Thank you for your help.

**Comment by eefriedman** [comment]
Could you rebase and push what you currently have?  It's hard to help without being able to read your current code.

**Comment by jdm** [comment]
According to the TravisCI link, many of the remaining errors are of the form "function expected 4 arguments, got 3" (which I presume has to do with need to pass the new error reporter value). If you correct that issue, I would expect the rest of the errors to disappear.

**Comment by GauriGNaik** [comment]
Yes correct, most of the errors are of that form and all the errors are in properties.rs. However, when I make those changes and do (./mach build --dev), initially I was able to reduce the number of errors. However, now when I build servo again, I lost the changes that I made to properties.rs and I am again back to the same number of errors I was facing earlier.

**Comment by eefriedman** [comment]
properties.rs is generated; you should be able to make equivalent changes to properties.mako.rs.

**Comment by GauriGNaik** [comment]
Thank you very much for the information. I knew that properties.rs was getting generated when servo is built but did not know where to make changes to be able to modify it.

**Comment by jdm** [comment]
Good start! There are a couple places we can be more efficient, but these are basically the changes that I was expecting :)
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[components/layout/css/matching.rs, line 458 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2giQ6z95x4FNLHebFz)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/layout/css/matching.rs#L458)):</sup>
Let's add a field to SharedLayoutContext instead and use that.


---

<sup>**[components/layout/layout_task.rs, line 242 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2giawjbPq7UeReuyyE)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/layout/layout_task.rs#L242)):</sup>
Add documentation like "The CSS error reporter for all CSS loaded in this layout thread."


---

<sup>**[components/layout/layout_task.rs, line 772 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2giwWw1pb8_OtJoHBY)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/layout/layout_task.rs#L772)):</sup>
This should be `self.error_reporter.clone()` instead of creating a new value in this method.


---

<sup>**[components/layout/layout_task.rs, line 822 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2gj1MIPwzX0na-NmBz)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/layout/layout_task.rs#L822)):</sup>
`self.error_reporter.clone()`


---

<sup>**[components/script/dom/element.rs, line 1498 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2gjDti1L9HCARCVXZ-)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/script/dom/element.rs#L1498)):</sup>
This could move right above the `parse_style_attribute` call.


---

<sup>**[components/script/dom/window.rs, line 1291 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2gjXf9yJUwUyJzU1Z1)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/script/dom/window.rs#L1291)):</sup>
We should store a member in `Window` and clone that instead.


---

<sup>**[components/script/reporter.rs, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2gjh0syt1VOzKRlOlU)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/script/reporter.rs#L13)):</sup>
nit: indent this by two extra spaces.


---

<sup>**[components/script/reporter.rs, line 16 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2gjjB8RqvG7gP9wP7A)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/script/reporter.rs#L16)):</sup>
nit: indent this block by four spaces beyond the `if`. 


---

<sup>**[components/script/reporter.rs, line 20 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2gjpx6xYFhkonngWio)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/script/reporter.rs#L20)):</sup>
This can be `box CSSErrorResporter`.


---

<sup>**[components/script/reporter.rs, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2gju5Oow-ZYr60yYsW)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/script/reporter.rs#L21)):</sup>
nit: indent both lines by two extra spaces.


---

<sup>**[components/servo/Cargo.lock, line 1558 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2gjzW6pqmrO_QpZalp)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/components/servo/Cargo.lock#L1558)):</sup>
Run `./mach update-cargo -p style_traits` to ensure that the other two Cargo.lock files are also updated accordingly.


---

<sup>**[tests/unit/style/viewport.rs, line 284 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8210#-K2gkdvIP8SPWfPj1GKw)** ([raw file](https://github.com/servo/servo/blob/f8cda204d8b7a2bc379e3e964dc55007fec66d0c/tests/unit/style/viewport.rs#L284)):</sup>
This won't compile - `./mach test-unit tests/unit/style/viewport.rs`. I recommend making a really simple type in this file that implements the trait.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8210)

**Comment by jdm** [comment]
Very close! Only small changes left :)
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

<sup>**[components/layout/layout_task.rs, line 454 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31MAyuMmMwJG43P15v)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/components/layout/layout_task.rs#L454)):</sup>
Let's make this method take an argument instead of creating a new value here.


---

<sup>**[components/layout/layout_task.rs, line 472 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31MLggxTZlu5XbLsg7)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/components/layout/layout_task.rs#L472)):</sup>
The clone shouldn't be necessary here with the use of an argument.


---

<sup>**[tests/unit/style/media_queries.rs, line 15 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31NJXE2fngpOE9qdsL)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/media_queries.rs#L15)):</sup>
If we make this `pub` we can use it from the other tests.


---

<sup>**[tests/unit/style/media_queries.rs, line 17 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31Mxea02iUvzbvwpWS)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/media_queries.rs#L17)):</sup>
We can remove this and prefix the argument names with `_` to suppress the warnings.


---

<sup>**[tests/unit/style/media_queries.rs, line 20 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31MrK0AaDltZkZyOGT)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/media_queries.rs#L20)):</sup>
nit: unindent this by four spaces.


---

<sup>**[tests/unit/style/media_queries.rs, line 24 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31MsoKYbhIqKMnY9Qk)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/media_queries.rs#L24)):</sup>
nit: unindent this `}` by four spaces.


---

<sup>**[tests/unit/style/media_queries.rs, line 30 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31N4Axa0vi6Ek0o2Tx)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/media_queries.rs#L30)):</sup>
This can be `box error_reporter` instead.


---

<sup>**[tests/unit/style/media_queries.rs, line 42 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31N6sy1eDfSqYRJgpj)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/media_queries.rs#L42)):</sup>
Same here.


---

<sup>**[tests/unit/style/stylesheets.rs, line 16 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31NN2QFrpi6Oc6Aqph)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/stylesheets.rs#L16)):</sup>
Let's add `use media_queries::CSSErrorReporterTest` instead of duplicating this again.


---

<sup>**[tests/unit/style/viewport.rs, line 19 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31NYTmXuLB5C8oKYLq)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/viewport.rs#L19)):</sup>
Same as previous; add a `use` instead of duplicating this.


---

<sup>**[tests/unit/style/viewport.rs, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31NgrfobQwPuhxqstW)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/viewport.rs#L34)):</sup>
The clone isn't necessary here if we're using `.clone()` in all of the callers.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8210)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/layout/layout_task.rs, line 452 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8210#-K3FsuvZh-DqLOkuhYDS)** ([raw file](https://github.com/servo/servo/blob/5d4e79eae962b1041cc071ee2abd902548202051/components/layout/layout_task.rs#L452)):</sup>
Actually, looking more closely at these changes we don't need to take an argument here.


---

<sup>**[components/layout/layout_task.rs, line 471 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8210#-K3FtX1PhZh-HuXmUhjE)** ([raw file](https://github.com/servo/servo/blob/5d4e79eae962b1041cc071ee2abd902548202051/components/layout/layout_task.rs#L471)):</sup>
This can be self.error_reporter.clone().


---

<sup>**[tests/unit/style/stylesheets.rs, line 16 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8210#-K31NN2QFrpi6Oc6Aqph)** ([raw file](https://github.com/servo/servo/blob/ddc0843ce4f811e856a47e4661211e82baaaa51c/tests/unit/style/stylesheets.rs#L16)):</sup>
Pretty sure this is not a compile error (`./mach test-unit tests/unit/style/stylesheets.rs`) because of the duplicate name.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8210)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 
Great work! Please rebase these changes against master and squash them into a single commit so they can be merged!


---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8210)

**Comment by jdm** [comment]
This can almost merge, but the changes to `support/android-rs-glue` from the rebase need to be reverted - specifically, that directory no longer exists on master. The build from TravisCI should be successful for this to merge correctly. You can commit changes using `--amend` and force push to avoid creating extra commits at this point.

**Comment by jdm** [comment]
Looks like something went wrong with the rebase, since there are merge conflicts now and changes are included in the commit that are already present in master. I'm going to go ahead and perform the surgery necessary to get this to land, in the interest of expediency :)

**Comment by jdm** [comment]
Rebased in #8682.

**Pull request closed without merging**
