### PR TITLE
Fix ./mach test-tidy --faster issue

### PR DESCRIPTION
**Pull request by zakorgy**
issue number: #9778 
there is a comment at line 594, uncomment it to test with empty file list using --faster

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9925)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
We need to make a few changes before we can land this PR.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[python/tidy.py, line 56 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9925#-KCO_FkooLVpI4f1Eaas:-KCO_FkooLVpI4f1Eaat:-1429196309) ([raw file](https://github.com/servo/servo/blob/3266b29819fbf2d6b7c02f318c5a86cdb54469f1/python/tidy.py#L56)):*
Let's name it something like `is_iter_empty`. And, we shouldn't use `iter` as a name - it's a built-in function. Let's simply call it as `iterator`.

---

*[python/tidy.py, line 63 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9925#-KCOVror00UPGJRLrpCf:-KCOVrosLKbIg_kpc5_9:-193907492) ([raw file](https://github.com/servo/servo/blob/3266b29819fbf2d6b7c02f318c5a86cdb54469f1/python/tidy.py#L63)):*
I agree that there's no straightforward way to check an iterator, but since we already make use of `itertools.chain`, we could have something like,

```python
try:
    obj = iterator.next()
    return True, itertools.chain((obj,), iterator)
except StopIteration:
    return False, iterator
```

---

*[python/tidy.py, line 80 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9925#-KCO_6qNVycj-nPZIZ6t:-KCO_6qNVycj-nPZIZ6u:467530294) ([raw file](https://github.com/servo/servo/blob/3266b29819fbf2d6b7c02f318c5a86cdb54469f1/python/tidy.py#L80)):*
Let's remove all the indentation, and raise `StopIteration` if `has_element` is `False`.

---

*[python/tidy.py, line 548 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9925#-KCOZqwDYV2ksTK4Zl0t:-KCOZqwDYV2ksTK4Zl0u:532203993) ([raw file](https://github.com/servo/servo/blob/3266b29819fbf2d6b7c02f318c5a86cdb54469f1/python/tidy.py#L548)):*
We should check the iterator's "emptiness" here before printing.

---

*[python/tidy.py, line 568 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9925#-KCOYfEX46vcbx1D3rVq:-KCOYfEYpZOwLQwgb7pV:762895485) ([raw file](https://github.com/servo/servo/blob/3266b29819fbf2d6b7c02f318c5a86cdb54469f1/python/tidy.py#L568)):*
We don't have to indent everything - just the `print` statement (since `for` calls the `next` method, it stops automatically when `StopIteration` is raised)

---

*[python/tidy.py, line 572 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9925#-KCOaMUNDMgt00LzU8fd:-KCOaMUNDMgt00LzU8fe:-520736041) ([raw file](https://github.com/servo/servo/blob/3266b29819fbf2d6b7c02f318c5a86cdb54469f1/python/tidy.py#L572)):*
We probably don't need this?

---

*[python/tidy.py, line 594 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9925#-KCOZ5fcst7XeMRgkhoL:-KCOZ5fcst7XeMRgkhoM:190499301) ([raw file](https://github.com/servo/servo/blob/3266b29819fbf2d6b7c02f318c5a86cdb54469f1/python/tidy.py#L594)):*
Please remove this.

---

*[python/tidy.py, line 612 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9925#-KCOZEWO97LdhymM-s8W:-KCOZEWO97LdhymM-s8X:-1187165721) ([raw file](https://github.com/servo/servo/blob/3266b29819fbf2d6b7c02f318c5a86cdb54469f1/python/tidy.py#L612)):*
ditto, we don't need this check.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9925#-:-KCO__9g5TJpY7QnVbGM:632404998)*

**Comment by zakorgy** [comment]
@Wafflespeanut  meanwhile my repository has been deleted, is there a way to continue this pull request?

**Comment by Wafflespeanut** [comment]
[The revision containing your changes is still there](https://github.com/zakorgy/servo/blob/3266b29819fbf2d6b7c02f318c5a86cdb54469f1/python/tidy.py).

**Comment by Wafflespeanut** [comment]
The best way would be to continue making the changes, push into a new branch, open a new PR and close this one.

**Comment by Wafflespeanut** [comment]
@zakorgy Are you working on this?

**Comment by zakorgy** [comment]
@Wafflespeanut  Yes, I want to create the new PR now.

**Comment by Wafflespeanut** [comment]
Oh, good to know :)

**Pull request closed without merging**
