### PR TITLE
Implement concept of dirty root

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
I hit the wrong button, I wanted to make a draft PR. Oh well.

@bors-servo try

**Comment by nox** [comment]
My code is doing bad stuff when the document's children are changed, looking into it.

**Comment by nox** [comment]
```
  ▶ CRASH [expected OK] /_webgl/conformance/ogles/GL/gl_FrontFacing/gl_FrontFacing_001_to_001.html
  │ 
  │ error: XDG_RUNTIME_DIR not set in the environment.
  │ libEGL warning: No hardware driver found, falling back to software rendering
  │ called `Option::unwrap()` on a `None` value (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /repo/components/layout/wrapper.rs:151)
  │    0: servo::backtrace::print
  │    1: servo::main::{{closure}}
  │    2: std::panicking::rust_panic_with_hook
  │              at src/libstd/panicking.rs:515
  │    3: rust_begin_unwind
  │              at src/libstd/panicking.rs:419
  │    4: core::panicking::panic_fmt
  │              at src/libcore/panicking.rs:111
  │    5: core::panicking::panic
  │              at src/libcore/panicking.rs:54
  │    6: <T as layout::wrapper::ThreadSafeLayoutNodeHelpers>::restyle_damage
  │    7: profile_traits::time::profile
  │    8: layout_thread::LayoutThread::handle_reflow
  │    9: profile_traits::time::profile
  │   10: layout_thread::LayoutThread::handle_request_helper
  │   11: layout_thread::LayoutThread::start
  │   12: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  │   13: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  │              at /rustc/42abbd8878d3b67238f3611b0587c704ba94f39c/src/liballoc/boxed.rs:1008
  │   16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  │              at /rustc/42abbd8878d3b67238f3611b0587c704ba94f39c/src/liballoc/boxed.rs:1008
  │       std::sys::unix::thread::Thread::new::thread_start
  │              at src/libstd/sys/unix/thread.rs:87
  │   17: start_thread
  │   18: __clone
  │ [2020-05-11T12:24:59Z ERROR servo] called `Option::unwrap()` on a `None` value
  │ Pipeline failed in hard-fail mode.  Crashing!
  │ thread panicked while processing panic. aborting.
  └ thread panicked while processing panic. aborting.
```

I must be missing something somewhere.

This can only happen if there is an element which doesn't have any data, but I don't see how that can happen through the dirty root, given that the parent without the data should be dirty too.

**Comment by nox** [comment]
I guess I can try without 2020 meanwhile. I had to do some fancy stuff in 2013 for incremental restyle, and that stuff is not needed on the 2020 side.

@bors-servo try=wpt-2020

**Comment by nox** [comment]
Fixed another panic, baby steps.

@bors-servo try=wpt-2020

**Comment by nox** [comment]
There are many of this:

```
 0:04.21 pid:20627 condition was Some(DirtyDescendants) (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/dom/window.rs:1750)
 0:04.81 pid:20627    0: backtrace::backtrace::trace_unsynchronized
 0:04.83 pid:20627    1: <servo::backtrace::Print as core::fmt::Debug>::fmt
 0:04.83 pid:20627    2: core::fmt::write
 0:04.83 pid:20627    3: std::io::Write::write_fmt
 0:04.84 pid:20627    4: servo::backtrace::print
 0:04.85 pid:20627    5: servo::main::{{closure}}
 0:04.85 pid:20627    6: std::panicking::rust_panic_with_hook
 0:04.85 pid:20627    7: rust_begin_unwind
 0:04.86 pid:20627    8: std::panicking::begin_panic_fmt
 0:04.86 pid:20627    9: script::dom::window::Window::reflow
 0:04.87 pid:20627   10: script::dom::document::Document::maybe_queue_document_completion::{{closure}}
 0:04.88 pid:20627   11: core::ops::function::FnOnce::call_once
 0:04.88 pid:20627   12: <script::task::CancellableTask<T> as script::task::TaskOnce>::run_once
 0:04.89 pid:20627   13: <T as script::task::TaskBox>::run_box
 0:04.89 pid:20627   14: script::script_thread::ScriptThread::handle_msg_from_script
 0:04.90 pid:20627   15: script::script_thread::ScriptThread::handle_msgs::{{closure}}
 0:04.91 pid:20627   16: script::script_thread::ScriptThread::profile_event
 0:04.91 pid:20627   17: script::script_thread::ScriptThread::handle_msgs
 0:04.92 pid:20627   18: script::script_thread::ScriptThread::start
 0:04.93 pid:20627   19: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
 0:04.93 pid:20627   20: profile_traits::mem::ProfilerChan::run_with_memory_reporting
 0:04.94 pid:20627   21: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
 0:04.94 pid:20627   22: std::sys_common::backtrace::__rust_begin_short_backtrace
 0:04.95 pid:20627   23: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
 0:04.96 pid:20627   24: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 0:04.96 pid:20627   25: std::panicking::try::do_call
 0:04.96 pid:20627   26: __rust_try.llvm.1180409861988729277
 0:04.97 pid:20627   27: std::panicking::try
 0:04.98 pid:20627   28: std::panic::catch_unwind
 0:04.98 pid:20627   29: std::thread::Builder::spawn_unchecked::{{closure}}
 0:04.99 pid:20627   30: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
 0:05.00 pid:20627   31: std::sys::unix::thread::Thread::new::thread_start
 0:05.00 pid:20627   32: _pthread_body
 0:05.00 pid:20627   33: _pthread_start
 0:05.00 pid:20627 [2020-05-14T12:33:43Z ERROR servo] condition was Some(DirtyDescendants)
 0:05.17 pid:20627 Pipeline failed in hard-fail mode.  Crashing!
```

And many many tests that just give wrong values. There is so much technical debt around dirtiness that it's really hard understanding what the hell is going on.

**Comment by nox** [comment]
This crash because somehow the root element is marked as having dirty descendants but the dirty root was somehow one of its descendants, I have legit no idea how that can happen.

**Comment by nox** [comment]
Just for a data point:

Chunk 1:

```
Ran 6442 tests finished in 1069.0 seconds.
  • 6096 ran as expected. 0 tests skipped.
  • 81 tests crashed unexpectedly
  • 215 tests failed unexpectedly
  • 1 tests timed out unexpectedly
  • 10 tests passed unexpectedly
  • 39 tests had unexpected subtest results
```

Chunk 2:

```
Ran 3498 tests finished in 619.0 seconds.
  • 3245 ran as expected. 0 tests skipped.
  • 53 tests crashed unexpectedly
  • 185 tests failed unexpectedly
  • 11 tests passed unexpectedly
  • 1 tests unexpectedly okay
  • 3 tests had unexpected subtest results
```

**Comment by nox** [comment]
Hopefully I found out why there were crashes, but there will still be `FAIL` results that I am now trying to debug.

@bors-servo try=wpt-2020

**Comment by nox** [comment]
```
Ran 6442 tests finished in 1024.0 seconds.
  • 6433 ran as expected. 0 tests skipped.
  • 4 tests crashed unexpectedly
  • 1 tests had errors unexpectedly
  • 1 tests failed unexpectedly
  • 3 tests had unexpected subtest results
```

```
Ran 3498 tests finished in 599.0 seconds.
  • 3469 ran as expected. 0 tests skipped.
  • 25 tests crashed unexpectedly
  • 3 tests failed unexpectedly
  • 1 tests unexpectedly okay
```

Feeling just a bit better right now, nice.

**Comment by nox** [comment]
Pog

@bors-servo try=wpt

**Comment by nox** [comment]
@bors-servo try

Everything should be ok now.

r? @SimonSapin

**Comment by SimonSapin** [comment]
Looks good!

@bors-servo r+

**Pull request merged**
