### PR TITLE
Parse srcset algo

### PR DESCRIPTION
**Pull request by akhan7**
Implementing parse a sourceset algorithm

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10829)

### CODE REVIEW

**Comment by jdm** [comment]
Note: I keep changing the labels because I use them as a TODO list for myself. When it's time for me to actually review the code, please speak up :)

**Comment by jdm** [comment]
I strongly recommend writing unit tests in the same manner as I described at https://github.com/servo/servo/pull/10827#issuecomment-216083562, by the way!

**Comment by akhan7** [comment]
@jdm : We've reached till step 9 of parse a source set algorithm, the test tidy passes and the build is successful. Can you please check if the algo written is conceptually correct up till this step?

**Comment by jdm** [comment]
As far as I can tell, the algorithm makes sense as written. Tests would verify that gut feeling, of course ;) You can implement the EOF condition by matching against the current state after the loop is complete, since that means that the final character was encountered.

**Comment by jdm** [comment]
I've noted this work as part of #11416. Thank you for doing it; we have learned more about what is required for implementing this. The lack of tests means that this isn't appropriate to merge right now; we'll return to it as part of #11416.

**Pull request closed without merging**
