### PR TITLE
style: Work from multiple bugs.

### PR DESCRIPTION
**Pull request by emilio**
Bug: 1429846,1429248,1430608,1409672
Reviewed-by: xidorn,heycam

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19790)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0308]: mismatched types
   --> components/style/gecko/media_queries.rs:688:17
    |
688 |                 device.pres_context().mDocument.raw::<structs::nsIDocument>(),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `gecko_bindings::structs::root::nsPresContext`, found struct `gecko_bindings::structs::root::nsIDocument`
    |
    = note: expected type `*mut gecko_bindings::structs::root::nsPresContext`
               found type `*mut gecko_bindings::structs::root::nsIDocument`
```

**Comment by emilio** [comment]
@bors-servo r=xidorn,heycam

 * Updated the bindings.

**Comment by emilio** [comment]
@bors-servo p=1

 * Need to coordiland.

**Comment by emilio** [comment]
@bors-servo r=heycam,xidorn

 * tidy

**Comment by emilio** [comment]
@bors-servo retry 

 * Tons of referrer-policy test failures?

**Pull request merged**
