### PR TITLE
Enable additional WPT test suites

### PR DESCRIPTION
**Pull request by jdm**
This enables some directories of tests that were added upstream without being enabled locally.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #20889
- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21398)

### CODE REVIEW

**Comment by jdm** [comment]
@jgraham Could you sign off on the last two changes?

**Comment by jdm** [comment]
linux:
```
  ▶ TIMEOUT [expected OK] /mimesniff/mime-types/charset-parameter.window.html
  │ 
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 18.1.0-devel

  ▶ Unexpected subtest result in /mimesniff/mime-types/charset-parameter.window.html:
  │ TIMEOUT [expected FAIL] text/html;0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789=x;charset=gbk
  └   → Test timed out

  ▶ Unexpected subtest result in /mimesniff/mime-types/charset-parameter.window.html:
  │ TIMEOUT [expected FAIL] text/html;test=\xff;charset=gbk
  └   → Test timed out

  ▶ TIMEOUT [expected OK] /_mozilla/mozilla/mime_sniffing_font_context.html
  │ 
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 18.1.0-devel

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  └ NOTRUN [expected PASS] Sniffed font is loaded and applied

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  └ NOTRUN [expected PASS] Sniffed font with xml is not loaded

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  └ NOTRUN [expected PASS] Sniffed font with xhtml+xml is not loaded

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] XHR Content-Type has xhtml+xml
  │   → assert_equals: expected "application/xhtml+xml" but got "application/json"
  │ 
  │ xhr.onload<@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:54:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1553:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1593:17

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] XHR Content-Type is empty
  │   → assert_equals: expected (object) null but got (string) "application/json"
  │ 
  │ xhr.onload<@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:44:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1553:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1593:17

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] XHR Content-Type has xml
  │   → assert_equals: expected "application/xml" but got "application/json"
  │ 
  │ xhr.onload<@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:64:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1553:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1593:17
```

mac:
```
  ▶ CRASH [expected OK] /mimesniff/mime-types/charset-parameter.window.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.1.0-devel
  │ failed to open /dev/urandom: Os { code: 24, kind: Other, message: "Too many open files" } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(75) }, at libcore/result.rs:945)
  │ 2018-08-13 16:38:22.294 servo[7120:49805363] Metadata.framework [Error]: couldn't get the client port
  │ failed to open /dev/urandom: Os { code: 24, kind: Other, message: "Too many open files" } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(90) }, at libcore/result.rs:945)
  │ failed to open /dev/urandom: Os { code: 24, kind: Other, message: "Too many open files" } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(96) }, at libcore/result.rs:945)
  │ failed to open /dev/urandom: Os { code: 24, kind: Other, message: "Too many open files" } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(2), index: PipelineIndex(93) }, at libcore/result.rs:945)

  ▶ TIMEOUT [expected OK] /_mozilla/mozilla/mime_sniffing_font_context.html
  │ 
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 18.1.0-devel

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  └ NOTRUN [expected PASS] Sniffed font is loaded and applied

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  └ NOTRUN [expected PASS] Sniffed font with xml is not loaded

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  └ NOTRUN [expected PASS] Sniffed font with xhtml+xml is not loaded

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] XHR Content-Type has xhtml+xml
  │   → assert_equals: expected "application/xhtml+xml" but got "application/json"
  │ 
  │ xhr.onload<@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:54:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1553:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1593:17

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] XHR Content-Type is empty
  │   → assert_equals: expected (object) null but got (string) "application/json"
  │ 
  │ xhr.onload<@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:44:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1553:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1593:17

  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] XHR Content-Type has xml
  │   → assert_equals: expected "application/xml" but got "application/json"
  │ 
  │ xhr.onload<@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:64:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1553:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1593:17
```

**Comment by jgraham** [comment]
r+ from me once it passes try.

**Comment by jdm** [comment]
@jgraham So I found https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests/infrastructure/metadata/infrastructure; is there any way to have our local test run use those expected outcomes instead of tests/wpt/metadata/infrastructure?

**Comment by jgraham** [comment]
You could set up a separate job just for the infra tests and point to the metadata there (either using a config.ini file or the command line). There isn't any built-in way for a single invocation of the runner to combine ini files from multiple sources. The obvious other option would be to copy the files over during sync.

**Comment by jdm** [comment]
Mmm, smart! Thanks.

**Comment by nox** [comment]
How come this never landed?

**Comment by jdm** [comment]
Because I am easily distracted.

**Comment by dralley** [comment]
Maybe some open pull request cleanup is warranted :)

**Review by Manishearth — APPROVED** [review]

**Comment by jdm** [comment]
Most of these tests are now included in Servo's WPT runs, excluding infrastructure/ and mimesniff/. infrastructure/ is a bit complicated (see https://github.com/servo/servo/pull/21398#issuecomment-430391717) and mimesniff/ does not look high value enough for me to prioritize at the moment.

**Pull request closed without merging**
