### PR TITLE
Make History attributes and methods throw

### PR DESCRIPTION
**Pull request by cbrewster**
All History methods and attributes should throw a `SecurityError` if the document associated with the `History` object is not fully active.
https://html.spec.whatwg.org/multipage/browsers.html#history-3

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16697)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo r+

I suspect that we may have passing tests; if so, just update the expectations and r=me again.

**Comment by KiChjang** [comment]
@bors-servo retry
* infra

**Comment by cbrewster** [comment]
Hmm no tests for these; however, I don't know how we would make a test that makes calls to the History object on a non fully-active document.

**Pull request merged**
