### PR TITLE
Preparing request for async

### PR DESCRIPTION
**Pull request by KiChjang**
cc #4576
This is a commit to refactor all of the existing request code to support async listeners in the future

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6304)

### CODE REVIEW

**Comment by KiChjang** [comment]
Actually, now I think about it, `ResponseResult` is kind of silly because this only works for sync results... Ideally, the async result should simply return an `Ok(())`, but this currently doesn't work.

**Comment by jdm** [comment]
I've started reviewing this. Apologies for the extremely delay!

**Comment by jdm** [comment]
Huh, I was convinced that this was a bigger PR than it actually is. I feel worse about not having got around to it now. Anyways, onwards!

This feels like an unusual way to go about this. IIRC there are no actual consumers of the fetch code right now, so creating this intermediate state of conceptually allowing both async and sync fetches to occur doesn't seem valuable to me. Additionally, I'm not really enthusiastic about overloading the Result type this way - while we can argue that a network error result can be represented by an Err, I think that an Err result should really indicate that our fetch infrastructure messed up and it's impossible to determine the result of a network request instead.

Here's my proposal for how to move forward - we go full async all the time. We also don't try to shoehorn in the AsyncResponseListener stuff into the interface, since that operates at the level of the network protocol: "the response has started", "here's some data", "no more response notifications will arrive". Instead, let's make an AsyncFetchListener interface that has listener methods for whatever makes sense for Fetch - presumably one that takes a Response argument, at least. We can then call that directly instead of returning Result values, and we can create a bridge between the AsyncResponseListener infrastructure if necessary. See the code in cors.rs that does a similar thing for prior art. Does that make sense?

Given the very different path forward that I've proposed, I don't see much point in leaving this particular PR open. I'm glad you started this work so that we could have this conversation, though!

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/fetch/request.rs, line 19 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6304#-JuRFktqRvDoxAa-2QX8)** ([raw file](https://github.com/servo/servo/blob/441335a52cba07bb9872096df5ebd84e427f6f82/components/net/fetch/request.rs#L19)):</sup>
When would we have a successful fetch result with no response?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6304)

**Comment by Manishearth** [comment]
Note that Rust may get ES6-style generator support (eddy is working on an rfc), so if we just use async everywhere and simulate sync via blocking, we can later easily convert the API into one which is both sync and async with zero cost for sync. Perhaps. 

I'd love our entire net infra to move to a generator-based model.

**Pull request closed without merging**
