### PR TITLE
Update network stack dependencies

### PR DESCRIPTION
**Pull request by mrobinson**
This change updates the following dependencies:

- webpki-roots
- webpki
- async-tungstenite
- rustls
- rustls-webpki
- ring
- hyper-rustls

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they just update dependencies.

### CODE REVIEW

**Comment by mrobinson** [comment]
This is still pending on the release of a new version of `hyper-rustls`.

**Comment by atouchet** [comment]
hyper-rustls 0.24.2 is now out.

**Comment by mrobinson** [comment]
Okay.  This is ready to review. It removes two duplicated dependencies.

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
```
error: package `async-tungstenite v0.23.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.69.0-nightly
```

**Pull request merged**
