### PR TITLE
Fix the "get the parent" loop when dispatching event (fixes #6733)

### LINKED ISSUE #6733: Ensure mouse events are dispatched to document/window as necessary
I'm not sure what the spec mandates here, but I'm pretty sure our implementation is lacking.

### PR DESCRIPTION
**Pull request by nox**
The DOM specification says:

> A document's get the parent algorithm, given an event, returns null
> if event's type attribute value is "load" or document does not have
> a browsing context, and the document's associated Window object
> otherwise.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9734)

### CODE REVIEW

**Comment by jdm** [comment]
This fixes #6733.

**Comment by Ms2ger** [comment]
I want a bunch of tests that this does not affect documents that are not in a browsing context

**Comment by Ms2ger** [comment]
Reviewed 1 of 2 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBO0oUcmNujoHLbqFlk:-KBO0oUcmNujoHLbqFll:1266165714) ([raw file](https://github.com/servo/servo/blob/94686fc3fb783bed5f7c93d4fc4d4901e3cc7bd4/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L34)):*
I'd move the `test()` out of the function, to make sure we catch exceptions from`concat`, say.

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 80 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBO0aHeKJNVRydnd4v3:-KBO0aHeKJNVRydnd4v4:1807066171) ([raw file](https://github.com/servo/servo/blob/94686fc3fb783bed5f7c93d4fc4d4901e3cc7bd4/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L80)):*
Please also add `new Document()` / `createHTMLDocument()`, and test them all with `load` too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9734)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBO0oUcmNujoHLbqFlk:-KBSf_lPrYnlQJI8S515:-1056892065) ([raw file](https://github.com/servo/servo/blob/94686fc3fb783bed5f7c93d4fc4d4901e3cc7bd4/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L34)):*
If I do this, I can't build the test name anymore by concatenating it.

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 80 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBO0aHeKJNVRydnd4v3:-KBSfgG62LBzl4C02oHZ:-499146009) ([raw file](https://github.com/servo/servo/blob/94686fc3fb783bed5f7c93d4fc4d4901e3cc7bd4/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L80)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9734)*

**Comment by Ms2ger** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBO0oUcmNujoHLbqFlk:-KBSo3t3y7Hr28xi_n7G:-387146302) ([raw file](https://github.com/servo/servo/blob/94686fc3fb783bed5f7c93d4fc4d4901e3cc7bd4/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L34)):*
Feel free to drop the ": Event.dispatchEvent with Event.bubbles set to false." bit

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9734)*

**Comment by nox** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBO0oUcmNujoHLbqFlk:-KBSthIQ_rvMWyZdQbUu:-499146009) ([raw file](https://github.com/servo/servo/blob/94686fc3fb783bed5f7c93d4fc4d4901e3cc7bd4/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L34)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9734)*

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 34 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBTBqZxpAmGTyDVRPkp:-KBTBqZxpAmGTyDVRPkq:-350585676) ([raw file](https://github.com/servo/servo/blob/1270c8acc8fbc0d772242154ea5ee802d377f186/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L34)):*
Also test "load"

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 71 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBTBjPqmPPGZ9NL9OsN:-KBTBjPr0og5l-vKMRWX:570623798) ([raw file](https://github.com/servo/servo/blob/1270c8acc8fbc0d772242154ea5ee802d377f186/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L71)):*
Add a `var`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9734)*

**Comment by nox** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 34 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBTBqZxpAmGTyDVRPkp:-KBTCqBZECWlLFv2FF32:-499146009) ([raw file](https://github.com/servo/servo/blob/1270c8acc8fbc0d772242154ea5ee802d377f186/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L34)):*
Done.

---

*[tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html, line 71 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9734#-KBTBjPqmPPGZ9NL9OsN:-KBTCpMmpeNeyqWEfk2o:-499146009) ([raw file](https://github.com/servo/servo/blob/1270c8acc8fbc0d772242154ea5ee802d377f186/tests/wpt/web-platform-tests/dom/events/Event-dispatch-bubbles-false.html#L71)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9734)*

**Comment by Ms2ger** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9734#-:-KBTOJjHZcMpwo2qQzIz:1236647940)*

**Comment by nox** [comment]
@bors-servo r=Ms2ger

The failure is unrelated, and better than the previous timeout.

**Comment by nox** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /DOMEvents/tests/approved/DOM.event.flow.html:
  └ PASS [expected FAIL] Test Description: Dispatch an event in a DOM tree using the DOM event flow.

  ▶ Unexpected subtest result in /DOMEvents/tests/approved/stopImmediatePropagation.effect.html:
  └ PASS [expected FAIL] Test Description: stopImmediatePropagation() prevents other event listeners from being triggered and, unlike Event.stopPropagation(), its effect must be immediate. Once it has been called, further calls to this method have no additional effect.

  ▶ Unexpected subtest result in /DOMEvents/tests/approved/stopPropagation.deferred.effect.html:
  └ PASS [expected FAIL] Test Description: stopPropagation() prevents other event listeners from being triggered but its effect must be deferred until all event listeners attached on the Event.currentTarget have been triggered.

  ▶ Unexpected subtest result in /DOMEvents/tests/submissions/Microsoft/converted/DOM.event.flow.html:
  └ PASS [expected FAIL] Test Description: Dispatch an event in a DOM tree using the DOM event flow.

  ▶ Unexpected subtest result in /DOMEvents/tests/submissions/Microsoft/converted/EventListener.dispatch.new.event.html:
  └ PASS [expected FAIL] Test Description: Implementations of the DOM event model must be reentrant. Event listeners may perform actions that cause additional events to be dispatched. Such events are handled in a synchronous manner, the event propagation that causes the event listener to be triggered must resume only after the event dispatch of the new event is completed.

  ▶ Unexpected subtest result in /DOMEvents/tests/submissions/Microsoft/converted/stopImmediatePropagation.effect.html:
  └ PASS [expected FAIL] Test Description: stopImmediatePropagation() prevents other event listeners from being triggered and, unlike Event.stopPropagation(), its effect must be immediate. Once it has been called, further calls to this method have no additional effect.

  ▶ Unexpected subtest result in /DOMEvents/tests/submissions/Microsoft/converted/stopPropagation.deferred.effect.html:
  └ PASS [expected FAIL] Test Description: stopPropagation() prevents other event listeners from being triggered but its effect must be deferred until all event listeners attached on the Event.currentTarget have been triggered.

  ▶ Unexpected subtest result in /old-tests/submission/Opera/script_scheduling/112.html:
  │ FAIL [expected PASS]  scheduler: removing async attribute at runtime, script also has defer attribute
  │   → assert_array_equals: lengths differ, expected 0 got 1
  │ 
  │ @http://web-platform.test:8000/old-tests/submission/Opera/script_scheduling/112.html:5:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1
```

Last one is an intermittent. Will fix tomorrow.

**Comment by nox** [comment]
The failing Opera test seems to be unrelated to that change, I guess it was a coincidence that it was passing before. @Ms2ger r?

**Comment by nox** [comment]
```

15:03 <nox> jdm: https://github.com/servo/servo/pull/9734#issuecomment-189629001 Any opinion?
15:03 <crowbot1> PR #9734: Fix the "get the parent" loop when dispatching event (fixes #6733) - https://github.com/servo/servo/pull/9734
15:03 — ~jdm reads
15:04 <~jdm> interesting
15:04 <~jdm> go ahead and file it as an intermittent, in that case
15:04 <nox> It's not an intermittent.
15:04 <nox> jdm: I don't understand how it could pass before.
15:05 <~jdm> oh
15:05 <nox> jdm: We don't do anything with 'async' in HTMLScriptElement::attribute_mutated,
15:05 <nox> so there is no way something special should happen when it's removed.
15:05 <nox> So I don't see why it was passing, nor why my patch changes that.
15:05 <~jdm> oh, so previously we didn't dispatch DOMContentLoaded at the window element, perhaps?
15:06 <nox> Oh, yes.
15:06 <nox> Probably that.
15:06 <~jdm> yep, we fire it at the document
15:06 <~jdm> so your changes change that
15:06 <nox> So it's normal that it doesn't pass?
15:06 <~jdm> yes
15:06 <nox> So can I r=jdm,Ms2ger?
15:06 <~jdm> yep
15:06 <nox> Good.
```

@bors-servo r=Ms2ger,jdm

**Comment by nox** [comment]
@bors-servo r=Ms2ger,jdm

Forgot one last expectation.

**Pull request merged**
