### PR TITLE
Restore exit after load command line flag.

### PR DESCRIPTION
**Pull request by glennw**
Also updates glutin with a crash fix that was exposed by this patch.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6666)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6666)

**Comment by larsbergstrom** [comment]
It's not just mac3 - linux2 http://build.servo.org/builders/linux2/builds/2326, linux3 http://build.servo.org/builders/linux3/builds/478, and mac1 http://build.servo.org/builders/mac1/builds/2562/steps/shell_2/logs/stdio all failed, too. It doesn't appear to be related to the build machines but instead is a new crash, but feel free to push back if it seems machine-related.

**Comment by glennw** [comment]
@larsbergstrom Ah I missed that the wpt reftests pass both the exit + output flags. Updated PR to handle this case correctly.

**Comment by larsbergstrom** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6666)

**Comment by larsbergstrom** [comment]
Nice! Squash & r=me.

**Pull request merged**
