### PR TITLE
README: Add python3-setuptools to ubuntu apt install line

### PR DESCRIPTION
**Pull request by sagudev**
This was needed on my clean installed ubuntu 24.10.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it's only docs

### CODE REVIEW

**Comment by mrobinson** [comment]
Do you happen to have a copy of the error? Perhaps this is needed in `requirements.txt` instead.

**Comment by sagudev** [comment]
> Do you happen to have a copy of the error? Perhaps this is needed in `requirements.txt` instead.

Unfortunately not, but given that we also install pip and venv this way I think it is right way to do as setuptools is also about installing py packages.

**Comment by mrobinson** [comment]
> Unfortunately not, but given that we also install pip and venv this way I think it is right way to do as setuptools is also about installing py packages.

It's not a direct dependency of our installation process though and typically indirect dependencies are installed via `requirements.txt` AFAIK.

**Comment by sagudev** [comment]
error:
```
Collecting blessings==1.7 (from -r /servo/python/requirements.txt (line 4))
  Downloading blessings-1.7-py3-none-any.whl.metadata (19 kB)
Collecting distro==1.4 (from -r /servo/python/requirements.txt (line 5))
  Downloading distro-1.4.0-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting mozinfo==1.2.3 (from -r /servo/python/requirements.txt (line 6))
  Downloading mozinfo-1.2.3-py2.py3-none-any.whl.metadata (649 bytes)
Collecting mozlog==8.0.0 (from -r /servo/python/requirements.txt (line 7))
  Downloading mozlog-8.0.0.tar.gz (53 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-s9ipom8b/mozlog_9174927e8a1140948d3b8243ff162e6d/setup.py", line 5, in <module>
          from setuptools import find_packages, setup
      ImportError: cannot import name 'find_packages' from 'setuptools' (unknown location)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

```

**Comment by sagudev** [comment]
I think the problem is that mozlog expect setuptools to be already installed in its installer, but it's not installed yet (we install it by same invocation of `pip install -r`).

BTW moving setuptools in requirements.txt to be first does not help.

**Comment by mrobinson** [comment]
I guess this is a decent workaround until we can get more information about what is going on here.  It's pretty likely that this should ultimately be something that `./mach bootstrap` does.

**Review by mrobinson — APPROVED** [review]

**Pull request merged**
