### PR TITLE
Expect dom syntax error in window postmessage sameorigin test

### LINKED ISSUE #25808: Intermittent failure in /_mozilla/mozilla/window-postmessage-sameorigin.html
```
  â–¶ Unexpected subtest result in /_mozilla/mozilla/window-postmessage-sameorigin.html:
  â”‚ FAIL [expected PASS] explicit invalid url, cloneable string message (handler)
  â”‚   â†’ assert_throws_js: function "function() { postMessage(message, origin) }" threw object "SyntaxError: The string did not match the expected pattern." ("SyntaxError") expected instance of function "function SyntaxError() {
  â”‚   â†’     [native code]
  â”‚   â†’ }" ("SyntaxError")
  â”‚ 
  â”‚ expect_error_js/</<@http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:15:7
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1867:25
  â”‚ test@http://web-platform.test:8000/resources/testharness.js:548:30
  â”‚ expect_error_js/<@http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:14:5
  â”‚ next_test@http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:77:26
  â”‚ @http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:84:3
  â”‚ Tests.prototype.notify_result/<@http://web-platform.test:8000/resources/testharness.js:2593:21
  â”‚ forEach@http://web-platform.test:8000/resources/testharness.js:3460:26
  â”‚ Tests.prototype.notify_result@http://web-platform.test:8000/resources/testharness.js:2590:9
  â”‚ Tests.prototype.result@http://web-platform.test:8000/resources/testharness.js:2584:14
  â”‚ cleanup_done@http://web-platform.test:8000/resources/testharness.js:2112:15
  â”‚ Test.prototype.cleanup@http://web-platform.test:8000/resources/testharness.js:2051:13
  â”‚ Test.prototype.done@http://web-platform.test:8000/resources/testharness.js:1997:14
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1878:18
  â”‚ test@http://web-platform.test:8000/resources/testharness.js:548:30
  â”‚ expect_error_js/<@http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:14:5
  â”‚ next_test@http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:77:26
  â”‚ @http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:84:3
  â”‚ Tests.prototype.notify_result/<@http://web-platform.test:8000/resources/testharness.js:2593:21
  â”‚ forEach@http://web-platform.test:8000/resources/testharness.js:3460:26
  â”‚ Tests.prototype.notify_result@http://web-platform.test:8000/resources/testharness.js:2590:9
  â”‚ Tests.prototype.result@http://web-platform.test:8000/resources/testharness.js:2584:14
  â”‚ cleanup_done@http://web-platform.test:8000/resources/testharness.js:2112:15
  â”‚ Test.prototype.cleanup@http://web-platform.test:8000/resources/testharness.js:2051:13
  â”‚ Test.prototype.done@http://web-platform.test:8000/resources/testharness.js:1997:14
  â”” Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1911:23

  â–¶ Unexpected subtest result in /_mozilla/mozilla/window-postmessage-sameorigin.html:
  â”‚ FAIL [expected PASS] explicit invalid url, cloneable string message (listener)
  â”‚   â†’ assert_throws_js: function "function() { postMessage(message, origin) }" threw object "SyntaxError: The string did not match the expected pattern." ("SyntaxError") expected instance of function "function SyntaxError() {
  â”‚   â†’     [native code]
  â”‚   â†’ }" ("SyntaxError")
  â”‚ 
  â”‚ expect_error_js/</<@http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:15:7
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1867:25
  â”‚ test@http://web-platform.test:8000/resources/testharness.js:548:30
  â”‚ expect_error_js/<@http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:14:5
  â”‚ next_test@http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:77:26
  â”‚ @http://web-platform.test:8000/_mozilla/mozilla/window-postmessage-sameorigin.html:84:3
  â”‚ Tests.prototype.notify_result/<@http://web-platform.test:8000/resources/testharness.js:2593:21
  â”‚ forEach@http://web-platform.test:8000/resources/testharness.js:3460:26
  â”‚ Tests.prototype.notify_result@http://web-platform.test:8000/resources/testharness.js:2590:9
  â”‚ Tests.prototype.result@http://web-platform.test:8000/resources/testharness.js:2584:14
  â”‚ cleanup_done@http://web-platform.test:8000/resources/testharness.js:2112:15
  â”‚ Test.prototype.cleanup@http://web-platform.test:8000/resources/testharness.js:2051:13
  â”‚ Test.prototype.done@http://web-platform.test:8000/resources/testharness.js:1997:14
  â”” Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1911:23

```
My suspicion is that this is related to the global that is used to retrieve the SyntaxError constructor, since the objects will be different for different globals.

### PR DESCRIPTION
**Pull request by gterzian**
FIX #25808

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by gterzian** [comment]
@jdm r?

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo r-
Temporarily to keep the queue down.

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Pull request merged**
