### PR TITLE
script: Make timer events e10s-safe.

### LINKED ISSUE #8235: TimerEventRequest is completely un-e10s-safe (blocks e10s from landing)
Boxed trait objects sent from script to compositor. This is a big no-no.

### PR DESCRIPTION
**Pull request by jdm**
Closes #8235.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8492)

### CODE REVIEW

**Comment by jdm** [comment]
Rebase of #8237.

**Comment by eefriedman** [comment]
```
/home/servo/buildbot/slave/linux-rel/build/components/script/dom/window.rs:57:21: 57:32 error: unresolved import `script_traits::MsgDuration`. There is no `MsgDuration` in `script_traits` [E0432]
/home/servo/buildbot/slave/linux-rel/build/components/script/dom/window.rs:57 use script_traits::{MsgDuration, TimerEvent, TimerEventId, TimerEventRequest, TimerSource};
                                                                                                  ^~~~~~~~~~~
```

**Pull request merged**
