### PR TITLE
webgl: FBO support preparation

### PR DESCRIPTION
**Pull request by anholt**
Sending this PR now so that we can get the webrender patches merged.  This is prep for the webgl-fbo series, with one small fix for some conformance tests.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13309)

### CODE REVIEW

**Comment by anholt** [comment]
Note that the first commit will require a bump of the webrender dependency.  I haven't figured out how to make mach update-cargo update to a commit that's not in master, though.

**Comment by emilio** [comment]
r=me with the webrender traits update

@anholt feel free to land yourself this one :)

@bors-servo: delegate+

**Comment by glennw** [comment]
@anholt The required webrender changes have landed in master now. So you should be able to to ./mach update-cargo -p webrender in this branch and then we should be able to land this.

**Pull request merged**
