### PR TITLE
Layout 2020: Remove the floats preference

### PR DESCRIPTION
**Pull request by mrobinson**
Enable floats always. It doesn't make sense to have this preference as it's a basic feature of an experimental layout engine.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

### CODE REVIEW

**Comment by Loirooriol** [comment]
#29852 should have addressed the timeouts.
@bors-servo try=wpt-2020

**Comment by mrobinson** [comment]
@bors-servo try=wpt-2020

The crash in /css/css-flexbox/flexbox_inline-float.html should be addressed by #29859.

**Review by Loirooriol — APPROVED** [review]
So these are the new failures:
- /_mozilla/css/absolute_hypothetical_float.html
- /_mozilla/css/content_color.html
- /_mozilla/css/flex_nochild.html
- /css/CSS2/css1/c5514-brdr-lw-001.xht
- /css/CSS2/margin-padding-clear/padding-applies-to-007.xht
- /css/CSS2/margin-padding-clear/padding-applies-to-013.xht
- /css/CSS2/margin-padding-clear/padding-applies-to-014.xht
- /css/css-flexbox/abspos/flex-abspos-staticpos-justify-self-001.html
- /css/css-flexbox/abspos/flex-abspos-staticpos-margin-001.html
- /css/css-flexbox/flex-basis-intrinsics-001.html
- /css/css-flexbox/flex-vertical-align-effect.html
- /css/css-flexbox/flexbox-writing-mode-016.html
- /css/css-flexbox/overflow-area-001.html
- /css/css-flexbox/overflow-area-002.html
- /css/css-logical/logical-values-float-clear-1.html
- /css/css-logical/logical-values-float-clear-2.html
- /css/css-logical/logical-values-float-clear-reftest.html

I'm particularly surprised by:

- /css/css-logical/logical-values-float-clear-1.html
- /css/css-logical/logical-values-float-clear-2.html

**Comment by mrobinson** [comment]
@bors-servo r=Loirooriol

Thanks for the review!

**Pull request merged**
