### PR TITLE
Update WR (preserve-3d, AA improvements)

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16860)

### CODE REVIEW

**Comment by glennw** [comment]
The first two commits have already been reviewed in https://github.com/servo/servo/pull/16775 - this just adds a commit with some updated test expectations.

**Comment by glennw** [comment]
r? anyone on the last commit - it adds 6 new passes and 1 new fail. The failure is due to a couple of stray pixels due to the ongoing anti-aliasing work.

**Comment by glennw** [comment]
@bors-servo retry
 * See if the timeout on mac is consistent.

**Comment by glennw** [comment]
Looks like a permanent timeout on mac - will try to reproduce locally.

**Comment by glennw** [comment]
I can reproduce this locally - it looks like the border tests are taking longer to execute on OSMesa. I'll investigate why tomorrow.

**Comment by nox** [comment]
Please squash the expectation commit into kvark's commit.

**Comment by mbrubeck** [comment]
@bors-servo r-

Forgot about @nox's feedback above.  r=mbrubeck after squashing.

**Comment by glennw** [comment]
Squashed the commits and rebased. Added one new test change - disabled https://github.com/servo/servo/pull/16860/files#diff-000446b741b205b52169061e9caf4fb9.

The test in question renders a 160,000 px border, which WR currently times out on with the software rasterizer.

r? anyone for that last change.

**Comment by glennw** [comment]
@bors-servo r-
 * I messed up the commit squashing - will fix up and re-open.

**Comment by glennw** [comment]
@bors-servo r=mbrubeck
 * Pulled across a couple more of the test changes from the previous PR that I accidentally missed.

**Pull request merged**
