### PR TITLE
Implement value for DOMTokenList

### LINKED ISSUE #9725: Implement DOMTokenList.value
https://dom.spec.whatwg.org/#interface-domtokenlist
https://dom.spec.whatwg.org/#dom-domtokenlist-value

This allows us to put `PutForwards=value` on `DOMTokenList` interface properties like `Element.classList` and pass the last failing test in `tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html`.

Files:
 * components/script/dom/domtokenlist.rs
 * components/script/dom/webidls/DOMTokenList.webidl
 * components/script/dom/webidls/Element.webidl
 * tests/wpt/metadata/dom/nodes/Element-classlist.html.ini
 * tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html

### PR DESCRIPTION
**Pull request by Tangresh**
Fixes #9725

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9763)

### CODE REVIEW

**Comment by Ms2ger** [comment]
You'll need to add spec links for those new methods to make `./mach test-tidy` happy.

I'm also somewhat concerned that there's no more passing tests.

r? @nox

**Comment by Tangresh** [comment]
I think there are 4 more tests that pass with this change, should there be more?

**Comment by Ms2ger** [comment]
Yeah, but the interfaces test only checks that the attribute is implemented, not if it works correctly. I'll see if I can find anything better.

**Comment by nox** [comment]
The new passing tests check that PutForwards work correctly, but none of them check the actual value of `list.value`. Trying the PR to see if there are more of them, but unfortunately I don't think there are any.

@bors-servo try

**Comment by nox** [comment]
Could you add a test in `tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html` that actually use the `value` attribute?

**Comment by Tangresh** [comment]
Is the Element-classlist test the right place for such a test? I found a test for DOMTokenList-stringifier, would an equivalent test for value be more appropriate?

**Comment by nox** [comment]
@Tangresh Now that you mention it, it should just probably go in a new test.

```
./mach create-wpt tests/wpt/web-platform-tests/dom/lists/DOMTokenList-value.html
```

**Comment by nox** [comment]
r=me once you squash the commits.

-S-awaiting-review -C-needs-test -S-needs-tests +S-needs-squash 

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9763#-:-KBh8cWJ7SPk1UlHugGS:1819316711)*

**Pull request merged**
