### PR TITLE
Use keyboard-types::webdriver::send_keys

### PR DESCRIPTION
**Pull request by pyfisch**
This improves the quality of KeyboardEvents sent by WebDriver. Now key, code, location and modifiers are set according to spec. CompositionEvents are discarded as servo does not handle them at all.

CompositionEvent support can be added later.

Is there a good way to automatically test this?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22173)

### CODE REVIEW

**Comment by paulrouget** [comment]
There are tests here: tests/wpt/web-platform-tests/webdriver/tests/element_send_keys/send_keys.py

In case you haven't done any manual testing, I usually test web driver commands like this:

```
servo --webdriver
curl  -d '{"url":"data:text/html,<input>"}' -X POST http://127.0.0.1:7000/session
curl  -d '{"using":"css selector", "value":"input"}' -X POST http://127.0.0.1:7000/session/SESSIONID/element 
X=`printf "\\uE023"`
curl  -d "{\"text\":\"$X\"}" -X POST http://127.0.0.1:7000/session/SESSIONID/element/ELEMENTID/value
```

**Comment by pyfisch** [comment]
> In case you haven't done any manual testing

Yeah, I did test it like that. Additionally I checked that the `send_keys` logic does what I expect.

See also w3c/webdriver#1360 for a list of reported inconsistencies/typos in the specification.

**Pull request merged**
