### PR TITLE
send a reply when thread is done exiting

### LINKED ISSUE #11467: Storage, resource threads race with shutdown to write out their data
When receiving an `Exit` message, they try to write out their data to the config dir, but nothing guarantees that they manage to do that before the process exits.

### PR DESCRIPTION
**Pull request by ab22**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #11467

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because: in this case if code compiles then it's good enough.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11497)

### CODE REVIEW

**Comment by Ms2ger** [comment]
R? @Ms2ger

**Comment by ab22** [comment]
Just ran these on my branch:
- `./mach clean` 
- `./mach build -d` 
- `./mach build --release`

And they all run successfully. 

AppVeyor reports:
C:/projects/servo/target/debug/build/mozjs_sys-661d4efe7c7ca939/out/dist/include/js/**TypeDecls.h**:23:23: fatal error: **js-config.h: No such file or directory**
compilation terminated.

Travis-CI: 
The command "**bash etc/ci/check_no_unwrap.sh**" exited with 1.
$ bash etc/ci/lockfile_changed.sh

Any ideas?

**Comment by ab22** [comment]
Managed to fix the "**The command "bash etc/ci/check_no_unwrap.sh" exited with 1.**". I did not notice the command printed the actual error.

Now I'm just stuck with the AppVeyor error.

**Comment by jdm** [comment]
Yes, appveyor is covered by #11494.

**Comment by Ms2ger** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/constellation/constellation.rs, line 821 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11497#-KJ-aAMfT0Y2flAXM6Zj:-KJ-aAMfT0Y2flAXM6Zk:-1532838688) ([raw file](https://github.com/servo/servo/blob/897ef271825b1188a8667e273fd3ec54b333272a/components/constellation/constellation.rs#L821)):*
> ```Rust
>     fn handle_exit(&mut self) {
>         // Channel to recieve signals when thread is done exiting.
>         let (sender, rx) = ipc::channel().expect("Failed to create IPC channel!");
> ```

Using `rx` is an unfortunately common obfuscation in Rust; please use `receiver`.

---

*[components/constellation/constellation.rs, line 848 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11497#-KJ-aJVaXIyWNcU65LRp:-KJ-aJVaXIyWNcU65LRq:411560894) ([raw file](https://github.com/servo/servo/blob/897ef271825b1188a8667e273fd3ec54b333272a/components/constellation/constellation.rs#L848)):*
> ```Rust
>         }
>         self.font_cache_thread.exit();
>         for _ in 0..2 {
> ```

I have to say I don't really like this loop. I think I'd rather use two separate channels and explicitly receive on each of them. That's a little more work, but this code only runs once per process, so *shrug*.

---

*[components/net_traits/storage_thread.rs, line 38 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11497#-KJ-i7YzC7v2Uk3dWPlH:-KJ-i7YzC7v2Uk3dWPlI:-400843773) ([raw file](https://github.com/servo/servo/blob/897ef271825b1188a8667e273fd3ec54b333272a/components/net_traits/storage_thread.rs#L38)):*
> ```Rust
>     Clear(IpcSender<bool>, Url, StorageType),
> 
>     /// shut down this thread
> ```

Update the documentation here too.

---

*[tests/unit/net/resource_thread.rs, line 44 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11497#-KJ-iHB0HzAuYrJ8iCQS:-KJ-iHB0HzAuYrJ8iCQT:-1814244094) ([raw file](https://github.com/servo/servo/blob/897ef271825b1188a8667e273fd3ec54b333272a/tests/unit/net/resource_thread.rs#L44)):*
> ```Rust
>     let (sender, _receiver) = ipc::channel().unwrap();
>     let resource_thread = new_core_resource_thread("".to_owned(), None, ProfilerChan(tx));
>     resource_thread.send(CoreResourceMsg::Exit(sender)).unwrap();
> ```

Let's add `receiver.recv().unwrap();` to all these tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11497)*

**Comment by ab22** [comment]
@Ms2ger This is ready for CR. AppVeyor is still failing because of #11494

**Comment by Ms2ger** [comment]
Sorry for the delay, I lost track of the tab I'd loaded this in.

@bors-servo r+

<details><summary><i>Previously, ab22 (Abelardo Mendoza) wrote…</i></summary>
> @Ms2ger This is ready for CR. AppVeyor is still failing because of #11494 
</details>


---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11497#-:-KJA8hO0T2lkOx66SSXe:-762369099)*

**Comment by ab22** [comment]
@Ms2ger No worries .. thought that you guys might be waiting for a rebase :P

**Pull request merged**
