### PR TITLE
Use generics for the vertical-align property

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18301)

### CODE REVIEW

**Comment by nox** [comment]
r? @emilio 

Will do a geckotry tomorrow.

**Comment by jdm** [comment]
```
 couldn't read "C:\\projects\\servo\\components\\style\\values\\computed\\box.rs": The system cannot find the file specified. (os error 2)
  --> C:\projects\servo\components\style\values\computed\mod.rs:65:9
   |
65 | pub mod box_;
   |         ^^^^
error: aborting due to previous error
error: Could not compile `style`.
```

**Comment by nox** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=1edf1e2a1227b73388d8c4ecf936f1bd305f04e3

**Review by emilio — APPROVED** [review]

**Comment by emilio** [comment]
Wonderful :)

**Comment by nox** [comment]
Had forgotten `-moz-middle-with-baseline`, will do a geckotry again when @emilio's PR removing `HasViewportPercentage` lands in autoland.

**Comment by nox** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=974bb2328403af3933340a8377116c86551f325a

**Comment by nox** [comment]
Known intermittent in the geckotry.

@bors-servo r=emilio

**Pull request merged**
