### PR TITLE
Remove patched webxr

### PR DESCRIPTION
**Pull request by Manishearth**
Unsure if this compiles yet, testing locally.

r? @jdm

### CODE REVIEW

**Comment by Manishearth** [comment]
Included in https://github.com/servo/servo/pull/24657

**Comment by jdm** [comment]
@bors-servo r-
This needs a `mach fmt`.

**Comment by Manishearth** [comment]
Looks like the sparkle update makes some webgl tests fail?

cc @pcwalton 

<details>

```
 (view as text)

{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: area outside scissor should be black\nat (0, 16) expected: 0,0,0,0 was 168,132,185,44 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\ntestCanvasSizeChange@http://web-platform.test:8000/_webgl/conformance/rendering/gl-scissor-canvas-dimensions.html:87:7\n@http://web-platform.test:8000/_webgl/conformance/rendering/gl-scissor-canvas-dimensions.html:93:1\n", 
    "subtest": "WebGL test #4: area outside scissor should be black\nat (0, 16) expected: 0,0,0,0 was 168,132,185,44", 
    "test": "/_webgl/conformance/rendering/gl-scissor-canvas-dimensions.html", 
    "line": 227306, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: area outside scissor should be black\nat (18, 0) expected: 0,0,0,0 was 3,0,0,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\ntestCanvasSizeChange@http://web-platform.test:8000/_webgl/conformance/rendering/gl-scissor-canvas-dimensions.html:88:7\n@http://web-platform.test:8000/_webgl/conformance/rendering/gl-scissor-canvas-dimensions.html:93:1\n", 
    "subtest": "WebGL test #5: area outside scissor should be black\nat (18, 0) expected: 0,0,0,0 was 3,0,0,0", 
    "test": "/_webgl/conformance/rendering/gl-scissor-canvas-dimensions.html", 
    "line": 227307, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (24, 2) expected: 0,0,0,0 was 81,101,0,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:60:9\n", 
    "subtest": "WebGL test #6: internal buffers have been initialized to 0\nat (24, 2) expected: 0,0,0,0 was 81,101,0,0", 
    "test": "/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html", 
    "line": 263271, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (24, 2) expected: 0,0,0,0 was 81,88,2,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:62:9\n", 
    "subtest": "WebGL test #12: internal buffers have been initialized to 0\nat (24, 2) expected: 0,0,0,0 was 81,88,2,0", 
    "test": "/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html", 
    "line": 263277, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (3, 1) expected: 0,0,0,0 was 113,94,2,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:59:9\n", 
    "subtest": "WebGL test #20: internal buffers have been initialized to 0\nat (3, 1) expected: 0,0,0,0 was 113,94,2,0", 
    "test": "/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html", 
    "line": 263285, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (38, 2) expected: 0,0,0,0 was 193,82,2,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:60:9\n", 
    "subtest": "WebGL test #26: internal buffers have been initialized to 0\nat (38, 2) expected: 0,0,0,0 was 193,82,2,0", 
    "test": "/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html", 
    "line": 263291, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (40, 2) expected: 0,0,0,0 was 97,81,2,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html:62:9\n", 
    "subtest": "WebGL test #32: internal buffers have been initialized to 0\nat (40, 2) expected: 0,0,0,0 was 97,81,2,0", 
    "test": "/_webgl/conformance/renderbuffers/stencil-renderbuffer-initialization.html", 
    "line": 263297, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (24, 2) expected: 0,0,0,0 was 81,102,0,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:60:9\n", 
    "subtest": "WebGL test #6: internal buffers have been initialized to 0\nat (24, 2) expected: 0,0,0,0 was 81,102,0,0", 
    "test": "/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html", 
    "line": 318389, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (32, 2) expected: 0,0,0,0 was 177,93,2,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:62:9\n", 
    "subtest": "WebGL test #12: internal buffers have been initialized to 0\nat (32, 2) expected: 0,0,0,0 was 177,93,2,0", 
    "test": "/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html", 
    "line": 318403, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (3, 1) expected: 0,0,0,0 was 49,93,2,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:59:9\n", 
    "subtest": "WebGL test #20: internal buffers have been initialized to 0\nat (3, 1) expected: 0,0,0,0 was 49,93,2,0", 
    "test": "/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html", 
    "line": 318420, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (2, 1) expected: 0,0,0,0 was 33,91,2,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:60:9\n", 
    "subtest": "WebGL test #26: internal buffers have been initialized to 0\nat (2, 1) expected: 0,0,0,0 was 33,91,2,0", 
    "test": "/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html", 
    "line": 318439, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: internal buffers have been initialized to 0\nat (40, 2) expected: 0,0,0,0 was 161,79,2,0 expected true got false", 
    "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/js/js-test-pre.js:123:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\nreportTestResultsToHarness@http://web-platform.test:8000/_webgl/js/js-test-pre.js:122:7\ntestFailed@http://web-platform.test:8000/_webgl/js/js-test-pre.js:249:5\ncheckCanvasRect/<@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1269:9\ncheckCanvasRectColor@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1225:9\ncheckCanvasRect@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1257:3\nrunTest@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:75:9\n@http://web-platform.test:8000/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html:62:9\n", 
    "subtest": "WebGL test #32: internal buffers have been initialized to 0\nat (40, 2) expected: 0,0,0,0 was 161,79,2,0", 
    "test": "/_webgl/conformance/renderbuffers/depth-renderbuffer-initialization.html", 
    "line": 318451, 
    "action": "test_result", 
    "expected": "PASS"
}

```

</details>

**Comment by asajeffrey** [comment]
Should we move over to the published surfman crate?

**Comment by Manishearth** [comment]
Yes

**Comment by asajeffrey** [comment]
We now have v1.1 of surfman-chains.

**Comment by jdm** [comment]
Are we prevented from upgrading surfman-chains because surfman's changes broke webgl tests again? :(

**Comment by Manishearth** [comment]
Annoyingly I can't reproduce that failure locally.

**Comment by Manishearth** [comment]
@bors-servo r=jdm

let's see how it goes with an updated sparkle

**Comment by Manishearth** [comment]
Same failures, chains update didn't fix things :/

cc @pcwalton @asajeffrey

**Comment by Manishearth** [comment]
@jdm should we just merge this with the expectations tweaked? It feels like we should move off the patch as soon as we can, and let Alan/Patrick take their time debugging the issue.

**Comment by jdm** [comment]
I would prefer if someone actually committed to doing that debugging before accepting the failures.

**Comment by asajeffrey** [comment]
I can have a look at the test failures.

**Comment by asajeffrey** [comment]
OK, so the problem is that surfman OSMesa doesn't call `OSMesaMakeCurrent` if you bind a surface to the current context, so subsequent calls to, e.g., `readPixels` use the old surface data.

A workaround is to add to https://github.com/Manishearth/servo/blob/unpatch/components/canvas/webgl_thread.rs#L588-L593:
```rust
            swap_chain
                .resize(&mut self.device, &mut data.ctx, size.to_i32())
                .expect("Failed to resize swap chain");
            self.device
                .make_context_current(&data.ctx)
                .expect("Failed to make context current again");
            swap_chain
                .clear_surface(&mut self.device, &mut data.ctx, &*data.gl)
                .expect("Failed to clear resized swap chain");
```

**Comment by Manishearth** [comment]
@bors-servo r=jdm

It being an OSMesa bug explains why I couldn't reproduce locally.

**Comment by asajeffrey** [comment]
I filed https://github.com/pcwalton/surfman/issues/35 if you want an issue to refer to.

**Comment by jdm** [comment]
@bors-servo retry
* https://github.com/servo/servo/issues/24611

**Comment by Manishearth** [comment]
OOM for mozjs build?

<details>

```
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x607A0000, RegionSize 0xE0000, State 0x10000
C:\Users\task_1573485483\repo\.servo\msvc-dependencies\moztools\3.2\msys\bin\pwd.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x607A0000, RegionSize 0xE0000, State 0x10000
C:\Users\task_1573485483\repo\.servo\msvc-dependencies\moztools\3.2\msys\bin\sh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
mozmake: *** [makefile.cargo:193: maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', C:\Users\task_1573485483\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\5906588\build.rs:133:5
```

</details>

@bors-servo retry

**Pull request merged**
