### PR TITLE
Update WR (dashed border clip fix, subpixel text + filter fixes).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20714)

### CODE REVIEW

**Comment by CYBAI** [comment]
```
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size-027.html 45774cd6c9eb8d6ebee90aebc0705356f74c931d\n/css/css-backgrounds/reference/background-size-027-ref.xht 0024c206b1bc33e4ac813ebc89459ae9e43ff5cc\nTesting 45774cd6c9eb8d6ebee90aebc0705356f74c931d == 0024c206b1bc33e4ac813ebc89459ae9e43ff5cc", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size-027.html", "line": 18290, "action": "test_result", "expected": "PASS"}
```

**Comment by nox** [comment]
@glennw Could you mark it as failing for now, so that we can r+ this PR? It's a test that recently started passing thanks to some changes from @nical, so I don't think it's bad if we just mark it as failing again.

**Comment by glennw** [comment]
@nox I can't right now - but you should have permissions to push to this branch (or open a new PR) if you want it done before I get to it tomorrow.

**Comment by nox** [comment]
Ok no problem! Have a good night. :)

**Comment by nox** [comment]
Filed #20733 for the other failure.

**Comment by nox** [comment]
#20732

**Pull request closed without merging**
