### PR TITLE
Correct unicode handling for text input

### LINKED ISSUE #15819: panic when deleting non-ascii character
#### Step to reproduce

- ``` ./mach run -d test.html ```
*test.html:*
    ```html
     <input value="çççççççççççç"></input>
     ```
 - click on the middle of the strings.
    - The cursor move at the wrong place (first bug)
    - Example: 
 ```
çççççç|çççççç
          ^ clicked here
ççç|ççççççççç
     ^ cursor here
```

- delete one ```ç```. Get a panic:
```
byte index 5 is not a char boundary; it is inside 'ç' (bytes 4..6) of `çççççççççççç` (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at /checkout/src/libcore/str/mod.rs:1771)
stack backtrace:
   0:     0x55c820518ce1 - backtrace::backtrace::libunwind::trace
                        at /home/charles/Dev/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /home/charles/Dev/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.0/src/backtrace/mod.rs:42
   1:     0x55c820513f84 - backtrace::capture::{{impl}}::new
                        at /home/charles/Dev/servo/target/debug/build/backtrace-17fa5380aeaf9437/out/capture.rs:79
   2:     0x55c81bf220c6 - servo::main::{{closure}}
                        at /home/charles/Dev/servo/ports/servo/main.rs:123
   3:     0x55c8214b6dcd - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:546
   4:     0x55c8214b6c14 - std::panicking::begin_panic<collections::string::String>
                        at /checkout/src/libstd/panicking.rs:507
   5:     0x55c8214b6b89 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:491
   6:     0x55c8214b6b17 - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:467
   7:     0x55c8214e37ed - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:69
   8:     0x55c8214e4810 - core::str::slice_error_fail
                        at /checkout/src/libcore/str/mod.rs:1771
   9:     0x55c81dda0114 - core::str::traits::{{impl}}::index
                        at /checkout/src/libcore/str/mod.rs:1491
  10:     0x55c81e0e88bb - script::textinput::{{impl}}::adjust_horizontal_by_one<ipc_channel::ipc::IpcSender<script_traits::script_msg::ScriptMsg>>
                        at /home/charles/Dev/servo/components/script/textinput.rs:389
  11:     0x55c81e0e644f - script::textinput::{{impl}}::delete_char<ipc_channel::ipc::IpcSender<script_traits::script_msg::ScriptMsg>>
                        at /home/charles/Dev/servo/components/script/textinput.rs:173
  12:     0x55c81e0e917e - script::textinput::{{impl}}::handle_keydown_aux<ipc_channel::ipc::IpcSender<script_traits::script_msg::ScriptMsg>>
                        at /home/charles/Dev/servo/components/script/textinput.rs:510
  13:     0x55c81e0e9006 - script::textinput::{{impl}}::handle_keydown<ipc_channel::ipc::IpcSender<script_traits::script_msg::ScriptMsg>>
                        at /home/charles/Dev/servo/components/script/textinput.rs:474
  14:     0x55c81e0522b3 - script::dom::htmlinputelement::{{impl}}::handle_event
                        at /home/charles/Dev/servo/components/script/dom/htmlinputelement.rs:1129
  15:     0x55c81d0af428 - script::dom::event::{{impl}}::dispatch
                        at /home/charles/Dev/servo/components/script/dom/event.rs:158
  16:     0x55c81d0b30c8 - script::dom::eventtarget::{{impl}}::dispatch_event
                        at /home/charles/Dev/servo/components/script/dom/eventtarget.rs:306
  17:     0x55c81d0afa8a - script::dom::event::{{impl}}::fire
                        at /home/charles/Dev/servo/components/script/dom/event.rs:220
  18:     0x55c81d5b404e - script::dom::document::{{impl}}::dispatch_key_event
                        at /home/charles/Dev/servo/components/script/dom/document.rs:1328
  19:     0x55c81e0da8fb - script::script_thread::{{impl}}::handle_event
                        at /home/charles/Dev/servo/components/script/script_thread.rs:1918
  20:     0x55c81e0c824a - script::script_thread::{{impl}}::handle_msg_from_constellation
                        at /home/charles/Dev/servo/components/script/script_thread.rs:979
  21:     0x55c81e0c678c - script::script_thread::{{impl}}::handle_msgs::{{closure}}
                        at /home/charles/Dev/servo/components/script/script_thread.rs:870
  22:     0x55c81e0c71f1 - script::script_thread::{{impl}}::profile_event<closure,core::option::Option<bool>>
                        at /home/charles/Dev/servo/components/script/script_thread.rs:970
  23:     0x55c81e0c4fcf - script::script_thread::{{impl}}::handle_msgs
                        at /home/charles/Dev/servo/components/script/script_thread.rs:864
  24:     0x55c81e0c3805 - script::script_thread::{{impl}}::start
                        at /home/charles/Dev/servo/components/script/script_thread.rs:719
  25:     0x55c81d134214 - script::script_thread::{{impl}}::create::{{closure}}::{{closure}}
                        at /home/charles/Dev/servo/components/script/script_thread.rs:557
  26:     0x55c81cbe9c26 - profile_traits::mem::{{impl}}::run_with_memory_reporting<closure,fn(profile_traits::mem::ReportsChan) -> script::script_runtime::CommonScriptMsg,script::script_runtime::CommonScriptMsg,std::sync::mpsc::Sender<script::script_thread::MainThreadScriptMsg>>
                        at /home/charles/Dev/servo/components/profile_traits/mem.rs:63
  27:     0x55c81e679ad9 - script::script_thread::{{impl}}::create::{{closure}}
                        at /home/charles/Dev/servo/components/script/script_thread.rs:556
  28:     0x55c81e61209a - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  29:     0x55c81e51ac12 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:450
  30:     0x55c8214bdd9a - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  31:     0x55c81e357353 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:429
  32:     0x55c81e273b54 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  33:     0x55c81db61c00 - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:357
  34:     0x55c81ddf8bf2 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:638
  35:     0x55c8214b5a14 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:648
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
  36:     0x7f3de31f4453 - start_thread
  37:     0x7f3de2d207de - __GI___clone
  38:                0x0 - <unknown>
ERROR:servo: byte index 5 is not a char boundary; it is inside 'ç' (bytes 4..6) of `çççççççççççç`
```

Looks like unicode character are badly supported on HTMLInputElement.

### PR DESCRIPTION
**Pull request by charlesvdv**
Allow proprer handling of unicode sequence in text input.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15819 

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15822)

### CODE REVIEW

**Comment by emilio** [comment]
Looks fine, any chance we could add a test for this?

**Comment by emilio** [comment]
Hmm... I guess adding a WPT that is reliable is not super-simple, and I don't think we support a bunch of other APIs that could help.

It seems to me you could fake a mouse event on the text input though.

**Comment by charlesvdv** [comment]
@emilio I will do that 👍

**Comment by charlesvdv** [comment]
@emilio where should this test be added ?

**Comment by emilio** [comment]
Just for reference, since I think I mentioned it on IRC at the time, `tests/wpt/mozilla/tests` seems like a good place. Sorry if I didn't though.

**Comment by jdm** [comment]
@charlesvdv Are you planning to return to this work?

**Comment by charlesvdv** [comment]
Yep sorry but I can't manage do get the test working :/ For the moment I created this but this doesn't work neither on Firefox or Servo.
``` html
<!doctype html>
<meta charset='utf-8'>
<title></title>
<script src='/resources/testharness.js'></script>
<script src='/resources/testharnessreport.js'></script>
<input id='inp' value='éàèù'> </input>
<script>
    var input = document.getElementById('inp');

    document.addEventListener('DOMContentLoaded', function() {
        input.focus();
        input.click();

        var evtDelete = new KeyboardEvent('keypress', { 'key': 'Backspace', 'code': 'Backspace' });
        input.dispatchEvent(evtDelete);
    });
</script>
```

**Comment by jdm** [comment]
I don't think we can write a WPT test for this right now. I recommend adding to the unit tests in `tests/unit/script/textinput.rs` instead.

**Comment by charlesvdv** [comment]
Ok I will do it! 😄

**Comment by emilio** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
