### PR TITLE
CSSOM: Make Stylesheet fields have their own synchronization

### PR DESCRIPTION
**Pull request by SimonSapin**
r? @upsuper 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix bug 1314208.

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14232)

### CODE REVIEW

**Comment by upsuper** [comment]
I wonder whether we still want to wrap `Stylesheet` into `Arc<RwLock<_>>`, given that in #14190 `rules` is now wrapped in `Arc<RwLock<_>>`.

Wrapping `Stylesheet.media` is still needed, though.

**Comment by SimonSapin** [comment]
You’re right. With other fields being already behind their own `RwLock` or immutable in CSSOM, this leaves `dirty_on_viewport_size_change`. I’ll make it an `AtomicBool`. We’ll need to add code to update it in various CSSOM mutating methods, though.

**Comment by SimonSapin** [comment]
Updated.

**Review by upsuper — APPROVED** [review]
This looks good to me, but I cannot really approve this. Probably r? @Manishearth

**Comment by KiChjang** [comment]
@bors-servo delegate=upsuper

Now you can!

**Comment by upsuper** [comment]
I'll try to do a more careful review then.

**Comment by SimonSapin** [comment]
@bors-servo retry

* #13776

**Comment by KiChjang** [comment]
@bors-servo retry
* #14267

**Comment by KiChjang** [comment]
@bors-servo retry
* #12797

**Pull request merged**
