### PR TITLE
Update ws to 0.7.8

### PR DESCRIPTION
**Pull request by Eijebong**
This makes some mor tests pass as it now handles basic authentication

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21426)

### CODE REVIEW

**Comment by jdm** [comment]
You will want to pull the WPT result changes from https://github.com/servo/servo/pull/21356 which also includes a url crate update.

**Comment by jdm** [comment]
```

  ▶ Unexpected subtest result in /url/failure.html:
  └ PASS [expected FAIL] URL's constructor's base argument: https://0x100000000/test should throw

  ▶ Unexpected subtest result in /url/failure.html:
  └ PASS [expected FAIL] URL's href: https://0x100000000/test should throw

  ▶ Unexpected subtest result in /url/failure.html:
  └ PASS [expected FAIL] XHR: https://0x100000000/test should throw

  ▶ Unexpected subtest result in /url/failure.html:
  └ PASS [expected FAIL] Location's href: https://0x100000000/test should throw
```

**Comment by asajeffrey** [comment]
Over in #21607 I temporarily disabled duplicate-checking for the `slab` package, because `mio` and `ws` have different requirements for it. This PR can remove that entry from `servo-tidy.toml`.

**Pull request closed without merging**
