### PR TITLE
Integrate font-variation-settings descriptor with stylo

### PR DESCRIPTION
**Pull request by upsuper**
This is the Servo side change for [bug 1435984](https://bugzilla.mozilla.org/show_bug.cgi?id=1435984).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20042)

### CODE REVIEW

**Comment by upsuper** [comment]
```
LLVM ERROR: IO failure on output stream.
error: Could not compile `geckoservo`.
```
...?

**Comment by bholley** [comment]
thread 'bindings::root::bindgen_test_layout_nsCSSFontFaceRule' panicked at 'assertion failed: `(left == right)`
  left: `256`,
 right: `240`: Size of: nsCSSFontFaceRule', /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-4b43331712e911df/out/gecko/structs.rs:37619:8

**Comment by upsuper** [comment]
Manual adjusting binding files is hard :/ I probably should copy that from try server and rustfmt it from the beginning... I didn't do that because I need to run rustfmt for it, and rustfmt reports errors... maybe it's not that bad I guess...

**Pull request merged**
