### PR TITLE
Use symlink for resources in embedder_traits

### LINKED ISSUE #31838: embedder_traits fails to compile when vendored due to resource files missing
Sub task of #31812.

This happens because when vendoring all crates are flattened to `vendor/crate_name` so resource path is not even checked out. I think we need to make resources live in `components/shared/embedder` so they will be included when vendoring (does vendoring follows links?).

All compilation errors:
```
error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/prefs.json: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:121:43
    |
121 |                 Resource::Preferences => &include_bytes!("../../../resources/prefs.json")[..],
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/gatt_blocklist.txt: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:123:22
    |
123 |                     &include_bytes!("../../../resources/gatt_blocklist.txt")[..]
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/public_domains.txt: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:126:22
    |
126 |                     &include_bytes!("../../../resources/public_domains.txt")[..]
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/hsts_preload.json: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:129:22
    |
129 |                     &include_bytes!("../../../resources/hsts_preload.json")[..]
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/badcert.html: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:131:43
    |
131 |                 Resource::BadCertHTML => &include_bytes!("../../../resources/badcert.html")[..],
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/neterror.html: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:132:44
    |
132 |                 Resource::NetErrorHTML => &include_bytes!("../../../resources/neterror.html")[..],
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/user-agent.css: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:133:44
    |
133 |                 Resource::UserAgentCSS => &include_bytes!("../../../resources/user-agent.css")[..],
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/servo.css: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:134:40
    |
134 |                 Resource::ServoCSS => &include_bytes!("../../../resources/servo.css")[..],
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/presentational-hints.css: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:136:22
    |
136 |                     &include_bytes!("../../../resources/presentational-hints.css")[..]
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/quirks-mode.css: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:139:22
    |
139 |                     &include_bytes!("../../../resources/quirks-mode.css")[..]
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/rippy.png: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:141:40
    |
141 |                 Resource::RippyPNG => &include_bytes!("../../../resources/rippy.png")[..],
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/media-controls.css: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:143:22
    |
143 |                     &include_bytes!("../../../resources/media-controls.css")[..]
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/media-controls.js: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:146:22
    |
146 |                     &include_bytes!("../../../resources/media-controls.js")[..]
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read /home/user/Desktop/verso/vendor/embedder_traits/../../../resources/crash.html: No such file or directory (os error 2)
   --> /home/user/Desktop/verso/vendor/embedder_traits/resources.rs:148:41
    |
148 |                 Resource::CrashHTML => &include_bytes!("../../../resources/crash.html")[..],
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by sagudev**
I manually tested and it works.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #31838 

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by mrobinson** [comment]
@sagudev Will this work on Windows?

**Comment by sagudev** [comment]
> @sagudev Will this work on Windows?

I think it should as they are soft links, let's test it in CI.

**Comment by sagudev** [comment]
It might require additional work I guess: https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/59761201#59761201, but alternative is to move folders to respective crates or just keep `cargo vendor` broken for embeddeders.

**Comment by sagudev** [comment]
I just tested on my windows machine and it works after https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/59761201#59761201 and fresh git clone. GitHub runners seems to support them out of the box.

**Comment by mrobinson** [comment]
So this works, but based on the StackOverflow comment above it looks like this requires careful configuration of Git and a very new Git version. This means weighing the three options that all have downsides:

1. Keep current configuration: `cargo vendor` is broken (though this is an uncommon build configuration).
2. Add the symlink: Potentially breaking things for folks who haven't set up Windows properly or have an older version of Git. This could lead to lots of new bug reports from people building in the usual way on Windows.
3. Move the resources: The files are now in a slightly odd place in the repository.

My tendency is to go with 3 or 1. 3 introduces some awkwardness to the repository, but it doesn't cause potential breakage for anyone. 1 is probably okay IMO as well, since we don't *need* to support `cargo vendor`. We do need to build reliably on Windows though.

**Comment by sagudev** [comment]
I do not think git version is the problematic part (we are in 2024), but developer mode and setting git can still be problematic on platform that is already hard as is (also the need for new clone).

If we go with 3 that would meant that we need to also move webidl,ply to components/script folder (what we actually had before `third_party`) and potentially more as I did not found out if there are any more problematic stuff. So here is that to consider.

**Comment by mrobinson** [comment]
It sounds a bit like the easiest thing would be to officially not support `cargo vendor`.

**Comment by fgaz** [comment]
Could this be reconsidered? In [Nix](https://nixos.org) we use `cargo vendor` to build rust packages, so this is an obstacle to packaging any servo-based browser

**Comment by sagudev** [comment]
> Could this be reconsidered? In [Nix](https://nixos.org) we use `cargo vendor` to build rust packages, so this is an obstacle to packaging any servo-based browser

See https://github.com/servo/servo/issues/31812 for issue and https://github.com/servo/servo/pull/33502#discussion_r1780847936 for some latest discussion.

**Pull request closed without merging**
