### PR TITLE
Add bindings support for unrestricted float/double values.

### LINKED ISSUE #707: Add bindings support for unrestricted float values
This error happen on parsing HTMLMediaElement.webidl.
HTMLMediaElement.webidl: http://mxr.mozilla.org/mozilla-central/source/dom/webidl/HTMLMediaElement.webidl

```
Traceback (most recent call last):
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/pythonpath.py", line 60, in <module>
    main(sys.argv[1:])
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/pythonpath.py", line 52, in main
    execfile(script, frozenglobals)
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/GlobalGen.py", line 88, in <module>
    main()
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/GlobalGen.py", line 66, in main
    parser.parse(''.join(lines), fullPath)
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/parser/WebIDL.py", line 3885, in parse
    self._productions.extend(self.parser.parse(lexer=self.lexer,tracking=True))
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/ply/ply/yacc.py", line 263, in parse
    return self.parseopt(input,lexer,debug,tracking,tokenfunc)
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/ply/ply/yacc.py", line 792, in parseopt
    tok = self.errorfunc(errtoken)
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/parser/WebIDL.py", line 3835, in p_error
    raise WebIDLError("invalid syntax", [Location(self.lexer, p.lineno, p.lexpos, self._filename)])
WebIDL.WebIDLError: error: invalid syntax, /Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/HTMLMediaElement.webidl line 55:34
  readonly attribute unrestricted double duration;
                                  ^
make: *** [/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/ParserResults.pkl] Error 1
```

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
Fix #707

### CODE REVIEW

**Comment by saneyuki** [comment]
Why tests are fails is that CanvasRenderingContext2D's almost methods should take `unrestricted double` by [the spec](http://www.w3.org/html/wg/drafts/2dcontext/html5_canvas_CR/#canvasrenderingcontext2d), but the current servo's idl uses [`double`](https://github.com/servo/servo/blob/9eaa48b793de78b713e6c3a3c79c4060084d5fbe/components/script/dom/webidls/CanvasRenderingContext2D.webidl) to avoid to not support unrestricted values. 

So I'll update its idl.

**Comment by jdm** [comment]
Good find :)

**Comment by saneyuki** [comment]
@jdm @Ms2ger plaese review these?:

* https://github.com/saneyuki/servo/commit/07581de6382176cd0833ded3900042f1767bba2f
* https://github.com/saneyuki/servo/commit/5f8c893a71a2b830226235e5d85757754424b21f
* https://github.com/saneyuki/servo/commit/27233d17401edb9ec9adc353fe6f4125fe1d7b44

**Comment by saneyuki** [comment]
This pull request doesn't include to support to throw `TypeError` when [`float`][float]/[`double`][double] is `NaN` or `+-In` in WebIDL.

[float]: http://heycam.github.io/webidl/#es-float
[double]: http://heycam.github.io/webidl/#es-double

**Comment by Ms2ger** [comment]
"Except where otherwise specified, for the 2D context interface, any method call with a numeric argument whose value is infinite or a NaN value must be ignored."

**Comment by jdm** [comment]
These changes look good, but as quoted we should add early returns to those methods if the arguments are not finite. I'm fine with filing the type error bits as a follow up easy bug.

**Comment by saneyuki** [comment]
I'll open a new pull request to take over this.

**Pull request closed without merging**
