### PR TITLE
pass -vv through mach to cargo

### LINKED ISSUE #17231: The build tool passes -vv to cargo as -v
Running `./mach build -d -j 1 -vv` executes `cargo build -j 1 -v` when IMO it should execute `cargo build -j 1 -vv`.

### PR DESCRIPTION
**Pull request by tigercosmos**
base on #17237, which is reviewed by emilio and jdm.
just need to rename commit and rebase

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17231 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19633)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r+

Thanks!

**Review by emilio — APPROVED** [review]

**Comment by tigercosmos** [comment]
I click a wrong button ...

**Comment by tigercosmos** [comment]
@emilio  could you r+ again?

**Pull request merged**
