### PR TITLE
Consider media attribute on link and style tags

### PR DESCRIPTION
**Pull request by cyndis**
Don't add a stylesheet if the current device does not match the media
query specified in a link or style tag.

Cheers,
cyndis

### CODE REVIEW

**Comment by jdm** [comment]
I apologize for allowing this to get lost in the shuffle! I've reviewed the changes on Critic; nice work! There's one little style nit to fix, but the rest looks great to me.

**Comment by cyndis** [comment]
Thanks for reviewing! I moved the NodeCast use to the previous line.

**Comment by jdm** [comment]
Looks good! Go ahead and squash them together :)

**Comment by cyndis** [comment]
Squashed

**Pull request merged**
