### PR TITLE
implement shadow_check_callback in script_task

### LINKED ISSUE #8333: Implement shadow_check_callback
Our code is in `components/script/script_task.rs`; Gecko's equivalent is at https://mxr.mozilla.org/mozilla-central/source/dom/bindings/DOMJSProxyHandler.cpp?rev=a849e759a0f7#34.

Right now we always return `ShadowCheckFailed`; perhaps @bzbarsky knows if this is simply causing awful performance, or if it also causes detectable behaviour changes.

### PR DESCRIPTION
**Pull request by ajnirp**
Fixes #8333

this requires servo/rust-mozjs#218

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8563)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Fails tidy

**Comment by michaelwu** [comment]
This is a bit tricky - I remember looking at this and thinking that it can't be implemented correctly without handling ExpandoAndGeneration on DOM objects that need it.

**Comment by Ms2ger** [comment]
Any chance you could try to write some tests that cover this?

**Comment by jdm** [comment]
@Ms2ger Given that 
1) I'm not even clear when this callback is invoked, or what the results mean
2) Every bug and commit I've looked at for lines related to the shadow check in Gecko contain either no tests or no mochitests
it seems a bit unrealistic to expect @wenderen to "write some tests" with no further guidance.

**Comment by Ms2ger** [comment]
I've been looking into it, and bz was so kind to make me realize that we don't tell SM about the proxy family we use for DOM proxies. (This is the first argument to `SetDOMProxyInformation`.) Unfortunately, the family is the `HandlerFamily` constant in `jsglue.cpp` in rust-mozjs.

I would prefer we fixed that first, so this isn't just dead code. According to bz,
```js
for (var i = 0; i < 100000; ++i) {
  document.getElementById("x")
}
```
should land us in the callback once that's fixed. @wenderen, would you be willing to work on that?

**Comment by wenderen** [comment]
@Ms2ger sure I'll look into adding some tests. Thanks for the suggestions.

**Comment by jdm** [comment]
Closing due to lack of updates.

**Pull request closed without merging**
