### PR TITLE
Removed JS::root #8251

### LINKED ISSUE #8251: Remove JS::root.
The method is defined in `components/script/dom/bindings/js.rs`.

It should be possible to remove most calls altogether, and use the `JS<T>` where the `Root<T>` return value is currently used. When that isn't possible, `Root::from_ref(&*js)` should work.

### PR DESCRIPTION
**Pull request by nxnfufunezn**
Fixes #8251 

r? @Ms2ger

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8262)

### CODE REVIEW

**Comment by Ms2ger** [comment]
r+ modulo fixes in https://github.com/nxnfufunezn/servo/pull/2

r? @jdm

**Comment by nxnfufunezn** [comment]
@Ms2ger merged!

**Comment by Ms2ger** [comment]
Looking great, I just noticed three small nits I missed earlier.

-S-awaiting-review -S-blocked-on-external -S-needs-squash +S-needs-code-changes 


---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[components/script/dom/htmlcollection.rs, line 167 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8262#-K1xpyk8fi06VPtkmsbK)** ([raw file](https://github.com/servo/servo/blob/d0aaeb96440f8498e8d6d037a92b85837a1165f6/components/script/dom/htmlcollection.rs#L167)):</sup>
These inner parentheses aren't necessary.


---

<sup>**[components/script/dom/htmlelement.rs, line 364 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8262#-K1xq6kljufoDeY5Lgjz)** ([raw file](https://github.com/servo/servo/blob/d0aaeb96440f8498e8d6d037a92b85837a1165f6/components/script/dom/htmlelement.rs#L364)):</sup>
If you remove the `r()` here, you can remove the `map(|js| Root::from_ref(&**js))` as well.


---

<sup>**[components/script/dom/namednodemap.rs, line 90 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8262#-K1xqFkfLhjIAMizBO4l)** ([raw file](https://github.com/servo/servo/blob/d0aaeb96440f8498e8d6d037a92b85837a1165f6/components/script/dom/namednodemap.rs#L90)):</sup>
Remove the first `map()`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8262)

**Comment by Ms2ger** [comment]
@bors-servo r+ p=1 force


---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8262)

**Pull request merged**
