### PR TITLE
Implement step 6 of media `time marches on` algorithm. Improves stability of media WPTs

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

This should help with the WPTs problems observed in https://github.com/servo/servo/pull/22348#issuecomment-446369831

Unfortunately, GStreamer does not seem to be very reliable with Ogg (check https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/issues/520) and most of the media-element WPTs uses a short ogv file, so I had to make our `canPlayType` report that it is not able to play this type to make the tests pick the alternative mp4 version of the same files. Once Ogg support for GStreamer improves, we should be able to revert this change.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22477)

### CODE REVIEW

**Comment by ferjm** [comment]
@bors-servo retry
- #21666

**Comment by CYBAI** [comment]
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "event is not defined", 
    "stack": "video.onerror<@http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/track-active-cues.html:27:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1566:20\nTest.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1606:17\n", 
    "subtest": "Ensure that no text track cues are active after the video is unloaded", 
    "test": "/html/semantics/embedded-content/media-elements/track/track-element/track-active-cues.html", 
    "line": 128244, 
    "action": "test_result", 
    "expected": "TIMEOUT"
}
{
    "status": "OK", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/track/track-element/track-active-cues.html", 
    "line": 128245, 
    "action": "test_result", 
    "expected": "TIMEOUT"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": "Test timed out", 
    "stack": null, 
    "subtest": "Removing a track by setting video.innerHTML doesn't crash", 
    "test": "/html/semantics/embedded-content/media-elements/track/track-element/track-remove-by-setting-innerHTML.html", 
    "line": 132195, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/track/track-element/track-remove-by-setting-innerHTML.html", 
    "line": 132196, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": "Test timed out", 
    "stack": null, 
    "subtest": "Cue fragment is mutable", 
    "test": "/html/semantics/embedded-content/media-elements/track/track-element/track-cue-mutable-fragment.html", 
    "line": 132607, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/track/track-element/track-cue-mutable-fragment.html", 
    "line": 132608, 
    "action": "test_result", 
    "expected": "OK"
}
```

**Comment by ferjm** [comment]
```
  │ 0:00:00.052853469 110152 0x7f530c4155e0 ERROR             gst-player gstplayer.c:1139:emit_warning:<player0> Warning: Warning from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0: There is no codec present that can handle the stream's type.
  │ No decoder available for type 'video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)3, profile=(string)constrained-baseline, codec_data=(buffer)0142c01effe100176742c01e9a720283f60220000003002000000611e2c5c901000568ce06cb20, width=(int)320, height=(int)240, framerate=(fraction)24/1, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true'.
```

We need to update GStreamer on CI to include the missing plugin :|

**Comment by ferjm** [comment]
The missing plugin seems to be `gst-libav`. Working on getting the new binaries for CI.

```
servo@vagrant-ubuntu-trusty-64:~$ gst-inspect-1.0 |grep x-h264
typefindfunctions: video/x-h264: h264, x264, 264
servo@vagrant-ubuntu-trusty-64:~$ gst-inspect-1.0 avdec_h264
No such element or plugin 'avdec_h264'
```

**Comment by ferjm** [comment]
I fixed this locally, but I am having troubles uploading the binaries to S3.

We already had `gst-libav` along with the rest of required plugins on CI, but we were missing some ffmpeg dependencies

```
servo@vagrant-ubuntu-trusty-64:~$ gst-inspect-1.0 /home/servo/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so

(gst-inspect-1.0:25278): GStreamer-WARNING **: Failed to load plugin '/home/servo/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so': libavfilter.so.7: cannot open shared object file: No such file or directory
Could not load plugin file: Opening module failed: libavfilter.so.7: cannot open shared object file: No such file or directory

servo@vagrant-ubuntu-trusty-64:~$ ldd /home/servo/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so
	linux-vdso.so.1 =>  (0x00007ffe2aaf2000)
	libgstreamer-1.0.so.0 => /home/servo/gstreamer/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007f24f5ea6000)
	libgstbase-1.0.so.0 => /home/servo/gstreamer/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007f24f5c32000)
	libgstvideo-1.0.so.0 => /home/servo/gstreamer/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007f24f59ac000)
	libgstaudio-1.0.so.0 => /home/servo/gstreamer/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0 (0x00007f24f573f000)
	libgstpbutils-1.0.so.0 => /home/servo/gstreamer/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0 (0x00007f24f5507000)
	libavfilter.so.7 => not found
	libavformat.so.58 => not found
	libavcodec.so.58 => not found
	libavutil.so.56 => not found
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f24f51ff000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f24f4fae000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f24f4d90000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f24f49c7000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f24f47c3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f24f44bd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f24f42b9000)
	libgsttag-1.0.so.0 => /home/servo/gstreamer/lib/x86_64-linux-gnu/libgsttag-1.0.so.0 (0x00007f24f4080000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f24f3e42000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f24f3c3a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f24f6418000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f24f3a21000)
```

I've updated https://github.com/servo/servo/wiki/How-to-generate-GStreamer-binaries-for-Travis-(Ubuntu-Trusty) accordingly.

**Comment by ferjm** [comment]
Oh gosh...

```
  │ 0:00:00.043080348 61918 0x7f9ba44095e0 ERROR             gst-player gstplayer.c:1139:emit_warning:<player0> Warning: Warning from element /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0: There is no codec present that can handle the stream's type.
  │ No decoder available for type 'audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)2, layer=(int)3, rate=(int)22050, channels=(int)1, parsed=(boolean)true'.
  │ ../subprojects/gst-plugins-base/gst/playback/gsturidecodebin.c(921): unknown_type_cb (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0 (gst-player-error-quark, 0)
  │ 0:00:00.043580538 61918 0x7f9b5002d230 WARN            uridecodebin gsturidecodebin.c:988:no_more_pads_full:<uridecodebin0> error: no suitable plugins found:
  │ ../subprojects/gst-plugins-base/gst/playback/gstdecodebin2.c(4640): gst_decode_bin_expose (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:
  │ no suitable plugins found:
  │ Missing decoder: MPEG-1 Layer 3 (MP3) (audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)2, layer=(int)3, rate=(int)22050, channels=(int)1, parsed=(boolean)true)
```

More missing decoders.

**Comment by ferjm** [comment]
With https://github.com/servo/saltfs/pull/937/commits/1ec4e8f51af0173ee12a20f76c6e1463f418e754 I am able to play an mp4 file on servo-linux1.servo.org

```
gst-play-1.0 movie_5.mp4
Press 'k' to see a list of keyboard shortcuts.
Now playing /tmp/movie_5.mp4
Redistribute latency...
Redistribute latency...
Redistribute latency...
0:00:00.8 / 0:00:05.1
```

@bors-servo try=wpt

**Pull request merged**
