### PR TITLE
Update to cargo 0.17.0-nightly (385e243 2017-01-27)

### PR DESCRIPTION
**Pull request by SimonSapin**
Pick up https://github.com/rust-lang/cargo/pull/3590, to print errors without waiting for parallel jobs.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require new tests

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15277)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
GeckoLib build completed in 0:02:23
LLVM ERROR: IO failure on output stream.
error: Could not compile `geckoservo`.

To learn more, run the command again with --verbose.
```

Let’s see if it’s a temporary thing:

@bors-servo try retry

**Comment by SimonSapin** [comment]
@bors-servo try

With `--verbose` added.

**Comment by SimonSapin** [comment]
Ok, so it looks like the final rustc invocation (below) prints "LLVM ERROR: IO failure on output stream." then exists with status code 1.

The range of Cargo changes is https://github.com/rust-lang/cargo/compare/6291619896fc6a83d619945148670b6420aa06ec...385e24360dc2c714e5f14bcc0e54afb87fc042d3

> `rustc --crate-name geckoservo lib.rs --crate-type staticlib --crate-type rlib --emit=dep-info,link -C codegen-units=4 -C debuginfo=2 -C metadata=e50e85bcc1b97142 -C extra-filename=-e50e85bcc1b97142 --out-dir C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps -L dependency=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps --extern lazy_static=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\liblazy_static-cdc27b3838abea72.rlib --extern selectors=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libselectors-15cf41946cfff98b.rlib --extern parking_lot=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libparking_lot-954f6d3bf6d4e2c7.rlib --extern servo_url=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libservo_url-6f8bef027c9bb5eb.rlib --extern style=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libstyle-40c665b2aad2742f.rlib --extern cssparser=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libcssparser-450288f50f114a7f.rlib --extern atomic_refcell=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libatomic_refcell-8ca19a786e0e078c.rlib --extern libc=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\liblibc-63a6b9527932ce3d.rlib --extern env_logger=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libenv_logger-1ad4007fc38d23ae.rlib --extern log=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\liblog-644e3c12ff33c18f.rlib --extern num_cpus=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libnum_cpus-a698a88c6ba8c5a0.rlib --extern style_traits=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libstyle_traits-3e26c66e4df6fac1.rlib --extern euclid=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libeuclid-d4cd13d1cb9c3b3f.rlib --extern app_units=C:\buildbot\slave\windows-gnu-dev\build\target\geckolib\debug\deps\libapp_units-f13a9ce245a65974.rlib -W unused-extern-crates`

**Comment by SimonSapin** [comment]
Downgrading Cargo a bit to try and narrow the range.

@bors-servo try

**Comment by jdm** [comment]
Keep in mind https://github.com/servo/saltfs/issues/585; this is not necessarily a cargo problem.

**Comment by SimonSapin** [comment]
Ah, I didn’t know about that. Thanks.

**Comment by SimonSapin** [comment]
https://github.com/servo/saltfs/issues/585 (lack of disk space on the CI server) is closed.

@bors-servo r=emilio

**Pull request merged**
