### PR TITLE
style: Rewrite the restyle hints code to allow different kinds of element snapshots.

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] These changes do not require tests because refactoring.

This is a rewrite for how style interfaces with its consumers in order to allow
different representations for an element snapshot.

This also changes the requirements of an element snapshot, requiring them to
only implement MatchAttr, instead of MatchAttrGeneric. This is important for
stylo since implementing MatchAttrGeneric is way more difficult for us given the
atom limitations. This also allows for more performant implementations in the
Gecko side of things.

I don't want to get this merged just yet, mainly because the stylo part is not
implemented, but I'd like early feedback from @bholley and/or @heycam: How do
you see this approach? I don't think we'll have much problem to implement
MatchAttr for our element snapshots, but... worth checking.

r? @heycam

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12469)

### CODE REVIEW

**Comment by nox** [comment]
Do we really need yet another "Servo" prefix? :(

**Comment by emilio** [comment]
This is basically ready for review... r? @bholley or @heycam 

Relevant gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1287951

**Comment by emilio** [comment]
@SimonSapin: This kind of conflicts with your current efforts to use conditional compilation in style. I don't expect this to be a *lot* of breakage (the only relevant changes for that are the restyle_hints.rs file, and the implementation added in geckolib), though could you please check?

I don't mind holding this off for a bit and rebase if your changes are landing soon :)

**Comment by SimonSapin** [comment]
I tried merging this PR into https://github.com/servo/servo/pull/12515 (which I just submitted) and got conflicts in:

* `ports/geckolib/wrapper.rs`
* `ports/geckolib/glue.rs`
* `components/style/selector_matching.rs`
* `components/style/selector_impl.rs`
* `components/style/restyle_hints.rs`
* `components/script/dom/document.rs`

I haven’t looked in more details than that.

**Comment by emilio** [comment]
@SimonSapin: Then don't bother about it, I'll do the rebase :)

**Comment by bholley** [comment]
Reviewed 13 of 14 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/style/selector_impl.rs, line 82 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDdSevQYnIaBAEaYBz:-KNDdSevQYnIaBAEaYC-:-814740450) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/components/style/selector_impl.rs#L82)):*
> ```Rust
> 
> // NB: The `Clone` trait is here for convenience due to:
> // https://github.com/rust-lang/rust/issues/26925
> ```

This text appears twice...

---

*[ports/geckolib/glue.rs, line 452 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDf5NEauAbkbq4MkfN:-KNDf5NEauAbkbq4MkfO:624910216) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/glue.rs#L452)):*
> ```Rust
>     let element = unsafe { GeckoElement::from_raw(element) };
> 
>     // NB: This involves an FFI call, we can take rid of it easily if needed.
> ```

Nit: "get rid of".

---

*[ports/geckolib/glue.rs, line 459 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDfAfO-z_lJerUYIZw:-KNDfAfO-z_lJerUYIZx:-1649916585) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/glue.rs#L459)):*
> ```Rust
>                                                  current_state);
> 
>     // NB: Binaries representation match.
> ```

Do we have an enforcement mechanism for this somewhere? If not, please file a bug so that we remember to do that.

---

*[ports/geckolib/glue.rs, line 460 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDfcQ5jyEZUSb2rZMr:-KNDfcQ5jyEZUSb2rZMs:1529854813) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/glue.rs#L460)):*
> ```Rust
> 
>     // NB: Binaries representation match.
>     unsafe { transmute(hint.bits() as u32) }
> ```

Does this really need to be a transmute? I don't remember if |as| works for repr(C) enums.

---

*[ports/geckolib/snapshot.rs, line 16 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDjXqQpMxtPWiQmrFA:-KNDjXqRiM_sHS_8aDIz:1180431898) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L16)):*
> ```Rust
> 
> // NB: This is sound, in some sense, because during computation of restyle hints
> // the snapshot is kept alive by the modified elements table.
> ```

Hm, so these are basically only valid in stack scope, right? Can we either use a lifetime or a strong reference here to make sure these don't escape? Happy for that to happen in a followup if that makes sense.

---

*[ports/geckolib/snapshot.rs, line 31 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDk7InWNhvp3rPQBbr:-KNDk7IorC48sqFe1dTu:-1800195501) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L31)):*
> ```Rust
> 
>     fn has_any(&self, flags: Flags) -> bool {
>         unsafe { (*self.0).mContains as u8 & flags as u8 != 0 }
> ```

Can you parenthesize a bit more here make the precedence clearer?

---

*[ports/geckolib/snapshot.rs, line 62 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDliSm-QilNv3Zd6nh:-KNDliSn8FpFcd9xB-qe:1478459492) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L62)):*
> ```Rust
>                                                attr.select_name(self.is_html_element_in_html_document()),
>                                                value.as_ptr(),
>                                                /* ignoreCase = */ false)
> ```

Don't you want ignoreCase = true here?

---

*[ports/geckolib/snapshot.rs, line 129 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDm2H3Y9FUHOCuTseu:-KNDm2H49OgjZ6Pt310Z:-1506061695) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L129)):*
> ```Rust
>         } else {
>             Some(Atom::from(value))
>         }
> ```

Can you use .as_ref().map here instead?

---

*[ports/geckolib/snapshot.rs, line 132 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDqCsh1C07xEIJECR6:-KNDqCsiPSMYn0WxtTKZ:-1629394453) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L132)):*
> ```Rust
>     }
> 
>     // TODO: share logic with Element::{has_class, each_class}?
> ```

Yeah, the logic here is complicated enough that I think we should share these and just pass a function argument to the helper which invokes the appropriate FFI method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12469)*

**Comment by bholley** [comment]
r=me with those addressed. @bors-servo delegate+

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/style/selector_impl.rs, line 82 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDdSevQYnIaBAEaYBz:-KNE9BuwJEArzF9cr_nM:-1249416724) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/components/style/selector_impl.rs#L82)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> This text appears twice...
</details>
Dammit, rebase maddness... For some reason git decided to automerge it this way, sigh.

---

*[ports/geckolib/glue.rs, line 452 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDf5NEauAbkbq4MkfN:-KNEL6NxuI39yIBr-wR5:-499146009) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/glue.rs#L452)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Nit: "get rid of".
</details>
Done.

---

*[ports/geckolib/glue.rs, line 459 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDfAfO-z_lJerUYIZw:-KNE9Zox8H2bhJRKu0Pj:1891325967) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/glue.rs#L459)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Do we have an enforcement mechanism for this somewhere? If not, please file a bug so that we remember to do that.
</details>
We don't. I can add it as a followup.

---

*[ports/geckolib/glue.rs, line 460 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDfcQ5jyEZUSb2rZMr:-KNE9f0vHO9PZU31F7B1:-1155350981) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/glue.rs#L460)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Does this really need to be a transmute? I don't remember if |as| works for repr(C) enums.
</details>
It works in the enum to integer case, but not the opposite without transmute.

---

*[ports/geckolib/snapshot.rs, line 16 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDjXqQpMxtPWiQmrFA:-KNE9pqQvl-TxkY33fE7:-1158242509) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L16)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Hm, so these are basically only valid in stack scope, right? Can we either use a lifetime or a strong reference here to make sure these don't escape? Happy for that to happen in a followup if that makes sense.
</details>
Hm... Not really, they are kept alive in the heap, but cleared just before the `DoProcessRestyles` function returns.

Nontheless, yeah, I can try to give it a lifetime, and use the lifetime of the scope of that function as a follow-up.

---

*[ports/geckolib/snapshot.rs, line 31 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDk7InWNhvp3rPQBbr:-KNEAX8uebmq9h8x81OS:-485110604) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L31)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Can you parenthesize a bit more here make the precedence clearer?
</details>
Sure.

---

*[ports/geckolib/snapshot.rs, line 62 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDliSm-QilNv3Zd6nh:-KNEBNDYon_G4bWo6vCE:-1751459606) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L62)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Don't you want ignoreCase = true here?
</details>
Good catch, as usual :)

---

*[ports/geckolib/snapshot.rs, line 129 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDm2H3Y9FUHOCuTseu:-KNEDQWUrq8ssNepGdDo:-1854541759) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L129)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Can you use .as_ref().map here instead?
</details>
Nope, since it converts it into a reference, and then `Atom::from` doesn't know what to do. We can certainly add an impl like `From<'a> &'a nsIAtom for Atom`, but I don't quite love it that much.

---

*[ports/geckolib/snapshot.rs, line 132 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12469#-KNDqCsh1C07xEIJECR6:-KNEL2SHD3gCRyO_BfyB:-499146009) ([raw file](https://github.com/servo/servo/blob/14374a8da4136084a6af2e723be2c3f24f56174f/ports/geckolib/snapshot.rs#L132)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Yeah, the logic here is complicated enough that I think we should share these and just pass a function argument to the helper which invokes the appropriate FFI method.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12469)*

**Pull request merged**
