### PR TITLE
Mach Bootstrap: Support for more platforms

### PR DESCRIPTION
**Pull request by UK992**
Adds support for Debian, Fedora and OS X. 
On osx you need to choose package manager (Homebrew or MacPorts). Chosen manager will be set as default manager and written in `.servo/default_package_manager` file. If only one package manager exist, will be automatically chosen as default. 

Also add new flag `--silent` and checks for missing packages before every build on all supported platforms.

If pip or virtualenv missing, it will run script to install packages needed for creating virtualenv.

Still need some testings if it works as expected, especially osx which i could only tested via travis-ci and at half-working virtual machine.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13226)

### CODE REVIEW

**Comment by aneeshusa** [comment]
I think we can re-use/migrate our Salt configurations from [saltfs](https://github.com/servo/saltfs/) here instead of re-creating the package maangement logic, which I would prefer to do. I will check into the feasibility of this and leave another comment.

**Comment by UK992** [comment]
@aneeshusa Any informations about feasibility of Salt configuration?

**Comment by aneeshusa** [comment]
@UK992 It looks like Salt can be run from inside a virtualenv, so I'm working on a PR that sets that up.

**Comment by larsbergstrom** [comment]
This is SUPER exciting to me because it means that user machines and CI machines are provisioned in exactly the same manner. Thank you both for working on it!

**Comment by aneeshusa** [comment]
FYI, this is on hold until servo/saltfs#483 is merged + deployed + the kinks are worked out, since it jumps our Salt version by two major versions (to the latest).

**Comment by Wafflespeanut** [comment]
Ping @aneeshusa

**Comment by aneeshusa** [comment]
Watch #14974 for updates.

**Comment by aneeshusa** [comment]
Closing since #14974 is merged, however @UK992 I'd love to see the Fedora/Debian support added to the Salt-based `mach bootstrap` by upstreaming those package lists to the saltfs repo!

**Pull request closed without merging**
