### PR TITLE
update "navigation within beforeunload" test to match the spec

### PR DESCRIPTION
**Pull request by gterzian**
Follow up on https://github.com/servo/servo/pull/20329#issuecomment-387138449
@cbrewster 

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20780)

### CODE REVIEW

**Comment by cbrewster** [comment]
LGTM, you will need to run `./mach update-manifest` since you changed a wpt test.

**Comment by cbrewster** [comment]
r=me once CI isn’t broken

@bors-servo delegate+

**Comment by gterzian** [comment]
it seems both http://build.servo.org/builders/linux-rel-nogate and http://build.servo.org/builders/android are both failing across builds at the moment...

**Comment by gterzian** [comment]
@bors-servo retry

- #20788 

- #20774

**Comment by gterzian** [comment]
Seeing this one again
`Metadata.framework [Error]: couldn't get the client port`
resulting in the unit tests failing with
```
error: process didn't exit successfully: `/Users/servo/buildbot/slave/mac-dev-unit/build/target/debug/deps/text_util-9a954535af80505d` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by nox** [comment]
@bors-servo treeclosed=8000

https://github.com/servo/servo/pull/20750#issuecomment-389823547

**Comment by gterzian** [comment]
```
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: sending non-ascii, combining chars and non-BMP", "test": "/websockets/interfaces/WebSocket/send/011.html", "line": 99922, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/send/011.html", "line": 99923, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "ArrayBuffer should be created in the relevant realm of the WebSocket", "test": "/websockets/multi-globals/message-received.html", "line": 106347, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "Blob should be created in the relevant realm of the WebSocket", "test": "/websockets/multi-globals/message-received.html", "line": 106348, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/multi-globals/message-received.html", "line": 106349, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: protocol array", "test": "/websockets/constructor/022.html", "line": 106489, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/022.html", "line": 106490, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: wrong accept key", "test": "/websockets/security/001.html", "line": 108469, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/security/001.html", "line": 108470, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "Constructor succeeds", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108749, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings (null)", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108750, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings (undefined)", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108751, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings (1)", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108752, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings ([object Window])", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108753, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings ([object HTMLBodyElement])", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108754, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings ([object Object])", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108755, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings ()", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108756, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings ([object WebSocket])", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108757, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings (function (){})", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108758, "action": "test_result", "expected": "PASS"}
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: sending non-strings (Error)", "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108759, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/send/010.html", "line": 108760, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: bufferedAmount for 65K data", "test": "/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-large.html", "line": 110900, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: uppercase 'WS:'", "test": "/websockets/constructor/019.html", "line": 114807, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/019.html", "line": 114808, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: converting first arguments", "test": "/websockets/constructor/006.html", "line": 115304, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/006.html", "line": 115306, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: uppercase host", "test": "/websockets/constructor/020.html", "line": 121189, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/020.html", "line": 121190, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: bufferedAmount for ArrayBuffer", "test": "/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-arraybuffer.html", "line": 122028, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-arraybuffer.html", "line": 122029, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: getting readyState in closing", "test": "/websockets/interfaces/WebSocket/readyState/007.html", "line": 122395, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/readyState/007.html", "line": 122396, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: sending HttpOnly cookies in ws request", "test": "/websockets/cookies/003.html", "line": 123409, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: sending null", "test": "/websockets/interfaces/WebSocket/send/012.html", "line": 123436, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/send/012.html", "line": 123439, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: close() followed by send()", "test": "/websockets/interfaces/WebSocket/send/007.html", "line": 124174, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/send/007.html", "line": 124175, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: protocol", "test": "/websockets/constructor/009.html", "line": 124654, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/009.html", "line": 124655, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: protocol in response but no requested protocol", "test": "/websockets/constructor/010.html", "line": 126893, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/010.html", "line": 126894, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: bufferedAmount for unicode data", "test": "/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-unicode.html", "line": 128031, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-unicode.html", "line": 128032, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: no protocol in response", "test": "/websockets/constructor/012.html", "line": 132081, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/012.html", "line": 132082, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: send() in onclose", "test": "/websockets/interfaces/WebSocket/send/008.html", "line": 132955, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/send/008.html", "line": 132956, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: wasClean, true", "test": "/websockets/interfaces/CloseEvent/clean-close.html", "line": 133634, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: getting readyState in open", "test": "/websockets/interfaces/WebSocket/readyState/006.html", "line": 138713, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/readyState/006.html", "line": 138714, "action": "test_result", "expected": "OK"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "WebSockets: close() when connecting", "test": "/websockets/interfaces/WebSocket/close/close-connecting.html", "line": 153011, "action": "test_result", "expected": "FAIL"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: Set-Cookie in response", "test": "/websockets/cookies/002.html", "line": 160868, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/cookies/002.html", "line": 160869, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: NULL char in url", "test": "/websockets/constructor/018.html", "line": 162664, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/018.html", "line": 162665, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: 20s inactivity after handshake", "test": "/websockets/keeping-connection-open/001.html", "line": 162690, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: send('')", "test": "/websockets/interfaces/WebSocket/send/009.html", "line": 163248, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/send/009.html", "line": 163249, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: serialize establish a connection", "test": "/websockets/constructor/014.html", "line": 195184, "action": "test_result", "expected": "FAIL"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/014.html", "line": 195185, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: getting readyState in closed", "test": "/websockets/interfaces/WebSocket/readyState/008.html", "line": 195321, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/readyState/008.html", "line": 195322, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: bufferedAmount after send()ing", "test": "/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-getting.html", "line": 200619, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-getting.html", "line": 200620, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: when to process set-cookie fields in ws response", "test": "/websockets/cookies/007.html", "line": 206610, "action": "test_result", "expected": "FAIL"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: protocol mismatch", "test": "/websockets/constructor/011.html", "line": 208351, "action": "test_result", "expected": "FAIL"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/011.html", "line": 208352, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: Cookie in request", "test": "/websockets/cookies/001.html", "line": 208377, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/cookies/001.html", "line": 208378, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: non-ascii URL in query, document encoding windows-1252", "test": "/websockets/constructor/016.html", "line": 208467, "action": "test_result", "expected": "FAIL"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/constructor/016.html", "line": 208468, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: setting HttpOnly cookies in ws response, checking document.cookie", "test": "/websockets/cookies/004.html", "line": 209200, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: send() return value", "test": "/websockets/interfaces/WebSocket/send/005.html", "line": 209412, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/send/005.html", "line": 209413, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: bufferedAmount for blob", "test": "/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-blob.html", "line": 209510, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-blob.html", "line": 209511, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSockets: send() with unpaired surrogate when readyState is OPEN", "test": "/websockets/interfaces/WebSocket/send/006.html", "line": 210536, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/interfaces/WebSocket/send/006.html", "line": 210537, "action": "test_result", "expected": "OK"}
```
Looks unrelated to me, perhaps more of a performance issue with the server?

**Comment by jdm** [comment]
Yeah, that's #20734.

**Comment by gterzian** [comment]
also seeing also seeing https://github.com/servo/servo/issues/20796

**Comment by gterzian** [comment]
seems to be stuck on that one failure similar to https://github.com/servo/servo/issues/20796
it's a pitty because all others are passing and still valid, would be too bad to have to run them all over again at a later stage...

**Comment by jdm** [comment]
Unfortunately retrying is not going to help. The crashes are consistent on this particular builder; I'm looking for a permanent solution.

**Comment by jdm** [comment]
@bors-servo retry
* #20734

**Comment by jdm** [comment]
@bors-servo retry
* #13480

**Comment by gterzian** [comment]
rebased, this one will need a new r+...

**Comment by gterzian** [comment]
@bors-servo retry

- #20734

**Pull request merged**
