### PR TITLE
Update servo-media

### PR DESCRIPTION
**Pull request by Manishearth**
Should fix webrtc

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23334)

### CODE REVIEW

**Comment by Manishearth** [comment]
This also contains https://github.com/servo/media/pull/254, which is a minor breaking change.

**Review by jdm — APPROVED** [review]

**Comment by Manishearth** [comment]
@bors-servo p=-1

this is contained in  #23342 , so if that lands we shouldn't have to test this

**Pull request merged**
