### PR TITLE
compositing: Send mouse events to the right pipeline when using WebRender.

### PR DESCRIPTION
**Pull request by pcwalton**
Fixes mouse events in browser.html.

Requires servo/webrender_traits#47 and servo/webrender#272.

r? @glennw
cc @paulrouget

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11000)

### CODE REVIEW

**Comment by glennw** [comment]
@pcwalton This (and the associated PRs in WR/traits) look good to me - I'll leave you to merge them in the appropriate order.

**Comment by mbrubeck** [comment]
@bors-servo p=1

* to unblock a rustup PR

**Pull request merged**
