### PR TITLE
Fixes Issue #6866

### PR DESCRIPTION
**Pull request by HarryLovesCode**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6893)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
(for #6866 /cc @jdm)

**Comment by jdm** [comment]
Fantastic work! Thanks for the patch, @HarryLovesCode. Could you [squash](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) these commits into one, now? 
-S-awaiting-review +S-needs-squash 

---

Reviewed 8 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6893)

**Comment by HarryLovesCode** [comment]
Whoops one sec

**Comment by jdm** [comment]
I'll also note for future reference that it's easier for us to review branches that use [rebase](http://rypress.com/tutorials/git/rebasing), rather than merge, to stay up to date with servo/master.

**Comment by HarryLovesCode** [comment]
@jdm Sorry, but how should I be squashing? Everytime I attempt to it says that my patch fails.

**Comment by HarryLovesCode** [comment]
@jdm I seem to have created a mess. I tried squashing, but each time it reverts all my changes that got caught up in a previous merge. Any idea how I can fix?

**Comment by jdm** [comment]
I suggest making a new branch, resetting to a revision from servo/master, using `git merge --squash master`, and force pushing the result to this PR using `git push -f origin [newbranchname]:master`, assuming `origin` is the name of the remote for HarryLovesCode/servo.

**Comment by HarryLovesCode** [comment]
New branch of this repo or my fork?

**Comment by jdm** [comment]
A new branch of your local clone.

**Comment by HarryLovesCode** [comment]
And then what would be the correct command to squash the two commits and update? The link suggested it would be `git rebase -i 9a2f28ae33efd5216b0e1933bf186ad2fadba137` where `9a2f28ae33efd5216b0e1933bf186ad2fadba137` is the commit right before what I want to squash.

**Comment by jdm** [comment]
Oh, in this particular case the `git merge --squash` should take care of that automatically.

**Comment by HarryLovesCode** [comment]
Odd, that just closed this pull request...

**Comment by HarryLovesCode** [comment]
I better make sure this builds before merging.

**Comment by jdm** [comment]
@bors-servo: r+
Fantastic!

**Pull request merged**
