### PR TITLE
Use box syntax instead of Box::new()

### LINKED ISSUE #5417: Replace all instances of `Box::new(foo)` with `box foo`
This may require adding `#![feature(box_syntax)]` to the corresponding lib.rs for the crate.

### PR DESCRIPTION
**Pull request by bdero**
Closes #5417

### CODE REVIEW

**Comment by Ms2ger** [comment]
ports/gonk/ needs a feature gate

**Comment by bdero** [comment]
Whoops, just added one. Unfortunately, I can't build gonk locally, so I can't verify.

**Comment by jdm** [comment]
Go ahead and squash those together.

**Comment by bdero** [comment]
All set

**Pull request merged**
