### PR TITLE
Appveyor: Fix missing gstreamer dlls

### LINKED ISSUE #23749: Appveyor is broken after gstreamer packaging changes
Same symptoms as https://github.com/servo/servo/issues/23747 except that it's our own CI.

### PR DESCRIPTION
**Pull request by UK992**
This changes will execute complete installation of gstreamer. And should fix https://github.com/servo/servo/issues/23749

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23765)

### CODE REVIEW

**Comment by jdm** [comment]
Aha, thanks for finding that option!

**Comment by jdm** [comment]
@UK992 Out of curiosity, how did you figure that out?

**Comment by saschanaz** [comment]
Could we enable only the required one rather than =ALL? Might be better to detect when requirement changes.

**Comment by UK992** [comment]
@jdm many search queries related to gstreamer msi installer arguments / properties and somehow found out someone using ADDLOCAL on gstreamer installer. Then testing, installing and removing gstreamer many times. :)

**Pull request merged**
