### PR TITLE
Include transform changes in list that cause incremental reflows.

### LINKED ISSUE #8329: CSS 3D transforms cut along the compositor borders
s

```html
<style>
  div {
    background: #f06;
    top: calc(50vh - 100px);
    left: calc(50vw - 100px);
    height: 200px;
    width: 200px;
    position: absolute;
  }
</style>

<body>
  <div></div>
</body>

<script>

  const cssGimbal = (x, y, z, rx, ry, rz) => `translate3d(${x}px, ${y}px, ${z}px) rotateX(${rx}deg) rotateY(${ry}deg) rotateZ(${rz}deg)`;

  var div = document.querySelector('div');
  var t = 0;
  setInterval(() => {
    t += 0.05;
    x = 1000 * Math.cos(t);
    y = 1000 * Math.sin(t);
    div.style.transform = cssGimbal(
      (x * -0.02),
      (y * -0.07),
      -400,
      (-1 * (y * 0.02)),
      (x * 0.02),
      0
    );
  }, 20);
</script>
```

### PR DESCRIPTION
**Pull request by glennw**
Also ensure that 3d translations get layers.

Fixes #8329.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8559)

### CODE REVIEW

**Comment by eefriedman** [comment]
Missing testcase?

**Comment by glennw** [comment]
We don't have a way to reliably test incremental layout bugs at the moment.

**Comment by pcwalton** [comment]
Hmm, this looks pretty suboptimal (and not what other browsers do). We shouldn't be reflowing when transforms change. In fact, that's much of the purpose of CSS transforms existing…

**Comment by glennw** [comment]
The problem is that the value of the transform variable affects whether it needs a layer - which is only calculated during reflow. I'll update the PR to only trigger a reflow when those special case changes of transform occur.

**Comment by glennw** [comment]
@pcwalton Updated to include that change - good catch :)

**Comment by jdm** [comment]
@bors-servo: retry
* #8614

**Pull request merged**
