### PR TITLE
OffscreenCanvas API

### LINKED ISSUE #14627: Implement OffscreenCanvas API (needed for WebGL canvas in workers)
The `OffscreenCanvas` API supports a canvas to be rendered off screen. It is available in both the `window` and worker contexts.

Supported by a flag today in Firefox, under active development right now by Chrome.

Relevant links:
* https://wiki.whatwg.org/wiki/OffscreenCanvas
* https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas
* https://hacks.mozilla.org/2016/01/webgl-off-the-main-thread/
* https://crbug.com/563816

### PR DESCRIPTION
**Pull request by maharsh312**
Initial Steps for OffscreenCanvas API are done in this commit.

r? @jdm 
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14627 (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22495)

### CODE REVIEW

**Comment by jdm** [comment]
Please note that `./mach test-tidy` is failing, this error is present:
```
error: unused import: `Error`
 --> components/script/dom/offscreencanvas.rs:9:35
  |
9 | use crate::dom::bindings::error::{Error, Fallible};
  |                                   ^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`
```

**Comment by maharsh312** [comment]
@jdm Can you suggest any solution to resolve unreachable pattern warning?

**Comment by fabricedesre** [comment]
> @jdm Can you suggest any solution to resolve unreachable pattern warning?

There is only one variant in the enum, so you can never match on anything else but OffscreenCanvas2D. For now, just remove the `_ => ...` part.

**Comment by maharsh312** [comment]
> > @jdm Can you suggest any solution to resolve unreachable pattern warning?
> 
> There is only one variant in the enum, so you can never match on anything else but OffscreenCanvas2D. For now, just remove the `_ => ...` part.

Getting this error now: https://pastebin.com/jzTYEkiu

**Comment by fabricedesre** [comment]
You removed it from get_or_init_2d_context() right?

**Comment by maharsh312** [comment]
> ./mach update-wpt text text.1

I getting this erros while running "./mach update-qpt text text.1" : https://pastebin.com/vYHL6yah

@jdm Is this fine? Should I go ahead with other commands?

**Comment by jdm** [comment]
@maharsh312 You may need to rebase your branch against master before you can run that command.

**Comment by maharsh312** [comment]
> @maharsh312 You may need to rebase your branch against master before you can run that command.

Did that. Now it is showing some test are not found

**Comment by maharsh312** [comment]
@jdm I messed up rebasing the repo right?

**Comment by jdm** [comment]
Yes. Here is what I did to fix it up starting from a pristine master branch:
```
$ git checkout -b offscreencanvas
git cherry-pick b4a77a5fea7026f388a80d24864a4fa375052096
git cherry-pick df1e451
git cherry-pick 30da91f
git cherry-pick a489778
git cherry-pick 042fa3d
git cherry-pick e845644
git cherry-pick 668a19c
git cherry-pick 637add5
```
This attached each of your commits, and I fixed up a merge conflict with the last one. Then I rebased to [squash](https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/) all of the commits into one. Then I force pushed the resulting commit over your master branch so the pull request was updated. I'm going to go ahead and try to merge this, because I would rather us not get stuck on trying to keep fixing this up.

**Comment by jdm** [comment]
@bors-servo retry
* #22706 #22705

**Pull request merged**
