### PR TITLE
Introduce a compositing_traits crate.

### PR DESCRIPTION
**Pull request by Ms2ger**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy --faster` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because refactoring

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11419)

### CODE REVIEW

**Comment by Ms2ger** [comment]
This was an experiment; if people feel it isn't much of an improvement, I'd be happy to drop it.

**Comment by metajack** [comment]
The normal motivation for this split is to allow more crates to compile in parallel. Which crates does this now allow to compile earlier, and how does it affect build time?

**Comment by jdm** [comment]
This allows compositing and constellation to compile in parallel, which are the final step before servo and after layout. Compositing is likely able to build slightly earlier in the process, too.

**Comment by metajack** [comment]
This looks good. It needs squashing and the ports/cef and ports/gonk and lockfiles also need updating, or at least seem like they should since they currently depend on compositing crate. r=me with those changes.

<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> This allows compositing and constellation to compile in parallel, which are the final step before servo and after layout. Compositing is likely able to build slightly earlier in the process, too.
</details>


---

Reviewed 7 of 7 files at r1, 15 of 15 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11419#-:-KIeBzx46jpXRk4iJ8Fy:-1632693911)*

**Comment by notriddle** [comment]
It looks like @metajack said it was all good, and then it bitrotted. Should it be rebased?

**Comment by jdm** [comment]
Closing this given http://logs.glob.uno/?c=mozilla%23servo#c568125.

**Pull request closed without merging**
