### PR TITLE
Implement HTMLTextArea.setSelectionRange (continuation of #10007)

### LINKED ISSUE #9994: Implement HTMLTextArea.setSelectionRange
Spec: https://html.spec.whatwg.org/multipage/forms.html#textFieldSelection
Code: `components/script/dom/htmtextareaelement.rs`, `components/script/dom/webidls/HTMLTextAreaElement.webidl`
Test: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/forms/textfieldselection/textfieldselection-setSelectionRange.html`

This will be very similar to #9905 which implemented this API for `<input>` elements.

### PR DESCRIPTION
**Pull request by autrilla**
Tests on `tests/wpt/web-platform-tests/html/semantics/forms/textfieldselection/textfieldselection-setSelectionRange.html` all pass and the other tests don't panic due to double borrows anymore.

cc: @KiChjang

Fixes #9994.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10612)

### CODE REVIEW

**Comment by jdm** [comment]
Looks like `./mach test-unit -p script` currently fails:
```
C:\projects\servo\tests\unit\script\textinput.rs:127:25: 132:6 error: this function takes 5 parameters but 4 parameters were supplied [E0061]
C:\projects\servo\tests\unit\script\textinput.rs:127     let mut textinput = TextInput::new(
C:\projects\servo\tests\unit\script\textinput.rs:128         Lines::Single,
C:\projects\servo\tests\unit\script\textinput.rs:129         DOMString::from(""),
C:\projects\servo\tests\unit\script\textinput.rs:130         DummyClipboardContext::new(""),
C:\projects\servo\tests\unit\script\textinput.rs:131         Some(2)
C:\projects\servo\tests\unit\script\textinput.rs:132     );
C:\projects\servo\tests\unit\script\textinput.rs:127:25: 132:6 help: run `rustc --explain E0061` to see a detailed explanation
C:\projects\servo\tests\unit\script\textinput.rs:144:25: 149:6 error: this function takes 5 parameters but 4 parameters were supplied [E0061]
C:\projects\servo\tests\unit\script\textinput.rs:144     let mut textinput = TextInput::new(
C:\projects\servo\tests\unit\script\textinput.rs:145         Lines::Single,
C:\projects\servo\tests\unit\script\textinput.rs:146         DOMString::from(""),
C:\projects\servo\tests\unit\script\textinput.rs:147         DummyClipboardContext::new(""),
C:\projects\servo\tests\unit\script\textinput.rs:148         Some(3)
C:\projects\servo\tests\unit\script\textinput.rs:149     );
C:\projects\servo\tests\unit\script\textinput.rs:144:25: 149:6 help: run `rustc --explain E0061` to see a detailed explanation
C:\projects\servo\tests\unit\script\textinput.rs:163:25: 168:6 error: this function takes 5 parameters but 4 parameters were supplied [E0061]
C:\projects\servo\tests\unit\script\textinput.rs:163     let mut textinput = TextInput::new(
C:\projects\servo\tests\unit\script\textinput.rs:164         Lines::Single,
C:\projects\servo\tests\unit\script\textinput.rs:165         DOMString::from("\u{10437}"),
C:\projects\servo\tests\unit\script\textinput.rs:166         DummyClipboardContext::new(""),
C:\projects\servo\tests\unit\script\textinput.rs:167         Some(1)
C:\projects\servo\tests\unit\script\textinput.rs:168     );
C:\projects\servo\tests\unit\script\textinput.rs:163:25: 168:6 help: run `rustc --explain E0061` to see a detailed explanation
error: aborting due to 3 previous errors 
Build failed, waiting for other jobs to finish...
error: Could not compile `script_tests`.
 
To learn more, run the command again with --verbose.
Command exited with code 101
```

**Comment by autrilla** [comment]
@jdm yes, I noticed that. Do you remember it failing on the previous PR? I don't see any record of it, but I didn't change `TextInput::new` at all. Anyway, I'll be sure to fix that.

**Comment by emilio** [comment]
The changes look good to me, thanks for doing this! :)

I left some nits. There were also some tests crashing due to double borrows... Not totally sure they're fixed, so I'll make a try run before r+'ing.

The panicking tests were `html/semantics/forms/the-input-element/selection.html`, `html/semantics/forms/textfieldselection/selection-not-application-textarea.html` and `html/semantics/forms/textfieldselection/selection-not-application.html`and `html/semantics/forms/textfieldselection/textfieldselection-setRangeText.html`.


@bors-servo: try

There were also a few other passing tests IIRC, so more expectations might need to get updated... Anyways, we'll find out soon! :)

-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/htmlinputelement.rs, line 545 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10612#-KFUudkBxO8Q7JnG2naI:-KFUudkBxO8Q7JnG2naJ:117110528) ([raw file](https://github.com/servo/servo/blob/693d764c94062e1f56103bd612d7c311ab94907b/components/script/dom/htmlinputelement.rs#L545)):*
nit: The match below could be written more concisely as:

```rust
let direction = direction.map_or(SelectionDirection::None, |d| SelectionDirection::from(d));
self.textinput.borrow_mut().selection_direction = direction;
```

---

*[components/script/dom/htmltextareaelement.rs, line 257 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10612#-KFUvA3DlxZFryofnC8S:-KFUvA3DlxZFryofnC8T:-469765787) ([raw file](https://github.com/servo/servo/blob/693d764c94062e1f56103bd612d7c311ab94907b/components/script/dom/htmltextareaelement.rs#L257)):*
ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10612#-:-KFUvS-oKgU_iBX3Yer5:-1732997253)*

**Comment by autrilla** [comment]
@emilio any clue why the appveyor tests fail?

**Comment by jdm** [comment]
That's an unrelated problem that was fixed in a PR that merged after that commit was pushed.

**Comment by autrilla** [comment]
@jdm thanks. I rebased my commit on top of the last one on master.

**Comment by emilio** [comment]
Cool, you have to update the `interfaces.html` test:

```
Tests with unexpected results:
  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLTextAreaElement interface: attribute selectionStart

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLTextAreaElement interface: attribute selectionEnd

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLTextAreaElement interface: attribute selectionDirection

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLTextAreaElement interface: operation setSelectionRange(unsigned long,unsigned long,DOMString)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLTextAreaElement interface: document.createElement("textarea") must inherit property "selectionStart" with the proper type (27)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLTextAreaElement interface: document.createElement("textarea") must inherit property "selectionEnd" with the proper type (28)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLTextAreaElement interface: document.createElement("textarea") must inherit property "selectionDirection" with the proper type (29)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLTextAreaElement interface: document.createElement("textarea") must inherit property "setSelectionRange" with the proper type (32)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLTextAreaElement interface: calling setSelectionRange(unsigned long,unsigned long,DOMString) on document.createElement("textarea") with too few arguments must throw TypeError
```

**Comment by emilio** [comment]
@bors-servo: r+

Thanks for taking this @autrilla!

**Pull request merged**
