### PR TITLE
Stylo: implement -moz-orient

### LINKED ISSUE #14198: Stylo: implement -moz-orient
Please go through [the guide](https://github.com/servo/servo/wiki/Stylo-hacking-guide) if you wish to hack on stylo.

[`-moz-orient`](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-orient) is a keyword property ([implementation guide](https://github.com/servo/servo/wiki/Stylo-hacking-guide#implementing-a-simple-keyword-property)) with the set of possible values being `inline | block | horizontal | vertical`. `inline` is the default. The field name is [`mOrient`](http://searchfox.org/mozilla-central/rev/4b6cab91f93c73ae591dafaea40fd5704b41810e/layout/style/nsStyleStruct.h#2824), and the enum prefix is [`StyleOrient`](http://searchfox.org/mozilla-central/rev/4b6cab91f93c73ae591dafaea40fd5704b41810e/layout/style/nsStyleConsts.h#237).

The testcase on the MDN page must work in stylo once this property is implemented.

File: https://github.com/servo/servo/blob/master/components/style/properties/longhand/box.mako.rs

### PR DESCRIPTION
**Pull request by ctjhoa**
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-orient
2016-12-21-213132_1342x870_scrot

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14198 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it's a style addition

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14663)

### CODE REVIEW

**Comment by KiChjang** [comment]
@ctjhoa Why did you submit this PR when the issue is assigned to @RockyTV?

**Comment by ctjhoa** [comment]
@KiChjang  Sorry I was working on this before his assignment and did not ask for assignment. It's my first servo contribution, is assignment mandatory?

**Comment by KiChjang** [comment]
Yes, please do so next time.

r? @Manishearth

**Comment by Manishearth** [comment]
@bors-servo r+

thanks

**Pull request merged**
