### PR TITLE
Add a build switch to disable the native bluetooth backend.

### LINKED ISSUE #22059: Magic Leap build of blurdroid fails
Building for Magic Leap with the android-toolchain directory removed produces:
```
     Running `/Users/ajeffrey/github/asajeffrey/servo/target/debug/build/blurdroid-34d1dca00bf7eab7/build-script-build`                                                             
thread 'main' panicked at 'Please set the ANDROID_SDK environment variable', libcore/option.rs:1010:5                                                                               
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                                                                                                  
error: failed to run custom build command for `blurdroid v0.1.6`                                                                                                                    
process didn't exit successfully: `/Users/ajeffrey/github/asajeffrey/servo/target/debug/build/blurdroid-34d1dca00bf7eab7/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Please set the ANDROID_SDK environment variable', libcore/option.rs:1010:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
Rather oddly, it builds if there's an android-toolchain present.

### PR DESCRIPTION
**Pull request by jdm**
Fixes #22059.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22060)

### CODE REVIEW

**Review by asajeffrey — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* #22062

**Comment by jdm** [comment]
@bors-servo retry
* oom

**Pull request merged**
