### PR TITLE
Use OpenXR loader from NuGet

### PR DESCRIPTION
**Pull request by Manishearth**
No need to manually download the DLL

r? @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24140)

### CODE REVIEW

**Comment by paulrouget** [comment]
With this change, I keep getting this error:

```
RUST: WARN - webxr_api::registry - XR device error BackendSpecific("\"The specified module could not be found. (os error 126)\"")
```

Without this commit, no error.

**Comment by Manishearth** [comment]
Make sure you restore nuget packages. You need to install the OpenXR package from the Windows Store as well.

**Comment by paulrouget** [comment]
> Make sure you restore nuget packages. You need to install the OpenXR package from the Windows Store as well.

I've done all of that. I've very confused.

**Pull request merged**
