### PR TITLE
Remove the legacy reftest framework.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9293)

### CODE REVIEW

**Comment by frewsxcv** [comment]
`./python/tidy.py:64: F821 undefined name 'reftest_filetype'`

**Comment by KiChjang** [comment]
```
Ran 3837 tests finished in 264.0 seconds.
  • 3836 ran as expected. 701 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /_mozilla/css/acid2-wrapper.html
```

**Comment by Ms2ger** [comment]
@bors-servo retry
* https://github.com/servo/servo/issues/9311

**Pull request merged**
