### PR TITLE
Only compile applicable event handler content attributes

### PR DESCRIPTION
**Pull request by Manishearth**
Part of https://github.com/servo/servo/issues/13152

r? @jdm

cc @pshaugn

### CODE REVIEW

**Comment by Manishearth** [comment]
Hm, this is causing a lot of timeouts, maybe the overhead is too much there.

**Comment by pshaughn** [comment]
> 
> 
> Hm, this is causing a lot of timeouts, maybe the overhead is too much there.

Timeouts can also be because t.done() was inside an event handler that never came. I'd guess that before the overhead from some hashmap lookups.

**Comment by Manishearth** [comment]
It's not the lookups, the lazy_static means that we spend some time setting up the hashmap the first time someone ever sets an event handler. But yeah, we could also be just not triggering the event handlers.

**Comment by Manishearth** [comment]
CLosing in favor of an approach that uses proc macros.

**Comment by jdm** [comment]
@manishearth Where did the approach that uses proc macros end up?

**Comment by Manishearth** [comment]
@jdm Oh, it didn't happen, I played around with it a bit but you basically have to manually generate a PHF map. I was indicating that I wanted to close this in favor of us looking into such an approach, not necessarily that such an approach was already underway. I'll file an issue.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/issues/25760

**Pull request closed without merging**
