### PR TITLE
Update anonymous box list

### PR DESCRIPTION
**Pull request by bholley**
These have drifted since we introduced them. Adding a few other misc commits while I'm at it.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12608)

### CODE REVIEW

**Comment by Manishearth** [comment]
The llvm_stable thing breaks the binding generation for me. If I pass it llvm38, I get this error:

```
  "_clang_Type_getNamedType", referenced from:
      bindgen::clang::Type::named::h017a16ee858af8af in libbindgen.rlib(bindgen.0.o)
  "_clang_Cursor_isFunctionInlined", referenced from:
      bindgen::clang::Cursor::is_inlined_function::hbf3ecb6d1f288ea8 in libbindgen.rlib(bindgen.0.o)
```

If I pass it my local llvm trunk build, it works but makes changes like:

```diff
 -- a/ports/geckolib/gecko_bindings/bindings.rs
 ++ b/ports/geckolib/gecko_bindings/bindings.rs
@@ -147,7 +147,7 @@ use structs::nsIAtom;

 pub type RawGeckoNode = nsINode;
 pub enum Element { }
- pub type RawGeckoElement = Element;
+ pub type RawGeckoElement = ::std::os::raw::c_void;
 pub type RawGeckoDocument = nsIDocument;
 pub enum ServoNodeData { }
 pub enum ServoComputedValues { }
```

(all `mozilla::` things get replaced with void)

**Comment by bholley** [comment]
Hm, _clang_Cursor_isFunctionInlined and friends are LLVM39 symbols. The whole point of llvm_stable is that it avoids requiring llvm39 symbols, because we need to be on LLVM38 to have any chance at all of making LLVM a build-time requirement for Firefox.

Can you debug why llvm_stable seems to be having the opposite effect as intended?

**Comment by Manishearth** [comment]
I'll try, sure :smile:

a clean build of bindgen didn't seem to change anything but I should try this again.

**Comment by Manishearth** [comment]
Works now. I cleaned it again, reset env vars, and it's fine.

**Pull request merged**
