### PR TITLE
clippy:Use `map` instead of `filter_map` in `components/devtools`

### PR DESCRIPTION
**Pull request by tony-nyagah**
**File**: components/devtools/actors/inspector/page_style.rs

**PR Description**
Issue: Clippy warned about unnecessary use of .filter_map() in the PageStyleActor implementation. The .filter_map() operation was not actually filtering out any elements, making it equivalent to a .map() operation.

**Changes**
Replaced .filter_map(|node| { ... }) with .map(|node| { ... }) in the get_applied method of PageStyleActor.
Removed the Some(...) wrapper from the return value of the closure inside the mapping operation.

Impact: Improved code clarity and efficiency by using the appropriate iterator method. This change resolves a Clippy warning, contributing to better code quality without affecting the functionality of the code.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes are part of #31500

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
@tony-nyagah You need to sign your commits as detailed in https://github.com/servo/servo/pull/33723/checks?check_run_id=31225514051.

**Comment by tony-nyagah** [comment]
> @tony-nyagah You need to sign your commits as detailed in https://github.com/servo/servo/pull/33723/checks?check_run_id=31225514051.

I have followed the signoff steps as requested.

I ran clippy again and I got this:
```
warning: called `map(..).flatten()` on `Iterator`
   --> components/devtools/actors/inspector/page_style.rs:154:10
    |
154 |           .map(|node| {
    |  __________^
155 | |             let inherited = (node.actor != target).then(|| node.actor.clone());
156 | |             let node_actor = registry.find::<NodeActor>(&node.actor);
...   |
211 | |         })
212 | |         .flatten()
    | |__________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten
    = note: `#[warn(clippy::map_flatten)]` on by default
help: try replacing `map` with `flat_map` and remove the `.flatten()`
```

Should I update `map` to `flat_map` first or let this commit go through?

**Comment by mrobinson** [comment]
@tony-nyagah Yes, please update this commit. It's best not to introduce new clippy errors when fixing a clippy error.

**Comment by mrobinson** [comment]
Closing in favor of #33724.

**Pull request closed without merging**
