### PR TITLE
Issue #8462: Add support for BufferSubData, CompressedTexImage2D and CompressedSubTexImage2D and reenable individual webgl WPT tests

### PR DESCRIPTION
**Pull request by simartin**
Fixes https://github.com/servo/servo/issues/8462

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8712)

### CODE REVIEW

**Comment by jdm** [comment]
@ecoal95 Are you interested in taking a first pass at this review?

**Comment by ecoal95** [comment]
Yeah, sure!

I'll take a look at it as soon as I arrive home today :P

**Comment by ecoal95** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 406 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4F1fEU5ctO1AnVgTK1:-K4F1fEU5ctO1AnVgTK2:2027632815) ([raw file](https://github.com/servo/servo/blob/8527b7e980ace48bfb5597d954d61e6ad19265f8/components/script/dom/webglrenderingcontext.rs#L406)):*
Per the WebGL spec (5.14.5):
> If data is null then an INVALID_VALUE error is generated.

Returning `self.webgl_error(InvalidValue)` here will be enough.

---

*[components/script/dom/webglrenderingcontext.rs, line 407 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4F-0Fz_yi7grywIPE8:-K4F-0Fz_yi7grywIPE9:-239783881) ([raw file](https://github.com/servo/servo/blob/8527b7e980ace48bfb5597d954d61e6ad19265f8/components/script/dom/webglrenderingcontext.rs#L407)):*
May you add a basic validation of the `target` parameter here? Something similar to what we have [here](https://github.com/simartin/servo/blob/issue_8462/components/script/dom/webglrenderingcontext.rs#L308).

If you add it to `BufferData` too it will be great too :)

We should also validate that `offset` is not negative (GLES 2.0 spec):

> GL_INVALID_VALUE is generated if offset or size is negative, or if together they define a region of memory that extends beyond the buffer object's allocated data store.

The same paragraph says we should also validate that the offset and the size of the `ArrayBufferView` combined don't define a region inside the allocated one (via `BufferData`).

Not doing it this way will generate errors in the paint task instead of here (which is unexpected), but if @jdm agrees, it can be left as a followup (since it doesn't involve unsafety, just weird error behaviour, and is more difficult to implement). In that case, a `FIXME` comment here with the issue number will be appropriate I think, and if you CC me to keep track of it, or implement it when I have the time, it will be great :)

---

*[components/script/dom/webglrenderingcontext.rs, line 413 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4F2OMr3hZWctsBTzMO:-K4F2OMsAjDScSOgaq4N:514540502) ([raw file](https://github.com/servo/servo/blob/8527b7e980ace48bfb5597d954d61e6ad19265f8/components/script/dom/webglrenderingcontext.rs#L413)):*
Not sure if a panic here is adequate enough... Maybe we could just generate and `InvalidValue` error, and leave a comment with a link to the relevant issue about code generation. This applies to `BufferData` too.

I'd want to know what @jdm thinks about it though.

---

*[components/script/dom/webglrenderingcontext.rs, line 435 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4F37NLlXHP6-jmZ3QR:-K4F37NLlXHP6-jmZ3QS:-533328727) ([raw file](https://github.com/servo/servo/blob/8527b7e980ace48bfb5597d954d61e6ad19265f8/components/script/dom/webglrenderingcontext.rs#L435)):*
I think right now we should always generate an `InvalidEnum` error, since we don't have any extensions which add compressed texture image support. It's not about the number of extensions, but about if we support any extension which add compressed texture image support (which we don't).

So I'll also remove the `CompressedTexImage2D` message and the code in the paint task, and leave a return `self.webgl_error(InvalidEnum)` here.

---

*[components/script/dom/webglrenderingcontext.rs, line 472 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4F3mjc0WA9vvv8RCG-:-K4F3mjc0WA9vvv8RCG0:41660073) ([raw file](https://github.com/servo/servo/blob/8527b7e980ace48bfb5597d954d61e6ad19265f8/components/script/dom/webglrenderingcontext.rs#L472)):*
Same remark here, I'll be fine leaving this functions as one-liners with a comment saying something like:

> Right now we don't support any compressed image formats. This is spec-complaint (see: // https://www.khronos.org/registry/webgl/specs/latest/1.0/#COMPRESSED_TEXTURE_SUPPORT)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8712)*

**Comment by ecoal95** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 407 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4F-0Fz_yi7grywIPE8:-K4F6m3z99MhLPSdIFho:-1154811299) ([raw file](https://github.com/servo/servo/blob/8527b7e980ace48bfb5597d954d61e6ad19265f8/components/script/dom/webglrenderingcontext.rs#L407)):*
Sorry, `s/don't define a region/define a region` here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8712)*

**Comment by simartin** [comment]
Thanks a lot for the review. Sending an updated diff shortly.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8712#-:-K4IaTlFleeun0-v-UZk:-1209313506)*

**Comment by ecoal95** [comment]
Nice work! Just some minor fixes and a little clean-up pending and I think this will be ready to merge! :)

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 7 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[components/canvas_traits/lib.rs, line 146 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4Kbassijdw86LIpK-P:-K4Kbassijdw86LIpK-Q:363071103) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/canvas_traits/lib.rs#L146)):*
Please remove this messages and associated code in `webgl_paint_task.rs` for now, until it's implemented.

---

*[components/script/dom/webglrenderingcontext.rs, line 384 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4KcWoTq31dKicbB6Vi:-K4KcWoURAl8zBwOlaZU:-1556034754) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L384)):*
This should be an `InvalidEnum` error.

Also may you add this just below this match? (just realized this validation was also missing from the initial implementation)

```
match usage {
    constants::STREAM_DRAW |
    constants::STATIC_DRAW |
    constants::DYNAMIC_DRAW => (),
    _ => return sef.webgl_error(InvalidEnum),
}
```

---

*[components/script/dom/webglrenderingcontext.rs, line 388 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4KdIuc6gW3qRLEHiGw:-K4KdIuc6gW3qRLEHiGx:1897686633) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L388)):*
Please generate an `InvalidValue` error here if you can (sorry for the extra work :/).

From the WebGL spec (5.14.5):
> If the passed data is null then an INVALID_VALUE error is generated.

---

*[components/script/dom/webglrenderingcontext.rs, line 395 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4KZLudAi8HudDsPWqk:-K4KZLudAi8HudDsPWql:-173226860) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L395)):*
May you add a comment here pointing to https://github.com/servo/servo/issues/5014? :)

---

*[components/script/dom/webglrenderingcontext.rs, line 412 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4KZnPF_MRX7BJ_3tSa:-K4KZnPF_MRX7BJ_3tSb:1009065833) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L412)):*
This should be an `InvalidEnum` error, just as above.

---

*[components/script/dom/webglrenderingcontext.rs, line 426 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4KZsnF18KeHPCjEFmI:-K4KZsnF18KeHPCjEFmJ:-248726463) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L426)):*
Same issue number than in `BufferData`.

---

*[components/script/dom/webglrenderingcontext.rs, line 432 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4Kb6HjIgbX2sAGnsqQ:-K4Kb6HjIgbX2sAGnsqR:-823026428) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L432)):*
May you add the issue number for https://github.com/servo/servo/issues/8738?

---

*[components/script/dom/webglrenderingcontext.rs, line 445 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4Kby5ZlzMpqzYwI9Is:-K4Kby5ZlzMpqzYwI9It:-1095372292) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L445)):*
Since this method always returns the same error (`InvalidEnum`), regardless of the value of `target`, I'd remove the `match` here for now, until an extension is implemented.

---

*[components/script/dom/webglrenderingcontext.rs, line 460 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4Kc2uaa4AOgAOOjx-2:-K4Kc2uaa4AOgAOOjx-3:-1677837463) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L460)):*
ditto.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8712#-:-K4Kc6Gwsz0m0gcLe-eO:1980282667)*

**Comment by simartin** [comment]
*[components/script/dom/webglrenderingcontext.rs, line 384 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4KcWoTq31dKicbB6Vi:-K4REFhsSw8uP95UOiR0:1971476185) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L384)):*
I put InvalidOperation because that's how I interpreted the following in https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.5: "A given WebGLBuffer object may only be bound to one of the ARRAY_BUFFER or ELEMENT_ARRAY_BUFFER target in its lifetime. An attempt to bind a buffer object to the other target will generate an INVALID_OPERATION error". Am I misunderstanding the sentence and its consequence on the other functions from that paragraph?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8712)*

**Comment by simartin** [comment]
*[components/script/dom/webglrenderingcontext.rs, line 412 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4KZnPF_MRX7BJ_3tSa:-K4REmQgEHEl0lRTM_e2:-2073021532) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L412)):*
Same as above

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8712)*

**Comment by ecoal95** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 384 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4KcWoTq31dKicbB6Vi:-K4Rhrmf8caL9_MWvV5Z:-202637725) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L384)):*
That means that when the buffer is bound to `ARRAY_BUFFER`, then it can't be re-bound to `ELEMENT_ARRAY_BUFFER`. That logic is already handled here: https://github.com/servo/servo/blob/master/components/script/dom/webglbuffer.rs#L59

In this case it's an `InvalidEnum` error.

---

*[components/script/dom/webglrenderingcontext.rs, line 412 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8712#-K4KZnPF_MRX7BJ_3tSa:-K4RibrzHBC5HS7JYUnB:1640817) ([raw file](https://github.com/servo/servo/blob/4fc66c780f48178f40c6f54d69a2e406104fd712/components/script/dom/webglrenderingcontext.rs#L412)):*
Same here :P

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8712#-:-K4RiiEuB73AOlDVSX38:1458266033)*

**Comment by jdm** [comment]
I agree with @ecoal95 on both points he brought up that referenced me.

**Comment by ecoal95** [comment]
Great work! Thanks @simartin :)

@bors-servo: r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8712#-:-K4d60qFonPtYzH1h2DO:108509382)*

**Pull request merged**
