### PR TITLE
Make use statements in gecko.mako.rs neater.

### PR DESCRIPTION
**Pull request by heycam**
Similarly to #13792 I find the grouped `use` statements in gecko.mako.rs hard to deal with.  Splitting these out to one per line should help avoid rebasing problems (which I sometimes get), is easier to read, and easier to keep sorted.  r? @emilio 

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13793)

### CODE REVIEW

**Comment by Manishearth** [comment]
r=me if this passes tidy locally

**Comment by heycam** [comment]
Yep, it does.

**Comment by Manishearth** [comment]
@bors-servo retry

 - #13796

**Pull request merged**
