### PR TITLE
Adding window.onstorage WindowEventHandler

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
Well it built successfully this time around :smile: @jdm . Working to solve #7994

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8038)

### CODE REVIEW

**Comment by jdm** [comment]
Great! Make sure to include the [test result changes](https://github.com/servo/servo/pull/7999#issuecomment-148051132), too!

**Comment by martiansideofthemoon** [comment]
@jdm :- Do I include it as a GithubGist? Because I cannot commit / push the log file

**Comment by jdm** [comment]
I believe there should be a new commit present in your local branch. If so, you should be able to push to github and make it appear here.

**Comment by martiansideofthemoon** [comment]
Well I'm getting a "Everything is up-to-date" message. Probably the bug fix didn't really help and those commands didn't change any file :/

**Comment by Ms2ger** [comment]
Somewhat surprisingly, this doesn't seem to have made any storage tests pass, only:
```
/html/dom/interfaces.html
-------------------------
PASS expected FAIL HTMLBodyElement interface: attribute onstorage
PASS expected FAIL HTMLBodyElement interface: document.createElement("body") must inherit property "onstorage" with the proper type (17)
```

**Comment by jdm** [comment]
You'll want to remove the appropriate lines from http://mxr.mozilla.org/servo/source/tests/wpt/metadata/html/dom/interfaces.html.ini .

**Comment by martiansideofthemoon** [comment]
@jdm Would I need to remove lines such as well?http://mxr.mozilla.org/servo/source/tests/wpt/metadata/html/dom/interfaces.html.ini#6978
http://mxr.mozilla.org/servo/source/tests/wpt/metadata/html/dom/interfaces.html.ini#7332

**Comment by jdm** [comment]
No; the tests for the properties on the Window object are failing in Servo due to #4593.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by martiansideofthemoon** [comment]
finally :smile: Any good followup bugs @jdm ?

**Pull request merged**
