### PR TITLE
Update CSS tests to revision 2ade4807c4389ff29f1ff22a9c660a8ba4703da6

### PR DESCRIPTION
**Pull request by SimonSapin**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7603)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo r+

Try run to get results changes.

**Comment by SimonSapin** [comment]
```
Unexpected Results
==================

/css-variables-1_dev/html/variable-external-font-face-01.htm
------------------------------------------------------------
PASS expected FAIL [Parent]
/css-variables-1_dev/html/variable-font-face-01.htm
---------------------------------------------------
PASS expected FAIL [Parent]
/css-variables-1_dev/html/variable-font-face-02.htm
---------------------------------------------------
PASS expected FAIL [Parent]
```

The above is https://github.com/w3c/csswg-test/pull/853 , but the rest seem to be regressions that I don’t know how to explain. @Ms2ger, should I update the expectation files anyway?

```
/css21_dev/html4/at-charset-071.htm
-----------------------------------
FAIL [Parent]
/css21_dev/html4/at-charset-072.htm
-----------------------------------
FAIL [Parent]
/css21_dev/html4/at-charset-073.htm
-----------------------------------
FAIL [Parent]
/css21_dev/html4/at-charset-074.htm
-----------------------------------
FAIL [Parent]
/css21_dev/html4/at-charset-075.htm
-----------------------------------
FAIL [Parent]
/css21_dev/html4/at-charset-076.htm
-----------------------------------
FAIL [Parent]
/css21_dev/html4/at-charset-077.htm
-----------------------------------
FAIL [Parent]
/css21_dev/html4/case-sensitive-000.htm
---------------------------------------
FAIL [Parent]
/css21_dev/html4/case-sensitive-001.htm
---------------------------------------
FAIL [Parent]
/css21_dev/html4/escapes-001.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/escapes-002.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/escapes-003.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/escapes-004.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/escapes-005.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/escapes-006.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/escapes-007.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/escapes-008.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/escapes-014.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/keywords-000.htm
---------------------------------
FAIL [Parent]
/css21_dev/html4/numbers-units-015.htm
--------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/style-attr-cascade-004.htm
-------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/style-attr-cascade-005.htm
-------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/uri-015.htm
----------------------------
FAIL [Parent]
```

**Comment by Ms2ger** [comment]
Those look like tests I recently added references to.

**Comment by Ms2ger** [comment]
Sorry, forgot about this. The others are https://github.com/w3c/csswg-test/pull/871

**Pull request closed without merging**
