### PR TITLE
Fix replacement logic when navigating nested browsing contexts

### LINKED ISSUE #22996: Traversing iframe history does not update iframe contents
I have a testcase demonstrating that calling contentWindow.history.back() with valid session history does not cause an iframe's contentWindow to be updated correctly, nor do the displayed contents of the iframe change.

### PR DESCRIPTION
**Pull request by jdm**
These changes also fix a bug where traversing the session history in a nested browsing context did not update the iframe's contentWindow appropriately.

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22996
- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22999)

### CODE REVIEW

**Comment by jdm** [comment]
r? @asajeffrey 
This is session history and window proxies for double the fun!

**Comment by asajeffrey** [comment]
Oh joy, session history. This all LGTM, might be worth running it by @cbrewster who has looked at it more recently than I have. You can r=me.

**Comment by cbrewster** [comment]
LGTM as well

**Pull request merged**
