### PR TITLE
Add support for more @font-face descriptors

### PR DESCRIPTION
**Pull request by SimonSapin**
Part of https://bugzilla.mozilla.org/show_bug.cgi?id=1290237. I’ll add conversions to `nsCSSValue` separately because that requires new C++ functions in the stylo repository.

r? @bholley 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15356)

### CODE REVIEW

**Comment by bholley** [comment]
Nice! I think Manish is probably the best person to review this.

r? @Manishearth

**Comment by SimonSapin** [comment]
```
	thread 'fetch::test_fetch_redirect_count_ceiling' panicked at 'assertion failed: !fetch_response.is_network_error()', /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/net/fetch.rs:642
```

Seems unrelated…

@bors-servo retry

**Comment by Manishearth** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 3 of 3 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/parser.rs, line 109 at r11](https://reviewable.io:443/reviews/servo/servo/15356#-Kc0lBB3AGrNBfMDFTfc:-Kc0lBB3AGrNBfMDFTfd:b-ywmhz2) ([raw file](https://github.com/servo/servo/blob/4701850f379e3de4ec51ba357ce36238ab74f899/components/style/parser.rs#L109)):*
> ```Rust
> impl<T> Parse for Vec<T> where T: Parse + CommaSeparated {
>     fn parse(context: &ParserContext, input: &mut Parser) -> Result<Self, ()> {
>         input.parse_comma_separated(|input| T::parse(context, input))
> ```

Slight issue is that we need to differentiate between vecs that are allowed to be empty and those that aren't. I guess we can always special case in the use cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15356#-:-Kc0nE9cE3MsEhkV1jw5:bnfp4nl)*

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/parser.rs, line 109 at r11](https://reviewable.io:443/reviews/servo/servo/15356#-Kc0lBB3AGrNBfMDFTfc:-Kc2Ws_2eWgm8tDFG8eV:b-cq3r68) ([raw file](https://github.com/servo/servo/blob/4701850f379e3de4ec51ba357ce36238ab74f899/components/style/parser.rs#L109)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary><blockquote>

Slight issue is that we need to differentiate between vecs that are allowed to be empty and those that aren't. I guess we can always special case in the use cases.
</blockquote></details>

What it work for you if I rename the `CommaSeparated` marker to `OneOrMoreCommaSeparated`? If needed we can also add `ZeroOrMoreCommaSeparated`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15356)*

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/parser.rs, line 109 at r11](https://reviewable.io:443/reviews/servo/servo/15356#-Kc0lBB3AGrNBfMDFTfc:-Kc2X9TAIqy9NdVq6aTV:bdze68e) ([raw file](https://github.com/servo/servo/blob/4701850f379e3de4ec51ba357ce36238ab74f899/components/style/parser.rs#L109)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

What it work for you if I rename the `CommaSeparated` marker to `OneOrMoreCommaSeparated`? If needed we can also add `ZeroOrMoreCommaSeparated`.
</blockquote></details>

Although, is there anything with zero or more components? CSS usually doesn’t like empty things, they tend to be replaced with a keyword like `normal`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15356)*

**Comment by Manishearth** [comment]
There are a couple, see the `allow_empty` param for vector longhands.

`OneOrMore...` works for me. r=me

**Pull request merged**
