### PR TITLE
Moving the error handling out of network loader

### LINKED ISSUE #8678: Move error handling out of the network loader
There are a couple steps here:
* replace the free-form string in the `Result` that network listeners receive with the LoadError type from `http_loader.rs`
* propagate the errors from `load_for_consumer` to the network receiver instead of sending a string
* convert the other network loaders to use the LoadError values
* move the SSL validation error handling into the HTML parser network listener (`servohtmlparser.rs`)
* make `headers_available` take a `Result<Metadata, LoadError>` value to reflect the possibility of early errors (such as SSL validation failure)

### LINKED ISSUE #9944: Run unit tests on appveyor
#9942 is adding windows-only unit tests, but I have no way to run them right now. We should do that as part of appveyor.

### PR DESCRIPTION
**Pull request by jdm**
Rebase of #8851. Fixes #8678. Fixes #9944.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/servo/servo/9942)

### CODE REVIEW

**Comment by jdm** [comment]
Note, currently writing tests for the security properties of chrome_loader.rs.

**Comment by jdm** [comment]
Tests written. I've reviewed all the commits by @Wafflespeanut but someone else should review my changes in the final commit.

**Comment by Ms2ger** [comment]
LGTM

**Comment by jdm** [comment]
@bors-servo: r-
It's not clear from the appveyor log that the tests actually ran.

**Comment by Ms2ger** [comment]
> Running C:/projects/servo/target\debug\deps\gfx_tests-34a41c7816b6d727.exe
> Command exited with code 127

**Comment by jdm** [comment]
Yeah. I'm guessing it's mach PATH shenanigans like all the times people have encountered that with `./mach run` on Windows.

**Comment by jdm** [comment]
I'm still futzing with this stuff, FYI. Not waiting on further review.

**Comment by larsbergstrom** [comment]
OK, ping me when it's ready!

**Comment by jdm** [comment]
This is not awaiting review; I'm just waiting on windows test results now that they actually work.

**Comment by jdm** [comment]
On all platforms:
```
---- data_loader::empty_invalid stdout ----
	thread 'data_loader::empty_invalid' panicked at 'assertion failed: `(left == right)` (left: `Done(Err(Internal("invalid data uri")))`, right: `Done(Err(Internal("Invalid Data URI")))`)', /home/travis/build/servo/servo/tests/unit/net/data_loader.rs:39
stack backtrace:
   1:     0x7fe47ba0fec0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7fe47ba1351f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7fe47ba130e3 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7fe47ba01b7c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7fe47ba02988 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7fe47ae7bff1 - data_loader::assert_parse::he7410b3801a81c9fOGa
                        at /home/travis/build/servo/servo/components/servo/<std macros>:8
   7:     0x7fe47aea4e61 - data_loader::empty_invalid::hab104979293ea79e2Oa
                        at /home/travis/build/servo/servo/tests/unit/net/data_loader.rs:50
   8:     0x7fe47b998c66 - boxed::F.FnBox<A>::call_box::h3086104596211722217
   9:     0x7fe47b99b35b - sys_common::unwind::try::try_fn::h3500291712527960233
  10:     0x7fe47ba0f14b - __rust_try
  11:     0x7fe47ba0f0dd - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  12:     0x7fe47b99b6da - boxed::F.FnBox<A>::call_box::h17872316467409945728
  13:     0x7fe47ba11ae9 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  14:     0x7fe479b4b181 - start_thread
  15:     0x7fe47966247c - __clone
  16:                0x0 - <unknown>
failures:
    data_loader::empty_invalid
```
On windows:
```
---- chrome_loader::test_valid stdout ----
	thread 'chrome_loader::test_valid' panicked at 'called `Result::unwrap()` on an `Err` value: ()', ../src/libcore\result.rs:746
stack backtrace:
   0:          0x1613d9a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x161326c - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x15d697f - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x15d7f7b - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x1605d82 - rust_begin_unwind
   5:          0x1628378 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:           0x5cf1b3 - result::unwrap_failed::h16385158986519983610
                        at ../src/libcore/macros.rs:29
   7:           0x5ceaf4 - result::Result<T, E>::unwrap::h12540842167449277427
                        at ../src/libcore/result.rs:687
   8:           0x5e3cf6 - chrome_loader::resolve_chrome_url::h6f1527eb9eda792fzea
                        at C:\projects\servo\components\net/chrome_loader.rs:29
   9:           0x402935 - chrome_loader::test_valid::hc39d1e7d9aba4bd2Wca
                        at C:\projects\servo\tests\unit\net/chrome_loader.rs:44
  10:          0x1568038 - boxed::F.FnBox<A>::call_box::h13253005572439445335
  11:          0x156a793 - sys_common::unwind::try::try_fn::h8856492297229960163
  12:          0x1605caa - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
  13:          0x156ab4a - boxed::F.FnBox<A>::call_box::h6456279283256665074
  14:          0x1611229 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  15:     0x7ffd3fa113d1 - tinfl_decompressor_free
```

**Comment by frewsxcv** [comment]
@jdm I can rebase this if you're too busy

**Comment by jdm** [comment]
The main thing that was blocking me was getting the windows-only unit test to pass. Appveyor's broken again so it's difficult to iterate on it.

**Comment by frewsxcv** [comment]
I just opened https://github.com/servo/servo/pull/10731 and am now realizing it probably overlaps with this :-/ (I hadn't really looked at this PR until now).

**Comment by jdm** [comment]
Waiting on the result of the appveyor test.

**Comment by KiChjang** [comment]
```
Ran 4682 tests finished in 361.0 seconds.
  • 4680 ran as expected. 1363 tests skipped.
  • 1 tests failed unexpectedly
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /html/browsers/browsing-the-web/scroll-to-fragid/scroll-frag-percent-encoded.html:
  └ PASS [expected FAIL] Fragment Navigation: fragment id should be percent-decoded

  ▶ FAIL [expected PASS] /_mozilla/css/incremental_trailing_whitespace_a.html
  └   → /_mozilla/css/incremental_trailing_whitespace_a.html da54041086f2975f8e3c776d2283ad6609e6862a
/_mozilla/css/incremental_trailing_whitespace_ref.html f5d0147c8bddbdc772a7e5e86c7c9e433fcd486b
Testing da54041086f2975f8e3c776d2283ad6609e6862a == f5d0147c8bddbdc772a7e5e86c7c9e433fcd486b
```

**Comment by jdm** [comment]
@bors-servo: retry
* #10753, #10473

**Pull request merged**
