### PR TITLE
Upgrade to rustc 1.48.0-nightly (623fb90b5 2020-09-26)

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/rust-lang/hashbrown/pull/159 reduced `size_of::<HashMap>()`

### CODE REVIEW

**Comment by CYBAI** [comment]
Failed in UWP builds 👀

```
error: `rust-src` component not found. Run `rustup component add rust-src`.
```

**Comment by SimonSapin** [comment]
> Failed in UWP builds eyes
> 
> ```
> error: `rust-src` component not found. Run `rustup component add rust-src`.
> ```

This is still the case even though just a few lines above we have:

```
info: downloading component 'rust-src'
info: installing component 'rust-src'
```

https://community-tc.services.mozilla.com/tasks/ZndkCKvZTTSW8dZD9P0UAA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FZndkCKvZTTSW8dZD9P0UAA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L352-391

**Comment by jdm** [comment]
Yeah, that issue showed up back in August and I have not been able to figure it out yet.

**Comment by SimonSapin** [comment]
``error: `rust-src` component not found. Run `rustup component add rust-src`.`` is still there

**Comment by SimonSapin** [comment]
If someone who has access to a Windows build environment wants to help investigate this, that would be great. Possible steps:

* Check out the repository with this PR
* Run `python mach build --dev --target=x86_64-uwp-windows-msvc`
* See if you reproduce the ``error: `rust-src` component not found`` error
* Try to find out what needs that component and why. Also why only for UWP.
* Check if `rustup component add rust-src` fixes it and enables to a successful build

Without a local Windows it’s possible to try things blindly on CI machines, but much more tedious and with a longer trial/error cycle time. If someone wants to spend that time we can probably arrange to give `try` access. Steps for that:

* Make another PR based on this one
* In `etc/taskcluster/decision_task.py`, reduce the number of redundant builds
  ```diff
   -            "try-windows": [windows_unit, windows_arm64, windows_uwp_x64],
   +            "try-windows": [windows_uwp_x64],
   ```
* Make other changes to investigate or try things
* Push to your remote branch to update the PR
* Comment <code>@</code><code>bors-servo try=windows</code> on the PR to trigger a new build

**Comment by jdm** [comment]
UWP is the only platform we install rust-src for: https://github.com/servo/servo/blob/4d7b4d249fa90fb335cfdc9f0264747eda088808/python/servo/build_commands.py#L273-L275

**Comment by SimonSapin** [comment]
Oh, right. And we do so for Xargo to be able to compile the standard library.

https://github.com/japaric/xargo/blob/master/CHANGELOG.md#v0322---2020-07-29 says "Fix for changed rustc directory layout." so it sounds like we need to update Xargo to 0.3.22.

`aws --no-sign-request s3 ls servo-deps-2/msvc-deps/` lists `xargo-v0.3.17.zip`. How was that file built?

However Xargo is also "in maintainance mode", so perhaps we should migrate to Cargo’s [`-Z build-std`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) instead?

Or even use a pre-built std like for other targets. https://doc.rust-lang.org/nightly/rustc/platform-support.html lists `x86_64-uwp-windows-msvc` with `✓` but `aarch64-uwp-windows-msvc` with `?` which means “standard library support is unknown or a work-in-progress”. Worth a try?

**Comment by SimonSapin** [comment]
Ok that last idea was short-lived.

```
error: toolchain 'nightly-2021-01-25-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'x86_64-uwp-windows-msvc'; did you mean 'x86_64-pc-windows-msvc'?
error: toolchain 'nightly-2021-01-25-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'aarch64-uwp-windows-msvc'; did you mean 'aarch64-pc-windows-msvc'?
```

**Comment by jdm** [comment]
There's a PR open where I tried using build-std and it didn't work out of the box. I never followed up on it.

**Comment by SimonSapin** [comment]
I creatied a task at https://community-tc.services.mozilla.com/tasks/create to build Xargo 0.3.22 on/for Windows:
```yaml
provisionerId: proj-servo
workerType: win2016
schedulerId: taskcluster-github
created: '2021-01-25T19:39:29.952Z'
deadline: '2021-01-26T19:39:29.952Z'
expires: '2022-01-25T19:39:29.952Z'
payload:
  mounts:
    - file: rustup-init.exe
      content:
        url: https://win.rustup.rs/x86_64
  command:
    - '%HOMEDRIVE%%HOMEPATH%\rustup-init.exe --profile=minimal -y'
    - set PATH=%HOMEDRIVE%%HOMEPATH%\.cargo\bin;%PATH%
    - |-
      cargo install xargo --version 0.3.22
      copy %HOMEDRIVE%%HOMEPATH%\.cargo\bin\xargo.exe .
  artifacts:
    - name: public/xargo.exe
      path: xargo.exe
      type: file
      expires: '2022-01-25T15:07:23.782706Z'
  maxRunTime: 5400
metadata:
  name: Xargo build for Windows
  description: ''
  owner: infra@servo.org
  source: https://community-tc.services.mozilla.com/tasks/create
```

Then created a ZIP file with the same directory structure as the previous one, uploaded it with `aws s3 cp ./xargo-v0.3.22.zip s3://servo-deps-2/msvc-deps/`, and changed the version number in `python/servo/packages.py` in this PR.

@bors-servo try=windows

**Comment by SimonSapin** [comment]
With fixed up S3 permissions…

@bors-servo retry

**Comment by SimonSapin** [comment]
I’ve filed:

* https://github.com/servo/servo/issues/28101 with details about the new panic on Windows
* https://github.com/rust-lang/rust/issues/81395 for a new rustdoc ICE in `gstreamer-video`

**Comment by SimonSapin** [comment]
I’ve reverted this to the previous toolchain from November to avoid at least https://github.com/rust-lang/rust/issues/81395. I don’t understand how we only see https://github.com/servo/servo/issues/28101 now though, since it seems related to a Rust change that landed in Nightly in March. Let’s see

@bors-servo try

**Comment by SimonSapin** [comment]
```
error[E0432]: unresolved import `SetThreadStackGuarantee`
    --> C:\Users\task_1611644854\.rustup\toolchains\nightly-2020-11-12-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\c.rs:1038:12
     |
1038 |     pub fn SetThreadStackGuarantee(_size: *mut c_ulong) -> BOOL {
     |            ^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type `SetThreadStackGuarantee`
```

Looks fixed by https://github.com/rust-lang/rust/pull/79205

**Comment by SimonSapin** [comment]
Moving *back* to nightly-2020-09-27 which is just before https://github.com/servo/servo/issues/28101 starts causing runtime panics (though it’s still UB).

@bors-servo try

**Comment by SimonSapin** [comment]
I’m seeing a semi-high rate (3 out of ~29, I re-ran those tasks) of intermittent network errors while `curl` in a WPT task downloads the build artifact from a compile task.

```
+ curl --compressed --retry 5 --connect-timeout 10 -Lf https://community-tc.services.mozilla.com/api/queue/v1/task/ATIHs5PXRwys0nHvE05M3Q/artifacts/public/target.tar.gz -o target.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   115  100   115    0     0   1084      0 --:--:-- --:--:-- --:--:--  1084
  0 95.5M    0 16987    0     0  26459      0  1:03:04 --:--:--  1:03:04 26459
 28 95.5M   28 26.8M    0     0  16.4M      0  0:00:05  0:00:01  0:00:04 27.0M
 30 95.5M   30 29.4M    0     0  16.9M      0  0:00:05  0:00:01  0:00:04 26.9M
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
```

Another WPT failure is a font-related panic. I don’t know if it’s intermittent.

```rust
  │ Failed to receive a response from live font cache (thread StyleThread#0, at components/gfx/font_cache_thread.rs:513)
  │    0: servo::backtrace::print
  │    1: servo::main::{{closure}}
  │    2: std::panicking::rust_panic_with_hook
  │              at /rustc/623fb90b5a1f324e0ec44085116bf858cef19a00/library/std/src/panicking.rs:581:17
  │    3: std::panicking::begin_panic::{{closure}}
  │    4: std::sys_common::backtrace::__rust_end_short_backtrace
  │    5: std::panicking::begin_panic
  │    6: <gfx::font_cache_thread::FontCacheThread as gfx::font_context::FontSource>::get_font_instance
  │    7: gfx::font_context::FontContext<S>::font
  │    8: std::thread::local::LocalKey<T>::with
  │    9: layout::flow::inline::TextRun::break_and_shape
```

r? @jdm

**Comment by SimonSapin** [comment]
`Running target/debug/deps/hang_monitor_tests-0db0d021ed42143c` on macOS seems to be hanging, twice in a row

**Comment by SimonSapin** [comment]
This failure seems to happen reliably on macOS:

```
     Running target/debug/deps/hang_monitor_tests-0db0d021ed42143c
running 3 tests
test test_hang_monitoring_unregister ... test test_hang_monitoring_unregister has been running for over 60 seconds
test test_hang_monitoring_exit_signal ... test test_hang_monitoring_exit_signal has been running for over 60 seconds
test test_hang_monitoring ... test test_hang_monitoring has been running for over 60 seconds
[taskcluster:error] Aborting task...
[taskcluster 2021-01-26T19:29:18.556Z] Task Duration: 1h59m59.914749827s
[taskcluster:error] Task aborted - max run time exceeded
```

**Comment by jdm** [comment]
This can't merge until someone figures out why the unit test is breaking on macOS.

**Comment by jdm** [comment]
I have not been able to reproduce the unit test timeout on my mac :(

**Comment by SimonSapin** [comment]
:shrug:

**Pull request merged**
