### PR TITLE
Update rust-selectors

### PR DESCRIPTION
**Pull request by SimonSapin**
Update for https://github.com/servo/rust-selectors/pull/37

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6700)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@Ms2ger r?

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/layout/css/matching.rs, line 20 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6700#-Juqq4EmRxUItQr6uFzq)** ([raw file](https://github.com/servo/servo/blob/bbb03d3164061ea7bafcf7f8299019272424d9c2/components/layout/css/matching.rs#L20)):</sup>
Nit: lose the `{}`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6700)

**Comment by jdm** [comment]
```
failures:
    first_child_pseudo_a.html == first_child_pseudo_b.html
    first_of_type_pseudo_a.html == first_of_type_pseudo_b.html
    last_child_pseudo_a.html == last_child_pseudo_b.html
    last_of_type_pseudo_a.html == last_of_type_pseudo_b.html
    nth_child_pseudo_a.html == nth_child_pseudo_b.html
    nth_last_child_pseudo_a.html == nth_last_child_pseudo_b.html
    nth_last_of_type_pseudo_a.html == nth_last_of_type_pseudo_b.html
    nth_of_type_pseudo_a.html == nth_of_type_pseudo_b.html
    only_of_type_pseudo_a.html == only_of_type_pseudo_b.html
```

**Comment by SimonSapin** [comment]
Added a commit. `mach test-ref` passes locally.

**Pull request merged**
