### PR TITLE
style: Less messy namespace handling.

### PR DESCRIPTION
**Pull request by emilio**
This PR accounts for the fact that the namespace table is only needed in
`NestedRuleParser`, and only for style rules, in order to simplify the setup and
be able to fix a few bugs wrt parsing of invalid rules.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18142)

### CODE REVIEW

**Comment by emilio** [comment]
or, @SimonSapin

**Comment by SimonSapin** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/style/stylesheets/rule_parser.rs, line 242 at r1](https://reviewable.io:443/reviews/servo/servo/18142#-KrpWxgDgnNzqsmgj9cB:-KrpWxgDgnNzqsmgj9cC:bdwpo5i) ([raw file](https://github.com/servo/servo/blob/36dad96c4ef54e4b7e2a8bec1b6f29426d1ef0d5/components/style/stylesheets/rule_parser.rs#L242)):*
> ```Rust
>         // "Freeze" the namespace map (no more namespace rules can be parsed
>         // after this point), and stick it in the context.
>         if self.namespaces.is_some() {
> ```

Should this be in the previous commit?

---

*[ports/geckolib/glue.rs, line 1515 at r3](https://reviewable.io:443/reviews/servo/servo/18142#-KrpcdqFK6H-ryXtT2RU:-KrpcdqG6SrsUSmLpIvy:b2e8qt4) ([raw file](https://github.com/servo/servo/blob/99f0fcc90c6031cbe39d1ecf3dcd3ef44096d3f7/ports/geckolib/glue.rs#L1515)):*
> ```Rust
>     //
>     // We seem to ignore it, but someone could still set content: attr(..) from
>     // a declaration inside the keyframe block.
> ```

Right, this looks like a bug. `Keyframe::parse` should use the namespace map from `StylesheetContents`.

---

*[ports/geckolib/glue.rs, line 2819 at r3](https://reviewable.io:443/reviews/servo/servo/18142#-KrpbYEamzh8URiV6wRD:-KrpbYEbYL7XwHUPSWSR:b-xexdtg) ([raw file](https://github.com/servo/servo/blob/99f0fcc90c6031cbe39d1ecf3dcd3ef44096d3f7/ports/geckolib/glue.rs#L2819)):*
> ```Rust
>         let url_data = unsafe { dummy_url_data() };
>         let reporter = NullReporter;
>         // FIXME(emilio): What about namespaces? (Does it even matter?)
> ```

The `CSS.supports` API is not associated to any stylesheet, so there is no `@namespace` rule in scope. (Please change this comment to that.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18142)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 7 of 7 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18142#-:-KrpmAdgCTgc95ZMBTAG:bkg9nno)*

**Comment by jdm** [comment]
```
  ▶ CRASH [expected OK] /cssom/CSS.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ assertion failed: `(left == right)`
  │   left: `Supports`,
  │  right: `Style` (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /home/servo/buildbot/slave/linux-rel-wpt/build/components/style/stylesheets/supports_rule.rs:245)
  │ stack backtrace:
  │    0:     0x7f42393abf1c - backtrace::backtrace::trace::hda211579ee718fec
  │    1:     0x7f42393abf52 - backtrace::capture::Backtrace::new::h66f10ff730bd3424
  │    2:     0x7f4237135b2e - servo::main::{{closure}}::h981a6aa510b5435c
  │    3:     0x7f42393f2616 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:611
  │    4:     0x7f42393f2434 - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:571
  │    5:     0x7f42393f23a9 - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:521
  │    6:     0x7f4238bc2387 - style::stylesheets::supports_rule::Declaration::eval::hf61923580e2c9b49
  │    7:     0x7f4238bc129c - style::stylesheets::supports_rule::SupportsCondition::eval::he93f2908527574c5
  │    8:     0x7f423761af98 - std::panicking::try::do_call::h7a9042dc6da37cae
  │    9:     0x7f42393f96cc - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:98
  │   10:     0x7f4237c95873 - script::dom::bindings::codegen::Bindings::CSSBinding::CSSBinding::supports::hb6b1e05aebeeaa0a
  │   11:     0x7f4238346e60 - CallJSNative
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  │                          - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  │   12:     0x7f42383397de - CallFromStack
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
  │                          - Interpret
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2873
  │   13:     0x7f4238346a2b - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  │   14:     0x7f4238346c08 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:471
  │   15:     0x7f4238347014 - _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
  │   16:     0x7f4238244cef - _ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:1325
  │   17:     0x7f4238346e60 - CallJSNative
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  │                          - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  │   18:     0x7f42383397de - CallFromStack
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
  │                          - Interpret
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2873
  │   19:     0x7f4238346a2b - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  │   20:     0x7f423834def8 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_16AbstractFramePtrEPS9_
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:679
  │   21:     0x7f423834e027 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:712
  │   22:     0x7f42381bf038 - Evaluate
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4407
  │   23:     0x7f42381bf596 - Evaluate
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4443
  │                          - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4501
  │   24:     0x7f4237a7815b - script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result::{{closure}}::h2c2acd2fa1cf8f55
  │   25:     0x7f4237a77e8d - script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result::h5bb08b215c92e400
  │   26:     0x7f4237ae650c - script::dom::htmlscriptelement::HTMLScriptElement::run_a_classic_script::h01dc204fa7896f3c
  │   27:     0x7f4237ae557d - script::dom::htmlscriptelement::HTMLScriptElement::execute::hbc61f7e8585f0f52
  │   28:     0x7f4237ae2005 - script::dom::htmlscriptelement::HTMLScriptElement::prepare::h1817b0a5bdde4134
  │   29:     0x7f4237b66020 - script::dom::servoparser::ServoParser::do_parse_sync::h2541d89abec87633
  │   30:     0x7f4237b65be6 - script::dom::servoparser::ServoParser::parse_sync::hd2a8a6f22807e179
  │   31:     0x7f4237b64060 - script::dom::servoparser::ServoParser::resume_with_pending_parsing_blocking_script::h2d33f1aa2cfd7ffe
  │   32:     0x7f4237a266ba - script::dom::document::Document::process_pending_parsing_blocking_script::hcb4d8423d77b82e1
  │   33:     0x7f4237a26291 - script::dom::document::Document::pending_parsing_blocking_script_loaded::hc62c8fe58509a141
  │   34:     0x7f4237ae08e4 - <script::dom::htmlscriptelement::ScriptContext as net_traits::FetchResponseListener>::process_response_eof::h0bcdb42f961a5ccd
  │   35:     0x7f4237c2398b - <script::network_listener::ListenerRunnable<A, Listener> as script::script_thread::Runnable>::handler::hd7ac4fb7d3a6872a
  │   36:     0x7f4237c2847f - <script::script_thread::CancellableRunnable<T> as script::script_thread::Runnable>::main_thread_handler::h55da876d116fde42
  │   37:     0x7f4237c45ce2 - script::script_thread::ScriptThread::handle_msg_from_script::h753c1af157ca8db5
  │   38:     0x7f4237c3dffe - script::script_thread::ScriptThread::handle_msgs::{{closure}}::h7b8fe1df806a62f5
  │   39:     0x7f4237c3a52f - script::script_thread::ScriptThread::handle_msgs::hcce290a7cdefc184
  │   40:     0x7f4237c359eb - script::script_thread::ScriptThread::start::hcdaeed7dbd2e7032
  │   41:     0x7f423751fdff - std::sys_common::backtrace::__rust_begin_short_backtrace::h7eb35c9319e17ad1
  │   42:     0x7f42376e35e5 - std::panicking::try::do_call::hd8c993ca6ec81a90
  │   43:     0x7f42393f96cc - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:98
  │   44:     0x7f42378606a2 - <F as alloc::boxed::FnBox<A>>::call_box::hcb2a16171be9bdd0
  │   45:     0x7f42393f12cb - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /checkout/src/liballoc/boxed.rs:692
  │                          - std::sys_common::thread::start_thread
  │                         at /checkout/src/libstd/sys_common/thread.rs:21
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:84
  │   46:     0x7f4234e11183 - start_thread
  │   47:     0x7f4234927ffc - clone
  │   48:                0x0 - <unknown>
  │ ERROR:servo: assertion failed: `(left == right)`
  │   left: `Supports`,
  │  right: `Style`
  └ Pipeline failed in hard-fail mode.  Crashing!
```

**Comment by jdm** [comment]
```
  ▶ CRASH [expected OK] /quirks-mode/supports.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ assertion failed: `(left == right)`
  │   left: `Supports`,
  │  right: `Style` (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }, at /home/servo/buildbot/slave/linux-rel-wpt/build/components/style/stylesheets/supports_rule.rs:245)
  │ stack backtrace:
  │    0:     0x7ff0a983bf1c - backtrace::backtrace::trace::hda211579ee718fec
  │    1:     0x7ff0a983bf52 - backtrace::capture::Backtrace::new::h66f10ff730bd3424
  │    2:     0x7ff0a75c5b2e - servo::main::{{closure}}::h981a6aa510b5435c
  │    3:     0x7ff0a9882616 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:611
  │    4:     0x7ff0a9882434 - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:571
  │    5:     0x7ff0a98823a9 - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:521
  │    6:     0x7ff0a9052387 - style::stylesheets::supports_rule::Declaration::eval::hf61923580e2c9b49
  │    7:     0x7ff0a7aaad5c - std::panicking::try::do_call::h7a9042dc6da37cae
  │    8:     0x7ff0a98896cc - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:98
  │    9:     0x7ff0a8125873 - script::dom::bindings::codegen::Bindings::CSSBinding::CSSBinding::supports::hb6b1e05aebeeaa0a
  │   10:     0x7ff0a87d6e60 - CallJSNative
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  │                          - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  │   11:     0x7ff0a87c97de - CallFromStack
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
  │                          - Interpret
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2873
  │   12:     0x7ff0a87d6a2b - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  │   13:     0x7ff0a87d6c08 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:471
  │   14:     0x7ff0a87d7014 - _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:517
  │   15:     0x7ff0a86d4cef - _ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsfun.cpp:1325
  │   16:     0x7ff0a87d6e60 - CallJSNative
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jscntxtinlines.h:232
  │                          - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:453
  │   17:     0x7ff0a87c97de - CallFromStack
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:504
  │                          - Interpret
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:2873
  │   18:     0x7ff0a87d6a2b - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:399
  │   19:     0x7ff0a87ddef8 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_16AbstractFramePtrEPS9_
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:679
  │   20:     0x7ff0a87de027 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/vm/Interpreter.cpp:712
  │   21:     0x7ff0a864f038 - Evaluate
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4407
  │   22:     0x7ff0a864f596 - Evaluate
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4443
  │                          - _ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsmNS_13MutableHandleINS_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/834ce35/mozjs/js/src/jsapi.cpp:4501
  │   23:     0x7ff0a7f0815b - script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result::{{closure}}::h2c2acd2fa1cf8f55
  │   24:     0x7ff0a7f07e8d - script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result::h5bb08b215c92e400
  │   25:     0x7ff0a7f7650c - script::dom::htmlscriptelement::HTMLScriptElement::run_a_classic_script::h01dc204fa7896f3c
  │   26:     0x7ff0a7f7557d - script::dom::htmlscriptelement::HTMLScriptElement::execute::hbc61f7e8585f0f52
  │   27:     0x7ff0a7f72005 - script::dom::htmlscriptelement::HTMLScriptElement::prepare::h1817b0a5bdde4134
  │   28:     0x7ff0a7ff6020 - script::dom::servoparser::ServoParser::do_parse_sync::h2541d89abec87633
  │   29:     0x7ff0a7ff5be6 - script::dom::servoparser::ServoParser::parse_sync::hd2a8a6f22807e179
  │   30:     0x7ff0a7ff4060 - script::dom::servoparser::ServoParser::resume_with_pending_parsing_blocking_script::h2d33f1aa2cfd7ffe
  │   31:     0x7ff0a7eb66ba - script::dom::document::Document::process_pending_parsing_blocking_script::hcb4d8423d77b82e1
  │   32:     0x7ff0a7eb6291 - script::dom::document::Document::pending_parsing_blocking_script_loaded::hc62c8fe58509a141
  │   33:     0x7ff0a7f708e4 - <script::dom::htmlscriptelement::ScriptContext as net_traits::FetchResponseListener>::process_response_eof::h0bcdb42f961a5ccd
  │   34:     0x7ff0a80b398b - <script::network_listener::ListenerRunnable<A, Listener> as script::script_thread::Runnable>::handler::hd7ac4fb7d3a6872a
  │   35:     0x7ff0a80b847f - <script::script_thread::CancellableRunnable<T> as script::script_thread::Runnable>::main_thread_handler::h55da876d116fde42
  │   36:     0x7ff0a80d5ce2 - script::script_thread::ScriptThread::handle_msg_from_script::h753c1af157ca8db5
  │   37:     0x7ff0a80cdffe - script::script_thread::ScriptThread::handle_msgs::{{closure}}::h7b8fe1df806a62f5
  │   38:     0x7ff0a80ca52f - script::script_thread::ScriptThread::handle_msgs::hcce290a7cdefc184
  │   39:     0x7ff0a80c59eb - script::script_thread::ScriptThread::start::hcdaeed7dbd2e7032
  │   40:     0x7ff0a79afdff - std::sys_common::backtrace::__rust_begin_short_backtrace::h7eb35c9319e17ad1
  │   41:     0x7ff0a7b735e5 - std::panicking::try::do_call::hd8c993ca6ec81a90
  │   42:     0x7ff0a98896cc - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:98
  │   43:     0x7ff0a7cf06a2 - <F as alloc::boxed::FnBox<A>>::call_box::hcb2a16171be9bdd0
  │   44:     0x7ff0a98812cb - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /checkout/src/liballoc/boxed.rs:692
  │                          - std::sys_common::thread::start_thread
  │                         at /checkout/src/libstd/sys_common/thread.rs:21
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:84
  │   45:     0x7ff0a52a1183 - start_thread
  │   46:     0x7ff0a4db7ffc - clone
  │   47:                0x0 - <unknown>
  │ ERROR:servo: assertion failed: `(left == right)`
  │   left: `Supports`,
  │  right: `Style`
  └ Pipeline failed in hard-fail mode.  Crashing!
```

**Comment by emilio** [comment]
Gah, of course I only looked at the Gecko callers. Fix:

```diff
diff --git a/components/script/dom/css.rs b/components/script/dom/css.rs
index 0ee5a95366..e1d9b98f6d 100644
--- a/components/script/dom/css.rs
+++ b/components/script/dom/css.rs
@@ -36,9 +36,13 @@ impl CSS {
         decl.push_str(&value);
         let decl = Declaration(decl);
         let url = win.Document().url();
-        let context = ParserContext::new_for_cssom(&url, win.css_error_reporter(), Some(CssRuleType::Supports),
-                                                   PARSING_MODE_DEFAULT,
-                                                   QuirksMode::NoQuirks);
+        let context = ParserContext::new_for_cssom(
+            &url,
+            win.css_error_reporter(),
+            Some(CssRuleType::Style),
+            PARSING_MODE_DEFAULT,
+            QuirksMode::NoQuirks
+        );
         decl.eval(&context)
     }
```

**Comment by emilio** [comment]
Err, of course I only changed one of the two CSS.supports overloads...

@bors-servo r=SimonSapin

**Pull request merged**
