### PR TITLE
Remove logic from webrender_helpers.rs

### PR DESCRIPTION
**Pull request by pyfisch**
This PR is the first step in resolving the TODO at the top of the *webrender_helpers.rs* file.
> TODO(gw): This contains helper traits and implementations for converting Servo display lists
>           into WebRender display lists. In the future, this step should be completely removed.
>           This might be achieved by sharing types between WR and Servo display lists, or
>           completely converting layout to directly generate WebRender display lists, for example.

It moves logic outside of the helper file into the *display_list_builder.rs*. Where possible intermediate types are removed and webrender types are used. Inside display list types `LayoutPoint` and friends are used like in webrender. This PR will make it easier to completely remove intermediate display lists in servo.

There is a [FIXME](https://github.com/pyfisch/servo/blob/674efa355a8abd234677a8a689fcdc8511528153/components/layout/webrender_helpers.rs#L114) in *webrender_helpers.rs* depending on servo/webrender#1244.

The `derive(HeapSizeOf)` was removed from display list types because it is unused and made it impossible to use some webrender types inside of them since they do not implement it.

This is similar to #14546 by @pcwalton but does not completely replace old display lists yet.

If this changeset is too big it can also be merged in steps since all commits leave servo in a working condition.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] These changes do not require tests because: *refactor*

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16838)

### CODE REVIEW

**Comment by pyfisch** [comment]
The failed test (`border_radius_overlapping_a.html`) is caused by an real, visible rendering difference. I am looking into it.

**Comment by pyfisch** [comment]
Bug fixed.

@bors-servo try

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css21_dev/html4/content-counter-001.htm
  └   → /css21_dev/html4/content-counter-001.htm 6ffd149b98163c5f4e53e43ef62c3d892e2d22de
/css21_dev/html4/reference/content-counter-001-ref.htm 343acac52510837d414a99903bb2a92b951ac171
Testing 6ffd149b98163c5f4e53e43ef62c3d892e2d22de == 343acac52510837d414a99903bb2a92b951ac171
```

**Comment by pyfisch** [comment]
@jdm I can not reproduce the failed test on my computer. The two images are the same. Does the test fail for you?

How can I look if other platforms also failed without a direct link?

**Comment by emilio** [comment]
Can you rebase? It may just be an intermittent issue.

**Comment by pyfisch** [comment]
Rebased.

@bors-servo try

**Comment by pyfisch** [comment]
A different test this time with a timeout :confounded: So try again.

@bors-servo try

**Comment by pyfisch** [comment]
Second failure was no timeout but also the same failed test. I clicked the wrong link. The test "/css21_dev/html4/content-counter-001.htm" always fails with the same hashes.

**Comment by emilio** [comment]
So analyzing the log with http://hoppipolla.co.uk/410/reftest-analyser-structured.xhtml (you can upload the `test-css.log` file there), it seems that there's a slight mismatch in the position of one of the letters, so it could be a rounding issue.

I know we've had similar issues in the past on Mac, not sure if it's acceptable to just mark it as failing on Mac.

screenshot from 2017-05-14 17-09-46

**Comment by pyfisch** [comment]
Well it definitely could be rounding since I changed some coordinates to use floating point variables like webrender. There are a few calculations done with these numbers, it seems unlikely that this is the only time this causes problems.

> I know we've had similar issues in the past on Mac, not sure if it's acceptable to just mark it as failing on Mac.

I am curious since the test passes on Linux and Windows, do floating point numbers work differently on Mac?

**Comment by emilio** [comment]
> I am curious since the test passes on Linux and Windows, do floating point numbers work differently on Mac?

No, but font rendering does.

**Comment by pyfisch** [comment]
@glennw have you had a look at this?

**Comment by glennw** [comment]
@pyfisch Sorry, I missed this somehow! In general it looks good to me - let's get it rebased, and do another try run. Then we can take a look at any remaining test differences and try to track down what is causing them.

**Comment by pyfisch** [comment]
Rebased. (Removed some patches because they were to difficult to merge)

**Comment by pyfisch** [comment]
Note the tests pass because the patch causing the failure is no longer part of the PR.

**Comment by emilio** [comment]
On Thu, May 25, 2017 at 06:58:09AM -0700, Pyfisch wrote:
> Note the tests pass because the patch causing the failure is no longer part of the PR.

Which patch was causing the failure? Could you open an issue for that?

Thanks!

**Comment by pyfisch** [comment]
> Which patch was causing the failure?

It was the patch replacing `Rect<Au>` with `LayoutRect`. The hash is 4b603a1e063dd5d6890ad46d14d0da03469c83db. I am not sure what the issue will say: Applying this patch causes that test to fail?

Maybe I will continue to work to remove the webrender_helper file but only in smaller increments since rebasing these commits was a nightmare. In this case I will propose something similar.

**Comment by pyfisch** [comment]
Closing for lack of activity. Would need a rebase.

**Pull request closed without merging**
