### PR TITLE
Don't promote all scrollable regions to stacking contexts

### LINKED ISSUE #13529: Should be able to interleave scroll frame contents with unscrolled elements from outside the scroll frame
This will probably be addressed by @mrobinson's "scroll frames shouldn't build stacking contexts" work, but I made a testcase so I may as well file a bug for it.

In this testcase, during scrolling, the blue element should be underneath the yellow circle, but the green element should be on top of the yellow circle: https://jsfiddle.net/mstange/e52gpo6j/1/

``` html
<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<title>Scroll frame contents can be interleaved by unscrolled elements</title>

<style>

.scrollbox {
  margin-left: 100px;
  width: 300px;
  height: 400px;
  overflow: auto;
  border: 1px solid black;
}

.scrolledContent {
  padding: 200px 0;
  height: 1000px;
}

.layer {
  height: 40px;
  margin: 10px;
  border: 1px solid rgba(0, 0, 0, 0.3);
}

.bottom {
  background-color: blue;
}

.middle {
  background-color: rgba(255, 255, 0, 0.9);
  position: absolute;
  top: 50px;
  left: 30px;
  width: 150px;
  height: 150px;
  border-radius: 100%;
}

.top {
  background-color: lime;
  position: relative;
  z-index: 1;
}

</style>

<div class="scrollbox">
  <div class="scrolledContent">
    <div class="layer bottom"></div>
    <div class="layer top"></div>
  </div>
</div>

<div class="layer middle"></div>
```

### PR DESCRIPTION
**Pull request by mrobinson**
Don't promote all scrollable regions to stacking contexts
    
Instead annotate all flows with their owning ScrollRoots. When
processing the display list items into a flattened display list, we add
PushScrollRoot and PopScrollRoot to signal when scrolling regions start
and end. It is possible for content from different scrolling regions to
intersect and when they do, the stack of scrolling regions is
duplicated.  When these duplicated scrolling regions stacks reach
WebRender, it will scroll them in tandem.
    
The PushScrollRoot and PopScrollRoot items are currently represented as
StackingContexts in WebRender, but eventually these will be replaced
with special WebRender display items.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13529 and #13298. (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14084)

### CODE REVIEW

**Comment by mrobinson** [comment]
@pcwalton or @glennw r?

**Comment by glennw** [comment]
@mrobinson Did any shaders need to be copied across with the WR update?

**Comment by mrobinson** [comment]
@glennw No, I do not think any shaders where updated. I'm looking rayon issue now.

**Comment by mrobinson** [comment]
@glennw Actually, yes! Some shaders were updated. I was copying them into the wrong checkout of Servo. I'll update the branch.

**Comment by glennw** [comment]
@mrobinson OK, once the shaders are copied across let's issue a try run and I'll review in the morning. Thanks!

**Comment by mrobinson** [comment]
@glennw Thanks!

**Comment by jdm** [comment]
Filed #14118 for the previous failure.

**Comment by glennw** [comment]
@bors-servo retry
 * https://github.com/servo/servo/issues/14118

**Comment by glennw** [comment]
@mrobinson Awesome! The code looks good. We don't have great test coverage for scroll issues, but I tested manually on a number of sites, including browser.html and all seemed good from what I could see.

**Pull request merged**
