### PR TITLE
resources: Give button elements `white-space: normal` again.

### PR DESCRIPTION
**Pull request by pcwalton**
Fixes Twitter.

Originally regressed in 0a86543e6decf02860a5a98c46e01940e79af6fa.

r? @metajack

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13445)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* #13479

**Comment by larsbergstrom** [comment]
@bors-servo retry
- infra

**Pull request merged**
