### PR TITLE
Update webrender to master

### PR DESCRIPTION
**Pull request by emilio**
I'll rebase #10224 against it.

Sorry for the blocking of #10224, I expected it to be reviewed way sooner, my fault for landing breaking changes.

r? @nox or @pcwalton

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10302)

### CODE REVIEW

**Comment by nox** [comment]
Why do we need the duplicated xml-rs and gl_generator though?

**Comment by emilio** [comment]
Gleam update upgraded gl generator, and a bunch of deps still haven't

**Comment by emilio** [comment]
(And gl generator depends on xml-rs)

**Comment by nox** [comment]
Oh it's only codegen stuff, I guess that's ok.

@bors-servo r+

**Comment by nox** [comment]
```
Unexpected dynamic symbols in binary: glGenVertexArrays, glBindVertexArray, glDeleteVertexArrays, glVertexAttribDivisor, glDrawArraysInstanced
```

**Pull request merged**
