### PR TITLE
Implement meta referrer policy delivery (3)

### LINKED ISSUE #10311: Implement referrer policy
See https://w3c.github.io/webappsec-referrer-policy/

Necessary for https://github.com/servo/servo/issues/10309#issuecomment-203929226

### PR DESCRIPTION
**Pull request by rebstar6**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #10311 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11468)

### CODE REVIEW

**Comment by rebstar6** [comment]
@nox - new (old) issue!

**Comment by nox** [comment]
Please squash the two commits together.

-S-awaiting-review +S-needs-code-changes +S-needs-squash 

<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> @nox - new (old) issue!
</details>


---

Reviewed 8 of 8 files at r1, 48 of 48 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/msg/constellation_msg.rs, line 355 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KInt_g46nI76EgwJHyL:-KInt_g46nI76EgwJHyM:-1813151561) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/msg/constellation_msg.rs#L355)):*
> ```Rust
> /// [Policies](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-states)
> /// for providing a referrer header for a request
> #[derive(HeapSizeOf, Clone, Deserialize, Serialize, Debug, Copy)]
> ```

Nit: alphanumeric order.

---

*[components/script/dom/document.rs, line 2804 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KInvBP0VGedX9RrJxai:-KInvBP0VGedX9RrJxaj:13282120) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/script/dom/document.rs#L2804)):*
> ```Rust
>     fn Referrer(&self) -> DOMString {
>         //TODO - unimplemented, for ref pol tests
>         DOMString::new()
> ```

Why don't we implement that?  Should we remove it altogether for now if we can't? Or does that mean new test hacks?

---

*[components/script/dom/htmlmetaelement.rs, line 100 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KIntrE1zsUlorwITyoh:-KIntrE1zsUlorwITyoi:1255712124) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/script/dom/htmlmetaelement.rs#L100)):*
> ```Rust
>         https://html.spec.whatwg.org/multipage/#meta-referrer
>         https://w3c.github.io/webappsec-referrer-policy/#set-referrer-policy
>         */
> ```

So the spec is pretty clear, conceptually, the meta referrer policy is the referrer policy of the first `meta name="referrer"` element which satisfies all the conditions.

You should write a method on `HTMLHeadElement` that returns the first referrer policy it finds among the element children, and call this whenever there is a mutation somewhere that could change the referrer policy.

To do the second part, you will need to patch `attribute_mutated`, `bind_from_tree` and `unbind_from_tree` in the implementation of `VirtualMethods` for `HTMLMetaElement`.

---

*[components/script/dom/xmlhttprequest.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KInufwFJO5AxWuLZu96:-KInufwFJO5AxWuLZu97:-454035262) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/script/dom/xmlhttprequest.rs#L158)):*
> ```Rust
>     fn new_inherited(global: GlobalRef) -> XMLHttpRequest {
>         //TODO - will this panic (outside of the scope of the ref policy tests)?
>         let current_doc = global.as_window().Document();
> ```

```rust
let (referrer_policy, referrer_url) = if let GlobalRef::Window(window) = global {
    let document = window.Document();
    (document.url().clone(), document.get_referrer_policy())
} else {
    (None, None)
};
```

And please put a todo about doing this correctly for workers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468#-:-KInvaARN2Thgl04P8Ei:2031902149)*

**Comment by rebstar6** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/msg/constellation_msg.rs, line 355 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KInt_g46nI76EgwJHyL:-KJ6JSRf8X5HOOyh8Nwc:-499146009) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/msg/constellation_msg.rs#L355)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Nit: alphanumeric order.
</details>
Done.

---

*[components/script/dom/document.rs, line 2804 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KInvBP0VGedX9RrJxai:-KJ6JWqxmifwWCXqkE0V:-386032682) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/script/dom/document.rs#L2804)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Why don't we implement that?  Should we remove it altogether for now if we can't? Or does that mean new test hacks?
</details>
I believe it is required for test hacks (@jdm can confirm). Implementing requires passing info from http_loader through to document, which is also required to implement referrer policy deliver via header. Given that, I was planning to group those two into the next PR.

---

*[components/script/dom/htmlmetaelement.rs, line 100 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KIntrE1zsUlorwITyoh:-KJ6L1na8amUminuFrfJ:897027343) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/script/dom/htmlmetaelement.rs#L100)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> So the spec is pretty clear, conceptually, the meta referrer policy is the referrer policy of the first `meta name="referrer"` element which satisfies all the conditions.
> 
> You should write a method on `HTMLHeadElement` that returns the first referrer policy it finds among the element children, and call this whenever there is a mutation somewhere that could change the referrer policy.
> 
> To do the second part, you will need to patch `attribute_mutated`, `bind_from_tree` and `unbind_from_tree` in the implementation of `VirtualMethods` for `HTMLMetaElement`.
</details>
Pushing other changes - this is still TODO

---

*[components/script/dom/xmlhttprequest.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KInufwFJO5AxWuLZu96:-KJ6KrbrdNCHajKri83y:-499146009) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/script/dom/xmlhttprequest.rs#L158)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> ```rust
> let (referrer_policy, referrer_url) = if let GlobalRef::Window(window) = global {
>     let document = window.Document();
>     (document.url().clone(), document.get_referrer_policy())
> } else {
>     (None, None)
> };
> ```
> 
> And please put a todo about doing this correctly for workers.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468)*

**Comment by jdm** [comment]
The mozilla-specific tests were modified to not require document.referrer any more, so I think it would make sense to remove the stub implementation.

**Comment by nox** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/document.rs, line 2804 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KInvBP0VGedX9RrJxai:-KJAQ4Le1a4b1ictIvd6:-1297058508) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/script/dom/document.rs#L2804)):*
<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> I believe it is required for test hacks (@jdm can confirm). Implementing requires passing info from http_loader through to document, which is also required to implement referrer policy deliver via header. Given that, I was planning to group those two into the next PR.
</details>
@jdm says it can apparently be removed altogether for now, given we modified the tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468)*

**Comment by rebstar6** [comment]
Review status: 53 of 56 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/htmlmetaelement.rs, line 100 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KIntrE1zsUlorwITyoh:-KJBcD3OIhRX4quG-5CP:-699311926) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/script/dom/htmlmetaelement.rs#L100)):*
<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> Pushing other changes - this is still TODO
</details>
Ok see latest commit - moved logic into HTMLHeadElement with a call from HTMLMetaElement. Still need to add calls within attribute_mutated and unbind_from_tree, but that should be quick if this piece looks right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468)*

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

Ssssssh... Do you hear it? Do you hear the merge coming to us, slowly but surely? :)

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/htmlheadelement.rs, line 43 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJBdDuBuErOOuXysSjm:-KJBdDuCuEOoW5ZkdGDW:1875499637) ([raw file](https://github.com/servo/servo/blob/1f01c8842a2f1ee08af88f91f38868c81838df4c/components/script/dom/htmlheadelement.rs#L43)):*
> ```Rust
>     pub fn set_document_referrer(&self) {
>         //TODO is this THE head element, or any? If any, should confirm it's the one
>         //on second thought, may not matter if this is only called from the metaelements
> ```

I think you can instead call this from `HTMLMetaElement` if the parent of the `meta` element is a `head`, and check here whether that `head` is *the* `head` element.

---

*[components/script/dom/htmlheadelement.rs, line 50 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJBdTeADWxEEp5f-b8O:-KJBdTeADWxEEp5f-b8P:-1819002665) ([raw file](https://github.com/servo/servo/blob/1f01c8842a2f1ee08af88f91f38868c81838df4c/components/script/dom/htmlheadelement.rs#L50)):*
> ```Rust
>                            .filter(|elem| elem.get_string_attribute(&atom!("name")) == "referrer")
>                            .filter(|elem| elem.get_attribute(&ns!(), &atom!("content")).is_some());
>         
> ```

Nit: unneeded blanks.

---

*[components/script/dom/htmlmetaelement.rs, line 100 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11468#-KIntrE1zsUlorwITyoh:-KJBdP0ORJ2Kx0amDKjJ:307738639) ([raw file](https://github.com/servo/servo/blob/eaf44859bb6d311154e2cf824f8f28d68b3227da/components/script/dom/htmlmetaelement.rs#L100)):*
<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> Ok see latest commit - moved logic into HTMLHeadElement with a call from HTMLMetaElement. Still need to add calls within attribute_mutated and unbind_from_tree, but that should be quick if this piece looks right.
</details>
This is mostly what I had in mind. Great work!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468#-:-KJBd_pfLta5802wivh_:882755527)*

**Comment by rebstar6** [comment]
@nox I hear it! Latest has the VirtualMethod changes and everything!

**Comment by nox** [comment]
Final remarks, I think.

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> @nox I hear it! Latest has the VirtualMethod changes and everything!
</details>


---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/htmlheadelement.rs, line 48 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9JLRnWIjow9u6KHq:-KJD9JLRnWIjow9u6KHr:1094378185) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlheadelement.rs#L48)):*
> ```Rust
> 
>         if let Some(head) = doc.GetHead() {
>             if node.IsSameNode(Some(head.upcast::<Node>())) {
> ```

Can you just do an early return instead? Also you can just use `==`.

```
if doc.GetHead().r() != Some(head.upcast::<Node>()) {
    return;
}
```

---

*[components/script/dom/htmlmetaelement.rs, line 108 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9r1wj3L4sazSYR9g:-KJD9r1wj3L4sazSYR9h:-598633423) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L108)):*
> ```Rust
> 
>     /// https://html.spec.whatwg.org/multipage/#meta-referrer
>     fn apply_referrer(&self) {
> ```

No need to check anything in that function, so you can just call `head.set_document_referrer()` from `process_referrer_attribute` directly.

---

*[components/script/dom/htmlmetaelement.rs, line 156 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJDA4Vk6iPKlzPTOKeG:-KJDA4Vk6iPKlzPTOKeH:-1859050331) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L156)):*
> ```Rust
>         if let Some(s) = self.super_type() {
>             s.attribute_mutated(attr, mutation);
>         }
> ```

Nit: just do:

```rust
self.super_type().unwrap().attribute_mutated(attr, mutation);
```

---

*[components/script/dom/htmlmetaelement.rs, line 158 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9z1Feu9pflZQ9z9m:-KJD9z1Feu9pflZQ9z9n:213072485) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L158)):*
> ```Rust
>         }
> 
>         //TODO any conditions here?
> ```

No need since the rest will check everything correctly.

---

*[components/script/dom/htmlmetaelement.rs, line 170 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJDA1DxGH3ZlYoabbCL:-KJDA1DyAqLqpy1OL5bp:1662361328) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L170)):*
> ```Rust
>             self.process_referrer_attribute();
>         }
>     }
> ```

You need a similar method for `bind_to_tree`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468#-:-KJDAKHDttp5xkoBjVC1:-37538805)*

**Comment by rebstar6** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/htmlheadelement.rs, line 48 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9JLRnWIjow9u6KHq:-KJGgmvt_VaYpfaJ9rQb:-1626060343) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlheadelement.rs#L48)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Can you just do an early return instead? Also you can just use `==`.
> 
> ```
> if doc.GetHead().r() != Some(head.upcast::<Node>()) {
>     return;
> }
> ```
</details>
gethead returns an option, so this is a little uglier. See latest.

---

*[components/script/dom/htmlmetaelement.rs, line 108 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9r1wj3L4sazSYR9g:-KJGgJubj-yTSFHEd-yJ:1594598022) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L108)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> No need to check anything in that function, so you can just call `head.set_document_referrer()` from `process_referrer_attribute` directly.
</details>
I wanted to still have the check on if this meta element is even a referrer type within a head element - that's why I have the intermediate process_referrer_attribute method

---

*[components/script/dom/htmlmetaelement.rs, line 156 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJDA4Vk6iPKlzPTOKeG:-KJGgiYNElU8ADBtMK64:1124350540) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L156)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Nit: just do:
> 
> ```rust
> self.super_type().unwrap().attribute_mutated(attr, mutation);
> ```
</details>
i copy/pasted from VirtualMethods :) - still change it?

---

*[components/script/dom/htmlmetaelement.rs, line 170 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJDA1DxGH3ZlYoabbCL:-KJGgUbS4QCuD8_2HeXk:-2021177650) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L170)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> You need a similar method for `bind_to_tree`.
</details>
There is one - bind_to_tree calls process_attributes, which in turn calls head.set_document_referrer if relevant 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468)*

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

Just change the early return test and remove `apply_referrer` and we are done!

@bors-servo try

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/htmlheadelement.rs, line 48 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9JLRnWIjow9u6KHq:-KJH5d806Bpy8CDyxd-6:2093360806) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlheadelement.rs#L48)):*
<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> gethead returns an option, so this is a little uglier. See latest.
</details>
I know it returns an `Option`, but we have `.r()` on `Option`. :)

---

*[components/script/dom/htmlmetaelement.rs, line 108 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9r1wj3L4sazSYR9g:-KJH5rtlQBa_YTdcECUW:532026907) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L108)):*
<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> I wanted to still have the check on if this meta element is even a referrer type within a head element - that's why I have the intermediate process_referrer_attribute method
</details>
It's more confusing to have the tests in two places.

---

*[components/script/dom/htmlmetaelement.rs, line 156 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJDA4Vk6iPKlzPTOKeG:-KJH5ucItvQRXuaztI6m:160383661) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L156)):*
<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> i copy/pasted from VirtualMethods :) - still change it?
</details>
OK.

---

*[components/script/dom/htmlmetaelement.rs, line 158 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9z1Feu9pflZQ9z9m:-KJH6-ECOAvh1Ms0kYmz:1659859850) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L158)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> No need since the rest will check everything correctly.
</details>
You didn't remove that comment.

---

*[components/script/dom/htmlmetaelement.rs, line 170 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJDA1DxGH3ZlYoabbCL:-KJH61ni3SYjT-fREF4Y:-31541101) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L170)):*
<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> There is one - bind_to_tree calls process_attributes, which in turn calls head.set_document_referrer if relevant 
</details>
Neat. Didn't notice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468#-:-KJH6514KzyTJwpKGIaG:-1955482633)*

**Comment by nox** [comment]
I'm pretty sure this is intermittent.

**Comment by jdm** [comment]
Filed #11561.

**Comment by rebstar6** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlheadelement.rs, line 48 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9JLRnWIjow9u6KHq:-KJHymsJYAWdNyLbyJBa:1983761672) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlheadelement.rs#L48)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> I know it returns an `Option`, but we have `.r()` on `Option`. :)
</details>
it's still an option though...i'll compare it to Some(self)?

---

*[components/script/dom/htmlmetaelement.rs, line 108 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9r1wj3L4sazSYR9g:-KJHxxMgQqATrgYke4gt:-389684855) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L108)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> It's more confusing to have the tests in two places.
</details>
Which 2 places? These checks should still be there, or set_document_referrer is going to get called for every meta element of any type...which seems super inefficient (?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468)*

**Comment by nox** [comment]
Remove the `TODO` comment that you forgot and r=me. Great work!

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/htmlheadelement.rs, line 48 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9JLRnWIjow9u6KHq:-KJIPHHbOdBt4upIw927:-1953337440) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlheadelement.rs#L48)):*
<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> it's still an option though...i'll compare it to Some(self)?
</details>
Yes exactly.

---

*[components/script/dom/htmlmetaelement.rs, line 108 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11468#-KJD9r1wj3L4sazSYR9g:-KJIOQcidbvsAqzxMPdZ:-2118253537) ([raw file](https://github.com/servo/servo/blob/e47f8a8cf89883ab0287476dac4eafac0c14f13e/components/script/dom/htmlmetaelement.rs#L108)):*
<details><summary><i>Previously, rebstar6 (Rebecca) wrote…</i></summary>
> Which 2 places? These checks should still be there, or set_document_referrer is going to get called for every meta element of any type...which seems super inefficient (?)
</details>
Never mind, I was talking about the two `if let` to get the parent `head` element, but we can't even avoid them given we have to call the `set_document_referrer` method on it. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11468#-:-KJIPKv0YIHxvZsthzu9:-1549432005)*

**Comment by rebstar6** [comment]
Should be set. I believe my 'todos' are in order as well. Woot woot!

**Pull request merged**
