### PR TITLE
armv7 update

### PR DESCRIPTION
**Pull request by fabricedesre**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11041)

### CODE REVIEW

**Comment by fabricedesre** [comment]
I can't change labels, but it's not ready for review

**Comment by fabricedesre** [comment]
@jdm can you remove the `S-needs-rebase` label. This should be all good finally ;)

**Comment by larsbergstrom** [comment]
Reviewed 3 of 3 files at r1.
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11041)*

**Comment by jdm** [comment]
@bors-servo: retry
* #11059

**Pull request merged**
