### PR TITLE
Update immeta dependency to resolve ImageCacheThread panic

### LINKED ISSUE #9501: crash while loading cnn.com (unimplemented VP8X_CHUNK)
```
thread 'ImageCacheThread' panicked at 'not yet implemented', servo/.cargo/registry/src/github.com-0a35038f75765ae4/immeta-0.2.4/src/formats/webp.rs:67
stack backtrace:
   1:        0x10ae35158 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x10ae372b5 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x10ae36eb6 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10ae225c6 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10a416a04 - sys_common::unwind::begin_unwind::h5964474997714817546
   6:        0x10a416505 - generic::load_from_buf::hc54a410bf7bd827f6ta
   7:        0x10a357a2e - image_cache_thread::ImageCache::run::hf7259cb8eaea33b8cfc
   8:        0x10a39086e - sys_common::unwind::try::try_fn::h13365323490457168969
   9:        0x10ae346fb - __rust_try
  10:        0x10ae31693 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  11:        0x10a39199a - boxed::F.FnBox<A>::call_box::h5439146165892437764
  12:        0x10ae3653d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  13:     0x7fff9242c99c - _pthread_body
  14:     0x7fff9242c919 - _pthread_start
```

`unimplemented!()`: https://github.com/netvl/immeta/blob/f252cf4a154e0e110f96bf3cf7392e6b23366e21/src/formats/webp.rs#L67

### PR DESCRIPTION
**Pull request by timvandermeij**
Fixes #9501.

Before this patch, a website such as http://www.universiteitleiden.nl would consistently crash Servo. After this patch, the website loads just fine.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9542)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by KiChjang** [comment]
@bors-servo retry
* #8120

**Comment by jdm** [comment]
@bors-servo: retry
* #7846

**Comment by KiChjang** [comment]
@bors-servo retry
* #8191

**Comment by jdm** [comment]
@bors-servo: retry
* #8120 #7846

**Comment by jdm** [comment]
@bors-servo: retry
* #9092

**Comment by jdm** [comment]
@bors-servo: retry
* #8120

**Pull request merged**
