### PR TITLE
add FFI functions for Gecko @counter-style value parsing

### PR DESCRIPTION
**Pull request by heycam**
Servo-side part of https://bugzilla.mozilla.org/show_bug.cgi?id=1420117, reviewed there by Xidorn.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19441)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* I don't understand what went wrong, but it appears to be isolated to that single job?

**Comment by heycam** [comment]
@bors-retry

* Same timeouts. My patches here shouldn't affect Servo builds at all.

**Comment by heycam** [comment]
@bors-servo retry

* Same timeouts. My patches here shouldn't affect Servo builds at all.

**Comment by jdm** [comment]
I've pressed the "graceful shutdown" button on the linux3 build machine; hopefully we can cause a different machine to be selected when retrying next time.

**Comment by heycam** [comment]
@bors-servo retry

* One more try for those timeouts. Otherwise I'm not sure what to do...

**Comment by emilio** [comment]
@bors-servo retry

 * Srsly

**Pull request merged**
