### PR TITLE
Network: Preserve HEAD on 303 redirect

### LINKED ISSUE #21449: Preserve HEAD on 303 redirect
https://github.com/whatwg/fetch/pull/796

### PR DESCRIPTION
**Pull request by tigercosmos**
fixed #21449. This is an update for spec.

This PR just update one step for redirect fetch according to spec. No tests result change, since the whole process is still in development(So many todo).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21454)

### CODE REVIEW

**Comment by KiChjang** [comment]
Is there a reason why this is a WIP?

**Comment by KiChjang** [comment]
Nevermind, looks good to me, thanks!

@bors-servo r+

**Comment by tigercosmos** [comment]
I want to check if any test result change. But there is no, due to so many TODO in the function.

**Comment by KiChjang** [comment]
@bors-servo retry
* servo/intermittent-failure-tracker#5

**Pull request merged**
