### PR TITLE
Ensure that text nodes don't inherit opacity.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9503)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #9504

**Comment by KiChjang** [comment]
@bors-servo retry
* #7791

**Comment by jdm** [comment]
@bors-servo: retry
* #9303

**Comment by jdm** [comment]
@bors-servo: retry
* #9106

**Comment by KiChjang** [comment]
@bors-servo retry
* #8120

**Comment by KiChjang** [comment]
@bors-servo retry
* #9106

**Comment by KiChjang** [comment]
@bors-servo retry
* #9120

**Pull request merged**
