### PR TITLE
mach: Fix cargo-geckolib check / cargo-geckolib build after #19476.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19539)

### CODE REVIEW

**Comment by SimonSapin** [comment]
This doesn’t work in the general case of arbitrary cargo subcommands, since not all of them take `-p`.

Maybe something like this? https://github.com/servo/servo/pull/19395/files#diff-309c064985884bee5b85e07757ca0103R44

**Comment by emilio** [comment]
Sounds good, just did that

**Pull request merged**
