### PR TITLE
Add a transparent hit-testing rectangle for scrollable block content.

### LINKED ISSUE #22073: Trackpad scrolling has dead zones
When I run http://asvd.github.io/dragscroll/ in Servo, I can use the trackpad to scroll the text element smoothly. However, the scrolling stops abruptly partway down, and I need to move the mouse somewhere else to resume scrolling.

### PR DESCRIPTION
**Pull request by jdm**
This implements the strategy described at https://github.com/servo/webrender/issues/3261#issuecomment-435106998 and which Gecko uses as well. Adding a transparent rectangle below the content and above the background ensures that hit testing correctly associates the background area with the right scrolling node.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22073
- [x] These changes do not require tests because the affected codepath requires user input, and we don't support webdriver tests yet.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22156)

### CODE REVIEW

**Comment by jdm** [comment]
This allows http://asvd.github.io/dragscroll/ to be scrolled with the trackpad regardless of where the mouse is placed.

**Comment by pcwalton** [comment]
r+

**Pull request merged**
