### PR TITLE
[WIP] Upgrade to SpiderMonkey 97

### PR DESCRIPTION
**Pull request by CYBAI**
This should be merged after https://github.com/servo/mozjs/pull/295 and https://github.com/servo/rust-mozjs/pull/556 merged.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)
- [x] There are tests for these changes (We need to confirm this smup will break or fix which tests)

### CODE REVIEW

**Comment by CYBAI** [comment]
Looks like there are still something wrong for PropertyDescriptor. Let me find out where I should fix it.

```
  ▶ ERROR [expected OK] b'/_webgl/conformance/ogles/GL/functions/functions_121_to_126.html'
  │   → setting getter-only property "display"
  │ 
  │ addShaderSource@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:2504:3
  │ addShaderSources@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:2550:18
  │ addShader@http://web-platform.test:8000/_webgl/conformance/ogles/ogles-utils.js:587:15
  │ loadShader/<@http://web-platform.test:8000/_webgl/conformance/ogles/ogles-utils.js:568:16
  └ loadTextFileAsync/request.onreadystatechange@http://web-platform.test:8000/_webgl/js/webgl-test-utils.js:1744:17
```

**Comment by CYBAI** [comment]
With running this test, I can see crashes from the proxy hooks

```
$ ./mach test-wpt tests/wpt/web-platform-tests/dom/ranges/Range-detach.html
```

we currently got following errors

<details>

```
pid:70703 Stack trace for thread "Script(1,1)"
 0:26.78 pid:70703    0: backtrace::backtrace::libunwind::trace
 0:26.78 pid:70703              at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/backtrace/libunwind.rs:90:5
 0:26.78 pid:70703       backtrace::backtrace::trace_unsynchronized
 0:26.78 pid:70703              at /Users/cybai/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/backtrace/mod.rs:66:5
 0:26.79 pid:70703    1: <servo::backtrace::Print as core::fmt::Debug>::fmt
 0:26.79 pid:70703              at /Users/cybai/codespace/servo/servo/ports/winit/backtrace.rs:53:13
 0:26.84 pid:70703    2: core::fmt::write
 0:26.84 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/fmt/mod.rs:1190:17
 0:26.97 pid:70703    3: std::io::Write::write_fmt
 0:26.97 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/io/mod.rs:1655:15
 0:26.97 pid:70703    4: servo::backtrace::print
 0:26.97 pid:70703              at /Users/cybai/codespace/servo/servo/ports/winit/backtrace.rs:17:5
 0:26.97 pid:70703    5: servo::crash_handler::install::handler
 0:26.97 pid:70703              at /Users/cybai/codespace/servo/servo/ports/winit/crash_handler.rs:25:21
 0:26.98 pid:70703    6: __sigtramp
 0:27.20 pid:70703    7: _ZNSt3__1L17__cxx_atomic_loadImEET_PKNS_22__cxx_atomic_base_implIS1_EENS_12memory_orderE
 0:27.20 pid:70703              at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/atomic:1003:12
 0:27.21 pid:70703       _ZNKSt3__113__atomic_baseImLb0EE4loadENS_12memory_orderE
 0:27.21 pid:70703              at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/atomic:1607:17
 0:27.21 pid:70703       _ZN7mozilla6detail18IntrinsicMemoryOpsImLNS_14MemoryOrderingE0EE4loadERKNSt3__16atomicImEE
 0:27.21 pid:70703              at /Users/cybai/codespace/servo/servo/target/debug/build/mozjs_sys-21fc0fd092429935/out/build/dist/include/mozilla/Atomics.h:195:17
 0:27.21 pid:70703       _ZNK7mozilla6detail16AtomicBaseIncDecImLNS_14MemoryOrderingE0EEcvmEv
 0:27.21 pid:70703              at /Users/cybai/codespace/servo/servo/target/debug/build/mozjs_sys-21fc0fd092429935/out/build/dist/include/mozilla/Atomics.h:340:31
 0:27.21 pid:70703       _ZNK2js2gc24CellWithTenuredGCPointerINS0_4CellENS_5ShapeEE9headerPtrEv
 0:27.21 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/gc/Cell.h:786:46
 0:27.21 pid:70703       _ZNK8JSObject5shapeEv
 0:27.21 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/JSObject.h:99:37
 0:27.21 pid:70703       _ZNK8JSObject8getClassEv
 0:27.21 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/JSObject.h:118:44
 0:27.21 pid:70703       _ZNK8JSObject17getOpsHasPropertyEv
 0:27.21 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/JSObject.h:128:12
 0:27.21 pid:70703       _ZN2js11HasPropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_11PropertyKeyEEEPb
 0:27.21 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/ObjectOperations-inl.h:88:31
 0:27.21 pid:70703       _Z18JS_HasPropertyByIdP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_11PropertyKeyEEEPb
 0:27.21 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/PropertyAndElement.cpp:534:10
 0:27.29 pid:70703    8: script::dom::windowproxy::has
 0:27.29 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/windowproxy.rs:977:9
 0:27.34 pid:70703    9: _ZNK19WrapperProxyHandler3hasEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_11PropertyKeyEEEPb
 0:27.34 pid:70703              at /Users/cybai/.cargo/git/checkouts/rust-mozjs-c056748d355cf1fd/0aabac9/src/jsglue.cpp:395:5
 0:27.57 pid:70703   10: _ZN2js5Proxy3hasEP9JSContextN2JS6HandleIP8JSObjectEENS4_INS3_11PropertyKeyEEEPb
 0:27.57 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/proxy/Proxy.cpp:384:19
 0:27.94 pid:70703   11: _ZN2js11HasPropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_11PropertyKeyEEEPb
 0:27.94 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/ObjectOperations-inl.h:89:12
 0:27.94 pid:70703       _ZL9InterpretP9JSContextRN2js8RunStateE
 0:27.94 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/Interpreter.cpp:2415:14
 0:27.94 pid:70703   12: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
 0:27.94 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/Interpreter.cpp:394:13
 0:27.94 pid:70703   13: _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEENS3_IP8JSObjectEENS3_INS2_5ValueEEENS_16AbstractFramePtrENS2_13MutableHandleISA_EE
 0:27.94 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/Interpreter.cpp:767:13
 0:28.30 pid:70703   14: _Z16JS_ExecuteScriptP9JSContextN2JS6HandleIP8JSScriptEENS1_13MutableHandleINS1_5ValueEEE
 0:28.30 pid:70703              at /Users/cybai/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/js/src/vm/CompilationAndEvaluation.cpp:532:10
 0:28.41 pid:70703   15: mozjs::rust::wrappers::JS_ExecuteScript
 0:28.41 pid:70703              at /Users/cybai/.cargo/git/checkouts/rust-mozjs-c056748d355cf1fd/0aabac9/src/rust.rs:1477:51
 0:28.51 pid:70703   16: script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result::{{closure}}
 0:28.51 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/globalscope.rs:2657:34
 0:28.63 pid:70703   17: profile_traits::time::profile
 0:28.63 pid:70703              at /Users/cybai/codespace/servo/servo/components/profile_traits/time.rs:141:15
 0:28.72 pid:70703   18: script::dom::globalscope::GlobalScope::evaluate_script_on_global_with_result
 0:28.72 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/globalscope.rs:2597:9
 0:28.80 pid:70703   19: script::dom::htmlscriptelement::HTMLScriptElement::run_a_classic_script
 0:28.80 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/htmlscriptelement.rs:1073:9
 0:28.80 pid:70703   20: script::dom::htmlscriptelement::HTMLScriptElement::execute
 0:28.80 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/htmlscriptelement.rs:1035:17
 0:28.89 pid:70703   21: script::dom::servoparser::ServoParser::resume_with_pending_parsing_blocking_script
 0:28.89 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/servoparser/mod.rs:319:9
 0:29.00 pid:70703   22: script::dom::document::Document::process_pending_parsing_blocking_script
 0:29.00 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/document.rs:2439:13
 0:29.00 pid:70703   23: script::dom::document::Document::pending_parsing_blocking_script_loaded
 0:29.00 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/document.rs:2425:9
 0:29.00 pid:70703   24: script::dom::htmlscriptelement::finish_fetching_a_classic_script
 0:29.00 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/htmlscriptelement.rs:334:13
 0:29.00 pid:70703   25: script::dom::htmlscriptelement::off_thread_compilation_callback::{{closure}}
 0:29.00 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/dom/htmlscriptelement.rs:153:13
 0:29.00 pid:70703   26: <script::dom::htmlscriptelement::off_thread_compilation_callback::off_thread_compile_continue<F> as script::task::TaskOnce>::run_once
 0:29.00 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/task.rs:24:17
 0:29.09 pid:70703   27: <script::task::CancellableTask<T> as script::task::TaskOnce>::run_once
 0:29.09 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/task.rs:114:13
 0:29.09 pid:70703   28: <T as script::task::TaskBox>::run_box
 0:29.10 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/task.rs:57:9
 0:29.20 pid:70703   29: script::script_thread::ScriptThread::handle_msg_from_script
 0:29.21 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/script_thread.rs:2098:82
 0:29.34 pid:70703   30: script::script_thread::ScriptThread::handle_msgs::{{closure}}
 0:29.34 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/script_thread.rs:1647:46
 0:29.34 pid:70703   31: script::script_thread::ScriptThread::profile_event
 0:29.34 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/script_thread.rs:1890:13
 0:29.35 pid:70703   32: script::script_thread::ScriptThread::handle_msgs
 0:29.35 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/script_thread.rs:1640:26
 0:29.35 pid:70703   33: script::script_thread::ScriptThread::start
 0:29.35 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/script_thread.rs:1444:15
 0:29.35 pid:70703   34: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
 0:29.35 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/script_thread.rs:832:25
 0:29.52 pid:70703   35: profile_traits::mem::ProfilerChan::run_with_memory_reporting
 0:29.52 pid:70703              at /Users/cybai/codespace/servo/servo/components/profile_traits/mem.rs:88:9
 0:29.52 pid:70703   36: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
 0:29.52 pid:70703              at /Users/cybai/codespace/servo/servo/components/script/script_thread.rs:830:17
 0:29.63 pid:70703   37: std::sys_common::backtrace::__rust_begin_short_backtrace
 0:29.63 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/sys_common/backtrace.rs:122:18
 0:29.75 pid:70703   38: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
 0:29.75 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/thread/mod.rs:498:17
 0:29.86 pid:70703   39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
 0:29.86 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/panic/unwind_safe.rs:271:9
 0:29.96 pid:70703   40: std::panicking::try::do_call
 0:29.96 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:492:40
 0:29.96 pid:70703   41: ___rust_try
 0:29.96 pid:70703   42: std::panicking::try
 0:29.96 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:456:19
 0:30.06 pid:70703   43: std::panic::catch_unwind
 0:30.06 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panic.rs:137:14
 0:30.06 pid:70703   44: std::thread::Builder::spawn_unchecked_::{{closure}}
 0:30.06 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/thread/mod.rs:497:30
 0:31.05 pid:70703   45: core::ops::function::FnOnce::call_once{{vtable.shim}}
 0:31.05 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/ops/function.rs:227:5
 0:31.19 pid:70703   46: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
 0:31.19 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/alloc/src/boxed.rs:1854:9
 0:31.19 pid:70703       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
 0:31.19 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/alloc/src/boxed.rs:1854:9
 0:31.19 pid:70703       std::sys::unix::thread::Thread::new::thread_start
 0:31.19 pid:70703              at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/sys/unix/thread.rs:108:17
 0:31.19 pid:70703   47: __pthread_start
```

</details>

I'm looking into how Gecko implements those hooks for windowproxy.

https://searchfox.org/mozilla-central/rev/a019f4f233dc43af0ade38be0914010448c4ce03/js/src/proxy/Wrapper.cpp#49

**Comment by sagudev** [comment]
UWP failing with:
```
  In file included from Unified_cpp_mfbt0.cpp:65:
  C:/Users/runneradmin/.cargo/git/checkouts/mozjs-59f3e6c6d1dae588/0ce5c85/mozjs/mfbt/RandomNum.cpp(99,12): error: use of undeclared identifier 'RtlGenRandom'
    return !!RtlGenRandom(aBuffer, aLength);
             ^
  1 error generated.
```

**Comment by sagudev** [comment]
Here is interesting discussion: https://github.com/rust-random/getrandom/issues/65.
I recommend adding patch to mozjs that would used `BCryptGenRandom` on UWP.

**Comment by CYBAI** [comment]
@jdm @emilio (cc @sagudev) is it correct for me to see `ForwardingProxyHandler` in Gecko as our `windowproxy.rs` in Servo? I'm wondering if it's correct to read through the handler functions (e.g. [`ForwardingProxyHandler::getOwnPropertyDescriptor`](https://searchfox.org/mozilla-central/rev/4365e6ab34ca829c930b60252ff19a5f42856da0/js/src/proxy/Wrapper.cpp#49-55)) and see if I miss something on Servo side.

Currently, if I run following test on a787e46 commit:

```
$ ./mach test-wpt tests/wpt/web-platform-tests/html/semantics/scripting-1/the-script-element/module/integrity.html
```

I would get a failure of "inlineRan" is read-only.

image

It looks like I miss something for `PropertyDescriptor` to make it writable (or I should omit a `JSPROP_READONLY` somewhere?) 🤔 

(I'd like to note that I haven't changed `JSPROP_*` attrs to the new one, `PropertyAttributes`, because I'd like to keep this smup as small as possible and maybe we can move them to the new one when this smup is done.)

Could you please give me some direction or suggestion 🙏? Thanks!

**Comment by sagudev** [comment]
@CYBAI any progress?

**Comment by CYBAI** [comment]
@sagudev I didn't have too much time to dive into it yet :( but I've noticed some code was wrongly patched so I've corrected them and pushed again.

**Comment by CYBAI** [comment]
I was wondering if it can be related to `fill_property_descriptor` in `proxyhandler.rs`

https://github.com/servo/servo/blob/147a2b65de613beefc9bcd325f6ee69e2656943c/components/script/dom/bindings/proxyhandler.rs#L207-L209

but the test case, `tests/wpt/web-platform-tests/html/semantics/scripting-1/the-script-element/module/integrity.html`, still failed with readonly `window.inlineRun`; even I pass `true` directly to `writable` in above section.

So, I'll look into if there's any other places I should mutate the `writable` flag manually 🤔

**Comment by sagudev** [comment]
I did full WPT testing on previous patches yesterday to test gitpod and according to logs other properties are misused too. Here are logs: https://github.com/sagudev/servo/releases/tag/smup97logs

**Comment by CYBAI** [comment]
Let's close this PR as we're going to bump to SM 107 at #29079!

**Pull request closed without merging**
