### PR TITLE
task -> thread

### PR DESCRIPTION
**Pull request by ajnirp**
for #8512

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9201)

### CODE REVIEW

**Comment by KiChjang** [comment]
Fails tidy:
```
./components/script/dom/dedicatedworkerglobalscope.rs:223: Line is longer than 120 characters
./components/script/dom/storage.rs:71: Line is longer than 120 characters
```

Also fails to build:
```
/home/travis/build/servo/servo/tests/unit/net/http_loader.rs:24:5: 24:45 error: unresolved import `net::resource_task::CancellationListener`. Could not find `resource_task` in `net` [E0432]
/home/travis/build/servo/servo/tests/unit/net/http_loader.rs:24 use net::resource_task::CancellationListener;
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/servo/servo/tests/unit/net/http_loader.rs:24:5: 24:45 help: run `rustc --explain E0432` to see a detailed explanation
/home/travis/build/servo/servo/tests/unit/net/http_loader.rs:1200:9: 1200:48 error: unresolved import `net::resource_task::CancellableResource`. Could not find `resource_task` in `net` [E0432]
/home/travis/build/servo/servo/tests/unit/net/http_loader.rs:1200     use net::resource_task::CancellableResource;
                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/servo/servo/tests/unit/net/http_loader.rs:1200:9: 1200:48 help: run `rustc --explain E0432` to see a detailed explanation
```

**Comment by jdm** [comment]
@bors-servo: delegate+
This is ready to merge once it builds and passes test-tidy.

**Comment by wenderen** [comment]
r+

**Comment by nox** [comment]
```
clang: error: no such file or directory: 'src/thread_info.c'
clang: error: no input files
thread '<main>' panicked at 'explicit panic', /Users/servo/.cargo/registry/src/github.com-0a35038f75765ae4/gcc-0.3.17/src/lib.rs:768
stack backtrace:
   1:        0x105995da8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
   2:        0x10599a27f - panicking::log_panic::_<closure>::closure.40842
   3:        0x105999d22 - panicking::log_panic::h7a04edac7e1f2797HEx
   4:        0x1059851a6 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
   5:        0x10596cd57 - sys_common::unwind::begin_unwind::begin_unwind::h13679756390154096214
   6:        0x10597ca2b - fail::h347fdab72b7e387duZa
   7:        0x105977360 - run::hf216d327ca11976fQVa
   8:        0x10596dfee - _<impl>::compile_object::h4e58a958d1ed6132yna
   9:        0x105969ab2 - _<impl>::compile::h79cf50932d333253Gja
  10:        0x10596360d - main::hc3af6fac7c1932e6faa
  11:        0x105999aa2 - sys_common::unwind::try::try_fn::h9781900235654175042
  12:        0x1059951e8 - __rust_try
  13:        0x105999949 - rt::lang_start::h7f8cb47bb0ba3293PBx
  14:        0x1059664b9 - main
```

**Comment by nox** [comment]
```
browser.rs:13:5: 13:28 error: unresolved import `util::task::spawn_named`. Could not find `task` in `util` [E0432]
browser.rs:13 use util::task::spawn_named;
                  ^~~~~~~~~~~~~~~~~~~~~~~
browser.rs:13:5: 13:28 help: run `rustc --explain E0432` to see a detailed explanation
task.rs:5:5: 5:36 error: unresolved import `interfaces::cef_thread_runner_t`. There is no `cef_thread_runner_t` in `interfaces` [E0432]
task.rs:5 use interfaces::cef_thread_runner_t;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
task.rs:5:5: 5:36 help: run `rustc --explain E0432` to see a detailed explanation
window.rs:21:36: 21:40 error: unresolved import `compositing::compositor_task`. There is no `compositor_task` in `compositing` [E0432]
window.rs:21 use compositing::compositor_task::{self, CompositorProxy, CompositorReceiver};
                                                ^~~~
window.rs:21:36: 21:40 help: run `rustc --explain E0432` to see a detailed explanation
window.rs:21:42: 21:57 error: unresolved import `compositing::compositor_task::CompositorProxy`. Could not find `compositor_task` in `compositing` [E0432]
window.rs:21 use compositing::compositor_task::{self, CompositorProxy, CompositorReceiver};
                                                      ^~~~~~~~~~~~~~~
window.rs:21:42: 21:57 help: run `rustc --explain E0432` to see a detailed explanation
window.rs:21:59: 21:77 error: unresolved import `compositing::compositor_task::CompositorReceiver`. Could not find `compositor_task` in `compositing` [E0432]
window.rs:21 use compositing::compositor_task::{self, CompositorProxy, CompositorReceiver};
                                                                       ^~~~~~~~~~~~~~~~~~
window.rs:21:59: 21:77 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to 5 previous errors
```

**Comment by wenderen** [comment]
Is there a way I can test the Windows and OS X builds on my Linux machine?

**Comment by wenderen** [comment]
@bors-servo r=jdm

once more unto the breach

**Comment by wenderen** [comment]
phew

**Pull request merged**
