### PR TITLE
Add HTMLFormControlsCollection interface

### PR DESCRIPTION
**Pull request by frewsxcv**
https://html.spec.whatwg.org/multipage/#htmlformcontrolscollection

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7845)

### CODE REVIEW

**Comment by Manishearth** [comment]
LGTM overall. Minor nits.


---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlcollection.rs, line 25 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7845#-K-lFNsTBd_jila3msRu)** ([raw file](https://github.com/servo/servo/blob/25016f90205e3621c97f9cd050c9d071218a95b3/components/script/dom/htmlcollection.rs#L25)):</sup>
Would prefer if these were private with a constructor and `#[privatize]`. Too easy to accidentally extract a `JS<T>` otherwise


---

<sup>**[components/script/dom/htmlformcontrolscollection.rs, line 24 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7845#-K-lI9bojwJ0d1-5IY4S)** ([raw file](https://github.com/servo/servo/blob/25016f90205e3621c97f9cd050c9d071218a95b3/components/script/dom/htmlformcontrolscollection.rs#L24)):</sup>
Spec link: https://html.spec.whatwg.org/multipage/forms.html#category-listed


---

<sup>**[components/script/dom/htmlformcontrolscollection.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7845#-K-lJCrBiR-ih0V59LLV)** ([raw file](https://github.com/servo/servo/blob/25016f90205e3621c97f9cd050c9d071218a95b3/components/script/dom/htmlformcontrolscollection.rs#L57)):</sup>
What's this for?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7845)

**Comment by Manishearth** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7845)

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlformcontrolscollection.rs, line 59 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7845#-K-lKCof2UwWn9QDSW-O)** ([raw file](https://github.com/servo/servo/blob/25016f90205e3621c97f9cd050c9d071218a95b3/components/script/dom/htmlformcontrolscollection.rs#L59)):</sup>
@nox: Any reason why this needs to be explicitly implemented (given that in can inherit)?

We haven't uncommented the explicit overriding getter in the webidl. (I think we should file a followup for that though)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7845)

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlformcontrolscollection.rs, line 59 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7845#-K-lKCof2UwWn9QDSW-O)** ([raw file](https://github.com/servo/servo/blob/25016f90205e3621c97f9cd050c9d071218a95b3/components/script/dom/htmlformcontrolscollection.rs#L59)):</sup>
You mean this? :) https://github.com/servo/servo/issues/5875


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7845)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/htmlformcontrolscollection.rs, line 24 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7845#-K-lI9bojwJ0d1-5IY4S)** ([raw file](https://github.com/servo/servo/blob/25016f90205e3621c97f9cd050c9d071218a95b3/components/script/dom/htmlformcontrolscollection.rs#L24)):</sup>
I have it linked a few lines abvoe


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7845)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/htmlformcontrolscollection.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7845#-K-lJCrBiR-ih0V59LLV)** ([raw file](https://github.com/servo/servo/blob/25016f90205e3621c97f9cd050c9d071218a95b3/components/script/dom/htmlformcontrolscollection.rs#L57)):</sup>
The tidy checker makes sure all methods in  `*Methods` traits have spec links. This comment allows that behavior to be overridden. I didn't link to the spec for these methods here because these are all inherited by the parent interface


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7845)

**Comment by Manishearth** [comment]
You need to update /_mozilla/mozilla/interfaces.html

**Comment by frewsxcv** [comment]
screen shot 2015-10-04 at 12 15 38 pm

/cc @jdm @Ms2ger

**Comment by Manishearth** [comment]
That's fine, it's a window-exposed DOM type (try it in Firefox). Make sure you add it to the DOM interface array, not the ECMA array.

**Comment by frewsxcv** [comment]
Yep, it's added

**Comment by Ms2ger** [comment]
There's ongoing discussion about this: https://github.com/whatwg/html/issues/200

**Comment by frewsxcv** [comment]
#8566

**Pull request closed without merging**
