### PR TITLE
Avoid allocations when joining strings

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7776)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7776)

**Comment by frewsxcv** [comment]
@bors-servo retry

* https://github.com/servo/servo/issues/7787

**Comment by Ms2ger** [comment]
This changes behaviour in the face of empty strings in the iterator, I think. Did you confirm that can't happen?

**Comment by frewsxcv** [comment]
How does the behavior change with empty strings?

**Comment by Ms2ger** [comment]
Joining `["", "x"]` would have a leading separator before, I think, and won't now.

**Comment by frewsxcv** [comment]
http://is.gd/UiOvie

**Comment by Ms2ger** [comment]
http://is.gd/ZBCjKg

**Comment by frewsxcv** [comment]
Ah, that's what you meant. I'm not sure about cssstyledeclaration.rs, but with the other two DOM instances, I think we're just going to eventually strip away the whitespace (they're being joined together by `" "`) so it shouldn't affect the generated value AFAIK

**Comment by mbrubeck** [comment]
In cssstyledeclaration, this is run on the result of `longhands_from_shorthand` which returns a list of static strings that are never empty.

**Comment by frewsxcv** [comment]
I'm planning to open a PR later that will make `str_join` functionally consistent with the builtin `join` method

**Comment by frewsxcv** [comment]
PR opened https://github.com/servo/servo/pull/7806

**Pull request merged**
