### PR TITLE
Fix prototypes of interface objects (fixes #2665)

### LINKED ISSUE #2665: Hook up interface object proto chains as if they were ES6 classes
https://bugzilla.mozilla.org/show_bug.cgi?id=860841
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23133

### PR DESCRIPTION
**Pull request by nox**
Callback interface objects' (i.e. NodeFilter's) prototype is now Object instead of
Function and non-callback interface objects' their proper ancestor, starting with
the Function prototype.

The function do_create_interface_objects is removed in favour of 4 functions:
create_callback_interface_object, create_interface_prototype_object,
create_noncallback_interface_object and create_named_constructors.

While this increases the amount of codegen'd code, this greatly improves the
readability of the code involved in this part of DOM, instead of having one function
doing 4 different things. We can always find a more adequate abstraction later.

NativeProperties and everything related to the interface objects have been removed
from the utils module.

Fixes #2665.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8954)

### CODE REVIEW

**Comment by nox** [comment]
For Document, we end up with:

```rust
fn CreateInterfaceObjects(cx: *mut JSContext, global: HandleObject, cache: *mut ProtoOrIfaceArray, receiver: HandleObject) {
    unsafe {
        let mut prototype_proto = RootedObject::new(cx, ptr::null_mut());
        NodeBinding::GetProtoObject(cx, global, receiver, prototype_proto.handle_mut());
        assert!(!prototype_proto.ptr.is_null());

        let mut prototype = RootedObject::new(cx, ptr::null_mut());
        create_interface_prototype_object(cx,
                                          prototype_proto.handle(),
                                          &PrototypeClass,
                                          Some(sMethods),
                                          Some(sAttributes),
                                          &[],
                                          prototype.handle_mut());
        assert!(!prototype.ptr.is_null());
        (*cache)[PrototypeList::ID::Document as usize] = prototype.ptr;
        if <*mut JSObject>::needs_post_barrier(prototype.ptr) {
            <*mut JSObject>::post_barrier((*cache).as_mut_ptr().offset(PrototypeList::ID::Document as isize));
        }

        let mut interface_proto = RootedObject::new(cx, ptr::null_mut());
        NodeBinding::GetConstructorObject(cx, global, receiver, interface_proto.handle_mut());
        assert!(!interface_proto.ptr.is_null());

        let mut interface = RootedObject::new(cx, ptr::null_mut());
        create_noncallback_interface_object(cx,
                                            receiver,
                                            interface_proto.handle(),
                                            &InterfaceObjectClass,
                                            None,
                                            None,
                                            &[],
                                            prototype.handle(),
                                            b"Document\0",
                                            0,
                                            interface.handle_mut());
        assert!(!interface.ptr.is_null());
        (*cache)[PrototypeList::Constructor::Document as usize] = interface.ptr;
        if <*mut JSObject>::needs_post_barrier(prototype.ptr) {
            <*mut JSObject>::post_barrier((*cache).as_mut_ptr().offset(PrototypeList::Constructor::Document as isize));
        }

        let mut unforgeable_holder = RootedObject::new(cx, ptr::null_mut());
        unforgeable_holder.handle_mut().set(
            JS_NewObjectWithoutMetadata(cx, ptr::null(), HandleObject::null()));
        assert!(!unforgeable_holder.ptr.is_null());

        define_properties(cx, unforgeable_holder.handle(), sUnforgeableAttributes).unwrap();
        JS_SetReservedSlot(prototype.ptr, DOM_PROTO_UNFORGEABLE_HOLDER_SLOT,
                           ObjectValue(&*unforgeable_holder.ptr))
    }
}
```

**Comment by frewsxcv** [comment]
Fails tidy

**Comment by Ms2ger** [comment]
I'd still like to try and get the hasInstance stuff into a separate commit. Will try to look tomorrow.

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/bindings/interface.rs, line 173 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8954#-K5q01EdeLpMif0-VgFm:-K5q01EdeLpMif0-VgFn:-598981123) ([raw file](https://github.com/servo/servo/blob/8fdd1dd40939976143ae35e390fed3a565920259/components/script/dom/bindings/interface.rs#L173)):*
I think `define_on_global_object` would be clearer.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8954#-:-K5q17rF94l1m_EjG8kJ:-1870630504)*

**Comment by nox** [comment]
I've just rebuilt on d81fe2f4c5edf469a3b668924a7c0454f0486ecc with the `hasInstance` hook disabled (i.e. set to `None`):

```
± ./mach test-wpt --no-pause /dom/interfaces.html
Running 1 tests in web-platform-tests

  ▶ Unexpected subtest result in /dom/interfaces.html:
  │ FAIL [expected PASS] Document interface: xmlDoc must inherit property "implementation" with the proper type (0)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Document interface: xmlDoc must inherit property "children" with the proper type (29)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: xmlDoc must inherit property "childNodes" with the proper type (19)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] DocumentFragment interface: document.createDocumentFragment() must inherit property "children" with the proper type (1)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.createDocumentFragment() must inherit property "ownerDocument" with the proper type (15)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.createDocumentFragment() must inherit property "childNodes" with the proper type (19)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.doctype must inherit property "ownerDocument" with the proper type (15)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.doctype must inherit property "parentNode" with the proper type (16)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.doctype must inherit property "childNodes" with the proper type (19)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.doctype must inherit property "nextSibling" with the proper type (23)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Element interface: element must inherit property "classList" with the proper type (6)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Element interface: element must inherit property "attributes" with the proper type (8)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Element interface: element must inherit property "children" with the proper type (27)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: element must inherit property "ownerDocument" with the proper type (15)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: element must inherit property "childNodes" with the proper type (19)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Attr interface: document.querySelector("[id]").attributes[0] must inherit property "ownerElement" with the proper type (7)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.createTextNode("abc") must inherit property "ownerDocument" with the proper type (15)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.createTextNode("abc") must inherit property "childNodes" with the proper type (19)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: xmlDoc.createProcessingInstruction("abc", "def") must inherit property "ownerDocument" with the proper type (15)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: xmlDoc.createProcessingInstruction("abc", "def") must inherit property "childNodes" with the proper type (19)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.createComment("abc") must inherit property "ownerDocument" with the proper type (15)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Node interface: document.createComment("abc") must inherit property "childNodes" with the proper type (19)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Range interface: document.createRange() must inherit property "startContainer" with the proper type (0)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Range interface: document.createRange() must inherit property "endContainer" with the proper type (2)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Range interface: document.createRange() must inherit property "commonAncestorContainer" with the proper type (5)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Range interface: detachedRange must inherit property "startContainer" with the proper type (0)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Range interface: detachedRange must inherit property "endContainer" with the proper type (2)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] Range interface: detachedRange must inherit property "commonAncestorContainer" with the proper type (5)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] NodeIterator interface: document.createNodeIterator(document.body, NodeFilter.SHOW_ALL, null, false) must inherit property "root" with the proper type (0)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] NodeIterator interface: document.createNodeIterator(document.body, NodeFilter.SHOW_ALL, null, false) must inherit property "referenceNode" with the proper type (1)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] TreeWalker interface: document.createTreeWalker(document.body, NodeFilter.SHOW_ALL, null, false) must inherit property "root" with the proper type (0)
  │   → invalid 'instanceof' operand self[type]
  │ FAIL [expected PASS] TreeWalker interface: document.createTreeWalker(document.body, NodeFilter.SHOW_ALL, null, false) must inherit property "currentNode" with the proper type (3)
  │   → invalid 'instanceof' operand self[type]
  │
  │ IdlArray.prototype.assert_type_is@http://web-platform.test:8000/resources/idlharness.js:468:13
  │ IdlInterface.prototype.test_interface_of/<@http://web-platform.test:8000/resources/idlharness.js:1447:29
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ IdlInterface.prototype.test_interface_of@http://web-platform.test:8000/resources/idlharness.js:1416:1
  │ IdlInterface.prototype.test_object@http://web-platform.test:8000/resources/idlharness.js:1329:9
  │ IdlArray.prototype.test/<@http://web-platform.test:8000/resources/idlharness.js:325:17
  │ IdlArray.prototype.test@http://web-platform.test:8000/resources/idlharness.js:323:13
  └ @http://web-platform.test:8000/dom/interfaces.html:33:1

Ran 1 tests finished in 2.0 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 1 tests had unexpected subtest results
```

So this was actually already provided by the fact that `create_constructor` uses `JS_NewFunction` in the current code. That's why I believe it can't be moved to another commit without a regression.

**Comment by nox** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/bindings/interface.rs, line 173 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8954#-K5q01EdeLpMif0-VgFm:-K5rLmBHFIV6_FYMuhu2:-499146009) ([raw file](https://github.com/servo/servo/blob/8fdd1dd40939976143ae35e390fed3a565920259/components/script/dom/bindings/interface.rs#L173)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8954)*

**Comment by nox** [comment]
@Ms2ger Ping?

**Comment by Ms2ger** [comment]
Refactor prototype initialisation
=================================

```python
getParentProto = "prototype_proto.ptr = JS_GetObjectPrototype(cx, global)"
```

`getParentProto` made sense when it was defining `parent_proto`, not so much for `prototype_proto`.


```diff
+        if self.descriptor.interface.isCallback():
+            assert not self.descriptor.interface.ctor()
```

Also assert `self.descriptor.interface.hasConstants()` here.

```diff
+/// Create and define the interface object of a callback interface.
+pub unsafe fn create_callback_interface_object(cx: *mut JSContext,
+                                               receiver: HandleObject,
+                                               constructor_native: NonNullJSNative,
+                                               length: u32,
+                                               constants: &'static [ConstantSpec],
+                                               name: &'static [u8]) {
+    assert!(!constants.is_empty());
+    let obj = RootedObject::new(cx, create_constructor(cx, constructor_native, length, name));
```

Maybe `interface_object` rather than `obj`.

```diff
+unsafe fn define_on_global_object(
+        cx: *mut JSContext,
+        receiver: HandleObject,
+        name: &'static [u8],
```

Please assert this is null-terminated

```python
            if self.descriptor.interface.ctor():
                properties["length"] = methodLength(self.descriptor.interface.ctor())
            else:
                properties["length"] = 0

            if self.descriptor.interface.ctor():
                properties["constructor"] = CONSTRUCT_HOOK_NAME
            else:
                properties["constructor"] = "throwing_constructor"
```

I think I would prefer having just one `if`. (But the second one is going away later, so feel free to leave it.)

```diff
+pub unsafe fn create_noncallback_interface_object(
+        cx: *mut JSContext,
+        receiver: HandleObject,
+        constructor_native: NonNullJSNative,
+        static_methods: Option<&'static [JSFunctionSpec]>,
+        static_properties: Option<&'static [JSPropertySpec]>,
+        constants: &'static [ConstantSpec],
+        interface_prototype_object: HandleObject,
```

Assert this is not null.

```diff
+        name: &'static [u8],
+        length: u32,
+        rval: MutableHandleObject) {
```

Is there any reason for this to have an `rval`?

```diff
+    define_name(cx, rval.handle(), name);
+    define_length(cx, rval.handle(), length);
```

My fault: this should go into the other commit, along with the definition of `define_length`. `define_name` should go in the commit that changes `create_callback_interface_object`.


Use the object prototype for callback interface objects
=======================================================

```diff
         if self.descriptor.interface.isCallback():
-            assert not self.descriptor.interface.ctor()
```

I guess maybe keep this assertion.

Describe non-callback interface objects with JSClass structures
===============================================================

```diff
+            code.append(CGGeneric("""
+let interface_proto = RootedObject::new(cx, JS_GetFunctionPrototype(cx, global));"""))
             code.append(CGGeneric("""\
+assert!(!interface_proto.ptr.is_null());
```

The two separate strings here look weird. (Also changed later, never mind.)

```diff
+class CGClassHasInstanceHook(CGAbstractExternMethod):
+    def definition_body(self):
+        index = len(self.descriptor.prototypeChain) - 1
```

This calculation also happens in `CGClassHasInstanceHook`; can we introduce a small helper function?

```diff
+    while JS_GetPrototype(cx, value.handle(), value.handle_mut()) {
```

If `JS_GetPrototype` returns false, we should propagate that from the `hasInstance` hook. Either return `Result<bool, ()>` or an outparam.

Fix prototypes of interface objects (fixes #2665)
=================================================

Okay, I guess.

**Comment by nox** [comment]
@bors-servo r=Ms2ger

I addressed all your remarks.

**Comment by nox** [comment]
Bot is playing dead on the other PR.

@bors-servo force

**Comment by nox** [comment]
Looks like I forgot a hook for toString while removing the use of JS_NewFunction. :(

**Comment by nox** [comment]
https://github.com/servo/mozjs/pull/69

**Comment by nox** [comment]
https://github.com/servo/rust-mozjs/pull/231

**Comment by nox** [comment]
https://github.com/rust-lang/rust/pull/30733

**Comment by nox** [comment]
@Ms2ger "Describe non-callback interface objects with JSClass structures" needs a new review, I introduce NonCallbackInterfaceObjectClass in there, and implement fun_to_string. I do that once per interface even though the function can be shared between all of them by adding fields to the structure, but I guess that can be done in follow-ups, possibly easy ones.

**Comment by nox** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLFormControlsCollection interface: existence and properties of interface object

  ▶ Unexpected subtest result in /_mozilla/mozilla/documentElement.html:
  │ FAIL [expected PASS] Untitled
  │   → assert_true: Should be Window expected true got false
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/documentElement.html:2:3
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  └ @http://web-platform.test:8000/_mozilla/mozilla/documentElement.html:1:1

  ▶ Unexpected subtest result in /_mozilla/mozilla/window.html:
  │ FAIL [expected PASS] Untitled
  │   → assert_true: Should be Window expected true got false
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/window.html:3:3
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  └ @http://web-platform.test:8000/_mozilla/mozilla/window.html:1:1
```

**Pull request merged**
