### PR TITLE
Websocket errors

### LINKED ISSUE #7861: Don't ignore errors when sending data over websockets
In `WebSocket::send` we ignore the result of actually sending the data over the network. That causes us to fail tests, funnily enough :) Following the [spec](https://tools.ietf.org/html/rfc6455#section-10.7) for dealing with invalid data, we should be dispatching a `CloseTask` to ensure that the connection is terminated, and additionally for certain cases of errors we should be implementing the `fail the websocket connection` algorithm which causes the `close the websocket connection` to dispatch an `error` event at the `WebSocket` object. One example is when there are [errors processing UTF-8 data](https://tools.ietf.org/html/rfc6455#section-8.1), which corresponds to a case in the [error result](http://doc.servo.org/websocket/result/enum.WebSocketError.html) from calling send!

Test: `./mach test-wpt tests/wpt/web-platform-tests/websockets/interfaces/WebSocket/events/018.html`
Code: components/script/dom/websocket.rs

### PR DESCRIPTION
**Pull request by samfoo**
Fixes #7861. Errors should be triggered on failed connections (e.g. invalid DNS resolution, invalid port, etc) and on invalid message data (e.g. improperly encoded UTF-8 messages).

Errors are simple errors and should not reveal to the script any details about the failure that could lead to probing.

The spec recommends a message to the console as an indication to developers what went wrong, but I've not implemented that. I believe another issue should be opened for this.

Relevant:

https://html.spec.whatwg.org/multipage/comms.html#handler-eventsource-onerror
https://tools.ietf.org/html/rfc6455#section-8
http://www.w3.org/TR/websockets/#concept-websocket-close-fail

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8868)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you for your PR.

Just one thing I noticed, see below.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/websocket.rs, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8868#-K4yVLSbhY6iFcTLYpN8:-K4yVLSbhY6iFcTLYpN9:1840971465) ([raw file](https://github.com/servo/servo/blob/5d3d3cfe32c57fe4bd0c0715f3d7910114774d46/components/script/dom/websocket.rs#L192)):*
The HTML spec says (after "When the WebSocket connection is closed, …") that the error event should be dispatched first. Please check if there are any tests that start to pass when you switch those around?

Also, while there's currently no way to detect this, I don't think we should send two messages where the spec only has one "task". It might be best to factor out some code from the `CloseTask` implementation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8868#-:-K4yWDlY--Nk3GTGUHFX:939075217)*

**Comment by samfoo** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/websocket.rs, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8868#-K4yVLSbhY6iFcTLYpN8:-K5TwrdtMRHvoQ-dN8Q2:-1298033518) ([raw file](https://github.com/servo/servo/blob/5d3d3cfe32c57fe4bd0c0715f3d7910114774d46/components/script/dom/websocket.rs#L192)):*
There are already tests for it.

You're right about the `Task` bit, I didn't realise that the `CloseTask` already had some error mechanic in it. I've now refactored it.

I just tested (by swapping the order) and there are no WPT tests for the order of event dispatch. I could write a new WPT test for this if we think it's necessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8868)*

**Comment by KiChjang** [comment]
@samfoo ping?

**Comment by jdm** [comment]
This isn't waiting on @samfoo; it's waiting on being re-reviewed.

**Comment by jsanders** [comment]
@samfoo: #9358 caused all sorts of conflict with this! Sorry about that, let me know if you want to discuss how to approach merging.

**Comment by samfoo** [comment]
@jsanders, probably easiest to just re-write it. Just starting a new job, so my response time is slow.

**Comment by jdm** [comment]
Rebased in #9757. It turns out the changes here were exceedingly similar to the ones made by @jsanders, but the ones here were slightly more correct and therefore made more tests pass :)

**Pull request closed without merging**
