### PR TITLE
Always send epochs to webrender in layout 2020

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23940)

### CODE REVIEW

**Review by emilio — APPROVED** [review]
rs+

**Comment by jdm** [comment]
```
Diff in /repo/components/layout_thread_2020/lib.rs at line 957:
     }
 
     /// Advances the animation clock of the document.
[31m-    fn handle_advance_clock_ms<'a, 'b>(
(B[m[31m-        &mut self,
(B[m[31m-        how_many_ms: i32,
(B[m[31m-        tick_animations: bool,
(B[m[31m-    ) {
(B[m[32m+    fn handle_advance_clock_ms<'a, 'b>(&mut self, how_many_ms: i32, tick_animations: bool) {
(B[m         self.timer.increment(how_many_ms as f64 / 1000.0);
         if tick_animations {
             self.tick_all_animations();
Diff in /repo/components/layout_thread_2020/lib.rs at line 1281:
         }
 
         // Perform post-style recalculation layout passes.
[31m-        self.perform_post_style_recalc_layout_passes(
(B[m[31m-            &data.reflow_goal,
(B[m[31m-            Some(&document),
(B[m[31m-        );
(B[m[32m+        self.perform_post_style_recalc_layout_passes(&data.reflow_goal, Some(&document));
(B[m 
         self.first_reflow.set(false);
         self.respond_to_query_if_necessary(&data.reflow_goal, &mut *rw_data, &mut layout_context);
Diff in /repo/components/layout_thread_2020/lib.rs at line 1416:
                 ua_or_user: &ua_or_user_guard,
             };
 
[31m-            self.perform_post_style_recalc_layout_passes(
(B[m[31m-                &ReflowGoal::TickAnimations,
(B[m[31m-                None,
(B[m[31m-            );
(B[m[32m+            self.perform_post_style_recalc_layout_passes(&ReflowGoal::TickAnimations, None);
(B[m         }
     }
 
Run `./mach fmt` to fix the formatting
```

**Pull request merged**
