### PR TITLE
Start implementing protocolDescription and canCurrentlyRecord in devtools

### PR DESCRIPTION
**Pull request by nox**
We can merge it but it doesn't make things work more than before. Mostly filing it for comments, especially the `description` method. If you feel it's too verbose I guess the way to go would be to properly formalise all types involved in the devtools server, but that's going to be a gigantic task.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11094)

### CODE REVIEW

**Comment by nox** [comment]
This PR makes the remote debugger in Firefox show a "start recording" button in the performance tab, but recording isn't implemented yet.

**Comment by larsbergstrom** [comment]
r? @Ms2ger 

Or is there somebody else that should be looking at this? It all lgtm, but I don't know anything about the devtools integration.

**Comment by Ms2ger** [comment]
Without a protocol definition from the devtools people, there's not much I can review here, but if it improves things, let's do it.

@bors-servo r+

**Comment by KiChjang** [comment]
Fails tidy:
```
$ ./mach test-tidy --no-progress
Checking files for tidiness...
./components/devtools/actors/root.rs:12: use statement is not in alphabetical order
	expected: actors::tab::{TabActor, TabActorMsg}
	found: actors::performance::PerformanceActor
```

**Pull request merged**
