### PR TITLE
Fix #6379

### LINKED ISSUE #6379: Should send an Origin header.
Blocks #6060.

At least `websockets/security/001.html` seems to rely on it. Not sure where the spec is. This probably needs to be fixed in https://github.com/cyderize/rust-websocket, though.

### PR DESCRIPTION
**Pull request by cuzbog**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6532)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

Can you run the websocket tests and see if any new failures are reported? `./mach test-wpt websockets` should do the trick.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/websocket.rs, line 152 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6532#-JtFlptdaN-N-1rf7kUf)** ([raw file](https://github.com/servo/servo/blob/81b09be87ea3ee6426ff23fcabe7a34851954a1e/components/script/dom/websocket.rs#L152)):</sup>
http://doc.servo.org/websocket/header/struct.Origin.html
request.headers.set(Origin(global.get_url().serialize()));

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6532)

**Comment by boghison** [comment]
@jdm I ran the tests (both with this commit and without it). There's a very large output and as far as I can see a lot of tests aren't passed in both cases. Is there any way to test specifically against the origin header?

**Comment by jdm** [comment]
You can run the specific test that @Ms2ger mentioned in the issue with `./mach test path/to/test.html`. That being said, the actual failures that are reported by the harness are summarized at the end of the run. Those are tests where the output is different than expected; we have a lot of tests that do not succeed, but that is an expected failure so it doesn't get reported.

**Comment by boghison** [comment]
@jdm OK, I ran the specific test, but it panicked "thread 'ScriptTask PipelineId(0)' panicked at 'called `Result::unwrap()` on an `Err` value: ResponseError("Sec-WebSocket-Accept is invalid")', src/libcore/result.rs:731

**Comment by boghison** [comment]
Umm, excuse me, is someone going to merge this or not (it now sends the origin header, I tested it myself)

**Comment by Ms2ger** [comment]
It looks like there are outstanding review comments on reviewable.

**Comment by boghison** [comment]
@Ms2ger Oh sorry, I didn't get a notification or anything, gonna change that line now

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6532)

**Comment by jdm** [comment]
```
/websockets/constructor/010.html
--------------------------------
TIMEOUT WebSockets: protocol in response but no requested protocol
TIMEOUT expected CRASH [Parent]
/websockets/constructor/011.html
--------------------------------
TIMEOUT WebSockets: protocol mismatch
TIMEOUT expected CRASH [Parent]
/websockets/constructor/012.html
--------------------------------
TIMEOUT WebSockets: no protocol in response
TIMEOUT expected CRASH [Parent]
/websockets/cookies/002.html
----------------------------
FAIL WebSockets: Set-Cookie in response
OK expected CRASH [Parent]
/websockets/cookies/004.html
----------------------------
OK expected CRASH [Parent]
/websockets/cookies/007.html
----------------------------
FAIL WebSockets: when to process set-cookie fields in ws response
OK expected CRASH [Parent]
/websockets/cookies/005.html
----------------------------
TIMEOUT WebSockets: setting HttpOnly cookies in ws response, checking ws request
TIMEOUT expected CRASH [Parent]
/websockets/opening-handshake/005.html
--------------------------------------
TIMEOUT WebSockets: proper first line
TIMEOUT expected CRASH [Parent]
```

**Comment by SimonSapin** [comment]
@boghison For future PRs, could you write more descriptive titles? Thanks! (“Fix #6379” alone does not say much when you don’t know from memory what #6379 is about.)

**Comment by boghison** [comment]
@SimonSapin Ok
@jdm I am not sure whether these changes are caused by my changes

**Comment by jdm** [comment]
@boghison They are all difference in the test output caused by your changes, so the test expectation files need to be updated to match them, eg. http://mxr.mozilla.org/servo/source/tests/wpt/metadata/websockets/opening-handshake/005.html.ini

**Comment by boghison** [comment]
@jdm I've never edited these, what do I have to do?

**Comment by boghison** [comment]
Actually nevermind, I just have to replace CRASH with PASS, right?

**Comment by jdm** [comment]
Precisely. For the tests with new FAIL output (rather than a `FOO expected BLAH`), you need a new entry like:
```
[output message goes here]
  expected: FAIL
```

**Comment by jdm** [comment]
@boghison The other option is to follow the steps at http://mxr.mozilla.org/servo/source/tests/wpt/README.md#71 and update all the expectations automatically.

**Comment by boghison** [comment]
@jdm I already started doing that ~5 mins ago, thanks for writing a guide (for noobs like me) :)

**Comment by jdm** [comment]
Oh sorry, github doesn't notify us when a new push happens so I didn't see the new commit. Unfortunately there are a lot of WPT test expectations here that don't belong, so I'll try rebasing this locally.

**Comment by boghison** [comment]
@jdm OK

**Pull request closed without merging**
