### PR TITLE
When an iframe loads a new page, dirty and reflow it so that the layout fragment will pick up the new subpage ID.

### LINKED ISSUE #8081: iframe not painted anymore after navigation (regression c72d0c2)
Since commit c72d0c2ed04f6c5f9fa22a3f576e1df5878f941d, clicking a link in a iframe turns the iframe white.

I believe the iframe is loaded but not painted (we get load events).

### PR DESCRIPTION
**Pull request by pcwalton**
This is necessary to make its new contents show up!

Closes #8081.

r? @jdm 

cc @paulrouget @glennw

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8662)

### CODE REVIEW

**Comment by pcwalton** [comment]
cc @metajack as well.

**Comment by eefriedman** [comment]
The page shouldn't actually be changing visibly until around step 22 of the navigate algorithm, after we see the initial response from the server (https://html.spec.whatwg.org/multipage/browsers.html#navigating-across-documents).  This patch marks the iframe dirty and forces a reflow around step 10 or so.

I'm not completely sure whether that indicates a problem with your patch or a more general architectural issue.

**Comment by pcwalton** [comment]
I think the correct solution to that is to not update the iframe DOM node's stored subpage ID until the right time. Relying on the timing of dirty bits and reflows is wrong since those can be set or can happen for lots of reasons.

In other words I think that's a preexisting problem independent of this patch.

**Comment by Ms2ger** [comment]
Why is the `force_reflow` necessary exactly? It would be nice to have documentation so I could figure out when it's necessary from first principles rather than having to take it on faith.

**Comment by pcwalton** [comment]
I'll see if I can use reflow instead of force reflow.

Renaming force reflow and reflow seems out of scope for this patch.

**Comment by pcwalton** [comment]
Updated to use `reflow` instead of `force_reflow`. r? @jdm

**Comment by jdm** [comment]
@eefriedman is right. I think this actually intersects with #8612, and we should piggy-back off of that work. I propose we add a Constellation->Script message called `FramedContentChanged`, which is sent to the script task for the framing pipeline. This will mark the iframe element as dirty and initiate the reflow, and will be sent from the code in the constellation that receives the ActivateDocument message in #8612.

**Comment by pcwalton** [comment]
#8612 seems blocked for whatever reason. Status?

**Comment by jdm** [comment]
@glennw and I decided to go with his proposed simple solution in that PR last week.

**Comment by glennw** [comment]
I implemented the simple solution yesterday. But when I ran WPT tests a heap of unexpected failures occurred. I suspect it's exposing a different race, but perhaps there is a bug in the implementation. I'll try to look into it again today.

**Comment by glennw** [comment]
@pcwalton @jdm #8612 has landed now, if that was still blocking further work here.

**Comment by metajack** [comment]
@pcwalton This is the last known P1 browser.html blocker, so let's get this rebased an landed.

**Comment by pcwalton** [comment]
Superseded by #9285.

**Pull request closed without merging**
