### PR TITLE
Fix an overflow issue in the layout_2020 unit tests

### PR DESCRIPTION
**Pull request by ohno418**
Fix failing unit test due to overflow.

<details>
<summary>failing test log</summary>

```
$ ./mach test-unit test_tree_range_setting
      Timing report saved to /path/to/servo/target/cargo-timings/cargo-timing-20230805T090747Z.html
    Finished test [unoptimized + debuginfo] target(s) in 1.44s
     Running unittests lib.rs (target/debug/deps/background_hang_monitor-991cde6a4bf697da)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/hang_monitor_tests.rs (target/debug/deps/hang_monitor_tests-17afc9a90835517e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out; finished in 0.00s

     Running unittests lib.rs (target/debug/deps/deny_public_fields_tests-b51bf4d3d71f1a6e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests lib.rs (target/debug/deps/gfx-b6fdddc62e398b7a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/font_context.rs (target/debug/deps/font_context-06c616d3ef15ae5e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s

     Running tests/font_template.rs (target/debug/deps/font_template-0da502ba1710f24f)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running tests/text_util.rs (target/debug/deps/text_util-6a692eb5174b3c2a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 5 filtered out; finished in 0.00s

     Running unittests lib.rs (target/debug/deps/layout_2013-ac2da0712ac98b6d)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/size_of.rs (target/debug/deps/size_of-c1dd212ed2b13bce)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.00s

     Running unittests lib.rs (target/debug/deps/layout_2020-b5d6abbe15bdcf6d)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running tests/floats.rs (target/debug/deps/floats-7fafad8026494fc8)

running 1 test
test test_tree_range_setting ... FAILED

failures:

---- test_tree_range_setting stdout ----
thread 'test_tree_range_setting' panicked at 'attempt to add with overflow', components/layout_2020/tests/floats.rs:317:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test_tree_range_setting' panicked at 'attempt to add with overflow', components/layout_2020/tests/floats.rs:317:23
thread 'test_tree_range_setting' panicked at 'attempt to add with overflow', components/layout_2020/tests/floats.rs:317:23
thread 'test_tree_range_setting' panicked at 'attempt to add with overflow', components/layout_2020/tests/floats.rs:317:23
thread 'test_tree_range_setting' panicked at 'attempt to add with overflow', components/layout_2020/tests/floats.rs:317:23
thread 'test_tree_range_setting' panicked at 'attempt to add with overflow', components/layout_2020/tests/floats.rs:317:23
thread 'test_tree_range_setting' panicked at 'attempt to add with overflow', components/layout_2020/tests/floats.rs:317:23
thread 'test_tree_range_setting' panicked at 'attempt to add with overflow', components/layout_2020/tests/floats.rs:317:23
thread 'test_tree_range_setting' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ([], [FloatRangeInput { start_index: 2186238731, side: Left, length: 3516551292 }])
Error: "attempt to add with overflow"', /home/ohno/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-1.0.3/src/tester.rs:165:28


failures:
    test_tree_range_setting

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 14 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p layout_2020 --test floats`
```

</details>

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Review by mrobinson — CHANGES_REQUESTED** [review]
Please remove the changes to `tests/unit/style/lib.rs` and `tests/unit/style/stylesheets.rs` as these files are vendored from the upstream Gecko repository and we are systematically updating them. The proper place to push these fixes would be to Gecko itself since this is shared code.

**Comment by mrobinson** [comment]
Thanks for this fix! There's just one issue with this change, but otherwise it looks good.

**Comment by ohno418** [comment]
> these files are vendored from the upstream Gecko repository and we are systematically updating them.

Understood. Thanks!

**Review by mrobinson — APPROVED** [review]
Thanks again!

**Pull request merged**
