### PR TITLE
Add test for createDocument().

### PR DESCRIPTION
**Pull request by JayNakrani**
Solves Issue #5754.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5761)

### CODE REVIEW

**Comment by jdm** [comment]
Ah, sorry I wasn't more specific in #5754. This should follow the model of the other tests in that file - specifically, we should at least be cloning the node and testing the expected properties on the clone :)

**Comment by dhananjay92** [comment]
Oh! Failed to notice that! :sweat_smile: 
Updated the test case to follow that model.

**Comment by jdm** [comment]
Reviewed files:
- tests/wpt/mozilla/tests/mozilla/node_cloneNode.html @ r1

---

<sup>**[tests/wpt/mozilla/tests/mozilla/node_cloneNode.html, line 186 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5761#-JnRDf9elIoGk_U6g6kI)** ([raw file](https://github.com/servo/servo/blob/b5dcba5fed7f41fc5bf22a3d4a1baca4db471bca/tests/wpt/mozilla/tests/mozilla/node_cloneNode.html#L186)):</sup>
Let's just use `document.implementation.createDocument(null, null)` instead, since we're not testing anything about the extra arguments here.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5761)

**Comment by dhananjay92** [comment]
<sup>**[tests/wpt/mozilla/tests/mozilla/node_cloneNode.html, line 186 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5761#-JnRDf9elIoGk_U6g6kI)** ([raw file](https://github.com/servo/servo/blob/b5dcba5fed7f41fc5bf22a3d4a1baca4db471bca/tests/wpt/mozilla/tests/mozilla/node_cloneNode.html#L186)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5761)

**Comment by jdm** [comment]
Reviewed files:
- tests/wpt/mozilla/tests/mozilla/node_cloneNode.html @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5761)

**Pull request merged**
