### PR TITLE
Implement private browsing for mozbrowser

### PR DESCRIPTION
**Pull request by jdm**
Support the `mozprivatebrowsing` attribute on mozbrowser iframes. This separates the non-private and private sessions in terms of cookies, HSTS lists, cached HTTP credentials, HTTP connection pools, and web storage. The private session is shared between all private mozbrowsers, and lasts until shutdown. 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11544)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Mostly this looks good, but there is one big change I think is worth making.

This PR adds the pipeline id to each of the resource messages, but not the privacy level of the pipeline. Since the resource thread doesn't know the privacy level, it has to send a message to the constellation asking it. This adds quite a bit of complexity to the code, and involves the constellation in every resource access. Life would be a lot simpler if the resource messages included the privacy level of the pipeline, not just the pipeline id.

<details><summary><i>Previously, highfive wrote…</i></summary>
> Heads up! This PR modifies the following files:
>  * @asajeffrey: components/constellation/constellation.rs, components/constellation/pipeline.rs
>  * @kichjang: components/script/dom/htmliframeelement.rs, components/script/dom/document.rs, components/net/resource_thread.rs, components/net_traits/lib.rs, components/net_traits/lib.rs, components/script/dom/websocket.rs, components/script/dom/webidls/HTMLIFrameElement.webidl
</details>


---

Reviewed 6 of 9 files at r1, 3 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[components/constellation/constellation.rs, line 105 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC1FOOQkkFelBOSXI7:-KJC1FOOQkkFelBOSXI8:-1272839441) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/constellation/constellation.rs#L105)):*
> ```Rust
> 
>     /// Receives ConstellationMsg
>     pub resource_msg_receiver: Receiver<FromResourceMsg>,
> ```

This channel wouldn't be needed if the resource messages included the privacy level.

---

*[components/constellation/constellation.rs, line 340 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC175USQtxTD8S_onf:-KJC175USQtxTD8S_ong:-1272839441) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/constellation/constellation.rs#L340)):*
> ```Rust
>                 panic_sender: ipc_panic_sender,
>                 compositor_receiver: compositor_receiver,
>                 resource_msg_receiver: resource_receiver,
> ```

This channel wouldn't be needed if the resource messages included the privacy level.

---

*[components/constellation/constellation.rs, line 420 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJBzvD1CrlvGYcdeWU9:-KJBzvD265_QS48ECdSH:1940287339) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/constellation/constellation.rs#L420)):*
> ```Rust
>                     script_channel: Option<IpcSender<ConstellationControlMsg>>,
>                     load_data: LoadData,
>                     is_private: bool) {
> ```

Better to use an enum for this?

---

*[components/constellation/constellation.rs, line 503 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC13HGtZ8zAMKZpay7:-KJC13HGtZ8zAMKZpay8:791679158) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/constellation/constellation.rs#L503)):*
> ```Rust
>             Layout(FromLayoutMsg),
>             Panic(PanicMsg),
>             Resource(FromResourceMsg),
> ```

This case wouldn't be needed if the resource messages included the privacy level.

---

*[components/constellation/constellation.rs, line 533 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC0zNqE5zPLOZD6CZE:-KJC0zNqE5zPLOZD6CZF:1258462696) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/constellation/constellation.rs#L533)):*
> ```Rust
>                     Request::Panic(msg.expect("Unexpected panic channel panic in constellation")),
>                 msg = receiver_from_constellation_msg.recv() =>
>                     Request::Resource(msg.expect("Unexpected resource failure in constellation"))
> ```

This branch wouldn't be needed if the resource messages included the privacy level.

---

*[components/constellation/constellation.rs, line 560 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC0uV_aGrKXg89yt9i:-KJC0uV_aGrKXg89yt9j:-513479114) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/constellation/constellation.rs#L560)):*
> ```Rust
>     }
> 
>     fn handle_request_from_resource(&self, message: FromResourceMsg) {
> ```

This handler wouldn't be needed if the resource messages included the privacy level.

---

*[components/net/resource_thread.rs, line 412 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJBzZjHthtByZ_E0Euk:-KJBzZjHthtByZ_E0Eul:-2053682486) ([raw file](https://github.com/servo/servo/blob/771628b473cc0639f826b4cb209bccb59a49f2c6/components/net/resource_thread.rs#L412)):*
> ```Rust
>             read_json_from_file(&mut cookie_jar, config_dir, "cookie_jar.json");
>         }
>         let resource_group = ResourceGroup {
> ```

Add `ResourceGroup::new`?

---

*[components/net/resource_thread.rs, line 395 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC0kHgN8PKAVmht2Bf:-KJC0kHgN8PKAVmht2Bg:-1272839441) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/net/resource_thread.rs#L395)):*
> ```Rust
>     cancel_load_map: HashMap<ResourceId, Sender<()>>,
>     next_resource_id: ResourceId,
>     constellation_msg_chan: Option<IpcSender<ConstellationMsg>>,
> ```

This channel wouldn't be needed if the resource messages included the privacy level.

---

*[components/net/resource_thread.rs, line 520 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC-P3gT75ZS8HMGhHO:-KJC-P3gT75ZS8HMGhHP:-1636955803) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/net/resource_thread.rs#L520)):*
> ```Rust
>     }
> 
>     fn get_resource_group(&self, pipeline_id: Option<PipelineId>) -> ResourceGroup {
> ```

This is sending a message to the constellation every time a resource is accessed. Wouldn't it be easier to make the parameter to this function a resource group name (or just `is_private: bool` if you prefer). If the resource messages included the pipeline's privacy level, this means the constellation wouldn't be involved in checking privacy levels.

---

*[components/net_traits/lib.rs, line 333 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC0JJuEbjunkfwiUFc:-KJC0JJuEbjunkfwiUFd:-1277258633) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/net_traits/lib.rs#L333)):*
> ```Rust
>     Load(LoadData, LoadConsumer, Option<IpcSender<ResourceId>>),
>     /// Try to make a websocket connection to a URL.
>     WebsocketConnect(PipelineId, WebSocketCommunicate, WebSocketConnectData),
> ```

Life would be a lot easier if you included the privacy level of the pipeline in this message.

---

*[components/net_traits/lib.rs, line 343 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC0W4TgBPmGxm30HHQ:-KJC0W4TgBPmGxm30HHR:761668083) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/net_traits/lib.rs#L343)):*
> ```Rust
>     Synchronize(IpcSender<()>),
>     /// Send the channel for checking a private pipeline
>     SendConstellationMsgChannel(IpcSender<ConstellationMsg>),
> ```

This message wouldn't be needed if the resource messages included the privacy level.

---

*[components/script/dom/htmliframeelement.rs, line 495 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC21P9a65fTlR0iTQl:-KJC21P9a65fTlR0iTQm:2049705930) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/script/dom/htmliframeelement.rs#L495)):*
> ```Rust
>     // check-tidy: no specs after this line
>     fn SetMozprivatebrowsing(&self, value: bool) {
>         let element = self.upcast::<Element>();
> ```

Check if mozbrowser is enabled?

---

*[components/script/dom/htmliframeelement.rs, line 499 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJC26IE50hF0HHk6BAz:-KJC26IE50hF0HHk6BB-:2049705930) ([raw file](https://github.com/servo/servo/blob/82155b34591cbc883bd3dc94b934e04aa5664917/components/script/dom/htmliframeelement.rs#L499)):*
> ```Rust
>     }
> 
>     fn Mozprivatebrowsing(&self) -> bool {
> ```

Check if mozbrowser is enabled?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11544#-:-KJC2OBrsTh7i39E5oFh:235196883)*

**Comment by asajeffrey** [comment]
IRC chat: http://logs.glob.uno/?c=mozilla%23servo&s=2+Jun+2016&e=2+Jun+2016&h=private#c446852

**Comment by asajeffrey** [comment]
OK, looks much nicer!

<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> IRC chat: http://logs.glob.uno/?c=mozilla%23servo&s=2+Jun+2016&e=2+Jun+2016&h=private#c446852
</details>


---

Reviewed 8 of 9 files at r4, 4 of 4 files at r5, 3 of 3 files at r6, 9 of 9 files at r7.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[components/constellation/constellation.rs, line 424 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJvExSbp8Sa-z2aUs9n:-KJvExSbp8Sa-z2aUs9o:-581803246) ([raw file](https://github.com/servo/servo/blob/5ec01d9dcafe81bfba3cd053015393baae5f3e37/components/constellation/constellation.rs#L424)):*
> ```Rust
>                     load_data: LoadData,
>                     is_private: bool) {
>         if self.shutting_down { return; }
> ```

This change doesn't appear to have much to do with private browsing, care to comment?

---

*[components/net/resource_thread.rs, line 209 \[r7\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJvFOTGtqmoN2EVFeim:-KJvFOTGtqmoN2EVFein:-1413444196) ([raw file](https://github.com/servo/servo/blob/e29b29943b05bda1d0f98a1e8670d4d380190e81/components/net/resource_thread.rs#L209)):*
> ```Rust
>     let mut hsts_list = HstsList::from_servo_preload();
>     let mut auth_cache = AuthCache::new();
>     let mut cookie_jar = CookieStorage::new();
> ```

Just inline auth_cache and cookie_jar below? That way the public and private cases are symmetric.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11544#-:-KJvG0dP8v1EKsxU3uPY:-2043494690)*

**Comment by asajeffrey** [comment]
`./mach test-unit is failing`:

```
$ ./mach test-unit
   Compiling util_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/util)
   Compiling profile_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/profile)
   Compiling style_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/style
   Compiling net_traits_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/net_traits)
   Compiling gfx_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/gfx)
   Compiling net_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/net)
   Compiling script_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/script)
   Compiling layout_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/layout)
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:44:21: 44:25 error: no method named `send` found for type `(ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>, ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>)` in the current scope
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:44     resource_thread.send(CoreResourceMsg::Exit(sender)).unwrap();
                                                                                        ^~~~
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:55:21: 55:25 error: no method named `send` found for type `(ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>, ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>)` in the current scope
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:55     resource_thread.send(CoreResourceMsg::Load(LoadData::new(LoadContext::Browsing, url, &ResourceTest),
                                                                                        ^~~~
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:63:21: 63:25 error: no method named `send` found for type `(ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>, ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>)` in the current scope
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:63     resource_thread.send(CoreResourceMsg::Exit(sender)).unwrap();
                                                                                        ^~~~
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:237:21: 237:25 error: no method named `send` found for type `(ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>, ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>)` in the current scope
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:237     resource_thread.send(CoreResourceMsg::Load(LoadData::new(LoadContext::Browsing, url, &ResourceTest),
                                                                                         ^~~~
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:242:21: 242:25 error: no method named `send` found for type `(ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>, ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>)` in the current scope
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:242     resource_thread.send(CoreResourceMsg::Cancel(res_id)).unwrap();
                                                                                         ^~~~
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:244:21: 244:25 error: no method named `send` found for type `(ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>, ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>)` in the current scope
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:244     resource_thread.send(CoreResourceMsg::Synchronize(sync_sender)).unwrap();
                                                                                         ^~~~
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:252:21: 252:25 error: no method named `send` found for type `(ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>, ipc_channel::ipc::IpcSender<net_traits::CoreResourceMsg>)` in the current scope
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:252     resource_thread.send(CoreResourceMsg::Exit(exit_sender)).unwrap();
                                                                                         ^~~~
error: aborting due to 7 previous errors
Build failed, waiting for other jobs to finish...
error: Could not compile `net_tests`.
To learn more, run the command again with --verbose.
The command "./mach test-unit" exited with 101.
```

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[components/constellation/constellation.rs, line 424 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJvExSbp8Sa-z2aUs9n:-KJvRP70GA_5njY2vFR9:1015926622) ([raw file](https://github.com/servo/servo/blob/5ec01d9dcafe81bfba3cd053015393baae5f3e37/components/constellation/constellation.rs#L424)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> This change doesn't appear to have much to do with private browsing, care to comment?
</details>
I can't figure out what you're commenting about from Reviewable. Maybe you observed a change that was part of a rebase? The self.shutting_down check is already present on master.

---

*[components/net/resource_thread.rs, line 209 \[r7\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJvFOTGtqmoN2EVFeim:-KJvQw9Xu0teA84tmu6k:1482958933) ([raw file](https://github.com/servo/servo/blob/e29b29943b05bda1d0f98a1e8670d4d380190e81/components/net/resource_thread.rs#L209)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Just inline auth_cache and cookie_jar below? That way the public and private cases are symmetric.
</details>
They're used in the if block that follows their declaration...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11544)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[components/constellation/constellation.rs, line 424 \[r6\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJvExSbp8Sa-z2aUs9n:-KJvWdtr1WA-hLxlU23C:-1827756365) ([raw file](https://github.com/servo/servo/blob/5ec01d9dcafe81bfba3cd053015393baae5f3e37/components/constellation/constellation.rs#L424)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> I can't figure out what you're commenting about from Reviewable. Maybe you observed a change that was part of a rebase? The self.shutting_down check is already present on master.
</details>
Ah, it's part of the rebase, cool. (In fact, I may have written that line...)

---

*[components/net/resource_thread.rs, line 209 \[r7\]](https://reviewable.io:443/reviews/servo/servo/11544#-KJvFOTGtqmoN2EVFeim:-KJvWvfXhDLHRzn0agYY:-1824982924) ([raw file](https://github.com/servo/servo/blob/e29b29943b05bda1d0f98a1e8670d4d380190e81/components/net/resource_thread.rs#L209)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> They're used in the if block that follows their declaration...
</details>
Oh, fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11544)*

**Comment by asajeffrey** [comment]
After you get test-unit to pass and squash, you can r=me.

**Pull request merged**
