### PR TITLE
Include screenshots in css test html log

### LINKED ISSUE #12401: The --log-html file doesn't have the correct Reftest_Screenshots
STR:
1. Run `./mach test-css --log-html test.log`
2. Open `test.log`

Expected: 
The `Reftest_Screenshots` link for failed tests will link to the correct screenshot (using base64 encoded img link)

Actual:
All of them are empty links

selection_011

### PR DESCRIPTION
**Pull request by shinglyu**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12401  (github issue number if applicable).

- [x] These changes do not require tests because mozlog has its own tests.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12403)

### CODE REVIEW

**Comment by shinglyu** [comment]
Before:
selection_011
After: 
selection_012

There are screenshots (green and white block) left to the logs. User can click the image to zoom in.

**Comment by Ms2ger** [comment]
This needs to go upstream.

**Comment by shinglyu** [comment]
By upstream do you mean wptrunner or mozlog?

**Comment by Ms2ger** [comment]
The code you're changing is in wptrunner, but if you think it would fit better in mozlog (it might be useful for Gecko's legacy reftests too), feel free to convince the maintainers of that :)

**Comment by shinglyu** [comment]
I'll refactor the patch and move the change to mozlog instead. Modifying wptrunner to fit Gecko's log format sounds wierd.

**Comment by shinglyu** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1287019

**Comment by shinglyu** [comment]
Closed by #12510

**Pull request closed without merging**
