### PR TITLE
 stylo: Use AtomicRefCell for PerDocumentStyleData

### PR DESCRIPTION
**Pull request by bholley**
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1309090

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13688)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo retry

 - #13535

**Comment by bholley** [comment]
@Manishearth thanks for doing #13620! Already paid off in this PR, where I forgot to update the signatures of the Servo_* functions in glue.rs. Testing and infra FTW!

**Comment by Manishearth** [comment]
😄

**Pull request merged**
