### PR TITLE
Remove code duplication from IdentityHub

### PR DESCRIPTION
**Pull request by imiklos**
Outsourced the backend selection to a function.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

cc @kvark @jdm @zakorgy

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Nice improvement!

**Comment by CYBAI** [comment]
@bors-servo retry

- #24726 
- #25513

**Comment by CYBAI** [comment]
@bors-servo retry

- #24726

**Comment by CYBAI** [comment]
@bors-servo retry

- #24726

**Pull request merged**
