### PR TITLE
Upgrade gstreamer to 1.15.1 on appveyor

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22949)

### CODE REVIEW

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/fd07be1cefa7c96ec15bcb16e21dbb0558627d3d/python/servo/build_commands.py#L608-L618 seems to be broken now.

**Comment by ferjm** [comment]
Yes, I need a Windows machine to see what's wrong there.

**Comment by jdm** [comment]
I'm seeing if I can replicate the issue on servo-windows3 right now.

**Comment by UK992** [comment]
https://github.com/servo/servo/blob/fd07be1cefa7c96ec15bcb16e21dbb0558627d3d/python/servo/build_commands.py#L613

`libz.dll` was renamed to `libz-1.dll` in 1.15.1.

**Comment by ferjm** [comment]
I believe this is not required atm, so I'm closing this PR. FTR this was an attempt of addressing https://github.com/servo/servo/pull/22944#issuecomment-468009073

**Pull request closed without merging**
