### PR TITLE
Update Rust to 1.15.0-nightly (8f02c429a 2016-12-15).

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14481)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@Manishearth: I didn't manage to get the `visit::walk_expr` call to work; its signature is
```rust
pub fn walk_expr<'v, V: Visitor<'v>>(visitor: &mut V, expression: &'v Expr) {
```
but the lifetimes of the `cx` and `body` arguments are not related. Could you take a look>

**Comment by Manishearth** [comment]
I believe you need https://github.com/rust-lang/rust/pull/38191 for this to work. Clippy did at least.

**Comment by nox** [comment]
@bors-servo try

It's still broken, let's see what CI says though.

**Comment by nox** [comment]
Wait how did that work? I couldn't build on my local machine because of https://github.com/rust-lang/rust/issues/38430

**Pull request merged**
