### PR TITLE
gfx: Use proper freetype bindings.

### PR DESCRIPTION
**Pull request by emilio**
Needs https://github.com/servo/rust-freetype/pull/48, and https://github.com/servo/webrender/pull/716

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15018)

### CODE REVIEW

**Comment by nox** [comment]
This still uses freetype 0.1.3 in tree, no?

**Comment by emilio** [comment]
Yes, missing a WR update and a rust-azure update too

**Comment by emilio** [comment]
This is now ready for review. r? @nox or @jdm

**Pull request merged**
