### PR TITLE
Update to unicode-bidi 0.2.1

### PR DESCRIPTION
**Pull request by mbrubeck**
Also includes some missing changes from #6416.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6998)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Just a moment, this is missing a change...

**Comment by jdm** [comment]
```
/css21_dev/html4/first-letter-dynamic-002.htm
---------------------------------------------
PASS expected FAIL [Parent]
```

**Pull request merged**
