### PR TITLE
Ensure crate are alphabetically sorted

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
#7441

cc @nox

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8692)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/tidy.py, line 221 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8692#-K47HU35PijGN06dWAdF:-K47HU35PijGN06dWAdG:-354485884) ([raw file](https://github.com/servo/servo/blob/2d5a208200941032f54f7be4310e3a424353935d/python/tidy.py#L221)):*
Um, `check_rust` already checks for lines that begin with `mod` and `use`. Why don't we include this as a part of it? That way, we won't be needing another travel through all the files :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8692)*

**Comment by GuillaumeGomez** [comment]
@Wafflespeanut: Good point, I updated it this way.

**Comment by jdm** [comment]
@Wafflespeanut Would you like to do a full review for this?

**Comment by Wafflespeanut** [comment]
@jdm I'll be glad :)
@GuillaumeGomez Can you squash the commits together? Because, the latest commit seems to modify the previous one. Squash it and we'll land it :)

---

Reviewed 1 of 1 files at r1, 22 of 22 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8692#-:-K4BOlrVwf9DsErPlpZy:436286407)*

**Comment by Wafflespeanut** [comment]
There are some nits (which I might've overlooked earlier), Sorry...

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[python/tidy.py, line 227 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8692#-K4CwZNZoPopMksH2Og5:-K4CwZNZoPopMksH2Og6:1078667143) ([raw file](https://github.com/servo/servo/blob/e0169d9c7b37b8c35e7674b14bed47930dd97de2/python/tidy.py#L227)):*
Shall we have this, like

``` python
uses, mods = [], []
prev_crate = {}
```

We're having quite a lot of newlines.

---

*[python/tidy.py, line 233 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8692#-K4CxAvdj-UqYfh9m-Px:-K4CxAvdj-UqYfh9m-Py:452777422) ([raw file](https://github.com/servo/servo/blob/e0169d9c7b37b8c35e7674b14bed47930dd97de2/python/tidy.py#L233)):*
Shall we have a reasonable name like `crate_name`?

---

*[python/tidy.py, line 245 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8692#-K4CwQdde3rsidtsR4b8:-K4CwQdeIpZg8vwIR2X-:595274381) ([raw file](https://github.com/servo/servo/blob/e0169d9c7b37b8c35e7674b14bed47930dd97de2/python/tidy.py#L245)):*
Shall we move all those lines below this line, so that we don't need `cut_line`, and make use of `line` itself?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8692#-:-K4CxJAS421KsRqeORWg:1025497910)*

**Comment by Wafflespeanut** [comment]
@bors-servo r+

Thanks! :)

**Comment by Wafflespeanut** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8692)*

**Pull request merged**
