### PR TITLE
Generalise RootedVec::<JS<T>>::r as [JS<T>]::r

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11171)

### CODE REVIEW

**Comment by nox** [comment]
This supersedes #11162.

**Comment by Ms2ger** [comment]
Fine by me, r? @jdm for the extra `use`s.

**Comment by KiChjang** [comment]
Fails tidy:
```
Checking files for tidiness...

./components/script/dom/bindings/callback.rs:9: use statement is not in alphabetical order

	expected: dom::bindings::js::RootedReference

	found: dom::bindings::global::global_root_from_object
```

**Comment by jdm** [comment]
I'm not convinced that this is a strict improvement. Conceptually the implementation is nicer to read, but the extra import required for every file that needs to interact with a GlobalRoot is a papercut that outweighs that.

**Comment by notriddle** [comment]
So, what's the status on this one? Is it just a change we don't want to make at all? Or should it be rebased and fixed up in some way? @jdm?

**Comment by jdm** [comment]
Previous discussions have not convinced me that this change is worth merging.

**Pull request closed without merging**
