### PR TITLE
Add onkey* global event handler attributes

### PR DESCRIPTION
**Pull request by jgraham**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6451)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/macros.rs, line 279 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6451#-JsZwpvJcQLP8nwUwEBG)** ([raw file](https://github.com/servo/servo/blob/7f63309602c3167f0e9e9f393ddad0746abaa728/components/script/dom/macros.rs#L279)):</sup>
keyup. Sounds like we need some testing :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6451)

**Comment by Ms2ger** [comment]
+C-needs-test  -S-awaiting-review 

Wanna write a test?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6451)

**Comment by metajack** [comment]
@jgraham ping? this is getting quite old.

**Pull request merged**
