### PR TITLE
Adds tidy.py check for multiple crate occurrence

### LINKED ISSUE #8691: tidy.py check for cargo versions doesn't report multiple byteorder packages
Noticed in review for #8446.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #8691

cc @jdm 
cc @Wafflespeanut

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8809)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I wrote https://github.com/servo/servo/pull/8824 as an alternative.

**Comment by Wafflespeanut** [comment]
This is okay, but I think we should go for @Ms2ger's alternative :)

**Comment by GuillaumeGomez** [comment]
I guess. Poor me. :'(

**Comment by jdm** [comment]
Sorry @GuillaumeGomez! Let us know if you'd like suggestions for other pieces to work on!

**Pull request closed without merging**
