### PR TITLE
Update test expectations for update-rendering

### LINKED ISSUE #33028: Intermittent PASS in `/html/webappapis/update-rendering/child-document-raf-order.html`
```
OK /html/webappapis/update-rendering/child-document-raf-order.html

    PASS [expected FAIL] subtest: Ordering of steps in "Update the Rendering" - child document requestAnimationFrame order
```

### PR DESCRIPTION
**Pull request by gterzian**
Update test expectations for update-rendering; this should have been done as part of https://github.com/servo/servo/pull/33480

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
I wonder how this change made it past the merge queue... Perhaps it is still intermittent?

**Comment by gterzian** [comment]
at https://github.com/servo/servo/pull/33830 it showed up as a flaky PASS
at https://github.com/servo/servo/pull/33830 it showed up as a stable PASS

**Comment by gterzian** [comment]
> I wonder how this change made it past the merge queue... Perhaps it is still intermittent?

@mrobinson @jdm I would say we merge this and find out. My best guess for remaining intermittency at this point is https://github.com/servo/servo/issues/31973

Note that the failed results so far where PASS, but for one run it was marked as "flaky".

**Comment by mrobinson** [comment]
> Note that the failed results so far where PASS, but for one run it was marked as "flaky".

Maybe we should update the result, but keep the bug open. Keeping the bug open will allow more easily tracking when it fails. If a couple months pass and you notice that the bug hasn't been tagged by the CI then it's likely not flaky any longer.

**Comment by gterzian** [comment]
Thanks for the info, this should now not close the issue anymore when merged.

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
@gterzian Great! I think the commits just needs to be signed now.

**Pull request merged**
