### PR TITLE
Add support for WebGL2 getFramebufferAttachmentParameter

### PR DESCRIPTION
**Pull request by mmatyas**
Implements the WebGL2 variant of `getFramebufferAttachmentParameter` and the related parameter checks.

See: https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.7.4

Depends on #25784

cc @jdm @zakorgy

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
This can merge after a rebase.

**Comment by mmatyas** [comment]
Rebased and regenerated the tests.

**Comment by jdm** [comment]
@bors-servo retry
* #25513

**Pull request merged**
