### PR TITLE
Rebase of #12905: Fix #12193 Servo displays upper level Thai character in wrong place.

### LINKED ISSUE #12193: Servo displays upper level Thai character in wrong place.
On Ubuntu 16.04, Servo nightly, that I downloaded on 2016-07-03, displays upper level Thai characters in the incorrect place. Moreover it choose incorrect glyph too. 

Update: Servo on Mac OS X 10.11.5. has this issue too.

The text is "ยินดี". It is supposed to display    ี  on top of ด but it displays     ิ   on top of น, which is incorrect glyph and incorrect placement. 

servo_thai_bug

An URL for the test case is http://file.veerkesto.net/servo_test/simple-thai.html

### PR DESCRIPTION
**Pull request by pcwalton**
Taking over #12905

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13442)

### CODE REVIEW

**Comment by veer66** [comment]
I suppose that this patch won't pass word breaking test until #12939 is fixed.

**Comment by jdm** [comment]
Yes, but you could duplicate some of the relevant tests and make them use `getBoundingClientRect().width` instead. That's what the author of #13414 did.

**Comment by veer66** [comment]
I will try to fix css-text-3_dev/html/word-break-break-all-007.htm like @jdm suggested.

**Comment by veer66** [comment]
I just added new commit for fixing test. 

https://github.com/veer66/servo/commit/01094c5932f4c08506602c10baa238df3a0c7fbb

**Comment by veer66** [comment]
So I pull this https://github.com/servo/servo/pull/13506.

**Comment by jdm** [comment]
More work happening in #13506.

**Pull request closed without merging**
