### PR TITLE
build(deps): bump bitflags from 1.3.2 to 2.3.1

### PR DESCRIPTION
**Pull request by mrobinson**
Bumps [bitflags](https://github.com/bitflags/bitflags) from 1.3.2 to 2.3.1.
 - [Release notes](https://github.com/bitflags/bitflags/releases)
 - [Changelog](https://github.com/bitflags/bitflags/blob/main/CHANGELOG.md)
 - [Commits](https://github.com/bitflags/bitflags/compare/1.3.2...2.3.1)

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they do not change behavior.

### CODE REVIEW

**Review by mukilan — APPROVED** [review]
I've fixed the tidy issue that failed the build.

**Comment by mrobinson** [comment]
Wow, @mukilan thanks for the great detective work! I'll see what I can do to fix this issue.

**Comment by mrobinson** [comment]
I've just moved the `TextAlign` data structure out of the flags. This might be a bit less efficient memory-wise, but I think this is okay considering that we are dealing with the legacy layout here.

**Pull request merged**
