### PR TITLE
Bump winit to 0.28.1

### LINKED ISSUE #27740: [linux][2020-11-05] startup crash (wayland related)
**Servo Developer Preview Download**
```
./servo                                                                                     [23:15:00]
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
Redirecting call to abort() to mozalloc_abort

Stack trace for thread "main"
   0: servo::backtrace::print
   1: servo::install_crash_handler::handler
   2: <unknown>
   3: _ZL22AnnotateMozCrashReasonPKc
             at /repo/target/release/build/mozjs_sys-e27741865a3660c6/out/build/dist/include/mozilla/Assertions.h:42:19
      mozalloc_abort
             at /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/memory/mozalloc/mozalloc_abort.cpp:33:3
   4: abort
             at /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a40b829/mozjs/memory/mozalloc/mozalloc_abort.cpp:82:3
   5: wayland_client::imp::proxy::proxy_dispatcher
   6: <unknown>
   7: <unknown>
   8: wl_display_dispatch_queue_pending
   9: wl_display_roundtrip_queue
  10: wayland_client::event_queue::EventQueue::sync_roundtrip
  11: winit::platform::platform::EventsLoop::new_wayland
  12: winit::platform::platform::EventsLoop::new
  13: winit::EventsLoop::new
  14: servo::events_loop::EventsLoop::new
  15: servo::app::App::run
  16: servo::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/rt.rs:52:13
      std::panicking::try::do_call
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panicking.rs:348:40
      std::panicking::try
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panicking.rs:325:15
      std::panic::catch_unwind
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/panic.rs:394:14
      std::rt::lang_start_internal
             at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f/src/libstd/rt.rs:51:25
  19: main
  20: __libc_start_main
  21: _start
```

### PR DESCRIPTION
**Pull request by atomgardner**
This fixes the following wayland-client error:

	Attempted to dispatch unknown opcode 0 for wl_shm, aborting.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #27740 (GitHub issue number if applicable)

- [x] There are tests for these changes OR
- [X] These changes do not require tests because only dependencies are updated.

### CODE REVIEW

**Comment by jdm** [comment]
Nice, this looks like this avoids the fontconfig issues from 0.27 in https://github.com/servo/servo/pull/29168. Want to make a pull request to surfman?

**Comment by jdm** [comment]
Can you cherry-pick the changes from https://github.com/Snowiiii/servo/pull/1/files to fix the mac build?

**Comment by atomgardner** [comment]
@jdm, let's see whether I've butchered the cherry pick. Your patch was against winit 0.27.x, I think, and I have no access to a `macos` build machine.

Also, I *sometimes* see local fontsan failures, possibly due to Cmake attempting to install libots without permission:

```
error: failed to run custom build command for `fontsan v0.4.0 (https://github.com/servo/fontsan#29e879c8)`

Caused by:
  process didn't exit successfully: `/home/servo/servo/target/debug/build/fontsan-a2d5f0faf0ca3c10/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/servo/servo/target/debug/build/fontsan-e43d45948d7b1ef4/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/servo/.cargo/git/checkouts/fontsan-75864180be477bc9/29e879c/src" "-DCMAKE_INSTALL_PREFIX=/home/servo/servo/target/debug/build/fontsan-e43d45948d7b1ef4/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=x86_64-unknown-linux-gnu" "-DCMAKE_C_COMPILER=/usr/bin/clang" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=x86_64-unknown-linux-gnu" "-DCMAKE_CXX_COMPILER=/usr/bin/clang++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC --target=x86_64-unknown-linux-gnu" "-DCMAKE_ASM_COMPILER=/usr/bin/clang" "-DCMAKE_BUILD_TYPE=Debug"
  -- Configuring done
  -- The C compiler identification is Clang 15.0.7
  -- The CXX compiler identification is Clang 15.0.7
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /home/servo/servo/target/debug/build/fontsan-e43d45948d7b1ef4/out/build
  running: cd "/home/servo/servo/target/debug/build/fontsan-e43d45948d7b1ef4/out/build" && MAKEFLAGS="-j --jobserver-fds=22,23 --jobserver-auth=22,23" "cmake" "--build" "." "--target" "install" "--config" "Debug"
  [  1%] Building CXX object CMakeFiles/ots.dir/ots/src/cff.cc.o
  [  3%] Building CXX object CMakeFiles/ots.dir/ots/src/cff_type2_charstring.cc.o
  [  5%] Building CXX object CMakeFiles/ots.dir/ots/src/cmap.cc.o
  [  7%] Building CXX object CMakeFiles/ots.dir/ots/src/cvt.cc.o
  [  8%] Building CXX object CMakeFiles/ots.dir/ots/src/feat.cc.o
  [ 10%] Building CXX object CMakeFiles/ots.dir/ots/src/fpgm.cc.o
  [ 12%] Building CXX object CMakeFiles/ots.dir/ots/src/gasp.cc.o
  [ 14%] Building CXX object CMakeFiles/ots.dir/ots/src/gdef.cc.o
  [ 16%] Building CXX object CMakeFiles/ots.dir/ots/src/glat.cc.o
  [ 17%] Building CXX object CMakeFiles/ots.dir/ots/src/gloc.cc.o
  [ 19%] Building CXX object CMakeFiles/ots.dir/ots/src/glyf.cc.o
  [ 21%] Building CXX object CMakeFiles/ots.dir/ots/src/gpos.cc.o
  [ 23%] Building CXX object CMakeFiles/ots.dir/ots/src/gsub.cc.o
  [ 25%] Building CXX object CMakeFiles/ots.dir/ots/src/hdmx.cc.o
  [ 26%] Building CXX object CMakeFiles/ots.dir/ots/src/head.cc.o
  [ 28%] Building CXX object CMakeFiles/ots.dir/ots/src/hhea.cc.o
  [ 30%] Building CXX object CMakeFiles/ots.dir/ots/src/hmtx.cc.o
  [ 32%] Building CXX object CMakeFiles/ots.dir/ots/src/kern.cc.o
  [ 33%] Building CXX object CMakeFiles/ots.dir/ots/src/layout.cc.o
  [ 35%] Building CXX object CMakeFiles/ots.dir/ots/src/loca.cc.o
  [ 37%] Building CXX object CMakeFiles/ots.dir/ots/src/ltsh.cc.o
  [ 39%] Building CXX object CMakeFiles/ots.dir/ots/src/math.cc.o
  [ 41%] Building CXX object CMakeFiles/ots.dir/ots/src/maxp.cc.o
  [ 42%] Building CXX object CMakeFiles/ots.dir/ots/src/metrics.cc.o
  [ 44%] Building CXX object CMakeFiles/ots.dir/ots/src/name.cc.o
  [ 46%] Building CXX object CMakeFiles/ots.dir/ots/src/os2.cc.o
  [ 48%] Building CXX object CMakeFiles/ots.dir/ots/src/ots.cc.o
  [ 50%] Building CXX object CMakeFiles/ots.dir/ots/src/post.cc.o
  [ 51%] Building CXX object CMakeFiles/ots.dir/ots/src/prep.cc.o
  [ 53%] Building CXX object CMakeFiles/ots.dir/ots/src/sile.cc.o
  [ 55%] Building CXX object CMakeFiles/ots.dir/ots/src/silf.cc.o
  [ 57%] Building CXX object CMakeFiles/ots.dir/ots/src/sill.cc.o
  [ 58%] Building CXX object CMakeFiles/ots.dir/ots/src/vdmx.cc.o
  [ 60%] Building CXX object CMakeFiles/ots.dir/ots/src/vhea.cc.o
  [ 62%] Building CXX object CMakeFiles/ots.dir/ots/src/vmtx.cc.o
  [ 64%] Building CXX object CMakeFiles/ots.dir/ots/src/vorg.cc.o
  [ 66%] Linking CXX static library libots.a
  [ 66%] Built target ots
  [ 67%] Building C object CMakeFiles/brotli.dir/ots/third_party/brotli/c/common/dictionary.c.o
  [ 69%] Building C object CMakeFiles/brotli.dir/ots/third_party/brotli/c/dec/bit_reader.c.o
  [ 71%] Building C object CMakeFiles/brotli.dir/ots/third_party/brotli/c/dec/decode.c.o
  [ 73%] Building C object CMakeFiles/brotli.dir/ots/third_party/brotli/c/dec/huffman.c.o
  [ 75%] Building C object CMakeFiles/brotli.dir/ots/third_party/brotli/c/dec/state.c.o
  [ 76%] Linking C static library libbrotli.a
  [ 76%] Built target brotli
  [ 78%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/font.cc.o
  [ 80%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/glyph.cc.o
  [ 82%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/normalize.cc.o
  [ 83%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/table_tags.cc.o
  [ 85%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/transform.cc.o
  [ 87%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/variable_length.cc.o
  [ 89%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/woff2_common.cc.o
  [ 91%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/woff2_dec.cc.o
  [ 92%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/woff2_enc.cc.o
  [ 94%] Building CXX object CMakeFiles/woff2.dir/ots/third_party/woff2/src/woff2_out.cc.o
  [ 96%] Linking CXX static library libwoff2.a
  [ 96%] Built target woff2
  [ 98%] Building CXX object CMakeFiles/ots_glue.dir/ots_glue.cc.o
  [100%] Linking CXX static library libots_glue.a
  [100%] Built target ots_glue
  Install the project...
  -- Install configuration: ""
  -- Installing: /usr/local/lib/libots.a

  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  You have changed variables that require your cache to be deleted.
  Configure will be re-run and you may have to reset some variables.
  The following variables have changed:
  CMAKE_C_COMPILER= /usr/bin/clang
  CMAKE_CXX_COMPILER= /usr/bin/clang++

  CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
  CMake Error at cmake_install.cmake:46 (file):
    file INSTALL cannot copy file
    "/home/servo/servo/target/debug/build/fontsan-e43d45948d7b1ef4/out/build/libots.a"
    to "/usr/local/lib/libots.a": Permission denied.


  make: *** [Makefile:100: install] Error 1
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2

  build script failed, must exit now', /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:1104:5
```

**Comment by atomgardner** [comment]
Updated the surfman git entry.

**Comment by mukilan** [comment]
> Updated the surfman git entry.

I think we can now publish surfman 0.6.0 and consume it here without using `patches` in Cargo.toml. 

@jdm wdyt? I can update the surfman/examples and publish to crates.io if this sounds good to you.

**Comment by mukilan** [comment]
@atomgardner:  surfman 0.6.0 with winit 0.28.1 has been published to crates.io, but t complete this update the following also need to be done:

1) Update surfman version in servo/surfman-chain and servo/webxr (completed)
2) Update all references to surfman in servo to the published crate 0.6.0 - this PR updates Cargo.toml in ports/winit but we also need to update Cargo.toml  for: 
ports/gstplugin
ports/libsimpleservo/capi
ports/libsimpleservo/api
components/servo
components/compositing
components/webrender_surfman
components/canvas
3) The lockfile needs to be regenerated with `cargo update --package surfman`

Please let me know if you want to handle the remaining steps. If not, I can update this PR.

**Comment by atomgardner** [comment]
@mukilan, I'm happy to handle it, but I'll need some guidance.

> Update all references to surfman in servo to the published crate 0.6.0 

Done.

> The lockfile needs to be regenerated with `cargo update --package surfman`

This leads to 18 new duplicate package warnings, since there'd still be a `surfman v0.5` dependency though `surfman-chains` and `webxr`. I've bumped those two crates, and it _seems_ OK; how does it look it you?

I think it's safe to drop the relevant commits if you'd rather bump `surfman-chains` and `webxr` in a separate PR.

**Comment by mukilan** [comment]
@atomgardner  awesome! thanks for changes. 

>  I've bumped those two crates, and it seems OK; how does it look it you?

Yep, those two crates would have to be bumped as well. I forgot to mention in my comment. Thanks for handling those as well!

**Comment by jdm** [comment]
@bors-servo r+
Woohoo!

**Comment by atomgardner** [comment]
Nice! +cc @snowiiii

**Comment by Snowiiii** [comment]
> Nice! +cc @Snowiiii

What is +cc ?

**Pull request merged**
