### PR TITLE
Cleanup ports/servo to only rely on libservo

### PR DESCRIPTION
**Pull request by fabricedesre**
When using `ports/servo` as a starting point for an embedding, it's easier if it only relies on the `libservo` crate and not directly on `components` ones. Since `libservo` reexports all the modules we need, it's a straightforward fix.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because There are no relevant tests, and no real code change.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20483)

### CODE REVIEW

**Review by paulrouget — CHANGES_REQUESTED** [review]
Can you remove the commented lines?

**Comment by fabricedesre** [comment]
> Can you remove the commented lines?

Yep, done.

**Comment by fabricedesre** [comment]
Arg, tidy was clean locally... what did I miss :disappointed:

**Review by paulrouget — APPROVED** [review]

**Comment by CYBAI** [comment]
```
bash ./etc/ci/lockfile_changed.sh
 in dir /home/servo/buildbot/slave/android/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['bash', './etc/ci/lockfile_changed.sh']
 environment:
  ANDROID_NDK=/home/servo/android/ndk/current/
  ANDROID_SDK=/home/servo/android/sdk/current/
  BUILD_MACHINE=<buildbot.process.properties.Property instance at 0x7f28989cbd88>
  CARGO_INCREMENTAL=0
  CCACHE=/usr/bin/ccache
  DISPLAY=:0
  HOME=/home/servo
  JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  PATH=/home/servo/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/home/servo/android/sdk/current/platform-tools
  PWD=/home/servo/buildbot/slave/android/build
  RUSTFLAGS=-Dwarnings
  RUST_BACKTRACE=1
  SCCACHE_IDLE_TIMEOUT=1200
  SERVO_CACHE_DIR=/home/servo/.servo
  SHELL=/bin/bash
  TERM=linux
  UPSTART_INSTANCE=
  UPSTART_JOB=buildbot-slave
 using PTY: False
diff --git a/Cargo.lock b/Cargo.lock
index e8726c0..25eb879 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -2717,25 +2717,18 @@ dependencies = [
  "android_injected_glue 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)",
  "backtrace 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
  "bitflags 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
- "compositing 0.0.1",
  "euclid 0.17.2 (registry+https://github.com/rust-lang/crates.io-index)",
  "gdi32-sys 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
  "gleam 0.4.29 (registry+https://github.com/rust-lang/crates.io-index)",
  "glutin 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)",
  "libservo 0.0.1",
  "log 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)",
- "msg 0.0.1",
  "osmesa-src 17.3.1-devel (git+https://github.com/servo/osmesa-src)",
  "osmesa-sys 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
- "script_traits 0.0.1",
  "servo-egl 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
- "servo_config 0.0.1",
- "servo_geometry 0.0.1",
  "sig 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
- "style_traits 0.0.1",
  "tinyfiledialogs 3.3.5 (registry+https://github.com/rust-lang/crates.io-index)",
  "user32-sys 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
- "webrender_api 0.57.0 (git+https://github.com/servo/webrender)",
  "winapi 0.2.8 (registry+https://github.com/rust-lang/crates.io-index)",
  "winit 0.11.2 (registry+https://github.com/rust-lang/crates.io-index)",
  "winres 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
program finished with exit code 1
```

**Comment by CYBAI** [comment]
```
{"status": "NOTRUN", "group": "default", "message": null, "stack": null, "subtest": "Overall test", "test": "/_mozilla/webgl/conformance-1.0.3/conformance/ogles/GL/atan/atan_001_to_008.html", "line": 136121, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/_mozilla/webgl/conformance-1.0.3/conformance/ogles/GL/atan/atan_001_to_008.html", "line": 136134, "action": "test_result", "expected": "OK"}
```

**Comment by jdm** [comment]
@bors-servo retry
* #20490

**Pull request merged**
