### PR TITLE
hacking quickstart documentation

### PR DESCRIPTION
**Pull request by paulrouget**
Please someone review this (content and english).

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8165)

### CODE REVIEW

**Comment by Manishearth** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[HACKING_QUICKSTART.md, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1J9weleoVNOnT8zFBg)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L7)):</sup>
Things should be properly capitalized (throughout the post)

First character in headings, and "Servo"


---

<sup>**[HACKING_QUICKSTART.md, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JA1pHElPSGYYy7c-p)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L17)):</sup>
Note that -r is slower, too

Also, spelling of personally


---

<sup>**[HACKING_QUICKSTART.md, line 100 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JAwz-_IuW6IIVbTkK)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L100)):</sup>
in one of its *dependencies


---

<sup>**[HACKING_QUICKSTART.md, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JB7003VydXcRAhHTs)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L114)):</sup>
This won't work.

You need to instead edit `components/servo/.cargo/config`, and add full paths to the paths array


---

<sup>**[HACKING_QUICKSTART.md, line 185 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JBpzXU7iTn6nIBAl_)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L185)):</sup>
`image lookup -r -n <name>` to search for a function full name/regex is also helpful


---

<sup>**[HACKING_QUICKSTART.md, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JB_JCIrtW1prvKyrc)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L192)):</sup>
link to a gdb one too, the default debugger on linux is gdb

Most of our contributors are on Linux, too

The corresponding commands are the same, though the image lookup command is replaced by  `info functions <name>`

Another useful command is `frame n` (works on both debuggers, IIRC), which lets us choose the stack frame from the number in the bt. This, combined with `print varname` is quite useful.


---

<sup>**[HACKING_QUICKSTART.md, line 221 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JDHmJSwsRQshO8djY)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L221)):</sup>
In some cases extensive tests for the feature may already exist under `tests/wpt`.


 - Make a release build
 - run `./mach test-wpt --log-raw=/path/to/some/logfile`
 - run update-wpt on it (https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations)

This may create a new commit with changes to expectation ini files. If there are lots of changes, it's likely that your feature had tests in wpt already.

Include this commit in your pull request.


---

<sup>**[HACKING_QUICKSTART.md, line 223 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JE3PWnJEb5dWIhV9Q)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L223)):</sup>
Mention: To run the test, `./mach test-wpt tests/wpt/.....` is enough


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8165)

**Comment by paulrouget** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[HACKING_QUICKSTART.md, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JA1pHElPSGYYy7c-p)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L17)):</sup>
-r is slower than what?


---

<sup>**[HACKING_QUICKSTART.md, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JB7003VydXcRAhHTs)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L114)):</sup>
That works for me. And I don't need full paths.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8165)

**Comment by Manishearth** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[HACKING_QUICKSTART.md, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JA1pHElPSGYYy7c-p)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L17)):</sup>
Sorry, I mean that's it's slower to build.


---

<sup>**[HACKING_QUICKSTART.md, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JB7003VydXcRAhHTs)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L114)):</sup>
It only works because your Servo folder is within `~/my-projects` :smile: 

Yeah, you don't need full paths if it's nearby, relative paths from the folder containing .cargo work too


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8165)

**Comment by paulrouget** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[HACKING_QUICKSTART.md, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JA1pHElPSGYYy7c-p)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L17)):</sup>
Done.


---

<sup>**[HACKING_QUICKSTART.md, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JB7003VydXcRAhHTs)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L114)):</sup>
I'd like to keep it simple, and I think it's a ok project layout. I will link to this documentation for more details: http://doc.crates.io/guide.html#overriding-dependencies


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8165)

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[HACKING_QUICKSTART.md, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JB7003VydXcRAhHTs)** ([raw file](https://github.com/servo/servo/blob/136a1845e823f26d3876f7629667284fdbcd9ed8/HACKING_QUICKSTART.md#L114)):</sup>
Yeah, my point is that this assumes things about the layout which others may not have. Editing the in-tree cargoconfig is something that anyone can do


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8165)

**Comment by Manishearth** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[HACKING_QUICKSTART.md, line 244 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JgaaoftHfT-BMqtBn)** ([raw file](https://github.com/servo/servo/blob/48d65b3500f7185eb46f1af43bf2eccd18d5e49f/HACKING_QUICKSTART.md#L244)):</sup>
Sorry, I forgot to mention that we need a -r here


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8165)

**Comment by paulrouget** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[HACKING_QUICKSTART.md, line 244 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8165#-K1JgaaoftHfT-BMqtBn)** ([raw file](https://github.com/servo/servo/blob/48d65b3500f7185eb46f1af43bf2eccd18d5e49f/HACKING_QUICKSTART.md#L244)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8165)

**Comment by Manishearth** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8165)

**Pull request merged**
