### PR TITLE
Use WebRender to compute text index on click events

### PR DESCRIPTION
**Pull request by mrobinson**
This is the second half of switching over to WebRender for hit testing.
Now that WebRender gives us the location of the hit tested point in the
display item, we can use that to calculate text index.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they shouldn't change behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18933)

### CODE REVIEW

**Comment by mrobinson** [comment]
```
command timed out: 1200 seconds without output running ['env', 'PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig', './mach', 'build', '--release'], attempting to kill
```
The build timed out when compiling layout, so I think this is an infrastructure issue.

@bors-servo retry

**Comment by mrobinson** [comment]
I added another commit to this PR that removes a now unused iterator class.

**Review by jdm — APPROVED** [review]
I've looked at all of the code changes; I don't think this needs anybody else to review it.

**Comment by jdm** [comment]
@bors-servo: r+
I'm not delighted about how we smuggle around this extra data in certain instances of mouse events, but it's not all that different from what previously existed.

**Pull request merged**
