### PR TITLE
mach: run linux unit tests for 'full' try jobs

### PR DESCRIPTION
**Pull request by mukilan**
Windows and Mac have unit tests enabled when triggered via the 'full' alias but
they are disabled on Linux, which is confusing.

Signed-off-by: Mukilan Thiyagarajan <mukilan@igalia.com>

---

- [x] `./mach build -d` does not report any errors.
- [x] `./mach test-tidy` does not report any errors.
- [x] There are tests for the changes to the try parser logic.

### CODE REVIEW

**Comment by mukilan** [comment]
Example [run](https://github.com/servo/servo/actions/runs/11886582157) where the unit tests fail on Windows and MacOS but not on Linux.

**Comment by sagudev** [comment]
Actually I already done this as part of https://github.com/servo/servo/pull/34146

**Review by sagudev — COMMENTED** [review]
Let's add naming changes from https://github.com/servo/servo/pull/34146/files#diff-e5a800a414ff1b0236f85f7e56dbf6a8906198a9f49ef7436026b8188a7935d7 and land this without https://github.com/servo/servo/pull/34146

**Comment by mukilan** [comment]
> Actually I already done this as part of #34146

Ah, I didn't realize that :)

> Let's add naming changes from https://github.com/servo/servo/pull/34146/files#diff-e5a800a414ff1b0236f85f7e56dbf6a8906198a9f49ef7436026b8188a7935d7 and land this without #34146

Sure, sounds good.

**Review by sagudev — APPROVED** [review]

**Comment by mukilan** [comment]
Thanks for the review!

**Pull request merged**
