### PR TITLE
Revert 3/4 nightly rustc upgrade

### LINKED ISSUE #25908: 3/4 rustc upgrade broke RootedTraceableSet with RootedVec
On macOS 10.15, starting with ea8aed1ba927012d992a3d3c9880858e0282f5f9 I receive this output on any page:
```
oshmatthews@joshmatthews-fcmd6r servo-master % ./mach run
internal error: entered unreachable code (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/dom/bindings/trace.rs:896)
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
   1: <servo::backtrace::Print as core::fmt::Debug>::fmt
   2: core::fmt::write
   3: std::io::Write::write_fmt
   4: servo::backtrace::print
   5: servo::main::{{closure}}
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::begin_panic
   8: script::dom::bindings::trace::RootedTraceableSet::remove::{{closure}}
   9: std::thread::local::LocalKey<T>::try_with
  10: std::thread::local::LocalKey<T>::with
  11: script::dom::bindings::trace::RootedTraceableSet::remove
  12: <script::dom::bindings::trace::RootedVec<T> as core::ops::drop::Drop>::drop
  13: core::ptr::drop_in_place
  14: script::dom::event::Event::dispatch
  15: script::dom::eventtarget::EventTarget::dispatch_event
  16: script::dom::event::Event::fire
  17: script::dom::eventtarget::EventTarget::fire_event_with_params
  18: script::dom::eventtarget::EventTarget::fire_event
  19: script::dom::document::Document::set_ready_state
  20: script::script_thread::ScriptThread::load
  21: script::script_thread::ScriptThread::handle_page_headers_available::{{closure}}
  22: core::option::Option<T>::map
  23: script::script_thread::ScriptThread::handle_page_headers_available
  24: script::script_thread::ScriptThread::page_headers_available::{{closure}}
  25: std::thread::local::LocalKey<T>::try_with
  26: std::thread::local::LocalKey<T>::with
  27: script::script_thread::ScriptThread::page_headers_available
  28: <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response
  29: script::script_thread::ScriptThread::handle_fetch_metadata
  30: script::script_thread::ScriptThread::handle_msg_from_constellation
  31: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  32: script::script_thread::ScriptThread::profile_event
  33: script::script_thread::ScriptThread::handle_msgs
  34: script::script_thread::ScriptThread::start
  35: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
  36: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  37: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
  38: std::sys_common::backtrace::__rust_begin_short_backtrace
  39: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
  40: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  41: std::panicking::try::do_call
  42: __rust_maybe_catch_panic
  43: std::panicking::try
  44: std::panic::catch_unwind
  45: std::thread::Builder::spawn_unchecked::{{closure}}
  46: core::ops::function::FnOnce::call_once{{vtable.shim}}
  47: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  48: std::sys::unix::thread::Thread::new::thread_start
  49: _pthread_start
```
This comes from https://github.com/servo/servo/blob/ca25e18791163de5c6af1267d876c7f5bb705f61/components/script/dom/bindings/trace.rs#L896, because the fat pointer received from https://github.com/servo/servo/blob/ca25e18791163de5c6af1267d876c7f5bb705f61/components/script/dom/bindings/trace.rs#L1040 does not match the one added in https://github.com/servo/servo/blob/ca25e18791163de5c6af1267d876c7f5bb705f61/components/script/dom/bindings/trace.rs#L1029.

### PR DESCRIPTION
**Pull request by jdm**
Fixes #25908.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* #24622

**Pull request merged**
