### PR TITLE
Move some of the CSSStyleDeclaration logic to the style crate

### PR DESCRIPTION
**Pull request by SimonSapin**
… so that Stylo can re-use it.

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1295865

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because refator

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13640)

### CODE REVIEW

**Comment by emilio** [comment]
```
▶ CRASH [expected PASS] /_mozilla/css/removeproperty.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ DOMRefCell<T> already mutably borrowed: BorrowError (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at ../src/libcore/result.rs:799)
```

**Comment by mbrubeck** [comment]
@bors-servo r+

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13640#-:-KTky9CgSAI2GIIedboi:bkg9nno)*

**Comment by SimonSapin** [comment]
@bors-servo retry

* #13037

**Comment by SimonSapin** [comment]
@bors-servo retry

Infra?

```
  │ ERROR:servo: failed to create an OS RNG: Error { repr: Os { code: 24, message: "Too many open files" } }
```

**Comment by SimonSapin** [comment]
IRC
> 	<Manishearth>	SimonSapin: it's not infra, it's an IPC issue iirc

**Comment by jdm** [comment]
@bors-servo: retry
* #13535

**Comment by jdm** [comment]
@bors-servo: retry
* #13731

**Pull request merged**
