### PR TITLE
Enable experimental layout prefs for CSSWG reftests.

### PR DESCRIPTION
**Pull request by jdm**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7520)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Enabling everything everywhere seems heavy-handed. Could we enable just the relevant prefs to a given test suite?

**Comment by mbrubeck** [comment]
@bors-servo r+

(Just doing a try run so we can see what passes.)

**Comment by jdm** [comment]
@SimonSapin I feel like it could be more confusing if we enable some flags for some directories and come across tests in others which use features that we're used to being enabled.

**Comment by metajack** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7520)

**Comment by jdm** [comment]
The failure was #7437. However, I'm not going to retry yet because I noticed that these extra tests add 5 minutes to the mac build cycle.

Also there are these separate failures on mac:
```
/css-flexbox-1_dev/html/css-flexbox-column-reverse.htm
------------------------------------------------------
FAIL [Parent]
/css-text-3_dev/html/css3-text-line-break-jazh-159.htm
------------------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/css3-text-line-break-jazh-377.htm
------------------------------------------------------
PASS expected FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-embed-001.htm
------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-embed-002.htm
------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-embed-006.htm
------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-embed-011.htm
------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-glyph-mirroring-002.htm
----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-isolate-001.htm
--------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-isolate-002.htm
--------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-isolate-006.htm
--------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-isolate-005.htm
--------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-isolate-011.htm
--------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-isolate-override-001.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-isolate-override-002.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-isolate-override-005.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-isolate-override-011.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-normal-006.htm
-------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-override-001.htm
---------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-override-002.htm
---------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-override-011.htm
---------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-plaintext-001.htm
----------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-plaintext-005.htm
----------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-plaintext-006.htm
----------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-unset-006.htm
------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/block-override-002.htm
----------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/block-override-003.htm
----------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/block-override-isolate-002.htm
------------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/block-override-isolate-003.htm
------------------------------------------------------------
FAIL [Parent]
```
Sigh.

**Comment by metajack** [comment]
I'm ok with the extra test time. We'll figure out some way to deal with it.

**Comment by jdm** [comment]
Linux test-css:
```

/css-text-3_dev/html/css3-text-line-break-baspglwj-016.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-014.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-022.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-023.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-021.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-024.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-049.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-050.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-051.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-052.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-062.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-065.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-064.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-063.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-070.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-068.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-072.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-069.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-071.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-075.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-076.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-074.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-073.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-080.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-081.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-082.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-084.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-085.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-086.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-090.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-092.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-093.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-094.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-095.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-096.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-098.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-097.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-099.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-100.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-101.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-102.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-103.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-104.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-105.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-106.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-107.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-110.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-109.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-112.htm
----------------------------------------------------------
PASS expected FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-122.htm
----------------------------------------------------------
FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-126.htm
----------------------------------------------------------
FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-127.htm
----------------------------------------------------------
FAIL  
/css-text-3_dev/html/css3-text-line-break-baspglwj-128.htm
----------------------------------------------------------
FAIL  
/css-writing-modes-3_dev/html/orthogonal-parent-shrink-to-fit-001.htm
---------------------------------------------------------------------
PASS expected FAIL 2: Shrink-to-fit inline-block with a child of orthogonal inline
PASS expected FAIL 4: Shrink-to-fit inline-block with a child of orthogonal inline with borders
PASS expected FAIL 6: Shrink-to-fit inline-block with a child of orthogonal inline in inline-block
PASS expected FAIL 8: Shrink-to-fit inline-block with a child of orthogonal inline with borders in inline-block
PASS expected FAIL 10: Shrink-to-fit float with a child of orthogonal inline
PASS expected FAIL 12: Shrink-to-fit float with a child of orthogonal inline with borders
PASS expected FAIL 14: Shrink-to-fit float with a child of orthogonal inline in inline-block
PASS expected FAIL 16: Shrink-to-fit float with a child of orthogonal inline with borders in inline-block
PASS expected FAIL 18: Shrink-to-fit table-cell with a child of orthogonal inline
PASS expected FAIL 20: Shrink-to-fit table-cell with a child of orthogonal inline with borders
PASS expected FAIL 22: Shrink-to-fit table-cell with a child of orthogonal inline in inline-block
PASS expected FAIL 24: Shrink-to-fit table-cell with a child of orthogonal inline with borders in inline-block
/css-writing-modes-3_dev/html/text-combine-upright-parsing-digits-002.htm
-------------------------------------------------------------------------
FAIL Computed value for `text-combine-upright: digits calc(1 + 1)` is `digits 2`
FAIL Computed value for `text-combine-upright: digits calc(1 + 1 + 1)` is `digits 3`
FAIL Computed value for `text-combine-upright: digits calc(2 + 2)` is `digits 4`
FAIL Computed value for `text-combine-upright: digits calc(4 - 2)` is `digits 2`
FAIL Computed value for `text-combine-upright: digits calc(6 - 3)` is `digits 3`
FAIL Computed value for `text-combine-upright: digits calc(7 - 1 - 2)` is `digits 4`
FAIL Computed value for `text-combine-upright: digits calc(2 * 1)` is `digits 2`
FAIL Computed value for `text-combine-upright: digits calc(3 * 1)` is `digits 3`
FAIL Computed value for `text-combine-upright: digits calc(2 * 2 * 1)` is `digits 4`
FAIL Computed value for `text-combine-upright: digits calc(4 / 2)` is `digits 2`
FAIL Computed value for `text-combine-upright: digits calc(6 / 2)` is `digits 3`
FAIL Computed value for `text-combine-upright: digits calc(24 / 3 / 2)` is `digits 4`
/css-writing-modes-3_dev/html/text-orientation-parsing-sideways-right-001.htm
-----------------------------------------------------------------------------
FAIL text-orientation: sideways-right
/css-writing-modes-3_dev/html/text-combine-upright-parsing-valid-001.htm
------------------------------------------------------------------------
FAIL Computed value for `text-combine-upright: inherit` is `all` which is inherited from the parent element
FAIL Computed value for `text-combine-upright: unset` is `all` which is inherited from the parent element
/css-writing-modes-3_dev/html/text-orientation-parsing-001.htm
--------------------------------------------------------------
FAIL text-orientation initial value
FAIL text-orientation: upright
FAIL text-orientation should inherit
FAIL text-orientation: mixed
FAIL text-orientation: initial
FAIL text-orientation: inherit
FAIL text-orientation: foo
/css-writing-modes-3_dev/html/text-combine-upright-parsing-digits-001.htm
-------------------------------------------------------------------------
FAIL Computed value for `text-combine-upright: digits` is `digits 2`
FAIL Computed value for `text-combine-upright: digits 2` is `digits 2`
FAIL Computed value for `text-combine-upright: digits 3` is `digits 3`
FAIL Computed value for `text-combine-upright: digits 4` is `digits 4`
FAIL Computed value for `text-combine-upright: digits +2` is `digits 2`
FAIL Computed value for `text-combine-upright: digits+3` is `digits 3`
FAIL Computed value for `text-combine-upright: digits[TAB]4` is `digits 4`
FAIL Computed value for `text-combine-upright: digits[LF]2` is `digits 2`
FAIL Computed value for `text-combine-upright: digits [TAB]3` is `digits 3`
FAIL Computed value for `text-combine-upright: digits[TAB][LF]4` is `digits 4`
/css-writing-modes-3_dev/html/unicode-bidi-parsing-001.htm
----------------------------------------------------------
FAIL Initial value of unicode-bidi
FAIL unicode-bidi should not inherit
/css-writing-modes-3_dev/html/writing-mode-parsing-sideways-lr-001.htm
----------------------------------------------------------------------
FAIL writing-mode: sideways-lr
/css-writing-modes-3_dev/html/writing-mode-parsing-sideways-rl-001.htm
----------------------------------------------------------------------
FAIL writing-mode: sideways-rl
/css-writing-modes-3_dev/html/writing-mode-parsing-svg1-001.htm
---------------------------------------------------------------
FAIL writing-mode: tb
FAIL writing-mode: tb-rl
/css-text-3_dev/html/bidi-004.htm
---------------------------------
FAIL [Parent]
/css-text-3_dev/html/text-align-end-004.htm
-------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-end-008.htm
-------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-end-001.htm
-------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-end-005.htm
-------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-end-010.htm
-------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-end-015.htm
-------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-end-017.htm
-------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-justify-001.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-justify-004.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-justify-006.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-start-001.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-start-005.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-start-004.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-start-010.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-start-008.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-start-015.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/text-align-start-017.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css-text-3_dev/html/word-break-break-all-007.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-004.htm
------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/bidi-breaking-003.htm
---------------------------------------------------
FAIL expected TIMEOUT [Parent]
/css-writing-modes-3_dev/html/bidi-plaintext-010.htm
----------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/block-override-002.htm
----------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/block-override-003.htm
----------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/block-override-isolate-002.htm
------------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/block-override-isolate-003.htm
------------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/caption-side-vlr-003.htm
------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/caption-side-vrl-002.htm
------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/caption-side-vrl-004.htm
------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/caption-side-vlr-005.htm
------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/table-progression-vlr-001.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/table-progression-vlr-004.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/table-progression-vlr-002.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/table-progression-vrl-002.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/table-progression-vlr-003.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/table-progression-vrl-001.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/table-progression-vrl-003.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/table-progression-vrl-004.htm
-----------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-003.htm
--------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-004.htm
--------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-002.htm
--------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-006.htm
--------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-005.htm
--------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-008.htm
--------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-007.htm
--------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-009.htm
--------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-vrl-024.htm
------------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-vrl-022.htm
------------------------------------------------------------
FAIL [Parent]
/css-writing-modes-3_dev/html/vertical-alignment-vrl-026.htm
------------------------------------------------------------
FAIL [Parent]
```

**Comment by jdm** [comment]
I can't think of anything to do here but add platform-specific expectations.

**Comment by jdm** [comment]
I'm splitting this into more manageable PRs for specific test directories.

**Pull request closed without merging**
