### PR TITLE
Use external 'threadpool' crate, remove in-tree utility.

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9788)

### CODE REVIEW

**Comment by frewsxcv** [comment]
If anyone wants to see a direct comparison with the new `ThreadPool`: https://github.com/frewsxcv/rust-threadpool/blob/master/src/lib.rs

**Comment by frewsxcv** [comment]
```
11:12 AM <•Ms2ger> I'd be more in favour if the repo lived in the servo org and you bumped to 1.0
```

I don't like bumping for the sake of bumping so I'm going to pass.

**Comment by frewsxcv** [comment]
> I don't like bumping for the sake of bumping so I'm going to pass.

After thinking about it for a few days, I'm reversing my stance on this.

https://github.com/frewsxcv/rust-threadpool/pull/22

**Comment by Ms2ger** [comment]
Also interested in moving this into servo/? I don't like reducing bus factors more than necessary.

**Comment by frewsxcv** [comment]
> I don't like reducing bus factors more than necessary.

Would it be okay if I added Servo people as "Collaborators" to the repository?

**Comment by frewsxcv** [comment]
Merge conflicts addressed.

**Comment by frewsxcv** [comment]
I added Ms2ger, SimonSapin, nox, and Manishearth as collaborators to the repository. I also gave the 'publish' Servo org team publish access on crates.io.

**Comment by Ms2ger** [comment]
That's three times UTC+1/2, and Manish. I'd like to have Australia/US coverage too.

**Comment by frewsxcv** [comment]
Just added larsberg.

**Comment by jdm** [comment]
I'll r+ a rebase.

**Comment by frewsxcv** [comment]
> I'll r+ a rebase.

Done. :white_check_mark:

**Comment by jdm** [comment]
@bors-servo: r-
This is missing updates to the other lock files, unfortunately.

**Comment by frewsxcv** [comment]
> This is missing updates to the other lock files, unfortunately.

How do I update the other lockfiles?

**Comment by frewsxcv** [comment]
Updated other lockfiles.

**Comment by KiChjang** [comment]
@bors-servo retry
* The annoying git

**Pull request merged**
