### PR TITLE
Implement base machinery of Range

### PR DESCRIPTION
**Pull request by nox**
The actual boundary points are behind a Rc<_> value to let nodes be able to store weak references to them in the future.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5839)

### CODE REVIEW

**Comment by nox** [comment]
Note that I have no idea why the tests for Range methods that are not yet implemented must be marked as TIMEOUT, it was a CRASH as expected before I rebased today.

**Comment by nox** [comment]
My Rc<_> idea is silly compared to using the MutationObserver machinery, but that is not in Servo yet.

**Comment by Manishearth** [comment]
Reviewed files:
- components/script/dom/bindings/error.rs @ r3
- components/script/dom/document.rs @ r5
- components/script/dom/node.rs @ r1, r2
- components/script/dom/range.rs @ r5
- tests/wpt/metadata/dom/interfaces.html.ini @ r5
- tests/wpt/metadata/dom/nodes/MutationObserver-characterData.html.ini @ r5
- tests/wpt/metadata/dom/nodes/MutationObserver-childList.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-attributes.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-cloneContents.html.ini @ r4
- tests/wpt/metadata/dom/ranges/Range-cloneRange.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-collapse.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-commonAncestorContainer-2.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-commonAncestorContainer.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-compareBoundaryPoints.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-comparePoint-2.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-comparePoint.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-deleteContents.html.ini @ r4
- tests/wpt/metadata/dom/ranges/Range-detach.html.ini @ r4
- tests/wpt/metadata/dom/ranges/Range-extractContents.html.ini @ r4
- tests/wpt/metadata/dom/ranges/Range-insertNode.html.ini @ r4
- tests/wpt/metadata/dom/ranges/Range-intersectsNode-binding.html.ini @ r4
- tests/wpt/metadata/dom/ranges/Range-intersectsNode.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-isPointInRange.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-mutations.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-selectNode.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-set.html.ini @ r5
- tests/wpt/metadata/dom/ranges/Range-surroundContents.html.ini @ r4

---

<sup>**[components/script/dom/range.rs, line 368 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5839#-Jo5LPOukpN5R7txKhp5)** ([raw file](https://github.com/servo/servo/blob/b712057b3b42389f218c1ee16c18bb6f57362446/components/script/dom/range.rs#L368)):</sup>
nit: Leave a note here that steps 1-3 were done in the Range object

---

<sup>**[components/script/dom/range.rs, line 383 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5839#-Jo5LVeiDQY2rn1Gzl_G)** ([raw file](https://github.com/servo/servo/blob/b712057b3b42389f218c1ee16c18bb6f57362446/components/script/dom/range.rs#L383)):</sup>
Ditto

---

<sup>**[components/script/dom/range.rs, line 508 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5839#-Jo5Nv_EPKkPwAXJuwQq)** ([raw file](https://github.com/servo/servo/blob/b712057b3b42389f218c1ee16c18bb6f57362446/components/script/dom/range.rs#L508)):</sup>
`ref child`, though the lint probably caught that

---

<sup>**[tests/wpt/metadata/dom/interfaces.html.ini, line 390 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5839#-Jo5KHM8O0Ef6ZxeV7Wv)** ([raw file](https://github.com/servo/servo/blob/b712057b3b42389f218c1ee16c18bb6f57362446/tests/wpt/metadata/dom/interfaces.html.ini#L390)):</sup>
This should be working I guess?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5839)

**Comment by Manishearth** [comment]
Reviewed files:
- components/script/dom/bindings/error.rs @ r7
- components/script/dom/document.rs @ r7
- components/script/dom/node.rs @ r7
- components/script/dom/range.rs @ r7
- components/script/dom/webidls/Range.webidl @ r5
- tests/wpt/metadata/dom/interfaces.html.ini @ r7
- tests/wpt/metadata/dom/ranges/Range-compareBoundaryPoints.html.ini @ r6

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5839)

**Comment by nox** [comment]
Blocked by https://github.com/servo/servo/pull/5902.

**Comment by nox** [comment]
<sup>**[tests/wpt/metadata/dom/interfaces.html.ini, line 387 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5839#-Jo5KHM8O0Ef6ZxeV7Wv)** ([raw file](https://github.com/servo/servo/blob/b712057b3b42389f218c1ee16c18bb6f57362446/tests/wpt/metadata/dom/interfaces.html.ini#L387)):</sup>
https://github.com/servo/servo/pull/5902

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5839)

**Comment by Manishearth** [comment]
Reviewed files:
- components/script/dom/range.rs @ r8

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5839)

**Comment by Manishearth** [comment]
```
   Compiling compositing v0.0.1 (file:///Users/servo/buildbot/slave/mac1/build/components/servo)
/Users/servo/buildbot/slave/mac1/build/components/script/dom/node.rs:576:13: 576:29 error: unresolved enum variant, struct or const `Text`
/Users/servo/buildbot/slave/mac1/build/components/script/dom/node.rs:576             NodeTypeId::Text |
                                                                                     ^~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac1/build/components/script/dom/node.rs:577:13: 577:46 error: unresolved enum variant, struct or const `ProcessingInstruction`
/Users/servo/buildbot/slave/mac1/build/components/script/dom/node.rs:577             NodeTypeId::ProcessingInstruction |
                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac1/build/components/script/dom/node.rs:578:13: 578:32 error: unresolved enum variant, struct or const `Comment`
/Users/servo/buildbot/slave/mac1/build/components/script/dom/node.rs:578             NodeTypeId::Comment => {
                                                                                     ^~~~~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
```

**Comment by Manishearth** [comment]
Broken by #5879

**Pull request merged**
