### PR TITLE
Win32 support

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @frewsxcv for python stuff
r? @pcwalton for the "remove usage of Gaol" stuff for Win32
r? anybody else for misc cargo.lock updates, etc.

This replaces #7878.

This works best with https://github.com/servo/mozjs/pull/71, too, to enable static linking, but can be run without (via some PATH hackery).

The instructions are here, and will be added to a .md file in the repo once the mozjs changes also land:
https://hackpad.com/Servo-on-Windows-C1LPcI2bP25

I'd like to get these changes landed because I've been rebasing them for months, they're otherwise quite stable, and don't affect our other platforms and targets.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9385)

### CODE REVIEW

**Comment by jdm** [comment]
I left the python stuff and the sandboxing stuff alone.

---

Reviewed 5 of 14 files at r1, 2 of 3 files at r2, 4 of 9 files at r4.
Review status: 11 of 24 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[components/gfx/Cargo.toml, line 88 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8Uhuo0tTE8CcZLV-vU:-K8Uhuo0tTE8CcZLV-vV:-2051094223) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/gfx/Cargo.toml#L88)):*
This should use crates.io instead.

---

*[components/servo/Cargo.lock, line 72 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8UhKfN1EW0eTVbtrQ2:-K8UhKfN1EW0eTVbtrQ3:-483717898) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/servo/Cargo.lock#L72)):*
Uh...

---

*[components/servo/Cargo.lock, line 913 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8Uh4KakDGMAJoxpY1T:-K8Uh4KbQ_IBEFNud4YO:2053290966) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/servo/Cargo.lock#L913)):*
Two kernel32-sys packages.

---

*[components/servo/Cargo.lock, line 1660 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8Ugp9GcNdBmy0QssFk:-K8Ugp9HppLo0xwlFNT_:1771886103) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/servo/Cargo.lock#L1660)):*
Two servo-fontconfigs? I'm surprised that `test-tidy` doesn't complain here.

---

*[components/util/Cargo.toml, line 71 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8UhSYaSl7ETm2x-VhF:-K8UhSYaSl7ETm2x-VhG:-605036940) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/util/Cargo.toml#L71)):*
Let's use the more recent version instead.

---

*[ports/gonk/Cargo.lock, line 54 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8Uhf6xcd0MmTstfu6w:-K8Uhf6xcd0MmTstfu6x:618337797) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/ports/gonk/Cargo.lock#L54)):*
Revert.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385#-:-K8UhqVfp6DY-EIWF4gc:1521266760)*

**Comment by larsbergstrom** [comment]
Review status: 6 of 24 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/gfx/Cargo.toml, line 88 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8Uhuo0tTE8CcZLV-vU:-K8VNM6W-TGhZ2nAsmWu:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/gfx/Cargo.toml#L88)):*
Done.

---

*[components/servo/Cargo.lock, line 72 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8UhKfN1EW0eTVbtrQ2:-K8VNOgnOM1LHzE6ifGi:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/servo/Cargo.lock#L72)):*
Done.

---

*[components/servo/Cargo.lock, line 913 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8Uh4KakDGMAJoxpY1T:-K8VNOF8YxTC9o3aXsab:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/servo/Cargo.lock#L913)):*
Done.

---

*[components/servo/Cargo.lock, line 1660 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8Ugp9GcNdBmy0QssFk:-K8VNNwcQpQKmi4R2Td1:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/servo/Cargo.lock#L1660)):*
Done.

---

*[components/util/Cargo.toml, line 71 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8UhSYaSl7ETm2x-VhF:-K8VNP_e_m7Ls0_orLa-:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/components/util/Cargo.toml#L71)):*
Done.

---

*[ports/gonk/Cargo.lock, line 54 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8Uhf6xcd0MmTstfu6w:-K8VOKM8WhLSvcNi3vX_:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/ports/gonk/Cargo.lock#L54)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by Wafflespeanut** [comment]
I've looked into some of the Python code.

---

Review status: 6 of 25 files reviewed at latest revision, 9 unresolved discussions.

---

*[python/servo/command_base.py, line 21 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VH20bZeg9jhrtAXMI:-K8VH20c5D123sBYeBN0:1309214290) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L21)):*
This could be

``` python
BIN_SUFFIX = '.exe' if sys.platform == 'win32' else ''
```

---

*[python/servo/command_base.py, line 46 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VHY1wvBOWCYMZ8SRt:-K8VHY1wvBOWCYMZ8SRu:1397123719) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L46)):*
We could really go for something like

``` python
known_os = {
'linux': 'unknown-linux-gnu',
# all other OSes
}
os_type = 'pc-windows-gnu' if os_type.startswith('mingw64_nt-') else known_os.get(os_type, 'unknown')
```

---

*[python/servo/command_base.py, line 65 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VJ3Yd55H0lxTxejy-:-K8VJ3Yd55H0lxTxejy0:1513872766) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L65)):*
comprehension (we don't really need bools):

``` python
return int(os.environ.get('SERVO_USE_NIGHTLY_RUST', 0))
```

---

*[python/servo/command_base.py, line 77 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMWwkAEYEEnH2cgvM:-K8VMWwkAEYEEnH2cgvN:547708063) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L77)):*
could be just

``` python
return subprocess.call(*args, shell = sys.platform == 'win32', **kwargs)
```

---

*[python/servo/command_base.py, line 89 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMn7h8t5iKnpgAhL4:-K8VMn7h8t5iKnpgAhL5:1857383350) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L89)):*
Instead of having two functions which share the same code, we could go for a single function which takes one more key/value pair in `kwargs` (say, `call_func`), so that we can pass whatever object we want - something like,

``` python
def verbose_caller(*args, **kwargs):
    # verbose stuff ...
    call_func = kwargs.pop('call_func', subprocess.call)
    # default to subprocess.call (we could also pass subprocess.check_call to `kwargs`)
    return call_func(*args, shell = sys.platform == 'win32', **kwargs)
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385#-:-K8VGNWmQTbCzNSQvHpQ:1155918421)*

**Comment by jdm** [comment]
Reviewed 6 of 6 files at r5.
Review status: 12 of 25 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by frewsxcv** [comment]
*[components/util/workqueue.rs, line 108 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VRa-6u0ErtufqbtSY:-K8VRa-6u0ErtufqbtSZ:224525755) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/util/workqueue.rs#L108)):*
Is `Sleep(0)` the same as not calling it at all?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by frewsxcv** [comment]
Review status: 12 of 25 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/compositing/constellation.rs, line 413 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VQhzwnpZ0oMLQZjhv:-K8VQhzwnpZ0oMLQZjhw:-1020602683) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/compositing/constellation.rs#L413)):*
Inconsistent indentation

---

*[python/servo/command_base.py, line 65 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VJ3Yd55H0lxTxejy-:-K8VRsA-CHygSrdyBGZq:-1846835655) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L65)):*
Why should we use integers instead of booleans?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by frewsxcv** [comment]
*[python/servo/command_base.py, line 77 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMWwkAEYEEnH2cgvM:-K8VS7BnMweAE5W-jRRq:1481324219) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L77)):*
Not the same. `shell` could be `True` on Linux and your suggestion won't reflect that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by frewsxcv** [comment]
Review status: 12 of 25 files reviewed at latest revision, 8 unresolved discussions.

---

*[python/servo/command_base.py, line 227 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VSYVnlUh94pGFMVBF:-K8VSYVnlUh94pGFMVBG:1297900857) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/python/servo/command_base.py#L227)):*
I think `type(env['PATH']) == unicode` might be the same as `isinstance(env['PATH'], unicode)`, though I'm not sure of the functional differences

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by Wafflespeanut** [comment]
Review status: 12 of 25 files reviewed at latest revision, 8 unresolved discussions.

---

*[python/servo/command_base.py, line 65 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VJ3Yd55H0lxTxejy-:-K8VSNqLRvAwwvtH88Y6:396152002) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L65)):*
Well, because we can eliminate one other comparison, and it's the *Pythonic* way. When we only want to check whether the object is *something*, why not pass the object itself?

---

*[python/servo/command_base.py, line 77 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMWwkAEYEEnH2cgvM:-K8VT9gv-fwQHsCYz2gM:1891943536) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L77)):*
The [docs](https://docs.python.org/2/library/subprocess.html) seem to say that `shell = True` is a security hazard and it's `False` by default.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by frewsxcv** [comment]
*[python/servo/command_base.py, line 65 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VJ3Yd55H0lxTxejy-:-K8VUTgRh3e6p6_TQ3m1:-1314352421) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L65)):*
If a function should return "yes" or "no", it should return a boolean, not an integer. Right?

This is how I would write it personally:

```

def use_nightly_rust():
    envvar = os.environ.get("SERVO_USE_NIGHTLY_RUST", "0")
    return envvar != "0"
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by ecoal95** [comment]
Review status: 12 of 25 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[components/servo/lib.rs, line 270 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VgOBI9VgC-_DnDTPH:-K8VgOBI9VgC-_DnDTPI:2086360143) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/servo/lib.rs#L270)):*
nit: Indentation

---

*[components/servo/lib.rs, line 275 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VgQJnxbQtqyYD7_Dq:-K8VgQJnxbQtqyYD7_Dr:1623411017) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/servo/lib.rs#L275)):*
Here too

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by larsbergstrom** [comment]
Review status: 12 of 25 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[components/compositing/constellation.rs, line 413 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VQhzwnpZ0oMLQZjhv:-K8W78KrlATOqgG3JDL_:-499146009) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/compositing/constellation.rs#L413)):*
Done.

---

*[components/servo/lib.rs, line 270 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VgOBI9VgC-_DnDTPH:-K8W7YlGXR_mnLg7UP9H:-499146009) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/servo/lib.rs#L270)):*
Done.

---

*[components/servo/lib.rs, line 275 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VgQJnxbQtqyYD7_Dq:-K8W7aRO3EV9IOpiBIkN:-499146009) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/servo/lib.rs#L275)):*
Done.

---

*[components/util/workqueue.rs, line 108 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VRa-6u0ErtufqbtSY:-K8ZSpUESa0EzrvwWaI4:1215726328) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/util/workqueue.rs#L108)):*
@vvuk, can you comment here?

---

*[python/servo/command_base.py, line 21 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VH20bZeg9jhrtAXMI:-K8ZTOeausgk4xvwxy_8:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L21)):*
Done.

---

*[python/servo/command_base.py, line 46 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VHY1wvBOWCYMZ8SRt:-K8ZTajTd0G8IN4Own9_:-1428471555) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L46)):*
Can we do this as a follow-up E-Easy? I'm not confident in my python-fu to not mess this up on a less supported platform :-)

---

*[python/servo/command_base.py, line 65 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VJ3Yd55H0lxTxejy-:-K8ZTr6wIIBsGKTcH3G_:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L65)):*
Done.

---

*[python/servo/command_base.py, line 77 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMWwkAEYEEnH2cgvM:-K8ZTzGKs6v5sg7izFbR:2140083581) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L77)):*
I'm not sure what to do here, given this comment thread?

---

*[python/servo/command_base.py, line 89 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMn7h8t5iKnpgAhL4:-K8ZU5Gt4XlhQJAmod3s:1020360901) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L89)):*
Another E-Easy follow-up, if you don't mind :-)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by larsbergstrom** [comment]
@pcwalton can you please look at https://github.com/larsbergstrom/servo/commit/843f983acf960ee164db90fc344ee65ccb75ab33?
(ignore the switch on the gaol repo; it's switched back to yours in a later cargo commit- I will do some squashing)

**Comment by vvuk** [comment]
Review status: 12 of 25 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[components/util/workqueue.rs, line 108 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VRa-6u0ErtufqbtSY:-K8ZixPKQkH3ApSm6Pel:-235222088) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/util/workqueue.rs#L108)):*
No -- Sleep(0) gives any other threads a chance to run if any are ready to do so.

---

*[python/servo/command_base.py, line 46 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VHY1wvBOWCYMZ8SRt:-K8ZjoEiJQwhQtU8nKd8:487415408) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L46)):*
Obviously up to you guys, but the proposed alternative looks ugly as hell to me... the if/else tree uses a lot of vertical space, but it's pretty clear what it's doing.  If you want to turn it into a table lookup, then I'd suggest using a dict with regexps so that everything can be kept in it instead of having one-offs for windows.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by frewsxcv** [comment]
*[python/servo/command_base.py, line 46 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VHY1wvBOWCYMZ8SRt:-K8Zks-RrATnieCM7Euv:1410314382) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L46)):*
Personally, I prefer the conditional over dictionary indexing. The latter doesn't really make any sense to me in this case

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by ecoal95** [comment]
Tidy says the following:

```
./components/compositing/constellation.rs:453: trailing whitespace
./python/servo/bootstrap_commands.py:31: F401 'use_nightly_rust' imported but unused
./python/servo/command_base.py:21: E302 expected 2 blank lines, found 1
./python/servo/devenv_commands.py:99: F821 undefined name 'subprocess'
```

And this fails to build in travis due to:

```
/home/travis/build/servo/servo/components/compositing/lib.rs:29:1: 29:19 error: can't find crate for `gaol` [E0463]
/home/travis/build/servo/servo/components/compositing/lib.rs:29 extern crate gaol;
                                                                ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `compositing`.
```

**Comment by Wafflespeanut** [comment]
Review status: 9 of 25 files reviewed at latest revision, 8 unresolved discussions.

---

*[python/servo/command_base.py, line 77 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMWwkAEYEEnH2cgvM:-K8b3AkPezJGBfoKr1nT:-892455894) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L77)):*
It could be what I suggested if @frewsxcv is okay with it...

---

*[python/servo/command_base.py, line 89 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMn7h8t5iKnpgAhL4:-K8b2tcA9dmm4brTnYjI:1852966921) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L89)):*
Yes, we need E-easy!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by frewsxcv** [comment]
*[python/servo/command_base.py, line 77 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMWwkAEYEEnH2cgvM:-K8b9Dn-ANdE2P5X9sr4:-1282958685) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L77)):*
I think @wafflespeanut's suggestion is fine, though make sure to format it like 

```python
return subprocess.call(*args, shell=sys.platform == 'win32', **kwargs)

# or

shell= sys.platform == 'win32'
return subprocess.call(*args, shell=shell, **kwargs)
```

or the style checker (flake8) will complain (you could add parens for clarity if you wish). Make sure to retain the comment about the PATH handling on windows.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by frewsxcv** [comment]
*[python/servo/command_base.py, line 77 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMWwkAEYEEnH2cgvM:-K8b9GwDtWdWSwqaSLXH:-1050077525) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L77)):*
I meant:

```python
shell = sys.platform == 'win32'
```

for line 5 of my previous post

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by ecoal95** [comment]
Review status: 9 of 25 files reviewed at latest revision, 8 unresolved discussions.

---

*[components/util/workqueue.rs, line 108 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VRa-6u0ErtufqbtSY:-K8bOzwxIZ-vueOMo-wR:-451700504) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/util/workqueue.rs#L108)):*
Oh, btw, this could use [`std::thread::yield_now`](https://doc.rust-lang.org/std/thread/fn.yield_now.html), but I don't know if it's really worth it since in this case this is Win32 specific (we'll get rid of the `kernel32` dep though).

I also don't understand why this ignores the `usec` param (will this potentially spin up the cpu all the time?), but I assume that has been already thought (I *think* I read in IRC this was left as a followup).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by pcwalton** [comment]
@larsbergstrom That commit looks good to me.

**Comment by larsbergstrom** [comment]
Review status: 9 of 25 files reviewed at latest revision, 8 unresolved discussions.

---

*[components/util/workqueue.rs, line 108 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VRa-6u0ErtufqbtSY:-K8fzzAQQnXXE1D1QrjI:-164146809) ([raw file](https://github.com/servo/servo/blob/1b7ab75347978f72ad087ae25df774b83aa0dce9/components/util/workqueue.rs#L108)):*
Yes, we will follow up on this with an appropriate `MsgWaitForMultipleObjectsEx` (sleep on main thread is bad on windows because it will prevent the window from repainting during a drag because the message loop doesn't pump).

---

*[python/servo/command_base.py, line 46 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VHY1wvBOWCYMZ8SRt:-K8g-DF80QQT0FZFJvZ5:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L46)):*
Done.

---

*[python/servo/command_base.py, line 77 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMWwkAEYEEnH2cgvM:-K8g-iNWFxAoGqA0EihT:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L77)):*
Done.

---

*[python/servo/command_base.py, line 89 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9385#-K8VMn7h8t5iKnpgAhL4:-K8g-j4hFeAmKDrOsLyF:-499146009) ([raw file](https://github.com/servo/servo/blob/32b6d288b3bdd04844690949027bd6b1eab80ece/python/servo/command_base.py#L89)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9385)*

**Comment by frewsxcv** [comment]
Python stuff LGTM

**Comment by frewsxcv** [comment]
:confetti_ball:

**Comment by paulrouget** [comment]
@larsbergstrom Should we move https://hackpad.com/Servo-on-Windows-C1LPcI2bP25 to the servo/wiki?

**Comment by larsbergstrom** [comment]
@paulrouget I meant to move it to Readme.md, and will do so in a follow-up. Thanks for the reminder!

**Comment by jasonwilliams200OK** [comment]
Great! :+1: 
Could we also have AppVeyor CI configured (http://www.appveyor.com/docs/appveyor-yml) to see Windows builds on CI via MinGW and Visual Studio? e.g. https://github.com/Snaipe/Criterion/blob/bleeding/appveyor.yml

**Comment by frewsxcv** [comment]
@jasonwilliams200k https://github.com/servo/servo/pull/9406

**Pull request merged**
