### PR TITLE
WebGL: add Uniform2f

### PR DESCRIPTION
**Pull request by this-jacob**
Currently blocked on servo/webrender_traits#30

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10356)

### CODE REVIEW

**Comment by emilio** [comment]
Looks great, thanks!

Could you update webrender traits when the blocking PR merges and squash?

r=me then :)

**Comment by Ar13mis** [comment]
@emilio I updated webrender_traits and squashed.

**Comment by emilio** [comment]
@Ar13mis: Looks good!

The build queue is huge right now, and another PR updating to a previous version of webrender has just landed (#10349). You'll need to rebase your changes on top of those.

Let me know if you need any help with anything :)

**Comment by Ar13mis** [comment]
@emilio It has been rebased!

Thanks for offering your assistance as well!

**Comment by emilio** [comment]
You'll have to re-add the trailing newlines to the lockfiles, else the ci script lockfile_changed will complain.

**Comment by Ar13mis** [comment]
@emilio Should be ready to go now.

**Comment by emilio** [comment]
@bors-servo: r+

Thanks for doing this! :)

**Comment by KiChjang** [comment]
@bors-servo retry
* #10398

**Comment by KiChjang** [comment]
@bors-servo retry
* #10398

**Pull request merged**
