### PR TITLE
layout: When a table is too large for its explicitly-specified inline width, ignore the latter.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5549)

### CODE REVIEW

**Comment by mbrubeck** [comment]
r+, needs rebase.

**Comment by jdm** [comment]
```
failures:
    table_float_translation_a.html == table_float_translation_ref.html
```

**Comment by pcwalton** [comment]
This PR is actually wrong, sorry. The issue here is that `white-space: nowrap` doesn't impact minimum width.

**Pull request closed without merging**
