### PR TITLE
Initial fetch refactor

### PR DESCRIPTION
**Pull request by KiChjang**
Partial #4576
I am really unsure of how things would look like, so would really appreciate some feedback on this.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7275)

### CODE REVIEW

**Comment by jdm** [comment]
This is a good start! Having looked further at the fetch spec and the existing code, I propose the following:
* we should only require the `FetchContext` value when we go to the network in `http_network_or_cache_fetch` (which obviously is not actually implemented yet).
* spawn a thread in `fetch_async`, call `fetch` from it, and invoke `listener.response_available` with the `Response` return value
`fetch_async` now runs asynchronously from the point of view of the caller, and the listener will need to be implemented such that it sends the Response value that is passed over a channel back to the thread that invoked `fetch_async` (just like http://mxr.mozilla.org/servo/source/components/script/network_listener.rs#16)

Does that make sense?

**Comment by jdm** [comment]
Looking better!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/net/fetch/request.rs, line 152 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7275#-K-1pt__aIM5jmwCZojI)** ([raw file](https://github.com/servo/servo/blob/0c7e5281f812e2f42c3323be03492dd6c50ca9b4/components/net/fetch/request.rs#L152)):</sup>
If we make this method take self by value, we shouldn't need this clone.

---

<sup>**[components/net/fetch/request.rs, line 153 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7275#-K-1q1wqCPv1FQr_l39N)** ([raw file](https://github.com/servo/servo/blob/0c7e5281f812e2f42c3323be03492dd6c50ca9b4/components/net/fetch/request.rs#L153)):</sup>
`format!("fech for {:?}", self.url.serialize())`

---

<sup>**[components/net_traits/lib.rs, line 167 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7275#-K-1pNpdfqhpR3etFvkz)** ([raw file](https://github.com/servo/servo/blob/8b803ba1948f01f6d1c8963bf8f942bce4736a7c/components/net_traits/lib.rs#L167)):</sup>
I'd go with:
```rust
/// Interface for observing the final response for an asynchronous fetch operation.
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7275)

**Comment by jdm** [comment]
Great! Let's squash all these commits and then merge them :)
-S-needs-rebase -S-awaiting-review +S-needs-squash 


---

Reviewed 3 of 3 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7275)

**Comment by KiChjang** [comment]
Just one sec, currently it doesn't compile and it generates this error:

```
servo/components/net/fetch/request.rs:153:9: 153:20 error: the trait `core::marker::Send` is not implemented for the type `fetch::cors_cache::CORSCache + 'static` [E0277]
servo/components/net/fetch/request.rs:153         spawn_named(format!("fetch for {:?}", self.url.serialize()), move || {
```

and goes on to say that `fetch::cors_cache::CORSCache + 'static' cannot be sent between threads safely`. Not sure what the best way to fix this.

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/7275/files#diff-4039fbc0ced622014645f0d0d9c4e443R117 will need to be `Box<CORSCache + Send>` instead, I believe.

**Comment by KiChjang** [comment]
Squashed and fixed build errors. Little guy should be ready to merge, apolgies for taking so long to finish this simple task.

**Comment by jdm** [comment]
@bors-servo: r+
No worries! Thanks for doing this!

**Pull request merged**
