### PR TITLE
Remove the global argument to EventTarget::{fire_event, fire_simple_event}.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9571)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Yay, the code got a lot cleaner!

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9571#-:-KA2EZDkdhlxeXulGUdX:2042531409)*

**Comment by asajeffrey** [comment]
The CSS failure is probably just an intermittent. The compiler warning is more of a concern, do you know what's causing it?

**Comment by KiChjang** [comment]
Which compiler warning are you talking about?

**Comment by KiChjang** [comment]
@bors-servo retry
* #7791

**Comment by asajeffrey** [comment]
The warnings at http://build.servo.org/builders/linux-rel/builds/1822, but if you reckon those are unrelated then yay.

**Pull request merged**
