### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mbrubeck**
Cargo.lock changes only. Note: May cause some new bidi tests to pass.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17188)

### CODE REVIEW

**Comment by jdm** [comment]
The error appearing here is due to including metadeps, which brings in backtrace. Possibly the problem is that it's used during the build script phase and our ARM builder is somehow confused by that?

**Comment by mbrubeck** [comment]
`$CC` is incorrectly set to `aarch64-linux-gnu-gcc` while configuring libbacktrace, while building `backtrace-sys` as a build-dependency, even though `$TARGET` is correctly set to `x86_64-unknown-linux-gnu`.

`$CC` is set [by the backtrace-sys build script](https://github.com/alexcrichton/backtrace-rs/blob/backtrace-sys-0.1.11/backtrace-sys/build.rs#L78) using the `gcc` crate, so maybe this is a bug in the new version of the `gcc` crate.

<details>
```
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("aarch64-linux-gnu-gcc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("release")
running: "sh" "/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.11/src/libbacktrace/configure" "--with-pic" "--disable-multilib" "--disable-shared" "--disable-host-shared" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu"
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for x86_64-unknown-linux-gnu-gcc... aarch64-linux-gnu-gcc
```
</details>

**Pull request closed without merging**
