### PR TITLE
./mach has a formatting error

### LINKED ISSUE #12766: ./mach has a formatting error
This occurred today. I'm not sure what goes wrong here. This occurs only when we append non-string values to strings.

    TypeError: coercing to Unicode: need string or buffer, instance found

      File "/media/Windows/Mozilla/servo/python/servo/build_commands.py", line 203, in build
        self.ensure_bootstrapped(target=target)
      File "./python/servo/command_base.py", line 499, in ensure_bootstrapped
        stable=self._use_stable_rust)
      File "/media/Windows/Mozilla/servo/python/_virtualenv/lib/python2.7/site-packages/mach/registrar.py", line 123, in dispatch
        return self._run_command_handler(handler, context=context, **kwargs)
      File "/media/Windows/Mozilla/servo/python/_virtualenv/lib/python2.7/site-packages/mach/registrar.py", line 90, in _run_command_handler
        result = fn(**kwargs)
      File "/media/Windows/Mozilla/servo/python/servo/bootstrap_commands.py", line 203, in bootstrap_rustc
        download_file("Host rust library for target %s" % target_triple, std_url, tgz_file)
      File "/media/Windows/Mozilla/servo/python/servo/bootstrap_commands.py", line 85, in download_file
        download(desc, src, fd, start_byte=start_byte)
      File "/media/Windows/Mozilla/servo/python/servo/bootstrap_commands.py", line 73, in download
        print("Error downloading Rust compiler: " + str(e.reason) + ". The failing URL was: " + src)

Instead of appending, we can `format` the values, which (I'm pretty sure) will fix this error.

Code: `python/servo/bootstrap_commands.py`

### PR DESCRIPTION
**Pull request by pathway27**
Fix for #12766. Couldn't reproduce the exact error.

I explicitly raised urllib2.URLError to get to the print and then tried using many different variable types for e.reason and src but it still didn't throw a coercion error.

So, as @Wafflespeanut said, 

> Instead of appending, we can format the values, which (I'm pretty sure) will fix this error.

which is what i've done.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12766, hopefully.

- [ ] There are tests for these changes OR
- [X] These changes do not require tests they execute before the test runner is installed. Can't test the bootstraping code.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12870)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Next time, if an error pops up like this, we'll know what exactly did go wrong (since almost every object can be formatted using `print`). So, yeah, we dunno the diagnosis, but we're sure about the treatment :smile: 

Can you please change your commit message to something sensible? (something like, `"Fix error-prone message while bootstrapping"`)

**Comment by Wafflespeanut** [comment]
Looking at the code again, I think I'd missed something the other day. `src` is being redefined [here](https://github.com/servo/servo/blob/master/python/servo/bootstrap_commands.py#L41). So, when we resume a download, if an `URLError` is raised, we catch it and try to append the `src` (which is now, a `Request` instance, instead of a string) to the message, which throws this error. Now, there's a way to test it? :)

**Comment by pathway27** [comment]
Yup, you were right on the money @Wafflespeanut .

I interrupted the download in manually:

```
$ ./mach bootstrap-rust -f
Downloading Rust compiler...
Downloading Rust compiler:   0.4%^Cmach interrupted by signal or user action. Stopping.
```


Then raised the exception after the src assignment. The old code produced the error you saw!
```
$ ./mach bootstrap-rust -f
...

TypeError: coercing to Unicode: need string or buffer, instance found

  File "/Users/sreechela/ws/git/servo/python/servo/bootstrap_commands.py", line 167, in bootstrap_rustc
    download_file("Rust compiler", rustc_url, tgz_file)
  File "/Users/sreechela/ws/git/servo/python/servo/bootstrap_commands.py", line 88, in download_file
    download(desc, src, fd, start_byte=start_byte)
  File "/Users/sreechela/ws/git/servo/python/servo/bootstrap_commands.py", line 75, in download
    print("Error downloading Rust compiler: " + str(e.reason) + ". The failing URL was: " + src)
```

The new code gives exactly what you described, a `Request` instance.

```
$ ./mach bootstrap-rust -f
Resuming download of Rust compiler...
Error downloading Rust compiler: blah. The failing URL was: <urllib2.Request instance at 0x1020de488>
```

How shall we handle the errors message when resuming? Change the variable name for the request?

**Comment by Wafflespeanut** [comment]
Maybe we should have a new variable binding (`req`?) which is always a `Request(src)`. If `start_byte` is positive, then it's `Request(src, headers ...)`. `urlopen` will always take this `req`, and so we won't override `src` :)

**Comment by pathway27** [comment]
Perfect. It works :D, check my latest commit.

**Comment by Wafflespeanut** [comment]
Great work! :)

@bors-servo r+

**Pull request merged**
