### PR TITLE
Make DOMTokenList.contains not throw anymore

### LINKED ISSUE #11579: Make DOMTokenList.contains not throw anymore
See https://github.com/whatwg/dom/issues/202 and https://dom.spec.whatwg.org/#dom-domtokenlist-contains.

Files:
* components/script/dom/domtokenlist.rs
* components/script/dom/webidls/DOMTokenList.webidl

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #11579.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11589)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
The test /dom/ranges/Range-mutations.html now gets timeout error.

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/domtokenlist.rs, line 74 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11589#-KJNJnaYauJJ3c-IxXh_:-KJNJnaYauJJ3c-IxXha:-1512706276) ([raw file](https://github.com/servo/servo/blob/577caa2b431daddbd88f8119505465f8eabaa9ca/components/script/dom/domtokenlist.rs#L74)):*
> ```Rust
>     // https://dom.spec.whatwg.org/#dom-domtokenlist-contains
>     fn Contains(&self, token: DOMString) -> bool {
>         if let Ok(token) = self.check_token_exceptions(&token) {
> ```

No, you shouldn't call `check_token_exceptions` anymore. The issue is about making `DOMTokenList.contains` follow [the spec](https://dom.spec.whatwg.org/#dom-domtokenlist-contains). There is no need at all anymore to check exceptions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11589#-:-KJNK1uZYftd4GROqZNU:1458266033)*

**Comment by nox** [comment]
-S-awaiting-review 

@bors-servo r+

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11589#-:-KJNSQCA3qv1hh_ooO18:1206180040)*

**Comment by nox** [comment]
@bors-servo r+

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11589#-:-KJQbfyRITdcv-cG3CjR:1236647940)*

**Pull request merged**
