### PR TITLE
Avoid recompiling script every time surfman changes

### PR DESCRIPTION
**Pull request by asajeffrey**
Uses a version of webxr where webxr-api doesn't depend on surfman, so we can make changes to it without rebuilding script.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it's just build issues

### CODE REVIEW

**Comment by asajeffrey** [comment]
Can land once https://github.com/servo/webxr/pull/91 does.

**Review by jdm — APPROVED** [review]

**Comment by asajeffrey** [comment]
Rebased. @bors-servo r=jdm

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Pull request merged**
