### PR TITLE
Servo side of gecko bug 1343078: update bindinggen bits for the changes I'm making to Gecko atoms.

### PR DESCRIPTION
**Pull request by bzbarsky**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because they will get tested by Firefox CI.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15843)

### CODE REVIEW

**Comment by bzbarsky** [comment]
@upsuper Would you please review?  But this needs to be coordinated with landing the Gecko-side changes, so please don't r+, just delegate to me...

**Comment by nox** [comment]
Please write a shorter commit title that fits Git general guidelines next time.

**Comment by bzbarsky** [comment]
I'm happy to update the commit title to fit whatever guidelines, if you link me to the guidelines.

**Comment by nox** [comment]
Usually I just ask people to do something like in [Tim Pope's original template](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). Very low priority, hence why I just asked you to keep it in mind for next time. :)

Sometimes when rebasing stuff, or just looking at `git log`'s output in its shorter format, the long titles get truncated and it makes things difficult to follow.

**Comment by bzbarsky** [comment]
Done.

**Comment by upsuper** [comment]
This may conflict with #15846. @bzbarsky could you update the atoms file again so that it includes the `scroll-position` atom added in [bug 1344964](https://bugzilla.mozilla.org/show_bug.cgi?id=1344964)? I can close #15846 so we wouldn't conflict.

**Comment by bzbarsky** [comment]
Updated to include scroll-position.

**Pull request merged**
