### PR TITLE
Add expected failures for send-entity-body-document.htm.

### LINKED ISSUE #8157: XMLHttpRequest/send-entity-body-document.htm intermittently fails

### PR DESCRIPTION
**Pull request by eefriedman**
Fixes #8157.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8289)

### CODE REVIEW

**Comment by jdm** [comment]
This doesn't seem like a useful change right now; the test was disabled because the failures only appeared intermittently on OS X, which makes merging things harder.

**Comment by eefriedman** [comment]
The tests all fail consistently.  They just don't run consistently, which is what causes the intermittent failures.

**Comment by jdm** [comment]
Yes, that distinction is true. I don't understand the benefit of re-enabling this test while the results are not consistently, however.

**Comment by eefriedman** [comment]
Whatever, I'll just leave it alone for now.

**Comment by Ms2ger** [comment]
If these tests don't run consistently, would these annotations make everything finish successfully?

**Comment by eefriedman** [comment]
They would, I think.  (At least, they do in my brief testing.)  The test runner ignores annotations for tests which aren't run.

**Pull request closed without merging**
