### PR TITLE
Implement Stringifier for Range

### PR DESCRIPTION
**Pull request by KiChjang**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9796)

### CODE REVIEW

**Comment by ecoal95** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/range.rs, line 871 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9796#-KBd0EEOxXEh-A5iSZ-2:-KBd0EEOxXEh-A5iSZ-3:-1769292104) ([raw file](https://github.com/servo/servo/blob/b2c16f9d9024ca88485da5a8ca8a7fe372256098/components/script/dom/range.rs#L871)):*
I'm almost sure there's a missing paren here :P

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9796)*

**Comment by nox** [comment]
#9795

**Comment by nox** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Range interface: stringifier
```

This needs many more tests, I think.

**Comment by jdm** [comment]
I agree that a thorough testsuite would be valuable here.
-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/range.rs, line 862 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9796#-KBrzZ8ECFqUkDX3qjoN:-KBrzZ8ECFqUkDX3qjoO:2083578555) ([raw file](https://github.com/servo/servo/blob/1814cd55e189c2fef1f3ab5c9e3bf049f8ab16f0/components/script/dom/range.rs#L862)):*
Let's use `if let` here instead.

---

*[components/script/dom/range.rs, line 863 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9796#-KBrzb5rXFUXZlS_XzXX:-KBrzb5rXFUXZlS_XzXY:-557999092) ([raw file](https://github.com/servo/servo/blob/1814cd55e189c2fef1f3ab5c9e3bf049f8ab16f0/components/script/dom/range.rs#L863)):*
Then this can be an upcast of the value from the `if let`.

---

*[components/script/dom/range.rs, line 881 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9796#-KBrzzONQYFKsw8N1D-f:-KBrzzONQYFKsw8N1D-g:-1377826717) ([raw file](https://github.com/servo/servo/blob/1814cd55e189c2fef1f3ab5c9e3bf049f8ab16f0/components/script/dom/range.rs#L881)):*
What if we filter_map the iterator to call downcast?

---

*[components/script/dom/range.rs, line 884 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9796#-KBs-9avg7nWQAjKwl1p:-KBs-9avg7nWQAjKwl1q:923906962) ([raw file](https://github.com/servo/servo/blob/1814cd55e189c2fef1f3ab5c9e3bf049f8ab16f0/components/script/dom/range.rs#L884)):*
This can be an upcast of the iterator value with the previous change.

---

*[components/script/dom/range.rs, line 889 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9796#-KBs-Hf8Pq6sQ0yT-fxZ:-KBs-Hf8Pq6sQ0yT-fx_:-648789395) ([raw file](https://github.com/servo/servo/blob/1814cd55e189c2fef1f3ab5c9e3bf049f8ab16f0/components/script/dom/range.rs#L889)):*
`if let`

---

*[components/script/dom/range.rs, line 892 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9796#-KBs-aN9kY0WsQwFOmRN:-KBs-aN9kY0WsQwFOmRO:1012865347) ([raw file](https://github.com/servo/servo/blob/1814cd55e189c2fef1f3ab5c9e3bf049f8ab16f0/components/script/dom/range.rs#L892)):*
Using start offset here is incorrect. Tests!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9796#-:-KBs-eDcRel2y7aakOIr:-2072063370)*

**Comment by jdm** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9796)*

**Comment by jdm** [comment]
-S-awaiting-review 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/wpt/web-platform-tests/dom/ranges/Range-stringifier.html, line 16 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9796#-KCRmWjJRAnSwTIUC0B_:-KCRmWjJRAnSwTIUC0Ba:1773259082) ([raw file](https://github.com/servo/servo/blob/8241074babe89099e3e3429cefc93f8d049f61fa/tests/wpt/web-platform-tests/dom/ranges/Range-stringifier.html#L16)):*
Could we test these variations as well?
1) entirely contained in a single node with start and end offsets
2) two nodes with no offsets
3) three nodes with start and end offsets?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9796#-:-KCRn4JhsqrruW4Fp4Y_:879583689)*

**Comment by jdm** [comment]
-S-awaiting-review -S-needs-tests +S-needs-code-changes 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/ranges/Range-stringifier.html, line 17 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9796#-KCS0UFFMOEKbNEx74-S:-KCS0UFGB37WAcilNWNu:-1774228996) ([raw file](https://github.com/servo/servo/blob/6631eb297e50406eb11e03d1de8ef0de1371aba3/tests/wpt/web-platform-tests/dom/ranges/Range-stringifier.html#L17)):*
Please use a separate test() for each testcase, and add a descriptive message (`test(..., "message")`).

---

*[tests/wpt/web-platform-tests/dom/ranges/Range-stringifier.html, line 20 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9796#-KCS0pcYV06t7-iy3nOO:-KCS0pcYV06t7-iy3nOP:-1366763067) ([raw file](https://github.com/servo/servo/blob/6631eb297e50406eb11e03d1de8ef0de1371aba3/tests/wpt/web-platform-tests/dom/ranges/Range-stringifier.html#L20)):*
Can we use a non-zero offset here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9796#-:-KCS1SpllOPhK14_E7fI:330330613)*

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9796#-:-KCSVLOBAV9USv-lquaJ:-1746383326)*

**Comment by KiChjang** [comment]
@bors-servo retry
* larsbors stopped the build

**Pull request merged**
