### PR TITLE
Sync WPT with upstream manually (27-04-2022)

### PR DESCRIPTION
**Pull request by CYBAI**

### CODE REVIEW

**Comment by jdm** [comment]
Error syncing changes upstream. Logs saved in error-snapshot-1651109943444.

**Comment by jdm** [comment]
Error syncing changes upstream. Logs saved in error-snapshot-1651110198360.

**Comment by CYBAI** [comment]
`test-tidy` failed with this 👀 

> WPT Lint Tool:: lint error(s) in Web Platform Tests: exit status 62

I will look into it 🤔

**Comment by CYBAI** [comment]
I will check if they are intermittent results during the sync job.

```
1 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected OK] b'/html/browsers/the-window-object/open-close/creating_browsing_context_test_01.html'

  ▶ Unexpected subtest result in /html/browsers/the-window-object/open-close/creating_browsing_context_test_01.html:
  │ TIMEOUT [expected PASS] b'first argument: absolute url'
  └   → Test timed out

1 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected OK] b'/webstorage/localstorage-about-blank-3P-iframe-opens-3P-window.partitioned.tentative.html'

  ▶ Unexpected subtest result in /webstorage/localstorage-about-blank-3P-iframe-opens-3P-window.partitioned.tentative.html:
  │ TIMEOUT [expected PASS] b'StorageKey: test 3P about:blank window opened from a 3P iframe'
  └   → Test timed out

1 unexpected results that are NOT known-intermittents:
  ▶ Unexpected subtest result in /css/CSS2/normal-flow/block-in-inline-hittest-001.html:
  │ FAIL [expected PASS] b'block-in-inline-hittest-001'
  │   → assert_equals: expected Element node <div id="target">
  │   →           <div style="width: 64px; heig... but got Element node <html><head><meta name="assert" content="Test hit-testing...
  │ 
  │ @http://web-platform.test:8000/css/CSS2/normal-flow/block-in-inline-hittest-001.html:26:16
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2590:25
  │ test@http://web-platform.test:[800](https://github.com/servo/servo/runs/6204268825?check_suite_focus=true#step:7:800)0/resources/testharness.js:628:30
  └ @http://web-platform.test:8000/css/CSS2/normal-flow/block-in-inline-hittest-001.html:20:5
```

**Comment by CYBAI** [comment]
@bors-servo try=wpt

- `/html/browsers/the-window-object/open-close/creating_browsing_context_test_01.html`: it's a 7 years old test so I guess this is an intermittent failure this time.
- `/webstorage/localstorage-about-blank-3P-iframe-opens-3P-window.partitioned.tentative.html` & `/css/CSS2/normal-flow/block-in-inline-hittest-001.html`: added in this PR. let's retry to see the status in next run

**Comment by CYBAI** [comment]
@bors-servo retry

Interesting, they all failed again but I'd like to do a third try 🤔 

```
1 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected OK] b'/html/browsers/the-window-object/open-close/creating_browsing_context_test_01.html'

  ▶ Unexpected subtest result in /html/browsers/the-window-object/open-close/creating_browsing_context_test_01.html:
  │ TIMEOUT [expected PASS] b'first argument: absolute url'
  └   → Test timed out

1 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected OK] b'/webstorage/localstorage-about-blank-3P-iframe-opens-3P-window.partitioned.tentative.html'

  ▶ Unexpected subtest result in /webstorage/localstorage-about-blank-3P-iframe-opens-3P-window.partitioned.tentative.html:
  │ TIMEOUT [expected PASS] b'StorageKey: test 3P about:blank window opened from a 3P iframe'
  └   → Test timed out

1 unexpected results that are NOT known-intermittents:
  ▶ Unexpected subtest result in /css/CSS2/normal-flow/block-in-inline-hittest-001.html:
  │ FAIL [expected PASS] b'block-in-inline-hittest-001'
  │   → assert_equals: expected Element node <div id="target">
  │   →           <div style="width: 64px; heig... but got Element node <html><head><meta name="assert" content="Test hit-testing...
  │ 
  │ @http://web-platform.test:8000/css/CSS2/normal-flow/block-in-inline-hittest-001.html:26:16
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2590:25
  │ test@http://web-platform.test:8000/resources/testharness.js:628:30
  └ @http://web-platform.test:8000/css/CSS2/normal-flow/block-in-inline-hittest-001.html:20:5
```

**Comment by CYBAI** [comment]
```
1 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected OK] b'/webstorage/localstorage-about-blank-3P-iframe-opens-3P-window.partitioned.tentative.html'

  ▶ Unexpected subtest result in /webstorage/localstorage-about-blank-3P-iframe-opens-3P-window.partitioned.tentative.html:
  │ TIMEOUT [expected PASS] b'StorageKey: test 3P about:blank window opened from a 3P iframe'
  └   → Test timed out

1 unexpected results that are NOT known-intermittents:
  ▶ Unexpected subtest result in /css/CSS2/normal-flow/block-in-inline-hittest-002.html:
  │ FAIL [expected PASS] b'elementFromPoint'
  │   → assert_equals: expected Element node <h3 id="target">
  │   →         text
  │   →       </h3> but got Element node <html><head><meta name="assert" content="Test list-based ...
  │ 
  │ @http://web-platform.test:8000/css/CSS2/normal-flow/block-in-inline-hittest-002.html:32:16
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2590:25
  │ test@http://web-platform.test:8000/resources/testharness.js:628:30
  └ @http://web-platform.test:8000/css/CSS2/normal-flow/block-in-inline-hittest-002.html:30:5
```

**Comment by jdm** [comment]
Error syncing changes upstream. Logs saved in error-snapshot-1653886162785.

**Comment by jdm** [comment]
Error syncing changes upstream. Logs saved in error-snapshot-1654073154755.

**Comment by jdm** [comment]
Error syncing changes upstream. Logs saved in error-snapshot-1654331873716.

**Comment by jdm** [comment]
Error syncing changes upstream. Logs saved in error-snapshot-1660577145938.

**Pull request closed without merging**
