### PR TITLE
Implement referrer policy

### LINKED ISSUE #26270: Implement missing referrer policy for HTTP-redirect fetch
Spec: step 14 of https://fetch.spec.whatwg.org/#http-redirect-fetch
Code: components/net/http_loader.rs, http_redirect_fetch function
Tests: tests/wpt/web-platform-tests/fetch/api

### PR DESCRIPTION
**Pull request by Eijebong**
Fixes #26270

### CODE REVIEW

**Comment by Eijebong** [comment]
```
2 unexpected results that are NOT known-intermittents:
  ▶ FAIL [expected PASS] /css/CSS2/text/white-space-processing-046.xht
  │   → /css/CSS2/text/white-space-processing-046.xht 002fd45a59a878dd2b265df90e10f49571fa5f8a
  └   → /css/CSS2/text/white-space-processing-046-ref.xht 31cb4a869a914063af9f573e661c9f4336c85ec3
  ▶ FAIL [expected PASS] /css/CSS2/text/white-space-processing-047.xht
  │   → /css/CSS2/text/white-space-processing-047.xht 002fd45a59a878dd2b265df90e10f49571fa5f8a
  └   → /css/CSS2/text/white-space-processing-046-ref.xht 31cb4a869a914063af9f573e661c9f4336c85ec3
```

Unrelated

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
