### PR TITLE
Adds browserhtml dependency and mach run --browserhtml

### PR DESCRIPTION
**Pull request by metajack**
This makes the experience for testing browserhtml super easy.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9873)

### CODE REVIEW

**Comment by ecoal95** [comment]
r=me with that nit adressed :)

**Comment by ecoal95** [comment]
Aghh sorry, should have caught it, all lockfiles should be updated.

**Comment by metajack** [comment]
The dependency only exists for components/servo. It's not required in the other Cargo.tomls.

**Pull request merged**
