### PR TITLE
Stylo: Deep clone ServoStyleSheets.

### PR DESCRIPTION
**Pull request by bradwerth**
MozReview-Commit-ID: 6hYIcOa86Y

https://bugzilla.mozilla.org/show_bug.cgi?id=1339629
https://reviewboard.mozilla.org/r/135314/

---

- [x] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17028)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r-

Unit tests are failing:
```
The command "./mach build -d --verbose" exited with 101.
23.99s$ ./mach test-compiletest
   Compiling compiletest_rs v0.2.6
   Compiling style v0.0.1 (file:///home/travis/build/servo/servo/components/style)
   Compiling compiletest_helper v0.0.1 (file:///home/travis/build/servo/servo/tests/compiletest/helper)
error: no method named `deep_clone_from_gecko` found for type `&font_face::FontFaceRuleData` in the current scope
   --> /home/travis/build/servo/servo/components/style/stylesheets.rs:509:26
    |
509 |                     rule.deep_clone_from_gecko())))
    |                          ^^^^^^^^^^^^^^^^^^^^^
error: no method named `deep_clone_from_gecko` found for type `&counter_style::CounterStyleRuleData` in the current scope
   --> /home/travis/build/servo/servo/components/style/stylesheets.rs:514:26
    |
514 |                     rule.deep_clone_from_gecko())))
    |                          ^^^^^^^^^^^^^^^^^^^^^
error: aborting due to 2 previous errors
error: Could not compile `style`.
To learn more, run the command again with --verbose.
```

**Comment by bradwerth** [comment]
retrying after intermittents
* #16216
* #16627

**Pull request merged**
