### PR TITLE
Ignore VSCode IDE files

### PR DESCRIPTION
**Pull request by saschanaz**
This ignores launch.json (to configure debugger) and `ipch/` (for IntelliSense).

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [x] These changes do not require tests because it only changes gitignore.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23686)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Why not ignore all of `.vscode/` ?

**Comment by saschanaz** [comment]
AFAIK `ipch/` is just a cache, and we don't have a `launch.json` (Do we want to create and maintain this?)

**Comment by saschanaz** [comment]
>Why not ignore all of .vscode/ ?

Because we have extensions.json? Maybe I can do `!/.vscode/extensions.json`

**Comment by saschanaz** [comment]
@jdm Could you review this? Currently I have to consciously ignore those files when I commit 🤔

**Comment by SimonSapin** [comment]
> I have to consciously ignore those files

For what it’s worth you can also use the local-clone-only ignore file at `.git/info/exclude`

**Pull request merged**
