### PR TITLE
Add [Default] toJSON() to performance interfaces

### LINKED ISSUE #21274: Duplicate tests when running /navigation-timing/idlharness.window.html
After upgrading to SM60, the IDL tests in WPT are run. One of them fails, complaining about duplicate tests:
```
{"status": "ERROR", "group": "default", "message": "41 duplicate test names: \"PerformanceNavigationTiming interface: existence and properties of interface object\", \"PerformanceNavigationTiming interface object length\", \"PerformanceNavigationTiming interface object name\", \"PerformanceNavigationTiming interface: existence and properties of interface prototype object\", \"PerformanceNavigationTiming interface: existence and properties of interface prototype object's \"constructor\" property\", \"PerformanceNavigationTiming interface: existence and properties of interface prototype object's @@unscopables property\", \"PerformanceNavigationTiming interface: attribute unloadEventStart\", \"Unscopable handled correctly for unloadEventStart property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: attribute unloadEventEnd\", \"Unscopable handled correctly for unloadEventEnd property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: attribute domInteractive\", \"Unscopable handled correctly for domInteractive property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: attribute domContentLoadedEventStart\", \"Unscopable handled correctly for domContentLoadedEventStart property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: attribute domContentLoadedEventEnd\", \"Unscopable handled correctly for domContentLoadedEventEnd property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: attribute domComplete\", \"Unscopable handled correctly for domComplete property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: attribute loadEventStart\", \"Unscopable handled correctly for loadEventStart property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: attribute loadEventEnd\", \"Unscopable handled correctly for loadEventEnd property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: attribute type\", \"Unscopable handled correctly for type property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: attribute redirectCount\", \"Unscopable handled correctly for redirectCount property on PerformanceNavigationTiming\", \"PerformanceNavigationTiming interface: operation toJSON()\", \"Unscopable handled correctly for toJSON() on PerformanceNavigationTiming\", \"PerformanceNavigationTiming must be primary interface of performance.getEntriesByType(\"navigation\")[0]\", \"Stringification of performance.getEntriesByType(\"navigation\")[0]\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"unloadEventStart\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"unloadEventEnd\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"domInteractive\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"domContentLoadedEventStart\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"domContentLoadedEventEnd\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"domComplete\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"loadEventStart\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"loadEventEnd\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"type\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"redirectCount\" with the proper type\", \"PerformanceNavigationTiming interface: performance.getEntriesByType(\"navigation\")[0] must inherit property \"toJSON()\" with the proper type\"", "stack": null, "subtest": null, "test": "/navigation-timing/idlharness.window.html", "line": 177677, "action": "test_result", "expected": "OK"}
```
And indeed, running it, the `PerformanceNavigationTiming` tests are run twice, and `this.tested` is `undefined` on both runs.

### PR DESCRIPTION
**Pull request by saschanaz**
Enable `[Default] toJSON()` lines that were previously commented out.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #21274

- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24097)

### CODE REVIEW

**Comment by saschanaz** [comment]
@cybai Do you know how can I update wpt metadata automatically? I tried updating by `./mach test-wpt --log-raw servo.log navigation-timing/idlharness.window.html` and then `./mach update-wpt servo.log` but it doesn't do anything on my machine.

**Comment by CYBAI** [comment]
> @CYBAI Do you know how can I update wpt metadata automatically? I tried updating by `./mach test-wpt --log-raw servo.log navigation-timing/idlharness.window.html` and then `./mach update-wpt servo.log` but it doesn't do anything on my machine.

That command looks right and I just checked [previous `try` result](https://build.servo.org/builders/linux-rel-css/builds/13247/steps/shell__4/logs/filtered-wpt-errorsummary.log).

It seems `navigation-timing/idlharness.window.html` is not in the filtered error 😂

Btw, if you want to use the result from homu directly, you can try commands like following next time 👀

```sh
$ wget https://build.servo.org/builders/linux-rel-css/builds/13247/steps/test/logs/test-wpt.log/text
$ ./mach update-wpt text
```

**Comment by saschanaz** [comment]
@bors-servo try=wpt

I'm abusing homu this time...

**Comment by saschanaz** [comment]
I expected `update-wpt` to update `tests/wpt/metadata/navigation-timing/idlharness.window.js.ini` but somehow it doesn't touch the file, even if I get the input log directly from homu: https://build.servo.org/builders/linux-rel-wpt/builds/13309/steps/test__1/logs/test-wpt.log/text

**Comment by CYBAI** [comment]
> I expected `update-wpt` to update `tests/wpt/metadata/navigation-timing/idlharness.window.js.ini` but somehow it doesn't touch the file but only other files, even if I get the input log directly from homu: https://build.servo.org/builders/linux-rel-wpt/builds/13309/steps/test__1/logs/test-wpt.log/text

Oh! I saw [this change](https://github.com/servo/servo/pull/24097/commits/7ec1163581570745e5b3ca2d44b87b29b88a43c1#diff-3fc2b7f5f596c6c28a4bbd7254b25d8dL2)!

The test was disabled so the test wasn't run.

**Comment by saschanaz** [comment]
>The test was disabled so the test wasn't run.

Right, and the problem is `update-wpt` doesn't work even if I enable the test and the log includes relevant failures 🤔

**Comment by saschanaz** [comment]
@bors-servo try=wpt

Everything should be okay now.

**Comment by CYBAI** [comment]
If this PR fixes #21274 that the tests won't be run twice, maybe you can update the 3rd checkbox in PR description to `These changes fix #21274` so that the issue can be closed automatically after this PR merged 👀?

**Comment by saschanaz** [comment]
I think it has been fixed for a while, but sure!

**Review by Manishearth — APPROVED** [review]
r=me with squash

**Pull request merged**
