### PR TITLE
Let resources timing entries be added to performance entry buffer.

### PR DESCRIPTION
**Pull request by gatoWololo**
Update relevant tests to properly report and expect failure.

These changes are the first step for #23328. Not sure if I would say they _fix_ the issue.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [X] There are tests for these changes: Existing tests have been updated to expect pass/failures.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23536)

### CODE REVIEW

**Comment by jdm** [comment]
Looks like a few more test results changed:
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "uncaught exception: unknown (can't convert to string)", 
    "stack": "image_was_loaded/<@http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/srcset/avoid-reload-on-resize.html:15:5\nstep_timeout/<@http://web-platform.test:8000/resources/testharness.js:806:13\n", 
    "subtest": "Avoid srcset image reloads when viewport resizes", 
    "test": "/html/semantics/embedded-content/the-img-element/srcset/avoid-reload-on-resize.html", 
    "line": 179867, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: expected 1 but got 3", 
    "stack": "request.onload<@http://web-platform.test:8000/_mozilla/mozilla/xmlhttprequest_url.html:22:5\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20\nTest.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1634:17\n", 
    "subtest": "Performance entries should contain the URL where the XMLHttpRequest originated", 
    "test": "/_mozilla/mozilla/xmlhttprequest_url.html", 
    "line": 302755, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: clearResourceTimings cleared the resource timings expected 0 but got 1", 
    "stack": "testPerformanceClearResourceTimings@http://web-platform.test:8000/workers/worker-performance.worker.js:95:5\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\n@http://web-platform.test:8000/workers/worker-performance.worker.js:93:1\n", 
    "subtest": "performance.clearResourceTimings in workers", 
    "test": "/workers/worker-performance.worker.html", 
    "line": 302815, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: setResourceTimingBufferSize(0) prevents resource entries from being added expected 0 but got 2", 
    "stack": "testPerformanceSetResourceTimingBufferSize@http://web-platform.test:8000/workers/worker-performance.worker.js:103:5\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\n@http://web-platform.test:8000/workers/worker-performance.worker.js:98:1\n", 
    "subtest": "performance.setResourceTimingBufferSize in workers", 
    "test": "/workers/worker-performance.worker.html", 
    "line": 302816, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Comment by jdm** [comment]
`/xmlhttprequest_url.html` should be updated to accommodate the new changes. I expressed surprise that it passed in https://github.com/servo/servo/pull/23372#discussion_r286965287, and I'm glad to see that this change makes it behave as I expected.

**Comment by gatoWololo** [comment]
This pull request has been marked as `Queued` since last Friday without any progress. I'm pretty sure it's stuck?

**Comment by jdm** [comment]
Indeed! Good thing the TravisCI tests are just early-warning systems instead of mission-critical.
@bors-servo r+

**Comment by jdm** [comment]
```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "getEntriesByName values are case sensitive", 
    "test": "/performance-timeline/case-sensitivity.any.html", 
    "line": 202256, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: Import should not be in timeline expected 0 but got 1", 
    "stack": "@http://web-platform.test:8000/resource-timing/no-entries-for-cross-origin-css-fetched.sub.html:30:11\nTest.prototype.step_timeout/<@http://web-platform.test:8000/resources/testharness.js:1652:20\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1618:20\n", 
    "subtest": "Make sure that resources fetched by cross origin CSS are not in the timeline.", 
    "test": "/resource-timing/no-entries-for-cross-origin-css-fetched.sub.html", 
    "line": 229332, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Comment by gatoWololo** [comment]
@jdm I'm having a hard time figuring out which tests need to be marked as "expected failure" versus have the actual tests values updated.

For example:
```
    "subtest": "Make sure that resources fetched by cross origin CSS are not in the timeline.", 
    "test": "/resource-timing/no-entries-for-cross-origin-css-fetched.sub.html", 
```
This seems like a regression? So do I mark it as expected failure. It seems like changing from `false` to `true` fixed some things but broke others? Or am I thinking of it wrong.

For the first test we can just get rid of the expected failure?

New test failures keep popping up, I think it's because I haven't done a big `./mach test-wpt --release`. I tried at one point but I saw 20k+ tests which was taking forever. I general, should I do this locally before pull requesting, or let the CI handle it and update tests results as needed? It's also hard to do it locally, since I get a some random test failures, which I assume are intermittent failures I should ignore? It's hard to tell though.

**Comment by asajeffrey** [comment]
I usually let CI do the big `test-wpt`, and just do targeted ones locally. In this case that would be `./mach test-wpt --release /resource-timing`.

**Comment by gatoWololo** [comment]
Okay. I'll fix those tests before pushing again. Thanks.

**Comment by jdm** [comment]
@gatoWololo "This seems like a regression?" Strictly, yes, in that our implementation previously did not report cross-origin CSS timing information and now does. Since that was a side-effect of the fact that our implementation did not report timing information for any resources at all, I choose not to insist that we need to implement the missing cross-origin CSS checks before merging these changes.

**Comment by gatoWololo** [comment]
@jdm That makes sense thanks. I was just worried about erroneously modifying the tests.

**Comment by gatoWololo** [comment]
Well, this is fun. Calling `./mach test-wpt --release /performance-timeline` several times. It randomly passes half the time, fails the other half.
Passes:
```
gatowololo@omar-mozilla ~/M/servo> ./mach test-wpt --release /performance-timeline
...
Running 32 tests in web-platform-tests

Ran 32 tests finished in 15.0 seconds.
  • 32 ran as expected. 0 tests skipped.
```

Fails:
```
gatowololo@omar-mozilla ~/M/servo> ./mach test-wpt --release /performance-timeline
Running 32 tests in web-platform-tests

  ▶ Unexpected subtest result in /performance-timeline/webtiming-resolution.any.worker.html:
  │ FAIL [expected PASS] Verifies the resolution of performance.now() is at least 5 microseconds.
  │   → assert_greater_than_equal: The second performance.now() should be much greater than the first expected a number greater than or equal to 0.0049900000000000005 but got 0.002425000000002342
  │ 
  │ testTimeResolution/<@http://web-platform.test:8000/performance-timeline/webtiming-resolution.any.js:9:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20
  │ test@http://web-platform.test:8000/resources/testharness.js:544:21
  │ testTimeResolution@http://web-platform.test:8000/performance-timeline/webtiming-resolution.any.js:2:5
  │ @http://web-platform.test:8000/performance-timeline/webtiming-resolution.any.js:24:1
  └ @http://web-platform.test:8000/performance-timeline/webtiming-resolution.any.worker.js:8:1

Ran 32 tests finished in 15.0 seconds.
  • 31 ran as expected. 0 tests skipped.
  • 1 tests had unexpected subtest results
```

**Comment by jdm** [comment]
That's a known intermittent failure: https://github.com/servo/servo/issues/21276

**Comment by asajeffrey** [comment]
Searching the github repo for wpt test names quite often finds the right intermittent.

**Comment by CYBAI** [comment]
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: responseEnd should not be 0 in timing-allow cross-origin request. expected true got false", 
    "stack": "test_greater_than/<@http://web-platform.test:8000/resource-timing/resources/webperftestharness.js:141:27\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\nwp_test@http://web-platform.test:8000/resource-timing/resources/webperftestharness.js:57:5\ntest_greater_than@http://web-platform.test:8000/resource-timing/resources/webperftestharness.js:141:5\nonload_test@http://web-platform.test:8000/resource-timing/resource_TAO_origin.htm:43:5\n", 
    "subtest": "responseEnd should not be 0 in timing-allow cross-origin request.", 
    "test": "/resource-timing/resource_TAO_origin.htm", 
    "line": 66551, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: responseEnd should be greater than 0 in cross-origin request. expected true got false", 
    "stack": "test_greater_than/<@http://web-platform.test:8000/resource-timing/resources/webperftestharness.js:141:27\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\nwp_test@http://web-platform.test:8000/resource-timing/resources/webperftestharness.js:57:5\ntest_greater_than@http://web-platform.test:8000/resource-timing/resources/webperftestharness.js:141:5\nonload_test@http://web-platform.test:8000/resource-timing/resource_TAO_zero.htm:42:5\n", 
    "subtest": "responseEnd should be greater than 0 in cross-origin request.", 
    "test": "/resource-timing/resource_TAO_zero.htm", 
    "line": 70352, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Comment by jdm** [comment]
I wonder if those are new intermittent results...

**Comment by jdm** [comment]
@bors-servo retry
 #23625

**Pull request merged**
