### PR TITLE
Update bindings

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17367)

### CODE REVIEW

**Comment by Manishearth** [comment]
cc @emilio 

This may fail the nsPresContext layout test on CI. Does fail locally on osx for me. Probably a bindgen bug.

**Comment by jdm** [comment]
```
failures:
    bindings::root::bindgen_test_layout_nsPresContext
    bindings::root::bindgen_test_layout_nsRootPresContext
```

**Comment by Manishearth** [comment]
Ok, thought so. cc @emilio @fitzgen

**Comment by Manishearth** [comment]
When I remove the sizeof assertions, I get:

<details>
```
---- bindings::root::bindgen_test_layout_nsPresContext stdout ----
	thread 'bindings::root::bindgen_test_layout_nsPresContext' panicked at 'assertion failed: `(left == right)` (left: `1316`, right: `1314`): Alignment of field: nsPresContext::mRestyleLoggingEnabled', /Users/manishearth/mozilla/sneutrino/target/geckolib/debug/build/style-213285628ceb0759/out/gecko/structs_debug.rs:19922
stack backtrace:
   1:        0x10bde176c - std::sys::imp::backtrace::tracing::imp::write::h21ca2762819c7ae8
   2:        0x10bde375e - std::panicking::default_hook::{{closure}}::h38f99a37d00bb19b
   3:        0x10bde3303 - std::panicking::default_hook::ha2186ee24b50729c
   4:        0x10bde3c17 - std::panicking::rust_panic_with_hook::h979db19ee91d2a53
   5:        0x10bde3ac4 - std::panicking::begin_panic::h6a69f5b54391c64d
   6:        0x10bde39e2 - std::panicking::begin_panic_fmt::h9de2343580b3c2c4
   7:        0x10bcb12ac - stylo_tests::bindings::root::bindgen_test_layout_nsPresContext::h3bc4d854c0f1fd86
   8:        0x10bdb237e - <F as test::FnBox<T>>::call_box::h911d6e7479d078b1
   9:        0x10bde4afa - __rust_maybe_catch_panic
  10:        0x10bda6858 - std::panicking::try::do_call::h3431891132b0ee14
  11:        0x10bde4afa - __rust_maybe_catch_panic
  12:        0x10bdad5be - <F as alloc::boxed::FnBox<A>>::call_box::h2e47f51b54ac05cf
  13:        0x10bde2e34 - std::sys::imp::thread::Thread::new::thread_start::hca57ad22492f366f
  14:     0x7fff9a09999c - _pthread_body
  15:     0x7fff9a099919 - _pthread_start

---- bindings::root::bindgen_test_layout_nsRootPresContext stdout ----
	thread 'bindings::root::bindgen_test_layout_nsRootPresContext' panicked at 'assertion failed: `(left == right)` (left: `1336`, right: `1328`): Alignment of field: nsRootPresContext::mNotifyDidPaintTimers', /Users/manishearth/mozilla/sneutrino/target/geckolib/debug/build/style-213285628ceb0759/out/gecko/structs_debug.rs:26041
stack backtrace:
   1:        0x10bde176c - std::sys::imp::backtrace::tracing::imp::write::h21ca2762819c7ae8
   2:        0x10bde375e - std::panicking::default_hook::{{closure}}::h38f99a37d00bb19b
   3:        0x10bde3303 - std::panicking::default_hook::ha2186ee24b50729c
   4:        0x10bde3c17 - std::panicking::rust_panic_with_hook::h979db19ee91d2a53
   5:        0x10bde3ac4 - std::panicking::begin_panic::h6a69f5b54391c64d
   6:        0x10bde39e2 - std::panicking::begin_panic_fmt::h9de2343580b3c2c4
   7:        0x10bcddaba - stylo_tests::bindings::root::bindgen_test_layout_nsRootPresContext::h556c85a99f890809
   8:        0x10bdb237e - <F as test::FnBox<T>>::call_box::h911d6e7479d078b1
   9:        0x10bde4afa - __rust_maybe_catch_panic
  10:        0x10bda6858 - std::panicking::try::do_call::h3431891132b0ee14
  11:        0x10bde4afa - __rust_maybe_catch_panic
  12:        0x10bdad5be - <F as alloc::boxed::FnBox<A>>::call_box::h2e47f51b54ac05cf
  13:        0x10bde2e34 - std::sys::imp::thread::Thread::new::thread_start::hca57ad22492f366f
  14:     0x7fff9a09999c - _pthread_body
  15:     0x7fff9a099919 - _pthread_start
```

</details>

Basically, everything after and including `mRestyleLoggingEnabled` is broken, because the [44-bit bitfield](https://dxr.mozilla.org/mozilla-central/source/layout/base/nsPresContext.h#1431-1503) before it doesn't have the right size/alignment.

**Comment by emilio** [comment]
So this was uncovered by https://github.com/servo/rust-bindgen/pull/736, but the bitfield offsets were wrong before. In particular, this is a case of https://github.com/servo/rust-bindgen/issues/734.

I'd think until we figure out a good way to do that in bindgen, it's easier to just work around it on Gecko. Should be trivial, I'll write a patch.

**Comment by emilio** [comment]
Multiple binding updates have landed in the meantime, so I think this can be closed.

**Pull request closed without merging**
