### PR TITLE
Add Origin header to WebSocket connections.

### PR DESCRIPTION
**Pull request by jdm**
Closes #6532.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6611)

### CODE REVIEW

**Comment by jdm** [comment]
What the heck:
```
failures:
    ../html/acid2.html != acid2_ref.html
    absolute_inline_containing_block_a.html == absolute_inline_containing_block_ref.html
    acid1_a.html == acid1_b.html
    acid2_noscroll.html == acid2_ref_broken.html
    after_block_iteration.html == after_block_iteration_ref.html
    alpha_gif_a.html == alpha_gif_b.html
    alpha_png_a.html == alpha_png_b.html
    anon_block_inherit_a.html == anon_block_inherit_b.html
    append_style_a.html == append_style_b.html
    attr_exists_selector.html == attr_exists_selector_ref.html
    attr_selector_case_sensitivity.html == attr_selector_case_sensitivity_ref.html
    background_clip_a.html == background_clip_ref.html
    background_external_stylesheet.html == background_ref.html
    background_image_position_a.html == background_image_position_ref.html
    background_none_a.html == background_none_b.html
    background_origin_a.html == background_origin_ref.html
    background_position_a.html == background_position_b.html
    background_position_keyword.html == background_position_b.html
    background_position_percent.html == background_position_b.html
    background_position_shorthand.html == background_position_shorthand_ref.html
    background_repeat_both_a.html == background_repeat_both_b.html
    background_repeat_none_a.html == background_repeat_none_b.html
    background_repeat_x_a.html == background_repeat_x_b.html
    background_repeat_y_a.html == background_repeat_y_b.html
    background_size_a.html == background_size_ref.html
    background_size_shorthand_a.html == background_size_shorthand_ref.html
    background_style_attr.html == background_ref.html
    basic_width_px.html == basic_width_em.html
    block-formatting-contexts-005.htm == block-formatting-contexts-005-ref.htm
    block-formatting-contexts-006.htm == block-formatting-contexts-006-ref.htm
    block_formatting_context_a.html == block_formatting_context_ref.html
    block_formatting_context_cleared_float_a.html == block_formatting_context_cleared_float_ref.html
    block_formatting_context_complex_a.html == block_formatting_context_complex_ref.html
    block_formatting_context_containing_floats_a.html == block_formatting_context_containing_floats_ref.html
    block_formatting_context_float_placement_a.html == block_formatting_context_float_placement_ref.html
    block_formatting_context_relative_a.html == block_formatting_context_ref.html
    block_formatting_context_translation_a.html == block_formatting_context_translation_ref.html
    block_image.html != noteq_500x300_white.html
    block_image.html == 500x300_green.html
    block_replaced_content_a.html == block_replaced_content_ref.html
    block_replaced_content_b.html == block_replaced_content_ref.html
    blur_a.html == blur_ref.html
    border_black_groove.html != border_black_solid.html
    border_black_ridge.html != border_black_groove.html
    border_black_ridge.html != border_black_solid.html
    border_code_tag.html == border_code_tag_ref.html
    border_collapse_missing_cell_a.html == border_collapse_missing_cell_ref.html
    border_collapse_simple_a.html == border_collapse_simple_ref.html
    border_radius_clip_a.html == border_radius_clip_ref.html
    border_radius_overlapping_a.html == border_radius_overlapping_ref.html
    border_spacing_a.html == border_spacing_ref.html
    border_spacing_auto_layout_a.html == border_spacing_ref.html
    border_spacing_empty_table.html == border_spacing_empty_table_ref.html
    border_spacing_fixed_layout_a.html == border_spacing_ref.html
    border_style_none_a.html == border_style_none_b.html
    borders_a.html == borders_b.html
    box_shadow_blur_a.html != box_shadow_blur_ref.html
    box_shadow_border_box_a.html == box_shadow_border_box_ref.html
    box_shadow_default_color_a.html == box_shadow_default_color_ref.html
    box_shadow_inset_a.html == box_shadow_inset_ref.html
    box_shadow_inset_parsing_a.html == box_shadow_inset_parsing_ref.html
    box_shadow_paint_order_a.html == box_shadow_paint_order_ref.html
    box_shadow_spread_a.html == box_shadow_spread_ref.html
    box_sizing_border_box_a.html == box_sizing_border_box_ref.html
    box_sizing_sanity_check_a.html == box_sizing_sanity_check_ref.html
    br.html == br-ref.html
    canvas_as_block_element_a.html == canvas_as_block_element_ref.html
    case-insensitive-font-family.html == case-insensitive-font-family-ref.html
    clear_generated_content_table_a.html == clear_generated_content_table_ref.html
    clip_a.html == clip_ref.html
    counters_nested_a.html == counters_nested_ref.html
    counters_simple_a.html == counters_simple_ref.html
    data_img_a.html == data_img_b.html
    empty_cells_a.html == empty_cells_ref.html
    external_media_query_link.html == external_media_query_ref.html
    external_media_query_style.html == external_media_query_ref.html
    filter_inline_a.html == filter_inline_ref.html
    filter_opacity_a.html == filter_opacity_ref.html
    filter_sepia_a.html == filter_sepia_ref.html
    first_child_pseudo_a.html == first_child_pseudo_b.html
    first_of_type_pseudo_a.html == first_of_type_pseudo_b.html
    fixed_width_overrides_child_intrinsic_width_a.html == fixed_width_overrides_child_intrinsic_width_ref.html
    float_clearance_a.html == float_clearance_ref.html
    float_clearance_intrinsic_width_a.html == float_clearance_intrinsic_width_ref.html
    float_intrinsic_height.html == float_intrinsic_height_ref.html
    float_intrinsic_width_a.html == float_intrinsic_width_ref.html
    float_overflow_area_a.html == float_overflow_area_ref.html
    float_right_intrinsic_width_a.html == float_right_intrinsic_width_ref.html
    float_table_a.html == float_table_ref.html
    float_under_top_margin_a.html == float_under_top_margin_ref.html
    floated_generated_content_a.html == floated_generated_content_b.html
    floated_list_item_a.html == floated_list_item_ref.html
    floated_table_with_margin_a.html == floated_table_with_margin_ref.html
    focus_selector.html == focus_selector_ref.html
    font_advance.html == font_advance_ref.html
    font_color_attribute_a.html == font_color_attribute_ref.html
    font_size.html == font_size_ref.html
    font_style.html == font_style_ref.html
    height_compute_reset.html == height_compute.html
    hello_a?foo#bar.html == hello_b.html
    hide_after_create.html == hide_after_create_ref.html
    iframe/bg_color.html == iframe/bg_color_ref.html
    iframe/hide_and_show.html == iframe/hide_and_show_ref.html
    iframe/hide_layers1.html == iframe/hide_layers_ref.html
    iframe/hide_layers2.html == iframe/hide_layers_ref.html
    iframe/multiple_external.html == iframe/multiple_external_ref.html
    iframe/overflow.html == iframe/overflow_ref.html
    iframe/positioning_margin.html == iframe/positioning_margin_ref.html
    iframe/simple.html == iframe/simple_ref.html
    iframe/simple_inline_default.html == iframe/simple_inline_default_ref.html
    iframe/simple_inline_height.html == iframe/simple_inline_height_ref.html
    iframe/simple_inline_max.html == iframe/simple_inline_max_ref.html
    iframe/simple_inline_min.html == iframe/simple_inline_min_ref.html
    iframe/simple_inline_width.html == iframe/simple_inline_width_ref.html
    iframe/simple_inline_width_height.html == iframe/simple_inline_width_height_ref.html
    iframe/simple_inline_width_percentage.html == iframe/simple_inline_width_percentage_ref.html
    iframe/size_attributes.html == iframe/size_attributes_ref.html
    iframe/size_attributes_vertical_writing_mode.html == iframe/size_attributes_ref.html
    image_rendering_auto_a.html != image_rendering_pixelated_a.html
    image_rendering_pixelated_a.html == image_rendering_pixelated_ref.html
    img_block_display_a.html == img_block_display_ref.html
    img_block_maxwidth_a.html == img_block_maxwidth_ref.html
    img_block_maxwidth_b.html == img_block_maxwidth_ref.html
    img_dynamic_remove.html == img_dynamic_remove_ref.html
    img_padding_a.html == img_padding_b.html
    img_simple.html != img_simple_ref.html
    img_size_a.html == img_size_b.html
    img_width_attribute_intrinsic_width_a.html == img_width_attribute_intrinsic_width_ref.html
    incremental_float_a.html == incremental_float_ref.html
    incremental_inline_layout_a.html == incremental_inline_layout_ref.html
    inline_background_a.html != inline_background_ref.html
    inline_block_baseline_a.html == inline_block_baseline_ref.html
    inline_block_block_direction_margins_a.html == inline_block_block_direction_margins_ref.html
    inline_block_border_a.html == inline_block_border_ref.html
    inline_block_border_intrinsic_size_a.html == inline_block_border_intrinsic_size_ref.html
    inline_block_img_a.html == inline_block_img_ref.html
    inline_block_margin_a.html == inline_block_margin_ref.html
    inline_block_min_width.html == inline_block_min_width_ref.html
    inline_block_overflow.html == inline_block_overflow_ref.html
    inline_block_overflow_hidden_a.html == inline_block_overflow_hidden_ref.html
    inline_block_parent_padding_a.html == inline_block_parent_padding_ref.html
    inline_block_parent_width.html == inline_block_parent_width_ref.html
    inline_block_parent_width_percentage.html == inline_block_parent_width_ref.html
    inline_block_percentage_height_a.html == inline_block_percentage_height_ref.html
    inline_block_stacking_context_a.html == inline_block_stacking_context_ref.html
    inline_block_with_margin_a.html == inline_block_with_margin_ref.html
    inline_element_border_a.html == inline_element_border_ref.html
    inline_hypothetical_box_a.html == inline_hypothetical_box_ref.html
    inline_margin_multiple_fragments_a.html == inline_margin_multiple_fragments_ref.html
    inline_margins_a.html == inline_margins_ref.html
    inline_padding_a.html == inline_padding_b.html
    inline_whitespace_a.html == inline_whitespace_ref.html
    inline_whitespace_b.html == inline_whitespace_ref.html
    input_button_size_a.html == input_button_size_ref.html
    input_height_a.html != input_height_ref.html
    inset.html == inset_ref.html
    inset_blackborder.html != blackborder_ref.html
    issue-1324.html == issue-1324-ref.html
    jumpiness_a.html == jumpiness_ref.html
    last_child_pseudo_a.html == last_child_pseudo_b.html
    last_of_type_pseudo_a.html == last_of_type_pseudo_b.html
    legacy_cellspacing_attribute_a.html == border_spacing_ref.html
    legacy_input_size_attribute_override_a.html == legacy_input_size_attribute_override_ref.html
    legacy_table_border_attribute_a.html == legacy_table_border_attribute_ref.html
    legacy_td_bgcolor_attribute_a.html == legacy_td_bgcolor_attribute_ref.html
    legacy_td_width_attribute_a.html == legacy_td_width_attribute_ref.html
    letter_spacing_a.html == letter_spacing_ref.html
    line_breaking_whitespace_collapse_a.html == line_breaking_whitespace_collapse_ref.html
    line_height_a.html == line_height_ref.html
    line_height_float_placement_a.html == line_height_float_placement_ref.html
    linear_gradients_corners_a.html != linear_gradients_corners_ref.html
    linear_gradients_lengths_a.html == linear_gradients_lengths_ref.html
    linear_gradients_parsing_a.html == linear_gradients_parsing_ref.html
    linear_gradients_reverse_a.html == linear_gradients_reverse_ref.html
    linear_gradients_smoke_a.html != linear_gradients_smoke_ref.html
    linebreak_inline_span_a.html == linebreak_inline_span_b.html
    linebreak_simple_a.html == linebreak_simple_b.html
    link_style_order.html == link_style_order_ref.html
    list_style_image_sizing_a.html == list_style_image_sizing_ref.html
    list_style_position_a.html == list_style_position_ref.html
    list_style_type_a.html != list_style_type_ref.html
    many_brs_a.html == many_brs_ref.html
    margin_a.html == margin_b.html
    margins_inside_floats_a.html == margins_inside_floats_ref.html
    max_width_float_simple_a.html == max_width_float_simple_b.html
    max_width_simple_a.html == max_width_simple_b.html
    min_max_height_a.html == min_max_height_b.html
    min_width_float_simple_a.html == min_width_float_simple_b.html
    min_width_simple_a.html == min_width_simple_b.html
    minimum_line_height_a.html == minimum_line_height_b.html
    mix_blend_mode_a.html == mix_blend_mode_ref.html
    multiple_css_class_a.html == multiple_css_class_b.html
    negative_margin_uncle_a.html == negative_margin_uncle_b.html
    negative_margins_a.html == negative_margins_b.html
    no-image.html == no-image-ref.html
    no_image_background_a.html == no_image_background_ref.html
    noscript.html == noscript_ref.html
    noteq_attr_exists_selector.html != attr_exists_selector_ref.html
    nth_child_pseudo_a.html == nth_child_pseudo_b.html
    nth_last_child_pseudo_a.html == nth_last_child_pseudo_b.html
    nth_last_of_type_pseudo_a.html == nth_last_of_type_pseudo_b.html
    nth_of_type_pseudo_a.html == nth_of_type_pseudo_b.html
    object_element_a.html == object_element_b.html
    ol_japanese_iroha_a.html == ol_japanese_iroha_ref.html
    ol_japanese_iroha_bullet_styles.html != ol_japanese_iroha_ref.html
    ol_simple_a.html == ol_simple_ref.html
    only_child_pseudo_a.html == only_child_pseudo_b.html
    only_of_type_pseudo_a.html == only_of_type_pseudo_b.html
    opacity_simple_a.html == opacity_simple_ref.html
    opacity_stacking_context_a.html == opacity_stacking_context_ref.html
    outline_offset_a.html == outline_offset_ref.html
    outlines_simple_a.html == outlines_simple_ref.html
    outlines_wrap_a.html == outlines_wrap_ref.html
    outset.html == outset_ref.html
    outset_blackborder.html != blackborder_ref.html
    overconstrained_block.html != overconstrained_block_ref.html
    overflow_auto.html == overflow_simple_b.html
    overflow_scroll.html == overflow_simple_b.html
    overflow_simple_a.html == overflow_simple_b.html
    overflow_wrap_a.html == overflow_wrap_ref.html
    overflow_xy_a.html == overflow_xy_ref.html
    per_glyph_font_fallback_a.html == per_glyph_font_fallback_ref.html
    percent_height.html == percent_height_ref.html
    percentage_height_float_a.html == percentage_height_float_ref.html
    percentage_height_root.html == percentage_height_root_ref.html
    percentage_width_inline_block_a.html == percentage_width_inline_block_ref.html
    png_rgba_colorspace_a.html == png_rgba_colorspace_b.html
    position_abs_cb_with_non_cb_kid_a.html == position_abs_cb_with_non_cb_kid_b.html
    position_abs_height_width_a.html == position_abs_height_width_b.html
    position_abs_left_a.html == position_abs_left_b.html
    position_abs_margin_top_percentage_a.html == position_abs_margin_top_percentage_b.html
    position_abs_nested_a.html == position_abs_nested_b.html
    position_abs_pseudo_a.html == position_abs_pseudo_b.html
    position_abs_replaced_simple_a.html == position_abs_replaced_simple_b.html
    position_abs_static_y_a.html == position_abs_static_y_b.html
    position_abs_width_percentage_a.html == position_abs_width_percentage_b.html
    position_fixed_background_color_a.html == position_fixed_background_color_b.html
    position_fixed_overflow_a.html == position_fixed_overflow_b.html
    position_fixed_tile_edge.html == position_fixed_tile_edge_ref.html
    position_fixed_tile_edge_2.html == position_fixed_tile_edge_ref.html
    position_fixed_tile_edge_3.html == position_fixed_tile_edge_ref.html
    position_relative_a.html == position_relative_b.html
    position_relative_painting_order_a.html == position_relative_painting_order_ref.html
    position_relative_top_percentage_a.html == position_relative_top_percentage_b.html
    pre_ignorable_whitespace_a.html == pre_ignorable_whitespace_ref.html
    pre_with_tab.html == pre_with_tab_ref.html
    pseudo_element_a.html == pseudo_element_b.html
    pseudo_inherit.html == pseudo_inherit_ref.html
    quotes_simple_a.html == quotes_simple_ref.html
    root_height_a.html == root_height_b.html
    root_margin_collapse_a.html == root_margin_collapse_b.html
    root_pseudo_a.html == root_pseudo_b.html
    rtl_body.html == rtl_body_ref.html
    rtl_float_a.html == rtl_float_ref.html
    rtl_margin_a.html == rtl_margin_ref.html
    rtl_simple.html == rtl_simple_ref.html
    rtl_table_a.html == rtl_table_ref.html
    servo_center_a.html == servo_center_ref.html
    setattribute_id_restyle_a.html == setattribute_id_restyle_b.html
    stacking_context_overflow_a.html == stacking_context_overflow_ref.html
    stacking_context_overflow_relative_outline_a.html == stacking_context_overflow_relative_outline_ref.html
    table_auto_width.html == table_auto_width_ref.html
    table_caption_bottom_a.html == table_caption_bottom_ref.html
    table_caption_top_a.html == table_caption_top_ref.html
    table_cell_float_a.html == table_cell_float_ref.html
    table_colspan_fixed_a.html == table_colspan_fixed_ref.html
    table_colspan_simple_a.html == table_colspan_simple_ref.html
    table_containing_block_a.html == table_containing_block_ref.html
    table_expansion_to_fit_a.html == table_expansion_to_fit_ref.html
    table_float_translation_a.html == table_float_translation_ref.html
    table_intrinsic_style_specified_width_a.html == table_intrinsic_style_specified_width_ref.html
    table_margin_auto_a.html == table_margin_auto_ref.html
    table_padding_a.html == table_padding_ref.html
    table_percentage_capping_a.html == table_percentage_capping_ref.html
    table_percentage_width_a.html == table_percentage_width_ref.html
    table_row_direction_a.html == table_row_direction_ref.html
    table_width_attribute_a.html == table_width_attribute_ref.html
    text_align_complex_a.html == text_align_complex_ref.html
    text_align_justify_a.html == text_align_justify_ref.html
    text_align_rtl.html == text_align_rtl_ref.html
    text_align_start_end.html == text_align_start_end_ref.html
    text_decoration_cached.html == text_decoration_cached_ref.html
    text_decoration_smoke_a.html != text_decoration_smoke_ref.html
    text_indent_a.html == text_indent_ref.html
    text_justify_none_a.html == text_justify_none_ref.html
    text_overflow_a.html != text_overflow_ref.html
    text_overflow_basic_a.html == text_overflow_basic_ref.html
    text_shadow_blur_a.html == text_shadow_blur_ref.html
    text_shadow_decorations_a.html == text_shadow_decorations_ref.html
    text_shadow_simple_a.html == text_shadow_simple_ref.html
    text_transform_capitalize_a.html == text_transform_capitalize_ref.html
    text_transform_lowercase_a.html == text_transform_lowercase_ref.html
    text_transform_none_a.html == text_transform_none_ref.html
    text_transform_uppercase_a.html == text_transform_uppercase_ref.html
    transform_3d.html == transform_3d_ref.html
    transform_simple_a.html == transform_simple_ref.html
    transform_stacking_context_a.html == transform_stacking_context_ref.html
    upper_id_attr.html == upper_id_attr_ref.html
    vertical-lr-blocks.html == vertical-lr-blocks_ref.html
    vertical_align_bottom_a.html == vertical_align_bottom_ref.html
    vertical_align_inline_block_a.html == vertical_align_inline_block_ref.html
    vertical_align_inside_table_a.html == vertical_align_inside_table_ref.html
    vertical_align_sub_a.html == vertical_align_sub_ref.html
    vertical_align_super_a.html == vertical_align_super_ref.html
    vertical_align_super_nested_a.html == vertical_align_super_nested_ref.html
    vertical_align_text_bottom_a.html == vertical_align_text_bottom_ref.html
    vertical_align_text_top_a.html == vertical_align_text_top_ref.html
    vertical_align_top_a.html == vertical_align_top_ref.html
    vertical_align_top_bottom_a.html == vertical_align_top_bottom_ref.html
    vertical_align_top_span_a.html == vertical_align_top_span_ref.html
    viewport_percentage_vmin_vmax.html == viewport_percentage_vmin_vmax_a.html
    viewport_percentage_vw_vh.html == viewport_percentage_vw_vh_a.html
    viewport_rule.html == viewport_rule_ref.html
    visibility_hidden.html == visibility_hidden_ref.html
    webgl-context/clearcolor.html == webgl-context/clearcolor_ref.html
    webgl-context/draw_arrays_simple.html == webgl-context/draw_arrays_simple_ref.html
    whitespace_nowrap_a.html == whitespace_nowrap_ref.html
    whitespace_pre.html == whitespace_pre_ref.html
    width_nonreplaced_block_simple_a.html == width_nonreplaced_block_simple_b.html
    word_break_a.html == word_break_ref.html
    word_spacing_a.html == word_spacing_ref.html

test result: FAILED. 0 passed; 321 failed; 0 ignored; 0 measured
```

**Comment by Ms2ger** [comment]
@bors-servo retry
* #6619

**Pull request merged**
