### PR TITLE
Factor out a UrlOrNone type for -moz-binding and list-style-image to use

### PR DESCRIPTION
**Pull request by heycam**
r? @Manishearth 

---

- [x] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13715)

### CODE REVIEW

**Comment by jdm** [comment]
```
error: attempted tuple index `0` on type `style::values::computed::UrlOrNone`, but the type was not a tuple or tuple struct
    --> /Users/servo/buildbot/slave/mac-dev-unit/build/components/layout/construct.rs:1267:38
     |
1267 |         let marker_fragments = match node.style(self.style_context()).get_list().list_style_image.0 {
     |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by heycam** [comment]
Servo itself is building locally for me now with these changes.

**Comment by heycam** [comment]
Rebased.

**Pull request merged**
