### PR TITLE
Update Tetsuharu OHZEKI's entry in mailmap

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
I no longer use these mail addresses (the former is still reachable but I cannot access to the later one). I'll update them with reachable one by myself.

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by saneyuki** [comment]
Ugh, is this random failure...?

-----

@jdm  thank you for your review!

**Comment by CYBAI** [comment]
@bors-servo retry

(@saneyuki yes, that's #23290)

**Comment by saneyuki** [comment]
@CYBAI aha, thank you.

**Comment by jdm** [comment]
@CYBAI #23290 is only for mac reftest failures. Linux ones are probably #24726.

**Comment by CYBAI** [comment]
@jdm argh!! thanks for pointing that out!

**Pull request merged**
