### PR TITLE
Update rustc to latest nightly.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by CYBAI** [comment]
I'm so confused why @servo-wpt-sync is triggered for this PR 🤔

**Comment by jdm** [comment]
I think that's happening because I need to regenerate the access tokens that servo-wpt-sync uses.

**Comment by jdm** [comment]
https://github.com/rust-lang/rust/issues/88764

**Comment by CYBAI** [comment]
Build fail on Windows UWP jobs 👀 

```
error[E0599]: no method named `raw` found for struct `Handle` in the current scope
   --> C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\fs.rs:360:29
    |
360 |                 self.handle.raw(),
    |                             ^^^ method not found in `Handle`
    |
   ::: C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\handle.rs:17:1
    |
17  | pub struct Handle(OwnedHandle);
    | ------------------------------- method `raw` not found for this

error[E0599]: no method named `raw` found for struct `Handle` in the current scope
   --> C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\fs.rs:388:29
    |
388 |                 self.handle.raw(),
    |                             ^^^ method not found in `Handle`
    |
   ::: C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\handle.rs:17:1
    |
17  | pub struct Handle(OwnedHandle);
    | ------------------------------- method `raw` not found for this

error[E0599]: no function or associated item named `new` found for struct `Handle` in the current scope
  --> C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\stdio_uwp.rs:28:26
   |
28 |     let handle = Handle::new(handle);
   |                          ^^^ function or associated item not found in `Handle`
   |
  ::: C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\handle.rs:17:1
   |
17 | pub struct Handle(OwnedHandle);
   | ------------------------------- function or associated item `new` not found for this

error[E0599]: no method named `write` found for struct `ManuallyDrop<_>` in the current scope
    --> C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\stdio_uwp.rs:29:31
     |
29   |     ManuallyDrop::new(handle).write(data)
     |                               ^^^^^ method not found in `ManuallyDrop<_>`
     |
     = note: `ManuallyDrop::new(handle)` is a function, perhaps you wish to call it
     = help: items from traits can only be used if the trait is implemented and in scope
note: `io::Write` defines an item `write`, perhaps you need to implement it
    --> C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\io\mod.rs:1368:1
     |
1368 | pub trait Write {
     | ^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `new` found for struct `Handle` in the current scope
  --> C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\stdio_uwp.rs:41:30
   |
41 |         let handle = Handle::new(handle);
   |                              ^^^ function or associated item not found in `Handle`
   |
  ::: C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\handle.rs:17:1
   |
17 | pub struct Handle(OwnedHandle);
   | ------------------------------- function or associated item `new` not found for this

error[E0599]: no method named `read` found for struct `ManuallyDrop<_>` in the current scope
   --> C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\stdio_uwp.rs:42:35
    |
42  |         ManuallyDrop::new(handle).read(buf)
    |                                   ^^^^ method not found in `ManuallyDrop<_>`
    |
    = note: `ManuallyDrop::new(handle)` is a function, perhaps you wish to call it
    = help: items from traits can only be used if the trait is implemented and in scope
note: `io::Read` defines an item `read`, perhaps you need to implement it
   --> C:\Rust\.rustup\toolchains\nightly-2021-09-06-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\io\mod.rs:520:1
    |
520 | pub trait Read {
    | ^^^^^^^^^^^^^^
```

**Comment by jdm** [comment]
Yep, I filed a rust-lang issue about it per https://github.com/servo/servo/pull/28591#issuecomment-915592400.

**Comment by CYBAI** [comment]
ah, I see! thank you! 🙏

**Comment by jdm** [comment]
https://github.com/rust-lang/rust/pull/88587 just merged so this can update to a newer nightly.

**Comment by jdm** [comment]
Oh, the errors come from having an empty PR body :)

**Pull request merged**
