### PR TITLE
Simplify and fix iteration over radio button group

### LINKED ISSUE #25486: Detached radio buttons do not propagate their checkedness
Radio buttons in subtrees detached from document do not synchronize their checkedness. Consider this example:

```html
<script>
let form = document.createElement("form");
let radios = [];

for (let i = 0; i < 3; i++) {
    let elem = document.createElement("input");
    elem.type = "radio";
    elem.name = "my_group";
    form.appendChild(elem);
    radios.push(elem);
}

for (let elem of radios) {
    elem.checked = true;
}

for (let elem of radios) {
    document.write(elem.checked + " ");
}
</script>
```

Expected result is `false false true`, Servo outputs `true true true`.

### PR DESCRIPTION
**Pull request by teapotd**
- Code for iterating over radio button group elements has been extracted to `radio_group_iter`
- `in_same_group` now checks if elements are in the same tree
- `radio_group_name` returns `None` if name is empty
- Radio buttons now group together in orphan trees (#25486)

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25486
- [ ] There are tests for these changes

### CODE REVIEW

**Comment by teapotd** [comment]
There is a test for orphan trees in `html/semantics/forms/the-input-element/radio.html`, but it doesn't pass due to form validation being missing (#25447).

**Comment by jdm** [comment]
That's #24726 and #21067.

**Comment by jdm** [comment]
@Manishearth Review ping.

**Comment by Manishearth** [comment]
@bors-servo r+

Thanks!

**Comment by Manishearth** [comment]
@bors-servo retry

looks like the solid color intermittents again? cc @jdm

**Comment by Manishearth** [comment]
@bors-servo retry

random timeouts?

**Pull request merged**
