### PR TITLE
Add XMLDocument object

### LINKED ISSUE #8000: createDocument method of DOMImplementation should return an XMLDocument
Currently, it returns a Document, which isn't precisely correct according to the spec.

DOMImplementation interface: https://dom.spec.whatwg.org/#domimplementation .

XMLDocument interface: https://dom.spec.whatwg.org/#xmldocument plus https://html.spec.whatwg.org/multipage/dom.html#dom-xmldocument-load .

Fixing this should be straightforward, just a bunch of boilerplate.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #8000

(Still working on it)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8675)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @nox

**Comment by nox** [comment]
Thanks for your contribution!

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/domimplementation.rs, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8675#-K3yhS4LFRn7SIOsBaSW:-K3yhS4LFRn7SIOsBaSX:-2015120370) ([raw file](https://github.com/servo/servo/blob/ba2a672f78b6d897be78f1455b8273495d6b6336/components/script/dom/domimplementation.rs#L76)):*
Nit: reindent the arguments.

---

*[components/script/dom/webidls/XMLDocument.webidl, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8675#-K3yhVfvPNtMP6PoAaeF:-K3yhVfvPNtMP6PoAaeG:-1150701817) ([raw file](https://github.com/servo/servo/blob/ba2a672f78b6d897be78f1455b8273495d6b6336/components/script/dom/webidls/XMLDocument.webidl#L13)):*
`interface Document`? :)
Nit: newline at end of file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8675#-:-K3yhZpIiwCepu0KFtCx:-1584523799)*

**Comment by jdm** [comment]
components/script/dom/xmldocument.rs is missing from this PR.

**Comment by GuillaumeGomez** [comment]
@jdm: It seems that one of my commits hasn't been pushed. I'll add it this evening. But like I said, I have to test a bit more before it can be merged.

**Comment by frewsxcv** [comment]
FYI, according to Travis, this fails to compile

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/layout/wrapper.rs, line 635 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8675#-K432-TQgvGEwSk1sKPu:-K432-TQgvGEwSk1sKPv:-2051120495) ([raw file](https://github.com/servo/servo/blob/cd1ba4c2ec1445afee07b3f08d65da40381135da/components/layout/wrapper.rs#L635)):*
Nit: Put the clause body in a block, and the match expressions in that block on a new line.

---

*[components/script/dom/document.rs, line 1395 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8675#-K4326OFqTNC_PuRjGti:-K4326OFqTNC_PuRjGtj:-1825940193) ([raw file](https://github.com/servo/servo/blob/cd1ba4c2ec1445afee07b3f08d65da40381135da/components/script/dom/document.rs#L1395)):*
Nit: realign the other arguments.

---

*[components/script/dom/webidls/DOMImplementation.webidl, line 20 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8675#-K436NgXTUv40Tc8jgwJ:-K436NgXTUv40Tc8jgwK:-1545097428) ([raw file](https://github.com/servo/servo/blob/cd1ba4c2ec1445afee07b3f08d65da40381135da/components/script/dom/webidls/DOMImplementation.webidl#L20)):*
Nit: align the other arguments.

---

*[components/script/dom/xmldocument.rs, line 50 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8675#-K436UaLSQQR5ad01P9I:-K436UaLSQQR5ad01P9J:144402208) ([raw file](https://github.com/servo/servo/blob/cd1ba4c2ec1445afee07b3f08d65da40381135da/components/script/dom/xmldocument.rs#L50)):*
Some arguments here can probably be elided, can you look into it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8675#-:-K436ZnASaRsQkTczusO:1458266033)*

**Comment by nox** [comment]
This just needs to have test expectations fixed and this is good to go.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/xmldocument.rs, line 50 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8675#-K436UaLSQQR5ad01P9I:-K44QQ6X3Aj82WLqMjX3:-440631314) ([raw file](https://github.com/servo/servo/blob/cd1ba4c2ec1445afee07b3f08d65da40381135da/components/script/dom/xmldocument.rs#L50)):*
Please file a follow-up issue about it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8675#-:-K44QXDz7O1ut98E6Zah:1873100291)*

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8675#-:-K45K2QIsGbhJA-Y6-Z_:1236647940)*

**Comment by frewsxcv** [comment]
Fail seems relevant

**Comment by nox** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /domparsing/DOMParser-parseFromString-xml.html:
  └ PASS [expected FAIL] XMLDocument interface for correctly parsed document with type text/xml

  ▶ Unexpected subtest result in /domparsing/DOMParser-parseFromString-xml.html:
  └ PASS [expected FAIL] XMLDocument interface for incorrectly parsed document with type text/xml
```

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8675#-:-K482YNPPEOgUJp3cxdV:1236647940)*

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8675#-:-K48EKHDiSDyz3_4SUzd:1236647940)*

**Pull request merged**
