### PR TITLE
fix: typo in textinput.rs

### PR DESCRIPTION
**Pull request by varundhand**
This PR fixes typos in **components/script/textinput.rs** file.

Following typos have been fixed:

`effecient` -> `efficient`

No other changes.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they simply fix a typo.

### CODE REVIEW

**Review by mrobinson — CHANGES_REQUESTED** [review]
Do you mind using the template that's suggested when opening a PR?

**Comment by mrobinson** [comment]
> Do you mind using the template that's suggested when opening a PR?

I've gone ahead and done this.

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
It looks like we need to update mach before we land any more changes. :face_exhaling:

**Comment by varundhand** [comment]
@mrobinson I reckon that wont be happening anytime soon

**Comment by mrobinson** [comment]
> It looks like we need to update mach before we land any more changes. 😮‍💨

Addressed in #30659.

**Pull request merged**
