### PR TITLE
Refactor WebGL implementation (reopens #5769)

### PR DESCRIPTION
**Pull request by emilio**
GitHub doesn't allow me to reopen #5769, so I created this.

Sorry about the merge fail, my bad :/

cc/ @jdm @dmarcos

---

This PR uses customized GL context creation code, right now only working under Linux, so I expect the clearcolor test to fail on other platforms.

It addresses some other problems:
- Propagates context creation error to the top, returning null if not found.
- Uses GLContextAttributes, which will allow us to write WebGLContextAttributes easily.
- Doesn't allow a 2d context and a WebGL context coexist.
- Panics when resizing the context to larger dimensions (to be fixed soon, but better than blindly allowing it).
  Removes some unused dependencies

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5863)

### CODE REVIEW

**Comment by jdm** [comment]
Still needs a rebase, unfortunately.

**Comment by ecoal95** [comment]
Yep, I was just doing it.

The previous issue was that I failed to merge some old commits when the first implementation wasn't in master yet.

Should be mergeable now, sorry.

**Comment by ecoal95** [comment]
Rewinded to old cocoa version. I kept winapi version since it was duplicated in master.

**Pull request merged**
