### PR TITLE
Changes alignment check from explicit SAFE to !UNSAFE in positioned.rs

### LINKED ISSUE #34240: Default to safe alignment for absolutely positioned elements
```html
<!DOCTYPE html>
<style>
.wrapper { position: relative; width: 50px; height: 50px; border: 3px solid; margin: 50px; }
.abspos { position: absolute; place-self: unsafe end; background: cyan; height: 100px; width: 100px; inset: 0; }
</style>
<div class="wrapper"><div class="abspos" style="place-self: unsafe end"></div></div>
<div class="wrapper"><div class="abspos" style="place-self: safe end"></div></div>
<div class="wrapper"><div class="abspos" style="place-self: end"></div></div>
```

| Servo after #34235 | Blink & FF Nightly |
| - | - |
|  |  |

https://github.com/servo/servo/blob/91026444701cfd68658beb21fbf446f6ed8723e6/components/layout_2020/positioned.rs#L922

should check for `self.alignment.flags() != AlignFlags::UNSAFE`, I think.

### PR DESCRIPTION
**Pull request by chickenleaf**
**File:** `servo/components/layout_2020/positioned.rs: `

**PR Description**
Makes absolutely positioned elements default to safe alignment unless explicitly marked unsafe.

**Changes:**
- Modified alignment check from `flags() == AlignFlags::SAFE` to `flags() != AlignFlags::UNSAFE`

**Future work:**
Could implement proper logic that evaluates and adjusts the alignment based on overflow conditions (unsafe/safe/unspecified) as described in [here](https://drafts.csswg.org/css-align/#auto-safety-position)

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #34240 

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by chickenleaf** [comment]
can i get the github-actions test results bot to run the tests by myself?

**Comment by simonwuelker** [comment]
> can i get the github-actions test results bot to run the tests by myself?

You can run the tests on your fork with `./mach try wpt-2020`. The results are under the "actions" tab, for example https://github.com/simonwuelker/servo/actions/runs/11856516958#summary-33044825976

**Review by Loirooriol — COMMENTED** [review]
Please add a TODO comment saying that the default overflow alignment should be as defined in https://drafts.csswg.org/css-align/#auto-safety-position

**Comment by nicoburns** [comment]
The linked spec says that the fallback if "smart" behaviour is not implemented should be "unsafe" (except for align-content in block layouts):

> UAs that have not implemented the “smart” default behavior must behave as [safe](https://drafts.csswg.org/css-align/#valdef-overflow-position-safe) for [align-content](https://drafts.csswg.org/css-align/#propdef-align-content) on [block containers](https://drafts.csswg.org/css-display-4/#block-container) and [unsafe](https://drafts.csswg.org/css-align/#valdef-overflow-position-unsafe) otherwise.

This PR would contravene that I think? I'm not too worried about this, but wanted to make sure we're doing this knowingly.

**Comment by Loirooriol** [comment]
Yeah, good point. Maybe we should do the actual thing or leave it as-is, after all.
Before #34235 we were always using safe alignment in the inline axis so I thought this would be fine.
But one failure and no pass isn't that great.

**Comment by chickenleaf** [comment]
So should this PR be closed and a new issue be opened for the full implementation?

**Pull request closed without merging**
