### PR TITLE
Upgrade to rustc 1.23.0-nightly (02004ef78 2017-11-08)

### PR DESCRIPTION
**Pull request by SimonSapin**
This fixes some new warnings, some of which (in `style`) are treated as errors. See https://users.rust-lang.org/t/psa-dealing-with-warning-unused-import-std-ascii-asciiext-in-today-s-nightly/13726

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19128)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
test cookie_http_state::test_0004 ... ok
error: An unknown error occurred
```

@bors-servo retry

**Comment by SimonSapin** [comment]
I can reproduced this reliably on mac:
```
$ mach test-unit -p net -- --verbose -- --test-threads 1 test_0003
       Fresh bitflags v0.7.0
[…]
       Fresh net_tests v0.0.1 (file:///Users/simon/projects/servo/tests/unit/net)
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/Users/simon/projects/servo/target/debug/deps/net_tests-77c63548d7be0fc1 --test-threads 1 test_0003`

running 1 test
test cookie_http_state::test_0003 ... error: process didn't exit successfully: `/Users/simon/projects/servo/target/debug/deps/net_tests-77c63548d7be0fc1 --test-threads 1 test_0003` (signal: 10, SIGBUS: access to undefined memory)
```

But *not* when running the binary directly:

```
target/debug/deps/net_tests-77c63548d7be0fc1 test_0003

running 1 test
test cookie_http_state::test_0003 ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 419 filtered out
```

**Comment by SimonSapin** [comment]
It turns out that using lldb over SSH is not allowed on OS X these day. Anyway, this test has `#[should_panic]` and it only fails when `RUST_BACKTRACE=1` is set. Here is an lldb backtrace:

```
* thread #2, name = 'cookie_http_state::test_0003', stop reason = EXC_BAD_ACCESS (code=10, address=0x1019f2000)
  * frame #0: 0x000000010080c001 net_tests-77c63548d7be0fc1`macho_get_commands + 145
    frame #1: 0x000000010080d2cc net_tests-77c63548d7be0fc1`macho_try_dwarf + 396
    frame #2: 0x000000010080dd86 net_tests-77c63548d7be0fc1`macho_try_dsym + 726
    frame #3: 0x000000010080e319 net_tests-77c63548d7be0fc1`macho_add + 1225
    frame #4: 0x000000010080e507 net_tests-77c63548d7be0fc1`backtrace_initialize + 263
    frame #5: 0x000000010080b89e net_tests-77c63548d7be0fc1`fileline_initialize + 558
    frame #6: 0x000000010080b97d net_tests-77c63548d7be0fc1`backtrace_syminfo + 45
    frame #7: 0x00000001007f00e2 net_tests-77c63548d7be0fc1`core::slice::{{impl}}::position::{{closure}}<std::sys_common::backtrace::Frame,closure> [inlined] std::sys_common::gnu::libbacktrace::resolve_symname<closure> at libbacktrace.rs:79 [opt]
    frame #8: 0x00000001007f00af net_tests-77c63548d7be0fc1`core::slice::{{impl}}::position::{{closure}}<std::sys_common::backtrace::Frame,closure> [inlined] std::sys::imp::backtrace::printing::resolve_symname<closure> at mod.rs:36 [opt]
    frame #9: 0x00000001007f00af net_tests-77c63548d7be0fc1`core::slice::{{impl}}::position::{{closure}}<std::sys_common::backtrace::Frame,closure> [inlined] std::sys_common::backtrace::filter_frames::{{closure}} at backtrace.rs:108 [opt]
    frame #10: 0x00000001007f00a8 net_tests-77c63548d7be0fc1`core::slice::{{impl}}::position::{{closure}}<std::sys_common::backtrace::Frame,closure> at mod.rs:1204 [opt]
    frame #11: 0x00000001007fd781 net_tests-77c63548d7be0fc1`std::sys_common::backtrace::_print [inlined] core::slice::{{impl}}::search_while<std::sys_common::backtrace::Frame,core::option::Option<usize>,closure> at mod.rs:1271 [opt]
    frame #12: 0x00000001007fd73f net_tests-77c63548d7be0fc1`std::sys_common::backtrace::_print [inlined] core::slice::{{impl}}::position<std::sys_common::backtrace::Frame,closure> at mod.rs:1203 [opt]
    frame #13: 0x00000001007fd733 net_tests-77c63548d7be0fc1`std::sys_common::backtrace::_print [inlined] std::sys_common::backtrace::filter_frames at backtrace.rs:106 [opt]
    frame #14: 0x00000001007fd70f net_tests-77c63548d7be0fc1`std::sys_common::backtrace::_print at backtrace.rs:71 [opt]
    frame #15: 0x0000000100803ed4 net_tests-77c63548d7be0fc1`std::panicking::default_hook::{{closure}} [inlined] std::sys_common::backtrace::print at backtrace.rs:58 [opt]
    frame #16: 0x0000000100803eb3 net_tests-77c63548d7be0fc1`std::panicking::default_hook::{{closure}} at panicking.rs:381 [opt]
    frame #17: 0x0000000100803a23 net_tests-77c63548d7be0fc1`std::panicking::default_hook at panicking.rs:391 [opt]
    frame #18: 0x00000001008043b3 net_tests-77c63548d7be0fc1`std::panicking::rust_panic_with_hook at panicking.rs:577 [opt]
    frame #19: 0x000000010080422d net_tests-77c63548d7be0fc1`std::panicking::begin_panic<alloc::string::String> at panicking.rs:538 [opt]
    frame #20: 0x0000000100804183 net_tests-77c63548d7be0fc1`std::panicking::begin_panic_fmt at panicking.rs:522 [opt]
    frame #21: 0x00000001001ad22b net_tests-77c63548d7be0fc1`net_tests::cookie_http_state::test_0003::hffd4f07838948d71 + 443
```

The top frames look like https://github.com/rust-lang/rust/blob/master/src/libbacktrace/macho.c, and the only change to that in this interval of Rust versions is https://github.com/rust-lang/rust/pull/45523.

**Comment by SimonSapin** [comment]
Bad news: I can also reproduce on master.

**Comment by SimonSapin** [comment]
This is likely https://github.com/rust-lang/rust/issues/45731

**Comment by SimonSapin** [comment]
> I can also reproduce on master.

It’s more subtle than that. After observing the failure if I downgrade the compiler to a normally not-affected version I’ll still see the same failure until I run `cargo clean`.

Anyway, some people over at https://github.com/rust-lang/rust/issues/45731 seem to have a much better idea than me of what’s going on, so let’s wait for a fix upstream.

**Comment by nox** [comment]
That seems like a network issue, file https://s3.amazonaws.com/rust-lang-ci/rustc-builds-alt/02004ef78383cb174a41df7735a552823fa10b90/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz definitely is downloadable.

@bors-servo retry

**Pull request merged**
