### PR TITLE
Enable pip error output in mach_bootstrap.py

### PR DESCRIPTION
**Pull request by SWW13**
When `pip` encounters an error during mach bootstrapping in `mach_bootstrap.py` there is no error log because of `-q`. The output will only be read when an error was encountered, so this looks like an unintended mistake.

---

This gives error outputs like:
```
D:\Code\moz\servo>mach.bat -h
Pip failed to execute properly:
Output: Collecting marionette_driver>=2.4 (from -r D:\Code\moz\servo\tests\wpt\web-platform-tests\tools\wptrunner\requirements_firefox.txt (line 1))
  Using cached marionette_driver-2.4.0.tar.gz
Collecting mozprofile>=0.21 (from -r D:\Code\moz\servo\tests\wpt\web-platform-tests\tools\wptrunner\requirements_firefox.txt (line 2))
  Using cached mozprofile-0.28.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\$USER\AppData\Local\Temp\pip-build-zqivz5en\mozprofile\setup.py", line 12, in <module>
        assert sys.version_info[0] == 2
    AssertionError

    ----------------------------------------

Error: Command "python setup.py egg_info" failed with error code 1 in C:\Users\$USER\AppData\Local\Temp\pip-build-zqivz5en\mozprofile\
```

instead of:

```
D:\Code\moz\servo>mach.bat -h
Pip failed to execute properly:
Output:
Error: Command "python setup.py egg_info" failed with error code 1 in C:\Users\$USER\AppData\Local\Temp\pip-build-htd5no9k\mozprofile\
```

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19362)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
This looks like a useful improvement; thanks!

**Comment by tigercosmos** [comment]
it crashed unexpectedly.
```
mach.bat clean-nightlies --keep 3 --force
 in dir c:\buildbot\slave\windows-msvc-dev\build (timeout 1200 secs)
 watching logfiles {}
 argv: ['mach.bat', 'clean-nightlies', '--keep', '3', '--force']
 environment:
  ALLUSERSPROFILE=C:\ProgramData
  APPDATA=C:\Windows\system32\config\systemprofile\AppData\Roaming
  BUILD_MACHINE=<buildbot.process.properties.Property instance at 0x7fcef4792d88>
  CARGO_HOME=C:\Users\Administrator\.cargo
  COMMONPROGRAMFILES=C:\Program Files\Common Files
  COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
  COMMONPROGRAMW6432=C:\Program Files\Common Files
  COMPUTERNAME=WIN-1UDOTULBFGN
  COMSPEC=C:\Windows\system32\cmd.exe
  FP_NO_HOST_CHECK=NO
  HOME=C:\buildbot\slave\windows-msvc-dev\build
  LOCALAPPDATA=C:\Windows\system32\config\systemprofile\AppData\Local
  NUMBER_OF_PROCESSORS=4
  OS=Windows_NT
  PATH=C:\Python27;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Amazon\cfn-bootstrap;C:\Program Files\Git\cmd;C:\Program Files (x86)\WiX Toolset v3.10\bin;C:\sccache
  PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  PROCESSOR_ARCHITECTURE=AMD64
  PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
  PROCESSOR_LEVEL=6
  PROCESSOR_REVISION=3f02
  PROGRAMDATA=C:\ProgramData
  PROGRAMFILES=C:\Program Files
  PROGRAMFILES(X86)=C:\Program Files (x86)
  PROGRAMW6432=C:\Program Files
  PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\AWS Tools\PowerShell\
  PUBLIC=C:\Users\Public
  PWD=c:\buildbot\slave\windows-msvc-dev\build
  RUST_BACKTRACE=1
  SERVO_CACHE_DIR=C:\Users\Administrator\.servo
  SYSTEMDRIVE=C:
  SYSTEMROOT=C:\Windows
  TEMP=C:\Windows\TEMP
  TMP=C:\Windows\TEMP
  USERDOMAIN=WORKGROUP
  USERNAME=WIN-1UDOTULBFGN$
  USERPROFILE=C:\Windows\system32\config\systemprofile
  VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
  WINDIR=C:\Windows
  WIX=C:\Program Files (x86)\WiX Toolset v3.10\
 using PTY: False

command timed out: 1200 seconds without output running ['mach.bat', 'clean-nightlies', '--keep', '3', '--force'], attempting to kill
program finished with exit code 1
elapsedTime=1200.089000
```

**Comment by jdm** [comment]
@bors-servo: retry
* mysterious timeout

**Comment by jdm** [comment]
Ok, there is definitely something about this PR that breaks our windows builds, since it's happened twice.

**Comment by SWW13** [comment]
The `stdout=PIPE` seems the be the problem:
> Warning: This will deadlock when using stdout=PIPE and/or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use communicate() to avoid that.
https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait

I'll work out a solution with `tempfile` and `pip --log $file`. The `pip -q` could potentially also deadlock if there are enough warnings, so the current state is also not perfect.

**Comment by SWW13** [comment]
I refactored all `Popen` calls (there was a third one for `virtualenv`), they now use a `tempfile` instead of pipes so we should be safe to not trigger deadlocks.
And additionally the `-q` of `pip` calls are removed.

New output in case of errors:
```
D:\Code\moz\servo>mach.bat build -d
"D:\Code\moz\servo\python\_virtualenv\Scripts\pip.exe" "install" "-I" "-r" "D:\Code\moz\servo\tests\wpt\web-platform-tests\tools\wptrunner\requirements_firefox.txt" failed with error code 1:
Output:
Collecting marionette_driver>=2.4 (from -r D:\Code\moz\servo\tests\wpt\web-platform-tests\tools\wptrunner\requirements_firefox.txt (line 1))
  Using cached marionette_driver-2.4.0.tar.gz
Collecting mozprofile>=0.21 (from -r D:\Code\moz\servo\tests\wpt\web-platform-tests\tools\wptrunner\requirements_firefox.txt (line 2))
  Using cached mozprofile-0.28.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Simon\AppData\Local\Temp\pip-build-i1zr_4w3\mozprofile\setup.py", line 12, in <module>
        assert sys.version_info[0] == 2
    AssertionError

    ----------------------------------------
Error:
Command "python setup.py egg_info" failed with error code 1 in C:\Users\$USER\AppData\Local\Temp\pip-build-i1zr_4w3\mozprofile\
```

**Comment by jdm** [comment]
@bors-servo: r+
Thanks, this looks even better now!

**Pull request merged**
