### PR TITLE
Implement node::LookupPrefix and add test.

### PR DESCRIPTION
**Pull request by ienzam**
Tracking issue #1826 - implemented one of the three methods.

This is follow up of #5402. Rebased and squashed and made the method iterative.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5650)

### CODE REVIEW

**Comment by jdm** [comment]
This is great work with very readable implementations! I've left one small comment on Critic :)

**Comment by ienzam** [comment]
Pushed the fix.

**Comment by jdm** [comment]
Looks good! Squash and rebase!

**Comment by ienzam** [comment]
Squashed and rebased :)

**Comment by jdm** [comment]
```
/Users/servo/buildbot/slave/mac2/build/components/script/dom/node.rs:1735:42: 1735:43 help: did you mean to close this delimiter?
/Users/servo/buildbot/slave/mac2/build/components/script/dom/node.rs:1735 impl<'a> NodeMethods for JSRef<'a, Node> {
                                                                                                                   ^
/Users/servo/buildbot/slave/mac2/build/components/script/dom/node.rs:2541:2: 2542:2 error: this file contains an un-closed delimiter 
/Users/servo/buildbot/slave/mac2/build/components/script/dom/node.rs:2541 }
/Users/servo/buildbot/slave/mac2/build/components/script/dom/node.rs:2542 
```

**Comment by ienzam** [comment]
Sorry my mistake, bad merge - https://github.com/servo/servo/pull/5650/files#diff-3a91deb90f65260523e1e9bd52154934R2281

Fixed and pushed

**Comment by ienzam** [comment]
@jdm The fail does not seem to related to my change. Do I need to do anything?

**Comment by jdm** [comment]
@bors-servo: retry
* #5714

**Comment by jdm** [comment]
@bors-servo: retry
* #5714

**Pull request merged**
