### PR TITLE
Documents now fully deactivate when a freeze message is sent

### LINKED ISSUE #14906: Documents are never fully deactivated
We `fully_activate` documents when a thaw message is sent but never `fully_deactivate` them when a freeze message is sent.

cc @asajeffrey

### PR DESCRIPTION
**Pull request by 0xRampey**
Documents now fully deactivate when a freeze message is sent

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14906  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because minimal changes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15016)

### CODE REVIEW

**Comment by cbrewster** [comment]
@bors-servo r+
Thank you!

**Comment by metajack** [comment]
I'm traveling all weekend so someone else should grab this if it can't wait until Monday.

**Comment by metajack** [comment]
Or just get it done while I'm logging in from my phone.  That works too :)

**Comment by prampey** [comment]
You're welcome. :)

**Pull request merged**
