### PR TITLE
Update mozbrowserlocationchange_event.html

### LINKED ISSUE #11450: The mozbrowserlocationchanged event property should be url, not uri
The documentation at https://developer.mozilla.org/en-US/docs/Web/Events/mozbrowserlocationchange describes the details object has having property:

**url** The URL of the new location

but our implementation https://github.com/servo/servo/blob/master/components/script/dom/webidls/BrowserElement.webidl#L66 has a property **uri**.

### PR DESCRIPTION
**Pull request by Coder206**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #11450 (github issue number if applicable).

- [x] There are tests for these changes OR
- [x] These changes do not require tests because @asajeffrey just wanted compiled code (testing was and still isn't working for me on Windows 10)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11603)

### CODE REVIEW

**Comment by Coder206** [comment]
@asajeffrey Here is the long overdue and awaited code for your issue post (#11450). I noticed there were a few URIs left in the iframe related Rust files, should I change these too?

**Comment by asajeffrey** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11603)*

**Comment by asajeffrey** [comment]
I think some of the files are missing, this PR just has changes to `tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowserlocationchange_event.html`.

Glad that you were able to submit!

**Comment by Coder206** [comment]
@asajeffrey I thought it was working. I am having lots of trouble getting Servo and BrowserHTML working.

**Comment by Coder206** [comment]
@asajeffrey Can I add to this PR the changes?

**Comment by asajeffrey** [comment]
@Coder206 yes, just push new commits.

**Comment by Coder206** [comment]
Please consult #11765

**Comment by Coder206** [comment]
#11782 is the new PR for this

**Pull request closed without merging**
