### PR TITLE
default to number of available cpu for wpt-tests

### LINKED ISSUE #5046: Make test-wpt default to the number of CPUs
I feel bad every time somebody says "the WPT tests are really slow" because it means they're not using `--processes=[N>1]`. We should have a sensible default here that gets the number of CPUs and passes that as a parameter when invoking the test harness in the `test-wpt` command in `testing_commands.py`.

### PR DESCRIPTION
**Pull request by deepak1556**
fixes #5046

### CODE REVIEW

**Comment by jdm** [comment]
Thanks; I've left a comment on Critic! I'm concerned about losing the free-form params argument here, since it's very useful.

**Comment by deepak1556** [comment]
thanks! missed that scenario, fixed it. Users can now do `./mach test path/to/test.html` `./mach test-wpt --include path/to/test.html` `./mach test-wpt path/to/test.html` with `--processes <N>` too

**Comment by jdm** [comment]
Nearly there! I just want to make sure that we don't regress our existing abilities :)

**Comment by deepak1556** [comment]
Should work as expected now :) thanks!

**Comment by jdm** [comment]
Great! Please squash the commits and I'll merge them!

**Comment by deepak1556** [comment]
Done :) thanks!

**Pull request merged**
