### PR TITLE
Implemented HTMLInputElement placeholder attribute

### PR DESCRIPTION
**Pull request by minsumm**
I'm unsure whether I should wrap 'placeholder' in Cell, or DomRefCell, or leave as it is now.
Also, the spec says that the placeholder should be presented with line breaks stripped off,
should it be done in this stage?

### CODE REVIEW

**Comment by jdm** [comment]
@genkku This is a good start! I've left comments on Critic; the most important takeaway is that testing your changes would have demonstrated that the implementation is not yet complete :)

**Comment by genkku** [comment]
@jdm Doh! I was also unsure about which tests where relevant. I'll try to make sense of the required changes.

**Comment by jdm** [comment]
The spec link in the original issue has a decent HTML example that would show the desired behaviour in the browser of your choice.

**Comment by metajack** [comment]
Assigning to @jdm since he already did the initial pass.

**Comment by genkku** [comment]
Sorry for the lack of communication. What's the status? Can I still finish this, as I've implemented the feature and it works when testing with servo. I'm now working on the tests.

Also, there's a small problem relating to string_cache:
If I've understood correctly I should be matching against

&atom!("placeholder")

Now this fails, since string_cache doesn't have "placeholder" in 'plugin/src/atom/data.rs'.

I locally made the change and tested that it works. Should I make pull request to string_cache?

**Comment by jdm** [comment]
For now, you can just use Atom::from_slice("placeholder") instead of using the atom macro. And yes, do go ahead and finish this work - we're just assigning the PRs to team members as a way of saying "you're responsible for making sure this PR doesn't get forgotten".

**Comment by genkku** [comment]
It might be that I'm confused and using Atom::from_slice("placeholder") in a wrong way, but it seems that it can't be matched against. Various unsatisfactory hacks don't work either (local variables, constants, etc.)

I fixed the test expectations that we're expected to fail, but I'm also getting a few failed tests. I'm unsure whether they're related to the changes I've made:
```
/html/browsers/history/the-location-interface/security_location_0.sub.htm
-------------------------------------------------------------------------
NOTRUN Accessing location object from different origins doesn't raise SECURITY_ERR exception
TIMEOUT expected CRASH [Parent]
/html/browsers/the-window-object/security-window/window-security.sub.html
-------------------------------------------------------------------------
NOTRUN Window Security testing
TIMEOUT expected CRASH [Parent]
/html/dom/reflection-forms.html
-------------------------------
TIMEOUT [Parent]
/html/dom/reflection-misc.html
------------------------------
TIMEOUT [Parent]
/html/webappapis/scripting/processing-model-2/compile-error-cross-origin-setTimeout.html
----------------------------------------------------------------------------------------
FAIL expected NOTRUN window.onerror - compile error in cross-origin setTimeout
FAIL expected NOTRUN window.onerror - compile error in cross-origin setTimeout (column)
OK expected TIMEOUT [Parent]
/html/webappapis/scripting/processing-model-2/compile-error-cross-origin-setInterval.html
-----------------------------------------------------------------------------------------
FAIL expected NOTRUN window.onerror - compile error in cross-origin setInterval
FAIL expected NOTRUN window.onerror - compile error in cross-origin setInterval (column)
OK expected TIMEOUT [Parent]
/html/webappapis/scripting/processing-model-2/runtime-error-cross-origin-setInterval.html
-----------------------------------------------------------------------------------------
FAIL expected NOTRUN window.onerror - runtime error in cross-origin setInterval
FAIL expected NOTRUN window.onerror - runtime error in cross-origin setInterval (column)
OK expected TIMEOUT [Parent]
/html/webappapis/scripting/processing-model-2/runtime-error-cross-origin-setTimeout.html
----------------------------------------------------------------------------------------
FAIL expected NOTRUN window.onerror - runtime error in cross-origin setTimeout
FAIL expected NOTRUN window.onerror - runtime error in cross-origin setTimeout (column)
OK expected TIMEOUT [Parent]
/html/semantics/text-level-semantics/the-wbr-element/wbr-element.html
---------------------------------------------------------------------
TIMEOUT expected FAIL [Parent]
```

**Comment by jdm** [comment]
I admit that I don't know what to make of that. The first two look like the changes from #5476, and I've seen the reflection ones time out before for testharness-related reasons, but the rest are super weird. Maybe try submitting the changes you have and we'll see what happens on the test machines?

**Comment by jdm** [comment]
With regards to Atom::from_slice, are you using `&Atom::from_slice` where you would use `&atom!`?

**Comment by jdm** [comment]
Oh wait, that probably doesn't work. You may need a separate `_ if foo == Atom::from_slice("placeholder") =>` branch.

**Comment by genkku** [comment]
I failed to find a way to accomplish this without excessive mutation. I'm also wondering if there's a more idiomatic way to strip the line breaks.

**Comment by jdm** [comment]
http://mxr.mozilla.org/servo/source/components/script/dom/window.rs#249 is a nice example of removing whitespace from strings.

**Comment by jdm** [comment]
I've left some more comments on Critic, but this is looking much more like what I was expecting :)

**Comment by genkku** [comment]
I tried removing the to_owned() on line 159, but it fails: 'cannot move out of borrowed content'.

**Comment by jdm** [comment]
One teeny little style nit left, and then it's mergeable!

**Comment by genkku** [comment]
Haha, I got a bit ahead of myself and let that one slip past me :)

**Comment by jdm** [comment]
Squash!

**Comment by genkku** [comment]
@jdm hopefully everything is fine and dandy now!

**Pull request closed without merging**
