### PR TITLE
Update to rustc 1.7.0-nightly (b4707ebca 2015-12-27)

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9093)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r- force

```
./components/plugins/heap_size.rs:22: use statement is not in alphabetical order
	expected: syntax_ext::deriving::generic::*
	found: syntax::ptr::P
./components/plugins/jstraceable.rs:12: use statement is not in alphabetical order
	expected: syntax_ext::deriving::generic::{combine_substructure, EnumMatching, FieldInfo, MethodDef}
	found: syntax::ptr::P
```

**Comment by jdm** [comment]
```
error: linking with `/home/servo/buildbot/slave/gonk/build/ports/gonk/./fake-ld.sh` failed: exit code: 1
note: "/home/servo/buildbot/slave/gonk/build/ports/gonk/./fake-ld.sh" "-Wl,--as-needed" "-Wl,--allow-multiple-definition" "-L" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/b2s.0.o" "-o" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/b2s" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/b2s-5842bb6d6e0bc152/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/angle-ee9dc8911de0d6f3/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/azure-d7ea6502b6b7c362/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/expat-sys-ac3e44549914c8aa/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/harfbuzz-sys-278d3b2daab5baa1/out/lib" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/hbs-pow-sys-cf8ae81d4cf55502/out/_build/lib" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/js-b63ddf1f18d33225/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/miniz-sys-f1c39e8e406fa25f/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/mozjs_sys-e411d274df144795/out/dist/lib" "-L" "/home/servo/B2G//out/target/product/flame/obj/lib" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/openssl-sys-extras-e38fd8aa704c6185/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/servo-6fa8e8e4b3273dd4/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/servo-fontconfig-sys-f6f8aa0960029b48/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/servo-freetype-sys-8d16379bf1510faa/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/servo-skia-293ef5cd3d245c0c/out" "-L" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/stb_image-e0c1ec4a3ad34af3/out" "-L" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-l" "native_window_glue" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-l" "stlport" "-l" "hardware" "-l" "suspend" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libservo-9bb739e51529b391.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libnet-322a4be8cebce3c6.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libcompositing-c9eb82ba0374119f.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblayout-7d1f917cb662390a.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libunicode_bidi-28d517779a365a0b.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libprofile-e939ff243140ff0b.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libhbs_pow-9e5fd5a2655bc375.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libdevtools-80a1b1e45ac44128.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libscript-9a59d0654cbd572f.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libcaseless-a92ff95a6c11bb0c.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libangle-ee9dc8911de0d6f3.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libxml5ever-319ff8bc429c0762.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libenv_logger-9877a407b506c549.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libregex-a1f41b95f7958684.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libbrotli-fa388f4f29cc510f.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liberrno-556de28574b59be4.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libgaol-b183c78eb8c0edba.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libserde_json-363b4f85f577417b.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libregex_syntax-6d9e9f3bd76497d4.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libclipboard-63bc7ea4a6fe06c9.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libref_slice-d330b35eafb38760.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libhbs_pow_sys-cf8ae81d4cf55502.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libhbs_common_sys-35d0997fd370efc9.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libmime_guess-8355f8f3d19d1ba9.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libaho_corasick-399b4a6bb6d46cc8.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libmemchr-49395bf503c0fa9c.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libunicode_normalization-78fb2197226c310a.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblayout_traits-34f6bb46c0999165.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libgfx-e169a2b2e18fd1b6.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libfontconfig-39784ba4f9bd6bef.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libscript_traits-d56330cbd3469e5d.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libdevtools_traits-f977eec127221aeb.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libprofile_traits-529f0a0159267ba1.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libfontconfig_sys-f6f8aa0960029b48.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libexpat_sys-ac3e44549914c8aa.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libstyle-e63c8fff7e66bdbe.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libstyle_traits-1dd3fa3984e62a19.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libunicode_script-cf2058d473e757bb.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libharfbuzz_sys-278d3b2daab5baa1.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libnet_traits-5376413252cae14a.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libwebsocket-0468772e04956882.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libimage-d4eebd4b60993596.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libpng-4b704d4773932522.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libenum_primitive-f59ab0a46937bdae.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libgif-6b12b58df6c08f1f.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libcolor_quant-6695fde28ee2e395.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblzw-b298258ca3ee8886.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libnet2-9256a64b8ef2a2ac.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libws2_32-ec8d9fa041ca4cbb.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libinflate-b852113d32258b7b.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libcfg_if-0dcf5e6d515dd4d2.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libkernel32-35c1a745c861d23a.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libstb_image-e0c1ec4a3ad34af3.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libwinapi-d88a8c018c340227.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libflate2-f631189bcf5818ae.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libminiz_sys-f1c39e8e406fa25f.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libcanvas-62ec5d15e834d714.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libcanvas_traits-841fe15e016ee5ee.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liboffscreen_gl_context-cc3be91171f9cf84.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libgfx_traits-43bdcf6f7438da8a.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libmsg-f472afe437e22bdb.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libutil-6d988a194ce2c89a.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libapp_units-68eeb8021de9e8c6.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblayers-2f80348cb96e017d.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libjs-b63ddf1f18d33225.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libmozjs_sys-e411d274df144795.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libgetopts-1be2f24cd9708e15.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libhyper-a8204aa4c798b8b1.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libsolicit-699226f9674a00ef.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblanguage_tags-2c71650f1f494658.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libhpack-37abaf37ec66685c.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libmime-895d454306901c0a.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libtraitobject-e8fd97c9f52dc0fb.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libunicase-5cad4981df096787.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libazure-d7ea6502b6b7c362.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libskia-293ef5cd3d245c0c.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libegl-830a4f4da9374fc6.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libhtml5ever-332b5d04a21129d7.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libphf-67f3c539a431de21.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libdebug_builders-337a04ff86d82ad7.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libtendril-6ef15ef6855d281c.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libtypeable-3d4cacf3175a54fa.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libfreetype_sys-8d16379bf1510faa.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libfutf-2d68187ed3b54e00.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libhttparse-f5094c54083a7a46.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libfreetype-bc804dedae87cd10.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblibz_sys-521f51dd8fade4c2.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libmac-9253dcbe1dddc564.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libnum_cpus-0fd73096755c3779.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libipc_channel-e9ff443c2a3b3a48.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libbincode-7985896c8cc576c9.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libbyteorder-8489290bbd10b018.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblibc-29adb837ec836726.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libgleam-09fdc1f85ff8e17d.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libselectors-8633a00278b915f5.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libquickersort-4ee5a0d175320e87.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libsmallvec-464dc4542849ab4f.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libcssparser-b17582595cb0af3a.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libfnv-5893ac1ec1276f44.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libstring_cache-26d9b6c94815fe3e.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libdebug_unreachable-bb8686e7201a0fcf.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libunreachable-3dea623717e22df5.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libvoid-bc07a168f02e800d.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libphf_shared-3160efea5fa48a57.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libcookie-bba1a51bc81dd84b.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libtime-b8d9c9e7ca5bced7.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libopenssl-63722611fd0329f7.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblazy_static-f3aa6dfcc7c157cc.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libbitflags-eec34728826d9769.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liburl-805aa5d8362d9b8d.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libuuid-82ee95c4f525f1f6.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libencoding-a635ee1112a4a115.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libencoding_index_korean-e6ea16a131576deb.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libmatches-68291f81832fc22d.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libencoding_index_simpchinese-36d98fe1ee6656fc.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libopenssl_sys_extras-e38fd8aa704c6185.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libopenssl_sys-a614809a8b88adb9.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libencoding_index_singlebyte-989206689effef1e.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libencoding_index_tradchinese-1ea03524459844c3.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libeuclid-a7667628cb93c861.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblog-db195e915b7f1b50.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libserde-3d84e1340fb936c2.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libnum-e432b6183cf6cb0e.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/librand-204b49f864ff4762.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/librustc_serialize-7ff5bfc027146194.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libheapsize-e9447c46cffe7bb1.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/liblibc-540159808ccfa9ab.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/librc-c5d6d71555bcc452.rlib" "/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/deps/libencoding_index_japanese-02d1e3db3f81af39.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/libtest-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/libserialize-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/libterm-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/liblog-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/libgetopts-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/libstd-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/libcollections-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/librustc_unicode-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/librand-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/liballoc-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/liballoc_jemalloc-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/liblibc-17a8ccbd.rlib" "/home/servo/.servo/rust/2015-12-27/rustc-nightly-x86_64-unknown-linux-gnu/rustc/lib/rustlib/arm-linux-androideabi/lib/libcore-17a8ccbd.rlib" "-l" "log" "-l" "android" "-l" "stdc++" "-l" "stdc++" "-l" "EGL" "-l" "jsglue" "-l" "stdc++" "-l" "gcc" "-l" "stdc++" "-l" "stdc++" "-l" "expat" "-l" "fontconfig" "-l" "EGL" "-l" "azure" "-l" "stdc++" "-l" "GLESv2" "-l" "EGL" "-l" "EGL" "-l" "freetype" "-l" "z" "-l" "c" "-l" "m" "-l" "GLESv2" "-l" "ssl" "-l" "crypto" "-l" "dl" "-l" "log" "-l" "gcc" "-l" "gcc" "-l" "c" "-l" "m" "-fuse-ld=gold" "-l" "compiler-rt"
note: /home/servo/buildbot/slave/gonk/build/ports/gonk/./fake-ld.sh: line 8: -pie: command not found
/home/servo/.cargo/registry/src/github.com-0a35038f75765ae4/errno-0.1.5/src/unix.rs:52: error: undefined reference to '__errno_location'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Could not compile `b2s`.
```

**Comment by Ms2ger** [comment]
Gah. @larsbergstrom?

**Comment by larsbergstrom** [comment]
I'll try to repro this on my local Linux box. I've only seen this before when attempting to do a cargoup.

**Comment by larsbergstrom** [comment]
Few things going on here:
1) the note about `-pie` is just a bug in the build script, and we can fix that pretty quickly

2) if we attempt to build on a machine with the gold linker installed, we get WAY more errors than even just that! we will need to add some anti-gold protection here
cc @alexcrichton is there a way to turn off using the gold linker from Cargo?

3) I can also repro that missing symbol. Not sure why a rustup is causing it, but it probably means that somewhere some native library is being built and pointing at the GNU libc headers, which redefined `errno` to `__errno_location`, which is not available in the libc available on Android. Really not sure why this is only occurring on Gonk and not Android, too, but I'll keep digging.
cc @michaelwu in case he has any ideas off the top of his head

**Comment by alexcrichton** [comment]
There's currently not a great way to disable gold without using a wrapper-rustc-script which passes `-C disable-gold`, but we may end up reverting the change to use gold by default anyway.

I'd be pretty interested, however, in what the errors are with using gold. I'm sure that Servo would *greatly* improve link times using gold instead of the default ld, so it'd be great to investigate!

**Comment by alexcrichton** [comment]
cc @brson about gold issues as well

**Comment by larsbergstrom** [comment]
@alexcrichton Hrm, this might be us. We've been using gold for a long time (August 15th - https://github.com/servo/servo/commit/fb7a53c6cfc8bc2985423a55834507c930537bfc), but it breaks on cross-compiles, as in https://github.com/servo/servo/issues/7564 (totally fine on native builds). I think this is our fault - looking at the rustc code, you shouldn't be using gold on cross-compiles, so I should back out that commit with this rustc update, since we should no longer have to do the gold linker determination ourselves.

**Comment by alexcrichton** [comment]
@larsbergstrom that build error actually looks unrelated to the usage of gold to me, looking at the two errors it looks like you've seen that `-pie` is just a weird command being run (and can be fixed), and the second problem is actually because `__errno_location` [used to be a symbol but was removed](https://github.com/rust-lang/rust/pull/30175/files#diff-cbcfdc29f0353c1a505c3c1980858a09L17) from our "dummy android runtime" file. The [correct name for that symbol](https://github.com/rust-lang/rust/pull/30175/files#diff-8e72b70bbc345c1ce56671cb9a998e2bR45) is `__errno` on android.

Other than that I think that it may be fine to just leave gold as-is.

**Comment by larsbergstrom** [comment]
@alexcrichton I didn't provide the output from using gold - if you use it on a cross compile, you get a slew of errors (primarily around missing symbols). I'm assuming that's why @brson disabled use of gold in cross-compile build in rustc (https://github.com/rust-lang/rust/pull/29974#issuecomment-161077451). #2 is a bug in our build scripts, and I'll fix it separately.

You're right that for #3 it's either in a rust library or one of or gajillion C libraries. It's super easy to accidentally link against system headers instead of Android/bionic libc. I'll try to look into which is the lucky module trying to bring it in today :-)

**Comment by brson** [comment]
Ok, for now based on @larsbergstrom I'm assuming there are no upstream issues related to gold, but I'm kinda skeptical. Why do you think the new gold errors are related to your script - did it change?

**Comment by larsbergstrom** [comment]
@brson I'm pretty sure I just ended up with a bunch of new errors because I accidentally tried to cross-compile targeting gonk with the gold linker. Typically I've been on OSX or on a linux box w/o gold installed.

So, no need to worry! Once I revert the Servo hackery that forces us onto gold even in cross-compiles if it's available and rely on the stuff you added to rustc instead, we should be fine here.

The only real work on this PR is to figure out where the sneaky `__errno_location` is creeping into the build, which I'm looking into now.

**Comment by larsbergstrom** [comment]
Needs https://github.com/lfairy/rust-errno/pull/5 to land & push up to crates.io.

**Comment by larsbergstrom** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /html/infrastructure/terminology/plugins/text-plain.html:
  └ PASS [expected FAIL] A user agent must not consider the type text/plain as having a registered plugin.
```

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #9286

**Comment by Ms2ger** [comment]
@bors-servo retry
* #9286

**Comment by Ms2ger** [comment]
Seems to be hitting #9286 pretty consistently...

**Comment by KiChjang** [comment]
@bors-servo retry

* #9286
I'm going to retry again, third time's the trick hopefully...

**Pull request merged**
