### PR TITLE
Disable reflection-embedded.html (tracked in #11100)

### PR DESCRIPTION
**Pull request by nox**
See #11100.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11414)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo p=27

As the number of PRs mentioned in the intermittent issue.

**Comment by mbrubeck** [comment]
Somehow this is still running on mac? https://github.com/servo/servo/pull/11372#issuecomment-221755349

**Pull request merged**
