### PR TITLE
Implement resettable and String-valued prefs.

### PR DESCRIPTION
**Pull request by jgraham**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7651)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed 9 of 9 files at r1.
Review status: 6 of 11 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/style/stylesheets.rs, line 432 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ2ASraQTI5-STRUdr)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/style/stylesheets.rs#L432)):</sup>
`get_boolean_pref`?

---

<sup>**[components/util/prefs.rs, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ25OKLyhOxEftl1Ml)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/util/prefs.rs#L26)):</sup>
Can this consume the `Json`?

---

<sup>**[components/util/prefs.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ20rgZFas_WpOHfse)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/util/prefs.rs#L44)):</sup>
`Option<&str>`

---

<sup>**[components/util/prefs.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ1rC2nJb8cOVN-TXh)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/util/prefs.rs#L87)):</sup>
This can return `&Arc<PrefValue>` or `&PrefValue`

---

<sup>**[components/util/prefs.rs, line 153 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ1VHeSr6BLQGDXDEw)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/util/prefs.rs#L153)):</sup>
Maybe

```rust
if let Some(pref) = prefs.get_mut(name) {
    pref.set_value(value);
    return;
}
prefs.insert(name.to_owned(), Pref::new(value));
```

---

<sup>**[components/util/prefs.rs, line 163 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ07C2reDlHGSUQvBi)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/util/prefs.rs#L163)):</sup>
How about

```rust
let result = match prefs.get_mut(name) {
    None => return None,
    Some(&mut Pref::NoDefault(_)) => None,
    Some(&mut Pref::WithDefault(ref default, ref mut set_value)) => {
        *set_value = None;
        Some(default.clone())
    },
};
if result.is_none() {
    prefs.remove(name);
}
result
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by jgraham** [comment]
Review status: 6 of 11 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/util/prefs.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ20rgZFas_WpOHfse)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/util/prefs.rs#L44)):</sup>
Agreed, this was an oversight, but it creates an ergonomic problem for the "get the homepage from the command line or use the pref" use case I think because `prefs.get("foo").and_then(|x| x.as_string())` doesn't work because the `PrefValue` `x` has a lifetime limited to the closure.  So it's annoying to go from an `Option<PrefValue::String>` to an `Option<&str>`. Suggestions?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by jgraham** [comment]
Review status: 6 of 11 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/util/prefs.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ20rgZFas_WpOHfse)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/util/prefs.rs#L44)):</sup>
Ah, perhaps removing the `Option<>` and just having a `PrefValue::Missing` is a good solution. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by jgraham** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/style/stylesheets.rs, line 432 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ2ASraQTI5-STRUdr)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/style/stylesheets.rs#L432)):</sup>
Not sure this is needed now.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/util/prefs.rs, line 149 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzW3ZaneijsyWrQWCMy)** ([raw file](https://github.com/servo/servo/blob/fbc4ea41dce9a740095265e2343e183157c542f4/components/util/prefs.rs#L149)):</sup>
Kinda sucks that we need to allocate an `Arc` for the missing case now.

---

<sup>**[components/webdriver_server/lib.rs, line 657 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzW3K94aYPGCx0vUHM8)** ([raw file](https://github.com/servo/servo/blob/fbc4ea41dce9a740095265e2343e183157c542f4/components/webdriver_server/lib.rs#L657)):</sup>
Indentation is off

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/util/prefs.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ1rC2nJb8cOVN-TXh)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/util/prefs.rs#L0)):</sup>
I think we decided it can't.

---

<sup>**[components/util/prefs.rs, line 0 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzW3ZaneijsyWrQWCMy)** ([raw file](https://github.com/servo/servo/blob/fbc4ea41dce9a740095265e2343e183157c542f4/components/util/prefs.rs#L0)):</sup>
Is this avoidable?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/util/prefs.rs, line 89 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7651#-JzQ1rC2nJb8cOVN-TXh)** ([raw file](https://github.com/servo/servo/blob/5ea0406621646a74474136c997a425b082af00bf/components/util/prefs.rs#L89)):</sup>
`&Arc<PrefValue>` should still work.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by Ms2ger** [comment]
Thanks. Please squash.

-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by jgraham** [comment]
Done

**Comment by jgraham** [comment]
Pushed a fixup

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 1 of 6 files at r6.
Review status: 7 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by jdm** [comment]
```
   Compiling style_tests v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-ref-unit/build/components/servo)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/style/viewport.rs:29:56: 29:60 error: mismatched types:
 expected `util::prefs::PrefValue`,
    found `bool`
(expected enum `util::prefs::PrefValue`,
    found bool) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/style/viewport.rs:29     ::util::prefs::set_pref("layout.viewport.enabled", true);
                                                                                                                                          ^~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/style/viewport.rs:29:56: 29:60 help: run `rustc --explain E0308` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/style/viewport.rs:176:56: 176:60 error: mismatched types:
 expected `util::prefs::PrefValue`,
    found `bool`
(expected enum `util::prefs::PrefValue`,
    found bool) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/style/viewport.rs:176     ::util::prefs::set_pref("layout.viewport.enabled", true);
                                                                                                                                           ^~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/style/viewport.rs:176:56: 176:60 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 2 previous errors
Could not compile `style_tests`.
```

**Comment by jdm** [comment]
Seems to have broken `./mach test-ref` somehow, too.

**Comment by Ms2ger** [comment]
Reviewed 5 of 6 files at r6, 7 of 8 files at r7.
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/reftest.rs, line 127 \[r7\]](https://reviewable.io:443/reviews/servo/servo/7651#-K-2XuKlLHUlPtWRJfv7)** ([raw file](https://github.com/servo/servo/blob/bd4e0a143998d6e65aca6def986ed421790030da/tests/reftest.rs#L127)):</sup>
That's unfortunate... What's going on here?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by jgraham** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/reftest.rs, line 127 \[r7\]](https://reviewable.io:443/reviews/servo/servo/7651#-K-2XuKlLHUlPtWRJfv7)** ([raw file](https://github.com/servo/servo/blob/bd4e0a143998d6e65aca6def986ed421790030da/tests/reftest.rs#L127)):</sup>
It's trying to launch the browser to check if command line argument parsing worked. Previously it relied on the fact that not supplying a URL would cause it to exit immediately but with a different error message to an invalid command line argument. Now that isn't true so to preserve the behaviour I made it wait a bit to "ensure" that it has time to output the error message should it fail, before killing it manually. But the whole thing seems a little silly tbh.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7651)

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Pull request merged**
