### PR TITLE
Prepare related files to make it easier to split up the Mako template

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/servo/servo/pull/10586#issuecomment-211490049

r? @nox

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10749)

### CODE REVIEW

**Comment by nox** [comment]
Looks fine to me.

@bors-servo r+

---

Reviewed 5 of 6 files at r1, 12 of 12 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/build.rs, line 31 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10749#-KFnuGdCNenALv7DzuN1:-KFnuGdCNenALv7DzuN2:-1783875554) ([raw file](https://github.com/servo/servo/blob/b7eb720c74ac28ab2745c52f1920c0be5fa3107a/components/style/build.rs#L31)):*
Nit: `Result::unwrap_or_else` exists too, but shrug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10749#-:-KFnw_SejDXWkbeoqADS:663557541)*

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/build.rs, line 31 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10749#-KFnuGdCNenALv7DzuN1:-KFnxMjAOuFX3tq8VPLj:338568333) ([raw file](https://github.com/servo/servo/blob/b7eb720c74ac28ab2745c52f1920c0be5fa3107a/components/style/build.rs#L31)):*
That one wants a callable that takes the error value as a parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10749)*

**Comment by SimonSapin** [comment]
@bors-servo r=nox

(self-approving the tidy commit)

**Comment by KiChjang** [comment]
```
Ran 4682 tests finished in 359.0 seconds.
  • 4680 ran as expected. 1363 tests skipped.
  • 2 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /html/browsers/browsing-the-web/scroll-to-fragid/scroll-frag-percent-encoded.html:
  └ PASS [expected FAIL] Fragment Navigation: fragment id should be percent-decoded

  ▶ Unexpected subtest result in /html/browsers/browsing-the-web/scroll-to-fragid/scroll-to-id-top.html:
  └ PASS [expected FAIL] Fragment Navigation: TOP is a valid element id, which overrides navigating to top of the document
```
wat

**Comment by KiChjang** [comment]
```
Ran 9969 tests finished in 955.0 seconds.
  • 9968 ran as expected. 131 tests skipped.
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /css-transitions-1_dev/html/detached-container-001.htm:
  │ FAIL [expected PASS] transition within detached container / values
  │   → assert_equals: no intermediate values expected 2 but got 1
  │ 
  │ .cases.values.done@http://web-platform.test:8000/css-transitions-1_dev/html/detached-container-001.htm:69:29
  │ runLoop/</</</<@http://web-platform.test:8000/css-transitions-1_dev/html/support/runParallelAsyncHarness.js:121:26
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1226:20
  │ runLoop/</</<@http://web-platform.test:8000/css-transitions-1_dev/html/support/runParallelAsyncHarness.js:120:21
  │ runLoop/</<@http://web-platform.test:8000/css-transitions-1_dev/html/support/runParallelAsyncHarness.js:119:17
  └ runLoop/<@http://web-platform.test:8000/css-transitions-1_dev/html/support/runParallelAsyncHarness.js:117:13
```

**Comment by SimonSapin** [comment]
@bors-servo retry

* #10549 
* #10753

**Comment by jdm** [comment]
@bors-servo: retry
* #10753 #10473

**Comment by jdm** [comment]
@bors-servo: retry
#10753

**Comment by Wafflespeanut** [comment]
@bors-servo retry

#10656 #10772

**Comment by perlun** [comment]
Gha, I hate those intermittent errors. :cry:

**Pull request merged**
