### PR TITLE
Rename SharedKeyboardAndMouseEventInit to EventModifierInit

### LINKED ISSUE #11611: Rename SharedMouseAndKeyboardEventInit to EventModifierInit
[The spec](https://w3c.github.io/uievents/#event-modifier-initializers) says that `KeyboardEventInit` and `MouseEventInit` should both inherit from `EventModifierInit`, not `SharedMouseAndKeyboardEventInit`.

The file components/script/dom/webidls/SharedMouseAndKeyboardEventInit.webidl should be renamed to components/script/dom/webidls/EventModifierInit.webidl and all references to `SharedMouseAndKeyboardEventInit` changed to `EventModifierInit`, in code and in the test.

Files:
* components/script/dom/webidls/KeyboardEvent.webidl
* components/script/dom/webidls/MouseEvent.webidl
* components/script/dom/webidls/SharedMouseAndKeyboardEventInit.webidl
* tests/wpt/web-platform-tests/html/dom/interfaces.html

### PR DESCRIPTION
**Pull request by zeusintuivo**
- [X] renamed file SharedMouseAndKeyboardEventInit,
- [X] changed SharedKeyboardAndMouseEventInit to EventModifierInit.
- [X] Rebased mozilla/master into it.
- [x] Ran build and tidy test without errors

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11611 (github issue number if applicable).

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12383)

### CODE REVIEW

**Comment by KiChjang** [comment]
Generally, we don't accept PRs with merge commits. Could you remove them and rebase your PR against master instead? This otherwise looks good to me, unless r? @nox

**Comment by nox** [comment]
As @KiChjang said, please rebase on top of master and remove the merge commit, and also please change the commit title to just "Rename SharedKeyboardAndMouseEventInit to EventModifierInit".

**Comment by zeusintuivo** [comment]
Done

**Comment by nox** [comment]
Can you change the commit title too? This is going to end up in the WPT repository too so I would like a clean message.

**Comment by zeusintuivo** [comment]
Done Commit Renaming

**Comment by larsbergstrom** [comment]
@bors-servo retry
- infra

**Pull request merged**
