### PR TITLE
Add a command line option to disable native titlebar

### PR DESCRIPTION
**Pull request by paulrouget**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7778)

### CODE REVIEW

**Comment by paulrouget** [comment]
The failure looks unrelated to me.

**Comment by metajack** [comment]
@bors-servo retry

- #7785

**Comment by paulrouget** [comment]
Intermittent? /2dcontext/drawing-images-to-the-canvas/drawimage_canvas_10.html

**Comment by pcwalton** [comment]
@bors-servo: retry

* #7778

**Pull request merged**
