### PR TITLE
MSVC support for Servo, and CMake builds for native code

### PR DESCRIPTION
**Pull request by vvuk**
This is the base PR for MSVC builds of servo and dependent crates.  It's got replacements in the Cargo.toml to pull in the right versions, to make sure that crates were properly converted to CMake for all other platforms, not just Windows.  (Servo builds with MSVC 2015 with this PR; also with 2013, though a manual change in rust-mozjs to select a different set of bindings is needed.)

This PR isn't quite ready yet, but I want bors-servo to do builds.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11756)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Given that Gecko is dropping 2013, is there any point to us trying to?

**Comment by vvuk** [comment]
@metajack can we get ninja installed on the builders, or should I try to figure out the parallel make issue?

**Comment by metajack** [comment]
This is looking good. I had a few comments, but the main stuff left to do is:

1. Land dependent PRs so that we can remove the [replace] section.
2. Update the other Cargo.locks if needed

---

Reviewed 9 of 9 files at r1, 11 of 11 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 10 of 10 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 7 of 7 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 8 of 8 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, 2 of 2 files at r19.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/script/build.rs, line 11 \[r10\]](https://reviewable.io:443/reviews/servo/servo/11756#-KMzpUjgsIWyBGY-R3ZW:-KMzpUjgsIWyBGY-R3ZX:-753071304) ([raw file](https://github.com/servo/servo/blob/48355fd6306b06c18046e5c69f077f1361e0b948/components/script/build.rs#L11)):*
> ```Rust
>     // parallelizes cmake's output properly.  (Cmake generates
>     // separate makefiles, each of which try to build
>     // ParserResults.pkl, and then stomp on eachother.)
> ```

I'm not sure what you mean by it generating separate makefiles. Which build generator did that? Nmake? You might mention that the VS generator serializes all custom commands, so they won't run in parallel even if it is successful. I seem to recall nmake had a similar behavior, but not 100% sure.

---

*[components/script/build.rs, line 20 \[r11\]](https://reviewable.io:443/reviews/servo/servo/11756#-KMzpqI8lG0p8wS42KSw:-KMzpqI8lG0p8wS42KSx:2063957122) ([raw file](https://github.com/servo/servo/blob/dc0a954d0192a9637b10ec58b03e081f17d41e4d/components/script/build.rs#L20)):*
> ```Rust
>     if target.contains("windows-msvc") {
>         // because we're using ninja, we need to explicitly set these
>         // to VC++, otherwise it'll try to use cc
> ```

I think we should use vcvars.bat to do this and check for the right stuff in mach. I don't remember needing to do any of this, but I was definitely running in cmd.exe shells that had run vcvars.bat

---

*[components/script/CMakeLists.txt, line 93 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11756#-KMznz2Ex4o-QN3LQqE8:-KMznz2Fibd3WHczUQx2:1468134811) ([raw file](https://github.com/servo/servo/blob/237faf32b425f3ded3faf30346083c4bffe77f9b/components/script/CMakeLists.txt#L93)):*
> ```CMake
> endforeach()
> 
> PREPEND(globalgen_out ${CMAKE_BINARY_DIR}/ ${globalgen_base_src})
> ```

Where were these going before? It's not clear why this bit is needed.

---

*[components/script/CMakeLists.txt, line 82 \[r19\]](https://reviewable.io:443/reviews/servo/servo/11756#-KMzrM-7qi37DVaVSEZk:-KMzrM-7qi37DVaVSEZl:-598479142) ([raw file](https://github.com/servo/servo/blob/3a5ae33fec82336c13ff21e529381afaa023250a/components/script/CMakeLists.txt#L82)):*
> ```CMake
> # below would cause GlobalGen.py to be executed each time.
> add_custom_target(ParserResults ALL DEPENDS ParserResults.pkl)
> add_custom_target(generate-bindings ALL)
> ```

Isn't this weird to have a target that has no dependencies?

---

*[components/servo/Cargo.toml, line 21 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11756#-KMzoWbtdCk7gIvoobo6:-KMzoWbubdi6jszxQxwS:275670638) ([raw file](https://github.com/servo/servo/blob/0583e9d975300c28235be380b6f2380ec14fdd4a/components/servo/Cargo.toml#L21)):*
> ```TOML
> bench = false
> 
> [replace]
> ```

We'll need to remove this when it's ready to finally land.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11756#-:-KMzrSib27ojkFRmdXuE:1276769411)*

**Comment by vvuk** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/script/build.rs, line 11 \[r10\]](https://reviewable.io:443/reviews/servo/servo/11756#-KMzpUjgsIWyBGY-R3ZW:-KN2IEKig7OgeUMpidbs:620723979) ([raw file](https://github.com/servo/servo/blob/48355fd6306b06c18046e5c69f077f1361e0b948/components/script/build.rs#L11)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> I'm not sure what you mean by it generating separate makefiles. Which build generator did that? Nmake? You might mention that the VS generator serializes all custom commands, so they won't run in parallel even if it is successful. I seem to recall nmake had a similar behavior, but not 100% sure.
</details>
I updated this comment to explain what was going on in the latest commit; but basically, if cmake has a custom command A for a target (RESULT), and that target depends on the output of another custom command B, it creates a rule that runs both B and A for RESULT.

So in our case, we had a command to generate ParserResults.pkl, and then each individual binding depended on ParserResults.pkl.  Without an intermediate target, every binding target re-created ParserResults.pkl first -- which would often error out with a pickle error, as one command was trying to read it while something else was stomping on it.

This happened with makefiles, msbuild, or ninja.  In a later commit once I figured out what was going on I fixed it, so in theory we could use any generator here, including msbuild... I kept it using ninja for msvc targets though.

---

*[components/script/build.rs, line 20 \[r11\]](https://reviewable.io:443/reviews/servo/servo/11756#-KMzpqI8lG0p8wS42KSw:-KN2KNB-ZcLrAIP8n1Sh:1208174713) ([raw file](https://github.com/servo/servo/blob/dc0a954d0192a9637b10ec58b03e081f17d41e4d/components/script/build.rs#L20)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> I think we should use vcvars.bat to do this and check for the right stuff in mach. I don't remember needing to do any of this, but I was definitely running in cmd.exe shells that had run vcvars.bat
</details>
The issue is that cmake makefiles/ninja/etc. will prefer cc/gcc before cl if it finds them -- so if you're running from a shell that has cc/gcc in the path at all, it won't choose cl.  The msbuild cmake generator prefers cl.

---

*[components/script/CMakeLists.txt, line 93 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11756#-KMznz2Ex4o-QN3LQqE8:-KN2L3wcVUzCURzMZlma:-2026669696) ([raw file](https://github.com/servo/servo/blob/237faf32b425f3ded3faf30346083c4bffe77f9b/components/script/CMakeLists.txt#L93)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> Where were these going before? It's not clear why this bit is needed.
</details>
They're all being generated in the cmake build dir, script-.../out/build.  We need them in script-.../out.  For the Bindings/*, we have the install(DIRECTORY... ) command, but for these one-off files that are not in the Bindings dir, we have to manually prepend the "build/" bit.

---

*[components/script/CMakeLists.txt, line 82 \[r19\]](https://reviewable.io:443/reviews/servo/servo/11756#-KMzrM-7qi37DVaVSEZk:-KN2K2FMV_ZK2rqQGz6e:590542171) ([raw file](https://github.com/servo/servo/blob/3a5ae33fec82336c13ff21e529381afaa023250a/components/script/CMakeLists.txt#L82)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> Isn't this weird to have a target that has no dependencies?
</details>
It does -- we add dependencies to it in the foreach() loop below.  But we have to create the target first before doing so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11756)*

**Comment by vvuk** [comment]
Hmm, we'll need to bump version numbers on everything as well... I forgot to do that, I'll make more PRs.

**Comment by metajack** [comment]
Ok. That all sounds good. Seems like we just need cargo [replace] fixes, version bumps, and a rebase and we're good to go.

**Comment by vvuk** [comment]
Note: this is waiting on smup #12255 to avoid having to land additional bindings etc in mozjs and then replacing them immediately after

**Comment by vvuk** [comment]
Hmm... tidy test:
> ./components/gfx/Cargo.toml:62: Line is longer than 120 characters

This is in a long [target.'cfg...] line. I don't think this can be split up into multiple?

**Comment by Wafflespeanut** [comment]
Maybe we should relax tidy a little bit :/

**Comment by nox** [comment]
Please remove the Make files you are replacing while you are at it.

**Comment by metajack** [comment]
I am totally fine with removing the tidy line length check for Cargo.tomls.

**Comment by larsbergstrom** [comment]
@vvuk How is this going? Is there anything I can do to help with this? Or is it just the CI failures? I'm happy to carry this through to landing, if you have done all of the work you want to and just need it muscled through the last little bit.

**Comment by UK992** [comment]
test-unit error on msvc, should be fixed by changing [testing_commands.py#L221](https://github.com/servo/servo/blob/master/python/servo/testing_commands.py#L221) to:
 ``env[b"RUST_BACKTRACE"] = b"1"``

**Comment by vvuk** [comment]
\o/ ! I'm guessing the msvc execution failure is not copying the ffmpeg DLLs in place.

**Comment by larsbergstrom** [comment]
Gah, looks like the CEF (and possibly geckolib?) Cargo.lock files are not updated:
```
error: failed to select a version for `expat-sys` (required by `servo-fontconfig-sys`):
all possible versions conflict with previously selected versions of `expat-sys`
  version 2.1.2 in use by expat-sys v2.1.2
  possible versions to select: 2.1.4
```

An easy way to "fix" this is to copy the components/servo/Cargo.lock over them and then do `./mach build-geckolib` and `./mach build-cef` to remove the extra bits.

Once @SimonSapin lands the removal of the `[replace]` for geckolib, I can land the move to cargo workspaces and we'll only have one Cargo.lock file.

**Comment by larsbergstrom** [comment]
@bors-servo r+

(the additional `checksum` blocks in geckolib seem spurious, but the builders will tell us if they're redundant via checking for a changed Cargo.lock file)

**Pull request merged**
