### PR TITLE
Improve implementation of media resource fetch algorithm

### PR DESCRIPTION
**Pull request by ferjm**
I have been observing inconsistent behaviors with my local tests depending of the media asset being played. I figured that we had these issues:

- We were setting the player EOS as soon as we got the first [process_response_eof](https://github.com/servo/servo/blob/1046ae58a155d3f1ab4d011242a03a81a712f3c4/components/script/dom/htmlmediaelement.rs#L1596). This is fine only if there is a single request. But that's not the case for multiple range requests or for seeks. Setting the player EOS makes the player appsrc reject any new buffers, and that breaks playback. Figuring out when is the right time to set the player EOS won't be a straight forward task, so my suggested fix for now is to simply not set it for now. It is a cleanup step that it would be nice to have but it is not mandatory.

- We were setting the input size more than once for multiple range requests and with the incorrect value. The fix uses the `content-length` or the `content-range` headers for single and range requests respectively.

- We were moving to the HaveEnoughData state if a fetch request succeded but no data was fetched from the network.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22433)

### CODE REVIEW

**Comment by ferjm** [comment]
I filed #22434 for setting the EOS back

**Comment by ceyusa** [comment]
r+

**Comment by ceyusa** [comment]
r+

\o/

**Comment by ferjm** [comment]
It seems that try is [happy](http://build.servo.org/builders/linux-rel-css/builds/11033).

@bors-servo r=ceyusa

**Pull request merged**
