### PR TITLE
Various textinput fixes

### PR DESCRIPTION
**Pull request by Manishearth**
- Currently the cursor sticks around if you click elsewhere. Now the text inputs are relayout-ed on blur.
- Currently whitespace gets collapsed in text input (https://github.com/servo/servo/issues/8772). Not anymore.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8983)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Want to add the regression test from #8722?

**Comment by Manishearth** [comment]
Done

**Comment by frewsxcv** [comment]
Why not a WPT reftest?

**Comment by Manishearth** [comment]
Yeah, I'm working on that, after I get #8543 working too.

**Comment by Manishearth** [comment]
I added a reftest. It compares against things with `&nbsp;` in their value (which used to work before). Let me know if I should add an image ref instead.

**Comment by KiChjang** [comment]
Travis CI fails to build right now.
```
$ bash etc/ci/manifest_changed.sh

diff --git a/tests/wpt/mozilla/meta/MANIFEST.json b/tests/wpt/mozilla/meta/MANIFEST.json

index 84262fa..7fccb08 100644

--- a/tests/wpt/mozilla/meta/MANIFEST.json

+++ b/tests/wpt/mozilla/meta/MANIFEST.json

@@ -2431,6 +2431,18 @@

             "url": "/_mozilla/css/input_whitespace.html"

           }

         ],

+        "css/input_whitespace_ref.html": [

+          {

+            "path": "css/input_whitespace_ref.html",

+            "references": [

+              [

+                "/_mozilla/css/input_whitespace_ref.html",

+                "=="

+              ]

+            ],

+            "url": "/_mozilla/css/input_whitespace_ref.html"

+          }

+        ],

         "css/inset.html": [

           {

             "path": "css/inset.html",

@@ -8316,6 +8328,18 @@

           "url": "/_mozilla/css/input_whitespace.html"

         }

       ],

+      "css/input_whitespace_ref.html": [

+        {

+          "path": "css/input_whitespace_ref.html",

+          "references": [

+            [

+              "/_mozilla/css/input_whitespace_ref.html",

+              "=="

+            ]

+          ],

+          "url": "/_mozilla/css/input_whitespace_ref.html"

+        }

+      ],

       "css/inset.html": [

         {

           "path": "css/inset.html",

The command "bash etc/ci/manifest_changed.sh" exited with 1.
```

**Comment by Manishearth** [comment]
I used create-wpt to create the test, and it added those changes. Not sure why they're failing.

**Comment by Manishearth** [comment]
Fixed.

**Comment by Manishearth** [comment]
Rebased.

**Comment by Manishearth** [comment]
Rebased

**Comment by jdm** [comment]
-S-awaiting-review -S-needs-rebase +S-needs-code-changes 

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/document.rs, line 598 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8983#-K7I3SkWGicart8aYL6P:-K7I3SkWGicart8aYL6Q:-413903205) ([raw file](https://github.com/servo/servo/blob/539ee18cf0e50ba0e2469d6706e9215bb637fc76/components/script/dom/document.rs#L598)):*
I propose instead that set_focus_state should mark the node dirty, instead of adding a new virtual call.

---

*[components/script/dom/virtualmethods.rs, line 107 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8983#-K7I3gMkAOhP0A3sd8fE:-K7I3gMkAOhP0A3sd8fF:-635271434) ([raw file](https://github.com/servo/servo/blob/539ee18cf0e50ba0e2469d6706e9215bb637fc76/components/script/dom/virtualmethods.rs#L107)):*
No need for this with my previous suggestion.

---

*[tests/wpt/mozilla/tests/css/input_whitespace.html, line 1 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8983#-K7I5U6H8Qo0BEgySVCe:-K7I5U6H8Qo0BEgySVCf:-1572135199) ([raw file](https://github.com/servo/servo/blob/539ee18cf0e50ba0e2469d6706e9215bb637fc76/tests/wpt/mozilla/tests/css/input_whitespace.html#L1)):*
I was going to ask that this go in http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/html/rendering/bindings/the-input-element-as-a-text-entry-widget/ but noticed that the spec doesn't mention whitespace behaviour. I've filed https://github.com/whatwg/html/issues/470 and we can move it after that's resolved.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8983#-:-K7I5jtZSHG_ObVVxEkP:904062486)*

**Comment by Manishearth** [comment]
Fixed

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/element.rs, line 1907 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8983#-K7PxsgR3WeMFyOpxafq:-K7PxsgR3WeMFyOpxafr:934279753) ([raw file](https://github.com/servo/servo/blob/afce1af185b95a32018b3d44ae0c86296e2eb84c/components/script/dom/element.rs#L1907)):*
I think we should dirty the node regardless of the new state.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8983#-:-K7Py30i8zxVIAx4wgmL:1458266033)*

**Comment by Manishearth** [comment]
Done

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8983#-:-K7Ri2H82vVo4byzwYKL:-317921516)*

**Pull request merged**
