### PR TITLE
Revert "Update WR (various reftest fixes)."

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13189)

### CODE REVIEW

**Comment by glennw** [comment]
The vertex texture fetch changes are causing issues on *some* mac machines. Revert this webrender update until I can figure out what is going on.

**Comment by glennw** [comment]
r? anyone

**Comment by glennw** [comment]
@bors-servo retry

* #13059

**Comment by glennw** [comment]
@bors-servo retry
* #13165

**Comment by KiChjang** [comment]
@bors-servo retry
* #13165

**Pull request merged**
