### PR TITLE
Use an already-installed Homebrew at /usr/local

### PR DESCRIPTION
**Pull request by SimonSapin**
This requires https://github.com/servo/taskcluster-config/pull/4 to be deployed.

Having the standard location helps `pkg-config` (CC https://github.com/servo/servo/pull/24688), and allows installing pre-compiled pakcages (which is much faster than compiling from source).

### CODE REVIEW

**Comment by SimonSapin** [comment]
Since the queue is busy I stuffed some other changes in this PR. The most significant one is making use of https://github.com/servo/taskcluster-config/pull/6, which cuts several minutes from each macOS task.

**Comment by SimonSapin** [comment]
@bors-servo r=jdm
https://github.com/servo/servo/issues/24611

**Comment by SimonSapin** [comment]
@bors-servo retry

```
  ▶ TIMEOUT [expected PASS] /css/CSS2/colors/color-002.xht
  │ 
  │ 
  │ 
  │ 
  │ 0:00:13.447396000 37319 0x7fdc7c6672c0 WARN      GST_PLUGIN_LOADING gstplugin.c:793:GstPlugin *_priv_gst_plugin_load_file_for_registry(const gchar *, GstRegistry *, GError **): module_open failed: dlopen(/usr/local/lib/gstreamer-1.0/libgstgtk.so, 2): Library not loaded: /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
  │   Referenced from: /usr/local/lib/gstreamer-1.0/libgstgtk.so
  │   Reason: Incompatible library version: libgstgtk.so requires version 2407.0.0 or later, but libgtk-3.0.dylib provides version 2406.0.0
  │ 
  │ (gst-plugin-scanner:37319): GStreamer-WARNING **: 09:49:43.222: Failed to load plugin '/usr/local/lib/gstreamer-1.0/libgstgtk.so': dlopen(/usr/local/lib/gstreamer-1.0/libgstgtk.so, 2): Library not loaded: /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
  │   Referenced from: /usr/local/lib/gstreamer-1.0/libgstgtk.so
  └   Reason: Incompatible library version: libgstgtk.so requires version 2407.0.0 or later, but libgtk-3.0.dylib provides version 2406.0.0
  ▶ TIMEOUT [expected PASS] /FileAPI/url/url_xmlhttprequest_img.html
  │ 
  │ 
  │ 
  │ 
  │ 0:00:13.447362000 37318 0x7f9730e6b2c0 WARN      GST_PLUGIN_LOADING gstplugin.c:793:GstPlugin *_priv_gst_plugin_load_file_for_registry(const gchar *, GstRegistry *, GError **): module_open failed: dlopen(/usr/local/lib/gstreamer-1.0/libgstgtk.so, 2): Library not loaded: /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
  │   Referenced from: /usr/local/lib/gstreamer-1.0/libgstgtk.so
  │   Reason: Incompatible library version: libgstgtk.so requires version 2407.0.0 or later, but libgtk-3.0.dylib provides version 2406.0.0
  │ 
  │ (gst-plugin-scanner:37318): GStreamer-WARNING **: 09:49:43.222: Failed to load plugin '/usr/local/lib/gstreamer-1.0/libgstgtk.so': dlopen(/usr/local/lib/gstreamer-1.0/libgstgtk.so, 2): Library not loaded: /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
  │   Referenced from: /usr/local/lib/gstreamer-1.0/libgstgtk.so
  └   Reason: Incompatible library version: libgstgtk.so requires version 2407.0.0 or later, but libgtk-3.0.dylib provides version 2406.0.0
  ▶ TIMEOUT [expected PASS] /css/CSS2/colors/color-004.xht
  │ 
  │ 
  │ 
  │ 
  │ 0:00:13.447390000 37317 0x7fd82b2526c0 WARN      GST_PLUGIN_LOADING gstplugin.c:793:GstPlugin *_priv_gst_plugin_load_file_for_registry(const gchar *, GstRegistry *, GError **): module_open failed: dlopen(/usr/local/lib/gstreamer-1.0/libgstgtk.so, 2): Library not loaded: /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
  │   Referenced from: /usr/local/lib/gstreamer-1.0/libgstgtk.so
  │   Reason: Incompatible library version: libgstgtk.so requires version 2407.0.0 or later, but libgtk-3.0.dylib provides version 2406.0.0
  │ 
  │ (gst-plugin-scanner:37317): GStreamer-WARNING **: 09:49:43.222: Failed to load plugin '/usr/local/lib/gstreamer-1.0/libgstgtk.so': dlopen(/usr/local/lib/gstreamer-1.0/libgstgtk.so, 2): Library not loaded: /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
  │   Referenced from: /usr/local/lib/gstreamer-1.0/libgstgtk.so
  └   Reason: Incompatible library version: libgstgtk.so requires version 2407.0.0 or later, but libgtk-3.0.dylib provides version 2406.0.0

  ▶ TIMEOUT [expected PASS] /css/css-text-decor/text-underline-offset-scroll-001.html
  │ 
  │ 
  │ 
  │ 
  │ No URL for Core Text font! (thread FontCacheThread, at src/libcore/option.rs:1187)
  │ stack backtrace:
  │    0: backtrace::backtrace::trace
  │    1: backtrace::capture::Backtrace::new
  │    2: servo::main::{{closure}}
  │    3: std::panicking::rust_panic_with_hook
  │    4: std::panicking::continue_panic_fmt
  │    5: rust_begin_unwind
  │    6: core::panicking::panic_fmt
  │    7: core::option::expect_failed
  │    8: gfx::platform::macos::font_template::FontTemplateData::bytes
  │    9: gfx::font_cache_thread::FontCache::run
  │   10: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   11: _ZN3std9panicking3try7do_call17h2bca40d5ab25b1b9E.llvm.18247778191580573126
  │   12: __rust_maybe_catch_panic
  │   13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  │   15: std::sys::unix::thread::Thread::new::thread_start
  │   16: _pthread_body
  │   17: _pthread_start
  │ 
  │ [2019-11-17T09:58:05Z ERROR servo] No URL for Core Text font!
  │ Font cache thread has already exited. (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/gfx/font_cache_thread.rs:547)
  │ stack backtrace:
  │    0: backtrace::backtrace::trace
  │    1: backtrace::capture::Backtrace::new
  │    2: servo::main::{{closure}}
  │    3: std::panicking::rust_panic_with_hook
  │    4: std::panicking::begin_panic
  │    5: <gfx::font_cache_thread::FontCacheThread as gfx::font_context::FontSource>::font_template
  │    6: gfx::font_context::FontContext<S>::font
  │    7: gfx::font::FontGroup::find_by_codepoint
  │    8: layout::text::TextRunScanner::scan_for_runs
  │    9: std::thread::local::LocalKey<T>::with
```

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by jdm** [comment]
@bors-servo retry
* #13480

**Comment by SimonSapin** [comment]
Oops, I still had a browser tab opened that did not update after https://github.com/servo/servo/pull/24753#issuecomment-554735291

**Pull request merged**
