### PR TITLE
canvas: Deallocate WebRender images on canvas 

### LINKED ISSUE #11062: WebRender + Canvas repaints cause huge memory leak.
I've made a simple test page for this issue, and when any of the three actions in the JS is performed (setting canvas size, clearing canvas or drawing randomized lines) in a fast loop (works with setInterval and requestAnimationFrame), the memory usage goes up to a gigabyte in somewhere around a minute.

I also tested it with WebRender disabled and it seems not to occur then. The command I used to launch it was "./mach run -r -w [filename]".

[CanvasTest.zip](https://github.com/servo/servo/files/253290/CanvasTest.zip)

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #11062.
- [x] These changes do not require tests because it's wr-only.

r? @glennw

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11750)

### CODE REVIEW

**Comment by emilio** [comment]
Depends on: #11744, servo/webrender_traits#57, and servo/webrender#292

**Comment by glennw** [comment]
@emilio Is this ready to go now?

**Comment by emilio** [comment]
@glennw: well, @pcwalton hasn't reviewed #11744, but if you sign-off it, this should be ready to go.

**Pull request merged**
