### PR TITLE
Add a tool for comparing Dromaeo outputs

### PR DESCRIPTION
**Pull request by jdramani**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7759)

### CODE REVIEW

**Comment by jdramani** [comment]
I have not added a class for formatting terminal outputs. But if you want me to add then pls let me know where it should go.

**Comment by nox** [comment]
Nice work! I can't wait to see this integrated somehow to our continuous integration platform.

**Comment by mbrubeck** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7759)

**Comment by mbrubeck** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
