### PR TITLE
test-tidy: Check for space between function name and `(`

### LINKED ISSUE #13980: Add a tidy check for spaces between function names and (
Code like `fn foo (..)` and `something (...)` should be flagged by `./mach test-tidy`, since typical Rust style is to avoid adding spaces between function names and the opening parenthesis.

Code: `python/tidy/servo_tidy/tidy.py` (add a new rule to `regex_rules`)
Test: add incorrect code to `python/tidy/servo_tidy_tests/rust_tidy.rs`, then update `python/tidy/servo_tidy_tests/test_tidy.py` and run `./mach test-tidy --self`.

### PR DESCRIPTION
**Pull request by dsprenkels**
Disallow an extraneous space in a function call between
the function name and the opening parenthesis in Rust
code, while ignoring macro declarations.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy --all` does not report any errors
- [x] `./mach test-tidy --self` does not report any errors
- [x] These changes fix #13980

- [x] There are tests for these changes, these are written in
 - `python/tidy/servo_tidy_tests/rust_tidy.rs`
 - `python/tidy/servo_tidy_tests/test_tidy.py`
- [ ] These changes do not require tests

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13988)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Please claim the issue before working on it.

**Comment by dsprenkels** [comment]
@Wafflespeanut Sorry for not claiming the issue. I'll make sure I claim them beforehand from now on. (I was afraid for committing on the issue, not being sure if I could provide a suitable fix.)

**Comment by dsprenkels** [comment]
I see I actually badly reported that I did not submit any tests. I just fixed this in the PR description.

**Comment by jdm** [comment]
`./python/tidy/servo_tidy/tidy.py:447: E128 continuation line under-indented for visual indent`

**Comment by Wafflespeanut** [comment]
Looks pretty neat to me. r=me after fixing that flake error :)

**Pull request merged**
