### PR TITLE
MIMEClassifier::classify always succeeds; fix the type to reflect this.

### PR DESCRIPTION
**Pull request by eefriedman**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7967)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-awaiting-answer 


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/mime_classifier.rs, line 45 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7967#-K0YUVba_pHTEzYdpJnU)** ([raw file](https://github.com/servo/servo/blob/a4870aad27fe5919794ec39a053e51d9faf42736/components/net/mime_classifier.rs#L45)):</sup>
Why this change?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7967)

**Comment by eefriedman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/mime_classifier.rs, line 45 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7967#-K0YUVba_pHTEzYdpJnU)** ([raw file](https://github.com/servo/servo/blob/a4870aad27fe5919794ec39a053e51d9faf42736/components/net/mime_classifier.rs#L45)):</sup>
A few lines later, the function calls `supplied_type.clone()`... that needs to result in `(String, String)`, not `Option<(String, String)>`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7967)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-answer 


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7967)

**Comment by eefriedman** [comment]
Fixed unit-test.

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Pull request merged**
