### PR TITLE
Expose javascript:window.alert() to libsimpleservo

### PR DESCRIPTION
**Pull request by paulrouget**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23801)

### CODE REVIEW

**Comment by paulrouget** [comment]
> Why do we want to leak this memory?

I haven't found a way to make Alert synchronous in the HoloLens code for now, so the string will be dropped early. And we leak all the strings in the capi.

Or I could just copy the string in HoloLens.

**Comment by jdm** [comment]
Ok, I'll file a followup for moving away from leaking all strings in the capi in that case :)
@bors-servo r+

**Comment by CYBAI** [comment]
In `magicleap` build:

```rust
error[E0046]: not all trait items implemented, missing: `on_alert`
   --> ports/libmlservo/src/lib.rs:338:1
    |
338 | impl HostTrait for HostCallbacks {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `on_alert` in implementation
    |
    = note: `on_alert` from trait: `fn(&Self, std::string::String)`

error: aborting due to previous error
```

**Pull request merged**
