### PR TITLE
Update cargo

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @Manishearth (or whomever)

This Cargo update has two big features we like:
1) Much better output from `RUST_LOG=cargo::ops::cargo_rustc::fingerprint=info`
2) Far fewer unnecessary rebuilds of the script & layout crate (at least in my experience testing it)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8375)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Weird! This works on my OSX and Linux boxes. @alexcrichton have you seen this failure before? We're updating to yesterday's nightly Cargo:
```
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-m64" "-L" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/servo.0.o" "-o" "/home/servo/buildbot/slave/linux-dev/build/target/debug/servo" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/angle-ee9dc8911de0d6f3/out" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/azure-02d2460d0e135e86/out" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/fontconfig-sys-1f38cf9d1e1a4d19/out" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/harfbuzz-sys-c803ba98b97fb9d7/out/lib" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/hbs-pow-sys-4f2a0dd8d72ac62e/out/_build/lib" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/js-1b3537edd7ef8c3c/out" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/miniz-sys-fa48ce1a538dca79/out" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/mozjs_sys-e411d274df144795/out/dist/lib" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/openssl-sys-f0bee5fb97afc90d/out" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/skia-d333fdba915552af/out" "-L" "/home/servo/buildbot/slave/linux-dev/build/target/debug/build/stb_image-1f6702ea4c6749c2/out" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/servo/buildbot/slave/linux-dev/build/components/servo/.rust/lib/x86_64-unknown-linux-gnu" "-L" "/home/servo/buildbot/slave/linux-dev/build/components/servo/lib/x86_64-unknown-linux-gnu" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libenv_logger-9877a407b506c549.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/libservo.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libnet-4dd79285fabfde23.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libprofile-4f93fca3eefa422d.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libhbs_pow-29607ae2c5d97f00.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libhbs_pow_sys-4f2a0dd8d72ac62e.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libbrotli-86a895eac0ac4ff9.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liblayout-cec166994bf2c4c2.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libscript-9e17fd85f2564550.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libwebsocket-d9dc4cbabbfe284b.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libangle-ee9dc8911de0d6f3.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libcaseless-a92ff95a6c11bb0c.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libclock_ticks-4e910fa1778932df.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libserde_json-363b4f85f577417b.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libunicode_normalization-78fb2197226c310a.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libunicode_bidi-28d517779a365a0b.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libuuid-e3cfaf8f9acfc716.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libhbs_common_sys-7e5134c1d10f6a51.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libglutin_app-afbab504f12a2ee7.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libglutin-06f2ddee88e17546.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libosmesa_sys-498014c9e0ce79d5.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libcompositing-3140f47efb866679.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liblayout_traits-6aabb359616b6897.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libclipboard-894de032d612d710.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libwayland_window-aa8c09937ab4ec50.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libtempfile-91489cdece569e6b.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libgfx-c6ebdf6330620db4.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libstyle-9de4c56c4fb593b9.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libscript_traits-235dd64f0fb1ed6e.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libprofile_traits-6d824cd72b9103f5.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig-98a34dc6c01f3190.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libnet_traits-529214524b54097d.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libregex-c5abedf84fe61ddb.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libregex_syntax-6d9e9f3bd76497d4.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libstb_image-1f6702ea4c6749c2.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libunicode_script-cf2058d473e757bb.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libwayland_kbd-b9034ccf21ee13d1.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libmmap-e119158b3cffea45.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libbitflags-dd68b8369bcd8ff0.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libimage-2923d624ae61adbe.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libgif-91f540bfc42dbd3f.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libenum_primitive-0dc42c1f3182f8bc.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libpng-71c0461c4b812283.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libflate2-98f57e2f7af2d432.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libminiz_sys-fa48ce1a538dca79.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libaho_corasick-4235a5ba781fe1b1.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libmemchr-1ef94c8f78e37fc7.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libsimd-7ff109c8a97d92b8.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libwayland_client-9985527036c83b6b.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libdlib-c93cf01a2438fd25.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libexpat_sys-e22582e7d0e6b2e6.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libharfbuzz_sys-c803ba98b97fb9d7.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libcolor_quant-6695fde28ee2e395.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libx11_dl-93e3054d0a700b91.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libdylib-41a627506b9909f5.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libcanvas-0caffea7ad7ed073.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liblzw-f4c4a3ecf5835e0f.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libdevtools-a08b91471589dd77.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libdevtools_traits-18e152017974d3e8.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libmsg-ef99ab0f3e56aedd.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libcanvas_traits-2312b5694ef3b869.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liboffscreen_gl_context-cc3be91171f9cf84.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libstyle_traits-2f161ae4f5318a09.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libutil-5a5a2fa59dec104f.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libhtml5ever-8214c9985aaecbe4.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libgetopts-1be2f24cd9708e15.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/librc-c5d6d71555bcc452.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liblayers-847af0c24c0bb6f7.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libapp_units-643be3b30adb1afe.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libphf-67f3c539a431de21.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libtendril-6ef15ef6855d281c.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libselectors-9a6105985a7bfc96.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libcssparser-cd1913e4082b7004.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libstring_cache-d9ae2575d311b42d.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfutf-2d68187ed3b54e00.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libstring_cache_shared-256621bc2a16d3c7.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libphf_shared-3160efea5fa48a57.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libdebug_unreachable-bb8686e7201a0fcf.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libmac-9253dcbe1dddc564.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libipc_channel-35faaae5f49b95f7.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libbincode-7985896c8cc576c9.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libbyteorder-3e27c88aa235985f.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libhyper-6fff3aee9b6153fe.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libtraitobject-e8fd97c9f52dc0fb.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libcookie-e6818e9cbd9a23bd.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libopenssl-9e4539c913eed78d.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libopenssl_sys-f0bee5fb97afc90d.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libmime-895d454306901c0a.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libbitflags-c495827ddcd6a202.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libunicase-1487702606f8b2d5.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libhttparse-85f05eaebae0e7de.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liburl-5247f81b4a7b5841.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libmatches-68291f81832fc22d.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libnum_cpus-a42ee6f13e06854f.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libencoding-a635ee1112a4a115.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libencoding_index_simpchinese-36d98fe1ee6656fc.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libencoding_index_japanese-02d1e3db3f81af39.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libencoding_index_tradchinese-1ea03524459844c3.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libgfx_traits-be08912a06549bad.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libazure-02d2460d0e135e86.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libskia-d333fdba915552af.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libglx-3a94d6d02aa3bea2.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libx11-44f211d41b539b51.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfreetype_sys-6942b42598677f74.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libgleam-7c85d276d7e3c71c.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libgl_common-191611e16c4da32b.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfreetype-bc804dedae87cd10.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liblanguage_tags-97753499b1120d44.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libencoding_index_korean-e6ea16a131576deb.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libjs-1b3537edd7ef8c3c.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libmozjs_sys-e411d274df144795.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liblibz_sys-e8e1552876cd3abe.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libtime-60470bfe19faf27e.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libsmallvec-464dc4542849ab4f.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libsolicit-699226f9674a00ef.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libhpack-37abaf37ec66685c.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libencoding_index_singlebyte-989206689effef1e.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libdebug_builders-337a04ff86d82ad7.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libeuclid-8278f0e00fa18dd6.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liblog-35171053ffe7ab96.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libheapsize-b60be8a7511f3e50.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libserde-854905b9f092a3f1.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libquickersort-4ee5a0d175320e87.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libnum-397f282c1d72fe58.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/librustc_serialize-7ff5bfc027146194.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libunreachable-3dea623717e22df5.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libvoid-bc07a168f02e800d.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/librand-bdfcc55d3466feb3.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libtypeable-3d4cacf3175a54fa.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libshared_library-5803f342d4deed60.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liblibc-144c435538abd757.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/liblazy_static-f3aa6dfcc7c157cc.rlib" "/home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfnv-5893ac1ec1276f44.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libserialize-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-bb943c5a.rlib" "/home/servo/.servo/rust/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown-linux-gnu/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-bb943c5a.rlib" "-l" "stdc++" "-l" "rt" "-l" "expat" "-l" "stdc++" "-l" "ssl" "-l" "crypto" "-l" "skia" "-l" "GL" "-l" "stdc++" "-l" "freetype" "-l" "bz2" "-l" "fontconfig" "-l" "expat" "-l" "X11" "-l" "azure" "-l" "stdc++" "-l" "bz2" "-l" "GL" "-l" "Xcursor" "-l" "Xxf86vm" "-l" "X11" "-l" "Xmu" "-l" "Xt" "-l" "X11" "-l" "freetype" "-l" "freetype" "-l" "jsglue" "-l" "stdc++" "-l" "z" "-l" "rt" "-l" "c" "-l" "m" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "rt" "-l" "pthread" "-l" "c" "-l" "m" "-fuse-ld=gold" "-l" "compiler-rt"
note: /usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fccfg.o): requires dynamic R_X86_64_PC32 reloc against 'free' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fccharset.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcdbg.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcdefault.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcdir.o): requires dynamic R_X86_64_PC32 reloc against '__lxstat' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcfreetype.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcfs.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fchash.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcinit.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fclang.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fclist.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcmatch.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcmatrix.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcname.o): requires dynamic R_X86_64_PC32 reloc against '__ctype_b_loc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcobjs.o): requires dynamic R_X86_64_PC32 reloc against 'strcmp' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcpat.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcserialize.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcstat.o): requires dynamic R_X86_64_PC32 reloc against 'fstatfs' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcstr.o): requires dynamic R_X86_64_PC32 reloc against 'strlen' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcxml.o): requires unsupported dynamic reloc 11; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcblanks.o): requires dynamic R_X86_64_PC32 reloc against 'malloc' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fccache.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fccompat.o): requires dynamic R_X86_64_PC32 reloc against '__open_2' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /home/servo/buildbot/slave/linux-dev/build/target/debug/deps/libfontconfig_sys-1f38cf9d1e1a4d19.rlib(fcatomic.o): requires dynamic R_X86_64_PC32 reloc against 'strlen' which may overflow at runtime; recompile with -fPIC
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Could not compile `servo`.

To learn more, run the command again with --verbose.
```

**Comment by alexcrichton** [comment]
Hm I can't say I've seen that before, but it does look legitimate at least? I'm not sure what change in Cargo would have prompted that, however.

**Comment by larsbergstrom** [comment]
Yeah, that's what I was curious about, too - the only change is to Cargo, so I'm not sure what's happening. There also weren't any stealth updates to libfontconfig. I'll try to repro locally. Thanks!

**Comment by larsbergstrom** [comment]
grrrr, can't repro locally.

@metajack, how does one log in to the Linux builders now that they're on EC2?

**Comment by metajack** [comment]
You have to get the IP from AWS console and then ssh in that as normal. The current IPs are:
52.25.219.205
52.32.154.134

**Comment by larsbergstrom** [comment]
Hrm, we've been compiling with `-fPIC` since sept 2014 (https://github.com/servo/libfontconfig/commit/b21767c04287d2bf428b1acd9a5a2dfff22b4943), which makes sense because it wouldn't work on Android otherwise.

**Comment by larsbergstrom** [comment]
@metajack Oh, an easier way for people with root is just to log in to servo-master and look at the buildbot log. When the EC2 machines connect, there will be an IP there.

CC @Manishearth

**Comment by Manishearth** [comment]
Oh, that's cool.

Should we perhaps note these in separate files so that `ssh servo-linux1` works on servo-master?

**Comment by larsbergstrom** [comment]
@Manishearth I'll at least add a note to buildbot-administration about how to find it, since I'll probably forget by tomorrow :-)

I was able to reproduce the `-fPIC` error, but it's super confusing because the generated Makefile for libfontconfig definitely has it listed in the CFLAGS. This is another case where https://github.com/rust-lang/cargo/issues/1106 for verbose logging including the output from the compilation would *really* help.

**Comment by Manishearth** [comment]
Edited it in. https://github.com/servo/servo/wiki/Buildbot-administration#ip-addresses

**Comment by metajack** [comment]
The real fix for this is that we'll have static IPs once we move to the Servo specific EC2 account.

**Pull request closed without merging**
