### PR TITLE
Added check for the existence of for and element attribute when preparing a script

### LINKED ISSUE #5258: Script for/event attributes should only be considered if they're both present.
Blocks #2968.

* Spec: <https://html.spec.whatwg.org/multipage/#prepare-a-script> (step 12).
* Code: `components/script/dom/htmlscriptelement.rs`.
* Test: `html/semantics/scripting-1/the-script-element/script-for-event.html`.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #5258

### CODE REVIEW

**Comment by KiChjang** [comment]
Squashed, r? @Ms2ger

**Comment by Ms2ger** [comment]
Looks like there are issues with the rooting. Please try putting the roots in local bindings and matching on `(for.r(), event.r())`.

**Comment by Ms2ger** [comment]
I'm going to have to ask you to build before pushing.

**Comment by metajack** [comment]
Assigned to @ms2ger since he was already reviewing this.

**Comment by Ms2ger** [comment]
Rebased as https://github.com/servo/servo/pull/5474

**Pull request closed without merging**
