### PR TITLE
Investigations for #7787

### PR DESCRIPTION
**Pull request by jdm**
I'm just going to keep throwing stuff at try, because running directly on the builders isn't yielding results.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8314)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8314)

**Comment by jdm** [comment]
@bors-servo: retry
* #8339

**Comment by jdm** [comment]
@bors-servo: retry
* #8191

**Pull request merged**
