### PR TITLE
Avoid sending idle message more than once after a reflow is complete

### LINKED ISSUE #22410: Only send one SetDocumentState message, not an infinite number
When the document is finished loading and there are no pending images to load, the script thread continues to send a SetDocumentState message every time a reflow is complete. This is unnecessary; we should not need to send more than one. We should add a boolean to Window to avoid this.

Code: https://github.com/servo/servo/blob/160f1137fb66408f98e952df8b6b93df16fd7ee1/components/script/dom/window.rs#L1549

### PR DESCRIPTION
**Pull request by kingdido999**
A boolean variable is introduced to prevent sending SetDocumentState idle message multiple times after a reflow is complete.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22410 (GitHub issue number if applicable)

- [x] These changes do not require tests because automated test is not possible.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22451)

### CODE REVIEW

**Comment by kingdido999** [comment]
Please let me know if any test is needed for this change.

**Comment by jdm** [comment]
I don't think there's any way to write an automated test for it.

**Comment by jdm** [comment]
@bors-servo try-
We don't actually care about the try job.

**Comment by CYBAI** [comment]
@bors-servo retry

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Link with onclick form submit to javascript url with document.write and href navigation ", 
    "test": "/html/browsers/browsing-the-web/navigating-across-documents/009.html", 
    "line": 150123, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/forms/the-textarea-element/textarea-textLength.html", 
    "line": 172978, 
    "action": "test_result", 
    "expected": "OK"
}
```

**Comment by CYBAI** [comment]
@bors-servo retry

- #22445

**Comment by CYBAI** [comment]
@bors-servo retry

- oom

**Pull request merged**
