### PR TITLE
Don’t install rust-docs, rust-src, or clippy on CI

### PR DESCRIPTION
**Pull request by SimonSapin**
See https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html#profiles

### CODE REVIEW

**Comment by SimonSapin** [comment]
Alright, managed to observe the desired behavior on [Windows](https://tools.taskcluster.net/groups/O2eoLFiJQCaE_3_cAc5Elw/tasks/GJWaAIfYS16jdhUarVvluw/runs/0/logs/public%2Flogs%2Flive.log#L290), [macOS](https://tools.taskcluster.net/groups/Pq9v7SIjTp2A5CNc_QuRWw/tasks/YDD2uWGQTBWb54WiYiUZaQ/runs/0/logs/public%2Flogs%2Flive.log#L290), and [Linux](https://tools.taskcluster.net/groups/GiSax0dYTeq3KX-8sRPXqQ/tasks/U3kOLetjTjKEw434UdMOjQ/runs/0/logs/public%2Flogs%2Flive.log#L522). This PR should be good now.

In my first attempt nothing happened on macOS because the worker already had that version of Rust Nightly installed, so I wanted to have a look at what’s on each server:

```
% for i in $(seq 1 7); ssh -o 'BatchMode=yes' servo-tc-mac$i.servo.org du -sh /Users/worker/.rustup/toolchains
 21G	/Users/worker/.rustup/toolchains
 21G	/Users/worker/.rustup/toolchains
root@servo-tc-mac3.servo.org: Permission denied (publickey,password,keyboard-interactive).
root@servo-tc-mac4.servo.org: Permission denied (publickey,password,keyboard-interactive).
root@servo-tc-mac5.servo.org: Permission denied (publickey,password,keyboard-interactive).
root@servo-tc-mac6.servo.org: Permission denied (publickey,password,keyboard-interactive).
root@servo-tc-mac7.servo.org: Permission denied (publickey,password,keyboard-interactive).
```

I expected each worker to have [my key](https://github.com/servo/saltfs/blob/master/admin/files/ssh/simonsapin.pub) configured through [salt](https://github.com/servo/servo/blob/882dcc8408159bed5633337d11e83b6839f97e34/etc/taskcluster/macos/states/generic-worker.sls#L9-L15). @jdm, are workers to 3 to 7 configured differently?

**Comment by jdm** [comment]
Looks like those workers had never been salted since the ssh key changes.

**Comment by jdm** [comment]
Does this have any impact on our code that tries to merge the standard library docs with our project docs?

**Comment by SimonSapin** [comment]
Oh that’s a good point. That task likely needs `rustup component add rust-docs` or similar. I’ll add it.

**Comment by SimonSapin** [comment]
https://tools.taskcluster.net/groups/fRGfWK7SQze62WwLbxe1PA/tasks/T6SB8V5eS3u0ZwfpH08wZw/runs/0/logs/public%2Flogs%2Flive.log#L2530 ran without error, I wonder if it copied an empty directory.

**Comment by SimonSapin** [comment]
Ah, foiled again by `~/.rustup` being cached on workers. Here is a proper [before](https://tools.taskcluster.net/groups/T_2d3HBfT7qe_8uCYvljRg/tasks/T7atzoWOQcyeIhoH9eBCLw/runs/0/logs/public%2Flogs%2Flive.log#L546) and [after](https://tools.taskcluster.net/groups/BEepKdCQQzO7dP8gBcFEKQ/tasks/Ujp_XgE5Sn-XqSP4c12fdw/runs/0/logs/public%2Flogs%2Flive.log#L582), with the fix now in this PR.

> Looks like those workers had never been salted since the ssh key changes.

My key hasn’t changed in a couple years, though? Trying again now, I can access all macOS workers except # 2 and 9.

**Comment by jdm** [comment]
There is no worker 9. I missed 2; I have now deployed the keys to that worker.

**Comment by SimonSapin** [comment]
Our Macstadium account shows 9 machines, and `servo-tc-mac9.servo.org` resolves to the corresponding IP address. Anyway, I’ve filed https://github.com/servo/servo/issues/24520.

This PR is ready for review.

**Pull request merged**
