### PR TITLE
Layout_thread: removed all possible opts::get()

### PR DESCRIPTION
**Pull request by oneturkmen**
Removed almost all `opts::get()` from components/layout_thread. The untouched one is used by [`get_ua_stylesheets()`](https://github.com/servo/servo/blob/2ad3066d7c92c504838f72aaca73bec44048cb58/components/layout_thread/lib.rs#L1924), which is in turn used by [`lazy_static!`](https://github.com/servo/servo/blob/2ad3066d7c92c504838f72aaca73bec44048cb58/components/layout_thread/lib.rs#L1998).

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix *partially* #22854 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because these are cleanup changes which neither add any feature, nor fix any bug.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23515)

### CODE REVIEW

**Comment by oneturkmen** [comment]
r? @jdm 

(is it ok if I constantly "r?" you (with this issue)? feels like bugging you all the time hehe).

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by oneturkmen** [comment]
@jdm do you think it's network issue again?

**Comment by jdm** [comment]
@bors-servo retry
* #21480

**Pull request merged**
