### PR TITLE
refactor(layout_task.rs): move some functions to query.rs

### LINKED ISSUE #8470: Move some LayoutTask methods to query.rs.
We started this in #6836.

Move the `LayoutTask` methods `process_node_geometry_request`, `process_resolved_style_request`, and `process_offset_parent_query` from `components/layout/layout_task.rs` to `components/layout/query.rs`.

In the process, the `&self` argument should be removed.

### PR DESCRIPTION
**Pull request by luthfianto**
Should fixes #8470

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8497)

### CODE REVIEW

**Comment by jdm** [comment]
```
./components/layout/layout_task.rs:49: trailing whitespace

./components/layout/layout_task.rs:1064: Line is longer than 120 characters

./components/layout/layout_task.rs:49: use statement is not in alphabetical order

	expected: query::{MarginPadding, MarginRetrievingFragmentBorderBoxIterator, PositionProperty}

	found: query::{process_node_geometry_request, process_resolved_style_request, process_offset_parent_query}

./components/layout/layout_task.rs:50: use statement is not in alphabetical order

	expected: query::{PositionRetrievingFragmentBorderBoxIterator, Side}

	found: query::{MarginPadding, MarginRetrievingFragmentBorderBoxIterator, PositionProperty}

./components/layout/layout_task.rs:51: use statement is not in alphabetical order

	expected: query::{process_node_geometry_request, process_resolved_style_request, process_offset_parent_query}

	found: query::{PositionRetrievingFragmentBorderBoxIterator, Side}

The command "./mach test-tidy" exited with 1.
```

**Comment by jdm** [comment]
Otherwise this looks good!

**Comment by jdm** [comment]
`./mach test-tidy` still reports some errors:
```
./components/layout/layout_task.rs:49: use statement is not in alphabetical order
	expected: query::{MarginPadding, MarginRetrievingFragmentBorderBoxIterator, PositionProperty}
	found: query::{process_node_geometry_request, process_offset_parent_query, process_resolved_style_request}
./components/layout/layout_task.rs:50: use statement is not in alphabetical order
	expected: query::{PositionRetrievingFragmentBorderBoxIterator, Side}
	found: query::{MarginPadding, MarginRetrievingFragmentBorderBoxIterator, PositionProperty}
./components/layout/layout_task.rs:51: use statement is not in alphabetical order
	expected: query::{process_node_geometry_request, process_offset_parent_query, process_resolved_style_request}
	found: query::{PositionRetrievingFragmentBorderBoxIterator, Side}
```
There are also a bunch of build errors; did you compile these change?

**Comment by rilut** [comment]
Sorry, I have no luck for building Servo on my MSYS2. Does anybody has the solution to build Servo on Windows? I'm stuck in
```
MSYS /c/servo
$ ./mach build --dev
Downloading Rust snapshot...
Download failed (404): Not Found - https://servo-rust.s3.amazonaws.com/168a23ebe1729386138fa71643382fdd64fac205/rustc-1.5.0-dev-x86_64-unknown.tar.gz
```

Or I'll try to install/find a linux machine

**Comment by Ms2ger** [comment]
We don't support Windows at this point.

**Comment by jdm** [comment]
If you watch the mailing list/twitter, we'll announce when Windows support is merged.

**Comment by rilut** [comment]
@jdm Thanks! Currently temporarily testing on my own Travis.
Btw, how long does it take to build Servo in your computer?

**Comment by jdm** [comment]
2-3 minutes for most builds when I make a change to script/.

**Pull request closed without merging**
