### PR TITLE
Upgrade to rustc 1.3.0-dev (e4e93196e 2015-07-14)

### PR DESCRIPTION
**Pull request by SimonSapin**
This gets us the `[&str]::connect` to `join` renaming, which matters because string_cache_plugin uses `#![deny(warnings)]` and https://github.com/rust-lang/rust/issues/27259 is not here yet.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6737)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed 4 of 4 files at r1, 7 of 7 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6737)

**Comment by SimonSapin** [comment]
Maybe wait for e10s to land before this. CC @pcwalton

**Comment by metajack** [comment]
@pcwalton Do you want a rust up landed? It should probably be easy enough to update this rustup to include the drop flag partial removal.

**Comment by metajack** [comment]
Is this superceded by #6850?

**Comment by mbrubeck** [comment]
> Is this superceded by #6850?

Yes.

**Pull request closed without merging**
