### PR TITLE
Fix computed value of outline width when outline style is not set.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6403)

### CODE REVIEW

**Comment by SimonSapin** [comment]
This should happen in a `to_computed_value` method, in `cascade`.

**Comment by SimonSapin** [comment]
Hum, that’s already done: https://github.com/servo/servo/blob/ee22ae263515c2804b739ead4c02bc7333c3965c/components/style/properties.mako.rs#L326-L332

In what case does this PR make any difference?

**Comment by glennw** [comment]
(I haven't confirmed this) I would guess that the code you referenced is only called if outline-width is actually specified, and this new case handles when both values are default? It certainly doesn't seem to call the code you referenced in the test case I was looking at.

**Comment by SimonSapin** [comment]
@bors-servo r+

I was wrong in my first comment, sorry!

**Comment by SimonSapin** [comment]
@glennw two consecutive runs have the same failures. Maybe it’s a legit bug?
```
/css21_dev/html4/abspos-containing-block-001.htm
------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/abspos-containing-block-003.htm
------------------------------------------------
PASS expected FAIL [Parent]

**Comment by glennw** [comment]
@SimonSapin I had a look at those tests, and I can't see how my change would affect them. They match when I run the tests manually, although I did see a flash of red for one frame, so I suspect a race.

I'll do one more retry and if it still fails, I'll disable those tests if you agree that they should be unaffected by my change?

**Comment by glennw** [comment]
@SimonSapin Oh! I misread the test output - this PR fixes two expected failures :) I have confirmed locally and removed those from the expected failures list.

**Comment by SimonSapin** [comment]
Nice! (I also misread the output…)

**Pull request merged**
