### PR TITLE
Add webdriver commands for (Get|Add)Cookie

### PR DESCRIPTION
**Pull request by dlrobertson**
Add the webdriver commands for GetCookie and AddCookie. In addition the basic messages for sending cookie data back and forth from the resource thread needed to be created and the handlers for those messages were created as well.

Do we plan to have some sort of test suite for the webdriver at some point? At this point I primarily test my PRs with basic shell scripts with a lot of `curl` and `jq`.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10826)

### CODE REVIEW

**Comment by jdm** [comment]
Getting a test harness for the webdriver code is the subject of an [ongoing student project](https://github.com/servo/servo/pull/10113).

**Comment by danlrobertson** [comment]
Ah! Thanks! Thats awesome!

**Comment by danlrobertson** [comment]
I didn't correctly handle `max-age` and `expiry` per [RFS 6265](https://tools.ietf.org/html/rfc6265#section-5.3). I'll make the update shortly

**Comment by danlrobertson** [comment]
Fixed. Some of the changes made to `max-age` and `expiry` may not be as visible until jgraham/webdriver-rust#29 lands.

**Comment by jdm** [comment]
Note, there's a compile error in `net/resource_thread.rs`.

**Comment by danlrobertson** [comment]
Thanks, sorry about that.

**Comment by asajeffrey** [comment]
I had a look over the code, and added some comments. The main thing is I've lost track of how many types we have to represent a cookie, which results in a lot of book-keeping data transforms. It would be nice if we could reduce this number, e.g. by getting the webdriver crate to use the cookie crate?

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :umbrella: The latest upstream changes (presumably #11049) made this pull request unmergeable. Please resolve the merge conflicts.
</details>


---

Reviewed 9 of 9 files at r1.
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/msg/constellation_msg.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIyRs8QgpzF7h4w7i5:-KIIyRs99jzMIA6-p8LJ:1706974953) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/msg/constellation_msg.rs#L60)):*
> ```Rust
> 
> #[derive(Deserialize, Serialize)]
> pub struct CookieData {
> ```

This looks remarkably like `Cookie` from `webdriver`. It's a bit annoying that we end up needing so many types to represent a cookie, is there no way to avoid all this duplication?

---

*[components/net/cookie_storage.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIzGNgdXq7RaL0pOAK:-KIIzGNgdXq7RaL0pOAL:698587767) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/cookie_storage.rs#L124)):*
> ```Rust
>     }
> 
>     pub fn cookies_by_name_for_url(&mut self, url: &Url, name: &str, source: CookieSource) -> Vec<cookie_rs::Cookie> {
> ```

Should this be returning a `cookie_rs::Cookie` or a `Cookie`?

---

*[components/net/cookie_storage.rs, line 126 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIz8CECFhvafm46cXn:-KIIz8CECFhvafm46cXo:174801833) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/cookie_storage.rs#L126)):*
> ```Rust
>     pub fn cookies_by_name_for_url(&mut self, url: &Url, name: &str, source: CookieSource) -> Vec<cookie_rs::Cookie> {
>         self.cookies.iter_mut().filter(|c| { c.appropriate_for_url(url, source) && c.cookie.name == name }).map(|c| {
>             c.touch();
> ```

Side-effecting get?

---

*[components/net/cookie_storage.rs, line 128 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIzpMu-lA-mGIvPVWb:-KIIzpMu-lA-mGIvPVWc:356307026) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/cookie_storage.rs#L128)):*
> ```Rust
>             c.touch();
>             c.cookie.clone()
>         }).collect()
> ```

Collecting the cookies into a vector then iterating over the vector in `resource_thread.rs`? Can we not just return the iterator?

---

*[components/net/resource_thread.rs, line 195 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIzW89MEIEnF_mAtbc:-KIIzW8Ai-GtCBU3JQEd:1990723267) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/resource_thread.rs#L195)):*
> ```Rust
>                 }
>                 ControlMsg::GetCookiesByNameForUrl(url, name, consumer, source) => {
>                     //consumer.send(self.resource_manager.get_cookie_by_name_for_url(url, name, source));
> ```

What is this comment for? This block does look like it should be wrapped into a method on the resource manager.

---

*[components/net/resource_thread.rs, line 406 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIJ-RCBaOh86EuV6Xlx:-KIJ-RCBaOh86EuV6Xly:2011462448) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/resource_thread.rs#L406)):*
> ```Rust
>             httponly: cookie_data.http,
>             custom: BTreeMap::new(),
>         };
> ```

A lot of book-keeping caused by having so many data types for cookies.

---

*[components/script/webdriver_handlers.rs, line 200 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIJ-vJ8yFaq-6ynRS3O:-KIJ-vJ9LF8X5iOAQYMS:-370300383) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/script/webdriver_handlers.rs#L200)):*
> ```Rust
>                          cookie: CookieData,
>                          reply: IpcSender<Result<(), WebDriverCookieError>>) {
>     let document = page.document();
> ```

This method is slightly hairy, is there a spec link for the expected behaviour?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10826#-:-KIJ0ozdIHyN8dgL8d68:-158509219)*

**Comment by danlrobertson** [comment]
I completely agree, the main problem is implementing `Deseriealize ` and `Serialize`. `cookie_rs` and `webdriver-rust` use `RustcEncodeable`. Thoughts?

<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> I had a look over the code, and added some comments. The main thing is I've lost track of how many types we have to represent a cookie, which results in a lot of book-keeping data transforms. It would be nice if we could reduce this number, e.g. by getting the webdriver crate to use the cookie crate?
</details>


---

Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/msg/constellation_msg.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIyRs8QgpzF7h4w7i5:-KIJDrO9X_XlgIJqyUFT:682273088) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/msg/constellation_msg.rs#L60)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> This looks remarkably like `Cookie` from `webdriver`. It's a bit annoying that we end up needing so many types to represent a cookie, is there no way to avoid all this duplication?
</details>
Yes, this is identical. In order to be able to be "sent" it has to derive `Deserialize` and `Serialize`. I could add that to `webdriver::Cookie` and submit a separate PR to `webdriver`

---

*[components/net/cookie_storage.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIzGNgdXq7RaL0pOAK:-KIJEZ7utryJAZl5CaAE:76187890) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/cookie_storage.rs#L124)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Should this be returning a `cookie_rs::Cookie` or a `Cookie`?
</details>
[`cookies_rs::Cookie`](https://github.com/alexcrichton/cookie-rs/blob/master/src/lib.rs#L16-L28). a [`cookie::Cookie`](https://github.com/servo/servo/blob/master/components/net/cookie.rs#L19-L27) contains extra metadata that is not returned by the webdriver command + `cookies_rs::Cookie`.

---

*[components/net/cookie_storage.rs, line 126 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIz8CECFhvafm46cXn:-KIJFLDu51MZ3zdtRvut:-2023782379) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/cookie_storage.rs#L126)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Side-effecting get?
</details>
I tried to make it as similar as possible to [`cookies_for_url`](https://github.com/servo/servo/blob/master/components/net/cookie_storage.rs#L85-L116). In particular, check out lines 99 - 109

---

*[components/net/cookie_storage.rs, line 128 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIzpMu-lA-mGIvPVWb:-KIJFrWQ8M2gpG7cFy13:951572538) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/cookie_storage.rs#L128)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Collecting the cookies into a vector then iterating over the vector in `resource_thread.rs`? Can we not just return the iterator?
</details>
So return a `std::iter::Map<...>`?

---

*[components/net/resource_thread.rs, line 195 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIzW89MEIEnF_mAtbc:-KIJH1MSNrgJscsGznGu:-629425487) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/resource_thread.rs#L195)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> What is this comment for? This block does look like it should be wrapped into a method on the resource manager.
</details>
No idea, I think this was part of my work in progress? This should be removed

---

*[components/net/resource_thread.rs, line 406 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIJ-RCBaOh86EuV6Xlx:-KIJHCAk4vbQk9lmmsbh:13612891) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/resource_thread.rs#L406)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> A lot of book-keeping caused by having so many data types for cookies.
</details>
Agreed. Definitely my least favorite part of this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10826#-:-KIJHINzek-SJjg6Oimd:1515999382)*

**Comment by asajeffrey** [comment]
If we could remove all the cookie types, we would be done here. I guess that requires coordinating with other crate maintainers though. How should we proceed?

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :umbrella: The latest upstream changes (presumably #11179) made this pull request unmergeable. Please resolve the merge conflicts.
</details>


---

Reviewed 1 of 8 files at r3, 8 of 8 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/msg/constellation_msg.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIyRs8QgpzF7h4w7i5:-KITgDaI6hkiREtvwWdK:1327233431) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/msg/constellation_msg.rs#L60)):*
<details><summary><i>Previously, danlrobertson (Dan Robertson) wrote…</i></summary>
> Yes, this is identical. In order to be able to be "sent" it has to derive `Deserialize` and `Serialize`. I could add that to `webdriver::Cookie` and submit a separate PR to `webdriver`
</details>
That would be ideal.

---

*[components/net/cookie_storage.rs, line 128 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIzpMu-lA-mGIvPVWb:-KITgS2AMmWCZfO9RB9o:-2041051142) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/cookie_storage.rs#L128)):*
<details><summary><i>Previously, danlrobertson (Dan Robertson) wrote…</i></summary>
> So return a `std::iter::Map<...>`?
</details>
There's a problem that you either have to box the iterator, or return an explicit iterator type, since impl traits aren't in Rust yet. Perhaps best to define a custom iterator type?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10826#-:-KIThNwbbjNL8JdVdvEn:-223918811)*

**Comment by danlrobertson** [comment]
I have a commit using `cookie-rs` as the core representation of a cookie. Waiting on alexcrichton/cookie-rs#48 to land before I'll push the changes.

**Comment by asajeffrey** [comment]
It landed!

**Comment by danlrobertson** [comment]
Awesome! Once the version is bumped I can push the updates!

**Comment by jdm** [comment]
Filed https://github.com/alexcrichton/cookie-rs/pull/49.

**Comment by jdm** [comment]
The deed is done.

**Comment by danlrobertson** [comment]
Cool beans! I'll push the update shortly

**Comment by danlrobertson** [comment]
Merge conflicts 😠

**Comment by danlrobertson** [comment]
Updated!

**Comment by asajeffrey** [comment]
Sorry about the delay, this got slightly lost in the MozLondon rush! This now looks really nice, thanks for all the work! I have a few niggles, but nothing serious. Once it's rebased (and optionally you have fixed my niggles), you can r=me.

---

Reviewed 17 of 18 files at r8.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[components/msg/webdriver_msg.rs, line 14 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10826#-KL1Pk7d3kFZVi6RR7zl:-KL1Pk7d3kFZVi6RR7zm:264720186) ([raw file](https://github.com/servo/servo/blob/cb1f07312c02d42b99835092f7aab32587a427c8/components/msg/webdriver_msg.rs#L14)):*
> ```Rust
> #[derive(Deserialize, Serialize)]
> pub enum WebDriverScriptCommand {
>     AddCookie(Cookie, IpcSender<Result<(), WebDriverCookieError>>),
> ```

Much nicer!

---

*[components/net_traits/lib.rs, line 340 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10826#-KL1QMB8xLvrRiM4UW9G:-KL1QMB8xLvrRiM4UW9H:-587837619) ([raw file](https://github.com/servo/servo/blob/cb1f07312c02d42b99835092f7aab32587a427c8/components/net_traits/lib.rs#L340)):*
> ```Rust
>     SetCookiesForUrl(Url, String, CookieSource),
>     /// Store a set of cookies for a given originating URL
>     SetCookiesForUrlWithData(Url, cookie_rs::Cookie, CookieSource),
> ```

Can we `use cookie_rs::Cookie` so we can use the type directly?

---

*[components/script/webdriver_handlers.rs, line 200 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIJ-vJ8yFaq-6ynRS3O:-KL1QujnP-DXldnrF7Cr:-37600396) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/script/webdriver_handlers.rs#L200)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> This method is slightly hairy, is there a spec link for the expected behaviour?
</details>
Can you add a spec link?

---

*[components/script/webdriver_handlers.rs, line 187 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10826#-KL1Qh4bZdzvkH8XCoxQ:-KL1Qh4bZdzvkH8XCoxR:2138763811) ([raw file](https://github.com/servo/servo/blob/cb1f07312c02d42b99835092f7aab32587a427c8/components/script/webdriver_handlers.rs#L187)):*
> ```Rust
> pub fn handle_get_cookies(context: &BrowsingContext,
>                          _pipeline: PipelineId,
>                          reply: IpcSender<Vec<cookie_rs::Cookie>>) {
> ```

Can we `use cookie_rs::Cookie`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10826#-:-KL1R8BnX_ZAReioYu5M:-169628024)*

**Comment by danlrobertson** [comment]
Np. Thanks for the review! I updated the pr with the requested changes

---

Review status: 6 of 17 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/msg/webdriver_msg.rs, line 14 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10826#-KL1Pk7d3kFZVi6RR7zl:-KL8AcPW8Zi6fNK_8Bqq:-510466975) ([raw file](https://github.com/servo/servo/blob/cb1f07312c02d42b99835092f7aab32587a427c8/components/msg/webdriver_msg.rs#L14)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Much nicer!
</details>
:+1: 

---

*[components/net/cookie_storage.rs, line 128 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIIzpMu-lA-mGIvPVWb:-KL8AfTcTpre4G5QgvRo:-1530771663) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/net/cookie_storage.rs#L128)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> There's a problem that you either have to box the iterator, or return an explicit iterator type, since impl traits aren't in Rust yet. Perhaps best to define a custom iterator type?
</details>
Agreed.

---

*[components/net_traits/lib.rs, line 340 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10826#-KL1QMB8xLvrRiM4UW9G:-KL8Ai5VzfkU3Pfq4txz:-1973413397) ([raw file](https://github.com/servo/servo/blob/cb1f07312c02d42b99835092f7aab32587a427c8/components/net_traits/lib.rs#L340)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Can we `use cookie_rs::Cookie` so we can use the type directly?
</details>
Yup. Done.

---

*[components/script/webdriver_handlers.rs, line 200 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10826#-KIJ-vJ8yFaq-6ynRS3O:-KL8AnJYvphgPZuHngRE:-1142452737) ([raw file](https://github.com/servo/servo/blob/b680e736de590a3590e6188f54894da06b64364a/components/script/webdriver_handlers.rs#L200)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Can you add a spec link?
</details>
Added link

---

*[components/script/webdriver_handlers.rs, line 187 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10826#-KL1Qh4bZdzvkH8XCoxQ:-KL8AkRnBSs9Ulh8HuH7:-1973413397) ([raw file](https://github.com/servo/servo/blob/cb1f07312c02d42b99835092f7aab32587a427c8/components/script/webdriver_handlers.rs#L187)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Can we `use cookie_rs::Cookie`?
</details>
Yup. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10826#-:-KL8B3E_mA9bBlrjen6x:136896)*

**Comment by ConnorGBrewster** [comment]
Fails tidy:
```
Checking files for tidiness...
./components/msg/lib.rs:23: extern crate declaration is not in alphabetical order
	expected: webrender_traits
	found: cookie as cookie_rs
./components/msg/webdriver_msg.rs:6: use statement is not in alphabetical order
	expected: cookie_rs::Cookie
	found: constellation_msg::PipelineId
./components/net/cookie_storage.rs:119: Line is longer than 120 characters
```

**Comment by danlrobertson** [comment]
Ha! My bad... Guess I forgot to follow my own and add the git commit hook :frowning:

**Comment by danlrobertson** [comment]
Ah! The unit test failures are expected failures... I'll remove them from [`FAILING_TESTS`](https://github.com/servo/servo/blob/master/tests/unit/net/cookie_http_state_utils.py#L26-L29)

**Comment by jdm** [comment]
@bors-servo: retry
* #11859

**Pull request merged**
