### PR TITLE
Update WR (AA on transformed box-shadows, resource leak fixes)

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19414)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone

**Comment by KiChjang** [comment]
```
  ▶ FAIL [expected PASS] /css/compositing/mix-blend-mode/mix-blend-mode-intermediate-element-overflow-hidden-and-border-radius.html
  └   → /css/compositing/mix-blend-mode/mix-blend-mode-intermediate-element-overflow-hidden-and-border-radius.html 49ccc05739443927d8e1bf333d2191d978c0a4c4
/css/compositing/mix-blend-mode/reference/mix-blend-mode-intermediate-element-overflow-hidden-and-border-radius-ref.html 403d6ed3567e2736f5445c3eb43353f2cde7c66d
Testing 49ccc05739443927d8e1bf333d2191d978c0a4c4 == 403d6ed3567e2736f5445c3eb43353f2cde7c66d
```

**Comment by glennw** [comment]
This has a small number of pixel differences. It looks like an anti-aliasing issue. There's a couple of PRs coming in WR today that might fix this. If it's not fixed by those, I'll take a more detailed look.

**Comment by glennw** [comment]
@bors-servo retry
 * infra

**Comment by jdm** [comment]
This PR appears to only update byteorder now.

**Comment by glennw** [comment]
(I don't intend to merge the servo-tidy changes, but this will allow me to test on CI if there are any WR specific failures in this update).

**Comment by jdm** [comment]
```
  ▶ PASS [expected FAIL] /css/CSS2/tables/empty-cells-applies-to-008.xht

  ▶ PASS [expected FAIL] /css/CSS2/tables/empty-cells-applies-to-017.xht

  ▶ PASS [expected FAIL] /css/CSS2/tables/empty-cells-applies-to-009.xht

  ▶ PASS [expected FAIL] /css/CSS2/tables/empty-cells-applies-to-011.xht

  ▶ PASS [expected FAIL] /css/CSS2/tables/empty-cells-applies-to-010.xht
```

**Comment by glennw** [comment]
r? anyone (the duplicate of smallvec should be resolved in the next WR update).

**Pull request merged**
