### PR TITLE
Dedupe the dirs dependency

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by nox** [comment]
POGGERS

@bors-servo r+

**Comment by Eijebong** [comment]
```
1 unexpected results that are NOT known-intermittents:
  ▶ CRASH [expected PASS] /_mozilla/css/text_node_opacity.html
  │ 
  │ error: XDG_RUNTIME_DIR not set in the environment.
  │ libEGL warning: No hardware driver found, falling back to software rendering
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ error: XDG_RUNTIME_DIR not set in the environment.
  │ libEGL warning: No hardware driver found, falling back to software rendering
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ Stack trace for thread "LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }"
  └ stack backtrace:
```
Uh ? Could this be related ? If so why is it the only failing one ?

**Comment by Eijebong** [comment]
Well the test passes locally even if I `unset XDG_RUNTIME_DIR` before

**Comment by jdm** [comment]
That's probably #26129.

@bors-servo retry

**Pull request merged**
