### PR TITLE
Ensure documents drop when a pipeline exits

### PR DESCRIPTION
**Pull request by gterzian**
minimalist companion/alternative to https://github.com/servo/servo/pull/24047
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24072)

### CODE REVIEW

**Comment by gterzian** [comment]
```
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/cross-origin-embedder-policy/blob.https.html", 
    "line": 197679, 
    "action": "test_result", 
    "expected": "OK"
}
```

Same as with https://github.com/servo/servo/pull/24047

**Comment by gterzian** [comment]
@asajeffrey @jdm Ok so this is the most minimal change required to fix the leaking of window/global/document, and to be honest I have no idea why it has to do with `Performance`. 

The risk off-course is that we unknowingly start leaking those again due to a future change to something else...

**Comment by gterzian** [comment]
@asajeffrey theory of performance entries being added "late" in the lifecycle of the pipeline, seems probably, asctually when debugging the other PR I did run into panics where `performance.queue_entry` seemed to be called _after_ the pipeline was closed, and some of my changes(not the end results and I don't remember exactly the state of the code) would then result in a panic in such a situation. 

I remember being surprised this could happen, since the message handler in the script-thread does a `self.documents.find_window`, which would seem to imply the queuing of a performance entry can only happen if the pipeline hasn't been closed yet. 

@jdm If this could be reproduced, it could be a way to verify the "leak via performance entry that are never run" theory.

**Comment by gterzian** [comment]
Another possiblity, since performance tasks are potentially throttled by the task-queue, is that we get the following sequence:

1. Performance task is throttled,
2. Pipeline is closed.
3. Performance task is kept forever by the task-queue(it doesn't clear tasks when a pipeline is closed, in fact it sees those as tasks related to "not fully-active" documents, which is a leak in the case of a document that is not just "not fully-active" but actually related to a closed pipeline).

Although I looked into this in the other PR, and set it aside because it didn't actually seem to happen while we were still leaking windows.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Comment by kanaka** [comment]
Is this at a point where it would be worth me building and testing it?

**Comment by asajeffrey** [comment]
It's in master, if you can take a look that would be great!

**Comment by kanaka** [comment]
I hit a build regression on Linux I had to track down first: https://github.com/servo/servo/pull/24099 But it's building now and hopefully I'll have results shortly.

**Comment by kanaka** [comment]
I posted the results over in #23905. I assume that's still the right place until the fd growth issue is fully resolved?

**Pull request merged**
