### PR TITLE
Remove MutHeapJSVal

### LINKED ISSUE #15316: Remove MutHeapJSVal
https://github.com/servo/rust-mozjs/pull/328 makes it unnecessary. We should be able to replace all users with `Heap<JSVal>`.

### PR DESCRIPTION
**Pull request by chansuke**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15316 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15408)

### CODE REVIEW

**Comment by jdm** [comment]
@chansuke The original issue suggested removing the type entirely and replacing all uses of it with `Heap<JSVal>` instead.

**Comment by jdm** [comment]
@chansuke Are you planning to continue this work?

**Comment by chansuke** [comment]
@jdm Sorry for the late reply.Yes,I want to continue the work.

**Comment by jdm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
