### PR TITLE
Derive Debug for FontGroup and Homu is a bully

### PR DESCRIPTION
**Pull request by nox**
#8908 is @bors-servo's unlucky number, it seems.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9013)

### CODE REVIEW

**Comment by nox** [comment]
@antrik Thank you for your work, sorry for our excuse of a continuous integration this time. :(

**Comment by antrik** [comment]
And back to where we started :-(

By the looks of it, it's the same -- or similar -- problem it run into on the first try (in the original issue) with the latest code. (Is there a way to get at the old log to make sure?) But it's just coincidence that it triggered the same intermittent issue, right?...

**Comment by KiChjang** [comment]
@bors-servo retry
* #8769

**Comment by antrik** [comment]
This is getting surreal. The original PR *also* failed linux-rel on the retry. WTF?

(I found the old logs BTW. It's not the exact same test failing -- but very close by.)

**Comment by KiChjang** [comment]
@bors-servo retry
* #8769

**Pull request merged**
