### PR TITLE
Centralize construction of specified url() values in style.

### PR DESCRIPTION
**Pull request by emilio**
This reduces a decent amount of overhead in #13778.

r? @SimonSapin 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13791)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I don’t see how this helps. You still need to do that work sooner or later. Worse, it’s possible for two threads to race and both do that work.

**Comment by emilio** [comment]
Maybe it doesn't show up anymore in the profile because I'm delaying and never getting there (maybe the font panic I'm getting in the demo happens before layout?).

In any case, this is going to be better in the case we don't need to resolve the computed url, for example if the element is not displayed. I'll investigate more though.

**Comment by SimonSapin** [comment]
I’m tempted to close this as I don’t think it’s a good idea, but let’s get a second opinion. @pcwalton, what do you think?

**Comment by emilio** [comment]
Yep, I agree resolving it lazily may not be a good idea.

I'd still like to refcount urls a lot more though, does that seem ok to you @SimonSapin?

**Comment by emilio** [comment]
So I ended up refactoring how we handle style urls, so the place is centralized and we can refactor this in the future more easily.

I agree with @SimonSapin we should be bypassing rust-url for data-uris, but I'd prefer to leave that as a followup for now.

r? @SimonSapin

**Comment by SimonSapin** [comment]
r=me with `ToCss` impl fixed. (See inline comment.)

---

Reviewed 15 of 15 files at r1, 4 of 5 files at r2.
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/values/specified/url.rs, line 139 at r1](https://reviewable.io:443/reviews/servo/servo/13791#-KW8yfQoaXA-mnmXBwLl:-KW8yfQp_QMNdRBtWfRb:b-q7d033) ([raw file](https://github.com/servo/servo/blob/97b6bec8bec3504d790c96ac36a95f94be25fd9d/components/style/values/specified/url.rs#L139)):*
> ```Rust
>     fn to_css<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
>         if let Some(ref original) = self.original {
>             write!(dest, "url(\"{}\")", original)
> ```

This needs to use `cssparser::serializer::CssStringWriter`, for example in case `original` contains a double quote.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13791#-:-KW8yqofEsGvVFNwjRvQ:bu64914)*

**Comment by SimonSapin** [comment]
Unit tests need to be update for API changes.

**Comment by emilio** [comment]
@bors-servo r=SimonSapin

Fixed the unit tests :)

**Comment by emilio** [comment]
@bors-servo r=SimonSapin

Homu seemed stuck so I rebased.

**Comment by emilio** [comment]
@bors-servo retry

 * Homu's back

**Pull request merged**
