### PR TITLE
Implement EventListenerOptions for EventTarget

### LINKED ISSUE #9785: Implement EventListenerOptions for EventTarget
The WebIDL file that we have currently reflects an older version of the DOM spec. We should update this to use `EventListenerOptions` accordingly.

Code: `components/script/dom/webidls/EventTarget.webidl`, `components/script/dom/eventtarget.rs`
Spec: https://dom.spec.whatwg.org/#interface-eventtarget

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #9785.

Needs #11612 to be fixed first.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12952)

### CODE REVIEW

**Comment by jdm** [comment]
I'm not sure that it makes sense to merge this without the actual behaviour changes for the new kinds of listeners.

**Comment by GuillaumeGomez** [comment]
@jdm: I just opened it to not forget it (I did this a long time ago already).

**Comment by Ms2ger** [comment]
I'm sure that it does not make sense, but we could take `{ capture }` if there are tests.

**Comment by nox** [comment]
We should only use `EventListenerOptions` for now given we don't support the rest.

**Comment by KiChjang** [comment]
@GuillaumeGomez This still looks forgotten to me even after opening a PR for it.

**Comment by GuillaumeGomez** [comment]
@KiChjang: It was on stand-by, waiting for a feature. However, I can't remember which at all...

**Comment by Ms2ger** [comment]
Unions with objects

**Comment by GuillaumeGomez** [comment]
Has it been added or not yet?

**Comment by Ms2ger** [comment]
I think it was; that's what causing the dead code warning we have in script right now

**Comment by GuillaumeGomez** [comment]
Ok, I'll update this PR then!

**Comment by GuillaumeGomez** [comment]
I still have the following error:

```
TypeError: Can't handle AddEventListenerOptions (Wrapper) in unions yet
```

**Comment by jdm** [comment]
I don't see a reason to keep this open until #11612 is fixed.

**Comment by KiChjang** [comment]
So #11612 is fixed now, @GuillaumeGomez would you still like to work on this?

**Comment by GuillaumeGomez** [comment]
Sure!

**Pull request closed without merging**
