### PR TITLE
Sync WPT with upstream manually (20-01-2022)

### PR DESCRIPTION
**Pull request by CYBAI**
This is a follow-up for https://github.com/servo/servo/pull/28592. Because we still have a gap to sync from 2021/09/07, I'd like to merge this one and try to fix the nightly sync action PR. 🙏

### CODE REVIEW

**Comment by CYBAI** [comment]
@bors-servo try=wpt

We had only one failure which is

```
  ▶ FAIL [expected TIMEOUT] b'/css/css-flexbox/flexbox-writing-mode-013.html'
  │   → /css/css-flexbox/flexbox-writing-mode-013.html ['62d2f5d4af8d1058a66dc66218de0c479894ab54']
  └   → /css/css-flexbox/flexbox-writing-mode-013-ref.html ['f753db8e4ce4f4b4f48a6d9059fca8c6708d0a1d']
```

and I think it was an intermittent TIMEOUT in the update so I filed #28701.

Let's try again!

**Comment by CYBAI** [comment]
@bors-servo retry

hmm, let me retry to see if it's an intermittent ERROR 🤔 

```
  ▶ ERROR [expected OK] b'/html/semantics/scripting-1/the-script-element/module/import-meta/import-meta-url.html'
  │   → import.meta may only appear in a module
  │ 
  └ http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/module/import-meta/postmessage-worker.js?DedicatedWorker:3:21
```

**Comment by CYBAI** [comment]
^ WPT passed.

but macOS build failed at mozjs 🤔  It passed in the first try of this PR though, is it an intermittent build fail? 👀 

```
error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/servo/mozjs?rev=4cd3f5b81f4c363c039631bf870e61a00c983f63#4cd3f5b8)`

Caused by:
  process didn't exit successfully: `/Users/runner/work/servo/servo/target/release/build/mozjs_sys-fa46ef939b468b63/build-script-build` (exit status: 101)
```

**Comment by jdm** [comment]
Huh, it happened again:
```
  Creating Python 3 environment
  Traceback (most recent call last):
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv.py", line 56, in <module>
      run()
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv.py", line 50, in run
      from virtualenv.__main__ import run as run_virtualenv
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/__init__.py", line 3, in <module>
      from .run import cli_run, session_via_cli
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/run/__init__.py", line 13, in <module>
      from .plugin.creators import CreatorSelector
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/run/plugin/creators.py", line 6, in <module>
      from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
      from virtualenv.create.creator import Creator
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/create/creator.py", line 15, in <module>
      from virtualenv.discovery.cached_py_info import LogCmd
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/discovery/cached_py_info.py", line 16, in <module>
      from virtualenv.discovery.py_info import PythonInfo
    File "/Users/runner/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/4cd3f5b/mozjs/third_party/python/virtualenv/virtualenv/discovery/py_info.py", line 16, in <module>
      from distutils import dist
    File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 83, in create_module
      return importlib.import_module('setuptools._distutils')
    File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  ModuleNotFoundError: No module named 'setuptools'
  DEBUG: python3: running with pid 41180
  DEBUG: python3: sys.executable: '/Users/runner/work/servo/servo/python/_virtualenv3.9/bin/python3'
  DEBUG: python3: executable from configuration: None
  DEBUG: python3: found executable: '/Users/runner/work/servo/servo/python/_virtualenv3.9/bin/python3'
```

**Comment by CYBAI** [comment]
@bors-servo retry

- #28717

**Pull request merged**
