### PR TITLE
Implements 2 helper functions for Color type (white() and black())

### PR DESCRIPTION
**Pull request by Adenilson**
Implements 2 helper functions for Color type (white() and black()) plus uses the new equality operators implemented in rust-azure.

### CODE REVIEW

**Comment by jdm** [comment]
This will need to include the result of `./mach update-cargo -p azure --precise [hash]` where hash is a revision of rust-azure that includes the equality change.

**Comment by SimonSapin** [comment]
I’m reluctant to add helper functions for their own sake if nothing uses them. If you’re planning to use them in another pull request, these functions are perfectly fine as part of that.

**Comment by SimonSapin** [comment]
Oops, sorry, I misread the diff. Please disregard my earlier comment.

**Comment by Adenilson** [comment]
Josh

Thanks for the tip concerning updating rust-azure, just pushed a patch with the changes after running update-cargo.

**Comment by Adenilson** [comment]
Ok, so I removed the use of equality operators while we wait for syncing with rust-azure. Should compile fine now.

**Pull request merged**
