### PR TITLE
Enable cookies tests

### LINKED ISSUE #24869: Enable cookies WPT tests
Tests like tests/wpt/web-platform-tests/cookies/http-state/path-tests.html are testing fundamental parts of the cookie spec, so we should be running them.

### PR DESCRIPTION
**Pull request by pshaughn**
fix #24869

The first run of this will spit out a lot of new test failure metadata, of course.

### CODE REVIEW

**Comment by jdm** [comment]
I suspect it might make sense to skip the samesite subdirectory - it's a lot of timeouts right now, and we don't have any implementation for the new samesite cookie spec (https://web.dev/samesite-cookies-explained/), and the tests appear to use features like multiple windows that we don't support yet.

**Comment by pshaughn** [comment]
Most of the failures on the first pass were because #25598 hadn't landed yet.
@bors-servo try=wpt

**Pull request merged**
