### PR TITLE
Refactored optional argument "last_modified" for Document

### LINKED ISSUE #4981: Add optional Headers argument to Document constructor
There are lots of information that documents can and should extract from HTTP headers. Right now the script task explicitly parses the Last-Modified header and calls `Document::set_last_modified`, but that should really be the responsibility of code in `document.rs` instead. We can get rid of `set_last_modified` and make the `last_modified` field immutable if we do that in the constructor itself.

### PR DESCRIPTION
**Pull request by mschroeder**
Fixes #4981

### CODE REVIEW

**Comment by saneyuki** [comment]
@mschroeder Thank you for your contribution! I reviewed your patch on [critic](https://critic.hoppipolla.co.uk/r/4203). Please change your code and push them as fixup commit :)

(more details of our reviewing process is [here](https://github.com/servo/servo/wiki/Github-%26-Critic-PR-handling-101))

**Comment by saneyuki** [comment]
@mschroeder thank you update. I reviewed your patch again.

**Comment by mschroeder** [comment]
I did the requested code changes and awaiting review again.

**Comment by saneyuki** [comment]
@mschroeder I'm sorry to make you wait to review. how do you think about [this](https://critic.hoppipolla.co.uk/showcomment?chain=10958)?

**Comment by mschroeder** [comment]
@saneyuki Sorry, did not see the updated review. Changed the code as suggested.

**Comment by saneyuki** [comment]
@mschroeder we accept your patch. please squash :)

**Comment by mschroeder** [comment]
Successfully squashed my commits on the feature branch.

**Comment by saneyuki** [comment]
```sh
/home/servo/buildbot/slave/linux2/build/components/script/script_task.rs:982:35: 982:44 error: use of undeclared type name `DOMString`
/home/servo/buildbot/slave/linux2/build/components/script/script_task.rs:982         let last_modified: Option<DOMString> = response.metadata.headers.as_ref().and_then(|headers| {
                                                                                                               ^~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `script`.
```

@mschroeder please fix this.

**Comment by mschroeder** [comment]
@saneyuki Added the missing 'use' statement, and the build went green.

**Pull request merged**
