### PR TITLE
Update euclid

### PR DESCRIPTION
**Pull request by Manishearth**
r? @nox @jdm

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /2dcontext/path-objects/2d.path.stroke.skew.html:
  └ PASS [expected FAIL] Strokes lines are skewed by the current transformation matrix
  ▶ Unexpected subtest result in /2dcontext/path-objects/2d.path.stroke.scale2.html:
  └ PASS [expected FAIL] Stroke line widths are scaled by the current transformation matrix
  ▶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.stroke.scale2.html:
  └ PASS [expected FAIL] Stroke line widths are scaled by the current transformation matrix
  ▶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.stroke.skew.worker.html:
  └ PASS [expected FAIL] Strokes lines are skewed by the current transformation matrix
  ▶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.stroke.skew.html:
  └ PASS [expected FAIL] Strokes lines are skewed by the current transformation matrix
  ▶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.stroke.scale2.worker.html:
  └ PASS [expected FAIL] Stroke line widths are scaled by the current transformation matrix
```

**Comment by jdm** [comment]
Looks like https://github.com/servo/euclid/pull/377 fixed some bugs.

**Comment by Manishearth** [comment]
nice

@bors-servo r=nox

**Pull request merged**
