### PR TITLE
Fixed #8594 -- use a more modern default cipher suite list by default

### LINKED ISSUE #8594: servo should negotiate more modern secure ciphersuites
Right now servo appears to use OpenSSL's defaults, which are very bad. It should use a modern ciphersuite string such as https://github.com/python/cpython/blob/master/Lib/ssl.py#L168-L172 

You can see the list it's sending at https://howsmyssl.com

### PR DESCRIPTION
**Pull request by alex**
Fixes #8594.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8611)

### CODE REVIEW

**Comment by alex** [comment]
test failures look unrelated (@frewsxcv tells me they're known flaky?)

**Comment by pcwalton** [comment]
Can you add some references to the comment by any chance? It'd be great if people who update this in the future (as well as reviewers) could have a link to some background reading as to best practices, since this is a security-critical configuration decision.

**Comment by alex** [comment]
@pcwalton Added! Thanks.

**Comment by pcwalton** [comment]
Thanks, that was helpful! The string doesn't `!` out all insecure ciphers (e.g. export-grade crypto). Is OpenSSL guaranteed to never use them even though they're not explicitly blacklisted?

**Comment by alex** [comment]
I believe so, yes. I use this cipher string (or ones very similar) in many libraries and TLS servers and have never seen it include things like export grade crypto. (If you go to `howsmyssl.com` before this change you'll see that without this, it does include various weak ciphers, and does not with)

**Comment by pcwalton** [comment]
OK, looks good from my end then once try comes back green. (We should get a security review from someone who's a professional as opposed to a dabbler like me before we ship any of this. But this is clearly an improvement and looks good based on my knowledge.)

**Comment by pcwalton** [comment]
Oh, why the leading underscore in `_DEFAULT_CIPHERS`?

**Comment by alex** [comment]
@pcwalton Oh, it's a carryover from my Python days. Idiomatic rust would be to remove the `_`?

**Comment by pcwalton** [comment]
Yeah, we try not to use leading underscores unless we're silencing an unused parameter compiler warning.

**Comment by jvehent** [comment]
I would say r-, but a weak one.

This is a secure ciphersuite that can be improved a bit. The list of ciphers it expands to is too long, mostly due to keywords like HIGH and RSA that expand to a lot of ciphers. For servo, I would recommend explicitly listing the ciphers that we want, as opposed to using keywords.

```
ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:
ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:
DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:
ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:
ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:
ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:
DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:
ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:
AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA
```

Which expands to:
```
0xC0,0x2B  -  ECDHE-ECDSA-AES128-GCM-SHA256  TLSv1.2  Kx=ECDH  Au=ECDSA  Enc=AESGCM(128)  Mac=AEAD
0xC0,0x2F  -  ECDHE-RSA-AES128-GCM-SHA256    TLSv1.2  Kx=ECDH  Au=RSA    Enc=AESGCM(128)  Mac=AEAD
0xC0,0x2C  -  ECDHE-ECDSA-AES256-GCM-SHA384  TLSv1.2  Kx=ECDH  Au=ECDSA  Enc=AESGCM(256)  Mac=AEAD
0xC0,0x30  -  ECDHE-RSA-AES256-GCM-SHA384    TLSv1.2  Kx=ECDH  Au=RSA    Enc=AESGCM(256)  Mac=AEAD
0x00,0x9E  -  DHE-RSA-AES128-GCM-SHA256      TLSv1.2  Kx=DH    Au=RSA    Enc=AESGCM(128)  Mac=AEAD
0xC0,0x23  -  ECDHE-ECDSA-AES128-SHA256      TLSv1.2  Kx=ECDH  Au=ECDSA  Enc=AES(128)     Mac=SHA256
0xC0,0x27  -  ECDHE-RSA-AES128-SHA256        TLSv1.2  Kx=ECDH  Au=RSA    Enc=AES(128)     Mac=SHA256
0xC0,0x24  -  ECDHE-ECDSA-AES256-SHA384      TLSv1.2  Kx=ECDH  Au=ECDSA  Enc=AES(256)     Mac=SHA384
0xC0,0x28  -  ECDHE-RSA-AES256-SHA384        TLSv1.2  Kx=ECDH  Au=RSA    Enc=AES(256)     Mac=SHA384
0xC0,0x09  -  ECDHE-ECDSA-AES128-SHA         SSLv3    Kx=ECDH  Au=ECDSA  Enc=AES(128)     Mac=SHA1
0xC0,0x13  -  ECDHE-RSA-AES128-SHA           SSLv3    Kx=ECDH  Au=RSA    Enc=AES(128)     Mac=SHA1
0xC0,0x0A  -  ECDHE-ECDSA-AES256-SHA         SSLv3    Kx=ECDH  Au=ECDSA  Enc=AES(256)     Mac=SHA1
0xC0,0x14  -  ECDHE-RSA-AES256-SHA           SSLv3    Kx=ECDH  Au=RSA    Enc=AES(256)     Mac=SHA1
0x00,0x67  -  DHE-RSA-AES128-SHA256          TLSv1.2  Kx=DH    Au=RSA    Enc=AES(128)     Mac=SHA256
0x00,0x33  -  DHE-RSA-AES128-SHA             SSLv3    Kx=DH    Au=RSA    Enc=AES(128)     Mac=SHA1
0x00,0x6B  -  DHE-RSA-AES256-SHA256          TLSv1.2  Kx=DH    Au=RSA    Enc=AES(256)     Mac=SHA256
0x00,0x39  -  DHE-RSA-AES256-SHA             SSLv3    Kx=DH    Au=RSA    Enc=AES(256)     Mac=SHA1
0xC0,0x12  -  ECDHE-RSA-DES-CBC3-SHA         SSLv3    Kx=ECDH  Au=RSA    Enc=3DES(168)    Mac=SHA1
0xC0,0x08  -  ECDHE-ECDSA-DES-CBC3-SHA       SSLv3    Kx=ECDH  Au=ECDSA  Enc=3DES(168)    Mac=SHA1
0x00,0x9C  -  AES128-GCM-SHA256              TLSv1.2  Kx=RSA   Au=RSA    Enc=AESGCM(128)  Mac=AEAD
0x00,0x9D  -  AES256-GCM-SHA384              TLSv1.2  Kx=RSA   Au=RSA    Enc=AESGCM(256)  Mac=AEAD
0x00,0x3C  -  AES128-SHA256                  TLSv1.2  Kx=RSA   Au=RSA    Enc=AES(128)     Mac=SHA256
0x00,0x3D  -  AES256-SHA256                  TLSv1.2  Kx=RSA   Au=RSA    Enc=AES(256)     Mac=SHA256
0x00,0x2F  -  AES128-SHA                     SSLv3    Kx=RSA   Au=RSA    Enc=AES(128)     Mac=SHA1
0x00,0x35  -  AES256-SHA                     SSLv3    Kx=RSA   Au=RSA    Enc=AES(256)     Mac=SHA1
```

This ciphersuite is closer to the prioritization rules described [on the wiki](https://wiki.mozilla.org/Security/Server_Side_TLS#Prioritization_logic), and is also mostly identical to what Firefox currently uses.

**Comment by alex** [comment]
Looks great to me, I'll update this PR to use that set later today.

**Comment by jvehent** [comment]
Looks good to me. r+

**Comment by Ms2ger** [comment]
@bors-servo r-

Sorry, I'd like you to squash the four commits first.

**Comment by alex** [comment]
@Ms2ger done.

**Comment by Ms2ger** [comment]
Much appreciated.

@bors-servo r=jvehent

**Comment by tarcieri** [comment]
Note that Chromium recently deprecated (FF)DHE ciphersuites (although they will temporarily be performing DHE fallback):

https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/dYyhKHPnrI0

**Comment by alex** [comment]
@tarcieri I considered whether to include that in this PR. I decided that servo didn't need to be at the bleeding edge (aka stuff people should have been doing 3 years ago), and keeping it simple now was fine. FFDHE can be dropped when other browsers actually land that stuff. (Or if necessary as a part of #8581 )

**Comment by Ms2ger** [comment]
@tarcieri feel free to file an issue on that; I think this is already a welcome improvement, though.

**Comment by pcwalton** [comment]
@jdm Do you recognize the failure?

**Comment by frewsxcv** [comment]
@bors-servo retry

@larsbergstrom suggested #8502

**Comment by jdm** [comment]
@larsbergstrom suggested rightly.

**Comment by jdm** [comment]
@bors-servo: retry
* #8614

**Comment by jdm** [comment]
@bors-servo: retry
* #8614

**Comment by jdm** [comment]
@bors-servo: retry
* #8616 #8614

**Comment by jdm** [comment]
@bors-servo: retry
* #8614

**Comment by jdm** [comment]
@bors-servo: retry
* #8614

**Comment by jdm** [comment]
@bors-servo: retry
* #8614

**Pull request merged**
