### PR TITLE
Bug 1395064 - stylo: Add uses of fallible Vec, SmallVec and HashMap f…

### PR DESCRIPTION
**Pull request by julian-seward1**
…acilities.  r=emilio@crisal.io.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18434)

### CODE REVIEW

**Comment by jdm** [comment]
There's a ton of segfaults like:
```
servo(94106,0x7fff763ce000) malloc: *** error for object 0x100000000: pointer being freed was not allocated
```

**Comment by emilio** [comment]
Hmm, right. Servo uses jemalloc and we're calling directly to system malloc on the fallible alloc stuff

**Comment by emilio** [comment]
@bors-servo r- try

Could we get a review for the last two commits? @jdm or @Manishearth or @bholley, maybe?

**Comment by bholley** [comment]
@emilio LGTM. Though I don't follow your comment about how we'd make the non-inline call even in the non-error case. Where does that happen?

**Comment by emilio** [comment]
@bholley, we are using `ok_or` instead of `ok_or_else`, which means that we construct the object unconditionally, and if I'm right that the call to `::new` can't be optimized out.

@bors-servo r=bholley

**Pull request merged**
