### PR TITLE
Upgrade to latest mach from mozilla-central

### PR DESCRIPTION
**Pull request by mbrubeck**
r? @jgraham

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7838)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7838)

**Comment by metajack** [comment]
Not that I'm likely to object, but I would prefer it if you included the reason in the pull request description.

**Comment by mbrubeck** [comment]
This was motivated by https://bugzilla.mozilla.org/show_bug.cgi?id=1175968 which makes `./mach run -- --help` run `servo --help`.

**Pull request merged**
