### PR TITLE
Format component `style`

### PR DESCRIPTION
**Pull request by chansuke**
Format `components/style` with:
```
rustfmt components/style/*.rs
```

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #21373.
- [x] These changes do not require tests because they format the components only.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21652)

### CODE REVIEW

**Comment by CYBAI** [comment]
Maybe `These changes fix #21373.` needs to be `These changes fix part of #21373.`?
Or, it will make the issue closed once this PR merged.

**Comment by jdm** [comment]
cc @emilio

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1489862

**Comment by emilio** [comment]
@bors-servo p=1

 * So that they both merge before other changes to `components/` which are also in the queue and should get synced in Gecko, so that the order of the commit is the same on both repos... Though it's fairly unimportant if it doesn't happen.

**Comment by jdm** [comment]
@bors-servo retry
* #20734

**Pull request merged**
