### PR TITLE
Revert PR that introduced frequent linux reftest failures

### LINKED ISSUE #24726: Intermittent reftest failures on linux (blank rendering)
I've noticed this in two different pull requests since yesterday, and I'm pretty sure we've been ignoring these intermittent failures for an indeterminate amount of time. One test result looks like:
Screen Shot 2019-11-13 at 10 51 15 AM
The other test result is completely blank. This has been observed with /css/CSS2/text/text-transform-applies-to-013.xht and /css/CSS2/fonts/shand-font-002.xht so far.

### PR DESCRIPTION
**Pull request by jdm**
This should reduce the frequency of #24726.

### CODE REVIEW

**Comment by asajeffrey** [comment]
Pity, I liked #24677. You can r=me.

**Comment by jdm** [comment]
I plan to reintroduce the changes from #24677, but now that I know there's a bug somewhere it will be easier to identify its source starting from a known-working revision, rather than trying to undo historical changes in a broken revision.

**Comment by jdm** [comment]
```
1 unexpected results that are NOT known-intermittents:
  ▶ FAIL [expected PASS] /css/CSS2/bidi-text/bidi-box-model-001.xht
  │   → /css/CSS2/bidi-text/bidi-box-model-001.xht 54a9df64f1476dd12020019d7cf22ac34d727bc0
  │   → /css/CSS2/bidi-text/bidi-box-model-001-ref.xht e597a04d78f1523f67bd3e2a01e4b8ad831bd031
  └   → Screenshot is solid color 0xFFFFFF for /css/CSS2/bidi-text/bidi-box-model-001.xht
```
ARRRRRRRRRRRRRGH

**Comment by jdm** [comment]
@bors-servo retry
* #21480

**Comment by jdm** [comment]
No longer needed.

**Pull request closed without merging**
