### PR TITLE
Fix formdata-blob.htm

### PR DESCRIPTION
**Pull request by KiChjang**
The other failure is a legitimate WPT bug, will fix upstream.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16325)

### CODE REVIEW

**Comment by KiChjang** [comment]
w3c/web-platform-tests#5517

**Comment by KiChjang** [comment]
Hold on, test is correct, but our implementation isn't following spec.

**Comment by KiChjang** [comment]
This is ready for review.

@bors-servo try

**Comment by KiChjang** [comment]
```

  ▶ ERROR [expected OK] /workers/data-url.html
  └   → expected expression, got '}'

  ▶ Unexpected subtest result in /workers/data-url.html:
  │ FAIL [expected PASS] worker has opaque origin
  │   → assert_equals: expected "PASS" but got "FAIL"
  │ 
  │ assert_worker_sends_pass/</w.onmessage<@http://web-platform.test:8000/workers/data-url.html:12:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1409:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1449:17
```
@jdm  :(

**Comment by jdm** [comment]
You can ignore that. It's dealt with now.

**Comment by cbrewster** [comment]
LGTM. @bors-servo r+

**Pull request merged**
