### PR TITLE
Send reason in the Websocket close handshake

### LINKED ISSUE #7862: Send the reason in the WebSocket close handshake
Websites are allowed to specify a freeform UTF-8 string as a reason for closing the connection, but we don't send that reason in the message to the server right now [contrary to the specification](https://tools.ietf.org/html/rfc6455#section-7.1.6). We should adjust the code in `WebSocket::Close` (inside `send_close`) to send the string stored in `WebSocket::reason` instead of `None`.

Code: components/script/dom/websocket.rs

### PR DESCRIPTION
**Pull request by psdh**
Fixes #7862

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7871)

### CODE REVIEW

**Comment by psdh** [comment]
@jdm How should I test this?

**Comment by Ms2ger** [comment]
Try `./mach test-wpt websockets`; I hope that will point out some newly passing tests.

**Comment by psdh** [comment]
@Ms2ger No change! :(

**Comment by jdm** [comment]
It's not immediately obvious how a test would report successfully seeing the expected close reason when the connection is closed, unless there were multiple websocket servers and they could communicate. I'm inclined to merge this change as-is.

**Pull request merged**
