### PR TITLE
Add devtools_chan method to GlobalRef

### PR DESCRIPTION
**Pull request by thiagopnts**
The notification for new globals now works for nested workers too (refs #5309)

### CODE REVIEW

**Comment by jdm** [comment]
Great! I've left comments on Critic; be sure you click the 'sign in' link there to receive updates by email.

**Comment by thiagopnts** [comment]
@jdm Done!

**Comment by jdm** [comment]
This can be squashed :)

**Comment by thiagopnts** [comment]
@jdm Done

**Comment by jdm** [comment]
Now it just needs a rebase; sorry!

**Comment by thiagopnts** [comment]
@jdm No problem, rebased.

**Pull request closed without merging**
