### PR TITLE
Remove Document.get_html_element() (fixes #8409)

### LINKED ISSUE #8409: Should Document::invalidate_stylesheets really call get_html_element?
It means we won't mark the document element dirty if it's not an `html` element.

### PR DESCRIPTION
**Pull request by djc**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #8409 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because small refactor

Replace uses by calling self.GetDocumentElement(), instead.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11449)

### CODE REVIEW

**Comment by Ms2ger** [comment]
The bug was specifically about `Document::invalidate_stylesheets`, the other calls are correct and necessary.

**Comment by nox** [comment]
@Ms2ger Oops, you have all the reason to be surprised. Sorry for the r+, should have thought twice about it.

**Comment by nox** [comment]
+S-needs-code-changes 

<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> @Ms2ger Oops, you have all the reason to be surprised. Sorry for the r+, should have thought twice about it.
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/script/dom/document.rs, line 1232 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11449#-KIlUSUS33GoNc-AnITW:-KIlUSUS33GoNc-AnITX:1986563288) ([raw file](https://github.com/servo/servo/blob/cbeccdd4675b627f04b1c655dd51e46c060d6727/components/script/dom/document.rs#L1232)):*
> ```Rust
>         self.GetDocumentElement().map(|root| {
>             root.upcast::<Node>().dirty(NodeDamage::NodeStyleDamaged);
>         });
> ```

Nit: let's remove the side-effecting map call while we are at it.

```rust
if let Some(element) = self.GetDocumentElement() {
    element.upcast::<Node>().dirty(NodeDamage::NodeStyleDamaged);
}
```

---

*[components/script/dom/document.rs, line 1761 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11449#-KIlUiLGRsO5rFb0bRTN:-KIlUiLGRsO5rFb0bRTO:769298873) ([raw file](https://github.com/servo/servo/blob/bf3c437683808fdfb1f8406c023c391e5728266f/components/script/dom/document.rs#L1761)):*
> ```Rust
> 
>     fn get_html_element(&self) -> Option<Root<HTMLHtmlElement>> {
>         self.GetDocumentElement().and_then(Root::downcast)
> ```

Revert this.

---

*[components/script/dom/document.rs, line 2354 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11449#-KIlUjCayTS2ohi9sK3e:-KIlUjCayTS2ohi9sK3f:769298873) ([raw file](https://github.com/servo/servo/blob/cbeccdd4675b627f04b1c655dd51e46c060d6727/components/script/dom/document.rs#L2354)):*
> ```Rust
>     // https://html.spec.whatwg.org/multipage/#dom-document-head
>     fn GetHead(&self) -> Option<Root<HTMLHeadElement>> {
>         self.GetDocumentElement()
> ```

Revert this.

---

*[components/script/dom/document.rs, line 2365 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11449#-KIlUk60itcivBB28CWC:-KIlUk60itcivBB28CWD:769298873) ([raw file](https://github.com/servo/servo/blob/cbeccdd4675b627f04b1c655dd51e46c060d6727/components/script/dom/document.rs#L2365)):*
> ```Rust
>     // https://html.spec.whatwg.org/multipage/#dom-document-body
>     fn GetBody(&self) -> Option<Root<HTMLElement>> {
>         self.GetDocumentElement().and_then(|root| {
> ```

Revert this.

---

*[components/script/dom/document.rs, line 2398 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11449#-KIlUl-xK0-B1bx5KgYY:-KIlUl-xK0-B1bx5KgYZ:769298873) ([raw file](https://github.com/servo/servo/blob/cbeccdd4675b627f04b1c655dd51e46c060d6727/components/script/dom/document.rs#L2398)):*
> ```Rust
>         }
> 
>         match (self.GetDocumentElement(), &old_body) {
> ```

Revert this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11449#-:-KIlUmpIz_h40xKU34T-:1522908653)*

**Comment by nox** [comment]
Thanks!

@bors-servo r+

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11449#-:-KIlbRF_R_kDt0f48-44:-579303246)*

**Pull request merged**
