### PR TITLE
layout: Simplify the pseudo-element setup.

### PR DESCRIPTION
**Pull request by emilio**
It's kind of a mess. See individual commits for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19769)

### CODE REVIEW

**Comment by emilio** [comment]
Those two failures are due to the last commit, but it's a pre-existing bug (#19771).

Will undo it for now, leaving a comment.

**Comment by emilio** [comment]
The last commit is https://github.com/emilio/servo/commit/03208bac87, fwiw.

**Comment by nox** [comment]
@bors-servo r+

Neat.

**Pull request merged**
