### PR TITLE
Implement Navigator.appVersion(#5409)

### PR DESCRIPTION
**Pull request by deokjinkim**
In my mistake, I close PR for this commit.
I'm sorry for inconvenience.

@jdm 's comment
The test expectations for /tests/wpt/web-platform-tests/html/dom/interfaces.html and /tests/wpt/web-platform-tests/workers/interfaces.workers.js will need to be updated - http://mxr.mozilla.org/servo/search?string=appversion

According to your guide, I revised commit. Is this your intention?
r? @jdm 

cc @yichoi

### CODE REVIEW

**Comment by jdm** [comment]
That's right, but instead of changing FAIL to PASS we should just remove those lines instead (and the [foo] above them).

**Comment by deokjinkim** [comment]
Thank you for your advice. I updated test expectations of wpt for Navigator.appVersion. r? @jdm

**Comment by jdm** [comment]
Go ahead and squash :)

**Comment by deokjinkim** [comment]
squashed :)

**Pull request closed without merging**
