### PR TITLE
Update clipboard related dependencies to use xcb 0.8

### PR DESCRIPTION
**Pull request by Eijebong**
See https://github.com/rtbo/rust-xcb/pull/55

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20067)

### CODE REVIEW

**Comment by Eijebong** [comment]
Failure seems legit
```
/home/servo/android/ndk/r12b/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot find -lxcb
```

No idea how to fix that though

**Comment by Eijebong** [comment]
https://github.com/aweinstock314/rust-clipboard/issues/52

**Comment by nox** [comment]
I'm confused, why wasn't it an issue before the bump?

**Comment by Eijebong** [comment]
I have no idea...

**Comment by Eijebong** [comment]
That error is unrelated and reverting that commit makes the android build work again

**Comment by CYBAI** [comment]
```rust
error[E0463]: can't find crate for `x11_clipboard_crate`
  --> /home/servo/.cargo/git/checkouts/rust-clipboard-4a1584d52df56684/ba9efe8/src/lib.rs:23:1
   |
23 | extern crate x11_clipboard as x11_clipboard_crate;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `clipboard`.
```

**Comment by Eijebong** [comment]
Yeah it's missing the `target_os="android"` on this one.

**Comment by Eijebong** [comment]
@bors-servo try

Let's hope this is right this time

**Comment by Eijebong** [comment]
There we go, @nox r?

**Comment by jdm** [comment]
@bors-servo retry
* #20087

**Comment by Eijebong** [comment]
@jdm The build for android is going to be broken anyway :( @aweinstock314 failed their rebase and published the wrong fix to `rust-clipboard`, it's missing some `target_os=` and the line on the `extern crate xcb`

**Comment by jdm** [comment]
@bors-servo retry
* https://github.com/rust-lang/cargo/issues/5066

**Comment by jdm** [comment]
@bors-servo: retry
* #13480

**Pull request merged**
