### PR TITLE
Make it possible for iframes to create their own pipeline ID.

### PR DESCRIPTION
**Pull request by glennw**
This doesn't change any functionality, but it's the first step towards removing SubpageId.

Adding this change now will allow us to gradually change over code referencing subpage id rather than in one massive PR.

Introduces a namespace for pipeline ID generation - there is a namespace for the constellation thread, and one per script thread.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7807)

### CODE REVIEW

**Comment by glennw** [comment]
@jdm This introduces the core functionality that allows iframes to generate their own pipeline IDs. This is the first step towards allowing us to simplify all management of SubpageIds. This should be a much simpler PR to review than doing the entire change at once. r?

**Comment by jdm** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 336 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_UCdmnkvAPs_ueCqD)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/compositing/constellation.rs#L336)):</sup>
I'm finding the following difficult to reason about:
* the script thread for a pipeline in namespace 1 with index 1 is created
* it starts loading a URL in an iframe, sending an ID with namespace 1 with index 2 to the constellation
* the constellation creates a new pipeline with ID of namespace 1 and index 2, but the contained `pipeline_namespace_id` in PipelineContent is namespace 2
* when the new pipeine creates a new script thread, any iframes created in that script thread will have IDs of namespace 2, index N?

I guess I haven't found anything that seems _wrong_, per se, but the setup is feels less intuitive than it was before. I fear what will happen when we start grouping pipelines in the same script task by origin, even for simple setups like clicking a link on a.com that goes to a.com/page and uses the same script thread for the load.


---

<sup>**[components/compositing/constellation.rs, line 620 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_QRvebtbWfPupUqwo)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/compositing/constellation.rs#L620)):</sup>
The interaction between this and initializing the next namespace as 1 in the constructor is extremely subtle. Remind me why we can't use `new` here instead?


---

<sup>**[components/devtools/lib.rs, line 436 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_SiCFoH5FUnoGLncC)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/devtools/lib.rs#L436)):</sup>
If this ends up being the only legitimate use for PipelineId::nil, it should probably be called `fake_me_a_pipeline` instead.


---

<sup>**[components/gfx/paint_task.rs, line 186 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_Sdp3fAgxs7JyFWz7)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/gfx/paint_task.rs#L186)):</sup>
Same note as further down.


---

<sup>**[components/layout/layout_task.rs, line 280 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_ScJyGkDxqu6g4vcg)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/layout/layout_task.rs#L280)):</sup>
Same note as further down.


---

<sup>**[components/msg/constellation_msg.rs, line 226 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_RXIF-tbnGck0bqAv)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L226)):</sup>
We're going to need to either turn this into a struct variant or a simple struct wrapper and provide meaningful names.


---

<sup>**[components/msg/constellation_msg.rs, line 397 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-Znaa89sx-CdwClHs0)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L397)):</sup>
The similarity between `PipelineIdNamespace` and `PipelineNamespaceId` is unfortunate. What about `PipelineNamespace`? Documentation of the relationship between pipeline IDs and namespaces would also be lovely.


---

<sup>**[components/msg/constellation_msg.rs, line 428 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_R8dnCpy5Hef3rtk1)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L428)):</sup>
Is it possible to use Cell instead?


---

<sup>**[components/msg/constellation_msg.rs, line 451 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_QpNdCNsiMag0PlzY)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L451)):</sup>
I'd love to get rid of this method if we can; I find its existence very confusing. At minimum we should clearly document when it's appropriate to use.


---

<sup>**[components/script/dom/htmliframeelement.rs, line 123 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_S-NwgJn0zqUGCyZj)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/script/dom/htmliframeelement.rs#L123)):</sup>
Let's use a local binding to the new pipeline ID instead of using unwrap here.


---

<sup>**[components/script/script_task.rs, line 496 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_S6j31HYwVi4Ak1zn)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/script/script_task.rs#L496)):</sup>
We should have a custom representation like `(namespace,index)`; I assume the actual output we get here right now will be less than optimal.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7807)

**Comment by nox** [comment]
I wonder if this fixes #7826.

**Comment by glennw** [comment]
Review status: 3 of 9 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 336 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_UCdmnkvAPs_ueCqD)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/compositing/constellation.rs#L336)):</sup>
Does it help to think about it as the namespace ID being an identifier for the thread that created the pipeline ID? It is less intuitive, I agree - but I feel that it's a worthwhile tradeoff for the benefits (we will be able to remove all subpage concepts from the compositor, layout, script task etc).


---

<sup>**[components/compositing/constellation.rs, line 620 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_QRvebtbWfPupUqwo)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/compositing/constellation.rs#L620)):</sup>
Only because of the code in devtools you noted below - I will ping @jgragam to find out what we can do with that.


---

<sup>**[components/devtools/lib.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_SiCFoH5FUnoGLncC)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/devtools/lib.rs#L0)):</sup>
Agreed - I'll discuss with jgraham


---

<sup>**[components/gfx/paint_task.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_Sdp3fAgxs7JyFWz7)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/gfx/paint_task.rs#L0)):</sup>
Done.


---

<sup>**[components/layout/layout_task.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_ScJyGkDxqu6g4vcg)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/layout/layout_task.rs#L0)):</sup>
Done.


---

<sup>**[components/msg/constellation_msg.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-Znaa89sx-CdwClHs0)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L0)):</sup>
Done.


---

<sup>**[components/msg/constellation_msg.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_QpNdCNsiMag0PlzY)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L0)):</sup>
I have added a TODO comment for now.


---

<sup>**[components/msg/constellation_msg.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_R8dnCpy5Hef3rtk1)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L0)):</sup>
Done.


---

<sup>**[components/msg/constellation_msg.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_RXIF-tbnGck0bqAv)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L0)):</sup>
This comment seems to be about a line not included in this PR?


---

<sup>**[components/script/dom/htmliframeelement.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_S-NwgJn0zqUGCyZj)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/script/dom/htmliframeelement.rs#L0)):</sup>
Done.


---

<sup>**[components/script/script_task.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_S6j31HYwVi4Ak1zn)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/script/script_task.rs#L0)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7807)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes -S-awaiting-answer 


---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 336 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_UCdmnkvAPs_ueCqD)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/compositing/constellation.rs#L336)):</sup>
Actually, when you phrase it like that it makes a lot more sense to me. Let's make sure to document that somewhere :)


---

<sup>**[components/msg/constellation_msg.rs, line 226 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_RXIF-tbnGck0bqAv)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L226)):</sup>
Not if you look at the original context by dragging r1->r2 in reviewable.


---

<sup>**[components/msg/constellation_msg.rs, line 397 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-Znaa89sx-CdwClHs0)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L397)):</sup>
Can we turn it into doc comments? Otherwise it won't show up on doc.servo.org.


---

<sup>**[components/msg/constellation_msg.rs, line 406 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-u07v_Ia6ex2jrKwkM)** ([raw file](https://github.com/servo/servo/blob/4489b78f2bd7871521ca165e396aa4fd84d9232a/components/msg/constellation_msg.rs#L406)):</sup>
I first read this as script threads and constellations create namespaces willy-nilly, but we should be clear that only the constellation creates new namespaces so there's no danger of collisions.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7807)

**Comment by glennw** [comment]
Review status: 5 of 9 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_UCdmnkvAPs_ueCqD)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/compositing/constellation.rs#L0)):</sup>
Done.


---

<sup>**[components/msg/constellation_msg.rs, line 226 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-_RXIF-tbnGck0bqAv)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L226)):</sup>
Done.


---

<sup>**[components/msg/constellation_msg.rs, line 396 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-u07v_Ia6ex2jrKwkM)** ([raw file](https://github.com/servo/servo/blob/4489b78f2bd7871521ca165e396aa4fd84d9232a/components/msg/constellation_msg.rs#L396)):</sup>
Done.


---

<sup>**[components/msg/constellation_msg.rs, line 397 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7807#-K-Znaa89sx-CdwClHs0)** ([raw file](https://github.com/servo/servo/blob/891f90b8fba934ab72ebaa470f6a251ecb88d7a8/components/msg/constellation_msg.rs#L397)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7807)

**Comment by jdm** [comment]
Looks good! Squash and merge!
-S-awaiting-review +S-needs-squash 


---

Reviewed 4 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7807)

**Pull request merged**
