### PR TITLE
Fix ./mach clean-cargo-cache

### PR DESCRIPTION
**Pull request by Gae24**
By chance I used the command and realized that it didn't work. Also while I looked to see if it had already been reported, I stumbled in #17084, that should be closed given that the option to override cargo-home-dir was removed from servobuild.

In Python 2 the `filter` function used to return a `list`, but the behaviour changed in Python 3, wrapping the result in a list was enough. 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because it's a simple python fix

### CODE REVIEW

**Comment by mrobinson** [comment]
@Gae24 Do you mind explaining a bit what the problem was in your commit description and how your change addresses it? Thank you!

**Review by jdm — APPROVED** [review]
Thanks!

**Comment by mrobinson** [comment]
> @Gae24 Do you mind explaining a bit what the problem was in your commit description and how your change addresses it? Thank you!

This isn't a huge deal if it look okay to @jdm.

**Comment by Gae24** [comment]
Basically in python 2 the filter function used to return a list, but the behaviour changed in python3, wrapping the result in a list was enough

**Pull request merged**
