### PR TITLE
Provide pull request link when syncing web-platform-tests with upstream

### PR DESCRIPTION
**Pull request by jdm**
This allows other people watching that repository to see where the review of the test changes occurred.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16186)

### CODE REVIEW

**Comment by jdm** [comment]
This does add a requirement that https://github.com/mhagger/git-when-merged/ is in your path, in order to find the associated merge for each commit that touches web-platform-tests.

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/update/tree.py, line 184 at r1](https://reviewable.io:443/reviews/servo/servo/16186#-KgVWkB3uPOey0PgPB2O:-KgVWkB4nk7QzksoMfft:b-4fb0wx) ([raw file](https://github.com/servo/servo/blob/73d2c20d3cf049c61f602bf98b48ccad024700bd/tests/wpt/update/tree.py#L184)):*
> ```Python
>         if not is_merge:
>             args = ["-c", sha1]
>             merge_rev = self.git("when-merged", *args).strip()
> ```

I think that the logic here should either be inlined (see http://stackoverflow.com/questions/8475448/find-merge-commit-which-include-a-specific-commit) or we should at least print a helpful error when this is unavaliable.

---

*[tests/wpt/update/tree.py, line 197 at r1](https://reviewable.io:443/reviews/servo/servo/16186#-KgVXK9BnJTlWKz1rMud:-KgVXK9BnJTlWKz1rMue:b6hpo62) ([raw file](https://github.com/servo/servo/blob/73d2c20d3cf049c61f602bf98b48ccad024700bd/tests/wpt/update/tree.py#L197)):*
> ```Python
>         diff = self.git("show", *args)
> 
>         return Patch(self.author, self.email, self.message, self.merge.message, diff)
> ```

In theory self.merge can be `None` here (I mean not in practice because you added `--no-merges` above and we never create a patch for an associated merge commit, but the error handling is inconsistent compared to the `__init__` function, which is confusing).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16186)*

**Review by jgraham — CHANGES_REQUESTED** [review]
[see reviewable]

**Comment by jdm** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/update/tree.py, line 184 at r1](https://reviewable.io:443/reviews/servo/servo/16186#-KgVWkB3uPOey0PgPB2O:-KgZuzoILD0mh_LRHSTy:b-spgu84) ([raw file](https://github.com/servo/servo/blob/73d2c20d3cf049c61f602bf98b48ccad024700bd/tests/wpt/update/tree.py#L184)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I think that the logic here should either be inlined (see http://stackoverflow.com/questions/8475448/find-merge-commit-which-include-a-specific-commit) or we should at least print a helpful error when this is unavaliable.
</blockquote></details>

I originally tried running the commands from that post, but I could not make them return meaningful results. I'll go with the helpful error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16186)*

**Comment by jdm** [comment]
How does this look?
```
godot2:dev-servo jdm$ ./mach update-wpt --sync --token-file ~/wpt_token_file --patch
 0:00.31 LOG: MainThread INFO Looking for last sync commit
 0:00.33 LOG: MainThread INFO Last sync to web-platform-tests happened in 30a31fb744a2fd2b11b901d722704fe458df3022
 0:06.91 LOG: MainThread INFO Updating sync tree from https://github.com/w3c/web-platform-tests.git
0:12.01 LOG: MainThread vcs ERROR git: 'when-merged' is not a git command. See 'git --help'.

Either the `when-merged` git command is missing (https://github.com/mhagger/git-when-merged/) or the command did not complete successfully.

Error running mach:

    ['update-wpt', '--sync', '--token-file', '/Users/jdm/wpt_token_file', '--patch']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '['git', 'when-merged', '-c', '4fadf9b0b613f4e9673defedf26a81eea4217d8b']' returned non-zero exit status 1

  File "/Users/jdm/src/dev-servo/python/servo/testing_commands.py", line 506, in update_wpt
    return run_globals["update_tests"](**kwargs)
  File "/Users/jdm/src/dev-servo/tests/wpt/update.py", line 25, in update_tests
    rv = update.run_update(logger, **kwargs)
  File "/Users/jdm/src/dev-servo/tests/wpt/./update/__init__.py", line 25, in run_update
    return updater.run()
  File "/Users/jdm/src/dev-servo/tests/wpt/harness/wptrunner/update/update.py", line 151, in run
    rv = update_runner.run()
  File "/Users/jdm/src/dev-servo/tests/wpt/harness/wptrunner/update/base.py", line 65, in run
    rv = step(self.logger).run(step_index, self.state)
  File "/Users/jdm/src/dev-servo/tests/wpt/harness/wptrunner/update/base.py", line 36, in run
    self.create(state)
  File "/Users/jdm/src/dev-servo/tests/wpt/./update/upstream.py", line 85, in create
    runner.run()
  File "/Users/jdm/src/dev-servo/tests/wpt/harness/wptrunner/update/base.py", line 65, in run
    rv = step(self.logger).run(step_index, self.state)
  File "/Users/jdm/src/dev-servo/tests/wpt/harness/wptrunner/update/base.py", line 36, in run
    self.create(state)
  File "/Users/jdm/src/dev-servo/tests/wpt/./update/upstream.py", line 146, in create
    state.tests_path)
  File "/Users/jdm/src/dev-servo/tests/wpt/./update/tree.py", line 68, in log
    return [self.commit_cls(self, sha1) for sha1 in data.split("\0") if sha1]
  File "/Users/jdm/src/dev-servo/tests/wpt/./update/tree.py", line 191, in __init__
    raise exn
```

**Comment by jdm** [comment]
Better:
```
godot2:dev-servo jdm$ ./mach update-wpt --sync --token-file ~/wpt_token_file --patch
 0:00.30 LOG: MainThread INFO Looking for last sync commit
 0:00.33 LOG: MainThread INFO Last sync to web-platform-tests happened in 30a31fb744a2fd2b11b901d722704fe458df3022
 0:06.20 LOG: MainThread INFO Updating sync tree from https://github.com/w3c/web-platform-tests.git
 0:10.44 LOG: MainThread vcs ERROR git: 'when-merged' is not a git command. See 'git --help'.

Please add the `when-merged` git command to your PATH (https://github.com/mhagger/git-when-merged/).
```

**Comment by jgraham** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16186)*

**Review by jgraham — APPROVED** [review]

**Pull request merged**
