### PR TITLE
 Lazy load fonts in a FontGroup 

### PR DESCRIPTION
**Pull request by jonleighton**
The first commit message explains this so I'll just copy it here:

---

This is a step towards fixing #17267. To fix that, we need to be able to
try various different fallback fonts in turn, which would become
unweildy with the prior eager-loading strategy.

Prior to this change, FontGroup loaded up all Font instances, including
the fallback font, before any of them were checked for the presence of
the glyphs we're trying to render.

So for the following CSS:

    font-family: Helvetica, Arial;

The FontGroup would contain a Font instance for Helvetica, and a Font
instance for Arial, and a Font instance for the fallback font.

It may be that Helvetica contains glyphs for every character in the
document, and therefore Arial and the fallback font are not needed at
all.

This change makes the strategy lazy, so that we'll only create a Font
for Arial if we cannot find a glyph within Helvetica. I've also
substantially refactored the existing code in the process and added
some documentation along the way.

---

I've added some tests in the second commit, but it required quite a bit of gymnastics to make it possible to write such a test. I'm not sure if the added complexity to the production code is worth it?

On the other hand, having this infrastructure in place may be useful for testing future changes in this area, and also possibly brings us a step closer to extracting a library as discussed in #4901. (What I mean by that is: it reduces coupling between `FontCacheThread` and `FontContext` -- the latter would have a place in such a library, the former wouldn't.)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20021)

### CODE REVIEW

**Comment by glennw** [comment]
Reviewed 7 of 10 files at r1, 2 of 7 files at r2.
Review status: 9 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/gfx/platform/freetype/font.rs, line 77 at r1](https://reviewable.io:443/reviews/servo/servo/20021#-L5Fvj72Li0_oUm20DcB:-L5Fvj72Li0_oUm20DcC:b9g40d8) ([raw file](https://github.com/servo/servo/blob/e30e525dcca972aec1327847e3fce9a4194e40d1/components/gfx/platform/freetype/font.rs#L77)):*
> ```Rust
> 
> impl PartialEq for FontHandle {
>     fn eq(&self, other: &FontHandle) -> bool {
> ```

I'm always slightly uneasy about implementing PartialEq, since it's easy to add fields to the struct at a later date, and not realize that they may need to be included in the PartialEq implementation. Perhaps we could add a comment at the struct definition warning people to update the PartialEq implementation if fields are added to it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20021)*

**Comment by glennw** [comment]
Partial review only so far - I'll work through the rest of this today.

**Comment by glennw** [comment]
Reviewed 2 of 7 files at r2.
Review status: 11 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/layout/text.rs, line 139 at r2](https://reviewable.io:443/reviews/servo/servo/20021#-L5Fy58fFdwRMyh3f5Yj:-L5Fy58fFdwRMyh3f5Yk:bu6wxbq) ([raw file](https://github.com/servo/servo/blob/c69c3caefc6eb4dc10523680cb1380a703d3f307/components/layout/text.rs#L139)):*
> ```Rust
>     /// be adjusted.
>     fn flush_clump_to_list(&mut self,
>                            mut font_context: &mut LayoutFontContext,
> ```

Why does this need to be mut when it is a mutable reference?

---

*[components/layout/text.rs, line 326 at r2](https://reviewable.io:443/reviews/servo/servo/20021#-L5FyH7rdDimgORuBf3e:-L5FyH7rdDimgORuBf3f:b-q09ek9) ([raw file](https://github.com/servo/servo/blob/c69c3caefc6eb4dc10523680cb1380a703d3f307/components/layout/text.rs#L326)):*
> ```Rust
> 
>                 // If no font is found (including fallbacks), there's no way we can render.
>                 let font = run_info.font.expect("No font found for text run!");
> ```

Do we ever expect a situation where this could be hit? Should this be a panic or just skip drawing and log an error / warning?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20021)*

**Comment by glennw** [comment]
Reviewed 3 of 7 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/gfx/tests/font_context.rs, line 58 at r2](https://reviewable.io:443/reviews/servo/servo/20021#-L5I0EU0VDFLSnfzPtxh:-L5I0EU0VDFLSnfzPtxi:b-osmt2i) ([raw file](https://github.com/servo/servo/blob/c69c3caefc6eb4dc10523680cb1380a703d3f307/components/gfx/tests/font_context.rs#L58)):*
> ```Rust
> 
>     fn add_face(family: &mut FontTemplates, name: &str) {
>         let mut path: PathBuf = [
> ```

Is it a good idea to rely on files existing in WPT? I'm not sure - jdm will know whether that's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20021)*

**Comment by glennw** [comment]
This generally looks OK to me (minor comments from reviewable above). However, I haven't delved into the servo layout or text code for a long time now, so it'd be good for someone else to take a look at this and see if there are any obvious issues - perhaps @pcwalton or @mbrubeck ?

**Comment by jonleighton** [comment]
Thanks for the review!

> I'm always slightly uneasy about implementing PartialEq, since it's easy to add fields to the struct at a later date, and not realize that they may need to be included in the PartialEq implementation. Perhaps we could add a comment at the struct definition warning people to update the PartialEq implementation if fields are added to it?

I think that's a sensible concern. I did something different than you suggested though: I added methods so that we can get at the underlying font identifier (an `Atom`), since that's what we're really trying to compare. WDYT?

> Why does this need to be mut when it is a mutable reference?

Without it I get this error:

```
error[E0596]: cannot borrow immutable argument `font_context` as mutable
   --> components/layout/text.rs:218:79
    |
140 |                            font_context: &mut FontContext,
    |                            ------------ consider changing this to `mut font_context`
...
218 |                     let font = font_group.borrow_mut().find_by_codepoint(&mut font_context, character);
    |                                                                               ^^^^^^^^^^^^ cannot borrow mutably
```

I believe it is because this method passes the `&mut font_context` to more than one callee.

> Do we ever expect a situation where this could be hit? Should this be a panic or just skip drawing and log an error / warning?

The current code [already panics](https://github.com/servo/servo/blob/5af219e8188f2e657c5711eb5def4c8e8065e29d/components/layout/text.rs#L223-L224) in the same situation which is why I haven't handled this different. We'd basically only hit this if we cannot find *any* font (including fallbacks) for the text run, even one which doesn't contain a glyph for the character we're trying to render. So I think it's a pretty rare case and would probably require a rather strange underlying system.

> Is it a good idea to rely on files existing in WPT? I'm not sure - jdm will know whether that's fine.

I can't see those files changing, but I agree this does feel a bit weird. We could alternatively just copy those files into `components/gfx/tests/support`. Do you have any thoughts @jdm? If the files did ever get (re)moved, the test would start to fail, so it's not like we wouldn't notice.

**Comment by jdm** [comment]
Given that the WPT files could be renamed, moved, removed, etc. as part of an automated sync process that I'm trying to keep as hands-off as possible, I would prefer to duplicate any files that are relied upon by our unit tests, rather than hardcoding paths to files we don't completely control.

**Comment by glennw** [comment]
@mbrubeck or @pcwalton are you able to take a quick look over this too?

**Review by mbrubeck — APPROVED** [review]
The code changes look good to me.  The test infrastructure looks fine too; it's not very heavyweight and the decoupling is very nice!

**Comment by jonleighton** [comment]
@glennw @mbrubeck great, thanks. could one of you give it the "r+" please?

**Comment by jdm** [comment]
Tests failed on all platforms.

**Comment by jonleighton** [comment]
@jdm should be fixed now

**Pull request merged**
