### PR TITLE
Remove unused XHR method

### LINKED ISSUE #11760: Remove unused XHR method
```
warning: method is never used: `insert_trusted_header`, #[warn(dead_code)] on by default
    --> /Users/nox/src/servo/components/script/dom/xmlhttprequest.rs:1044:5
     |>
1044 |>     fn insert_trusted_header(&self, name: String, value: String) {
     |>     ^
```

### PR DESCRIPTION
**Pull request by splav**
## Remove unused XHR method.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11760 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it is a cleanup

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11769)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for the patch!

**Comment by jdm** [comment]
@bors-servo: retry
* #11772

**Comment by jdm** [comment]
@bors-servo: retry
* #11703 #11574

**Comment by KiChjang** [comment]
@bors-servo retry
* #11574

**Pull request merged**
