### PR TITLE
Run a decision task on both TC deployments

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
https://tools.taskcluster.net/groups/EkcR2QAMQEu0rVOhZcMCoQ is green.

(WPT tasks previously failed to download the release build artifact.)

**Comment by jdm** [comment]
@bors-servo retry
* #24667

**Comment by jdm** [comment]
```
Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
etc/taskcluster/decision_task.py     182      1    99%   29
```

**Comment by SimonSapin** [comment]
Eh, maybe I was a bit too eager with requiring 100% coverage :)

@bors-servo r=jdm

**Pull request merged**
