### PR TITLE
Create pull request template.

### PR DESCRIPTION
**Pull request by jdm**
r? @metajack

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11118)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> #### Create pull request template\.
> 
> r? @metajack
> 
> 
> </details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11118#-:-KHRDNUKd01HrhiGE5Kb:1236647940)*

**Comment by metajack** [comment]
@bors-servo retry
- git

cc @alexcrichton Maybe cargo should retry git failures once or twice?

**Comment by alexcrichton** [comment]
Indeed! That's covered by https://github.com/rust-lang/cargo/issues/1602 and there's a PR at https://github.com/rust-lang/cargo/pull/2396

**Comment by jdm** [comment]
@bors-servo: retry
* git

**Comment by KiChjang** [comment]
@bors-servo retry
* #11059

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * Infra

**Pull request merged**
