### PR TITLE
Moved dispatch_key_event method from script_task.rs to document.rs

### LINKED ISSUE #4982: Move body of ScriptTask::dispatch_key_event into a method on Document
The vast majority of the method has nothing to do with the script task and everything to do with the document that is the target of the event. It will be a little bit tricky because of the `self.compositor.borrow_mut().send_key_event(key, state, modifiers);` line, but that can just be passed as an argument to the new method for now (`RefMut<Box<ScriptListener+'static>>`, probably).

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #4982

### CODE REVIEW

**Comment by jdm** [comment]
Squash!

**Comment by KiChjang** [comment]
Squashed.

**Comment by jdm** [comment]
This needs a rebase, unfortunately. The test that failed before was just an intermittent one; it's no problem with your changes.

**Comment by KiChjang** [comment]
Hopefully I've done it right, r? @jdm

**Pull request merged**
