### PR TITLE
Remove the glfw port (it doesn't compile since last rustup anyway).

### PR DESCRIPTION
**Pull request by glennw**

### CODE REVIEW

**Comment by glennw** [comment]
Not sure if we should wait until next meeting to check if there's any objections / glutin issues before we merge this?

r? @larsbergstrom

**Comment by SimonSapin** [comment]
It’s in the git history, we can always bring it back if necessary.

**Comment by SimonSapin** [comment]
> +10 −744

:)

**Comment by bjz** [comment]
Huzzah!

**Pull request closed without merging**
