### PR TITLE
Refactor DrawImage implementations to avoid code duplication

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6985)

### CODE REVIEW

**Comment by jdm** [comment]
Good stuff. r=me when homu is back on.

**Comment by glennw** [comment]
r=jdm

**Comment by jdm** [comment]
```

/_mozilla/mozilla/canvas/drawimage_html_image_5.html
----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_3.html
----------------------------------------------------
FAIL [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_4.html
----------------------------------------------------
FAIL [Parent]
```

**Pull request merged**
