### PR TITLE
Fix clippy warnings in `components/rand`

### PR DESCRIPTION
**Pull request by sandeepB3**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #31500
- [x] These changes do not require tests because they do not modify functionality, it only adds a `Default` implementation for `ServoRng`

### CODE REVIEW

**Review by mrobinson — CHANGES_REQUESTED** [review]
This adds a default implementation for `ServoRng`, but the implementation is not used. It should be used somewhere and the clippy warning should likely give you a hint as to where. Perhaps it is about replacing `new()` with `default()` in which case you should find all the callers of `new()` and have them use `default()`.

**Comment by sandeepB3** [comment]
@mrobinson, I have made the required changes by replacing new() with default() in line 109, but is it applicable in line 165 as well ? As we have a Default implementation for ServoReseeder in line 147

**Comment by mrobinson** [comment]
> @mrobinson, I have made the required changes by replacing new() with default() in line 109, but is it applicable in line 165 as well? As we have a Default implementation for ServoReseeder in line 147.

You can determine if this it's adequate by moving the contents of the `new()` function into `default()`, removing `new()` and then trying to recompile.

**Comment by sandeepB3** [comment]
> > @mrobinson, I have made the required changes by replacing new() with default() in line 109, but is it applicable in line 165 as well? As we have a Default implementation for ServoReseeder in line 147.
> 
> You can determine if this it's adequate by moving the contents of the `new()` function into `default()`, removing `new()` and then trying to recompile.

Yes understood, so wherever `ServoRng::new()` is implemented is to be replaced with `ServoRng::default()`, I have made the required changes and both `./mach build -d` and `./mach test-tidy`, does not report any error.

Screenshot 2024-03-07 at 7 13 28 PM

**Comment by mrobinson** [comment]
> > > @mrobinson, I have made the required changes by replacing new() with default() in line 109, but is it applicable in line 165 as well? As we have a Default implementation for ServoReseeder in line 147.
> > 
> > 
> > You can determine if this it's adequate by moving the contents of the `new()` function into `default()`, removing `new()` and then trying to recompile.
> 
> Yes understood, so wherever `ServoRng::new()` is implemented, it is to be replaced with `ServoRng::default()`, I have made the required changes and both `./mach build -d` and `./mach test-tidy`, does not report any error.
> Screenshot 2024-03-07 at 7 13 28 PM

Thanks. I think you'll still need to move the contents of the `new()` method into the `default()` method and then completely remove the `new()` method though.

**Comment by sandeepB3** [comment]
@mrobinson, I have made the required changes, so that now calling ServoRng::default() will now perform the same operations that were originally in the new() method. Subsequently I have replaced ServoRng::new() with ServoRng::default(), wherever `./mach build -d` test failed. Do let me know if there would be any other modifications.

**Review by mrobinson — APPROVED** [review]
Thanks!

**Pull request merged**
