### PR TITLE
Remove the w3c link for the Event interface

### PR DESCRIPTION
**Pull request by nerith**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9194)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@bors-servo r-

I'm afraid this is the wrong link; `Event` is defined at <https://dom.spec.whatwg.org/#event>. Please also remove the W3C copyright claim.

**Comment by nox** [comment]
@Ms2ger Ugh sorry. Bot on IRC didn't yell at the link either. :(

**Comment by Ms2ger** [comment]
It is the right like for some interfaces, but not this one :)

**Pull request merged**
