### PR TITLE
Upgrade some dependencies

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8884)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8884)*

**Comment by mbrubeck** [comment]
r=mbrubeck, assuming the try build succeeds

**Comment by frewsxcv** [comment]
@bors-servo r=mbrubeck

Builders didn't finish 'try'ing this, just going to move forward

**Comment by KiChjang** [comment]
Oh noes! gaol failed to compile!
/cc @pcwalton

**Comment by mbrubeck** [comment]
This might be a libc mismatch issue.  gaol has several `*` dependencies.

```
/home/servo/.cargo/git/checkouts/gaol-2f5ad236210c8e99/master/platform/linux/namespace.rs:64:19: 64:33 error: mismatched types:
 expected `*const i8`,
    found `*const u8`
(expected i8,
    found u8) [E0308]
/home/servo/.cargo/git/checkouts/gaol-2f5ad236210c8e99/master/platform/linux/namespace.rs:64             mount(tmpfs.as_ptr(),
                                                                                                               ^~~~~~~~~~~~~~
```

**Comment by frewsxcv** [comment]
Somewhat related: https://github.com/pcwalton/gaol/pull/8

**Comment by mbrubeck** [comment]
I can confirm that pcwalton/gaol#8 fixes the Android build.

**Pull request merged**
