### PR TITLE
Remove HTMLTableCellElement fields with parsed attribute values

### PR DESCRIPTION
**Pull request by eefriedman**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8336)

### CODE REVIEW

**Comment by frewsxcv** [comment]
@bors-servo r+


---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8336)

**Comment by eefriedman** [comment]
@bors-servo r-

Err, looks like I didn't rebase this correctly; looking.

**Comment by eefriedman** [comment]
Updated; not sure if `(&*self.upcast::<Element>().unsafe_get())` is a good way of writing the cast.

**Comment by frewsxcv** [comment]
> Updated; not sure if (&*self.upcast::<Element>().unsafe_get()) is a good way of writing the cast.

It's the best way I know of with the current system. The same strategy is used in similar methods in other HTMLElement modules, so if there is a better way, it should be updated in those too, which could happen in a follow-up PR.

@bors-servo r+


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8336)

**Comment by frewsxcv** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8336)

**Pull request merged**
