### PR TITLE
Matching over event listeners and handlers; r=Ms2ger

### PR DESCRIPTION
**Pull request by ghost**
... for #7065

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7241)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
I'm not sure whether this is what's expected, because my changes have rendered `get_listener` unusable for now. So, I chose to keep it as `dead_code` for future use.

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

Thank you for your PR. I have some suggestions below.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/eventdispatcher.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7241#-JwuqrLhS3ndfLLlC02Z)** ([raw file](https://github.com/servo/servo/blob/5e8506742ab8521e36c3e08290b2a61e739938fc/components/script/dom/eventdispatcher.rs#L48)):</sup>
I think `listener` was a better name.

---

<sup>**[components/script/dom/eventtarget.rs, line 111 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7241#-Jwuqy6_wfn6e1aGMNN8)** ([raw file](https://github.com/servo/servo/blob/5e8506742ab8521e36c3e08290b2a61e739938fc/components/script/dom/eventtarget.rs#L111)):</sup>
Remove this

---

<sup>**[components/script/dom/eventtarget.rs, line 118 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7241#-JwuqzT-i-9ofOtR7Hid)** ([raw file](https://github.com/servo/servo/blob/5e8506742ab8521e36c3e08290b2a61e739938fc/components/script/dom/eventtarget.rs#L118)):</sup>
And this

---

<sup>**[components/script/dom/eventtarget.rs, line 165 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7241#-Jwur3eXvdKFEVcrhEGE)** ([raw file](https://github.com/servo/servo/blob/5e8506742ab8521e36c3e08290b2a61e739938fc/components/script/dom/eventtarget.rs#L165)):</sup>
I think this can just be `.get(type_).clone()`

---

<sup>**[components/script/dom/eventtarget.rs, line 261 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7241#-JwurF98Y0mmNF1WZz9t)** ([raw file](https://github.com/servo/servo/blob/5e8506742ab8521e36c3e08290b2a61e739938fc/components/script/dom/eventtarget.rs#L261)):</sup>
`iter().filter_map(...).next()` would be cleaner here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7241)

**Comment by Wafflespeanut** [comment]
@Ms2ger You're right and I've fixed everything other than the one in `get_listeners`, because `self.handlers.borrow().get(type_)` seems to give an `&Vec<EventListenerEntry>`, and so we have to iterate throughout the thing to get the event listeners out. I can't see how they could be pulled out otherwise :/

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7241)

**Comment by Wafflespeanut** [comment]
@Ms2ger Ah! I forgot to test the thing -_-

**Pull request merged**
