### PR TITLE
compositing: Don't translate points to layer space when using WebRender.

### LINKED ISSUE #11108: [regression] hittest issue - iframe in the background take precedence over foreground elements
```html
<style>
  iframe, div {
    display: block;
    top: 0;
    left: 0;
    position: absolute;
  }
  iframe {
    border-width: 0;
    width: 100%;
    height: 100%;
  }
  div {
    width: 100px;
    height: 100px;
    background: red;
  }
</style>
<iframe src="http://example.com"></iframe>
<div onclick="console.log(42)"></div>
```

### PR DESCRIPTION
**Pull request by pcwalton**
This makes mouse events take the same code path, regardless of whether
WebRender is in use or not. This approach enables accurate
display-list-based hit testing when WebRender is in use.

Closes #11108.

r? @glennw

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11537)

### CODE REVIEW

**Comment by glennw** [comment]
@pcwalton This looks good to me. Could you just verify that it works with --device-pixel-ratio set to 1 and 2, and then r=me.

**Comment by pcwalton** [comment]
Verified that it works with different device pixel ratios.

**Comment by pcwalton** [comment]
@bors-servo: retry

Seems infra related.

**Comment by larsbergstrom** [comment]
@bors-servo retry
 - infra (new servo-mac1)

**Comment by larsbergstrom** [comment]
Weird, I see the mac-rel-wpt failure as:
```
./mach build --release
 in dir /Users/servo/buildbot/slave/mac-rel-wpt/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['./mach', 'build', '--release']
 environment:
  CARGO_HOME=/Users/servo/.cargo
  CCACHE=/usr/local/bin/ccache
  HOME=/Users/servo
  LOGNAME=servo
  PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  PWD=/Users/servo/buildbot/slave/mac-rel-wpt/build
  RUST_BACKTRACE=1
  SERVO_CACHE_DIR=/Users/servo/.servo
  SHELL=/bin/bash
  TMPDIR=/var/folders/vw/bcpmp_yj5c304vm86dyyq8800000gp/T/
  USER=servo
  XPC_FLAGS=0x0
  XPC_SERVICE_NAME=buildslave
  __CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0
 using PTY: False
Pip failed to execute properly: Could not open requirements file: [Errno 2] No such file or directory: '/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/requirements.txt'
```

**Comment by paulrouget** [comment]
Could this have caused this: https://github.com/servo/servo/issues/11648

**Pull request merged**
