### PR TITLE
Add libffi to pkgconfig's search path.

### LINKED ISSUE #23358: servo-tc-mac3 doesn't pass the gstreamer check
`bin/pkg-config --atleast-version=1.14 gstreamer; echo $?` return 1, and on other mac machines it returns 0.

### PR DESCRIPTION
**Pull request by jdm**
Fixes #23358.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23359)

### CODE REVIEW

**Comment by CYBAI** [comment]
@bors-servo retry

- #23354

**Comment by jdm** [comment]
I'm looking into the openssl failure.

**Comment by jdm** [comment]
Amazing. System integrity protection is enabled on servo-tc-mac3, so DYLD_LIBRARY_PATH has no effect. It's disabled on the other TC mac build machines, so I'm going to take this machine out of the pool until I can get macstadium to look at it.

**Comment by SimonSapin** [comment]
I’m not super familiar with pkg-config details, but if CI is happy I’m happy.

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #23322 22212

**Pull request merged**
