### PR TITLE
Remove URL.domainToASCII and URL.domainToUnicode

### LINKED ISSUE #13835: Remove URL.domainToASCII and URL.domainToUnicode
They were removed from the spec.

https://twitter.com/urlstandard/status/788712433934270464

Files:
 * components/script/dom/url.rs
 * components/script/dom/webidls/URL.webidl

### PR DESCRIPTION
**Pull request by leaexplores**
Modifications
- Removed URL.domainToASCII method
- Removed URL.domainToUnicode method
- Added test in wpt to make sure both method are undefined.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13835  (github issue number if applicable).
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13912)

### CODE REVIEW

**Comment by Ms2ger** [comment]
That's perfect, thank you!

@bors-servo r+

**Comment by Ms2ger** [comment]
Sounds like you get to `git rm url/url-domainToUnicode.html` (and `./mach update-manifest`).

**Comment by ddrmanxbxfr** [comment]
@Ms2ger Done, i've regenerated the manifest and removed the unrelated file.

**Pull request merged**
