### PR TITLE
Create a seperate thread for devtools' TCP acceptor (Closes #5294).

### LINKED ISSUE #5294: Move devtools TCP acceptor into a separate thread
We have code in devtools/lib.rs that runs an event loop that watches for events from many sources. One of these sources is the TCP server that's waiting for connections. Right now we block on it for 300ms (see the set_timeout calls), and then poll the other event sources. We should make a dedicated thread for this server, then send an event to the main event loop with the new stream object when a connection is made.

### PR DESCRIPTION
**Pull request by aweinstock314**

### CODE REVIEW

**Comment by jdm** [comment]
@aweinstock314 Have you tested running servo with the devtools server enabled and connecting to it from Firefox? [This page](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Thunderbird) describes how to do the latter.

**Comment by aweinstock314** [comment]
I just tested that, it seems to work (devtools console displays the DOM tree from servo). (Previously, I had tested with "netcat localhost 6000", got a JSON blob on start, but didn't know what to send it. I did verify through netcat that multiple concurrent connections are accepted)

**Comment by jdm** [comment]
And Servo shuts down without completely when you press escape, whether there's a client connected or not?

**Comment by aweinstock314** [comment]
Yes (and the devtools window closes too).

**Comment by jdm** [comment]
Rad!

**Comment by jdm** [comment]
Just a couple small requests on Critic. Thanks for doing this!

**Pull request merged**
