### PR TITLE
remove DocumentProgressTask enum

### PR DESCRIPTION
**Pull request by ajnirp**
for #8211

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8217)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+

Thanks!

**Comment by Manishearth** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8217)

**Comment by Manishearth** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8217)

**Comment by Manishearth** [comment]
@eefriedman We've not yet updated the servers with your review bit. Will do when the queue is empty.

**Comment by Manishearth** [comment]
@bors-servo r-

Going to update the server, keeping the queue clean (temporary)

**Comment by Manishearth** [comment]
@eefriedman You should be able to use the bors commands now. Enjoy!

**Comment by eefriedman** [comment]
@Manishearth Thanks. :)

**Pull request merged**
