### PR TITLE
Install virtualenv through APT, in Docker images

### LINKED ISSUE #25757: Docker image creation is busted
The docker image was created as part of the WPT update job today, and it failed with:
```

Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/18/cb/9799b00a192391cab56f1e6400bfdeb331afff7527e18dc3df25543782ff/virtualenv-20.0.3-py2.py3-none-any.whl (4.6MB)
Collecting filelock<4,>=3.0.0 (from virtualenv)
  Downloading https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
```

Virtualenv v20 was release in the past month, which is the last time the image was recreated.

### PR DESCRIPTION
**Pull request by SimonSapin**
Fix https://github.com/servo/servo/issues/25757
Close https://github.com/servo/servo/pull/25758

### CODE REVIEW

**Comment by SimonSapin** [comment]
Green in https://community-tc.services.mozilla.com/tasks/groups/F9pNqZKZS1-bwvMoiphRCw

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Pull request merged**
