### PR TITLE
[WIP] Modify criteria for synthetic click event on Enter/Space

### PR DESCRIPTION
**Pull request by nishanthkarthik**
Normalize behaviour of space vs. return for activating elements #22782 

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22904)

### CODE REVIEW

**Comment by ferjm** [comment]
There are a couple of Travis CI errors to fix:

- Formatting errors that you can fix by running `./mach fmt`
- Unused imports warnings that break the build:

```
error: unused imports: `ActivationSource`, `synthetic_click_activation`
 --> components/script/dom/htmlbuttonelement.rs:5:30
  |
5 | use crate::dom::activation::{synthetic_click_activation, Activatable, ActivationSource};
  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^               ^^^^^^^^^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`
error: unused import: `document_from_node`
  --> components/script/dom/htmlbuttonelement.rs:21:24
   |
21 | use crate::dom::node::{document_from_node, window_from_node, Node, UnbindContext};
   |                        ^^^^^^^^^^^^^^^^^^
error: aborting due to 2 previous errors
error: Could not compile `script`.
To learn more, run the command again with --verbose.
The command "./mach test-unit" exited with 101.
```

**Comment by jdm** [comment]
@nishanthkarthik Are you planning to complete this work?

**Comment by nishanthkarthik** [comment]
@jdm I am caught up at work, might not be able to get to this PR this week. You can take over if it's blocking your dev.

**Comment by ferjm** [comment]
Closing due to inactivity. If you want to return to it, go ahead and reopen it, please. Thanks!

**Pull request closed without merging**
