### PR TITLE
Update Rust to 1.13.0-nightly (198713106 2016-08-26)

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13055)

### CODE REVIEW

**Comment by metajack** [comment]
r=me

And hooray for memshrinkage!

**Comment by nox** [comment]
https://github.com/zmike/cef-rebase/pull/1

**Comment by nox** [comment]
```
Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /_mozilla/css/iframe/hide_layers2.html
  │ 
  └ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
```

This is #13059.

**Comment by nox** [comment]
Needs https://github.com/rust-lang/rust/pull/36008.

**Comment by nox** [comment]
And https://github.com/servo/rust-mozjs/pull/298 of course.

**Comment by nox** [comment]
Forgot to remove "(Do not merge)" damn. Anyway, for the record: this was ready to be merged.

**Pull request merged**
