### PR TITLE
Use SmallBitVec to optimize size of PropertyDeclarationBlock

### PR DESCRIPTION
**Pull request by mbrubeck**
https://bugzilla.mozilla.org/show_bug.cgi?id=1398322

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18431)

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ CRASH [expected FAIL] /css21_dev/html4/first-letter-punctuation-234.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 17.2.0-devel
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ CRASH [expected FAIL] /css21_dev/html4/first-letter-punctuation-236.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 17.2.0-devel
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ CRASH [expected FAIL] /css21_dev/html4/first-letter-punctuation-237.htm

  ▶ CRASH [expected FAIL] /css21_dev/html4/first-letter-punctuation-235.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 17.2.0-devel
  └ Shutting down the Constellation after generating an output file or exit flag specified
```

**Comment by mbrubeck** [comment]
@bors-servo retry

* infra

**Comment by mbrubeck** [comment]
@bors-servo try-

I think this is ready now. r? @bholley

**Comment by bholley** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1398322#c14 regarding eq perf, which I think we should probably fix before landing, otherwise revalidation will get slower.

At a high-level this looks great otherwise, but given the unsafe code I think it probably deserves a more-careful review than I have cycles for at the moment, so probably @SimonSapin or @Manishearth should at least review the SmallBitVec code.

**Comment by mbrubeck** [comment]
> See https://bugzilla.mozilla.org/show_bug.cgi?id=1398322#c14 regarding eq perf, which I think we should probably fix before landing, otherwise revalidation will get slower.

The latest `smallbitvec` now has fast paths for `eq`.

**Comment by SimonSapin** [comment]
r=me on this PR and https://github.com/servo/smallbitvec/blob/v1.0.2/src/lib.rs. While we’re at it, let’s land this with 1.0.3 instead of 1.0.2?

---

Reviewed 5 of 5 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/style/properties/declaration_block.rs, line 81 at r2](https://reviewable.io:443/reviews/servo/servo/18431#-Ktkp4eSPK4mfxsjKlFy:-Ktkp4eTjQuvwm1u2621:b-bcubcu) ([raw file](https://github.com/servo/servo/blob/606e597d1a7fe292e0cd7958f6e57ca848f2a14e/components/style/properties/declaration_block.rs#L81)):*
> ```Rust
> 
>     /// The "important" flag for each declaration in `declarations`.
>     important_declarations: SmallBitVec,
> ```

`important_declarations` sounds to be like it contains declarations that have the `!important` flag. Rename this to `declarations_importance`?

---

*[components/style/properties/declaration_block.rs, line 249 at r2](https://reviewable.io:443/reviews/servo/servo/18431#-Ktkpkf-Zl3mKoDifxoQ:-Ktkpkf0EouzYtrLJsQt:bifojna) ([raw file](https://github.com/servo/servo/blob/606e597d1a7fe292e0cd7958f6e57ca848f2a14e/components/style/properties/declaration_block.rs#L249)):*
> ```Rust
>     pub fn get(&self, property: PropertyDeclarationId) -> Option<(&PropertyDeclaration, Importance)> {
>         self.declarations.iter().position(|decl| decl.id() == property).map(|i| {
>             let decl = &self.declarations[i];
> ```

To avoid indexing, could this use `.enumerate().find(…)` instead of `.position(…)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18431#-:-Ktl13A8u3PxMFMvhK5D:b-qkqwpe)*

**Comment by mbrubeck** [comment]
@bors-servo r=SimonSapin

Addressed all of the review comments above.

**Comment by mbrubeck** [comment]
@bors-servo retry

Infra

**Pull request merged**
