### PR TITLE
Implement a FileList

### PR DESCRIPTION
**Pull request by cuzbog**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6714)

### CODE REVIEW

**Comment by jdm** [comment]
For future reference, adding more description to the commit messages (like "Implement the FileList interface. Fixes #6708") would be useful!

**Comment by jdm** [comment]
This will require updating http://mxr.mozilla.org/servo/source/tests/wpt/mozilla/tests/mozilla/interfaces.html?force=1 and a bunch of the tests that appear in the results at http://mxr.mozilla.org/servo/search?string=filelist will now have different results.

**Comment by farodin91** [comment]
You not needing to add another link for checking WebIDLs.
This work correct http://dev.w3.org/2006/webapi/FileAPI/#dfn-filelist

**Comment by boghison** [comment]
@farodin91 I'd prefer having links to what w3 is using now, not in the past, even if they are redirected.

**Comment by boghison** [comment]
@jdm I am not seeing any unexpected results.

**Comment by jdm** [comment]
@boghison Really? `./mach test-wpt tests/wpt/mozilla/tests/mozilla/interfaces.html` should fail, and `./mach test-wpt tests/wpt/web-platform-tests/FileAPI/` should have a bunch of unexpected PASS values now.

**Comment by boghison** [comment]
@jdm Thanks for the paths. Interfaces crashed. The second one: `Unexpected results: 109 (CRASH: 1, FAIL: 100, PASS: 8)`. FileList passed, the rest failed :( (Is this normal?)

**Comment by jdm** [comment]
Oh, I bet the tests aren't enabled by default, so this is the first time we're getting results for them: http://mxr.mozilla.org/servo/source/tests/wpt/include.ini#12

**Comment by boghison** [comment]
@jdm What should I do?

**Comment by jdm** [comment]
Oh, sorry I wasn't clear! You can update the test in mozilla/, but for the other ones you'll want to follow the steps at http://mxr.mozilla.org/servo/source/tests/wpt/README.md#71

**Comment by boghison** [comment]
@jdm I'm confused. The interfaces test crashed because I was running it through ssh. It now says "FAIL Interfaces exposed on the window". How do I update it? And for the rest, I can manually edit the FailList ones to make the pass, but as I said, 100 are failing (mostly Blob and FileReader). Those are not caused by my changes.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/filelist.rs, line 32 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6714#-Jv9XTAVf9B8fONDDJE7)** ([raw file](https://github.com/servo/servo/blob/fb9e25b8bd30fe8af4ef4185e9bd206b0277fc37/components/script/dom/filelist.rs#L32)):</sup>
Let's not add this method until we actually need it.

---

<sup>**[test.html, line 5 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6714#-Jv9Y6BO4KCb0DEUZJv1)** ([raw file](https://github.com/servo/servo/blob/dbe0ebcf89c1cb035cbe00c714665215454ddfd5/test.html#L5)):</sup>
I think this file can be removed.

---

<sup>**[tests/wpt/metadata/FileAPI/filelist-section/filelist.html.ini, line 7 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6714#-Jv9Y9KkofDhZYZ4RtCw)** ([raw file](https://github.com/servo/servo/blob/dbe0ebcf89c1cb035cbe00c714665215454ddfd5/tests/wpt/metadata/FileAPI/filelist-section/filelist.html.ini#L7)):</sup>
We can remove these lines now (both the `[...]` and the `expected: PASS`).

---

<sup>**[tests/wpt/metadata/FileAPI/idlharness.html.ini, line 64 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6714#-Jv9YNfYFylijW6BDVgm)** ([raw file](https://github.com/servo/servo/blob/dbe0ebcf89c1cb035cbe00c714665215454ddfd5/tests/wpt/metadata/FileAPI/idlharness.html.ini#L64)):</sup>
Same here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6714)

**Comment by boghison** [comment]
<sup>**[components/script/dom/filelist.rs, line 32 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6714#-Jv9XTAVf9B8fONDDJE7)** ([raw file](https://github.com/servo/servo/blob/fb9e25b8bd30fe8af4ef4185e9bd206b0277fc37/components/script/dom/filelist.rs#L32)):</sup>
I based my code on NodeList, but if you don't want it, I'll take it out.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6714)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/filelist.rs, line 32 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6714#-Jv9XTAVf9B8fONDDJE7)** ([raw file](https://github.com/servo/servo/blob/fb9e25b8bd30fe8af4ef4185e9bd206b0277fc37/components/script/dom/filelist.rs#L32)):</sup>
Yep. It was added to NodeList because it was a common operation to perform. I'm not certain the same will be true for FileList, and it's easy to add back if we need it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6714)

**Comment by boghison** [comment]
@jdm Is this ok now?

**Comment by jdm** [comment]
One last tidy error:
```
$ ./mach test-tidy

components/script/dom/webidls/FileList.webidl:11: no newline at EOF
```

**Comment by jdm** [comment]
You can go ahead and squash them all together into one commit, too.

**Comment by boghison** [comment]
@jdm Squashed, rebased and fixed :)

**Comment by Ms2ger** [comment]
```
/FileAPI/idlharness.worker
--------------------------
PASS expected FAIL FileList interface: existence and properties of interface object
PASS expected FAIL FileList interface object length
PASS expected FAIL FileList interface: existence and properties of interface prototype object
PASS expected FAIL FileList interface: existence and properties of interface prototype object's "constructor" property
PASS expected FAIL FileList interface: operation item(unsigned long)
PASS expected FAIL FileList interface: attribute length
/workers/semantics/interface-objects/001.worker
-----------------------------------------------
PASS expected FAIL The FileList interface object should be exposed.
```

**Comment by boghison** [comment]
Umm... So what do I do? Weren't those tests supposed to be ignored or something now (since I deleted those lines)?

**Comment by jdm** [comment]
No, those tests results need to updated as well - the changes in this PR don't touch those files.

**Comment by boghison** [comment]
@jdm What do I need to do?

**Comment by jdm** [comment]
Modify http://mxr.mozilla.org/servo/source/tests/wpt/metadata/FileAPI/idlharness.worker.js.ini and http://mxr.mozilla.org/servo/source/tests/wpt/metadata/workers/semantics/interface-objects/001.worker.js.ini to remove the tests that are now passing.

**Comment by boghison** [comment]
Ok, done.

**Comment by metajack** [comment]
@bors-servo retry

ref tests appeard to have gotten stuck. never seen that before.

**Pull request merged**
