### PR TITLE
Throwing errors on event compilation, without panics and at least sometimes test-passingly

### LINKED ISSUE #25200: Setting onclick to a garbage string and then evaluating it (without calling it) should fire an error event but doesn't
WPT html/webappapis/scripting/events/invalid-uncompiled-raw-handler-compiled-once.window.html  and invalid-uncompiled-raw-handler-keeps-position.window.html fail on this; they expect window.onerror to have fired and it hasn't. The onclick is showing up as null, so there was an attempt to compile the Javascript that decided it was invalid, but the invalidness didn't manifest in an error.

### PR DESCRIPTION
**Pull request by pshaughn**
Error events on event handler attribute string compilation were disabled a few years ago (#13152) for fear of a double-borrow panic; event propagation code has changed enough since then that enabling the events is possible and makes some WPT cases happy.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25200 and make progress on #13152 

- [X] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ OK [expected TIMEOUT] /html/webappapis/scripting/events/compile-event-handler-lexical-scopes.html

  ▶ ERROR [expected OK] /_mozilla/mozilla/event_handler_syntax_error.html
  │   → missing } after function body
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/event_handler_syntax_error.html:14:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25
  │ test@http://web-platform.test:8000/resources/testharness.js:548:30
  └ @http://web-platform.test:8000/_mozilla/mozilla/event_handler_syntax_error.html:12:3
```

**Comment by pshaughn** [comment]
https://github.com/servo/servo/blob/master/components/script/dom/htmlelement.rs#L728 seems to be at fault: any attribute starting with "on" gets stored as an uncompiled event handler instead of a string, even when it isn't an event handler attribute.

**Comment by pshaughn** [comment]
This was sort of working, but I stopped it to await https://github.com/servo/servo/pull/25274 so we wouldn't get spurious errors, and then I think that one ran aground?

**Comment by jdm** [comment]
I suspect we can fix event_handler_syntax_error.html by using assert_throws_dom judiciously to verify that an error event occurs without it reaching the test harness?

**Comment by pshaughn** [comment]
It shouldn't be throwing an exception at all. onx and ony should just behave as ordinary attribute names and not do any event-listener compilation.

**Comment by pshaughn** [comment]
Oh, I misread the line number and error type. Line 14 fails for an ErrorEvent, not an exception; we can get around this by putting `setup({ allow_uncaught_exception: true })` at the top of the script. Since that'll also allow literal uncaught exceptions, we can also wrap everything in a try/catch with an assert_unreached in the catch block; that way we allow error events but still catch unexpected exceptions.

**Comment by pshaughn** [comment]
I adjusted that test, pulled in #25249, adjusted #25249 to concatenate "on" before all the event names when building the lookup map for handler names, and I suspect this might actually work.
@bors-servo try=wpt

**Comment by pshaughn** [comment]
Weird and probably not the code; I need to add another check to that event_handler_syntax_error.html test anyway though

**Comment by pshaughn** [comment]
Nope, this combination of merges isn't working, I'm getting script in an "onx" content attribute run when I fire an "x" event. My own code changes here are tiny compared to @Manishearth's; there's not really anything of mine here especially worth keeping other than the concat("on") bit.

**Pull request closed without merging**
