### PR TITLE
Write unit tests for cookie isolation

### LINKED ISSUE #7624: Write unit tests for cookie isolation
We are missing tests for the following functionality:
* when a cookie is set for domain a.com with CookieSource::NonHttp, it should not be included in a subsequent request for a.com
* when a cookie is received that is marked httpsOnly, it is ignored if the request was for an http connection (instead of https)
* when a cookie is set for a.com and is marked httpsOnly, it is not sent as part of requests that are for http://a.com

Code: tests/unit/net/http_loader.rs

### PR DESCRIPTION
**Pull request by jxs**
closes #7624

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7646)

### CODE REVIEW

**Comment by jdm** [comment]
Good start!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 464 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzM1zgCMUtgjRZsbgO7)** ([raw file](https://github.com/servo/servo/blob/1f7441e7c2f4ac8f56f494ff37b8fd9197d0bd9e/tests/unit/net/http_loader.rs#L464)):</sup>
s/set/send/

---

<sup>**[tests/unit/net/http_loader.rs, line 467 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzM22yZEoKCuSNLbJLm)** ([raw file](https://github.com/servo/servo/blob/1f7441e7c2f4ac8f56f494ff37b8fd9197d0bd9e/tests/unit/net/http_loader.rs#L467)):</sup>
Let's use the url variable here instead.

---

<sup>**[tests/unit/net/http_loader.rs, line 473 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzM3fYT2snVGz-VCE_o)** ([raw file](https://github.com/servo/servo/blob/1f7441e7c2f4ac8f56f494ff37b8fd9197d0bd9e/tests/unit/net/http_loader.rs#L473)):</sup>
Let's add an `AssertRequestMustNotHaveHeaders` for clarity (and because this won't actually test what we want until #7646).

---

<sup>**[tests/unit/net/http_loader.rs, line 482 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzM2R27T88Vcw1HyXqZ)** ([raw file](https://github.com/servo/servo/blob/1f7441e7c2f4ac8f56f494ff37b8fd9197d0bd9e/tests/unit/net/http_loader.rs#L482)):</sup>
No need for the `httpsonly` bit in this name.

---

<sup>**[tests/unit/net/http_loader.rs, line 484 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzM2L7yvxPDd3P-yGt1)** ([raw file](https://github.com/servo/servo/blob/1f7441e7c2f4ac8f56f494ff37b8fd9197d0bd9e/tests/unit/net/http_loader.rs#L484)):</sup>
This is a good start, but we can be more thorough. Instead of setting cookies manually by sending a SetCookiesForUrl for this test, we should be making a request that produces a response that includes a Set-Cookie header. Does that make sense?

---

<sup>**[tests/unit/net/http_loader.rs, line 495 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzM3UlykCdk1j_9L3OA)** ([raw file](https://github.com/servo/servo/blob/1f7441e7c2f4ac8f56f494ff37b8fd9197d0bd9e/tests/unit/net/http_loader.rs#L495)):</sup>
This should be https://, and we should assert that the cookie was set properly after doing this.

---

<sup>**[tests/unit/net/http_loader.rs, line 501 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzM3osQ4vWm7-9-REt-)** ([raw file](https://github.com/servo/servo/blob/1f7441e7c2f4ac8f56f494ff37b8fd9197d0bd9e/tests/unit/net/http_loader.rs#L501)):</sup>
Let's use the `AssertRequestMustNotHaveHeaders` from earlier.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7646)

**Comment by jxs** [comment]
thanks @jdm, updated it, but still have 2 issues:
- getting this :
```
http_loader::test_when_cookie_set_marked_httpsonly_secure_isnt_sent_on_http_request stdout ----
	thread 'http_loader::test_when_cookie_set_marked_httpsonly_secure_isnt_sent_on_http_request' panicked at 'assertion failed: `(left == right)` (left: `"mozillaIs=theBest; HttpOnly; Secure;"`, right: `"mozillaIs=theBest"`)', /Volumes/data/dev/jxs/servo/tests/unit/net/http_loader.rs:227
``` 

on making a request that produces a response, should i use MockRequest/MockResponse ?
 and how do i integrate it with a ResourceTask ?

**Comment by jdm** [comment]
That's the correct output; the code that fetches cookies for a given URL only returns data in the form "name=value" (see http://mxr.mozilla.org/servo/source/components/net/cookie_storage.rs#100), so the expected output needs to be corrected.

**Comment by jdm** [comment]
As for making a response, yes, we want a MockRequest that uses ResponseType::WithHeaders like http://mxr.mozilla.org/servo/source/tests/unit/net/http_loader.rs#426 .

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 178 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzOdwGdPFvtEddfCVCt)** ([raw file](https://github.com/servo/servo/blob/6f23979f33ea09f6a41d9bb9284335a22be6bc7c/tests/unit/net/http_loader.rs#L178)):</sup>
Since we're not checking the header values, let's just store `Vec<String>` instead.

---

<sup>**[tests/unit/net/http_loader.rs, line 197 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzOdmnwPsx2LW6H3E_O)** ([raw file](https://github.com/servo/servo/blob/6f23979f33ea09f6a41d9bb9284335a22be6bc7c/tests/unit/net/http_loader.rs#L197)):</sup>
I think this can be `for header in &self.headers_not_expected {`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7646)

**Comment by jxs** [comment]
thanks! updated
but still having one failing, now on:
```
http_loader::test_load_doesnt_send_cookie_if_nonhttp stdout ----
	thread 'http_loader::test_load_doesnt_send_cookie_if_nonhttp' panicked at 'assertion failed: self.request_headers.get_raw(header).is_none()', /Volumes/data/dev/jxs/servo/tests/unit/net/http_loader.rs:198
```

**Comment by jdm** [comment]
Oh! That's because the premise of the test is incorrect; my apologies! We do actually want to send NonHTTP cookies with HTTP requests, so let's make this test for that instead by using AssertRequestMustHaveHeaders :)

My original request was confused - what I was thinking of is that cookies that are set with `httponly` should not be available when using GetCookiesForUrl and passing CookieSource::NonHttp.

**Comment by jxs** [comment]
no problem :)
updated it, do you want me to also test for that, cookies set with httponly should not be available when using GetCookiesForUrl and passing CookieSource::NonHttp?

**Comment by jdm** [comment]
Yes, it looks like we don't have any for that. Let's have the test use a request that uses Set-Cookie, rather than setting it directly, too.

**Comment by jxs** [comment]
ok, added `test_cookie_set_with_httponly_should_not_be_available_using_getcookiesforurl`

**Comment by jxs** [comment]
@jdm r+ ?

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 585 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzkknZiKKQWlO4RuVBb)** ([raw file](https://github.com/servo/servo/blob/c1215b8086c4378535867d6c21ef78d726cc053c/tests/unit/net/http_loader.rs#L585)):</sup>
The `Secure` here means this cookie will not actually be set (since it's an insecure URL). we should remove it so we're actually testing what we want :)

---

<sup>**[tests/unit/net/http_loader.rs, line 614 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzklGLYLDLZiUatI_zR)** ([raw file](https://github.com/servo/servo/blob/c1215b8086c4378535867d6c21ef78d726cc053c/tests/unit/net/http_loader.rs#L614)):</sup>
Let's remove the HttpOnly here.

---

<sup>**[tests/unit/net/http_loader.rs, line 631 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7646#-JzklXcT2bvUPGIcwS32)** ([raw file](https://github.com/servo/servo/blob/c1215b8086c4378535867d6c21ef78d726cc053c/tests/unit/net/http_loader.rs#L631)):</sup>
Let's remove the HttpOnly here, too.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7646)

**Comment by jdm** [comment]
@jxs Are you still planning to finish this up?

**Comment by jxs** [comment]
yes sorry @jdm i have been away, i'll finish it this weekend

**Comment by jdm** [comment]
Not a problem! Thanks!

**Comment by jxs** [comment]
updated!
still there's one test failing
```failures:

---- http_loader::test_when_cookie_set_marked_httpsonly_secure_isnt_sent_on_http_request stdout ----
	thread 'http_loader::test_when_cookie_set_marked_httpsonly_secure_isnt_sent_on_http_request' panicked at 'assertion failed: self.request_headers.get_raw(header).is_none()', /Volumes/data/dev/jxs/servo/tests/unit/net/http_loader.rs:265


failures:
    http_loader::test_when_cookie_set_marked_httpsonly_secure_isnt_sent_on_http_request
```

**Comment by jdm** [comment]
Almost there!
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[tests/unit/net/http_loader.rs, line 883 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7646#-K2myMmmA0urmjxwqCvM)** ([raw file](https://github.com/servo/servo/blob/bdc889e9db455650f38600015a862b7683323267/tests/unit/net/http_loader.rs#L883)):</sup>
This is using the http:// URL for the secure cookie, now, hence the test failure.


---

<sup>**[tests/unit/net/http_loader.rs, line 887 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7646#-K2myUrmnjzAGkyuGpm7)** ([raw file](https://github.com/servo/servo/blob/bdc889e9db455650f38600015a862b7683323267/tests/unit/net/http_loader.rs#L887)):</sup>
Let's call this HTTP instead, to match the push call below.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7646)

**Comment by jxs** [comment]
updated! but still failing that test

**Comment by jdm** [comment]
Yes, because of the URL that is still not secure :)
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7646)

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for sticking with it!


---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7646)

**Comment by jdm** [comment]
@bors-servo: retry
* #8416

**Comment by jdm** [comment]
Uh oh:
```
---- http_loader::test_when_cookie_set_marked_httpsonly_secure_isnt_sent_on_http_request stdout ----
	thread 'http_loader::test_when_cookie_set_marked_httpsonly_secure_isnt_sent_on_http_request' panicked at 'assertion failed: self.request_headers.get_raw(header).is_none()', /Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:265
```

**Comment by jdm** [comment]
Ah, I misread the last change; my mistake. https://github.com/servo/servo/pull/7646/files#diff-c007a862cc2c468a1b2ae7aa7707e35dR876 says we're setting a secure cookie for https://mozilla.com as expected, but we're also making a request to https://mozilla.com, which explains why the test is failing. We should be requesting http://mozilla.com instead, and making sure that the previously stored cookie is not present in the request.

**Comment by jxs** [comment]
updated, and makes sense! test still failing though

**Comment by jdm** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/unit/net/http_loader.rs, line 877 \[r7\]](https://reviewable.io:443/reviews/servo/servo/7646#-K2tuSr-c-h7RsbN48iH)** ([raw file](https://github.com/servo/servo/blob/a8356bfa6515f3e2d1637cc34c26184d68fb4512/tests/unit/net/http_loader.rs#L877)):</sup>
I have a theory - what if we use example.com instead of mozilla.com? I think the insecure request is being upgraded due to the HSTS preload entry: http://mxr.mozilla.org/servo/source/resources/hsts_preload.json#1856


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7646)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 1 of 1 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7646)

**Pull request merged**
