### PR TITLE
style: Remove HasViewportPercentage.

### PR DESCRIPTION
**Pull request by emilio**
It's not needed since #18268, let's kill it.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18300)

### CODE REVIEW

**Comment by nox** [comment]
Nice.

@bors-servo r+

**Comment by emilio** [comment]
@bors-servo retry

 * infra

**Comment by emilio** [comment]
Too bad this diff was that small :(

**Comment by jdm** [comment]
Any chance this is caused by these changes?
```
  ▶ ERROR [expected OK] /_mozilla/css/animations/basic-linear-width.html
  └   → uncaught exception: unknown (can't convert to string)

  ▶ Unexpected subtest result in /_mozilla/css/animations/basic-linear-width.html:
  │ TIMEOUT [expected PASS] Animation test: Linear animation repeated infinitely.
  └   → Test timed out
```

**Comment by emilio** [comment]
No way, this is removing dead code.

@bors-servo retry

**Pull request merged**
