### PR TITLE
Remove activatable element filter within HTMLElement#click()

### PR DESCRIPTION
**Pull request by rebstar6**
Address https://github.com/servo/servo/issues/6542

Ensure that click() calls are not limited to activatable elements. Also makes the isTrusted attribute false when synthetic click activation are called from a click() method (as per spec).

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9930)

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /DOMEvents/throwing-in-listener-when-all-have-not-run-yet.html:
  └ PASS [expected FAIL] Throwing in event listener
```
You'll need to remove the appropriate ini file, now that the test passes :)

**Comment by rebstar6** [comment]
Wow, that definitely was not the test that I was coding for. Seems weird that it now passes, but I can certainly take that ini out.

**Comment by jdm** [comment]
Looks good! I've only got stylistic nits about the changes, so you can go ahead and squash all the commits together when you're addressing my comments.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 8 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[components/script/dom/activation.rs, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjE2dIuIoCwCaWLDs:-KCRjE2dIuIoCwCaWLDt:603939529) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L34)):*
Let's use `/// Whether an activation was initiated via the click() method`. We should also add `#[derive(PartialEq)]` to make comparisons easier later on.

---

*[components/script/dom/activation.rs, line 42 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjKeNNeV6a89JSr3q:-KCRjKeNNeV6a89JSr3r:455721599) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L42)):*
nit: let's align these arguments with `element`

---

*[components/script/dom/activation.rs, line 46 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjbzfMMwxUb1ALYjf:-KCRjbzfMMwxUb1ALYjg:-2049237525) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L46)):*
Let's call this `source`.

---

*[components/script/dom/activation.rs, line 54 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjqUQ0tCKqyA0pOjH:-KCRjqURVmoxEVFwreMG:1627134982) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L54)):*
Let's add a `let activatable = element.as_maybe_activatable()` and use that throughout this method.

---

*[components/script/dom/activation.rs, line 77 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjSE6LR37_AuAUQS3:-KCRjSE6LR37_AuAUQS4:-910358521) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L77)):*
```rust
if source == ActivationSource::FromClick {
    event.set_trusted(false);
}
```

---

*[components/script/dom/document.rs, line 8 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRk-sN6wX3859URcQh:-KCRk-sN6wX3859URcQi:-1761659905) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/document.rs#L8)):*
`use dom::activation::{ActivationSource, synthetic_click_activation};`

---

*[components/script/dom/document.rs, line 1083 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRk49r5nQfvuONuYo9:-KCRk49r5nQfvuONuYoA:-2093487359) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/document.rs#L1083)):*
nit: let's move this to the previous line and align the remaining arguments with it.

---

*[components/script/dom/htmlbuttonelement.rs, line 7 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkGVrvZcswRD7nO-_:-KCRkGVrvZcswRD7nO-a:-477306579) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlbuttonelement.rs#L7)):*
`use dom::activation::{Activatable, ActivationSource, synthetic_click_activation};`

---

*[components/script/dom/htmlelement.rs, line 6 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkPzzPieck9tIQNpG:-KCRkQ--4sk6nolqGhY6:-1761659905) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlelement.rs#L6)):*
`use dom::activation::{ActivationSource, synthetic_click_activation};`

---

*[components/script/dom/htmlelement.rs, line 188 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkXys-hZk9Si-PWZr:-KCRkXys-hZk9Si-PWZs:-1420984528) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlelement.rs#L188)):*
nit: ensure these arguments align with the previous line.

---

*[components/script/dom/htmlinputelement.rs, line 8 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkcQSl4Hq00X5Jno8:-KCRkcQSl4Hq00X5Jno9:-477387303) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlinputelement.rs#L8)):*
`use dom::activation::{Activatable, ActivationSource, synthetic_click_activation);`

---

*[components/script/dom/htmlinputelement.rs, line 906 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkhCvhcBHZOqQXdkn:-KCRkhCvhcBHZOqQXdko:2070328269) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlinputelement.rs#L906)):*
nit: ensure these arguments are indented to match the first one.

---

*[components/script/dom/htmllabelelement.rs, line 7 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRklSRqT3OGeCbyAI7:-KCRklSRqT3OGeCbyAI8:-477387303) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmllabelelement.rs#L7)):*
`use dom::activation::{Activatable, ActivationSource, synthetic_click_activation);`

---

*[components/script/dom/htmllabelelement.rs, line 69 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkm__eq4lSdfEC8RB:-KCRkm__eq4lSdfEC8RC:418491503) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmllabelelement.rs#L69)):*
nit: indentation

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9930#-:-KCRkyXE_HqzbbtVBqyG:-626262810)*

**Comment by rebstar6** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[components/script/dom/activation.rs, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjE2dIuIoCwCaWLDs:-KCVrKZJJRmztOF7W3-p:-1698881962) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L34)):*
On the enum? It's giving me: error: `derive` may only be applied to structs and enums

---

*[components/script/dom/activation.rs, line 42 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjKeNNeV6a89JSr3q:-KCVrZixEb7JJC9z9n0q:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L42)):*
Done.

---

*[components/script/dom/activation.rs, line 46 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjbzfMMwxUb1ALYjf:-KCVraVe0NPndPLJYv2D:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L46)):*
Done.

---

*[components/script/dom/activation.rs, line 54 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjqUQ0tCKqyA0pOjH:-KCVrbjqyr5PDYrOyeAu:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L54)):*
Done.

---

*[components/script/dom/activation.rs, line 77 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRjSE6LR37_AuAUQS3:-KCVrdz4o5kl2TBWlTxH:318698366) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/activation.rs#L77)):*
I had tried this initially but it gives errors: note: an implementation of `std::cmp::PartialEq` might be missing for `dom::activation::ActivationSource`

...which I'm now realizing is related to the partialeq comment above

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9930)*

**Comment by jdm** [comment]
Yes, I meant on the enum. Apologies if that's not where I commented.

**Comment by rebstar6** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[components/script/dom/document.rs, line 8 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRk-sN6wX3859URcQh:-KCVsxjdz0mPfGPlaTSN:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/document.rs#L8)):*
Done.

---

*[components/script/dom/document.rs, line 1083 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRk49r5nQfvuONuYo9:-KCVsyafaROp4glgYQrE:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/document.rs#L1083)):*
Done.

---

*[components/script/dom/htmlbuttonelement.rs, line 7 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkGVrvZcswRD7nO-_:-KCVtA155UrzdfinoWK3:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlbuttonelement.rs#L7)):*
Done.

---

*[components/script/dom/htmlelement.rs, line 6 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkPzzPieck9tIQNpG:-KCVtMAHMucfdCG4tHDM:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlelement.rs#L6)):*
Done.

---

*[components/script/dom/htmlelement.rs, line 188 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkXys-hZk9Si-PWZr:-KCVtNqQ_0a6rMTEFGkN:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlelement.rs#L188)):*
Done.

---

*[components/script/dom/htmlinputelement.rs, line 8 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkcQSl4Hq00X5Jno8:-KCVta7t_JeTc38Rp3jz:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlinputelement.rs#L8)):*
Done.

---

*[components/script/dom/htmlinputelement.rs, line 906 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkhCvhcBHZOqQXdkn:-KCVtcQX2LhsgvvOXgcS:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmlinputelement.rs#L906)):*
Done.

---

*[components/script/dom/htmllabelelement.rs, line 7 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRklSRqT3OGeCbyAI7:-KCVto7a66sG3yfT28js:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmllabelelement.rs#L7)):*
Done.

---

*[components/script/dom/htmllabelelement.rs, line 69 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCRkm__eq4lSdfEC8RB:-KCVtov0EkkESFwweH5a:-499146009) ([raw file](https://github.com/servo/servo/blob/bfa1b4f18f18d431b9603224ddcef539d0272f96/components/script/dom/htmllabelelement.rs#L69)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9930)*

**Comment by rebstar6** [comment]
Comments addressed, squashed down to 1 commit.

**Comment by jdm** [comment]
One last change and this will be good to merge :)
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/activation.rs, line 56 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCW3HEsVggYfBozzGmy:-KCW3HEsVggYfBozzGmz:1516546053) ([raw file](https://github.com/servo/servo/blob/8d2fb7f7c4f96cb7da6373812531a4ea2e1cf458/components/script/dom/activation.rs#L56)):*
Let's use `if let Some(a) = activatable {` here (and elsewhere in this function), since it's more idiomatic than using map for side-effects.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9930#-:-KCW3esT3ONEsd33f63x:-947857592)*

**Comment by rebstar6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/activation.rs, line 56 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9930#-KCW3HEsVggYfBozzGmy:-KCX2k9_4Du5MmBsnyJ-:-499146009) ([raw file](https://github.com/servo/servo/blob/8d2fb7f7c4f96cb7da6373812531a4ea2e1cf458/components/script/dom/activation.rs#L56)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9930)*

**Comment by jdm** [comment]
@bors-servo: retry
* #9012

**Pull request merged**
