### PR TITLE
Fix #12193 Servo displays upper level Thai character in wrong place.

### LINKED ISSUE #12193: Servo displays upper level Thai character in wrong place.
On Ubuntu 16.04, Servo nightly, that I downloaded on 2016-07-03, displays upper level Thai characters in the incorrect place. Moreover it choose incorrect glyph too. 

Update: Servo on Mac OS X 10.11.5. has this issue too.

The text is "ยินดี". It is supposed to display    ี  on top of ด but it displays     ิ   on top of น, which is incorrect glyph and incorrect placement. 

servo_thai_bug

An URL for the test case is http://file.veerkesto.net/servo_test/simple-thai.html

### PR DESCRIPTION
**Pull request by veer66**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12905)

### CODE REVIEW

**Comment by pcwalton** [comment]
Great find! Could you add a reftest for this to make sure it doesn't regress? Thanks :)

**Comment by emilio** [comment]
No luck, there wasn't a pre-existing test covering this, so you should create one as @pcwalton says. 

The word-break-break-all-007.htm test doesn't seem intermittent, and seems related to this PR, so it deserves some investigation too.

You don't need to do anything about the perspective test, that's #12891.

Thanks for your PR! :)

**Comment by veer66** [comment]
A reftest was just added.

**Comment by KiChjang** [comment]
What about the test failure for `word-break-break-all-007.htm`? Is that not addressed?

**Comment by emilio** [comment]
@KiChjang Hmm... I thought it was intermittent, but apparently it's not? Then it'll fail.

@bors-servo: r-

Yeah, it deserves some more investigation, @mbrubeck seemed to think they were passing accidentally in #11303, but yeah, agreed. @veer66 can you check if they were passing by accident before your patch or not?

**Comment by veer66** [comment]
According to /word-break-break-all-007.htm, after applying the patch, document.getElementById('testspan').offsetWidth returns 0.

Please give a hint where the code for obtaining offsetWidth is.

**Comment by emilio** [comment]
This is what you're looking for: https://github.com/servo/servo/blob/4cefbcc94927a1c7cf12b188c4abbd63d7636e3d/components/layout/query.rs#L777

Thanks!

**Comment by veer66** [comment]
document.getElementById('testspan').offsetWidth returned 0 for /word-break-break-all-007.htm even before the patch was applied. I keep investigating.

**Comment by veer66** [comment]
word-break-break-all-007.htm test should fail before apply patch.  

By increasing div.test width to 400px,

In Servo (2eb0328), it looks like picture below:

css_change

However, I should look like this: 

change_css

**Comment by veer66** [comment]
When I just change width of div in word-break-break-all-007.htm to 370px, the test can be passed.

In brief, the problem occurs because document.getElementById('testspan').offsetWidth always return 0.

**Comment by emilio** [comment]
It seems to me we might have been passing that test accidentally, but I'll let @pcwalton confirm if that's the case.

**Comment by pcwalton** [comment]
See https://github.com/servo/servo/pull/13442

**Pull request closed without merging**
