### PR TITLE
Use wptrunner for some old-style reftests.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8648)

### CODE REVIEW

**Comment by frewsxcv** [comment]
@bors-servo r+

---

Reviewed 6 of 6 files at r1, 8 of 8 files at r2, 6 of 6 files at r3, 8 of 8 files at r4, 8 of 8 files at r5, 6 of 6 files at r6, 6 of 6 files at r7, 6 of 6 files at r8, 6 of 6 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8648#-:-K3jearjWCk784lhbBjd:1236647940)_

**Comment by jdm** [comment]
If this hits #8502 again we should actually attempt to look into it.

**Pull request merged**
