### PR TITLE
Update HACKING_QUICKSTART.md

### PR DESCRIPTION
**Pull request by tshepang**
Some grammar fixes

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they are documentation changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12266)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/HACKING_QUICKSTART.md, line 12 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12266#-KLvr6wn4iN5sADhhOHE:-KLvr6wn4iN5sADhhOHF:117597245) ([raw file](https://github.com/servo/servo/blob/0325bf7f073af5635ccbd46a44016ab31814dbac/docs/HACKING_QUICKSTART.md#L12)):*
> ```Markdown
> ## Building Servo
> 
> Building Servo is quite easy. Install the pre-requisites described in the [README](../README.md) file, then type:
> ```

"Prerequisites" exists and seems to be more widely-used, no?

---

*[docs/HACKING_QUICKSTART.md, line 48 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12266#-KLvrDUHoqhMTFYpeH1o:-KLvrDUHoqhMTFYpeH1p:677194780) ([raw file](https://github.com/servo/servo/blob/0325bf7f073af5635ccbd46a44016ab31814dbac/docs/HACKING_QUICKSTART.md#L48)):*
> ```Markdown
> ```
> 
> The `--`  separates `mach` options from `servo` options. This is not required, but we recommend it. `mach` and `servo` have some options with the same name (`--help`, `--debug`), so the `--` makes it clear where options apply.
> ```

Why?

---

*[docs/HACKING_QUICKSTART.md, line 244 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12266#-KLvrElXnGZ9AOHjVbkv:-KLvrElXnGZ9AOHjVbkw:1356084191) ([raw file](https://github.com/servo/servo/blob/0325bf7f073af5635ccbd46a44016ab31814dbac/docs/HACKING_QUICKSTART.md#L244)):*
> ```Markdown
> ### Updating a test:
> 
> In some cases, extensive tests for the feature you're working on already exist under tests/wpt:
> ```

Why remove "may"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12266#-:-KLvrHnyXX9LNeyU4aAA:453359453)*

**Comment by tshepang** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/HACKING_QUICKSTART.md, line 12 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12266#-KLvr6wn4iN5sADhhOHE:-KLvtfw05ls1UxNGAo5L:-480655556) ([raw file](https://github.com/servo/servo/blob/0325bf7f073af5635ccbd46a44016ab31814dbac/docs/HACKING_QUICKSTART.md#L12)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> "Prerequisites" exists and seems to be more widely-used, no?
</details>
agreed... I thought it was the other way around

---

*[docs/HACKING_QUICKSTART.md, line 48 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12266#-KLvrDUHoqhMTFYpeH1o:-KLvuB7w0FAvNHJep1IM:1043449465) ([raw file](https://github.com/servo/servo/blob/0325bf7f073af5635ccbd46a44016ab31814dbac/docs/HACKING_QUICKSTART.md#L48)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Why?
</details>
One should not continue the sentence like that, so adding *so* makes it flow better.

---

*[docs/HACKING_QUICKSTART.md, line 244 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12266#-KLvrElXnGZ9AOHjVbkv:-KLvuc85Iq1sh0Qxj3Xt:538630932) ([raw file](https://github.com/servo/servo/blob/0325bf7f073af5635ccbd46a44016ab31814dbac/docs/HACKING_QUICKSTART.md#L244)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Why remove "may"?
</details>
You either want to remove *may* or *In some cases**. That is, in this case, *In some cases* implies *sometimes*, same as *may*.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12266)*

**Comment by nox** [comment]
Thanks for your contribution!

-S-awaiting-answer +S-needs-code-changes 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/HACKING_QUICKSTART.md, line 12 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12266#-KLvr6wn4iN5sADhhOHE:-KLvvyUKUiI5Z2dMy_It:-614424673) ([raw file](https://github.com/servo/servo/blob/0325bf7f073af5635ccbd46a44016ab31814dbac/docs/HACKING_QUICKSTART.md#L12)):*
<details><summary><i>Previously, tshepang (Tshepang Lekhonkhobe) wrote…</i></summary>
> agreed... I thought it was the other way around
</details>
r=me once this is reverted. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12266#-:-KLvw-iCpecb5scJhVuz:-595543357)*

**Comment by tshepang** [comment]
r=@nox

**Comment by KiChjang** [comment]
Unfortunately, bors-servo only listens to reviewers.

@bors-servo r=nox

**Comment by tshepang** [comment]
yeah, I thought there may have been something wrong with the syntax I used

**Comment by KiChjang** [comment]
@bors-servo r-

@tshepang Sorry, can I get you to squash your two commits into one before I accept this PR?

**Comment by tshepang** [comment]
Does the UI not allow you to do it? Let me do it from my CLI.

**Comment by jdm** [comment]
@bors-servo: r=nox
The github UI does, but our merge bot does not.

**Comment by Wafflespeanut** [comment]
This is happening again! 

    Traceback (most recent call last):
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/executors/base.py", line 149, in run_test
        result = self.do_test(test)
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/executors/executorservo.py", line 133, in do_test
        self.proc.kill()
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 749, in kill
        self.proc.kill(sig=sig)
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 165, in kill
        send_sig(signal.SIGTERM)
      File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/_virtualenv/lib/python2.7/site-packages/mozprocess/processhandler.py", line 152, in send_sig
        os.killpg(pid, sig)
    OSError: [Errno 1] Operation not permitted

**Comment by KiChjang** [comment]
@bors-servo retry
* #InfraOnFire

**Comment by tshepang** [comment]
@jdm you could squash via Github UI then ask the bot to merge?

**Comment by Wafflespeanut** [comment]
We never use the Github UI to merge commits. We've been relying on bors's auto-merging mechanism for a long time. Also, testing helps us to keep track of the intermittents that pop up every now and then.

**Comment by tshepang** [comment]
@Wafflespeanut understood, but that's not what I said

**Comment by KiChjang** [comment]
@tshepang I only see the "Squash and Merge" option. I don't think GitHub UI provides a way for us to only perform a squash.

**Comment by tshepang** [comment]
oh, alright

**Pull request merged**
