### PR TITLE
Ensure winit windows are cleaned up before TLS disappears.

### PR DESCRIPTION
**Pull request by jdm**
Since the winit update, closing Servo on macOS can lead to a crash. This is because winit panics while trying to clean up the window, since it requires the TLS to be available. Right now this code doesn't run until Servo's TLS is being destroyed. There's no reason to use a thread local value to store the window information, however, and moving it into the App object avoids the panic.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because we don't run non-headless tests on macOS.

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
This seems like a good fix and a nice cleanup.

**Comment by CYBAI** [comment]
build failure on windows, linux and macos 👀 

```
error[E0614]: type `std::collections::HashMap<WindowId, Rc<(dyn WindowPortsMethods + 'static)>>` cannot be dereferenced
   --> ports/winit/app.rs:196:35
    |
196 |         for (_win_id, window) in &*self.windows {
    |                                   ^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0614`.
```

**Comment by jdm** [comment]
@bors-servo r+
Missed committing a local change.

**Pull request merged**
