### PR TITLE
 Use raqote for 2D canvas rendering 

### LINKED ISSUE #23431: Use raqote for 2D canvas rendering
While working on #22957, @jdm mentioned the possiblity to use [https://github.com/jrmuizel/raqote](https://github.com/jrmuizel/raqote) as a canvas rendering backend.
As stated in [https://github.com/servo/servo/issues/22957#issuecomment-493991851](https://github.com/servo/servo/issues/22957#issuecomment-493991851), this issue is for tracking progress of the conversion to raqote.

Remaining missing pieces:
* [x] LinearGradient/RadialGradient (https://docs.rs/raqote/0.6.4/raqote/struct.Gradient.html)
* [x] ColorBurn support (https://github.com/jrmuizel/raqote/issues/81)
* [x] Path::transformed_copy_to_buiilder (https://github.com/jrmuizel/raqote/issues/82)
* [x] Shadows (https://github.com/jrmuizel/raqote/issues/83)
* [x] `snapshot` API (might just be `SourceSurface::Raqote(self.snapshot_data_owned())`
* [x] `ellipse` path API

### PR DESCRIPTION
**Pull request by pylbrecht**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #23431

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24422)

### CODE REVIEW

**Comment by pylbrecht** [comment]
I'm not quite sure if my implementations are correct, so @jrmuizel, maybe you want to take a look at this, as well.

@jdm, I need some general guidance on how to continue after my changes here have been approved. You mentioned some tests that will show what needs to be implemented?

**Comment by pylbrecht** [comment]
I broke `Cargo.lock`.. I'm working on it.

**Comment by jdm** [comment]
Changing [this code](https://github.com/servo/servo/blob/46b048c0a5e25579496b32e629db9009c675e3fe/python/servo/command_base.py#L894-L895) to check for the presence of canvas2d-azure and default to canvas2d-raqote if it's not present will swap the default canvas backend, and then running `./mach test-wpt tests/wpt/web-platform-tests/2dcontext` will show the difference in test results based on the raqote backend.

**Comment by jrmuizel** [comment]
Looks fine to me.

**Pull request merged**
