### PR TITLE
Use lazy_static for HOST_TABLE.

### PR DESCRIPTION
**Pull request by Ms2ger**
This might change behaviour if the file is changed between Servo startup and
the moment HOST_TABLE is first accessed. I don't think we care.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/servo/servo/9988)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Less unsafe! Yay!

**Comment by jdm** [comment]
```
src/main.rs:9:12: 9:19 warning: unused or unknown feature, #[warn(unused_features)] on by default
src/main.rs:9 #![feature(convert)]
                         ^~~~~~~
src/main.rs:47:5: 47:22 error: unused import
src/main.rs:47 use net_traits::hosts;
                   ^~~~~~~~~~~~~~~~~
src/main.rs:5:9: 5:23 note: lint level defined here
src/main.rs:5 #![deny(unused_imports)]
                      ^~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `b2s`.
```

**Comment by Ms2ger** [comment]
Updated.

**Comment by Manishearth** [comment]
```
src/window.rs:27:5: 27:15 error: unresolved import `net_traits::net_error_list::NetError`. Maybe a missing `extern crate net_traits`? [E0432]
src/window.rs:27 use net_traits::net_error_list::NetError;
                     ^~~~~~~~~~
src/window.rs:27:5: 27:15 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to previous error
Could not compile `b2s`.

To learn more, run the comm
```

**Pull request merged**
