### PR TITLE
Remove [PrimaryGlobal]

### LINKED ISSUE #24336: Remove [PrimaryGlobal]
Following https://github.com/heycam/webidl/pull/423 and https://bugzilla.mozilla.org/show_bug.cgi?id=1423562.

### PR DESCRIPTION
**Pull request by saschanaz**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24336 

- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24354)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by saschanaz** [comment]
Seems the server is dead 🤔

**Comment by jdm** [comment]
@saschanaz Nothing can merge until we deal with

**Pull request merged**
