### PR TITLE
Make gonk compile again (not)

### PR DESCRIPTION
**Pull request by Manishearth**
Doesn't actually work (see below), I'm just PRing so that we can figure out why

This also removes the necessity of override submodules. I've used the `.config` to override the openssl build script and link dynamically to libopenssl/libcrypto. Adding `-DTARGET_OS_GONK` to `$CPPFLAGS` will make libtime compile without the duplicate symbol error.

### CODE REVIEW

**Comment by Manishearth** [comment]
Env vars:

```
export GONKDIR=...
export ANDROID_NDK=...
export GONK_PRODUCT=flame
export CC=arm-linux-androideabi-gcc
export ARCH_DIR=arch-arm
export CPPFLAGS="-DANDROID -DTARGET_OS_GONK -DGR_GL_USE_NEW_SHADER_SOURCE_SIGNATURE=1 -isystem $GONKDIR/bionic/libc/$ARCH_DIR/include -isystem $GONKDIR/bionic/libc/include/ -isystem $GONKDIR/bionic/libc/kernel/common -isystem $GONKDIR/bionic/libc/kernel/$ARCH_DIR -isystem $GONKDIR/bionic/libm/include -I$GONKDIR/system -I$GONKDIR/system/core/include -isystem $GONKDIR/bionic -I$GONKDIR/frameworks/native/opengl/include -I$GONKDIR/external/zlib -I$GONKDIR/hardware/libhardware/include/hardware/"
export CXXFLAGS="-O2 -mandroid -fPIC $CPPFLAGS -I$GONKDIR/ndk/sources/cxx-stl/stlport/stlport -I$GONKDIR/ndk/sources/cxx-stl/system/include"
export CFLAGS="-O2 -mandroid -fPIC $CPPFLAGS -I$GONKDIR/ndk/sources/cxx-stl/stlport/stlport -I$GONKDIR/ndk/sources/cxx-stl/system/include"
export ANDROID_TOOLCHAIN=$ANDROID_NDK/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64
export PATH=$GONKDIR/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.7/bin:$PATH
export LDFLAGS="-mandroid -L$GONKDIR/out/target/product/$GONK_PRODUCT/obj/lib -Wl,-rpath-link=$GONKDIR/out/target/product/$GONK_PRODUCT/obj/lib --sysroot=$GONKDIR/out/target/product/$GONK_PRODUCT/obj/"
export OPENSSL_PATH=$GONKDIR/out/target/product/$GONK_PRODUCT/obj/lib
```

Steps:

 - `../../mach cargo build --target=arm-linux-androideabi` from `ports/gonk`
 - At the final link step, copy the rustc invocation (Pass `-v` to cargo to get it), and run `../../mach rustc` with those flags along with `-C link-args="$LDFLAGS -lGLESv2 -L $GONKDIR/backup-flame/system/lib/"`. 
  - Alternatively, `LD_LIBRARY_PATH=$GONKDIR/out/target/product/$GONK_PRODUCT/obj/lib ../../mach rustc $INVOCATION -lGLESv2 -L $GONKDIR/backup-flame/system/lib/ -C link-args="--sysroot=$GONKDIR/out/target/product/$GONK_PRODUCT/obj/"`

I get the stdlib error:

```
note: /home/manishearth/Mozilla/servo/ports/gonk/target/arm-linux-androideabi/deps/libazure-cc187b961189251d.rlib(r-azure-DrawEventRecorder.o):DrawEventRecorder.cpp:function std::ostream::write(char const*, int): error: undefined reference to 'std::uncaught_exception()'
/home/manishearth/Mozilla/servo/ports/gonk/target/arm-linux-androideabi/deps/libazure-cc187b961189251d.rlib(r-azure-RecordedEvent.o):RecordedEvent.cpp:function mozilla::gfx::RecordedPathCreation::RecordToStream(std::ostream&) const: error: undefined reference to 'std::uncaught_exception()'
/home/manishearth/Mozilla/servo/ports/gonk/target/arm-linux-androideabi/deps/libazure-cc187b961189251d.rlib(r-azure-RecordedEvent.o):RecordedEvent.cpp:function mozilla::gfx::RecordedPathCreation::RecordToStream(std::ostream&) const: error: undefined reference to 'std::uncaught_exception()'
/home/manishearth/Mozilla/servo/ports/gonk/target/arm-linux-androideabi/deps/libazure-cc187b961189251d.rlib(r-azure-RecordedEvent.o):RecordedEvent.cpp:function mozilla::gfx::RecordedPathCreation::RecordToStream(std::ostream&) const: error: undefined reference to 'std::uncaught_exception()'
collect2: error: ld returned 1 exit status
```

**Comment by Manishearth** [comment]
@michaelwu, any idea why the build above fails? I'm using the same flags pre-rustup and it works. I also tried cleaning the targetdir.

**Comment by michaelwu** [comment]
I see that when the include path order is bad.

**Comment by larsbergstrom** [comment]
This problem seems to be occurring because either the version of the STL's ostream impl we are including or the compiler flags set during the azure build are emitting calls to `uncaught_exception`, which I believe is not available on this target platform.

**Comment by larsbergstrom** [comment]
Compilation of the azure files appears to be the following line:

```
arm-linux-androideabi-g++ libazure/RecordedEvent.cpp -o /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/libazure/RecordedEvent.o -c -O2 -mandroid -fPIC -I/mnt/more/B2G/ndk/sources/cxx-stl/stlport/stlport -I/mnt/more/B2G/ndk/sources/cxx-stl/system/include -DANDROID -DTARGET_OS_GONK -DGR_GL_USE_NEW_SHADER_SOURCE_SIGNATURE=1 -isystem /mnt/more/B2G/bionic/libc/arch-arm/include -isystem /mnt/more/B2G/bionic/libc/include/ -isystem /mnt/more/B2G/bionic/libc/kernel/common -isystem /mnt/more/B2G/bionic/libc/kernel/arch-arm -isystem /mnt/more/B2G/bionic/libm/include -I/mnt/more/B2G/system -I/mnt/more/B2G/system/core/include -isystem /mnt/more/B2G/bionic -I/mnt/more/B2G/frameworks/native/opengl/include -I/mnt/more/B2G/external/zlib -std=gnu++11 -fPIC -Ilibazure -DMOZ_GFX -DMOZ_WARN_UNUSED_RESULT=""  -O3 -DSK_RELEASE -DGR_RELEASE=1  -I /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/../../freetype-sys-e48ba9ea21b28e35/out/include -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/../../skia-6e4aedc1084a4c11/out/include -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/../../skia-6e4aedc1084a4c11/out/include/core -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/../../skia-6e4aedc1084a4c11/out/include/config -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/../../skia-6e4aedc1084a4c11/out/include/effects -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/../../skia-6e4aedc1084a4c11/out/include/ports -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/../../skia-6e4aedc1084a4c11/out/include/utils -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/../../skia-6e4aedc1084a4c11/out/include/gpu -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/build/azure-2a56d947f1ea3f24/out/../../skia-6e4aedc1084a4c11/out/include/gpu/gl -DUSE_SKIA -DUSE_SKIA_GPU -DMOZ_ENABLE_FREETYPE -DXP_UNIX -DSK_BUILD_FOR_UNIX -DXP_UNIX -DSK_BUILD_FOR_ANDROID -DMOZ_ENABLE_FREETYPE
```

**Comment by larsbergstrom** [comment]
And here's a line from a pre-rustup version (which did link correctly):
```
arm-linux-androideabi-g++ libazure/RecordedEvent.cpp -o /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/libazure/RecordedEvent.o -c -O2 -mandroid -fPIC -I/mnt/more/B2G/ndk/sources/cxx-stl/stlport/stlport -I/mnt/more/B2G/ndk/sources/cxx-stl/system/include -DANDROID -DTARGET_OS_GONK -DGR_GL_USE_NEW_SHADER_SOURCE_SIGNATURE=1 -isystem /mnt/more/B2G/bionic/libc/arch-arm/include -isystem /mnt/more/B2G/bionic/libc/include/ -isystem /mnt/more/B2G/bionic/libc/kernel/common -isystem /mnt/more/B2G/bionic/libc/kernel/arch-arm -isystem /mnt/more/B2G/bionic/libm/include -I/mnt/more/B2G/system -I/mnt/more/B2G/system/core/include -isystem /mnt/more/B2G/bionic -I/mnt/more/B2G/frameworks/native/opengl/include -I/mnt/more/B2G/external/zlib -std=gnu++11 -fPIC -Ilibazure -DMOZ_GFX -DMOZ_WARN_UNUSED_RESULT=""  -O3 -DSK_RELEASE -DGR_RELEASE=1  -I /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/../freetype-sys-e48ba9ea21b28e35/include -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/../skia-6e4aedc1084a4c11/include -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/../skia-6e4aedc1084a4c11/include/core -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/../skia-6e4aedc1084a4c11/include/config -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/../skia-6e4aedc1084a4c11/include/effects -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/../skia-6e4aedc1084a4c11/include/ports -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/../skia-6e4aedc1084a4c11/include/utils -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/../skia-6e4aedc1084a4c11/include/gpu -iquote /home/larsberg/servo/ports/gonk/target/arm-linux-androideabi/native/azure-2a56d947f1ea3f24/../skia-6e4aedc1084a4c11/include/gpu/gl -DUSE_SKIA -DUSE_SKIA_GPU -DMOZ_ENABLE_FREETYPE -DXP_UNIX -DSK_BUILD_FOR_UNIX -DXP_UNIX -DSK_BUILD_FOR_ANDROID -DMOZ_ENABLE_FREETYPE
```

**Comment by larsbergstrom** [comment]
One alternative that at least links is to change the "final link step" extra args to pull in a library with a definition of that function:
```
-C link-args="$LDFLAGS -lGLESv2 -lsupc++ -L $GONK\
DIR/backup-flame/system/lib/ -L$GONKDIR/prebuilts/ndk/9/sources/cxx-stl/gnu-libstdc++/4.6/libs/armeabi/" 
```

**Comment by Manishearth** [comment]
Closing so that Critic can get to the new one

**Pull request closed without merging**
