### PR TITLE
Add pip as a requirement

### PR DESCRIPTION
**Pull request by jdm**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7641)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Closing briefly

**Comment by frewsxcv** [comment]
At least for debian, python-pip-whl is a dependency of python-virtualenv, so there's no reason to specify it explicitly. Not sure about the others. What prompted this?

**Comment by jdm** [comment]
Someone on linux said they installed all prerequisites from the readme and had a mach error.

**Pull request merged**
