### PR TITLE
Update mozangle to use bindgen

### PR DESCRIPTION
**Pull request by sagudev**
Companion PR to https://github.com/servo/mozangle/pull/65

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

### CODE REVIEW

**Comment by sagudev** [comment]
try run: https://github.com/sagudev/servo/actions/runs/6282941900

**Comment by mrobinson** [comment]
Is this ready to be reviewed?

**Comment by sagudev** [comment]
This needs new mozangle release (as it was done in the past), but we could also switch to commit pin like we do for mozjs.

**Comment by mrobinson** [comment]
Version update PR here: https://github.com/servo/mozangle/pull/67

**Review by mrobinson — APPROVED** [review]

**Comment by sagudev** [comment]
try run: https://github.com/sagudev/servo/actions/runs/6504401369

**Pull request merged**
