### PR TITLE
Update offscreen_gl_context. Fixes #12320

### LINKED ISSUE #12320: Shadertoy claims webgl is missing
It checks using
```js
function piCreateGlContext( cv, useAlpha, useDepth, usePreserveBuffer )
{
    var opts = { alpha: useAlpha, depth: useDepth, stencil: false, premultipliedAlpha: false, antialias: false, preserveDrawingBuffer: usePreserveBuffer };
	var gl = cv.getContext( "webgl", opts);
    if( gl == null)
        gl = cv.getContext("experimental-webgl", opts );
    return gl;
}
```
and calling `piCreateGlContext(this.mCanvas, false, false, true)`.

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12320 (github issue number if applicable).

- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13085)

### CODE REVIEW

**Comment by emilio** [comment]
r? @jdm (or anyone really)

@bors-servo: try

(just in case this fixes any WebGL crash).

**Comment by nox** [comment]
@emilio Seems like you did this PR pre-cargoup, thus the metadata bits weren't properly updated. Just rebase and do `./mach cargo-update -p offscreen_gl_context` and it should be ok.

**Pull request merged**
