### PR TITLE
Mechanism to allow Servo to prompt the user

### LINKED ISSUE #23376: Permissions prompt support in Servo
Currently Servo cannot trigger permissions prompts. This is going to be necessary to be able to expose `getUserMedia()` and some of the XR stuff.

This will likely be somewhere in the embedder API.

Ideally, for `getUserMedia()` we can have a "pick your device" menu as well (may need a separate API)

cc @paulrouget

### PR DESCRIPTION
**Pull request by paulrouget**
This blocks the embedder thread (compositor thread). Not ideal. I don't think it's too much work to only block script, I'll do that in a follow up bug.

Fix #23376 

@Manishearth we have a few new APIs. Hopefully this will cover your needs. A thing I haven't implemented yet is a way to ask the user to pick from a list. Let me know if it's something you'll need.

### CODE REVIEW

**Review by asajeffrey — COMMENTED** [review]
Small nit, otherwise the changes to the embedder LGTM. I'll leave the HL code up to @Manishearth.

**Comment by paulrouget** [comment]
Added comments and enum instead of bool.

**Comment by jdm** [comment]
@Manishearth Review ping.

**Review by Manishearth — APPROVED** [review]
looks good to me!

(sorry for the delay, was waiting on some XR permissions discussions to happen)

**Comment by jdm** [comment]
Shoot, we should have merged this :(

**Comment by pshaughn** [comment]
It looks like this is adding more tinyfiledialogs calls; if any of them can come from strings written by page authors, send them through the escaper.

**Comment by paulrouget** [comment]
I’ll get back to that once I figured #25683

**Comment by paulrouget** [comment]
I’ve put together the 3 prompt/devtools related PR (this one + https://github.com/servo/servo/pull/25266  + https://github.com/servo/servo/pull/25307).

**Review by Manishearth — APPROVED** [review]

**Comment by CYBAI** [comment]
In Android builds:

```
error[E0407]: method `on_alert` is not a member of trait `HostTrait`
   --> ports/libsimpleservo/jniapi/src/lib.rs:397:5
    |
397 | /     fn on_alert(&self, message: String) {
398 | |         debug!("on_alert");
399 | |         let env = self.jvm.get_env().unwrap();
400 | |         let s = match new_string(&env, &message) {
...   |
411 | |         .unwrap();
412 | |     }
    | |_____^ not a member of trait `HostTrait`
error[E0046]: not all trait items implemented, missing: `prompt_alert`, `prompt_yes_no`, `prompt_ok_cancel`, `prompt_input`
   --> ports/libsimpleservo/jniapi/src/lib.rs:382:1
    |
382 | impl HostTrait for HostCallbacks {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `prompt_alert`, `prompt_yes_no`, `prompt_ok_cancel`, `prompt_input` in implementation
    |
    = help: implement the missing item: `fn prompt_alert(&self, _: std::string::String, _: bool) { unimplemented!() }`
    = help: implement the missing item: `fn prompt_yes_no(&self, _: std::string::String, _: bool) -> embedder_traits::PromptResult { unimplemented!() }`
    = help: implement the missing item: `fn prompt_ok_cancel(&self, _: std::string::String, _: bool) -> embedder_traits::PromptResult { unimplemented!() }`
    = help: implement the missing item: `fn prompt_input(&self, _: std::string::String, _: std::string::String, _: bool) -> std::option::Option<std::string::String> { unimplemented!() }`
error: aborting due to 2 previous errors
```

```
  ▶ OK [expected TIMEOUT] /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_block_modals-3.html
  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_block_modals-3.html:
  │ FAIL [expected TIMEOUT] Frames without `allow-modals` should not be able to open modal dialogs
  │   → assert_equals: Call to open modal dialog did not return expected value expected (object) null but got (string) "DEFAULT VALUE"
  │ 
  │ runTest/</iframe.onload</<@http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/support/iframe_sandbox_block_modals.js:11:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:2065:32
  ▶ OK [expected TIMEOUT] /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_block_modals-2.html
  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-iframe-element/iframe_sandbox_block_modals-2.html:
  │ FAIL [expected TIMEOUT] Frames without `allow-modals` should not be able to open modal dialogs
  │   → assert_equals: Call to open modal dialog did not return expected value expected false but got true
  │ 
  │ runTest/</iframe.onload</<@http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/support/iframe_sandbox_block_modals.js:11:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:2065:32
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?include=(Document|Window):
  └ PASS [expected FAIL] Window interface: operation confirm(DOMString)
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?include=(Document|Window):
  └ PASS [expected FAIL] Window interface: operation prompt(DOMString, DOMString)
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?include=(Document|Window):
  └ PASS [expected FAIL] Window interface: window must inherit property "confirm(DOMString)" with the proper type
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?include=(Document|Window):
  └ PASS [expected FAIL] Window interface: calling confirm(DOMString) on window with too few arguments must throw TypeError
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?include=(Document|Window):
  └ PASS [expected FAIL] Window interface: window must inherit property "prompt(DOMString, DOMString)" with the proper type
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?include=(Document|Window):
  └ PASS [expected FAIL] Window interface: calling prompt(DOMString, DOMString) on window with too few arguments must throw TypeError
  ▶ Unexpected subtest result in /html/browsers/the-window-object/window-properties.https.html:
  └ PASS [expected FAIL] Window method: confirm
  ▶ Unexpected subtest result in /html/browsers/the-window-object/window-properties.https.html:
  └ PASS [expected FAIL] Window method: prompt
```

**Comment by paulrouget** [comment]
Fixed mlservo and android implementations.

@bors-servo r=manishearth

**Comment by CYBAI** [comment]
```
clang-format version 8.0.1 (tags/RELEASE_801/final)
support/hololens/ServoApp/ServoControl/Servo.h is not formatted correctly.
support/hololens/ServoApp/ServoControl/ServoControl.cpp is not formatted correctly.
support/hololens/ServoApp/ServoControl/ServoControl.h is not formatted correctly.
Run `./mach fmt` to fix the formatting
```

**Comment by paulrouget** [comment]
Erf, I missed the failed tests.

@bors-servo r-

**Comment by paulrouget** [comment]
Didn’t try to build locally:

@bors-servo try=magicleap

**Pull request merged**
