### PR TITLE
Add instructions to update create.rs when adding new DOM interfaces

### PR DESCRIPTION
**Pull request by KiChjang**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9297)

### CODE REVIEW

**Comment by ecoal95** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/mod.rs, line 190 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9297#-K7wFU3-NugI1SJmjJKt:-K7wFU3-NugI1SJmjJKu:-140872226) ([raw file](https://github.com/servo/servo/blob/191268ad1747f26e6572cbcceaba398519ecc498/components/script/dom/mod.rs#L190)):*
Please clarify that this is only needed when adding a new `HTMLElement`, no other kind of interfaces.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9297)*

**Comment by KiChjang** [comment]
Done.

**Comment by KiChjang** [comment]
@bors-servo retry
* #9092

**Pull request merged**
