### PR TITLE
Cleanup lint special cases, refactor flake8 linting 

### PR DESCRIPTION
**Pull request by frewsxcv**
Currently, there are a few linting functions that only run on certain
filetypes (determined by the file extension). Prior to this commit, the
special cases were handled in a parent function with a conditional. This
commit changes the system so each linting function gets passed a
filename so the function can determine whether it should run or not
based on the file extension.

I also refactored flake8 linting slightly. From what I've read so far of
the code, flake8 itself will only print the results directly to stdout
(though the linter would report the quantity of errors detected).
Prior to this commit, we would let flake8 print directly to stdout and
just determine if there were >0 errors reported. This commit (sort of
hackily) temporarily captures stdout when we call flake8 so we can do
what we want with the output, allowing us to `yield` the line number
and message like we do with the other linting functions.

In my opinion, both of these changes isolate specific behaviors/checks
into their respective linting functions instead of having them handled
at a more global level.

In addition to the changes above:
- The whitespace linter now runs on WebIDL and TOML files
- The license header linter now runs on WebIDL files

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6777)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+

Thanks for the patch!
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 15 of 15 files at r3, 60 of 60 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6777)

**Comment by jdm** [comment]
```
WebIDL.WebIDLError: error: invalid syntax, /home/servo/buildbot/slave/gonk/build/components/script/dom/webidls/CanvasRenderingContext2D.webidl line 183:45
                               double radiusX, double radiusY, double rotation);
                                             ^
```

**Comment by frewsxcv** [comment]
Ah, wrapped some commented out lines but didn't retain the comment on the new lines. It should be fixed now

**Comment by frewsxcv** [comment]
This could use a retry

**Comment by jdm** [comment]
@bors-servo: retry
* #6656 and #6780

**Pull request merged**
