### PR TITLE
Fix unrooted_must_root lint to handle arguments/return types properly

### PR DESCRIPTION
**Pull request by Manishearth**
r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8030)

### CODE REVIEW

**Comment by nox** [comment]
```
./components/plugins/utils.rs:12: use statement is not in alphabetical order
	expected: syntax::codemap::{ExpnFormat, Span}
	found: syntax::ptr::P
./components/plugins/utils.rs:13: use statement is not in alphabetical order
	expected: syntax::ptr::P
	found: syntax::codemap::{ExpnFormat, Span}
```

**Comment by frewsxcv** [comment]
Reopened because the workers were stuck

**Pull request merged**
