### PR TITLE
Switch from let to var in mozilla wpt tests

### PR DESCRIPTION
**Pull request by michaelwu**
let can't be used without specifying a newer JS version at the moment.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6339)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- tests/wpt/mozilla/tests/mozilla/document_body.html @ r1
- tests/wpt/mozilla/tests/mozilla/document_getElementById.html @ r1
- tests/wpt/mozilla/tests/mozilla/document_getElementsByName.html @ r1
- tests/wpt/mozilla/tests/mozilla/document_head.html @ r1
- tests/wpt/mozilla/tests/mozilla/DOMParser.html @ r1
- tests/wpt/mozilla/tests/mozilla/element_attribute.html @ r1
- tests/wpt/mozilla/tests/mozilla/element_classList.html @ r1
- tests/wpt/mozilla/tests/mozilla/element_className.html @ r1
- tests/wpt/mozilla/tests/mozilla/element_matches.html @ r1
- tests/wpt/mozilla/tests/mozilla/Event.html @ r1
- tests/wpt/mozilla/tests/mozilla/htmlcollection.html @ r1
- tests/wpt/mozilla/tests/mozilla/MouseEvent.html @ r1
- tests/wpt/mozilla/tests/mozilla/parentNode_querySelector.html @ r1
- tests/wpt/mozilla/tests/mozilla/parentNode_querySelectorAll.html @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6339)

**Comment by larsbergstrom** [comment]
```
Summary
=======

Ran 202781 tests (2443 parents, 200338 subtests)
Expected results: 202709
Unexpected results: 4 (TIMEOUT: 4)
Skipped: 68

Unexpected Results
==================

/websockets/constructor/005.html
--------------------------------
TIMEOUT [Parent]
/websockets/constructor/004.html
--------------------------------
TIMEOUT [Parent]
/websockets/constructor/007.html
--------------------------------
TIMEOUT [Parent]
/websockets/constructor/008.html
--------------------------------
TIMEOUT [Parent]
18:58.69 LOG: MainThread INFO Closing logging queue
18:58.70 LOG: MainThread INFO queue closed
program finished with exit code 1
```

**Comment by pcwalton** [comment]
var is the new let

**Comment by larsbergstrom** [comment]
@jgraham @ms2ger any idea on these failures?

**Comment by jgraham** [comment]
It's nothing that this patch touched afaict. I suspect something happened that got the WebSockets server stuck for a bit so the tests running at that time timed out, or something.

**Comment by Ms2ger** [comment]
@bors-servo: retry
* #6266

**Pull request merged**
