### PR TITLE
Fix unexpected overflow with overflow: hidden set.

### LINKED ISSUE #9719: Unexpected overflow
It should not be possible to scroll this page, but in Servo, it's possible to scroll vertically and horizontally.

```html
<div style="position: absolute; left: 0px; bottom: 0px; width: 100%; height: 48px; overflow: hidden; background: red;">
  <!-- vertical overflow -->
  <span style="display: inline-block; height: 32px; width: 32px; margin: 20px;"></span>
  <!-- horizontal overflow -->
  <div style="width: 40px; height: 40px; position: absolute; right: -40px;"></div>
</div>
```

x6xyrrvxok

This makes it impossible to scroll webcontent in browser.html.

### PR DESCRIPTION
**Pull request by glennw**
Fixes #9719.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9841)

### CODE REVIEW

**Comment by ecoal95** [comment]
```
PASS [expected FAIL] /css21_dev/html4/quotes-036.htm
```

**Comment by jdm** [comment]
Was it impossible to write a reftests?

**Comment by glennw** [comment]
@jdm Yep, it relies on mouse scroll.

**Pull request merged**
