### PR TITLE
Upgrade setuptools.

### LINKED ISSUE #28704: macOS CI is broken
It started within the past day, and manifests as the mozjs build reporting that the setuptools python package is not found. We should see if there were any GitHub environment changes made.

### PR DESCRIPTION
**Pull request by jdm**
Fixes #28704.

### CODE REVIEW

**Comment by CYBAI** [comment]
@bors-servo ping

- Looks like the last CI run is all green though 👀

**Comment by jdm** [comment]
I've usually put it down to missed webhooks, but it's annoying to see it happening this often.

**Comment by CYBAI** [comment]
@bors-servo retry

- #28713

**Comment by CYBAI** [comment]
@bors-servo retry

- #28714

**Comment by CYBAI** [comment]
@bors-servo retry

- #28715

**Comment by jdm** [comment]
Something is weird about the webhook. I'll see if reopening the PR helps.

**Comment by CYBAI** [comment]
hmm, webhook seems weird to this PR :/

**Comment by CYBAI** [comment]
hmmm, I just noticed that the CI jobs will be run for both #28710 and #28592 while #28592 is merged at 22 days ago though... I'm wondering, is it possible that bors trigger both of them and pick the wrong results so that we cannot merge this PR? 🤔 

(See https://github.com/servo/servo/actions/workflows/main.yml)

image

**Comment by jdm** [comment]
That happens because homu first pushes the latest master revision to the auto branch, then immediately pushes the merge commit after it. This causes two jobs to start every time, sadly.

**Comment by jdm** [comment]
I have a suspicion that it's the taskcluster integration that hasn't been completely disconnected yet.

**Pull request merged**
