### PR TITLE
style: Inline RestyleData.

### PR DESCRIPTION
**Pull request by emilio**
Bug: 1368236
MozReview-Commit-ID: 49s3SO0PMHf

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17348)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0599]: no method named `ensure_restyle` found for type `atomic_refcell::AtomicRefMut<'_, style::data::ElementData>` in the current scope
    --> C:\projects\servo\components\layout_thread\lib.rs:1119:35
     |
1119 |                                 d.ensure_restyle().hint.insert(RestyleHint::restyle_subtree());
     |                                   ^^^^^^^^^^^^^^
error[E0599]: no method named `ensure_restyle` found for type `atomic_refcell::AtomicRefMut<'_, style::data::ElementData>` in the current scope
    --> C:\projects\servo\components\layout_thread\lib.rs:1155:23
     |
1155 |                     d.ensure_restyle().hint.insert(RestyleHint::restyle_subtree());
     |                       ^^^^^^^^^^^^^^
error[E0599]: no method named `ensure_restyle` found for type `atomic_refcell::AtomicRefMut<'_, style::data::ElementData>` in the current scope
    --> C:\projects\servo\components\layout_thread\lib.rs:1200:47
     |
1200 |             let mut restyle_data = style_data.ensure_restyle();
     |                                               ^^^^^^^^^^^^^^
error: aborting due to previous error(s)
error: Could not compile `layout_thread`.
Caused by:

```
@bors-servo: r-

**Comment by emilio** [comment]
Eek, thanks... I stopped cargo-check after compiling layout, but that was not enough :)

@bors-servo r=bholley

**Pull request merged**
