### PR TITLE
Fix ServoDriver is_alive method

### LINKED ISSUE #22664: Can't use --debugger with servodriver WPT harness
```
godot:servo jdm$ ./mach test-wpt --product servodriver --headless tests/wpt/mozilla/tests/css/img_simple.html --debugger
 0:02.96 LOG: MainThread INFO Using 1 client processes
 0:03.46 LOG: MainThread INFO Starting http server on 127.0.0.1:8000
 0:03.47 LOG: MainThread INFO Starting https server on 127.0.0.1:8443
 0:03.47 LOG: MainThread INFO Starting http server on 127.0.0.1:8001
 0:03.95 SUITE_START: MainThread 1
 0:03.95 LOG: MainThread INFO Running reftest tests
 0:03.96 LOG: TestRunnerManager-1 INFO Starting runner
(lldb) target create "/Users/jdm/src/servo/target/debug/servo"
 0:04.99 LOG: TestRunnerManager-1 ERROR Traceback (most recent call last):
  File "/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 363, in run
    new_state = self.wait_event()
  File "/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 408, in wait_event
    self.browser.started and not self.browser.is_alive()):
  File "/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 240, in is_alive
    return self.browser.is_alive()
  File "/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/browsers/servodriver.py", line 169, in is_alive
    if self.runner:
AttributeError: 'ServoWebDriverBrowser' object has no attribute 'runner'
```

### PR DESCRIPTION
**Pull request by shanavas786**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22664 

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it fixes test runner

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22673)

### CODE REVIEW

**Comment by CYBAI** [comment]
```
$ ./mach test-tidy --no-progress --all
 0:13.10 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/mozilla/meta/MANIFEST.json
 0:13.27 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/metadata/MANIFEST.json
 0:17.70 WARNING Manifest /home/travis/build/servo/servo/tests/wpt/metadata/MANIFEST.json contains correct tests but file hashes changed.
 0:17.82 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/webgl/meta/MANIFEST.json
 0:18.04 ERROR Manifest /home/travis/build/servo/servo/tests/wpt/webgl/meta/MANIFEST.json is outdated, use |./mach update-manifest| to fix.
```

**Comment by CYBAI** [comment]
@shanavas786 Would you mind to squash these 2 commits into one :)?

**Comment by shanavas786** [comment]
@CYBAI done :)

**Pull request merged**
