### PR TITLE
Remove layout_2020::display_list, use WebRender display lists instead

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24153)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r-
```
[0m[1m[38;5;9merror[E0308][0m[0m[1m: mismatched types[0m
[0m  [0m[0m[1m[38;5;12m--> [0m[0mtests/unit/metrics/paint_time.rs:69:9[0m
[0m   [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m69[0m[0m [0m[0m[1m[38;5;12m| [0m[0m        &*display_list,[0m
[0m   [0m[0m[1m[38;5;12m| [0m[0m        [0m[0m[1m[38;5;9m^^^^^^^^^^^^^^[0m[0m [0m[0m[1m[38;5;9mexpected bool, found reference[0m
[0m   [0m[0m[1m[38;5;12m|[0m
[0m   [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: expected type `[0m[0m[1mbool[0m[0m`[0m
[0m              found type `[0m[0m[1m&layout::display_list::items::DisplayList[0m[0m`[0m
```

**Comment by SimonSapin** [comment]
Made the unit test to pass, though it’s arguably less meaningful now.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Pull request merged**
