### PR TITLE
[wip] layout: Use a magic pseudo-element for text styles.

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes

This is an example that partially addresses
https://github.com/servo/servo/issues/8570, hoping that other people will
complete it based on an example like this.

Actually, we do approximately the same amount of work now, but we could mark
this pseudos as "eagerly" cascaded, and do less work in layout, at the expense
of (possibly) wasted work in style.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12496)

### CODE REVIEW

**Comment by stshine** [comment]
Good, I'm about to ask for this :laughing:

**Comment by pcwalton** [comment]
This looks good when rebased and when tests are updated. Thanks!

**Comment by jdm** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
