### PR TITLE
Custom properties, take 2

### PR DESCRIPTION
**Pull request by SimonSapin**
Support `var()` in shorthand properties, and fix various bugs.

r? @pcwalton

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7555)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Rebased.

**Comment by SimonSapin** [comment]
Of the remaining failing css-variables tests:

* Those with `supports` in the name fail because we don’t implement `@support`
* https://github.com/w3c/csswg-test/pull/853 should fix those with `font-face` in the name
* `test_variable_legal_values.htm` fails because we don’t support stylesheet updates. This PR adds a copy that uses a `style` attribute instead and passes.

**Comment by SimonSapin** [comment]
Depends on https://github.com/servo/rust-cssparser/pull/89

**Comment by mbrubeck** [comment]
Reviewed 4 of 4 files at r1, 10 of 10 files at r2, 8 of 8 files at r3, 2 of 2 files at r4.
Review status: 15 of 38 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7555)

**Comment by mbrubeck** [comment]
Reviewed 2 of 2 files at r5, 4 of 4 files at r6, 2 of 2 files at r7, 7 of 7 files at r8.
Review status: 25 of 38 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/wpt/mozilla/tests/css/test_variable_legal_values.html, line 1 \[r7\]](https://reviewable.io:443/reviews/servo/servo/7555#-JzMdlHFJB2U6s5SNhGb)** ([raw file](https://github.com/servo/servo/blob/25bb0fb32a02a363c3b398ce2805a756a0882de5/tests/wpt/mozilla/tests/css/test_variable_legal_values.html#L1)):</sup>
Should we change this filename to be different from the original?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7555)

**Comment by SimonSapin** [comment]
Review status: 25 of 38 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/wpt/mozilla/tests/css/test_variable_legal_values.html, line 1 \[r7\]](https://reviewable.io:443/reviews/servo/servo/7555#-JzMdlHFJB2U6s5SNhGb)** ([raw file](https://github.com/servo/servo/blob/25bb0fb32a02a363c3b398ce2805a756a0882de5/tests/wpt/mozilla/tests/css/test_variable_legal_values.html#L1)):</sup>
I don’t know. It does it differently, but it still tests legal values for variables.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7555)

**Comment by mbrubeck** [comment]
Reviewed 6 of 6 files at r9, 9 of 9 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/wpt/mozilla/tests/css/test_variable_serialization_specified.html, line 44 \[r10\]](https://reviewable.io:443/reviews/servo/servo/7555#-JzOsKUqH7j5I7WHoWCc)** ([raw file](https://github.com/servo/servo/blob/8cfdabb4f0910a577989fc789e014ac477ac0ad7/tests/wpt/mozilla/tests/css/test_variable_serialization_specified.html#L44)):</sup>
Is this serialization required by the spec, or is it implementation-defined?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7555)

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/wpt/mozilla/tests/css/test_variable_serialization_specified.html, line 44 \[r10\]](https://reviewable.io:443/reviews/servo/servo/7555#-JzOsKUqH7j5I7WHoWCc)** ([raw file](https://github.com/servo/servo/blob/8cfdabb4f0910a577989fc789e014ac477ac0ad7/tests/wpt/mozilla/tests/css/test_variable_serialization_specified.html#L44)):</sup>
https://drafts.csswg.org/css2/syndata.html#unexpected-eof says “User agents must close all open constructs […] at the end of the style sheet.” (In CSS Syntax Level 3 this is not as succinct, but it’s a consequence of the *consume a token* and *consume a component value* algorithms.)

In this example:

```html
<p style="background: var(--b) green; --a: url(foo.png); --b: var(--a /* unclosed comment">
```

… you want `green` to be parsed as a color after the `foo.png` image, not be part of the comment or the var function.

But yeah, the css-variables spec could probably specify this a bit more.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7555)

**Comment by mbrubeck** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/wpt/mozilla/tests/css/test_variable_serialization_specified.html, line 44 \[r10\]](https://reviewable.io:443/reviews/servo/servo/7555#-JzOsKUqH7j5I7WHoWCc)** ([raw file](https://github.com/servo/servo/blob/8cfdabb4f0910a577989fc789e014ac477ac0ad7/tests/wpt/mozilla/tests/css/test_variable_serialization_specified.html#L44)):</sup>
I was actually curious about the comment serialization, since [CSS Syntax](https://drafts.csswg.org/css-syntax/#serialization) says that “the serialization of comments an whitespace is not defined.”

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7555)

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/wpt/mozilla/tests/css/test_variable_serialization_specified.html, line 44 \[r10\]](https://reviewable.io:443/reviews/servo/servo/7555#-JzOsKUqH7j5I7WHoWCc)** ([raw file](https://github.com/servo/servo/blob/8cfdabb4f0910a577989fc789e014ac477ac0ad7/tests/wpt/mozilla/tests/css/test_variable_serialization_specified.html#L44)):</sup>
Alright, I’ll add a comment like this:
> NOTE: CSS does not define the exact serialization of whitespace and comments (see https://drafts.csswg.org/css-syntax/#serialization) so an implementation could fail this test but still be conforming.

How does this look?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7555)

**Comment by mbrubeck** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7555)

**Comment by mbrubeck** [comment]
Reviewed 2 of 2 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7555)

**Pull request merged**
