### PR TITLE
Start using on_refresh_driver_tick #5681

### PR DESCRIPTION
**Pull request by gurobokum**
RequestAnimationFrame
[Task](https://github.com/servo/servo/issues/5681)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5753)

### CODE REVIEW

**Comment by jdm** [comment]
Does this cause any test result changes in test-wpt?

---

Reviewed files:
- components/devtools/actors/framerate.rs @ r1
- components/devtools/actors/timeline.rs @ r1
- components/devtools_traits/lib.rs @ r1
- components/layout/animation.rs @ r1
- components/script/dom/bindings/trace.rs @ r1
- components/script/dom/document.rs @ r1
- components/script/dom/webidls/Window.webidl @ r1
- components/script/dom/window.rs @ r1
- components/script/lib.rs @ r1
- components/script/script_task.rs @ r1
- components/script_traits/lib.rs @ r1
- tests/html/test_request_animation_frame.html @ r1

---

<sup>**[components/devtools/actors/framerate.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRHvAJh4hQTJ2l4Vxe)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/devtools/actors/framerate.rs#L81)):</sup>
Instead of creating a separate thread here (and for the regular timeline ticks as well), what if we sent a message to the main devtools event loop (via ScriptDevtoolControlMsg) with the actor name and the timestamp?

---

<sup>**[components/script/dom/document.rs, line 86 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMTQXiYtHl2TXv55p)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L86)):</sup>
std::iter::FromIterator

---

<sup>**[components/script/dom/document.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMXCgobWBUXVFVJ6P)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L135)):</sup>
No need for webappapis.html

---

<sup>**[components/script/dom/document.rs, line 137 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMW0khFpqNSjiq4LD)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L137)):</sup>
Cell

---

<sup>**[components/script/dom/document.rs, line 138 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMZ7FYdXvkIa6D5iC)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L138)):</sup>
No need for webappapis.html

---

<sup>**[components/script/dom/document.rs, line 774 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRNDJBew-ae1hRHERj)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L774)):</sup>
This isn't quite right - animations are driven by the compositor, so we should use that system. In particular, process_new_animations in animation.rs shows how we should notify the constellation that animations exist. We will need to differentiate between "there are active animations" and "the animation callback list is not empty" so that we continue receiving animation ticks even if a CSS animation finishes but there are still animation frame callbacks.

---

<sup>**[components/script/dom/document.rs, line 783 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMwPkfc3_iG8TJspW)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L783)):</sup>
No need for webappapis.html

---

<sup>**[components/script/dom/document.rs, line 784 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMsO-f1wULRxyCDhq)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L784)):</sup>
Use http://w3c.github.io/animation-timing/ instead of the TR/ version.

---

<sup>**[components/script/dom/document.rs, line 785 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRO3a7xOdAiqUyeGcq)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L785)):</sup>
invoke_animation_callbacks

---

<sup>**[components/script/dom/document.rs, line 786 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRO9SrcmIzgvagnGwh)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L786)):</sup>
This will cause a panic if a callback calls requestAnimationFrame again, I'm pretty sure.

---

<sup>**[components/script/dom/webidls/Window.webidl, line 145 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRONULc0KINV_FWxVd)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/webidls/Window.webidl#L145)):</sup>
http://w3c.github.io/animation-timing/#Window-interface-extensions

---

<sup>**[components/script/dom/window.rs, line 460 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnROfPxfqXyw09Ynuoj)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/window.rs#L460)):</sup>
No need for webappapis.html

---

<sup>**[components/script/dom/window.rs, line 465 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnROmaWuIHSWbKiC6cM)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/window.rs#L465)):</sup>
The spec says that any exceptions should be suppressed; let's use Report right now instead and add a TODO.

---

<sup>**[components/script/dom/window.rs, line 471 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnROwjLCK8QKv8grcOC)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/window.rs#L471)):</sup>
No need for webappapis.html

---

<sup>**[components/script/dom/window.rs, line 886 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRP-V3UQKHwWr4CPFg)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/window.rs#L886)):</sup>
Unintentional change?

---

<sup>**[components/script/script_task.rs, line 917 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRPCxmcBHr2FC6oP9p)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/script_task.rs#L917)):</sup>
Move this into the devtools module like the other handlers.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by jdm** [comment]
This is exciting! The main areas for improvement I can see are the integration with the existing animation ticking system and the use of threads for the devtools actor loops.

**Comment by JIoJIaJIu** [comment]
> Does this cause any test result changes in test-wpt?

No, it should not

---





<sup>**[components/devtools/actors/framerate.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRHvAJh4hQTJ2l4Vxe)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/devtools/actors/framerate.rs#L81)):</sup>
ScriptDevtoolControlMsg does not used anywhere, is it legacy? I refactored with DevtoolsControlMsg

---

<sup>**[components/script/dom/document.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMXCgobWBUXVFVJ6P)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L135)):</sup>
Why is better do not use webappis? I thinked that whatwg specification is general

---

<sup>**[components/script/dom/window.rs, line 886 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRP-V3UQKHwWr4CPFg)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/window.rs#L886)):</sup>
My bad)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by jdm** [comment]
Looks like we should enable the tests in http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/animation-timing/ :) Add the dir to http://mxr.mozilla.org/servo/source/tests/wpt/include.ini ?

**Comment by jdm** [comment]
<sup>**[components/devtools/actors/framerate.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRHvAJh4hQTJ2l4Vxe)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/devtools/actors/framerate.rs#L81)):</sup>
Yes, I'll file an issue about removing it.

---

<sup>**[components/script/dom/document.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMXCgobWBUXVFVJ6P)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L135)):</sup>
Oh, because the page.html links are not stable; only the #section-title links are stable, so `./mach test-tidy` will complain about specific page links in the comments.

---

<sup>**[components/script/dom/window.rs, line 886 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRP-V3UQKHwWr4CPFg)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/window.rs#L886)):</sup>
(I accidentally marked this issue resolved, so ignore this comment I am making right now)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by JIoJIaJIu** [comment]
Nice, thank you, I'll do it

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by JIoJIaJIu** [comment]
One test failed cause document.hidden is undefined, can I exclude someway this one?
```bash
 0:03.15 TEST_END: Thread-TestrunnerManager-1 Harness OK. Subtests passed 0/1. Unexpected 1
requestAnimationFrame callback is invoked at least once before the timeout
--------------------------------------------------------------------------
Expected PASS, got FAIL
assert_false: document.hidden must be exist and be false to run this test properly expected false got undefined
@http://localhost:8000/animation-timing/callback-invoked.html:4
Test.step@http://localhost:8000/resources/testharness.js:1295
@http://localhost:8000/animation-timing/callback-invoked.html:3
Test.step@http://localhost:8000/resources/testharness.js:1295
async_test@http://localhost:8000/resources/testharness.js:445
@http://localhost:8000/animation-timing/callback-invoked.html:9
```

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by jdm** [comment]
You can just add an expected failure in http://mxr.mozilla.org/servo/source/tests/wpt/metadata/ . See http://mxr.mozilla.org/servo/source/tests/wpt/metadata/XMLHttpRequest/data-uri.htm.ini for an example.

**Comment by JIoJIaJIu** [comment]
It's without tests, just for review, I'll add tests as soon as I can

**Comment by jdm** [comment]
Reviewed files:
- components/compositing/compositor.rs @ r2
- components/compositing/compositor_task.rs @ r2
- components/compositing/constellation.rs @ r2
- components/devtools/actors/framerate.rs @ r2
- components/devtools/actors/timeline.rs @ r2
- components/devtools/lib.rs @ r2
- components/devtools_traits/lib.rs @ r2
- components/layout/animation.rs @ r2
- components/msg/constellation_msg.rs @ r2
- components/script/devtools.rs @ r2
- components/script/dom/bindings/trace.rs @ r2
- components/script/dom/document.rs @ r2
- components/script/dom/webidls/Window.webidl @ r2
- components/script/dom/window.rs @ r2
- components/script/script_task.rs @ r2
- components/script_traits/lib.rs @ r2

---

<sup>**[components/compositing/compositor.rs, line 428 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbhHeTrHkM_ZhMwvgZ)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/compositing/compositor.rs#L428)):</sup>
This clone shouldn't be necessary.

---

<sup>**[components/compositing/compositor.rs, line 428 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-Jnbif_n2w3mfH2MvQtk)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/compositing/compositor.rs#L428)):</sup>
I don't think this handles pages that use requestAnimationCallback as well as CSS animations at the same time. When the animations finish the page will report AnimationState::Stopped, right? I think the pipeline should have two booleans, and AnimiationState should have four states - NoAnimationsPresent, AnimationsPresent, AnimationCallbacksPresent, and NoAnimationCallbacksPresent. This method can toggle the booleans based on the states received. Does that make sense?

---

<sup>**[components/devtools/actors/framerate.rs, line 83 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbfGw3LausaDH7CqyA)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/actors/framerate.rs#L83)):</sup>
fabric?

---

<sup>**[components/devtools/actors/framerate.rs, line 83 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbfMjl6hqwE8Oa1U52)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/actors/framerate.rs#L83)):</sup>
Why a Box?

---

<sup>**[components/devtools/actors/framerate.rs, line 98 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbfUvAmuYYNBj_xe6b)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/actors/framerate.rs#L98)):</sup>
This looks like it will never use the update value stored in the actor.

---

<sup>**[components/devtools/lib.rs, line 271 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbgOEubgkJQQfKLyOh)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/lib.rs#L271)):</sup>
Why is this block necessary? Can't we just use a different name instead of `sender`?

---

<sup>**[components/msg/constellation_msg.rs, line 236 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbhCnBJxe1ucROfVQH)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/msg/constellation_msg.rs#L236)):</sup>
This can be Copy instead of Clone.

---

<sup>**[components/script/dom/document.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMXCgobWBUXVFVJ6P)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L135)):</sup>
The spec link is useful, it should just be https://html.spec.whatwg.org/multipage/#animation-frame-callback-identifier

---

<sup>**[components/script/dom/document.rs, line 138 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMZ7FYdXvkIa6D5iC)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L138)):</sup>
Same here; spec links are good :)

---

<sup>**[components/script/dom/document.rs, line 783 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnRMwPkfc3_iG8TJspW)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/document.rs#L783)):</sup>
This link can stay, just without webappapis.html :)

---

<sup>**[components/script/dom/window.rs, line 471 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnROwjLCK8QKv8grcOC)** ([raw file](https://github.com/servo/servo/blob/d24c73afd7167a2a2dbeb27c1d7470fe65439f37/components/script/dom/window.rs#L471)):</sup>
This can stay, just without webappapis.html :)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by JIoJIaJIu** [comment]
Execuse me for long silence

---





<sup>**[components/compositing/compositor.rs, line 428 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbhHeTrHkM_ZhMwvgZ)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/compositing/compositor.rs#L428)):</sup>
If I move animation_state I cannot use it below in comparison, isn't it?

---

<sup>**[components/devtools/actors/framerate.rs, line 83 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbfGw3LausaDH7CqyA)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/actors/framerate.rs#L83)):</sup>
Is it bad name?

---

<sup>**[components/devtools/actors/framerate.rs, line 83 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbfMjl6hqwE8Oa1U52)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/actors/framerate.rs#L83)):</sup>
May be Box<&bool>?
I want to send reference on self.is_recording
For avoid pointing lifetime I take Box

---

<sup>**[components/devtools/actors/framerate.rs, line 98 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbfUvAmuYYNBj_xe6b)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/actors/framerate.rs#L98)):</sup>
I think problem is in Box<bool>, that I didn't send reference to self.is_recording and just ref to Box

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by JIoJIaJIu** [comment]
<sup>**[components/devtools/lib.rs, line 271 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbgOEubgkJQQfKLyOh)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/lib.rs#L271)):</sup>
I choosed that way for avoid bloating function's stack with many local variables

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by jdm** [comment]
<sup>**[components/compositing/compositor.rs, line 428 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbhHeTrHkM_ZhMwvgZ)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/compositing/compositor.rs#L428)):</sup>
If you making AnimationState derive Copy there is no need to clone it.

---

<sup>**[components/devtools/actors/framerate.rs, line 83 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbfGw3LausaDH7CqyA)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/actors/framerate.rs#L83)):</sup>
Well, I don't understand what it means here :)

---

<sup>**[components/devtools/actors/framerate.rs, line 83 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbfMjl6hqwE8Oa1U52)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/actors/framerate.rs#L83)):</sup>
I think we want `Arc<Mutex<bool>>` so that we can check the actual, shared value when the closure executes; otherwise we are sending the value that was present when the closure was created.

---

<sup>**[components/devtools/actors/framerate.rs, line 98 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbfUvAmuYYNBj_xe6b)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/actors/framerate.rs#L98)):</sup>
I agree.

---

<sup>**[components/devtools/lib.rs, line 271 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5753#-JnbgOEubgkJQQfKLyOh)** ([raw file](https://github.com/servo/servo/blob/bfba26780d19747b5864042731b5d19782e3b997/components/devtools/lib.rs#L271)):</sup>
I don't think that's a big concern here :)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by jdm** [comment]
Reviewed files:
- components/compositing/compositor.rs @ r3
- components/compositing/compositor_task.rs @ r3
- components/compositing/constellation.rs @ r3
- components/devtools/actors/framerate.rs @ r3
- components/devtools/lib.rs @ r3
- components/devtools_traits/lib.rs @ r3
- components/layout/animation.rs @ r3
- components/msg/constellation_msg.rs @ r3
- components/script/devtools.rs @ r3
- components/script/dom/bindings/trace.rs @ r3
- components/script/dom/document.rs @ r3
- components/script/dom/window.rs @ r3
- components/script/lib.rs @ r3
- components/script/script_task.rs @ r3
- components/script_traits/lib.rs @ r3
- tests/wpt/include.ini @ r3
- tests/wpt/metadata/animation-timing/callback-invoked.html.ini @ r3

---

<sup>**[components/compositing/compositor.rs, line 171 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoUz-X2KKbjYLdSR3bA)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/compositing/compositor.rs#L171)):</sup>
Whether

---

<sup>**[components/compositing/compositor.rs, line 174 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoUz3R-QCMOacw5Ym0u)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/compositing/compositor.rs#L174)):</sup>
Whether

---

<sup>**[components/devtools/actors/framerate.rs, line 83 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoUzcREDcguEswUSKv7)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/devtools/actors/framerate.rs#L83)):</sup>
Let's just make the one from earlier mutable instead.

---

<sup>**[components/devtools/actors/framerate.rs, line 128 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoUzyQEd6XHa4mM58f5)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/devtools/actors/framerate.rs#L128)):</sup>
Make the first one mutable instead.

---

<sup>**[components/layout/animation.rs, line 58 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoV-B7BIx60Bh6wUyIo)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/layout/animation.rs#L58)):</sup>
This doesn't look right; this code executes if the running_animations vector is not empty.

---

<sup>**[components/script/dom/document.rs, line 819 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoV-he3NZ5Iwq9n547O)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/script/dom/document.rs#L819)):</sup>
We don't seem to send NoAnimationCallbacksPresent anywhere in these changes.

---

<sup>**[tests/wpt/metadata/animation-timing/callback-invoked.html.ini, line 3 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoV-nQdkC4mgfEKd0w3)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/tests/wpt/metadata/animation-timing/callback-invoked.html.ini#L3)):</sup>
Have you investigated why this fails?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by JIoJIaJIu** [comment]
<sup>**[components/script/dom/document.rs, line 819 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoV-he3NZ5Iwq9n547O)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/script/dom/document.rs#L819)):</sup>
Did I understand right? That NoAnimationCallbacksPresent sends [nowhere](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/compositing/compositor.rs#L437)?
Or I should in animation.rs create something like `tick_animation_callbacks`?

---

<sup>**[tests/wpt/metadata/animation-timing/callback-invoked.html.ini, line 3 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoV-nQdkC4mgfEKd0w3)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/tests/wpt/metadata/animation-timing/callback-invoked.html.ini#L3)):</sup>
I think [document.hidden](https://html.spec.whatwg.org/multipage/interaction.html#editing) should be implemented

```javascript
async_test(function (t) {                                                                                                                                                               
    t.step(function() {                                                                                                                                                                   
        assert_false(document.hidden, "document.hidden must be exist and be false to run this test properly");                                                                              
    });                                                                                                                                                                                   
    window.requestAnimationFrame(function () {                                                                                                                                            
        t.step(function() { assert_true(true); t.done(); });                                                                                                                                
    });                                                                                                                                                                                   
}, "requestAnimationFrame callback is invoked at least once before the timeout");
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/compositing/compositor.rs @ r4
- components/devtools/actors/framerate.rs @ r4
- components/layout/animation.rs @ r4
- components/script/dom/document.rs @ r4

---

<sup>**[components/script/dom/document.rs, line 819 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoV-he3NZ5Iwq9n547O)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/script/dom/document.rs#L819)):</sup>
We should have some code that runs after all animation callbacks have finished executing that checks if there any any new animation callbacks; if there are none, we should send NoAnimationCallbacksPresent.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by JIoJIaJIu** [comment]
<sup>**[components/script/dom/document.rs, line 825 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5753#-JoV-he3NZ5Iwq9n547O)** ([raw file](https://github.com/servo/servo/blob/e8478701272c3568f7713829c9489f6218707a67/components/script/dom/document.rs#L825)):</sup>
Ahh, precise

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-rebase 

---

Reviewed files:
- components/script/dom/document.rs @ r5
- components/script/dom/window.rs @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Comment by jdm** [comment]
-S-awaiting-review

---

Reviewed files:
- components/compositing/compositor.rs @ r6
- components/devtools/actors/timeline.rs @ r6
- components/devtools/lib.rs @ r6
- components/devtools_traits/lib.rs @ r6
- components/layout/animation.rs @ r6
- components/script/dom/bindings/trace.rs @ r6
- components/script/dom/document.rs @ r6
- components/script/dom/window.rs @ r6
- components/script/lib.rs @ r6
- components/script/script_task.rs @ r6
- components/script_traits/lib.rs @ r6

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5753)

**Pull request merged**
