### PR TITLE
Fix dictionary member conversion failure (fixes #7231)

### LINKED ISSUE #7231: Uncatcheable exception with DOM object in dictionary
Neither `alert` is shown in
```js
try {
    alert(new UIEvent("x", {
        view: 7
    }))
} catch (e) {
    alert(e)
}
```

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7236)

### CODE REVIEW

**Comment by nox** [comment]
```rust
            match try!(get_dictionary_property(cx, object.handle(), "view", rval.handle_mut())) {
                true => {
                    if rval.handle().get().is_object() {
                        Some(match native_from_handlevalue(rval.handle()) {
                            Ok(val) => val,
                            Err(()) => {
                                throw_type_error(cx, "value does not implement interface Window.");
                                return Err(());
                            }
                        })
                    } else if rval.handle().get().is_null_or_undefined() {
                        None
                    } else {
                        throw_type_error(cx, "Value is not an object.");
                        return Err(());
                    }
                },
                false => {
                    None
                },
            }
```

Where do you want me to add a test, @Ms2ger?

**Comment by Ms2ger** [comment]
Surprisingly nice patch :)

Add a test under `tests/wpt/web-platform-tests/DOMEvents/`, perhaps?

**Comment by nox** [comment]
Will do.

**Pull request merged**
