### PR TITLE
Upgrade to rustc 1.43.0-nightly (5d04ce67f 2020-02-13)

### LINKED ISSUE #25550: macOS ld considers libscript-*.rlib to be invalid
Cannot build Servo with latest master (2a594821ba) on macOS 10.14.6

(This is my first time to see this kind of compilation error 🤔 I've tried to run `./mach clean` but it didn't help :/)

Check the error message [in this gist](https://gist.github.com/CYBAI/190f432efdf1d0398c502337ec22234f) 👈

### PR DESCRIPTION
**Pull request by SimonSapin**
~This Nightly doesn’t have rustfmt, so merging this PR is blocked on https://github.com/rust-lang/rust/issues/68917 and upgrading to a Nightly with the fix.~

Fixes #25550

### CODE REVIEW

**Comment by paulrouget** [comment]
r=me

Some warning though:

```
warning: unnecessary parentheses around block return value                                                  
   --> components/layout/fragment.rs:947:13                                                                 
    |
947 | /             (MaybeAuto::from_style(margin.inline_start, Au(0)).specified_or_zero() +                
948 | |                 MaybeAuto::from_style(margin.inline_end, Au(0)).specified_or_zero())                
    | |____________________________________________________________________________________^                
    |
    = note: `#[warn(unused_parens)]` on by default                                                          
help: remove these parentheses
    |
947 |             MaybeAuto::from_style(margin.inline_start, Au(0)).specified_or_zero() +                   
948 |                 MaybeAuto::from_style(margin.inline_end, Au(0)).specified_or_zero()                   
    |
warning: unnecessary parentheses around block return value                                                  
   --> components/layout/fragment.rs:960:13
    |
960 |             (padding.inline_start.to_used_value(Au(0)) + padding.inline_end.to_used_value(Au(0)))     
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help:
 remove these parentheses
```

**Comment by nox** [comment]
I fixed it.

@bors-servo r=paulrouget

**Comment by paulrouget** [comment]
Fix #25550

**Comment by SimonSapin** [comment]
That only works in the PR description (or commit messages), I’ve added it.

**Comment by SimonSapin** [comment]
Fixed some Windows-only warnings:

```
error: unnecessary parentheses around block return value
   --> components\gfx\platform\windows\font.rs:138:21
    |
138 |                     ((family, face))
    |                     ^^^^^^^^^^^^^^^^ help: remove these parentheses
    |
    = note: `-D unused-parens` implied by `-D warnings`
error: unnecessary parentheses around block return value
   --> components\gfx\platform\windows\font.rs:148:21
    |
148 |                     ((family, face))
    |                     ^^^^^^^^^^^^^^^^ help: remove these parentheses
```

@bors-servo r=paulrouget

**Comment by SimonSapin** [comment]
*Sighs*

@bors-servo retry #24726

**Comment by jdm** [comment]
@bors-servo retry
* #25513

**Pull request merged**
