### PR TITLE
style: Make GeckoElement::traversal_children faster.

### PR DESCRIPTION
**Pull request by heycam**
From https://bugzilla.mozilla.org/show_bug.cgi?id=1372061.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17541)

### CODE REVIEW

**Comment by heycam** [comment]
@emilio is this a bindgen bug?  The types in C++ look like this:

```C++
class ExplicitChildIterator {
  const nsIContent* mParent;
  nsIContent* mChild;
  nsAutoPtr<ExplicitChildIterator> mShadowIterator;
  uint32_t mIndexInInserted;
  bool mIsFirst;
};

class FlattenedChildIterator : ExplicitChildIterator {
  bool mXBLInvolved;
};
```

and the generated Rust types look like:

```rust
pub struct ExplicitChildIterator {
    pub mParent: *const root::nsIContent,
    pub mChild: *mut root::nsIContent,
    pub mDefaultChild: *mut root::nsIContent,
    pub mShadowIterator: root::nsAutoPtr<root::mozilla::dom::ExplicitChildIterator>,
    pub mIndexInInserted: u32,
    pub mIsFirst: bool,
}

pub struct FlattenedChildIterator {
    pub _base: root::mozilla::dom::ExplicitChildIterator,
    pub mXBLInvolved: bool,
}   
```

The generated assertions show that bindgen expects both types to have size 40 (maybe as if the `mXBLInvolved` bool packs up with `mIsFirst`?), and the assertion fails for `FlattenedChildIterator`, which Rust (correctly) computes to have size 48.

**Comment by emilio** [comment]
It's a bindgen _codegen_ bug: https://github.com/servo/rust-bindgen/issues/380. 

In particular, the struct in C++ (in OSX/Linux) is able to merge the `mXBLInvolved` field in the remaining space in `ExplicitChildIterator`.

This doesn't happen for MSVC though, so fixing it in bindgen hasn't been prioritary (because the fix varies per platform, which sucks).

A way to work-around this could be moving the `mIsFirst` field before `mIndexInInserted` instead of after.

**Pull request merged**
