### PR TITLE
layout: Use a special path that treats `margin: auto` as zero for inline-block inline size computation.

### PR DESCRIPTION
**Pull request by pcwalton**
Places the search icon in the right place on the Google SERPs.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7533)

### CODE REVIEW

**Comment by pcwalton** [comment]
dbaron tells me that this is wrong. Fixing

**Comment by pcwalton** [comment]
OK, this should be correct now. r? @mbrubeck

**Comment by jdm** [comment]
Is there a test that would have picked up why the previous patch was wrong? Could we add it too?

**Comment by pcwalton** [comment]
Yeah, let me add one.

**Comment by mbrubeck** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7533)

**Comment by mbrubeck** [comment]
`test inline_block_margin_auto_a.html == inline_block_margin_auto_ref.html ... FAILED`

**Comment by pcwalton** [comment]
@bors-servo: r=mbrubeck

Just typo'd the file name

**Comment by pcwalton** [comment]
@bors-servo: r=mbrubeck

Added the test @jdm requested.

**Comment by jdm** [comment]
```

/css21_dev/html4/inline-block-replaced-width-001.htm
----------------------------------------------------
PASS expected FAIL [Parent]
```

**Pull request merged**
