### PR TITLE
Improve implementation of DOMRect and implement DOMRectReadOnly

### PR DESCRIPTION
**Pull request by tschneidereit**
Passes most tests from test-css. The remaining ones should pass once we have https://github.com/w3c/csswg-test/pull/834.

r? @Ms2ger

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7415)

### CODE REVIEW

**Comment by tschneidereit** [comment]
Rookie mistake. Will fix.

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

Use drafts.fxtf.org links, fix the nits, and it's all good.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/devtools.rs, line 106 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7415#-Jxo8NRAZttJMaWvHvUW)** ([raw file](https://github.com/servo/servo/blob/6f4a68ec8ef444b185b790fb1838ea12bcc5ee96/components/script/devtools.rs#L106)):</sup>
.r() is useless now that Root implements Deref.

---

<sup>**[components/script/dom/domrect.rs, line 5 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7415#-Jxo9avmB45Yz9ekgKPy)** ([raw file](https://github.com/servo/servo/blob/6f4a68ec8ef444b185b790fb1838ea12bcc5ee96/components/script/dom/domrect.rs#L5)):</sup>
Nit: We generally don't import Wrap in IDL implementations, instead we import both the Binding module and the Methods trait inside.

---

<sup>**[components/script/dom/domrectreadonly.rs, line 94 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7415#-Jxo9Bo4rgIBKpEyrtDT)** ([raw file](https://github.com/servo/servo/blob/6f4a68ec8ef444b185b790fb1838ea12bcc5ee96/components/script/dom/domrectreadonly.rs#L94)):</sup>
Implement helper methods on DOMRect itself, without an intermediate trait.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7415)

**Comment by nox** [comment]
Reviewed 1 of 12 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/domrectreadonly.rs, line 41 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7415#-JxoJ_sk7Cu01Sb1PkH6)** ([raw file](https://github.com/servo/servo/blob/39ceb67ea0340324a400a3bd623c5fccc4d45022/components/script/dom/domrectreadonly.rs#L41)):</sup>
set_x

---

<sup>**[components/script/dom/domrectreadonly.rs, line 45 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7415#-JxoJakkTlgbLu4VHMeX)** ([raw file](https://github.com/servo/servo/blob/39ceb67ea0340324a400a3bd623c5fccc4d45022/components/script/dom/domrectreadonly.rs#L45)):</sup>
set_y

---

<sup>**[components/script/dom/domrectreadonly.rs, line 49 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7415#-JxoJb_gCKpbUoOkfSjy)** ([raw file](https://github.com/servo/servo/blob/39ceb67ea0340324a400a3bd623c5fccc4d45022/components/script/dom/domrectreadonly.rs#L49)):</sup>
set_width

---

<sup>**[components/script/dom/domrectreadonly.rs, line 53 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7415#-JxoJcJ6PhNY2Sxvyciz)** ([raw file](https://github.com/servo/servo/blob/39ceb67ea0340324a400a3bd623c5fccc4d45022/components/script/dom/domrectreadonly.rs#L53)):</sup>
set_height

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7415)

**Comment by nox** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7415)

**Comment by jdm** [comment]
```
/_mozilla/mozilla/getBoundingClientRect.html
--------------------------------------------
FAIL Untitled
FAIL Untitled 1
/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-auto.html
--------------------------------------------------------------------------
PASS expected FAIL placeholder: 'img', svgViewBoxAttr: '0 0 100 200', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', 
PASS expected FAIL placeholder: 'img', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgWidthAttr: '200', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgWidthAttr: '200', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-percentage.html
--------------------------------------------------------------------------------
PASS expected FAIL placeholder: 'img', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', 
PASS expected FAIL placeholder: 'img', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgWidthAttr: '200', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '200', 
PASS expected FAIL placeholder: 'img', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
PASS expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
/html/rendering/replaced-elements/svg-inline-sizing/svg-inline.html
-------------------------------------------------------------------
PASS expected FAIL svgViewBoxAttr: '0 0 100 200', 
PASS expected FAIL containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', 
```

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 3 of 4 files at r5.
Review status: 14 of 15 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7415)

**Comment by jdm** [comment]
```
/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-auto.html
--------------------------------------------------------------------------
FAIL placeholder: 'img', svgViewBoxAttr: '0 0 100 200', 
FAIL placeholder: 'img', containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', 
FAIL placeholder: 'img', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
FAIL placeholder: 'img', containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '200', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgWidthAttr: '200', svgHeightAttr: '200', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgWidthAttr: '200', svgHeightAttr: '200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '200', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '200', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '200', 
FAIL placeholder: 'img', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
FAIL placeholder: 'img', containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '25%', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '25%', 
FAIL placeholder: 'img', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
FAIL placeholder: 'img', containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
FAIL placeholder: 'img', containerHeightStyle: '400px', placeholderWidthAttr: '50%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-percentage.html
--------------------------------------------------------------------------------
FAIL placeholder: 'img', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', 
FAIL placeholder: 'img', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgWidthAttr: '200', svgHeightAttr: '200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '200', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '200', 
FAIL placeholder: 'img', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgHeightAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '25%', 
FAIL placeholder: 'img', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '25%', svgHeightAttr: '25%', 
/html/rendering/replaced-elements/svg-inline-sizing/svg-inline.html
-------------------------------------------------------------------
FAIL svgViewBoxAttr: '0 0 100 200', 
FAIL containerHeightStyle: '400px', svgViewBoxAttr: '0 0 100 200', 
```

**Comment by nox** [comment]
@tschneidereit I think you failed somewhere during your rebase.

**Comment by nox** [comment]
Why are there so many more expected failures now?

-S-awaiting-review +S-needs-code-changes +S-awaiting-answer 

---

Reviewed 1 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/element.rs, line 1269 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7415#-Jz4mUrhC0QDl_-xQNLM)** ([raw file](https://github.com/servo/servo/blob/c3364264645549b7e01c20f58898ae2d1ab5bfb1/components/script/dom/element.rs#L1269)):</sup>
I've noticed that there are now more `DOMRect::new()` calls where the inputs are from Point2D and Size2D than separate values. Separate values are passed only in the `Constructor()` method. Wouldn't it be better if `DOMRect::new()` itself took Point2D and Size2D values?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7415)

**Comment by nox** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7415)

**Comment by nox** [comment]
@tschneidereit Ping?

**Comment by tschneidereit** [comment]
@nox, I finally rebased this, should be ready for review again.

**Comment by nox** [comment]
Still one issue and this is good to go.

-S-awaiting-answer -S-awaiting-answer -S-needs-rebase 


---

Reviewed 6 of 6 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[tests/wpt/metadata-css/geometry-1_dev/html/DOMRect-001.htm.ini, line 14 \[r7\]](https://reviewable.io:443/reviews/servo/servo/7415#-K0r_8o6dHYyGMCBhAMi)** ([raw file](https://github.com/servo/servo/blob/4c1c05fac67903ca5e1d06a1e5be04a90a1766e2/tests/wpt/metadata-css/geometry-1_dev/html/DOMRect-001.htm.ini#L14)):</sup>
We still don't have the changes from your csswg-test fix?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7415)

**Comment by tschneidereit** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/element.rs, line 1269 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7415#-Jz4mUrhC0QDl_-xQNLM)** ([raw file](https://github.com/servo/servo/blob/c3364264645549b7e01c20f58898ae2d1ab5bfb1/components/script/dom/element.rs#L1269)):</sup>
As discussed on IRC, that'd make things either more tedious by requiring us to first unwrap the scalar values, then convert them to f64, and then create `{Point,Size}2D<f64>` from them. Or implement a `From` trait, but that'd need to go into app_units (or Euclid, but probably the former). Punting for now.


---

<sup>**[tests/wpt/metadata-css/geometry-1_dev/html/DOMRect-001.htm.ini, line 14 \[r7\]](https://reviewable.io:443/reviews/servo/servo/7415#-K0r_8o6dHYyGMCBhAMi)** ([raw file](https://github.com/servo/servo/blob/4c1c05fac67903ca5e1d06a1e5be04a90a1766e2/tests/wpt/metadata-css/geometry-1_dev/html/DOMRect-001.htm.ini#L14)):</sup>
We don't, no. The last import was from a day before my fix landed upstream.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7415)

**Comment by nox** [comment]
@bors-servo r+

Thanks for your contribution!

-S-needs-code-changes 


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7415)

**Pull request merged**
