### PR TITLE
Scheduler with fewer threads

### LINKED ISSUE #11268: Avoid creating a thread every single event we receive
We're doing this right now, for some reason I can't understand. We spawn a single thread just to sleep, ensure we're not cancelled, and send an empty message.

If we're going to use threads, we should at least use a thread pool, but probably there's a smarter way to do this, like a single thread that sleeps just the necessary time to dispatch the next event, or something.

I plan to take a look at this, but my time is actually constrained a lot, so if someone wants to investigate and refactor this, please do!

### PR DESCRIPTION
**Pull request by asajeffrey**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [X] These changes fix #11268.

Either:
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it's improving perf, not adding functionality.

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11283)

### CODE REVIEW

**Comment by asajeffrey** [comment]
r? emilio
cc @metajack @pcwalton

**Comment by asajeffrey** [comment]
Compare and contrast with #11279.

**Comment by asajeffrey** [comment]
This is a poor-devs-version of https://github.com/rust-lang/rfcs/issues/962.

**Comment by asajeffrey** [comment]
Rewrote after IRC conversation http://logs.glob.uno/?c=mozilla%23servo&s=19+May+2016&e=19+May+2016#c434085

**Comment by emilio** [comment]
The approach looks good to me, though I think it needs a bit more documentation, and handling errors somehow instead of silently exiting :)

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Rewrote after IRC conversation http://logs.glob.uno/?c=mozilla%23servo&s=19+May+2016&e=19+May+2016#c434085
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/constellation/timer_scheduler.rs, line 54 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIEBRMazpoK230Vl8pD:-KIEBRMazpoK230Vl8pE:-1709821342) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L54)):*
> ```Rust
>             .spawn(move || {
>                 let mut scheduled_events = BinaryHeap::<ScheduledEvent>::new();
>                 loop {
> ```

I'd prefer this to be commented at least minimally with the approach. It's fairly obvious when you read it, but it would be great now we haven't specific methods for `dispatch_pending_events`, etc.

---

*[components/constellation/timer_scheduler.rs, line 77 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIEATnY1nwhhMO_ArIa:-KIEATnY1nwhhMO_ArIb:-794744780) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L77)):*
> ```Rust
>                             Some(event) => thread::park_timeout(event.for_time - now),
>                         },
>                         Err(Disconnected) => break,
> ```

Since if this happens it'd be a bug, and this is a self-contained thread, that shouldn't make the whole constellation crash, I'd rather `panic!()` here with a descriptive message that silently shut down the scheduler.

---

*[components/constellation/timer_scheduler.rs, line 85 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIEAo1G6Q9Rdkexno9F:-KIEAo1G6Q9Rdkexno9G:468593611) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L85)):*
> ```Rust
>             .clone();
> 
>         thread::Builder::new()
> ```

nit: This can probably use `spawn_named` just fine. Not a big deal though, your choice :)

---

*[components/constellation/timer_scheduler.rs, line 88 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIECaY9rbXfiXa-Iki4:-KIECaY9rbXfiXa-Iki5:-607245948) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L88)):*
> ```Rust
>             .name(String::from("TimerProxy"))
>             .spawn(move || {
>                 while let Ok(req) = req_ipc_receiver.recv() {
> ```

Same here, this `recv()` shouldn't error, and if it does, it's better to issue a warning and either miss an event or panic instead of shutting down the `TimerProxy` silently.

---

*[components/constellation/timer_scheduler.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIEB1ngJNvAoU9CNhNl:-KIEB1ngJNvAoU9CNhNm:434857795) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L90)):*
> ```Rust
>                 while let Ok(req) = req_ipc_receiver.recv() {
>                     req_sender.send(req).unwrap();
>                     timeout_thread.unpark();
> ```

A comment here describing the semantics of `park()`/`unpark()` that make this be race-free would help other people reading the code to avoid scratching their head too much unnecessarily.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11283#-:-KIEDFPp81ciDxtM7MYl:136791888)*

**Comment by asajeffrey** [comment]
More IRC conversation: http://logs.glob.uno/?c=mozilla%23servo&s=20+May+2016&e=20+May+2016#c434669 about whether to move forward with #11283 or #11279.

**Comment by asajeffrey** [comment]
Added comments.

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :hourglass: Trying commit 082a752 with merge 17c1ccd...
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/constellation/timer_scheduler.rs, line 54 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIEBRMazpoK230Vl8pD:-KIEIAOsehfuhfIfwysr:-133038635) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L54)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> I'd prefer this to be commented at least minimally with the approach. It's fairly obvious when you read it, but it would be great now we haven't specific methods for `dispatch_pending_events`, etc.
</details>
Added comments.

---

*[components/constellation/timer_scheduler.rs, line 77 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIEATnY1nwhhMO_ArIa:-KIEIIXtrVwkKug9-EwZ:-1816861756) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L77)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> Since if this happens it'd be a bug, and this is a self-contained thread, that shouldn't make the whole constellation crash, I'd rather `panic!()` here with a descriptive message that silently shut down the scheduler.
</details>
I don't think it's a bug if this disconnects: it can happen if the `req_ipc_sender` is dropped, since this causes the proxy thread to terminate,  dropping the `req_sender`, causing a disconnect.

---

*[components/constellation/timer_scheduler.rs, line 85 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIEAo1G6Q9Rdkexno9F:-KIEIubvq95aLkRyvyG3:-1369871894) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L85)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> nit: This can probably use `spawn_named` just fine. Not a big deal though, your choice :)
</details>
For the moment I'd rather leave it as-is, so both threads use the same mechanism for spawning. At some point we might want to make `spawn_named` return the join handler.

---

*[components/constellation/timer_scheduler.rs, line 88 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIECaY9rbXfiXa-Iki4:-KIEIqfwXkjR4Ei99oGv:1317703676) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L88)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> Same here, this `recv()` shouldn't error, and if it does, it's better to issue a warning and either miss an event or panic instead of shutting down the `TimerProxy` silently.
</details>
Same answer :)

---

*[components/constellation/timer_scheduler.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIEB1ngJNvAoU9CNhNl:-KIEK6il2qSOwLiDijVS:-499146009) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L90)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> A comment here describing the semantics of `park()`/`unpark()` that make this be race-free would help other people reading the code to avoid scratching their head too much unnecessarily.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11283#-:-KIEKV7jMkSTOTf9oQMK:-133038635)*

**Comment by emilio** [comment]
Well, reviewable ate the rest of the comments for me it seems, but anyway. The last remaining nit would be an exit message, but feel free to `r=me` if you don't think it's necessary :)

-S-awaiting-review

<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Added comments.
</details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/constellation/timer_scheduler.rs, line 85 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIEAo1G6Q9Rdkexno9F:-KIET_HeyxVX5eP1V0GJ:-842062816) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L85)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> For the moment I'd rather leave it as-is, so both threads use the same mechanism for spawning. At some point we might want to make `spawn_named` return the join handler.
</details>
Makes sense.

---

*[components/constellation/timer_scheduler.rs, line 88 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIECaY9rbXfiXa-Iki4:-KIETkvo5nSo5CzkUcA2:960140302) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L88)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Same answer :)
</details>
Fair enough.

I'd still love to see a message (`warn!()`, maybe?) when the scheduler is exiting, but feel free to land this as-is if you think it's not necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11283#-:-KIEUARwnx7Z7-S48hLj:633252949)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/constellation/timer_scheduler.rs, line 88 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11283#-KIECaY9rbXfiXa-Iki4:-KIEWW0ahQRAGn0Q7M0w:-909266951) ([raw file](https://github.com/servo/servo/blob/082a752cef4d7c2101064bebbed7ec38e63ed615/components/constellation/timer_scheduler.rs#L88)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> Fair enough.
> 
> I'd still love to see a message (`warn!()`, maybe?) when the scheduler is exiting, but feel free to land this as-is if you think it's not necessary.
</details>
Added warnings if/when these threads terminate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11283)*

**Pull request merged**
