### PR TITLE
WIP - Add an attribute to iframe to toggle mozcontentblocker

### LINKED ISSUE #11500: Add an attribute to iframe to toggle mozcontentblocker
The same way we have `<iframe mozprivatebrowsing>`, we could have `<iframe mozcontentblocker>` to toggle the content blocker mechanism.

/cc @nox @jdm

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11500 
- [ ] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15841)

### CODE REVIEW

**Comment by ferjm** [comment]
@nox I managed to expose the `mozcontentblocker` attribute on the `iframe` element, but I am not sure what needs to be done next. Could you give me some pointers about where is content blocking being handled now, please?

I saw that you implemented support for content blocking on #11413, but it seems that it was partially removed later on #14360, and I can't find how content blocking is currently done.

**Comment by fabricedesre** [comment]
I'm not convinced that content blocking should be part of Servo itself. I'd rather do that in the embedder, which means that Servo needs hooks but not the blocker itself.

**Comment by nox** [comment]
FWIW our "embedder hook" story is really not up to the task for now, and if we go that way we should clear that up.

**Comment by ferjm** [comment]
It seems that the content blocker needs to be rewritten in #14307 (or maybe with a different approach as suggested by @fabricedesre). And until this is done, it makes no sense to add the iframe attribute.

**Comment by metajack** [comment]
@fabricedesre Are you suggesting we put it in the embedding API and expose it in JS for browser.html?

**Comment by fabricedesre** [comment]
Yes, the embedding API should offer facilities similar to https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIContentPolicy . In the case of b.html the Rust -> JS glue could choose to expose that.

WebExtensions offer the same kind of features through the https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest api. I suspect that we would want to build WebExtension support on top of the ContentPolicy mechanism, though.

Another related thing to consider is tracking protection. Gecko has an internal implementation of tracking protection that may be nice to replicate and turn on with the already existing private browsing mode.

**Pull request closed without merging**
