### PR TITLE
Remove broken thumbprint.

### PR DESCRIPTION
**Pull request by jdm**
This prevents me from building locally every time I make a new clone of Servo or try a branch that still has it present.

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Fun fact, the nightly has been broken for months \o/

**Comment by paulrouget** [comment]
> Fun fact, the nightly has been broken for months \o/

Ouch. You mean it couldn't be installed?

**Comment by jdm** [comment]
Yes, ever since my changes that removed signing to upload to the store.

**Pull request merged**
