### PR TITLE
Fix #14497: WeakMediaQueryListVec assumes its contents are still alive

### LINKED ISSUE #14497: WeakMediaQueryListVec assumes its contents are still alive
screen shot 2016-12-08 at 9 41 26 am

called `Result::unwrap()` on an `Err` value: "SendError(..)"
### Servo Version:
Servo 0.0.1-0fe94a6
### Backtrace:
```

WARNING: <Constellation>: Sending layout exit message failed (Bogus destination port.).
WARNING: <Constellation>: creating replacement pipeline for about:failure
WARNING: <ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(6) }>: Panic hook called.
ERROR: called `Result::unwrap()` on an `Err` value: "SendError(..)"

stack backtrace:
   0:        0x10a22a1ee - backtrace::backtrace::trace::h90be2828c7ec6b59
   1:        0x10a22a4dc - backtrace::capture::Backtrace::new::h8135b43a33e0c535
   2:        0x10a2202e5 - constellation::constellation::log_entry::h21fb09bca1beb3f1
   3:        0x10a21f1b2 - _<constellation..constellation..FromCompositorLogger as log..Log>::log::h1b866bc979bfd912
   4:        0x10bad4531 - log::__log::hb57b61a1a8ce0303
   5:        0x10a0181a0 - servo::main::_{{closure}}::h027bb2285067f26b
   6:        0x10bb1dc53 - std::panicking::rust_panic_with_hook::ha5aed1dfc0e220e3
   7:        0x10bb1db24 - std::panicking::begin_panic::hc066339e2fdc17d1
   8:        0x10bb1da42 - std::panicking::begin_panic_fmt::h5912b2d2df332044
   9:        0x10bb1d9a7 - rust_begin_unwind
  10:        0x10bb4b860 - core::panicking::panic_fmt::h561c5ee168a3d2cb
  11:        0x10a48f460 - core::result::unwrap_failed::hafae191a23c88cc1
  12:        0x10a7624fe - script::dom::window::Window::force_reflow::hc13998871345e936
  13:        0x10a762ab5 - script::dom::window::Window::reflow::h9725c858aa36194e
  14:        0x10a7ac536 - script::script_thread::ScriptThread::handle_msgs::h845cf289a659023e
  15:        0x10a3968c7 - std::panicking::try::do_call::h8c169752eba05a89
  16:        0x10bb1eb2a - __rust_maybe_catch_panic
  17:        0x10a4c8926 - _<F as alloc..boxed..FnBox<A>>::call_box::hd0a3119c99f60ac4
  18:        0x10bb1cbd4 - std::sys::imp::thread::Thread::new::thread_start::h8084b1107992ae5b
  19:     0x7fff883bf99c - _pthread_body
  20:     0x7fff883bf919 - _pthread_start
```
This report was generated by the browser.html issue reporter.

### PR DESCRIPTION
**Pull request by potocpav**
First time contributor here. Noticed this issue is easily solved, so I did it. I am very unsure about how things work here: Is a test needed? What should it look like? Should the "unwrap" be avoided (making bigger changes to the code)?

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14497  (github issue number if applicable).

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15083)

### CODE REVIEW

**Comment by jdm** [comment]
Yes, a test that demonstrates that the problem does not occur (and will not reoccur in the future!) is necessary. We have [documentation](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) explaining how to create new ones in `tests/wpt/mozilla/tests/mozilla/`.

**Comment by jdm** [comment]
It doesn't look like it's possible to avoid the unwrap call with the current API, though.

**Comment by potocpav** [comment]
The issue reproduces when a MediaQueryList is garbage collected. How can I trigger garbage collection in a test?

**Comment by potocpav** [comment]
Added a test that crashes on master

**Pull request merged**
