### PR TITLE
Clarify how Servo rust snapshots work

### PR DESCRIPTION
**Pull request by mbrubeck**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6121)

### CODE REVIEW

**Comment by waddlesplash** [comment]
As someone who's kinda new and unfamiliar with the Servo build system, I definitely prefer the new wording to the old.

**Comment by metajack** [comment]
+S-awaiting-merge -S-awaiting-review 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- README.md @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6121)

**Comment by metajack** [comment]
r+

**Pull request merged**
