### PR TITLE
Appveyor: Downgrade GCC to 5.4.0-1

### PR DESCRIPTION
**Pull request by UK992**
Fix building on Appveyor.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12573)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
This looks awesome!

@jdm can you re-enable appveyor? How are you disabling it? It looks enabled on the Servo project page on appveyor...

**Comment by jdm** [comment]
I've been enabling/disabling the webhook, specifically.

**Comment by jdm** [comment]
@UK992 could you force push to the branch to kick off an appveyor build?

**Comment by UK992** [comment]
done.

**Comment by larsbergstrom** [comment]
@bors-servo r+

Thanks a TON for doing this!

**Comment by larsbergstrom** [comment]
Hrm, I don't see an intermittent for this:

```
Tests with unexpected results:
  ▶ Unexpected subtest result in /html/browsers/history/the-history-interface/002.html:
  │ FAIL [expected PASS] replaceState should not actually load the new URL
  │   → assert_true: expected true got undefined
  │ 
  │ tests10/<@http://web-platform.test:8000/html/browsers/history/the-history-interface/002.html:258:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ tests10@http://web-platform.test:8000/html/browsers/history/the-history-interface/002.html:257:9
```

**Comment by jdm** [comment]
File it and cc @connorgbrewster.

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #12580

**Pull request merged**
