### PR TITLE
style: Do not expose LocalMatchingContext.

### PR DESCRIPTION
**Pull request by emilio**
This type is a lot of complexity related to a very specific thing such as the
hover and active quirk.

Instead of that, move `nesting_level` to `MatchingContext`, and simplify all
this computing whether the quirk applies upfront, for each complex selector we
test.

This is less error-prone, and also allows simplifying more stuff in a bit.

Also, this makes the hover and active quirk work in Servo with no extra effort.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18876)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo try

 * Pretty sure this should be green, but just in case while waiting for someone to review...

**Comment by emilio** [comment]
Yup, green: https://treeherder.mozilla.org/#/jobs?repo=try&revision=222e03a5db940e169d4eaf17ee419a3ab34c9abd

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 7 of 7 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18876#-:-KwTuCbfWeJGUEBXxTPP:bkg9nno)*

**Pull request merged**
