### PR TITLE
Create own file for background calculations in layout

### PR DESCRIPTION
**Pull request by pyfisch**
See #19676

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19686)

### CODE REVIEW

**Comment by pyfisch** [comment]
Maybe `compute_background_placement` should also be moved but while it only is a method of `Fragment`  to access `self.border_padding` it depends on a lot of inputs.

**Review by emilio — COMMENTED** [review]
Maybe we should consider moving this to `gfx`? Or to a dedicated layout directory like `layout/display_list/` (moving `display_list_builder` to `layout/display_list/builder.rs`)?

**Comment by pyfisch** [comment]
> Maybe we should consider moving this to gfx? Or to a dedicated layout directory like layout/display_list/ (moving display_list_builder to layout/display_list/builder.rs)?

I am not sure how layout and gfx should be separated. From what I can see gfx mainly handles fonts. It also has the display lists code but it would be no longer need if only servos display lists are used. (Some code would probably remain.)

I am fine with both suggestions.

**Comment by emilio** [comment]
@mbrubeck or @glennw, any opinion on the discussion above?

**Comment by emilio** [comment]
Given radio silence, I'd go with `layout/display_list` for now, does that sound fine @pyfisch? :)

**Comment by pyfisch** [comment]
Updated. I have also moved the webrender_helpers. See the commit message.

**Review by emilio — APPROVED** [review]
LGTM, thanks a lot!

**Pull request merged**
