### PR TITLE
Some more drive-by fixes for rgba8_image_to_tex_image_data

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21660)

### CODE REVIEW

**Comment by jdm** [comment]
Build errors.

**Comment by nox** [comment]
Fixed.

**Comment by jdm** [comment]
@bors-servo retry
* #13479

**Comment by jdm** [comment]
@bors-servo retry
* oom

**Comment by jdm** [comment]
@bors-servo retry
* #13480

**Pull request merged**
