### PR TITLE
layout: Don't use the block container inline size as the initial computed table inline size.

### PR DESCRIPTION
**Pull request by pcwalton**
Makes google.com fully centered.

r? @glennw 
cc @SimonSapin

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6947)

### CODE REVIEW

**Comment by pcwalton** [comment]
@bors-servo: r-

This broke HN

**Comment by pcwalton** [comment]
Here's an alternate approach that still centers Google without breaking HN. r? @glennw

**Comment by glennw** [comment]
@pcwalton Is it possible to add a test to test for the HN case you encountered? Looks fine apart from that.

**Comment by pcwalton** [comment]
Done.

**Comment by jdm** [comment]
```
/css21_dev/html4/background-attachment-applies-to-001.htm
---------------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/background-attachment-applies-to-003.htm
---------------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/background-attachment-applies-to-002.htm
---------------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/background-attachment-applies-to-004.htm
---------------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/background-attachment-applies-to-007.htm
---------------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/background-attachment-applies-to-013.htm
---------------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/background-repeat-applies-to-007.htm
-----------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/c5525-fltmult-000.htm
--------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/line-height-applies-to-001.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/line-height-applies-to-002.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/line-height-applies-to-003.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/line-height-applies-to-004.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/line-height-applies-to-007.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/line-height-applies-to-006.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/line-height-applies-to-013.htm
-----------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/margin-bottom-applies-to-001.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/margin-bottom-applies-to-002.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/margin-bottom-applies-to-003.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/margin-bottom-applies-to-004.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/margin-bottom-applies-to-006.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/margin-bottom-applies-to-007.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/table-visual-layout-026a.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/table-visual-layout-026b.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/table-visual-layout-026c.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/table-visual-layout-026d.htm
---------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/vertical-align-baseline-009.htm
------------------------------------------------
FAIL [Parent]
```

**Comment by pcwalton** [comment]
What a nice problem to have.

**Comment by pcwalton** [comment]
The failing test seems to just be a pre-existing bug whereby Servo incorrectly applies padding to table captions.

**Pull request merged**
