### PR TITLE
Update margins when merging inline fragments

### LINKED ISSUE #10633: Inline margins are jumpy when applied to &nbsp
Test case:

    <!DOCTYPE html>
    <span style="margin-right: 128px">X&nbsp;</span>Y

Resize the window and notice that Y jumps into place.

This breaks http://reddit.com/r/rust.

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes #10633.  r? @pcwalton

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10655)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo retry

* #10656

**Comment by mbrubeck** [comment]
@bors-servo retry

WebGL conformance failure. Will file when at a computer.

**Comment by KiChjang** [comment]
Filed #10660.

**Comment by mbrubeck** [comment]
@bors-servo retry

*  #10656

**Pull request merged**
