### PR TITLE
Windows: Add missing dependencies

### LINKED ISSUE #16422: Windows nightly build fails due to missing VCRUNTIME140.dll and MSVCP140.dll
When trying to launch the nightly build of Servo on Windows 10, a dialog box is shown:

> The program can't start because VCRUNTIME140.dll is missing from your computer. Try reinstalling the program to fix this problem. 

Clicking OK on this error twice gives a new error:

> The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem.

### PR DESCRIPTION
**Pull request by UK992**
Rebased https://github.com/servo/servo/pull/16445 and updated with Gstreamer DLLs.

About msi installer, there is also included gstreamer installer, should be removed and replaced by needed gstreamer DLLs or keep it at is it?

Fixes #16422.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21968)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Looks good! Sorry for the delay in reviewing these changes.

**Comment by jdm** [comment]
```
Error running mach:

    ['build', '--dev']

The error occurred in the implementation of the invoked mach command.

This should never occur and is likely a bug in the implementation of that
command. Consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

KeyError: u'GSTREAMER_1_0_ROOT_X86_64'

  File "c:\buildbot\windows-msvc-dev\build\python\servo\build_commands.py", line 591, in build
    gst_root = env["GSTREAMER_1_0_ROOT_" + gst_x64]
program finished with exit code 1
```
Where is that environment variable supposed to come from?

**Comment by UK992** [comment]
@jdm Gstreamer installer set this variable.

**Comment by atouchet** [comment]
Would this help with #22315?

**Comment by UK992** [comment]
@atouchet it should solve this issue. 

Also I removed GStreamer installer from package, because it is no longer needed.

**Comment by atouchet** [comment]
@jdm r?

**Comment by jdm** [comment]
Ok, so let's be clear - the effect of this change is that:
* we generate an EXE instead of an MSI
* we no longer run the official GStreamer installer during the installation
* the installer contains all of the known DLL dependencies of Servo, including the GStreamer ones
Is that correct?

**Comment by UK992** [comment]
Correct.

**Comment by atouchet** [comment]
@jdm is anyone available to finish reviewing this? It would be nice to get this merged if it helps with some of the issues the Windows nightlies are having.

**Comment by jdm** [comment]
@bors-servo r+
Sorry for forgetting about this!

**Comment by jdm** [comment]
`Could not found GStreamer installation directory.` from the windows CI.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/master/etc/taskcluster/windows/bootstrap.ps1#L8-L10 makes it seem like the path should be correct, so I'm not sure what to make of that.

**Comment by UK992** [comment]
@jdm please try run with last commit

**Comment by jdm** [comment]
https://treeherder.allizom.org/#/jobs?repo=servo-try&revision=9cd2684f7f08ee6ead94d24cf47244426c701d93

**Comment by jdm** [comment]
```
C:\gstreamer\1.0\X86_64
False
Could not found GStreamer installation directory.
```

**Comment by jdm** [comment]
@SimonSapin Is it possible that GStreamer is not installed on the Windows taskcluster builder? The build could presumably still succeed because we're dynamically linking.

**Comment by SimonSapin** [comment]
In `etc/taskcluster/decision_task.py` we have:

```py
windows_build_env = {
    "LIB": "%HOMEDRIVE%%HOMEPATH%\\gst\\gstreamer\\1.0\\x86_64\\lib;%LIB%",
}
```
```py
        .with_repacked_msi(
            url="https://gstreamer.freedesktop.org/data/pkg/windows/" +
                "1.14.3/gstreamer-1.0-devel-x86_64-1.14.3.msi",
            sha256="b13ea68c1365098c66871f0acab7fd3daa2f2795b5e893fcbb5cd7253f2c08fa",
            path="gst",
        )
```

Maybe `gstreamer-1.0-x86-1.14.3.msi` (without `-devel`) is also needed?

**Comment by UK992** [comment]
@jdm try again please

Added missing `gstreamer-1.0-x86_64-1.14.3.msi` which contain needed dlls.

**Comment by UK992** [comment]
Installing `gstreamer-1.0-x86_64-1.14.3.msi` and setting `GSTREAMER_1_0_ROOT_X86_64` environment variable seems to solve the problem with Gstreamer.

But adding another `.with_repacked_msi()` in `etc/taskcluster/decision_task.py` creates new task in TC.

**Comment by jdm** [comment]
@bors-servo r+
LGTM! Thanks for fixing that!

**Comment by atouchet** [comment]
@jdm I don't think that worked. Retry?

**Comment by atouchet** [comment]
I tried running the latest nightly without having GStreamer installed and got some errors about missing DLLs.

Installer

**Comment by jdm** [comment]
Those will need to be added to the list of people ncludee DLLs.

**Pull request merged**
