### PR TITLE
Use the gold linker when available.

### PR DESCRIPTION
**Pull request by SimonSapin**
This shaves 50 seconds off the build time on my machine.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7229)

### CODE REVIEW

**Comment by Ms2ger** [comment]
What about if you don't have gold installed?

**Comment by SimonSapin** [comment]
I’ve run `mach build` successfully with this branch on a mac, where I think gold is not available. I assume that `-fuse-ld=gold` is ignored in that case.

**Comment by SimonSapin** [comment]
IRC chat:
> 12:35 	&lt;gw>	SimonSapin: that patch looks generally good to me, but I don't know a whole lot about if there's any implications to switching to gold (in terms of support on various distros, gotchas etc)
12:35 	&lt;SimonSapin>	I don’t know either, other than I really want my 50 seconds :)
12:36 	&lt;SimonSapin>	If it turns out to be problematic we can make it opt-in
12:36 	&lt;SimonSapin>	But I don’t know how to check if it is without doing it and waiting for bug reports
12:37 	&lt;nox>	SimonSapin: Is it really gold that is faster, or just that some linker flags aren't used anymore?
12:37 	&lt;SimonSapin>	nox: I think gold is known to be significantly faster
12:37 	&lt;SimonSapin>	it’s not the default because it doesn’t support some things
12:38 	&lt;SimonSapin>	I don’t know what things exactly
12:38 	&lt;nox>	SimonSapin: I know nothing about it, I was just wondering if your patch somewhat undoes what is done in https://github.com/rust-lang/rust/issues/6190.
12:38 	&lt;crowbot1>	Issue #6190: use linker optimizations - https://github.com/rust-lang/rust/issues/6190
12:38 	&lt;nox>	If these are passed through a different flag than link-args=-fuse-ld=, I have nothing more to say.
12:39 	&lt;Ms2ger>	SimonSapin, btw, if you install gold on ubuntu, it replaces ld transparently
12:44 	&lt;gw>	Ms2ger: are you sure about that? I have gold installed on my machine, and the link times seem terrible. I'd hate to think I'm already seeing this improvement!
12:45 	&lt;SimonSapin>	I’m not on Ubuntu, and `export LD=ld.gold` per https://wiki.archlinux.org/index.php/Gold_linker didn’t work
12:45 	&lt;Ms2ger>	Or it used to
12:46 	&lt;Ms2ger>	Weird
12:48 	&lt;SimonSapin>	$PATH hacks didn’t work either :/

**Comment by metajack** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[python/servo/command_base.py, line 305 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7229#-JwloIsXE5Ph3tRDEM_-)** ([raw file](https://github.com/servo/servo/blob/e0c975d040493001b67dd2e9721f2a28a0608471/python/servo/command_base.py#L305)):</sup>
Both of these are incorrect and should use the topdir instead of relative paths. We might be running mach from somewhere else.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7229)

**Comment by SimonSapin** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[python/servo/command_base.py, line 305 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7229#-JwloIsXE5Ph3tRDEM_-)** ([raw file](https://github.com/servo/servo/blob/e0c975d040493001b67dd2e9721f2a28a0608471/python/servo/command_base.py#L305)):</sup>
These paths are not for mach to interpret, they’re for Cargo in processes created with a specific current directory:
```python
subprocess.call(
            ["cargo", "build"] + opts,
            env=env, cwd=self.servo_crate())
```

… but I suppose it doesn’t hurt to make them absolute. (Done.)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7229)

**Comment by metajack** [comment]
@bors-servo r+

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7229)

**Comment by metajack** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7229)

**Comment by SimonSapin** [comment]
> I’ve run mach build successfully with this branch on a mac, where I think gold is not available. I assume that -fuse-ld=gold is ignored in that case.

Oh, well.

```
note: clang: error: invalid linker name in argument '-fuse-ld=gold'
```

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7229)

**Pull request merged**
