### PR TITLE
Fix all the Mac-specific test expectations

### PR DESCRIPTION
**Pull request by nox**
It's "mac", not "osx".

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11436)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 36 of 36 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11436)*

**Comment by jgraham** [comment]
So I suspect this isn't going to pass CI because it actually changes a lot of expectations. But if you want we can try to land it and confirm that way?

**Comment by nox** [comment]
Sure.

@bors-servo try

**Comment by nox** [comment]
@bors-servo retry

Homu dying again it seems.

**Comment by jgraham** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11436)*

**Pull request merged**
