### PR TITLE
Derive Debug for FontGroup and its components

### PR DESCRIPTION
**Pull request by antrik**
In order to enable `#[derive(Debug)]` on HashMap (used by Font), this also requires applying trait bounds to HashMap itself (rather than just the impl) -- which is probably better anyway.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8908)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you for your PR!

**Comment by antrik** [comment]
This is bad: The macos platform implementation ultimately goes back to core_font::CTFont, which doesn't implement Debug... Not sure how to deal with this. Implement it in core_font, and depend on the updated version? (This is kinda getting out of hand, for a simple debug convenience feature...) Or maybe just add a dummy impl Debug for CTFont for now in the files using it?...

**Comment by antrik** [comment]
Also, don't know how to test the macos build without running that system myself?...

**Comment by jdm** [comment]
We can run `@bors-servo: try` to run a sample compile against linux, OS X, and android, if necessary.

**Comment by antrik** [comment]
I added the platform/macos bits. It's entirely untested, though -- let's see what the build bot makes of it...

**Comment by antrik** [comment]
Looks good so far... Will it actually build on MacOS? :-)

**Comment by KiChjang** [comment]
```
Ran 3733 tests finished in 883.0 seconds.
  • 3732 ran as expected. 708 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected OK] /_mozilla/mozilla/webgl/bufferData.html
  │ 
  │ thread 'WebGLTask' panicked at 'assertion failed: gl::get_error() == gl::NO_ERROR', /Users/servo/buildbot/slave/mac-rel-wpt/build/components/canvas/webgl_paint_task.rs:175
  │ stack backtrace:
  │    1:        0x11088b9b8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x11088da7f - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x11088d522 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x1108793c6 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x10fc055f4 - sys_common::unwind::begin_unwind::begin_unwind::h11202042830455691448
  │    6:        0x10fc3d587 - webgl_paint_task::_<impl>::handle_webgl_message::h893d69423c857c2b98r
  │    7:        0x10fc3fe0e - sys_common::unwind::try::try_fn::try_fn::h16236525448532473054
  │    8:        0x11088adf8 - __rust_try
  │    9:        0x110887efe - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   10:        0x10fc40ed1 - boxed::_<impl>::call_box::call_box::h2899970556402076055
  │   11:      ALERT: RESULT: ["/_mozilla/mozilla/webgl/bufferData.html",0,null,null,[["bufferData and bufferSubData input array type check (issue #6791)",0,null,null]]]
  │   0x11088cd0d - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   12:     0x7fff8416a059 - _pthread_body
  └   13:     0x7fff84169fd6 - _pthread_start
```

**Comment by antrik** [comment]
I'm have a hard time believing this run-time test failure is related to my changes. They shouldn't affect run time at all. (Unless there is some compiler bug or something...) It builds cleanly on all platforms, so it's good to go I'd say.

**Comment by antrik** [comment]
BTW, the needs-rebuild label is outdated -- I already pushed a rebased version...

**Comment by KiChjang** [comment]
@antrik your PR compiles fine right now, it's just the intermittents that's causing an issue.

**Comment by Ms2ger** [comment]
@bors-servo retry
* #8931

**Comment by Ms2ger** [comment]
Doh.

@bors-servo try- force r+

**Pull request closed without merging**
