### PR TITLE
style: Unify how servo and Gecko handle UA sheets.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18502)

### CODE REVIEW

**Comment by emilio** [comment]
On top of #18501, only last commit needs review.

**Comment by emilio** [comment]
@bors-servo try

 * Fixed unit tests

**Comment by emilio** [comment]
@bors-servo retry

 * IOError: CRC check while downloading rustc?

**Comment by jdm** [comment]
Every other build was green, so no need to keep retrying this.

**Comment by emilio** [comment]
Rebased on top of #18501. r? @SimonSapin

**Comment by SimonSapin** [comment]
r+

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/document.rs, line 2402 at r1](https://reviewable.io:443/reviews/servo/servo/18502#-Ku0VZZ0uH88X0fA5I2I:-Ku0VZZ0uH88X0fA5I2J:bl0ltli) ([raw file](https://github.com/servo/servo/blob/c495a15bea8aa01c3d0a2492e3524bf69f9fe5a2/components/script/dom/document.rs#L2402)):*
> ```Rust
>         let insertion_point = stylesheets.iter().find(|&(sheet_in_doc, _origin)| {
>             owner.upcast::<Node>().is_before(sheet_in_doc.owner.upcast())
>         }).map(|(sheet, _origin)| sheet).cloned();
> ```

Nit: this might be nicer with `map` before `find`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18502#-:-Ku0aV4F8TrdxiX3Uf1j:b32wu6)*

**Comment by emilio** [comment]
Thanks for the review simon!

**Comment by emilio** [comment]
@bors-servo retry

 * Download failed (500): Internal Server Error - https://s3.amazonaws.com/rust-lang-ci/rustc-builds/d93036a043dbd19f394ad320313bdbe81644f121/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz

**Pull request merged**
