### PR TITLE
Run test-tidy with CPP files check on Windows

### PR DESCRIPTION
**Pull request by paulrouget**

### CODE REVIEW

**Comment by jdm** [comment]
Sigh. We do a [sparse checkout](https://github.com/servo/servo/blob/100ff06804089c803bad0fe2d6a0fc0375d559bc/etc/taskcluster/decision_task.py#L172) on windows right now:
```
C:\Users\task_1573196648\repo>type .git\info\sparse-checkout 
/*
!/tests/wpt/metadata
!/tests/wpt/mozilla
!/tests/wpt/webgl
!/tests/wpt/web-platform-tests
/tests/wpt/web-platform-tests/tools
```
And this causes test-tidy to fail:
```
C:\Users\task_1573196648\repo>python mach test-tidy --force-cpp 
Fatal: metadata path C:\Users\task_1573196648\repo\tests\wpt\metadata does not exist
```

**Comment by paulrouget** [comment]
Adding `--no-wpt`.

**Comment by jdm** [comment]
```
C:\Users\task_1573730667\repo>python mach test-tidy --force-cpp --no-wpt 

Checking the config file...

.\servo-tidy.toml:52: ignored file './tests/wpt/metadata/MANIFEST.json' doesn't exist

.\servo-tidy.toml:53: ignored file './tests/wpt/mozilla/meta/MANIFEST.json' doesn't exist

.\servo-tidy.toml:55: ignored file './tests/wpt/mozilla/tests/mozilla/resources/brotli.py' doesn't exist

.\servo-tidy.toml:56: ignored file './tests/wpt/webgl/meta/MANIFEST.json' doesn't exist

.\servo-tidy.toml:59: ignored file './tests/wpt/webgl/tests' doesn't exist

.\servo-tidy.toml:61: ignored file './tests/wpt/webgl/tools/import-conformance-tests.py' doesn't exist

.\servo-tidy.toml:64: ignored file './tests/wpt/mozilla/tests/css/fonts' doesn't exist

.\servo-tidy.toml:65: ignored file './tests/wpt/mozilla/tests/css/pre_with_tab.html' doesn't exist

.\servo-tidy.toml:66: ignored file './tests/wpt/mozilla/tests/mozilla/textarea_placeholder.html' doesn't exist

Checking the wpt manifest file...

C:\Users\task_1573730667\repo\tests\wpt\include.ini:4: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\2dcontext

C:\Users\task_1573730667\repo\tests\wpt\include.ini:5: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\cors

C:\Users\task_1573730667\repo\tests\wpt\include.ini:6: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css

C:\Users\task_1573730667\repo\tests\wpt\include.ini:7: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\compositing

C:\Users\task_1573730667\repo\tests\wpt\include.ini:8: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\CSS2

C:\Users\task_1573730667\repo\tests\wpt\include.ini:9: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-align

C:\Users\task_1573730667\repo\tests\wpt\include.ini:10: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-animations

C:\Users\task_1573730667\repo\tests\wpt\include.ini:11: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-backgrounds

C:\Users\task_1573730667\repo\tests\wpt\include.ini:12: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-color

C:\Users\task_1573730667\repo\tests\wpt\include.ini:13: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-conditional

C:\Users\task_1573730667\repo\tests\wpt\include.ini:14: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-flexbox

C:\Users\task_1573730667\repo\tests\wpt\include.ini:15: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-fonts

C:\Users\task_1573730667\repo\tests\wpt\include.ini:16: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-images

C:\Users\task_1573730667\repo\tests\wpt\include.ini:17: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-paint-api

C:\Users\task_1573730667\repo\tests\wpt\include.ini:18: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-style-attr

C:\Users\task_1573730667\repo\tests\wpt\include.ini:19: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-text

C:\Users\task_1573730667\repo\tests\wpt\include.ini:20: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-text\i18n

C:\Users\task_1573730667\repo\tests\wpt\include.ini:21: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-text-decor

C:\Users\task_1573730667\repo\tests\wpt\include.ini:22: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-transforms

C:\Users\task_1573730667\repo\tests\wpt\include.ini:23: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-transitions

C:\Users\task_1573730667\repo\tests\wpt\include.ini:24: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-ui

C:\Users\task_1573730667\repo\tests\wpt\include.ini:25: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-values

C:\Users\task_1573730667\repo\tests\wpt\include.ini:26: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\css-variables

C:\Users\task_1573730667\repo\tests\wpt\include.ini:27: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\cssom

C:\Users\task_1573730667\repo\tests\wpt\include.ini:28: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\cssom-view

C:\Users\task_1573730667\repo\tests\wpt\include.ini:29: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\filter-effects

C:\Users\task_1573730667\repo\tests\wpt\include.ini:30: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\geometry

C:\Users\task_1573730667\repo\tests\wpt\include.ini:31: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\mediaqueries

C:\Users\task_1573730667\repo\tests\wpt\include.ini:32: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\css\selectors

C:\Users\task_1573730667\repo\tests\wpt\include.ini:33: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\custom-elements

C:\Users\task_1573730667\repo\tests\wpt\include.ini:34: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\dom

C:\Users\task_1573730667\repo\tests\wpt\include.ini:35: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\domparsing

C:\Users\task_1573730667\repo\tests\wpt\include.ini:36: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\encoding

C:\Users\task_1573730667\repo\tests\wpt\include.ini:37: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\eventsource

C:\Users\task_1573730667\repo\tests\wpt\include.ini:38: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\fetch

C:\Users\task_1573730667\repo\tests\wpt\include.ini:39: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\FileAPI

C:\Users\task_1573730667\repo\tests\wpt\include.ini:40: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\fullscreen

C:\Users\task_1573730667\repo\tests\wpt\include.ini:41: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\gamepad

C:\Users\task_1573730667\repo\tests\wpt\include.ini:42: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\hr-time

C:\Users\task_1573730667\repo\tests\wpt\include.ini:43: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html

C:\Users\task_1573730667\repo\tests\wpt\include.ini:44: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\cross-origin-embedder-policy

C:\Users\task_1573730667\repo\tests\wpt\include.ini:45: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\cross-origin-opener-policy

C:\Users\task_1573730667\repo\tests\wpt\include.ini:46: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics

C:\Users\task_1573730667\repo\tests\wpt\include.ini:47: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\document-metadata

C:\Users\task_1573730667\repo\tests\wpt\include.ini:48: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\document-metadata\the-meta-element

C:\Users\task_1573730667\repo\tests\wpt\include.ini:49: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\document-metadata\the-meta-element\pragma-directives

C:\Users\task_1573730667\repo\tests\wpt\include.ini:50: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\document-metadata\the-meta-element\pragma-directives\attr-meta-http-equiv-refresh

C:\Users\task_1573730667\repo\tests\wpt\include.ini:51: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\embedded-content

C:\Users\task_1573730667\repo\tests\wpt\include.ini:52: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\embedded-content\media-elements

C:\Users\task_1573730667\repo\tests\wpt\include.ini:53: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\embedded-content\media-elements\track

C:\Users\task_1573730667\repo\tests\wpt\include.ini:54: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\embedded-content\media-elements\track\track-element

C:\Users\task_1573730667\repo\tests\wpt\include.ini:55: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\embedded-content\media-elements\track\track-element\cors

C:\Users\task_1573730667\repo\tests\wpt\include.ini:56: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\scripting-1

C:\Users\task_1573730667\repo\tests\wpt\include.ini:57: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\scripting-1\the-script-element

C:\Users\task_1573730667\repo\tests\wpt\include.ini:58: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\scripting-1\the-script-element\json-module

C:\Users\task_1573730667\repo\tests\wpt\include.ini:59: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\html\semantics\scripting-1\the-script-element\module

C:\Users\task_1573730667\repo\tests\wpt\include.ini:60: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\js

C:\Users\task_1573730667\repo\tests\wpt\include.ini:61: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\navigation-timing

C:\Users\task_1573730667\repo\tests\wpt\include.ini:62: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\offscreen-canvas

C:\Users\task_1573730667\repo\tests\wpt\include.ini:63: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\old-tests

C:\Users\task_1573730667\repo\tests\wpt\include.ini:64: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\old-tests\submission

C:\Users\task_1573730667\repo\tests\wpt\include.ini:65: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\performance-timeline

C:\Users\task_1573730667\repo\tests\wpt\include.ini:66: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\permissions

C:\Users\task_1573730667\repo\tests\wpt\include.ini:67: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\quirks

C:\Users\task_1573730667\repo\tests\wpt\include.ini:68: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\referrer-policy

C:\Users\task_1573730667\repo\tests\wpt\include.ini:69: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\referrer-policy\gen

C:\Users\task_1573730667\repo\tests\wpt\include.ini:70: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\referrer-policy\gen\srcdoc-inherit.http-rp

C:\Users\task_1573730667\repo\tests\wpt\include.ini:71: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\referrer-policy\gen\srcdoc-inherit.meta

C:\Users\task_1573730667\repo\tests\wpt\include.ini:72: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\referrer-policy\gen\srcdoc.meta

C:\Users\task_1573730667\repo\tests\wpt\include.ini:73: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\resource-timing

C:\Users\task_1573730667\repo\tests\wpt\include.ini:74: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\subresource-integrity

C:\Users\task_1573730667\repo\tests\wpt\include.ini:75: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\touch-events

C:\Users\task_1573730667\repo\tests\wpt\include.ini:76: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\uievents

C:\Users\task_1573730667\repo\tests\wpt\include.ini:77: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\url

C:\Users\task_1573730667\repo\tests\wpt\include.ini:78: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\wasm

C:\Users\task_1573730667\repo\tests\wpt\include.ini:79: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\webaudio

C:\Users\task_1573730667\repo\tests\wpt\include.ini:80: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\WebCryptoAPI

C:\Users\task_1573730667\repo\tests\wpt\include.ini:81: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\webgl

C:\Users\task_1573730667\repo\tests\wpt\include.ini:82: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\webvr

C:\Users\task_1573730667\repo\tests\wpt\include.ini:83: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\webxr

C:\Users\task_1573730667\repo\tests\wpt\include.ini:84: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\WebIDL

C:\Users\task_1573730667\repo\tests\wpt\include.ini:85: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\webmessaging

C:\Users\task_1573730667\repo\tests\wpt\include.ini:86: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\websockets

C:\Users\task_1573730667\repo\tests\wpt\include.ini:87: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\webstorage

C:\Users\task_1573730667\repo\tests\wpt\include.ini:88: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\workers

C:\Users\task_1573730667\repo\tests\wpt\include.ini:89: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\workers\modules

C:\Users\task_1573730667\repo\tests\wpt\include.ini:90: Path in manifest was not found: C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\xhr

Checking directories for correct file extensions...
Error running mach:

    ['test-tidy', '--force-cpp', '--no-wpt']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

IOError: [Errno 2] No such file or directory: u'C:\\Users\\task_1573730667\\repo\\tests\\wpt\\web-platform-tests\\lint.whitelist'

  File "C:\Users\task_1573730667\repo\python\servo\testing_commands.py", line 339, in test_tidy
    tidy_failed = tidy.scan(not all_files, not no_progress, stylo=stylo)
  File "C:\Users\task_1573730667\repo\python\tidy\servo_tidy\tidy.py", line 1131, in scan
    for error in errors:
  File "C:\Users\task_1573730667\repo\python\tidy\servo_tidy\tidy.py", line 1102, in run_lint_scripts
    for error in runner.check():
  File "C:\Users\task_1573730667\repo\python\tidy\servo_tidy\tidy.py", line 1083, in check
    for error in lint.run():
  File "./python/servo/lints/wpt_lint.py", line 41, in run
    returncode = lint.lint(file_dir, list(files), output_format="json")
  File "C:\Users\task_1573730667\repo\tests\wpt\web-platform-tests\tools\lint\lint.py", line 878, in lint
```

**Comment by paulrouget** [comment]
I will make it so tidy -no-wpt doesn't scan the wpt manifest and doesn't check the existence of the wpt files in the config files.

**Comment by jdm** [comment]
@bors-servo retry
* #24779

**Comment by jdm** [comment]
`Error: can't find suitable clang-format version. Required with --force-cpp.`

**Comment by paulrouget** [comment]
```
CalledProcessError: Command '[u'clang-format.exe', u'--version']' returned non-zero exit status 1
```

**Comment by paulrouget** [comment]
Added some logs.

@bors-servo try

**Comment by jdm** [comment]
Use try=windows next time, please.

**Comment by paulrouget** [comment]
> Use try=windows next time, please.

Oops. Right.

> `CalledProcessError: Command '[u'where', u'clang-format.exe']' returned non-zero exit status 1`

llvm is in the path. clang-format should be in there. For some reason it doesn't find it. Gonna list the content of the directory to make sure it's installed.

**Comment by paulrouget** [comment]
```
dir C:\Users\task_1574163984\repo\.servo\msvc-dependencies\llvm\8.0.0\bin
The system cannot find the path specified.
```

That's consistent with `where` and `clang-format.exe` failing.

@jdm isn't that where llvm is supposed to be installed? At least that where PATH is pointing to. Also - is there a better way to debug these than running the TC try script?

**Comment by jdm** [comment]
This is almost certainly because the msvc-dependencies packages aren't downloaded until the build command is used. If you run the formatting command after the build, I would expect it to work.

**Comment by jdm** [comment]
@bors-servo retry
* #24814 #24815 #24726

**Comment by jdm** [comment]
@bors-servo retry
* #13480 #24820

**Pull request merged**
