### PR TITLE
Implement file reading task source

### PR DESCRIPTION
**Pull request by KiChjang**
Partial #7959.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11645)

### CODE REVIEW

**Comment by Ms2ger** [comment]
This appears to break `FileReader` in workers.

**Comment by KiChjang** [comment]
Argh, I can't seem to figure out how to implement task sources for workers. Any hints?

**Comment by jdm** [comment]
I've added support for worker task sources in #12448.

**Pull request closed without merging**
