### PR TITLE
Extend the developer tools support

### PR DESCRIPTION
**Pull request by hsvalava**
Initial version of support for logging HTTP requests and responses - https://github.com/servo/servo/wiki/More-developer-tools-student-project
cc @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5920)

### CODE REVIEW

**Comment by jdm** [comment]
I'll review this ASAP; meanwhile, be sure to address these failures:
```
$ ./mach test-tidy
components/devtools/lib.rs:302: trailing whitespace
components/devtools/lib.rs:375: trailing whitespace
components/devtools/lib.rs:377: trailing whitespace
components/devtools/actors/network_event.rs:85: trailing whitespace
components/devtools/actors/network_event.rs:94: trailing whitespace
components/devtools/actors/network_event.rs:131: trailing whitespace
components/devtools/actors/network_event.rs:139: trailing whitespace
components/net/http_loader.rs:71: trailing whitespace
components/net/http_loader.rs:208: trailing whitespace
```

**Comment by jdm** [comment]
This is looking great! Be sure to run `./mach test-unit` too and fix up any failures there due to the changes to LoadData::new.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/devtools/actors/network_event.rs @ r4
- components/devtools/Cargo.toml @ r1
- components/devtools/lib.rs @ r4
- components/devtools_traits/Cargo.toml @ r1
- components/devtools_traits/lib.rs @ r2
- components/net/Cargo.toml @ r3
- components/net/http_loader.rs @ r3
- components/net/image_cache_task.rs @ r6
- components/net/lib.rs @ r2
- components/net/resource_task.rs @ r1
- components/net_traits/Cargo.toml @ r3
- components/net_traits/lib.rs @ r3
- components/script/dom/xmlhttprequest.rs @ r3
- components/script/script_task.rs @ r3
- components/servo/Cargo.lock @ r5
- components/servo/lib.rs @ r1

---

<sup>**[components/devtools/actors/network_event.rs, line 9 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKVbmfqGoxV5bpItKq)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/devtools/actors/network_event.rs#L9)):</sup>
These shouldn't be necessary in this file.

---

<sup>**[components/devtools/actors/network_event.rs, line 46 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKUd-LGcuVC6vJZndj)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/devtools/actors/network_event.rs#L46)):</sup>
isXHR and private can be bool values.

---

<sup>**[components/devtools/actors/network_event.rs, line 134 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKUI1mgvBJyUEb9B04)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/devtools/actors/network_event.rs#L134)):</sup>
add_request

---

<sup>**[components/devtools/actors/network_event.rs, line 141 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKUJ6OrvxEC1Kqhgr0)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/devtools/actors/network_event.rs#L141)):</sup>
add_response

---

<sup>**[components/devtools/Cargo.toml, line 23 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKVPHA7VIk-85rOgp8)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/devtools/Cargo.toml#L23)):</sup>
No need for a separate section. These can probably also just use "*" instead of specific versions.

---

<sup>**[components/devtools_traits/Cargo.toml, line 18 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKVj1ogi5_V3dlX4MG)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/devtools_traits/Cargo.toml#L18)):</sup>
Just use "*" here.

---

<sup>**[components/net/http_loader.rs, line 210 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKWF8xynMbcYQm5p38)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/net/http_loader.rs#L210)):</sup>
Let's use
if let Some(ref chan) = devtools_chan {
    let request_id = ...;
    let net_event = ...;
    chan.send(...);
}

---

<sup>**[components/net/http_loader.rs, line 246 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKWeHRWs5wluh-POxd)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/net/http_loader.rs#L246)):</sup>
Let's send the message right above this line, since we set the Content-Length header in the previous section.

---

<sup>**[components/net/http_loader.rs, line 346 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKWp_2fN8-B9FctXuL)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/net/http_loader.rs#L346)):</sup>
Seems like it to me!

---

<sup>**[components/net/http_loader.rs, line 348 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKX-AJSVGCe9LLcV9z)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/net/http_loader.rs#L348)):</sup>
Same if let here as above.

---

<sup>**[components/script/dom/xmlhttprequest.rs, line 517 \[r6\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoKXX9JPa_rAHU2fCHz)** ([raw file](https://github.com/servo/servo/blob/ab61fa7303ffc6f08e15bbdb219487f75c7f0a0e/components/script/dom/xmlhttprequest.rs#L517)):</sup>
let global = self.global.root();
let pipeline = global.r().pipeline();

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5920)

**Comment by jdm** [comment]
Reviewed files:
- components/net/http_loader.rs @ r7

---

<sup>**[components/net/http_loader.rs, line 209 \[r7\]](https://reviewable.io:443/reviews/servo/servo/5920#-JoWeeiJb0pXH0tEbEhx)** ([raw file](https://github.com/servo/servo/blob/27fad32b0887e0b9328704faaa4802c6fdb79b90/components/net/http_loader.rs#L209)):</sup>
nit: make all of these line up with the load_data on the first line, and remove the trailing whitespace after `load_data.data.clone()`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5920)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5920)

**Comment by jdm** [comment]
Reviewed files:
- components/devtools/actors/network_event.rs @ r9
- components/devtools/Cargo.toml @ r9
- components/devtools/lib.rs @ r9
- components/devtools_traits/Cargo.toml @ r9
- components/net/http_loader.rs @ r9
- components/script/dom/xmlhttprequest.rs @ r9
- tests/unit/net/data_loader.rs @ r9
- tests/unit/net/resource_task.rs @ r9

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5920)

**Comment by jdm** [comment]
Yay! I'll make sure this gets merged now; thanks!

**Comment by hsvalava** [comment]
Sorry about that intermediate update, didn't intend to push just then. I think all the review comments should be addressed now. ./mach test-unit reports no fails. Thank you! :)

**Comment by hsvalava** [comment]
Ah, thank you Josh! :)

**Comment by jdm** [comment]
Closed in favour of #5947 which I rebased to reduce the number of extra commits.

**Pull request closed without merging**
