### PR TITLE
Sanitise web fonts

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12938)

### CODE REVIEW

**Comment by nox** [comment]
@metajack Seems like it still fails on Windows.

**Comment by nox** [comment]
https://github.com/khaledhosny/ots/issues/112

**Comment by nox** [comment]
https://github.com/servo/fontsan/pull/13

**Comment by nox** [comment]
@bors-servo r=larsbergstrom

Silly libc issue after a libc bump in a separate PR.

**Comment by jdm** [comment]
@bors-servo: retry
* #12592 #11618

**Pull request merged**
