### PR TITLE
Conforming image loading to HTML5 standards

### PR DESCRIPTION
**Pull request by akhan7**
We attempt to conform the image loading on Servo browser to conform to the standards defined in HTML5

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10134)

### CODE REVIEW

**Comment by KiChjang** [comment]
Lots of tidy failures reported by Travis CI:
```
Checking files for tidiness...
./components/script/dom/htmlimageelement.rs:1: incorrect license
./components/script/dom/htmlimageelement.rs:160: Line is longer than 120 characters
./components/script/dom/htmlimageelement.rs:161: Line is longer than 120 characters
./components/script/dom/htmlimageelement.rs:35: use statement is not in alphabetical order
	expected: util::str::{DOMString, LengthOrPercentageOrAuto}
	found: heapsize::{HeapSizeOf}
./components/script/dom/htmlimageelement.rs:36: missing space after ,
./components/script/dom/htmlimageelement.rs:37: missing space before {
./components/script/dom/htmlimageelement.rs:43: missing space after ,
./components/script/dom/htmlimageelement.rs:160: missing space after ,
./components/script/dom/htmlimageelement.rs:160: missing space after ,
./components/script/dom/htmlimageelement.rs:160: missing space after ,
./components/script/dom/htmlimageelement.rs:160: missing space after :
./components/script/dom/htmlimageelement.rs:160: missing space after :
./components/script/dom/htmlimageelement.rs:160: missing space after :
./components/script/dom/htmlimageelement.rs:160: missing space before {
./components/script/dom/htmlimageelement.rs:160: missing space before }
./components/script/dom/htmlimageelement.rs:160: missing space after {
./components/script/dom/htmlimageelement.rs:161: missing space after ,
./components/script/dom/htmlimageelement.rs:161: missing space after ,
./components/script/dom/htmlimageelement.rs:161: missing space after ,
./components/script/dom/htmlimageelement.rs:161: missing space after :
./components/script/dom/htmlimageelement.rs:161: missing space after :
./components/script/dom/htmlimageelement.rs:161: missing space after :
./components/script/dom/htmlimageelement.rs:161: missing space before {
./components/script/dom/htmlimageelement.rs:161: missing space before }
./components/script/dom/htmlimageelement.rs:161: missing space after {
```

You can run `./mach test-tidy`, optionally with a --faster flag, to check whether your coding style passes our standards.

**Comment by jdm** [comment]
The substance of the changes look correct to me! We just need to fix up the stylistic nits and address the tests that will now fail.

---

Reviewed 1 of 2 files at r7, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlimageelement.rs, line 1 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYdH_vRNNplThSG-6a:-KDYdH_vRNNplThSG-6b:-17289934) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L1)):*
We can remove this :)

---

*[components/script/dom/htmlimageelement.rs, line 5 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYdIoxZDqkPuP7EDUq:-KDYdIoxZDqkPuP7EDUr:1423188035) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L5)):*
Let's remove this also.

---

*[components/script/dom/htmlimageelement.rs, line 36 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYdOC8bC3jZi0wrVoe:-KDYdOC9BaFMp8gfEwT-:1810866088) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L36)):*
nit: add a newline above this. Let's also add this comment: `/// https://html.spec.whatwg.org/multipage/#the-img-element:img-req-state`

---

*[components/script/dom/htmlimageelement.rs, line 48 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYdfSrctjGvBpNcMAs:-KDYdfSrctjGvBpNcMAt:851463310) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L48)):*
Let's remove all the DOMRefCells here and put them around the ImageRequest members of HTMLImageElement instead.

---

*[components/script/dom/htmlimageelement.rs, line 55 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYdpMTtCW1bBs_0U5b:-KDYdpMU-eQADnHz-5zg:-1773341784) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L55)):*
We can remove these comments now.

---

*[components/script/dom/htmlimageelement.rs, line 57 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYds9v7rKEp95TSVTc:-KDYds9v7rKEp95TSVTd:-2100305043) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L57)):*
nit: current_request and pending_request

---

*[components/script/dom/htmlimageelement.rs, line 81 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYdzF8DkvtyQqUEgGX:-KDYdzF9QSWskzr1Ue71:-750458973) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L81)):*
nit: let's remove this extra newline.

---

*[components/script/dom/htmlimageelement.rs, line 136 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYe9davWbZ5OgDgdF6:-KDYe9db5gyi8rWaptPf:1321300438) ([raw file](https://github.com/servo/servo/blob/a4251c832d605a02d6c82fc188d1746367599e59/components/script/dom/htmlimageelement.rs#L136)):*
Let's add this newline back.

---

*[components/script/dom/htmlimageelement.rs, line 159 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYeCdtOJzJJV9IQTgv:-KDYeCdtOJzJJV9IQTgw:-411056460) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L159)):*
We can remove these now.

---

*[components/script/dom/htmlimageelement.rs, line 160 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYeEl4iGjDVpR-r9Bl:-KDYeEl4iGjDVpR-r9Bm:-1324251013) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L160)):*
This should be State::Unavailable according to https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element:img-none . Let's also split this up on multiple lines like:
```rust
current_request: ImageRequest {
    state: ...,
    url: ...,
},

---

*[components/script/dom/htmlimageelement.rs, line 163 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYeP1fAwld2erq-SaO:-KDYeP1fAwld2erq-SaP:-574315751) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L163)):*
These can be removed.

---

*[components/script/dom/htmlimageelement.rs, line 247 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYfBcTUcDapujkB82G:-KDYfBcTUcDapujkB82H:-1070566046) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L247)):*
This link should be https://html.spec.whatwg.org/multipage/#dom-img-crossorigin

---

*[components/script/dom/htmlimageelement.rs, line 248 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYeplPx9DI5DkWEXUl:-KDYeplPx9DI5DkWEXUm:-209672990) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L248)):*
This should be make_enumerated_getter in accordance with https://html.spec.whatwg.org/multipage/infrastructure.html#cors-settings-attribute

---

*[components/script/dom/htmlimageelement.rs, line 249 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYfFu8NXSJ6ZNIyUnz:-KDYfFu8NXSJ6ZNIyUo-:1713165213) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L249)):*
This link should be https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-crossorigin

---

*[components/script/dom/htmlimageelement.rs, line 257 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYfQxfj9zwSwlxlE78:-KDYfQxfj9zwSwlxlE79:-117588050) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L257)):*
Let's remove this extra newline.

---

*[components/script/dom/htmlimageelement.rs, line 312 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDYfTHOwJiiRC9BzJSb:-KDYfTHOwJiiRC9BzJSc:-117588050) ([raw file](https://github.com/servo/servo/blob/23ad86de8c2ed6b40bfe0e50022e1c8bc9d70a5c/components/script/dom/htmlimageelement.rs#L312)):*
Let's remove this extra newline.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10134#-:-KDYfb8zO2L3IueN9XuZ:-1879299602)*
<!-- Sent from Reviewable.io -->

**Comment by jdm** [comment]
Test result changes that need to be addressed:
```
  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLImageElement interface: attribute crossOrigin

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLImageElement interface: document.createElement("img") must inherit property "crossOrigin" with the proper type (4)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLImageElement interface: new Image() must inherit property "crossOrigin" with the proper type (4)

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: setAttribute() to "anonymous" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: setAttribute() to "use-credentials" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to " \\0\\x01\\x02\\x03\\x04\\x05\\x06\\x07 \\b\\t\\n\\v\\f\\r\\x0e\\x0f \\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17 \\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f  foo " followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to 7 followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to 1.5 followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to true followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to false followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to object "[object Object]" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to NaN followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to Infinity followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to -Infinity followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "\\0" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to object "test-toString" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to object "test-valueOf" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "anonymous" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "xanonymous" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "anonymous\\0" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "nonymous" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "ANONYMOUS" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "use-credentials" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "xuse-credentials" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "use-credentials\\0" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  └ PASS [expected FAIL] img.crossOrigin: IDL set to "se-credentials" followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-embedded.html:
  │ FAIL [expected PASS] img.crossOrigin: IDL set to null followed by IDL get
  │   → assert_equals: expected (object) null but got (string) "null"
  │ 
  │ ReflectionHarness.test/<@http://web-platform.test:8000/html/dom/new-harness.js:6:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ ReflectionHarness.test@http://web-platform.test:8000/html/dom/new-harness.js:5:1
  │ ReflectionTests.doReflects/<@http://web-platform.test:8000/html/dom/reflection.js:750:1
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ ReflectionHarness.run@http://web-platform.test:8000/html/dom/new-harness.js:14:3
  │ ReflectionTests.doReflects@http://web-platform.test:8000/html/dom/reflection.js:737:1
  │ ReflectionTests.reflects/<@http://web-platform.test:8000/html/dom/reflection.js:577:9
  │ ReflectionHarness.testWrapper@http://web-platform.test:8000/html/dom/original-harness.js:93:3
  │ ReflectionTests.reflects@http://web-platform.test:8000/html/dom/reflection.js:576:5
  └ @http://web-platform.test:8000/html/dom/reflection.js:812:9
```
These can be run locally via `./mach test-wpt tests/wpt/web-platform-tests/html/dom/reflection-embedded.html` (eg).

**Comment by jdm** [comment]
Remember to run `./mach test-tidy` and fix the results. I suspect that there are new test failures due to the currentSrc changes; be sure that you've run those tests again.
-S-awaiting-review +S-needs-code-changes +S-fails-tidy 

---

Reviewed 1 of 2 files at r10, 2 of 2 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlimageelement.rs, line 319 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDgH1IQlJhDnLYBtYUA:-KDgH1IQlJhDnLYBtYUB:-907908853) ([raw file](https://github.com/servo/servo/blob/db72a715695e3ae0298b49aa93986a97dd83b0d0/components/script/dom/htmlimageelement.rs#L319)):*
nit: no need for the {} here.

---

*[components/script/dom/htmlimageelement.rs, line 321 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDgGy5_emOysJ0uyN6p:-KDgGy5aRnuL61ss_8Id:781977050) ([raw file](https://github.com/servo/servo/blob/db72a715695e3ae0298b49aa93986a97dd83b0d0/components/script/dom/htmlimageelement.rs#L321)):*
nit: remove this newline.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10134#-:-KDgHEb7xipQlBnZqKEa:-188731525)*

**Comment by jdm** [comment]
-S-fails-tidy -S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/htmlimageelement.rs, line 155 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10134#-KDvEOLGZ7oCiyRBYR-t:-KDvEOLHcXfcmyI4ZP9v:-1694521581) ([raw file](https://github.com/servo/servo/blob/87378a8bb954ac2220e60748a97193825c1c3e1c/components/script/dom/htmlimageelement.rs#L155)):*
The previous version that had each field on a separate line was much easier to read.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10134#-:-KDvEcfGWTYg573uk_8y:900620026)*

**Comment by jdm** [comment]
There are still unaddressed comments from previous reviews, in case that's unclear. Click on the reviewable link to see them.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r15.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10134#-:-KDy0kIYCJ5tWQnhy1MY:-1515262541)*

**Comment by sneha1302** [comment]
Hi Josh ,

I am unable to figure out what is still pending from the link. 
Could you kindly help .

Thanks a lot 
-Sneha

**Comment by jdm** [comment]
@sneha1302 If you visit https://reviewable.io/reviews/servo/servo/10134, there are three comments left by me that say "In progress" in their title.

**Comment by sneha1302** [comment]
Alright , thanks Josh . Have only resolved 2 out of the 3 comments.

**Comment by jdm** [comment]
TravisCI reports that `./mach test-tidy` isn't passing any more.
-S-awaiting-review +S-needs-code-changes +S-fails-tidy 

---

Reviewed 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10134#-:-KE-BbHrnnYqidMaliAa:-771796403)*

**Comment by sneha1302** [comment]
thanks josh , have fixed tidy error.

**Comment by jdm** [comment]
There were a bunch of changes here which I found confusing, and I assume they were unintentional. Please be more careful when addressing review comments in the future?
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 4 files at r18, 1 of 1 files at r19.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlimageelement.rs, line 250 \[r16\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4sTI0XOHTi1rXronm:-KF4sTI0XOHTi1rXronn:753395594) ([raw file](https://github.com/servo/servo/blob/5b4928747def7fab001b5982c7e22fdde3a74b7d/components/script/dom/htmlimageelement.rs#L250)):*
Why this change?

---

*[components/script/dom/htmlimageelement.rs, line 57 \[r19\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4t8HW5Sno4gDr3iLB:-KF4t8HW5Sno4gDr3iLC:-1704270815) ([raw file](https://github.com/servo/servo/blob/4d0e1c7d068bb5b96e08691bbaaf9c6187051fcc/components/script/dom/htmlimageelement.rs#L57)):*
We should remove these comments.

---

*[components/script/dom/htmlimageelement.rs, line 84 \[r19\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4t6a0mNAtoLgu86yp:-KF4t6a1jeELg4RcVWyb:781977050) ([raw file](https://github.com/servo/servo/blob/4d0e1c7d068bb5b96e08691bbaaf9c6187051fcc/components/script/dom/htmlimageelement.rs#L84)):*
nit: remove this newline.

---

*[components/script/dom/htmlimageelement.rs, line 161 \[r19\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4shZNHzOeNvFqLDmA:-KF4shZNHzOeNvFqLDmB:-279506153) ([raw file](https://github.com/servo/servo/blob/4d0e1c7d068bb5b96e08691bbaaf9c6187051fcc/components/script/dom/htmlimageelement.rs#L161)):*
Please remove these lines.

---

*[components/script/dom/htmlimageelement.rs, line 162 \[r19\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4skRiG3w5FOUJ-vx3:-KF4skRiG3w5FOUJ-vx4:-366621774) ([raw file](https://github.com/servo/servo/blob/4d0e1c7d068bb5b96e08691bbaaf9c6187051fcc/components/script/dom/htmlimageelement.rs#L162)):*
I think it's easier to read if we use:
```rust
let current = ImageRequest {
    state: ...,
    image: ...,
    ....
};
...
HTMLImageElement {
    currentrequest: DOMRefCell::new(current),
    ...
}
```

---

*[components/script/dom/htmlimageelement.rs, line 162 \[r19\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4sy1_JMP_SADdc3j4:-KF4sy1_JMP_SADdc3j5:797909732) ([raw file](https://github.com/servo/servo/blob/4d0e1c7d068bb5b96e08691bbaaf9c6187051fcc/components/script/dom/htmlimageelement.rs#L162)):*
State changed from Unavailable to CompletelyAvailable, which is incorrect.

---

*[components/script/dom/htmlimageelement.rs, line 253 \[r19\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4sWYS1C-1yo0L8N25:-KF4sWYS1C-1yo0L8N26:934979157) ([raw file](https://github.com/servo/servo/blob/4d0e1c7d068bb5b96e08691bbaaf9c6187051fcc/components/script/dom/htmlimageelement.rs#L253)):*
nit: remove this extra indentation.

---

*[components/script/dom/htmlimageelement.rs, line 263 \[r19\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4sZhfmcSR4WbshvyD:-KF4sZhfmcSR4WbshvyE:781977050) ([raw file](https://github.com/servo/servo/blob/4d0e1c7d068bb5b96e08691bbaaf9c6187051fcc/components/script/dom/htmlimageelement.rs#L263)):*
nit: remove this newline.

---

*[components/script/dom/htmlimageelement.rs, line 318 \[r19\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4sex0fMxFeuLEXlZ3:-KF4sex0fMxFeuLEXlZ4:753395594) ([raw file](https://github.com/servo/servo/blob/4d0e1c7d068bb5b96e08691bbaaf9c6187051fcc/components/script/dom/htmlimageelement.rs#L318)):*
Why this change?

---

*[components/script/dom/webidls/HTMLImageElement.webidl, line 20 \[r19\]](https://reviewable.io:443/reviews/servo/servo/10134#-KF4tFeN2UFiodMclLI-:-KF4tFeN2UFiodMclLI0:753395594) ([raw file](https://github.com/servo/servo/blob/4d0e1c7d068bb5b96e08691bbaaf9c6187051fcc/components/script/dom/webidls/HTMLImageElement.webidl#L20)):*
Why this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10134#-:-KF4tJsSvs4wHelmMs8G:-1861769604)*

**Comment by jdm** [comment]
Looks great! I'll squash the commits into one and merge them in a new PR, just to keep the process moving quickly :)
+S-needs-squash 

---

Reviewed 2 of 2 files at r20.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10134#-:-KFAEYAjII5s16F9_5gA:1930232975)*

**Comment by jdm** [comment]
Rebased in #10543.

**Pull request closed without merging**
