### PR TITLE
Bump websocket to 0.16.1

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10240)

### CODE REVIEW

**Comment by Manishearth** [comment]
Should we also un-ignore any intermittents that this may have fixed?

**Comment by jdm** [comment]
@bobthekingofegypt said they'd do so.

**Comment by Manishearth** [comment]
@bors-servo retry

 - https://github.com/servo/servo/issues/9555

**Pull request merged**
