### PR TITLE
Support pair and value iterable WebIDL bindings

### LINKED ISSUE #571: Multiple interface definitions in the same WebIDL file yield duplicate autogenerated definitions
Functions like `GetProtoObject` are duplicated for each autogenerated binding, so rustc complains.

### LINKED ISSUE #12628: Support iterable declarations in WebIDL
http://heycam.github.io/webidl/#idl-iterable
https://dxr.mozilla.org/mozilla-central/rev/78dd94ba93c77d0bba45f8e4525947629a305a41/dom/bindings/Codegen.py#2249 and CGIterableMethodGenerator and https://dxr.mozilla.org/mozilla-central/source/dom/bindings/IterableIterator.h

Blocks #11897.

### PR DESCRIPTION
**Pull request by jdm**
The actual iterator implementation and JSAPI calls related to setting up the interface are ported directly from Gecko's Codegen.py, IterableIterator.h, and IterableIterator.webidl. The changes to support multiple interfaces in one file are required because the internal iterator interface the parser generates gets associated with the original interface's WebIDL file. It seemed like a good time to address #571 in that case.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12628 and fix #571.
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12819)

### CODE REVIEW

**Comment by jdm** [comment]
I don't understand why appveyor is failing, since that error was intended to be addressed by the modification to WebIDL.py (which worked locally and on travis).

**Comment by Manishearth** [comment]
I'm not familiar enough with codegen to give this a proper review -- I understand the changes, but not enough to find any mistakes/issues/etc.

r? @Ms2ger

**Comment by KiChjang** [comment]
@nox is also a good person to review codegen.

**Comment by nox** [comment]
Reviewed 5 of 5 files at r1, 7 of 7 files at r2.
Review status: 7 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/12819#-KPIAJchF8DtqNStEjvu:-KPIAJchF8DtqNStEjvv:b-12u6e8) (no related file):*
Can you paste a diff of the generated code showing the changes of supporting multiple WebIDL interfaces in a single file?

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1749 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPI9SmB4h87k0gKyV8R:-KPI9SmB4h87k0gKyV8S:b-ngu514) ([raw file](https://github.com/servo/servo/blob/bcd85af31fe959a8180c2bf60f58c9350fc2d454/components/script/dom/bindings/codegen/CodegenRust.py#L1749)):*
> ```Python
>             return t.identifier
> 
>         def removeWrapperAndNullableTypes(types):
> ```

I don't understand what that function is for, it looks like a misnomer. My intuition is that it peels wrappers and nullable types, but then it returns an array so I don't know what it does.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2110 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPI9jgTTAC71XxGBY2R:-KPI9jgTTAC71XxGBY2S:bsyj1s3) ([raw file](https://github.com/servo/servo/blob/bcd85af31fe959a8180c2bf60f58c9350fc2d454/components/script/dom/bindings/codegen/CodegenRust.py#L2110)):*
> ```Python
>     unionStructs = (i[1] for i in sorted(unionStructs.items(), key=operator.itemgetter(0)))
> 
>     return CGImports(CGList(unionStructs, "\n\n"), [], [], [], [], imports, config, ignored_warnings=[])
> ```

Nit: could you use named arguments?

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2708 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPI9v9ni-3vF4lFmwg_:-KPI9v9ni-3vF4lFmwga:b-y6r4ku) ([raw file](https://github.com/servo/servo/blob/bcd85af31fe959a8180c2bf60f58c9350fc2d454/components/script/dom/bindings/codegen/CodegenRust.py#L2708)):*
> ```Python
>     def __init__(self, descriptor):
>         CGGetPerInterfaceObject.__init__(self, descriptor, "GetProtoObject",
>                                          "PrototypeList::ID", pub=True)
> ```

Why do we need to always expose `GetProtoObject` and `GetConstructorObject` now?

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1521 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPIBFuuSdgYGhZBvf7m:-KPIBFuvJM075HaVkYWQ:b43zomk) ([raw file](https://github.com/servo/servo/blob/85b459243e0eae19256f43ddb0f1e5f94bfc4465/components/script/dom/bindings/codegen/CodegenRust.py#L1521)):*
> ```Python
>                 "condition": PropertyDefiner.getControllingCondition(m,
>                                                                      descriptor)
>             })
> ```

So where are the magic definitions of all these methods?

---

*[components/script/dom/bindings/codegen/parser/callback-location.patch, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPIAFK7R8_dwpoUmt3U:-KPIAFK7R8_dwpoUmt3V:b-jvj80t) ([raw file](https://github.com/servo/servo/blob/bcd85af31fe959a8180c2bf60f58c9350fc2d454/components/script/dom/bindings/codegen/parser/callback-location.patch#L13)):*
> ```Diff
>                  else:
>                      type = IDLWrapperType(self.getLocation(p, 1), p[1])
>                  p[0] = self.handleModifiers(type, p[2])
> ```

Did you upstream this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12819)*

**Comment by nox** [comment]
I've reviewed the first two commits and will wait for an answer before reviewing the rest. On a side-note, @jdm could you shorten your commit titles? They are hard to read in git-log and on GH.

**Comment by jdm** [comment]
Review status: 7 of 18 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1749 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPI9SmB4h87k0gKyV8R:-KPrn1qgURijwoAzOd7g:b-z77blc) ([raw file](https://github.com/servo/servo/blob/bcd85af31fe959a8180c2bf60f58c9350fc2d454/components/script/dom/bindings/codegen/CodegenRust.py#L1749)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> I don't understand what that function is for, it looks like a misnomer. My intuition is that it peels wrappers and nullable types, but then it returns an array so I don't know what it does.
</details>
It accepts an array of types, and returns an array of types that have had their wrapper and nullable-ness removed.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2708 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPI9v9ni-3vF4lFmwg_:-KProYKb_2pDmWlppY66:b-jfwtpb) ([raw file](https://github.com/servo/servo/blob/bcd85af31fe959a8180c2bf60f58c9350fc2d454/components/script/dom/bindings/codegen/CodegenRust.py#L2708)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Why do we need to always expose `GetProtoObject` and `GetConstructorObject` now?
</details>
The functions need to be public to be reexported, and the code that adds the names to the reexport list shouldn't need to replicate the logic to decide if the functions need to be public or not. This was the easiest solution.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1521 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPIBFuuSdgYGhZBvf7m:-KPrmwegqnydFaOyN7Gm:bjc6fb3) ([raw file](https://github.com/servo/servo/blob/85b459243e0eae19256f43ddb0f1e5f94bfc4465/components/script/dom/bindings/codegen/CodegenRust.py#L1521)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> So where are the magic definitions of all these methods?
</details>
They are self-hosted and already exist.

---

*[components/script/dom/bindings/codegen/parser/callback-location.patch, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPIAFK7R8_dwpoUmt3U:-KProqEYouvnBzN7lwp9:bo9gid3) ([raw file](https://github.com/servo/servo/blob/bcd85af31fe959a8180c2bf60f58c9350fc2d454/components/script/dom/bindings/codegen/parser/callback-location.patch#L13)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Did you upstream this?
</details>
Not yet. I'd like to do that as a followup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12819)*

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer 

Feel free to r=me if my last question is nonsense.

---

Reviewed 11 of 11 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/12819#-KPIAJchF8DtqNStEjvu:-KPrqy1JwMpNFZaYXqEv:b-9lx5uo) (no related file):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Can you paste a diff of the generated code showing the changes of supporting multiple WebIDL interfaces in a single file?
</details>
You forgot to do that.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2675 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPrqkMwkwQwITZ9I1UQ:-KPrqkMwkwQwITZ9I1UR:b533mw2) ([raw file](https://github.com/servo/servo/blob/53be3aadb14b2d325cfe8f951b93de9b261c439c/components/script/dom/bindings/codegen/CodegenRust.py#L2675)):*
> ```Python
> """ % properties))
> 
>         aliasedMembers = [m for m in self.descriptor.interface.members if m.isMethod() and m.aliases]
> ```

What are aliases here? I thought we didn't support `Alias` yet. Is that something different?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12819#-:-KPrqvwgdnmowYZXFozY:btheip3)*

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/12819#-KPIAJchF8DtqNStEjvu:-KPrttOtxu8eyMdmcKOO:b-lp1cf7) (no related file):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> You forgot to do that.
</details>
Didn't forget; just not complete yet.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2675 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12819#-KPrqkMwkwQwITZ9I1UQ:-KPrtloZ-O9JdcTbUabv:baufs9) ([raw file](https://github.com/servo/servo/blob/53be3aadb14b2d325cfe8f951b93de9b261c439c/components/script/dom/bindings/codegen/CodegenRust.py#L2675)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> What are aliases here? I thought we didn't support `Alias` yet. Is that something different?
</details>
forEach is an automatic alias of @@iterator that is created by the webidl parser.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12819)*

**Comment by jdm** [comment]
Before/after diff for TestBindingPairIterableBinding.rs when adding the iterable declaration that causes an extra interface to be generated in the binding file: https://gist.github.com/jdm/0c2fa6068c6f630a5377550f635cc2bb

**Comment by jdm** [comment]
Whee, now appveyor passes and travis fails with the same error getting Function's original location wrong. I wonder if this is caused by running multiple parsers in parallel...

**Comment by jdm** [comment]
I'll merge this if travis and appveyor are ok with it.

**Comment by jdm** [comment]
@bors-servo: r=nox
One appveyor build had a weird problem with angle; not the fault of this PR.

**Pull request merged**
