### PR TITLE
components/script/dom/performance.rs: correctly convert ns to ms.

### LINKED ISSUE #5690: window.performance.now values are way too big
The implementation at http://mxr.mozilla.org/servo/source/components/script/dom/performance.rs#54 multiples a nanosecond value by 1 million and calls that a high-precision millisecond value. That seems obviously wrong to me; we should be dividing in order to return fractional milliseconds.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #5690

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5697)

### CODE REVIEW

**Comment by jdm** [comment]
Could you write a content test that uses the result of performance.now() and a timer to ensure that sensible values are being output?

**Comment by jagtalon** [comment]
@jdm sure thing!

**Comment by jagtalon** [comment]
@jdm done! hope it looks ok.

**Comment by jdm** [comment]
@jagtalon The test looks good! Unfortunately, we have recently removed our contenttest harness, so the new test should be converted to a WPT test in tests/wpt/mozilla/. See #5732 for an example of such a conversion!

**Comment by jdm** [comment]
You can be sure it still runs after conversion with `./mach test-wpt /_mozilla/mozilla/test_file.html`

**Comment by jagtalon** [comment]
@jdm awesome, I can do that!

**Comment by jdm** [comment]
Sorry to keep shifting the goalposts :)

**Comment by jagtalon** [comment]
@jdm sorry for being late on this--will try to do it soon!

**Comment by jdm** [comment]
Thanks!

**Comment by jdm** [comment]
Subsumed by #6292. Thanks for your efforts!

**Pull request closed without merging**
