### PR TITLE
Update dependencies with fixes for native ARM builds

### PR DESCRIPTION
**Pull request by connorimes**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7961)

### CODE REVIEW

**Comment by connorimes** [comment]
These updated dependencies allow building servo natively on an ARM system.  More changes likely to come later as I test on other devices.  Cef and gonk ports don't build yet.

**Comment by jdm** [comment]
```
In file included from libazure/DataSurfaceHelpers.h:9:0,
                 from libazure/FilterNodeSoftware.cpp:9:
libazure/2D.h:32:22: fatal error: ft2build.h: No such file or directory
 #include "ft2build.h"
                      ^
compilation terminated.
```

**Comment by connorimes** [comment]
I don't see why that should be the case, nothing changed in the code.  The only change in rust-azure is in selecting the correct gcc/ar to use.

**Comment by mbrubeck** [comment]
This pulls in servo/libfreetype2#17 which is a significant change to the freetype-sys build.  In particular, if the freetype-sys build script uses pkg-config successfully, then it no longer outputs the DEP_FREETYPE_OUTDIR variable which is used by azure [here](https://github.com/servo/rust-azure/blob/7816fcf170da14bb59d3175b80c8bf2767b8ae2b/makefile.cargo#L67).

**Comment by mbrubeck** [comment]
servo/rust-azure#203 fixes the azure build error.

**Comment by connorimes** [comment]
At @jdm 's request I pulled the rust-azure update from this PR, but the problem it caused should be fixed in @mbrubeck 's PR above which is now merged.  We can either retry the build in this PR as is and do the rust-azure dependency update separately, or I can add it back in before we continue. Let me know how you want to proceed.

**Comment by jdm** [comment]
You can add it back in, now that we have a theory for why the previous build failed.

**Comment by connorimes** [comment]
OK, it's added back in.  I think we're ready to try again.  Thanks.

**Pull request merged**
