### PR TITLE
Implement HTMLHyperlinkElementUtils for HTMLAnchorElement

### LINKED ISSUE #7857: Implement HTMLHyperlinkElementUtils for HTMLAnchorElement
We need to uncomment the `implements` line in `HTMLAnchorElement.webidl`, and then add the missing methods to the `HTMLAnchorMethods` implementation in `htmlanchorelement.rs`. Use `WorkerLocation` as a model for this; each time a method from `URLUtils` is called (via `UrlHelper`), we should fetch the current value of the `href` attribute, then adjust the relevant property if necessary, then set the `href` attribute to the new value if necessary.

Code: components/script/dom/webidls/HTMLAnchorElement.webidl, components/script/dom/htmlanchorelement.rs
Test: `./mach test-wpt tests/wpt/web-platform-tests/websockets/constructor/006.html`

### PR DESCRIPTION
**Pull request by Ms2ger**
Fixes #7857.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9292)

### CODE REVIEW

**Comment by nox** [comment]
r=me but why don't we use `AttrValue::Url`?

**Comment by nox** [comment]
Actually, r-. What happens if you try to set the password of a `<a>` element with no href attribute?

**Comment by Ms2ger** [comment]
This is a WIP; I might get around to finishing it at some point.

**Comment by jdm** [comment]
Closed due to lack of updates.

**Pull request closed without merging**
