### PR TITLE
remove unwrap(), not needed

### LINKED ISSUE #15387: Remove use of unwrap in handle_exit_pipeline_msg
After the panic in #15386, there is a subsequent panic that looks like this:
```
called `Result::unwrap()` on an `Err` value: RecvError (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(5) }, at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:870)
stack backtrace:
   0:        0x10dff9351 - backtrace::backtrace::trace::h6545df4cf0bad269
   1:        0x10dff1fc4 - backtrace::capture::Backtrace::new::ha2ca403b809d6889
   2:        0x10cf9d3eb - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h85aa86e426463240
   3:        0x11356ad54 - std::panicking::rust_panic_with_hook::h33761bada49f3713
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/panicking.rs:556
   4:        0x11356ac34 - std::panicking::begin_panic<collections::string::String>
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/panicking.rs:517
   5:        0x11356ab52 - std::panicking::begin_panic_fmt::h4c0c43306d52c68f
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/panicking.rs:501
   6:        0x11356aab7 - rust_begin_unwind
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/panicking.rs:477
   7:        0x1135943a0 - core::panicking::panic_fmt::hbd633f652cd3a047
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/panicking.rs:69
   8:        0x110ed0e33 - core::result::unwrap_failed::h464454790b527e4e
   9:        0x110e7720e - _$LT$core..result..Result$LT$T$C$$u20$E$GT$$GT$::unwrap::haf5a956ae11f7cf9
  10:        0x11121ec78 - script::script_thread::ScriptThread::handle_exit_pipeline_msg::h657369f758716b54
  11:        0x111212111 - script::script_thread::ScriptThread::handle_msg_from_constellation::h20815a76d127f741
  12:        0x1112104b4 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hefc1e567c5c79d36
  13:        0x1112108e1 - script::script_thread::ScriptThread::profile_event::h1e0b6fc9a779e9a2
  14:        0x11120ec46 - script::script_thread::ScriptThread::handle_msgs::hece15ce7cd26d13d
  15:        0x11120d1f5 - script::script_thread::ScriptThread::start::h578c1fccec1e8ed9
  16:        0x1100a5c04 - _$LT$script..script_thread..ScriptThread$u20$as$u20$script_traits..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hcc1940d0bd439320
  17:        0x10fb82093 - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hac8ba0198f923299
  18:        0x10f75374e - script::script_thread::{{impl}}::create::{{closure}}
                        at /Users/jdm/src/servo/components/script/script_thread.rs:554
  19:        0x10f6fd8ca - std::panic::{{impl}}::call_once<(),closure>
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/panic.rs:296
  20:        0x10f450d29 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/panicking.rs:460
  21:        0x11356bc6a - __rust_maybe_catch_panic
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libpanic_unwind/lib.rs:98
  22:        0x10f35fac3 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/panicking.rs:436
  23:        0x10f133a54 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/panic.rs:361
  24:        0x110c3fcfb - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h52f8c2759c72acd7
  25:        0x110f21982 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h17eff6b4be61cfd2
  26:        0x113569cd4 - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/liballoc/boxed.rs:615
  27:     0x7fff91cdf898 - _pthread_body
  28:     0x7fff91cdf729 - _pthread_start
ERROR:servo: called `Result::unwrap()` on an `Err` value: RecvError
```
This comes from `response_port.recv().unwrap()` in [handle_exit_pipeline_msg](https://dxr.mozilla.org/servo/rev/da89099e26955cf5ba44031a0a536e3af4e6a0d5/components/script/script_thread.rs#1537), and the unwrap is unnecessary because we're trying to shut down the thread. It doesn't matter if we encounter an error here, so we should just ignore it instead.

I doubt that there's a useful automated test we can write here, but we can see what happens before and after the change by visiting http://entanglement.gopherwoodstudios.com/ while #15386 is unfixed.

### PR DESCRIPTION
**Pull request by karan1276**
Fixes #15387

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15470)

### CODE REVIEW

**Comment by karan1276** [comment]
@Wafflespeanut please review

**Comment by Wafflespeanut** [comment]
Please change the commit message to something more specific like, `"Remove usage of unwrap in handle_exit_pipeline_msg"`

**Comment by asajeffrey** [comment]
Seems like a sensible change to me, thanks!

**Comment by KiChjang** [comment]
The commit message has a typo, `handel` instead of `handle`.

**Comment by Wafflespeanut** [comment]
Thanks!

@bors-servo r+

**Pull request merged**
