### PR TITLE
Move all tasks to Community-TC

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’m submitting this for review, but landing it should be coordinated with migrating the macOS workers. (Or everything will become slow since only one macOS worker is picking up tasks from Community-TC at the moment.)

I’ll do this tomorrow if https://community-tc.services.mozilla.com/tasks/groups/HeJ8speJQnuCKArF2pngvg looks good.

**Review by jdm — APPROVED** [review]

**Comment by SimonSapin** [comment]
I’ve moved all but one macOS workers.

@bors-servo r=jdm p=100 treeclosed=100

**Comment by SimonSapin** [comment]
More possibly-pkgconfig-related issues on `mac1` :/

https://community-tc.services.mozilla.com/tasks/FxoimHEgSeOxCfbbYEinUA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FFxoimHEgSeOxCfbbYEinUA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L1456-1459
```
Package libtizcore was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtizcore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtizcore' found
```

I’ve reran that task, it seems to be doing ok on `mac4` for now.

**Comment by SimonSapin** [comment]
One WPT chunk had one failure (below). Two have not finished yet.

@bors-servo retry force

https://community-tc.services.mozilla.com/tasks/KNkBKJLCSmWFfhuGWx1RJA

<details>

```
  │ [2019-11-08T08:14:22Z ERROR servo] Font cache thread has already exited.
  │ assertion failed: !self.Document().needs_reflow() ||
  │     (!for_display && self.Document().needs_paint()) ||
  │     self.suppress_reflow.get() (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/dom/window.rs:1695)
  │ stack backtrace:
  │    0: backtrace::backtrace::trace
  │    1: backtrace::capture::Backtrace::new
  │    2: servo::main::{{closure}}
  │    3: std::panicking::rust_panic_with_hook
  │    4: std::panicking::begin_panic
  │    5: script::dom::window::Window::reflow
  │    6: script::dom::document::Document::finish_load
  │    7: script::dom::servoparser::ServoParser::do_parse_sync
  │    8: profile_traits::time::profile
  │    9: _ZN6script3dom11servoparser11ServoParser10parse_sync17h101295c1d14ac3b0E.llvm.10984848111799813079
  │   10: <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_eof
  │   11: script::script_thread::ScriptThread::handle_msg_from_constellation
  │   12: _ZN6script13script_thread12ScriptThread11handle_msgs17h62b3688227031e3dE.llvm.17534440358121355182
  │   13: script::script_thread::ScriptThread::start
  │   14: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  │   15: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   16: _ZN3std9panicking3try7do_call17ha2b3b5597b4e3c77E.llvm.181114007576099400
  │   17: __rust_maybe_catch_panic
  │   18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  │   20: std::sys::unix::thread::Thread::new::thread_start
  │   21: _pthread_body
  │   22: _pthread_start
  │ 
  │ [2019-11-08T08:14:22Z ERROR servo] assertion failed: !self.Document().needs_reflow() ||
  │     (!for_display && self.Document().needs_paint()) ||
  └     self.suppress_reflow.get()
```

</details>

**Comment by SimonSapin** [comment]
```
  ▶ FAIL [expected PASS] /css/css-style-attr/style-attr-urls-002.xht
  └   → /css/css-style-attr/style-attr-urls-002.xht e1a2ce13e5bc959047c165aaa07d0e97257e6323
/css/css-style-attr/reference/ref-green-on-green.xht 78c92b98a55f7b4056e1abea2f63aa9a4f20881c
```

@bors-servo retry force

**Pull request merged**
