### PR TITLE
Remove rustc-serialize from the dependencies

### LINKED ISSUE #12410: Stop using rustc_serialize
There is no reason for us to use both rustc_serialize and serde.

### PR DESCRIPTION
**Pull request by Eijebong**
Closes #12410.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22087)

### CODE REVIEW

**Comment by Eijebong** [comment]
@bors-servo try

Builds locally, I pushed -f devices recently so I hope that was the problem

**Comment by Eijebong** [comment]
@bors-servo try

I'm talking to you !

**Comment by Eijebong** [comment]
@bors-servo try

Pushing might help...

**Comment by pyfisch** [comment]
When this is merged also close #12410 :tada:

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* #22135

**Comment by jdm** [comment]
@bors-servo retry
* #22140

**Pull request merged**
