### PR TITLE
Measure memory usage of Stylo's Rule Tree.

### PR DESCRIPTION
**Pull request by nnethercote**
This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1394729, which was r=heycam.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because tests exist in Gecko.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18310)

### CODE REVIEW

**Comment by heycam** [comment]
@bors-servo retry

* some message about mismatching commits

**Comment by heycam** [comment]
@bors-servo p=1

I want to base some work on this today.

**Comment by upsuper** [comment]
@bors-servo p=10

If it's blocking you, probably we can make it a little bit higher priority. I can land my patches later today.

**Pull request merged**
