### PR TITLE
Mention gstreamer LIB variable for Windows

### PR DESCRIPTION
**Pull request by Manishearth**
This got missed.

Ideally we'll get bootstrap to do all of this, but I haven't yet made
bootstrap work properly for Windows.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21729)

### CODE REVIEW

**Comment by ferjm** [comment]
In theory, this shouldn't be necessary after #21515. Note that we are not setting this on CI.

**Comment by Manishearth** [comment]
We do! It's set in the saltfs config

**Comment by Manishearth** [comment]
https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/environments.py#L91

**Comment by ferjm** [comment]
Oh, I was referring to [AppVeyor](https://github.com/servo/servo/blob/master/appveyor.yml) But I guess that's ok because we don't run any tests there (other than unit tests).

**Pull request merged**
