### PR TITLE
style: Temporarily use OrderMap on Gecko.

### PR DESCRIPTION
**Pull request by emilio**
This will allow us to discard std hash map as a source of crashes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19912)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0244]: wrong number of type arguments: expected 2, found 3
   --> components/style/selector_map.rs:521:17
    |
521 |     ) -> Result<hash_map::Entry<Atom, V, BuildHasherDefault<PrecomputedHasher>>, FailedAllocationError> {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 type arguments
error: aborting due to previous error
error: Could not compile `style`.
```

**Comment by emilio** [comment]
Fixed, thanks @jdm :)

**Comment by emilio** [comment]
Also, r? @Manishearth

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
