### PR TITLE
Add NS_FONT_STRETCH_* consts and regenerate bindings

### PR DESCRIPTION
**Pull request by ghost**
Depends on servo/rust-bindgen#74

---

- [x] `./mach build-geckolib` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] These changes do not require tests because they're autogenerated

Once that merges, r? @Manishearth

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13566)

### CODE REVIEW

**Comment by Manishearth** [comment]
r=me. I might replace the regen with one from my own machine to avoid churn

**Comment by Manishearth** [comment]
Could you only include the consts changes? `git reset structs_foo.rs; git add -p structs_foo.rs` will work for selecting diff chunks.

**Comment by Wafflespeanut** [comment]
It now has the constants generated by the script.

**Pull request merged**
