### PR TITLE
Make the style crate (almost) build with a stable compiler

### PR DESCRIPTION
**Pull request by SimonSapin**
The bulk of this is adding cargo features to make derived implementations of `heapsize` and `serde` traits optional.

"Almost" because `std::intrinsics::discriminant_value` is currently unstable and doesn’t have any stable replacement that I know of. For now, this PR conditionally replaces it with `unimplemented!()`.

r? @nox

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes <s>fix</s> are part of #11815 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not <s>require tests</s> _have tests yet_ because that requires https://github.com/servo/servo/issues/11806, but I still want to land this before it bitrots. (Tests should check that the build succeeds with a stable compiler.)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11816)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Should be trivial to replace `std::intrinsics::discriminant_value` with a hand-written method.

**Comment by SimonSapin** [comment]
You mean one per enum type rather than a generic one, right? And we’d probably want to auto-generate them with Mako or something.

**Comment by SimonSapin** [comment]
As a side-effect, this removes a bunch of crates from the geckolib build. (Dependencies of `util` that are now made optional and only enabled for servo.)

**Comment by KiChjang** [comment]
Did highfive not assign a reviewer?

**Comment by Wafflespeanut** [comment]
Highfive intermittent: servo/highfive#124

**Comment by Ms2ger** [comment]
Oh, I only recalled the call in `viewport.rs`.

**Comment by nox** [comment]
r=me but I would like us to remove the `unimplemented!()` before it lands, and if we could keep the features to just `"servo"` I think it would be better.

-S-awaiting-review +S-awaiting-answer 

---

Reviewed 20 of 20 files at r1, 40 of 40 files at r2, 2 of 2 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11816#-:-KKrm47RNEX7p7ID_Aon:89709155)*

**Comment by SimonSapin** [comment]
@bors-servo r=nox

Updated lock file.

**Comment by nox** [comment]
@bors-servo r-

Put the lockfile updates in the commit they belong.

**Comment by KiChjang** [comment]
The first failure is #11703.

**Comment by jdm** [comment]
@bors-servo: retry
* #11703 #11825

**Pull request merged**
