### PR TITLE
execute wpt tests with experimental flag

### LINKED ISSUE #7335: Make it possible to run tests with the experimental flag
Some features are only available when Servo runs with the `-e` option.

### PR DESCRIPTION
**Pull request by paulrouget**
closes #7335

Locally, all tests pass.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7385)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Did you also run test-css?

**Comment by paulrouget** [comment]
No. Testing now.

**Comment by jdm** [comment]
This would need to go upstream to https://github.com/w3c/wptrunner .

**Comment by paulrouget** [comment]
How is wptrunner updated in servo? It' not a submodule. Is it just a copy?

**Comment by paulrouget** [comment]
See https://github.com/w3c/wptrunner/pull/139

**Comment by jgraham** [comment]
Per @SimonSapin's description of the experimental flag I'm not sure this is a great idea since enabling the flag could enable features for which "[the Servo] impl is not ready yet (e.g. hits unimplemented!() or assertion errors that crash the browser)"

**Comment by paulrouget** [comment]
Indeed. For example, `test-css` fails because of the flexbox tests.

We need to figure out something else. Back to #7335.

**Comment by jgraham** [comment]
test-css possibly just needs new metadata if we are enabling a new feature.

In any case I should also note that I have philosophical objects to only testing the non-default configuration.

**Comment by metajack** [comment]
@jgraham We can test both if we spin up more builders. I'm still not convinced about `-e` and defaultness though. For example, we're planning to ship the alpha with mozbrowser which requires `-e`, and that will be the default config. We still haven't resolved what to do about this issue. Some of the other stuff behind `-e` probably shouldn't be on by default.

**Comment by jgraham** [comment]
Sure, I don't object to testing both, but they would need different metadata in some cases.

It seems like the meaning of `-e` is heavily overloaded at the moment. A more ideal situation might be to have different features behind different flags and enable non-default features for the tests that require them (e.g. `--feature flexbox` for the flexbox tests, or something). `wptrunner` can certainly be taught to deal with per-test flags although for servodriver it's currently non-trivial because by the time we know what test we are running the browser has already started. Nothing a little refactor couldn't fix ofc.

**Comment by jdm** [comment]
I've implemented a preference system in #7391 to split up the grab-bag of `-e`. It should be usable by the WPT harness for setting preferences for individual tests, too.

**Comment by jgraham** [comment]
@jdm ++

I think the right thing to do here is to allow per-test prefs just like Firefox. It will require some implementation work for servodriver, but nevertheless I think it's the best way forward.

**Pull request closed without merging**
