### PR TITLE
Allow disabling LLVM assertions in rustc (fixes #15548)

### LINKED ISSUE #15548: Use rustc builds without asserts
The Rust team is making these builds available in the s3 bucket, so we need to modify the mach bootstrap command to fetch the appropriate URL to retrieve them. This is blocked until https://github.com/rust-lang/rust/pull/39754 is merged.

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15559)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I got some numbers on Servo commit 09d88cbc8e52fe64d0cdb7b37d7ba4fd77b2b520 with Rust commit https://github.com/rust-lang/rust/commit/025c328bf5ab336ff708e62a59292298dc1bc089, on a fast desktop. My config has incremental compilation and `ccache` enabled. Timings do not include downloading and unpacking dependencies or a compiler.

* Debug, `llvm-assertions = true`, after `cargo clean`: 385 secs
* Debug, `llvm-assertions = true`, after `touch components/style/lib.rs`: 87 secs
* Debug, `llvm-assertions = false`, after `cargo clean`: 333 secs
* Debug, `llvm-assertions = false`, after `touch components/style/lib.rs`: 86 secs
* Release, `llvm-assertions = true`, after `cargo clean`: 583 secs
* Release, `llvm-assertions = true`, after `touch components/style/lib.rs`: 67 secs
* Release, `llvm-assertions = false`, after `cargo clean`: 380 secs
* Release, `llvm-assertions = false`, after `touch components/style/lib.rs`: 69 secs

Observations:

* With an empty incremental compilation cache (or, I presumably, with incremental compilation disabled), **LLVM assertions add 16% to the compilation time in debug mode, 53% (!) in release mode**.
* With an ideal incremental compilation cache (nothing actually changed other than a source timestamp), LLVM assertions make no difference (beyond noise levels). I think this is because LLVM is not used at all in this scenario
* With an ideal incremental compilation cache, **release mode 23% is faster to compile than debug mode!** I have no explanation for this.

**Comment by SimonSapin** [comment]
This PR doesn’t change the default config, so unless you tweak `.servobuild` it’s just a rustup.

@bors-servo r+

**Comment by SimonSapin** [comment]
```
error: compile-fail/privatize.rs:10: unexpected "error": '10:10: 10:26: proc-macro derive panicked'
error: compile-fail/privatize.rs:10: expected error not found: custom derive attribute panicked
error: compile-fail/ban.rs:14: unexpected "error": '14:10: 14:21: Banned type Cell<JSVal> detected. Use MutJS<JSVal> instead'
error: compile-fail/ban.rs:14: expected error not found: Banned type Cell<JSVal> detected. Use MutJS<JSVal> instead,
error: compile-fail/ban-domrefcell.rs:15: unexpected "error": '15:10: 15:30: Banned type DOMRefCell<JS<T>> detected. Use MutJS<JS<T>> instead'
error: compile-fail/ban-domrefcell.rs:15: expected error not found: Banned type DOMRefCell<JS<T>> detected. Use MutJS<JS<T>> instead,
```

**Comment by mbrubeck** [comment]
> With an ideal incremental compilation cache, release mode 23% is faster to compile than debug mode! I have no explanation for this.

Conditional compilation means we tend to compile less code in release mode (due to assertions and debugging being omitted), though I'm surprised it makes this much difference.

> LLVM assertions add 16% to the compilation time in debug mode, 53% (!) in release mode.

This probably means that most of the assertions are in code that is only run during release builds, so enabling assertions during debug builds will be of much more limited use for finding LLVM bugs.

**Pull request merged**
