### PR TITLE
Update Canvas webIDL to spec

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8729)

### CODE REVIEW

**Comment by jdm** [comment]
```
/home/travis/build/servo/servo/components/script/dom/canvasrenderingcontext2d.rs:15:5: 15:89 error: unresolved import `dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding::CanvasWindingRule`. There is no `CanvasWindingRule` in `dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding` [E0432]

/home/travis/build/servo/servo/components/script/dom/canvasrenderingcontext2d.rs:15 use dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding::CanvasWindingRule;

                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jdm** [comment]
Fix that and you can merge this.

**Comment by jdm** [comment]
```
./components/script/dom/canvasrenderingcontext2d.rs:14: use statement is not in alphabetical order
	expected: dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding::CanvasFillRule
	found: dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding::CanvasRenderingContext2DMethods
./components/script/dom/canvasrenderingcontext2d.rs:15: use statement is not in alphabetical order
	expected: dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding::CanvasRenderingContext2DMethods
	found: dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding::CanvasFillRule
```

**Comment by dzbarsky** [comment]
r+

**Pull request merged**
