### PR TITLE
Add mach test-webidl command

### PR DESCRIPTION
**Pull request by shinglyu**
I updated the `WebIDL.py` from latest mozilla-central. And add a `./mach test-webidl` command. For #9397

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9459)

### CODE REVIEW

**Comment by nxnfufunezn** [comment]
*[python/servo/testing_commands.py, line 245 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9459#-K9D137cKOKPO2E5IFLN:-K9D137cKOKPO2E5IFLO:-949413700) ([raw file](https://github.com/servo/servo/blob/18b6817755b3509990e0a9fbe1acb5318d81c957/python/servo/testing_commands.py#L245)):*
reduce this line to 120 chars add `\` after `"script",` move rest to newline

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9459)*

**Comment by nxnfufunezn** [comment]
*[python/servo/testing_commands.py, line 246 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9459#-K9D2v1tfJGdLawB4FYf:-K9D2v1tfJGdLawB4FYg:-1087154795) ([raw file](https://github.com/servo/servo/blob/18b6817755b3509990e0a9fbe1acb5318d81c957/python/servo/testing_commands.py#L246)):*
move the comment above this line...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9459)*

**Comment by nxnfufunezn** [comment]
You can run tidy checks by running this command `./mach test-tidy` :smile:

**Comment by Wafflespeanut** [comment]
The changes look good :)

@nox do we have to update `update.sh` here, or could that be an E-easy follow-up?

**Comment by Wafflespeanut** [comment]
-S-awaiting-review

---

Reviewed 4 of 6 files at r1, 1 of 1 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9459#-:-K9FypBBxXvwQ1gj8Nez:721110327)*

**Comment by nox** [comment]
It can probably be an E-Easy thing.

**Comment by Wafflespeanut** [comment]
@bors-servo r+

Thanks!

**Comment by Wafflespeanut** [comment]
@bors-servo retry

#8191

**Pull request merged**
