### PR TITLE
Add jQuery test runner and mach integration.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6201)

### CODE REVIEW

**Comment by metajack** [comment]
Looks pretty good, but a few nits found.

-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 5 unresolved discussions, all commit checks successful.
Reviewed files:
- python/servo/testing_commands.py @ r1
- tests/jquery/.gitignore @ r1
- tests/jquery/expected_selector.txt @ r1
- tests/jquery/run_jquery.py @ r2

---

<sup>**[python/servo/testing_commands.py, line 323 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNb-QZhciuDOlkCz6X)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/python/servo/testing_commands.py#L323)):</sup>
This needs to use the right thing if servo is not built in release mode. Isn't this abstracted somewhere in mach now?

---

<sup>**[tests/jquery/.gitignore, line 1 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNbECQWj6S26uHAO-3)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/tests/jquery/.gitignore#L1)):</sup>
Do other ignores live outside the root? If so this is fine.

---

<sup>**[tests/jquery/run_jquery.py, line 18 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNbYGmNuy5Jbgvs8iG)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/tests/jquery/run_jquery.py#L18)):</sup>
These should have a bug filed. No need to block this PR on it, but please file them.

---

<sup>**[tests/jquery/run_jquery.py, line 44 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNboqkX9TRmJwTnKnh)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/tests/jquery/run_jquery.py#L44)):</sup>
This is slightly fragile. Does HTTPServer have an option to return you a free port number? What does wpt do?

---

<sup>**[tests/jquery/run_jquery.py, line 196 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNcKNvfEJWr0XQYilA)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/tests/jquery/run_jquery.py#L196)):</sup>
This message will need updating if we change mach to support debug builds too.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6201)

**Comment by waddlesplash** [comment]
Would it be a good idea to make the buildbots run the jQuery testsuite?

**Comment by metajack** [comment]
I believe that is the plan.

**Comment by glennw** [comment]
Review status: 2 of 6 files reviewed, 5 unresolved discussions, some commit checks pending.

---

<sup>**[python/servo/testing_commands.py, line 323 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNb-QZhciuDOlkCz6X)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/python/servo/testing_commands.py#L323)):</sup>
Done.

---

<sup>**[tests/jquery/.gitignore, line 1 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNbECQWj6S26uHAO-3)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/tests/jquery/.gitignore#L1)):</sup>
There are several other ignores outside the root.

---

<sup>**[tests/jquery/run_jquery.py, line 18 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNbYGmNuy5Jbgvs8iG)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/tests/jquery/run_jquery.py#L18)):</sup>
Done.

---

<sup>**[tests/jquery/run_jquery.py, line 44 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNboqkX9TRmJwTnKnh)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/tests/jquery/run_jquery.py#L44)):</sup>
WPT has a hard coded port (8000).

---

<sup>**[tests/jquery/run_jquery.py, line 196 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6201#-JqNcKNvfEJWr0XQYilA)** ([raw file](https://github.com/servo/servo/blob/ef9d2f0116a11d912ed3f177ae2a97991a332752/tests/jquery/run_jquery.py#L196)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6201)

**Comment by glennw** [comment]
@metajack I think this is ready to go now?

**Comment by metajack** [comment]
@glennw Looks good. Squash and r=me.

-S-awaiting-review +S-needs-squash 

---

Review status: all files reviewed, 5 unresolved discussions, all commit checks successful.
Reviewed files:
- python/servo/command_base.py @ r3
- python/servo/post_build_commands.py @ r3
- python/servo/testing_commands.py @ r3
- tests/jquery/run_jquery.py @ r3

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6201)

**Pull request merged**
