### PR TITLE
Fix a cached style cascade bug that only manifested in sequential mode

### LINKED ISSUE #11818: Sequential layout bug with (possibly) RTL direction
When we use the sequential layout traversal, there's an error with overconstrained_block.html and div_align.html.

Discovered while testing #11713

### PR DESCRIPTION
**Pull request by notriddle**
When copying cached styles, keep the `writing_mode` up to date.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11818 (github issue number if applicable).
- [X] There are tests for these changes

EDIT: The test is now working. I ran it with the first commit (the actual fix) reverted and it failed.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12839)

### CODE REVIEW

**Comment by emilio** [comment]
Can you elaborate why it only reproduced on sequential mode?

Also, you can pass `--binary-arg="-y 1"` to run it sequentially, I guess, though the pref you've used might work?

**Comment by notriddle** [comment]
The pref doesn't work, because Servo doesn't read it. I put it there as a note.

**Comment by notriddle** [comment]
As for why it only shows up in sequential mode, it's because the parallel layout traversal creates the context fresh every time it does a different chunk, while the sequential layout traversal uses the same one the entire time.

**Comment by emilio** [comment]
Oh, I see. You might be able to reproduce it in parallel layout adding more than 64 children then, right? That should make all of them going into the same chunk.

**Comment by emilio** [comment]
That being said, I think that's flacky-ish. We should run a few tests on parallel mode, probably adding the pref to the `resources/prefs.json` does the trick.

**Comment by notriddle** [comment]
Can I just change it so that `layout_threads` is a preference instead of an argument? That would change the command syntax (`-y1`-> `--pref layout_threads 1`), but it would fix the problem.

**Comment by emilio** [comment]
Why not making it a pref and make `-y` only set that pref?

**Comment by notriddle** [comment]
That probably is a good idea.

**Comment by notriddle** [comment]
Replaced the unwrap with expect, and everything else works. This should be ready to review now.

@bors-servo try

**Comment by metajack** [comment]
Wow @notriddle nice find!

cc @avadacatavra

**Comment by emilio** [comment]
@bors-servo: r+

Good find @notriddle :)

**Pull request merged**
