### PR TITLE
Taskcluster: use current rustup.rs on Windows

### PR DESCRIPTION
**Pull request by SimonSapin**
1.18.3 includes speed improvements when excracting tarballs:
https://github.com/rust-lang/rustup.rs/blob/1.18.3/CHANGELOG.md

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23445)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Does `try=windows` still make homu confused? Here is a task with this change, though rustup does not print detailed timing info:

https://tools.taskcluster.net/groups/SIzwFTw4Siq3ZZ_n4oKvcg/tasks/VhnevOa6Q2aXVgIBqX4BbQ/runs/0/logs/public%2Flogs%2Flive.log#L237

**Comment by jdm** [comment]
A Windows try run does require restarting homu, yes.

**Review by jdm — APPROVED** [review]

**Pull request merged**
