### PR TITLE
Implement HTMLInputElement cloning steps

### LINKED ISSUE #25385: Cloning a form doesn't preserve changed values of its HTMLInputElement children.
WPT html/semantics/forms/the-input-element/clone.html has a form with `value` and `checked` content attributes on many input children. It sets .value on the children, then calls cloneNode on the form. It gets back a clone, but the clone's children's values match the original values from their content attributes, not the updated values that were set by the script.

### PR DESCRIPTION
**Pull request by teapotd**
This change adds missing [cloning steps for input elements](https://html.spec.whatwg.org/multipage/#the-input-element%3Aconcept-node-clone-ext).

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25385
- [X] There are tests for these changes

### CODE REVIEW

**Comment by CYBAI** [comment]
The failure is #21067

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
* #24762

**Pull request merged**
