### PR TITLE
Upgrade to rustc 1.37.0-nightly (04a3dd8a8 2019-06-18) + fix new warnings

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23600)

### CODE REVIEW

**Comment by jdm** [comment]
```
./python/tidy/servo_tidy/tidy.py:537: F841 local variable 'prev_indent' is assigned to but never used
```

**Comment by jdm** [comment]
Unfortunately this adds a bunch of warnings on other platforms that need to be fixed:
```
error: trait objects without an explicit `dyn` are deprecated
   --> C:\Users\task_1561141646\repo\target\debug\build\simpleservo-c77badf302fe26b6\out/egl_bindings.rs:350:47
    |
350 |                 fn do_metaloadfn(loadfn: &mut FnMut(&'static str) -> *const __gl_imports::raw::c_void,
    |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn FnMut(&'static str) -> *const __gl_imports::raw::c_void`
    |
    = note: `-D bare-trait-objects` implied by `-D warnings`
error: trait objects without an explicit `dyn` are deprecated
  --> ports\libsimpleservo\api\src\lib.rs:55:19
   |
55 |     VRService(Box<VRService>, Box<VRMainThreadHeartbeat>),
   |                   ^^^^^^^^^ help: use `dyn`: `dyn VRService`
error: trait objects without an explicit `dyn` are deprecated
  --> ports\libsimpleservo\api\src\lib.rs:55:35
   |
55 |     VRService(Box<VRService>, Box<VRMainThreadHeartbeat>),
   |                                   ^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn VRMainThreadHeartbeat`
error: trait objects without an explicit `dyn` are deprecated
   --> ports\libsimpleservo\api\src\lib.rs:574:34
    |
574 |         heartbeats: &mut Vec<Box<VRMainThreadHeartbeat>>,
    |                                  ^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn VRMainThreadHeartbeat`
error: aborting due to 4 previous errors
```

```
error: trait objects without an explicit `dyn` are deprecated
  --> components/background_hang_monitor/sampler_mac.rs:19:25
   |
19 |     pub fn new() -> Box<Sampler> {
   |                         ^^^^^^^ help: use `dyn`: `dyn Sampler`
   |
   = note: `-D bare-trait-objects` implied by `-D warnings`
```

```
error: trait objects without an explicit `dyn` are deprecated
  --> components/canvas/raqote_backend.rs:39:23
   |
39 |         _drawtarget: &GenericDrawTarget,
   |                       ^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn GenericDrawTarget`
   |
   = note: `-D bare-trait-objects` implied by `-D warnings`
error: trait objects without an explicit `dyn` are deprecated
  --> components/canvas/raqote_backend.rs:48:23
   |
48 |         _drawtarget: &GenericDrawTarget,
   |                       ^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn GenericDrawTarget`
error: trait objects without an explicit `dyn` are deprecated
  --> components/canvas/raqote_backend.rs:61:59
   |
61 |     fn create_drawtarget(&self, size: Size2D<u64>) -> Box<GenericDrawTarget> {
   |                                                           ^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn GenericDrawTarget`
error: trait objects without an explicit `dyn` are deprecated
   --> components/canvas/raqote_backend.rs:124:14
```

**Comment by SimonSapin** [comment]
Added a couple more `dyn` keywords, and one `#![allow(bare_trait_objects)]` in a module that includes generated files that lack `dyn`. The latter is until we upgrade to a `gl_generator` version that has https://github.com/brendanzab/gl-rs/pull/493.

A green pseudo-try run: https://tools.taskcluster.net/groups/Vc8qkHbWS6W4RplbemO6oA

@bors-servo r=nox

**Pull request merged**
