### PR TITLE
Opaque DOMString

### PR DESCRIPTION
**Pull request by asajeffrey**
This patch makes DOMString an opaque wrapper round String (currently it's a transparent wrapper).

The changes are:
- Replacing DOMString(foo) by DOMString::from(foo).
- Replacing foo.0 by String::from(foo).
- Adding functions clear, push_str and extend for in-place mutation of DOMStrings.
- Replacing DOMString by String in other threads (devtools, storage and filereader).
- Making DOMString implement !Send.
- Removing the pub attribute from the contents of DOMString.

This enables experimenting with other string representations in the DOM.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8477)

### CODE REVIEW

**Comment by pcwalton** [comment]
Neat!

**Comment by jdm** [comment]
Thanks for splitting the commits up this way!
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 63 of 63 files at r8, 1 of 1 files at r9, 5 of 5 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[components/devtools/actors/inspector.rs, line 209 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8477#-K2wMXQVM5RU-dpy_Nha)** ([raw file](https://github.com/servo/servo/blob/e057c7dc196cd31c41ab9d532c06067e287d1d88/components/devtools/actors/inspector.rs#L209)):</sup>
I don't think these String::from calls are necessary any more.


---

<sup>**[components/script/dom/create.rs, line 85 \[r8\]](https://reviewable.io:443/reviews/servo/servo/8477#-K2wZTe6rASS-va17eOL)** ([raw file](https://github.com/servo/servo/blob/50e1de0db7765c17185ab2ad79e33f4d832c3e22/components/script/dom/create.rs#L85)):</sup>
No need for {}.


---

<sup>**[components/script/dom/htmlinputelement.rs, line 579 \[r10\]](https://reviewable.io:443/reviews/servo/servo/8477#-K2waPHAb_3XEC8Xta1k)** ([raw file](https://github.com/servo/servo/blob/513c6ef1a911ee75a540134d89e545d1f78edcde/components/script/dom/htmlinputelement.rs#L579)):</sup>
We should probably be fetching the placeholder attribute on-demand in the layout code instead of storing a duplicate. File an issue?


---

<sup>**[components/script/dom/storage.rs, line 131 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8477#-K2wOVSnKHxRN3NaFrBc)** ([raw file](https://github.com/servo/servo/blob/dc31593a893b42bf7b4d50bf2377aacd2ed3fc69/components/script/dom/storage.rs#L131)):</sup>
I don't have any better ideas.


---

<sup>**[components/script/script_task.rs, line 1705 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8477#-K2wMoPBEGaQjnzRtP-Z)** ([raw file](https://github.com/servo/servo/blob/574204d3c8eb54410e699bf92f954f69655a1ef5/components/script/script_task.rs#L1705)):</sup>
I'd prefer to keep this as DOMString and perform the conversion explicitly inside this function.


---

<sup>**[components/util/mem.rs, line 106 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8477#-K2wPJ-jCtzo7KZm3jQZ)** ([raw file](https://github.com/servo/servo/blob/2269efc79a8616b1c5d4af33a3f0b6b758813a2d/components/util/mem.rs#L106)):</sup>
What if we made it really obvious what we're doing by transmuting to &String and calling heap_size_of_children instead?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8477)

**Comment by asajeffrey** [comment]
I'm getting better at rewriting my git history :)


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/util/mem.rs, line 106 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8477#-K2wPJ-jCtzo7KZm3jQZ)** ([raw file](https://github.com/servo/servo/blob/2269efc79a8616b1c5d4af33a3f0b6b758813a2d/components/util/mem.rs#L106)):</sup>
Well, this code is going to vanish pretty soon anyway, since the next task is to move str.rs out of util and into script/dom, at which point we can derive HeapSizeOf.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8477)

**Comment by jdm** [comment]
@bors-servo: delegate+
-S-awaiting-review +S-needs-squash 


---

Reviewed 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8477)

**Comment by asajeffrey** [comment]
-S-needs-squash

**Comment by asajeffrey** [comment]
Rebased, and updated the unit tests.

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 1 of 1 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8477)

**Comment by jdm** [comment]
@bors-servo: retry
* #8416

**Comment by asajeffrey** [comment]
Ah the trying-to-land-a-patch dance, how I love it. Rebased again.

**Pull request merged**
