### PR TITLE
Fix clamp-like pattern warning in font.rs

### PR DESCRIPTION
**Pull request by chickenleaf**
**File**: components/fonts/platform/windows/font.rs

**PR Description**
**Issue**: Clippy warned about a clamp-like pattern without using the clamp function in the stretch calculation.

---
**Change**:
Updated `let stretch = match min(9, max(1, width_val))` to `let stretch = match width_val.clamp(1, 9)` in the stretch calculation.

**Impact**:
Improved code readability.

---

- [X] ./mach build -d does not report any errors
- [X] ./mach test-tidy does not report any errors
- [X] These changes are part of Fix as many clippy problems as possible #31500
- [X] These changes do not require tests because they do not alter functionality.

### CODE REVIEW

**Review by Loirooriol — COMMENTED** [review]
The change looks good, but

> Also prevents potential panics if max < min in future code

It's the opposite, `clamp` would panic while the original would not. But this is not a worry since `1 < 9` and I doubt this will change in a way that `max < min`.

> ☐  ./mach test-tidy does not report any errors

So it reports errors?

**Comment by chickenleaf** [comment]
> The change looks good, but
> 
> > Also prevents potential panics if max < min in future code
> 
> It's the opposite, `clamp` would panic while the original would not. But this is not a worry since `1 < 9` and I doubt this will change in a way that `max < min`.
> 
> > ☐  ./mach test-tidy does not report any errors
> 
> So it reports errors?

i havent checked ./mach test-tidy the github issue only asked for the checking of ./mach build -d ? i was informed the same in the outreachy group.

**Comment by chickenleaf** [comment]
> The change looks good, but
> 
> > Also prevents potential panics if max < min in future code
> 
> It's the opposite, `clamp` would panic while the original would not. But this is not a worry since `1 < 9` and I doubt this will change in a way that `max < min`.
> 
> > ☐  ./mach test-tidy does not report any errors
> 
> So it reports errors?

Hello! ./mach test-tidy reports no errors.

**Review by Loirooriol — APPROVED** [review]
But please fix the incorrect "prevents potential panics if max < min in future code" comment.

**Pull request merged**
