### PR TITLE
Removed incorrectly exposed webidl interfaces

### PR DESCRIPTION
**Pull request by lucasloisp**
I removed exposure in Window and Worker to some interfaces that
was not specified in the specification. Specifically:
- HTMLLinkElement.webidl
- HTMLMapElement.webidl
- HTMLMediaElement.webidl
- HTMLMetaElement.webidl
- HTMLMeterElement.webidl
- HTMLModElement.webidl
- HTMLObjectElement.webidl
- HTMLOListElement.webidl
- HTMLOptGroupElement.webidl
- HTMLOptionElement.webidl
- HTMLOutputElement.webidl

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes partially fix #12415 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they do not add any feature

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13787)

### CODE REVIEW

**Comment by lucasloisp** [comment]
I'm mentioning @scotttrinh cause he expected this changes for his own PR

**Comment by emilio** [comment]
Hi, thanks for your pull request! I think you might need to update more tests, but I'm not totally sure, so let's see :)

@bors-servo: try

Probably it's easier for @Ms2ger, @jdm or @nox to review this, but I'll find the time to do it properly if they can't :)

**Comment by jdm** [comment]
I'm pretty sure the changes to interfaces.html should be reverted, since the interfaces are expected to be exposed in the window's global scope by default.

**Comment by emilio** [comment]
Yep, you're right @jdm, no way that's passing.

**Comment by emilio** [comment]
This looks good to me.

@bors-servo: r+

Thanks!

**Comment by KiChjang** [comment]
@bors-servo retry
* #13605

**Pull request merged**
