### PR TITLE
Avoid ./mach build to clobber the build by default.

### LINKED ISSUE #20489: `cargo build` rebuilds the world after `./mach build`, and vice versa.
And it's annoying because I tend to use them interchangeably, accidentally.

STR:

```shell
$ cd servo
$ ./mach build -d
$ cargo build
```

### PR DESCRIPTION
**Pull request by emilio**
Fixes #20489.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20491)

### CODE REVIEW

**Comment by emilio** [comment]
Not sure if the WITH_GOLD bit will make the ARM build fail... I guess we'll see.

**Comment by emilio** [comment]
> Not sure if the tradeoff is worth disabling the gold linker by default :/

It definitely is for me, but if you think otherwise I can try to find another solution... Not clear to me how'd that look.

**Comment by jdm** [comment]
It might be worth taking this to the mailing list. I'm on leave this month, so I'm unassigning myself.

**Comment by emilio** [comment]
I mailed the list. Not sure if we should proceed here or not, I guess @SimonSapin tried to make the gold bits use the cargo config and hit a cargo bug.

**Comment by SimonSapin** [comment]
My hope was to move the "unused `extern crate`" warning to `.cargo/config` (and while I’m at it the "enable NEON on ARM" bit too, since `.cargo/config` can have `cfg(…)` sections), and keep the linker one set by mach in an env variable because it’s done dynamically based on the presence of `ld.gold` in `$PATH`. I was hoping that both sets of flags would be passed to rustc, but instead the env variable *overrides* the config: https://github.com/rust-lang/cargo/issues/5376

**Comment by jdm** [comment]
Given the downsides, I'm going to close this.

**Pull request closed without merging**
