### PR TITLE
Update heartbeats and energymon profiler dependencies

### PR DESCRIPTION
**Pull request by connorimes**
Heartbeats now on crates.io.
Updates to energymon interface for energy profiling.
Profiling script for Android.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9926)

### CODE REVIEW

**Comment by asajeffrey** [comment]
@larsbergstrom can you take a look at tests/heartbeats/characterize_android.py?

**Comment by asajeffrey** [comment]
Reviewed 6 of 9 files at r1.
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/parser.out, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9926#-KCMyeLbIe5FpNFgHBf8:-KCMyeLbIe5FpNFgHBf9:-513145947) ([raw file](https://github.com/servo/servo/blob/2bf1e66203c55a894a81705770457fc6fda20d22/components/script/parser.out#L0)):*
Do you know what caused this diff?

---

*[tests/heartbeats/characterize.py, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9926#-KCMxxo3b_GU-6G136O8:-KCMxxo4hOdrGc7bnhef:1342636381) ([raw file](https://github.com/servo/servo/blob/2bf1e66203c55a894a81705770457fc6fda20d22/tests/heartbeats/characterize.py#L26)):*
A test commented out?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9926)*

**Comment by asajeffrey** [comment]
Mostly looks fine. It'd be nice to get someone who knows their way round the android build to look at it. Do you know why parser.out changed?

**Comment by connorimes** [comment]
I don't have any idea what that parser thing is. I commented out that profiler category because it doesn't use the profiling interface properly and therefore doesn't behave like the others.  It screws up data in log files and the chart generation by the `process_logs` python as a result.

Basically all the heartbeats changes are just better build support, esp. for cross compiling (also now using Alex's `cmake` crate to help).  Also, I published both the bindings and abstraction crates on crates.io.  Additionally, they're relicensed to dual MIT/Apache-2.0.

The real changes are in the `energymon`-related crates and associated native C code.  They are also re-licensed now.  Energy monitoring capabilities are only enabled with the `energy-profiling` feature, which is disabled by default.

**Comment by connorimes** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/heartbeats/characterize.py, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9926#-KCMxxo3b_GU-6G136O8:-KCN0v-e4x02RnwFgsRx:-149822511) ([raw file](https://github.com/servo/servo/blob/2bf1e66203c55a894a81705770457fc6fda20d22/tests/heartbeats/characterize.py#L26)):*
This is intentional - this profiler category doesn't use the profiling interface properly and causes problems.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9926)*

**Comment by larsbergstrom** [comment]
Reviewed 1 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/parser.out, line  \[r1\]](https://reviewable.io:443/reviews/servo/servo/9926#-KCMyeLbIe5FpNFgHBf8:-KCN1p2eYEpkfznWn2-b:1300553112) ([raw file](https://github.com/servo/servo/blob/2bf1e66203c55a894a81705770457fc6fda20d22/components/script/parser.out#L)):*
This file was removed in #9817. Does this PR need a rebase?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9926)*

**Comment by asajeffrey** [comment]
I'm going to regret asking this, but... over in https://github.com/libheartbeats/heartbeats-simple/blob/master/LICENSE the copyright holder is given as "The University of Chicago". Is this correct?

**Comment by connorimes** [comment]
Ah, I didn't even realize I had added a deleted file back in.  Maybe something happened pushing/popping my git stash when I pulled to get the latest changes before making my branch.  Sorry about that - good catch.  I've deleted the file and rebased my commit.

**Comment by asajeffrey** [comment]
Reviewed 1 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9926)*

**Comment by connorimes** [comment]
We chose the 3-clause BSD license when we released Heartbeats source as part of other work.  The `heartbeats-simple` project is originally based on that source.  The BSD license allows source redistribution as long as the LICENSE file is retained.  We've previously included these projects in servo, so this is not new.
When I began development on the `energymon` projects, I just applied the same license, but I can easily relicense `energymon` since I'm the only contributor ever.
All the rust code (sys bindings and abstraction crates) are dual-licensed under MIT/Apache-2.0 which I started work on last summer while I was with Mozilla.  They were originally MIT only, which is what was recommended to me at the time.

**Comment by asajeffrey** [comment]
Is UoC the copyright holder? I'm a bit concerned that if they are, we need someone to officially bless the licensing.

**Comment by connorimes** [comment]
I'm a graduate student at UofC and primary developer of the libraries.  Per the licensing, nobody at UofC's end has to bless the redistribution, nor is it a copyleft license.  If you need blessing from inside Mozilla, I think @larsbergstrom can provide that.

**Comment by asajeffrey** [comment]
Sorry to harp on about this, but is UoC the copyright holder? If they are, we need to think about the licensing. If not, could you update the LICENSE files?

**Comment by connorimes** [comment]
I've updated the license files for the `energymon` project to be dual MIT/Apache-2.0.

**Comment by asajeffrey** [comment]
Thanks!

**Comment by asajeffrey** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9926)*

**Comment by asajeffrey** [comment]
@larsbergstrom did tests/heartbeats/characterize_android.py look good to you?

@bors-servo try

**Comment by larsbergstrom** [comment]
@asajeffrey I had marked it OK/reviewed in reviewable, but it occurs to me now that instead of passing `-g` for the graphics backend, it should probably pass `-w` for the webrender backend. The old "GPU backend" is more than deprecated (it basically doesn't work at all, AFAIK), but the new webrender backend should be very interesting, from a power perspective!

**Comment by asajeffrey** [comment]
@connorimes can you replace `-g` by `-w`? After that, we can land this PR.

**Comment by connorimes** [comment]
This `-g` option was a carry-over from the `characterize.py` script (`characterize_android.py` is a simplified version of this).  Neither script was intended to provide complete option support for launching servo.  I threw the Android one together recently when I needed to collect data from Android.  I'm not sure anybody is actually using these scripts (nobody else has ever modified them AFAIK), I just thought I'd include the new Android one since the other was already there.  Realistically these scripts should be combined into one and be redesigned s.t. they don't need to be modified when servo's options change.  I haven't had the time, and it would be great if a real python programmer took up the task since I mostly hack my way through it.

I'll make the change.  Is `-w` Android-specific, or should I make the change in both scripts?  This PR is not intended to be script work, so let's please put off remaining script tasks until later.  I don't believe anything is in danger of breaking in the meantime.

**Comment by larsbergstrom** [comment]
I'm fine with not merging the scripts now. '-w' is specific to both. I'd prefer not to have usages of the '-g' option around because it's non-functional (and will probably be removed once webrender becomes the default).

**Comment by connorimes** [comment]
I'm just about done with the changes, I'll get it in.

**Comment by asajeffrey** [comment]
Reviewed 1 of 2 files at r4.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9926)*

**Comment by connorimes** [comment]
I rebased this yesterday afternoon.  Did it become unmergeable again?  Or is something else missing?

**Comment by larsbergstrom** [comment]
@bors-servo r=asajeffrey

Unlike nearly every other action on GitHub, rebases / pushing extra commits to a branch does not send any update mails.

**Comment by connorimes** [comment]
I knew that but I thought highfive automatically picked it up.  Thanks.

**Comment by asajeffrey** [comment]
@bors-servo: retry
 * #9012

**Pull request merged**
