### PR TITLE
Make button elements activatable.

### PR DESCRIPTION
**Pull request by jdm**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8109)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Regression test?

**Comment by jdm** [comment]
I'll see if form.submit() could catch this.

**Comment by frewsxcv** [comment]
Also, according to travis, there are build issues

**Comment by jdm** [comment]
I have a WPT test which is waiting on a fix for #8113.

**Comment by frewsxcv** [comment]
#8113 has been resolved

**Comment by jdm** [comment]
Updated!

**Comment by eefriedman** [comment]
```
  ▶ OK [expected TIMEOUT] /DOMEvents/tests/approved/dispatchEvent.click.checkbox.html

  ▶ Unexpected subtest result in /DOMEvents/tests/approved/dispatchEvent.click.checkbox.html:
  │ FAIL [expected PASS] Test Description: MouseEvent: Default action is performed when a synthetic click event is dispatched on a checkbox element
  │   → assert_array_equals: property 0, expected true but got false
  │ 
  │ TestEvent/<@http://web-platform.test:8000/DOMEvents/tests/approved/dispatchEvent.click.checkbox.html:55:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ TestEvent@http://web-platform.test:8000/DOMEvents/tests/approved/dispatchEvent.click.checkbox.html:53:1
  │ TestEvent@http://web-platform.test:8000/DOMEvents/tests/approved/dispatchEvent.click.checkbox.html:49:13
  └ window.onload@http://web-platform.test:8000/DOMEvents/tests/approved/dispatchEvent.click.checkbox.html:16:9

  ▶ OK [expected TIMEOUT] /DOMEvents/tests/submissions/Microsoft/converted/dispatchEvent.click.checkbox.html

  ▶ Unexpected subtest result in /DOMEvents/tests/submissions/Microsoft/converted/dispatchEvent.click.checkbox.html:
  │ FAIL [expected PASS] Test Description: MouseEvent: Default action is performed when a synthetic click event is dispatched on a checkbox element
  │   → assert_array_equals: property 0, expected true but got false
  │ 
  │ TestEvent/<@http://web-platform.test:8000/DOMEvents/tests/submissions/Microsoft/converted/dispatchEvent.click.checkbox.html:55:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ TestEvent@http://web-platform.test:8000/DOMEvents/tests/submissions/Microsoft/converted/dispatchEvent.click.checkbox.html:53:1
  │ TestEvent@http://web-platform.test:8000/DOMEvents/tests/submissions/Microsoft/converted/dispatchEvent.click.checkbox.html:49:13
  └ window.onload@http://web-platform.test:8000/DOMEvents/tests/submissions/Microsoft/converted/dispatchEvent.click.checkbox.html:16:9

  ▶ CRASH [expected TIMEOUT] /html/semantics/forms/the-button-element/button-events.html
  │ 
  │ thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(100) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } }', ../src/libcore/result.rs:741
  │ stack backtrace:
  │    1:        0x103141e08 - sys::backtrace::tracing::imp::write::h7d2881098672eadd7It
  │    2:        0x103143f4f - panicking::log_panic::_<closure>::closure.40649
  │    3:        0x1031439f2 - panicking::log_panic::h8037c21ca8707493MAx
  │    4:        0x10312eee6 - sys_common::unwind::begin_unwind_inner::h87d033c2dbe04bc77Ls
  │    5:        0x10312f2ce - sys_common::unwind::begin_unwind_fmt::h086b7999edf0c62fdLs
  │    6:        0x103141427 - rust_begin_unwind
  │    7:        0x103166530 - panicking::panic_fmt::h761c3d51c4df5175ZFK
  │    8:        0x101f2e335 - result::_<impl>::unwrap::unwrap::h17986274935423628741
  │    9:        0x101f4f0bf - workqueue::_<impl>::new::new::h6179496024418368859
  │   10:        0x101f30f5b - layout_task::_<impl>::new::h0d0f44fbe7e7b5617oq
  │   11:        0x101f2ea0b - sys_common::unwind::try::try_fn::try_fn::h2827801216446258168
  │   12:        0x103141248 - __rust_try
  │   13:        0x10313e34e - sys_common::unwind::try::inner_try::hdd63401dff52b04dFIs
  │   14:        0x101f2fd1a - boxed::_<impl>::call_box::call_box::h12730511991798588194
  │   15:        0x1031431dd - sys::thread::_<impl>::new::thread_start::h146dc2a2095e243ajVw
  │   16:     0x7fff84ed8059 - _pthread_body
  │   17:     0x7fff84ed7fd6 - _pthread_start
  │ thread 'thread 'LayoutWorker worker 1/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ stack backtrace:
  │ thread 'LayoutWorker worker 3/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ LayoutWorker worker 2/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(100) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │ thread 'LayoutWorker worker 4/6' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:741
  │    1:        0x103141e08 - sys::backtrace::tracing::imp::write::h7d2881098672eadd7It
  │ Pipeline failed in hard-fail mode.  Crashing!
  │    2:        0x103143f4f - panicking::log_panic::_<closure>::closure.40649
  │    3:        0x1031439f2 - panicking::log_panic::h8037c21ca8707493MAx
  │    4:        0x10312eee6 - sys_common::unwind::begin_unwind_inner::h87d033c2dbe04bc77Ls
  │    5:        0x10312f2ce - sys_common::unwind::begin_unwind_fmt::h086b7999edf0c62fdLs
  └    6:        0x103141427 - rust_begin_unwind

  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-spec-example.html:
  └ PASS [expected FAIL] Event handler listeners should be registered when they are first set to an object value (object "[object Object]").

  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-spec-example.html:
  └ PASS [expected FAIL] Event handler listeners should be registered when they are first set to an object value (function "function () {}").

  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-spec-example.html:
  └ PASS [expected FAIL] Event handler listeners should be registered when they are first set to an object value (object "42").

  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-spec-example.html:
  └ PASS [expected FAIL] Event handler listeners should be registered when they are first set to an object value (object "").

  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-spec-example.html:
  └ PASS [expected FAIL] Event handler listeners should be registered when they are first set to an object value (42).

  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-spec-example.html:
  └ PASS [expected FAIL] Event handler listeners should be registered when they are first set to an object value (null).

  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-spec-example.html:
  └ PASS [expected FAIL] Event handler listeners should be registered when they are first set to an object value (undefined).

  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-spec-example.html:
  └ PASS [expected FAIL] Event handler listeners should be registered when they are first set to an object value ("").

  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-spec-example.html:
  └ PASS [expected FAIL] Event handler listeners should be registered when they are first set to an object value.
```

**Comment by jdm** [comment]
All previously encountered test result changes are now updated accordingly.

**Pull request merged**
