### PR TITLE
Handle flex item cross sizing and minmax for flexbox in 2020

### PR DESCRIPTION
**Pull request by Manishearth**
Note: a lot more tests pass, however update-wpt is somehow not accepting them. I'm going to try and do an update again.

### CODE REVIEW

**Comment by pcwalton** [comment]
Looks good to me.

**Comment by Manishearth** [comment]
@bors-servo r=pcwalton

I updated expectations for the wrong folder :sheep:  . 49 new passing 2020 flex tests!

**Comment by Manishearth** [comment]
Actually this is buggy but it doesn't matter since it's buggy around its align-items behavior which is hardcoded anyway

**Comment by Manishearth** [comment]
Oh, no, it's not.

**Comment by SimonSapin** [comment]
CC https://github.com/servo/servo/pull/27334

**Pull request merged**
