### PR TITLE
Update web-platform-tests to revision 1ac278f94d0e86b88fc9f1eeb31ed2d2ef35b472

### PR DESCRIPTION
**Pull request by jgraham**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9386)

### CODE REVIEW

**Comment by jgraham** [comment]
Needs updated expectation data

**Comment by KiChjang** [comment]
Homu complains about manifest changed.

**Comment by jdm** [comment]
Looks like #8270 is back.

**Pull request merged**
