### PR TITLE
Document InheritTypes

### PR DESCRIPTION
**Pull request by Manishearth**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7395)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r-

Not so fast, didn't push changes.

**Comment by Manishearth** [comment]
@bors retry

```
Unexpected Results
==================

/webstorage/storage_session_setitem_quotaexceedederr.html
---------------------------------------------------------
CRASH expected TIMEOUT [Parent]
```

**Comment by frewsxcv** [comment]
@Manishearth I think you meant @bors-servo

**Comment by jdm** [comment]
@bors-servo: retry
* #7402

**Pull request merged**
