### PR TITLE
tidy.py: pass list of lines to each testing function

### PR DESCRIPTION
**Pull request by dsprenkels**
instead of whole content buffer

See #9060.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9066)

### CODE REVIEW

**Comment by dsprenkels** [comment]
Mention: @Wafflespeanut

**Comment by Wafflespeanut** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[python/tidy.py, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9066#-K6JkzNu3RIhQAc0tp2d:-K6JkzNwgpmAuaraPU_M:-2025934941) ([raw file](https://github.com/servo/servo/blob/20f904abca613a2f7f00a2de46734f81a4ad93d3/python/tidy.py#L76)):*
If we look at the license-checking mechanism (`licenseck.py`), it appears that the licenses (in comments) span at most 8 lines. So, let's join only the first 8 lines of contents.

---

*[python/tidy.py, line 528 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9066#-K6JthM-8l9oIKZ8luc5:-K6JthM0lKaSyYfriwZp:703134361) ([raw file](https://github.com/servo/servo/blob/20f904abca613a2f7f00a2de46734f81a4ad93d3/python/tidy.py#L528)):*
Let's add a bool to this function's argument (which could default to something depending on convenience), and split the `checking_functions` in `scan()` into two lists - one that has the functions which require the files to be read as a giant string, and the other which has those that need only an iterator.

Once that's done, let's modify this loop in such a way that we choose between `read` or `readlines` depending on the bool. That way, we can eliminate the `join` used elsewhere.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9066)*

**Comment by dsprenkels** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/tidy.py, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9066#-K6JkzNu3RIhQAc0tp2d:-K6KMhamcSjVVdX_6ZNu:1225155802) ([raw file](https://github.com/servo/servo/blob/20f904abca613a2f7f00a2de46734f81a4ad93d3/python/tidy.py#L76)):*
I am afraid that _if_ this (the line span of licenses) will change, this will just be an annoying bug. I would not mind waiting 50 microseconds per file instead.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9066)*

**Comment by dsprenkels** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[python/tidy.py, line 528 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9066#-K6JthM-8l9oIKZ8luc5:-K6L1VxP7z-gjVLiejtb:2091790057) ([raw file](https://github.com/servo/servo/blob/20f904abca613a2f7f00a2de46734f81a4ad93d3/python/tidy.py#L528)):*
Would you like this to be done in this pull request, or in a follow-up (maybe #8733)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9066)*

**Comment by Wafflespeanut** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[python/tidy.py, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9066#-K6JkzNu3RIhQAc0tp2d:-K6MjHCxpFSrx7UkSOgA:-828374105) ([raw file](https://github.com/servo/servo/blob/20f904abca613a2f7f00a2de46734f81a4ad93d3/python/tidy.py#L76)):*
Well, it could still be done by declaring a `MAX_LIC_LEN` at the top which gets the string of maximum length from the `licenses` list.

---

*[python/tidy.py, line 528 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9066#-K6JthM-8l9oIKZ8luc5:-K6MjqCwNWqTbBeK3zdd:1948342064) ([raw file](https://github.com/servo/servo/blob/20f904abca613a2f7f00a2de46734f81a4ad93d3/python/tidy.py#L528)):*
No, I think it'd be nice if we fix this as a part of this issue, since that's our goal - to pass file lines to the checking functions.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9066)*

**Comment by Wafflespeanut** [comment]
That being said, you can always work on another issue in the mean time :)

**Comment by Wafflespeanut** [comment]
One nit. Once that's clarified, squash the commits, and let's land it :)

+S-needs-squash +S-awaiting-answer  -S-awaiting-review

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/tidy.py, line 79 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9066#-K6THtkqNS2zvhHdwpml:-K6THtkrcp5ix4uPnAs5:1986133665) ([raw file](https://github.com/servo/servo/blob/ab96169400520c921b88af97b89481d8edbec597/python/tidy.py#L79)):*
Shouldn't this be `contents`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9066#-:-K6TB8_oryY5dcSIw1yD:-1612522316)*

**Comment by dsprenkels** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/tidy.py, line 79 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9066#-K6THtkqNS2zvhHdwpml:-K6TJ2YIPnuTYsUzdz3E:-426856308) ([raw file](https://github.com/servo/servo/blob/ab96169400520c921b88af97b89481d8edbec597/python/tidy.py#L79)):*
You are asolutely right. The idea was to scan each of the first lines, and not just the first 100 characters. I will fix this accordingly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9066)*

**Comment by Wafflespeanut** [comment]
@bors-servo r+

Thanks for doing this! :)

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9066#-:-K6TQ6kfA3VOFm9epxrj:-1270722369)*

**Pull request merged**
