### PR TITLE
layout: Allow inline elements to be containing blocks for absolutely-positioned elements.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5911)

### CODE REVIEW

**Comment by mbrubeck** [comment]
<sup>**[components/layout/flow.rs, line 1328 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5911#-JoGiqt-wVVhVMiAWI3Z)** ([raw file](https://github.com/servo/servo/blob/826b7222027b7b8b5df417998a1e4826aecb019a/components/layout/flow.rs#L1328)):</sup>
There's code in `multicol.rs` that still uses the old name for this fn, causing a compiler error.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/layout_task.rs @ r4
- components/layout/list_item.rs @ r4
- components/layout/multicol.rs @ r4
- components/layout/table.rs @ r1
- components/layout/table_caption.rs @ r1
- components/layout/table_cell.rs @ r1
- components/layout/table_colgroup.rs @ r1
- components/layout/table_row.rs @ r1
- components/layout/table_rowgroup.rs @ r4
- components/layout/table_wrapper.rs @ r4
- tests/ref/absolute_inline_containing_block_a.html @ r1
- tests/ref/absolute_inline_containing_block_ref.html @ r1
- tests/ref/basic.list @ r4

---

<sup>**[tests/ref/basic.list, line 45 \[r4\]](https://reviewable.io:443/reviews/servo/servo/5911#-Jo_Dj6QPBdibhHDn94R)** ([raw file](https://github.com/servo/servo/blob/8c2f81390d93d39760afb12b840062b20244857f/tests/ref/basic.list#L45)):</sup>
All but two of these files are missing.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by mbrubeck** [comment]
Reviewed files:
- components/gfx/display_list/mod.rs @ r4
- components/layout/block.rs @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by pcwalton** [comment]
It was merge fallout. Rebased and fixed. r? @mbrubeck

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/data.rs @ r1
- components/layout/display_list_builder.rs @ r4

---

<sup>**[components/layout/display_list_builder.rs, line 1494 \[r4\]](https://reviewable.io:443/reviews/servo/servo/5911#-Jo_nE1x4eGYCLLiiYAf)** ([raw file](https://github.com/servo/servo/blob/8c2f81390d93d39760afb12b840062b20244857f/components/layout/display_list_builder.rs#L1494)):</sup>
Should this be combined with the previous case using `|`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by mbrubeck** [comment]
Reviewed files:
- components/gfx/display_list/mod.rs @ r5
- components/layout/block.rs @ r5
- components/layout/construct.rs @ r5
- components/layout/display_list_builder.rs @ r5
- components/layout/layout_task.rs @ r5
- components/layout/table.rs @ r5
- components/layout/table_wrapper.rs @ r5
- tests/ref/basic.list @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/flow.rs @ r5
- components/layout/fragment.rs @ r5

---

<sup>**[components/layout/flow.rs, line 1381 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5911#-JofhxBB8qlq1TGWyofs)** ([raw file](https://github.com/servo/servo/blob/48b64e009087cb953b8cb6f62929b1f898613592/components/layout/flow.rs#L1381)):</sup>
Please add a doc comment.

---

<sup>**[components/layout/fragment.rs, line 1659 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5911#-JofiZWd5RaK1_C_M_PL)** ([raw file](https://github.com/servo/servo/blob/48b64e009087cb953b8cb6f62929b1f898613592/components/layout/fragment.rs#L1659)):</sup>
Can this be combined with the preceding pattern using `|`?

---

<sup>**[components/layout/fragment.rs, line 1824 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5911#-JofiyiG4gdGQbzuaD47)** ([raw file](https://github.com/servo/servo/blob/48b64e009087cb953b8cb6f62929b1f898613592/components/layout/fragment.rs#L1824)):</sup>
Should this be combined with the preceding match arm?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/inline.rs @ r5

---

<sup>**[components/layout/inline.rs, line 1458 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5911#-JojWI25fcFuPJIlnuyh)** ([raw file](https://github.com/servo/servo/blob/48b64e009087cb953b8cb6f62929b1f898613592/components/layout/inline.rs#L1458)):</sup>
This is O(n^2) in the worst case. If that's a concern, this loop could record indices as it goes, though it might get tricky if you can have multiple fragments from the same flow that are not consecutive...

---

<sup>**[components/layout/inline.rs, line 1467 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5911#-JojVuhckDVmdXNxPHML)** ([raw file](https://github.com/servo/servo/blob/48b64e009087cb953b8cb6f62929b1f898613592/components/layout/inline.rs#L1467)):</sup>
This looks unreachable to me, because we just found an InlineAbsolute fragment for this flow in self.fragments.  Isn't `containing_block_range_for_flow` guaranteed to find the same one or an earlier one?

---

<sup>**[components/layout/inline.rs, line 1581 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5911#-JojX_nxI3NtIs8n64Pk)** ([raw file](https://github.com/servo/servo/blob/48b64e009087cb953b8cb6f62929b1f898613592/components/layout/inline.rs#L1581)):</sup>
Nit: The `result` local isn't needed here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by mbrubeck** [comment]
Review complete; some minor comments on Reviewable above.

**Comment by pcwalton** [comment]
<sup>**[components/gfx/display_list/mod.rs, line 544 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5911#-JoHDbAScEPGe35DZjod)** ([raw file](https://github.com/servo/servo/blob/e8e8c5caa6e7015d8c60d265ee10fa7267f0c8de/components/gfx/display_list/mod.rs#L544)):</sup>
fasdfsadf

---

<sup>**[components/layout/fragment.rs, line 1659 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5911#-JofiZWd5RaK1_C_M_PL)** ([raw file](https://github.com/servo/servo/blob/48b64e009087cb953b8cb6f62929b1f898613592/components/layout/fragment.rs#L1659)):</sup>
Unfortunately not, because `InlineBlockFragmentInfo` and `InlineAbsoluteFragmentInfo` are different types.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by pcwalton** [comment]
Review comments addressed. r? @mbrubeck

**Comment by mbrubeck** [comment]
Reviewed files:
- components/gfx/display_list/mod.rs @ r6
- components/layout/block.rs @ r6
- components/layout/construct.rs @ r5
- components/layout/data.rs @ r1
- components/layout/display_list_builder.rs @ r6
- components/layout/flow.rs @ r6
- components/layout/fragment.rs @ r6
- components/layout/inline.rs @ r6
- components/layout/layout_task.rs @ r6
- components/layout/list_item.rs @ r4
- components/layout/multicol.rs @ r4
- components/layout/table.rs @ r6
- components/layout/table_caption.rs @ r1
- components/layout/table_cell.rs @ r1
- components/layout/table_colgroup.rs @ r1
- components/layout/table_row.rs @ r1
- components/layout/table_rowgroup.rs @ r4
- components/layout/table_wrapper.rs @ r6
- tests/ref/absolute_inline_containing_block_a.html @ r1
- tests/ref/absolute_inline_containing_block_ref.html @ r1
- tests/ref/basic.list @ r6

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by jdm** [comment]
```
failures:
    absolute_inline_containing_block_a.html == absolute_inline_containing_block_ref.html
```

**Comment by pcwalton** [comment]
Looks like that test failure was Linux-only (maybe bots-only)?

**Comment by mbrubeck** [comment]
I can reproduce the test failure locally on Linux; the box is offset downward 1px in `absolute_inline_containing_block_a.html`.

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/block.rs @ r8
- components/layout/construct.rs @ r7
- components/layout/fragment.rs @ r7, r8
- components/layout/inline.rs @ r7, r8
- components/layout/layout_task.rs @ r7
- components/layout/table.rs @ r8
- components/layout/table_cell.rs @ r8
- components/layout/table_row.rs @ r8
- components/layout/table_rowgroup.rs @ r8
- components/layout/table_wrapper.rs @ r8
- tests/ref/basic.list @ r7, r8

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5911)

**Comment by nox** [comment]
@pcwalton @mbrubeck Could one of you explain why do we need to check if any fragment is positioned in inline elements, instead of just checking whether the inline element itself is positioned?

**Comment by mbrubeck** [comment]
If I remember correctly, this is because there is not a 1:1 mapping between iinline *elements* and inline *flows*.  A single inline flow may contain fragments from multiple elements.  When traversing the flow tree, one can't simply look at "the inline element" of an inline flow.

**Pull request merged**
