### PR TITLE
Automatically generate Gecko style struct setters for most keyword properties

### PR DESCRIPTION
**Pull request by bholley**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10556)

### CODE REVIEW

**Comment by heycam** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ports/geckolib/properties.mako.rs, line 172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10556#-KFBxri_66pEGB6wcWmZ:-KFBxriamqUVqyxE2keh:969817851) ([raw file](https://github.com/servo/servo/blob/32fce3f159f8cb6a672fd44f048a32f469e8a54d/ports/geckolib/properties.mako.rs#L172)):*
The list-style-type representation is more complicated because we strings and support custom counters. I'm not sure about nsStyleTextOverflow.

---

*[ports/geckolib/properties.mako.rs, line 173 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10556#-KFByFBkljcz-enztcJx:-KFByFBkljcz-enztcJy:-1588172081) ([raw file](https://github.com/servo/servo/blob/32fce3f159f8cb6a672fd44f048a32f469e8a54d/ports/geckolib/properties.mako.rs#L173)):*
FWIW we plan to use enum classes in the future, and we may at some point convert all the existing style consts too.

---

*[ports/geckolib/properties.mako.rs, line 178 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10556#-KFBx3j0R1uYxgOuybbD:-KFBx3j0R1uYxgOuybbE:903634016) ([raw file](https://github.com/servo/servo/blob/32fce3f159f8cb6a672fd44f048a32f469e8a54d/ports/geckolib/properties.mako.rs#L178)):*
The spec changed about 6 months ago: https://drafts.csswg.org/css-writing-modes/#block-flow

---

*[ports/geckolib/properties.mako.rs, line 196 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10556#-KFByYb5sHd9TDRJK6uC:-KFByYb5sHd9TDRJK6uD:2088182223) ([raw file](https://github.com/servo/servo/blob/32fce3f159f8cb6a672fd44f048a32f469e8a54d/ports/geckolib/properties.mako.rs#L196)):*
Rather than wait until we've done all the alignments, maybe we can generate a check that the Gecko and Servo constant values match up and do a simple assignment if so?  Then the other branch with the match should be optimized away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10556)*

**Comment by bholley** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[ports/geckolib/properties.mako.rs, line 173 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10556#-KFByFBkljcz-enztcJx:-KFC5KggGLnGO9Y-Rejq:2025601237) ([raw file](https://github.com/servo/servo/blob/32fce3f159f8cb6a672fd44f048a32f469e8a54d/ports/geckolib/properties.mako.rs#L173)):*
I'm all for enum classes, though ideally we'd use a consistent representation to make the automatic code generation easier.

If we mass-convert later on, maybe we can take the opportunity to generate them automatically from some single source of truth?

---

*[ports/geckolib/properties.mako.rs, line 178 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10556#-KFBx3j0R1uYxgOuybbD:-KFC5gL_feNvBkj1azWn:-1090359583) ([raw file](https://github.com/servo/servo/blob/32fce3f159f8cb6a672fd44f048a32f469e8a54d/ports/geckolib/properties.mako.rs#L178)):*
Ok. So sideways-left and sideways-right should be considered servo-only properties (or even removed)? Or does sideways-right need to remain as a compat alias (like the MDN article suggests)?

---

*[ports/geckolib/properties.mako.rs, line 196 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10556#-KFByYb5sHd9TDRJK6uC:-KFC5zJXTWAx-xD-yEvn:1485255540) ([raw file](https://github.com/servo/servo/blob/32fce3f159f8cb6a672fd44f048a32f469e8a54d/ports/geckolib/properties.mako.rs#L196)):*
We can look into this at some point, but I think it's lower priority than getting everything bootstrapped. I'm not worried about solving the problem long-term. We can just manually reorder a few things and let the static asserts catch any errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10556)*

**Comment by heycam** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ports/geckolib/properties.mako.rs, line 173 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10556#-KFByFBkljcz-enztcJx:-KFC8Bc56KA8_lbGJcoF:1223384390) ([raw file](https://github.com/servo/servo/blob/32fce3f159f8cb6a672fd44f048a32f469e8a54d/ports/geckolib/properties.mako.rs#L173)):*
Yes, that sounds like a good plan. (I don't think anyone is working on the conversion to enum classes currently.)

---

*[ports/geckolib/properties.mako.rs, line 178 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10556#-KFBx3j0R1uYxgOuybbD:-KFC8rUXGmo-jfkPksso:191070018) ([raw file](https://github.com/servo/servo/blob/32fce3f159f8cb6a672fd44f048a32f469e8a54d/ports/geckolib/properties.mako.rs#L178)):*
Sorry, I linked to the writing-mode definition (which also changed) rather than text-orientation. I am not sure whether the sideways-right alias is indeed needed for compatibility, but Gecko (and the spec) does support that, and we still have a bunch of tests that use it. jkew would know. So let's leave sideways-right. I'm not sure what the state of Servo's vertical text support is, but sidways-left should be removed at some point.

(Gecko's writing-mode supports more values than Servo's does, but I guess that is a general issue that we'll need to audit for.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10556)*

**Comment by bholley** [comment]
Updated the commit message to note that, with @mauriocioc's work, the number of auto-generated property setter implementations rose from ~20 to ~45. Nice!

**Comment by SimonSapin** [comment]
r=me for the part outside `ports/geckolib`.

**Comment by bholley** [comment]
@bors-servo r=SimonSapin

Discussed with Simon. I'm fine with him rubber-stamping changes to geckolib coming from me, at least for now.

**Pull request merged**
