### PR TITLE
Refactor FileReader #6762 #6763 #6750 #6751

### PR DESCRIPTION
**Pull request by farodin91**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6807)

### CODE REVIEW

**Comment by jdm** [comment]
Makes sense! Thanks!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/filereader.rs, line 221 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6807#-JvJtwWBWAp3icNmtHsF)** ([raw file](https://github.com/servo/servo/blob/b28ce37f3d5b0dbd9ffc88803f57c36b3c8f0d05/components/script/dom/filereader.rs#L221)):</sup>
This can just return DOMString.

---

<sup>**[components/script/dom/filereader.rs, line 254 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6807#-JvJtynK2st3jq0zln57)** ([raw file](https://github.com/servo/servo/blob/b28ce37f3d5b0dbd9ffc88803f57c36b3c8f0d05/components/script/dom/filereader.rs#L254)):</sup>
This can just return DOMString.

---

<sup>**[components/script/dom/filereader.rs, line 328 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6807#-JvJu5dEUunpEJos6GUy)** ([raw file](https://github.com/servo/servo/blob/b28ce37f3d5b0dbd9ffc88803f57c36b3c8f0d05/components/script/dom/filereader.rs#L328)):</sup>
nit: space after `:`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6807)

**Comment by farodin91** [comment]
We need to wait until #6723 is merged!

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6807)

**Comment by farodin91** [comment]
I will squash this. if #6803 is merged!

But humo is slow!

**Pull request merged**
