### PR TITLE
Remove some unused extern crates.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9275)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
```
main.rs:28:1: 28:19 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:28 extern crate libc;
           ^~~~~~~~~~~~~~~~~~
main.rs:28:1: 28:19 help: add #![feature(libc)] to the crate attributes to enable
main.rs:210:23: 210:35 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:210     fn app_dummy() -> libc::c_void;
                                  ^~~~~~~~~~~~
main.rs:210:23: 210:35 help: add #![feature(libc)] to the crate attributes to enable
main.rs:224:5: 224:23 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:224     extern crate libc;
                ^~~~~~~~~~~~~~~~~~
main.rs:224:5: 224:23 help: add #![feature(libc)] to the crate attributes to enable
main.rs:226:9: 226:26 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:226     use self::libc::c_int;
                    ^~~~~~~~~~~~~~~~~
main.rs:226:9: 226:26 help: add #![feature(libc)] to the crate attributes to enable
main.rs:230:26: 230:39 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:230         use self::libc::{STDERR_FILENO, STDOUT_FILENO};
                                     ^~~~~~~~~~~~~
main.rs:230:26: 230:39 help: add #![feature(libc)] to the crate attributes to enable
main.rs:230:41: 230:54 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:230         use self::libc::{STDERR_FILENO, STDOUT_FILENO};
                                                    ^~~~~~~~~~~~~
main.rs:230:41: 230:54 help: add #![feature(libc)] to the crate attributes to enable
main.rs:234:25: 234:38 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:234         redirect_output(STDERR_FILENO);
                                    ^~~~~~~~~~~~~
main.rs:234:25: 234:38 help: add #![feature(libc)] to the crate attributes to enable
main.rs:235:25: 235:38 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:235         redirect_output(STDOUT_FILENO);
                                    ^~~~~~~~~~~~~
main.rs:235:25: 235:38 help: add #![feature(libc)] to the crate attributes to enable
main.rs:240:25: 240:41 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:240     struct FilePtr(*mut self::libc::FILE);
                                    ^~~~~~~~~~~~~~~~
main.rs:240:25: 240:41 help: add #![feature(libc)] to the crate attributes to enable
main.rs:244:33: 244:38 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:244     fn redirect_output(file_no: c_int) {
                                            ^~~~~
main.rs:244:33: 244:38 help: add #![feature(libc)] to the crate attributes to enable
main.rs:245:13: 245:31 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:245         use self::libc::fdopen;
                        ^~~~~~~~~~~~~~~~~~
main.rs:245:13: 245:31 help: add #![feature(libc)] to the crate attributes to enable
main.rs:246:13: 246:30 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:246         use self::libc::fgets;
                        ^~~~~~~~~~~~~~~~~
main.rs:246:13: 246:30 help: add #![feature(libc)] to the crate attributes to enable
main.rs:247:26: 247:30 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:247         use self::libc::{pipe, dup2};
                                     ^~~~
main.rs:247:26: 247:30 help: add #![feature(libc)] to the crate attributes to enable
main.rs:247:32: 247:36 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:247         use self::libc::{pipe, dup2};
                                           ^~~~
main.rs:247:32: 247:36 help: add #![feature(libc)] to the crate attributes to enable
main.rs:254:29: 254:34 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:254             let mut pipes: [c_int; 2] = [ 0, 0 ];
                                        ^~~~~
main.rs:254:29: 254:34 help: add #![feature(libc)] to the crate attributes to enable
main.rs:255:13: 255:17 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:255             pipe(pipes.as_mut_ptr());
                        ^~~~
main.rs:255:13: 255:17 help: add #![feature(libc)] to the crate attributes to enable
main.rs:256:13: 256:17 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:256             dup2(pipes[1], file_no);
                        ^~~~
main.rs:256:13: 256:17 help: add #![feature(libc)] to the crate attributes to enable
main.rs:258:38: 258:44 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:258             let input_file = FilePtr(fdopen(pipes[0], mode.as_ptr()));
                                                 ^~~~~~
main.rs:258:38: 258:44 help: add #![feature(libc)] to the crate attributes to enable
main.rs:264:21: 264:26 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
main.rs:264                     fgets(read_buffer.as_mut_ptr(), (read_buffer.len() as i32)-1, input_file);
                                ^~~~~
main.rs:264:21: 264:26 help: add #![feature(libc)] to the crate attributes to enable
main.rs:35:5: 35:14 warning: unused import, #[warn(unused_imports)] on by default
main.rs:35 use gleam::gl;
               ^~~~~~~~~
main.rs:36:28: 36:37 warning: unused import, #[warn(unused_imports)] on by default
main.rs:36 use offscreen_gl_context::{GLContext, NativeGLContext};
                                      ^~~~~~~~~
main.rs:36:39: 36:54 warning: unused import, #[warn(unused_imports)] on by default
main.rs:36 use offscreen_gl_context::{GLContext, NativeGLContext};
                                                 ^~~~~~~~~~~~~~~
error: aborting due to 19 previous errors
Could not compile `servo`.
```

**Comment by Ms2ger** [comment]
Fixed

**Pull request merged**
