### PR TITLE
subtlecrypto: Don't throw exceptions twice when converting to Algorithm object

### PR DESCRIPTION
**Pull request by simonwuelker**
Removes match statements like
```rust
let Ok(ConversionResult::Success(algorithm)) = Algorithm::new(cx, value.handle())
else {
    return Err(Error::Syntax);
};
```
These don't cause issues if `Algorithm::new` returns `Ok(ConversionResult::Failure`, but in the case of `Err(())` the implementation already called `throw_type_error` and we must not throw an additional Syntax error, otherwise we'll crash.

Luckily, this case is already handled elsewhere by the `value_from_js_object` macro.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

### CODE REVIEW

**Review by msub2 — COMMENTED** [review]
Very nice, appreciate the added test. Do you think it'd make sense to add similar empty alg checks in the other WebCrypto tests?

**Comment by simonwuelker** [comment]
> Do you think it'd make sense to add similar empty alg checks in the other WebCrypto tests?

Perhaps! I wasn't sure earlier today, because it felt like a silly thing to test for. But when I think about it now, I probably should add some more test cases. I'll do that tomorrow, thanks for the review.

**Comment by simonwuelker** [comment]
I added tests for `generateKey`/`importKey`. I think that's enough coverage, any implementation is going to run into these methods quickly. The other algorithms(`deriveBits` for example) support many different variants, and I don't really want to add tests for all of them.

**Comment by simonwuelker** [comment]
CI fails due to https://github.com/servo/servo/pull/34257, going to rebase once that's merged.

**Review by msub2 — COMMENTED** [review]
Looks good! This has my stamp @jdm

**Review by jdm — APPROVED** [review]
Thanks for the tests!

**Pull request merged**
