### PR TITLE
Replace iterator struct with anonymous return iterator type.

### PR DESCRIPTION
**Pull request by frewsxcv**
```
hi servo. it's been
some time. here's a pull request.
i hope you like it.
```

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17488)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
This witchcraft, but I like it.

**Comment by frewsxcv** [comment]
@bors-servo p=-7

not really an important pr

**Comment by frewsxcv** [comment]
oh, there's a new 'tree closed' thing now in the queue. guess i'll bring this back to 0

@bors-servo p=0

**Pull request merged**
