### PR TITLE
tests/net: Update testing cert.

### LINKED ISSUE #19634: [CI failed] [test-unit] thread 'fetch::test_fetch_with_hsts' panicked at 'called `Option::unwrap()` on a `None` value'
`./mach test-unit` in current master  bcdb82b

This make all CI failed!

```
---- fetch::test_fetch_with_hsts stdout ----
	thread 'fetch::test_fetch_with_hsts' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  11: net_tests::fetch::test_fetch_with_hsts
             at ./fetch.rs:558
  12: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1491
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/libtest/lib.rs:142
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99


failures:
    fetch::test_fetch_with_hsts

test result: FAILED. 421 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

### PR DESCRIPTION
**Pull request by emilio**
Fixes #19634

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19640)

### CODE REVIEW

**Comment by emilio** [comment]
We should have for 10y. r? @jdm

**Comment by tigercosmos** [comment]
Fies -> Fixes?

**Comment by emilio** [comment]
Actually, given this is blocking any other PR and this is a test-only change:

@bors-servo r+

**Comment by jdm** [comment]
Thanks for fixing this!

**Pull request merged**
