### PR TITLE
Optimize `TextRun::advance_for_range`.

### PR DESCRIPTION
**Pull request by pcwalton**
The combined effects of these optimizations move `advance_for_range` from #1 in the layout profile on all sites I tested to #2, #3, or #4, depending on the site.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8990)

### CODE REVIEW

**Comment by samlh** [comment]
Is a text run being freed and a new one being created at the same location an issue here? Or is it unlikely to cause a problem in practice?

**Comment by pcwalton** [comment]
@samlh Added a mitigation for this (always safe because TextRuns are always Arc'd).

**Comment by mbrubeck** [comment]
-S-awaiting-review +S-fails-tidy 

r=mbrubeck with the tidy failure fixed

```
./components/gfx/text/text_run.rs:18: trailing whitespace
```

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8990#-:-K5bp5o_vAx8KEgiHws_:789680103)*

**Comment by frewsxcv** [comment]
This pull request apparently caused a regression: https://github.com/servo/servo/issues/9057

**Pull request merged**
