### PR TITLE
Update mozjs.

### PR DESCRIPTION
**Pull request by emilio**
Peeks up https://github.com/servo/rust-mozjs/pull/408.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20419)

### CODE REVIEW

**Comment by jdm** [comment]
```
error: variable does not need to be mutable
  --> components/script/dom/dommatrix.rs:64:9
   |
64 |         mut array: CustomAutoRooterGuard<Float32Array>)
   |         ---^^^^^^
   |         |
   |         help: remove this `mut`
   |
   = note: `-D unused-mut` implied by `-D warnings`

error: variable does not need to be mutable
  --> components/script/dom/dommatrix.rs:73:9
   |
73 |         mut array: CustomAutoRooterGuard<Float64Array>)
   |         ---^^^^^^
   |         |
   |         help: remove this `mut`

error: variable does not need to be mutable
   --> components/script/dom/dommatrixreadonly.rs:348:9
    |
348 |         mut array: CustomAutoRooterGuard<Float32Array>)
    |         ---^^^^^^
    |         |
    |         help: remove this `mut`

error: variable does not need to be mutable
   --> components/script/dom/dommatrixreadonly.rs:358:9
    |
358 |         mut array: CustomAutoRooterGuard<Float64Array>)
    |         ---^^^^^^
    |         |
    |         help: remove this `mut`

error: aborting due to 4 previous errors

error: Could not compile `script`.

```

**Comment by emilio** [comment]
@bors-servo r=jdm

 * Outdated tree, whoops

**Pull request merged**
