### PR TITLE
Add missing action in CreateContextualFragment method

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
r? @nox

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14210)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Test please :)

**Comment by nox** [comment]
> 18:38 &lt;nox> imperio: The code is exactly what I wanted, but it should pass more tests with it so I'll have to experiment locally.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by nox** [comment]
Please squash everything. The only separate commit I wanted was for the whitespace-only changes in expectations.

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by nox** [comment]
Nice, more passing tests. ^

**Comment by GuillaumeGomez** [comment]
Urg.

**Pull request merged**
