### PR TITLE
Issue #9042: Report incorrect number of spaces around => in the style checker

### PR DESCRIPTION
**Pull request by simartin**
Fixes https://github.com/servo/servo/issues/9042

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9055)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
This looks nice. Only one nit :)

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/tidy.py, line 317 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6CrvEaZkSk3a0c2cG7:-K6CrvEbehwEBc7P_pyS:835597525) ([raw file](https://github.com/servo/servo/blob/c6f95ed1dea2620287dc649abba330c7b472f2be/python/tidy.py#L317)):*
Nit: I suppose we could just use `line.find` since we're not really doing a complex regex match. Moreover, if we make use of `find` we could just use the index to check for spaces (by this way, we can also avoid multiple searches)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055#-:-K6Cu7BCvfC3iZKOkjx4:-526781972)*

**Comment by simartin** [comment]
*[python/tidy.py, line 317 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6CrvEaZkSk3a0c2cG7:-K6Cx05Bl2B-Cb3sm6z9:-1399305837) ([raw file](https://github.com/servo/servo/blob/c6f95ed1dea2620287dc649abba330c7b472f2be/python/tidy.py#L317)):*
Yes indeed; update is coming up

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055)*

**Comment by simartin** [comment]
Thanks for the review. I've replaced the first test by a call to find, but I've kept the rest as regexp matching for readability (catching all kinds of whitespaces won't be very readable). I also check for whitespace before => because patterns like "Err(_)=>" are not caught

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055#-:-K6CxBcNxxMRFpESpu_h:-1366385192)*

**Comment by Wafflespeanut** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[python/tidy.py, line 317 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6CyJzBfQVj6MCKz3g9:-K6CyJzCb-P5NtK64jUw:-895723532) ([raw file](https://github.com/servo/servo/blob/e9f4211f4b9e7836ef5dde5483e1cef439715fc5/python/tidy.py#L317)):*
Since we don't actually have to check for all spaces, why can't we do this?

``` python
match_idx = line.find('=>')
if match != -1:
    if line[match_idx - 1] != ' ':
        # missing space ...
    elif line[match_idx + 2] != ' ':
        # missing space ...
    elif line[match_idx + 3] == ' ':
        # extra space ...
```

This also avoids multiple searches, right?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055)*

**Comment by simartin** [comment]
*[python/tidy.py, line 317 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6CyJzBfQVj6MCKz3g9:-K6D2TQAZQl0N9WDVul7:-1860777323) ([raw file](https://github.com/servo/servo/blob/e9f4211f4b9e7836ef5dde5483e1cef439715fc5/python/tidy.py#L317)):*
It wouldn't work if we have for instance \t instead of spaces, would it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055)*

**Comment by Wafflespeanut** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[python/tidy.py, line 317 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6CyJzBfQVj6MCKz3g9:-K6D3exEfXhfk1zzXjWY:1511519916) ([raw file](https://github.com/servo/servo/blob/e9f4211f4b9e7836ef5dde5483e1cef439715fc5/python/tidy.py#L317)):*
No, but we should enforce making use of space and newlines (no tabs!). I just realized that we already use newlines in match arms at various places. So, the only additional change would be

``` python
match_idx = line.find('=>')
if match != -1:
    if line[match_idx - 1] != ' ':
        # missing space ...
    elif line[match_idx + 2] != ' ':
        if line[match_idx + 2] != '\n'
            # missing space ...
    elif line[match_idx + 3] == ' ':
        # extra space ...
```

I'm sorry that I'm being nitpicky here. The reason I'm obsessed about `re.search` is because we have about 8k lines of code in Servo that has `=>`, and [this is somewhat expensive](https://stackoverflow.com/q/4901523/). So, we should try to avoid it for cases where we have an alternative.

Well, I agree that there are plenty of regex searches in tidy already. I'm planning to refactor it someday soon. That said, I'll leave this decision to someone else (I'm probably biased about this :P)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055)*

**Comment by simartin** [comment]
*[python/tidy.py, line 317 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6CyJzBfQVj6MCKz3g9:-K6E7sB0qBMxaGBbH21V:633013797) ([raw file](https://github.com/servo/servo/blob/e9f4211f4b9e7836ef5dde5483e1cef439715fc5/python/tidy.py#L317)):*
Makes sense, thanks. PR update will come shortly

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055)*

**Comment by jdm** [comment]
I believe
```python
    elif line[match_idx + 2] != ' ':
        if line[match_idx + 2] != '\n'
```
could also be written as:
```python
    elif line[match_idx + 2] not in [' ', '\n']:
```

**Comment by Wafflespeanut** [comment]
@jdm Yeah, that works. I'm pretty sure I thought of that back then, but I now forget why I chose not use it. *(sigh)*

**Comment by Wafflespeanut** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[python/tidy.py, line 319 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6EldguT5hAfHM826Cm:-K6EldgvdUTEggbwE4XY:-971567075) ([raw file](https://github.com/servo/servo/blob/2b8fb6031649ca97fc643d31e0d31ec43b96d827/python/tidy.py#L319)):*
We don't want this `arrow_pos > 0`, because I'm pretty sure almost all the cases are indented (and so, the lines always begin with spaces). But, if you really insist, I suggest the pythonic way - `if arrow_pos and ...` :)

---

*[python/tidy.py, line 321 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6EmAgTYsBkY90PyRqu:-K6EmAgTYsBkY90PyRqv:-1549134657) ([raw file](https://github.com/servo/servo/blob/2b8fb6031649ca97fc643d31e0d31ec43b96d827/python/tidy.py#L321)):*
We really don't want this `arrow_pos + 2`, because the end of the line will definitely be a newline or a space (that's how we split the lines). Also, you forgot to include newline here. See @jdm's comment...

---

*[python/tidy.py, line 323 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6EnkKrdC6hY00unQEj:-K6EnkKs-9B5l2C0aA3G:768545746) ([raw file](https://github.com/servo/servo/blob/2b8fb6031649ca97fc643d31e0d31ec43b96d827/python/tidy.py#L323)):*
This is okay, but I now realize that we've used `len(line)` about 4 times in `check_rust`. So, let's declare a `line_length` at the start of the iteration, and replace all those lengths.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055)*

**Comment by simartin** [comment]
*[python/tidy.py, line 319 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6EldguT5hAfHM826Cm:-K6FJVDoD5cWv-1qhhN0:-1996583732) ([raw file](https://github.com/servo/servo/blob/2b8fb6031649ca97fc643d31e0d31ec43b96d827/python/tidy.py#L319)):*
Heading whitespaces are removed there: line = original_line.strip() (currently line 250), so line[arrow_pos - 1] might be not where we expect.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055)*

**Comment by simartin** [comment]
*[python/tidy.py, line 321 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6EmAgTYsBkY90PyRqu:-K6FOKFQDStOZlfxCyJ2:-1101591875) ([raw file](https://github.com/servo/servo/blob/2b8fb6031649ca97fc643d31e0d31ec43b96d827/python/tidy.py#L321)):*
I don't think it's true since line is original_line stripped, so \n and trailing spaces are removed in line already

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055)*

**Comment by Wafflespeanut** [comment]
The PR looks great!

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/tidy.py, line 319 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9055#-K6EldguT5hAfHM826Cm:-K6HOejCSF1DM-Tx2bHj:51631245) ([raw file](https://github.com/servo/servo/blob/2b8fb6031649ca97fc643d31e0d31ec43b96d827/python/tidy.py#L319)):*
Oops, didn't notice that, sorry :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9055#-:-K6HOjxXTYJWqpaU2KKE:383590794)*

**Comment by Wafflespeanut** [comment]
*(sigh)*

**Comment by KiChjang** [comment]
```

Ran 3737 tests finished in 212.0 seconds.
  • 3736 ran as expected. 709 tests skipped.
  • 1 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/css/nth_last_of_type_pseudo_a.html
  └   → /_mozilla/css/nth_last_of_type_pseudo_a.html c368d1126a9f5412469b9167a2622a0d43593d96
/_mozilla/css/nth_last_of_type_pseudo_b.html c568e8f044d5faec2a239694ad297caffcb9a00e
Testing c368d1126a9f5412469b9167a2622a0d43593d96 == c568e8f044d5faec2a239694ad297caffcb9a00e
```

**Comment by KiChjang** [comment]
@bors-servo retry
* #9063

**Pull request merged**
