### PR TITLE
Use presentation hints correctly for the dimensions of `<img>`.

### PR DESCRIPTION
**Pull request by eefriedman**
Mostly straightforward; includes some extra fixes to make `<canvas>`
work the same way as `` for reflow.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8531)

### CODE REVIEW

**Comment by eefriedman** [comment]
Hmm... looks like there's pretty good coverage for this stuff in wpt already; I'll just throw a small test into the HTML testsuite specifically checking dimension parsing.  (I'll also have to figure out how I introduced a crash...)

**Comment by eefriedman** [comment]
Okay; everything should be set new except that I didn't update the manifest for the new test (#8535),

**Comment by eefriedman** [comment]
Rebased, should be complete.

@bors-servo try

r? @pcwalton for the layout bits.

**Comment by jdm** [comment]
@bors-servo: retry
* #8616

**Comment by pcwalton** [comment]
Needs a rebase

**Comment by eefriedman** [comment]
@pcwalton Rebased.

**Comment by pcwalton** [comment]
@eefriedman I assume there are no functional changes?

**Comment by eefriedman** [comment]
No.

**Comment by jdm** [comment]
Rebased in #9743.

**Pull request closed without merging**
