### PR TITLE
Disable TLS compression

### PR DESCRIPTION
**Pull request by alex**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

This prevents the CRIME attack.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12035)

### CODE REVIEW

**Comment by Ms2ger** [comment]
CC @djc

**Comment by frewsxcv** [comment]
A couple resources about this:

* https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2012/september/details-on-the-crime-attack/
* https://blog.qualys.com/ssllabs/2012/09/14/crime-information-leakage-attack-against-ssltls

**Comment by larsbergstrom** [comment]
cc @avadacatavra :-)

**Comment by frewsxcv** [comment]
Thanks for catching this @alex!

**Pull request merged**
