### PR TITLE
Make JSTraceable for DomRefCell<T> panic if cell is mutably borrowed

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19872)

### CODE REVIEW

**Comment by nox** [comment]
INCREDIBRU, I did not expect this to succeed.

**Comment by emilio** [comment]
:shipit:?

**Comment by jdm** [comment]
Yeah, this is probably the right choice.

**Comment by nox** [comment]
@jdm r=you?

**Comment by jdm** [comment]
R=me

**Pull request merged**
