### PR TITLE
Implement HTMLDataElement#value

### LINKED ISSUE #12966: Implement HTMLDataElement#value
We already have convenient macros defined for reflecting content attributes. Look into `make_getter` and `make_setter` for accomplishing this task.

Spec: https://html.spec.whatwg.org/multipage/semantics.html#dom-data-value
Files: `components/script/dom/webidls/HTMLDataElement.webidl`, `components/script/dom/htmldataelement.rs`
Test: None yet, but one that tests for the behaviour of the `value` IDL attribute should be [created](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) under `tests/wpt/web-platform-tests/html/semantics/text-level-semantics/the-data-element/` (Use `./mach create-wpt <path>` for creating WPT tests)

### PR DESCRIPTION
**Pull request by ofekd**
Implement HTMLDataElement#value

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12966

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13028)

### CODE REVIEW

**Comment by KiChjang** [comment]
Thanks for working on this! If you would squash your commits into one I'll happily land this :).

**Comment by ofekd** [comment]
@KiChjang done :)

**Comment by KiChjang** [comment]
@bors-servo r+

Thanks!

**Comment by KiChjang** [comment]
You'll need to update the test expectations under `tests/wpt/metadata/`. The ini files that mark the tests as failing needs to be removed (by default, no entry means a PASS).

**Comment by ofekd** [comment]
@KiChjang updated, I hope it's good now

**Pull request merged**
