### PR TITLE
Reject websocket protocol requests that don't match https://tools.iet…

### PR DESCRIPTION
**Pull request by jdm**
…f.org/html/rfc6455#section-4.1 .

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6694)

### CODE REVIEW

**Comment by jdm** [comment]
There are some more test expectation updates incoming, so hang tight.

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/webidls/WebSocket.webidl, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6694#-JuohIucW96AcaQptNpA)** ([raw file](https://github.com/servo/servo/blob/05beb9980788d16040725da7275143aa069947df/components/script/dom/webidls/WebSocket.webidl#L7)):</sup>
File a followup for the array form

---

<sup>**[components/script/dom/websocket.rs, line 109 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6694#-Juoi2dkMqc-sfp2vXoA)** ([raw file](https://github.com/servo/servo/blob/05beb9980788d16040725da7275143aa069947df/components/script/dom/websocket.rs#L109)):</sup>
No need to allocate here. `as_slice()` would work here, or inline it if you want to avoid its instability.

---

<sup>**[components/script/dom/websocket.rs, line 121 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6694#-JuoiehQjwE09S5dQRna)** ([raw file](https://github.com/servo/servo/blob/05beb9980788d16040725da7275143aa069947df/components/script/dom/websocket.rs#L121)):</sup>
`protocols[i+1..].iter()`; `any()`

---

<sup>**[components/script/dom/websocket.rs, line 125 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6694#-JuoirAeBQ6BrvfK_l58)** ([raw file](https://github.com/servo/servo/blob/05beb9980788d16040725da7275143aa069947df/components/script/dom/websocket.rs#L125)):</sup>
`any()`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6694)

**Comment by Ms2ger** [comment]
Reviewed 1 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6694)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6694)

**Pull request merged**
