### PR TITLE
Enable flexbox for flexbox tests.

### PR DESCRIPTION
**Pull request by jdm**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9766)

### CODE REVIEW

**Comment by Ms2ger** [comment]
r+ when you're don

**Comment by KiChjang** [comment]
```
Ran 4607 tests finished in 228.0 seconds.
  • 4606 ran as expected. 1374 tests skipped.
  • 1 tests timed out unexpectedly
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ TIMEOUT [expected OK] /websockets/opening-handshake/003.html

  ▶ Unexpected subtest result in /websockets/opening-handshake/003.html:
  │ TIMEOUT [expected PASS] WebSockets: origin
  └   → Test timed out
```
Are these new intermittents?

**Comment by jdm** [comment]
@bors-servo: retry
* #9777

**Pull request merged**
