### PR TITLE
Moving third_party/webrender to chrono and std::time::Duration

### PR DESCRIPTION
**Pull request by aadi58002**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fixes part of #30150

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because these changes remove a old library (time) with a better maintained library (chorno)

### CODE REVIEW

**Comment by aadi58002** [comment]
It took sometime to move things over. Originally i tried to move every thing as once ( later found out it was not a good idea but it was fun ). 

If you have any feedback related to the changes i have made it is very welcome. I think i have named changed things which take time as consideration to duration if i have changed some field which i should not have let me know we can discuss on it.

Also i noticed when i ran `./mach cargo-clippy` it suggested many many changes. I am not sure if that is intended or not.

**Comment by sagudev** [comment]
Webrender is sourced from mozilla and servo is only it's downstream user (that's why it is in folder named `third_party`). So we need to maintain all our [changes to webrender as separate patches](https://github.com/servo/servo/tree/master/third_party/webrender/patches). IMO it's not worth maintaining patch.

[A quick look over all webrender usages of time create](https://searchfox.org/mozilla-central/search?q=time%3A%3A&path=gfx%2Fwr%2Fwebrender&case=false&regexp=false) reveals it's only used for `precise_time_ns` [to create Durations](https://searchfox.org/mozilla-central/search?q=precise_time_ns&path=gfx%2Fwr%2Fwebrender&case=false&regexp=false) or for debugging messages, which can all be replaced with `std::time::Instant`, but this should be proposed to upstream first.

**Comment by aadi58002** [comment]
> Webrender is sourced from mozilla and servo is only it's downstream user (that's why it is in folder named `third_party`). So we need to maintain all our [changes to webrender as separate patches](https://github.com/servo/servo/tree/master/third_party/webrender/patches). IMO it's not worth maintaining patch.
> 
> [A quick look over all webrender usages of time create](https://searchfox.org/mozilla-central/search?q=time%3A%3A&path=gfx%2Fwr%2Fwebrender&case=false&regexp=false) reveals it's only used for `precise_time_ns` [to create Durations](https://searchfox.org/mozilla-central/search?q=precise_time_ns&path=gfx%2Fwr%2Fwebrender&case=false&regexp=false) or for debugging messages, which can all be replaced with `std::time::Instant`, but this should be proposed to upstream first.

Thanks for the info about the third party folder being mozilla downstream. Didn't knew that.
I start working on one of the crates in the components folder.I might create a bug report of this over on mozilla bug tracker.For the time being I keep this PR open to see what the others think about what to do with this PR.

**Comment by mrobinson** [comment]
I agree with @sagudev that the contents of the 'third_party' directory are not the best place to do this work for the reasons mentioned. There's a chance that the webrender upstream will accept your work though, so maybe look into contributing it to Gecko.

**Pull request closed without merging**
