### PR TITLE
Update to 6/24 rust nightly.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23627)

### CODE REVIEW

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/commit/73cb9ab5261813309b41e21cacfc44d2b61fe396 suggests we should use `get`.

**Comment by jdm** [comment]
Fixed.

**Comment by jdm** [comment]
```
[0m[1m[38;5;9merror[E0275][0m[0m[1m: overflow evaluating the requirement `alloc::raw_vec::RawVec<(syn::Lifetime, syn::token::Add)>: std::marker::Unpin`[0m
[0m  [0m[0m[1m[38;5;12m|[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mhelp[0m[0m: consider adding a `#![recursion_limit="128"]` attribute to your crate[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::vec::Vec<(syn::Lifetime, syn::token::Add)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::punctuated::Punctuated<syn::Lifetime, syn::token::Add>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::LifetimeDef`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `(syn::LifetimeDef, syn::token::Comma)`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `*const (syn::LifetimeDef, syn::token::Comma)`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::ptr::Unique<(syn::LifetimeDef, syn::token::Comma)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `alloc::raw_vec::RawVec<(syn::LifetimeDef, syn::token::Comma)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::vec::Vec<(syn::LifetimeDef, syn::token::Comma)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::punctuated::Punctuated<syn::LifetimeDef, syn::token::Comma>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::BoundLifetimes`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::option::Option<syn::BoundLifetimes>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::PredicateType`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::WherePredicate`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `(syn::WherePredicate, syn::token::Comma)`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `*const (syn::WherePredicate, syn::token::Comma)`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::ptr::Unique<(syn::WherePredicate, syn::token::Comma)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `alloc::raw_vec::RawVec<(syn::WherePredicate, syn::token::Comma)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::vec::Vec<(syn::WherePredicate, syn::token::Comma)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::punctuated::Punctuated<syn::WherePredicate, syn::token::Comma>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::WhereClause`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::option::Option<syn::WhereClause>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::Generics`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::ItemType`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::Item`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::Stmt`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `*const syn::Stmt`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::ptr::Unique<syn::Stmt>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `alloc::raw_vec::RawVec<syn::Stmt>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::vec::Vec<syn::Stmt>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::Block`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::ExprIf`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::Expr`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::TypeArray`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::Type`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::GenericArgument`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `(syn::GenericArgument, syn::token::Comma)`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `*const (syn::GenericArgument, syn::token::Comma)`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::ptr::Unique<(syn::GenericArgument, syn::token::Comma)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `alloc::raw_vec::RawVec<(syn::GenericArgument, syn::token::Comma)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::vec::Vec<(syn::GenericArgument, syn::token::Comma)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::punctuated::Punctuated<syn::GenericArgument, syn::token::Comma>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::AngleBracketedGenericArguments`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::PathArguments`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::PathSegment`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `(syn::PathSegment, syn::token::Colon2)`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `*const (syn::PathSegment, syn::token::Colon2)`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::ptr::Unique<(syn::PathSegment, syn::token::Colon2)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `alloc::raw_vec::RawVec<(syn::PathSegment, syn::token::Colon2)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::vec::Vec<(syn::PathSegment, syn::token::Colon2)>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::punctuated::Punctuated<syn::PathSegment, syn::token::Colon2>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::Path`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::Attribute`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `*const syn::Attribute`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::ptr::Unique<syn::Attribute>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `alloc::raw_vec::RawVec<syn::Attribute>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::vec::Vec<syn::Attribute>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::TypeParam`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `syn::GenericParam`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `*const syn::GenericParam`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::ptr::Unique<syn::GenericParam>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `alloc::raw_vec::RawVec<syn::GenericParam>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `std::vec::Vec<syn::GenericParam>`[0m
[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: required because it appears within the type `Structure<'a>`[0m
```

**Comment by jdm** [comment]
I tried cloning synstructure 0.10.1 locally and running `cargo +nightly doc --release` with the 6/24 nightly, and I couldn't reproduce the problem :<

**Comment by SimonSapin** [comment]
I could reproduce with this diff in the synstructure repository:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 621b06c..e49b010 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -16,7 +16,7 @@ include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]
 simple-derive = []
 
 [dependencies]
-syn = { version = "0.15", features = ["visit", "extra-traits"] }
+syn = { version = "0.15", features = ["visit", "extra-traits", "full"] }
 proc-macro2 = "0.4"
 quote = "0.6"
 unicode-xid = "0.1"

**Comment by SimonSapin** [comment]
I’ve submitted https://github.com/rust-lang/rust/issues/62132.

**Pull request closed without merging**
