### PR TITLE
Cleanup ThreadSafeLayoutNodeChildrenIterator.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6657)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I suspect this breaks something on elements without children but with both `::before` and `::after`; trying to write a test.

**Comment by Ms2ger** [comment]
This already failed some of the CSS tests; should be good to go now.

**Comment by Ms2ger** [comment]
@pcwalton r? please

**Comment by jdm** [comment]
```
   Compiling layout v0.0.1 (file:///Users/servo/buildbot/slave/mac1/build/components/servo)
/Users/servo/buildbot/slave/mac1/build/components/layout/wrapper.rs:982:40: 982:87 error: mismatched types:
 expected `core::option::Option<wrapper::ThreadSafeLayoutNode<'a>>`,
    found `wrapper::ThreadSafeLayoutNode<'_>`
(expected enum `core::option::Option`,
    found struct `wrapper::ThreadSafeLayoutNode`) [E0308]
/Users/servo/buildbot/slave/mac1/build/components/layout/wrapper.rs:982                         Some(first) => self.parent_node.new_with_this_lifetime(&first),
                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: in expansion of if let expansion
/Users/servo/buildbot/slave/mac1/build/components/layout/wrapper.rs:978:9: 1016:10 note: expansion site
/Users/servo/buildbot/slave/mac1/build/components/layout/wrapper.rs:982:40: 982:87 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
```

**Comment by jdm** [comment]
@bors-servo: retry
* #6644

**Pull request merged**
