### PR TITLE
Issue4906 fix characterdata substringdata

### PR DESCRIPTION
**Pull request by yodalee**
issue #4906
Fix substringData function, and add a test case for all function in characterdata.

### CODE REVIEW

**Comment by jdm** [comment]
Commented on Critic! Make sure you've clicked the 'sign in' link there so you receive updates by email.

**Comment by yodalee** [comment]
I push new testcase include Chinese character(usually same to Japaneses and Korean). There are two issues I cannot determine:
* length on Chinese character: There are two Chinese characters, but the length of the string are are 6.
* substringdata also need length 6 to cut down two Chinese characters

**Comment by jdm** [comment]
@yodalee It is as I feared, in that case. We should be using the `chars` method instead of slicing the string, which is apparently bytes instead of character offsets.

**Comment by yodalee** [comment]
I see, so I should change the test case of `length()` and `substringdata()` to 2 to get 2 Chinese characters. Also the function impl. of `length()` and `substringdata()` should be changed too.

**Comment by jdm** [comment]
Yep!

**Comment by yodalee** [comment]
Where can I found the those `char()` function for DOMString, as described at here:
http://doc.rust-lang.org/std/str/trait.StrExt.html#tymethod.char_at
I tried to replace bytes slice with function `char_len`, `slice_to`, `slice_from` and `slice_chars`. But the compiler cannot found proper function:
```
data DOMRefCell<DOMString>
...
self.data.borrow().char_len() as u32
```
I will suggest import `char_len()` from `core::str::StrExt` and import `slice series` from `collections::str::StrExt`. These two will conflict with each other. Maybe I should do something after `borrow()`?

**Comment by jdm** [comment]
`chars` should Just Work on a DOMString; for `char_len` you need to use `as_slice()`, since StrExt is only implemented on `str`, not `String`.

**Comment by Ms2ger** [comment]
Instead of `char_len()`, use `chars().count()`. You can call it directly on a `DOMString`, as it dereferences to `str`.

**Comment by yodalee** [comment]
I just make the test file to test all function with non-utf8 and utf8. Also fix the `characterdata` with function `chars().count()` and `slice_chars()`

**Comment by jdm** [comment]
Looks good! Have you tried running the CharacterData tests in tests/wpt/web-platform-tests/dom/nodes/?

**Comment by yodalee** [comment]
I ran the test and it passed two tests.

**Comment by jdm** [comment]
Ok! Go ahead and squash the commits, then :)

**Comment by yodalee** [comment]
Done, I remove the first commit that only change `count` to `count + offset`.
Fix function behavior is squash with comment out tests.

**Comment by jdm** [comment]
Thanks a lot!

**Pull request closed without merging**
