### PR TITLE
Android: Introduce ServoSurface

### PR DESCRIPTION
**Pull request by paulrouget**
(WIP as it depends on 2 other PRs)

Depends on #21199. Only last commit matters.

r? @MortimerGoro 

Please look at ServoSurface.java. The rest is mostly some refactoring to share as much code as possible with ServoView.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21234)

### CODE REVIEW

**Review by MortimerGoro — CHANGES_REQUESTED** [review]

**Comment by paulrouget** [comment]
@MortimerGoro done.

**Comment by paulrouget** [comment]
@MortimerGoro can you give me a final review on the last commit?

This has been tested with Crow.

**Review by MortimerGoro — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* fixed window server issue on mac4

**Pull request merged**
