### PR TITLE
Behave properly when app is suspended

### LINKED ISSUE #21329: Servo crashes after screen turns off and on again on android device
```
08-02 16:03:14.006 19366 19366 I DeviceStatusMonitor: onReceive() : Action = android.intent.action.SCREEN_OFF
08-02 16:03:14.757 15810 15841 D simpleservo: wakeup
08-02 16:03:14.759 15810 15827 D simpleservo: performUpdates
08-02 16:03:14.759 15810 15827 D simpleservo: perform_updates
08-02 16:03:14.760 15810 15827 D simpleservo: WindowMethods::prepare_for_composite
08-02 16:03:14.760 15810 15827 D simpleservo: make_current
08-02 16:03:14.771 15810 15827 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
08-02 16:03:14.774 15810 15827 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7 in tid 15827 (GLThread 3216), pid 15810 (m.mozilla.servo)
08-02 16:03:14.989 16466 16466 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
08-02 16:03:14.990   733   733 I /system/bin/tombstoned: received crash request for pid 15810
********** Crash dump: **********
Build fingerprint: 'google/sailfish/sailfish:8.1.0/OPM4.171019.021.P1/4820305:user/release-keys'
pid: 15810, tid: 15827, name: GLThread 3216  >>> com.mozilla.servo <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7
Stack frame #00 pc 0005e71c  /system/bin/linker (__dl_syscall+32)
Stack frame #01 pc 00019053  /system/bin/linker (__dl__ZL13resend_signalP7siginfob+54)
Stack frame #02 pc 00018eaf  /system/bin/linker (__dl__ZL24debuggerd_signal_handleriP7siginfoPv+774)
Stack frame #03 pc 00002261  /system/bin/app_process32 (art::SignalChain::Handler(int, siginfo*, void*)+220)
Stack frame #04 pc 000189a0  /system/lib/libc.so
Stack frame #05 pc 048c718a  /data/app/com.mozilla.servo-Pd8K4Nyb469-H45rei4XCg==/lib/arm/libsimpleservo.so: Routine unw_get_reg at /Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/Unwind/libunwind.cpp:164
Stack frame #06 pc 048c6d89  /data/app/com.mozilla.servo-Pd8K4Nyb469-H45rei4XCg==/lib/arm/libsimpleservo.so: Routine _Unwind_VRS_Get_Internal(_Unwind_Context*, _Unwind_VRS_RegClass, unsigned int, _Unwind_VRS_DataRepresentation, void*) at /Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/Unwind/Unwind-EHABI.cpp:844
Stack frame #07 pc 048afd20  /data/app/com.mozilla.servo-Pd8K4Nyb469-H45rei4XCg==/lib/arm/libsimpleservo.so: Routine __gnu_Unwind_RaiseException at /Volumes/Android/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-arm-common.inc:432
Stack frame #08 pc 048b0864  /data/app/com.mozilla.servo-Pd8K4Nyb469-H45rei4XCg==/lib/arm/libsimpleservo.so: Routine _Unwind_RaiseException at /Volumes/Android/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/config/arm/libunwind.S:356
```

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #21329

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21405)

### CODE REVIEW

**Comment by paulrouget** [comment]
@bors-servo r=jdm

- Forgot to add refresh to capi.rs

**Comment by paulrouget** [comment]
https://github.com/servo/servo/issues/21406

**Comment by jdm** [comment]
@bors-servo retry
* #20734

**Comment by jdm** [comment]
@bors-servo retry
* killed the stuck emulator

**Comment by jdm** [comment]
@bors-servo retry
* actually killed the process

**Pull request merged**
