### PR TITLE
Header values no longer have to be ASCII or UTF-8

### PR DESCRIPTION
**Pull request by pshaughn**
This passes some failed tests related to header validity when handling ByteStrings outside the printable ASCII range. A few failures remain because the HeaderValue class is stricter than WHATWG/WPT, disallowing various control-code bytes that the spec and tests expect to be allowed.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix some of the test cases described in #24903 

- [X] There are tests for these changes OR

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /fetch/api/response/response-init-002.html:
  └ PASS [expected FAIL] Testing empty Response Content-Type header
  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  └ PASS [expected FAIL] Testing empty Request Content-Type header
```

**Comment by pshaughn** [comment]
A couple notes about this:
* I _think_ I've taken out all the places where a header value gets parsed as a UTF-8 string without sanity-checking, but I don't know for sure. Hyper HeaderMap does a lot of the sanity-checking for us; for most "typed" headers we can safely cast the value that comes out of the map to a string. Conversion from a header value to a DOMString for Javascript consumption happens via ByteString, which should give a weird but safe "isomorphic decode" from bytes to UTF-16 values 0-255 instead of a UTF-8 parse.
* The "Servo thinks \"{:?}\" is a valid HTTP header value but HeaderValue doesn't." codepath represents a case where different parties still haven't really converged on a spec; Hyper is currently following the RFC rather than WHATWG. In practice I don't think any legitimate website is going to send a header where this particular disagreement matters.

**Comment by jdm** [comment]
@bors-servo r+
Thanks for sorting this out!

**Comment by jdm** [comment]
@bors-servo retry
* #24622

**Pull request merged**
