### PR TITLE
Use the API base URL in Fetch APIs.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14632)

### CODE REVIEW

**Comment by jdm** [comment]
I am super wary of changing the multi-global tests without getting input from Domenic or others involved in their creation. I would prefer them to be submitted as a PR upstream instead.

**Comment by Ms2ger** [comment]
@Domenic: could you have a look at the first two commits here? The first avoids `frames[i]` which is not yet implemented in Servo, the second delays accessing `contentWindow` (not sure what's up there exactly); neither should affect the meaning of the test.

**Comment by domenic** [comment]
LGTM; the second commit that ensures it's testing the API base URL is a nice one.

**Comment by jdm** [comment]
Thanks!
@bors-servo: r+

**Pull request merged**
