### PR TITLE
Use String to represent IDL USVString values.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8331)

### CODE REVIEW

**Comment by nox** [comment]
What if we want to optimise ASCII and Latin-1 USVString values in the future?

**Comment by jdm** [comment]
@Ms2ger Is this still desirable? If so, please choose a reviewer.

**Comment by asajeffrey** [comment]
I'm not sure we want to do this, since it fixed the string representation to be String. At some point we might want to use a different representation, e.g. one which makes sharing strings with SM possible.

**Comment by nox** [comment]
Closing it for now.

**Pull request closed without merging**
