### PR TITLE
Update ipc-channel and other dependencies

### PR DESCRIPTION
**Pull request by mukilan**
These updates will allow us to move to latest rustc nightly.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they update dependency crates.

### CODE REVIEW

**Comment by mrobinson** [comment]
It looks like the new crashes are hare not flakes unfortunately.

**Comment by mukilan** [comment]
These two tests are now intermittently crashing:

1. CRASH [expected OK] /fetch/local-network-access/worker-fetch.https.window.html
2. CRASH [expected OK] /fetch/local-network-access/worker.window.html

I am not able to reproduce the crashes on my local NixOS machine and on my Ubuntu 20.04 VM. I also tried running the tests in isolation in my fork on GH and they are still only intermittently crashing, though they do crash more often than not. The CI run doesn't produce any backtrace and only prints:

```
 0:07.83 pid:3646 Caught signal 11 in thread "Script(1,1)"
 0:08.08 TEST_END: CRASH, expected OK
 ```

I also tried extracting the coredump from CI, but it looks like the information may not be complete as the logic to print backtrace itself crashed:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f23618424c2 in do_lookup_x (
    undef_name=undef_name@entry=0x7f235f3804e6 "dl_iterate_phdr", 
    new_hash=new_hash@entry=649489807, old_hash=old_hash@entry=0x7f23500e6080, 
    ref=0x7f235f37f528, result=result@entry=0x7f23500e6090, scope=0x7f2361866450, i=0, 
    version=0x7f235d77dcf0, flags=5, skip=0x0, type_class=1, undef_map=0x7f235f516470)
    at dl-lookup.c:368
368	dl-lookup.c: No such file or directory.
[Current thread is 1 (Thread 0x7f230effd700 (LWP 3482))]
(gdb) bt
#0  0x00007f23618424c2 in do_lookup_x (
    undef_name=undef_name@entry=0x7f235f3804e6 "dl_iterate_phdr", 
    new_hash=new_hash@entry=649489807, old_hash=old_hash@entry=0x7f23500e6080, 
    ref=0x7f235f37f528, result=result@entry=0x7f23500e6090, scope=0x7f2361866450, i=0, 
    version=0x7f235d77dcf0, flags=5, skip=0x0, type_class=1, undef_map=0x7f235f516470)
    at dl-lookup.c:368
#1  0x00007f23618431f1 in _dl_lookup_symbol_x (undef_name=0x7f235f3804e6 "dl_iterate_phdr", 
    undef_map=0x7f235f516470, ref=ref@entry=0x7f23500e6128, symbol_scope=0x7f235f5167d8, 
    version=0x7f235d77dcf0, type_class=type_class@entry=1, flags=5, skip_map=0x0)
    at dl-lookup.c:861
#2  0x00007f2361848197 in _dl_fixup (l=<optimized out>, reloc_arg=<optimized out>)
    at ../elf/dl-runtime.c:112
#3  0x00007f236184fb7e in _dl_runtime_resolve_xsave ()
    at ../sysdeps/x86_64/dl-trampoline.h:126
#4  0x00007f235f3883a9 in ?? () from /lib/x86_64-linux-gnu/libunwind.so.8
#5  0x00007f235f38649d in ?? () from /lib/x86_64-linux-gnu/libunwind.so.8
#6  0x00007f235f387685 in ?? () from /lib/x86_64-linux-gnu/libunwind.so.8
#7  0x00007f235f387d3d in ?? () from /lib/x86_64-linux-gnu/libunwind.so.8
#8  0x00007f235f3841f4 in _ULx86_64_step () from /lib/x86_64-linux-gnu/libunwind.so.8
#9  0x00007f235f382804 in __libunwind_Unwind_Backtrace ()
   from /lib/x86_64-linux-gnu/libunwind.so.8
#10 0x000055a0abe4e71a in backtrace::backtrace::libunwind::trace (cb=...)
    at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/backtrace/libunwind.rs:93
#11 backtrace::backtrace::trace_unsynchronized (cb=...)
    at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/backtrace/mod.rs:66
#12 0x000055a0abe4e850 in <servo::backtrace::Print as core::fmt::Debug>::fmt (
    self=0x7f23500e76a0, fmt=0x7f23500e7508) at ports/winit/backtrace.rs:38
```

The full backtrace is [here](https://gist.github.com/mukilan/ae55cae1bc376f7132ca362de61602cc) and seems to indicate the original crash might have happened in mozjs WASM related code ??.

I'm inclined to mark this test as intermittent and investigate it separately. WDYT @mrobinson @jdm ?

**Comment by mrobinson** [comment]
Thanks for the investigation @mukilan. To be honest, I'm not exactly sure what to do here. The references to messaging make me wonder if these intermittent crashes are related to this pull request: https://github.com/servo/servo/pull/27171. If this is blocking the rustup, I guess we should simply mark the test as intermittent crashes, but we really should try to fix all of the intermittent crashes.

**Pull request merged**
