### PR TITLE
Implementing Blur filter

### PR DESCRIPTION
**Pull request by Adenilson**

### CODE REVIEW

**Comment by Adenilson** [comment]
Not for commit, as it still needs the BLUR_INFLATION_FACTOR to avoid clipping.

**Comment by jdm** [comment]
When there's an in-progress Critic review, it's usually preferable to continue adding commits to the existing PR rather than opening a new one.

**Comment by Adenilson** [comment]
@SimonSapin and @pcwalton

**Comment by jdm** [comment]
Sorry, I just read the #servo backlog. Carry on.

**Comment by larsbergstrom** [comment]
Please rebase this PR and then reopen. It has been temporarily closed to avoid generating excessive work for GitHub's servers.

**Pull request closed without merging**
