### PR TITLE
Added support for int32 to webdriver.

### PR DESCRIPTION
**Pull request by chotchki**
Fix for issue #6729

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6742)

### CODE REVIEW

**Comment by jdm** [comment]
Thanks for the patch!

**Comment by chotchki** [comment]
I'll dig into it later today.

On Sat, Jul 25, 2015, 1:02 AM bors-servo <notifications@github.com> wrote:

> [image: :broken_heart:] Test failed - mac3
> <http://build.servo.org/builders/mac3/builds/604>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/servo/servo/pull/6742#issuecomment-124800382>.
>
-- 

- Chris

**Comment by jdm** [comment]
The errors are unrelated to this change, but thanks for being keen :)

**Comment by chotchki** [comment]
Oh so servo doesn't have a hard all unit tests must pass policy?

On Sat, Jul 25, 2015, 9:50 AM bors-servo <notifications@github.com> wrote:

> [image: :hourglass:] Testing commit 4694537
> <https://github.com/servo/servo/commit/469453787f8754a2e45360b6f39eb69bb15542c0>
> with merge ee07e71
> <https://github.com/servo/servo/commit/ee07e7110d045eb6411ba101d2373318b5ab4f17>
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/servo/servo/pull/6742#issuecomment-124848665>.
>
-- 

- Chris

**Comment by jdm** [comment]
We have issues with tests that intermittently fail for a variety of reasons. Often times these get tickled by unrelated code changes.

**Comment by jdm** [comment]
@bors-servo: retry
* #6748

**Pull request merged**
