### PR TITLE
'closeevent' argument for Document::createEvent

### LINKED ISSUE #10737: Implement the "closeevent" argument to Document::createEvent
Blocks #2185, #10734.

This will involve writing a `new_uninitialized` function on `CloseEvent` and calling it from `Document::CreateEvent`.

* Spec: <https://dom.spec.whatwg.org/#dom-document-createevent>, <https://html.spec.whatwg.org/multipage/#closeevent>.
* Code: `components/script/dom/document.rs`, `components/script/dom/closeevent.rs`.
* Test: `dom/nodes/Document-createEvent.html`.

### PR DESCRIPTION
**Pull request by mrmiywj**
Add "close event" argument for Document::createEvent
Fixes #10737

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11051)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r+

**Comment by Ms2ger** [comment]
@bors-servo r-

`./mach test-tidy` reports

```
./components/script/dom/document.rs:42: use statement is not in alphabetical order
	expected: dom::errorevent::ErrorEvent
	found: dom::closeevent::CloseEvent
```

**Comment by Ms2ger** [comment]
@bors-servo r+

Thanks again

**Comment by mbrubeck** [comment]
@bors-servo retry

* servo/saltfs#363

**Comment by larsbergstrom** [comment]
@bors-servo retry
 - https://github.com/servo/saltfs/pull/365

**Comment by Ms2ger** [comment]
You can remove that part of `tests/wpt/web-platform-tests/websockets/interfaces/CloseEvent/historical.html`.

**Comment by Ms2ger** [comment]
Or make a change similar to https://github.com/w3c/web-platform-tests/pull/2964

**Comment by mrmiywj** [comment]
cc @Ms2ger

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r+

**Pull request merged**
