### PR TITLE
Move nsstring from gecko into servo/support/gecko/nsstring

### PR DESCRIPTION
**Pull request by mystor**
This is the servo side of bug 1403213.

This cannot merge until https://bugzilla.mozilla.org/show_bug.cgi?id=1377351 merges. It is currently on inbound. This will break autoland when it merges until the gecko-side part has also landed.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18941)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r-

(seems like it needs to wait?)

**Comment by mystor** [comment]
@Manishearth When you're around, I'd love it if you'd merge this & then land https://bugzilla.mozilla.org/attachment.cgi?id=8920141&action=edit on autoland to unbust it.

**Pull request merged**
