### PR TITLE
Stylo: Update bindings for ServoType

### PR DESCRIPTION
**Pull request by canova**
This is needed for https://bugzilla.mozilla.org/show_bug.cgi?id=1348873

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix [Bug 1348873](https://bugzilla.mozilla.org/show_bug.cgi?id=1348873)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16047)

### CODE REVIEW

**Comment by emilio** [comment]
You need to update also the tests, please check the generated bindings in directly.

**Comment by canaltinova** [comment]
Updated the bindings.

**Comment by emilio** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
