### PR TITLE
Implement nodeName on Attr

### PR DESCRIPTION
**Pull request by dzbarsky**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10372)

### CODE REVIEW

**Comment by dzbarsky** [comment]
Not sure what travis is complaining about, any thoughts?

**Comment by jdm** [comment]
The CI is complaining about a test being deleted without the manifest being updated.

**Comment by KiChjang** [comment]
```
Ran 4648 tests finished in 319.0 seconds.
  • 4647 ran as expected. 1364 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected CRASH] /webstorage/storage_setitem.html
  │ 
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  │ thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'Found an unpaired surrogate in a DOM string. If you see this in real web content, please comment on https://github.com/servo/servo/issues/6564 Use `-Z replace-surrogates` on the command line to make this non-fatal.', /home/servo/buildbot/slave/linux-rel/build/components/util/non_geckolib.rs:83
  │ stack backtrace:
  │    1:     0x7ffdf9c7c1b0 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
  │    2:     0x7ffdf9c810ff - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
  │    3:     0x7ffdf9c80d78 - panicking::default_handler::h4e73712d1e927dfeH0z
  │    4:     0x7ffdf9c6ab1c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
  │    5:     0x7ffdf94b6b5f - sys_common::unwind::begin_unwind::h5644377430908265868
  │    6:     0x7ffdf94b8a03 - non_geckolib::jsstring_to_str::hbe4eefbe554e46aaNNa
  │    7:     0x7ffdf86865bf - dom::bindings::conversions::jsid_to_str::ha3334b092c04778blFc
  │    8:     0x7ffdf882ef6f - dom::bindings::codegen::Bindings::StorageBinding::getOwnPropertyDescriptor::ha50d68c52013b721t2T
  │    9:     0x7ffdf95e5e81 - _ZNK22ForwardingProxyHandler24getOwnPropertyDescriptorEP9JSContextN2JS6HandleIP8JSObjectEENS3_I4jsidEENS2_13MutableHandleI20JSPropertyDescriptorEE
  │   10:     0x7ffdf9a83323 - _ZNK2js16BaseProxyHandler3setEP9JSContextN2JS6HandleIP8JSObjectEES7_NS4_I4jsidEENS3_13MutableHandleINS3_5ValueEEERNS3_14ObjectOpResultE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/proxy/BaseProxyHandler.cpp:86
  │   11:     0x7ffdf95e5858 - _ZNK22ForwardingProxyHandler3setEP9JSContextN2JS6HandleIP8JSObjectEES6_NS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEERNS2_14ObjectOpResultE
  │   12:     0x7ffdf9a9c960 - _ZN2js5Proxy3setEP9JSContextN2JS6HandleIP8JSObjectEES7_NS4_I4jsidEENS3_13MutableHandleINS3_5ValueEEERNS3_14ObjectOpResultE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/proxy/Proxy.cpp:326
  │   13:     0x7ffdf970a759 - _ZN2js11PutPropertyEP9JSContextN2JS6HandleIP8JSObjectEENS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEEb
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.h:1450
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsobj.h:905
  │   14:     0x7ffdf96f2a3a - _ZL9InterpretP9JSContextRN2js8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:1406
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2531
  │   15:     0x7ffdf96fd75c - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  │   16:     0x7ffdf96fd9dd - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:521
  └   17:     0x7ffdf9a42b62 - _ZN2js9fun_applyEP9JSContextjPN2JS5ValueE
```

**Comment by Ms2ger** [comment]
@bors-servo retry
* https://github.com/servo/servo/issues/10392

**Pull request merged**
