### PR TITLE
Print out useful SSL-related information on SSL error page.

### PR DESCRIPTION
**Pull request by jdm**
Make certificate error pages more useful. Attempt to identify known cases where upgrading OpenSSL would be useful.

screen shot 2016-06-29 at 12 29 30 pm

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11932)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Is the problem actually related to old versions of OpenSSL? Or maybe the TLS negotiation code is incorrect?

**Comment by asajeffrey** [comment]
@jdm should we also change the meme text? As @jonathandturner said over in #11929, it's a bit off-putting.

**Comment by frewsxcv** [comment]
Relevant to https://github.com/servo/servo/issues/11929

**Comment by asajeffrey** [comment]
@frewsxcv ah, this could be about cipher suite negotiation after all: it could be that the downgrade from SHA256 to SHA1 is the thing that's failing.

**Comment by asajeffrey** [comment]
@frewsxcv https://github.com/servo/servo/blob/e273517fe06720afe0ef74815cce5e007df7dc3d/components/net/http_loader.rs#L55 does contain ECDH-ECDSA-AES128-SHA, which I believe is what we're expecting cipher suite negotiation to fall back to if SHA256 isn't available.

**Comment by frewsxcv** [comment]
Relevant thread and pull request: https://github.com/servo/servo/pull/8611

**Comment by jdm** [comment]
screen shot 2016-06-29 at 3 03 18 pm

The latest commit changes the image.

**Comment by asajeffrey** [comment]
@bors-servo: r+

---

Reviewed 5 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11932#-:-KLSYQt4rQ6xBikWR4v8:-317921516)*

**Pull request merged**
