### PR TITLE
Move abstract parser infrastructure from servohtmlparser.rs to parse

### LINKED ISSUE #10856: Move abstract parser infrastructure out of servohtmlparser.rs
This includes `ParserRoot`, `ParserField`, `MutNullableParserField`, `TrustedParser`, and `ParserRef`. Let's move them to `components/script/parse/mod.rs` instead.

Code: `components/script/dom/servohtmlparser.rs`, `components/script/parse/mod.rs`

### PR DESCRIPTION
**Pull request by broesamle**
Fixes #10856

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10866)

### CODE REVIEW

**Comment by Ms2ger** [comment]
This looks great! All I can find to complain about is a few whitespace nits, so I'll do that :)

-S-awaiting-review +S-needs-code-changes 

r? @Ms2ger

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/servohtmlparser.rs, line 39 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10866#-KGLW1jpcoDjoCfxJKZ2:-KGLW1jq-9LlOPUlsUKw:1054945762) ([raw file](https://github.com/servo/servo/blob/c8b9119c55c838b14ae3d6c1ec590d5dc7df6ea9/components/script/dom/servohtmlparser.rs#L39)):*
Revert those two new empty lines, please.

---

*[components/script/dom/servohtmlparser.rs, line 55 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10866#-KGLWNiPfKvsJFWzEHX2:-KGLWNiPfKvsJFWzEHX3:701981165) ([raw file](https://github.com/servo/servo/blob/c8b9119c55c838b14ae3d6c1ec590d5dc7df6ea9/components/script/dom/servohtmlparser.rs#L55)):*
There's now three empty lines below this; one should be enough.

---

*[components/script/parse/mod.rs, line 5 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10866#-KGLWUk2v6Coa6THS_v_:-KGLWUk31mp_h_t9oMOU:195480592) ([raw file](https://github.com/servo/servo/blob/c8b9119c55c838b14ae3d6c1ec590d5dc7df6ea9/components/script/parse/mod.rs#L5)):*
Just one empty line between license and imports.

---

*[components/script/parse/mod.rs, line 25 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10866#-KGLWYOtBflsw9WbzHW9:-KGLWYOtBflsw9WbzHWA:45917022) ([raw file](https://github.com/servo/servo/blob/c8b9119c55c838b14ae3d6c1ec590d5dc7df6ea9/components/script/parse/mod.rs#L25)):*
And just one here...

---

*[components/script/parse/mod.rs, line 49 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10866#-KGLWZmzidW_zW8Tr8lW:-KGLWZmzidW_zW8Tr8lX:1243838654) ([raw file](https://github.com/servo/servo/blob/c8b9119c55c838b14ae3d6c1ec590d5dc7df6ea9/components/script/parse/mod.rs#L49)):*
And here

---

*[components/script/parse/mod.rs, line 180 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10866#-KGLWcWTVnG05_fLn6ou:-KGLWcWTVnG05_fLn6ov:278936101) ([raw file](https://github.com/servo/servo/blob/c8b9119c55c838b14ae3d6c1ec590d5dc7df6ea9/components/script/parse/mod.rs#L180)):*
And no empty line at the end here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10866#-:-KGLVr3QhdfKVuItG90Q:-1978061885)*

**Comment by broesamle** [comment]
removed empty lines.

**Comment by Ms2ger** [comment]
Thanks! just needs a squash now; let me know if you need help with that.

-S-awaiting-review +S-needs-squash 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10866#-:-KGLjVEMOVuBwkYwViVU:-53098295)*

**Comment by broesamle** [comment]
the idea is to make one commit out of it... like the second last point in the git workflow?

`$ git rebase -i --autosquash <mozilla>/master`

**Comment by Ms2ger** [comment]
Yep.

**Comment by broesamle** [comment]
done.

**Comment by Ms2ger** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
