### PR TITLE
Group WPT chunks together in Treeherder

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
* Before: https://treeherder.allizom.org/#/jobs?repo=servo-try&revision=ae3096b5518961b17ff6bd5744e93b6acc64ebab
* After: https://treeherder.allizom.org/#/jobs?repo=servo-try&revision=44029f88945f2b4e0736f60ea7993790b615ea71

**Review by jdm — APPROVED** [review]

**Comment by SimonSapin** [comment]
@bors-servo retry

```
4 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected PASS] /_mozilla/mozilla/fullscreen/reftests/fullscreen-hides-others.html
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ 36 threads are still running after shutdown (bad).
  ▶ TIMEOUT [expected PASS] /css/filter-effects/filter-invert-001-test.html
  ▶ TIMEOUT [expected PASS] /css/filter-effects/filters-sepia-001-test.html
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ 18 threads are still running after shutdown (bad).
  ▶ TIMEOUT [expected PASS] /css/filter-effects/svg-feoffset-001.html

**Pull request merged**
