### PR TITLE
Webbluetooth requestDevice refactor and update

### LINKED ISSUE #12614: Step annotations for files related to WebBluetooth
cc @zakorgy

### PR DESCRIPTION
**Pull request by zakorgy**
Refactor requestDevice function according to the specification changes. 
1. Moved the `request_bluetooth_devices` algorithm out from the `requestDevice` function.
2. Two new members in `BluetoothRequestDeviceFilter` and one new member in `RequestDeviceOptions`.
3. Also added annotations to the related functions.
Related links:
https://webbluetoothcg.github.io/web-bluetooth/#device-discovery, 
https://webbluetoothcg.github.io/web-bluetooth/#dom-bluetooth-requestdevice, https://webbluetoothcg.github.io/web-bluetooth/#request-bluetooth-devices,
https://webbluetoothcg.github.io/web-bluetooth/#matches-a-filter

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12614

- [x] These changes do not require tests because , there is no WebBluetooth Test API implementation yet.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13184)

### CODE REVIEW

**Comment by nox** [comment]
Could it somehow be split in multiple independent commits?

**Comment by zakorgy** [comment]
@nox how do you prefer the splitting? First commit refactor and update, second with the annotations, or should I split it by sub parts with the corresponding annotations e.g. first commit new dict members , second commit requestDevice modification etc. ?

**Comment by nox** [comment]
Unrelated changes should go in separate commits, and each commit should build correctly. So probably just two or three, one with the clean up, one with the annotations, and finally the fix.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for adding the annotations!

**Comment by jdm** [comment]
@bors-servo: retry
* #11574

**Pull request merged**
