### PR TITLE
Prefer Either type for LengthOrNumber

### PR DESCRIPTION
**Pull request by ghost**
This adds `impl GeckoStyleCoordConvertible for Either<A, B>` and makes `LengthOrNumber` prefer `Either<A, B>`.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach build-geckolib` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] These changes do not require tests because it's a refactor

r? @SimonSapin

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14261)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Looks like the unit tests need to be updated (as per Travis CI)

**Comment by Wafflespeanut** [comment]
Whoops. Fixed :smile:

**Comment by SimonSapin** [comment]
> +36 −110

Nice :)

@bors-servo r+

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/14261#-:-KWrd4ghjwZ5-Gl_icU8:b-vep1ow)*

**Comment by Wafflespeanut** [comment]
Thanks! :)

**Pull request merged**
