### PR TITLE
unblock using JS_GC_ZEAL

### PR DESCRIPTION
**Pull request by froydnj**
I think these patches move the `JS_SetReservedSlot` call to the right place for #6057.  I'm not sure that the interface to `create_dom_global` is the best; passing a `JSVal` or a `*libc::c_void` seemed about equal, so I'd welcome feedback there.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8226)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 2168 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8226#-K1eeLjJutXUsZnCxQfT)** ([raw file](https://github.com/servo/servo/blob/e488d37163fdd6265de654b8b29bfd56fd311bf6/components/script/dom/bindings/codegen/CodegenRust.py#L2168)):</sup>
Let's merge these two.


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 2180 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8226#-K1eeOvx9S2RwNNVR20r)** ([raw file](https://github.com/servo/servo/blob/e488d37163fdd6265de654b8b29bfd56fd311bf6/components/script/dom/bindings/codegen/CodegenRust.py#L2180)):</sup>
Let's merge these two.


---

<sup>**[components/script/dom/bindings/utils.rs, line 10 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8226#-K1eexrHm9gy3o5sMTjK)** ([raw file](https://github.com/servo/servo/blob/5f72326c35800d459c3f731be5fe392fa178abac/components/script/dom/bindings/utils.rs#L10)):</sup>
Add this to an existing import line.


---

<sup>**[components/script/dom/bindings/utils.rs, line 629 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8226#-K1eeSqeYbQBGkP-Cln2)** ([raw file](https://github.com/servo/servo/blob/5f72326c35800d459c3f731be5fe392fa178abac/components/script/dom/bindings/utils.rs#L629)):</sup>
I'm inclined towards `create_dom_global<T: Reflectable>(implementation: *mut T)` and call PrivateValue when calling JS_SetReservedSlot.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8226)

**Comment by froydnj** [comment]
> I'm inclined towards `create_dom_global<T: Reflectable>(implementation: *mut T)` and call PrivateValue when calling JS_SetReservedSlot.

I didn't see much benefit to templating the function over T when we didn't really use T for anything.  Do you prefer the templating for consistency with the Gecko implementation, or are there deeper issues here?

**Comment by jdm** [comment]
There's no deeper issue, it's just slightly more type-safe than accepting a `*const libc::c_void`. I'm ok with that choice, though.

**Comment by froydnj** [comment]
> There's no deeper issue, it's just slightly more type-safe than accepting a` *const libc::c_void`. I'm ok with that choice, though.

OK, thanks.  I went with that option.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8226)

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Comment by jdm** [comment]
@bors-servo: retry
* infra

**Comment by jdm** [comment]
@bors-servo: retry
* infra

**Pull request merged**
