### PR TITLE
Implement history.length

### PR DESCRIPTION
**Pull request by cbrewster**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12685)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
```
  ▶ Unexpected subtest result in /html/browsers/history/the-location-interface/location_assign_about_blank.html:
  │ FAIL [expected PASS] location.assign with initial about:blank browsing context
  │   → assert_equals: expected 1 but got 2
  │ 
  │ onload</</iframe.onload</<@http://web-platform.test:8000/html/browsers/history/the-location-interface/location_assign_about_blank.html:8:11
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1426:20
```
I am going to mark this is failing, since `about:blank` is not replaced after navigating. I will investigate that issue later.

**Comment by asajeffrey** [comment]
Yay, another property implemented! A question about code reuse, but apart from that LGTM.

---

Reviewed 4 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/constellation/constellation.rs, line 1499 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12685#-KOB2Le8thk0hSxe2n1a:-KOB2Le9lxORKbTzseJs:-445168036) ([raw file](https://github.com/servo/servo/blob/d76302c54829fe5d00b745aa4a078da380555a8f/components/constellation/constellation.rs#L1499)):*
> ```Rust
>     }
> 
>     fn handle_joint_session_history_length(&self, pipeline_id: PipelineId, sender: IpcSender<u32>) {
> ```

Can we not reuse some code from `joint_session_future` and `joint_session_past`? Something like have functions `joint_session_future_iterator`, which iterates over the unsorted joint session future, and ditto past. Then the joint session future would be something like `let mut result = joint_session_future_iterator().collect(); result.sort(); result`, and this function could be `joint_session_past_iterator().length() + joint_session_future_iterator().length()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12685#-:-KOB3obSMwQon5FDjs2w:-655752996)*

**Comment by ConnorGBrewster** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/constellation/constellation.rs, line 1499 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12685#-KOB2Le8thk0hSxe2n1a:-KOBWhyMqh7htrWPBNfZ:-1435423438) ([raw file](https://github.com/servo/servo/blob/d76302c54829fe5d00b745aa4a078da380555a8f/components/constellation/constellation.rs#L1499)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Can we not reuse some code from `joint_session_future` and `joint_session_past`? Something like have functions `joint_session_future_iterator`, which iterates over the unsorted joint session future, and ditto past. Then the joint session future would be something like `let mut result = joint_session_future_iterator().collect(); result.sort(); result`, and this function could be `joint_session_past_iterator().length() + joint_session_future_iterator().length()`.
</details>
Creating an iterator would be a little too complicated for this scenario. Since it would be a massive chain of `Chain`s. The only other option would to create a new struct that impls Iterator, which I think ends up being too complicated for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12685)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/constellation/constellation.rs, line 1499 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12685#-KOB2Le8thk0hSxe2n1a:-KOC0OjcMaps7bCVqzdF:-455034625) ([raw file](https://github.com/servo/servo/blob/d76302c54829fe5d00b745aa4a078da380555a8f/components/constellation/constellation.rs#L1499)):*
<details><summary><i>Previously, ConnorGBrewster (Connor Brewster) wrote…</i></summary>
> Creating an iterator would be a little too complicated for this scenario. Since it would be a massive chain of `Chain`s. The only other option would to create a new struct that impls Iterator, which I think ends up being too complicated for this.
</details>
OK, if you reckon it would be more complicated. It looks to me like you've done most of the work. Perhaps a version of `FrameTreeIterator` that iterated over every frame, not just the fully active ones?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12685)*

**Comment by ConnorGBrewster** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/constellation/constellation.rs, line 1499 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12685#-KOB2Le8thk0hSxe2n1a:-KOD8J8Abf9tK-NlEuk_:1579463595) ([raw file](https://github.com/servo/servo/blob/d76302c54829fe5d00b745aa4a078da380555a8f/components/constellation/constellation.rs#L1499)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> OK, if you reckon it would be more complicated. It looks to me like you've done most of the work. Perhaps a version of `FrameTreeIterator` that iterated over every frame, not just the fully active ones?
</details>
I like that idea, I have done that and it does reduce code duplication quite a bit. I would like to use it in `clear_joint_session_future` but that requires a mutable iterator. I don't want to make a separate mutable iterator just for use in one place, nor do I want to make it always mutable. Any thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12685)*

**Comment by asajeffrey** [comment]
LGTM, squash and r=me.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/constellation/constellation.rs, line 1499 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12685#-KOB2Le8thk0hSxe2n1a:-KOGNb8F7DFX8X5v1Z-k:197132731) ([raw file](https://github.com/servo/servo/blob/d76302c54829fe5d00b745aa4a078da380555a8f/components/constellation/constellation.rs#L1499)):*
<details><summary><i>Previously, ConnorGBrewster (Connor Brewster) wrote…</i></summary>
> I like that idea, I have done that and it does reduce code duplication quite a bit. I would like to use it in `clear_joint_session_future` but that requires a mutable iterator. I don't want to make a separate mutable iterator just for use in one place, nor do I want to make it always mutable. Any thoughts?
</details>
This is much nicer now. I'm afraid I can't see an easy way to share code between the mutable and immutable iterators, Rust doesn't have polymorphism over mutability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12685#-:-KOGOALkUdDSv_czy4xa:2033635182)*

**Pull request merged**
