### PR TITLE
Clean up task sources and make all tasks cancellable

### LINKED ISSUE #11703: Intermittent crash in /html/semantics/embedded-content/the-iframe-element/change_parentage.html (Option::unwrap on a None value)
```
▶ CRASH [expected OK] /html/semantics/embedded-content/the-iframe-element/change_parentage.html
  │ 
  │ Xlib:  extension &#34;XFree86-VidModeExtension&#34; missing on display &#34;:0&#34;.
  │ ERROR:constellation::constellation: Panic: called `Option::unwrap()` on a `None` value
  │ ERROR:constellation::constellation: Backtrace:
  │ frame #0  - 0x00007f71d010466d - backtrace::backtrace::trace::hccde8df28b4db2a2
  │ frame #1  - 0x00007f71d01045f5 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
  │ frame #2  - 0x00007f71cf15adc9 - _&lt;F as alloc..boxed..FnBox&lt;A&gt;&gt;::call_box::h89adae1a802be550
  │ frame #3  - 0x00007f71d00f5ea8 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::he2b22674ad1748f3
  │ frame #4  - 0x00007f71d03c07cc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
  │ frame #5  - 0x00007f71d03dabd1 - std::panicking::begin_panic::he426e15a3766089a
  │ frame #6  - 0x00007f71d03c203a - std::panicking::begin_panic_fmt::hdddb415186c241e7
  │ frame #7  - 0x00007f71d03dab6e - rust_begin_unwind
  │ frame #8  - 0x00007f71d041116f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  │ frame #9  - 0x00007f71d0411448 - core::panicking::panic::h907815f47e914305
  │ frame #10 - 0x00007f71cef7cc81 - script::dom::event::Event::new_uninitialized::h05ae188a870e92b9
  │ frame #11 - 0x00007f71cef84b3b - script::dom::event::Event::new::h7a12c706eaf845bc
  │ frame #12 - 0x00007f71cefcb95c - script::dom::eventtarget::EventTarget::fire_event::h0d5b30039f5820d2
  │ frame #13 - 0x00007f71cf1cd7fa - script::task_source::dom_manipulation::DOMManipulationTask::handle_task::h0ea31f97e475cb7a
  │ frame #14 - 0x00007f71cf1652c5 - script::script_thread::ScriptThread::handle_msg_from_script::h47e979ae1e7fb676
  │ frame #15 - 0x00007f71cf1b1d9f - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hb50cf7fd97943b65
  │ frame #16 - 0x00007f71cf19a0e9 - script::script_thread::ScriptThread::handle_msgs::h1e1abab71191c950
  │ frame #17 - 0x00007f71cf159447 - std::panicking::try::call::h78dcd5319adf08fa
  │ frame #18 - 0x00007f71d03e4dcb - __rust_try
  │ frame #19 - 0x00007f71d03e4d6e - __rust_maybe_catch_panic
  │ frame #20 - 0x00007f71cf15a72d - _&lt;F as alloc..boxed..FnBox&lt;A&gt;&gt;::call_box::hce043844655ea6a9
  │ frame #21 - 0x00007f71d03d8d94 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  │ frame #22 - 0x00007f71cc242181 - start_thread
  │ frame #23 - 0x00007f71cbd5947c - __clone
  │ frame #24 - 0x0000000000000000 - &lt;unknown&gt;
```

### PR DESCRIPTION
**Pull request by cbrewster**
This makes it so each task is a thin wrapper over a runnable and whenever a task is queued, it is automatically wrapped by the window's `runnable_wrapper`.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix  #11703 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12404)

### CODE REVIEW

**Comment by jdm** [comment]
All the webstorage tests now time out, suggesting that something went wrong here :)

**Comment by ConnorGBrewster** [comment]
Woops, `CancellableRunnable` needed to implement the new `Runnable` methods to call the proper method on their inner runnable.

**Comment by asajeffrey** [comment]
May fix #11703?

**Comment by asajeffrey** [comment]
Mostly this looks good, and yay for one less intermittent! My only question is about the amount of boxing we're doing, can we replace `Box<T>` by `T`?

---

Reviewed 1 of 9 files at r1, 1 of 3 files at r2, 12 of 13 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/script_thread.rs, line 177 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12404#-KMZtMQdi5LuIs4zcpqV:-KMZtMQdi5LuIs4zcpqW:-99291809) ([raw file](https://github.com/servo/servo/blob/2b42b8fcac7edd0db0a5bd0897a1b9df1ead8208/components/script/script_thread.rs#L177)):*
> ```Rust
> 
> impl RunnableWrapper {
>     pub fn wrap_runnable<T: Runnable + Send + 'static>(&self, runnable: Box<T>) -> Box<Runnable + Send> {
> ```

Why are we taking a `Box<T>` rather than a `T` as argument?

---

*[components/script/task_source/mod.rs, line 16 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12404#-KMZslsMRKN7vJa3dQ1Y:-KMZslsMRKN7vJa3dQ1Z:1463813782) ([raw file](https://github.com/servo/servo/blob/2b42b8fcac7edd0db0a5bd0897a1b9df1ead8208/components/script/task_source/mod.rs#L16)):*
> ```Rust
> 
> pub trait TaskSource {
>     fn queue<T: Runnable + Send + 'static>(&self, msg: Box<T>, window: &Window) -> Result<(), ()>;
> ```

Why are we taking a `Box<T>` as an argument rather than a `T`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12404#-:-KMZvnefmrlGjpl44-yk:438242566)*

**Comment by ConnorGBrewster** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/script_thread.rs, line 177 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12404#-KMZtMQdi5LuIs4zcpqV:-KMZy35-02LDkj_onJlN:1214168501) ([raw file](https://github.com/servo/servo/blob/2b42b8fcac7edd0db0a5bd0897a1b9df1ead8208/components/script/script_thread.rs#L177)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Why are we taking a `Box<T>` rather than a `T` as argument?
</details>
This doesn't end up boxing any more than usual, it just requires boxing the runnable before it reaches this point (as before this method boxed the runnable). I do think it is cleaner to have this method do the boxing rather than requiring the boxing to be done when the runnable is created.

---

*[components/script/task_source/mod.rs, line 16 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12404#-KMZslsMRKN7vJa3dQ1Y:-KMZyJbBJ0U_7n6OkPjZ:160841994) ([raw file](https://github.com/servo/servo/blob/2b42b8fcac7edd0db0a5bd0897a1b9df1ead8208/components/script/task_source/mod.rs#L16)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Why are we taking a `Box<T>` as an argument rather than a `T`?
</details>
Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12404)*

**Comment by asajeffrey** [comment]
Review status: 5 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/script_thread.rs, line 177 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12404#-KMZtMQdi5LuIs4zcpqV:-KM_0I00_MgT4gdeQiy4:-1360776886) ([raw file](https://github.com/servo/servo/blob/2b42b8fcac7edd0db0a5bd0897a1b9df1ead8208/components/script/script_thread.rs#L177)):*
<details><summary><i>Previously, ConnorGBrewster (Connor Brewster) wrote…</i></summary>
> This doesn't end up boxing any more than usual, it just requires boxing the runnable before it reaches this point (as before this method boxed the runnable). I do think it is cleaner to have this method do the boxing rather than requiring the boxing to be done when the runnable is created.
</details>
I meant why are we doing any boxing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12404)*

**Comment by KiChjang** [comment]
@asajeffrey Because `Runnable` is a trait, and you cannot have a trait as an argument type.

**Comment by asajeffrey** [comment]
Reviewed 10 of 11 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/script_thread.rs, line 177 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12404#-KMZtMQdi5LuIs4zcpqV:-KM_FjC_n6SIpA1U1RLA:-649878388) ([raw file](https://github.com/servo/servo/blob/2b42b8fcac7edd0db0a5bd0897a1b9df1ead8208/components/script/script_thread.rs#L177)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> I meant why are we doing any boxing?
</details>
IRC conversation: http://logs.glob.uno/?c=mozilla%23servo&s=13+Jul+2016&e=13+Jul+2016#c479392

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12404)*

**Pull request merged**
