### PR TITLE
Framebuffer and renderbuffer fixes

### LINKED ISSUE #21252: renderbufferStorage with RGB565 format causes panic in GL thread
```html
<canvas id="canvas"></canvas>
<script>
  var gl = document.getElementById('canvas').getContext('webgl');
  var buffer = gl.createRenderbuffer();
  gl.bindRenderbuffer(gl.RENDERBUFFER, buffer);
  gl.renderbufferStorage(gl.RENDERBUFFER, gl.RGB565, 1, 1);
  console.log(gl.getError());
</script>
```
This yields:
```
ERROR 2018-07-26T16:43:52Z: canvas::webgl_thread: Last GL operation failed: RenderbufferStorage(36161, 36194, 1, 1)
assertion failed: `(left == right)`
  left: `1280`,
 right: `0`: Unexpected WebGL error: 0x500 (1280) (thread WebGLThread, at components/canvas/webgl_thread.rs:1131)
```
The RGB565 format is allowed by the spec and checked in the conformance tests. This does not affect headless builds using OSMesa, so I'm going to see if Firefox's implementation does anything special here.

### PR DESCRIPTION
**Pull request by jdm**
This commits address two separate panics that occur when running the framebuffer-object-attachment.html test. The test still panics due to another framebuffer completion status problem, so the overall test results don't demonstrate any improvement.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #21252
- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21313)

### CODE REVIEW

**Comment by nox** [comment]
r=me once the tidy issue is fixed.

**Comment by jdm** [comment]
@bors-servo retry
* #21067

**Comment by jdm** [comment]
@bors-servo retry
* #20734

**Pull request merged**
