### PR TITLE
improve reliability of hang monitor tests

### LINKED ISSUE #27191: Intermittent timeout in test_hang_monitoring_exit_signal
```
     Running target/debug/deps/hang_monitor_tests-cc9feffccc80420b
running 3 tests
test test_hang_monitoring ... ok
test test_hang_monitoring_unregister ... ok
test test_hang_monitoring_exit_signal ... test test_hang_monitoring_exit_signal has been running for over 60 seconds
```

### PR DESCRIPTION
**Pull request by gterzian**
FIX https://github.com/servo/servo/issues/27191

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by gterzian** [comment]
@jdm r?

**Comment by jdm** [comment]
@bors-servo retry
* #26726 #25513

**Comment by jdm** [comment]
@bors-servo retry
* #26895

**Pull request merged**
