### PR TITLE
webgl: Make context creation fallible. Fixes #6806

### LINKED ISSUE #6806: Make webgl creation fallible
We call `unwrap` on a result in `handle_create_webgl_paint_task_msg`. We should make the `IpcSender<(IpcSender<CanvasMsg>, usize)>` take a `Result` instead, and we can return an `Err` value from `WebGLRenderingContext::new_inherited` where the `CreateWebGLPaintTask` message is sent from.

Code: components/script/dom/webglrenderingcontext.rs, components/compositing/constellation.rs, components/msg/constellation_msg.rs

### PR DESCRIPTION
**Pull request by emilio**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6812)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 73 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6812#-JvKHUFy2_22NKoxVEaA)** ([raw file](https://github.com/servo/servo/blob/e49eaf7da23d9bc38f59152cfda8753d91b168fb/components/script/dom/webglrenderingcontext.rs#L73)):</sup>
Let's split this into separate `let result = receiver.recv().unwrap();` and `result.map(|...| {` lines.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6812)

**Comment by ecoal95** [comment]
Done! :P

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6812)

**Comment by jdm** [comment]
Thanks for the patch!

**Comment by metajack** [comment]
@bors-servo r=jdm

Not sure why bors didn't catch this yet.

**Pull request merged**
