### PR TITLE
Remove unused imports in script

### LINKED ISSUE #9345: Remove the unused imports in script
There are 9 unused imports in various modules of the `script` crate. We should exterminate those...

Code: `components/script/*.rs`

### PR DESCRIPTION
**Pull request by kishorbhat**
Fixes #9345.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9348)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
@bors-servo r+

Thanks!

**Comment by KiChjang** [comment]
@bors-servo retry
* #8157

**Comment by ecoal95** [comment]
@bors-servo: retry
 * (https://github.com/servo/servo/issues/9303)

**Pull request merged**
