### PR TITLE
Use str for bindgen output directly

### PR DESCRIPTION
**Pull request by upsuper**
r? @emilio

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13889)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo: delegate+
```
03:14 <emilio> xidorn: what's the purpose of if ord(content[end]) & 0b11000000 != 0b10000000?
03:14 <xidorn> emilio: check whether it is a start byte of a codepoint in UTF-8
03:15 <xidorn> emilio: see https://en.wikipedia.org/wiki/UTF-8#Description
03:15 <emilio> xidorn: TIL that function existed :)
03:15 <xidorn> oh?
03:15 <xidorn> emilio: I actually wonder whether we could just print the str directly...
03:15 <xidorn> emilio: what would go wrong if we do that?
03:15 <emilio> xidorn: I'm not such a pythonist to be fair. I learn by need :P
03:16 <emilio> xidorn: It might just work?
03:16 <xidorn> emilio: probably? I can try :)
03:17 <emilio> xidorn: In any case, if it doesn't and you want to merge that one, r=me with a comment on that check. if it does, just r=me directly :)
```

**Comment by upsuper** [comment]
Ah, I wanted to do some further test on my windows laptop before merging it... Anyway, I guess this change should be fine, so I guess it's okay to merge it now.

**Comment by emilio** [comment]
I can hold it if you want, in any case, that failing test is #13887. Otherwise r=me yourself :)

**Pull request merged**
