### PR TITLE
Run test-tidy when landing pull requests

### PR DESCRIPTION
**Pull request by mrobinson**
Currently `test-tidy` only runs during the quick check. This can mean that when a change is approved, the quick check can be skipped and a change can land without `test-tidy` ever being run on it. This change adds a `test-tidy` run to the main CI run to avoid this happening.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests

### CODE REVIEW

**Comment by sagudev** [comment]
What if bors just fails if Quickcheck is failing, this way we would not do double-checking.

**Comment by mrobinson** [comment]
Oh, in addition, running `test-tidy` before landing will also verify that no tidy errors are introduced in the process of merging, though admittedly that seems really unlikely.

**Comment by sagudev** [comment]
Good point, but landing should still be prevented if Quickcheck fails.

The only difference between quickcheck and linux-build are smoketest (10s) and Unit tests (cca. 10 min) both present only in quickcheck while linux-build has packaging and uploading. I wonder if we could unify them.

**Review by jdm — APPROVED** [review]

**Pull request merged**
