### PR TITLE
Navigate to a new page even when there's a fragment.

### LINKED ISSUE #7169: `load_url` ignores the URL if it has a fragment
```html
<a href="http://www.example.com/#foo">test</a>
<div style="height: 1000px"></div>
<p id=foo>Blah</p>
<div style="height: 1000px"></div>
```
Clicking the link goes straight to the `p` element rather than visiting `example.com`.

### PR DESCRIPTION
**Pull request by notriddle**
Closes #7169

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7260)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you for your PR. Just one nit below.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/document.rs, line 259 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7260#-JwzzVuPiSGliqLvRYwH)** ([raw file](https://github.com/servo/servo/blob/5bbf1f877426dd6783dbdff8f30a5d8f72d3de2b/components/script/dom/document.rs#L259)):</sup>
Should be `&str`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7260)

**Comment by notriddle** [comment]
Fixed it. I will need to squash it before r+.

**Comment by notriddle** [comment]
@Ms2ger I have no idea how I unassigned you; I didn't even know I *could* do that.

**Comment by nox** [comment]
@notriddle I think you removed him of the Servo organisation or something.

**Comment by nox** [comment]
@bors-servo r=Ms2ger

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7260)

**Comment by nox** [comment]
@bors-servo r-

Err, it wasn't squashed.

**Comment by notriddle** [comment]
Squashed.

And how could I have removed him from the Servo organization?! I'm pretty sure I don't have admin rights to it.

**Comment by nox** [comment]
@bors-servo r=Ms2ger

@notriddle Oh, I had not noticed you were that PR's author. Probably what happened is that someone removed him, and GitHub couldn't be arsed to reflect that properly in issues and whatnot, instead showing you as unassigning him.

**Pull request merged**
