### PR TITLE
Issue #7382 Use descriptive enums instead of booleans for MIMEClassifier::classifer

### PR DESCRIPTION
**Pull request by leaexplores**
Hi guys i've done a small pass of refactor in the MIMEClassifier implementation. (See issue #7382 )
- Moved the predicates to separate functions
- Added a mimetype enum so we can compare them easily after calling MIMEClassifier::get_media_type

I hope it follows rust good pratices (care it's my first time doing rust).

Improvements and tips are welcome :).

Thanks for looking at it.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7447)

### CODE REVIEW

**Comment by jdm** [comment]
Huh; the original issue was actually filed about the boolean arguments to the classify function (which ironically weren't touched in this PR). I'll need to think about whether these changes are also worthwhile improvements!

**Comment by ddrmanxbxfr** [comment]
Oh I see, you wanted to swap out https://github.com/ddrmanxbxfr/servo/blob/master/components/net/mime_classifier.rs#L29
and
https://github.com/ddrmanxbxfr/servo/blob/master/components/net/mime_classifier.rs#L30

For a ENUM too ? 

While having the hands in refactoring this I could undergo with adding a ENUM such as MIMEClassifyOptions which could include the check_for_apache_bug and no_sniff checks ?

This way we'll be able to drop out both booleans and add more check later if needed.

If it seems a sane idea please confirm and i'll improve it quickly :)

Thanks!

**Comment by jdm** [comment]
A MIMEClassifyOptions bitfield (http://mxr.mozilla.org/servo/source/components/gfx/font.rs#102) would work, but I think I would prefer two separate enum arguments instead.

**Comment by ddrmanxbxfr** [comment]
Hi JDM,

I've added the following so we get it right :
     - Added a ENUM for the Check Apache Bug Flag
     - Added a ENUM for the No Sniff Flag
     - Updated broken test + tidy
     - Added unit test when no sniff flag is at on skips the processing as per the specs to whatwg.
     - Added unit test when apache check bug flag is at on to make sure it bahaves as per https://mimesniff.spec.whatwg.org/#rules-for-text-or-binary

Thanks for looking into it,
Comments/improvements would be appreciated.

**Comment by ddrmanxbxfr** [comment]
Just rebased and squashed the fixup together.

It should help for merge :).

Thanks for looking into it.

**Comment by ddrmanxbxfr** [comment]
@jdm ping ? Just rebased a 2nd time against upstream/master.

**Comment by jdm** [comment]
Sorry about the delay. I'll review this by Tuesday at the latest (Monday is a holdiay).

**Comment by ddrmanxbxfr** [comment]
k82h8x

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/mime_classifier.rs, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhC3aQtPmi8KSsvotx)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L17)):</sup>
Let's remove the MIME from the name.

---

<sup>**[components/net/mime_classifier.rs, line 22 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhAJ6ywo4amQiMjjqL)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L22)):</sup>
Let's remove this entry, treat `Unknown` as `SniffForUnknownType`, and make `get_media_type` return `Option<MIMEMediaType>` instead. I don't think `get_media_type` and `MIMEMediaType` need to be public, either.

---

<sup>**[components/net/mime_classifier.rs, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhAEx-2xa10UNneR14)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L26)):</sup>
I think we can remove the MIME from the name.

---

<sup>**[components/net/mime_classifier.rs, line 31 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhAGYnbBFNl6heo0C9)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L31)):</sup>
Same here.

---

<sup>**[components/net/mime_classifier.rs, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhB35Cpb8Swu_VIdaz)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L47)):</sup>
These changes switch the order so that the the no_sniff_flag takes priority, which contradicts the specification: https://mimesniff.spec.whatwg.org/#mime-type-sniffing-algorithm

---

<sup>**[components/net/mime_classifier.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhByblbJcfTzx7b0ap)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L56)):</sup>
nit: please keep this with the relevant code:
```rust
MIMEMediaType:Html =>
    //Implied in section 7.3, but flow is not clear
    self.feeds_classifier.classify(...)
```

---

<sup>**[components/net/mime_classifier.rs, line 103 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhCUVo60zo5IjKa0a6)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L103)):</sup>
Let's call this `is_explicit_unknown`

---

<sup>**[components/net/mime_classifier.rs, line 130 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhCJmWRSpfKETrD3Kt)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L130)):</sup>
Please move this back to its original location so it's easier to see the changes :)

---

<sup>**[components/net/mime_classifier.rs, line 132 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhCtgIVIm4y1H0cAsH)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L132)):</sup>
I think the logic will be easier to follow like this:
```rust
let should_sniff_scriptable = no_sniff_flag == MIMENoSniffFlag::OFF;
let sniffed = if should_sniff_scriptable {
    self.scriptable_classifier.classify(data)
} else {
    None
};
sniffed.or_else(...)
```
This will require adding `#[derive(PartialEq)]` to `MIMENoSniffFlag`.

---

<sup>**[components/net/mime_classifier.rs, line 142 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhCQL4LV9SBACVHJz9)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L142)):</sup>
Please move this back to its original location so it's easier to see the changes :)

---

<sup>**[components/net/resource_task.rs, line 75 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhDpTHLONPheunVDRw)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/resource_task.rs#L75)):</sup>
nit: no need for the explicit types here.

---

<sup>**[components/net/resource_task.rs, line 107 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhE-gK9wzNnAhnpin1)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/resource_task.rs#L107)):</sup>
`&[u8]` is more efficient than `&Vec<u8>`.

---

<sup>**[tests/unit/net/mime_classifier.rs, line 40 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhEwdmomhLmQd4Vp_H)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/tests/unit/net/mime_classifier.rs#L40)):</sup>
Let's call this `test_sniff_with_flags`

---

<sup>**[tests/unit/net/mime_classifier.rs, line 79 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhF0ExUKUWzgvDif6K)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/tests/unit/net/mime_classifier.rs#L79)):</sup>
nit: this should only be indented four spaces past the `fn` at the start.

---

<sup>**[tests/unit/net/mime_classifier.rs, line 493 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhFSOOuATERVnmY8lY)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/tests/unit/net/mime_classifier.rs#L493)):</sup>
I'm not sure these tests that enable the apache bug flag are that useful unless they cause the sniffing behaviour to actually change. It looks like we get the same result, right? What about a test for something like an A/V file that would not usually be classified as plaintext?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7447)

**Comment by ddrmanxbxfr** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[components/net/mime_classifier.rs, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhB35Cpb8Swu_VIdaz)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L47)):</sup>
Good catch, (unknown, unkown), (application, application) and (*,*) needs to be checked before going into the no_sniff flag logic. Refactoring them into a is_unknown_type method.

---

<sup>**[components/net/mime_classifier.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhByblbJcfTzx7b0ap)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L56)):</sup>
This belongs to the FeedsClassifier related to the mislabeled fields. 

I am not quite sure where you want to move this comment.

---

<sup>**[components/net/mime_classifier.rs, line 132 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhCtgIVIm4y1H0cAsH)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L132)):</sup>
Mhm indeed. It'll remove one pattern matching. I'll look into doing this change :).

---

<sup>**[tests/unit/net/mime_classifier.rs, line 493 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhFSOOuATERVnmY8lY)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/tests/unit/net/mime_classifier.rs#L493)):</sup>
Mhmh, it's the usual sniffing for mislabeled resource. 

We had cases where the resource was interpreted as mislabeled / unknown but no test for the flags at on. They were all done with the flags at off even though they are supposed to have the same behavior.

If a resource is unknown mimetype OR comes from Apache Bug Flag, need to interpret it as mislabeled.

As I read they have case on UTF-8, 16, 16le bom's.

Section 7.2 for mislabeled rules.
Section 7 for the algorithm

https://mimesniff.spec.whatwg.org/#check-for-apache-bug-flag

> If the check-for-apache-bug flag is set, execute the rules for distinguishing if a  resource is text or binary and abort these steps.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7447)

**Comment by ddrmanxbxfr** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/mime_classifier.rs, line 22 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhAJ6ywo4amQiMjjqL)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/components/net/mime_classifier.rs#L22)):</sup>
SniffForUnknownType is basically the rule we were missing before the no_sniff check. 

It shouldn't be in this enum... I removed it and fixed the original algorithm in the classify function.

Fixing the scope of get_media_type. It should be indeed private :).
Ditto for the Option modification, great idea.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7447)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/mime_classifier.rs, line 493 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhFSOOuATERVnmY8lY)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/tests/unit/net/mime_classifier.rs#L493)):</sup>
This is true. I would still like to see an additional test that explicitly checks a case where the apache bug flag causes a resource to be classified differently than if it were disabled.

---

<sup>**[tests/wpt/css-tests/css21_dev/html4/border-left-color-125.htm, line 0 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7447#-Jym6jJC8tmKmv0ZwKN4)** ([raw file](https://github.com/servo/servo/blob/934df273d5ae5ff40973fd6830374a0b631c782d/tests/wpt/css-tests/css21_dev/html4/border-left-color-125.htm#L0)):</sup>
Accidental deletion?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7447)

**Comment by ddrmanxbxfr** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[tests/unit/net/mime_classifier.rs, line 493 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7447#-JyhFSOOuATERVnmY8lY)** ([raw file](https://github.com/servo/servo/blob/b02f025170a7859498b186728af677d4147f31e0/tests/unit/net/mime_classifier.rs#L493)):</sup>
Indeed. I added a test with the mp4 file we already had in the project.

---

<sup>**[tests/wpt/css-tests/css21_dev/html4/border-left-color-125.htm, line 0 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7447#-Jym6jJC8tmKmv0ZwKN4)** ([raw file](https://github.com/servo/servo/blob/934df273d5ae5ff40973fd6830374a0b631c782d/tests/wpt/css-tests/css21_dev/html4/border-left-color-125.htm#L0)):</sup>
Seems unrelated, not sure how Reviewable says this... If I look in the Github diff viewer this file is not removed :\. Maybe related because I rebased servo/master and then squashed the commits together ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7447)

**Comment by jdm** [comment]
-S-awaiting-review -S-needs-rebase +S-awaiting-answer 

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/mime_classifier.rs, line 536 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7447#-Jz2PFKKAjl5nrwb0UUl)** ([raw file](https://github.com/servo/servo/blob/2ae3f4a44ea40736b90c988c33154be24369f1c6/tests/unit/net/mime_classifier.rs#L536)):</sup>
I don't understand the expected output here; the video classifier shouldn't be running when the apache bug flag is enabled, right?

---

<sup>**[tests/wpt/css-tests/css21_dev/html4/border-left-color-125.htm, line 0 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7447#-Jym6jJC8tmKmv0ZwKN4)** ([raw file](https://github.com/servo/servo/blob/934df273d5ae5ff40973fd6830374a0b631c782d/tests/wpt/css-tests/css21_dev/html4/border-left-color-125.htm#L0)):</sup>
This is a known reviewable bug that was recently fixed, so nevermind.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7447)

**Comment by ddrmanxbxfr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/mime_classifier.rs, line 536 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7447#-Jz2PFKKAjl5nrwb0UUl)** ([raw file](https://github.com/servo/servo/blob/2ae3f4a44ea40736b90c988c33154be24369f1c6/tests/unit/net/mime_classifier.rs#L536)):</sup>
Good call.

All the tests with Apache Flag ON needs to have a supplied type to trigger it correctly.

I should get Application/Octet-Stream from a video/mp4 file when I have the flag at on....

This means I have a bug in my tests regarding apache flag on.

While fixing them I found that utf16-be and utf16-le were not responding the good type. We had application/octet-stream instead of text/plain.

I fixed them in BinaryOrPlaintextClassifier.

I hope it goes ok with

If length is greater than or equal to 2 and the first 2 bytes of the resource header are equal to 0xFE 0xFF (UTF-16BE BOM) or 0xFF 0xFE (UTF-16LE BOM), the computed MIME type is "text/plain". Abort these steps.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7447)

**Comment by ddrmanxbxfr** [comment]
We'll get it right @jdm once it looks ok let me know i'll rebase commits to not polute the git log.

**Comment by ddrmanxbxfr** [comment]
Ping? @jdm

**Comment by jdm** [comment]
@bors-servo: r+
Great work! Thank you for the PR!

---

Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7447)

**Pull request merged**
