### PR TITLE
Remove Unnecessary Code in FileReader #6753

### PR DESCRIPTION
**Pull request by farodin91**
@jdm r?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7001)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@bors-servo r+

Thank you for the PR.

**Comment by farodin91** [comment]
Why Travis CI doesn't test this?

**Comment by Ms2ger** [comment]
Travis can't handle building Servo. However, our own infrastructure is busy building this PR, and should be done in 20 minutes or so.

**Comment by farodin91** [comment]
@Ms2ger travis run normally the tidy test. Why not here?

**Pull request merged**
