### PR TITLE
Revert "Remove gold hack, since it's in rustc automatically now"

### PR DESCRIPTION
**Pull request by larsbergstrom**
This reverts commit 2955d895a4d723bc616f37a55a973c677318a950.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9449)

### CODE REVIEW

**Comment by notriddle** [comment]
This is probably doing to sound dumb, but why is this being reverted?

**Comment by KiChjang** [comment]
@bors-servo retry
* #9460

@notriddle See the conversation (here)[http://logs.glob.uno/?c=mozilla%23servo&s=28+Jan+2016&e=28+Jan+2016#c353891]. @mbrubeck indicated that we're still on an earlier version of Rust, so the rustc we currently have doesn't have the ability to automatically choose between gold and non-gold builds.

**Comment by KiChjang** [comment]
@bors-servo retry
* #8120

**Comment by KiChjang** [comment]
@bors-servo retry
* #8815

**Comment by KiChjang** [comment]
@bors-servo retry
* #8815

**Comment by jdm** [comment]
@bors-servo: retry
* #8157

**Comment by larsbergstrom** [comment]
@notriddle We have to revert the removal of the gold linker support because Rust reverted their detection/use of the gold linker.

Or in less obtuse language (too many negatives & removals!), we need to add back the code to detect when we can use the gold linker, since it no longer exists in Rust.

**Comment by notriddle** [comment]
Yeah, I get it.

**Pull request merged**
