### PR TITLE
Enable CSS Color wpt tests

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7121)

### CODE REVIEW

**Comment by metajack** [comment]
Next time, please keep the unrelated changes in separate commits.

---

Reviewed 84 of 84 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7121)

**Comment by dzbarsky** [comment]
the update-css command made all those changes =( I'm not sure why it changed things outside of the color tests, those were the only ones I ran.

**Comment by jdm** [comment]
That's the tool automatically simplifying unnecessary parentheses, I expect.

**Comment by metajack** [comment]
Carry on then. No need to overcomplicate things if the tools aren't helping.

**Comment by Ms2ger** [comment]
(I interrupted that run because it'd been timing out tests one after the other for three hours.)

**Comment by mbrubeck** [comment]
@bors-servo retry

It's not clear why the tests started timing out after the first 30 seconds on the Mac builder.  Testing to see if it was just an unrelated problem with the build machine.  I'll keep an eye on this and cancel it if it happens again.

**Comment by larsbergstrom** [comment]
This happened on the machine servo-mac1, which went DOA earlier this morning and had to be manually powered back on by the macstadium folks.

**Pull request merged**
