### PR TITLE
Update heartbeats and energymon dependencies

### PR DESCRIPTION
**Pull request by connorimes**
Also aligns the heartbeats profiling script with current ProfilerCategory values.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9204)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo retry

 - #9163

**Comment by KiChjang** [comment]
@bors-servo retry
* #9163

**Comment by KiChjang** [comment]
@bors-servo retry
* #7625

**Comment by ecoal95** [comment]
@bors-servo: retry
 * Was #7625, should be fixed now

**Comment by ecoal95** [comment]
@bors-servo: retry
 * #9163 (*sigh*)

**Comment by KiChjang** [comment]
@bors-servo retry
* #9163

**Pull request merged**
