### PR TITLE
Start running reftests with wptrunner.

### PR DESCRIPTION
**Pull request by Ms2ger**
CC #5618.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5687)

### CODE REVIEW

**Comment by jdm** [comment]
I tried to look into this but I can't figure out how to run serve.py locally and run any tests under _mozilla.

**Comment by Ms2ger** [comment]
So if you run a single test, Servo remains open and while it's open, you can access the server (though not directory listings) with `./mach run`

**Comment by larsbergstrom** [comment]
To run this locally by itself, you do:
```
./mach test-wpt _mozilla/css/abs_float_pref_width.html --log-raw=something.log
```
And then can plug something.log into: http://hoppipolla.co.uk/410/reftest-analyser-structured.xhtml

It appears that pixels around the edge of the box are "fuzzy" in the floated version that uses the ahem font to make the big green square, and only on OSX (this test passes on Linux).

**Comment by larsbergstrom** [comment]
@pcwalton Have you seen anything where font rendering is fuzzy on OSX, particularly with ahem, as if it has been floated to a fractional position?

The file at https://github.com/Ms2ger/servo/blob/427ec5bdbae3a54b10932dfafdd8b087039fd46d/tests/wpt/mozilla/tests/css/abs_float_pref_width.html renders a green square, but the pixels at column 99 (which should be white) appear to be about 2/3 saturated green. Similarly, the pixels at column 300 differ.

**Comment by Ms2ger** [comment]
I'm not surprised that aligning on fractional pixels would cause issues, but this test appears to pass fine in the rust harness?

**Comment by larsbergstrom** [comment]
Needs:
```
 -Z disable-text-aa
```

As used in: https://github.com/servo/servo/blob/master/tests/reftest.rs#L254-L256

I confirmed that without that flag we get the identical failing behavior in the current codebase, and with the flag things appear to work correctly (from the commandline, at least).

cc @jgraham

**Comment by jgraham** [comment]
https://critic.hoppipolla.co.uk/r/4848

**Comment by Ms2ger** [comment]
https://github.com/servo/servo/pull/5901

**Pull request merged**
