### PR TITLE
layout: Draw the insertion point in input elements.

### PR DESCRIPTION
**Pull request by pcwalton**
Known issues:
- The caret doesn't show up if there's no text present, because we don't create text runs in that case. This should be a followup.
- Text runs don't support decomposing ligatures into their constituent subglyphs for advance computation, so the caret won't appear inside a ligature. This is a text run bug.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7644)

### CODE REVIEW

**Comment by jdm** [comment]
This is a really nice series of self-contained commits. Nicely done!

**Comment by mbrubeck** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 6 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/layout/construct.rs, line 723 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7644#-JzJ_qNXcT3GJF-NQfFV)** ([raw file](https://github.com/servo/servo/blob/35f617827603011c98b666ef4707203b5a5442d5/components/layout/construct.rs#L723)):</sup>
This assumes the `text_content` vector contains only one String item. It looks like this has issues when the element contains generated string content, e.g. `input:before { content: "hello"; }`.

Really we shouldn't be rendering generated content in `input` and `textarea` elements at all, which is a separate issue. The situation for contenteditable will be a little more complicated.

Perhaps `ThreadSafeLayoutNode::text_content` should return something like this instead of a Vec:

```rust
enum TextContent {
    Text(String),
    GeneratedContent(Vec<ContentItem>),
}
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7644)

**Comment by pcwalton** [comment]
Changed that method.

@mbrubeck r?

**Comment by mbrubeck** [comment]
Reviewed 6 of 6 files at r10.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7644)

**Pull request merged**
