### PR TITLE
Implement 'align' attribute for <div> elements

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7953)

### CODE REVIEW

**Comment by frewsxcv** [comment]
So I need a little help with this.

At the time of writing, this test fails after this pull request: 
`tests/wpt/metadata/html/rendering/non-replaced-elements/flow-content-0/div-align.html`

I'm actually not even sure how it was passing prior to this getting implemented. I'm guessing it fails now because [this](https://github.com/servo/servo/pull/7953/files#diff-9082d52f79e121265b7ddf64d11fe044R352) isn't implemented? If anyone has any thoughts, please let me know, thanks.

**Comment by eefriedman** [comment]
See https://github.com/servo/servo/blob/ab42ca42967354cba08d1dca83aa99a637bd7a6b/resources/presentational-hints.css#L10 .  See also #7825.

I don't think there's any reason to move the rendering rule from presentational-hints.css to synthesize_presentational_hints_for_legacy_attributes.

**Comment by nox** [comment]
> I don't think there's any reason to move the rendering rule from presentational-hints.css to synthesize_presentational_hints_for_legacy_attributes.

Not all presentational hints can be expressed through CSS, though.

**Comment by frewsxcv** [comment]
Will those CSS hints work correctly with the IDL/content getters/setters? Also, align=center is not part of the spec

**Comment by nox** [comment]
@frewsxcv You sure?

> The center element, and the div element when it has an align attribute whose value is an ASCII case-insensitive match for either the string "center" or the string "middle", are expected to center text within themselves, as if they had their 'text-align' property set to 'center' in a presentational hint, and to align descendants to the center.

**Comment by nox** [comment]
@frewsxcv I'm pretty sure you can just implement reflecting IDL getters and setters and consider that attribute to hold onto a plain old string.

**Comment by nox** [comment]
@frewsxcv For other presentational hints, like the one related to the non-zero table border, or fancy color attributes that need to be parsed, we can't avoid going through the synthesis machinery, but I'm pretty sure we prefer going through CSS for the simpler one, as mentioned by @eefriedman.

**Comment by frewsxcv** [comment]
You're right. I totally glossed over that first paragraph because I thought it only applied to `center` elements

**Comment by frewsxcv** [comment]
Thanks all for the help, very helpful information to know :)

Force push incoming...

**Comment by frewsxcv** [comment]
Ready for review

**Comment by mbrubeck** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7953)

**Comment by frewsxcv** [comment]
@bors-servo retry

* #7731

**Pull request merged**
