### PR TITLE
Move `MozBrowserEvent` to `script_traits`

### LINKED ISSUE #9225: Move MozBrowserEvent to script_traits
It's defined in `msg` but only used by `compositing`, `script`, and `script_traits`. It belongs in `script_traits`.

Code: `components/msg/constellation_msg.rs`, `components/script_traits/lib.rs`

### PR DESCRIPTION
**Pull request by apopiak**
close #9225

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9271)

### CODE REVIEW

**Comment by apopiak** [comment]
sry, overlooked the WIP and the rebase

**Comment by KiChjang** [comment]
-S-awaiting-review +S-needs-code-changes

Thanks for taking up the issue! A couple of minor nits and this can be merged :)

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/compositing/constellation.rs, line 33 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9271#-K7prGjEy5KssY46NNke:-K7prGjEy5KssY46NNkf:-1775640667) ([raw file](https://github.com/servo/servo/blob/06911b6808289345221969748e8f74b3b690ea02/components/compositing/constellation.rs#L33)):*
nit: Remove the braces and meld into next/previous line.

---

*[components/compositing/constellation.rs, line 49 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9271#-K7prWXJKwojuwt1Z2SG:-K7prWXJKwojuwt1Z2SH:1876232759) ([raw file](https://github.com/servo/servo/blob/06911b6808289345221969748e8f74b3b690ea02/components/compositing/constellation.rs#L49)):*
nit: Meld into next line.

---

*[components/compositing/pipeline.rs, line 28 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9271#-K7prUPKqE0raQvZPWCz:-K7prUPKqE0raQvZPWD-:1609343547) ([raw file](https://github.com/servo/servo/blob/06911b6808289345221969748e8f74b3b690ea02/components/compositing/pipeline.rs#L28)):*
nit: Meld into previous line.

---

*[components/script/dom/htmliframeelement.rs, line 29 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9271#-K7prPPg-4ykIioODHn_:-K7prPPg-4ykIioODHna:1876232759) ([raw file](https://github.com/servo/servo/blob/06911b6808289345221969748e8f74b3b690ea02/components/script/dom/htmliframeelement.rs#L29)):*
nit: Meld into next line.

---

*[components/script/dom/htmliframeelement.rs, line 34 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9271#-K7pr__XsfqK6OOOSySF:-K7pr__XsfqK6OOOSySG:505382524) ([raw file](https://github.com/servo/servo/blob/06911b6808289345221969748e8f74b3b690ea02/components/script/dom/htmliframeelement.rs#L34)):*
nit: Combine `IFrameLoadInfo`, `MozBrowserEvent` and `ScriptMsg as ConstellationMsg` into one line.

---

*[components/script/dom/htmllinkelement.rs, line 27 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9271#-K7prncDL2l61qICxa2n:-K7prncDL2l61qICxa2o:807088125) ([raw file](https://github.com/servo/servo/blob/06911b6808289345221969748e8f74b3b690ea02/components/script/dom/htmllinkelement.rs#L27)):*
nit: Remove the braces.

---

*[components/script/dom/htmllinkelement.rs, line 30 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9271#-K7prpSVToIUYsxcQIgk:-K7prpSVToIUYsxcQIgl:1876232759) ([raw file](https://github.com/servo/servo/blob/06911b6808289345221969748e8f74b3b690ea02/components/script/dom/htmllinkelement.rs#L30)):*
nit: Meld into next line.

---

*[components/script/dom/window.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9271#-K7prsNS7DdK_NtNM7Lp:-K7prsNS7DdK_NtNM7Lq:1876232759) ([raw file](https://github.com/servo/servo/blob/06911b6808289345221969748e8f74b3b690ea02/components/script/dom/window.rs#L60)):*
nit: Meld into next line.

---

*[components/script/script_thread.rs, line 86 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9271#-K7prvn-uWcj02B1MFur:-K7prvn-uWcj02B1MFus:-964041917) ([raw file](https://github.com/servo/servo/blob/06911b6808289345221969748e8f74b3b690ea02/components/script/script_thread.rs#L86)):*
nit: Meld into next/previous line.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9271#-:-K7pr6961QqGUlt4glGE:-590803171)*

**Comment by KiChjang** [comment]
-S-awaiting-review 

All good! Thanks for taking the time to work on this!

@bors-servo r+

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9271#-:-K7rWR6yyCla30C6CODB:1062075165)*

**Comment by nox** [comment]
@bors-servo retry

Git snafu.

**Comment by apopiak** [comment]
rebased

**Comment by apopiak** [comment]
@KiChjang and another `commit --amend` because the rebase wasn't clean (I left a doubling of `DocumentState` in)

**Pull request merged**
