### PR TITLE
Implement async fetching of extenal script sources via interruptible parsing.

### PR DESCRIPTION
**Pull request by jdm**
Requires https://github.com/servo/html5ever/pull/107 and #5156.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5197)

### CODE REVIEW

**Comment by jdm** [comment]
(Only the last two commits are new since #5156)

**Comment by metajack** [comment]
Assigning @SimonSapin to review.

**Comment by metajack** [comment]
@jdm I think this is back to you for changes.

**Comment by Manishearth** [comment]
(Note: I've looked through most of this, it seems fine to me -- in case it's still blocked on my review)

**Comment by jdm** [comment]
Nope, just waiting on me to address the comments.

**Pull request closed without merging**
