### PR TITLE
Update WR (move glyph data to gpu cache and halve glyph alloc/uploads).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17196)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /_mozilla/css/multiple_backgrounds.html
  └   → /_mozilla/css/multiple_backgrounds.html 280814457901af927805056747079352dc62d327
/_mozilla/css/multiple_backgrounds_ref.html 1a09e2de443d18de1c2fe3acbf8e364fd3f6a5cc
Testing 280814457901af927805056747079352dc62d327 == 1a09e2de443d18de1c2fe3acbf8e364fd3f6a5cc
```

**Comment by glennw** [comment]
I've investigated and found the cause of this failure (it's intermittent).

In the reftest analyzer, there are a small number of pixels (typically ~12) that are off by a single bit in one channel (i.e. 1.0 / 255.0).

The cause of this is the non-determinism in order of loaded images from Servo. The test in question has two background images. When they load in a different order, they end up at a different location in the texture atlas.

This different location, coupled with floating point inaccuracy is enough to cause the small differences in a few pixels.

This has started occurring due to https://github.com/servo/webrender/pull/1338/files - in that PR, I removed two small 2x2 dummy images that were added to the texture cache during initialization. These images are no longer required. That change is good, it just happened to mask the non-determinism in this test by chance.

Ideally, we could mark this test as fuzzy - but WPT test runner doesn't support that. In absence of fuzzy support, some options are to:

1) Disable this test altogether / mark as intermittent.
2) Switch the test to only have one image (perhaps use a url gradient as a replacement for the other image - there is already a gradient in use though for the third layer). I don't think that would affect what this is testing?).
3) Make image loading order deterministic during tests.

Thoughts @jdm or anyone? Is (3) feasible?

**Comment by jdm** [comment]
We could make the image order deterministic by using built-in WPT pipes to delay the load of the second image by a second (add `?pipe=trickle(d1)` to the URL and it should Just Work).

**Comment by glennw** [comment]
That syntax seems to fail to parse correctly in ```url()``` CSS fields.

**Comment by glennw** [comment]
Updated the test to try and force load order of the background images. It seems to work for me locally, hopefully that will work on CI machines too.

r? @jdm

**Comment by jdm** [comment]
@bors-servo r-
Needs a manifest update.

**Comment by glennw** [comment]
Updated the manifest.

@bors-servo r=jdm

**Pull request merged**
