### PR TITLE
Fix the hasInstance hook of interface objects

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9645)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/bindings/interface.rs, line 264 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9645#-KAZs5Xsoi92hEQmgG5d:-KAZs5Xsoi92hEQmgG5e:1579555168) ([raw file](https://github.com/servo/servo/blob/cd4c2cc36c0c39aae06eda61b23a479a823edb22/components/script/dom/bindings/interface.rs#L264)):*
`interface_object`

---

*[components/script/dom/bindings/interface.rs, line 286 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9645#-KAZsm-w1zbXrW8vE8vz:-KAZsm-w1zbXrW8vE8w-:-1109426461) ([raw file](https://github.com/servo/servo/blob/cd4c2cc36c0c39aae06eda61b23a479a823edb22/components/script/dom/bindings/interface.rs#L286)):*
I think this is guaranteed to be the *interface prototype object*, which we cache, so that might be an easier way to get hold of the object.

---

*[tests/wpt/mozilla/tests/mozilla/has-instance.html, line 1 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9645#-KAZrudE4dLfwn86Dlon:-KAZrudFbmV80BMxzJJ_:680695770) ([raw file](https://github.com/servo/servo/blob/cd4c2cc36c0c39aae06eda61b23a479a823edb22/tests/wpt/mozilla/tests/mozilla/has-instance.html#L1)):*
Why not upstream?

---

*[tests/wpt/mozilla/tests/mozilla/has-instance.html, line 8 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9645#-KAZrmUJRMW1N5fWrQtg:-KAZrmUJRMW1N5fWrQth:1519125944) ([raw file](https://github.com/servo/servo/blob/cd4c2cc36c0c39aae06eda61b23a479a823edb22/tests/wpt/mozilla/tests/mozilla/has-instance.html#L8)):*
I think `Object.create()` is the preferred approach.

---

*[tests/wpt/mozilla/tests/mozilla/has-instance.html, line 9 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9645#-KAZrzZHMEtuzT-59M7X:-KAZrzZI8a1IOWiqjm4z:-302618140) ([raw file](https://github.com/servo/servo/blob/cd4c2cc36c0c39aae06eda61b23a479a823edb22/tests/wpt/mozilla/tests/mozilla/has-instance.html#L9)):*
Also test `Element`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9645#-:-KAZt0DU7KZlxO7cTOWi:1458266033)*

**Comment by nox** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/bindings/interface.rs, line 286 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9645#-KAZsm-w1zbXrW8vE8vz:-KAZyJVuASFEPt57nYcO:-499146009) ([raw file](https://github.com/servo/servo/blob/cd4c2cc36c0c39aae06eda61b23a479a823edb22/components/script/dom/bindings/interface.rs#L286)):*
Done.

---

*[tests/wpt/web-platform-tests/WebIDL/ecmascript-binding/has-instance.html, line 1 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9645#-KAZrudE4dLfwn86Dlon:-KAZyFwoR3RH8sxBEMHm:-499146009) ([raw file](https://github.com/servo/servo/blob/cd4c2cc36c0c39aae06eda61b23a479a823edb22/tests/wpt/web-platform-tests/WebIDL/ecmascript-binding/has-instance.html#L1)):*
Done.

---

*[tests/wpt/web-platform-tests/WebIDL/ecmascript-binding/has-instance.html, line 8 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9645#-KAZrmUJRMW1N5fWrQtg:-KAZyGIBlUPQCFx34TRD:-499146009) ([raw file](https://github.com/servo/servo/blob/cd4c2cc36c0c39aae06eda61b23a479a823edb22/tests/wpt/web-platform-tests/WebIDL/ecmascript-binding/has-instance.html#L8)):*
Done.

---

*[tests/wpt/web-platform-tests/WebIDL/ecmascript-binding/has-instance.html, line 9 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9645#-KAZrzZHMEtuzT-59M7X:-KAZyG_YiqBzQ9Zw9rec:-499146009) ([raw file](https://github.com/servo/servo/blob/cd4c2cc36c0c39aae06eda61b23a479a823edb22/tests/wpt/web-platform-tests/WebIDL/ecmascript-binding/has-instance.html#L9)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9645)*

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/bindings/interface.rs, line 286 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9645#-KA_-Z9Vh_sxP_J4FFjJ:-KA_-Z9WdSd8ozgk6Llm:-15323706) ([raw file](https://github.com/servo/servo/blob/ca0a957f46bdddcb9747097035e27e65c338422c/components/script/dom/bindings/interface.rs#L286)):*
I would prefer not to use `from_marked_location` here; this code is not hot enough to warrant it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9645#-:-KA_-uH_pxS4iAURRC8k:1458266033)*

**Comment by nox** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/bindings/interface.rs, line 286 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9645#-KA_-Z9Vh_sxP_J4FFjJ:-KA_36aY8AjvFwvGew9j:-499146009) ([raw file](https://github.com/servo/servo/blob/ca0a957f46bdddcb9747097035e27e65c338422c/components/script/dom/bindings/interface.rs#L286)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9645)*

**Comment by Ms2ger** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9645#-:-KA_4YdDQe0gjh7Mokry:1236647940)*

**Pull request merged**
