### PR TITLE
adding .isConnected DOM attribute

### LINKED ISSUE #25126: Implement Node.isConnected
https://dom.spec.whatwg.org/#interface-node has it in IDL, Servo does not, WPT dom/nodes/Node-isConnected.html tests it.

### PR DESCRIPTION
**Pull request by pshaughn**
is_connected already existed for this concept and just needed to be hooked up to an IDL attribute.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25126 

- [X] There are tests for these changes OR

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /dom/idlharness.window.html?include=Node:
  └ PASS [expected FAIL] Node interface: attribute isConnected
  ▶ Unexpected subtest result in /dom/idlharness.window.html?include=Node:
  └ PASS [expected FAIL] Node interface: new Document() must inherit property "isConnected" with the proper type
  ▶ Unexpected subtest result in /dom/idlharness.window.html?include=Node:
  └ PASS [expected FAIL] Node interface: xmlDoc must inherit property "isConnected" with the proper type
  ▶ Unexpected subtest result in /dom/idlharness.window.html?include=Node:
  └ PASS [expected FAIL] Node interface: document.doctype must inherit property "isConnected" with the proper type
  ▶ Unexpected subtest result in /dom/idlharness.window.html?include=Node:
  └ PASS [expected FAIL] Node interface: document.createDocumentFragment() must inherit property "isConnected" with the proper type
  ▶ Unexpected subtest result in /dom/idlharness.window.html?include=Node:
  └ PASS [expected FAIL] Node interface: element must inherit property "isConnected" with the proper type
  ▶ Unexpected subtest result in /dom/idlharness.window.html?include=Node:
  └ PASS [expected FAIL] Node interface: document.createTextNode("abc") must inherit property "isConnected" with the proper type
  ▶ Unexpected subtest result in /dom/idlharness.window.html?include=Node:
  └ PASS [expected FAIL] Node interface: xmlDoc.createProcessingInstruction("abc", "def") must inherit property "isConnected" with the proper type
  ▶ Unexpected subtest result in /dom/idlharness.window.html?include=Node:
  └ PASS [expected FAIL] Node interface: document.createComment("abc") must inherit property "isConnected" with the proper type
```

**Comment by CYBAI** [comment]
```
  ▶ Unexpected subtest result in /html/semantics/forms/the-option-element/option-text-setter.html:
  └ PASS [expected FAIL] Verify that using HTMLOptionElement.text setter does not update the existing text child node.
```

**Comment by pshaughn** [comment]
These all look unrelated to me?
@bors-servo retry

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Pull request merged**
