### PR TITLE
Improve prototypes of global objects

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13030)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2498 \[r2\]](https://reviewable.io:443/reviews/servo/servo/13030#-KQ0UUggN1VoWeUiQ01J:-KQ0UUggN1VoWeUiQ01K:b-2du3pb) ([raw file](https://github.com/servo/servo/blob/2f180e37f88917ebf3bec4cec057fb6b64244eb6/components/script/dom/bindings/codegen/CodegenRust.py#L2498)):*
> ```Python
> 
> 
> class CGWrapGlobalMethod(CGAbstractMethod):
> ```

Two empty lines between classes

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2520 \[r4\]](https://reviewable.io:443/reviews/servo/servo/13030#-KQ0VVjfL4sTCNAqLJuI:-KQ0VVjg-_M_SbDkC4gE:blw2uhu) ([raw file](https://github.com/servo/servo/blob/4b1f03caf53f30e5768d5c77ee50b4d742a16ce1/components/script/dom/bindings/codegen/CodegenRust.py#L2520)):*
> ```Python
>     create_global_object(
>         cx,
>         &*(&Class.base as *const js::jsapi::Class as *const _),
> ```

If `Class.base` was a `JSClass`, this would be a lot nicer... File a followup.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2516 \[r6\]](https://reviewable.io:443/reviews/servo/servo/13030#-KQ0Wae2sq-3yCYm2lzW:-KQ0Wae3Shnawl3o9rNw:b8lnkyh) ([raw file](https://github.com/servo/servo/blob/75281af9255edaa7312d99710ff5c813bdcf7b14/components/script/dom/bindings/codegen/CodegenRust.py#L2516)):*
> ```Python
>         }
> 
>         defineAttrs = "define_guarded_properties(cx, obj.handle(), %s);"
> ```

Why not

```python
pairs = [
    ("define_guarded_properties", self.properties.attrs),

members.append(CGGeneric("%s(cx, obj.handle(), %s);" % (function, array.variableName())))
```

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2551 \[r7\]](https://reviewable.io:443/reviews/servo/servo/13030#-KQ0XIH5Aq6QrxiU0AVp:-KQ0XIH6TzB5TQh9i1FR:bl2nz1t) ([raw file](https://github.com/servo/servo/blob/5d6968edd59ae33ce1e6d6ba22aa94aa3f8e3824/components/script/dom/bindings/codegen/CodegenRust.py#L2551)):*
> ```Python
> assert!(JS_SplicePrototype(cx, obj.handle(), proto.handle()));
> let mut immutable = false;
> assert!(JS_SetImmutablePrototype(cx, obj.handle(), &mut immutable));
> ```

Is there a spec for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13030)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2498 \[r2\]](https://reviewable.io:443/reviews/servo/servo/13030#-KQ0UUggN1VoWeUiQ01J:-KQ0cZgjqPsXYGAJn9kD:b-896fix) ([raw file](https://github.com/servo/servo/blob/2f180e37f88917ebf3bec4cec057fb6b64244eb6/components/script/dom/bindings/codegen/CodegenRust.py#L2498)):*
<details><summary><i>Previously, Ms2ger wrote…</i></summary>
> Two empty lines between classes
</details>
Done.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2520 \[r4\]](https://reviewable.io:443/reviews/servo/servo/13030#-KQ0VVjfL4sTCNAqLJuI:-KQ0cbQyFOLIbEsszmIk:b-896fix) ([raw file](https://github.com/servo/servo/blob/4b1f03caf53f30e5768d5c77ee50b4d742a16ce1/components/script/dom/bindings/codegen/CodegenRust.py#L2520)):*
<details><summary><i>Previously, Ms2ger wrote…</i></summary>
> If `Class.base` was a `JSClass`, this would be a lot nicer... File a followup.
</details>
Done.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2516 \[r6\]](https://reviewable.io:443/reviews/servo/servo/13030#-KQ0Wae2sq-3yCYm2lzW:-KQ0c_R64lVSpk4pQoP9:b-896fix) ([raw file](https://github.com/servo/servo/blob/75281af9255edaa7312d99710ff5c813bdcf7b14/components/script/dom/bindings/codegen/CodegenRust.py#L2516)):*
<details><summary><i>Previously, Ms2ger wrote…</i></summary>
> Why not
> 
> ```python
> pairs = [
>     ("define_guarded_properties", self.properties.attrs),
> 
> members.append(CGGeneric("%s(cx, obj.handle(), %s);" % (function, array.variableName())))
> ```
</details>
Done.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2551 \[r7\]](https://reviewable.io:443/reviews/servo/servo/13030#-KQ0XIH5Aq6QrxiU0AVp:-KQ0cbukotY8zIVGvD1r:b5ldei1) ([raw file](https://github.com/servo/servo/blob/5d6968edd59ae33ce1e6d6ba22aa94aa3f8e3824/components/script/dom/bindings/codegen/CodegenRust.py#L2551)):*
<details><summary><i>Previously, Ms2ger wrote…</i></summary>
> Is there a spec for this?
</details>
No idea, but Gecko does it and @jdm filed an issue about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13030)*

**Comment by Ms2ger** [comment]
Reviewed 1 of 3 files at r9, 3 of 4 files at r12, 1 of 1 files at r13, 7 of 8 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13030)*

**Comment by bzbarsky** [comment]
> Is there a spec for this?

You mean the immutable prototype thing?  See https://github.com/heycam/webidl/pull/133

**Pull request merged**
