### PR TITLE
Stylo: Add some missing pseudo classes

### PR DESCRIPTION
**Pull request by canova**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix [Bug 1341739](https://bugzilla.mozilla.org/show_bug.cgi?id=1341739)

- [X] These changes do not require tests because they are stylo changes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15983)

### CODE REVIEW

**Comment by canaltinova** [comment]
Reviewed by @upsuper 
r? @upsuper

**Comment by KWierso** [comment]
This change caused mochitest-style test failures when it got merged to autoland: https://treeherder.mozilla.org/logviewer.html#?job_id=84297787&repo=autoland

@canaltinova Can we revert this if the test expectations can't be adjusted soon?

**Comment by bholley** [comment]
I think for this case we should just annotate those two failures and get a bug on file.

**Comment by bholley** [comment]
I adjusted the expectations.

**Pull request merged**
