### PR TITLE
Update to Rust 1.14.0-nightly (19ac57926 2016-10-08)

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13649)

### CODE REVIEW

**Comment by nox** [comment]
If merged right now, this does hundreds of spurious warnings because of https://github.com/rust-lang/rust/pull/37034.

**Comment by nox** [comment]
This can be merged but triggers 720 spurious warnings. The nightly that was supposed to land today include a fix for the warnings, but [the build failed](https://buildbot.rust-lang.org/builders/nightly-dist-rustc-linux/builds/676). Should I just go ahead with this nightly even if it outputs stupid warnings?

**Comment by nox** [comment]
OK, I was wrong. The nightlies are uploaded to S3 only when all the boxes finished building, and that wasn't the last remaining build. Things should be ok in one hour.

**Comment by jdm** [comment]
```
thread 'rustc' panicked at 'assertion failed: bpos.to_usize() >= mbc.pos.to_usize() + mbc.bytes', ../src/libsyntax\codemap.rs:707
stack backtrace:
   0:         0x61eaf524 - <unknown>
   1:         0x61eabdaa - <unknown>
   2:         0x61eac51a - <unknown>
   3:         0x6ee89453 - <unknown>
   4:         0x6eeec431 - <unknown>
   5:         0x6eee997f - <unknown>
   6:         0x64b133f5 - <unknown>
   7:         0x64b13223 - <unknown>
   8:         0x64b17ba2 - <unknown>
   9:         0x64b15a38 - <unknown>
  10:         0x64ab50cd - <unknown>
  11:         0x64b36746 - <unknown>
  12:         0x64ab87fd - <unknown>
  13:         0x687bdb7d - <unknown>
  14:         0x687fadc5 - <unknown>
  15:         0x687f0552 - <unknown>
  16:         0x6872cef5 - <unknown>
  17:         0x687ac37d - <unknown>
  18:         0x687d1496 - <unknown>
  19:         0x68709bb5 - <unknown>
  20:         0x61eb8118 - <unknown>
  21:         0x687256c2 - <unknown>
  22:         0x61ea9e92 - <unknown>
  23:      0x7ff66fd1841 - <unknown>

error: internal compiler error: unexpected panic
```
Uh oh.

**Comment by jdm** [comment]
Other platforms worked fine.

**Comment by nox** [comment]
With the workaround commit, [the build seems to be fine](http://build.servo.org/builders/windows-dev/builds/1370).

@jdm r?

**Comment by nox** [comment]
#13662

**Pull request merged**
