### PR TITLE
Implement stub for NavigatorPlugins

### PR DESCRIPTION
**Pull request by cbrewster**
This PR implements stub for NavigatorPlugins as outlined in #9991.

r? @jdm

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10485)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Looks good, but let's remove some code.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 13 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/script/dom/mimetype.rs, line 19 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10485#-KF4l_PwNsYjKIAGgxDE:-KF4l_PwNsYjKIAGgxDF:1740266806) ([raw file](https://github.com/servo/servo/blob/d3c18ba72b30fefba534f185039434f1ded7a7f1/components/script/dom/mimetype.rs#L19)):*
Since we never construct an instance of this interface, remove `new` and `new_inherited`.

---

*[components/script/dom/mimetype.rs, line 35 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10485#-KF4li_NH5QZig25BM5u:-KF4li_NH5QZig25BM5v:1285371229) ([raw file](https://github.com/servo/servo/blob/d3c18ba72b30fefba534f185039434f1ded7a7f1/components/script/dom/mimetype.rs#L35)):*
Make all those `unreachable!()`.

---

*[components/script/dom/mimetype.rs, line 50 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10485#-KF4krK5RPFhMuc95deV:-KF4krK5RPFhMuc95deW:-622485008) ([raw file](https://github.com/servo/servo/blob/d3c18ba72b30fefba534f185039434f1ded7a7f1/components/script/dom/mimetype.rs#L50)):*
For future reference: this is not allowed; you'd need to use `Plugin::new()`.

---

*[components/script/dom/plugin.rs, line 19 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10485#-KF4ltILBI6qtrRWsZsz:-KF4ltILBI6qtrRWsZt-:730986700) ([raw file](https://github.com/servo/servo/blob/d3c18ba72b30fefba534f185039434f1ded7a7f1/components/script/dom/plugin.rs#L19)):*
Same as for `MimeType`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10485#-:-KF4m2SZmH5u_YLsciHA:1353985119)*

**Comment by ConnorGBrewster** [comment]
Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/mimetype.rs, line 19 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10485#-KF4l_PwNsYjKIAGgxDE:-KF4o0zGCPiZVDynLEFP:-499146009) ([raw file](https://github.com/servo/servo/blob/d3c18ba72b30fefba534f185039434f1ded7a7f1/components/script/dom/mimetype.rs#L19)):*
Done.

---

*[components/script/dom/mimetype.rs, line 35 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10485#-KF4li_NH5QZig25BM5u:-KF4o1JSgZdAL6i13oiL:-499146009) ([raw file](https://github.com/servo/servo/blob/d3c18ba72b30fefba534f185039434f1ded7a7f1/components/script/dom/mimetype.rs#L35)):*
Done.

---

*[components/script/dom/mimetype.rs, line 50 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10485#-KF4krK5RPFhMuc95deV:-KF4o1rGq00a8lQiDdtr:-499146009) ([raw file](https://github.com/servo/servo/blob/d3c18ba72b30fefba534f185039434f1ded7a7f1/components/script/dom/mimetype.rs#L50)):*
Done.

---

*[components/script/dom/plugin.rs, line 19 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10485#-KF4ltILBI6qtrRWsZsz:-KF4o2FGQtppTeLIKLBJ:-499146009) ([raw file](https://github.com/servo/servo/blob/d3c18ba72b30fefba534f185039434f1ded7a7f1/components/script/dom/plugin.rs#L19)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10485)*

**Comment by Ms2ger** [comment]
Thanks! Please squash, LGTM once that's done.

-S-awaiting-review +S-needs-squash 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10485#-:-KF4qzyhykJEv7rDLeZX:-1444927828)*

**Comment by ConnorGBrewster** [comment]
@Ms2ger squashed

**Comment by Ms2ger** [comment]
@bors-servo r+

-S-needs-squash -S-awaiting-review +S-awaiting-merge 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10485#-:-KF4tobppvOvP7lZaHEW:663128804)*

**Pull request merged**
