### PR TITLE
Implement Msg::Status with serialized url upon mouseover

### LINKED ISSUE #6178: links should send status message with url to constellation/compositor on mouseover
handle_mouse_move_event() in dom/document.rs seems to be the place for it

@Ms2ger @Manishearth

### PR DESCRIPTION
**Pull request by brunoabinader**
Credits for Mike Blumenkrantz (@zmike), I just rebased against trunk and
fixed the url serialization.

Fixes #6178.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6181)

### CODE REVIEW

**Comment by zmike** [comment]
Hooray!

**Comment by larsbergstrom** [comment]
Review status: 9 of 10 files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/compositing/compositor.rs @ r1
- components/compositing/compositor_task.rs @ r1
- components/compositing/constellation.rs @ r1
- components/compositing/headless.rs @ r1
- components/compositing/windowing.rs @ r1
- components/msg/constellation_msg.rs @ r1
- ports/cef/window.rs @ r1
- ports/glutin/window.rs @ r1
- ports/gonk/src/window.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6181)

**Comment by jdm** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.
Reviewed files:
- components/script/dom/document.rs @ r1

---

<sup>**[components/script/dom/document.rs, line 655 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6181#-JqGYVp9T38r0obLz6TZ)** ([raw file](https://github.com/servo/servo/blob/de79c295a34ff37d11adaa0dd249070fc8883ffc/components/script/dom/document.rs#L655)):</sup>
Let's add a `let target = target.root();` and clean up these two lines.

---

<sup>**[components/script/dom/document.rs, line 660 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6181#-JqGZeWk_CKMqVRkqUEt)** ([raw file](https://github.com/servo/servo/blob/de79c295a34ff37d11adaa0dd249070fc8883ffc/components/script/dom/document.rs#L660)):</sup>
Let's add a loop to the MouseMoveEvent handler in script_task.rs instead of doing this work here.

---

<sup>**[components/script/dom/document.rs, line 698 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6181#-JqGZQSctlbl9AmubHvV)** ([raw file](https://github.com/servo/servo/blob/de79c295a34ff37d11adaa0dd249070fc8883ffc/components/script/dom/document.rs#L698)):</sup>
Let's move this whole loop to the MouseMoveEvent handler in script_task.rs instead of adding it here.

---

<sup>**[components/script/dom/document.rs, line 703 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6181#-JqGYnTUl5vRom1FanoF)** ([raw file](https://github.com/servo/servo/blob/de79c295a34ff37d11adaa0dd249070fc8883ffc/components/script/dom/document.rs#L703)):</sup>
ElementCast::to_ref(anchor.r()).unwrap();

---

<sup>**[components/script/dom/document.rs, line 712 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6181#-JqGZ13UX5Sl4oXswdeI)** ([raw file](https://github.com/servo/servo/blob/de79c295a34ff37d11adaa0dd249070fc8883ffc/components/script/dom/document.rs#L712)):</sup>
We don't need any of this.

---

<sup>**[components/script/dom/document.rs, line 721 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6181#-JqGZC-oIdx_mUy6Q2fv)** ([raw file](https://github.com/servo/servo/blob/de79c295a34ff37d11adaa0dd249070fc8883ffc/components/script/dom/document.rs#L721)):</sup>
`let status = attr.map(|href| {` instead of the match.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6181)

**Comment by metajack** [comment]
@larsbergstrom re-r?

**Comment by larsbergstrom** [comment]
Reviewed 1 of 11 files at r2.
Review status: 1 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[components/script/script_task.rs, line 1426 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6181#-JvQEHsao9eALrHHTigG)** ([raw file](https://github.com/servo/servo/blob/8f497755f2747798754999a99bf50ecdfd241c48/components/script/script_task.rs#L1426)):</sup>
tiny nit: Please remove the one extra newline.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6181)

**Comment by larsbergstrom** [comment]
Reviewed 8 of 11 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6181)

**Comment by larsbergstrom** [comment]
Reviewed 1 of 11 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6181)

**Comment by larsbergstrom** [comment]
@metajack GH still thinks it needs a rebase? Plus the one nit :-)

**Comment by metajack** [comment]
@brunoabinader ping

**Comment by brunoabinader** [comment]
@metajack pong! I've rebased against master and fixed the nit :+1: 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6181)

**Comment by brunoabinader** [comment]
Please do not merge yet, I found an issue in script_task related to misusage of `root()`. Fixing it now.

**Comment by brunoabinader** [comment]
> :broken_heart: Test failed - linux1

Oops, that one didn't fired up on my OSX build. I've added a stub for glutin.

**Comment by jdm** [comment]
@bors-servo: retry
* #6818

**Pull request merged**
