### PR TITLE
Added uniform matrix functions (fixes #10671)

### LINKED ISSUE #10671: Implement uniformMatrix*v
Part of #10209.

### PR DESCRIPTION
**Pull request by autrilla**
r? @emilio

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11065)

### CODE REVIEW

**Comment by autrilla** [comment]
Just a note: Running http://mdn.github.io/webgl-examples/tutorial/sample6/ locally on Chrome is much smoother than running it on servo, and CPU usage on servo is considerably high too (10% with Chrome on all CPUs, ~70% with servo). Is it possible it is being rendered on the CPU?

**Comment by metajack** [comment]
@autrilla I suggest opening a new bug for that issue.

**Comment by autrilla** [comment]
Nice! I'll update the test expectations

**Comment by emilio** [comment]
This looks good to me @autrilla :)

Regarding the tests, don't fear marking any new subtest that looks like `successfullyParsed should be true` as failing, since that means that some previous test initialization didn't end because some function was not yet implemented.

**Comment by emilio** [comment]
Doing another try run to be if those no-longer-timeout are deterministic.

@bors-servo: r+

**Comment by emilio** [comment]
whoops,

@bors-servo: r- clean try

**Comment by KiChjang** [comment]
@bors-servo retry
* The annoying git

**Comment by nox** [comment]
Why is `/webgl/conformance-1.0.3/conformance/ogles/GL/vec/vec_009_to_016.html` timing out again? Intermittent?

**Comment by autrilla** [comment]
@nox I have no idea. @jdm ran the tests 6 times when they were enabled in #10806, but they seem to be intermittent now for some reason?

**Comment by KiChjang** [comment]
What's the status of this?

**Comment by autrilla** [comment]
@KiChjang there were unrelated failing tests and also some related tests failing, iirc.

**Comment by KiChjang** [comment]
@autrilla Can you rebase to recent master? I'll make a try run and see if it still persists.

**Comment by KiChjang** [comment]
Okay, it looks like something went wrong with your rebase. The first commit you have on this tree has over 3,000 line additions...

**Comment by autrilla** [comment]
@KiChjang yes, gonk was removed from ports, so there's a huge cargo.lock there, and also some other cargo.locks. I'll get that fixed asap

**Comment by KiChjang** [comment]
@autrilla Is this still being worked on?

**Comment by KiChjang** [comment]
Closing due to inactivity.

**Pull request closed without merging**
