### PR TITLE
Use new DisplayListBuilder improvements in Servo

### PR DESCRIPTION
**Pull request by mrobinson**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they should not change behavior.

In particular, we no longer to have a WebRenderFrameBuilder. All of the
complication is now handled by the DisplayListBuilder itself.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14386)

### CODE REVIEW

**Comment by glennw** [comment]
@mrobinson Looks like ports/cef/Cargo.lock didn't get updated? r=me after that is fixed and rebased.

**Comment by mrobinson** [comment]
@glennw I think this file has been removed after https://github.com/servo/servo/pull/14381. I don't think there is anything else do do beyond what ./mach update-cargo does. Given that, I think this is safe to land. Thanks for the review!

**Comment by glennw** [comment]
@mrobinson Ah great, r=me then when rebased.

**Comment by glennw** [comment]
@bors-servo retry
 * #14317 
 * #13776

**Comment by glennw** [comment]
@bors-servo retry
 * #14337

**Comment by mrobinson** [comment]
All tests passed, but looks like there was an issue with the filter-intermittents step.

```
Error running mach:

    ['filter-intermittents', 'wpt-errorsummary.log', '--log-intermittents', 'intermittents.log', '--log-filteredsummary', 'filtered-wpt-errorsummary.log', '--use-tracker']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

HTTPError: HTTP Error 403: Forbidden
```

I ran this locally and it worked, so I'll retry.

**Comment by mrobinson** [comment]
```
HTTPError: HTTP Error 403: Forbidden
```

Seems to be the same issue with filter-intermittents. I'm really not sure what is going on here.

**Pull request merged**
