### PR TITLE
Deduplicate the cocoa crate.

### PR DESCRIPTION
**Pull request by SimonSapin**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9509)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* #9063

**Comment by jdm** [comment]
@bors-servo: retry
* #7846

**Comment by SimonSapin** [comment]
Rebased, conflict solved automatically by kdiff3.

@bors-servo r=Ms2ger

(Previous failures were likely #9534 and #9533.)

**Comment by nox** [comment]
@bors-servo retry

Git snafu.

**Pull request merged**
