### PR TITLE
Reduce LayoutTaskData to the fields used for RPC.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8378)

### CODE REVIEW

**Comment by eefriedman** [comment]
Nice simplification... except that I'll have to redo large chunks of it to rebase #7524 on top of this.

The problem is that if you have an `&mut LayoutTask` floating around, it's impossible to borrow the Stylist... and SharedLayoutContext does precisely that.  The borrow checker just can't see it at the moment because SharedLayoutContext uses a raw pointer.


---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/layout/layout_task.rs, line 332 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8378#-K2T8qnZCaxeOKiim1AD)** ([raw file](https://github.com/servo/servo/blob/3770adab17bcca42be887c2604c7b5dabbd72b49/components/layout/layout_task.rs#L332)):</sup>
Accidentally left this in?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8378)

**Comment by Ms2ger** [comment]
I think anything that prevents us from using `&mut LayoutTask` is problematic; you see how much pointless locking I'm removing. I'll see if I can think of something for `Stylist`.


---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/layout/layout_task.rs, line 332 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8378#-K2T8qnZCaxeOKiim1AD)** ([raw file](https://github.com/servo/servo/blob/3770adab17bcca42be887c2604c7b5dabbd72b49/components/layout/layout_task.rs#L332)):</sup>
No, I believe it should be used in some places where it isn't: https://github.com/servo/servo/issues/8358


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8378)

**Comment by Ms2ger** [comment]
@eefriedman I dropped the stylist changes in this PR

**Comment by jdm** [comment]
Looking at the failure in the reftest analyzer, the screenshot is blank. Can you reproduce this failure?

**Comment by eefriedman** [comment]
The failed test is blank, white; given that the test has a green background, most likely reflow didn't finish before the screenshot was taken.  Probably just an intermittent failure which happened to show up here, but I'll look a little more.

**Pull request merged**
