### PR TITLE
Implement CORS preflight fetch

### LINKED ISSUE #10145: Implement CORS preflight fetch concept
Code: `components/net/fetch/methods.rs` (see `preflight_fetch` function)
Spec: https://fetch.spec.whatwg.org/#cors-preflight-fetch
Tests: need to be written in `tests/unit/net/fetch.rs` (`./mach test-unit -p net`)

The spec looks long, but the building blocks necessary should be present in that file already.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #10145.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10189)

### CODE REVIEW

**Comment by KiChjang** [comment]
Hold on... I'm not even sure how to test this since CORS preflight fetch doesn't modify the response in any way, it simply updates the cache. Perhaps I can test that from the server-side, there are 2 responses being received, one of which uses the the OPTIONS method?

**Comment by jdm** [comment]
That would be a way of testing that a CORS request isn't prevented, yes.

**Comment by KiChjang** [comment]
Test added.

**Comment by jdm** [comment]
The test... doesn't compile?

**Comment by KiChjang** [comment]
Darn, must be a merge conflict... lemme fix it up real quick.

**Comment by KiChjang** [comment]
Should be ok now.

**Comment by jdm** [comment]
It would be nice to get at least one additional test for some of the cases where the preflight request returns an error, but this is a great PR :)

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 7 files at r1, 1 of 6 files at r2, 1 of 1 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[components/net/fetch/methods.rs, line 947 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF4xNymCv6eZVUasiC1:-KF4xNynOemtYb_I71YZ:1720310977) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L947)):*
This doesn't look like it excludes simple headers.

---

*[components/net/fetch/methods.rs, line 960 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF4xehXF5RahRV7xjj4:-KF4xehXF5RahRV7xjj5:-677925830) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L960)):*
We should be using `request` here, not `preflight`.

---

*[components/net/fetch/methods.rs, line 961 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF4xmCTUVOiFA7dZ6Yv:-KF4xmCTUVOiFA7dZ6Yw:-1356991947) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L961)):*
nit: no need for the {} here, and && belongs on the previous line.

---

*[components/net/fetch/methods.rs, line 978 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF4yYu-bQvywyPIXPRO:-KF4yYu-bQvywyPIXPRP:686917618) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L978)):*
This header isn't mandatory, so we should only return this if the header is actually present.

---

*[components/net/fetch/methods.rs, line 983 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF4ygdklWMuuqDU_8T2:-KF4ygdklWMuuqDU_8T3:-144079508) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L983)):*
nit: && on previous line.

---

*[components/net/fetch/methods.rs, line 1006 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF4zy0sP1aJ0nNdYEHg:-KF4zy0sP1aJ0nNdYEHh:-1626417324) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L1006)):*
`in &methods`

---

*[components/net/fetch/methods.rs, line 1010 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF5-NqBdhjY-huvXg0k:-KF5-NqBdhjY-huvXg0l:1708807819) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L1010)):*
`!(request.credentials_mode != CredentialsMode::Include)`

---

*[components/net/fetch/methods.rs, line 1015 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF5-CdLeqgyLeOGnxPN:-KF5-CdLeqgyLeOGnxPO:1667090276) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L1015)):*
`in &header_names`

---

*[components/net/fetch/methods.rs, line 1019 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF5-b6Xmu3Mk_CvwRgU:-KF5-b6Xmu3Mk_CvwRgV:-1045866338) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L1019)):*
Same as previous.

---

*[components/net/fetch/methods.rs, line 1053 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF5-kq43JiPkLn3k1ca:-KF5-kq5adKddmvAv17V:-451601162) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L1053)):*
`there's no need`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10189#-:-KF50x6DiUoSLC2_glEB:-1056477633)*

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/net/fetch/methods.rs, line 1010 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10189#-KF5-NqBdhjY-huvXg0k:-KF67jcgurDyWC2Jnj6C:425074918) ([raw file](https://github.com/servo/servo/blob/331dd9947bcc91b7f3ec012f927da1661504a461/components/net/fetch/methods.rs#L1010)):*
Nevermind, the spec is just written in a silly way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10189)*

**Comment by KiChjang** [comment]
Comments addressed, and negative test added. I actually had to fix some other stuff, because the test wasn't actually hitting the `cors_preflight_fetch` fn before, but now it is.

**Comment by jdm** [comment]
Better! Still some troubling logic errors that it would be nice to write tests for :)
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/net/fetch/methods.rs, line 106 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFAFi0XaoAsM21nMBRm:-KFAFi0YXoeZ2zjZhHAq:-945672452) ([raw file](https://github.com/servo/servo/blob/fb5dae57b95dbd93d31e04e6a3ab9a0122f0db24/components/net/fetch/methods.rs#L106)):*
This doesn't look right to me - the spec does not set the CORS flag at all when invoking this algorithm.

---

*[components/net/fetch/methods.rs, line 994 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFBelLdWVFgu0EI5B2X:-KFBelLepA7Q_387Ycyr:-2018387843) ([raw file](https://github.com/servo/servo/blob/fb5dae57b95dbd93d31e04e6a3ab9a0122f0db24/components/net/fetch/methods.rs#L994)):*
This change seems wrong, since if Access-Controll-Allow-Methods contains `GET, POST, CHICKEN`, a CHICKEN request will be treated as an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10189#-:-KFBfhp5GcJgMSpQ8HIM:515874595)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/net/fetch/methods.rs, line 106 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFAFi0XaoAsM21nMBRm:-KFBkU-Pyv6MZQH_i8If:-772105887) ([raw file](https://github.com/servo/servo/blob/fb5dae57b95dbd93d31e04e6a3ab9a0122f0db24/components/net/fetch/methods.rs#L106)):*
I can't seem to otherwise force a CORS request. Setting use_cors_preflight flag doesn't necessarily guarantee that a CORS preflight fetch will be called.

---

*[components/net/fetch/methods.rs, line 156 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFBl1XbXkFw8jsbRBuO:-KFBl1XbXkFw8jsbRBuP:463325599) ([raw file](https://github.com/servo/servo/blob/fb5dae57b95dbd93d31e04e6a3ab9a0122f0db24/components/net/fetch/methods.rs#L156)):*
The reason is this if statement here, which will always return true since the origin of the request is the same as the URL origin.

---

*[components/net/fetch/methods.rs, line 994 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFBelLdWVFgu0EI5B2X:-KFBnrzuQxfeq7Xq_gxc:447196460) ([raw file](https://github.com/servo/servo/blob/fb5dae57b95dbd93d31e04e6a3ab9a0122f0db24/components/net/fetch/methods.rs#L994)):*
Yes, I had a hard time parsing the spec while I was reading the code, but using `.all()` was correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10189)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/net/fetch/methods.rs, line 156 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFBl1XbXkFw8jsbRBuO:-KFEaTHjZlp1Rk2qgxOE:2023557548) ([raw file](https://github.com/servo/servo/blob/fb5dae57b95dbd93d31e04e6a3ab9a0122f0db24/components/net/fetch/methods.rs#L156)):*
If only we had some way of changing the origin of the request... ;)

---

*[components/net/fetch/methods.rs, line 995 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFEadagWgIZXYB2tg60:-KFEadagWgIZXYB2tg61:620200199) ([raw file](https://github.com/servo/servo/blob/bf3824f6f1939640aaf75eb0f0cff6ffd422d843/components/net/fetch/methods.rs#L995)):*
nit: revert this indentation change.

---

*[tests/unit/net/fetch.rs, line 159 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFEai-a_qby3Q4d9bLe:-KFEai-a_qby3Q4d9bLf:-1106476427) ([raw file](https://github.com/servo/servo/blob/bf3824f6f1939640aaf75eb0f0cff6ffd422d843/tests/unit/net/fetch.rs#L159)):*
This should be a different origin.

---

*[tests/unit/net/fetch.rs, line 195 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFEaDFrPEj8dwd-5yCg:-KFEaDFsa5c3Lj0kLajL:-1725654763) ([raw file](https://github.com/servo/servo/blob/bf3824f6f1939640aaf75eb0f0cff6ffd422d843/tests/unit/net/fetch.rs#L195)):*
This should be an origin which is not same-origin to the destination to avoid the problems with invoking main_fetch.

---

*[tests/unit/net/fetch.rs, line 197 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10189#-KFE_l5hrcjB15HlK4Jw:-KFE_l5hrcjB15HlK4Jx:627521264) ([raw file](https://github.com/servo/servo/blob/bf3824f6f1939640aaf75eb0f0cff6ffd422d843/tests/unit/net/fetch.rs#L197)):*
This test should use a custom method instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10189#-:-KFEazk4dSYNr7phmMZj:1458266033)*

**Comment by KiChjang** [comment]
Comments addressed.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10189#-:-KFEzKWEbBI32JlFMevz:-1746383326)*

**Comment by KiChjang** [comment]
Thought I did a .`./mach cargo-update -p unicase`... apparently not.

**Comment by jdm** [comment]
@bors-servo: retry
* #8931

**Pull request merged**
