### PR TITLE
Put every Android build artefact in target/android/

### PR DESCRIPTION
**Pull request by nox**
This works around #20380 at the cost of rebuilding build-only dependencies twice,
once for normal builds and once for android builds.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22277)

### CODE REVIEW

**Comment by nox** [comment]
@asajeffrey Do you want me to put every ML artifact in `target/magicleap`?

**Comment by asajeffrey** [comment]
@nox sounds good. The places that aren't checked in CI are the ones to do with the nightly upload, in particular https://github.com/servo/servo/blob/c6f4dcce47433b2677375c69b269c30028bbb82b/python/servo/package_commands.py#L59-L61

**Comment by nox** [comment]
@asajeffrey I made a second commit for ML, feel free to look at it again.

**Review by jdm — APPROVED** [review]

**Pull request merged**
