### PR TITLE
Remove some redundant animation interpolation code

### PR DESCRIPTION
**Pull request by upsuper**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17157)

### CODE REVIEW

**Comment by upsuper** [comment]
Not sure who should review this... probably @hiikezoe or @birtles

**Comment by hiikezoe** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/properties/helpers/animated_properties.mako.rs, line 365 at r2](https://reviewable.io:443/reviews/servo/servo/17157#-Klpwj6moM5uM8X9kfaA:-KlpweNnsGcTiSeV83eZ:b-scc5gx) ([raw file](https://github.com/servo/servo/blob/61eb7e055f73cd3255e10de5c810fbcf4d5b2940/components/style/properties/helpers/animated_properties.mako.rs#L365)):*
>     % if not prop.is_animatable_with_computed_value:
>                             let value: longhands::${prop.ident}::computed_value::T = value.into();
>                         % endif
What I couldn't find initially was that the corresponding part of this change for stylo. Yeah, it's done in the first commit. Rust trait magic. Great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/17157)*

**Comment by hiikezoe** [comment]
Awesome! Thank you Xidorn!
r=me with a try for stylo.

**Comment by upsuper** [comment]
Let's see https://treeherder.mozilla.org/#/jobs?repo=try&revision=c3da17bd9bbd1606ec1c2ec5722ba05e712efdb7

**Comment by upsuper** [comment]
Stylo try run looks good so far. There are three different intermittents appear on Servo try run. Based on the content of the tests, I believe they are unrelated to changes here. FWIW:
* http://build.servo.org/builders/linux-rel-wpt/builds/4433/steps/shell__2/logs/filtered-wpt-errorsummary.log
* http://build.servo.org/builders/linux-rel-css/builds/4414/steps/shell__2/logs/filtered-css-errorsummary.log
* http://build.servo.org/builders/linux-rel-wpt/builds/4434/steps/shell__2/logs/filtered-wpt-errorsummary.log

**Pull request merged**
