### PR TITLE
support url() values in background-image, mask-image and list-style-image in stylo

### PR DESCRIPTION
**Pull request by heycam**
Corresponding Gecko bugs, where @Manishearth has given r+s:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1288302
- https://bugzilla.mozilla.org/show_bug.cgi?id=1310463

(Sorry for the large structs_{debug,release}.rs changes; I thought it was too much trouble to disentangle the useless changes from the legitimate ones.)

Holding off on landing this until the Gecko patches are reviewed and landed.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because I've tested the stylo functionality manually and we can rely on Gecko's existing tests going forward

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13786)

### CODE REVIEW

**Comment by emilio** [comment]
@ConnorGBrewster This is already reviewed:

> Holding off on landing this until the Gecko patches are reviewed and landed.

**Comment by ConnorGBrewster** [comment]
@emilio haha wooops! Missed that :)

**Comment by heycam** [comment]
@bors-servo retry
* infra

**Comment by heycam** [comment]
@bors-servo retry
* infra

**Comment by heycam** [comment]
@bors-servo retry
* infra

**Comment by heycam** [comment]
I guess I should have included the #13851 changes when I regenerated bindings in my rebase...

**Comment by heycam** [comment]
I will hold off landing this until the memory usage regressions in https://bugzilla.mozilla.org/show_bug.cgi?id=1311921 are sorted out.

**Comment by heycam** [comment]
I've got a Gecko patch up that solves the talos regressions, and rebased this patch queue on top of recent bindings-affecting changes, so I think this is good to land now.

@bors-servo r=Manishearth

**Comment by heycam** [comment]
Missed one commit of Xidorn's commit when regenerating the bindings.

@bors-servo r=Manishearth

**Pull request merged**
