### PR TITLE
removing mutHeapJs references

### LINKED ISSUE #15316: Remove MutHeapJSVal
https://github.com/servo/rust-mozjs/pull/328 makes it unnecessary. We should be able to replace all users with `Heap<JSVal>`.

### PR DESCRIPTION
**Pull request by sendilkumarn**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15316

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15833)

### CODE REVIEW

**Comment by KiChjang** [comment]
I'm pretty sure this is still the wrong fix. The issue specifically asked for removing MutHeapJSVal and replace it with Heap<JSVal> , and not renaming MutHeapJSVal to HeapJSVal.

**Comment by nox** [comment]
Please squash the 2 commits together and I'll r+ it.

**Comment by sendilkumarn** [comment]
@nox done 👍

**Pull request merged**
