### PR TITLE
Don't call `layout_font_group_for_style()` to fetch the font metrics for a fragment if there's a more direct way to get to them.

### PR DESCRIPTION
**Pull request by pcwalton**
31% layout time improvement on
https://drafts.csswg.org/css-backgrounds-3/.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9196)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo retry
* Build was interrupted

**Comment by Ms2ger** [comment]
```
  ▶ FAIL [expected PASS] /_mozilla/css/line_breaking_whitespace_collapse_a.html
  └   → /_mozilla/css/line_breaking_whitespace_collapse_a.html 117395f5c755abaebbcdef86ebfef696f64b8137
/_mozilla/css/line_breaking_whitespace_collapse_ref.html c3bc177ff55f7250853bfd581426840809dcd247
Testing 117395f5c755abaebbcdef86ebfef696f64b8137 == c3bc177ff55f7250853bfd581426840809dcd247
```

**Comment by jdm** [comment]
@pcwalton This had a test failure. Are you planning to investigate or should we close the PR?

**Comment by pcwalton** [comment]
I'll look at it.

**Comment by jdm** [comment]
Go ahead and reopen this whenever you take the time to look into it. Filed #9954 so we have a record of it.

**Pull request closed without merging**
