### PR TITLE
Match forwarded events as atoms, fixes #7495

### LINKED ISSUE #7495: Forwarded events should be referenced as atoms in HTMLBodyElement::attribute_mutated()
The attribute name should be matched against atoms, not against strings like the ones in FORWARDED_EVENTS. Follow-up of #7452.

### PR DESCRIPTION
**Pull request by aidanhs**
Hopefully I understood the issue correctly...

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7623)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r+

@aidanhs Thanks for your contribution.

**Comment by nox** [comment]
```
Unexpected Results
==================

/css21_dev/html4/font-family-013.htm
------------------------------------
FAIL [Parent]
/css21_dev/html4/fonts-013.htm
------------------------------
FAIL [Parent]
```

**Comment by nox** [comment]
Probably an intermittent failure, @jdm is looking into it.

**Comment by jdm** [comment]
@bors-servo: retry
* #7625

**Comment by jdm** [comment]
@bors-servo: retry
* #7625

**Comment by SimonSapin** [comment]
`font-family-013.htm` and `fonts-013.htm` were failing until we installed some Microsoft fonts on the builders. Could this have regressed? CC @larsbergstrom

**Comment by aidanhs** [comment]
Worth a retry? I note some other PRs have been merged successfully.

**Comment by nox** [comment]
@bors-servo retry

@aidanhs Yes.

**Comment by aidanhs** [comment]
```
 scheduler: IFRAMEs added with DOM
----------------------------------
Expected PASS, got FAIL
assert_array_equals: lengths differ, expected 5 got 3

assert_array_equals: lengths differ, expected 5 got 3
test@http://localhost:8000/old-tests/submission/Opera/script_scheduling/039.html:5:1
Test.prototype.step@http://localhost:8000/resources/testharness.js:1379:20
Test.prototype.step_func/<@http://localhost:8000/resources/testharness.js:1403:1
[...]
Unexpected results: 22 (FAIL: 1, PASS: 1, TIMEOUT: 20)
[...]
/old-tests/submission/Opera/script_scheduling/039.html
------------------------------------------------------
FAIL  scheduler: IFRAMEs added with DOM
```

I note that test did:
```
        onload = t.step_func(function() {
                setTimeout(t.step_func(test), 200);
        });
```

Buildbot running too slowly so popups weren't created before 200ms?

**Comment by aidanhs** [comment]
Ready for retry following https://github.com/servo/saltfs/pull/116?

**Comment by jdm** [comment]
This is #7625 and #7437. We'll get this sorted out.

**Pull request merged**
