### PR TITLE
Reduce the amount of dom code used outside the script crate.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11656)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r+

<details><summary><i>Previously, highfive wrote…</i></summary>
> warning **Warning** warning
> 
> * These commits modify **unsafe code**. Please review it carefully!
</details>


---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 28 of 28 files at r5, 6 of 6 files at r6, 5 of 5 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11656#-:-KJeqg2zhVkP32xujNOs:1236647940)*

**Comment by jdm** [comment]
Should we add a test-tidy check to prevent any non layout_interface script dependencies being added to layout?

**Comment by KiChjang** [comment]
@bors-servo retry
* #11613

**Pull request merged**
