### PR TITLE
Stylo - Bug 1365674: Simulate compute value failure for tests

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

https://bugzilla.mozilla.org/show_bug.cgi?id=1365674

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17093)

### CODE REVIEW

**Comment by jdm** [comment]
```
   Compiling geckoservo v0.0.1 (file:///home/servo/buildbot/slave/linux-dev/build/ports/geckolib)
error: no field `mSimulateComputeValuesFailure` on type `&style::gecko_bindings::structs::PropertyValuePair`
    --> glue.rs:2431:43
     |
2431 |     id.as_shorthand().is_ok() && property.mSimulateComputeValuesFailure
     |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by hiikezoe** [comment]
@ferjm you need to update generated binding files in components/style/gecko/generated/.
You can get the files from try builds. target.stylo-bindings.zip is the file.

**Comment by ferjm** [comment]
@bors-servo r=hiikezoe

- Updated bindings

**Comment by jdm** [comment]
@bors-servo: retry
* https://github.com/servo/saltfs/issues/684

**Pull request merged**
