### PR TITLE
Implement support for WebDriver send keys command.

### PR DESCRIPTION
**Pull request by jgraham**
Supports sending keys to an element. The specification here is still
rather unfinished so the error handling and so on in this code will
need iteration as it becomes clearer what the expected behaviour is.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8151)

### CODE REVIEW

**Comment by frewsxcv** [comment]
This fails tidy

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/webdriver_server/keys.rs, line 3 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8151#-K28u3nuEXzH1F1QF721)** ([raw file](https://github.com/servo/servo/blob/08d94a326a4daa0e56dc829f512f6a3439ffa669/components/webdriver_server/keys.rs#L3)):</sup>
Could we document the return value here?


---

<sup>**[components/webdriver_server/keys.rs, line 106 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8151#-K28u725YzKjvybaikwH)** ([raw file](https://github.com/servo/servo/blob/08d94a326a4daa0e56dc829f512f6a3439ffa669/components/webdriver_server/keys.rs#L106)):</sup>
I'm not clear on what this comment means.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8151)

**Comment by jdm** [comment]
@bors-servo: delegate+
-S-awaiting-review +S-needs-squash 


---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8151)

**Comment by jdm** [comment]
@bors-servo: retry
* #8502

**Pull request merged**
