### PR TITLE
Link OpenSSL statically on Unix

### LINKED ISSUE #20783: Link OpenSSL statically in Linux nightly builds
Our downloadable nightly builds don't work on all Linux distros because they are dynamically linked to a specific version of OpenSSL that is not available everywhere.  We might be able to fix this by setting the `OPENSSL_STATIC` environment variable at build time on the nightly builders:

https://github.com/sfackler/rust-openssl/blob/9e5dcb03f2e429e9a8bda2ade64b6d75058907b8/openssl-sys/build.rs#L506

### PR DESCRIPTION
**Pull request by Darkspirit**
build.rs was removed because [Windows](https://github.com/servo/openssl-windows-build) uses OpenSSL 1.1.1 through https://github.com/servo/servo/blob/425328a64f37a795ce36516e495c386be27a6100/python/servo/packages.py#L11. Upstream openssl-src doesn't support UWP yet.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #20783 for #26114

### CODE REVIEW

**Comment by Darkspirit** [comment]
Before:
`$ ./mach build --dev` with libssl-dev installed, wants to load libssl.so.1.1 and libcrypto.so.1.1:
```
$ ldd target/debug/servo
        linux-vdso.so.1 (0x00007ffc8a396000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb6fdb15000)
        libgstgl-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstgl-1.0.so.0 (0x00007fb6fda9f000)
        libgstvideo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007fb6fd9f3000)
        libgstbase-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007fb6fd977000)
        libgstreamer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007fb6fd834000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fb6fd7d5000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fb6fd6ac000)
        libgstwebrtc-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstwebrtc-1.0.so.0 (0x00007fb6fd6a0000)
        libgstsdp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstsdp-1.0.so.0 (0x00007fb6fd687000)
        libgstplayer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstplayer-1.0.so.0 (0x00007fb6fd668000)
        libgstaudio-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0 (0x00007fb6fd5ed000)
        libgstapp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0 (0x00007fb6fd5dc000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb6fd40d000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb6fd3f0000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fb6fd35e000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fb6fd073000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb6fd052000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fb6fcf4d000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb6fce09000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fb6fcdc3000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fb6fcd04000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fb6fccb1000)
        libunwind-x86_64.so.8 => /usr/lib/x86_64-linux-gnu/libunwind-x86_64.so.8 (0x00007fb6fcc8f000)
        libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007fb6fcc72000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb6fcc6b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb6fcc60000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb6fca9d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb70a88e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb6fc958000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb6fc754000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fb6fc54e000)
        libgstallocators-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstallocators-1.0.so.0 (0x00007fb6fc545000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fb6fc53f000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fb6fc4b8000)
        libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fb6fc4b3000)
        libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fb6fc4ae000)
        libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fb6fc49d000)
        libEGL.so.1 => /usr/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007fb6fc486000)
        libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fb6fc472000)
        libgbm.so.1 => /usr/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007fb6fc461000)
        libgudev-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgudev-1.0.so.0 (0x00007fb6fc454000)
        liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007fb6fc3d2000)
        libffi.so.7 => /usr/lib/x86_64-linux-gnu/libffi.so.7 (0x00007fb6fc3c4000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fb6fc350000)
        libgstrtp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstrtp-1.0.so.0 (0x00007fb6fc32b000)
        libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fb6fc153000)
        libgsttag-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so.0 (0x00007fb6fc116000)
        libgstpbutils-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0 (0x00007fb6fc0da000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb6fc0be000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fb6fc092000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fb6fc065000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fb6fc05c000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fb6fc023000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fb6fbf79000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb6fbf50000)
        libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fb6fbf36000)
        libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fb6fbe7e000)
        libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fb6fbe4a000)
        libwayland-server.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007fb6fbe31000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fb6fbe06000)
        libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fb6fbda5000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fb6fbd7a000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fb6fbd62000)
        liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fb6fbd3e000)
        libgcrypt.so.20 => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fb6fbc21000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fb6fbbcb000)
        libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fb6fbb3b000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fb6fbb18000)
```
        
        
`$ ./mach build --dev` without having libssl-dev installed, fails to build:
```
error: failed to run custom build command for `openssl-sys v0.9.54`

Caused by:
  process didn't exit successfully: `/home/darkspirit/github/servo/target/debug/build/openssl-sys-55d8f96d9784ee2e/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-unknown-linux-gnu
$TARGET = x86_64-unknown-linux-gnu
openssl-sys = 0.9.54

', /home/darkspirit/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.54/build/find_normal.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...

```

-----

After:
`$ ./mach build --dev` without having libssl-dev installed, but using "vendored" openssl build flag, doesn't expect libssl.so.1.1 and libcrypto.so.1.1:

```
$ ldd target/debug/servo
        linux-vdso.so.1 (0x00007ffd7e3e6000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa32fe26000)
        libgstgl-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstgl-1.0.so.0 (0x00007fa32fdb0000)
        libgstvideo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007fa32fd04000)
        libgstbase-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007fa32fc88000)
        libgstreamer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007fa32fb45000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fa32fae6000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fa32f9bd000)
        libgstwebrtc-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstwebrtc-1.0.so.0 (0x00007fa32f9b1000)
        libgstsdp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstsdp-1.0.so.0 (0x00007fa32f998000)
        libgstplayer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstplayer-1.0.so.0 (0x00007fa32f979000)
        libgstaudio-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0 (0x00007fa32f8fe000)
        libgstapp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0 (0x00007fa32f8ed000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa32f71e000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa32f701000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa32f6e0000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fa32f5db000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa32f499000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fa32f453000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fa32f392000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fa32f33f000)
        libunwind-x86_64.so.8 => /usr/lib/x86_64-linux-gnu/libunwind-x86_64.so.8 (0x00007fa32f31d000)
        libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007fa32f300000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa32f2fb000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa32f2f0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa32f12b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa33cdee000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa32efe6000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa32ede2000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa32ebdc000)
        libgstallocators-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstallocators-1.0.so.0 (0x00007fa32ebd5000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fa32ebcf000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fa32eb46000)
        libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fa32eb41000)
        libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fa32eb3c000)
        libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fa32eb2b000)
        libEGL.so.1 => /usr/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007fa32eb16000)
        libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fa32eb02000)
        libgbm.so.1 => /usr/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007fa32eaef000)
        libgudev-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgudev-1.0.so.0 (0x00007fa32eae2000)
        liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007fa32ea60000)
        libffi.so.7 => /usr/lib/x86_64-linux-gnu/libffi.so.7 (0x00007fa32ea54000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fa32e9e0000)
        libgstrtp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstrtp-1.0.so.0 (0x00007fa32e9b9000)
        libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fa32e7e1000)
        libgsttag-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so.0 (0x00007fa32e7a4000)
        libgstpbutils-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0 (0x00007fa32e768000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa32e74e000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fa32e720000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fa32e6f3000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fa32e6ea000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fa32e6b1000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fa32e609000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fa32e5e0000)
        libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fa32e5c4000)
        libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fa32e50c000)
        libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fa32e4d8000)
        libwayland-server.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007fa32e4c1000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fa32e496000)
        libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fa32e433000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fa32e408000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa32e3f0000)
        liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fa32e3ce000)
        libgcrypt.so.20 => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fa32e2b1000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fa32e259000)
        libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fa32e1c9000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fa32e1a6000)
```

**Comment by SimonSapin** [comment]
Diff looks ok, r? @jdm on the approach

I feel that if we do this it would be good have something in place for updating `Cargo.lock` in this repository for https://crates.io/crates/openssl-src soon after each upstream OpenSSL release. This could be one or a few team members who subscribe to release announcements, or something more sophisticated that automatically files an issue for each release.

**Comment by Darkspirit** [comment]
Yes, it's good to start taking care about immediate OpenSSL updates. Maybe it works for Windows as well. [UWP](https://github.com/servo/openssl-windows-build) support should be upstreamed to openssl-src.
It might be good to have Dependabot #26118 and cargo audit #15989.

**Comment by jdm** [comment]
@bors-servo r+
This seems reasonable.

**Comment by SimonSapin** [comment]
@jdm 

* It looks like CI is failing because https://build.servo.org/intermittent-tracker is returning HTTP 500 errors
* What do you think we should do about tracking OpenSSL updates?

**Comment by jdm** [comment]
I'm not particularly worried about the OpenSSL updates as long as we're not trying to ship products on targets that rely on them.

**Comment by Darkspirit** [comment]
Mozilla is listed as customer of Github's free [Dependabot](https://github.com/marketplace/dependabot-preview). #26118

Allmost all WPT blocks have one or two unexpected results (css, webgl, content-type, resource-timing, webaudio).

Windows unexpectedly compiles with "openssl-src v111.8.1+1.1.1f" and fails because of missing UWP support; I assume because it's generally listed as openssl-sys dependency in Cargo.lock.

Until UWP support is upstreamed, we could override openssl-src with Servo's existing [fork](https://github.com/servo/openssl-src-rs/tree/servo) and use "vendored" everywhere.
openssl-src = { git = "https://github.com/servo/openssl-src-rs.git", branch = "[servo](https://github.com/servo/openssl-src-rs/tree/servo)" }

**Comment by atouchet** [comment]
openssl 0.10.29 is now out.

**Comment by Darkspirit** [comment]
- Original problem: We can't define different dependency feature sets per target, if Cargo.lock should stay untouched.
- Discarded idea: Cargo hits a libgit2 bug when using openssl-src as git dependency. Openssl-src must be used as crates.io package or be checked out manually (git clone https://github.com/servo/openssl-src-rs; cd openssl-src-rs; git checkout servo; git submodule update --init --recursive).
  ```
  $ ./mach build -d
      Updating git repository `https://github.com/servo/openssl-src-rs`
  error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`
  
  Caused by:
    failed to load source for dependency `openssl-src`
  
  Caused by:
    Unable to update https://github.com/servo/openssl-src-rs?branch=servo
  
  Caused by:
    failed to update submodule `openssl`
  
  Caused by:
    failed to update submodule `boringssl`
  
  Caused by:
    failed to fetch submodule `boringssl` from https://boringssl.googlesource.com/boringssl
  
  Caused by:
    error reading from the zlib stream; class=Zlib (5)
  Build FAILED in 0:01:07
  ```
- Solution: Since today's openssl-sys 0.9.55, `OPENSSL_NO_VENDOR=1` can be used to override the "verdored" feature flag on Windows.
- Outcast: With `choco install activeperl` it already works as shared lib on non-UWP Windows. Static linking needs at least admin rights until openssl-src sets [`--openssldir`](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1f/NOTES.WIN#L68-L84) to `$prefix/SSL`.

**Comment by Darkspirit** [comment]
I have confirmed that openssl[-sys] with feature flag "vendored" does not compile OpenSSL on Win10 because [`OPENSSL_NO_VENDOR=1`](https://github.com/sfackler/rust-openssl/blob/b027f1603189919d5f63c6aff483243aaa188568/openssl-sys/build/main.rs#L47-L53) env var is set by this PR. Windows keeps the same code path as before.
r?@jdm

**Comment by mrobinson** [comment]
https://github.com/servo/servo/commit/bce7622cde4cd10f6b3edf852d97ae9a540a0076 makes this obsolete now.

**Pull request closed without merging**
