### PR TITLE
Store unset keyword as specified value

### PR DESCRIPTION
**Pull request by upsuper**
`unset` keyword value should *not* be converted to something else during parsing. It is a specified-value time value, which should be preserved until computation.

WIP patch for seeing what tests would be broken and / or if there is necessary to add any new test.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14640)

### CODE REVIEW

**Comment by upsuper** [comment]
FWIW this fixes 700+ failures in Gecko's test_initial_storage test.

**Comment by emilio** [comment]
r=me when it passes tests with a link to https://drafts.csswg.org/css-values/#common-keywords, noting that "acts as" doesn't imply we can just convert it to the other value because of user-visible effects like serialization.

Good find! :)

**Comment by emilio** [comment]
Oh, and please add a test if none exists (though I'd be surprised)

**Comment by upsuper** [comment]
> Oh, and please add a test if none exists (though I'd be surprised)

I'd be surprised too. That's why I just submitted a WIP and trigger a try :)

**Comment by upsuper** [comment]
I'm surprised... OK, I'll add some tests.

**Comment by upsuper** [comment]
I have no idea what kind of test should be added for this change. Any suggestion?

**Comment by emilio** [comment]
A longhand serializing to `unset` or any of the failing tests in gecko?

**Comment by upsuper** [comment]
Gecko's failing test is part of the large mochitest, so not reasonable to be added to servo...

Is there something like script test (or mochitest in gecko) in servo? Probably outside wpt?

In theory this should be a script test in csswg test repo... But do we run script test there? How can we add new test from Servo repo?

cc @Manishearth if you have any suggestion.

**Comment by Ms2ger** [comment]
Just put it in wpt.

**Comment by upsuper** [comment]
@Ms2ger Create a new directory called `css-values`?

**Comment by Ms2ger** [comment]
Fine by me

**Comment by emilio** [comment]
Sorry for how much this took to get merged btw :/

**Comment by upsuper** [comment]
No worries :)

**Pull request merged**
