### PR TITLE
Update to selectors 0.8.2 (generic over atoms)

### PR DESCRIPTION
**Pull request by SimonSapin**
This removes the `[replace]` override in geckolib and therefore unblocks https://github.com/servo/servo/pull/12391.

This includes the `gecko_string_cache` redesign discussed in https://github.com/servo/servo/pull/12548.

r? @bholley 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12548 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require new tests because refactor

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12571)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bholley, you said in #12548 that instead of `pub struct WeakAtom(nsIAtom);` you’d rather use `nsIAtom` directly with its fields made private, and that @Manishearth is working on this in bindgen.

In https://github.com/servo/rust-bindgen/pull/20, it looks like these fields systematically have unsafe accessors, which I don’t think is desirable here. `WeakAtom` (or renamed or equivalent) should be opaque other than for methods that `gecko_string_cache` implements for it. (By the way, `nsIAtom` is from another crate so `gecko_string_cache` couldn’t implement inherent methods for it.)

**Comment by Manishearth** [comment]
That bindgen PR isn't complete. I only needed unsafe fields,  but I'll be adding ways for making it fully private without accessors too.

**Comment by bholley** [comment]
Looks good modulo those issues, but please test the final result with a stylo build and make sure everything works as expected.

---

Reviewed 4 of 10 files at r1, 23 of 26 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ports/geckolib/Cargo.lock, line 251 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12571#-KNsicZCH1gdaiUb96L2:-KNsicZCH1gdaiUb96L3:-1485168316) ([raw file](https://github.com/servo/servo/blob/24d621145ca9e689b442c6f6afb3a247ab40fc5f/ports/geckolib/Cargo.lock#L251)):*
> ```
> 
> [[package]]
> name = "phf_generator"
> ```

Hm, why do we need to pull in the phf stuff now?

---

*[ports/geckolib/string_cache/lib.rs, line 234 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12571#-KNsmW2seFvwuPlzn8Wn:-KNsmW2tdc1N9xWefThb:430236816) ([raw file](https://github.com/servo/servo/blob/24d621145ca9e689b442c6f6afb3a247ab40fc5f/ports/geckolib/string_cache/lib.rs#L234)):*
> ```Rust
>         other == self
>     }
> }
> ```

Hm, I've been explicitly avoiding implementing such a thing because it's really easily to accidentally use these slow string comparisons. I would prefer this to not work (or at least have some kind of explicit call) for gecko atoms so that we catch cases that aren't atomized. Why do we need this, and .chars()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12571#-:-KNsnI6Oce_1FUJWE-Xu:-1147751461)*

**Comment by SimonSapin** [comment]
Rebased. Looks ok in a gecko/stylo build.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ports/geckolib/Cargo.lock, line 251 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12571#-KNsicZCH1gdaiUb96L2:-KOFaqBVKZLdlz_m3_jp:-1556997602) ([raw file](https://github.com/servo/servo/blob/24d621145ca9e689b442c6f6afb3a247ab40fc5f/ports/geckolib/Cargo.lock#L251)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Hm, why do we need to pull in the phf stuff now?
</details>
The style crate has an optional dependency on string-cache (not gecko-string-cache) which depends on phf. That dependency is not enabled by geckolib, but Cargo still keeps the whole graph in `Cargo.lock`

---

*[ports/geckolib/string_cache/lib.rs, line 234 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12571#-KNsmW2seFvwuPlzn8Wn:-KOFxuJ0TKPW8pdx7IOi:-108780149) ([raw file](https://github.com/servo/servo/blob/24d621145ca9e689b442c6f6afb3a247ab40fc5f/ports/geckolib/string_cache/lib.rs#L234)):*
<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> Hm, I've been explicitly avoiding implementing such a thing because it's really easily to accidentally use these slow string comparisons. I would prefer this to not work (or at least have some kind of explicit call) for gecko atoms so that we catch cases that aren't atomized. Why do we need this, and .chars()?
</details>
I don’t remember exactly why I added these impls, they don’t seem to be needed. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12571#-:-KOFy61N_zpFV8pWEGEB:853116922)*

**Comment by emilio** [comment]
@SimonSapin: Sorry for the bitrot :/

This is just awaiting for review from @bholley right?

**Comment by bholley** [comment]
I don't need to look again.r=me if the comments were addressed

**Comment by SimonSapin** [comment]
Picking `/css21_dev/html4/absolute-replaced-height-017.htm` for example, it looks like the problem is in the rendering of the reference where a `div` selector applies correctly, but `div + div` does not.

**Comment by SimonSapin** [comment]
Latest finding: adding IDs to any of the two `<div>`s hides the issue. (The `div + div` rule now correctly applies to the second div.) I suspect style sharing.

Changing the `selectors` crate like below seems to fix the issue. What I still don’t understand is how this PR, which changes APIs but shouldn’t introduce any functional change, exposed this existing bug.

```diff
--- a/src/matching.rs
+++ b/src/matching.rs
@@ -488,14 +490,15 @@ fn matches_compound_selector_internal<E>(selector: &CompoundSelector<E::Impl>,
             let (siblings, candidate_not_found) = match combinator {
                 Combinator::Child => (false, SelectorMatchingResult::NotMatchedGlobally),
                 Combinator::Descendant => (false, SelectorMatchingResult::NotMatchedGlobally),
                 Combinator::NextSibling => (true, SelectorMatchingResult::NotMatchedAndRestartFromClosestDescendant),
                 Combinator::LaterSibling => (true, SelectorMatchingResult::NotMatchedAndRestartFromClosestDescendant),
             };
             let mut next_element = if siblings {
+                *shareable = false;
                 element.prev_sibling_element()
             } else {
                 element.parent_element()
             };
             loop {
                 let element = match next_element {
                     None => return candidate_not_found,
```

**Comment by SimonSapin** [comment]
Amended to include https://github.com/servo/rust-selectors/issues/94

@bors-servo r=bholley

**Comment by SimonSapin** [comment]
With https://github.com/servo/rust-selectors/pull/95

@bors-servo r=bholley

**Pull request merged**
