### PR TITLE
Replace usage of deprecated min_by with min_by_key

### PR DESCRIPTION
**Pull request by alex**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8928)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8928)*

**Comment by frewsxcv** [comment]
Duplicate of https://github.com/servo/servo/pull/8923. Sorry!

**Comment by alex** [comment]
Doh! Not sure how I missed that.

**Pull request closed without merging**
