### PR TITLE
[WIP] PointerEvent

### PR DESCRIPTION
**Pull request by dowoncha**
- [X]  added pointerevent webidl
- [X]  added pointerevent struct
- [X]  Added event handler macros
- [ ]   Implement the pointerevents
- [ ]  Propogate pointer events from glutin/constellation. Not sure how to design this
- [ ]   Extensions to the Element Interface 
- [X]  Extensions to the Global Event Handlers
- [X]  Extensions to the Navigator Interface 

Small Changes:
Added `PointerWindowEventClass` to `WindowEvent`
Made `MouseEvent.new_inherited()` public

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes (wpt)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16273)

### CODE REVIEW

**Comment by cbrewster** [comment]
@dowoncha do you plan to continue work on this? If you have any questions let me know, or feel free to drop by on IRC #rust on Mozilla.

**Comment by jdm** [comment]
Is there anything preventing following the same design as touch events for https://github.com/servo/servo/pull/16273/files#diff-f8d10559c852d773193e1ad337448532R837 ?

**Comment by dowoncha** [comment]
I will be fixing the conflicts tomorrow. @jdm I'm unsure what you mean

**Comment by jdm** [comment]
@dawincha As far as I understand, the pointer events are first received by the code in the compositor, like the touch events, keyboard input, etc. Why can't you use those as a model for how to make the pointer events reach the code in script/?

**Comment by cbrewster** [comment]
@dowoncha are you still working on this?

**Comment by dowoncha** [comment]
@cbrewster no i'm not

**Comment by cbrewster** [comment]
@dowoncha I am going to close this for now then, feel free to reopen if you pick this up again.

**Pull request closed without merging**
