### PR TITLE
Daily batch of drive-by WebGL improvements, wholesome and gluten-free

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20565)

### CODE REVIEW

**Review by emilio — APPROVED** [review]

**Comment by CYBAI** [comment]
```
{"status": "FAIL", "group": "default", "message": "assert_true: getError expected: NO_ERROR. Was INVALID_ENUM : bind draw framebuffer to default (null) framebuffer. expected true got false", "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_mozilla/webgl/conformance-2.0.0/js/js-test-pre.js:128:11\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1501:20\ntest@http://web-platform.test:8000/resources/testharness.js:511:9\nreportTestResultsToHarness@http://web-platform.test:8000/_mozilla/webgl/conformance-2.0.0/js/js-test-pre.js:127:9\ntestFailed@http://web-platform.test:8000/_mozilla/webgl/conformance-2.0.0/js/js-test-pre.js:254:5\nglErrorShouldBeImpl@http://web-platform.test:8000/_mozilla/webgl/conformance-2.0.0/js/webgl-test-utils.js:1615:5\nglErrorShouldBe@http://web-platform.test:8000/_mozilla/webgl/conformance-2.0.0/js/webgl-test-utils.js:1589:10\ntestFramebufferRenderbuffer@http://web-platform.test:8000/_mozilla/webgl/conformance-2.0.0/conformance2/renderbuffers/framebuffer-test.html:294:3\n@http://web-platform.test:8000/_mozilla/webgl/conformance-2.0.0/conformance2/renderbuffers/framebuffer-test.html:302:1\n", "subtest": "WebGL test #56: getError expected: NO_ERROR. Was INVALID_ENUM : bind draw framebuffer to default (null) framebuffer.", "test": "/_mozilla/webgl/conformance-2.0.0/conformance2/renderbuffers/framebuffer-test.html", "line": 151541, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: getError expected: INVALID_OPERATION. Was NO_ERROR :  colorBufferFormat: RGB565 internalFormat: RGBA target: TEXTURE_2D border: 0 expected true got false", "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:88:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1501:20\ntest@http://web-platform.test:8000/resources/testharness.js:511:9\nreportTestResultsToHarness@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:87:7\ntestFailed@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:159:5\nglErrorShouldBe@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1406:5\ntestCopyTexImage2D@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:124:5\n@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:338:5\n", "subtest": "WebGL test #34: getError expected: INVALID_OPERATION. Was NO_ERROR :  colorBufferFormat: RGB565 internalFormat: RGBA target: TEXTURE_2D border: 0", "test": "/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html", "line": 213441, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: getError expected: NO_ERROR. Was INVALID_OPERATION :  colorBufferFormat: RGB565 internalFormat: RGB target: TEXTURE_2D border: 0 expected true got false", "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:88:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1501:20\ntest@http://web-platform.test:8000/resources/testharness.js:511:9\nreportTestResultsToHarness@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:87:7\ntestFailed@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:159:5\nglErrorShouldBe@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1406:5\ntestCopyTexImage2D@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:124:5\n@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:338:5\n", "subtest": "WebGL test #37: getError expected: NO_ERROR. Was INVALID_OPERATION :  colorBufferFormat: RGB565 internalFormat: RGB target: TEXTURE_2D border: 0", "test": "/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html", "line": 213444, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: getError expected: INVALID_OPERATION. Was NO_ERROR :  colorBufferFormat: RGB565 internalFormat: RGBA target: TEXTURE_2D expected true got false", "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:88:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1501:20\ntest@http://web-platform.test:8000/resources/testharness.js:511:9\nreportTestResultsToHarness@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:87:7\ntestFailed@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:159:5\nglErrorShouldBe@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1406:5\ntestCopyTexSubImage2D@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:152:5\n@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:354:5\n", "subtest": "WebGL test #45: getError expected: INVALID_OPERATION. Was NO_ERROR :  colorBufferFormat: RGB565 internalFormat: RGBA target: TEXTURE_2D", "test": "/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html", "line": 213452, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: getError expected: INVALID_OPERATION. Was NO_ERROR :  colorBufferFormat: RGB internalFormat: RGBA expected true got false", "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:88:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1501:20\ntest@http://web-platform.test:8000/resources/testharness.js:511:9\nreportTestResultsToHarness@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:87:7\ntestFailed@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:159:5\nglErrorShouldBe@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1406:5\ntestCopyFromInternalFBO@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:187:5\n@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:378:5\n", "subtest": "WebGL test #53: getError expected: INVALID_OPERATION. Was NO_ERROR :  colorBufferFormat: RGB internalFormat: RGBA", "test": "/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html", "line": 213460, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: getError expected: INVALID_OPERATION. Was NO_ERROR :  colorBufferFormat: RGB internalFormat: RGBA expected true got false", "stack": "reportTestResultsToHarness/<@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:88:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1501:20\ntest@http://web-platform.test:8000/resources/testharness.js:511:9\nreportTestResultsToHarness@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:87:7\ntestFailed@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/resources/js-test-pre.js:159:5\nglErrorShouldBe@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/resources/webgl-test-utils.js:1406:5\ntestCopyFromInternalFBO@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:187:5\n@http://web-platform.test:8000/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html:378:5\n", "subtest": "WebGL test #61: getError expected: INVALID_OPERATION. Was NO_ERROR :  colorBufferFormat: RGB internalFormat: RGBA", "test": "/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html", "line": 213468, "action": "test_result", "expected": "PASS"}
{"status": "OK", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/_mozilla/webgl/conformance-1.0.3/conformance/textures/tex-input-validation.html", "line": 213470, "action": "test_result", "expected": "CRASH"}
```

**Comment by nox** [comment]
Errors are better than crashes.

@bors-servo r=emilio

**Pull request merged**
