### PR TITLE
[WIP] Optional compositor

### PR DESCRIPTION
**Pull request by paulrouget**
Early work on some refactoring of how the compositor works. Mostly to document my progress.

We want to be able to create the compositor after creating the constellation. We also want to be able to shutdown the compositor without shutting down the constellation. This will partially address #13993 and #19679.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21808)

### CODE REVIEW

**Comment by paulrouget** [comment]
This is also necessary for Android Component where view and session are supposed to be separated.

**Comment by asajeffrey** [comment]
Is this still active?

**Comment by paulrouget** [comment]
This is still something I’m planning to work on.

**Comment by delan** [comment]
Hi @paulrouget! @atbrakhi and I are also interested in pursuing this. Would you recommend we use your patch as a starting point? What were the most important problems to watch out for?

**Comment by paulrouget** [comment]
> Hi @paulrouget! @atbrakhi and I are also interested in pursuing this. Would you recommend we use your patch as a starting point? What were the most important problems to watch out for?

Oh that was a while ago. iirc, step one was to make the constellation run without a compositor (no window and no gl context), then find a way to make attach a compositor, then make it possible to have multiple compositor.

I don't remember well, but there was some components that the constellation needed but that were relying on the compositor (something to do with the font iirc).

Don't re-use the patch. I have a more "recent" branch here: https://github.com/servo/servo/compare/master...paulrouget:servo:optional-compositor-v2 … but if I were you I'd start from scratch.

**Comment by mrobinson** [comment]
I think we can close this for now given the recommendation from @paulrouget about starting from scratch. Feel free to reopn if I'm mistaken though.

**Pull request closed without merging**
