### PR TITLE
Update Rust to 1.11.0-nightly (ad7fe6521 2016-06-23)

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11871)

### CODE REVIEW

**Comment by nox** [comment]
@jdm This needs https://github.com/servo/webrender/pull/296, I thought it had landed already but no.

**Comment by ConnorGBrewster** [comment]
```
BUILD FAILED
/home/servo/android/sdk/current/tools/ant/build.xml:483: SDK does not have any Build Tools installed.
```

**Comment by larsbergstrom** [comment]
@bors-servo retry
- infra

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11859

**Comment by nox** [comment]
This now includes https://github.com/TyOverby/bincode/commit/d964b52e59e24ab01ca7005c4e0d2dc765a5d086, which fixes the deserialisation issue for euclid with bincode which made pretty much all the CI infra dies. Sorry for this.

**Comment by jdm** [comment]
@bors-servo: retry
* #11859

**Pull request merged**
