### PR TITLE
Record reference test stdout and stderr

### PR DESCRIPTION
**Pull request by mrobinson**
When reference tests crash it is difficult to debug the issue, because
the stacktrace and any other output is discarded by the test harness.
Instead of discarding it, write the output to text files in the test
results directory which will make it easier to debug crashing tests.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7917)

### CODE REVIEW

**Comment by jdm** [comment]
Any particular reason not to use Stdio::inherit() and Stderr::inherit(), to get the output into the standard logging on the build machines?

**Comment by jdm** [comment]
Alterntively, if all the reftests were translated to WPT reftests than this issue would be moot :)

**Comment by mrobinson** [comment]
@jdm I can definitely explore that, but I originally did not do that because I thought the output would be interlaced confusingly with the output from the test harness itself.

**Comment by mrobinson** [comment]
@jdm Stderr::inherit(), does seem to mix the backtraces with the output of the test harness, which makes the output quite a bit more confusing. I think that the output file is a better option in this case.

I also agree that it's a good idea to migrate the ref-tests to be W3C style tests, but that is a much more complicated task, so I think this is a decent stopgap solution. This change was very helpful for debugging a recent issue that only appeared during reftesting.

**Comment by jdm** [comment]
Ok. I guess my only remaining concern is that this is not Windows friendly, and it would be nice to fix that.

**Comment by jdm** [comment]
I also have vague concerns about the temp directories becoming crowded on the build machines? Not sure how much of a problem that is; any thoughts @larsbergstrom?

**Comment by mrobinson** [comment]
@jdm Could you elaborate a bit on the Windows concerns? Is it that the path names are too long?

I'm not sure if it is feasible, but moving the results from a temporary directory to a checkout specific directory would make it possible to clear the results between runs and allow running tests for two checkouts in parallel.

**Comment by jdm** [comment]
I was assuming that `/tmp` wouldn't work, but maybe if we rely on msys out of the gate that's not a problem.

**Comment by mrobinson** [comment]
@jdm or @larsbergstrom Do you have a sense if moving the results to the build directory would be useful  and possible? To me it seems like a good option because it is simpler to clean them and they will not clash between checkouts.

**Comment by larsbergstrom** [comment]
@bors-servo r+

I think this will definitely help with debugging in the short term. In the longer term, @Ms2ger is planning to rewrite these tests as WPT tests and remove the harness entirely, so I'm fine with doing anything that eases immediate pain, so long as it's not a huge investment since this tool is on its way out.

**Pull request merged**
