### PR TITLE
HTMLMediaElement backoff protocol and other improvements to a/v playback

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

This PR implements a backoff protocol to keep us from dropping frames whenever it's possible. It also add some other improvements like:
- Clean up the implementation a little bit by adding all fetch request related state to `HTMLMediaElementFetchContext`.
- Make sure that we ignore responses from old requests.
- Set the stream to seekable iff there's support for range requests. This will likely change when we add the media cache.
- Implements part of [step 8 of the seek spec](https://html.spec.whatwg.org/multipage/media.html#dom-media-seek) where we bail out if the stream is not seekable.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22522)

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
looks good!

**Comment by CYBAI** [comment]
<details>

```
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_canplay.html", 
    "line": 87076, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_loadeddata_noautoplay.html", 
    "line": 91335, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_order_canplay_playing.html", 
    "line": 92915, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/infrastructure/urls/dynamic-changes-to-base-urls/dynamic-urls.sub.html", 
    "line": 94398, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/syntax/parsing/html5lib_tests7.html?run_type=uri", 
    "line": 94456, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/paused_false_during_play.html", 
    "line": 94672, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/infrastructure/urls/dynamic-changes-to-base-urls/historical.sub.xhtml", 
    "line": 96420, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_canplaythrough.html", 
    "line": 106111, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_loadedmetadata_noautoplay.html", 
    "line": 107629, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/loading-the-media-resource/load-events-networkState.html", 
    "line": 114549, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_canplay_noautoplay.html", 
    "line": 114746, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/networkState_during_loadstart.html", 
    "line": 118096, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/paused_true_during_pause.html", 
    "line": 119657, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_order_canplay_canplaythrough.html", 
    "line": 125854, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/_mozilla/mozilla/collections.html", 
    "line": 126207, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/loading-the-media-resource/load-removes-queued-error-event.html", 
    "line": 128732, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_loadedmetadata.html", 
    "line": 129350, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_play.html", 
    "line": 136775, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_playing.html", 
    "line": 144488, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_loadstart.html", 
    "line": 144924, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/readyState_during_loadedmetadata.html", 
    "line": 175297, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_playing_noautoplay.html", 
    "line": 175360, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_canplaythrough_noautoplay.html", 
    "line": 176728, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_play_noautoplay.html", 
    "line": 177739, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-insert-into-iframe.html", 
    "line": 177901, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_loadeddata.html", 
    "line": 182922, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/loading-the-media-resource/autoplay-overrides-preload.html", 
    "line": 183326, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/readyState_during_canplaythrough.html", 
    "line": 183766, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": "Test timed out", 
    "stack": null, 
    "subtest": "audio events - pause", 
    "test": "/html/semantics/embedded-content/media-elements/event_pause_noautoplay.html", 
    "line": 183958, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "NOTRUN", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "video events - pause", 
    "test": "/html/semantics/embedded-content/media-elements/event_pause_noautoplay.html", 
    "line": 183959, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "NOTRUN", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "calling play() then pause() on non-autoplay audio should trigger pause event", 
    "test": "/html/semantics/embedded-content/media-elements/event_pause_noautoplay.html", 
    "line": 183960, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_pause_noautoplay.html", 
    "line": 183961, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_order_loadedmetadata_loadeddata.html", 
    "line": 186458, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/event_loadstart_noautoplay.html", 
    "line": 188529, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/readyState_during_playing.html", 
    "line": 189672, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/readyState_during_canplay.html", 
    "line": 189889, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/the-audio-element/audio_constructor.html", 
    "line": 193741, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/src_reflects_attribute_not_source_elements.html", 
    "line": 193834, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": "Test timed out", 
    "stack": null, 
    "subtest": "paused state when removing from a document", 
    "test": "/html/semantics/embedded-content/media-elements/playing-the-media-resource/pause-remove-from-document.html", 
    "line": 217872, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/media-elements/playing-the-media-resource/pause-remove-from-document.html", 
    "line": 217873, 
    "action": "test_result", 
    "expected": "OK"
}
```

</details>

**Comment by ferjm** [comment]
@bors-servo retry
- #22675

**Pull request merged**
