### PR TITLE
Eliminate duplicate Layout DOM wrappers

### LINKED ISSUE #29691: Look into moving the layout DOM wrappers back into the script crate
The layout / style DOM wrappers are in the layout_thread crate because they currently need to know how to initialize and clear the `LayoutData` which is stored on the DOM nodes themselves. This has a few issues:

1. Details of the script thread leak into layout whereas the `script_layout_interface` could provide a safe interface between them.
2. The wrappers must be duplicated in both Layout 2020 and Layout 2013.
3. Because of the tricky design, there is a proliferation of traits on these wrappers which makes the code difficult to understand.

An idea here is to make all of the wrappers generics on LayoutData.

### PR DESCRIPTION
**Pull request by mrobinson**
There are duplicate sets of Layout DOM wrappers: one for Layout 2013 and one for Layout 2020. As part of cleaning up and simplifying the wrappers, this change parameterizes them on the specific layout data they contain. This allows them to be shared again. In addition, various small cleanups are included.

Fixes #29691.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #29691
- [x] There are tests for these changes

### CODE REVIEW

**Review by jdm — APPROVED** [review]
This looks like a reasonable way to reduce duplication!

**Comment by mrobinson** [comment]
@bors-servo r=jdm

Thanks for the review!

**Comment by jdm** [comment]
@bors-servo retry
* #29724

**Pull request merged**
