### PR TITLE
Make android logging work for multiple println calls

### LINKED ISSUE #21875: Android logging is cutting off the beginning of some messages
```
10-05 16:16:11.184  5344  5547 D simpleservo: [object Object]
10-05 16:16:11.389  5344  5547 D simpleservo:
10-05 16:16:11.586  5344  5547 D simpleservo: {"message":"Polyfilling worker: //polyfill.twitchsvc.net/v2/polyfill.min.js?unknown=polyfill&features=fetch%2CSet%2CMap%2CObject.assign%2CURL%2CUserTiming%2CString.prototype.startsWith%2CArray.prototype.includes%2CString.prototype.includes%2CObject.values%2CObject.entries%2CArray.from%2CIntl%2CIntl.~locale.en&flags=gated","level":"INFO","time":1538770571579}
10-05 16:16:11.629  5344  5547 D simpleservo:
10-05 16:16:12.104  5344  5547 D simpleservo: ct.values%2CObject.entries%2CArray.from%2CIntl%2CIntl.~locale.en&flags=gated","level":"INFO","time":1538770571579}
10-05 16:16:12.116  5344  5547 D simpleservo: en&flags=gated","level":"INFO","time":1538770571579}
```

### PR DESCRIPTION
**Pull request by jdm**
The existing implementation had incorrect calculations for calculating when there was unlogged data sitting in the buffer and when the buffer was full. With these changes I am able to see the expected output for the following testcase:
```html
<script>
  console.log("hi");
  console.log("hi there");
  console.log("hi there again");
  let s = "hi there again x2 ";
  for (var i = 0; i < 10; i++) {
    s += s;
  }
  console.log(s);
  </script>
```

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #21875
- [x] These changes do not require tests because no automated tests for behaviour of logcat on android

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21950)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r+

PogChamp

**Comment by jdm** [comment]
@bors-servo retry
* oom

**Comment by jdm** [comment]
This did not make the nightly build, if that's what you're testing.

**Comment by nox** [comment]
Nah I just forgot to reinstall the app on my device.

**Pull request merged**
