### PR TITLE
Merge BoxShadowList and TextShadowList into ShadowList<T>

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17576)

### CODE REVIEW

**Comment by nox** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=c363c79b3bb819cc53c7c4327008a893dea7ce08

**Comment by SimonSapin** [comment]
r=me with gecko fixed:

```rust
[task 2017-06-30T14:10:26.756875Z] 14:10:26     INFO -  error[E0432]: unresolved import `gecko_bindings::bindings::Gecko_ClearAlternateValues`
[task 2017-06-30T14:10:26.762094Z] 14:10:26     INFO -      --> /home/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-077f5b469d68e8b7/out/gecko_properties.rs:5391:40
[task 2017-06-30T14:10:26.762159Z] 14:10:26     INFO -       |
[task 2017-06-30T14:10:26.762220Z] 14:10:26     INFO -  5391 |         use gecko_bindings::bindings::{Gecko_ClearAlternateValues, Gecko_AppendAlternateValues};
[task 2017-06-30T14:10:26.762286Z] 14:10:26     INFO -       |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Gecko_ClearAlternateValues` in `gecko_bindings::bindings`
[task 2017-06-30T14:10:26.762340Z] 14:10:26     INFO -  error[E0432]: unresolved import `gecko_bindings::bindings::Gecko_AppendAlternateValues`
[task 2017-06-30T14:10:26.762414Z] 14:10:26     INFO -      --> /home/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-077f5b469d68e8b7/out/gecko_properties.rs:5391:68
[task 2017-06-30T14:10:26.762445Z] 14:10:26     INFO -       |
[task 2017-06-30T14:10:26.762498Z] 14:10:26     INFO -  5391 |         use gecko_bindings::bindings::{Gecko_ClearAlternateValues, Gecko_AppendAlternateValues};
[task 2017-06-30T14:10:26.762573Z] 14:10:26     INFO -       |                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Gecko_AppendAlternateValues` in `gecko_bindings::bindings`
[task 2017-06-30T14:10:26.762627Z] 14:10:26     INFO -  error[E0432]: unresolved import `gecko_bindings::bindings::Gecko_CopyAlternateValuesFrom`
[task 2017-06-30T14:10:26.762710Z] 14:10:26     INFO -      --> /home/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-077f5b469d68e8b7/out/gecko_properties.rs:5473:13
[task 2017-06-30T14:10:26.762744Z] 14:10:26     INFO -       |
[task 2017-06-30T14:10:26.767669Z] 14:10:26     INFO -  5473 |         use gecko_bindings::bindings::Gecko_CopyAlternateValuesFrom;
[task 2017-06-30T14:10:26.768351Z] 14:10:26     INFO -       |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Gecko_CopyAlternateValuesFrom` in `gecko_bindings::bindings`. Did you mean to use `Gecko_CopyImageValueFrom`?
[task 2017-06-30T14:10:26.768906Z] 14:10:26     INFO -  error: aborting due to 3 previous errors
[task 2017-06-30T14:10:26.768979Z] 14:10:26     INFO -  error: Could not compile `style`.
```

**Comment by nox** [comment]
I'm pretty sure this my code isn't the culprit on this.

**Comment by nox** [comment]
Cc @emilio @heycam

**Comment by emilio** [comment]
Yup, it's not, autoland was busted for an hour or so, should be fixed now.

**Comment by nox** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=f178ec68f9d186b2b4ae909b4565b0feaf957864

**Comment by nox** [comment]
Did a mistake in the `color` field of the result of `SimpleShadow::get_zero_value`.

https://treeherder.mozilla.org/#/jobs?repo=try&revision=c5a4550087b7c9ba259689a861c9c39bdb9696f1

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/17576#-:-Ko2N_LgE9bmslGwSbQG:bkg9nno)*

**Pull request merged**
