### PR TITLE
Fix geckolib build for Windows

### PR DESCRIPTION
**Pull request by upsuper**
It contains several fixes to make `./mach build-geckolib` work on Windows.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12338)

### CODE REVIEW

**Comment by bholley** [comment]
Awesome, thanks! @bors-servo r+

**Comment by aneeshusa** [comment]
Is this something that should be added to our Windows builder to prevent regressions in the future?

**Comment by bholley** [comment]
That would be great! Any idea who can help with that?

**Comment by aneeshusa** [comment]
You'll need to make a PR to the servo/saltfs repo and update the `buildbot/master/files/config/steps.yml` file, adding a line to the windows builder.

**Pull request merged**
