### PR TITLE
Update web-platform-tests.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5146)

### CODE REVIEW

**Comment by jdm** [comment]
```
/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm
------------------------------------------------------------
ERROR expected FAIL [Parent]
/2dcontext/compositing/canvas_compositing_globalcompositeoperation_001.htm
--------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/2dcontext/line-styles/canvas_linestyles_linecap_001.htm
--------------------------------------------------------
ERROR expected FAIL [Parent]
/2dcontext/building-paths/canvas_complexshapes_beziercurveto_001.htm
--------------------------------------------------------------------
ERROR expected FAIL [Parent]
/2dcontext/shadows/canvas_shadows_002.htm
-----------------------------------------
ERROR [Parent]
/2dcontext/transformations/canvas_transformations_scale_001.htm
---------------------------------------------------------------
ERROR expected FAIL [Parent]
/FileAPI/url/url_xmlhttprequest_img.html
----------------------------------------
ERROR expected TIMEOUT [Parent]
/2dcontext/the-canvas-state/canvas_state_restore_001.htm
--------------------------------------------------------
ERROR expected FAIL [Parent]
/html/dom/elements/global-attributes/dir_auto-EN-L.html
-------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-EN-R.html
-------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-L.html
----------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-N-EN-L.html
---------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-N-EN-R.html
---------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-N-EN.html
-------------------------------------------------------
ERROR expected FAIL [Parent]
/html/dom/elements/global-attributes/dir_auto-N-R.html
------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-N-L.html
------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-R.html
----------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-L.html
--------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-bdi-L.html
------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-R.html
--------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-bdi-R.html
------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-dir-L.html
------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-dir_auto-L.html
-----------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-dir-R.html
------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-dir_auto-R.html
-----------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-style-L.html
--------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-textarea-L.html
-----------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-style-R.html
--------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-textarea-R.html
-----------------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-input-EN-L.html
-------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-input-L.html
----------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-input-EN-R.html
-------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-input-N-EN-R.html
---------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-input-N-EN-L.html
---------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-input-N-EN.html
-------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-input-N-L.html
------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-input-N-R.html
------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-input-R.html
----------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-pre-N-EN.html
-----------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-isolate.html
----------------------------------------------------------
ERROR expected FAIL [Parent]
/html/dom/elements/global-attributes/dir_auto-pre-N-between-Rs.html
-------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/dom/elements/global-attributes/dir_auto-pre-mixed.html
------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/dom/elements/global-attributes/dir_auto-textarea-N-EN.html
----------------------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/dir_auto-textarea-N-between-Rs.html
------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/dom/elements/global-attributes/lang-xmllang-01.html
---------------------------------------------------------
ERROR expected FAIL [Parent]
/html/dom/elements/global-attributes/dir_auto-textarea-mixed.html
-----------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/dom/elements/global-attributes/style-01.html
--------------------------------------------------
ERROR [Parent]
/html/dom/elements/global-attributes/lang-xyzzy.html
----------------------------------------------------
ERROR expected FAIL [Parent]
/html/rendering/non-replaced-elements/flow-content-0/figure.html
----------------------------------------------------------------
ERROR [Parent]
/html/rendering/bindings/the-select-element-0/option-label.html
---------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/rendering/non-replaced-elements/tables/table-border-1.html
----------------------------------------------------------------
ERROR [Parent]
/html/rendering/non-replaced-elements/tables/table-border-2.html
----------------------------------------------------------------
ERROR [Parent]
/html/rendering/non-replaced-elements/tables/table-width-150percent.html
------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/rendering/non-replaced-elements/tables/table-layout.html
--------------------------------------------------------------
ERROR [Parent]
/html/rendering/non-replaced-elements/the-page/body_text_00ffff.xhtml
---------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/img_border_percent.xhtml
-----------------------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/object_border_perc.xhtml
-----------------------------------------------------------------------------------------------------
ERROR [Parent]
/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/object_border_pixel.xhtml
------------------------------------------------------------------------------------------------------
ERROR [Parent]
/html/semantics/document-metadata/the-style-element/html_style_in_comment.xhtml
-------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/rendering/replaced-elements/images/space.html
---------------------------------------------------
ERROR [Parent]
/html/semantics/embedded-content/the-embed-element/embed-represent-nothing-02.html
----------------------------------------------------------------------------------
ERROR [Parent]
/html/semantics/embedded-content/the-embed-element/embed-represent-nothing-01.html
----------------------------------------------------------------------------------
ERROR [Parent]
/html/semantics/embedded-content/the-embed-element/embed-represent-nothing-04.html
----------------------------------------------------------------------------------
ERROR [Parent]
/html/semantics/embedded-content/the-embed-element/embed-represent-nothing-03.html
----------------------------------------------------------------------------------
ERROR [Parent]
/html/semantics/forms/the-textarea-element/textarea-newline-bidi.html
---------------------------------------------------------------------
ERROR [Parent]
/html/semantics/forms/the-input-element/image01.html
----------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/grouping-content/the-li-element/grouping-li-reftest-001.html
----------------------------------------------------------------------------
ERROR [Parent]
/html/semantics/grouping-content/the-li-element/grouping-li-reftest-002.html
----------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-start-reftest-001.html
----------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-rev-reftest-001.html
--------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-001.html
---------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-start-reftest-002.html
----------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-002.html
---------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-003.html
---------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/grouping-content/the-pre-element/grouping-pre-reftest-001.html
------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/reversed-2.html
---------------------------------------------------------------
ERROR [Parent]
/html/semantics/grouping-content/the-pre-element/pre-newline-bidi.html
----------------------------------------------------------------------
ERROR [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-auto-dir-default.html
------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-nested.html
----------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-missing-pdf.html
---------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-number.html
----------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-separate.html
------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-another-bdi-1.html
--------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-another-bdi-2.html
--------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-letter-following-1.html
-------------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-letter-following-2.html
-------------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-letter-preceding-1.html
-------------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-letter-preceding-2.html
-------------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-number-following-1.html
-------------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-number-following-2.html
-------------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-surrounding-run.html
----------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped.html
-----------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-paragraph-level-container.html
---------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdo-element/bdo-child.html
-------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdo-element/bdo-ltr.html
-----------------------------------------------------------------
ERROR [Parent]
/html/semantics/text-level-semantics/the-bdo-element/bdo-override.html
----------------------------------------------------------------------
ERROR [Parent]
/html/semantics/text-level-semantics/the-bdo-element/bidi-001.html
------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-br-element/br-bidi-in-inline-ancestors.html
------------------------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-wbr-element/wbr-element.html
---------------------------------------------------------------------
ERROR expected FAIL [Parent]
/html/semantics/text-level-semantics/the-br-element/br-bidi.html
----------------------------------------------------------------
ERROR [Parent]
```

**Comment by jdm** [comment]
Note - reftests are the only things failing, and only on linux, so I suspect one of the wptrunner changes.

**Comment by jdm** [comment]
I was wrong, we are still hitting this on other PRs.

**Comment by jdm** [comment]
Wow - our "passing" reftests right now are hitting this: http://build.servo.org/builders/linux2/builds/951/steps/shell_1/logs/stdio . Maybe the wptrunner update just better detects these problems now?

**Comment by Ms2ger** [comment]
That should be fixed by https://github.com/servo/saltfs/pull/21.

**Comment by jdm** [comment]
```
/webstorage/event_local_key.html
--------------------------------
NOTRUN key property test of local event
/webstorage/event_local_newvalue.html
-------------------------------------
NOTRUN newValue property test of local event
/webstorage/event_local_storagearea.html
----------------------------------------
NOTRUN storageArea property test of local event
/webstorage/event_local_oldvalue.html
-------------------------------------
NOTRUN oldValue property test of local event
/webstorage/event_local_url.html
--------------------------------
NOTRUN url property test of local event
```

**Pull request merged**
