### PR TITLE
added tests to http_loader, veryfing if redirects use correct cookies

### PR DESCRIPTION
**Pull request by njskalski**
this is second PR, following https://github.com/servo/servo/pull/7617 .

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9039)

### CODE REVIEW

**Comment by askalski** [comment]
@jdm, can you look at this?

**Comment by jdm** [comment]
Sorry for the delay! This looks good apart from two small corrections.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/unit/net/http_loader.rs, line 173 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9039#-K6oJkxgEyS8lQKvpdn_:-K6oJkxgEyS8lQKvpdna:2084073986) ([raw file](https://github.com/servo/servo/blob/552df7e79e283621b93028501a3362d698916f6b/tests/unit/net/http_loader.rs#L173)):*
Any test using this type will not actually test anything if `expected_headers` is empty. We should keep this assertion.

---

*[tests/unit/net/http_loader.rs, line 1336 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9039#-K6oKlPJeJkiTKMinXWt:-K6oKlPJeJkiTKMinXWu:222426724) ([raw file](https://github.com/servo/servo/blob/f7858f5c568ed86b94fb2d26a7cb46b0bc4833a4/tests/unit/net/http_loader.rs#L1336)):*
Looks like this should be AssertRequestMustNotHaveHeaders, with a "Cookie" header present.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9039#-:-K6oLf_w-98gf1nmbfSQ:-273008237)*

**Comment by askalski** [comment]
@jdm 
Well, about AssertRequestMustNotHaveHeaders - you are right, but I was unable to figure out how to do it, since above I have 
```
impl HttpRequestFactory for Factory {
        type R = AssertRequestMustIncludeHeaders;
...
```
Is there a way to use them both in one factory, or use two factories?

**Comment by jdm** [comment]
Oh, that's interesting. I don't have a good solution, immediately.

**Comment by askalski** [comment]
Well, that's why I removed that assertion. The other way around is to create a separate "AssertRequestMustHaveHeadersSet" or something like this, with an *optional* dictionary.

**Comment by askalski** [comment]
I messed up the commit again :(

**Comment by askalski** [comment]
@jdm ready for another review

**Comment by askalski** [comment]
hi, what's wrong? What does it mean " code-review/reviewable — Review status updates disabled by admin"? Is it because I squashed the commits?

**Comment by jdm** [comment]
No, that's because I disabled the reviewable commit status updates in the admin interface. You can ignore that.

**Comment by jdm** [comment]
Sorry for sitting on this. I think the solution here is Good Enough, and I'll file issues if I come up with a way to change the factory output between requests.

**Pull request merged**
