### PR TITLE
implement navigator.platform

### LINKED ISSUE #7573: Implement navigator.platform
https://github.com/servo/servo/blob/master/components/script/dom/navigator.rs#L54

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #7573

I used this as a reference: http://stackoverflow.com/questions/19877924/what-is-the-list-of-possible-values-for-navigator-platform-as-of-today

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7582)

### CODE REVIEW

**Comment by huonw** [comment]
FYI, one can use the `cfg!(...)` macro (rather than attribute) to write it all as a normal expression rather than having to have repeated definitions of the function, e.g.

```rust
if cfg!(all(any(target_os = "linux",
                       target_os = "android"),
                   target_arch = "x86_64")) {
    "Linux x86_64"
} else if cfg!(all(any(target_os = "linux",
                       target_os = "android"),
                   target_arch = "x86")) {
    "Linux i686"
} else {
    ""
}
```

**Comment by paulrouget** [comment]
Didn't know that. This will probably be better. Thanks.

**Comment by paulrouget** [comment]
Hm, with my current approach, it won't compile if the platform is not listed. So any port to a new platform requires adding a string for `navigator.platorm`. Which is, I believe, a good thing.

**Comment by huonw** [comment]
Good point; seems like a good thing to me too.

**Comment by nox** [comment]
https://html.spec.whatwg.org/multipage/webappapis.html#dom-navigator-platform

> Any information in this API that varies from user to user can be used to profile the user. In fact, if enough such information is available, a user can actually be uniquely identified. For this reason, user agent implementors are strongly urged to include as little information in this API as possible.

Couldn't we just emit a constant?

**Comment by paulrouget** [comment]
> Couldn't we just emit a constant?

What do you mean?

**Comment by nox** [comment]
I mean to always return the same thing. Even on different plateforms. At the very least I am not sure the architecture is important to include.

**Comment by paulrouget** [comment]
> I mean to always return the same thing. Even on different plateforms.

This is how it works now. It always returns an empty string.

> At the very least I am not sure the architecture is important to include.

For browser.html, we need `navigator.platform` to know what modifiers to use for the keybindings and what kind of window controls we should use. We don't care much about the architecture.

**Comment by paulrouget** [comment]
I removed the architecture string.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes +@jdm

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/wpt/mozilla/meta/mozilla/navigator.html.ini, line 6 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7582#-JzLPCgXKXhRyRYBZLje)** ([raw file](https://github.com/servo/servo/blob/6836db0fafec5e504021922245c9114d24247635/tests/wpt/mozilla/meta/mozilla/navigator.html.ini#L6)):</sup>
Can we use `if os != "linux": FAIL?

---

<sup>**[tests/wpt/mozilla/meta/mozilla/navigator.html.ini, line 11 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7582#-JzLPHg-TO3ay9f9eUG9)** ([raw file](https://github.com/servo/servo/blob/6836db0fafec5e504021922245c9114d24247635/tests/wpt/mozilla/meta/mozilla/navigator.html.ini#L11)):</sup>
Ditto.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7582)

**Comment by nox** [comment]
> For browser.html, we need navigator.platform to know what modifiers to use for the keybindings and what kind of window controls we should use. We don't care much about the architecture.

Do you mean that browser.html will reimplement input methods etc in JS land? Won't that have the same insane amount of issues like the Atom editor suffers from?

https://github.com/andischerer/atom-keyboard-localization/issues

**Comment by paulrouget** [comment]
> Do you mean that browser.html will reimplement input methods etc in JS land?

No. By “keybinding”, I refer to things like “Cmd-T” (which has nothing to do with text input), and "window controls” refers to the close|max|min buttons of a window.

**Comment by paulrouget** [comment]
review ping

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7582)

**Comment by jdm** [comment]
```
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/navigator.rs:56:9: 56:32 error: unresolved name `navigatorinfo::Platform`. Did you mean to call `self.navigatorinfo::Platform`? [E0425]
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/navigator.rs:56         navigatorinfo::Platform()
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/navigator.rs:56:9: 56:32 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/workernavigator.rs:57:9: 57:32 error: unresolved name `navigatorinfo::Platform`. Did you mean to call `self.navigatorinfo::Platform`? [E0425]
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/workernavigator.rs:57         navigatorinfo::Platform()
                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/workernavigator.rs:57:9: 57:32 help: run `rustc --explain E0425` to see a detailed explanation
```

**Comment by paulrouget** [comment]
Oops, s/Linux/linux.

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Comment by paulrouget** [comment]
Intermittent? /html/semantics/embedded-content/the-canvas-element/size.attributes.setAttribute.hex.html

**Comment by nox** [comment]
@bors-servo retry

@7422

**Comment by jdm** [comment]
Infrastructure failure; hold tight.

**Comment by metajack** [comment]
@bors-servo retry

- infra issues addressed i hope

**Pull request merged**
