### PR TITLE
Replace side-effecting unwrap_or_else by if let in constellation.

### PR DESCRIPTION
**Pull request by asajeffrey**
This addresses @nox's comments in #10295.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10345)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[components/compositing/constellation.rs, line 717 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQxK5rfbJBJcWkUGdY:-KEQxK5rfbJBJcWkUGdZ:1418615264) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L717)):*
This code isn't the same, now you don't call anymore `handle_send_error` when the pipeline couldn't be found at all. I guess that's intended though?

In that case, I would do:

```rust
if let Some(pipeline) = self.pipelines.get(&pipeline_id) {
    if let Err(e) = pipeline.script_chan.send(msg) {
        self.handle_send_error(pipeline_id, e);
    }
} else {
    debug!(...);
    return true;
}
```

---

*[components/compositing/constellation.rs, line 729 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQyL7uRLBb_T7WIrey:-KEQyL7uRLBb_T7WIrez:-716728200) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L729)):*
I don't hate all combinators in all circumstances, the `map_or` is fine here. :)

---

*[components/compositing/constellation.rs, line 908 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQybcfESOy1roY4t1s:-KEQybcfESOy1roY4t1t:1293162310) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L908)):*
Just rewrite the whole function:

```rust
if let Some(pipeline) = self.pipelines.get_mut(&pipeline_id) {
    pipeline.size = Some(*size);
    if let Err(e) = pipeline.script_chan.send(msg) {
        self.handle_send_error(pipeline_id, e);
    }
}
```

---

*[components/compositing/constellation.rs, line 930 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQz0S9UWqrMefrUfAY:-KEQz0S9UWqrMefrUfAZ:1266499169) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L930)):*
```
if let Some(pipeline) = self.pipelines.get(&subframe_parent_id) {
    if let Err(e) = pipeline.script_chan.send(msg) {
        self.handle_send_error(subframe_parent_id, e);
    }
} else {
    debug!("Pipeline {:?} subframe loaded after closure.", subframe_parent_id)
    return;
}
```

---

*[components/compositing/constellation.rs, line 1030 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQziosjQKsNe3NMtm3:-KEQziotT3VsLr60N7Sd:-380770845) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1030)):*
Again, it seems to me that you can just rewrite the whole function:

```rust
let pipeline = match self.pipelines.get(&pipeline_id) {
    Some(pipeline) => pipeline,
    None => {
        debug!(...);
        return;
    }
};

let result = match tick_type {
    AnimationTickType::Script => {
        pipeline.script_chan.0.send(ConstellationControlMsg::TickAllAnimations(pipeline_id))
    },
    AnimationTickType::Layout => {
        pipeline.layout_chan.0.send(LayoutControlMsg::TickAnimations)
    }
};

if let Err(e) = result {
    self.handle_send_error(pipeline_id, e);
}
```

I really think we should have a specific function on pipelines, which would take a channel and a message and would call `handle_send_error` itself. We don't even distinguish whether it's script_chan or layout_chan that encountered an error in this case.

---

*[components/compositing/constellation.rs, line 1042 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER0TdHQOoKVkefhFCH:-KER0TdHQOoKVkefhFCI:901257296) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1042)):*
Why not just:

```rust
let (parent_info, window_size) =
    self.pipelines.get(&source_id)
        .map(|source| (source.parent_info, source.size))
        .unwrap_or((None, None));
```

---

*[components/compositing/constellation.rs, line 1058 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER05w3skPfrMtP7p0k:-KER05w3skPfrMtP7p0l:-352368207) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1058)):*
As usual, I think this idiom is better conveyed as two nested `if let` without intermediate results.

---

*[components/compositing/constellation.rs, line 1083 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER0Il13p8nBsVm2klV:-KER0Il13p8nBsVm2klW:250875891) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1083)):*
I preferred the original way, where both `parent_info` and `window_size` were bound at the same moment.

---

*[components/compositing/constellation.rs, line 1235 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER11NuFFvjvtB-ZjTX:-KER11NuFFvjvtB-ZjTY:-352368207) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1235)):*
As usual, I think this idiom is better conveyed as two nested `if let` without intermediate results.

---

*[components/compositing/constellation.rs, line 1253 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER13kvmAiGMOdvKcLj:-KER13kvmAiGMOdvKcLk:-972711970) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1253)):*
An `if let` expression here would decrease the indentation, and thus look nicer.

---

*[components/compositing/constellation.rs, line 1262 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER12H18ER_fLaYPAvv:-KER12H18ER_fLaYPAvw:-352368207) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1262)):*
As usual, I think this idiom is better conveyed as two nested `if let` without intermediate results.

---

*[components/compositing/constellation.rs, line 1338 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER1FPFBM3eurS5BOHe:-KER1FPFBM3eurS5BOHf:-352368207) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1338)):*
As usual, I think this idiom is better conveyed as two nested `if let` without intermediate results.

---

*[components/compositing/constellation.rs, line 1411 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER1HV3qS2Hu7F3A4vB:-KER1HV3qS2Hu7F3A4vC:-352368207) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1411)):*
As usual, I think this idiom is better conveyed as two nested `if let` without intermediate results.

---

*[components/compositing/constellation.rs, line 1431 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER1V6jFCq3XSyVhqCL:-KER1V6jFCq3XSyVhqCM:-996777661) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1431)):*
What happens if that one send call fails, btw?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10345#-:-KER1dR1Hc_kGGKjf37g:1458266033)*

**Comment by asajeffrey** [comment]
We have different opinions about coding style, quel surprise.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[components/compositing/constellation.rs, line 717 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQxK5rfbJBJcWkUGdY:-KEX54i1Bm4d8kZPMHTb:-499146009) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L717)):*
Done.

---

*[components/compositing/constellation.rs, line 729 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQyL7uRLBb_T7WIrey:-KEX5FtE-iV1C8klHwK_:-808846234) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L729)):*
OK, I don't see why, doesn't the `debug!` count as a side-effect?

---

*[components/compositing/constellation.rs, line 908 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQybcfESOy1roY4t1s:-KEX5iYqjL_uG1l_XtB8:-1969147958) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L908)):*
Does your version pass the borrow checker?

---

*[components/compositing/constellation.rs, line 930 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQz0S9UWqrMefrUfAY:-KEX5u7xee_qMZhNOl1R:1700997001) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L930)):*
Ditto.

---

*[components/compositing/constellation.rs, line 1030 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQziosjQKsNe3NMtm3:-KEX6fYLTnJCz3i9u_ig:-499146009) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1030)):*
Done.

---

*[components/compositing/constellation.rs, line 1042 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER0TdHQOoKVkefhFCH:-KEX7lWvbynz0Cjjo6Nr:-499146009) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1042)):*
Done.

---

*[components/compositing/constellation.rs, line 1058 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER05w3skPfrMtP7p0k:-KEX7rnCHhr4oA02gJJF:-1223351142) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1058)):*
The problem with the nested-if idiom is that the code gradually drifts right, due to indentation. You also end up with spurious diffs whenever the indentation changes, which makes code maintenance annoying.

Also in this case, borowchk.

---

*[components/compositing/constellation.rs, line 1083 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER0Il13p8nBsVm2klV:-KEX8_BqyscugJWbfBfj:-499146009) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1083)):*
Done.

---

*[components/compositing/constellation.rs, line 1235 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER11NuFFvjvtB-ZjTX:-KEX8qabP0KZhBVWuxfc:1700997001) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1235)):*
Ditto.

---

*[components/compositing/constellation.rs, line 1253 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER13kvmAiGMOdvKcLj:-KEX91gOpxQ-bEhDop1S:138951996) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1253)):*
I prefer match to if let in the case that there's an else branch. The extra indentation makes the code easier to read, IMO. YMMV.

---

*[components/compositing/constellation.rs, line 1262 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER12H18ER_fLaYPAvv:-KEX9Opeq8z7uodOT_OL:1700997001) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1262)):*
Ditto.

---

*[components/compositing/constellation.rs, line 1338 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER1FPFBM3eurS5BOHe:-KEX9SJQRDS0ki0W1yV4:1700997001) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1338)):*
Ditto.

---

*[components/compositing/constellation.rs, line 1411 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER1HV3qS2Hu7F3A4vB:-KEX9UZ26SESu7u4arxI:1700997001) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1411)):*
Ditto.

---

*[components/compositing/constellation.rs, line 1431 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KER1V6jFCq3XSyVhqCL:-KEX9YYOgtUG0Z2QoQys:2079741235) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L1431)):*
The API for  the compositor proxy doesn't return a Result.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10345#-:-KEX9heUhBkmALBT7tzS:-265789265)*

**Comment by asajeffrey** [comment]
@nox: I reverted some of your suggested changes, since I couldn't get them to pass borrowchk. Serves me right for checking in changes without compiling them!

**Comment by nox** [comment]
Review status: 0 of 1 files reviewed at latest revision, 14 unresolved discussions.

---

*[components/compositing/constellation.rs, line 717 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQxK5rfbJBJcWkUGdY:-KE_jQX2STXaKv0ENg7x:1542314760) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L717)):*
So was there a borrowck problem here if you remove the intermediate `result` value?

---

*[components/compositing/constellation.rs, line 729 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQyL7uRLBb_T7WIrey:-KE_jZeC70PH0MFBGJM7:2001056576) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L729)):*
Because that's not the main point of that snippet, we do need the result value, which when the clipboard is broken is an empty string.

---

*[components/compositing/constellation.rs, line 908 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQybcfESOy1roY4t1s:-KE_k5Po2QQVyxHqbEjp:-812458853) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L908)):*
I don't see what can make it fail. :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10345)*

**Comment by asajeffrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 14 unresolved discussions.

---

*[components/compositing/constellation.rs, line 717 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQxK5rfbJBJcWkUGdY:-KEaq2QB7DkxANZV8Lwk:-1156170576) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L717)):*
Yes, the pipeline is borrowed from self.pipelines, which means self.handle_send_error can't be called whole pipeline is in scope.

---

*[components/compositing/constellation.rs, line 729 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQyL7uRLBb_T7WIrey:-KEasIbbsp63ELYqmIJx:-499146009) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L729)):*
Done.

---

*[components/compositing/constellation.rs, line 908 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10345#-KEQybcfESOy1roY4t1s:-KEasTVIIHjcaq_8dm5I:-803083712) ([raw file](https://github.com/servo/servo/blob/7f6cc24145dda4f056f70add7154fd3a416bb0d6/components/compositing/constellation.rs#L908)):*
Calling self.handle_send_error while pipeline is still in scope. Pipeline is borrowed from self.pipelines, and self.handle_send_error needs `&mut self`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10345)*

**Comment by asajeffrey** [comment]
Rebased and squashed.

**Comment by asajeffrey** [comment]
Rebased.

**Comment by asajeffrey** [comment]
Rebased. @nox: this is bitrotting.

**Comment by asajeffrey** [comment]
Another rebase. Serious bitrotting here :(

**Comment by nox** [comment]
Sorry about this @asajeffrey. Looks good to me with your last remarks and changes.

@bors-servo r+

**Comment by asajeffrey** [comment]
Thanks!

**Pull request merged**
