### PR TITLE
Read 32kb from the network at a time.

### PR DESCRIPTION
**Pull request by jdm**
Now that https://github.com/servo/servo/pull/16989 has merged, this might actually work.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17169)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks like `read_block` doesn’t need to be generic, we might be able to avoid zeroing the buffers and passing uninitialized memory to `StreamedResponse::read`.

**Comment by jdm** [comment]
Homu never reported back, but all tests passed.

**Comment by jdm** [comment]
Having thought about it further, I would prefer not to introduce unsafe code here without strong motivation.

**Pull request merged**
