### PR TITLE
Test namespace prefix for element equality

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6554)

### CODE REVIEW

**Comment by Ms2ger** [comment]
If this doesn't fix any test, we should change that.

**Comment by dzbarsky** [comment]
Yes, I need to write tests for this and the other namespace stuff I've been working on.

**Comment by dzbarsky** [comment]
Doesn't need a test anymore, but I'm not sure how to remove the label.

**Comment by Ms2ger** [comment]
Test doesn't seem like it can work, you're calling `ttest` rather than `test`.

**Comment by dzbarsky** [comment]
Hmm, I did check that the test failed before the change and passed after. I guess I somehow added the stray character after.

**Comment by dzbarsky** [comment]
But the test doesn't finish now...need to investigate.

**Comment by dzbarsky** [comment]
OK the relevant part of the test passes. I think something else may have regressed in the last few days causing the later part of the test to time out.  We should enable the test and investigate in a followup.

**Comment by dzbarsky** [comment]
Hmm that test is completely unrelated and unexpectedly passes for me even without this change

**Comment by Ms2ger** [comment]
@bors-servo retry
* #6619

**Pull request merged**
