### PR TITLE
Disable SVG sizing tests until SVG is implemented.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11052)

### CODE REVIEW

**Comment by jdm** [comment]
#9374 #9909 #10457 #11027

**Comment by jdm** [comment]
@bors-servo: retry
* infra

**Comment by larsbergstrom** [comment]
@bors-servo retry
 - bad @larsbergstrom

**Comment by larsbergstrom** [comment]
@bors-servo retry
 - https://github.com/servo/saltfs/pull/365

**Comment by mbrubeck** [comment]
@bors-servo retry

* #11052

**Comment by mbrubeck** [comment]
@bors-servo retry

* #11059

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11059

**Pull request merged**
