### PR TITLE
Move DOMString back to script

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11326)

### CODE REVIEW

**Comment by jdm** [comment]
Why all the changes from DOMString to String?

**Comment by nox** [comment]
Because `AttrValue` using `DOMString` is the reason why we have that `non-geckolib` mess, and why `style` ends up transitively depending on `js` through `util` in the normal build. This is what this patch removes.

**Comment by jdm** [comment]
It makes it more difficult to experiment with different underlying representations in the future, right?

**Comment by nox** [comment]
Given we share the `style` crate with `geckolib`, we are going to need something other than `DOMString` in `AttrValue` if we want to get fancy with string representations anyway.

**Comment by Ms2ger** [comment]
@bholley how does this work in Geckolib? Do you use `restyle_hints.rs` at all?

**Comment by bholley** [comment]
> @bholley how does this work in Geckolib?

For non-atomized strings we're currently converting. Depending on the profiles I may end up needing to introduce a wrapper class for certain usages of string within components/style that just acts like String in servo builds and does some tricky utf-16 stuff in Gecko builds. DOMString might help with building that layer, but I can't say so concretely enough to justify objecting to these changes on those grounds.

> Do you use restyle_hints.rs at all?
We don't yet but we will.

**Comment by Ms2ger** [comment]
@bors-servo r+

I suppose.

**Pull request merged**
