### PR TITLE
style: Avoid quadratic time serialization of a declaration block.

### PR DESCRIPTION
**Pull request by emilio**
At least when the longhands aren't custom properties.

We should also look into not serializing the style attribute eagerly when it's
not needed... But a lot of code currently rely on attribute values being
dereferenciables to &str, so that's harder to fix.

We should really look into all those vectors around too, but that's probably
less urgent.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17315)

### CODE REVIEW

**Comment by emilio** [comment]
This should fix most of the perf cliffs seen in #17308.

r? @SimonSapin (or anyone else)

**Comment by emilio** [comment]
cc @glennw

**Comment by emilio** [comment]
This shaves a good amount of time in the following benchmark (~1s to ~600ms):

```html
<!doctype html>
<script>
var div = document.createElement('div');
div.style.border = "10px solid red";
div.style.position = "absolute";
div.style.top = "10px";
div.style.left = "100px";
div.style.width = "100px";
div.style.height = "100px";

var start = new Date();
for (var i = 0; i < 100000; ++i)
  div.style.cssText;
document.write(new Date() - start);
</script>
```

But we should aim to be at the ~300/~400ms boundary.

**Comment by emilio** [comment]
Latest commit puts us at 400ms: https://treeherder.mozilla.org/#/jobs?repo=try&revision=89803b4a80a7093c29443cdbaa96a9b09f1af4df

**Comment by emilio** [comment]
Gah, bad timing pushing to try:

```
[task 2017-06-14T11:21:01.421797Z] 11:21:01     INFO -  error[E0061]: this function takes 2 parameters but 3 parameters were supplied
[task 2017-06-14T11:21:01.422049Z] 11:21:01     INFO -     --> /home/worker/workspace/build/src/servo/components/style/gecko/values.rs:407:26
[task 2017-06-14T11:21:01.422302Z] 11:21:01     INFO -      |
[task 2017-06-14T11:21:01.422577Z] 11:21:01     INFO -  407 |                   set_name(gecko_value, atom!("none").into_addrefed(), pres_context);
[task 2017-06-14T11:21:01.422881Z] 11:21:01     INFO -      |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters
[task 2017-06-14T11:21:01.423117Z] 11:21:01     INFO -      |
[task 2017-06-14T11:21:01.423371Z] 11:21:01     INFO -     ::: /home/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-a2ebb78ccb6eb042/out/gecko/bindings.rs
[task 2017-06-14T11:21:01.423505Z] 11:21:01     INFO -      |
[task 2017-06-14T11:21:01.423677Z] 11:21:01     INFO -  908 | /     pub fn Gecko_SetCounterStyleToName(ptr: *mut CounterStylePtr,
[task 2017-06-14T11:21:01.423860Z] 11:21:01     INFO -  909 | |                                        name: *mut nsIAtom);
[task 2017-06-14T11:21:01.424040Z] 11:21:01     INFO -      | |___________________________________________________________- defined here
[task 2017-06-14T11:21:01.424263Z] 11:21:01     INFO -  error[E0061]: this function takes 2 parameters but 3 parameters were supplied
[task 2017-06-14T11:21:01.424430Z] 11:21:01     INFO -     --> /home/worker/workspace/build/src/servo/components/style/gecko/values.rs:410:26
```

https://treeherder.mozilla.org/#/jobs?repo=try&revision=2e59616696ec527441273f8e9afa92990d56fe59

**Comment by emilio** [comment]
This is all green :)

**Comment by SimonSapin** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/properties/properties.mako.rs, line 1342 at r3](https://reviewable.io:443/reviews/servo/servo/17315#-KmautmK0n0SDU2f-fvA:-KmautmK0n0SDU2f-fvB:b6pstkq) ([raw file](https://github.com/servo/servo/blob/f8d1bd5965fb5537776920cce008dad87a20faac/components/style/properties/properties.mako.rs#L1342)):*
> ```Rust
> 
>     /// The shorthands that this longhand is part of.
>     pub fn shorthands(&self) -> &'static [ShorthandId] {
> ```

Can this whole method be replaced with `self.id().shorthands()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/17315)*

**Comment by emilio** [comment]
> Can this whole method be replaced with self.id().shorthands()?

Not literally, but yes if you match on `self.id()`, so I just did that.

**Comment by SimonSapin** [comment]
Looks good!

@bors-servo r+

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/17315#-:-Kmayj5E0ZpUpkWnPjTW:bchqs7m)*

**Pull request merged**
