### PR TITLE
match :lang() against snapshots correctly

### PR DESCRIPTION
**Pull request by heycam**
Reviewed in https://bugzilla.mozilla.org/show_bug.cgi?id=1365162.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17206)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0432]: unresolved import `gecko_bindings::structs::RawGeckoGfxMatrix4x4`
     --> /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/style-cb572a7d4cfdc2ba/out/properties.rs:78114:31
      |
78114 | #[cfg(feature = "gecko")] use gecko_bindings::structs::RawGeckoGfxMatrix4x4;
      |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `RawGeckoGfxMatrix4x4` in `gecko_bindings::structs`

error[E0425]: cannot find function `Gecko_CSSValue_InitSharedList` in module `bindings`
   --> /home/servo/buildbot/slave/linux-dev/build/components/style/gecko_bindings/sugar/ns_css_value.rs:266:18
    |
266 |         unsafe { bindings::Gecko_CSSValue_InitSharedList(self, values.len() as u32) };
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `bindings::Gecko_CSSValue_SetList`?

error: aborting due to 2 previous errors

error: Could not compile `style`.
```
Needs updated bindings, presumably.

**Comment by heycam** [comment]
I did push some bindings updates but I think I must have clobbered some previous bindings updates that happened since I rebased.

**Pull request merged**
