### PR TITLE
Improve Blob.Size() speed by avoid reading content

### PR DESCRIPTION
**Pull request by izgzhen**
r? @Manishearth 

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12896)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+

wonderful!

**Comment by izgzhen** [comment]
@bors-servo retry

- Intermittent #12891

**Comment by izgzhen** [comment]
wat ... retry is again no working? am I missing something here?

**Comment by Manishearth** [comment]
Retry worked, your PR is still in the queue http://build.servo.org/homu/queue/all

**Comment by izgzhen** [comment]
But homu doesn't give a hint about his ...

**Comment by Manishearth** [comment]
Right. Homu in general doesn't output anything when you approve or retry a PR.

It only outputs in the case you approve a PR without explicitly specifying the hash -- it does this so that the approved hash is logged in the PR somewhere.

So `@bors r+ bcf3e98` and `@bors retry` will not produce any output, but `@bors r+` will; to indicate which hash was approved.

**Comment by Manishearth** [comment]
However, you can do this:

@bors-servo r+

and it will tell you why your PR is not being tested

**Pull request merged**
