### PR TITLE
Account for percentages in fixed table layout

### LINKED ISSUE #13166: Github issue & pull request lists are squashed to the left
image

### PR DESCRIPTION
**Pull request by notriddle**
Don't just use the minimum length all the time.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13166 (github issue number if applicable).
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13192)

### CODE REVIEW

**Comment by notriddle** [comment]
@pcwalton Done.

**Comment by emilio** [comment]
@bors-servo: r=pcwalton,emilio

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/layout/table.rs, line 376 \[r1\]](https://reviewable.io:443/reviews/servo/servo/13192#-KR2_59Mqz88gjov6ivF:-KR2_59Mqz88gjov6ivG:bmjmznm) ([raw file](https://github.com/servo/servo/blob/3a26783b693858383a24a716b17fe7904ac7a54c/components/layout/table.rs#L376)):*
> ```Rust
>                         });
>                     }
>                 } else if num_unspecified_inline_sizes != 0 {
> ```

Could you convert this branch in an `else`? If there are any other reftests to update?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13192#-:-KR2_NK_SILPRWu3PXZx:b-r0zjl9)*

**Comment by Ms2ger** [comment]
Is there a spec for this?

**Comment by notriddle** [comment]
I found this: https://drafts.csswg.org/css-tables-3/#computing-column-measures

>  For the purpose of measuring a column when laid out in fixed mode, only cells which originate in the first row of the table (after reordering the header and footer) will be considered, if any. In addition, the min-content and max-content width of cells is considered zero unless they are directly specified as a length-percentage, in which case they are resolved based on the table width (if it is definite, otherwise use 0).

I wasn't able to find anything this explicit in the CSS2 spec, but it doesn't contradict this anywhere.

**Comment by notriddle** [comment]
I don't think this is actually correct, either (though it does fix Github and my testcase is correct). [The actual rules for assigning column widths in fixed mode are this](https://drafts.csswg.org/css-tables-3/#distributing-width-to-columns):

> These rules *[the rules for distributing excess width in automatic layout mode]* do not apply when the table is laid out in fixed mode. In this case, the simpler rules that follow apply instead:
>
>   * If there are any columns with no width specified, the excess width is distributed in equally to such columns
>   * otherwise, if there are columns with non-zero length widths from the base assignment, the excess width is distributed proportionally to width among those columns
>   * otherwise, if there are columns with non-zero percentage widths from the base assignment, the excess width is distributed proportionally to percentage width among those columns
>   * otherwise, the excess width is distributed equally to the zero-sized columns

In other words, we need to count the number of columns with percentage widths, and follow step 2 if they're not zero.

**Comment by notriddle** [comment]
There, thanks for asking for a spec reference. I forget to do stuff like that.

**Comment by notriddle** [comment]
@bors-servo retry

* #13165

**Pull request merged**
