### PR TITLE
Output to png file since exit flag doesn't work

### PR DESCRIPTION
**Pull request by connorimes**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9425)

### CODE REVIEW

**Comment by KiChjang** [comment]
Sorry, I'm not quite certain what problem this is trying to fix.

**Comment by jdm** [comment]
It's adjusting the code for monitoring energy usage to account for #9203.

**Comment by connorimes** [comment]
That's correct.  We received an email from somebody that will be doing some energy profiling with servo so I wanted to make sure this was working.

**Comment by larsbergstrom** [comment]
@bors-servo r+

I'd ideally like to fix `-x`, but there are a couple of issues with our shutdown-and-exit support too. I'll open separate issues.

**Pull request merged**
