### PR TITLE
Implement DOMTokenList.supports API

### LINKED ISSUE #24965: Implement DOMTokenList.supports API
html/semantics/embedded-content/the-iframe-element/sandbox-ascii-case-insensitive incidentally fails, separately from what it's trying to test, because there's no .supports on iframe.sandbox. It looks like Servo's IDL doesn't even mention it; https://dom.spec.whatwg.org/#interface-domtokenlist does.

### PR DESCRIPTION
**Pull request by ghostd**
Implement DOMTokenList.supports API and "rel" attribute for HTMLAreaElement

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [x] These changes fix #24965

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /custom-elements/reactions/HTMLAreaElement.html:
  └ PASS [expected FAIL] rel on HTMLAreaElement must enqueue an attributeChanged reaction when adding a new attribute
  ▶ Unexpected subtest result in /custom-elements/reactions/HTMLAreaElement.html:
  └ PASS [expected FAIL] rel on HTMLAreaElement must enqueue an attributeChanged reaction when replacing an existing attribute
  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-iframe-element/sandbox-ascii-case-insensitive.html:
  └ PASS [expected FAIL] iframe 'sandbox' ASCII case insensitive, allow-same-or\u0130gin
  ▶ Unexpected subtest result in /dom/idlharness.window.html?exclude=Node:
  └ PASS [expected FAIL] DOMTokenList interface: operation supports(DOMString)
  ▶ Unexpected subtest result in /dom/idlharness.window.html?exclude=Node:
  └ PASS [expected FAIL] DOMTokenList interface: document.body.classList must inherit property "supports(DOMString)" with the proper type
  ▶ Unexpected subtest result in /dom/idlharness.window.html?exclude=Node:
  └ PASS [expected FAIL] DOMTokenList interface: calling supports(DOMString) on document.body.classList with too few arguments must throw TypeError
  ▶ Unexpected subtest result in /html/semantics/document-metadata/the-link-element/link-rellist.html:
  └ PASS [expected FAIL] link.relList: non-string contains
  ▶ Unexpected subtest result in /fetch/metadata/prefetch.https.sub.html:
  └ PASS [expected FAIL] Browser supports prefetch.
  ▶ Unexpected subtest result in /fetch/metadata/preload.https.sub.html:
  └ PASS [expected FAIL] Browser supports preload.
  ▶ Unexpected subtest result in /fetch/metadata/redirect/redirect-http-upgrade.sub.html:
  │ TIMEOUT [expected PASS] Http upgrade preload
  └   → Test timed out
  ▶ Unexpected subtest result in /fetch/metadata/redirect/redirect-http-upgrade.sub.html:
  └ NOTRUN [expected PASS] Http upgrade stylesheet
  ▶ Unexpected subtest result in /fetch/metadata/redirect/redirect-http-upgrade.sub.html:
  └ NOTRUN [expected PASS] Http upgrade track
  ▶ Unexpected subtest result in /fetch/metadata/redirect/redirect-https-downgrade.sub.html:
  │ TIMEOUT [expected PASS] Https downgrade preload
  └   → Test timed out
  ▶ Unexpected subtest result in /fetch/metadata/redirect/redirect-https-downgrade.sub.html:
  └ NOTRUN [expected PASS] Https downgrade stylesheet
  ▶ Unexpected subtest result in /fetch/metadata/redirect/redirect-https-downgrade.sub.html:
  └ NOTRUN [expected PASS] Https downgrade track
  ▶ Unexpected subtest result in /html/links/manifest/link-relationship/link-rel-manifest.html:
  └ PASS [expected FAIL] link element supports a rel value of "manifest".
```

**Comment by jdm** [comment]
I'm not concerned about the new TIMEOUTs, given [this code](https://github.com/web-platform-tests/wpt/blob/421a2362caa02bd3ad4162ade6dcb1ca62212b76/fetch/metadata/resources/redirectTestHelper.sub.js#L163) that now executes.

**Comment by ghostd** [comment]
Rebased, and tests updated

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by jdm** [comment]
One more missing test expectation change:
```
  ▶ Unexpected subtest result in /fetch/metadata/preload.https.sub.html:
  └ PASS [expected FAIL] Browser supports preload.
```

**Comment by ghostd** [comment]
Tests updated.

**Comment by CYBAI** [comment]
@bors-servo try

(Just help to try so that next r+ can merge directly)

**Pull request merged**
