### PR TITLE
counter-reset defaults to 0, not 1.

### PR DESCRIPTION
**Pull request by SimonSapin**
https://drafts.csswg.org/css2/generate.html#counters

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8321)

### CODE REVIEW

**Comment by pcwalton** [comment]
Can you reftest this?

**Comment by SimonSapin** [comment]
@bors-servo try

Let’s see if it fixes existing tests. If not I’ll add some.

**Comment by dzbarsky** [comment]
▶ PASS [expected FAIL] /css21_dev/html4/counters-001.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/counters-004.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/counters-008.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/counters-006.htm

  ▶ Unexpected subtest result in /_mozilla/css/test_variable_serialization_computed.html:

  └ PASS [expected FAIL] subtest #23 with `counter-reset: var(--a)red; --a:orange;`

  ▶ TIMEOUT [expected PASS] /_mozilla/css/canvas_over_area.html

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/style/properties.mako.rs, line 1341 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8321#-K2Guk2-hg5F0P4FUN_O)** ([raw file](https://github.com/servo/servo/blob/657e4f4b0ce8c115432ac6be7ae61dfe8259ee8c/components/style/properties.mako.rs#L1341)):</sup>
Does this need to be a pub use?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8321)

**Comment by SimonSapin** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/style/properties.mako.rs, line 1341 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8321#-K2Guk2-hg5F0P4FUN_O)** ([raw file](https://github.com/servo/servo/blob/657e4f4b0ce8c115432ac6be7ae61dfe8259ee8c/components/style/properties.mako.rs#L1341)):</sup>
It doesn’t. Fixed.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8321)

**Comment by Ms2ger** [comment]
@bors-servo r+

Thanks!


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8321)

**Comment by SimonSapin** [comment]
@bors-servo retry

#7787

**Pull request merged**
