### PR TITLE
[hololens] Gesture capture

### LINKED ISSUE #24010: [hololens] manipulation events trigger clicks/focus on regular controls
See https://github.com/servo/servo/pull/23981#issuecomment-522749381

### PR DESCRIPTION
**Pull request by paulrouget**
I can't reproduce #24010 but I think this should fix it.

Fix #24010

Depends on #24008

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24013)

### CODE REVIEW

**Comment by paulrouget** [comment]
> Can we return a unique_ptr so this is freed automatically?

I guess. As long as internally we don't store the str.

**Comment by paulrouget** [comment]
@Manishearth can you try this and tell me if the keyboard still shows up?

**Comment by Manishearth** [comment]
Don't have a device on me until September, @jdm will though

**Comment by paulrouget** [comment]
I can reproduce the focus issue in the simulator. This PR solves the problem.

**Pull request merged**
