### PR TITLE
Refactor style lengths per #13584

### LINKED ISSUE #13584: Split length values into their own file
[`components/style/values/computed/mod.rs`](https://github.com/servo/servo/blob/aea9545e16fd6ea4a6b1234d1b969457313a5fa7/components/style/values/computed/mod.rs) and [`components/style/values/specified/mod.rs`](https://github.com/servo/servo/blob/aea9545e16fd6ea4a6b1234d1b969457313a5fa7/components/style/values/specified/mod.rs) are huge. Those modules have submodules (`position` and `basic_shape`) for groups of CSS values related to particular properties, and we should add more.

A lot of the length-related stuff could be moved into a new module `length` in `values/specified/length.rs` (same for computed). Lengths are imported everywhere (and it's convenient to import directly from `style::values`, so we should reexport the moved types in `mod.rs` (via `pub use length::SomeType`).

The types that this would include would basically be anything in those files with `Length`, `Calc`, or `Percentage` in its name, as well as `CharacterWidth`. The `impl`s related to those would need to be moved too.

### PR DESCRIPTION
**Pull request by kivikakk**
Refactor `components/style/values/{computed,specified}/mod.rs` into `…/length.rs` per #13584.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13584

- [x] These changes do not require tests because the existing code should be covered by tests

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14077)

### CODE REVIEW

**Comment by kivikakk** [comment]
I had to make a few more things public to be accessible from the parent module (or vice-versa); not sure how I feel about that.

**Comment by emilio** [comment]
Hi, thanks for doing this!

This looks good to me, and even though I agree making some stuff public so the inner modules can access it is not great, it's not too bad (and it'll become better with the `pub restricted` thing eventually: https://github.com/rust-lang/rfcs/pull/1422).

I don't think we want to delay landing this PR given it's sort of prone to bitrot, thanks a bunch for doing this! :)

@bors-servo: r+

**Comment by emilio** [comment]
Ouch, this breaks the geckolib build, could you fix that? (should be easy, they're only warnings)

To test it you can do `./mach build-geckolib`.

Thanks!

**Comment by kivikakk** [comment]
@emilio; will do; thanks for the heads up!

**Comment by kivikakk** [comment]
Rebased with care, and gecko build fixed. 👍

**Comment by kivikakk** [comment]
AppVeyor gnu/msys build failed with:

```
CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 127
```

.. which is strange.

**Comment by emilio** [comment]
Yeah, don't bother about appveyor, we don't gate on it and it's been broken for a few days now. r=me, thanks again! :)

@bors-servo: r+

**Pull request merged**
