### PR TITLE
Update devices no bluetooth (do not merge!)

### PR DESCRIPTION
**Pull request by djc**
@larsbergstrom, please have a look later.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11812)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
`./mach build -d` seems to succeed here.

So does `./mach build -d --no-default-features --features="glutin_app"`, and as far as I can tell it didn't build in bluetooth.

What error are you seeing / do you want help correcting with this branch?

**Comment by djc** [comment]
It still seemed to build blurz for me, and error out linking it with dbus.

**Comment by larsbergstrom** [comment]
Hrm, I was unable to get this working either. Hopefully after I get us onto cargo workspaces (https://github.com/servo/servo/pull/12391), this can be retried and will be easier? Sorry I sat on this for so long!

**Comment by jdm** [comment]
https://github.com/rust-lang/cargo/issues/3024#issuecomment-241312148 suggests that more code changes are necessary here. Closing, since this appears to have a solution now.

**Pull request closed without merging**
