### PR TITLE
Cookie support

### PR DESCRIPTION
**Pull request by jdm**
As specified in http://tools.ietf.org/html/rfc6265. Requires https://github.com/servo/cookie-rs/pull/1. Tested against http://www.joshmatthews.net/cookie.php, http://www.html-kit.com/tools/cookietester/, https://github.com/login, and https://mobile.twitter.com/session/new .

### CODE REVIEW

**Comment by metajack** [comment]
Comments in critic. Next time let's squash rewrites before opening the PR; it makes it hard to review.

**Comment by jdm** [comment]
Well, it is also possible to squash in Critic by clicking and dragging across several commits.

**Comment by jdm** [comment]
But I appreciate the review, regardless :)

**Comment by metajack** [comment]
I guess the issue is that you don't know you should have done that until the first time you try to comment in a section that's been rewritten.

**Comment by jdm** [comment]
@jgraham There's a new commit here, but Critic's not picking it up despite claiming that it's tracking.

**Comment by jdm** [comment]
Note: I can't test github any more due to font-related layout panics, but twitter login is broken, so allow me to investigate that before trying to merge this.

**Comment by jdm** [comment]
Fixed; https://mobile.twitter.com/session/new will now allow you to log in to mobile twitter.

**Comment by metajack** [comment]
Almost there. A few notes in Critic.

**Pull request merged**
