### PR TITLE
Add `use-system-allocator` to not use jemalloc

### LINKED ISSUE #31442: Add ability to use system allocator (on systems that use jemalloc by default)
When building ASAN build, AddressSanitizer also replaces default system alloc so it can generate smarter reports but using jemalloc overrides it.

### PR DESCRIPTION
**Pull request by sagudev**
~~Add `jemalloc` feature that enables jemallocator on supported platforms ( not(windows, android) ). Features are additive and unified so this is the most natural way to do this without pulling jemallocator when it's not used.~~

Add `use-system-allocator` feature so we can disable jemallocator.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #31442 

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Review by mrobinson — COMMENTED** [review]
Instead of adding more default features, which makes life complicated -- can this be a non-default use-system-allocator feature that is only exposed on the allocator crate? Cargo allows enabling features of dependencies via the command-line: https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options

**Comment by sagudev** [comment]
> Instead of adding more default features, which makes life complicated -- can this be a non-default use-system-allocator feature that is only exposed on the allocator crate? Cargo allows enabling features of dependencies via the command-line: https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options

The problem is that features are additive, which means that if we do something like `use-system-allocator` we still pull jemallocator (so we cannot solve https://github.com/servo/servo/issues/310590).

**Comment by mrobinson** [comment]
It is fine to pull in the allocator as long as you make this code conditional on the feature, right?

```rust
#[global_allocator]
static ALLOC: Allocator = Allocator;
```

**Review by mrobinson — APPROVED** [review]
Thanks for the updates. This looks good to me.

**Pull request merged**
