### PR TITLE
Make CanvasRenderingContext2D.createPattern() return null for incomplete images

### PR DESCRIPTION
**Pull request by pylbrecht**
`createPattern()` should return `null` if the passed `image` argument is not usable.

References:
- https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-createpattern
- https://html.spec.whatwg.org/multipage/canvas.html#check-the-usability-of-the-image-argument
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #25331

- [x] There are tests for these changes

### CODE REVIEW

**Comment by pylbrecht** [comment]
These changes are based on https://github.com/servo/servo/pull/25675.

**Comment by pshaughn** [comment]
```
  ▶ Unexpected subtest result in /2dcontext/fill-and-stroke-styles/2d.pattern.image.broken.html:
  │ FAIL [expected PASS] Canvas test: 2d.pattern.image.broken
  │   → assert_throws_dom: function "function() { ctx.createPattern(img, 'repeat'); }" did not throw
  │ 
  │ @http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.broken.html:23:1
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  │ _addTest/</<@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:66:15
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  └ _addTest/<@http://web-platform.test:8000/2dcontext/resources/canvas-tests.js:63:11
```
Looks like this test is expecting a throw on an image it thinks is broken, and possibly getting the new null instead?

**Comment by pylbrecht** [comment]
`is_usable()` somehow returns *bad*, when it shouldn't, because `create_pattern()` returns before actually trying to fetch the image data, which should fail for `broken.png` and therefore lead to the desired result. Maybe we need to incorporate fetching the image data into `is_usable()` somehow.

It would be very helpful to know how `broken.png` is broken, so we can figure out why our checks fail.
I guess today is about looking at the image's bytes and learning how PNG works.

**Comment by pylbrecht** [comment]
> No one else is passing either, so probably the spec is right and the test is wrong https://wpt.fyi/results/2dcontext/fill-and-stroke-styles/2d.pattern.image.broken.html?label=experimental&label=master&aligned
I've never considered this an option. It would spare me the debugging though.

**Comment by pylbrecht** [comment]
I wasn't checking for a broken state in case the `current_request`'s image attribute is `None`. Hopefully the rewrite will still pass all the tests. 🤞

**Comment by pylbrecht** [comment]
```
1 unexpected results that are NOT known-intermittents:
  ▶ Unexpected subtest result in /2dcontext/drawing-images-to-the-canvas/2d.drawImage.broken.html:
  │ FAIL [expected PASS] Canvas test: 2d.drawImage.broken
  └   → The object is in an invalid state.
```
This is weird. It seems `createPattern()` and `drawImage()` need to be handled differently, although the spec links to the same [usability checks](https://html.spec.whatwg.org/multipage/canvas.html#check-the-usability-of-the-image-argument).

But maybe my implementation of `is_usable()` is missing something.

**Comment by pylbrecht** [comment]
Since looking at other browsers' behavior for reference seems the common thing to do, I'm a little lost on how to proceed.
Should we fail this test (like most other browsers) in favor of passing the `drawImage()` equivalent? Or is implementing two different usability checks for `createPattern()` and `drawImage()` the way to go?

**Comment by pylbrecht** [comment]
It seems `2d.pattern.broken.image.html` is wrong, so I will roll back to the previous changes that fail this test, but pass `2d.drawImage.broken.html`.
See https://github.com/guest271314/wpt/pull/10 for reference.

**Comment by jdm** [comment]
@bors-servo r+
Looks like a good improvement!

**Comment by jdm** [comment]
@bors-servo retry
* #24726 #25720

**Comment by jdm** [comment]
@bors-servo retry
#24726

**Pull request merged**
