### PR TITLE
Remove unnecessary `recv` in the constellation

### PR DESCRIPTION
**Pull request by cbrewster**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17505)

### CODE REVIEW

**Comment by cbrewster** [comment]
It seems like this is unnecessary since the old backend was removed.

Introduced in: https://github.com/servo/servo/commit/80675351b3195071bafac7b7af76c8bee9085ba4

old backend removed in: https://github.com/servo/servo/commit/acfdfd2fa98562c9f891fbee2dbc3424803c1a3c

r? @asajeffrey 
cc @glennw 

@bors-servo try

**Review by asajeffrey — COMMENTED** [review]
This will certainly increase concurrency, hopefully there's no new race conditions!

@glennw: there's no reason any more for the constellation to block on the compositor when seeing the frame tree is there?

Unless Glenn says otherwise, you can r=me.

**Comment by asajeffrey** [comment]
@glennw?

**Comment by glennw** [comment]
This seems reasonable to me, I can't think why it would be necessary now. Let's see if it changes intermittent rates I guess :)

@bors-servo r=asajeffrey,glennw

**Pull request merged**
