### PR TITLE
Remove expect calls in service worker manager thread

### PR DESCRIPTION
**Pull request by creativcoder**
An intermittent timeout was seen in #12516 , caused by panic of ServiceWorkerManager thread on reception of messages from resource thread. This PR amends things to not have the ServiceWorkerManager thread panic in such situation.
cc @jdm 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix ##12516 (github issue number if applicable).

- [X] These changes do not require tests because its an "intermittent fix"

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12518)

### CODE REVIEW

**Comment by nox** [comment]
Thanks for the contribution. I want a couple of changes but that's all.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/12518#-KN6_4n2TRrG4G8rZcDk:-KN6_4n2TRrG4G8rZcDl:1070170303) (no related file):*
It took me quite a bit of time to realise that it was about removing the two `expect` calls in `receive_message`.

Could you reword the commit message to make that crystal clear?

---

*[components/script/serviceworker_manager.rs, line 107 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12518#-KN6Z12Mco2lxEZMG4Kx:-KN6Z12Mco2lxEZMG4Ky:-1851978923) ([raw file](https://github.com/servo/servo/blob/701e678d8eac3ebab7309759988832932f89af56/components/script/serviceworker_manager.rs#L107)):*
> ```Rust
>        while self.receive_message() {
>         // process message
>        }
> ```

Please restore the two additional `handle_message` methods and do something like this:

```rust
fn handle_message(&mut self) {
    while let Ok(message) = self.receive_message() {
        let should_continue = match message {
            Message::FromConstellation(msg) => {
                self.handle_message_from_constellation(msg)
            },
            Message::FromResource(msg) => {
                self.handle_message_from_resource(msg)
            }
        };
        if !should_continue {
            break;
        }
    }
}
```

---

*[components/script/serviceworker_manager.rs, line 160 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12518#-KN6ZzgWhmPZ9vUQ_wf8:-KN6ZzgWhmPZ9vUQ_wf9:-108519444) ([raw file](https://github.com/servo/servo/blob/47fcb5a186cad19dc92223281b7bf6acaad0b310/components/script/serviceworker_manager.rs#L160)):*
> ```Rust
>         } else {
>             panic!("Unexpected select result");
>         }
> ```

I'm pretty sure you can continue to use `select!` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12518#-:-KN6_5EwPzZwW8d2Xn9B:-578444385)*

**Comment by creativcoder** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/12518#-KN6_4n2TRrG4G8rZcDk:-KN76EvJvSBuQLNoiSr9:676635175) (no related file):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> It took me quite a bit of time to realise that it was about removing the two `expect` calls in `receive_message`.
> 
> Could you reword the commit message to make that crystal clear?
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12518)*

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

One last nit and I'll r+ it. Thanks again!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/serviceworker_manager.rs, line 163 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12518#-KNCPy5P7zoeMlVeuRCL:-KNCPy5P7zoeMlVeuRCM:-1835140998) ([raw file](https://github.com/servo/servo/blob/6e89a7b4a86877570f8d379928c9c4c791c0d0bc/components/script/serviceworker_manager.rs#L163)):*
> ```Rust
>         select! {
>             msg = msg_from_constellation.recv() => Ok(Message::FromConstellation(try!(msg))),
>             msg = msg_from_resource.recv() => Ok(Message::FromResource(try!(msg)))
> ```

Nit: for these you can write `msg.map(Message::FromConstellation)` and `msg.map(Message::FromResource)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12518#-:-KNCQ5wA5J2h5TG7qzO0:-962719481)*

**Comment by nox** [comment]
bors-servo r+

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12518#-:-KNCySXMSNMAJOezT-G6:-1407063270)*

**Comment by nox** [comment]
...

@bors-servo r+

**Pull request merged**
