### PR TITLE
Add FileReaderSync skeleton

### PR DESCRIPTION
**Pull request by izgzhen**
Add a FileReaderSync interface skeleton, no concrete implementation yet.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12663)

### CODE REVIEW

**Comment by izgzhen** [comment]
The interface is easy to write, but I am thinking how much code-sharing can be achieved between this and `filereader.rs`

**Comment by izgzhen** [comment]
I am not very clear what happened in the failed test :$

**Comment by Manishearth** [comment]
Oh, just edit that test and add FileReaderSync to the list of exposed interfaces

**Comment by izgzhen** [comment]
@bors-servo retry

test updated

**Comment by Ms2ger** [comment]
Does the interfaces.html failure message no longer specify who can review those changes?

**Comment by izgzhen** [comment]
> Do not make a change to this file without review from jdm or Ms2ger for that specific change! 

Oops.

**Pull request merged**
