### PR TITLE
Add libxcb dependencies to README and bootstrap.py

### LINKED ISSUE #27327: Need libxcb-composite0-dev
On Ubuntu 20.04, I got a linker error with

```
  = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
```

This was fixed by installing libxcb-composite0-dev

I'm not sure if this dependency is also necessary on 18.04.

### PR DESCRIPTION
**Pull request by asajeffrey**
Gets servo to build on Ubuntu xenial+ again.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #27327
- [x] These changes do not require tests because it's fixing build breakage

### CODE REVIEW

**Comment by CYBAI** [comment]
@bors-servo retry

- #26895

**Comment by CYBAI** [comment]
@bors-servo retry

- #26895

**Comment by asajeffrey** [comment]
@bors-servo retry
- #27315

**Pull request merged**
