### PR TITLE
layout: Take margins in the inline direction into account when guessing the inline-size of block formatting contexts.

### PR DESCRIPTION
**Pull request by pcwalton**
Fixes the layout on reddit.com.

Partially addresses #10571.

r? @mbrubeck

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11125)

### CODE REVIEW

**Comment by mbrubeck** [comment]
r=mbrubeck (waiting for try)

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :hourglass: Trying commit b6bed34 with merge 105912b...</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11125#-:-KHSEnRqkJ1a71mA1lVE:-1614390061)*

**Comment by emilio** [comment]
@bors-servo: retry
 * https://github.com/servo/servo/issues/11100

**Pull request merged**
