### PR TITLE
added unit tests for TextInput - fixes #4352

### LINKED ISSUE #4352: Write unit tests for TextInput
It occurs to me that it should be very easy to test that component in isolation. Let's do that; there have been lots of edge cases discovered that we should avoid regressing in the future.

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Please bear with me. This is the first Rust code I've ever written and the first systems programming language I've ever used.

I've added unit tests for all methods of TextInput ( - except `handle_keydown`). I probably didn't cover all cases - I don't know if this is a real requirement until we have some coverage tools which identify all missing cases easily.
If someone could show me how to create a `KeyboardEvent` easily I could add another test for `handle_keydown`.

Other questions:
1. Running `$ time ./mach test-unit -c script test_textinput` takes `3m29.536s` on my MacBook Pro (2012). Any hints on speeding this up?
2. Who is responsible for the feedback of the unit tests? It would be nice if the output could be colored (e.g. make `11 passed;` green, `0 failed;` red and so on.)

### CODE REVIEW

**Comment by jdm** [comment]
Great! Creating KeyboardEvent values won't be possible, unfortunately, since they're so tied up with the JavaScript engine and garbage collection. If we do want to test things like handle_keydown, we would probably want to extract its contents to a function that just takes the needed values from KeyboardEvent as arguments. That is probably a valuable thing to do so we get full coverage.

**Comment by jdm** [comment]
@donaldpipowitch Looking good! I've left comments on Critic; be sure to click the "sign in" link there so you receive future updates by email. In general I'd like to avoid directly modifying the internals of TextInput and add any missing APIs to perform the equivalent actions (such as initiating a selection, or moving the cursor around).

**Comment by donaldpipowitch** [comment]
Not sure if this is expected in `test_textinput_set_content`: We have the String `"abc\nf"`, make a selection of `"abc"`, replace the content with `"de"` and `edit_point.index` will be `1`. I would expect `0` as the beginning of `"de"` or `2` as the end of `"de"`.

**Comment by jdm** [comment]
Agreed, I would expect the edit point to be 2 in that case. Feel free to file an issue and leave a commented out test :)

**Comment by donaldpipowitch** [comment]
Open an issue. Should I comment out the test now to get this merged or can it stay there and should be updated when #4622 is solved?

**Comment by jdm** [comment]
Add the expected value to the assert_eq and comment it out (since it will no longer pass), referencing the new issue, please!

**Comment by Ms2ger** [comment]
Can we keep the assertion in, testing the current behaviour, with a note that it's not what we thing is right? Then we'll at least notice if it gets fixed.

**Comment by donaldpipowitch** [comment]
I think both ways would be okay. One of you two needs to decide this. For me it would be fine if it would be merged the way it is now :)

**Comment by jdm** [comment]
Ok, let's uncomment the assertion and add back the incorrect value. Sorry to flip flop like this!

**Comment by donaldpipowitch** [comment]
I hope everything is fine now :)

**Comment by jdm** [comment]
Great! Please squash and we'll merge these changes :)

**Comment by donaldpipowitch** [comment]
:)

**Comment by jdm** [comment]
Thanks @donaldpipowitch!

**Comment by donaldpipowitch** [comment]
What's up with the failing tests?

**Comment by jdm** [comment]
Ah, you ran afoul of the changes to make adjust_horizontal/adjust_vertical take enum arguments instead of booleans. It's not failing tests; the tests just don't compile now. See all the lines of
```
textinput.rs:373:36: 373:41 error: mismatched types: expected `textinput::Selection`, found `bool` (expected enum textinput::Selection, found bool)
textinput.rs:373     textinput.adjust_horizontal(2, false);
                                                    ^~~~~
```
at the bottom of the logs.

**Comment by donaldpipowitch** [comment]
So after `git pull upstream master` in master and `git rebase master` I now get the following compile error multiple times:

````
task 'rustc' panicked at 'assertion failed: end <= self.len()', /Users/larsberg/rust/src/libcore/slice.rs:432
````

**Comment by jdm** [comment]
You'll want a `./mach clean`; there's some stale compiled data lying around that's interfering with your build.

**Comment by donaldpipowitch** [comment]
Thanks. Should be fixed now.

**Pull request merged**
