### PR TITLE
Added liblzma-dev dependency on Debian

### PR DESCRIPTION
**Pull request by asajeffrey**
This fixes a link error on Debian Linux 
```
  = note: /usr/bin/ld.gold: error: cannot find -llzma
          collect2: error: ld returned 1 exit status
```

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because it's a README

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23248)

### CODE REVIEW

**Comment by jdm** [comment]
Could you update https://github.com/servo/servo/blob/54f54d194df1911d1dd35a82dd87331853f985a3/python/servo/bootstrap.py#L110 as well?

**Comment by asajeffrey** [comment]
Done.

**Comment by asajeffrey** [comment]
One of the taskcluster Mac runs timed out:
```
[taskcluster:error] Aborting task...
[taskcluster 2019-04-24T01:35:16.891Z] === Task Finished ===
[taskcluster 2019-04-24T01:35:16.892Z] Task Duration: 1h0m0.03685367s
[taskcluster 2019-04-24T01:35:17.743Z] Uploading artifact public/test-wpt-mp.log from file repo/test-wpt-mp.log with content encoding "gzip", mime type "text/plain" and expiry 2020-04-22T23:55:09.914Z
[taskcluster 2019-04-24T01:35:18.741Z] Uploading artifact public/wpt-mp-errorsummary.log from file repo/wpt-mp-errorsummary.log with content encoding "gzip", mime type "text/plain" and expiry 2020-04-22T23:55:09.914Z
[taskcluster 2019-04-24T01:35:19.120Z] Uploading artifact public/test-wpt.log from file repo/test-wpt.log with content encoding "gzip", mime type "text/plain" and expiry 2020-04-22T23:55:09.914Z
[taskcluster 2019-04-24T01:35:27.915Z] Uploading artifact public/wpt-errorsummary.log from file repo/wpt-errorsummary.log with content encoding "gzip", mime type "text/plain" and expiry 2020-04-22T23:55:09.914Z
[taskcluster 2019-04-24T01:35:28.360Z] Uploading artifact public/wpt-errorsummary.log from file repo/wpt-errorsummary.log with content encoding "gzip", mime type "text/plain" and expiry 2020-04-22T23:55:09.914Z
[taskcluster:error] Uploading error artifact public/intermittents.log from file repo/intermittents.log with message "Could not read file '/Users/worker/tasks/task_1556066072/repo/intermittents.log'", reason "file-missing-on-worker" and expiry 2020-04-22T23:55:09.914Z
[taskcluster:error] TASK FAILURE during artifact upload: file-missing-on-worker: Could not read file '/Users/worker/tasks/task_1556066072/repo/intermittents.log'
[taskcluster:error] Uploading error artifact public/filtered-wpt-errorsummary.log from file repo/filtered-wpt-errorsummary.log with message "Could not read file '/Users/worker/tasks/task_1556066072/repo/filtered-wpt-errorsummary.log'", reason "file-missing-on-worker" and expiry 2020-04-22T23:55:09.914Z
[taskcluster:error] TASK FAILURE during artifact upload: file-missing-on-worker: Could not read file '/Users/worker/tasks/task_1556066072/repo/filtered-wpt-errorsummary.log'
[taskcluster 2019-04-24T01:35:29.628Z] Uploading redirect artifact public/logs/live.log to URL https://queue.taskcluster.net/v1/task/Mhgo87xbTwqDJTz2i6dc7g/runs/0/artifacts/public/logs/live_backing.log with mime type "text/plain; charset=utf-8" and expiry 2020-04-22T23:55:09.914Z
[taskcluster:error] Task aborted - max run time exceeded
```

@bors-servo retry

**Comment by CYBAI** [comment]
@bors-servo retry

-  #22955

**Pull request merged**
