### PR TITLE
Draw shadows after the background.

### LINKED ISSUE #7872: inner shadows are drawn behind the background instead of above
```html
<div></div>

<style>
  div {
    width: 100px;
    height: 100px;
    box-shadow: inset 0 20px 0 0 red;
    background-color: rgba(0,0,0,0.7);
  }
</style>
```

screen shot 2015-10-05 at 15 49 13

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #7872

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7883)

### CODE REVIEW

**Comment by notriddle** [comment]
That timeout doesn't occur when I run the test myself.

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Comment by jdm** [comment]
@bors-servo: retry
* #7870

**Pull request merged**
