### PR TITLE
Enable more CSS fonts tests

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11311)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo try

I want to see what happens if we address https://github.com/servo/servo/pull/8374#issuecomment-191062480.

**Comment by jdm** [comment]
That looks like a much more reasonable set of failures!

**Comment by jdm** [comment]
Especially since that test relies on the ahem font that's being deleted in this PR.

**Comment by nox** [comment]
@bors-servo try

@jdm Is it good enough to merge? What should we do about mime_sniffing_font_context.html?

**Comment by jdm** [comment]
@nox we should modify the test to rely on a font that isn't removed in this PR.

**Comment by larsbergstrom** [comment]
```
Tests with unexpected results:
  ▶ FAIL [expected PASS] /css-fonts-3_dev/html/fonts-012.htm
  └   → /css-fonts-3_dev/html/fonts-012.htm b8b65868ebce8e1c27e5cb9b3a45d4616c37eb10
/css-fonts-3_dev/html/reference/fonts-012-ref.htm 77ee766668bb5ce95d0e5549c1de5fd851494d96
Testing b8b65868ebce8e1c27e5cb9b3a45d4616c37eb10 == 77ee766668bb5ce95d0e5549c1de5fd851494d96
```
(the other failures were infra intermittents)

**Comment by nox** [comment]
Also on linux-rel:

```
Tests with unexpected results:
  ▶ TIMEOUT [expected OK] /XMLHttpRequest/send-entity-body-document.htm
  │ 
  └ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".

  ▶ TIMEOUT [expected OK] /html/browsers/windows/nested-browsing-contexts/frameElement.sub.html
  │ 
  └ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".

  ▶ TIMEOUT [expected OK] /html/dom/documents/dom-tree-accessors/nameditem-02.html
  │ 
  └ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".

  ▶ TIMEOUT [expected OK] /html/infrastructure/urls/terminology-0/document-base-url.html
  │ 
  └ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".

  ▶ TIMEOUT [expected OK] /html/semantics/embedded-content/the-iframe-element/iframe-allowfullscreen.html
  │ 
  └ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".

  ▶ TIMEOUT [expected OK] /html/syntax/parsing/html5lib_innerHTML_tests6.html
  │ 
  └ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".

  ▶ TIMEOUT [expected OK] /html/syntax/parsing/html5lib_innerHTML_tests_innerHTML_1.html
  │ 
  └ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".

  ▶ TIMEOUT [expected OK] /html/syntax/parsing/html5lib_innerHTML_tests7.html
  │ 
  └ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
```

```
Tests with unexpected results:
  ▶ FAIL [expected PASS] /css-fonts-3_dev/html/fonts-012.htm
  └   → /css-fonts-3_dev/html/fonts-012.htm b8b65868ebce8e1c27e5cb9b3a45d4616c37eb10
/css-fonts-3_dev/html/reference/fonts-012-ref.htm 77ee766668bb5ce95d0e5549c1de5fd851494d96
Testing b8b65868ebce8e1c27e5cb9b3a45d4616c37eb10 == 77ee766668bb5ce95d0e5549c1de5fd851494d96
```

**Comment by jdm** [comment]
Tracking this work in https://github.com/servo/servo/issues/15275. Closing because it doesn't appear to be going anywhere.

**Pull request closed without merging**
