### PR TITLE
Remove unnecessary clone from ServiceWorkerManager::prepare_activation

### LINKED ISSUE #12999: Remove unnecessary clone from ServiceWorkerManager::prepare_activation
Right before returning from `prepare_activation`, we clone `scope_url` and pass the result to a function. This is redundant; we should be able to pass `scope_url` without cloning it.

Code: `components/script/serviceworker_manager.rs`

No need for automated tests; if it builds, it's good enough for a PR.

Note: This is reserved for the upcoming Taiwan Code Sprint; please do not work on it.

### PR DESCRIPTION
**Pull request by wdv4758h**
remove unnecessary for `scope_url`
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12999 
- [X] These changes do not require tests because it should works when it compiles

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13076)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by izgzhen** [comment]
I don't see why this will fail... @jdm idea?

```
{"status": "TIMEOUT", "line": 20933, "subtest": null, "action": "test_result", "test": "/XMLHttpRequest/send-usp.worker", "message": null, "stack": null, "expected": "OK"}
```

**Comment by KiChjang** [comment]
```
Ran 6850 tests finished in 2126.0 seconds.
  • 6849 ran as expected. 1660 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected OK] /XMLHttpRequest/send-usp.worker
  │ 
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
  │ stack backtrace:
  │    0:        0x110b5469e - backtrace::backtrace::trace::h22a738598d75d447
  │    1:        0x110b549ac - backtrace::capture::Backtrace::new::h1a277804460ccff5
  │    2:        0x10f2a0898 - servo::install_crash_handler::handler::h7d01d896c8f0d15d
  │    3:     0x7fff9852df19 - _sigtramp
  │    4:        0x110197e3f - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleIP8JSObjectEENS2_6HandleIS5_E
  │    5:        0x1101757dd - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleINS2_5ValueEEENS2_6HandleIP8JSObjectE
  │    6:        0x11015c644 - _Z12JS_WrapValueP9JSContextN2JS13MutableHandleINS1_5ValueEEE
  │    7:        0x10f7a8ac8 - std::panicking::try::do_call::h7f1663ddafd7ad43
  │    8:        0x110beb22a - __rust_maybe_catch_panic
  │    9:        0x10fa849d7 - script::dom::bindings::codegen::Bindings::MessageEventBinding::MessageEventBinding::get_data::h9dcb7acd957cbcbf
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
  │ stack backtrace:
  │    0:        0x110b5469e - backtrace::backtrace::trace::h22a738598d75d447
  │    1:        0x110b549ac - backtrace::capture::Backtrace::new::h1a277804460ccff5
  │    2:        0x10f2a0898 - servo::install_crash_handler::handler::h7d01d896c8f0d15d
  │    3:     0x7fff9852df19 - _sigtramp
  │    4:        0x10f2a091c - servo::install_crash_handler::handler::h7d01d896c8f0d15d
  │    5:     0x7fff9852df19 - _sigtramp
  │    6:        0x110197e3f - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleIP8JSObjectEENS2_6HandleIS5_E
  │    7:        0x1101757dd - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleINS2_5ValueEEENS2_6HandleIP8JSObjectE
  │    8:        0x11015c644 - _Z12JS_WrapValueP9JSContextN2JS13MutableHandleINS1_5ValueEEE
  │    9:        0x10f7a8ac8 - std::panicking::try::do_call::h7f1663ddafd7ad43
  │   10:        0x110beb22a - __rust_maybe_catch_panic
  └   11:        0x10fa849d7 - script::dom::bindings::codegen::Bindings::MessageEventBinding::MessageEventBinding::get_data::h9dcb7acd957cbcbf
```

**Comment by KiChjang** [comment]
@bors-servo retry
* #12654

**Pull request merged**
