### PR TITLE
Splitting ScriptMsg into various enums...

### PR DESCRIPTION
**Pull request by ghost**
... for #3734, which is also one of the oldest issues. (/cc @jdm)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7006)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
OIC (fixing)...

**Comment by Wafflespeanut** [comment]
@jdm r?

**Comment by Ms2ger** [comment]
Could you add a commit on top of this that puts a `Receiver<WorkerScriptMsg>` in `DedicatedWorkerGlobalScope`? That should help evaluate whether this is an improvement.

**Comment by jdm** [comment]
Note; the WorkerScriptMsg/MainThreadScriptMsg enums will have to contain Common, rather than having them all part of the same enum.

**Comment by Wafflespeanut** [comment]
@jdm (just a commit for showing the progress) r?

**Comment by Wafflespeanut** [comment]
@jdm r?

**Comment by Wafflespeanut** [comment]
Oh yeah, great... -_-

**Comment by Wafflespeanut** [comment]
(resolved conflicts) @jdm r?

**Comment by jdm** [comment]
This is a great improvement! We might even be able to fix the problems with ScriptPort by playing around a bit more as I've suggested.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/global.rs, line 161 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7006#-JwgfCdmi0XXICJw_dwE)** ([raw file](https://github.com/servo/servo/blob/2cbd0ac06127dc4b123a001b45995349bd23c01c/components/script/dom/bindings/global.rs#L161)):</sup>
I would prefer if callers would call as_window instead of adding this new method.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7006#-JwgfPEngQcm39p2774Q)** ([raw file](https://github.com/servo/servo/blob/2cbd0ac06127dc4b123a001b45995349bd23c01c/components/script/dom/dedicatedworkerglobalscope.rs#L52)):</sup>
The comment about "only dispatched to" isn't necessary any more :)

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 61 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7006#-Jwgh2BRnt_K4kv3Cm3k)** ([raw file](https://github.com/servo/servo/blob/2cbd0ac06127dc4b123a001b45995349bd23c01c/components/script/dom/dedicatedworkerglobalscope.rs#L61)):</sup>
I actually suspect that this could be CommonScriptMsg, given the way this struct is used. That would fix the problem with ScriptPort, too.

---

<sup>**[components/script/dom/storage.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7006#-JwghnJwHuYjqu6UnB75)** ([raw file](https://github.com/servo/servo/blob/2cbd0ac06127dc4b123a001b45995349bd23c01c/components/script/dom/storage.rs#L150)):</sup>
Use as_window instead.

---

<sup>**[components/script/dom/window.rs, line 238 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7006#-Jwgi3kyeeedw6frR7wp)** ([raw file](https://github.com/servo/servo/blob/2cbd0ac06127dc4b123a001b45995349bd23c01c/components/script/dom/window.rs#L238)):</sup>
Let's make this return &Sender instead of cloning each time.

---

<sup>**[components/script/dom/worker.rs, line 54 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7006#-JwgiEVeaeZzHwbvoUng)** ([raw file](https://github.com/servo/servo/blob/2cbd0ac06127dc4b123a001b45995349bd23c01c/components/script/dom/worker.rs#L54)):</sup>
nit: indent this to match `global`.

---

<sup>**[components/script/dom/worker.rs, line 63 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7006#-JwgiHKNcht546HFiuWu)** ([raw file](https://github.com/servo/servo/blob/2cbd0ac06127dc4b123a001b45995349bd23c01c/components/script/dom/worker.rs#L63)):</sup>
nit: indent this to match `global`.

---

<sup>**[components/script/script_task.rs, line 253 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7006#-JwgihLujJ5B6G9u6r1K)** ([raw file](https://github.com/servo/servo/blob/2cbd0ac06127dc4b123a001b45995349bd23c01c/components/script/script_task.rs#L253)):</sup>
Out of curiosity, what if we make this `Sender<CommonScriptMsg>`, and store `Sender<MainThreadScriptMsg>` values in places that currently store `NonWorkerScriptChan` values (like `Window` and `ScriptTask`).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7006)

**Comment by Wafflespeanut** [comment]
@jdm r?

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 6 of 6 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7006)

**Pull request merged**
