### PR TITLE
Update rust-selectors

### PR DESCRIPTION
**Pull request by SimonSapin**
r? @Ms2ger

https://github.com/servo/rust-selectors/pull/33

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6468)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/layout/css/matching.rs, line 230 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskTR3j7cfk_SqH4gRE)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/css/matching.rs#L230)):</sup>
`let element = match...`

---

<sup>**[components/layout/css/matching.rs, line 508 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskU0a6FNq_CMYfm7i-)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/css/matching.rs#L508)):</sup>
Followup to implement this on Element instead?

---

<sup>**[components/layout/css/matching.rs, line 510 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskTlysnW7fls4cTZuk)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/css/matching.rs#L510)):</sup>
`match parent_node.as_element()`?

---

<sup>**[components/layout/wrapper.rs, line 71 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskVOclXO-lC1deDcAZ)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/wrapper.rs#L71)):</sup>
Unused

---

<sup>**[components/layout/wrapper.rs, line 251 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskUr5j-wy45A_sS_Fy)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/wrapper.rs#L251)):</sup>
Not anymore

---

<sup>**[components/layout/wrapper.rs, line 255 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskUeZ_bszLZ2T7zNyU)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/wrapper.rs#L255)):</sup>
`.map()`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6468)

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/layout/css/matching.rs, line 230 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskTR3j7cfk_SqH4gRE)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/css/matching.rs#L230)):</sup>
Done.

---

<sup>**[components/layout/css/matching.rs, line 508 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskU0a6FNq_CMYfm7i-)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/css/matching.rs#L508)):</sup>
https://github.com/servo/servo/issues/6476

---

<sup>**[components/layout/css/matching.rs, line 510 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskTlysnW7fls4cTZuk)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/css/matching.rs#L510)):</sup>
`parent_node` as that point is `Option<LayoutNode>`, we can’t call `as_element` on it yet.

---

<sup>**[components/layout/wrapper.rs, line 71 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskVOclXO-lC1deDcAZ)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/wrapper.rs#L71)):</sup>
It is used to call methods like `prev_sibling`.

---

<sup>**[components/layout/wrapper.rs, line 251 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskUr5j-wy45A_sS_Fy)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/wrapper.rs#L251)):</sup>
Fixed.

---

<sup>**[components/layout/wrapper.rs, line 255 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6468#-JskUeZ_bszLZ2T7zNyU)** ([raw file](https://github.com/servo/servo/blob/ad0a84ab8acafad6f94f052bc0695ec30360d7b9/components/layout/wrapper.rs#L255)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6468)

**Comment by Ms2ger** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6468)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6468)

**Pull request merged**
