### PR TITLE
Add HTTP compression

### PR DESCRIPTION
**Pull request by mattnenterprise**

### CODE REVIEW

**Comment by jdm** [comment]
Nice work! I've left a few comments on Critic.

**Comment by jdm** [comment]
Two small issues left :)

**Comment by jdm** [comment]
Go ahead and squash these changes!

**Comment by mattnenterprise** [comment]
Ok got it.

**Comment by jdm** [comment]
```
/XMLHttpRequest/response-data-gzip.htm
--------------------------------------
PASS expected FAIL XMLHttpRequest: GZIP response was correctly inflated
```
```
/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-0.2.0/src/lib.rs:33:1: 33:33 error: can't find crate for `ffi`
/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-0.2.0/src/lib.rs:33 extern crate "miniz-sys" as ffi;
                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The latter is from the CEF build, which can be replicated using `./mach build-cef`.

**Comment by mattnenterprise** [comment]
@jdm So the response-data-gzip.htm test passed but it was expected to fail? Also I don't quite understand what is happening with the CEF build err.

**Comment by jdm** [comment]
The test failure is because the test is currently annotated to fail in Servo right now (http://mxr.mozilla.org/servo/source/tests/wpt/metadata/XMLHttpRequest/response-data-gzip.htm.ini), and your changes invalidate that. You should remove that ini file now, since it contains no more test annotations once removing this one.

As for the CEF error, that's... mysterious.

**Comment by metajack** [comment]
Are you able to build CEF on master successfully? i.e. are you able to reproduce that failure locally?

**Comment by mattnenterprise** [comment]
I can reproduce the failure on my branch locally.

**Comment by jdm** [comment]
Me too, and strangely enough the flate2-rs clone that Cargo downloaded doesn't contain the miniz-sys folder that's present in https://github.com/alexcrichton/flate2-rs/tree/88cb8cfc12bd5990d846851482b83450822f8703 . I'm super confused.

**Comment by jdm** [comment]
Aha, I figured it out! For some reason the cef/Cargo.lock uses a version of flate2 that depends on miniz-sys 0.1.4, whereas all of the other ones use miniz-sys 0.1.3. If you use `./mach update-cargo -p miniz-sys --precise 0.1.3` the build will succeed.

**Comment by mattnenterprise** [comment]
@jdm It should work now.

**Pull request merged**
