### PR TITLE
Make tasks easier to find in Treeherder

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
https://treeherder.mozilla.org/#/jobs?repo=servo-try&revision=dd1cdf51eafece0c83663a68a0db6012fe3fa0e3

**Comment by SimonSapin** [comment]
```
  ▶ PASS [expected FAIL] /css/css-text-decor/text-decoration-skip-ink-sidewaysrl-001.html
```

Possibly https://github.com/servo/servo/issues/19085?

@bors-servo retry

**Comment by jdm** [comment]
@bors-servo retry
* #24726 #24297

**Pull request merged**
