### PR TITLE
Implement Range#surroundContents

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7426)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

Just a small performance nit and LGTM.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 681 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7426#-JxyinaGZvjyQCKqQf2C)** ([raw file](https://github.com/servo/servo/blob/d545802db3b7c802445087f8cafd5366ff403586/components/script/dom/range.rs#L681)):</sup>
AFAICT, if a Text node is partially-contained in a range, it means it is either its start node or its end node, but not both of them. You don't actually need to check every inclusive ancestors because a Text node can't have children.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7426)

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 681 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7426#-JxyinaGZvjyQCKqQf2C)** ([raw file](https://github.com/servo/servo/blob/d545802db3b7c802445087f8cafd5366ff403586/components/script/dom/range.rs#L681)):</sup>
I'm not sure I understand what you're proposing. We have to throw an error if there is any non-Text node that is partially contained. I understand that a Text node can't have children, but we can have a document with 0 text nodes and a partially contained ancestor of start. So how would not checking all the ancestors be correct?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7426)

**Comment by nox** [comment]
bors-servo r+

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 681 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7426#-JxyinaGZvjyQCKqQf2C)** ([raw file](https://github.com/servo/servo/blob/d545802db3b7c802445087f8cafd5366ff403586/components/script/dom/range.rs#L681)):</sup>
Apparently I can't read. I read that step as "If a Text node, (…)". LGTM.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7426)

**Comment by nox** [comment]
@bors-servo r+

Computering is hard.

**Comment by nox** [comment]
```
Unexpected Results
==================

/dom/interfaces.html
--------------------
PASS expected FAIL Range interface: operation surroundContents(Node)
PASS expected FAIL Range interface: document.createRange() must inherit property "surroundContents" with the proper type (24)
PASS expected FAIL Range interface: calling surroundContents(Node) on document.createRange() with too few arguments must throw TypeError
PASS expected FAIL Range interface: detachedRange must inherit property "surroundContents" with the proper type (24)
PASS expected FAIL Range interface: calling surroundContents(Node) on detachedRange with too few arguments must throw TypeError
```

**Pull request merged**
