### PR TITLE
Fix libffi pkg-config in WPT nightly job.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23374)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I don’t mind landing this, but why is this needed here but not in `macos_wpt` tasks?

**Comment by jdm** [comment]
The answer may be that we're just not running any tests that involve media elements yet. I'll see if it makes any difference for #23355.

**Comment by SimonSapin** [comment]
Is the set of tests that are run for the daily WPT update not the same as for gating PRs? Should it be?

**Comment by SimonSapin** [comment]
Ah sorry, you meant the media tests might happen to be in chunks that are still run on buildbot.

**Comment by jdm** [comment]
Let's merge this so we get a working nightly tonight.
@bors-servo r=SimonSapin

**Comment by CYBAI** [comment]
It's servo/intermittent-failure-tracker#5

**Pull request merged**
