### PR TITLE
Bug 1350140: stylo: Implement all the remaining state pseudo-classes.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16177)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo p=10

 * Needs a fair amount of changes in the Gecko side, so I need to be around for that.

**Comment by jdm** [comment]
```
---- size_of::size_div stdout ----
	thread 'size_of::size_div' panicked at 'Your changes have increased the stack size of commonly used DOM struct HTMLDivElement from 328 to 336. These structs are present in large quantities in the DOM, and increasing the size may dramatically affect our memory footprint. Please consider choosing a design which avoids this increase. If you feel that the increase is necessary, update to the new size in tests/unit/script/size_of.rs.', C:\buildbot\slave\windows-msvc-dev\build\tests\unit\script\size_of.rs:36
---- size_of::size_element stdout ----
	thread 'size_of::size_element' panicked at 'Your changes have increased the stack size of commonly used DOM struct Element from 312 to 320. These structs are present in large quantities in the DOM, and increasing the size may dramatically affect our memory footprint. Please consider choosing a design which avoids this increase. If you feel that the increase is necessary, update to the new size in tests/unit/script/size_of.rs.', C:\buildbot\slave\windows-msvc-dev\build\tests\unit\script\size_of.rs:34
---- size_of::size_htmlelement stdout ----
	thread 'size_of::size_htmlelement' panicked at 'Your changes have increased the stack size of commonly used DOM struct HTMLElement from 328 to 336. These structs are present in large quantities in the DOM, and increasing the size may dramatically affect our memory footprint. Please consider choosing a design which avoids this increase. If you feel that the increase is necessary, update to the new size in tests/unit/script/size_of.rs.', C:\buildbot\slave\windows-msvc-dev\build\tests\unit\script\size_of.rs:35
---- size_of::size_span stdout ----
	thread 'size_of::size_span' panicked at 'Your changes have increased the stack size of commonly used DOM struct HTMLSpanElement from 328 to 336. These structs are present in large quantities in the DOM, and increasing the size may dramatically affect our memory footprint. Please consider choosing a design which avoids this increase. If you feel that the increase is necessary, update to the new size in tests/unit/script/size_of.rs.', C:\buildbot\slave\windows-msvc-dev\build\tests\unit\script\size_of.rs:37
```

**Comment by emilio** [comment]
I updated the flags, we could conditionally compile the flags to take less space I guess, but servo will eventually need some if not all of them... @jdm mind signing off the last commit? (or alternatively, tell me if I should just conditionally compile ElementFlags?)

**Pull request merged**
