### PR TITLE
Add RwLock in more Arc’d things in stylesheets.

### PR DESCRIPTION
**Pull request by SimonSapin**
CSSOM needs hold potentially multiple references (through `Arc`) to these objects, and then mutate them.

CC @upsuper 
r? @mbrubeck 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13839)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo r+

Note (for future reference): @bholley filed https://bugzilla.mozilla.org/show_bug.cgi?id=1311469 to track investigation of perf impact from this and related changes.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13839#-:-KUUG7AAxmPCkJuP414D:b-ksp71h)*

**Comment by SimonSapin** [comment]
```
'cat' is not recognized as an internal or external command,
operable program or batch file.
```

@bors-servo retry

* Ms2ger says on IRC "I think that's fixed in master saltfs"

**Comment by SimonSapin** [comment]
https://github.com/servo/saltfs/pull/514

**Comment by SimonSapin** [comment]
```
./mach test-stylo --release
	thread 'gecko_bindings::structs::bindgen_test_layout_nsIDocument' panicked at 'assertion failed: `(left == right)` (left: `952`, right: `944`)', /home/servo/buildbot/slave/linux-rel-css/build/components/style/gecko_bindings/structs_release.rs:3165
```

I can reproduce this… but I can also reproduce on master.

**Comment by SimonSapin** [comment]
@bors-servo retry

* #13847

**Comment by SimonSapin** [comment]
@bors-servo retry

* #13360

**Pull request merged**
