### PR TITLE
Update raqote and associated dependencies

### PR DESCRIPTION
**Pull request by atouchet**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by atouchet** [comment]
`▶ Unexpected subtest result in /html/canvas/element/path-objects/2d.path.arc.shape.1.html:
│ FAIL [expected PASS] arc() from 0 to pi does not draw anything in the wrong half
│   → assert_equals: Red channel of the pixel at (20, 48) expected 0 but got 63`

These canvas tests look related.

**Comment by atouchet** [comment]
Had an issue with a change. @jdm can you re-try?

**Comment by atouchet** [comment]
The test failures appear to have been due to updating lyon_geom so I reverted that bump. I think this should be good to go now.

**Comment by jdm** [comment]
@bors-servo r+
It sounds like we should file an issue on lyon_geom.

**Pull request merged**
