### PR TITLE
do a second pass on the style sharing cache after computing the rule node

### PR DESCRIPTION
**Pull request by bholley**
https://bugzilla.mozilla.org/show_bug.cgi?id=1397976

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18496)

### CODE REVIEW

**Comment by bholley** [comment]
@bors-servo retry

CRASH [expected OK] /html/syntax/parsing/html5lib_template.html?run_type=uri
panic in webrender_api::api::RenderApiSender::create_api

**Comment by jdm** [comment]
That's #13480.

**Comment by jfkthame** [comment]
This appears to have caused a regression in Firefox nightly: https://bugzilla.mozilla.org/show_bug.cgi?id=1401317

**Pull request merged**
