### PR TITLE
Sync WebIDL.py with gecko

### LINKED ISSUE #23703: Implement the new syntax (= {}) for dictionary defaulting
See heycam/webidl#750

```
This implements two things:
- A syntax for specifying "default dictionary" using {}.
- The requirement that trailing optional dictionaries be thus specified.
```

(Copied from [bugzilla#1562680](https://bugzilla.mozilla.org/show_bug.cgi?id=1562680))

Related spec update PR in `html` and `dom`:
- whatwg/html#4745
- whatwg/dom#771

### PR DESCRIPTION
**Pull request by saschanaz**
The new change requires default dictionary value for optional dictionary-type arguments.

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23703 

- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23748)

### CODE REVIEW

**Comment by saschanaz** [comment]
That AppVeyor failure is exactly what I'm getting in #23747.

**Comment by Manishearth** [comment]
@bors-servo r+

this seems correct.

When you have time can you compare your PR with https://phabricator.services.mozilla.com/D36504#inline-220264 and see which webidl changes we have that they don't? (Also check for webidl changes they have that we don't for webidl files we have). We'll need to file upstream bugs for those.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Pull request merged**
