### PR TITLE
style: Unship the legacy syntax for -moz-transform.

### PR DESCRIPTION
**Pull request by emilio**
Intent to unship link:

  https://groups.google.com/d/msg/mozilla.dev.platform/T3PGm97MPNU/59XUavMlCgAJ

Reviewed-by: xidorn
Bug: 1438297
MozReview-Commit-ID: 6ybGBasPAWU

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20072)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r=xidorn p=1

 * coordiland

**Comment by CYBAI** [comment]
```
error[E0599]: no function or associated item named `eCSSPropertyAlias_MozTransform` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /Users/servo/buildbot/slave/mac-dev-unit/build/target/geckolib/debug/build/style-91447de1e353ecf6/out/properties.rs:91513:5
      |
91513 |     nsCSSPropertyID::eCSSPropertyAlias_MozTransform,
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `style`.
```

**Comment by emilio** [comment]
Blerg, bindings, of course, thanks @CYBAI! Will fix :)

**Pull request merged**
