### PR TITLE
Integrate clippy into Servo; cleanup some of script

### PR DESCRIPTION
**Pull request by Manishearth**
The integration is off by default for now. You can try it out with `./mach build --features "script/plugins/clippy"`.

We're using a branch of clippy with some of the lints changed to Allow, either because they don't apply to us, or because they're noisy and dwarf other warnings (but still should be fixed)

After going through the rest of Servo's warnings I'll figure out which lints we should be keeping.

There's a cargo bug with optional deps that makes it hard for this to work with Cargo.lock -- so this PR contains no changes to lockfiles (and running the build with clippy on may dirty the lockfile, though it gets fixed later)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7224)

### CODE REVIEW

**Comment by Manishearth** [comment]
cc @larsbergstrom

**Comment by dzbarsky** [comment]
Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: 4 of 21 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 2091 \[r9\]](https://reviewable.io:443/reviews/servo/servo/7224#-JwiiSsn2fNen56eWW-v)** ([raw file](https://github.com/servo/servo/blob/c20f970f4581f713a7ef1a49a6891216c67c758c/components/script/dom/node.rs#L2091)):</sup>
this can all be CharacterDataCast::to_ref(self).map(|c| c.Data())

---

<sup>**[components/script/dom/range.rs, line 341 \[r9\]](https://reviewable.io:443/reviews/servo/servo/7224#-Jwiiyveb9u_QwfQQq2N)** ([raw file](https://github.com/servo/servo/blob/c20f970f4581f713a7ef1a49a6891216c67c758c/components/script/dom/range.rs#L341)):</sup>
Isn't this just bp_position(....) == Ordering::Greater && bp_position(...) == Ordering::Less ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7224)

**Comment by Manishearth** [comment]
The single_match lint probably could be improved to suggest using `if` instead of `if let` when we're matching against unit variants which impl `PartialEq`.

(I just blindly copied those changes from Clippy's output, verifying that they were correct, but not thinking more about it :smile: )

**Comment by Ms2ger** [comment]
Review status: 3 of 21 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 341 \[r10\]](https://reviewable.io:443/reviews/servo/servo/7224#-JwkYbZ5uB9kif-PXo-Z)** ([raw file](https://github.com/servo/servo/blob/52ebe86c9fbc254e46c22c2210ca0c4a91309448/components/script/dom/range.rs#L341)):</sup>
No need for an if at all here.

---

<sup>**[components/script/dom/treewalker.rs, line 195 \[r10\]](https://reviewable.io:443/reviews/servo/servo/7224#-JwkYg7pgDCplFbxSfkz)** ([raw file](https://github.com/servo/servo/blob/52ebe86c9fbc254e46c22c2210ca0c4a91309448/components/script/dom/treewalker.rs#L195)):</sup>
I really *really* don't like `if let constant = ...`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7224)

**Comment by Manishearth** [comment]
Review status: 3 of 21 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 341 \[r10\]](https://reviewable.io:443/reviews/servo/servo/7224#-JwkYbZ5uB9kif-PXo-Z)** ([raw file](https://github.com/servo/servo/blob/52ebe86c9fbc254e46c22c2210ca0c4a91309448/components/script/dom/range.rs#L341)):</sup>
Ironically, clippy caught this too (and suggested removing the if), just that I didn't notice it :P

---

<sup>**[components/script/dom/treewalker.rs, line 195 \[r10\]](https://reviewable.io:443/reviews/servo/servo/7224#-JwkYg7pgDCplFbxSfkz)** ([raw file](https://github.com/servo/servo/blob/52ebe86c9fbc254e46c22c2210ca0c4a91309448/components/script/dom/treewalker.rs#L195)):</sup>
Fixing

(We're tweaking clippy to suggest `if` whenever possible, too)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7224)

**Comment by Ms2ger** [comment]
Reviewed 1 of 6 files at r1, 2 of 2 files at r2, 1 of 2 files at r6, 1 of 3 files at r8, 9 of 11 files at r9, 11 of 11 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 278 \[r11\]](https://reviewable.io:443/reviews/servo/servo/7224#-Jx-yya9g_gYrAXwQ60h)** ([raw file](https://github.com/servo/servo/blob/77b3c043f011eaee23c5bc90aeaad43d3efd935f/components/script/dom/node.rs#L278)):</sup>
Uh, where'd the `&` go?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7224)

**Comment by Ms2ger** [comment]
-S-awaiting-review -S-needs-rebase +S-needs-squash 

---

Reviewed 1 of 1 files at r12.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7224)

**Comment by Manishearth** [comment]
erwha

**Pull request merged**
