### PR TITLE
Replace twitter fail whale with redirect to archive.org version

### PR DESCRIPTION
**Pull request by bjwbell**
Sorry @pcwalton should have gotten the attribution approved first (https://twitter.com/subcide/status/645149674546966528)

r? @pcwalton

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7685)

### CODE REVIEW

**Comment by bjwbell** [comment]
follow up tweet with author https://twitter.com/bjwbell/status/645453144906829825

**Comment by Ms2ger** [comment]
I would prefer removing the file if it's not freely licensed.

**Comment by bjwbell** [comment]
@Ms2ger what do you think about https://github.com/bjwbell/servo/commit/62f8ecd008222944b28e61c59fc0a25050a841e3?
(I know servo doesn't currently do redirects)

**Comment by Ms2ger** [comment]
Probably fine.

**Comment by bjwbell** [comment]
@pcwalton can you r+?

**Comment by bjwbell** [comment]
test ref timeout.

@pcwalton I guess retry bors.

**Comment by jdm** [comment]
@bors-servo: retry
* #7737

**Comment by jdm** [comment]
@bors-servo: retry
* #7422

**Pull request merged**
