### PR TITLE
Fix restyle hints to handle non-last psuedo-selectors, and track pristine state values rather than changesets

### PR DESCRIPTION
**Pull request by bholley**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8341)

### CODE REVIEW

**Comment by jdm** [comment]
```
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/document.rs:1316:1: 1316:3 error: expected ident, found `<<`
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/document.rs:1316 <<<<<<< HEAD
                                                                                  ^~
```

**Comment by Manishearth** [comment]
This is going to fail the build due to a lockfile change. Apply the diff [here](http://build.servo.org/builders/gonk/builds/300/steps/shell/logs/stdio) and you should be good to go

**Comment by Manishearth** [comment]
@bors-servo r=larsbergstrom 

That failure should not have happened, my bad. Something off with the CI, will look at it again later. In the meantime, I'll keep this in the queue.

**Comment by Manishearth** [comment]
Okay, ignore all the spam above about the lockfile; a infra deploy pulled in some untested changes and led to some confusing results. Your PR is fine, sorry about the confusion :smile: 

@bors-servo r=pcwalton

**Pull request merged**
