### PR TITLE
Start precomputing presentational hints.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6311)

### CODE REVIEW

**Comment by pcwalton** [comment]
Does Gecko do preshints this way? I'm a little nervous about the memory overhead on `Attr`, although obviously I like doing less at selector matching time.

**Comment by Ms2ger** [comment]
I don't know what Gecko does here. I'll try to poke people.

**Comment by metajack** [comment]
@Ms2ger What was the answer?

**Comment by frewsxcv** [comment]
Any updates on this?

**Comment by Ms2ger** [comment]
I didn't get a definitive answer. I think this is still worth trying, but haven't had time to rebase.

**Comment by nox** [comment]
@Ms2ger Want me to take that over?

**Pull request closed without merging**
