### PR TITLE
Remove CompositorEventListener trait

### LINKED ISSUE #11339: Remove CompositorEventListener trait?
Only `IOCompositor` implements it now, and I doubt we'll reintroduce other implementations.

### PR DESCRIPTION
**Pull request by kyleheadley**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11339 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because refactoring

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11443)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Hi Kyle. Now you get to see reviewable in action, lucky you.

**Comment by asajeffrey** [comment]
Reviewed 5 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/compositing/compositor_thread.rs, line 8 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11443#-KIiKzUlnsrrSSwKB1EN:-KIiKzUmrQMQu1GF5-q2:560277183) ([raw file](https://github.com/servo/servo/blob/22398e85298ddc8ebd7afbc93bbca576d4017b62/components/compositing/compositor_thread.rs#L8)):*
> ```Rust
> 
> use SendableFrameTree;
> use compositor::{self, CompositingReason};
> ```

Add `IOCompositor` to the `use` list, so it can be used below?

---

*[components/compositing/compositor_thread.rs, line 289 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11443#-KIiKDqzhgqagT_aYhSZ:-KIiKDqzhgqagT_aYhS_:242645717) ([raw file](https://github.com/servo/servo/blob/22398e85298ddc8ebd7afbc93bbca576d4017b62/components/compositing/compositor_thread.rs#L289)):*
> ```Rust
>     pub fn create<Window>(window: Rc<Window>,
>                           state: InitialCompositorState)
>                           -> Box<compositor::IOCompositor<Window>>
> ```

If we're returning ownership of the `IOCompositor<Window>`, can we get rid of the `Box`? I think it was only needed because `CompoositorEventListener` was a trait.

---

*[components/servo/lib.rs, line 100 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11443#-KIiJ3fyfQHHJQqlOAOF:-KIiJ3fyfQHHJQqlOAOG:-165507110) ([raw file](https://github.com/servo/servo/blob/22398e85298ddc8ebd7afbc93bbca576d4017b62/components/servo/lib.rs#L100)):*
> ```Rust
> /// loop to pump messages between the embedding application and
> /// various browser components.
> pub struct Browser<Window: WindowMethods + 'static> {
> ```

Ah, that's interesting, `Browser` is now parametric in `Window`.

---

*[components/servo/lib.rs, line 101 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11443#-KIiKjU4JZXtpkoAtssm:-KIiKjU5LiN1YJo_5KTn:-103077628) ([raw file](https://github.com/servo/servo/blob/22398e85298ddc8ebd7afbc93bbca576d4017b62/components/servo/lib.rs#L101)):*
> ```Rust
> /// various browser components.
> pub struct Browser<Window: WindowMethods + 'static> {
>     compositor: Box<IOCompositor<Window>>,
> ```

Do we need this `Box`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11443)*

**Comment by asajeffrey** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11443)*

**Comment by kyleheadley** [comment]
Thanks for the quick review! Do I comment here?

I adjusted the `use` case above. The `box`es doesn't have to be there, but E-Easy Issue #10261 deals with that, so I left it for another contributor.

The modification in main.rs and lib.rs was scary, but I think it conforms better to the comments in those files, linking the `Brower` and `WindowMethods`.

**Comment by asajeffrey** [comment]
You reply back on reviewable. I think it's worth removing the box while you're there, as it really only makes sense for trait objects.

**Comment by asajeffrey** [comment]
Looks good, can you squash the commits now?

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11443#-:-KIjCzgPoOF2r7kB2vUZ:-79021654)*

**Comment by asajeffrey** [comment]
They're you go, that's the process!

**Comment by Ms2ger** [comment]
`./mach build-cef` is failing.

**Comment by jdm** [comment]
```
browser.rs:30:14: 30:21 error: wrong number of type arguments: expected 1, found 0 [E0243]
browser.rs:30     OnScreen(Browser),
                           ^~~~~~~
browser.rs:30:14: 30:21 help: run `rustc --explain E0243` to see a detailed explanation
browser.rs:31:15: 31:22 error: wrong number of type arguments: expected 1, found 0 [E0243]
browser.rs:31     OffScreen(Browser),
                            ^~~~~~~
```

**Comment by asajeffrey** [comment]
@kyleheadley oops, ports/cef needs updated.

**Comment by asajeffrey** [comment]
I think the fix is to replace `Browser` by `Browser<glutin_app::window::Window>`.

**Comment by kyleheadley** [comment]
yes, and the other `Browser` by `Browser<window::Window>`. I've got it working but was about to try to rebase off the current master because it's been a few days.

Is there another build I should try? Or leave the others to test on the proper system?

**Comment by jdm** [comment]
You'll need to change `ports/gonk/src/main.rs` as well, since it refers to the `Browser` type. It's harder to build locally, so those changes will probably need to be validated by the builders.

**Comment by asajeffrey** [comment]
OK, let's see what happens now. @bors-servo r+

**Comment by asajeffrey** [comment]
@kyleheadley The appveyor build failure is spurious, try rebasing against the upstream master, and see if that fixes things.

**Comment by asajeffrey** [comment]
Hmm, more spurious appveyor failures. @bors-servo r+

**Comment by asajeffrey** [comment]
Yay!

**Pull request merged**
