### PR TITLE
Implements drawImage for html image as ImageSource

### PR DESCRIPTION
**Pull request by dmarcos**

### CODE REVIEW

**Comment by jdm** [comment]
I've reviewed everything except for the code that fetches the image pixels from the cache. I'll need to look at that separately, since I want to make sure it's the best way to go about this and I don't know much about how the image cache works.

**Comment by dmarcos** [comment]
@jdm Thanks for taking time to review this. I know you have plenty of PRs on your plate. I will take care of your comments later today.

**Comment by metajack** [comment]
Assigned @jdm since he did the review.

**Comment by dmarcos** [comment]
@jdm I addressed all your comments. Let me know if you want me to change anything of the routine that retrieves the image from cache.

**Comment by dmarcos** [comment]
@jdm I have bandwidth today to finish this out. Let me know if there's any changes you want me to do

**Comment by jdm** [comment]
Ok, I'll dig into the image cache stuff.

**Comment by jdm** [comment]
Done. It seems sensible, just a few more changes for code readability.

**Comment by dmarcos** [comment]
@jdm Done :)

**Comment by jdm** [comment]
window_from_node is much more versatile than your changes allow :)

**Comment by dmarcos** [comment]
@jdm Sorry, I'm not following here. What do you want me to change?

**Comment by jdm** [comment]
@dmarcos All of the lines that I highlighted in the review can be replaced by a single window_from_node call, as described in the review comment.

**Comment by dmarcos** [comment]
Ups. Sorry! Just pushed changes. How does it look like now?

Still learning to navigate the different DOM types. it's about time to invest some time and understand what I'm doing :)

**Comment by jdm** [comment]
Delightful! If you squash, I'll merge!

**Comment by dmarcos** [comment]
@jdm Done!

**Comment by dmarcos** [comment]
@jdm Travis is failing but it seems is because github is timing out.

**Comment by dmarcos** [comment]
@jdm travis keeps failing because it cannot pull stuff from github. What can I do?

**Comment by dmarcos** [comment]
@jdm rust-png is not compiling:

http://build.servo.org/builders/gonk/builds/445/steps/compile/logs/stdio

My patch adds the dependency on the png library but I don't understand why it doesn't compile. Maybe I'm not pulling the proper version? It compiles on my local machine

https://github.com/dmarcos/servo/commit/475e696124a51d73fe32c6145aeb05e24eb7ca71#diff-8501f90e59ffc746eb00052e9a42c25aR60

**Comment by jdm** [comment]
Oh, I bet it's because the lock files for gonk and cef weren't updated, so Cargo ends up pulling in a much newer version of rust-png which our rustc can't compile. You should run `./mach update-cargo -p rust-png --precise 1d9c59c97598014860077f372443ae98b35ff4d9` and commit the results.

**Comment by dmarcos** [comment]
@jdm Ok. I pushed the changes. I hope it works

**Comment by larsbergstrom** [comment]
Failed in web platform tests:
http://build.servo.org/builders/mac1/builds/1481/steps/shell_2/logs/stdio
http://build.servo.org/builders/linux2/builds/1266/steps/shell_1/logs/stdio

**Comment by dmarcos** [comment]
@jdm I updated the test expectations. In the process I discovered a test that should be passing but fails: the case when the destination rectangle has an origin with negative coordinates. Do you want me to fix the problem in this PR or on a follow up patch?

**Comment by Ms2ger** [comment]
In general, doing it right the first time is easier than coming in to fix it after the fact :)

**Comment by jdm** [comment]
I agree with @Ms2ger here.

**Comment by dmarcos** [comment]
@jdm I rebased and made some improvements so additional WPT tests pass. Those changes are in independent commits so it can reviewed independently of the changes you already r+ed.

**Comment by jdm** [comment]
Ouch, that rebase didn't last long.

**Comment by jdm** [comment]
Otherwise those changes look fine to me.

**Comment by dmarcos** [comment]
@jdm Just rebased againt and now I'm trying to run wpt tests before pushing. I'm getting an error when running ```./mach test-wpt``` Is this a known issue? This is the output: https://pastebin.mozilla.org/8829013

**Comment by jdm** [comment]
Yes, I believe it was mentioned on the mailing list that you need to `rm -rf tests/wpt/_virtualenv` after the big test restructuring that happened over the weekend.

**Comment by dmarcos** [comment]
@jdm I just have my local master pointing to the latest commit in the upstream (1f57c6d), I run ```rm -rf tests/wpt/_virtualenv``` and still get the same error when running the tests ```./mach test-wpt```

**Comment by jdm** [comment]
@jgraham Any idea what's up with the output @dmarcos is seeing?

**Comment by dmarcos** [comment]
@jdm I addressed your review comments and pushed them to the branch. It passes the ref tests but I haven't been able to run the wpt suite yet. If the changes look good to you I will squash and we can let travis speak :)

**Comment by jdm** [comment]
I'm ok with that.

**Comment by jdm** [comment]
```
/2dcontext/shadows/2d.shadow.canvas.transparent.1.html
------------------------------------------------------
PASS expected FAIL Shadows are not drawn for transparent canvases
/2dcontext/shadows/2d.shadow.image.section.html
-----------------------------------------------
PASS expected FAIL Shadows are not drawn for areas outside image source rectangles
/2dcontext/shadows/2d.shadow.image.transparent.1.html
-----------------------------------------------------
PASS expected FAIL Shadows are not drawn for transparent images
```

**Comment by jdm** [comment]
Additionally, let's clean up these warnings:
```
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:650:27: 650:35 warning: use of unstable library feature 'core': trait is likely to be removed
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:650         Size2D(self.width.to_i32().unwrap(),
                                                                                                             ^~~~~~~~
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:650:35: 650:35 help: add #![feature(core)] to the crate attributes to silence this warning
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:651:28: 651:36 warning: use of unstable library feature 'core': trait is likely to be removed
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:651                self.height.to_i32().unwrap())
                                                                                                              ^~~~~~~~
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:651:36: 651:36 help: add #![feature(core)] to the crate attributes to silence this warning
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:662:36: 662:44 warning: use of unstable library feature 'core': trait is likely to be removed
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:662         Rect(Point2D(self.origin.x.to_i32().unwrap(),
                                                                                                                      ^~~~~~~~
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:662:44: 662:44 help: add #![feature(core)] to the crate attributes to silence this warning
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:663:36: 663:44 warning: use of unstable library feature 'core': trait is likely to be removed
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:663                      self.origin.y.to_i32().unwrap()),
                                                                                                                      ^~~~~~~~
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:663:44: 663:44 help: add #![feature(core)] to the crate attributes to silence this warning
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:664:37: 664:45 warning: use of unstable library feature 'core': trait is likely to be removed
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:664              Size2D(self.size.width.to_i32().unwrap(),
                                                                                                                       ^~~~~~~~
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:664:45: 664:45 help: add #![feature(core)] to the crate attributes to silence this warning
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:665:38: 665:46 warning: use of unstable library feature 'core': trait is likely to be removed
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:665                     self.size.height.to_i32().unwrap()))
                                                                                                                        ^~~~~~~~
/home/servo/buildbot/slave/linux2/build/components/canvas/canvas_paint_task.rs:665:46: 665:46 help: add #![feature(core)] to the crate attributes to silence this warning
```

**Comment by jgraham** [comment]
Re: the failure to run wpt, what happens if you activate the virtualenv by hand (something like `source tests/wpt/_virtualenv/bin/activate`), run `python2` (note the 2) and try to import mozrunner? If it imports OK, what does `dir(mozrunner)` show?

**Comment by dmarcos** [comment]
@jgraham I'm not familiarized on how the python infrastructure works but this is what I've done:

https://pastebin.mozilla.org/8829067

I get ```ImportError: No module named mozrunner```

**Comment by dmarcos** [comment]
@jdm To get rid of the warnings. Should I use "as i32" to cast from f64 to i32 instead of ```to_i32()```

**Comment by jgraham** [comment]
Hmm, so that means that you aren't installing the required dependencies. I wonder why not. If you do basically the same thing but `import wptrunner` and `from wptrunner.browsers import servo` instead, do they both work?

**Comment by dmarcos** [comment]
@jgraham I get ```ImportError: No module named wptrunner``` (https://pastebin.mozilla.org/8829069)

More info in case it's relevant: I'm on OSX and servo master (e521860). I could run wpt tests on friday with no issues. I can still run the ref tests e.g: ```/mach test tests/ref/2dcontext/```

**Comment by jdm** [comment]
@dmarcos Just add the core feature to canvas/lib.rs, as the warning suggests.

**Comment by jgraham** [comment]
@dmarcos I am very confused because if you can't import wptrunner then `./mach test-wpt` is supposed to install all the deps into the virtualenv for you. I presume that your `python/servo/tesing_commands.py` file is up to date with (and unchanged from) the upstream master?

**Comment by dmarcos** [comment]
@jgraham I haven't touched any python file. On Friday everything was okay and stopped working when I rebased my changes yesterday. I have the same problems on straight master at  after doing ```rm -rf tests/wpt/_virtualenv``` ```./mach clean``` ```./mach build```

**Comment by dmarcos** [comment]
@jdm I updated the tests expecations, rebased and squashed. Can we ask Travis is everything is ok? :)

**Comment by dmarcos** [comment]
@jgraham I just rebased and squashed my branch and ./mach test-wpt seems to be running now. weird!

**Comment by dmarcos** [comment]
@jdm Wait! Still one test failing. Pushing updated expectations in a minute

**Comment by jdm** [comment]
There are also a bunch of ini files that just contain passing tests now. Could you remove those?

**Comment by dmarcos** [comment]
@jdm I removed the ini files. All wpt tests pass on my local machine except two but they have nothing to do with the canvas or the drawImage API. Is this expected?

```
Summary
=======

Ran 151855 tests (2102 parents, 149753 subtests)
Expected results: 151771
Unexpected results: 2 (FAIL: 1, TIMEOUT: 1)
Skipped: 82

Unexpected Results
==================

/html/dom/reflection-text.html
------------------------------
TIMEOUT [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-001.html
---------------------------------------------------------------------------------
FAIL [Parent]
```

**Comment by jdm** [comment]
Those are known to cause problems occasionally. You can ignore them.

**Comment by dmarcos** [comment]
@larsbergstrom  Do you know why I don't see those failed tests on my local machine?

**Comment by jdm** [comment]
Yeah, we restarted our mac CI infrastructure and forgot to perform the black magic required to make the graphics stuff work.

**Comment by larsbergstrom** [comment]
@dmarcos This was my fault! We upgraded the hard disks on the mac servers to SSDs, but I did not manage to log in to open up a window session before this test run started. Our tests unfortunately require a window session open on Mac or they fail (due to the graphics libraries being unable to render anything).

I'm very sorry for the delay landing this!

**Comment by dmarcos** [comment]
@larsbergstrom Thanks! Happy to see this merge :)

**Pull request merged**
