### PR TITLE
Whitespace stripping should not result in a dangling, open border.

### PR DESCRIPTION
**Pull request by notriddle**
No open issue (found it while working on #7681).

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10419)

### CODE REVIEW

**Comment by notriddle** [comment]
CC @pcwalton, because according to git-blame, he actually wrote the code in construct.rs that I changed.

**Comment by mbrubeck** [comment]
@bors-servo r+

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10419#-:-KEbmAZSaG7kQH06dtVL:1236647940)*

**Pull request merged**
