### PR TITLE
script: Refactor CSSStyleDeclaration and fix some bugs in the way.

### PR DESCRIPTION
**Pull request by emilio**
This is preliminar work for the style attribute restyle hint.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15256)

### CODE REVIEW

**Comment by emilio** [comment]
r? @SimonSapin or @Manishearth 

cc @bholley

**Comment by emilio** [comment]
@bors-servo try

 * I hope not messing it up too much.

**Comment by SimonSapin** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/cssstyledeclaration.rs, line 65 at r1](https://reviewable.io:443/reviews/servo/servo/15256#-KbVabwYCarzLkRqgo44:-KbVabwYCarzLkRqgo45:b-lyr897) ([raw file](https://github.com/servo/servo/blob/e55731d3f31096379e47a0fe99ed8a1b7a2b43b9/components/script/dom/cssstyledeclaration.rs#L65)):*
> ```Rust
>                     (result, pdb.declarations.is_empty())
>                 } else {
>                     let mut pdb = PropertyDeclarationBlock {
> ```

@emilio, you asked me on IRC if I was against creating empty blocks. I think this is fine, since `vec![]` does not allocate.

---

*[components/script/dom/cssstyledeclaration.rs, line 417 at r1](https://reviewable.io:443/reviews/servo/servo/15256#-KbVftYXxXzsRkAN3vU8:-KbVftYXxXzsRkAN3vU9:b-8vwood) ([raw file](https://github.com/servo/servo/blob/e55731d3f31096379e47a0fe99ed8a1b7a2b43b9/components/script/dom/cssstyledeclaration.rs#L417)):*
> ```Rust
>             // Step 3
>             *pdb = parse_style_attribute(&value,
>                                          &window.get_url(),
> ```

That was already the case before, but using the document’s URL for `CSSStyleRule` is a bug. Please either fix it or file an issue. It should be the `style::Stylesheet::base_url` field, reachable through `CSSStyleRule::parent_stylesheet`. Maybe `mutate_associated_block` should pass the base URL as an additional parameter.

Same above in `set_property`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15256)*

**Comment by emilio** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/cssstyledeclaration.rs, line 65 at r1](https://reviewable.io:443/reviews/servo/servo/15256#-KbVabwYCarzLkRqgo44:-KbWDqe26E_50JJc1_g1:b-rf7tqe) ([raw file](https://github.com/servo/servo/blob/e55731d3f31096379e47a0fe99ed8a1b7a2b43b9/components/script/dom/cssstyledeclaration.rs#L65)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

@emilio, you asked me on IRC if I was against creating empty blocks. I think this is fine, since `vec![]` does not allocate.
</blockquote></details>

Yeah, that was my thinking too.

---

*[components/script/dom/cssstyledeclaration.rs, line 417 at r1](https://reviewable.io:443/reviews/servo/servo/15256#-KbVftYXxXzsRkAN3vU8:-KbWDt2UCFPeMiyBDur3:ba1u8nc) ([raw file](https://github.com/servo/servo/blob/e55731d3f31096379e47a0fe99ed8a1b7a2b43b9/components/script/dom/cssstyledeclaration.rs#L417)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

That was already the case before, but using the document’s URL for `CSSStyleRule` is a bug. Please either fix it or file an issue. It should be the `style::Stylesheet::base_url` field, reachable through `CSSStyleRule::parent_stylesheet`. Maybe `mutate_associated_block` should pass the base URL as an additional parameter.

Same above in `set_property`.
</blockquote></details>

Fixed both. using window.get_url() isn't the same as window.Document().base_url() either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15256)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15256#-:-KbZNJwIR7lGladY2voy:bkg9nno)*

**Comment by emilio** [comment]
@bors-servo r=SimonSapin

 * Just rebased to get homu unstuck

**Pull request merged**
