### PR TITLE
Get the mozjs crate to work with the mozjs_sys which uses bindgen

### PR DESCRIPTION
**Pull request by asajeffrey**
This is the matching PR to https://github.com/servo/mozjs/pull/134 and https://github.com/servo/rust-mozjs/pull/425 which runs bindgen on spidermonkey to produce Rust bindings.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because current tests should catch failures

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20793)

### CODE REVIEW

**Comment by nox** [comment]
(The commits should be cleaned up before landing the PR.)

**Comment by asajeffrey** [comment]
@jdm: the bindgenup landed in mozjs, so this is now ready for review.

**Review by jdm — APPROVED** [review]

**Comment by asajeffrey** [comment]
Squashed. @bors-servo r=jdm

**Comment by jdm** [comment]
All of the linux, arm, and android builders complained:
```
error: unknown argument: '-fno-sized-deallocation'
/usr/include/features.h:374:12: fatal error: 'sys/cdefs.h' file not found
error: unknown argument: '-fno-sized-deallocation', err: true
/usr/include/features.h:374:12: fatal error: 'sys/cdefs.h' file not found, err: true
thread 'main' panicked at 'Should generate JSAPI bindings OK: ()', libcore/result.rs:945:5
```

**Comment by jdm** [comment]
And windows:
```
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'clang.dll\', \'libclang.dll\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', libcore\result.rs:945:5
```

**Comment by asajeffrey** [comment]
Also http://build.servo.org/builders/linux-rel-css/builds/8802 complained:
```
/usr/include/limits.h:123:16: fatal error: 'limits.h' file not found
```
All these errors make me suspicious about the libclang on our build machines.

**Comment by asajeffrey** [comment]
Ah, our salt is for llvm 3.5, and bindgen needs at least 3.9.

https://github.com/servo/saltfs/blob/6ae68d8712863b2c8176aa1b102c8c0360dea4db/servo-build-dependencies/init.sls#L63-L65

**Comment by asajeffrey** [comment]
@bors-servo try

(Added the llvm dependency to msvc builds.)

**Comment by asajeffrey** [comment]
The android build errors should be fixed by https://github.com/servo/rust-mozjs/pull/427 and https://github.com/servo/saltfs/pull/844.

**Comment by asajeffrey** [comment]
It looks like bindgen isn't passing in `CXXFLAGS` to clang. https://github.com/asajeffrey/mozjs/tree/pass-cxx-flags-to-bindgen passes them in explicitly, let's see if that does the job. @bors-servo try

**Comment by asajeffrey** [comment]
The PR for CXXFLAGS is https://github.com/servo/mozjs/pull/136

**Comment by asajeffrey** [comment]
https://github.com/servo/mozjs/pull/136 landed

@bors-servo try

**Comment by asajeffrey** [comment]
That test failure is #20734

**Comment by asajeffrey** [comment]
We now have mozjs v0.7.1 and mozjs_sys v0.51.1 on crates.io, so we should be in a good place for android cross-compiles.

@bors-servo r=jdm

**Comment by asajeffrey** [comment]
@bors-servo retry
 * infra

**Comment by asajeffrey** [comment]
@bors-servo retry
 * #20734

**Comment by asajeffrey** [comment]
@bors-servo retry
 * infra

**Comment by asajeffrey** [comment]
@bors-servo r=jdm

https://mozilla.logbot.info/servo/20180530#c14829093

**Comment by paulrouget** [comment]
Since the mozjs v0.7.1 update, I can't compile anymore: https://github.com/servo/servo/issues/20958

**Pull request merged**
