### PR TITLE
style: Fix some dead links in style.md

### PR DESCRIPTION
**Pull request by gootorov**
Part of https://github.com/servo/book/issues/32

---

- [ ] These changes fix #__ (github issue number if applicable).

- [x] These changes do not require tests because: documentation

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20282)

### CODE REVIEW

**Comment by gootorov** [comment]
There are still some dead links. Not sure what happened to those.
For example, looking at the history of `style/selector_parser.rs` the `SelectorImplExt` trait didn't exist even at the earliest commit, although `style.md` already had a link to the trait.
List of remaining dead links:
http://doc.servo.org/style/selector_parser/trait.SelectorImplExt.html
http://doc.servo.org/style/stylist/struct.PerOriginSelectorMap.html
http://doc.servo.org/style/selector_parser/enum.PseudoElement.html

**Review by emilio — APPROVED** [review]
Looks good, thanks!

I should probably bring those docs a bit more up-to-date too :)

**Pull request merged**
