### PR TITLE
Add timeout pref to the mozilla/worklets wpt tests

### LINKED ISSUE #20292: Intermittent failure in /_mozilla/mozilla/worklets/test_paint_worklet.html
cc @asajeffrey 
```
  ▶ FAIL [expected PASS] /_mozilla/mozilla/worklets/test_paint_worklet.html
  └   → /_mozilla/mozilla/worklets/test_paint_worklet.html 23b755622cc81841a23cc8431a6546dfb1401c66
/_mozilla/mozilla/worklets/test_paint_worklet_ref.html 7949e80732fa0f4afdbae3b1cad96ccd75bb04f6
Testing 23b755622cc81841a23cc8431a6546dfb1401c66 == 7949e80732fa0f4afdbae3b1cad96ccd75bb04f6
```
The non-reference image was a blank page.

### PR DESCRIPTION
**Pull request by asajeffrey**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #20292 
- [X] These changes do not require tests because this is test infrastructure

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20296)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo retry
* #19937

**Comment by jdm** [comment]
Hmm, this timeout was also observed:
```

  ▶ FAIL [expected PASS] /_mozilla/mozilla/worklets/test_paint_worklet_timeout.html
  └   → /_mozilla/mozilla/worklets/test_paint_worklet_timeout.html be717e2507be2f526606aae5544551c4cfc1cf5e
/_mozilla/mozilla/worklets/test_paint_worklet_timeout_ref.html bc7e16713b4b0b41e57fdf3c7d7bbfa5d5b1fa9f
Testing be717e2507be2f526606aae5544551c4cfc1cf5e == bc7e16713b4b0b41e57fdf3c7d7bbfa5d5b1fa9f

```

**Comment by jdm** [comment]
@bors-servo retry
* infrastructure issue

**Comment by jdm** [comment]
The worklet timeout test seems to be failing reliably now.

**Comment by asajeffrey** [comment]
Argh, of course I shouldn't bump the timeout on the test that makes sure timeouts happen promptly. D'oh!

**Pull request merged**
