### PR TITLE
clippy: Fix missing indentation in comments and remove on unecessary cast

### PR DESCRIPTION
**Pull request by DanielFrantes**
Fixing clippy warnings

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes are part of #31500

- [X] These changes do not require tests because don't change logic of code

### CODE REVIEW

**Comment by danik292** [comment]
> @danik292  You will need to sign your commit (use `--amend` with `-s`). See https://wiki.linuxfoundation.org/dco.

So git --amend -s  with no files in staging arena,If I understand.

**Comment by mrobinson** [comment]
> So git --amend -s with no files in staging arena,If I understand.

The easiest way to do this is to squash all of your commits into a single commit and then simply `git --amend -s`. If there are files in the staging area, they are automatically committed when you commit, so they will also be committed when you amend. It's best not to have files in the staging area if you do not plan to commit them.

**Comment by danik292** [comment]
@mrobinson  I singed off both my commits.

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
Thanks for the contribution. I will land this now.

**Pull request merged**
