### PR TITLE
implement display_handler::on_status_message for cef

### PR DESCRIPTION
**Pull request by zmike**
r+? @jdm @larsbergstrom @metajack @pcwalton @anyone with r+

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6890)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Homu or buildbot seems stuck here, trying to close/reopen to see if that helps.

**Comment by metajack** [comment]
@zmike You need to associate your commit email with GitHub or it will confuse our systems. I worked around this with https://github.com/servo/saltfs/pull/92 for now.

**Pull request merged**
