### PR TITLE
Remove FIXME in handle_evaluate_js #6728 

### PR DESCRIPTION
**Pull request by initsecret**
I removed the comments

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6755)

### CODE REVIEW

**Comment by jdm** [comment]
Thanks for the patch! There are a couple changes that will be needed before we can merge this, though :)
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/devtools.rs, line 42 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6755#-Jv4voTBJR6-MaxN_xJh)** ([raw file](https://github.com/servo/servo/blob/9e02ef93478c41a3fc6971611b358da6f73625d6/components/script/devtools.rs#L42)):</sup>
Please leave this FIXME; it hasn't been resolved yet. However, feel free to work on https://github.com/servo/servo/issues/6756 and change that!

---

<sup>**[components/script/script_task.rs, line 793 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6755#-Jv4whfYfrhxnfYZkZK3)** ([raw file](https://github.com/servo/servo/blob/9e02ef93478c41a3fc6971611b358da6f73625d6/components/script/script_task.rs#L793)):</sup>
nit: please revert this change.

---

<sup>**[components/script/script_task.rs, line 814 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6755#-Jv4vkX25wA0GZgCv0vh)** ([raw file](https://github.com/servo/servo/blob/6162de144c99d91dbc18b87cf373fc82b954327f/components/script/script_task.rs#L814)):</sup>
nit: revert this change, please.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6755)

**Comment by metajack** [comment]
@s142857 Are you still working on the necessary changes?

**Comment by s142857** [comment]
I had actually suspended working on it, I'll continue today

**Comment by s142857** [comment]
If you want to take it up,  I committed my changes so you can continue

Thanks

**Comment by s142857** [comment]
sorry i cant finish it.

**Comment by jdm** [comment]
Ok, thanks for letting us know!

**Pull request closed without merging**
