### PR TITLE
style: Move the StyleSheetSet into the Stylist.

### PR DESCRIPTION
**Pull request by emilio**
This will allow tracking whether there have been only additions to the
stylesheet set, and in that case don't destroy and completely rebuild the
invalidation map.

This is on top of #18143.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18170)

### CODE REVIEW

**Comment by emilio** [comment]
(or, @heycam, too)

**Comment by emilio** [comment]
This is now rebased on top of #18143, and ready for review.

**Comment by emilio** [comment]
Since @SimonSapin asked about the `unsafe impl Sync for GeckoStyleSheet`, and I didn't have a better answer than "our usage happens to be fine", I pushed another commit to isolate the unsafety harder.

Thanks Simon :)

**Comment by SimonSapin** [comment]
I’d still like a couple sentences on that impl to say how it’s used etc.

---

Reviewed 3 of 3 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/style/stylist.rs, line 54 at r2](https://reviewable.io:443/reviews/servo/servo/18170#-Ks5o1KwV_Tw_MMK1TbZ:-Ks5o1Ky5SBR-Xom7q2_:b-ji74zo) ([raw file](https://github.com/servo/servo/blob/1700ff398858d4ce739f5286925749b79717d71b/components/style/stylist.rs#L54)):*
> ```Rust
> /// The type of the stylesheets that the stylist contains.
> ///
> /// FIXME(emilio): It'd be pretty nice to make the stylist generic, but that's
> ```

I think cfg over generics is fine.

---

*[components/style/stylist.rs, line 330 at r2](https://reviewable.io:443/reviews/servo/servo/18170#-Ks9GcJFEbzUcooRRJba:-Ks9GcJG8ruUaH4g1Rk4:b-pcavgp) ([raw file](https://github.com/servo/servo/blob/1700ff398858d4ce739f5286925749b79717d71b/components/style/stylist.rs#L330)):*
> ```Rust
> /// This structure holds all the selectors and device characteristics
> /// for a given document. The selectors are converted into `Rule`s
> /// (defined in rust-selectors), and sorted into `SelectorMap`s keyed
> ```

`Rule` is not in rust-selectors anymore.

---

*[components/style/stylist.rs, line 333 at r4](https://reviewable.io:443/reviews/servo/servo/18170#-Ks9PqA36obze3LME52h:-Ks9PqA4j0arsze44I7m:b-41dpuz) ([raw file](https://github.com/servo/servo/blob/c5f46705c570c234ff8fa87590e6f3919d28b592/components/style/stylist.rs#L333)):*
> ```Rust
> #[cfg_attr(feature = "servo", derive(HeapSizeOf))]
> struct StylistStylesheetSet(StylesheetSet<StylistSheet>);
> unsafe impl Sync for StylistStylesheetSet {}
> ```

Please add a doc-comment here to explain why this impl is ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18170#-:-Ks9Q2lGXvQHBx2r5-KX:b-1j6dij)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 2 of 2 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18170#-:-Ks9S8iQH66IEBZ6Esvt:bkg9nno)*

**Comment by emilio** [comment]
@bors-servo p=1

 * More patches incoming.

**Pull request merged**
