### PR TITLE
Fix compositor timing issues

### PR DESCRIPTION
**Pull request by mrobinson**
Clean up compositor data structures and fix timing issues that cause Compositor panics.

### CODE REVIEW

**Comment by mrobinson** [comment]
This fixes a lot of back/forward navigation panics on Wikipedia.

**Comment by jdm** [comment]
I just read through these changes and they make a lot of sense. :+1:

**Comment by pcwalton** [comment]
LGTM, r? @larsbergstrom

**Comment by larsbergstrom** [comment]
Gah! Sorry I missed the Critic update mails. I made a tiny request - if you could address it, squash, and r=me. Sorry for the delay!

**Comment by mrobinson** [comment]
Thank you all very kindly for the reviews.

**Pull request closed without merging**
