### PR TITLE
Update WR (inset box shadow fix, border-image support).

### PR DESCRIPTION
**Pull request by glennw**
I have a follow up PR for Servo that uses the new border-image
APIs, but I'll land that separately, so that we don't delay
landing the WR update itself.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15681)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
cc #15583

**Comment by Wafflespeanut** [comment]
Okay #15583 again. Looks like our intermittents database needs to be updated.

**Comment by Wafflespeanut** [comment]
(great, forgot to retry)

@bors-servo retry

**Comment by jdm** [comment]
@bors-servo: retry
#15583 
The DB should actually be up to date now.

**Comment by Wafflespeanut** [comment]
@bors-servo retry

(something error something?)

**Comment by glennw** [comment]
I've timed the WPT tests with this update, and it seems to be around 3-4% slower, which might explain why it's triggering some of these intermittents. I'll investigate further today.

**Comment by glennw** [comment]
@bors-servo retry
 * It looks like 3 of the failures were expected intermittents, and one of them is a known intermittent occurring on a different test.

**Comment by jonathandturner** [comment]
Just gave this a try.  Looks like some of the recent fixes definitely are improving things (yay!), so we now aren't hanging on reddit/rust-lang/servo/HN.  

I am seeing some font issues, but perhaps they're unrelated?

reddit_with_patch

**Pull request merged**
