### PR TITLE
Upgrade to rustc 1.19.0-nightly (ced823e26 2017-05-07)

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16756)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Extract that seems relevant of the error messages:
```
error: failed to run custom build command for `blurdroid v0.1.2`
process didn't exit successfully: `/home/servo/buildbot/slave/android/build/target/debug/build/blurdroid-e2727e499c92c405/build-script-build` (exit code: 1)
--- stdout
make: Entering directory `/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/blurdroid-0.1.2/src/jni'
make: Leaving directory `/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/blurdroid-0.1.2/src/jni'
Error while executing javac

--- stderr
src/java/hu/uszeged/bluetooth/ScanRecord.java:25: error: package android.os does not exist
import android.os.ParcelUuid;
                 ^
src/java/hu/uszeged/bluetooth/ScanRecord.java:26: error: package android.util does not exist
import android.util.SparseArray;
                   ^
```

@larsbergstrom Have you seen this before?

**Comment by SimonSapin** [comment]
Also depends on https://github.com/laumann/compiletest-rs/pull/63

**Comment by jdm** [comment]
@bors-servo: retry
* #16773

**Pull request merged**
