### PR TITLE
Update script_plugin for rust-lang/rust#85296

### PR DESCRIPTION
**Pull request by bjorn3**
This will update the script_plugin for the plugin interface changes in rust-lang/rust#85296.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it is a fix for rustc changes.

### CODE REVIEW

**Comment by jdm** [comment]
Thanks for updating this usage!

**Comment by bjorn3** [comment]
```
Ran 976 tests finished in 738.9 seconds.
  • 973 ran as expected. 117 tests skipped.
  • 1 tests timed out unexpectedly
  • 2 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /html/browsers/history/the-history-interface/traverse_the_history_1.html:
  │ FAIL [expected PASS] b'Multiple history traversals from the same task'
  │   → assert_array_equals: Pages opened during history navigation expected property 1 to be 2 but got 1 (expected array [4, 2] got [4, 1])
  │ 
  │ start_test_wait</timer<@http://web-platform.test:8000/html/browsers/history/the-history-interface/traverse_the_history_1.html:16:30
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2095:25
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:2122:35

  ▶ Unexpected subtest result in /html/browsers/history/the-history-interface/traverse_the_history_3.html:
  │ FAIL [expected PASS] b'Multiple history traversals, last would be aborted'
  │   → assert_array_equals: Pages opened during history navigation expected property 1 to be 3 but got 2 (expected array [6, 3] got [6, 2])
  │ 
  │ start_test_wait</timer<@http://web-platform.test:8000/html/browsers/history/the-history-interface/traverse_the_history_3.html:17:32
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2095:25
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:2122:35

  ▶ TIMEOUT [expected OK] b'/html/browsers/origin/cross-origin-objects/cross-origin-objects.html'
  │ 
  └ error: XDG_RUNTIME_DIR not set in the environment.

1 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected OK] b'/html/browsers/origin/cross-origin-objects/cross-origin-objects.html'
  │ 
  └ error: XDG_RUNTIME_DIR not set in the environment.

Error: Process completed with exit code 1.
```

**Comment by jdm** [comment]
@bors-servo retry
* #28569

**Pull request merged**
