### PR TITLE
Make DOMString a newtype around String, rather than a typedef.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8312)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Yay, this will make experimenting with alternative DOMString representations a lot easier! A couple of comments...

It would be nice to have a function for converting DOMString to String: x.flatten() or x.to_utf8() or something. At the moment there's lots of x.0 in the code, which would all need rewritten if DOMString changed internals.

It might be nice to use a macro domstring!("foo") or something, so that we might be able to do compile-time magic to optimize constant DOMStrings. I can imagine the macro using a different representation for short strings or strings which are in the list of blessed atoms.

**Comment by Ms2ger** [comment]
Agreed, but I'd prefer to push that to a followup.

**Comment by Manishearth** [comment]
Reviewed 24 of 24 files at r1, 79 of 79 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[components/script/dom/bindings/trace.rs, line 287 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8312#-K2CwPK8fKD9zFJ2ZGNW)** ([raw file](https://github.com/servo/servo/blob/dac13e021a2e7be3f0bf802ab36a3a31be878018/components/script/dom/bindings/trace.rs#L287)):</sup>
I prefer derive(trace) on DOMstring, the macro is only for stuff we importn


---

<sup>**[components/util/mem.rs, line 104 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8312#-K2D-P8uLM2-4Ze_xjm7)** ([raw file](https://github.com/servo/servo/blob/dac13e021a2e7be3f0bf802ab36a3a31be878018/components/util/mem.rs#L104)):</sup>
use derivexz


---

<sup>**[components/util/str.rs, line 31 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8312#-K2D-SL6TytbKr_h22Ut)** ([raw file](https://github.com/servo/servo/blob/dac13e021a2e7be3f0bf802ab36a3a31be878018/components/util/str.rs#L31)):</sup>
I'd prefer this to deref to &str if it doesn't cause too much churnxzx


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8312)

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[components/script/dom/bindings/trace.rs, line 287 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8312#-K2CwPK8fKD9zFJ2ZGNW)** ([raw file](https://github.com/servo/servo/blob/dac13e021a2e7be3f0bf802ab36a3a31be878018/components/script/dom/bindings/trace.rs#L287)):</sup>
Me too, but `DOMString` is in `util`, so it can't see `script`'s `JSTraceable`.


---

<sup>**[components/util/mem.rs, line 104 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8312#-K2D-P8uLM2-4Ze_xjm7)** ([raw file](https://github.com/servo/servo/blob/dac13e021a2e7be3f0bf802ab36a3a31be878018/components/util/mem.rs#L104)):</sup>
It doesn't work in `util` itself.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8312)

**Comment by Manishearth** [comment]
nooooo

**Comment by jdm** [comment]
```
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:21:55: 21:75 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:21     let mut textinput = TextInput::new(Lines::Single, "abcdefg".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:21:55: 21:75 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:24:5: 24:51 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:27:5: 27:50 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:31:5: 31:48 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:33:55: 33:71 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:33     let mut textinput = TextInput::new(Lines::Single, "a🌠b".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                           ^~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:33:55: 33:71 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:38:5: 38:47 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:43:55: 43:75 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:43     let mut textinput = TextInput::new(Lines::Single, "abcdefg".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:43:55: 43:75 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:46:5: 46:53 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:50:5: 50:52 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:52:55: 52:71 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:52     let mut textinput = TextInput::new(Lines::Single, "a🌠c".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                           ^~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:52:55: 52:71 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:58:5: 58:49 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:63:55: 63:75 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:63     let mut textinput = TextInput::new(Lines::Single, "abcdefg".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:63:55: 63:75 help: run `rustc --explain E0308` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:80:55: 80:75 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:80     let mut textinput = TextInput::new(Lines::Single, "abcdefg".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:80:55: 80:75 help: run `rustc --explain E0308` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:84:33: 84:49 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:84     textinput.replace_selection("xyz".to_owned());
                                                                                                                     ^~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:84:33: 84:49 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:85:5: 85:53 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:90:57: 90:80 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:90     let mut textinput = TextInput::new(Lines::Multiple, "abc\nde\nf".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:90:57: 90:80 help: run `rustc --explain E0308` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:102:57: 102:80 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:102     let mut textinput = TextInput::new(Lines::Multiple, "abc\nde\nf".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:102:57: 102:80 help: run `rustc --explain E0308` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:119:57: 119:80 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:119     let mut textinput = TextInput::new(Lines::Multiple, "abc\nde\nf".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:119:57: 119:80 help: run `rustc --explain E0308` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:140:24: 140:43 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:140         Lines::Single, "abcdef".to_owned(), DummyClipboardContext::new(""));
                                                                                                             ^~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:140:24: 140:43 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:143:5: 143:63 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:146:26: 146:45 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:146         Lines::Multiple, "abcdef".to_owned(), DummyClipboardContext::new(""));
                                                                                                               ^~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:146:26: 146:45 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:149:5: 149:64 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:155:26: 155:49 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:155         Lines::Multiple, "abc\nde\nf".to_owned(), DummyClipboardContext::new(""));
                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:155:26: 155:49 help: run `rustc --explain E0308` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:166:63: 166:83 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:166     let single_line_textinput = TextInput::new(Lines::Single, "abcdefg".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                                    ^~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:166:63: 166:83 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:167:5: 167:64 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:170:26: 170:49 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:170         Lines::Multiple, "abc\nde\nf".to_owned(), DummyClipboardContext::new(""));
                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:170:26: 170:49 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:171:5: 171:66 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:176:57: 176:80 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:176     let mut textinput = TextInput::new(Lines::Multiple, "abc\nde\nf".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:176:57: 176:80 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:177:5: 177:55 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:179:27: 179:46 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:179     textinput.set_content("abc\nf".to_owned());
                                                                                                                ^~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:179:27: 179:46 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:180:5: 180:51 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:187:27: 187:42 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:187     textinput.set_content("de".to_owned());
                                                                                                                ^~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:187:27: 187:42 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:188:5: 188:47 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:200:55: 200:72 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:200     let mut textinput = TextInput::new(Lines::Single, "defg".to_owned(), DummyClipboardContext::new("abc"));
                                                                                                                                            ^~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:200:55: 200:72 help: run `rustc --explain E0308` to see a detailed explanation
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:201:5: 201:49 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
<std macros>:9:3: 9:13 error: the trait `core::fmt::Debug` is not implemented for the type `util::str::DOMString` [E0277]
<std macros>:9 , * left_val , * right_val ) } } } } )
                 ^~~~~~~~~~
<std macros>:9:1: 9:40 note: in this expansion of format_args!
<std macros>:6:1: 9:29 note: in this expansion of panic! (defined in <std macros>)
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:204:5: 204:52 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:9:3: 9:13 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:9:3: 9:13 note: `util::str::DOMString` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
<std macros>:9:3: 9:13 note: required by `core::fmt::Debug::fmt`
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:209:55: 209:74 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:209     let mut textinput = TextInput::new(Lines::Single, "abcdef".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                            ^~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:209:55: 209:74 help: run `rustc --explain E0308` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:233:57: 233:80 error: mismatched types:
 expected `util::str::DOMString`,
    found `collections::string::String`
(expected struct `util::str::DOMString`,
    found struct `collections::string::String`) [E0308]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:233     let mut textinput = TextInput::new(Lines::Multiple, "abc\nde\nf".to_owned(), DummyClipboardContext::new(""));
                                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/script/textinput.rs:233:57: 233:80 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 38 previous errors
```

**Pull request merged**
