### PR TITLE
Build geckolib on travis.

### PR DESCRIPTION
**Pull request by Ms2ger**
This adds about two minutes to the twenty-minute build.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12386)

### CODE REVIEW

**Comment by nox** [comment]
Cool.

@bors-servo r+

**Comment by SimonSapin** [comment]
@larsbergstrom Do you think it would be beneficial to make it a separate entry in the build matrix, so that it builds in parallel? Or is 2 minutes not worth it?

**Comment by larsbergstrom** [comment]
The only risk is that it's pretty easy to consume all of our concurrent builds when people are pushing to a bunch of open PRs and then we end up stalled/backlogged. So, I'm not against trying it out, but we might want to make sure we don't end up starving e.g., saltfs PRs or other things sharing the "servo github organization" concurrent build limit.

**Pull request merged**
