### PR TITLE
Update dependencies for js, fontconfig-sys and mozjs_sys

### LINKED ISSUE #6088: Replace /usr/bin/find hacks in dependency makefiles with Cargo variables
Some of our dependencies makefiles have hacks like this:

https://github.com/servo/rust-azure/blob/11d7292919a365c55ca6204c465c5eeefcabfe05/makefile.cargo#L62
```Makefile
SKIA_OUTDIR = $(shell find $(OUT_DIR)/../.. -name 'skia-*' -type d)/out
```
… which break when e.g. there is more then one directory matching `skia-*` (multiple versions have been built without `cargo clean`).

Instead, we should be using Cargo’s metadata and `DEP_*` environment variables: http://doc.crates.io/build-script.html#the-links-manifest-key

### PR DESCRIPTION
**Pull request by asbaker**
Fixes servo/servo#6088

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6218)

### CODE REVIEW

**Comment by asbaker** [comment]
@SimonSapin Thanks for getting those other fixes reviewed and merged so quickly! This should be the last part for servo/servo#6088.

I updated the `js`, `fontconfig-sys` and `mozjs_sys` packages using `mach update-cargo -p <package>` to pull in the makefile fixes from those dependencies.

Running another egrep from cargo shows that there are no remaining makefile hacks that traverse up the tree:

```
~/Source/servo <update-dependencies-for-6088> grep -ri "shell find" .
./.cargo/git/checkouts/mozjs-2284529523a8d467/master/js/src/Makefile.in:ALL_FILES=$(shell find $(srcdir) \( -name "*.cpp" -o -name "*.h" \) ! -path "*/dist/*" ! -path "*/config/*")
./.cargo/git/checkouts/rust-azure-03a3575c638f374d/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/. -type f -name '*.rs')
./.cargo/git/checkouts/rust-core-foundation-083fc637ecf87027/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/git/checkouts/rust-core-graphics-1e327b35416cbd60/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/git/checkouts/rust-core-text-e599875907e5f455/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/git/checkouts/rust-egl-995f9207ca3ade64/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/git/checkouts/rust-fontconfig-aa919ab93567a942/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/git/checkouts/rust-freetype-c7f42bafd2dee115/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/git/checkouts/rust-io-surface-f335bb7b39c2aba0/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/git/checkouts/rust-layers-3d9d5f0b4e4d9002/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/git/checkouts/rust-mozjs-ab9bfe6e592bc16c/master/Makefile.in:RUST_SRC = $(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/git/checkouts/rust-stb-image-f9fd72864e9c69fe/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/. -type f -name '*.rs')
./.cargo/git/checkouts/rust-xlib-13f0f7593ba233ec/master/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/registry/src/github.com-1ecc6299db9ec823/glutin_core_foundation-0.1.2/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./.cargo/registry/src/github.com-1ecc6299db9ec823/glutin_core_graphics-0.1.4/Makefile.in:RUST_SRC=$(shell find $(VPATH)/src -type f -name '*.rs')
./components/servo/target/debug/build/mozjs_sys-476fe81cd282b5dc/out/Makefile:ALL_FILES=$(shell find $(srcdir) \( -name "*.cpp" -o -name "*.h" \) ! -path "*/dist/*" ! -path "*/config/*")
./support/rust-task_info/Makefile.in:RUST_SRC = $(shell find $(VPATH)/. -type f -name '*.rs')
```

**Comment by SimonSapin** [comment]
Looks good, thanks for pushing on this!

I’ve edited your PR message to "Fixes servo/servo#6088" so that GitHub closes it automatically when this lands, since this is the last part.

**Comment by SimonSapin** [comment]
```
In file included from /home/servo/.cargo/git/checkouts/libfontconfig-b319b63600e740b1/master/src/fcftint.h:26:0,
                 from /home/servo/.cargo/git/checkouts/libfontconfig-b319b63600e740b1/master/src/fcfreetype.c:48:
/home/servo/.cargo/git/checkouts/libfontconfig-b319b63600e740b1/master/fontconfig/fcfreetype.h:27:22: fatal error: ft2build.h: No such file or directory
```

Looks like a legit error, something is missing in one of the build scripts or makefiles.

**Comment by SimonSapin** [comment]
Can you build locally, with this PR?

**Comment by SimonSapin** [comment]
https://github.com/servo/libfontconfig/pull/5#discussion_r31378355

**Pull request merged**
