### PR TITLE
Add `#![feature(int_uint)]` to script

### PR DESCRIPTION
**Pull request by akosthekiss**
This one line change makes 4970 lines of warning go away

### CODE REVIEW

**Comment by SimonSapin** [comment]
I don’t think we should do this. The warnings exist for a reason.

**Comment by akiss77** [comment]
It's already there in gfx, util, net, compositing, and style.

**Comment by SimonSapin** [comment]
I disagree with these too :)

**Comment by Ms2ger** [comment]
We should remove those, but after the rustup; now they're just noise.

**Pull request merged**
