### PR TITLE
Remove mako zip

### LINKED ISSUE #12958: Remove the mako zip file and use proper python dependencies
```
<emilio> SimonSapin: btw, do you remember why do we have the mako zip file in-tree? Couldn't we pull it as a dependency like we do with everything else?
<•SimonSapin> emilio: because we didn’t have any other Python code in the tree at the time, and that seemed less fragile than requiring virtualenv
<•SimonSapin> but now that we have a virtualenv we could very well install Mako there
<•SimonSapin> and remove the zip file
<emilio> SimonSapin: I see, I'll fill an issue about that, thanks!
<•SimonSapin> make sure to pin some required version number
```

Should be easy enough, though I'm not too versed in our python infra. @Wafflespeanut would you be interested in mentoring this if nobody does it on their own?

### PR DESCRIPTION
**Pull request by tvladyslav**
---

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
  Tidy tests fails with following error
  IndexError: list index out of range
  
  File "/home/cryptouniverse/GIT/servo/python/servo/testing_commands.py", line 316, in test_tidy
    return tidy.scan(not all_files, not no_progress)
  File "/home/cryptouniverse/GIT/servo/python/tidy/servo_tidy/tidy.py", line 841, in scan
    for error in errors:
  File "/home/cryptouniverse/GIT/servo/python/tidy/servo_tidy/tidy.py", line 748, in collect_errors_for_files
    for error in check(filename, lines):
  File "/home/cryptouniverse/GIT/servo/python/tidy/servo_tidy/tidy.py", line 142, in check_license
    if lines[0].startswith("#!") and lines[1].strip():
- [X] These changes fix #12958 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Issue #12958
r? @KiChjang

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13065)

### CODE REVIEW

**Comment by crypto-universe** [comment]
@KiChjang Look at this commit, please. Seems to work, but:
1) Tidy tests fails. "IndexError: list index out of range";
2) Hardcoded ENV value, as I don't know how to import VIRTUAL_ENV;

**Comment by KiChjang** [comment]
I'm no python guru. r? @Wafflespeanut

**Comment by bholley** [comment]
CC @SimonSapin

**Comment by SimonSapin** [comment]
This doesn’t look right. The `virtualenv` command creates a new virtual environment (whereas by the time we get here the environment should probably already exist), then this code keeps running Python like before: not in the environment.

Perhaps it would be better to make a new mach sub-command for this, and call it from the build script. That way we can relay on mach to bootstrap itself and create the virtualenv as needed.

@Wafflespeanut, what do you think?

**Comment by Wafflespeanut** [comment]
@SimonSapin is right. We don't need another `virtualenv` for this. `mach` already ensures that (during bootstrapping). Simply removing the zip file, and adding it to the existing dependencies should make it work.

**Comment by crypto-universe** [comment]
I moved changes to PR #13097 . Check it there, please.

**Comment by Wafflespeanut** [comment]
superseded by #13097

**Pull request closed without merging**
