### PR TITLE
Use a stable compiler for build-geckolib

### LINKED ISSUE #11815: Build geckolib with a stable Rust compiler
Stylo wants to eventually switch to stable Rust. This is a meta-issue to track tasks needed.

* [x] https://github.com/servo/servo/issues/11806
  * [x] https://github.com/servo/servo/pull/11945
* [x] https://github.com/servo/servo/pull/11816
* [x] <s>https://github.com/rust-lang/rust/issues/24263</s> https://github.com/servo/servo/pull/11884
* [x] https://github.com/servo/servo/pull/11827
* [x] <s>https://github.com/rust-lang/rust/issues/27708</s> https://github.com/servo/servo/pull/11835
* [x] https://github.com/servo/servo/pull/12263

### PR DESCRIPTION
**Pull request by SimonSapin**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #11815 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because CI already runs `./mach build-geckolib`

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12319)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Rebased. r? @larsbergstrom

**Comment by larsbergstrom** [comment]
Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 8 of 8 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/servo/build_commands.py, line 372 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12319#-KM9U96bHD3v-QMNVD6l:-KM9U96bHD3v-QMNVD6m:-67855733) ([raw file](https://github.com/servo/servo/blob/b6446267538869fa786125a04297793a2272a388/python/servo/build_commands.py#L372)):*
> ```Python
> 
>         env = self.build_env()
>         env["CARGO_TARGET_DIR"] = path.join(self.context.topdir, "ports/geckolib/target")
> ```

maybe target/geckolib instead? I'm a little wary of having another target/ dir buried inside the source tree instead of at toplevel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12319)*

**Comment by larsbergstrom** [comment]
Feel free to r=me with that change (if you agree), as I'm on PTO today. Otherwise, I'll take a look this weekend :-)

Thanks for doing this!

**Comment by SimonSapin** [comment]
@bors-servo r= larsbergstrom

---

Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/servo/build_commands.py, line 372 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12319#-KM9U96bHD3v-QMNVD6l:-KM9VymAsLR6HTL9dANX:-499146009) ([raw file](https://github.com/servo/servo/blob/b6446267538869fa786125a04297793a2272a388/python/servo/build_commands.py#L372)):*
<details><summary><i>Previously, larsbergstrom (Lars Bergstrom) wrote…</i></summary>
> maybe target/geckolib instead? I'm a little wary of having another target/ dir buried inside the source tree instead of at toplevel.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12319#-:-KM9W2BWXqpGw763Yabt:-998004521)*

**Comment by SimonSapin** [comment]
@bors-servo retry

* Network error… hopefully temporary?

```
Error downloading Rust compiler: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure. The failing URL was: https://static.rust-lang.org/dist/rust-std-1.9.0-x86_64-unknown-linux-gnu.tar.gz
```

**Comment by SimonSapin** [comment]
@bors-servo retry

* Previous build downloaded rustc but not std? I’ve emptied the `/home/servo/.servo` cache on servo-linux2.servo.org

```
error: can't find crate for `std` [E0463]
```

**Comment by aneeshusa** [comment]
@bors-servo retry

- infra? Permissions seemed wonky (root/root) on the cached rust 1.9.0 on `servo-linux1` so I removed it

**Comment by SimonSapin** [comment]
@bors-servo retry

* > aneeshusa: I removed the cached 1.9.0 rust so hopefully that fixed it

**Comment by SimonSapin** [comment]
I *believe* that `_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure.` is not an intermittent failure, but rather the builder’s Python version not supporting TLS SNI (or something else TLS-related) for static.rust-lang.org’s certificate.

**Comment by SimonSapin** [comment]
@bors-servo retry

* With partially-downloaded (rustc but not std) 1.9.0 removed again from linux1 *and* commit e2262882ad8b77e05e56527e22d37a00ad3115d7 to not go through the CDN.

**Comment by SimonSapin** [comment]
@bors-servo r=larsbergstrom+SimonSapin

With an extra commit to download std even if rustc is already there.

**Pull request merged**
