### PR TITLE
Write a reftest for the background attribute on the body element

### PR DESCRIPTION
**Pull request by initsecret**
Testing the background in a basic way. #6838

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6992)

### CODE REVIEW

**Comment by jdm** [comment]
Thanks @s142857! There are a couple issues here:
* none of the tests are using the `<body background="foo">` feature that we want to check
* the tests are still in test/ref so they won't be found.

We will want to create a branch new pair of test files in tests/wpt/mozilla/tests/css, one of which should use `<body background>` and the other (the _ref.html file) should use a CSS `background-image` on the body element. Does that make sense?

**Comment by jdm** [comment]
The changes to tests/ref/background_image_position_a.html and tests/ref/background_none_a.html should be reverted, as well as the removal of tests/ref/400x400_green.png. We're also missing the new files.

**Comment by s142857** [comment]
i added them check added commit

**Comment by s142857** [comment]
i did not change the files, i actually copied them to wpt then changed then deleted the files

**Comment by s142857** [comment]
if you are talking about addition of link, it is harmless and makes it relatively easier in the future

**Comment by s142857** [comment]
i could remove the links if you want me to

**Comment by s142857** [comment]
thanks buddy

**Comment by jdm** [comment]
400x400_green.png was moved from test/ref, which will break any reftests there that use it. Please do remove the new `<link>` changes in the old tests, too.

**Comment by s142857** [comment]
I copied it, not moved, it i still exists in tests/ref

On Thu, Aug 6, 2015 at 11:05 AM, Josh Matthews <notifications@github.com>
wrote:

> 400x400_green.png was moved from test/ref, which will break any reftests
> there that use it. Please do remove the new <link> changes in the old
> tests, too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/servo/servo/pull/6992#issuecomment-128249797>.
>



-- 
Sanketh

**Comment by s142857** [comment]
ok, I will change the path


On Thu, Aug 6, 2015 at 11:12 AM, Sanketh Menda <mendasanketh@gmail.com>
wrote:

> I copied it, not moved, it i still exists in tests/ref
>
> On Thu, Aug 6, 2015 at 11:05 AM, Josh Matthews <notifications@github.com>
> wrote:
>
>> 400x400_green.png was moved from test/ref, which will break any reftests
>> there that use it. Please do remove the new <link> changes in the old
>> tests, too.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/servo/servo/pull/6992#issuecomment-128249797>.
>>
>
>
>
> --
> Sanketh
>



-- 
Sanketh

**Comment by s142857** [comment]
I'll place the 400*400_green.png back in its place and make a new file
(Like red_400*400.png) for wpt tests, there are more 16million possibilites
right!!

Give me 5hrs to do the needed, I need to go home and do it, I'm in school.

On Thu, Aug 6, 2015 at 11:13 AM, Sanketh Menda <mendasanketh@gmail.com>
wrote:

> ok, I will change the path
>
>
> On Thu, Aug 6, 2015 at 11:12 AM, Sanketh Menda <mendasanketh@gmail.com>
> wrote:
>
>> I copied it, not moved, it i still exists in tests/ref
>>
>> On Thu, Aug 6, 2015 at 11:05 AM, Josh Matthews <notifications@github.com>
>> wrote:
>>
>>> 400x400_green.png was moved from test/ref, which will break any reftests
>>> there that use it. Please do remove the new <link> changes in the old
>>> tests, too.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/servo/servo/pull/6992#issuecomment-128249797>.
>>>
>>
>>
>>
>> --
>> Sanketh
>>
>
>
>
> --
> Sanketh
>



-- 
Sanketh

**Pull request closed without merging**
