### PR TITLE
Force buttons to render as inline block. Apply button padding style as FF does.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5859)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r- for using Rust code to do this. I believe the same can be achieved through the user-agent stylesheet. `resources/servo.css` already contains `input, textarea, select { display: inline-block; }`. `button` could be added to the selector.

**Comment by SimonSapin** [comment]
If you really want to prevent author stylesheets for overriding this, `button { display: inline-block !important }` can do that. But I’m not convinced it’s the right thing to do.

**Comment by pcwalton** [comment]
Agreed with @SimonSapin; `!important` in the UA stylesheet has transcendent priority and should be preferred.

**Comment by glennw** [comment]
Using !important does sound like a better option.

@SimonSapin When you say above you're not convinced it's the right thing to do, did you see https://html.spec.whatwg.org/multipage/#the-button-element-2 ? Is there a better way to meet that part of the spec?

**Comment by SimonSapin** [comment]
I said that just out of general feeling that `!important` is sometimes dangerous. But it turns out that author-level style *can* override `display` on `button` in other browsers:

Test case: `data:text/html,<button%20style="display:block">Click</button>Text`

I believe the spec is not being precise enough with *expected to render as an 'inline-block' box*.

**Comment by glennw** [comment]
Hmmm, you're right - I'll find another way to fix the buttons on the site I'm testing.

**Comment by SimonSapin** [comment]
Is `button { display: inline-block }` in the UA stylesheet not enough?

**Comment by glennw** [comment]
I don't believe so - because when we override display: block in Servo, it takes up the full width of the screen in your example above (which is what I was trying to fix). I guess FF perhaps implicitly sets the width property of buttons, or something like that?

**Comment by SimonSapin** [comment]
Indeed. Adding `width: 100%` does what I expect in Firefox, but `width: auto` doesn’t. I don’t understand what in Firefox’s UA stylesheet is doing this, maybe it’s magic that’s part of `-moz-appearance: button`.

https://dxr.mozilla.org/mozilla-central/source/layout/style/forms.css

**Pull request closed without merging**
