### PR TITLE
Use StaticStructGenerator on Windows

### PR DESCRIPTION
**Pull request by paulrouget**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23502)

### CODE REVIEW

**Comment by paulrouget** [comment]
Not ready for review, just want to see if the CI is happy with this change (probably gonna break because of EGL missing).

**Comment by jdm** [comment]
Windows CI was green: https://treeherder.allizom.org/#/jobs?repo=servo-try&revision=64fa23fde90bd81507326c8b3124f676cdfc3315

**Comment by jdm** [comment]
Nevermind; none of our Windows CI builds libsimpleservo.

**Comment by jdm** [comment]
```
  = note: lld-link.exe: error: could not open libegl.lib: no such file or directory
```
As expected.

**Comment by paulrouget** [comment]
@jdm libsimpleservo will require egl.dll.

We could re-use the one provided by MS angle. Builds are available here https://www.nuget.org/packages/ANGLE.WindowsStore/ zip file is https://www.nuget.org/api/v2/package/ANGLE.WindowsStore/{version} (2.1.13 atm).

Not sure if we want to install it system-wise on the CI and let users provide their own EGL library (like we do for gstreamer) or, make it so that mach download that specific version of EGL.

Any recommendation?

**Comment by jdm** [comment]
I am inclined to have mach download it.

**Comment by paulrouget** [comment]
Closing in favor of #23696

**Pull request closed without merging**
