### PR TITLE
HTML5 Form Validation - Subsequent Steps

### PR DESCRIPTION
**Pull request by vinay92**
Implemented the subsequent steps mentioned in the spec.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10843)

### CODE REVIEW

**Comment by KiChjang** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/htmlformelement.rs, line 812 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGEzZ9gYgNYAyyjpTyT:-KGEzZ9gYgNYAyyjpTyU:-895531288) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmlformelement.rs#L812)):*
I'm quite sad that nobody realized that I left a comment here that makes life easier when implementing form validations for form control elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10843)*

**Comment by srm912** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/htmlformelement.rs, line 377 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGF8_-DFMrLLdWAGVQk:-KGF8_-DFMrLLdWAGVQl:69321937) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmlformelement.rs#L377)):*
Follow snake casing (`check_validity`) for function and variable names

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10843)*

**Comment by jdm** [comment]
r? @KiChjang 
Please reassign if you don't have time :)

**Comment by KiChjang** [comment]
-S-awaiting-review +S-needs-code-changes 

As I've noted previously, we really should make the best use of the existing `FormControl` infrastructure, this would save you a lot of headaches :). Most of my comments revolve around how exactly we should be utilizing it. Don't hesitate to ask questions if it's still unclear!

---

Reviewed 6 of 8 files at r1, 3 of 24 files at r4, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[components/script/dom/htmlformelement.rs, line 358 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFs6jSd0umf0sqYl3Y:-KGFs6jTY-xKLkBxXjDp:-1389167613) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmlformelement.rs#L358)):*
What we should do instead is to upcast err[0] into an `HTMLElement`, and then call `.Focus()`. I'm also not sure whether this is necessary. @jdm or @Ms2ger, should the first invalid form element request focus on itself?

---

*[components/script/dom/htmlformelement.rs, line 367 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFrQ8baw3ir4ERvHL1:-KGFrQ8cvWeKKd82AIll:1450131591) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmlformelement.rs#L367)):*
This also isn't how I imagine the check for validation candidate should be implemented. As I've noted further down in this file, we can just add member methods on implementors of `FormControl`.

---

*[components/script/dom/htmlformelement.rs, line 377 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGF8_-DFMrLLdWAGVQk:-KGFowdijkoWJEz54ndv:36038772) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmlformelement.rs#L377)):*
This shouldn't be implemented here; this is part of the [constraint validation API](https://html.spec.whatwg.org/multipage/forms.html#dom-cva-checkvalidity), which should live under `impl HTMLFormElementMethods for HTMLFormElement`.

---

*[components/script/dom/htmlformelement.rs, line 386 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFpRaGP8_NwamXxSTW:-KGFpRaHX_GUE3a-TVkb:-982639840) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmlformelement.rs#L386)):*
Ditto about being under `impl HTMLFormElementMethods for HTMLFormElement`.

---

*[components/script/dom/htmlformelement.rs, line 393 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFpYbqAiCF8J_R8n3g:-KGFpYbqAiCF8J_R8n3h:486043864) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmlformelement.rs#L393)):*
Ditto about member methods on implementors of `FormControl`.

---

*[components/script/dom/htmlformelement.rs, line 442 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFqEQpeaxHkNNaoTkf:-KGFqEQqUdgTcroOCpdO:644429903) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmlformelement.rs#L442)):*
nit: Ending brace on newline.

---

*[components/script/dom/htmlinputelement.rs, line 903 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFsdOUK9gEc_YH0l7X:-KGFsdOVTDP7eZ4I7ue4:379911759) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmlinputelement.rs#L903)):*
It doesn't sound quite right that the form element requests focus on the first errored element, only then to have all other invalid elements to request focus as well. I'd like to see the spec for this.

---

*[components/script/dom/htmlselectelement.rs, line 237 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFtdYvSXxuxwQ2Jn7L:-KGFtdYwlIpSrw5j243h:-1836944393) ([raw file](https://github.com/servo/servo/blob/1c195211470a5ae51baf103b34409330d76d9222/components/script/dom/htmlselectelement.rs#L237)):*
Where is this being called?

---

*[components/script/dom/htmltextareaelement.rs, line 373 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFu1Wfw7N1Emlk6SoS:-KGFu1Wfw7N1Emlk6SoT:959540766) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/htmltextareaelement.rs#L373)):*
Spec for this behaviour, please.

---

*[components/script/dom/validation.rs, line 8 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFuJNoVa8HeIfJ0IbG:-KGFuJNpcSqtvIah3EIH:-164123860) ([raw file](https://github.com/servo/servo/blob/c3f747c0be18348883871b082f408cbd5ab7d351/components/script/dom/validation.rs#L8)):*
I'm actually not convinced that this trait (or this file for the matter) should exist. Following on my coment with `FormControls`, it seems unnecessary to add another trait which all `FormControls` should implement.

---

*[components/script/dom/validitystate.rs, line 47 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFuhCI25IubOCuHUB1:-KGFuhCI25IubOCuHUB2:418687607) ([raw file](https://github.com/servo/servo/blob/81f6e70a623a6f11535322ed2ef954eafaf8c70c/components/script/dom/validitystate.rs#L47)):*
Revert this and add that newline back, please.

---

*[components/script/dom/validitystate.rs, line 74 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFwwdjuPPWDItU-NL2:-KGFwwdkSygOf026sI_c:320312585) ([raw file](https://github.com/servo/servo/blob/452be286a625029175a92d4bc2a462e5ab2af100/components/script/dom/validitystate.rs#L74)):*
I'm not convinced that this is the optimal way of handling form control validity. The code here is divorced from the actual elements that implements the constraint validation API. I propose to add value_missing, type_mismatch and other methods to the `FormControl` trait, and in here, downcast `self.element` to `FormControl` and call the methods appropriately.

---

*[components/script/dom/validitystate.rs, line 649 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFy0CAAfuYthzG4slf:-KGFy0CAAfuYthzG4slg:-1138950268) ([raw file](https://github.com/servo/servo/blob/452be286a625029175a92d4bc2a462e5ab2af100/components/script/dom/validitystate.rs#L649)):*
nit: Wrong indentation and space before `|`.

---

*[components/compositing/compositor.rs, line 1308 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFy9KzDaaksfMQnHVO:-KGFy9KzDaaksfMQnHVP:1938224598) ([raw file](https://github.com/servo/servo/blob/e695878c71b22baf813d1cc049699e3b856dfbbd/components/compositing/compositor.rs#L1308)):*
This seems unrelated to your changes, an error from rebasing?

---

*[components/compositing/constellation.rs, line 890 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFyLoiiY_z_ckXrA1b:-KGFyLoiiY_z_ckXrA1c:2143201124) ([raw file](https://github.com/servo/servo/blob/e695878c71b22baf813d1cc049699e3b856dfbbd/components/compositing/constellation.rs#L890)):*
Same for this file. Error from rebasing?

---

*[components/gfx/font_cache_thread.rs, line 173 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10843#-KGFyQ0juyyKPmxKkG22:-KGFyQ0juyyKPmxKkG23:2143201124) ([raw file](https://github.com/servo/servo/blob/e695878c71b22baf813d1cc049699e3b856dfbbd/components/gfx/font_cache_thread.rs#L173)):*
Same for this file. Error from rebasing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10843#-:-KGFyTZHJ3ErHbn_AKMf:-222213829)*

**Comment by KiChjang** [comment]
@vinay92 Is this ready for review? If not, just ping me whenever you want me to look at it.

**Comment by vinay92** [comment]
Hey Keith,

We are currently working on the changes you mentioned. We have an exam
tomorrow, once that is done, we will incorporate the remaining changes you
mentioned and ping you when it is ready for review.

Thank You,
Vinay.

**Comment by srm912** [comment]
Fixed errors while rebasing. No new code changes committed. Please do not review.

**Comment by raviflipsyde** [comment]
Hi @KiChjang ,
I am trying to fix the focus issue, when there is one or more invalid form element - user agent needs to focus on one of them. (spec: https://html.spec.whatwg.org/multipage/forms.html#interactively-validate-the-constraints)
as u advised, I've upcasted err[0] into an HTMLElement, and then call .Focus() on it.
The order in which the elements are getting focused is not in order though.

**Comment by KiChjang** [comment]
@raviflipsyde Is it because other invalid form elements are being focused as well? I had concerns about that in my review. Take a look at `htmlinputelement.rs` for example, it is requesting for focus when an "invalid" event is fired, causing it to conflict with your changes.

**Comment by raviflipsyde** [comment]
I guess that needs to be removed from there.

**Comment by vinay92** [comment]
@KiChjang We have made the changes you mentioned in the review. The branch is now ready for review. Thanks.

**Comment by KiChjang** [comment]
I don't think I have time for reviewing this in the near future. r? @jdm

**Comment by jdm** [comment]
I have the following concerns about this pull request:
* there is a lot of duplicated code (such as `candidate_for_validation` and `satisfies_constraints`)
* the mechanism of splitting each possible constraint into a separate function yields a lot of stub methods that just return false; it might make more sense to have a single method that returns a bit flags that represent failed constraints.
* there are several places that downcast to a particular element type and call the same sets of methods for each one - this would be better handled by obtaining a trait object and invoking the methods on that instead (like how `as_maybe_activatable` is used)
* we probably don't want to use regular expressions for the number, email, and URL input types since there are a lot of edge cases possible
* many of the validation methods could benefit from sharing common code (eg. TooShort, RangeUnderflow, RangeOverflow in HTMLInputElement)
* there are a number of instances where we parse strings as numbers and unwrap the result, which will panic for non-numeric values
* not sure why the handle_event method is added for HTMLSelectElement

@KiChjang may have other more general architectural concerns. I'm closing this PR because I suspect that the original authors are not planning to continue working on it; if that assumption is untrue, they are welcome to do so and address the aforementioned concerns! I'm linking to this work from #11444 as the basis for any future implementation of the form validation.

**Comment by jdm** [comment]
That being said - thank you for doing this work and sharing your efforts! This will help us make better decisions when the time comes for someone else to finish your work.

**Pull request closed without merging**
