### PR TITLE
Update `ipc-channel` to pick up the improved error reporting.

### PR DESCRIPTION
**Pull request by pcwalton**
Intended to help diagnose intermittent failures.

r? @jdm or @larsbergstrom (or whoever)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8660)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

_[components/servo/Cargo.lock, line 943 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8660#-K3qqMBbeYYzkAzFHz1P:-K3qqMBbeYYzkAzFHz1Q:542477353) ([raw file](https://github.com/servo/servo/blob/e16295c43f5b20c41769f0c31b1be717b4671c1d/components/servo/Cargo.lock#L943)):_
It looks like there are now two versions of ipc-channel in use. Is there any way to remove this old one?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8660)_

**Comment by larsbergstrom** [comment]
Reviewed 20 of 22 files at r1.
Review status: 20 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

_[ports/cef/Cargo.lock, line 892 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8660#-K3qqpo9ba0ITZk3Fh_E:-K3qqpo9ba0ITZk3Fh_F:-1325761164) ([raw file](https://github.com/servo/servo/blob/e16295c43f5b20c41769f0c31b1be717b4671c1d/ports/cef/Cargo.lock#L892)):_
this version does not have your change

---

_[ports/gonk/Cargo.lock, line 872 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8660#-K3qqnmJGi2o7IkAz6b9:-K3qqnmJGi2o7IkAz6bA:-1325761164) ([raw file](https://github.com/servo/servo/blob/e16295c43f5b20c41769f0c31b1be717b4671c1d/ports/gonk/Cargo.lock#L872)):_
this version does not have your change

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8660)_

**Comment by larsbergstrom** [comment]
I think you need a `./mach update-cargo -p ipc-channel` or similar to update all of the Cargo.lock files and toss out the old version.

**Comment by pcwalton** [comment]
Updated. r? @larsbergstrom

**Comment by larsbergstrom** [comment]
Reviewed 1 of 22 files at r1, 3 of 4 files at r2.
Review status: 22 of 23 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8660)_

**Comment by larsbergstrom** [comment]
Hrm, though this might not work - did you do a `cargo build` and see if the Cargo.lock files change? Travis is reporting:
```
The command "bash etc/ci/manifest_changed.sh" exited with 1.
```
Which means that Cargo.lock changed on the builder after doing a build.

**Comment by jdm** [comment]
That was preexisting and fixed in a subsequent PR.

**Comment by pcwalton** [comment]
What do I need to do here?

**Comment by jdm** [comment]
Nothing. It's in the queue.

**Comment by pcwalton** [comment]
Odd looking timeout. @jdm/@larsbergstrom, any ideas?

**Comment by larsbergstrom** [comment]
@bors-servo retry
 - #8502

**Pull request merged**
