### PR TITLE
Remove outdated test results

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24292)

### CODE REVIEW

**Comment by SimonSapin** [comment]
With diff stats like “+0 −13,433” I want to say if CI is happy I’m happy and rubber-stamp, but still: did you write a script to automate this and find which results are outdated? Would it be useful to include that script, perhaps in `etc/`, so we can run it again some time later?

**Comment by jdm** [comment]
This was not a script.

**Comment by SimonSapin** [comment]
Oh. Then I’m curious what the process was. Eyeballing each file one by one seems like it would take days?

**Comment by SimonSapin** [comment]
In any case,

@bors-servo r+

Based on diff stat, and GitHub’s “file filter” saying only `.ini` files are changed.

**Comment by jdm** [comment]
@bor-servo retry
* #24299

**Pull request merged**
