### PR TITLE
Compile less

### LINKED ISSUE #21332: Gradle build performs redundant custom step multiple times
When packaging the android build, I see 4-5 tasks that look like:
```
> Task :servoview:ndkbuildcompileMainArmv7DebugSources
[armeabi-v7a] Gdbserver      : [arm-linux-androideabi-4.9] /Users/jdm/src/master-servo/target/armv7-linux-androideabi/debug/apk/jniLibs/armeabi-v7a/gdbserver
[armeabi-v7a] Gdbsetup       : /Users/jdm/src/master-servo/target/armv7-linux-androideabi/debug/apk/jniLibs/armeabi-v7a/gdb.setup
[armeabi-v7a] Install        : libc++_shared.so => /Users/jdm/src/master-servo/target/armv7-linux-androideabi/debug/apk/jniLibs/armeabi-v7a/libc++_shared.so
[armeabi-v7a] Install        : libsimpleservo.so => /Users/jdm/src/master-servo/target/armv7-linux-androideabi/debug/apk/jniLibs/armeabi-v7a/libsimpleservo.so
```
This is redundant, and the following patch significantly improves the speed of the packaging step:
```diff
diff --git a/support/android/apk/servoview/build.gradle b/support/android/apk/servoview/build.gradle
index 17ec228306..d85396a9f5 100644
--- a/support/android/apk/servoview/build.gradle
+++ b/support/android/apk/servoview/build.gradle
@@ -147,7 +147,7 @@ android {
     // Call our custom NDK Build task using flavor parameters
     tasks.all {
         compileTask ->
-            Pattern pattern = Pattern.compile(/^compile[A-Z][\w\d]+([A-Z][\w\d]+)(Debug|Release)/)
+            Pattern pattern = Pattern.compile(/^compile[A-Z][\w\d]+([A-Z][\w\d]+)(Debug|Release)Sources/)
             Matcher matcher = pattern.matcher(compileTask.name)
             if (!matcher.find()) {
                 return
```
cc @paulrouget

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #21332

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21361)

### CODE REVIEW

**Comment by jdm** [comment]
Clearly my change broke something important.

**Comment by MortimerGoro** [comment]
It looks good. We should only call the NDK build on that specific task.

**Pull request merged**
