### PR TITLE
[WIP RFC] Enforce rustfmt on automation.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20617)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo try

 * (should be green since I changed no rust code)

**Comment by emilio** [comment]
@bholley how do you feel about this? We'd need to make an easy way of running this to apply the formatting changes but other than that...

**Comment by emilio** [comment]
Also, anyone that would like to comment on whether we should do it or not, or maybe just filtering some paths or what not, please let me know. cc @nox / @SimonSapin / @heycam / @Manishearth / anyone else.

**Comment by emilio** [comment]
Well, tidy failed (lol), but the rustfmt lint itself did not :)

**Comment by CYBAI** [comment]
Implemented in #22126

**Pull request closed without merging**
