### PR TITLE
Bug1367283

### PR DESCRIPTION
**Pull request by dadaa**
This PR is to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1367283

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes. The tests will land in dom/animation/test of m-c.  Test code is patch 9 of https://bugzilla.mozilla.org/show_bug.cgi?id=1367283

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17075)

### CODE REVIEW

**Comment by dadaa** [comment]
These patches have been reviewed by @hiikezoe

**Comment by emilio** [comment]
This seems to be failing a unit test (not sure if legitimately or not):

```
---- parsing::ui::test_moz_user_select stdout ----
	thread 'parsing::ui::test_moz_user_select' panicked at 'Failed to parse -moz-none: ()', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:761
  11: style_tests::parsing::ui::test_moz_user_select::{{closure}}
             at ./parsing/mod.rs:67
  12: style_tests::parsing::parse
             at ./parsing/mod.rs:26
  13: style_tests::parsing::ui::test_moz_user_select
             at ./parsing/ui.rs:23
  14: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1440
             at /checkout/src/libcore/ops.rs:2626
             at /checkout/src/libtest/lib.rs:140
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
```

You can run them with `./mach test-unit -p style`.

**Comment by dadaa** [comment]
Thanks @emilio !
I fixed the fail.

**Pull request merged**
