### PR TITLE
Use build-std instead of xargo.

### PR DESCRIPTION
**Pull request by jdm**
The changes to num-integer and indexmap are to work around https://github.com/cuviper/autocfg/issues/34.

### CODE REVIEW

**Comment by jdm** [comment]
```
error: failed to run custom build command for `num-traits v0.2.12`
Caused by:
  process didn't exit successfully: `C:\Users\task_1600367902\repo\target\debug\build\num-traits-e96d93a113616dca\build-script-build` (exit code: 101)
  --- stderr
  error[E0463]: can't find crate for `std`
    |
    = note: the `x86_64-uwp-windows-msvc` target may not be installed
  error: aborting due to previous error
  For more information about this error, try `rustc --explain E0463`.
  error[E0463]: can't find crate for `core`
    |
    = note: the `x86_64-uwp-windows-msvc` target may not be installed
  error: aborting due to previous error
  For more information about this error, try `rustc --explain E0463`.
  warning: autocfg could not probe for `std`
  error[E0463]: can't find crate for `std`
    |
    = note: the `x86_64-uwp-windows-msvc` target may not be installed
  error: aborting due to previous error
```
Sigh.

**Comment by greg904** [comment]
Could this error be fixed by https://github.com/rust-num/num-traits/pull/185? It seems to be related. That fix is included in the next version of num-traits: v0.2.13. I saw that the PR to update num-traits (https://github.com/servo/servo/pull/27822) was closed, but I don't understand why as the CI seems to build and the diff is just two lines of code. Sorry I don't really understand much about Servo development.

**Comment by jdm** [comment]
I don't see how that issue is related at all.

**Comment by jdm** [comment]
You're right, I just tested locally and was able to reproduce the issue in a simple repo that depended on num_traits 0.2.12 with the i128 feature enabled, and I could not reproduce with 02.13.

**Comment by jdm** [comment]
Indexmap is another crate with a build script that uses autocfg to determine if certain features are present.

**Comment by jdm** [comment]
Filed https://github.com/cuviper/autocfg/issues/34, which is the same underlying issue that the num-traits upgrade worked around.

**Review by SimonSapin — APPROVED** [review]
Looks good. r=me with a rebase to solve a merge conflict.

**Pull request merged**
