### PR TITLE
Issue #9097: Don't panic when calling *VertexAttrib* with invalid indices

### PR DESCRIPTION
**Pull request by simartin**
Fixes https://github.com/servo/servo/issues/9097

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9102)

### CODE REVIEW

**Comment by jdm** [comment]
Relevant Gecko code is http://mxr.mozilla.org/mozilla-central/source/dom/canvas/WebGLContextVertices.cpp#288 and http://mxr.mozilla.org/mozilla-central/source/dom/canvas/WebGLContextValidate.cpp#539 .

**Comment by ecoal95** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/canvas/webgl_paint_task.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9102#-K6p6P67OPgZjXKhbiD8:-K6p6P67OPgZjXKhbiD9:1023866132) ([raw file](https://github.com/servo/servo/blob/b9531f4d617c63928ee346072062691f38b174c3/components/canvas/webgl_paint_task.rs#L60)):*
Good work finding the root cause of the panic :)

I think this is not the best solution though, since this check is needed in the DOM side too, and should generate an error there, instead of silently returning.

Normally whenever the WebGL task panics due to a gl error, it means that that error should have been handled in the DOM side.

As a quick fix, we could make these calls synchronous, and return a WebGLResult, but long term it's probably more efficient to make a `GLLimits` or `GLContextInfo` structure, pass it on context creation, and refresh it when needed so we can do the checks before sending messages all over the place.

It'd be a good idea to add it to https://github.com/ecoal95/rust-offscreen-rendering-context/, so it can be re-used, over all in WebRender (don't forget to derive `Serialize` so it can be sent).

For now it could just have a single member (`max_vertex_attribs`), but we should be able to add more context info there for use in the DOM side.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9102)*

**Comment by simartin** [comment]
*[components/canvas/webgl_paint_task.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9102#-K6p6P67OPgZjXKhbiD8:-K6pFA-hVf91ShzwTk-W:-1182686101) ([raw file](https://github.com/servo/servo/blob/b9531f4d617c63928ee346072062691f38b174c3/components/canvas/webgl_paint_task.rs#L60)):*
Thanks for the hint. I'll work in that direction...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9102)*

**Comment by simartin** [comment]
*[components/canvas/webgl_paint_task.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9102#-K6p6P67OPgZjXKhbiD8:-K7bKcn2p9YVyx06lF5R:-381562552) ([raw file](https://github.com/servo/servo/blob/b9531f4d617c63928ee346072062691f38b174c3/components/canvas/webgl_paint_task.rs#L60)):*
rust-offscreen-rendering-context PR submitted: https://github.com/ecoal95/rust-offscreen-rendering-context/pull/48

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9102)*

**Comment by jdm** [comment]
@ecoal95 What's the status here? Is this waiting on changes from @simartin or review from you?

**Comment by ecoal95** [comment]
It's waiting changes from @simartin, I initially forgot to update the labels when reviewing, I'll do it now.

**Comment by jdm** [comment]
I filed #9958 to keep track of this work. Feel free to reopen this PR if you want to keep working on it!

**Pull request closed without merging**
