### PR TITLE
dom: Remove CSSStyleDeclaration.setPropertyValue/setPropertyPriority.

### PR DESCRIPTION
**Pull request by emilio**
They were removed from the spec, see https://github.com/w3c/csswg-drafts/issues/2680, and setPropertyValue was wrongly implemented anyway.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20901)

### CODE REVIEW

**Comment by jdm** [comment]
```
{"status": "FAIL", "group": "default", "message": "/_mozilla/css/setpropertypriority.html 8702dc9d5448a9b35232255293ad6d410b2fb14c\n/_mozilla/css/setpropertypriority_ref.html 29e1ae96db7c0c4964506ddc0f0e83feff4dea93\nTesting 8702dc9d5448a9b35232255293ad6d410b2fb14c == 29e1ae96db7c0c4964506ddc0f0e83feff4dea93", "stack": null, "subtest": null, "test": "/_mozilla/css/setpropertypriority.html", "line": 48117, "action": "test_result", "expected": "PASS"} {"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Historical CSSStyleDeclaration member: setPropertyValue", "test": "/css/cssom/historical.html", "line": 116281, "action": "test_result", "expected": "FAIL"} {"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Historical CSSStyleDeclaration member: setPropertyPriority", "test": "/css/cssom/historical.html", "line": 116282, "action": "test_result", "expected": "FAIL"} 
```

**Comment by emilio** [comment]
@bors-servo r=jdm

 * Removed the `/_mozilla/` test, and updated the expectations to account for the new passes.

**Comment by CYBAI** [comment]
@bors-servo retry

- websocket failure

**Pull request merged**
