### PR TITLE
Add bindings support for unrestricted float values

### LINKED ISSUE #707: Add bindings support for unrestricted float values
This error happen on parsing HTMLMediaElement.webidl.
HTMLMediaElement.webidl: http://mxr.mozilla.org/mozilla-central/source/dom/webidl/HTMLMediaElement.webidl

```
Traceback (most recent call last):
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/pythonpath.py", line 60, in <module>
    main(sys.argv[1:])
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/pythonpath.py", line 52, in main
    execfile(script, frozenglobals)
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/GlobalGen.py", line 88, in <module>
    main()
  File "/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/GlobalGen.py", line 66, in main
    parser.parse(''.join(lines), fullPath)
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/parser/WebIDL.py", line 3885, in parse
    self._productions.extend(self.parser.parse(lexer=self.lexer,tracking=True))
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/ply/ply/yacc.py", line 263, in parse
    return self.parseopt(input,lexer,debug,tracking,tokenfunc)
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/ply/ply/yacc.py", line 792, in parseopt
    tok = self.errorfunc(errtoken)
  File "/Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/parser/WebIDL.py", line 3835, in p_error
    raise WebIDLError("invalid syntax", [Location(self.lexer, p.lineno, p.lexpos, self._filename)])
WebIDL.WebIDLError: error: invalid syntax, /Users/tetsuharu/src/servo/src/components/script/dom/bindings/codegen/HTMLMediaElement.webidl line 55:34
  readonly attribute unrestricted double duration;
                                  ^
make: *** [/Users/tetsuharu/src/servo//src/components/script/dom/bindings/codegen/ParserResults.pkl] Error 1
```

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
- Fix #707
- Take over from #5106

### CODE REVIEW

**Comment by saneyuki** [comment]
@Ms2ger r?

**Comment by jdm** [comment]
Good work! It sounds like it's worth filing a bug on the spec about the putImageData problem you noticed.

**Comment by saneyuki** [comment]
> it's worth filing a bug on the spec about the putImageData problem you noticed.

Filed :)
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28327

**Comment by jdm** [comment]
The fixups look fine; go ahead and squash them.

**Comment by saneyuki** [comment]
@jdm thank you!

**Pull request closed without merging**
