### PR TITLE
Update webdriver to 0.39

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23234)

### CODE REVIEW

**Comment by Eijebong** [comment]
```
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/_webgl/conformance/ogles/GL/asin/asin_001_to_006.html", 
    "line": 52499, 
    "action": "test_result", 
    "expected": "OK"
}
```

Pretty sure it's unrelated

**Comment by jdm** [comment]
Fascinating - this update totally breaks the tests that rely on the webdriver server.

**Comment by Eijebong** [comment]
Oh, my bad... Should've read the code more carefully :)

@bors-servo try=wpt

**Comment by Eijebong** [comment]
Yup, that fixed all the servodriver tests

**Pull request merged**
