### PR TITLE
Add alphabetical order check for use statements

### LINKED ISSUE #7112: Check that consecutive use statements in Rust files are in alphabetical order
I propose the following rule:
* for each Rust source file, look at every line
* if the whitespace-stripped line starts with `use `, append the path up to any `{` to _imports_
* if the line is empty
  * let _sorted_ be _imports_ sorted alphabetically
  * if _sorted_ and _imports_ differ, report the first import that does not match
  * reset _imports_ to the empty list

This allows us to retain our sorted lists that are separated by whitespace that currently exist today.

Code: python/tidy.py

### PR DESCRIPTION
**Pull request by tafia**
close #7112

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7265)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

Thank you for your PR. Unfortunately, this can't land until we have all these failures fixed. Is that something you'd like to work on?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[python/tidy.py, line 179 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7265#-Jx0JgNa0CIr5Gia9zoc)** ([raw file](https://github.com/servo/servo/blob/020c8622cddfbfde0f882a234d04492e07c4c8ed/python/tidy.py#L179)):</sup>
No need for this to be defined here.

---

<sup>**[python/tidy.py, line 257 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7265#-Jx0JU_qm-dUTPYWr7Ul)** ([raw file](https://github.com/servo/servo/blob/020c8622cddfbfde0f882a234d04492e07c4c8ed/python/tidy.py#L257)):</sup>
Maybe: `use = line[4:]` ...

---

<sup>**[python/tidy.py, line 258 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7265#-Jx0JNxvkwZAAvSb-qok)** ([raw file](https://github.com/servo/servo/blob/020c8622cddfbfde0f882a234d04492e07c4c8ed/python/tidy.py#L258)):</sup>
`if match < 0`

---

<sup>**[python/tidy.py, line 266 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7265#-Jx0J95fVBhOR8zHfqUq)** ([raw file](https://github.com/servo/servo/blob/020c8622cddfbfde0f882a234d04492e07c4c8ed/python/tidy.py#L266)):</sup>
There's a `sorted()` function you can use.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7265)

**Comment by tafia** [comment]
Thanks for the review!
Working on your comments + all these new failures. Should I push all fixes in this pull request?

**Comment by Ms2ger** [comment]
Doing it here makes sense to me.

**Comment by tafia** [comment]
Should be all good now ...
I finally sorted the `{...}` groups as well (it feels better).

I started doing it manually ... then used this script (my 2nd python script ever!):

```py
import os

from tempfile import mkstemp
from shutil import move
from os import remove, close

def replace_uses(file_path):
    #Create temp file
    fh, abs_path = mkstemp()
    with open(abs_path,'w') as new_file:
        with open(file_path) as old_file:
            uses = []
            for line in old_file:
                if line.lstrip().startswith("use "):
                    uses.append(line[:len(line)-2])
                else:
                    if len(uses) > 0:
                        new_file.write("".join([u + ";\n" for u in sorted(uses)]))
                        uses = []
                    new_file.write(line)
    close(fh)
    #Remove original file
    remove(file_path)
    #Move new file
    move(abs_path, file_path)


# navigate the entire directories and replace uses
for root, subdirs, files in os.walk("./"):
    for f in files:
        if f.endswith(".rs"):
            filePath = os.path.join(root, f)
            replace_uses(filePath)
```

**Comment by Ms2ger** [comment]
Maybe squash into two commits: first one that fixes all the `.rs` files, and then on top of that a commit to add the check to the python script.

**Comment by tafia** [comment]
Fine! I'll try to do it asap.

**Comment by tafia** [comment]
Squashed and rebased (was failing the tests again). @Ms2ger let me know!

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r+ p=1000

**Comment by tafia** [comment]
Thanks

**Pull request merged**
