### PR TITLE
Add multiple WebGL calls and improve error detection

### PR DESCRIPTION
**Pull request by emilio**
Since it probably won't merge until multiprocess lands, I plan to use this PR to keep improving WebGL support until it can land.

Main TODOs are integration of tests, since it seems https://github.com/KhronosGroup/WebGL/issues/1105 is going nowhere, adding missing calls and proper painting via native surfaces instead of readback.

I can't resolve conflicts right now because of time but I will do it soon.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6770)

### CODE REVIEW

**Comment by Ms2ger** [comment]
We'll likely impose a moratorium on new WebGL features until e10s (electrolysis, multiprocess Servo) lands.

**Comment by ecoal95** [comment]
@Ms2ger yep, that's why I marked it as WIP and didn't take the time to resolve conflicts :P

**Comment by pcwalton** [comment]
NB: e10s for WebGL has landed, so full speed ahead here!

**Comment by ecoal95** [comment]
@pcwalton Nice then :) in that case this can be reviewed and I'll keep working on top of it, I just rebased it.

r? @pcwalton @jdm @Ms2ger

**Comment by ecoal95** [comment]
Arrg, forgot to update gleam with my local version. My fault, I'll do it ASAP.

**Comment by ecoal95** [comment]
This is blocked until gleam is published to crates.io

**Comment by metajack** [comment]
@glennw Can you publish a new gleam? Or do we have to wait for upstream?

**Comment by glennw** [comment]
@metajack We are the upstream :) I've published 0.1.6 on crates.io.

**Comment by ecoal95** [comment]
Once #6830 lands this should be mergeable :)

**Comment by metajack** [comment]
@bors-servo retry

This is ready to go now.

**Comment by metajack** [comment]
Sigh. Those functions don't exist on Android. @glennw thoughts?

**Comment by glennw** [comment]
@metajack desktop GL has glClearDepth() and glDepthRange() which take f64, while es2 has glClearDepthf() and glDepthRangef() which take f32 (note the f on the end of the function names). It should be possible to abstract this in gleam.

**Comment by ecoal95** [comment]
I need to complete the reftest and update gleam yet, didn't have the time
today :/

**Comment by jdm** [comment]
Ah, my mistake. I didn't notice the new commits since the previous attempt to merge this :/

**Comment by ecoal95** [comment]
r? @jdm 
Rebased and updated gleam so this should be ready to merge :P

See the commit notes on the update to see why it also updates other crates and on the reftest to see why it's not enabled.

**Comment by ecoal95** [comment]
Unbitrotted again, for some reason the S-needs-rebase flag didn't disappear (cc/ @jdm)

**Comment by jdm** [comment]
I'll try to review this tomorrow.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r1, 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 19 unresolved discussions, all commit checks successful.

---

<sup>**[components/canvas/webgl_paint_task.rs, line 164 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZtO-ANl2hH084BM2O)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/canvas/webgl_paint_task.rs#L164)):</sup>
Let's make this message take a u32 instead of whatever it currently does.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 396 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZtboyTUl_iKq7i-RP)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/canvasrenderingcontext2d.rs#L396)):</sup>
I would prefer separate `window` and `canvas` bindings here.

---

<sup>**[components/script/dom/webglbuffer.rs, line 21 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZu6ZFFArEfso31R1I)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglbuffer.rs#L21)):</sup>
The target to which this buffer was bound the first time.

---

<sup>**[components/script/dom/webglbuffer.rs, line 60 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZuGDdiIa_BB-eYrG4)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglbuffer.rs#L60)):</sup>
Let's not add these annotations unless we discover performance problems that they solve.

---

<sup>**[components/script/dom/webglbuffer.rs, line 66 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZuSFVkUaLvv3xwoIc)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglbuffer.rs#L66)):</sup>
We could enforce this by creating `BufferTarget(u32)` and `ValidatedBufferTarget(u32)` types, with a `validate(self) -> ValidatedBufferTarget` method present on `BufferTarget`, then make this method only take `ValidatedBufferTarget` and only pass validated ones in the webgl messages. That's fine as a followup issue, though.

---

<sup>**[components/script/dom/webglbuffer.rs, line 79 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZv3DLfQdKvwBC8x3S)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglbuffer.rs#L79)):</sup>
Remove this unless it's solving a known problem.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 65 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZw4QIrU75D-cPS0ES)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L65)):</sup>
I'm not sure that this macro is pulling its weight.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 80 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZwFRG-MxebkJJQO51)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L80)):</sup>
I think we can use `#[derive(HeapSizeOf)]` on TextureUnpacking instead.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 87 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZwJq30FI8gQEiizI8)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L87)):</sup>
Same here for deriving JSTraceable.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 148 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZy4ZQ8X9Y9RWiNYzv)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L148)):</sup>
Remove this unless it is solving a problem.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 670 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZzjGTELQ4pNWA2v9f)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L670)):</sup>
http://doc.servo.org/num/traits/trait.Float.html#tymethod.is_nan exists; why not use it now?

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 840 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_-7ZTx9wviWLLD-AH)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L840)):</sup>
Let's have a `let global` in here to break this up.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 848 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_-GDFjVEkWsp3g97k)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L848)):</sup>
`let window` and `let canvas`, please.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 936 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_07MF4YUuYZ5EjsRs)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L936)):</sup>
Remove this.

---

<sup>**[components/script/dom/webgltexture.rs, line 23 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_0DSBumB-TO8pvQCj)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webgltexture.rs#L23)):</sup>
The target to which this texture...

---

<sup>**[components/script/dom/webgltexture.rs, line 63 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_0GaApOazW9ZA7K2b)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webgltexture.rs#L63)):</sup>
Let's make an enum here instead of two Option parameters.

---

<sup>**[components/script/dom/webgltexture.rs, line 67 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_0KoGJn3Y5-lDKRQD)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webgltexture.rs#L67)):</sup>
Remove this.

---

<sup>**[components/script/dom/webgltexture.rs, line 87 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_0QB0gJ2P_wFednO6)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webgltexture.rs#L87)):</sup>
Remove thi.

---

<sup>**[tests/ref/basic.list, line 380 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_17IIrT9p0jqdnayh)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/tests/ref/basic.list#L380)):</sup>
Does using `reftest-wait` make this test more reliable? http://mxr.mozilla.org/servo/source/tests/ref/iframe/hide_and_show.html?force=1#17

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6770)

**Comment by ecoal95** [comment]
Review status: 8 of 15 files reviewed at latest revision, 19 unresolved discussions, all commit checks successful.

---

<sup>**[components/canvas/webgl_paint_task.rs, line 164 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZtO-ANl2hH084BM2O)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/canvas/webgl_paint_task.rs#L164)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 396 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZtboyTUl_iKq7i-RP)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/canvasrenderingcontext2d.rs#L396)):</sup>
Done.

---

<sup>**[components/script/dom/webglbuffer.rs, line 21 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZu6ZFFArEfso31R1I)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglbuffer.rs#L21)):</sup>
Done.

---

<sup>**[components/script/dom/webglbuffer.rs, line 60 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZuGDdiIa_BB-eYrG4)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglbuffer.rs#L60)):</sup>
Done.

---

<sup>**[components/script/dom/webglbuffer.rs, line 66 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZuSFVkUaLvv3xwoIc)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglbuffer.rs#L66)):</sup>
At the end the valid buffer targets are just ARRAY_BUFFER or ELEMENT_ARRAY_BUFFER, we could create an enum to enforce type safety there, but since we'll need to convert back to a u32, I don't know if it's worth it. Anyways I agree it can be done as a followup.

---

<sup>**[components/script/dom/webglbuffer.rs, line 79 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZv3DLfQdKvwBC8x3S)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglbuffer.rs#L79)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 65 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZw4QIrU75D-cPS0ES)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L65)):</sup>
You're right, I imported the `WebGLError` variants and renamed `handle_webgl_error` to just `webgl_error`.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 80 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZwFRG-MxebkJJQO51)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L80)):</sup>
True, sorry! I tried to put them before the macro and the compiler didn't like it.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 87 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZwJq30FI8gQEiizI8)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L87)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 148 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZy4ZQ8X9Y9RWiNYzv)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L148)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 670 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-JxZzjGTELQ4pNWA2v9f)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L670)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 840 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_-7ZTx9wviWLLD-AH)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L840)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 848 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_-GDFjVEkWsp3g97k)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L848)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 936 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_07MF4YUuYZ5EjsRs)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webglrenderingcontext.rs#L936)):</sup>
Done.

---

<sup>**[components/script/dom/webgltexture.rs, line 23 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_0DSBumB-TO8pvQCj)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webgltexture.rs#L23)):</sup>
Done.

---

<sup>**[components/script/dom/webgltexture.rs, line 63 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_0GaApOazW9ZA7K2b)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webgltexture.rs#L63)):</sup>
True, that was dumb on my side.

---

<sup>**[components/script/dom/webgltexture.rs, line 67 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_0KoGJn3Y5-lDKRQD)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webgltexture.rs#L67)):</sup>
Done.

---

<sup>**[components/script/dom/webgltexture.rs, line 87 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_0QB0gJ2P_wFednO6)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/components/script/dom/webgltexture.rs#L87)):</sup>
Done.

---

<sup>**[tests/ref/basic.list, line 0 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6770#-Jx_17IIrT9p0jqdnayh)** ([raw file](https://github.com/servo/servo/blob/aa85e28b6d2a616cef0bdf51a9a50bc58bbea3c4/tests/ref/basic.list#L0)):</sup>
Yes, totally! Didn't know about that, thanks! :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6770)

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for the PR!

---

Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6770)

**Pull request merged**
