### PR TITLE
M1503 : Integrate XML Parser : First 2 of 4 Subsequent Steps

### PR DESCRIPTION
**Pull request by Jigar24**
Hi,

This is for NCSU Fall 15 project M1503 for Mozilla.

We have included changes for first 2 of the 4 subsequent steps for M1503 (Integrate XML Parser) in this pull request. 
https://github.com/servo/servo/wiki/Integrate-xml5ever

Kindly review !

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8746)

### CODE REVIEW

**Comment by jdm** [comment]
Great work! I'd like to hook up the actual parser before we merge these changes though, since parse_xml currently is an empty function :)
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/dom/servoxmlparser.rs, line 18 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4OGm-MYxDHyG735LQb:-K4OGm-MYxDHyG735LQc:-1350240055) ([raw file](https://github.com/servo/servo/blob/7232ab0c24ff7455f831c47cee940c7450291a5b/components/script/dom/servoxmlparser.rs#L18)):*
This doesn't appear to be used.

---

*[components/script/dom/servoxmlparser.rs, line 24 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4OGo2sOivc0yB4oKeg:-K4OGo2sOivc0yB4oKeh:-503705757) ([raw file](https://github.com/servo/servo/blob/7232ab0c24ff7455f831c47cee940c7450291a5b/components/script/dom/servoxmlparser.rs#L24)):*
Since there's only one caller (in xml.rs), I think we can just inline this method body there instead of defining it separately.

---

*[components/script/parse/xml.rs, line 97 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4OGvkzNNWo_XFrsP5X:-K4OGvkzNNWo_XFrsP5Y:-339006146) ([raw file](https://github.com/servo/servo/blob/7232ab0c24ff7455f831c47cee940c7450291a5b/components/script/parse/xml.rs#L97)):*
It would be nice to actually make use of the new code in this PR by invoking the parser here, like in html.rs.

---

*[components/script/script_task.rs, line 1648 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4OG0UC_8TBlR7BO8EC:-K4OG0UC_8TBlR7BO8ED:-1232944080) ([raw file](https://github.com/servo/servo/blob/d284349476adc267a3410cb0c59d050cd074d151/components/script/script_task.rs#L1648)):*
nit: let's remove this empty line here

---

*[components/script/script_task.rs, line 1668 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4OGCdk7ePIDhuDVXmo:-K4OGCdlVNVR_1-lJJiI:-1355713606) ([raw file](https://github.com/servo/servo/blob/d284349476adc267a3410cb0c59d050cd074d151/components/script/script_task.rs#L1668)):*
Instead of duplicating the creation, let's do this:
```rust
let is_html_document = match metadata.content_type {
    Some(ContentType(Mime(TopLevel::Text, SubLevel::Xml, _))) => IsHTMLDocument::NonHTMLDocument,
    _ => IsHTMLDocument::HTMLDocument,
};
```
and pass `is_html_document` as an argument when calling `Document::new`.

---

*[components/script/script_task.rs, line 1736 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4OG_waNBnsZd_j3wsG:-K4OG_waNBnsZd_j3wsH:-2081024946) ([raw file](https://github.com/servo/servo/blob/d284349476adc267a3410cb0c59d050cd074d151/components/script/script_task.rs#L1736)):*
nit: let's remove this empty line.

---

*[components/script/script_task.rs, line 1669 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4OHIyTE8T5IHeUKqdc:-K4OHIyTE8T5IHeUKqdd:-792304118) ([raw file](https://github.com/servo/servo/blob/1b2e4c4bf3ae607b717ba66b6212faf6624aeb2f/components/script/script_task.rs#L1669)):*
nit: please match the indentation of the surrounding code.

---

*[components/script/script_task.rs, line 1740 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4OHNiFoUQaNr7mzZMT:-K4OHNiFoUQaNr7mzZMU:-792304118) ([raw file](https://github.com/servo/servo/blob/1b2e4c4bf3ae607b717ba66b6212faf6624aeb2f/components/script/script_task.rs#L1740)):*
nit: please match the indentation of the surrounding code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8746#-:-K4OHUm_pFB0mCIpgLqq:575895064)*

**Comment by Jigar24** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/parse/xml.rs, line 97 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4OGvkzNNWo_XFrsP5X:-K4Vf0CSDjPWqxREbE-2:-1671373206) ([raw file](https://github.com/servo/servo/blob/7232ab0c24ff7455f831c47cee940c7450291a5b/components/script/parse/xml.rs#L97)):*
Does this men that we have to implement  Parser trait for ServoXMLParser with parse_chunk and finish methods and provide implementation of new method in ServoXMLParser and call it in parse_xml ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8746)*

**Comment by jdm** [comment]
Yes, that is correct.

**Comment by jdm** [comment]
Note: I have submitted a pull request to this branch that contains changes that will be very useful for making use of the new XML parser.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 5 of 5 files at r8, 4 of 4 files at r10.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8746#-:-K4c1PrH_eqZ0XPb1I9O:1458266033)*

**Comment by Jigar24** [comment]
@jdm We have incorporated the changes. Please review it.
Thanks

**Comment by jdm** [comment]
Looking good! However, we'll need to be sure to change http://mxr.mozilla.org/servo/source/components/script/dom/servohtmlparser.rs#130 to deal with the Xml mimetype as well (it can be an empty {} like the Html branch), and then try running it against an actual XML file like http://www.xmlfiles.com/examples/note.xml .

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r12, 1 of 1 files at r14, 1 of 1 files at r15, 2 of 2 files at r16, 2 of 2 files at r17.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/parse/xml.rs, line 68 \[r16\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4fEahLHGT7QZ2r2trq:-K4fEahLHGT7QZ2r2trr:109365425) ([raw file](https://github.com/servo/servo/blob/4343a6a43c3add8cbb7372384cfc1e331a175bbe/components/script/parse/xml.rs#L68)):*
nit: this should only be indented four spaces beyond the previous line.

---

*[components/script/script_task.rs, line 1682 \[r12\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4fBa2ntoqbIILUlO_5:-K4fBa2ntoqbIILUlO_6:-1215800063) ([raw file](https://github.com/servo/servo/blob/cf660f7c4272d7f3e60e35d3d91b83d284e90086/components/script/script_task.rs#L1682)):*
nit: please indent this and the subsequent line by four spaces

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8746#-:-K4fF21vsOCB-2afHeXu:-2099099382)*

**Comment by Jigar24** [comment]
@jdm : We have incorporated changes. However, we are not sure how to run it against actual xml file and check. Please review the changes.
Thanks

**Comment by jdm** [comment]
@Jigar24 It should be possible to do `./mach run http://www.xmlfiles.com/examples/note.xml` as a sanity check.

**Comment by jdm** [comment]
@bors-servo: try

---

Reviewed 3 of 3 files at r19.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/servohtmlparser.rs, line 294 \[r19\]](https://reviewable.io:443/reviews/servo/servo/8746#-K4faTv5zKXxSl9l0nG8:-K4faTv6krFZyctdOLir:307258009) ([raw file](https://github.com/servo/servo/blob/32cfc54fc1bcf3d6000f69e6772e8b49babd29b9/components/script/dom/servohtmlparser.rs#L294)):*
"text/xml", not "text/xtml" :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8746#-:-K4faaePlFm7I4pV38u5:-1265628160)*

**Comment by jdm** [comment]
The following tests are crashing while hitting the explicit `panic!()` calls that I added to methods in ServoXMLParser:
/dom/nodes/Document-contentType/contentType/contenttype_mimeheader_01.html
/dom/nodes/Element-tagName.html
/domparsing/DOMParser-parseFromString-xml.html
/html/semantics/tabular-data/the-table-element/tBodies.html

An example of the backtrace from the first test:
```
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'explicit panic', /home/servo/buildbot/slave/linux-rel/build/components/script/dom/servoxmlparser.rs:131
  │ stack backtrace:
  │    1:     0x7f26802a9d40 - sys::backtrace::tracing::imp::write::ha5f3f0d9df3eccc0xXt
  │    2:     0x7f26802acc25 - panicking::log_panic::_<closure>::closure.40991
  │    3:     0x7f26802ac6a0 - panicking::log_panic::hb6d5879621a98ec062x
  │    4:     0x7f26802959a3 - sys_common::unwind::begin_unwind_inner::h56feb86a7746f2474Ps
  │    5:     0x7f267eeef0cf - sys_common::unwind::begin_unwind::begin_unwind::h4176731564643064400
  │    6:     0x7f267f294ac6 - dom::servoxmlparser::_<impl>::parse_chunk::hf9c992190946957976O
  │    7:     0x7f267f1ed423 - parse::xml::parse_xml::h6344f664c1a229f6Bk0
  │    8:     0x7f267f3a54a8 - script_task::_<impl>::load::h66a40c36e4d762f0M81
  │    9:     0x7f267f2976f3 - script_task::_<impl>::page_fetch_complete::h23d7455c9b56bbd73e1
  │   10:     0x7f267f29526d - dom::servohtmlparser::_<impl>::headers_available::h8953eb8620067fcbFFO
  │   11:     0x7f267f82ef19 - _<impl>::process::h303f4076b6893f65psd
  │   12:     0x7f267f3aa5c7 - network_listener::_<impl>::handler::h13233018609430827843
  │   13:     0x7f267f34416e - script_task::_<impl>::handle_msg_from_script::h2ea846792f54ce5aGz1
  │   14:     0x7f267f38a10d - script_task::_<impl>::handle_msgs::_<closure>::closure.157883
  │   15:     0x7f267f36e593 - script_task::_<impl>::handle_msgs::h56c5c25c153d90baDl1
  │   16:     0x7f267f334387 - sys_common::unwind::try::try_fn::try_fn::h5503114760103935314
  │   17:     0x7f26802a91e8 - __rust_try
  │   18:     0x7f26802a55bb - sys_common::unwind::try::inner_try::hb614b0fa85d9fb24CMs
  │   19:     0x7f267f335dba - boxed::_<impl>::call_box::call_box::h9708194320540369532
  │   20:     0x7f26802ab583 - sys::thread::_<impl>::new::thread_start::h73d591f2e83d6559I5w
  │   21:     0x7f267c24a181 - start_thread
  │   22:     0x7f267ca6447c - __clone
  │   23:                0x0 - <unknown>
  └ Pipeline failed in hard-fail mode.  Crashing!
```
ie. line 131 in servoxmlparser.rs is the one being hit in this case. You'll want to fill out these methods to match the implementations in servohtmlparser.rs and ensure that running the tests (ie. `./mach test-wpt /dom/nodes/Document-contentType/contentType/contenttype_mimeheader_01.html`) doesn't crash.

**Comment by jdm** [comment]
@bors-servo: try

---

Reviewed 1 of 1 files at r20, 2 of 2 files at r21.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8746#-:-K4ijdCKA5fR67Z1uTru:-1265628160)*

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /dom/nodes/Document-contentType/contentType/contenttype_mimeheader_01.html:
  └ PASS [expected FAIL] Custom document.contentType === 'text/xml' when explicitly set to this value
```
The best kind of test failure; it means that the test is actually passing now and we should delete http://mxr.mozilla.org/servo/source/tests/wpt/metadata/dom/nodes/Document-contentType/contentType/contenttype_mimeheader_01.html.ini !

**Comment by jdm** [comment]
In fact, just to speed things along I'll do that and squash these commits.

**Comment by Jigar24** [comment]
Thanks @jdm

**Comment by jdm** [comment]
Squashed in #8829.

**Pull request closed without merging**
