### PR TITLE
Cleanup of default ciphersuite list

### PR DESCRIPTION
**Pull request by Darkspirit**
* don't offer DHE ciphersuites like Chrome (Firefox is in [progress](https://www.fxsitecompat.com/en-CA/docs/2018/dhe-cipher-suites-are-no-longer-supported-in-webrtc/) of deprecating DHE as well)
* don't offer AES-CBC-SHA2 like Firefox and Chrome
* don't offer AES-GCM for plain RSA like Firefox
* don't offer ECDSA with AES-CBC like Chrome
* don't offer weak DES-CBC3-SHA
* prefer AES256 over AES128 like [Mozilla Modern](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility), Safari and Edge

(The last line of cipher suites would be removed in the future when Servo deprecates TLS 1.0/1.1 and switches to Rustls.)

You can compare Firefox and Chrome with https://www.ssllabs.com/ssltest/viewMyClient.html.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22243)

### CODE REVIEW

**Comment by avadacatavra** [comment]
Sorry for the delay--for now, let's leave in plain RSA. 5% is a bit too high IMO, particularly since we're still working on compat in other components.

**Comment by jdm** [comment]
@bors-servo retry
* #22243

**Pull request merged**
