### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

https://bugzilla.mozilla.org/show_bug.cgi?id=1500260

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21982)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo retry

 * Infra

**Comment by CYBAI** [comment]
@bors-servo retry

```
{"status": "FAIL", "group": "default", "message": "/css/CSS2/css1/c5504-mrgn-l-003.xht 4e6ec2a4e7504e5c4bb739eb4fad793251d3180f\n/css/CSS2/css1/c5504-mrgn-l-003-ref.xht d1f5b687ad16a1a2404cea028a09a015f52802b8\nTesting 4e6ec2a4e7504e5c4bb739eb4fad793251d3180f == d1f5b687ad16a1a2404cea028a09a015f52802b8", "stack": null, "subtest": null, "test": "/css/CSS2/css1/c5504-mrgn-l-003.xht", "line": 2416, "action": "test_result", "expected": "PASS"}
```

**Pull request merged**
