### PR TITLE
Rename fire_simple_event_params to fire_event in eventtarget.rs

### LINKED ISSUE #9180: Rename fire_simple_event_params to fire_event in eventtarget.rs
`fire_simple_event` implements an algorithm [defined in the HTML spec](https://html.spec.whatwg.org/multipage/webappapis.html#fire-a-simple-event). However, there is also `fire_event` which is [defined in the DOM spec](https://dom.spec.whatwg.org/#concept-event-fire), and it is currently named `fire_simple_event_params`. We should instead rename it appropriately.

Also, the WebIDL definition for `Event` needs a spec link.

Code: `components/script/dom/eventtarget.rs`, `components/script/dom/webidls/Event.webidl`
Spec: https://dom.spec.whatwg.org/#concept-event-fire

### PR DESCRIPTION
**Pull request by nerith**
Fixes #9180.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9193)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo r+
Thanks for working on this!

**Comment by KiChjang** [comment]
@bors-servo r-
Whoops, can you squash the commits?

**Comment by nox** [comment]
Interrupted to reuse more build results on #9177.

**Pull request merged**
