### PR TITLE
Fedora pkg names

### PR DESCRIPTION
**Pull request by mathstuf**
Updates for more canonical names of Fedora Python packages in the docs.

---
- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors

(Will let CI handle those two right now; working on building Servo for the first time myself at the moment.)

- [X] These changes do not require tests because they only update the `README.md` file

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21547)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thank you!

**Comment by mathstuf** [comment]
Found another typo while building locally.

**Comment by mathstuf** [comment]
And more…I'll wait for my build to finish I suppose :) .

**Comment by mathstuf** [comment]
Updated with two more gstreamer packages which are required and my build has now completed :) .

**Comment by mathstuf** [comment]
CI failure looks to be due to a full disk on Travis (for those curious).

**Comment by jdm** [comment]
@bors-servo retry
* #20734

**Comment by mathstuf** [comment]
Hmm. Not sure what I can do with changes to a README to fix the test failures…

**Comment by jdm** [comment]
@bors-servo retry
* #19221

**Pull request merged**
