### PR TITLE
Update offscreen_gl_context

### PR DESCRIPTION
**Pull request by MortimerGoro**
Adds https://github.com/emilio/rust-offscreen-rendering-context/pull/97 and https://github.com/emilio/rust-offscreen-rendering-context/pull/98 required to run some WebGL demos

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16867)

### CODE REVIEW

**Comment by nox** [comment]
Many many failures. What happened there? Cc @emilio

**Comment by MortimerGoro** [comment]
It's because some tests were exiting early when canvas.getContext("webgl") was failing when setting antialias or depth + stencil.

There are a lot of errors but they come from the same 2 files:

- context-attributes-alpha-depth-stencil-antialias.html
- copy-tex-image-and-sub-image-2d.html

I'll check if they are easy to fix

**Comment by MortimerGoro** [comment]
I checked the failing tests and they're quite easy to fix.

We'll need to wait for https://github.com/servo/webrender/pull/1255 (this fixes 99% of context-attributes-alpha-depth-stencil-antialias.html tests)

The remaining tests just fail because now enabling antialias doesn't fail to create the WebGL context as the spec says and  some tests expect a bit different colors in that case. I'll update expectations for those tests, which can't be passed until real antialias is implemented.

**Comment by MortimerGoro** [comment]
https://github.com/servo/webrender/pull/1255 landed and I updated test expectatios.

Ready for retry

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/webgl/context_creation_error.html:
  │ FAIL [expected PASS] WebGLContextEvent "webglcontextcreationerror" event
  │   → assert_false: WebGLContext creation succeeded, please update this test! expected false got true
  │ 
  │ @http://web-platform.test:8000/_mozilla/mozilla/webgl/context_creation_error.html:20:3
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ async_test@http://web-platform.test:8000/resources/testharness.js:514:13
  └ @http://web-platform.test:8000/_mozilla/mozilla/webgl/context_creation_error.html:7:1
```
Interesting...

**Comment by jdm** [comment]
Oh, I guess we need to change this test now: https://dxr.mozilla.org/servo/source/tests/wpt/mozilla/tests/mozilla/webgl/context_creation_error.html?q=path%3Acontext_creation&redirect_type=single#17-18

**Comment by MortimerGoro** [comment]
> Oh, I guess we need to change this test now: https://dxr.mozilla.org/servo/source/tests/wpt/mozilla/tests/mozilla/webgl/context_creation_error.html?q=path%3Acontext_creation&redirect_type=single#17-18

Done.

**Comment by jdm** [comment]
./mach update-manifest is required.

**Comment by MortimerGoro** [comment]
Ok. I updated expectations for that test, added some comments and ran update-manifest. 

Now that antialias doesn't throw an error, we don't have a way to force WebGL context creation errors. Other browsers use a dummy function to fail the webgl context forcefully from js tests (e.g. forceNextWebGLContextCreationToFail(bool) on Chrome). That can be tracked into a new issue, it's not important for this PR.

**Comment by jdm** [comment]
Ok, that makes sense.

**Comment by jdm** [comment]
@bors-servo: r+
Filed https://github.com/servo/servo/issues/17038.

**Comment by MortimerGoro** [comment]
```
wget https://www.openssl.org/source/openssl-1.0.1t.tar.gz
--2017-05-25 16:20:11--  https://www.openssl.org/source/openssl-1.0.1t.tar.gz
Resolving www.openssl.org (www.openssl.org)... 104.126.148.122, 2600:1405:6:180::c1e, 2600:1405:6:18b::c1e
Connecting to www.openssl.org (www.openssl.org)|104.126.148.122|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-05-25 16:20:12 ERROR 404: Not Found.

make: *** [openssl-1.0.1t/Configure] Error 8
program finished with exit code 2
elapsedTime=2.563634
```

**Comment by MortimerGoro** [comment]
OpenSSL has published some new versions new versions today: https://www.openssl.org/source/

Maybe they have deleted the one used in Android? If that's the case all PRs will fail until fixed.

**Comment by jdm** [comment]
Yes, we need to use https://www.openssl.org/source/old/1.0.1/openssl-1.0.1.tar.gz now.

**Pull request merged**
