### PR TITLE
Implement drop-shadow filter for Stylo

### PR DESCRIPTION
**Pull request by shinglyu**
This patch got an r+ on [MozReview](https://reviewboard.mozilla.org/r/90560/#issue-summary)

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix Bugzilla [#1315157](https://bugzilla.mozilla.org/show_bug.cgi?id=1315157)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because unit test not land-able if not enabled for servo. I'll land the test later when we enable it in Servo

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14218)

### CODE REVIEW

**Comment by shinglyu** [comment]
Thanks @Manishearth

**Comment by jdm** [comment]
@bors-servo: retry
* #13776

**Comment by shinglyu** [comment]
@bors-servo: retry

* https://github.com/servo/servo/issues/14267

**Comment by KiChjang** [comment]
@bors-servo retry
* #13776

**Pull request merged**
