### PR TITLE
Reduce allocator churn when parsing property declaration blocks

### LINKED ISSUE #15060: Reduce unnecessary allocations in parse_property_declaration_list
`parse_property_declaration_list` has some allocator churn

[The function](﻿https://github.com/servo/servo/blob/a4551d0ceea8f2aceb68775452ea3010760f2825/components/style/properties/declaration_block.rs#L556-L578) works by iterating through the parsed declarations.

However, each iteration produces a `Vec<(PropertyDecl, Importance)>`, which is read from an immediately destroyed. These are of length 1 when dealing with longhands

We should be reducing this. There are many ways of doing so:

 - Make the `PropertyDeclarationParser` parser append to an internal vector, and iteration only yields a `Result</* importance count */ u32,  ErrorType>`
 - Use a 1-element SmallVec for [`<PropertyDeclarationParser as DeclarationParser>::Declaration`](https://github.com/servo/servo/blob/a4551d0ceea8f2aceb68775452ea3010760f2825/components/style/properties/declaration_block.rs#L531). Or some other SmallVec.
 - Restructure the iterator so that it can yield one property declaration at a time. Sounds hard and unnecessary

Any opinions on what we should do here? I like the first option.

cc @SimonSapin

### PR DESCRIPTION
**Pull request by Manishearth**
fixes #15060

cc @emilio

r? @SimonSapin

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15089)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good. These intermediate vecs had been bothering me ever since I initially wrote this code, thanks for taking care of them!

@bors-servo r+

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15089#-:-KalZzmOsG7CUkQ5YhOh:b-kkrfrm)*

**Comment by SimonSapin** [comment]
```
./components/style/properties/properties.mako.rs:1042: Line is longer than 120 characters
```

Feel free to r=me again with that fixed :)

**Comment by jdm** [comment]
```
---- stylesheets::test_parse_stylesheet stdout ----
	thread 'stylesheets::test_parse_stylesheet' panicked at 'assertion failed: `(left == right)` (left: `"Stylesheet {\n    rules: RwLock { data: CssRules([Namespace(RwLock { data: NamespaceRule { prefix: None, url: Atom(\'http://www.w3.org/1999/xhtml\' type=static) } }), Style(RwLock { data: StyleRule { selectors: SelectorList([Selector(input[type = \"hidden\" i], specificity = 0x401)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(display: none, Important), (--a: inherit, Important)], important_count: 2 } } } }), Style(RwLock { data: StyleRule { selectors: SelectorList([Selector(html, specificity = 0x1), Selector(body, specificity = 0x1)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(display: block, Normal)], important_count: 0 } } } }), Style(RwLock { data: StyleRule { selectors: SelectorList([Selector(#d1 > .ok, specificity = 0x100400)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(background-color: blue, Normal), (background-position-x: 0%, Normal), (background-position-y: 0%, Normal), (background-repeat: repeat, Normal), (background-attachment: scroll, Normal), (background-image: none, Normal), (background-size: auto auto, Normal), (background-origin: padding-box, Normal), (background-clip: border-box, Normal)], important_count: 0 } } } }), Keyframes(RwLock { data: KeyframesRule { name: Atom(\'foo\' type=inline), keyframes: [RwLock { data: Keyframe { selector: KeyframeSelector([KeyframePercentage(0)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(width: 0%, Normal)], important_count: 0 } } } }, RwLock { data: Keyframe { selector: KeyframeSelector([KeyframePercentage(1)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(width: 100%, Normal), (width: 50%, Normal), (animation-play-state: running, Normal)], important_count: 0 } } } }] } })]) },\n    media: RwLock { data: MediaList { media_queries: [] } },\n    origin: UserAgent,\n    base_url: ServoUrl(\n        \"about::test\"\n    ),\n    namespaces: RwLock { data: Namespaces { default: Some(Atom(\'http://www.w3.org/1999/xhtml\' type=static)), prefixes: {} } },\n    dirty_on_viewport_size_change: AtomicBool(\n        false\n    ),\n    disabled: AtomicBool(\n        false\n    )\n}"`, right: `"Stylesheet {\n    rules: RwLock { data: CssRules([Namespace(RwLock { data: NamespaceRule { prefix: None, url: Atom(\'http://www.w3.org/1999/xhtml\' type=static) } }), Style(RwLock { data: StyleRule { selectors: SelectorList([Selector(input[type = \"hidden\" i], specificity = 0x401)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(display: none, Important), (--a: inherit, Important)], important_count: 2 } } } }), Style(RwLock { data: StyleRule { selectors: SelectorList([Selector(html, specificity = 0x1), Selector(body, specificity = 0x1)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(display: block, Normal)], important_count: 0 } } } }), Style(RwLock { data: StyleRule { selectors: SelectorList([Selector(#d1 > .ok, specificity = 0x100400)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(background-color: blue, Normal), (background-position-x: 0%, Normal), (background-position-y: 0%, Normal), (background-repeat: repeat, Normal), (background-attachment: scroll, Normal), (background-image: none, Normal), (background-size: auto auto, Normal), (background-origin: padding-box, Normal), (background-clip: border-box, Normal)], important_count: 0 } } } }), Keyframes(RwLock { data: KeyframesRule { name: Atom(\'foo\' type=inline), keyframes: [RwLock { data: Keyframe { selector: KeyframeSelector([KeyframePercentage(0)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(width: 0%, Normal)], important_count: 0 } } } }, RwLock { data: Keyframe { selector: KeyframeSelector([KeyframePercentage(1)]), block: RwLock { data: PropertyDeclarationBlock { declarations: [(width: 100%, Normal), (animation-play-state: running, Normal)], important_count: 0 } } } }] } })]) },\n    media: RwLock { data: MediaList { media_queries: [] } },\n    origin: UserAgent,\n    base_url: ServoUrl(\n        \"about::test\"\n    ),\n    namespaces: RwLock { data: Namespaces { default: Some(Atom(\'http://www.w3.org/1999/xhtml\' type=static)), prefixes: {} } },\n    dirty_on_viewport_size_change: AtomicBool(\n        false\n    ),\n    disabled: AtomicBool(\n        false\n    )\n}"`)', /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/style/stylesheets.rs:275
stack backtrace:
   1:        0x11083bcec - std::sys::imp::backtrace::tracing::imp::write::h36dcd6719b30e145
   2:        0x11083f7ce - std::panicking::default_hook::{{closure}}::hce0d7336eef94718
   3:        0x11083f373 - std::panicking::default_hook::hd7b4c7a7e16abb43
   4:        0x11083fc87 - std::panicking::rust_panic_with_hook::h33761bada49f3713
   5:        0x11083fae4 - std::panicking::begin_panic::h37a3cca06423c62e
   6:        0x11083fa52 - std::panicking::begin_panic_fmt::h4c0c43306d52c68f
   7:        0x1101f7ee9 - style_tests::stylesheets::test_parse_stylesheet::h412846936ae3d6ef
   8:        0x1107960ee - <F as test::FnBox<T>>::call_box::hd3e66f92cdaae6cf
   9:        0x110840b6a - __rust_maybe_catch_panic
  10:        0x11078a558 - std::panicking::try::do_call::he4607ec420b57245
  11:        0x110840b6a - __rust_maybe_catch_panic
  12:        0x11079127e - <F as alloc::boxed::FnBox<A>>::call_box::h6050ba529cee3602
  13:        0x11083eea4 - std::sys::imp::thread::Thread::new::thread_start::he1b44499d44cc4a4
  14:     0x7fff8afbb059 - _pthread_body
  15:     0x7fff8afbafd6 - _pthread_start


failures:
    stylesheets::test_parse_stylesheet
```

**Comment by Manishearth** [comment]
Yeah, need to truncate when parsing doesn't complete.

@bors-servo r=SimonSapin

**Comment by samlh** [comment]
Ran 10064 tests finished in 739.0 seconds.
  • 10053 ran as expected. 146 tests skipped.
  • 11 tests failed unexpectedly

<details>

```
Tests with unexpected results:
  ▶ FAIL [expected PASS] /css-backgrounds-3_dev/html4/border-bottom-left-radius-014.htm
  └   → /css-backgrounds-3_dev/html4/border-bottom-left-radius-014.htm fd423fa2cdf3feaf818ce419e20fbe1aeefd0117
/css-backgrounds-3_dev/html4/reference/border-radius-001-ref.htm ac0b014b71f2484415720d1f341b24e10d84a4a1
Testing fd423fa2cdf3feaf818ce419e20fbe1aeefd0117 == ac0b014b71f2484415720d1f341b24e10d84a4a1

  ▶ FAIL [expected PASS] /css-backgrounds-3_dev/html4/border-bottom-right-radius-014.htm
  └   → /css-backgrounds-3_dev/html4/border-bottom-right-radius-014.htm 7e1808bb2359417ad6aa788f9d0fdf6c79695d83
/css-backgrounds-3_dev/html4/reference/border-radius-001-ref.htm ac0b014b71f2484415720d1f341b24e10d84a4a1
Testing 7e1808bb2359417ad6aa788f9d0fdf6c79695d83 == ac0b014b71f2484415720d1f341b24e10d84a4a1

  ▶ FAIL [expected PASS] /css-backgrounds-3_dev/html4/border-top-left-radius-014.htm
  └   → /css-backgrounds-3_dev/html4/border-top-left-radius-014.htm 7d0d2aaebaeace655d3349809041968395671224
/css-backgrounds-3_dev/html4/reference/border-radius-001-ref.htm ac0b014b71f2484415720d1f341b24e10d84a4a1
Testing 7d0d2aaebaeace655d3349809041968395671224 == ac0b014b71f2484415720d1f341b24e10d84a4a1

  ▶ FAIL [expected PASS] /css-backgrounds-3_dev/html4/border-top-right-radius-014.htm
  └   → /css-backgrounds-3_dev/html4/border-top-right-radius-014.htm 485aed3e039dc647e74e372d32274a36f932a23d
/css-backgrounds-3_dev/html4/reference/border-radius-001-ref.htm ac0b014b71f2484415720d1f341b24e10d84a4a1
Testing 485aed3e039dc647e74e372d32274a36f932a23d == ac0b014b71f2484415720d1f341b24e10d84a4a1

  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_display.htm
  └   → /css-flexbox-1_dev/html/flexbox_display.htm 2f8987e5895d81164857ad55a3ec310d2b2c286e
/css-flexbox-1_dev/html/reference/flexbox_display-ref.htm 342f933555f80043d1304c062649be139962f604
Testing 2f8987e5895d81164857ad55a3ec310d2b2c286e == 342f933555f80043d1304c062649be139962f604

  ▶ FAIL [expected PASS] /css-style-attr-1_dev/html4/style-attr-braces-001.htm
  └   → /css-style-attr-1_dev/html4/style-attr-braces-001.htm 0bf2654019aa3b1e85932408ad5af5dd396123c7
/css-style-attr-1_dev/html4/reference/ref-green-on-green.htm dfe12a4b0d5e8e5c4efca55f7bccad016041a015
Testing 0bf2654019aa3b1e85932408ad5af5dd396123c7 == dfe12a4b0d5e8e5c4efca55f7bccad016041a015

  ▶ FAIL [expected PASS] /css21_dev/html4/c71-fwd-parsing-003.htm
  └   → /css21_dev/html4/c71-fwd-parsing-003.htm 3901acbf77b76badf8c72ca67577f57da1b83f8a
/css21_dev/html4/reference/c71-fwd-parsing-003-ref.htm 0f68145d5826ab9b60d7aa5eab7320c8df7611d5
Testing 3901acbf77b76badf8c72ca67577f57da1b83f8a == 0f68145d5826ab9b60d7aa5eab7320c8df7611d5

  ▶ FAIL [expected PASS] /css21_dev/html4/escapes-015.htm
  └   → /css21_dev/html4/escapes-015.htm 3df614aa6418fb9431be3104e95d4b2181f39b38
/css21_dev/html4/reference/ref-if-there-is-no-red.htm b86cf59b589a81159aa623ad486eaa39148099e9
Testing 3df614aa6418fb9431be3104e95d4b2181f39b38 == b86cf59b589a81159aa623ad486eaa39148099e9

  ▶ FAIL [expected PASS] /css21_dev/html4/ignored-rules-004.htm
  └   → /css21_dev/html4/ignored-rules-004.htm 43b503f42edab5005fbb2fa9adb54a5df16cd859
/css21_dev/html4/reference/filler-text-below-green.htm c78c6372a389dca51a62a01c251cbb942d1125e0
Testing 43b503f42edab5005fbb2fa9adb54a5df16cd859 == c78c6372a389dca51a62a01c251cbb942d1125e0

  ▶ FAIL [expected PASS] /css21_dev/html4/matching-brackets-002.htm
  └   → /css21_dev/html4/matching-brackets-002.htm c6224a06c5f08d4958b723c38e72e4b99fba0298
/css21_dev/html4/reference/matching-brackets-002-ref.htm fd6a3dc08c7e96494f5cb632da16db12822b29de
Testing c6224a06c5f08d4958b723c38e72e4b99fba0298 == fd6a3dc08c7e96494f5cb632da16db12822b29de

  ▶ FAIL [expected PASS] /css21_dev/html4/position-006.htm
  └   → /css21_dev/html4/position-006.htm ee1921359c5b7d9a05f898086835dd9665dd4eba
/css21_dev/html4/reference/position-006-ref.htm 06db67944363b446641bad7ab013e758549e6ba1
Testing ee1921359c5b7d9a05f898086835dd9665dd4eba == 06db67944363b446641bad7ab013e758549e6ba1
```

</details>

**Comment by Manishearth** [comment]
Yeah, I'm investigating

**Comment by Manishearth** [comment]
We basically needed to tweak this to "roll back" before erroring out.

**Comment by Manishearth** [comment]
@bors-servo r=SimonSapin

tidyyy

**Pull request merged**
