### PR TITLE
 DOMContentLoaded event should be trusted

### LINKED ISSUE #9332: DOMContentLoaded event should be trusted
Blocks #2968.

* Spec: <https://html.spec.whatwg.org/multipage/#the-end>.
* Code: `components/script/dom/document.rs`.
* Test: `html/syntax/parsing/the-end.html`.

### PR DESCRIPTION
**Pull request by MonsieurLanza**
Hopefully resolves #9332.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9334)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@bors-servo r+

Thank you!

**Comment by KiChjang** [comment]
```
Ran 3837 tests finished in 234.0 seconds.
  • 3835 ran as expected. 690 tests skipped.
  • 2 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /dom/events/Event-dispatch-redispatch.html:
  └ PASS [expected FAIL] EventTarget#dispatchEvent(): redispatching a native event

  ▶ Unexpected subtest result in /html/infrastructure/terminology/plugins/text-plain.html:
  └ PASS [expected FAIL] A user agent must not consider the type text/plain as having a registered plugin.
```
The first one is a PASS that is fixed by this PR, the second one is #9286.

**Comment by KiChjang** [comment]
Perhaps I wasn't clear, but the test expectations for `/dom/events/Event-dispatch-redispatch.html` needs to be updated.

**Comment by MonsieurLanza** [comment]
Done.

**Comment by KiChjang** [comment]
Could you also squash the commits?

**Comment by MonsieurLanza** [comment]
Done also. Seems I have to get some habits...

**Comment by KiChjang** [comment]
@bors-servo r+

Thanks for working on this!

**Comment by KiChjang** [comment]
@bors-servo retry
* #9012

**Pull request merged**
