### PR TITLE
WR multi-document update

### PR DESCRIPTION
**Pull request by kvark**
The PR updates WR version to support multiple documents (https://github.com/servo/webrender/pull/1509) but doesn't take advantage of this new feature yet.
It also makes Servo to use `DevicePixel` from WR instead of rolling out another one.

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because _____ no extra logic

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17892)

### CODE REVIEW

**Comment by glennw** [comment]
Nice!

@bors-servo r+

**Comment by jdm** [comment]
`./mach build-cef` needs to be fixed.

**Comment by kvark** [comment]
Thanks @jdm !
@bors-servo r=glennw

**Comment by jdm** [comment]
@bors-servo: retry
* #17900

**Comment by mrobinson** [comment]
@bors-servo: retry
* #17900

**Comment by mrobinson** [comment]
@bors-servo retry
* #17900

**Comment by jdm** [comment]
This feels like WR has broken some webgl feature.

**Comment by kvark** [comment]
@jdm it is quite possible, since I was re-arranging WebGL flushes.
I'll do another pass to see if the logic has changed.
cc @MortimerGoro - want to check out https://github.com/servo/webrender/pull/1509 ?

**Comment by MortimerGoro** [comment]
@kvark I think that the problem is that `current_bound_webgl_context_id` gets dirty after a `flush_webgl()`. Try setting current_bound_webgl_context_id to None.

**Comment by kvark** [comment]
@MortimerGoro yep, I saw that. Should be fixed by #1530

**Comment by kvark** [comment]
No code changes to this PR, just getting past the WebGL PR in WR that is supposed to fix the issues here.
@bors-servo r=glennw

**Pull request merged**
