### PR TITLE
Add unit tests for cookies handling

### LINKED ISSUE #9965: Run the tests from the cookie compatibility testsuite
http://inikulin.github.io/cookie-compat/ is a great resource. We can use this to improve our confidence in our cookie code.

### PR DESCRIPTION
**Pull request by fduraffourg**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #9965

Either:
- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Add unit tests for the `net` component about cookies. The tests are generated
with a new `mach update-net-cookies` command from this repo: https://github.com/abarth/http-state.

This PR also includes two trivial bug fixes about cookie handling.

From all the tests included, the following ones are currently failing:
- cookie_http_state::test_0003
- cookie_http_state::test_0006
- cookie_http_state::test_attribute0004
- cookie_http_state::test_attribute0005
- cookie_http_state::test_attribute0007
- cookie_http_state::test_attribute0008
- cookie_http_state::test_domain0017
- cookie_http_state::test_mozilla0001
- cookie_http_state::test_mozilla0002
- cookie_http_state::test_mozilla0003
- cookie_http_state::test_mozilla0005
- cookie_http_state::test_mozilla0007
- cookie_http_state::test_mozilla0009
- cookie_http_state::test_mozilla0010
- cookie_http_state::test_mozilla0013

`test_000[36]` and `test_mozilla*` are failing because there is currently no
method to clean a `net::cookie_storage` from expired cookies.

`test_attribute000[4578]` are failing because hyper does not parse the `Secure`
attribute correctly. I will open an issue on the upstream project.

`test_domain0017` fails because the TLD .org is not on the PUB_DOMAINS list.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11196)

### CODE REVIEW

**Comment by nox** [comment]
r? @jdm 

Not sure what you wanted Josh, the issue is quite vague.

**Comment by fduraffourg** [comment]
`./mach test-tidy` was not OK. Sorry about that. I reformated the code.

**Comment by jdm** [comment]
This is really great! To deal with the tests that currently fail, let's add a text file that lists the expected failures, and when we're generating the appropriate test we can add `#[should_panic]` to the test. This will allow the unit test suite to pass, and when we change the cookie implementation to fix the failure then the test should report an error until the list of expected failures if updated.
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, fduraffourg wrote…</i></summary>
> `./mach test-tidy` was not OK. Sorry about that. I reformated the code.</details>


---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[python/servo/testing_commands.py, line 667 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11196#-KHvoKybHkfrfUtKDVus:-KHvoKybHkfrfUtKDVut:1157058927) ([raw file](https://github.com/servo/servo/blob/5dd5af672c0d18837fea1cae363af3d6d6e3c53d/python/servo/testing_commands.py#L667)):*
> ```Python
>         run_file = path.abspath(path.join(
>                 PROJECT_TOPLEVEL_PATH,
>                 "tests/unit/net/cookie_http_state_utils.py"
> ```

`"tests", "unit", "net", "cookie_http-state_utils.py"`

---

*[tests/unit/net/cookie_http_state_utils.py, line 19 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11196#-KHvl6qFbQ-xVL5B0wbE:-KHvl6qFbQ-xVL5B0wbF:-1457590604) ([raw file](https://github.com/servo/servo/blob/5dd5af672c0d18837fea1cae363af3d6d6e3c53d/tests/unit/net/cookie_http_state_utils.py#L19)):*
> ```Python
>             {set_cookies},
>             "{location}");
>     assert_eq!(result, "{expect}".to_string());
> ```

This could be `assert_eq!(&result, "{expect}")` instead.

---

*[tests/unit/net/cookie_http_state_utils.py, line 69 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11196#-KHvnbzAGpQilPRjaBsS:-KHvnbzBO2qw4qOEhug5:52236894) ([raw file](https://github.com/servo/servo/blob/5dd5af672c0d18837fea1cae363af3d6d6e3c53d/tests/unit/net/cookie_http_state_utils.py#L69)):*
> ```Python
>             line = line.decode("utf-8").rstrip()
>             if line.startswith("Set-Cookie: "):
>                 set_cookies.append(line[12:])
> ```

Let's do
```py
prefix = "Set-Cookie: "
if line.startswith(prefix):
    set_cookies.append(line[len(prefix):])
```
for all of these.

---

*[tests/unit/net/cookie_http_state_utils.py, line 132 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11196#-KHvmk3okoYSo0S7ZA0d:-KHvmk3peswBUrBbreK3:-1843870335) ([raw file](https://github.com/servo/servo/blob/5dd5af672c0d18837fea1cae363af3d6d6e3c53d/tests/unit/net/cookie_http_state_utils.py#L132)):*
> ```Python
> 
>     # Append all tests to unit test file
>     tests_dir = os.path.join(repo_dir, "tests/data/parser")
> ```

`os.path.join(repo_dir, "tests", "data", "parser")`

---

*[tests/unit/net/cookie_http_state_utils.py, line 140 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11196#-KHvmQD9QKCqL1D2uli2:-KHvmQDAYwZUE9DnaKrB:910785454) ([raw file](https://github.com/servo/servo/blob/5dd5af672c0d18837fea1cae363af3d6d6e3c53d/tests/unit/net/cookie_http_state_utils.py#L140)):*
> ```Python
> 
> if __name__ == "__main__":
>     update_test_file("/tmp")
> ```

Perhaps we can use `tempfile.gettempdir()` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11196#-:-KHvqC1nwZVbWdmWuRRa:-510971568)*

**Comment by jdm** [comment]
I filed #11216 about updating the list of TLDs.

**Comment by fduraffourg** [comment]
Thanks for the review, I'll make the changes.

I also filed https://github.com/alexcrichton/cookie-rs/issues/46 and https://github.com/alexcrichton/cookie-rs/pull/47 regarding the parsing fo the `Secure` attribute.

**Comment by jdm** [comment]
@bors-servo: r+
Fantastic work! Thank you!

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.</details>


---

Reviewed 4 of 4 files at r6.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11196#-:-KHz6iHPQ6BFtx_piJUb:1701139459)*

**Comment by jdm** [comment]
@bors-servo: retry
* #11234

**Comment by jdm** [comment]
@bors-servo: retry
* #11099

**Pull request merged**
