### PR TITLE
Rewrite and remove most unit tests for the legacy fetch stack.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14315)

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
r=me

Regarding https://github.com/servo/servo/pull/14315/commits/9a4322b4927f5fcf9165c24a1bd0f54cfd9455b4 , could you elaborate about the security model? Is there a bug we should file here?

**Comment by jdm** [comment]
@Ms2ger I think I'd like either the test in 9a4322b rewritten to use host replacement or replaced by a WPT test.

**Comment by Ms2ger** [comment]
I tried to write a wpt test at https://github.com/Ms2ger/servo/commit/addfba6d07c1d41ccc1c16b1a7ad1f6af0d9492d , but failed... There's a CORS check rejecting my last fetch.

**Comment by Ms2ger** [comment]
https://github.com/servo/servo/pull/14345

**Pull request merged**
