### PR TITLE
XMLHttpRequest.responseXML returns null when a network error occurs

### LINKED ISSUE #24285: XMLHttpRequest.responseXML should return null when a network error occurs
Spec: https://xhr.spec.whatwg.org/#document-response step 1
Code: `components/script/dom/xmlhttprequest.rs`
Test:
* `./mach test-wpt tests/wpt/web-platform-tests/xhr/xmlhttprequest-network-error.htm`
* `./mach test-wpt tests/wpt/web-platform-tests/xhr/xmlhttprequest-network-error-sync.htm`

We fail the `assert_equals(client.responseXML, null, "responseXML")` check, because we don't check if `self.response_status` is an Err value in the `document_response` method before creating a document response to return.

### PR DESCRIPTION
**Pull request by RoyDePoy**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24285 (GitHub issue number if applicable)

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because tests ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24342)

### CODE REVIEW

**Comment by jdm** [comment]
Look at all those passing tests! Please update the ini files for them to remove the expected failures that now pass.

**Comment by petosorus** [comment]
Those fail expectations are pretty neat (I'm also trying out the tooling :) )

**Comment by petosorus** [comment]
From what I read, the modification I made has made Redirection tests pass.
I'm not really sure if it should, but I don't know enough. Reading the spec, the check is on the response body, not the response status.
Can we safely assume an error response status implies a null response body?

**Comment by jdm** [comment]
Yes, the specification states that error responses have a null body.

**Comment by petosorus** [comment]
Nice. So, I'll be removing the relevant redirect tests.
If I look at this log https://build.servo.org/builders/linux-rel-wpt/builds/13631/steps/shell__4/logs/intermittents.log, there are a lot of apparently css tests that do not fail anymore, or do fail again. I'm not sure they are related to me. What do you think of these?

**Comment by jdm** [comment]
intermittents.log is a list of tests that had unexpected results but are known to do so intermittently (based on issues in our issue tracker that have the I-intermittent label applied). You should ignore them.

**Comment by jdm** [comment]
Looks like we missed one:
```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "XMLHttpRequest: abort() after send()", 
    "test": "/xhr/abort-after-send.any.html", 
    "line": 282809, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

**Comment by jdm** [comment]
@bors-servo retry
* #13480

**Pull request merged**
