### PR TITLE
Add clobber mechanism

### PR DESCRIPTION
**Pull request by UK992**
Solution for https://github.com/servo/servo/issues/16602 and https://github.com/servo/servo/issues/16632
Only work when `AUTOCLOBBER` environment variable is defined.

CC @SimonSapin @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16722)

### CODE REVIEW

**Comment by Manishearth** [comment]
Mostly looks fine by me, r? @jdm since you proposed it

**Comment by SimonSapin** [comment]
Same error as in https://github.com/servo/servo/pull/16756:
```
error: failed to run custom build command for `blurdroid v0.1.2`
process didn't exit successfully: `/home/servo/buildbot/slave/android/build/target/debug/build/blurdroid-e2727e499c92c405/build-script-build` (exit code: 1)
--- stdout
make: Entering directory `/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/blurdroid-0.1.2/src/jni'
make: Leaving directory `/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/blurdroid-0.1.2/src/jni'
Error while executing javac

--- stderr
src/java/hu/uszeged/bluetooth/ScanRecord.java:25: error: package android.os does not exist
import android.os.ParcelUuid;
                 ^
src/java/hu/uszeged/bluetooth/ScanRecord.java:26: error: package android.util does not exist
import android.util.SparseArray;
                   ^
src/java/hu/uszeged/bluetooth/ScanRecord.java:65: error: cannot find symbol
    public static final ParcelUuid BASE_UUID =
                        ^
  symbol:   class ParcelUuid
  location: class ScanRecord

…
```

**Comment by aneeshusa** [comment]
FYI @SimonSapin that android error is being tracked at https://github.com/servo/saltfs/issues/661

**Pull request merged**
