### PR TITLE
Insert adjacent

### LINKED ISSUE #11622: Implement Element.insertAdjacentHTML
See [the spec](https://w3c.github.io/DOM-Parsing/#dom-element-insertadjacenthtml).

In a first commit, extract the matching of `where_` from `Element::insert_adjacent` and introduce a new enum `AdjacentPosition`. This enum should then be passed instead of `where_` to `Element::insert_adjacent`. This requires updating its two callers `InsertAdjacentElement` and `InsertAdjacentText`.

```rust
enum AdjacentPosition {
    BeforeBegin,
    AfterEnd,
    AfterBegin,
    BeforeEnd
}

impl AdjacentPosition {
    pub fn parse(position: &str) -> Fallible<AdjacentPosition> { ... }
}
```

In a second commit, use `AdjacentPosition` and `Element::insert_adjacent` to implement `Element::InsertAdjacentHTML` correctly.

```webidl
partial interface Element {
    ...
    [Throws]
    void insertAdjacentHTML(DOMString position, DOMString text);
}
```

```rust
impl ElementMethods for Element {
    ...
    fn InsertAdjacentHTML(DOMString position, DOMString text) -> ErrorResult { ... }
}
```

Files:
* components/script/dom/element.rs
* components/script/dom/webidls/Element.webidl
* tests/wpt/metadata/domparsing/insert-adjacent.html.ini
* tests/wpt/metadata/domparsing/insert_adjacent_html.html.ini
* tests/wpt/web-platform-tests/domparsing/insert-adjacent.html
* tests/wpt/web-platform-tests/domparsing/insert_adjacent_html.html

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #11622.

r? @nox

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11668)

### CODE REVIEW

**Comment by nox** [comment]
This just requires small changes and a few tests.

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> warning **Warning** warning
> 
> * These commits modify script code, but no tests are modified. Please consider adding a test!
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/11668#-KJgp8D7GuKohd929nmS:-KJgp8D81yc0HmrXGZEE:1788588379) (no related file):*
Second commit needs tests, I think. We will see when we `try`.

---

*[components/script/dom/element.rs, line 132 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJgpEE2P3rL3_IdaRws:-KJgpEE2P3rL3_IdaRwt:-659249760) ([raw file](https://github.com/servo/servo/blob/65237e8efb922e7ac82fbba9a2aae4f014cde805/components/script/dom/element.rs#L132)):*
> ```Rust
> impl AdjacentPosition {
>     pub fn parse(position: &str) -> Fallible<AdjacentPosition> {
>         match &*position.to_ascii_lowercase() {
> ```

Use `match_ignore_ascii_case!`.

---

*[components/script/dom/element.rs, line 2034 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJgqrRijgT6Q5LJTKcu:-KJgqrRijgT6Q5LJTKcv:138568598) ([raw file](https://github.com/servo/servo/blob/26067232201b99dfedd759fd47e6ede6310dc797/components/script/dom/element.rs#L2034)):*
> ```Rust
> 
>     // https://w3c.github.io/DOM-Parsing/#dom-element-insertadjacenthtml
>     fn InsertAdjacentHTML(&self, where_: DOMString, html: DOMString)
> ```

Nit: in that method, the parameters are called `position` and `text` .

---

*[components/script/dom/element.rs, line 2036 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJgpyUl6l66fv_F6RUd:-KJgpyUl6l66fv_F6RUe:-5836808) ([raw file](https://github.com/servo/servo/blob/26067232201b99dfedd759fd47e6ede6310dc797/components/script/dom/element.rs#L2036)):*
> ```Rust
>     fn InsertAdjacentHTML(&self, where_: DOMString, html: DOMString)
>                           -> ErrorResult {
>         fn step3(context: &Element, where_: AdjacentPosition, html: DOMString)
> ```

Inline that, no need to do a `step3` function.

---

*[components/script/dom/element.rs, line 2045 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJgptRw5OyjISPOiMtQ:-KJgptRw5OyjISPOiMtR:716856509) ([raw file](https://github.com/servo/servo/blob/26067232201b99dfedd759fd47e6ede6310dc797/components/script/dom/element.rs#L2045)):*
> ```Rust
>         }
> 
>         fn step2(context: &Element, where_: AdjacentPosition, html: DOMString)
> ```

Inline that and just do like for `Range.createContextualFragment`.

---

*[components/script/dom/element.rs, line 2061 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJgq41j-xJE5-YGTzYY:-KJgq41j-xJE5-YGTzYZ:-93715744) ([raw file](https://github.com/servo/servo/blob/26067232201b99dfedd759fd47e6ede6310dc797/components/script/dom/element.rs#L2061)):*
> ```Rust
> 
>         // Step 1.
>         let where_ = try!(AdjacentPosition::parse(&*where_));
> ```

What about:

```rust
let context = match position {
    AdjacentPosition::BeforeBegin | AdjacentPosition::AfterEnd => {
        match self.upcast::<Node>().GetParentNode() {
            Some(parent) if !parent.is::<Document>() => parent,
            _ => return Err(Error::NoModificationAllowed),
        }
    },
    AdjacentPosition::AfterBegin | AdjacentPosition::BeforeEnd => {
        Root::from_ref(self.upcast::<Node>())
    },
};
```

---

*[components/script/dom/element.rs, line 2065 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJgr9KGWWQoVD7hSe-p:-KJgr9KGWWQoVD7hSe-q:1215898226) ([raw file](https://github.com/servo/servo/blob/26067232201b99dfedd759fd47e6ede6310dc797/components/script/dom/element.rs#L2065)):*
> ```Rust
>         match where_ {
>             AdjacentPosition::BeforeBegin | AdjacentPosition::AfterEnd => {
>                 match self.clone().upcast::<Node>().GetParentElement() {
> ```

`GetParentElement()` returns an element, which should be a hint that it is not the right method to use here. How could an `Element` be a `Document`? Use `GetParentNode()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11668#-:-KJgsoLyQeIGEAmQB5kk:432240808)*

**Comment by jdm** [comment]
Sorry my IRC suggestion of element.document() didn't work. I should have said `document_from_node(element)` instead, which is different than calling GetParentNode.

**Comment by GuillaumeGomez** [comment]
No worries, I found it so everything's fine! :)

**Comment by nox** [comment]
-S-awaiting-review -S-tests-failed +S-needs-code-changes +S-fails-tidy 

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :broken_heart: Test failed - [linux-dev](http://build.servo.org/builders/linux-dev/builds/1450)
</details>


---

Reviewed 3 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/script/dom/element.rs, line 2061 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJgq41j-xJE5-YGTzYY:-KJjOGwnuqvmXnv1Hyt8:-1848664689) ([raw file](https://github.com/servo/servo/blob/26067232201b99dfedd759fd47e6ede6310dc797/components/script/dom/element.rs#L2061)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> What about:
> 
> ```rust
> let context = match position {
>     AdjacentPosition::BeforeBegin | AdjacentPosition::AfterEnd => {
>         match self.upcast::<Node>().GetParentNode() {
>             Some(parent) if !parent.is::<Document>() => parent,
>             _ => return Err(Error::NoModificationAllowed),
>         }
>     },
>     AdjacentPosition::AfterBegin | AdjacentPosition::BeforeEnd => {
>         Root::from_ref(self.upcast::<Node>())
>     },
> };
> ```
</details>
Did you have lifetime issues with that way?

---

*[components/script/dom/element.rs, line 134 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJjNwI8PL5gCuhOpdxc:-KJjNwI9A_URLeAVVovh:-1647764776) ([raw file](https://github.com/servo/servo/blob/7542fed1331575709634d1b1d0babcc181b34af1/components/script/dom/element.rs#L134)):*
> ```Rust
>         match_ignore_ascii_case! { &*position,
>             "beforebegin" => Ok(AdjacentPosition::BeforeBegin),
>             "afterbegin"  => Ok(AdjacentPosition::AfterEnd),
> ```

`AfterBegin`

---

*[components/script/dom/element.rs, line 135 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJjNyYXm01vLaUOHZ6X:-KJjNyYXm01vLaUOHZ6Y:612325727) ([raw file](https://github.com/servo/servo/blob/7542fed1331575709634d1b1d0babcc181b34af1/components/script/dom/element.rs#L135)):*
> ```Rust
>             "beforebegin" => Ok(AdjacentPosition::BeforeBegin),
>             "afterbegin"  => Ok(AdjacentPosition::AfterEnd),
>             "beforeend"   => Ok(AdjacentPosition::AfterBegin),
> ```

`BeforeEnd`

---

*[components/script/dom/element.rs, line 136 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJjNzy7EcyBrW5JkNiZ:-KJjNzy7EcyBrW5JkNi_:-86532826) ([raw file](https://github.com/servo/servo/blob/7542fed1331575709634d1b1d0babcc181b34af1/components/script/dom/element.rs#L136)):*
> ```Rust
>             "afterbegin"  => Ok(AdjacentPosition::AfterEnd),
>             "beforeend"   => Ok(AdjacentPosition::AfterBegin),
>             "afterend"    => Ok(AdjacentPosition::BeforeEnd),
> ```

`AfterEnd`

---

*[components/script/dom/element.rs, line 2051 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJjOQIzw7xp8LBI2EP8:-KJjOQIzw7xp8LBI2EP9:-2066630341) ([raw file](https://github.com/servo/servo/blob/7542fed1331575709634d1b1d0babcc181b34af1/components/script/dom/element.rs#L2051)):*
> ```Rust
>             }
>             AdjacentPosition::AfterBegin | AdjacentPosition::BeforeEnd => Root::from_ref(self.upcast::<Node>()),
>         };
> ```

Do you have a lifetime issue with this?

```rust
let context = match position {
    AdjacentPosition::BeforeBegin | AdjacentPosition::AfterEnd => {
        match self.upcast::<Node>().GetParentNode() {
            Some(parent) if !parent.is::<Document>() => parent,
            _ => return Err(Error::NoModificationAllowed),
        }
    },
    AdjacentPosition::AfterBegin | AdjacentPosition::BeforeEnd => {
        Root::from_ref(self.upcast::<Node>())
    },
};
```

---

*[components/script/dom/webidls/Element.webidl, line 79 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJjOZ-5N_Qu_I1-skNT:-KJjOZ-5N_Qu_I1-skNU:-1737547299) ([raw file](https://github.com/servo/servo/blob/7542fed1331575709634d1b1d0babcc181b34af1/components/script/dom/webidls/Element.webidl#L79)):*
> ```WebIDL
>   void insertAdjacentText(DOMString where_, DOMString data);
>   [Throws]
>   void insertAdjacentHTML(DOMString psoition, DOMString html);
> ```

Nit: `position`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11668#-:-KJjOddN6frZOoqgyxMI:-1266899942)*

**Comment by nox** [comment]
-S-needs-code-changes 

<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> -S-awaiting-review -S-tests-failed +S-needs-code-changes +S-fails-tidy 
</details>


---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[components/script/dom/element.rs, line 2051 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11668#-KJjOQIzw7xp8LBI2EP8:-KJjTUoSq4_fcPy6HH3s:1787940161) ([raw file](https://github.com/servo/servo/blob/7542fed1331575709634d1b1d0babcc181b34af1/components/script/dom/element.rs#L2051)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Do you have a lifetime issue with this?
> 
> ```rust
> let context = match position {
>     AdjacentPosition::BeforeBegin | AdjacentPosition::AfterEnd => {
>         match self.upcast::<Node>().GetParentNode() {
>             Some(parent) if !parent.is::<Document>() => parent,
>             _ => return Err(Error::NoModificationAllowed),
>         }
>     },
>     AdjacentPosition::AfterBegin | AdjacentPosition::BeforeEnd => {
>         Root::from_ref(self.upcast::<Node>())
>     },
> };
> ```
</details>
Ok, that can't work because "cannot bind by-move into a pattern guard".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11668#-:-KJjTgXf_vXPjYh70mYv:1741763371)*

**Comment by nox** [comment]
-S-awaiting-review -S-fails-tidy 

@bors-servo try

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 3 of 3 files at r6, 2 of 2 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11668#-:-KJjW99vxBFaChG6Ra4n:864428565)*

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/11668#-KJjpaJry9PULHW0GEdK:-KJjvxpfaMpn_c1rffzP:296831301) (no related file):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Please just update expectations for the unexpected `PASS`, not timeouts that occur locally because you are using a debug build.
</details>
There are still wrong expectations for createContextualFragment.html and you didn't remove the failing expectations for insertAdjacentHTML, the unexpected `PASS` tests on Buildbot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11668#-:-KJjw7BoJXw_jqxOiaQq:1458266033)*

**Comment by nox** [comment]
-S-awaiting-review

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 5 of 5 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/11668#-KJjpaJry9PULHW0GEdK:-KJk8Lyqr1e9QwqsVc2A:-1893320889) (no related file):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> There are still wrong expectations for createContextualFragment.html and you didn't remove the failing expectations for insertAdjacentHTML, the unexpected `PASS` tests on Buildbot.
</details>
The expectations are now ok.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/11668#-KJk8NsS-fNvC-u7zje_:-KJk8NsS-fNvC-u7zjea:1863808003) (no related file):*
That's a lot of still failing tests. This requires further enquiry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11668#-:-KJk8R5XCzh9lAk4VTwN:721110327)*

**Comment by nox** [comment]
@bors-servo r+

<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> -S-awaiting-review
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/11668#-KJk8NsS-fNvC-u7zje_:-KJkBzvPmidH_spnY0b4:438818431) (no related file):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> That's a lot of still failing tests. This requires further enquiry.
</details>
The tests look broken, I'll study that myself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11668#-:-KJkC1koDdgY1lZPRCEp:1236647940)*

**Pull request merged**
