### PR TITLE
use DisplayListBuilder::with_capacity

### PR DESCRIPTION
**Pull request by Gankra**
DO NOT MERGE until https://github.com/servo/webrender/pull/1399 has landed in Servo.

Previously webrender was reserving 1MB of space for each display list (empirically pages weighed between 100k and 10MB when I implemented this). This was problematic for gecko because they used webrender differently. This just brings Servo back to where it was.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17406)

### CODE REVIEW

**Comment by Manishearth** [comment]
r+

**Comment by stshine** [comment]
servo/webrender#1399 landed.

**Comment by Gankro** [comment]
rebased

**Pull request merged**
