### PR TITLE
Track event state changes on Document and do the dirtying from layout

### PR DESCRIPTION
**Pull request by bholley**
This is a first step in fixing #6942.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8098)

### CODE REVIEW

**Comment by bholley** [comment]
@frewsxcv can you kick off a try push for me?

**Comment by bholley** [comment]
oh wait, need to fix some tidness. Moment.

**Comment by jdm** [comment]
```
failures:
    iframe/bg_color.html == iframe/bg_color_ref.html
    iframe/hide_after_load.html == iframe/hide_after_load_ref.html
    iframe/hide_layers1.html == iframe/hide_layers_ref.html
    iframe/simple_inline_height.html == iframe/simple_inline_height_ref.html
```

**Comment by bholley** [comment]
Another try push plz. :-)

**Comment by frewsxcv** [comment]
@bors-servo: try

That last fail was intermittent

**Comment by jdm** [comment]
I don't think there's value in re-trying try pushes that have known intermittent failures.

**Comment by pcwalton** [comment]
Looks good to me.

**Comment by pcwalton** [comment]
(at least layout. r? @jdm for script)

**Comment by Manishearth** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: 1 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8098)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 6 of 6 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8098)

**Pull request merged**
