### PR TITLE
2020: paint borders

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by jdm** [comment]
Sorry, mac9 is in a weird intermediate state.
@bors-servo retry

**Comment by CYBAI** [comment]
@bors-servo retry

- cygwin oom

**Comment by jdm** [comment]
```
/Users/worker/tasks/task_1572003607/repo/android-toolchains/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++: /Users/worker/tasks/task_1572003607/repo/android-toolchains/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++: cannot execute binary file
```
Hooray!

@bors-servo retry

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
