### PR TITLE
Update web-platform-tests to revision 5e3ea8f49fee68c327388bfd1dd1375a8ce12a0e.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6584)

### CODE REVIEW

**Comment by jdm** [comment]
```
/XMLHttpRequest/send-redirect-to-non-cors.htm
---------------------------------------------
PASS expected FAIL XMLHttpRequest: send() - Redirect to cross-origin resource, not CORS-enabled (301)
PASS expected FAIL XMLHttpRequest: send() - Redirect to cross-origin resource, not CORS-enabled (302)
PASS expected FAIL XMLHttpRequest: send() - Redirect to cross-origin resource, not CORS-enabled (303)
PASS expected FAIL XMLHttpRequest: send() - Redirect to cross-origin resource, not CORS-enabled (307)
```

**Comment by Ms2ger** [comment]
@jgraham this hangs; reverting tests/wpt/web-platform-tests/tools/ changes fixes it. You want to look into that?

**Pull request merged**
