### PR TITLE
Fix a few things regarding redirects

### PR DESCRIPTION
**Pull request by Eijebong**
See individual commits

### CODE REVIEW

**Comment by Eijebong** [comment]
```
▶ TIMEOUT [expected OK] /fetch/api/redirect/redirect-method.any.html
  │ TIMEOUT [expected PASS] Redirect 301 with POST
```

:eyes

**Comment by Eijebong** [comment]
I can repro locally, guess I failed some rebase before pushing...

**Comment by Eijebong** [comment]
@bors-servo retry

```
1 unexpected results that are NOT known-intermittents:
  ▶ FAIL [expected PASS] /css/CSS2/ui/outline-color-101.xht
  │   → /css/CSS2/ui/outline-color-101.xht 54a9df64f1476dd12020019d7cf22ac34d727bc0
  │   → /css/CSS2/reference/boxes_same_color_100px_black_50px_margin.xht bb2751bfe2e9b16331e4522f296d899b22e12085
  └   → Screenshot is solid color 0xFFFFFF for /css/CSS2/ui/outline-color-101.xht
```

#24726

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /xhr/send-redirect-to-cors.htm:
  │ FAIL [expected PASS] XMLHttpRequest: send() - Redirect to CORS-enabled resource (303 LALA with string and explicit Content-Type safelisted)
  │   → assert_equals: expected "application/x-pony" but got "NO"
  │ FAIL [expected PASS] XMLHttpRequest: send() - Redirect to CORS-enabled resource (301 POST with string and explicit Content-Type safelisted)
  │   → assert_equals: expected "application/x-pony" but got "NO"
  │ 
  │ redirect/</client.onreadystatechange<@http://web-platform.test:8000/xhr/send-redirect-to-cors.htm:41:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:2009:35
  ▶ Unexpected subtest result in /xhr/send-redirect-to-cors.htm:
  │ FAIL [expected PASS] XMLHttpRequest: send() - Redirect to CORS-enabled resource (301 POST with string and explicit Content-Type)
  │   → assert_equals: expected 0 but got 200
  │ FAIL [expected PASS] XMLHttpRequest: send() - Redirect to CORS-enabled resource (302 POST with string and explicit Content-Type)
  │   → assert_equals: expected 0 but got 200
  │ 
  │ redirect/</client.onreadystatechange<@http://web-platform.test:8000/xhr/send-redirect-to-cors.htm:45:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:2009:35
  ▶ Unexpected subtest result in /xhr/send-redirect-post-upload.htm:
  └ PASS [expected FAIL] XMLHttpRequest: The send() method: POSTing to URL that redirects (301)
  ▶ Unexpected subtest result in /xhr/send-redirect-post-upload.htm:
  └ PASS [expected FAIL] XMLHttpRequest: The send() method: POSTing to URL that redirects (302)
  ▶ Unexpected subtest result in /xhr/send-redirect-post-upload.htm:
  └ PASS [expected FAIL] XMLHttpRequest: The send() method: POSTing to URL that redirects (303)
```

**Comment by Eijebong** [comment]
So I'm very confused right now. Looking at `/xhr/send-redirect-to-cors.htm` failures.

I looked at firefox's implementation if the step 11 of redirect-fetch (https://fetch.spec.whatwg.org/#http-redirect-fetch), which is here: https://searchfox.org/mozilla-central/rev/aec63591821712236a522f7f55116f582ed7c920/dom/fetch/FetchDriver.cpp#1318

At first I thought I was going crazy because the condition is exactly the same but firefox passes those tests. But then I removed the line actually skipping those headers in the redirected request at https://searchfox.org/mozilla-central/rev/aec63591821712236a522f7f55116f582ed7c920/dom/fetch/FetchDriver.cpp#1444 and the test still passed. Apparently, firefox never goes through that `AsyncOnChannelRedirect` method for XHR requests but does for fetch ones. Now the question is: Why ?

The spec here says that for XHR requests, you should be using the fetch API even on XHR (https://xhr.spec.whatwg.org/#the-send()-method) so you should be removing those headers, right ?

Am I missing something important here ? Is the spec wrong ? Are the tests wrong ? Is my code wrong ? Is servo's handling of XHR wrong ?

**Comment by jdm** [comment]
Gecko doesn't use Fetch internally for its XHR implementation. Instead it uses [XMLHttpRequestMainThread::AsyncOnChannelRedirect](https://searchfox.org/mozilla-central/source/dom/xhr/XMLHttpRequestMainThread.cpp#3223).

**Comment by jdm** [comment]
I suspect the XHR code ends up hitting https://searchfox.org/mozilla-central/rev/3446310d6cc5c85cde16a82eccf560e9b71a3d44/netwerk/protocol/http/HttpBaseChannel.cpp#3625-3632 and https://searchfox.org/mozilla-central/source/netwerk/protocol/http/HttpBaseChannel.cpp#84 doesn't include Content-Type.

**Comment by jdm** [comment]
Welp. The test doesn't match the specification, and the right behaviour is not clear to me. I have filed https://github.com/web-platform-tests/wpt/issues/23156 upstream about resolving the mismatch between the Fetch and XHR tests somehow; I propose we merge these changes with the expected failures.

**Comment by jdm** [comment]
The commit I added to this branch causes us to pass almost all of the tests in send-redirect-to-cors.htm with https://github.com/web-platform-tests/wpt/pull/23164 and https://github.com/web-platform-tests/wpt/pull/23176 applied. It exposes two remaining failures which I'm arguing in 23176 are incorrect tests.

**Comment by Eijebong** [comment]
With your commit:

```
Running 373 tests in web-platform-tests

  ▶ TIMEOUT [expected CRASH] /xhr/send-data-sharedarraybuffer.any.worker.html
  │
  │ assertion failed: !shared (thread WebWorker for http://web-platform.test:8000/xhr/send-data-sharedarraybuffer.any.worker.js, at /home/eijebong/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/ea10bed/src/typedarray.rs:381)
  │ stack backtrace:
  │    0: servo::backtrace::print
  │              at ports/glutin/backtrace.rs:17
  │    1: servo::main::{{closure}}
  │              at ports/glutin/main2.rs:150
  │    2: std::panicking::rust_panic_with_hook
  │              at src/libstd/panicking.rs:515
  │    3: std::panicking::begin_panic
  │              at /rustc/42abbd8878d3b67238f3611b0587c704ba94f39c/src/libstd/panicking.rs:438
  │    4: <mozjs::typedarray::ArrayBufferViewU8 as mozjs::typedarray::TypedArrayElement>::length_and_data
  │              at /home/eijebong/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/ea10bed/src/typedarray.rs:292
  │    5: mozjs::typedarray::TypedArray<T,S>::data
  │              at /home/eijebong/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/ea10bed/src/typedarray.rs:156
  │    6: mozjs::typedarray::TypedArray<T,S>::as_slice
  │              at /home/eijebong/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/ea10bed/src/typedarray.rs:195
  │    7: mozjs::typedarray::TypedArray<T,S>::to_vec
  │              at /home/eijebong/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/ea10bed/src/typedarray.rs:187
  │    8: <script::dom::xmlhttprequest::XMLHttpRequest as script::dom::bindings::codegen::Bindings::XMLHttpRequestBinding::XMLHttpRequestBinding::XMLHttpRequestMethods>::Send
  │              at components/script/dom/xmlhttprequest.rs:583
  │    9: script::dom::bindings::codegen::Bindings::XMLHttpRequestBinding::XMLHttpRequestBinding::send::{{closure}}
  │              at /home/eijebong/code/servo/target/debug/build/script-e9f8ec9a137ea379/out/Bindings/XMLHttpRequestBinding.rs:1318
  │   10: core::ops::function::FnOnce::call_once
  │              at /rustc/42abbd8878d3b67238f3611b0587c704ba94f39c/src/libcore/ops/function.rs:232
  │   11: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  │              at /rustc/42abbd8878d3b67238f3611b0587c704ba94f39c/src/libstd/panic.rs:318
  │   12: std::panicking::try::do_call
  │              at /rustc/42abbd8878d3b67238f3611b0587c704ba94f39c/src/libstd/panicking.rs:331
  │   13: __rust_try
  │   14: std::panicking::try
  │              at /rustc/42abbd8878d3b67238f3611b0587c704ba94f39c/src/libstd/panicking.rs:274
  │   15: std::panic::catch_unwind
  └              at /rustc/42abbd8878d3b67238f3611b0587c704ba94f39c/src/libstd/panic.rs:394

  ▶ TIMEOUT [expected OK] /xhr/preserve-ua-header-on-redirect.htm

  ▶ TIMEOUT [expected OK] /xhr/open-url-base-inserted-after-open.htm

  ▶ TIMEOUT [expected OK] /xhr/open-after-stop.window.html

  ▶ TIMEOUT [expected OK] /xhr/send-accept.htm

  ▶ TIMEOUT [expected OK] /xhr/open-url-worker-origin.htm

  ▶ TIMEOUT [expected OK] /xhr/open-url-multi-window.htm

  ▶ TIMEOUT [expected OK] /xhr/getallresponseheaders.htm

  ▶ TIMEOUT [expected OK] /xhr/historical.html

  ▶ TIMEOUT [expected OK] /xhr/responseXML-unavailable-in-worker.html

  ▶ TIMEOUT [expected OK] /xhr/send-authentication-competing-names-passwords.htm

  ▶ TIMEOUT [expected OK] /xhr/getresponseheader-server-date.htm

  ▶ TIMEOUT [expected OK] /xhr/status-async.htm

  ▶ TIMEOUT [expected OK] /xhr/send-sync-timeout.htm

  ▶ TIMEOUT [expected OK] /xhr/send-entity-body-document.htm

  ▶ TIMEOUT [expected OK] /xhr/response-invalid-responsetype.htm

  ▶ TIMEOUT [expected OK] /xhr/open-url-worker-simple.htm

  ▶ TIMEOUT [expected OK] /xhr/open-url-redirected-worker-origin.htm

  ▶ TIMEOUT [expected OK] /xhr/open-user-password-non-same-origin.htm

  ▶ TIMEOUT [expected OK] /xhr/overridemimetype-invalid-mime-type.htm

  ▶ TIMEOUT [expected OK] /xhr/open-during-abort-processing.htm

  ▶ TIMEOUT [expected OK] /xhr/send-data-formdata.any.worker.html

  ▶ TIMEOUT [expected OK] /xhr/open-open-sync-send.htm

  ▶ TIMEOUT [expected OK] /xhr/getresponseheader-special-characters.htm

  ▶ TIMEOUT [expected OK] /xhr/open-after-abort.htm

  ▶ TIMEOUT [expected OK] /xhr/responsexml-media-type.htm

  ▶ TIMEOUT [expected OK] /xhr/send-blob-with-no-mime-type.html

  ▶ TIMEOUT [expected OK] /xhr/send-redirect-bogus-sync.htm

  ▶ TIMEOUT [expected OK] /xhr/responsexml-basic.htm

  ▶ TIMEOUT [expected OK] /xhr/response-data-deflate.htm

  ▶ TIMEOUT [expected OK] /xhr/response-data-gzip.htm

  ▶ TIMEOUT [expected OK] /xhr/responsetype.any.html

  ▶ TIMEOUT [expected OK] /xhr/overridemimetype-open-state-force-xml.htm

  ▶ TIMEOUT [expected OK] /xhr/send-network-error-sync-events.sub.htm

  ▶ TIMEOUT [expected OK] /xhr/open-url-javascript-window-2.htm

  ▶ TIMEOUT [expected OK] /xhr/send-authentication-basic-cors.htm

  ▶ TIMEOUT [expected OK] /xhr/open-sync-open-send.htm

  ▶ TIMEOUT [expected OK] /xhr/send-content-type-charset.htm

  ▶ Unexpected subtest result in /xhr/send-redirect-post-upload.htm:
  └ PASS [expected FAIL] XMLHttpRequest: The send() method: POSTing to URL that redirects (307 (string))

  ▶ Unexpected subtest result in /xhr/send-redirect-post-upload.htm:
  └ PASS [expected FAIL] XMLHttpRequest: The send() method: POSTing to URL that redirects (307 (blob))

  ▶ Unexpected subtest result in /xhr/send-redirect-to-cors.htm:
  └ PASS [expected FAIL] XMLHttpRequest: send() - Redirect to CORS-enabled resource (307 post with string)

  ▶ Unexpected subtest result in /xhr/send-redirect-to-cors.htm:
  └ PASS [expected FAIL] XMLHttpRequest: send() - Redirect to CORS-enabled resource (307 post with typed array)

  ▶ Unexpected subtest result in /xhr/send-redirect-to-cors.htm:
  └ PASS [expected FAIL] XMLHttpRequest: send() - Redirect to CORS-enabled resource (308 FOO with string and explicit Content-Type text/plain)

  ▶ Unexpected subtest result in /xhr/send-redirect-to-cors.htm:
  └ PASS [expected FAIL] XMLHttpRequest: send() - Redirect to CORS-enabled resource (308 FOO with string and explicit Content-Type multipart/form-data)

  ▶ Unexpected subtest result in /xhr/send-redirect-to-cors.htm:
  └ PASS [expected FAIL] XMLHttpRequest: send() - Redirect to CORS-enabled resource (308 FOO with string and explicit Content-Type safelisted)

  ▶ Unexpected subtest result in /xhr/send-redirect-to-cors.htm:
  └ PASS [expected FAIL] XMLHttpRequest: send() - Redirect to CORS-enabled resource (307 POST with string and explicit Content-Type safelisted)

Ran 373 tests finished in 245.0 seconds.
  • 333 ran as expected. 1 tests skipped.
  • 38 tests timed out unexpectedly
  • 2 tests had unexpected subtest results

```

**Comment by Eijebong** [comment]
```
1 unexpected results that are NOT known-intermittents:
  ▶ Unexpected subtest result in /css/css-transitions/properties-value-inherit-003.html:
  │ FAIL [expected PASS] outline-offset length-em(em) / events
  │   → assert_equals: Expected TransitionEnd events triggered on .transition expected "" but got "outline-offset:2s"
  │ 
  │ assertExpectedEventsFunc/<@http://web-platform.test:8000/css/css-transitions/support/generalParallelTest.js:207:26
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1975:25
  │ done@http://web-platform.test:8000/css/css-transitions/properties-value-inherit-003.html:134:34
  │ concludeSlice/</</<@http://web-platform.test:8000/css/css-transitions/support/runParallelAsyncHarness.js:122:59
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1975:25
  │ concludeSlice/</<@http://web-platform.test:8000/css/css-transitions/support/runParallelAsyncHarness.js:121:38
  │ concludeSlice/<@http://web-platform.test:8000/css/css-transitions/support/runParallelAsyncHarness.js:120:23
  └ concludeSlice@http://web-platform.test:8000/css/css-transitions/support/runParallelAsyncHarness.js:118:19
```

Sounds unrelated

**Comment by jdm** [comment]
@bors-servo retry
* #26435

**Pull request merged**
