### PR TITLE
Move the type_id fields to DOMClass

### PR DESCRIPTION
**Pull request by nox**
Cc @michaelwu.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7606)

### CODE REVIEW

**Comment by nox** [comment]
Oh I forgot to mark XmlHttpRequestEventTarget as [Abstract].

**Comment by jdm** [comment]
WorkerGlobalScope needs it, too.

**Comment by nox** [comment]
@jdm Thanks for noticing this, r?

**Comment by jdm** [comment]
@bors-servo: r+
Looks good! Thanks for cleaning this up.

**Comment by michaelwu** [comment]
Thanks for getting this done!

**Pull request merged**
