### PR TITLE
Fix path to browserhtml in Linux runservo.sh

### LINKED ISSUE #13552: Servo nightly package has the wrong path for browserhtml
The package I download just now (`./servo -v == Servo 0.0.1-7da20f2
`) has the wrong path for browserhtml package. 

The `runservo.sh` says `./build/browserhtml-5c846c4e388d17ec/out/index.html`, but the unzipped folder looks like: 

```
.
├── build
│   ├── build-script-build
│   ├── out
│   └── output
```

I can't reproduce this locally, so I'd appreciate if someone can check the CI environment.

### PR DESCRIPTION
**Pull request by aneeshusa**
- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13552 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because needs to be verified manually

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13558)

### CODE REVIEW

**Comment by shinglyu** [comment]
On line 207 (can't seem to comment on the line directly), we still use `browserhtml_path.split('/')[-1]` for the macOS case, do we want to make them consistent across platforms?

**Review by shinglyu — COMMENTED** [review]
On line 207 (can't seem to comment on the line directly), we still use browserhtml_path.split('/')[-1] for the macOS case, do we want to make them consistent across platforms?

**Comment by aneeshusa** [comment]
I definitely would like to go through the rest of the packaging code and clean it up, but I think it's best to save that for a follow-up (maybe a few E-easy bugs), considering the OS X packaging is still working and I don't have a Mac to test on. For this PR I just want to get our Linux nightlies working again ASAP.

**Comment by shinglyu** [comment]
Is the embedding build the "infra change" you refer to? If that's not related to the patch, it's a r=me. :)

**Pull request merged**
