### PR TITLE
Removed createEvent cases, removed now-unused new_uninitializeds

### LINKED ISSUE #25137: per WPT, should throw NOT_SUPPORTED_ERR on more non-legacy event interfaces
dom/nodes/Document-createEvent.https.html has a big list of "someNonCreatableEvents", most of which throw NOT_SUPPORTED_ERR already. Remaining ones that should throw and don't:
* CloseEvent
* ErrorEvent
* PageTransitionEvent
* PopStateEvent
* ProgressEvent
* WebGLContextEvent

Chrome and Edge have a similar list of failures here.

### PR DESCRIPTION
**Pull request by pshaughn**
document.createEvent was creating some event types WHATWG now says shouldn't be created that way. This was the only caller of a few new_uninitialized methods, so those are removed too.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25137

- [X] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by CYBAI** [comment]
@bors-servo retry

- #24762

**Pull request merged**
