### PR TITLE
Add copy-to-clipboard feature under x11

### PR DESCRIPTION
**Pull request by aweinstock314**
The main work is in the the rust-clipboard library, this PR updates Cargo.lock and adds plumbing.

https://github.com/aweinstock314/rust-clipboard/commit/0337e48b3f1a8bbb274a10099a39d7d18e902494

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6654)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

I haven't done anything more than skim the X11 code. Maybe @glennw or @metajack can take a look at the changes in the submodule?

---

Reviewed 4 of 4 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/compositing/constellation.rs, line 467 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6654#-JuhoVqcwQXiMPM93mOO)** ([raw file](https://github.com/servo/servo/blob/094b045c4cccfd52a5e7d32f602c97af65af95bb/components/compositing/constellation.rs#L467)):</sup>
```rust
if let Some(ref ctx) = self.clipboard_ctx {
    if let Err(e) = ctx.set_contents(s) {
        debug!("Error setting clipboard contents ({})", e);
    }
}
```

---

<sup>**[components/script/textinput.rs, line 166 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6654#-JuhpR2x7AV70fJ61B-5)** ([raw file](https://github.com/servo/servo/blob/094b045c4cccfd52a5e7d32f602c97af65af95bb/components/script/textinput.rs#L166)):</sup>
Can we use `connect` here instead? http://doc.servo.org/collections/slice/trait.SliceConcatExt.html#tymethod.connect

---

<sup>**[components/script/textinput.rs, line 332 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6654#-JuhpeHY7cqjuWPglSZS)** ([raw file](https://github.com/servo/servo/blob/094b045c4cccfd52a5e7d32f602c97af65af95bb/components/script/textinput.rs#L332)):</sup>
Remove this.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6654)

**Comment by jdm** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/servo/Cargo.lock, line 1523 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6654#-JuiY05ncd73AmgeqMvz)** ([raw file](https://github.com/servo/servo/blob/51e35d40b1a75bcebd729e539fee7dd2726f8f17/components/servo/Cargo.lock#L1523)):</sup>
Let's update the version we use, rather than use two different versions.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6654)

**Comment by aweinstock314** [comment]
<sup>**[components/script/textinput.rs, line 166 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6654#-JuhpR2x7AV70fJ61B-5)** ([raw file](https://github.com/servo/servo/blob/094b045c4cccfd52a5e7d32f602c97af65af95bb/components/script/textinput.rs#L166)):</sup>
Replacing the for loop with ```
s.push_str("\n");
s.push_str(self.lines.iter().enumerate().filter(|&(i,_)| begin.line < i && i < end.line).map(|&(_,line)| line).connect("\n"));```
wouldn't handle the case where there are 0 intermediate lines correctly, and I think that trying to handle that case (conditionally emitting the newline) with ```connect``` would be more complicated than it currently is.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6654)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash +S-needs-rebase 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6654)

**Pull request merged**
