### PR TITLE
Ripped out regex_macros dependency

### PR DESCRIPTION
**Pull request by 0rvar**
Implements cleanup suggestion from #6114 .
`regex_macros` is no longer a dependency, unit tests still pass.

I have not tested the performance difference, is there an easy way to do so?
Does it matter?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6115)

### CODE REVIEW

**Comment by Manishearth** [comment]
Code looks good to me (r+ on that).

I'm not sure how we can bench this, but @burntsushi might be able to tell which would be faster here.

**Comment by BurntSushi** [comment]
`regex!` is nearly always faster because it:

1. Reduces heap allocation.
2. Reduces branching.
3. Converts some binary searches to `match` expressions.

The one major downside of `regex!` (other than it only being available on the nightly compiler) is the code bloat. I'm skeptical that two uses of `regex!` would significantly impact compile times or code bloat as mentioned in #6114. (In fact, if you compile with LTO, using `regex!` exclusively a small number of times could lead to less code bloat because it doesn't need to pull in the entire dynamic VM, compiler or parser!)

**Comment by Manishearth** [comment]
cc @mbrubeck I guess we should close this then?

Sorry, @awestroke :frowning:

**Comment by BurntSushi** [comment]
That said, don't take my word for it. :-) Is there an easy way to compare binary sizes before/after?

**Comment by Manishearth** [comment]
By ... comparing binary sizes before and after? :P

**Comment by Manishearth** [comment]
(Servo is statically linked to the most part)

**Comment by mbrubeck** [comment]
@awestroke, would you be willing to compare the size of a Servo binary built in `--release` mode with and without this patch?

It would also be interesting to do the same comparison with LTO enabled in the [`[profile.release]` section](http://doc.crates.io/manifest.html#the-[profile.*]-sections).

**Comment by awestroke** [comment]
@mbrubeck Absolutely. I'll be back with data

**Comment by awestroke** [comment]
Size measured using `du components/servo/target/release/servo`
<table>
  <tr>
    <td></td>
    <td>master</td>
    <td>cleanup-regex-macros</td>
    <td>diff</td>
  </tr>
  <tr>
    <td>lto: false</td>
    <td>94308 KB</td>
    <td>94280 KB</td>
    <td>-28 KB</td>
  </tr>
  <tr>
    <td>lto: true</td>
    <td>93620 KB</td>
    <td>93580 KB</td>
    <td>-40 KB</td>
  </tr>
</table>

**Comment by awestroke** [comment]
In review, this patch saves ~30KB of the release binary and some unknown, but relatively small, amount of compile time. It also removes a dependency.
On the other hand, `regex!` is more performant, but that might be negligible in this case.
Very small differences overall.

Close or merge?

**Comment by Manishearth** [comment]
I think we should keep the macro if it is more performant (even if negligible) for now. Those differences are really tiny otherwise.

**Comment by Manishearth** [comment]
We may want to revisit this later if/when we need to use more regexes.

Again, sorry about the lost work!

**Comment by awestroke** [comment]
No problem at all

**Pull request closed without merging**
