### PR TITLE
Make Response::url private.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14127)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r-
```
error[E0382]: use of partially moved value: `fetch_response`

   --> /home/travis/build/servo/servo/tests/unit/net/fetch.rs:387:13

    |

386 |     assert!(fetch_response.url_list.into_inner().len() == 0);

    |             ----------------------- value moved here

387 |     assert!(fetch_response.url().is_none());

    |             ^^^^^^^^^^^^^^ value used here after move

    |

    = note: move occurs because `fetch_response.url_list` has type `std::cell::RefCell<std::vec::Vec<url::Url>>`, which does not implement the `Copy` trait

error: aborting due to previous error
```

**Comment by Ms2ger** [comment]
Let's try that again...

@bors-servo r=nox

**Pull request merged**
