### PR TITLE
fix to bug #7604, tests for cookies in redirects

### LINKED ISSUE #7604: Write tests for cookie behaviour with HTTP redirects
I am interested in tests that ensure that:
* when a redirect from a.com to b.com is processed, the request to b.com contains cookies for b.com
* when a redirect from a.com to a.com is processed, any cookies set in the redirected response are sent in the second request

The existing `test_load_sets_cookies_in_the_resource_manager_when_it_get_set_cookie_header_in_response` and `test_load_sets_requests_cookies_header_for_url_by_getting_cookies_from_the_resource_manager` tests are good ones to model this work off of.

Code: tests/unit/net/http_loader.rs

### PR DESCRIPTION
**Pull request by njskalski**
initial pull request, waiting for feedback.

Fixes #7604.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7617)

### CODE REVIEW

**Comment by jdm** [comment]
Arg, sorry about the delay here. I'll review this today.

**Comment by jdm** [comment]
This looks great! Just a couple stylistic changes and then we can merge. Please also [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) all the commits into one.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 85 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1k2b-gSBsnHhw_8OO)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L85)):</sup>
If we use `mut initial_headers: Headers` then we don't need the separate clone on the next line.

---

<sup>**[tests/unit/net/http_loader.rs, line 690 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1k_V3bqdvkkIQU_IE)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L690)):</sup>
Let's use the DEFAULT_USER_AGENT constant here.

---

<sup>**[tests/unit/net/http_loader.rs, line 714 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1kNj4pMEJnRrNqqTO)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L714)):</sup>
nit: odd indentation here

---

<sup>**[tests/unit/net/http_loader.rs, line 770 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1l8Hxgwxa4-JX5HFQ)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L770)):</sup>
nit: odd indentation here

---

<sup>**[tests/unit/net/http_loader.rs, line 791 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1lJOMg9gh2XLkZ26R)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L791)):</sup>
DEFAULT_USER_AGENT

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7617)

**Comment by askalski** [comment]
could you be more specific about "odd indentation"? I tried to mimic lines from "test_load_errors_when_there_a_redirect_loop" on "else if". Do you mean these lines, or some other, below?

Also, I updated user-agent (to "default_opts().user_agent"). Please re-review it, and after I finish with indentation, I will "squash" the commit messages again.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 85 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1k2b-gSBsnHhw_8OO)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L85)):</sup>
If we use `mut headers: Headers` instead of `headers: &mut Headers` we don't need a clone anywhere.


---

<sup>**[tests/unit/net/http_loader.rs, line 690 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1k_V3bqdvkkIQU_IE)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L690)):</sup>
I would prefer to use `DEFAULT_USER_AGENT` instead.


---

<sup>**[tests/unit/net/http_loader.rs, line 714 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1kNj4pMEJnRrNqqTO)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L714)):</sup>
I would prefer this style (and feel free to adjust any others that don't match):
```rust
Ok(AssertRequestMustHaveHeaders::new(
    ResponseType::Redirect("http://mozilla.org".to_string()),
    expected_headers_x))
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7617)

**Comment by askalski** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 86 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1k2b-gSBsnHhw_8OO)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L86)):</sup>
I changed it as expected, but now they differ from

`ResponseType::WithHeaders(b, mut h) => {
            Ok(respond_with_headers(b, &mut h))
        }`

which was my inspiration. I don't get Rust's grammar so well to know what is the difference.


---

<sup>**[tests/unit/net/http_loader.rs, line 690 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1k_V3bqdvkkIQU_IE)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L690)):</sup>
I tried, and got an error that it's private. So I looked for something public that seems to do what I want.
I tried:
`use util::opts::{DEFAULT_USER_AGENT, default_user_agent_string)`
Again, it might be something with my lack of knowledge of Rust lang.
	
 


---

<sup>**[tests/unit/net/http_loader.rs, line 714 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1kNj4pMEJnRrNqqTO)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L714)):</sup>
thanks, that's much more informative. are there official code guidelines?


---

<sup>**[tests/unit/net/http_loader.rs, line 770 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1l8Hxgwxa4-JX5HFQ)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L770)):</sup>
I tried to mimic for instance line from test_load_errors_when_there_a_redirect_loop (if you mean "else if..." line). Where are the guidelines? Is there a code formatter?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7617)

**Comment by askalski** [comment]
I updated PR and Review.

**Comment by jdm** [comment]
I apologize for the long delay again. I promise a quicker review of subsequent changes!
-S-awaiting-review +S-needs-code-changes +S-needs-rebase 


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 85 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1k2b-gSBsnHhw_8OO)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L85)):</sup>
Ah, you're right. I've filed #7922 to fix that.


---

<sup>**[tests/unit/net/http_loader.rs, line 690 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1k_V3bqdvkkIQU_IE)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L690)):</sup>
Oh, this PR is built on an older version of servo that didn't have it. I guess a rebase will solve all this.


---

<sup>**[tests/unit/net/http_loader.rs, line 714 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1kNj4pMEJnRrNqqTO)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L714)):</sup>
No. We really need to make some official ones.


---

<sup>**[tests/unit/net/http_loader.rs, line 770 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7617#-K-1l8Hxgwxa4-JX5HFQ)** ([raw file](https://github.com/servo/servo/blob/6f22f4c8670f37d456d822fe21f05083b9e86162/tests/unit/net/http_loader.rs#L770)):</sup>
If you want to run [rustfmt](https://github.com/nrc/rustfmt) on this file in a separate commit/PR I would not object.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7617)

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for sticking with this!


---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7617)

**Comment by jdm** [comment]
```
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:969:24: 969:41 error: unresolved name `new_resource_task` [E0425]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:969     let resource_mgr = new_resource_task(default_opts().user_agent, None);
                                                                                                            ^~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:969:24: 969:41 help: run `rustc --explain E0425` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:970:23: 970:51 error: failed to resolve. Use of undeclared type or module `ControlMsg` [E0433]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:970     resource_mgr.send(ControlMsg::SetCookiesForUrl(url_x.clone(),
                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:970:23: 970:51 help: run `rustc --explain E0433` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:970:23: 970:51 error: unresolved name `ControlMsg::SetCookiesForUrl` [E0425]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:970     resource_mgr.send(ControlMsg::SetCookiesForUrl(url_x.clone(),
                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:970:23: 970:51 help: run `rustc --explain E0425` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:973:23: 973:51 error: failed to resolve. Use of undeclared type or module `ControlMsg` [E0433]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:973     resource_mgr.send(ControlMsg::SetCookiesForUrl(url_y.clone(),
                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:973:23: 973:51 help: run `rustc --explain E0433` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:973:23: 973:51 error: unresolved name `ControlMsg::SetCookiesForUrl` [E0425]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:973     resource_mgr.send(ControlMsg::SetCookiesForUrl(url_y.clone(),
                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:973:23: 973:51 help: run `rustc --explain E0425` to see a detailed explanation
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:1047:24: 1047:41 error: unresolved name `new_resource_task` [E0425]
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:1047     let resource_mgr = new_resource_task(default_opts().user_agent, None);
                                                                                                             ^~~~~~~~~~~~~~~~~
/Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:1047:24: 1047:41 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 6 previous errors
```
Sorry, the unit tests need updating to build against the latest code.

**Comment by Wafflespeanut** [comment]
@askalski You're close! Any plans to finish this off? :)

**Comment by askalski** [comment]
yes, absolutely. I just have a very busy time. I will try to fix it soon.

**Comment by jdm** [comment]
Ok, good to know :)

**Comment by askalski** [comment]
I am writing an updated version of this patch, but this time with less luck. The tests doesn't work as expected. Can you look at it?

**Comment by jdm** [comment]
@askalski What failures do the tests show?

**Comment by askalski** [comment]
---- http_loader::test_redirect_from_x_to_x_provides_x_with_cookie_from_first_response stdout ----
	thread 'http_loader::test_redirect_from_x_to_x_provides_x_with_cookie_from_first_response' panicked at 'assertion failed: expected_headers.len() != 0', /home/andrzej/slow_hdd/mozilla/servo/tests/unit/net/http_loader.rs:186

the cause is that in lines 1341 - 1344 I need to specify AssertRequestMustIncludeHeaders (or rebuild everything, which I don't necessarily know how to do :) ), but the problem is, that I don't have any prequisites (any required headers) from initial request to ask for, and passing either empty list or list with empty element fails.

**Comment by askalski** [comment]
It's late, I am going to sleep. I will try to get back to it tomorrow.

**Comment by askalski** [comment]
allright, I took a crash course of Rust, and now I feel I understand more.

I have several ideas how to fix last test:

1) change expected_headers in AssertRequestMustIncludeHeaders to Option<Headers>
2) create another AssertRequestMustIncludeHeaders clone with Option<Headers> (if that option is suggested, please suggest a name as well).
3) put an dummy Cookie to jar, and expect it in "initial" request at test_redirect_from_x_to_x_provides_x_with_cookie_from_first_response's Factory.

the reason the test doesn't work is that AssertRequestMustIncludeHeaders requires expected_headers not to be empty, and even if I remove that requirement, it still crashes around line 200, for the reason that there is a header "Cookies" with no body (I don't know why it appears).

any suggestions?

**Comment by askalski** [comment]
I think I was wrong about the reason of error. I added some additional println! statements, and it seems like the first ("initial") request is fine, it's the second that fails (after removing requirement that expected_headers are non-empty in line 186).

Does this mean that the cookie is not set? I mean, the test is OK, but the expected behaviour is not met?

**Comment by frewsxcv** [comment]
*[tests/unit/net/http_loader.rs, line 105 \[r8\]](https://reviewable.io:443/reviews/servo/servo/7617#-K5reT-iq4vGGcXlr4xS:-K5reT-iq4vGGcXlr4xT:1088979478) ([raw file](https://github.com/servo/servo/blob/c43a1b7374a023d8cad2bb2b759f7efc15afd6c1/tests/unit/net/http_loader.rs#L105)):*
These are equivalent: `b"foo"` and `"foo".as_bytes()`

More info [in the reference](https://doc.rust-lang.org/reference.html#byte-and-byte-string-literals)

Also bytes (which in Rust have data type `&[u8]`, a slice of unsigned integers), has a method `to_vec`: https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.to_vec

So the whole thing could be written: `b"".to_vec()`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7617)*

**Comment by askalski** [comment]
can someone pull this PR and run it locally? It seems that the last test (the one not working) is actually pointing servo's error.

**Comment by askalski** [comment]
Got it, needed to set "path=/" to set-cookie, my mistake.

**Comment by askalski** [comment]
ok, so I removed unnecessary lines. It's ready for another review (I think). How to "squash" all these commits into one (I did a merge somewhere on the line). Also, what was the command to automatically check coding style?

**Comment by KiChjang** [comment]
To check for tidiness, use `./mach test-tidy`.

To squash commits, do `git rebase -i HEAD~10`. This will open up your default editor and you'll see all 10 of your commits on your branch, with a `pick` keyword. To squash all your commits into one, change all the `pick` keywords into `f` or `fixup` EXCEPT for the first commit at the very top.

NB: It is good practice to create a new branch on your fork when trying to make PRs. Your master branch on your fork may get confused when you pull from upstream master in the future.

**Comment by jdm** [comment]
I usually refer people to [this explanation](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) about squashing.

**Comment by askalski** [comment]
Hi, I made another PR, because I was too noob with git to undo merge from master without destroying results of work.
The new one is : https://github.com/servo/servo/pull/9039

**Pull request closed without merging**
