### PR TITLE
Tentative fix for  issue #7110

### PR DESCRIPTION
**Pull request by fabricedesre**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7119)

### CODE REVIEW

**Comment by dzbarsky** [comment]
Thanks for the PR! r=me (but someone will need to tell bors to merge this)

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[components/devtools/actor.rs, line 201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7119#-JwK_0EI8ZVR1Ky1FsbH)** ([raw file](https://github.com/servo/servo/blob/d90f28648c9e56d73fdd65026b01a820ab154890/components/devtools/actor.rs#L201)):</sup>
if actor.handle_message(self, &msg_type.to_string(), msg, stream) == Ok(ActorMessageStatus::Ignored) { .. }

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7119)

**Comment by dzbarsky** [comment]
Also please fix the tidy check:
4.12s$ ./mach test-tidy
components/devtools/actor.rs:201: (much) overlong line

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 10 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/devtools/actor.rs, line 200 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7119#-JwKklrS-02czMrTcu8z)** ([raw file](https://github.com/servo/servo/blob/d90f28648c9e56d73fdd65026b01a820ab154890/components/devtools/actor.rs#L200)):</sup>
Please keep the `try` in order to propagate errors to the caller.

---

<sup>**[components/devtools/actor.rs, line 201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7119#-JwK_0EI8ZVR1Ky1FsbH)** ([raw file](https://github.com/servo/servo/blob/d90f28648c9e56d73fdd65026b01a820ab154890/components/devtools/actor.rs#L201)):</sup>
Note: this will require deriving PartialEq on the enum.

---

<sup>**[components/devtools/actor.rs, line 202 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7119#-JwKl5PgXegNDfkEDmLy)** ([raw file](https://github.com/servo/servo/blob/d90f28648c9e56d73fdd65026b01a820ab154890/components/devtools/actor.rs#L202)):</sup>
nit: indent this to match the opening " on the previous line.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7119)

**Comment by fabricedesre** [comment]
Review status: 8 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/devtools/actor.rs, line 200 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7119#-JwKklrS-02czMrTcu8z)** ([raw file](https://github.com/servo/servo/blob/d90f28648c9e56d73fdd65026b01a820ab154890/components/devtools/actor.rs#L200)):</sup>
Done.

---

<sup>**[components/devtools/actor.rs, line 201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7119#-JwK_0EI8ZVR1Ky1FsbH)** ([raw file](https://github.com/servo/servo/blob/d90f28648c9e56d73fdd65026b01a820ab154890/components/devtools/actor.rs#L201)):</sup>
Done.

---

<sup>**[components/devtools/actor.rs, line 202 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7119#-JwKl5PgXegNDfkEDmLy)** ([raw file](https://github.com/servo/servo/blob/d90f28648c9e56d73fdd65026b01a820ab154890/components/devtools/actor.rs#L202)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7119)

**Comment by jdm** [comment]
Looks fine. Squash, please!
-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 10 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7119)

**Comment by fabricedesre** [comment]
Should be all squashed properly now.

---

Review status: 6 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7119)

**Pull request merged**
