### PR TITLE
Remove the HTMLTable{Header,Data}CellElement interfaces

### LINKED ISSUE #17222: Table data and header cell interfaces no longer exist in the spec
`HTMLTableHeaderCellElement` and `HTMLTableDataCellElement` no longer exist in the spec.

`th` and `td` now just use the `HTMLTableCellElement` interface.

https://html.spec.whatwg.org/multipage/#the-th-element
https://html.spec.whatwg.org/multipage/#the-td-element

whatwg/html#1125

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes #17222.

This removes the `HTMLTableHeaderCellElement` and `HTMLTableDataCellElement` interfaces and uses the `HTMLTableCellElement` interface for both `th` and `td` elements, as per the spec.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17222.

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21856)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+

Thanks!

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /html/dom/interfaces.https.html?include=HTML.*:
  └ PASS [expected FAIL] HTMLTableCellElement must be primary interface of document.createElement("td")

  ▶ Unexpected subtest result in /html/dom/interfaces.https.html?include=HTML.*:
  └ PASS [expected FAIL] Stringification of document.createElement("td")

  ▶ Unexpected subtest result in /html/dom/interfaces.https.html?include=HTML.*:
  └ PASS [expected FAIL] HTMLTableCellElement must be primary interface of document.createElement("th")

  ▶ Unexpected subtest result in /html/dom/interfaces.https.html?include=HTML.*:
  └ PASS [expected FAIL] Stringification of document.createElement("th")

  ▶ Unexpected subtest result in /html/semantics/interfaces.html:
  └ PASS [expected FAIL] Interfaces for td

  ▶ Unexpected subtest result in /html/semantics/interfaces.html:
  └ PASS [expected FAIL] Interfaces for TD

  ▶ Unexpected subtest result in /html/semantics/interfaces.html:
  └ PASS [expected FAIL] Interfaces for th

  ▶ Unexpected subtest result in /html/semantics/interfaces.html:
  └ PASS [expected FAIL] Interfaces for TH

  ▶ OK [expected ERROR] /custom-elements/builtin-coverage.html

  ▶ Unexpected subtest result in /custom-elements/builtin-coverage.html:
  └ PASS [expected FAIL] td: document.createElement() should instantiate a customized built-in element

  ▶ Unexpected subtest result in /custom-elements/builtin-coverage.html:
  └ PASS [expected FAIL] th: document.createElement() should instantiate a customized built-in element
```

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by jdm** [comment]
Sorry, one last set:
```
  ▶ Unexpected subtest result in /html/dom/interfaces.https.html?include=HTML.*:
  └ PASS [expected FAIL] HTMLTableCellElement must be primary interface of document.createElement("td")

  ▶ Unexpected subtest result in /html/dom/interfaces.https.html?include=HTML.*:
  └ PASS [expected FAIL] Stringification of document.createElement("td")

  ▶ Unexpected subtest result in /html/dom/interfaces.https.html?include=HTML.*:
  └ PASS [expected FAIL] HTMLTableCellElement must be primary interface of document.createElement("th")

  ▶ Unexpected subtest result in /html/dom/interfaces.https.html?include=HTML.*:
  └ PASS [expected FAIL] Stringification of document.createElement("th")
```

**Pull request merged**
