### PR TITLE
Update FileAPI WPT idlharness

### PR DESCRIPTION
**Pull request by izgzhen**
Updated to match the latest https://w3c.github.io/FileAPI/#idl-index

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12662)

### CODE REVIEW

**Comment by izgzhen** [comment]
@bors-servo retry

The failures look unrelated to me, but maybe someone could help explain what happened?

**Comment by izgzhen** [comment]
err, why is retry not working (again)?

**Comment by jdm** [comment]
Please file a new issue about the test failure or link to an existing one whenever retrying a build.

**Comment by izgzhen** [comment]
Filed at #12681

**Pull request merged**
