### PR TITLE
Update gstreamer + [Imgbot] Optimize Images + whitesource

### PR DESCRIPTION
**Pull request by szb512**
Updates gstreamer from 1.14 to 1.16.

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [x ] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23243)

### CODE REVIEW

**Comment by Eijebong** [comment]
Pretty sure you pushed too many commits ;)

**Comment by szb512** [comment]
I did not push too many commits.

**Comment by szb512** [comment]
Also includes imgbot.

**Comment by Manishearth** [comment]
The WPT files are vendored, while we have a syncing mechanism we usually won't land general changes like these especially in unrelated PRs. Please make those changes upstream on https://github.com/w3c/web-platform-tests

Also, the gstreamer file link you've listed doesn't exist yet, @ferjm will have to create it. We'll also need to wait for the 1.16 gstreamer-rs crate to exist.

**Pull request closed without merging**
