### PR TITLE
Update WR (mostly optimizations).

### PR DESCRIPTION
**Pull request by glennw**
* Correctly handle degenerate border corner radii.
* Hold glyphs and images in resource cache longer.
* Optimize the primitive instance code.
* Texture cache coalescing optimizations.
* Workarounds for a couple of driver shader parsing issues.
* Optimize vertex format sizes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17052)

### CODE REVIEW

**Comment by jdm** [comment]
```
94.90s$ ./mach build -d --verbose

cargo build -v

    Updating git repository `https://github.com/servo/webrender`

error: failed to load source for a dependency on `webrender_traits`

Caused by:

  Unable to update https://github.com/servo/webrender#9cc838b7

Caused by:

  failed to fetch into /home/travis/build/servo/servo/.cargo/git/db/webrender-c3596abe1cf4f320

Caused by:

  [9/-3] Object not found - no match for id (6902f7d200ad115e5e9a95e08303db15f0f0dbba)

Build FAILED in 0:00:00
```

**Comment by jdm** [comment]
This might be fixed by #17040.

**Comment by glennw** [comment]
@jdm Is this worth retrying? Or is it going to always fail due to that CI / infra issue?

**Comment by jdm** [comment]
This should be mergeable once that PR merges.

**Pull request merged**
