### PR TITLE
WebGL: Finish, Flush, DetachShader, GenerateMipmap

### PR DESCRIPTION
**Pull request by cbrewster**
Implements #10212 and #10213

r? @emilio

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10215)

### CODE REVIEW

**Comment by emilio** [comment]
This is blocked on a webrender + webrender_traits + offscreen_gl_context update, but looks great otherwise! :)

**Comment by ConnorGBrewster** [comment]
Added support for detaching shaders #10216

**Comment by emilio** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/webglprogram.rs, line 117 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDrx3VuOls6tK9DTL4B:-KDrx3VuOls6tK9DTL4C:-1661977276) ([raw file](https://github.com/servo/servo/blob/83c10b6486ad9919d4ca21221a958837827559b1/components/script/dom/webglprogram.rs#L117)):*
This should never ever happen, could you put an `error!("detachShader: Unexpected shader type")` here also?

I'd go to even putting `unreachable!()`, but...

You can do the same in `attach_shader`.

---

*[components/script/dom/webglprogram.rs, line 128 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDrwnQZw_EvsSUcNsE3:-KDrwnQ_n60_WRSXMVak:700633821) ([raw file](https://github.com/servo/servo/blob/83c10b6486ad9919d4ca21221a958837827559b1/components/script/dom/webglprogram.rs#L128)):*
Hrm... At first I wondered if appart from this we should be resetting the program link status, but it seems we don't (see [gecko's implementation](https://dxr.mozilla.org/mozilla-central/source/dom/canvas/WebGLProgram.cpp#451)).

So this looks great! :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10215)*

**Comment by ConnorGBrewster** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/webglprogram.rs, line 117 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDrx3VuOls6tK9DTL4B:-KDsfvu6spUAQ11IU0-G:368453428) ([raw file](https://github.com/servo/servo/blob/83c10b6486ad9919d4ca21221a958837827559b1/components/script/dom/webglprogram.rs#L117)):*
Sounds good, I will do that!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10215)*

**Comment by emilio** [comment]
Mipmap generation is tricky, but this looks like the correct approach so far (modulo the nits). Great job! :)

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/webgltexture.rs, line 27 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDzGiuAD4VjsqMwinPG:-KDzGiuBWop41O-lpwCP:392776529) ([raw file](https://github.com/servo/servo/blob/c52b09cc63979051753e1f6363b628314a445b38/components/script/dom/webgltexture.rs#L27)):*
ultra-nit: I'd prefer this definition (and the `impl`) to go under WebGLTexture, since that's what I'd expect to find in this file.

---

*[components/script/dom/webgltexture.rs, line 74 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDzG7-EOEbuWuyWAgUc:-KDzG7-EOEbuWuyWAgUd:-1550973354) ([raw file](https://github.com/servo/servo/blob/c52b09cc63979051753e1f6363b628314a445b38/components/script/dom/webgltexture.rs#L74)):*
nit: We should be able to do this array a plain array, and the ImageInfo fields `Cell`, since they're all copy. It'd be easier to manage and a bit faster to access.

---

*[components/script/dom/webgltexture.rs, line 75 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDzH0f5fEcVsTfK8gDg:-KDzH0f6qOOTvXj95Zvu:1297421899) ([raw file](https://github.com/servo/servo/blob/c52b09cc63979051753e1f6363b628314a445b38/components/script/dom/webgltexture.rs#L75)):*
nit: Put a comment here to make clear this can only be either `1` or `6`.

---

*[components/script/dom/webgltexture.rs, line 147 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDzGrpv_NO-z_WlWShk:-KDzGrpw42uZNL4kmaNn:-83659858) ([raw file](https://github.com/servo/servo/blob/c52b09cc63979051753e1f6363b628314a445b38/components/script/dom/webgltexture.rs#L147)):*
nit: You already have the `target` parameter (`self.target`).

---

*[components/script/dom/webgltexture.rs, line 151 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDzGMqw_okP6H4OYpqt:-KDzGMqw_okP6H4OYpqu:695248431) ([raw file](https://github.com/servo/servo/blob/c52b09cc63979051753e1f6363b628314a445b38/components/script/dom/webgltexture.rs#L151)):*
nit: This probably doesn't need to call `borrow_mut()`, just `borrow()`, but this comment would be obsolete if it's converted to a plain array.

---

*[components/script/dom/webgltexture.rs, line 153 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDzGQddJ_fTAbTVRtNJ:-KDzGQddJ_fTAbTVRtNK:-726684557) ([raw file](https://github.com/servo/servo/blob/c52b09cc63979051753e1f6363b628314a445b38/components/script/dom/webgltexture.rs#L153)):*
nit: Prefer snake_case for method names.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10215#-:-KDzHh8WIxTHTiHPHXNs:1082798167)*

**Comment by ConnorGBrewster** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/webgltexture.rs, line 74 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDzG7-EOEbuWuyWAgUc:-KE-jIkfcEaR58zkqLID:5411819) ([raw file](https://github.com/servo/servo/blob/c52b09cc63979051753e1f6363b628314a445b38/components/script/dom/webgltexture.rs#L74)):*
Done, although I did have to use some unsafe code to initialize the entire array. If there is a better way, that would be awesome.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10215)*

**Comment by emilio** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[components/script/dom/webgltexture.rs, line 74 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDzG7-EOEbuWuyWAgUc:-KE1O2r2GUidgiRdH6OB:-447984431) ([raw file](https://github.com/servo/servo/blob/c52b09cc63979051753e1f6363b628314a445b38/components/script/dom/webgltexture.rs#L74)):*
What I meant was making `ImageInfo`'s fields as cells, so this becomes, `[ImageInfo; MAX_LEVEL_COUNT * MAX_FACE_COUNT]`, but `ImageInfo` becomes `width: Cell<u32>, ...`, so we can mutate the fields.

---

*[components/script/dom/webgltexture.rs, line 56 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10215#-KE1O0UnInVzj6iWbtnl:-KE1O0UnInVzj6iWbtnm:1796581934) ([raw file](https://github.com/servo/servo/blob/3d5e7a232e04813b97af8ea15f283c773834a2f7/components/script/dom/webgltexture.rs#L56)):*
What I meant was using

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10215)*

**Comment by ConnorGBrewster** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/script/dom/webgltexture.rs, line 74 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10215#-KDzG7-EOEbuWuyWAgUc:-KE1g7NKxoK-LWL9v-GM:-180069609) ([raw file](https://github.com/servo/servo/blob/c52b09cc63979051753e1f6363b628314a445b38/components/script/dom/webgltexture.rs#L74)):*
Ahh yes, that does make a lot more sense! Although I will probably still run into the issue with array initialization because `ImageInfo` won't be able to derive Copy.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10215)*

**Comment by ConnorGBrewster** [comment]
@emilio I moved to DOMRefCell for the array. The only issue is that the convenience functions cannot return a reference(unless there is a way that I am unaware of). So currently they are just copied on return.

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10215#-:-KE1tEGZVRmaehQrNoou:-1890076898)*

**Comment by jdm** [comment]
They can return `Ref<T>` instead of `&T` (ie. the result of `.borrow()`), I believe.

**Comment by ConnorGBrewster** [comment]
The borrow returns the array and once I get an element at an index it returns a plain `ImageInfo`

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10215#-:-KE1u-U-utOcPqHRdUOH:693368846)*

**Comment by ConnorGBrewster** [comment]
@jdm Looks like `Ref::map` did the trick

**Comment by ConnorGBrewster** [comment]
I have the bulk of the work done for generating mipmaps... 

I still need to implement a couple of extra functions on `WebGLTexture` and finish adding support for storing depth in `ImageInfo` and adding support for `TEXTURE_CUBE_MAP`. 

I am also working on creating a basic test for this, the `texture-mips.html` wpt test will require implementing a few other things that are currently blocked on #5014.

**Comment by ConnorGBrewster** [comment]
This is almost ready for review. Currently the test crashes due to #10326. Once that is resolved I can make sure this actually works and then it will be ready for review.

**Comment by ConnorGBrewster** [comment]
After reverting angle to an older version, the test works. Mipmaps are generated and the image appears! This PR will be blocked until #10326 is resolved.

**Comment by emilio** [comment]
Looks good so far (btw did the angle update solve the `sampler2d` issue?), but I don't think the tests are actually using the mipmaps, am I right?

-S-awaiting-review +S-awaiting-answer 

---

Reviewed 4 of 7 files at r9, 6 of 9 files at r12.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 453 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELsTc5n0Cn1BWVmmWd:-KELsTc5n0Cn1BWVmmWe:-1052765539) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webglrenderingcontext.rs#L453)):*
This should be InvalidOperation

---

*[components/script/dom/webgltexture.rs, line 130 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELt7-gEKpbwKxR-EmV:-KELt7-hvHriPthfxKug:251381816) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webgltexture.rs#L130)):*
This could be structured better like:

```rust
let target = match self.target.get() {
    Some(target) => target,
    None => {
        error!(...);
        return Err(WebGLError::InvalidOperation);
    }
}
```

And using `target` instead of `.get().unwrap()` below.

---

*[components/script/dom/webgltexture.rs, line 288 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELu3mfGVkEZDchic7n:-KELu3mgY42NqmQfmQTL:-1937949302) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webgltexture.rs#L288)):*
Maybe returning a reference here could be smarter, so we don't blindly copy every time.

---

*[components/script/dom/webgltexture.rs, line 299 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELtiyYG8LnlTtBsmYR:-KELtiy_QZRzqhzkEKmf:-1698792097) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webgltexture.rs#L299)):*
What do we use `is_resolved` and `invalidate_resolve_cache` for? If they're not used, please remove them.

---

*[components/script/dom/webgltexture.rs, line 369 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELuO-Zi0U_JG6_y7By:-KELuO-_YfksGpIA2uE5:-1133176577) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webgltexture.rs#L369)):*
I don't think this is quite correct, we should check if the format is one of the compressed texture formats, the `COMPRESEED_TEXTURE_FORMATS` is a constant to query the context about what compressed texture formats it supports. 

Actually we don't support any (which is allowed), so this will always return false, but we should make a TODO or NOTE comment here about updating this code when we support them.

---

*[components/script/dom/bindings/trace.rs, line 206 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELvqGtAOGFF9pkiVuf:-KELvqGtAOGFF9pkiVug:-1477595531) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/bindings/trace.rs#L206)):*
Maybe, since this does not contains managed fields, we should remove this impl, and the `ImageInfo` derive, and use `no_jsmanaged_fields!(ImageInfo, [ImageInfo; 31 * 6])` in the webgltexture.rs file.

---

*[tests/html/test_webgl_texture_mipmaps.html, line 36 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELwwBhP0aMhSGyMq9v:-KELwwBj2TJ0tVJHpvqz:337240823) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/tests/html/test_webgl_texture_mipmaps.html#L36)):*
How does this use the generated mipmaps?

also, nit, no need to use `vec2(vTextureCoord.s, vTextureCoord.t)`, just `vTextureCoord` should do it.

---

*[tests/html/test_webgl_texture_mipmaps.html, line 37 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELxTNqyjLXbmduboXp:-KELxTNrUFF4a5knz_Is:772989062) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/tests/html/test_webgl_texture_mipmaps.html#L37)):*
Please remove this comment.

---

*[tests/html/test_webgl_texture_mipmaps.html, line 70 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELxXNbicCDFXenocHB:-KELxXNc3fc8qM_MT3tJ:1013757134) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/tests/html/test_webgl_texture_mipmaps.html#L70)):*
nit: `console.log` instead of `alert`.

---

*[tests/wpt/mozilla/tests/mozilla/webgl/tex_image_2d_mipmap.html, line 30 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELxq8SVgIa2byBXP_w:-KELxq8UpGmSaNESzL0c:180922097) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/tests/wpt/mozilla/tests/mozilla/webgl/tex_image_2d_mipmap.html#L30)):*
Same here, how does this use the generated mipmaps?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10215#-:-KELy5clbBJf2xosI6Ev:-1339206308)*

**Comment by ConnorGBrewster** [comment]
@emilio the test does use mipmaps because of `gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);`. If you remove `gl.generateMipmap(gl.TEXTURE_2D);`, the texture will not be rendered. Has there been an update to angle

I just tried rebasing this with master and it still has the `sampler2d` issue.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 453 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELsTc5n0Cn1BWVmmWd:-KEMNy-M86a0Ceay0b1E:-499146009) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webglrenderingcontext.rs#L453)):*
Done.

---

*[components/script/dom/webgltexture.rs, line 130 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELt7-gEKpbwKxR-EmV:-KEMO1A2T-QS-laZuUg3:-499146009) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webgltexture.rs#L130)):*
Done.

---

*[components/script/dom/webgltexture.rs, line 288 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELu3mfGVkEZDchic7n:-KEMMQJphQT5shPsjCGr:-1912896575) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webgltexture.rs#L288)):*
I wanted to do that, and maybe the is a way. I originally used Ref::map, but in `generateMipmap`, it stores a reference to the base image info and then iterates through all the levels and sets the new image info, but it will crash because it tries to mutably borrow the `image_info_array` while it is already borrowed from the base image info

---

*[components/script/dom/webgltexture.rs, line 299 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELtiyYG8LnlTtBsmYR:-KEMModIKHzLAx_SJgWn:322306983) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webgltexture.rs#L299)):*
Missed this during cleanup.

---

*[components/script/dom/webgltexture.rs, line 369 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELuO-Zi0U_JG6_y7By:-KEMMsPQtj5T09kyIvb0:-499146009) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webgltexture.rs#L369)):*
Done.

---

*[components/script/dom/bindings/trace.rs, line 206 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELvqGtAOGFF9pkiVuf:-KEMN1eXl8cRKvSmGiy-:-499146009) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/bindings/trace.rs#L206)):*
Done.

---

*[tests/html/test_webgl_texture_mipmaps.html, line 36 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELwwBhP0aMhSGyMq9v:-KEMNQwpd4VEsswZZYK5:1084271926) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/tests/html/test_webgl_texture_mipmaps.html#L36)):*
`gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);` forces it to use mipmaps

---

*[tests/html/test_webgl_texture_mipmaps.html, line 37 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELxTNqyjLXbmduboXp:-KEMNRWfY4lBrOMjwE-6:-499146009) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/tests/html/test_webgl_texture_mipmaps.html#L37)):*
Done.

---

*[tests/html/test_webgl_texture_mipmaps.html, line 70 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELxXNbicCDFXenocHB:-KEMNS18FYDJlB3S-j2S:-499146009) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/tests/html/test_webgl_texture_mipmaps.html#L70)):*
Done.

---

*[tests/wpt/mozilla/tests/mozilla/webgl/tex_image_2d_mipmap.html, line 30 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELxq8SVgIa2byBXP_w:-KEMNWhQePButq60wK_S:1084271926) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/tests/wpt/mozilla/tests/mozilla/webgl/tex_image_2d_mipmap.html#L30)):*
`gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);` forces it to use mipmaps

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10215#-:-KEMLVkUpWAOpH1-8lhD:251129710)*

**Comment by emilio** [comment]
Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/webgltexture.rs, line 288 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELu3mfGVkEZDchic7n:-KEMrOezsd8n3x0Dh-Pu:1356658486) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/components/script/dom/webgltexture.rs#L288)):*
Ahh I see, maybe using an extra block could avoid that, but anyway, this is a sligh optimisation, so there's no problem :)

---

*[tests/html/test_webgl_texture_mipmaps.html, line 36 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10215#-KELwwBhP0aMhSGyMq9v:-KEMrnL-jxefc89oGAwO:1588863563) ([raw file](https://github.com/servo/servo/blob/08c596c396b9350c23d7ad578b7ebe52104716c6/tests/html/test_webgl_texture_mipmaps.html#L36)):*
Gotcha, missed that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10215)*

**Comment by emilio** [comment]
Looks great! Just a few nits and this is good to go.

Please squash your commits also, or ensure every one compiles individually (the former is easier I think).

-S-awaiting-answer -S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 5 files at r14, 4 of 4 files at r15.
Review status: 13 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 1237 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEMz5pfux__-GgzF0AY:-KEMz5pfux__-GgzF0AZ:810197677) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webglrenderingcontext.rs#L1237)):*
Mind leaving a comment about why this is `1`, not really so important, but I hate magic numbers :)

---

*[components/script/dom/webgltexture.rs, line 43 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEN0hIvpY3T27IWLCvP:-KEN0hIvpY3T27IWLCvQ:-614896784) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L43)):*
Do we use this field? It doesn't we do.

---

*[components/script/dom/webgltexture.rs, line 111 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEN15RWsS5L-B5JE44X:-KEN15RWsS5L-B5JE44Y:1123628922) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L111)):*
Check `level` also here? Alternatively, make the params unsigned and give the responsability of this to the caller.

---

*[components/script/dom/webgltexture.rs, line 158 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEMzu1pIISjP6Lj4uzA:-KEMzu1pIISjP6Lj4uzB:-1279868130) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L158)):*
We might want to check if `base_mipmap_level + base_image_info.get_max_mipmap_levels()` is zero, to prevent crashing because of an underflow here. This could only happen in real corner cases, but it's an easy test and it's worth it I think.

---

*[components/script/dom/webgltexture.rs, line 305 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEN-za89C-8L9Z3M40w:-KEN-za9VuvUuUIyeo4G:-1732573160) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L305)):*
I don't think this can't happen as of right now, can we replace it for an `assert!(self.base_mipmap_level < MAX_LEVEL_COUNT)` and just return `ImageInfo`?

---

*[components/script/dom/webgltexture.rs, line 338 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEMyY9l9xuLS-zTM4RH:-KEMyY9l9xuLS-zTM4RI:2003140044) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L338)):*
There's some cool parts of the rust standard library, and on of it is that you don't have to implement `is_power_of_two()` for a number manually using `sqrt()`, so this can be read just as:

```rust
self.width.is_power_of_two() && self.height.is_power_of_two() && self.depth.is_power_of_two()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10215#-:-KEN-fNigazwTk09OItW:-1196568051)*

**Comment by ConnorGBrewster** [comment]
Review status: 13 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 1237 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEMz5pfux__-GgzF0AY:-KEN4HohX9OqON02lFa7:-697028300) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webglrenderingcontext.rs#L1237)):*
Added comment.

---

*[components/script/dom/webgltexture.rs, line 43 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEN0hIvpY3T27IWLCvP:-KEN4Fz-t1rdnba_67_H:119920281) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L43)):*
Removed field.

---

*[components/script/dom/webgltexture.rs, line 111 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEN15RWsS5L-B5JE44X:-KEN4Eu6RA7M9QcHZZcw:-499146009) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L111)):*
Done.

---

*[components/script/dom/webgltexture.rs, line 158 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEMzu1pIISjP6Lj4uzA:-KEN4D4id--eG36NL5g7:-499146009) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L158)):*
Done.

---

*[components/script/dom/webgltexture.rs, line 305 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEN-za89C-8L9Z3M40w:-KEN4CMuLkRBEELNDG1F:-499146009) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L305)):*
Done.

---

*[components/script/dom/webgltexture.rs, line 338 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEMyY9l9xuLS-zTM4RH:-KEN49sYbsT80ZP3qyar:-499146009) ([raw file](https://github.com/servo/servo/blob/27a12bb1908b2dba6bca4920843f2f9484545646/components/script/dom/webgltexture.rs#L338)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10215)*

**Comment by emilio** [comment]
Remove the unneeded casts and it's done! :)

-S-blocked-on-external -S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r16, 2 of 2 files at r17.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/webgltexture.rs, line 110 \[r17\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEN6BIs6BFBibRdSxry:-KEN6BIs6BFBibRdSxrz:736455243) ([raw file](https://github.com/servo/servo/blob/3d6eeb2a92484bef6102b8e6cd41ea0f7d2db078/components/script/dom/webgltexture.rs#L110)):*
We don't need these casts anymore

---

*[tests/html/test_webgl_texture_mipmaps.html, line 22 \[r17\]](https://reviewable.io:443/reviews/servo/servo/10215#-KEN6PNDkVFJqptwGyC_:-KEN6PNDkVFJqptwGyCa:888974924) ([raw file](https://github.com/servo/servo/blob/3d6eeb2a92484bef6102b8e6cd41ea0f7d2db078/tests/html/test_webgl_texture_mipmaps.html#L22)):*
heh, cool :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10215#-:-KEN6YWC5mDU25g551SI:-1589662465)*

**Comment by emilio** [comment]
Looks great, awesome job! :)

@bors-servo: r+

**Comment by emilio** [comment]
@bors-servo: r- clean force

Tidy complains about trailing whitespace in `webglrenderingcontext.rs`, and there's no point in making the rest of the queue stop.

**Comment by emilio** [comment]
Fix it and feel free to use `@bors-...: r=emilio` after it :)

@bors-servo: delegate+

**Comment by emilio** [comment]
Wohooo! Congratulations for landing this @ConnorGBrewster :)

**Comment by ConnorGBrewster** [comment]
@emilio Thanks for all the help!  :)

**Pull request merged**
