### PR TITLE
Update js.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14225)

### CODE REVIEW

**Comment by nox** [comment]
This is an intermittent and the compile error disappeared.

@bors-servo r=jdm,Ms2ger

**Comment by nox** [comment]
Damn Homu.

@bors-servo try- r=jdm,Ms2ger force

**Comment by notriddle** [comment]
Why was a commit with the description "WIP" allowed into master?

**Pull request merged**
