### PR TITLE
Leak message ports in Dom, until they are closed

### LINKED ISSUE #24488: Intermittent failure in /fetch/security/embedded-credentials.tentative.sub.html
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: The image should not load. expected \"Error\" but got \"Load\"", 
    "stack": "c.port1.onmessage<@http://web-platform.test:8000/fetch/security/embedded-credentials.tentative.sub.html:36:11\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25\nTest.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1948:32\n", 
    "subtest": "Embedded credentials are treated as network errors in new windows.", 
    "test": "/fetch/security/embedded-credentials.tentative.sub.html", 
    "line": 197608, 
    "action": "test_result", 
    "expected": "TIMEOUT"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": "Test timed out", 
    "stack": null, 
    "subtest": "Embedded credentials matching the top-level are treated as network errors for cross-origin URLs.", 
    "test": "/fetch/security/embedded-credentials.tentative.sub.html", 
    "line": 197611, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

### LINKED ISSUE #24810: open.spotify.com panics with 'post_messageport_msg called on an unknown port'
https://open.spotify.com

```
post_messageport_msg called on an unknown port. (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/dom/globalscope.rs:462)
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
   1: backtrace::backtrace::trace
   2: backtrace::capture::Backtrace::create
   3: backtrace::capture::Backtrace::new
   4: servo::main::{{closure}}
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: script::dom::globalscope::GlobalScope::post_messageport_msg
   8: script::dom::messageport::MessagePort::post_message_impl
   9: <script::dom::messageport::MessagePort as script::dom::bindings::codegen::Bindings::MessagePortBinding::MessagePortBinding::MessagePortMethods>::PostMessage_
  10: script::dom::bindings::codegen::Bindings::MessagePortBinding::MessagePortBinding::postMessage::{{closure}}
  11: core::ops::function::FnOnce::call_once
  12: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::panicking::try
  16: std::panic::catch_unwind
  17: mozjs::panic::wrap_panic
  18: script::dom::bindings::codegen::Bindings::MessagePortBinding::MessagePortBinding::postMessage
  19: CallJitMethodOp
  20: script::dom::bindings::utils::generic_call
  21: script::dom::bindings::utils::generic_method
  22: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  23: _ZL9InterpretP9JSContextRN2js8RunStateE
  24: _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  25: _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  26: _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
  27: _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE
  28: mozjs::rust::wrappers::JS_CallFunctionValue
  29: script::dom::bindings::codegen::Bindings::WindowBinding::FrameRequestCallback::Call
  30: script::dom::bindings::codegen::Bindings::WindowBinding::FrameRequestCallback::Call__
  31: script::dom::document::AnimationFrameCallback::call
  32: script::dom::document::Document::run_the_animation_frame_callbacks
  33: script::script_thread::ScriptThread::handle_tick_all_animations
  34: script::script_thread::ScriptThread::handle_msg_from_constellation
  35: script::script_thread::ScriptThread::handle_msgs::{{closure}}
  36: script::script_thread::ScriptThread::profile_event
  37: script::script_thread::ScriptThread::handle_msgs
  38: script::script_thread::ScriptThread::start
  39: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}::{{closure}}
  40: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  41: <script::script_thread::ScriptThread as script_traits::ScriptThreadFactory>::create::{{closure}}
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
  43: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
  44: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  45: std::panicking::try::do_call
  46: __rust_maybe_catch_panic
  47: std::panicking::try
  48: std::panic::catch_unwind
  49: std::thread::Builder::spawn_unchecked::{{closure}}
  50: core::ops::function::FnOnce::call_once{{vtable.shim}}
  51: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  52: std::sys::unix::thread::Thread::new::thread_start
  53: _pthread_body
  54: _pthread_start
```

### LINKED ISSUE #25461: Fix messageport "GC'ed too early"
Part of https://github.com/servo/servo/issues/25208, with regards to 

- Figure out the "port GC'ed too early" issues: #24707 and #24810

I'm thinking we might want to switch to the "leak memory" strategy, where we would hold a `Dom<MessagePort>` instead of a `Weak` inside `ManagedMessagePort` https://github.com/servo/servo/blob/709e06928a3cd09426a54cab66aaa8557d739239/components/script/dom/globalscope.rs#L256

Then we could remove those when [`close`](https://github.com/servo/servo/blob/709e06928a3cd09426a54cab66aaa8557d739239/components/script/dom/globalscope.rs#L624) is called on a port, as opposed to rely on the GC mechanism of Spidermonkey.

I haven't been able to diagnose what exactly triggers the "early GC" in the two issues mentioned, and I think for now we can simply assume that we cannot rely on SM to fully manage the lifetimes of ports. 

Instead, so that it at least "works" when for example browsing Spotify, we could just leak them inside a `Dom`, and only drop them if the JS actually calls `Close`, or if the page is navigated away from. 

Then later we could try to come-up with our own heuristics to GC ports that are logically unreachable. 

The spec has a note on the topic: https://html.spec.whatwg.org/multipage/#ports-and-garbage-collection

### PR DESCRIPTION
**Pull request by gterzian**
FIX #25461
FIX #24810
FIX #24488

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by gterzian** [comment]
Ok looks like this one is ready for review. 

@jdm r?

**Comment by gterzian** [comment]
Please note there is a potential follow-up, at https://github.com/servo/servo/issues/25772

**Comment by gterzian** [comment]
@jdm r?

**Comment by jdm** [comment]
This is in my queue to review. Apologies about the wait.

**Comment by jdm** [comment]
```
  ▶ CRASH [expected OK] /html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events.dedicatedworker.html
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ 
  │ 
  │ 
  │ remove_message_port called on a global not managing the port. (thread WebWorker for http://web-platform.test:8000/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/support/promise-rejection-events.js, at components/script/dom/globalscope.rs:666)
  │ stack backtrace:
  │    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  │    1: core::fmt::write
  │    2: std::io::Write::write_fmt
  │    3: servo::backtrace::print
  │    4: servo::main::{{closure}}
  │    5: std::panicking::rust_panic_with_hook
  │    6: std::panicking::begin_panic
  │    7: script::dom::globalscope::GlobalScope::remove_message_port
  │    8: <script::dom::globalscope::MessageListener::notify::process_remove_message_port<F> as script::task::TaskOnce>::run_once
  │    9: <T as script::task::TaskBox>::run_box
  │   10: script::dom::workerglobalscope::WorkerGlobalScope::process_event
  │   11: <script::dom::dedicatedworkerglobalscope::DedicatedWorkerGlobalScope as script::dom::abstractworkerglobalscope::WorkerEventLoopMethods>::handle_event
  │   12: script::dom::abstractworkerglobalscope::run_worker_event_loop
  │   13: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  │   14: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   15: _ZN3std9panicking3try7do_call17hd915b3dca089cc12E.llvm.17344723410305141537
  │   16: __rust_maybe_catch_panic
  │   17: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  │   19: std::sys::unix::thread::Thread::new::thread_start
  │   20: _pthread_body
  │   21: _pthread_start
  │ [2020-02-21T16:24:16Z ERROR servo] remove_message_port called on a global not managing the port.
  └ Pipeline failed in hard-fail mode.  Crashing!
```

**Comment by gterzian** [comment]
Ah yes, if the test closes the port, then we can't be sure it's still there when this message is handled. I turned this into a no-op, see https://github.com/servo/servo/pull/25771/files#diff-59d233642d0ce6d687484bdd009e1017R661

**Pull request merged**
