### PR TITLE
Added missing NavigatorId attributes

### PR DESCRIPTION
**Pull request by asajeffrey**
Add the missing attributes from https://html.spec.whatwg.org/multipage/system-state.html#navigatorid

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because there are already tests for Navigator

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23551)

### CODE REVIEW

**Comment by asajeffrey** [comment]
These missing attributes are blockers for running sketchfab:
```
./mach run -r --pref dom.webvr.enabled --pref dom.webvr.test --pref dom.gamepad.enabled https://sketchfab.com/3d-models/disco-ball-ff4fcb7af1e248c2964c18e8779f1bd7
[2019-06-11T16:18:34Z ERROR script::dom::bindings::error] Error at https://static.sketchfab.com/static/builds/web/dist/viewer-a8c3ce6e8219e56349b21857ce328c62.js:1:556278 navigator.vendor is undefined
[2019-06-11T16:18:34Z ERROR offscreen_gl_context::draw_buffer] The given GLContext doesn't support requested antialising
```
Unfortunately fixing this just causes other errors, but we may as well fix this.

**Comment by jdm** [comment]
A bunch of failures caused by #23332.

**Comment by asajeffrey** [comment]
Hmm, is the best bet to mark those tests as having expectation `FAIL`, or wait until #23332 is fixed?

**Comment by jdm** [comment]
Mark them as failed.

**Pull request merged**
