### PR TITLE
Don't use inherited custom properties for substitution

### PR DESCRIPTION
**Pull request by upsuper**
Custom properties from parent node has been considered in early stage of cascading them (in [`custom_properties::cascade`](https://github.com/servo/servo/blob/01adcf69d794b09396ea469a4fe2ca3324ef9306/components/style/custom_properties.rs#L461-L469)), and there is nothing in the spec stating that substitution should take inherited values into consideration when the value is invalid in the current node. Actually, there is a web-platform test explicitly checks that inherited value is not taken when the value is computed to invalid.

This would fix [bug 1402217](https://bugzilla.mozilla.org/show_bug.cgi?id=1402217).

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18660)

### CODE REVIEW

**Comment by upsuper** [comment]
try run: https://treeherder.mozilla.org/#/jobs?repo=try&revision=84cc3712f18a6ef6425663534d472f62672df716

**Comment by upsuper** [comment]
Looks like Servo doesn't have the corresponding wpt.

**Review by emilio — APPROVED** [review]

**Comment by upsuper** [comment]
@emilio thanks for reviewing. I wouldn't be able to land the test expectation change in Gecko side since it has been too late here. Could you help landing a commit in Gecko side to remove `testing/web-platform/meta/css/css-variables-1/variable-substitution-variable-declaration.html.ini` after this lands to autoland?

**Comment by emilio** [comment]
Sure thing, no worries :)

**Comment by emilio** [comment]
@bors-servo r-

Simon had some complaints about this, and he wants to double-check with the test and the spec.

**Comment by SimonSapin** [comment]
I thought the test disagreed with the spec:

```css
--varA: var(--varB);
--varB: var(--varA);
--varC: var(--varB);
```

`--varC` is not part of the cycle, so https://drafts.csswg.org/css-variables/#cycles does not make it compute to its initial (always-invalid) value. However it refers to an invalid variable, so https://drafts.csswg.org/css-variables/#invalid-variables makes it "invalid at computed-value time" which makes it behave is if the value were `unset`, which for custom properties means `inherit`.

And I thought the code being removed was what implemented that behavior, but that’s not the case. Instead, as @upsuper said, inherited values in inserted into the `HashMap` of computed values at the start of cascading custom properties for a given element. When `substitute_block` returns `Err(())` (when a value is invalid at computed value time), returning early is sufficient: the `custom_properties_map.insert(…)` call (which is really "insert or replace") won’t be executed and the value previously in the hashmap, the inherited value, is left there.

All this to say: false alarm, sorry for the delay :)

@bors-servo r=emilio

**Comment by SimonSapin** [comment]
But wait. This code change looks right, but the test for `--varC` in https://github.com/w3c/web-platform-tests/blob/0f1ee41f0a/css/css-variables-1/variable-substitution-variable-declaration.html still looks wrong. That declaration is invalid at computed-value time, so the property should computed to the inherited value…

**Pull request merged**
