### PR TITLE
Clarify servo as parallel browser engine

### PR DESCRIPTION
**Pull request by tirkarthi**
In the repo title it says servo is a "parallel browser engine" whereas readme says its a "parallel browser". It will be helpful to add a more clear title.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8638)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@bors-servo r+

Thanks!

**Comment by jdm** [comment]
@bors-servo: retry
* #8502

**Comment by jdm** [comment]
@bors-servo: retry
* #8502

**Comment by jdm** [comment]
@bors-servo: retry
* #8502

**Comment by jdm** [comment]
@bors-servo: retry
* infra failure

**Pull request merged**
