### PR TITLE
Implement Node.baseURI

### PR DESCRIPTION
**Pull request by kball**
Addresses Issue #1824.  Implements Node.baseURI based on https://www.w3.org/Bugs/Public/show_bug.cgi?id=20976#c32

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6559)

### CODE REVIEW

**Comment by bzbarsky** [comment]
@kball Does that do the right thing if the document contains a `<base>` tag?  Or does Servo not support those yet?

**Comment by Ms2ger** [comment]
`<base>` is #6303

**Comment by Ms2ger** [comment]
Fixes #1824.

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

Looking good; just needs a few tweaks to the test.

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/Node-baseURI.html, line 8 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6559#-JtXowbczLVgZUYhCHwg)** ([raw file](https://github.com/servo/servo/blob/dbbab3b113e24e2e3be4b8556218e44ca5a1db35/tests/wpt/web-platform-tests/dom/nodes/Node-baseURI.html#L8)):</sup>
One space on either side of the equals sign.

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/Node-baseURI.html, line 9 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6559#-JtXoq1qT8R8gzCX2Mlr)** ([raw file](https://github.com/servo/servo/blob/dbbab3b113e24e2e3be4b8556218e44ca5a1db35/tests/wpt/web-platform-tests/dom/nodes/Node-baseURI.html#L9)):</sup>
Please don't use the log element as part of the test.

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/Node-baseURI.html, line 12 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6559#-JtXomzh4fp6WLcNW6Fc)** ([raw file](https://github.com/servo/servo/blob/dbbab3b113e24e2e3be4b8556218e44ca5a1db35/tests/wpt/web-platform-tests/dom/nodes/Node-baseURI.html#L12)):</sup>
Empty line between tests, please.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6559)

**Comment by bzbarsky** [comment]
> `<base>` is #6303

Then it might make sense to have a base URL getter on document that this patch uses and the `<base>` changes affect the behavior of whenever they land, right?

**Comment by Ms2ger** [comment]
That's true, but then again, we'll need to audit a lot more code. @kball, feel free to do this either way.

**Comment by kball** [comment]
I'd prefer to keep this patch minimal and address the base changes in a separate issue.  I'll happily tackle that issue as well, but since I'm brand new to rust+servo and my time for this work is likely to be pretty up and down, bite sized chunks seem indicated.

@Ms2ger review comments addressed.

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6559)

**Comment by kball** [comment]
The failure in question appears to be that a test in a different part of the test suite which was previously expected to fail now passes.  My inclination is to simply update the expectation, does that seem reasonable?

**Comment by kball** [comment]
Update to that expectation pushed up

**Pull request merged**
