### PR TITLE
Remove SslProvider, fixes #7627

### LINKED ISSUE #7627: Remove SslProvider wrapper
This was needed back when we supported running Servo without SSL, but that is no longer supported. We can remove this whole type and just use the Openssl type directly.

Code: components/net/http_loader.rs

### PR DESCRIPTION
**Pull request by aidanhs**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7633)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for the PR!

**Comment by aidanhs** [comment]
Are there no integration-style tests for this kind of change?

**Comment by jdm** [comment]
For this change in particular, I can't think of any meaningful test beyond whether it compiles. There's no reason it should affect whether we can load HTTPS sites, but that would be an integration test I suppose.

**Comment by aidanhs** [comment]
```
remoteFailed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
]
```

```
17:16 < jack> crap. i inadvertently recycled buildbot :(
17:17 < jack> sorry whoever's PR i just failed
```

:(

**Pull request merged**
