### PR TITLE
Add an assertion to get_root_pipeline_and_containing_parent.

### PR DESCRIPTION
**Pull request by Ms2ger**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy --faster` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because _____

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11298)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Hmm, this has introduced a source of panic to the constellation. Can we make this assertion in such a way that the user gets an option to submit a crash report?

**Comment by nox** [comment]
@Ms2ger Please reopen this and push immediately afterwards, or just recreate the PR. Homu doesn't want to forget about it.

**Comment by KiChjang** [comment]
Do you mean creating a new commit hash and then force pushing?

**Comment by nox** [comment]
Yes.

**Pull request closed without merging**
