### PR TITLE
Upgrade stylo to 2024-06-24

### PR DESCRIPTION
**Pull request by Loirooriol**
This continues #32474

Changelog:
 - Upstream: https://github.com/servo/stylo/compare/07759020d8574d371bb92bca609c82e669d77566...8a13add71238c8cb0880b857a5db387ae47822c7
 - Servo fixups: https://github.com/servo/stylo/compare/f2fbf5520e9fe1f45d0fe868c3f8e2d100b6d3a8...fafff4ca2cc971acc5278977ee69d6351cfbbaca

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
The layout2013 failures are because we do not run layout 2013 WPT tests by default so results are only updated once a week during WPT imports.

**Comment by nicoburns** [comment]
> The layout 2013 failures are because we do not run layout 2013 WPT tests by default so results are only updated once a week during WPT imports.

Does this mean I don't need to bother updating layout_2013 test results on new PRs?

**Comment by mrobinson** [comment]
> Does this mean I don't need to bother updating layout_2013 test results on new PRs?

Correct.

**Comment by mrobinson** [comment]
Closing in favor of #32812.

**Pull request closed without merging**
