### PR TITLE
Fix GFX Warnings

### LINKED ISSUE #12624: Fix compiler warnings in gfx
```
<quote expansion>:1:12: 1:22 warning: private type in public interface, #[warn(private_in_public)] on by default 
<quote expansion>:1  where Vec<GlyphEntry>: _serde::ser::Serialize,
                               ^~~~~~~~~~
<quote expansion>:1:12: 1:22 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release! 
<quote expansion>:1:12: 1:22 note: for more information, see the explanation for E0446 (`--explain E0446`) 
<quote expansion>:1:12: 1:22 warning: private type in public interface, #[warn(private_in_public)] on by default 
<quote expansion>:1  where Vec<GlyphEntry>: _serde::de::Deserialize,
                               ^~~~~~~~~~
<quote expansion>:1:12: 1:22 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release! 
<quote expansion>:1:12: 1:22 note: for more information, see the explanation for E0446 (`--explain E0446`) 
<quote expansion>:2:1: 2:19 warning: private type in public interface, #[warn(private_in_public)] on by default 
<quote expansion>:2 DetailedGlyphStore: _serde::ser::Serialize, Au: _serde::ser::Serialize,
                    ^~~~~~~~~~~~~~~~~~
<quote expansion>:2:1: 2:19 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release! 
<quote expansion>:2:1: 2:19 note: for more information, see the explanation for E0446 (`--explain E0446`) 
<quote expansion>:2:1: 2:19 warning: private type in public interface, #[warn(private_in_public)] on by default 
<quote expansion>:2 DetailedGlyphStore: _serde::de::Deserialize, Au: _serde::de::Deserialize,
                    ^~~~~~~~~~~~~~~~~~
<quote expansion>:2:1: 2:19 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release! 
<quote expansion>:2:1: 2:19 note: for more information, see the explanation for E0446 (`--explain E0446`) 
```

Code: `components/gfx/text/glyph.rs`

No need for WPT tests for this; if it compiles, it's good for a PR.

### PR DESCRIPTION
**Pull request by Coder206**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12624 (github issue number if applicable).
- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12849)

### CODE REVIEW

**Comment by emilio** [comment]
Hmm... This doesn't seem to fix the warning for me (the actual private type in the interface is GlyphEntry).

**Comment by KiChjang** [comment]
Yes, `GlyphEntry` and `DetailedGlyphStore` should be made public.

**Comment by Coder206** [comment]
@KiChjang @emilio How do I get Servo to show me warnings when doing "./mach build -d"?

**Comment by jdm** [comment]
Modify a file in `gfx` to ensure that the crate gets rebuilt.

**Comment by Coder206** [comment]
@jdm Thanks.

**Comment by Wafflespeanut** [comment]
Can you please squash those commits, btw?

**Comment by Coder206** [comment]
@Wafflespeanut Absolutely!

**Pull request merged**
