### PR TITLE
Update WR (improved double border quality, minor API changes).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16551)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone

**Comment by jdm** [comment]
```
error[E0308]: mismatched types
   --> /Users/servo/buildbot/slave/mac-dev-unit/build/components/gfx/font_cache_thread.rs:352:90
    |
352 |                     (None, Some(native_font)) => webrender_api.add_native_font(font_key, native_font),
    |                                                                                          ^^^^^^^^^^^ expected struct `webrender_traits::NativeFontHandle`, found struct `core_graphics::font::CGFont`
    |
    = note: expected type `webrender_traits::NativeFontHandle`
               found type `core_graphics::font::CGFont`

error: aborting due to previous error
```
Want to pull https://github.com/servo/servo/pull/16512 into this as well?

**Comment by glennw** [comment]
@jdm OK, I've added that commit.

**Comment by jdm** [comment]
```
  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-input-018.htm
```

**Comment by glennw** [comment]
@bors-servo r=jdm
 * Added a new pass as reported above.

**Pull request merged**
