### PR TITLE
Basic pinch zoom handling

### PR DESCRIPTION
**Pull request by mbrubeck**
r? glennw

Basic fix for #20387 and #20109.  Note: Without calling `generate_frame`
when updating Webrender's pinch zoom level, rendering doesn't happen
reliably during/after a pinch zoom gesture.  I'm not sure whether this
is the correct way to fix that or not.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20749)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Updated.

(Along with the FIXME comment, there's also some refactoring we want to do to move some of this logic to the embedder side, but this patch should be enough for testing graphics and layout functionality.)

**Comment by jdm** [comment]
This can be merged once it's rebased.

**Comment by jdm** [comment]
@bors-servo retry
* #20859

**Pull request merged**
