### PR TITLE
layout: Support percentage widths in inline-blocks.

### PR DESCRIPTION
**Pull request by pcwalton**
Improves Twitter.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5993)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/block.rs @ r1
- components/layout/fragment.rs @ r1
- components/layout/inline.rs @ r1
- tests/ref/basic.list @ r1
- tests/ref/percentage_width_inline_block_a.html @ r1
- tests/ref/percentage_width_inline_block_ref.html @ r1

---

<sup>**[tests/ref/percentage_width_inline_block_a.html, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5993#-JpEUFbGKPmMuUdYncDV)** ([raw file](https://github.com/servo/servo/blob/86dc693155c8fbd5ebb8b344daa8d42c1c2853c8/tests/ref/percentage_width_inline_block_a.html#L7)):</sup>
This test seems to be already passing on master. To test this properly I think the inline-block element needs a sibling.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5993)

**Comment by pcwalton** [comment]
Issues addressed. r? @mbrubeck

**Comment by mbrubeck** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/layout/block.rs @ r2
- components/layout/fragment.rs @ r2
- components/layout/inline.rs @ r2
- tests/ref/basic.list @ r2
- tests/ref/percentage_width_inline_block_a.html @ r2
- tests/ref/percentage_width_inline_block_ref.html @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5993)

**Pull request merged**
