### PR TITLE
Avoid accessing global objects from DOM destructors

### LINKED ISSUE #23986: Unregistering from XR's destructor causes panics
Specifically, XR::unregister tries to get the webvr thread handle from the object's global, but Drop can be called during GC when there is no real global object any more. We should perform any unregistration during page teardown instead.

### LINKED ISSUE #25258: Intermittent timeout in CSS paint api tests (called `Option::unwrap()` on a `None` value)
```
  â–¶ TIMEOUT [expected PASS] /css/css-paint-api/parse-input-arguments-001.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ Shutting down the Constellation after generating an output file or exit flag specified
  â”‚ called `Option::unwrap()` on a `None` value (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63/src/libcore/macros/mod.rs:15)
  â”‚ stack backtrace:
  â”‚    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  â”‚    1: core::fmt::write
  â”‚    2: <std::io::stdio::Stdout as std::io::Write>::write_fmt
  â”‚    3: std::io::stdio::_print
  â”‚    4: servo::backtrace::print
  â”‚    5: servo::main::{{closure}}
  â”‚    6: std::panicking::rust_panic_with_hook
  â”‚    7: rust_begin_unwind
  â”‚    8: core::panicking::panic_fmt
  â”‚    9: core::panicking::panic
  â”‚   10: std::thread::local::LocalKey<T>::with
  â”‚   11: <script::dom::worklet::Worklet as core::ops::drop::Drop>::drop
  â”‚   12: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  â”‚   13: __rust_maybe_catch_panic
  â”‚   14: script::dom::bindings::codegen::Bindings::WorkletBinding::WorkletBinding::_finalize
  â”‚   15: _ZN2js2gc5Arena8finalizeI8JSObjectEEmPNS_6FreeOpENS0_9AllocKindEm
  â”‚   16: _ZL19FinalizeTypedArenasI8JSObjectEbPN2js6FreeOpEPPNS1_2gc5ArenaERNS4_15SortedArenaListENS4_9AllocKindERNS1_11SliceBudgetENS4_10ArenaLists14KeepArenasEnumE
  â”‚   17: _ZN2js2gc10ArenaLists18foregroundFinalizeEPNS_6FreeOpENS0_9AllocKindERNS_11SliceBudgetERNS0_15SortedArenaListE
  â”‚   18: _ZN2js2gc9GCRuntime17finalizeAllocKindEPNS_6FreeOpERNS_11SliceBudgetEPN2JS4ZoneENS0_9AllocKindE
  â”‚   19: _ZN11sweepaction18SweepActionForEachI13ContainerIterIN7mozilla7EnumSetIN2js2gc9AllocKindEjEEES7_JPNS5_9GCRuntimeEPNS4_6FreeOpERNS4_11SliceBudgetEPN2JS4ZoneEEE3runESA_SC_SE_SH_
  â”‚   20: _ZN11sweepaction19SweepActionSequenceIJPN2js2gc9GCRuntimeEPNS1_6FreeOpERNS1_11SliceBudgetEPN2JS4ZoneEEE3runES4_S6_S8_SB_
  â”‚   21: _ZN11sweepaction18SweepActionForEachIN2js2gc19SweepGroupZonesIterEP9JSRuntimeJPNS2_9GCRuntimeEPNS1_6FreeOpERNS1_11SliceBudgetEEE3runES7_S9_SB_
  â”‚   22: _ZN11sweepaction19SweepActionSequenceIJPN2js2gc9GCRuntimeEPNS1_6FreeOpERNS1_11SliceBudgetEEE3runES4_S6_S8_
  â”‚   23: _ZN11sweepaction20SweepActionRepeatForIN2js2gc15SweepGroupsIterEP9JSRuntimeJPNS2_9GCRuntimeEPNS1_6FreeOpERNS1_11SliceBudgetEEE3runES7_S9_SB_
  â”‚   24: _ZN2js2gc9GCRuntime19performSweepActionsERNS_11SliceBudgetE
  â”‚   25: _ZN2js2gc9GCRuntime16incrementalSliceERNS_11SliceBudgetEN2JS8GCReasonERNS0_13AutoGCSessionE
  â”‚   26: _ZN2js2gc9GCRuntime7gcCycleEbNS_11SliceBudgetEN2JS8GCReasonE
  â”‚   27: _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetEN2JS8GCReasonE
  â”‚   28: _ZN2js2gc9GCRuntime2gcE18JSGCInvocationKindN2JS8GCReasonE
  â”‚   29: _ZN9JSRuntime14destroyRuntimeEv
  â”‚   30: _ZN2js14DestroyContextEP9JSContext
  â”‚   31: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop
  â”‚   32: _ZN4core3ptr18real_drop_in_place17h7e2ba5dbda7e7435E.llvm.16719392747939577752
  â”‚   33: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  â”‚   34: core::ptr::real_drop_in_place
  â”‚   35: std::sys_common::backtrace::__rust_begin_short_backtrace
  â”‚   36: _ZN3std9panicking3try7do_call17h929e6f7ad0a1aec8E.llvm.1681200393123249568
  â”‚   37: __rust_maybe_catch_panic
  â”‚   38: core::ops::function::FnOnce::call_once{{vtable.shim}}
  â”‚   39: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  â”‚   40: std::sys::unix::thread::Thread::new::thread_start
  â”‚   41: _pthread_body
  â”‚   42: _pthread_start
  â”‚ 
  â”” [2019-12-12T03:29:00Z ERROR servo] called `Option::unwrap()` on a `None` value

```

### PR DESCRIPTION
**Pull request by jdm**
This removes all instances that I could find of DOM objects accessing `self.global()` in code that runs as part of a Drop method. This is unsafe because the GC could destroy objects in any order when doing a big sweep. Instead, these types should store the data they need as members so they can run in isolation without accessing the rest of the GC graph as part of their destructors.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #25258 and fix #23986
- [x] There are tests for these changes

### CODE REVIEW

**Review by asajeffrey — APPROVED** [review]
Ah, good catch! We could do with some way to make sure this doesn't happen again, not that I'm sure what that would be short of passing around something like a Josephine `JSContext`.

**Comment by jdm** [comment]
```
8 unexpected results that are NOT known-intermittents:
  â–¶ TIMEOUT [expected PASS] /css/css-paint-api/parse-input-arguments-016.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”” Shutting down the Constellation after generating an output file or exit flag specified


  â–¶ TIMEOUT [expected PASS] /css/css-paint-api/parse-input-arguments-019.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”” Shutting down the Constellation after generating an output file or exit flag specified


  â–¶ TIMEOUT [expected FAIL] /css/css-paint-api/parse-input-arguments-018.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”” Shutting down the Constellation after generating an output file or exit flag specified


  â–¶ TIMEOUT [expected PASS] /css/css-paint-api/parse-input-arguments-017.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”” Shutting down the Constellation after generating an output file or exit flag specified


  â–¶ TIMEOUT [expected FAIL] /css/css-paint-api/color-custom-property-animation.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ [2019-12-19T23:48:52Z ERROR script::dom::bindings::error] Error at https://web-platform.test:8443/css/css-paint-api/color-custom-property-animation.https.html:39:5 CSS.registerProperty is not a function
  â”” Shutting down the Constellation after generating an output file or exit flag specified


  â–¶ TIMEOUT [expected PASS] /css/css-paint-api/setTransform-002.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”” Shutting down the Constellation after generating an output file or exit flag specified


  â–¶ TIMEOUT [expected PASS] /css/css-paint-api/paint2d-filter.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”” Shutting down the Constellation after generating an output file or exit flag specified


  â–¶ TIMEOUT [expected PASS] /css/css-paint-api/valid-image-after-load.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”” Shutting down the Constellation after generating an output file or exit flag specified


```

**Comment by CYBAI** [comment]
@bors-servo retry

- #24726
- #24762 
- #24622

**Comment by jdm** [comment]
@bors-servo r-
Something isn't working correctly in the worklet code.

**Comment by jdm** [comment]
@bors-servo r=asajeffrey
I've moved the problematic worklet changes into #25838 so we can at least get rid of the other known instances of this problem.

**Pull request merged**
