### PR TITLE
Update WebGPU CTS to main branch

### PR DESCRIPTION
**Pull request by kunalmohan**
`main` branch in https://github.com/gpuweb/cts is closer to our implementation and it makes more sense to use that.

r?@kvark

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by kunalmohan** [comment]
@bors-servo try=wpt-mac

A number of tests have been added/deleted, so we need to check again which ones crash on metal backend only.

**Comment by kunalmohan** [comment]
I am worried about a large number of `TIMEOUT`s that I get, some of which intermittently `PASS/FAIL`.

**Review by kvark — APPROVED** [review]

**Comment by kunalmohan** [comment]
@bors-servo try=wpt-mac

CI should hopefully be happy. Let's check this before approving/merging.

**Comment by kunalmohan** [comment]
There are no unexpected results in the webgpu cts now. The failure comes from an unrelated test (probably intermittent).

@kvark This is ready to merge now.

**Pull request merged**
