### PR TITLE
style: Don't assert when the final rule tree GC happens in script.

### PR DESCRIPTION
**Pull request by emilio**
This should silence the assertions in https://github.com/servo/servo/issues/14213.

r? @Ms2ger

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14278)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo retry
* #13776

**Comment by emilio** [comment]
@bors-servo r=Ms2ger p=1

 * this wasn't in the queue apparently

**Pull request merged**
