### PR TITLE
Implement the constructor for EventSource

### PR DESCRIPTION
**Pull request by KiChjang**
Partial #8925.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13666)

### CODE REVIEW

**Comment by Ms2ger** [comment]
It's not clear to me why we'd want to create a js promise here at all.

**Comment by KiChjang** [comment]
How else would you fetch the request?

**Comment by Ms2ger** [comment]
With all the usual infra, like you did for the script element.

**Comment by KiChjang** [comment]
An EventSource needs to have an associated Request object. I recall @jdm saying that we should store a dom::Request instead of a net_traits::Request, and by doing so, the straightforward way to fetch a dom::Request would be via dom::Fetch. I could instead make a function that transforms this dom::Request into a RequestInit, but if so, I think we're better off storing a RequestInit instead.

**Comment by KiChjang** [comment]
Not sure if there's any value in merging just the EventSource constructor here, since it doesn't make any failing tests pass.

**Comment by Ms2ger** [comment]
Agreed.

**Pull request closed without merging**
