### PR TITLE
Make Attr::prefix an Atom

### PR DESCRIPTION
**Pull request by tamird**
Rebase of https://github.com/Ms2ger/servo/commits/ICE-attr-prefix-atom

Some of the changes weren't necessary since the internals had been refactored some in the interim. In any case, I was unable to reproduce the ICE reported in https://github.com/rust-lang/rust/issues/18957.

@Ms2ger

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5777)

### CODE REVIEW

**Comment by jdm** [comment]
That.. is dedication. Thanks @tamird!

**Comment by tamird** [comment]
@jdm @Ms2ger any interest in this?

**Comment by jdm** [comment]
Yes, I'll make sure it's reviewed by the end of tomorrow.

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/attr.rs @ r2
- components/script/dom/bindings/utils.rs @ r2
- components/script/dom/create.rs @ r3
- components/script/dom/document.rs @ r3
- components/script/dom/element.rs @ r3
- components/script/dom/node.rs @ r3

---

<sup>**[components/script/dom/node.rs, line 1737 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5777#-Jnv2gPoJn133cNtOkzT)** ([raw file](https://github.com/servo/servo/blob/5f78d91d0ebf2970656929a284c0fc46afb58c0b/components/script/dom/node.rs#L1737)):</sup>
Atom::from_slice(&p)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5777)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5777)

**Comment by tamird** [comment]
<sup>**[components/script/dom/node.rs, line 1737 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5777#-Jnv2gPoJn133cNtOkzT)** ([raw file](https://github.com/servo/servo/blob/5f78d91d0ebf2970656929a284c0fc46afb58c0b/components/script/dom/node.rs#L1737)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5777)

**Comment by jdm** [comment]
@bors-servo: r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed files:
- components/script/dom/attr.rs @ r4
- components/script/dom/create.rs @ r4
- components/script/dom/document.rs @ r4
- components/script/dom/element.rs @ r4
- components/script/dom/node.rs @ r4

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5777)

**Pull request merged**
