### PR TITLE
Add a pref to indicate user intent to enter webxr

### PR DESCRIPTION
**Pull request by asajeffrey**
Add a pref to indicate that the user has indicated intent to enter webxr.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it's a command-line pref

### CODE REVIEW

**Comment by asajeffrey** [comment]
This needs thought about a bit, because it's switching off a security feature. It's needed for scenarios where we're launching straight into webxr, for example from the gstreamer plugin, which has no 2d view. With this pref we can enter hubs using
```
./mach run -r "https://hubs.mozilla.com/$ROOM_ID?no_force_webvr&vr_entry_type=vr_now" --pref dom.gamepad.enabled --pref dom.svg.enabled --pref dom.webrtc.enabled --pref dom.canvas_capture.enabled --pref dom.webrtc.transceiver.enabled --pref dom.webxr.user-intent
```

**Comment by asajeffrey** [comment]
@avadacatavra you may have opinions about ^

**Comment by Manishearth** [comment]
Perhaps we should name the pref something scarier? idk. Implementation seems fine by me.

**Comment by asajeffrey** [comment]
Yeah, I tried to think of an appropriate `dom.webxr.you-really-need-to-know-what-youre-doing-here` pref name.

**Comment by Manishearth** [comment]
override_user_intent?

**Comment by Manishearth** [comment]
maybe stick an _unsafe in there

**Comment by asajeffrey** [comment]
`assume_user_intent`?

**Comment by Manishearth** [comment]
Yeah, but unsafe_assume_user_intent

**Comment by asajeffrey** [comment]
We have a winner!

**Comment by asajeffrey** [comment]
Renamed the pref. @Manishearth ok'd setting the pref in the gstreamer plugin at https://chat.mozilla.org/#/room/#servo:mozilla.org/$3DTiFVKWr85K322xn49tTBoMtEOvScTFtqi4o5okyA4

@bors-servo r=Manishearth

**Pull request merged**
