### PR TITLE
Fixed scaling artefacts in paint worklets caused by zoom and hidpi

### LINKED ISSUE #17454: Paint worklets: scaling artefacts with zoom
If you zoom in on a paint worklet, you get scaling artefacts. Chrome doesn't display these.

screenshot from 2017-06-21 11-07-48

### PR DESCRIPTION
**Pull request by asajeffrey**
This PR renders paint worklet canvases at the device pixel resolution, rather than the CSS pixel resolution.

It's a dependent PR, building on #17239, #17326 and #17364.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17454 
- [X] These changes do not require tests because we don't run reftests with zoom enabled

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17499)

### CODE REVIEW

**Comment by jdm** [comment]
```
error: no method named `device_pixel_ratio` found for type `&gecko::media_queries::Device` in the current scope

   --> /home/travis/build/servo/servo/components/style/context.rs:150:31

    |

150 |         self.stylist.device().device_pixel_ratio()

    |                               ^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `style`.
```

**Comment by asajeffrey** [comment]
OK, I added a definition to `style/gecko/media_queries.rs`, but I'm not sure it's the right one...
```rust
    pub fn device_pixel_ratio(&self) -> ScaleFactor<f32, CSSPixel, DevicePixel> {
        let mut dppx = self.pres_context().mOverrideDPPX;
        if dppx <= 0.0 { dppx = 1.0; }
        ScaleFactor::new(dppx)
    }
```
@emilio or @bzbarsky does this look right?

**Comment by bzbarsky** [comment]
No, that's not right.  That's an override value if someone really needs to override the normal value and have the prescontext pretend like the override is what's going on.  The normal value is nsPresContext::AppUnitsPerCSSPixel()/presContext->AppUnitsPerDevPixel() or so.

**Comment by asajeffrey** [comment]
@bzbarsky: thanks!

**Comment by asajeffrey** [comment]
Slightly annoyingly, those functions aren't exported by our Gecko bindings. I think this is equivalent:
```rust
    pub fn device_pixel_ratio(&self) -> ScaleFactor<f32, CSSPixel, DevicePixel> {
        let au_per_dpx = self.pres_context().mCurAppUnitsPerDevPixel as f32;
        let au_per_px = AU_PER_PX as f32;
        ScaleFactor::new(au_per_px / au_per_dpx)
    }
```

**Comment by bzbarsky** [comment]
Yes, that seems reasonable.  But again, mOverrideDPPX overrides if its `> 0`.

**Comment by asajeffrey** [comment]
Good point. Thanks!

**Comment by asajeffrey** [comment]
@glennw This PR's dependencies have been merged, so it's ready for review!

**Comment by jdm** [comment]
```
error[E0432]: unresolved import `script_traits::DevicePixel`

  --> /home/travis/build/servo/servo/ports/glutin/window.rs:27:21

   |

27 | use script_traits::{DevicePixel, LoadData, TouchEventType, TouchpadPressurePhase};

   |                     ^^^^^^^^^^^ no `DevicePixel` in the root

error[E0412]: cannot find type `IpcSender` in this scope

    --> /home/travis/build/servo/servo/ports/glutin/window.rs:1304:60

     |

1304 |     fn allow_navigation(&self, _: ServoUrl, response_chan: IpcSender<bool>) {

     |                                                            ^^^^^^^^^ not found in this scope

     |

help: possible candidate is found in another module, you can import it into scope

     |

36   | use servo::ipc_channel::ipc::IpcSender;

     |

error: aborting due to 2 previous errors

error: Could not compile `glutin_app`.
```

**Comment by glennw** [comment]
@asajeffrey r=me on the changes - it'd be good if we could add a reftest either here or as a follow up though (I'm not sure if the reftest harness allows setting dpi ratio though).

**Comment by asajeffrey** [comment]
Squashed. @bors-servo: r=glennw

**Comment by asajeffrey** [comment]
Got build-cef to compile. @bors-servo r=glennw

**Pull request merged**
