### PR TITLE
Upgrade to rustc 1.18.0-nightly (23de823e9 2017-04-23)

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16579)

### CODE REVIEW

**Comment by jdm** [comment]
I'm surprised that this does not break due to https://github.com/rust-lang/rust/issues/41484.

**Comment by jdm** [comment]
Oh, that's because this doesn't build the tests. Lucky us!

**Comment by SimonSapin** [comment]
@jdm https://github.com/rust-lang/rust/issues/41484 looks like the same as https://github.com/rust-lang/rust/issues/41394, which was fixed in https://github.com/rust-lang/rust/issues/41408. This upgrade includes the fix.

**Pull request merged**
