### PR TITLE
Referer header

### PR DESCRIPTION
**Pull request by rebstar6**
PR1 for https://github.com/servo/servo/issues/10311

This puts the code and data structures in place to set the Referer header based on the Referrer Policy for a given document. Note that document:: get_referrer_policy() always returns the 'No Referrer' option, so for now, this should have no impact on production code, and that policy requires that the Referer header is not added.

Later PRs will determine the policy and edit that get_referrer_policy() accordingly.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10696)

### CODE REVIEW

**Comment by rebstar6** [comment]
@jdm fyi on this PR. Also, merge conflicts, lame. I'll look into addressing.

**Comment by rebstar6** [comment]
Want to point out - LoadData creation with referrer in components/msg/constellation_msg.rs is handled with a new_with_referrer() method. In components/net_traits/lib.rs, I edited the new() method to just add these 2 new fields in.

I assume I should make them consistent, but wanted your opinion on which is better 1st. new_with_referrer means less changes to track down throughout the code, and you don't just have "None, None" thrown on the end most of the time you are creating. Editing new is maybe cleaner though, considering there may be future adds. 

Either way.

**Comment by jdm** [comment]
Yeah, I'd prefer to stay with editing the `new` method for now just to make sure we catch all the right places.

As for these changes, great work! I'm a bit leery of the way we pass around URLs and strings in the main referrer determination algorithm, so I'd like to see what that looks like if we write it more like the specification algorithm and only deal in URLs instead.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 15 files at r1, 12 of 12 files at r2, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[components/msg/constellation_msg.rs, line 420 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkSN1ciLR4w_mio1H5:-KFkSN1ciLR4w_mio1H6:1332937816) ([raw file](https://github.com/servo/servo/blob/9ccdef5fbeafb8b643d4d921643cba08511a6c68/components/msg/constellation_msg.rs#L420)):*
Let's go with `[Policies](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-states) for providing a referrer header for a request`

---

*[components/net/http_loader.rs, line 369 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFitFJhqNSZG8IZ7DGR:-KFitFJiuc8jqjMatdIb:-585052649) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L369)):*
This can accept &Url values. Let's just call `serialize` instead of accepting the serialized form as an argument as well.

---

*[components/net/http_loader.rs, line 370 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFitH69d4fIdBR_FeX1:-KFitH69d4fIdBR_FeX2:677251276) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L370)):*
Yes.

---

*[components/net/http_loader.rs, line 380 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFitpF3dE915ixvGNlr:-KFitpF4TQ3NHmdNVFQQ:-496775834) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L380)):*
That is correct.

---

*[components/net/http_loader.rs, line 381 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkRHN4jlIhvu_hfw78:-KFkRHN4jlIhvu_hfw79:-537926617) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L381)):*
We should be relying on the `Url::origin` method here instead.

---

*[components/net/http_loader.rs, line 388 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFitwWVbTzOgzYrWDXL:-KFitwWWfyiCDXtgJKtY:-605726735) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L388)):*
`mut referrer_url` instead of creating `ref_mutable` below.

---

*[components/net/http_loader.rs, line 391 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFjz8T5suJMbtIFaEoh:-KFjz8T5suJMbtIFaEoi:-1198438569) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L391)):*
`relative.path.truncate()`

---

*[components/net/http_loader.rs, line 398 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFiuIG1BiSJ_Zk5Kg5k:-KFiuIG29MToMi6UhuXE:1984836861) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L398)):*
`mut referrer_url: Url`
Also, `nonorigin` in the name is unclear. I assume this is referring to the `origin-only` flag specified in the original algorithm? I'd prefer to implement the algorithm from the specification as written (ie. as single method that accepts a boolean argument), since it's much easier to reason about the results in the caller than comparing the implementation of `generate_nonorigin_referer_url` to `generate_origin_referer_url` and the specification.

---

*[components/net/http_loader.rs, line 401 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFiuOGSM1YaCHohbU-W:-KFiuOGSM1YaCHohbU-X:940059113) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L401)):*
No need for this.

---

*[components/net/http_loader.rs, line 413 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFk7W9RlqMjfF2Ojl9v:-KFk7W9SBFFJgBU8o3g6:2026311694) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L413)):*
Let's have this return an `Option<Url>` instead of modifying the header directly. Then we could call this `determine_request_referrer` and have it more clearly match the specification algorithm.

---

*[components/net/http_loader.rs, line 416 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFiu88haOm2Kyh7PbX6:-KFiu88haOm2Kyh7PbX7:241633816) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L416)):*
We should be able to assert that this is false instead.

---

*[components/net/http_loader.rs, line 427 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFk6flH3oU3CR8PHW6x:-KFk6flH3oU3CR8PHW6y:-1044200656) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L427)):*
Let's use explicit patterns here instead of the catch-all `_`.

---

*[components/net/http_loader.rs, line 412 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkT5TZmYP1RgQojQfQ:-KFkT5TZmYP1RgQojQfR:1539127475) ([raw file](https://github.com/servo/servo/blob/9ccdef5fbeafb8b643d4d921643cba08511a6c68/components/net/http_loader.rs#L412)):*
The proper way to support step 2 and related bits about redirections isn't totally clear to me right now. Let's add some TODO comments to call that out and deal with it later.

---

*[components/net_traits/lib.rs, line 90 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkJMkSuL0eSmvx6vh0:-KFkJMkT_4YMrUN7dPb4:160828367) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net_traits/lib.rs#L90)):*
I'd go with `/// The policy and referring URL for the originator of this request`

---

*[components/script/script_thread.rs, line 1886 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkK_JJuEqXXZe2Q_mn:-KFkK_JKobYke4A11-Rc:-270294599) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/script/script_thread.rs#L1886)):*
Is this still relevant?

---

*[components/script/dom/document.rs, line 229 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkN7kMjp1HGtT1mJHW:-KFkN7kMjp1HGtT1mJHX:448842446) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/script/dom/document.rs#L229)):*
Let's make this link https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-states

---

*[components/script/dom/document.rs, line 1689 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkNIH0rFEfwmId5dEH:-KFkNIH1oqrMq09vvXTd:1086600057) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/script/dom/document.rs#L1689)):*
Let's initialize this to NoReferrer.

---

*[components/script/dom/document.rs, line 1821 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkNKtA2JxxtxIYuiAA:-KFkNKtA2JxxtxIYuiAB:690005522) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/script/dom/document.rs#L1821)):*
Let's make this return `self.referrer_policy`

---

*[components/script/dom/xmlhttprequest.rs, line 585 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkNXzlLa5l7servB3t:-KFkNXzmYcuCAHZ4SNwf:-1656478121) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/script/dom/xmlhttprequest.rs#L585)):*
For future reference, we'll want to add an API to GlobalRef that returns a ReferrerPolicy value; we can use global.get_url() for the other I believe.

---

*[tests/unit/net/http_loader.rs, line 1461 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkOE6eM3_yXSsPtJoh:-KFkOE6eM3_yXSsPtJoi:176050673) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/tests/unit/net/http_loader.rs#L1461)):*
The explicit type after `load` isn't necessary any more.

---

*[tests/unit/net/http_loader.rs, line 1470 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkPHTNwQQ_0zmjkpXR:-KFkPHTNwQQ_0zmjkpXS:85947151) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/tests/unit/net/http_loader.rs#L1470)):*
Since these tests have so much code in common, let's merge them like so:
```rust
fn assert_referer_header_matches(request_url: &str, referrer_url: &str, referrer_policy: Option<ReferrerPolicy>, expected_referrer: &str) {
    // set up the URLs, create the LoadData, set the header value, call load
}
```
Then we can either have a bunch of different #[test] functions that all delegate to that one, or just one that contains a bunch of tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10696#-:-KFkSYKqjS8qSBBu6pO1:-645414325)*

**Comment by rebstar6** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[components/msg/constellation_msg.rs, line 420 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkSN1ciLR4w_mio1H5:-KFqGcOy3-8DzAniXoUJ:-499146009) ([raw file](https://github.com/servo/servo/blob/9ccdef5fbeafb8b643d4d921643cba08511a6c68/components/msg/constellation_msg.rs#L420)):*
Done.

---

*[components/net/http_loader.rs, line 369 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFitFJhqNSZG8IZ7DGR:-KFqPGbVmO8QR81A0Phy:-499146009) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L369)):*
Done.

---

*[components/net/http_loader.rs, line 381 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkRHN4jlIhvu_hfw78:-KFqPIUSkaRBJRkBpNJr:-499146009) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L381)):*
Done.

---

*[components/net/http_loader.rs, line 391 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFjz8T5suJMbtIFaEoh:-KFqPLMdMkdFI_Begsh2:-499146009) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L391)):*
Done.

---

*[components/net/http_loader.rs, line 398 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFiuIG1BiSJ_Zk5Kg5k:-KFqPP6GmcP22a7UU6i3:-499146009) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L398)):*
Done.

---

*[components/net/http_loader.rs, line 416 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFiu88haOm2Kyh7PbX6:-KFqR9GBdH1FDI6-rULQ:-800801879) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L416)):*
No explicit method for it - this is how the other headers are handled fyi.

---

*[components/net/http_loader.rs, line 427 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFk6flH3oU3CR8PHW6x:-KFqRHhy32gqXEEUQhvn:-499146009) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L427)):*
Done.

---

*[components/net/http_loader.rs, line 412 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkT5TZmYP1RgQojQfQ:-KFqPTvc_vjpkcVCeUXF:-499146009) ([raw file](https://github.com/servo/servo/blob/9ccdef5fbeafb8b643d4d921643cba08511a6c68/components/net/http_loader.rs#L412)):*
Done.

---

*[components/script/script_thread.rs, line 1886 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkK_JJuEqXXZe2Q_mn:-KFqRR_7HNAPjlMJg9Fy:-460356205) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/script/script_thread.rs#L1886)):*
nope.

---

*[components/script/dom/document.rs, line 229 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkN7kMjp1HGtT1mJHW:-KFqRbXLGpzW6Z3Wl0Gx:-499146009) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/script/dom/document.rs#L229)):*
Done.

---

*[components/script/dom/document.rs, line 1689 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFkNIH0rFEfwmId5dEH:-KFqRsQBJxt3gc09mfA5:-499146009) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/script/dom/document.rs#L1689)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10696)*

**Comment by rebstar6** [comment]
FYI - code comments addressed. Test changes are still a todo, as is the newest merge conflict (grr).

**Comment by jdm** [comment]
Only minor stuff left. Great work!
-S-awaiting-review -S-needs-tests +S-needs-code-changes 

---

Reviewed 12 of 14 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[components/net/http_loader.rs, line 416 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFiu88haOm2Kyh7PbX6:-KFuIigLdB-vmowgg7Ci:-663436033) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L416)):*
I mean `assert!(!headers.has::<Referer>());`

---

*[components/net/http_loader.rs, line 373 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFuIKNGkum3psLtQOxK:-KFuIKNHJDwCUMzzHfgj:1486172968) ([raw file](https://github.com/servo/servo/blob/3f3b6a6cb6b835c99452f33fd02370583f8e6e95/components/net/http_loader.rs#L373)):*
Let's call this `strip_url`, too.

---

*[components/net/http_loader.rs, line 399 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFuIuc6_HdW9pAhVooF:-KFuIuc7ZIbnmE2HNokK:43423704) ([raw file](https://github.com/servo/servo/blob/3f3b6a6cb6b835c99452f33fd02370583f8e6e95/components/net/http_loader.rs#L399)):*
The scheme is already compared as part of the origin checks.

---

*[components/net/http_loader.rs, line 406 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFuJ6R4UPXt3dORHaoi:-KFuJ6R4UPXt3dORHaoj:1017623877) ([raw file](https://github.com/servo/servo/blob/3f3b6a6cb6b835c99452f33fd02370583f8e6e95/components/net/http_loader.rs#L406)):*
We can combine these branches with `Some(ReferrerPolicy::NoRefWhenDowngrade) | None =>`

---

*[components/net/http_loader.rs, line 408 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFuJC6Bg2Pl6Wnbhvyd:-KFuJC6Bg2Pl6Wnbhvye:-465183419) ([raw file](https://github.com/servo/servo/blob/3f3b6a6cb6b835c99452f33fd02370583f8e6e95/components/net/http_loader.rs#L408)):*
Code like `let foo = ...; return foo` is equivalent to `return ...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10696#-:-KFuK3EClyC6xLzMFg8V:1790785980)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 6 of 6 files at r8.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[components/compositing/constellation.rs, line 1016 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFufwVh_JgARkNB47J7:-KFufwVirBs0k0xRiILl:-970406787) ([raw file](https://github.com/servo/servo/blob/a7a01c00a2a53b26d5583872f8f63d8eff5dc287/components/compositing/constellation.rs#L1016)):*
Hmm, this is one where we're going to want the policy and URL of the document that's being navigated inside of an iframe. It'll be part of the IFrameLoadInfo structure; a TODO here would be ok.

---

*[components/script/dom/htmlformelement.rs, line 287 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFugNWwxBsGQ2vSl0ti:-KFugNWxFxl1c55mQnyP:1064840330) ([raw file](https://github.com/servo/servo/blob/a7a01c00a2a53b26d5583872f8f63d8eff5dc287/components/script/dom/htmlformelement.rs#L287)):*
We'll want real values here too for the current document.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10696#-:-KFugXe0Ien02iqk5eEv:1458266033)*

**Comment by rebstar6** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[components/compositing/constellation.rs, line 1016 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFufwVh_JgARkNB47J7:-KG9S4qfhaDCrXT4FIlq:-499146009) ([raw file](https://github.com/servo/servo/blob/a7a01c00a2a53b26d5583872f8f63d8eff5dc287/components/compositing/constellation.rs#L1016)):*
Done.

---

*[components/net/http_loader.rs, line 416 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFiu88haOm2Kyh7PbX6:-KG9Shho-9RJzF8cCfbb:-427129034) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L416)):*
that throws an error though, right? is it possible this would be called with something that already has a referer header (thinking redirects here, which we're not sure about anyway)

---

*[components/net/http_loader.rs, line 373 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFuIKNGkum3psLtQOxK:-KG9SEo9PZyXYJrlNILT:-499146009) ([raw file](https://github.com/servo/servo/blob/3f3b6a6cb6b835c99452f33fd02370583f8e6e95/components/net/http_loader.rs#L373)):*
Done.

---

*[components/net/http_loader.rs, line 399 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFuIuc6_HdW9pAhVooF:-KG9VcDIlLEbHpESBKqb:522784413) ([raw file](https://github.com/servo/servo/blob/3f3b6a6cb6b835c99452f33fd02370583f8e6e95/components/net/http_loader.rs#L399)):*
weird, for some reason i thought that was giving me an error before, but seems fine now. must have been something else - done!

---

*[components/net/http_loader.rs, line 406 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFuJ6R4UPXt3dORHaoi:-KG9Vp3wFxQE7jTYvZNo:-499146009) ([raw file](https://github.com/servo/servo/blob/3f3b6a6cb6b835c99452f33fd02370583f8e6e95/components/net/http_loader.rs#L406)):*
Done.

---

*[components/net/http_loader.rs, line 408 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFuJC6Bg2Pl6Wnbhvyd:-KG9Vt22Gflky_IW2kcO:-499146009) ([raw file](https://github.com/servo/servo/blob/3f3b6a6cb6b835c99452f33fd02370583f8e6e95/components/net/http_loader.rs#L408)):*
Done.

---

*[components/script/dom/htmlformelement.rs, line 287 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFugNWwxBsGQ2vSl0ti:-KG9X15XABoY86dQFwQm:1744648711) ([raw file](https://github.com/servo/servo/blob/a7a01c00a2a53b26d5583872f8f63d8eff5dc287/components/script/dom/htmlformelement.rs#L287)):*
Doc was pulled out earlier - hopefully it's the right document :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10696)*

**Comment by rebstar6** [comment]
Please re-review the strip_url method after the latest commit - looks like rust-url was updated, so that method is changed.

Latest commit has that change and all comments to this point addressed.

**Comment by jdm** [comment]
Looking great!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 11 of 15 files at r9, 4 of 4 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/net/http_loader.rs, line 416 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFiu88haOm2Kyh7PbX6:-KGCirmTcXx7bjLrBwpB:-632926127) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L416)):*
Any headers object we pass in here should not already have a Referer header; APIs like XMLHttpRequest/Fetch forbid setting it, and other browser code shouldn't be setting it either. We don't carry over headers that were set by the browser prior to a redirect, either.

---

*[components/net/http_loader.rs, line 369 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10696#-KGCiWx33dE1Lu3SkOte:-KGCiWx33dE1Lu3SkOtf:-56191016) ([raw file](https://github.com/servo/servo/blob/bc1cc597fa4c76b282c9ea9b8609e4e008e3369c/components/net/http_loader.rs#L369)):*
Add `.unwrap()` to each of the lines that complains about unused results. These operations shouldn't fail, and we'll want to know if they do, so unwrap is the right thing here..

---

*[tests/unit/net/http_loader.rs, line 1565 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10696#-KGCruGdDmo7uHX2JB5e:-KGCruGepsOnmoE0E5Hm:-1625576980) ([raw file](https://github.com/servo/servo/blob/bc1cc597fa4c76b282c9ea9b8609e4e008e3369c/tests/unit/net/http_loader.rs#L1565)):*
Shouldn't this be https?

---

*[tests/unit/net/http_loader.rs, line 1575 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10696#-KGCkAwqWf4R4cIrtrrx:-KGCkAwqWf4R4cIrtrry:-426581070) ([raw file](https://github.com/servo/servo/blob/bc1cc597fa4c76b282c9ea9b8609e4e008e3369c/tests/unit/net/http_loader.rs#L1575)):*
The test is called http_to_http...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10696#-:-KGCsAVacrhf3tEdP0Y9:-453788606)*

**Comment by rebstar6** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/net/http_loader.rs, line 416 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10696#-KFiu88haOm2Kyh7PbX6:-KGDbFqe15cVNSEeu0zD:-499146009) ([raw file](https://github.com/servo/servo/blob/1460ccf910389faeef693be0cb7699c4b8ed3809/components/net/http_loader.rs#L416)):*
Done.

---

*[components/net/http_loader.rs, line 369 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10696#-KGCiWx33dE1Lu3SkOte:-KGDdCrxcx1vW2vsA8qO:-499146009) ([raw file](https://github.com/servo/servo/blob/bc1cc597fa4c76b282c9ea9b8609e4e008e3369c/components/net/http_loader.rs#L369)):*
Done.

---

*[tests/unit/net/http_loader.rs, line 1565 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10696#-KGCruGdDmo7uHX2JB5e:-KGDbAsncAVA6oD9udGO:476461063) ([raw file](https://github.com/servo/servo/blob/bc1cc597fa4c76b282c9ea9b8609e4e008e3369c/tests/unit/net/http_loader.rs#L1565)):*
Oops, flipped these two. 

---

*[tests/unit/net/http_loader.rs, line 1575 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10696#-KGCkAwqWf4R4cIrtrrx:-KGDbESbK6iePs70ZR4a:-499146009) ([raw file](https://github.com/servo/servo/blob/bc1cc597fa4c76b282c9ea9b8609e4e008e3369c/tests/unit/net/http_loader.rs#L1575)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10696)*

**Comment by jdm** [comment]
A+ would review again. Go ahead and squash the commits into one!
-S-awaiting-review +S-needs-squash 

---

Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10696#-:-KGDeLQKKArjg1bmWF8-:949969841)*

**Pull request merged**
