### PR TITLE
Remove usage of phf_macros.

### PR DESCRIPTION
**Pull request by SimonSapin**
It’s a compiler plugin that uses unstable compiler APIs that are not on a path to stabilization.

With this changes, there is one less thing that might break when we update the compiler. For example: https://github.com/sfackler/rust-phf/pull/101

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15099)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Reading a generated file and them modifying it in place is a bit tricky. I’d rather have the Python codegen emit the map’s entries in a separate file (maybe JSON) and have the Rust build script read that and generate a new file, but I don’t know how to do that while keeping cmake’s dependency tracking happy.

**Comment by nox** [comment]
@SimonSapin Just make CMake generate the JSON file and then use Rust to read it in build.rs?

**Comment by SimonSapin** [comment]
r? @jdm

I’ve modified this per your advice on IRC.

**Pull request merged**
