### PR TITLE
Run same tests for layout-2020 and layout-2013

### PR DESCRIPTION
**Pull request by Loirooriol**
Most tests were only being run for layout-2013, not for layout-2020. This wasn't great since layout-2020 is now the default.

So this patch unifies the lists of included tests for both layouts. For layout-2013 this implies adding css/css-content/, css/css-logical/ and css/css-masking/clip/.
For layout-2020 this implies adding several additional css tests, and also tests like dom/, js/, html/, etc.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because there is no change in behavior

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]
Looks good to me once results are updated. Thank you!

**Comment by Loirooriol** [comment]
I will also add this in order to let webgl tests have different expectations for 2013 and 2020:

```diff
diff --git a/python/wpt/__init__.py b/python/wpt/__init__.py
index c80c7491f..9adb69d6a 100644
--- a/python/wpt/__init__.py
+++ b/python/wpt/__init__.py
@@ -60,6 +60,9 @@ def update_args_for_legacy_layout(kwargs: dict):
         kwargs["test_paths"]["/_mozilla/"]["metadata_path"] = os.path.join(
             WPT_PATH, "mozilla", "meta-legacy-layout"
         )
+        kwargs["test_paths"]["/_webgl/"]["metadata_path"] = os.path.join(
+            WPT_PATH, "webgl", "meta-legacy-layout"
+        )
 
 
 def run_tests():
```

**Pull request merged**
