### PR TITLE
Use a BTreeMap for Document::animation_frame_list (fixes #9834)

### LINKED ISSUE #9834: Concurrent rAF loops are not deterministic
```html
<script>
  var i = 0;
  
  var loopA = t => {
    console.log("A: " + t);
    
    if (i++ < 5) {
      requestAnimationFrame(loopA);
    }
  };
  
  var loopB = t => {
    console.log("B: " + t);    
    if (i < 5) {
      requestAnimationFrame(loopB);
    }
  };

  loopA();
  loopB();
</script>
```

Chrome and Firefox:
```
====
A
B
A
B
A
B
A
B
A
B
A
```

Servo:

```
====
A
B
B
A
B
A
A
B
A
B
A
```

### PR DESCRIPTION
**Pull request by nox**
The callbacks must stay ordered.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9837)

### CODE REVIEW

**Comment by mbrubeck** [comment]
r=mbrubeck with some minor changes

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/document.rs, line 1257 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9837#-KBrvjO7NNMZ621va8bM:-KBrvjO89uSpGVUMF5HU:-604407182) ([raw file](https://github.com/servo/servo/blob/9b874416443d98910e08d5de87e1059bb7b99103/components/script/dom/document.rs#L1257)):*
Nit: `.into_iter()` isn't needed here.

---

*[components/script/dom/bindings/trace.rs, line 242 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9837#-KBrvxWGYiRRBnRMBr6b:-KBrvxWHpnLrDjbAR77_:-1945320285) ([raw file](https://github.com/servo/servo/blob/9b874416443d98910e08d5de87e1059bb7b99103/components/script/dom/bindings/trace.rs#L242)):*
Nit: `&*` isn't needed here.  Looks like the same is true for the HashMap impl above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9837#-:-KBrwPdIDPwi6bWUrt7i:504143933)*

**Comment by nox** [comment]
@bors-servo r=mbrubeck

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/document.rs, line 1257 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9837#-KBrvjO7NNMZ621va8bM:-KBs0AB6-3NxanqlWrD0:-499146009) ([raw file](https://github.com/servo/servo/blob/9b874416443d98910e08d5de87e1059bb7b99103/components/script/dom/document.rs#L1257)):*
Done.

---

*[components/script/dom/bindings/trace.rs, line 242 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9837#-KBrvxWGYiRRBnRMBr6b:-KBs0KzWJfHk6Hb7BRXX:-499146009) ([raw file](https://github.com/servo/servo/blob/9b874416443d98910e08d5de87e1059bb7b99103/components/script/dom/bindings/trace.rs#L242)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9837#-:-KBs15mKA_fSn1Ug17WH:436296857)*

**Comment by nox** [comment]
What.

**Comment by nox** [comment]
Had forgotten to push.

@bors-servo r=mbrubeck

**Pull request merged**
