### PR TITLE
Implement onsubmit and onfocusin event handlers

### LINKED ISSUE #5396: Implement GlobalEventHandlers.onsubmit
From the jQuery test suite initialization:
```
	// Support: IE<9 (lack submit/change bubble), Firefox 17+ (lack focusin event)
	// Beware of CSP restrictions (https://developer.mozilla.org/en/Security/CSP), test/csp.php
	for ( i in { submit: true, change: true, focusin: true }) {
		div.setAttribute( eventName = "on" + i, "t" );

		support[ i + "Bubbles" ] = eventName in window || div.attributes[ eventName ].expando === false;
	}
```

```
ERROR:js::rust: Error at http://localhost:8888/test/data/jquery-1.9.1.js:1446: TypeError: div.attributes[eventName] is undefined
```

Needed for #5395.

### PR DESCRIPTION
**Pull request by pikzen**
fixes #5396 

jquery test suite is still broken with the following errors:

```
ERROR:js::rust: Error at http://localhost:8000/test/jquery.js:6: TypeError: window.location.pathname is undefined

ERROR:js::rust: Error at http://localhost:8000/test/data/testrunner.js:11: TypeError: jQuery is undefined
```

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed on critic

**Comment by pikzen** [comment]
Ah, I knew I was missing tests references. Added them. The commits are visible on github, though I have no idea how to force critic to display them here too.

Please tell me if you want to rebase the multiple commits into one.

**Comment by metajack** [comment]
Assigned @Ms2ger since he did the review.

**Comment by Ms2ger** [comment]
Rebased as https://github.com/servo/servo/pull/5475. Thanks a lot!

**Pull request closed without merging**
