### PR TITLE
Use incumbent settings object's origin in Window.postMessage

### LINKED ISSUE #12715: Use incumbent settings object for Window::postMessage.
Depends on #10963.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #12715.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15291)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Should be <https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-origin>, not the origin of `get_url()`, which doesn't have a well-defined meaning AFAICT.

Definitions are here:
* https://html.spec.whatwg.org/multipage/browsers.html#script-settings-for-browsing-contexts
* https://html.spec.whatwg.org/multipage/workers.html#script-settings-for-workers

Can we find a way to test this?

**Comment by KiChjang** [comment]
I expect this to pass some WPT tests; let's see if that's true.

@bors-servo try

**Comment by KiChjang** [comment]
Also, stepping through the code, get_url() seems to return the url that is defined by the window's document object, if the global is a window, not sure for the worker's case.

**Comment by Ms2ger** [comment]
Note that a document's origin is not the origin of it's url, necessarily.

**Comment by nox** [comment]
We only have cross-origin window proxies right? So this change isn't observable, is it?

**Comment by Ms2ger** [comment]
Yeah, we should probably wait for @avadacatavra's XOW work.

**Comment by nox** [comment]
@asajeffrey said on IRC he is going to work on cross-origin proxies without waiting for XOWs. I'm confused about that.

**Comment by Ms2ger** [comment]
He's working on cross-reference thread coordination; similar-but-not-same-origin windows are sufficient here.

**Comment by KiChjang** [comment]
In which case, it sounds like this change isn't desirable at this stage.

**Pull request closed without merging**
