### PR TITLE
Update XRWebGLLayer to match specification.

### LINKED ISSUE #27312: XRWebGLLayer IDL members don't match the specification
Spec: https://immersive-web.github.io/webxr/#xrwebgllayer
```
[SecureContext, Exposed=Window]
interface XRWebGLLayer: XRLayer {
  constructor(XRSession session,
             XRWebGLRenderingContext context,
             optional XRWebGLLayerInit layerInit = {});
  // Attributes
  readonly attribute boolean antialias;
  readonly attribute boolean ignoreDepthValues;

  [SameObject] readonly attribute WebGLFramebuffer? framebuffer;
  readonly attribute unsigned long framebufferWidth;
  readonly attribute unsigned long framebufferHeight;

  // Methods
  XRViewport? getViewport(XRView view);

  // Static Methods
  static double getNativeFramebufferScaleFactor(XRSession session);
};
```

XRWebGLLayer.webidl:
```
[SecureContext, Exposed=Window, Pref="dom.webxr.enabled"]
interface XRWebGLLayer {
  [Throws] constructor(XRSession session,
              XRWebGLRenderingContext context,
              optional XRWebGLLayerInit layerInit = {});
  // // Attributes
  readonly attribute XRWebGLRenderingContext context;

  readonly attribute boolean antialias;
  readonly attribute boolean depth;
  readonly attribute boolean stencil;
  readonly attribute boolean alpha;

  readonly attribute WebGLFramebuffer? framebuffer;
  readonly attribute unsigned long framebufferWidth;
  readonly attribute unsigned long framebufferHeight;

  // // Methods
  XRViewport? getViewport(XRView view);
  // void requestViewportScaling(double viewportScaleFactor);

  // // Static Methods
  // static double getNativeFramebufferScaleFactor(XRSession session);
};
```
This is breaking WPT webxr tests, because they try to set the `context` property on the layer and it's readonly.

### PR DESCRIPTION
**Pull request by jdm**
This unbreaks most of the webxr WPT tests.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #27312
- [x] There are tests for these changes

### CODE REVIEW

**Review by asajeffrey — APPROVED** [review]
OK, you win the award for the ratio of size of change to number of newly-passing tests.

**Comment by jdm** [comment]
```
  ▶ ERROR [expected TIMEOUT] /webxr/dom-overlay/ar_dom_overlay.https.html
  │   → input_source.setOverlayPointerPosition is not a function
  │ 
  └ testInput/</<@https://web-platform.test:8443/webxr/dom-overlay/ar_dom_overlay.https.html:142:20
  ▶ Unexpected subtest result in /webxr/dom-overlay/ar_dom_overlay.https.html:
  │ TIMEOUT [expected FAIL] Ensures DOM Overlay input deduplication works
  └   → Test timed out
  ▶ Unexpected subtest result in /webxr/dom-overlay/ar_dom_overlay.https.html:
  └ NOTRUN [expected FAIL] Ensures DOM Overlay Fullscreen API doesn't change DOM overlay
  ▶ Unexpected subtest result in /webxr/dom-overlay/ar_dom_overlay.https.html:
  └ NOTRUN [expected FAIL] Ensures DOM Overlay interactions on cross origin iframe are ignored

  ▶ ERROR [expected TIMEOUT] /webxr/hit-test/ar_hittest_subscription_transientInputSources.https.html
  │   → session.requestHitTestSourceForTransientInput is not a function
  │ 
  └ testFunction/</</<@https://web-platform.test:8443/webxr/hit-test/ar_hittest_subscription_transientInputSources.https.html:70:17
  ▶ Unexpected subtest result in /webxr/hit-test/ar_hittest_subscription_transientInputSources.https.html:
  │ TIMEOUT [expected FAIL] Ensures subscription to transient hit test works with an XRSpace from input source - no move
  └   → Test timed out
  ▶ Unexpected subtest result in /webxr/hit-test/ar_hittest_subscription_transientInputSources.https.html:
  └ NOTRUN [expected FAIL] Ensures subscription to transient hit test works with an XRSpace from input source - after move - no results
  ▶ Unexpected subtest result in /webxr/hit-test/ar_hittest_subscription_transientInputSources.https.html:
  └ NOTRUN [expected FAIL] Ensures subscription to transient hit test works with an XRSpace from input source - after move - 1 result

  ▶ Unexpected subtest result in /webxr/xrSession_cancelAnimationFrame_invalidhandle.https.html:
  │ TIMEOUT [expected FAIL] XRSession cancelAnimationFrame does not have unexpected behavior when given invalid handles on immersive testSession
  └   → Test timed out
  ▶ Unexpected subtest result in /webxr/xrSession_cancelAnimationFrame_invalidhandle.https.html:
  └ NOTRUN [expected FAIL] XRSession cancelAnimationFrame does not have unexpected behavior when given invalid handles on non-immersive testSession
  ▶ Unexpected subtest result in /webxr/xrDevice_disconnect_ends.https.html:
  │ TIMEOUT [expected FAIL] Immersive session ends when device is disconnected
  └   → Test timed out
```

**Comment by jdm** [comment]
@bors-servo retry
* #25513

**Comment by jdm** [comment]
@bors-servo retry
* #25513

**Pull request merged**
