### PR TITLE
Cleanup constellation after nll

### PR DESCRIPTION
**Pull request by cbrewster**
This cleans up a couple cases where we had to add extra scopes to appease the borrowck, now that nll has landed, this cleans these up.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because cleanup

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22376)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thanks for cleaning this up!

**Comment by CYBAI** [comment]
@bors-servo retry

- #21893

**Comment by CYBAI** [comment]
@bors-servo retry

- #22271

**Comment by CYBAI** [comment]
hmm.. it keeps `TIMEOUT` on `servo-mac8` on various of tests 🤔

**Pull request merged**
