### PR TITLE
Move tinyfiledialog call from script to embedder

### LINKED ISSUE #23057: Remove use of tinyfiledialogs from script code
This is very similar to https://github.com/servo/servo/issues/20428 and https://github.com/servo/servo/issues/20429. Right now the DOM permissions code directly invokes the tinyfiledialogs library to create a permission UI. Instead, we should be sending a message to the embedder and making the embedding layer create the UI.

Code: `components/script/dom/permissions.rs`, `components/embedder_traits/lib.rs`, `ports/servo/browser.rs`, `ports/libsimpleservo/api/src/lib.rs`

### PR DESCRIPTION
**Pull request by iulianR**
PR is based on work started in #23651. I rebased on top of master and addressed review comments. Handling the `PromptPermission` message in `libsimpleservo` is probably not ideal. Looking forward to make more changes, just let me know how I should proceed.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23057 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by jdm** [comment]
While we could certainly add a member to HostTrait like `fn permission_prompt(prompt: PermissionPrompt) -> PermissionRequest`, and then add implementations in:
* https://github.com/servo/servo/blob/504437938a675dc8f31449bf15801daf44a22118/ports/libmlservo/src/lib.rs#L358
* https://github.com/servo/servo/blob/504437938a675dc8f31449bf15801daf44a22118/ports/libsimpleservo/jniapi/src/lib.rs#L383
* https://github.com/servo/servo/blob/b5b9732509bb66a2427be7848d9b21bc5357a4b7/ports/libsimpleservo/capi/src/lib.rs#L722

I don't actually see a reason to do that work until we have a need to have a different per-embedding behaviour for the permission prompt. I'm happy with the current implementation for now!

@bors-servo r+

**Comment by jdm** [comment]
These changes now cause us to run more of the permissions API tests to completion!
```
  ▶ OK [expected CRASH] /permissions/idlharness.any.worker.html
  ▶ Unexpected subtest result in /permissions/idlharness.any.worker.html:
  │ FAIL [expected PASS] Permissions interface: calling query(object) on navigator.permissions with too few arguments must throw TypeError
  │   → assert_unreached: Throws "TypeError: Not enough arguments to "Permissions.query"." instead of rejecting promise Reached unreachable code
  │ 
  │ throwOrReject/<@http://web-platform.test:8000/resources/idlharness.js:116:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1926:25
  │ throwOrReject@http://web-platform.test:8000/resources/idlharness.js:115:20
  │ IdlInterface.prototype.test_interface_of/<@http://web-platform.test:8000/resources/idlharness.js:2958:21
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1926:25
  │ IdlInterface.prototype.test_interface_of@http://web-platform.test:8000/resources/idlharness.js:2933:20
  │ IdlInterface.prototype.test_object@http://web-platform.test:8000/resources/idlharness.js:2767:27
  │ IdlArray.prototype.test/<@http://web-platform.test:8000/resources/idlharness.js:917:36
  │ IdlArray.prototype.test@http://web-platform.test:8000/resources/idlharness.js:912:21
  └ idl_test/</<@http://web-platform.test:8000/resources/idlharness.js:3440:31
  ▶ Unexpected subtest result in /permissions/idlharness.any.worker.html:
  │ FAIL [expected PASS] Permissions interface: operation query(object)
  │   → assert_unreached: Throws "TypeError: "this" object does not implement interface Permissions." instead of rejecting promise Reached unreachable code
  │ 
  │ throwOrReject/<@http://web-platform.test:8000/resources/idlharness.js:116:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1926:25
  │ throwOrReject@http://web-platform.test:8000/resources/idlharness.js:115:20
  │ IdlInterface.prototype.do_member_operation_asserts@http://web-platform.test:8000/resources/idlharness.js:2542:13
  │ IdlInterface.prototype.test_member_operation/<@http://web-platform.test:8000/resources/idlharness.js:2462:14
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1926:25
  │ IdlInterface.prototype.test_member_operation@http://web-platform.test:8000/resources/idlharness.js:2410:12
  │ IdlInterface.prototype.test_members@http://web-platform.test:8000/resources/idlharness.js:2720:26
  │ IdlInterface.prototype.test@http://web-platform.test:8000/resources/idlharness.js:1580:10
  │ IdlArray.prototype.test@http://web-platform.test:8000/resources/idlharness.js:905:28
  └ idl_test/</<@http://web-platform.test:8000/resources/idlharness.js:3440:31
```
You will need to update https://github.com/servo/servo/blob/master/tests/wpt/metadata/permissions/idlharness.any.js.ini to remove the CRASH line, and duplicate [these lines](https://github.com/servo/servo/blob/master/tests/wpt/metadata/permissions/idlharness.any.js.ini#L4-L9) but with the header `idlharness.any.worker.html` instead. Running `./mach test-wpt tests/wpt/web-platform-tests/permissions` will verify that it's working as expected.

**Comment by iulianR** [comment]
With these changes, `./mach test-wpt tests/wpt/web-platform-tests/permissions` reports no errors. I can squash my commits if you'd like.

**Comment by jdm** [comment]
I'm fine with the current set of commits!
@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #25875

**Pull request merged**
