### PR TITLE
M1453: Review for ConsoleApiCall and Console::Log

### PR DESCRIPTION
**Pull request by srm09**
Do not merge.!

### CODE REVIEW

**Comment by jdm** [comment]
@muchhalsagar88 This is very close! The changes to ConsoleAPICall aren't quite right, though - I specifically highlighted the `message` field as requiring changes (it needs to be a separate object containing the new fields); the other fields need to be left unchanged.

**Comment by muchhalsagar88** [comment]
Oops!! Totally misunderstood the comment. Hope this solves it.

**Comment by jdm** [comment]
Nice! This will need to be rebased, but we should probably wait to do that until after we're finished upgrading the Rust compiler that Servo uses, since there will be a bunch of conflicts.

**Comment by muchhalsagar88** [comment]
@jdm I can see that Rust version has been upgraded to 1.0.0
Can I proceed with the rebase??

**Comment by jdm** [comment]
Yes please :)

**Comment by jdm** [comment]
Rebased in #4853.

**Pull request closed without merging**
