### PR TITLE
Bug 1354970 - Add @counter-style rules

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16455)

### CODE REVIEW

**Comment by upsuper** [comment]
IIRC, I'm supposed to review this pr? Assigning myself in case I forgot.

r? @upsuper

**Comment by nox** [comment]
@SimonSapin AFAICT you can squash "Fix up unit tests" with the `CustomIdent` commits.

**Comment by upsuper** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/counter_style.rs, line 25 at r19](https://reviewable.io:443/reviews/servo/servo/16455#-KiEBcuvvc1w8C29x_0n:-KiEBcuwM_rV7AQ86LB-:b-jc26hc) ([raw file](https://github.com/servo/servo/blob/10ba98247eec41b8460eda7ca4e619ed17766d2c/components/style/counter_style.rs#L25)):*
> ```Rust
> /// Parse the prelude of an @counter-style rule
> pub fn parse_counter_style_name(input: &mut Parser) -> Result<CustomIdent, ()> {
>     CustomIdent::from_ident(input.expect_ident()?, &["decimal", "none"])
> ```

This is wrong, actually. `<counter-style-name>` is `<custom-ident>` but it is lower-cased if it is a predefined counter style in the Counter Styles Level 3 spec. See the paragraph below the note in https://drafts.csswg.org/css-counter-styles/#typedef-counter-style-name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16455)*

**Comment by upsuper** [comment]
(I comment that first because I suppose that may or may not affect the first commit in your patchset)

**Comment by SimonSapin** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/counter_style/mod.rs, line 25 at r19](https://reviewable.io:443/reviews/servo/servo/16455#-KiEBcuvvc1w8C29x_0n:-KiUALxRf9WEYu44729E:b-2wxnv4) ([raw file](https://github.com/servo/servo/blob/10ba98247eec41b8460eda7ca4e619ed17766d2c/components/style/counter_style/mod.rs#L25)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This is wrong, actually. `<counter-style-name>` is `<custom-ident>` but it is lower-cased if it is a predefined counter style in the Counter Styles Level 3 spec. See the paragraph below the note in https://drafts.csswg.org/css-counter-styles/#typedef-counter-style-name
</blockquote></details>

Fixed, and filed https://github.com/w3c/csswg-drafts/issues/1285.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16455)*

**Comment by upsuper** [comment]
Reviewed 1 of 2 files at r1, 18 of 19 files at r20, 8 of 8 files at r21, 3 of 3 files at r22, 3 of 3 files at r23, 1 of 1 files at r24, 5 of 6 files at r25, 3 of 4 files at r26, 2 of 3 files at r27, 1 of 2 files at r28, 2 of 3 files at r29, 2 of 3 files at r30, 3 of 4 files at r31, 2 of 3 files at r32, 1 of 2 files at r33, 2 of 3 files at r34, 2 of 3 files at r35, 2 of 3 files at r36, 1 of 2 files at r37, 2 of 3 files at r38, 2 of 2 files at r39, 2 of 2 files at r40, 3 of 3 files at r41.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[Cargo.lock, line 284 at r40](https://reviewable.io:443/reviews/servo/servo/16455#-KiVTtpQ1REgGMoJQ1pS:-KiVTtpQ1REgGMoJQ1pT:bc9oodc) ([raw file](https://github.com/servo/servo/blob/42ff479f6b11e08b20590d603aa254513deb25fc/Cargo.lock#L284)):*
> ```
>  "azure 0.15.0 (git+https://github.com/servo/rust-azure)",
>  "canvas_traits 0.0.1",
>  "cssparser 0.12.4 (registry+https://github.com/rust-lang/crates.io-index)",
> ```

Please update a Cargo.toml at the same time, otherwise Stylo build wouldn't get the update automatically.

---

*[components/script/dom/csskeyframesrule.rs, line 118 at r21](https://reviewable.io:443/reviews/servo/servo/16455#-KiUCblKgZlMYMU3OGJ3:-KiUCblKgZlMYMU3OGJ4:b-5t2pkx) ([raw file](https://github.com/servo/servo/blob/893525b515bf7a2aebe6a06dc315f9097a6376fa/components/script/dom/csskeyframesrule.rs#L118)):*
> ```Rust
>         // Setting this property to a CSS-wide keyword or `none` will
>         // throw a Syntax Error.
>         let name = CustomIdent::from_ident(value.into(), &["none"]).map_err(|()| Error::Syntax)?;
> ```

This is actually wrong. The name in keyframes rule can accept a string in CSS, thus it can accept arbitrary string. I think that also means there shouldn't be any check for CSSOM at all. But I guess that is probably a separate issue.

---

*[components/style/stylesheets.rs, line 531 at r21](https://reviewable.io:443/reviews/servo/servo/16455#-KiUDFTcHJj9rtXo7NF-:-KiUDFTcHJj9rtXo7NF0:b-u8s2up) ([raw file](https://github.com/servo/servo/blob/893525b515bf7a2aebe6a06dc315f9097a6376fa/components/style/stylesheets.rs#L531)):*
> ```Rust
> pub struct KeyframesRule {
>     /// The name of the current animation.
>     pub name: CustomIdent,
> ```

Given that the name can be an arbitrary, it probably shouldn't be stored as a `CustomIdent`.

---

*[components/style/stylesheets.rs, line 940 at r21](https://reviewable.io:443/reviews/servo/servo/16455#-KiUDfsK41iJdm2dAL4f:-KiUDfsLGGNP7Y078H2q:bs4q9op) ([raw file](https://github.com/servo/servo/blob/893525b515bf7a2aebe6a06dc315f9097a6376fa/components/style/stylesheets.rs#L940)):*
> ```Rust
>     Viewport,
>     /// A @keyframes rule, with its animation name and vendor prefix if exists.
>     Keyframes(CustomIdent, Option<VendorPrefix>),
> ```

Ditto.

---

*[components/style/stylesheets.rs, line 1142 at r21](https://reviewable.io:443/reviews/servo/servo/16455#-KiUDkZ5YZb-SdCrEKt0:-KiUDkZ5YZb-SdCrEKt1:b-8d8al8) ([raw file](https://github.com/servo/servo/blob/893525b515bf7a2aebe6a06dc315f9097a6376fa/components/style/stylesheets.rs#L1142)):*
> ```Rust
>                 let name = match input.next() {
>                     Ok(Token::Ident(value)) => CustomIdent::from_ident(value, &["none"])?,
>                     Ok(Token::QuotedString(value)) => CustomIdent(Atom::from(value)),
> ```

This is weird. Strings like `"initial"` is not really a valid custom ident. We probably need a new function in cssparser to serialize customident-or-string.

---

*[components/style/counter_style/update_predefined.py, line 11 at r41](https://reviewable.io:443/reviews/servo/servo/16455#-KiVW_jKInTS5px-80ln:-KiVW_jKInTS5px-80lo:bjb14ae) ([raw file](https://github.com/servo/servo/blob/1861809909292f06a790ca27803bfce7f8031894/components/style/counter_style/update_predefined.py#L11)):*
> ```Python
>         re.search(">([^>]+)</dfn>", line).group(1)
>         for line in urllib.urlopen("https://drafts.csswg.org/css-counter-styles/")
>         if 'data-dfn-for="<counter-style-name>"' in line
> ```

You missed Japanese and Chinese counter style types. This is probably an editorial issue of the spec, though, that they are using `data-dfn-for="<counter-style>"` rather than `data-dfn-for="<counter-style-name>"`.

---

*[components/style/counter_style/update_predefined.py, line 17 at r41](https://reviewable.io:443/reviews/servo/servo/16455#-KiVWM7c-tnRzNmlxnnA:-KiVWM7dfeDiX9EpyzT7:bmcf1i8) ([raw file](https://github.com/servo/servo/blob/1861809909292f06a790ca27803bfce7f8031894/components/style/counter_style/update_predefined.py#L17)):*
> ```Python
>         for name in names:
>             # FIXME https://github.com/w3c/csswg-drafts/issues/1285
>             if name == 'decimal':
> ```

This is probably wrong. You should include `decimal` and probably also `none` here, otherwise things like `list-style-type: DeCiMaL` may not work as expected.

---

*[components/style/properties/properties.mako.rs, line 845 at r40](https://reviewable.io:443/reviews/servo/servo/16455#-KiVUPlQ0FD89NK-Z6kc:-KiVUPlR8Pd5g59IRS8V:b-bt92fm) ([raw file](https://github.com/servo/servo/blob/42ff479f6b11e08b20590d603aa254513deb25fc/components/style/properties/properties.mako.rs#L845)):*
> ```Rust
>         // FIXME(https://github.com/rust-lang/rust/issues/33156): remove this enum and use PropertyId
>         // when stable Rust allows destructors in statics.
>         pub enum StaticId {
> ```

This change seems to be unrelated.

---

*[components/style/counter_style.rs, line 20 at r26](https://reviewable.io:443/reviews/servo/servo/16455#-KiVZLgtxOfODRqZXWH6:-KiVZLgtxOfODRqZXWH7:b1a4w2b) ([raw file](https://github.com/servo/servo/blob/2a3ffd2416da92439fd93f0f6ea8d5dfd6bdb605/components/style/counter_style.rs#L20)):*
> ```Rust
> /// Parse the prelude of an @counter-style rule
> pub fn parse_counter_style_name(input: &mut Parser) -> Result<CustomIdent, ()> {
>     CustomIdent::from_ident(input.expect_ident()?, &["decimal", "none"])
> ```

This is wrong. Nothing stops one from extending `decimal` at all. `fallback` (in a future commit) should accept `decimal` as well. The same applies to other usages of counter style name elsewhere, e.g. `list-style-type`, `counter()`.

---

*[components/style/counter_style.rs, line 192 at r26](https://reviewable.io:443/reviews/servo/servo/16455#-KiUGSDuykny_LCdyifl:-KiUGSDvDwVEUqOjM_oo:b-per4yc) ([raw file](https://github.com/servo/servo/blob/2a3ffd2416da92439fd93f0f6ea8d5dfd6bdb605/components/style/counter_style.rs#L192)):*
> ```Rust
>             }
>             System::Extends(ref other) => {
>                 dest.write_str("symbolic ")?;
> ```

`"extends "`

---

*[components/style/counter_style.rs, line 155 at r31](https://reviewable.io:443/reviews/servo/servo/16455#-KiUNGvuLOyp-JMq6p8e:-KiUNGvuLOyp-JMq6p8f:b2msdv1) ([raw file](https://github.com/servo/servo/blob/0ff21a5821e75b6d12524110e63fe0b0049fa73d/components/style/counter_style.rs#L155)):*
> ```Rust
>     /// https://drafts.csswg.org/css-counter-styles/#counter-style-fallback
>     "fallback" fallback / eCSSCounterDesc_Fallback: Fallback =
>         Fallback(CustomIdent(Atom::from("decimal")));
> ```

Probably add a `FIXME` here for adding an atom for `decimal`.

---

*[components/style/counter_style.rs, line 239 at r32](https://reviewable.io:443/reviews/servo/servo/16455#-KiUOF-NpQL1RtnJekHd:-KiUOF-NpQL1RtnJekHe:b-6halgf) ([raw file](https://github.com/servo/servo/blob/8035c5540c920823547025007d1a3fe9ac507da7/components/style/counter_style.rs#L239)):*
> ```Rust
> }
> 
> impl OneOrMoreCommaSeparated for Symbol {}
> ```

It doesn't seem to me that `<symbol>` is ever used in comma separated list? I don't think this is necessary.

---

*[components/style/counter_style.rs, line 465 at r35](https://reviewable.io:443/reviews/servo/servo/16455#-KiUQtsi-5wJ9xTyEonc:-KiUQtsi-5wJ9xTyEond:bt2j3v3) ([raw file](https://github.com/servo/servo/blob/e2ab1b4c0104fe26ddcea6271af0b1a59b06e5e3/components/style/counter_style.rs#L465)):*
> ```Rust
> /// https://drafts.csswg.org/css-counter-styles/#descdef-counter-style-additive-symbols
> #[derive(Debug, Clone)]
> pub struct AdditiveSymbol {
> ```

It is called "additive tuple" in the spec. Probably this struct should be `AdditiveTuple` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16455)*

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[Cargo.lock, line 284 at r40](https://reviewable.io:443/reviews/servo/servo/16455#-KiVTtpQ1REgGMoJQ1pS:-KiYaB_J-W3foSZBScaN:b5y0l2l) ([raw file](https://github.com/servo/servo/blob/42ff479f6b11e08b20590d603aa254513deb25fc/Cargo.lock#L284)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Please update a Cargo.toml at the same time, otherwise Stylo build wouldn't get the update automatically.
</blockquote></details>

This will be moot when rebasing on top of #16589, though I’m holding off the rebase for now to make navigation in Reviewable easier. (I should have done the same for yesterday’s rebase but forgot.)

---

*[components/script/dom/csskeyframesrule.rs, line 118 at r21](https://reviewable.io:443/reviews/servo/servo/16455#-KiUCblKgZlMYMU3OGJ3:-KiX2vv_78qtkcP2pPjc:b-lx4fjp) ([raw file](https://github.com/servo/servo/blob/893525b515bf7a2aebe6a06dc315f9097a6376fa/components/script/dom/csskeyframesrule.rs#L118)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This is actually wrong. The name in keyframes rule can accept a string in CSS, thus it can accept arbitrary string. I think that also means there shouldn't be any check for CSSOM at all. But I guess that is probably a separate issue.
</blockquote></details>

Fixed.

---

*[components/style/stylesheets.rs, line 531 at r21](https://reviewable.io:443/reviews/servo/servo/16455#-KiUDFTcHJj9rtXo7NF-:-KiX38s7aJhdAVaG5y7I:b3g18fi) ([raw file](https://github.com/servo/servo/blob/893525b515bf7a2aebe6a06dc315f9097a6376fa/components/style/stylesheets.rs#L531)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Given that the name can be an arbitrary, it probably shouldn't be stored as a `CustomIdent`.
</blockquote></details>

Added a dedicated KeyframesName type, for `<keyframes-name>` in the spec.

---

*[components/style/stylesheets.rs, line 940 at r21](https://reviewable.io:443/reviews/servo/servo/16455#-KiUDfsK41iJdm2dAL4f:-KiYyE-4K0jnJ6xW-fB3:brlflaq) ([raw file](https://github.com/servo/servo/blob/893525b515bf7a2aebe6a06dc315f9097a6376fa/components/style/stylesheets.rs#L940)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Changed to `KeyframesName`.

---

*[components/style/stylesheets.rs, line 1142 at r21](https://reviewable.io:443/reviews/servo/servo/16455#-KiUDkZ5YZb-SdCrEKt0:-KiYyMvUyHV7SlVSd7Gq:b-uohoyh) ([raw file](https://github.com/servo/servo/blob/893525b515bf7a2aebe6a06dc315f9097a6376fa/components/style/stylesheets.rs#L1142)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This is weird. Strings like `"initial"` is not really a valid custom ident. We probably need a new function in cssparser to serialize customident-or-string.
</blockquote></details>

Fixed with `KeyframesName`.

---

*[components/style/counter_style/mod.rs, line 20 at r26](https://reviewable.io:443/reviews/servo/servo/16455#-KiVZLgtxOfODRqZXWH6:-KiZ0G7D7WUlMORrRSGq:b-eahw46) ([raw file](https://github.com/servo/servo/blob/2a3ffd2416da92439fd93f0f6ea8d5dfd6bdb605/components/style/counter_style/mod.rs#L20)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This is wrong. Nothing stops one from extending `decimal` at all. `fallback` (in a future commit) should accept `decimal` as well. The same applies to other usages of counter style name elsewhere, e.g. `list-style-type`, `counter()`.
</blockquote></details>

Changed `parse_counter_style_name` to allow `decimal` and `none` (the former lower-cased) and `@counter-style` parsing to exclude them.

---

*[components/style/counter_style/mod.rs, line 192 at r26](https://reviewable.io:443/reviews/servo/servo/16455#-KiUGSDuykny_LCdyifl:-KiZHvdhmaDEQRWnhsTH:bt2vr1b) ([raw file](https://github.com/servo/servo/blob/2a3ffd2416da92439fd93f0f6ea8d5dfd6bdb605/components/style/counter_style/mod.rs#L192)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

`"extends "`
</blockquote></details>

Fixed.

---

*[components/style/counter_style/mod.rs, line 155 at r31](https://reviewable.io:443/reviews/servo/servo/16455#-KiUNGvuLOyp-JMq6p8e:-KiX3rxUFxk7Kx_MGhMp:byewplo) ([raw file](https://github.com/servo/servo/blob/0ff21a5821e75b6d12524110e63fe0b0049fa73d/components/style/counter_style/mod.rs#L155)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Probably add a `FIXME` here for adding an atom for `decimal`.
</blockquote></details>

Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1359323 and added a FIXME linking to it.

---

*[components/style/counter_style/mod.rs, line 239 at r32](https://reviewable.io:443/reviews/servo/servo/16455#-KiUOF-NpQL1RtnJekHd:-KiZI6kb5uXZliA3S707:b-pawsh4) ([raw file](https://github.com/servo/servo/blob/8035c5540c920823547025007d1a3fe9ac507da7/components/style/counter_style/mod.rs#L239)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

It doesn't seem to me that `<symbol>` is ever used in comma separated list? I don't think this is necessary.
</blockquote></details>

Left over from before I realized `symbols` does not use commas. Removed.

---

*[components/style/counter_style/mod.rs, line 465 at r35](https://reviewable.io:443/reviews/servo/servo/16455#-KiUQtsi-5wJ9xTyEonc:-KiZIb_hUpheX5ZhxW1h:b-896fix) ([raw file](https://github.com/servo/servo/blob/e2ab1b4c0104fe26ddcea6271af0b1a59b06e5e3/components/style/counter_style/mod.rs#L465)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

It is called "additive tuple" in the spec. Probably this struct should be `AdditiveTuple` instead?
</blockquote></details>

Done.

---

*[components/style/counter_style/update_predefined.py, line 11 at r41](https://reviewable.io:443/reviews/servo/servo/16455#-KiVW_jKInTS5px-80ln:-KiZJPG2N6xg1GfwPmRG:bt2vr1b) ([raw file](https://github.com/servo/servo/blob/1861809909292f06a790ca27803bfce7f8031894/components/style/counter_style/update_predefined.py#L11)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

You missed Japanese and Chinese counter style types. This is probably an editorial issue of the spec, though, that they are using `data-dfn-for="<counter-style>"` rather than `data-dfn-for="<counter-style-name>"`.
</blockquote></details>

Fixed.

---

*[components/style/counter_style/update_predefined.py, line 17 at r41](https://reviewable.io:443/reviews/servo/servo/16455#-KiVWM7c-tnRzNmlxnnA:-KiX4ceECeterkvuFQvc:b-3i586s) ([raw file](https://github.com/servo/servo/blob/1861809909292f06a790ca27803bfce7f8031894/components/style/counter_style/update_predefined.py#L17)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This is probably wrong. You should include `decimal` and probably also `none` here, otherwise things like `list-style-type: DeCiMaL` may not work as expected.
</blockquote></details>

Ok for `decimal`, but why `none`? `list-style-type: none` will be parsed explicitly, not through this code.

---

*[components/style/properties/properties.mako.rs, line 845 at r40](https://reviewable.io:443/reviews/servo/servo/16455#-KiVUPlQ0FD89NK-Z6kc:-KiX4lIAcj2jH4U3znMx:bnqyfxe) ([raw file](https://github.com/servo/servo/blob/42ff479f6b11e08b20590d603aa254513deb25fc/components/style/properties/properties.mako.rs#L845)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This change seems to be unrelated.
</blockquote></details>

It is due to the cssparser update. The split into multiple commits is significant :)

This fixes a "private in public" warning caused by `ascii_case_insensitive_phf_map!` now generating a public function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16455)*

**Comment by upsuper** [comment]
Reviewed 1 of 2 files at r39, 2 of 2 files at r42, 13 of 13 files at r43, 7 of 7 files at r44, 1 of 1 files at r45, 1 of 1 files at r46, 1 of 1 files at r47, 2 of 2 files at r48.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/style/stylesheets.rs, line 1137 at r44](https://reviewable.io:443/reviews/servo/servo/16455#-KibveeIl0bQDsSTtu-T:-KibveeIl0bQDsSTtu-U:bwa5w03) ([raw file](https://github.com/servo/servo/blob/6e0112b60cc542afeef1aa633cdca7ffba5cf48b/components/style/stylesheets.rs#L1137)):*
> ```Rust
>                 // https://bugzilla.mozilla.org/show_bug.cgi?id=1359323
>                 if name.0.eq_str_ignore_ascii_case("decimal") ||
>                     name.0.eq_str_ignore_ascii_case("none") {
> ```

This shouldn't be needed. `parse_counter_style_name` should return a lower-cased atom for `decimal` and `none`, so it makes no sense to do case-insensitive compare here.

---

*[components/style/counter_style/update_predefined.py, line 17 at r41](https://reviewable.io:443/reviews/servo/servo/16455#-KiVWM7c-tnRzNmlxnnA:-KibxjKble6NfPHHaxnv:b-r85wqy) ([raw file](https://github.com/servo/servo/blob/1861809909292f06a790ca27803bfce7f8031894/components/style/counter_style/update_predefined.py#L17)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Ok for `decimal`, but why `none`? `list-style-type: none` will be parsed explicitly, not through this code.
</blockquote></details>

`none` seems to be a valid `<counter-style-name>` per spec (since it's a valid `<custom-ident>`. It is just not usable anywhere. Also making `parse_counter_style_name` return `none` in lower-cased atom should simplify code in its callsites.

---

*[components/style/values/mod.rs, line 243 at r43](https://reviewable.io:443/reviews/servo/servo/16455#-Kibs1CKOKpJmWthe_ie:-Kibs1CLPxw6Bthc6xT9:b-y03cw0) ([raw file](https://github.com/servo/servo/blob/4a2e81beb3f9386b7b83f971e3102163f6ea3888/components/style/values/mod.rs#L243)):*
You probably need to impl `PartialEq` manually to compare between `Ident` and `QuotedString`. An keyframes rule named `x` is same as one called `"x"`.

The spec says:
> A @keyframes block has a name given by the <custom-ident> or <string> in its prelude. The two syntaxes are equivalent in functionality; the name is the value of the ident or string. 

https://drafts.csswg.org/css-animations-1/#keyframes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16455)*

**Comment by SimonSapin** [comment]
Review status: 24 of 26 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/style/stylesheets.rs, line 1137 at r44](https://reviewable.io:443/reviews/servo/servo/16455#-KibveeIl0bQDsSTtu-T:-KicDcD_E2AgyFKwmw1G:b-ue1chn) ([raw file](https://github.com/servo/servo/blob/6e0112b60cc542afeef1aa633cdca7ffba5cf48b/components/style/stylesheets.rs#L1137)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This shouldn't be needed. `parse_counter_style_name` should return a lower-cased atom for `decimal` and `none`, so it makes no sense to do case-insensitive compare here.
</blockquote></details>

For `decimal` yes (done), but `nOnE` is not a predefined style and so shouldn’t be lower-cased.

---

*[components/style/counter_style/update_predefined.py, line 17 at r41](https://reviewable.io:443/reviews/servo/servo/16455#-KiVWM7c-tnRzNmlxnnA:-KicDlTxJz0S1kYzyV0v:b-47rjdh) ([raw file](https://github.com/servo/servo/blob/1861809909292f06a790ca27803bfce7f8031894/components/style/counter_style/update_predefined.py#L17)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

`none` seems to be a valid `<counter-style-name>` per spec (since it's a valid `<custom-ident>`. It is just not usable anywhere. Also making `parse_counter_style_name` return `none` in lower-cased atom should simplify code in its callsites.
</blockquote></details>

It’s valid but not a predefined style. This file only deals with predefined.

---

*[components/style/values/mod.rs, line 243 at r43](https://reviewable.io:443/reviews/servo/servo/16455#-Kibs1CKOKpJmWthe_ie:-KicFyuKllvWDSUHZeBZ:buetzhi) ([raw file](https://github.com/servo/servo/blob/4a2e81beb3f9386b7b83f971e3102163f6ea3888/components/style/values/mod.rs#L243)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

You probably need to impl `PartialEq` manually to compare between `Ident` and `QuotedString`. An keyframes rule named `x` is same as one called `"x"`.

The spec says:
> A @keyframes block has a name given by the <custom-ident> or <string> in its prelude. The two syntaxes are equivalent in functionality; the name is the value of the ident or string. 

https://drafts.csswg.org/css-animations-1/#keyframes
</blockquote></details>

Good point. I’ve change the `PartialEq` and `Hash` impls to us `.as_atom()`. (Though I think these impls might only be used in unit tests?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16455)*

**Comment by upsuper** [comment]
Reviewed 1 of 2 files at r39, 1 of 1 files at r49, 1 of 1 files at r50, 2 of 2 files at r51.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/values/mod.rs, line 243 at r43](https://reviewable.io:443/reviews/servo/servo/16455#-Kibs1CKOKpJmWthe_ie:-KicNcRIidchBbY995D8:bq7jv0w) ([raw file](https://github.com/servo/servo/blob/4a2e81beb3f9386b7b83f971e3102163f6ea3888/components/style/values/mod.rs#L243)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Good point. I’ve change the `PartialEq` and `Hash` impls to us `.as_atom()`. (Though I think these impls might only be used in unit tests?)
</blockquote></details>

LGTM. I think we need them for animation code as well, no? How should we locate the keyframes rule for a given animation-name if we don't use eq and hash?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16455)*

**Comment by upsuper** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16455#-:-KicOqdFDrYUuSUFBSAH:bnfp4nl)*

**Comment by upsuper** [comment]
I suppose you may want to rebase and squash some of the commits.

@bors-servo delegate+

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/values/mod.rs, line 243 at r43](https://reviewable.io:443/reviews/servo/servo/16455#-Kibs1CKOKpJmWthe_ie:-KicSORP-HXivPG5Mz-T:b92pr27) ([raw file](https://github.com/servo/servo/blob/4a2e81beb3f9386b7b83f971e3102163f6ea3888/components/style/values/mod.rs#L243)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

LGTM. I think we need them for animation code as well, no? How should we locate the keyframes rule for a given animation-name if we don't use eq and hash?
</blockquote></details>

`Stylist::add_stylesheet()` uses `keyframes_rule.name.as_atom()` and the `Stylist::animations` hashmap is still keyed on `Atom`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16455)*

**Comment by SimonSapin** [comment]
@bors-servo r=upsuper

Included https://github.com/w3c/web-platform-tests/pull/5695.

**Comment by SimonSapin** [comment]
Manifest update.

@bors-servo r=upsuper

**Comment by SimonSapin** [comment]
Failed to push…

@bors-servo r=upsuper

**Pull request merged**
