### PR TITLE
Fix some char/byte bugs in textinput

### LINKED ISSUE #9569: TextInput::replace_selection confuses chars and bytes.
```rust
            let last_char_to_insert = min(allowed_to_insert_count, insert.chars().count());
            let chars_to_insert = (&insert[0 .. last_char_to_insert]).to_owned();
```

`insert.chars().count()` returns a number of `char`s, while the slicing syntax expects a number of bytes.

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes #9569. r? @SimonSapin or @Ms2ger

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10350)

### CODE REVIEW

**Comment by SimonSapin** [comment]
The HTML spec for [the `maxlength` attribute](https://html.spec.whatwg.org/multipage/forms.html#attr-fe-maxlength) links to [code-unit length](https://html.spec.whatwg.org/multipage/infrastructure.html#code-unit-length). `maxlen` is counted neither in bytes nor in `char`/code points but in UTF-16 code units. So `(c: char) <= '\u{FFFF}'` count as 1 while other `char`s count as 2 each.

**Comment by mbrubeck** [comment]
> 

The HTML spec for the maxlength attribute links to code-unit length. maxlen is counted neither in bytes nor in char/code points but in UTF-16 code units. So (c: char) <= '\u{FFFF}' count as 1 while other chars count as 2 each.

Ugh.

**Comment by mbrubeck** [comment]
Fixed to use UTF-16 code units for max_length.

**Comment by SimonSapin** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/textinput.rs, line 214 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10350#-KEL94HdbrGiELW5Bvb_:-KEL94Heyt0VE5_6Pu-s:-1111497955) ([raw file](https://github.com/servo/servo/blob/f121a5b68a7a1d5b1bcc7b917c65fbfb6100650f/components/script/textinput.rs#L214)):*
Nit: this would do slightly less work: `slice.chars().map(char::len_utf16).sum()`

---

*[components/script/textinput.rs, line 333 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10350#-KELBCjJzEZD8bqC8mmZ:-KELBCjK9LxmG6AUxcjh:-862747012) ([raw file](https://github.com/servo/servo/blob/f121a5b68a7a1d5b1bcc7b917c65fbfb6100650f/components/script/textinput.rs#L333)):*
With `col` as it is defined above, isn’t this line a no-op? I read it as "Set `.index` to the UTF-8 len corresponding to the number of code points in the first `.index` UTF-8 bytes of the line", which simplifies to "Set `.index` to itself".

---

*[components/script/textinput.rs, line 533 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10350#-KELC2eBvwq9p4_UNX7n:-KELC2eCZL5CfxhG2VIY:1593583863) ([raw file](https://github.com/servo/servo/blob/f121a5b68a7a1d5b1bcc7b917c65fbfb6100650f/components/script/textinput.rs#L533)):*
Nit: this would do slightly less work: `l.chars().map(char::len_utf16).sum()`

---

*[tests/unit/script/textinput.rs, line 138 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10350#-KELD8YIIh1rwy30n9DP:-KELD8YJltfIcuGGI9ZJ:620859917) ([raw file](https://github.com/servo/servo/blob/f121a5b68a7a1d5b1bcc7b917c65fbfb6100650f/tests/unit/script/textinput.rs#L138)):*
Maybe add a test case where `maxlen` falls in the "middle" of a non-BMP code point?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10350)*

**Comment by mbrubeck** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/textinput.rs, line 214 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10350#-KEL94HdbrGiELW5Bvb_:-KEMLFufe0NvePYQ2VdD:-499146009) ([raw file](https://github.com/servo/servo/blob/f121a5b68a7a1d5b1bcc7b917c65fbfb6100650f/components/script/textinput.rs#L214)):*
Done.

---

*[components/script/textinput.rs, line 333 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10350#-KELBCjJzEZD8bqC8mmZ:-KEMLT5XmfcVRW6PB6_e:-2055029320) ([raw file](https://github.com/servo/servo/blob/f121a5b68a7a1d5b1bcc7b917c65fbfb6100650f/components/script/textinput.rs#L333)):*
No, because `self.edit_point.line` has changed.  We find the column on the original line, then find the corresponding column on the new line.

---

*[components/script/textinput.rs, line 533 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10350#-KELC2eBvwq9p4_UNX7n:-KEMLc6K05bs6iMUqUcb:-499146009) ([raw file](https://github.com/servo/servo/blob/f121a5b68a7a1d5b1bcc7b917c65fbfb6100650f/components/script/textinput.rs#L533)):*
Done.

---

*[tests/unit/script/textinput.rs, line 138 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10350#-KELD8YIIh1rwy30n9DP:-KEMNdYZEnD6Sl6lu0rs:-499146009) ([raw file](https://github.com/servo/servo/blob/f121a5b68a7a1d5b1bcc7b917c65fbfb6100650f/tests/unit/script/textinput.rs#L138)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10350)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10350#-:-KEMW5afRHVU4SCoCdVH:1236647940)*

**Pull request merged**
