### PR TITLE
Uniformise the various Msg types [#5882]

### LINKED ISSUE #5882: Uniformise the various Msg types
The Error suffix from dom::error::Error constructors was recently dropped and the CanvasMsg constructors never include a Msg suffix, instead the type of their contents is itself suffixed with Msg, making chains such as CanvasMsg::Canvas2d(Canvas2dMsg).

The other Msg types such as constellation_msg::Msg and MozBrowserEventMsg should follow the same scheme.

### PR DESCRIPTION
**Pull request by psdh**
Fixes #5882

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5895)

### CODE REVIEW

**Comment by Manishearth** [comment]
Reviewed files:
- components/compositing/constellation.rs @ r1
- components/compositing/pipeline.rs @ r1
- components/msg/constellation_msg.rs @ r1
- components/script/dom/document.rs @ r1
- components/script/script_task.rs @ r1
- components/script_traits/lib.rs @ r1

---

<sup>**[components/script_traits/lib.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4cAOEI1EJZ6sgdc7f)** ([raw file](https://github.com/servo/servo/blob/a16dc2442865ed6ad55e88df4158ed70a9f9e2ba/components/script_traits/lib.rs#L81)):</sup>
These two `Msg` variants still exist, could you fix those too? :)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5895)

**Comment by jgraham** [comment]
<sup>**[components/compositing/constellation.rs, line 389 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lHwzJUCX0-SV1Su4)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/compositing/constellation.rs#L389)):</sup>
Indentation

---

<sup>**[components/compositing/pipeline.rs, line 264 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4laov_T_--4oKpL16)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/compositing/pipeline.rs#L264)):</sup>
Indentation

---

<sup>**[components/script/dom/document.rs, line 773 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4ldh5Fyj-en11dfLl)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/script/dom/document.rs#L773)):</sup>
Indentation

---

<sup>**[components/script/script_task.rs, line 722 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lfYy5QzZKWbjlfnU)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/script/script_task.rs#L722)):</sup>
Indentation

---

<sup>**[components/webdriver_server/lib.rs, line 137 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lhT2qygx1Hni6H0B)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/webdriver_server/lib.rs#L137)):</sup>
Indentation

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5895)

**Comment by Manishearth** [comment]
Reviewed files:
- components/compositing/constellation.rs @ r2
- components/compositing/pipeline.rs @ r2
- components/layout/layout_task.rs @ r2
- components/layout_traits/lib.rs @ r2
- components/msg/constellation_msg.rs @ r2
- components/script/dom/document.rs @ r2
- components/script/script_task.rs @ r2
- components/script_traits/lib.rs @ r2
- components/webdriver_server/lib.rs @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5895)

**Comment by psdh** [comment]
<sup>**[components/compositing/constellation.rs, line 389 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lHwzJUCX0-SV1Su4)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/compositing/constellation.rs#L389)):</sup>
Done.

---

<sup>**[components/compositing/pipeline.rs, line 264 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4laov_T_--4oKpL16)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/compositing/pipeline.rs#L264)):</sup>
Done.

---

<sup>**[components/script/dom/document.rs, line 773 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4ldh5Fyj-en11dfLl)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/script/dom/document.rs#L773)):</sup>
Done.

---

<sup>**[components/script/script_task.rs, line 722 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lfYy5QzZKWbjlfnU)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/script/script_task.rs#L722)):</sup>
Done.

---

<sup>**[components/webdriver_server/lib.rs, line 137 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lhT2qygx1Hni6H0B)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/webdriver_server/lib.rs#L137)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5895)

**Comment by Manishearth** [comment]
<sup>**[components/compositing/constellation.rs, line 389 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lHwzJUCX0-SV1Su4)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/compositing/constellation.rs#L389)):</sup>
....these don't look done? You want the next line of arguments to align with the previous list.

e.g

```
            ConstellationMsg::MozBrowserEvent(pipeline_id,
                                                                                    subpage_id,
```

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5895)

**Comment by Manishearth** [comment]
<sup>**[components/compositing/constellation.rs, line 389 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lHwzJUCX0-SV1Su4)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/compositing/constellation.rs#L389)):</sup>
Um, sorry

```
            ConstellationMsg::MozBrowserEvent(pipeline_id,
                                              subpage_id,
```

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5895)

**Comment by psdh** [comment]
<sup>**[components/compositing/constellation.rs, line 389 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lHwzJUCX0-SV1Su4)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/compositing/constellation.rs#L389)):</sup>
I meant, I have made the required changes as part of the next commit :)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5895)

**Comment by Manishearth** [comment]
Reviewed files:
- components/compositing/constellation.rs @ r3
- components/compositing/pipeline.rs @ r3
- components/layout/layout_task.rs @ r2
- components/layout_traits/lib.rs @ r2
- components/msg/constellation_msg.rs @ r2
- components/script/dom/document.rs @ r3
- components/script/script_task.rs @ r3
- components/script_traits/lib.rs @ r2
- components/webdriver_server/lib.rs @ r3

---

<sup>**[components/compositing/constellation.rs, line 389 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5895#-Jo4lHwzJUCX0-SV1Su4)** ([raw file](https://github.com/servo/servo/blob/c0996a077ae1bc9f3131f57750510e7b6ac0a08e/components/compositing/constellation.rs#L389)):</sup>
Somehow didn't notice that. Sorry.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5895)

**Comment by Manishearth** [comment]
Squash please!

**Pull request merged**
