### PR TITLE
Use one Python virtual environment for all mach commands

### PR DESCRIPTION
**Pull request by frewsxcv**
_See individual commits for more information_

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7103)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

Nice work!

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 45 of 45 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7103)

**Comment by Ms2ger** [comment]
I reverted this because wpt no longer ran any tests.

**Comment by frewsxcv** [comment]
@Ms2ger What command did you run that caused it to not run any tests? It seems to be working fine for me locally

**Comment by Ms2ger** [comment]
http://build.servo.org/builders/linux2/builds/2687/steps/shell_1/logs/stdio

**Comment by frewsxcv** [comment]
Hmm. I am now able to reproduce this (not sure why I was not before). The tests are actually getting run, but (with exception to those `KeyError`s) are not logging at all. I am looking into it now...

**Comment by frewsxcv** [comment]
It looks like the `KeyError` is unrelated and has been happening with build results predating this PR

https://github.com/servo/servo/issues/7113

**Comment by metajack** [comment]
cc @jgraham

**Comment by frewsxcv** [comment]
In this pull request, I (unknowingly) bumped mozlog to a newer version [that has a breaking change](https://github.com/mozilla/gecko-dev/commit/2be5ff0c107cfbdfede957147de2560ce9876a28#diff-f7927aa6bbd3cf41aaac8e3e2f011a3a). I will update the necessary things before opening a PR for the revert of the revert.

**Comment by frewsxcv** [comment]
Actually, [it looks like the necessary changes have already been made upstream to wptrunner](https://github.com/w3c/wptrunner/commit/1e8170ea7d8c1caa36389a968d155b12a648c1d9#diff-b4ef698db8ca845e5845c4618278f29a), we just need to update our local copy

**Comment by metajack** [comment]
Yes, I ran into this exact thing when I tried to upgrade wptrunner but hadn't updated mozlog. I didn't know what had caused it, so thanks for figuring this out.

**Pull request merged**
