### PR TITLE
WebGPU: always send exit message to script before exiting

### PR DESCRIPTION
**Pull request by gterzian**
When WebGPU exits, including when it internally encounters an error, always first send the `Exit` message to script before exiting. 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix https://github.com/servo/servo/issues/30915

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Review by sagudev — COMMENTED** [review]
LGTM, but I would like to wait for webgpu run: https://github.com/sagudev/servo/actions/runs/7398389520

**Comment by sagudev** [comment]
New run for updated expectations: https://github.com/sagudev/servo/actions/runs/7398819825

**Review by sagudev — APPROVED** [review]
Given that https://github.com/servo/servo/issues/30999, I think the real changes are captured in updates expectations (mostly CRASH -> TIMEOUT).

**Comment by gterzian** [comment]
Thanks for the review and test update! @sagudev

**Pull request merged**
