### PR TITLE
Do not leak the CAPI strings

### PR DESCRIPTION
**Pull request by paulrouget**
Depends on #23983 

I haven't remove the mem::forget here: https://github.com/servo/servo/blob/6528c0d9b7b36fbdffc29bab99e0066b83a7f970/ports/libsimpleservo/capi/src/lib.rs#L228

What would be the right approach in that specific case?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23998)

### CODE REVIEW

**Comment by jdm** [comment]
Any chance servo_version() can return a static string? The changes in this PR look fine to me.

**Comment by CYBAI** [comment]
```
   Compiling libservo v0.0.1 (/repo/components/servo)
error: unused import: `std::mem`
  --> ports/libsimpleservo/capi/src/lib.rs:20:5
   |
20 | use std::mem;
   |     ^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`

error: aborting due to previous error

error: Could not compile `simpleservo_capi`.
```

**Pull request merged**
