### PR TITLE
Support non-QWERTY keyboards, take 2

### PR DESCRIPTION
**Pull request by nox**
See #11950.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11955)

### CODE REVIEW

**Comment by jdm** [comment]
The use of logical_key in keyboardevent.rs is supposed to avoid the need to change text input, so I'm confused about why this is necessary.

**Comment by nox** [comment]
@jdm I have no idea which specific part of the code you talk about without a link. I'm confused why you would think anything is not necessary, given it didn't work on my machine without it (e.g. `shift-;` inputs `;` instead of `.`, and `:` inputs `;` instead of `:`).

**Comment by jdm** [comment]
The only use of logical_key is in keyboardevent.rs. It takes the key value (physical key) and the character value (logical key) and returns a key value that is supposed to correspond to the logical key if it exists. This is stored in the event and returned by get_key() which is used by text input.rs. This way, the text input code is supposed to only deal with enumerated key values that reflect the character value that gluten reported.

**Comment by nox** [comment]
I have no idea what all of this mean sorry. All I know is that textinput didn't get the right chars without my commit.

**Comment by jdm** [comment]
You were right; I made similar changes to #11950.

**Pull request closed without merging**
