### PR TITLE
Use TypeError instead of InvalidState for exception.

### LINKED ISSUE #23202: Update CustomElementConstructor type and exception
The IDL for CustomElementConstructor was changed in https://github.com/whatwg/html/pull/4525. We should update that as well as the exception used by [this code](https://github.com/servo/servo/blob/17204544d975a44f813b96ed3e0eae3b688596bc/components/script/dom/customelementregistry.rs#L668).

To test these changes, we will need the tests in https://github.com/web-platform-tests/wpt/pull/16328.

### PR DESCRIPTION
**Pull request by gatoWololo**
Use TypeError instead of InvalidState as per https://github.com/whatwg/html/pull/4525 for making CustomElementConstructor exceptions more consistent.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #23202  (GitHub issue number if applicable)

- [X] There are tests for these changes: Tests that expected failure now expect passing with correct result.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23530)

### CODE REVIEW

**Review by CYBAI — COMMENTED** [review]
Thanks for working on this!

As part of the updated spec in  https://github.com/whatwg/html/pull/4525/files#diff-36cd38f49b9afa08222c0dc9ebfe35ebR66823, we'll need to update the idl type as well.

https://github.com/servo/servo/blob/1e158bbfaed2bed6c739d14dbd1cd4ba5cacfe82/components/script/dom/webidls/CustomElementRegistry.webidl#L16

**Comment by gatoWololo** [comment]
@CYBAI Okay, thanks! I have amended by commit to do update the idl type.

**Comment by jdm** [comment]
@bors-servo r=cybai,jdm
Thanks!

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by jdm** [comment]
@bors-servo retry
* https://github.com/servo/intermittent-failure-tracker/issues/5

**Comment by asajeffrey** [comment]
So what I mean about intermittents being annoying?

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Comment by CYBAI** [comment]
@bors-servo retry

-  #23540

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Pull request merged**
