### PR TITLE
Fixes for insertion point caret rendering

### PR DESCRIPTION
**Pull request by mbrubeck**
This contains several fixes for the code to position and render the insertion point.  The main effect is that the insertion point is now rendered correctly when in an empty input field.  See the individual commit messages for more detais.  r? @pcwalton

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10361)

### CODE REVIEW

**Comment by pcwalton** [comment]
\o/

**Comment by KiChjang** [comment]
```
Ran 4651 tests finished in 1072.0 seconds.
  • 4647 ran as expected. 1362 tests skipped.
  • 4 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-nested.html
  └   → /html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-nested.html 9ee74880d4eebe46cca63f83ce42407c4d27b7fb
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-nested-ref.html 98e4bba8700abda1a869e67f4f7ead663ff68ffd
Testing 9ee74880d4eebe46cca63f83ce42407c4d27b7fb == 98e4bba8700abda1a869e67f4f7ead663ff68ffd

  ▶ FAIL [expected PASS] /html/semantics/text-level-semantics/the-bdo-element/bdo-override.html
  └   → /html/semantics/text-level-semantics/the-bdo-element/bdo-override.html 71166ce448ca0e18d6255cab348364853ca98a95
/html/semantics/text-level-semantics/the-bdo-element/bidi-001-ref.html 765ae13aed4ac2ac5b828905bf9aae621a73b98b
Testing 71166ce448ca0e18d6255cab348364853ca98a95 == 765ae13aed4ac2ac5b828905bf9aae621a73b98b

  ▶ FAIL [expected PASS] /_mozilla/css/focus_selector.html
  └   → /_mozilla/css/focus_selector.html b63153bdd815642c474727d89b836ff14818e86d
/_mozilla/css/focus_selector_ref.html 8ebbf7f031e262434263c05476489eae5ff99cdc
Testing b63153bdd815642c474727d89b836ff14818e86d == 8ebbf7f031e262434263c05476489eae5ff99cdc

  ▶ FAIL [expected PASS] /_mozilla/css/per_glyph_font_fallback_a.html
  └   → /_mozilla/css/per_glyph_font_fallback_a.html 4035eaba412448185cdebbd09cb71206d92cfa0e
/_mozilla/css/per_glyph_font_fallback_ref.html ba54cac56e2d0f4863e726d992495ea6d059e33f
Testing 4035eaba412448185cdebbd09cb71206d92cfa0e == ba54cac56e2d0f4863e726d992495ea6d059e33f
```

**Comment by mbrubeck** [comment]
> `FAIL [expected PASS] /_mozilla/css/focus_selector.html`

This is a bug in the test, which can be fixed by focusing the input in the reference.  The other failures are real regressions.

**Comment by mbrubeck** [comment]
@bors-servo r=pcwalton

* Fixed the broken test.
* Reverted part of the first commit, which was supposed to be just refactoring but introduced a bug that broke the other tests.
* Everything else is unchanged.

**Pull request merged**
