### PR TITLE
Update nsstring.

### PR DESCRIPTION
**Pull request by emilio**
This should fix bug 1334579

r? @bholley @heycam or @Manishearth

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15582)

### CODE REVIEW

**Comment by heycam** [comment]
rs=me

@bors-servo r+

**Comment by emilio** [comment]
@bors-servo r=heycam

 * I don't know why bors hasn't replied

**Comment by emilio** [comment]
@bors-servo r=heycam

 * Apparently this wasn't in the queue, synchronizing should've fixed this.

**Comment by mystor** [comment]
@emilio The fact that you're including the #[no_mangle] helper functions might be problematic for when this is built with gecko, as there will be duplicate symbols. You might want to not include the test helpers module.

**Comment by emilio** [comment]
Ouch, of course, great catch.

@bors-servo r=heycam

**Comment by emilio** [comment]
@bors-servo r=heycam 

 * Warnings in the build due to the removal of the tests

**Pull request merged**
