### PR TITLE
Update BrowserElement.webidl

### PR DESCRIPTION
**Pull request by Coder206**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11451)

### CODE REVIEW

**Comment by jdm** [comment]
It appears that you haven't compiled the changes. Please do so before making a pull request :)

**Comment by Coder206** [comment]
@jdm I am new to this, do you mean compile and re upload?

**Comment by ConnorGBrewster** [comment]
@Coder206 your change the `webidl` file will require some more changes elsewhere, when you compile you should get some errors, those errors will need to be fixed.

**Comment by jdm** [comment]
When you've made the necessary changes and fixed the tests from #11450, you can commit your changes and push them to this branch and reopen the pull request.

**Comment by Coder206** [comment]
@jdm and @ConnorGBrewster So you just want me to try to compile and ensure it works on my end before sending it off?

**Comment by jdm** [comment]
@Coder206 Yes, that makes reviewing the code changes much less effort for us.

**Comment by Coder206** [comment]
@jdm Sorry for the inconvenience, won't happen again from me.

**Pull request closed without merging**
