### PR TITLE
Enable more CSS module tests

### PR DESCRIPTION
**Pull request by gsnedders**
As noted, this excludes Fonts, on the assumption #8374 will land first. This should get us testing every property we support, I think.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8565)

### CODE REVIEW

**Comment by gsnedders** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /css-transitions-1_dev/html/properties-value-001.htm:
  └ PASS [expected FAIL] height length(pt) / values

  ▶ Unexpected subtest result in /css-transitions-1_dev/html/properties-value-inherit-003.htm:
  └ PASS [expected FAIL] border-right-width length-em(em) / values

  ▶ Unexpected subtest result in /css-transitions-1_dev/html/properties-value-inherit-003.htm:
  └ PASS [expected FAIL] padding-bottom length-em(em) / values

  ▶ Unexpected subtest result in /css-transitions-1_dev/html/properties-value-inherit-003.htm:
  └ PASS [expected FAIL] margin-bottom length-em(em) / values

  ▶ Unexpected subtest result in /css-transitions-1_dev/html/properties-value-inherit-003.htm:
  └ PASS [expected FAIL] width length-em(em) / values

  ▶ Unexpected subtest result in /css-transitions-1_dev/html/properties-value-inherit-003.htm:
  │ FAIL [expected PASS] border-left-width length-em(em) / values
  │   → assert_not_equals: initial and target values may not match got disallowed value "22px"
  │ FAIL [expected PASS] outline-offset length-em(em) / values
  │   → assert_not_equals: initial and target values may not match got disallowed value "22px"
  │ 
  │ .cases.values.start@http://web-platform.test:8000/css-transitions-1_dev/html/properties-value-inherit-003.htm:70:29
  │ runLoop/</</<@http://web-platform.test:8000/css-transitions-1_dev/html/support/runParallelAsyncHarness.js:110:22
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1226:20
  │ runLoop/</<@http://web-platform.test:8000/css-transitions-1_dev/html/support/runParallelAsyncHarness.js:109:17
  │ runLoop/<@http://web-platform.test:8000/css-transitions-1_dev/html/support/runParallelAsyncHarness.js:108:13
  └ runLoop@http://web-platform.test:8000/css-transitions-1_dev/html/support/runParallelAsyncHarness.js:107:9

  ▶ Unexpected subtest result in /css-transitions-1_dev/html/properties-value-inherit-002.htm:
  └ PASS [expected FAIL] padding-bottom length(cm) / values

  ▶ Unexpected subtest result in /css-transitions-1_dev/html/transitions-animatable-properties-01.htm:
  └ NOTRUN [expected PASS] font-size intermediate

  ▶ PASS [expected CRASH] /css-transforms-1_dev/html/svg-translate-006.htm
```

**Comment by gsnedders** [comment]
Bah. A lot of these transitions tests seem to be random, and that transforms test is an intermittent crash.

**Comment by gsnedders** [comment]
[linux-rel](http://build.servo.org/builders/linux-rel/builds/543) had a bunch of the transitions tests time out, too…

**Comment by gsnedders** [comment]
Conclusion on IRC is to disable the random tests.

**Comment by SimonSapin** [comment]
```
  ▶ TIMEOUT [expected OK] /css-transitions-1_dev/html/properties-value-inherit-001.htm
```
(Lots of TIMEOUT and NOTRUN subtests)

```
  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/css-flexbox-column-reverse.htm
  └   → /css-flexbox-1_dev/html/css-flexbox-column-reverse.htm b2d841c70185698b294c6b5ab6ba7135ddffaeab
/css-flexbox-1_dev/html/reference/css-flexbox-column-ref.htm 4c1c7da7e7b20df6ec20c20364127cf1cdf82ca6
Testing b2d841c70185698b294c6b5ab6ba7135ddffaeab == 4c1c7da7e7b20df6ec20c20364127cf1cdf82ca6

  ▶ FAIL [expected PASS] /css-text-3_dev/html/word-break-normal-ar-000.htm
  └   → /css-text-3_dev/html/word-break-normal-ar-000.htm 781fa943d05a90d3d52c49ca38832ebe0f17e99b
/css-text-3_dev/html/reference/word-break-normal-ar-ref-000.htm 45fe8dc5205843b9238fda6e911d894a0b3335ea
Testing 781fa943d05a90d3d52c49ca38832ebe0f17e99b == 45fe8dc5205843b9238fda6e911d894a0b3335ea
```

**Comment by gsnedders** [comment]
Yeah, I saw. Never had those timeout locally. *sighs* I fear we'll just have to disable all the transitions tests?

**Comment by SimonSapin** [comment]
Or just that file? They seem to be all in the same file.

**Comment by gsnedders** [comment]
You do that, then you'll find a different one failing on the next try run…

**Comment by SimonSapin** [comment]
Ok, so it sounds like transition tests results are too unreliable to enable right now. Let’s file a follow-up issue and land the rest of this PR?

**Comment by gsnedders** [comment]
OK, disabled all of properties-value-* and it's looking promising.

**Comment by gsnedders** [comment]
Bah, something has broken media queries…

**Comment by frewsxcv** [comment]
> Bah, something has broken media queries…

Potentially relevant testcase in the comments: https://github.com/servo/servo/pull/9024

**Comment by gsnedders** [comment]
That's now https://github.com/servo/servo/issues/9052

**Comment by gsnedders** [comment]
@bors-servo try

I feel hopeful now.

**Comment by gsnedders** [comment]
I think there's a few more final disables needed for transforms tests.

**Comment by nox** [comment]
Seems like trying PRs is still kind of broken.

**Comment by gsnedders** [comment]
Well... those are unexpected results I've never seen before :(

**Comment by gsnedders** [comment]
@bors-servo retry

Let's just retry this, given these failures seem really rare. They are:

```
Tests with unexpected results:
  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/css-flexbox-column-reverse.htm
  └   → /css-flexbox-1_dev/html/css-flexbox-column-reverse.htm b2d841c70185698b294c6b5ab6ba7135ddffaeab
/css-flexbox-1_dev/html/reference/css-flexbox-column-ref.htm 4c1c7da7e7b20df6ec20c20364127cf1cdf82ca6
Testing b2d841c70185698b294c6b5ab6ba7135ddffaeab == 4c1c7da7e7b20df6ec20c20364127cf1cdf82ca6

  ▶ FAIL [expected PASS] /css-text-3_dev/html/word-break-normal-ar-000.htm
  └   → /css-text-3_dev/html/word-break-normal-ar-000.htm 781fa943d05a90d3d52c49ca38832ebe0f17e99b
/css-text-3_dev/html/reference/word-break-normal-ar-ref-000.htm 45fe8dc5205843b9238fda6e911d894a0b3335ea
Testing 781fa943d05a90d3d52c49ca38832ebe0f17e99b == 45fe8dc5205843b9238fda6e911d894a0b3335ea
```

**Comment by nox** [comment]
`/css-flexbox-1_dev/html/css-flexbox-column-reverse.htm` happened on #9108 too, this one should probably be disabled and filed as intermittent.

**Comment by gsnedders** [comment]
Both of them seem to reproducibly fail on buildbot on Linux. Can't repro either locally.

**Comment by larsbergstrom** [comment]
@gsnedders Do they pass for you even with a headless build? That is, setting `SERVO_HEADLESS=1` in your environment, doing a build of Servo, and then running with that build? It takes a slightly different rendering path than running the CSS tests in non-headless mode.

**Comment by gsnedders** [comment]
@bors-servo try

@larsbergstrom Will try that. Still, probably better to disable given we don't seem to have any way to change expectation dependent on headlessness.

**Comment by gsnedders** [comment]
Should that not have removed the tests failed label? Let's get this landed, guys!

**Comment by nox** [comment]
Let's get this squashed first.

**Comment by nox** [comment]
And reviewed beforehand, I guess.

**Comment by gsnedders** [comment]
That failure is #9106. Do we want to retry or not?

**Pull request merged**
