### PR TITLE
Flatten display list structure

### PR DESCRIPTION
**Pull request by mrobinson**
Instead of producing a tree of stacking contexts, display list
generation now produces a flat list of display items and a tree of
stacking contexts. This will eventually allow display list construction
to produce and modify WebRender vertex buffers directly, removing the
overhead of display list conversion.  This change also moves
layerization of the display list to the paint thread, since it isn't
currently useful for WebRender.

To accomplish this, display list generation now takes three passes of
the flow tree:

```
    1. Calculation of absolute positions.
    2. Collection of a tree of stacking contexts.
    3. Creation of a list of display items.
```

After collection of display items, they are sorted based upon the index
of their parent stacking contexts and their position in CSS 2.1
Appendeix E stacking order.

This is a big change, but it actually simplifies display list generation.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9756)

### CODE REVIEW

**Comment by mrobinson** [comment]
@pcwalton r?

I really am sorry for the size of this patch, but I couldn't really figure out a way to split it up. I'm happy to help out in whatever way to get it reviewed.

**Comment by pcwalton** [comment]
Review status: 0 of 27 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/gfx/paint_thread.rs, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9756#-KBjRPMYvGUFCLW-GSGp:-KBjRPMYvGUFCLW-GSGq:-656313791) ([raw file](https://github.com/servo/servo/blob/b5c6e6734e303299cf0aa029568da46ed0c628d1/components/gfx/paint_thread.rs#L58)):*
How about `single_item`?

Also, I'm not sure why this flag exists. Could you explain?

---

*[components/gfx/paint_thread.rs, line 198 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9756#-KBjRYV9uJIuMds9L5QI:-KBjRYV9uJIuMds9L5QJ:463853142) ([raw file](https://github.com/servo/servo/blob/b5c6e6734e303299cf0aa029568da46ed0c628d1/components/gfx/paint_thread.rs#L198)):*
nit: could be `self.layer_details_stack.last().as_ref().map(|layer| layer.layer_properties.id)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9756)*

**Comment by pcwalton** [comment]
Ah, OK.

In that case, this looks good to me modulo the surrounding comments! Rebase and I'll r+.

**Comment by mrobinson** [comment]
Review status: 0 of 27 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/gfx/paint_thread.rs, line 58 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9756#-KBjRPMYvGUFCLW-GSGp:-KBnsOjB9FtEG5XRMNpx:-499146009) ([raw file](https://github.com/servo/servo/blob/b5c6e6734e303299cf0aa029568da46ed0c628d1/components/gfx/paint_thread.rs#L58)):*
Done.

---

*[components/gfx/paint_thread.rs, line 198 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9756#-KBjRYV9uJIuMds9L5QI:-KBnfRzQ27iOR-g05Sqg:-499146009) ([raw file](https://github.com/servo/servo/blob/b5c6e6734e303299cf0aa029568da46ed0c628d1/components/gfx/paint_thread.rs#L198)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9756)*

**Comment by mrobinson** [comment]
Thanks for the review! I think I've addressed all your comments and uploaded the rebased patch.

---

Review status: 0 of 27 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9756#-:-KBoZCU5UQ7tEpO2e7ZB:-364731806)*

**Comment by pcwalton** [comment]
@bors-servo: r+

Here we go!

**Comment by metajack** [comment]
Woohoo!

Great job on this @mrobinson !

**Pull request merged**
