### PR TITLE
gfx: Implement WOFF support in Servo via conversion to OTF with the `rust-woff` crate.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7349)

### CODE REVIEW

**Comment by jdm** [comment]
As discussed on IRC, I think this should expose an API for font context-specific sniffing per the spec, and we should call that directly instead of relying on the full MIME classifying algorithm.

**Comment by pcwalton** [comment]
@jdm When you say you want to use an API for font-context-specific matching, do you think that API should live in `mime_classifier.rs` or would you prefer it to be a separate implementation altogether?

**Comment by jdm** [comment]
mime_classifier.rs makes sense to me.

**Comment by pcwalton** [comment]
I have addressed the MIME sniffing issue, but many WOFF fonts aren't being loaded properly. I think this should wait on `ots` OpenType sanitization, since it contains code to load WOFF files and should hopefully work right.

**Comment by jdm** [comment]
Whenever we get around to the OpenType sanitization, this should build on top of the work from #8190 that implements the font-sniffing appropriately.

**Pull request closed without merging**
