### PR TITLE
Support Scroll in HoloLens mode

### PR DESCRIPTION
**Pull request by paulrouget**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23831)

### CODE REVIEW

**Comment by paulrouget** [comment]
This doesn't work in non-HoloLens env. I could use `wheelchanged` but I'm still talking to MS about how to properly handle gestures.

This approach is the "Right way" for hololens.

fix #23678

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Comment by jdm** [comment]
@bors-servo retry
#13480

**Pull request merged**
