### PR TITLE
Add basic HTMLDialogElement interface

### PR DESCRIPTION
**Pull request by dhodder**
An empty DOM interface for HTMLDialogElement

r?

### CODE REVIEW

**Comment by Manishearth** [comment]
Thanks!

Do you intend to extend this later?

**Comment by dhodder** [comment]
Hi @Manishearth, thank you for the review! I'm still learning but hope to see if I can extend in later PRs (maybe `open` or `show()` next). Looking at http://build.servo.org/builders/linux2/builds/1291/steps/shell_1/logs/stdio I can see:

```/html/dom/interfaces.html
-------------------------
PASS expected FAIL HTMLDialogElement interface: existence and properties of interface prototype object
PASS expected FAIL HTMLDialogElement interface: existence and properties of interface prototype object's "constructor" property
/html/semantics/interfaces.html
-------------------------------
PASS expected FAIL Interfaces for dialog
 9:15.16 LOG: MainThread INFO Closing logging queue
 9:15.16 LOG: MainThread INFO queue closed
program finished with exit code 1
```

Sorry! :(

Should I attempt to address this and add to this PR?

**Comment by Manishearth** [comment]
Oh, right, sorry. I forgot to ask you to update the tests.

Follow the steps [here](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations), and push the changes

**Comment by dhodder** [comment]
Thanks @Manishearth -- I've updated `tests/wpt/metadata/html/dom/interfaces.html.ini` and `tests/wpt/metadata/html/semantics/interfaces.html.ini` accordingly.

**Pull request merged**
