### PR TITLE
Upgrade to rustc 1.52.0-nightly (a8486b64b 2021-02-24)

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
This is likely still blocked on https://github.com/servo/servo/issues/28101, but let’s see if anything else came up:

@bors-servo try

**Comment by SimonSapin** [comment]
And we’re down to https://github.com/servo/servo/issues/28101 as expected, and a couple WPT failures that might (?) be intermittent

**Comment by jdm** [comment]
I'm going to get us onto a fixed version of truetype in https://github.com/servo/servo/pull/28203.

**Comment by SimonSapin** [comment]
This should be good to go. r? @jdm (see individual commits to separate changes made by rustfmt from other changes)

**Pull request merged**
