### PR TITLE
Skip dependencyci checks for known deprecated modules.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14045)

### CODE REVIEW

**Comment by jdm** [comment]
r? @larsbergstrom 
This makes our DependencyCI build go green. I've also submitted https://github.com/librariesio/librarian-parsers/pull/52 to avoid the confusion between our local crates and actual ones one crates.io.

**Comment by larsbergstrom** [comment]
Does this need a squash? It looks like you've added and removed a bunch of interesting exclusions to the `dependencyci.yml` file in this commit sequence.

**Comment by jdm** [comment]
I did it all through the github UI, so couldn't amend. I can squash if you'd like.

**Comment by larsbergstrom** [comment]
r=me. A squash would be nice if you don't mind. Otherwise, the history will be a bit icky.

**Comment by jdm** [comment]
@bors-servo: retry
* #13479

**Pull request merged**
