### PR TITLE
Update README.md to include openSUSE dependencies

### PR DESCRIPTION
**Pull request by j-koreth**
---

- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because the only file changed is the README.md to include openSUSE dependencies

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13534)

### CODE REVIEW

**Comment by KiChjang** [comment]
@j-koreth Just a tip, next time you create a PR, try not to make commits on your fork's master branch. Instead, check out a feature branch and commit to that. That way your changes would not be affected when you pull from upstream. Thanks!

@bors-servo r=jdm

**Comment by j-koreth** [comment]
@KiChjang Thanks for the advice and I'm sorry for having 4 commits like that. I didn't realize you can do it in other ways, I guess I have a lot of learning to do :P

**Comment by j-koreth** [comment]
Oops didn't mean to close this, sorry about that

**Comment by KiChjang** [comment]
@bors-servo retry
* #13133

**Comment by j-koreth** [comment]
Wait how can a change to the README.md file fail tests?

**Comment by KiChjang** [comment]
@j-koreth It has nothing to do with your changes, the test failure is a known intermittent.

**Comment by j-koreth** [comment]
Oh all right thanks @KiChjang, I only saw your earlier #13133 comment after submitting my comment

**Pull request merged**
