### PR TITLE
Update WR (new border code path).

### PR DESCRIPTION
**Pull request by glennw**
This includes the new border code path for simple (solid) borders.
This gives much higher quality border rendering, including proper
support for elliptical border segments.

The quality on https://github.com/servo/servo is noticeably improved.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16398)

### CODE REVIEW

**Comment by glennw** [comment]
I have disabled two tests in this update. Both of them have 1.0 / 255.0 pixel differences in a small number of pixels near the bottom left corner.

This is a floating point inaccuracy during rasterization (one test has transforms which results in the floating point accumulating slightly differently). Ideally we'd use a fuzzy reftest here to account for the difference in a few pixels.

**Comment by jdm** [comment]
```
▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-input-019.htm
```
Delightful!

**Pull request merged**
