### PR TITLE
Clean up WebGL parameter functions

### PR DESCRIPTION
**Pull request by dzbarsky**
Do we have tests for WebGL?
Trying to get http://learningwebgl.com/lessons/lesson01/index.html running but we're still missing some things.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8743)

### CODE REVIEW

**Comment by jdm** [comment]
We have some tests (there's webgl/ under WPT and webg/ under the mozilla/ directory), but most are disabled due to #7931.

**Comment by jdm** [comment]
@ecoal95 Want to review this one? :)

**Comment by ecoal95** [comment]
@jdm Yep! :)

**Comment by ecoal95** [comment]
Looks good to me, @bzbarsky ping me when gleam is updated and I'll r+ this :)

-S-awaiting-review +S-blocked-on-external

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/canvas/webgl_paint_task.rs, line 343 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8743#-K4ODpWXYf4--vpLZdRt:-K4ODpWXYf4--vpLZdRu:533145684) ([raw file](https://github.com/servo/servo/blob/a8c5a3204515a5483dd6c496b0b09d84180c8a08/components/canvas/webgl_paint_task.rs#L343)):*
Nice! These validations were done in script to avoid an ipc-channel roundtrip, but I think this way is better, since we only have the logic in one place, and we'd only get the speed-up in invalid cases anyways, so...

---

*[components/script/dom/webglrenderingcontext.rs, line 640 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8743#-K4OFUL29ml_ZJgAQ11I:-K4OFUL29ml_ZJgAQ11J:-1990626433) ([raw file](https://github.com/servo/servo/blob/a8c5a3204515a5483dd6c496b0b09d84180c8a08/components/script/dom/webglrenderingcontext.rs#L640)):*
I've re-read the spec here, and even though there's no behaviour specified, both gecko and chromium generate an `InvalidValue` error when the program is null.

I think it would be nice to mimic this behaviour where null values are not expected. They're a few functions though, so this can be left as a followup if you want. I've filled https://github.com/servo/servo/issues/8753

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8743#-:-K4ODwG6H3DrFw6jJ8pL:1602154226)*

**Comment by bzbarsky** [comment]
@ecoal95 You have the wrong Zbarsky, I think.

**Comment by ecoal95** [comment]
@bzbarsky thanks! Sorry, I meant @dzbarsky.

**Comment by dzbarsky** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/canvas/webgl_paint_task.rs, line 343 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8743#-K4ODpWXYf4--vpLZdRt:-K4QyihRGd9KdKMBT0uc:1411271431) ([raw file](https://github.com/servo/servo/blob/a8c5a3204515a5483dd6c496b0b09d84180c8a08/components/canvas/webgl_paint_task.rs#L343)):*
Yep, that's what I figured.

---

*[components/script/dom/webglrenderingcontext.rs, line 640 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8743#-K4OFUL29ml_ZJgAQ11I:-K4Qyn9teS9KlkBf_zFI:-1803872352) ([raw file](https://github.com/servo/servo/blob/a8c5a3204515a5483dd6c496b0b09d84180c8a08/components/script/dom/webglrenderingcontext.rs#L640)):*
If we do that we should also get the spec changed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8743)*

**Comment by ecoal95** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/webglrenderingcontext.rs, line 640 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8743#-K4OFUL29ml_ZJgAQ11I:-K4RmnrqTrZ12sXPsUWO:899651792) ([raw file](https://github.com/servo/servo/blob/a8c5a3204515a5483dd6c496b0b09d84180c8a08/components/script/dom/webglrenderingcontext.rs#L640)):*
I don't think so, I think it conforms to the spec in the sense that WebGL's behaviour, unless specified otherwise, must much the behaviour of GLES 2.

In that sense, the reference for most of this functions ([eg `glGetProgramiv`](https://www.khronos.org/opengles/sdk/docs/man3/html/glGetProgramiv.xhtml)) have a line similar to the following:

> GL_INVALID_OPERATION is generated if program does not refer to a program object.

I therefore think it's legit and spec-compliant (probably even required?) to acquire this behaviour.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8743)*

**Comment by ecoal95** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/webglrenderingcontext.rs, line 640 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8743#-K4OFUL29ml_ZJgAQ11I:-K4Ro7xCjGlRLd1nGLvj:-134626711) ([raw file](https://github.com/servo/servo/blob/a8c5a3204515a5483dd6c496b0b09d84180c8a08/components/script/dom/webglrenderingcontext.rs#L640)):*
s/must much/must match/ (sorry)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8743)*

**Comment by dzbarsky** [comment]
https://github.com/servo/servo/pull/8761 instead

**Pull request closed without merging**
