### PR TITLE
Automated tests for WebDriver

### PR DESCRIPTION
**Pull request by krunal3103**
Created two test files in /tests/webdriver directory.
The command ./mach test-webdriver executes all the tests.py files in this directory.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10113)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/webdriver/test.py, line 3 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDRJCmyWW9ZPhk5EdGC:-KDRJCmyWW9ZPhk5EdGD:-1160394668) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/tests/webdriver/test.py#L3)):*
Not everyone's "servo" directory lives in `~`, so this probably won't work.

---

*[tests/webdriver/test.py, line 18 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDRJ84dE51TzMcnUuMS:-KDRJ84eR2HfR45SsGFk:395074351) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/tests/webdriver/test.py#L18)):*
This should be indented four spaces.

---

*[tests/webdriver/test.py, line 28 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDRJAIA81_H53wv3RQs:-KDRJAIA81_H53wv3RQt:395074351) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/tests/webdriver/test.py#L28)):*
This should be indented four spaces.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10113)*

**Comment by jdm** [comment]
Thanks for making this pull request! It's a good start, but I've proposed some changes that will make it easier to write more complicated tests going forwards, I think. In particular, I've made a pull request to your branch to add a standalone HTTP server, which will allow us to write tests that don't use real websites. I'd like to see what this PR looks like once we removed some of the code and test duplication; I think it will be easier to read at that point :)

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 5 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[python/servo/testing_commands.py, line 106 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDUsv_-rBViDfaniXfI:-KDUsv_0iomFB7BRs9v2:2008525621) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/python/servo/testing_commands.py#L106)):*
I think this is a rebase error? This testsuite doesn't exist any longer on master.

---

*[python/servo/testing_commands.py, line 294 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDUueNQbY2x1nTdzpos:-KDUueNQbY2x1nTdzpot:1147259612) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/python/servo/testing_commands.py#L294)):*
nit: space after `,`

---

*[python/servo/testing_commands.py, line 298 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVDO7DiEkW5vSloi0E:-KDVDO7DiEkW5vSloi0F:1691057621) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/python/servo/testing_commands.py#L298)):*
Test harnesses have certain requirements that invoking python via Popen doesn't quite satisfy. I've proposed a pull request for your branch that uses execfile instead so we can catch exceptions - we'll need to fill in the TODO blocks to report on tests passing or failing, and return an appropriate value to if any tests fail.

---

*[python/servo/testing_commands.py, line 378 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDUwLMFPLkAp9gXx4Z6:-KDUwLMFPLkAp9gXx4Z7:2018744027) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/python/servo/testing_commands.py#L378)):*
I think we can get rid of this; I removed the caller in my branch.

---

*[tests/dromaeo/dromaeo, line 1 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVK708kO5R-vK8Miip:-KDVK709ikvafJtgMWNl:1655797479) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/tests/dromaeo/dromaeo#L1)):*
This looks unintentional and should be reverted.

---

*[tests/webdriver/test.py, line 3 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDRJCmyWW9ZPhk5EdGC:-KDVKJdCLQ83iziWsLaQ:1921961116) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/tests/webdriver/test.py#L3)):*
Additionally, we should move this into the test-webdriver code that invokes python so it doesn't need to be replicated in every test.

---

*[tests/webdriver/test.py, line 19 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVMHwbc4ofE9i7WsE3:-KDVMHwcpKxsruj-U8bQ:-412255862) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/tests/webdriver/test.py#L19)):*
What happened to using ServoProcess? We should move that into the `harness` directory I create in my branch and use it in all the tests instead of duplicating this all the time.

---

*[tests/webdriver/test.py, line 1 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVcMHePKCHK1a90JNh:-KDVcMHePKCHK1a90JNi:-1551059896) ([raw file](https://github.com/servo/servo/blob/6faeff425bdc67f1447aa30aaee14951a8b1c2d6/tests/webdriver/test.py#L1)):*
Can we give this file a more descriptive name?

---

*[tests/webdriver/test.py, line 22 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVcPMS35fQMdTm3M3w:-KDVcPMS35fQMdTm3M3x:-801121291) ([raw file](https://github.com/servo/servo/blob/6faeff425bdc67f1447aa30aaee14951a8b1c2d6/tests/webdriver/test.py#L22)):*
Rather than using a real website, we should use the standalone HTTP server I included in my pull request.

---

*[tests/webdriver/test.py, line 33 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVc_O3nqf0yg-yTjy_:-KDVc_O43akeKDen-t73:-151944969) ([raw file](https://github.com/servo/servo/blob/6faeff425bdc67f1447aa30aaee14951a8b1c2d6/tests/webdriver/test.py#L33)):*
I think this test is duplicating the previous one in terms of things we're actually testing about webdriver, so I don't think it's useful to keep around.

---

*[tests/webdriver/test1.py, line 9 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVMUpXp1DZVX4hxGoB:-KDVMUpXp1DZVX4hxGoC:-316061993) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/tests/webdriver/test1.py#L9)):*
Why duplicate ServoProcess?

---

*[tests/webdriver/test1.py, line 23 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVclXQynmp-2qZK8eU:-KDVclXQynmp-2qZK8eV:1687962555) ([raw file](https://github.com/servo/servo/blob/6faeff425bdc67f1447aa30aaee14951a8b1c2d6/tests/webdriver/test1.py#L23)):*
What are we testing that's different than the previous file here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10113#-:-KDVcxVOW3uqTN7sFPOh:-1858985323)*

**Comment by jdm** [comment]
-S-awaiting-review -S-needs-rebase +S-needs-code-changes 

---

Reviewed 2 of 2 files at r5, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[tests/webdriver/test.py, line 3 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDRJCmyWW9ZPhk5EdGC:-KDvDLrZlRxLcSE3Vmr5:-301587933) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/tests/webdriver/test.py#L3)):*
I'm pretty sure this change makes it impossible to run the tests unless the Servo code is present in a subdirectory of the root of the partition.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10113#-:-KDvE5_Xmn6QjQ3X7QVS:904062486)*

**Comment by jdm** [comment]
@krunal3103 What's the plan here? I haven't seen any updates to address most of the review comments so far.

**Comment by jdm** [comment]
It looks like you've created the test_url.py to address my comments about the other python files, but those files should now be removed. I still have serious concerns about the test harness that haven't been addressed:
* the test still relies on real HTTP servers that are out of our control
* the test runner doesn't do any reporting about whether tests passed or failed
* it should be possible to share ServoProcess between all the tests, so it shouldn't be defined in a test file

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[tests/webdriver/test_url.py, line 19 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10113#-KF4qZtmtuZtM_45H_Tc:-KF4qZtmtuZtM_45H_Td:1403310213) ([raw file](https://github.com/servo/servo/blob/72219fd61771f4b8ff195ca239196a20f4082ed1/tests/webdriver/test_url.py#L19)):*
This isn't used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10113#-:-KF4qrIhDmiPD911VWR6:1985055582)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 4 files at r9.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[tests/webdriver/test_url.py, line 12 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10113#-KFQb9tn-40HBiuvjoqn:-KFQb9tn-40HBiuvjoqo:755379580) ([raw file](https://github.com/servo/servo/blob/27e17aceb50f425a2229d78f2779d7cd98b5caac/tests/webdriver/test_url.py#L12)):*
This won't work for any other Servo developer :)

---

*[tests/webdriver/test_url.py, line 24 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10113#-KFQbUvGA-PZGl3LEaEK:-KFQbUvGA-PZGl3LEaEL:-1599627792) ([raw file](https://github.com/servo/servo/blob/27e17aceb50f425a2229d78f2779d7cd98b5caac/tests/webdriver/test_url.py#L24)):*
We're still using a real HTTP server here. We really should be using a server that can be controlled by the test.

---

*[tests/webdriver/test_url.py, line 25 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10113#-KFQbHB4KkVzIqCOF9E1:-KFQbHB4KkVzIqCOF9E2:753395594) ([raw file](https://github.com/servo/servo/blob/27e17aceb50f425a2229d78f2779d7cd98b5caac/tests/webdriver/test_url.py#L25)):*
Why this change?

---

*[tests/wpt/harness/wptrunner/executors/ServoProcess.py, line 6 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10113#-KFQbK2S9ppqS4HO1FmW:-KFQbK2S9ppqS4HO1FmX:1403310213) ([raw file](https://github.com/servo/servo/blob/27e17aceb50f425a2229d78f2779d7cd98b5caac/tests/wpt/harness/wptrunner/executors/ServoProcess.py#L6)):*
This isn't used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10113#-:-KFQbcFgZBddn00_5EZi:1458266033)*

**Comment by srm912** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[python/servo/testing_commands.py, line 298 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVDO7DiEkW5vSloi0E:-KGIuwxUnnEuIdkoGPK0:452966563) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/python/servo/testing_commands.py#L298)):*
Using the code from the PR to execute the Python test files, we aren't able to get the tests running. But doing an `execfile` from the Python interpreter causes the test case to run.
We are stuck at these parts.

---

*[python/servo/testing_commands.py, line 378 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDUwLMFPLkAp9gXx4Z6:-KGIq-UASiDxnCcsD7fc:-351747037) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/python/servo/testing_commands.py#L378)):*
We can  

---

*[tests/webdriver/test_url.py, line 12 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10113#-KFQb9tn-40HBiuvjoqn:-KGIon0GFRj678YdhfS0:-1804265725) ([raw file](https://github.com/servo/servo/blob/27e17aceb50f425a2229d78f2779d7cd98b5caac/tests/webdriver/test_url.py#L12)):*
Should we try to introduce __init__.py files in the directory structure to be able to access the module? OR we can use your piece of code to try and add the reference of harness to the `sys.path`
` sys.path.append(path.join(self.context.topdir, "tests", "wpt", "harness", "wptrunner", "exectuors")) `

---

*[tests/webdriver/test_url.py, line 24 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10113#-KFQbUvGA-PZGl3LEaEK:-KGInzl-rap5O4Ly9lMg:634630712) ([raw file](https://github.com/servo/servo/blob/27e17aceb50f425a2229d78f2779d7cd98b5caac/tests/webdriver/test_url.py#L24)):*
Instead of keeping an external URL, we start the HTTP server here and try receiving responses based on the handler that is passed. 

---

*[tests/webdriver/test_url.py, line 25 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10113#-KFQbHB4KkVzIqCOF9E1:-KGIoT-sobv4qPlKIRwX:-1266868369) ([raw file](https://github.com/servo/servo/blob/27e17aceb50f425a2229d78f2779d7cd98b5caac/tests/webdriver/test_url.py#L25)):*
If this statement is included, the test case fails since the server returns a `500 Error`. What could be the possible cause of this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10113)*

**Comment by srm912** [comment]
Reviewed 1 of 3 files at r7.
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[python/servo/testing_commands.py, line 378 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDUwLMFPLkAp9gXx4Z6:-KGIvdab73q3F0uNP218:-2100552204) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/python/servo/testing_commands.py#L378)):*
We can remove this function once we can get the above code to execute the test file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10113)*

**Comment by srm912** [comment]
Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[python/servo/testing_commands.py, line 298 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVDO7DiEkW5vSloi0E:-KGIwrzbOQT2DKGqGAkm:1954707261) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/python/servo/testing_commands.py#L298)):*
Actually we figured out, that the test cases do not end up running at all via the Python interpreter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10113)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 4 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[python/servo/testing_commands.py, line 298 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10113#-KDVDO7DiEkW5vSloi0E:-KGIyCjBbVV0aIm9qPhq:-262939273) ([raw file](https://github.com/servo/servo/blob/a79aa0844440a2e10bb9f8851b97367e43dd1e62/python/servo/testing_commands.py#L298)):*
Does `execfile` throw an exception? Is it something else that doesn't work?

---

*[tests/webdriver/test_url.py, line 12 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10113#-KFQb9tn-40HBiuvjoqn:-KGIwxQD5n-h_gF0N5rW:-1388041787) ([raw file](https://github.com/servo/servo/blob/27e17aceb50f425a2229d78f2779d7cd98b5caac/tests/webdriver/test_url.py#L12)):*
If we use the code based on execfile, it should be enough to append to sys.path in the caller, like you said.

---

*[tests/webdriver/test_url.py, line 25 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10113#-KFQbHB4KkVzIqCOF9E1:-KGIxrBQ71HNEtJblMrH:1390435063) ([raw file](https://github.com/servo/servo/blob/27e17aceb50f425a2229d78f2779d7cd98b5caac/tests/webdriver/test_url.py#L25)):*
I don't know off the top of my head. I'm ok with leaving this with a comment explaining the problem.

---

*[tests/wpt/harness/wptrunner/executors/ServoProcess.py, line 1 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10113#-KGIyS33yirIxTk2OD8s:-KGIyS33yirIxTk2OD8t:510879373) ([raw file](https://github.com/servo/servo/blob/c8b33424b9038e887d935e8650f5952d0f70e647/tests/wpt/harness/wptrunner/executors/ServoProcess.py#L1)):*
I just noticed that this file is under tests/wpt/harness - we shouldn't make changes to this directory, since it's imported from https://github.com/w3c/wptrunner . This file should live somewhere in tests/webdriver/ instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10113#-:-KGDKzEzSdg55N34d_fh:1458266033)*

**Comment by krunal3103** [comment]
We have pushed this new commit in which we have used the dummy HttpServer instead of actual URLs. We are trying to run the web driver tests using `./mach test-webdriver`. We have introduced the relative paths due to which it isn't able to find certain dependencies required by the test files, in this case `test_url.py`
Pasting the error here
```
======================================================================
ERROR: test_get (mach.commands.f7840c870be911e6b707f45c8998d8e1.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/krunal/Git/servo/tests/webdriver/test_url.py", line 27, in test_get
    with ServoProcess():
NameError: global name 'ServoProcess' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test passed
```

**Comment by jdm** [comment]
Interesting. I just checked out your branch, ran `./mach test-webdriver` and got this:
```
godot2:dev-servo jdm$ ./mach test-webdriver
in here test_url.py
Test passed
```

**Comment by jdm** [comment]
My debugging shows me that test_url.py is being executed, but the `if __name__ == "__main__"` doesn't succeed so the testcase never runs.

**Comment by krunal3103** [comment]
The previous test_url.py does not execute the test_get method when called using execfile. I`ve pushed a new version, you can try running it to see the error.

**Comment by jdm** [comment]
For some reason the top-level imports aren't available when executing the testcases. If I add the `from ServoProcess import ServoProcess` inside `test_get` that error goes away.

**Comment by jdm** [comment]
It's not clear to me that the `unittest` package is adding value here. If the python files simply consist of import statements and the actual test code to be executed, I feel like these problems will disappear :)

**Comment by srm912** [comment]
Referring the latest commit, we plan to move forward this way i.e. by adding the test files and raising the appropriate exceptions based on the test that is being run.
In the test-runner, we will perform the following tasks:
1. Catch the exceptions raised by tests.
2. Keep a count of the number of passed and failed test cases.
3. Print a summary of the failed test cases.

**Comment by jdm** [comment]
That sounds good to me. Don't forget to return 0 or 1 from the test runner depending on whether all tests passed or not!

**Comment by krunal3103** [comment]
For the subsequent step to check response type, I do not see an already existing method in the webdriver.py that returns that. I found the text command under class Element that can be used to check the content. But how do we get the response type? Do I need to implement that method?

**Comment by jdm** [comment]
That refers to the return value of `send_command`, which is the JSON response body. The goal is to ensure that it matches the expected JSON response body defined in the specification.

**Comment by jdm** [comment]
Good improvements! Please be sure to run `./mach test-tidy` before pushing changes, and also address the old comments that are still pending in this review.
-S-awaiting-review +S-fails-tidy +S-needs-code-changes 

---

Reviewed 1 of 6 files at r11, 8 of 9 files at r15.
Review status: 8 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[python/servo/testing_commands.py, line 293 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10113#-KGNwzEaKAhrBWQQ9Tb8:-KGNwzEbh05Cihhk1znO:-848103749) ([raw file](https://github.com/servo/servo/blob/fb06f2b5fc60f8b26ff09c3c4bd32e6a08bfe907/python/servo/testing_commands.py#L293)):*
We should get rid of these if the tests are working now.

---

*[tests/webdriver/test_content.py, line 16 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10113#-KGNxIo6Fp5YIB_ibJz_:-KGNxIo6Fp5YIB_ibJza:-1769357372) ([raw file](https://github.com/servo/servo/blob/fb06f2b5fc60f8b26ff09c3c4bd32e6a08bfe907/tests/webdriver/test_content.py#L16)):*
Let's add a comment explaining what this test is testing.

---

*[tests/webdriver/test_content.py, line 26 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10113#-KGNx96jBYTpC3QhRnnt:-KGNx96jBYTpC3QhRnnu:2043023549) ([raw file](https://github.com/servo/servo/blob/fb06f2b5fc60f8b26ff09c3c4bd32e6a08bfe907/tests/webdriver/test_content.py#L26)):*
Why raise a different exception? Can't we have an assert without any try/except?

---

*[tests/webdriver/test_emptyurl.py, line 23 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10113#-KGNzDsF3TczUV5Wodno:-KGNzDsGozJC34iX8VGF:367974628) ([raw file](https://github.com/servo/servo/blob/fb06f2b5fc60f8b26ff09c3c4bd32e6a08bfe907/tests/webdriver/test_emptyurl.py#L23)):*
What are we testing here exactly?

---

*[tests/webdriver/test_emptyurl.py, line 27 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10113#-KGNxR330YY_Yf3W9PM9:-KGNxR330YY_Yf3W9PMA:-1649738053) ([raw file](https://github.com/servo/servo/blob/fb06f2b5fc60f8b26ff09c3c4bd32e6a08bfe907/tests/webdriver/test_emptyurl.py#L27)):*
What's the purpose of this commented code?

---

*[tests/webdriver/harness/test_timeout.py, line 28 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10113#-KGNzfFs8WqCdHt7y2hG:-KGNzfFs8WqCdHt7y2hH:-963512810) ([raw file](https://github.com/servo/servo/blob/fb06f2b5fc60f8b26ff09c3c4bd32e6a08bfe907/tests/webdriver/harness/test_timeout.py#L28)):*
This test doesn't really tell us anything useful right now about the webdriver implementation. https://w3c.github.io/webdriver/webdriver-spec.html#sessions says that sessions have a "session page load timeout" - what we'd like to test is that the webdriver server times out after an appropriate amount of time and follows step 6.3 of https://w3c.github.io/webdriver/webdriver-spec.html#go . We should be able to set the page load timeout via https://w3c.github.io/webdriver/webdriver-spec.html#set-timeout to make the test take less than 300 seconds :)

---

*[tests/wpt/harness/wptrunner/executors/webdriver.py, line 423 \[r15\]](https://reviewable.io:443/reviews/servo/servo/10113#-KGO-cSgaPxsAITCNl3o:-KGO-cSgaPxsAITCNl3p:1975474827) ([raw file](https://github.com/servo/servo/blob/fb06f2b5fc60f8b26ff09c3c4bd32e6a08bfe907/tests/wpt/harness/wptrunner/executors/webdriver.py#L423)):*
Let's revert the changes to this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10113#-:-KGO-gHu4huUJfE-Yzxh:-1867917821)*

**Comment by srm912** [comment]
Please ignore. Rebased the branch with `upstream/master`

**Comment by jdm** [comment]
Due to the unaddressed review comments as well as the existence of webdriver tests in https://github.com/w3c/web-platform-tests/, giving us a shared set of tests with other browsers, I'm going to go ahead and close this. Thanks for doing this work!

**Pull request closed without merging**
