### PR TITLE
Support 'flex' and 'flex-flow' shorthand properties

### PR DESCRIPTION
**Pull request by stshine**
Support the `flex` and `flex-flow` shorthand properties in
servo. Currently they are marked as experimental, so they are added to
`__dir__.ini`.
Thanks SimonSapin and jdm for help :)

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11948)

### CODE REVIEW

**Comment by emilio** [comment]
Hi, thanks for doing this!

It looks good to me, I have only left a few comments that need to be addressed, but it looks great! :)

Sorry it took a bit to review btw.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r1, 21 of 21 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/style/properties/shorthand/position.mako.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrq7fpt7hZvoENfSxb:-KLrq7fpt7hZvoENfSxc:1369411626) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L7)):*
> ```Rust
> <%namespace name="helpers" file="/helpers.mako.rs" />
> 
> <%helpers:shorthand name="flex-flow" sub_properties="flex-direction flex-wrap"
> ```

Can you leave a link to the spec above this line? :)

---

*[components/style/properties/shorthand/position.mako.rs, line 18 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrmsI6cS9Vhb7mIQA7:-KLrmsI6cS9Vhb7mIQA8:1549862508) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L18)):*
> ```Rust
>             if let Ok(value) = input.try(|input| flex_direction::parse(context, input)) {
>                 direction = Some(value);
>                 any = true;
> ```

Same here with the variable name as below.

---

*[components/style/properties/shorthand/position.mako.rs, line 42 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrq-C1S9Av42cNMtIH:-KLrq-C1S9Av42cNMtII:-1727256667) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L42)):*
> ```Rust
> </%helpers:shorthand>
> 
> <%helpers:shorthand name="flex" sub_properties="flex-grow flex-shrink flex-basis"
> ```

Here a link would be appreciated too :)

---

*[components/style/properties/shorthand/position.mako.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrlVFfNkff-C5toJbk:-KLrlVFfNkff-C5toJbl:515567573) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L48)):*
> ```Rust
> 
>     pub fn parse_flexibility(input: &mut Parser)
>                              -> Result<(Option<Number>, Option<Number>),()> {
> ```

I think it makes more sense to return `(Number, Option<Number>)`, and add the `Some()` later if needed, but it's not too important.

---

*[components/style/properties/shorthand/position.mako.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrlpFQtZCcTOkFodqO:-KLrlpFQtZCcTOkFodqP:91860341) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L57)):*
> ```Rust
>     let mut shrink = None;
>     let mut basis = None;
>     let mut any = false;
> ```

I guess instead of the `any` variable you can use `grow.is_none() && basis.is_none()`, right?

I'm fine with keeping it, but if that's the case please use a more descriptive variable name, such as `parsed_at_least_one`.

---

*[components/style/properties/shorthand/position.mako.rs, line 85 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrm69Q9evSRZpxzuPz:-KLrm69Q9evSRZpxzuQ-:-1639095076) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L85)):*
> ```Rust
>     }
>     if any {
>         if grow == None {
> ```

Nit: `grow.is_none()` is preferred.

This can be simplified as:

```rust
let grow = grow.unwrap_or(Number(1.0));
let shrink = shrink.unwrap_or(Number(1.0));
...
```

That way all the "logic" related to the longhand sticks in that module, and we only have to care about the shorthand here.

Also, according to [`css-flexbox-1`](https://www.w3.org/TR/css-flexbox-1/#propdef-flex-grow), the default value for `flex_grow` is 0.

---

*[components/style/properties/shorthand/position.mako.rs, line 88 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrpMpPPEfETf5MRbyy:-KLrpMpPPEfETf5MRbyz:517046286) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L88)):*
Hm... I'm confused about this logic. According to https://www.w3.org/TR/css-flexbox-1/#propdef-flex, in the `flex-basis` section:

> When omitted from the flex shorthand, its specified value is 0.

So I don't see the why this logic and the other check.

---

*[tests/wpt/metadata-css/css-flexbox-1_dev/html/percentage-heights-000.htm.ini, line 13 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrnQ3xqqYa1fsItjT5:-KLrnQ3yuVu2ap5CzCms:886079615) ([raw file](https://github.com/servo/servo/blob/c6efbc34e0ad537fd570185085daf3df7db63a1b/tests/wpt/metadata-css/css-flexbox-1_dev/html/percentage-heights-000.htm.ini#L13)):*
> ```INI
> 
>   [.flexbox 4]
>     expected: PASS
> ```

nit: Tests are pass by default, so you should remove all the `[.flexbox 4]` block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11948#-:-KLrnbMP98BAeC939q18:-219692974)*

**Comment by stshine** [comment]
Not at all, thanks for review! The code gets much cleaner with you help :)

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/style/properties/shorthand/position.mako.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrq7fpt7hZvoENfSxb:-KLvd5JCxvqA5Bgo7JVX:-687945316) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L7)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> Can you leave a link to the spec above this line? :)
</details>
Sure, added one line. Same is done for 'flex'.

---

*[components/style/properties/shorthand/position.mako.rs, line 18 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrmsI6cS9Vhb7mIQA7:-KLvhGJkor3ahwONDP9C:-499146009) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L18)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> Same here with the variable name as below.
</details>
Done.

---

*[components/style/properties/shorthand/position.mako.rs, line 42 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrq-C1S9Av42cNMtIH:-KLvhRwlxwBkxo3VC8na:-499146009) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L42)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> Here a link would be appreciated too :)
</details>
Done.

---

*[components/style/properties/shorthand/position.mako.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrlVFfNkff-C5toJbk:-KLvdIXUNzVQVMlz0bSI:-2007866290) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L48)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> I think it makes more sense to return `(Number, Option<Number>)`, and add the `Some()` later if needed, but it's not too important.
</details>
Good point! The logic get simpler with this. done.

---

*[components/style/properties/shorthand/position.mako.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrlpFQtZCcTOkFodqO:-KLvdPz3DSqsOBYfRcFL:331802426) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L57)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> I guess instead of the `any` variable you can use `grow.is_none() && basis.is_none()`, right?
> 
> I'm fine with keeping it, but if that's the case please use a more descriptive variable name, such as `parsed_at_least_one`.
</details>
Hmm sine there are only two values I think your point is quite valid. Done.

---

*[components/style/properties/shorthand/position.mako.rs, line 85 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrm69Q9evSRZpxzuPz:-KLvdwLzg8mbrzATmpf3:-1376579104) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L85)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> Nit: `grow.is_none()` is preferred.
> 
> This can be simplified as:
> 
> ```rust
> let grow = grow.unwrap_or(Number(1.0));
> let shrink = shrink.unwrap_or(Number(1.0));
> ...
> ```
> 
> That way all the "logic" related to the longhand sticks in that module, and we only have to care about the shorthand here.
> 
> Also, according to [`css-flexbox-1`](https://www.w3.org/TR/css-flexbox-1/#propdef-flex-grow), the default value for `flex_grow` is 0.
</details>
Thanks for instruction! I use the `Option.or()` method, And the code get much more cleaner.

As specified here https://drafts.csswg.org/css-flexbox/#valdef-flex-flex-grow , the default value for `flex_grow` in `flex` shorthand is 1.

---

*[components/style/properties/shorthand/position.mako.rs, line 88 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrpMpPPEfETf5MRbyy:-KLvezGWFWfMua5tJpBc:585982366) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L88)):*
This is the basic form `flex: <positive-number>` for `flex` in https://drafts.csswg.org/css-flexbox/#flex-common . 

When there is only a number for `flex` value, it is 
> Equivalent to flex: <positive-number> 1 0. Makes the flex item flexible and sets the flex basis to zero, resulting in an item that receives the specified proportion of the free space in the flex container. If all items in the flex container use this pattern, their sizes will be proportional to the specified flex factor. 

---

*[tests/wpt/metadata-css/css-flexbox-1_dev/html/percentage-heights-000.htm.ini, line 13 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrnQ3xqqYa1fsItjT5:-KLvfbU5krc0ojZXdF1N:-1066636135) ([raw file](https://github.com/servo/servo/blob/c6efbc34e0ad537fd570185085daf3df7db63a1b/tests/wpt/metadata-css/css-flexbox-1_dev/html/percentage-heights-000.htm.ini#L13)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> nit: Tests are pass by default, so you should remove all the `[.flexbox 4]` block.
</details>
Right, removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11948#-:-KLvcDrS_5kPjfUNHjKm:-1908212570)*

**Comment by emilio** [comment]
Only that `flex_basis` when not found in the longhand question, other than that this looks good to me :)

Thanks for doing this again! :)

-S-awaiting-review +S-awaiting-answer 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/properties/shorthand/position.mako.rs, line 85 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrm69Q9evSRZpxzuPz:-KLvvGpmSgpomd7lH_QZ:-256365828) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L85)):*
<details><summary><i>Previously, stshine wrote…</i></summary>
> Thanks for instruction! I use the `Option.or()` method, And the code get much more cleaner.
> 
> As specified here https://drafts.csswg.org/css-flexbox/#valdef-flex-flex-grow , the default value for `flex_grow` in `flex` shorthand is 1.
</details>
Yes, sorry, I read that later while reviewing but forgot to update this comment :)

---

*[components/style/properties/shorthand/position.mako.rs, line 88 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrpMpPPEfETf5MRbyy:-KLvu0_CpK4ZnlGYelHY:-740845474) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L88)):*
Yes, what I meant is: why to specify it to `auto` below, and only use `0` here?

We could just do `flex_basis: basis.unwrap_or(LengthOrPercentageOrAutoOrContent::Length(Length::Absolute(Au(0)))` below, right? If not, care to explain why?

At least, that's my reading of both of the paragraphs in this conversation:

> When omitted from the flex shorthand, its specified value is 0.

and:

> Makes the flex item flexible and sets the flex basis to zero.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11948#-:-KLvwSrjCcIriASmexlX:586971970)*

**Comment by stshine** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/properties/shorthand/position.mako.rs, line 88 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11948#-KLrpMpPPEfETf5MRbyy:-KLw1GKSB26MjDubV2S-:1253203299) ([raw file](https://github.com/servo/servo/blob/7badba01ead797a883e27aa656a9d9051bfd7efb/components/style/properties/shorthand/position.mako.rs#L88)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> Yes, what I meant is: why to specify it to `auto` below, and only use `0` here?
> 
> We could just do `flex_basis: basis.unwrap_or(LengthOrPercentageOrAutoOrContent::Length(Length::Absolute(Au(0)))` below, right? If not, care to explain why?
> 
> At least, that's my reading of both of the paragraphs in this conversation:
> 
> > When omitted from the flex shorthand, its specified value is 0.
> 
> and:
> 
> > Makes the flex item flexible and sets the flex basis to zero.
</details>
YES you are right! A *foolish* mistake made by me for a long time, The note in the spec deceived me  :（ Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11948)*

**Comment by emilio** [comment]
Neat! I don't think there's anything left, thanks once again :)

@bors-servo: r+

-S-awaiting-answer -S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11948#-:-KLwCt-PE-GUpN20T79-:-516955258)*

**Comment by stshine** [comment]
It's my pleasure! Looking forward for your critics and suggestions later.

**Comment by stshine** [comment]
Well this test again.

**Comment by emilio** [comment]
@bors-servo: r+

Thanks for doing this once again! :)

**Pull request merged**
