### PR TITLE
Compute overflow when viewport size changed

### LINKED ISSUE #11120: Text being clipped after window resize
Visualisation of the issue using testcase from #10499:
clipping
Hovering the link triggers #11024, which corrects the issue.

This happens both with and without webrender.

### PR DESCRIPTION
**Pull request by kilobtye**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [X] These changes fix #11120 (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11294)

### CODE REVIEW

**Comment by kilobtye** [comment]
Sorry I accidentally deleted my branch...  caused this pull request closed.

**Comment by mbrubeck** [comment]
@bors-servo r+

Nice work!

**Comment by jdm** [comment]
Could this be tested using an iframe and changing its width?

**Pull request merged**
