### PR TITLE
Remove 'get_*' on getters as per RFC 0344 on canevas, compositing, devtools, gfx, layout, net, profile, servo and webdriver_server

### PR DESCRIPTION
**Pull request by leaexplores**
Hi guys,

I just gave a big pass of RFC-0344 as per issue #6224 .

Pretty much renamed all the get_\* fn that were used to fetch values. 

I hope I didn't rename too much. 

As said in the issue discussion, I didn't touch at the scripts folder so we keep the unsafe ones pretty explicit.

I've ran the whole pass of test, everything seems to be still working right :).

Please give feedback on this PR.

Thanks for looking into it.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7559)

### CODE REVIEW

**Comment by nox** [comment]
@ddrmanxbxfr Didn't expect to see you here. I guess I will take this review.

**Comment by nox** [comment]
Good work. Some nits, and some questions for @mbrubeck. Could you rewrite the commit message when you amend it? You mistyped "canvas" (and its title is a bit long, but that's not very important).

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/compositor.rs, line 577 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygRtDVQ4gwwcXIHlA5)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/compositing/compositor.rs#L577)):</sup>
Is it really important that we signal this function might create the pipeline details? What about just pipeline_details()? @mbrubeck?

---

<sup>**[components/gfx/font_cache_task.rs, line 224 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygTlWSRqDLUJIcRcCe)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/font_cache_task.rs#L224)):</sup>
Not really a getter. The function just above also returns the same optional type and use a "find_" prefix. @mbrubeck?

---

<sup>**[components/gfx/font_cache_task.rs, line 288 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygULFGaKU96HyyWTLu)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/font_cache_task.rs#L288)):</sup>
"find_" maybe? @mbrubeck?

---

<sup>**[components/gfx/font_template.rs, line 91 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygUVsXmpv-JCr9yr3u)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/font_template.rs#L91)):</sup>
"_if_matches" sounds like a bad suffix, it can be used on any method that returns an `Option<T>`. What about just find_font or something like this? @mbrubeck?

---

<sup>**[components/gfx/platform/freetype/font_list.rs, line 30 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZbFJDN3h5WQcGtv6)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/platform/freetype/font_list.rs#L30)):</sup>
I don't like these names, with or without prefix, they don't even return anything! foreach_available_families? @mbrubeck?

---

<sup>**[components/gfx/platform/freetype/font_list.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZbpMCAumICF_Rid3)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/platform/freetype/font_list.rs#L60)):</sup>
I don't like these names, with or without prefix, they don't even return anything! foreach_available_families? @mbrubeck?

---

<sup>**[components/gfx/platform/macos/font_list.rs, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygYjZTeGz_UR9vmV-n)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/platform/macos/font_list.rs#L13)):</sup>
Ditto.

---

<sup>**[components/gfx/platform/macos/font_list.rs, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZVO_citHeg4CuW0s)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/platform/macos/font_list.rs#L23)):</sup>
Ditto.

---

<sup>**[components/net/storage_task.rs, line 140 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZtPfJOxYp9zO6RcK)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/net/storage_task.rs#L140)):</sup>
Weird name, this doesn't actually return anything. send_item? @mbrubeck?

---

<sup>**[components/net_traits/image_cache_task.rs, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-Jyg_8AbtROPSGJvfX_H)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/net_traits/image_cache_task.rs#L114)):</sup>
This _if_available suffix looks as weird as _if_matches. What about dropping it altogether? @mbrubeck?

---

<sup>**[components/servo/lib.rs, line 190 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-Jyg_KDGTbc3b_wuFw9C)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/servo/lib.rs#L190)):</sup>
This doesn't return anything, what does it actually do?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7559)

**Comment by mbrubeck** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/compositor.rs, line 577 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygRtDVQ4gwwcXIHlA5)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/compositing/compositor.rs#L577)):</sup>
Yes, just `pipeline_details` seems fine to me.

---

<sup>**[components/gfx/font_cache_task.rs, line 224 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygTlWSRqDLUJIcRcCe)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/font_cache_task.rs#L224)):</sup>
Agreed.

---

<sup>**[components/gfx/font_cache_task.rs, line 288 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygULFGaKU96HyyWTLu)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/font_cache_task.rs#L288)):</sup>
Agreed.

---

<sup>**[components/gfx/font_template.rs, line 91 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygUVsXmpv-JCr9yr3u)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/font_template.rs#L91)):</sup>
I suggest `data_for_descriptor`

---

<sup>**[components/gfx/platform/freetype/font_list.rs, line 30 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZbFJDN3h5WQcGtv6)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/platform/freetype/font_list.rs#L30)):</sup>
I like `for_each_available_family`

---

<sup>**[components/gfx/platform/freetype/font_list.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZbpMCAumICF_Rid3)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/gfx/platform/freetype/font_list.rs#L60)):</sup>
I suggest `for_each_variation`

---

<sup>**[components/net/storage_task.rs, line 140 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZtPfJOxYp9zO6RcK)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/net/storage_task.rs#L140)):</sup>
I think we can treat this as "returning" an item through the IPC channel.

---

<sup>**[components/net_traits/image_cache_task.rs, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-Jyg_8AbtROPSGJvfX_H)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/net_traits/image_cache_task.rs#L114)):</sup>
Maybe `find_image`?

---

<sup>**[components/servo/lib.rs, line 190 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-Jyg_KDGTbc3b_wuFw9C)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/servo/lib.rs#L190)):</sup>
This sends a `GetPipelineTitle` message requesting the title; the "return" value will come through another message channel.  Perhaps `send_get_title_for_main_frame` would be better.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7559)

**Comment by ddrmanxbxfr** [comment]
Review status: 19 of 28 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

<sup>**[components/net/storage_task.rs, line 140 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZtPfJOxYp9zO6RcK)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/net/storage_task.rs#L140)):</sup>
Seems fine for me.

---

<sup>**[components/net_traits/image_cache_task.rs, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-Jyg_8AbtROPSGJvfX_H)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/net_traits/image_cache_task.rs#L114)):</sup>
It may be interesting to modify ImageCacheCommand::GetImageIfAvailable while we're at it or open a issue for it ? 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7559)

**Comment by ddrmanxbxfr** [comment]
@nox we'll I guess I'll be chipping in and try to learn some rust along the way :)

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer 

@mbrubeck Some last questions for you and I'm done with this review.

---

Reviewed 9 of 9 files at r2.
Review status: 27 of 28 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 140 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZtPfJOxYp9zO6RcK)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/net/storage_task.rs#L140)):</sup>
@mbrubeck I feel like "request_item" or something like that would be better.

---

<sup>**[components/net_traits/image_cache_task.rs, line 114 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-Jyg_8AbtROPSGJvfX_H)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/net_traits/image_cache_task.rs#L114)):</sup>
@ddrmanxbxfr That can be filed as a follow-up, I think.

---

<sup>**[components/servo/lib.rs, line 190 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-Jyg_KDGTbc3b_wuFw9C)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/servo/lib.rs#L190)):</sup>
request_?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7559)

**Comment by mbrubeck** [comment]
-S-awaiting-answer +S-needs-code-changes 

---

Review status: 27 of 28 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 140 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-JygZtPfJOxYp9zO6RcK)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/net/storage_task.rs#L140)):</sup>
I like that. `request_item` works for me.

---

<sup>**[components/servo/lib.rs, line 190 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7559#-Jyg_KDGTbc3b_wuFw9C)** ([raw file](https://github.com/servo/servo/blob/ee55f216b1ded825b2449a33c4d7925298827147/components/servo/lib.rs#L190)):</sup>
Sure. `request_title_for_main_frame` sounds good to me.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7559)

**Comment by nox** [comment]
@ddrmanxbxfr Ping? Almost there! :)

**Comment by ddrmanxbxfr** [comment]
Incoming. 

Had some work rush that got underway :p.

---

Review status: 27 of 28 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7559)

**Comment by ddrmanxbxfr** [comment]
@nox I guess we're safe and sound now... :+1:

**Comment by nox** [comment]
@ddrmanxbxfr Please squash everything together.

**Comment by ddrmanxbxfr** [comment]
@nox ok. done.

**Comment by nox** [comment]
https://github.com/Reviewable/Reviewable/issues/165

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7559)

**Comment by nox** [comment]
```
browser.rs:45:60: 45:86 error: no method named `get_title_for_main_frame` found for type `&servo::Browser` in the current scope
browser.rs:45             ServoBrowser::OnScreen(ref browser) => browser.get_title_for_main_frame(),
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
browser.rs:45:60: 45:86 help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `get_title_for_main_frame`, perhaps you need to implement it:
browser.rs:45:60: 45:86 help: candidate #1: `browser::ServoCefBrowserExtensions`
browser.rs:46:61: 46:87 error: no method named `get_title_for_main_frame` found for type `&servo::Browser` in the current scope
browser.rs:46             ServoBrowser::OffScreen(ref browser) => browser.get_title_for_main_frame(),
                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
browser.rs:46:61: 46:87 help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `get_title_for_main_frame`, perhaps you need to implement it:
browser.rs:46:61: 46:87 help: candidate #1: `browser::ServoCefBrowserExtensions`
error: aborting due to 2 previous errors
```

**Comment by ddrmanxbxfr** [comment]
@nox I just updated the ref tests to make sure they pass using the new function names.

Thanks!

**Comment by nox** [comment]
@bors-servo r+

Thanks for your contribution.

---

Reviewed 32 of 32 files at r5, 30 of 30 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7559)

**Comment by ddrmanxbxfr** [comment]
@nox wait before merging commit https://github.com/ddrmanxbxfr/servo/commit/5db4b09aebbce71b2b3bcd8047d51aba8fd27ec0

Shouldn't be in this branch.. it's open in an other PR...

**Comment by ddrmanxbxfr** [comment]
Rebasing without this commit!

**Comment by ddrmanxbxfr** [comment]
@nox Should be ok with this one. I removed the nits commits. Error on my side while rebasing commits.

**Pull request merged**
