### PR TITLE
style: Cascade custom properties specially in a fast path.

### PR DESCRIPTION
**Pull request by emilio**
When you change a custom property on an element, we need to restyle all children, given custom properties are inherited.

That's usually wasted work, if the element being restyled didn't use any custom property reference. This patch implements a fast path for that.

Do not merge yet, since it's unmeasured so far.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20151)

### CODE REVIEW

**Comment by emilio** [comment]
r? @upsuper 

 * Don't land it straight away, I want to push to talos too.

**Comment by upsuper** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/invalidation/element/restyle_hints.rs, line 51 at r1](https://reviewable.io:443/reviews/servo/servo/20151#-L6TqWO04K1YhvXUvz6U:-L6TqWO04K1YhvXUvz6V:b4iesze) ([raw file](https://github.com/servo/servo/blob/945ebd2f74bf614ef4442fb30eb800f8765acb0d/components/style/invalidation/element/restyle_hints.rs#L51)):*
> ```Rust
>         /// In practice we may end up recascading more because of custom
>         /// property references of course.
>         const RESTYLE_CUSTOM_PROPERTIES = 1 << 7;
> ```

Should be `1 << 8`, shouldn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20151)*

**Comment by emilio** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/invalidation/element/restyle_hints.rs, line 51 at r1](https://reviewable.io:443/reviews/servo/servo/20151#-L6TqWO04K1YhvXUvz6U:-L6Tr-uMeGZTnv9Vo07r:bgnv4t6) ([raw file](https://github.com/servo/servo/blob/945ebd2f74bf614ef4442fb30eb800f8765acb0d/components/style/invalidation/element/restyle_hints.rs#L51)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Should be `1 << 8`, shouldn't it?
</blockquote></details>

Yes, it's fixed, apparently I'm pretty bad at syncing changes across two trees... :(.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20151)*

**Comment by upsuper** [comment]
Hmm... it seems Reviewable somehow gets confused...

**Comment by upsuper** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: 1 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20151)*

**Comment by emilio** [comment]
Try / talos, with a one-liner that fixes the patch set:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=0eb5333b64a41c26232f22a675babec1804f64c5
https://treeherder.mozilla.org/#/jobs?repo=try&revision=01a030d2526da00d7c64e862ab5db22707e28a1c

**Comment by upsuper** [comment]
The talos result doesn't show very encouraging result :/

Probably worth try taking a profile with and without this patch for the modified tpaint test, and check whether any restyle actually becomes faster.

**Comment by upsuper** [comment]
It may also be worth checking whether we do better on testcases in [bug 1417970](https://bugzilla.mozilla.org/show_bug.cgi?id=1417970).

**Comment by emilio** [comment]
So, https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=e5a87d482c43c9c21c156afcf67febda16117b47&newProject=try&newRevision=01a030d2526da00d7c64e862ab5db22707e28a1c&framework=1 is comparing against the same base, w/o patches.

None of the result seem very encouraging. There's a 85% improvement in a test with high confidence, but it's BS, I think. @upsuper if you could double check that'd be awesome, since I can never make any sense of talos :)

**Comment by bholley** [comment]
5 runs generally doesn't say very much, so I wouldn't worry too much about those regressions if there's not an obvious way your patch would slow things down. I'd recommend manually measuring on testcases that should be affected.

**Comment by emilio** [comment]
The test-case from the url of https://bugzilla.mozilla.org/show_bug.cgi?id=1417970 looks much better with this patch, so I think I want to land it.

r? @upsuper

**Comment by upsuper** [comment]
Reviewed 6 of 6 files at r5, 2 of 2 files at r6, 5 of 5 files at r7, 1 of 1 files at r8, 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/properties/properties.mako.rs, line 3687 at r9](https://reviewable.io:443/reviews/servo/servo/20151#-L738Q39IYPZeKJLJTDK:-L738Q39IYPZeKJLJTDL:b6uyxc) ([raw file](https://github.com/servo/servo/blob/60b2d38cde33322832d364d794e72b35f432f72a/components/style/properties/properties.mako.rs#L3687)):*
> ```Rust
>                             .set_uncacheable();
>                     }
>                     context.builder.flags.insert(ComputedValueFlags::HAS_CUSTOM_PROPERTY_REFERENCES);
> ```

It seems to be wrong if you reuse reset properties from rule node, and that includes custom property references. Maybe we should set the flag in `copy_reset_from` if the source has this flag. In that case, this flag should probably be renamed to `MAY_HAVE_CUSTOM_PROPERTY_REFERENCES`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20151)*

**Comment by upsuper** [comment]
It seems to add quite a bit of complexity, and I'm less sure whether it's really worth it...

**Comment by upsuper** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/style/properties/properties.mako.rs, line 2871 at r8](https://reviewable.io:443/reviews/servo/servo/20151#-L73NhCNuSbWIzPeQMKF:-L73NhCPVyIZU9_ZP5Hb:b85fdpu) ([raw file](https://github.com/servo/servo/blob/3ee7b900c968dedaceb2f9f465d5444e06dd83cb/components/style/properties/properties.mako.rs#L2871)):*
> ```Rust
> 
> macro_rules! iter_declarations {
>     ($rule_node:expr, $guards:ident, $restrictions:ident, $empty_small_bit_vec:ident) => {{
> ```

Any reason why this couldn't be a function instead of a macro?

---

*[components/style/properties/properties.mako.rs, line 3330 at r9](https://reviewable.io:443/reviews/servo/servo/20151#-L73Ka0ByaXiR1Gyy0eU:-L73Ka0ByaXiR1Gyy0eV:b-72ized) ([raw file](https://github.com/servo/servo/blob/60b2d38cde33322832d364d794e72b35f432f72a/components/style/properties/properties.mako.rs#L3330)):*
> ```Rust
>                 CustomPropertiesBuilder::new(parent_style.custom_properties());
>             if let Some(ref rules) = old_style.rules {
>                 let restrictions = pseudo.and_then(|p| p.property_restriction());
> ```

It doesn't seem to me restriction is useful here... Custom properties are not restricted anyway, are they?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20151)*

**Comment by upsuper** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/style/style_resolver.rs, line 163 at r9](https://reviewable.io:443/reviews/servo/servo/20151#-L73QpZqTnQTGomDjq2e:-L73QpZqTnQTGomDjq2f:b-uk3wuz) ([raw file](https://github.com/servo/servo/blob/60b2d38cde33322832d364d794e72b35f432f72a/components/style/style_resolver.rs#L163)):*
> ```Rust
> 
>     let primary_style = styles.primary();
>     if style_or_visited_have_custom_property_references(&primary_style) {
> ```

It's not clear to me why do we want to take a full cascade for pseudo if the primary style contains custom property references. Mind explaining a bit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20151)*

**Comment by upsuper** [comment]
It looks mostly fine, but I'm not fully convinced this is worth taking... Maybe @bholley should have a look as well...

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/style/style_resolver.rs, line 163 at r9](https://beta.reviewable.io/reviews/servo/servo/20151#-L73QpZqTnQTGomDjq2e:-L73flGR6qzzgz5pkf7-:bx1elmz) ([raw file](https://github.com/servo/servo/blob/60b2d38cde33322832d364d794e72b35f432f72a/components/style/style_resolver.rs#L163)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

It's not clear to me why do we want to take a full cascade for pseudo if the primary style contains custom property references. Mind explaining a bit?
</blockquote></details>

Because the pseudo-element inherits from the primary style, so its inherited properties may depend on the primary styles' if it had custom property references..

---

*[components/style/properties/properties.mako.rs, line 2871 at r8](https://beta.reviewable.io/reviews/servo/servo/20151#-L73NhCNuSbWIzPeQMKF:-L73gDuh2B_TWH3kzTky:b-il692s) ([raw file](https://github.com/servo/servo/blob/3ee7b900c968dedaceb2f9f465d5444e06dd83cb/components/style/properties/properties.mako.rs#L2871)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Any reason why this couldn't be a function instead of a macro?
</blockquote></details>

You can't specify types that reference a closure in a function signature, and the `impl Trait` syntax is not stable. So I'd need to convert it into an iterator object manually, and when I tried it was just a bunch of effort that didn't seem worth it.

---

*[components/style/properties/properties.mako.rs, line 3330 at r9](https://beta.reviewable.io/reviews/servo/servo/20151#-L73Ka0ByaXiR1Gyy0eU:-L73g6zf-R6SFk-0P_Hf:bz97tk1) ([raw file](https://github.com/servo/servo/blob/60b2d38cde33322832d364d794e72b35f432f72a/components/style/properties/properties.mako.rs#L3330)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

It doesn't seem to me restriction is useful here... Custom properties are not restricted anyway, are they?
</blockquote></details>

It is not, but it allowed me to share more code.

---

*[components/style/properties/properties.mako.rs, line 3687 at r9](https://beta.reviewable.io/reviews/servo/servo/20151#-L738Q39IYPZeKJLJTDK:-L73g9_r7PmZtg9hM7hP:b-mtsubf) ([raw file](https://github.com/servo/servo/blob/60b2d38cde33322832d364d794e72b35f432f72a/components/style/properties/properties.mako.rs#L3687)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

It seems to be wrong if you reuse reset properties from rule node, and that includes custom property references. Maybe we should set the flag in `copy_reset_from` if the source has this flag. In that case, this flag should probably be renamed to `MAY_HAVE_CUSTOM_PROPERTY_REFERENCES`.
</blockquote></details>

Hmm, that's a good point, yeah.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/servo/servo/20151)*

**Comment by emilio** [comment]
Yeah, the point about complexity is fair. I _think_ it's not that bad, or at least it's much better than when I tried in the past, but if you think it's not worth it / really needed I'm happy not taking it.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/servo/servo/20151#-:-L73gb7n6_PPsjMfKvgi:b-stk9sk)*

**Comment by bholley** [comment]
I don't have a strong opinion here, because I don't have a great sense of how custom properties are used in practice. A few questions:
* Is this likely to have any effect on some regular websites, aside from specific testcases where it makes a big difference? If so, we should land it.
* Does Chrome have this optimization? If so, somebody might depend on it, and we should have it too.

Absent clear signals from the above, I probably don't have much input. If you want a tie-breaker, you could ask heycam or dbaron.

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1452525 is a case that should be helped by this, even if not the main issue in that profile.

**Comment by jdm** [comment]
Closing this given that it's been untouched for more than a year and stylo development happens in mozilla-central.

**Pull request closed without merging**
