### PR TITLE
Make no_viewport_percentage! use an absolute path for HasViewportPerc…

### LINKED ISSUE #16781: Make no_viewport_percentage! use an absolute path for HasViewportPercentage
Currently to use `no_viewport_percentage!`, one needs to first import the `HasViewportPercentage` trait in scope. This is a paper cut.

### PR DESCRIPTION
**Pull request by brisad**
…entage

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #16781 

- [X] These changes do not require tests because the compiler warnings should be enough

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16805)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Thanks for doing this!

@bors-servo r+

**Comment by Wafflespeanut** [comment]
error: unused import: `values::HasViewportPercentage`
      --> /home/servo/buildbot/slave/linux-dev/build/components/style/values/specified/align.rs:15:5
       |
    15 | use values::HasViewportPercentage;
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
    note: lint level defined here
      --> /home/servo/buildbot/slave/linux-dev/build/components/style/lib.rs:26:9
       |
    26 | #![deny(warnings)]
       |         ^^^^^^^^

    error: unused import: `values::HasViewportPercentage`
      --> /home/servo/buildbot/slave/linux-dev/build/components/style/values/specified/color.rs:30:9
       |
    30 |     use values::HasViewportPercentage;
       |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    error: aborting due to 2 previous errors

    error: Could not compile `style`.

We should also make sure that `./mach build-geckolib` passes. You can add a `#[cfg(feature = "servo")]` to those imports.

**Comment by brisad** [comment]
Thanks! Seems like the imports weren't needed at all, so I removed them instead.

**Comment by Wafflespeanut** [comment]
Oh cool.

@bors-servo r+

**Pull request merged**
