### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7717)

### CODE REVIEW

**Comment by metajack** [comment]
An explanation for the dupes or removal of the dupes is needed before this should land.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/servo/Cargo.lock, line 651 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7717#-JzuoYGmtYjhzybL9LBa)** ([raw file](https://github.com/servo/servo/blob/6fc66dd905a46acc1229fc9e15840f2182d788ac/components/servo/Cargo.lock#L651)):</sup>
Whoops. This is adding a second copy of gl_generator instead of updating the one we have.

---

<sup>**[components/servo/Cargo.lock, line 897 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7717#-Jzuof6kd8Jz6eSEpdrL)** ([raw file](https://github.com/servo/servo/blob/6fc66dd905a46acc1229fc9e15840f2182d788ac/components/servo/Cargo.lock#L897)):</sup>
Dupe khronos_api added here.

---

<sup>**[ports/cef/Cargo.lock, line 602 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7717#-JzuonwRNYmwAvDvaUx5)** ([raw file](https://github.com/servo/servo/blob/6fc66dd905a46acc1229fc9e15840f2182d788ac/ports/cef/Cargo.lock#L602)):</sup>
dupe

---

<sup>**[ports/cef/Cargo.lock, line 848 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7717#-Jzuopw5Y0xv_2wJ5dbQ)** ([raw file](https://github.com/servo/servo/blob/6fc66dd905a46acc1229fc9e15840f2182d788ac/ports/cef/Cargo.lock#L848)):</sup>
dupe

---

<sup>**[ports/cef/Cargo.lock, line 1870 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7717#-Jzuoy9Y6dgfmHC44N9k)** ([raw file](https://github.com/servo/servo/blob/6fc66dd905a46acc1229fc9e15840f2182d788ac/ports/cef/Cargo.lock#L1870)):</sup>
yay for removing a dupe

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7717)

**Comment by metajack** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7717)

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/servo/Cargo.lock, line 651 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7717#-JzuoYGmtYjhzybL9LBa)** ([raw file](https://github.com/servo/servo/blob/6fc66dd905a46acc1229fc9e15840f2182d788ac/components/servo/Cargo.lock#L651)):</sup>
glutin is apparently very picky about its version of gl_generator.

---

<sup>**[components/servo/Cargo.lock, line 897 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7717#-Jzuof6kd8Jz6eSEpdrL)** ([raw file](https://github.com/servo/servo/blob/6fc66dd905a46acc1229fc9e15840f2182d788ac/components/servo/Cargo.lock#L897)):</sup>
Ditto

---

<sup>**[ports/cef/Cargo.lock, line 602 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7717#-JzuonwRNYmwAvDvaUx5)** ([raw file](https://github.com/servo/servo/blob/6fc66dd905a46acc1229fc9e15840f2182d788ac/ports/cef/Cargo.lock#L602)):</sup>
Ditto

---

<sup>**[ports/cef/Cargo.lock, line 848 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7717#-Jzuopw5Y0xv_2wJ5dbQ)** ([raw file](https://github.com/servo/servo/blob/6fc66dd905a46acc1229fc9e15840f2182d788ac/ports/cef/Cargo.lock#L848)):</sup>
Ditto

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7717)

**Comment by metajack** [comment]
@bors-servo r+

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7717)

**Comment by jdm** [comment]
@bors-servo: retry
* #7422

**Pull request merged**
