### PR TITLE
Add some more tests for gradients

### PR DESCRIPTION
**Pull request by pyfisch**
@jdm proposed to add these tests directly to servo.

@bors-servo try

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17405)

### CODE REVIEW

**Comment by pyfisch** [comment]
Update manifest.

@bors-servo try

**Comment by jdm** [comment]
@bors-servo: retry
* servo-mac5 timed out on a bunch of builds but seems to be working fine now

**Comment by pyfisch** [comment]
Rebased.

@bors-servo: try

**Comment by jdm** [comment]
@bors-servo: retry
Weird manifest check failure.

**Comment by jdm** [comment]
@bors-servo: retry
* something strange is happening with the http server on the mac builders

**Pull request merged**
