### PR TITLE
layout_2020: Specify the used cross size when replaced item is stretched

### LINKED ISSUE #29788: Images in flexbox are not rendered properly
For example, Make a flex container with 200x200 dimensions, having a image of 100x100 dimensions inside:

```html
<!DOCTYPE html>
<html>
  <head>
    <style>
     .container {
         display: flex;
         width: 200px;
         height: 200px;
     }
    </style>
  </head>
  <body>
    <div class="container">
      <img alt="" src="support/100x100-green.png"/>
    </div>
    Hello
  </body>
</html>
```

The image is rendered as 100px square, while it should be a 200px square.

### PR DESCRIPTION
**Pull request by stshine**
According to spec, if the flex item has [align-self: stretch](https://drafts.csswg.org/css-flexbox/#propdef-align-self), redo layout for its contents, treating this used size as its definite cross size so that percentage-sized children can be resolved.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #29788  (GitHub issue number if applicable)

- [x] There are tests for these changes OR

### CODE REVIEW

**Comment by stshine** [comment]
These failed tests are using column flexbox, so they are just false-positives.
This pull request is ready for review.

**Review by Loirooriol — APPROVED** [review]
Seems reasonable

**Comment by stshine** [comment]
Test expectations updated. Thanks!###

**Pull request merged**
