### PR TITLE
Refactor WebGLPaintTask to prevent creating extra IPC channels - Issu…

### LINKED ISSUE #9228: Refactor WebGLPaintTask to prevent creating extra IPC channels
Right now we create an IPC channel when we create a `WebGLPaintTask`. 

When the context creation fails, this channel is not returned and thus created in vain.

The mspc channel is necessary, since the task makes use of it, but it should be easy to wait until we know the task has succeeded to create the IPC channel.

Code: https://github.com/servo/servo/blob/master/components/canvas/webgl_paint_task.rs#L188-L234

### PR DESCRIPTION
**Pull request by coder543**
closes #9228

and this time I have a separate branch.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9234)

### CODE REVIEW

**Comment by KiChjang** [comment]
Fails tidy:
```
./components/canvas/webgl_paint_task.rs:233: trailing whitespace
```

NB: You can run `./mach test-tidy` locally to check whether your source files are conforming to tidy rules.

**Comment by nox** [comment]
I'm pretty sure @ecoal95 meant to initialise the IPC channel in the last `.map(|_| …)` call in that function. You are still creating the channel for nothing if the context couldn't be initialised.

**Comment by ecoal95** [comment]
Yep, @nox is correct, you still always create the IPC channel.

It should be done if the `recv()` receives an `Ok` value, that is,
in the last `.map` call.

**Comment by ecoal95** [comment]
@coder543 Was this closed on purpose? You can rebase without creating a new PR, I'm happy to help you to do that if you want :P

**Comment by coder543** [comment]
Yeah, I was up to the 3 or 4 commit mark, a commit last night renamed all Tasks to Threads, and after rebasing I realized I needed to make another commit just to handle some whitespace issues. Things were getting messy. I know there's a way to squash commits, but I've never done that before, so I just cloned `master` again and pasted in my changes. Now there is only one commit in a new pull request... sorry about the number of PRs this has caused.

**Comment by ecoal95** [comment]
@coder543 No problem! :-)

**Comment by nox** [comment]
@coder543 Feel free to come on IRC, we can help you with Git.

**Pull request closed without merging**
