### PR TITLE
HoloLens URL handler

### PR DESCRIPTION
**Pull request by paulrouget**
Handles servo URLS. For example, in any browser, a link to `servo://https://servo.org` will load `https://servo.org` will open and load the servo app.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24008)

### CODE REVIEW

**Comment by paulrouget** [comment]
Depends on #23981

Fixes #23974 and #23908

**Review by jdm — APPROVED** [review]

**Comment by paulrouget** [comment]
> Can we return a unique_ptr so this is freed automatically?

I guess. As long as internally we don't store the str.

**Pull request merged**
