### PR TITLE
Use iterators for iterating through CSS rules

### PR DESCRIPTION
**Pull request by luniv**

### CODE REVIEW

**Comment by luniv** [comment]
Rebased + squashed version of #5513

**Comment by SimonSapin** [comment]
```
/home/servo/buildbot/slave/linux1/build/tests/unit/style/media_queries.rs:6:26: 6:53 error: unresolved import `style::stylesheets::iter_stylesheet_media_rules`. There is no `iter_stylesheet_media_rules` in `style::stylesheets`
/home/servo/buildbot/slave/linux1/build/tests/unit/style/media_queries.rs:6 use style::stylesheets::{iter_stylesheet_media_rules, iter_stylesheet_style_rules, Stylesheet};
                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux1/build/tests/unit/style/media_queries.rs:6:55: 6:82 error: unresolved import `style::stylesheets::iter_stylesheet_style_rules`. There is no `iter_stylesheet_style_rules` in `style::stylesheets`
/home/servo/buildbot/slave/linux1/build/tests/unit/style/media_queries.rs:6 use style::stylesheets::{iter_stylesheet_media_rules, iter_stylesheet_style_rules, Stylesheet};
                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
```

This is probably because this was rebased across the move of unit tests to a separate crate.

**Comment by luniv** [comment]
I've pushed a fix-up commit that fixes the error.

**Pull request merged**
