### PR TITLE
Update to quickersort 2.2

### PR DESCRIPTION
**Pull request by notriddle**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14652)

### CODE REVIEW

**Comment by KiChjang** [comment]
Woah, that's a minor version change, did any interface break?

**Comment by notriddle** [comment]
Not that I know of. I didn't modify any of the tests, and they all pass.

**Comment by KiChjang** [comment]
wat
```
Tests with unexpected results:
  ▶ PASS [expected TIMEOUT] /css-flexbox-1_dev/html/css-flexbox-height-animation-stretch.htm
```
@notriddle Is this actually possible or is this an actual intermittent?

**Comment by notriddle** [comment]
According to #12328, that should be impossible.

**Comment by notriddle** [comment]
I'm willing to believe it's an intermittent, though. Everything else is.

**Comment by KiChjang** [comment]
Filed #14656 for the new passing intermittent.

**Pull request merged**
