### PR TITLE
clippy: components/script/realms

### PR DESCRIPTION
**Pull request by remysaissy**
Fixes a clippy::self_named_constructors in realms.rs.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes are part of #31500 

- [X] These changes do not require tests because they do not modify functionality, they only fix lint errors.

### CODE REVIEW

**Review by gterzian — APPROVED** [review]
Thank you! Not sure if you want to close the issue though...

**Comment by mrobinson** [comment]
I adjusted the PR message so that the issue is not automatically closed.

@remysaissy Thanks so much for the clippy warning fixes, but maybe just write " These changes are part of #31500" so that the issue isn't closed automatically by GitHub. We shouldn't close the issue until all the warnings are fixed.

**Comment by remysaissy** [comment]
> * These changes are part of [Fix as many clippy problems as possible #31500](https://github.com/servo/servo/issues/31500)

You're welcome, this is a great way to understand a bit better how servo works. thanks for having these beginner issues.

I don't understand what I should write to avoid automatic close.
In the description, I've put 
These changes are part of https://github.com/servo/servo/issues/31500 and These changes do not require tests because they do not modify functionality, they only fix lint errors by following the PR template.

Do you mean that I should update the description to have only one line?

Thanks!

**Comment by remysaissy** [comment]
> I adjusted the PR message so that the issue is not automatically closed.
> 
> @remysaissy Thanks so much for the clippy warning fixes, but maybe just write "These changes are part of #31500" so that the issue isn't closed automatically by GitHub. We shouldn't close the issue until all the warnings are fixed.

You're welcome, this issue is a great way to understand better how servo works, thanks for it!

I didn't understand the fix/part of subtlety in the description at first, I will do as you say for the future PRs.
Thanks!

**Pull request merged**
