### PR TITLE
Respect the composition op when drawing images.

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6989)

### CODE REVIEW

**Comment by jdm** [comment]
```
/2dcontext/drawing-images-to-the-canvas/2d.drawImage.broken.html
----------------------------------------------------------------
FAIL Canvas test: 2d.drawImage.broken
/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.emptysrc.html
-----------------------------------------------------------------------------
FAIL Canvas test: 2d.drawImage.incomplete.emptysrc
/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.immediate.html
------------------------------------------------------------------------------
FAIL Canvas test: 2d.drawImage.incomplete.immediate
/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.nosrc.html
--------------------------------------------------------------------------
FAIL Canvas test: 2d.drawImage.incomplete.nosrc
/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.reload.html
---------------------------------------------------------------------------
FAIL Canvas test: 2d.drawImage.incomplete.reload
/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.removedsrc.html
-------------------------------------------------------------------------------
FAIL Canvas test: 2d.drawImage.incomplete.removedsrc
```

**Comment by dzbarsky** [comment]
Not sure what's going on here, those tests were passing locally. I guess we can try landing without them.

**Comment by dzbarsky** [comment]
For what it's worth it makes no sense that this change would cause those tests to suddently pass...

**Comment by metajack** [comment]
@bors-servo r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 14 of 14 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6989)

**Comment by jdm** [comment]
```
/css21_dev/html4/c536-bgpos-001.htm
-----------------------------------
TIMEOUT expected FAIL [Parent]
```

**Comment by dzbarsky** [comment]
I can't reproduce this failure locally and it seems unrelated. What do you think?

**Comment by jdm** [comment]
Agreed.

**Comment by jdm** [comment]
@bors-servo: retry
* #7022

**Pull request merged**
