### PR TITLE
Make the dom module private.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11672)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer 

<details><summary><i>Previously, highfive wrote…</i></summary>
> Heads up! This PR modifies the following files:
>  * @kichjang: components/script/test.rs, components/script/dom/nodeiterator.rs, components/script/dom/webglframebuffer.rs, components/script/dom/webglshaderprecisionformat.rs, components/script/dom/filereader.rs, components/script/dom/beforeunloadevent.rs, components/script/dom/webgltexture.rs, components/script/dom/workerglobalscope.rs, components/script/dom/htmlmediaelement.rs, components/script/dom/htmltablecellelement.rs, components/script/dom/webglobject.rs, components/script/dom/webglbuffer.rs, components/script/dom/htmltextareaelement.rs, components/script/dom/webidls/WebGLObject.webidl, components/script/dom/bindings/mod.rs, components/script/lib.rs, components/script/dom/stylesheet.rs, components/script/dom/validitystate.rs, components/script/dom/abstractworker.rs, components/script/dom/mod.rs, components/script/dom/radionodelist.rs, components/script/dom/htmlformelement.rs, components/script/dom/webglrenderingcontext.rs, components/script/dom/webglrenderbuffer.rs, components/script/dom/domexception.rs
>  * @emilio: components/script/dom/webglframebuffer.rs, components/script/dom/webglshaderprecisionformat.rs, components/script/dom/webgltexture.rs, components/script/dom/webglobject.rs, components/script/dom/webglbuffer.rs, components/script/dom/webglrenderingcontext.rs, components/script/dom/webglrenderbuffer.rs
</details>


---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 22 of 22 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/dom/beforeunloadevent.rs, line 5 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11672#-KJk5Fp7B1mRV916WnSV:-KJk5Fp7B1mRV916WnSW:677194780) ([raw file](https://github.com/servo/servo/blob/8541d800c42f6a0201642d7c4eacf96d090876de/components/script/dom/beforeunloadevent.rs#L5)):*
> ```Rust
>  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
> 
> #![allow(dead_code)]
> ```

Why?

---

*[components/script/dom/filereader.rs, line 378 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11672#-KJk5INRA_RuJFgEepXa:-KJk5INRA_RuJFgEepXb:677194780) ([raw file](https://github.com/servo/servo/blob/8541d800c42f6a0201642d7c4eacf96d090876de/components/script/dom/filereader.rs#L378)):*
> ```Rust
>     ProcessRead(TrustedFileReader, GenerationId),
>     ProcessReadData(TrustedFileReader, GenerationId),
>     #[allow(dead_code)]
> ```

Why?

---

*[components/script/dom/htmlformelement.rs, line 689 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11672#-KJk5JbGf6QmJAb3MELy:-KJk5JbGf6QmJAb3MELz:677194780) ([raw file](https://github.com/servo/servo/blob/8541d800c42f6a0201642d7c4eacf96d090876de/components/script/dom/htmlformelement.rs#L689)):*
> ```Rust
> 
> pub enum FormDatumValue {
>     #[allow(dead_code)]
> ```

Why?

---

*[components/script/dom/htmlformelement.rs, line 725 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11672#-KJk5Kj3At3z8M5y3Vv2:-KJk5Kj3At3z8M5y3Vv3:677194780) ([raw file](https://github.com/servo/servo/blob/8541d800c42f6a0201642d7c4eacf96d090876de/components/script/dom/htmlformelement.rs#L725)):*
> ```Rust
> 
> #[derive(HeapSizeOf)]
> #[allow(dead_code)]
> ```

Why?

---

*[components/script/dom/stylesheet.rs, line 5 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11672#-KJk5N-kja1NxGTW43Sz:-KJk5N-kja1NxGTW43T-:677194780) ([raw file](https://github.com/servo/servo/blob/8541d800c42f6a0201642d7c4eacf96d090876de/components/script/dom/stylesheet.rs#L5)):*
> ```Rust
>  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
> 
> #![allow(dead_code)]
> ```

Why?

---

*[components/script/dom/validitystate.rs, line 15 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11672#-KJk5O3TGjaCrLzNi6UZ:-KJk5O3TGjaCrLzNi6U_:677194780) ([raw file](https://github.com/servo/servo/blob/8541d800c42f6a0201642d7c4eacf96d090876de/components/script/dom/validitystate.rs#L15)):*
> ```Rust
> // https://html.spec.whatwg.org/multipage/#validity-states
> #[derive(JSTraceable, HeapSizeOf)]
> #[allow(dead_code)]
> ```

Why?

---

*[components/script/dom/webglshaderprecisionformat.rs, line 5 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11672#-KJk5PyffHI6csi68cbL:-KJk5PyffHI6csi68cbM:677194780) ([raw file](https://github.com/servo/servo/blob/8541d800c42f6a0201642d7c4eacf96d090876de/components/script/dom/webglshaderprecisionformat.rs#L5)):*
> ```Rust
>  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
> 
> #![allow(dead_code)]
> ```

Why?

---

*[components/script/dom/bindings/mod.rs, line 131 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11672#-KJk5RRX_X3pbN3hT1OB:-KJk5RRX_X3pbN3hT1OC:677194780) ([raw file](https://github.com/servo/servo/blob/8541d800c42f6a0201642d7c4eacf96d090876de/components/script/dom/bindings/mod.rs#L131)):*
> ```Rust
> //! (error/enum.Error.html).
> 
> #![allow(dead_code)]
> ```

Why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11672#-:-KJk5XIApvXhC_onmhcd:453359453)*

**Comment by samlh** [comment]
https://llvm.org/bugs/show_bug.cgi?id=24234 ?

**Comment by nox** [comment]
This didn't fail again with LLVM error.

@bors-servo r+

**Comment by jdm** [comment]
```
LLVM ERROR: fixup value out of range
error: Could not compile `script`.
```

**Pull request merged**
