### PR TITLE
Fix #7855 Implement port blocking For WebSocket connection algorithm

### LINKED ISSUE #7855: Implement port blocking for WebSocket connection algorithm
The [connection algorithm](https://html.spec.whatwg.org/multipage/comms.html#dom-websocket) contains a step 4 that says we should throw an exception if the port is blacklisted. This is currently missing from our implementation, which causes `./mach test-wpt tests/wpt/web-platform-tests/websockets/Create-Secure-blocked-port.htm` to fail (hence `tests/wpt/metadata/websockets/Create-Secure-blocked-port.htm.ini` contains an expected failure). Let's copy Gecko's [list of blacklisted ports](http://mxr.mozilla.org/mozilla-central/source/netwerk/base/nsIOService.cpp#85) and fix the test failure!

Code: components/script/dom/websocket.rs

### PR DESCRIPTION
**Pull request by vectorijk**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7889)

### CODE REVIEW

**Comment by jdm** [comment]
Looking good!
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[components/script/dom/websocket.rs, line 143 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7889#-K-xVnnqRsQmk2jN-7TC)** ([raw file](https://github.com/servo/servo/blob/4e4a90f90cf8b23f1c271608ada728ef552e42e0/components/script/dom/websocket.rs#L143)):</sup>
Let's make this a `const` value and declare it globally outside of this method, since it makes it much longer :)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7889)

**Comment by vectorijk** [comment]
<sup>**[components/script/dom/websocket.rs, line 143 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7889#-K-xVnnqRsQmk2jN-7TC)** ([raw file](https://github.com/servo/servo/blob/4e4a90f90cf8b23f1c271608ada728ef552e42e0/components/script/dom/websocket.rs#L143)):</sup>
I was wondering if you could give me some clues how to make it globally. Do you mean making this array parallel with  `enum` and `struct`?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7889)

**Comment by jdm** [comment]
```rust
const blocked_ports_list: &[u16] = &[...];
impl WebSocketMethods for WebSocket {
    fn Send(&self) {
         blocked_ports_list.iter()...
    }
}
```
should do the trick.

**Comment by vectorijk** [comment]
rebased and make BLOCKED_PORTS_LIST `const`

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for implementing this!


---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7889)

**Pull request merged**
