### PR TITLE
Upgrade clang to 9.0 on Windows.

### PR DESCRIPTION
**Pull request by jdm**
This is required for building with the latest versions of Visual Studio 2019.

### CODE REVIEW

**Comment by jdm** [comment]
@ors-servo r=asajeffrey

**Comment by ferjm** [comment]
@bors-servo retry
- #25513

**Comment by ferjm** [comment]
@bors-servo retry
- #26192

**Comment by ferjm** [comment]
@bors-servo retry
- #25513 
- #26192

**Pull request merged**
