### PR TITLE
Make unsafe

### LINKED ISSUE #16868: Clean up unsafe Document methods
All the methods taking `*mut JSRuntime`, such as `handle_mouse_event` and friends should be `unsafe`, because they take a raw pointer and do dangerous things with it.

### PR DESCRIPTION
**Pull request by teymour-aldridge**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #16868 (GitHub issue number if applicable) (maybe – I'm not sure)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because ___

### CODE REVIEW

**Review by jdm — CHANGES_REQUESTED** [review]
Thanks for doing this work! I think I see an improvement that's possible, however - if we modify the functions to accept a `&Runtime` argument instead, we can call `runtime.rt()` inside the methods and they can be called from safe code again.

**Comment by teymour-aldridge** [comment]
I've just been looking at the code again, and it might be possible to actually remove the argument entirely? It seems to be passed only to `from_untrusted_node_address` which doesn't use it (as far as I can see).

**Comment by jdm** [comment]
That's even better!

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Pull request merged**
