### PR TITLE
compositing/script: Do not dispatch the resize event when initially l…

### PR DESCRIPTION
**Pull request by notriddle**
…oading.

No bug report corresponds to this, but I noticed it while trying to
reduce #10593

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10654)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Do you have a spec to back this up?

**Comment by pcwalton** [comment]
I don't think we need a spec cite for this, because it makes us stop doing something that the spec does not require us to do and that is nonsensical to begin with. (That is, this essentially corrects a pre-existing spec violation.)

**Comment by notriddle** [comment]
You're only supposed to fire the event if the window size has changed since the last time the [run the resize steps](https://drafts.csswg.org/cssom-view/#resizing-viewports) algorithm has been run. This is clearly false the first time the algorithm runs.

**Comment by pcwalton** [comment]
compositing changes look fine to me.

**Comment by notriddle** [comment]
Is there something wrong with the script part?

**Comment by asajeffrey** [comment]
A probably dumb question... why have the compositor send a window size message with type `Initial`, rather than just have the window track whether it's had its initial size set? It seems like the code would be simpler if we just had script keep track of this.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10654#-:-KFfN_wb_db8WErnal_C:1177015819)*

**Comment by notriddle** [comment]
The compositor knows how the message is supposed to be treated; it would be bad if the script were silently out of sync with that expectation. I admit it's just a heuristic "explicit is better than implicit" choice.

I can change it, if you would prefer it the other way.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10654#-:-KFfur8hfko7SBthmwRI:1330632316)*

**Comment by asajeffrey** [comment]
It's just a question of who keeps track of that bit of state -- the compositor (as you have it) or script (by keeping track of an optional size). Personally I prefer the latter, but this is just taste.

@notriddle would you like me to finish doing the code review?

**Comment by notriddle** [comment]
I'd say yeah, finish the code review.

**Comment by asajeffrey** [comment]
OK, looks good. If we're going to go with the compositor rather than script deciding which is the initial size, then this seems a good implementation. r=me if so.

---

Reviewed 1 of 8 files at r1, 1 of 1 files at r2, 5 of 6 files at r3.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10654#-:-KFkp3TnmCuc39kqpc8L:-796723758)*

**Comment by asajeffrey** [comment]
Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10654)*

**Comment by notriddle** [comment]
Still awaiting answer?

**Comment by asajeffrey** [comment]
@bors-servo retry
* test for intermittent

**Comment by asajeffrey** [comment]
Okay, it looks like that's a real test failure. @notriddle, any ideas?

**Comment by notriddle** [comment]
Incremental reflow bug; it passed because it relied on the `force_reflow` that happened after the resize event.

**Comment by asajeffrey** [comment]
@notriddle we had a test which relied on the old behaviour, hmm... Is it easy to patch the test?

**Comment by notriddle** [comment]
* #10660

**Comment by notriddle** [comment]
Pinging @asajeffrey

**Comment by asajeffrey** [comment]
Oops. Minor nit below.

---

Reviewed 3 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[components/script/script_thread.rs, line 1032 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10654#-KFySRfHEylnQM5N6pSR:-KFySRfISAtNtTzd0CIF:478011413) ([raw file](https://github.com/servo/servo/blob/3e18116845dd02e723446c7cce56f3a3614dfd3b/components/script/script_thread.rs#L1032)):*
Does this reflow happen in the `Resize` case too? Should the `force_reflow` be moved out of the `if`? The code reads a bit oddly, like the reflow is only happening on initial sizing, not on resizing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10654#-:-KFySz6e36UYnw2zjFkk:-117109335)*

**Comment by notriddle** [comment]
*[components/script/script_thread.rs, line 1032 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10654#-KFySRfHEylnQM5N6pSR:-KFz_u5lDNayi-ehy_Ig:-2017399758) ([raw file](https://github.com/servo/servo/blob/3e18116845dd02e723446c7cce56f3a3614dfd3b/components/script/script_thread.rs#L1032)):*
You're right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10654)*

**Comment by notriddle** [comment]
*[components/script/script_thread.rs, line 1032 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10654#-KFySRfHEylnQM5N6pSR:-KFzgAwV_RaxyOfkFCZm:-499146009) ([raw file](https://github.com/servo/servo/blob/3e18116845dd02e723446c7cce56f3a3614dfd3b/components/script/script_thread.rs#L1032)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10654)*

**Comment by asajeffrey** [comment]
:lgtm:

@bors-servo r+

---

Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10654#-:-KFzh5uMZnXhos1VfJJ9:-2042399280)*

**Pull request merged**
