### PR TITLE
style: Add support to test animations programatically.

### LINKED ISSUE #12120: How to test transitions/animations?
As animation support increases, it'd be great to have some sort of testing support for it.

We can't test them deteministically right now. Gecko has a "test mode" in their refresh driver that allows them to fake the times, advance the clocks, etc. as well as an API to get the computed style for an element in a given point of time.

We don't have that infra, and though it seems like a good amount of work, I think it's worth doing.

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12120 

- [x] There are tests for these changes OR

r? @SimonSapin for the style changes, @Ms2ger or @jdm for the dom and test changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12392)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Reviewed 2 of 2 files at r1, 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/servo/Cargo.lock, line 1168 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12392#-KMUaJdVWi8MXUNKjj5r:-KMUaJdVWi8MXUNKjj5s:1476489752) ([raw file](https://github.com/servo/servo/blob/9e010a8aec7f99fd15bf6334f84c39a3229d115f/components/servo/Cargo.lock#L1168)):*
> ```
>  "style 0.0.1",
>  "style_traits 0.0.1",
>  "time 0.1.35 (registry+https://github.com/rust-lang/crates.io-index)",
> ```

You probably want to run something like `./mach cargo-update -p layout` to update `ports/cef/Cargo.lock`.

---

*[components/style/matching.rs, line 461 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12392#-KMUbHRwOq8OvPQVnwf3:-KMUbHRxnsnqaxIqvjel:-1955296938) ([raw file](https://github.com/servo/servo/blob/5349d14d3322e22d727085def5b60d152662cfe0/components/style/matching.rs#L461)):*
> ```Rust
>                                      context: &SharedStyleContext<<Self::ConcreteElement as Element>::Impl>,
>                                      style: &mut Option<&mut
>                                      Arc<Self::ConcreteComputedValues>>)
> ```

This is an usual place to insert a line break. Is it needed at all?

---

*[components/style/timer.rs, line 52 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12392#-KMUbhMZ8cFIQeNa0Djf:-KMUbhM_zpAgAy0pTVC6:271197962) ([raw file](https://github.com/servo/servo/blob/5349d14d3322e22d727085def5b60d152662cfe0/components/style/timer.rs#L52)):*
> ```Rust
>         if let TimerMode::Test(ref mut val) = self.mode {
>             *val += by;
>         }
> ```

Should this panic in non-test mode? I think an `else { panic!(…) }` here could replace the assertion in `handle_advance_clock_ms`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12392)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/servo/Cargo.lock, line 1168 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12392#-KMUaJdVWi8MXUNKjj5r:-KMVkD_b8HEvofUB3Ji3:676635175) ([raw file](https://github.com/servo/servo/blob/9e010a8aec7f99fd15bf6334f84c39a3229d115f/components/servo/Cargo.lock#L1168)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> You probably want to run something like `./mach cargo-update -p layout` to update `ports/cef/Cargo.lock`.
</details>
Done

---

*[components/style/matching.rs, line 461 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12392#-KMUbHRwOq8OvPQVnwf3:-KMVk7hkduaxNWvIA0Ki:-1736987012) ([raw file](https://github.com/servo/servo/blob/5349d14d3322e22d727085def5b60d152662cfe0/components/style/matching.rs#L461)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> This is an usual place to insert a line break. Is it needed at all?
</details>
Whoops, sorry, bad autoformatting :)

---

*[components/style/timer.rs, line 52 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12392#-KMUbhMZ8cFIQeNa0Djf:-KMVkBVhz4K7NyYJ0pOo:-131377525) ([raw file](https://github.com/servo/servo/blob/5349d14d3322e22d727085def5b60d152662cfe0/components/style/timer.rs#L52)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Should this panic in non-test mode? I think an `else { panic!(…) }` here could replace the assertion in `handle_advance_clock_ms`.
</details>
Makes sense, done :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12392)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12392#-:-KN6EZwhX1x4xPcm1N8f:1236647940)*

**Pull request merged**
