### PR TITLE
Move LayerKind and ScrollPolicy enums to gfx_traits

### LINKED ISSUE #8836: Move LayerKind and ScrollPolicy enums to gfx_traits
These are only used by code in `layout/`, `gfx/`, and `compositing/`, so they're good candidates to move out of the grab-bag `msg/` crate.

Code: `components/msg/compositor_msg.rs`, `components/gfx_traits/lib.rs`, and other files in http://mxr.mozilla.org/servo/search?string=scrollpolicy and http://mxr.mozilla.org/servo/search?string=layerkind

### PR DESCRIPTION
**Pull request by nerith**
Fixes #8836.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8938)

### CODE REVIEW

**Comment by KiChjang** [comment]
It looks like you need to do a `./mach update-cargo -p gfx_traits`

**Comment by jdm** [comment]
@nerith: Could you try an experiment for me? It looks like it might be possible to move LayerId and LayerProperties into gfx_traits, which would allow us to remove the new dependency in `msg` on `gfx_traits`.

**Comment by nerith** [comment]
@jdm: It is possible to move LayerId and LayerProperties into gfx_traits. This also includes moving ScriptToCompositorMsg.

**Comment by jdm** [comment]
@nerith Could we move ScriptToCompositorMsg to script_traits and make script_traits depend on gfx_traits? If so, that would be my preferred solution. If not, go ahead and push the changes with everything moved to gfx_traits.

**Comment by jdm** [comment]
Looks like my last comment is addressed by #9027, so we can rebase on top of that when it merges.

**Comment by Ms2ger** [comment]
Does `gfx_traits` need to depend on `util`? That would be nice to avoid.

**Comment by jdm** [comment]
It looks like the answer to that is no, since there's no `use util` lines in the diff.

**Comment by nerith** [comment]
@Ms2ger @jdm If the dependency on `util` is removed, ` gfx_traits` can't be compiled.

```
servo/components/gfx_traits/lib.rs:42:69: 42:73 error: failed to resolve. Maybe a missing `extern crate util`? [E0433]
servo/components/gfx_traits/lib.rs:42 #[derive(Clone, PartialEq, Eq, Copy, Deserialize, Serialize, Debug, HeapSizeOf)]
                                                                                                          ^~~~
servo/components/gfx_traits/lib.rs:42:69: 42:79 note: in this expansion of #[derive_HeapSizeOf] (defined in servo/components/gfx_traits/lib.rs)
servo/components/gfx_traits/lib.rs:42:69: 42:73 help: run `rustc --explain E0433` to see a detailed explanation
servo/components/gfx_traits/lib.rs:42:69: 42:79 error: use of undeclared trait name `util::mem::HeapSizeOf` [E0405]
servo/components/gfx_traits/lib.rs:42 #[derive(Clone, PartialEq, Eq, Copy, Deserialize, Serialize, Debug, HeapSizeOf)]
                                                                                                          ^~~~~~~~~~
servo/components/gfx_traits/lib.rs:42:69: 42:79 note: in this expansion of #[derive_HeapSizeOf] (defined in servo/components/gfx_traits/lib.rs)
servo/components/gfx_traits/lib.rs:42:69: 42:79 help: run `rustc --explain E0405` to see a detailed explanation
servo/components/gfx_traits/lib.rs:50:68: 50:72 error: failed to resolve. Maybe a missing `extern crate util`? [E0433]
servo/components/gfx_traits/lib.rs:50 #[derive(Clone, PartialEq, Eq, Copy, Hash, Deserialize, Serialize, HeapSizeOf)]
                                                                                                         ^~~~
servo/components/gfx_traits/lib.rs:50:68: 50:78 note: in this expansion of #[derive_HeapSizeOf] (defined in servo/components/gfx_traits/lib.rs)
servo/components/gfx_traits/lib.rs:50:68: 50:72 help: run `rustc --explain E0433` to see a detailed explanation
servo/components/gfx_traits/lib.rs:50:68: 50:78 error: use of undeclared trait name `util::mem::HeapSizeOf` [E0405]
servo/components/gfx_traits/lib.rs:50 #[derive(Clone, PartialEq, Eq, Copy, Hash, Deserialize, Serialize, HeapSizeOf)]
                                                                                                         ^~~~~~~~~~
servo/components/gfx_traits/lib.rs:50:68: 50:78 note: in this expansion of #[derive_HeapSizeOf] (defined in servo/components/gfx_traits/lib.rs)
servo/components/gfx_traits/lib.rs:50:68: 50:78 help: run `rustc --explain E0405` to see a detailed explanation
error: aborting due to 4 previous errors
Could not compile `gfx_traits`.
```

**Comment by Ms2ger** [comment]
Sigh. Thanks for checking.

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo: r+
Thanks @nerith!

**Pull request merged**
