### PR TITLE
Update to Rust 1.10.0-nightly (2b79e05a0 2016-05-13)

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11183)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo: r+

<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> #### Update to Rust 1\.10\.0\-nightly \(2b79e05a0 2016\-05\-13\)
> 
> 
> 
> 
> </details>


---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11183#-:-KHkjFNF_F9eml1NoNqG:-317921516)*

**Comment by nox** [comment]
@bors-servo retry force

Git issues.

**Pull request merged**
