### PR TITLE
Minor script::dom::window::Window cleanup

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7613)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

Just two small nits, the first one you decide whether it's important to keep ScaleFactor around in the expression, it might help understanding the code after all.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/window.rs, line 753 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7613#-Jz0l5QkjOuoSwfmdoRn)** ([raw file](https://github.com/servo/servo/blob/0070c4e4a65a910d31ee47e5a4eafbb2f3de94dd/components/script/dom/window.rs#L753)):</sup>
Bikeshedding at its best, but I think you can do `self.window_size.get().map(|data| data.device_pixel_ratio.get()).unwrap_or(1.0f32)`.

---

<sup>**[components/script/dom/window.rs, line 1060 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7613#-Jz0kuHShEmcNKgdEuJj)** ([raw file](https://github.com/servo/servo/blob/0070c4e4a65a910d31ee47e5a4eafbb2f3de94dd/components/script/dom/window.rs#L1060)):</sup>
You can just do `ElementCast::to_root(&node)`. Also, `.r()` is useless on roots now, they deref to their underlying type.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7613)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/window.rs, line 753 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7613#-Jz0l5QkjOuoSwfmdoRn)** ([raw file](https://github.com/servo/servo/blob/0070c4e4a65a910d31ee47e5a4eafbb2f3de94dd/components/script/dom/window.rs#L753)):</sup>
I was primarily fixing the indentation, but sure

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7613)

**Comment by frewsxcv** [comment]
Addressed your comments

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7613)

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

Sorry you misunderstood my nit. If you can't be bothered feel free to r=nox. :)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/window.rs, line 1058 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7613#-Jz0q2pOyY9HUKR4pWqH)** ([raw file](https://github.com/servo/servo/blob/3a7a610c92b10aa4b7106097f4ebfdff8d89340b/components/script/dom/window.rs#L1058)):</sup>
`ElementCast::to_root(node)`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7613)

**Comment by nox** [comment]
@bors-servo r+

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7613)

**Pull request merged**
