### PR TITLE
Support focus management and keyboard events for iframes.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5559)

### CODE REVIEW

**Comment by glennw** [comment]
r? @jdm 

I opened a new PR to save rebasing the old one over the CSS test changes, and because it's quite different to the previous implementation.

**Comment by Ms2ger** [comment]
Can we talk to Gecko's IME people about this?

**Comment by glennw** [comment]
@jdm Are you happy looking at this, or do you know who I should ping from Gecko?

**Comment by jdm** [comment]
I'm happy reviewing the code, but I would like to figure out specifically what @Ms2ger would like invited expert feedback on.

**Comment by jdm** [comment]
Squash!

**Comment by glennw** [comment]
Squashed and rebased

**Comment by jdm** [comment]
@Ms2ger If you have particular concerns here, I'd be happy to take them to relevant people. Previous requests to have them look at focus/keyboard stuff without a specific focus have not been successful.

**Comment by Ms2ger** [comment]
Fair enough; we'll probably figure out what we did wrong at some later point.

**Comment by glennw** [comment]
Squashed and rebased

**Pull request merged**
