### PR TITLE
compositing: removed opts-get

### LINKED ISSUE #22854: Remove uses of opts::get() from as much code as possible
Right now the code in components/config has a bunch of code depending on it because the command line arguments for Servo are global singleton that any code can access. This makes changing the command line code for Servo frustrating, because a lot of code gets rebuilt unnecessarily. We should remove as many uses of opts::get() as possible, and replace them with values that are passed into appropriate constructors via the code in components/servo/lib.rs.

We can focus on one component at a time:
* [ ] bluetooth
* [ ] compositing
* [ ] constellation
* [ ] layout
* [ ] layout_thread
* [ ] metrics
* [ ] net
* [ ] profile
* [ ] profile_traits
* [ ] script
* [ ] style

### PR DESCRIPTION
**Pull request by oneturkmen**
Removed all `opts::get()` from `compositing` component.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix *partially* #22854 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they are not feature- or bug-related changes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23493)

### CODE REVIEW

**Comment by oneturkmen** [comment]
PS. The issue #22854 is not done yet. There are other components to work on. This is only for `compositing` component.
PSS. Huge thanks goes to @gootorov for helping me with my 1st contribution.

**Comment by oneturkmen** [comment]
@jdm Let me know if you'd prefer a PR per component, or a single PR with the entire issue fixed (thus, with the changes from all listed components).

**Review by jdm — CHANGES_REQUESTED** [review]
Since we have removed the only use of servo_config from this crate, we can now remove the dependency from components/compositing/Cargo.toml. Thanks!

**Comment by jdm** [comment]
@bors-servo r+
Hooray!

**Comment by oneturkmen** [comment]
@jdm thanks for the help with the 1st contribution! proceeding with the rest now.

**Pull request merged**
