### PR TITLE
style: Cleanup always-false argument to Servo_ResolveStyleLazily.

### PR DESCRIPTION
**Pull request by emilio**
I changed this setup in https://bugzilla.mozilla.org/show_bug.cgi?id=1414999,
because it was totally unsound.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20082)

### CODE REVIEW

**Comment by emilio** [comment]
r? @nox or anyone else.

Don't r+ directly since I need to pick a train and I need to be around to push the Gecko side (just removing the argument).

**Comment by jdm** [comment]
@bors-servo retry
* flushing out problems with the windows builders, unfortunately

**Comment by jdm** [comment]
@bors-servo retry
* more windows flushing

**Comment by jdm** [comment]
@bors-servo retry
* getting there

**Comment by emilio** [comment]
@bors-servo r-

 * @jdm feel free to retry on #20081 instead, that shouldn't require Gecko changes, and I'm not going to be around if this takes too much more to land. Thanks!

**Pull request merged**
