### PR TITLE
animation-iteration-count property is a number instead of integer.

### PR DESCRIPTION
**Pull request by hiikezoe**
This is a revised PR  for #14732.
@emilio?
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14851)

### CODE REVIEW

**Comment by emilio** [comment]
This looks great.

One last thing this PR would need to do is to check the animation state more often (see the caller of tick()).

If you don't want to make that part of this PR (which is fine IMO since this doesn't regress functionality), please file an issue and cc me on it.

r=me with any of those 

Thanks once again for the patch :)

**Comment by hiikezoe** [comment]
@emilio can you please tell me about the animation state check in more detail?  I don't quite understand what 'more often' means.

**Comment by emilio** [comment]
So right now we call `tick` once per animation iteration (which actually is kinda misleading).

With this patch, thinks like `animation-iteration-count: 1.5` will parse but won't work I think, because we only check that number once per iteration, and we only increment it by `1.0`.

**Comment by hiikezoe** [comment]
Thank you, @emilio!  Now I think I understand the problem.  Filed #14858.

**Comment by emilio** [comment]
Awesome, thanks for filling it!

@bors-servo r+

**Pull request merged**
