### PR TITLE
Headers API constructor and methods

### PR DESCRIPTION
**Pull request by malisas**
This PR fills out the constructor and the delete, get, has, and set methods for the Headers API. Addresses issue #11897 .

The PR also rewrites the append method to support `hyper::header::Headers`'s HashMap `insert` method, which overwrites entries instead of appending.  
As a result of this, for a given header name there is at most one value in the inner "header list"/HashMap. Multiple values for the same name are comma-delimited.

There are still a few TODOs:
- Support `OpenEndedDictionary<ByteString>`  as a possible `HeadersInit` value. [OpenEndedDictionary<T> is a future IDL construct.](https://fetch.spec.whatwg.org/#headers-class)
- Support `iterable<ByteString, ByteString>`. Related issue: #12628 
- Values are comma-delimited, except for values with the name `set-cookie`, which are newline-delimited. This is because values for `set-cookie` are [allowed to contain](https://tools.ietf.org/html/rfc7230#section-3.2.2) inner commas. This violates the [spec](https://fetch.spec.whatwg.org/#concept-header-value-combined).
- The TODOs from PR #12467 regarding value parsing also still need to be resolved.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because tests for the Headers API already exists, but this commit does not implement the interface fully. The tests will fail.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12634)

### CODE REVIEW

**Comment by fitzgen** [comment]
cc myself

**Comment by jdm** [comment]
Great work! I've also submitted #12636 which will allow us to verify at least some of these changes against automated tests.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[components/script/dom/headers.rs, line 46 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn3oqWtUwj1HylXO6T:-KNn3oqWtUwj1HylXO6U:-774636332) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L46)):*
> ```Rust
>     // https://fetch.spec.whatwg.org/#concept-headers-fill
>     pub fn new(global: GlobalRef, init: Option<HeadersBinding::HeadersInit>)
>                -> Result<Root<Headers>, Error> {
> ```

This can be `Fallible<Root<Header>>` instead.

---

*[components/script/dom/headers.rs, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn5HhqN8NeqBXBH7ui:-KNn5HhqN8NeqBXBH7uj:393827510) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L47)):*
> ```Rust
>     pub fn new(global: GlobalRef, init: Option<HeadersBinding::HeadersInit>)
>                -> Result<Root<Headers>, Error> {
>         let domHeadersNew = reflect_dom_object(box Headers::new_inherited(), global, HeadersBinding::Wrap);
> ```

Let's call this `dom_headers_new`.

---

*[components/script/dom/headers.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn3xBm_UDkfwk5fBKW:-KNn3xBm_UDkfwk5fBKX:90566135) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L52)):*
> ```Rust
>             Some(HeadersOrByteStringSequenceSequence::Headers(h)) => {
>                 // headerListCopy has type hyper::header::Headers
>                 let headerListCopy = h.header_list.clone();
> ```

Traditional Servo code style is to name this `header_list_copy` instead.

---

*[components/script/dom/headers.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn467gUrl91ijdMG-R:-KNn467gUrl91ijdMG-S:1034518605) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L53)):*
> ```Rust
>                 // headerListCopy has type hyper::header::Headers
>                 let headerListCopy = h.header_list.clone();
>                 for header in headerListCopy.borrow().iter() {
> ```

`for header in &headerListCopy.borrow() {`

---

*[components/script/dom/headers.rs, line 70 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn4YadVUnBiFlDvjie:-KNn4YadVUnBiFlDvjif:-683350742) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L70)):*
> ```Rust
>                     } else {
>                         return Err(Error::Type(
>                             "Each inner Vec<ByteString> in HeadersInit must have length 2"
> ```

`format!("Each header object must be a sequence of length 2 - found one with length {}", seq.len())`

---

*[components/script/dom/headers.rs, line 122 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn7cLkTK8qNLpZoZXM:-KNn7cLkTK8qNLpZoZXN:391730995) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L122)):*
> ```Rust
>         // "set-cookie" values allow commas, so we use a different delimiter.
>         if &*valid_name == "set-cookie" {
>             combined_value.push(b"\n"[0]);
> ```

This change isn't part of the fetch specification, so this isn't compatible with the Headers implementation in other browsers. We should remove the special case here and file an issue against the Fetch specification.

---

*[components/script/dom/headers.rs, line 132 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn5y3ADfQ7FkCPsPtH:-KNn5y3B7906IgB_sUo2:1349490548) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L132)):*
> ```Rust
> 
>     // https://fetch.spec.whatwg.org/#dom-headers-delete
>     fn Delete(&self, name: ByteString) -> Result<(), Error> {
> ```

This can return `ErrorResult` instead.

---

*[components/script/dom/headers.rs, line 157 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn73MhzRiLpVBmxyFS:-KNn73MhzRiLpVBmxyFT:-198202853) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L157)):*
> ```Rust
> 
>     // https://fetch.spec.whatwg.org/#dom-headers-get
>     fn Get(&self, name: ByteString) -> Result<Option<ByteString>, Error> {
> ```

This can use Fallible.

---

*[components/script/dom/headers.rs, line 165 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn80JD_mUFAdAmovNa:-KNn80JEjZDuziTHn0a6:-1374110115) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L165)):*
> ```Rust
>         // TODO header fields with a name of "set-cookie" will be
>         // returned as newline-delimited values. This
>         // goes against the spec, which requires commas:
> ```

We should remove this note when we remove the spec-incompatible behaviour.

---

*[components/script/dom/headers.rs, line 167 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn6YqtprsgmOkAMu1-:-KNn6YqtprsgmOkAMu10:237631167) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L167)):*
> ```Rust
>         // goes against the spec, which requires commas:
>         // https://fetch.spec.whatwg.org/#concept-header-value-combined
>         match self.header_list.borrow_mut().get_raw(&valid_name) {
> ```

```rust
Ok(self.header_list.borrow().get_raw(&valid_name).map(|v| {
    ByteString::new(v[0].clone())
}))
```

---

*[components/script/dom/headers.rs, line 174 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn74_ekSdTk-zi8Du2:-KNn74_ekSdTk-zi8Du3:-1038004228) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L174)):*
> ```Rust
> 
>     // https://fetch.spec.whatwg.org/#dom-headers-has
>     fn Has(&self, name: ByteString) -> Result<bool, Error> {
> ```

Fallible.

---

*[components/script/dom/headers.rs, line 183 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12634#-KNn76ExhXOBMDurZ_cp:-KNn76ExhXOBMDurZ_cq:-1038004228) ([raw file](https://github.com/servo/servo/blob/51cfea3da8ef457b934663e76f05414d4f53d0df/components/script/dom/headers.rs#L183)):*
> ```Rust
> 
>     // https://fetch.spec.whatwg.org/#dom-headers-set
>     fn Set(&self, name: ByteString, value: ByteString) -> Result<(), Error> {
> ```

Fallible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12634#-:-KNn9PQh6oCor42ZIqP-:716793705)*

**Comment by malisas** [comment]
Thanks @jdm for the feedback!
I made the changes -- still need to file the Fetch spec issue though.

**Comment by malisas** [comment]
(and [here](https://github.com/whatwg/fetch/issues/345) is the filed issue about the `Set-Cookie` headers exception)

**Comment by jdm** [comment]
The only remaining change is to [update the expected test results](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) and squash the commits together.
-S-awaiting-review +S-needs-code-changes +S-needs-squash 

---

Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12634#-:-KNs7HnM51ksePYEf-IZ:330286279)*

**Pull request merged**
