### PR TITLE
Update phf_codegen and phf_shared to 0.11

### PR DESCRIPTION
**Pull request by MunishMummadi**
**Description:**
This pull request updates the versions of `phf_codegen` and `phf_shared` dependencies in the `servo/components/script/Cargo.toml` file from `0.10` to `0.11`. These changes aim to keep the project up-to-date with the latest versions of these dependencies.

**Changes Made:**
- Updated `servo/components/script/Cargo.toml`:
- Changed the versions of `phf_codegen` and `phf_shared` from `0.10` to `0.11` on lines 25 and 26.

Testing:
- Built the project to ensure that `Cargo.lock` gets updated.
- Checked that the build process completes successfully with the updated dependencies.

**Closes** #31516

### CODE REVIEW

**Review by Loirooriol — CHANGES_REQUESTED** [review]
Thanks, but Cargo.lock should get modified when you compile. Please include these changes in the patch.

**Review by mrobinson — CHANGES_REQUESTED** [review]
You will also need to check in the changes to the Cargo.lock file.

**Comment by MunishMummadi** [comment]
Hey @mrobinson , @Loirooriol 
I am struck with this error from the past 5 hours . As soon as i do `cargo build` exactly at (475/488). I am getting the attached error.
Screenshot (10)
Screenshot (11)

**Comment by fabricedesre** [comment]
fwiw I could build fine on Linux with this change. There are still deps that use 0.10 though (markup5ever and string_cache).

**Comment by MunishMummadi** [comment]
> fwiw I could build fine on Linux with this change. There are still deps that use 0.10 though (markup5ever and string_cache).

Actually I am trying to build in WSL(Ubuntu). Are you suggesting me to do a clean build in Linux only. Correct and guide me if I am wrong.

**Comment by mrobinson** [comment]
> Actually I am trying to build in WSL(Ubuntu). Are you suggesting me to do a clean build in Linux only. Correct and guide me if I am wrong.

I would either try to do a pure Linux build or a pure Windows build. I'm not sure if Servo supports WSL.

**Comment by Loirooriol** [comment]
> As soon as i do `cargo build`

Have you tried `./mach build` instead? https://github.com/servo/servo?tab=readme-ov-file#normal-build

**Review by Loirooriol — APPROVED** [review]
Thanks, looks good!

**Review by mrobinson — APPROVED** [review]

**Pull request merged**
