### PR TITLE
Wrap extern static usage in unsafe block.

### PR DESCRIPTION
**Pull request by jdm**
This avoids a soft-warning from rustc which will become a hard error in the future.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13435)

### CODE REVIEW

**Comment by jdm** [comment]
Before:
```
warning: use of extern static requires unsafe function or block (error E0133), #[warn(safe_extern_statics)] on by default

     --> /home/travis/build/servo/servo/components/style/./gecko_string_cache/atom_macro.rs:15844:80

      |

15844 | ("right") => { $crate::string_cache::atom_macro::unsafe_atom_from_static($crate::string_cache::atom_macro::nsGkAtoms_right as *mut _) };

      |                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      | 

     ::: /home/travis/build/servo/servo/components/style/matching.rs

      |

366   |             mode: CommonStyleAffectingAttributeMode::IsEqual(atom!("right"), ALIGN_RIGHT_ATTRIBUTE),

      |                                                              -------------- in this macro invocation

      |

      = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!

      = note: for more information, see issue 36247 <https://github.com/rust-lang/rust/issues/35112>
```
After:
```
/home/servo/buildbot/slave/linux-dev/build/components/style/./gecko_string_cache/atom_macro.rs:15844:74: 15844:144 warning: unnecessary `unsafe` block, #[warn(unused_unsafe)] on by default
/home/servo/buildbot/slave/linux-dev/build/components/style/./gecko_string_cache/atom_macro.rs:15844 ("right") => { $crate::string_cache::atom_macro::unsafe_atom_from_static(unsafe { $crate::string_cache::atom_macro::nsGkAtoms_right as *mut _ }) };
                                                                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Wat.

**Comment by Wafflespeanut** [comment]
We don't seem to use a lot of atoms as of now. Maybe we should `#[allow(unsafe_code, unused_unsafe)]` ?

**Comment by jdm** [comment]
So I realized what the problem is, and why my previous fix (`allow(unsafe_extern_static)`) also had no effect - the unsafe is substituted in every invocation of the macro, so sometimes it's already inside of an unsafe block, and other times it's in files where unsafe code isn't allowed right now (so we get compilation errors). This _really_ sucks. @Manishearth any ideas on how to resolve this?

**Comment by Wafflespeanut** [comment]
We `#![deny(unsafe_code)]` in `style` crate, and I'm not sure whether we can override it for a particular mod. Maybe we should allow unsafe code for that crate, or have a separate crate for `style_bindings` which can have unsafe code, and other lints (which aren't necessary for the `style` themselves)?

**Comment by jdm** [comment]
Allowing per module works when deny is present.

**Comment by Wafflespeanut** [comment]
Huh. Having something like this,

```rust
#[allow(improper_ctypes, safe_extern_statics, unsafe_code)]
 pub mod atom_macro;
```

still throws an error...

    /media/Ubuntu/servo/components/style/./gecko_string_cache/atom_macro.rs:15063:14: 15063:141 error: usage of an `unsafe` block
    /media/Ubuntu/servo/components/style/./gecko_string_cache/atom_macro.rs:15063 ("dir") => { unsafe { $crate::string_cache::atom_macro::unsafe_atom_from_static($crate::string_cache::atom_macro::nsGkAtoms_dir as *mut _) } };
                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /media/Ubuntu/servo/components/style/lib.rs:33:9: 33:20 note: lint level defined here
    /media/Ubuntu/servo/components/style/lib.rs:33 #![deny(unsafe_code)]

The same goes for allowing unsafe code for the entire module `gecko_string_cache`.

**Comment by Manishearth** [comment]
I think `#[allow]` works on blocks now, so `#[allow(unsafe_code, unused_unsafe)]` might be okay? You might need to add an extra block within the macro to make this work.

**Comment by jdm** [comment]
@Manishearth:
```
/home/travis/build/servo/servo/components/style/lib.rs:32:32: 32:62 error: #[feature] may not be used on the stable release channel

/home/travis/build/servo/servo/components/style/lib.rs:32 #![cfg_attr(feature = "gecko", feature(stmt_expr_attributes))]

                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
:(

**Comment by Manishearth** [comment]
I guess one solution is to generate safe static fns that return pointers for each atom here? (and `#[allow]` internally)

Or we could tweak the compiler to not warn here.

**Comment by Manishearth** [comment]
Importing the safe static fns could be a pain. We get stuck with privacy too. I think there's a way to punch through privacy errors for macros but IIRC that's plugin-only.

```
extern {
    #[link_name = "foo"]
    pub static foo: *mut u8;
}
pub static bar: *mut u8 = unsafe {foo};
```
doesn't work because `*mut u8` isn't `Sync` :/

**Comment by Manishearth** [comment]
This works

```rust
#![deny(unsafe_code)]
#![allow(bad_style, unused)]

extern {
    #[link_name = "foo"]
    pub static foo: &'static u8;
}

#[allow(unsafe_code)]
pub static bar: &'static &'static u8 = unsafe {&foo};

fn main() {
    let x = *bar;
}
```

([playpen](https://play.rust-lang.org/?gist=abb32c10524bce168e2f03336ce93301&version=nightly&backtrace=0))

Introduces double indirection, sadly. We can leave a comment to get it removed once attributes are allowed on statements.

**Comment by Wafflespeanut** [comment]
fixed by #13686

**Pull request closed without merging**
