### PR TITLE
Update NuGet packages

### LINKED ISSUE #25341: Upgrade to UWP Angle 2.1.17 package
This adds PDB files to the package, which can be added as paths for symbols when profiling and debugging.

### PR DESCRIPTION
**Pull request by paulrouget**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #25341 (GitHub issue number if applicable)

### CODE REVIEW

**Comment by paulrouget** [comment]
I ran into that issue: https://github.com/microsoft/cppwinrt/issues/410

Adding onecore.lib appears to solve the winrt missing symbol issue.

Not tested on device.

**Comment by jdm** [comment]
```
     3>XamlMetaDataProvider.obj : error LNK2001: unresolved external symbol WINRT_GetErrorInfo [C:\Users\task_1578310905\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>Servo.obj : error LNK2001: unresolved external symbol WINRT_GetErrorInfo [C:\Users\task_1578310905\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>ServoControl.obj : error LNK2001: unresolved external symbol WINRT_GetErrorInfo [C:\Users\task_1578310905\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>XamlTypeInfo.Impl.g.obj : error LNK2001: unresolved external symbol WINRT_GetErrorInfo [C:\Users\task_1578310905\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>XamlTypeInfo.g.obj : error LNK2001: unresolved external symbol WINRT_GetErrorInfo [C:\Users\task_1578310905\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>App.obj : error LNK2001: unresolved external symbol WINRT_GetErrorInfo [C:\Users\task_1578310905\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>BrowserPage.obj : error LNK2001: unresolved external symbol WINRT_GetErrorInfo [C:\Users\task_1578310905\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>module.g.obj : error LNK2001: unresolved external symbol WINRT_GetErrorInfo [C:\Users\task_1578310905\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     3>OpenGLES.obj : error LNK2001: unresolved external symbol WINRT_GetErrorInfo [C:\Users\task_1578310905\repo\support\hololens\ServoApp\ServoApp.vcxproj]
```

**Comment by jdm** [comment]
We're missing onecore.lib for the arm64 linking arguments.

**Comment by paulrouget** [comment]
Angle has been updated separately.
I haven’t tested on device.

**Comment by dralley** [comment]
Is anything blocking this, or does it just need a fresh passing test run?

**Comment by jdm** [comment]
It needs testing.

**Pull request closed without merging**
