### PR TITLE
DO NOT MERGE Try turning on overflow checking on release

### PR DESCRIPTION
**Pull request by larsbergstrom**
Just trying this out via try to see what happens...

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10544)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
MUA-HA-HA-HA!
```
Tests with unexpected results:
  ▶ CRASH [expected OK] /html/dom/reflection-embedded.html
  │ 
  │ thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'arithmetic operation overflowed', /Users/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/app_units-0.2.3/src/app_unit.rs:117
  │ stack backtrace:
  │    1:        0x1095fe0d8 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
  │    2:        0x109601d65 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
  │    3:        0x10960197c - std::panicking::default_hook::h08ad3bb09872855b
  │    4:        0x1095ec068 - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
  │    5:        0x1095ed31e - std::sys_common::unwind::begin_unwind_fmt::h57ea3fbee1a40196
  │    6:        0x1095fd3a7 - rust_begin_unwind
  │    7:        0x109629700 - core::panicking::panic_fmt::ha6b3c19493c123b3
  │    8:        0x109629a5c - core::panicking::panic::h188c6c6a0fe5463c
  │    9:        0x10863db69 - script::dom::htmlimageelement::image_dimension_setter::h2e3eec119f489294
  │   10:        0x108206dd0 - script::dom::bindings::codegen::Bindings::HTMLImageElementBinding::set_width::h7f3877b6e131f649
  │   11:        0x108d9940a - CallJitSetterOp
  │   12:        0x108455ead - script::dom::bindings::utils::call_setter::hf3affdd67a62659e
  │   13:        0x108455d87 - script::dom::bindings::utils::generic_call::hfefc1ba5d4f4d4f0
  │   14:        0x108ed317b - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │   15:        0x108ecb77d - _ZN2js6InvokeEP9JSContextRKN2JS5ValueES5_jPS4_NS2_13MutableHandleIS3_EE
  │   16:        0x108ee93ae - _ZN2js20InvokeGetterOrSetterEP9JSContextP8JSObjectN2JS5ValueEjPS5_NS4_13MutableHandleIS5_EE
  │   17:        0x108f06f77 - _ZN2js17NativeSetPropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_IP8JSObjectEENS3_I4jsidEENS_13QualifiedBoolENS2_13MutableHandleINS2_5ValueEEERNS2_14ObjectOpResultE
  │   18:        0x108eeda70 - _ZN2js16SetObjectElementEP9JSContextN2JS6HandleIP8JSObjectEENS3_INS2_5ValueEEES8_bNS3_IP8JSScriptEEPh
  │   19:        0x108ffcc62 - _ZN2js3jitL17DoSetElemFallbackEP9JSContextPNS0_13BaselineFrameEPNS0_18ICSetElem_FallbackEPN2JS5ValueENS7_6HandleIS8_EESB_SB_
  └ fatal runtime error: Could not unwind stack, error = 5

program finished with exit code 1
elapsedTime=1086.134747
```

Looks like adding overflow checking, even just for our buildbot/CI builds, would be useful.


cc @edunham  @metajack @nmatsakis @pnkfelix

**Comment by edunham** [comment]
@larsbergstrom I'm +1 on this; it doesn't look like it's slowing things down noticeably. I'll r+ if/when you're ready :)

**Comment by Ms2ger** [comment]
We clamp to `i32::max_value()` (effectively), but then `Au::from_px()` multiplies by 60, leading to the overflow.

**Comment by larsbergstrom** [comment]
@bors-servo try

(this is mainly to check out the windows support, not because I expect things to be fixed)

**Comment by jdm** [comment]
@larsbergstrom What's the plan here?

**Comment by larsbergstrom** [comment]
@jdm I was planning to:
1) Get all the bugs identified fixed
2) Do some perf testing of real scenarios to see if this has negative impacts on Servo or not

Would you like me to close it instead for now?

**Comment by jdm** [comment]
Yeah, I don't see much reason in leaving it open until it's ready to be dealt with by a reviewer.

**Pull request closed without merging**
