### PR TITLE
Backport several style changes from Gecko (10)

### PR DESCRIPTION
**Pull request by Loirooriol**
This continues https://github.com/servo/servo/pull/30692.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

### CODE REVIEW

**Comment by Loirooriol** [comment]
So I was treating the `layout.css.more_color_4.enabled` pref as false, but turns out that `hwb()` used to work and now is behind the pref, so I guess I will treat the pref as true.

**Comment by Loirooriol** [comment]
These are my changes: 1c3077edb 178a9c810 c638858ba a45e3b023 9c58b152f e6c859a96 1e05f54c5 660200478 91f243d77 89dbbf686 8c922853d e9925e0ad aa1fde791 cc74fed67 ee5af092b c0c2eb606 2d08a7ddf 2ee2aa17b

**Review by mrobinson — APPROVED** [review]
Nice. These are really coming along.

**Comment by mrobinson** [comment]
I will land this one the merge queue is empty.

**Pull request merged**
