### PR TITLE
Optimize WebGL function calls

### PR DESCRIPTION
**Pull request by MortimerGoro**
I measured the cost of calling some WebGL methods from JavaScript and they are slower compared to Firefox or Chrome.  It seems that one of the bottlenecks is the ipc-channel. Current Servo WebGL implementation uses two ipc-channel layers: DOM<=>WebGLPaintThread and WebGLPaintThread<=>Webrender. 

This PR replaces the first DOM<=>WebGLPaintThread ipc-channel with a faster mpsc:channel. This doesn't give untrusted content access to the GPU to DOM because the WebGLContexts are still owned by WebRender and the real render messages still sent through the second ipc-channel. 

With this change the inmediate cost of simple WebGL method calls are closer to what we see in Firefox or Chrome. Example with measured times on a Desktop linux:

New version, 200 webgl.clearColor calls. Frame times in milliseconds.
```
0.07886199999938981
0.0779819999997926
0.04238999999961379
0.04007799999999406
0.08114899999964109
0.07670300000063435
0.08235400000012305
0.07708800000000338
0.08082799999920098
0.08204200000000128
0.08140400000047521
0.08121699999992416
0.0797919999995429
```

Old version, 200 webgl.clearColor calls. Frame times in milliseconds.

```
0.9031110000000808
0.8622270000000753
0.9009390000001076
0.8202759999999216
0.848363000000063
0.8556140000000596
0.8366560000004029
0.864226000000599
0.8818160000000717
0.8485639999998966
0.9495310000002064
0.8295939999998154
0.8321460000006482
```
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16679)

### CODE REVIEW

**Comment by MortimerGoro** [comment]
@jdm Could you run bors-servo try again? I pushed a minor change just after you ran it and the build stopped

**Comment by emilio** [comment]
I believe, btw, that WebGLPaintThreads are supposed to live in the UI process. I'd need to double-check tomorrow, but seems to me that the layer of indirection we could theoretically remove is the WebGLPaintThread <=> WR.

But actually, the paint thread when WR is enabled is just a proxy, so we may be able to avoid creating a WebGLPaintThread entirely when using the WR back-end?

**Comment by MortimerGoro** [comment]
`But actually, the paint thread when WR is enabled is just a proxy, so we may be able to avoid creating a WebGLPaintThread entirely when using the WR back-end?`

I thought about removing the WebGLPaintThread too. It seems possible to entirely avoid creating it when WR is enabled. I didn't remove yet because I thought that the thread  could help with the ipc-channel serialziation slowness (the slow serialization work is done in background instead of blocking JS).

**Comment by MortimerGoro** [comment]
Ready for retry. Test failed because pixels were upside-down when a webglcanvas is used as source in texImage2D/texSubImage2D. Previously webgl-canvas textImage2D sources were not implemented and all pixels were 0,0,0,0

**Comment by emilio** [comment]
As I said, I think this is conceptually wrong, and the channel we should be avoiding is the WebGLPaintThread <=> WR. @pcwalton can confirm if that's right, since he did the initial multi-process stuff, though.

@bors-servo try

**Comment by MortimerGoro** [comment]
> As I said, I think this is conceptually wrong, and the channel we should be avoiding is the WebGLPaintThread <=> WR. @pcwalton can confirm if that's right, since he did the initial multi-process stuff, though.

I'd love to get rid of WebGLPaintThread. As I said with this PR the WebGLPaintThread is really only used as a "helper" thread to avoid blocking JS thread with serialization work. I measured the JS raf time in some Three.js demo and it has some impact. If there is a way to improve this I don't mind rewriting the code to remove WebGLPaintThread, for example:

- I saw that bincode-based IPC landed in webrender, can this help?
- Batching WebGL calls and serialize/send some of them at once may help

**Comment by MortimerGoro** [comment]
```
Compiling parking_lot_core v0.2.1
LLVM ERROR: Invalid data was encountered while parsing the file
error: Could not compile `parking_lot_core`.
Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by MortimerGoro** [comment]
@jdm yes, totally replaced. This can be closed.

**Pull request closed without merging**
