### PR TITLE
Add style_traits crate to improve crate separation,

### LINKED ISSUE #7353: Add a style_traits crate to improve crate separation
There are cases where some crates (eg. `compositing` and `msg`) that rely on very few public types from the style crate (such as `viewport::ViewportConstraints`). We should be able to extract these into a separate `style_traits` crate and make `style` depend on that, to reduce the number of crates that need to be rebuilt when making changes to `style`.

### PR DESCRIPTION
**Pull request by jxs**
closes #7353

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7508)

### CODE REVIEW

**Comment by Ms2ger** [comment]
You'll need to reorder `use` statements to appease test-tidy.

I'd also like you to add `#![deny(unsafe_code)]` to the new crate, and only allow it where needed.

r? @SimonSapin

**Comment by SimonSapin** [comment]
Please maintain the module structure of items moved from the style crate. For example, `style_traits::Origin` should instead be at `style_traits::stylesheets::Origin`. Feel free to do that either with `mod foo { … }` in `lib.rs` or with `mod foo;` and separate `*.rs` files.

The reason is that many terms are overloaded. "Origin" by itself could be the origin of an URL (as in cross-origin policy), which is completely different from the origin of a stylesheet (which influences precedence in the cascade).

This is particularly important for things from `style::values::specified`, as they have their conterparts with the same name in `style::values::computed` that look very similar, but are different. Using e.g. `specified::Length` (with `use style::values::specified;`) all over the code instead of just `Length` (with `use style::values::specified::Length;`) is deliberate: it disambiguates locally. Please preserve that in the move.

---

Reviewed 25 of 31 files at r1.
Review status: 25 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7508)

**Comment by jxs** [comment]
thanks for the explanation @SimonSapin,  updated and managed to move a lot less code to the new style_traits crate, preserving previous structure.
 `use` statements are also now ordered

**Comment by jdm** [comment]
Ooh, I really like that `msg` does not depend on `style` any more. That's a nice improvement.

**Comment by SimonSapin** [comment]
Looks good, thanks!

@bors-servo r+

**Comment by Ms2ger** [comment]
```
./components/servo/Cargo.lock:1615: conflicting versions for package "cssparser"
	expected maximum version "0.3.6"
	but, "style_traits" demands "0.3.5"
	try upgrading with ./mach cargo-update -p cssparser:0.3.5
```

**Comment by jxs** [comment]
fixed, had to fix cargo.lock after the merge

**Comment by SimonSapin** [comment]
Looks like unit tests need to be updated as well. They’re in `tests/unit` and can be run with `./mach test-unit`.

**Comment by SimonSapin** [comment]
Oh, you’ve already done it :) Good. (GitHub unfortunately doesn’t notify for new commits in PR.)

@bors-servo r+

**Pull request merged**
