### PR TITLE
Remove unnecessary generics from low-level script code

### PR DESCRIPTION
**Pull request by jdm**
This should remove one of the larger offenders from the cargo-llvm-lines output for the script crate.

CC https://github.com/servo/servo/issues/26713

### CODE REVIEW

**Comment by jdm** [comment]
Together these changes remove ~250k lines from the output of cargo-llvm-lines.

**Comment by SimonSapin** [comment]
Nice!

@bors-servo r+

**Comment by nox** [comment]
Just a side note: the passed function is always a `T::derives`, which is always implemented as `proto_chain[depth] == some_interface_id`, so we could probably get rid of the passed function entirely.

**Pull request merged**
