### PR TITLE
Quality: Fix CS

### PR DESCRIPTION
**Pull request by Hywan**
Just remove trailing spaces.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9483)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Sorry for the bother; that was me preparing to do some work on our infrastructure. I'll retry this PR in a little bit.

**Comment by KiChjang** [comment]
@bors-servo retry
* #9448

**Comment by jdm** [comment]
@bors-servo: retry
* #9488

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #9504

**Comment by Hywan** [comment]
\o/

**Pull request merged**
