### PR TITLE
Bump euclid to 0.22

### LINKED ISSUE #27424: Update to euclid 0.22
https://crates.io/crates/euclid/0.21.0

This contains [a number of breaking changes](https://github.com/servo/euclid/pulls?q=is%3Apr+is%3Aclosed+label%3A%22breaking+change%22)

Most are minor, and I believe all of them pair behavior changes with method renames. The ones that will be the trickiest are:

 - [Move away from pre_transform/post_transform terminology](https://github.com/servo/euclid/pull/451)
 - [Adopt the column-major-column-vector notation](https://github.com/servo/euclid/pull/452)

This essentially means we'll need to flip our `from_row_majors` and also fix up our `pre_transform`/etc usage. Currently we do things backwards because we want to use column-major column vectors, this will make it easier for us to do that, but will involve a bit of work.

### PR DESCRIPTION
**Pull request by mrobinson**
Major changes:

- All matrices are now stored in row major order. This means that parameters to rotation functions should no longer be negated.
- `post_...()` functions are now named `then()`. `pre_transform()` is removed, so `then()` is used and the order of operations changed.

In addition, this PR updates lyon_geom to the latest version.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #27424
- [x] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
@bors-servo try

I've pushed a new version of this change that fixes the issue mentioned in https://github.com/servo/servo/pull/28605#issuecomment-962378295.

>  - `/css/cssom-view/scrolling-quirks-vs-nonquirks.html`: A change in `UnioningFragmentScrollAreaIterator`'s behavior is associated with `euclid::Rect::union`'s handling of operands with negative sizes. It's used by this code, which to be honest doesn't make much sense:

I agree that this iterator doesn't make much sense, but for now I've just added a workaround which emulates euclid's old behavior and added a comment explaining the situation.

**Comment by mrobinson** [comment]
I think this upgrade is ready to review. It currently switches servo to use the git version of surfman-chains, but it's unclear when that will be updated on crates.io.

**Comment by mrobinson** [comment]
@Manishearth and @jdm if you have a few free moments, would you be willing to review this change? Thank you! @Manishearth I know you are not quite as active as before, but I'm adding just in case you were interested due to working on this before.

**Comment by jdm** [comment]
@bors-servo r+
Thank you!

**Review by Manishearth — APPROVED** [review]
r+ but ideally we can have a second eye on this too to catch anything I may have missed

**Comment by Manishearth** [comment]
Or, well, jdm reviewed it in the meantime anyway, that works :smile:

**Pull request merged**
