### PR TITLE
script: Split `Pipeline::create` into chrome process and content process parts.

### PR DESCRIPTION
**Pull request by pcwalton**
This will make it easier to adapt to IPC.

The trickiest part here was to make script tasks spawn new layout tasks
directly instead of having the pipeline do it for them. The latter
approach will not work in multiprocess mode, because layout and script
must run in the same address space and the pipeline cannot inject tasks
into another process.

r? @larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6618)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6618)

**Comment by larsbergstrom** [comment]
```
4.84s$ ./mach test-tidy

components/compositing/pipeline.rs:271: trailing whitespace

components/compositing/pipeline.rs:278: trailing whitespace
```

Fix then r=me

**Comment by pcwalton** [comment]
Should fix the timeouts. r? @larsbergstrom

**Comment by larsbergstrom** [comment]
Reviewed 1 of 11 files at r1, 11 of 11 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6618)

**Pull request merged**
