### PR TITLE
Prepend, rather than append, SVG title elements.

### LINKED ISSUE #8164: Fix document.title setter for SVG documents to match spec changes
See https://github.com/whatwg/html/commit/f7ff53e761a9fc813d9765073e2752d42347f0b6 .  The relevant code in Servo is https://github.com/servo/servo/blob/dcd207f9bf15c9ecf5d043385ba93277e69201f6/components/script/dom/document.rs#L1495 .

Should be easy to fix... ~~the only potentially tricky bit is that Servo can't parse SVG at the moment, so testing it involves synthesizing an SVG document using DOM calls.~~ Nevermind, a test already exists (or at least it will next time we sync with upstream web-platform-tests),

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #8164

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8296)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/script/dom/document.rs, line 1698 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8296#-K2Gop4DOQYfaf6uWnt3)** ([raw file](https://github.com/servo/servo/blob/81e03846994469284a592aeedba617fb32c68a49/components/script/dom/document.rs#L1698)):</sup>
Please insert before first child instead. Please also upcast `elem` directly before inserting it. This way you don't need to upcast it against when returning it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8296)

**Comment by notriddle** [comment]
Fixed.

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/script/dom/document.rs, line 1746 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8296#-K2NXSzJsJjYD4I4T54A)** ([raw file](https://github.com/servo/servo/blob/42657d87ae471a1c1b07605ff88d6b1f6c069b84/components/script/dom/document.rs#L1746)):</sup>
Use `RootedReference::r`: `.InsertBefore(elem_node, root_node.GetFirstChild().r())` should work. By the way we generally just name these `parent` and `child`, not `root_node` and `elem_node`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8296)

**Comment by notriddle** [comment]
Fixed more.

**Comment by nox** [comment]
Please squash and I'll r+ it.

-S-awaiting-review +S-needs-squash 


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8296)

**Comment by notriddle** [comment]
Squashed.

**Comment by nox** [comment]
@bors-servo r+


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8296)

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Pull request merged**
