### PR TITLE
Use the correct log crate and setup env_logger in main.

### PR DESCRIPTION
**Pull request by eddyb**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6296)

### CODE REVIEW

**Comment by eddyb** [comment]
```
ERROR:js::rust: Error at https://jsfiddle.net/b99y0ja2/show/:2: TypeError: document.write is not a function
```

**Comment by Ms2ger** [comment]
Fixes #4920.

@bors-servo: r+

**Comment by eddyb** [comment]
@Ms2ger this is on top of the smupgrade3 branch btw, do you want me to backport?

**Comment by Ms2ger** [comment]
Doh.

**Pull request closed without merging**
