### PR TITLE
Make unrooted_must_root ignore Rc<Promise>

### LINKED ISSUE #22504: Make unrooted_must_root understand promises
Currently methods returning an `Rc<Promise>` need to be marked as `allow(unrooted_must_root)`, because `Rc<Promise>` is transitively `must_root`. Almost all the new APIs use promises, which means we opt out of our soundness checks a lot.

Perhaps we can instead use a thin wrapper around `Rc<Promise>` called `RootedPromise`, which itself isn't `must_root`? Or special case the lint for this. I'm hesitant to just go ahead and do it because I don't fully understand the soundness situation for promises.

see also https://github.com/servo/servo/issues/14900

cc @nox @jdm @asajeffrey

### PR DESCRIPTION
**Pull request by Manishearth**
fixes #22504

r? @jdm @nox

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22608)

### CODE REVIEW

**Comment by Manishearth** [comment]
Note: this PR is currently based on https://github.com/servo/servo/pull/22528, which should land soon. If not I can rebase.

**Comment by Manishearth** [comment]
There's some further potential cleanup in htmlmediaelement.rs which I haven't touched yet

**Comment by Manishearth** [comment]
@nox I've got a WIP that cleans up the pending promises stuff for HTMLMediaElement, but the following code seems to be specced such that we _have_ to maintain a pending promises list? Maybe I'm misreading

https://github.com/servo/servo/blob/7c34a70ca8d2087e5d1b7b29ae128b803cecacf9/components/script/dom/htmlmediaelement.rs#L949-L951

**Comment by jdm** [comment]
```
./components/script/dom/serviceworkercontainer.rs:57: method declared in webidl is missing a comment with a specification link
```
```
error[E0069]: `return;` in a function whose return type is not `()`
    --> components/script/dom/htmlmediaelement.rs:1301:13
     |
1289 |     fn Play(&self) -> Rc<Promise> {
     |                       ----------- expected `Rc<Promise>` because of this return type
...
1301 |             return;
     |             ^^^^^^ return type is not `()`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0069`.
error: Could not compile `script`.
```

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
```
[94m./components/script/dom/serviceworkercontainer.rs[0m:[93m57[0m: [91mmethod declared in webidl is missing a comment with a specification link[0m
```

**Pull request merged**
