### PR TITLE
Implement HTMLLIElement#value

### LINKED ISSUE #12575: Implement HTMLLIElement#value
In order to parse the value attribute value as an integer, the `parse_plain_attribute` function from the `VirtualMethods` trait should be implemented accordingly.

Spec: https://html.spec.whatwg.org/multipage/semantics.html#dom-li-value
Code: `components/script/dom/htmllielement.rs`, `components/script/dom/webidls/HTMLLIElement.webidl`
Test: tests/wpt/web-platform-tests/html/semantics/grouping-content/the-li-element/grouping-li.html

### PR DESCRIPTION
**Pull request by vrod**
- Add implementation of parse_plain_attribute from VirtualMethods trait for HTMLLIElement
- Add make_int_setter! macro
- Implement getter and setter for HTMLLIElement#value attribute
- Update test expectations for HTMLLIElement#value

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12575
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12620)

### CODE REVIEW

**Comment by vrod** [comment]
the test `[li should have a 'value' attribute]` is still not passing. It does not pass for Firefox 47.0.1 nor Chrome 52.0.2743.82, so I am not sure whether I should do anything about it.

**Comment by KiChjang** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/htmllielement.rs, line 54 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12620#-KNhLTiooYmroV4QcuBl:-KNhLTipsTZU1zDus6GI:-1265883387) ([raw file](https://github.com/servo/servo/blob/3299d0ffdd9bc53a15e4ec6763bb185fce28d29d/components/script/dom/htmllielement.rs#L54)):*
This looks wrong. Spec says the following:
> If the value attribute is present, user agents must parse it as an integer, in order to determine the attribute's value. If the attribute's value cannot be converted to a number, the attribute must be treated as if it was absent. The attribute has no default value.

---

*[components/script/dom/macros.rs, line 50 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12620#-KNhKRgBYO15_VB4fyp9:-KNhKRgBYO15_VB4fypA:-166318467) ([raw file](https://github.com/servo/servo/blob/3299d0ffdd9bc53a15e4ec6763bb185fce28d29d/components/script/dom/macros.rs#L50)):*
> ```Rust
> 
> #[macro_export]
> macro_rules! make_int_setter(
> ```

This is incorrect. If you look at the spec examples, the `<li>` elements have `value="1"` (with quotes around the integer). This means that the value being set is actually a string, not an int.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12620#-:-KNhLYPIKCJzN7SlGIbH:1458266033)*

**Comment by KiChjang** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/htmllielement.rs, line 54 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12620#-KNhLTiooYmroV4QcuBl:-KNic9BRuaHR2TIqGWzm:-333837508) ([raw file](https://github.com/servo/servo/blob/3299d0ffdd9bc53a15e4ec6763bb185fce28d29d/components/script/dom/htmllielement.rs#L54)):*
<details><summary><i>Previously, KiChjang (Keith Yeung) wrote…</i></summary>
> This looks wrong. Spec says the following:
> > If the value attribute is present, user agents must parse it as an integer, in order to determine the attribute's value. If the attribute's value cannot be converted to a number, the attribute must be treated as if it was absent. The attribute has no default value.
</details>
Ignore this, correct part of the spec is https://html.spec.whatwg.org/multipage/infrastructure.html#reflecting-content-attributes-in-idl-attributes:rules-for-parsing-integers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12620)*

**Comment by Ms2ger** [comment]
This LGTM, but please squash the commits together. Let me know if you need help with that.

r? @Ms2ger

-S-needs-code-changes +S-needs-squash 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[components/script/dom/macros.rs, line 50 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12620#-KNhKRgBYO15_VB4fyp9:-KNkjKpgQ5gZLeDG75ch:934274806) ([raw file](https://github.com/servo/servo/blob/3299d0ffdd9bc53a15e4ec6763bb185fce28d29d/components/script/dom/macros.rs#L50)):*
<details><summary><i>Previously, KiChjang (Keith Yeung) wrote…</i></summary>
> This is incorrect. If you look at the spec examples, the `<li>` elements have `value="1"` (with quotes around the integer). This means that the value being set is actually a string, not an int.
</details>
This in not anywhere close to making any sense; all content attributes are strings, and the DOM parsed from `x=foo`, `x='foo'` and `x="foo"` is exactly the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12620#-:-KNkjoASYCzwVFgQmuaj:-1428066579)*

**Comment by vrod** [comment]
@Ms2ger: Done.

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLLIElement interface: attribute value

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLLIElement interface: document.createElement("li") must inherit property "value" with the proper type (0)

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: typeof IDL attribute

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: IDL get with DOM attribute unset

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to -36 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to -1 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to 0 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to 1 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to 2147483647 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to -2147483648 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to 2147483648 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to -2147483649 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to 4294967295 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to 4294967296 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "-1" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "-0" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "0" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "1" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to " \\0\\x01\\x02\\x03\\x04\\x05\\x06\\x07 \\b\\t\\n\\v\\f\\r\\x0e\\x0f \\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17 \\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f  foo " followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\\t7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\\v7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\\f7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to " 7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\xa07" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\ufeff7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\\n7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\\r7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20287" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20297" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u16807" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u180e7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20007" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20017" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20027" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20037" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20047" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20057" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20067" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20077" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20087" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u20097" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u200a7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u202f7" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\u30007" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to undefined followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to 1.5 followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to true followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to false followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to object "[object Object]" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to NaN followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to Infinity followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to -Infinity followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to "\\0" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to object "2" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: setAttribute() to object "3" followed by IDL get

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: IDL set to -36 followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: IDL set to -1 followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: IDL set to 0 followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: IDL set to 1 followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: IDL set to 2147483647 followed by getAttribute()

  ▶ Unexpected subtest result in /html/dom/reflection-grouping.html:
  └ PASS [expected FAIL] li.value: IDL set to -2147483648 followed by getAttribute()
```

**Comment by KiChjang** [comment]
@vrod You'll need to change the test expectations for the passing tests.

**Comment by KiChjang** [comment]
Spec is changing on this one: whatwg/html#1610

**Comment by vrod** [comment]
@KiChjang: updated the test expectations. By the way, it is good to see that the documentation is getting changed to express the correct behavior more clearly.

**Comment by KiChjang** [comment]
@bors-servo r+

The spec changes are mostly clarifications, it has no bearing on how the IDL attribute should behave. Thanks!

**Pull request merged**
