### PR TITLE
deny warnings for all crates as default

### LINKED ISSUE #19572: check build warning about unused import
If there is unused import, somewhere check for it and then return fail.

### PR DESCRIPTION
**Pull request by tigercosmos**
deny warnings for all crates as default
r? emilio 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #19572 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19573)

### CODE REVIEW

**Review by emilio — APPROVED** [review]
Fine for me, thanks!

@jdm or anyone else, any opinion against this?

**Comment by jdm** [comment]
Historically blanket denies like this can make local debugging more frustrating, since attempts to comment out pieces of code can make arguments or fictions unused. I'm not sure that the benefit of not merging unused imports is worth it.

**Comment by KiChjang** [comment]
Moreover, we're still using the nightly channel, so any erroneous warning messages from nightly could cause some roadblocks when we're performing a rustup.

**Comment by tigercosmos** [comment]
I thought the question is which one will be better:
1. deny warning as default, and modify if need (nightly or ..?)
2. when find warning, fix it manually

Maybe not "all" set as default, but "almost"?

**Comment by SimonSapin** [comment]
@KiChjang I don’t remember ever seeing erroneous warnings so far. Have you? Which ones?

**Comment by KiChjang** [comment]
I haven't, but I suppose that's not quite important since we can just use a different nightly version...

**Comment by tigercosmos** [comment]
How to determine let the PR pass or not?
I don't mind to close this one if most members deny this.

**Comment by jdm** [comment]
I haven't seen much enthusiasm for denying warnings from other people, and I still feel strongly that it makes debugging much more frustrating. I'm going to go ahead and close this.

**Comment by SimonSapin** [comment]
> I haven't seen much enthusiasm

I only click the "thumb up" because I didn’t realize I should be more vocal, but I’m rather in favor of doing *something* more to not land PRs that introduce warnings.

Warnings unrelated to what you’re working on at the moment are noise that you need to visually filter out from relevant output at every recompilation. And sending "Fix warnings" PRs is busy work.

@jdm, what do you think of setting `RUSTFLAGS="-D warnings"` on CI? That way debugging is not affected.

**Comment by jdm** [comment]
That sounds like a perfectly fine choice to me!

**Comment by tigercosmos** [comment]
@SimonSapin What CI files should be included?
travis, buildbot?

**Comment by jdm** [comment]
You will want to modify travisCI, Appveyor, and buildbot_steps.yml.

**Pull request closed without merging**
