### PR TITLE
Update rand to 0.7 (fixes #24448)

### LINKED ISSUE #24448: Switch to rand 0.7
This would remove the need for the two forked `rand` crates and also remove `autocfg` from that part of the crate tree.

* [x] [`gaol`](https://github.com/servo/gaol/pull/55)
* [x] [`ipc-channel`](https://github.com/servo/ipc-channel/pull/244)
* [x] [`phf_generator`](https://github.com/sfackler/rust-phf/issues/154)
* [x] [`uuid`](https://github.com/uuid-rs/uuid/issues/431)
* [x] [`ws`](https://github.com/housleyjk/ws-rs/pull/293)

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by SimonSapin** [comment]
> Your changes have decreased the stack size of commonly used DOM struct HTMLSpanElement from 400 to 368

Nice! Do you think the `Option<Atom>` layout optimization could contribute that much?

**Review by jdm — APPROVED** [review]

**Comment by nox** [comment]
> Nice! Do you think the `Option<Atom>` layout optimization could contribute that much?

Yep, seems like it, good idea.

@bors-servo r=jdm

**Comment by CYBAI** [comment]
Failures in magicleap and android builds:

```rust
error[E0432]: unresolved import `xml5ever::rcdom`
  --> components/gfx/platform/freetype/android/font_list.rs:12:15
   |
12 | use xml5ever::rcdom::*;
   |               ^^^^^ could not find `rcdom` in `xml5ever`

error[E0432]: unresolved import `xml5ever::rcdom`
  --> components/gfx/platform/freetype/android/font_list.rs:13:15
   |
13 | use xml5ever::rcdom::{Node, RcDom};
   |               ^^^^^ could not find `rcdom` in `xml5ever`

error[E0433]: failed to resolve: use of undeclared type or module `NodeData`
   --> components/gfx/platform/freetype/android/font_list.rs:173:13
    |
173 |             NodeData::Element { ref name, .. } => &*name.local == "familyset",
    |             ^^^^^^^^ use of undeclared type or module `NodeData`

error[E0433]: failed to resolve: use of undeclared type or module `NodeData`
   --> components/gfx/platform/freetype/android/font_list.rs:190:17
    |
190 |                 NodeData::Element {
    |                 ^^^^^^^^ use of undeclared type or module `NodeData`

error[E0433]: failed to resolve: use of undeclared type or module `NodeData`
   --> components/gfx/platform/freetype/android/font_list.rs:280:17
    |
280 |                 NodeData::Element { ref name, .. } => &*name.local == "nameset",
    |                 ^^^^^^^^ use of undeclared type or module `NodeData`

error[E0433]: failed to resolve: use of undeclared type or module `NodeData`
   --> components/gfx/platform/freetype/android/font_list.rs:300:17
    |
300 |                 NodeData::Element {
    |                 ^^^^^^^^ use of undeclared type or module `NodeData`

error[E0433]: failed to resolve: use of undeclared type or module `NodeData`
   --> components/gfx/platform/freetype/android/font_list.rs:341:17
    |
341 |                 NodeData::Element { ref name, .. } => {
    |                 ^^^^^^^^ use of undeclared type or module `NodeData`

error[E0433]: failed to resolve: use of undeclared type or module `NodeData`
   --> components/gfx/platform/freetype/android/font_list.rs:440:17
    |
440 |                 NodeData::Text { ref contents } => {
    |                 ^^^^^^^^ use of undeclared type or module `NodeData`

error[E0433]: failed to resolve: use of undeclared type or module `NodeData`
   --> components/gfx/platform/freetype/android/font_list.rs:452:17
    |
452 |                 NodeData::Element { ref name, .. } => {
    |                 ^^^^^^^^ use of undeclared type or module `NodeData`

error: aborting due to 9 previous errors
```

**Comment by nox** [comment]
Cherry-picked a commit by @SimonSapin which replaces the use of rcdom by xml-rs, which is already in our crate graph.

@bors-servo r=jdm,nox

**Comment by jdm** [comment]
Needs a `mach fmt`, unfortunately.

**Comment by nox** [comment]
Classic. Glad it happened in a way where your checklist wouldn't have reminded us. :P

@bors-servo r=jdm,nox

**Comment by nox** [comment]
Grr.

@bors-servo retry #24369

**Pull request merged**
