### PR TITLE
layout: Implement `mix-blend-mode` per COMPOSITING § 3.4.1.

### PR DESCRIPTION
**Pull request by pcwalton**
`background-blend-mode` is not yet supported because we don't support
multiple backgrounds yet.

r? @glennw

### CODE REVIEW

**Comment by pcwalton** [comment]
Here's the spec: http://dev.w3.org/fxtf/compositing-1/

**Comment by glennw** [comment]
The test files are missing.

**Comment by pcwalton** [comment]
Doh! Fixed.

**Comment by glennw** [comment]
squash and r=me

**Pull request closed without merging**
