### PR TITLE
Split layout wrappers into style+layout and layout-only functionality

### PR DESCRIPTION
**Pull request by bholley**
This is a step towards removing the dependency of stylo on layout/.

This PR depends on #9004.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9051)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Unit tests are failing: https://travis-ci.org/servo/servo/jobs/98431601

**Comment by bholley** [comment]
r? @pcwalton 

Sorry for the megapatch - there were too many inter-dependencies. Please review quickly if you can, since this has bitrotted several times already.

**Comment by SimonSapin** [comment]
Reviewed 16 of 24 files at r1.
Review status: 16 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/data.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9051#-K6eckPeju5y9HWEyNwt:-K6eckPeju5y9HWEyNwu:1709266081) ([raw file](https://github.com/servo/servo/blob/48a8411c638a953e3b1cc73c2b110278ec991180/components/style/data.rs#L38)):*
I feel that this doesn’t belong here, but I’m guessing that not having it here makes things difficult in other places so don’t worry about it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9051)*

**Comment by bholley** [comment]
*[components/style/data.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9051#-K6eckPeju5y9HWEyNwt:-K6eg-x-QtTrUjYT2uat:360964775) ([raw file](https://github.com/servo/servo/blob/48a8411c638a953e3b1cc73c2b110278ec991180/components/style/data.rs#L38)):*
Yeah, this is needed for parallel DOM traversal. When I hoist parallel.rs into style/, I can move it into that file, which probably makes more sense.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9051)*

**Comment by larsbergstrom** [comment]
I've spent a bunch of time staring at the layout & script portions of this code, and to my eye they preserve the previous behaviors (including clearing out the `Option` properly on `dispose`, panicing at appropriate places if a value is expected but the `Option` is empty, only calling `transmute` as needed, etc.). Not quite confident enough to r+ it yet, though, and would appreciate if @pcwalton or @SimonSapin could check to make sure that they like the structure of the refactoring in terms of which methods ended up where, to make sure it's in line with the design.

I'm very happy with the mechanics, though - they appear to have been preserved across the refactoring, so far as I can tell!

**Comment by Manishearth** [comment]
Overall LGTM, but I'd also like to wait for review from Simon or Patrick.

**Comment by bholley** [comment]
Switching r? @SimonSapin, who will probably be able to review this sooner that @pcwalton.

**Comment by SimonSapin** [comment]
Looks good overall.

---

Reviewed 8 of 24 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/layout/wrapper.rs, line 178 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9051#-K6hY8H9gZZKXM_thS3v:-K6hY8HAZKrYtLM-_wKU:1722143246) ([raw file](https://github.com/servo/servo/blob/48a8411c638a953e3b1cc73c2b110278ec991180/components/layout/wrapper.rs#L178)):*
Nit: please use `as` rather than `transmute` when possible. (I’m kinda scared of unqualified transmute + type inference + code changing over time.)

---

*[components/script/dom/node.rs, line 921 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9051#-K6hSevSrjpJE0jZ2106:-K6hSevTpKdn1a64KM-q:1501525572) ([raw file](https://github.com/servo/servo/blob/48a8411c638a953e3b1cc73c2b110278ec991180/components/script/dom/node.rs#L921)):*
Nit: could this pair of methods be a single method that returns `Option`? It’s more idiomatic to leave it to callers to call `.unwrap()` or `.is_some()` or not.

---

*[components/style/dom.rs, line 32 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9051#-K6hType_VB-6c4FE37e:-K6hType_VB-6c4FE37f:-1946796316) ([raw file](https://github.com/servo/servo/blob/48a8411c638a953e3b1cc73c2b110278ec991180/components/style/dom.rs#L32)):*
Nit: while you’re touching this, please change `uintptr_t` to `usize`. They’re the same, except the latter doesn’t need to be imported.

---

*[components/style/dom.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9051#-K6hUS7D6eMDWlFIohzr:-K6hUS7D6eMDWlFIohzs:-293423658) ([raw file](https://github.com/servo/servo/blob/48a8411c638a953e3b1cc73c2b110278ec991180/components/style/dom.rs#L44)):*
(Re IRC discussion: no need to change anything here, but I haven’t seen the TFoo naming convention anywhere else and I don’t think it’s useful, other than as a not-so-good way to work around name conflicts.)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9051#-:-K6hZPBejSavZj56L6Yh:-499954989)*

**Comment by bholley** [comment]
*[components/style/dom.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9051#-K6hUS7D6eMDWlFIohzr:-K6iyjWJPuqmuu4Qdga0:939591138) ([raw file](https://github.com/servo/servo/blob/48a8411c638a953e3b1cc73c2b110278ec991180/components/style/dom.rs#L44)):*
I'm certainly open to other suggestions. Per IRC discussion, I think it's pretty confusing to have selectors::tree::Element, style::Element, and script::dom::Element, where the former two are traits and the latter is a struct. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9051)*

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/style/dom.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9051#-K6hUS7D6eMDWlFIohzr:-K6izmO0qV9-hgGgvfy6:-961125609) ([raw file](https://github.com/servo/servo/blob/48a8411c638a953e3b1cc73c2b110278ec991180/components/style/dom.rs#L44)):*
One solution is to always call these as `style::Element` and never import directly  Another is `AbstractElement` (hello, Java, old friend). `TElement` is fine by me really, the other solutions don't seem too great.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9051)*

**Comment by bholley** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/node.rs, line 921 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9051#-K6hSevSrjpJE0jZ2106:-K6izf2BTEwcY23JRq4L:997458026) ([raw file](https://github.com/servo/servo/blob/48a8411c638a953e3b1cc73c2b110278ec991180/components/script/dom/node.rs#L921)):*
I can change it, sure. I went with this convention on the layout side because almost all of the cases just .unwrap(), and I found that unnecessarily cluttered and confusing. But that leaves us with the has_data and the maybe_* variants. So I guess just .unwrap()-ing everywhere is in fact the most idiomatic.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9051)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 10 of 14 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9051#-:-K6l9VZMkLptqJfOTI-P:1236647940)*

**Pull request merged**
