### PR TITLE
Implementation of Blob Constructor with test changes

### PR DESCRIPTION
**Pull request by stspyder**
Apologize for the late PR. I see that #9977 already overlaps with some of the work. If that is accepted, then I'll change my PR to reflect just the WPT changes.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/servo/servo/9979)

### CODE REVIEW

**Comment by tbu-** [comment]
@Ms2ger's hint probably also applies here: https://github.com/w3c/FileAPI/issues/30.

Just getting the byte slices out of the blob and the string and pushing them to a result vector would probably perform better, as it is more easily optimizable to a single allocation plus a few memcpys.

**Comment by jdm** [comment]
@bors-servo: r+
These changes make sense. Sorry for sitting on this review for a week! I'm inclined to file followup issues for joining the bytes together as well as the FileAPI spec change.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9979#-:-KDUhsYuDBYAV4GyIOtf:-369850629)*

**Comment by jdm** [comment]
@bors-servo: retry
* silly appveyor

**Comment by larsbergstrom** [comment]
@bors-servo retry
- infra

**Comment by Ms2ger** [comment]
@bors-servo retry
* #9777

**Comment by stspyder** [comment]
Fix for #8397

**Pull request merged**
