### PR TITLE
net: Try to turn on HTTP pooling.

### PR DESCRIPTION
**Pull request by seanmonstar**
rebased and fixed up #6026 

(Can't compile some of the native dependencies on my current machine, so I'll have to rely on travis?).

Also, better if viewed with [w=1](https://github.com/servo/servo/compare/servo:master...seanmonstar:pool?expand=1&w=1).

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6948)

### CODE REVIEW

**Comment by jdm** [comment]
Exciting! Thanks for getting this ball rolling again :)
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/net/http_loader.rs, line 40 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6948#-JvqjqbrjKBhU20XVErG)** ([raw file](https://github.com/servo/servo/blob/3c5d24dbf43e22176d382b6f8bd9a88805c1d8b2/components/net/http_loader.rs#L40)):</sup>
Rebase error?

---

<sup>**[components/net/resource_task.rs, line 27 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6948#-JvqkAIf9K7WjPWaLs6H)** ([raw file](https://github.com/servo/servo/blob/2a3ce5a2b968652b4866f168f84f7589ca146cc8/components/net/resource_task.rs#L27)):</sup>
nit: move this below hyper::mime.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6948)

**Comment by seanmonstar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[components/net/http_loader.rs, line 40 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6948#-JvqjqbrjKBhU20XVErG)** ([raw file](https://github.com/servo/servo/blob/3c5d24dbf43e22176d382b6f8bd9a88805c1d8b2/components/net/http_loader.rs#L40)):</sup>
Indeed. Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6948)

**Comment by seanmonstar** [comment]
Oh dang, travis only does `make tidy`? I thought it ran the test suite. I don't currently have a way to make sure this compiles...

**Comment by jdm** [comment]
Ok, I'll pull locally.

**Comment by seanmonstar** [comment]
It builds! And is a bit different.

Side note: if the `--no-ssl` option could become a compile time option, such that `env!(NO_SSL)` could be used, then the `SslProvider` wouldn't need to be an enum, which would prevent the branch in `wrap_client`.

**Comment by jdm** [comment]
Almost there!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/Cargo.toml, line 45 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6948#-Jw-8emvEa9SGrAz81OA)** ([raw file](https://github.com/servo/servo/blob/7134f33d9feeac981201ba8d237701ca7a8ccf71/components/net/Cargo.toml#L45)):</sup>
This was a mistake I made; we can remove it.

---

<sup>**[components/net/http_loader.rs, line 199 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6948#-Jw-9-QoJdeCpnm08i4P)** ([raw file](https://github.com/servo/servo/blob/7134f33d9feeac981201ba8d237701ca7a8ccf71/components/net/http_loader.rs#L199)):</sup>
This block is no longer necessary afaict; let's unindent everything below it.

---

<sup>**[components/net/lib.rs, line 24 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6948#-Jw-9EMQsthEXO0OuveM)** ([raw file](https://github.com/servo/servo/blob/7134f33d9feeac981201ba8d237701ca7a8ccf71/components/net/lib.rs#L24)):</sup>
Remove this too.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6948)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6948)

**Comment by jdm** [comment]
```
/old-tests/submission/Opera/script_scheduling/087.html
------------------------------------------------------
FAIL  scheduler: multiple defer scripts, one slow loading
```
Can you see if this fails locally for you?

**Comment by seanmonstar** [comment]
I can only compile up to the script crate, so I can't run the WPTs.

**Comment by seanmonstar** [comment]
@jdm I don't recall at what line that ConnectionAborted error was occurring, and the loop you had written.

I've updated hyper to close pooled streams that have errors, so with that other adjustment, this should work.

**Comment by jdm** [comment]
My work is in https://github.com/jdm/servo/tree/httppool, so I guess I'll give that a try tomorrow unless someone else gets to it first.

**Comment by seanmonstar** [comment]
@jdm I pulled in the diff from your commit, and rebased.

**Comment by jdm** [comment]
```
9.59s$ ./mach test-tidy

components/net/http_loader.rs:32: use statement is not in alphabetical order

components/net/http_loader.rs:33: use statement is not in alphabetical order

components/net/resource_task.rs:9: use statement is not in alphabetical order

components/net/resource_task.rs:10: use statement is not in alphabetical order

components/net/resource_task.rs:11: use statement is not in alphabetical order

components/net/resource_task.rs:12: use statement is not in alphabetical order

components/net/resource_task.rs:13: use statement is not in alphabetical order

components/net/resource_task.rs:14: use statement is not in alphabetical order

components/net/resource_task.rs:34: use statement is not in alphabetical order

components/net/resource_task.rs:35: use statement is not in alphabetical order
```

**Comment by seanmonstar** [comment]
grumble alphabet grumble

**Comment by jdm** [comment]
I don't think the code builds right now - there's a `let mut response` outside of the loop, but inside the loop there's another `let mut response =` that shadows it.

**Comment by seanmonstar** [comment]
correct, it wasn't compiling. I also had to update the lockfiles since I'd updated `unicase` to 1.0.0 from 0.1.0 (there was no code change, but I felt it was 1.0 worthy).

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 7 of 7 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6948)

**Comment by seanmonstar** [comment]
Updated tests, marking many that expected TIMEOUT as PASS.

However, a few that were FAIL are now TIMEOUT. I have no way of locally running the wpt tests.

**Comment by jdm** [comment]
I'll take a look at them.

**Comment by jdm** [comment]
Fascinating!
```
 0:05.12 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16557) Full command: /Users/jdm/src/servo/target/debug/servo --cpu --hard-fail -u Servo/wptrunner http://localhost:8000/old-tests/submission/Opera/script_scheduling/085.html --user-stylesheet /Users/jdm/src/servo/resources/ahem.css
(pid:16557) "thread 'http_loader' panicked at 'Http11Message lost its underlying stream somehow', /Users/jdm/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.10/src/http/h1.rs:270"
```

**Comment by jdm** [comment]
```
(pid:16784) "thread 'http_loader' panicked at 'Http11Message lost its underlying stream somehow', /Users/jdm/.cargo/registry/src/github.com-0a35038f75765ae4/hyper-0.6.10/src/http/h1.rs:270"
 0:04.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "stack backtrace:"
 0:04.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "   1:        0x10d286b00 - sys::backtrace::write::h095d0f07f92e7e3eYts"
 0:04.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "   2:        0x10d289ed3 - panicking::on_panic::h5f4115f30a6b4860Z7w"
 0:04.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "   3:        0x10d278e92 - rt::unwind::begin_unwind_inner::h7c54671eea5e313e0Cw"
 0:04.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "   4:        0x10cf12c17 - rt::unwind::begin_unwind::h15331884341034434895"
 0:04.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "   5:        0x10cf73f53 - http::h1::Http11Message::get_mut::h89ef6e1f04f35dcfBGj"
 0:04.83 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "   6:        0x10ace5ba1 - http::h1::Http11Message.HttpMessage::close_connection::he6540d19a3caa4cfQDj"
 0:04.84 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "   7:        0x10cf320d1 - client::response::Response::with_message::h0a1bf58d6ed303adlSa"
 0:04.84 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "   8:        0x10cf31b5d - client::request::Request<Streaming>::send::hf31638ee583678caqNa"
 0:04.84 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "   9:        0x10acc8bbb - http_loader::load::h23f3aea7c64866a5dpa"
 0:04.84 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  10:        0x10acc4187 - http_loader::factory::closure.26120"
 0:04.84 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  11:        0x10acc3f1f - task::spawn_named::closure.26113"
 0:04.84 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  12:        0x10acc3e77 - boxed::F.FnBox<A>::call_box::h8285890207617347537"
 0:04.84 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  13:        0x10acb311b - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h4130720213201258293"
 0:04.85 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  14:        0x10acb2cfd - thread::Builder::spawn_inner::closure.25099"
 0:04.85 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  15:        0x10acb2ca9 - rt::unwind::try::try_fn::h16787200724282224943"
 0:04.85 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  16:        0x10d2898a8 - __rust_try"
 0:04.85 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  17:        0x10d285500 - rt::unwind::try::inner_try::h39d984f71e9cc780Tyw"
 0:04.85 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  18:        0x10acb2c13 - rt::unwind::try::h17106555173943191013"
 0:04.85 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  19:        0x10acb2a8b - thread::Builder::spawn_inner::closure.25075"
 0:04.85 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  20:        0x10acb337c - boxed::F.FnBox<A>::call_box::h15713970663752920389"
 0:04.85 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  21:        0x10d288b9d - sys::thread::Thread::new::thread_start::h999b3790b6d4b23deXv"
 0:04.86 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  22:     0x7fff928ae898 - _pthread_body"
 0:04.86 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:16784) "  23:     0x7fff928ae729 - _pthread_start"
```

**Comment by seanmonstar** [comment]
@jdm boo, panics. I've updated to hyper 0.6.11, which fixes those panics (and some other possible ones). I'm not entirely sure which tests that I've marked as TIMEOUT instead of FAIL should  be reverted...

**Comment by jdm** [comment]
Closing this in favour of #7418.

**Pull request closed without merging**
