### PR TITLE
Fix defineProperty codegen

### PR DESCRIPTION
**Pull request by snf**
This patch should get rid of #5223.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5845)

### CODE REVIEW

**Comment by snf** [comment]
Don't review it yet. I found a bug when the id is a number. We should convert any id object to a string (but few exceptions) inside defineProperty.

**Comment by snf** [comment]
Ok, I will fix that in another PR.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/script/dom/bindings/codegen/CodegenRust.py @ r1
- tests/wpt/metadata/webstorage/builtins.html.ini @ r2
- tests/wpt/metadata/webstorage/in.html.ini @ r2
- tests/wpt/metadata/webstorage/setitem.html.ini @ r2

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 3935 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5845#-JnwfvhJRXLEff3BPlve)** ([raw file](https://github.com/servo/servo/blob/a7a7e2f356da227d957b3cad669a3ceefb90d3af/components/script/dom/bindings/codegen/CodegenRust.py#L3935)):</sup>
Let's file an issue to fix this after the SpiderMonkey upgrade, and leave a TODO here pointing to it.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5845)

**Comment by snf** [comment]
squash?

**Comment by jdm** [comment]
Yep!

**Comment by snf** [comment]
Done!

**Comment by Ms2ger** [comment]
@bors-servo: retry
* #5798

**Pull request merged**
