### PR TITLE
Update rayon to 0.7.1.

### PR DESCRIPTION
**Pull request by heycam**
To take advantage of nikomatsakis/rayon#348.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17105)

### CODE REVIEW

**Comment by heycam** [comment]
cc @julian-seward1 @bholley

**Comment by bholley** [comment]
@bors-servo retry

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.2, Android SDK Platform 25].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

**Comment by larsbergstrom** [comment]
@bors-servo: retry
- Android is fixed now

**Pull request merged**
