### PR TITLE
Remove old features 'clone_from_slice' and 'convert'

### LINKED ISSUE #9495: Remove old features clone_from_slice and convert
```
components/canvas/lib.rs:5:12: 5:28 warning: this feature is stable. attribute no longer needed, #[warn(stable_features)] on by default
components/canvas/lib.rs:5 #![feature(clone_from_slice)]
                                      ^~~~~~~~~~~~~~~~
components/gfx/lib.rs:6:75: 6:82 warning: unused or unknown feature, #[warn(unused_features)] on by default
components/gfx/lib.rs:6 #![cfg_attr(any(target_arch = "x86_64", target_arch = "aarch64"), feature(convert))]
                                                                                                  ^~~~~~~
components/compositing/lib.rs:6:12: 6:28 warning: this feature is stable. attribute no longer needed, #[warn(stable_features)] on by default
components/compositing/lib.rs:6 #![feature(clone_from_slice)]
                                           ^~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by timvandermeij**
Fixes #9495.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9512)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Thanks!

@bors-servo r+

**Comment by timvandermeij** [comment]
Whoops, I made a mistake in my previous commit. After reading http://chrismorgan.info/blog/rust-cfg_attr.html I now know about `cfg_attr`. Could you trigger the tests again?

**Comment by Wafflespeanut** [comment]
Cloning into '.'...
    fatal: did not receive expected object 961038bb24b2ca4290dfe2d287459ca26b7c256e
    fatal: index-pack failed

@bors-servo retry

**Comment by Wafflespeanut** [comment]
Oooh, sorry :)

**Comment by KiChjang** [comment]
@bors-servo retry
* #7846

**Comment by Wafflespeanut** [comment]
@bors-servo retry

#8191

**Pull request merged**
