### PR TITLE
XHR timeouts use same abstraction as scripts timers. (fixes #3396)

### LINKED ISSUE #3396: Intermittent failure in /XMLHttpRequest/event-timeout.htm
This one's fun - the test sets a 5ms timeout on the XHR, and calls setTimeout with a delay of 10ms. The test asserts that the setTimeout is never reached, because the ontimeout handler ends the test. Our timer implementation is messy, in that both the XHR and setTimeout timers have their own tasks which send a message to the script task when they expire. That means that scheduling-wise we have no guarantees that lower timer values will expire and notify the script task before the timers with higher values.

### PR DESCRIPTION
**Pull request by benschulz**
Alright, this is it. Finally the fix for #3396. :D

I'll add two comments via reviewable in a second.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8168)

### CODE REVIEW

**Comment by benschulz** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/xmlhttprequest.rs, line 963 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8HPBRY9-r-RsG0_4)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L963)):</sup>
Actually I still need a `Trusted` later (to send the RunnableMsg). Still, I'd rather not add `HeapSizeOf` for `Trusted`. Should I use a `JS<XMLHttpRequest>`?


---

<sup>**[components/script/timers.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J9PJz80E2UrYgkAkA)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L124)):</sup>
I feel like this entire trait isn't "rusty".


---

<sup>**[components/script/timers.rs, line 189 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8j7PQLxHqdx2le0H)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L189)):</sup>
I don't like that `setTimeout`/`setInterval` and `XMLHttpRequest` are getting this complected. I'd like to file another PR to extract a minimal abstraction based on `ScheduledCallback`. XHR timeouts and (the old) `ActiveTimers` would sit on top of that abstraction. Thoughts?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8168)

**Comment by nox** [comment]
Not a proper review, but some questions and a couple of doc nits.

+S-needs-code-changes 


---

Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/global.rs, line 201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1Jc28uCHRS6T7IxBPP)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/bindings/global.rs#L201)):</sup>
"Schedule"


---

<sup>**[components/script/dom/bindings/global.rs, line 210 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1Jc47vhgy3hNBIYLHI)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/bindings/global.rs#L210)):</sup>
"Unschedule a previously-scheduled callback."


---

<sup>**[components/script/dom/xmlhttprequest.rs, line 963 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8HPBRY9-r-RsG0_4)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L963)):</sup>
I'm pretty sure the `XMLHttpRequest` value isn't owned by `ScheduledXHRTimeout`, so its `HeapSizeOf` impl should ignore it anyway. Same for the `target` field, actually.


---

<sup>**[components/script/dom/xmlhttprequest.rs, line 969 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1Jcp9elhOOmrevkmeh)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L969)):</sup>
Why the explicit deref?


---

<sup>**[components/script/timers.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J9PJz80E2UrYgkAkA)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L124)):</sup>
Given `Box<T>` derefs to `T`, couldn't you just have a trait like this?

```rust
pub trait ScheduledCallback: Clone + JSTraceable + HeapSizeOf {
    fn invoke(self);
}
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8168)

**Comment by benschulz** [comment]
Thanks for the input. =)


---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/xmlhttprequest.rs, line 963 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8HPBRY9-r-RsG0_4)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L963)):</sup>
But shouldn't the overhead of the `Trusted` pointer be counted?


---

<sup>**[components/script/dom/xmlhttprequest.rs, line 969 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1Jcp9elhOOmrevkmeh)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L969)):</sup>
Otherwise I'd have to clone xhr, wouldn't I? (Not a rhetorical question. :D)


---

<sup>**[components/script/timers.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J9PJz80E2UrYgkAkA)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L124)):</sup>
I tried that, but deriving `Clone` ended up [not working](http://is.gd/E6pgKg). It's somewhat odd given `impl Clone for Box<T> where T: Clone`. There were similar errors for implementors of `ScheduledCallback`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8168)

**Comment by eefriedman** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/timers.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J9PJz80E2UrYgkAkA)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L124)):</sup>
The Clone trait isn't object-safe; you can't write `Box<Clone>`, or any variation.

At a slightly higher level, this shouldn't really need to implement clone: a oneshot timer can only execute once, so the callback never actually needs to be cloned.  It should be possible to encode this into the type system.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8168)

**Comment by benschulz** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/timers.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J9PJz80E2UrYgkAkA)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L124)):</sup>
> The Clone trait isn't object-safe; you can't write Box<Clone>, or any variation.

Thanks, this confirms my suspcicion. Also, I just realized that `impl<T> Clone for Box<T> where T: Clone`isn't applicable due to the implicit `Sized` constraint. I'm still getting the hang of rust.

> At a slightly higher level, this shouldn't really need to implement clone

The cloning is currently necessary because `InternalTimerCallback`s need to be cloneable. I'd need to introduce a separate abstraction (see other discussion) to get rid of that requirement on `ScheduledCallback`. Perhaps I should fold it into this PR though…


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8168)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 6 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/xmlhttprequest.rs, line 963 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8HPBRY9-r-RsG0_4)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L963)):</sup>
Trusted is necessary for sending JS pointers between threads; `JS<T>` isn't safe since it could be garbage collected. As for the overhead of the `Trusted` value vs. its pointed-at contents, that's already accounted for by the heap profiling code.


---

<sup>**[components/script/dom/xmlhttprequest.rs, line 969 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1Jcp9elhOOmrevkmeh)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L969)):</sup>
I don't see why. The `Box<Self>` syntax allow us to move out of self at will, same as in the various implementations of `Runnable`.


---

<sup>**[components/script/timers.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J9PJz80E2UrYgkAkA)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L124)):</sup>
@benschulz: I threw together [a diff](https://gist.github.com/jdm/d2f8bebe267388fd85e9) which eliminates the Clone requirement for InternalTimerCallback. Maybe that helps?


---

<sup>**[components/script/timers.rs, line 189 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8j7PQLxHqdx2le0H)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L189)):</sup>
I like that idea in principle. I agree that there's a surprising amount of machinery here for these things.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8168)

**Comment by jdm** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8168)

**Comment by benschulz** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/xmlhttprequest.rs, line 963 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8HPBRY9-r-RsG0_4)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L963)):</sup>
My reasoning to remove the `Trusted` was that the `XMLHttpRequest` isn't leaving the script task anymore. My reasoning for a `JS` pointer was, that it should be reachable by the GC through `ActiveTimers`. However, the intricacies of the various pointer types still escape me. So if you say, `Trusted` is the way to go, then I'll trust you. ;)

(If there's a reference explaining the pointer types in more detail than *[Using DOM types][1]*, I'd appreciate a link.)

[1]: https://github.com/servo/servo/wiki/Using-DOM-types


---

<sup>**[components/script/dom/xmlhttprequest.rs, line 969 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1Jcp9elhOOmrevkmeh)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L969)):</sup>
My understand is that I can't move out of `s` while `s.target.send(…` borrows it. This is the most compact and direct way arround that, I came up with.


---

<sup>**[components/script/timers.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J9PJz80E2UrYgkAkA)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L124)):</sup>
@jdm That's roughly what it used to look like, but it [breaks a test][1]. Essentially the repeating timer needs to be rescheduled before its callback is executed, so that it can unschedule itself. I don't see any way of getting rid of `Clone` before the other refactoring.

[1]: https://github.com/servo/servo/pull/7450#issuecomment-149708963


---

<sup>**[components/script/timers.rs, line 189 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8j7PQLxHqdx2le0H)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L189)):</sup>
Should it be part of this PR, or is it okay if I file a separate one?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8168)

**Comment by jdm** [comment]
Let's rebase and squash this :)
-S-awaiting-review 


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/xmlhttprequest.rs, line 963 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8HPBRY9-r-RsG0_4)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L963)):</sup>
Oh, right. You are correct about the reachability, but the use of `JS<T>` would be harder to prove correct for the compiler in this case due to the whole boxing thing, so let's leave it as Trusted. I don't know of a better reference than one the you linked, but feel free to file an issue (or use the mailing list) to list things you find confusing or incomplete about the current docs!


---

<sup>**[components/script/dom/xmlhttprequest.rs, line 969 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1Jcp9elhOOmrevkmeh)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/dom/xmlhttprequest.rs#L969)):</sup>
Fascinating; https://play.rust-lang.org/?gist=f03483eab3bd1c6b133e&version=stable agrees with you.


---

<sup>**[components/script/timers.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J9PJz80E2UrYgkAkA)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L124)):</sup>
Womp womp.


---

<sup>**[components/script/timers.rs, line 189 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8168#-K1J8j7PQLxHqdx2le0H)** ([raw file](https://github.com/servo/servo/blob/3c687fa484bcb2cb510d7cb9937321a29b4ada43/components/script/timers.rs#L189)):</sup>
Separate is fine with me.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8168)

**Pull request merged**
