### PR TITLE
Remove the layout trace viewer

### PR DESCRIPTION
**Pull request by mbrubeck**
It hasn't worked for quite a while.  Alternately, maybe @glennw could investigate what's broken and file some issues to get it working again.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11397)

### CODE REVIEW

**Comment by metajack** [comment]
Note that there was a lot of interest by the devtools team and from web developers in tools similar to this. It seems a shame this has bitrotted.

**Comment by frewsxcv** [comment]
If there's potential for this to be fixed, it could be moved to a separate repository and hosted on GitHub pages

**Pull request merged**
