### PR TITLE
Stop using Salt-installed Android SDK on CI

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21185)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r? @paulrouget 

I think this makes https://github.com/servo/saltfs/pull/856 unnecessary. (The same change can be done in `python/servo/bootstrap_commands.py` instead.) In what order do you prefer to do things?

**Comment by paulrouget** [comment]
This will make part of it unnecessary. We still need java 8. But it's a good step forward.

Where is `bootstrap-android-and-accept-licences.sh` coming from?

**Comment by SimonSapin** [comment]
I’ll take this as approval :)

@bors-servo r=paulrouget

**Pull request merged**
