### PR TITLE
Use if let in HTMLTableElement::SetCaption.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6291)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-merge 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/script/dom/htmltableelement.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6291)

**Comment by jdm** [comment]
```
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:83:54: 83:60 error: no method named `root` found for type `core::option::Option<dom::bindings::js::Temporary<dom::htmltablecaptionelement::HTMLTableCaptionElement>>` in the current scope
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:83         if let Some(ref caption) = self.GetCaption().root() {
                                                                                                                                          ^~~~~~
note: in expansion of if let expansion
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:83:9: 85:10 note: expansion site
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:83:54: 83:60 help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:83:54: 83:60 help: candidate #1: use `dom::bindings::js::OptionalRootable`
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:84:65: 84:68 error: the type of this value must be known in this context
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:84             assert!(node.RemoveChild(NodeCast::from_ref(caption.r())).is_ok());
                                                                                                                                                     ^~~
<std macros>:1:1: 5:46 note: in expansion of assert!
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:84:13: 84:80 note: expansion site
note: in expansion of if let expansion
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:83:9: 85:10 note: expansion site
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:84:65: 84:68 help: items from traits can only be used if the trait is implemented and in scope; the following traits define an item `r`, perhaps you need to implement one of them:
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:84:65: 84:68 help: candidate #1: `dom::bindings::js::RootedReference`
/home/servo/buildbot/slave/linux1/build/components/script/dom/htmltableelement.rs:84:65: 84:68 help: candidate #2: `dom::bindings::js::OptionalRootedReference`
error: aborting due to 2 previous errors
Could not compile `script`.
```

**Comment by nox** [comment]
Hah. I see that I didn't r+… Well, @Ms2ger did you even compile? ;)

**Comment by Ms2ger** [comment]
No, I can't: #6256.

@bors-servo: r=nox

**Pull request merged**
