### PR TITLE
Allow passing a path to --userscripts

### PR DESCRIPTION
**Pull request by Manishearth**
r? @kmcallister

### CODE REVIEW

**Comment by metajack** [comment]
Assigning @kmcallister since @Manishearth pinged him.

**Comment by kmcallister** [comment]
I am the one who asked for this feature :)

**Comment by kmcallister** [comment]
Putting all this logic in `HTMLHeadElement` seems bad. Let's change that to a call into a separate userscript module.

**Comment by kmcallister** [comment]
r=me with those changes. Thanks for doing this, it'll help with #5260.

**Pull request merged**
