### PR TITLE
Update xml5ever.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10191)

### CODE REVIEW

**Comment by frewsxcv** [comment]
@perlun bors-servo only responds to a list of whitelisted users, sorry!

@bors-servo retry

* https://github.com/servo/servo/issues/10036

**Comment by Ms2ger** [comment]
@bors-servo retry
https://github.com/servo/servo/issues/10036

**Comment by perlun** [comment]
> @perlun bors-servo only responds to a list of whitelisted users, sorry!

Hehe, nice try eh? :wink:

**Pull request merged**
