### PR TITLE
Move unit tests to their own crates, cut time by 96%

### LINKED ISSUE #5291: Move unit tests to dedicated crates
Running `rustc --test` on a large crate (which is what `mach test-unit` currently does, through `cargo test`) often takes as much time or more as building the crate in the first place. This is especially silly for crates that happen to not have any unit tests.

By moving the unit tests we do have and disabling `rustc --test` on "normal" crates, we should be able to reduce the build+test time significantly.

Cargo has `test = false` and `doctest = false` [configuration keys](http://doc.crates.io/manifest.html#configuring-a-target) that can be set in the `[lib]` section of a `Cargo.toml` file.

### PR DESCRIPTION
**Pull request by SimonSapin**
On my laptop, running `./mach test-unit` goes from about 11 minutes to 22 seconds, when run after `./mach build`.

Fix #5291.

### CODE REVIEW

**Comment by metajack** [comment]
@SimonSapin reviewed in Critic.

**Comment by SimonSapin** [comment]
Issues addressed.

**Comment by jdm** [comment]
Mac builder doesn't appear to be logged in, or can't otherwise initialize video things.

**Comment by larsbergstrom** [comment]
The physical servo-mac1 machine is having issues with freezing after the upgrade. The MacStadium folks are looking at it; until then just running everything on servo-mac2.

**Pull request merged**
