### PR TITLE
Start running webdriver tests

### PR DESCRIPTION
**Pull request by jdm**
This branch includes the patches necessary to start running webdriver tests consistently.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13261)

### CODE REVIEW

**Comment by jdm** [comment]
3c04711 and c73ecf7 will need to be upstreamed.

**Comment by jdm** [comment]
I fear that the webdriver tests don't deal well with concurrent processes. I'm not sure how to reduce the number of processes used only for that test type, however. Any ideas, @jgraham?

**Comment by jgraham** [comment]
Run them using a separate command on buildbot which limits the test type using `--test-type wdspec` and process count using `--processes=1`? The existing invocation will also need to select the test types it wants to run rather than doing everything.

**Comment by jdm** [comment]
Bah, that's impossible to test until we finish converting our buildbot instances to use in-tree test configurations :(

**Comment by jdm** [comment]
Specifically, blocked on https://github.com/servo/saltfs/issues/316.

**Comment by aneeshusa** [comment]
The final PR for servo/saltfs#316 has been merged and [deployed](https://github.com/servo/saltfs/pull/504#issuecomment-254929993), so this is no longer blocked.

**Comment by jgraham** [comment]
Remember to upstream changes to wptrunner.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 16 of 18 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/webdriver_server/lib.rs, line 509 at r9](https://reviewable.io:443/reviews/servo/servo/13261#-KVZVTtHJGg0CP-Hdh2I:-KVZVTtIoxjqV1Oh1S8s:bo6c2bu) ([raw file](https://github.com/servo/servo/blob/2449bc73165a66a7a344d720f399e0918d9bfdec/components/webdriver_server/lib.rs#L509)):*
> ```Rust
>     fn handle_dismiss_alert(&mut self) -> WebDriverResult<WebDriverResponse> {
>         //TODO figure out how to interact with blocking native UI
>         Ok(WebDriverResponse::Void)
> ```

Can't we return unsupported operation for now?

---

*[tests/wpt/harness/wptrunner/executors/executorservo.py, line 295 at r9](https://reviewable.io:443/reviews/servo/servo/13261#-KVZaR5wz3dHzDUxjbeW:-KVZaR5xTEEqv_brXMf_:b-fvcvgl) ([raw file](https://github.com/servo/servo/blob/2449bc73165a66a7a344d720f399e0918d9bfdec/tests/wpt/harness/wptrunner/executors/executorservo.py#L295)):*
> ```Python
>     def setup(self, runner):
>         try:
>             self.server = ServoDriverServer(self.logger, binary=self.browser.binary, binary_args=self.browser.binary_args, render_backend=self.browser.render_backend)
> ```

Some more linebreaks here would be nice.

---

*[tests/wpt/harness/wptrunner/executors/executorservo.py, line 334 at r9](https://reviewable.io:443/reviews/servo/servo/13261#-KVZeCst5WPsuuVTA267:-KVZeCsuQieAkPRVfb_j:btbdse7) ([raw file](https://github.com/servo/servo/blob/2449bc73165a66a7a344d720f399e0918d9bfdec/tests/wpt/harness/wptrunner/executors/executorservo.py#L334)):*
> ```Python
> 
> 
> class ServoWdspecExecutor(WdspecExecutor):
> ```

Not necessarily a blocker, but this seems to share all of the code with MarionetteWdSpecExecutor except the protocol. Maybe we can construct a base class that is just parameterized by the protocol class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13261#-:-KVZegrKmUf-I_rBdHH7:b-j1sqhv)*

**Comment by jdm** [comment]
Tracking this work in #15274.

**Pull request closed without merging**
