### PR TITLE
layout: Disallow margins from collapsing through block formatting contexts per CSS 2.1 § 8.3.1.

### LINKED ISSUE #10449: Block formatting contexts should never collapse margins
Here is a test case:

```html
<style>

  main {
    height: 300px;
    width: 250px;
    background-image: linear-gradient(to bottom, red, blue);
    overflow: scroll;
  }

  div {
    margin-top: 200px;
    height: 200px;
    width: 200px;
    overflow: scroll;
  }

  p {
    height: 250px;
    background-image: linear-gradient(to bottom, white, black);
    margin: 0;
  }

</style>
<main>
  <div>
    <p></p>
  </div>
</main>
```

cc @paulrouget

### PR DESCRIPTION
**Pull request by pcwalton**
Closes #10449.

r? @mbrubeck

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10458)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r-
Missing MANIFEST.json changes.

**Comment by jdm** [comment]
By which I mean the reference HTML files contain `<link ref="match">` which makes them look like tests themselves.

**Comment by KiChjang** [comment]
```
Ran 4651 tests finished in 1075.0 seconds.
  • 4650 ran as expected. 1362 tests skipped.
  • 1 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/css/block_formatting_context_containing_floats_a.html
  └   → /_mozilla/css/block_formatting_context_containing_floats_a.html ffe721099194e2bc0d54d4cf5c910b308aa810c4
/_mozilla/css/block_formatting_context_containing_floats_ref.html b4db0bf47752bbf4453dccc70d814635c95f441b
Testing ffe721099194e2bc0d54d4cf5c910b308aa810c4 == b4db0bf47752bbf4453dccc70d814635c95f441b
```

**Comment by Ms2ger** [comment]
And
```
  ▶ PASS [expected FAIL] /css21_dev/html4/margin-collapse-009.htm
```

**Comment by mbrubeck** [comment]
r=mbrubeck

-S-awaiting-review 

---

Reviewed 1 of 5 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10458#-:-KEs9fU5S9Rety_lwGnF:547006267)*

**Comment by jdm** [comment]
```
  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/Flexible-order.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/adjacent-floats-001.htm

  ▶ FAIL [expected PASS] /css21_dev/html4/bidi-010b.htm
  └   → /css21_dev/html4/bidi-010b.htm 27a29e0bbf6d29d45e42c137d12ca337ff55c7b5
/css21_dev/html4/reference/bidi-007b-ref.htm e2db4f9e8c9e0225f812ddcf18dce6d0263e896f
Testing 27a29e0bbf6d29d45e42c137d12ca337ff55c7b5 == e2db4f9e8c9e0225f812ddcf18dce6d0263e896f

  ▶ PASS [expected FAIL] /css21_dev/html4/border-right-color-175.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/c414-flt-fit-002.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/c414-flt-fit-003.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/c414-flt-fit-004.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/c414-flt-fit-005.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/c414-flt-fit-006.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/clear-002.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/clear-float-007.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/clear-float-008.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/clear-float-004.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/clear-float-005.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/clear-float-006.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/clear-float-009.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/float-006.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/float-applies-to-009.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/float-applies-to-012.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/float-non-replaced-height-001.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/floats-003.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/floats-004.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/floats-123.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/floats-141.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/floats-146.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/floats-144.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/floats-145.htm

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-018.htm
  └   → /css21_dev/html4/margin-collapse-018.htm 271a150679e76dd6ad73e929bc86d85239cd9891
/css21_dev/html4/reference/clearance-006-ref.htm 150217045eeb0235733c92cf3c2ce2644f1f15a3
Testing 271a150679e76dd6ad73e929bc86d85239cd9891 == 150217045eeb0235733c92cf3c2ce2644f1f15a3

  ▶ PASS [expected FAIL] /css21_dev/html4/position-absolute-007.htm
```

**Comment by pcwalton** [comment]
Jackpot!

**Comment by pcwalton** [comment]
The failing test is confusing me. I believe it can be reduced to this:

https://gist.github.com/pcwalton/9d18b3d3ccdddd519e0bd2ec5fadccfc

In Gecko and WebKit, the green box is 32px down in the first case and 0px down in the second case. This seems strange to me, because the presence of clearance is lowering the float ceiling of floats *earlier* in the document. I assume this has to do with margin collapse, but I'm having trouble finding where in the spec this is mandated. @SimonSapin, perhaps you can help?

**Comment by pcwalton** [comment]
WeasyPrint replicates Gecko/WebKit's behavior.

**Comment by SimonSapin** [comment]
Is it this rule?

https://drafts.csswg.org/css2/visuren.html#float-rules

> A floating box's outer top may not be higher than the top of its containing block. When the float occurs between two collapsing margins, the float is positioned as if it had an otherwise empty anonymous block parent taking part in the flow. The position of such a parent is defined by the rules in the section on margin collapsing. 

`#a` is not "in the flow" since it’s a float, which makes `#b` the first in-flow child of `<body>`, which makes the top margins of `<body>` and `#b` "adjoining" (even if the former is zero) which makes them collapse.

So the quoted rule applies and there’s an hypothetical block around `#a`. Since that blocks has no in-flow content, margins collapse through it.

Then I believe this rule applies:

https://drafts.csswg.org/css2/box.html#collapsed-through
> If the element's margins are collapsed with its parent's top margin, the top border edge of the box is defined to be the same as the parent's. 

The top border edge of `<body>` is below its top margin, which is collapsed with that of `#b`.

**Comment by pcwalton** [comment]
r? @mbrubeck (the second commit)

That should fix the test failures.

**Comment by mbrubeck** [comment]
@bors-servo r+

---

Reviewed 35 of 37 files at r8, 5 of 5 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10458#-:-KFKXKSLZgvPAk6CDw89:1236647940)*

**Comment by notriddle** [comment]
Everything's cosher except the `MANIFEST.json`.

**Comment by pcwalton** [comment]
`floats_145.htm` failed. Will this never end?

**Comment by pcwalton** [comment]
Actually, that one seems to have been failing before, so I'll just add the expected failure back if there are no objections.

**Comment by KiChjang** [comment]
```
Ran 9969 tests finished in 951.0 seconds.
  • 9968 ran as expected. 130 tests skipped.
  • 1 tests passed unexpectedly

Tests with unexpected results:
  ▶ PASS [expected FAIL] /css21_dev/html4/floats-145.htm
```

**Comment by pcwalton** [comment]
Ugh! This is intermittent or platform specific, then.

**Comment by pcwalton** [comment]
I believe that `floats-145.htm` is a bad test for the following reason. The test assumes that a border on the bottom of an inline element is placed in the exact same Y position as a float with ceiling below that inline. The border on the bottom of an inline box is placed right below the content area of that box—in the case of text, this is the baseline position + the font descent value. The ceiling of a float below a block with auto height containing inlines and no borders/padding/margins is equal to the top of that block plus the *line height* of the inline's line box. This inline has `line-height` set to `normal`. Thus the test assumes that the `normal` line height of the inline's line box is equal to the ascent plus the descent of the font. However, there is no guarantee in the spec that this is the case. https://www.w3.org/TR/CSS22/visudet.html#propdef-line-height specifies:

"`normal`: Tells user agents to set the used value to a "reasonable" value based on the font of the element. The value has the same meaning as <number>. We recommend a used value for 'normal' between 1.0 to 1.2. The computed value is 'normal'."

In Servo, in order to handle `normal` we ask the font for a reasonable line height given its metrics. (See `layout::text::line_height_from_style()`.) I believe that this yields different values on Linux and Mac, and as a result the test fails on Mac and passes on Linux. The spec seems to allow us to do this. *Gecko is doing something similar, and as a result Gecko fails this test just as Servo does.* Blink and WebKit seem to pass this test.

Can you check my reasoning here, @mbrubeck and/or @SimonSapin? If this is correct, I'd like to ignore this test.

**Comment by mbrubeck** [comment]
> Can you check my reasoning here, @mbrubeck and/or @SimonSapin? If this is correct, I'd like to ignore this test.

Yes, I agree. We should also file a bug or patch against the CSSSWG tests.

**Comment by Ms2ger** [comment]
https://lists.w3.org/Archives/Public/public-css-testsuite/2016Apr/0028.html

**Comment by SimonSapin** [comment]
Can we change the test to set `line-height` to some fixed number, to avoid this platform/font dependence?

**Comment by Ms2ger** [comment]
https://lists.w3.org/Archives/Public/public-css-testsuite/2016Apr/0033.html

**Pull request merged**
