### PR TITLE
Shorthand with variable reference should not have extra whitespace after colon for serialization.

### LINKED ISSUE #15295: Shorthand with variable reference should not have extra whitespace after colon for serialization
```html
<!DOCTYPE html>
<div style="font:var(--a);"></div>
<script>
alert(document.querySelector('div').style.cssText);
</script>
```

The above code outputs `font: var(--a);` while it should be `font:var(--a);` like what it does for longhands. Otherwise, `cssText` would not be idempotent.

You can see that if the declaration is `font-size:var(--a);`, it would output `font-size:var(--a);` rather than `font-size: var(--a);`.

The relevant code is probably https://github.com/servo/servo/blob/master/components/style/properties/declaration_block.rs#L484-L486

Probably simply need to make this branch do nothing rather than write a whitespace.

### PR DESCRIPTION
**Pull request by emilio**
This is https://github.com/servo/servo/pull/15422 + a manifest update. Fixes  #15295.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16135)

### CODE REVIEW

**Comment by emilio** [comment]
(r? @upsuper  for the last two commits, which are non-trivial)

**Comment by upsuper** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/properties/declaration_block.rs, line 436 at r2](https://reviewable.io:443/reviews/servo/servo/16135#-KgMlYLca2pUGbMUCDAv:-KgMlYLca2pUGbMUCDAw:b-n05iqq) ([raw file](https://github.com/servo/servo/blob/1746b900ca7b01ebb385ff45ca295259399f1429/components/style/properties/declaration_block.rs#L436)):*
> ```Rust
>                     // a CSS value of current longhands.
>                     let mut value = String::new();
>                     let has_variables = {
> ```

It doesn't seem to me wrapping the following lines inside this block makes any sense. Could you unwrap them?

---

*[components/style/properties/declaration_block.rs, line 446 at r2](https://reviewable.io:443/reviews/servo/servo/16135#-KgMmCSBXg1m4y3lMPHO:-KgMmCSBXg1m4y3lMPHP:b4kg1y5) ([raw file](https://github.com/servo/servo/blob/1746b900ca7b01ebb385ff45ca295259399f1429/components/style/properties/declaration_block.rs#L446)):*
> ```Rust
>                             AppendableValue::Css { with_variables, .. } => with_variables,
>                             _ => false,
>                         };
> ```

I think you actually don't need to call into `append_declaration_value` if `appendable_value` is already `AppendableValue::Css`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16135)*

**Comment by upsuper** [comment]
Sorry for the delay. I somehow missed the review request :/

**Comment by upsuper** [comment]
And r=me with the issues addressed.

**Pull request merged**
