### PR TITLE
Actually store the overflow for inline-block elements.

### LINKED ISSUE #7571: overflow:hidden + inline-block + position:relative: element not painted
```html
<style>
  div {
    overflow:hidden;
    display:inline-block;
    position:relative;
    width:100px;
    height:100px;
    background:red
  }
</style>
<div></div>
```

The `div` is not visible. Remove one of them: `overflow|display|position`, and the div shows up.

screen shot 2015-09-09 at 07 52 12

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #7571

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7588)

### CODE REVIEW

**Comment by jdm** [comment]
Sorry, I'm no good for reviewing layout code. Let's try @mbrubeck.

**Comment by notriddle** [comment]
Alright, then. r? @mbrubeck

**Comment by jdm** [comment]
Sorry, this is #7625 again. We'll sort it out.

**Comment by mbrubeck** [comment]
@bors-servo retry

#7422

**Pull request merged**
