### PR TITLE
Remove whitespace when serializing operators in attribute selectors

### LINKED ISSUE #17181: Do not add spaces when serializing operators in attribute selectors
Servo serializes `[a="b"]` as `[a = "b"]`, other browsers omit the spaces.

Relevant code: https://github.com/servo/servo/blob/2da8eb0342f6701b5365116b96113c83a1599b1f/components/selectors/attr.rs#L79

Simplified testcase:

```html
<style type="text/css">
  div [a=b]{}
</style>
<script type="text/javascript">document.write(document.styleSheets[0].cssRules[0].selectorText)</script>
```

This causes stylo (not run on Servo CI) failures on:

```
  /selectors/attribute-selectors/attribute-case/cssom.html
  /selectors/attribute-selectors/attribute-case/semantics.htm
  /selectors/attribute-selectors/attribute-case/syntax.html
```

### PR DESCRIPTION
**Pull request by achiwhane**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17181.

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17203)

### CODE REVIEW

**Comment by jdm** [comment]
From `./mach test-unit -p style`:
```
---- parser::tests::test_parsing stdout ----

	thread 'parser::tests::test_parsing' panicked at 'assertion failed: `(left == right)` (left: `"[attr|=\"foo\"]"`, right: `"[attr |= \"foo\"]"`)', /home/travis/build/servo/servo/components/selectors/parser.rs:1717
```

**Comment by Manishearth** [comment]
You'll need to update the tests in components/selectors/parser.rs to be ok with spaces too.

**Comment by Manishearth** [comment]
@bors-servo try

hm, infra

**Comment by achiwhane** [comment]
Hey, sorry for the delay. I'm out of town right now and will get this fixed by the coming Tuesday or so.

**Comment by Manishearth** [comment]
@jyc had fixes for the tests here, perhaps he can help take this over the finish line?

**Comment by Manishearth** [comment]
Please rebase your changes instead of merging, `git rebase origin/master`

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/cssom.html:
  └ PASS [expected FAIL] [foo="bar"] /* sanity check */ getting CSSRule#cssText

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/cssom.html:
  └ PASS [expected FAIL] [foo="bar"] /* sanity check */ getting CSSRule#cssText in @media

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/cssom.html:
  └ PASS [expected FAIL] [foo="bar" i] getting CSSRule#cssText

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/cssom.html:
  └ PASS [expected FAIL] [foo="bar" i] getting CSSRule#cssText in @media

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/cssom.html:
  └ PASS [expected FAIL] [foo="bar" /**/ i] getting CSSRule#cssText

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/cssom.html:
  └ PASS [expected FAIL] [foo="bar" /**/ i] getting CSSRule#cssText in @media

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/cssom.html:
  └ PASS [expected FAIL] [foo="bar"/**/i] getting CSSRule#cssText

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/cssom.html:
  └ PASS [expected FAIL] [foo="bar"/**/i] getting CSSRule#cssText in @media
```

**Comment by Manishearth** [comment]
Please apply the following patch after rebasing on to master:

(Alternatively, use https://github.com/manishearth/servo/tree/pr-17203 or tick the "allow maintainers to push changes" box on this pull request)

<details>
```patch
diff --git a/tests/wpt/metadata/selectors/attribute-selectors/attribute-case/cssom.html.ini b/tests/wpt/metadata/selectors/attribute-selectors/attribute-case/cssom.html.ini
index 4b2a69d..ed81ef0 100644
--- a/tests/wpt/metadata/selectors/attribute-selectors/attribute-case/cssom.html.ini
+++ b/tests/wpt/metadata/selectors/attribute-selectors/attribute-case/cssom.html.ini
@@ -1,65 +1,41 @@
 [cssom.html]
   type: testharness
-  [[foo="bar"\] /* sanity check */ getting CSSRule#cssText]
-    expected: FAIL
-
   [[foo="bar"\] /* sanity check */ getting CSSStyleRule#selectorText]
     expected: FAIL
 
   [[foo="bar"\] /* sanity check */ setting CSSStyleRule#selectorText]
     expected: FAIL
 
-  [[foo="bar"\] /* sanity check */ getting CSSRule#cssText in @media]
-    expected: FAIL
-
   [[foo="bar"\] /* sanity check */ getting CSSStyleRule#selectorText in @media]
     expected: FAIL
 
   [[foo="bar"\] /* sanity check */ setting CSSStyleRule#selectorText in @media]
     expected: FAIL
 
-  [[foo="bar" i\] getting CSSRule#cssText]
-    expected: FAIL
-
   [[foo="bar" i\] getting CSSStyleRule#selectorText]
     expected: FAIL
 
-  [[foo="bar" i\] getting CSSRule#cssText in @media]
-    expected: FAIL
-
   [[foo="bar" i\] getting CSSStyleRule#selectorText in @media]
     expected: FAIL
 
-  [[foo="bar" /**/ i\] getting CSSRule#cssText]
-    expected: FAIL
-
   [[foo="bar" /**/ i\] getting CSSStyleRule#selectorText]
     expected: FAIL
 
   [[foo="bar" /**/ i\] setting CSSStyleRule#selectorText]
     expected: FAIL
 
-  [[foo="bar" /**/ i\] getting CSSRule#cssText in @media]
-    expected: FAIL
-
   [[foo="bar" /**/ i\] getting CSSStyleRule#selectorText in @media]
     expected: FAIL
 
   [[foo="bar" /**/ i\] setting CSSStyleRule#selectorText in @media]
     expected: FAIL
 
-  [[foo="bar"/**/i\] getting CSSRule#cssText]
-    expected: FAIL
-
   [[foo="bar"/**/i\] getting CSSStyleRule#selectorText]
     expected: FAIL
 
   [[foo="bar"/**/i\] setting CSSStyleRule#selectorText]
     expected: FAIL
 
-  [[foo="bar"/**/i\] getting CSSRule#cssText in @media]
-    expected: FAIL
-
   [[foo="bar"/**/i\] getting CSSStyleRule#selectorText in @media]
     expected: FAIL
 </details>

**Comment by jdm** [comment]
@achiwhane Are you planning to address the previous comment?

**Comment by jdm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
