### PR TITLE
Fix ServiceWorker in multiprocess

### LINKED ISSUE #15217: Service worker code only supports a single content process
When a new content process is spawned, we send a `SWManagerMsg::OwnSender` message to the constellation, which does
```rust
                // store service worker manager for communicating with it.
                self.swmanager_chan = Some(sw_sender);
```

and any previous value of that field is gone.

### LINKED ISSUE #26100: ServiceWorker: allow for a network mediator per origin
Mirror problem of https://github.com/servo/servo/issues/15217

Currently the [`CoreResourceManager`](https://github.com/servo/servo/blob/e66ab111a6fb5ea9fc7684a0ebeddbe6aa2134f1/components/net/resource_thread.rs#L431) only has one `swmanager_chan`, which means that starting multiple `ServiceWorkerManager` will overwrite previous values and only the last one will work as a network mediator. 

https://github.com/servo/servo/blob/e66ab111a6fb5ea9fc7684a0ebeddbe6aa2134f1/components/net/resource_thread.rs#L303

Instead, the `CoreResourceManager` should own a map of `ImmutableOrigin` -> `Option<IpcSender<CustomResponseMediator>>`

### PR DESCRIPTION
**Pull request by gterzian**
FIX #15217
FIX #26100

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by jdm** [comment]
I'm impressed by how much more readable the resulting infrastructure is here.

**Comment by gterzian** [comment]
Ok this one is ready for review. @SimonSapin r? or @jdm r?

**Comment by CYBAI** [comment]
👀

```
error[E0599]: no method named `register_with_background_hang_monitor` found for enum `constellation::sandboxing::UnprivilegedContent` in the current scope
    --> components/servo/lib.rs:1018:38
     |
1018 |                 unprivileged_content.register_with_background_hang_monitor()
     |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `constellation::sandboxing::UnprivilegedContent`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0599`.
error: could not compile `libservo`.
```

**Comment by gterzian** [comment]
@bors-servo retry 

- UWP dev build failure

**Comment by CYBAI** [comment]
seems we're not able to build on windows 👀

```rust
error[E0432]: unresolved import `crate::sandboxing`
 --> components\constellation\pipeline.rs:6:12
  |
6 | use crate::sandboxing::{spawn_multiprocess, UnprivilegedContent};
  |            ^^^^^^^^^^ maybe a missing crate `sandboxing`?
error[E0432]: unresolved import `crate::sandboxing`
 --> components\constellation\serviceworker.rs:5:12
  |
5 | use crate::sandboxing::{spawn_multiprocess, UnprivilegedContent};
  |            ^^^^^^^^^^ maybe a missing crate `sandboxing`?
error: aborting due to 2 previous errors
```

**Comment by gterzian** [comment]
Ok let's try this

@bors-servo try=wpt

**Comment by gterzian** [comment]
Ah ok `try=wpt` is not going to help because I guess it only runs a subset and that's why it was passing previously.

**Pull request merged**
