### PR TITLE
Dedupe num-traits

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21372)

### CODE REVIEW

**Comment by jdm** [comment]
Ok, so this broke the build for every platform that uses gstreamer. That probably means that the media crate update includes a change that doesn't work.

**Comment by jdm** [comment]
https://github.com/servo/media/commit/29e4280d4d5cb9ba1080aef76f1546947cfc5ba5 looks very suspicious to me. I suspect we have never actually successfully compiled the gstreamer backend on our CI before that revision. @Manishearth can you confirm?

**Comment by Manishearth** [comment]
Yeah, servo-media wasn't compiling the right backend for a short while (https://github.com/servo/media/commit/e5b18a2a1305c423f0d33b157824e84d500a8343#diff-32f57fbac3caf57b942d32855207d6b7)

But this was _after_ I'd fixed the CI for linux, IIRC. I'm surprised it's broken again.

**Comment by Manishearth** [comment]
Since buildbot doesn't really group these together:

<details>

```
sqlite> select * from build_res where repo='servo' and num='21372';
servo|21372|android|1|http://build.servo.org/builders/android/builds/12169|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|android-x86|1|http://build.servo.org/builders/android-x86/builds/283|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|arm32|1|http://build.servo.org/builders/arm32/builds/12368|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|arm64|1|http://build.servo.org/builders/arm64/builds/12412|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|linux-dev|0|http://build.servo.org/builders/linux-dev/builds/12462|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|linux-rel-css|0|http://build.servo.org/builders/linux-rel-css/builds/9380|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|linux-rel-wpt|0|http://build.servo.org/builders/linux-rel-wpt/builds/9383|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|mac-dev-unit|0|http://build.servo.org/builders/mac-dev-unit/builds/12504|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|mac-rel-css1|0|http://build.servo.org/builders/mac-rel-css1/builds/4940|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|mac-rel-css2|0|http://build.servo.org/builders/mac-rel-css2/builds/4944|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|mac-rel-wpt1|0|http://build.servo.org/builders/mac-rel-wpt1/builds/9210|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|mac-rel-wpt2|0|http://build.servo.org/builders/mac-rel-wpt2/builds/9250|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|mac-rel-wpt3|0|http://build.servo.org/builders/mac-rel-wpt3/builds/5013|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|mac-rel-wpt4|0|http://build.servo.org/builders/mac-rel-wpt4/builds/4957|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
servo|21372|windows-msvc-dev|0|http://build.servo.org/builders/windows-msvc-dev/builds/7861|50c3c5d16ca3393898ba20d80c858b4b34dedd8e
```
</details>

**Comment by Manishearth** [comment]
Ah, so this is the gstplayer dependency that was added around the time we were figuring out CI -- I was doing the ARM stuff after I had regular linux working, and this snuck in. I know how to fix this (except Windows, perhaps)

**Comment by Manishearth** [comment]
@bors-servo try retry

linux will still fail, but with luck mac and windows will work now

**Comment by Manishearth** [comment]
@bors-servo try=linux retry clean

homu can't handle multiple try builds but buildbot can

**Comment by Manishearth** [comment]
[windows](http://build.servo.org/builders/windows-msvc-dev/builds/7885), [linux](http://build.servo.org/builders/linux-dev/builds/12489)

**Comment by Manishearth** [comment]
what

**Comment by Manishearth** [comment]
linux-dev and windows works, but the WPT builds are still failing?? (linux-dev has no problems with the gstplayer dep now)

**Comment by Manishearth** [comment]
There are some new failures of tests that were previously timing out. We can update the expectations for now, I'll investigate.

**Comment by Manishearth** [comment]
The issue was https://github.com/servo/saltfs/pull/875, and the WPT/CSS builders were having trouble because for WPT we add osmesa to the dynamic lib search path, except we replace it instead of appending to it. Fixed.

r? @jdm on the new commits (and the salt PR, which is already deployed)

**Comment by Manishearth** [comment]
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Multiple history traversals from the same task", "test": "/html/browsers/history/the-history-interface/traverse_the_history_1.html", "line": 177747, "action": "test_result", "expected": "FAIL"}
```

intermittent, probably?

**Comment by Manishearth** [comment]
Bunch of websocket intermittents in http://build.servo.org/builders/mac-rel-wpt4/builds/4984, html/browsers/history/the-history-interface/traverse_the_history_1.html now passes in html/browsers/history/the-history-interface/traverse_the_history_1.html http://build.servo.org/builders/mac-rel-wpt2/builds/9280 (looks like a permapass?)

Everything else is green.

**Comment by Manishearth** [comment]
Also, so that I don't have to trawl through pages of waterfall to find old build results ever again, https://github.com/servo/homu/pull/169

**Pull request merged**
