### PR TITLE
Bump euclid to 0.13 and heapsize to 0.4

### PR DESCRIPTION
**Pull request by Eijebong**
This is necessary for the serde 1.0 update.

--
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] These changes do not require tests because it's just a dependency bump

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17104)

### CODE REVIEW

**Comment by jdm** [comment]
There appear to be many other packages updating at well...

**Comment by Eijebong** [comment]
Well technically I updated everything that was depending on heapsize 0.4

**Comment by jdm** [comment]
Ah, that makes more sense.
@bors-servo: r+

**Comment by larsbergstrom** [comment]
@bors-servo: retry
- Android is fixed now

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /_mozilla/css/text_decoration_underline_subpx_a.html
  └   → /_mozilla/css/text_decoration_underline_subpx_a.html eb603a9d8941aee44b9aad75877e1fe7d90c247e
/_mozilla/css/text_decoration_underline_subpx_ref.html eb603a9d8941aee44b9aad75877e1fe7d90c247e
Testing eb603a9d8941aee44b9aad75877e1fe7d90c247e != eb603a9d8941aee44b9aad75877e1fe7d90c247e
```
I suspect this is caused by upgrading webrender.

**Comment by Eijebong** [comment]
Mhhh ;( Can someone that actually knows what's going on have a look ?

**Comment by jdm** [comment]
One test file includes an underline and the other does not; the test is verifying that the rendered results are different. In this case the underline is now missing from the test that includes it. Can you reproduce this failure locally?

**Comment by glennw** [comment]
I can't reproduce that failure locally with the test as it is. However, if I set the font size to 14.4px - then the underline disappears with this PR, but is present in servo master. So that seems like a reasonable way to reproduce the issue - I'll investigate today.

**Comment by glennw** [comment]
Potential fix here https://github.com/servo/webrender/pull/1319.

Note that once we get that merged and updated in this PR, there will also be a few test expectation updates we need to add to this PR. Specifically, there are three new failures - but these tests also fail in Gecko and Chrome, so it should be fine to disable them for now. Details https://github.com/servo/webrender/pull/1292#issuecomment-304132642.

**Comment by glennw** [comment]
@Eijebong OK, https://github.com/servo/webrender/pull/1319 has landed. So if you update the WR hash in this PR, hopefully that will fix the subpx text failure. Then we'll need to do the test expectation updates I mentioned above.

**Comment by Eijebong** [comment]
What's wrong with appveyor ? :(

Also can someone ask @bors-servo to retry ?

**Comment by emilio** [comment]
@bors-servo r+

Appveyor doesn't block landing FWIW.

**Comment by emilio** [comment]
More updates are needed.

```
Tests with unexpected results:
  ▶ PASS [expected FAIL] /compositing-1_dev/html/mix-blend-mode-blended-with-transform-and-perspective.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-input-019.htm

  ▶ PASS [expected FAIL] /css21_dev/html4/block-non-replaced-height-001.htm
```

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /_mozilla/css/block_formatting_context_complex_a.html
  └   → /_mozilla/css/block_formatting_context_complex_a.html 238c28274442bbad7d6a04caeb06a695ba98b115
/_mozilla/css/block_formatting_context_complex_ref.html 7db3890ea65aa38d696dfe9158ddf671d9de72a1
Testing 238c28274442bbad7d6a04caeb06a695ba98b115 == 7db3890ea65aa38d696dfe9158ddf671d9de72a1

  ▶ FAIL [expected PASS] /_mozilla/css/inline_block_overflow_hidden_a.html
  └   → /_mozilla/css/inline_block_overflow_hidden_a.html 166369590684f747242d7b4e33ad536822176f5b
/_mozilla/css/inline_block_overflow_hidden_ref.html 2ced5bf7487dfedb4614d62c84d84bf5235d4ec6
Testing 166369590684f747242d7b4e33ad536822176f5b == 2ced5bf7487dfedb4614d62c84d84bf5235d4ec6

  ▶ FAIL [expected PASS] /_mozilla/css/input_selection_a.html
  └   → /_mozilla/css/input_selection_a.html 7213567830dda6a2c81e4baec7a2d71fd68cfbf1
/_mozilla/css/input_selection_ref.html f96057a96e7b2bfa36fe38ae33ce935993b118d8
Testing 7213567830dda6a2c81e4baec7a2d71fd68cfbf1 == f96057a96e7b2bfa36fe38ae33ce935993b118d8
```

**Comment by jdm** [comment]
screen shot 2017-06-01 at 11 22 22 am
screen shot 2017-06-01 at 11 23 28 am
screen shot 2017-06-01 at 11 24 12 am

**Comment by glennw** [comment]
Those are not expected fails - I'll see if I can repro on mac today.

**Comment by glennw** [comment]
I can repro these locally on a mac mini - will investigate today.

**Comment by glennw** [comment]
I have a fix here - https://github.com/servo/webrender/pull/1331. This fixes the mac issues above.

Unfortunately, it does change a couple of those transform test expectations that fail on Gecko and Chrome, but we will just have to live with those for now by changing the test expectations again.

So, once the PR above is reviewed and merged, we'll need to update the WR hash here, do a try run, update the test expectations, and then we *should* be able to merge this.

I've run this PR through the complete WPT / CSS test suites locally on both Linux and Mac, and the only differences are the test expectations I mentioned above.

WR updates aren't normally this difficult, thanks for your patience!

**Comment by glennw** [comment]
Great, those are the two tests that differed locally for me too - we can mark those as expected fails.

**Comment by Eijebong** [comment]
Wut, there is one that passed and is an expected fail. I guess you meant that ^^

**Comment by glennw** [comment]
Yea - the pass is (I think) one that we've added an expected fail for in this PR, which we can now remove.

I *think* that painting order fail (which is a 1px rounding issue) is mac-only too - there should be some example .ini files that show how to mark a test as failing on one platform only. Nearly there! :)

**Comment by Eijebong** [comment]
Okay', this should work :)
And if I understood correctly how to do that
@bors-servo: r=emilio

**Comment by glennw** [comment]
Looks like ```mix-blend-mode-parent-with-3D-transform.htm``` is a new pass on mac, and the other crash in that test is a known intermittent, so we shouldn't need to do anything there.

**Comment by Eijebong** [comment]
Not sure if it's an expected failure or not

**Comment by glennw** [comment]
That test failure is not one I've seen before, and it wasn't happening locally for me either. I'll investigate next week, unless @jdm knows if it's an existing issue?

**Comment by jdm** [comment]
It is not a failure that I recognize.

**Comment by glennw** [comment]
I've rebased this and pushed to @Eijebong branch. Let's see if that failure is still occurring on CI, while I try to reproduce it locally.

@bors-servo try

**Comment by glennw** [comment]
Testing if the ```stylesheet_media_queries.html``` failure is intermittent - it seems unrelated to this PR.

**Comment by glennw** [comment]
@bors-servo retry
 * Infra?? [mac failure is: hdiutil: create failed - error -5341]

**Comment by glennw** [comment]
@bors-servo try
 * Updated test expectations (the transform failure is consistent on mac + linux).

**Comment by glennw** [comment]
The snap rect changes in WR seem to be causing machine specific failures on CI, which is not a good sign. I've created a PR in WR to revert those for now - https://github.com/servo/webrender/pull/1339. Once that lands, we should be able to undo (most of) the test expectation changes here and finally land it.

**Comment by kvark** [comment]
The WR PR is merged now. This PR should be unblocked.

**Comment by Eijebong** [comment]
Ok, now the question is: Which test expectations do we need to revert...

**Pull request merged**
