### PR TITLE
Backport several style changes from Gecko (6)

### PR DESCRIPTION
**Pull request by Loirooriol**
This continues https://github.com/servo/servo/pull/30108.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

The failure in `css/css-fonts/variations/font-style-parsing.html` also happens on Gecko.

### CODE REVIEW

**Comment by Loirooriol** [comment]
These are my changes: 85b04179f da59e09b5 6be56c9b1 e7e754d7a b7c1958f8 2edb04441 caf989b3a 1a810faac 49356a3dc 99546fce5 296fd8be0 00114912e 2a3ea9839 03e851263 fadf6b58a b74b9f77e

The 1st one is especially big, that's because https://phabricator.services.mozilla.com/D148537 moved `servo/components/style/element_state.rs` into `dom/base/rust/lib.rs`, outside of the `servo` directory, but Servo still needs it, so I'm adding it back in `components/dom/`

**Review by mrobinson — CHANGES_REQUESTED** [review]
Great work, @Loirooriol. I just have a few minor suggestions, but otherwise this is just fine.

**Review by mrobinson — APPROVED** [review]
Nice.

**Pull request merged**
