### PR TITLE
Basic Media Session UI for Hololens

### LINKED ISSUE #24807: [HoloLens] Implement Media Session UI
#24499 introduced the Media Session API, targeting Android as the first supported platform. Having the Media Session UI on the HoloLens as an alternative to the regular media controls would significantly improve the media playback experience.

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #24807

This PR implements a extremely basic Media Session UI. The media controls are part of the main window, which is not very nice, but it is what we can do until #24873 is done.

### CODE REVIEW

**Comment by ferjm** [comment]
This is a short video running in the Hololens emulator https://vimeo.com/376384891

**Comment by paulrouget** [comment]
This is great :)

Can you make it so MediaSession.h is not necessary? Maybe look at how CMouseButton work?

**Comment by paulrouget** [comment]
r=me with `mach fmt`.

**Comment by CYBAI** [comment]
```
Build FAILED.
       "c:\users\task_1~4\appdata\local\temp\tmpxxolzj" (default target) (1) ->
       "C:\Users\task_1575353602\repo\support\hololens\ServoApp.sln" (Build target) (2) ->
       "C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj" (default target) (3) ->
       (ClCompile target) -> 
         c:\users\task_1575353602\repo\support\hololens\servoapp\servocontrol\servo.cpp(50): warning C4100: 'content': unreferenced formal parameter [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\servocontrol\servocontrol.cpp(151): warning C4100: 'e': unreferenced formal parameter [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\servocontrol\servocontrol.cpp(184): warning C4244: 'argument': conversion from 'const float' to 'GLsizei', possible loss of data [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\servocontrol\servocontrol.cpp(386): warning C4100: 'aShow': unreferenced formal parameter [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
       "c:\users\task_1~4\appdata\local\temp\tmpxxolzj" (default target) (1) ->
       "C:\Users\task_1575353602\repo\support\hololens\ServoApp.sln" (Build target) (2) ->
       "C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj" (default target) (3) ->
       (ClCompile target) -> 
         c:\users\task_1575353602\repo\support\hololens\servoapp\browserpage.cpp(160): error C2039: 'MediaSessionAction': is not a member of 'winrt::servo' [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\browserpage.cpp(160): error C3083: 'MediaSessionAction': the symbol to the left of a '::' must be a type [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\browserpage.cpp(160): error C2039: 'PLAY': is not a member of 'winrt::servo' [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\browserpage.cpp(160): error C2065: 'PLAY': undeclared identifier [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\browserpage.cpp(166): error C2039: 'MediaSessionAction': is not a member of 'winrt::servo' [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\browserpage.cpp(166): error C3083: 'MediaSessionAction': the symbol to the left of a '::' must be a type [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\browserpage.cpp(166): error C2039: 'PAUSE': is not a member of 'winrt::servo' [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
         c:\users\task_1575353602\repo\support\hololens\servoapp\browserpage.cpp(166): error C2065: 'PAUSE': undeclared identifier [C:\Users\task_1575353602\repo\support\hololens\ServoApp\ServoApp.vcxproj]
    4 Warning(s)
    8 Error(s)
```

**Pull request merged**
