### PR TITLE
Update cargo

### LINKED ISSUE #9794: Spurious script rebuilds with shared target directory with build-cef
As seen in: http://build.servo.org/builders/mac-rel-wpt/builds/1966, despite sharing a target directory, runing `./mach build-cef -r` after a `./mach build -r`, it still takes 14 minutes and 43 seconds. This time is because the script crate believes that it has been changed and needs to re-run the build. Here's a sample fingerprint output:

```
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for script v0.0.1 (file:///Users/larsberg/servo/components/servo): precalculated components have changed: 1456675029.000000000s (/Users/larsberg/servo/components/script/parser.out) != 145644786\
6.000000000s (/Users/larsberg/servo/components/script/dom/element.rs)
```

Does not seem to be the same as #7936.

I'm not really sure what this file is (yet), but am looking into it.

CC: @jdm @ms2ger @alexcrichton @metajack

### PR DESCRIPTION
**Pull request by larsbergstrom**
Confirmed locally that it fixes #9794 (thanks, @alexcrichton!).

r? @nox @metajack

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9880)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo retry

- #9012

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #9012

**Comment by KiChjang** [comment]
@bors-servo retry
* #9278

**Pull request merged**
