### PR TITLE
#17079 : Changed the openssl url and bumped the version.

### LINKED ISSUE #17079: Download OpenSSL from rust-lang mirror
The Rust team has an OpenSSL mirror (https://github.com/rust-lang/rust/pull/42220). We should use that instead of downloading releases directly from the openssl website: https://github.com/servo/servo/blob/45d8b0f0b61b8026a57cf5704de2f9d8b53ace45/support/android/openssl.makefile#L13

### PR DESCRIPTION
**Pull request by o0Ignition0o**
Changed the openssl url and bumped the version.
It's a wip because I haven't figured out a relevant way to write a test about it yet.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17079 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because The mach command will fail if anything goes wrong.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17240)

### CODE REVIEW

**Comment by o0Ignition0o** [comment]
cc @MortimerGoro you might wanna provide me more insights on what I can do to improve this :)

**Comment by jdm** [comment]
There's no meaningful way to test this automatically; our CI already accomplishes this by using this script. I would prefer not to update the version of OpenSSL in use as part of this PR; that's a separate task that likely has further-reaching implications.

**Comment by jdm** [comment]
There's no meaningful way to test this automatically; our CI already accomplishes this by using this script. I would prefer not to update the version of OpenSSL in use as part of this PR; that's a separate task that likely has further-reaching implications.

**Comment by o0Ignition0o** [comment]
hey @jdm I tried to keep the same version but it looks like the link is not available on aws :/ 
https://s3.amazonaws.com/rust-lang-ci/rust-ci-mirror/openssl-1.0.1t.tar.gz => is there anything I'm missing ?

**Comment by jdm** [comment]
Ah, I see. That would definitely impede us using it ;)

**Comment by jdm** [comment]
```
openssl.makefile:15: *** missing separator.  Stop.
```

**Comment by o0Ignition0o** [comment]
oh I'm not allowed to do it ^^'

**Comment by MortimerGoro** [comment]
```
./openssl.sh: line 184: cd: openssl-1.0.2k: No such file or directory
Can't open Makefile.org: No such file or directory.
./openssl.sh: line 189: ./config: No such file or directory
```

**Comment by o0Ignition0o** [comment]
By the way I've seen the version is used in the makefile as well as in the .sh file. 

I was considering calling the script passing it the version as second argument, which would look like this : `
./openssl.sh ${ANDROID_NDK} ${VERSION}
`
It would also require changing a line in the .sh file : 
`cd openssl-$2`
@MortimerGoro I've seen that you call the script in your changes, what do you think of such a modification ?

**Comment by o0Ignition0o** [comment]
@jdm Do you want me to squash my commits ? 

Also should the discussion about: 

> I was considering calling the script passing it the version as second argument, which would look like this : ./openssl.sh ${ANDROID_NDK} ${VERSION}
It would also require changing a line in the .sh file :
cd openssl-$2 

stay here or should it maybe be a followup ?

**Comment by MortimerGoro** [comment]
@o0Ignition0o Yes, it's a good idea to pass the version to the openssl.h to avoid duplication. I'd like $OPENSSL_VERSION better for the name of the var.

**Comment by o0Ignition0o** [comment]
Sounds great ! Should I do it here, or should I better do it in an other PR / in a followup issue ?

**Comment by MortimerGoro** [comment]
@o0Ignition0o it's fine to do in this PR

**Comment by o0Ignition0o** [comment]
Ok I've squashed my commits, and refactored it. I guess there should be a way to also do it in the build_commands.py file, but I'm not really sure about it. Any suggestions ?

**Comment by MortimerGoro** [comment]
> I guess there should be a way to also do it in the build_commands.py file, but I'm not really sure about it

Makefile can read environment variable: e.g.: ${OPENSSL_VERSION}. If you set the env variable in build_commands.py it can be read by the makefile and used to pass the argument to sh script too. That way the version we want to use is defined once

**Comment by o0Ignition0o** [comment]
@MortimerGoro Thanks for your reply, I've done as you told me to, I guess I'm one @bors-servo try away from a merge \o/

**Comment by jdm** [comment]
@bors-servo: r+
Looks good! Thanks for doing this!

**Pull request merged**
