### PR TITLE
rewrite uses of map as if let

### PR DESCRIPTION
**Pull request by jxs**
in the end only found this case as re-writable, am i missing some?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7631)

### CODE REVIEW

**Comment by jdm** [comment]
Yes, the two instances in dispatch_key_event which were the goal of #7580 :)

**Comment by jdm** [comment]
http://mxr.mozilla.org/servo/source/components/script/dom/document.rs#800

**Comment by jdm** [comment]
I don't think the change made in this PR so far is an improvement, since we were using the result of the `map` call in the previous code.

**Comment by jxs** [comment]
ok thanks! updated it

**Comment by jdm** [comment]
@bors-servo: r+
Much better; thanks!

**Pull request merged**
