### PR TITLE
Merge some test crates in their corresponding components

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19819)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Please also add `doctest = false` to crates that happen to contain zero doctest. Going through a large crate to collect zero doctests can still take some time.

---

Reviewed 7 of 7 files at r1, 8 of 8 files at r2, 9 of 9 files at r3, 249 of 250 files at r4, 10 of 10 files at r5, 9 of 9 files at r6, 6 of 6 files at r7.
Review status: 155 of 156 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/net/Cargo.toml, line 48 at r4](https://reviewable.io:443/reviews/servo/servo/19819#-L3Ees-CDLrsRdxq1agx:-L3Ees-CDLrsRdxq1agy:b-aqd0in) ([raw file](https://github.com/servo/servo/blob/fa9484474bfa335b0e53de968cd43284b7cb299d/components/net/Cargo.toml#L48)):*
> ```TOML
> tinyfiledialogs = "2.5.9"
> 
> [[test]]
> ```

IIRC if you specify any `[[test]]` section auto-detection based on `tests/*.rs` is disabled so you need to specify all of them.

---

*[components/net/tests/file_loader.rs, line 5 at r4](https://reviewable.io:443/reviews/servo/servo/19819#-L3EfB6s48mq55KEftFu:-L3EfB6s48mq55KEftFv:bsfm6tg) ([raw file](https://github.com/servo/servo/blob/fa9484474bfa335b0e53de968cd43284b7cb299d/components/net/tests/file_loader.rs#L5)):*
> ```Rust
>  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
> 
> extern crate Url;
> ```

`url` lower case. It looks like this code is not being compiled. (See `Cargo.toml` comment on this commit.)

---

*[components/net/tests/http_loader.rs, line 1 at r4](https://reviewable.io:443/reviews/servo/servo/19819#-L3EgsLHjtZvrKRNohom:-L3EgsLIp9hwmugaaZnS:b1gw10i) ([raw file](https://github.com/servo/servo/blob/fa9484474bfa335b0e53de968cd43284b7cb299d/components/net/tests/http_loader.rs#L1)):*
> ```Rust
> /* This Source Code Form is subject to the terms of the Mozilla Public
> ```

This file appears to be the same as `fetch/http_loader.rs`. Copy/paste error?

---

*[components/net/tests/fetch/main.rs, line 32 at r4](https://reviewable.io:443/reviews/servo/servo/19819#-L3EhuD2fJ2RkSrt08ee:-L3EhuD2fJ2RkSrt08ef:b-ekf6lg) ([raw file](https://github.com/servo/servo/blob/671b69c0b77f9a4bd0c098cb2a2f73c95dacb954/components/net/tests/fetch/main.rs#L32)):*
> ```Rust
> mod filemanager_thread;
> mod hsts;
> mod http_loader;
> ```

Shouldn’t `mod data_loader;` and `mod http_loader;` be removed as well? Since they’re test programs of their own.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19819#-:-L3Ee0nPKIsun5qBS3dc:b-my5132)*

**Comment by nox** [comment]
I wonder if we could make Cargo complain if a crate says `doctest = false` (or even `test = false`) and there are actually doctests (or even tests) in the crate.

---

Review status: 3 of 155 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/net/Cargo.toml, line 48 at r4](https://reviewable.io:443/reviews/servo/servo/19819#-L3Ees-CDLrsRdxq1agx:-L3J-geB_BRXBzh00Z8y:b-wdlo4g) ([raw file](https://github.com/servo/servo/blob/fa9484474bfa335b0e53de968cd43284b7cb299d/components/net/Cargo.toml#L48)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

IIRC if you specify any `[[test]]` section auto-detection based on `tests/*.rs` is disabled so you need to specify all of them.
</blockquote></details>

I removed the `fetch` subdirectory and just moved every file as-is, renaming `lib.rs` to `main.rs`.

---

*[components/net/tests/file_loader.rs, line 5 at r4](https://reviewable.io:443/reviews/servo/servo/19819#-L3EfB6s48mq55KEftFu:-L3J-nvjzqlTXwnpTGrH:b-896fix) ([raw file](https://github.com/servo/servo/blob/fa9484474bfa335b0e53de968cd43284b7cb299d/components/net/tests/file_loader.rs#L5)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

`url` lower case. It looks like this code is not being compiled. (See `Cargo.toml` comment on this commit.)
</blockquote></details>

Done.

---

*[components/net/tests/http_loader.rs, line 1 at r4](https://reviewable.io:443/reviews/servo/servo/19819#-L3EgsLHjtZvrKRNohom:-L3J-pwqqQ_c1e77gg6j:b-896fix) ([raw file](https://github.com/servo/servo/blob/fa9484474bfa335b0e53de968cd43284b7cb299d/components/net/tests/http_loader.rs#L1)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

This file appears to be the same as `fetch/http_loader.rs`. Copy/paste error?
</blockquote></details>

Done.

---

*[components/net/tests/main.rs, line 32 at r4](https://reviewable.io:443/reviews/servo/servo/19819#-L3EhuD2fJ2RkSrt08ee:-L3J-tApz9-JuYD4Pmj_:b-896fix) ([raw file](https://github.com/servo/servo/blob/671b69c0b77f9a4bd0c098cb2a2f73c95dacb954/components/net/tests/main.rs#L32)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

Shouldn’t `mod data_loader;` and `mod http_loader;` be removed as well? Since they’re test programs of their own.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19819#-:-L3J-V5UfZnM7OLKBykw:b-xs2kds)*

**Comment by SimonSapin** [comment]
Reviewed 1 of 8 files at r2, 1 of 9 files at r3, 119 of 253 files at r4, 3 of 10 files at r5, 2 of 9 files at r6, 1 of 6 files at r7, 4 of 286 files at r8, 6 of 8 files at r9, 7 of 9 files at r10, 247 of 249 files at r11, 8 of 10 files at r12, 7 of 9 files at r13, 6 of 6 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19819)*

**Pull request merged**
