### PR TITLE
Add CI script to retry builds

### PR DESCRIPTION
**Pull request by Manishearth**
We can then run test-ref as `retry.sh 2 ./mach test-ref ....`

We could also have this curl to some server with information on the
intermittent; so that we can keep track of these separately. It would also be
nice to have crowbot report them in chat (@jdm, is this possible?) and have
something comment on GH with a cross-reference.

This isn't too different from what we do already, we mostly just file or link to
an intermittent hit retry, and move on.

r? @larsbergstrom

cc @jack @edunham

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9572)

### CODE REVIEW

**Comment by Manishearth** [comment]
(Of course, we should only run this on test-ref. Most PRs don't change things that affect test-ref; and test-ref is where all the intermittents are from)

**Comment by jdm** [comment]
test-ref doesn't exist. test-wpt and test-css are both sources of intermittent failures...

**Comment by Manishearth** [comment]
Ugh, I meant test-css, but yeah, wpt has reftests too. Not sure if we should retry wpt since plenty of legit failures come from it too.

**Comment by larsbergstrom** [comment]
If you're mainly concerned about test-css, I'd almost be more interested in running specific intermittent failures with non-incremental layout instead (assuming that is, indeed, the source of our bugs).

I guess I'm personally just really afraid of auto-retry because it starts with this, then goes to "retry just the failed test," and then shortly people start to forget that it's even there and just have a general sense that tests are flaky and/or "only run on the builders."

I'm mainly citing from past life experiences, and admittedly the Visual Studio tests drove the UI via accessibility automation, which is *significantly* more challenging to get reproducible than our wpt/css tests, so I might be overly worried.

**Comment by larsbergstrom** [comment]
@bors-servo r+

I'll go ahead and land this so that we can test this out and/or bikeshed our opinions on retry over in the saltfs repo where we'd be making the concrete changes :-)

**Pull request merged**
