### PR TITLE
Upgrade webxr

### PR DESCRIPTION
**Pull request by paulrouget**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24134)

### CODE REVIEW

**Comment by CYBAI** [comment]
```
{
    "status": "NOTRUN", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "end event fires when non-immersive session ends", 
    "test": "/webxr/xrSession_end.https.html", 
    "line": 291681, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "ERROR", 
    "group": "default", 
    "message": "Timeout while running cleanup for test named \"end event fires when immersive session ends\".", 
    "stack": null, 
    "subtest": null, 
    "test": "/webxr/xrSession_end.https.html", 
    "line": 291682, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "ERROR", 
    "group": "default", 
    "message": "Timeout while running cleanup for test named \"Calling end during an input callback stops processing at the right time\".", 
    "stack": null, 
    "subtest": null, 
    "test": "/webxr/xrSession_input_events_end.https.html", 
    "line": 327809, 
    "action": "test_result", 
    "expected": "OK"
}
```

**Comment by paulrouget** [comment]
https://github.com/servo/webxr/pull/53 will solve these tests issues.

**Comment by CYBAI** [comment]
```rust
error[E0063]: missing field `is_running` in initializer of `magicleap::MagicLeapDevice`
   --> /Users/worker/.cargo/git/checkouts/webxr-702fa5244eec1e69/614c1b7/webxr/magicleap/mod.rs:158:26
    |
158 |         let mut device = MagicLeapDevice {
    |                          ^^^^^^^^^^^^^^^ missing `is_running`

error: aborting due to previous error
```

**Comment by CYBAI** [comment]
@bors-servo retry

- cygwin oom

**Pull request merged**
