### PR TITLE
Remove fnv & smallvec crate reexports from util

### PR DESCRIPTION
**Pull request by frewsxcv**
The util component specified fnv and smallvec as dependencies and publicly
reexported both of them. Several other components utilized these reexports,
presumably because fnv and smallvec used to live in the tree so reexporting
made the transition easier.

These indirect dependencies through the util component are unnecessary.

This commit removes the fnv & smallvec crate reexports in the util component.
It exchange, it adds fnv & smallvec as dependencies to non-util components
wherever needed. Finally, it removes the fnv dependency from util as it is not
utilized anywhere in the util component.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6317)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

Please update the other Cargo.locks as well; should be as easy as starting a build until the actual compilation starts.

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/gfx/Cargo.toml @ r1
- components/gfx/display_list/mod.rs @ r1
- components/gfx/font.rs @ r1
- components/gfx/font_context.rs @ r1
- components/gfx/lib.rs @ r1
- components/layout/Cargo.toml @ r1
- components/layout/context.rs @ r1
- components/layout/css/matching.rs @ r1
- components/layout/generated_content.rs @ r1
- components/layout/layout_task.rs @ r1
- components/layout/lib.rs @ r1
- components/layout/wrapper.rs @ r1
- components/script/Cargo.toml @ r1
- components/script/dom/bindings/trace.rs @ r1
- components/script/dom/element.rs @ r1
- components/script/dom/eventtarget.rs @ r1
- components/script/lib.rs @ r1
- components/servo/Cargo.lock @ r1
- components/style/Cargo.toml @ r1
- components/style/legacy.rs @ r1
- components/style/lib.rs @ r1
- components/style/node.rs @ r1
- components/style/properties.mako.rs @ r1
- components/style/selector_matching.rs @ r1
- components/style/stylesheets.rs @ r1
- components/util/Cargo.toml @ r1
- components/util/lib.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6317)

**Comment by frewsxcv** [comment]
Which Cargo.locks are missing? I just successfully built and none of them updated any further

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6317)

**Comment by Ms2ger** [comment]
cef and gonk

**Comment by frewsxcv** [comment]
I just force pushed with that change using `cargo update -p fnv` and `cargo update -p smallvec`

---

Review status: 27 of 29 files reviewed, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6317)

**Comment by Ms2ger** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- ports/cef/Cargo.lock @ r2
- ports/gonk/Cargo.lock @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6317)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 
@bors-servo: r+

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6317)

**Pull request merged**
