### PR TITLE
add basic |mach rr-{record,replay}| commands

### LINKED ISSUE #4177: Create a mach command to run Servo under rr
Assuming that rr is installed in your PATH, it would be super useful for reproducing problems.

### PR DESCRIPTION
**Pull request by froydnj**
These are very basic commands for invoking Servo underneath rr.  rr
currently doesn't support all the syscalls that Servo requires, but
that's easy to fix on the rr side.

Fixes #4177.

### CODE REVIEW

**Comment by Manishearth** [comment]
Any updates? :)

**Comment by froydnj** [comment]
All right, so assuming I didn't botch something, 1cf8aa9 should address the review comments.

**Comment by jdm** [comment]
Critic says there's a merge commit with -10,000, +17,000 changes, which is unfortunate.

**Comment by froydnj** [comment]
Well, boo, apparently I botched something.  Maybe my rebasing of my local branch wasn't a fast-forward merge or something?  I:

1. Pulled servo HEAD
2. Rebased local branch
3. Force-pushed to my github branch
4. Told critic to rebase the review

...and thought I was in the clear.  What can I do to help fix this?

**Comment by jdm** [comment]
Luckily the fixup was separate from the rebase/merge, so we can just ignore the weirdness and squash this.

**Comment by jdm** [comment]
Rebased in #5047.

**Pull request closed without merging**
