### PR TITLE
Update rust-mozjs.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6440)

### CODE REVIEW

**Comment by Ms2ger** [comment]
https://github.com/servo/rust-mozjs/pull/159

**Comment by metajack** [comment]
@bors-servo r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6440)

**Pull request merged**
