### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by sinkuu**
Removes unused crates from `Cargo.toml` to (possibly) shorten build time.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because no semantic changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24335)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Nice! Did you manually look at each `Cargo.toml` file and corresponding code, or was there a way to semi-automate this?

Either way:

@bors-servo r+

**Comment by sinkuu** [comment]
@SimonSapin A script that runs `rg -qw $dependency` for each dependency. https://gist.github.com/sinkuu/8083240257c485c9f928744b41bbac98

**Comment by nox** [comment]
Would #24334 break your script?

**Comment by jdm** [comment]
@bors-servo retry
* #21696

**Comment by sinkuu** [comment]
@nox No, the script uses `cargo_metadata`, which is independent from actual file formats.

**Pull request merged**
