### PR TITLE
Bug 1364850: Move PseudoElement to be just another combinator in selectors. r=bholley

### PR DESCRIPTION
**Pull request by emilio**
On top of https://github.com/servo/servo/pull/16890.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16900)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0412]: cannot find type `PseudoElementSelector` in module `dummies`
  --> /home/servo/buildbot/slave/linux-dev/build/tests/unit/stylo/size_of.rs:15:26
   |
15 |     assert_eq!(size_of::<dummies::PseudoElementSelector>(), size_of::<real::PseudoElementSelector>());
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `dummies`

error[E0412]: cannot find type `PseudoElementSelector` in module `real`
  --> /home/servo/buildbot/slave/linux-dev/build/tests/unit/stylo/size_of.rs:15:71
   |
15 |     assert_eq!(size_of::<dummies::PseudoElementSelector>(), size_of::<real::PseudoElementSelector>());
   |                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `real`

error[E0412]: cannot find type `PseudoElementSelector` in module `dummies`
  --> /home/servo/buildbot/slave/linux-dev/build/tests/unit/stylo/size_of.rs:16:27
   |
16 |     assert_eq!(align_of::<dummies::PseudoElementSelector>(), align_of::<real::PseudoElementSelector>());
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `dummies`

error[E0412]: cannot find type `PseudoElementSelector` in module `real`
  --> /home/servo/buildbot/slave/linux-dev/build/tests/unit/stylo/size_of.rs:16:73
   |
16 |     assert_eq!(align_of::<dummies::PseudoElementSelector>(), align_of::<real::PseudoElementSelector>());
   |                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `real`

error: aborting due to 4 previous errors

error: Could not compile `stylo_tests`.
```

**Comment by emilio** [comment]
Gah, rebase fail, I messed up the precomputed pseudo-element stuff.

@bors-servo r=bholley

**Comment by emilio** [comment]
> Gah, rebase fail, I messed up the precomputed pseudo-element stuff.

I meant the `is_universal` stuff.

**Pull request merged**
