### PR TITLE
Cache XHR JSON responses

### LINKED ISSUE #3919: Cache response types in XHR
See https://xhr.spec.whatwg.org/#response-json-object -- the parsed responses should be cached once calculated.

Should make `/XMLHttpRequest/response-json.htm` pass.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #3919.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9621)

### CODE REVIEW

**Comment by jdm** [comment]
This isn't a through review, just a couple things that jumped out at me:
* I'm not convinced that having the MutJSHeapValue size be reported as 0 is better than selectively ignoring the field with a useful explanation
* I'm pretty sure we want is_null() instead of comparing the JS value against a null handle value

**Comment by KiChjang** [comment]
Not sure what the explanation should be though, "managed through JS GC"?

**Comment by KiChjang** [comment]
@bors-servo retry
* #8191

**Comment by KiChjang** [comment]
@bors-servo retry
* #9205

**Comment by jdm** [comment]
@bors-servo: retry
* #9120

**Comment by jdm** [comment]
@bors-servo: retry
* #8191

**Comment by KiChjang** [comment]
@bors-servo retry
* #9488

**Pull request merged**
