### PR TITLE
relocation from src to app units #8012

### PR DESCRIPTION
**Pull request by creativcoder**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8013)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Why did `components/app_units/Cargo.toml` get deleted?

**Comment by creativcoder** [comment]
Hi, added back Cargo.toml. Please review PR.

**Comment by frewsxcv** [comment]
You probably need to add something like [this](https://github.com/servo/servo/blob/dd2f8b6891f963a6c0cf42be9212e85a86a77df7/components/gfx/Cargo.toml#L7-L9) to the `Cargo.toml` file in the component since it no longer lives in `src/lib.rs`. You can verify if it works by doing:

```
cd components/app_units/
cargo build
```

More info about the `[lib]` section [here](http://doc.crates.io/manifest.html#configuring-a-target)

**Comment by creativcoder** [comment]
I assume that Under [lib] section, the name atttribute should be "app_units". Correct me if am wrong.

**Comment by frewsxcv** [comment]
That sounds right

**Comment by creativcoder** [comment]
Updated Cargo.toml. Please Review PR.

**Comment by frewsxcv** [comment]
@bors-servo r+

Thanks!

**Comment by Ms2ger** [comment]
@bors-servo r-

Sorry @creativcoder, this is my mistake. We'll move this code into a separate repository, where the existing directory structure makes more sense, so I'm dropping this PR.

Again, apologies for wasting your time.

**Pull request closed without merging**
