### PR TITLE
Revert "Replace use of callbacks in webxr by channels"

### PR DESCRIPTION
**Pull request by SimonSapin**
This backs out commit 133a17e15c4110fe7a5f0933bb50842bb3eeeccb / PR #23848 because it relies on a git branch that was apparently removed:

```
$ cargo fetch
    Updating git repository `https://github.com/asajeffrey/webxr`
error: failed to resolve patches for `https://github.com/servo/webxr`

Caused by:
  failed to load source for a dependency on `webxr`

Caused by:
  Unable to update https://github.com/asajeffrey/webxr?branch=optional-glsync#da820a3a

Caused by:
  revspec 'da820a3ab266fce07c9a8abee3e6e9231cb93ec5' not found; class=Reference (4); code=NotFound (-3)
```

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23874)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo r+

CC @asajeffrey, @Manishearth

**Comment by jdm** [comment]
This will be fixed by #23857.

**Pull request closed without merging**
