### PR TITLE
Various cleanup

### PR DESCRIPTION
**Pull request by UK992**
Reduces msi file size from 102 MB to 94 MB and installation size from 394 MB to 334 MB.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14193)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Great work!

r? @larsbergstrom or @vvuk

**Comment by vvuk** [comment]
r=me

Great! I notice that we still install freetype.. we should be able to remove that, as long as we've killed all downstream uses.  (Now that I think of it, it may still be hanging on via skia maybe..)

**Comment by leeoniya** [comment]
related quasi-meta for this: https://github.com/servo/servo/issues/14176

**Pull request merged**
