### PR TITLE
Implement Navigator.languages

### LINKED ISSUE #27210: Implement navigator.languages
This is used by hubs in places like https://github.com/mozilla/hubs/blob/2c60de07a1cf7ed070f04f440637aa0e3b592e8f/src/utils/i18n.js#L4 and https://github.com/mozilla/hubs/blob/6defae0ef0163a835c551650acdc614bb86e5559/src/storage/media-search-store.js#L81, and breaks the avatar selection panel.

### PR DESCRIPTION
**Pull request by jdm**
Fixes #27210.

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo retry
* #26895

**Comment by Manishearth** [comment]
```
   6: std::sys_common::backtrace::_print
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\/src\libstd\sys_common\backtrace.rs:62
   7: std::sys_common::backtrace::print
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\/src\libstd\sys_common\backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\/src\libstd\panicking.rs:198
   9: std::panicking::default_hook
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\/src\libstd\panicking.rs:214
  10: std::panicking::rust_panic_with_hook
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\/src\libstd\panicking.rs:526
  11: std::panicking::begin_panic_handler
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\/src\libstd\panicking.rs:437
  12: std::panicking::begin_panic_fmt
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\/src\libstd\panicking.rs:391
  13: main::http_loader::test_origin_set
             at .\tests\http_loader.rs:1443
  14: main::http_loader::test_origin_set::{{closure}}
             at .\tests\http_loader.rs:1376
  15: core::ops::function::FnOnce::call_once<closure-0,()>
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\src\libcore\ops\function.rs:233
  16: alloc::boxed::{{impl}}::call_once
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\src\liballoc\boxed.rs:1081
  17: std::panic::{{impl}}::call_once
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\src\libstd\panic.rs:318
  18: std::panicking::try::do_call
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\src\libstd\panicking.rs:348
  19: std::panicking::try
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\src\libstd\panicking.rs:325
  20: std::panic::catch_unwind
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\src\libstd\panic.rs:394
  21: test::run_test_in_process
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\/src\libtest\lib.rs:541
  22: test::run_test::run_test_inner::{{closure}}
             at /rustc/2753fab7ce3647033146b07c8b6c9f4856a910b0\/src\libtest\lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failures:
    http_loader::test_origin_set

```

@bors-servo retry

**Comment by jdm** [comment]
That's #26895.

**Pull request merged**
