### PR TITLE
Added support for mouseover and mouseout events

### PR DESCRIPTION
**Pull request by yoava333**
fixes issue https://github.com/servo/servo/issues/6404

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6434)

### CODE REVIEW

**Comment by glennw** [comment]
@Ms2ger Is this something you could look at?

**Comment by Ms2ger** [comment]
@yoava333: could you point at the spec you're implementing here? In any case, this PR needs a rebase over the SpiderMonkey upgrade.

**Comment by yoava333** [comment]
@Ms2ger I'm implementing this spec https://w3c.github.io/uievents/#event-type-mouseover
which branch is the spider monkey upgrade?

**Comment by yoava333** [comment]
I've rebased over the spider monkey, and fixed type errors

**Comment by nox** [comment]
The two changes are quite similar, could you make a fire_mouse_event method or something?

**Comment by yoava333** [comment]
@nox you're right, I've moved the logic to a new function and pushed again.

**Comment by nox** [comment]
@bors-servo r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6434)

**Pull request merged**
