### PR TITLE
style: Remove pretty useless layer of abstraction.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19452)

### CODE REVIEW

**Comment by emilio** [comment]
r? anyone

**Comment by jdm** [comment]
r=me. Weird piece of code :)

However:
```
./ports/geckolib/glue.rs:126: use statement is not in alphabetical order

	expected: style::properties::animated_properties::compare_property_priority

	found: style::properties::{parse_one_declaration_into, parse_style_attribute}
```

**Comment by emilio** [comment]
Thanks for the review Josh :)

**Pull request merged**
