### PR TITLE
Add build option to ignore packaging errors.

### PR DESCRIPTION
**Pull request by jdm**
Works around #23749.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23752)

### CODE REVIEW

**Comment by saschanaz** [comment]
Does this assume that the new dll requirement in #23749 is actually not needed?

**Comment by jdm** [comment]
It is only a workaround for appveyor in particular.

**Comment by jdm** [comment]
@bors-servo r-
#23765 is a better solution.

**Pull request closed without merging**
