### PR TITLE
Support preserveDrawingBuffer

### LINKED ISSUE #24604: Implement preserveDrawingBuffe=true support for webgl
#24482 adds multiple frame buffers so we don't get preserveDrawingBuffer=true support for free any more by choosing not to clear them. We need to add some code in handle_swap_buffers to copy the previous framebuffer's contents to the new framebuffer.

### PR DESCRIPTION
**Pull request by jdm**
Depends on https://github.com/asajeffrey/surfman-chains/pull/9 and https://github.com/servo/webxr/pull/190.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24604
- [x] There are tests for these changes

### CODE REVIEW

**Review by asajeffrey — APPROVED** [review]
LGTM with the patch sections in Cargo.toml removed, and version bumps of `surfman-chains` added.

**Comment by jdm** [comment]
@bors-servo retry
* #27535

**Pull request merged**
