### PR TITLE
Add DOMLoad message to constellation that is sent after the DOM Load event is dispatched.

### PR DESCRIPTION
**Pull request by jgraham**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6415)

### CODE REVIEW

**Comment by metajack** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 716 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6415#-Js7ZcG1XTJW5-6_Mw1H)** ([raw file](https://github.com/servo/servo/blob/e6bbaec1821a10e24050d438069303770c97d8d5/components/compositing/constellation.rs#L716)):</sup>
Why are these split now? Some explanation would be useful as it's not obvious just from reading through the code here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6415)

**Comment by jgraham** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 716 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6415#-Js7ZcG1XTJW5-6_Mw1H)** ([raw file](https://github.com/servo/servo/blob/e6bbaec1821a10e24050d438069303770c97d8d5/components/compositing/constellation.rs#L716)):</sup>
If the question is essentially "why do we have LoadComplete and "DOMLoad", the answer is "I'm not sure". I suspect that LodComplete should never be used because it's racy, but I just made the minimal change. @glennw might know more.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6415)

**Comment by glennw** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 716 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6415#-Js7ZcG1XTJW5-6_Mw1H)** ([raw file](https://github.com/servo/servo/blob/e6bbaec1821a10e24050d438069303770c97d8d5/components/compositing/constellation.rs#L716)):</sup>
I'm also not sure why they both exist. When I made the changes to fix the reftest race conditions, I considered removing LoadComplete because it seemed like it wasn't particularly useful due to what jgraham mentioned above. I left it at the time because the patch was already large and some parts of the mac miniservo build were using the LoadComplete callback (I don't think anything else does). Perhaps add a TODO / GH issue to investigate whether it can be removed?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6415)

**Comment by jgraham** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 716 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6415#-Js7ZcG1XTJW5-6_Mw1H)** ([raw file](https://github.com/servo/servo/blob/e6bbaec1821a10e24050d438069303770c97d8d5/components/compositing/constellation.rs#L716)):</sup>
Issue #6455 filed on this. Does it also need another comment in the code (the match statement that dispatches here already has a comment that describes when each message is produced)?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6415)

**Comment by jdm** [comment]
-S-awaiting-review -S-awaiting-answer +S-needs-code-changes 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 716 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6415#-Js7ZcG1XTJW5-6_Mw1H)** ([raw file](https://github.com/servo/servo/blob/e6bbaec1821a10e24050d438069303770c97d8d5/components/compositing/constellation.rs#L716)):</sup>
Yes, LoadComplete should go away, but it will be easier for someone to do once this split it accomplished.

---

<sup>**[components/compositing/constellation.rs, line 720 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6415#-JuRPGqegIpA0blpss2x)** ([raw file](https://github.com/servo/servo/blob/666c46262f823f36c61e2bf93dbd5ed990fdd38d/components/compositing/constellation.rs#L720)):</sup>
Nix the unused argument.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6415)

**Comment by metajack** [comment]
@jgraham ping

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/constellation.rs, line 716 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6415#-Js7ZcG1XTJW5-6_Mw1H)** ([raw file](https://github.com/servo/servo/blob/e6bbaec1821a10e24050d438069303770c97d8d5/components/compositing/constellation.rs#L716)):</sup>
OK, I'm assuming no further action is required for now.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6415)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6415)

**Pull request merged**
