### PR TITLE
Upgrade to rustc 1.3.0-dev (87055a68c 2015-07-30)

### PR DESCRIPTION
**Pull request by SimonSapin**
This builds and passes unit tests.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6850)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed 4 of 4 files at r1, 7 of 7 files at r2, 7 of 7 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6850)

**Comment by larsbergstrom** [comment]
```
/home/servo/.cargo/registry/src/github.com-0a35038f75765ae4/string_cache_shared-0.1.4/lib.rs:24:1: 24:59 error: couldn't read "/home/servo/buildbot/slave/android/build/target/arm-linux-androideabi/debug/build/string_cache_shared-958073fd46aee134/out/static_atom_set.rs": No such file or directory (os error 2)
/home/servo/.cargo/registry/src/github.com-0a35038f75765ae4/string_cache_shared-0.1.4/lib.rs:24 include!(concat!(env!("OUT_DIR"), "/static_atom_set.rs"));
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Compiling serde_macros v0.4.1
```

**Comment by SimonSapin** [comment]
```
Downloading debug_unreachable v0.0.6
Unable to get packages from source
```

Looks like network or crates.io reliability issues.

**Pull request merged**
