### PR TITLE
Use cleaner StrokeOptions interface

### PR DESCRIPTION
**Pull request by andreasgal**
The new interface will be added by https://github.com/ser...vo/rust-azure/pull/145 (has to be merged first).

### CODE REVIEW

**Comment by jdm** [comment]
This will require committing the result of `./mach update-cargo -p azure --precise [rev]` where rev is the commit in rust-azure to use.

**Comment by andreasgal** [comment]
furball:servo gal$ ./mach update-cargo -p azure --precise 16cca6bebbadf194d6403748c32f91f679a57571
components/servo
    Updating git repository `https://github.com/servo/rust-azure`
Unable to update https://github.com/servo/rust-azure#16cca6be

To learn more, run the command again with --verbose.
ports/cef
    Updating git repository `https://github.com/servo/rust-azure`
Unable to update https://github.com/servo/rust-azure#16cca6be

To learn more, run the command again with --verbose.
ports/gonk
    Updating git repository `https://github.com/servo/rust-azure`
Unable to update https://github.com/servo/rust-azure#16cca6be

To learn more, run the command again with --verbose.

Mhm ... help!

**Comment by jdm** [comment]
Oh right, that will need to wait until the PR in rust-azure is merged.

**Comment by andreasgal** [comment]
Right I was thinking so.

**Pull request closed without merging**
