### PR TITLE
Run all unit tests with just one Cargo command.

### PR DESCRIPTION
**Pull request by SimonSapin**
Upgrade Cargo to get https://github.com/rust-lang/cargo/pull/1828, and use it for unit tests. This allows Cargo to get some more parallelism when compiling the test crates’ dependencies.

`touch components/util/lib.rs && mach test-unit` on my machine goes from 149 seconds to 124.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7813)

### CODE REVIEW

**Comment by metajack** [comment]
```
./mach test-unit
 in dir /Users/servo/buildbot/slave/mac-dev-ref-unit/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['./mach', 'test-unit']
 environment:
  CARGO_HOME=/Users/servo/.cargo
  HOME=/Users/servo
  LOGNAME=servo
  PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  PWD=/Users/servo/buildbot/slave/mac-dev-ref-unit/build
  RUST_BACKTRACE=1
  SERVO_CACHE_DIR=/Users/servo/.servo
  SHELL=/bin/bash
  TMPDIR=/var/folders/sd/sks3rs2s3pb9bdrg9ldf9d5w0000gp/T/
  USER=servo
  VERSIONER_PYTHON_PREFER_32_BIT=no
  VERSIONER_PYTHON_VERSION=2.7
  XPC_FLAGS=0x0
  XPC_SERVICE_NAME=buildslave
  __CF_USER_TEXT_ENCODING=0x1F6:0:0
 using PTY: False
Invalid arguments.

Usage:
    cargo test [options] [--] [<args>...]
```

**Comment by SimonSapin** [comment]
Looks like the `cargo-nightly-build` change did not take effect. Can we check what Cargo version the builder is using? Does it have a `.servobuild` file?

**Comment by SimonSapin** [comment]
Never mind, it’s me who’s using `system-cargo = true` in my local `.servobuild` file. It turns out that having `2015-09-30` in `cargo-nightly-build` gets us `cargo 0.6.0-nightly (ec9398e 2015-09-29)`, not `cargo 0.6.0-nightly (7931e58 2015-09-30)` as I expected. Having `2015-10-01` in the file does that.

**Comment by SimonSapin** [comment]
```
Unexpected Results
==================

/css21_dev/html4/font-family-013.htm
------------------------------------
FAIL [Parent]
/css21_dev/html4/fonts-013.htm
------------------------------
FAIL [Parent]
```

Could the builders have lost Microsoft fonts again?

**Comment by jdm** [comment]
cc @metajack

**Comment by SimonSapin** [comment]
@bors-servo retry

(Other PRs seem to be landing.)

**Comment by metajack** [comment]
The fonts are indeed missing. I'm not sure why their installation is unreliable. I have manually added them on servo-linux2, but servo-linux1 refuses to install them still.

**Pull request merged**
