### PR TITLE
Compile raw inline event handlers lazily. Resolves #8489.

### LINKED ISSUE #8489: Stop eagerly compiling raw uncompiled event handlers
Stuff like `<body onload="foo()">` is eagerly compiled right now, and the spec says it should not be until we get the value of the event handler (either through `body.onload` or using it for an event target chain).

I have patches that correct this.

### PR DESCRIPTION
**Pull request by jdm**
Per https://html.spec.whatwg.org/multipage/webappapis.html#getting-the-current-value-of-the-event-handler and https://html.spec.whatwg.org/multipage/webappapis.html#event-handler-attributes:event-handlers-2 .

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8491)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I started to review this, but it doesn't have the changes from #8430?

**Comment by Ms2ger** [comment]
Reviewed 2 of 5 files at r1, 1 of 4 files at r2.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8491)

**Comment by Ms2ger** [comment]
Sorry, finding it hard to review this, since the code here as well as the spec are twisty mazes, not quite alike.

-S-needs-rebase +S-needs-code-changes 

---

Reviewed 1 of 4 files at r3.
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/eventtarget.rs, line 328 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8491#-K4NpsaYUL8O1eLdvR9C:-K4NpsaYUL8O1eLdvR9D:-1809310572) ([raw file](https://github.com/servo/servo/blob/18d10e7150bc88fc8c464da465cb71f02886c757/components/script/dom/eventtarget.rs#L328)):*
Note in the comment that this only handles the substeps of step 1.

---

*[components/script/dom/eventtarget.rs, line 334 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8491#-K4NosbcfTpfhcBaksdY:-K4NosbcfTpfhcBaksdZ:-324538615) ([raw file](https://github.com/servo/servo/blob/18d10e7150bc88fc8c464da465cb71f02886c757/components/script/dom/eventtarget.rs#L334)):*
Consider creating a struct for what the spec calls an "internal raw uncompiled handler".

---

*[components/script/dom/eventtarget.rs, line 335 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8491#-K4NoQ--XJf3bV7qDZMb:-K4NoQ-0LDO6qGifgk-c:-1917085626) ([raw file](https://github.com/servo/servo/blob/18d10e7150bc88fc8c464da465cb71f02886c757/components/script/dom/eventtarget.rs#L335)):*
Spurious parens

---

*[components/script/dom/eventtarget.rs, line 101 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8491#-K4O3_2Kgki1H_2U3T0t:-K4O3_2LG61Ja_lIg8eM:-384306504) ([raw file](https://github.com/servo/servo/blob/12c43c0f8bd18469be28a3a80f6c509f42332161/components/script/dom/eventtarget.rs#L101)):*
An "event handler" in the spec can also be null. Explain why this can't be?

Possibly because you remove the null ones from the list, but that seems  to be wrong. See below.

---

*[components/script/dom/eventtarget.rs, line 115 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8491#-K4O1t2tUIu8hdjIbaGq:-K4O1t2tUIu8hdjIbaGr:550029288) ([raw file](https://github.com/servo/servo/blob/12c43c0f8bd18469be28a3a80f6c509f42332161/components/script/dom/eventtarget.rs#L115)):*
This `unwrap()` panics in
```html
<!DOCTYPE html>
<div>...</div>
<script>
var e = document.body;
e.setAttribute("onclick", "console.log('x')");
e.onclick;
e.onclick;
</script>
```

---

*[components/script/dom/eventtarget.rs, line 245 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8491#-K4O5mLaZFN5ElVQ7mvB:-K4O5mLaZFN5ElVQ7mvC:2080845978) ([raw file](https://github.com/servo/servo/blob/12c43c0f8bd18469be28a3a80f6c509f42332161/components/script/dom/eventtarget.rs#L245)):*
This entire removing business seems broken. Consider:
```html
<!DOCTYPE html>
<div>...</div>
<script>
var e = document.body;
e.addEventListener("click", function() { console.log("ONE") });
e.setAttribute("onclick", "console.log(");
e.addEventListener("click", function() { console.log("THREE") });
e.onclick;
e.setAttribute("onclick", "console.log('TWO')");
e.dispatchEvent(new Event("click"))
</script>
```

I believe Gecko's one/two/three output is correct.

---

*[components/script/dom/eventtarget.rs, line 275 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8491#-K4O2R89DsHgB_b6oYyv:-K4O2R89DsHgB_b6oYyw:640759796) ([raw file](https://github.com/servo/servo/blob/12c43c0f8bd18469be28a3a80f6c509f42332161/components/script/dom/eventtarget.rs#L275)):*
Perhaps this would be simpler iterating backwards?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8491#-:-K4O6BLE0-Ap5HpG6vY7:-478016170)*

**Comment by Ms2ger** [comment]
bz also had some variants: http://logs.glob.uno/?c=mozilla%23content#c344801

**Comment by Ms2ger** [comment]
A test that
```js
var e = document.body;
e.setAttribute("onclick", "console.log(");
e.onclick;
e.onclick;
```
only calls `onerror` once would be good too, if that isn't covered yet.

**Comment by jdm** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/eventtarget.rs, line 328 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8491#-K4NpsaYUL8O1eLdvR9C:-K6syDeZ1OMTPogyBKUi:-212606924) ([raw file](https://github.com/servo/servo/blob/18d10e7150bc88fc8c464da465cb71f02886c757/components/script/dom/eventtarget.rs#L328)):*
Not relevant in later revisions.

---

*[components/script/dom/eventtarget.rs, line 335 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8491#-K4NoQ--XJf3bV7qDZMb:-K6szbWo00rZYcCza7Mb:1143802449) ([raw file](https://github.com/servo/servo/blob/18d10e7150bc88fc8c464da465cb71f02886c757/components/script/dom/eventtarget.rs#L335)):*
Addressed in subsequent revision.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8491)*

**Comment by jdm** [comment]
The code is a bit less complicated now that all traces of removing inline event handlers has been excised. The requested tests have been added, and we pass the ones that don't rely on `onerror` support.

**Comment by Ms2ger** [comment]
Reviewed 2 of 5 files at r4, 1 of 7 files at r5.
Review status: 3 of 11 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/script/dom/eventtarget.rs, line 119 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8491#-K9lyVReTlr644gC0kgU:-K9lyVRfE9ZlIBQtvlEf:1923206060) ([raw file](https://github.com/servo/servo/blob/a4686722c490110d2e7b7125e873bb14836763ce/components/script/dom/eventtarget.rs#L119)):*
Point to <https://html.spec.whatwg.org/multipage/#getting-the-current-value-of-the-event-handler>.

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/invalid-uncompiled-raw-handler-compiled-once.html, line 7 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8491#-K9lwXVlpBqPzimJMtQB:-K9lwXVnhXUyuq2fy2eA:-1555695089) ([raw file](https://github.com/servo/servo/blob/a4686722c490110d2e7b7125e873bb14836763ce/tests/wpt/web-platform-tests/html/webappapis/scripting/events/invalid-uncompiled-raw-handler-compiled-once.html#L7)):*
This would be `iframe` if it was used at all.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8491)*

**Comment by Ms2ger** [comment]
Reviewed 3 of 7 files at r5.
Review status: 6 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/script/dom/eventtarget.rs, line 127 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8491#-K9mI3e444sQ3ZQv0NWM:-K9mI3e6crunb4s4rIs8:515739438) ([raw file](https://github.com/servo/servo/blob/a4686722c490110d2e7b7125e873bb14836763ce/components/script/dom/eventtarget.rs#L127)):*
I think there's now an easier way to do this: if you match on `mem::replace(self, InlineEventListener::Null)`, you can move out of the result and should no longer need the `Option` around the `InternalRawUncompiledHandler` or the `Action` enum.

---

*[components/script/dom/eventtarget.rs, line 238 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8491#-K9mNEYymiP6dRo39AtS:-K9mNEYz-WwAkIXxvyXP:-1058079570) ([raw file](https://github.com/servo/servo/blob/a4686722c490110d2e7b7125e873bb14836763ce/components/script/dom/eventtarget.rs#L238)):*
"... of the same type", right?

---

*[tests/wpt/mozilla/tests/mozilla/inline-event-listener-panic.html, line 3 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8491#-K9mO0p0NViPbuA0hD93:-K9mO0p15LdI9lEPrgTq:-1510636941) ([raw file](https://github.com/servo/servo/blob/a4686722c490110d2e7b7125e873bb14836763ce/tests/wpt/mozilla/tests/mozilla/inline-event-listener-panic.html#L3)):*
Consider adding a note in the `.ini` file to remove this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8491)*

**Comment by jdm** [comment]
Review status: 6 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/wpt/mozilla/tests/mozilla/inline-event-listener-panic.html, line 3 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8491#-K9mO0p0NViPbuA0hD93:-K9n8Q5WYggsJUEtO__b:285810983) ([raw file](https://github.com/servo/servo/blob/a4686722c490110d2e7b7125e873bb14836763ce/tests/wpt/mozilla/tests/mozilla/inline-event-listener-panic.html#L3)):*
I don't understand what you're asking for/referring to here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8491)*

**Comment by Ms2ger** [comment]
Reviewed 2 of 5 files at r4, 1 of 7 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/eventtarget.rs, line 123 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8491#-KAFZreQiFVK4OH38s6R:-KAFZreSu1WS6jAm3y4m:795372746) ([raw file](https://github.com/servo/servo/blob/18d10e7150bc88fc8c464da465cb71f02886c757/components/script/dom/eventtarget.rs#L123)):*
η-convert this, please.

---

*[components/script/dom/eventtarget.rs, line 128 \[r8\]](https://reviewable.io:443/reviews/servo/servo/8491#-KAFbRjXJ4k1fr2w6YYU:-KAFbRjXJ4k1fr2w6YYV:-920245542) ([raw file](https://github.com/servo/servo/blob/b4e69f4a2466f4b56f30441787ab189809a3e66c/components/script/dom/eventtarget.rs#L128)):*
`if let Some(ref compiled) = result {}`

---

*[components/script/dom/eventtarget.rs, line 330 \[r8\]](https://reviewable.io:443/reviews/servo/servo/8491#-KAFcILMWGkuyslD4JSn:-KAFcILO1bPgeNm7Ypbi:-423730659) ([raw file](https://github.com/servo/servo/blob/b4e69f4a2466f4b56f30441787ab189809a3e66c/components/script/dom/eventtarget.rs#L330)):*
I think `unwrap_or` would get rid of this `match`.

---

*[components/script/dom/htmlbodyelement.rs, line 175 \[r8\]](https://reviewable.io:443/reviews/servo/servo/8491#-KAFds3gflv98Ub3TxPR:-KAFds3uI-HnaMWxcLTp:1134954050) ([raw file](https://github.com/servo/servo/blob/b4e69f4a2466f4b56f30441787ab189809a3e66c/components/script/dom/htmlbodyelement.rs#L175)):*
File an issue for that, and link it here and in the other TODO.

---

*[tests/wpt/mozilla/tests/mozilla/inline-event-listener-panic.html, line 3 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8491#-K9mO0p0NViPbuA0hD93:-KAFe3BK0lqzBQRP817A:-93305320) ([raw file](https://github.com/servo/servo/blob/a4686722c490110d2e7b7125e873bb14836763ce/tests/wpt/mozilla/tests/mozilla/inline-event-listener-panic.html#L3)):*
Once we support onerror, there's no real need to keep this test around, so it'd be nice to put a note in the `.ini` file for the test you submitted upstream, so we remember to remove this test.

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/inline-event-handler-ordering.html, line 17 \[r8\]](https://reviewable.io:443/reviews/servo/servo/8491#-KAFeUVD6YyQNbNe1Kni:-KAFeUVD6YyQNbNe1Knj:1409796838) ([raw file](https://github.com/servo/servo/blob/b4e69f4a2466f4b56f30441787ab189809a3e66c/tests/wpt/web-platform-tests/html/webappapis/scripting/events/inline-event-handler-ordering.html#L17)):*
Maybe add a note above this line that says "Try to compile the event handler", or something.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8491)*

**Comment by Ms2ger** [comment]
Squash the two commits and r=me

-S-awaiting-review +S-needs-squash 

---

Reviewed 7 of 7 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8491#-:-KAFltmhNPROrgBKzuxa:-1451953557)*

**Pull request merged**
