### PR TITLE
Ignore /.cargo/

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
catch #5168

### CODE REVIEW

**Comment by SimonSapin** [comment]
Thanks! (I skipped bors for this one, there is no point.)

**Comment by saneyuki** [comment]
@SimonSapin 

your merging did not include the address to @larsbergstrom 's [review](https://critic.hoppipolla.co.uk/showcomment?chain=10889). What should we do?

**Comment by larsbergstrom** [comment]
We can always do another PR. I don't have a strong opinion on including the slash or not (the trailing slash means that it will ignore a directory named .cargo but not a file with that name).

**Comment by SimonSapin** [comment]
Oops, sorry about that.

I think the only use case where the trailing slash makes a difference would be having `.cargo` be a symlink. With the trailing slash, a symlink would not be ignored. However, I believe any reason to have such a symlink is already covered by changing configuration in `.servobuild`.

Feel free to submit another PR to remove it for consistency, but I don’t think it’s a problem either way.

**Pull request merged**
