### PR TITLE
Update WR (hit test fix, render target pool optimizations, picture tree)

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19236)

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css/compositing/mix-blend-mode/mix-blend-mode-animation.html
  └   → /css/compositing/mix-blend-mode/mix-blend-mode-animation.html 5514e28909e55e8bb7581416eb560b78f9592eee
/css/compositing/mix-blend-mode/reference/mix-blend-mode-animation-ref.html 0b76076b41713d8c3650a45c94c931b9a97367ef
Testing 5514e28909e55e8bb7581416eb560b78f9592eee == 0b76076b41713d8c3650a45c94c931b9a97367ef
```

**Comment by glennw** [comment]
@jdm That test was previously accidentally passing. The reason it's failing now should be fixed by a PR in the WR queue (https://github.com/servo/webrender/pull/2048). I'd like to land this in the interim though, since it fixes a hit testing issue. We should be able to re-enable that test next week.

**Comment by jdm** [comment]
Fine by me!
@bors-servo: r+

**Pull request merged**
