### PR TITLE
Enable the Fetch API web platform tests

### PR DESCRIPTION
**Pull request by jeenalee**
This will enable the remaining Fetch API tests, which will be useful for future PRs related to implementing the fetch method.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13260)

### CODE REVIEW

**Comment by jdm** [comment]
I recommend running `wget http://build.servo.org/builders/linux-rel/builds/3153/steps/test_1/logs/test-wpt.log/text`, then `./mach update-wpt text`, committing the results and pushing.

**Comment by KiChjang** [comment]
@bors-servo retry
* infra

**Pull request merged**
