### PR TITLE
Don't serialize url() twice

### PR DESCRIPTION
**Pull request by upsuper**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15949)

### CODE REVIEW

**Review by heycam — APPROVED** [review]
We should fix this on the computed value too, right? r=me with that.

**Comment by upsuper** [comment]
Good catch. Although that probably doesn't really matter, since we don't use Servo code to serialize computed value, and url in filter is currently Gecko-only. But yeah, we should fix both.

**Pull request merged**
