### PR TITLE
Make WebIDL static items take a more specific global if possible

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14376)

### CODE REVIEW

**Comment by jdm** [comment]
Window is the default, so the changes in ecd92a7 should be redundant: https://github.com/servo/servo/pull/13493/files

**Comment by nox** [comment]
AFAIK the plan was to eventually remove `[PrimaryGlobal]` from the spec and make `[Exposed]` mandatory. That's why the HTML spec now is full of explicit `[Exposed=Window]` now.

**Comment by nox** [comment]
I'm also not sure what you mean by redundant, given the commit you link to isn't just about changing `Exposed` attributes.

**Comment by jdm** [comment]
I meant the exposed changes in that commit.

**Comment by nox** [comment]
Ok, I would rather we keep them, and not rely on PrimaryGlobal once all interfaces have an Exposed attribute. What do you think? Cc @Ms2ger.

**Comment by nox** [comment]
See the spec of [`Node`](https://dom.spec.whatwg.org/#node), for example.

**Comment by Ms2ger** [comment]
I agree that explicit is better than implicit.

**Comment by KiChjang** [comment]
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.worker.html:
  │ FAIL [expected PASS] Untitled
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface DOMMatrixReadOnly to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:73:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.worker.js:9:1
```
You'll need some blessings from @jdm or @Ms2ger.

**Comment by nox** [comment]
It's ok, it's in the spec.

@bors-servo r=KiChjang,nox

**Pull request merged**
