### PR TITLE
Fix a panic when using layout 2020

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23920)

### CODE REVIEW

**Comment by jdm** [comment]
That failure is #21067, but test-tidy fails:
```
[94m./components/style/properties/properties.mako.rs[0m:[93m508[0m: [91mLine is longer than 120 characters[0m
```

**Comment by nox** [comment]
Oops, fixed.

@bors-servo r=SimonSapin

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
