### PR TITLE
Refactor in components/script/dom/htmlanchorelement.rs to

### LINKED ISSUE #11280: Make update_href accept a &Url argument instead of DOMString
This is a followup to the changes in #11264. This will allow removing some duplication in all of the callers of `update_href` in `htmlanchorelement.rs`. We can call it from inside the match, rather that storing an intermediary value before calling it.

Code: `components/script/dom/htmlanchorelement.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/text-level-semantics/the-a-element/` (should continue to pass)

### PR DESCRIPTION
**Pull request by shuky19**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [X] These changes fix #11280 (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because test are already exists and passed

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. 

Refactor in components/script/dom/htmlanchorelement.rs to make update_href accept &Url argument

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11349)

### CODE REVIEW

**Comment by KiChjang** [comment]
I'm sorry, but there isn't any consensus on whether this PR is what we need yet.

**Comment by metajack** [comment]
Was there discussion of this somewhere? If so, that discussion should be summarized here.

**Comment by KiChjang** [comment]
The issue referenced (#11280) has discussions that are waiting an answer from @jdm.

**Comment by metajack** [comment]
Sorry, I should have followed the reference. Thanks for clarifying.

**Comment by jdm** [comment]
Sorry, we're going to need to sit on these changes until we resolve the confusion in #11281.

**Comment by jdm** [comment]
Nobody ever replied in #11281. I don't think there's any point in leaving this open until there's some movement there, unfortunately.

**Pull request closed without merging**
