### PR TITLE
Tidy check for FooMethods in components/script/dom/*.rs and color for tidy

### PR DESCRIPTION
**Pull request by cuzbog**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6699)

### CODE REVIEW

**Comment by jdm** [comment]
This is great! Thanks for doing this!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1, 58 of 58 files at r2.
Review status: all files reviewed at latest revision, 42 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/domstringmap.rs, line 38 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqh5vOQrvFI-yqV2jF)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/domstringmap.rs#L38)):</sup>
https://html.spec.whatwg.org/multipage/infrastructure.html#dom-domstringmap-additem

---

<sup>**[components/script/dom/domstringmap.rs, line 43 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqh9TKRJPJQGBVbfOG)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/domstringmap.rs#L43)):</sup>
https://html.spec.whatwg.org/multipage/infrastructure.html#dom-domstringmap-removeitem

---

<sup>**[components/script/dom/domstringmap.rs, line 49 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqhBW-j-enlxbZuZu1)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/domstringmap.rs#L49)):</sup>
https://html.spec.whatwg.org/multipage/infrastructure.html#dom-domstringmap-setitem

---

<sup>**[components/script/dom/domstringmap.rs, line 55 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqhDSdpMXIptQqMc5W)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/domstringmap.rs#L55)):</sup>
https://html.spec.whatwg.org/multipage/infrastructure.html#dom-domstringmap-nameditem

---

<sup>**[components/script/dom/formdata.rs, line 61 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqi3AvmvfCQBhmCOkX)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/formdata.rs#L61)):</sup>
https://xhr.spec.whatwg.org/#dom-formdata-append

---

<sup>**[components/script/dom/formdata.rs, line 115 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqiANXWJ7wjkE_Li63)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/formdata.rs#L115)):</sup>
https://xhr.spec.whatwg.org/#dom-formdata-set

---

<sup>**[components/script/dom/htmlbodyelement.rs, line 73 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqjdWEnEg3UheK_Ari)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/htmlbodyelement.rs#L73)):</sup>
https://html.spec.whatwg.org/multipage/#the-body-element

---

<sup>**[components/script/dom/htmlbodyelement.rs, line 79 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqjemo_56al5hEvGBb)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/htmlbodyelement.rs#L79)):</sup>
https://html.spec.whatwg.org/multipage/#the-body-element

---

<sup>**[components/script/dom/htmlcollection.rs, line 232 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqk7mma3DsZKVWBsxK)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/htmlcollection.rs#L232)):</sup>
https://dom.spec.whatwg.org/#dom-htmlcollection-item

---

<sup>**[components/script/dom/htmlelement.rs, line 159 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqkW8A2GnkqTyUK-0h)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/htmlelement.rs#L159)):</sup>
https://html.spec.whatwg.org/multipage/#handler-onload

---

<sup>**[components/script/dom/htmlelement.rs, line 170 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqkXS88aCUqaysPiO-)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/htmlelement.rs#L170)):</sup>
https://html.spec.whatwg.org/multipage/#handler-onload

---

<sup>**[components/script/dom/keyboardevent.rs, line 764 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmD-hsddAGtUs-DLS)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L764)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-initKeyboardEvent

---

<sup>**[components/script/dom/keyboardevent.rs, line 787 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmI23YFvRs4daMpbt)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L787)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-key

---

<sup>**[components/script/dom/keyboardevent.rs, line 792 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmKWC53RKc1s1ax4e)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L792)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-code

---

<sup>**[components/script/dom/keyboardevent.rs, line 797 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmM6xe_M1kkRKXZtW)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L797)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-location

---

<sup>**[components/script/dom/keyboardevent.rs, line 802 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmN_B1XXkN8KdUYCH)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L802)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-ctrlKey

---

<sup>**[components/script/dom/keyboardevent.rs, line 807 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmPAoKV0gYTFZ5lnZ)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L807)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-shiftKey

---

<sup>**[components/script/dom/keyboardevent.rs, line 812 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmQjVWyrSnjKJioZr)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L812)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-altKey

---

<sup>**[components/script/dom/keyboardevent.rs, line 817 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmRxqHYNN6SaA5BBj)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L817)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-metaKey

---

<sup>**[components/script/dom/keyboardevent.rs, line 822 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmTfVUueTWF4T9_BR)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L822)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-repeat

---

<sup>**[components/script/dom/keyboardevent.rs, line 827 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmV8bOu6XmS0NDahs)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L827)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-isComposing

---

<sup>**[components/script/dom/keyboardevent.rs, line 845 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqm_2BslRBHVO8GsT7)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L845)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-charCode

---

<sup>**[components/script/dom/keyboardevent.rs, line 850 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmaUOehvdCVt9X-25)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L850)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-keyCode

---

<sup>**[components/script/dom/keyboardevent.rs, line 855 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmbdVyWLvttdXLPkb)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/keyboardevent.rs#L855)):</sup>
https://w3c.github.io/uievents/#widl-KeyboardEvent-which

---

<sup>**[components/script/dom/mouseevent.rs, line 167 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmjmRzEuhm-Wg_Ndb)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/mouseevent.rs#L167)):</sup>
https://w3c.github.io/uievents/#widl-MouseEvent-initMouseEvent

---

<sup>**[components/script/dom/namednodemap.rs, line 94 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmpQq8LH2f5SlakOJ)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/namednodemap.rs#L94)):</sup>
https://dom.spec.whatwg.org/#dom-namednodemap-item

---

<sup>**[components/script/dom/nodelist.rs, line 76 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqmwEN8AiinYe4a5Yk)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/nodelist.rs#L76)):</sup>
https://dom.spec.whatwg.org/#dom-nodelist-item

---

<sup>**[components/script/dom/progressevent.rs, line 62 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqn3rgXxSu_SOyZU-B)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/progressevent.rs#L62)):</sup>
https://dom.spec.whatwg.org/#dom-nodelist-item

---

<sup>**[components/script/dom/progressevent.rs, line 67 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqn7gdpLKr-qfi8J9U)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/progressevent.rs#L67)):</sup>
https://xhr.spec.whatwg.org/#dom-progressevent-loaded

---

<sup>**[components/script/dom/progressevent.rs, line 72 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqnBpJ-mLdTnoOiY_5)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/progressevent.rs#L72)):</sup>
https://xhr.spec.whatwg.org/#dom-progressevent-total

---

<sup>**[components/script/dom/screen.rs, line 32 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqnLsE_-sAgokW141W)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/screen.rs#L32)):</sup>
https://drafts.csswg.org/cssom-view/#dom-screen-colordepth

---

<sup>**[components/script/dom/screen.rs, line 37 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqnNMBqaSLqyD24TcM)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/screen.rs#L37)):</sup>
https://drafts.csswg.org/cssom-view/#dom-screen-pixeldepth

---

<sup>**[components/script/dom/window.rs, line 483 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqnyau_WP2pu_R-JIF)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/window.rs#L483)):</sup>
https://html.spec.whatwg.org/multipage/#dom-windowbase64-btoa

---

<sup>**[components/script/dom/window.rs, line 488 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqo-Vjqeo8CJFvffAw)** ([raw file](https://github.com/servo/servo/blob/bf659215e1679a837be78c195c8880938c2312cd/components/script/dom/window.rs#L488)):</sup>
https://html.spec.whatwg.org/multipage/#dom-windowbase64-atob

---

<sup>**[python/tidy.py, line 162 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqfPTCX7jRFp6mEvgI)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L162)):</sup>
`if "// check-tidy: no specs after this line" in line:`

---

<sup>**[python/tidy.py, line 165 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqf1HNSSYABc5_c5KX)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L165)):</sup>
```python
pattern = ""impl<'a> %sMethods for &'a %s {" % (file_name, file_name)
if (pattern.lower()) in line.lower():
```

---

<sup>**[python/tidy.py, line 168 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqet1R77sVUbxHV6Z_)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L168)):</sup>
`if "// https://" in contents[idx - 1] or "// https://" in contents[idx - 2]:`

---

<sup>**[python/tidy.py, line 169 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqeFcpQ_uoYw0HP4ku)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L169)):</sup>
"method declared in webidl is missing a comment with a specification link"

---

<sup>**[python/tidy.py, line 170 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqemFCG7wV397E40rE)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L170)):</sup>
`if '{' in line and in_impl:`

---

<sup>**[python/tidy.py, line 172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqeoy-0ob5Hav2_BP9)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L172)):</sup>
`if '}' in line and in_impl:`

---

<sup>**[python/tidy.py, line 191 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqfatcp3TmClo7FPEO)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L191)):</sup>
base_path = "components/script/dom/"
`if base_path in file_name:`

---

<sup>**[python/tidy.py, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqfxBNTAg3aSCKGvGT)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L192)):</sup>
```python
stripped_name = os.path.relpath(os.path.splitext(file_name), base_path)
for error in check_spec(contents, stripped_name)
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
<sup>**[python/tidy.py, line 191 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqfatcp3TmClo7FPEO)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L191)):</sup>
Won't work, because there are subfolders.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
<sup>**[python/tidy.py, line 191 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqfatcp3TmClo7FPEO)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L191)):</sup>
We're only checking components/script/dom/*.rs, right?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
<sup>**[python/tidy.py, line 191 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqfatcp3TmClo7FPEO)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L191)):</sup>
Never mind.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
<sup>**[python/tidy.py, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqfxBNTAg3aSCKGvGT)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L192)):</sup>
`stripped_name = os.path.relpath(file_name, base_path)`, otherwise tuple error.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
<sup>**[python/tidy.py, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqfxBNTAg3aSCKGvGT)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L192)):</sup>
And still needs`.rs` removed, is there a point in changing this (or am I doing something wrong)?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 42 unresolved discussions, all commit checks successful.

---

<sup>**[python/tidy.py, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-JuqfxBNTAg3aSCKGvGT)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L192)):</sup>
Ah, the tuple error was because splitext returns `(name, extension)`. If we use the first field then we don't need to manually remove the `.rs` any longer. I find these changes easier to reason about than hardcoding `[22:-3]` in the code.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
<sup>**[python/tidy.py, line 168 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6699#-Juqet1R77sVUbxHV6Z_)** ([raw file](https://github.com/servo/servo/blob/81ba7a6ba2c8487391215ac29680f5b07542f0b1/python/tidy.py#L168)):</sup>
if not ("// https://" in contents[idx - 1] and "// https://" in contents[idx - 2]):

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
@jdm Thanks for the help! I think everything is fine now :)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 18 of 18 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/progressevent.rs, line 62 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6699#-JurBdbcoA0GmV9dmUha)** ([raw file](https://github.com/servo/servo/blob/2015be6910ef1216089952cb661667b61cc62dea/components/script/dom/progressevent.rs#L62)):</sup>
Not quite.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
<sup>**[components/script/dom/progressevent.rs, line 62 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6699#-JurBdbcoA0GmV9dmUha)** ([raw file](https://github.com/servo/servo/blob/2015be6910ef1216089952cb661667b61cc62dea/components/script/dom/progressevent.rs#L62)):</sup>
?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/progressevent.rs, line 62 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6699#-JurBdbcoA0GmV9dmUha)** ([raw file](https://github.com/servo/servo/blob/2015be6910ef1216089952cb661667b61cc62dea/components/script/dom/progressevent.rs#L62)):</sup>
You want https://xhr.spec.whatwg.org/#dom-progressevent-lengthcomputable instead.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
@jdm Ok, I solved that.

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

Thanks!

---

Reviewed 2 of 3 files at r4.
Review status: 58 of 59 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by jdm** [comment]
@bors-servo: r+
-S-needs-rebase +S-awaiting-merge -S-awaiting-review 

---

Reviewed 1 of 3 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by boghison** [comment]
You must be kidding me. For future reference, tidy PRs should be merged ASAP

**Comment by jdm** [comment]
Sorry, I would have but github doesn't notify me when a new commit appears in a PR.

**Comment by boghison** [comment]
@jdm Then I'm notifying you

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 11 of 11 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6699)

**Comment by jdm** [comment]
I'm really sorry; our CI infrastructure has been having load problems and this didn't get merged. Rebase again? :/

**Comment by boghison** [comment]
@jdm How about now?

**Comment by frewsxcv** [comment]
Wow, loving all the new spec links here, nice job @boghison :)

**Comment by Ms2ger** [comment]
@bors-servo: retry
* #6748

**Comment by jdm** [comment]
@bors-servo: retry
* #6748

**Comment by boghison** [comment]
@frewsxcv Thanks, but @jdm helped *a lot*, as you can see

**Pull request merged**
