### PR TITLE
Flesh out the iframe attribute processing steps.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10972)

### CODE REVIEW

**Comment by Ms2ger** [comment]
r=me on @jdm's parts; r? @jdm for a second set of eyes on the changes I made.

**Comment by jdm** [comment]
Oof, https://gist.github.com/jdm/20298f81c0788359f46ef358f31a19f1 suggests there's some problems.

**Comment by Ms2ger** [comment]
Looks like there's two issues here:
* we need a pipeline ID; might need to just fold this into #8600 again to fix that
* https://github.com/whatwg/html/issues/1173

**Comment by jdm** [comment]
This appears to be abandoned. Better luck next time!

**Pull request closed without merging**
