### PR TITLE
Replace watcher threads with panic handlers

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10572)

### CODE REVIEW

**Comment by asajeffrey** [comment]
This change looks fine, but we probably want a more comprehensive story about error handling at some point.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/util/thread.rs, line 64 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFFy9Fl8epyq4xGfnn9:-KFFy9Fl8epyq4xGfnnA:753975067) ([raw file](https://github.com/servo/servo/blob/1d8072c54f8a3ade313555d972cf932419318d95/components/util/thread.rs#L64)):*
We could make this `dest: S` rather than `dest: Option<S>`, and then pass in `()` in the case where we're not sending a message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10572#-:-KFFybeUA4fbnImPGdFA:-246018941)*

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/util/thread.rs, line 64 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFFy9Fl8epyq4xGfnn9:-KFG7mu-MlPy8NS5GflU:969745840) ([raw file](https://github.com/servo/servo/blob/1d8072c54f8a3ade313555d972cf932419318d95/components/util/thread.rs#L64)):*
The only issue is that the debug log will always print in that case. Is that okay?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10572)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/util/thread.rs, line 64 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFFy9Fl8epyq4xGfnn9:-KFGDKgCQwEgGRDvPOvs:-510980002) ([raw file](https://github.com/servo/servo/blob/1d8072c54f8a3ade313555d972cf932419318d95/components/util/thread.rs#L64)):*
I think that's fine, `debug!` messages aren't a performance worry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10572)*

**Comment by asajeffrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/util/thread.rs, line 92 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFGFxY9jELeHUXea4CG:-KFGFxY9jELeHUXea4CH:894798000) ([raw file](https://github.com/servo/servo/blob/cbb265e439cf9692b4227a45421f7a8357ccda6f/components/util/thread.rs#L92)):*
We should probably reword this debug message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10572)*

**Comment by asajeffrey** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10572)*

**Comment by KiChjang** [comment]
```
Ran 4669 tests finished in 1070.0 seconds.
  • 4668 ran as expected. 1361 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected CRASH] /html/semantics/embedded-content/the-img-element/update-the-image-data/fail-to-resolve.html
  │ 
  │ thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidIpv6Address', ../src/libcore/result.rs:746
  │ stack backtrace:
  │    1:        0x10b6e82c8 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
  │    2:        0x10b6ee5b5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
  │    3:        0x10b6ee1cc - std::panicking::default_hook::h08ad3bb09872855b
  │    4:        0x10a95e1ed - util::thread::spawn_named_with_send_on_failure_maybe::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h42c597ffe8d62528
  │    5:        0x10a95e1ed - util::thread::spawn_named_with_send_on_failure_maybe::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h42c597ffe8d62528
  │    6:        0x10a95e1ed - util::thread::spawn_named_with_send_on_failure_maybe::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h42c597ffe8d62528
  │    7:        0x10a95e1ed - util::thread::spawn_named_with_send_on_failure_maybe::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h42c597ffe8d62528
  │    8:        0x10a95e1ed - util::thread::spawn_named_with_send_on_failure_maybe::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h42c597ffe8d62528
  │    9:        0x10ac28f0d - util::thread::spawn_named_with_send_on_failure_maybe::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h7b909c316fd96a1b
  │   10:        0x10ac28f0d - util::thread::spawn_named_with_send_on_failure_maybe::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h7b909c316fd96a1b
  │   11:        0x10b6d5dc8 - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
  │   12:        0x10b6d76fe - std::sys_common::unwind::begin_unwind_fmt::h57ea3fbee1a40196
  │   13:        0x10b6e7597 - rust_begin_unwind
  │   14:        0x10b715ff0 - core::panicking::panic_fmt::ha6b3c19493c123b3
  │   15:        0x10a4a5a92 - core::result::unwrap_failed::h0c839604c267a932
  │   16:        0x10a4a8f9d - _<dom..htmlimageelement..HTMLImageElement as dom..virtualmethods..VirtualMethods>::attribute_mutated::hca84433617991a25
  │   17:        0x10a1f5052 - script::dom::element::Element::push_attribute::h66f97a220dd374a5
  │   18:        0x10a1f4d3d - script::dom::element::Element::push_new_attribute::h1ec092485ab1d84c
  │   19:        0x10a1f582a - script::dom::element::Element::set_attribute_from_parser::h8b3a181ebd69b869
  │   20:        0x10a236c8d - script::parse::html::_<impl html5ever..tree_builder..TreeSink for dom..servohtmlparser..Sink>::create_element::h89dbe4111d373de7
  │   21:        0x10a4d09f2 - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tree_builder..actions..TreeBuilderActions<Handle>>::insert_element::hf6309733f5e7b254
  │   22:        0x10a4e017e - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tree_builder..rules..TreeBuilderStep>::step::h93ab3bfcf1691622
  │   23:        0x10a4c9c8c - _<html5ever..tree_builder..TreeBuilder<Handle, Sink> as html5ever..tokenizer..TokenSink>::process_token::h2ab46857f7deb4ad
  │   24:        0x10a4c9351 - _<html5ever..tokenizer..Tokenizer<Sink>>::process_token::h9af6f4ff4f9b91c3
  │   25:        0x10a4f707c - _<html5ever..tokenizer..Tokenizer<Sink>>::emit_current_tag::ha3a7e889987621fc
  │   26:        0x10a4f4960 - _<html5ever..tokenizer..Tokenizer<Sink>>::step::h6d0c3ad36918d153
  │   27:        0x10a4ecf87 - _<html5ever..tokenizer..Tokenizer<Sink>>::run::hd992ab6f97dc045a
  │   28:        0x10a4c393a - script::dom::servohtmlparser::ServoHTMLParser::parse_sync::h46474db81a0f7e9d
  │   29:        0x10a5adf06 - script::dom::document::Document::finish_load::hcfd8a11ed8391a31
  │   30:        0x10a5d83e8 - _<dom..htmlscriptelement..ScriptContext as net_traits..AsyncResponseListener>::response_complete::h40072aa6124e07ae
  │   31:        0x10acda1d5 - net_traits::ResponseAction::process::h0f42bbdc19738906
  │   32:        0x10a5dba01 - _<network_listener..ListenerRunnable<T> as script_thread..Runnable>::handler::h4eee1cf024ddf8d5
  │   33:        0x10a2558ce - script::script_thread::ScriptThread::handle_msg_from_script::hf5b489b6a847acd7
  │   34:        0x10a2a6dc8 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::h73eff2b1fdf241f0
  │   35:        0x10a294695 - script::script_thread::ScriptThread::handle_msgs::h56b62e268fb8eb5a
  │   36:        0x10a247d47 - std::sys_common::unwind::try::try_fn::h0857d23e95acfabe
  │   37:        0x10b6e752b - __rust_try
  │   38:        0x10b6e74b3 - std::sys_common::unwind::inner_try::h4e97625a08807651
  │   39:        0x10a24953a - _<F as std..boxed..FnBox<A>>::call_box::hfdc004bdc48c980d
  │   40:        0x10b6ed628 - std::sys::thread::Thread::new::thread_start::h74af400293164137
  │   41:     0x7fff86bcf059 - _pthread_body
  └   42:     0x7fff86bcefd6 - _pthread_start
```

**Comment by asajeffrey** [comment]
@bors-servo retry
* testing to see if html/semantics/embedded-content/the-img-element/update-the-image-data/fail-to-resolve.html is a new intermittent

**Comment by Manishearth** [comment]
The issue was that `set_hook` is a global thing, not a per-thread thing as I had expected. This caused tons of recursion in set_hook and hard-fail mode stopped working.

I changed it so that it only sets the hook once, and uses a TLS thunk to notify the constellation.

**Comment by Manishearth** [comment]
This needs more review; r? @asajeffrey 

One thing we might want to do is call the panic handler initialization somewhere in the Servo main function. What do you think?

**Comment by Manishearth** [comment]
Tests pass (the failure was a tidy failure, since fixed)

**Comment by asajeffrey** [comment]
In the multi-process case, is the panic hook per-process?

**Comment by Manishearth** [comment]
Yep, because the Once is per-process

**Comment by Manishearth** [comment]
(We don't use `fork()` to duplicate processes, we just find the current process command and tell the OS to spin a copy up. `fork()` in Rust sounds like a very bad idea anyway)

**Comment by asajeffrey** [comment]
OK, so registering the panic hook when the process is started up is probably a good idea. We may need a different hook for the top-level process than for the content processes.

**Comment by asajeffrey** [comment]
Since we're taking a pause here to work out how to register a per-process panic handler, I think we should land #10587.

**Comment by Manishearth** [comment]
Moved to panicking.rs. r?

**Comment by asajeffrey** [comment]
Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/servo/main.rs, line 55 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFKrU4ilWIV6hn75ZhR:-KFKrU4ilWIV6hn75ZhS:1144909640) ([raw file](https://github.com/servo/servo/blob/da2f0445d505792db26376af3c2bf77ac7720ee7/components/servo/main.rs#L55)):*
Can we replace this by `set_hook(Box::new(panic_hook))` and have `servo::util::panicking` just export `panic_hook`?

---

*[components/util/panicking.rs, line 27 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFKsG2PgAIy-k_C5pIK:-KFKsG2QVShTm3RLvDxc:1573031911) ([raw file](https://github.com/servo/servo/blob/da2f0445d505792db26376af3c2bf77ac7720ee7/components/util/panicking.rs#L27)):*
This seems over-complex compared to just exporting a function `panic_hook` and letting the main program decide how/when to register it.

---

*[components/util/thread.rs, line 85 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFKsmzj7ydwQmf8-jm5:-KFKsmzj7ydwQmf8-jm6:465016666) ([raw file](https://github.com/servo/servo/blob/da2f0445d505792db26376af3c2bf77ac7720ee7/components/util/thread.rs#L85)):*
I really don't like this, since it's adding some completely unknown code to the panic hook. We should try to avoid any potential source of double-panic.

---

*[ports/gonk/src/main.rs, line 65 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFKtIKUvqQgvgQiAsJ1:-KFKtIKUvqQgvgQiAsJ2:785174237) ([raw file](https://github.com/servo/servo/blob/da2f0445d505792db26376af3c2bf77ac7720ee7/ports/gonk/src/main.rs#L65)):*
Same comment as for `servo/main.rs`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10572)*

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/servo/main.rs, line 55 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFKrU4ilWIV6hn75ZhR:-KFKyKso59YSb3Adw023:1598030160) ([raw file](https://github.com/servo/servo/blob/da2f0445d505792db26376af3c2bf77ac7720ee7/components/servo/main.rs#L55)):*
We can't, because the new hook will need to capture the old hook. This is why the panic hook is a closure in the first place.

---

*[components/util/panicking.rs, line 27 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFKsG2PgAIy-k_C5pIK:-KFKyXniq9OZx7SD1geY:-1263119049) ([raw file](https://github.com/servo/servo/blob/da2f0445d505792db26376af3c2bf77ac7720ee7/components/util/panicking.rs#L27)):*
It needs to capture the old hook.

---

*[components/util/thread.rs, line 85 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFKsmzj7ydwQmf8-jm5:-KFKyaxssk2BumJmxMWu:1422249157) ([raw file](https://github.com/servo/servo/blob/da2f0445d505792db26376af3c2bf77ac7720ee7/components/util/thread.rs#L85)):*
This function is private, the public function above uses implementors of `SendOnFailure` which can be verified for double panics above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10572)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/servo/main.rs, line 55 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFKrU4ilWIV6hn75ZhR:-KFL0DfDMYqvY248-X4S:505055018) ([raw file](https://github.com/servo/servo/blob/da2f0445d505792db26376af3c2bf77ac7720ee7/components/servo/main.rs#L55)):*
Why does it? Shouldn't this be up to the main program?

---

*[components/util/thread.rs, line 85 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10572#-KFKsmzj7ydwQmf8-jm5:-KFL0Ryr1oDNbL5gkvtf:1533641003) ([raw file](https://github.com/servo/servo/blob/da2f0445d505792db26376af3c2bf77ac7720ee7/components/util/thread.rs#L85)):*
I still prefer the original, it was easier to see which code is being executed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10572)*

**Comment by asajeffrey** [comment]
OK, we're agreed (in IRC) that in the long term, the call to initialize the panic hook will be replaced by having the constellation panic handler printing the backtrace. So this can go through as-is.

bors-servo: r+

**Pull request merged**
