### PR TITLE
Resync bindings

### PR DESCRIPTION
**Pull request by Manishearth**
New atoms were added.

r? @bholley

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13221)

### CODE REVIEW

**Comment by Manishearth** [comment]
(Cherry picked this onto the incubator and pushed an update (to http://hg.mozilla.org/incubator/stylo/rev/78dff9c4cf75). Wikipedia works.

I've also uplifted @shinglyu's patch from https://bugzilla.mozilla.org/show_bug.cgi?id=1301316 . The reftest lists are already in tree, but these changes can't be made a part of m-c. They should be re-grafted each update. This will get us reftest runs on try builds. Note that there are a bunch of intermittents right now, which AIUI will be marked as such soon.

**Comment by bholley** [comment]
On PTO. Flag Emilio?

**Comment by Manishearth** [comment]
Oh, right.

r? @emilio

**Pull request merged**
