### PR TITLE
Alternative CA database generator

### PR DESCRIPTION
**Pull request by Darkspirit**
[resources/certs](https://github.com/servo/servo/blob/master/resources/certs) is Servo's CA database and was last updated on 3 Apr 2017. Symantec has been revoked in the meantime.
[etc/cert_generator.js](https://github.com/servo/servo/blob/b9847e29537f2c7dc3515f28342f9b519f2c9790/etc/cert_generator.js) is an XPCShell script for updating the certs file, but I found it too complex to run, so I made a simpler script.

What it does:
1. Download Mozilla's [official](https://wiki.mozilla.org/CA/Included_Certificates) CA database CSV file with curl and process it with awk: https://ccadb-public.secure.force.com/mozilla/IncludedCACertificateReportPEMCSV
2. rows end with "\n
3. split each row by `^"` and `","` into columns. (I had to remove `"$` because of servo-tidy.)
4. remove single and double quotes from column 30
5. if column 13 (12 in the csv file) contains `Websites` (some are Email-only), print column 30, the raw certificate
6. put everything into a `certs` file

servo-tidy wasn't happy so I had to make it a bit uglier. lol
> ./etc/cert_generator.sh:8: Line is longer than 80 characters
> ./etc/cert_generator.sh:8: script is missing options "set -o errexit", "set -o nounset", "set -o pipefail"
> ./etc/cert_generator.sh:8: variable substitutions should use the full "${VAR}" form
> ./etc/cert_generator.sh:8: variable substitutions should use the full "${VAR}" form
> ./etc/cert_generator.sh:8: variable substitutions should use the full "${VAR}" form
> ./etc/cert_generator.sh:8: variable substitutions should use the full "${VAR}" form

---
- [x] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22254)

### CODE REVIEW

**Comment by paulrouget** [comment]
Can you add the above comments to the script?
Otherwise, looks good to me. I had to replace awk with gawk on Mac.

**Comment by Darkspirit** [comment]
Ok. Here on Debian Testing, awk is a shortcut for gawk, so we can just use gawk directly.

**Comment by paulrouget** [comment]
gawk works. Thank you.

@bors-servo r+

**Comment by Darkspirit** [comment]
servo/intermittent-failure-tracker#5

**Comment by paulrouget** [comment]
@bors-servo retry

- servo/intermittent-failure-tracker#5

**Comment by CYBAI** [comment]
Failed with servo/intermittent-failure-tracker#5 again. Maybe need someone to fix it in builders.

**Comment by jdm** [comment]
@bors-servo retry
* #22271

**Comment by jdm** [comment]
@bors-servo retry
* #22271

**Pull request merged**
