### PR TITLE
Minor code cleanup in layout

### PR DESCRIPTION
**Pull request by mbrubeck**
r? @pcwalton

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11752)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Can we hold off on landing this for a day or two?

**Comment by mbrubeck** [comment]
> Can we hold off on landing this for a day or two?

Sure.

**Comment by Ms2ger** [comment]
... and until #11754 lands.

**Comment by mbrubeck** [comment]
Rebased. r? @pcwalton

**Pull request merged**
