### PR TITLE
Fixing Intermittent failure in pages with timers

### LINKED ISSUE #4923: Intermittent failure in pages with timers
I see one new failure [here](http://build.servo.org/builders/mac2/builds/962/steps/shell/logs/stdio):
```
thread 'Window:SetTimeout' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /Users/larsberg/rust/src/libcore/result.rs:743
stack backtrace:
   1:        0x10b091927 - sys::backtrace::write::h084c3267f5afd4a3hvy
   2:        0x10b0a7893 - failure::on_fail::hc5ca3b9ac2e803f33NF
   3:        0x10b074b58 - rt::unwind::begin_unwind_inner::h6a7a87805596eb8avvF
   4:        0x10b0752c1 - rt::unwind::begin_unwind_fmt::h1fd6919e00fae1f31tF
   5:        0x10b0a728e - rust_begin_unwind
   6:        0x10b0c9f97 - panicking::panic_fmt::hd22743a6fa1fac27zow
   7:        0x10a4deadc - result::Result<T, E>::unwrap::h14384637977615199039
   8:        0x10a4de8bd - script_task::NonWorkerScriptChan.ScriptChan::send::h7a77ad0a9e7dcfe07rD
   9:        0x10a537d97 - timers::TimerManager::set_timeout_or_interval::closure.88350
  10:        0x10a537691 - task::spawn_named::closure.88343
  11:        0x10a537564 - thunk::Thunk<(), R>::new::closure.88339
  12:        0x10a53742d - thunk::F.Invoke<A, R>::invoke::h9755239712050321226
  13:        0x10a2d2ac1 - thunk::Thunk<A, R>::invoke::h11641617110891784916
  14:        0x10a2d37fa - thread::Builder::spawn_inner::closure.81789
  15:        0x10a2d377f - rt::unwind::try::try_fn::__rust_abi::h13345969517191097717
  16:        0x10a2d371a - rt::unwind::try::try_fn::h13345969517191097717
  17:        0x10b0a9279 - rust_try_inner
  18:        0x10b0a9266 - rust_try
  19:        0x10a2d2c0c - rt::unwind::try::h5213795867344952062
  20:        0x10a2d194f - thread::Builder::spawn_inner::closure.81687
  21:        0x10a2d47d9 - thunk::Thunk<(), R>::new::closure.81810
  22:        0x10a2d46c1 - thunk::F.Invoke<A, R>::invoke::h11315143147767302084
  23:        0x10b095353 - sys::thread::thread_start::h8d91e5be653c10c05CB
  24:     0x7fff8e0db772 - _pthread_start
```
This should just be a silent failure; there's no need to unwrap the result, we can just check for failure and shut the task down gently. Relevant code is in `components/script/timers.rs`.

### PR DESCRIPTION
**Pull request by psdh**
Fixes #4923

### CODE REVIEW

**Comment by psdh** [comment]
I get a bunch of unused result warnings, I am trying to find a way to resolve them

**Comment by jdm** [comment]
You can just add the unwrap back to all of the callers that aren't the timer code now. That will bring us back to the status quo and get rid of the warnings.

**Comment by jdm** [comment]
Looking good! Just a rebase required now.

**Comment by psdh** [comment]
@jdm Done ^ :)

**Pull request merged**
