### PR TITLE
Update servo-egl to fix CEF linkage

### LINKED ISSUE #10130: embedding shared lib no longer linkable
```
undefined reference to `eglDestroyImageKHR'
undefined reference to `eglCreateImageKHR'
```

cc @larsbergstrom @pcwalton @glennw @jdm

### PR DESCRIPTION
**Pull request by larsbergstrom**
Fixes #10130 
r? @zmike

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10174)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@bors-servo retry

Network on AppVeyor:
```
nstalling setuptools, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python2.7
    Updating registry `https://github.com/rust-lang/crates.io-index`
Unable to update https://github.com/Ygg01/xml5ever#6c701706 
 
Caused by:
  failed to update submodules
 
Caused by:
  [2/-1] Failed to receive response: The server returned an invalid or unrecognized response
 
cargo build -v
Build completed in 92.49s
Command exited with code 101
```

**Comment by jdm** [comment]
@bors-servo: retry
* #9724

**Comment by larsbergstrom** [comment]
@bors-servo: retry

    #9724

(is homu having problems? sigh)

**Comment by larsbergstrom** [comment]
@bors-servo retry

appveyor madness

**Pull request merged**
