### PR TITLE
Implement File DOM object interface

### PR DESCRIPTION
**Pull request by izgzhen**
- Rewrite constructors of `Blob` and `File` with `DataSlice` as argument
- Update WebIDL of `Blob` and `File`
- Implement missing interfaces of `File` (However, due to lack of working `ArrayBuffer/ArrayBufferView` in `Blob`, so it still differs from spec)
- Update WPT test `File-constructor.html`

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11076)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I talked to @izgzhen on IRC; we're going to simplify `Blob`/`File` construction first, by passing in `DataSlice` consistently.

**Comment by mbrubeck** [comment]
@bors-servo retry

* network error

**Pull request merged**
