### PR TITLE
Make session history aware of URLs

### PR DESCRIPTION
**Pull request by cbrewster**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach build-geckolib` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20671)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Looking good so far. Let me know when you'd like a review!

**Comment by cbrewster** [comment]
@asajeffrey will do!
I need to write couple test cases that this PR fixes and verify that this is actually working. Testing this is pretty tricky.

**Comment by asajeffrey** [comment]
OK, finally dug myself out from under SM... This all looks good! I'm a bit surprised there aren't any new passing tests, do you have a feeling for why? Apart from that, yay, you can r=me.

**Comment by cbrewster** [comment]
I believe most tests are relying on other things to be implemented, like adding history entries when `location.hash` is set. Once that is implemented, there should be some more passing tests.

@bors-servo r=asajeffrey

**Pull request merged**
