### PR TITLE
Add note on Windows build

### LINKED ISSUE #18256: An alternative solution to build on Windows
As #18055 happens, I am still not able to build followed by README. Although @larsbergstrom tested it works as #18157, but I always test failed. I try to debug, but no progress.

I find an alternative solution to build on windows, and it works. I think it is worth to share, and let other developers who encountering problems while building have a new way.

Here's the steps:

1.  Download and install [Build Tools for Visual Studio 2017](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15)
2.  Install `python2.7 x86-x64` and `virtualenv`
3.  Since `mach.bat` cannot find the prompt, we should execute `Developer Command Prompt for VS 2017` manually in the Windows menu.
4. `cd to/the/path/servo`
5. `python mach build -d`

### PR DESCRIPTION
**Pull request by tigercosmos**
Update `README` with workaround note about an alternative solution to build on Windows.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #18256 .

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it's `README`

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18291)

### CODE REVIEW

**Comment by shinglyu** [comment]
I guess we should just write down the steps in the README. Reader needs to take extra effort reading through the bug discussion.

And maybe r?@larsbergstrom

**Comment by larsbergstrom** [comment]
I agree that putting the alternative instructions in the README would get an r+ from me! Thanks for the contribution.

**Comment by tigercosmos** [comment]
Should I close this PR and open a new one to do that?

**Comment by larsbergstrom** [comment]
Whatever is easiest for you is fine for us! Thanks for your patience and hard work on this issue.

**Pull request closed without merging**
