### PR TITLE
Update WR (1st round of box shadow optimizations)

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19066)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone

**Comment by jdm** [comment]
```
  ▶ PASS [expected FAIL] /_mozilla/css/text_shadow_blur_a.html
```

**Comment by glennw** [comment]
Added a new PASS.

@bors-servo r=jdm

**Comment by jdm** [comment]
@bors-servo: retry
* #13479

**Pull request merged**
