### PR TITLE
adding initial support for websocket subprotocol negotation

### PR DESCRIPTION
**Pull request by jmr0**
Addresses #8177 

I also noticed some bugs/gaps (and at least one of my TODO's can be an E-Easy)

cc @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8825)

### CODE REVIEW

**Comment by frewsxcv** [comment]
*[components/script/dom/websocket.rs, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8825#-K4i3OOF_3YB2Pp6cTMt:-K4i3OOF_3YB2Pp6cTMu:-1918715795) ([raw file](https://github.com/servo/servo/blob/cb2bc253c505a308a80a66563680959752cc19e9/components/script/dom/websocket.rs#L192)):*
I don't think the `!protocols.is_empty()` is necessary here since calling `.iter()` on an empty collection is a no-op

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8825)*

**Comment by frewsxcv** [comment]
*[components/script/dom/websocket.rs, line 208 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8825#-K4i3-hIK-ugZPCcNN2q:-K4i3-hJhN2y8RLDRDxE:-1736606581) ([raw file](https://github.com/servo/servo/blob/cb2bc253c505a308a80a66563680959752cc19e9/components/script/dom/websocket.rs#L208)):*
Alternatively, I think something like this would also work:

```
if let Some(ref p) = protocol_list.get(0) {
  return Some(p);
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8825)*

**Comment by jmr0** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/websocket.rs, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8825#-K4i3OOF_3YB2Pp6cTMt:-K4iBPw0gWDmZJRjfb9v:1078450059) ([raw file](https://github.com/servo/servo/blob/cb2bc253c505a308a80a66563680959752cc19e9/components/script/dom/websocket.rs#L192)):*
The idea here was to shortcut out if we were dealing with an empty vector -- this Err should not be triggered if protocols is empty, and if iter().any() returns false on an empty vector, Err would be incorrectly triggered I think

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8825)*

**Comment by frewsxcv** [comment]
*[components/script/dom/websocket.rs, line 192 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8825#-K4i3OOF_3YB2Pp6cTMt:-K4mEvnxyjcXi4kUsTkI:1238289654) ([raw file](https://github.com/servo/servo/blob/cb2bc253c505a308a80a66563680959752cc19e9/components/script/dom/websocket.rs#L192)):*
Yeah, that sounds right. I think I overlooked the `!` after the `&&`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8825)*

**Comment by jdm** [comment]
Great work! I've made a couple comments on ways to clarify the code, but I was able to compare this against the specification text without difficulty.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 10 of 10 files at r1.
Review status: 9 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/websocket.rs, line 204 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8825#-K5g2uokbqL8-IEVy-Vk:-K5g2uokbqL8-IEVy-Vl:-1855893735) ([raw file](https://github.com/servo/servo/blob/cb2bc253c505a308a80a66563680959752cc19e9/components/script/dom/websocket.rs#L204)):*
nit: add a space after ///

---

*[components/script/dom/websocket.rs, line 206 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8825#-K5g2zGU5DTdPuUnMn7T:-K5g2zGU5DTdPuUnMn7U:1627703567) ([raw file](https://github.com/servo/servo/blob/cb2bc253c505a308a80a66563680959752cc19e9/components/script/dom/websocket.rs#L206)):*
```rust
wsp.and_then(|protocol_list| protocol_list.get(0).map(|protocol| &*protocol))
```

---

*[components/script/dom/websocket.rs, line 539 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8825#-K5gfBMfh9mAs5dEGlxW:-K5gfBMfh9mAs5dEGlxX:265485709) ([raw file](https://github.com/servo/servo/blob/cb2bc253c505a308a80a66563680959752cc19e9/components/script/dom/websocket.rs#L539)):*
This could move into the related `if` block.

---

*[components/script/dom/websocket.rs, line 540 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8825#-K5gfGn_ygqG5rERLreq:-K5gfGn_ygqG5rERLrer:1046665214) ([raw file](https://github.com/servo/servo/blob/cb2bc253c505a308a80a66563680959752cc19e9/components/script/dom/websocket.rs#L540)):*
I don't think this change is necessary?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8825#-:-K5ggQPkdPheK3Dq5pVV:481626285)*

**Comment by jdm** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/net_traits/lib.rs, line 434 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8825#-K5ggjg30ijlk4UCrysw:-K5ggjg4AQUI9a1YONNX:1147212567) ([raw file](https://github.com/servo/servo/blob/d617628cfe65eb8a80676a3e941c14655f8165ab/components/net_traits/lib.rs#L434)):*
nit: space after ///

---

*[components/net_traits/lib.rs, line 436 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8825#-K5ggnodDd1-NTmMW434:-K5ggnodDd1-NTmMW435:1627703567) ([raw file](https://github.com/servo/servo/blob/d617628cfe65eb8a80676a3e941c14655f8165ab/components/net_traits/lib.rs#L436)):*
```rust
wsp.and_then(|protocol_list| protocol_list.get(0).map(|protocol| &*protocol))
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8825)*

**Comment by jmr0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/net_traits/lib.rs, line 436 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8825#-K5ggnodDd1-NTmMW434:-K5gxoMSXdrdU_i3k1Bj:-982399031) ([raw file](https://github.com/servo/servo/blob/d617628cfe65eb8a80676a3e941c14655f8165ab/components/net_traits/lib.rs#L436)):*
oddly enough, the &* syntax here leads to expected `core::option::Option<&str> found `core::option::Option<&collections::string::String>` but using as_ref() works

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8825)*

**Comment by jdm** [comment]
Go ahead an squash this into a single commit, then it will be ready for merging. Thanks!
-S-awaiting-review +S-needs-squash 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8825#-:-K5hXDv2o9O5sTZEO1pI:-341461476)*

**Comment by jmr0** [comment]
All set. Thanks again.

**Comment by jdm** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] WebSocket interface: attribute protocol
```
One more test result change required.

**Comment by KiChjang** [comment]
```

Ran 3735 tests finished in 869.0 seconds.
  • 3734 ran as expected. 708 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /_mozilla/css/iframe/hide_layers2.html
  │ 
  │ thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
  │ stack backtrace:
  │    1:        0x110180638 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x1101826ff - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x1101821a2 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x11016dfb6 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x11016e39e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
  │    6:        0x11017fc57 - rust_begin_unwind
  │    7:        0x1101a4d60 - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:        0x10eb8fa7d - constellation::_<impl>::handle_request::handle_request::h3729023280372224693
  │    9:        0x10eb717d7 - sys_common::unwind::try::try_fn::try_fn::h8847135229958083224
  │   10:        0x11017fa78 - __rust_try
  │   11:        0x11017cb7e - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   12:        0x10eb73cba - boxed::_<impl>::call_box::call_box::h8173981309006571422
  │   13:        0x11018198d - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   14:     0x7fff8416a059 - _pthread_body
  └   15:     0x7fff84169fd6 - _pthread_start
```

**Comment by jdm** [comment]
@bors-servo: retry
* #8769

**Pull request merged**
