### PR TITLE
net: Try to turn on HTTP pooling.

### PR DESCRIPTION
**Pull request by pcwalton**
But I don't see any actual pooling going on in Wireshark. What am I
doing wrong?

r? @jdm 
r? @seanmonstar

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6026)

### CODE REVIEW

**Comment by seanmonstar** [comment]
It looks correct to me. Here's possible reasons it's not reused:

- Connections are to different `(scheme, host, port)` triples (of course).
- The server responds with a `Connection: close` header.
- The response isn't drained (read till EOF).

Turning on `RUST_LOG=hyper` would help show if there are the case. Specifically, a `TRACE:hyper::client::pool` occurs when the `PooledStream` is dropped, listing `is_closed` (connection header) and `is_drained` (read to EOF).

If they're `false` and `true` respectively, you should see a second trace `reuse (scheme, host, port)`.

-----------

One situation needs to handled manually in this PR: if the pooled connection has been killed or timed out by the server, it will still be in the Pool and given out when another connection is requested. I imagine handling the error case when passing `Request::with_connector` would need to check for something like `io::ErrorKind::NotConnected` or `ConnectionAborted` (I don't know yet), and if so, try again with the connector, which will use a different stream.

I haven't thought of a good way to do that myself in hyper yet.

**Comment by jdm** [comment]
I'm not keen on the huge block in which the connector is exclusively locked. Is there a way to minimize that?

**Comment by pcwalton** [comment]
@jdm I tried to get it as small as I reasonably could, but I could try to do better. Note that apparently if we do another hyperup, we won't need the lock at all.

**Comment by seanmonstar** [comment]
Yea, that will be in 0.5, no longer taking a `&mut Connector`: https://github.com/hyperium/hyper/commit/1b318724a5fd425366daddf15c5964d7c3cbc240

**Comment by pcwalton** [comment]
I removed the block and added retrying in the case @seanmonstar requested. r? @jdm

**Comment by jdm** [comment]
-S-awaiting-review +S-awaiting-answer 

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/net/http_loader.rs @ r1
- components/net/resource_task.rs @ r1

---

<sup>**[components/net/http_loader.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6026#-JpmoRglJYPFoMwiLIC8)** ([raw file](https://github.com/servo/servo/blob/17ee730456620e86feb2eaf843459cfd9e7a9894/components/net/http_loader.rs#L139)):</sup>
Does this need to be mut? I'm also unclear why we can't use `let writer =` down below.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6026)

**Comment by pcwalton** [comment]
Addressed comment. r? @jdm

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- components/net/http_loader.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6026)

**Comment by pcwalton** [comment]
Unexpected Results
    ==================

    /old-tests/submission/Opera/script_scheduling/087.html
    ------------------------------------------------------
    FAIL  scheduler: multiple defer scripts, one slow loading
    /old-tests/submission/Opera/script_scheduling/105.html
    ------------------------------------------------------
    FAIL  scheduler: adding async attribute at runtime
    /old-tests/submission/Opera/script_scheduling/123.html
    ------------------------------------------------------
    FAIL scheduler: altering the type attribute and adding/removing external script with async=false 
    /old-tests/submission/Opera/script_scheduling/126.html
    ------------------------------------------------------
    FAIL scheduler: altering the type attribute and changing script data external script async=false

**Comment by seanmonstar** [comment]
I found eventually that in cases where the response was chunked, the stream wouldn't be reused. Responses with `Content-Length` would be. This has been fixed in hyper v0.6, though it has some breaking changes around using Ssl. They're not to difficult to change, just providing a OpenSSL `SslContext` instead of a `ContextVerifier`.

**Comment by metajack** [comment]
@pcwalton ping. This one is getting quite old.

**Pull request closed without merging**
