### PR TITLE
Update bitflags to 1.0 in every servo crate

### PR DESCRIPTION
**Pull request by Eijebong**
It still needs dependencies update to remove all the other bitflags
versions.

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it's a dependency update

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18809)

### CODE REVIEW

**Comment by SimonSapin** [comment]
This adds a *fifth* version of bitflags to the dependency graph. It’s not overly dramatic since bitflags itself is small, but could we try to bitflags in some external dependencies first?

**Comment by Eijebong** [comment]
Well I wanted to do this as soon as possible because it's so huge. We can wait for dependencies if you'd prefer to do so.

**Comment by SimonSapin** [comment]
Alright, since PR is large and prone to bitrot feel free to ignore me. The build fails on Travis, though. You can run `./mach test-unit` and `./mach check-geckolib` to test locally.

**Comment by Eijebong** [comment]
Yeah, I forgot to compile tests, fixing them right now

**Comment by Eijebong** [comment]
Tests are failing because firefox is still using rust 1.19

**Comment by SimonSapin** [comment]
It sounds like this is blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1396884, unfortunately.

**Comment by rillian** [comment]
I've [bumped the gecko minimum rust version to 1.20.0](https://bugzilla.mozilla.org/show_bug.cgi?id=1408567), so it should be ok to update the lint and merge this now.

**Comment by SimonSapin** [comment]
Thanks @rillian.

@Eijebong, this should be good to go once https://github.com/servo/servo/pull/18883 lands.

**Comment by SimonSapin** [comment]
@Eijebong if you rebase this PR and get it in a state that can be merged please also add a comment. GitHub doesn’t send notifications for pushes of amended commits to a PR, so nobody might notice if you only do that.

**Comment by nox** [comment]
Thanks for keeping up with that huge task.

**Comment by Eijebong** [comment]
@nox Fixed

**Pull request merged**
