### PR TITLE
Updated to v0.1.15 of string_cache.

### PR DESCRIPTION
**Pull request by asajeffrey**
Matches https://github.com/servo/string-cache/commit/145f5332901fe238b7b43961cdf34e5c253f6474.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8214)

### CODE REVIEW

**Comment by nox** [comment]
```
failed to select a version for `string_cache` (required by `script`):
all possible versions conflict with previously selected versions of `string_cache`
  version 0.1.13 in use by string_cache v0.1.13
  possible versions to select: 0.1.15
```

**Comment by nox** [comment]
Please squash everything together.

**Comment by asajeffrey** [comment]
Will do.

**Comment by mbrubeck** [comment]
Moved to #8224.

**Pull request closed without merging**
