### PR TITLE
Fire error when placeholder is loaded

### LINKED ISSUE #21397: Image loads that yield a placeholder image receive a load event instead of an error event
Running [this test](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cimg%20src%3D%22http%3A%2F%2Fwhatevertheheckawefawefawe.org%2Fimg.gif%22%20onload%3D%22w(%27load%27)%22%20onerror%3D%22w(%27error%27)%22%3E) in Firefox shows a "error" message in the log. Running it in Servo shows a "load" message instead.

### PR DESCRIPTION
**Pull request by gterzian**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #21397 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21399)

### CODE REVIEW

**Comment by jdm** [comment]
We should run this through try and add a test if no results change.

**Review by jdm — APPROVED** [review]

**Comment by gterzian** [comment]
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "document.open bailout should not have any side effects (active parser whose script nesting level is greater than 0)", "test": "/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/bailout-side-effects-synchronous-script.window.html", "line": 47791, "action": "test_result", "expected": "FAIL"```
looks like an intermittent, I'll look into writing a test...

**Comment by gterzian** [comment]
@jdm I've added a "mozilla" wpt test because I couldn't find any reference to placeholder in the spec, and I assume whether to load a placeholder or not isn't normalized. There already is a wpt test to cover the case of a non-existent image at https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/nonexistent-image.html

We were passing this test because it hits the `ImageResponse::None` branch(not due to url parsing failure by the way), so I've copy/pasted it and change the url to the one from the manual test you linked, and we indeed get a placeholder. The test was failing without the current changes...

**Review by jdm — APPROVED** [review]
Sorry for forgetting about this! This is ready to be merged after a rebase.

**Comment by gterzian** [comment]
Ok, this one has been rebased...

**Comment by jdm** [comment]
@vors-servo r+

**Pull request merged**
