### PR TITLE
stylo: Keep unshipping stuff.

### PR DESCRIPTION
**Pull request by emilio**
From bug 1396066

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18759)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo p=1

 * Coordiland

**Comment by jdm** [comment]
@bors-servo r-
Tidy failure

**Comment by emilio** [comment]
@bors-servo r=upsuper

 * I promise I'll never make any sense of how tidy treats underscores.

**Comment by emilio** [comment]
@bors-servo retry 

> command timed out: 1200 seconds without output running ['env', 'PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig', './mach', 'build', '--release'], attempting to kill

**Pull request merged**
