### PR TITLE
Measure the stylist during memory reporting.

### PR DESCRIPTION
**Pull request by nnethercote**
This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1387958

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because testing is in Gecko.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18375)

### CODE REVIEW

**Comment by chenpighead** [comment]
Looks like #18374 ... :(

**Comment by nnethercote** [comment]
If this should land while I'm offline, the Gecko-side patch is ready to autoland in https://bugzilla.mozilla.org/show_bug.cgi?id=1387958.

**Comment by emilio** [comment]
@bors-servo retry

 * Infra should be back up

**Comment by emilio** [comment]
This landed in https://github.com/servo/servo/pull/18384

**Pull request closed without merging**
