### PR TITLE
Refactors some entities from script_thread into script_runtime

### LINKED ISSUE #10271: Create a script_runtime module
`script_thread.rs` contains the implementation of the main script thread (where `Window`s/`Document`s live), as well as a number of things that are shared between that thread and web worker threads (`dedicatedworkerglobalscope.rs` and `workerglobalscope.rs`). In particular:

* `ScriptThread::new_rt_and_cx`
* `ScriptThread::get_reports`
* `ScriptChan`
* `ScriptPort`
* `StackRootTLS`
* `CommonScriptMsg`
* `ScriptThreadEventCategory`

All of those should move to a new file (`components/script/script_runtime.rs`).

### PR DESCRIPTION
**Pull request by creativcoder**
Fixes #10271.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10342)

### CODE REVIEW

**Comment by jdm** [comment]
These changes look great! Please also move the things in script_thread.rs that were made public, since they're only used by the other moved code.

**Comment by Ms2ger** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/lib.rs, line 95 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10342#-KEGxqu6BfggXbo0Kay1:-KEGxqu7mGGzDqE_b7KZ:1553037912) ([raw file](https://github.com/servo/servo/blob/8eff11abd57fe41f328cbcad262cc4a48cffe983/components/script/lib.rs#L95)):*
Let's move this to the places where it's needed instead.

---

*[components/script/script_thread.rs, line 117 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10342#-KEGz8Q05W-Emc4dQSHV:-KEGz8Q1-Z5u6IV2mJEv:1366663711) ([raw file](https://github.com/servo/servo/blob/8eff11abd57fe41f328cbcad262cc4a48cffe983/components/script/script_thread.rs#L117)):*
Let's add a static function `ScriptTask::trace_thread(tr: *mut JSTracer)` and move the `SCRIPT_THREAD_ROOT.with()` call into it. Then move `trace_rust_roots` into `script_runtime` too.

---

*[components/script/script_thread.rs, line 313 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10342#-KEGzusTEpw7JnnPDrak:-KEGzusTEpw7JnnPDral:909093962) ([raw file](https://github.com/servo/servo/blob/8eff11abd57fe41f328cbcad262cc4a48cffe983/components/script/script_thread.rs#L313)):*
Are there two of those now? Remove this one.

---

*[components/script/script_thread.rs, line 513 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10342#-KEGzRyLiD9SqQyfobGR:-KEGzRyLiD9SqQyfobGS:-1687087629) ([raw file](https://github.com/servo/servo/blob/8eff11abd57fe41f328cbcad262cc4a48cffe983/components/script/script_thread.rs#L513)):*
Move this too, along with the `thread_local`s

---

*[components/script/script_thread.rs, line 553 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10342#-KEGzVQJs5Xi-YaqEjdg:-KEGzVQJs5Xi-YaqEjdh:-499318459) ([raw file](https://github.com/servo/servo/blob/8eff11abd57fe41f328cbcad262cc4a48cffe983/components/script/script_thread.rs#L553)):*
Ditto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10342)*

**Comment by Ms2ger** [comment]
Reviewed 2 of 6 files at r2, 5 of 8 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/script_runtime.rs, line 10 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10342#-KEeOnFx1lGyFLa_0aSx:-KEeOnFx1lGyFLa_0aSy:-1775439125) ([raw file](https://github.com/servo/servo/blob/17b928465169c5c88eff500d86b839c529dbbbbf/components/script/script_runtime.rs#L10)):*
Nit: no `{}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10342)*

**Comment by Ms2ger** [comment]
@bors-servo r+

Thanks!

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10342#-:-KEeRbMfp7KtbDYYDZBI:-1544677996)*

**Pull request merged**
