### PR TITLE
Better tooltip for UWP port

### LINKED ISSUE #24721: HoloLens: keyboard shortcut tooltips are "floating" in the middle of the UI

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #24721

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Comment by jdm** [comment]
@bors-servo retry
* https://github.com/servo/servo/issues/24611

**Comment by CYBAI** [comment]
@bors-servo retry

- #24726

**Comment by jdm** [comment]
@bors-servo retry
* #24622

**Pull request merged**
