### PR TITLE
Use RootedTraceableBox for unions.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15589)

### CODE REVIEW

**Comment by jdm** [comment]
type_needs_tracing does not appear to believe that DOM interfaces need tracing, which seems incorrect?

**Comment by Ms2ger** [comment]
Those still use `Root`, for now.

**Comment by nox** [comment]
@bors-servo retry

Network issues.

**Pull request merged**
