### PR TITLE
Switch to a faster Brotli crate

### LINKED ISSUE #11933: Switch to Dropbox's crate for Brotli encoding/decoding
https://github.com/servo/servo/search?utf8=%E2%9C%93&q=brotli

https://blogs.dropbox.com/tech/2016/06/lossless-compression-with-brotli/

https://github.com/dropbox/rust-brotli

I haven't done any benchmarks; I'm ignorantly assuming the Dropbox one has better performance. Though if someone felt compelled to, they could do benchmarks. [Relevant thread about brotli-rs performance](https://github.com/ende76/brotli-rs/issues/24).

This might be a candidate for an E-Easy task.

### PR DESCRIPTION
**Pull request by johannhof**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #11933.

- [x] These changes do not require tests (I hope) because no new behavior was introduced

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12050)

### CODE REVIEW

**Comment by jdm** [comment]
There's an automated test at https://dxr.mozilla.org/servo/source/tests/wpt/mozilla/tests/mozilla/response-data-brotli.htm so we should be good to go.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by ConnorGBrewster** [comment]
Could you run `./mach cargo-update -p brotli` to change the other locations in the lockfiles? (The CEF ones did not get updated)

**Comment by johannhof** [comment]
Oh, yes, I missed that one. Updated! Thanks!

**Comment by ConnorGBrewster** [comment]
@johannhof no problem, thanks for doing this!
@bors-servo r=jdm

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11574

**Comment by larsbergstrom** [comment]
@bors-servo retry

    #11574

**Pull request merged**
