### PR TITLE
Implement most of the unsupported parameters in gl.getParameter()

### LINKED ISSUE #20536: Implement gl.getParameter(gl.BLEND_COLOR)
https://github.com/servo/servo/pull/20414 is pretty similar.

https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

### LINKED ISSUE #20537: Implement gl.getParameter(gl.COLOR_CLEAR_VALUE)
https://github.com/servo/servo/pull/20414 is pretty similar.

https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

### LINKED ISSUE #20538: Implement gl.getParameter(gl.COLOR_WRITEMASK)
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

### LINKED ISSUE #20544: Implement gl.getParameter(gl.COMPRESSED_TEXTURE_FORMATS)
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

### LINKED ISSUE #20545: Implement gl.getParameter(gl.DEPTH_RANGE)
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

### LINKED ISSUE #20546: Implement gl.getParameter(gl.GENERATE_MIPMAP_HINT)
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

### LINKED ISSUE #20548: Support MAX_FRAGMENT_UNIFORM_VECTORS and MAX_VERTEX_UNIFORM_VECTORS
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

See also #20330.

### LINKED ISSUE #20549: Implement gl.getParameter(gl.MAX_VARYING_VECTORS)
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

### LINKED ISSUE #20551: Support SCISSOR_TEST and SCISSOR_BOX
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.3
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGet.xml

### PR DESCRIPTION
**Pull request by nox**
Fixes #20536.
Fixes #20537.
Fixes #20538.
Fixes #20544.
Fixes #20545.
Fixes #20546.
Fixes #20548.
Fixes #20549.
Fixes #20551.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20771)

### CODE REVIEW

**Comment by jdm** [comment]
Does this overlap with https://github.com/servo/servo/pull/20754?

**Comment by jdm** [comment]
Android build failure that wasn't reported as a buildbot failure:
```
"/usr/local/bin/virtualenv" "-p" "/usr/bin/python2.7" "--system-site-packages" "/home/servo/buildbot/slave/android/build/python/_virtualenv" failed with error code 1:
Output:
New python executable in /home/servo/buildbot/slave/android/build/python/_virtualenv/bin/python2.7
Not overwriting existing python script /home/servo/buildbot/slave/android/build/python/_virtualenv/bin/python (you must use /home/servo/buildbot/slave/android/build/python/_virtualenv/bin/python2.7)
Running virtualenv with interpreter /usr/bin/python2.7
Error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2304, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 924, in create_environment
    download=download,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 843, in install_wheel
    cert_data = pkgutil.get_data("pip._vendor.requests", "cacert.pem")
  File "/usr/lib/python2.7/pkgutil.py", line 578, in get_data
    loader = get_loader(package)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/utils/__init__.py", line 26, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3130, in <module>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3116, in _call_aside
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 956, in subscribe
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3155, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2655, in activate
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2225, in declare_namespace
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2194, in _handle_ns
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2192, in sort_key
ValueError: '/usr/local/lib/python2.7/dist-packages' is not in list
```

**Comment by nox** [comment]
> Does this overlap with #20754?

No.

**Comment by nox** [comment]
I had not even realised that this didn't land yet…

**Pull request merged**
