### PR TITLE
Fix some issues with the WPT UI output

### LINKED ISSUE #8368: Intermittent timeout in WPT testsuite
Very little information here, unfortunately.

```
./mach test-wpt --release --processes 24 --log-raw test-wpt.log
 in dir /home/servo/buildbot/slave/linux-rel/build (timeout 1200 secs)
 watching logfiles {'test-wpt.log': 'test-wpt.log'}
 argv: ['./mach', 'test-wpt', '--release', '--processes', '24', '--log-raw', 'test-wpt.log']
 environment:
  CARGO_HOME=/home/servo/.cargo
  DISPLAY=:0
  HOME=/home/servo
  PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
  PWD=/home/servo/buildbot/slave/linux-rel/build
  RUST_BACKTRACE=1
  SERVO_CACHE_DIR=/home/servo/.servo
  SERVO_HEADLESS=1
  SHELL=/bin/bash
  TERM=linux
  UPSTART_INSTANCE=
  UPSTART_JOB=buildbot-slave
 using PTY: False
Running 3601 tests in web-platform-tests


command timed out: 1200 seconds without output running ['./mach', 'test-wpt', '--release', '--processes', '24', '--log-raw', 'test-wpt.log'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=3786.091293
```

### LINKED ISSUE #8395: WPT log formatter doesn't work on OS X
Instead of the nice always-updating behaviour, I get this output under iTerm2:
```
  [177/185] /html/semantics/embedded-content/media-elements/seeking/seek-to-negative-time.htm
            /html/semantics/embedded-content/media-elements/seeking/seek-to-max-value.htm
            /html/semantics/embedded-content/media-elements/video_volume_check.html
            /html/semantics/embedded-content/media-elements/seeking/seek-to-currentTime.html
            /html/semantics/embedded-content/media-elements/audio_loop_base.html
            /html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html
            /html/semantics/embedded-content/media-elements/video_loop_base.html
  [177/185] /html/semantics/embedded-content/media-elements/seeking/seek-to-negative-time.htm
            /html/semantics/embedded-content/media-elements/seeking/seek-to-max-value.htm
            /html/semantics/embedded-content/media-elements/video_volume_check.html
            /html/semantics/embedded-content/media-elements/seeking/seek-to-currentTime.html
            /html/semantics/embedded-content/media-elements/audio_loop_base.html
            /html/semantics/embedded-content/media-elements/volume_nonfinite.html
            /html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html
            /html/semantics/embedded-content/media-elements/video_loop_base.html
  [178/185] /html/semantics/embedded-content/media-elements/seeking/seek-to-negative-time.htm
            /html/semantics/embedded-content/media-elements/seeking/seek-to-max-value.htm
            /html/semantics/embedded-content/media-elements/seeking/seek-to-currentTime.html
            /html/semantics/embedded-content/media-elements/audio_loop_base.html
            /html/semantics/embedded-content/media-elements/volume_nonfinite.html
            /html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html
            /html/semantics/embedded-content/media-elements/video_loop_base.html
  [179/185] /html/semantics/embedded-content/media-elements/seeking/seek-to-negative-time.htm
            /html/semantics/embedded-content/media-elements/seeking/seek-to-max-value.htm
            /html/semantics/embedded-content/media-elements/seeking/seek-to-currentTime.html
            /html/semantics/embedded-content/media-elements/audio_loop_base.html
            /html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html
            /html/semantics/embedded-content/media-elements/video_loop_base.html
  [180/185] /html/semantics/embedded-content/media-elements/seeking/seek-to-negative-time.htm
            /html/semantics/embedded-content/media-elements/seeking/seek-to-max-value.htm
            /html/semantics/embedded-content/media-elements/seeking/seek-to-currentTime.html
            /html/semantics/embedded-content/media-elements/audio_loop_base.html
            /html/semantics/embedded-content/media-elements/video_loop_base.html
  [181/185] /html/semantics/embedded-content/media-elements/seeking/seek-to-negative-time.htm
            /html/semantics/embedded-content/media-elements/seeking/seek-to-max-value.htm
            /html/semantics/embedded-content/media-elements/audio_loop_base.html
            /html/semantics/embedded-content/media-elements/video_loop_base.html
  [182/185] /html/semantics/embedded-content/media-elements/seeking/seek-to-negative-time.htm
            /html/semantics/embedded-content/media-elements/audio_loop_base.html
            /html/semantics/embedded-content/media-elements/video_loop_base.html
  [183/185] /html/semantics/embedded-content/media-elements/audio_loop_base.html
            /html/semantics/embedded-content/media-elements/video_loop_base.html
  [184/185] /html/semantics/embedded-content/media-elements/video_loop_base.html
  [185/185] No tests running.
```

### PR DESCRIPTION
**Pull request by mrobinson**
When running in non-interactive mode, print test names as they are run.
This prevent timeouts on the bots, which are detected by watching for
output from the test runner.

When running in iTerm.app don't use the multi-line status line, as the
carriage return is not processed properly. Instead use a single-line
output with the last test run and then backspace characters to keep it
up to date.

Fixes #8368.
Fixes #8395.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8456)

### CODE REVIEW

**Comment by mrobinson** [comment]
@jdm or @jgraham  r?

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/wpt/grouping_formatter.py, line 28 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8456#-K2mE7URiDBpZHWgvFLL)** ([raw file](https://github.com/servo/servo/blob/75f8963d63a743cd718374f0245c36c9c66ff746/tests/wpt/grouping_formatter.py#L28)):</sup>
I'm not a super-fan of having hardcoded lists of bad terminals like this, but I don't concretely have a better suggestion, apart from trying something like blessings which might already have this kind of thing built in.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8456)

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8456)

**Pull request merged**
