### PR TITLE
Add instruction to use mach.bat for bootstrap on Windows

### PR DESCRIPTION
**Pull request by six-shot**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix the mash set for windows (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because its documentation

### CODE REVIEW

**Review by mrobinson — COMMENTED** [review]
I think it should be possible to run just `mach` on Windows. You shouldn't need to type `mach.bat`.

**Comment by six-shot** [comment]
I use windows and normal mash didn’t work for me until I added bat so I thought it would help for people who have same issues

**Comment by mrobinson** [comment]
I'm going to close this one, because I think maybe it's just due to a misconception about a build issue and also includes lots of changes that I've already reviewed in a different PR. Maybe we can continue the conversation on Zulip?

@six-shot When uploading changes, please make sure that they are based on the version of the latest code from the repository and only includes changes relevant to the fix you are trying to make.

**Comment by mrobinson** [comment]
> I use windows and normal mash didn’t work for me until I added bat so I thought it would help for people who have same issues

What terminal are you running in? Make sure that you are either running in PowerShell or Windows `cmd.exe`, but *not* in the Visual Studio terminal.

**Comment by six-shot** [comment]
Oohkay sir…I used  windows cmd.exe

**Pull request closed without merging**
