### PR TITLE
Implement setters in URLUtils

### LINKED ISSUE #6145: Null-check in location getters
Followup #6135 
Implement the null-check in https://url.spec.whatwg.org/#urlutils-and-urlutilsreadonly-members

### PR DESCRIPTION
**Pull request by nox**
This fixes #6145 and takes care of most of #4250.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7228)

### CODE REVIEW

**Comment by jdm** [comment]
@dzbarsky Would you like to review this?

**Comment by dzbarsky** [comment]
I'm gone for the next week, but I'll do it week after next if nobody else
gets to it.

**Comment by nox** [comment]
Cc'ing @SimonSapin.

**Comment by Ms2ger** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/location.rs, line 88 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7228#-Jwv7MMNEO5WSstEYMes)** ([raw file](https://github.com/servo/servo/blob/3b02c1ec061768976a4b639ab486f38afec8d0c9/components/script/dom/location.rs#L88)):</sup>
This can't throw.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7228)

**Comment by nox** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/location.rs, line 88 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7228#-Jwv7MMNEO5WSstEYMes)** ([raw file](https://github.com/servo/servo/blob/3b02c1ec061768976a4b639ab486f38afec8d0c9/components/script/dom/location.rs#L88)):</sup>
https://url.spec.whatwg.org/#dom-urlutils-href

Setter, step 2, in the URL case it can throw.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7228)

**Comment by nox** [comment]
#7412

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7228)

**Comment by jdm** [comment]
Thanks for tackling this, @nox!

**Pull request merged**
