### PR TITLE
Move width and height from Box to Position.

### PR DESCRIPTION
**Pull request by heycam**
This helps with style struct alignment between Servo and Gecko.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10999)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10999#-:-KGwpLXZu4iaJJzJAXS6:1236647940)*

**Comment by heycam** [comment]
@bors-servo retry

* #10457

**Comment by SimonSapin** [comment]
@bors-servo retry

* #10457

**Pull request merged**
