### PR TITLE
Implement 'do nothing' methods on Window and Document

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7389)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Please link to the multipage spec.

**Comment by frewsxcv** [comment]
> Please link to the multipage spec.

Done.

**Comment by frewsxcv** [comment]
Looks like a legit fail, I'll look into it later when I have some free time

```
Unexpected Results
==================

/html/dom/interfaces.html
-------------------------
PASS expected FAIL Document interface: operation clear()
PASS expected FAIL Document interface: operation captureEvents()
PASS expected FAIL Document interface: operation releaseEvents()
PASS expected FAIL Document interface: document.implementation.createDocument(null, "", null) must inherit property "clear" with the proper type (78)
PASS expected FAIL Document interface: document.implementation.createDocument(null, "", null) must inherit property "captureEvents" with the proper type (79)
PASS expected FAIL Document interface: document.implementation.createDocument(null, "", null) must inherit property "releaseEvents" with the proper type (80)
```

**Comment by nox** [comment]
@frewsxcv You just need to change the test expectations.

**Comment by frewsxcv** [comment]
Oh, you're right. I'll do that right now

**Comment by frewsxcv** [comment]
Done

**Comment by jdm** [comment]
```

/html/dom/interfaces.html
-------------------------
FAIL Document interface: iframe.contentDocument must inherit property "clear" with the proper type (78)
FAIL Document interface: iframe.contentDocument must inherit property "captureEvents" with the proper type (79)
FAIL Document interface: iframe.contentDocument must inherit property "releaseEvents" with the proper type (80)
PASS expected FAIL Document interface: document.implementation.createDocument(null, "", null) must inherit property "clear" with the proper type (78)
PASS expected FAIL Document interface: document.implementation.createDocument(null, "", null) must inherit property "captureEvents" with the proper type (79)
PASS expected FAIL Document interface: document.implementation.createDocument(null, "", null) must inherit property "releaseEvents" with the proper type (80)
```

Looks like the incorrect failures were removed.

**Comment by frewsxcv** [comment]
Yeah, woops. I'm going to actually compile/run this time around.

**Comment by frewsxcv** [comment]
Sorry about that, just ran that test locally and it should work now

**Comment by nox** [comment]
@bors-servo r+

No problem.

**Pull request merged**
