### PR TITLE
Cleaning up CalcLengthOrPercentage

### PR DESCRIPTION
**Pull request by ghost**
We don't really need enum variants in `CalcLengthOrPercentage`. Given that we already have the information (whether it's `vw`, `ch`, etc.) in the struct fields, we could just store `Option<CSSFloat>` there, and modify our `ToCss` implementation a bit.

cc #15061

r? @Manishearth or anyone interested

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] These changes do not require tests because it's a refactor

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15063)

### CODE REVIEW

**Comment by emilio** [comment]
Can you also remove the option and represent None with zero?

**Comment by heycam** [comment]
In https://drafts.csswg.org/css-values/#calc-serialize it says "(Terms with a value of zero must be preserved in this summation.)" which I think means we need to continue distinguishing zero from a value with that unit not being specified.

**Comment by Wafflespeanut** [comment]
@bors-servo r=heycam

(meh)

**Pull request merged**
