### PR TITLE
Move profiler code from `util` into a new crate `profile`.

### PR DESCRIPTION
**Pull request by nnethercote**
- Most of util::memory has been moved into profile::mem, though the
  `SizeOf` trait and related things remain in util::memory. The
  `SystemMemoryReporter` code is now in a submodule
  profile::mem::system_reporter.
- util::time has been moved entirely into profile::time.

### CODE REVIEW

**Comment by nnethercote** [comment]
This does the first half of #5283 -- it creates the new `profile` crate, but doesn't rename anything else. Creating a new crate is fiddly enough, and has enough scope for merge conflicts, that I decided to separate the two steps.

r? @jdm.

**Comment by jdm** [comment]
Looks like we'll want a profile_traits crate containing the public interfaces if we want to reap any compile-time benefits from this.

**Comment by nnethercote** [comment]
Thank you for the fast review! :)

> Looks like we'll want a profile_traits crate containing the public interfaces if we want to reap any compile-time benefits from this.

After touching components/util/memory.rs, 16 crates are rebuilt, taking ~220s. After touching components/profile/mem.rs, 11 crates are rebuilt, taking ~190s. So it's a slight improvement, but yeah, `profile_traits` would be a bigger win.

**Comment by nnethercote** [comment]
r+

**Comment by nnethercote** [comment]
@jdm, @glennw: ... and I need another r+, because I had a gonk build failure :(

Is there any way to trigger a run of bors' tests ahead of time, so I have some idea whether it will fail or succeed? Like a try server push for Gecko?

**Comment by Manishearth** [comment]
I think `@bors: try` worked once upon a time, but it's broken now (I think).

**Comment by metajack** [comment]
@Manishearth it is `@bors: retry` but it only works for someone who is a committer.

**Comment by Manishearth** [comment]
`@bors: retry` ends up merging if it passes. `try` is for testing it without a merge

**Pull request closed without merging**
