### PR TITLE
Backport several style changes from Gecko (7)

### PR DESCRIPTION
**Pull request by Loirooriol**
This continues https://github.com/servo/servo/pull/30421.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
Try runs triggered from `try.yml` are currently broken until #30647 lands.

**Comment by Loirooriol** [comment]
Try run: https://github.com/Loirooriol/servo/actions/runs/6692325327

**Comment by Loirooriol** [comment]
These are my changes: d498cf5c 0631b247 4115db92 f33af0e4 f5633510 bc97dff3 1c398398 1b92788c ed91ac4a 9339c229 099cbbcf d5d34099 31104e62

**Review by mrobinson — APPROVED** [review]
Nicely done. Once the merge queue is empty we can adjust the settings to not squash and land this.

**Comment by mrobinson** [comment]
I'm going to turn off the merge queue to merge this.

**Pull request merged**
