### PR TITLE
[WIP] Add WACK checking to Windows CI.

### LINKED ISSUE #24173: Run WACK and make sure no regression occurs
It's probably possible to run the WACK validation from the command line. The same way we build the UWP app, we should also run the WACK, to avoid regressions like [this](https://github.com/servo/servo/issues/24156).

### PR DESCRIPTION
**Pull request by jdm**
Fixes #24173.

### CODE REVIEW

**Comment by jdm** [comment]
I suspect the first hurdle in running appcert.exe is getting access to a context in which it won't trigger the warning dialog.

**Comment by jdm** [comment]
```
C:\Users\task_1595445052\repo>appcert reset 
Access is denied.
[taskcluster 2020-07-22T22:34:16.093Z]    Exit Code: 1
[taskcluster 2020-07-22T22:34:16.093Z]    User Time: 15.625ms
[taskcluster 2020-07-22T22:34:16.093Z]  Kernel Time: 31.25ms
[taskcluster 2020-07-22T22:34:16.093Z]    Wall Time: 2m2.416282s
[taskcluster 2020-07-22T22:34:16.093Z]       Result: FAILED
[taskcluster 2020-07-22T22:34:16.093Z] === Task Finished ===
[taskcluster 2020-07-22T22:34:16.093Z] Task Duration: 2m15.8067632s
```
@paulrouget When you were trying to get UWP tests working on CI, did you find a way to deal with programs that required elevated permissions?

**Comment by paulrouget** [comment]
@jdm not during a test.

```
The Windows App Certification Kit must be run in the context of an active user session but you can't launch apps in a non-interactive session. The way the kit handles tokens for running tests with or without administrative privileges depends on this user session context as well. The kit can be run from a service, but the service must be able to spawn the kit process in an active user session.
```

As far as I understand, the tests run in an interactive session. I wish there was more details about what the "user session context" needs.

**Pull request closed without merging**
