### PR TITLE
Update js.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8428)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Depends on https://github.com/servo/rust-mozjs/pull/213

**Comment by Manishearth** [comment]
Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 12 of 15 files at r3.
Review status: 17 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/script/devtools.rs, line 31 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8428#-K2n-9GVf2-NanqZZDx3)** ([raw file](https://github.com/servo/servo/blob/9e8b6441de8bc24770e68dfef7d4b7260c3fb740/components/script/devtools.rs#L31)):</sup>
Probably should have a comment here explaining why this block is safe, since it's pretty large.


---

<sup>**[components/script/dom/websocket.rs, line 573 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8428#-K2n-_wBEzp1Pirtjvm-)** ([raw file](https://github.com/servo/servo/blob/9e8b6441de8bc24770e68dfef7d4b7260c3fb740/components/script/dom/websocket.rs#L573)):</sup>
ditto


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8428)

**Comment by Ms2ger** [comment]
Depends on https://github.com/servo/rust-mozjs/pull/217

**Comment by Manishearth** [comment]
Reviewed 3 of 15 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8428)

**Comment by Ms2ger** [comment]
In both cases, the explanation is basically "because window.get_cx() returns a valid pointer".

**Comment by Manishearth** [comment]
Sure, just saying that we should leave a comment explaining why `unsafe` is okay especially in cases where there are huge unsafe blocks.

**Comment by Ms2ger** [comment]
Done.

**Comment by Manishearth** [comment]
@bors-servo r+


---

Reviewed 9 of 9 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8428)

**Comment by Manishearth** [comment]
@bors-servo retry

Not a known failure

```
  ▶ FAIL [expected PASS] /css21_dev/html4/background-root-101.htm
  └   → /css21_dev/html4/background-root-101.htm bd645f458de9645a6cd7eef158c95f4114664277
/css21_dev/html4/reference/background-root-101-ref.htm 761d59fc719a654e337e61be9844883a919ce098
Testing bd645f458de9645a6cd7eef158c95f4114664277 == 761d59fc719a654e337e61be9844883a919ce098
```

**Comment by jdm** [comment]
@bors-servo: retry
* #8486

**Comment by jdm** [comment]
@bors-servo: retry
* #8486

**Comment by jdm** [comment]
@bors-servo: retry
* #8486

**Comment by jdm** [comment]
@bors-servo: retry
* #8486

**Comment by jdm** [comment]
@bors-servo: retry
* #8486

**Comment by jdm** [comment]
@bors-servo: retry
* #8416

**Pull request merged**
