### PR TITLE
Remove redundant RefCell from CanvasState struct

### LINKED ISSUE #23436: Remove Cell/DomRefCell member wrappers from CanvasState struct
CanvasState was introduced as part of a big refactor in #23381 that extracted common aspects of the offscreen canvas rendering context and the 2d canvas rendering context. Since the CanvasState struct is stored inside of a DomRefCell itself, that means that we can modify the methods for CanvasState to accept `&self` or `&mut self` directly, so the Cell and DomRefCell members inside of CanvasState are redundant and can be removed.

Code: `components/script/dom/canvasrenderingcontext2d.rs`

To verify that everything behaves the same after changing the code, run `./mach test-wpt tests/wpt/web-platform-tests/2dcontext/ tests/wpt/web-platform-tests/offscreen-canvas`.

### PR DESCRIPTION
**Pull request by chansuke**
Removed DomRefCell member wrappers from CanvasState.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23436 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it only fixed redundancy.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23730)

### CODE REVIEW

**Comment by CYBAI** [comment]
<details>
<summary>Failures in `linux-rel-css`</summary>

```
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.case.html", 
    "line": 38867, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.unrecognised.html", 
    "line": 39584, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.nullsuffix.html", 
    "line": 40139, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.null.html", 
    "line": 40622, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/embedded-content/the-canvas-element/initial.reset.pattern.html", 
    "line": 106360, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.changed.html", 
    "line": 151463, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.unrecognisednull.html", 
    "line": 152146, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.undefined.html", 
    "line": 173173, 
    "action": "test_result", 
    "expected": "OK"
}
```

</details>

**Comment by chansuke** [comment]
@CYBAI Thanks for your comment. How can I debug the error of `linux-rel-css` in my local env?

**Comment by CYBAI** [comment]
I think you can try to run these tests locally with `./mach test-wpt`.

**Comment by jdm** [comment]
Specifically `./mach test-wpt /2dcontext/fill-and-stroke-styles/2d.pattern.repeat.case.html` will run one failing test and show the output in the terminal.

**Comment by chansuke** [comment]
Sorry for taking time, the error says `DomRefCell<T> already borrowed:` so I at first tried to change `this.canvas_state.borrow()` ⇒ `this.canvas_state.borrow()` in `canvasrenderingcontext2` and `offscreencanvasrenderingcontext2d` but could not get rid of the error, and am stacking right now.

**Comment by gterzian** [comment]
@chansuke since you transform some `borrow` into `borrow_mut`, and a `borrow` can be followed by another `borrow` but not a `borrow_mut`, it must be that some where where you introduced a `borrow_mut`, that which is borrowed mutably is already borrow immutably. Previously, the borrow was followed by another borrow, and now it's changed to a mutable borrow, hence the panic. 

I can't tell why one it is though...

**Comment by jdm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
