### PR TITLE
Enable HTTP connection pooling

### PR DESCRIPTION
**Pull request by jdm**
Rebased and adjusted version of #6948. Closes #6948.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7418)

### CODE REVIEW

**Comment by jdm** [comment]
This is going to fail because I forgot to update XMLHttpRequest/response-method.htm.ini . That being said, the tests that are now passing make me suspect that something is weird in our non-pooling code, because I can't figure out why they would fail.

**Comment by jdm** [comment]
Actually I bet that one is https://github.com/hyperium/hyper/commit/31f117ea08c01889016fd45e7084e9a049c53f7a#diff-913a0c0dbdad7f268ff826d6af8c19abR166

**Comment by jdm** [comment]
```
/css21_dev/html4/background-color-075.htm
-----------------------------------------
TIMEOUT [Parent]
```
```
 1:02.98 TEST_START: Thread-TestrunnerManager-35 /css21_dev/html4/background-color-075.htm
 1:03.19 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) Full command: /home/servo/buildbot/slave/linux2/build/target/release/servo --cpu --hard-fail --exit -u Servo/wptrunner -Z disable-text-aa --output=/tmp/tmpRp06Iu/a6fe72d9-a29b-40e3-88c5-e4dac2995b9f http://localhost:8000/css21_dev/html4/background-color-075.htm --user-stylesheet /home/servo/buildbot/slave/linux2/build/resources/ahem.css
(pid:27586) "thread 'http_loader' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:732"
 1:03.19 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "stack backtrace:"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   1:     0x7f645f4335c9 - sys::backtrace::write::h29675241e432c301Pws"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   2:     0x7f645f436eb9 - panicking::on_panic::h1e1c334783ff2a38jzx"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   3:     0x7f645f4247fe - rt::unwind::begin_unwind_inner::hb529041d76c2c802L1w"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   4:     0x7f645f425111 - rt::unwind::begin_unwind_fmt::h027d2621615b5dcfR0w"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   5:     0x7f645f4368b1 - rust_begin_unwind"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   6:     0x7f645f466a7f - panicking::panic_fmt::ha8483564b9ba8c9c47D"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   7:     0x7f645e8425c9 - http_loader::load::h19ac6a5bc624e6cfdpa"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   8:     0x7f645e83d504 - boxed::F.FnBox<A>::call_box::h11481485006043150976"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "   9:     0x7f645e837244 - rt::unwind::try::try_fn::h12677946051234551213"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  10:     0x7f645f436858 - __rust_try"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  11:     0x7f645f4314c2 - rt::unwind::try::inner_try::hbf179233f048e0c1EXw"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  12:     0x7f645e8373de - boxed::F.FnBox<A>::call_box::h3081112056388942627"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  13:     0x7f645f435c43 - sys::thread::Thread::new::thread_start::hb07a6549e7b84f0f46v"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  14:     0x7f645cdca181 - start_thread"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  15:     0x7f645d8ff47c - __clone"
 1:03.47 PROCESS_OUTPUT: Thread-TestrunnerManager-35 (pid:27586) "  16:                0x0 - <unknown>"
```

**Comment by seanmonstar** [comment]
@jdm there's several `unwrap`s in that function :(

**Comment by seanmonstar** [comment]
```
99:        Ok(p) => p.send(Done(Err(err))).unwrap(),
156:        let inner_url = load_data.url.non_relative_scheme_data().unwrap();
157:        doc_url = Url::parse(inner_url).unwrap();
173:        if &*url.scheme != "https" && request_must_be_secured(&hsts_list.lock().unwrap(), &url) {
218:                    let load_data = LoadData::new(Url::from_file_path(&*image).unwrap(), None);
231:                hostname: doc_url.serialize_host().unwrap(),
260:            let (tx, rx) = ipc::channel().unwrap();
263:                                                                CookieSource::HTTP)).unwrap();
265:            if let Some(cookie_list) = rx.recv().unwrap() {
325:                                                                 net_event))).unwrap();
357:                                                                        CookieSource::HTTP)).unwrap();
379:                    ).unwrap();
469:                                                             net_event_response))).unwrap();
```

These are all the unwraps that could happen in the `load` function. They're either: 

- Url serialization
- ipc channel creation
- a mutex lock of hsts_list
- channel send() and recv().

**Comment by jdm** [comment]
Unless we happen to be calling something that's inlined and unwrapping :/

**Comment by seanmonstar** [comment]
Took a while for me to realize, but its a `Result<_, ()>`, so what uses `()` as an error?

**Comment by seanmonstar** [comment]
Hyper doesn't ever use that as an error type, and I don't think Url does either. Mutex doesn't. Looking at [ipc-channel](https://github.com/pcwalton/ipc-channel/blob/master/ipc.rs), I see its the error type of both channel creation and sending and recving.

**Comment by jdm** [comment]
@bors-servo: retry
* lost the logs when fiddling with buildbot

**Comment by seanmonstar** [comment]
Well, a different error. This time, looks like ToSocketAddrs failed.

**Comment by jdm** [comment]
Why do you say that? All I see is 
```
POST
----
Expected PASS, got FAIL
A network error occurred.
```

**Comment by seanmonstar** [comment]
My bad, I saw just further down an IoError about looking up an address, and wrongly assumed they were the same error.

**Comment by seanmonstar** [comment]
@jdm I'm at a loss as to what the appropriate behavior is. 

- In this [log from the buildbot](https://gist.github.com/jdm/7752b263ea8c45aaec9f#file-gistfile1-txt-L342-L348), you can see that the bytes are read in small pieces from the socket, until it gets to 136 bytes, which is enough to parse the message head. If it had read the last 4 bytes (to 140), those bytes would have been in the `BufReader` and not on the wire, and they would have been dropped on the floor just like in Gecko.
- In the [Gecko logs](https://gist.github.com/jdm/a35d8e3e139b69d8f181#file-gecko-log-L8278-L8284), you can see that 140 bytes were read in a single go.
- When I make a specific test file in hyper that runs these 3 methods against `https://w3c-test.org/XMLHttpRequest/response-method.htm`, I see 2 reads: 1 for 17  bytes (the request line), and then one more that brings us to 140, which leads to same behavior as Gecko.

-------

Since it seems that it works out nicely if enough bytes are read, I'm left wondering what would Gecko do **if it instead only read 136 bytes** before hitting `EWOULDBLOCK`, and than tried parsing the content. My hunch is that it would do the same as hyper: it would see the full headers, and the double line endings, and since it's a response to a HEAD request, it would finish up right there, and return the connection to the pool.

If it did that, it would then have those 4 bytes ready to read from the socket at the next request. If so, I wonder if that would trigger Gecko's request retry strategy. I don't know for certain, but it seems to be described [here](http://mxr.mozilla.org/mozilla-central/source/netwerk/protocol/http/nsHttpTransaction.cpp#910).

**Comment by jdm** [comment]
Should we try to read Content-Length bytes from the socket just in case?

**Comment by seanmonstar** [comment]
The [spec claims](https://tools.ietf.org/html/rfc7230#section-3.3.2):

> A server MAY send a Content-Length header field in a response to a
   HEAD request (Section 4.3.2 of [RFC7231]); a server MUST NOT send
   Content-Length in such a response unless its field-value equals the
   decimal number of octets that would have been sent in the payload
   body of a response if the same request had used the GET method.

So, semantically, any additional bytes *should* be part of a different response.

Also, while hyper still uses blocking IO, a read (such as `res.read(&mut [0u8; 4])`) could block for a long time if there *wasn't* any additional body to the HEAD response.

**Comment by jgraham** [comment]
I think expecting all servers to follow the correct behaviour here is unreasonably optimistic. I might be tempted to always close the connection after a HEAD request.

**Comment by jdm** [comment]
The Gecko folks pointed me at https://mxr.mozilla.org/mozilla-central/source/netwerk/protocol/http/nsHttpTransaction.cpp#1427 too.

**Comment by seanmonstar** [comment]
@jdm just published v0.6.12 of hyper that includes [a commit to handle invalid response bodies similar to Gecko](https://github.com/hyperium/hyper/commit/75c71170206db3119d9b298ea5cf3ee860803124).

**Comment by jdm** [comment]
@bors-servo: r+
Nth time is the charm!

**Comment by jdm** [comment]
```
/old-tests/submission/Opera/script_scheduling/087.html
------------------------------------------------------
FAIL  scheduler: multiple defer scripts, one slow loading
```
It's almost like this is complicated stuff that's tickling complicated tests!

**Comment by seanmonstar** [comment]
I feel like we went in a big circle: that's the original failing test of this PR!

**Comment by seanmonstar** [comment]
```
(pid:39073) "ERROR:script::dom::htmlscriptelement: error loading script os error"
```

**Comment by jdm** [comment]
Full hyper log at https://gist.github.com/jdm/e957e003606408f9550f

**Comment by jdm** [comment]
I assume the problem comes from
```
 0:03.87 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:36440) "INFO:net::http_loader: got HTTP response 200 OK, headers:"
 0:03.87 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:36440) "INFO:net::http_loader:  - Date: Wed, 02 Sep 2015 14:20:50 GMT"
 0:03.87 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:36440) "INFO:net::http_loader:  - Content-Type: text/javascript"
 0:03.87 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:36440) "INFO:net::http_loader:  - Server: BaseHTTP/0.3 Python/2.7.9"
 0:05.87 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:36440) "TRACE:hyper::http::h1: eofread: Ok(26)"
 0:05.87 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:36440) "TRACE:hyper::http::h1: eofread: Ok(0)"
 0:05.87 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:36440) "TRACE:hyper::client::response: Response.drop is_drained=true"
```
since include-1.js is coming through a delayed pipe in the test.

**Comment by seanmonstar** [comment]
Ah, the shame. I didn't notice that `EofReader` by definition means that the connection will be closed at the end. I've published v0.6.13 that should properly handle this.

**Pull request merged**
