### PR TITLE
Webgl blend func tests

### PR DESCRIPTION
**Pull request by ioctaptceb**
Add a function that validates the conditions for [Constant Color Blend](https://www.khronos.org/registry/webgl/specs/latest/1.0/#CONSTANT_COLOR_BLEND) in the WebGL specs. ./mach run -r tests/wpt/web-platform-tests/webgl/conformance-1.0.3/conformance/misc/webgl-specific.html

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14924)

### CODE REVIEW

**Comment by emilio** [comment]
@anholt, do you want to review this one? (No worries if you're busy, I can do it if that's the case)

Thanks for the PR @ioctaptceb! :)

**Comment by emilio** [comment]
Tidy is complaining:

```
./components/script/dom/webglrenderingcontext.rs:112: missing space after ,
```

**Comment by ioctaptceb** [comment]
Hi!, after reading the travis log, I am a little confused about what is currently failing... suggestions appreciated! @emilio 

Here is what I got from the travis build: 

`./mach build-geckolib` fails due to
```
LLVM ERROR: IO failure on output stream.
error: Could not compile `geckoservo`.
```

`./mach test-stylo` fails due to 
```
error: An unknown error occurred
```

`bash etc/ci/manifest_changed.sh` exits with a 1

I ran all of these locally and had no failures, but I am not clear about the environment variables that were set for this second travis test. There is a environment variable set with the path to ccache, I installed it and tried running again but didn't get the same result. I think I am missing something very simple as I didn't change much, let me know where I should look.

thanks!

**Comment by Ms2ger** [comment]
Feel free to ignore travis failures; if there's a problem, homu will tell you. You should, however, squash your commits into one.

**Comment by ioctaptceb** [comment]
Updated! I was also told something about running and updating all the tests so that there is no regression. the command was something along the lines of `./mach test-wpt --release tests/wpt/web-platform-tests/webgl --low-raw wpt-with-my-fix;` I... do not fully understand what this command is doing. Is this important? How do I run this correctly (I am assuming the 'with-my-fix' should be replaced but I am not sure what the naming scheme is like here)

**Comment by Ms2ger** [comment]
I've asked homu to try running the tests, so it should let us know if they pass; I don't think there's a need right now to run the tests locally.

**Comment by jdm** [comment]
@ioctaptceb That command creates a log file named `with-my-wpt-fix`, which can then be used to update the expected test results via `./mach update-wpt with-my-wpt-fix`.

**Comment by jdm** [comment]
All of the test runs on the builders did not show any changes to the the results of the webgl tests, though, which is interesting.

**Pull request merged**
