### PR TITLE
Mediadevices.enumeratedevices

### LINKED ISSUE #26877: Implement MediaDevices.enumerateDevices
This is used by hubs: https://github.com/servo/hubs/blob/7e9a9c0d9343704d6e37aafd0311cc501e6775e9/src/react-components/ui-root.js#L106-L109

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #26877

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
we should do the "running in parallel" but, btu aside from that, r=me

**Comment by ferjm** [comment]
@bors-servo retry

#25237

**Pull request merged**
