### PR TITLE
Add WebDriver support for getting elements by selector.

### PR DESCRIPTION
**Pull request by jgraham**
Also adds example support for getting the name and text properties of the elements.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5969)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/script/script_task.rs @ r1
- components/script/webdriver_handlers.rs @ r1
- components/webdriver_server/lib.rs @ r1
- components/webdriver_traits/lib.rs @ r1

---

<sup>**[components/script/webdriver_handlers.rs, line 28 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofFXewxkngLnebznzR)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/script/webdriver_handlers.rs#L28)):</sup>
nit: no need for `: JSRef<Node>`.

---

<sup>**[components/script/webdriver_handlers.rs, line 42 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofFi3XpjB3HwJtxXIX)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/script/webdriver_handlers.rs#L42)):</sup>
Let's make get_unique_id always initialize the unique id if it isn't set yet, instead.

---

<sup>**[components/script/webdriver_handlers.rs, line 105 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofGg8BqKt7HNVyJSn4)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/script/webdriver_handlers.rs#L105)):</sup>
unwrap_or("".to_owned())

---

<sup>**[components/script/webdriver_handlers.rs, line 115 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofGlALSJ2XDfai0wNn)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/script/webdriver_handlers.rs#L115)):</sup>
nit: no need for `: JSRef<Element>`

---

<sup>**[components/webdriver_server/lib.rs, line 162 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofH7U5yRz9tRrOFZeq)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/webdriver_server/lib.rs#L162)):</sup>
Let's move the command into a separate binding; this is a pretty long line.

---

<sup>**[components/webdriver_server/lib.rs, line 183 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofHFaaLxy624QgNuM5)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/webdriver_server/lib.rs#L183)):</sup>
Same here.

---

<sup>**[components/webdriver_server/lib.rs, line 186 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofHIyElXKorIMaoItV)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/webdriver_server/lib.rs#L186)):</sup>
If you use into_iter() you don't need `x.clone()`.

---

<sup>**[components/webdriver_server/lib.rs, line 201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofHPL4MRpOF1WA1nPm)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/webdriver_server/lib.rs#L201)):</sup>
Long line, separate binding.

---

<sup>**[components/webdriver_server/lib.rs, line 215 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofHSXVzrzJCIARIoWE)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/webdriver_server/lib.rs#L215)):</sup>
Long line; separate binding.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5969)

**Comment by jgraham** [comment]
<sup>**[components/script/webdriver_handlers.rs, line 105 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5969#-JofGg8BqKt7HNVyJSn4)** ([raw file](https://github.com/servo/servo/blob/90af46664c57842f72da656ba64f9fd5f7da83da/components/script/webdriver_handlers.rs#L105)):</sup>
It's not supposed to be possible to select non-Elements through the API, but I guess this can't hurt.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5969)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 

---

Reviewed files:
- components/script/dom/node.rs @ r2
- components/script/webdriver_handlers.rs @ r2
- components/webdriver_server/lib.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5969)

**Pull request merged**
