### PR TITLE
Add a dummy implementation of contentEditable

### PR DESCRIPTION
**Pull request by asajeffrey**
Add a dummy implementation of `contentEditable`.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because the existing wpt tests should do

### CODE REVIEW

**Comment by asajeffrey** [comment]
This is still a draft, as I expect the test expectations to change. @bors-servo try=wpt

**Comment by asajeffrey** [comment]
This is a teeny tiny step towards https://github.com/servo/servo/issues/12776.

Hopefully it'll fix https://github.com/servo/servo/issues/26252.

**Comment by asajeffrey** [comment]
It does seem to fix #26252, yay I can do slide presentations in servo.

**Comment by asajeffrey** [comment]
Ah, just some FAILs that are now PASS.

**Comment by jdm** [comment]
@bors-servo retry
* #25875 #25513

**Comment by CYBAI** [comment]
@bors-servo retry

- #25513

**Comment by jdm** [comment]
@bors-servo retry
* #25513

**Pull request merged**
