### PR TITLE
Hoist the rest of css/matching.rs (and its dependencies) into style/.

### PR DESCRIPTION
**Pull request by bholley**
Slowly but surely.

This goes on top of #9103.

Fixes #9103.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9110)

### CODE REVIEW

**Comment by SimonSapin** [comment]
> after #9103 

GitHub and Reviweable don’t deal very well with PRs based on top of another opened before the base one is merged. I’ll review both sets of changes in this PR if that’s ok with you.

**Comment by SimonSapin** [comment]
Looks good. Feel free to land after a rebase if conflicts don’t seem too significant.

@bors-servo delegate+

---

Reviewed 4 of 4 files at r1, 7 of 7 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 11 of 11 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9110#-:-K7Bp7TqkKxOk3x1UvM-:1069264136)*

**Comment by bholley** [comment]
@SimonSapin thanks!

@bors-servo r=SimonSapin

**Pull request merged**
