### PR TITLE
Upgrade to rustc 1.39.0-nightly (f7af19c27 2019-08-15)

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23984)

### CODE REVIEW

**Comment by jdm** [comment]
Needs a `mach fmt`.

**Review by jdm — APPROVED** [review]

**Comment by SimonSapin** [comment]
I’ve pushed a commit that should fix the Android build failure, but I’m a bit stumped by the Windows one:

```
DEBUG: Executing: `c:/Users/task_1566024117/.rustup/toolchains/nightly-2019-08-16-x86_64-pc-windows-msvc/bin/rustc.exe --crate-type staticlib --target=aarch64-uwp-windows-msvc -o 'c:\users\ta211f~1\appdata\local\temp\conftest9hia1p.rlib' 'c:\users\ta211f~1\appdata\local\temp\conftestp0xem_.rs'`
DEBUG: The command returned non-zero exit status 1.
DEBUG: Its error output was:
DEBUG: | error[E0463]: can't find crate for `std`
DEBUG: |   |
DEBUG: |   = note: the `aarch64-uwp-windows-msvc` target may not be installed
DEBUG: | 
DEBUG: | error: aborting due to previous error
DEBUG: | 
DEBUG: | For more information about this error, try `rustc --explain E0463`.
ERROR: Cannot compile for aarch64-windows-mingw32 with c:/Users/task_1566024117/.rustup/toolchains/nightly-2019-08-16-x86_64-pc-windows-msvc/bin/rustc.exe
The target may be unsupported, or you may not have
a rust std library for that target installed. Try:
  rustup target add aarch64-uwp-windows-msvc
```

According to https://forge.rust-lang.org/platform-support.html there is no `aarch64-uwp-windows-msvc` target. Earlier in the log, the `rust-std` component installed by mach is `aarch64-pc-windows-msvc`.

@jdm, any idea?

**Comment by SimonSapin** [comment]
I’ve also filed https://github.com/rust-lang/rust-forge/issues/247.

**Comment by jdm** [comment]
The error comes from the mozjs built in the rust configuration checks. I suspect I know what's happening, and I'll try and write a patch to work around it today.

**Comment by SimonSapin** [comment]
```
error: failed to run custom build command for `mozjs_sys v0.67.0 (https://github.com/jdm/mozjs.git?branch=uwp-fix#c3dbddf4)`
```
[…]
```
ERROR: Don't know how to translate aarch64-windows-mingw32 for rustc
```

**Comment by jdm** [comment]
Once https://github.com/servo/mozjs/pull/195 is merged and we update https://github.com/servo/rust-mozjs to use the new revision then we can merge this.

**Comment by jdm** [comment]
Now that https://github.com/servo/rust-mozjs/pull/468 has merged, the extra commit in this PR can be replaced with one that upgrades rust-mozjs and this should be ready to merge.

**Comment by SimonSapin** [comment]
The GitHub Status update seems to have gotten lost.

@bors-servo r=jdm

**Comment by jdm** [comment]
@bors-servo r-
A bunch of build errors in jniapi.

**Comment by SimonSapin** [comment]
Do you mean those in the tasks started ~6 hours ago? I fixed those in the current commit.

**Comment by jdm** [comment]
Oh, sorry.
@bors-servo r+

**Comment by jdm** [comment]
Needs a `mach fmt`.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Pull request merged**
