### PR TITLE
Replace Servo DL items with WR ones

### PR DESCRIPTION
**Pull request by pyfisch**
The Servo internal display list items are already pretty much
equivalent to the WebRender ones. Except that Servo items contain
base information and associated glyphs and gradient stops which are
stored implicitly in WebRender. Remove the display items for
rectangles, text, images, border, gradients and box shadow and
replace them with their WebRender counter parts.

Some more internal items like line, text shadow and iframe can definitively be replaced with WebRender equivalents but I think the PR is already quite huge. If WebRender would expose a quite minimal API which allowed servo to directly push items onto the display list most of webrender_helpers boilerplate code could go away. As WebRender performs normalization of gradients this would need to be called by servo explicitly in this case.

It should be noted that gradient borders don't actually work neither with the old version nor with this PR as the measurements are all set to zero.

Part of #19676

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21348)

### CODE REVIEW

**Comment by pyfisch** [comment]
sccache: error : No space left on device (os error 28)

**Comment by pyfisch** [comment]
I think highfive should have removed the tests-failed label?

Are there any major issues remaining with the PR?

**Comment by pyfisch** [comment]
r? @emilio

Can you please review the PR?

**Comment by jdm** [comment]
@bors-servo r+
Thanks for doing this work!

**Comment by jdm** [comment]
@bors-servo retry
* #20734

**Pull request merged**
