### PR TITLE
Support for webxr layer management

### PR DESCRIPTION
**Pull request by asajeffrey**
This adds layer management to servo's webxr implementation, and removes all the special-cased code for openxr surface creation and opaque framebuffers.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it's all back-end plumbing

### CODE REVIEW

**Comment by asajeffrey** [comment]
Note: this is still a draft because it depends on https://github.com/servo/webxr/pull/176

**Review by Manishearth — APPROVED** [review]
Script side seems okay, i'm not so clear on the webgl side though

**Comment by asajeffrey** [comment]
@jdm ok'd landing this at https://chat.mozilla.org/#/room/#servo:mozilla.org/$hp8mucO869VdIFPbYkZQDhwkcYkqBXbYKhwktno1XUw

@bors-servo r=Manishearth

**Comment by asajeffrey** [comment]
Hmm, so the windows failure is #26895 but the macOS failures look like genuine errors with WebGL in WebXR, e.g. https://community-tc.services.mozilla.com/tasks/bIxuL7ubTYS69siWmOpkmQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FbIxuL7ubTYS69siWmOpkmQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Ffiltered-wpt-errorsummary.log is
```
  ▶ CRASH [expected ERROR] /webxr/gamepads-module/xrInputSource_gamepad_input_registered.https.html
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ [2020-06-27T16:48:41Z ERROR canvas::webgl_thread] Last GL operation failed: BindTexture(3553, Some(WebGLTextureId(3)))
  │ Unexpected WebGL error: 0x502 (1282) [BindTexture(3553, Some(WebGLTextureId(3)))] (thread WebGL thread, at components/canvas/webgl_thread.rs:2229)
  │    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  │    1: core::fmt::write
  │    2: std::io::Write::write_fmt
  │    3: servo::backtrace::print
  │    4: servo::main::{{closure}}
  │    5: std::panicking::rust_panic_with_hook
  │    6: _rust_begin_unwind
  │    7: std::panicking::begin_panic_fmt
  │    8: canvas::webgl_thread::WebGLImpl::apply
  │    9: canvas::webgl_thread::WebGLThread::handle_msg
  │   10: canvas::webgl_thread::WebGLThread::process
  │   11: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   13: std::sys::unix::thread::Thread::new::thread_start
  │   14: __pthread_body
  │   15: __pthread_start
```

**Comment by asajeffrey** [comment]
Running that test 100 times on linux it doesn't fail, so it is a macOS-specific issue. Sigh.

**Comment by asajeffrey** [comment]
So that was caused by macOS having the texture target `TEXTURE_RECTANGLE` rather than `TEXTURE_2D`.

@bors-servo r=Manishearth

**Comment by asajeffrey** [comment]
Rebased. @bors-servo r=Manishearth

**Comment by asajeffrey** [comment]
Hmm, another macOS WebGL error...
```
 ▶ CRASH [expected OK] /webxr/xrWebGLLayer_framebuffer_draw.https.html
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ [2020-06-27T21:42:09Z ERROR canvas::webgl_thread] Last GL operation failed: Clear(16384)
  │ Unexpected WebGL error: 0x506 (1286) [Clear(16384)] (thread WebGL thread, at components/canvas/webgl_thread.rs:2229)
  │    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  │    1: core::fmt::write
  │    2: std::io::Write::write_fmt
  │    3: servo::backtrace::print
  │    4: servo::main::{{closure}}
  │    5: std::panicking::rust_panic_with_hook
  │    6: _rust_begin_unwind
  │    7: std::panicking::begin_panic_fmt
  │    8: canvas::webgl_thread::WebGLImpl::apply
  │    9: canvas::webgl_thread::WebGLThread::handle_msg
  │   10: canvas::webgl_thread::WebGLThread::process
  │   11: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   13: std::sys::unix::thread::Thread::new::thread_start
  │   14: __pthread_body
  │   15: __pthread_start
```

**Comment by asajeffrey** [comment]
So that one was caused by WebGL not supporting `TEXTURE_RECTANGLE` so we need to do bind the texture to the opaque framebuffer without error checking.

@bors-servo r=Manishearth

**Comment by jdm** [comment]
Looks like it's just missing a `mach fmt` now; the reftests failures are just #23290.

**Comment by asajeffrey** [comment]
Ran mach fmt. @bors-servo r=Manishearth

**Pull request merged**
