### PR TITLE
Update servo.icns icon

### LINKED ISSUE #27775: while downloading the nightly-build servo of macOS, it still uses the older logo, not the newer one.
Screen Shot 2020-11-18 at 9 25 06 AM

### PR DESCRIPTION
**Pull request by atouchet**
Update .icns icon file. I do not have a Mac so I would appreciate if someone who has one could test this out and make sure it actually fixes the issue.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [x] These changes fix #27775

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by twilco** [comment]
I just tested this downloading via https://servo.org/#download and it doesn't appear to be fixed.

Screen Shot 2020-11-22 at 12 21 27 PM

**Comment by atouchet** [comment]
This hasn't been merged so it won't show up in the nightly builds yet.

**Comment by twilco** [comment]
...*facepalm*

I just actually tested this change with `./mach package` and confirm the icon is correct now 🙂 

Screen Shot 2020-11-22 at 2 57 16 PM

**Pull request merged**
