### PR TITLE
Add the requesting URL to the 401 prompt. Only show the 401 prompt wh…

### LINKED ISSUE #10912: Loading nytimes.com results in username/password prompt
untitled

### PR DESCRIPTION
**Pull request by jdm**
…en the WWW-Authenticate header is present.

Fixes #10912.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10932)

### CODE REVIEW

**Comment by frewsxcv** [comment]
How difficult would a regression test be?

**Comment by jdm** [comment]
A unit test would be very easy.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10932#-:-KGwolXRxxvr1qM17eqK:1236647940)*

**Pull request merged**
