### PR TITLE
tidy check for vim and emacs modelines

### PR DESCRIPTION
**Pull request by zbynekwinkler**
See #10719.

It skips *.webidl files for now since I am not sure where they come from and if they should be edited in tree or not.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10786)

### CODE REVIEW

**Comment by Manishearth** [comment]
Editing webidl in-tree for stuff like this is fine.

**Comment by Manishearth** [comment]
r=me with the webidl check removed

**Comment by Wafflespeanut** [comment]
Careful. @edunham had already done that in #10723

**Comment by Manishearth** [comment]
Yeah, but that didn't add a tidy check

**Comment by Wafflespeanut** [comment]
Oh, right. I misunderstood

**Comment by zwn** [comment]
I've added the modelines removal commit before the tidy check addition.

**Comment by Manishearth** [comment]
Could you keep attribution for that commit? Thanks.

(Or, we can just land that one first)

**Comment by zwn** [comment]
Oh, I see the edits of wpt were taken out of that PR so it can be landed. I didn't notice.
So feel free to land #10723 first. I can always delete it from here.

**Comment by Wafflespeanut** [comment]
#10723 has landed

**Comment by jdm** [comment]
@bors-servo: retry
#10473

**Pull request merged**
