### PR TITLE
Remove `get_` prefix on getters

### PR DESCRIPTION
**Pull request by frewsxcv**
Part of #6224

I certainly didn't remove all of them; I avoided `unsafe` areas and also `components/script`

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6230)

### CODE REVIEW

**Comment by nox** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.
Reviewed files:
- components/compositing/compositor.rs @ r1
- components/compositing/compositor_layer.rs @ r1
- components/compositing/compositor_task.rs @ r1
- components/devtools/actor.rs @ r1
- components/devtools/actors/network_event.rs @ r1
- components/devtools/actors/timeline.rs @ r1
- components/devtools/lib.rs @ r1
- components/gfx/font.rs @ r1
- components/gfx/font_context.rs @ r1
- components/gfx/paint_context.rs @ r1
- components/gfx/paint_task.rs @ r1
- components/gfx/platform/freetype/font.rs @ r1
- components/gfx/platform/macos/font.rs @ r1
- components/gfx/text/text_run.rs @ r1
- components/layout/construct.rs @ r1
- components/layout/fragment.rs @ r1
- components/layout/wrapper.rs @ r1
- components/msg/compositor_msg.rs @ r1
- components/net/fetch/cors_cache.rs @ r1
- components/script/clipboard_provider.rs @ r1
- components/script/textinput.rs @ r1

---

<sup>**[components/compositing/compositor.rs, line 498 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6230#-JqkYexoWJeI7_1PTAY6)** ([raw file](https://github.com/servo/servo/blob/c63fc4dc13a23cf5b9f8c0972111b3f9436d2143/components/compositing/compositor.rs#L498)):</sup>
That's not exactly a plain old getter (it takes a PipelineId argument), should it really be renamed like this?

---

<sup>**[components/gfx/font.rs, line 44 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6230#-JqkalgXTyLJmR5pwVd-)** ([raw file](https://github.com/servo/servo/blob/c63fc4dc13a23cf5b9f8c0972111b3f9436d2143/components/gfx/font.rs#L44)):</sup>
Maybe use a "compute_" prefix given the implementations are quite complex and do, well, computations?

---

<sup>**[components/gfx/paint_context.rs, line 681 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6230#-Jqk_lsvMYgIOqG3AliI)** ([raw file](https://github.com/servo/servo/blob/c63fc4dc13a23cf5b9f8c0972111b3f9436d2143/components/gfx/paint_context.rs#L681)):</sup>
This method has many arguments, is that really a getter? Should we instead use another verb instead of just stripping the verb? There are many methods in Servo using "compute_" as a prefix, and this one looks like it could use it.

---

<sup>**[components/gfx/platform/freetype/font.rs, line 279 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6230#-JqkaEQlZC5-pM0IIbxf)** ([raw file](https://github.com/servo/servo/blob/c63fc4dc13a23cf5b9f8c0972111b3f9436d2143/components/gfx/platform/freetype/font.rs#L279)):</sup>
face_rec_mut() maybe?

---

<sup>**[components/layout/construct.rs, line 1478 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6230#-JqkaXHpbX2allbA3JIJ)** ([raw file](https://github.com/servo/servo/blob/0ddc6df7ff00e9e7ce0e3811b766a23aeafb0859/components/layout/construct.rs#L1478)):</sup>
construction_result_mut() maybe?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6230)

**Comment by Manishearth** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/compositing/compositor.rs, line 498 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6230#-JqkYexoWJeI7_1PTAY6)** ([raw file](https://github.com/servo/servo/blob/c63fc4dc13a23cf5b9f8c0972111b3f9436d2143/components/compositing/compositor.rs#L498)):</sup>
:bike:  IMO it shouldn't be

---

<sup>**[components/gfx/paint_context.rs, line 681 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6230#-Jqk_lsvMYgIOqG3AliI)** ([raw file](https://github.com/servo/servo/blob/c63fc4dc13a23cf5b9f8c0972111b3f9436d2143/components/gfx/paint_context.rs#L681)):</sup>
:bike:  same, compute_ preferred

---

<sup>**[components/gfx/platform/freetype/font.rs, line 279 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6230#-JqkaEQlZC5-pM0IIbxf)** ([raw file](https://github.com/servo/servo/blob/c63fc4dc13a23cf5b9f8c0972111b3f9436d2143/components/gfx/platform/freetype/font.rs#L279)):</sup>
:bike: :+1:

---

<sup>**[components/layout/construct.rs, line 1478 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6230#-JqkaXHpbX2allbA3JIJ)** ([raw file](https://github.com/servo/servo/blob/0ddc6df7ff00e9e7ce0e3811b766a23aeafb0859/components/layout/construct.rs#L1478)):</sup>
:bike: :+1:

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6230)

**Comment by nox** [comment]
@bors-servo: r+

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/compositing/compositor.rs @ r2
- components/compositing/compositor_layer.rs @ r2
- components/gfx/paint_context.rs @ r2
- components/gfx/platform/freetype/font.rs @ r2
- components/layout/construct.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6230)

**Comment by nox** [comment]
@bors-servo: r-

Sorry @frewsxcv, please squash.

**Comment by frewsxcv** [comment]
It has been squashed

**Comment by nox** [comment]
@bors-servo: r+

-S-awaiting-review -S-needs-squash +S-awaiting-merge 

---

Review status: all files reviewed, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6230)

**Pull request merged**
