### PR TITLE
Add initial support for css-text-3 whitespace handling

### LINKED ISSUE #29590: White space is not preserved between atomic inlines
https://bucket.daz.cat/work/igalia/servo/0.html

```html
<!doctype html><meta charset="utf-8"
><span>.</span> <span>.</span><br
><div></div> <div></div><br
><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
> <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
><style>
    span, div { background: black; }
    div, img { width: 1em; height: 1em; }
    div { display: inline-block; }
</style>
```

| layout 2020 | layout 2013 |
| --- | --- |
| image | image |

### LINKED ISSUE #29994: Empty inline formatting contexts are not collapsing through
```html
<body style="margin-top: 50px;">
    <div><span></span></div>
    <p style="background: green; margin-top: 50px;">Content</p>
</body>
```

Layout 2020:

Layout 2020

Layout 2013 and Gecko:

Layout 2013 and Gecko

### PR DESCRIPTION
**Pull request by atbrakhi**
This adds initial support for whitespace handling from the CSS
specification for Layout 2020. In general, the basics are covered. Since
test output is very sensitive to whitespace handling, this change
incorporates several fixes:

1. Whitespace is collapsed according to the Phase 1 rules of the
   specification, though language-specific unbreaking rules are not
   handled properly yet.
2. Whitespace is mostly trimmed and positioned according to the Phase 2
   rules, but full support for removing whitespace at the end of lines
   is pending on a temporary data structure to hold lines under
   construction.
3. Completely empty box fragments left over immediately after line
   breaks are now trimmed from the fragment tree.
4. This change tries to detect when an inline formatting context
   collapses through.

Fixes #29994.
Fixes #29590.

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #29590, #29994.
- [x] There are tests for these changes

### CODE REVIEW

**Comment by stshine** [comment]
Too many failed tests, maybe this is not the right fix?

**Comment by atbrakhi** [comment]
> Too many failed tests, maybe this is not the right fix?

yeah true, I am looking into it.

**Comment by mrobinson** [comment]
@bors-servo try=wept-2020

@atbrakhi can you make a pull request against the servo/saltfs repository giving yourself try access? You should be able to find previous commits that do the same.

**Comment by mrobinson** [comment]
@bors-servo try=wpt-2020

@atbrakhi Can you make a PR against the servo/saltfs repository giving yourself try access? You should be able to find previous commits doing the same.

**Review by mrobinson — APPROVED** [review]

**Review by mukilan — APPROVED** [review]

**Pull request merged**
