### PR TITLE
Avoid dropping arbitrary animation callbacks without running them

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20098)

### CODE REVIEW

**Comment by nox** [comment]
r? @pcwalton 

Cc @jdm because that may be the cause of some weird intermittent failures. Or not.

**Comment by pcwalton** [comment]
Looks good to me.

**Comment by emilio** [comment]
Is there any way this can be tested?

**Comment by nox** [comment]
@emilio I don't really understand how the faking works, so I'll let that as an exercice to the reader.

@bors-servo retry #JustInfraThings

**Pull request merged**
