### PR TITLE
First step to have all ref tests using the same Rust logo.

### PR DESCRIPTION
**Pull request by Adenilson**
Currently we have 3 variants of Rust logo (2 being opaque white and 1 transparent). It would be nice to have a single logo to avoid duplication, this patch is the first step on doing this.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5832)

### CODE REVIEW

**Comment by Adenilson** [comment]
Perhaps leave the other tests as an easy task for some volunteer?

**Comment by Adenilson** [comment]
See #5837

**Comment by Ms2ger** [comment]
I would much rather not use the rust logo at all.

**Comment by jdm** [comment]
I don't really see the value of this. I'm going to close it, but anybody can reopen it and merge it if they feel strongly otherwise.

**Pull request closed without merging**
