### PR TITLE
Update raqote

### PR DESCRIPTION
**Pull request by dralley**
re: https://github.com/jrmuizel/raqote/issues/125

### CODE REVIEW

**Comment by dralley** [comment]
Well, those results are kind of weird.  Lots of unexpectedly passing tests but also a bunch of failing tests for things like history and audio that don't seem canvas-related at all.

**Comment by dralley** [comment]
@jdm do those look like known intermittents?

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /offscreen-canvas/line-styles/2d.line.cap.closed.html:
  └ PASS [expected FAIL] Line caps are not drawn at the corners of an unclosed rectangle
  ▶ Unexpected subtest result in /offscreen-canvas/line-styles/2d.line.cap.closed.worker.html:
  └ PASS [expected FAIL] Line caps are not drawn at the corners of an unclosed rectangle
  ▶ Unexpected subtest result in /offscreen-canvas/fill-and-stroke-styles/2d.gradient.radial.inside3.worker.html:
  └ PASS [expected FAIL] 2d
  ▶ Unexpected subtest result in /offscreen-canvas/fill-and-stroke-styles/2d.gradient.radial.inside3.html:
  └ PASS [expected FAIL] OffscreenCanvas test: 2d.gradient.radial.inside3
  ▶ PASS [expected TIMEOUT] /css/css-paint-api/overdraw.https.html
  ▶ Unexpected subtest result in /2dcontext/line-styles/2d.line.cap.closed.html:
  └ PASS [expected FAIL] Line caps are not drawn at the corners of an unclosed rectangle
  ▶ Unexpected subtest result in /2dcontext/fill-and-stroke-styles/2d.gradient.radial.inside3.html:
  └ PASS [expected FAIL] Canvas test: 2d.gradient.radial.inside3
```
That's the set of tests that we care about. In general, always look at the `filtered-wpt-errorsummary.log` file from the Artifacts list, as that has known intermittent failures filtered out of it.

**Comment by dralley** [comment]
@jdm could you trigger it?

**Comment by dralley** [comment]
Should be good this time..

**Pull request merged**
