### PR TITLE
Refactoring, return an Atom from Element::parsed_name. #5774

### PR DESCRIPTION
**Pull request by mskrzypkows**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6405)

### CODE REVIEW

**Comment by saneyuki** [comment]
@mskrzypkows  have you compiled this?  I feel your patch need to change [this](https://github.com/servo/servo/blob/09f2977cc945850a35f7a5ef1ed014bc42cb265a/components/script/dom/namednodemap.rs#L81).

**Comment by mskrzypkows** [comment]
Yes I've compiled and run tests. You're right, I'll change it.

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6405)

**Comment by jdm** [comment]
```
---- viewport::multiple_stylesheets_cascading stdout ----
	thread 'viewport::multiple_stylesheets_cascading' panicked at 'expected 3 declarations; have 0: [])', /home/servo/buildbot/slave/linux1/build/tests/unit/style/viewport.rs:186
```

**Comment by mskrzypkows** [comment]
I've rebased sources, this test pass on my linux.

**Comment by saneyuki** [comment]
@mskrzypkows okay, please squash

**Comment by mskrzypkows** [comment]
Squashed

**Comment by mskrzypkows** [comment]
Again some viewport test fails, strange...

**Pull request merged**
