### PR TITLE
Partial fix for #12415: expose WebGL interfaces

### PR DESCRIPTION
**Pull request by scotttrinh**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes partially fix #12415  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they do not add any features

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13493)

### CODE REVIEW

**Review by jdm — APPROVED** [review]
@bors-servo: r+
Thanks!

**Comment by KiChjang** [comment]
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.worker:
  │ FAIL [expected PASS] Untitled
  │   → assert_true: WebGLRenderingContext should be defined on the global scope expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:82:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.worker.js:9:1
```

Looks like `WebGLRenderingContext` should be defined on the worker scope as well? Or that our tests need to change?

**Comment by scotttrinh** [comment]
@KiChjang I was having a hard time getting the right answer about that between [the specs](https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl) which does not and Firefox's implementation which does. I'll dig in a bit more and see if I can find a definitive answer.

**Comment by jdm** [comment]
We should remove the interface from the list int interfaces.worker.

**Comment by scotttrinh** [comment]
@jdm You're saying remove [these lines](https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/interfaces.worker.js#L109-L120)?

**Comment by jdm** [comment]
That is correct.

**Comment by KiChjang** [comment]
Needs squashing.

**Pull request merged**
