### PR TITLE
Upgrade to new Hasher API

### LINKED ISSUE #9494: Use the now-stable API in std::hash instead of std::collections::hash_state
See BuildHasher and BuildHasherDefault in [std::hash](https://doc.rust-lang.org/nightly/std/hash/index.html).

```
components/util/cache.rs:9:5: 9:47 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/util/cache.rs:9 use std::collections::hash_state::DefaultState;
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
components/util/cache.rs:20:28: 20:51 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/util/cache.rs:20     entries: HashMap<K, V, DefaultState<SipHasher>>,
                                                       ^~~~~~~~~~~~~~~~~~~~~~~
components/util/cache.rs:29:46: 29:69 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/util/cache.rs:29           entries: HashMap::with_hash_state(<DefaultState<SipHasher> as Default>::default()),
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
components/util/cache.rs:29:20: 29:44 warning: use of deprecated item: renamed to with_hasher, #[warn(deprecated)] on by default
components/util/cache.rs:29           entries: HashMap::with_hash_state(<DefaultState<SipHasher> as Default>::default()),
                                               ^~~~~~~~~~~~~~~~~~~~~~~~
components/gfx/font_context.rs:22:5: 22:47 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/gfx/font_context.rs:22 use std::collections::hash_state::DefaultState;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
components/gfx/font_context.rs:89:57: 89:80 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/gfx/font_context.rs:89         HashMap<LayoutFontGroupCacheKey, Rc<FontGroup>, DefaultState<FnvHasher>>,
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~
components/gfx/font_context.rs:103:38: 103:62 warning: use of deprecated item: renamed to with_hasher, #[warn(deprecated)] on by default
components/gfx/font_context.rs:103             layout_font_group_cache: HashMap::with_hash_state(Default::default()),
                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
components/script/dom/eventtarget.rs:31:5: 31:47 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/script/dom/eventtarget.rs:31 use std::collections::hash_state::DefaultState;
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
components/script/dom/eventtarget.rs:164:65: 164:88 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/script/dom/eventtarget.rs:164     handlers: DOMRefCell<HashMap<Atom, Vec<EventListenerEntry>, DefaultState<FnvHasher>>>,
                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
components/layout/context.rs:23:5: 23:47 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/layout/context.rs:23 use std::collections::hash_state::DefaultState;
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
components/layout/context.rs:98:55: 98:78 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/layout/context.rs:98     pub visible_rects: Arc<HashMap<LayerId, Rect<Au>, DefaultState<FnvHasher>>>,
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~
components/layout/layout_thread.rs:57:5: 57:47 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/layout/layout_thread.rs:57 use std::collections::hash_state::DefaultState;
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
components/layout/layout_thread.rs:198:51: 198:74 warning: use of deprecated item: support moved to std::hash, #[warn(deprecated)] on by default
components/layout/layout_thread.rs:198     visible_rects: Arc<HashMap<LayerId, Rect<Au>, DefaultState<FnvHasher>>>,
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
components/layout/layout_thread.rs:433:37: 433:61 warning: use of deprecated item: renamed to with_hasher, #[warn(deprecated)] on by default
components/layout/layout_thread.rs:433             visible_rects: Arc::new(HashMap::with_hash_state(Default::default())),
                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~
components/layout/layout_thread.rs:1102:37: 1102:61 warning: use of deprecated item: renamed to with_hasher, #[warn(deprecated)] on by default
components/layout/layout_thread.rs:1102         let mut old_visible_rects = HashMap::with_hash_state(Default::default());
                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by ruuda**
This fixes #9494.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9523)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
@bors-servo r+

Thanks!

**Comment by Wafflespeanut** [comment]
... but, but, it's been a day!

**Comment by Wafflespeanut** [comment]
@ruud-v-a BTW, next time you work on an issue, please comment on the issue saying that you're working on it :)

**Comment by ruud-v-a** [comment]
Ok, I’ll leave a comment next time.

**Pull request merged**
