### PR TITLE
Refactor #[jstraceable] to #[derive(JSTraceable)]

### LINKED ISSUE #6524: Change #[jstraceable] to #[derive(JSTraceable)]
A syntax decorator named #[derive_Foo] can be used as #[derive(Foo)]. #[jstraceable] derives an implementation of the JSTraceable trait and thus should be named derive_JSTraceable.

See files:

 * components/plugins/jstraceable.rs
 * components/plugins/lib.rs

### PR DESCRIPTION
**Pull request by dwins**
fixes #6524.  I had to make an additional change not mentioned in the ticket - adding the `#[feature]` to enable deriving custom traits but I assume that's expected at this time.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6529)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+

Thanks!

**Comment by Manishearth** [comment]
You missed some on CodegenRust.py, line 3190 and 5180

Ensure that it compiles after fixing this and let me know, thanks! :smile:

**Comment by dwins** [comment]
@Manishearth Thank you for the quick review.  I should have known that I should do a clean build after that refactor.  I verified that a clean compile works and overwrote my previous commit.

**Pull request merged**
