### PR TITLE
Implement a quota of 5MB per origin for localstorage and sessionstorage

### PR DESCRIPTION
**Pull request by iawaknahc**
PR for https://github.com/servo/servo/issues/6739

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7835)

### CODE REVIEW

**Comment by jdm** [comment]
This looks really good! Just a couple subtleties about counting bytes and some changes for readability before we can merge!
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 43 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7835#-K0527aMRn9vqry2qrVc)** ([raw file](https://github.com/servo/servo/blob/c80c10be9512fc4cea8a5355bd583f29fa9a5fca/components/net/storage_task.rs#L43)):</sup>
I'm inclined to make this a global `const` value rather than a member.


---

<sup>**[components/net/storage_task.rs, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7835#-K053jLzx5ViuqcPv-6t)** ([raw file](https://github.com/servo/servo/blob/c80c10be9512fc4cea8a5355bd583f29fa9a5fca/components/net/storage_task.rs#L112)):</sup>
We should update this description with the new behaviour.


---

<sup>**[components/net/storage_task.rs, line 128 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7835#-K053xFIwZpRqnW7jvqe)** ([raw file](https://github.com/servo/servo/blob/c80c10be9512fc4cea8a5355bd583f29fa9a5fca/components/net/storage_task.rs#L128)):</sup>
This doesn't seem necessary.


---

<sup>**[components/net/storage_task.rs, line 137 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7835#-K06zF2lXrzXm0z4976R)** ([raw file](https://github.com/servo/servo/blob/c80c10be9512fc4cea8a5355bd583f29fa9a5fca/components/net/storage_task.rs#L137)):</sup>
Can we use this instead?
```rust
let mut new_total_size = current_total_size + value.len();
if let Some(old_value) = entry.get(&name) {
     new_total_size -= old_value.len();
} else {
    new_total_size += name.len();
};
```
Also, we should be using `.as_bytes().len()` instead of `.len()` for all of these calculations, to account for multibyte characters.


---

<sup>**[components/net/storage_task.rs, line 147 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7835#-K07-m0R2dv-gdyyaKjV)** ([raw file](https://github.com/servo/servo/blob/c80c10be9512fc4cea8a5355bd583f29fa9a5fca/components/net/storage_task.rs#L147)):</sup>
We don't need to repeat the total calculations again, do we? Can't we use the value we calculated above?


---

<sup>**[components/net/storage_task.rs, line 182 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7835#-K070A9MYuaY_o2N9TTM)** ([raw file](https://github.com/servo/servo/blob/c80c10be9512fc4cea8a5355bd583f29fa9a5fca/components/net/storage_task.rs#L182)):</sup>
Same comment about byte length.


---

<sup>**[components/net_traits/storage_task.rs, line 28 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7835#-K052h4UynjdB57ErcG3)** ([raw file](https://github.com/servo/servo/blob/c80c10be9512fc4cea8a5355bd583f29fa9a5fca/components/net_traits/storage_task.rs#L28)):</sup>
I'm inclined to make this a `Result<(bool, Option<DOMString>), ()>` instead.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7835)

**Comment by jdm** [comment]
Great! Go ahead and squash these commits together, please!
-S-awaiting-review +S-needs-squash 


---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7835)

**Comment by jdm** [comment]
Just need to rebase to resolve the merge conflicts now :)

**Comment by jdm** [comment]
```
/build/components/net/storage_task.rs:121:54: 121:60 error: no method named `keys` found for type `&(usize, collections::btree::map::BTreeMap<collections::string::String, collections::string::String>)` in the current scope

/build/components/net/storage_task.rs:121                        .map_or(vec![], |entry| entry.keys().cloned().collect());

                                                                                               ^~~~~~
```

**Comment by iawaknahc** [comment]
Sorry about that.

**Comment by jdm** [comment]
No problem! It's what travis is there to protect against :)

**Comment by jdm** [comment]
@bors-servo: retry
* #7931

**Comment by jdm** [comment]
@bors-servo: retry
* #7931

**Comment by jdm** [comment]
@bors-servo: retry
* #7731

**Pull request merged**
