### PR TITLE
build: flatpak support

### LINKED ISSUE #12102: Support building flatpak packages
This will make cross-distro packaging somewhat less of a headache.

I'd like to claim this issue -- just filing it here for tracking.

### PR DESCRIPTION
**Pull request by okias**
Development build takes about 30 minutes on i7-7500U CPU @ 2.70GHz / 3.50GHz (with turbo). At least 8 GB RAM required.

Current state:
- [x] python stuff is installed
- [x] cargo deps needs to be packages (but sadly script needs to be [patched](https://github.com/flatpak/flatpak-builder-tools/issues/181)).
- [x] fix few CMake deps to get pre-downloaded and used https://github.com/servo/servo/issues/28102 .
- [x] open Servo window. Works when based on https://github.com/servo/servo/pull/28236
- [x] wait for https://github.com/servo/servo/pull/28236 merge
- [x] fix error[E0532]: expected unit struct, unit variant or constant, found tuple variant `visit::FnKind::Closure`
- [x] create update script, to keep flatpak in sync with servo rust requirement, cargo dependencies and misc.

```
flatpak-builder --repo=repo org.servo.Servo data/org.servo.Servo.json --force-clean
flatpak build-export repo org.servo.Servo
flatpak build-bundle repo org.servo.Servo.flatpak org.servo.Servo
flatpak install --user org.servo.Servo.flatpak
```

Maintanance
Flatpak cargo dependencies update process (assuming it's in master branch):
```
git pull --rebase
./data/flatpak_updater.sh
```

Related to: https://github.com/servo/servo/issues/12102
Based on: https://github.com/servo/servo/issues/27942

---

- [x] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [x] These changes fix #12102 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because does not change the Servo code, just add different way to build it

### CODE REVIEW

**Comment by jdm** [comment]
I know nothing about flatpak. What is the purpose of adding support for it?

**Comment by okias** [comment]
User or developer doesn't have to setup environment, everything is build in separate environment, packaged into one archive (distributable with flathub, as file or any other way).

It offers advantage of good reproducibility across all Linux systems.

Build can be done just by installing GNOME Builder and clicking at Build (and Run button). Also it's really handy for development.

**Comment by hfiguiere** [comment]
> It offers advantage of good reproducibility (stable SDK + runtime environment) across all Linux systems.

By "across all Linux system" did you mean to include at least `aarch64` which is the other architecture officially supported by the freedesktop-sdk ? This would be even more useful as building fails on a Raspberry Pi 400 (it only has 4GB - and yes, requirements above say 8GB minimum)

**Comment by okias** [comment]
> > It offers advantage of good reproducibility (stable SDK + runtime environment) across all Linux systems.
> 
> By "across all Linux system" did you mean to include at least `aarch64` which is the other architecture officially supported by the freedesktop-sdk ? This would be even more useful as building fails on a Raspberry Pi 400 (it only has 4GB - and yes, requirements above say 8GB minimum)

Cannot do it bow, but if u just fill sha256 for rust nightly sources, it should work! 😄

**Comment by okias** [comment]
Crashed after while, but works on Wayland (with XWayland emulation). Pulled winit https://github.com/servo/servo/pull/28236

**Comment by okias** [comment]
@hfiguiere I did updated the MR, now it includes aarch64, but it's untested.

**Comment by okias** [comment]
ok, aarch64 seems to be problem:
```
error: linker `aarch64-linux-gnu-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `syn`

```
even over the fact it's installed.

**Comment by okias** [comment]
current version **does run** on aarch64 (tested on Mobian with Phosh), but sadly incompatible with GLES
```
Failed to create WR surfman: ContextCreationFailed(BadMatch) (thread main, at ports/winit/headed_window.rs:158)
```
so must be run as `LIBGL_ALWAYS_SOFTWARE=1 flatpak run org.servo.Servo`

**Comment by yookoala** [comment]
Made a repo to build the manifest for building / installing flatpak:
https://github.com/yookoala/servo-flatpak/

If you're looking for solution to build and install Servo's demo browser as flatpak, please try this out.

**Pull request closed without merging**
