### PR TITLE
Combine transform-origin, perspective-origin code

### LINKED ISSUE #7194: Combine code for parsing perspective-origin and transform-origin
Code is in [components/style/properties.mako.rs](https://github.com/servo/servo/blob/master/components/style/properties.mako.rs)
Look for `<%self:longhand name="perspective-origin">` and `<%self:longhand name="transform-origin">`

There's about 80 lines of parsing that is identical except transform-origin also parses a depth. Perspective-origin can probably just return an error if depth is not None.

### PR DESCRIPTION
**Pull request by tgkokk**
First PR, please tell me if anything is wrong/could use improvement.

Fixes #7194.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7289)

### CODE REVIEW

**Comment by dzbarsky** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/style/properties.mako.rs, line 4067 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7289#-Jx7IDb85LwKMe2jVLUd)** ([raw file](https://github.com/servo/servo/blob/bf4224e3cb0739689d14814c0974af16817282b3/components/style/properties.mako.rs#L4067)):</sup>
You can do let result = try!(super::parse_origin(context, input));
Then you don't need to return Err or check for Ok.

---

<sup>**[components/style/properties.mako.rs, line 4146 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7289#-Jx7IQ4WV6zd4g5VDHQF)** ([raw file](https://github.com/servo/servo/blob/bf4224e3cb0739689d14814c0974af16817282b3/components/style/properties.mako.rs#L4146)):</sup>
try! here as well.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7289)

**Comment by dzbarsky** [comment]
Thanks for the PR!

**Comment by tgkokk** [comment]
Thanks, I've updated it.

**Comment by nox** [comment]
@bors-servo r=dzbarsky

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7289)

**Pull request merged**
