### PR TITLE
HTML 5 form validation

### PR DESCRIPTION
**Pull request by tyagiarpit**
Implemented the stub methods for HTML5 Form validations.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10108)

### CODE REVIEW

**Comment by jdm** [comment]
Two issues that are being caught by TravisCI for us - be sure to run `./mach test-tidy` and fix the stylistic errors that it reports. Additionally, the changes as written do not compile due to these errors:
```
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:271:55: 271:65 error: multiple applicable items in scope [E0034]
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:271             .map(|s| synthetic_click_activation(s.r().as_element(),
                                                                                                                                    ^~~~~~~~~~
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:271:55: 271:65 help: run `rustc --explain E0034` to see a detailed explanation
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:208:5: 210:6 note: candidate #1 is defined in an impl of the trait `dom::validation::Validatable` for the type `dom::htmlbuttonelement::HTMLButtonElement`
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:208     fn as_element(&self) -> &Element {
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:209         self.upcast()
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:210     }
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:219:5: 221:6 note: candidate #2 is defined in an impl of the trait `dom::activation::Activatable` for the type `dom::htmlbuttonelement::HTMLButtonElement`
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:219     fn as_element(&self) -> &Element {
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:220         self.upcast()
/home/travis/build/servo/servo/components/script/dom/htmlbuttonelement.rs:221     }
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:1111:55: 1111:65 error: multiple applicable items in scope [E0034]
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:1111                     synthetic_click_activation(button.as_element(),
                                                                                                                                    ^~~~~~~~~~
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:1111:55: 1111:65 help: run `rustc --explain E0034` to see a detailed explanation
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:913:5: 915:6 note: candidate #1 is defined in an impl of the trait `dom::validation::Validatable` for the type `dom::htmlinputelement::HTMLInputElement`
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:913     fn as_element(&self) -> &Element {
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:914         self.upcast()
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:915     }
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:927:5: 929:6 note: candidate #2 is defined in an impl of the trait `dom::activation::Activatable` for the type `dom::htmlinputelement::HTMLInputElement`
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:927     fn as_element(&self) -> &Element {
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:928         self.upcast()
/home/travis/build/servo/servo/components/script/dom/htmlinputelement.rs:929     }
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `script`.
```

**Comment by jdm** [comment]
Great work! There are some more changes we can make to increase the clarity of the new code, but this is looking good!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 2 files at r1, 1 of 6 files at r2, 13 of 13 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[components/script/dom/element.rs, line 1918 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUq4YpA0TYiUbfhds5:-KDUq4YpA0TYiUbfhds6:-1190432425) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/element.rs#L1918)):*
Let's add a `// https://html.spec.whatwg.org/multipage/#category-submit` comment above this.

---

*[components/script/dom/element.rs, line 1928 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUphjwQZFxiIbglkmF:-KDUphjx3y9fDCkfr1JW:1130908744) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/element.rs#L1928)):*
This isn't necessary, since anchor elements aren't [submittable elements](https://html.spec.whatwg.org/multipage/forms.html#category-submit) and can't be validated.

---

*[components/script/dom/element.rs, line 1932 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUpo0UExoxEWXcU_p1:-KDUpo0UExoxEWXcU_p2:160841994) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/element.rs#L1932)):*
Same as above.

---

*[components/script/dom/element.rs, line 1949 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUqYyhjwlNJ_ZH_CXa:-KDUqYyibRkob7ZGQroN:1857488645) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/element.rs#L1949)):*
The specification doesn't list any exceptions for an element being considered submittable or not, so let's remove this check. We can just return `element` directly.

---

*[components/script/dom/htmlinputelement.rs, line 939 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUr2frvtAMdOK69WY4:-KDUr2fsdEIM9-kiMz2R:697959344) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/htmlinputelement.rs#L939)):*
Let's remove these extraneous newlines.

---

*[components/script/dom/validation.rs, line 6 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUrAB8nNNGNrzYLu9P:-KDUrAB9aQUXrOxmcwGb:891293811) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/validation.rs#L6)):*
This method isn't necessary. In the future we'll want to add things like `is_barred_from_constraint_validation` and `satisfies_constraints` (ie. step 3 of (the spec)[https://html.spec.whatwg.org/multipage/forms.html#statically-validate-the-constraints]) but right now it's not needed.

---

*[components/script/dom/validitystate.rs, line 14 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUrXdrZz-g5bQLn5b-:-KDUrXdrZz-g5bQLn5b0:-2027340838) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/validitystate.rs#L14)):*
Let's add a `/// https://html.spec.whatwg.org/multipage/#validity-states` comment above this.

---

*[components/script/dom/validitystate.rs, line 33 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUs4uYg_QlWy81rixj:-KDUs4uYg_QlWy81rixk:290586871) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/validitystate.rs#L33)):*
Let's make `state` a `ValidityStatus` field instead, and default to `Valid`.

---

*[components/script/dom/validitystate.rs, line 55 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUrqEJKWrJRSK4fL6x:-KDUrqEJKWrJRSK4fL6y:-1668051671) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/validitystate.rs#L55)):*
https://html.spec.whatwg.org/multipage/#dom-validitystate-valuemissing

---

*[components/script/dom/validitystate.rs, line 60 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDUrtEiGblSKNUGp19V:-KDUrtEiGblSKNUGp19W:1823877060) ([raw file](https://github.com/servo/servo/blob/2300431e12b889c47a68bef6b2535187a2eb1530/components/script/dom/validitystate.rs#L60)):*
https://html.spec.whatwg.org/multipage/#dom-validitystate-typemismatch

etc. for the remainder of the method comments here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10108#-:-KDUsIq4c5bcdLfyQvC4:-1798813929)*

**Comment by jdm** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute valueMissing

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute typeMismatch

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute patternMismatch

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute tooLong

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute tooShort

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute rangeUnderflow

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute rangeOverflow

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute stepMismatch

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute badInput

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute customError

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] ValidityState interface: attribute valid
```

**Comment by jdm** [comment]
Those will also need to be addressed according to [our documentation](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations). Tests that used to fail and now pass are a good thing :)

**Comment by jdm** [comment]
One tiny change! Please [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) all the commits into one, as well.
-S-awaiting-review +S-needs-code-changes +S-needs-squash 

---

Reviewed 9 of 11 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/validitystate.rs, line 15 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDVm2cQimXn2icti-XB:-KDVm2cQimXn2icti-XC:1634308723) ([raw file](https://github.com/servo/servo/blob/7fdf05538799bd285daa8f4f3d0ebee4ac1dacf5/components/script/dom/validitystate.rs#L15)):*
Use `derive(Foo)` instead of `derive_Foo`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10108#-:-KDVmDVNkPsLaHQzpe0E:751423739)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/validitystate.rs, line 16 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10108#-KDWoCxuohFZnFUEMVLu:-KDWoCxvo_4Z3ncG5rMh:603058062) ([raw file](https://github.com/servo/servo/blob/7fdf05538799bd285daa8f4f3d0ebee4ac1dacf5/components/script/dom/validitystate.rs#L16)):*
nit: ValidityStates

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10108)*

**Comment by jdm** [comment]
Ok, just waiting on addressing the test result changes and squashing all the commits in to one.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10108#-:-KD_MxLu0nsvq22OwlAF:2003968026)*

**Comment by srm912** [comment]
@jdm Tried squashing the commits into a single one, it shows some code which does not belong to From Validation feature. Not sure how to get rid of it!
What do you suggest? Should we recreate a new PR with a single commit

**Comment by jdm** [comment]
@srm912 It looks like it worked fine to me!

**Comment by jdm** [comment]
Ah, my mistake. It appears there were rebasing errors that undid recent changes in htmlinputelement.rs and htmllabelelement.rs. Those will need to be undone in order for the changes to merge.

**Comment by jdm** [comment]
Rebased in #10169. Thanks!

**Pull request closed without merging**
