### PR TITLE
Change all DOMStrings to USV strings for XHR

### PR DESCRIPTION
**Pull request by KiChjang**
This is in compliance with the new spec [here](https://xhr.spec.whatwg.org/#xmlhttprequest).

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9294)

### CODE REVIEW

**Comment by Ms2ger** [comment]
If this doesn't fix any tests, we should write some.

**Comment by KiChjang** [comment]
Only one way to know.

@bors-servo try

**Comment by KiChjang** [comment]
Wow. That was quick.

@bors-servo retry
* Networking issue, perhaps?

**Comment by KiChjang** [comment]
@Ms2ger I'm not sure what to test for in this case. I'm assuming `USVString`s still get converted to a normal JS String?

**Comment by Ms2ger** [comment]
For things that return `USVString`, there's nothing you can do. You should test that unpaired surrogates in the arguments to `open` are replaced by U+fffd, though.

**Comment by KiChjang** [comment]
Added tests, one should be enough.

**Comment by Ms2ger** [comment]
Why does your new test fail?

**Comment by nox** [comment]
What. I can't read. Just read the test and didn't read the expectations… :(

@bors-servo r-

**Comment by KiChjang** [comment]
The test was actually originally failing before, the returned "x-request-query" header value is "%EF%BF%BD", both before my patch and after (in both tests).

**Comment by nox** [comment]
```
decodeURIComponent("%EF%BF%BD")
```

This is U+FFFD though. How come the replacement was already done on the previous code? Do you mean with the `-Z` flag?

**Comment by KiChjang** [comment]
Beats me. I'm guessing the german "ess-zet" was incorrectly parsed as a lone surrogate? I'll try to find the root cause of it.

**Comment by KiChjang** [comment]
I've updated the test to instead use \u00DF to represent the german eszett (the ß character). Somehow, the test file stores the ß character as <DF> instead of the unicode \u00DF.

With that, the test should now pass.

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9294#-:-K89i3fA3ckUWkC-OwjM:1236647940)*

**Comment by KiChjang** [comment]
@bors-servo retry
* #8961

**Comment by nox** [comment]
Weird. What failed this time?

**Comment by KiChjang** [comment]
@bors-servo retry
* Buildbot interruption

**Pull request merged**
