### PR TITLE
Add sugar for RefPtr<T>; use for `quotes` property

### PR DESCRIPTION
**Pull request by Manishearth**
Carry-over from https://bugzilla.mozilla.org/show_bug.cgi?id=1309848

r=mystor,emilio

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13754)

### CODE REVIEW

**Comment by KiChjang** [comment]
Fails tidy:
```
Checking files for tidiness...

./components/style/gecko_bindings/sugar/refptr.rs:6: use statement is not in alphabetical order
	expected: heapsize::HeapSizeOf
	found: gecko_bindings::structs

./components/style/gecko_bindings/sugar/refptr.rs:8: use statement is not in alphabetical order
	expected: std::marker::PhantomData
	found: std::{mem, ptr}
```

**Comment by Manishearth** [comment]
@bors-servo r+

Ugh, push -f

**Pull request merged**
