### PR TITLE
Improve code around Window::load_url.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7075)

### CODE REVIEW

**Comment by dzbarsky** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/location.rs, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7075#-Jw8ffEoMbNbYq2Oemir)** ([raw file](https://github.com/servo/servo/blob/40b5c4586ed7aa8327b2ae1f058bdaf6202bb90e/components/script/dom/location.rs#L47)):</sup>
We fail silently here but Step 6 of https://html.spec.whatwg.org/multipage/infrastructure.html#resolve-a-url say to to abort with an error

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7075)

**Comment by Ms2ger** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/location.rs, line 46 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7075#-Jw8ffEoMbNbYq2Oemir)** ([raw file](https://github.com/servo/servo/blob/40b5c4586ed7aa8327b2ae1f058bdaf6202bb90e/components/script/dom/location.rs#L46)):</sup>
> When the assign(url) method is invoked, the UA must resolve the argument, relative to the API base URL specified by the entry settings object, and *if that is successful*, must navigate the browsing context to the specified url, with exceptions enabled.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7075)

**Comment by dzbarsky** [comment]
r=me

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/location.rs, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7075#-Jw8ffEoMbNbYq2Oemir)** ([raw file](https://github.com/servo/servo/blob/40b5c4586ed7aa8327b2ae1f058bdaf6202bb90e/components/script/dom/location.rs#L47)):</sup>
I guess it doesn't say what kind of error it so, so it must not be an actual DOMException.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7075)

**Comment by Ms2ger** [comment]
It's basically `Err(())`.

@bors-servo r=dzbarsky

**Pull request merged**
