### PR TITLE
rename 

### LINKED ISSUE #11418: ScriptThread::{page_fetch_complete, handle_page_fetch_complete} are poorly named
They are called when we've received the headers, not the content.

@jdm suggested `page_headers_available`.

Code: `components/script/script_thread.rs`

### PR DESCRIPTION
**Pull request by rafaqtro**
rename of page_fetch_complete and handle_page_fetch_complete for page_headers_available and handle_page_headers_available .

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #11418 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11480)

### CODE REVIEW

**Comment by jdm** [comment]
@rafaqtro It doesn't appear that you have compiled these changes, since no code that calls `page_fetch_complete` was updated.

**Comment by emilio** [comment]
Hi, this looks a lot better now! :)

Could you align the arguments for those functions to the same column, please?
This is ready to land with that.

Thanks for doing this! :-)

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/script/script_thread.rs, line 481 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11480#-KIsUfVzA2QCX98rTGr9:-KIsUfW-DBU96sAk6qfv:1780374676) ([raw file](https://github.com/servo/servo/blob/115ed16c8b4b8ba55b323a617a094a68b4acc87a/components/script/script_thread.rs#L481)):*
> ```Rust
> impl ScriptThread {
>     pub fn page_headers_available(id: &PipelineId, subpage: Option<&SubpageId>, metadata: Option<Metadata>)
>                                -> Option<ParserRoot> {
> ```

nit: Could you align this with the parenthesis, as it was before?

---

*[components/script/script_thread.rs, line 1302 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11480#-KIsUjrJomULJMEHYEXe:-KIsUjrJomULJMEHYEXf:-469765787) ([raw file](https://github.com/servo/servo/blob/115ed16c8b4b8ba55b323a617a094a68b4acc87a/components/script/script_thread.rs#L1302)):*
> ```Rust
>     /// Kick off the document and frame tree creation process using the result.
>     fn handle_page_headers_available(&self, id: &PipelineId, subpage: Option<&SubpageId>,
>                                   metadata: Option<Metadata>) -> Option<ParserRoot> {
> ```

ditto

---

*[components/script/dom/servohtmlparser.rs, line 98 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11480#-KIsUn_g3vbG4a417gLk:-KIsUn_g3vbG4a417gLl:-2101067928) ([raw file](https://github.com/servo/servo/blob/c0832d94267c02158a0600de6fa0846b0df8d07b/components/script/dom/servohtmlparser.rs#L98)):*
> ```Rust
>         let content_type = metadata.clone().and_then(|meta| meta.content_type);
>         let parser = match ScriptThread::page_headers_available(&self.id,
>                                                              self.subpage.as_ref(),
> ```

here too, please :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11480#-:-KIsUrligjVBwMZlxthQ:-1887346200)*

**Comment by emilio** [comment]
Also, if you could squash the commits, that would be great, let us know if you need any help with that :)

**Comment by rafaqtro** [comment]
yes, @emilio  how do i squash the commits?

**Comment by jdm** [comment]
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ is a useful reference.

**Comment by emilio** [comment]
Great, thanks for doing this @rafaqtro! :)

@bors-servo: r+ 

Take a look to https://starters.servo.org if you want to find another issue, we're happy to help!

**Comment by rafaqtro** [comment]
yes i would like  to find other issue. if  you can help me @emilio ?

**Comment by emilio** [comment]
Hi @rafaqtro,

So, would you like something like https://github.com/servo/servo/issues/11557, or maybe something a bit more challenging? If you'd prefer to use other languages, like JavaScript or Rust, there are also good first PRs for those, what would you be more interested in?

**Comment by rafaqtro** [comment]
yes, i do this, and after that, i could do some more challenging maybe in js.

**Pull request merged**
