### PR TITLE
Remove gst-plugins-ugly dep from README

### PR DESCRIPTION
**Pull request by Manishearth**
We don't use it and shouldn't be using it because of the license

r? @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21904)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo retry

 - timeout on `html/semantics/embedded-content/media-elements/location-of-the-media-resource/currentSrc.html`

**Comment by Manishearth** [comment]
@bors retry

 - referrer policy stuff

**Comment by CYBAI** [comment]
@bors-servo retry

- referrer policy stuff

@Manishearth Ha, we should ask `bors-servo` in Servo :P

**Comment by CYBAI** [comment]
@bors-servo retry

- referrer policy stuff

**Comment by jdm** [comment]
@bors-servo retry
Network issues

**Pull request merged**
