### PR TITLE
Move build.rs along with the other Servo files from components to ports

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @Ms2ger 

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14280)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo retry
* #10473, #14221

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #10473

**Comment by KiChjang** [comment]
@bors-servo retry
* #13133

**Comment by larsbergstrom** [comment]
@bors-servo retry
 - #10473

**Comment by larsbergstrom** [comment]
@bors-servo retry

    #10473

**Comment by larsbergstrom** [comment]
@bors-servo retry
- infra (OS too many fds)

**Pull request merged**
