### PR TITLE
Make handle_potential_webgl_error more ergonomic

### PR DESCRIPTION
**Pull request by wilcus**
https://github.com/servo/servo/issues/7358

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7360)

### CODE REVIEW

**Comment by jdm** [comment]
Can you update the existing case where we use this macro with (), too?

**Comment by wilmoz** [comment]
Yes, i'll search that

**Comment by wilmoz** [comment]
I've finished now

**Comment by jdm** [comment]
As it happens, #6770 added several additional uses, too. Could you rebase and update those?

**Comment by wilmoz** [comment]
ok i forget to pull

**Pull request merged**
