### PR TITLE
Don't insta-free in UniqueArc::assume_init.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23843)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Oops :)

@bors-servo r+

**Comment by emilio** [comment]
@bors-servo r=SimonSapin

 * Added another gecko-only fix I needed for mozilla-central.

**Comment by CYBAI** [comment]
```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "The document for a standalone media file should have one child in the body.", 
    "test": "/html/browsers/browsing-the-web/read-media/pageload-image-in-popup.html", 
    "line": 77249, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

**Comment by emilio** [comment]
@bors-servo retry

 * That can't be related to this PR.

**Pull request merged**
