### PR TITLE
Add CCACHE infra and turn it on in travis

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @Manishearth 

This lets devs configure their use of CCACHE with their .servobuild file, as usual. For build environments, they can either have a .servobuild file or set the CCACHE env var to point at the ccache binary to use.

It also adds support for ccache to our travis builds. Buildbot will come in a separate commit to the saltfs repo.

It is expected that the various cargo makefiles will look at this variable and do the "right thing" to tell their native build to instead use ccache. e.g., https://github.com/servo/mozjs/pull/62

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8366)

### CODE REVIEW

**Comment by frewsxcv** [comment]
@bors-servo r-

This causes Travis to fail. We should make it a policy to let Travis finish if the config file ever changes.

**Comment by larsbergstrom** [comment]
`Could not locate requirements.txt. Override the install: key in your .travis.yml to install dependencies.`

wat

**Comment by frewsxcv** [comment]
It might be worth going this route: http://docs.travis-ci.com/user/caching/#ccache-cache ?

**Comment by larsbergstrom** [comment]
@frewsxcv That does the same thing (but also adds it to the PATH, which we don't need). I think there's something deeper going on, and I'll try to dig in tomorrow. I'm not sure how this is working at all today, as the travis validator claims that what we have right now gets most of its content thrown out because they're not valid in those parts of the file.

**Comment by frewsxcv** [comment]
FWIW, I don't know think the current caching statements in the config do anything

**Comment by frewsxcv** [comment]
Asked about this on IRC. A response I got:

```
9:09 PM <jhass> frewsxcv: add the env to the matrix key
9:10 PM <jhass> cache: false\n     env: CCACCHE=...
9:10 PM <jhass> and the other one too
9:11 PM <jhass> or not
```

It might be worth adding the `env` section into the second `matrix` `include` and seeing what happens

**Comment by larsbergstrom** [comment]
This is green! Can I get a re-r+ including the new bit?

**Pull request merged**
