### PR TITLE
Make manifest_changed.sh check the CSS tests as well

### LINKED ISSUE #13607: Make manifest_changed.sh check the CSS tests as well
Right now the script invokes the `test-wpt` command, which verifies that the MANIFEST.json file for the WPT tests is valid. We should run the same set of commands for `test-css`, which would verify that the CSS tests' MANIFEST.json is valid too. This would have caught the syntax error seen in #13599.

Code: `etc/ci/manifest_changed.sh`

### PR DESCRIPTION
**Pull request by shubheksha**
Make manifest_changed.sh check the CSS tests as well

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #13607  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13642)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+

lgtm.

There's a good chance this will fail due to some manifest changes that need to be made, but we can just apply them once the test results are in.

**Comment by Manishearth** [comment]
Could you apply the diff from http://build.servo.org/builders/mac-dev-unit/builds/3455/steps/shell_2/logs/stdio ?

@jgraham @jdm that's a pretty big diff, did something go wrong in the last sync?

**Comment by jdm** [comment]
This looks similar to https://github.com/servo/servo/issues/8535, which was never solved - we just committed the huge amount of manifest changes, I believe.

**Comment by Manishearth** [comment]
Alright, cool. @shubheksha you can just apply the diff in the link, commit that, push, and let me know

**Comment by Ms2ger** [comment]
This should all be gone soon enough, so fine by me

**Comment by Manishearth** [comment]
Huh. Looks like the compositing tests are only run on mac?

I'm not sure what's going on here. @Ms2ger ?

**Comment by Ms2ger** [comment]
Not sure what's up, and I'm not convinced it's worth spending the time to figure it out. Sorry to waste your time like this, @shubheksha :/

**Pull request closed without merging**
