### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See individual commits for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23609)

### CODE REVIEW

**Comment by CYBAI** [comment]
Travis complains about tidy

```
$ ./mach test-tidy --no-progress --all
 0:08.04 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/mozilla/meta/MANIFEST.json
 0:08.15 WARNING Manifest /home/travis/build/servo/servo/tests/wpt/mozilla/meta/MANIFEST.json contains correct tests but file hashes changed.
 0:08.16 ERROR Manifest /home/travis/build/servo/servo/tests/wpt/mozilla/meta/MANIFEST.json is outdated, use |./mach update-manifest| to fix.
 0:08.16 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/metadata/MANIFEST.json
 0:13.33 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/webgl/meta/MANIFEST.json


info: downloading component 'rustfmt'
info: installing component 'rustfmt'
Diff in /home/travis/build/servo/servo/tests/unit/style/stylesheets.rs at line 11:
 use style::error_reporting::{ContextualParseError, ParseErrorReporter};
 use style::media_queries::MediaList;
 use style::shared_lock::SharedRwLock;
-use style::stylesheets::Stylesheet;
 use style::stylesheets::Origin;
+use style::stylesheets::Stylesheet;
 
 #[derive(Debug)]
 struct CSSError {
Diff in /home/travis/build/servo/servo/components/script/dom/element.rs at line 683:
             hints.push(from_declaration(
                 shared_lock,
                 PropertyDeclaration::BackgroundImage(background_image::SpecifiedValue(
-                    vec![specified::ImageLayer::Image(specified::Image::for_cascade(url.into()))].into(),
+                    vec![specified::ImageLayer::Image(specified::Image::for_cascade(
+                        url.into(),
+                    ))]
+                    .into(),
                 )),
             ));
         }
Run `./mach fmt` to fix the formatting
```

In `linux-rel-wpt`:

<details>

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Property background-size value '1px' computes to '1px'", 
    "test": "/css/css-backgrounds/parsing/background-size-computed.html", 
    "line": 56611, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Property background-size value '1px auto' computes to '1px'", 
    "test": "/css/css-backgrounds/parsing/background-size-computed.html", 
    "line": 56612, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "background-size_length_zero", 
    "test": "/css/css-backgrounds/background-size-001.html", 
    "line": 142433, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "background-size_length_negative_zero", 
    "test": "/css/css-backgrounds/background-size-001.html", 
    "line": 142434, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "background-size_length_positive_zero", 
    "test": "/css/css-backgrounds/background-size-001.html", 
    "line": 142435, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "background-size_length_normal", 
    "test": "/css/css-backgrounds/background-size-001.html", 
    "line": 142436, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "background-size_percentage_min", 
    "test": "/css/css-backgrounds/background-size-001.html", 
    "line": 142437, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "background-size_percentage_normal", 
    "test": "/css/css-backgrounds/background-size-001.html", 
    "line": 142438, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "background-size_percentage_max", 
    "test": "/css/css-backgrounds/background-size-001.html", 
    "line": 142439, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: background-size supporting value expected \"15px auto\" but got \"15px\"", 
    "stack": "@http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:101:13\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\n@http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:100:9\n", 
    "subtest": "background-size_length_auto", 
    "test": "/css/css-backgrounds/background-size-001.html", 
    "line": 142443, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: background-size supporting value expected \"50% auto\" but got \"50%\"", 
    "stack": "@http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:119:13\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\n@http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:118:9\n", 
    "subtest": "background-size_percentage_auto", 
    "test": "/css/css-backgrounds/background-size-001.html", 
    "line": 142446, 
    "action": "test_result", 
    "expected": "PASS"
}
```

</details>

**Comment by jdm** [comment]
```

  ▶ Unexpected subtest result in /css/css-backgrounds/background-size-001.html:
  └ PASS [expected FAIL] background-size_length_zero

  ▶ Unexpected subtest result in /css/css-backgrounds/background-size-001.html:
  └ PASS [expected FAIL] background-size_length_negative_zero

  ▶ Unexpected subtest result in /css/css-backgrounds/background-size-001.html:
  └ PASS [expected FAIL] background-size_length_positive_zero

  ▶ Unexpected subtest result in /css/css-backgrounds/background-size-001.html:
  └ PASS [expected FAIL] background-size_length_normal

  ▶ Unexpected subtest result in /css/css-backgrounds/background-size-001.html:
  └ PASS [expected FAIL] background-size_percentage_min

  ▶ Unexpected subtest result in /css/css-backgrounds/background-size-001.html:
  └ PASS [expected FAIL] background-size_percentage_normal

  ▶ Unexpected subtest result in /css/css-backgrounds/background-size-001.html:
  └ PASS [expected FAIL] background-size_percentage_max

  ▶ Unexpected subtest result in /css/css-backgrounds/background-size-001.html:
  │ FAIL [expected PASS] background-size_percentage_auto
  │   → assert_equals: background-size supporting value expected "50% auto" but got "50%"
  │ 
  │ @http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:119:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20
  │ test@http://web-platform.test:8000/resources/testharness.js:544:21
  └ @http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:118:9

  ▶ Unexpected subtest result in /css/css-backgrounds/background-size-001.html:
  │ FAIL [expected PASS] background-size_length_auto
  │   → assert_equals: background-size supporting value expected "15px auto" but got "15px"
  │ 
  │ @http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:101:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1594:20
  │ test@http://web-platform.test:8000/resources/testharness.js:544:21
  └ @http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:100:9

  ▶ Unexpected subtest result in /css/css-backgrounds/parsing/background-size-computed.html:
  └ PASS [expected FAIL] Property background-size value '1px' computes to '1px'

  ▶ Unexpected subtest result in /css/css-backgrounds/parsing/background-size-computed.html:
  └ PASS [expected FAIL] Property background-size value '1px auto' computes to '1px'
```

**Pull request merged**
