### PR TITLE
Add support for Visual Studio 2017

### PR DESCRIPTION
**Pull request by UK992**
This adds support for Visual Studio 2017.
Also need update cmake to 3.7.2.

r? @larsbergstrom 

Can you please upload [this cmake](https://www.dropbox.com/s/3b2z36jj4gh4qpk/cmake-3.7.2.zip?dl=0) to s3 bucket?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16307)

### CODE REVIEW

**Comment by Coder206** [comment]
@UK992 I was successful in building and running Servo with 3.8.0 downloaded from the CMake website as a binary.

**Comment by larsbergstrom** [comment]
Does this require an update to heartbeats? I tried it locally (and put an updated cmake in the s3 bucket), but got:
```
error: failed to run custom build command for `heartbeats-simple-sys v0.4.1`
process didn't exit successfully: `C:\Users\lars\code\servo\target\debug\build\heartbeats-simple-sys-bf7003c17df5d8c7\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\lars\\code\\servo\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\heartbeats-simple-sys-0.4.1/heartbeats-simple" "-G" "Visual Studio 15 Win64" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\lars\\code\\servo\\target\\debug\\build\\heartbeats-simple-sys-28376003c39ead8c\\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_C_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_BUILD_TYPE=Release"

--- stderr
CMake Error: Could not create named generator Visual Studio 15 Win64

Generators
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 8 2005 [arch]  = Generates Visual Studio 2005 project files.
                                 Optional [arch] can be "Win64".
```

**Comment by larsbergstrom** [comment]
Oh, duh, I needed to change `python/servo/packages.py` to `3.7.2`. Now fighting s3 permissions :-/

**Comment by larsbergstrom** [comment]
OK, just add that one change I mentioned (for the cmake version) and r=me. Thanks as always for all your Windows help!

**Comment by UK992** [comment]
Updated cmake and added checking for version of installed cmake to avoid using outdated cmake.

**Pull request merged**
