### PR TITLE
style: Rename MozLength to Size, and MaxLength to MaxSize.

### PR DESCRIPTION
**Pull request by emilio**
MozLength is not a very descriptive name. If we're going to use it in both Gecko
and Servo we may as well name it something more accurate.

I would've chosen `ContentSize` per CSS2[1][2] if it wasn't a lie in presence
of box-sizing. I don't have better ideas than `Size`, given that.

[1]: https://drafts.csswg.org/css2/visudet.html#propdef-width
[2]: https://drafts.csswg.org/css2/box.html#content-width

Differential Revision: https://phabricator.services.mozilla.com/D19280

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22864)

### CODE REVIEW

**Comment by CYBAI** [comment]
<details>

```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/floats-clear/clear-float-003.xht f32503616c3a3e2da646a25e933b2d711a695b2b\n/css/CSS2/floats-clear/clear-float-003-ref.xht 047458519bb75356f065de6692f8f70ccb025866\nTesting f32503616c3a3e2da646a25e933b2d711a695b2b == 047458519bb75356f065de6692f8f70ccb025866", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/floats-clear/clear-float-003.xht", 
    "line": 3488, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/floats-clear/margin-collapse-035.xht", 
    "line": 3971, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/floats-clear/margin-collapse-034.xht", 
    "line": 4038, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/floats-clear/margin-collapse-135.xht 7f1b9ed87de2596d4e6b32586179d3342276dade\n/css/CSS2/floats-clear/margin-collapse-135-ref.xht 45ab2fbc3b47fed65d441e8223ca0f3a341ba551\nTesting 7f1b9ed87de2596d4e6b32586179d3342276dade == 45ab2fbc3b47fed65d441e8223ca0f3a341ba551", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/floats-clear/margin-collapse-135.xht", 
    "line": 4438, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/floats-clear/margin-collapse-clear-014.xht", 
    "line": 4644, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-bottom-104.xht 5c13a7e429ad62330402007f06ace2736d30a897\n/css/CSS2/margin-padding-clear/margin-bottom-103-ref.xht 2e049a1c954577f415a4fd40687cc02b941277de\nTesting 5c13a7e429ad62330402007f06ace2736d30a897 == 2e049a1c954577f415a4fd40687cc02b941277de", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-bottom-104.xht", 
    "line": 7822, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-103.xht 770cfd1fc9f0411b571f59d9bcf7eb47b4007337\n/css/CSS2/margin-padding-clear/margin-collapse-103-ref.xht 7552ed9cf39a24a2186f222ca798883fa11aeea7\nTesting 770cfd1fc9f0411b571f59d9bcf7eb47b4007337 == 7552ed9cf39a24a2186f222ca798883fa11aeea7", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-103.xht", 
    "line": 7990, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-101.xht 6b9a898482c202065acd293d1ad3a4dc9aeeb342\n/css/CSS2/margin-padding-clear/margin-collapse-101-ref.xht 9fa45304fbf33e6250afd2b22b5eb8340abfa0d9\nTesting 6b9a898482c202065acd293d1ad3a4dc9aeeb342 == 9fa45304fbf33e6250afd2b22b5eb8340abfa0d9", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-101.xht", 
    "line": 8070, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-137.xht ac5d1af4402f7141a9c89d01bd454d82159d0716\n/css/CSS2/margin-padding-clear/margin-collapse-137-ref.xht 321e72483a2fb9ff55ce9d590052644894c09db7\nTesting ac5d1af4402f7141a9c89d01bd454d82159d0716 == 321e72483a2fb9ff55ce9d590052644894c09db7", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-137.xht", 
    "line": 8638, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-104.xht e5e4500d63cc4e3e954b7d265c1fabeca8bba48c\n/css/CSS2/reference/ref-filled-green-100px-square.xht d261ae08efbb2862baeb699cc2f5b449203e1e12\nTesting e5e4500d63cc4e3e954b7d265c1fabeca8bba48c == d261ae08efbb2862baeb699cc2f5b449203e1e12", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-104.xht", 
    "line": 8692, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-102.xht e5e4500d63cc4e3e954b7d265c1fabeca8bba48c\n/css/CSS2/reference/ref-filled-green-100px-square.xht d261ae08efbb2862baeb699cc2f5b449203e1e12\nTesting e5e4500d63cc4e3e954b7d265c1fabeca8bba48c == d261ae08efbb2862baeb699cc2f5b449203e1e12", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-102.xht", 
    "line": 8822, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-019.xht 5c18c7d2e7c4b5fd6e550e6efe06054792406a59\n/css/CSS2/margin-padding-clear/margin-collapse-002-ref.xht d357b89f8b27b99c6a699823208e6dd49499a346\nTesting 5c18c7d2e7c4b5fd6e550e6efe06054792406a59 == d357b89f8b27b99c6a699823208e6dd49499a346", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-019.xht", 
    "line": 9051, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-min-height-002.xht b0969cdb55a594ec1ae9a379a83e8990b6fc97ee\n/css/CSS2/margin-padding-clear/margin-collapse-min-height-002-ref.xht 842e4538667bc08edfda4516d1f1283adec85c80\nTesting b0969cdb55a594ec1ae9a379a83e8990b6fc97ee == 842e4538667bc08edfda4516d1f1283adec85c80", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-min-height-002.xht", 
    "line": 9069, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-115.xht 146c665a21c02f20631dd1727131ef15f8bc2ee7\n/css/CSS2/margin-padding-clear/margin-collapse-115-ref.xht f51b28da33af2c987e11c255c194eb9f7cb7c4d2\nTesting 146c665a21c02f20631dd1727131ef15f8bc2ee7 == f51b28da33af2c987e11c255c194eb9f7cb7c4d2", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-115.xht", 
    "line": 9076, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-bottom-103.xht 5c13a7e429ad62330402007f06ace2736d30a897\n/css/CSS2/margin-padding-clear/margin-bottom-103-ref.xht 2e049a1c954577f415a4fd40687cc02b941277de\nTesting 5c13a7e429ad62330402007f06ace2736d30a897 == 2e049a1c954577f415a4fd40687cc02b941277de", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-bottom-103.xht", 
    "line": 9085, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-111.xht 75406850718f79d127b617d2e8c3971073cecf03\n/css/CSS2/margin-padding-clear/margin-collapse-110-ref.xht 09dbbbf488013f7ffc80c70951b5353ce8954228\nTesting 75406850718f79d127b617d2e8c3971073cecf03 == 09dbbbf488013f7ffc80c70951b5353ce8954228", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-111.xht", 
    "line": 9140, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-155.xht b97adc69618b261d355dde877732331ebadeb99b\n/css/CSS2/margin-padding-clear/margin-collapse-155-ref.xht 91ec8cb2e19bcaa1acd44bce1b106deff3b72f7f\nTesting b97adc69618b261d355dde877732331ebadeb99b == 91ec8cb2e19bcaa1acd44bce1b106deff3b72f7f", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-155.xht", 
    "line": 9411, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-105.xht 6b9a898482c202065acd293d1ad3a4dc9aeeb342\n/css/CSS2/margin-padding-clear/margin-collapse-101-ref.xht 9fa45304fbf33e6250afd2b22b5eb8340abfa0d9\nTesting 6b9a898482c202065acd293d1ad3a4dc9aeeb342 == 9fa45304fbf33e6250afd2b22b5eb8340abfa0d9", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-105.xht", 
    "line": 9445, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-138.xht ac5d1af4402f7141a9c89d01bd454d82159d0716\n/css/CSS2/margin-padding-clear/margin-collapse-137-ref.xht 321e72483a2fb9ff55ce9d590052644894c09db7\nTesting ac5d1af4402f7141a9c89d01bd454d82159d0716 == 321e72483a2fb9ff55ce9d590052644894c09db7", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-138.xht", 
    "line": 9609, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-026.xht 5c18c7d2e7c4b5fd6e550e6efe06054792406a59\n/css/CSS2/margin-padding-clear/margin-collapse-002-ref.xht d357b89f8b27b99c6a699823208e6dd49499a346\nTesting 5c18c7d2e7c4b5fd6e550e6efe06054792406a59 == d357b89f8b27b99c6a699823208e6dd49499a346", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-026.xht", 
    "line": 9977, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/normal-flow/margin-collapse-through-zero-height-block.html f2c19798b83bc3966dd555b76c0de4cf2564283b\n/css/reference/ref-filled-green-200px-square.html 664089d27690bf612b86e48886fd776b3720aeae\nTesting f2c19798b83bc3966dd555b76c0de4cf2564283b == 664089d27690bf612b86e48886fd776b3720aeae", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/normal-flow/margin-collapse-through-zero-height-block.html", 
    "line": 13485, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/positioning/abspos-022.xht e8355ebafb214ab35e4dea88f7780b23ce5b58c0\n/css/CSS2/positioning/abspos-013-ref.xht 7696da56a5cc10ea3a92bcb4cba295169040ac34\nTesting e8355ebafb214ab35e4dea88f7780b23ce5b58c0 == 7696da56a5cc10ea3a92bcb4cba295169040ac34", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/positioning/abspos-022.xht", 
    "line": 17332, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/_mozilla/css/transform_skew_a.html", 
    "line": 37162, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/floats-clear/margin-collapse-clear-017.xht e469e51828c07ab1316b205df3257807997c8d43\n/css/CSS2/floats-clear/margin-collapse-clear-017-ref.xht 87c66311e0d492367c6a99bf1ea797174a5e5078\nTesting e469e51828c07ab1316b205df3257807997c8d43 == 87c66311e0d492367c6a99bf1ea797174a5e5078", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/floats-clear/margin-collapse-clear-017.xht", 
    "line": 38072, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/floats-clear/margin-collapse-clear-016.xht 715b8b72a2dc00710b6aaebee2ae1c9ecb848058\n/css/CSS2/floats-clear/margin-collapse-clear-016-ref.xht 74f2a5a516898ad3c02a4bf913a8283c007f8381\nTesting 715b8b72a2dc00710b6aaebee2ae1c9ecb848058 == 74f2a5a516898ad3c02a4bf913a8283c007f8381", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/floats-clear/margin-collapse-clear-016.xht", 
    "line": 39368, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/floats-clear/margin-collapse-033.xht", 
    "line": 39682, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-116.xht c6d247467a229fdc82f24f6eaf1e4e92c0aac11e\n/css/CSS2/margin-padding-clear/margin-collapse-115-ref.xht f51b28da33af2c987e11c255c194eb9f7cb7c4d2\nTesting c6d247467a229fdc82f24f6eaf1e4e92c0aac11e == f51b28da33af2c987e11c255c194eb9f7cb7c4d2", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-116.xht", 
    "line": 40957, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/margin-padding-clear/margin-collapse-016.xht 5c18c7d2e7c4b5fd6e550e6efe06054792406a59\n/css/CSS2/margin-padding-clear/margin-collapse-002-ref.xht d357b89f8b27b99c6a699823208e6dd49499a346\nTesting 5c18c7d2e7c4b5fd6e550e6efe06054792406a59 == d357b89f8b27b99c6a699823208e6dd49499a346", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/margin-padding-clear/margin-collapse-016.xht", 
    "line": 41480, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Computed min-width/min-height of specified auto for flex item.", 
    "test": "/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-auto-size.html", 
    "line": 64270, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: expected \"0px\" but got \"auto\"", 
    "stack": "@http://web-platform.test:8000/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-auto-size.html:44:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1587:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\n@http://web-platform.test:8000/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-auto-size.html:43:5\n", 
    "subtest": "Computed min-width/min-height of specified auto inside display:none which would otherwise have been a flex item.", 
    "test": "/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-auto-size.html", 
    "line": 64271, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Computed min-width/min-height of specified auto for flex item inside display:contents.", 
    "test": "/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-auto-size.html", 
    "line": 64272, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: expected \"0px\" but got \"auto\"", 
    "stack": "@http://web-platform.test:8000/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-auto-size.html:44:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1587:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\n@http://web-platform.test:8000/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-auto-size.html:43:5\n", 
    "subtest": "Computed min-width/min-height of specified auto with display:none which would otherwise have been a flex item.", 
    "test": "/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-auto-size.html", 
    "line": 64273, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "flexbox | computed style | min-height: auto", 
    "test": "/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-height-auto.html", 
    "line": 142924, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "flexbox | computed style | min-width: auto", 
    "test": "/css/css-flexbox/getcomputedstyle/flexbox_computedstyle_min-width-auto.html", 
    "line": 174126, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

</details>

**Comment by emilio** [comment]
Thanks @CYBAI! I fixed the margin collapsing issues and updated the other expectations, which are expected because we changed the initial value of the `min-*` properties to be `auto`.

@bors-servo r+

**Comment by emilio** [comment]
Aand rustfmt.

@bors-servo r+

**Comment by emilio** [comment]
Gah, missed one more unexpected pass.

@bors-servo r+

**Pull request merged**
