### PR TITLE
Fix canvas arc path WPT test failures

### LINKED ISSUE #25331: Fix WPT test failures induced by switching 2D canvas rendering backend to Raqote
#24470 left over some failing tests, which need to be addressed.

Relevant tests: `tests/wpt/web-platform-tests/2dcontext/`

### PR DESCRIPTION
**Pull request by pylbrecht**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #25331 (GitHub issue number if applicable)

- [x] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.arcTo.ensuresubpath.2.worker.html:
  └ PASS [expected FAIL] If there is no subpath, the first control point is added
```

**Comment by pylbrecht** [comment]
Sorry, missed that file.

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
