### PR TITLE
Return None as style for elements not in a document

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6851)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r-
I'm not convinced that we've decided what to do here, given the IRC conversation. This is web-compatibility land.

**Comment by jdm** [comment]
Relevant log: http://logs.glob.uno/?c=mozilla%23servo#c248309

**Comment by dzbarsky** [comment]
For this testcase, we will now report "". This matches Chrome and Safari, so it should be web-compatible.
```
var foo = document.createElement('div');
foo.style.setPropertyValue('left', '15px');
alert(getComputedStyle(foo).getPropertyValue('left'));
```

**Comment by pcwalton** [comment]
Can we move forward here? This is causing a lot of crashes.

**Comment by jdm** [comment]
Filed #6860 about the uncertainty here.

**Pull request merged**
