### PR TITLE
 Register a glwindow test XR device 

### PR DESCRIPTION
**Pull request by asajeffrey**
Registers a test WebXR device with the glutin port.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because it's webxr plumbing

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23721)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Blocked on https://github.com/servo/webxr/pull/6

The first commit is #23720.

**Comment by Manishearth** [comment]
@bors-servo r+

dom.webxr.test is for the mock API, fwiw. we can add a mock endpoint to glwindow, though

**Comment by asajeffrey** [comment]
Rebased and updated webxr crates. @bors-servo r=Manishearth

**Pull request merged**
