### PR TITLE
remove no-op InitializeCompositing message

### PR DESCRIPTION
**Pull request by paulrouget**
I think this is no-op.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17685)

### CODE REVIEW

**Comment by jdm** [comment]
```
   Compiling embedding v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/ports/cef)
error[E0599]: no associated item named `InitializeCompositing` found for type `compositing::windowing::WindowEvent` in the current scope
   --> browser_host.rs:490:47
    |
490 |             this.downcast().send_window_event(WindowEvent::InitializeCompositing);
    |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `embedding`.
```

**Comment by paulrouget** [comment]
Fixed the cef building issue.

**Pull request merged**
