### PR TITLE
Add some documentation to the style crate.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11834)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r=me with one additional URL

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/values.rs, line 5 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11834#-KLHP3eKGUcHcdfSnsge:-KLHP3eLXCY9lmFNisI8:1587912330) ([raw file](https://github.com/servo/servo/blob/1bb3a7ee0a59e44418d173375baf48fbcb14d824/components/style/values.rs#L5)):*
> ```Rust
>  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
> 
> //! Common values used in CSS.
> ```

Maybe link to https://drafts.csswg.org/css-values/ ? This Rust module and spec module don’t map 1:1, but they have a lot of overlap.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11834#-:-KLHPLjcX8WbgZLm7oOf:-992875598)*

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11574

**Comment by jdm** [comment]
@bors-servo: retry
* #11859

**Pull request merged**
