### PR TITLE
Avoid decoding XHR type="json" responses as UTF-16BE/LE

### PR DESCRIPTION
**Pull request by hsivonen**
https://infra.spec.whatwg.org/#parse-json-from-bytes says to use
"UTF-8 decode" rather than "decode", so UTF-16BE/LE BOM should
not be honored.

CC @SimonSapin 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19096)

### CODE REVIEW

**Comment by avadacatavra** [comment]
This looks good to me  -- could you add a comment linking to the spec you mentioned with your changes?

**Comment by hsivonen** [comment]
Thanks. Added a comment.

**Comment by avadacatavra** [comment]
Great! All this needs is a squash and I'll approve it -- let me know if you need any help with the squash

**Pull request merged**
