### PR TITLE
Support font-family in geckolib

### PR DESCRIPTION
**Pull request by mbrubeck**
r? @heycam

Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1278647

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11667)

### CODE REVIEW

**Comment by heycam** [comment]
Looks good, but did you forget to add the structs.rs changes?

**Comment by emilio** [comment]
@heycam: The corresponding enums seem to be already generated before this patch, so they only needed to be `use`d from `bindings.rs`.

Also LGTM modulo those nits.

<details><summary><i>Previously, heycam (Cameron McCormack) wrote…</i></summary>
> Looks good, but did you forget to add the structs.rs changes?
</details>


---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[ports/geckolib/properties.mako.rs, line 618 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11667#-KJhf23HK8vWz6nUDPRn:-KJhf23HK8vWz6nUDPRo:-1264211949) ([raw file](https://github.com/servo/servo/blob/944d97ece26fff9b8dfe68f07eb5e48e5c1dfe80/ports/geckolib/properties.mako.rs#L618)):*
> ```Rust
>         for (i, family) in v.0.iter().enumerate() {
>             let list = &mut self.gecko.mFont.fontlist;
>             match family {
> ```

nit: I kind of prefer matching against the dereference instead of the ref itself (i.e. `match *family`), but feel free to keep it.

---

*[ports/geckolib/properties.mako.rs, line 623 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11667#-KJhfB0OnwnpuY7dRuhV:-KJhfB0PsCYtZaP2zeyi:-1244634025) ([raw file](https://github.com/servo/servo/blob/944d97ece26fff9b8dfe68f07eb5e48e5c1dfe80/ports/geckolib/properties.mako.rs#L623)):*
> ```Rust
>                 }
>                 &FontFamily::Generic(ref name) => {
>                     let family_type =
> ```

Maybe this could be something like:

```rust
match *name {
    atom!("serif") => FontFamilyType::eFamily_serif,
    //...
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11667#-:-KJhfVhL2sMTICYIhkmw:-1489395777)*

**Comment by mbrubeck** [comment]
Addressed review comments, removed a leftover unused variable, and added a call to FontFamilyList::Clear which was necessary to make this actually work in my test cases.

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[ports/geckolib/properties.mako.rs, line 618 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11667#-KJhf23HK8vWz6nUDPRn:-KJlkuITBgYQIekUai0m:-499146009) ([raw file](https://github.com/servo/servo/blob/944d97ece26fff9b8dfe68f07eb5e48e5c1dfe80/ports/geckolib/properties.mako.rs#L618)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> nit: I kind of prefer matching against the dereference instead of the ref itself (i.e. `match *family`), but feel free to keep it.
</details>
Done.

---

*[ports/geckolib/properties.mako.rs, line 623 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11667#-KJhfB0OnwnpuY7dRuhV:-KJlkvJY6ddeaxy1HHWb:-1072338522) ([raw file](https://github.com/servo/servo/blob/944d97ece26fff9b8dfe68f07eb5e48e5c1dfe80/ports/geckolib/properties.mako.rs#L623)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> Maybe this could be something like:
> 
> ```rust
> match *name {
>     atom!("serif") => FontFamilyType::eFamily_serif,
>     //...
> }
> ```
</details>
I couldn't do this because `atom!` expands to something that isn't a valid pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11667#-:-KJll0t_6U7zcuRvH3Ri:634781805)*

**Pull request merged**
