### PR TITLE
Move PaintMsg enum to gfx_traits #8844

### PR DESCRIPTION
**Pull request by mskrzypkows**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9007)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Unfortunately, this conflicts with #8612, which has precedence. Could you rebase once that has landed?

**Comment by mskrzypkows** [comment]
OK, I'll wait for that patch.

**Comment by mskrzypkows** [comment]
It's strange, There was no check for PaintMsg::Ready and it compiled. Now there is error: components/compositing/constellation.rs:494:9: 698:10 error: non-exhaustive patterns: `Paint(Ready(_))` not covered [E0004]

**Comment by jdm** [comment]
Looks like Ready doesn't exist on master: https://github.com/servo/servo/pull/9007/files#diff-8dc9268416cd4f037d50206e76c73cf9L247

**Comment by mskrzypkows** [comment]
Oh, that's right! Thanks

**Comment by mskrzypkows** [comment]
Corrected, please retry.

**Comment by Manishearth** [comment]
moved to https://github.com/servo/servo/pull/9007

**Pull request closed without merging**
