### PR TITLE
Upgrade rust to 716f920b7e234b450f272346fea961832505c06e

### PR DESCRIPTION
**Pull request by mbrubeck**
(Tue May 19 05:39:29 2015 +0000)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6151)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Review status: 3 of 7 files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/plugins/jstraceable.rs @ r1
- components/plugins/lib.rs @ r1
- tests/reftest.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6151)

**Comment by larsbergstrom** [comment]
Review status: 4 of 7 files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- rust-snapshot-hash @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6151)

**Comment by larsbergstrom** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/servo/Cargo.lock @ r1
- ports/cef/Cargo.lock @ r1
- ports/gonk/Cargo.lock @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6151)

**Pull request merged**
