### PR TITLE
style: Add infra to differentiate chrome and UA sheets.

### PR DESCRIPTION
**Pull request by emilio**
This keeps the behavior of stuff being accessible from chrome stylesheets being
the same of content sheets except on the UA origin. That will be changed in a
followup.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19235)

### CODE REVIEW

**Review by upsuper — DISMISSED** [review]

**Comment by emilio** [comment]
Ok, I rewrote the thing and I'm more happy about the logic here now.

r? @upsuper

**Comment by upsuper** [comment]
Reviewed 3 of 3 files at r2, 6 of 6 files at r3, 16 of 16 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[components/style/properties/properties.mako.rs, line 1301 at r7](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1xJsvXpbrVR3JHEzo:-Kz1xJsvXpbrVR3JHEzp:bvsr856) ([raw file](https://github.com/servo/servo/blob/8e5703e089f69380f19ba2ec9de2bdedb6d7ddeb/components/style/properties/properties.mako.rs#L1301)):*
Do you think the following explanation makes things clearer?
> Experimental properties are generally controlled by prefs, but an experimental properties explicitly enabled in certain context (UA sheets / chrome sheets) are always usable in the context regardless of pref.
> Non-experimental properties are either normal properties which are usable everywhere, or internal-only properties which are only usable in certain context they are explicitly enabled in.

---

*[components/style/properties/properties.mako.rs, line 1305 at r7](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1t5DwAbSEDsy22AO4:-Kz1t5DwAbSEDsy22AO5:b-8mbm8u) ([raw file](https://github.com/servo/servo/blob/8e5703e089f69380f19ba2ec9de2bdedb6d7ddeb/components/style/properties/properties.mako.rs#L1305)):*
> ```Rust
>         // TODO(emilio): This is kinda messy, and makes the common path be
>         // slower than what it needs to be, should we add at least a fast-path
>         // for public, non-experimental properties?
> ```

Since you have added the fast path, this comment seems no longer relevant?

---

*[components/style/properties/properties.mako.rs, line 1309 at r7](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1qfVd_cVvDVDPIYwJ:-Kz1qfVd_cVvDVDPIYwK:b2yezxp) ([raw file](https://github.com/servo/servo/blob/8e5703e089f69380f19ba2ec9de2bdedb6d7ddeb/components/style/properties/properties.mako.rs#L1309)):*
> ```Rust
>         ${id_set("ENABLED_IN_CHROME", lambda p: p.explicitly_enabled_in_chrome())}
>         ${id_set("EXPERIMENTAL", lambda p: p.experimental(product))}
>         ${id_set("ALWAYS_ENABLED", lambda p: not p.experimental(product) and not p.explicitly_enabled_in_ua_sheets())}
> ```

I'm wondering whether we should instead collapse the three sets above into an array of three-bit-items, so that we have better locality (and a slightly smaller codesize). But I guess if we have a fast path, the slow path probably doesn't matter that much...

---

*[components/style/properties/properties.mako.rs, line 1351 at r7](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1qW4Ih5IbdeZtnu7d:-Kz1qW4Ih5IbdeZtnu7e:b36p2r6) ([raw file](https://github.com/servo/servo/blob/8e5703e089f69380f19ba2ec9de2bdedb6d7ddeb/components/style/properties/properties.mako.rs#L1351)):*
> ```Rust
> 
>         if EXPERIMENTAL.contains(id) {
>             return passes_pref_check();
> ```

This is incorrect. It should be
```rust
if EXPERIMENTAL.contains(id) && passes_pref_check() {
  return Ok(());
}
```
and thus your change to `passes_pref_check` doesn't seem to be useful.

---

*[components/style/properties/longhand/box.mako.rs, line 912 at r4](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1pUoOmbz4gLUjPe-P:-Kz1pUoOmbz4gLUjPe-Q:bfw9jjp) ([raw file](https://github.com/servo/servo/blob/187d28c732a4b9929294fd90d4d9f5f020e6276b/components/style/properties/longhand/box.mako.rs#L912)):*
> ```Rust
> )}
> 
> <%helpers:longhand name="touch-action"
> ```

This seems to be controlled by "layout.css.touch_action.enabled".

---

*[components/style/properties/longhand/column.mako.rs, line 65 at r4](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1olSx5BkWJdwGCkyV:-Kz1olSx5BkWJdwGCkyW:bgoisg) ([raw file](https://github.com/servo/servo/blob/187d28c732a4b9929294fd90d4d9f5f020e6276b/components/style/properties/longhand/column.mako.rs#L65)):*
> ```Rust
> ${helpers.single_keyword("column-span", "none all",
>                          products="gecko", animation_value_type="discrete",
>                          gecko_pref="layout.css.color-adjust.enabled",
> ```

This should be "layout.css.column-span.enabled". You should put this pref to `color-adjust`.

---

*[components/style/properties/shorthand/box.mako.rs, line 331 at r4](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1kAAtJsnsPXZRxrpH:-Kz1kAAuhC1a_rwr_QKf:bfuh7yt) ([raw file](https://github.com/servo/servo/blob/9863d514512aabbcfaeabba7e530b87f61a8d489/components/style/properties/shorthand/box.mako.rs#L331)):*
> layout.css.scroll-snap.enabled

---

*[components/style/properties/shorthand/column.mako.rs, line 9 at r3](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1ik2kkW5HuBPnkqvb:-Kz1ik2lA3GfBu5cJkV9:bhkl7av) ([raw file](https://github.com/servo/servo/blob/f4683d17184baf9e201be68f36876ac72e1d2542/components/style/properties/shorthand/column.mako.rs#L9)):*
> ```Rust
> <%helpers:shorthand name="columns"
>                     sub_properties="column-width column-count"
>                     servo_pref="layout.columns.enabled",
> ```

So you can specify a specific pref now, I guess it makes sense to use the same pref for all the columns-related properties. It's not a big deal though, and can be done in a separate PR.

---

*[components/style/properties/shorthand/position.mako.rs, line 105 at r4](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1o6YmXBSaCWJgv9Xp:-Kz1o6YmXBSaCWJgv9Xq:b-yujeky) ([raw file](https://github.com/servo/servo/blob/187d28c732a4b9929294fd90d4d9f5f020e6276b/components/style/properties/shorthand/position.mako.rs#L105)):*
> ```Rust
> </%helpers:shorthand>
> 
> <%helpers:shorthand name="grid-gap" sub_properties="grid-row-gap grid-column-gap"
> ```

This and the following 4 shorthands are also controlled by "layout.css.grid.enabled".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19235)*

**Comment by emilio** [comment]
Review status: 14 of 19 files reviewed at latest revision, 10 unresolved discussions.

---

*[components/style/properties/properties.mako.rs, line 1301 at r7](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1xJsvXpbrVR3JHEzo:-Kz40uhX4341OMvUdCDM:b-87u3pi) ([raw file](https://github.com/servo/servo/blob/8e5703e089f69380f19ba2ec9de2bdedb6d7ddeb/components/style/properties/properties.mako.rs#L1301)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Do you think the following explanation makes things clearer?
> Experimental properties are generally controlled by prefs, but an experimental properties explicitly enabled in certain context (UA sheets / chrome sheets) are always usable in the context regardless of pref.
> Non-experimental properties are either normal properties which are usable everywhere, or internal-only properties which are only usable in certain context they are explicitly enabled in.
</blockquote></details>

I do!

---

*[components/style/properties/properties.mako.rs, line 1305 at r7](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1t5DwAbSEDsy22AO4:-Kz40vlPYUFqhjyijIev:bqog80t) ([raw file](https://github.com/servo/servo/blob/8e5703e089f69380f19ba2ec9de2bdedb6d7ddeb/components/style/properties/properties.mako.rs#L1305)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Since you have added the fast path, this comment seems no longer relevant?
</blockquote></details>

Agreed

---

*[components/style/properties/properties.mako.rs, line 1309 at r7](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1qfVd_cVvDVDPIYwJ:-Kz40xMEjxy1KPvah8b7:baulm2w) ([raw file](https://github.com/servo/servo/blob/8e5703e089f69380f19ba2ec9de2bdedb6d7ddeb/components/style/properties/properties.mako.rs#L1309)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

I'm wondering whether we should instead collapse the three sets above into an array of three-bit-items, so that we have better locality (and a slightly smaller codesize). But I guess if we have a fast path, the slow path probably doesn't matter that much...
</blockquote></details>

Yeah, we could do that, but I didn't think it mattered enough compared to making it readable, and it's rare to end up looking in all of them anyway.

---

*[components/style/properties/properties.mako.rs, line 1351 at r7](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1qW4Ih5IbdeZtnu7d:-Kz419DSqM-szlyck9Fj:bryfuiz) ([raw file](https://github.com/servo/servo/blob/8e5703e089f69380f19ba2ec9de2bdedb6d7ddeb/components/style/properties/properties.mako.rs#L1351)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This is incorrect. It should be
```rust
if EXPERIMENTAL.contains(id) && passes_pref_check() {
  return Ok(());
}
```
and thus your change to `passes_pref_check` doesn't seem to be useful.
</blockquote></details>

Right, nice catch.

---

*[components/style/properties/longhand/box.mako.rs, line 912 at r4](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1pUoOmbz4gLUjPe-P:-Kz41VvQo4WmtzKM4GML:bw2igzy) ([raw file](https://github.com/servo/servo/blob/187d28c732a4b9929294fd90d4d9f5f020e6276b/components/style/properties/longhand/box.mako.rs#L912)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This seems to be controlled by "layout.css.touch_action.enabled".
</blockquote></details>

D'oh, I missed that.

---

*[components/style/properties/longhand/column.mako.rs, line 65 at r4](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1olSx5BkWJdwGCkyV:-Kz41YEG_lsc7ce51rYp:bvvpikx) ([raw file](https://github.com/servo/servo/blob/187d28c732a4b9929294fd90d4d9f5f020e6276b/components/style/properties/longhand/column.mako.rs#L65)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This should be "layout.css.column-span.enabled". You should put this pref to `color-adjust`.
</blockquote></details>

Yup. color-adjust already had it fwiw

---

*[components/style/properties/shorthand/box.mako.rs, line 331 at r4](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1kAAtJsnsPXZRxrpH:-Kz41eiQAqmLoaWi77Cp:b48pchp) ([raw file](https://github.com/servo/servo/blob/9863d514512aabbcfaeabba7e530b87f61a8d489/components/style/properties/shorthand/box.mako.rs#L331)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

> layout.css.scroll-snap.enabled
</blockquote></details>

I don't understand this comment, that pref is already there.

---

*[components/style/properties/shorthand/column.mako.rs, line 9 at r3](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1ik2kkW5HuBPnkqvb:-Kz420cDsUcgaWOebnzD:bqfm9k2) ([raw file](https://github.com/servo/servo/blob/f4683d17184baf9e201be68f36876ac72e1d2542/components/style/properties/shorthand/column.mako.rs#L9)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

So you can specify a specific pref now, I guess it makes sense to use the same pref for all the columns-related properties. It's not a big deal though, and can be done in a separate PR.
</blockquote></details>

Yeah, but I didn't want to bother changing the test manifest files for now.

---

*[components/style/properties/shorthand/position.mako.rs, line 105 at r4](https://reviewable.io:443/reviews/servo/servo/19235#-Kz1o6YmXBSaCWJgv9Xp:-Kz424VjeSFsnRFjkkdo:bcqlarf) ([raw file](https://github.com/servo/servo/blob/187d28c732a4b9929294fd90d4d9f5f020e6276b/components/style/properties/shorthand/position.mako.rs#L105)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

This and the following 4 shorthands are also controlled by "layout.css.grid.enabled".
</blockquote></details>

Yup, nice catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19235)*

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css/css-text/overflow-wrap/word-wrap-001.html
  └   → /css/css-text/overflow-wrap/word-wrap-001.html 5959a21d114a114a65365ca839b0898f4023c809
/css/css-text/overflow-wrap/overflow-wrap-001-ref.html 406a112948e57196ff43de00d916e0bf3626e151
Testing 5959a21d114a114a65365ca839b0898f4023c809 == 406a112948e57196ff43de00d916e0bf3626e151

  ▶ FAIL [expected PASS] /css/css-text/overflow-wrap/word-wrap-002.html
  └   → /css/css-text/overflow-wrap/word-wrap-002.html cd2505ad6a1cfa022cdaab05595a0a6950f0d898
/css/css-text/overflow-wrap/overflow-wrap-002-ref.html 0fc792d972ffd53ca1fa30ba873b3d6f91346c2f
Testing cd2505ad6a1cfa022cdaab05595a0a6950f0d898 == 0fc792d972ffd53ca1fa30ba873b3d6f91346c2f

  ▶ FAIL [expected PASS] /_mozilla/css/overflow_wrap_a.html
  └   → /_mozilla/css/overflow_wrap_a.html b176ee8b296be720b73762103ad634f54109488e
/_mozilla/css/overflow_wrap_ref.html aa59b6aaebca0803219975377c889eb5833a4e14
Testing b176ee8b296be720b73762103ad634f54109488e == aa59b6aaebca0803219975377c889eb5833a4e14
```

**Comment by emilio** [comment]
@bors-servo r=xidorn

Alias weren't getting accounted for in `non_custom_property_id_set`.

**Pull request merged**
