### PR TITLE
[DO NOT MERGE] Let's see how badly things break with text AA enabled for tests...

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17899)

### CODE REVIEW

**Comment by glennw** [comment]
@bors-servo try

Doing an experiment to see what / how much breaks with AA enabled on text during CI tests.

**Comment by nox** [comment]
@bors-servo retry

The logs are not available anymore and I'm curious.

**Comment by glennw** [comment]
Closing for now - I'll reopen when I have more time to work on this.

**Pull request closed without merging**
