### PR TITLE
generate unions from Typdefs inner type

### LINKED ISSUE #10605: Typdefs are not generated in unions
Suppose I have the following:
```webidl
typedef (A or B or C) Foo;

DOMString bar(Foo or DOMString? qux);
```

The codegen currently does not generate `FooOrString` as expected - it would instead generate `AorBorCorDOMString`, and ignoring the typedef altogether.

### PR DESCRIPTION
**Pull request by amarant**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #10605 (github issue number if applicable).

Either:
- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

It replace PR #10615 and keeps the type hierarchy with typedef.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11203)

### CODE REVIEW

**Comment by jdm** [comment]
`./mach test-tidy` reports errors and `./mach build` throws an exception the WebIDL parser. I'm going to hold off reviewing these changes until those are fixed.

**Comment by amarant** [comment]
I'm stupid, I didn't commited the tidiness changes.

**Comment by KiChjang** [comment]
This still doesn't compile.

**Comment by amarant** [comment]
I don't understand it now, it compiles on my box, I also made clean and recompiled it in debug and release, and my git status says it's clean.

**Comment by amarant** [comment]
The error seems to be that a type of an typdef union is not defined, so it probably come from my test : Blob or HTMLElement or FormData

**Comment by jdm** [comment]
Huh. I wonder if there's some python caching happening on travis that isn't in local builds for some reason...

**Comment by amarant** [comment]
I've put up my travis and removed the cache dirs and it doesn't fix it, it seems Blob is unresolved : '<unresolved scope>::Blob'.

**Comment by jdm** [comment]
I also can't reproduce the build failure locally. This is really annoying!

**Comment by jdm** [comment]
The fact that there are changes to WebIDL.py and that's the file that's complaining is suspicious to me. Why are the changes to that file necessary?

**Comment by amarant** [comment]
WebIDL.py changes are used to change the way IDLUnionType are flattened, it no longer do a deep flatten but stop at IDLTypedefType.

**Comment by amarant** [comment]
I just installed ubuntu and could reproduce it, so I will look into it.

**Comment by KiChjang** [comment]
@amarant What's the status here?

**Comment by KiChjang** [comment]
@amarant Is this still being worked on?

**Comment by Scorpil** [comment]
As per IRC chat with @KiChjang , I'll try to drive this forward, as it blocks #10604 and #12341.

**Comment by KiChjang** [comment]
Closing in favour of #12397.

**Pull request closed without merging**
