### PR TITLE
build: upgrade rustc to 1.81.0

### PR DESCRIPTION
**Pull request by mukilan**
I [tried to upgrade to 1.82.0][1], but there were a handful of new clippy
warnings that can't be fixed using `cargo clippy --fix`. The try run also
showed unit test failures related to crown lints.

Hence, this PR only gets us to 1.81.0 for now.

[1]: https://github.com/mukilan/servo/actions/runs/11886069630

Signed-off-by: Mukilan Thiyagarajan <mukilan@igalia.com>

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by sagudev** [comment]
The problem is that for compile-fail tests rustc now returns exit code 101 instead of 1.

**Comment by sagudev** [comment]
> > Should rust-version in Cargo.toml be updated as well?
> 
> Good catch! I'll update that one as well.
> 
> > The problem is that for compile-fail tests rustc now returns exit code 101 instead of 1.
> 
> Yep, I was looking at this yesterday. There are no reported issues in [compiletest-rs](https://github.com/Manishearth/compiletest-rs). Should we just create an issue and block on that, or is there a way to override things in crown?

I tried overriding but it didn't work. cc @Manishearth who might know what's going on. Workaround would be to change compile-fail test to ui tests, but let's wait with that. I will check klint in the meantime.

**Comment by sagudev** [comment]
Klint also returns 101 if run manually, but because it uses UI test they have no problem with testing, so either we both use rustc_driver wrong or compile_test should be updated to accept 101 as status error.

**Comment by mukilan** [comment]
Should we move to UI tests  (I can do that) or wait till compiletest_rs addresses the error? Are there any drawbacks to using UI tests? I guess we will have additional work like checking-in the stdout and stderr files.

**Comment by sagudev** [comment]
> Should we move to UI tests (I can do that) or wait till compiletest_rs addresses the error? Are there any drawbacks to using UI tests? I guess we will have additional work like checking-in the stdout and stderr files.

I think we should wait as this is not our error.

UI test are not really for checking that correct error is triggered, but for checking all rustc output (all warnings and errors). This is used in rustc to test that error and warnings are sexy (and to check for suggestions and multi span errors).

**Comment by jschwe** [comment]
So if I understand correctly someone would need to make a PR to adjust [this expected errorcode](https://github.com/Manishearth/compiletest-rs/blob/cb121796a041255ae0afcd9c2766bee4ebfd54f0/src/runtest.rs#L233) and make it depend on the rust version?

**Comment by sagudev** [comment]
> So if I understand correctly someone would need to make a PR to adjust [this expected errorcode](https://github.com/Manishearth/compiletest-rs/blob/cb121796a041255ae0afcd9c2766bee4ebfd54f0/src/runtest.rs#L233) and make it depend on the rust version?

Generally yes, but we need to be sure that this is also correct and not just misunderstanding situation. I tried to manually find commit in rust that changed the behavior, but I was not successful, I plan to do bisect sometime.

**Comment by sagudev** [comment]
[Bisect](https://github.com/sagudev/crown-bisect/actions/runs/12030895296/job/33539267492) says it's https://github.com/rust-lang/rust/commit/c2d2bb38c9067d983d13505c47e761308b1694db.

**Comment by sagudev** [comment]
Yeah, the commit that did this is https://github.com/rust-lang/rust/pull/126834/commits/e3ffbbd2263059fd7d11881540c214aeb000a7d3, basically rustc now aborts/panics which maps to exit code 101.

I do not think this solution is applicable to us because we run compiler using https://github.com/servo/servo/blob/63793ccbb7c0768af3f31c274df70625abacb508/support/crown/src/main.rs#L69 I wonder why rustc errors still pass in compiletest-rs.

**Comment by jschwe** [comment]
>  I wonder why rustc errors still pass in compiletest-rs.

It seems that normal rustc errors are still error code 1.  Perhaps this change only affects linters?

**Comment by jschwe** [comment]
With https://github.com/Manishearth/compiletest-rs/pull/296 and this patch, the crown compile-fail tests are passing for me again.

```patch
Index: support/crown/tests/compile_test.rs
===================================================================
diff --git a/support/crown/tests/compile_test.rs b/support/crown/tests/compile_test.rs
--- a/support/crown/tests/compile_test.rs	(revision 428560726653b8acefcff02b46ba42b83c3ea0f6)
+++ b/support/crown/tests/compile_test.rs	(revision e0deaeae6ad83599974232e0cbd3d747d07fc3b8)
@@ -35,6 +35,7 @@
     // Does not work reliably: https://github.com/servo/servo/pull/30508#issuecomment-1834542203
     //config.link_deps();
     config.strict_headers = true;
+    config.compile_test_exit_code = Some(101);
 
     compiletest::run_tests(&config);
 }
```

**Comment by mukilan** [comment]
This is now ready for review.

**Review by jdm — APPROVED** [review]

**Review by jschwe — APPROVED** [review]

**Review by sagudev — APPROVED** [review]

**Pull request merged**
