### PR TITLE
Add timeline markers for HTTP requests, JS evaluation, and HTML parsing.

### LINKED ISSUE #11218: Profiling Parsing
Ideally we'd like to know how much time Servo spends in its pipeline stages. Currently we have profiling set up for Styling, Primary Layout Passes, Compositing, Painting and Image Saving. We'd like to get profiling numbers in stages like Parsing, Javascript and resource fetching (network). This issue is focusing only on profiling Parsing. Although some profiling code in script_thread.rs exists, it cannot be used along with the existing -p option. The -profile-script-tasks debug option needs to be used by itself. Also, among the tasks being profiled within script_thread.rs, Parsing doesn't seem to be profiled. The profiling in script_thread.rs is being done slightly differently than how profiling for styling, layout, etc. is being done. Let me know if you have ideas about how to go about doing this. I'll keep hacking around as well :)

### PR DESCRIPTION
**Pull request by jdm**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [ ] `./mach build -d` does not report any errors (didn't try to compile past a rustc upgrade on airplane wifi)
- [X] `./mach test-tidy --faster` does not report any errors
- [X] These changes fix #11218 (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because we don't have testing infrastructure for profiling.

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11239)

### CODE REVIEW

**Comment by jdm** [comment]
cc @rzambre

**Comment by jdm** [comment]
JS evaluation doesn't include JS callbacks right now (eg: event listeners), since it was more complicated than the rest of the bits in this PR.

**Comment by jdm** [comment]
@bors-servo: r-
Unit tests.

**Comment by rzambre** [comment]
@jdm thanks a bunch!

**Pull request merged**
