### PR TITLE
Split the style-related bits out of LayoutContext and hoist more stuff into style/

### PR DESCRIPTION
**Pull request by bholley**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9077)

### CODE REVIEW

**Comment by bholley** [comment]
This depends on #9051. r? @SimonSapin when he's done with the former.

**Comment by SimonSapin** [comment]
Looks good. (Unreviewed files are those changed only in #9051.)

---

Reviewed 11 of 11 files at r2.
Review status: 11 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9077#-:-K6hbt7_AdFD5kjBpTbP:-1011899378)*

**Comment by bholley** [comment]
@bors-servo try

(Just in case, mostly to check the updates in #9051)

**Pull request merged**
