### PR TITLE
script: Disable our dependency in ffmpeg until the media madness is over

### PR DESCRIPTION
**Pull request by emilio**
r? @larsbergstrom 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12863)

### CODE REVIEW

**Comment by emilio** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Wouldn't it better to put it behind a feature disabled by default?

**Comment by emilio** [comment]
@GuillaumeGomez I agree, but there might be licensing issues with linking ffmpeg, so that's why I removed it.

**Comment by GuillaumeGomez** [comment]
Any idea how firefox solved these license issues?

**Comment by emilio** [comment]
Not linking it, but `dlopen`ing it dinamically.

**Comment by GuillaumeGomez** [comment]
So if we use something along this, we could keep it, right? Wouldn't it be faster to add it in `video-metadata-rs` crate?

**Comment by emilio** [comment]
I don't know, maybe? I don't know for sure if linking it dynamically will solve all the problems either, that's a question maybe for @asajeffrey.

**Comment by larsbergstrom** [comment]
This will also need to disable the corresponding tests.

@GuillaumeGomez Should we do this, or do you think that we will move video-metadata-rs off of ffmpeg in the next day or so? We can certainly land this first to avoid rushing the PRs to that crate, and then turn everything back on later once the dependency is ready again.

**Comment by asajeffrey** [comment]
Usual IANAL disclaimer. The FFmpeg licensing page is at: https://www.ffmpeg.org/legal.html

The main requirements are:

1. Compile FFmpeg without `--enable-gpl` and without `--enable-nonfree`.
2. Use dynamic linking (on windows, this means linking to dlls) for linking with FFmpeg libraries. 

There other items in their checklist, but there are the main two.

**Comment by emilio** [comment]
@larsbergstrom: tests updated

@bors-servo: try

**Comment by emilio** [comment]
That's a known intermittent. @larsbergstrom, feel free to review this if/when you think it should land.

**Comment by larsbergstrom** [comment]
@bors-servo r+

We can recover this functionality once the ffmpeg dependency is gone.

**Comment by larsbergstrom** [comment]
Hrm, homu never decided to run this. Because of the weird `try` states? Ugh. Will need a small change (sorry!) after #11756 lands, removing the copy of the ffmpeg stuff (or at least making it conditional).

**Comment by emilio** [comment]
@bors-servo: retry

That was my fault, I was investigating WebGL tests failures in the build
slave and I had a wpt socket already up, sorry

**Comment by KiChjang** [comment]
@bors-servo retry
* #12891

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #12592

**Comment by KiChjang** [comment]
FINALLY!

**Pull request merged**
