### PR TITLE
Remove a bunch of winapi 0.2 crates

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22703)

### CODE REVIEW

**Comment by nox** [comment]
I'm not actually sure that compiles on Windows 🤡

**Comment by jdm** [comment]
```
error[E0432]: unresolved import `winapi::um::heapapi`
   --> components\allocator\lib.rs:103:21
    |
103 |     use winapi::um::heapapi::{GetProcessHeap, HeapSize, HeapValidate};
    |                     ^^^^^^^ could not find `heapapi` in `um`
```

**Comment by SimonSapin** [comment]
There’s a `heapapi` Cargo feature

**Comment by jdm** [comment]
```
error[E0432]: unresolved import `rand::reseeding`
  --> components/rand/lib.rs:25:11
   |
25 | use rand::reseeding::{Reseeder, ReseedingRng};
   |           ^^^^^^^^^ could not find `reseeding` in `rand`

error[E0407]: method `next_u32` is not a member of trait `Rng`
  --> components/rand/lib.rs:64:5
   |
64 | /     fn next_u32(&mut self) -> u32 {
65 | |         self.rng.next_u32()
66 | |     }
   | |_____^ not a member of trait `Rng`

error[E0407]: method `next_u64` is not a member of trait `Rng`
  --> components/rand/lib.rs:69:5
   |
69 | /     fn next_u64(&mut self) -> u64 {
70 | |         self.rng.next_u64()
71 | |     }
   | |_____^ not a member of trait `Rng`

error[E0407]: method `reseed` is not a member of trait `SeedableRng`
  --> components/rand/lib.rs:86:5
   |
86 | /     fn reseed(&mut self, seed: &'a [usize]) {
87 | |         trace!("Manually reseeding ServoRng.");
88 | |         self.rng.reseed((ServoReseeder, as_isaac_seed(seed)))
89 | |     }
   | |_____^ not a member of trait `SeedableRng`

error[E0407]: method `next_u32` is not a member of trait `Rng`
   --> components/rand/lib.rs:139:5
    |
139 | /     fn next_u32(&mut self) -> u32 {
140 | |         self.rng.borrow_mut().next_u32()
141 | |     }
    | |_____^ not a member of trait `Rng`

error[E0407]: method `next_u64` is not a member of trait `Rng`
   --> components/rand/lib.rs:143:5
    |
143 | /     fn next_u64(&mut self) -> u64 {
144 | |         self.rng.borrow_mut().next_u64()
145 | |     }
    | |_____^ not a member of trait `Rng`

error[E0407]: method `fill_bytes` is not a member of trait `Rng`
   --> components/rand/lib.rs:148:5
    |
148 | /     fn fill_bytes(&mut self, bytes: &mut [u8]) {
149 | |         self.rng.borrow_mut().fill_bytes(bytes)
150 | |     }
    | |_____^ not a member of trait `Rng`

error: use of deprecated item 'rand::Rand': replaced by distributions::Standard
  --> components/rand/lib.rs:26:16
   |
26 | pub use rand::{Rand, Rng, SeedableRng};
   |                ^^^^
   |
   = note: `-D deprecated` implied by `-D warnings`

error: use of deprecated item 'rand::Rand': replaced by distributions::Standard
   --> components/rand/lib.rs:156:18
    |
156 | pub fn random<T: Rand>() -> T {
    |                  ^^^^

error[E0107]: wrong number of type arguments: expected 0, found 1
  --> components/rand/lib.rs:74:22
   |
74 | impl<'a> SeedableRng<&'a [usize]> for ServoRng {
   |                      ^^^^^^^^^^^ unexpected type argument

error: aborting due to 10 previous errors
```

**Comment by nox** [comment]
I removed the rand commit because it's not that useful and I don't want to spend the day doing the migration right now.

**Pull request merged**
