### PR TITLE
Rollup of PRs in the queue

### PR DESCRIPTION
**Pull request by Manishearth**
Did the rebase locally to save some efforts and broken bors

Merges:
- https://github.com/servo/servo/pull/5508
- https://github.com/servo/servo/pull/5509
- https://github.com/servo/servo/pull/5507
- https://github.com/servo/servo/pull/5461

### CODE REVIEW

**Comment by Manishearth** [comment]
:/

**Comment by Ms2ger** [comment]
I'd really rather not go there.

**Comment by Manishearth** [comment]
Where? All these PRs need rebasing to work with bots; thought I could just do them at once.

**Comment by Manishearth** [comment]
*bors

**Comment by mbrubeck** [comment]
#5461 was already rebased, and shuold be mergeable. Something is wrong with bors or auto.

**Comment by Manishearth** [comment]
Yeah, Lars poked bors -- hopefully it will work now.

**Pull request closed without merging**
