### PR TITLE
Extra space check

### LINKED ISSUE #17700: tidy: Detect keywords with more than one space afterwards
In `document.rs`:

```rust
            if  now.duration_since(last_time) < DBL_CLICK_TIMEOUT &&
                dist < DBL_CLICK_DIST_THRESHOLD as f64 {
```

(note the double space after the `if`).

We should write a tidy lint that catches this (and presumably also with other keywords, like `else`, `unsafe`, ... (any other?), and makes `./mach test-tidy` fail if that's the case.

@wafflespeanut, would you be able to mentor this? (I can too, though it'd take me a bit more time I presume)

### PR DESCRIPTION
**Pull request by SergeevPavel**
Add tidy check for keywords with more than one space afterwards.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17700 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17749)

### CODE REVIEW

**Comment by edunham** [comment]
IMO this might be better for rustfmt (https://github.com/nrc/rustfmt), since it's a nit in all Rust code rather than just Servo. 

However, if the rustfmt maintainers deem it not suitable for there for whatever reason, we can go ahead and consider sticking it in our Tidy.

**Comment by jdm** [comment]
@edunham I think adding support to rustfmt should be done in parallel, rather than instead. It doesn't make sense to put this off while we don't have any actual plans to make use of rustfmt yet.

**Comment by wafflespeanut** [comment]
We could add a few more (and hopefully have them as a list) - `impl`, `fn`, `struct`, `enum`, `pub`, `mod`, `use`, `in`, `ref`, `type`, `where` and `trait` - These are all I could think of 😄

**Comment by SergeevPavel** [comment]
@wafflespeanut  I added check for keywords that you mentioned. But I believe that using rustfmt would be better. Have we any problems with using rustfmt?

**Comment by jdm** [comment]
Yes. rustfmt has historically not been able to deal with the size and complexity of Servo's code, so we have built our own linting tools until it's usable for us.

**Pull request merged**
