### PR TITLE
Remove Message suffix from NetworkEventMessage

### PR DESCRIPTION
**Pull request by wilcus**
https://github.com/servo/servo/issues/7129

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7140)

### CODE REVIEW

**Comment by jdm** [comment]
Thanks! Just a couple indentation nits to fix before this merges :)
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/http_loader.rs, line 281 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7140#-JwOmh-R1wmELvFEG7eg)** ([raw file](https://github.com/servo/servo/blob/bc9863bdf6af58b3753502d74db745eb769d25c8/components/net/http_loader.rs#L281)):</sup>
nit: adjust the indentation on this line to match the `request_id` on the previous on.

---

<sup>**[components/net/http_loader.rs, line 417 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7140#-JwOml5R_PwG9X2gF8c4)** ([raw file](https://github.com/servo/servo/blob/bc9863bdf6af58b3753502d74db745eb769d25c8/components/net/http_loader.rs#L417)):</sup>
nit: same indentation here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7140)

**Comment by wilmoz** [comment]
Ready :). It's needed to create other create other pull request?

**Comment by jdm** [comment]
Nope! Just squash these two together, please: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7140)

**Comment by Ms2ger** [comment]
Thank you!

@bors-servo r=jdm

**Pull request merged**
