### PR TITLE
Performance: limit buffer size, clear on pipeline exit

### PR DESCRIPTION
**Pull request by gterzian**
Part of https://github.com/servo/servo/issues/24074

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24109)

### CODE REVIEW

**Comment by gterzian** [comment]
@jdm @asajeffrey The story continues, with a follow-up on https://github.com/servo/servo/issues/24074

These changes undo the previous changes made at https://github.com/servo/servo/pull/24072, while keeping the fix in place, and improving compliance with the performance spec.

**Comment by asajeffrey** [comment]
Ooh, nice find! Let me know when you're ready for a review!

**Comment by gterzian** [comment]
@asajeffrey r?

**Review by asajeffrey — APPROVED** [review]
That looks quite a bit nicer, thanks for finding an appropriate bit of the spec!

**Comment by gterzian** [comment]
@asajeffrey Actually, just seeing that there is already a concept in place like the one I introduced, so all that is necessary is to add a link to the spec and set the max size to 0 when the window clears its runtime...

**Comment by gterzian** [comment]
@asajeffrey r?

**Comment by jdm** [comment]
@bors-servo retry
* Network

**Pull request merged**
