### PR TITLE
Fire mozbrowserclose event on Window.close()

### LINKED ISSUE #11560: Fire a mozbrowserclose event when a page calls window.close()
At the moment we close the constellation when a page calls `window.close()`. In the mozbrowser case, we should fire a `mozbrowserclose` event.

cc @paulrouget (you may want to set a priority for this)

### PR DESCRIPTION
**Pull request by aneeshusa**
cc @asajeffrey 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11560 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____
- [X] I don't know how to test this

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11710)

### CODE REVIEW

**Comment by aneeshusa** [comment]
This is concise but inefficient. As I understand it, this implementation will send a MozBrowserEvent message from the script thread (window -> document) to the constellation, which returns it back to the script thread, which looks up the appropriate HTMLIFrameElement to call dispatch_mozbrowser_event on.

Here's my understanding/where I'm blocked on a better implementation: the way mozbrowser works is that certain iframes have mozbrowser attributes, so the dispatch_mozbrowser_event function is defined on HTMLIFrameElement. Furthermore, all iframes have an associated (WindowProxy and thus) Window; so when we get a Window.close() event, in the mozbrowser case we want to call dispatch_mozbrowser_event on that associated iframe. However, I don't know how to get a reference to that iframe; there is Document.find_iframe, but that needs to be called on the Document of the parent, and parent_info only has a PipelineId. Is there a way to use one of the iterators on Node (Node.ancestors? Node.inclusive_ancestors?) analogously to how Node.traverse_preorder is used in Document.find_iframe to find the right HTMLIFrameElement? Is there a more direct way that doesn't require searching the DOM?

**Comment by jdm** [comment]
I believe this is the most efficient way, given that the window being closed may live in a completely different thread (or process!) from the iframe that needs to receive the message.

**Comment by ConnorGBrewster** [comment]
We should add a test for this, similar to the ones in `tests/wpt/mozilla/tests/mozilla/mozbrowser/`.

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/window.rs, line 471 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11710#-KLrlVOzRZc_kYNwI64K:-KLrlVOzRZc_kYNwI64L:470866597) ([raw file](https://github.com/servo/servo/blob/d1079fac2d0f57305b2a7768c74fb217bba08cd2/components/script/dom/window.rs#L471)):*
> ```Rust
>             return;
>         }
>         // TODO(aneeshusa): do this more efficiently (avoid round-tripping to constellation)
> ```

We should remove this as per @jdm's comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11710#-:-KLrlkCpjncWHAOzkOiA:2027035053)*

**Comment by Manishearth** [comment]
Oh, forgot to comment on this it seems. r=me once Connor's comments are addressed.

**Comment by paulrouget** [comment]
@aneeshusa do you need help with the test?

**Comment by aneeshusa** [comment]
I don't have time to finish this right now.

**Pull request closed without merging**
