### PR TITLE
python: Add a serve-wpt command to mach

### PR DESCRIPTION
**Pull request by emilio**
r? @frewsxcv

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9798)

### CODE REVIEW

**Comment by ecoal95** [comment]
By the way, doing things this way (or using `./serve` directly), there's a syntax error in `testharnessreport.js`, do you know how it can be worked around @frewsxcv?

**Comment by frewsxcv** [comment]
I tried running this:

```
coreyf@frewbook-pro ~/D/r/servo ((18f4846...))> ./mach serve-wpt
DEBUG:web-platform-tests:Going to use port 56641
Process ServerDictManager-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 550, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 162, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
    self._socket.bind(address)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno 8] nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/serve", line 5, in <module>
    serve.main()
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/serve.py", line 4, in main
    serve.main()
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/tools/serve/serve.py", line 526, in main
    with stash.StashServer((config["host"], get_port()), authkey=str(uuid.uuid4())):
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/stash.py", line 30, in __enter__
    self.manager, self.address, self.authkey = start_server(self.address, self.authkey)
  File "/Users/coreyf/Development/rust/servo/tests/wpt/web-platform-tests/tools/wptserve/wptserve/stash.py", line 52, in start_server
    manager.start()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 528, in start
    self._address = reader.recv()
EOFError
```

**Comment by Wafflespeanut** [comment]
It occurs when you don't have the [domains in the `hosts` file](https://github.com/w3c/web-platform-tests#running-the-tests). Maybe it should be mentioned somewhere. I guess the testsuite makes use of the default hosts file, unlike wptrunner.

**Comment by jdm** [comment]
We should set our environment variable to get the proper host replacements.

**Comment by ecoal95** [comment]
I don't seem to find a cross-platform way to override the hosts file... Should I dive in serve.py and do whatever wptrunner is doing?

**Comment by Ms2ger** [comment]
It seems better to implement this as part of `test-wpt`.

**Comment by metajack** [comment]
@ms2ger Are you suggesting that test-wpt get a `--serve` option?

**Comment by Ms2ger** [comment]
Yes, I think that would be easiest

**Comment by jdm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
