### PR TITLE
Use our copy of RefCell for style data

### PR DESCRIPTION
**Pull request by SimonSapin**
This allows removing `#![feature(as_unsafe_cell)]` in geckolib and make progress towards #11815.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #11815.

- [ ] There are tests for these changes OR
- [x] These changes do not require new tests because they don’t introduce no functional changes.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11835)

### CODE REVIEW

**Comment by metajack** [comment]
Is there justification for this somewhere? Ie, does the Rust team not want to stabilize this? Using custom data structures is a road that may end up infected crates that others depend on, and could segregate us from the ecosystem. Not to mention we won't be getting RefCell bugfixes.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/issues/27708 is the tracking issue for stabilizing `as_unsafe_cell`. Alex has expressed some concerns, but as far as I can tell it isn’t a firm "does not want to". I’m hoping this can be stabilized in the coming weeks, and once it rides the trains and reaches the stable channel we can revert this PR (except for the `#![feature(as_unsafe_cell)]` bit).

I agree that forking data structures from `std` is not great, but I’m not concerned about infecting more crates: nothing outside of Servo and Stylo depends on the `style` crate, and I don’t expect that to change.

I made this PR because I’d like to not be blocked several weeks (at best) before we can get CI for #11815.

**Comment by metajack** [comment]
Thanks for the explanation.

**Pull request merged**
