### PR TITLE
Fixes #5917

### LINKED ISSUE #5917: Cannot Build: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
Got pre-reqs via port, cloned the git repo, tried `./mach build` and got the following error:

https://gist.githubusercontent.com/sneakyness/291546375a0cd17fab78/raw/97541beb685b97c3a7a745bda3038fad670da6e4/gistfile1.sh

I joined #servo on moz irc, apparently they've never seen this before. 

I tried manually printing out the s3 urls for cargo and rust, and extracting them to the correct location, then removing those steps from the build script, but this only created more errors.

### PR DESCRIPTION
**Pull request by sneakyness**
Thank you @learnopengles for figuring this out :)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5954)

### CODE REVIEW

**Comment by learnopengles** [comment]
Full credit goes to @onodera-punpun ;) I just mentioned the part of the fix that worked for me.

**Comment by onodera-punpun** [comment]
I just want to mention that I got this workaround from https://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error, the guy mentions that 'fixing' it this is **highly discouraged** (in bold). I don't know enough about either python or ssl why though.

**Comment by Manishearth** [comment]
I don't think we want to use an unverified context; otherwise we would just serve over http.

We want to be able to fall back to an unverified context with reporting. I.e. if the build fails due to this, let the user know about a problem with the certs, and suggest  `./mach bootstrap -f --unverified`.

Alternate suggestions can include downloading the snap via a browser (we can print the url) and asking users to `./mach bootstrap --from-tar=...`.

**Comment by jdm** [comment]
For the purposes of this PR, I agree that we should only bypass these checks with an `--unverified` argument to the `bootstrap` command. And yes, we should try to catch the exception from #5917 and show the user a more useful error message that suggests that option.

**Comment by Manishearth** [comment]
Let me know if you need help adding the unverified option :)

**Comment by metajack** [comment]
Closing this. If someone wnats to revive to fix #5917 then it will be linked now.

**Pull request closed without merging**
