### PR TITLE
 Update XMLHTTPRequest FetchBodyInit and related Impl (#9291)

### LINKED ISSUE #9291: Update XMLHTTPRequest FetchBodyInit
The type is actually defined by the Fetch spec [here](https://fetch.spec.whatwg.org/#bodyinit). We'll also potentially have to update the `extract` method implementation as well.

Code: `components/script/dom/xmlhttprequest.rs`, `components/script/dom/webidls/XMLHttpRequest.webidl`
Spec: https://fetch.spec.whatwg.org/#bodyinit, https://fetch.spec.whatwg.org/#concept-bodyinit-extract

### PR DESCRIPTION
**Pull request by stspyder**
Fixes #9291.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9354)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo try

No tests are failing/passing?

**Comment by stspyder** [comment]
No failing wpt tests.

**Comment by KiChjang** [comment]
Can you squash the commits together, please?

**Comment by stspyder** [comment]
Sure will do.

**Comment by Ms2ger** [comment]
@KiChjang, can you file an issue about the missing test coverage here?

**Comment by stspyder** [comment]
squashed the commits

**Comment by KiChjang** [comment]
@Ms2ger Filed #9357.

@bors-servo r+

**Comment by KiChjang** [comment]
@bors-servo retry
* #9012

**Comment by KiChjang** [comment]
@bors-servo retry
* #9278

**Pull request merged**
