### PR TITLE
Set a reasonable max count on open files and don't panic if set fails

### PR DESCRIPTION
**Pull request by connorimes**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7992)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/lib.rs, line 106 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7992#-K0W_DszDE7uln82o-81)** ([raw file](https://github.com/servo/servo/blob/fd710eebc1037ff6e5953168f19c8c8e647cc6b7/components/script/lib.rs#L106)):</sup>
Why 4096? In the code from gecko that I linked to you yesterday (http://mxr.mozilla.org/mozilla-central/source/netwerk/base/nsSocketTransportService2.cpp#1426 ), Gecko sets the limit to 550+250=800.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7992)

**Comment by connorimes** [comment]
`setrlimit` was failing on an ARM system and it's unclear why.  A C program that does the same thing worked, but we may want to track down why it failed.  A Rust problem?

**Comment by connorimes** [comment]
Yes, I saw that.  I picked 4096 because of the extra parallelization in servo and didn't see any harm in requesting a higher limit (doesn't mean we'll use it).  I was originally thinking 1024, but we can default to 800 if you want, as long we you think it's enough.  Before we were requesting the max possible, which at least on my laptop was 65536.  The ARM system I'm testing on has a max of 4096 and a default of 1024.

**Comment by larsbergstrom** [comment]
I'm a little worried about http://mxr.mozilla.org/mozilla-central/source/netwerk/base/nsSocketTransportService2.cpp#1432, which uses '>=', implying only 1k somewhere? Maybe @vvuk can comment - did you run into anything with `setrlimit` calls when doing the Windows port?

**Comment by connorimes** [comment]
FYI, this `perform_platform_specific_initialization` fn is for linux only.  For other OS targets the fn is currently empty.

**Comment by larsbergstrom** [comment]
Hrm, yeah, let's just stick with 4096, then, and see how it works out.

@bors-servo r+

**Comment by vvuk** [comment]
Windows doesn't really have such a limit -- each process can have as many as 16M (2^24) handles open, and there isn't a soft limit that needs to be raised.

**Comment by larsbergstrom** [comment]
```
Ran 213204 tests (3286 parents, 209918 subtests)
Expected results: 212504
Unexpected results: 1 (TIMEOUT: 1)
Skipped: 699

Unexpected Results
==================

/_mozilla/mozilla/canvas/drawimage_html_image_10.html
-----------------------------------------------------
```

**Comment by larsbergstrom** [comment]
@bors-servo retry
* Issue #7787

**Pull request merged**
