### PR TITLE
Pass the event loop waker into WebXR

### LINKED ISSUE #23796: Intermittent timeouts in /webxr/xrSession_prevent_multiple_exclusive.https.html, /webxr/xrDevice_disconnect_ends.https.html, /webxr/xrSession_input_events_end.https.html
```
  ▶ TIMEOUT [expected OK] /webxr/xrSession_prevent_multiple_exclusive.https.html
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 18.3.0-devel

  ▶ Unexpected subtest result in /webxr/xrSession_prevent_multiple_exclusive.https.html:
  │ TIMEOUT [expected FAIL] Test prevention of multiple simultaneous immersive sessions
  └   → Test timed out
```
cc @Manishearth

### PR DESCRIPTION
**Pull request by asajeffrey**
This PR passes the event loop waker into webxr so it can wake the main thread up when needed.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #23796 
- [X] These changes do not require tests because existing tests do the job

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23847)

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by asajeffrey** [comment]
```
error[E0407]: method `clone` is not a member of trait `EventLoopWaker`
  --> components/net/tests/main.rs:70:13
   |
70 | /             fn clone(&self) -> Box<dyn EventLoopWaker + Send> {
71 | |                 Box::new(DummyEventLoopWaker {})
72 | |             }
   | |_____________^ not a member of trait `EventLoopWaker`
```
Serves me right for renaming a method. @bors-servo r=jdm

**Comment by asajeffrey** [comment]
Didn't catch all the impls of EventLoopWaker. @bors-servo r=jdm

**Pull request merged**
