### PR TITLE
Update servo-media to fix intermittent timeouts

### LINKED ISSUE #22010: Intermittent TIMEOUT in /2dcontext/imagebitmap/canvas-createImageBitmap-video-resize.html
```
  ▶ TIMEOUT [expected OK] /2dcontext/imagebitmap/canvas-createImageBitmap-video-resize.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.1.0-devel
  └ Setup media player error SetPropertyFailed("Failed to set config")

  ▶ Unexpected subtest result in /2dcontext/imagebitmap/canvas-createImageBitmap-video-resize.html:
  └ NOTRUN [expected FAIL] createImageBitmap(HTMLVideoElement) with resize option
```

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22010

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22014)

### CODE REVIEW

**Comment by asajeffrey** [comment]
```
  ▶ TIMEOUT [expected ERROR] /2dcontext/imagebitmap/createImageBitmap-transfer.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.1.0-devel
  │ 0:00:00.040711370 73605 0x7fc8a402d230 WARN                typefind gsttypefindelement.c:856:gst_type_find_get_extension:<typefind> could not find uri extension in appsrc://
  └ 0:00:00.045652871 73605 0x7fc8940039e0 WARN                typefind gsttypefindelement.c:856:gst_type_find_get_extension:<typefind> could not find uri extension in appsrc://
```
Looks like the `TIMEOUT` is still there.

**Comment by asajeffrey** [comment]
Oh you're right, I didn't pattern-match the names properly.

**Comment by ferjm** [comment]
I am unable to reproduce the `TIMEOUT` or get the warnings locally.

@sdroege @ceyusa I am not sure what these warnings mean and/or how they affect the player functionality.

**Comment by sdroege** [comment]
Those warnings can be ignored, wrong log  level. Should be info or something, not warning :) will change later

This is from the debug logs, not a warning/error message. You can control the display of those via API

**Pull request merged**
