### PR TITLE
Make PipelineId a pair of PipelineId and Option<SubpageId>

### LINKED ISSUE #5235: Make PipelineId a pair of PipelineId and Option<SubpageId>
This would conceivably allow us to move all subpage-related modification out of script and into the constellation, where it arguably belongs.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes #5235

So, considering this is my first real PR, I can happily report

### CODE REVIEW

**Comment by jdm** [comment]
So there are a couple more parts to #5235:
* the SubpageId field should be an Option
* SugpageId arguments should rarely exist along with a PipelineId argument, as they do now
* the code in HTMLIFrameElement that creates a new subpage id should take the existing pipeline id and modify the contained subpage id

Does that make sense? Part 2 is really where the expected line churn comes from.

**Comment by frewsxcv** [comment]
I think I understand. I'll make those modifications and report back

**Comment by frewsxcv** [comment]
@jdm The type signature for `Constellation.subpage_map` shouldn't change, right?

**Comment by jdm** [comment]
Correct.

**Comment by frewsxcv** [comment]
I'm still interested in completing this, but it might take a couple more days due to my schedule. So if this is a critical issue that needs to be addressed before then, someone else can take over the work

**Comment by jdm** [comment]
It's not critical, fear not :)

**Comment by frewsxcv** [comment]
So after attempting to complete this, I'm not sure I'm qualified. I feel like there's a lot cases where PipelineId and SubpageId shouldn't be reduced to just PipelineId, and I'm not familiar enough with the codebase to really know on my own.

**Comment by jdm** [comment]
That is a fair concern. If you'd like to keep trying, I'm happy to keep answering questions. Otherwise, go ahead and close this PR.

**Pull request closed without merging**
