### PR TITLE
Regenerate bindings

### PR DESCRIPTION
**Pull request by Manishearth**
Don't merge yet

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14268)

### CODE REVIEW

**Comment by Manishearth** [comment]
I'm getting this segfault on wikipedia:

```
thread '<unnamed>' panicked at 'Calling previous_styles without having gathered it', /Users/manishearth/mozilla/s-i/servo/components/style/data.rs:172
stack backtrace:
   1:        0x114b01138 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x114b0eacf - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x114b0bf9f - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x114b0c5c6 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x1147af61a - std::panicking::begin_panic::hc03e2830c2c89a5f
   6:        0x11487c01a - style::data::ElementData::previous_styles_mut::h3209ac372e2e86dd
   7:        0x11488af2d - style::matching::MatchMethods::cascade_node::hc5639905206ebb4b
   8:        0x114892dba - style::traversal::recalc_style_at::h0e01fc41d4f2f294
   9:        0x11487dc79 - <style::gecko::traversal::RecalcStyleOnly<'lc> as style::traversal::DomTraversalContext<style::gecko::wrapper::GeckoNode<'ln>>>::process_preorder::ha33cdaf57d18a3a9
  10:        0x1146f71b1 - style::parallel::top_down_dom::{{closure}}::h5d9a5fa5b76c3f58
  11:        0x1146f70c3 - rayon::scope::Scope::execute_job_closure::{{closure}}::h1f98fccacfa09a33
  12:        0x1146ec797 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h415c352b9b94e4d7
  13:        0x114693a67 - std::panicking::try::do_call::h3f93514d15f1526b
```

Trypush at https://treeherder.mozilla.org/#/jobs?repo=try&revision=dee8796be7b8a0b9811c683bf3b5079bc5019af0&selectedJob=31377430

@bholley , know anything about this? Seems to be related  to your cascade changes?

**Comment by Wafflespeanut** [comment]
Note: There's another #14255

**Comment by KiChjang** [comment]
@bors-servo retry
* #10473

**Comment by Manishearth** [comment]
@bors-servo retry

 - #14217

**Comment by Manishearth** [comment]
@bors-servo retry

  -  #10473

**Comment by Manishearth** [comment]
@bors-servo retry

 - #14221

**Comment by Manishearth** [comment]
@bors-servo retry

 - #14221

**Comment by KiChjang** [comment]
@bors-servo retry
* #13133

**Comment by KiChjang** [comment]
@bors-servo retry
* #14247

**Comment by Manishearth** [comment]
@bors-servo retry

 - #14267

**Pull request merged**
