### PR TITLE
Implement focus, blur, focusin and focusout events

### PR DESCRIPTION
**Pull request by paulrouget**
Based on https://github.com/servo/servo/pull/7985

Fixes https://github.com/servo/servo/issues/7981

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9529)

### CODE REVIEW

**Comment by KiChjang** [comment]
It's a tidy failure, everything else looks good so far as testing goes.

**Comment by nox** [comment]
@paulrouget Does it really need to live in script_traits?

**Comment by paulrouget** [comment]
> @paulrouget Does it really need to live in script_traits?

No. Where do you recommend I put it?

**Comment by jdm** [comment]
`document.rs` makes sense.

**Comment by paulrouget** [comment]
This is now ready for review.

**Comment by asajeffrey** [comment]
This looks pretty good! The only real comment is that you appear to be defining+using methods that are deprecated in https://w3c.github.io/uievents/

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/document.rs, line 1436 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0a35wlC1SULiW28rl:-KA0a35wlC1SULiW28rm:596335208) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/components/script/dom/document.rs#L1436)):*
The spec (https://html.spec.whatwg.org/multipage/#fire-a-focus-event) says that the fired event should be set not to bubble. Is there a different bit of the spec that says that focusin and focusout should bubble?

---

*[components/script/dom/focusevent.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0hAWii0M8WYchfqUA:-KA0hAWii0M8WYchfqUB:-1879232322) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/components/script/dom/focusevent.rs#L48)):*
This is calling a method that appears not to be in the spec.

---

*[components/script/dom/focusevent.rs, line 83 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0gsXDKkX-r1hVY5_q:-KA0gsXDKkX-r1hVY5_r:8683045) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/components/script/dom/focusevent.rs#L83)):*
This URL appears to be dangling, and initFocusEvent appears to be removed from the spec.

---

*[components/script/dom/focusevent.rs, line 96 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0hRJknrVnMbJxu_MA:-KA0hRJknrVnMbJxu_MB:-44039023) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/components/script/dom/focusevent.rs#L96)):*
initUIEvent is listed as deprecated in https://w3c.github.io/uievents/#widl-UIEvent-initUIEvent

---

*[components/script/dom/webidls/FocusEvent.webidl, line 6 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0cOnu_bbKweO2y3Uv:-KA0cOnu_bbKweO2y3Uw:-1233391103) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/components/script/dom/webidls/FocusEvent.webidl#L6)):*
This URL redirects to https://w3c.github.io/uievents/#idl-def-FocusEvent. The id seems to be `#interface-FocusEvent`.

---

*[components/script/dom/webidls/FocusEvent.webidl, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0fdUQ5PLiSbk0K_9A:-KA0fdURm0dRDhmauZvi:-1804412333) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/components/script/dom/webidls/FocusEvent.webidl#L17)):*
Couldn't find this method, a quick google kicked up https://github.com/w3c/uievents/issues/44, which says that it isn't needed for web compat.

---

*[tests/wpt/mozilla/tests/mozilla/FocusEvent.html, line 104 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0gFNAOsOqnzBEydvw:-KA0gFNAOsOqnzBEydvx:1216661908) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/tests/wpt/mozilla/tests/mozilla/FocusEvent.html#L104)):*
Yay tests!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9529#-:-KA0hlfUL16qikev9Yoo:-2044728300)*

**Comment by paulrouget** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/document.rs, line 1436 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0a35wlC1SULiW28rl:-KA3rkQCFSQYPJ6jXXAY:1421623437) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/components/script/dom/document.rs#L1436)):*
https://www.w3.org/TR/DOM-Level-3-Events/#event-type-focusin

I don't know if we want to support focusin and focusout. It was part of the original comment: "// TODO: dispatch blur, focus, focusout, and focusin events". According to MDN, focusin/focusout are not supported by Firefox, but supported by all the other browsers.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9529)*

**Comment by Ms2ger** [comment]
Somewhat better spec: https://w3c.github.io/uievents/

**Comment by paulrouget** [comment]
So I should remove `initUIEvent`, or just not use it?

**Comment by asajeffrey** [comment]
I'd say remove initUIEvent, just implement what's in https://w3c.github.io/uievents/#events-focusevent

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/document.rs, line 1436 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0a35wlC1SULiW28rl:-KA5YNley8dMnAUMEyVf:1456736766) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/components/script/dom/document.rs#L1436)):*
The whatwg spec appears not to mention focusin and focusout, but they are in the w3c spec, great. I'd say include them, but put a link to the w3c spec, and perhaps a bit of text discussing the w3c/whatwg spec issue.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9529)*

**Comment by asajeffrey** [comment]
Discussion on IRC (http://logs.glob.uno/?c=mozilla%23servo#c361717). The consensus was a) implement focusin/focusout, and b) defer to the w3c spec for focusin/focusout, the whatwg spec for focus events only applies to `focus` and `blur`.

**Comment by Ms2ger** [comment]
Why are we adding focusin/focusout? Doesn't seem like Gecko supports them.

**Comment by paulrouget** [comment]
Relevant: https://bugzilla.mozilla.org/show_bug.cgi?id=687787

**Comment by paulrouget** [comment]
(not ready for review yet)

**Comment by paulrouget** [comment]
I'm not sure I can easily not use `InitUIEvent` (needed to initialize `view` and `detail`).

**Comment by Ms2ger** [comment]
Yeah, just use it. It's not going away.

**Comment by asajeffrey** [comment]
OK, all looks good. My only niggle is that we should include a comment about the W3C / WhatWG spec overlap.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/document.rs, line 1436 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9529#-KA0a35wlC1SULiW28rl:-KAfYU4Du3GCwkq4g39Q:110708067) ([raw file](https://github.com/servo/servo/blob/de5ef0c55fcda1a13a4b671678e92cb7cba5a7f4/components/script/dom/document.rs#L1436)):*
Should fire_focus_event apply to focusin/focusout? We should at least include a comment with a reference to the w3c spec for focusin/focusout, and add a comment that the specs are overlapping.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9529#-:-KAfYqXlhr0nGCQ6xpUP:-868776641)*

**Comment by Ms2ger** [comment]
Still not convinced we should implement in/out while its fate is unclear

**Comment by paulrouget** [comment]
> Still not convinced we should implement in/out while its fate is unclear

Let's not add `focusin` and `focusout` for now. I'll file a different issue where we can discuss adding these events or not.

**Comment by paulrouget** [comment]
Moved focusin/focusout out of this PR (see https://github.com/paulrouget/servo/compare/focusEvents...paulrouget:focusinout)

**Comment by asajeffrey** [comment]
Looks good, we can have a separate discussion about focusin/focusout.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9529#-:-KAjv8-0X-4y57nApUl8:1328812001)*

**Comment by KiChjang** [comment]
```

Ran 4600 tests finished in 229.0 seconds.
  • 4598 ran as expected. 1372 tests skipped.
  • 1 tests failed unexpectedly
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /DOMEvents/constructors.html:
  └ PASS [expected FAIL] FocusEvent constructor (no argument)

  ▶ Unexpected subtest result in /DOMEvents/constructors.html:
  └ PASS [expected FAIL] FocusEvent constructor (undefined argument)

  ▶ Unexpected subtest result in /DOMEvents/constructors.html:
  └ PASS [expected FAIL] FocusEvent constructor (null argument)

  ▶ Unexpected subtest result in /DOMEvents/constructors.html:
  └ PASS [expected FAIL] FocusEvent constructor (empty argument)

  ▶ Unexpected subtest result in /DOMEvents/constructors.html:
  └ PASS [expected FAIL] FocusEvent constructor (argument with default values)

  ▶ Unexpected subtest result in /DOMEvents/constructors.html:
  └ PASS [expected FAIL] FocusEvent constructor (argument with non-default values)

  ▶ FAIL [expected PASS] /_mozilla/css/border_collapse_simple_a.html
  └   → /_mozilla/css/border_collapse_simple_a.html 3193ec98288d78bdd692cb2acc61456553d72f9f
/_mozilla/css/border_collapse_simple_ref.html c14395ed4b2c80aee21c9bd21c8b4b734fec07e5
Testing 3193ec98288d78bdd692cb2acc61456553d72f9f == c14395ed4b2c80aee21c9bd21c8b4b734fec07e5
```
Looks good! Except for that intermittent...

**Comment by asajeffrey** [comment]
Can you change the test results that are now passing and we'll re-run?

**Comment by paulrouget** [comment]
> Can you change the test results that are now passing and we'll re-run?

done.

**Pull request merged**
