### PR TITLE
Dispatch message events for WebSocket.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7066)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

This is exciting :)

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 63 of 63 files at r1, 27 of 27 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7066)

**Comment by Ms2ger** [comment]
@bors-servo p=5

Should reduce wpt turnaround time by a few minutes.

**Comment by jdm** [comment]
```

/html/dom/interfaces.html
-------------------------
PASS expected FAIL WebSocket interface: attribute onmessage
```

**Pull request merged**
