### PR TITLE
Fix #6519

### LINKED ISSUE #6519: acid3 uses unpaired surrogates
Visiting http://acid3.acidtests.org/

thread 'ScriptTask PipelineId(0)' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf16Error(())', src/libcore/result.rs:731
    stack backtrace:
       1:        0x107894065 - sys::backtrace::write::hab580a18e6ade3dauns
       2:        0x107897685 - panicking::on_panic::h1844ce5c03c54289BFw
       3:        0x1078851a2 - rt::unwind::begin_unwind_inner::hbe10c68a88d62d39Nnw
       4:        0x107885809 - rt::unwind::begin_unwind_fmt::h1cd2a6c7dee6575eTmw
       5:        0x10789705c - rust_begin_unwind
       6:        0x1078bfec5 - panicking::panic_fmt::h2f556e59c40f3e3cE8B
       7:        0x1067c7182 - dom::bindings::conversions::jsstring_to_str::h5792c886e1f6e49fXtd
       8:        0x1067cbc69 - dom::bindings::conversions::DOMString.FromJSValConvertible::from_jsval::h1afc9893bea3bbdbCxd
       9:        0x1068f9588 - dom::bindings::codegen::Bindings::HTMLInputElementBinding::set_value::h50e535774fb4155dyF5
      10:        0x1078c8b1a - CallJitSetterOp
      11:        0x1067c8652 - dom::bindings::utils::call_setter::hed79a0ad67ff6e85xrc
      12:        0x1067c839a - dom::bindings::utils::generic_call::h3ebb307afb54a3a8bnc
      13:        0x106d17824 - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
      14:        0x106d0fa17 - _ZN2js6InvokeEP9JSContextRKN2JS5ValueES5_jPS4_NS2_13MutableHandleIS3_EE
      15:        0x106d2d38e - _ZN2js20InvokeGetterOrSetterEP9JSContextP8JSObjectN2JS5ValueEjPS5_NS4_13MutableHandleIS5_EE
      16:        0x106d49ecb - _ZN2js17NativeSetPropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_IP8JSObjectEENS3_I4jsidEENS_13QualifiedBoolENS2_13MutableHandleINS2_5ValueEEERNS2_14ObjectOpResultE
      17:        0x106d262d5 - _ZL9InterpretP9JSContextRN2js8RunStateE
      18:        0x106d1f059 - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
      19:        0x106d17a19 - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
      20:        0x106d0fa17 - _ZN2js6InvokeEP9JSContextRKN2JS5ValueES5_jPS4_NS2_13MutableHandleIS3_EE
      21:        0x106e669b1 - _ZN2js3jitL14DoCallFallbackEP9JSContextPNS0_13BaselineFrameEPNS0_15ICCall_FallbackEjPN2JS5ValueENS7_13MutableHandleIS8_EE

### PR DESCRIPTION
**Pull request by cuzbog**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6541)

### CODE REVIEW

**Comment by jdm** [comment]
@SimonSapin do you have thoughts on this?

**Comment by SimonSapin** [comment]
This works, but only on little-endian platforms. Not that we support any big-endian architecture anyway, but you can use `String::from_utf16_lossy` to get the same behavior (replace lone surrogates with U+FFFD) and avoid dealing with bytes and endianness entirely.

**Comment by Ms2ger** [comment]
This is definitely the wrong fix. What should happen, if this actually is a problem outside acid3, is moving DOMString to wtf-8.

**Comment by boghison** [comment]
I am closing this if it's the wrong fix

**Pull request closed without merging**
