### PR TITLE
Rename the browsercontext module.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8942)

### CODE REVIEW

**Comment by jdm** [comment]
:clap: :clap:

**Comment by KiChjang** [comment]
```

Ran 7097 tests finished in 372.0 seconds.
  • 7075 ran as expected. 8 tests skipped.
  • 22 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /css21_dev/html4/display-014.htm

  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/display-013.htm

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/display-002.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/display-001.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/direction-applies-to-015.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/direction-applies-to-014.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/direction-applies-to-006.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ was ready to save, resetting ready_to_save_state

  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/direction-applies-to-005.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ was ready to save, resetting ready_to_save_state

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/direction-applies-to-013.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/display-010.htm
  │ 
  └ was ready to save, resetting ready_to_save_state

  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/direction-applies-to-008.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ was ready to save, resetting ready_to_save_state

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/display-015.htm

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/display-011.htm
  │ 
  └ was ready to save, resetting ready_to_save_state

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/display-006.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ was ready to save, resetting ready_to_save_state

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/display-016.htm

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/display-008.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/display-007.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/direction-applies-to-007.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/direction-applies-to-012.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ was ready to save, resetting ready_to_save_state

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/direction-applies-to-009.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/display-012.htm
  │ 
  └ was ready to save, resetting ready_to_save_state

  ▶ TIMEOUT [expected PASS] /css21_dev/html4/display-005.htm
  │ 
  │ was ready to save, resetting ready_to_save_state
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ was ready to save, resetting ready_to_save_state
```

**Comment by jdm** [comment]
@bors-servo: retry
* #8944

**Comment by jdm** [comment]
@bors-servo: retry
* #7437

**Pull request merged**
