### PR TITLE
Extract bodies of generated binding helpers into common code

### PR DESCRIPTION
**Pull request by jdm**
This is part of fixing #29770, by extracting common behaviour that [will be called](https://searchfox.org/mozilla-central/rev/2d678a843ceab81e43f7ffb83212197dc10e944a/dom/bindings/BindingUtils.cpp#3744) from new code in interface.rs.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

### CODE REVIEW

**Comment by sagudev** [comment]
I do not know what exactly to review here as this is mostly just refactor change. LGTM, but still getting: `Error at https://sagudev.github.io/test-cases/extendEventTarget:23:11 a.meth is not a function`

**Comment by jdm** [comment]
Yes, this does not fix #29770 yet. I just wanted to pull this refactor out while I worked on the full fix.

**Pull request merged**
