### PR TITLE
Try to conform a bit more to "The event loop processing model"

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18611)

### CODE REVIEW

**Comment by nox** [comment]
Cc @emilio
@bors-servo try

**Comment by nox** [comment]
Cc @emilio, was that already the case in your PR?

```
  ▶ TIMEOUT [expected PASS] /css-ui-3_dev/html/text-overflow-005.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 17.2.0-devel
```

**Comment by emilio** [comment]
Not really, I can look into it if you can't. Thanks a lot for rebasing this @nox!

**Comment by jdm** [comment]
Closing due to inactivity. Tracking in https://github.com/servo/servo/issues/19242.

**Pull request closed without merging**
