### PR TITLE
move modules around

### PR DESCRIPTION
**Pull request by ajnirp**
for #8130

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8221)

### CODE REVIEW

**Comment by nox** [comment]
The branch should be rebased, and that merge commit in the middle of nowhere removed from it.

**Comment by jdm** [comment]
Oh, I guess #8130 wasn't clear. We don't actually want to remove the code generation related to the type ids. We only want to re-export the generated values from the new module, like this:
```
pub use dom::bindings::codegen::InheritTypes::*;
```

**Comment by wenderen** [comment]
@jdm that makes the fix much simpler, thanks.

**Comment by jdm** [comment]
This looks fine, although a find and replace for `dom::bindings::codegen::InheritTypes::` -> `dom::bindings::inheritance::` would be nice :)

**Comment by wenderen** [comment]
Ah right, sorry, I forgot to (re-)do that.

**Comment by jdm** [comment]
At this point, it looks like all we need is a rebase against master and fixes for the results of `./mach test-tidy` before this can merge :)

**Comment by wenderen** [comment]
done! I didn't correct the `test-tidy` warning about a name being redefined in `CodegenRust.py` because that is separate from this patch.

**Comment by nox** [comment]
@wenderen That's not separate, given it happens on that specific PR.

**Comment by jdm** [comment]
Travis doesn't like these changes so far.

**Pull request merged**
