### PR TITLE
sorted the declarations in various files...

### PR DESCRIPTION
**Pull request by ghost**
This is a direct extract from my abandoned PR for a lint (#7546), along with some rather clumsy modifications (only on `components/script/dom/mod.rs` and `components/style/lib.rs`), because I had to sort some of the files again to make peace with tidy, which hasn't been educated about sorting yet!

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7698)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Oh, did I really?

**Comment by jdm** [comment]
That's just tidy see the word `unsafe` anywhere in the diff.

**Comment by frewsxcv** [comment]
<sup>**[components/compositing/lib.rs, line 15 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7698#-JzorHEamZjxy5NUgl9a)** ([raw file](https://github.com/servo/servo/blob/de44f186a61960a1e546c585a45f012d65e0f67e/components/compositing/lib.rs#L15)):</sup>
Why are the `macro_use` crates not sorted with the others below?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by Wafflespeanut** [comment]
@frewsxcv Because, the macros of a module is visible to the other modules only after the `#[macro_use]` declaration. For instance, we can't have [this declaration](https://mxr.mozilla.org/servo/source/components/script/dom/mod.rs#185) anywhere but the top, because other modules demand its macros.

**Comment by frewsxcv** [comment]
Conflicts :-/

I'll try to review faster now that my comment was addressed

**Comment by frewsxcv** [comment]
Reviewed 52 of 195 files at r1.
Review status: 52 of 195 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by frewsxcv** [comment]
<sup>**[components/script/lib.rs, line 98 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7698#-Jzs0frw6PAPBZxXZg6s)** ([raw file](https://github.com/servo/servo/blob/de44f186a61960a1e546c585a45f012d65e0f67e/components/script/lib.rs#L98)):</sup>
Why did this get added?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by frewsxcv** [comment]
<sup>**[components/script/lib.rs, line 98 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7698#-Jzs0frw6PAPBZxXZg6s)** ([raw file](https://github.com/servo/servo/blob/de44f186a61960a1e546c585a45f012d65e0f67e/components/script/lib.rs#L98)):</sup>
Nevemrind, I see it was moved from the module

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by frewsxcv** [comment]
<sup>**[components/servo/Cargo.toml, line 71 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7698#-Jzs1W1vKKSJ16MjJobr)** ([raw file](https://github.com/servo/servo/blob/de44f186a61960a1e546c585a45f012d65e0f67e/components/servo/Cargo.toml#L71)):</sup>
Is there any reason to keep these new 'plugin' dependencies?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by frewsxcv** [comment]
Reviewed 143 of 195 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by Wafflespeanut** [comment]
No problem, fixed it :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[components/servo/Cargo.toml, line 71 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7698#-Jzs1W1vKKSJ16MjJobr)** ([raw file](https://github.com/servo/servo/blob/de44f186a61960a1e546c585a45f012d65e0f67e/components/servo/Cargo.toml#L71)):</sup>
Sorry, that has to be removed, since that was added only for checking the sorting.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by frewsxcv** [comment]
<sup>**[components/servo/Cargo.toml, line 71 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7698#-Jzs1W1vKKSJ16MjJobr)** ([raw file](https://github.com/servo/servo/blob/de44f186a61960a1e546c585a45f012d65e0f67e/components/servo/Cargo.toml#L71)):</sup>
Just to clarify, are you going to remove it? If so, make sure to remove it in the other Cargo.toml and Cargo.lock files

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by frewsxcv** [comment]
Reviewed 1 of 18 files at r2.
Review status: 178 of 195 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by frewsxcv** [comment]
Reviewed 16 of 18 files at r2.
Review status: 194 of 195 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by Wafflespeanut** [comment]
@frewsxcv Sorry again, I forgot to add my changes :)

**Comment by frewsxcv** [comment]
<sup>**[components/canvas/Cargo.toml, line 20 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7698#-JzuFnf48FLPGn-JrsfM)** ([raw file](https://github.com/servo/servo/blob/7a384f69dda46742d92f2612ac3ab2925597f038/components/canvas/Cargo.toml#L20)):</sup>
It should also be removed here

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by frewsxcv** [comment]
<sup>**[components/profile/Cargo.toml, line 14 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7698#-JzuFyR5iC0m_9LP-Pxr)** ([raw file](https://github.com/servo/servo/blob/7a384f69dda46742d92f2612ac3ab2925597f038/components/profile/Cargo.toml#L14)):</sup>
and here

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by Wafflespeanut** [comment]
*sigh*

**Comment by frewsxcv** [comment]
Reviewed 1 of 18 files at r2, 1 of 2 files at r3, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7698)

**Comment by frewsxcv** [comment]
Sorry for the spam, I'm a new reviewer :P (I understand why the previous commands failed)

**Comment by Wafflespeanut** [comment]
@frewsxcv Thanks! :)

**Pull request merged**
