### PR TITLE
Fix #10147: Correctly handle flag local_urls_only

### LINKED ISSUE #10147: Scheme check for local_urls_only is backwards
Step 2 in `main_fetch`; should find some way to test it.

### PR DESCRIPTION
**Pull request by ghost**
In function Request::fetch_main, flag local_urls_only (if set)
should allow fetching local urls only. Before this change, the flag had
the inverse behaviour.

Fixes #10147.
Test with: `./mach test-unit -p net fetch::test_fetch_with_local_urls_only`

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10154)

### CODE REVIEW

**Comment by stjepang** [comment]
+@jdm -@KiChjang

**Comment by KiChjang** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[components/net/fetch/methods.rs, line 1047 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10154#-KDbc-7SkgrB6vCLQ1my:-KDbc-7T_1cIIXKPeAn8:-1500669612) ([raw file](https://github.com/servo/servo/blob/6576fde29bde57148f325f38e1ff04750b5b7389/components/net/fetch/methods.rs#L1047)):*
Not sure why this is better, since the only consumer of this function is in step 2 of main fetch.

---

*[components/net_traits/request.rs, line 261 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10154#-KDbcA3BDMVtvmjSWbGx:-KDbcA3CPXt9424gz8vK:250174081) ([raw file](https://github.com/servo/servo/blob/6576fde29bde57148f325f38e1ff04750b5b7389/components/net_traits/request.rs#L261)):*
This isn't necessary if we instead make Request.local_urls_only a Cell<bool>.

---

*[tests/unit/net/fetch.rs, line 294 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10154#-KDbchA2xmBpnnl7By2F:-KDbchA2xmBpnnl7By2G:-536970368) ([raw file](https://github.com/servo/servo/blob/6576fde29bde57148f325f38e1ff04750b5b7389/tests/unit/net/fetch.rs#L294)):*
Why would this fail? An about scheme is a local scheme, is it not?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10154#-:-KDbdRr2aAY_OtGZqzRo:1458266033)*

**Comment by KiChjang** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10154)*

**Comment by stjepang** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[components/net/fetch/methods.rs, line 1047 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10154#-KDbc-7SkgrB6vCLQ1my:-KDbgeN1ldX4qc458wvw:1677205430) ([raw file](https://github.com/servo/servo/blob/6576fde29bde57148f325f38e1ff04750b5b7389/components/net/fetch/methods.rs#L1047)):*
Just thought the code might be slightly cleaner this way - there are other similar one-shot functions at the end of this file (e.g. `includes_credentials`, `is_simple_method`). That said, I don't have a strong preference for a separate function.

---

*[components/net_traits/request.rs, line 261 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10154#-KDbcA3BDMVtvmjSWbGx:-KDcC3XCHzIH73UGGL5W:-1284376071) ([raw file](https://github.com/servo/servo/blob/6576fde29bde57148f325f38e1ff04750b5b7389/components/net_traits/request.rs#L261)):*
It doesn't even have to be a Cell. I can set this flag directly on a mutable Request. Will remove this fn and do so.

---

*[tests/unit/net/fetch.rs, line 294 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10154#-KDbchA2xmBpnnl7By2F:-KDcBIBrAJmdDXVOtFib:-384802932) ([raw file](https://github.com/servo/servo/blob/6576fde29bde57148f325f38e1ff04750b5b7389/tests/unit/net/fetch.rs#L294)):*
Yep, this is backwards. Sorry, I'll fix it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10154)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[components/net/fetch/methods.rs, line 1047 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10154#-KDbc-7SkgrB6vCLQ1my:-KDcRKCeo9cxXOT4hWqr:-1034259702) ([raw file](https://github.com/servo/servo/blob/6576fde29bde57148f325f38e1ff04750b5b7389/components/net/fetch/methods.rs#L1047)):*
I think this function is short enough to not warrant for another layer of indirection + a stack frame.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10154)*

**Comment by KiChjang** [comment]
@bors-servo r+

Thanks for working on this!

**Pull request merged**
