### PR TITLE
Bug 1417725 - (Servo) Add -moz-column-span alias for column-span prop…

### PR DESCRIPTION
**Pull request by neerjapancholi**
…erty.

This is part of the patch for adding a -moz- alias for column-span. See https://bugzilla.mozilla.org/show_bug.cgi?id=1417725
Clean try run for this patch is at:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=faa9c050c9adf10714953b8c5d5af67683992437&selectedJob=151353901

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19579)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r+

Thanks!

**Comment by jdm** [comment]
```
error[E0425]: cannot find value `GECKO_IS_NIGHTLY` in module `structs`
   --> components/style/context.rs:130:18
    |
130 |         structs::GECKO_IS_NIGHTLY
    |                  ^^^^^^^^^^^^^^^^ not found in `structs`

error[E0425]: cannot find value `GECKO_IS_NIGHTLY` in module `structs`
   --> components/style/gecko/data.rs:186:22
    |
186 |         if !structs::GECKO_IS_NIGHTLY {
    |                      ^^^^^^^^^^^^^^^^ not found in `structs`

error[E0425]: cannot find function `Gecko_RecordTraversalStatistics` in module `bindings`
   --> components/style/gecko/data.rs:193:28
    |
193 |         unsafe { bindings::Gecko_RecordTraversalStatistics(total, parallel,
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find function `Gecko_GetBoolPrefValue` in module `bindings`
   --> components/style/stylesheets/supports_rule.rs:202:24
    |
202 |     unsafe { bindings::Gecko_GetBoolPrefValue(name.as_ptr()) }
    |                        ^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings`

error[E0425]: cannot find value `StylePrefs_sGridTemplateSubgridValueEnabled` in module `mozilla`
   --> components/style/values/specified/grid.rs:333:23
    |
333 |     unsafe { mozilla::StylePrefs_sGridTemplateSubgridValueEnabled }
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `mozilla`

error[E0599]: no function or associated item named `eCSSProperty_overflow_clip_box_inline` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/properties.rs:60109:5
      |
60109 |     nsCSSPropertyID::eCSSProperty_overflow_clip_box_inline => true,
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `eCSSProperty_overflow_clip_box_block` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/properties.rs:60111:5
      |
60111 |     nsCSSPropertyID::eCSSProperty_overflow_clip_box_block => true,
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `eCSSProperty_overflow_clip_box_inline` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/properties.rs:61755:5
      |
61755 |     nsCSSPropertyID::eCSSProperty_overflow_clip_box_inline => {
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `eCSSProperty_overflow_clip_box_block` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/properties.rs:61759:5
      |
61759 |     nsCSSPropertyID::eCSSProperty_overflow_clip_box_block => {
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `eCSSProperty_overflow_clip_box_inline` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/properties.rs:92261:5
      |
92261 |     nsCSSPropertyID::eCSSProperty_overflow_clip_box_inline
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `eCSSProperty_overflow_clip_box_block` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/properties.rs:92265:5
      |
92265 |     nsCSSPropertyID::eCSSProperty_overflow_clip_box_block
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `eCSSProperty_overflow_clip_box_inline` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/properties.rs:99520:5
      |
99520 |     nsCSSPropertyID::eCSSProperty_overflow_clip_box_inline => {
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `eCSSProperty_overflow_clip_box_block` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/properties.rs:99524:5
      |
99524 |     nsCSSPropertyID::eCSSProperty_overflow_clip_box_block => {
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0609]: no field `mOverflowClipBoxInline` on type `gecko_bindings::structs::root::nsStyleDisplay`
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/gecko_properties.rs:13267:20
      |
13267 |         self.gecko.mOverflowClipBoxInline = result;
      |                    ^^^^^^^^^^^^^^^^^^^^^^ did you mean `mOverflowClipBox`?

error[E0609]: no field `mOverflowClipBoxInline` on type `gecko_bindings::structs::root::nsStyleDisplay`
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/gecko_properties.rs:13273:20
      |
13273 |         self.gecko.mOverflowClipBoxInline = other.gecko.mOverflowClipBoxInline;
      |                    ^^^^^^^^^^^^^^^^^^^^^^ did you mean `mOverflowClipBox`?

error[E0609]: no field `mOverflowClipBoxInline` on type `gecko_bindings::structs::root::nsStyleDisplay`
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/gecko_properties.rs:13273:57
      |
13273 |         self.gecko.mOverflowClipBoxInline = other.gecko.mOverflowClipBoxInline;
      |                                                         ^^^^^^^^^^^^^^^^^^^^^^ did you mean `mOverflowClipBox`?

error[E0609]: no field `mOverflowClipBoxInline` on type `gecko_bindings::structs::root::nsStyleDisplay`
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/gecko_properties.rs:13300:26
      |
13300 |         match self.gecko.mOverflowClipBoxInline as u8 {
      |                          ^^^^^^^^^^^^^^^^^^^^^^ did you mean `mOverflowClipBox`?

error[E0609]: no field `mOverflowClipBoxBlock` on type `gecko_bindings::structs::root::nsStyleDisplay`
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/gecko_properties.rs:13320:20
      |
13320 |         self.gecko.mOverflowClipBoxBlock = result;
      |                    ^^^^^^^^^^^^^^^^^^^^^ did you mean `mOverflowClipBox`?

error[E0609]: no field `mOverflowClipBoxBlock` on type `gecko_bindings::structs::root::nsStyleDisplay`
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/gecko_properties.rs:13326:20
      |
13326 |         self.gecko.mOverflowClipBoxBlock = other.gecko.mOverflowClipBoxBlock;
      |                    ^^^^^^^^^^^^^^^^^^^^^ did you mean `mOverflowClipBox`?

error[E0609]: no field `mOverflowClipBoxBlock` on type `gecko_bindings::structs::root::nsStyleDisplay`
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/gecko_properties.rs:13326:56
      |
13326 |         self.gecko.mOverflowClipBoxBlock = other.gecko.mOverflowClipBoxBlock;
      |                                                        ^^^^^^^^^^^^^^^^^^^^^ did you mean `mOverflowClipBox`?

error[E0609]: no field `mOverflowClipBoxBlock` on type `gecko_bindings::structs::root::nsStyleDisplay`
     --> /home/servo/buildbot/slave/linux-rel-css/build/target/geckolib/release/build/style-01d183bc6377c630/out/gecko_properties.rs:13353:26
      |
13353 |         match self.gecko.mOverflowClipBoxBlock as u8 {
      |                          ^^^^^^^^^^^^^^^^^^^^^ did you mean `mOverflowClipBox`?

error: aborting due to 21 previous errors
```

**Comment by emilio** [comment]
Updated the bindings.

@bors-servo r+

**Comment by emilio** [comment]
@bors-servo r+

Now with the right set of bindings.

**Comment by jdm** [comment]
```
error[E0599]: no function or associated item named `eCSSPropertyAlias_MozColumnSpan` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
     --> /Users/servo/buildbot/slave/mac-dev-unit/build/target/geckolib/debug/build/style-55046d2555925070/out/properties.rs:99866:5
      |
99866 |     nsCSSPropertyID::eCSSPropertyAlias_MozColumnSpan => {
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no function or associated item named `eCSSPropertyAlias_MozColumnSpan` found for type `gecko_bindings::structs::root::nsCSSPropertyID` in the current scope
      --> /Users/servo/buildbot/slave/mac-dev-unit/build/target/geckolib/debug/build/style-55046d2555925070/out/properties.rs:138012:5
       |
138012 |     nsCSSPropertyID::eCSSPropertyAlias_MozColumnSpan
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `style`.
```

**Comment by emilio** [comment]
Yikes, forgot to include the Gecko bits. @bors-servo r+

**Comment by jdm** [comment]
@bors-servo: retry
* #19495

**Pull request merged**
