### PR TITLE
Fix `./mach clippy`.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/servo/servo/issues/13117.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14134)

### CODE REVIEW

**Comment by jdm** [comment]
```
110.95s$ ./mach test-tidy --no-progress --all
Checking the config file...
Checking directories for correct file extensions...
Checking files for tidiness...
./components/servo/Cargo.lock:1: duplicate versions for package "semver"
	found dependency on version 0.1.20
	but highest version is 0.2.3
	try upgrading with ./mach cargo-update -p semver:0.1.20
	The following packages depend on version 0.1.20:
		rustc_version
```

**Comment by frewsxcv** [comment]
Addressed in https://github.com/servo/servo/pull/14134/commits/fa8e6c14784413a50ef0c6cdd4d261097d3f4c36.

**Comment by jdm** [comment]
@bors-servo: r+
Woo, semver ecosystems.

**Comment by jdm** [comment]
@bors-servo: retry
* #11100

**Pull request merged**
