### PR TITLE
Fix a few issues

### PR DESCRIPTION
**Pull request by cuzbog**
- Use SmallVec<[T; N]>
- Make find_iframe a free function
- Make ProgressEvent use enums for bubbles and cancelable
- Change README, as `rust-snapshot-hash` is just a text file

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6682)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/script_task.rs, line 1716 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6682#-JuntkqmxauG-zGJa7fQ)** ([raw file](https://github.com/servo/servo/blob/c5e58993ca828d8d0daed716db18c132d2cfdafa/components/script/script_task.rs#L1716)):</sup>
I feel [@Ms2ger 's point](https://github.com/servo/servo/issues/6676#issuecomment-123346761) is more reasonable.

Could you move this method on `Document`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6682)

**Comment by boghison** [comment]
<sup>**[components/script/script_task.rs, line 1716 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6682#-JuntkqmxauG-zGJa7fQ)** ([raw file](https://github.com/servo/servo/blob/c5e58993ca828d8d0daed716db18c132d2cfdafa/components/script/script_task.rs#L1716)):</sup>
[Here](https://github.com/servo/servo/blob/master/components/script/dom/document.rs#L1021) or in `DocumentHelpers`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6682)

**Comment by jdm** [comment]
DocumentHelpers makes sense.

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6682)

**Pull request merged**
