### PR TITLE
Constellation: removed almost all opts::get

### PR DESCRIPTION
**Pull request by oneturkmen**
Removed *almost* all (except 1) "opts::get()" from `constellation` component. The one untouched is in `pipeline.rs` which uses "opts::get()" as a [struct field](https://github.com/oneturkmen/servo/blob/cd153efb4acce81170927790653555c5f10929eb/components/constellation/pipeline.rs#L501) that is set [here](https://github.com/oneturkmen/servo/blob/cd153efb4acce81170927790653555c5f10929eb/components/constellation/pipeline.rs#L296).

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix *partially* #22854 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because no feature (or no bug) has been added (refactoring only).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23506)

### CODE REVIEW

**Comment by oneturkmen** [comment]
@jdm r?

**Comment by jdm** [comment]
Looks good! We should be able to remove remaining Opts usage from this code after we finish converting the remaining crates, since it's only used to call `opts::set_options` in components/servo/lib.rs.

**Comment by oneturkmen** [comment]
@jdm it seems that it failed when downloading cmake - `Error downloading cmake-3.14.3: [Errno 10054] An existing connection was forcibly closed by the remote host. The failing URL was: https://servo-deps.s3.amazonaws.com/msvc-deps/cmake-3.14.3.zip`. Is there any way to restart this?

**Comment by jdm** [comment]
@bors-servo retry
* network issue

**Pull request merged**
