### PR TITLE
Add --with-debug-assertions flag for Mach

### LINKED ISSUE #14009: Add a `mach` argument to enable debug assertions
Follow up from #13387.

`mach` currently honors the `SERVO_ENABLE_DEBUG_ASSERTIONS` environment variable to enable debug assertions. To make this option more discoverable and better documented, add a `mach` flag that does the same thing.

IMO, we can also remove the code that checks for and acts on the environment variable.

Files:
- python/servo/build_commands.py
- etc/ci/buildbot_steps.yml (pass the new flag for the `linux-rel-wpt` and `linux-rel-css` builders)

Tests:
- I can't think of a good automated test, so manual testing is probably fine.

cc @emilio @Ms2ger

### PR DESCRIPTION
**Pull request by ghost**
I tested out building a release with the flag and added a `debug_assert!(false)` in `fn main` and it panicked.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14009  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they are manually tested

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14025)

### CODE REVIEW

**Comment by aneeshusa** [comment]
LGTM overall, just one question.

@larsbergstrom Do we need to add the `--with-debug-assertions` to the `build-cef` steps as well in `etc/ci/buildbot_steps.yml`?

**Comment by larsbergstrom** [comment]
Yes, please add them to the `build-cef` steps, too. Otherwise, CEF will rebuild everything.

**Comment by larsbergstrom** [comment]
Yes, please add them to the `build-cef` steps, too. Otherwise, CEF will rebuild everything.

**Comment by Wafflespeanut** [comment]
Squash the commits please.

**Comment by iamrohit7** [comment]
@Wafflespeanut Done :)

**Review by ghost — APPROVED** [review]
Thanks!

**Comment by Wafflespeanut** [comment]
Oh, right. bors is configured only to listen to comments, not review comments.

@bors-servo r+

**Pull request merged**
