### PR TITLE
replace use of load_whole_resource in net/image_cache_task.rs with Fi…

### LINKED ISSUE #8402: Replace load_whole_resource in image cache with reading from a file
We call `load_whole_resource` in `image_cache_task.rs`, but all we're actually doing is reading from a `file://` URL. We can do this more clearly by opening the file using the [regular APIs](http://rustbyexample.com/std_misc/file/open.html) and reading the contents instead. This will get us closer to being able to remove the `load_whole_resource` API in the future.

Code: `components/net/image_cache_task.rs`

### PR DESCRIPTION
**Pull request by ajnirp**
…le::open

Fixes #8402.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8405)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/net/image_cache_task.rs, line 466 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8405#-K2bFnuNCF-Iu7xsj69Q)** ([raw file](https://github.com/servo/servo/blob/236fddf1f9ea05c7295efef3f20ffb6347edf389/components/net/image_cache_task.rs#L466)):</sup>
I'd rather not ignore this error. You could make this

```rust
let result = File::open(&placeholder_path).and_then(|mut file| {
    file.read_to_end(&mut image_data)
});
let placeholder_image = result.ok().map(|image_data| {
    Arc::new(load_from_memory(&image_data).unwrap())
});
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8405)

**Comment by wenderen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/net/image_cache_task.rs, line 466 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8405#-K2bFnuNCF-Iu7xsj69Q)** ([raw file](https://github.com/servo/servo/blob/236fddf1f9ea05c7295efef3f20ffb6347edf389/components/net/image_cache_task.rs#L466)):</sup>
i agree


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8405)

**Comment by Ms2ger** [comment]
Looks good, please squash these commits and ping me.

-S-awaiting-review +S-needs-squash 


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8405)

**Comment by wenderen** [comment]
ping @Ms2ger

**Comment by Ms2ger** [comment]
Thanks!

**Pull request merged**
