### PR TITLE
Introduce trait Castable

### PR DESCRIPTION
**Pull request by nox**
Removes all those messy FooCast structures in InheritTypes.rs.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8041)

### CODE REVIEW

**Comment by jdm** [comment]
I got through the first two commits.


---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: 2 of 84 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8041)

**Comment by eefriedman** [comment]
It's probably a good idea to always specify the type of downcasts, even if the compiler can technically infer the expected type, it's difficult to read.  For example, in one case the type of a downcast is deduced based on the fact that LayoutHTMLInputElementHelpers is the only trait which currently has a method called "get_size_for_layout".

**Comment by nox** [comment]
@eefriedman I don't think so. The case you found maybe is surprising, but not much more than some Deref coercions we already have all over the place. In other occurrences, removing the type really helps readability:

```rust
    fn get_html_element(&self) -> Option<Root<HTMLHtmlElement>> {
        self.GetDocumentElement().and_then(Root::downcast)
    }
```

**Comment by jdm** [comment]
-S-awaiting-review 


---

Reviewed 82 of 82 files at r3, 66 of 66 files at r4, 40 of 40 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/conversions.rs, line 112 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8041#-K15ZYuMZoHbPKR7cHiX)** ([raw file](https://github.com/servo/servo/blob/0d68684c08b63af57af57441e909a8fa3fae9991/components/script/dom/bindings/conversions.rs#L112)):</sup>
It's not clear to me that these traits belong in this file. Maybe we should have an inheritance.rs in bindings/?


---

<sup>**[components/script/dom/domimplementation.rs, line 118 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8041#-K15tATYzcTpM6IAMaRA)** ([raw file](https://github.com/servo/servo/blob/523555ef3b4ea48eb389c16008a335830bae8226/components/script/dom/domimplementation.rs#L118)):</sup>
I'm not thrilled with these rewrites of assert; I feel like the purpose of unwrap is less clear.


---

<sup>**[components/script/dom/htmltableelement.rs, line 66 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8041#-K15w2uPR8-dXZG9mAo-)** ([raw file](https://github.com/servo/servo/blob/523555ef3b4ea48eb389c16008a335830bae8226/components/script/dom/htmltableelement.rs#L66)):</sup>
Same comment about assert! as earlier.


---

<sup>**[components/script/dom/htmltableelement.rs, line 105 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8041#-K15vyTNQh-LLgY-XyhR)** ([raw file](https://github.com/servo/servo/blob/523555ef3b4ea48eb389c16008a335830bae8226/components/script/dom/htmltableelement.rs#L105)):</sup>
Same comment about assert! as earlier.


---

<sup>**[components/script/parse/html.rs, line 128 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8041#-K15zyZH6Wz_AXV0wBaX)** ([raw file](https://github.com/servo/servo/blob/523555ef3b4ea48eb389c16008a335830bae8226/components/script/parse/html.rs#L128)):</sup>
Same assert comment.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8041)

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/conversions.rs, line 112 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8041#-K15ZYuMZoHbPKR7cHiX)** ([raw file](https://github.com/servo/servo/blob/0d68684c08b63af57af57441e909a8fa3fae9991/components/script/dom/bindings/conversions.rs#L112)):</sup>
Well, these are conversions. I feel like we should make a round of patches to move around pieces of code, introducing new modules in the process, but that feels a bit out of scope.


---

<sup>**[components/script/dom/domimplementation.rs, line 118 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8041#-K15tATYzcTpM6IAMaRA)** ([raw file](https://github.com/servo/servo/blob/523555ef3b4ea48eb389c16008a335830bae8226/components/script/dom/domimplementation.rs#L118)):</sup>
What about an expect call? I don't really like assert that actually do important things. I'm pretty sure we have more unwrap calls than we have uses of assert in such cases.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8041)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/conversions.rs, line 112 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8041#-K15ZYuMZoHbPKR7cHiX)** ([raw file](https://github.com/servo/servo/blob/0d68684c08b63af57af57441e909a8fa3fae9991/components/script/dom/bindings/conversions.rs#L112)):</sup>
File a followup issue, please. Everything else in this file is related to converting to/from JS values.


---

<sup>**[components/script/dom/domimplementation.rs, line 118 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8041#-K15tATYzcTpM6IAMaRA)** ([raw file](https://github.com/servo/servo/blob/523555ef3b4ea48eb389c16008a335830bae8226/components/script/dom/domimplementation.rs#L118)):</sup>
That's fair. I'd be ok with either
``rust
let result = doc_node.AppendChild(doc_type.upcast());
assert!(result.is_ok());
```
or expect.
<!-- Reviewable comment -K1626QxuGVBvZH-J3vk:1633268150 -->

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8041)
<!-- Sent from Reviewable.io -->

**Comment by nox** [comment]
@jdm Rebased and addressed, I would appreciate it if I don't need to ever rebase that again. ;)

**Comment by nox** [comment]
Added a commit to fix #8125.

**Comment by jdm** [comment]
@bors-servo: r+
https://www.youtube.com/watch?v=FnpJBkAMk44


---

Reviewed 35 of 35 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8041)

**Pull request merged**
