### PR TITLE
Do not run faster than 60 FPS

### LINKED ISSUE #25305: Useless calls from the embedder
Follow up of #25263.

The number of calls from the embedder to Servo can be absurdly high. 300K+ per seconds.

The way we let the embedder know about the running animation state and run animations is spaghetti-esque. A mix of #21855 and #20379 issues.

This is how we would expect animations to work:

1. animation happens Layout
2. let the compositor know
3. let the embedder know
4. embedder runs full speed and block on swapbuffer.

But:

Step 2, letting the compositor know, triggers the compositor proxy to wake up the embedder loop which will run a `compositor.perform_update()` call which triggers compositing.
Now goes step 3, animating is set to animating.
Step 4, compositor won't swap the buffer because nothing needs to be done, compositing has already happened in step 2.

Adding to that the fact that AnimationState is sent at each tick, and we don't end the animation properly, and there is nothing to animate, the embedder calls perform_update full speed, and block on nothing, ending up with 300K+ calls per seconds.

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #25305

### CODE REVIEW

**Comment by atouchet** [comment]
Does this limit Servo to running at 60 FPS? Would it make sense to instead use the display's refresh rate?

**Comment by paulrouget** [comment]
If the monitor is cadenced at 120 FPS, it will force Servo to run at 60 FPS.

We could rely on https://docs.rs/winit/0.20.0-alpha4/winit/monitor/struct.VideoMode.html#method.refresh_rate

We should also maybe only sleep if not call to `compositor::composite` happen.

This is an improvement non the less.

**Comment by atouchet** [comment]
> If the monitor is cadenced at 120 FPS, it will force Servo to run at 60 FPS.

What about displays that don't run at multiples of 60 (ex. 75, 90, 144, etc.)?

**Comment by paulrouget** [comment]
Servo will always run at 60FPS max.

This is not the best approach. Open to suggestions.

**Comment by atouchet** [comment]
Using that winit method instead of assuming 60 seems like a reasonable idea to me.

**Comment by Manishearth** [comment]
cc @asajeffrey thoughts on this?

**Review by Manishearth — APPROVED** [review]
Approach seems fine by me but I'm not sure if this is the right way to do this.

**Comment by asajeffrey** [comment]
Can we avoid blocking the main thread? The embedder may have things they want to do on the main thread at more than 60fps. If nothing else we should make the number 60 configurable, e.g. for devices that run at 120fps.

**Comment by paulrouget** [comment]
Closing this as this starting to look more complex that I initially imagined. See #25305.

**Pull request closed without merging**
