### PR TITLE
Implement DOMPoint and DOMPointReadOnly

### PR DESCRIPTION
**Pull request by tschneidereit**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6683)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 6 of 6 files at r1, 40 of 40 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/dompoint.rs, line 13 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6683#-Jun1umsy2A8GE7JLkb6)** ([raw file](https://github.com/servo/servo/blob/102a87487815e9348d62c76601c5c9cc51c9e1f6/components/script/dom/dompoint.rs#L13)):</sup>
Spec pointer somewhere around here.

---

<sup>**[components/script/dom/dompoint.rs, line 50 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6683#-Jun5-dEW5hDqCTJ7O2i)** ([raw file](https://github.com/servo/servo/blob/102a87487815e9348d62c76601c5c9cc51c9e1f6/components/script/dom/dompoint.rs#L50)):</sup>
`-> ()` is typically only written out in generated code.

---

<sup>**[components/script/dom/dompointreadonly.rs, line 13 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6683#-Jun4vwyBxWwcjtVkiwd)** ([raw file](https://github.com/servo/servo/blob/102a87487815e9348d62c76601c5c9cc51c9e1f6/components/script/dom/dompointreadonly.rs#L13)):</sup>
Spec link

---

<sup>**[components/script/dom/dompointreadonly.rs, line 58 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6683#-Jun4o1KlCUue4WbUbcx)** ([raw file](https://github.com/servo/servo/blob/102a87487815e9348d62c76601c5c9cc51c9e1f6/components/script/dom/dompointreadonly.rs#L58)):</sup>
Rm

---

<sup>**[components/script/dom/webidls/DOMPoint.webidl, line 13 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6683#-Jun2Pnk6zm9NNkxzlyV)** ([raw file](https://github.com/servo/servo/blob/102a87487815e9348d62c76601c5c9cc51c9e1f6/components/script/dom/webidls/DOMPoint.webidl#L13)):</sup>
No Pref.

---

<sup>**[components/script/dom/webidls/DOMPoint.webidl, line 14 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6683#-Jun2U68PevNrZSm65wh)** ([raw file](https://github.com/servo/servo/blob/102a87487815e9348d62c76601c5c9cc51c9e1f6/components/script/dom/webidls/DOMPoint.webidl#L14)):</sup>
This constructor doesn't exist in the spec for some irresponsible reason.

---

<sup>**[components/script/dom/webidls/DOMPointReadOnly.webidl, line 13 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6683#-Jun213D-Osl1_WebMo7)** ([raw file](https://github.com/servo/servo/blob/102a87487815e9348d62c76601c5c9cc51c9e1f6/components/script/dom/webidls/DOMPointReadOnly.webidl#L13)):</sup>
No Pref, and needs a spec link for the interface. Also needs a constructor.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6683)

**Comment by tschneidereit** [comment]
Thanks for the review, I think this addresses all comments. As discussed on IRC, I left out the `DOMPoint(ReadOnly).fromPoint` implementations because they're not implemented anywhere yet and might go away. Removing the `DOMPointInit`-using constructor and making `DOMPointReadOnly` constructible made more than half of the tests fail, but given that that's what the spec says, that's probably the tests' fault.
r? @Ms2ger

---

Review status: 39 of 46 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/dompoint.rs, line 50 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6683#-Jun5-dEW5hDqCTJ7O2i)** ([raw file](https://github.com/servo/servo/blob/102a87487815e9348d62c76601c5c9cc51c9e1f6/components/script/dom/dompoint.rs#L50)):</sup>
Right, I just copied the definitions from the generated bindings, but should've cleaned them up.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6683)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-squash 

Squash all four commits and ping me, please.

---

Reviewed 4 of 4 files at r3, 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6683)

**Comment by jdm** [comment]
```

/_mozilla/mozilla/interfaces.html
---------------------------------
FAIL Interfaces exposed on the window
```

**Pull request merged**
