### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20675)

### CODE REVIEW

**Comment by CYBAI** [comment]
```
2018-04-21 15:49:57.987 rustc[8131:1870962019] Metadata.framework [Error]: couldn't get the client port
error[E0308]: mismatched types
   --> components/gfx/platform/macos/font.rs:218:20
    |
218 |         FontWeight(normalized * 100.)
    |                    ^^^^^^^^^^^^^^^^^ expected f32, found f64

error: aborting due to previous error
```

**Comment by CYBAI** [comment]
```
   Compiling style_tests v0.0.1 (file:///C:/buildbot/slave/windows-msvc-dev/build/tests/unit/style)
error[E0308]: mismatched types
   --> components\gfx\platform\windows\font.rs:160:38
    |
160 |         let weight = StyleFontWeight(weight_val);
    |                                      ^^^^^^^^^^ expected f32, found u16
help: you can cast an `u16` to `f32`, producing the floating point representation of the integer
    |
160 |         let weight = StyleFontWeight(weight_val.into());
    |                                      ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `gfx`.
```

**Comment by emilio** [comment]
Alright, one platform at a time, thanks @CYBAI!

**Comment by emilio** [comment]
So those fails are invalid tests that are fixed in WPT upstream. The passes are expected, will update.

**Comment by Manishearth** [comment]
r=me for that one commit.

the rest seem to have been reviewed already, so r+

**Comment by emilio** [comment]
@bors-servo retry

 * Infra: Servers failed to start.

**Comment by CYBAI** [comment]
In [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/8581):
<details>
<pre>
<code>
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value 850 for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37236, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value 850.3 for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37237, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(100 + 300) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37238, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(0.2 + 205.5) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37239, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(0 - 100) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37240, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(200 + 801) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37241, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 99", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56441, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 99", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56444, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 349", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56453, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 550", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56464, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 550", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56467, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 749", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56470, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 749", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56473, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 750", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56509, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 750", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56510, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 899", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56511, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 899", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56512, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 901", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56515, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 901", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 56516, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Values that are not multiple of 100 should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58600, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Non-integer Values should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58601, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Minimum allowed value should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58602, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Maximum allowed value should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58605, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Simple calc value", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58607, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Negative simple calc value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58608, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Out-of-range simple calc value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58609, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Valid calc expression", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58610, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Valid calc expression with out-of-range value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58611, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Values that are not multiple of 100 should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58617, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Non-integer Values should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58618, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Minimum allowed value should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58619, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Maximum allowed value should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58620, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Simple calc value", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58621, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Negative simple calc value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58622, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Out-of-range simple calc value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58623, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Valid calc expression", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58624, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Valid calc expression with out-of-range value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 58625, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: Font weight specified as number", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 119773, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: Font weight specified as calc()", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 119776, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: Font weight specified as calc(), value smaller than 1", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 119777, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: Font weight specified as calc(), value greater than 1000", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 119778, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: 'oblique' followed by valid small weight", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 119784, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: 'oblique' followed by valid calc() weight", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 119788, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: 'oblique' followed by a to-be-clamped calc() weight", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 119790, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: calc() weight folowed by 'oblique'", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 119791, "action": "test_result", "expected": "FAIL"}
</code>
</pre>
</details>

In [mac-rel-wpt4](http://build.servo.org/builders/mac-rel-wpt4/builds/4176):
<details>
<pre>
<code>
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value 850 for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 21312, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value 850.3 for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 21313, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(100 + 300) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 21314, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(0.2 + 205.5) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 21315, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(0 - 100) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 21316, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(200 + 801) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 21317, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: Font weight specified as number", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 21400, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: Font weight specified as calc()", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 21403, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: Font weight specified as calc(), value smaller than 1", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 21404, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: Font weight specified as calc(), value greater than 1000", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 21405, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: 'oblique' followed by valid small weight", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 21411, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: 'oblique' followed by valid calc() weight", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 21415, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: 'oblique' followed by a to-be-clamped calc() weight", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 21417, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Font shorthand: calc() weight folowed by 'oblique'", "test": "/css/css-fonts/variations/font-shorthand.html", "line": 21418, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 99", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21562, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 99", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21563, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 349", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21567, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 550", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21572, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 550", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21573, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 749", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21574, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 749", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21575, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 750", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21576, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 750", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21577, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 899", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21578, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 899", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21579, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test lighter font-weight for base weight 901", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21582, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Test bolder font-weight for base weight 901", "test": "/css/css-fonts/variations/font-weight-lighter-bolder.html", "line": 21583, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Values that are not multiple of 100 should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86788, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Non-integer Values should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86789, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Minimum allowed value should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86790, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Maximum allowed value should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86793, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Simple calc value", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86795, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Negative simple calc value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86796, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Out-of-range simple calc value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86797, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Valid calc expression", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86798, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "@supports: Valid calc expression with out-of-range value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86799, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Values that are not multiple of 100 should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86805, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Non-integer Values should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86806, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Minimum allowed value should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86807, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Maximum allowed value should be parsed successfully", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86808, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Simple calc value", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86809, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Negative simple calc value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86810, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Out-of-range simple calc value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86811, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Valid calc expression", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86812, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Computed style: Valid calc expression with out-of-range value (to be clamped)", "test": "/css/css-fonts/variations/font-weight-parsing.html", "line": 86813, "action": "test_result", "expected": "FAIL"}
</code>
</pre>
</details>

In [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/8584):
<details>
<pre>
<code>
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/CSS2/margin-padding-clear/padding-top-072.xht", "line": 14922, "action": "test_result", "expected": "PASS"}
</code>
</pre>
</details>

**Comment by CYBAI** [comment]
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value 850 for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37448, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value 850.3 for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37449, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(100 + 300) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37450, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(0.2 + 205.5) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37451, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(0 - 100) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37452, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Valid value calc(200 + 801) for font property weight used for styling.", "test": "/css/css-fonts/variations/font-parse-numeric-stretch-style-weight.html", "line": 37453, "action": "test_result", "expected": "FAIL"}
```

**Comment by emilio** [comment]
@bors-servo retry

 #JustInfraThings

**Comment by emilio** [comment]
superceded by #20692

**Pull request closed without merging**
