### PR TITLE
build: Try to use shared LLVM libraries for OSMesa.

### LINKED ISSUE #7: llvm linking build break
I have a build break on my Ubuntu 14.04

```
configure: WARNING: Building mesa with statically linked LLVM may cause compilation issues
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5b7): undefined reference to `setupterm'
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5e0): undefined reference to `tigetnum'
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5e9): undefined reference to `set_curterm'
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5f1): undefined reference to `del_curterm'
collect2: error: ld returned 1 exit status
```

Is it connected with this issue: https://github.com/rust-lang/rust/issues/36854 ? How to make it build?

### PR DESCRIPTION
**Pull request by emilio**
This fixes https://github.com/servo/osmesa-src/issues/7

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18889)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r-
Travis is failing

**Comment by emilio** [comment]
This landed.

**Pull request closed without merging**
