### PR TITLE
Bump bitflags to 1.0

### PR DESCRIPTION
**Pull request by Eijebong**
See #18809 

Still haven't had time to test it but it should fix the tests failures that appeared in m-c

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18967)

### CODE REVIEW

**Comment by emilio** [comment]
./mach build-geckolib seems to fail:

```
error[E0425]: cannot find value `NS_DOCUMENT_STATE_RTL_LOCALE` in module `element_state`
--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:202:66
|
202 | NonTSPseudoClass::MozLocaleDir(..) => element_state::NS_DOCUMENT_STATE_RTL_LOCALE,
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `element_state`
error[E0425]: cannot find value `NS_DOCUMENT_STATE_WINDOW_INACTIVE` in module `element_state`
--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:203:67
|
203 | NonTSPseudoClass::MozWindowInactive => element_state::NS_DOCUMENT_STATE_WINDOW_INACTIVE,
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `element_state`
error: aborting due to 2 previous errors
error: Could not compile `style`.
To learn more, run the command again with --verbose.
[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
GeckoLib build completed in 0:01:46
The command "./mach build-geckolib" exited with 101.
42.68s$ ./mach test-stylo
Compiling size_of_test v0.0.1 (file:///home/travis/build/servo/servo/components/size_of_test)
Compiling stylo_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/stylo)
Compiling style v0.0.1 (file:///home/travis/build/servo/servo/components/style)
error[E0425]: cannot find value `NS_DOCUMENT_STATE_RTL_LOCALE` in module `element_state`
--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:202:66
|
202 | NonTSPseudoClass::MozLocaleDir(..) => element_state::NS_DOCUMENT_STATE_RTL_LOCALE,
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `element_state`
error[E0425]: cannot find value `NS_DOCUMENT_STATE_WINDOW_INACTIVE` in module `element_state`
--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:203:67
|
203 | NonTSPseudoClass::MozWindowInactive => element_state::NS_DOCUMENT_STATE_WINDOW_INACTIVE,
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `element_state`error[E0425]: cannot find value `NS_DOCUMENT_STATE_RTL_LOCALE` in module `element_state`
--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:202:66
|
202 | NonTSPseudoClass::MozLocaleDir(..) => element_state::NS_DOCUMENT_STATE_RTL_LOCALE,
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `element_state`
error[E0425]: cannot find value `NS_DOCUMENT_STATE_WINDOW_INACTIVE` in module `element_state`
--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:203:67
|
203 | NonTSPseudoClass::MozWindowInactive => element_state::NS_DOCUMENT_STATE_WINDOW_INACTIVE,
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `element_state`
error: aborting due to 2 previous errors
error: Could not compile `style`.
To learn more, run the command again with --verbose.
[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
GeckoLib build completed in 0:01:46
The command "./mach build-geckolib" exited with 101.
42.68s$ ./mach test-stylo
Compiling size_of_test v0.0.1 (file:///home/travis/build/servo/servo/components/size_of_test)
Compiling stylo_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/stylo)
Compiling style v0.0.1 (file:///home/travis/build/servo/servo/components/style)
error[E0425]: cannot find value `NS_DOCUMENT_STATE_RTL_LOCALE` in module `element_state`
--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:202:66
|
202 | NonTSPseudoClass::MozLocaleDir(..) => element_state::NS_DOCUMENT_STATE_RTL_LOCALE,
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `element_state`
error[E0425]: cannot find value `NS_DOCUMENT_STATE_WINDOW_INACTIVE` in module `element_state`
--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:203:67
|
203 | NonTSPseudoClass::MozWindowInactive => element_state::NS_DOCUMENT_STATE_WINDOW_INACTIVE,
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `element_state`

**Comment by Eijebong** [comment]
Yeah, I failed my rebase ^^

**Comment by jdm** [comment]
Geckolib still fails :)
```
error[E0599]: no associated item named `NS_DOCUMENT_STATE_RTL_LOCALE` found for type `element_state::ElementState` in the current scope

--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:202:51

|

202 | NonTSPseudoClass::MozLocaleDir(..) => ElementState::NS_DOCUMENT_STATE_RTL_LOCALE,

| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

|

= help: items from traits can only be used if the trait is implemented and in scope

= note: the following traits define an item `NS_DOCUMENT_STATE_RTL_LOCALE`, perhaps you need to implement one of them:

candidate #1: `<element_state::DocumentState as std::fmt::Debug>::fmt::__BitFlags`

candidate #2: `element_state::DocumentState::all::__BitFlags`

error[E0599]: no associated item named `NS_DOCUMENT_STATE_WINDOW_INACTIVE` found for type `element_state::ElementState` in the current scope

--> /home/travis/build/servo/servo/components/style/gecko/selector_parser.rs:203:52

|

203 | NonTSPseudoClass::MozWindowInactive => ElementState::NS_DOCUMENT_STATE_WINDOW_INACTIVE,

| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

|

= help: items from traits can only be used if the trait is implemented and in scope

= note: the following traits define an item `NS_DOCUMENT_STATE_WINDOW_INACTIVE`, perhaps you need to implement one of them:

candidate #1: `<element_state::DocumentState as std::fmt::Debug>::fmt::__BitFlags`

candidate #2: `element_state::DocumentState::all::__BitFlags`

error: aborting due to 2 previous errors

error: Could not compile `style`.
```

**Comment by Eijebong** [comment]
geckotry: https://treeherder.mozilla.org/#/jobs?repo=try&revision=86d1cd3505d3181f44ef4b43a5e083b0bae00b7a

**Comment by Eijebong** [comment]
Fixed those 3 'layout/style' tests

**Comment by Eijebong** [comment]
Gecko try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=b6f08bd2e1d6f158e3dca65d950e237c06e23799

**Review by mbrubeck — APPROVED** [review]
r=mbrubeck with the merge conflict resolved

**Comment by Eijebong** [comment]
Rebased

**Comment by mbrubeck** [comment]
@bors-servo p=1

(high bitrot risk)

**Pull request merged**
