### PR TITLE
Implement HTMLFormElement::Elements

### LINKED ISSUE #8566: Add HTMLFormControlsCollection interface
Tracking issue for https://github.com/servo/servo/pull/7845

Depends on the outcome of: https://github.com/whatwg/html/issues/200

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes #8566

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9237)

### CODE REVIEW

**Comment by frewsxcv** [comment]
@bors-servo r-

Sorry, I noticed something is wrong. I'll let you know when I fix it

**Comment by frewsxcv** [comment]
Fixed the issue (incorrect comments). Reviewable again

**Comment by KiChjang** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9237)*

**Comment by KiChjang** [comment]
@bors-servo retry
* SSL snafu

**Comment by frewsxcv** [comment]
tidy issues addressed

@bors-servo r=KiChjang

**Comment by KiChjang** [comment]
@bors-servo retry
* #9163

**Pull request merged**
