### PR TITLE
Add detailed instructions on setting up virtualenv to the README

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @metajack 

The previous instructions for installing virtualenv were a bit vague, so I decided to add some detail.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15370)

### CODE REVIEW

**Comment by UK992** [comment]
I think this step is rather confusing, because pip is installed by MSI installer by default.

**Comment by metajack** [comment]
I agree. Is the issue that we need C:\Python27\Scripts in the path as well as C:\Python?

**Comment by UK992** [comment]
Yes, but this shouldn't be a problem, by checking "Add python.exe to Path" feature, it's added to PATH too.

**Comment by larsbergstrom** [comment]
Hrm, that's not consistent with what I saw (i.e., `Scripts` was not added to the `PATH` when just the root directory was by the installer). But I'll close this for now until we can investigate further.

**Pull request closed without merging**
