### PR TITLE
Fix Android build errors on macOS.

### LINKED ISSUE #15758: Issues while Building servo for Android (on macOS Sierra)
I followed the instructions on the Wiki, using NDK r12b with toolchain api version set to 18.

While compiling with `./mach build --release --android`,
I encountered the following error messages:

```
error: failed to run custom build command for `backtrace-sys v0.1.8`
process didn't exit successfully: `/Users/#####/servo/target/release/build/backtrace-sys-5fc1b69b154456a4/build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("3")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("arm-linux-androideabi")
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
CC_arm-linux-androideabi = None
CC_arm_linux_androideabi = None
TARGET_CC = None
CC = None
TARGET = Some("arm-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
CFLAGS_arm-linux-androideabi = None
CFLAGS_arm_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = Some("--sysroot /Users/#####/Library/Android/sdk/ndk-bundle-r12b/platforms/android-18/arch-arm -I/Users/#####/Library/Android/sdk/ndk-bundle-r12b/sources/android/support/include")
PROFILE = Some("release")
running: "/Users/#####/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.8/src/libbacktrace/configure" "--with-pic" "--disable-multilib" "--disable-shared" "--disable-host-shared" "--target=arm-linux-androideabi" "--host=x86_64-apple-darwin"
checking build system type... x86_64-apple-darwin16.4.0
checking host system type... x86_64-apple-darwin
checking target system type... arm-unknown-linux-androideabi
checking for x86_64-apple-darwin-gcc... arm-linux-androideabi-gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... yes
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-linux-androideabi-gcc accepts -g... yes
checking for arm-linux-androideabi-gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /lib/cpp

--- stderr
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
configure: error: in `/Users/#####/servo/target/arm-linux-androideabi/release/build/backtrace-sys-433a9460a3cdf227/out':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details.
thread 'main' panicked at 'failed with: exit code: 1', /Users/#####/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.8/build.rs:129
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

In the config.log,
I'm seeing some error messages like this:

```
configure:3435: arm-linux-androideabi-gcc -E  conftest.c
In file included from /Users/#####/Library/Android/sdk/ndk-bundle-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/include-fixed/syslimits.h:7:0,
                 from /Users/#####/Library/Android/sdk/ndk-bundle-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/include-fixed/limits.h:34,
                 from conftest.c:10:
/Users/#####/Library/Android/sdk/ndk-bundle-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/include-fixed/limits.h:168:61: error: no include path in which to search for limits.h
 #include_next <limits.h>  /* recurse down to the real one */
```

Would be great if someone can shed some light on this issue.
Maybe I did something obviously wrong :/

### PR DESCRIPTION
**Pull request by jhlin**
- Add sysroot path to environment variable 'CPPFLAGS':
  When checking C preprocessor, the 'configure' script of libbacktrace uses 'CPPFLAGS' rather than 'CFLAGS' and doesn't get the correct search path. (#15758)
  This check passes on Linux because the '/lib/cpp' fallback is available there.

- Introduce CMake toolchain file for Android cross compiling:
  CMake needs several variables [1] to cross compile for Android.
  It works (accidentally) on Linux because cmake-rs sets compilers correctly and binutils for Linux & Android are pretty much the same.

[1] https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-android-with-the-ndk

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15758 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it's a fix to build errors.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18031)

### CODE REVIEW

**Comment by MortimerGoro** [comment]
This is great, thanks for doing it!

**Comment by jhlin** [comment]
Hi @mbrubeck, it's been a while since this PR is created. What do you think of it?

**Comment by mbrubeck** [comment]
@bors-servo r+

Oops, sorry for the delay.  This looks good!

**Pull request merged**
