### PR TITLE
add readonly pathname function in location

### PR DESCRIPTION
**Pull request by yodalee**
issue #5397

### CODE REVIEW

**Comment by metajack** [comment]
Assigning @jdm since he did the review.

**Comment by metajack** [comment]
@yodalee Josh reviewed this and comments are in critic.

**Comment by yodalee** [comment]
Modified.

**Comment by jdm** [comment]
This will require updating some test expectations, too: http://mxr.mozilla.org/servo/search?string=pathname

**Comment by jdm** [comment]
In future please continue adding new commits, instead of amending the existing ones. The critic review is no longer useful after force pushing :(

**Comment by yodalee** [comment]
But that will create a lot of commits, isn't it?

**Comment by Ms2ger** [comment]
We will let you squash before merging. Right now you're just making our life harder for no good reason.

**Comment by yodalee** [comment]
I didn't find test passed after running `test-wpt`.

**Comment by jdm** [comment]
Ah, as long as you've tried the tests then that's fine. Thanks!

**Comment by yodalee** [comment]
Should I modify the ini for those passed tests not fixed by this PR?

**Comment by jdm** [comment]
Yeah, all of those tests make use of location.pathname :)

**Comment by yodalee** [comment]
Should I changed metadata of those `FAIL expected NOTRUN`?

**Comment by yodalee** [comment]
I will be not able to connect internet later (no internet in my living place). I just push a commit that modifies the tests setting files, hope it works.

**Comment by jdm** [comment]
It's almost correct, but it's missing changes for 
/workers/interfaces/WorkerGlobalScope/location/members.html. If you don't get to it, I'll fix it later today.

**Comment by yodalee** [comment]
The metadata of `members.html` has already been delete. Isn't this means this PR make the test fail?

**Comment by yodalee** [comment]
I just push the commit includes `members.html.ini`.

**Comment by jdm** [comment]
Yes, this change seems to be enough to cause the test to finish executing and notice a failure. You'll need to create a new ini file for it like:
```
[members.html]
  type: testharness
  expected: FAIL
```

**Comment by yodalee** [comment]
Added.

**Comment by jdm** [comment]
Ah, my mistake. The new ini should be more like 
```
[members.html]
  type: testharness
  [members of WorkerLocation]
    expected: FAIL
```

**Comment by yodalee** [comment]
fixed

**Comment by yodalee** [comment]
I found that most `getter` in location is now able to implement. Can I open an issue for that?

**Comment by yodalee** [comment]
I found that most `getter` in location is now able to implement. Can I open an issue for that?

**Comment by jdm** [comment]
Absolutely!

**Pull request merged**
