### PR TITLE
Add cancellability to file manager load and related refactoring

### LINKED ISSUE #12589: Utilise cancel listener for reading content from file manager
See `net/blob_loader.rs` for where the cancel listener is introduced, and it is currently not utilised.

After #12577 is landed, this would be a problem since we can choose to cancel early rather than keep reading.

But here is actually some problem to do that -- the `CancellationListener` defined in `resource_thread.rs` can't be sent over some ipc-channel to the `FileManager`.

### PR DESCRIPTION
**Pull request by izgzhen**
Fixes #12589.

r? @Manishearth 

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12589 
- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12684)

### CODE REVIEW

**Comment by izgzhen** [comment]
Another patch for mis-design :/

**Comment by Manishearth** [comment]
@bors-servo r+

Don't worry about the mis-design, happens all the time 😄

**Comment by Manishearth** [comment]
@bors-servo r-

needs rebase

**Comment by izgzhen** [comment]
done

**Comment by KiChjang** [comment]
@bors-servo retry
* #12701

**Pull request merged**
