### PR TITLE
Clean up Node::ReplaceChild

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6783)

### CODE REVIEW

**Comment by dzbarsky** [comment]
Also tweaks the step ordering to account for how the spec will change after https://github.com/whatwg/dom/issues/59

**Comment by Ms2ger** [comment]
Is the step 9/10 swap script-detectable? If so, test

**Comment by dzbarsky** [comment]
That change is needed because otherwise the mutation record may end up with a null previousSibling rather than the correct one.  Since we don't implement MutationObserver yet, that change is not script-detectable in current Servo. It may make more sense to add this test when we implement MutationObserver, what do you think @nox ?

**Comment by nox** [comment]
@dzbarsky You should either not swap and rely on child == node being short-circuited currently in the absence of mutation observers, or swap and check whether node was child's previous sibling, your change breaks replaceChild if they are equal.

**Comment by dzbarsky** [comment]
I wasn't sure what "check whether node was child's previous sibling" meant so I undid the swap for now. We can fix it when we implement mutation observers.

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6783)

**Pull request merged**
