### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22645)

### CODE REVIEW

**Comment by emilio** [comment]
I think this is mostly straight-forward, but https://github.com/servo/servo/pull/22645/commits/ac8317a5c735ad1283350ffdda515fb06e64c6fe probably deserves some review.

r? @jdm / @nox / @SimonSapin for that?

@bors-servo try

**Comment by emilio** [comment]
Well that's a lot of broken tests, but the few I took a look at was just a logic error in margin collapsing which I introduced. Should be fixed now.

@bors-servo try=wpt

**Comment by emilio** [comment]
@bors-servo try=wpt

 * Now with tidy passing.

**Comment by emilio** [comment]
Alright, those were two expected new passes \o/.

**Comment by emilio** [comment]
The hash of the interesting commit now is https://github.com/servo/servo/pull/22645/commits/83f0286cb75b08feaf116ac424e1db00db799f21.

**Comment by emilio** [comment]
cc @mbrubeck, which I forgot about in my previous comment, in case you feel like it :)

**Comment by emilio** [comment]
Review of that commit in #22641, whoops.

@bors-servo r=emilio,mbrubeck

**Comment by CYBAI** [comment]
@bors-servo retry

```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/normal-flow/block-formatting-context-height-002.xht 293911574a59c7f3947436264557174a97acc7a5\n/css/CSS2/reference/ref-filled-black-96px-square.xht f73d1fa4091b541ed29c5bc4f99358740860d9e8\nTesting 293911574a59c7f3947436264557174a97acc7a5 == f73d1fa4091b541ed29c5bc4f99358740860d9e8", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/normal-flow/block-formatting-context-height-002.xht", 
    "line": 12443, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/_mozilla/css/floats_percentage_width_a.html eff35a4d6501e47e30663f90d48e5c67ff1b9036\n/_mozilla/css/floats_percentage_width_ref.html 7f9d03440f202f4fc3640fcba59efac763583039\nTesting eff35a4d6501e47e30663f90d48e5c67ff1b9036 == 7f9d03440f202f4fc3640fcba59efac763583039", 
    "stack": null, 
    "subtest": null, 
    "test": "/_mozilla/css/floats_percentage_width_a.html", 
    "line": 33947, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Comment by CYBAI** [comment]
@bors-servo retry

- #21067

**Comment by CYBAI** [comment]
I found this test case `FAIL` again 👀

```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/normal-flow/block-formatting-context-height-002.xht 293911574a59c7f3947436264557174a97acc7a5\n/css/CSS2/reference/ref-filled-black-96px-square.xht f73d1fa4091b541ed29c5bc4f99358740860d9e8\nTesting 293911574a59c7f3947436264557174a97acc7a5 == f73d1fa4091b541ed29c5bc4f99358740860d9e8", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/normal-flow/block-formatting-context-height-002.xht", 
    "line": 12380, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/_mozilla/css/floats_percentage_width_a.html eff35a4d6501e47e30663f90d48e5c67ff1b9036\n/_mozilla/css/floats_percentage_width_ref.html 7f9d03440f202f4fc3640fcba59efac763583039\nTesting eff35a4d6501e47e30663f90d48e5c67ff1b9036 == 7f9d03440f202f4fc3640fcba59efac763583039", 
    "stack": null, 
    "subtest": null, 
    "test": "/_mozilla/css/floats_percentage_width_a.html", 
    "line": 34141, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Comment by emilio** [comment]
@bors-servo r=emilio,mbrubeck

 * Was a typo in my patch:

```rust
diff --git a/components/layout/floats.rs b/components/layout/floats.rs
index e6a9b048a3..5a58e27f9d 100644
--- a/components/layout/floats.rs
+++ b/components/layout/floats.rs
@@ -551,7 +551,7 @@ impl SpeculatedFloatPlacement {
                 let fixed = match inline_size {
                     LengthPercentageOrAuto::Auto => false,
                     LengthPercentageOrAuto::LengthPercentage(ref lp) => {
-                        lp.is_definitely_zero() || lp.maybe_to_used_value(None).is_none()
+                        lp.is_definitely_zero() || lp.maybe_to_used_value(None).is_some()
                     },
                 };
                 if !fixed {
```

**Pull request merged**
