### PR TITLE
[WIP] style_derive: Allow omitting generation of bounds on fields in the ToCss deriver.

### PR DESCRIPTION
**Pull request by jyc**
Add a new `#[omit_to_css_bounds]` attribute on variants in an enum with
`#[derive(ToCss)]`. A variant `V(F1, F2, ...)` normally generates bounds on the
ToCss implementation `where F1: ToCss, F2: ToCss, ...`

This is problematic in following case:

    // Sort of what we will have for type custom CSS variable values.
    #[derive(ToCss)]
    pub enum E {
        V(Vec<E>)
    }

    // Sort of what we have in style_traits/values.rs.
    impl<T> ToCss for Vec<T> where T: ToCss {
        ...
    }

The generated implementation of `ToCss` for `E` looks like

    impl ToCss for E where Vec<E>: ToCss {
        ...
    }

... which creates a cycle, and the compiler exits with error E0257.

The `Vec<E>: ToCss` bound is not actually necessary, so with this commit we can
omit its generation with `#[omit_to_css_bounds]`. It would be cool if in the
future we could decide when to omit such bounds automatically.

For reference, what serde did is generate bounds for type parameters used in
fields only. See https://github.com/serde-rs/serde/pull/456 . I tried that and
it didn't seem to work with style::values::generics::BasicShape, however, maybe
because Circle in that module doesn't implement ToCss.

---

- [X] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] How should I test this? It's used in a later series, and I couldn't find other tests for this macro.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17349)

### CODE REVIEW

**Comment by nox** [comment]
I have plans for `#[derive(ToCss)]` for sequences (`Vec<T>` and any other similar type) that I have yet to implement, just don't use `derive` for such properties for now.

**Comment by jyc** [comment]
Thanks! When do you plan on implementing those, though (and what are your plans)? Hoping to land the patches that need these soon.

**Comment by nox** [comment]
I would recommend just writing the ToCss impl for now, or wrapping the Vec in its own type with a short ToCss impl.

I can work on sequences tomorrow if you want. Basically I want to make `#[css(sequence)]` and `#[css(sequence = ", ")]`, which would for any T such as `for<'a> &'a T: IntoIterator, <T as IntoIterator>::Item: ToCss>`.

**Comment by jyc** [comment]
Thanks again! Couldn't wrap Vec in it's own type with a ToCss impl because it's defined in a different module--I ended up extending the existing OneOrMoreCommaSeparated trait to allow different separators too (in particular spaces). Now I have `OneOrMoreSeparated`, and people write things like `impl OneOrMoreSeparated for UnicodeRange { type S = CommaSeparator; }
`. Is that related? Couldn't remove it entirely because of how Parser uses that type [https://github.com/servo/servo/blob/master/components/style/parser.rs#L164].

**Comment by nox** [comment]
I just realised that doesn't solve the circular trait bound though. :)

I've always thought we add too many trait bounds to parameterised derived impls, so I'll just work on fixing that tomorrow, which will make this PR unnecessary AFAIK.

Adding the impls for fields are necessary when we have fields with types `Foo<T>` where T is some type parameter of the derived impl, in case there is no `ToCss` impl for `Foo<T>` that works for all `T`.

A trait bound should only be added if the field type is a type parameterised by any derived type parameter. So in your case, given `Vec<E>` is only parameterised by `Self`, no bound should be added.

**Comment by jyc** [comment]
Cool! Yep, as noted in the commit message this is exactly the same as what serde did, see serde-rs/serde#456. Definitely would be better if you could do what they did! Thanks!

**Comment by nox** [comment]
We should really look into encoding all the details of how serde proceeds and making some convenience functions in syn or synstructure to do the same more easily, I'm tired of duplicating code between `HasViewPercentage`, `ToComputedValue` and `ToCss`. :)

**Comment by jyc** [comment]
Closing this because @nox has a better fix in #17356!

**Pull request closed without merging**
