### PR TITLE
style: Add support for parsing and serialization of <basic-shape>s

### PR DESCRIPTION
**Pull request by Manishearth**
Still WIP: I still need to use this somewhere and make serialization minimal. I'm not sure if I should do either in this PR.
The only other browser that handles basic shapes doesn't serialize correctly either (https://bugzilla.mozilla.org/show_bug.cgi?id=1290864), so that's not something we need to get done now.

As far as using this somewhere, I have the following options:
- Merge this now, work on using it in stylo in a followup.
- Just write extensive unit tests for parsing/serialization for now (stylo in a followup)
- Use this for clip-path in stylo only (which I intend to do anyway, just not sure if I should do it in this PR)
- Use this for clip-path in Servo (I'd rather not do this; this would be a huge change requiring a lot more layout knowledge than I currently have)

Thoughts? Review? @SimonSapin @bholley

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12680)

### CODE REVIEW

**Comment by nox** [comment]
```
./components/style/values/computed/basic_shape.rs:11: use statement is not in alphabetical order
	expected: values::computed::{BorderRadiusSize, LengthOrPercentage}
	found: values::computed::position::Position
./components/style/values/computed/basic_shape.rs:12: use statement is not in alphabetical order
	expected: values::computed::position::Position
	found: std::fmt
./components/style/values/computed/basic_shape.rs:13: use statement is not in alphabetical order
	expected: std::fmt
	found: cssparser::ToCss
./components/style/values/computed/basic_shape.rs:90: operators should go at the end of the first line
./components/style/values/computed/position.rs:12: use statement is not in alphabetical order
	expected: values::computed::LengthOrPercentage
	found: std::fmt
./components/style/values/specified/basic_shape.rs:12: use statement is not in alphabetical order
	expected: std::fmt
	found: cssparser::{Parser, ToCss}
./components/style/values/specified/basic_shape.rs:15: use statement is not in alphabetical order
	expected: values::specified::{BorderRadiusSize, Length, LengthOrPercentage}
	found: values::specified::position::{Position, PositionComponent}
./components/style/values/specified/basic_shape.rs:16: use statement is not in alphabetical order
	expected: values::specified::position::{Position, PositionComponent}
	found: values::computed::{Context, ToComputedValue, ComputedValueAsSpecified}
./components/style/values/specified/basic_shape.rs:17: use statement is not in alphabetical order
	expected: values::computed::{Context, ToComputedValue, ComputedValueAsSpecified}
	found: values::computed::basic_shape as computed_basic_shape
./components/style/values/specified/basic_shape.rs:90: missing space after ,
./components/style/values/specified/basic_shape.rs:90: missing space after ,
./components/style/values/specified/basic_shape.rs:90: missing space after ,
./components/style/values/specified/basic_shape.rs:234: operators should go at the end of the first line
./components/style/values/specified/position.rs:155: no newline at EOF
./components/style/values/specified/position.rs:11: use statement is not in alphabetical order
	expected: std::fmt
	found: cssparser::{Parser, ToCss, Token}
./components/style/values/specified/position.rs:14: use statement is not in alphabetical order
	expected: values::specified::{LengthOrPercentage, Percentage}
	found: values::computed::{Context, ToComputedValue}
./components/style/values/specified/position.rs:15: encountered whitespace following a use statement
```

**Comment by Manishearth** [comment]
We decided in the meeting to take the second option -- write unit tests, and in a later PR hook this up to stylo

**Comment by bholley** [comment]
Sounds good - I wouldn't spend too much time on the unit tests, basic smoketests are probably fine. We can test more when we have the stylo glue :-)

**Comment by Manishearth** [comment]
wfm

**Comment by Manishearth** [comment]
Ready for review; r? @bholley

**Comment by Manishearth** [comment]
Fixed up the four-value serialization too. This doesn't fix the serialization of border-radius sadly, because we don't use ToCss there :/

**Comment by SimonSapin** [comment]
To make it easier to navigate Reviewable, when addressing comments please push additional commits without squashing or rebasing until review is done.

---

Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 8 of 8 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, 5 of 5 files at r6, 4 of 4 files at r7, 4 of 4 files at r8, 2 of 2 files at r9, 4 of 4 files at r10, 5 of 5 files at r11.
Review status: all files reviewed at latest revision, 31 unresolved discussions.

---

*[components/style/properties/longhand/background.mako.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL4yWA0Vh5lc9I5fKH:-KOL4yWBYYG7qIa6ga1N:-1244053401) ([raw file](https://github.com/servo/servo/blob/44e33bcdc593bb3e5a8d4833e506ff135c082419/components/style/properties/longhand/background.mako.rs#L90)):*
> ```Rust
>             #[derive(PartialEq, Copy, Clone, Debug)]
>             #[cfg_attr(feature = "servo", derive(HeapSizeOf))]
>             pub struct T(pub Position);
> ```

Could this be a type alias or reexport rather than a newtype?

---

*[components/style/values/computed/basic_shape.rs, line 59 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL0jv_AD2earJ-kHXr:-KOL0jva1g3k-2Q2FHqq:-1752911286) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/computed/basic_shape.rs#L59)):*
> ```Rust
>     pub top_left: BorderRadiusSize,
>     pub top_right: BorderRadiusSize,
>     pub bottom_left: BorderRadiusSize,
> ```

The field order is in incorrect: bottom_right comes before bottom_left. (The order is: clockwise starting at top-left, not reading order of two lines of latin text.) The order not strictly important in the struct definition, but given the same bug happens in places it is important let’s make everything consistent.

---

*[components/style/values/computed/basic_shape.rs, line 75 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL0XMHhHOIYSCgj9XW:-KOL0XMINGdCRZwDH2R1:437194400) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/computed/basic_shape.rs#L75)):*
> ```Rust
>         try!(self.top_right.0.width.to_css(dest));
>         try!(dest.write_str(" "));
>         try!(self.bottom_left.0.width.to_css(dest));
> ```

Incorrect order.

---

*[components/style/values/computed/basic_shape.rs, line 83 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL1FC0uhJ0mVo_sgS0:-KOL1FC0uhJ0mVo_sgS1:437194400) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/computed/basic_shape.rs#L83)):*
> ```Rust
>         try!(self.top_right.0.height.to_css(dest));
>         try!(dest.write_str(" "));
>         try!(self.bottom_left.0.height.to_css(dest));
> ```

Incorrect order.

---

*[components/style/values/computed/basic_shape.rs, line 73 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL7qoPVV_dZd57IZy2:-KOL7qoPVV_dZd57IZy3:-1203327640) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/computed/basic_shape.rs#L73)):*
> ```Rust
>     fn to_css<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
>         try!(self.radius.to_css(dest));
>         try!(dest.write_str(" at "));
> ```

Maybe omit this if the position is the default `50% 50%`? What do other impls do?

---

*[components/style/values/computed/basic_shape.rs, line 83 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLDinXqCCxoPVpmHPg:-KOLDinY4NhJLeM9OY1r:-233329717) ([raw file](https://github.com/servo/servo/blob/78ce65d5a8e04939717b1cb455b79440e71f8ef9/components/style/values/computed/basic_shape.rs#L83)):*
> ```Rust
> pub struct Ellipse {
>     pub semiaxis_a: ShapeRadius,
>     pub semiaxis_b: ShapeRadius,
> ```

Why call them a and b rather than x and y?

---

*[components/style/values/computed/basic_shape.rs, line 90 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLDIkwODDU_aMoF7SV:-KOLDIkxXCON_QcgkdOs:-74876629) ([raw file](https://github.com/servo/servo/blob/78ce65d5a8e04939717b1cb455b79440e71f8ef9/components/style/values/computed/basic_shape.rs#L90)):*
> ```Rust
>     fn to_css<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
>         if ShapeRadius::ClosestSide != self.semiaxis_a
>             && ShapeRadius::ClosestSide != self.semiaxis_b {
> ```

I think you want `||` instead of `&&` here. But to be clearer, use tuple comparison: `if (self.semiaxis_a, self.semiaxis_b) != (ShapeRadius::ClosestSide, ShapeRadius::ClosestSide)`.

Or maybe even `if (self.semiaxis_a, self.semiaxis_b) != Default::default()` works?

---

*[components/style/values/computed/basic_shape.rs, line 30 \[r6\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLGujWJRpoyypEv2fk:-KOLGujXXmmDlUsdFjfy:148825214) ([raw file](https://github.com/servo/servo/blob/eb82cc25efab89d34f15c47568a8a21234be492b/components/style/values/computed/basic_shape.rs#L30)):*
> ```Rust
>             BasicShape::Circle(circle) => circle.to_css(dest),
>             BasicShape::Ellipse(e) => e.to_css(dest),
>             BasicShape::Polygon(ref poly) => poly.to_css(dest),
> ```

Nit: add `ref` to the other cases to avoid a copy (though the optimizer might remove it, I don’t know). Same in `match *self` in other methods.

---

*[components/style/values/computed/basic_shape.rs, line 122 \[r6\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLHaiHjLyO0v3VRFew:-KOLHaiIwEjSADzsSv39:-831520524) ([raw file](https://github.com/servo/servo/blob/eb82cc25efab89d34f15c47568a8a21234be492b/components/style/values/computed/basic_shape.rs#L122)):*
> ```Rust
>             try!(coord.0.to_css(dest));
>             try!(dest.write_str(" "));
>             try!(coord.1.to_css(dest));
> ```

Needs a comma here. `#` means comma-separated repetition: https://drafts.csswg.org/css-values/#mult-comma

---

*[components/style/values/computed/basic_shape.rs, line 191 \[r6\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLHjM_H7GONu32hE0i:-KOLHjMaM_6SRFAHDTc8:1032087741) ([raw file](https://github.com/servo/servo/blob/eb82cc25efab89d34f15c47568a8a21234be492b/components/style/values/computed/basic_shape.rs#L191)):*
> ```Rust
> }
> 
> pub use values::specified::basic_shape::FillRule;
> ```

Nit: move this to the top of the file?

---

*[components/style/values/specified/basic_shape.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL1689nGh79H3brHlg:-KOL168DS22AwrAkzeEG:437194400) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/specified/basic_shape.rs#L135)):*
> ```Rust
>     pub top_left: BorderRadiusSize,
>     pub top_right: BorderRadiusSize,
>     pub bottom_left: BorderRadiusSize,
> ```

Incorrect order.

---

*[components/style/values/specified/basic_shape.rs, line 151 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL-gUn2FFqwKoMxq5j:-KOL-gUn2FFqwKoMxq5k:437194400) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/specified/basic_shape.rs#L151)):*
> ```Rust
>         try!(self.top_right.0.width.to_css(dest));
>         try!(dest.write_str(" "));
>         try!(self.bottom_left.0.width.to_css(dest));
> ```

Incorrect order.

---

*[components/style/values/specified/basic_shape.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL-wKoT4nDYoi2yGF8:-KOL-wKoT4nDYoi2yGF9:437194400) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/specified/basic_shape.rs#L159)):*
> ```Rust
>         try!(self.top_right.0.height.to_css(dest));
>         try!(dest.write_str(" "));
>         try!(self.bottom_left.0.height.to_css(dest));
> ```

Incorrect order.

---

*[components/style/values/specified/basic_shape.rs, line 169 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL-BUotipzylNLg9TV:-KOL-BUpaiCQdDecyr0M:-296562870) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/specified/basic_shape.rs#L169)):*
> ```Rust
>     pub fn parse(input: &mut Parser) -> Result<BorderRadius, ()> {
>         let widths = try!(parse_one_set_of_border_values(input));
>         let mut heights = widths.clone();
> ```

Nit: rather than assigning to `heights` twice, use something like `let heights = if …`

---

*[components/style/values/specified/basic_shape.rs, line 176 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL04YhkgGJlvaWBS49:-KOL04YhkgGJlvaWBS4A:437194400) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/specified/basic_shape.rs#L176)):*
> ```Rust
>             top_left: BorderRadiusSize::new(widths[1], heights[1]),
>             top_right: BorderRadiusSize::new(widths[2], heights[2]),
>             bottom_left: BorderRadiusSize::new(widths[3], heights[3]),
> ```

Incorrect order.

---

*[components/style/values/specified/basic_shape.rs, line 177 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL-28lhWCbhL98x9g4:-KOL-28moLqZLdscNvxX:-154951943) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/specified/basic_shape.rs#L177)):*
> ```Rust
>             top_right: BorderRadiusSize::new(widths[2], heights[2]),
>             bottom_left: BorderRadiusSize::new(widths[3], heights[3]),
>             bottom_right: BorderRadiusSize::new(widths[4], heights[4]),
> ```

Indices should be 0 to 3 rather than 1 to 4, right? (Did any test fail with this?)

---

*[components/style/values/specified/basic_shape.rs, line 186 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL20mbgnxPJ0KB4JXF:-KOL20mcuGiRKeUNcm0I:1725650757) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/specified/basic_shape.rs#L186)):*
> ```Rust
>     let mut count = 0;
>     let mut values = [LengthOrPercentage::Length(Length::Absolute(Au(0))); 4];
>     while count < 4 {
> ```

Nit: `for value in &mut values` would look nicer than `while` with a counter. Or even unrolled:

```rust
    let a = try!(LengthOrPercentage::parse(input));
    let b = if let Ok(b) = input.try(LengthOrPercentage::parse) {
        b
    } else {
        return Ok([a, a, a, a])
    };
    let c = if let Ok(c) = input.try(LengthOrPercentage::parse) {
        c
    } else {
        return Ok([a, b, a, b])
    };
    if let Ok(d) = input.try(LengthOrPercentage::parse) {
        Ok([a, b, c, d])
    } else {
        Ok([a, b, c, b])
    }
```

---

*[components/style/values/specified/basic_shape.rs, line 19 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL7zFehTUqXC-QKKhq:-KOL7zFehTUqXC-QKKhr:-2051256632) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/specified/basic_shape.rs#L19)):*
> ```Rust
> use values::specified::{Length, LengthOrPercentage};
> use values::specified::BorderRadiusSize;
> use values::specified::position::{Position, PositionComponent};
> ```

Note that css-shapes references `<position>` from css-backgrounds-3, while this `Position` type currently implements CSS 2. Level 3 generalize the grammar to allow things like `right 10px bottom 20px` which means 10px from the right side horizontally, and 20px from the bottom side vertically.

Please either extend `Position` or file a follow-up issue.

---

*[components/style/values/specified/basic_shape.rs, line 142 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL9Isnph1ZbNI1LNxv:-KOL9Isnph1ZbNI1LNxw:-33387840) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/specified/basic_shape.rs#L142)):*
> ```Rust
> 
> impl Circle {
>     pub fn parse(input: &mut Parser) -> Result<Circle, ()> {
> ```

Nit: maybe inline `parse` for each specific shapes into `BasicShape::parse`, in order to have only one `expect_function()` call?

---

*[components/style/values/specified/basic_shape.rs, line 150 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL9ZwVJjVbEJqBiTS4:-KOL9ZwVJjVbEJqBiTS5:296680624) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/specified/basic_shape.rs#L150)):*
> ```Rust
>         }
>     }
>     pub fn parse_function(input: &mut Parser) -> Result<Circle, ()> {
> ```

Nit: rename to `parse_function_arguments` (and same in `InsetRect`).

---

*[components/style/values/specified/basic_shape.rs, line 156 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLAE-fpzlXXUs0OH0K:-KOLAE-ge2C8POLaHD9v:1615691754) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/specified/basic_shape.rs#L156)):*
> ```Rust
>         } else {
>             // Defaults to origin
>             try!(Position::new(PositionComponent::Center, PositionComponent::Center))
> ```

Nit: use a struct literal here to avoid `try!`.

---

*[components/style/values/specified/basic_shape.rs, line 171 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL86sFEgBIfxBY0s-F:-KOL86sFEgBIfxBY0s-G:-803196106) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/specified/basic_shape.rs#L171)):*
> ```Rust
>             try!(dest.write_str(" "));
>         }
>         try!(dest.write_str("at "));
> ```

Maybe omit this if the position is the default `center center`?

---

*[components/style/values/specified/basic_shape.rs, line 196 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLF1SEFynFvn5pIGvt:-KOLF1SF8EwSwG4Fim1p:-506292943) ([raw file](https://github.com/servo/servo/blob/78ce65d5a8e04939717b1cb455b79440e71f8ef9/components/style/values/specified/basic_shape.rs#L196)):*
> ```Rust
> pub struct Ellipse {
>     pub semiaxis_a: ShapeRadius,
>     pub semiaxis_b: ShapeRadius,
> ```

Same comment as above re a/b vs x/y.

---

*[components/style/values/specified/basic_shape.rs, line 213 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLFFbKoimFkdYE4Z_p:-KOLFFbKoimFkdYE4Z_q:1080739015) ([raw file](https://github.com/servo/servo/blob/78ce65d5a8e04939717b1cb455b79440e71f8ef9/components/style/values/specified/basic_shape.rs#L213)):*
> ```Rust
>         let (a, b) = input.try(|input| -> Result<_, ()> {
>             Ok((try!(ShapeRadius::parse(input)), try!(ShapeRadius::parse(input))))
>         }).unwrap_or((Default::default(), Default::default()));
> ```

Nit: `.ok().unwrap_or_default()`

---

*[components/style/values/specified/basic_shape.rs, line 218 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLF_AEnIdizY6oyQ_J:-KOLF_AEnIdizY6oyQ_K:619479118) ([raw file](https://github.com/servo/servo/blob/78ce65d5a8e04939717b1cb455b79440e71f8ef9/components/style/values/specified/basic_shape.rs#L218)):*
> ```Rust
>         } else {
>             // Defaults to origin
>             try!(Position::new(PositionComponent::Center, PositionComponent::Center))
> ```

Nit: use a struct literal to avoid `try!`.

---

*[components/style/values/specified/basic_shape.rs, line 231 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLFl4TWFf6fQaGpcWE:-KOLFl4TWFf6fQaGpcWF:960017208) ([raw file](https://github.com/servo/servo/blob/78ce65d5a8e04939717b1cb455b79440e71f8ef9/components/style/values/specified/basic_shape.rs#L231)):*
> ```Rust
>     fn to_css<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
>         if ShapeRadius::ClosestSide != self.semiaxis_a
>             && ShapeRadius::ClosestSide != self.semiaxis_b {
> ```

Same as above re `||` vs `&&` and tuple comparison.

---

*[components/style/values/specified/basic_shape.rs, line 288 \[r6\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLI2r0anNtnaitA35S:-KOLI2r4AYtextjWrBDL:-1107033873) ([raw file](https://github.com/servo/servo/blob/eb82cc25efab89d34f15c47568a8a21234be492b/components/style/values/specified/basic_shape.rs#L288)):*
> ```Rust
>         while !input.is_exhausted() {
>             buf.push((try!(LengthOrPercentage::parse(input)),
>                       try!(LengthOrPercentage::parse(input))));
> ```

Needs to look for comma here. `#` means comma-separated repetition: https://drafts.csswg.org/css-values/#mult-comma

Use `input.parse_comma_separated`, it’s designed exactly for this. (It also requires at least one item.)

---

*[components/style/values/specified/basic_shape.rs, line 311 \[r6\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLIQNpFTpMSTp6bEip:-KOLIQNpFTpMSTp6bEiq:-1974119091) ([raw file](https://github.com/servo/servo/blob/eb82cc25efab89d34f15c47568a8a21234be492b/components/style/values/specified/basic_shape.rs#L311)):*
> ```Rust
>             try!(dest.write_str(" "));
>             try!(coord.1.to_css(dest));
>             need_space = true;
> ```

Needs comma

---

*[tests/unit/style/parsing/basic_shape.rs, line 84 \[r10\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLNqIsFElJaK67lHsV:-KOLNqIt_5ZIee6aN0bx:1247101992) ([raw file](https://github.com/servo/servo/blob/c6feae3c5ce2a25dfd809699eb0b8d2a96c1816e/tests/unit/style/parsing/basic_shape.rs#L84)):*
> ```Rust
>     // not at least 3
>     assert_roundtrip_basicshape!(Polygon::parse, "polygon(10px 10px)", "polygon(10px 10px)");
>     assert_roundtrip_basicshape!(Polygon::parse, "polygon(10px 10px 10px 10px)", "polygon(10px 10px 10px 10px)");
> ```

Needs commas.

---

*[tests/unit/style/parsing/mod.rs, line 23 \[r10\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLN79WAtMaehujuvzu:-KOLN79XtmukjstmwTjW:-1656726992) ([raw file](https://github.com/servo/servo/blob/c6feae3c5ce2a25dfd809699eb0b8d2a96c1816e/tests/unit/style/parsing/mod.rs#L23)):*
> ```Rust
>         ::cssparser::ToCss::to_css(&parsed, &mut serialized)
>                         .expect("Failed to serialize");
>         assert_eq!(serialized, $output);
> ```

Please also test that parse(serialize(x)) is idempotent:

```rust
        let parsed_again = $crate::parsing::parse($fun, serialized)
                        .expect(&format!("Failed to parse {}", serialized));
        let mut serialized_again = String::new();
        ::cssparser::ToCss::to_css(&parsed, &mut serialized_again)
                        .expect("Failed to serialize");
        assert_eq!(serialized_again, $output)
```

---

*[tests/unit/style/parsing/mod.rs, line 14 \[r11\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLOcvuBYiQpY7NFscq:-KOLOcvvlV6xyYBhsRqZ:698566471) ([raw file](https://github.com/servo/servo/blob/d1e45f78afaba96d55034e59befe32d6445e7148/tests/unit/style/parsing/mod.rs#L14)):*
> ```Rust
> }
> 
> fn to_string<T: ToCss>(x: T) -> String {
> ```

The `ToCss` trait has a `to_css_string` default method doing this. Please use it instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12680#-:-KOLEjDNsq36g4HAM12S:1686540522)*

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 30 unresolved discussions.

---

*[components/style/values/specified/basic_shape.rs, line 19 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL7zFehTUqXC-QKKhq:-KOLPO5ge7K1CgLf7QKm:1314496606) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/specified/basic_shape.rs#L19)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Note that css-shapes references `<position>` from css-backgrounds-3, while this `Position` type currently implements CSS 2. Level 3 generalize the grammar to allow things like `right 10px bottom 20px` which means 10px from the right side horizontally, and 20px from the bottom side vertically.
> 
> Please either extend `Position` or file a follow-up issue.
</details>
Never mind, I see that you’ve already filed https://github.com/servo/servo/issues/12690

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12680)*

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 30 unresolved discussions.

---

*[components/style/properties/longhand/background.mako.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL4yWA0Vh5lc9I5fKH:-KOOLUj9Yu1ydjxqC9Z6:b-lre28e) ([raw file](https://github.com/servo/servo/blob/44e33bcdc593bb3e5a8d4833e506ff135c082419/components/style/properties/longhand/background.mako.rs#L90)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Could this be a type alias or reexport rather than a newtype?
</details>
I think there's mako-generated code that depends on it being local. I tried doing this during the array PR, and had some issues which I can't quite recall. We also do this elsewhere -- if you want I can try move us to type aliases in a followup.

---

*[components/style/values/computed/basic_shape.rs, line 73 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL7qoPVV_dZd57IZy2:-KOOMuQcLwtTJe43DdQo:b-i3ydz4) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/computed/basic_shape.rs#L73)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Maybe omit this if the position is the default `50% 50%`? What do other impls do?
</details>
The spec explicitly gives `circle(at center)` as serializing to `circle(at 50% 50%)`. It does say that defaults should be omitted, but it also says that positions should only serialize to their 2 or 4 value form, so the "0 value form" is probably excluded.

---

*[components/style/values/computed/basic_shape.rs, line 90 \[r5\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOLDIkwODDU_aMoF7SV:-KOOMkYKwduUbheMl7c5:b-hfurwb) ([raw file](https://github.com/servo/servo/blob/78ce65d5a8e04939717b1cb455b79440e71f8ef9/components/style/values/computed/basic_shape.rs#L90)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> I think you want `||` instead of `&&` here. But to be clearer, use tuple comparison: `if (self.semiaxis_a, self.semiaxis_b) != (ShapeRadius::ClosestSide, ShapeRadius::ClosestSide)`.
> 
> Or maybe even `if (self.semiaxis_a, self.semiaxis_b) != Default::default()` works?
</details>
Heh, I'd fixed that in one of the two files only

---

*[components/style/values/specified/basic_shape.rs, line 177 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL-28lhWCbhL98x9g4:-KOOPPSdeJIIuP9WcAYo:b-bd8kk5) ([raw file](https://github.com/servo/servo/blob/2580c1dc6ea3fbec337a31a38ab1a3abf6d2a90c/components/style/values/specified/basic_shape.rs#L177)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Indices should be 0 to 3 rather than 1 to 4, right? (Did any test fail with this?)
</details>
(this was fixed)

---

*[components/style/values/specified/basic_shape.rs, line 142 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL9Isnph1ZbNI1LNxv:-KOONYQpCly5aMSB3VrR:b-5dxljg) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/specified/basic_shape.rs#L142)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Nit: maybe inline `parse` for each specific shapes into `BasicShape::parse`, in order to have only one `expect_function()` call?
</details>
This makes it easier to test though.I'll keep parse around, but inline it in BasicShape

---

*[components/style/values/specified/basic_shape.rs, line 171 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL86sFEgBIfxBY0s-F:-KOOOMNPGomhRyl1v_2I:b-yajk6h) ([raw file](https://github.com/servo/servo/blob/77f345476f480fe1b7e2e74cfffd4510725d866b/components/style/values/specified/basic_shape.rs#L171)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Maybe omit this if the position is the default `center center`?
</details>
Can't, spec has explicit examples against

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12680)*

**Comment by SimonSapin** [comment]
:lgtm: Looks good! Squash if you like and r=me

---

Reviewed 2 of 2 files at r12, 2 of 2 files at r13, 2 of 2 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/properties/longhand/background.mako.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOL4yWA0Vh5lc9I5fKH:-KOPOXk-mdKKV7tspPnh:1166273418) ([raw file](https://github.com/servo/servo/blob/44e33bcdc593bb3e5a8d4833e506ff135c082419/components/style/properties/longhand/background.mako.rs#L90)):*
<details><summary><i>Previously, Manishearth (Manish Goregaokar) wrote…</i></summary>
> I think there's mako-generated code that depends on it being local. I tried doing this during the array PR, and had some issues which I can't quite recall. We also do this elsewhere -- if you want I can try move us to type aliases in a followup.
</details>
That’s not necessary. This was rather "simplify this slightly if it’s easy to do so".

---

*[tests/unit/style/parsing/basic_shape.rs, line 23 \[r14\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOPQH4QRaKscKFIFiBo:-KOPQH4RbEp1nKSLa_lF:161671434) ([raw file](https://github.com/servo/servo/blob/77fdeea821b35bfc0fe282d0a8c27976f396f454/tests/unit/style/parsing/basic_shape.rs#L23)):*
> ```Rust
>                           .expect(&format!("Failed parsing {} as border radius",
>                                   $input));
>         assert_eq!(::cssparser::ToCss::to_css_string(&input.top_left.0.width), $tlw);
> ```

Nit: does `foo.to_css_string()` method syntax not work here, with the trait `use`d?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12680#-:-KOPQlhEfaeZKfKhrPIB:1430225051)*

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/unit/style/parsing/basic_shape.rs, line 23 \[r14\]](https://reviewable.io:443/reviews/servo/servo/12680#-KOPQH4QRaKscKFIFiBo:-KOPS1DYdywY1lObaTUB:b-s7obh1) ([raw file](https://github.com/servo/servo/blob/234219cd842f1593c1eef3f39c91c5438f9f425e/tests/unit/style/parsing/basic_shape.rs#L23)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Nit: does `foo.to_css_string()` method syntax not work here, with the trait `use`d?
</details>
Can't `use` in a macro without the use getting duplicated.  I could import it on the top of the file, but in general in macros the style is to make them portable and use UFCS, so I'm doing that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12680)*

**Pull request merged**
