### PR TITLE
Make JS runnables for workers execute on correct event loop

### LINKED ISSUE #24812: JS runnables from worker threads do not run on the correct event loop
Running https://github.com/MozillaReality/hello-webxr on top of #23545 exposes an issue from #24757. The dedicated worker creation uses `parent_sender` as the target of the networking task source, but that causes any runnables to run on the event loop that created the worker.

### PR DESCRIPTION
**Pull request by jdm**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24812

### CODE REVIEW

**Comment by jdm** [comment]
That's a nice set of improved test results.

**Comment by jdm** [comment]
@nox Review ping.

**Comment by nox** [comment]
@bors-servo r+

Oops.

**Pull request merged**
