### PR TITLE
Use wptrunner for some old-style reftests.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8880)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/ref/basic.list, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8880#-K4yhyr7XH-Vfk_Hp0QP:-K4yhyr7XH-Vfk_Hp0QQ:-2136580971) ([raw file](https://github.com/servo/servo/blob/02f4be9c9f82a6e03942977eece39d98dcaff839/tests/ref/basic.list#L7)):*
Did this not make the cut?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8880)*

**Comment by Ms2ger** [comment]
@bors-servo r=frewsxcv

(On IRC)

**Comment by KiChjang** [comment]
```

Ran 3732 tests finished in 864.0 seconds.
  • 3731 ran as expected. 707 tests skipped.
  • 1 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/css/white_space_intrinsic_sizes_a.html
  └   → /_mozilla/css/white_space_intrinsic_sizes_a.html 2aac789a4ba9d3c3531f650eb61d3c0ed1d778c8
/_mozilla/css/white_space_intrinsic_sizes_ref.html 62a10a3c39c1958ffe988cc164fd57dfba255fdf
Testing 2aac789a4ba9d3c3531f650eb61d3c0ed1d778c8 == 62a10a3c39c1958ffe988cc164fd57dfba255fdf
```

**Comment by Ms2ger** [comment]
@bors-servo retry

Trying to see if it's intermittent or permanent

**Comment by KiChjang** [comment]
```

Ran 3732 tests finished in 862.0 seconds.
  • 3731 ran as expected. 707 tests skipped.
  • 1 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/css/white_space_intrinsic_sizes_a.html
  └   → /_mozilla/css/white_space_intrinsic_sizes_a.html 2aac789a4ba9d3c3531f650eb61d3c0ed1d778c8
/_mozilla/css/white_space_intrinsic_sizes_ref.html 62a10a3c39c1958ffe988cc164fd57dfba255fdf
Testing 2aac789a4ba9d3c3531f650eb61d3c0ed1d778c8 == 62a10a3c39c1958ffe988cc164fd57dfba255fdf
```

**Comment by KiChjang** [comment]
Looks like it's permanent damage.

**Comment by frewsxcv** [comment]
fwiw, it was marked as flaky before, so this could have always been the case prior to this

**Comment by frewsxcv** [comment]
Image diff on OSX btw:

meow

**Comment by frewsxcv** [comment]
Or a gif because I'm playing with imagemagick

flicker_cmp

**Pull request merged**
