### PR TITLE
The gstreamer plugin should resize when it's presented with frames to fill

### LINKED ISSUE #24835: GStreamer plugin resizing
For some reason when the gstreamer plugin gets resized, the page isn't reflowed so any GL content that dynamically sizes its canvas is still using the old size.

### PR DESCRIPTION
**Pull request by asajeffrey**
This is a workaround for race conditions in the embedder.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24835
- [x] These changes do not require tests because it's fixing a bug with an embedding

### CODE REVIEW

**Comment by asajeffrey** [comment]
OK, I think what's going on is this...

The embedder API uses push for some things (`WindowEvent`s being pushed from the embedder to servo) and pull for others (the `WindowMethods` trait implemented by the embedder), with the result that it's easy for things to get out of sync. In this case, it was the `get_coordinates` method, I think what was happening was:

- Embedder gets a `Start` message, and sends a `NewBrowser` event to Servo
- Embedder gets a `Resize` message, and resizes itself, then sends a `Resize` event to Servo
- Servo (still processing `NewBrowser`) calls `get_coordinates` and gets the new size
- When Servo processes `Resize`, there's nothing to do, since the size hasn't changed, and as a result script is never informed of the new size.

This PR is a workaround for that, by delaying sending the `Resize`.

A better fix is to revisit the embedding API to make it all push rather than mixed push/pull (or all async).

@paulrouget does my analysis sound right?

@ferjm r?

**Comment by paulrouget** [comment]
I know nothing about gstplugin. But

> When Servo processes Resize, there's nothing to do, since the size hasn't changed, and as a result script is never informed of the new size.

Right. But in the first place script should have had the new size.

> A better fix is to revisit the embedding API to make it all push rather than mixed push/pull (or all async).

One day :)

**Review by ferjm — APPROVED** [review]

**Comment by ferjm** [comment]
@bors-servo retry
- #22212

**Pull request merged**
