### PR TITLE
Add a `./mach grep` command.

### PR DESCRIPTION
**Pull request by JayNakrani**
Solves Issue #5838.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5842)

### CODE REVIEW

**Comment by Manishearth** [comment]
Reviewed files:
- python/servo/devenv_commands.py @ r1, r2

---

<sup>**[python/servo/devenv_commands.py, line 96 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5842#-JnldvsXv7zRgaiuCA7x)** ([raw file](https://github.com/servo/servo/blob/93ca4a37f7404c3fec5da3d337fc8a63715741c8/python/servo/devenv_commands.py#L96)):</sup>
Nit: Please use `path.join()` here

---

<sup>**[python/servo/devenv_commands.py, line 97 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5842#-Jnle3WH2BY3cvohQWWP)** ([raw file](https://github.com/servo/servo/blob/93ca4a37f7404c3fec5da3d337fc8a63715741c8/python/servo/devenv_commands.py#L97)):</sup>
Ditto

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5842)

**Comment by dhananjay92** [comment]
<sup>**[python/servo/devenv_commands.py, line 96 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5842#-JnldvsXv7zRgaiuCA7x)** ([raw file](https://github.com/servo/servo/blob/93ca4a37f7404c3fec5da3d337fc8a63715741c8/python/servo/devenv_commands.py#L96)):</sup>
Done. Amended.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5842)

**Comment by dhananjay92** [comment]
<sup>**[python/servo/devenv_commands.py, line 97 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5842#-Jnle3WH2BY3cvohQWWP)** ([raw file](https://github.com/servo/servo/blob/93ca4a37f7404c3fec5da3d337fc8a63715741c8/python/servo/devenv_commands.py#L97)):</sup>
Done. Amended.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5842)

**Comment by Manishearth** [comment]
Reviewed files:
- python/servo/devenv_commands.py @ r3

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5842)

**Comment by dhananjay92** [comment]
@Manishearth Log says two tests timed out! That shouldn't be because if changes in this PR. May be rerun the tests?!

**Pull request merged**
