### PR TITLE
Fix length value of interface methods

### PR DESCRIPTION
**Pull request by nox**
Blocked by https://github.com/w3c/testharness.js/pull/124.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5902)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review 

---

Reviewed files:
- components/script/dom/bindings/codegen/CodegenRust.py @ r1
- tests/wpt/metadata/dom/interfaces.html.ini @ r1
- tests/wpt/metadata/encoding/idlharness.html.ini @ r1
- tests/wpt/metadata/FileAPI/idlharness.html.ini @ r1
- tests/wpt/metadata/html/dom/interfaces.html.ini @ r1
- tests/wpt/metadata/workers/interfaces.worker.js.ini @ r1
- tests/wpt/metadata/XMLHttpRequest/interfaces.html.ini @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5902)

**Comment by jdm** [comment]
-S-awaiting-review 

---

Reviewed files:
- tests/wpt/metadata/html/dom/interfaces.html.ini @ r2
- tests/wpt/metadata/XMLHttpRequest/interfaces.html.ini @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5902)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 

---

Reviewed files:
- components/script/dom/bindings/codegen/CodegenRust.py @ r3

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5902)

**Comment by nox** [comment]
@jdm Squashed.

**Comment by jdm** [comment]
Sorry, forgot the WPT update hasn't happened yet.

**Comment by nox** [comment]
@jdm I think it just did.

**Comment by nox** [comment]
Oh wait, it's all grey.

**Pull request merged**
