### PR TITLE
Disable some intermittents

### PR DESCRIPTION
**Pull request by KiChjang**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9716)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo retry
* git being annoying

**Comment by frewsxcv** [comment]
@bors-servo retry

* #7791

**Comment by KiChjang** [comment]
Ok, I'm disabling #7791.

**Comment by KiChjang** [comment]
@bors-servo retry
* git being annoying

**Pull request merged**
