### PR TITLE
Move ConvertPipelineIdFromWebRender to compositing

### LINKED ISSUE #11082: Move ConvertPipelineIdFromWebRender to compositing
It's defined in `msg`, but only used in `compositing`.

Code: `components/msg/constellation_msg.rs`, `components/compositing/compositor.rs`

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
Fix #11082

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11090)

### CODE REVIEW

**Comment by Ms2ger** [comment]
This is going to conflict with #11084, so hold off for a moment.

**Comment by saneyuki** [comment]
> This is going to conflict with #11084, so hold off for a moment.

Okay, I'll wait it.

**Comment by saneyuki** [comment]
rbased

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by ConnorGBrewster** [comment]
@bors-servo 
 * Infra

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * Testing intermittent

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11100

**Pull request merged**
