### PR TITLE
Reuse Rect<T> some more

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17071)

### CODE REVIEW

**Comment by nox** [comment]
r? @emilio 
@bors-servo try
https://treeherder.mozilla.org/#/jobs?repo=try&revision=4538cf29cd803df5c49ec9abdde00b81ae09a8de

**Comment by emilio** [comment]
What's the rationale for converting `Rect` to a tuple? I find that somewhat confusing, over all because in layout we represent rects as `(Origin, Size)`, which makes the tuple indices very confusing.

**Comment by nox** [comment]
> What's the rationale for converting `Rect` to a tuple?

Not all values that behave that way correspond to the four sides of a rectangle. For example as part of `border-radius`, the values correspond to corners.

**Comment by emilio** [comment]
@bors-servo r+

Perhaps those should be newtypes... But not going to block on that. r=me

**Pull request merged**
