### PR TITLE
add unimplemented indexed access and length methods to select element

### LINKED ISSUE #11763: Implement indexed access on select elements
This also includes the `length` attribute.

It is probably simpler not to involve the `select.options` collection for now, and just implement the getter directly.

* Spec: <https://html.spec.whatwg.org/multipage/#dom-select-item>.
* Code: `components/script/dom/htmlselectelement.rs`, `components/script/dom/webidls/HTMLSelectElement.rs`.
* Test: `/html/semantics/forms/the-select-element/common-HTMLOptionsCollection.html`, `FileAPI/blob/Blob-constructor.html`.

### PR DESCRIPTION
**Pull request by kevgs**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #11763 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11805)

### CODE REVIEW

**Comment by kevgs** [comment]
PR for #11763

**Comment by metajack** [comment]
I thought our policy was not to implement stubs that did nothing, but to let the methods be undefined if we didn't support them?

**Comment by kevgs** [comment]
It looks like I didn't realize something. Could you give me some advice on how to implement those methods? Specifically, I do not understand where items are actually stored.

**Comment by jdm** [comment]
Ah, I understand the confusion. As Ms2ger mentioned in the issue, there's no need to store any new data in order to implement these methods. The need to traverse over the children of the HTMLSelectElement using `traverse_preorder`, and return the appropriate child based on the provided index. Does that make sense?

**Comment by kevgs** [comment]
This makes sense. Thank you!

**Comment by Ms2ger** [comment]
@kevgs I'm going to close this PR for now, but do feel free to create a new one when you've finished the implementation.

**Pull request closed without merging**
