### PR TITLE
Fully implement the "align descendants" rule for div.

### PR DESCRIPTION
**Pull request by eefriedman**
This adds -servo-left and -servo-right to complement -servo-center.

~~This intentionally doesn't try to address issue #7301.~~  Commit added to address #7301.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7825)

### CODE REVIEW

**Comment by Ms2ger** [comment]
This test should go somewhere under `tests/wpt/web-platform-tests/html/rendering/`.

**Comment by eefriedman** [comment]
`tests/wpt/web-platform-tests/html/rendering/` looks like it's part of an upstream repository; do you want me to upstream this test?

I'm guess the test should be named something like `web-platform-tests/html/rendering/non-replaced-elements/flow-content-0/div-align.html`?

Does it make sense to upstream the test as-is, without a test for #7301?

**Comment by jdm** [comment]
Upstreaming happens automatically, so it's fine to make changes there.

**Comment by eefriedman** [comment]
Moved tests.  Added fix for #7301, since it turned out to be easier than I thought it would be.

**Comment by mbrubeck** [comment]
Reviewed 8 of 8 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7825)

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Pull request merged**
