### PR TITLE
Replacing CSV profiling with TSV profiling

### PR DESCRIPTION
**Pull request by rzambre**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [X] These changes add to issue #10886 that has already been fixed.

Either:
- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11282)

### CODE REVIEW

**Comment by rzambre** [comment]
@larsbergstrom @aneeshusa Some urls (usually those of ads) contain commas in them.

**Comment by aneeshusa** [comment]
Thanks for this :)

Why are the fields separated by spaces as well as tabs? They should be separated by tabs only.

**Comment by aneeshusa** [comment]
We could also use the [csv](https://crates.io/crates/csv) crate, which can write out CSV and TSV records and handles proper quoting as well. License is MIT or Unlicense, which is Servo-compatible.

**Comment by rzambre** [comment]
Just removed the spaces :)

**Pull request merged**
