### PR TITLE
Update web-platform-tests

### PR DESCRIPTION
**Pull request by jdm**
This updates web-platform-tests to a46616a5b18e. It also removes our local copy of wptrunner in favour of the upstream one that we can modify and sync more easily.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17416)

### CODE REVIEW

**Comment by jdm** [comment]
r? @jgraham 

In particular, 61bd568 and d9fcd8c could use your eyes. c3a621b, b705807 and 4299c1c are direct imports from upstream that were landed since this update started.

**Comment by jdm** [comment]
@bors-servo: retry
#18748

**Comment by mbrubeck** [comment]
<details>

```
  ▶ OK [expected TIMEOUT] /html/semantics/tabular-data/processing-model-1/span-limits.html

  ▶ Unexpected subtest result in /html/semantics/tabular-data/processing-model-1/span-limits.html:
  │ FAIL [expected PASS] colspan of 1001 must be treated as 1000
  │   → assert_equals: expected 2009 but got 2022.1
  │ 
  │ @http://web-platform.test:8000/html/semantics/tabular-data/processing-model-1/span-limits.html:40:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1412:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  └ @http://web-platform.test:8000/html/semantics/tabular-data/processing-model-1/span-limits.html:39:1

  ▶ Unexpected subtest result in /html/semantics/tabular-data/processing-model-1/span-limits.html:
  │ FAIL [expected PASS] rowspan of 65534 must work
  │   → assert_equals: expected 393335 but got 137
  │ 
  │ @http://web-platform.test:8000/html/semantics/tabular-data/processing-model-1/span-limits.html:51:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1412:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  └ @http://web-platform.test:8000/html/semantics/tabular-data/processing-model-1/span-limits.html:44:1

  ▶ Unexpected subtest result in /html/semantics/tabular-data/processing-model-1/span-limits.html:
  │ FAIL [expected PASS] rowspan of 65535 must be treated as 65534
  │   → assert_equals: expected 393335 but got 137
  │ 
  │ @http://web-platform.test:8000/html/semantics/tabular-data/processing-model-1/span-limits.html:62:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1412:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  └ @http://web-platform.test:8000/html/semantics/tabular-data/processing-model-1/span-limits.html:55:1
```
</details>

**Comment by nox** [comment]
See #18756.

**Pull request closed without merging**
