### PR TITLE
Eliminate `AnimationFrame`

### PR DESCRIPTION
**Pull request by mrobinson**
This intermediate data structure doesn't really buy us anything and is a
bit confusing.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they do not change behavior.

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0596]: cannot borrow `style` as mutable, as it is not declared as mutable
   --> components/style/animation.rs:609:57
    |
594 |     style: &mut Arc<ComputedValues>,
    |     ----- help: consider changing this to be mutable: `mut style`
...
609 |                 property_animation.update(Arc::make_mut(&mut style), progress);
    |                                                         ^^^^^^^^^^ cannot borrow as mutable
```

**Review by emilio — APPROVED** [review]
Nice!

r=me with the build fixed

**Comment by CYBAI** [comment]
@bors-servo retry

- #25513, linux oom

**Pull request merged**
