### PR TITLE
Implement and test DOMTokenList.replace (fixes #8511)

### LINKED ISSUE #8511: Update our implementation of DOMTokenList and DOMSettableTokenList
The specification changed:

https://github.com/whatwg/dom/issues/28
https://github.com/whatwg/dom/issues/91
https://github.com/whatwg/dom/issues/105

### PR DESCRIPTION
**Pull request by nox**
Thanks to @sankha93 for the original work in #8525.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9353)

### CODE REVIEW

**Comment by nox** [comment]
This is a WIP: replace actually needs supports to be implemented.

**Comment by frewsxcv** [comment]
I know it's a WIP, but a couple suggestions if you weren't already going to do them:

1. explicitly add in the spec steps
2. create a separate internal function `run_update_steps` that performs the steps [outlined here](https://dom.spec.whatwg.org/#concept-dtl-update) and link to that

**Comment by nox** [comment]
There is no run_update_steps because the associated attribute's value is actually the only storage for their list of tokens. We already do this.

**Comment by jdm** [comment]
@nox What's the status here? Is this still classified a WIP and needs more work, or should @asajeffrey be reviewing it?

**Comment by nox** [comment]
I'll look at it tonight or tomorrow while rebasing it.

**Comment by asajeffrey** [comment]
I've been holding off while it has conflicts, let me know when you're ready.

**Comment by nox** [comment]
@asajeffrey This is ok to go.

**Comment by asajeffrey** [comment]
Mostly this looks fine, there's a spec issue plus a couple of extra tests I think we should add, but otherwise cool

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/domtokenlist.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9353#-KBNr5bzkQsmWdGDOY_H:-KBNr5c-ByNbg7y2rG6f:-1244138289) ([raw file](https://github.com/servo/servo/blob/636c0fc1cf61479a549956203e2de20432bba99d/components/script/dom/domtokenlist.rs#L135)):*
It looks like this is slightly different from the spec in the case `list.replace("a b", "")`. The spec says it should throw a `SyntaxError`, it will actually throw an `InvalidCharacterError`.

---

*[tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html, line 84 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9353#-KBNsTUjjQrBrqOYTSBD:-KBNsTUjjQrBrqOYTSBE:1264290645) ([raw file](https://github.com/servo/servo/blob/636c0fc1cf61479a549956203e2de20432bba99d/tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html#L84)):*
Can we add tests:
```
assert_throws( 'SYNTAX_ERR', function () { elem.classList.replace('', 'a b'); }
assert_throws( 'SYNTAX_ERR', function () { elem.classList.replace('a b', ''); }
```

---

*[tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html, line 263 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9353#-KBNt2m2_oFg2vYjNKCX:-KBNt2m3Vz1o2lbzQPHq:152299478) ([raw file](https://github.com/servo/servo/blob/636c0fc1cf61479a549956203e2de20432bba99d/tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html#L263)):*
Can we add a test for the case where we're replacing a token with one that's already in the list:
```
  secondelem.className = 'token1 token2 token3'
  secondelem.classList.replace('token1', 'token3');
  assert_equals( secondelem.classList.length, 2 );
  assert_false( secondelem.classList.contains('token1') );
  assert_true( secondelem.classList.contains('token2') );
  assert_true( secondelem.classList.contains('token23') );
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9353#-:-KBNtaGxzxt-HaLT-ROk:-1937340744)*

**Comment by jdm** [comment]
I think `assert_throws(new SyntaxError(), function () { elem.classList.replace('', 'a b'); }` is more idiomatic.

**Comment by Ms2ger** [comment]
That's an other kind of SyntaxError

**Comment by asajeffrey** [comment]
@nox: is this PR still open?

**Comment by nox** [comment]
It is still open, still blocked, still didn't address it, I'll try to do it soon.

**Comment by nox** [comment]
@asajeffrey Ready to go.

**Comment by asajeffrey** [comment]
Okay, I'll take a look later today.

**Comment by asajeffrey** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/domtokenlist.rs, line 142 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9353#-KDZPdB17Ww7gBNVZHhu:-KDZPdB2aOuccRiVdQrW:-841311312) ([raw file](https://github.com/servo/servo/blob/d8486458eb343f60b89c56839cbd3fb5156280bf/components/script/dom/domtokenlist.rs#L142)):*
Can you add comments for how the code lines up with the steps of the spec?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9353)*

**Comment by nox** [comment]
Done. r?

---

Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/domtokenlist.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9353#-KBNr5bzkQsmWdGDOY_H:-KDbymfdRM3wFQ6cZZRW:-499146009) ([raw file](https://github.com/servo/servo/blob/636c0fc1cf61479a549956203e2de20432bba99d/components/script/dom/domtokenlist.rs#L135)):*
Done.

---

*[components/script/dom/domtokenlist.rs, line 142 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9353#-KDZPdB17Ww7gBNVZHhu:-KDbzBDKbKW4gnTEaVDS:-499146009) ([raw file](https://github.com/servo/servo/blob/d8486458eb343f60b89c56839cbd3fb5156280bf/components/script/dom/domtokenlist.rs#L142)):*
Done.

---

*[tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html, line 84 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9353#-KBNsTUjjQrBrqOYTSBD:-KDbzCJSqriypnVuMXiS:-499146009) ([raw file](https://github.com/servo/servo/blob/636c0fc1cf61479a549956203e2de20432bba99d/tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html#L84)):*
Done.

---

*[tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html, line 263 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9353#-KBNt2m2_oFg2vYjNKCX:-KDbzCs5AcxKNE6FabIQ:-499146009) ([raw file](https://github.com/servo/servo/blob/636c0fc1cf61479a549956203e2de20432bba99d/tests/wpt/web-platform-tests/dom/nodes/Element-classlist.html#L263)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9353#-:-KDbzFgaYXy87cpJfgwe:-881941018)*

**Comment by asajeffrey** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9353)*

**Comment by asajeffrey** [comment]
@bors-servo retry
* #9724

**Pull request merged**
