### PR TITLE
Cleanup constellation debug messages

### PR DESCRIPTION
**Pull request by cbrewster**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because _cleanup_.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20777)

### CODE REVIEW

**Comment by cbrewster** [comment]
r? @asajeffrey 
Will probably need to wait until infra isn't on fire

**Comment by jdm** [comment]
```
error[E0004]: non-exhaustive patterns: `GetChildBrowsingContextId(_, _, _)` not covered
   --> components/script_traits/script_msg.rs:193:29
    |
193 |         let variant = match *self {
    |                             ^^^^^ pattern `GetChildBrowsingContextId(_, _, _)` not covered

error: aborting due to previous error
```

**Pull request merged**
