### PR TITLE
WebAudio MediaElementAudioSourceNode implementation

### LINKED ISSUE #22370: Implement MediaElementAudioSourceNode
Spec: https://webaudio.github.io/web-audio-api/#mediaelementaudiosourcenode

There is a brief mention of a potential approach to implement the backend part of this type of AudioNode at https://github.com/servo/media/issues/43

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22370
- [X] There are tests for these changes

Depends on https://github.com/servo/media/pull/321

Tested with https://ferjm.github.io/webaudio-examples/media-source-buffer/

I am still investigating why it is playing back with a low rate.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* #21696

**Pull request merged**
