### PR TITLE
Fix issues found by rust-clippy

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7987)

### CODE REVIEW

**Comment by Manishearth** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[components/canvas/canvas_paint_task.rs, line 604 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7987#-K0TRYGfGOF4SZS79IXY)** ([raw file](https://github.com/servo/servo/blob/4ac887c776cfe23d6be59797e2d3efac620b7dc5/components/canvas/canvas_paint_task.rs#L604)):</sup>
Mostly okay with nops being used to make code look neater. No strong opinion either way


---

<sup>**[components/net_traits/image/base.rs, line 40 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7987#-K0TSV984B25tYZevNhC)** ([raw file](https://github.com/servo/servo/blob/6303126e0c48e9c83aa7edd813079a6a360837b2/components/net_traits/image/base.rs#L40)):</sup>
same comment as above


---

<sup>**[components/util/vec.rs, line 74 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7987#-K0TTTmdA_oV-QAkwGjX)** ([raw file](https://github.com/servo/servo/blob/6303126e0c48e9c83aa7edd813079a6a360837b2/components/util/vec.rs#L74)):</sup>
ditto


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7987)

**Comment by frewsxcv** [comment]
The `+ 0`s have returned

**Comment by frewsxcv** [comment]
Nevermind, I didn't return all of them, one sec

**Comment by frewsxcv** [comment]
Okay, should be good now

**Comment by Manishearth** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7987)

**Pull request merged**
