### PR TITLE
Bindgenup 

### PR DESCRIPTION
**Pull request by emilio**
r? @heycam

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15216)

### CODE REVIEW

**Comment by SimonSapin** [comment]
`./mach test-tidy` fails:

I think updating bindgen to `quasi_codegen = "0.29"` would fix it, but it’s tricky to test without publishing to crates.io.

```
./Cargo.lock:1: duplicate versions for package `unicode-xid`
	The following packages depend on version 0.0.3 from 'crates.io':
		syn
		syntex_errors
		syntex_syntax
	The following packages depend on version 0.0.4 from 'crates.io':
		syntex_errors
		syntex_syntax
./Cargo.lock:1: duplicate versions for package `syntex_errors`
	The following packages depend on version 0.50.0 from 'crates.io':
		quasi_codegen
		syntex
		syntex_syntax
	The following packages depend on version 0.54.0 from 'crates.io':
		quasi
		syntex_syntax
./Cargo.lock:1: duplicate versions for package `syntex_syntax`
	The following packages depend on version 0.50.0 from 'crates.io':
		aster
		quasi_codegen
		serde_codegen
		syntex
	The following packages depend on version 0.54.0 from 'crates.io':
		aster
		bindgen
		quasi
./Cargo.lock:1: duplicate versions for package `syntex_pos`
	The following packages depend on version 0.50.0 from 'crates.io':
		syntex_errors
		syntex_syntax
	The following packages depend on version 0.54.0 from 'crates.io':
		syntex_errors
		syntex_syntax
./Cargo.lock:1: duplicate versions for package `aster`
	The following packages depend on version 0.34.0 from 'crates.io':
		quasi_codegen
	The following packages depend on version 0.38.0 from 'crates.io':
		bindgen

**Comment by SimonSapin** [comment]
https://github.com/servo/rust-bindgen/pull/441 hopefully fixes this.

**Comment by emilio** [comment]
It doesn't (still conflicting with html5ever build dependencies if I'm not wrong). I just pushed and update and whitelisted those, r? @SimonSapin for the whitelist stuff?

**Comment by heycam** [comment]
@bors-servo p=1

(I'm waiting on this for a mozilla-central -> stylo merge.)

**Pull request merged**
