### PR TITLE
use return value of invoking event handlers to cancel the event

### LINKED ISSUE #8490: Use the return value of invoking event handlers to cancel the value
Specifically, we are missing step 4 in the [event handler processing algorithm](https://html.spec.whatwg.org/multipage/webappapis.html#the-event-handler-processing-algorithm) in `EventListenerType::call_or_handle_event`.

Code: components/script/dom/eventtarget.rs

### PR DESCRIPTION
**Pull request by jxs**
Fixes #8490.

@jdm having some questions on the beforeunload event: how can i check if return_value is null?
shoud i also check if "If the Event object E is a BeforeUnloadEvent object, and the Event object E's returnValue attribute's value is the empty string, then set the returnValue attribute's value to return value." ?

thanks!

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8707)

### CODE REVIEW

**Comment by jdm** [comment]
We don't implement OnBeforeUnloadEventHandler or BeforeUnloadEvent yet; adding the new event interface is straightforward, but adding support for the special event handler will require work similar to #8430. I think doing that in a separate PR would make sense (or a separate commit in this one, if you'd like!), so it could just be a TODO in this one. As for checking whether it's null, there's an `is_null_or_undefined` method on `JSVal`: https://github.com/servo/rust-mozjs/blob/master/src/jsval.rs#L219

**Comment by jxs** [comment]
ok thanks, updated! Yeah i agree on a new PR so that this one can be closed first, what do you think?

**Comment by jdm** [comment]
That works for me!

**Comment by Ms2ger** [comment]
`is_null_or_undefined` does not sound correct; checking for `null` can be done with the aptly named `is_null` method.

It may be the case that the return value is never `undefined` here, but I don't think so. There's a similar issue that the return value is not necessarily a `boolean` in the other match arms. I would like to see tests for that; if you don't feel up for it, please let me know so I can write them.

Also, there's the problem of
```
/home/travis/build/servo/servo/components/script/dom/eventtarget.rs:150:35: 150:46 error: no rules expected the token `"mouseover"`
/home/travis/build/servo/servo/components/script/dom/eventtarget.rs:150                             atom!("mouseover") => {
```
which I assume means we need to add it to the list in the string-cache repo.

**Comment by eefriedman** [comment]
> which I assume means we need to add it to the list in the string-cache repo.

Already done, and landed in Servo; this PR just needs to be rebased.

**Comment by jxs** [comment]
ok, updated to ``ìs_null``` and rebased

**Comment by jdm** [comment]
Whoops, we need to update the code to account for #8710 now.

**Comment by jxs** [comment]
ok, updated!

**Comment by jdm** [comment]
Sorry for the delay!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[components/script/dom/eventtarget.rs, line 130 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZSfuX_ygWUUvr9pDr:-K4ZSfuX_ygWUUvr9pDs:734136793) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L130)):*
We should use `let return_value = RootedValue::new(cx, handler.Call_(object,` or it's a GC hazard.

---

*[components/script/dom/eventtarget.rs, line 131 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4Oi0C8vmAcXIQJBiUE:-K4Oi0C8vmAcXIQJBiUF:931768981) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L131)):*
nit: these lines should be indented to match `object` on the previous line.

---

*[components/script/dom/eventtarget.rs, line 137 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4Oi4E5RpNj_Qkl3aGH:-K4Oi4E5RpNj_Qkl3aGI:-174335451) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L137)):*
It's cleaner to use `if let Ok(value) = return_value` here, and we'll need the check to be `value.is_boolean() && value.to_boolean() == true` or we'll panic if an event handler returns a non-boolean value.

---

*[components/script/dom/eventtarget.rs, line 148 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZTRGwDtKZBC8HB3Bb:-K4ZTRGwDtKZBC8HB3Bc:944088229) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L148)):*
Same comment about `RootedValue` here.

---

*[components/script/dom/eventtarget.rs, line 149 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZTI-rqKkrftbFThFl:-K4ZTI-rqKkrftbFThFm:-736721919) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L149)):*
Let's add a `// Step 4` comment here.

---

*[components/script/dom/eventtarget.rs, line 151 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZSyct_yDvjwKmBkj-:-K4ZSYtn5qfzEEyURFF4:368422843) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L151)):*
Same as previous (`if let` and `is_boolean`).

---

*[components/script/dom/eventtarget.rs, line 152 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZSXHgYccWAehZBY_S:-K4ZSXHh1zs6nuEYTdD3:513813304) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L152)):*
nit: indent by four spaces

---

*[components/script/dom/eventtarget.rs, line 156 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZT2IUGEzGMBmloGGZ:-K4ZT2IUGEzGMBmloGG_:-648789395) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L156)):*
`if let`

---

*[components/script/dom/eventtarget.rs, line 161 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZT4sw1_ySuas57r8h:-K4ZT4sw1_ySuas57r8i:762734597) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L161)):*
`if let` and `is_boolean`.

---

*[components/script/dom/eventtarget.rs, line 171 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4OiZhOh6VfqCKHor5b:-K4OiZhOh6VfqCKHor5c:565862747) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L171)):*
We can remove this now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8707#-:-K4ZTLTB3f3frr9tGqZl:-1407477416)*

**Comment by jdm** [comment]
Don't forget to run `./mach test-tidy` after addressing these review comments!
-S-awaiting-review +S-fails-tidy +S-needs-code-changes 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[components/script/dom/eventtarget.rs, line 130 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZSfuX_ygWUUvr9pDr:-K4ZndH6fAEg8c09KWOU:-871667849) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L130)):*
Ah, sorry, I forgot about the `Result<>` that `Call_` returns. We'll need
```rust
let return_value = handler.Call_(object, ...);
if let Some(return_value) = return_value {
    let return_value = RootedValue::new(cx, return_value);
    ...
}
```

---

*[components/script/dom/eventtarget.rs, line 156 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZT2IUGEzGMBmloGGZ:-K4ZnPUlOX1depgtS-4t:-96383242) ([raw file](https://github.com/servo/servo/blob/0dfd544f8397c04176e2e2ab03aa2dd65da1b62d/components/script/dom/eventtarget.rs#L156)):*
This doesn't compile.

---

*[components/script/dom/eventtarget.rs, line 139 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4Zn7rSy5YOVixLsroH:-K4Zn7rSy5YOVixLsroI:2057177820) ([raw file](https://github.com/servo/servo/blob/2b041e206fbfe0f52cfe27226f9b7f3227f3b2a6/components/script/dom/eventtarget.rs#L139)):*
This doesn't compile, and doesn't use `is_boolean`. We'll need
```rust
if let Ok(return_value) = return_value {
    ...
    if return_value.is_boolean() && return_value.to_boolean() == true {
        ...
    }
}
```

---

*[components/script/dom/eventtarget.rs, line 149 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZnHQ8bP4W6C3DW2bg:-K4ZnHQ8bP4W6C3DW2bh:-236506648) ([raw file](https://github.com/servo/servo/blob/2b041e206fbfe0f52cfe27226f9b7f3227f3b2a6/components/script/dom/eventtarget.rs#L149)):*
This belongs above the `match event.type_()` line.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8707#-:-K4ZkI3eM6yv-HvDXtQB:1036517522)*

**Comment by jdm** [comment]
Let's add a test for this behaviour as well. `./mach create-wpt tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html` will create a new test file, and then we can base it off of the test I wrote at http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=3779 . We want to verify that for each of handlers listed in the spec, the event is marked as cancelled when the handler returns the appropriate value, and the event is not marked as cancelled when the handler does not. Does that make sense?

-S-awaiting-review -S-awaiting-review +S-needs-tests +S-needs-code-changes 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/eventtarget.rs, line 142 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4iLuEq6cKxynrSo02T:-K4iLuEq6cKxynrSo02U:-1882507251) ([raw file](https://github.com/servo/servo/blob/037b6f01547996ea8d78f8af2683160bb6f0feed/components/script/dom/eventtarget.rs#L142)):*
This will panic if the JS event handler returns a non-boolean, which is totally allowed by the spec :) We should just ignore it if this happens.

---

*[components/script/dom/eventtarget.rs, line 149 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4icw_8JLpz-kIS11Re:-K4icw_8JLpz-kIS11Rf:209717720) ([raw file](https://github.com/servo/servo/blob/037b6f01547996ea8d78f8af2683160bb6f0feed/components/script/dom/eventtarget.rs#L149)):*
This change can be reverted; if we ignore the return value, we don't need to perform any special rooting on it.

---

*[components/script/dom/eventtarget.rs, line 158 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ie2YyHRmBOufhyeqf:-K4ie2YyHRmBOufhyeqg:-1236761498) ([raw file](https://github.com/servo/servo/blob/037b6f01547996ea8d78f8af2683160bb6f0feed/components/script/dom/eventtarget.rs#L158)):*
We should have a RootedValue here as well. Let's rearrange this code like this for clarity:
```rust
if let Ok(value) = handler.Call_(...) {
    let value = RootedValue::new(..);
    let value = value.handle();
    let should_cancel = match event.type_() {
        atom!("mouseover") => value.is_boolean() && value.to_boolean() == true,
        ...
    };
    if should_cancel {
        event.PreventDefault();
    }
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8707#-:-K4ic7GUY9yXCVDp4_sg:-1896721884)*

**Comment by jdm** [comment]
A couple last changes and this will be ready to merge :)
-S-needs-tests -S-fails-tidy -S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[components/script/dom/eventtarget.rs, line 149 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8707#-K4ZnHQ8bP4W6C3DW2bg:-K5VpaYnUjiHN4KG-rfb:1507036209) ([raw file](https://github.com/servo/servo/blob/2b041e206fbfe0f52cfe27226f9b7f3227f3b2a6/components/script/dom/eventtarget.rs#L149)):*
This is still a change I'd like to see.

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 10 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5VqFxyjCluytYes-Ud:-K5VqFxyjCluytYes-Ue:-43709087) ([raw file](https://github.com/servo/servo/blob/00d555ff980cb2b923ec2032f78fad10dbb2b425/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L10)):*
This should use `step_func(function(ev) { ... })`.

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 12 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5VsNb_G9yY1OYP0Qj5:-K5VsNb_G9yY1OYP0Qj6:1952329835) ([raw file](https://github.com/servo/servo/blob/00d555ff980cb2b923ec2032f78fad10dbb2b425/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L12)):*
"Mouseover listener returning true cancels event"

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 14 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5VqYE2hanMh4GR8HGe:-K5VqYE2hanMh4GR8HGf:1789256418) ([raw file](https://github.com/servo/servo/blob/00d555ff980cb2b923ec2032f78fad10dbb2b425/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L14)):*
onbeforeunload

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 15 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5Vsfsff8asUqkUyFwk:-K5Vsfsff8asUqkUyFwl:467399922) ([raw file](https://github.com/servo/servo/blob/00d555ff980cb2b923ec2032f78fad10dbb2b425/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L15)):*
step_func

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 17 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5VsXLwOen393ulolyA:-K5VsXLwOen393ulolyB:186852019) ([raw file](https://github.com/servo/servo/blob/00d555ff980cb2b923ec2032f78fad10dbb2b425/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L17)):*
"beforeunload listener returning null cancels event"

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 19 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5Vq_NI3PYUXOnsYrPO:-K5Vq_NI3PYUXOnsYrPP:826455652) ([raw file](https://github.com/servo/servo/blob/00d555ff980cb2b923ec2032f78fad10dbb2b425/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L19)):*
onclick

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 20 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5VseQq7ReEyyUAX_QB:-K5VseQq7ReEyyUAX_QC:467399922) ([raw file](https://github.com/servo/servo/blob/00d555ff980cb2b923ec2032f78fad10dbb2b425/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L20)):*
step_func

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 22 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5VsaEU8W5vcmIZto5u:-K5VsaEU8W5vcmIZto5v:446503569) ([raw file](https://github.com/servo/servo/blob/00d555ff980cb2b923ec2032f78fad10dbb2b425/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L22)):*
"click listener returning false cancels event"

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 23 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5VssJHWXb62Zy3-ZHY:-K5VssJHWXb62Zy3-ZHZ:-399762392) ([raw file](https://github.com/servo/servo/blob/00d555ff980cb2b923ec2032f78fad10dbb2b425/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L23)):*
Could we also add more tests for handlers that don't return values that should cancel the event? Eg. a beforeunload listener that returns true, a mouseover listener that returns false, etc.?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8707#-:-K5Vsll1J2vuAiCfk0s9:1859936785)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 16 of 16 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 15 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5XxSnT98i5cvBJ-KJg:-K5XxSnT98i5cvBJ-KJh:-2142040487) ([raw file](https://github.com/servo/servo/blob/b89b44999dbb4ca7edcc4a95ff93a0c5ede65458/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L15)):*
We should be checking that this is false now.

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 25 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5XxY9J0pxE_Mz1Tudq:-K5XxY9J0pxE_Mz1Tudr:1330772931) ([raw file](https://github.com/servo/servo/blob/b89b44999dbb4ca7edcc4a95ff93a0c5ede65458/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L25)):*
This should be checking against false.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8707#-:-K5XxpXMenbQx7kCAhaz:1458266033)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 15 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5XxSnT98i5cvBJ-KJg:-K5fk66CRmbi3xEYqvOk:389565262) ([raw file](https://github.com/servo/servo/blob/b89b44999dbb4ca7edcc4a95ff93a0c5ede65458/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L15)):*
I'm pretty sure if we run this test it won't pass now - the actual listener is still returning true.

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html, line 25 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8707#-K5XxY9J0pxE_Mz1Tudq:-K5fkB1IJMiFqDr1eIsZ:-1045866338) ([raw file](https://github.com/servo/servo/blob/b89b44999dbb4ca7edcc4a95ff93a0c5ede65458/tests/wpt/web-platform-tests/html/webappapis/scripting/events/event-handler-processing-algorithm.html#L25)):*
Same as previous.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8707#-:-K5fkF43TKgvDlFfiYcy:1458266033)*

**Comment by jdm** [comment]
The changes here appear to have reverted to an earlier revision that didn't build.
-S-awaiting-review +S-needs-code-changes -S-needs-rebase 

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8707#-:-K5kwcaNm9io5T36ITYv:-947311275)*

**Comment by KiChjang** [comment]
@jxs Are you still working on this?

**Comment by jdm** [comment]
This is totally waiting on me. The spec issue I filed doesn't really have resolution yet.

**Comment by jdm** [comment]
Rebased in #9755.

**Pull request closed without merging**
