### PR TITLE
Update bincode.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8893)

### CODE REVIEW

**Comment by frewsxcv** [comment]
https://github.com/TyOverby/bincode/compare/c1d94fe8...590a862b

**Comment by KiChjang** [comment]
```

Ran 3729 tests finished in 865.0 seconds.
  • 3728 ran as expected. 707 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /_mozilla/css/iframe/hide_layers2.html
  │ 
  │ thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
  │ stack backtrace:
  │    1:        0x10b23f1c8 - sys::backtrace::tracing::imp::write::h7d2881098672eadd7It
  │    2:        0x10b24130f - panicking::log_panic::_<closure>::closure.40649
  │    3:        0x10b240db2 - panicking::log_panic::h8037c21ca8707493MAx
  │    4:        0x10b22c2a6 - sys_common::unwind::begin_unwind_inner::h87d033c2dbe04bc77Ls
  │    5:        0x10b22c68e - sys_common::unwind::begin_unwind_fmt::h086b7999edf0c62fdLs
  │    6:        0x10b23e7e7 - rust_begin_unwind
  │    7:        0x10b2638f0 - panicking::panic_fmt::h761c3d51c4df5175ZFK
  │    8:        0x109c5198d - constellation::_<impl>::handle_request::handle_request::h14315049613349382085
  │    9:        0x109c36a87 - sys_common::unwind::try::try_fn::try_fn::h1738942279423713703
  │   10:        0x10b23e608 - __rust_try
  │   11:        0x10b23b70e - sys_common::unwind::try::inner_try::hdd63401dff52b04dFIs
  │   12:        0x109c38b4a - boxed::_<impl>::call_box::call_box::h555662053166198483
  │   13:        0x10b24059d - sys::thread::_<impl>::new::thread_start::h146dc2a2095e243ajVw
  │   14:     0x7fff91449059 - _pthread_body
  └   15:     0x7fff91448fd6 - _pthread_start
```

**Comment by KiChjang** [comment]
@bors-servo retry
* #8769

**Pull request merged**
