### PR TITLE
layout: Add support for vertical alignment within table cells.

### LINKED ISSUE #10621: Table cells not vertically aligned
# HTML

```html
<style>
td {
  height: 5em;
  width: 5em;
  border: 1px solid black;
}
</style>
<table>
  <tr>
    <td>Foo</td>
  </tr>
</table>
```

# Chrome

screen shot 2016-04-14 at 7 12 06 pm

# Servo

screen shot 2016-04-14 at 7 11 51 pm

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #10621

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10722)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Thanks!

@bors-servo r+

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css21_dev/html4/floats-wrap-bfc-001-left-overflow.htm
  └   → /css21_dev/html4/floats-wrap-bfc-001-left-overflow.htm 252edff283e8f3395a2b9bff9e1f4bb79bf9520e
/css21_dev/html4/reference/floats-wrap-bfc-001-left-overflow-ref.htm c3a278115ff68702eec6eef472830b73b56c5ca4
Testing 252edff283e8f3395a2b9bff9e1f4bb79bf9520e == c3a278115ff68702eec6eef472830b73b56c5ca4

  ▶ FAIL [expected PASS] /css21_dev/html4/floats-wrap-bfc-001-left-table.htm
  └   → /css21_dev/html4/floats-wrap-bfc-001-left-table.htm 51a04b5663a0742ae83e073b4d19493f3c99927c
/css21_dev/html4/reference/floats-wrap-bfc-001-left-table-ref.htm 65b9b28a992188577f0143f69f7174b310641097
Testing 51a04b5663a0742ae83e073b4d19493f3c99927c == 65b9b28a992188577f0143f69f7174b310641097

  ▶ FAIL [expected PASS] /css21_dev/html4/floats-wrap-bfc-001-right-overflow.htm
  └   → /css21_dev/html4/floats-wrap-bfc-001-right-overflow.htm 35281888b2103f38b8d20505fdff67a714ca88a7
/css21_dev/html4/reference/floats-wrap-bfc-001-right-overflow-ref.htm 5b2654c00c64deeb9d4f6b2deb586adbcad4dcea
Testing 35281888b2103f38b8d20505fdff67a714ca88a7 == 5b2654c00c64deeb9d4f6b2deb586adbcad4dcea

  ▶ FAIL [expected PASS] /css21_dev/html4/floats-wrap-bfc-001-right-table.htm
  └   → /css21_dev/html4/floats-wrap-bfc-001-right-table.htm 9228915f27c6f357cc01ec5b692350572be57c29
/css21_dev/html4/reference/floats-wrap-bfc-001-right-table-ref.htm cf0a391cb213d457bab21dd4f3ee81a0d7c7fb9b
Testing 9228915f27c6f357cc01ec5b692350572be57c29 == cf0a391cb213d457bab21dd4f3ee81a0d7c7fb9b

  ▶ FAIL [expected PASS] /css21_dev/html4/floats-wrap-bfc-003-left-overflow.htm
  └   → /css21_dev/html4/floats-wrap-bfc-003-left-overflow.htm e0813a345422e055b3bcdc40b76dd0a0f69a6d6a
/css21_dev/html4/reference/floats-wrap-bfc-003-left-overflow-ref.htm 43f657c70beb6673a6f90ff025c7f06c55e5e20a
Testing e0813a345422e055b3bcdc40b76dd0a0f69a6d6a == 43f657c70beb6673a6f90ff025c7f06c55e5e20a

  ▶ FAIL [expected PASS] /css21_dev/html4/floats-wrap-bfc-003-right-overflow.htm
  └   → /css21_dev/html4/floats-wrap-bfc-003-right-overflow.htm d79fd7822e2d250e729cf0d71938b150338eaa08
/css21_dev/html4/reference/floats-wrap-bfc-003-right-overflow-ref.htm bcbd5aa6f218c40b4ca5d75a1c2d57e9134b3a48
Testing d79fd7822e2d250e729cf0d71938b150338eaa08 == bcbd5aa6f218c40b4ca5d75a1c2d57e9134b3a48

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-106.htm
  └   → /css21_dev/html4/margin-collapse-106.htm 95da76c6a92213707f31b4449a6efabcbbd97956
/css21_dev/html4/reference/margin-collapse-106-ref.htm 0573ebbb908815f7f8e760f58a56c4b9c6ad34d5
Testing 95da76c6a92213707f31b4449a6efabcbbd97956 == 0573ebbb908815f7f8e760f58a56c4b9c6ad34d5

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-110.htm
  └   → /css21_dev/html4/margin-collapse-110.htm a7b51eeb4566bf73589e763da4e494742912413c
/css21_dev/html4/reference/margin-collapse-110-ref.htm 2d82835c2ca6ad59272581ccd188e65f04495fb2
Testing a7b51eeb4566bf73589e763da4e494742912413c == 2d82835c2ca6ad59272581ccd188e65f04495fb2

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-112.htm
  └   → /css21_dev/html4/margin-collapse-112.htm 95da76c6a92213707f31b4449a6efabcbbd97956
/css21_dev/html4/reference/margin-collapse-106-ref.htm 0573ebbb908815f7f8e760f58a56c4b9c6ad34d5
Testing 95da76c6a92213707f31b4449a6efabcbbd97956 == 0573ebbb908815f7f8e760f58a56c4b9c6ad34d5

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-111.htm
  └   → /css21_dev/html4/margin-collapse-111.htm a7b51eeb4566bf73589e763da4e494742912413c
/css21_dev/html4/reference/margin-collapse-110-ref.htm 2d82835c2ca6ad59272581ccd188e65f04495fb2
Testing a7b51eeb4566bf73589e763da4e494742912413c == 2d82835c2ca6ad59272581ccd188e65f04495fb2

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-156.htm
  └   → /css21_dev/html4/margin-collapse-156.htm 2df71df2a230d95798c93ad1fff2d605cfe8e79f
/css21_dev/html4/reference/margin-collapse-156-ref.htm e86f3b4e92e45da8f7152256f4bf4b62bb8e2fbb
Testing 2df71df2a230d95798c93ad1fff2d605cfe8e79f == e86f3b4e92e45da8f7152256f4bf4b62bb8e2fbb

  ▶ PASS [expected FAIL] /css21_dev/html4/vertical-align-applies-to-007.htm
```
Well, there's a PASS with `vertical-align` in the name, so that's nice :)

**Comment by notriddle** [comment]
@bors-servo try

The test failures were me assuming that the first child would define the upper bound (and the last child the lower bound). Silly me.

**Comment by notriddle** [comment]
I got it down to five, now.
```
  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-111.htm
  └   → /css21_dev/html4/margin-collapse-111.htm a7b51eeb4566bf73589e763da4e494742912413c
/css21_dev/html4/reference/margin-collapse-110-ref.htm 2d82835c2ca6ad59272581ccd188e65f04495fb2
Testing a7b51eeb4566bf73589e763da4e494742912413c == 2d82835c2ca6ad59272581ccd188e65f04495fb2

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-112.htm
  └   → /css21_dev/html4/margin-collapse-112.htm 95da76c6a92213707f31b4449a6efabcbbd97956
/css21_dev/html4/reference/margin-collapse-106-ref.htm 0573ebbb908815f7f8e760f58a56c4b9c6ad34d5
Testing 95da76c6a92213707f31b4449a6efabcbbd97956 == 0573ebbb908815f7f8e760f58a56c4b9c6ad34d5

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-110.htm
  └   → /css21_dev/html4/margin-collapse-110.htm a7b51eeb4566bf73589e763da4e494742912413c
/css21_dev/html4/reference/margin-collapse-110-ref.htm 2d82835c2ca6ad59272581ccd188e65f04495fb2
Testing a7b51eeb4566bf73589e763da4e494742912413c == 2d82835c2ca6ad59272581ccd188e65f04495fb2

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-106.htm
  └   → /css21_dev/html4/margin-collapse-106.htm 95da76c6a92213707f31b4449a6efabcbbd97956
/css21_dev/html4/reference/margin-collapse-106-ref.htm 0573ebbb908815f7f8e760f58a56c4b9c6ad34d5
Testing 95da76c6a92213707f31b4449a6efabcbbd97956 == 0573ebbb908815f7f8e760f58a56c4b9c6ad34d5

  ▶ FAIL [expected PASS] /css21_dev/html4/margin-collapse-156.htm
  └   → /css21_dev/html4/margin-collapse-156.htm 2df71df2a230d95798c93ad1fff2d605cfe8e79f
/css21_dev/html4/reference/margin-collapse-156-ref.htm e86f3b4e92e45da8f7152256f4bf4b62bb8e2fbb
Testing 2df71df2a230d95798c93ad1fff2d605cfe8e79f == e86f3b4e92e45da8f7152256f4bf4b62bb8e2fbb

  ▶ PASS [expected FAIL] /css21_dev/html4/vertical-align-applies-to-007.htm
```

**Comment by notriddle** [comment]
There is now exactly one failure:

```
  ▶ Unexpected subtest result in /html/browsers/browsing-the-web/scroll-to-fragid/scroll-to-id-top.html:
  └ PASS [expected FAIL] Fragment Navigation: TOP is a valid element id, which overrides navigating to top of the document
```

Not sure if intermittent, or if I somehow fixed it.

**Comment by jdm** [comment]
That's #10753.

**Comment by notriddle** [comment]
Cool, then I've fixed the bugs and it's ready for you to re-review.

**Comment by notriddle** [comment]
Pinging @SimonSapin

**Comment by notriddle** [comment]
@bors-servo retry

Check for intermittent, because this test contains no tables.

**Comment by SimonSapin** [comment]
* #10859

**Pull request merged**
