### PR TITLE
Dolt

### LINKED ISSUE #11416: Support responsive images
This is a large piece of work that probably depends on making our image loading code better reflect the actual specification model. For more context on what responsive images are, see [the specification introduction](https://html.spec.whatwg.org/multipage/embedded-content.html#introduction-3).

Components:
- [x] [`<picture>`](https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element)
- [x] [`<source>`](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element)
- [x] [sizes attribute](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-sizes) (see #10989 for prior work)
- [x] [srcset attribute](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset) (see #10829 for prior work)
- [x] [relevant mutations](https://html.spec.whatwg.org/multipage/embedded-content.html#relevant-mutations) processing
- [x] [update the source set](https://html.spec.whatwg.org/multipage/embedded-content.html#update-the-source-set) as part of the image selection process
- [x] [environment changes](https://html.spec.whatwg.org/multipage/embedded-content.html#img-environment-changes) processing

### PR DESCRIPTION
**Pull request by Rakhisharma**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #11416  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18846)

### CODE REVIEW

**Comment by jdm** [comment]
You will want to rebase only the final commit on a recent upstream commit. Also, a more informative PR title would help ;)

**Comment by wafflespeanut** [comment]
What's the status of this?

**Comment by wafflespeanut** [comment]
Closing due to inactivity. Feel free to ping us if you're planning to work on something again. :)

**Comment by Rakhisharma** [comment]
I apologize for not updating the status. If anyone is not working on 'Picture element part' I would like to pick it up again. Thanks.

**Comment by wafflespeanut** [comment]
No worries! Apparently #11416 never got unassigned, and I don't think anyone's working on it. So, please go ahead!

**Pull request closed without merging**
