### PR TITLE
style: Resolver cleanup and sharing by rule node fixes.

### PR DESCRIPTION
**Pull request by emilio**
See the individual commits for details.

This is the only coherent story I have for crashes like:

  https://crash-stats.mozilla.com/report/index/bcdfe629-ca1f-4e4d-aa17-27f890170917

(And the fact that there are crashes like it on the main thread kinda indicates it's the case)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18547)

### CODE REVIEW

**Review by heycam — APPROVED** [review]
Looks good.

**Comment by emilio** [comment]
Err,

@bors-servo r=heycam

**Pull request merged**
