### PR TITLE
Implement [Unforgeable]

### PR DESCRIPTION
**Pull request by nox**
This is mostly stolen from Gecko. As there, we define the unforgeable members
on an object stored in the slots of the prototype object. They are then copied
onto instance objects when they are instantiated. It should be noted that
proxy objects see their unforgeable memebers defined on their expando object.

Unforgeable attributes aren't properly inherited in codegen (in a similar
fashion as getters and setters as filed in #5875) and require to be redefined
in derived interfaces. Fortunately, there are currently no such interfaces.

No unforgeable members can be included into the TestBinding interfaces for good
measure because they are not compatible with setters.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7988)

### CODE REVIEW

**Comment by jdm** [comment]
This matches up well with Gecko's implementation. I'm happy with it!
-S-awaiting-review +@jdm 


---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 2214 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7988#-K2sD2TyEsDaTEVoz75J)** ([raw file](https://github.com/servo/servo/blob/1e62cf33bf3a2d8be8a9d63bd0f4ab8080ae114c/components/script/dom/bindings/codegen/CodegenRust.py#L2214)):</sup>
These functions return Result, so we need to check them. Gecko passes in a `failureCode` argument; we might be able to just assert that it's Ok.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7988)

**Comment by jdm** [comment]
That being said, I'd like to have a test for overwriting an unforgeable property as well as unforgeable properties on proxies.

**Comment by jdm** [comment]
Here's one from gecko we can steal: http://mxr.mozilla.org/mozilla-central/source/dom/bindings/test/test_unforgeablesonexpando.html?force=1

**Comment by nox** [comment]
I added a test. The failing one is unrelated to unforgeable attributes but I included it nonetheless.

-S-needs-rebase 


---

Review status: 2 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 2214 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7988#-K2sD2TyEsDaTEVoz75J)** ([raw file](https://github.com/servo/servo/blob/1e62cf33bf3a2d8be8a9d63bd0f4ab8080ae114c/components/script/dom/bindings/codegen/CodegenRust.py#L2214)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7988)

**Comment by jdm** [comment]
@bors-servo: r+
-C-needs-test 


---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7988)

**Comment by nox** [comment]
What.

**Comment by nox** [comment]
Interesting.

**Comment by nox** [comment]
@jdm There is an error in my code somewhere that makes `Location`'s finalizer be run twice or something like that. Still trying to make sense out of the failures.

**Comment by nox** [comment]
Found the problem!

The finalize hook needs to check for nullness now, because the unforgeable holder has the same prototype as actual instances (by design) and thus ends up being finalized the same way.

**Comment by jdm** [comment]
The hide_layers2.html failure is #8769.

**Comment by jdm** [comment]
Nice find, by the way :)

**Comment by nox** [comment]
I amended the patch with the test expectations.

**Comment by jdm** [comment]
This can merge with the requested comment addition.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 4706 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7988#-K4ZS4Q4wQbJ269OJ3k7:-K4ZS4Q4wQbJ269OJ3k8:223509475) ([raw file](https://github.com/servo/servo/blob/5f9115ef64bdd90eb71ec1e7d88a6bc15c876715/components/script/dom/bindings/codegen/CodegenRust.py#L4706)):*
Let's add a comment explaining why this is necessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7988#-:-K4ZSIjJQo0m1B90YY3u:2095504311)*

**Comment by nox** [comment]
Comment added.

@bors-servo r=jdm

**Comment by KiChjang** [comment]
```
Ran 3717 tests finished in 870.0 seconds.
  • 3716 ran as expected. 710 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /_mozilla/css/iframe/hide_layers2.html
  │ 
  │ thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
  │ stack backtrace:
  │    1:        0x107c70d08 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
  │    2:        0x107c72e4f - panicking::log_panic::_<closure>::closure.40650
  │    3:        0x107c728f2 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
  │    4:        0x107c5dde6 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
  │    5:        0x107c5e1ce - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
  │    6:        0x107c70327 - rust_begin_unwind
  │    7:        0x107c95430 - panicking::panic_fmt::h2f3428e3725b99d6VFK
  │    8:        0x10669962d - constellation::_<impl>::handle_request::handle_request::h14084396330141331367
  │    9:        0x10667eaa7 - sys_common::unwind::try::try_fn::try_fn::h5790274250769403721
  │   10:        0x107c70148 - __rust_try
  │   11:        0x107c6d24e - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  │   12:        0x106680b6a - boxed::_<impl>::call_box::call_box::h8113799359328547308
  │   13:        0x107c720dd - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  │   14:     0x7fff91449059 - _pthread_body
```

**Comment by KiChjang** [comment]
@bors-servo retry
* #8769

**Pull request merged**
