### PR TITLE
Put each unexpected dynamic symbols on its own line

### LINKED ISSUE #10797: Put each undefined symbol on its own line in check_dynamic_symbols.py
See the current output of the script in https://github.com/servo/servo/pull/10756#issuecomment-213076077.

Files:
 * `etc/ci/check_dynamic_symbols.py`

### PR DESCRIPTION
**Pull request by askeing**
fix #10797

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10818)

### CODE REVIEW

**Comment by askeing** [comment]
origin
```bash
Unexpected dynamic symbols in binary: _ZNSt13_Filebuf_base12_M_file_sizeEv, _ZN12JSPrincipals4dumpEv, _ZN8JSTracer16asCallbackTracerEv, _ZNSt10_UnderflowIcSt11char_traitsIcEE7_M_doitEPSt13basic_filebufIcS1_E, _ZSt24__stl_throw_length_errorPKc, _ZNSt13_Filebuf_base8_M_closeEv, _ZNSt13_Filebuf_base8_M_unmapEPvl, _ZNSt8ios_base16_M_throw_failureEv, _ZNSt13_Filebuf_base8_M_writeEPci, _ZNSt13_Filebuf_base7_M_seekEli, _ZNSt13_Filebuf_base12_M_page_sizeE, _ZNKSt6locale12_M_get_facetERKNS_2idE, _ZNSt13_Filebuf_base7_M_openEPKci, _ZN2JS12AutoGCRooter5traceEP8JSTracer, _ZNSt13_Filebuf_baseC1Ev, _ZNKSt5ctypeIcE8scan_notENSt10ctype_base4maskEPKcS4_, _ZNSt4priv11_GetFacetIdEPKSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE, _ZNKSt6locale12_M_use_facetERKNS_2idE
```

after modified
```bash
▶ Unexpected dynamic symbols in binary: _ZNSt13_Filebuf_base12_M_file_sizeEv
├ _ZN12JSPrincipals4dumpEv
├ _ZN8JSTracer16asCallbackTracerEv
├ _ZNSt10_UnderflowIcSt11char_traitsIcEE7_M_doitEPSt13basic_filebufIcS1_E
├ _ZSt24__stl_throw_length_errorPKc
├ _ZNSt13_Filebuf_base8_M_closeEv
├ _ZNSt13_Filebuf_base8_M_unmapEPvl
├ _ZNSt8ios_base16_M_throw_failureEv
├ _ZNSt13_Filebuf_base8_M_writeEPci
├ _ZNSt13_Filebuf_base7_M_seekEli
├ _ZNSt13_Filebuf_base12_M_page_sizeE
├ _ZNKSt6locale12_M_get_facetERKNS_2idE
├ _ZNSt13_Filebuf_base7_M_openEPKci
├ _ZN2JS12AutoGCRooter5traceEP8JSTracer
├ _ZNSt13_Filebuf_baseC1Ev
├ _ZNKSt5ctypeIcE8scan_notENSt10ctype_base4maskEPKcS4_
├ _ZNSt4priv11_GetFacetIdEPKSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE
└ _ZNKSt6locale12_M_use_facetERKNS_2idE
```

**Comment by nox** [comment]
Nit: Put the first one on its own line and remove the (beautiful) markup, to ease copy and paste etc.

**Comment by askeing** [comment]
Sorry for missing the first line.
```bash
▶ Unexpected dynamic symbols in binary:
├ _ZNSt13_Filebuf_base12_M_file_sizeEv
├ _ZN12JSPrincipals4dumpEv
├ _ZN8JSTracer16asCallbackTracerEv
├ _ZNSt10_UnderflowIcSt11char_traitsIcEE7_M_doitEPSt13basic_filebufIcS1_E
├ _ZSt24__stl_throw_length_errorPKc
├ _ZNSt13_Filebuf_base8_M_closeEv
├ _ZNSt13_Filebuf_base8_M_unmapEPvl
├ _ZNSt8ios_base16_M_throw_failureEv
├ _ZNSt13_Filebuf_base8_M_writeEPci
├ _ZNSt13_Filebuf_base7_M_seekEli
├ _ZNSt13_Filebuf_base12_M_page_sizeE
├ _ZNKSt6locale12_M_get_facetERKNS_2idE
├ _ZNSt13_Filebuf_base7_M_openEPKci
├ _ZN2JS12AutoGCRooter5traceEP8JSTracer
├ _ZNSt13_Filebuf_baseC1Ev
├ _ZNKSt5ctypeIcE8scan_notENSt10ctype_base4maskEPKcS4_
├ _ZNSt4priv11_GetFacetIdEPKSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE
└ _ZNKSt6locale12_M_use_facetERKNS_2idE
```

**Comment by nox** [comment]
Could you remove the various `├` characters?

**Comment by askeing** [comment]
Ok. Should I also remove the `▶` character of first line?
Which format is better for you?

Has arrow
```bash
▶ Unexpected dynamic symbols in binary:
_ZNSt13_Filebuf_base12_M_file_sizeEv
...
_ZNKSt6locale12_M_use_facetERKNS_2idE
```

No arrow
```bash
Unexpected dynamic symbols in binary:
_ZNSt13_Filebuf_base12_M_file_sizeEv
...
_ZNKSt6locale12_M_use_facetERKNS_2idE
```

**Comment by askeing** [comment]
Removed the `▶`, `├`, and `└` chars from output.
Here's current result:
```bash
Unexpected dynamic symbols in binary:
_ZNSt13_Filebuf_base12_M_file_sizeEv
...
_ZNKSt6locale12_M_use_facetERKNS_2idE
```

**Comment by aneeshusa** [comment]
While we're updating the printing, can you also add a
```
from __future__ import absolute_import

```
at the top of the file, above the other imports?

**Comment by askeing** [comment]
@aneeshusa I added it at Line 10 for passing the tidy license check :)

**Comment by aneeshusa** [comment]
@askeing Thanks! I typo'd before and I meant to write `print_function` instead of `absolute_import` before; can you please change that line to `from __future__ import absolute_import, print_function`? (It doesn't hurt to keep `absolute_import`.)

Also, style nit: please add an empty line between the `__future__` imports and the other imports.

**Comment by askeing** [comment]
@aneeshusa okay, finished :)

**Pull request merged**
