### PR TITLE
layout: Reset values appropriately for floats flowing out of blocks with nonzero inline margins.

### PR DESCRIPTION
**Pull request by pcwalton**
These two commits correctly position the hamburger menu icons on http://reddit.com/r/rust.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10623)

### CODE REVIEW

**Comment by mbrubeck** [comment]
r=mbrubeck with nits below fixed. -S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/layout/block.rs, line 875 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10623#-KFPoXfCyHOuiztALSJB:-KFPoXfDwxxLbICleFyg:1602498525) ([raw file](https://github.com/servo/servo/blob/82c93fb2d6e1644785b62f1d2729b8b27a96e19b/components/layout/block.rs#L875)):*
Maybe un-comment this and change `println!` to `debug!`?

---

*[components/layout/floats.rs, line 491 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10623#-KFPocHWT2D1wZc5F6Uw:-KFPocHWT2D1wZc5F6Ux:-2046407288) ([raw file](https://github.com/servo/servo/blob/82c93fb2d6e1644785b62f1d2729b8b27a96e19b/components/layout/floats.rs#L491)):*
`debug!`?

---

*[components/layout/floats.rs, line 520 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10623#-KFPoea2BH5P1hYua5RP:-KFPoea2BH5P1hYua5RQ:-2046407288) ([raw file](https://github.com/servo/servo/blob/82c93fb2d6e1644785b62f1d2729b8b27a96e19b/components/layout/floats.rs#L520)):*
`debug!`?

---

*[tests/wpt/mozilla/meta/MANIFEST.json, line 1226 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10623#-KFRPMAkbU_jFi0aXOHg:-KFRPMAl0qn3wVpHyJrp:-1851198275) ([raw file](https://github.com/servo/servo/blob/82c93fb2d6e1644785b62f1d2729b8b27a96e19b/tests/wpt/mozilla/meta/MANIFEST.json#L1226)):*
I think you still have some leftover files in your working dir.  You should remove them and update the manifest.

---

*[tests/wpt/mozilla/meta/MANIFEST.json, line 7876 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10623#-KFRPUOHcF997yyhiYW4:-KFRPUOI2mD-xvnUTVuJ:610327397) ([raw file](https://github.com/servo/servo/blob/82c93fb2d6e1644785b62f1d2729b8b27a96e19b/tests/wpt/mozilla/meta/MANIFEST.json#L7876)):*
Remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10623#-:-KFRPzcPAWYvRx92_s9O:1871471864)*

**Comment by KiChjang** [comment]
```
diff --git a/tests/wpt/mozilla/meta/MANIFEST.json b/tests/wpt/mozilla/meta/MANIFEST.json
index b712281..fb7e4eb 100644
--- a/tests/wpt/mozilla/meta/MANIFEST.json
+++ b/tests/wpt/mozilla/meta/MANIFEST.json
@@ -1595,40 +1595,40 @@
             "url": "/_mozilla/css/floated_table_with_margin_a.html"
           }
         ],
-        "css/floats_margin_collapse_a.html": [
+        "css/floats_inline_margins_a.html": [
           {
-            "path": "css/floats_margin_collapse_a.html",
+            "path": "css/floats_inline_margins_a.html",
             "references": [
               [
-                "/_mozilla/css/floats_margin_collapse_ref.html",
+                "/_mozilla/css/floats_inline_margins_ref.html",
                 "=="
               ]
             ],
-            "url": "/_mozilla/css/floats_margin_collapse_a.html"
+            "url": "/_mozilla/css/floats_inline_margins_a.html"
           }
         ],
-        "css/floats_margin_collapse_with_clearance_a.html": [
+        "css/floats_margin_collapse_a.html": [
           {
-            "path": "css/floats_margin_collapse_with_clearance_a.html",
+            "path": "css/floats_margin_collapse_a.html",
             "references": [
               [
-                "/_mozilla/css/floats_margin_collapse_with_clearance_ref.html",
+                "/_mozilla/css/floats_margin_collapse_ref.html",
                 "=="
               ]
             ],
-            "url": "/_mozilla/css/floats_margin_collapse_with_clearance_a.html"
+            "url": "/_mozilla/css/floats_margin_collapse_a.html"
           }
         ],
-        "css/floats_inline_margins_a.html": [
+        "css/floats_margin_collapse_with_clearance_a.html": [
           {
-            "path": "css/floats_inline_margins_a.html",
+            "path": "css/floats_margin_collapse_with_clearance_a.html",
             "references": [
               [
-                "/_mozilla/css/floats_inline_margins_ref.html",
+                "/_mozilla/css/floats_margin_collapse_with_clearance_ref.html",
                 "=="
               ]
             ],
-            "url": "/_mozilla/css/floats_inline_margins_a.html"
+            "url": "/_mozilla/css/floats_margin_collapse_with_clearance_a.html"
           }
         ],
         "css/focus_selector.html": [
@@ -8245,40 +8245,40 @@
           "url": "/_mozilla/css/floated_table_with_margin_a.html"
         }
       ],
-      "css/floats_margin_collapse_a.html": [
+      "css/floats_inline_margins_a.html": [
         {
-          "path": "css/floats_margin_collapse_a.html",
+          "path": "css/floats_inline_margins_a.html",
           "references": [
             [
-              "/_mozilla/css/floats_margin_collapse_ref.html",
+              "/_mozilla/css/floats_inline_margins_ref.html",
               "=="
             ]
           ],
-          "url": "/_mozilla/css/floats_margin_collapse_a.html"
+          "url": "/_mozilla/css/floats_inline_margins_a.html"
         }
       ],
-      "css/floats_margin_collapse_with_clearance_a.html": [
+      "css/floats_margin_collapse_a.html": [
         {
-          "path": "css/floats_margin_collapse_with_clearance_a.html",
+          "path": "css/floats_margin_collapse_a.html",
           "references": [
             [
-              "/_mozilla/css/floats_margin_collapse_with_clearance_ref.html",
+              "/_mozilla/css/floats_margin_collapse_ref.html",
               "=="
             ]
           ],
-          "url": "/_mozilla/css/floats_margin_collapse_with_clearance_a.html"
+          "url": "/_mozilla/css/floats_margin_collapse_a.html"
         }
       ],
-      "css/floats_inline_margins_a.html": [
+      "css/floats_margin_collapse_with_clearance_a.html": [
         {
-          "path": "css/floats_inline_margins_a.html",
+          "path": "css/floats_margin_collapse_with_clearance_a.html",
           "references": [
             [
-              "/_mozilla/css/floats_inline_margins_ref.html",
+              "/_mozilla/css/floats_margin_collapse_with_clearance_ref.html",
               "=="
             ]
           ],
-          "url": "/_mozilla/css/floats_inline_margins_a.html"
+          "url": "/_mozilla/css/floats_margin_collapse_with_clearance_a.html"
         }
       ],
       "css/focus_selector.html": [
```

**Comment by mbrubeck** [comment]
Maybe I was wrong about the manifest changes being incorrect?  I don't understand.

**Comment by pcwalton** [comment]
Sorry, that was just my mistake.

**Comment by KiChjang** [comment]
```
diff --git a/tests/wpt/mozilla/meta/MANIFEST.json b/tests/wpt/mozilla/meta/MANIFEST.json
index 6aa3c30..fb78df5 100644
--- a/tests/wpt/mozilla/meta/MANIFEST.json
+++ b/tests/wpt/mozilla/meta/MANIFEST.json
@@ -1620,40 +1620,40 @@
             "url": "/_mozilla/css/floated_table_with_margin_a.html"
           }
         ],
-        "css/floats_margin_collapse_a.html": [
+        "css/floats_inline_margins_a.html": [
           {
-            "path": "css/floats_margin_collapse_a.html",
+            "path": "css/floats_inline_margins_a.html",
             "references": [
               [
-                "/_mozilla/css/floats_margin_collapse_ref.html",
+                "/_mozilla/css/floats_inline_margins_ref.html",
                 "=="
               ]
             ],
-            "url": "/_mozilla/css/floats_margin_collapse_a.html"
+            "url": "/_mozilla/css/floats_inline_margins_a.html"
           }
         ],
-        "css/floats_margin_collapse_with_clearance_a.html": [
+        "css/floats_margin_collapse_a.html": [
           {
-            "path": "css/floats_margin_collapse_with_clearance_a.html",
+            "path": "css/floats_margin_collapse_a.html",
             "references": [
               [
-                "/_mozilla/css/floats_margin_collapse_with_clearance_ref.html",
+                "/_mozilla/css/floats_margin_collapse_ref.html",
                 "=="
               ]
             ],
-            "url": "/_mozilla/css/floats_margin_collapse_with_clearance_a.html"
+            "url": "/_mozilla/css/floats_margin_collapse_a.html"
           }
         ],
-        "css/floats_inline_margins_a.html": [
+        "css/floats_margin_collapse_with_clearance_a.html": [
           {
-            "path": "css/floats_inline_margins_a.html",
+            "path": "css/floats_margin_collapse_with_clearance_a.html",
             "references": [
               [
-                "/_mozilla/css/floats_inline_margins_ref.html",
+                "/_mozilla/css/floats_margin_collapse_with_clearance_ref.html",
                 "=="
               ]
             ],
-            "url": "/_mozilla/css/floats_inline_margins_a.html"
+            "url": "/_mozilla/css/floats_margin_collapse_with_clearance_a.html"
           }
         ],
         "css/focus_selector.html": [
@@ -8372,40 +8372,40 @@
           "url": "/_mozilla/css/floated_table_with_margin_a.html"
         }
       ],
-      "css/floats_margin_collapse_a.html": [
+      "css/floats_inline_margins_a.html": [
         {
-          "path": "css/floats_margin_collapse_a.html",
+          "path": "css/floats_inline_margins_a.html",
           "references": [
             [
-              "/_mozilla/css/floats_margin_collapse_ref.html",
+              "/_mozilla/css/floats_inline_margins_ref.html",
               "=="
             ]
           ],
-          "url": "/_mozilla/css/floats_margin_collapse_a.html"
+          "url": "/_mozilla/css/floats_inline_margins_a.html"
         }
       ],
-      "css/floats_margin_collapse_with_clearance_a.html": [
+      "css/floats_margin_collapse_a.html": [
         {
-          "path": "css/floats_margin_collapse_with_clearance_a.html",
+          "path": "css/floats_margin_collapse_a.html",
           "references": [
             [
-              "/_mozilla/css/floats_margin_collapse_with_clearance_ref.html",
+              "/_mozilla/css/floats_margin_collapse_ref.html",
               "=="
             ]
           ],
-          "url": "/_mozilla/css/floats_margin_collapse_with_clearance_a.html"
+          "url": "/_mozilla/css/floats_margin_collapse_a.html"
         }
       ],
-      "css/floats_inline_margins_a.html": [
+      "css/floats_margin_collapse_with_clearance_a.html": [
         {
-          "path": "css/floats_inline_margins_a.html",
+          "path": "css/floats_margin_collapse_with_clearance_a.html",
           "references": [
             [
-              "/_mozilla/css/floats_inline_margins_ref.html",
+              "/_mozilla/css/floats_margin_collapse_with_clearance_ref.html",
               "=="
             ]
           ],
-          "url": "/_mozilla/css/floats_inline_margins_a.html"
+          "url": "/_mozilla/css/floats_margin_collapse_with_clearance_a.html"
         }
       ],
       "css/focus_selector.html": [
```

**Comment by pcwalton** [comment]
Confusing error. @larsbergstrom?

**Comment by larsbergstrom** [comment]
@pcwalton in Reviewable, @mbrubeck mentioned "I think you still have some leftover files in your working dir. You should remove them and update the manifest."

**Comment by mbrubeck** [comment]
The PR has some entries out of (alphabetical) order in the manifest, so `--manifest-update` is just reordering them.

**Comment by pcwalton** [comment]
@mbrubeck Aha, thank you.

**Pull request merged**
