### PR TITLE
Embedding windowing

### PR DESCRIPTION
**Pull request by zmike**
Depends on glutin PR #21

@glennw  @larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6016)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed files:
- ports/cef/browser.rs @ r6
- ports/cef/browser_host.rs @ r6
- ports/cef/core.rs @ r4
- ports/glutin/window.rs @ r6

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6016)

**Comment by larsbergstrom** [comment]
Does this also need an update to the CEF lock file for the updated glutin with landed commit? I believe you can do so with:
```
./mach update-cargo -p glutin
```

Also, waiting to approve until you resolve the URL-related changes you wanted to make.

**Comment by zmike** [comment]
I'll answer all these questions in about 4 hours when this test compile finishes.

**Comment by zmike** [comment]
We can just say this depends on #5995 now

**Comment by larsbergstrom** [comment]
This is r=me once #5995 lands

**Comment by jdm** [comment]
The reftest failure is #5958. However:
```
browser.rs:105:54: 105:55 error: mismatched types:
 expected `*mut libc::types::common::c95::c_void`,
    found `usize`
(expected *-ptr,
    found usize) [E0308]
browser.rs:105         let mut window_handle: cef_window_handle_t = 0;
                                                                    ^
browser.rs:151:41: 151:42 error: mismatched types:
 expected `*mut libc::types::common::c95::c_void`,
    found `usize`
(expected *-ptr,
    found usize) [E0308]
browser.rs:151         if window_info.parent_window != 0 {
                                                       ^
error: aborting due to 2 previous errors
Could not compile `embedding`.
```

**Comment by zmike** [comment]
Argh! Well I can't compile for macos, so I guess I'll keep putting updates into the branch to see if it compiles.

**Comment by zmike** [comment]
@jdm Try now I guess?

**Comment by jdm** [comment]
Any reason why you didn't initialize it to `ptr::mut_null()` and check `.is_null()`?

**Comment by jdm** [comment]
Nevermind, this looks like it would work too.

**Comment by zmike** [comment]
On linux it's an int type, not a ptr.

**Comment by jdm** [comment]
```
browser.rs:105:54: 105:70 error: the trait `core::default::Default` is not implemented for the type `*mut libc::types::common::c95::c_void` [E0277]
browser.rs:105         let mut window_handle: cef_window_handle_t = Default::default();
                                                                    ^~~~~~~~~~~~~~~~
```

**Comment by zmike** [comment]
I tried doing per-platform initialization using [cfg(target_os... lines, but, I get errors like

browser.rs:107:25: 107:26 error: expected item after attributes
browser.rs:107 #[cfg(target_os="macos")]

Suggestions?

**Comment by jdm** [comment]
There's `if cfg!(...)` you can use for that instead.

**Pull request merged**
