### PR TITLE
Run word-spacing tests under wpt.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7126)

### CODE REVIEW

**Comment by jdm** [comment]
Whoops!
```

---- word_spacing_a.html == word_spacing_ref.html stdout ----
	thread 'word_spacing_a.html == word_spacing_ref.html' panicked at 'Both renderings are empty', ../../tests/reftest.rs:316
```

**Comment by Ms2ger** [comment]
Whoops indeed.

**Comment by SimonSapin** [comment]
```
failed to run custom build command for `gleam v0.1.7`
Process didn't exit successfully: `/Users/servo/buildbot/slave/mac2/build/target/debug/build/gleam-41e398285c55c3fc/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'XML error: Error { pos: 29646:6, msg: "Unexpected end of stream: still inside the root element" }', /Users/servo/.cargo/registry/src/github.com-0a35038f75765ae4/gl_generator-0.0.27/registry.rs:328
stack backtrace:
   1:        0x102bed8f5 - sys::backtrace::write::h2513b694e23623efOvs
   2:        0x102bf6c70 - panicking::on_panic::h399650fb5f386215wWw
   3:        0x102bb03e2 - rt::unwind::begin_unwind_inner::h208861166cac0468HEw
   4:        0x102bb12bc - rt::unwind::begin_unwind_fmt::h2b843ddd6c3f7d25NDw
   5:        0x102789c6d - registry::RegistryBuilder<R>::recv::h5241867105180511809
   6:        0x1027b5e89 - registry::RegistryBuilder<R>::consume_two::h17753134333946543666
   7:        0x1027b5833 - registry::Require.FromXML::convert::h120760129474894892
   8:        0x1027b3c94 - registry::RegistryBuilder<R>::consume_two::h5363052486117708807
   9:        0x1027b2b17 - registry::Feature.FromXML::convert::h8162648643011244436
  10:        0x102787257 - registry::RegistryBuilder<R>::consume_registry::h13312214517257856163
  11:        0x102785e98 - registry::Registry::from_xml::h449339401943938677
  12:        0x1027d37e8 - generate_bindings::h6217841836777709169
  13:        0x10277873a - main::h66576c74bbcada4bkaa
  14:        0x102bf64af - __rust_try_inner
  15:        0x102bf64ea - __rust_try
  16:        0x102bf7b1a - rt::lang_start::h62f9a1aa1fee3678sRw
  17:        0x1027d941e - main

**Comment by Ms2ger** [comment]
@bors-servo retry
* https://github.com/servo/servo/issues/7155

**Pull request merged**
