### PR TITLE
Take ScriptThread::compositor out of its RefCell.

### PR DESCRIPTION
**Pull request by Ms2ger**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy --faster` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because refactoring

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. 

There's no reason for it; IpcSender::send takes &self.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11338)

### CODE REVIEW

**Comment by nox** [comment]
Nice catch as usual.

@bors-servo r+

**Comment by larsbergstrom** [comment]
this was infra stuff

**Comment by mbrubeck** [comment]
@bors-servo retry

* #11100

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11100

**Pull request merged**
