### PR TITLE
Update euclid in servo-media and rust-webvr.

### PR DESCRIPTION
**Pull request by emilio**
And thus finish the euclid update.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23842)

### CODE REVIEW

**Comment by CYBAI** [comment]
@bors-servo retry

- Hmm... the update is related to `servo-media`, not sure if the failure is related so let's retry!

```
  = note: /home/servo/buildbot/slave/linux-rel-wpt/build/target/release/deps/libgstreamer_gl-f443a8c6f3880ff3.rlib(gstreamer_gl-f443a8c6f3880ff3.gstreamer_gl.1q23owqq-cgu.4.rcgu.o):gstreamer_gl.1q23owqq-cgu.4:function gstreamer_gl::gl_display_wayland::_$LT$impl$u20$gstreamer_gl..auto..gl_display_wayland..GLDisplayWayland$GT$::new_with_display::h1eab92a985f184fc: error: undefined reference to 'gst_gl_display_wayland_new_with_display'
          /home/servo/buildbot/slave/linux-rel-wpt/build/target/release/deps/libgstreamer_gl-f443a8c6f3880ff3.rlib(gstreamer_gl-f443a8c6f3880ff3.gstreamer_gl.1q23owqq-cgu.4.rcgu.o):gstreamer_gl.1q23owqq-cgu.4:function gstreamer_gl::gl_display_wayland::_$LT$impl$u20$gstreamer_gl..auto..gl_display_wayland..GLDisplayWayland$GT$::new_with_display::h1eab92a985f184fc: error: undefined reference to 'gst_gl_display_wayland_get_type'
          collect2: error: ld returned 1 exit status
```

**Comment by CYBAI** [comment]
Same failure again 👀

```
  = note: /home/servo/buildbot/slave/linux-rel-css/build/target/release/deps/libgstreamer_gl-f443a8c6f3880ff3.rlib(gstreamer_gl-f443a8c6f3880ff3.gstreamer_gl.1q23owqq-cgu.4.rcgu.o):gstreamer_gl.1q23owqq-cgu.4:function gstreamer_gl::gl_display_wayland::_$LT$impl$u20$gstreamer_gl..auto..gl_display_wayland..GLDisplayWayland$GT$::new_with_display::h1eab92a985f184fc: error: undefined reference to 'gst_gl_display_wayland_new_with_display'
          /home/servo/buildbot/slave/linux-rel-css/build/target/release/deps/libgstreamer_gl-f443a8c6f3880ff3.rlib(gstreamer_gl-f443a8c6f3880ff3.gstreamer_gl.1q23owqq-cgu.4.rcgu.o):gstreamer_gl.1q23owqq-cgu.4:function gstreamer_gl::gl_display_wayland::_$LT$impl$u20$gstreamer_gl..auto..gl_display_wayland..GLDisplayWayland$GT$::new_with_display::h1eab92a985f184fc: error: undefined reference to 'gst_gl_display_wayland_get_type'
          collect2: error: ld returned 1 exit status
```

**Comment by jdm** [comment]
@ferjm/@ceyusa More gstgl linking issues :(

**Comment by ferjm** [comment]
Feature flags sounds good to me.

We may be able to workaround the issue by regenerating the gstreamer binaries for CI with all the required deps for gstgl to expose wayland related symbols.

**Comment by ferjm** [comment]
> Same failure again 👀
> 
> ```
>   = note: /home/servo/buildbot/slave/linux-rel-css/build/target/release/deps/libgstreamer_gl-f443a8c6f3880ff3.rlib(gstreamer_gl-f443a8c6f3880ff3.gstreamer_gl.1q23owqq-cgu.4.rcgu.o):gstreamer_gl.1q23owqq-cgu.4:function gstreamer_gl::gl_display_wayland::_$LT$impl$u20$gstreamer_gl..auto..gl_display_wayland..GLDisplayWayland$GT$::new_with_display::h1eab92a985f184fc: error: undefined reference to 'gst_gl_display_wayland_new_with_display'
>           /home/servo/buildbot/slave/linux-rel-css/build/target/release/deps/libgstreamer_gl-f443a8c6f3880ff3.rlib(gstreamer_gl-f443a8c6f3880ff3.gstreamer_gl.1q23owqq-cgu.4.rcgu.o):gstreamer_gl.1q23owqq-cgu.4:function gstreamer_gl::gl_display_wayland::_$LT$impl$u20$gstreamer_gl..auto..gl_display_wayland..GLDisplayWayland$GT$::new_with_display::h1eab92a985f184fc: error: undefined reference to 'gst_gl_display_wayland_get_type'
>           collect2: error: ld returned 1 exit status
> ```

This should be fixed after #23853. @emilio could you rebase, please?

**Comment by dralley** [comment]
@emilio I think this PR can be closed now, euclid got updated at some point: https://github.com/servo/servo/blob/master/Cargo.lock#L1477-L1478

**Pull request closed without merging**
