### PR TITLE
Replace mpsc with crossbeam-channel

### PR DESCRIPTION
**Pull request by SimonSapin**
Selecting over multiple channels in `std::sync::mpsc` is not stable and likely never will be:

https://github.com/rust-lang/rust/issues/27800#issuecomment-260136777
> It seems the only thing keeping `mpsc_select` around is Servo.

crossbeam-channel is designed specifically to replace `std::sync::mpsc` and fix many of its shortcomings:
https://github.com/stjepang/rfcs-crossbeam/blob/channel/text/2017-11-09-channel.md

This is to be landed together with https://github.com/servo/ipc-channel/pull/183.

----

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19515)

### CODE REVIEW

**Comment by SimonSapin** [comment]
This does not compile yet. This is a rebase of @stjepang’s branch. Still needed: update to the new selection API, and update the `ipc-channel` crate. @stjepang, did you have a branch for that?

**Comment by SimonSapin** [comment]
This depends on https://github.com/servo/servo/pull/19512, https://github.com/crossbeam-rs/crossbeam-channel/pull/16, and https://github.com/crossbeam-rs/crossbeam-channel/pull/17 to pass tidy.

**Comment by stjepang** [comment]
I do have a WIP branch for `ipc-channel`: https://github.com/servo/ipc-channel/compare/master...stjepang:crossbeam-channel
Currently it is blocked on [this issue](https://github.com/crossbeam-rs/crossbeam-channel/issues/6), which should be fairly easy to fix. Working on it.
If you're curious, [here](https://gist.github.com/stjepang/1d5bf7ee199bf2c09545069e58d1fe46) are the benchmark results with flag `--features force-inprocess`.

> Still needed: update to the new selection API,

By *new selection API* you mean the `select_loop!` macro? Btw, check out [these changes](https://github.com/crossbeam-rs/crossbeam-channel/issues/3) we've recently made to the macro to make a bit more convenient to use in Servo.

Also, I'd (probably) like to make three breaking changes to `crossbeam-channel` before we integrate it into Servo:

1. https://github.com/crossbeam-rs/crossbeam-channel/issues/6
2. https://github.com/crossbeam-rs/crossbeam-channel/issues/10
3. https://github.com/crossbeam-rs/crossbeam-channel/issues/11

If you have any input to these issues, that'd be really helpful in sorting them out.

**Comment by SimonSapin** [comment]
> By new selection API you mean the select_loop! macro?

That, or the explicit `Select` struct. This patch uses the API from the prototype with thread-local magic.

> Also, I'd (probably) like to make three breaking changes to crossbeam-channel before we integrate it into Servo

Alright, there’s no hurry landing this.

**Comment by SimonSapin** [comment]
This now compiles, but merging is blocked on:

* https://github.com/crossbeam-rs/crossbeam-channel/issues/6 + using it
* https://github.com/servo/ipc-channel/pull/183 + using it and removing `[patch]`

@bors-servo try

**Comment by SimonSapin** [comment]
Some of the test results are `TIMEOUT [expected CRASH]` with a backtrace in the output. This is likely failing to detect that a channel is disconnected: https://github.com/crossbeam-rs/crossbeam-channel/issues/6.

<details>

```
Ran 9451 tests finished in 855.0 seconds.
  • 9436 ran as expected. 1671 tests skipped.
  • 1 tests failed unexpectedly
  • 12 tests timed out unexpectedly
  • 3 tests had unexpected subtest results

Tests with unexpected results:
  ▶ TIMEOUT [expected PASS] /2dcontext/compositing/canvas_compositing_globalcompositeoperation_001.htm
  │ 
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 17.3.0-devel

  ▶ TIMEOUT [expected PASS] /_mozilla/mozilla/css-paint-api/paint2d-composite.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ Loading blob blob:http://web-platform.test:8000/9bc92b0406814a54b31414b6189625ea
  │ Loading blob blob:http://web-platform.test:8000/9bc92b0406814a54b31414b6189625ea
  └ Loading blob blob:http://web-platform.test:8000/9bc92b0406814a54b31414b6189625ea

  ▶ TIMEOUT [expected CRASH] /_mozilla/webgl/conformance-1.0.3/conformance/more/functions/uniformfBadArgs.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ Unexpected WebGL error: 0x502 (1282) (thread WebGLThread, at components/canvas/webgl_thread.rs:883)
  │ stack backtrace:
  │    0:     0x7f13f2f56bac - backtrace::backtrace::trace::h6b0af94f74672f08
  │    1:     0x7f13f2f56be2 - backtrace::capture::Backtrace::new::hbff890d685663b85
  │    2:     0x7f13f1cea752 - servo::main::{{closure}}::h2df85a5f78215329
  │    3:     0x7f13f4299fd5 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7f13f4299e5e - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7f13f4299d5a - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7f13f301c5b3 - canvas::webgl_thread::WebGLImpl::apply::h69dac2848d216ca3
  │    7:     0x7f13f2fead22 - <canvas::webgl_thread::WebGLThread<VR, OB>>::handle_msg::h2017b137593ecf69
  │    8:     0x7f13f2f83287 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd09c826cc86f70f9
  │    9:     0x7f13f2f834ef - std::panicking::try::do_call::h297297dd1b75e1f5
  │   10:     0x7f13f42b54ce - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   11:     0x7f13f2f9c92e - <F as alloc::boxed::FnBox<A>>::call_box::hcf2e0e9e98eec6c5
  │   12:     0x7f13f429162b - std::sys_common::thread::start_thread
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys::unix::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   13:     0x7f13efde5183 - start_thread
  │   14:     0x7f13ef4d9ffc - clone
  │   15:                0x0 - <unknown>
  └ ERROR:servo: Unexpected WebGL error: 0x502 (1282)

  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-img-element/non-active-document.html:
  └ PASS [expected FAIL] DOMParser

  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-img-element/non-active-document.html:
  └ PASS [expected FAIL] createHTMLDocument

  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-img-element/non-active-document.html:
  └ PASS [expected FAIL] <template>

  ▶ TIMEOUT [expected CRASH] /_mozilla/webgl/conformance-1.0.3/conformance/more/functions/uniformiBadArgs.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ Unexpected WebGL error: 0x502 (1282) (thread WebGLThread, at components/canvas/webgl_thread.rs:883)
  │ stack backtrace:
  │    0:     0x7f2d241cfbac - backtrace::backtrace::trace::h6b0af94f74672f08
  │    1:     0x7f2d241cfbe2 - backtrace::capture::Backtrace::new::hbff890d685663b85
  │    2:     0x7f2d22f63752 - servo::main::{{closure}}::h2df85a5f78215329
  │    3:     0x7f2d25512fd5 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7f2d25512e5e - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7f2d25512d5a - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7f2d242955b3 - canvas::webgl_thread::WebGLImpl::apply::h69dac2848d216ca3
  │    7:     0x7f2d24263d22 - <canvas::webgl_thread::WebGLThread<VR, OB>>::handle_msg::h2017b137593ecf69
  │    8:     0x7f2d241fc287 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd09c826cc86f70f9
  │    9:     0x7f2d241fc4ef - std::panicking::try::do_call::h297297dd1b75e1f5
  │   10:     0x7f2d2552e4ce - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   11:     0x7f2d2421592e - <F as alloc::boxed::FnBox<A>>::call_box::hcf2e0e9e98eec6c5
  │   12:     0x7f2d2550a62b - std::sys_common::thread::start_thread
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys::unix::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   13:     0x7f2d2105e183 - start_thread
  │   14:     0x7f2d20752ffc - clone
  │   15:                0x0 - <unknown>
  └ ERROR:servo: Unexpected WebGL error: 0x502 (1282)

  ▶ TIMEOUT [expected OK] /_mozilla/webgl/conformance-1.0.3/conformance/glsl/misc/shader-with-non-reserved-words.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ DESCRIPTION: WebGL GLSL Conformance Tests - Non Reserved Words
  │ 
  │ testing: Buffer
  │ PASS shader with: 'Buffer' compiled
```
…
```
  └ PASS getError was expected value: NO_ERROR : should be no GL errors

  ▶ Unexpected subtest result in /_mozilla/webgl/conformance-1.0.3/conformance/glsl/misc/shader-with-non-reserved-words.html:
  └ NOTRUN [expected PASS] Overall test

  ▶ TIMEOUT [expected CRASH] /_mozilla/webgl/conformance-1.0.3/conformance/more/functions/uniformMatrixBadArgs.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ Unexpected WebGL error: 0x502 (1282) (thread WebGLThread, at components/canvas/webgl_thread.rs:883)
  │ stack backtrace:
  │    0:     0x7f8470cd2bac - backtrace::backtrace::trace::h6b0af94f74672f08
  │    1:     0x7f8470cd2be2 - backtrace::capture::Backtrace::new::hbff890d685663b85
  │    2:     0x7f846fa66752 - servo::main::{{closure}}::h2df85a5f78215329
  │    3:     0x7f8472015fd5 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7f8472015e5e - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7f8472015d5a - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7f8470d985b3 - canvas::webgl_thread::WebGLImpl::apply::h69dac2848d216ca3
  │    7:     0x7f8470d66d22 - <canvas::webgl_thread::WebGLThread<VR, OB>>::handle_msg::h2017b137593ecf69
  │    8:     0x7f8470cff287 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd09c826cc86f70f9
  │    9:     0x7f8470cff4ef - std::panicking::try::do_call::h297297dd1b75e1f5
  │   10:     0x7f84720314ce - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   11:     0x7f8470d1892e - <F as alloc::boxed::FnBox<A>>::call_box::hcf2e0e9e98eec6c5
  │   12:     0x7f847200d62b - std::sys_common::thread::start_thread
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys::unix::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   13:     0x7f846db61183 - start_thread
  │   14:     0x7f846d255ffc - clone
  │   15:                0x0 - <unknown>
  └ ERROR:servo: Unexpected WebGL error: 0x502 (1282)

  ▶ TIMEOUT [expected CRASH] /_mozilla/webgl/conformance-2.0.0/conformance2/renderbuffers/multisampled-renderbuffer-initialization.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ DESCRIPTION: Verify multisampled renderbuffers are initialized to 0 before being read in WebGL
  │ PASS internal buffers have been initialized to 0
  │ PASS gl.checkFramebufferStatus(gl.FRAMEBUFFER) is gl.FRAMEBUFFER_COMPLETE
  │ FAIL getError expected: NO_ERROR. Was INVALID_ENUM : should be no errors
  │ Unexpected WebGL error: 0x506 (1286) (thread WebGLThread, at components/canvas/webgl_thread.rs:883)
  │ FAIL user buffer has been cleared to green
  │ at (0, 0) expected: 0,255,0,255 was 0,0,0,0
  │ stack backtrace:
  │    0:     0x7f60fee86bac - backtrace::backtrace::trace::h6b0af94f74672f08
  │    1:     0x7f60fee86be2 - backtrace::capture::Backtrace::new::hbff890d685663b85
  │    2:     0x7f60fdc1a752 - servo::main::{{closure}}::h2df85a5f78215329
  │    3:     0x7f61001c9fd5 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7f61001c9e5e - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7f61001c9d5a - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7f60fef4c5b3 - canvas::webgl_thread::WebGLImpl::apply::h69dac2848d216ca3
  │    7:     0x7f60fef1ad22 - <canvas::webgl_thread::WebGLThread<VR, OB>>::handle_msg::h2017b137593ecf69
  │    8:     0x7f60feeb3287 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd09c826cc86f70f9
  │    9:     0x7f60feeb34ef - std::panicking::try::do_call::h297297dd1b75e1f5
  │   10:     0x7f61001e54ce - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   11:     0x7f60feecc92e - <F as alloc::boxed::FnBox<A>>::call_box::hcf2e0e9e98eec6c5
  │   12:     0x7f61001c162b - std::sys_common::thread::start_thread
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys::unix::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   13:     0x7f60fbd15183 - start_thread
  │   14:     0x7f60fb409ffc - clone
  │   15:                0x0 - <unknown>
  └ ERROR:servo: Unexpected WebGL error: 0x506 (1286)

  ▶ TIMEOUT [expected CRASH] /_mozilla/webgl/conformance-2.0.0/conformance2/reading/read-pixels-from-rgb8-into-pbo-bug.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ Unexpected WebGL error: 0x506 (1286) (thread WebGLThread, at components/canvas/webgl_thread.rs:883)
  │ stack backtrace:
  │    0:     0x7fd27940fbac - backtrace::backtrace::trace::h6b0af94f74672f08
  │    1:     0x7fd27940fbe2 - backtrace::capture::Backtrace::new::hbff890d685663b85
  │    2:     0x7fd2781a3752 - servo::main::{{closure}}::h2df85a5f78215329
  │    3:     0x7fd27a752fd5 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7fd27a752e5e - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7fd27a752d5a - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7fd2794d55b3 - canvas::webgl_thread::WebGLImpl::apply::h69dac2848d216ca3
  │    7:     0x7fd2794a3d22 - <canvas::webgl_thread::WebGLThread<VR, OB>>::handle_msg::h2017b137593ecf69
  │    8:     0x7fd27943c287 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd09c826cc86f70f9
  │    9:     0x7fd27943c4ef - std::panicking::try::do_call::h297297dd1b75e1f5
  │   10:     0x7fd27a76e4ce - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   11:     0x7fd27945592e - <F as alloc::boxed::FnBox<A>>::call_box::hcf2e0e9e98eec6c5
  │   12:     0x7fd27a74a62b - std::sys_common::thread::start_thread
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys::unix::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   13:     0x7fd27629e183 - start_thread
  │   14:     0x7fd275992ffc - clone
  │   15:                0x0 - <unknown>
  └ ERROR:servo: Unexpected WebGL error: 0x506 (1286)

  ▶ TIMEOUT [expected CRASH] /_mozilla/webgl/conformance-1.0.3/conformance/renderbuffers/framebuffer-object-attachment.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ DESCRIPTION: Test framebuffer object attachment behaviors
  │ PASS gl = wtu.create3DContext() is non-null.
```
…
```
  │ PASS getError was expected value: NO_ERROR :
  │ FAIL gl.checkFramebufferStatus(gl.FRAMEBUFFER) returned 36053
  │ Unexpected WebGL error: 0x506 (1286) (thread WebGLThread, at components/canvas/webgl_thread.rs:883)
  │ stack backtrace:
  │    0:     0x7f8d71ce1bac - backtrace::backtrace::trace::h6b0af94f74672f08
  │    1:     0x7f8d71ce1be2 - backtrace::capture::Backtrace::new::hbff890d685663b85
  │    2:     0x7f8d70a75752 - servo::main::{{closure}}::h2df85a5f78215329
  │    3:     0x7f8d73024fd5 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7f8d73024e5e - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7f8d73024d5a - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7f8d71da75b3 - canvas::webgl_thread::WebGLImpl::apply::h69dac2848d216ca3
  │    7:     0x7f8d71d75d22 - <canvas::webgl_thread::WebGLThread<VR, OB>>::handle_msg::h2017b137593ecf69
  │    8:     0x7f8d71d0e287 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd09c826cc86f70f9
  │    9:     0x7f8d71d0e4ef - std::panicking::try::do_call::h297297dd1b75e1f5
  │   10:     0x7f8d730404ce - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   11:     0x7f8d71d2792e - <F as alloc::boxed::FnBox<A>>::call_box::hcf2e0e9e98eec6c5
  │   12:     0x7f8d7301c62b - std::sys_common::thread::start_thread
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys::unix::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   13:     0x7f8d6eb70183 - start_thread
  │   14:     0x7f8d6e264ffc - clone
  │   15:                0x0 - <unknown>
  └ ERROR:servo: Unexpected WebGL error: 0x506 (1286)

  ▶ TIMEOUT [expected CRASH] /_mozilla/webgl/conformance-2.0.0/conformance2/renderbuffers/framebuffer-object-attachment.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ DESCRIPTION: Test framebuffer object attachment behaviors
  │ PASS gl = wtu.create3DContext(undefined, undefined, 2) is non-null.
```
…
```
  │ PASS getError was expected value: INVALID_FRAMEBUFFER_OPERATION : clear with incomplete framebuffer
  │ FAIL checkFramebufferStatus expects [FRAMEBUFFER_INCOMPLETE_ATTACHMENT], was FRAMEBUFFER_COMPLETE
  │ 
  │ Drawing or reading from an incomplete framebuffer should generate INVALID_FRAMEBUFFER_OPERATION
  │ PASS getError was expected value: NO_ERROR :
  │ Unexpected WebGL error: 0x506 (1286) (thread WebGLThread, at components/canvas/webgl_thread.rs:883)
  │ stack backtrace:
  │    0:     0x7f51e881ebac - backtrace::backtrace::trace::h6b0af94f74672f08
  │    1:     0x7f51e881ebe2 - backtrace::capture::Backtrace::new::hbff890d685663b85
  │    2:     0x7f51e75b2752 - servo::main::{{closure}}::h2df85a5f78215329
  │    3:     0x7f51e9b61fd5 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7f51e9b61e5e - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7f51e9b61d5a - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7f51e88e45b3 - canvas::webgl_thread::WebGLImpl::apply::h69dac2848d216ca3
  │    7:     0x7f51e88b2d22 - <canvas::webgl_thread::WebGLThread<VR, OB>>::handle_msg::h2017b137593ecf69
  │    8:     0x7f51e884b287 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd09c826cc86f70f9
  │    9:     0x7f51e884b4ef - std::panicking::try::do_call::h297297dd1b75e1f5
  │   10:     0x7f51e9b7d4ce - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   11:     0x7f51e886492e - <F as alloc::boxed::FnBox<A>>::call_box::hcf2e0e9e98eec6c5
  │   12:     0x7f51e9b5962b - std::sys_common::thread::start_thread
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys::unix::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   13:     0x7f51e56ad183 - start_thread
  │   14:     0x7f51e4da1ffc - clone
  │   15:                0x0 - <unknown>
  └ ERROR:servo: Unexpected WebGL error: 0x506 (1286)

  ▶ TIMEOUT [expected CRASH] /_mozilla/webgl/conformance-2.0.0/conformance2/reading/read-pixels-from-fbo-test.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ DESCRIPTION: Checks that ReadPixels from a fbo works as expected.
  │ 
  │ ReadPixels from fbo with texture = (R8, RED, UNSIGNED_BYTE), format = RGBA, type = UNSIGNED_BYTE
  │ FAIL getError expected: NO_ERROR. Was INVALID_ENUM : Setting up fbo should generate no error
  │ Unexpected WebGL error: 0x506 (1286) (thread WebGLThread, at components/canvas/webgl_thread.rs:883)
  │ PASS getError was expected value: NO_ERROR : Clear color should generate no error
  │ stack backtrace:
  │    0:     0x7f2d136d9bac - backtrace::backtrace::trace::h6b0af94f74672f08
  │    1:     0x7f2d136d9be2 - backtrace::capture::Backtrace::new::hbff890d685663b85
  │    2:     0x7f2d1246d752 - servo::main::{{closure}}::h2df85a5f78215329
  │    3:     0x7f2d14a1cfd5 - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7f2d14a1ce5e - std::panicking::begin_panic<alloc::string::String>
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7f2d14a1cd5a - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7f2d1379f5b3 - canvas::webgl_thread::WebGLImpl::apply::h69dac2848d216ca3
  │    7:     0x7f2d1376dd22 - <canvas::webgl_thread::WebGLThread<VR, OB>>::handle_msg::h2017b137593ecf69
  │    8:     0x7f2d13706287 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd09c826cc86f70f9
  │    9:     0x7f2d137064ef - std::panicking::try::do_call::h297297dd1b75e1f5
  │   10:     0x7f2d14a384ce - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   11:     0x7f2d1371f92e - <F as alloc::boxed::FnBox<A>>::call_box::hcf2e0e9e98eec6c5
  │   12:     0x7f2d14a1462b - std::sys_common::thread::start_thread
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys::unix::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   13:     0x7f2d10568183 - start_thread
  │   14:     0x7f2d0fc5cffc - clone
  │   15:                0x0 - <unknown>
  └ ERROR:servo: Unexpected WebGL error: 0x506 (1286)
```

</details>

**Comment by SimonSapin** [comment]
`etc/ci/check_no_panic.sh` also fails on Travis because I replaced some calls to `Result::expect` with an explicit `panic!()` in `components/constellation/constellation.rs`.

@jdm, since you filed https://github.com/servo/servo/issues/10446, what is the goal of this file? It greps for `unwrap(` and `panic!(`. If it we want to avoid any panic there is no end of false negative, beyond `Result::expect` there’s many API even in std that can panic. If we want to avoid `unwrap` specifically because it produces less helpful error messages than `expect`, why is `panic!` also excluded?

**Comment by jdm** [comment]
We had a lot of instances of unwrapping and panicking that were taking down the constellation thread unnecessarily. We addressed the problem in the most straightforward way by forbidding using those directly.

**Comment by SimonSapin** [comment]
@jdm What should we do in `Constellation::handle_request` when the other end of a channel is disconnected? Is `None.expect("…")` more acceptable than `panic!("…")`?

**Comment by jdm** [comment]
In this particular case, unreachable!() is probably allowed and the right choice. It should be impossible to hit the case where all receivers are disconnected.

**Comment by SimonSapin** [comment]
On of the blockers for landing this is adding support of "any disconnected" upstream and using it instead of "all disconnected".

**Comment by nox** [comment]
@jdm I'm confused as to why you would consider channel disconnection "unreachable". Clearly this is a case that the code must handle, isn't it?

**Comment by SimonSapin** [comment]
I assume @jdm meant that it is highly unlikely that multiple senders that are on different threads all become disconnected at the same time. But what’s more interesting is what any of them disconnects. That usually indicates that the other thread panicked, which shouldn’t happen but can when something is buggy. The current behavior is to "propagate" panics to the reciever thread, eventually bringing down the application instead of letting it hang.

**Comment by jdm** [comment]
The case I was referring to was when all receivers are disconnected from their senders. This can't happen because the constellation holds copies of some of the corresponding senders, so those will never be treated as disconnected.

**Comment by SimonSapin** [comment]
Besides tidy, a lot of WPT tests with file names in `*.any.worker.html` or `*-worker.html` are timing out.

**Comment by SimonSapin** [comment]
`tests/wpt/web-platform-tests/fetch/data-urls/base64.any.js`

```js
promise_test(() => fetch("resources/base64.json").then(res => res.json()).then(runBase64Tests), "Setup.");
function runBase64Tests(tests) {
  for(let i = 0; i < tests.length; i++) {
    const input = tests[i][0],
          output = tests[i][1],
          dataURL = "data:;base64," + input;
    promise_test(t => {
      if(output === null) {
        return promise_rejects(t, new TypeError(), fetch(dataURL));
      }
      return fetch(dataURL).then(res => res.arrayBuffer()).then(body => {
        assert_array_equals(new Uint8Array(body), output);
      });
    }, "data: URL base64 handling: " + format_value(input));
  }
}
```

In this test in this PR, it looks like the `fetch(…)` promise is never resolved when the test is running in a WebWorker. `script::fetch::Fetch` calls `ipc::channel()`, so maybe this is a bug in https://github.com/servo/ipc-channel/pull/183 that is not caught by `ipc-channel`’s unit tests?

**Comment by SimonSapin** [comment]
@jdm, isn’t @servo-wpt-sync being over-eager here? Shouldn’t we wait until a servo/servo PR is merged before upstreaming its WPT changes?

**Comment by jdm** [comment]
It's much easier to end up in a valid state if the changes are merged upstream immediately after they are merged locally.

**Comment by stjepang** [comment]
Any updates on this PR? What are the current blockers?

**Comment by SimonSapin** [comment]
@gterzian, in you wrote about this PR: https://github.com/rust-lang/rust/issues/27800#issuecomment-409493989
> Maybe there is something I can do to help fix those last remaining failing wpt tests...

I’m glad you asked ! :) If you’re interested in working on this one place to start might be:

```sh
# In your clone of the repository
git fetch https://github.com/servo/servo crossbeam-channel:crossbeam-channel
git checkout crossbeam-channel
./mach build ---dev
./mach test-wpt /fetch/data-urls/base64.any.worker.html --ssl-type none --no-pause-after-test
```

(The `--ssl-type` thing is just to avoid the very verbose output from OpenSSL generating a new certificate on every run.)

If you see some red in the output with `TIMEOUT /fetch/data-urls/base64.any.worker.html`, you’ve managed to reproduce the issue. Now, unfortunately we pretty much don’t have devtools for JS debugging, so you’re left with `console.log()` whose output should show up in your terminal. The source for the test being run is `tests/wpt/web-platform-tests/fetch/data-urls/base64.any.js`, an the test harness is at `tests/wpt/web-platform-tests/resources/testharness.js`. With `.worker` in the URL this test is being run in a WebWorker, so anything with `Remote` in its name in the test harness might be relevant. You can also remove `--no-pause-after-test` from the command to keep the web server running, for example to run `curl http://127.0.0.1:8000/fetch/data-urls/base64.any.worker.html` and see what data `test-wpt` is serving to Servo.

The only lead I have found so far is https://github.com/servo/servo/pull/19515#issuecomment-397437635, but I haven’t yet investigated it further.

I’m sorry I don’t have more leads to offer, this is very much a case of "we made a big change and now *something* is broken but we have no idea what and how". Figuring this out is not an easy task and it might turn out frustrating, but pushing this further would be very helpful. Feel free to ask an question here or in the `#servo` channel on Mozilla IRC. Thank you for (sort of) volunteering! :)

**Comment by gterzian** [comment]
@SimonSapin Thanks for the intro, I'll look into this...

**Comment by gterzian** [comment]
> /// This macro allows declaring a set of channel operations and blocking until any one of them
/// becomes ready. Finally, one of the operations is executed. If multiple operations are ready at
/// the same time, a random one is chosen. **It is also possible to declare a `default` case that
/// gets executed if none of the operations are initially ready**. (https://github.com/crossbeam-rs/crossbeam-channel/blob/master/src/internal/select.rs#L11)

The default case in the select in [dedicatedworkerglobalscope.rs](https://github.com/servo/servo/pull/21325/commits/cb3a52dc6fbb7c9832b79edc39691f2ed6b016b0#diff-c3210c2a1bf5e1de39588154cd766100L288) would actually return `None` immediately, which resulted in the run loop of the worker exiting in the first iteration...

`tests/wpt/web-platform-tests/fetch/data-urls/base64.any.js` is now passing on my machine.

I'm wondering if it's worth a try on bors while there seems to be some duplicate dependencies issues, I'm guessing because of the `ipc-channel` branch used? see https://travis-ci.org/servo/servo/jobs/411366483 

@SimonSapin Do you want to rebase off my branch at https://github.com/servo/servo/pull/21325 and squash my commit  while we wait for the `ipc-channel` stuff to merge and resolve those duplicate depenencies?

**Comment by gterzian** [comment]
@jdm I'll try the other branch

**Comment by SimonSapin** [comment]
Great catch @gterzian!

Closing in favor of https://github.com/servo/servo/pull/21325, to keep the discussion in one place.

**Pull request closed without merging**
