### PR TITLE
script: Remove HTMLAppletElement.

### PR DESCRIPTION
**Pull request by emilio**
It was removed from the spec, there's no reason to keep it in tree.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18657)

### CODE REVIEW

**Comment by emilio** [comment]
r? @nox 

@bors-servo try

 * I'm moderately sure this requires test expectation changes.

**Comment by KiChjang** [comment]
Needs a change in manifest, once that done you can r=me.

**Comment by mbrubeck** [comment]
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/collections.html:
  │ FAIL [expected PASS] test_binding\n    page  
  │   → HTMLAppletElement is not defined
```

**Comment by emilio** [comment]
@bors-servo r=KiChjang 


Forgot to update the manifest again.

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /html/dom/documents/dom-tree-accessors/nameditem-03.html:
  └ PASS [expected FAIL] applet elements are (mostly) gone

  ▶ Unexpected subtest result in /html/semantics/interfaces.html:
  └ PASS [expected FAIL] Interfaces for applet

  ▶ Unexpected subtest result in /html/semantics/interfaces.html:
  └ PASS [expected FAIL] Interfaces for APPLET
```

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /html/dom/reflection-obsolete.html:
  │ FAIL [expected PASS] applet.name: IDL get with DOM attribute unset
  │   → assert_equals: expected (string) "" but got (undefined) undefined
  │ 
  │ ReflectionTests.reflects/<@http://web-platform.test:8000/html/dom/reflection.js:641:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  │ test@http://web-platform.test:8000/resources/testharness.js:511:9
  │ ReflectionHarness.test@http://web-platform.test:8000/html/dom/new-harness.js:6:3
  │ ReflectionTests.reflects@http://web-platform.test:8000/html/dom/reflection.js:640:9
  └ @http://web-platform.test:8000/html/dom/reflection.js:908:9

  ▶ Unexpected subtest result in /html/dom/reflection-obsolete.html:
  │ FAIL [expected PASS] applet.name: setAttribute() to ""
  │   → assert_equals: IDL get expected (string) "" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to " \\0\\x01\\x02\\x03\\x04\\x05\\x06\\x07 \\b\\t\\n\\v\\f\\r\\x0e\\x0f \\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17 \\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f  foo "
  │   → assert_equals: IDL get expected (string) " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo " but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to undefined
  │   → assert_equals: IDL get expected (string) "undefined" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to 7
  │   → assert_equals: IDL get expected (string) "7" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to 1.5
  │   → assert_equals: IDL get expected (string) "1.5" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to true
  │   → assert_equals: IDL get expected (string) "true" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to false
  │   → assert_equals: IDL get expected (string) "false" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to object "[object Object]"
  │   → assert_equals: IDL get expected (string) "[object Object]" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to NaN
  │   → assert_equals: IDL get expected (string) "NaN" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to Infinity
  │   → assert_equals: IDL get expected (string) "Infinity" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to -Infinity
  │   → assert_equals: IDL get expected (string) "-Infinity" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to "\\0"
  │   → assert_equals: IDL get expected (string) "\0" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to null
  │   → assert_equals: IDL get expected (string) "null" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to object "test-toString"
  │   → assert_equals: IDL get expected (string) "test-toString" but got (undefined) undefined
  │ FAIL [expected PASS] applet.name: setAttribute() to object "test-valueOf"
  │   → assert_equals: IDL get expected (string) "test-valueOf" but got (undefined) undefined
  │ 
  │ ReflectionTests.reflects/<@http://web-platform.test:8000/html/dom/reflection.js:819:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  │ test@http://web-platform.test:8000/resources/testharness.js:511:9
  │ ReflectionHarness.test@http://web-platform.test:8000/html/dom/new-harness.js:6:3
  │ ReflectionTests.reflects@http://web-platform.test:8000/html/dom/reflection.js:815:9
  └ @http://web-platform.test:8000/html/dom/reflection.js:908:9

  ▶ Unexpected subtest result in /html/dom/reflection-obsolete.html:
  │ FAIL [expected PASS] applet.name: IDL set to ""
  │   → assert_equals: getAttribute() expected "" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to " \\0\\x01\\x02\\x03\\x04\\x05\\x06\\x07 \\b\\t\\n\\v\\f\\r\\x0e\\x0f \\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17 \\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f  foo "
  │   → assert_equals: getAttribute() expected " \0\x01\x02\x03\x04\x05\x06\x07 \b\t\n\v\f\r\x0e\x0f \x10\x11\x12\x13\x14\x15\x16\x17 \x18\x19\x1a\x1b\x1c\x1d\x1e\x1f  foo " but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to undefined
  │   → assert_equals: getAttribute() expected "undefined" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to 7
  │   → assert_equals: getAttribute() expected "7" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to 1.5
  │   → assert_equals: getAttribute() expected "1.5" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to true
  │   → assert_equals: getAttribute() expected "true" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to false
  │   → assert_equals: getAttribute() expected "false" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to object "[object Object]"
  │   → assert_equals: getAttribute() expected "[object Object]" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to NaN
  │   → assert_equals: getAttribute() expected "NaN" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to Infinity
  │   → assert_equals: getAttribute() expected "Infinity" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to -Infinity
  │   → assert_equals: getAttribute() expected "-Infinity" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to "\\0"
  │   → assert_equals: getAttribute() expected "\0" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to null
  │   → assert_equals: getAttribute() expected "null" but got "test-valueOf"
  │ FAIL [expected PASS] applet.name: IDL set to object "test-toString"
  │   → assert_equals: getAttribute() expected "test-toString" but got "test-valueOf"
  │ 
  │ ReflectionTests.reflects/<@http://web-platform.test:8000/html/dom/reflection.js:842:21
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  │ test@http://web-platform.test:8000/resources/testharness.js:511:9
  │ ReflectionHarness.test@http://web-platform.test:8000/html/dom/new-harness.js:6:3
  │ ReflectionTests.reflects@http://web-platform.test:8000/html/dom/reflection.js:825:9
  └ @http://web-platform.test:8000/html/dom/reflection.js:908:9

  ▶ Unexpected subtest result in /html/dom/reflection-obsolete.html:
  │ FAIL [expected PASS] applet.name: typeof IDL attribute
  │   → assert_equals: expected "string" but got "undefined"
  │ 
  │ ReflectionTests.reflects/<@http://web-platform.test:8000/html/dom/reflection.js:620:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  │ test@http://web-platform.test:8000/resources/testharness.js:511:9
  │ ReflectionHarness.test@http://web-platform.test:8000/html/dom/new-harness.js:6:3
  │ ReflectionTests.reflects@http://web-platform.test:8000/html/dom/reflection.js:619:5
  └ @http://web-platform.test:8000/html/dom/reflection.js:908:9

  ▶ Unexpected subtest result in /html/dom/reflection-obsolete.html:
  │ FAIL [expected PASS] applet.name: IDL set to object "test-valueOf"
  │   → assert_equals: IDL get expected (string) "test-valueOf" but got (object) object "test-valueOf"
  │ 
  │ ReflectionTests.reflects/<@http://web-platform.test:8000/html/dom/reflection.js:846:21
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  │ test@http://web-platform.test:8000/resources/testharness.js:511:9
  │ ReflectionHarness.test@http://web-platform.test:8000/html/dom/new-harness.js:6:3
  │ ReflectionTests.reflects@http://web-platform.test:8000/html/dom/reflection.js:825:9
  └ @http://web-platform.test:8000/html/dom/reflection.js:908:9
```

**Comment by emilio** [comment]
So, a couple of those are defined in `HTMLElement` in Gecko. Should I just update the expectations for now @jdm?

**Comment by emilio** [comment]
Err, `applet.name` also fails in Gecko, I lie...

**Pull request merged**
