### PR TITLE
Update WR (text optimizations, Linux subpixel positioning / rasterization).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18002)

### CODE REVIEW

**Comment by glennw** [comment]
I've rebased this, and added the new transaction and debug API changes to the commit.

It can't land until https://github.com/servo/webrender/pull/1557 arrives in WR, but that should just be a hash change in Cargo.lock, so this is ready for re-review.

**Review by emilio — APPROVED** [review]
Looks fine once the WR update lands.

**Comment by emilio** [comment]
Err, once the hash changes, I mean.

**Comment by glennw** [comment]
Updated git hash only.

@bors-servo r=emilio

**Pull request merged**
