### PR TITLE
clippy: fix warnings in various modules in components

### PR DESCRIPTION
**Pull request by eerii**
Split from #31514, fixes multiple small clippy warnings in multiple modules from `components`:

- `allocator`
- `background_hang_monitor`
- `dom_struct`
- `domobject_derive`
- `hyper_serde`
- `layout`
- `media`
- `pixels`
- `profile`
- `range`
- `remutex`
- `url`

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes are part of #31500
- [x] These changes do not require tests because they do not modify functionality, they only fix lint errors.

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
Looks like this introduced a build error:

```
error[E0599]: no function or associated item named `new` found for struct `sampler::DummySampler` in the current scope
   --> components/background_hang_monitor/background_hang_monitor.rs:107:53
    |
107 |         let sampler = crate::sampler::DummySampler::new();
    |                                                     ^^^ function or associated item not found in `DummySampler`
    |
   ::: components/background_hang_monitor/sampler.rs:16:1
    |
16  | pub struct DummySampler;
    | ----------------------- function or associated item `new` not found for this struct
    |
```

**Comment by sagudev** [comment]
> Looks like this introduced a build error:
> 
> ```
> error[E0599]: no function or associated item named `new` found for struct `sampler::DummySampler` in the current scope
>    --> components/background_hang_monitor/background_hang_monitor.rs:107:53
>     |
> 107 |         let sampler = crate::sampler::DummySampler::new();
>     |                                                     ^^^ function or associated item not found in `DummySampler`
>     |
>    ::: components/background_hang_monitor/sampler.rs:16:1
>     |
> 16  | pub struct DummySampler;
>     | ----------------------- function or associated item `new` not found for this struct
>     |
> ```

Clippy might neede to be run with `--all-features` and maybe even `--all-features`

**Comment by eerii** [comment]
Yes, I missed the ones from other targets since they didn't show up when I built. I used the search now so there shouldn't be any more to change. Sorry about that!

**Comment by eerii** [comment]
I am so sorry about that, I thought it was one of the ones that changed to default, but in this case the warning was saying that `new` usually returns `Self`, and this returns a `Box`, that's why I changed it to `new_boxed`. I missed that on the last commit so it failed again as `default` was not defined. Now all samplers (including the Windows and MacOS ones that I previously didn't see because of the clippy target) should be using `new_boxed` and the error should be gone. Sorry :(

**Comment by mrobinson** [comment]
> I am so sorry about that, I thought it was one of the ones that changed to default, but in this case the warning was saying that `new` usually returns `Self`, and this returns a `Box`, that's why I changed it to `new_boxed`. I missed that on the last commit so it failed again as `default` was not defined. Now all samplers (including the Windows and MacOS ones that I previously didn't see because of the clippy target) should be using `new_boxed` and the error should be gone. Sorry :(

No worries. Thanks for the fix!

**Pull request merged**
