### PR TITLE
Add new Servo Logo

### PR DESCRIPTION
**Pull request by malqinneh**
* Added servo-64.png (replacing servo64.png @ 64px)
* Added servo-100.png (replacing doge-tiny.png @ 100px)
* Added servo-500.png
* Added servo-500-icon.ico
* Added servo-1000.png (replacing servo.png @ 1000px)
* Added servo.svg (replacing servo.svg)

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they add new logo assets

### CODE REVIEW

**Comment by paulrouget** [comment]
Can you also update support/android/apk/servoapp/src/main/res/mipmap/servo.png ?

**Comment by malqinneh** [comment]
> Can you also update support/android/apk/servoapp/src/main/res/mipmap/servo.png ?

Absolutely ✅

**Comment by paulrouget** [comment]
@jdm do we want to land that now?

**Comment by jdm** [comment]
@bors-servo r+
Thanks @malqinneh!

**Comment by jdm** [comment]
```
> /repo/support/android/apk/servoapp/src/main/res/mipmap/servo-1024.png: Error: '-' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```

**Comment by malqinneh** [comment]
> ```
> > /repo/support/android/apk/servoapp/src/main/res/mipmap/servo-1024.png: Error: '-' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
> ```

Is this a matter of replacing `-` (dash) with `_` (underscore)?

**Comment by jdm** [comment]
I expect that would work, but we should really overwrite the existing servo.png instead so that the new image gets used automatically.

**Comment by malqinneh** [comment]
> I expect that would work, but we should really overwrite the existing servo.png instead so that the new image gets used automatically.

Makes sense but tried to avoid overwriting original PNG file(s) to keep them safe/available in case they are needed in the future. I suppose one can always go back in commit history for them.

**Comment by atouchet** [comment]
This doesn't appear to have updated the logo on Windows. Servo.ico, servo.png, and servo64.png are still using the old logo.

**Comment by malqinneh** [comment]
> This doesn't appear to have updated the logo on Windows. Servo.ico, servo.png, and servo64.png are still using the old logo.

Probably due to file name(s). In order for the new assets to simply replace the old ones, they need to have the same name as the old assets. Alternatively, we can update the line of code that references old asset names to the new names.

**Comment by atouchet** [comment]
@malqinneh I'm not sure what the best approach would be but I took a quick look and it appears the relevant references are here:

https://github.com/servo/servo/blob/a9f7b132303f7c02648043df5ebdc25726bd3f88/ports/glutin/build.rs#L15

https://github.com/servo/servo/blob/8f3622af35a391b1d15ec1768aa90721ebc5396e/python/servo/build_commands.py#L722

https://github.com/servo/servo/blob/e07f0280fe9c16fbdeb34d488e00e8101f28fc9e/ports/glutin/headed_window.rs#L149

**Comment by malqinneh** [comment]
@atouchet happy to update those items. I need to create a new fork of the Servo branch since the last one I started was merged, is that correct?

**Comment by atouchet** [comment]
That should work. Taking another look at the files in /resources I suspect that servo.icns may be another file that needs updating but it appears to be an Apple image format and I don't have a Mac.

**Comment by malqinneh** [comment]
@atouchet created a [new pull request](https://github.com/servo/servo/pull/25846). Let me know if we missed anything. Thank you very much for your help and patience 👍

**Comment by atouchet** [comment]
Thanks! I will take a look at the PR.

**Pull request merged**
