### PR TITLE
Move rust-selectors into servo/servo

### PR DESCRIPTION
**Pull request by bholley**
See the thread at [1].

[1] https://groups.google.com/d/msg/mozilla.dev.servo/iHykieVC5SM/Z31_n0agBAAJ

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15447)

### CODE REVIEW

**Comment by bholley** [comment]
CC @Manishearth @emilio @metajack

**Comment by SimonSapin** [comment]
Let’s discuss on your mailing list thread first.

**Comment by nox** [comment]
If we ever do this (which I hope we don't), the two commits need to be squashed together.

**Comment by bholley** [comment]
> If we ever do this (which I hope we don't), the two commits need to be squashed together.

Can you explain why? I wanted to do a clean import of the existing code from the rust-selectors git repository, and then make any source modifications afterwards. It seems like there's a lot of value in having those be separate commits, but I need to land them together to pass tidy.

**Comment by nox** [comment]
It's just tidy so I guess it's not important, but not squashing means there is a commit that doesn't pass CI.

**Comment by bholley** [comment]
I'm happy to do whatever you guys want here. Another option would be for me to PR the tidy change to the rust-selectors git repo, which would let us have our cake and eat it too.

**Comment by SimonSapin** [comment]
Having intermediate commits pass CI is useful in case we want to use `git bisect`, but I don’t think that’s important for tidy. (You’d generally bisect a single test case.)

**Pull request merged**
