### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Eijebong**
Those are all easy and unrelated dependency updates, hence the single PR

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22221)

### CODE REVIEW

**Comment by Eijebong** [comment]
Mhhh I guess the openssl changes are to blame here

**Comment by Eijebong** [comment]
Actually... It passed on linux-wpt.

@bors-servo retry

**Review by emilio — APPROVED** [review]
r=me, assuming try is happy

**Comment by Eijebong** [comment]
Ok, this isn't intermittent but only happens on mac. I'll have a look tomorrow

**Comment by atouchet** [comment]
hyper 0.12.16 is now out.

**Comment by CYBAI** [comment]
@bors-servo retry

```
{"status": "FAIL", "group": "default", "message": "/_mozilla/css/inline_block_parent_padding_a.html 495641fc705b6af91aa9ff0d3235cd2c5342179c\n/_mozilla/css/inline_block_parent_padding_ref.html 4e6ec2a4e7504e5c4bb739eb4fad793251d3180f\nTesting 495641fc705b6af91aa9ff0d3235cd2c5342179c == 4e6ec2a4e7504e5c4bb739eb4fad793251d3180f", "stack": null, "subtest": null, "test": "/_mozilla/css/inline_block_parent_padding_a.html", "line": 31791, "action": "test_result", "expected": "PASS"}
```

**Comment by jdm** [comment]
That failure was #22062 for the record.

**Comment by jdm** [comment]
@bors-servo retry
* #22279

**Pull request merged**
