### PR TITLE
Tool that reads in WPT test output and logs it to a JSON file.

### PR DESCRIPTION
**Pull request by AgostonSzepessy**
This is for issue #7481. wpt_test_reader.py reads in WPT test results and outputs them to a JSON file. Usage:

`./mach test-wpt | python/wpt_test_reader.py --logfile=filename.json`

If I left out some tests please let me know and I'll include them.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10504)

### CODE REVIEW

**Comment by aneeshusa** [comment]
FYI, there is [an open PR](https://github.com/servo/saltfs/pull/310) from @jgraham to add support for `errorsummary` logs to our CI, which according to https://github.com/servo/servo/issues/10129 are already structured, shorter than the full logs, and should contain all the unexpected results. If the goal is to use this for reporting failures via Highfive, it may be a better idea to wait for that PR to land and use those logs directly.

**Comment by Wafflespeanut** [comment]
I'm not sure whether this should live in servo. The entire goal of this tool is to add log-reading support to highfive (cc @jdm)

**Comment by jdm** [comment]
Sorry for letting this sit around. There have been other developments that should make this easier; I think this is what we should do now:
* modify this script to process the output of the wpt_errorsummary.log file instead (eg. http://build.servo.org/builders/linux-rel/builds/463/steps/shell_1/logs/wpt_errorsummary.log), since it's well-formed, structured output
* merge the script into this repository in etc/ci
* add support to [highfive](https://github.com/servo/highfive) to fetch the log, fetch the python script from servo/servo/etc/ci/whatever.py, and use that to parse the log and attach the results

Does that make sense?

**Comment by aneeshusa** [comment]
Why not just have highfive do all the log parsing? I don't see the point of having the script live in this repo when we're going to need another script in highfive anyways.

**Comment by jgraham** [comment]
The general approach of using the error summary seems sensible to me.

**Comment by jdm** [comment]
Yeah, maybe it would be better for it to live entirely in highfive until there's a clear need for the script to exist in this repository too.

**Pull request closed without merging**
