### PR TITLE
Create pattern from HTMLCanvasElement or CanvasRenderingContext2D.

### PR DESCRIPTION
**Pull request by hyowon**
r? @nox @pcwalton 
cc @yichoi

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6410)

### CODE REVIEW

**Comment by pcwalton** [comment]
@bors-servo: r+

Thanks!

**Comment by hyowon** [comment]
@pcwalton Failed viewport_percentage_vw_vh.html which seems unrelated to this patch. Please retry?

**Comment by jdm** [comment]
Yes, the failed test is tracked in #6252.

**Comment by hyowon** [comment]
Rebase has been done.

**Comment by Ms2ger** [comment]
Could you change the `&&HTMLCanvasElement` to `&HTMLCanvasElement`?

**Comment by hyowon** [comment]
@Ms2ger Sure. Done.

**Pull request merged**
