### PR TITLE
Servo changes for bug 1383756

### PR DESCRIPTION
**Pull request by ehsan**
These changes are needed for https://bugzilla.mozilla.org/show_bug.cgi?id=1383756.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17842)

### CODE REVIEW

**Comment by bholley** [comment]
(When you're ready for this to land, type at-bors-servo r-equals-bholley)

**Comment by KiChjang** [comment]
How did this manage to get merged without any automated testing?

**Comment by emilio** [comment]
@KiChjang, https://github.com/servo/servo/pull/17844

**Comment by ehsan** [comment]
> How did this manage to get merged without any automated testing?

Apologies if I did something differently than what I should have done.  @emilio was helping me land this on IRC and this was the first time I had to do a split gecko/servo landing like this, and admittedly I don't quite understand what happened, but I think this landed with a very different process than the usual one.

**Pull request merged**
