### PR TITLE
Remove servo_url dependency for geckolib

### PR DESCRIPTION
**Pull request by upsuper**
It seems mod attr is not used for geckolib at all, and that is the only place where servo_url is still referenced for geckolib, so we can just remove it.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16297)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Could you also remove the `servo` feature in the `servo_url` crate, and make the corresponding things non-optional? Thanks.

**Comment by upsuper** [comment]
ok, and also I found that `servo_config` still depends on `servo_url` so there is a bit more work to do.

**Comment by SimonSapin** [comment]
Looks great, thanks!

@bors-servo r+

---

Reviewed 3 of 3 files at r1, 6 of 6 files at r2, 10 of 10 files at r3, 11 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16297#-:-Kh6kzCTYZ1-siLWUjjU:b-luwr89)*

**Pull request merged**
