### PR TITLE
Launch UWP app from command line

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

This PR makes it possible to launch the UWP app from the command line by executing (on any path) the `Servo` command. It requires building and launching Servo once on VS, so the command alias is properly registered.

It also allows passing command line arguments. So we can do for example `Servo --pref dom.webxr.enabled`.

Debugging is also possible when launching the app from the command line. It requires setting the `Launch Application` option (right click on `ServoApp (Universal Windows`) on the Solution Explorer view -> Properties ->  Configuration Properties -> Debugging) to `No`.

### CODE REVIEW

**Comment by paulrouget** [comment]
Aren't we gonna lose the `dom.webxr.enabled` pref when deploying from VS?

**Comment by ferjm** [comment]
Yes. I just fixed it with the last commit.

**Comment by paulrouget** [comment]
Works well :) Thank you.

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Pull request merged**
