### PR TITLE
Implemented Location.assign

### LINKED ISSUE #4841: Implement Location.assign
Spec: https://html.spec.whatwg.org/multipage/browsers.html#the-location-interface
Code: components/script/dom/location.rs

This can use the Window::load_url method.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #4841

### CODE REVIEW

**Comment by jdm** [comment]
Hmm, Critic's broken right now, but could you replace the link with https://html.spec.whatwg.org/multipage/browsers.html#dom-location-assign instead?

**Comment by KiChjang** [comment]
Done and squashed.

**Comment by KiChjang** [comment]
Okay, I removed the relevant expected test failures in the `html/dom/interfaces.ini` file and squashed the commits.

**Comment by jdm** [comment]
Thanks :)

**Pull request merged**
