### PR TITLE
Prevent use of reserved names in BindAttribLocation

### PR DESCRIPTION
**Pull request by dzbarsky**
(Depend on the WebGL tests landing)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10652)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo: delegate+

Good catch!

**Comment by jdm** [comment]
```
  ▶ OK [expected CRASH] /webgl/conformance-1.0.3/conformance/more/conformance/quickCheckAPI-G_I.html

  ▶ Unexpected subtest result in /webgl/conformance-1.0.3/conformance/more/conformance/quickCheckAPI-G_I.html:
  │ FAIL [expected PASS] WebGL test #0: testValidArgs
  │   → assert_true: testValidArgs expected true got false
  │ 
  │ reportTestResultsToHarness/<@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/more/unit.js:900:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ reportTestResultsToHarness@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/more/unit.js:899:1
  │ runTests@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/more/unit.js:188:5
  │ initTests@http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/more/unit.js:922:5
  └ @http://web-platform.test:8000/webgl/conformance-1.0.3/conformance/more/unit.js:947:7
```

**Pull request merged**
