### PR TITLE
rustup to 2016-07-11

### PR DESCRIPTION
**Pull request by eddyb**
Updates the Rust version to 2016-07-11 which is capable of compiling Servo with `-Zorbit`.

The two instances of `#[serde(bound = "")]` are necessary because serde starting being overzealous with bounds recently and Rust doesn't support cyclic bounds (they used to enable a huge soundness hole).
They could be removed after serde-rs/serde#436 is resolved, so you might want to block this PR on that or somehow track that issue to remove these attributes then.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] These changes do not require tests because they're a rust upgrade

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12393)

### CODE REVIEW

**Comment by eddyb** [comment]
[Lots of linker errors](http://build.servo.org/builders/windows/builds/1717/steps/compile/logs/stdio) - maybe @michaelwoerister knows something? I believe his PR with significant changes to trans monomorphization and symbol exports has landed recently.

**Comment by michaelwoerister** [comment]
Looking into it...

**Comment by michaelwoerister** [comment]
I cannot reproduce this on Linux.

**Comment by michaelwoerister** [comment]
So, this turns out to be a [known problem](https://github.com/rust-lang/rust/pull/33890#issuecomment-226259769) with the mingw toolchain. `libscript.rlib` contains so many closures that the number of resulting sections in the output object file exceeds 2^15, leading to invalid section indices for some symbols, which are then shown by mingw's `ld` as undefined references.

I'll look into fixing this.

**Comment by nox** [comment]
Superseded by #12586.

**Pull request closed without merging**
