### PR TITLE
Revert several changes that broke tests

### PR DESCRIPTION
**Pull request by mbrubeck**
This is based on #15158 by @aneeshusa, with additional reverts.

This reverts #15064, which is causing many tests not to run, and #15129 and #15155 which landed while tests were not running and may have caused some new failures in iframe tests.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15164)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Looks like we will need to revert #15136 as well for causing #15161 in tests: http://build.servo.org/builders/mac-rel-wpt2/builds/2058/steps/test/logs/stdio

CC @nox

**Comment by emilio** [comment]
@bors-servo retry

 * /css21_dev/html4/bidi-008b.htm, seems intermittent, will file now

**Comment by SimonSapin** [comment]
```
  ▶ CRASH [expected OK] /encoding/textdecoder-labels.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }"
  │ stack backtrace:
  │    0:     0x7f5ed17959ad - backtrace::backtrace::trace::h3daaf829744ddab9
  │    1:     0x7f5ed17960a2 - backtrace::capture::Backtrace::new::hd6fb6e83f9059b0d
  │    2:     0x7f5ecff7b1e4 - servo::install_crash_handler::handler::hb60740328a53f0c4
  │    3:     0x7f5ed11c38e3 - AsmJSFaultHandler
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7cd72d8/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
  │    4:     0x7f5ecde5132f - <unknown>
  │    5:     0x7f5ecfbbfffd - <unknown>
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }"
  │ stack backtrace:
  │    0:     0x7f5ed17959ad - backtrace::backtrace::trace::h3daaf829744ddab9
  │    1:     0x7f5ed17960a2 - backtrace::capture::Backtrace::new::hd6fb6e83f9059b0d
  │    2:     0x7f5ecff7b1e4 - servo::install_crash_handler::handler::hb60740328a53f0c4
  │    3:     0x7f5ecd89ccaf - <unknown>
  │    4:     0x7f5ecff7b26f - servo::install_crash_handler::handler::hb60740328a53f0c4
  │    5:     0x7f5ed11c38e3 - AsmJSFaultHandler
  │                         at /home/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/7cd72d8/mozjs/js/src/asmjs/WasmSignalHandlers.cpp:1171
  │    6:     0x7f5ecde5132f - <unknown>
  └    7:     0x7f5ecfbbfffd - <unknown>

**Comment by jdm** [comment]
@bors-servo: retry
* #15161

**Pull request merged**
