### PR TITLE
style: Make PercentageOrNumber also reject negative percentages.

### PR DESCRIPTION
**Pull request by emilio**
It always returns true, so this is just stupid.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16142)

### CODE REVIEW

**Comment by emilio** [comment]
This seems to come from da27b613521, so r? @canaltinova

**Comment by emilio** [comment]
Actually, `ImageRect` needs to reject negative percentages, this was causing a non-fatal assertion on one bug I was working on, so let me just fix that.

**Comment by canaltinova** [comment]
Thanks!
@bors-servo r+

**Comment by upsuper** [comment]
This seems to fix #15339.

**Pull request merged**
