### PR TITLE
Remove warning

### PR DESCRIPTION
**Pull request by thiagopnts**
Remove warning from unused import

### CODE REVIEW

**Comment by glennw** [comment]
@thiagopnts That import is required on Linux but not other platforms.

**Comment by Manishearth** [comment]
You can make it a separate import with `#[cfg(not(target_os = "linux"))]` to kill the warning.

**Comment by thiagopnts** [comment]
@glennw @Manishearth I added the import on the function body!

**Comment by glennw** [comment]
Thanks! Can you squash these into one commit and then I'll merge it :)

**Comment by thiagopnts** [comment]
@glennw Done!

**Pull request merged**
