### PR TITLE
Fix canvas wpt test ensuring there's a subpath when drawing bezier curves

### PR DESCRIPTION
**Pull request by pylbrecht**
These changes will ensure there's a subpath when drawing bezier curves.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #25331 

- [x] There are tests for these changes

### CODE REVIEW

**Comment by pylbrecht** [comment]
?r jdm

**Comment by pylbrecht** [comment]
r? jdm

**Comment by jdm** [comment]
```
  ▶ PASS [expected FAIL] /2dcontext/building-paths/canvas_complexshapes_beziercurveto_001.htm
```

**Pull request merged**
