### PR TITLE
Properly set the origin on websocket messages

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21430)

### CODE REVIEW

**Comment by Eijebong** [comment]
I'm not sure about this one. Is there a better way to get the origin ?

**Comment by jdm** [comment]
I would add an origin argument to dispatch_jsval instead of dynamically checking the target.

**Comment by Eijebong** [comment]
```

{"action": "test_groups", "line": 4, "groups": ["default"]}
{"status": "TIMEOUT", "group": "default", "line": 1011, "subtest": null, "action": "test_result", "test": "/eventsource/eventsource-constructor-stringify.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1012, "subtest": null, "action": "test_result", "test": "/eventsource/dedicated-worker/eventsource-eventtarget.worker.html", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1013, "subtest": null, "action": "test_result", "test": "/eventsource/eventsource-constructor-url-bogus.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1016, "subtest": null, "action": "test_result", "test": "/eventsource/dedicated-worker/eventsource-prototype.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1021, "subtest": null, "action": "test_result", "test": "/eventsource/dedicated-worker/eventsource-close.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1022, "subtest": null, "action": "test_result", "test": "/eventsource/dedicated-worker/eventsource-close2.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1023, "subtest": null, "action": "test_result", "test": "/eventsource/dedicated-worker/eventsource-constructor-url-bogus.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1041, "subtest": null, "action": "test_result", "test": "/eventsource/eventsource-onopen.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1044, "subtest": null, "action": "test_result", "test": "/eventsource/eventsource-eventtarget.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1045, "subtest": null, "action": "test_result", "test": "/eventsource/eventsource-constructor-url-multi-window.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1288, "subtest": null, "action": "test_result", "test": "/eventsource/dedicated-worker/eventsource-constructor-non-same-origin.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 1291, "subtest": null, "action": "test_result", "test": "/eventsource/eventsource-constructor-non-same-origin.htm", "message": null, "stack": null, "expected": "OK"}
```
Wut ?

**Comment by jdm** [comment]
@bors-servo: retry
* every test panicked with OOM

**Pull request merged**
