### PR TITLE
Replacing C libraries with Rust equivalents - student project

### PR DESCRIPTION
**Pull request by ankit3005**
We are a group of students at NCSU.
As part of a Mozilla student [project](https://github.com/servo/servo/wiki/Replace-C-libraries-student-project#evaluate-replacing-c-libraries-with-modern-rust-equivalents) we have replaced the use of [rust-freetype](https://github.com/servo/rust-freetype) and [rust-stb-image](https://github.com/servo/rust-stb-image)  libraries in servo with [freetype-rs](https://github.com/PistonDevelopers/freetype-rs) and [image](https://github.com/PistonDevelopers/image) respectively.

The changes are described in more detail at  http://wiki.expertiza.ncsu.edu/index.php/CSC/ECE_517_Fall_2014/final_M1455_yaaa

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/4215)

### CODE REVIEW

**Comment by jdm** [comment]
Any update here?

**Comment by kmcallister** [comment]
I'll work on merging this.

**Comment by kmcallister** [comment]
I have [a branch](https://github.com/kmcallister/servo/commits/piston-image) that contains a rebased version of the image-related changes, with style fixes and some other improvements. It's untested at the moment because I couldn't easily find a version of Piston's image library that builds with Servo's rustc.

**Comment by kmcallister** [comment]
It's now building and passing most but not all tests.

**Comment by kmcallister** [comment]
Blocked on PistonDevelopers/image#199 for Acid2.

**Comment by kmcallister** [comment]
That's fixed now, but we'll probably need a rustup before we can use a new enough version of the image library.

**Comment by kmcallister** [comment]
Note that `freetype_rs::ffi` is a re-export of `freetype_sys`. It's still a valuable change, but we should switch to the high-level bindings eventually.

**Comment by jdm** [comment]
@kmcallister Upgrade accomplished, so we should be safe to switch to the new image library now.

**Comment by kmcallister** [comment]
Yep, working on it right now :)

**Comment by waddlesplash** [comment]
@kmcallister Should this be closed as invalid/moved elsewhere, then?

**Comment by jdm** [comment]
Yep.

**Pull request closed without merging**
