### PR TITLE
Add content_type to metadata in file_loader

### LINKED ISSUE #4212: Servo should create a headers object in file_loader
Follow on issue to #3144 

Currently when a file from the filesystem is loaded in servo, no response headers are generated. This prevents testing via XMLHttpRequest.

For reference:
http://pastebin.com/k3kyci7m

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #4212.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8609)

### CODE REVIEW

**Comment by Ms2ger** [comment]
r? @jdm 

(Looks like the new dep is MIT-licensed.)

**Comment by frewsxcv** [comment]
You need to update the gonk lockfile

**Comment by jdm** [comment]
@bors-servo: delegate+
This is fine to merge when the lockfiles are updated.

**Comment by jdm** [comment]
Looks like the CEF lockfile is still not updated. It should be enough to do `./mach cargo-update -p net`.

**Pull request merged**
