### PR TITLE
Add Dimension member to AttrValue

### LINKED ISSUE #8417: Add Dimension member to AttrValue, and fix related attribute parsing
Misc places call `str::parse_length` on the value of an attribute; we should store the parsed result in Attr.

Relevant properties: https://html.spec.whatwg.org/multipage/#dimRendering , and everything else in the rendering section marked "maps to the dimension property" or "maps to the dimension property (ignoring zero)".  Probably everything needs to be reviewed so it actually matches the spec; for example, we currently parse `width` and `height` on `` as an integer, which is wrong.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes #8417

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8434)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Forgot to add a file, one sec

**Comment by frewsxcv** [comment]
Okay, should be reviewable now. r? @eefriedman

**Comment by eefriedman** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/script/dom/attr.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8434#-K2iabPrKXCsA8bpDaFA)** ([raw file](https://github.com/servo/servo/blob/5ea9bb9f4def840ca49d9fa82a1527d8c9b285ce/components/script/dom/attr.rs#L87)):</sup>
If you want to match the names of the rest of these methods, this would be "from_dimension".

Also, I guess this should actually be "from_nonzero_dimension" for parsing the width of a table, but I guess you're planning to leave that for another patch, since it would be a functional change?

Looks fine otherwise.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8434)

**Comment by frewsxcv** [comment]
Comments have been addressed

**Pull request merged**
