### PR TITLE
Port to the new cssparser.

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/servo/rust-cssparser/pull/68

r? @larsbergstrom

### CODE REVIEW

**Comment by pcwalton** [comment]
@larsbergstrom How would you like to split this up?

**Comment by larsbergstrom** [comment]
@pcwalton I was just going to review it since you are on PTO today and am happy to either let you review it or divide it up however you would like.

**Comment by SimonSapin** [comment]
I just realized I forgot to write any docs. Sorry!

I’ll write more down tomorrow. In the meantime, the main important point is the convention for parsing functions:

* Take (at least) a `input: &mut cssparser::Parser` parameter
* Return `Result<_, ()>`
* When returning `Ok(_)`, the function must have consume exactly the amount of input that represents the parsed value.
* When returning `Err(())`, any amount of input may have been consumed.

As a consequence, when calling another parsing function, either:
* Any `Err(())` return value must be propagated. This happens by definition for tail calls, and can otherwise be done with the `try!` macro.
* Or the call must be wrapped in a [`cssparser::Parser::try`](https://github.com/servo/rust-cssparser/blob/83b7cc8392d095aaacbe051841b81d86630bb0eb/src/parser.rs#L190) call. `try` takes a closure that takes a `Parser` and returns a `Result`, calls it once, and returns itself that same result. If the result is `Err`, it restores the position inside the input to the one saved before calling the closure.

Examples:

```rust
fn parse_background_image(context: &ParserContext, input: &mut Parser) 
                                    -> Result<Option<Image>, ()> {
    if input.try(|input| input.expect_ident_matching("none")).is_ok() {
        Ok(None)
    } else {
        Image::parse(context, input).map(Some)  // tail call
    }
}
```

```rust
fn parse_border_spacing(_context: &ParserContext, input: &mut Parser) 
                          -> Result<(LengthOrPercentage, LengthOrPercentage), ()> {
    let first = try!(LengthOrPercentage::parse);
    let second = input.try(LengthOrPercentage::parse).unwrap_or(first);
    (first, second)
}
```

**Comment by larsbergstrom** [comment]
@pcwalton I've reviewed everything but value.rs, if you could take a look at that when you have a chance!

**Pull request merged**
