### PR TITLE
Updated CONTRIBUTING file

### PR DESCRIPTION
**Pull request by asajeffrey**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it's documentation

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’ve cancelled this retry in order to start it again in a few minutes after some of the tasks in https://community-tc.services.mozilla.com/tasks/groups/G-vrow3rTSGesX7OHv8LVw have finished, so they can be re-used.

**Comment by CYBAI** [comment]
@bors-servo retry

- Other tasks are all completed, let's retry now!

**Pull request merged**
