### PR TITLE
Update HTMLFormElement.length to be of type unsigned long

### LINKED ISSUE #9402: Update HTMLFormElement.length to be of type unsigned long
whatwg/html#510 has changed the type of the `length` attribute in `HTMLFormElement` from `long` to `unsigned long`. We should reflect this change in our code as well.

Code: `components/script/dom/htmlformelement.rs`, `components/script/dom/webidls/HTMLFormElement.webidl`
Spec: https://html.spec.whatwg.org/multipage/forms.html#the-form-element:dom-form-elements

### PR DESCRIPTION
**Pull request by shssoichiro**
Fixes #9402

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9404)

### CODE REVIEW

**Comment by nox** [comment]
Could you also fix the interface in `tests/wpt/web-platform-tests/html/dom/interfaces.html`? Thank you.

**Comment by nox** [comment]
Please squash everything in one commit and I'll r+ it.

**Comment by shssoichiro** [comment]
Squashed commit is up

**Comment by nox** [comment]
Perfect, thanks.

@bors-servo r+

**Pull request merged**
