### PR TITLE
Enable more DOM preferences for unofficial WPT test runs

### PR DESCRIPTION
**Pull request by jdm**
These preferences were enabled for layout 2013 test runs, but weren't migrated to layout 2020 test runs.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes are part of #34111 and #34112.
- [x] These changes do not require tests because they are testing-only.

### CODE REVIEW

**Comment by nicoburns** [comment]
Is there a reason that these are only enabled for WPT runs, and not just enabled in general? I figure that the features probably aren't complete, but that applies to pretty much all of Servo!

**Comment by jdm** [comment]
Personally, my background working in browsers makes me hesitant to turn on APIs by default that have known holes in them. It's possible we should have z wider discussion about norms here!

**Review by sagudev — APPROVED** [review]

**Comment by sagudev** [comment]
@jdm did you copy expectations from legacy-layout or create new ones?

**Comment by jdm** [comment]
I created new ones.

**Comment by sagudev** [comment]
Maybe copying would result less flakes?

**Comment by sagudev** [comment]
OffScreen canvas and ImageBitmap expectations should be independent of layout, no? And legacy-layout expectations are still somewhat updated in the WPT imports.

**Comment by jdm** [comment]
The WPT imports update the expectations based on running the tests, but the merge is not gated on running the tests again and receiving identical results.

**Comment by sagudev** [comment]
> The WPT imports update the expectations based on running the tests, but the merge is not gated on running the tests again and receiving identical results.

Oh.

**Comment by mrobinson** [comment]
> The WPT imports update the expectations based on running the tests, but the merge is not gated on running the tests again and receiving identical results.

This is definitely the case, but only for Layout 2013. Tests will definitely be run again once the import PR is sent to the MQ for Layout 2020.

**Pull request merged**
