### PR TITLE
stylo: regenerate bindings

### PR DESCRIPTION
**Pull request by bholley**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12803)

### CODE REVIEW

**Comment by bholley** [comment]
Filed https://github.com/servo/rust-bindgen/issues/28 on the bindgen issue.

@bors-servo r=emilio

**Comment by bholley** [comment]
@bors-servo p=1

This blocks updating the stylo branch.

**Comment by larsbergstrom** [comment]
Had to retry due to CI issues. I was restarting things and we missed an event. That said, during the previous run, we had the following failure:
http://build.servo.org/builders/mac-rel-wpt/builds/2503/steps/test_1/logs/stdio

```
Tests with unexpected results:
  ▶ TIMEOUT [expected OK] /XMLHttpRequest/send-usp.worker
  │ 
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
  │ frame #0  - 0x000000011099d6ce - backtrace::backtrace::trace::h1195d62c5d35d60a
  │ frame #1  - 0x000000011099d9ec - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
  │ frame #2  - 0x000000010f0dd4a8 - servo::install_crash_handler::handler::h57fd71c5829cfe7c
  │ frame #3  - 0x00007fff99b3df19 - _sigtramp
  │ frame #4  - 0x0000000110088cff - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleIP8JSObjectEENS2_6HandleIS5_E
  │ frame #5  - 0x000000011006669d - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleINS2_5ValueEEENS2_6HandleIP8JSObjectE
  │ frame #6  - 0x000000011004db84 - _Z12JS_WrapValueP9JSContextN2JS13MutableHandleINS1_5ValueEEE
  │ frame #7  - 0x000000010f62b727 - std::panicking::try::call::h7a9fff3acdf72099
  │ frame #8  - 0x0000000110a3443a - __rust_maybe_catch_panic
  │ frame #9  - 0x000000010f92dda5 - script::dom::bindings::codegen::Bindings::MessageEventBinding::get_data::h5829833b91ec6817
  │ 
  │ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }"
  │ frame #0  - 0x000000011099d6ce - backtrace::backtrace::trace::h1195d62c5d35d60a
  │ frame #1  - 0x000000011099d9ec - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
  │ frame #2  - 0x000000010f0dd4a8 - servo::install_crash_handler::handler::h57fd71c5829cfe7c
  │ frame #3  - 0x00007fff99b3df19 - _sigtramp
  │ frame #4  - 0x000000010f0dd52c - servo::install_crash_handler::handler::h57fd71c5829cfe7c
  │ frame #5  - 0x00007fff99b3df19 - _sigtramp
  │ frame #6  - 0x0000000110088cff - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleIP8JSObjectEENS2_6HandleIS5_E
  │ frame #7  - 0x000000011006669d - 13JSCompartment4wrapEP9JSContextN2JS13MutableHandleINS2_5ValueEEENS2_6HandleIP8JSObjectE
  │ frame #8  - 0x000000011004db84 - _Z12JS_WrapValueP9JSContextN2JS13MutableHandleINS1_5ValueEEE
  │ frame #9  - 0x000000010f62b727 - std::panicking::try::call::h7a9fff3acdf72099
  │ frame #10 - 0x0000000110a3443a - __rust_maybe_catch_panic
  │ frame #11 - 0x000000010f92dda5 - script::dom::bindings::codegen::Bindings::MessageEventBinding::get_data::h5829833b91ec6817
  └ 
```

**Comment by emilio** [comment]
@larsbergstrom: That's #12654 (that just happened to hit us again).

@bors-servo: retry

**Comment by Manishearth** [comment]
Yesterday I was getting crashes on the list of values not being initialized -- does the gecko-side sync fix this, or is that a separate bug?

**Comment by bholley** [comment]
It would only fix it if you were running a rev of gecko different from the one that was on the stylo branch. We update the branch and land binding regens in lockstep.

**Comment by Manishearth** [comment]
I wasn't. Hm.

**Pull request merged**
