### PR TITLE
Fix placeholders for password inputs

### PR DESCRIPTION
**Pull request by Manishearth**
currently they show dots instead of the placeholder text

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9072)

### CODE REVIEW

**Comment by eefriedman** [comment]
I think this messes up get_insertion_point_index_for_layout; it expects to see the value before the mapping to dots.

Can we reftest this?  Maybe even just `<input type=password placeholder=xxx>` == `<input type=text placeholder=xxx>`.

**Comment by Manishearth** [comment]
The comment in `get_insertion_point_index_for_layout` mentions that we just need a 1:1 char mapping, which we have.

Yes, I can add a reftest.

**Comment by Manishearth** [comment]
Added a reftest

**Comment by Manishearth** [comment]
(failed due to an intermittent)

**Comment by eefriedman** [comment]
get_insertion_point_index_for_layout calls char_indices on the result of get_raw_textinput_value.  See #8265.

**Comment by Manishearth** [comment]
Given that layout only gets the dots, shouldn't it be calculating the insertion point based on the dots and not the actual text? In case the text contains non-ascii values this could get messed up.

**Comment by Manishearth** [comment]
Pushed another commit which takes a different approach and moves the placeholder logic out of get_raw_textinput_value (it doesn't really belong there anyway?)

**Comment by eefriedman** [comment]
Did you mean to make some other changes to get_raw_textinput_value, like removing the check for an empty string, or removing the mapping to dots?

**Comment by Manishearth** [comment]
My bad, updated.

**Comment by eefriedman** [comment]
Missing changes to get_raw_textinput_value?

**Comment by Manishearth** [comment]
Done

**Pull request merged**
