### PR TITLE
Implement <option> 'defaultSelected' reflecting attribute

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7743)

### CODE REVIEW

**Comment by jdm** [comment]
I think I'd like this to be implemented at the same time or after `HTMLOptionElement.selected`, so that we actually implement the required behaviour for `defaultSelected`.

**Comment by frewsxcv** [comment]
@jdm I'm not necessarily opposed to expanding this to also implement [`HTMLOptionElement.selected`](https://html.spec.whatwg.org/multipage/forms.html#dom-option-selected). Do you happen to know off-hand how trivial it would be to implement it?

**Comment by jdm** [comment]
It looks like it should be fairly straightforward to me:
* https://html.spec.whatwg.org/multipage/forms.html#attr-option-selected
* https://html.spec.whatwg.org/multipage/forms.html#dom-option-selected
* https://html.spec.whatwg.org/multipage/forms.html#concept-option-selectedness

**Comment by frewsxcv** [comment]
Sounds good, I'll look into it. I'll open a new PR if I complete it

**Comment by frewsxcv** [comment]
Continued in #7745

**Pull request closed without merging**
