### PR TITLE
Make Document::DefaultView return a null value when there's no browsi…

### LINKED ISSUE #11469: Make Document::DefaultView return a null value when there's no browsing context
This requires updating `Document.webidl` to indicate that a [nullable return value](http://heycam.github.io/webidl/#idl-nullable-type) is allowed, then modifying the implementation to check `self.browsing_context()` and return an appropriate value.

**Code**: `components/script/dom/webidls/Document.webidl`, `components/script/dom/document.rs`
**Test**: `./mach test-wpt tests/wpt/web-platform-tests/html/browsers/the-window-object/Document-defaultView.html` should show newly-passing tests, so the expected results will need to be [updated](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations).

### PR DESCRIPTION
**Pull request by kevgs**
- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #11469 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

…ng context

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11502)

### CODE REVIEW

**Comment by Ms2ger** [comment]
First of all, thank you for your PR!

You made some changes to scrolling APIs; let's see if there are any tests for those.

@bors-servo try

If not, I'd like to ask you to write a few tests. (In that case, you can use `./mach create-wpt tests/wpt/web-platform-tests/cssom-view/scrolling-no-browsing-context.html` to get started.)

+S-needs-code-changes +S-awaiting-answer 

<details><summary><i>Previously, kevgs wrote…</i></summary>
> #### Make Document::DefaultView return a null value when there&#39;s no browsi…
> 
> 
> 
> Fix for #11469
> 
> ---
> 
> 
> 
> - [ ] `./mach build -d` does not report any errors
> 
> - [ ] `./mach test-tidy` does not report any errors
> 
> - [ ] These changes fix #__ (github issue number if applicable).
> 
> 
> 
> 
> 
> - [ ] There are tests for these changes OR
> 
> - [ ] These changes do not require tests because _____
> 
> 
> 
> 
> 
> 
> 
> …ng context
> 
> 
> 
</details>


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/element.rs, line 1306 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11502#-KJ-dwEiM1U4aHg35A9L:-KJ-dwEiM1U4aHg35A9M:1575707716) ([raw file](https://github.com/servo/servo/blob/2653143b7c2d901804bcff241f2093e69a039f9f/components/script/dom/element.rs#L1306)):*
> ```Rust
>             return;
>         }
>         let win = w.unwrap();
> ```

This is somewhat of an unfortunate pattern; I suggest

```rust
let win = match doc.GetDefaultView() {
    None => return,
    Some(win) => win,
};
```

here and below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11502#-:-KJ-f3roPRbgBcYzVPn3:137828525)*

**Comment by kevgs** [comment]
Made code a bit good looking. Thanks for the suggestion!

Now looking for scrolling tests.

AppVeyor build failed, but it looks like something irrelevant to my patch because build failed in some c++ code.

**Comment by Ms2ger** [comment]
You can ignore the appveyor results.

**Comment by kevgs** [comment]
Sorry for the long timeout. It took me a while before I realized how this test should look like.

**Comment by Ms2ger** [comment]
Looks like the manifest update got lost; please apply the following diff:

```diff
--- a/tests/wpt/metadata/MANIFEST.json
+++ b/tests/wpt/metadata/MANIFEST.json
@@ -36028,7 +36028,16 @@
   "local_changes": {
     "deleted": [],
     "deleted_reftests": {},
-    "items": {},
+    "items": {
+      "testharness": {
+        "cssom-view/scrolling-no-browsing-context.html": [
+          {
+            "path": "cssom-view/scrolling-no-browsing-context.html",
+            "url": "/cssom-view/scrolling-no-browsing-context.html"
+          }
+        ]
+      }
+    },
     "reftest_nodes": {}
   },
   "reftest_nodes": {
```

and squash all commits into one.

-S-awaiting-answer -S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, kevgs wrote…</i></summary>
> Sorry for the long timeout. It took me a while before I realized how this test should look like.
</details>


---

Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/wpt/web-platform-tests/cssom-view/scrolling-no-browsing-context.html, line 3 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11502#-KJA92IMtBjBjrcuxoe-:-KJA92INXONlt1afcXjJ:-1197378445) ([raw file](https://github.com/servo/servo/blob/f1ef28e553c0aae5bf3c6a678811e83e0ab17bc6/tests/wpt/web-platform-tests/cssom-view/scrolling-no-browsing-context.html#L3)):*
> ```HTML
> <!doctype html>
> <meta charset="utf-8">
> <title></title>
> ```

Can you add a title here?

---

*[tests/wpt/web-platform-tests/cssom-view/scrolling-no-browsing-context.html, line 30 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11502#-KJA94hAnOaxh61RMsXU:-KJA94hAnOaxh61RMsXV:-711583691) ([raw file](https://github.com/servo/servo/blob/f1ef28e553c0aae5bf3c6a678811e83e0ab17bc6/tests/wpt/web-platform-tests/cssom-view/scrolling-no-browsing-context.html#L30)):*
> ```HTML
> 
>         },  "Element get and set scrollTop, scrollLeft, scroll() and scrollTo() test");
>     
> ```

Trailing whitespace; please remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11502#-:-KJA9OA_EBz7TbYeZB8u:-1615168861)*

**Comment by kevgs** [comment]
I failed to squash and created another PR https://github.com/servo/servo/pull/11548

**Pull request closed without merging**
