### PR TITLE
Update layout-2020 test expectations

### PR DESCRIPTION
**Pull request by Loirooriol**
Some tests are now passing thanks to #29661.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they are just updating test expectations.

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Comment by Loirooriol** [comment]
#29666 already covered `css/cssom-view/scrolling-quirks-vs-nonquirks.html`.

**Pull request merged**
