### PR TITLE
Remove syn 0.15 from our crate graph

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
Can't reproduce the failure locally.

r? @jdm

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
```
error[E0599]: no method named `print_display_list` found for struct `webrender_api::display_list::DisplayListBuilder` in the current scope
    --> components/layout_thread_2020/lib.rs:1423:29
     |
1423 |             display_list.wr.print_display_list();
     |                             ^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `emit_display_list`
error: aborting due to previous error
```

**Comment by nox** [comment]
Oopsie.

@bors-servo r=jdm

**Comment by jdm** [comment]
```
  ▶ PASS [expected FAIL] /css/css-transforms/transform-input-017.html
  ▶ PASS [expected FAIL] /_mozilla/css/pixel_snapping_glyphs.html
```

**Comment by jdm** [comment]
mac:
```
  ▶ FAIL [expected PASS] /css/css-transforms/transform-input-007.html
  │   → /css/css-transforms/transform-input-007.html 6bee6e27ba4ca58b20f8ad37b549bea2ef99ad8d
  └   → /css/css-transforms/transform-input-007-ref.html 800177cdd66435d8a39971642d49431a6f6da837
  ▶ FAIL [expected PASS] /css/css-transforms/transform-input-010.html
  │   → /css/css-transforms/transform-input-010.html 26729c861fca1b47786179eb75b5b079bbf54b90
  └   → /css/css-transforms/transform-input-010-ref.html 7996e1fb052707678836eb880ae6f25b93e95181
  ▶ FAIL [expected PASS] /css/css-transforms/transform-input-009.html
  │   → /css/css-transforms/transform-input-009.html 251699c1022d276d47116dc820f0140bcf9dd0e1
  └   → /css/css-transforms/transform-input-009-ref.html d2a5380eaaa6ddb4615b1aeac281f7da09732182
  ▶ PASS [expected FAIL] /css/css-transforms/transform-input-012.html
  ▶ FAIL [expected PASS] /css/css-paint-api/geometry-border-image-004.https.html
  │   → /css/css-paint-api/geometry-border-image-004.https.html 3145a6ada6d8aa45eb257bf007b98f3dbc9d4540
  └   → /css/css-paint-api/geometry-border-image-004-ref.html 8f803e0581a1800e4976edb007e33b60cc90de50
  ▶ FAIL [expected PASS] /css/css-paint-api/geometry-border-image-001.https.html
  │   → /css/css-paint-api/geometry-border-image-001.https.html 0d2e0f799a490f3467e1ffc471d72c014cb57905
  └   → /css/css-paint-api/geometry-border-image-001-ref.html e6ad70f4af27676c042855d3656a7802cab6b5f4
  ▶ PASS [expected FAIL] /css/compositing/mix-blend-mode/mix-blend-mode-both-parent-and-blended-with-3D-transform.html
  ▶ PASS [expected FAIL] /css/compositing/mix-blend-mode/mix-blend-mode-parent-with-3D-transform.html
```
linux:
```
  ▶ FAIL [expected PASS] /css/css-paint-api/geometry-border-image-004.https.html
  │   → /css/css-paint-api/geometry-border-image-004.https.html 3145a6ada6d8aa45eb257bf007b98f3dbc9d4540
  └   → /css/css-paint-api/geometry-border-image-004-ref.html 8f803e0581a1800e4976edb007e33b60cc90de50
  ▶ FAIL [expected PASS] /css/css-paint-api/geometry-border-image-001.https.html
  │   → /css/css-paint-api/geometry-border-image-001.https.html 0d2e0f799a490f3467e1ffc471d72c014cb57905
  └   → /css/css-paint-api/geometry-border-image-001-ref.html e6ad70f4af27676c042855d3656a7802cab6b5f4
  ▶ FAIL [expected PASS] /css/compositing/mix-blend-mode/mix-blend-mode-parent-with-text.html
  │   → /css/compositing/mix-blend-mode/mix-blend-mode-parent-with-text.html 4afe68f397f344d9f4569287456ef67ea3adf8f5
  └   → /css/compositing/mix-blend-mode/reference/mix-blend-mode-parent-with-text-ref.html 4dff65aaf855b5788010df7b97e065c18b25b151
  ▶ PASS [expected FAIL] /css/compositing/mix-blend-mode/mix-blend-mode-parent-with-3D-transform.html
  ▶ PASS [expected FAIL] /css/compositing/mix-blend-mode/mix-blend-mode-with-transform-and-preserve-3D.html
  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-010.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-010.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-017.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-017.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-009.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-009.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-197.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-197.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-174.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-174.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-176.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-176.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-019.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-019.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-122.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-122.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â”‚   â†’ /css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht b67e6025c65b4a0625ebf5225721f4774228ddb8
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-122.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-202.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-202.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-020.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-020.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-173.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-173.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-011.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-011.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-018.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-018.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-116.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-116.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â”‚   â†’ /css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht b67e6025c65b4a0625ebf5225721f4774228ddb8
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-116.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-012.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-012.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-175.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-175.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-198.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-198.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-200.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-200.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-203.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-203.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-121.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-121.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â”‚   â†’ /css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht b67e6025c65b4a0625ebf5225721f4774228ddb8
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-121.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-204.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-204.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-115.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-115.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â”‚   â†’ /css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht b67e6025c65b4a0625ebf5225721f4774228ddb8
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-115.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-201.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-201.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ FAIL [expected PASS] /css/CSS2/tables/table-anonymous-objects-199.xht
  â”‚   â†’ /css/CSS2/tables/table-anonymous-objects-199.xht a7409c71fc0df6d88f4420f5c7869c0d4fa0a4f8
  â””   â†’ /css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht aa5f2e2c376bd6b8862c2d8d71dc57d0460400a7


  â–¶ PASS [expected FAIL] /html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/fieldset-transform-translatez.html
```

**Comment by nox** [comment]
I didn't check all of them but that seems like snapping issues of some sort.

Capture d’écran 2020-03-03 à 11 35 13

**Comment by nox** [comment]
`/css/css-paint-api/geometry-border-image-004.https.html` and `/css/css-paint-api/geometry-border-image-001.https.html` also fail on Firefox so I just marked them as failures everywhere.

The rest of the Mac failures were failing on Linux, so I marked them as failures everywhere.

The `/css/CSS2/tables/table-anonymous-objects-***.xht` failures seem to be aliasing errors etc. I don't have the full logs to mark them fuzzy and I don't have a Linux box to run the tests myself.

**Comment by jdm** [comment]
You can get the full logs from taskcluster - find the test-wpt.log artifact and choose the raw output.

**Comment by nox** [comment]
Wait, those logs include the "there were X pixels different" and whatnot? TIL.

**Comment by jdm** [comment]
Mmm, they might not. Worth checking, though.

**Comment by nox** [comment]
I marked the various table anonymous objects failures on Linux as expected, just so we can land this and unblock webvr/webxr from landing in case some urgent patches need to be in the tree.

@bors-servo r=jdm p=1

**Comment by nox** [comment]
I think I properly fixed the expectations this time.

@bors-servo r=jdm

**Comment by jdm** [comment]
@bors-servo retry
* #21067 #25513

**Comment by CYBAI** [comment]
Linux tidy failed at building `mozjs_sys` 👀

```
[0m[0m[1m[31merror[0m[1m:[0m failed to run custom build command for `mozjs_sys v0.67.1 (https://github.com/servo/mozjs?rev=59065889ec7726b767d70b8702b43b4e4776cbfe#59065889)`

Caused by:
  process didn't exit successfully: `/repo/target/debug/build/mozjs_sys-09a4190b192df570/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=MAKE
cargo:rerun-if-env-changed=MOZTOOLS_PATH
[[ /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/configure -ot /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/configure.in ]] && touch /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/configure || true
[[ /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/old-configure -ot /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/old-configure.in ]] && touch /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/old-configure || true
! [[ /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/configure.in -ot /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/configure ]] && touch /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/configure || true
! [[ /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/old-configure.in -ot /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/old-configure ]] && touch /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/old-configure || true
if [[ /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/configure -nt /repo/target/debug/build/mozjs_sys-fac8652b6976d2aa/out/config.status ]] ; then \
  cd /repo/target/debug/build/mozjs_sys-fac8652b6976d2aa/out && \
  PYTHON="python2" MOZ_TOOLS="" \
  CC="clang" CFLAGS="" \
  CPP="gcc -E" CPPFLAGS="" \
  CXX="clang++" CXXFLAGS="" \
  AS="" AR="ar" \
  STLPORT_LIBS="" \
  RUST_TARGET="x86_64-unknown-linux-gnu" RUST_HOST="x86_64-unknown-linux-gnu" \
  RUST_SYSROOT="" \
  /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-shared-js --build-backends=RecursiveMake --enable-posix-nspr-emulation --with-ccache=sccache --disable-shared-js || (cat config.log && exit 1) ; \
fi
Creating Python environment
...
...
...
make[3]: *** [config/external/icu/i18n/target] Error 2
make[2]: *** [compile] Error 2
make[1]: *** [default] Error 2
make: *** [all] Error 2
thread 'main' panicked at 'assertion failed: result.success()', /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/build.rs:133:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1053
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
             at /rustc/4ad62488258972bdb0e2df225d100f99ef58dbad/src/libstd/panicking.rs:397
  12: build_script_build::build_jsapi
             at ./build.rs:133
  13: build_script_build::main
             at ./build.rs:19
  14: std::rt::lang_start::{{closure}}
             at /rustc/4ad62488258972bdb0e2df225d100f99ef58dbad/src/libstd/rt.rs:67
  15: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  16: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  18: std::panicking::try
             at src/libstd/panicking.rs:281
  19: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  20: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  21: std::rt::lang_start
             at /rustc/4ad62488258972bdb0e2df225d100f99ef58dbad/src/libstd/rt.rs:67
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by nox** [comment]
This is definitely some intermittent failure.

@bors-servo retry

**Comment by jdm** [comment]
For future reference, looking further up in the log for wintzimpl.o yields:
```
sccache: encountered fatal error
sccache: error : Invalid checksum
sccache:  cause: Invalid checksum
make[4]: *** [wintzimpl.o] Error 254
```
which is #25237.

**Pull request merged**
