### PR TITLE
Enable devtools by default on hololens.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by jdm** [comment]
No point in doing this before #25266.

**Comment by paulrouget** [comment]
Do you foresight any potential performance impact?

Otherwise, r=me.

**Comment by jdm** [comment]
I would be surprised by performance impact, since the devtools thread just waits on a channel and there's no default messages that are sent every frame.

**Comment by Manishearth** [comment]
A slight concern I have here is that this means that content can spam permissions prompts and lock up the browser by sending requests to localhost. Perhaps we can make this a setting or something? It's fine right now when it's just us using this.

**Comment by paulrouget** [comment]
@Manishearth we can’t start the devtools after servo started. Yet (#25119). So a setting would require a restart.

No ideal solution until we get the delayed devtools startup.

I think this is an ok short term solution.

But in general, we need a way to prevent any dialog to repeatedly be prompted: https://github.com/servo/servo/issues/25706

**Comment by paulrouget** [comment]
Landed as part of #25242

**Pull request closed without merging**
