### PR TITLE
Ensure that a navigation to the same URL is aborted. Fixes #10952.

### LINKED ISSUE #10952: panicking when loading agar.io
[ludo@Oulanl servo]$ ./mach run --release http://www.agar.io
ERROR:js::rust: Error at http://agar.io/js/a.js?a&ad_box_:0:0: document.write is not a function

ERROR:js::rust: Error at http://staticxx.facebook.com/connect/xd_arbiter.php?version=42#cb=f381742319487ba&domain=agar.io&origin=http%3A%2F%2Fagar.io%2Ff7bb7fb0cb1716&relation=parent&error=unknown_user:47:1880: window.name is undefined

ERROR:js::rust: Error at http://agar.io/js/master.js:2:23299: o is undefined

ERROR:js::rust: Error at https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.fr.0JX4waWGXC4.O/m=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCOmGNu6CSHv8uZNgXAzhVDn7pAJ9Q/cb=gapi.loaded_0:10:32: c is undefined

thread 'ImageCacheThread' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
  10:     0x561b5dbb8392 - <unknown>
  11:     0x561b5dbe26aa - <unknown>
  12:     0x561b5f07f86b - <unknown>
  13:     0x561b5f07f7fd - <unknown>
  14:     0x561b5dbe2afdthread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
thread 'PaintWorker' panicked at 'assertion failed: thread::panicking() || result == 0', /home/ludo/servo/.cargo/git/checkouts/ipc-channel-3840821e54ea11a6/master/platform/linux/mod.rs:95
thread 'PaintWorker' panicked at 'assertion failed: thread::panicking() || result == 0', /home/ludo/servo/.cargo/git/checkouts/ipc-channel-3840821e54ea11a6/master/platform/linux/mod.rs:95
thread 'PaintWorker' panicked at 'assertion failed: thread::panicking() || result == 0', /home/ludo/servo/.cargo/git/checkouts/ipc-channel-3840821e54ea11a6/master/platform/linux/mod.rs:95
 - <unknown>
  15:     0x561b5f086194 - <unknown>
  16:     0x7fd14b9f2589 - <unknown>
  17:     0x7fd14b5115cc - <unknown>
  18:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
  10:     0x561b5e5d3827 - <unknown>
  11:     0x561b5e5d435b - <unknown>
  12:     0x561b5d6e617d - <unknown>
  13:     0x561b5d6edcfe - <unknown>
  14:     0x561b5d6c04c4 - <unknown>
  15:     0x561b5d6f7ffc - <unknown>
  16:     0x561b5d6a8065 - <unknown>
  17:     0x561b5f0873b4 - <unknown>
  18:     0x561b5f07f86b - <unknown>
  19:     0x561b5f086dfb - <unknown>
  20:     0x7fd14b426720 - <unknown>
  21:     0x561b5d6a6268 - <unknown>
  22:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
  10:     0x561b5e5d3827 - <unknown>
  11:     0x561b5e5d435b - <unknown>
  12:     0x561b5e3593bf - <unknown>
  13:     0x561b5e357127 - <unknown>
  14:     0x561b5f07f86b - <unknown>
  15:     0x561b5f07f7fd - <unknown>
  16:     0x561b5e357841 - <unknown>
  17:     0x561b5f086194 - <unknown>
  18:     0x7fd14b9f2589 - <unknown>
  19:     0x7fd14b5115cc - <unknown>
  20:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
  10:     0x561b5e5d3827 - <unknown>
  11:     0x561b5e5d435b - <unknown>
  12:     0x561b5e3593bf - <unknown>
  13:     0x561b5e357127 - <unknown>
  14:     0x561b5f07f86b - <unknown>
  15:     0x561b5f07f7fd - <unknown>
  16:     0x561b5e357841 - <unknown>
  17:     0x561b5f086194 - <unknown>
  18:     0x7fd14b9f2589 - <unknown>
  19:     0x7fd14b5115cc - <unknown>
  20:                0x0 - <unknown>
stack backtrace:
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:785
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5d91de6f - <unknown>
   7:     0x561b5ed0f650 - <unknown>
   8:     0x561b5e35710d - <unknown>
   9:     0x561b5f07f86b - <unknown>
  10:     0x561b5f07f7fd - <unknown>
  11:     0x561b5e357841 - <unknown>
  12:     0x561b5f086194 - <unknown>
  13:     0x7fd14b9f2589 - <unknown>
  14:     0x7fd14b5115cc - <unknown>
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5d91de6f - <unknown>
   7:     0x561b5ed0f650 - <unknown>
   8:     0x561b5e35710d - <unknown>
   9:     0x561b5f07f86b - <unknown>
  10:     0x561b5f07f7fd - <unknown>
  11:     0x561b5e357841 - <unknown>
  12:     0x561b5f086194 - <unknown>
  13:     0x7fd14b9f2589 - <unknown>
  14:     0x7fd14b5115cc - <unknown>
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!  ', /home/ludo/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs :6196: 
    0x561b5d91de6f - <unknown>
   7:     0x561b5ed0f650 - <unknown>
   8:     0x561b5e35710d - <unknown>
   9:     0x561b5f07f86b - <unknown>
  10:     0x561b5f07f7fd - <unknown>
  11:     0x561b5e357841 - <unknown>
  12:     0x561b5f086194 - <unknown>
  13:     0x7fd14b9f2589 - <unknown>
  14:     0x7fd14b5115cc - <unknown>
  15:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5f06f778 - <unknown>
   7:     0x561b5f07f8e1 - <unknown>
   8:     0x561b5f0bf62f - <unknown>
   9:     0x561b5d91f105 - <unknown>
  10:     0x561b5e5d3827 - <unknown>
  11:     0x561b5e5d435b - <unknown>
  12:     0x561b5e3593bf - <unknown>
  13:     0x561b5e357127 - <unknown>
  14:     0x561b5f07f86b - <unknown>
  15:     0x561b5f07f7fd - <unknown>
  16:     0x561b5e357841 - <unknown>
  17:     0x561b5f086194 - <unknown>
  18:     0x7fd14b9f2589 - <unknown>
  19:     0x7fd14b5115cc - <unknown>
  20:                0x0 - <unknown>
stack backtrace:
   1:     0x561b5f080690 - <unknown>
   2:     0x561b5f087cab - <unknown>
   3:     0x561b5f087913 - <unknown>
   4:     0x561b5e6b66a6 - <unknown>
   5:     0x561b5f06dd33 - <unknown>
   6:     0x561b5d91de6f - <unknown>
   7:     0x561b5ed24060 - <unknown>
   8:     0x561b5d6ba0eb - <unknown>
   9:     0x561b5d6b9f77 - <unknown>
  10:     0x561b5d6b9f77 - <unknown>
  11:     0x561b5d6bbdd1 - <unknown>
  12:     0x561b5d6a8113 - <unknown>
  13:     0x561b5f0873b4 - <unknown>
  14:     0x561b5f07f86b - <unknown>
  15:     0x561b5f086dfb - <unknown>
  16:     0x7fd14b426720 - <unknown>
  17:     0x561b5d6a6268 - <unknown>
  18:                0x0 - <unknown>
thread panicked while panicking. aborting.
Servo exited with return value -4
[ludo@Oulanl servo]$

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10954)

### CODE REVIEW

**Comment by KiChjang** [comment]
-S-awaiting-review +S-needs-code-changes 

r=me after that small nit.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/script_thread.rs, line 1791 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10954#-KGfHWrbJuqwZz1mGBEt:-KGfHWrbJuqwZz1mGBEu:702365249) ([raw file](https://github.com/servo/servo/blob/b66c8dcb6b9381b50f2836bd20938fbe7d221ed2/components/script/script_thread.rs#L1791)):*
Can we move the above 3 lines into the if-body? It doesn't seem to be necessary to initialize and allocate resources for these variables if the condition turns out to be false.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10954#-:-KGfHozCHtgPApCZxyS2:-835772297)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/script_thread.rs, line 1800 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10954#-KGfKR4Y6FsaOAPjd1Ej:-KGfKR4ZG9B8zXT08a6x:1797384673) ([raw file](https://github.com/servo/servo/blob/b66c8dcb6b9381b50f2836bd20938fbe7d221ed2/components/script/script_thread.rs#L1800)):*
Hold on, the algorithm is only aborted when there is a fragment for nurl, so this should move 1 line up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10954)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/script_thread.rs, line 1800 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10954#-KGfKR4Y6FsaOAPjd1Ej:-KGgvmXXHQWb6OaqnpsF:1324263978) ([raw file](https://github.com/servo/servo/blob/b66c8dcb6b9381b50f2836bd20938fbe7d221ed2/components/script/script_thread.rs#L1800)):*
Yes, I think Keith is right here, the problem is that setting `location.hash` to an empty string seems to follow [this code path][1], which sets the url fragment to `None` instead of `Some("")`.

This seems to be the expected behaviour given the spec section for [`location.hash`][2]:

> If the given value is the empty string, set copyURL's fragment to null.

So not sure if the "navigate" algorithm spec should be updated to take into account null fragments, or if there's another bug in our code that should make us arrive with an url fragment (which doesn't seem to be the case, but I haven't looked too deeply at it).

[1]: https://github.com/servo/rust-url/blob/28d691c870223b3240ed8d284752ea7847774430/src/quirks.rs#L203
[2]: https://html.spec.whatwg.org/multipage/#dom-location-hash

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10954)*

**Comment by jdm** [comment]
I've filed https://github.com/whatwg/html/issues/1177 about this.

**Comment by emilio** [comment]
I think this should probably be rebased and landed while we wait for input in whatwg/html, there are quite a few pages affected.

What do you think @jdm? I can do the rebase if you're busy btw :)

**Comment by jdm** [comment]
I am inclined to agree, with a comment that links to the whatwg issue. If you could do the rebase, that would be swell!

**Comment by emilio** [comment]
Rebased in https://github.com/servo/servo/pull/11321

**Pull request closed without merging**
