### PR TITLE
#22484 small cleanup

### LINKED ISSUE #22484: HTMLImageElement::same_origin doesn't need to borrow mutable
It calls borrow_mut(), but it does not mutate anything. It should use borrow() instead.

Code: `components/script/dom/htmlimageelement.rs`

I would not this to be testable in any way, so if it builds it's good enough for a pull request.

### PR DESCRIPTION
**Pull request by cdeler**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22484 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it's a small code cleanup

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22490)

### CODE REVIEW

**Review by ferjm — APPROVED** [review]
LGTM, but let's change the commit message to something more descriptive like:

"_Do not borrow HTMLImageElement::same_origin as mutable_"

**Comment by CYBAI** [comment]
@bors-servo retry

<details>

```
{
    "status": "NOTRUN", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": "Accessing location object from different origins doesn't raise SECURITY_ERR exception", 
    "test": "/html/browsers/history/the-location-interface/security_location_0.htm", 
    "line": 125945, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/browsers/history/the-location-interface/security_location_0.htm", 
    "line": 125946, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/_mozilla/bluetooth/getDescriptors/device-goes-out-of-range.html", 
    "line": 126524, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/semantics/forms/attributes-common-to-form-controls/formAction_document_address.html", 
    "line": 126553, 
    "action": "test_result", 
    "expected": "OK"
}
```

</details>

**Comment by jdm** [comment]
@bors-servo r-
Emptying the queue so #22493 can merge easily.

**Pull request merged**
