### PR TITLE
Don't leak GitHub tokens when pushing

### PR DESCRIPTION
**Pull request by aneeshusa**
---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they just remove output/were lightly tested by hand

If git is unable to resolve the repo address (which includes the token),
it will print a message to stderr with the path to the repo, thus
leaking the token. Avoid doing this.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13507)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Since the queue is pretty long, I've updated this to a more secure method. r? @SimonSapin 

One thing I'm unsure of is whether there should be a colon (`:`) between the token and the `@github.com`. We didn't have it before but [the example you linked](https://github.com/t0yv0/t0yv0.github.io/blob/de5f1ef772ced750b5fe29fcf8388bbf2af8955a/deploy.sh) does, so I added it in case the file-based storage works differently.

**Comment by SimonSapin** [comment]
Looks ok to me, though I’ve never used `credential.helper` and don’t know what was the previous method that @larsbergstrom had approved.

Does this need corresponding changes on the CI servers?

**Comment by aneeshusa** [comment]
I spent some time looking at the git credentials documentation and I couldn't really understand how it worked, so I've moved away from that in the interest of knowing how our scripts work. This is now using the previous method of simply redirecting stdout/stderr, which is simpler and well-understood.

**Pull request merged**
