### PR TITLE
Convert private types to public

### LINKED ISSUE #9347: Change some of the private types to public
There are a few public methods in `components/compositing/compositor.rs`, `components/gfx/platform/freetype/font_context.rs` and `components/devtools` which return a private type, and so they show warnings during the build. We should make such types public.

### PR DESCRIPTION
**Pull request by mattkuo**
fixes #9347

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9352)

### CODE REVIEW

**Comment by nox** [comment]
Thanks for your contribution!

@bors-servo r+

**Comment by Wafflespeanut** [comment]
There's one last (platform-dependent) [private type in `gfx`](https://mxr.mozilla.org/servo/source/components/gfx/platform/freetype/font_context.rs#21). You wouldn't have gotten the warning if you're using Mac. Let's remove that, and we'll be good :)

**Comment by nox** [comment]
@Wafflespeanut Good catch.

**Comment by mattkuo** [comment]
@nox I've added the appropriate commit to the PR. So shouldn't it be labeled awaiting-review?

**Comment by nox** [comment]
@mattkuo Yes it should, somehow I thought @Wafflespeanut's comment was the last thing here. :)

**Pull request merged**
