### PR TITLE
Removed the T prefix for the style traits

### PR DESCRIPTION
**Pull request by perlun**
More work as described in #10185.

I am getting _extremely_ weird compile-time errors with this one, when it's trying to expand the `lazy_static!` macro. I think I'll need help getting that part sorted out. The rest should be pretty OK.

Anyone has ideas on how to resolve it?

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10488)

### CODE REVIEW

**Comment by emilio** [comment]
Here's the problem with lazy_static: https://github.com/rust-lang-nursery/lazy-static.rs/blob/master/src/lib.rs#L123

Probably it should use the fully qualified name for `Box`, but we're lucky, since we can just specify the `nightly` feature in our `Cargo.toml`, and it won't be a problem anymore :)

I'll send a patch regardless.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10488#-:-KF4xXnEKm6SeWKZk98Z:1236647940)*

**Comment by jdm** [comment]
From ./mach build-geckolib:
```
<lazy_static macros>:31:22: 31:33 error: wrong number of type arguments: expected 0, found 1 [E0244]
<lazy_static macros>:31 DATA = transmute:: < Box < $ T > , * const $ T > (
                                             ^~~~~~~~~~~
<lazy_static macros>:8:1: 9:72 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
/Users/servo/buildbot/slave/mac-dev-unit/build/target/debug/build/geckoservo-e51afb6640bc9a8f/out/properties.rs:2146:1: 2172:2 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
lib.rs:50:5: 50:58 note: in this expansion of include!
<lazy_static macros>:31:22: 31:33 help: run `rustc --explain E0244` to see a detailed explanation
<lazy_static macros>:32:1: 32:10 error: no associated item named `new` found for type `style::properties::style_struct_traits::Box` in the current scope
<lazy_static macros>:32 Box:: new ( __static_ref_initialize (  ) ) ) ; } ) ; & * DATA } let static_ref
                        ^~~~~~~~~
<lazy_static macros>:8:1: 9:72 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
/Users/servo/buildbot/slave/mac-dev-unit/build/target/debug/build/geckoservo-e51afb6640bc9a8f/out/properties.rs:2146:1: 2172:2 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
lib.rs:50:5: 50:58 note: in this expansion of include!
<lazy_static macros>:31:8: 31:49 error: the trait `std::marker::Sized` is not implemented for the type `style::properties::style_struct_traits::Box` [E0277]
<lazy_static macros>:31 DATA = transmute:: < Box < $ T > , * const $ T > (
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<lazy_static macros>:8:1: 9:72 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
/Users/servo/buildbot/slave/mac-dev-unit/build/target/debug/build/geckoservo-e51afb6640bc9a8f/out/properties.rs:2146:1: 2172:2 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
lib.rs:50:5: 50:58 note: in this expansion of include!
<lazy_static macros>:31:8: 31:49 help: run `rustc --explain E0277` to see a detailed explanation
<lazy_static macros>:31:8: 31:49 note: `style::properties::style_struct_traits::Box` does not have a constant size known at compile-time
<lazy_static macros>:31:8: 31:49 note: required by `std::mem::transmute`
<lazy_static macros>:31:22: 31:33 error: the trait `style::properties::style_struct_traits::Box` cannot be made into an object [E0038]
<lazy_static macros>:31 DATA = transmute:: < Box < $ T > , * const $ T > (
                                             ^~~~~~~~~~~
<lazy_static macros>:8:1: 9:72 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
/Users/servo/buildbot/slave/mac-dev-unit/build/target/debug/build/geckoservo-e51afb6640bc9a8f/out/properties.rs:2146:1: 2172:2 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
lib.rs:50:5: 50:58 note: in this expansion of include!
<lazy_static macros>:31:22: 31:33 help: run `rustc --explain E0038` to see a detailed explanation
<lazy_static macros>:31:22: 31:33 note: the trait cannot require that `Self : Sized`
error: aborting due to 4 previous errors
error: Could not compile `geckoservo`.
```

**Comment by SimonSapin** [comment]
Maybe it’d be easier to rename the `Box` style struct to `Box_` or something.

**Comment by pcwalton** [comment]
How about `Fragment` or `BoxStyle` or `BoxModel`? I have an irrational dislike of trailing underscores for disambiguation :)

**Comment by perlun** [comment]
Answering all three of you at once:

> From ./mach build-geckolib:

This is because of the issue that was mentioned earlier, that @emilio did a workaround for. Emilio, I guess we need to switch to the nightly version of lazy-static in our Cargo.toml...?

> Maybe it’d be easier to rename the Box style struct to Box_ or something.

Nah, I think it's better to solve it in the external crate. `Box` is such a common name that I think it makes sense to recommend crate developers to specify it with the full name anyway (to avoid ambiguities like this). Well, maybe not every Rust project would be implementing CSS features but anyway. ;)

> How about Fragment or BoxStyle or BoxModel? I have an irrational dislike of trailing underscores for disambiguation :)

I agree with that statement; it looks ugly and there must be better ways to solve it than that.

**Comment by bholley** [comment]
I didn't really follow the lazy_static thing, but we should avoid adding dependencies on new nightly features if we can, since Gecko will need to use stable rust.

BoxModel seems fine. That would also solve the problem of |box| being a keyword as well. Or even just "Display", which is what Gecko uses?

**Comment by perlun** [comment]
> I didn't really follow the lazy_static thing, but we should avoid adding dependencies on new nightly features if we can, since Gecko will need to use stable rust.

It's not a Rust-nightly feature, but a nightly-feature in lazy-static: https://github.com/rust-lang-nursery/lazy-static.rs/blob/master/src/lib.rs#L98

But yeah, I can live with the consensus on this if you feel that it's trying to bend the universe too much :)

**Comment by bholley** [comment]
I don't really have a good sense of whether it's likely to be a problem for us or not. If somebody does have a sense, and thinks it's going to be fine, then I don't care what we do here. Otherwise, I'd prefer to just do the safe thing and call it BoxModel.

**Comment by perlun** [comment]
I did a ugly hack for now, but let's give this some time to see if we can get this to land in `lazy-static` before resorting to workarounds. Builds should be fine now anyway. (no need to run the full-scale WPT on this one yet, so spare the buildbot the effort for now)

**Comment by SimonSapin** [comment]
Waiting for https://github.com/rust-lang-nursery/lazy-static.rs/pull/40 to be on crates.io, to avoid having two copies of `lazy_static`.

**Comment by perlun** [comment]
@SimonSapin - should be fine now, please re-check when you have a chance.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10488#-:-KFBC7d2yTPhN686iVCg:1236647940)*

**Pull request merged**
