### PR TITLE
Reduce max line length from 150 to 120 characters

### PR DESCRIPTION
**Pull request by frewsxcv**
Part of https://github.com/servo/servo/issues/6041

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6174)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Review status: 14 of 141 files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/gfx/text/shaping/harfbuzz.rs @ r1
- components/layout/construct.rs @ r1
- components/layout/display_list_builder.rs @ r1
- components/layout/model.rs @ r1
- components/layout/traversal.rs @ r1
- components/layout/wrapper.rs @ r1
- components/util/opts.rs @ r1
- python/tidy.py @ r1
- tests/reftest.rs @ r1
- tests/unit/net/data_loader.rs @ r1
- tests/unit/net/resource_task.rs @ r1
- tests/unit/script/textinput.rs @ r1
- tests/unit/style/media_queries.rs @ r1
- tests/unit/style/viewport.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6174)

**Comment by SimonSapin** [comment]
Review status: 29 of 141 files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- components/canvas/canvas_paint_task.rs @ r1
- components/canvas/webgl_paint_task.rs @ r1
- components/devtools/actors/console.rs @ r1
- components/devtools/actors/root.rs @ r1
- components/gfx/paint_context.rs @ r1
- components/gfx/paint_task.rs @ r1
- components/gfx/platform/freetype/font_list.rs @ r1
- components/style/build.rs @ r1
- components/style/legacy.rs @ r1
- components/style/properties.mako.rs @ r1
- components/style/viewport.rs @ r1
- components/webdriver_server/lib.rs @ r1
- ports/glutin/window.rs @ r1
- ports/gonk/src/input.rs @ r1
- ports/gonk/src/window.rs @ r1

---

<sup>**[components/devtools/actors/root.rs, line 6 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq3oxWA42FrUPghlifU)** ([raw file](https://github.com/servo/servo/blob/8e3f4bba85b9b246fb7da8ea0994fb0160578c1b/components/devtools/actors/root.rs#L6)):</sup>
Is this still a link in the output of `./mach doc`?

---

<sup>**[components/style/properties.mako.rs, line 1731 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq3o3035RRe6BtMo271)** ([raw file](https://github.com/servo/servo/blob/8e3f4bba85b9b246fb7da8ea0994fb0160578c1b/components/style/properties.mako.rs#L1731)):</sup>
Note that this is a Python/Mako string, not a Rust string. Have you verified that this builds?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6174)

**Comment by jgraham** [comment]
Review status: 29 of 141 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/webdriver_server/lib.rs, line 199 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq48M5Vu-YnswI0jcvD)** ([raw file](https://github.com/servo/servo/blob/8e3f4bba85b9b246fb7da8ea0994fb0160578c1b/components/webdriver_server/lib.rs#L199)):</sup>
nit: a fix more consistent with the rest of the file would be something like

    let value_resp = value.map(|x| WebElement::new(x).to_json()).to_json();
    Ok(WebDriverResponse::Generic(ValueResponse::new(value_resp)))

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6174)

**Comment by frewsxcv** [comment]
Review status: 28 of 141 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/webdriver_server/lib.rs, line 199 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq48M5Vu-YnswI0jcvD)** ([raw file](https://github.com/servo/servo/blob/8e3f4bba85b9b246fb7da8ea0994fb0160578c1b/components/webdriver_server/lib.rs#L199)):</sup>
https://github.com/servo/servo/commit/5793add4cdc9e96930160dfc90025f43607f9f5d

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6174)

**Comment by frewsxcv** [comment]
Review status: 28 of 141 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/devtools/actors/root.rs, line 6 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq3oxWA42FrUPghlifU)** ([raw file](https://github.com/servo/servo/blob/8e3f4bba85b9b246fb7da8ea0994fb0160578c1b/components/devtools/actors/root.rs#L6)):</sup>
It should; I do something similar in rust-rss:

https://github.com/frewsxcv/rust-rss/blob/f1a3d33c5d4504f375777b7aea216ba825f32729/src/channel.rs#L6-L7

and you can see here that it renders fine:

https://frewsxcv.github.io/rust-rss/rss/struct.Channel.html

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6174)

**Comment by frewsxcv** [comment]
Review status: 28 of 141 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/style/properties.mako.rs, line 1731 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq3o3035RRe6BtMo271)** ([raw file](https://github.com/servo/servo/blob/8e3f4bba85b9b246fb7da8ea0994fb0160578c1b/components/style/properties.mako.rs#L1731)):</sup>
Yeah, it builds fine. It does create extra spacing inbetween the keywords, but I figure it's not a huge deal

```
Python 2.7.9 (default, Jan 29 2015, 06:27:40)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "foo \
...    bar"
'foo    bar'
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6174)

**Comment by SimonSapin** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/msg/constellation_msg.rs @ r1
- components/net/cookie_storage.rs @ r1
- components/net/fetch/cors_cache.rs @ r1
- components/net/fetch/request.rs @ r1
- components/net/fetch/response.rs @ r1
- components/net/http_loader.rs @ r1
- components/net/image_cache_task.rs @ r1
- components/net/resource_task.rs @ r1
- components/net/storage_task.rs @ r1
- components/plugins/jstraceable.rs @ r1
- components/plugins/lib.rs @ r1
- components/plugins/lints/inheritance_integrity.rs @ r1
- components/plugins/lints/privatize.rs @ r1
- components/plugins/lints/unrooted_must_root.rs @ r1
- components/plugins/reflector.rs @ r1
- components/plugins/utils.rs @ r1
- components/script/cors.rs @ r1
- components/script/devtools.rs @ r1
- components/script/dom/bindings/trace.rs @ r1
- components/script/dom/blob.rs @ r1
- components/script/dom/browsercontext.rs @ r1
- components/script/dom/canvasrenderingcontext2d.rs @ r1
- components/script/dom/closeevent.rs @ r1
- components/script/dom/customevent.rs @ r1
- components/script/dom/document.rs @ r1
- components/script/dom/domexception.rs @ r1
- components/script/dom/domimplementation.rs @ r1
- components/script/dom/element.rs @ r1
- components/script/dom/errorevent.rs @ r1
- components/script/dom/htmlanchorelement.rs @ r1
- components/script/dom/htmlappletelement.rs @ r1
- components/script/dom/htmlareaelement.rs @ r1
- components/script/dom/htmlaudioelement.rs @ r1
- components/script/dom/htmlbaseelement.rs @ r1
- components/script/dom/htmlbodyelement.rs @ r1
- components/script/dom/htmlbrelement.rs @ r1
- components/script/dom/htmlbuttonelement.rs @ r1
- components/script/dom/htmlcanvaselement.rs @ r1
- components/script/dom/htmldataelement.rs @ r1
- components/script/dom/htmldatalistelement.rs @ r1
- components/script/dom/htmldialogelement.rs @ r1
- components/script/dom/htmldirectoryelement.rs @ r1
- components/script/dom/htmldivelement.rs @ r1
- components/script/dom/htmldlistelement.rs @ r1
- components/script/dom/htmlelement.rs @ r1
- components/script/dom/htmlembedelement.rs @ r1
- components/script/dom/htmlfieldsetelement.rs @ r1
- components/script/dom/htmlfontelement.rs @ r1
- components/script/dom/htmlformelement.rs @ r1
- components/script/dom/htmlframeelement.rs @ r1
- components/script/dom/htmlframesetelement.rs @ r1
- components/script/dom/htmlheadelement.rs @ r1
- components/script/dom/htmlheadingelement.rs @ r1
- components/script/dom/htmlhrelement.rs @ r1
- components/script/dom/htmlhtmlelement.rs @ r1
- components/script/dom/htmliframeelement.rs @ r1
- components/script/dom/htmlimageelement.rs @ r1
- components/script/dom/htmlinputelement.rs @ r1
- components/script/dom/htmllabelelement.rs @ r1
- components/script/dom/htmllegendelement.rs @ r1
- components/script/dom/htmllielement.rs @ r1
- components/script/dom/htmllinkelement.rs @ r1
- components/script/dom/htmlmapelement.rs @ r1
- components/script/dom/htmlmediaelement.rs @ r1
- components/script/dom/htmlmetaelement.rs @ r1
- components/script/dom/htmlmeterelement.rs @ r1
- components/script/dom/htmlmodelement.rs @ r1
- components/script/dom/htmlobjectelement.rs @ r1
- components/script/dom/htmlolistelement.rs @ r1
- components/script/dom/htmloptgroupelement.rs @ r1
- components/script/dom/htmloptionelement.rs @ r1
- components/script/dom/htmloutputelement.rs @ r1
- components/script/dom/htmlparagraphelement.rs @ r1
- components/script/dom/htmlparamelement.rs @ r1
- components/script/dom/htmlpreelement.rs @ r1
- components/script/dom/htmlprogresselement.rs @ r1
- components/script/dom/htmlquoteelement.rs @ r1
- components/script/dom/htmlscriptelement.rs @ r1
- components/script/dom/htmlselectelement.rs @ r1
- components/script/dom/htmlsourceelement.rs @ r1
- components/script/dom/htmlspanelement.rs @ r1
- components/script/dom/htmlstyleelement.rs @ r1
- components/script/dom/htmltablecaptionelement.rs @ r1
- components/script/dom/htmltablecellelement.rs @ r1
- components/script/dom/htmltablecolelement.rs @ r1
- components/script/dom/htmltabledatacellelement.rs @ r1
- components/script/dom/htmltableelement.rs @ r1
- components/script/dom/htmltableheadercellelement.rs @ r1
- components/script/dom/htmltablerowelement.rs @ r1
- components/script/dom/htmltablesectionelement.rs @ r1
- components/script/dom/htmltemplateelement.rs @ r1
- components/script/dom/htmltextareaelement.rs @ r1
- components/script/dom/htmltimeelement.rs @ r1
- components/script/dom/htmltitleelement.rs @ r1
- components/script/dom/htmltrackelement.rs @ r1
- components/script/dom/htmlulistelement.rs @ r1
- components/script/dom/htmlunknownelement.rs @ r1
- components/script/dom/htmlvideoelement.rs @ r1
- components/script/dom/messageevent.rs @ r1
- components/script/dom/mouseevent.rs @ r1
- components/script/dom/node.rs @ r1
- components/script/dom/processinginstruction.rs @ r1
- components/script/dom/storage.rs @ r1
- components/script/dom/storageevent.rs @ r1
- components/script/dom/uievent.rs @ r1
- components/script/dom/webglrenderingcontext.rs @ r1
- components/script/dom/websocket.rs @ r1
- components/script/dom/window.rs @ r1
- components/script/dom/worker.rs @ r1
- components/script/dom/xmlhttprequestupload.rs @ r1
- components/script/script_task.rs @ r1
- components/script/webdriver_handlers.rs @ r1
- components/webdriver_server/lib.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6174)

**Comment by nox** [comment]
Review status: all files reviewed, 7 unresolved discussions, some commit checks pending.

---

<sup>**[components/canvas/canvas_paint_task.rs, line 250 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq7FXjy85tx5oy880I0)** ([raw file](https://github.com/servo/servo/blob/5793add4cdc9e96930160dfc90025f43607f9f5d/components/canvas/canvas_paint_task.rs#L250)):</sup>
In previous change, and most everywhere in the code, the arrow goes on the same line and the clause's body is wrapped in curly braces.

---

<sup>**[components/layout/wrapper.rs, line 128 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq7EPZlCmfiVHsLfD1S)** ([raw file](https://github.com/servo/servo/blob/5793add4cdc9e96930160dfc90025f43607f9f5d/components/layout/wrapper.rs#L128)):</sup>
Useless type annotation.

---

<sup>**[components/layout/wrapper.rs, line 136 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq7EXdICbcOcjsPATPF)** ([raw file](https://github.com/servo/servo/blob/5793add4cdc9e96930160dfc90025f43607f9f5d/components/layout/wrapper.rs#L136)):</sup>
Useless type annotation.

---

<sup>**[components/layout/wrapper.rs, line 144 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq7EYiN0yjCgdqGvppE)** ([raw file](https://github.com/servo/servo/blob/5793add4cdc9e96930160dfc90025f43607f9f5d/components/layout/wrapper.rs#L144)):</sup>
Useless type annotation.

---

<sup>**[components/net/fetch/cors_cache.rs, line 146 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq7EjsakSu-76zLHEQl)** ([raw file](https://github.com/servo/servo/blob/5793add4cdc9e96930160dfc90025f43607f9f5d/components/net/fetch/cors_cache.rs#L146)):</sup>
You could also do:

```rust
let new_buf: Vec<CORSCacheEntry> = buf.into_iter().filter(|e| {
        e.origin == request.origin && request.destination == e.url
}).collect();
```

---

<sup>**[components/net/fetch/cors_cache.rs, line 154 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6174#-Jq7F9C24dBkFynZ8D78)** ([raw file](https://github.com/servo/servo/blob/5793add4cdc9e96930160dfc90025f43607f9f5d/components/net/fetch/cors_cache.rs#L154)):</sup>
Not consistent with previous change.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6174)

**Pull request merged**
