### PR TITLE
Implement the hashless color quirk (fixes #15341)

### LINKED ISSUE #15341: Implement hashless hex color quirk
Spec: https://quirks.spec.whatwg.org/#the-hashless-hex-color-quirk

In quirks mode, certain color properties should accept hashless hex color.

(Part of #11709)

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16858)

### CODE REVIEW

**Comment by nox** [comment]
Oh, rebase went successfully, but introduced garbage in lock file...

@bors-servo try

**Comment by jdm** [comment]
The bizarre crash output is a symptom of #16898.

**Comment by nox** [comment]
Live reviewing over IRC.

@bors-servo r=SimonSapin

**Pull request merged**
