### PR TITLE
Upgrade to html5ever 0.16

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16689)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
./mach package --dev
hdiutil: create failed - error -5341
Creating Servo.app
Copying files
Swapping prefs
Finding dylibs and relinking
Adding version to Credits.rtf
Writing run-servo
Creating dmg
Packaging MacOS dmg exited with return value 1
```

I… have no idea what this means. Let’s see if it happens again:

@bors-servo try retry

**Comment by jdm** [comment]
That's #16644.

**Comment by SimonSapin** [comment]
This is ready to land. r? @nox

**Pull request merged**
