### PR TITLE
implement PartialEq for MutHeap<JS<T>> and MutNullableHeap<JS<T>>

### PR DESCRIPTION
**Pull request by ajnirp**
for #8090

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8097)

### CODE REVIEW

**Comment by jdm** [comment]
@wenderen I believe the goal of this change was to allow comparing `MutHeap<JS<T>>`/MutNullableHeap<JS<T>>` values against `&T`/`Root<T>`, not other value of the same type.

**Comment by nox** [comment]
@jdm I need same values too. https://github.com/nox/servo/blob/a4cd9fb76ec3cd22af72e91f9df91e4dba6fd639/components/script/dom/range.rs#L783

**Comment by nox** [comment]
Thinking twice about it, I guess we should derive PartialEq for the same types implementation, and write another one to compare against `&T`, right?

**Comment by jdm** [comment]
Makes sense to me.

**Comment by wenderen** [comment]
I added separate methods for comparisons with `&T` / `Option<&T>`

**Comment by nox** [comment]
Thanks for your contribution! Some changes are needed, feel free to tell me if you have problems doing them.

To not root and get a `&JS<T>` from the unsafe cells, you will need to use `UnsafeCell::get`.

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/bindings/js.rs, line 265 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1AaTO1XJxPfqTSN0Wf)** ([raw file](https://github.com/servo/servo/blob/ab70c8c9421f09df9f705628d405de3109dcefd3/components/script/dom/bindings/js.rs#L265)):</sup>
You should compare the `val` fields directly instead, the whole point of this is to not root.


---

<sup>**[components/script/dom/bindings/js.rs, line 348 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1AaVNoUvPVSO_m0yqB)** ([raw file](https://github.com/servo/servo/blob/ab70c8c9421f09df9f705628d405de3109dcefd3/components/script/dom/bindings/js.rs#L348)):</sup>
Same remark about comparing the `val` field directly. Note that you don't need to explicitly call `PartialEq::eq`, you can just use `==`.


---

<sup>**[components/script/dom/bindings/js.rs, line 258 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1AaoNe3iNoiQIFxtYo)** ([raw file](https://github.com/servo/servo/blob/d9f8f686155da67322bcaf8a654596af11b900eb/components/script/dom/bindings/js.rs#L258)):</sup>
This should instead be in a separate `PartialEq<T>` impl, and you shouldn't root the values.


---

<sup>**[components/script/dom/bindings/js.rs, line 337 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1Ab8X1EyymWkqru4if)** ([raw file](https://github.com/servo/servo/blob/d9f8f686155da67322bcaf8a654596af11b900eb/components/script/dom/bindings/js.rs#L337)):</sup>
This should instead be in a separate `PartialEq<Option<&T>>` impl, and you shouldn't root the values.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8097)

**Comment by wenderen** [comment]
Thank you, this helped. I've pushed some more changes. 


---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/bindings/js.rs, line 265 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1AaTO1XJxPfqTSN0Wf)** ([raw file](https://github.com/servo/servo/blob/ab70c8c9421f09df9f705628d405de3109dcefd3/components/script/dom/bindings/js.rs#L265)):</sup>
Done.


---

<sup>**[components/script/dom/bindings/js.rs, line 348 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1AaVNoUvPVSO_m0yqB)** ([raw file](https://github.com/servo/servo/blob/ab70c8c9421f09df9f705628d405de3109dcefd3/components/script/dom/bindings/js.rs#L348)):</sup>
Done.


---

<sup>**[components/script/dom/bindings/js.rs, line 258 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1AaoNe3iNoiQIFxtYo)** ([raw file](https://github.com/servo/servo/blob/d9f8f686155da67322bcaf8a654596af11b900eb/components/script/dom/bindings/js.rs#L258)):</sup>
Done.


---

<sup>**[components/script/dom/bindings/js.rs, line 337 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1Ab8X1EyymWkqru4if)** ([raw file](https://github.com/servo/servo/blob/d9f8f686155da67322bcaf8a654596af11b900eb/components/script/dom/bindings/js.rs#L337)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8097)

**Comment by nox** [comment]
A few last remarks, and we are done!

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/js.rs, line 274 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1Kv5tXwoV2zcxyiihC)** ([raw file](https://github.com/servo/servo/blob/fe59b62db7e342abdc7b706a633ec4cfb9448b1b/components/script/dom/bindings/js.rs#L274)):</sup>
`**self.val.get() == other` should work, because `JS<T>` derefs to `T`.


---

<sup>**[components/script/dom/bindings/js.rs, line 344 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1KvEcUqeoF4bVFLFvU)** ([raw file](https://github.com/servo/servo/blob/fe59b62db7e342abdc7b706a633ec4cfb9448b1b/components/script/dom/bindings/js.rs#L344)):</sup>
```rust
**self.ptr.get() == other
```


---

<sup>**[components/script/dom/bindings/js.rs, line 352 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1KvJrBBsbDX6-oXo2T)** ([raw file](https://github.com/servo/servo/blob/fe59b62db7e342abdc7b706a633ec4cfb9448b1b/components/script/dom/bindings/js.rs#L352)):</sup>
```rust
*self.ptr.get() == other.map(JS::from_ref)
```

Here you obviously can't deref `Option<&T>`, but it's better to not use lambdas when you can just pass the function itself.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8097)

**Comment by wenderen** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/js.rs, line 274 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1Kv5tXwoV2zcxyiihC)** ([raw file](https://github.com/servo/servo/blob/fe59b62db7e342abdc7b706a633ec4cfb9448b1b/components/script/dom/bindings/js.rs#L274)):</sup>
Done.


---

<sup>**[components/script/dom/bindings/js.rs, line 344 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1KvEcUqeoF4bVFLFvU)** ([raw file](https://github.com/servo/servo/blob/fe59b62db7e342abdc7b706a633ec4cfb9448b1b/components/script/dom/bindings/js.rs#L344)):</sup>
`*self.ptr.get()` yields an `Option<T>`, which can't be dereferenced.


---

<sup>**[components/script/dom/bindings/js.rs, line 352 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8097#-K1KvJrBBsbDX6-oXo2T)** ([raw file](https://github.com/servo/servo/blob/fe59b62db7e342abdc7b706a633ec4cfb9448b1b/components/script/dom/bindings/js.rs#L352)):</sup>
This is cleaner, thanks.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8097)

**Comment by nox** [comment]
@bors-servo r+

Thanks!


---

Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8097)

**Pull request merged**
