### PR TITLE
Fix warnings: Use Vec.extend_from_slice instead of Vec.push_all

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8922)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo r-

Sorry, one nit.

-S-awaiting-merge +S-needs-code-changes 

---

Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/layout/construct.rs, line 180 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8922#-K5Cigny40p3dojz40jz:-K5Cigny40p3dojz40k-:1524108539) ([raw file](https://github.com/servo/servo/blob/53b60c9b661e66fb6c19bea560d5f9f7e2322e1e/components/layout/construct.rs#L180)):*
I think this function should not be renamed.

---

*[components/layout/construct.rs, line 231 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8922#-K5Cj7ez5I-Kna3_ygXN:-K5Cj7ez5I-Kna3_ygXO:1524108539) ([raw file](https://github.com/servo/servo/blob/53b60c9b661e66fb6c19bea560d5f9f7e2322e1e/components/layout/construct.rs#L231)):*
I think this function should not be renamed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8922#-:-K5CjC66Qg8p4yPKgCwE:-2018118012)*

**Comment by saneyuki** [comment]
oops! I replace them mechanically

---

Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/layout/construct.rs, line 180 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8922#-K5Cigny40p3dojz40jz:-K5CoQ-hyCJY6Ay2sRu_:-467915377) ([raw file](https://github.com/servo/servo/blob/53b60c9b661e66fb6c19bea560d5f9f7e2322e1e/components/layout/construct.rs#L180)):*
fixed

---

*[components/layout/construct.rs, line 231 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8922#-K5Cj7ez5I-Kna3_ygXN:-K5CoQxjEs_Xr4DPtYn5:-467915377) ([raw file](https://github.com/servo/servo/blob/53b60c9b661e66fb6c19bea560d5f9f7e2322e1e/components/layout/construct.rs#L231)):*
fixed

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8922#-:-K5CoS9xqNNa_gCqgAB9:-1757331562)*

**Comment by mbrubeck** [comment]
Reviewed 17 of 18 files at r1, 1 of 1 files at r2.
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/layout/construct.rs, line 548 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8922#-K5CqPUMM3_sMz3xwc0B:-K5CqPUMM3_sMz3xwc0C:1055950699) ([raw file](https://github.com/servo/servo/blob/53b60c9b661e66fb6c19bea560d5f9f7e2322e1e/components/layout/construct.rs#L548)):*
All the changes in this file should be reverted, because this method is no longer renamed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8922)*

**Comment by saneyuki** [comment]
> All the changes in this file should be reverted, because this method is no longer renamed.

Sorry!

**Comment by mbrubeck** [comment]
Reviewed 1 of 18 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8922)*

**Pull request merged**
