### PR TITLE
Add a `--dev` option to `mach build` and require either `--dev` or `--release`

### LINKED ISSUE #5933: Print a warning about performance after a debug build completes
When running `mach build` without the `--release` flag, print a message to the user about performance.  Something like:

> Warning: This is an un-optimized debug build. For performance testing, use `./mach build --release` to enable compiler optimizations.

The goal is to prevent users from unknowingly doing benchmarking or perf comparisons on debug builds.  The message can be printed at the end of the `build` function here:

https://github.com/servo/servo/blob/master/python/servo/build_commands.py

### PR DESCRIPTION
**Pull request by jinankjain**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5965)

### CODE REVIEW

**Comment by jinankjain** [comment]
@jdm @mbrubeck  as you suggested in #5941 I have implemented the third option that whenever a user build using --debug then then only warning is shown if both release and debug not set in that it exits compilation with a warning

**Comment by mbrubeck** [comment]
<sup>**[python/servo/build_commands.py, line 73 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5965#-Joe33Gl98CGQCxNynAM)** ([raw file](https://github.com/servo/servo/blob/ce23ab988ed6d5322091be15ec73e554a7555706/python/servo/build_commands.py#L73)):</sup>
We should update the build instructions in the `README.md` file to include this flag.

---

<sup>**[python/servo/build_commands.py, line 102 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5965#-Joe3Djal7mfytqtDzhm)** ([raw file](https://github.com/servo/servo/blob/ce23ab988ed6d5322091be15ec73e554a7555706/python/servo/build_commands.py#L102)):</sup>
We should also exit with an error if `release and debug` are both True. 

Nit: Python style convention is to omit the outer parentheses, and add a space after `not`.

---

<sup>**[python/servo/build_commands.py, line 103 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5965#-Joe1MIajitIWRZs74iw)** ([raw file](https://github.com/servo/servo/blob/ce23ab988ed6d5322091be15ec73e554a7555706/python/servo/build_commands.py#L103)):</sup>
If neither flag is True, then we should look for a default mode in `self.config` (which contains options from the parsed `.servobuild` file).  If there's no flag and no default mode, *then* we should display an error.

The error should explain exactly what to do, and (briefly) what the difference is.  For example: "Please specify either --debug for a development build or --release for an optimized build."

---

<sup>**[python/servo/build_commands.py, line 162 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5965#-Joe27fiX4kbmahjTp6C)** ([raw file](https://github.com/servo/servo/blob/ce23ab988ed6d5322091be15ec73e554a7555706/python/servo/build_commands.py#L162)):</sup>
I think this warning is no longer needed; we'll rely on the error message above instead.  That way we won't annoy deveolpers who frequently build in debug mode.

---

<sup>**[servobuild.example, line 27 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5965#-Joe1XVst2oe--KaHdTi)** ([raw file](https://github.com/servo/servo/blob/ce23ab988ed6d5322091be15ec73e554a7555706/servobuild.example#L27)):</sup>
I'd suggested changing this to a `mode` option, so it can allow both `mode="debug"` and `mode ="release"` (and any other profiles that Cargo adds in the future.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5965)

**Comment by mbrubeck** [comment]
Thanks!  I left a few comments on Reviewable, above.

**Comment by jinankjain** [comment]
@mbrubeck Could you please review the new full request I have amended the changes as you have suggested

**Comment by mbrubeck** [comment]
Reviewed files:
- python/servo/build_commands.py @ r1, r2
- README.md @ r2
- servobuild.example @ r1

---

<sup>**[python/servo/build_commands.py, line 73 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5965#-JokEC3mF1XwhHygD02b)** ([raw file](https://github.com/servo/servo/blob/773fdf5c6a39c5920710ff59060d47c605d06b7d/python/servo/build_commands.py#L73)):</sup>
Sorry I overlooked this before, but we should actually use `--dev` instead of `--debug` for consistency with other commands (like `mach run`).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5965)

**Comment by mbrubeck** [comment]
Reviewed files:
- python/servo/build_commands.py @ r2
- README.md @ r2
- servobuild.example @ r1

---

<sup>**[python/servo/build_commands.py, line 103 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5965#-Joe1MIajitIWRZs74iw)** ([raw file](https://github.com/servo/servo/blob/ce23ab988ed6d5322091be15ec73e554a7555706/python/servo/build_commands.py#L103)):</sup>
The first half of this comment (about `self.config`) still needs to be addressed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5965)

**Comment by mbrubeck** [comment]
@jinankjain Thanks! That addresses most of the issues.  There are still a couple of issues that haven't been addressed—in particular, reading the default from the config file.  Also, I added one more issue that I missed previously.  See the comments [on Reviewable](https://reviewable.io/reviews/servo/servo/5965) for details.

**Comment by jinankjain** [comment]
@mbrubeck I did not get the thing with config file what exactly needs to be done

**Comment by jinankjain** [comment]
@mbrubeck I had done that patch with --debug to --dev you could review that in my new PR

**Comment by mbrubeck** [comment]
@jinankjain: To read an option from the `servobuild` config file, you need to look in the `self.config` dictionary.  For example, see the code to [check the `android` setting in .servobuild](https://github.com/servo/servo/blob/02cf89f4d3fb991a27ecbaf8d3cafe5722750cc6/python/servo/build_commands.py#L93-L94).

If both `dev` and `release` are false, then `mach build` should check `self.config["build"]["mode"]`.  If it is set to "dev" then set the `dev` flag to True, and if it is set to "release" then set the `release` option to True.

The `self.config` dictionary is populated in the `CommandBase` constructor.  You can add code there to set `config["build"]["mode"]` to a default value of `""`, similar to [this code](https://github.com/servo/servo/blob/02cf89f4d3fb991a27ecbaf8d3cafe5722750cc6/python/servo/command_base.py#L95) which sets `config["build"]["android"]` to a default value of False.

**Comment by jinankjain** [comment]
@mbrubeck you could review the new PR

**Comment by mbrubeck** [comment]
<sup>**[servobuild.example, line 28 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5965#-JotOZkttvj9mIP8GAYK)** ([raw file](https://github.com/servo/servo/blob/a7a12e8c7cea0ab684c690259970d8e6cca0bf58/servobuild.example#L28)):</sup>
Nit: "dev" needs to be in quotation marks (`mode="dev"`).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5965)

**Comment by mbrubeck** [comment]
Reviewed files:
- python/servo/build_commands.py @ r3
- python/servo/command_base.py @ r3
- README.md @ r3
- servobuild.example @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5965)

**Comment by jinankjain** [comment]
Ya I fixed that up

**Comment by mbrubeck** [comment]
Everything looks great.  Thank you!

Note: We will need to deploy a change to our test infrastructure before we can merge this.  It'll be a little tricky because the two chances need to land at the same time.  I'll work on this next week.  See servo/saltfs#28 for details.

**Comment by jinankjain** [comment]
Any updates @mbrubeck ?

**Comment by mbrubeck** [comment]
This can land after #6023 and servo/saltfs#28 are merged and deployed. (It will need to be rebased, since part of it was split into #6023.)

**Comment by jinankjain** [comment]
What are merge conflicts should I have to look into it @mbrubeck ?

**Comment by mbrubeck** [comment]
I pushed the changes to add the `--dev` CommandOption, but nothing else.  You can rebase your patch onto master, and just leave out the parts that already landed in #6023.  Or I can rebase and push this if you would like.

**Comment by jinankjain** [comment]
Ya you could rebase and push it :)

**Comment by mbrubeck** [comment]
Rebased and moved to #6038.

**Comment by mbrubeck** [comment]
This was merged in the other PR.  Thank you @jinankjain!

**Pull request closed without merging**
