### PR TITLE
Use byte indices instead of char indices for text runs

### PR DESCRIPTION
**Pull request by mbrubeck**
Replace character indices with UTF-8 byte offsets throughout all code dealing with text runs.  This eliminates a lot of complexity when converting from one to the other, and interoperates better with the rest of the Rust ecosystem.

For most code this is just a simple replacement of char indices with byte indices.  In a few places like glyph storage and text fragment scanning, it also lets us get rid of code that existed only to map between bytes and chars.

Also includes some related fixes to text shaping, discovered while working on this conversion.  See the commit messages for details.

r? @pcwalton

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10895)

### CODE REVIEW

**Comment by mbrubeck** [comment]
> `▶ FAIL [expected PASS] /_mozilla/css/submit_focus_a.html`

Fixed. (I accidentally removed an `input_type` check in `HtmlInputElement::selection_for_layout`.)

**Comment by pcwalton** [comment]
@bors-servo: r+

This is awesome!

**Comment by mbrubeck** [comment]
@bors-servo retry

Infrastructure

**Comment by larsbergstrom** [comment]
cc me

**Pull request merged**
