### PR TITLE
replace vector iteration by ascii_case_insensitive_phf_map

### LINKED ISSUE #15994: Use case_insensitive_phf_map instead of iteration for system colors
#15974 adds system colors, but it parses them by [iterating over an array](https://github.com/servo/servo/pull/15974/files#diff-b0d36fd12bfc6b3e55fa2cfb9f55acd7R129).

We should use the `ascii_case_insensitive_phf_map` [like cssparser](https://github.com/servo/rust-cssparser/blob/0caaba170616cba326c4311967354110e4c79c8f/src/color.rs#L182) to efficiently parse these.

### PR DESCRIPTION
**Pull request by SergeevPavel**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15994 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17754)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good, thanks!

@bors-servo r+

**Comment by SimonSapin** [comment]
```rust
error[E0308]: mismatched types
     --> /Users/servo/buildbot/slave/mac-dev-unit/build/target/geckolib/debug/build/style-8e72fa08530fa207/out/properties.rs:19775:49
      |
19775 |                 if let Some(color) = color_name(ident) {
      |                                                 ^^^^^ expected &str, found struct `cssparser::CompactCowStr`
      |
      = note: expected type `&str`
                 found type `cssparser::CompactCowStr<'_>`
      = help: here are some functions which might fulfill your needs:
              - .trim()
              - .trim_left()
              - .trim_right()

error[E0308]: mismatched types
     --> /Users/servo/buildbot/slave/mac-dev-unit/build/target/geckolib/debug/build/style-8e72fa08530fa207/out/properties.rs:19776:24
      |
19776 |                     Ok(color)
      |                        ^^^^^ expected enum `gecko_bindings::structs::root::mozilla::LookAndFeel_ColorID`, found reference
      |
      = note: expected type `gecko_bindings::structs::root::mozilla::LookAndFeel_ColorID`
                 found type `&gecko_bindings::structs::root::mozilla::LookAndFeel_ColorID`

error: aborting due to 2 previous errors

error: Could not compile `style`.
```

Try `color_name(&ident)` and `Ok(*color)`, and run `./mach check-geckolib` to make sure it compiles.

**Comment by SergeevPavel** [comment]
thank for help

**Comment by emilio** [comment]
> thank for help

Thank _you_!

**Pull request merged**
