### PR TITLE
Issue4534 form submission for button elements

### PR DESCRIPTION
**Pull request by yodalee**
Sorry for the late PR for the issue #4534.
This issue is more complicated than I thought, I have to un-comment the Form-related attribute in Button element.
In the beginning, I modify the files in `bindings` directory, and it's ... generated files.
Hope I don't make something wrong.

### CODE REVIEW

**Comment by Manishearth** [comment]
Note: tree is closed (though I'll get around to reviewing this sometime)

**Comment by jdm** [comment]
Thanks for sticking with this @yodalee!

**Comment by jdm** [comment]
Sorry for the delay in reviewing these changes. It looks pretty good to me; I left some stylistic comments and some questions in the Critic review.

**Comment by yodalee** [comment]
Just rebase to master and solve the issues in critic review.

**Comment by jdm** [comment]
Great! I rebased the review on Critic for you (following the steps at https://github.com/servo/servo/wiki/Github-&-Critic-PR-handling-101); it's a helpful thing to do whenever you rebase a github branch in the future and allows us to continue reviewing the additional changes there :)

**Comment by jdm** [comment]
Looks like there's only one small change left :)

**Comment by yodalee** [comment]
Yeah, I see how it works in `inputelement`, it's no need to match type actually (lol)

**Comment by jdm** [comment]
Looks good! Thanks a lot!

**Comment by Manishearth** [comment]
Yes.

**Comment by yodalee** [comment]
Hope this time will work. My local result is slightly different to online result.

**Comment by yodalee** [comment]
Finally end lolololololololol

**Pull request merged**
