### PR TITLE
Update dependencies to reflect new locations, crate names

### LINKED ISSUE #6287: Package errors during mach cargo-update
```
~/D/r/servo (master|✔) $ ./mach cargo-update -a
components/servo
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/servo/rust-png`
    Updating git repository `https://github.com/servo/rust-geom`
    Updating git repository `https://github.com/servo/rust-stb-image`
    Updating git repository `https://github.com/servo/string-cache`
    Updating git repository `https://github.com/servo/rust-azure`
    Updating git repository `https://github.com/servo/rust-layers`
    Updating git repository `https://github.com/servo/rust-selectors`
    Updating git repository `https://github.com/servo/libfreetype2`
    Updating git repository `https://github.com/servo/rust-core-foundation`
    Updating git repository `https://github.com/servo/rust-freetype`
    Updating git repository `https://github.com/servo/rust-core-text`
    Updating git repository `https://github.com/servo/rust-egl`
    Updating git repository `https://github.com/servo/skia`
    Updating git repository `https://github.com/servo/rust-core-graphics`
no matching package named `core_foundation` found (required by `azure`)
location searched: https://github.com/servo/rust-core-foundation
version required: *
ports/cef
    Updating git repository `https://github.com/servo/gleam`
    Updating git repository `https://github.com/servo/rust-azure`
    Updating git repository `https://github.com/servo/rust-layers`
    Updating git repository `https://github.com/servo/rust-core-text`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/servo/rust-mozjs`
    Updating git repository `https://github.com/servo/rust-cgl`
    Updating git repository `https://github.com/servo/rust-stb-image`
    Updating git repository `https://github.com/servo/rust-cocoa`
    Updating git repository `https://github.com/servo/rust-core-foundation`
    Updating git repository `https://github.com/servo/rust-geom`
    Updating git repository `https://github.com/servo/rust-core-graphics`
    Updating git repository `https://github.com/servo/rust-png`
no matching package named `core_text` found (required by `embedding`)
location searched: https://github.com/servo/rust-core-text
version required: *
ports/gonk
    Updating git repository `https://github.com/servo/gleam`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/servo/rust-geom`
    Updating git repository `https://github.com/servo/rust-layers`
    Updating git repository `https://github.com/servo/rust-egl`
    Updating git repository `https://github.com/servo/rust-core-graphics`
    Updating git repository `https://github.com/servo/rust-png`
    Updating git repository `https://github.com/servo/rust-azure`
    Updating git repository `https://github.com/servo/rust-core-text`
    Updating git repository `https://github.com/servo/rust-x11-clipboard`
no matching package named `core_graphics` found (required by `compositing`)
location searched: https://github.com/servo/rust-core-graphics
version required: *
```

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes #6287 

Also in this commit: I ran `./mach cargo-update -a`

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6288)

### CODE REVIEW

**Comment by frewsxcv** [comment]
I just noticed rust-cgl also changed, let me add that in too

**Comment by frewsxcv** [comment]
....and I also need to add the lock files

**Comment by frewsxcv** [comment]
Current status: waiting on a few PRs to get merged:

* https://github.com/servo/io-surface-rs/pull/30

* https://github.com/servo/io-surface-rs/pull/30

* https://github.com/servo/rust-azure/pull/164

**Comment by frewsxcv** [comment]
This is ready to be reviewed now

**Comment by frewsxcv** [comment]
Looks like rust-azure is not compiling. Opened an issue: https://github.com/servo/rust-azure/issues/165

**Comment by metajack** [comment]
Closing, but went through and grabbed stuff I missed for #6295.

**Pull request closed without merging**
