### PR TITLE
Tidy finds WebIDLs with no spec.

### LINKED ISSUE #6689: Make tidy check for a specification link in webidl files
We want to ensure that every WebIDL file contains a comment with a link to the original specification.

code: python/tidy.py

### PR DESCRIPTION
**Pull request by notriddle**
Closes #6689

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6693)

### CODE REVIEW

**Comment by jdm** [comment]
Exciting! Thanks for doing this!

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/webidls/BrowserElement.webidl, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6693#-JuqCWrCmHqJ_ena9WGg)** ([raw file](https://github.com/servo/servo/blob/91c61ae7519956ddc22240a6db262c2fadd4cd13/components/script/dom/webidls/BrowserElement.webidl#L7)):</sup>
https://developer.mozilla.org/en-US/docs/Web/API/Using_the_Browser_API is more correct.

---

<sup>**[components/script/dom/webidls/CanvasPattern.webidl, line 6 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6693#-JuqC_mxzAjkMGKmSYxM)** ([raw file](https://github.com/servo/servo/blob/91c61ae7519956ddc22240a6db262c2fadd4cd13/components/script/dom/webidls/CanvasPattern.webidl#L6)):</sup>
Remove the scripting.html, but keep the #canvaspattern

---

<sup>**[components/script/dom/webidls/ErrorEvent.webidl, line 5 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6693#-JuqCdwLa2N6BHvs1ebN)** ([raw file](https://github.com/servo/servo/blob/91c61ae7519956ddc22240a6db262c2fadd4cd13/components/script/dom/webidls/ErrorEvent.webidl#L5)):</sup>
Remove webappapis.html but keep the hash.

---

<sup>**[components/script/dom/webidls/HTMLCollection.webidl, line 6 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6693#-JuqCmOTy-r-efPRq3us)** ([raw file](https://github.com/servo/servo/blob/91c61ae7519956ddc22240a6db262c2fadd4cd13/components/script/dom/webidls/HTMLCollection.webidl#L6)):</sup>
https://dom.spec.whatwg.org/#interface-htmlcollection

---

<sup>**[components/script/dom/webidls/WebSocket.webidl, line 5 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6693#-JuqCwG6i5Lf5wGWly39)** ([raw file](https://github.com/servo/servo/blob/91c61ae7519956ddc22240a6db262c2fadd4cd13/components/script/dom/webidls/WebSocket.webidl#L5)):</sup>
https://html.spec.whatwg.org/multipage/comms.html#the-websocket-interface

---

<sup>**[python/tidy.py, line 178 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6693#-JuqDD__Rd-Nsy_rkBa7)** ([raw file](https://github.com/servo/servo/blob/91c61ae7519956ddc22240a6db262c2fadd4cd13/python/tidy.py#L178)):</sup>
Let's remove this one.

---

<sup>**[python/tidy.py, line 184 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6693#-JuqD5QZqsdcSGtQ1TDZ)** ([raw file](https://github.com/servo/servo/blob/91c61ae7519956ddc22240a6db262c2fadd4cd13/python/tidy.py#L184)):</sup>
Do any errors occur if we remove this? We try to avoid any standard under the TR/ directory.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6693)

**Comment by notriddle** [comment]
> Do any errors occur if we remove this? We try to avoid any standard under the TR/ directory.

 *  components/script/dom/webidls/EventTarget.webidl
 *  components/script/dom/webidls/NodeIterator.webidl
 *  components/script/dom/webidls/EventListener.webidl

**Comment by jdm** [comment]
Let's make those use https://dom.spec.whatwg.org/#interface-eventtarget , https://dom.spec.whatwg.org/#nodeiterator and https://dom.spec.whatwg.org/#callbackdef-eventlistener respectively, in that case!

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 6 of 6 files at r2, 4 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6693)

**Comment by boghison** [comment]
What about https://w3c.github.io? I need this for #6708.

**Comment by jdm** [comment]
@boghison Feel free to add new ones as necessary.

**Pull request merged**
