### PR TITLE
Upgrade Rust

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? everybody

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5935)

### CODE REVIEW

**Comment by jdm** [comment]
Reviewed files:
- cargo-nightly-build @ r1
- components/canvas/canvas_paint_task.rs @ r1
- components/canvas/Cargo.toml @ r1
- components/canvas/lib.rs @ r1
- components/compositing/Cargo.toml @ r1
- components/compositing/compositor.rs @ r1
- components/compositing/compositor_layer.rs @ r1
- components/compositing/lib.rs @ r1
- components/compositing/scrolling.rs @ r1
- components/devtools/actor.rs @ r1
- components/devtools/actors/console.rs @ r1
- components/devtools/actors/inspector.rs @ r1
- components/devtools/actors/timeline.rs @ r1
- components/devtools/lib.rs @ r1
- components/devtools/protocol.rs @ r1
- components/devtools_traits/lib.rs @ r1
- components/gfx/Cargo.toml @ r1
- components/gfx/display_list/mod.rs @ r1
- components/gfx/filters.rs @ r1
- components/gfx/font.rs @ r1
- components/gfx/font_cache_task.rs @ r1
- components/gfx/font_context.rs @ r1
- components/gfx/lib.rs @ r1
- components/gfx/paint_context.rs @ r1
- components/gfx/paint_task.rs @ r1
- components/gfx/platform/freetype/font.rs @ r1
- components/gfx/platform/macos/font.rs @ r1
- components/gfx/platform/macos/font_template.rs @ r1
- components/gfx/text/glyph.rs @ r1
- components/gfx/text/shaping/harfbuzz.rs @ r1
- components/layout/animation.rs @ r1
- components/layout/Cargo.toml @ r1
- components/layout/construct.rs @ r1
- components/layout/css/matching.rs @ r1
- components/layout/display_list_builder.rs @ r1
- components/layout/flow.rs @ r1
- components/layout/flow_ref.rs @ r1
- components/layout/fragment.rs @ r1
- components/layout/generated_content.rs @ r1
- components/layout/incremental.rs @ r1
- components/layout/inline.rs @ r1
- components/layout/layout_task.rs @ r1
- components/layout/lib.rs @ r1
- components/layout/model.rs @ r1
- components/layout/sequential.rs @ r1
- components/layout/table.rs @ r1
- components/layout/table_wrapper.rs @ r1
- components/layout/text.rs @ r1
- components/layout/wrapper.rs @ r1
- components/net/about_loader.rs @ r1
- components/net/Cargo.toml @ r1
- components/net/cookie.rs @ r1
- components/net/data_loader.rs @ r1
- components/net/fetch/cors_cache.rs @ r1
- components/net/fetch/response.rs @ r1
- components/net/file_loader.rs @ r1
- components/net/http_loader.rs @ r1
- components/net/lib.rs @ r1
- components/net/resource_task.rs @ r1
- components/net_traits/image/base.rs @ r1
- components/net_traits/lib.rs @ r1
- components/plugins/casing.rs @ r1
- components/plugins/jstraceable.rs @ r1
- components/plugins/lib.rs @ r1
- components/plugins/lints/unrooted_must_root.rs @ r1
- components/plugins/utils.rs @ r1
- components/profile/lib.rs @ r1
- components/profile/mem.rs @ r1
- components/profile/time.rs @ r1
- components/profile_traits/time.rs @ r1
- components/script/Cargo.toml @ r1
- components/script/cors.rs @ r1
- components/script/dom/activation.rs @ r1
- components/script/dom/bindings/conversions.rs @ r1
- components/script/dom/bindings/js.rs @ r1
- components/script/dom/bindings/num.rs @ r1
- components/script/dom/bindings/refcounted.rs @ r1
- components/script/dom/bindings/trace.rs @ r1
- components/script/dom/bindings/utils.rs @ r1
- components/script/dom/blob.rs @ r1
- components/script/dom/canvasrenderingcontext2d.rs @ r1
- components/script/dom/dedicatedworkerglobalscope.rs @ r1
- components/script/dom/document.rs @ r1
- components/script/dom/domrect.rs @ r1
- components/script/dom/element.rs @ r1
- components/script/dom/formdata.rs @ r1
- components/script/dom/htmlanchorelement.rs @ r1
- components/script/dom/htmlcollection.rs @ r1
- components/script/dom/htmlelement.rs @ r1
- components/script/dom/imagedata.rs @ r1
- components/script/dom/keyboardevent.rs @ r1
- components/script/dom/node.rs @ r1
- components/script/dom/textencoder.rs @ r1
- components/script/dom/userscripts.rs @ r1
- components/script/dom/webglrenderingcontext.rs @ r1
- components/script/dom/window.rs @ r1
- components/script/dom/xmlhttprequest.rs @ r1
- components/script/horribly_inefficient_timers.rs @ r1
- components/script/layout_interface.rs @ r1
- components/script/lib.rs @ r1
- components/script/page.rs @ r1
- components/script/parse/html.rs @ r1
- components/script/script_task.rs @ r1
- components/script/textinput.rs @ r1
- components/script/timers.rs @ r1
- components/servo/Cargo.lock @ r1
- components/servo/lib.rs @ r1
- components/servo/main.rs @ r1
- components/style/animation.rs @ r1
- components/style/build.rs @ r1
- components/style/Cargo.toml @ r1
- components/style/legacy.rs @ r1
- components/style/lib.rs @ r1
- components/style/node.rs @ r1
- components/style/properties.mako.rs @ r1
- components/style/selector_matching.rs @ r1
- components/style/stylesheets.rs @ r1
- components/style/values.rs @ r1
- components/util/bezier.rs @ r1
- components/util/Cargo.toml @ r1
- components/util/cursor.rs @ r1
- components/util/deque/mod.rs @ r1
- components/util/geometry.rs @ r1
- components/util/lib.rs @ r1
- components/util/mem.rs @ r1
- components/util/opts.rs @ r1
- components/util/range.rs @ r1
- components/util/resource_files.rs @ r1
- components/util/str.rs @ r1
- components/util/taskpool.rs @ r1
- components/util/vec.rs @ r1
- components/webdriver_server/lib.rs @ r1
- components/webdriver_traits/Cargo.toml @ r1
- components/webdriver_traits/lib.rs @ r1
- ports/cef/Cargo.lock @ r1
- ports/cef/Cargo.toml @ r1
- ports/cef/lib.rs @ r1
- ports/cef/string.rs @ r1
- ports/cef/string_multimap.rs @ r1
- ports/cef/window.rs @ r1
- ports/cef/wrappers.rs @ r1
- ports/glutin/lib.rs @ r1
- ports/glutin/window.rs @ r1
- ports/gonk/Cargo.lock @ r1
- ports/gonk/Cargo.toml @ r1
- ports/gonk/src/input.rs @ r1
- ports/gonk/src/lib.rs @ r1
- ports/gonk/src/main.rs @ r1
- ports/gonk/src/window.rs @ r1
- rust-snapshot-hash @ r1
- tests/reftest.rs @ r1
- tests/unit/net/cookie.rs @ r1
- tests/unit/net/lib.rs @ r1
- tests/unit/net/mime_classifier.rs @ r1
- tests/unit/net/resource_task.rs @ r1
- tests/unit/style/Cargo.toml @ r1
- tests/unit/util/vec.rs @ r1
- tests/wpt/metadata/encoding/api-replacement-encodings.html.ini @ r1
- tests/wpt/metadata/encoding/textdecoder-labels.html.ini @ r1
- tests/wpt/metadata/encoding/textencoder-constructor-non-utf.html.ini @ r1
- tests/wpt/metadata/html/semantics/embedded-content/the-img-element/update-the-source-set.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/131.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/133.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/137.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/145.html.ini @ r1
- tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/146.html.ini @ r1
- tests/wpt/metadata/XMLHttpRequest/timeout-cors-async.htm.ini @ r1

---

<sup>**[components/gfx/font.rs, line 188 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVPI13ILO6nW7Wu-_e)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/gfx/font.rs#L188)):</sup>
?

---

<sup>**[components/gfx/text/glyph.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVPnzHCQIHG6chO2wZ)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/gfx/text/glyph.rs#L158)):</sup>
Why this change?

---

<sup>**[components/gfx/text/glyph.rs, line 731 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVPqzRtuYE1NUSutVZ)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/gfx/text/glyph.rs#L731)):</sup>
Why this change?

---

<sup>**[components/script/dom/xmlhttprequest.rs, line 1001 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVTcy3tdnjhv9wSYh6)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/script/dom/xmlhttprequest.rs#L1001)):</sup>
xhr.timeout_cancel

---

<sup>**[components/script/dom/xmlhttprequest.rs, line 1011 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVTocosP5QKrLKM0SO)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/script/dom/xmlhttprequest.rs#L1011)):</sup>
This comment is now meaningless.

---

<sup>**[components/script/parse/html.rs, line 186 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVU68n7VOIXBym26mn)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/script/parse/html.rs#L186)):</sup>
There's a PR open for this, but no need for this FIXME.

---

<sup>**[components/style/properties.mako.rs, line 2282 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVamP8y2kfwj6X8xP-)** ([raw file](https://github.com/servo/servo/blob/7b87085c1880c60aa3be5b3ec4572a0d93fd5537/components/style/properties.mako.rs#L2282)):</sup>
Why is it ok to get rid of this?

---

<sup>**[components/util/lib.rs, line 27 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVdG1tgi_JGN1qVT1d)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/util/lib.rs#L27)):</sup>
?

---

<sup>**[components/util/lib.rs, line 42 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVdE6YVw-A2XZ8dZ2j)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/util/lib.rs#L42)):</sup>
?

---

<sup>**[ports/cef/window.rs, line 117 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVeaTWI6bvA21ykByP)** ([raw file](https://github.com/servo/servo/blob/7b87085c1880c60aa3be5b3ec4572a0d93fd5537/ports/cef/window.rs#L117)):</sup>
Why this change?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by larsbergstrom** [comment]
<sup>**[ports/cef/window.rs, line 117 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVeaTWI6bvA21ykByP)** ([raw file](https://github.com/servo/servo/blob/7b87085c1880c60aa3be5b3ec4572a0d93fd5537/ports/cef/window.rs#L117)):</sup>
the msg_send function no longer exists and is now a macro. Unfortunately, that macro expects the literal selector name as its second argument, not a variable.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by jdm** [comment]
-

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by SimonSapin** [comment]
<sup>**[components/gfx/font.rs, line 188 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVPI13ILO6nW7Wu-_e)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/gfx/font.rs#L188)):</sup>
I’ve filed https://github.com/rust-lang/rust/issues/25106 about this. The comment should probably link to it.

---

<sup>**[components/gfx/text/glyph.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVPnzHCQIHG6chO2wZ)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/gfx/text/glyph.rs#L158)):</sup>
Because `.to_u32()`was provided by `ToPrimitive`, which is gone. In the specific case of converting from `i32`, it was equivalent to checking the sign.

---

<sup>**[components/gfx/text/glyph.rs, line 731 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVPqzRtuYE1NUSutVZ)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/gfx/text/glyph.rs#L731)):</sup>
Because `.to_u32()`was provided by `ToPrimitive`, which is gone. Perhaps this should assert that the value is non-negative. Unless glyph advances are always positive?

---

<sup>**[components/style/properties.mako.rs, line 2282 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVamP8y2kfwj6X8xP-)** ([raw file](https://github.com/servo/servo/blob/7b87085c1880c60aa3be5b3ec4572a0d93fd5537/components/style/properties.mako.rs#L2282)):</sup>
With cssparser switching to i32/f32 for everything, `count` is now `i32` instead of `i64`, and so can not be more than `u32::MAX`.

---

<sup>**[components/util/lib.rs, line 27 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVdG1tgi_JGN1qVT1d)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/util/lib.rs#L27)):</sup>
The point of this, together and the `pub use` below, is to re-export the crate/module to reduce churn in other crates. I tried `pub extern crate`, which built fine but did not do what I expected. (It’s the same as `extern crate`, AFAICT.)

---

<sup>**[components/util/lib.rs, line 42 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVdE6YVw-A2XZ8dZ2j)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/util/lib.rs#L42)):</sup>
See comment above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by jdm** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by jdm** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by SimonSapin** [comment]
<sup>**[components/gfx/font.rs, line 188 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVPI13ILO6nW7Wu-_e)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/gfx/font.rs#L188)):</sup>
The issue above is in the wrong repo. See https://github.com/servo/servo/issues/5938 instead.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by pcwalton** [comment]
Reviewed files:
- components/layout/animation.rs @ r1
- components/layout/Cargo.toml @ r1
- components/layout/construct.rs @ r1
- components/layout/css/matching.rs @ r1
- components/layout/display_list_builder.rs @ r1
- components/layout/flow.rs @ r1
- components/layout/flow_ref.rs @ r1
- components/layout/fragment.rs @ r1
- components/layout/generated_content.rs @ r1
- components/layout/incremental.rs @ r1
- components/layout/inline.rs @ r1
- components/layout/layout_task.rs @ r1
- components/layout/lib.rs @ r1
- components/layout/model.rs @ r1
- components/layout/sequential.rs @ r1
- components/layout/table.rs @ r1
- components/layout/table_wrapper.rs @ r1
- components/layout/text.rs @ r1
- components/layout/wrapper.rs @ r1

---

<sup>**[components/layout/flow.rs, line 604 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVs6fxeq7R1YntiAPz)** ([raw file](https://github.com/servo/servo/blob/f43d6158ef3f94f39d845e57652a02ce24f70011/components/layout/flow.rs#L604)):</sup>
Hmm, could this stuff be moved to `style` instead?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by mbrubeck** [comment]
Reviewed files:
- components/canvas/canvas_paint_task.rs @ r1
- components/util/bezier.rs @ r1
- components/util/Cargo.toml @ r1
- components/util/cursor.rs @ r1
- components/util/deque/mod.rs @ r1
- components/util/geometry.rs @ r1
- components/util/lib.rs @ r1

---

<sup>**[components/util/geometry.rs, line 306 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoW9ioowWlObbeMZD_P)** ([raw file](https://github.com/servo/servo/blob/f43d6158ef3f94f39d845e57652a02ce24f70011/components/util/geometry.rs#L306)):</sup>
Nit: The naming is inconsistent now, since `to_frac_px` returns `f32` while `from_frac_px` takes `f64`. For consistency, this should be `to_frac32_px` and/or `from_frac_px` should be `from_subpx`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by Manishearth** [comment]
Reviewed files:
- components/net/about_loader.rs @ r1
- components/net/Cargo.toml @ r1
- components/net/cookie.rs @ r1
- components/net/fetch/cors_cache.rs @ r1
- components/net/fetch/response.rs @ r1
- components/net/file_loader.rs @ r1
- components/net/http_loader.rs @ r1
- components/net/lib.rs @ r1
- components/net/resource_task.rs @ r1
- components/net_traits/image/base.rs @ r1

---

<sup>**[components/net/cookie.rs, line 71 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoWNp5SWe1O1xmHk4EU)** ([raw file](https://github.com/servo/servo/blob/f43d6158ef3f94f39d845e57652a02ce24f70011/components/net/cookie.rs#L71)):</sup>
What does this / check do?

Step 7 says:

>    If the cookie-attribute-list contains an attribute with an
        attribute-name of "Path", set the cookie's path to attribute-
        value of the last attribute in the cookie-attribute-list with an
        attribute-name of "Path".  Otherwise, set the cookie's path to
        the default-path of the request-uri.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by jdm** [comment]
<sup>**[components/net/cookie.rs, line 71 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoWNp5SWe1O1xmHk4EU)** ([raw file](https://github.com/servo/servo/blob/f43d6158ef3f94f39d845e57652a02ce24f70011/components/net/cookie.rs#L71)):</sup>
That seems like something that should be filed separately.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by SimonSapin** [comment]
<sup>**[components/script/parse/html.rs, line 186 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoVU68n7VOIXBym26mn)** ([raw file](https://github.com/servo/servo/blob/76ad99ff0ff2c41963d37932605b1256d21d2bc2/components/script/parse/html.rs#L186)):</sup>
This one https://github.com/servo/servo/pull/5727 ? Ok, I’ll remove the comment.

---

<sup>**[components/util/geometry.rs, line 306 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoW9ioowWlObbeMZD_P)** ([raw file](https://github.com/servo/servo/blob/f43d6158ef3f94f39d845e57652a02ce24f70011/components/util/geometry.rs#L306)):</sup>
I filed a follow up issue https://github.com/servo/servo/issues/5943 that I’ll take after this lands.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by jdm** [comment]
Reviewed files:
- components/canvas/lib.rs @ r3
- components/canvas/webgl_paint_task.rs @ r3
- components/layout/flow.rs @ r5
- components/script/dom/xmlhttprequest.rs @ r5
- components/script/layout_interface.rs @ r4
- components/script/parse/html.rs @ r5
- components/servo/main.rs @ r4
- components/style/properties.mako.rs @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by jdm** [comment]
<sup>**[components/net/cookie.rs, line 71 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5935#-JoWNp5SWe1O1xmHk4EU)** ([raw file](https://github.com/servo/servo/blob/f43d6158ef3f94f39d845e57652a02ce24f70011/components/net/cookie.rs#L71)):</sup>
Filed https://github.com/servo/servo/issues/5944.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5935)

**Comment by SimonSapin** [comment]
thread 'iframe/hide_layers2.html == iframe/hide_layers_ref.html' panicked at 'rendering difference: /tmp/servo-reftest-000099-diff.png', ../../tests/reftest.rs:336

**Pull request merged**
