### PR TITLE
Stop skipping css-logical tests in layout-2020

### PR DESCRIPTION
**Pull request by Loirooriol**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because there is no change in behavior

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Comment by Loirooriol** [comment]
I expected less failures TBH, since this should mostly be a style thing.

**Comment by Loirooriol** [comment]
Ah, that explains it. Most of the logical longhands seem enabled, but if writing modes aren't supported, they will not be mapped as the tests expect.

**Pull request merged**
