### PR TITLE
Move macOS WPT chunk 1 (only) from Buildbot to Taskcluster 

### PR DESCRIPTION
**Pull request by SimonSapin**
This is only one chunk at a time so that we don’t need to double the number of worker nor the cycle time during the migration.

A release build takes ~40 minutes which seems worrying, but this also happens (sometimes) on Buildbot. For example: https://build.servo.org/builders/mac-rel-wpt1/builds/10401

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22459)

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by SimonSapin** [comment]
> `[taskcluster:error] Uploading error artifact public/filtered-wpt-errorsummary.log from file repo/filtered-wpt-errorsummary.log with message "Could not read file '/Users/worker/tasks/task_1544801404/repo/filtered-wpt-errorsummary.log'", reason "file-missing-on-worker" and expiry 2019-12-14T14:47:58.994Z`
>
> `[taskcluster:error] TASK FAILURE during artifact upload: file-missing-on-worker: Could not read file '/Users/worker/tasks/task_1544801404/repo/filtered-wpt-errorsummary.log'`

**Comment by SimonSapin** [comment]
https://tools.taskcluster.net/groups/f1zynGgKQDe7PVq9ZQZ84w is green! (Hacked to not re-compile and to run fewer tests.)

**Comment by SimonSapin** [comment]
Removed the hacks, I think this is ready to land.

**Comment by SimonSapin** [comment]
One WPT failure on Linux. macOS WPT on TC is green.

@bors-servo retry

```
  ▶ CRASH [expected OK] /html/syntax/parsing/html5lib_webkit01.html?run_type=uri
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.3.0-devel
  │ PASS
  │ FOO<span>BAR</span>BAZ
  │ called `Result::unwrap()` on an `Err` value: Io(Custom { kind: ConnectionReset, error: StringError("All senders for this socket closed") }) (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at libcore/result.rs:1009)
  │ stack backtrace:
  │    0:     0x55acd4d6608c - backtrace::backtrace::trace::h8f3a081151eb58d3
  │    1:     0x55acd4d652b2 - <backtrace::capture::Backtrace as core::default::Default>::default::h1f4987997aac7394
  │    2:     0x55acd4d65328 - backtrace::capture::Backtrace::new::hf2131665d3ac906b
  │    3:     0x55acd26783b9 - servo::main::{{closure}}::h56d697211f3aa43c
  │    4:     0x55acd5ade033 - std::panicking::rust_panic_with_hook::hd470ff3b3e7a1b18
  │                         at libstd/panicking.rs:480
  │    5:     0x55acd5addb99 - std::panicking::continue_panic_fmt::hf0cf39ae1e114602
  │                         at libstd/panicking.rs:390
  │    6:     0x55acd5adda95 - rust_begin_unwind
  │                         at libstd/panicking.rs:325
  │    7:     0x55acd5aff1fb - core::panicking::panic_fmt::hf53111ba26d35bb0
  │                         at libcore/panicking.rs:77
  │    8:     0x55acd31249fd - core::result::unwrap_failed::hd92c2d8845ec560e
  │    9:     0x55acd35b0262 - script::dom::url::URL::RevokeObjectURL::h79600a550d0fc8eb
  │   10:     0x55acd2eb344b - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfc3d1b82d94eec31
  │   11:     0x55acd37fb20f - _ZN3std9panicking3try7do_call17hfa21f5a682225d3eE.llvm.16403237719749452487
  │   12:     0x55acd5af02a9 - __rust_maybe_catch_panic
  │                         at libpanic_unwind/lib.rs:102
  │   13:     0x55acd2f69e5c - script::dom::bindings::codegen::Bindings::URLBinding::URLBinding::revokeObjectURL::hef4be11b6201429f
  │   14:     0x55acd52e92e2 - _ZN2js12CallJSNativeEP9JSContextPFbS1_jPN2JS5ValueEERKNS2_8CallArgsE
  │                         at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.5/mozjs/js/src/vm/JSContext-inl.h:290
  │                          - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  │                         at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.5/mozjs/js/src/vm/Interpreter.cpp:468
  │   15:     0x55acd52dbf96 - _ZN2js13CallFromStackEP9JSContextRKN2JS8CallArgsE
  │                         at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.5/mozjs/js/src/vm/Interpreter.cpp:523
  │                          - Interpret
  │                         at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.5/mozjs/js/src/vm/Interpreter.cpp:3086
  │   16:     0x55acd52e8f44 - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.5/mozjs/js/src/vm/Interpreter.cpp:418
  │   17:     0x55acd52e94a1 - _ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE
  │                         at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.5/mozjs/js/src/vm/Interpreter.cpp:490
  │   18:     0x55acd52e9f1e - InternalCall
  │                         at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.5/mozjs/js/src/vm/Interpreter.cpp:517
  │                          - _ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE
  │                         at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.5/mozjs/js/src/vm/Interpreter.cpp:536
  │   19:     0x55acd4f38ee2 - _ZN2js8fun_callEP9JSContextjPN2JS5ValueE
  │                         at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs_sys-0.61.5/mozjs/js/src/vm/JSFunction.cpp:1179
  │   20:     0x2dc511e7cbe5 - <unknown>
  │ [2018-12-14T16:47:34Z ERROR servo] called `Result::unwrap()` on an `Err` value: Io(Custom { kind: ConnectionReset, error: StringError("All senders for this socket closed") })
  └ Pipeline failed in hard-fail mode.  Crashing!
```

**Comment by CYBAI** [comment]
@bors-servo retry

```
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": "Test timed out", 
    "stack": null, 
    "subtest": "_parent should reuse window.parent context", 
    "test": "/html/browsers/windows/browsing-context-names/choose-_parent-003.html", 
    "line": 132914, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/browsers/windows/browsing-context-names/choose-_parent-003.html", 
    "line": 132915, 
    "action": "test_result", 
    "expected": "OK"
}
```

**Pull request merged**
