### PR TITLE
Update OSMesa.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19396)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* sccache failure

**Comment by jdm** [comment]
Huh:
```
/Users/servo/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1cf8c2f/mesa-src/include/c11/threads_posix.h:391:9: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        clock_gettime(CLOCK_REALTIME, ts);
        ^
/Users/servo/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1cf8c2f/mesa-src/include/c11/threads_posix.h:391:23: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, ts);
                      ^
2 errors generated.
```

**Comment by emilio** [comment]
(It built locally on @nox's machine, and I have no clue about how to repro this given it's osx only... I'll login into a builder I guess)

**Comment by emilio** [comment]
Closing for now.

**Pull request closed without merging**
