### PR TITLE
style: Remove TNode::set_can_be_fragmented and TNode::can_be_fragmented.

### PR DESCRIPTION
**Pull request by emilio**
Replace them instead by a computed value flag, the same way as the
IS_IN_DISPLAY_NONE_SUBTREE flag works.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18893)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo try 

 * Now passing tidy

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_columns.htm
  └   → /css-flexbox-1_dev/html/flexbox_columns.htm e038cebd05342d3dd4d4ddc05038107516f916c4
/css-flexbox-1_dev/html/reference/flexbox_columns-ref.htm b162d7afebb1dac86e4f86aae00e6a06654fd405
Testing e038cebd05342d3dd4d4ddc05038107516f916c4 == b162d7afebb1dac86e4f86aae00e6a06654fd405
```

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18893#-:-Kw_WJKzb6TIhdofqtlQ:bkg9nno)*

**Comment by jdm** [comment]
@bors-servo: retry
* actual commit differed error

**Comment by emilio** [comment]
So with and without patch frame tree dumps:

 * [with-patch.txt](https://github.com/servo/servo/files/1391239/with-patch.txt)

 * [without_patch.txt](https://github.com/servo/servo/files/1391241/without_patch.txt)

Diff:

<details>
```diff
diff --git a/with-patch.txt b/without_patch.txt
index 85ba49bbb3..c46f4e1615 100644
--- a/with-patch.txt
+++ b/without_patch.txt
@@ -40,3 +40,45 @@
 │  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i891px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(66px×18.633333333333333px at (-14px,0px)), paint: TypedRect(66px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(13) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
 │  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)) }
 │  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(12) ["damer"] border_box=LogicalRect(H LTR, i52px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+┌ Post layout flow tree
+│  ├─ Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i1024px×b740px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(1024px×740px at (0px,0px)), paint: TypedRect(1024px×740px at (0px,0px)) } children=1
+│  │  ├─ ↑↑ Fragment for block: SpecificFragmentInfo::Generic(24) [] border_box=LogicalRect(H LTR, i1024px×b740px, @ (i0px,b0px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  ├─ Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i1024px×b18.633333333333333px, @ (i0px,b8px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(1008px×18.633333333333333px at (8px,0px)), paint: TypedRect(1008px×18.633333333333333px at (8px,0px)) } children=1
+│  │  │  ├─ ↑↑ Fragment for block: SpecificFragmentInfo::Generic(22) [] border_box=LogicalRect(H LTR, i1008px×b18.633333333333333px, @ (i8px,b0px)) margin=LogicalMargin(H LTR, i:8px..8px b:8px..8px) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  ├─ FlexFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i1008px×b18.633333333333333px, @ (i8px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(1008px×18.633333333333333px at (0px,0px)), paint: TypedRect(1008px×18.633333333333333px at (0px,0px)) } children=5 damage=REFLOW_OUT_OF_FLOW | REFLOW, main_mode: Inline, available_main_size: MinMax(SizeConstraint { min_size: 0px, max_size: None }), available_cross_size: MinMax(SizeConstraint { min_size: 0px, max_size: None }), lines: [FlexLine { range: 0..5, free_space: 650px, auto_margin_count: 0, cross_size: 18.633333333333333px }], items: [FlexItem { main_size: 150px, base_size: 150px, min_size: 0px, max_size: 17895697.05px, index: 0, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }, FlexItem { main_size: 52px, base_size: 52px, min_size: 0px, max_size: 17895697.05px, index: 1, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }, FlexItem { main_size: 52px, base_size: 52px, min_size: 0px, max_size: 17895697.05px, index: 2, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }, FlexItem { main_size: 52px, base_size: 52px, min_size: 0px, max_size: 17895697.05px, index: 3, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }, FlexItem { main_size: 52px, base_size: 52px, min_size: 0px, max_size: 17895697.05px, index: 4, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }], main_reverse: false, is_wrappable: false, cross_reverse: false }
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i150px×b18.633333333333333px, @ (i65px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(164px×18.633333333333333px at (-14px,0px)), paint: TypedRect(164px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(1) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i150px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(150px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(150px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(0) ["one two three four"] border_box=LogicalRect(H LTR, i150px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i345px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(66px×18.633333333333333px at (-14px,0px)), paint: TypedRect(66px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(4) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(3) ["damer"] border_box=LogicalRect(H LTR, i52px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i527px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(66px×18.633333333333333px at (-14px,0px)), paint: TypedRect(66px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(7) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(6) ["damer"] border_box=LogicalRect(H LTR, i52px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i709px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(66px×18.633333333333333px at (-14px,0px)), paint: TypedRect(66px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(10) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(9) ["damer"] border_box=LogicalRect(H LTR, i52px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i891px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(66px×18.633333333333333px at (-14px,0px)), paint: TypedRect(66px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(13) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(12) ["damer"] border_box=LogicalRect(H LTR, i52px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+┌ Post layout flow tree
+│  ├─ Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i1024px×b740px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(1024px×740px at (0px,0px)), paint: TypedRect(1024px×740px at (0px,0px)) } children=1
+│  │  ├─ ↑↑ Fragment for block: SpecificFragmentInfo::Generic(24) [] border_box=LogicalRect(H LTR, i1024px×b740px, @ (i0px,b0px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  ├─ Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i1024px×b18.633333333333333px, @ (i0px,b8px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(1008px×18.633333333333333px at (8px,0px)), paint: TypedRect(1008px×18.633333333333333px at (8px,0px)) } children=1
+│  │  │  ├─ ↑↑ Fragment for block: SpecificFragmentInfo::Generic(22) [] border_box=LogicalRect(H LTR, i1008px×b18.633333333333333px, @ (i8px,b0px)) margin=LogicalMargin(H LTR, i:8px..8px b:8px..8px) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  ├─ FlexFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i1008px×b18.633333333333333px, @ (i8px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(1008px×18.633333333333333px at (0px,0px)), paint: TypedRect(1008px×18.633333333333333px at (0px,0px)) } children=5 damage=REFLOW_OUT_OF_FLOW | REFLOW, main_mode: Inline, available_main_size: MinMax(SizeConstraint { min_size: 0px, max_size: None }), available_cross_size: MinMax(SizeConstraint { min_size: 0px, max_size: None }), lines: [FlexLine { range: 0..5, free_space: 650px, auto_margin_count: 0, cross_size: 18.633333333333333px }], items: [FlexItem { main_size: 150px, base_size: 150px, min_size: 0px, max_size: 17895697.05px, index: 0, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }, FlexItem { main_size: 52px, base_size: 52px, min_size: 0px, max_size: 17895697.05px, index: 1, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }, FlexItem { main_size: 52px, base_size: 52px, min_size: 0px, max_size: 17895697.05px, index: 2, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }, FlexItem { main_size: 52px, base_size: 52px, min_size: 0px, max_size: 17895697.05px, index: 3, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }, FlexItem { main_size: 52px, base_size: 52px, min_size: 0px, max_size: 17895697.05px, index: 4, flex_grow: 0, flex_shrink: 1, order: 0, is_frozen: true, is_strut: false }], main_reverse: false, is_wrappable: false, cross_reverse: false }
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i150px×b18.633333333333333px, @ (i65px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(164px×18.633333333333333px at (-14px,0px)), paint: TypedRect(164px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(1) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i150px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(150px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(150px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(0) ["one two three four"] border_box=LogicalRect(H LTR, i150px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i345px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(66px×18.633333333333333px at (-14px,0px)), paint: TypedRect(66px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(4) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(3) ["damer"] border_box=LogicalRect(H LTR, i52px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i527px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(66px×18.633333333333333px at (-14px,0px)), paint: TypedRect(66px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(7) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(6) ["damer"] border_box=LogicalRect(H LTR, i52px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i709px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(66px×18.633333333333333px at (-14px,0px)), paint: TypedRect(66px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(10) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(9) ["damer"] border_box=LogicalRect(H LTR, i52px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
+│  │  │  │  ├─ ListItemFlow { block_flow: Block sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i891px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(66px×18.633333333333333px at (-14px,0px)), paint: TypedRect(66px×18.633333333333333px at (-14px,0px)) } children=1 damage=REFLOW_OUT_OF_FLOW | REFLOW, marker_fragments: [SpecificFragmentInfo::ScannedText(13) ["•\u{a0}"] border_box=LogicalRect(H LTR, i14px×b18.616666666666667px, @ (i-14px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW | BUBBLE_ISIZES | REFLOW_OUT_OF_FLOW | REFLOW] }
+│  │  │  │  │  ├─ Inline sc=StackingContextId(0) pos=LogicalRect(H LTR, i52px×b18.633333333333333px, @ (i0px,b0px)),  floatspec-in=L 0px R 0px, floatspec-out=L 0px R 0px, overflow=Overflow { scroll: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)), paint: TypedRect(52px×18.616666666666667px at (0px,0.016666666666666666px)) }
+│  │  │  │  │  │  └─ SpecificFragmentInfo::ScannedText(12) ["damer"] border_box=LogicalRect(H LTR, i52px×b18.616666666666667px, @ (i0px,b0.016666666666666666px)) damage=REPOSITION | STORE_OVERFLOW
```
</details>

**Comment by emilio** [comment]
So, basically two more reflows are happening before the screenshot is taken.

**Comment by emilio** [comment]
Oh, I'm dumb, I got it, I think...

**Comment by jdm** [comment]
Is this going anywhere?

**Comment by emilio** [comment]
Yeah, I'd still want to figure out the failure and land it.

**Comment by emilio** [comment]
> exceptions.WindowsError: [Error 3] The system cannot find the path specified: u'c:\\buildbot\\slave\\windows-msvc-dev\\build\\target\\debug\\incremental\\script-1g52totqj6qac\\s-ex1p8h0sua-1w9qs9v-hbvaqqvv1zrk\\cgu-script-dom-bindings-codegen-Bindings-BluetoothCharacteristicPropertiesBinding-BluetoothCharacteristicPropertiesBinding.volatile.bc-compressed'

Sigh

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css/css-flexbox/flexbox_columns.html
  └   → /css/css-flexbox/flexbox_columns.html e038cebd05342d3dd4d4ddc05038107516f916c4
/css/css-flexbox/flexbox_columns-ref.html b162d7afebb1dac86e4f86aae00e6a06654fd405
Testing e038cebd05342d3dd4d4ddc05038107516f916c4 == b162d7afebb1dac86e4f86aae00e6a06654fd405
```
This consistently fails.

**Comment by emilio** [comment]
@SimonSapin I can't repro that test failure, and I'm pretty confident that if it was passing before it was just by chance. In any case, this is the right thing to do, as of right now Servo doesn't propagate the can_be_fragmented bit in any sort of right way, and this patch fixes it.

Mind if I land it with that test marked as failing?

**Comment by SimonSapin** [comment]
It indeed sounds likely that flexbox+multicol doesn’t actually work well together today. Making as failing sounds fine.

**Pull request merged**
