### PR TITLE
Resource task uses same port for initial headers + progress message.

### PR DESCRIPTION
**Pull request by glennw**
This doesn't change any functionality, but it is the first step to allowing resource loads to be multiplexed onto a single receiver.

It also means that resource loads only require one channel per load.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5695)

### CODE REVIEW

**Comment by jdm** [comment]
Given how much #5156 changes here, I'd like to hold off on this work until we get the async network stuff in place and reevaluate.

**Comment by glennw** [comment]
@jdm No probs. Once your PR lands I'll re-design / re-work this as required. In the mean time I'll keep adding commits here, but can easily split them into smaller independent PRs at a later time if that's easier.

**Comment by glennw** [comment]
Closing due to above PR landing - will re-open in smaller chunks based on the above PR.

**Pull request closed without merging**
