### PR TITLE
Remove runservo.sh for linux package

### PR DESCRIPTION
**Pull request by cbrewster**
We can use the package-prefs.json instead.
r? @aneeshusa 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12154)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
We should wait until #11983 is fixed before landing this. This will break running the package script twice in a row.

**Comment by aneeshusa** [comment]
I'm in favor of the core idea of removing `runservo.sh` and this code looks good at a first lookover, but I assume the swapping logic will change when #11983 is fixed, so I'll hold off on further review until then.

**Comment by aneeshusa** [comment]
This will also require a PR to https://github.com/servo/download.servo.org to fix the Linux instructions.

**Comment by aneeshusa** [comment]
#12850 was just merged, so this is no longer blocked.

**Comment by Coder206** [comment]
I apologize for the delay

**Comment by aneeshusa** [comment]
Also, any idea if we can get rid of the `runservo` for macOS as well?

**Comment by cbrewster** [comment]
closing in favor of #14737

**Pull request closed without merging**
