### PR TITLE
script: Move the layout_wrapper outside of script.

### PR DESCRIPTION
**Pull request by emilio**
This allows us to have ensure_data() and clear_data() functions on the TElement
trait, instead of hacking around it adding methods in random traits.

This also allows us to do some further cleanup, which I'd rather do in a
followup.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17744)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r=nox

 * Nox said this looked good to him, and the layout data side of things are just moving code around and the removal of the `DomTraversal::ensure_element_data/clear_element_data`, which were a hack.

**Comment by emilio** [comment]
@bors-servo r=nox

 * Unit tests

**Comment by bholley** [comment]
This is great. It also means that the servo-side fixup for style crate changes is more likely to happen in layout_thread, which has a much faster iteration time than script. Thanks emilio!

**Pull request merged**
