### PR TITLE
Cleanup/refactor build scripts for DOM codegen

### PR DESCRIPTION
**Pull request by frewsxcv**
Prior to this commit, the script codegen makefile relied on an
intermediary pythonpath.py file that handled python dependencies and
incorporated a couple hacks to get the codegen building working. This
commit removes that intermediary file and attempts to make the script
codegen build process cleaner.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7209)

### CODE REVIEW

**Comment by metajack** [comment]
Having worked on this before, this sounds great!

**Comment by Ms2ger** [comment]
Not sure how messing with `PYTHONPATH` globally is an improvement exactly.

**Comment by frewsxcv** [comment]
> Not sure how messing with PYTHONPATH globally is an improvement exactly.

[`export` is a special directive](http://www.gnu.org/software/make/manual/make.html#Variables_002fRecursion) in GNU Make that exports variables to sub-`make` commands; i.e. it shouldn't affect any shell variables of the user calling `make`. If that still doesn't

**Comment by metajack** [comment]
@bors-servo r+

Very nice cleanup.

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7209)

**Pull request merged**
