### PR TITLE
Add energy monitoring and characterization scripts

### PR DESCRIPTION
**Pull request by connorimes**
Add the energy-profiling feature.  Users can compile the proper (or their own) version of energymon libraries to capture power/energy data at runtime.  The results are accessed through heartbeats.

Additionally, there are a couple of python scripts to enable heartbeats for profiler categories and process the results into some visualizations to help understand how time and energy is being spent in Servo.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7581)

### CODE REVIEW

**Comment by connorimes** [comment]
Documentation will follow.

Cargo.lock files do not get updated for ports.  A bug in Cargo when using optional dependencies behind features?  I specified a git rev for the `energymon` dependency in the toml file instead.

r? @larsbergstrom

**Comment by larsbergstrom** [comment]
Reviewed 11 of 14 files at r1.
Review status: 11 of 14 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[tests/wpt/css-tests/css21_dev/html4/border-left-color-123.htm, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7581#-JynyQtwQRPa6bAzrXO4)** ([raw file](https://github.com/servo/servo/blob/3c25f47dbcfd39396298fdd9f229305676836118/tests/wpt/css-tests/css21_dev/html4/border-left-color-123.htm#L0)):</sup>
Why is this deleted?

---

<sup>**[tests/wpt/css-tests/css21_dev/html4/border-left-color-124.htm, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7581#-JynyTBoHigLNU2c30Lh)** ([raw file](https://github.com/servo/servo/blob/3c25f47dbcfd39396298fdd9f229305676836118/tests/wpt/css-tests/css21_dev/html4/border-left-color-124.htm#L0)):</sup>
Why is this deleted?

---

<sup>**[tests/wpt/css-tests/css21_dev/html4/border-left-color-125.htm, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7581#-JynyTtya0GEvzaV-fI9)** ([raw file](https://github.com/servo/servo/blob/3c25f47dbcfd39396298fdd9f229305676836118/tests/wpt/css-tests/css21_dev/html4/border-left-color-125.htm#L0)):</sup>
Why is this deleted?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7581)

**Comment by larsbergstrom** [comment]
@bors-servo r+

(the questions above appear to be a reviewable.io UI bug)

**Comment by jdm** [comment]
@bors-servo: retry
* #7422

**Pull request merged**
