### PR TITLE
Fix destination of cp in doc build.

### LINKED ISSUE #12964: upload_docs.sh is busted
http://build.servo.org/builders/doc/builds/1220/steps/shell/logs/stdio
```
make: Entering directory `/home/servo/buildbot/slave/doc/build/components/script'
make: makefile.cargo: No such file or directory
make: *** No rule to make target `makefile.cargo'.  Stop.
make: Leaving directory `/home/servo/buildbot/slave/doc/build/components/script'
```

CC @vvuk

### PR DESCRIPTION
**Pull request by jdm**
Fixes #12964.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13454)

### CODE REVIEW

**Comment by aneeshusa** [comment]
I've never liked `cd`ing during build scrips. Is it possible to change the cmake invocations to point at a different directory instead? i.e. like `cmake --build ./components/script/ --target supported-apis`?

**Comment by jdm** [comment]
@aneeshusa CMake appears to always generate the build system cache in the current working directory, so I can't figure out how to make that happen.

**Comment by aneeshusa** [comment]
That's disappointing; in that case, I think using a subshell for the `cd` and `cmake` commands would be nicer.

**Comment by aneeshusa** [comment]
Alternately, this is small enough that it's readable as is, so r=me either way.

**Comment by jdm** [comment]
I'd rather not spend more time messing around with the doc build until it's actually working again :)
@bors-servo: r=aneeshusa

**Pull request merged**
