### PR TITLE
Implement error reporting for workers.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13193)

### CODE REVIEW

**Comment by nox** [comment]
Two questions and maybe just as many follow-up issues, otherwise r=me.

-S-awaiting-review +S-awaiting-answer 

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 360 \[r1\]](https://reviewable.io:443/reviews/servo/servo/13193#-KR2sU1AYYjC2ch2qQnH:-KR2sU1BjsXJdQfTa4H5:bkg90jn) ([raw file](https://github.com/servo/servo/blob/a1dea38ea6562ad52ab7f7cdba0ea27296c4056c/components/script/dom/dedicatedworkerglobalscope.rs#L360)):*
> ```Rust
>         self.in_error_reporting_mode.set(true);
> 
>         // Steps 3-12.
> ```

Put a TODO for step 6? You don't seem to support it.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 372 \[r1\]](https://reviewable.io:443/reviews/servo/servo/13193#-KR2sb4KArV-uVmmiSsU:-KR2sb4KArV-uVmmiSsV:bp3vieq) ([raw file](https://github.com/servo/servo/blob/a1dea38ea6562ad52ab7f7cdba0ea27296c4056c/components/script/dom/dedicatedworkerglobalscope.rs#L372)):*
> ```Rust
> 
>         // Step 13.
>         let handled = !event.upcast::<Event>().fire(self.upcast::<EventTarget>());
> ```

Do you think we should change the return type of `Event::fire` to a more intelligible enum? The double negation here hurts my brain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13193#-:-KR2suiVrmhmKJQpl1bc:b-r8ag56)*

**Comment by Ms2ger** [comment]
Filed #13195 and #13196.

@bors-servo r=nox

**Pull request merged**
