### PR TITLE
WebGL Rendering Context - Fixed unnecessary unwrap calls for every send

### LINKED ISSUE #16021: WebGL rendering context should not unwrap every send
The implementation of the WebGL rendering context currently sends messages to another thread which is in charge of actually invoking the GL APIs. This code is riddled with `self.ipc_renderer.send(...).unwrap()` which means that any time the WebGL thread has an error that makes it panic, the web content thread also panics the next time it tries to communicate with the WebGL renderer. One of Servo's goals is to avoid problems like this, and an easy way to start is to replace the unwraps with `if self.ipc_renderer.send(...).is_err() {` instead, and add a warn! message that the renderer is unavailable (a helper method for this would be best to avoid duplication).

Code: `components/script/dom/webglrenderingcontext.rs`

It would be interesting to see the results of `./mach test-wpt tests/wpt/web-platform-tests/webgl` after these changes.

### PR DESCRIPTION
**Pull request by mrkajetanp**
### WebGL Rendering Context

* replaced unwrap() calls every send to ipc_renderer with if .. is_err()
* if error occurs, added a warning - "WebRenderer is unavailable!"
* functions will immediately return after the warning

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #16021  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because _____
I think they don't require additional tests because they're just meant to reduce possible thread panics if WebRenderer is not available for some reason.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16050)

### CODE REVIEW

**Comment by metajack** [comment]
The semantic change here is that previously these unwraps would panic if there was an error, but now we simply warn. Probably @glennw should weigh in on whether panics are appropriate or if we can relax them to warnings.

**Comment by jdm** [comment]
Don't we want Servo to be able to continue displaying the page even if something goes wrong in the WebGL rendering thread?

**Comment by metajack** [comment]
We do, but if the end result of this is that the renderer never recovers, it's not really much of an improvement. I haven't gone to look, but that part is already there, then the panics would indeed be unnecessary.

**Comment by CajetanP** [comment]
Well I guess if there are functions in which an error results in the renderer not being able to recover, we could panic!() instead of return in them.
I'm no expert but I think that even if that's the case for some functions, it doesn't apply to all of them.

**Comment by sviter** [comment]
What is the status of this PR?

**Comment by jdm** [comment]
It sounds like this change is not desired until we support recreating a failed renderer, unfortunately.

**Pull request closed without merging**
