### PR TITLE
Implements Node::isSameNode

### LINKED ISSUE #10746: Implement Node::isSameNode
Blocks #2185.

Fixing this bug will allow you to say you implemented one of the most useless features in the Web platform.

* Spec: <https://dom.spec.whatwg.org/#dom-node-issamenode>.
* Code: `components/script/dom/node.rs`, `components/script/dom/webidls/Node.webidl`.
* Test: to be [written](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) (at `dom/nodes/Node-isSameNode.html`).

### PR DESCRIPTION
**Pull request by amarant**
Fixes #10746

I adapted the tests from dom/nodes/Node-isEqualNode.html
should I also add ones for xhtml too like here : dom/nodes/Node-isEqualNode-xhtml.xhtml ?

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10761)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@bors-servo try

No, this is more than enough. You will need to update some expectations for `interfaces.html` (as reported by bors; let me know if you need help) and rebase over #10777, but otherwise this is good to go.

**Comment by Ms2ger** [comment]
```
  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: operation isSameNode(Node)

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: new Document() must inherit property "isSameNode" with the proper type (31)

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: calling isSameNode(Node) on new Document() with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: xmlDoc must inherit property "isSameNode" with the proper type (31)

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: calling isSameNode(Node) on xmlDoc with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: document.doctype must inherit property "isSameNode" with the proper type (31)

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: calling isSameNode(Node) on document.doctype with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: document.createDocumentFragment() must inherit property "isSameNode" with the proper type (31)

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: calling isSameNode(Node) on document.createDocumentFragment() with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: element must inherit property "isSameNode" with the proper type (31)

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: calling isSameNode(Node) on element with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: document.createTextNode("abc") must inherit property "isSameNode" with the proper type (31)

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: calling isSameNode(Node) on document.createTextNode("abc") with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: xmlDoc.createProcessingInstruction("abc", "def") must inherit property "isSameNode" with the proper type (31)

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: calling isSameNode(Node) on xmlDoc.createProcessingInstruction("abc", "def") with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: document.createComment("abc") must inherit property "isSameNode" with the proper type (31)

  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] Node interface: calling isSameNode(Node) on document.createComment("abc") with too few arguments must throw TypeError
```

(`scroll-to-top.html` is an intermittent)

**Comment by amarant** [comment]
I don't understand what went wrong ?

**Comment by jdm** [comment]
All of those PASS [expected FAIL] bits are tests that did not succeed before your changes. The text expectation files need to be [updated](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) to reflect the fact that they are now expected to succeed.

**Comment by amarant** [comment]
This is what I did with my last commit ammend, but the travis error of the new CI build is strange :

`Broadcast message from root@testing-gce-d1d1ce5e-48cd-4e0b-875f-29503086cd6b
	(unknown) at 19:12 ...
The system is going down for power off NOW!
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated`

**Comment by jdm** [comment]
I restarted it.

**Comment by Ms2ger** [comment]
Looks good, but needs a rebase.

**Comment by Ms2ger** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
