### PR TITLE
Move inline-block styling to user-agent and add button

### LINKED ISSUE #8064: <button> should be `display: inline-block`
https://html.spec.whatwg.org/multipage/rendering.html#the-button-element-2

### PR DESCRIPTION
**Pull request by badboy**
First Servo PR for me. \o/

Fixes #8064

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8070)

### CODE REVIEW

**Comment by pcwalton** [comment]
I guess this doesn't really affect any rendering, does it? Would be nice to add a reftest if it does.

**Comment by jdm** [comment]
It does affect things like `<button style="width: 200px">foo</button>`, which doesn't work without this change.

**Comment by badboy** [comment]
I can check out how the tests work and add one, just give me 1-2 days

**Comment by jdm** [comment]
A reftest that compares `<button style="width: 200px">foo</button> against `<input type="button" style="width: 200px" value="foo">` should do the trick.

**Comment by badboy** [comment]
Adding a reftest was surprisingly easy.

**Comment by frewsxcv** [comment]
@badboy Make sure the entry is alphabetized in the `basic.list` file

https://travis-ci.org/servo/servo/jobs/86299032

**Comment by jdm** [comment]
Sorry, there's a moratorium on adding new entries to basic.list. New reftests should be written as part of the WPT harness instead, in tests/wpt/mozilla/tests/css/.

**Comment by badboy** [comment]
Oops, okay

**Comment by badboy** [comment]
Force-pushed the new test now. I hope I got it right this time (I still couldn't run the test locally though)

**Comment by badboy** [comment]
I now also updated the test manifest and ran the test locally.

For reference:

```
# updating
./mach test-wpt --include _mozilla/css --manifest-update
# running the single test
./mach test-wpt --include _mozilla/css/button_css_width.html
```

**Comment by jdm** [comment]
Sorry for letting this slide. If you rebase it, I'll merge :)

**Comment by badboy** [comment]
Happy to do that. Just one thing: How to correctly update the manifest? Is the above correct? When I tried to rebase yesterday and then regenerate it with the above command it changed more than just adding the new test, so I'm unsure whether this is correct or not.

**Comment by jdm** [comment]
Yeah, it appears the manifest is not quite correct on master at the moment. If possible, just surgically add the changes that directly apply to your test to the manifest for now.

**Comment by badboy** [comment]
surgery it is then

**Comment by badboy** [comment]
Rebased on top of latest master & pushed. :)

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Pull request merged**
