### PR TITLE
Generate all Derived implementations in codegen

### PR DESCRIPTION
**Pull request by nox**
Follow-up of #7873.

@Ms2ger r? :)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8020)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 93 of 93 files at r1, 78 of 78 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/element.rs, line 122 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8020#-K0fsxMr4L0b7Xzs_rZU)** ([raw file](https://github.com/servo/servo/blob/f21c3928e1df18511d19b06935ff47ab82caf76d/components/script/dom/element.rs#L122)):</sup>
This would probably need `allow(unrooted_must_root)` if that lint worked.


---

<sup>**[components/script/dom/htmlelement.rs, line 55 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8020#-K0ftul5yHvfTEVV1FXC)** ([raw file](https://github.com/servo/servo/blob/f21c3928e1df18511d19b06935ff47ab82caf76d/components/script/dom/htmlelement.rs#L55)):</sup>
Or whitelist it in `unrooted_must_root.rs` if there's a lot of those.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8020)

**Comment by nox** [comment]
@Ms2ger Whitelisted all new_* functions.

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 
@bors-servo r+


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8020)

**Pull request merged**
