### PR TITLE
Profile: removed opts::get()

### PR DESCRIPTION
**Pull request by oneturkmen**
Removed opts::get() from `profile` component. **Note** that `profile_traits` component is the only component that uses single `opts::get().signpost` for IpcBytesReceiver and IpcReceiver structs, i.e. for recv() type method.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix *partially* #22854 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because these are cleanup changes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23521)

### CODE REVIEW

**Comment by jdm** [comment]
Some unit tests in tests/unit/profile/time.rs need to be updated as well. This can be tested with `./mach test-unit -p profile`.

**Comment by oneturkmen** [comment]
@jdm I fixed the unit tests, but appveyor fails to build. I guess it has to do something with [cygwin's persistent shared memory](https://stackoverflow.com/questions/18502999/git-extensions-win32-error-487-couldnt-reserve-space-for-cygwins-heap-win32). Do you think build restart/retry will help?

**Comment by oneturkmen** [comment]
PS. I did not touch the single opts::get() in components/profile_traits because it's used by `recv()`, which is in turn used throughout the codebase (not all, but it's reused in many places). I don't think we should touch it unless it's very necessary to do so (otherwise, there would probably be breaking changes).

**Comment by jdm** [comment]
Agreed, that will require some thought.
@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Pull request merged**
