### PR TITLE
Adds support for input element's maxlength attr

### PR DESCRIPTION
**Pull request by samfoo**
This implements maxlength [as described by whatwg](https://html.spec.whatwg.org/multipage/forms.html#dom-input-maxlength) for input elements.

Remaining work:
- WPT test - I have no idea how to write a WPT for simulating user input. Webdriver? Open to suggestions here.
- Support for textarea (should be trivial, probably worth filing another issue)

servo/servo#7320
servo/servo#7004

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7323)

### CODE REVIEW

**Comment by jdm** [comment]
Fun times! You've stumbled into a confusing, messy part of the spec; sorry about all of the weird edge cases that need to be supported :/
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlinputelement.rs, line 326 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-3qZmK19EbvI7SEJo)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/dom/htmlinputelement.rs#L326)):</sup>
We should be using a `make_int_getter` macro here (add a new one to http://mxr.mozilla.org/servo/source/components/script/dom/macros.rs#37).

---

<sup>**[components/script/dom/htmlinputelement.rs, line 334 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-4MUJJl3IOc6XwBl5)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/dom/htmlinputelement.rs#L334)):</sup>
We should be using a `make_limited_int_getter` macro here (add a new one like http://mxr.mozilla.org/servo/source/components/script/dom/macros.rs#166)

---

<sup>**[components/script/dom/htmlinputelement.rs, line 606 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jxzxed1-x1fA4bskK-t)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/dom/htmlinputelement.rs#L606)):</sup>
This should use a new from_limited_i32 API that results in AttrValue::Uint, since maxLength reflects a content attribute limited only to non-negative integers: https://html.spec.whatwg.org/multipage/forms.html#dom-input-maxlength . Additionally, this should be -1, according to https://html.spec.whatwg.org/multipage/infrastructure.html#limited-to-only-non-negative-numbers . Granted, Chrome returns 524288 for `document.createElement('input').maxLength`, which is delightful and deserving of its own test.

---

<sup>**[components/script/dom/htmltextareaelement.rs, line 97 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-6n3a_5L6rJgh_Tjc)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/dom/htmltextareaelement.rs#L97)):</sup>
This should be -1.

---

<sup>**[components/script/textinput.rs, line 199 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-9WWWycIoaD_Upd2O)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/textinput.rs#L199)):</sup>
As much as this makes sense conceptually, strictly enforcing the maximum length inside this component is not actually web-compatible. Setting the `value` attribute of an input element completely disregards any `maxLength` value that exists; it's only for the user-initiated input events that the limit should be consulted.

---

<sup>**[components/script/textinput.rs, line 203 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-908OVEENuWeq4v_v)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/textinput.rs#L203)):</sup>
Firefox replaces the selection with as much of the provided input string as possible, up to the enforced limit.

---

<sup>**[tests/unit/script/textinput.rs, line 120 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-9lXPsM1W1Uk-E3vy)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/tests/unit/script/textinput.rs#L120)):</sup>
Let's add a test for deleting content that already exists that is over the maximum length.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7323)

**Comment by samfoo** [comment]
Hurray!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlinputelement.rs, line 334 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-4MUJJl3IOc6XwBl5)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/dom/htmlinputelement.rs#L334)):</sup>
I assume you mean `make_limited_int_*setter*`. Because the max value has to be passed off to the textinput, it's not as simple as just setting a value on the node, I don't think a macro makes sense here, but I'm definitely not very familiar with the DOM code, so maybe I don't understand?

---

<sup>**[components/script/dom/htmlinputelement.rs, line 606 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jxzxed1-x1fA4bskK-t)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/dom/htmlinputelement.rs#L606)):</sup>
For the first bit: `from_limited_i32` surely must return an AttrValue::Int, right? Given the following scenario:

```html
<input type=text maxlength=-1></input>
```

What should `from_limited_i32` return? If it's an AttrValue::Int then `-1` makes sense. If it's an AttrValue::UInt... `i32::MAX`? There's not ability to return an Option in the current design.

For your second point: What should happen then in the following:

```js
var i = document.createElement('input')
i.maxLength = -100
```

The spec says to throw an `IndexSizeError`, but in servo, is there a mechanism for throwing errors based on a DOM value assignment? Is JS responsible for this, or is the DOM? Are there examples of other errors we throw as part of a DOM assignment? I scanned through and couldn't find anything.

---

<sup>**[components/script/textinput.rs, line 199 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-9WWWycIoaD_Upd2O)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/textinput.rs#L199)):</sup>
Setting the value from JS doesn't go through `replace_selection`. `set_content` should be the path through which the `value` attribute gets updated by scripts, and it doesn't use `maxlength` at all.

All the user input paths go through `replace_selection` which is why the limit is enforced here.

---

<sup>**[components/script/textinput.rs, line 203 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-908OVEENuWeq4v_v)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/textinput.rs#L203)):</sup>
This is in fact the implemented behaviour. See the test `test_single_line_textinput_with_max_length_doesnt_allow_appending_characters_when_replacing_a_selection`

This block is checking that, if I were to remove the selected text, and the content is still over the maxlength, then do nothing. This is consistent w/ how Firefox and Chrome work.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7323)

**Comment by jdm** [comment]
-S-needs-rebase -S-awaiting-review +S-needs-code-changes 

---

Reviewed 7 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlinputelement.rs, line 69 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy5ec4QGPwG440IZZZh)** ([raw file](https://github.com/servo/servo/blob/c5b07197b850b6d63b6cfddf5be9d912f87cf959/components/script/dom/htmlinputelement.rs#L69)):</sup>
I don't think this field is necessary?

---

<sup>**[components/script/dom/htmlinputelement.rs, line 334 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-4MUJJl3IOc6XwBl5)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/dom/htmlinputelement.rs#L334)):</sup>
Right, I did mean setter. However, the macro allows us to both store the attribute value as well as act on the new value since HTMLInputElement::after_set_attr will be called, which is where we can propagate it to TextInput.

---

<sup>**[components/script/dom/htmlinputelement.rs, line 606 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jxzxed1-x1fA4bskK-t)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/dom/htmlinputelement.rs#L606)):</sup>
I propose `from_limited_i32` return `Result<AttrValue::Uint, Error>`, and that we implement my plan described in #7461. That will enable us to throw an exception when appropriate, and avoid storing values that do not make sense. The `make_limited_int_getter` described earlier can take a `default` argument to return when no such attribute is present. Does that make sense?

---

<sup>**[components/script/textinput.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-9WWWycIoaD_Upd2O)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/textinput.rs#L0)):</sup>
Ah, my mistake! Perhaps a comment calling this out would be useful, in that case :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7323)

**Comment by samfoo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlinputelement.rs, line 597 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jxzxed1-x1fA4bskK-t)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/dom/htmlinputelement.rs#L597)):</sup>
I think I understanding you plan. Basically we change `parse_plain_attribute` to return a result instead of an `AttrValue`.

---

<sup>**[components/script/textinput.rs, line 195 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7323#-Jy-9WWWycIoaD_Upd2O)** ([raw file](https://github.com/servo/servo/blob/b39fac418147f0acb59d731ce9893a82f4e3dfb4/components/script/textinput.rs#L195)):</sup>
I've added a test for the set_content case (doh! should have had one before). I'll add a comment here as well.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7323)

**Comment by jdm** [comment]
With regards to http://logs.glob.uno/?c=mozilla%23servo#c267655; if the field now exists, then the test is no longer expected to fail and therefore the failure expectation should be removed.

**Comment by samfoo** [comment]
I am nervous that there's no end-to-end automation on this feature. I'm open to suggestions on how to write a test for actual user input (a WPT test using webdriver comes to mind), rather than just setting/getting DOM attributes.

**Comment by jdm** [comment]
Yeah, the situation is sucky for tests that require user interaction, unfortunately. WPT has the concept of manual tests, but by definition those don't get run on the build machines. Webdriver isn't working well enough with Servo yet to have a dedicated harness that automates input yet.

**Comment by jdm** [comment]
Adding a manual test to WPT might be the most effective way forward right now, if one doesn't already exist.

**Comment by jdm** [comment]
http://testthewebforward.org/docs/manual-test.html

**Comment by samfoo** [comment]
I've added a WPT manual test. Quite possibly in the wrong place, quite possibly a pretty crap test. I suppose it's better than nothing. I've limited the test to the absolute bare minimum, though obviously the use cases could be expanded if desired.

I don't fully understand the process for pushing new WPT tests upstream from servo, so I assume it's fine in the servo tree for now?

**Comment by jdm** [comment]
Yep, we sync with upstream regularly.

**Comment by jdm** [comment]
@ms2ger do you have any thoughts on the manual WPT test included in this PR?
@samfoo I appreciate the addition of the new unit tests, but I'd particularly like to see a WPT test that exercises the following cases:
* the value of input.maxLength for `<input>`
* the value of input.maxLength for `<input maxlength=-5>`
* the value of input.maxLength for `<input maxlength=foo>`
* the value of input.maxLength after `<input>.maxLength = -5`
Does that make sense?

---

Reviewed 28 of 28 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[tests/unit/script/attr.rs, line 19 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7323#-K-54qZCLW3FP-nbZ1fS)** ([raw file](https://github.com/servo/servo/blob/4c6c6fa2af29f57da3d2d0152a75897cc25e608a/tests/unit/script/attr.rs#L19)):</sup>
This can be
```rust
Ok(AttrValue::Int(_, result)) => ...,
Ok(_) => panic!("expeced a Int result"),
_ => panic!("expected a successful parse")
```

---

<sup>**[tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/maxlength-manual.html, line 25 \[r8\]](https://reviewable.io:443/reviews/servo/servo/7323#-K-56vyapKR92S_dyCTL)** ([raw file](https://github.com/servo/servo/blob/803243ca1dfcbe071e3cb43ead60f8b2527579a1/tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/maxlength-manual.html#L25)):</sup>
nit: remove the extra space before (

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7323)

**Comment by jdm** [comment]
Some of those tests I mentioned may already be covered by http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/html/dom/reflection.js#346 . I'm not sure if they test the case for parser-set attributes, however (ie. `<input maxlength=-5>`).

**Comment by Ms2ger** [comment]
I don't particularly care either way about manual tests; they don't matter for the CI use cases that matter to me.

The existing wpt reflection tests don't test parser-set attributes AFAIK. Is there a particular reason that they'd be handled specially here?

**Comment by samfoo** [comment]
The behaviours are subtly different, since setting a negative `maxLength` from the parser shouldn't cause an error. I'd be happy to write the WPT tests you're suggesting @jdm, but... The organisation of the WPT tests remains a bit of a mystery to me.

1. Where should such a test HTML file go in the WPT hierarchy?
2. Where does a new file get added to the list of WPT tests to run as part of CI?

**Comment by jdm** [comment]
When in doubt, you can add a test to `tests/wpt/mozilla/wpt`. Generally, test locations in tests/wpt/web-platform-tests/ conform to relevant parts of the specification, so this one could go in http://mxr.mozilla.org/servo/source/tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/ . As for adding it to the list of tests that get run, I could have sworn that was documented in http://mxr.mozilla.org/servo/source/tests/wpt/README.md but apparently not. You can either add it to `MANIFEST.json` manually, or use `./mach test-wpt --manifest-update path/to/test/file` to do it automatically.

**Comment by jdm** [comment]
I'm going to review this today. Sorry about the long wait.

**Comment by eefriedman** [comment]
The way this PR changes the signature of parse_plain_attribute is very wrong.  The IDL getters and setters don't affect the basic DOM semantics, which is that you're allowed to set any attribute of any element to an arbitrary value.  getAttribute and setAttribute aren't affected by the HTML rules for any specific attribute.

**Comment by jdm** [comment]
Erk, you're right. `input.setAttribute('maxLength', -5)` doesn't trigger the error in Firefox.

**Comment by jdm** [comment]
For reference, here's the testcase I've run against Firefox, Chrome, and Safari so far, which all agree on behaviour except for the value the getter returns for a negative attribute value: http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=3746

**Comment by jdm** [comment]
Ok, it appears my earlier suggestion about parse_plain_attribute was off base, exactly the way @eefriedman described. `make_limited_int_setter` correctly checks the provided value and throws the exception per spec, so all of the rest of our attribute-setting infrastructure appears to be operating as expected when compared against the results from my earlier testcase.

**Comment by jdm** [comment]
As mentioned in the previous coment, we'll need to undo the changes to parse_plain_attribute and from_limited_i32, unfortunately. Sorry for sending you down that road :( Sorry again about the huge delay in getting back to this PR. This is important infrastructure that you've added here!
-S-awaiting-review -S-needs-rebase 


---

Reviewed 26 of 26 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/maxlength.html, line 51 \[r11\]](https://reviewable.io:443/reviews/servo/servo/7323#-K2rlVhqoG-nafSgfWcP)** ([raw file](https://github.com/servo/servo/blob/e7d8fcbcedb2d9de639a128052d2b67ae835c949/tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/maxlength.html#L51)):</sup>
This can use `assert_throws`: http://testthewebforward.org/docs/testharness-library.html#assert_throws-code-func-description-


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7323)

**Comment by samfoo** [comment]
No worries. I'm currently abstaining from technology while I work on some other projects. This PR is not forgotten. I'll pick it up again in a few weeks.

**Comment by samfoo** [comment]
Slamakow :hand:

Sorry about the delay. In addition to the WPT tests that now pass, this works with your small test case.

```
<input maxlength="5">
5
5
5
5
<input maxlength="0">
0
0
0
0
<input maxlength="-0">
0
0
-0
-0
<input maxlength="-5">
-1
-1
-5
-5
<input>
caught using =
5
5
5
5
<input>
didn't catch using setAttribute
-1
-1
-5
-5
```

**Comment by jdm** [comment]
Thank you for addressing my comments, and thanks for your patience during this process! This is ready to merge, except that the MANIFEST.json changes aren't idempotent right now (ie. the automatic manifest update tool would make different changes than the ones you made: https://travis-ci.org/servo/servo/jobs/94322761). Once you incorporate those changes we can merge this!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 29 of 29 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7323#-:-K4W77OEZBj8FiySoFR4:760858903)*

**Comment by samfoo** [comment]
Wow. That's embarrassing :blush:. I must not have run the unit tests after saving a file or something.

**Pull request merged**
