### PR TITLE
Fix hit testing to take into account nested stacking contexts #12777

### LINKED ISSUE #12833: Hit test regression on browser.html newtab page
Found on latest nightly (8/11/16)
Steps to reproduce:
1. Open browser.html
2. Try to click on the Hacker News tile
3. It takes you to the Moire Demo

If you move the mouse around, you can see that the hit test is off.

### PR DESCRIPTION
**Pull request by emilio**
Fixes #12833.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12833 (github issue number if applicable).

- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12841)

### CODE REVIEW

**Comment by emilio** [comment]
@jdm: I was so dumb that I didn't pass the transformed point into the children sc. I'm scared no test caught this.

**Comment by emilio** [comment]
That's a know intermittent, but just to make sure: @bors-servo: try

**Comment by KiChjang** [comment]
Looks like this was never merged, and requires a rebase now.

**Pull request merged**
