### PR TITLE
Implement TextDecoder

### LINKED ISSUE #4769: Implement TextDecoder.
Spec: <https://encoding.spec.whatwg.org/#interface-textdecoder>.

Most of the actual decoding infrastructure should already be implemented in `rust-encoding`.

This includes enabling the relevant tests by adding
```ini
[encoding]
  skip: false
```
to `tests/wpt/include.ini`.

This may also include updating the `mozjs` and `rust-mozjs` dependencies to ensure we can work with typed arrays.

### PR DESCRIPTION
**Pull request by KiChjang**
This is a work-in-progress to fix #4769, right now most of the functionality is in place, but details of the implementation needs to be ironed out, especially for the Decode method.

### CODE REVIEW

**Comment by jdm** [comment]
This doesn't compile right now - there's a reference to `fatal` in `Decode` that won't resolve to anything.

**Comment by metajack** [comment]
Assigning to @glennw to figure out next steps. Looks like changes were made and need reviewing.

**Comment by jdm** [comment]
Nope, all of the commits have been reviewed on Critic. It's just a matter of addressing them now.

**Comment by metajack** [comment]
@KiChjang Are you planning on addressing these soon?

**Comment by KiChjang** [comment]
Unfortunately not, I am stuck with the implementation of the Decode method.

**Comment by jdm** [comment]
@KiChjang What's the problem you're stuck on?

**Comment by KiChjang** [comment]
For the WebIDL implementation of TextDecoder, a BufferSource/ArrayBuffer is required as an argument to the decode method, but these SpiderMonkey arguments are still not supported yet.

**Comment by jdm** [comment]
Oh right - why don't you try using an `object` argument, and returning early if `JS_IsArrayBufferObject(input)` is false?

**Comment by KiChjang** [comment]
That does not work either; `object` arguments are not supported. I haven't checked whether the latest commit on the master branch enables me to do so though, if so I might have to rebase.

**Comment by jdm** [comment]
FWIW, adding `object` support to the codegen is likely much easier than ArrayBuffer right now: http://mxr.mozilla.org/mozilla-central/source/dom/bindings/Codegen.py#5208 for reference.

**Comment by jdm** [comment]
A lot of the code in handleJSObjectType isn't applicable to us right now - we just take a `*mut JSObject` argument, and we can just assert the particular conditions we're trying to handle right here.

**Comment by Ms2ger** [comment]
Implemented object in #5569.

**Comment by Ms2ger** [comment]
Rebased as https://github.com/servo/servo/pull/5599

**Pull request closed without merging**
