### PR TITLE
Run our reftests with wptrunner

### PR DESCRIPTION
**Pull request by initsecret**
#5618, It allows us to run reftests using wptrunner

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6898)

### CODE REVIEW

**Comment by jdm** [comment]
This is a great effort! However, there's an important piece missing - the addition of the `<link>` that tells the test harness which file to compare against. This is also why I don't see any changes to MANIFEST.json, I think. Also, the output would be much easier to read if we let git know about the file moves with `git mv`, rather than copying them to the new folder. Does that make sense?

**Comment by s142857** [comment]
yup, I will update the manifest.json, sorry i forgot about it,
I have no idea about git mv, could you help me

**Comment by jdm** [comment]
If you're not afraid of spending time to learn lots of new things, I think it should be fine :)

MANIFEST.json is automatically updated by running the `test-wpt` mach command with `--manifest-update`. However, it will only update the file if it sees new tests that include changes like [https://github.com/servo/servo/pull/5687/files#diff-b7983c29eb43fd95994bf5386665018aR4](this) - does that make sense?

As for using `git mv`, does [this page](http://githowto.com/moving_files) answer your question?

**Comment by s142857** [comment]
the github link is broken

**Comment by s142857** [comment]
As for the move, i used git add instead for the time being to ensure backwards compatibility, if it wont cause any issues i will remove it from ref

**Comment by jdm** [comment]
It's a lot easier to review the changes if `git mv` is used :) The github link is fixed now, thanks.

**Comment by s142857** [comment]
but what if someone wanted to run the ref tests the old way, 

PS the link still dosent work
https://github.com/servo/servo/pull/5687/files#diff-b7983c29eb43fd95994bf5386665018aR4

**Comment by jdm** [comment]
The point of this change is that the old way is strictly worse than the new way, so we want to convert all of the tests to the new way. As for the link problem, the one in my comment and your link both work for me :/

**Comment by s142857** [comment]
ok you want me to reset and use git mv or 
can I use git rm

**Pull request closed without merging**
