### PR TITLE
Upgrade wptrunner

### PR DESCRIPTION
**Pull request by jdm**
This gets us back to a pristine local copy and allows us to start experimenting with webdriver tests.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13614)

### CODE REVIEW

**Comment by jdm** [comment]
cc @jgraham for the previous failure:
```
STDERR: /Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py:161: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if c == "\\":
STDERR: /Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py:163: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif c == "]":
Error running mach:

    ['test-wpt', '--release', '--processes', '8', '--total-chunks', '2', '--this-chunk', '2', '--log-raw', 'test-wpt.log', '--log-errorsummary', 'wpt-errorsummary.log']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 0: ordinal not in range(128)

  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/python/servo/testing_commands.py", line 396, in test_wpt
    return self.run_test_list_or_dispatch(kwargs["test_list"], "wpt", self._test_wpt, **kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/python/servo/testing_commands.py", line 407, in run_test_list_or_dispatch
    return correct_function(**kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/python/servo/testing_commands.py", line 402, in _test_wpt
    return self.wptrunner(run_file, **kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/python/servo/testing_commands.py", line 466, in wptrunner
    return run_globals["run_tests"](**kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/run_wpt.py", line 13, in run_tests
    return run.run_tests(paths=paths, **kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/run.py", line 36, in run_tests
    success = wptrunner.run_tests(**kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptrunner.py", line 135, in run_tests
    **kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptrunner.py", line 71, in get_loader
    include_https=ssl_env.ssl_enabled)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/testloader.py", line 460, in __init__
    self._load_tests()
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/testloader.py", line 526, in _load_tests
    for test_path, test_type, test in self.iter_tests():
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/testloader.py", line 511, in iter_tests
    inherit_metadata, test_metadata = self.load_metadata(manifest_file, metadata_path, test_path)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/testloader.py", line 494, in load_metadata
    metadata_path, test_path, test_manifest.url_base, self.run_info)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/manifestexpected.py", line 236, in get_manifest
    url_base=url_base)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/backends/static.py", line 221, in compile
    return compile_ast(parse(stream),
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py", line 747, in parse
    return p.parse(stream)
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py", line 511, in parse
    self.manifest()
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py", line 527, in manifest
    self.data_block()
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py", line 547, in data_block
    self.data_block()
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py", line 539, in data_block
    self.consume()
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py", line 515, in consume
    self.token = self.token_generator.next()
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py", line 102, in tokenize
    for token in tokens:
  File "/Users/servo/buildbot/slave/mac-rel-wpt2/build/tests/wpt/harness/wptrunner/wptmanifest/parser.py", line 168, in heading_state
    rv += c
program finished with exit code 1
```
I couldn't reproduce it locally.

**Comment by jgraham** [comment]
Try reverting 496353104e7ee0969e316c12caf3dc2988efb8e8 in the wptrunner repo (just a guess).

**Comment by jdm** [comment]
@jgraham reverting that commit did the trick.

**Comment by jgraham** [comment]
@Ms2ger: apparently things are never simple :(

**Comment by Ms2ger** [comment]
So it clearly is.

@bors-servo r+

**Comment by Ms2ger** [comment]
I'll try to figure out what's wrong after this lands.

**Comment by jdm** [comment]
@bors-servo: r-
A couple files are missing.

**Comment by Ms2ger** [comment]
https://github.com/w3c/wptrunner/pull/216 fixes the error seen here.

**Pull request merged**
