### PR TITLE
Fix infinite loop in flexbox algorithm

### LINKED ISSUE #29852: Infinite loop with flexbox in layout-2020
This causes an infinite loop:

```html
<div style="display: flex; width: 0px">
  <div style="flex: 1 1 0px; margin: 1px"></div>
</div>
```

The reason is that the spec is not avoiding a `0 / 0` division, so servo ends up with NaN lengths and the algorithm doesn't advance as expected. See https://github.com/w3c/csswg-drafts/issues/8928

### PR DESCRIPTION
**Pull request by nicoburns**
Only apply step 5c of "resolve flexible lengths" if sum of scaled flexible shrink factors > 0
Probably fixes #29852 (but speculative as I can't get mach to run).

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by nicoburns** [comment]
That looks like it's working to me (TIMEOUT's turning into OK/FAIL seems like what I would expect if an infinite loop bug is fixed).

**Review by Loirooriol — APPROVED** [review]
Thanks, I agree this seems the most reasonable solution

**Pull request merged**
