### PR TITLE
Hoist channel creation out of loop in handle_is_ready_to_save_image

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11313)

### CODE REVIEW

**Comment by nox** [comment]
Not sure how much it is an improvement.

r? @mbrubeck

**Comment by mbrubeck** [comment]
@bors-servo r+

I think this is worth doing, since it seems like creating huge numbers of IPC channels may be costly.  It does mean that the other end *must* send exactly one reply to each message, but this shouldn't be a problem in practice.

In the long term, maybe we should also consider using a pool of IPC channels?

**Comment by jdm** [comment]
@bots-servo: r-
CI doesn't take like it.

**Comment by nox** [comment]
@mbrubeck @jdm Had to create two IPC channels. You decide whether this patch is still worth it.

**Comment by jdm** [comment]
Seems reasonable.

**Pull request merged**
