### PR TITLE
Rustfmt some of script.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8569)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

While most of these are great, some seem questionable. I suppose having a definitive style enforced outweighs the potential perfection.

The one that bothers me most I guess is one function arg per line when it must get line split. In many cases hte function arguments fit together like clientX, clientY, screenX, screenY, and so could be two-combined instead of singletons on a line. There's no way for an automated script to know that though, and perhaps this is just my personal organizational preference anyway.

---

Reviewed 50 of 50 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8569#-:-K3LQ-CfS_odPnfxfv73:1519963590)_

**Comment by frewsxcv** [comment]
Also, tidy failed

**Comment by Ms2ger** [comment]
Arguably, those should take `Point` types.

**Pull request merged**
