### PR TITLE
Add Bluetooth device support

### PR DESCRIPTION
**Pull request by dati91**
Basic implementation of a simple Bluetooth API
Only supports linux (dbus/bluez) for now

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9839)

### CODE REVIEW

**Comment by Manishearth** [comment]
Should this be an out-of-tree crate? cc @larsbergstrom

**Comment by larsbergstrom** [comment]
@dati91 Will this crate have dependencies on in-Servo types (e.g., DOM stuff)? If not, we might want to move it out into a separate `devices` crate.

**Comment by jdm** [comment]
The discussion on IRC seemed to result in agreement that this could exist separately, so let's go ahead and do that. No need for this PR in that case.

**Comment by Manishearth** [comment]
Should I create a `servo/devices` repo?

**Comment by jdm** [comment]
Sure.

**Comment by Manishearth** [comment]
Done, and gave @dati91 push access https://github.com/servo/devices

**Comment by Manishearth** [comment]
https://github.com/servo/devices/pull/1

**Pull request closed without merging**
