### PR TITLE
M1502: Improve HTTP monitoring devtool support

### PR DESCRIPTION
**Pull request by akumar21NCSU**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8216)

### CODE REVIEW

**Comment by jdm** [comment]
Great work! Most of my comments that I've left are style issues or things that could be written more clearly!
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 9 of 9 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

<sup>**[components/net/http_loader.rs, line 5 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dNgCVIbnPCk8k9bbx)** ([raw file](https://github.com/servo/servo/blob/72ba7e787bb9cb4f77623d47742bb6eeca0f4ec1/components/net/http_loader.rs#L5)):</sup>
Let's move this to lib.rs with the other ones.


---

<sup>**[components/net/http_loader.rs, line 42 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dNj2WVfcz0E7WYlfI)** ([raw file](https://github.com/servo/servo/blob/72ba7e787bb9cb4f77623d47742bb6eeca0f4ec1/components/net/http_loader.rs#L42)):</sup>
This doesn't need the `self::` with the previous change.


---

<sup>**[components/net/http_loader.rs, line 597 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dR7QjPGAQ05s_Qt85)** ([raw file](https://github.com/servo/servo/blob/2ae7bdfe3370961509b779c49cf426e29ac10764/components/net/http_loader.rs#L597)):</sup>
Let's remove this comment.


---

<sup>**[components/net/http_loader.rs, line 603 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dRBlgtJSRtxm5e2xe)** ([raw file](https://github.com/servo/servo/blob/2ae7bdfe3370961509b779c49cf426e29ac10764/components/net/http_loader.rs#L603)):</sup>
These three lines of arguments should be indented by four spaces.


---

<sup>**[components/net/http_loader.rs, line 449 \[r8\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dRPUiaa4CbF291tBz)** ([raw file](https://github.com/servo/servo/blob/cd1a57d44360871fa59f4ad579acff428e2f50d9/components/net/http_loader.rs#L449)):</sup>
Let's style this like:
```rust
let request = DevtoolsHttpRequest {
    url: url, method: method, headers: headers, body: body, pipeline_id: pipeline_id
};
<!-- Reviewable comment -K1dRPUiaa4CbF291tC-:1829668303 -->

---

<sup>**[tests/unit/net/http_loader.rs, line 5 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dPwRQ7QsJ26hEoGpW)** ([raw file](https://github.com/servo/servo/blob/2757762fd6526523c3c67edc16883004e7dc822f/tests/unit/net/http_loader.rs#L5)):</sup>
Let's move this to lib.rs with the others.
<!-- Reviewable comment -K1dPwRQ7QsJ26hEoGpX:640999908 -->

---

<sup>**[tests/unit/net/http_loader.rs, line 30 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dPy9aySVcjppwP-pa)** ([raw file](https://github.com/servo/servo/blob/2757762fd6526523c3c67edc16883004e7dc822f/tests/unit/net/http_loader.rs#L30)):</sup>
Remove `self::` after the previous change.
<!-- Reviewable comment -K1dPy9aySVcjppwP-pb:-592860963 -->

---

<sup>**[tests/unit/net/http_loader.rs, line 388 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dQ6KWdA3PkLgvS080)** ([raw file](https://github.com/servo/servo/blob/2757762fd6526523c3c67edc16883004e7dc822f/tests/unit/net/http_loader.rs#L388)):</sup>
No need for this local value; just inline `Some(pipeline_id)` in the next line.
<!-- Reviewable comment -K1dQ6KWdA3PkLgvS081:1055405241 -->

---

<sup>**[tests/unit/net/http_loader.rs, line 459 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dQcbiDnvSRyvLb3tY)** ([raw file](https://github.com/servo/servo/blob/2757762fd6526523c3c67edc16883004e7dc822f/tests/unit/net/http_loader.rs#L459)):</sup>
No need to clone here, and we can just inline `None` instead of creating the `optional` value.
<!-- Reviewable comment -K1dQcbiDnvSRyvLb3tZ:698981802 -->

---

<sup>**[tests/unit/net/http_loader.rs, line 461 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dQWLCuy_zugkxNrdC)** ([raw file](https://github.com/servo/servo/blob/2757762fd6526523c3c67edc16883004e7dc822f/tests/unit/net/http_loader.rs#L461)):</sup>
This isn't necessary in this test. We can use the default headers in the LoadData value.
<!-- Reviewable comment -K1dQWLCuy_zugkxNrdD:1748514078 -->

---

<sup>**[tests/unit/net/http_loader.rs, line 468 \[r8\]](https://reviewable.io:443/reviews/servo/servo/8216#-K1dRmAb8T0D3hODj4r_)** ([raw file](https://github.com/servo/servo/blob/cd1a57d44360871fa59f4ad579acff428e2f50d9/tests/unit/net/http_loader.rs#L468)):</sup>
This can be `assert!(devtools_port.try_recv().is_error())`.
<!-- Reviewable comment -K1dRmAb8T0D3hODj4ra:-543670351 -->

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8216)
<!-- Sent from Reviewable.io -->

**Comment by jdm** [comment]
Lovely! We just need to clean up the remaining errors from `./mach test-tidy`, and [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) all the changes into one.
-S-awaiting-review -S-needs-rebase +S-fails-tidy +S-needs-squash 


---

Reviewed 9 of 9 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8216)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 4 of 4 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8216)

**Comment by eefriedman** [comment]
```
---- http_loader::test_request_and_response_data_with_network_messages stdout ----
	thread 'http_loader::test_request_and_response_data_with_network_messages' panicked at 'assertion failed: `(left == right)` (left: `HttpRequest { url: Url { scheme: "https", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("mozilla.com"), port: None, default_port: Some(443), path: [""] }), query: None, fragment: None }, method: Get, headers: Headers { User-Agent: Test-agent, Accept: text/html, application/xhtml+xml, application/xml; q=0.9, */*; q=0.8, Accept-Encoding: gzip, deflate, br, Host: mozilla.com, }, body: None, pipeline_id: PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) } }`, right: `HttpRequest { url: Url { scheme: "https", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("mozilla.com"), port: None, default_port: Some(443), path: [""] }), query: None, fragment: None }, method: Get, headers: Headers { User-Agent: Test-agent, Host: mozilla.com, Accept-Encoding: gzip, deflate, Accept: text/html, application/xhtml+xml, application/xml; q=0.9, */*; q=0.8, }, body: None, pipeline_id: PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) } }`)', /Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/http_loader.rs:433
stack backtrace:
   1:        0x102115d28 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s
   2:        0x10211782f - panicking::log_panic::_<closure>::closure.38923
   3:        0x1021172fc - panicking::log_panic::h87af6096e0b6fa7c4Uw
   4:        0x1021097b6 - sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r
   5:        0x102109b9e - sys_common::unwind::begin_unwind_fmt::he992719329bdd2c6x7r
   6:        0x101e1578b - http_loader::test_request_and_response_data_with_network_messages::h4823d798daf0308cVRc
   7:        0x1020b8edb - boxed::_<impl>::call_box::call_box::h1439439458556714188
   8:        0x1020bb62d - boxed::_<impl>::call_box::call_box::h8069092559954270103
   9:        0x1020b9832 - sys_common::unwind::try::try_fn::try_fn::h11324081254561251759
  10:        0x1021151f8 - __rust_try
  11:        0x102112dce - sys_common::unwind::try::inner_try::hc13d8e198528cd0fZ4r
  12:        0x1020b99e2 - boxed::_<impl>::call_box::call_box::h6022582708213645161
  13:        0x102116bfd - sys::thread::_<impl>::new::thread_start::h906ddce3a93d4852ksw
  14:     0x7fff8416a059 - _pthread_body
  15:     0x7fff84169fd6 - _pthread_start


failures:
    http_loader::test_request_and_response_data_with_network_messages

test result: FAILED. 149 passed; 1 failed; 0 ignored; 0 measured
```

**Comment by jdm** [comment]
Ah, I see the issue - we changed the default headers in #8192, so https://github.com/servo/servo/pull/8216/files#diff-c007a862cc2c468a1b2ae7aa7707e35dR400 needs to be updated to include the "br" encoding.

**Comment by akumar21NCSU** [comment]
@jdm Thanks. I have changed default headers accordingly.

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Pull request merged**
