### PR TITLE
Normalize rotations in computed transforms

### LINKED ISSUE #13265: Normalize rotations in computed transforms
While the spec doesn't explicitly say this, it seems like the `rotate3d()` and `rotate()` primitives should be stored in normalized form.

https://drafts.csswg.org/css-transforms/#funcdef-rotate3d

It refers to them as "direction vectors" which are by definition normalized. Current servo behavior is that `rotate3d(0.707,0.707,0,45deg);` and `rotate3d(1,1,0,45deg);` are different, which doesn't match other browsers.

We should probably just normalize before we create a `ComputedOperation::Rotate`.

cc @canaltinova

### PR DESCRIPTION
**Pull request by canova**
Normalize rotations in computed transforms.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13265  (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13275)

### CODE REVIEW

**Comment by Manishearth** [comment]
r=me on changes, if tests pass.

Once we know the tests pass we'd need to add a new test if it's not tested already.

**Comment by Manishearth** [comment]
@bors-servo delegate+

Use this to trigger try yourself, but please don't r+ until your own test is added

**Comment by canaltinova** [comment]
@Manishearth Ok, thanks!

**Comment by Manishearth** [comment]
Looks like the CSS tests passed, that's just an intermittent. http://build.servo.org/builders/mac-rel-css/builds/3003

Could you add a new test to mozilla/ that ensures that rotate3d(1,1,1,45deg) is the same as rotate3d(0.5,0.5,0.5,45deg)?

**Comment by canaltinova** [comment]
Added a test. Could you r? @Manishearth

**Pull request merged**
