### PR TITLE
Fix misspelled "get_suported_extensions" function

### LINKED ISSUE #21122: In WebGLExtensions struct, misspelled method name 'get_suported_extensions'; should be 'get_supported_extensions'
This is a very small issue, but the WebGLExtensions struct (in `components/script/dom/webgl_extensions/extensions.rs`) has a spelling error in it's method `get_suported_extensions`; it should be `get_supported_extensions` ([link](https://github.com/servo/servo/blob/3c43fa6b1ddf815b95f8924640228587304ede01/components/script/dom/webgl_extensions/extensions.rs#L146)). The only usage I could find of this method was in `components/script/dom/webglrenderingcontext.rs` ([link](https://github.com/servo/servo/blob/3c43fa6b1ddf815b95f8924640228587304ede01/components/script/dom/webglrenderingcontext.rs#L1539)).

If nobody has any objections, I can make a PR.

### PR DESCRIPTION
**Pull request by dralley**
closes #21122

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by dralley** [comment]
CI issue?

**Comment by jdm** [comment]
Yes.

**Pull request merged**
