### PR TITLE
doc/howto install: Fedora replaces yum with dnf

### PR DESCRIPTION
**Pull request by genodeftest**
According to the official change set [1] for Fedora 22 which will be released in some days [2] yum will be replaced by dnf. The syntax is basically the same (in these simple cases here it is exactly the same, tested with dnf). After that only Fedora 21 and 22 will be supported, both come with dnf shipped by default.

[1] https://fedoraproject.org/wiki/Releases/22/ChangeSet#Replace_Yum_With_DNF
[2] https://fedoraproject.org/wiki/Releases/22/Schedule?rd=Releases/22

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6079)

### CODE REVIEW

**Comment by genodeftest** [comment]
I hope I got it right, I'm still not used to git.

**Comment by jdm** [comment]
Yep, that worked. Can you squash these commits together? http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by genodeftest** [comment]
Sorry, doesn't look like I understand how to squash these commits.

**Comment by jdm** [comment]
Rebased in #6163.

**Pull request closed without merging**
