### PR TITLE
Update clippy, improve clippy integration

### PR DESCRIPTION
**Pull request by Manishearth**
This makes it much easier to run rustfix on servo

(rustfix is still pretty buggy though)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12409)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r-
Travis is displeased.

**Comment by Manishearth** [comment]
@bors-servo r=nox

fixed tidy

**Comment by Manishearth** [comment]
Sadly rustfix isn't too ready yet (a couple of crashes, and it messes up indentation), and clippy needs to improve its suggestions, so I wasn't able to do a proper fixing sweep. I'll try rustfix on some of our smaller crates later and go on from there.

**Comment by Wafflespeanut** [comment]
compile tests seem to have failed.

**Comment by Manishearth** [comment]
@bors-servo r=nox

I undid the change that only runs the plugins on script. Plugins take a fraction of a second for us, so it's no big deal.

**Comment by Manishearth** [comment]
@bors-servo retry

 - #11631

**Pull request merged**
