### PR TITLE
Simplify and improve Pipeline creation.

### PR DESCRIPTION
**Pull request by Ms2ger**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because refactoring

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11437)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Looks good, some minor nits.

<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> r? @asajeffrey 
</details>


---

Reviewed 1 of 2 files at r3, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[components/constellation/constellation.rs, line 40 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIhjJEdyaOfEdBucRfu:-KIhjJEdyaOfEdBucRfv:-531469967) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/constellation.rs#L40)):*
> ```Rust
> use net_traits::{self, ResourceThreads, IpcSend};
> use offscreen_gl_context::{GLContextAttributes, GLLimits};
> use pipeline::{ChildProcess, InitialPipelineState, Pipeline};
> ```

Are we ever actually using `ChildProcess` in the contellation? We are keeping a vector of them, but as far as I can tell, never actually doing anything with it.

---

*[components/constellation/constellation.rs, line 408 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIhjz6ZRr-aUNmaxDsu:-KIhjz6ZRr-aUNmaxDsv:-1787041393) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/constellation.rs#L408)):*
> ```Rust
>                     initial_window_size: Option<TypedSize2D<PagePx, f32>>,
>                     script_channel: Option<IpcSender<ConstellationControlMsg>>,
>                     load_data: LoadData) {
> ```

This function is now a lot nicer!

---

*[components/constellation/constellation.rs, line 432 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIhjbUzy2M10dGwVmZy:-KIhjbUzy2M10dGwVmZz:297309435) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/constellation.rs#L432)):*
> ```Rust
>         });
> 
>         let (pipeline, child_process) = match result {
> ```

if we don't actually use the child process we could just make this a `Result<Pipeline>`.

---

*[components/constellation/pipeline.rs, line 41 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIhk4s8BCMa3KjfimW-:-KIhk4s8BCMa3KjfimW0:-64677315) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/pipeline.rs#L41)):*
> ```Rust
> use webrender_traits;
> 
> pub enum ChildProcess {
> ```

Make this private? Or just get rid of it, as I don't see where it's being used.

---

*[components/constellation/pipeline.rs, line 186 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIhhOx8ZGSvXunduG0p:-KIhhOx8ZGSvXunduG0q:1627221039) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/pipeline.rs#L186)):*
> ```Rust
>         if let Some((script_port, pipeline_port)) = content_ports {
>             // Route messages coming from content to devtools as appropriate.
>             let script_to_devtools_chan = state.devtools_chan.as_ref().map(|devtools_chan| {
> ```

@nox would tell you off for side-effecting map :)

---

*[components/constellation/pipeline.rs, line 245 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIi9CASb83ID0hUXuY9:-KIi9CATqH7Fm0JbncxQ:1087758780) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/pipeline.rs#L245)):*
> ```Rust
>             };
> 
>             // Spawn the child process.
> ```

Nice that this is in pipeline rather than constellation.

---

*[components/constellation/pipeline.rs, line 392 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIi9oL1R5uUm8odIT9t:-KIi9oL1R5uUm8odIT9u:-97109321) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/pipeline.rs#L392)):*
> ```Rust
> 
> #[derive(Deserialize, Serialize)]
> pub struct UnprivilegedPipelineContent {
> ```

Can this be made private? Also, the name is odd now we don't have `PrivilegedPipelineContent`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11437#-:-KIiARhk5aknlp7N1S3W:535224607)*

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/constellation/constellation.rs, line 40 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIhjJEdyaOfEdBucRfu:-KIl6azZbTppCIlpftek:-1702371916) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/constellation.rs#L40)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Are we ever actually using `ChildProcess` in the contellation? We are keeping a vector of them, but as far as I can tell, never actually doing anything with it.
</details>
https://github.com/servo/servo/issues/11459

---

*[components/constellation/constellation.rs, line 432 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIhjbUzy2M10dGwVmZy:-KIl6gNxjaQLIO7TlKXo:-1702371916) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/constellation.rs#L432)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> if we don't actually use the child process we could just make this a `Result<Pipeline>`.
</details>
https://github.com/servo/servo/issues/11459

---

*[components/constellation/pipeline.rs, line 41 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIhk4s8BCMa3KjfimW-:-KIl6jHK7BcMhiyDRrxW:-1702371916) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/pipeline.rs#L41)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Make this private? Or just get rid of it, as I don't see where it's being used.
</details>
https://github.com/servo/servo/issues/11459

---

*[components/constellation/pipeline.rs, line 186 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIhhOx8ZGSvXunduG0p:-KIl6pasBOl0IUMe3VSo:1650367392) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/pipeline.rs#L186)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> @nox would tell you off for side-effecting map :)
</details>
Not my code :)

---

*[components/constellation/pipeline.rs, line 392 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIi9oL1R5uUm8odIT9t:-KIl6tq19nG_xnn1_Hx4:-1574835490) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/pipeline.rs#L392)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Can this be made private? Also, the name is odd now we don't have `PrivilegedPipelineContent`.
</details>
It cannot. (`components/servo/lib.rs` needs it when spawning a child process.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11437)*

**Comment by asajeffrey** [comment]
OK, r=me after squashing.

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :umbrella: The latest upstream changes (presumably #11430) made this pull request unmergeable. Please resolve the merge conflicts.
</details>


---

Reviewed 1 of 2 files at r12, 1 of 1 files at r20.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/constellation/pipeline.rs, line 392 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11437#-KIi9oL1R5uUm8odIT9t:-KImUmgU_U1z6ILX6P4E:-177701114) ([raw file](https://github.com/servo/servo/blob/ffa5b1dea6727499be0caa2c01de17987450d416/components/constellation/pipeline.rs#L392)):*
<details><summary><i>Previously, Ms2ger wrote…</i></summary>
> It cannot. (`components/servo/lib.rs` needs it when spawning a child process.)
</details>
Change the name? (Bikeshedding, I know...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11437#-:-KImVM5fz8OgYxHAGxoz:1338165495)*

**Pull request merged**
