### PR TITLE
Remove unit test that triggers frequent intermittent failure.

### PR DESCRIPTION
**Pull request by jdm**
This works around #26895 by removing the test that triggers it. The underlying cause of the failure isn't clear, but it's something to do with the hyper server and doesn't appear to impact the way that Servo's HTTP stack functions. The unit test itself is testing one particular property of the way CORS requests are made with HEAD requests, and that's not a property that is critical functionality if we stop testing it.

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
error: unused imports: `AccessControlAllowOrigin`, `Origin`
  --> components/net/tests/http_loader.rs:19:5
   |
19 |     AccessControlAllowOrigin, Authorization, ContentLength, Date, HeaderMapExt, Host, Origin,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^                                                          ^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`
error: unused import: `RequestMode`
  --> components/net/tests/http_loader.rs:37:34
   |
37 |     RequestBody, RequestBuilder, RequestMode,
   |                                  ^^^^^^^^^^^

**Comment by CYBAI** [comment]
Missing one 👀

```
error: unused import: `Origin`
  --> components/net/tests/http_loader.rs:19:61
   |
19 |     Authorization, ContentLength, Date, HeaderMapExt, Host, Origin, StrictTransportSecurity,
   |                                                             ^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`
```

**Pull request merged**
