### PR TITLE
Making create attribute lowercase

### LINKED ISSUE #9252: Argument to createAttribute should be lowercased in HTML documents
Blocks #2185.

* Spec: <https://dom.spec.whatwg.org/#dom-document-createattribute>, step 2.
* Code: `components/script/dom/document.rs`, `fn CreateAttribute`.
* Test: `dom/nodes/Document-createAttribute.html`.

Similar code exists in the `CreateElement` function.

### PR DESCRIPTION
**Pull request by mattnenterprise**
This should fix #9252. I need some help getting the test case to work correctly. I get output that "TITLE" should FAIL, but it PASS. How do I make it to where it should PASS?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9282)

### CODE REVIEW

**Comment by nox** [comment]
Run the following:

```
./mach test-wpt --no-pause --log-raw raw.log /dom/nodes/Document-createAttribute.html
./mach update-wpt --no-patch raw.log
```

This will change the test expectations for you.

**Comment by jdm** [comment]
If the test file is `tests/wpt/web-platform-tests/path/to/test.html`, you need to modify (or remove, if all subtests pass) `tests/wpt/metadata/path/to/test.html.ini`, as described in "Upating test expectations" in tests/wpt/README.md.

**Comment by KiChjang** [comment]
Also, code should be written for `CreateElement` as well, as stated by @Ms2ger in #9252

**Comment by mattnenterprise** [comment]
I followed the instructions for updating test expectation. They worked for me.

**Comment by KiChjang** [comment]
@bors-servo retry

* `./mach test-wpt` timed out

**Pull request merged**
