### PR TITLE
Read params from a file on Android

### PR DESCRIPTION
**Pull request by connorimes**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8254)

### CODE REVIEW

**Comment by connorimes** [comment]
I just called the file `android_params` and loaded it with the default options, but let me know if you'd rather have something else.

**Comment by larsbergstrom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/servo/main.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8254#-K1pYVk_39RrJdCh5Eu1)** ([raw file](https://github.com/servo/servo/blob/7ac48d1d5c35ce5ec4a8f028a453b8af4fe32885/components/servo/main.rs#L154)):</sup>
Maybe just make this debug log output instead of an unconditional `println`?


---

<sup>**[resources/android_params, line 1 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8254#-K1pYf0XJLOAv3dFAhIm)** ([raw file](https://github.com/servo/servo/blob/7ac48d1d5c35ce5ec4a8f028a453b8af4fe32885/resources/android_params#L1)):</sup>
Perhaps start with a quick bit of documentation. e.g., "one argument per line. First argument should be the servo program name"?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8254)

**Comment by larsbergstrom** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8254)

**Comment by connorimes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/servo/main.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8254#-K1pYVk_39RrJdCh5Eu1)** ([raw file](https://github.com/servo/servo/blob/7ac48d1d5c35ce5ec4a8f028a453b8af4fe32885/components/servo/main.rs#L154)):</sup>
The log macros were not available here and trying to add them resulted in build failures.  I was originally going to make this a `warn!`.  Do you know how I can properly add the logging macros instead?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8254)

**Comment by connorimes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/servo/main.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8254#-K1pYVk_39RrJdCh5Eu1)** ([raw file](https://github.com/servo/servo/blob/7ac48d1d5c35ce5ec4a8f028a453b8af4fe32885/components/servo/main.rs#L154)):</sup>
After rebasing, this particular problem has gone away.  It's now using a debug! message.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8254)

**Comment by larsbergstrom** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8254)

**Comment by mbrubeck** [comment]
@bors-servo retry

#7785

**Comment by mbrubeck** [comment]
@bors-servo retry

#7785

**Pull request merged**
