### PR TITLE
compositing: Make the constellation messages serializable.

### PR DESCRIPTION
**Pull request by pcwalton**
Same idea as before. This depends on:
- https://github.com/servo/euclid/pull/94
- https://github.com/hyperium/hyper/pull/603

r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6593)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/msg/Cargo.toml, line 37 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6593#-JuCUHysmfDKTxspTCb4)** ([raw file](https://github.com/servo/servo/blob/df90fef9f016530a681f5adf5a2a054c1074d207/components/msg/Cargo.toml#L37)):</sup>
Let's go back to the cargo version.

---

<sup>**[components/msg/Cargo.toml, line 41 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6593#-JuCUNoxY4_VQmARkscO)** ([raw file](https://github.com/servo/servo/blob/df90fef9f016530a681f5adf5a2a054c1074d207/components/msg/Cargo.toml#L41)):</sup>
Let's go back to the cargo version.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6593)

**Comment by pcwalton** [comment]
Fixed. r? @jdm 

Note that this is currently blocked on serde: https://github.com/serde-rs/serde/pull/102

**Comment by jdm** [comment]
-S-awaiting-review +S-blocked-on-external 

---

Reviewed 21 of 21 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6593)

**Comment by pcwalton** [comment]
Rebased. Still blocked on @erickt reviewing serde-rs/serde#102

**Comment by erickt** [comment]
@pcwalton: I merged in your PR. Do you need a release cut for this as well?

**Comment by jdm** [comment]
-S-awaiting-review -S-blocked-on-external +S-needs-rebase 

---

Reviewed 21 of 21 files at r2, 19 of 19 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6593)

**Comment by pcwalton** [comment]
@bors-servo: retry

Network failure

**Comment by pcwalton** [comment]
OK, that's odd. A URL parsing test case no longer fails. Perhaps the fact that we serialize URLs via strings between the constellation and the rest of Servo has caused this?

**Pull request merged**
