### PR TITLE
Fix all AudioBuffer WPTs

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21602)

### CODE REVIEW

**Comment by ferjm** [comment]
If I run these two tests independently, I get the crashes. If I run them together via ```./mach test-wpt tests/wpt/web-platform-tests/webaudio/the-audio-api/the-audiobuffer-interface```, I get timeouts.

**Comment by ferjm** [comment]
> If I run these two tests independently, I get the crashes. If I run them together via ./mach test-wpt tests/wpt/web-platform-tests/webaudio/the-audio-api/the-audiobuffer-interface, I get timeouts.

This is fun. I am getting different behaviors on OSX and Linux.

On OSX I get what I described above (timeouts when running all tests together). On Linux, what the try run reported (crashes).

**Comment by ferjm** [comment]
Regarding https://github.com/servo/servo/pull/21602#issuecomment-419015519, I am trying to fix all these crashes, so we don't introduce intermittent TIMEOUT vs CRASH failures.

**Comment by ferjm** [comment]
```
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1558:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nbeCloseToArray@http://web-platform.test:8000/webaudio/resources/audit.js:1009:14\n@http://web-platform.test:8000/webaudio/the-audio-api/the-audiobuffersourcenode-interface/buffer-resampling.html:86:19\n", "subtest": "X Interpolated sine wave does not equal [0,0.05756402388215065,0.11493714898824692,0.17192909121513367,0.22835086286067963,0.28401535749435425,0.3387379050254822,0.3923371136188507,0.44463518261909485,0.4954586327075958,0.5446390509605408,0.5920131802558899,0.6374239921569824,0.680720865726471,0.7217602133750916,0.760405957698822...] with an element-wise tolerance of {\"absoluteThreshold\":0.090348,\"relativeThreshold\":0}.\n\tIndex\tActual\t\t\tExpected\t\tAbsError\t\tRelError\t\tTest threshold\n\t[0]\t-1.6697746515274048e-1\t0.0000000000000000e+0\t1.6697746515274048e-1\tInfinity\t9.0347999999999998e-2\n\t[1]\t-1.7548391222953796e-1\t5.7564023882150650e-2\t2.3304793611168861e-1\t4.0484997468002177e+0\t9.0347999999999998e-2\n\t[2]\t-1.6324132680892944e-1\t1.1493714898824692e-1\t2.7817847579717636e-1\t2.4202660170874948e+0\t9.0347999999999998e-2\n\t[3]\t-1.3169741630554199e-1\t1.7192909121513367e-1\t3.0362650752067566e-1\t1.7659984437464975e+0\t9.0347999999999998e-2\n\t[4]\t-8.4581792354583740e-2\t2.2835086286067963e-1\t3.1293265521526337e-1\t1.3704027709594790e+0\t9.0347999999999998e-2\n\t...and 479 more errors.\n\tMax AbsError of 1.0805229544639587e+0 at index of 20.\n\t[20]\t-1.6697746515274048e-1\t9.1354548931121826e-1\t1.0805229544639587e+0\t1.1827795847130018e+0\t9.0347999999999998e-2\n\tMax RelError of Infinity at index of 0.\n", "test": "/webaudio/the-audio-api/the-audiobuffersourcenode-interface/buffer-resampling.html", "line": 181458, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_true: expected true got false", "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1558:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:9\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:7\nbeGreaterThanOrEqualTo@http://web-platform.test:8000/webaudio/resources/audit.js:577:14\n@http://web-platform.test:8000/webaudio/the-audio-api/the-audiobuffersourcenode-interface/buffer-resampling.html:92:19\n", "subtest": "X SNR (0.001829 dB) is not greater than or equal to 37.17. Got 0.0018292814994553732.", "test": "/webaudio/the-audio-api/the-audiobuffersourcenode-interface/buffer-resampling.html", "line": 181459, "action": "test_result", "expected": "PASS"}
```

These are new tests I didn't have on my local clone.

**Comment by ferjm** [comment]
Looking better now. r? @Manishearth

**Comment by ferjm** [comment]
Travis seems to be green although it didn't update the status here

**Comment by ferjm** [comment]
All AudioBuffer tests are passing now. r? @Manishearth

**Review by Manishearth — APPROVED** [review]
r=me 

should there be test expectation updates here?

**Comment by ferjm** [comment]
> should there be test expectation updates here?

Oh, I updated the expectation, but it seems that I discarded the commit while force pushing (that's one of the issues of working with two different machines...).

**Pull request merged**
