### PR TITLE
implementing step 12 of 'prepare a script' algorithm

### PR DESCRIPTION
**Pull request by psdh**
#4176

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/4865)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@psdh: looks pretty good; I left some comments on critic.

**Comment by psdh** [comment]
Sorry for the delay on this one, it just slipped out of my mind
can someone please help me correct https://critic.hoppipolla.co.uk/showcomment?chain=10458

**Comment by jdm** [comment]
@psdh The code linked there does not appear to be part of the algorithm described in the original issue, right?

**Comment by Ms2ger** [comment]
@psdh: another passing test!
```
/html/semantics/scripting-1/the-script-element/script-for-onload.html
---------------------------------------------------------------------
PASS expected FAIL Script for and onload attributes
```

**Pull request merged**
