### PR TITLE
Don't load stylesheets in documents without browsing contexts

### LINKED ISSUE #12047: assertion failed: count_cell.get() > 0
assertion failed: count_cell.get() > 0
### URL:
http://i.entropy.cc/
### Backtrace:
```
frame #0  - 0x00000001055526ce - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000105552651 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000104823086 - _<F as alloc..boxed..FnBox<A>>::call_box::h6059122298f825d8
frame #3  - 0x00000001054c6947 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2c0e77c593c00c08
frame #4  - 0x000000010573a844 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x000000010403dae4 - std::panicking::begin_panic::h0bf39f6d43ab9349
frame #6  - 0x00000001046ca262 - _<script..dom..htmllinkelement..StylesheetContext as net_traits..AsyncResponseListener>::response_complete::h315c5e417b85cb3a
frame #7  - 0x00000001046c7d65 - _<script..network_listener..ListenerRunnable<A, Listener> as script..script_thread..Runnable>::handler::hc0416bc7ab472afc
frame #8  - 0x000000010482e95c - script::script_thread::ScriptThread::handle_msg_from_script::hd1f5e7b2423a8c64
frame #9  - 0x000000010488aa71 - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hc67d8b381c013b79
frame #10 - 0x000000010487073f - script::script_thread::ScriptThread::handle_msgs::h236c5be60a207bea
frame #11 - 0x0000000104821907 - std::panicking::try::call::h645a328f039d97c6
frame #12 - 0x000000010575646b - __rust_try
frame #13 - 0x0000000105756405 - __rust_maybe_catch_panic
frame #14 - 0x0000000104822ab4 - _<F as alloc..boxed..FnBox<A>>::call_box::h3db95636eb747818
frame #15 - 0x0000000105751ee8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
frame #16 - 0x00007fff8d70499c - _pthread_body
frame #17 - 0x00007fff8d704919 - _pthread_start

```

### PR DESCRIPTION
**Pull request by jdm**
Per https://github.com/whatwg/html/issues/1495, this fixes the most commonly reported panic in nightlies by making us match what other browsers do.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12047 (github issue number if applicable).
- [X] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12241)

### CODE REVIEW

**Comment by notriddle** [comment]
Are you sure a bug about heap corruption on Android is related to this?

**Comment by jdm** [comment]
My mistake, I meant https://github.com/whatwg/html/issues/1495.

**Comment by notriddle** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12241)*

**Pull request merged**
