### PR TITLE
Introduce FontFaceRules::effective_sources()

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11565)

### CODE REVIEW

**Comment by metajack** [comment]
This looks good modulo some comments and docs. r=me with those.

<details><summary><i>Previously, highfive wrote…</i></summary>
> warning **Warning** warning
> 
> * These commits modify style and layout code, but no tests are modified. Please consider adding a test!
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/font_face.rs, line 67 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11565#-KJI3feLDxdcDrui1qXP:-KJI3feLDxdcDrui1qXQ:-444848846) ([raw file](https://github.com/servo/servo/blob/7c1700c2be8ebd10bc3c72de127894cebb11d810/components/style/font_face.rs#L67)):*
> ```Rust
> 
> impl FontFaceRule {
>     pub fn effective_sources(&self) -> EffectiveSourcesIter {
> ```

This needs doc comments.

---

*[components/style/font_face.rs, line 77 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11565#-KJI3r4WimgeU7iQohkl:-KJI3r4WimgeU7iQohkm:-1560067904) ([raw file](https://github.com/servo/servo/blob/7c1700c2be8ebd10bc3c72de127894cebb11d810/components/style/font_face.rs#L77)):*
> ```Rust
>         self.0.find(|source| {
>             if let Source::Url(ref url_source) = **source {
>                 !url_source.format_hints.iter().all(|hint| {
> ```

A comment here saying "We only support truetype or opentype hinting would probably help.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11565#-:-KJI4WqCV6LD2sHB69Wt:418638756)*

**Comment by nox** [comment]
-S-awaiting-review 

@bors-servo r=metajack

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/font_face.rs, line 67 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11565#-KJI3feLDxdcDrui1qXP:-KJIQAyiuVsIThi7NNqd:-499146009) ([raw file](https://github.com/servo/servo/blob/7c1700c2be8ebd10bc3c72de127894cebb11d810/components/style/font_face.rs#L67)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> This needs doc comments.
</details>
Done.

---

*[components/style/font_face.rs, line 77 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11565#-KJI3r4WimgeU7iQohkl:-KJIQBQmkalclD4l9LQ8:-499146009) ([raw file](https://github.com/servo/servo/blob/7c1700c2be8ebd10bc3c72de127894cebb11d810/components/style/font_face.rs#L77)):*
<details><summary><i>Previously, metajack (Jack Moffitt) wrote…</i></summary>
> A comment here saying "We only support truetype or opentype hinting would probably help.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11565#-:-KJIQBrOK87gRYbbu8FK:151228990)*

**Comment by metajack** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/style/font_face.rs, line 68 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11565#-KJIRorWiaDf5lea1Cpz:-KJIRorWiaDf5lea1Cq-:613616392) ([raw file](https://github.com/servo/servo/blob/64595671606ce88390786b224b1ef0e5d97c54a9/components/style/font_face.rs#L68)):*
> ```Rust
> impl FontFaceRule {
>     /// Returns the list of effective sources for that font-face, that is the
>     /// sources which don't list only formats that we don't support.
> ```

Can be done in a followup if the current build lands, but suggestd change:

"... that is the sources which have at least one format that we support."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11565)*

**Comment by metajack** [comment]
Reviewed 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11565)*

**Pull request merged**
