### PR TITLE
Update regex.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15042)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Hold off on landing for a bit; there was a bit of a mess-up with the webdriver versioning that I'd like to get fixed first.

**Comment by jgraham** [comment]
The webdriver problem [1] should now be "fixed"; 0.18.1 is yanked, 0.19.0 is published.

[1] c.f. https://twitter.com/nokusu/status/788285254322774016

**Comment by Ms2ger** [comment]
Good to go now.

**Pull request merged**
