### PR TITLE
[WIP] Exit if pip version is detected to be too old.

### PR DESCRIPTION
**Pull request by metajack**
Rebased #11149.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because bootstrapping

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14253)

### CODE REVIEW

**Comment by metajack** [comment]
@campaul @larsbergstrom So it looks like it detects 13.1.0.

**Comment by campaul** [comment]
The problem I was having with this approach was the minimum required version appears to be different between systems. On my computer, the build would fail with anything older than v14.0.0, but Travis is clearly able to build using v13.1.0.

I was operating under the assumption that a specific version of virtualenv always corresponds to a specific version of pip, perhaps that assumption is wrong?

**Comment by metajack** [comment]
I am thinking it probably makes sense to land this with some version, and we can increase the versions or lower them as we run into people with specific issues. It's easy to add `pip install --upgrade pip virtualenv`  to the travis yaml.

Should we start with 13.1.0 or 14.0.0 and add the upgrade line to travis? I think I'm leaning towards the former and adjusting based on incoming bug reports.

**Comment by frewsxcv** [comment]
Relevant PR: https://github.com/servo/servo/pull/14452

**Comment by jdm** [comment]
Given #14452, do we still need this?

**Comment by metajack** [comment]
I think #14452 and the saltification of bootstrap probably both address these issues.

**Pull request closed without merging**
