### PR TITLE
Magic Leap developer ergonomic improvements

### LINKED ISSUE #23041: Make public embedding API for command line arguments easier to use
Right now, libsimpleservo::init accepts an `Option<String>`, which is then parsed as JSON to extract a `Vec<String>` value. We should accept a `Vec<String>` value instead, and move the JSON parsing to the jniapi crate instead, which is the only embedding platform that has those particular constraints.

### PR DESCRIPTION
**Pull request by jdm**
These changes allow passing in command line arguments for Servo via a SERVO_ARGS from the mldb terminal when launching the activity, as well as passing in a launch URL as an argument. It also redirects stdout to the ML log, which allows observing the built-in profiler output.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23041
- [x] These changes do not require tests because no magic leap testing.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23300)

### CODE REVIEW

**Comment by CYBAI** [comment]
Travis complains about tidy

```diff
Checking files for tidiness...
./ports/libmlservo/src/lib.rs:72: derivable traits list is not in alphabetical order
	expected: Clone, Copy
	found: Copy, Clone
Running the dependency licensing lint...
 88.0 MiB /  88.0 MiB (100 %)  63.3 MiB/s ETA:   0 s
 88.0 MiB /  88.0 MiB (100 %)   9.4 MiB/s ETA:   0 s
 60.3 MiB /  60.3 MiB (100 %)  12.6 MiB/s ETA:   0 s
  8.9 MiB /  11.1 MiB ( 81 %)   5.1 MiB/s ETA:   0 sinfo: downloading component 'rustfmt'
info: installing component 'rustfmt'
Diff in /home/travis/build/servo/servo/ports/libmlservo/src/lib.rs at line 137:
                 .unwrap_or("")
                 .split(' ')
                 .map(|s| s.to_owned())
-                .collect()
+                .collect(),
         )
     };
     info!("got args: {:?}", args);
Run `./mach fmt` to fix the formatting
The command "./mach test-tidy --no-progress --all" exited with 1.
```

and `android-mac` failed with

```rust
error[E0433]: failed to resolve: use of undeclared type or module `serde_json`
   --> ports/libsimpleservo/jniapi/src/lib.rs:688:23
    |
688 |         Some(args) => serde_json::from_str(&args)
    |                       ^^^^^^^^^^ use of undeclared type or module `serde_json`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
The following warnings were emitted during compilation:

warning: clang: warning: argument unused during compilation: '-L/Users/servo/buildbot/slave/android-mac/build/android-toolchains/ndk/platforms/android-21/arch-arm/usr/lib' [-Wunused-command-line-argument]

error: Could not compile `simpleservo_jniapi`.
```

**Comment by CYBAI** [comment]
Failed in `./etc/ci/lockfile_changed.sh` 👀

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 41ee5e1..e651dba 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -4179,7 +4179,6 @@ dependencies = [
  "libloading 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)",
  "libservo 0.0.1",
  "log 0.4.6 (registry+https://github.com/rust-lang/crates.io-index)",
- "serde_json 1.0.13 (registry+https://github.com/rust-lang/crates.io-index)",
  "winapi 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)",
 ]
 
@@ -4203,6 +4202,7 @@ dependencies = [
  "jni 0.10.2 (registry+https://github.com/rust-lang/crates.io-index)",
  "libc 0.2.44 (registry+https://github.com/rust-lang/crates.io-index)",
  "log 0.4.6 (registry+https://github.com/rust-lang/crates.io-index)",
+ "serde_json 1.0.13 (registry+https://github.com/rust-lang/crates.io-index)",
  "simpleservo 0.0.1",
 ]
```

**Comment by jdm** [comment]
Whoops.
@bors-servo r=asajeffrey

**Comment by CYBAI** [comment]
@bors-servo retry

```
  ▶ FAIL [expected PASS] /html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend-display-none-rendering.html
  └   → /html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend-display-none-rendering.html f4160efd4d52c3db4cdd078a7efc8d7ca6f60032
/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend-display-none-rendering-ref.html 4dfce9506a172505b1a43187270e81ccd23aceda
```

**Pull request merged**
