### PR TITLE
Update WR (types updates, stacking context culling)

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15862)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone

**Comment by emilio** [comment]
```
error[E0063]: missing field `frame_id` in initializer of `device::GpuFrameProfile<_>`
   --> /home/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/9496efa/webrender/src/device.rs:522:9
    |
522 |         GpuFrameProfile {
    |         ^^^^^^^^^^^^^^^ missing `frame_id`
```

**Pull request merged**
