### PR TITLE
Move WPT Linux from Buildbot to Taskcluster

### PR DESCRIPTION
**Pull request by SimonSapin**
Closes https://github.com/servo/servo/pull/24418

### CODE REVIEW

**Comment by SimonSapin** [comment]
This run looks pretty good, I think? https://community-tc.services.mozilla.com/tasks/groups/XVj2vEiQT_K-RK9MYhBJlA

Filtered log:

```
  ▶ TIMEOUT [expected OK] /webdriver/tests/element_send_keys/file_upload.py
  │ 
  └ [2019-11-19T16:40:02Z ERROR script::dom::bindings::error] Error at :2:28 arguments[0] is undefined

  ▶ PASS [expected FAIL] /_mozilla/css/text_decoration_underline_subpx_a.html

  ▶ PASS [expected FAIL] /css/css-text/word-break/word-break-break-all-005.html

  ▶ OK [expected CRASH] /_mozilla/mozilla/fetch_cannot_overwhelm_system.window.html

**Review by jdm — APPROVED** [review]

**Comment by SimonSapin** [comment]
A second run got the exact same filtered unexpected results, so they don’t look intermittent: https://community-tc.services.mozilla.com/tasks/groups/UhZtEvtISO-VD3qkSvNRRA

I don’t have a precise explanation for these differences with Buildbot, but we’re running Ubuntu 18.04 instead of 14.04 and Ubuntu’s gstreamer instead of https://github.com/servo/servo/wiki/How-to-generate-GStreamer-binaries-for-CI

**Comment by jdm** [comment]
Yeah, I would go ahead and add linux-specific expected results for those tests.

**Comment by SimonSapin** [comment]
Alright, let’s see how this looks.

@bors-servo try=wpt

**Comment by SimonSapin** [comment]
Currently this runs on GCP instances that have 16 “vCPU” (which as I understand it map to 8 cores / 16 threads). We can change max capacity (number of instances running concurrently) or the machine type in https://community-tc.services.mozilla.com/worker-manager/proj-servo%2Fdocker and send a PR to [`projects.yml` in `mozilla/community-tc-config`](https://github.com/mozilla/community-tc-config/blob/878acd84f0a9e7f34c56412603a155cae787fa8c/config/projects.yml#L214-L230) in order to make that change persistent (not overwritten next time someone runs `tc-admin` in that repository).

Other knobs at disposal are the number of chunks (= number of tasks), and the number of wptrunner processes per task.

With the current config the time for release build + WPT tasks on Linux is well under that of macOS, which remains the limiting factor for cycle time.

**Comment by SimonSapin** [comment]
Per your previous comments:

@bors-servo r=jdm

**Pull request merged**
