### PR TITLE
Don't process events while borrowing the event loop

### PR DESCRIPTION
**Pull request by asajeffrey**
At the moment, the glutin embedder holds onto a borrow of the events loop while processing events, which is dangerous if any of the event handlers end up using the events loop reentrantly. (This caused a panic while integrating https://github.com/servo/rust-webvr/pull/84.)

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because this is low-level embedding code

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23574)

### CODE REVIEW

**Comment by paulrouget** [comment]
There was a good reason to have 2 loops (`loop{}` + `run_forever`), at least in the previous versions of  winit. I don't remember why though. Can you remove the early `borrow_mut` and maybe open a different PR for the `run_forever` removal where I can look at why we needed that in the first place?

**Comment by asajeffrey** [comment]
Well the run_forever loop is the one that's causing the problems, there isn't much point to changing the poll_events loop without changing run_forever. AFAIK the reason for having run_forever is to have the event loop block on window events, but the changed version should do that too.

**Comment by paulrouget** [comment]
Erf, I read the changes wrong.

The changes look fine. There was a reason to keep loop in run_forever in Glutin < 0.20 (resizing issue). I'll check if this is still a problem with Glutin 0.21.

**Comment by paulrouget** [comment]
Just tested. Indeed, on Mac, resizing the windows doesn't resize Servo until the mouse button is released. I think it has to do with the missing `Continue` in `run_forever`.

**Comment by asajeffrey** [comment]
Argh, that's annoying. I'll have a look to see if there's a work around for
this.

**Comment by asajeffrey** [comment]
Also, we can work around this by making the EventLoop an Option, and calling take() to grab ownership of it before calling run_forever. Sigh, what a hack.

**Comment by paulrouget** [comment]
Do we have to use a RefCell? iirc, it was just "easier" that way, but I'm not sure it was absolutely necessary.

**Comment by asajeffrey** [comment]
I added a hack to handle resize events differently, which isn't brilliant but I'm not sure what else to do.

We could try removing the `RefCell`, but that would mean changing methods that are currently `&self` to be `&mut self`, which seems like it might be a fair bit of work. If our plan is to drop the glutin port, I'm a bit reluctant to invest in fixing it up too much.

**Comment by paulrouget** [comment]
That's not too bad :) Thanks you.

@bors-servo r+

**Comment by asajeffrey** [comment]
Grr... 
```
   Compiling libservo v0.0.1 (/home/servo/buildbot/slave/linux-rel-wpt/build/components/servo)
error: method is never used: `has_events`
  --> ports/glutin/app.rs:72:5
   |
72 |     fn has_events(&self) -> bool {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`
```

**Pull request merged**
