### PR TITLE
Taskcluster: make WPT logs more readable

### LINKED ISSUE #22438: Taskcluster WPT output is not readable
```
+ ./mach test-wpt --release --product=servodriver --headless tests/wpt/mozilla/tests/mozilla/DOMParser.html tests/wpt/mozilla/tests/css/per_glyph_font_fallback_a.html tests/wpt/mozilla/tests/css/img_simple.html tests/wpt/mozilla/tests/mozilla/secure.https.html
Running 4 tests in web-platform-tests
  [0/4] /_mozilla/css/per_glyph_font_fallbac
ozilla/css/per_glyph_font_fallbac
        /_mozilla/css/img_sim
ozilla/css/img_sim
  [2/4] No tests running.
ozilla/mozilla/DOMPar
ozilla/mozilla/DOMPar
        /_mozilla/mozilla/secure.ht
ozilla/mozilla/secure.ht
  • 4 ran as expected. 0 tests skipped.
real	0m7.836s
user	0m4.644s
sys	0m1.060s
```

The default logger rewrites the terminal, which doesn't work well with the taskcluster logging. We should try enabling `--log-mach -` and see if that yields something more understandable.

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes #22438 

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22442)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I think this fixes https://github.com/servo/servo/issues/22438. r? @jdm

**Comment by SimonSapin** [comment]
An alternative is fixing https://github.com/mozilla-frontend-infra/react-lazylog so that it supports ANSI "Control Sequence Cursor Up" and "Control Sequence Erase in Line", but I don’t know how involved that would be.

**Comment by jdm** [comment]
@bors-servo r+
Can never have too many cats.

**Comment by SimonSapin** [comment]
> An alternative is fixing https://github.com/mozilla-frontend-infra/react-lazylog so that it supports ANSI "Control Sequence Cursor Up" and "Control Sequence Erase in Line", but I don’t know how involved that would be.

I’ve filed https://github.com/mozilla-frontend-infra/react-lazylog/issues/29, we’ll see if someone picks it up.

**Comment by jdm** [comment]
@bors-servo retry
* #22445

**Comment by jdm** [comment]
@bors-servo retry
* #22452

**Pull request merged**
