### PR TITLE
Remove some jobs from Buildbot

### LINKED ISSUE #23302: Linux perf data s3 upload is broken
```
aws s3 sync --size-only --acl public-read ./etc/ci/performance/output s3://servo-perf
 in dir /home/servo/buildbot/slave/linux-nightly/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['aws', 's3', 'sync', '--size-only', '--acl', 'public-read', './etc/ci/performance/output', 's3://servo-perf']
 using PTY: False
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 28, in <module>
    from awscli.formatter import get_formatter
  File "/usr/local/lib/python2.7/dist-packages/awscli/formatter.py", line 20, in <module>
    from awscli.table import MultiTable, Styler, ColorizedStyler
  File "/usr/local/lib/python2.7/dist-packages/awscli/table.py", line 17, in <module>
    import colorama
ImportError: No module named colorama
```

### PR DESCRIPTION
**Pull request by SimonSapin**
* `arm64`: “no good reason to continue to maintain”: https://github.com/servo/servo/pull/23414#issuecomment-505045672
* `mac-rel-intermittent`: disabled since https://github.com/servo/saltfs/pull/965
* `linux-rel-intermittent`: judged unnecessary https://github.com/servo/servo/pull/23633#issuecomment-505576450
* `linux-nigthly`: only perf data collection and upload now. Closes https://github.com/servo/servo/issues/23302, where this jobs has been know to be broken for 8 weeks but nobody cared enough to fix it

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23633)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r? @jdm

Was it intentional to disable `mac-rel-intermittent` without having a Taskcluster replacement for it?

With performance data collection disabled, various scripts under `etc/ci/performance/` are now dead code. Do we want to keep them?

**Comment by SimonSapin** [comment]
Speaking of, do we ever look at results form `linux-rel-nogate`? They don’t seem to be anywhere other than Buildbot logs.

**Comment by jdm** [comment]
I do look at the nogate jobs occasionally, but we can resurrect them if we ever want them again.

**Comment by jdm** [comment]
I admit that I forgot about the mac-rel-intermittents job when I switched off the mac builders, but I don't believe I have ever seen the intermittent jobs fail since they were added. I'm inclined to remove them.

**Comment by SimonSapin** [comment]
We do still run `linux-rel-intermittent` (on Buildbot). Are you saying we should remove it as well?

**Comment by jdm** [comment]
I am.

**Comment by SimonSapin** [comment]
Alright, PR updated.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23634

**Comment by SimonSapin** [comment]
With this I believe that the linux-cross-* EC2 instances are unused and we should stop them. I wanted to have a look at their cost but it looks like my AWS account doesn’t have access to billing information.

**Pull request merged**
