### PR TITLE
Update timer scheduler to use crossbeam

### PR DESCRIPTION
**Pull request by gterzian**
It seems time to update the timer scheduler implementation to use crossbeam constructs.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by gterzian** [comment]
cc @asajeffrey 

Haven't run it yet, could still use an initial review. 

@bors-servo try=wpt

**Comment by asajeffrey** [comment]
OK, this LGTM, r=me when you're happy with it.

I think this is the right syntax... @bors-servo delegate=gterzian

**Comment by gterzian** [comment]
Thanks, I just added a call to `check_timers` before computing the timeout at the start of the select, so that events that are ready to dispatch do so immediately versus after a 0 timeout(or perhaps even missing some?). See https://github.com/servo/servo/pull/24492/commits/84dda989e9fb1286f7b4362916bc05ba15313b87#diff-0c685a7a066b6822148c1ff02ff092e5R43

**Comment by gterzian** [comment]
@bors-servo retry
- https://github.com/servo/servo/issues/24504
- https://github.com/servo/servo/issues/23386

**Comment by gterzian** [comment]
@bors-servo retry

- #23386

**Comment by gterzian** [comment]
@bors-servo retry 
- https://github.com/servo/servo/issues/24502
- https://github.com/servo/servo/issues/23386

**Comment by jdm** [comment]
I am really suspicious of a PR that alters the timer infrastructure suddenly triggering a lot of new intermittent timeouts.

**Comment by asajeffrey** [comment]
Sigh, yes, it's possible that this implementation is correct but has different nondeterministic behaviour which causes different tests to be intermittent. Not sure what to do about that though, this implementation is much nicer, it'd be a pity not to land it due to other issues.

**Comment by gterzian** [comment]
So this was actually a logic error:

```
TIMEOUT [expected OK] /html/browsers/the-window-object/apis-for-creating-and-navigating-browsing-contexts-by-name/open-features-non-integer-left.html
  │ 
  │ 
  │ 
  │ 
  │ supplied instant is later than self (thread Constellation, at src/libcore/option.rs:1190)
  │ stack backtrace:
  │    0: servo::main::{{closure}}
  │    1: std::panicking::rust_panic_with_hook
  │              at src/libstd/panicking.rs:477
  │    2: std::panicking::continue_panic_fmt
  │              at src/libstd/panicking.rs:380
  │    3: rust_begin_unwind
  │              at src/libstd/panicking.rs:307
  │    4: core::panicking::panic_fmt
  │              at src/libcore/panicking.rs:84
  │    5: core::option::expect_failed
  │              at src/libcore/option.rs:1190
  │    6: core::option::Option<T>::expect
  │              at /rustc/084beb83e0e87d673d5fabc844d28e8e8ae2ab4c/src/libcore/option.rs:345
  │       std::time::Instant::duration_since
  │              at src/libstd/time.rs:261
  │       <std::time::Instant as core::ops::arith::Sub>::sub
  │              at src/libstd/time.rs:390
  │    7: constellation::timer_scheduler::TimerScheduler::get_timeout
  │    8: constellation::constellation::Constellation<Message,LTF,STF>::run
  │    9: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   10: _ZN3std9panicking3try7do_call17h1606cf2ce9a36817E.llvm.17468948721890200813
  │   11: __rust_maybe_catch_panic
  │              at src/libpanic_unwind/lib.rs:80
  │   12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  │              at /rustc/084beb83e0e87d673d5fabc844d28e8e8ae2ab4c/src/liballoc/boxed.rs:922
  │   14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  │              at /rustc/084beb83e0e87d673d5fabc844d28e8e8ae2ab4c/src/liballoc/boxed.rs:922
  │       std::sys_common::thread::start_thread
  │              at src/libstd/sys_common/thread.rs:13
  │       std::sys::unix::thread::Thread::new::thread_start
  │              at src/libstd/sys/unix/thread.rs:79
  │   15: start_thread
  │   16: clone
  │ 
  │ [2019-10-19T14:28:00Z ERROR servo] supplied instant is later than self
```

and what I've done is merge `get_timeout` into `check_timers`, so that each peek always checks if the event is past due. 

Please look at the last commit(to be squashed).

**Comment by gterzian** [comment]
Ok I squashed the fix, for clarity I essentially merged the below into the `check_timers` function
Screen Shot 2019-10-20 at 11 41 55 PM

The problem was that the match didn't take into account that `now` could be later than the earlier timeout, which is interesting since there first was a call to `check_timers`, but I guess the slight delay between that call and the next peek could mean that another timeout had already been reached and the substracting `now` from it would fail. 

Everything now happens in a single `check_timers` function that returns an optional timeout, and contains an match that catches the above problem.

**Pull request merged**
