### PR TITLE
Suggest a faster tidy.

### PR DESCRIPTION
**Pull request by jdm**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because documentation update.

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11201)

### CODE REVIEW

**Comment by KiChjang** [comment]
So I have some reservations about this, because some PRs do add WPT tests, and sometimes people did not know how to use `./mach create-wpt` to generate them. Running `./mach test-tidy` would at least catch the missing `<link>`s on the new WPT test file, which would otherwise be generated by `create-wpt`.

**Comment by Ms2ger** [comment]
@KiChjang I'm afraid you don't have a clue what you're talking about. `--faster` has included the wpt lint since #9394.

@bors-servo r+

**Comment by KiChjang** [comment]
@bors-servo r-

In which case, we should just do away the `--faster` option and make it the default, and add in something like `--all-wpt` when we want to check tidy rules against all WPT files.

**Comment by jdm** [comment]
@KiChjang This is directly addressing a complaint that @nox had about the current template. I'd rather file your suggestion as a separate issue, since it involves modifying various CI files as well as the implementation.

**Comment by KiChjang** [comment]
@bors-servo r+

Fine by me.

**Comment by Wafflespeanut** [comment]
heh, given #11217, we're gonna revert this soon :)

**Pull request merged**
