### PR TITLE
Derive DomObject with a proc macro

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15543)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/domobject_derive/lib.rs, line 41 at r1](https://reviewable.io:443/reviews/servo/servo/15543#-KcwraIaBFi5T2aQihzt:-KcwraIaBFi5T2aQihzu:bskfpuf) ([raw file](https://github.com/servo/servo/blob/c84cea995bd5d1596eaffe041b479ba1081a50fe/components/domobject_derive/lib.rs#L41)):*
> ```Rust
>             #[inline]
>             fn reflector(&self) -> &::dom::bindings::reflector::Reflector {
>                 self.#first_field_name.reflector()
> ```

Change this to a fully qualified call? `::dom::bindings::reflector::DomObject::reflector(&self.#first_field_name)`. Same for `init_reflector` below. r=me with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15543)*

**Comment by nox** [comment]
A trait is always imported in itself, so it's not a problem to not fully-qualify that.

@bors-servo r=SimonSapin

**Comment by Ms2ger** [comment]
> Change this to a fully qualified call? `::dom::bindings::reflector::DomObject::reflector(&self.#first_field_name)`. Same for `init_reflector` below. r=me with that.

I think we should still do this, to ensure that it is indeed a `DomObject` method we're calling.

**Comment by nox** [comment]
AFAIK it won't compile when it could be ambiguous.

**Pull request merged**
