### PR TITLE
Enable CSS tests.

### PR DESCRIPTION
**Pull request by jdm**
Do not merge this; I'm looking into what it takes to stop running the test-css jobs.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19070)

### CODE REVIEW

**Comment by jdm** [comment]
Test job times:
* servo-linux5 (linux-rel-wpt) before: ~18m
* servo-linux5 (linux-rel-wpt) after: ~25.5m

* servo-mac4 (mac-rel-wpt1) before: ~23.5m
* servo-mac5 (mac-rel-wpt1) after: ~28m

* servo-mac5 (mac-rel-wpt2) before: ~11.5m
* servo-mac9 (mac-rel-wpt2) after: ~22.5m

* servo-mac7 (mac-rel-wpt3) before: ~21.5m
* servo-mac7 (mac-rel-wpt3) after: ~30.5m

* servo-mac1 (mac-rel-wpt4) before: ~14m
* servo-mac1 (mac-rel-wpt4) after: ~18m

We could repurpose mac-rel-css1 and mac-rel-css2 to be mac-rel-wpt5 and mac-rel-wpt6 instead, and that should spread out the load quite a bit.

**Comment by jdm** [comment]
It looks like we might be having some trouble loading the xht documents, so I'm digging into that.

**Comment by jdm** [comment]
These changes depend on https://github.com/servo/html5ever/pull/324.

**Comment by jdm** [comment]
@metajack This is now ready for review.

**Comment by metajack** [comment]
@bors-servo r+

For a delta of +30k and -7M this was surprisingly easy to review. Also, the new setup seems much simpler. Great work!

**Pull request merged**
