### PR TITLE
Implement alignment shorthand properties

### LINKED ISSUE #15954: Implement place-{content,self,items} shorthand properties
Spec:
* place-content: https://drafts.csswg.org/css-align/#propdef-place-content
* place-self: https://drafts.csswg.org/css-align/#place-self-property
* place-items: https://drafts.csswg.org/css-align/#place-items-property

They are basically just shorthands of several existing properties, so it should be easy to implement.

This should be implemented in https://github.com/servo/servo/blob/master/components/style/properties/shorthand/position.mako.rs

and the related sub-properties are defined in https://github.com/servo/servo/blob/master/components/style/properties/longhand/position.mako.rs

### PR DESCRIPTION
**Pull request by tamamu**
I implemented the shorthand properties, but it may includes some bugs.

Currently, `mach test-unit -p style` caught some errors (see #15954). I already tried `mach build-geckolib`, though there is no improvement. Please check my code.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15954

- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16322)

### CODE REVIEW

**Comment by Manishearth** [comment]
Apply this patch:

```patch
diff --git a/components/style/properties/shorthand/position.mako.rs b/components/style/properties/shorthand/position.mako.rs
index f001c56..94c3bee 100644
--- a/components/style/properties/shorthand/position.mako.rs
+++ b/components/style/properties/shorthand/position.mako.rs
@@ -140,7 +140,7 @@
 
 <%helpers:shorthand name="place-content" sub_properties="align-content justify-content"
                     spec="https://drafts.csswg.org/css-align/#propdef-place-content"
-                    products="gecko">
+                    products="gecko" disable_when_testing="True">
     use properties::longhands::align_content;
     use properties::longhands::justify_content;
 
@@ -188,7 +188,7 @@
 
 <%helpers:shorthand name="place-self" sub_properties="align-self justify-self"
                     spec="https://drafts.csswg.org/css-align/#place-self-property"
-                    products="gecko">
+                    products="gecko" disable_when_testing="True">
     use values::specified::align::AlignJustifySelf;
     use parser::Parse;
 
@@ -213,7 +213,7 @@
 
 <%helpers:shorthand name="place-items" sub_properties="align-items justify-items"
                     spec="https://drafts.csswg.org/css-align/#place-items-property"
-                    products="gecko">
+                    products="gecko" disable_when_testing="True">
     use values::specified::align::{AlignItems, JustifyItems};
     use parser::Parse;
```


Remove the serialization tests, we'll rely on the tests in gecko.

**Comment by tamamu** [comment]
Is this all right? What else can I do?

**Comment by Manishearth** [comment]
It's fine, just needs review

**Comment by upsuper** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/style/properties/shorthand/position.mako.rs, line 153 at r1](https://reviewable.io:443/reviews/servo/servo/16322#-KhQvYeEQ-qZG9hd1Id2:-KhQvYeFM8RF-x3L1u5S:bomb1ub) ([raw file](https://github.com/servo/servo/blob/d6f4c8c6dd75b187d2c92eb7409a5a67534ac45e/components/style/properties/shorthand/position.mako.rs#L153)):*
> ```Rust
>             match align {
>                 align_content::SpecifiedValue::stretch =>
>                     justify_content::SpecifiedValue::stretch,
> ```

Maybe easier to just
```rust
% for value in "stretch flex_start flex_end center space_between space_around".split():
  align_content::SpecifiedValue::${value} => justify_content::SpecifiedValue::${value},
% endfor
```

---

*[components/style/properties/shorthand/position.mako.rs, line 184 at r1](https://reviewable.io:443/reviews/servo/servo/16322#-KhQwNLygXEqWKVIsUks:-KhQwNLzL17QLjUCOGpo:b-7wd06z) ([raw file](https://github.com/servo/servo/blob/d6f4c8c6dd75b187d2c92eb7409a5a67534ac45e/components/style/properties/shorthand/position.mako.rs#L184)):*
> ```Rust
>             self.align_content.to_css(dest)?;
>             dest.write_str(" ")?;
>             self.justify_content.to_css(dest)
> ```

Probably shouldn't be serializing the second value if it's identical to the first.

---

*[components/style/properties/shorthand/position.mako.rs, line 147 at r5](https://reviewable.io:443/reviews/servo/servo/16322#-KhR8cLuvnY4dFrLvdg8:-KhR8cLwVdkuRfLdK3NQ:buo4j10) ([raw file](https://github.com/servo/servo/blob/a864300a57d6c4d3bbb71e3f129fa1491e85f4a1/components/style/properties/shorthand/position.mako.rs#L147)):*
> ```Rust
>     use properties::longhands::justify_content;
> 
> % if product == "servo":
> ```

Probably just remove this block given the whole property isn't implemented for Servo at all.

---

*[components/style/properties/shorthand/position.mako.rs, line 209 at r5](https://reviewable.io:443/reviews/servo/servo/16322#-KhR9mgTPKpVq9lvDo8j:-KhR9mgUMugPY3rM_MKl:brhumzt) ([raw file](https://github.com/servo/servo/blob/a864300a57d6c4d3bbb71e3f129fa1491e85f4a1/components/style/properties/shorthand/position.mako.rs#L209)):*
> ```Rust
>             self.align_self.to_css(dest)?;
>             dest.write_str(" ")?;
>             self.justify_self.to_css(dest)
> ```

Same here.

---

*[components/style/properties/shorthand/position.mako.rs, line 241 at r5](https://reviewable.io:443/reviews/servo/servo/16322#-KhR9qH03TCBZ6dI_xth:-KhR9qH03TCBZ6dI_xti:b-1kzc9c) ([raw file](https://github.com/servo/servo/blob/a864300a57d6c4d3bbb71e3f129fa1491e85f4a1/components/style/properties/shorthand/position.mako.rs#L241)):*
> ```Rust
>             self.align_items.to_css(dest)?;
>             dest.write_str(" ")?;
>             self.justify_items.to_css(dest)
> ```

And here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16322)*

**Comment by tamamu** [comment]
@upsuper Thank you.

**Pull request merged**
