### PR TITLE
Deduplicate parking_lot by updating it to 0.9

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24129)

### CODE REVIEW

**Comment by Eijebong** [comment]
@jdm Updated scopeguard too since updating parking_lot allowed for that

**Comment by jdm** [comment]
```
[0m[1m[38;5;9merror[0m[0m[1m: use of deprecated item 'libc::fixed_width_ints::uint8_t': Use u8 instead.[0m
[0m  [0m[0m[1m[38;5;12m--> [0m[0mcomponents/background_hang_monitor/sampler.rs:33:27[0m
[0m   [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m33[0m[0m [0m[0m[1m[38;5;12m| [0m[0mpub type Address = *const libc::uint8_t;[0m
[0m   [0m[0m[1m[38;5;12m| [0m[0m                          [0m[0m[1m[38;5;9m^^^^^^^^^^^^^[0m
[0m   [0m[0m[1m[38;5;12m|[0m
[0m   [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: `-D deprecated` implied by `-D warnings`[0m

[0m[1m[38;5;9merror[0m[0m[1m: aborting due to previous error[0m
```

**Comment by jdm** [comment]
New deprecation introduced by updating libstd.

**Comment by Eijebong** [comment]
Arf. Should be fixed now

**Comment by jdm** [comment]
@bors-servo retry
* #24131

**Comment by CYBAI** [comment]
In Android, magicleap and windows builds:

```rust
error: use of deprecated item 'libc::fixed_width_ints::uint64_t': Use u64 instead.
  --> ports/libsimpleservo/api/src/gl_glue.rs:18:33
   |
18 |     pub type khronos_uint64_t = libc::uint64_t;
   |                                 ^^^^^^^^^^^^^^
   |
   = note: `-D deprecated` implied by `-D warnings`

error: use of deprecated item 'libc::fixed_width_ints::int32_t': Use i32 instead.
  --> ports/libsimpleservo/api/src/gl_glue.rs:20:23
   |
20 |     pub type EGLint = libc::int32_t;
   |                       ^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `simpleservo`.
```

**Comment by Eijebong** [comment]
```
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": "Test timed out", 
    "stack": null, 
    "subtest": "page-created Error (cross-site iframe)", 
    "test": "/html/infrastructure/safe-passing-of-structured-data/structured-cloning-error-stack-optional.sub.window.html", 
    "line": 331210, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": "Test timed out", 
    "stack": null, 
    "subtest": "JS-engine-created TypeError (cross-site iframe)", 
    "test": "/html/infrastructure/safe-passing-of-structured-data/structured-cloning-error-stack-optional.sub.window.html", 
    "line": 331214, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "TIMEOUT", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/infrastructure/safe-passing-of-structured-data/structured-cloning-error-stack-optional.sub.window.html", 
    "line": 331219, 
    "action": "test_result", 
    "expected": "OK"
}
```
intermittent failures, they failed once and then passed once when I ran them locally

**Comment by Eijebong** [comment]
There, the libc stuff is fixed now

**Comment by jdm** [comment]
@bors-servo retry
* #24145

**Comment by jdm** [comment]
@bors-servo retry
* network issue

**Pull request merged**
