### PR TITLE
layout: Take into account the client point for fixed positioned stacking contexts

### LINKED ISSUE #12763: Hit test on fixed DIV incorrectly offset when page is scrolled
The problem occurs when there is a div with CSS `position: fixed`.  In this test, there is a `cursor:pointer` style and a `:hover{ background-color: red} ` style to indicate that the DIV has been hovered over.

These styles initially work when the page first loads - hovering over the DIV makes the cursor become a pointer and changes the background colour of it.

 However, when the document is scrolled down by any amount, the pointer cursor and background colour no longer work on hover.  Scrolling the document back to the very top makes them work again.

The problem appears to be specific to 'position: fixed'.  
Demo:
demo

One subtlety is that scrolling the page down any amount which isn't the full height of the DIV means that the hover styles (cursor pointer and background colour) do work but only on a top portion of the div.  For example, scrolling down the page approximately half the height of the div means that the hover styles only work as expected on the top half of the div, but nothing happens when hovering over the bottom half.

It feels as if the DIV's hit test coordinates are scrolling along with the rest of the page just as it would if it didn't have `position: fixed` set.

Online test case [here](https://samuknet.github.io/test_cases/fixedDivHitTest/).

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12763 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12777)

### CODE REVIEW

**Comment by pcwalton** [comment]
Looks good to me

**Comment by emilio** [comment]
Whoops, I forgot to add a test for it, will do now.

**Pull request merged**
