### PR TITLE
Handle `inset: auto` values for absolutely positioned elements

### LINKED ISSUE #27387: <position>: auto does not work
```html
<p>Text text text text text text text </p>

<div style="width: 100px; height: 100px;  background-color: green; position: absolute;"></div>
```

Expected:
image

Actual: 
image

This is because we're resolving `auto` values for top/left/bottom/right to mean zero when we actually mean "where it was actually found"

cc @SimonSapin

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #27387

This is the same as https://github.com/servo/servo/pull/27397 , but written to share the box offset data instead of bubbling the hoisted box up based on comments from @SimonSapin.

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors try=wpt-2020

I've already updated expectations, so i'm hoping to see if anything changed between these two PRs.

**Comment by Manishearth** [comment]
It's the same tests, I just forgot to `git add` added files.

**Comment by SimonSapin** [comment]
Looks good! r=me with a rebase

**Comment by jdm** [comment]
@bors-servo retry
* #27414

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by Manishearth** [comment]
@bors-servo retry

```
  ▶ FAIL [expected PASS] /css/css-color/t421-rgb-values-meaning-b.xht
```

**Pull request merged**
