### PR TITLE
Implement 'labels' attribute on 'labelable elements'

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7965)

### CODE REVIEW

**Comment by jdm** [comment]
@nox could you review this?

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer +S-needs-code-changes 


---

Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/element.rs, line 1862 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7965#-K0WhMQef7yKoTkHk7SA)** ([raw file](https://github.com/servo/servo/blob/e085c3ef1c149aaa396f26e3d7fcaf676ee59685/components/script/dom/element.rs#L1862)):</sup>
Elements' IDs are stored as `AttrValue::Atom` values, we could use it if we use an atom for the `label` attribute on `HTMLLabelElement`. Either do it in that PR or file a follow-up issue.


---

<sup>**[components/script/dom/element.rs, line 1875 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7965#-K0WhNsohRgL8atrh2HO)** ([raw file](https://github.com/servo/servo/blob/e085c3ef1c149aaa396f26e3d7fcaf676ee59685/components/script/dom/element.rs#L1875)):</sup>
You didn't include that rule:

> If the for attribute is not specified, but the label element has a labelable element descendant, then the first such descendant in tree order is the label element's labeled control.


---

<sup>**[components/script/dom/element.rs, line 1855 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7965#-K0Wgt1Rc7NciNRos_UF)** ([raw file](https://github.com/servo/servo/blob/a8e512ecf822e0a5a289047bc8cbdbe7bd43e447/components/script/dom/element.rs#L1855)):</sup>
I'm not convinced by the `LabelableElement` trait, wouldn't it be simpler to define `labels()` on `Element` like how `ParentNode`'s methods are defined on `Node` as helpers and called from the actual interfaces that implement them through an upcast

If traits are the way to go, we should file a follow-up to rewrite `ParentNode` and friends as traits.

Cc. @jdm @Ms2ger


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7965)

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/element.rs, line 1855 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7965#-K0Wgt1Rc7NciNRos_UF)** ([raw file](https://github.com/servo/servo/blob/a8e512ecf822e0a5a289047bc8cbdbe7bd43e447/components/script/dom/element.rs#L1855)):</sup>
I don't see a need for the trait either.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7965)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/element.rs, line 1855 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7965#-K0Wgt1Rc7NciNRos_UF)** ([raw file](https://github.com/servo/servo/blob/a8e512ecf822e0a5a289047bc8cbdbe7bd43e447/components/script/dom/element.rs#L1855)):</sup>
Aww I thought I was being clever with it :P

I'll definitely change it, but is there any reason not to? Extra unnecessary complexity? Seems like an easy way to isolate methods to certain Element types


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7965)

**Comment by frewsxcv** [comment]
Addressed all the comments. Let me know how this looks.

**Comment by frewsxcv** [comment]
I just noticed that some of this code will overlap with a couple of the methods on `<label>` elements. I'll plan on implementing those after this merges and making sure it doesn't get repeated.

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes +S-awaiting-answer 


---

Reviewed 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlelement.rs, line 321 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7965#-K1Ono1Jn0V5a70ZX_Z-)** ([raw file](https://github.com/servo/servo/blob/4b45f9765e159f7c9806b9a25236790c26151a57/components/script/dom/htmlelement.rs#L321)):</sup>
Please match against the type ID as usual.


---

<sup>**[components/script/dom/htmlelement.rs, line 347 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7965#-K1PAlcC0bR7xC86_tkH)** ([raw file](https://github.com/servo/servo/blob/4b45f9765e159f7c9806b9a25236790c26151a57/components/script/dom/htmlelement.rs#L347)):</sup>
Can you explain to me this part of the code like I am 5? I can't make sense out of it. :/


---

<sup>**[components/script/dom/htmlinputelement.rs, line 344 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7965#-K1OoXsN7v9tQ_PzvXla)** ([raw file](https://github.com/servo/servo/blob/4b45f9765e159f7c9806b9a25236790c26151a57/components/script/dom/htmlinputelement.rs#L344)):</sup>
 There is no need to upcast when calling `window_from_node`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7965)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/htmlelement.rs, line 347 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7965#-K1PAlcC0bR7xC86_tkH)** ([raw file](https://github.com/servo/servo/blob/4b45f9765e159f7c9806b9a25236790c26151a57/components/script/dom/htmlelement.rs#L347)):</sup>
I'm going to pause on this PR briefly and implement `<label>` `control` attribute because it might clear this up


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7965)

**Comment by frewsxcv** [comment]
This is reviewable.

**Comment by nox** [comment]
Reviewed 12 of 12 files at r3.
Review status: 15 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/htmlelement.rs, line 347 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7965#-K1PAlcC0bR7xC86_tkH)** ([raw file](https://github.com/servo/servo/blob/4b45f9765e159f7c9806b9a25236790c26151a57/components/script/dom/htmlelement.rs#L347)):</sup>
You don't seem to use anything related to label's control attribute, am I wrong?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7965)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/htmlelement.rs, line 347 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7965#-K1PAlcC0bR7xC86_tkH)** ([raw file](https://github.com/servo/servo/blob/4b45f9765e159f7c9806b9a25236790c26151a57/components/script/dom/htmlelement.rs#L347)):</sup>
Not directly, but shared logic with `first_labelable_descendant`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7965)

**Comment by frewsxcv** [comment]
@nox Did you see any other issues here?

**Comment by frewsxcv** [comment]
Rebased

**Comment by nox** [comment]
Just one nit and we are done.

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 8 of 8 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlinputelement.rs, line 344 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7965#-K1OoXsN7v9tQ_PzvXla)** ([raw file](https://github.com/servo/servo/blob/4b45f9765e159f7c9806b9a25236790c26151a57/components/script/dom/htmlinputelement.rs#L344)):</sup>
Please change this.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7965)

**Comment by frewsxcv** [comment]
Comment has been addressed

**Comment by nox** [comment]
@bors-servo r+


---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7965)

**Pull request merged**
