### PR TITLE
Trigger mozbrowsererror event when a pipeline fails.

### PR DESCRIPTION
**Pull request by asajeffrey**
Addresses part of #10334 (it fires the event, but does not include a backtrace).

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10551)

### CODE REVIEW

**Comment by asajeffrey** [comment]
It could do with a test, but this requires more infrastructure for testing panics.

**Comment by paulrouget** [comment]
Is there a way to test that manually? To experiment with this event in browserhtml.

**Comment by Ms2ger** [comment]
r? @jdm 

I know you're busy, but you seem to be the only reviewer for mozbrowser code.

**Comment by asajeffrey** [comment]
@paul: I added --random-pipeline-closure-probability so we could test random pipeline failures. Would that do the trick?

**Comment by asajeffrey** [comment]
Grr, that was meant for @paulrouget oops!

**Comment by paulrouget** [comment]
> @paul: I added --random-pipeline-closure-probability so we could test random pipeline failures. Would that do the trick?

We need 2 things:
- being able to write a wpt test
- being able to experiment with this new mozbrowser event in browserhtml. We don't want to build integrate this feature "blindly"

Not sure what that would look like. What would `--random-pipeline-closure-probability` do exactly? And maybe we want to be able to tell which pipeline to crash/close (`--force-close-pipeline 1,2`).

**Comment by asajeffrey** [comment]
@paulrouget `--random-pipeline-closure-probability=P` causes the constellation to shut down a random pipeline with probability P per event.  This is almost what we want, but may end up shutting down the browser.html pipeline as well, which is not what we're after.

We have a lot of the tools to write wpt tests that use this to test panic, I've not put the pieces together yet, it's on my queue (#10568).

**Comment by jdm** [comment]
Sounds like @paulrouget wants the deterministic panics I suggested in #10144.

**Comment by asajeffrey** [comment]
@jdm `--random-pipeline-closure-probability=1` is pretty deterministic, it just is a bit brutal :)

**Comment by asajeffrey** [comment]
Rebased.

**Comment by jdm** [comment]
r=me with this change.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[components/compositing/constellation.rs, line 1905 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10551#-KFeszq8Z4wx_31HEZz0:-KFeszq99558_katyWzs:-2065569921) ([raw file](https://github.com/servo/servo/blob/aef2f0c09a5c1483f83049f3ef34c0796ee398a0/components/compositing/constellation.rs#L1905)):*
Let's invert this and safe a level of indentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10551#-:-KFetf2Ophl0M1MJAau3:-919915990)*

**Pull request merged**
