### PR TITLE
Prepare for error reporting in workers.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13174)

### CODE REVIEW

**Comment by nox** [comment]
One question but otherwise r=me.

-S-awaiting-review +S-awaiting-answer 

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/dom/bindings/global.rs, line 295 \[r1\]](https://reviewable.io:443/reviews/servo/servo/13174#-KQym0fAOPAca_PJVmQe:-KQym0fAOPAca_PJVmQf:bc3nssd) ([raw file](https://github.com/servo/servo/blob/b3050855e7cb63b6398540ddb7a5e808ac55be3c/components/script/dom/bindings/global.rs#L295)):*
> ```Rust
>         match *self {
>             GlobalRef::Window(ref window) => window.report_an_error(error_info, value),
>             GlobalRef::Worker(_) => (),
> ```

Will we ever report errors on `Worker`? If not, could we use `if let` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13174#-:-KQymfUMfk1oJWYosS8E:bjiu3q5)*

**Comment by Ms2ger** [comment]
@bors-servo r=nox

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[components/script/dom/bindings/global.rs, line 295 \[r1\]](https://reviewable.io:443/reviews/servo/servo/13174#-KQym0fAOPAca_PJVmQe:-KQyo6OqdCqJOZDRcM4B:b-44qc4x) ([raw file](https://github.com/servo/servo/blob/b3050855e7cb63b6398540ddb7a5e808ac55be3c/components/script/dom/bindings/global.rs#L295)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Will we ever report errors on `Worker`? If not, could we use `if let` here?
</details>
Yeah, working on that right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13174#-:-KQyoIJYdLMe7qJblufi:b-ko8oan)*

**Comment by Ms2ger** [comment]
@bors-servo retry #13059

AAARGH

**Pull request merged**
