### PR TITLE
Only display text carets in text inputs

### PR DESCRIPTION
**Pull request by j3parker**
For #7756

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7764)

### CODE REVIEW

**Comment by pcwalton** [comment]
Can we reftest this?

**Comment by pcwalton** [comment]
For example, by focusing a submit button with JS and checking to make sure no caret shows up.

**Comment by j3parker** [comment]
I can do that!

I can't think of a good way to reftest that there is no caret in the buttons at all (i.e. that reftest seems like it'd still pass before these changes)

**Comment by pcwalton** [comment]
Would it still pass even if you focus the buttons with JS?

**Comment by j3parker** [comment]
@pcwalton is this what you had in mind? It fails before the change and passes after. I had to add some css to make them match because of servo.css; I'm not sure if that's cool. I tried to do it in the least opinionated way I could.

**Comment by j3parker** [comment]
(The focusing is unnecessary for the test, though.)

**Comment by pcwalton** [comment]
@j3parker That looks great, thank you!

**Comment by metajack** [comment]
@bors-servo retry

- build canceled while addressing infra issues

**Comment by jdm** [comment]
@bors-servo: retry
* #7731 and #7787

**Pull request merged**
