### PR TITLE
window.performance.now values are way too big #5690; r=jdm

### PR DESCRIPTION
**Pull request by ghost**
Changed the operator and updated the wpt-test for `hr-time`.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6292)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- tests/wpt/include.ini @ r2
- tests/wpt/metadata/hr-time/test_cross_frame_start.html.ini @ r1
- tests/wpt/web-platform-tests/hr-time/basic.html @ r3

---

<sup>**[tests/wpt/web-platform-tests/hr-time/basic.html, line 33 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6292#-Jr3DVEcBmHCMsI5zrMA)** ([raw file](https://github.com/servo/servo/blob/f5baf646283f176015188e1caf22b315eefd5c81/tests/wpt/web-platform-tests/hr-time/basic.html#L33)):</sup>
Don't use tabs, please

---

<sup>**[tests/wpt/web-platform-tests/hr-time/basic.html, line 35 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6292#-Jr3DbTez6uzWpooBUaP)** ([raw file](https://github.com/servo/servo/blob/f5baf646283f176015188e1caf22b315eefd5c81/tests/wpt/web-platform-tests/hr-time/basic.html#L35)):</sup>
"Well within" isn't really true because Date() can use a relatively inaccurate clock (istr that this is especially a problem on WIndows). Therefore the margin here is to allow for inaccurate measurements.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6292)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- components/script/dom/performance.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6292)

**Comment by Wafflespeanut** [comment]
@jgraham @jdm Thanks for the reviews. I'm sorry about the tabs. I've fixed those and the descriptions. Looking forward to your review :)

**Comment by jgraham** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- hr-time.log @ r5
- tests/wpt/web-platform-tests/hr-time/basic.html @ r4

---

<sup>**[tests/wpt/web-platform-tests/hr-time/basic.html, line 35 \[r5\]](https://reviewable.io:443/reviews/servo/servo/6292#-Jr3P6Hj1uF0d7xlhKcw)** ([raw file](https://github.com/servo/servo/blob/c2979cbff61df07c140796d723e81a05d2bb66a2/tests/wpt/web-platform-tests/hr-time/basic.html#L35)):</sup>
It's a bit pedantic, but this seems more like a comment in the source than a description of what's being asserted. A better assert might be "high resolution time value increased by approximately the same amount as time from date object".

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6292)

**Comment by Wafflespeanut** [comment]
Thanks again @jgraham. I've updated the description :)

**Comment by jgraham** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- tests/wpt/web-platform-tests/hr-time/basic.html @ r6

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6292)

**Comment by Wafflespeanut** [comment]
@jdm I've squashed all my commits into a single commit. Please try & review it :)

**Comment by jdm** [comment]
Thanks!

**Comment by Wafflespeanut** [comment]
@jdm @jgraham Thanks for your help :)

**Pull request merged**
