### PR TITLE
Rewrite Taskcluster integration

### PR DESCRIPTION
**Pull request by SimonSapin**
This rewrites this repository’s integration with Taskcluster to have a decision task that runs an in-tree Python script to schedule a graph of other tasks with inter-dependencies, saved build artifacts, Docker images built from in-tree `Dockerfile`s, etc. This also adds support fail daily tasks, run automatically every 24 hours. See `etc/ci/taskcluster/README.md` for more details.

Example of a green build with web-platform-tests enabled: https://tools.taskcluster.net/groups/aDL0pUBkSmuhezT1OF80_g

For now this PR only enables one task, equivalent to Buildbot’s `linux-dev` job. (Running Tidy and other linting tools, compiling in debug mode, and running unit tests.) At this time Homu does **not** yet block PRs from merging on a successful result from Taskcluster, but I plan to do this soon after this PR lands.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21776)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r? @Manishearth 

I’ve included the commit history from https://github.com/servo/servo-taskcluster-experiments/ for historical interest, but feel free to ignore it and only look at the overall diff.

**Review by Manishearth — APPROVED** [review]
r=me

Could you add docstrings to all of the DecisionTask methods?

**Comment by aneeshusa** [comment]
Wow, this is awesome! Didn't think you'd leap all the way to decision tasks and all on TC in one PR, super glad to see this!

**Comment by SimonSapin** [comment]
Yeah it took a while to figure all this out, but now we’ll hopefully be able to make further changes much more easily :)

**Pull request merged**
