### PR TITLE
Add start_time to resource timing.

### LINKED ISSUE #21254: PerformanceResourceTiming: startTime
In components/net/http_loader.rs::http_fetch we need to set start_time for the PerformanceEntry member of PerformanceResourceTiming. This will be equal to either fetch_start or redirect_start.

Spec: https://w3c.github.io/resource-timing/#dfn-starttime

### PR DESCRIPTION
**Pull request by pajamapants3000**
`start_time` property added to `ResourceFetchTiming`, which enables the setting of `start_time` in the `PerformanceEntry` member of `PerformanceResourceTiming`.

Following the specification at https://w3c.github.io/resource-timing/#dfn-starttime, `start_time` is set to the value of `redirect_start` if redirection occurs and the timing allow check passes. Otherwise it has the same value as `fetch_start`.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #21254

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by pajamapants3000** [comment]
I question whether the timing logic belongs inside `set_attribute`. I went with that approach for consistency with existing code, but it seems like the caller already needs to know what times to set and when. Feels like the logic is being split into two places. I could change it so `set_attribute` just sets the time to whatever the caller says (at least for `start_time`) and just have the caller be entirely responsible for setting the time correctly. It already _mostly_ is.

**Comment by jdm** [comment]
Yeah, I'm on the fence about it. Let's merge it the way it's written and if it turns out to be difficult to reason about in the future we can rewrite it. Thanks!

@bors-servo r+

**Comment by jdm** [comment]
And thank you for writing those unit tests, too!

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Pull request merged**
