### PR TITLE
Docs and cleanup after moving tidy

### PR DESCRIPTION
**Pull request by edunham**
Missed a couple things in https://github.com/servo/servo/pull/10590

`licenseck.py` was moved into `tidy/servo_tidy/licenseck.py` by the prior PR

r? @larsbergstrom (sorry for PR spamming today)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10635)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10635)*

**Comment by jdm** [comment]
@bors-servo: retry
* #10549

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #10549

**Pull request merged**
