### PR TITLE
Make canvas send their data themselves to other canvas

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11506)

### CODE REVIEW

**Comment by Ms2ger** [comment]
> The command "bash etc/ci/lockfile_changed.sh" exited with 1.

**Comment by Ms2ger** [comment]
r+ with that fixed

**Comment by nox** [comment]
Cc @emilio ^

**Comment by nox** [comment]
This just needs synchronisation to do the right thing.

**Comment by emilio** [comment]
I'd prefer a try run dirtying the canvas directly here, but if you're on a rush or something feel free to land with the comment and file a follow-up for it.

@bors-servo: try

-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/canvasrenderingcontext2d.rs, line 382 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11506#-KKP63elNX4EQj4oyU8C:-KKP63elNX4EQj4oyU8D:-761611680) ([raw file](https://github.com/servo/servo/blob/35788bc4be6197e0a854ec9e3c478a1b95a5bcc6/components/script/dom/canvasrenderingcontext2d.rs#L382)):*
> ```Rust
>                 source_rect,
>                 smoothing_enabled,
>                 sender));
> ```

I find the alignment here weird, but it's not a blocker. A comment either here or in `draw_image_in_other` telling that the synchronisation is necessary to avoid the tests taking screenshots too early could be desirable.

Ideally, would just mark the other canvas as dirty here and avoid all the roundtrip work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11506#-:-KKP6yQrngscN2jv2gDF:1487976273)*

**Comment by emilio** [comment]
@bors-servo: r+

Really tricky race!

**Pull request merged**
