### PR TITLE
Only generate structs file for the current build

### PR DESCRIPTION
**Pull request by upsuper**
This PR changes build_gecko.rs to only generate the `structs.rs` for the current build (rather than both), depending on whether `gecko_debug` feature is set.

The in-tree files are switched to use the previous release one, because that's what we currently use for stylo test and it is in general what we really care about. For this change, `gecko_debug` mode is removed from Servo CI (in `build-geckolib`) with the assumption that people general do that build locally for stylo development, so it is less likely to be broken than release.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18753)

### CODE REVIEW

**Comment by upsuper** [comment]
Gecko try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=4f0109e53db4bb11b4e4bf4311cc2839bf50a0fa

**Review by emilio — APPROVED** [review]
r=me, as long as it's green.

**Comment by emilio** [comment]
@bors-servo p=2

 * Prone to bitrot
 * Blocking every PR that needs a bindings update.

**Comment by emilio** [comment]
@bors-servo r-

```
18.38s$ ./mach test-stylo
   Compiling size_of_test v0.0.1 (file:///home/travis/build/servo/servo/components/size_of_test)
   Compiling nsstring_vendor v0.1.0 (file:///home/travis/build/servo/servo/components/style/gecko_bindings/nsstring_vendor)
   Compiling style v0.0.1 (file:///home/travis/build/servo/servo/components/style)
   Compiling stylo_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/stylo)
error[E0243]: wrong number of type arguments: expected 1, found 0
  --> /home/travis/build/servo/servo/components/style/gecko_bindings/sugar/ns_com_ptr.rs:26:6
   |
26 | impl nsCOMPtr {
   |      ^^^^^^^^ expected 1 type argument
error: aborting due to previous error(s)
error: Could not compile `style`.
```

**Comment by upsuper** [comment]
Oh, because we run the test without `gecko_debug`... then I guess we need to use the files for release I guess.

**Comment by upsuper** [comment]
Hmmm, so geckolib uses debug, but test-stylo uses release...

**Comment by upsuper** [comment]
Oh, wait, we build both debug and release geckolib in CI... sounds like we would have to keep both struct files?

**Comment by upsuper** [comment]
@emilio there is some non-trivial change in the new commits, specifically, `build-geckolib` no longer uses `gecko_debug`, because we don't have both files in tree.

This increases the risk that something passes Servo CI but busts Gecko autoland, if it only breaks style with `gecko_debug`. I'm not sure whether this would be a usual case.

There are some code difference in `gecko_debug` mode, but I would expect most developers who are touching that code should be using a Gecko build, and as far as Gecko builds for them locally, the additional build mode on CI may have less value.

**Comment by emilio** [comment]
Ok, I guess I'm fine with this.

r=me, with the new test-stylo setup documented somewhere (even if it's `tests/unit/stylo/lib.rs`)

**Comment by upsuper** [comment]
`test-stylo` isn't changed, actually. It always test `structs_release.rs` since it never passes `gecko_debug`. This only changes the behavior of `build-geckolib`.

**Comment by emilio** [comment]
Hmm, oh, right... So there's no way to build with `gecko_debug` anymore from the servo repo... But there wasn't before any way to build with `debug_assertions` but not `gecko_debug`, is that right?

**Comment by upsuper** [comment]
`test-stylo` builds with `debug_assertions` but not `gecko_debug`. That's a weird one, though...

**Comment by upsuper** [comment]
So before this change,
* `test-stylo` -> `debug_assertions`, `structs_release.rs`
* `test-stylo --release` -> `!debug_assertions`, `structs_release.rs`
* `build-geckolib` -> `debug_assertions`, `structs_debug.rs`
* `build-geckolib --release` -> `!debug_assertions`, `structs_release.rs`

**Comment by emilio** [comment]
Yeah, I meant there wasn't any way to do that before via `build-geckolib`.

Ok, last question. It means now, since we always add the release bindings, that there's no way to update them locally from a debug build, and we always need to use try, that's slightly annoying I guess, but I guess it's fine.

**Comment by upsuper** [comment]
Yes, that's right. I think in general a change which touch bindings should really go through try before landing the servo side, so I guess that wouldn't be a big problem.

**Comment by emilio** [comment]
Yeah, but it's a problem when other people also do changes in parallel, and it forces you to do an extra try run rebased to autoland, instead of just `./mach build toolkit/library/rust` rebased to autoland.

Though I guess it's acceptable.

@bors-servo r+

**Pull request merged**
