### PR TITLE
Make it possible to navigate with the keyboard in the webxr glwindow view

### PR DESCRIPTION
**Pull request by paulrouget**
The glwindow is not interactive. With this PR we can use the arrow key to look up, down, right and left.

This will make debugging a lot easier.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24324)

### CODE REVIEW

**Comment by paulrouget** [comment]
This was not as easy as I expected. We need to process events for all windows, but the glutin app never had any reference to the xr' glwindow.

Managing multiple windows will be necessary in the future, so this work is not useless, but it's not complete either (see inline comment about multiple windows vs. multiple browser).

**Comment by asajeffrey** [comment]
I guess there's a question about which bits of logic should live in servo and which in the glwindow. If we want to put everything in servo this looks fine to me. We'll need most of it at some point when we handle multliple windows properly. You can r=me.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/3711ea91fd1d438265163d0bd37af7bfdb2ea9f8/ports/glutin/headless_window.rs#L135-L137

**Comment by CYBAI** [comment]
Failure in magicleap build:

```
error[E0053]: method `wait_for_animation_frame` has an incompatible type for trait
   --> /Users/worker/.cargo/git/checkouts/webxr-702fa5244eec1e69/13a57d7/webxr/magicleap/mod.rs:383:5
    |
383 |     fn wait_for_animation_frame(&mut self) -> Frame {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found struct `webxr_api::frame::Frame`
    |
    = note: expected type `fn(&mut magicleap::MagicLeapDevice) -> std::option::Option<webxr_api::frame::Frame>`
               found type `fn(&mut magicleap::MagicLeapDevice) -> webxr_api::frame::Frame`
```

**Comment by paulrouget** [comment]
https://github.com/servo/webxr/pull/64

**Pull request merged**
