### PR TITLE
Support WebGL2 contexts in immersive mode

### LINKED ISSUE #26138: webgl2 contexts don't render anything in immersive mode
I made a fork of https://threejs.org/examples/webxr_vr_lorenzattractor.html, added a `<canvas></canvas>` to the body and created a webgl2 context and passed appropriate `context` and `canvas` parameters when creating the WebGLRenderer object. It renders fine in windowed mode, but immersive mode shows that it's never rendering to the opaque framebuffer.

### PR DESCRIPTION
**Pull request by jdm**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #26138

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* #25258

**Pull request merged**
