### PR TITLE
Remove ConstellationChan.

### PR DESCRIPTION
**Pull request by Ms2ger**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy --faster` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because _____

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. 

It's a pointless abstraction that propagates the obsolete chan terminology,
swaps the order in which the sender and receiver are returned, and hides a
source of panics.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11270)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Yes yes yes!

**Comment by asajeffrey** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/constellation/constellation.rs, line 327 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11270#-KI8X_0gF56uKhbK1ZaP:-KI8X_0hu6wtYU7w_4N7:-323563518) ([raw file](https://github.com/servo/servo/blob/bb2a00048e80b4987e94137cdffa44fd9e2526f9/components/constellation/constellation.rs#L327)):*
> ```Rust
>     pub fn start(state: InitialConstellationState) -> Sender<FromCompositorMsg> {
>         let (ipc_script_sender, ipc_script_receiver) =
>             ipc::channel::<FromScriptMsg>().expect("ipc channel failure");
> ```

Do we need to provide the type arguments here? Can we not just use `ipc::channel().expect("ipc channel failure")`?

---

*[components/layout/layout_thread.rs, line 1084 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11270#-KI8Y1WDLCQFCdR-0o4a:-KI8Y1WEne6pAhNzr03v:901808989) ([raw file](https://github.com/servo/servo/blob/bb2a00048e80b4987e94137cdffa44fd9e2526f9/components/layout/layout_thread.rs#L1084)):*
> ```Rust
>                 rw_data.constellation_chan
>                        .send(ConstellationMsg::ViewportConstrained(self.id, constraints))
>                        .unwrap();
> ```

This is so much cleaner, hooray!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11270)*

**Comment by nox** [comment]
@bors-servo r-

Homu confused, will r+ again.

**Pull request merged**
