### PR TITLE
Prevent the error from triggering a page error in Worker-nested-importScripts-error

### LINKED ISSUE #23511: Intermittent error in /workers/Worker-nested-importScripts-error.html
```
  ▶ ERROR [expected OK] /workers/Worker-nested-importScripts-error.html
  │   → unexpected token: identifier
  │ 
  └ http://web-platform.test:8000/workers/support/invalidScript.js:1:14
```

### PR DESCRIPTION
**Pull request by Eijebong**
Fixes #23511

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23552)

### CODE REVIEW

**Comment by jdm** [comment]
Needs a `./mach update-manifest`.

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by CYBAI** [comment]
> Error syncing changes upstream. Logs saved in error-snapshot-1560391183233.

I'm guessing this is caused by https://github.com/web-platform-tests/wpt/pull/17272#issuecomment-501284195 so we get the error. The upstream PR will need a rebase 👀

**Pull request merged**
