### PR TITLE
Issue5591 location getter

### PR DESCRIPTION
**Pull request by yodalee**
Issue #5591. Implement getter listed below:
Protocol
Username
Password
Host
Hostname
Port

Notice that in spec, there is condition that url is null. The test is not implemented in this commit, since the url object in location seems always not null. So the test is skip temporarily.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5597)

### CODE REVIEW

**Comment by yodalee** [comment]
Yeah, I found I didn't think it rusty(?) enough, I replace the `unwrap` with `match`, so the case of Err return can be handled correctly.

**Comment by jdm** [comment]
@Ms2ger Are there tests you're looking for that aren't covered by WPT?

**Comment by Ms2ger** [comment]
Testing the getters when using a data URL (I think)

**Comment by yodalee** [comment]
Got a little busy this week, I will (maybe) be back on Friday.

**Comment by jdm** [comment]
Ok!

**Comment by yodalee** [comment]
Where should I put the testing? in `wpt` or other directory?

**Comment by jdm** [comment]
You can write one in tests/wpt/mozilla/tests/mozilla (you'll need to add it to the MANIFEST.json in tests/mozilla/).

**Comment by yodalee** [comment]
There is no such directory unless I rebase to master OAO, but rebase to master will destroy the review right?

**Comment by jdm** [comment]
Ah, yes.

**Comment by yodalee** [comment]
Just ask, I found this:
https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/url/a-element.html
with the testing URL file:
https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/url/urltestdata.txt
It already contain data URL testing. So do I need duplicate a similar one?

**Comment by jdm** [comment]
According to https://github.com/servo/servo/blob/master/tests/wpt/include.ini we don't run those right now. Want to try enabling them?

**Comment by yodalee** [comment]
Enable it. Here is the result:
```
Ran 316 tests (3 parents, 313 subtests)
Expected results: 10
Unexpected results: 306 (FAIL: 305, TIMEOUT: 1)
```
A little tragedy OAO, I will dig into why pass so little.

**Comment by yodalee** [comment]
Is there any way to generate the `*.ini` file that mark all tests to expected FAIL? I don't believe that this can be done by hand.

**Comment by yodalee** [comment]
Is there any way to generate the `*.ini` file that mark all tests to expected FAIL? I don't believe that this can be done by hand.

**Comment by jdm** [comment]
http://mxr.mozilla.org/servo/source/tests/wpt/README.md#71

**Comment by yodalee** [comment]
@jdm Since I will have to attend military training in the middle of May. I will transfer all my issues to @shinglyu, including issues #5591, #5600, #4431.
To issues 5591 and 5600, there are opening Pull Request of them. I suggest I close them and let ShingLyu open new ones.

**Comment by jdm** [comment]
Ok! Thanks for the work you have put in so far :)

**Comment by yodalee** [comment]
Close and transfer to Shinglyu

**Comment by shinglyu** [comment]
Hi @Ms2ger, you mentioned about data url tests, but I can't figure out how to do this in wpt-test. Most of the existing location test uses it's own url as test target, but when I try to use `window.history.pushState()` to set my url as a data url, it fails in both Firefox and Chrome. I guess there are security constrains (though I haven't find the spec yet.) Do you have any suggestions?

**Comment by Ms2ger** [comment]
You could use an iframe with a data URL and check `iframe.contentWindow.location`.

**Comment by shinglyu** [comment]
Smart! I'll move the discussion to #6135. Thanks!

**Pull request closed without merging**
