### PR TITLE
Instead of panicking on broken url, break from the loop and return.

### PR DESCRIPTION
**Pull request by Adenilson**
Bug report on #5365.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5464)

### CODE REVIEW

**Comment by Adenilson** [comment]
It will panic and emit a stack trace e.g. https://gist.github.com/Adenilson/4c19d9659df3fbb2e1ad

**Comment by Adenilson** [comment]
Output after patch: https://gist.github.com/Adenilson/709de33709cc56ee2710

**Comment by jdm** [comment]
```
/html/browsers/history/the-location-interface/security_location_0.sub.htm
-------------------------------------------------------------------------
NOTRUN Accessing location object from different origins doesn't raise SECURITY_ERR exception
TIMEOUT expected CRASH [Parent]
/html/browsers/the-window-object/security-window/window-security.sub.html
-------------------------------------------------------------------------
NOTRUN Window Security testing
TIMEOUT expected CRASH [Parent]
```

**Comment by Adenilson** [comment]
Documented findings in #5467.

**Comment by Adenilson** [comment]
@jgraham FYI.

**Comment by Ms2ger** [comment]
@Adenilson: you just need to update the expectation in this PR

**Comment by metajack** [comment]
Assigned @jdm since he r+ed.

**Comment by Adenilson** [comment]
I tested all combinations of TIMEOUT x {PASS, FAIL, TIMEOUT, CRASH, NOTRUN, ERROR} and it will always end with a “Unexpected results: 1 (NOTRUN: 1)”.

Not to mention that will add around to extra 10s to run the tests in the folder (e.g. html/browsers/history/the-location-interface/).

So I updated the test expectation to disabled, but I would like to ask suggestions for a proper fix in this case.

**Comment by jdm** [comment]
I would expect the following to work:
```
[security_location_0.sub.htm]
  type: testharness
  expect: TIMEOUT
  [Accessing location object from different origins doesn't raise SECURITY_ERR exception]
    expect: NOTRUN
```

**Comment by Ms2ger** [comment]
Rebased as https://github.com/servo/servo/pull/5476.

**Pull request closed without merging**
