### PR TITLE
Allow more valid use of calc expressions

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7400)

### CODE REVIEW

**Comment by pcwalton** [comment]
@dzbarsky Is this ready for review?

**Comment by dzbarsky** [comment]
Yes, it's good to go.

**Comment by SimonSapin** [comment]
Note that the first 19 commits of this are in #7185, which is good to go except that it needs to add support for the `ch` unit (which was added while the PR was waiting on my to review).

**Comment by SimonSapin** [comment]
See also #7496.

**Comment by dzbarsky** [comment]
Rebased this to apply cleanly.

**Comment by jdm** [comment]
Github disagrees.

**Comment by dzbarsky** [comment]
the var() stuff rotted this PR. Rebased again.

**Comment by frewsxcv** [comment]
@dzbarsky In case you missed it, there's a style check failure:

```
./components/style/values.rs:1353: missing space after ,
```

**Comment by SimonSapin** [comment]
Reviewed 1 of 20 files at r1, 8 of 19 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/style/properties.mako.rs, line 1927 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7400#-JyrD1_zPsCIBqU-QmfT)** ([raw file](https://github.com/servo/servo/blob/62238d978f93b5ccae8324dd0a1f53b9eb261d6a/components/style/properties.mako.rs#L1927)):</sup>
Please remove the outdated comment. (It used to explain why percentages were replaced with lengths at parse time.)

---

<sup>**[components/style/values.rs, line 210 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7400#-JyrDoFF-lwl-VmlaOxi)** ([raw file](https://github.com/servo/servo/blob/62238d978f93b5ccae8324dd0a1f53b9eb261d6a/components/style/values.rs#L210)):</sup>
It’s not great that this uses a `Calc` struct that has a `percentage` field while this `Length` type should not allow percentages, but I don’t have a good idea to suggest how to fix this without duplicating a lot of `calc()` code. What do you think?

---

<sup>**[components/style/values.rs, line 398 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7400#-JyrEfeXjsCFt2IAhsqs)** ([raw file](https://github.com/servo/servo/blob/62238d978f93b5ccae8324dd0a1f53b9eb261d6a/components/style/values.rs#L398)):</sup>
This accepts fractional numbers in the input and implicitly rounds them to integers, doesn’t it? See `<integer>` v.s. `<number>` in https://drafts.csswg.org/css-values/#calc-type-checking . I think this can be solved by adding an `Integer` variant to `CalcUnit`.

---

<sup>**[components/style/values.rs, line 447 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7400#-JyrHBb_MO0CAbm_KJiO)** ([raw file](https://github.com/servo/servo/blob/62238d978f93b5ccae8324dd0a1f53b9eb261d6a/components/style/values.rs#L447)):</sup>
Maybe rename this to `CalcLengthOrPercentage`?

---

<sup>**[components/style/values.rs, line 492 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7400#-JyrFkhflSx6sxJDjfnC)** ([raw file](https://github.com/servo/servo/blob/62238d978f93b5ccae8324dd0a1f53b9eb261d6a/components/style/values.rs#L492)):</sup>
Change this to `Ok(Token::Delim('/')) if expected_unit != CalcUnit::Integer => {`. (See previous comment.)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7400)

**Comment by dzbarsky** [comment]
Rebased. @SimonSapin review ping?

**Comment by mbrubeck** [comment]
Reviewed 1 of 6 files at r4, 3 of 7 files at r5.
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7400)

**Comment by mbrubeck** [comment]
Reviewed 2 of 19 files at r2, 4 of 7 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7400)

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[components/style/values.rs, line 210 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7400#-JyrDoFF-lwl-VmlaOxi)** ([raw file](https://github.com/servo/servo/blob/62238d978f93b5ccae8324dd0a1f53b9eb261d6a/components/style/values.rs#L210)):</sup>
Yeah, I didn't like it either. It works because of the CalcUnit enum but I agree it would be nice if we could make the type system enforce this for us =/


---

<sup>**[components/style/values.rs, line 398 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7400#-JyrEfeXjsCFt2IAhsqs)** ([raw file](https://github.com/servo/servo/blob/62238d978f93b5ccae8324dd0a1f53b9eb261d6a/components/style/values.rs#L398)):</sup>
You're right, good catch.


---

<sup>**[components/style/values.rs, line 492 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7400#-JyrFkhflSx6sxJDjfnC)** ([raw file](https://github.com/servo/servo/blob/62238d978f93b5ccae8324dd0a1f53b9eb261d6a/components/style/values.rs#L492)):</sup>
Interesting. I figured |transition-timing-function: steps(calc(4 / 2));| would be valid but Chrome doesn't accept it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7400)

**Comment by mbrubeck** [comment]
I've reviewed the new changes here and they look good. All previous comments have been addressed except this one by @SimonSapin:

>  It’s not great that this uses a Calc struct that has a percentage field while this Length type should not allow percentages, but I don’t have a good idea to suggest how to fix this without duplicating a lot of calc() code. What do you think?

@dzbarsky and @SimonSapin, do you want to do anything about this before merging this PR?  If not, I think it's ready to squash and land.

**Comment by dzbarsky** [comment]
We can always change this in a followup. I don't think it makes sense to block landing this if we don't know how to improve it right now.


---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7400)

**Comment by mbrubeck** [comment]
In that case, please squash any commits you want squashed, and this can land with r=mbrubeck.

**Comment by eefriedman** [comment]
```
Unexpected Results
==================

/_mozilla/mozilla/calc.html
---------------------------
FAIL calc for border-top-left-radius
FAIL calc for border-bottom-left-radius
FAIL calc for border-top-right-radius
FAIL calc for border-bottom-right-radius
/_mozilla/css/last_of_type_pseudo_a.html
----------------------------------------
FAIL [Parent]
```

**Comment by dzbarsky** [comment]
Fixed the calc tests and the pseudo test may be a flake (didn't reproduce locally).

**Comment by dzbarsky** [comment]
Yeah the pseudo thing is probably https://github.com/servo/servo/issues/8191

**Comment by eefriedman** [comment]
I'm not sure exactly why, but /css21_dev/html4/font-146.htm is consistently failing.

**Comment by dzbarsky** [comment]
The problem is the following declaration: div.test { font: 4em/-2em serif; background: red; color: yellow; }
The text in the div should not be visible, because the line-height is negative. Previously, servo didn't know how to parse 4em for the font-size, so the declaration would be ignored. We are now parsing that part, but are not yet handling the line-height, so the text shows up and the test breaks. We should fix font parsing, but this is follow-up fodder.

**Comment by eefriedman** [comment]
Fine; I'll r+ if you update the expected result.

**Comment by dzbarsky** [comment]
Looks like I was wrong. The actual problem is that we lost the check for negative line heights...

**Comment by SimonSapin** [comment]
```
Unexpected Results
==================

/2dcontext/drawing-images-to-the-canvas/drawimage_canvas_12.html
----------------------------------------------------------------
TIMEOUT [Parent]
```

Sounds maybe unrelated?

**Comment by SimonSapin** [comment]
@bors-servo retry

#8292

**Pull request merged**
