### PR TITLE
euclid update

### PR DESCRIPTION
**Pull request by paulrouget**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20156)

### CODE REVIEW

**Comment by paulrouget** [comment]
Infra issue?

@bors-servo retry

**Comment by paulrouget** [comment]
And Taskcluster says: `It looks like rustup is not installed`.

**Comment by jdm** [comment]
Taskcluster can be ignored.

**Pull request merged**
