### PR TITLE
Remove overflow references on AssignBSizesAndStoreOverflow code

### PR DESCRIPTION
**Pull request by DavidBM**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10061)

### CODE REVIEW

**Comment by Manishearth** [comment]
r? @mbrubeck 

(I'm not sure why this change is being made :smile: )

**Comment by tschneidereit** [comment]
@Manishearth, @mbrubeck suggested this as a good first change for @DavidBM, whom I'm teaching the basics of contributing to Servo at a community event here in Berlin.

**Comment by Manishearth** [comment]
@bors-servo r+

Ah, okay. 

Thanks for the change!

**Comment by KiChjang** [comment]
@DavidBM Don't worry, nothing's wrong with your code, we just have intermittent issues that occassionally pop up when we run our WPT tests.

Also, welcome to Servo!

@bors-servo retry
* #9012

**Comment by KiChjang** [comment]
@bors-servo retry
* #9278

**Comment by DavidBM** [comment]
Thanks you :) 
There is a lot of automation here!

**Pull request merged**
