### PR TITLE
Refactor WebGLPaintTask to prevent creating extra IPC channels

### LINKED ISSUE #9228: Refactor WebGLPaintTask to prevent creating extra IPC channels
Right now we create an IPC channel when we create a `WebGLPaintTask`. 

When the context creation fails, this channel is not returned and thus created in vain.

The mspc channel is necessary, since the task makes use of it, but it should be easy to wait until we know the task has succeeded to create the IPC channel.

Code: https://github.com/servo/servo/blob/master/components/canvas/webgl_paint_task.rs#L188-L234

### PR DESCRIPTION
**Pull request by coder543**
closes #9228

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9233)

### CODE REVIEW

**Comment by coder543** [comment]
Hmm, I did this pull on my fork when it was only one commit ahead of master. I didn't expect making another commit after the fact to show up here.

**Comment by KiChjang** [comment]
@coder543 You really should create another branch on your fork when opening new PRs. That way you can avoid this problem.

**Comment by coder543** [comment]
understandable. I just created a new branch and a new pull request.

**Pull request closed without merging**
