### PR TITLE
Update various dependencies

### PR DESCRIPTION
**Pull request by jdm**
This brings us more up to date for dependencies that rely on font-related crates.

### CODE REVIEW

**Comment by CYBAI** [comment]
```
error: multiple packages link to native library `freetype`, but a native library can be linked only once
package `freetype-sys v0.11.0`
    ... which is depended on by `freetype v0.5.1`
    ... which is depended on by `font-kit v0.9.0`
    ... which is depended on by `canvas v0.0.1 (/repo/components/canvas)`
    ... which is depended on by `compositing v0.0.1 (/repo/components/compositing)`
    ... which is depended on by `constellation v0.0.1 (/repo/components/constellation)`
    ... which is depended on by `libservo v0.0.1 (/repo/components/servo)`
    ... which is depended on by `servo v0.0.1 (/repo/ports/winit)`
links to native library `freetype`
package `servo-freetype-sys v4.0.3`
    ... which is depended on by `freetype v0.4.1`
    ... which is depended on by `webrender v0.61.0 (https://github.com/jdm/webrender?branch=crash-backtrace#34d968ad)`
    ... which is depended on by `canvas v0.0.1 (/repo/components/canvas)`
    ... which is depended on by `compositing v0.0.1 (/repo/components/compositing)`
    ... which is depended on by `constellation v0.0.1 (/repo/components/constellation)`
    ... which is depended on by `libservo v0.0.1 (/repo/components/servo)`
    ... which is depended on by `servo v0.0.1 (/repo/ports/winit)`
also links to native library `freetype`
```

**Comment by jdm** [comment]
Bleah, I think we'll need to get webrender onto the newer freetype and then update to the latest webrender before these changes can merge.

**Comment by jdm** [comment]
Waiting for https://github.com/servo/font-kit/pull/159 to be published, then we'll need to update raqote to use font-kit 0.10, then we can try updating webrender to bring in https://github.com/servo/webrender/commit/562be3c5f7656320db4a4fb9ae25155d39961ef1.

**Comment by jdm** [comment]
Also requires https://github.com/servo/rust-harfbuzz/pull/185.

**Review by Manishearth — APPROVED** [review]
r=me when necessary

**Comment by jdm** [comment]
There are a lot of mac failures that look like:
```
  ▶ CRASH [expected FAIL] /css/CSS2/tables/fixed-table-layout-003e12.xht
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ 12 threads are still running after shutdown (bad).
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ Stack trace
  │    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  │    1: core::fmt::write
  │    2: std::io::Write::write_fmt
  │    3: servo::backtrace::print
  │    4: servo::install_crash_handler::handler
  │    5: __sigtramp
  │    6: __os_unfair_lock_unowned_abort
  │    7: __os_unfair_lock_unlock_slow
  │    8: _arena_dalloc_bin_locked_impl
  │    9: __rjem_je_tcache_bin_flush_small
  │   10: _tcache_flush_cache
  │   11: _tcache_destroy
  │   12: __rjem_je_tsd_cleanup
  │   13: _tsd_cleanup_wrapper
  │   14: __pthread_tsd_cleanup
  │   15: __pthread_exit
  │   16: __pthread_body
  └   17: __pthread_start
```
Wonderful!

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by jdm** [comment]
@bors-servo retry
* #25522

**Pull request merged**
