### PR TITLE
style: Stop threading the ElementData around the invalidator. 

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18904)

### CODE REVIEW

**Comment by emilio** [comment]
This (and all the patches I submitted today) are green, fwiw.

**Comment by emilio** [comment]
@heycam can you review https://github.com/servo/servo/pull/18904/commits/953d9f157e3ac42d92eb45aea325361e8bdc7194 and, if it looks good, land with `r=jdm,nox,SimonSapin,heycam`?

This contains a handful other PRs I opened today, but that's because I don't want to wait forever for them to merge.

**Comment by emilio** [comment]
Try at https://treeherder.mozilla.org/#/jobs?repo=try&revision=11018603e15ce447e177efc4802f01bbe7d6d676

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flexbox_columns.htm
  └   → /css-flexbox-1_dev/html/flexbox_columns.htm 44f10cc94c33b872592bff82ba0dc396269d04ac
/css-flexbox-1_dev/html/reference/flexbox_columns-ref.htm 4ebdf782f0436f2dfbda58e09a2fbd44277bc27b
Testing 44f10cc94c33b872592bff82ba0dc396269d04ac == 4ebdf782f0436f2dfbda58e09a2fbd44277bc27b
```

**Comment by emilio** [comment]
Gah, this is because of #18893... I can drop that patch worst case but...

## Rendering

rendering

## Ref

ref

Aand the fun part, I cannot repro locally.

**Comment by jdm** [comment]
```
{"status": "FAIL", "group": "default", "message": "/css-flexbox-1_dev/html/flexbox_columns.htm 56423dfb00c3f6864391b3b360ed467db289c1fa\n/css-flexbox-1_dev/html/reference/flexbox_columns-ref.htm 4ebdf782f0436f2dfbda58e09a2fbd44277bc27b\nTesting 56423dfb00c3f6864391b3b360ed467db289c1fa == 4ebdf782f0436f2dfbda58e09a2fbd44277bc27b", "stack": null, "subtest": null, "test": "/css-flexbox-1_dev/html/flexbox_columns.htm", "line": 8219, "action": "test_result", "expected": "PASS"}
```

**Comment by heycam** [comment]
OK, r=me on 953d9f1 with that comment addressed.

**Comment by emilio** [comment]
> Was this a bug (i.e. we still needed to mark dirty descendants because we do actually want to restyle the root of the display:none subtree)?

It's not a bug, it just should never be the case because of `should_process_descendants`.

**Comment by emilio** [comment]
@bors-servo r=heycam,jdm,nox p=5

 * I removed the `can_be_fragmented` patch for now.

**Comment by emilio** [comment]
@bors-servo retry

 * Timeout

**Pull request merged**
