### PR TITLE
Add onresize handler to GlobalEventHandlers

### LINKED ISSUE #7996: Add onresize handler to GlobalEventHandlers
We dispatch the resize event when when the window is resized, but only pages that use `addEventListener` can receive it right now. We should hook up the `document.onresize` mechanism too: https://html.spec.whatwg.org/multipage/webappapis.html#idl-definitions:handler-onresize . This will probably change the output of `./mach test-wpt tests/wpt/web-platform-tests/html/dom/interfaces.html` pass!

Code: components/script/dom/webidls/EventHandler.webidl, components/script/dom/document.rs, components/script/dom/window.rs, components/script/dom/htmlelement.rs

### PR DESCRIPTION
**Pull request by g-k**
Rebased: https://github.com/servo/servo/pull/8006

Fixes #7996

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9456)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo r+

Thanks for rebasing this!

**Comment by KiChjang** [comment]
```
Ran 4559 tests finished in 229.0 seconds.
  • 4558 ran as expected. 1369 tests skipped.
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /html/webappapis/scripting/events/event-handler-attributes-body-window.html:
  └ PASS [expected FAIL] resize
```

Test expectations need to be updated.

**Comment by g-k** [comment]
Forgot about that one. Updated.

**Pull request merged**
