### PR TITLE
Added verbosity to build_commands.py

### PR DESCRIPTION
**Pull request by NateBrune**
As per [this issue](https://github.com/servo/servo/issues/6363) I have added verbosity to build_commands.py

First time contributing to mozilla community, please be gentle :3

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6579)

### CODE REVIEW

**Comment by jdm** [comment]
Thanks, @NateBrune! There's enough repetition here that I wonder if we could extract the common code into a separate `subprocess_call` function that did the right thing.

**Comment by jdm** [comment]
Then again, it's possible that we really just want to print out the exactly command being invoked each time, rather than the full output of each execution.

**Comment by NateBrune** [comment]
Hi josh! I actually was inspired by watching [this](https://www.youtube.com/watch?v=87SfA1sw7vY) video about an hour ago :)

Unfortunately my desktop computer's hard drive failed yesterday and I can only work on my sisters computer and she is kicking me out right now. I will get back to it tomorrow if you would like. 

I feel like making a separate function might be of use, but that it wouldn't be used outside of this particular file very much and it would just complicate matters further. However if you feel that it is the way to go (You obviously knowing more about the context that the code would be running then I), I would happily write the function and implement it. 

Side note: I don't know how to pass this test, I cant find the tab.
    python/servo/build_commands.py:404: tab on line

**Comment by jdm** [comment]
I'm sorry for letting this sit around without comment! I think my initial comment was correct, and this is actually more work than we need to do. We don't need the full output of each command; we just want to make sure that we print the full command line that is about to be executed for each process that is invoked. Does that make sense?

**Comment by NateBrune** [comment]
Yeah that makes perfect sense. I was attempting to satisfy the request of [this guy](https://github.com/servo/servo/issues/6363). I will update this later to just print out what command is being used instead. Thanks again man.

**Comment by jdm** [comment]
Fixed by #7232.

**Pull request closed without merging**
