### PR TITLE
opts.rs: don't accept multiple URLs. Fixes #5520.

### LINKED ISSUE #5520: Remove the ability to provide multiple URLs to Servo
It's just confusing and it usually doesn't work (it triggers assertions in the constellation). Why would you want to load a succession of pages without waiting for them to complete loading? It's pretty silly.

Code: http://mxr.mozilla.org/servo/source/components/util/opts.rs, http://mxr.mozilla.org/servo/search?string=opts.urls

### PR DESCRIPTION
**Pull request by ghost**
Switched from opts.urls from being of type Vec to type String and changing the name to `url` as well. Changed the other files that are using opts.urls accordingly.

### CODE REVIEW

**Comment by mbrubeck** [comment]
Looks great, thanks!  I noted one minor issue at the Critic link above.  After that's addressed, this can land with r=mbrubeck.

**Comment by jagtalon** [comment]
@mbrubeck done! Hope it's okay.

**Comment by mbrubeck** [comment]
Thanks! Please squash these commits together and then we will land them.

**Comment by jagtalon** [comment]
@mbrubeck squashed!

**Comment by Manishearth** [comment]
```
   Compiling embedding v0.0.1 (file:///home/servo/buildbot/slave/linux2/build/ports/cef)
browser.rs:19:5: 19:25 warning: unused import, #[warn(unused_imports)] on by default
browser.rs:19 use std::borrow::ToOwned;
                  ^~~~~~~~~~~~~~~~~~~~
browser.rs:207:9: 207:16 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
browser.rs:207     let mut url = "http://s27.postimg.org/vqbtrolyr/servo.jpg".to_string();
                       ^~~~~~~
browser.rs:207:19: 207:75 error: str.to_owned() is more efficient than str.to_string(), please use it instead, #[deny(str_to_string)] on by default
browser.rs:207     let mut url = "http://s27.postimg.org/vqbtrolyr/servo.jpg".to_string();
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core.rs:73:21: 73:41 error: str.to_owned() is more efficient than str.to_string(), please use it instead, #[deny(str_to_string)] on by default
core.rs:73     temp_opts.url = HOME_URL.to_string();
                               ^~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `embedding`.
```

**Comment by Ms2ger** [comment]
Use `./mach build-cef` to reproduce that build

**Comment by jagtalon** [comment]
Thanks will make the fix.

**Comment by jagtalon** [comment]
@mbrubeck fixed issue and rebased. Should be good!

**Pull request merged**
