### PR TITLE
Allow dumping the fragment tree in layout_2020

### PR DESCRIPTION
**Pull request by mrobinson**
This is done when the dump-flow-tree debug option is passed.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because this just adds debug output.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good, thanks!

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #24726 #25505

**Comment by jdm** [comment]
@bors-servo retry
* network

**Comment by jdm** [comment]
@bors-servo retry
* network issue

**Comment by jdm** [comment]
@bors-servo retry
* #24622

**Comment by jdm** [comment]
@bors-servo retry
* #25511

**Pull request merged**
