### PR TITLE
Cache the `id` attribute on Element

### LINKED ISSUE #6359: Cache the ID in a field on Element to optimize selectors::Element::get_id
Right now, we loop over all the attributes, which is probably too slow.

Code is in `components/script/dom/element.rs`.

### PR DESCRIPTION
**Pull request by nox**
Thanks to @asabil for the original work, I only rebased it.

Fixes #6359 and #7040.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7611)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo try

There was a failure in #7068, but the logs were lost when our builders were renamed. I hope Homu handle the try command well now.

**Comment by nox** [comment]
There is now a new failing test:

```
FAIL In-document Element.querySelectorAll: :enabled pseudo-class selector, matching all disabled form controls: #pseudo-ui :disabled
```

This will require more studying.

**Comment by nox** [comment]
@bors-servo try

There were two unrelated bugs hiding behind the failing tests of this patch.

**Comment by nox** [comment]
Finally ready to be reviewed!

**Comment by Ms2ger** [comment]
Can you explain why the ID changes caused new failures?

**Comment by nox** [comment]
Of course!

This patch put the ID in an Element field, but the current `Node::clone()` method bypasses the call to `Element::attribute_mutated()` and thus the clone's ID isn't properly set. My first commit fixes that, and that also fixes the setting of cloned control forms' disabled state, making calls `clone.querySelectorAll(":disabled")` work correctly.

But the current implementation of `Element.querySelectorAll()` erroneously always starts from the last inclusive ancestor of its context object. Given `element` with id "foo", cloning `element` and putting it back into the tree, running `element.querySelectorAll("#foo")` returns 2 nodes: `element` and its clone. The second commit fixes that.

**Comment by Ms2ger** [comment]
Makes sense to me on a high level. If nobody beats me to it, I'll try to review it in detail this week.

**Comment by nox** [comment]
@bors-servo retry

Heroku is suffering right now.

**Pull request merged**
