### PR TITLE
Porting Gecko's JSToNativeConversionInfo changes to Servo's codegen

### LINKED ISSUE #4800: Port Gecko's JSToNativeConversionInfo changes to Servo's codegen
This will make porting other changes from Gecko easier, rather than returning tuple types from `getJSToNativeConversionTemplate` (to be renamed `getJSToNativeConversionInfo`).

https://mxr.mozilla.org/mozilla-central/source/dom/bindings/Codegen.py#4764
https://mxr.mozilla.org/servo/source/components/script/dom/bindings/codegen/CodegenRust.py#648

### PR DESCRIPTION
**Pull request by psdh**
Fixes #4800

### CODE REVIEW

**Comment by psdh** [comment]
I cannot get it to build, and get this error: http://pastebin.mozilla.org/8710341

**Comment by Ms2ger** [comment]
I commented on critic.

**Comment by psdh** [comment]
@Ms2ger  I am working on changing the comments ( the first issue that you pointed out)

**Comment by psdh** [comment]
@Ms2ger made some changes

**Comment by psdh** [comment]
@Ms2ger squashing done :)

**Pull request closed without merging**
