### PR TITLE
Add Bluetooth idlharness test

### PR DESCRIPTION
**Pull request by dati91**
Add idlharness wpt test file for WebBluetooth.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15080)

### CODE REVIEW

**Comment by dati91** [comment]
r? @jdm
This was a long time debt from https://github.com/servo/servo/pull/13612#issuecomment-257896036.

Please not that this PR is not complete yet!

I broke it 2 separate patch because the 2. will crash servo... [crashlog](https://gist.github.com/dati91/9b06077b51e7203bd9ceb7cbf5ff7add)
I tried to investigate it, but the only thing i found is `ConstellationControlMsg::ExitScriptThread` message was sent right before we started the promise handle method. But I couldn't figure out what caused it (i mean I know its from a drop when the channel is destroyed, but what caused it).
I would appreciate any help with that!

**Comment by jdm** [comment]
@dati91 Do you still see that crash if you rebase against master? I'm used to seeing stacks like that before https://github.com/servo/rust-mozjs/pull/326 and https://github.com/servo/servo/pull/15041 merged.

**Comment by dati91** [comment]
I tested on a70af60eec11fa0a19cfd889c56b09dc834b35af revision.

**Comment by jdm** [comment]
The changes here look fine. Now that the cause for the crash has been discovered in #15085, I'd like to hold off on merging this until the crash is fixed.

**Comment by dati91** [comment]
I also added the missing objects (intentionally missing to minimize the crash test case).
If the crash cause is resolved I still have to do a rebase as well to fix the expected error list if necessary.

**Comment by dati91** [comment]
@jdm Updated the expected list and squashed everything.

**Comment by dati91** [comment]
Hmm, this can't be related because I only added a test... :/
```
{"status": "FAIL", "stack": null, "subtest": null, "action": "test_result", "test": "/_mozilla/css/iframe/hide_and_show.html", "line": 7915, "message": "/_mozilla/css/iframe/hide_and_show.html 2008c2e9f2c032e2a0e85f2cb521cb025574cf82\n/_mozilla/css/iframe/hide_and_show_ref.html 5aca5847510aafc7accd66fc41a5309e5656f02c\nTesting 2008c2e9f2c032e2a0e85f2cb521cb025574cf82 == 5aca5847510aafc7accd66fc41a5309e5656f02c", "expected": "PASS"}
```

**Comment by jdm** [comment]
@bors-servo: retry
* #15265

**Pull request merged**
