### PR TITLE
Rust upgrade to rustc 1.6.0-nightly (5b4986fa5 2015-11-08)

### PR DESCRIPTION
**Pull request by Manishearth**
<s>DO NOT r+ or try+ this</s>

<s>It causes an OOM (https://github.com/rust-lang/rust/issues/29740) and can crash the OS. Probably will set our CI on fire. </s>

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8446)

### CODE REVIEW

**Comment by Manishearth** [comment]
Needs Rust master snapshot, cc @larsbergstrom 

I believe this currently SIGILLs on libscript (only got to see the illegal instruction message once). Attempts to reproduce didn't work, since it kept crashing everything.

**Comment by Manishearth** [comment]
Unit test failure was due to https://github.com/rust-lang/rust/commit/46068c9dafe8cfa763ef855ec21f577a1e058de1, removed unit test since it's no longer relevant

**Comment by larsbergstrom** [comment]
@bors-servo retry

(failure was an unpatched build machine whose urllib was too old and mach saw it and exited)

**Comment by larsbergstrom** [comment]
@bors-servo retry try

Looks like a reboot was required for urllib3 to get upgraded to a new version of openssl, as it was managed by the OS install instead of `pip`...

**Comment by larsbergstrom** [comment]
@brson @edunham Have you ever seen this error when downloading from the Rust snapshot machine via python?

This is a fully-patched 14.04 Trusty Ubuntu box. I don't have this problem on my 15.10 Wily box at home. The only thing I can see is that 14.04 still has python-urllib3 at 1.7.1-1ubuntu4, whereas 15.10 is at 1.11-1.

Error:
```
URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

  File "/home/servo/servo/python/servo/build_commands.py", line 190, in build
    self.ensure_bootstrapped()
  File "./python/servo/command_base.py", line 340, in ensure_bootstrapped
    Registrar.dispatch("bootstrap-rust", context=self.context)
  File "/home/servo/servo/python/mach/mach/registrar.py", line 115, in dispatch
    return self._run_command_handler(handler, context=context, **kwargs)
  File "/home/servo/servo/python/mach/mach/registrar.py", line 90, in _run_command_handler
    result = fn(**kwargs)
  File "/home/servo/servo/python/servo/bootstrap_commands.py", line 141, in bootstrap_rustc
    download_file("Rust compiler", snapshot_url, tgz_file)
  File "/home/servo/servo/python/servo/bootstrap_commands.py", line 77, in download_file
    download(desc, src, fd)
  File "/home/servo/servo/python/servo/bootstrap_commands.py", line 39, in download
    resp = urllib2.urlopen(src)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
servo@localhost:~/servo$ 
```

Here's the `pip list`:
```
servo@localhost:~/servo$ pip list
argparse (1.2.1)
buildbot-slave (0.8.12)
chardet (2.0.1)
colorama (0.2.5)
configobj (4.7.2)
croniter (0.3.4)
ghp-import (0.4.1)
html5lib (0.999)
iotop (0.6)
Jinja2 (2.7.2)
M2Crypto (0.21.1)
MarkupSafe (0.18)
msgpack-python (0.3.0)
netifaces (0.8)
PAM (0.4.2)
Pillow (2.3.0)
pip (1.5.4)
pycrypto (2.6.1)
PyOpenGL (3.0.2)
pyOpenSSL (0.15.1)
pyserial (2.6)
python-apt (0.9.3.5ubuntu1)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.10)
pyzmq (14.0.1)
requests (2.2.1)
salt (2015.5.3)
setuptools (3.3)
six (1.10.0)
ssh-import-id (3.21)
Twisted (15.4.0)
Twisted-Core (13.2.0)
urllib3 (1.7.1)
virtualenv (13.1.2)
wheel (0.24.0)
wsgiref (0.1.2)
xpra (0.12.3)
zope.interface (4.0.5)
```

**Comment by larsbergstrom** [comment]
Example of the version differences between the machines (the first one is the builder that's failing to download):

```
servo@localhost:~/servo$ dpkg -l | grep -i url
ii  curl                             7.35.0-1ubuntu2.5                          amd64        command line tool for transferring data with URL syntax
ii  libcurl3:amd64                   7.35.0-1ubuntu2.5                          amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl3-gnutls:amd64            7.35.0-1ubuntu2.5                          amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  python-urllib3                   1.7.1-1ubuntu4                             all          HTTP library with thread-safe connection pooling for Python
ii  python-urllib3-whl               1.7.1-1ubuntu4                             all          HTTP library with thread-safe connection pooling
ii  python3-pycurl                   7.19.3-0ubuntu3                            amd64        Python 3 bindings to libcurl
servo@localhost:~/servo$ dpkg -l | grep -i ssl
ii  libcurl3:amd64                   7.35.0-1ubuntu2.5                          amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libgnutls-openssl27:amd64        2.12.23-12ubuntu2.2                        amd64        GNU TLS library - OpenSSL wrapper
ii  libssl-dev:amd64                 1.0.1f-1ubuntu2.15                         amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                       1.0.1f-1ubuntu2.15                         all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                1.0.1f-1ubuntu2.15                         amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                          1.0.1f-1ubuntu2.15                         amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python-m2crypto                  0.21.1-3ubuntu5                            amd64        a crypto and SSL toolkit for Python
ii  python-openssl                   0.13-2ubuntu6                              amd64        Python 2 wrapper around the OpenSSL library


[larsberg@thor servo]$ dpkg -l | grep -i url
ii  apturl                                        0.5.2ubuntu9                               amd64        install packages using the apt protocol - GTK+ frontend
ii  apturl-common                                 0.5.2ubuntu9                               amd64        install packages using the apt protocol - common data
ii  curl                                          7.43.0-1ubuntu2                            amd64        command line tool for transferring data with URL syntax
ii  libcurl3:amd64                                7.43.0-1ubuntu2                            amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl3-gnutls:amd64                         7.43.0-1ubuntu2                            amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  liblwp-mediatypes-perl                        6.02-1                                     all          module to guess media type for a file or a URL
ii  liburl-dispatcher1:amd64                      0.1+15.10.20150717-0ubuntu2~gcc5.1         amd64        library for sending requests to the url dispatcher
ii  python-ndg-httpsclient                        0.4.0-1                                    all          enhanced HTTPS support for httplib and urllib2 using PyOpenSSL
ii  python-urllib3                                1.11-1                                     all          HTTP library with thread-safe connection pooling for Python
ii  python-urllib3-whl                            1.11-1                                     all          HTTP library with thread-safe connection pooling
ii  python3-pycurl                                7.19.5.1-1ubuntu2                          amd64        Python bindings to libcurl (Python 3)
ii  python3-urllib3                               1.11-1                                     all          HTTP library with thread-safe connection pooling for Python3
ii  unity-scope-colourlovers                      0.1+13.10.20130723-0ubuntu1                all          COLOURlovers scope for Unity
[larsberg@thor servo]$ dpkg -l | grep -i ssl
ii  libcurl3:amd64                                7.43.0-1ubuntu2                            amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libflac8:amd64                                1.3.1-4                                    amd64        Free Lossless Audio Codec - runtime C library
ii  libgnutls-openssl27:amd64                     3.3.15-5ubuntu2                            amd64        GNU TLS library - OpenSSL wrapper
ii  libio-socket-ssl-perl                         2.019-1                                    all          Perl module implementing object oriented interface to SSL sockets
ii  libnet-smtp-ssl-perl                          1.01-3                                     all          Perl module providing SSL support to Net::SMTP
ii  libnet-ssleay-perl                            1.70-1                                     amd64        Perl module for Secure Sockets Layer (SSL)
ii  libssh-4:amd64                                0.6.3-3ubuntu3                             amd64        tiny C SSH library (OpenSSL flavor)
ii  libssl-dev:amd64                              1.0.2d-0ubuntu1                            amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                                    1.0.2d-0ubuntu1                            all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                             1.0.2d-0ubuntu1                            amd64        Secure Sockets Layer toolkit - shared libraries
ii  libwavpack1:amd64                             4.75.0-1                                   amd64        audio codec (lossy and lossless) - library
ii  openssl                                       1.0.2d-0ubuntu1                            amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python-ndg-httpsclient                        0.4.0-1                                    all          enhanced HTTPS support for httplib and urllib2 using PyOpenSSL
ii  python-openssl                                0.15.1-2build1                             all          Python 2 wrapper around the OpenSSL library
ii  python-service-identity                       14.0.0-1                                   all          Service identity verification for pyOpenSSL (Python 2 module)
ii  ssl-cert                                      1.0.37                                     all          simple debconf wrapper for OpenSSL
[larsberg@thor servo]$ 
```

**Comment by Manishearth** [comment]
https://github.com/servo/servo/issues/5917

**Comment by SimonSapin** [comment]
@larsbergstrom What’s the Python version on each builder? TLS Server Name Indication is only supported since 2.7.9.

**Comment by larsbergstrom** [comment]
@SimonSapin 2.7.6 is as high as it seems to go in the Ubuntu 14.04 LTS builds. I suspect we'll have to just be careful not to rely on post-2.7.6 features for a while <sigh>.

**Comment by SimonSapin** [comment]
If this is indeed the same issue, we’ve worked around it in the past by using https://static-rust-lang-org.s3.amazonaws.com instead of https://static.rust-lang.org: #3971

**Comment by larsbergstrom** [comment]
@SimonSapin Yup! That's what my final patch did - we also discovered the same solution, after @Manishearth spent quite a few hours digging into CAs and python versions with me :-)

**Comment by larsbergstrom** [comment]
Uh-oh (from Travis):
```
Illegal instruction (core dumped)

Could not compile `script`.
```

**Comment by Manishearth** [comment]
IIRC the OOM sometimes shows up as a sigill.

**Comment by Manishearth** [comment]
```
/home/servo/.cargo/git/checkouts/rust-egl-b9f4b2970b9d8077/master/src/egl.rs:107:41: 107:53 error: mismatched types:
 expected `*const u8`,
    found `*const i8`
(expected u8,
    found i8) [E0308]
/home/servo/.cargo/git/checkouts/rust-egl-b9f4b2970b9d8077/master/src/egl.rs:107         let c_str = ffi::CStr::from_ptr(query_string);
                                                                                                                         ^~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/rust-egl-b9f4b2970b9d8077/master/src/egl.rs:107:41: 107:53 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
   Compiling memchr v0.1.6
   Compiling heapsize v0.1.2
   Compiling hbs-pow-sys v0.1.0 (https://github.com/libheartbeats/heartbeats-simple-sys.git#5ce01d0e)
   Compiling freetype-sys v2.4.11 (https://github.com/servo/libfreetype2#237f95ba)
   Compiling expat-sys v2.1.0 (https://github.com/servo/libexpat#b4fdb7a2)
   Compiling harfbuzz-sys v0.1.0
   Compiling fontconfig-sys v2.11.1 (https://github.com/servo/libfontconfig#3f93fab7)
   Compiling plugins v0.0.1 (file:///home/servo/buildbot/slave/gonk/build/ports/gonk)
   Compiling kernel32-sys v0.1.4
/home/servo/.cargo/git/checkouts/rust-stb-image-61a49b194d5ec055/master/src/image.rs:75:33: 75:38 error: mismatched types:
 expected `*const i8`,
    found `*const u8`
(expected i8,
    found u8) [E0308]
/home/servo/.cargo/git/checkouts/rust-stb-image-61a49b194d5ec055/master/src/image.rs:75 	if !convert_hdr && stbi_is_hdr(bytes)!=0   {
                                                                                        	                               ^~~~~
/home/servo/.cargo/git/checkouts/rust-stb-image-61a49b194d5ec055/master/src/image.rs:75:33: 75:38 help: run `rustc --explain E0308` to see a detailed explanation
/home/servo/.cargo/git/checkouts/rust-stb-image-61a49b194d5ec055/master/src/image.rs:76:30: 76:35 error: mismatched types:
 expected `*const i8`,
    found `*const u8`
(expected i8,
    found u8) [E0308]
/home/servo/.cargo/git/checkouts/rust-stb-image-61a49b194d5ec055/master/src/image.rs:76 	    let buffer = stbi_loadf(bytes,
                                                                                        	                            ^~~~~
/home/servo/.cargo/git/checkouts/rust-stb-image-61a49b194d5ec055/master/src/image.rs:76:30: 76:35 help: run `rustc --explain E0308` to see a detailed explanation
/home/servo/.cargo/git/checkouts/rust-stb-image-61a49b194d5ec055/master/src/image.rs:87:29: 87:34 error: mismatched types:
 expected `*const i8`,
    found `*const u8`
(expected i8,
    found u8) [E0308]
/home/servo/.cargo/git/checkouts/rust-stb-image-61a49b194d5ec055/master/src/image.rs:87 	    let buffer = stbi_load(bytes,
                                                                                        	                           ^~~~~
/home/servo/.cargo/git/checkouts/rust-stb-image-61a49b194d5ec055/master/src/image.rs:87:29: 87:34 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 3 previous errors
   Compiling advapi32-sys v0.1.2
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling quasi_codegen v0.3.7
   Compiling unreachable v0.0.2
   Compiling phf v0.7.5
   Compiling html5ever_macros v0.2.6
   Compiling gif v0.5.1
   Compiling mime v0.1.0
   Compiling hpack v0.2.0
Build failed, waiting for other jobs to finish...
Could not compile `egl`.
```

**Comment by Manishearth** [comment]
looks like the reftest harness needs some fixes too

**Comment by SimonSapin** [comment]
@bors-servo try

Rebased and rustuped the reftest harness.

**Comment by larsbergstrom** [comment]
@SimonSapin Thanks for rebasing! Unforutnately, there are a bunch of submodules that need updating for Android/Gonk and i didn't have a chance to look at them this weekend.

**Comment by SimonSapin** [comment]
Reviewed 7 of 11 files at r1, 1 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: 12 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8446)

**Comment by SimonSapin** [comment]
@larsbergstrom that’s ok, one step at a time.

**Comment by SimonSapin** [comment]
We should fix #8608 eventually, but maybe not all of it is needed to unblock this. I suggest running `./mach build --android` in this PR, upgrading libc in crates that show build errors, and repeating.

**Comment by SimonSapin** [comment]
I managed to get an Android build with changes (PRs linked above) to libc, net2, and ipc-channel.

**Comment by Manishearth** [comment]
New aster/quasi/syntex updates have been pushed

**Comment by SimonSapin** [comment]
https://github.com/servo/rust-harfbuzz/issues/54#issuecomment-159316279

**Comment by SimonSapin** [comment]
Never mind, although it looks superficially similar this is not the same error as linked above. This one is about `autoheader`:

> /Users/servo/.cargo/registry/src/github.com-0a35038f75765ae4/harfbuzz-sys-0.1.2/harfbuzz/missing: line 81: autoheader: command not found
WARNING: 'autoheader' is missing on your system.
         You should only need it if you modified 'acconfig.h' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'autoheader' program is part of the GNU Autoconf package:
         <http://www.gnu.org/software/autoconf/>
         It also requires GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[1]: *** [/Users/servo/.cargo/registry/src/github.com-0a35038f75765ae4/harfbuzz-sys-0.1.2/harfbuzz/config.h.in] Error 127

**Comment by larsbergstrom** [comment]
@bors-servo retry

Added automake/autoconf to all the mac builders.

**Comment by SimonSapin** [comment]
@bors-servo try

(I’ve rebased since the last try, I think.)

**Comment by larsbergstrom** [comment]
@bors-servo try

(I've done a `brew link --overwrite autoconf` to get around the problem that autoconf fails to link if autoconf213 was installed first)

**Comment by Manishearth** [comment]
```
/home/servo/buildbot/slave/linux-dev/build/ports/glutin/window.rs:732:27: 732:63 error: mismatched types:
 expected `*const libc::c_void`,
    found `*const ()`
(expected enum `libc::c_void`,
    found ()) [E0308]
/home/servo/buildbot/slave/linux-dev/build/ports/glutin/window.rs:732         gl::load_with(|s| headless_context.get_proc_address(s));
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-dev/build/ports/glutin/window.rs:732:27: 732:63 help: run `rustc --explain E0308` to see a detailed explanation
```

**Comment by SimonSapin** [comment]
I’m on Linux and can’t reproduce this :/

**Comment by larsbergstrom** [comment]
@bors-servo try

This should fix debug and hopefully android should still work. build-cef will fail, though - lots more changes to make there.

**Comment by frewsxcv** [comment]
Gonk (and probably CEF) lockfile needs to be updated

**Comment by Manishearth** [comment]
```
types.rs:10:5: 10:40 error: unresolved import `libc::types::os::arch::c95::wchar_t`. Could not find `types` in `libc` [E0432]
types.rs:10 use libc::types::os::arch::c95::wchar_t;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
types.rs:10:5: 10:40 help: run `rustc --explain E0432` to see a detailed explanation
string.rs:7:5: 7:40 error: unresolved import `libc::types::os::arch::c95::wchar_t`. Could not find `types` in `libc` [E0432]
string.rs:7 use libc::types::os::arch::c95::wchar_t;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
string.rs:7:5: 7:40 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to 2 previous errors
Could not compile `embedding`.

To learn more, run the command again with --verbose.
```

**Comment by SimonSapin** [comment]
I’m on it.

**Comment by SimonSapin** [comment]
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /XMLHttpRequest/anonymous-mode-unsupported.htm:
  │ FAIL [expected PASS] XMLHttpRequest: anonymous mode unsupported
  │   → assert_equals: The deprecated anonymous:true should be ignored, cookie sent anyway expected "cookie: test=anonymous-mode-unsupported\n" but got ""
  │ 
  │ client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/anonymous-mode-unsupported.htm:22:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://192.0x00A80001> against <about:blank>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://%30%78%63%30%2e%30%32%35%30.01> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://%30%78%63%30%2e%30%32%35%30.01%2e> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://192.168.0.257> against <http://other.com/>
```

I don’t know about the first one, but the rust might be real fixes we picked up from rust-url

**Comment by SimonSapin** [comment]
So, this test uses `new XMLHttpRequest({anonymous:true})` and sends a same-origin request from a document with a cookie. Once upon a time, `anonymous:true` would have caused the cookie not to be sent. But that feature has been removed, and the test ensures that the feature is *not* implemented. That is, the cookie must be sent.

According to Wireshark, we send this XHR request without a cookie. But I don’t think because of `anonymous`, since `git grep anonymous components/script components/net` doesn’t find anything. Looks like another bug somewhere causing us not to send cookies.

**Comment by jdm** [comment]
If the cookie version we're using changed, it may be caused by https://github.com/alexcrichton/cookie-rs/commit/d53de1e58b2e20a8fcf6b2c590c4e15d650a1325 .

**Comment by SimonSapin** [comment]
It has indeed, we went from `0.1.21` to `0.2.1`. This looks promising, I’ll look into it.

**Comment by SimonSapin** [comment]
Only tidy failures left.

**Comment by Ms2ger** [comment]
Reviewed 43 of 48 files at r8, 1 of 1 files at r10.
Review status: 54 of 59 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8446)*

**Comment by jdm** [comment]
Reviewed 1 of 48 files at r8.
Review status: 55 of 59 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8446)*

**Comment by Manishearth** [comment]
Reviewed 1 of 48 files at r8.
Review status: 56 of 59 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8446)*

**Comment by jdm** [comment]
Reviewed 3 of 8 files at r12.
Review status: 53 of 59 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/servo/Cargo.lock, line 153 \[r13\]](https://reviewable.io:443/reviews/servo/servo/8446#-K447pYdjycinewTDvXo:-K447pYdjycinewTDvXp:-264511119) ([raw file](https://github.com/servo/servo/blob/e34a8f7d2769e07c9aee8dffa86918bd10b75cc3/components/servo/Cargo.lock#L153)):*
There are multiple versions of byteorder; I'm surprised tidy doesn't catch this.

---

*[components/servo/Cargo.lock, line 982 \[r13\]](https://reviewable.io:443/reviews/servo/servo/8446#-K449Fu2WfvrVTEmkaWe:-K449Fu2WfvrVTEmkaWf:-408587200) ([raw file](https://github.com/servo/servo/blob/e34a8f7d2769e07c9aee8dffa86918bd10b75cc3/components/servo/Cargo.lock#L982)):*
This duplicates an earlier package.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8446)*

**Comment by SimonSapin** [comment]
Review status: 50 of 59 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/servo/Cargo.lock, line 153 \[r13\]](https://reviewable.io:443/reviews/servo/servo/8446#-K447pYdjycinewTDvXo:-K44AdvGqiTQ2DTO-KD5:-1177677382) ([raw file](https://github.com/servo/servo/blob/e34a8f7d2769e07c9aee8dffa86918bd10b75cc3/components/servo/Cargo.lock#L153)):*
https://github.com/TyOverby/bincode/pull/49

---

*[components/servo/Cargo.lock, line 982 \[r13\]](https://reviewable.io:443/reviews/servo/servo/8446#-K449Fu2WfvrVTEmkaWe:-K44BAq47debyw-K15U8:1114355734) ([raw file](https://github.com/servo/servo/blob/e34a8f7d2769e07c9aee8dffa86918bd10b75cc3/components/servo/Cargo.lock#L982)):*
`clipboard-win` specifies `*` dependencies, so `./mach update-cargo -p kernel32-sys:0.1.4` "fixed" this one. I don’t know if it actually builds on Windows.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8446)*

**Comment by jdm** [comment]
Reviewed 3 of 3 files at r14.
Review status: 53 of 59 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8446)*

**Comment by Manishearth** [comment]
```
./ports/gonk/Cargo.lock:492: conflicting versions for package "kernel32-sys"
	expected maximum version "0.2.1"
	but, "errno" demands "0.1.4"
	try upgrading with ./mach cargo-update -p kernel32-sys:0.1.4
```

**Comment by larsbergstrom** [comment]
@SimonSapin @Manishearth Nice work! :-)

**Comment by SimonSapin** [comment]
@bors r=SimonSapin+Ms2ger+jdm+Manishearth

---

Reviewed 5 of 8 files at r12, 1 of 1 files at r13, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8446#-:-K45eabU2xK1eCtjmOaY:1019622819)*

**Comment by SimonSapin** [comment]
wat

**Pull request merged**
