### PR TITLE
Prevent panic on layout send in finish-load

### LINKED ISSUE #22955: Intermittent panic reflowing document from Document::finish_load (/html/browsers/windows/nested-browsing-contexts/name-attribute.window.html, /html/browsers/the-window-object/closed-attribute.window.html)
```
 ▶ CRASH [expected OK] /html/browsers/windows/auxiliary-browsing-contexts/opener.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.3.0-devel
  │ Layout thread disconnected.: "SendError(..)" (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at src/libcore/result.rs:997)
  │ stack backtrace:
  │    0:     0x7fb4d8418a3d - backtrace::backtrace::trace::hdbde910ecd054dd5
  │    1:     0x7fb4d8418622 - <backtrace::capture::Backtrace as core::default::Default>::default::h4d26883ca0c5c00e
  │    2:     0x7fb4d5de3a2f - servo::main::{{closure}}::h31fd4f8542e80111
  │    3:     0x7fb4d9101ef8 - rust_panic_with_hook
  │                         at src/libstd/panicking.rs:482
  │    4:     0x7fb4d9101991 - continue_panic_fmt
  │                         at src/libstd/panicking.rs:385
  │    5:     0x7fb4d9101875 - rust_begin_unwind
  │    6:     0x7fb4d912114c - panic_fmt
  │                         at src/libcore/panicking.rs:85
  │    7:     0x7fb4d6b0410d - core::result::unwrap_failed::h6f93908eb6ae2779
  │    8:     0x7fb4d647a70e - script::dom::window::Window::force_reflow::h10818cf57371fb4b
  │    9:     0x7fb4d647ae7a - script::dom::window::Window::reflow::h2f6852cb317c3c40
  │   10:     0x7fb4d674d7ab - script::dom::document::Document::finish_load::h0e271f1bc3989bd4
  │   11:     0x7fb4d6780339 - script::dom::servoparser::ServoParser::do_parse_sync::h0133462a850a38fe
  │   12:     0x7fb4d694b2f2 - profile_traits::time::profile::hdb03b8f9dc25d87b
  │   13:     0x7fb4d677f9d0 - _ZN6script3dom11servoparser11ServoParser10parse_sync17hc7b6c2649a0fc024E.llvm.15475779888509234564
  │   14:     0x7fb4d67859ff - <script::dom::servoparser::ParserContext as net_traits::FetchResponseListener>::process_response_eof::he3a218dd73256dd1
  │   15:     0x7fb4d6a468b0 - script::script_thread::ScriptThread::handle_msg_from_constellation::h9d1539e38495b8d9
  │   16:     0x7fb4d6a3d1da - script::script_thread::ScriptThread::handle_msgs::{{closure}}::h10c90dfa10c12c03
  │   17:     0x7fb4d6a38baa - _ZN6script13script_thread12ScriptThread11handle_msgs17h2b36a475ed0bc7fbE.llvm.17883111707991953694
  │   18:     0x7fb4d6a342a6 - script::script_thread::ScriptThread::start::hda56813bf3e9f276
  │   19:     0x7fb4d6adb9ee - profile_traits::mem::ProfilerChan::run_with_memory_reporting::hd979c4788c0335f2
  │   20:     0x7fb4d687b785 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4157a92b1609ffb0
  │   21:     0x7fb4d700b995 - _ZN3std9panicking3try7do_call17hd7fa3209cfdb04c4E.llvm.7884770878088097045
  │   22:     0x7fb4d910caa9 - __rust_maybe_catch_panic
  │                         at src/libpanic_unwind/lib.rs:87
  │   23:     0x7fb4d6b069d7 - <F as alloc::boxed::FnBox<A>>::call_box::h3ef1de137faa36de
  │   24:     0x7fb4d910bded - call_once<(),()>
  │                         at /rustc/097c04cf433048585dd9e3f63b30e03cc3509e4b/src/liballoc/boxed.rs:759
  │                          - start_thread
  │                         at src/libstd/sys_common/thread.rs:14
  │                          - thread_start
  │                         at src/libstd/sys/unix/thread.rs:81
  │   25:     0x7fb4d3385183 - start_thread
  │   26:     0x7fb4d1c4c03c - clone
  │   27:                0x0 - <unknown>
  │ [2019-03-01T16:22:49Z ERROR servo] Layout thread disconnected.: "SendError(..)"
  └ Pipeline failed in hard-fail mode.  Crashing!
```
I've seen this in various tests in the past week. Clearly there's a fundamental issue we should address here.

### PR DESCRIPTION
**Pull request by gterzian**
Do not run the finish load steps if the pipeline has been discarded by the time the parser finishes.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #22955 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by gterzian** [comment]
@bors-servo try=wpt

@jdm I think this one might actually fix https://github.com/servo/servo/issues/22955 (and hopefully not break other things)

**Comment by jdm** [comment]
I think a more robust fix would be calling ServoParser::abort on Document::current_parser (if it exists) when we know a pipeline is being closed.

**Comment by gterzian** [comment]
@jdm Thanks, I have changed the fix accordingly.

**Comment by jdm** [comment]
Sorry, the try build for #24821 stomped on the branch so all the test runners couldn't clone the appropriate git revision. I'm going to wait until the tests for #24821 start running to retry this.

**Comment by gterzian** [comment]
```
0 matches
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/url.window.html", 
    "line": 65380, 
    "action": "test_result", 
    "expected": "OK"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/abort-refresh-immediate.window.html", 
    "line": 65933, 
    "action": "test_result", 
    "expected": "TIMEOUT"
}
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/tasks.window.html", 
    "line": 66212, 
    "action": "test_result", 
    "expected": "TIMEOUT"
}
{
```

Looks like aborting the parser when the pipeline exits results in other crashes

**Comment by jdm** [comment]
The async parser doesn't get used unless `dom.servoparser.async_html_tokenizer.enabled` is true. I think we want to abort the parser before we start tearing down the window to avoid this.

**Comment by jdm** [comment]
In particular, because aborting the document can cause additional parser activity, I think we need to do that before we shut down the layout thread.

**Comment by gterzian** [comment]
@bors-servo try=wpt

Ok, trying before shutting down layout...

**Pull request merged**
