### PR TITLE
Only build ports/servo by default (except Android), add `./mach build --libsimpleservo`

### LINKED ISSUE #21314: Custom features no longer affect the build
When I write `./mach build -d --features whatever`, I no longer receive an error about the `whatever` feature not existing. If I add `-v` to the build, I don't see `whatever` passed to any of the crates. This regressed sometime in the past month.

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes #21314

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21809)

### CODE REVIEW

**Comment by paulrouget** [comment]
Can we make sure our CI keeps building libsimpleservo on at least one non-android platform?

**Comment by SimonSapin** [comment]
Multiple `OSError: [Errno 12] Cannot allocate memory` Python exceptions on servo-linux6. SSH’ing into that machine, I see 39 `servo` processes even though Buildbot says that machine is idle. Running `pkill servo` reduces occupied memory dramatically.

@bors-servo retry

**Comment by SimonSapin** [comment]
11 timeouts out of 62 tests is rather suspicious :/ (This is the subset of the test suite run with `--multiprocess`.) @jdm, what do you think?

**Comment by SimonSapin** [comment]
Let’s see if it happens again.

@bors-servo r- try retry

**Comment by SimonSapin** [comment]
jdm pointed out on IRC that the error messages included `Failed to start unsandboxed child process!: Os { code: 12, kind: Other, message: "Cannot allocate memory" }`, so this was likely another occurrence of remaining processes on the builder taking up RAM.

@bors-servo try- r+

(Does this command work?)

**Comment by jdm** [comment]
@bors-servo retry
* #21795

**Comment by jdm** [comment]
@bors-servo retry
* #21795

**Pull request merged**
