### PR TITLE
Completed implementation of devtools' `getLayout`. (#3598)

### LINKED ISSUE #3598: Fetch margins, padding, and borders for layout inspector
See the "getLayout" message in `components/devtools/actors/inspector.rs`. Currently we only fetch the width and height; instead we want to adjust the code in `handle_get_layout` to query the layout properties using LayoutRPC, rather than just calling `getBoundingClientRect`.

### PR DESCRIPTION
**Pull request by benschulz**
First PR; be gentle. ;)
Fixes #3598.

**Notes**
- I'm using serde_json for serialization, I will file a separate PR for converting the rest of devtools.
- As suggested I'm accessing the shared layout data from the directly from the script task.
  - Should the corresponding field be renamed ( `_shared_data` → `shared_data` )? I couldn't find any naming conventions, but I assume the underscore means "don't access".
  - Should any other documentation be updated?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7267)

### CODE REVIEW

**Comment by Manishearth** [comment]
The `_` was probably used to circumvent an unused-variable lint or something.

**Comment by pcwalton** [comment]
The layout/style bits look good to me.

**Comment by jdm** [comment]
@pcwalton Is there any danger from reading the style data directly in the script task, rather than querying layout for it?

**Comment by jdm** [comment]
Just to avoid radio silence, I've started looking at this several times but have run out time to wrap my head around all the changes. It's pretty dense, unfortunately. I'm going to try using github's split diff view to see if that makes it any easier.

**Comment by jdm** [comment]
I'll poke pcwalton to get an answer out of him, but these changes look pretty great to me!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 7 of 7 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/devtools.rs, line 141 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7267#-JyDDCphIyRzDAafbHYK)** ([raw file](https://github.com/servo/servo/blob/b701d745c26dcb879a70b2e04fff279a99689d7f/components/script/devtools.rs#L141)):</sup>
We can use `&Node` here instead.

---

<sup>**[components/script/dom/node.rs, line 63 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7267#-JyDDSLlMcLSRLjA20CE)** ([raw file](https://github.com/servo/servo/blob/b701d745c26dcb879a70b2e04fff279a99689d7f/components/script/dom/node.rs#L63)):</sup>
This shouldn't be necessary.

---

<sup>**[components/script/dom/node.rs, line 1073 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7267#-JyDE9MRkigO646Z5kgy)** ([raw file](https://github.com/servo/servo/blob/b701d745c26dcb879a70b2e04fff279a99689d7f/components/script/dom/node.rs#L1073)):</sup>
Just use `query(*style)` instead of calling deref above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7267)

**Comment by jdm** [comment]
-S-awaiting-review 

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7267)

**Comment by pcwalton** [comment]
@jdm If there are off-main-thread CSS transitions running, they could be concurrently modifying style. So I think you need to handle the synchronization somehow. Since styles are atomically copy-on-write, you can satisfy this by simply cloning the style object.

**Comment by jdm** [comment]
@benschulz Instead of using `borrow`, could we create a `style_for_script` API that clones the style value under the hood and returns it?

**Comment by benschulz** [comment]
Done.

Can I ask, how this addresses the problem? I've only just found out about `Arc::make_unique` and am unfamiliar with its exact mechanics. Isn't it based on the assumption that *if the reference count is one then there's only one (mut) reference to the `Arc`*? And if so, don't we break that assumption via `TrustedNodeAddress`es? I.e. couldn't the concurrent transition have checked that the reference count is one and then proceed to modify the `ComputedValues` in-place while the script task increments the ref count and reads those values?

**Comment by pcwalton** [comment]
@benschulz Yes, you're right that that's a potential race. Perhaps while there are `TrustedNodeAddress`es about we should take out a reference representing them? @jdm, what do you think?

**Comment by frewsxcv** [comment]
@jdm It looks like this is waiting on an answer from you?

**Comment by jdm** [comment]
Taking this so I stop forgetting about it.

**Comment by jdm** [comment]
Rebased in #9661.

**Pull request closed without merging**
