### PR TITLE
Make add_panic_object in thread.rs borrow rather than own the object.

### PR DESCRIPTION
**Pull request by asajeffrey**
r? @Manishearth

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10609)

### CODE REVIEW

**Comment by Manishearth** [comment]
Already handled in https://github.com/servo/servo/pull/10572

**Comment by asajeffrey** [comment]
Yes, but this shouldn't be blocked on #10572, which has a lot more moving parts.

**Comment by asajeffrey** [comment]
@Manishearth thanks!

**Pull request merged**
