### PR TITLE
Very basic touch events and touch scrolling

### PR DESCRIPTION
**Pull request by mbrubeck**
This implements just enough of [Touch Events](http://w3c.github.io/touch-events/) to enable scrolling on Android without regressing basic single-touch interaction like clicking on links.

Dragging a page will scroll it, unless the page calls `preventDefault` on the "touchstart" event.

Does **not** yet support pinch zooming or other multi-touch gestures or events.

Includes a `-Z convert-mouse-to-touch` command line flag for testing on non-touch platforms.  This is also enabled by default on Android because Glutin currently translates touch input to mouse events on Android.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7204)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Fixes #7036.

**Comment by mbrubeck** [comment]
If this PR is used for the upcoming demos, it also depends on servo/servoexperiments.com#2.

**Comment by metajack** [comment]
```
/home/jack/src/servo/components/compositing/compositor.rs:15:5: 15:27 warning: unused import, #[warn(unused_imports)] on by default
/home/jack/src/servo/components/compositing/compositor.rs:15 use euclid::length::Length;
                                                                 ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by metajack** [comment]
Dragging in the physics demo on a device doesn't seem to work.

**Comment by mbrubeck** [comment]
> Dragging in the physics demo on a device doesn't seem to work.

This is working for me, though it's a bit slower to react than desktop (I think partly because of how the page is "zoomed out" on mobile, so the physical speed of the particles is smaller).

**Comment by metajack** [comment]
I'll retest this again today.

Have you gotten the photo gallery slider to work on mobile?

**Comment by mbrubeck** [comment]
> Have you gotten the photo gallery slider to work on mobile?

No.  It's working in other mobile browsers, but not in Servo. Investigating...

**Comment by mbrubeck** [comment]
> No. It's working in other mobile browsers, but not in Servo. Investigating...

Fixed by adding in a missing `reflow()` call.

**Comment by glennw** [comment]
Reviewed 6 of 10 files at r2.
Review status: 6 of 18 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7204)

**Comment by glennw** [comment]
I've reviewed the compositor parts, and I've also tested this successfully on an android device.

Who would like to look at the DOM parts - @jdm @Ms2ger or @nox ?

**Comment by mbrubeck** [comment]
@jdm, can you review the DOM changes here?  I think you looked at them earlier.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 9 of 9 files at r1, 4 of 10 files at r2, 4 of 9 files at r3.
Review status: 13 of 18 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/document.rs, line 734 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4_2v39DEbo3ZRlkni)** ([raw file](https://github.com/servo/servo/blob/cfa6830936d4d30868c80967d885238812f5b241/components/script/dom/document.rs#L734)):</sup>
We can just use self.jsruntime.rt(), instead of passing this, right?

---

<sup>**[components/script/dom/document.rs, line 737 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4ZF5I4Ona3nVbQRcN)** ([raw file](https://github.com/servo/servo/blob/cfa6830936d4d30868c80967d885238812f5b241/components/script/dom/document.rs#L737)):</sup>
nit: odd indentation

---

<sup>**[components/script/dom/document.rs, line 760 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4ZM-xLMqUcDsD4jYO)** ([raw file](https://github.com/servo/servo/blob/cfa6830936d4d30868c80967d885238812f5b241/components/script/dom/document.rs#L760)):</sup>
We should use a RootedVec here.

---

<sup>**[components/script/dom/touchevent.rs, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4YCqFfH4mDIhw0H_K)** ([raw file](https://github.com/servo/servo/blob/ae963120c627e0b70b59b23de8ef38d7c21a8054/components/script/dom/touchevent.rs#L76)):</sup>
Why this block?

---

<sup>**[components/script/dom/touchevent.rs, line 77 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4YDe0JSjVKRvlnNXc)** ([raw file](https://github.com/servo/servo/blob/ae963120c627e0b70b59b23de8ef38d7c21a8054/components/script/dom/touchevent.rs#L77)):</sup>
nit: no need for an explicit type

---

<sup>**[components/script/dom/touchlist.rs, line 20 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4YUhRWrQn6zGlwmHs)** ([raw file](https://github.com/servo/servo/blob/ae963120c627e0b70b59b23de8ef38d7c21a8054/components/script/dom/touchlist.rs#L20)):</sup>
`&[&Touch]`

---

<sup>**[components/script/dom/touchlist.rs, line 27 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4YQHTzrkedGNzfEIo)** ([raw file](https://github.com/servo/servo/blob/ae963120c627e0b70b59b23de8ef38d7c21a8054/components/script/dom/touchlist.rs#L27)):</sup>
`&[&Touch]`

---

<sup>**[components/script/dom/webidls/Touch.webidl, line 9 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4YuatUVlsnRJgykED)** ([raw file](https://github.com/servo/servo/blob/ae963120c627e0b70b59b23de8ef38d7c21a8054/components/script/dom/webidls/Touch.webidl#L9)):</sup>
These have been fixed.

---

<sup>**[components/script/dom/webidls/TouchEvent.webidl, line 8 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4Z1ltxZKOudkYL-DU)** ([raw file](https://github.com/servo/servo/blob/ae963120c627e0b70b59b23de8ef38d7c21a8054/components/script/dom/webidls/TouchEvent.webidl#L8)):</sup>
Why not support the non-sequence arguments, at least?

---

<sup>**[components/script/script_task.rs, line 1872 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4ZxiiGa717PCEx-rn)** ([raw file](https://github.com/servo/servo/blob/cfa6830936d4d30868c80967d885238812f5b241/components/script/script_task.rs#L1872)):</sup>
This marker stuff isn't necessary any longer.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7204)

**Comment by mbrubeck** [comment]
Review status: 4 of 17 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/document.rs, line 734 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4_2v39DEbo3ZRlkni)** ([raw file](https://github.com/servo/servo/blob/cfa6830936d4d30868c80967d885238812f5b241/components/script/dom/document.rs#L734)):</sup>
Document doesn't have a `jsruntime` field. 


---

<sup>**[components/script/dom/touchlist.rs, line 20 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4YUhRWrQn6zGlwmHs)** ([raw file](https://github.com/servo/servo/blob/ae963120c627e0b70b59b23de8ef38d7c21a8054/components/script/dom/touchlist.rs#L20)):</sup>
Done, though this seems a bit more complex and less efficient, since I end up allocating one Vec just to copy it into a second Vec. Is this for safety, or just to make a more general API? 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7204)

**Comment by mbrubeck** [comment]
Review status: 2 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/webidls/TouchEvent.webidl, line 8 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4Z1ltxZKOudkYL-DU)** ([raw file](https://github.com/servo/servo/blob/ae963120c627e0b70b59b23de8ef38d7c21a8054/components/script/dom/webidls/TouchEvent.webidl#L8)):</sup>
I decided to just remove the constructor dictionaries for now, since they are new in Touch Events Level 2 and existing browsers aren't shipping them yet. I'll file an issue to add them when the spec stabilizes.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7204)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 
Looks good! This will need to modify tests/wpt/mozilla/tests/mozilla/interfaces.html, too. Please file a followup E-easy to add a new entry to Document::CreateEvent, as well!


---

Reviewed 9 of 16 files at r4.
Review status: 11 of 17 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/touchlist.rs, line 20 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7204#-K-4YUhRWrQn6zGlwmHs)** ([raw file](https://github.com/servo/servo/blob/ae963120c627e0b70b59b23de8ef38d7c21a8054/components/script/dom/touchlist.rs#L20)):</sup>
For safety.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7204)

**Comment by jdm** [comment]
Looks like dom/events/EventTarget-dispatchEvent.html might have new test results, too.

**Comment by mbrubeck** [comment]
Modified interfaces.html, and added a new commit implementing `createTouch` which allows some of the WPT tests to run (such as they are).  Filed issue #8160 for `document.createEvent`.


---

Review status: 6 of 21 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7204)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 9 of 10 files at r5.
Review status: 15 of 21 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7204)

**Pull request merged**
