### PR TITLE
Implement range index with the Position enum on ServoUrl

### PR DESCRIPTION
**Pull request by stshine**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because refactoring

r? @emilio

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14274)

### CODE REVIEW

**Comment by emilio** [comment]
So the idea is that this might eventually be not supported when we add a data variant that bypasses rust-url, but we can do that when needed I guess, and it's less easy to forget to change them when needed.

@bors-servo r+

**Comment by stshine** [comment]
Tried to take a look at the data uri thing, and since data uri can encode a complete html document, in case for url related spec to work properly, at least we should have the query part and the fragment part to work properly. That said, despite the actual implementation, we may have hope on that the index traits may still useful for data uri; and if not, like what you said, it may not be hard to remove them :)

**Comment by stshine** [comment]
@bors-servo retry
#11100

**Comment by jdm** [comment]
@bors-servo: retry
* #11100

**Pull request merged**
