### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See individual commits for details. https://bugzilla.mozilla.org/show_bug.cgi?id=1614394

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r=emilio,nox

(@nox reviewed the word-spacing and layout-2020 changes)

**Comment by jdm** [comment]
```
error[E0308]: mismatched types
  --> tests/unit/style/custom_properties.rs:30:63
   |
30 |     let mut builder = CustomPropertiesBuilder::new(inherited, &env);
   |                                                               ^^^^ expected struct `style::media_queries::Device`, found struct `style::custom_properties::CssEnvironment`
   |
   = note: expected reference `&style::media_queries::Device`
              found reference `&style::custom_properties::CssEnvironment`
error: aborting due to previous error
```

**Comment by emilio** [comment]
@bors-servo r=emilio,nox

 * I ended up fixing the benchmark.

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /css/css-transforms/inheritance.html:
  │ FAIL [expected PASS] Property transform-style has initial value auto
  │   → assert_equals: expected "auto" but got "flat"
  │ 
  │ assert_initial/<@http://web-platform.test:8000/css/support/inheritance-testcommon.js:17:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  │ test@http://web-platform.test:8000/resources/testharness.js:548:30
  │ assert_initial@http://web-platform.test:8000/css/support/inheritance-testcommon.js:10:3
  │ assert_not_inherited@http://web-platform.test:8000/css/support/inheritance-testcommon.js:74:3
  └ @http://web-platform.test:8000/css/css-transforms/inheritance.html:37:1
```

**Comment by emilio** [comment]
That test is delusional and doesn't match any browser :)

**Comment by emilio** [comment]
@bors-servo r=emilio,nox

 * Updated some more tests that are now passing.

**Comment by jdm** [comment]
@bors-servo retry
* network failure

**Pull request merged**
