### PR TITLE
Adding for support Blob.{close,isClose} #6723

### PR DESCRIPTION
**Pull request by farodin91**
Blob-close.html is impossible to pass

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6731)

### CODE REVIEW

**Comment by jdm** [comment]
I'm curious about why Blob-close.html is failing - I don't see any reason it should.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/blob.rs, line 168 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6731#-Jv9UsfkUEnvz0lhwT-i)** ([raw file](https://github.com/servo/servo/blob/de38fc10b6716d116b79c63f173e1bd9757ccaa4/components/script/dom/blob.rs#L168)):</sup>
This should return from this method if true.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6731)

**Comment by farodin91** [comment]
It's test in it self, because for example Input string is "TEST" and expected Ouput String is "PASS" for the slice test. 
Firefox also doesn't pass the test. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6731)

**Comment by jdm** [comment]
Huh, all major browser engines don't implement Blob.close yet.

**Comment by jdm** [comment]
You can go ahead an modify the test file to fix that problem. We'll submit the changes to the upstream project when we next sync with it.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6731)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/wpt/web-platform-tests/FileAPI/blob/Blob-close.html, line 25 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6731#-JvEdNFXzwVrO-k4LJlQ)** ([raw file](https://github.com/servo/servo/blob/d92efd36ab78a412c62f37021bc33472031197db/tests/wpt/web-platform-tests/FileAPI/blob/Blob-close.html#L25)):</sup>
Let's check that t.error is an InvalidStateError, too.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6731)

**Comment by farodin91** [comment]
For this I will add it domexception



—

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/wpt/web-platform-tests/FileAPI/blob/Blob-close.html, line 16 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6731#-JvFdYqOLet10Hmo4Wlt)** ([raw file](https://github.com/servo/servo/blob/d92efd36ab78a412c62f37021bc33472031197db/tests/wpt/web-platform-tests/FileAPI/blob/Blob-close.html#L16)):</sup>
Nit: make it
```js
async_test(function(t) {
  var reader = ...;
  ...
}, "Closed Blob");

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6731)
<!-- Sent from Reviewable.io -->

**Comment by jdm** [comment]
One last change and this should be ready to go :)
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/wpt/web-platform-tests/FileAPI/blob/Blob-close.html, line 25 \[r9\]](https://reviewable.io:443/reviews/servo/servo/6731#-JvFwGM8G5Ksu12wQaDu)** ([raw file](https://github.com/servo/servo/blob/fa8b5c097de67eb8fd9e350f87220d8f4818df2f/tests/wpt/web-platform-tests/FileAPI/blob/Blob-close.html#L25)):</sup>
Use DOMException.INVALID_STATE_ERR instead of 11 here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6731)

**Comment by jdm** [comment]
Lovely! Could you squash all of these commits into one again?

-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r11.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6731)

**Comment by farodin91** [comment]
i hope that work i forgot to use git push --force instead of pull and merge

**Comment by jdm** [comment]
Github still shows 13 commits, unfortunately. I recommend doing what we did with your last PR - make a new branch that's based on a recent revision of master, then use `git merge --squash tmpblob` and force push to this branch: `git push -f origin [newbranchname]:tmpblob`. Does that make sense?

**Comment by farodin91** [comment]
#6803

**Pull request closed without merging**
