### PR TITLE
Build and publish Linux amd64 --media-stack=dummy

### PR DESCRIPTION
**Pull request by ghost**
- this depends on servo/servo#24668
- servo/download.servo.org#54 depends on this

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] These changes do not require tests because it's build infra

### CODE REVIEW

**Comment by Darkspirit** [comment]
What is the purpose of storing and publishing half-functional Servo Linux builds and paying costs for it?

**Comment by jdm** [comment]
I don't see a compelling reason to publish nightly builds with media disabled. For the forseeable future this is only a build configuration to help local developers.

**Comment by tuncer** [comment]
To be clear, were you waiting for me to lists arguments in favor of including it in nightly builds?

**Comment by jdm** [comment]
As the person requesting this change, that would help us understand your use case better, yes.

**Comment by tuncer** [comment]
Missing media playback support is a wanted feature for part of the user base. In fact, Firefox and Blink browsers, as distributed by their upstreams, work without media playback already. Further, building servo takes considerable time, and its rustc nightly version is changed regularly, requiring full rebuilds from time to time.

This means that trying out a fresh nightly build, testing, reporting issues, and contributing will be easier, because one doesn't have to build their personal media-dummy servo. Also, having nightlies means that this build profile will be tested more often than it would be otherwise, as it's readily available.

**Comment by tuncer** [comment]
@jdm, what do you think? It wouldn't be ideal, but not linking to the artifact, and merely including it in the build matrix, would also suffice.

**Comment by jdm** [comment]
Sorry, I don't think there's a clear value for making them easily available at this point. A better longer-term solution would be to focus on enabling the media library to load dynamically at runtime and allow the application to continue running without it.

**Comment by tuncer** [comment]
That would work, too. Without arguing for a nightly build (artifact), do you think it's unnecessary to include it in CI to avoid bitrot?

**Comment by tuncer** [comment]
Should a ticket be filed regarding media-stack graceful fallback at runtime?

**Comment by jdm** [comment]
Yes, it would be useful to have an issue on file for making the media stack less statically coupled. And yes, I think adding a CI build that verifies that this configuration doesn't break is valuable.

**Comment by tuncer** [comment]
@jdm see https://github.com/servo/servo/pull/25495

**Comment by tuncer** [comment]
Also see https://github.com/servo/media/issues/329

**Pull request closed without merging**
