### PR TITLE
gfx: Implement display-list-based invalidation.

### PR DESCRIPTION
**Pull request by pcwalton**
This ensures that we don't throw away all tiles if only a few of them need to be repainted. You can test this with something like `servo -s 64 -Z paint-flashing tests/html/dlbi.html` and mousing over the button.

Requires https://github.com/servo/rust-layers/pull/167 to land first.

r? @glennw

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6213)

### CODE REVIEW

**Comment by waddlesplash** [comment]
Just curious: do you have any numbers for how much faster this can be / is in practice?

**Comment by glennw** [comment]
Review status: all files reviewed, 4 unresolved discussions, some commit checks failed.
Reviewed files:
- components/compositing/compositor.rs @ r2
- components/compositing/compositor_layer.rs @ r1
- components/gfx/display_list/invalidation.rs @ r1
- components/gfx/display_list/mod.rs @ r2
- components/gfx/paint_task.rs @ r2
- components/layout/display_list_builder.rs @ r2
- components/msg/compositor_msg.rs @ r1
- components/util/range.rs @ r1
- tests/html/dlbi.html @ r1

---

<sup>**[components/compositing/compositor.rs, line 658 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6213#-JqS8nQHeR-WNBKT07zU)** ([raw file](https://github.com/servo/servo/blob/d4fe046a45a6d57dab7c2ca208ec290f45a128ec/components/compositing/compositor.rs#L658)):</sup>
Use unwrap or expect?

---

<sup>**[components/compositing/compositor.rs, line 680 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6213#-JqS8rRdVYXSMx9z-9Kz)** ([raw file](https://github.com/servo/servo/blob/d4fe046a45a6d57dab7c2ca208ec290f45a128ec/components/compositing/compositor.rs#L680)):</sup>
unwrap or expect?

---

<sup>**[components/compositing/compositor.rs, line 1241 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6213#-JqhHOel9mffHDgo6zUt)** ([raw file](https://github.com/servo/servo/blob/d4fe046a45a6d57dab7c2ca208ec290f45a128ec/components/compositing/compositor.rs#L1241)):</sup>
Perhaps the function should be "invalidate_and_send ... " to make it clear from reading calling code?

---

<sup>**[components/gfx/display_list/invalidation.rs, line 316 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6213#-JqhKgmbHjMKhBT-98Mr)** ([raw file](https://github.com/servo/servo/blob/d4fe046a45a6d57dab7c2ca208ec290f45a128ec/components/gfx/display_list/invalidation.rs#L316)):</sup>
Is there a reason not to destructure the base item as you have for the items below?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6213)

**Comment by glennw** [comment]
@pcwalton This seems to break the 3d transforms demos (stuff clips and doesn't update). I'll do some more investigation. tests/ref/iframe/positioning_margin is also failing with this PR (on my laptop at least).

**Comment by glennw** [comment]
@pcwalton I looked briefly into this - it appears to suffer the same problems as we currently have with clipping on 3d layers. How about updating this PR to disable DLBI on 3d layers (like we do for clipping currently)? That way, we can get this merged since it is useful for 2d layers anyway, and when I get to supporting clipping for 3d layers, I can also fix up the DLBI on 3d layers then?

**Comment by pcwalton** [comment]
Rebased and attempted to turn this off for 3D layers.

@glennw How does this look?

**Comment by glennw** [comment]
@pcwalton Looks good to me, just needs a rebase.

**Comment by jdm** [comment]
```


failures:
    border_spacing_a.html == border_spacing_ref.html
    iframe/positioning_margin.html == iframe/positioning_margin_ref.html
```

**Comment by pcwalton** [comment]
@bors-servo: retry

They may be intermittent. I'm going to retry to see if they are.

**Comment by pcwalton** [comment]
OK, so `positioning_margin` is not intermittent, but `border_spacing` is. That's what I had suspected/worried about. Is the `border_spacing` one pre-existing, I wonder?

**Comment by pcwalton** [comment]
Actually, IIRC they're both intermittent; it's just that the iframe ones fail more often. I worry that DLBI is making our known compositor races worse :(

**Comment by metajack** [comment]
```
/home/servo/buildbot/slave/linux1/build/tests/unit/util/lib.rs:5:35: 5:43 warning: unused or unknown feature, #[warn(unused_features)] on by default
/home/servo/buildbot/slave/linux1/build/tests/unit/util/lib.rs:5 #![feature(plugin, custom_derive, heap_api)]
                                                                                                   ^~~~~~~~
   Compiling servo v0.0.1 (file:///home/servo/buildbot/slave/linux1/build/components/servo)
../../tests/reftest.rs:46:26: 46:32 warning: use of deprecated item: superseded by split_first, #[warn(deprecated)] on by default
../../tests/reftest.rs:46     let mut parts = args.tail().split(|e| &**e == "--");
                                                   ^~~~~~
../../tests/reftest.rs:104:22: 104:42 warning: use of deprecated item: use process::exit instead, #[warn(deprecated)] on by default
../../tests/reftest.rs:104         Ok(false) => env::set_exit_status(1), // tests failed
                                                ^~~~~~~~~~~~~~~~~~~~
../../tests/reftest.rs:105:19: 105:39 warning: use of deprecated item: use process::exit instead, #[warn(deprecated)] on by default
../../tests/reftest.rs:105         Err(_) => env::set_exit_status(2),    // I/O-related failure
                                             ^~~~~~~~~~~~~~~~~~~~
```

**Comment by pcwalton** [comment]
That was the reftest I fixed… maybe it's a Linux-only failure now?

**Comment by glennw** [comment]
@pcwalton Should we close this and re-open it when you have time to look at this again?

**Comment by pcwalton** [comment]
Yeah, sure.

**Pull request closed without merging**
