### PR TITLE
fix #4948 (removing ScriptMsg::Navigate)

### LINKED ISSUE #4948: Remove ScriptMsg::Navigate
It appears to be unused, since nobody instructs the script task to perform navigation in history.

Code: `components/script/script_task.rs`

### PR DESCRIPTION
**Pull request by seanmoon80**
I just removed code. is there something else that I need to do?

### CODE REVIEW

**Comment by jdm** [comment]
@seanmoon80 We'll want to remove the actual declaration from the ScriptMsg enum, too.

**Comment by jdm** [comment]
Similarly, that method is no longer called...

**Comment by jdm** [comment]
@seanmoon80 Could you remove handle_navigate_msg too?

**Comment by Ms2ger** [comment]
@seanmoon80: thanks a lot for your contribution! I rebased this as <https://github.com/servo/servo/pull/5068> and we'll be merging it right away.

**Pull request closed without merging**
