### PR TITLE
M1503: Integrate XML5 parser

### PR DESCRIPTION
**Pull request by Ronak6892**
Hi,

This is for NCSU fall 15 project for Mozilla.

We have included changes for initial steps in this pull request.
https://github.com/servo/servo/wiki/Integrate-xml5ever

Kindly review !

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8278)

### CODE REVIEW

**Comment by eefriedman** [comment]
Once you've addressed the review comments, please rebase and squash.


---

Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

<sup>**[components/script/Cargo.toml, line 88 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1utRjkYjIs_VidXgcs)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/Cargo.toml#L88)):</sup>
Please match the style of other dependencies in this file.  (Specifically, the git url.)


---

<sup>**[components/script/dom/domparser.rs, line 72 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1utctIqn5d22_GtTKM)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/dom/domparser.rs#L72)):</sup>
Could you fix this to match the parse_html case a bit more closely, so we don't have to modify this again once XML parsing is actually working?


---

<sup>**[components/script/dom/servoxmlparser.rs, line 1 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1uu9as0RYCxxnz53pW)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/dom/servoxmlparser.rs#L1)):</sup>
Missing license header.


---

<sup>**[components/script/dom/servoxmlparser.rs, line 9 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1uw2Q01wV4N6Nmbiq0)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/dom/servoxmlparser.rs#L9)):</sup>
ServoXMLParser should be marked `#[dom_struct]`.


---

<sup>**[components/script/dom/servoxmlparser.rs, line 10 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1uts4M0ZBJ4HMuk9vi)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/dom/servoxmlparser.rs#L10)):</sup>
Tab.  (Also in a bunch of other places in this file.)


---

<sup>**[components/script/dom/servoxmlparser.rs, line 15 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1utt6CkUrOyKJHU_jL)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/dom/servoxmlparser.rs#L15)):</sup>
Trailing whitespace.  


---

<sup>**[components/script/dom/servoxmlparser.rs, line 20 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1uu4cgorTjMkgrl8T-)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/dom/servoxmlparser.rs#L20)):</sup>
Space before opening brace (also in other places).


---

<sup>**[components/script/dom/webidls/ServoXMLParser.webidl, line 1 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1uuBe_KjzTSgNnIEsz)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/dom/webidls/ServoXMLParser.webidl#L1)):</sup>
Missing license header.


---

<sup>**[components/script/parse/xml.rs, line 1 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1uuEp_KNu4ROCVplnn)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/parse/xml.rs#L1)):</sup>
Missing license header.


---

<sup>**[components/script/parse/xml.rs, line 4 \[r11\]](https://reviewable.io:443/reviews/servo/servo/8278#-K1uube27wGTUTRq5SF0)** ([raw file](https://github.com/servo/servo/blob/a15e9f1096cd57cfcb749daab5c9d81b812644e3/components/script/parse/xml.rs#L4)):</sup>
This should have the same signature as parse_html.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8278)

**Comment by jdm** [comment]
Note: be sure to run `./mach test-tidy` and fix the reported errors :)

**Comment by Jigar24** [comment]
Hi,

In parse_xml, are we supposed to use ParseContext enum defined in html.rs file? We can not import two different types with same name in domparse.rs. 

Also, while running ./mach test-tidy, we are getting "Specification link not found" error for servoxmlparse.webidl file on line 0. Can you elaborate for this error or how to solve it? 

Thanks,
Jigar

**Comment by eefriedman** [comment]
For the specification link error, the file needs to contain the following comment:

```
// This interface is entirely internal to Servo, and should not be accessible to
// web pages.
```

For ParseContext, it definitely shouldn't use the same version.  If you're running into trouble with the names, there are a few different ways to deal with it; the simplest is probably just to refer to them as html::ParseContext and xml::ParseContext. (You can write `use parse::html::{self, parse_html};` etc. to make that work.)

**Comment by Jigar24** [comment]
Hi,

I tried to implement your suggestion by referring as xml::ParseContext but since it is a enum, I think it is not able to resolve the reference. However, same works fine for parse_xml (i.e. xml::parse_xml).

I think this is some known issue with enum in Rust. I tried to define my enum "pub enum mod ParseContext" as explained in this link (https://github.com/rust-lang/rust/issues/10090). But also didn't work out as it throws an error saying it expects a '{ 'after enum. I have also tried to nest enum inside a mod and call it but that also in not working. Can you point to a file or link where such situation has been handled? 

Also, for rebase and squash, are we supposed to sqaush only those commits which are added after review or all the commits that we made? 

One last quesion on servoxmlparse.rs After adding #[dom_struct], I can eliminate Reflectable and JSTraceable stubs as servo builds even without them. So shall I remove them as they are not necessary or shall I keep them as they are because they might be used in future?

Thanks,
Jigar

**Comment by eefriedman** [comment]
See http://is.gd/UeCztt for an outline of what I was thinking of with the enums.

If you're trying to look up information about Rust syntax, https://doc.rust-lang.org/nightly/book/ is usually the first place to go.  Try to be careful about where exactly you look for documentation; "enum mod" isn't valid syntax anymore.

> Also, for rebase and squash, are we supposed to sqaush only those commits which are added after review or all the commits that we made?

Squash everything.  (The reasoning behind this policy is that we don't really want the development history of every patch in master; it's mostly just noise.)

> One last quesion on servoxmlparse.rs After adding #[dom_struct], I can eliminate Reflectable and JSTraceable stubs as servo builds even without them. So shall I remove them as they are not necessary or shall I keep them as they are because they might be used in future?

Remove them. dom_struct triggers a plugin generates all the necessary code.

**Comment by eefriedman** [comment]
This is looking good!  Just a few more minor changes, and the commits need to be squashed.


---

Reviewed 1 of 7 files at r10, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r15, 1 of 2 files at r16, 2 of 2 files at r18, 1 of 1 files at r19.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[components/script/dom/domparser.rs, line 77 \[r20\]](https://reviewable.io:443/reviews/servo/servo/8278#-K2Hu8F42gk0Ag_sPZ71)** ([raw file](https://github.com/servo/servo/blob/a67d001e349e68d7e9fd1bb90bd4b78033cbd282/components/script/dom/domparser.rs#L77)):</sup>
Indentation (try to align all the arguments).


---

<sup>**[components/script/dom/servoxmlparser.rs, line 10 \[r20\]](https://reviewable.io:443/reviews/servo/servo/8278#-K2HuaWtonNZSFOXBxBX)** ([raw file](https://github.com/servo/servo/blob/a67d001e349e68d7e9fd1bb90bd4b78033cbd282/components/script/dom/servoxmlparser.rs#L10)):</sup>
Indentation.


---

<sup>**[components/script/dom/servoxmlparser.rs, line 14 \[r20\]](https://reviewable.io:443/reviews/servo/servo/8278#-K2HudL7XtLg2oiMhQXd)** ([raw file](https://github.com/servo/servo/blob/a67d001e349e68d7e9fd1bb90bd4b78033cbd282/components/script/dom/servoxmlparser.rs#L14)):</sup>
Indentation.


---

<sup>**[components/script/parse/xml.rs, line 16 \[r20\]](https://reviewable.io:443/reviews/servo/servo/8278#-K2HujJ3RvnEUU0ulMUL)** ([raw file](https://github.com/servo/servo/blob/a67d001e349e68d7e9fd1bb90bd4b78033cbd282/components/script/parse/xml.rs#L16)):</sup>
Indentation.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8278)

**Comment by jdm** [comment]
Note that squashing means [this operation](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

**Comment by eefriedman** [comment]
Looks like the commit wasn't rebased correctly:

```
/home/travis/build/servo/servo/components/script/dom/domparser.rs:78:41: 78:42 error: mismatched types:
 expected `collections::string::String`,
    found `util::str::DOMString`
(expected struct `collections::string::String`,
    found struct `util::str::DOMString`) [E0308]
/home/travis/build/servo/servo/components/script/dom/domparser.rs:78                 parse_xml(document.r(), s, url, xml::ParseContext::Owner(None));
                                                                                                             ^
/home/travis/build/servo/servo/components/script/dom/domparser.rs:78:41: 78:42 help: run `rustc --explain E0308` to see a detailed explanation
```

I think you just need to replace `s` with `DOMString(s)`.

**Comment by eefriedman** [comment]
(Also, please leave a comment when you upload new changes; GitHub doesn't send a notification.)

**Comment by Jigar24** [comment]
Hi, 
I have changed String to DOMString in parse_xml due to which previous build had failed. I have squashed new commits and I was able to build it successfully on my local. Please review it.

Thanks

**Pull request merged**
