### PR TITLE
Add support for viewport size adjustments in wptrunner.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9076)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Only a few left! :sparkles:

**Comment by jgraham** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/wpt/harness/wptrunner/executors/executormarionette.py, line 389 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9076#-K6f6eD64_vcHavm-w8z:-K6f6eD71HNjwnbsl8xb:-1718526930) ([raw file](https://github.com/servo/servo/blob/d0f22c20f9a5fc8a5d82e0c41ee1ebea34d34132/tests/wpt/harness/wptrunner/executors/executormarionette.py#L389)):*
OK, I guess, but can we file issues to support this for all the executors in the future? I don't see why it would be restricted to servo-only.

---

*[tests/wpt/harness/wptrunner/executors/executorservodriver.py, line 230 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9076#-K6f6zdJ67xRUd1cs6De:-K6f6zdJ67xRUd1cs6Df:-1667726781) ([raw file](https://github.com/servo/servo/blob/d0f22c20f9a5fc8a5d82e0c41ee1ebea34d34132/tests/wpt/harness/wptrunner/executors/executorservodriver.py#L230)):*
This one is particularly problematic, ofc.

---

*[tests/wpt/web-platform-tests/tools/manifest/sourcefile.py, line 186 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9076#-K6f5zh9xvrEzgsNqLY2:-K6f5zh9xvrEzgsNqLY3:-809382197) ([raw file](https://github.com/servo/servo/blob/d0f22c20f9a5fc8a5d82e0c41ee1ebea34d34132/tests/wpt/web-platform-tests/tools/manifest/sourcefile.py#L186)):*
Don't mention servo in the comment here, please; this will get out of date.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9076)*

**Comment by jdm** [comment]
```
Error running mach:

    ['test-wpt', '--release', '--processes', '4', '--log-raw', 'test-wpt.log']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

TypeError: __init__() got an unexpected keyword argument 'viewport_size'

  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/python/servo/testing_commands.py", line 293, in test_wpt
    return run_globals["run_tests"](**kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/run_wpt.py", line 13, in run_tests
    return run.run_tests(paths=paths, **kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/run.py", line 36, in run_tests
    success = wptrunner.run_tests(**kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/wptrunner.py", line 133, in run_tests
    **kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/wptrunner.py", line 71, in get_loader
    include_https=ssl_env.ssl_enabled)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/testloader.py", line 459, in __init__
    self._load_tests()
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/testloader.py", line 525, in _load_tests
    for test_path, test_type, test in self.iter_tests():
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/testloader.py", line 513, in iter_tests
    self.iter_wpttest(inherit_metadata, test_metadata, tests)):
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/testloader.py", line 420, in iterfilter
    for item in iter:
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/testloader.py", line 518, in iter_wpttest
    yield self.get_test(manifest_test, inherit_metadata, test_metadata)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/testloader.py", line 475, in get_test
    return wpttest.from_manifest(manifest_test, inherit_metadata, test_metadata)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/wpttest.py", line 303, in from_manifest
    return test_cls.from_manifest(manifest_test, inherit_metadata, test_metadata)
  File "/Users/servo/buildbot/slave/mac-rel-wpt/build/tests/wpt/harness/wptrunner/wpttest.py", line 117, in from_manifest
    viewport_size=getattr(manifest_item, "viewport_size", None))
```

**Comment by jdm** [comment]
```
Error running mach:

    ['test-css', '--release', '--processes', '4', '--log-raw', 'test-css.log']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

AttributeError: 'RefTest' object has no attribute 'viewport_size'

  File "/Users/servo/buildbot/slave/mac-rel-css/build/python/servo/testing_commands.py", line 348, in test_css
    return run_globals["run_tests"](**kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/run_css.py", line 13, in run_tests
    return run.run_tests(paths=paths, **kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/run.py", line 36, in run_tests
    success = wptrunner.run_tests(**kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/wptrunner.py", line 133, in run_tests
    **kwargs)
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/wptrunner.py", line 71, in get_loader
    include_https=ssl_env.ssl_enabled)
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/testloader.py", line 459, in __init__
    self._load_tests()
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/testloader.py", line 525, in _load_tests
    for test_path, test_type, test in self.iter_tests():
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/testloader.py", line 513, in iter_tests
    self.iter_wpttest(inherit_metadata, test_metadata, tests)):
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/testloader.py", line 420, in iterfilter
    for item in iter:
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/testloader.py", line 518, in iter_wpttest
    yield self.get_test(manifest_test, inherit_metadata, test_metadata)
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/testloader.py", line 475, in get_test
    return wpttest.from_manifest(manifest_test, inherit_metadata, test_metadata)
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/wpttest.py", line 302, in from_manifest
    return test_cls.from_manifest(manifest_test, inherit_metadata, test_metadata)
  File "/Users/servo/buildbot/slave/mac-rel-css/build/tests/wpt/harness/wptrunner/wpttest.py", line 252, in from_manifest
    viewport_size=manifest_test.viewport_size,
program finished with exit code 1
elapsedTime=7.809151
```

**Comment by KiChjang** [comment]
@bors-servo retry
* #8769

**Comment by Ms2ger** [comment]
Also #9148

**Pull request merged**
