### PR TITLE
Fix createImageData with sizes < 1 pixel

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6974)

### CODE REVIEW

**Comment by pcwalton** [comment]
Is there a test for this?

**Comment by dzbarsky** [comment]
Yep, the one I deleted the metadata for :)

**Comment by jdm** [comment]
This seems odd to me. There's no explicit spec text for this, and Gecko doesn't appear to have a similar maximization step: https://dxr.mozilla.org/mozilla-central/source/dom/canvas/CanvasRenderingContext2D.cpp#5365

**Comment by jdm** [comment]
I'm going off of https://html.spec.whatwg.org/multipage/scripting.html#pixel-manipulation:dom-context-2d-createimagedata-3 by the way.

**Comment by dzbarsky** [comment]
Gecko does the equivalent thing here: https://dxr.mozilla.org/mozilla-central/source/dom/canvas/CanvasRenderingContext2D.cpp#5341 (this is after calling abs).

The relevant spec text is a little lower: 
"New ImageData objects must be initialised so that their width attribute is set to the number of pixels per row in the image data, their height attribute is set to the number of rows in the image data...At least one pixel's worth of image data must be returned."
So the minimum size is 1x1.

**Comment by dzbarsky** [comment]
Unfortunately the canvas spec doesn't really list explicit steps for its algorithms, you have to infer them from various requirements. That's why we fail so many edge-case tests.

**Comment by jdm** [comment]
Delightful!

**Comment by jdm** [comment]
@bors-servo: retry
* infra issue

**Pull request merged**
