### PR TITLE
Implement pinch zoom emulation to the glutin port

### PR DESCRIPTION
**Pull request by mrobinson**
The GLFW port had pinch zoom emulation that could be triggered by
holding control and using the mouse wheel. This was very useful for
testing pinch zoom behavior on desktop machines. This commit
implements this for the glutin port.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8215)

### CODE REVIEW

**Comment by mrobinson** [comment]
@glennw r?

**Comment by jdm** [comment]
We actually just removed this intentionally in #8121.

**Comment by mrobinson** [comment]
@jdm @paulrouget Sorry. I should have looked a bit more closely. Perhaps this behavior can either be put behind a flag or change to a different key binding.

**Pull request merged**
