### PR TITLE
Bump js to get fix from servo/rust-mozjs#237

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9570)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I wanna test :)

**Comment by jdm** [comment]
@bors-servo: r-
@Ms2ger was asking for a test that verifies this change, I'm pretty sure.

**Comment by KiChjang** [comment]
Oh, sorry, didn't read the message.

**Comment by jdm** [comment]
I guess we got the changes in #9584 but still no test.

**Pull request closed without merging**
