### PR TITLE
Pass around event types as Atoms instead of Strings

### PR DESCRIPTION
**Pull request by frewsxcv**
`Event` internally stores the `type` as an `Atom`, and we're `String`s
everywhere, which can cause unnecessary allocations to occur since
they'll end up as `Atom`s anyways.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8930)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Should the new initialization methods take `EventBubbles`?

**Comment by frewsxcv** [comment]
Probably, but I'd rather make a separate issue for that

**Comment by nox** [comment]
@bors-servo r+

Looks ok to me, please file a follow-up issue for what @Ms2ger said.

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8930#-:-K5GhD0uKlsKTsK3yw1P:-1078371038)*

**Pull request merged**
