### PR TITLE
OSMesa is no longer a build dependency

### PR DESCRIPTION
**Pull request by SimonSapin**
Since https://github.com/servo/servo/pull/25853

### CODE REVIEW

**Comment by dralley** [comment]
Several of these issues can probably be cleaned up as well: https://github.com/servo/servo/issues?q=is%3Aissue+is%3Aopen+osmesa

**Comment by jdm** [comment]
@bors-servo retry
* #26192

**Comment by jdm** [comment]
@bors-servo retry
* #25513

**Pull request merged**
