### PR TITLE
Allow XHR to fetch about: and data: URLs.

### LINKED ISSUE #8015: Allow requesting data URLs from XMLHttpRequest
Step 5 of https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send explicitly sets the `same-origin data-URL flag` to true. We have a TODO about this in `CORSRequest::maybe_new`; I propose creating a new enum representing this flag, and passing it as an argument to `CORSRequest::maybe_new`. This should cause the output of `./mach test-wpt tests/wpt/web-platform-tests/XMLHttpRequest/data-uri.htm` to improve.

Note: this is reserved for a potential Outreachy contributor who I am in contact with.

Code: `components/script/cors.rs`, `components/script/dom/xmlhttprequest.rs`

### PR DESCRIPTION
**Pull request by emosenkis**
This was intended to fix #8015 but the tests are all still failing as of
this commit.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8807)

### CODE REVIEW

**Comment by Manishearth** [comment]
Looks good so far. Any idea why the tests fail?

**Comment by SimonSapin** [comment]
And which tests are failing?

**Comment by frewsxcv** [comment]
Tidy fail:

```
./components/script/cors.rs:77: tab on line

./components/script/cors.rs:78: tab on line
```

https://travis-ci.org/servo/servo/jobs/94749628

**Comment by Wafflespeanut** [comment]
@emosenkis um, did you notice the above comment?

**Comment by emosenkis** [comment]
@frewsxcv Fixed.
@Wafflespeanut Yep, but it took me until now to find time to work on it.
@SimonSapin All 10 of the tests in data-uri.htm are still failing.
@Manishearth I'm not sure why the first five tests are failing - it seems to be returning a null response when it should be returning a successful one. I'll have to dig into this further (it may take me some time). The last five tests seem to be failing due to an inconsistency between the tests and the spec. While the test [asserts](https://github.com/servo/servo/blob/1a81b18b9f22d7bc1a967d08fcc7fbcf2ee200f5/tests/wpt/web-platform-tests/XMLHttpRequest/data-uri.htm#L26) for statusText == "OK" when a network error is expected, the [spec](https://fetch.spec.whatwg.org/#concept-network-error) indicates that the status message should be the empty byte sequence, which is what servo currently does.

Here is the current test output (I pulled it from the --log-raw file - is there a better way?)
```json
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method GET with charset text/plain", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected (string) \"text/plain\" but got (object) null", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:23:1\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\n"}
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method GET with charset text/plain (base64)", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected (string) \"text/plain\" but got (object) null", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:23:1\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\n"}
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method GET with charset text/html", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected (string) \"text/html\" but got (object) null", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:23:1\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\n"}
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method GET with charset text/html;charset=UTF-8", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected (string) \"text/html;charset=UTF-8\" but got (object) null", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:23:1\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\n"}
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method GET with charset image/png", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected (string) \"image/png\" but got (object) null", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:23:1\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\n"}
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method POST with charset text/plain", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected \"OK\" but got \"\"", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:16:11\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\ndo_test/<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:30:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\ndo_test@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:4:5\n@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:38:3\n"}
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method PUT with charset text/plain", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected \"OK\" but got \"\"", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:16:11\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\ndo_test/<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:30:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\ndo_test@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:4:5\n@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:39:3\n"}
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method DELETE with charset text/plain", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected \"OK\" but got \"\"", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:16:11\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\ndo_test/<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:30:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\ndo_test@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:4:5\n@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:40:3\n"}
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method HEAD with charset text/plain", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected \"OK\" but got \"\"", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:16:11\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\ndo_test/<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:30:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\ndo_test@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:4:5\n@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:41:3\n"}
{"status": "FAIL", "thread": "Thread-TestrunnerManager-1", "subtest": "XHR method UNICORN with charset text/plain", "pid": 2979, "source": "web-platform-tests", "test": "/XMLHttpRequest/data-uri.htm", "time": 1449613354822, "action": "test_status", "message": "assert_equals: expected \"OK\" but got \"\"", "stack": "do_test/</client.onreadystatechange<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:16:11\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1\ndo_test/<@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:30:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20\ndo_test@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:4:5\n@http://web-platform.test:8000/XMLHttpRequest/data-uri.htm:42:3\n"}
```

**Comment by jdm** [comment]
Looks like Gecko fails all the same tests too, probably for the same reason!

**Comment by Manishearth** [comment]
Okay, in that case could you file a spec bug?

**Comment by jdm** [comment]
I'm pretty sure the correct choice would be to modify the test, but I need to verify that.

**Comment by Manishearth** [comment]
My bad, I meant a wpt bug :smile:

**Comment by jdm** [comment]
Oops, this fell through the cracks.

**Comment by jdm** [comment]
Let's modify the test to expect an empty statusText value per the spec.

**Comment by jdm** [comment]
The code as written looks fine, but I'm curious why the first five tests are failing. This shouldn't merge without figuring out why that's happening.

**Comment by jdm** [comment]
Got it - the test relies on getResponseHeader and getAllResponseHeaders, but we don't actually create a headers object in the Metadata value in `data_loader.rs`. Even more confusingly, Metadata::set_content_type doesn't interact with the nonexistent headers object, and sets a separate field in Metadata.

**Comment by jdm** [comment]
I'd say the short-term fix is to create a headers object and set the Content-Type header in it in data_loader.rs, and we'll file an issue about fixing this mess properly.

**Comment by KiChjang** [comment]
@emosenkis Are you still working on this?

**Comment by emosenkis** [comment]
@KiChjang I do still intend to finish this up and get it committed, but my laptop was stolen, which leaves me with more limited computer access (I should be getting a new one at some point). If this fix is needed for other work to continue, I won't be offended if someone else does this instead.

**Comment by jdm** [comment]
Sorry to hear that! I'm going to go ahead and close this PR for the time being; if you get regular access again and want to continue with it, please feel free to do so!

**Pull request closed without merging**
