### PR TITLE
CI: use new intermittent-tracker deployment

### PR DESCRIPTION
**Pull request by delan**
This patch switches to our new [intermittent-tracker](https://github.com/servo/intermittent-tracker) instance at [intermittent-tracker.servo.org](https://intermittent-tracker.servo.org), as deployed in servo/ci-runners [43d56bf194f81...304212f15d9b2](https://github.com/servo/ci-runners/compare/43d56bf194f81b3f88ab5d22b6339968411465a8...304212f15d9b2a46a5209ab1278e94388b3579ab).

As a result, we will also be able to test future intermittent-tracker changes by deploying to [staging.intermittent-tracker.servo.org](https://staging.intermittent-tracker.servo.org), and opening a pull request in this repo with the following changes:

- `TRACKER_API = "https://staging.intermittent-tracker.servo.org"`
- `TRACKER_DASHBOARD_SECRET_ENV_VAR = "INTERMITTENT_TRACKER_DASHBOARD_SECRET_STAGING"`

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] ~~These changes fix #___ (GitHub issue number if applicable)~~

- [x] CI test plan
  - [x] Build with unauthenticated POST /dashboard/query (<https://github.com/servo/servo/actions/runs/11659374763/job/32459956121#step:8:3022>)
  - [x] Build with authenticated POST /dashboard/attempts (<https://github.com/delan/servo/actions/runs/11659487000/job/32461315667#step:8:2649>)
  - [x] Data stored in tracker correctly: <https://intermittent-tracker.servo.org/?build_url=https%3A%2F%2Fgithub.com%2Fdelan%2Fservo%2Factions%2Fruns%2F11659487000>

### CODE REVIEW

**Comment by delan** [comment]
No data in database for [this build](https://github.com/servo/servo/actions/runs/11626919410/job/32379637271):

```
$ sqlite3 /config/intermittent-tracker/prod/data/dashboard.sqlite
sqlite> SELECT * FROM submission WHERE build_url = 'https://github.com/servo/servo/actions/runs/11626919410';
sqlite>
```

But we do get a bunch of successful POST requests:

```
$ journalctl -u intermittent-tracker-prod | rg 'POST /dashboard/query'
Nov 01 09:21:26 ci0 intermittent-tracker-prod-start[3629791]: 127.0.0.1 - - [01/Nov/2024 09:21:26] "POST /dashboard/query HTTP/1.1" 200 -
Nov 01 09:22:48 ci0 intermittent-tracker-prod-start[3629791]: 127.0.0.1 - - [01/Nov/2024 09:22:48] "POST /dashboard/query HTTP/1.1" 200 -
Nov 01 09:23:17 ci0 intermittent-tracker-prod-start[3629791]: 127.0.0.1 - - [01/Nov/2024 09:23:17] "POST /dashboard/query HTTP/1.1" 200 -
Nov 01 09:23:37 ci0 intermittent-tracker-prod-start[3629791]: 127.0.0.1 - - [01/Nov/2024 09:23:37] "POST /dashboard/query HTTP/1.1" 200 -
Nov 01 09:23:48 ci0 intermittent-tracker-prod-start[3629791]: 127.0.0.1 - - [01/Nov/2024 09:23:48] "POST /dashboard/query HTTP/1.1" 200 -
[...]
```

And they all come from [Microsoft IP addresses](https://bgp.he.net/AS8075):

```
$ rg 'POST /dashboard/query' /var/log/nginx/access.log
53911:40.65.196.146 - - [01/Nov/2024:09:21:27 +0000] "POST /dashboard/query HTTP/1.1" 200 1009 "-" "Python-urllib/3.10"
53969:13.91.68.144 - - [01/Nov/2024:09:22:48 +0000] "POST /dashboard/query HTTP/1.1" 200 401 "-" "Python-urllib/3.10"
53980:40.67.141.251 - - [01/Nov/2024:09:23:17 +0000] "POST /dashboard/query HTTP/1.1" 200 1426 "-" "Python-urllib/3.10"
53990:20.102.46.145 - - [01/Nov/2024:09:23:37 +0000] "POST /dashboard/query HTTP/1.1" 200 1206 "-" "Python-urllib/3.10"
53994:172.203.41.195 - - [01/Nov/2024:09:23:48 +0000] "POST /dashboard/query HTTP/1.1" 200 401 "-" "Python-urllib/3.10"
[...]
```

**Review by mrobinson — APPROVED** [review]
This seems fine, but do you have any idea why so many tests are failing @delan?

**Comment by delan** [comment]
> This seems fine, but do you have any idea why so many tests are failing @delan?

I was intentionally testing unexpected results by breaking ‘align-self’ in [this commit](https://github.com/servo/servo/commit/6012cd38112bbfa61bac64302c371089d0e16621) :)

**Comment by delan** [comment]
If this fails again, the known intermittents check may be misbehaving.

**Comment by jdm** [comment]
I suspect these changes have broken our GitHub labels integration with I-intermittent.

**Comment by delan** [comment]
Oh! That would explain why I had to open #34131 despite #34127 already existing…

**Pull request merged**
