### PR TITLE
Make canvas origin clean checks use origin of image response

### LINKED ISSUE #15409: Use the entry settings object in CanvasRenderingContext2d::is_origin_clean
We recently gained support for [GlobalScope::entry](http://doc.servo.org/script/dom/globalscope/struct.GlobalScope.html#method.entry), so we can use it to fix the TODO in this method.

Code: `components/script/dom/canvasrenderingcontext2d.rs`
Test: Try running `./mach test-wpt tests/wpt/web-platform-tests/2dcontext/` and see if any unexpected results appear.

### PR DESCRIPTION
**Pull request by jdm**
Adapted from #15887.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15409
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16913)

### CODE REVIEW

**Comment by Manishearth** [comment]
homu seems confused about mergeability here. could you force-push an amended commit and re-r+?

**Comment by jdm** [comment]
The current queue seems to think it's mergeable, so I'm going to leave it alone.

**Pull request merged**
