### PR TITLE
Hoist gecko bindings into their own crate

### PR DESCRIPTION
**Pull request by bholley**
This will be helpful for leveraging the bindings with our nsIAtom-backed
string_cache replacement.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11121)

### CODE REVIEW

**Comment by bholley** [comment]
r? @mbrubeck 
CC @heycam @emilio

**Comment by mbrubeck** [comment]
r=mbrubeck with some tiny doc updates (below)

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, bholley (Bobby Holley) wrote…</i></summary>
> r? @mbrubeck 
> 
> CC @heycam @emilio</details>


---

Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ports/geckolib/gecko_bindings/tools/README.md, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11121#-KHRy_gTokqdMnbNA35h:-KHRy_gUGY40C3ZeCrpG:18173636) ([raw file](https://github.com/servo/servo/blob/1b928300eeff231414b161577d7ee1ea132ba977/ports/geckolib/gecko_bindings/tools/README.md#L21)):*
> ```Markdown
> 
> This will regenerate the bindings for the `ServoBindings.h` file in your gecko
> build (which are in `ports/geckolib/bindings.rs`).
> ```

Should be `ports/geckolib/gecko_bindings/bindings.rs` or `../bindings.rs`.

---

*[ports/geckolib/gecko_bindings/tools/README.md, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11121#-KHRxWQfKTD6_Lk1EZ_h:-KHRxWQg7v1XHn3_Xl6e:-345675206) ([raw file](https://github.com/servo/servo/blob/1b928300eeff231414b161577d7ee1ea132ba977/ports/geckolib/gecko_bindings/tools/README.md#L26)):*
> ```Markdown
> 
> This will generate the bindings for Gecko's style structs. Current bindings are
> actually in `ports/geckolib/structs.rs`.
> ```

Should be `ports/geckolib/gecko_bindings/structs.rs` or `../structs.rs`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11121#-:-KHRzVMMIWo9xkS8LysI:-199842411)*

**Comment by heycam** [comment]
Sorry, I think I caused you merge conflicts twice in a row!

**Comment by bholley** [comment]
@bors=servo p=1

This has bitrotted three times now.

**Comment by mbrubeck** [comment]
```
error: Unable to update file:///Users/servo/buildbot/slave/mac-dev-unit/build/ports/geckolib/gecko_bindings

Caused by:
  failed to read `/Users/servo/buildbot/slave/mac-dev-unit/build/ports/geckolib/gecko_bindings/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by bholley** [comment]
@bors-servo r=mbrubeck

Forgot to `git add`.

**Pull request merged**
