### PR TITLE
gfx: Fix bug with 1px width borders disappearing

### LINKED ISSUE #7184: Rounding issue causing some borders not to be visible.
Regression occurred in https://github.com/servo/servo/pull/7161

Minimal test case:

```
<!DOCTYPE html>
<html>
	<head>
		<style type="text/css">
			.onyx {
				color: white;
			}
			.item {
				background-color: #333;
				border-bottom: 1px solid white;
			}
		</style>
	</head>
	<body>
		<div class="onyx">
			<div class="item">1</div>
			<div class="item">2</div>
			<div class="item">3</div>
			<div class="item">4</div>
		</div>
	</body>
</html>
```

### PR DESCRIPTION
**Pull request by bjwbell**
In to_nearest_azure_rect when rounding to pixel coordinates, maintain
the invariant of rect non-overlap (if before rounding two rects don't overlap).

The previous code rounded the rect top left corner to the nearest pixel with
the size rounded to the nearest pixel multiple which can violate the
non-overlap condition, e.g.
10px×9.60px at (0px,6.6px) & 10px×9.60px at (0px,16.2px)
would round to
10px×10.0px at (0px,7.0px) & 10px×10.0px at (0px,16.0px), which overlap.

Instead round each corner to the nearest pixel.

For rects that dont need to satify the non-overlap condition and with
width or height between 0.5px and 1px, rounding each rect corner to the
nearest pixel can yield an empty rect e.g.
10px×0.6px at 0px,28.56px -> 10px×0px at 0px,29px.

For this scenario a new function to_nearest_non_empty_azure_rect
rounds the rect top left corner to the nearest pixel and the rect size
to the nearest pixel multiple. It's possible for non-overlapping rects
after this rounding to overlap.

This should fix https://github.com/servo/servo/issues/7184 "rounding ...borders not to be visible", without breaking https://github.com/servo/servo/issues/7152 "Underlines less than 1px high sometimes invisible".

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7577)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Looks good! I appreciate the detailed comments, too.

---

Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7577)

**Comment by jdm** [comment]
The reftest analyzer shows this test is missing a pixel line of orange at the bottom of the rendered test.

**Comment by jdm** [comment]
```
/css21_dev/html4/position-relative-035.htm
------------------------------------------
FAIL [Parent]
```

**Comment by mbrubeck** [comment]
> /css21_dev/html4/position-relative-035.htm

Note: #7152 changed this test from failing on both our test platforms to failing on Mac only. The Mac failure seems to be different (the line of text is missing completely).

**Comment by bjwbell** [comment]
Interesting, I actually hadn't run test-css locally. I'll take a look at it.

**Comment by bjwbell** [comment]
@mbrubeck rerun bors?

**Pull request merged**
