### PR TITLE
Fix compilation errors on stream-related DOM methods traits

### PR DESCRIPTION
**Pull request by jdm**
These fixes are necessary since #34357.

### CODE REVIEW

**Comment by jdm** [comment]
FYI @gterzian

**Comment by gterzian** [comment]
Thanks! I think we need to first rebase the feature branch from main for this right?(see compilation failures). cc @Taym95

**Comment by jdm** [comment]
Huh, I'm confused why https://github.com/servo/servo/actions/runs/12023699563/job/33518013376 shows errors that are clearly against a more recent main revision.

**Comment by mrobinson** [comment]
Perhaps this is the result of the `git switch --detach` execution that seems to be something that the hosted runners do? cc @delan

**Comment by jdm** [comment]
No worries!

**Pull request closed without merging**
