### PR TITLE
Rename Runnable to Task and other improvements

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18533)

### CODE REVIEW

**Comment by KiChjang** [comment]
The difference between main_thread_handler and handler back when I first implemented task sources was that the former's Runnale is sent as a MainThreadScriptMsg whereas the latter's Runnable is sent as a CommonScriptMsg.

Nowadays, the difference is irrelevant and main_thread_handler is exclusively used to get a reference to the containing script thread. StorageEvents used to require a reference but after heroic efforts from @asajeffrey, the reference is made unnecessary, making Promise Runnable the sole users of main_thread_handler. If you are able to figure out a way to provide the correct reference to a script thread (or just the relevant JS context), then I believe you can safely remove main_thread_handler altogether.

**Comment by nox** [comment]
@KiChjang Interesting. The ultimate goal of this is to be able to just use closures, so if I can remove `main_thread_handler` altogether it makes everything even better. Will look into that.

**Comment by nox** [comment]
Welp, I ended up introducing *and* removing `MainThreadTask` in the same PR…

**Comment by nox** [comment]
I added commits that finally introduce my `task!` macro idea, which allows us to use closures. I am hyped.

**Comment by KiChjang** [comment]
```
Checking files for tidiness...

./components/script/dom/globalscope.rs:53: use statement is not in alphabetical order
expected: task_source::performance_timeline::PerformanceTimelineTaskSource
found: task::TaskCanceller
```

**Comment by asajeffrey** [comment]
I think @jdm is away right now. The PR LGTM. Do however much squashing you deem appropriate then r=me.

**Comment by asajeffrey** [comment]
```
error: Expression of type std::rc::Rc<dom::promise::Promise> must be rooted
   --> /home/servo/buildbot/slave/linux-rel-css/build/components/script/serviceworkerjob.rs:278:17
    |
278 |             let promise = promise.root();
    |                 ^^^^^^^
    |
    = note: #[deny(unrooted_must_root)] on by default
```

**Comment by nox** [comment]
There was a `#[allow(unrooted_must_root)]` on the former version of the code in the last commit. This is fixed now.

@bors-servo r=SimonSapin

**Pull request merged**
