### PR TITLE
Cleanup JS traits and methods

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5871)

### CODE REVIEW

**Comment by jdm** [comment]
Reviewed files:
- components/script/devtools.rs @ r1
- components/script/dom/activation.rs @ r1
- components/script/dom/attr.rs @ r4
- components/script/dom/bindings/codegen/CodegenRust.py @ r6
- components/script/dom/bindings/error.rs @ r1
- components/script/dom/bindings/global.rs @ r1
- components/script/dom/bindings/js.rs @ r5
- components/script/dom/bindings/utils.rs @ r1
- components/script/dom/browsercontext.rs @ r4
- components/script/dom/canvasrenderingcontext2d.rs @ r4
- components/script/dom/comment.rs @ r1
- components/script/dom/cssstyledeclaration.rs @ r1
- components/script/dom/customevent.rs @ r1
- components/script/dom/dedicatedworkerglobalscope.rs @ r1
- components/script/dom/document.rs @ r4
- components/script/dom/documentfragment.rs @ r1
- components/script/dom/domimplementation.rs @ r1
- components/script/dom/domparser.rs @ r1
- components/script/dom/domrectlist.rs @ r4
- components/script/dom/domstringmap.rs @ r1
- components/script/dom/domtokenlist.rs @ r1
- components/script/dom/element.rs @ r1
- components/script/dom/errorevent.rs @ r1
- components/script/dom/event.rs @ r4
- components/script/dom/eventdispatcher.rs @ r1
- components/script/dom/htmlanchorelement.rs @ r1
- components/script/dom/htmlbodyelement.rs @ r1
- components/script/dom/htmlbuttonelement.rs @ r1
- components/script/dom/htmlcanvaselement.rs @ r3
- components/script/dom/htmlcollection.rs @ r4
- components/script/dom/htmldatalistelement.rs @ r1
- components/script/dom/htmlelement.rs @ r1
- components/script/dom/htmlfieldsetelement.rs @ r1
- components/script/dom/htmlformelement.rs @ r1
- components/script/dom/htmliframeelement.rs @ r1
- components/script/dom/htmlimageelement.rs @ r1
- components/script/dom/htmlinputelement.rs @ r2
- components/script/dom/htmllinkelement.rs @ r1
- components/script/dom/htmlobjectelement.rs @ r1
- components/script/dom/htmloptgroupelement.rs @ r1
- components/script/dom/htmloptionelement.rs @ r1
- components/script/dom/htmloutputelement.rs @ r1
- components/script/dom/htmlscriptelement.rs @ r1
- components/script/dom/htmlselectelement.rs @ r1
- components/script/dom/htmlstyleelement.rs @ r1
- components/script/dom/htmltableelement.rs @ r1
- components/script/dom/htmltextareaelement.rs @ r1
- components/script/dom/htmltitleelement.rs @ r1
- components/script/dom/keyboardevent.rs @ r1
- components/script/dom/location.rs @ r1
- components/script/dom/messageevent.rs @ r1
- components/script/dom/mouseevent.rs @ r4
- components/script/dom/namednodemap.rs @ r4
- components/script/dom/node.rs @ r4
- components/script/dom/nodelist.rs @ r4
- components/script/dom/performance.rs @ r4
- components/script/dom/progressevent.rs @ r1
- components/script/dom/range.rs @ r1
- components/script/dom/servohtmlparser.rs @ r1
- components/script/dom/storage.rs @ r1
- components/script/dom/storageevent.rs @ r4
- components/script/dom/text.rs @ r1
- components/script/dom/treewalker.rs @ r4
- components/script/dom/uievent.rs @ r4
- components/script/dom/urlsearchparams.rs @ r1
- components/script/dom/userscripts.rs @ r1
- components/script/dom/window.rs @ r1
- components/script/dom/worker.rs @ r1
- components/script/dom/xmlhttprequest.rs @ r4
- components/script/page.rs @ r4
- components/script/parse/html.rs @ r4
- components/script/script_task.rs @ r1
- components/script/webdriver_handlers.rs @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5871)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5871)

**Comment by nox** [comment]
It was bitrotted by #5855.

**Pull request merged**
