### PR TITLE
Automatically clean old nightlies

### LINKED ISSUE #12103: Test packaging during normal builds to prevent bustage?
Inspired by https://github.com/servo/saltfs/pull/386.

Now that we have more than one packaging option and are adding more soon, the likelihood of packaging breaking increases. Because having pre-build nightlies is valuable,
IMO we should make sure the nightly builds succeed by testing the packaging during regular builds. See my comments at #12102 about officially supported packaging formats.
Thoughts?

If we move forward with this, this will be an E-easy bug; just need to add a few lines to our steps.yml.

### PR DESCRIPTION
**Pull request by aneeshusa**
Automatically clean old rustc and cargo nightlies on our builders up to preserve disk space.

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #12103 and help with servo/saltfs#321 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because tested manually

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16487)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
I'm not sure that we want to delete all of the nightlies. Firefox has gotten a *lot* of mileage out of being able to do a "binary bisection" to find when bugs were introduced without having to rebuild the product. 

That said, it might only be useful for the tarballs and not for the installers themselves.

Thoughts, @metajack & @jdm?

**Comment by aneeshusa** [comment]
@larsbergstrom Sorry that I wasn't clear, this deletes `rustc` and `cargo` nightlies, not Servo nightlies! The old compilers take up quite a bit of space, I think ~20GB on the Windows builders.

**Comment by larsbergstrom** [comment]
@aneeshusa Whoops! I should have read the *change* instead of just the PR comment. I've done so now and thanks a ton for this!

@bors-servo r+

**Pull request merged**
