### PR TITLE
Fall down the WebGL rabbit hole and fix some bugs there

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20375)

### CODE REVIEW

**Comment by emilio** [comment]
r=me, thanks!

**Comment by nox** [comment]
@emilio I don't know enough about WebGL to know whether I did something wrong.

**Comment by nox** [comment]
Found out the issue: we didn't implement `gl.getParameter(gl.CURRENT_PROGRAM)`.

**Comment by emilio** [comment]
r=me, but please revert the change to the webgl2 conformance test, or submit it upstream to Khronos

**Review by emilio — APPROVED** [review]

**Pull request merged**
