### PR TITLE
Drop CEF support

### PR DESCRIPTION
**Pull request by paulrouget**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19900)

### CODE REVIEW

**Comment by paulrouget** [comment]
I removed the `cef` directory and the related build commands. Also moved the glutin code with `ports/servo`.

**Comment by paulrouget** [comment]
Got the green light from @larsbergstrom and @pcwalton.

@jdm can you review this PR or assign it to whoever you think is best suited?

**Comment by SimonSapin** [comment]
Codegen in the build script of the `script` crate failed:

```
make[2]: *** [Bindings/HTMLFormControlsCollectionBinding.rs] Segmentation fault: 11
make[1]: *** [CMakeFiles/HTMLFormControlsCollection.dir/all] Error 2
```

I think this is cmake runnning Python? So this segfault might be in a Python process.

**Comment by jdm** [comment]
Yeah, this is an ongoing problem with servo-mac3.

**Comment by SimonSapin** [comment]
I couldn’t reproduce the failure on a macbook.

@bors-servo try- retry

**Comment by qwertychouskie** [comment]
So servo will no longer implement CEF?  That is a bit sad... :(

**Comment by paulrouget** [comment]
> So servo will no longer implement CEF? 

https://groups.google.com/forum/#!topic/mozilla.dev.servo/5MHDnfMya3s

**Comment by paulrouget** [comment]
> Unexpected dynamic symbols in binary

I reintroduced these symbols.

**Comment by SimonSapin** [comment]
@paulrouget `check_dynamic_symbols.py` has a list of allowed symbols, maybe you need to add to it?

**Comment by paulrouget** [comment]
I removed these by mistake: https://github.com/servo/servo/blob/b900664c1aaa57b7d53a46c83b9fe9ef743d161c/ports/glutin/window.rs#L1477

**Comment by est31** [comment]
For the historians and interested, why was this done?

**Comment by paulrouget** [comment]
> For the historians and interested, why was this done?

CEF was not maintained and was on the way of some other features. See
https://groups.google.com/forum/#!topic/mozilla.dev.servo/5MHDnfMya3s

**Pull request merged**
