### PR TITLE
Support keyboard events (and focus) for iframes and servo-shell.

### PR DESCRIPTION
**Pull request by glennw**

### CODE REVIEW

**Comment by metajack** [comment]
Assigned @jdm because @glennw pinged him.

**Comment by jdm** [comment]
Ok, so I'm not super keen on this design of processing events in the iframe element's handle_event and sending it on to the constellation. Could we instead notify the constellation about which pipeline has the active keyboard focus in Document::commit_focus_transaction, and allow the constellation to send key events directly to that script task instead? I believe that will allow us to sidestep many of the less clearly-beneficial changes in these commits.

**Comment by glennw** [comment]
@jdm I'm going to get back to this PR today - so I'll try the method you've suggested above and see how that works out. Thanks for looking into it!

**Comment by glennw** [comment]
Closing in favour of follow up PR.

**Pull request closed without merging**
