### PR TITLE
stylo: Add -moz-element support

### LINKED ISSUE #15443: Implement parsing and serialization of -moz-element function for stylo
This is not part of standard, but it is part of syntax which Gecko needs to support (before we implement the new syntax defined in the spec).

Syntax and description: https://developer.mozilla.org/en-US/docs/Web/CSS/element

(This might be an easy bug. The glue needs some work, though. It would be great if we can call the method directly, otherwise we would need a new binding function from Gecko side. We can probably take this as an experiment for calling method?)

### PR DESCRIPTION
**Pull request by canova**
Implemented -moz-element for background property.
r=upsuper

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15443 and [Bug 1341761](https://bugzilla.mozilla.org/show_bug.cgi?id=1341761)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16319)

### CODE REVIEW

**Comment by canaltinova** [comment]
r? @upsuper
(Probably I should wait for someone with push access to m-c to land this since it's Sunday)

**Comment by upsuper** [comment]
Most stylo people should have arrived Taipei now (and now it is night here), so it is probably not a good time to land code if you are not able to land the Gecko side code...

**Comment by canaltinova** [comment]
Ok, this can wait :)

**Pull request merged**
