### PR TITLE
Update string cache

### PR DESCRIPTION
**Pull request by asajeffrey**
Updated string_cache to 0.2, and updated the dependencies that depend on string_cache.
Removed references to string_cache_plugin.
Import atom! and ns! from string_cache.
Replaced ns!("") by ns!().
Replaced ns!(XML) and co by ns!(xml) and co.
Replaced Atom::from_slice by Atom::from.
Replaced atom.as_slice() by &*atom.

r? @SimonSapin

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8667)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo r-

+S-needs-squash

**Comment by asajeffrey** [comment]
Failing to build on MacOS. The OS-specific files weren't updated, oops. I'll fix this tomorrow.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 66 of 66 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8667#-:-K3zKKJdg6h9fygMav9c:1236647940)*

**Comment by asajeffrey** [comment]
Edited components/gfx/platform/macos/font_template.rs, hopefully that's the only breaking MacOS-specific file.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8667#-:-K3zqY4Y32StCHv9IKFW:1236647940)*

**Pull request merged**
