### PR TITLE
Fix UnderlyingSourceContainer::call_start_algorithm

### PR DESCRIPTION
**Pull request by Taym95**
part of #34064
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Review by jdm — APPROVED** [review]
Looks good!

**Comment by gterzian** [comment]
I'm wondering why the changes on main left the `Call_` into the pull algorithm compiling.

**Comment by gterzian** [comment]
I think the answer is because the pull algorihtm, like the yet to be implemented cancel one, return promises.

**Comment by gterzian** [comment]
I think it's better the pull(and cancel) algorithms return a promise.

**Pull request merged**
