### PR TITLE
Added error checking on XMLHttpRequest::setWithCredentials

### LINKED ISSUE #4665: Throw as necessary when setting XHR.withCredentials.
Blocks #2525.

* Spec: <https://xhr.spec.whatwg.org/#dom-xmlhttprequest-withcredentials>.
* Code: `components/script/dom/xmlhttprequest.rs`.
* Test: `XMLHttpRequest/XMLHttpRequest-withCredentials.html`, `XMLHttpRequest/XMLHttpRequest-withCredentials.worker`.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #4665

### CODE REVIEW

**Comment by jdm** [comment]
Thanks @KiChjang!
r? @Manishearth

**Comment by Manishearth** [comment]
You need to add a `[SetterThrows]` to the `withCredentials` part of the XHR webidl file (`script/dom/webidls/XMLHttpRequest.webidl`)

While you're at it, could you add a comment to the method with [a link to the spec](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-withcredentials)?


Also, you'll need to update the WPT expectations... Run `./mach test-wpt --include=XMLHttpRequest/XMLHttpRequest-withCredentials.html` (same for the other test), and see what the test results are -- everything should pass, and you can just delete the corresponding ini files in `tests/wpt/metadata/XMLHttpRequest/`

**Comment by KiChjang** [comment]
I'm having trouble with using *./mach build*. It's stuck on __git update servo/skia__. I literally left it running overnight but it didn't seem to move one bit.

I am thinking it might be a connectivity issue, but I am not sure. I won't be able to update the WPT expectations when mach fails to build.

**Comment by KiChjang** [comment]
Okay, I've added `[SetterThrows]` to `withCredentials` in `XMLHttpRequest.webidl`, and ran `./mach test-wpt --include=XMLHttpRequest/XMLHttpRequest-withCredentials.html`. The results are below:

```
/XMLHttpRequest/XMLHttpRequest-withCredentials.html
---------------------------------------------------------------
PASS expected FAIL setting on synchronous XHR
PASS expected FAIL setting withCredentials when not in UNSENT, OPENED state
```

which completely puzzles me. If I rewrite the SetWithCredentials method into the following
```rust
fn SetWithCredentials(self, with_credentials: bool) -> ErrorResult {
    self.with_credentials.set(with_credentials);
    Ok(())
}
```

the tests all pass.

**Comment by Ms2ger** [comment]
There's "pass" and "pass". Without your changes, we test that Servo's behaviour doesn't change without us noticing. That means that a test failure we know about means we actually pass the test suite. However, when you fix a test failure we know about, like you did here, you get a message "PASS expected FAIL …"; this means you have to make us no longer expect a failure for this test. The expectation is in `tests/wpt/metadata/XMLHttpRequest/XMLHttpRequest-withCredentials.html.ini`. As you fixed all expected failures listed in that file, you can just remove it.

**Comment by Manishearth** [comment]
Did you also do the same for `XMLHttpRequest/XMLHttpRequest-withCredentials.worker`?

**Comment by KiChjang** [comment]
Yes, sorry, I did not delete the INI file in the commit.

**Comment by Manishearth** [comment]
Alright, do that, squash, and then ping me :)

**Comment by KiChjang** [comment]
Did I squash it correctly?

**Comment by Manishearth** [comment]
The fixup should be merged with the other one. `git rebase -i HEAD~2` and just ensuring `fixup` is next to the `fixup!` commit, followed by a force push should do it.

**Comment by KiChjang** [comment]
Okay, hopefully I got everything right this time.

**Pull request closed without merging**
