### PR TITLE
Pending load guard does not assert if thread is panicking

### PR DESCRIPTION
**Pull request by pr0hin**
Fixes issue #6148 

@jdm After mulling over this for a little while, i'm not sure if this approach is correct. Any comments?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6162)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/net_traits/lib.rs @ r4

---

<sup>**[components/net_traits/lib.rs, line 155 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6162#-Jpx7XiklShmQbeHsqhz)** ([raw file](https://github.com/servo/servo/blob/d4cb3cc98f33327e75e41ad81f39ff88d4f43340/components/net_traits/lib.rs#L155)):</sup>
Let's instead use
```rust
if !thread::panicking() {
    assert!(self.loaded);
}
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6162)

**Comment by r0e** [comment]
Thanks @jdm. Makes sense.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/net_traits/lib.rs @ r5

---

<sup>**[components/net_traits/lib.rs, line 152 \[r5\]](https://reviewable.io:443/reviews/servo/servo/6162#-JpxLBzxy2SH5jNEp3Z4)** ([raw file](https://github.com/servo/servo/blob/0d5f87c8e1a8dc6b373844cc05c2249cea2b2a2e/components/net_traits/lib.rs#L152)):</sup>
nit: indent this by another four spaces.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6162)

**Comment by jdm** [comment]
Looks great! Could you [squash these](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) together now?

-S-awaiting-review +S-needs-squash 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/net_traits/lib.rs @ r6

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6162)

**Pull request merged**
