### PR TITLE
style: Remove a few uses of ComputedValueAsSpecified.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18429)

### CODE REVIEW

**Comment by emilio** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=80cd30910c4201c469009082ad75a1f6b44214a3

**Comment by emilio** [comment]
err, the try run above was unrelated, here it is the real one: https://treeherder.mozilla.org/#/jobs?repo=try&revision=068a0bf0a25280301bc6241b43e146ba0d58e9e2

**Comment by nox** [comment]
@bors-servo r+

Neat.

**Pull request merged**
