### PR TITLE
Disable reflection-embedded.html.

### PR DESCRIPTION
**Pull request by Ms2ger**
CC #11100

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14293)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo retry
* #14267

**Comment by KiChjang** [comment]
@bors-servo retry
 * #13776

**Comment by heycam** [comment]
@bors-servo retry

* #13731

**Comment by KiChjang** [comment]
@bors-servo retry
* #10549

**Pull request merged**
