### PR TITLE
Remove unused compositing dependency from bluetooth crate

### LINKED ISSUE #21176: Remove compositing dependency from bluetooth crate
It's declared in components/bluetooth/Cargo.toml, but not used in lib.rs. This means it can be removed.

### PR DESCRIPTION
**Pull request by georgeroman**
Closes #21176 

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21346)

### CODE REVIEW

**Comment by paulrouget** [comment]
Looks good to me. Thank you.

@bors-servo r+

**Comment by paulrouget** [comment]
Failure is unrelated: https://github.com/servo/servo/issues/21349

**Comment by paulrouget** [comment]
@bors-servo retry

- #21349

**Comment by jdm** [comment]
@bors-servo retry
* cleaned up builder

**Comment by jdm** [comment]
@bors-servo retry
* #20734

**Comment by paulrouget** [comment]
@bors-servo retry

#20734

**Comment by paulrouget** [comment]
@georgeroman thank you :)

**Pull request merged**
