### PR TITLE
Using helper color function (less verbose and clearer to understand).

### PR DESCRIPTION
**Pull request by Adenilson**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5787)

### CODE REVIEW

**Comment by Adenilson** [comment]
OOps, didn't noticed the alpha value. Fixing now.

**Comment by Adenilson** [comment]
Should be fine now.

**Comment by SimonSapin** [comment]
@glennw Is there a reason to use transparent white here rather than transparent black? Is this pre-multiplied alpha or not?

**Comment by Adenilson** [comment]
Let me know if I can squash it.

**Comment by SimonSapin** [comment]
I think it’s good to have in the commit history how we got there.

**Pull request merged**
