### PR TITLE
Moved WorkerId type to devtools_traits

### LINKED ISSUE #8846: Move WorkerId type to devtools_traits
It's defined in `components/msg/constellation_msg.rs` but only used by `components/script/` and `components/devtools`. We can do better!

Code: `components/msg/constellation_msg.rs`, `components/devtools_traits/lib.rs`

### PR DESCRIPTION
**Pull request by fstr**
Fixes #8846.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8862)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thanks for the PR! Unfortunately our "tidy" check caught one small mistake; see below. Let me know when you've made the change?

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/dom/window.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8862#-K4tnCIZ0MEXU6C_Cypw:-K4tnCIZ0MEXU6C_Cypx:861087023) ([raw file](https://github.com/servo/servo/blob/6bf8d87071de2d4489b51c7fe11b05cb157231d2/components/script/dom/window.rs#L7)):*
Could you merge those two `use` blocks? Right now, this fails our "tidy" check? Please confirm that `./mach test-tidy` reports no errors after fixing that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8862#-:-K4tnoi1bZThhBw4P3Ex:775558233)*

**Comment by fstr** [comment]
*[components/script/dom/window.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8862#-K4tnCIZ0MEXU6C_Cypw:-K4xbJdpf_yYnvE3mY9s:1848274159) ([raw file](https://github.com/servo/servo/blob/6bf8d87071de2d4489b51c7fe11b05cb157231d2/components/script/dom/window.rs#L7)):*
I tried to find out a pattern for the use statements. Sometimes there's a second use statement for more than 3 imports.

Sometimes, they are all chained in one line.

Interestingly, what works for the tidy check is
```
use devtools_traits::{ScriptToDevtoolsControlMsg, TimelineMarker, TimelineMarkerType};
use devtools_traits::{WorkerId};

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8862)*
<!-- Sent from Reviewable.io -->

**Comment by Ms2ger** [comment]
Thank you. Can you please squash the two commits now?

-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8862#-:-K4xmsYuo_Rhlp0U1xca:2103435128)*

**Comment by fstr** [comment]
Done!

**Comment by Ms2ger** [comment]
Thanks again, your help is much appreciated.

@bors-servo r+

**Pull request merged**
