### PR TITLE
generate JIT argument type information for methods

### PR DESCRIPTION
**Pull request by froydnj**
This enhances `CodegenRust.py` to output `JSTypedMethodJitInfo` structures where appropriate.  This brings a notable speedup to tests like Dromaeo's `dom-attr/getAttribute`, which improves by several orders of magnitude with these patches applied.

If there are tricks for addressing the XXX comments, I would appreciate hearing them.

I think this addresses all of #6904.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8040)

### CODE REVIEW

**Comment by frewsxcv** [comment]
In case you missed there are merge conflicts.

**Comment by Ms2ger** [comment]
Maybe `ArgType` should use bitflags?

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 
Ideally we could make ArgType use bitflags (although I don't know if those would work in const values right now), but that would require hand-modifying the rust-mozjs bindings right now. I'd rather use our knowledge of the types involved to make this work correctly.


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 3097 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8040#-K1a1OviaGZWHeluixsJ)** ([raw file](https://github.com/servo/servo/blob/216264c55d7d1315c01a96d5e7b0ec78ee35cdcd/components/script/dom/bindings/codegen/CodegenRust.py#L3097)):</sup>
If we make this i32 instead of ArgType, we can use | willy-nilly if we cast our ArgType values to i32.


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 3104 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8040#-K1a1WP3NXoUs-weucE2)** ([raw file](https://github.com/servo/servo/blob/216264c55d7d1315c01a96d5e7b0ec78ee35cdcd/components/script/dom/bindings/codegen/CodegenRust.py#L3104)):</sup>
Then this becomes `&${argTypes} as *const _ as *const ArgType`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8040)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8040)

**Pull request merged**
