### PR TITLE
(Do not merge) Enable incremental GC

### LINKED ISSUE #7621: Enable incremental GC.
@michaelwu left

``` rust
            // Pre barriers aren't working correctly at the moment
            DisableIncrementalGC(runtime.rt());
```

in `ScriptTask::new_rt_and_cx()` with no further explanation.

### PR DESCRIPTION
**Pull request by nox**
Fixes #7621.

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11101)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo retry
* The annoying git

**Comment by nox** [comment]
r? @jdm 

Are you satisfied with just the CI tests passing?

**Comment by jdm** [comment]
Nope! We're definitely going to need to run the tests with gczeal enabled before I'm comfortable enabling this.

**Comment by nox** [comment]
@jdm I have added GC zeal support, now we "only" need CI support. I guess I should split the GC zeal stuff in its own PR to first add some buildbots that use it?

Cc @larsbergstrom

**Comment by nox** [comment]
@jdm Would all the tests in `/dom/` be enough, or we should run even more of them?

**Comment by jdm** [comment]
I think we should run all of them.

**Comment by frewsxcv** [comment]
What is this blocked on?

**Comment by jdm** [comment]
This was blocked on getting se builders running tests with full gczeal enabled.

**Comment by notriddle** [comment]
"Was" blocked? So is it blocked now?

**Comment by jdm** [comment]
It continues to be blocked because our builder that supposedly had gczeal enabled did not actually have gczeal enabled.

**Comment by jdm** [comment]
Given the number of things block this effort (https://github.com/servo/servo/issues/7621#issuecomment-275741192), I'm going to close this.

**Pull request closed without merging**
