### PR TITLE
Update WR version, add latest shaders to resources.

### PR DESCRIPTION
**Pull request by samuknet**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because webrender update

Signed-off-by: Sam swood@mozilla.com

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13256)

### CODE REVIEW

**Comment by samuknet** [comment]
@glennw

**Comment by jdm** [comment]
@bors-servo: retry
* #12654

**Comment by jdm** [comment]
Superseded by #13273.

**Pull request closed without merging**
