### PR TITLE
Add lots of derived Debug impls

### PR DESCRIPTION
**Pull request by asajeffrey**
Add a bunch of derived `Debug` impls. After this, pretty much anything that implements `Deserializable` also implements `Debug`. The exception is `webrender_api::RenderApiSender`, which would need a webrender PR.
 
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because it's just debugging

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22028)

### CODE REVIEW

**Review by emilio — APPROVED** [review]
Sure, looks fine code-wise, but mind explaining why in the commit message?

**Comment by asajeffrey** [comment]
Changed the commit msg, and hopefully got it to compile under Windows. @bors-servo r=emilio

**Comment by asajeffrey** [comment]
Hopefully got it to compile under macos. @bors-servo r=emilio

**Comment by jdm** [comment]
I will retry this, but I'm going to wait until the remaining jobs finish.

**Pull request merged**
