### PR TITLE
ci: Use a servo.org email address for the servo-wpt-sync GitHub bot

### PR DESCRIPTION
**Pull request by mrobinson**
This is the new address of the WPT sync bot.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because this just changes CI behavior.

### CODE REVIEW

**Comment by sagudev** [comment]
I think this bot is also used for upstream sync, so WPT might need to trust it (like it does current @servo-wpt-sync account).

Although I am not sure exactly why do we need to change the bot persona, as current one works, is trusted and has history (also has nicer icon). If it is about email, we should be able to change it without losing any history information.

**Comment by mrobinson** [comment]
Maybe it's good enough to just change the bots email to something like wpt-sync@servo.org then?

**Comment by sagudev** [comment]
> Maybe it's good enough to just change the bots email to something like [wpt-sync@servo.org](mailto:wpt-sync@servo.org) then?

That would be ideal IMO.

**Comment by mukilan** [comment]
Do need a new `wpt-sync@servo.org` address or can we just use `ghbot+wpt-sync@servo.org`?

**Comment by mrobinson** [comment]
Okay. This is ready for a review.

**Comment by sagudev** [comment]
> Okay. This is ready for a review.

Just to be sure, this email is also set in bot's profile, right?

**Comment by mrobinson** [comment]
> Just to be sure, this email is also set in bot's profile, right?

Yes, as of a few minutes ago, it should be added to the bot's GitHub account

**Review by sagudev — APPROVED** [review]

**Pull request merged**
