### PR TITLE
Update style attributes on CSSStyleDeclaration changes

### LINKED ISSUE #9307: html style attribute not updated
```html
<div style="width:10px">
</div>
<script>
  var div = document.querySelector('div');
  div.style.backgroundColor = "red";
  console.log(div.getAttribute("style"));
</script>
```

This prints `width:10px` instead of `width: 10px; background-color: red;`.

### PR DESCRIPTION
**Pull request by SimonSapin**
Rebase of #9410. Fixes #9410, fixes #9307.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11377)

### CODE REVIEW

**Comment by paulrouget** [comment]
Thank you @craftytrickster

**Comment by frivoal** [comment]
Just a quick heads up: If you're looking at dynamic changes to the style attribute, depending on what else you have implemented already, this may be a good time to have a look at https://drafts.csswg.org/css-ui-3/#resize, since it works by modifying the style attribute.

**Pull request merged**
