### PR TITLE
style: Refactor font-feature-settings and font-variation-settings.

### PR DESCRIPTION
**Pull request by emilio**
This fixes all known issues with serialization and parsing of these two
properties, and in particular calc handling and such:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1434692
  https://bugzilla.mozilla.org/show_bug.cgi?id=1434724

Also does a fair amount of cleanup and all that, which was needed, this code
was a mess.

There are further cleanups that can be done, like renaming the
font-variation-settings animation stuff.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19918)

### CODE REVIEW

**Comment by emilio** [comment]
(Don't merge it directly, since needs to change some expected serialization tests in Gecko)

**Review by nox — APPROVED** [review]
r=me with green geckotry.

**Comment by emilio** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=25b3c2998fdee75ceb6aafe6f0bb2ac911d68f19

Looks green.

@bors-servo r=nox

**Comment by emilio** [comment]
> thread 'main' panicked at 'Fail to copy generated files to out dir: Error { repr: Os { code: 28, message: "No space left on device" } }', /checkout/src/libcore/result.rs:906:4

Great

**Comment by emilio** [comment]
@bors-servo retry

 * I tried to make some space on servo-linux4...

**Comment by emilio** [comment]
@bors-servo r=nox

 * Removed `boxed=True`.

**Pull request merged**
