### PR TITLE
Update WR (transaction API change)

### PR DESCRIPTION
**Pull request by gw3583**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20892)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
  ▶ FAIL [expected PASS] /css/compositing/mix-blend-mode/mix-blend-mode-parent-with-text.html
  └   → /css/compositing/mix-blend-mode/mix-blend-mode-parent-with-text.html 51aebb7c5a53f7412efc3d826d3b7ace57023e7d
/css/compositing/mix-blend-mode/reference/mix-blend-mode-parent-with-text-ref.html c2a3ce8ea5598b64d9ac0159e312b0e15f7d5ae6
Testing 51aebb7c5a53f7412efc3d826d3b7ace57023e7d == c2a3ce8ea5598b64d9ac0159e312b0e15f7d5ae6

  ▶ FAIL [expected PASS] /css/compositing/mix-blend-mode/mix-blend-mode-paragraph.html
  └   → /css/compositing/mix-blend-mode/mix-blend-mode-paragraph.html f6cb58abcc1d2274b393d5d49c274f70ea9bfc8b
/css/compositing/mix-blend-mode/reference/mix-blend-mode-paragraph-ref.html 737b4ae888e9d0b5d4a98f8e1bcb0cb7b7e8002b
Testing f6cb58abcc1d2274b393d5d49c274f70ea9bfc8b == 737b4ae888e9d0b5d4a98f8e1bcb0cb7b7e8002b
  ▶ Unexpected subtest result in /_mozilla/mozilla/hit_test_pos_fixed.html:
  │ FAIL [expected PASS] Hit-test of an element with position: fixed should discard scroll offset
  │   → assert_true: should be able to hit the fixed-positioned element expected true got false
  │ 
  │ window.onload<@http://web-platform.test:8000/_mozilla/mozilla/hit_test_pos_fixed.html:37:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1562:20
```

**Comment by gw3583** [comment]
Updated text expectations - in these two tests, the second line of text is offset by 1 vertical pixel. I verified that Servo is providing different positions for the glyphs between the two tests. This is being exposed by some WR fixes for text snapping.

@bors-servo try

**Comment by mrobinson** [comment]
@gw3583 I'm not certain, but I wouldn't be surprised if https://github.com/servo/servo/pull/20767 needs to land first.

**Comment by jdm** [comment]
That failure is #13480.

**Comment by jdm** [comment]
However:
```
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-011.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-011.xht", "line": 18159, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-116.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht 2d65cb34f07b034c8aef0aa011932da6acf629bd\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == 2d65cb34f07b034c8aef0aa011932da6acf629bd\n/css/CSS2/tables/table-anonymous-objects-116.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-116.xht", "line": 18190, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-019.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-019.xht", "line": 18319, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-175.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-175.xht", "line": 18645, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-197.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-197.xht", "line": 18762, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-174.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-174.xht", "line": 18775, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-203.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-203.xht", "line": 18842, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-122.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht 2d65cb34f07b034c8aef0aa011932da6acf629bd\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == 2d65cb34f07b034c8aef0aa011932da6acf629bd\n/css/CSS2/tables/table-anonymous-objects-122.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-122.xht", "line": 18894, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-199.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-199.xht", "line": 19073, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-010.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-010.xht", "line": 19509, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-018.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-018.xht", "line": 19583, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-198.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-198.xht", "line": 19606, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-204.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-204.xht", "line": 19687, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-115.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht 2d65cb34f07b034c8aef0aa011932da6acf629bd\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == 2d65cb34f07b034c8aef0aa011932da6acf629bd\n/css/CSS2/tables/table-anonymous-objects-115.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-115.xht", "line": 19748, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-202.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-202.xht", "line": 20618, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-003.html f49b5437f0a8b9f1066539c9fc43d5e573e83f6d\n/css/css-transforms/transform-input-003-ref.html 27e63562d4278489585d1f024e474b97b8dee410\nTesting f49b5437f0a8b9f1066539c9fc43d5e573e83f6d == 27e63562d4278489585d1f024e474b97b8dee410", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-003.html", "line": 24740, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-010.html a1fbd247c7ac9ec7dc81cc054a1f53765e52a492\n/css/css-transforms/transform-input-010-ref.html 08f2b5dc98401877a3c93783a52633763220e38a\nTesting a1fbd247c7ac9ec7dc81cc054a1f53765e52a492 == 08f2b5dc98401877a3c93783a52633763220e38a", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-010.html", "line": 24915, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-008.html f996f9b446a1be3202ccc753bcbb0e757d11e4a2\n/css/css-transforms/transform-input-008-ref.html 8fd11a6047a3fecfa9393cd24796988dc3db2a19\nTesting f996f9b446a1be3202ccc753bcbb0e757d11e4a2 == 8fd11a6047a3fecfa9393cd24796988dc3db2a19", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-008.html", "line": 24994, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-013.html 9a5d3478e9f8736fbe308f86e066cb446dcf9ab8\n/css/css-transforms/transform-input-013-ref.html 8ced258b4fd249affad6987761120c92c08b5355\nTesting 9a5d3478e9f8736fbe308f86e066cb446dcf9ab8 == 8ced258b4fd249affad6987761120c92c08b5355", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-013.html", "line": 25237, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-017.html d316a1bd3569db9bc3678627e8e4829dfd02574b\n/css/css-transforms/transform-input-017-ref.html 2894046530d7a26e3d4736dfc8a302cfed061d38\nTesting d316a1bd3569db9bc3678627e8e4829dfd02574b == 2894046530d7a26e3d4736dfc8a302cfed061d38", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-017.html", "line": 26027, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-005.html b18ec894fb7fb766a6dffae6519ef68118bc1317\n/css/css-transforms/transform-input-005-ref.html 954b148e4ca8094632d01e42e68f005d9d8c3550\nTesting b18ec894fb7fb766a6dffae6519ef68118bc1317 == 954b148e4ca8094632d01e42e68f005d9d8c3550", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-005.html", "line": 26525, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-002.html 8fbca800bcdf65e772eb71d5c7b73de99284ce63\n/css/css-transforms/transform-input-002-ref.html e961f4f4fa5228c648ecc86b59bd21f5558577ca\nTesting 8fbca800bcdf65e772eb71d5c7b73de99284ce63 == e961f4f4fa5228c648ecc86b59bd21f5558577ca", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-002.html", "line": 26886, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-001.html 90c46d17ac402e5e897b29390d7fcdfc19588f64\n/css/css-transforms/transform-input-001-ref.html 64ec3e128a31160e9bf915bb1bbaca3b61bdcecb\nTesting 90c46d17ac402e5e897b29390d7fcdfc19588f64 == 64ec3e128a31160e9bf915bb1bbaca3b61bdcecb", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-001.html", "line": 27577, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-014.html 515ea9aaaefefbf63a04303ab189a48ae3f5b0cd\n/css/css-transforms/transform-input-014-ref.html 206ad6653bf2897056534e74f735f10ccceec902\nTesting 515ea9aaaefefbf63a04303ab189a48ae3f5b0cd == 206ad6653bf2897056534e74f735f10ccceec902", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-014.html", "line": 27630, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-012.html 8fb4dee5b217134984f2d3dac4b767104f2ec035\n/css/css-transforms/transform-input-012-ref.html b125e1c41187f9a9091462475b072d2edd4519ab\nTesting 8fb4dee5b217134984f2d3dac4b767104f2ec035 == b125e1c41187f9a9091462475b072d2edd4519ab", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-012.html", "line": 27796, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-019.html 75c0028fa3ad3e52d67dc8124eb0a62d42146344\n/css/css-transforms/transform-input-019-ref.html 1f58e3ea27d5ffa48438154fb7b6411571e3fefa\nTesting 75c0028fa3ad3e52d67dc8124eb0a62d42146344 == 1f58e3ea27d5ffa48438154fb7b6411571e3fefa", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-019.html", "line": 27845, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-009.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-009.xht", "line": 39975, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-012.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-012.xht", "line": 40027, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-121.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_3x3_monospace_table-ref.xht 2d65cb34f07b034c8aef0aa011932da6acf629bd\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == 2d65cb34f07b034c8aef0aa011932da6acf629bd\n/css/CSS2/tables/table-anonymous-objects-121.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-121.xht", "line": 41120, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-176.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-176.xht", "line": 41166, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-017.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-017.xht", "line": 41219, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-173.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-173.xht", "line": 41608, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-201.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-201.xht", "line": 41699, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-020.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-020.xht", "line": 41807, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/tables/table-anonymous-objects-200.xht 9ec2d15589516c32a6227dc51aae95e06b423890\n/css/CSS2/tables/reference/no_red_antialiasing_a_bc_d-ref.xht c96c4fb330b417d0deec4d16120be8dd92f345dc\nTesting 9ec2d15589516c32a6227dc51aae95e06b423890 == c96c4fb330b417d0deec4d16120be8dd92f345dc", "stack": null, "subtest": null, "test": "/css/CSS2/tables/table-anonymous-objects-200.xht", "line": 42217, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-004.html 445ae13f465097562de4fa1689d5be8d6dd14eeb\n/css/css-transforms/transform-input-004-ref.html c675761a5d069fe4b2524856a9101ce85d13a82a\nTesting 445ae13f465097562de4fa1689d5be8d6dd14eeb == c675761a5d069fe4b2524856a9101ce85d13a82a", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-004.html", "line": 43428, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-007.html fac36ee9474fc52294c25640d2714ea3b6b3ccb1\n/css/css-transforms/transform-input-007-ref.html 26024f2ee723cb17f7111c2f87e941c7f9c51bba\nTesting fac36ee9474fc52294c25640d2714ea3b6b3ccb1 == 26024f2ee723cb17f7111c2f87e941c7f9c51bba", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-007.html", "line": 44555, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-009.html d064a447f975057284c4242b3b947da3a0239222\n/css/css-transforms/transform-input-009-ref.html a6d6e4c1c513e225349e2aeef3a76284d7537ebb\nTesting d064a447f975057284c4242b3b947da3a0239222 == a6d6e4c1c513e225349e2aeef3a76284d7537ebb", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-009.html", "line": 44736, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-016.html bedd7eb648fd517b08ce19d7303786b0eace2bd7\n/css/css-transforms/transform-input-016-ref.html 9a2c04e70b3a50d760a302ef257b6318cf134aa4\nTesting bedd7eb648fd517b08ce19d7303786b0eace2bd7 == 9a2c04e70b3a50d760a302ef257b6318cf134aa4", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-016.html", "line": 45502, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-006.html d2ccb8d84ac399f2def6479ce46328671032eb45\n/css/css-transforms/transform-input-006-ref.html 077c45dc000aca1f4a3617e32c89cdf629b5c371\nTesting d2ccb8d84ac399f2def6479ce46328671032eb45 == 077c45dc000aca1f4a3617e32c89cdf629b5c371", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-006.html", "line": 45558, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-transforms/transform-input-015.html 1c1d93902c3710d1c26b7de5f6043865583c7550\n/css/css-transforms/transform-input-015-ref.html 0c48d0099d430e03f13bf9c20f9d5ed76be721a2\nTesting 1c1d93902c3710d1c26b7de5f6043865583c7550 == 0c48d0099d430e03f13bf9c20f9d5ed76be721a2", "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-015.html", "line": 45646, "action": "test_result", "expected": "PASS"}
```

**Comment by gw3583** [comment]
Ugh, these all seem to be suffering the same problem.

Servo appears to be providing slightly different coordinates for the text runs between the test and reference.

This is resulting in them being snapped differently, which is causing the reftest failures. I'll try to find out what's causing the different snapping behavior, and see if we can either (a) fix it in Servo or (b) handle this in WR with a workaround.

**Comment by gw3583** [comment]
(Or, ideally, fix it in WR if it turns out to be a snapping bug!)

**Comment by gw3583** [comment]
My current hypothesis is that Gecko snaps subpixel offsets in transform matrices before sending to WR.

If this *is* happening, that would explain why Servo is rendering this differently than Gecko does (I verified that Gecko + WR produces a pixel-perfect comparison between these test cases).

Still investigating...

**Comment by gw3583** [comment]
Confirmed that the transform in this test case has a fractional component in Servo, but is a whole number in Gecko. Now to work out where the difference is, and what the correct fix / workaround is.

**Comment by gw3583** [comment]
We have identified what we think is a way to handle this in WR. @lsalzman is working on a patch for WR, which should unblock this update from landing in Servo.

**Comment by SimonSapin** [comment]
With https://github.com/servo/servo/pull/21058 Servo now requires serde 1.0.60+, so this likely won’t be able to land as-is, sorry. This should be fixed by either updating again to WebRender master to include https://github.com/servo/webrender/pull/2819 or, if that’s not practical, by merging commit 6931a25295d17d897a9f77798392bdde66132154 (which is based earlier).

Feel free to ping me if I can help with this.

**Comment by gw3583** [comment]
Rebased, updated to include latest serde + text snapping change. Let's see what else breaks :)

@bors-servo try

**Comment by gw3583** [comment]
Looks like the mix-blend-mode + transform test is failing, which might be a bug in the API changes I've made. Let's see what other tests also break.

@bors-servo try

**Comment by gw3583** [comment]
OK, so it looks like the change we made does resolve some of the tests. But after much discussion with @lsalzman we think that the remaining issue now lies in Servo. I'm going to prototype a few changes in Servo to see if we can make it work as WR now expects (which is a requirement to avoid some glyph animation issues that can otherwise be seen with the old technique).

**Comment by gw3583** [comment]
@mrobinson In addition to the text related failures I'm looking at, there are some transform related failures. Some of these are:

```
css-transform-3d-transform-style.html
css-transforms/transform-abspos-006.html
transform-abspos-004.html
transform-abspos-001.html
transform3d-image-scale-001.html
```

I'm not sure yet if these are related to a bug in WR itself, or some mistakes in the reference-frame API changes in this patch. Have you got cycles to take a look at these while I work on the text failures?

**Comment by gw3583** [comment]
Current hypothesis: Gecko does some snapping of either the text run font size / line height, or perhaps the stacking context offsets. I'll compare the display list outputs between Gecko and Servo for some of these test cases today to try and determine where the difference is.

**Comment by mrobinson** [comment]
@gw3583 If you still want me to look at this, I'm happy to do it.

**Comment by gw3583** [comment]
@mrobinson If you can look at the transform issues above, that'd be great - I'm looking at the text snapping failures, which are a separate issue.

**Comment by jdm** [comment]
I'm ok with that. Please file an issue tracking it and add the bug to each of the ini files that is added as part of this PR.

**Comment by paulrouget** [comment]
FYI, and I 'm not sure if it's a known issue, but with this PR, the viewport origin is ignored. For example, the snippet in #20847 would render a red square at 0x0 and not at 50x50.

**Comment by mrobinson** [comment]
Pretty sure that I've fixed the reference frame issues over at #21085. Feel free to steel those commits and integrate them here.

**Comment by gw3583** [comment]
@mrobinson Thanks! I'll pull those commits in today and update the other test expectations. :+1:

**Comment by gw3583** [comment]
OK, I believe this is ready for review now. :tada:

I have added several new test failures, as discussed above with annotations to bug #21092.

The API changes are mostly straightforward, I think.

r? @jdm or @mbrubeck

**Pull request merged**
