### PR TITLE
Disable cross origin check for mozbrowser-enabled top level pipelines

### PR DESCRIPTION
**Pull request by paulrouget**
Closes https://github.com/servo/servo/issues/9582

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10068)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Remove `components/script/parser.out`.

**Comment by paulrouget** [comment]
> Remove components/script/parser.out.

Done.

**Comment by paulrouget** [comment]
Anything in particular that might prevent this to land?

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/xmlhttprequest.rs, line 878 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10068#-KDdpklDYCszI267JCjH:-KDdpklDYCszI267JCjI:-1114871128) ([raw file](https://github.com/servo/servo/blob/fd6878cfdb8c27bf06ef758d488f66f443579388/components/script/dom/xmlhttprequest.rs#L878)):*
This breaks XHR in workers, since this method panics for non-windows.

---

*[tests/wpt/mozilla/tests/mozilla/mozbrowser/crossorigin_xhr.html, line 14 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10068#-KDdq820v6_TC4CIPr5E:-KDdq8213mznDM19Ue_W:-1254994831) ([raw file](https://github.com/servo/servo/blob/fd6878cfdb8c27bf06ef758d488f66f443579388/tests/wpt/mozilla/tests/mozilla/mozbrowser/crossorigin_xhr.html#L14)):*
this.unreached_func("Cross origin xhr() should not have failed");

---

*[tests/wpt/mozilla/tests/mozilla/mozbrowser/crossorigin_xhr.html, line 19 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10068#-KDdqD76Y-BfPQx1Ki3v:-KDdqD76Y-BfPQx1Ki3w:-322039884) ([raw file](https://github.com/servo/servo/blob/fd6878cfdb8c27bf06ef758d488f66f443579388/tests/wpt/mozilla/tests/mozilla/mozbrowser/crossorigin_xhr.html#L19)):*
this.step_func_done and remove the `t.done()`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10068#-:-KDdqTQuWQYQUDSa_gBe:1458266033)*

**Comment by paulrouget** [comment]
Addressed comments. For workers, I don't think there's an easy way to know if it's part of the top level window. We don't need it now though.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/xmlhttprequest.rs, line 878 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10068#-KDvCq6bficleX8eMLzw:-KDvCq6cj4Xr0W_e-GZQ:786038626) ([raw file](https://github.com/servo/servo/blob/41aa98e8e51921045fe605e5e765e3b93660e6e1/components/script/dom/xmlhttprequest.rs#L878)):*
```rust
if let GlobalRoot::Window(win) = self.global() {
    let is_root_pipeline = win.parent_info.is_none();
    ...
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10068#-:-KDvD4en9MbQVu651tu_:1458266033)*

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10068#-:-KDx_ocC9nEvU9QFSXRr:-317921516)*

**Pull request merged**
