### PR TITLE
gfx: Use a pattern instead of tiling images manually.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @SimonSapin

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6487)

### CODE REVIEW

**Comment by pcwalton** [comment]
cc @nickdesaulniers

**Comment by nickdesaulniers** [comment]
I tried applying this patch, building, and running my site.  I can scroll a little down the page, and the page stops rendering everything below the first few paragraphs.

```
➜  servo git:(background-tiling) ✗ ./mach run http://nickdesaulniers.github.io -Z show-parallel-layout
...
thread 'LayoutWorker worker 5/6' panicked at 'Link to containing block not established; perhaps you forgot to call `set_absolute_descendants`?', /Users/Nicholas/Downloads/servo-osx/servo/components/layout/flow.rs:1393
stack backtrace:
   1:        0x1029827e5 - sys::backtrace::write::hab580a18e6ade3dauns
   2:        0x102985e05 - panicking::on_panic::h1844ce5c03c54289BFw
   3:        0x102973922 - rt::unwind::begin_unwind_inner::hbe10c68a88d62d39Nnw
   4:        0x10083ebfc - rt::unwind::begin_unwind::h10098823487077890900
   5:        0x100927d03 - flow::ContainingBlockLink::generated_containing_block_size::h1a5ba2c8a7d5f91f7Gi
   6:        0x10092799b - block::BlockFlow::containing_block_size::h97636cafe1bc91fbHfb
   7:        0x100951e9c - table_row::TableRowFlow.Flow::assign_inline_sizes::hd9086e5a721ee500LPt
   8:        0x100b4be80 - traversal::AssignISizes<'a>.PreorderFlowTraversal::process::h6192444e4c0168e46Uv
   9:        0x100b4af44 - parallel::AssignISizes<'a>.ParallelPreorderFlowTraversal::run_parallel::had59bbd2b3292c4397q
  10:        0x100b513f5 - parallel::assign_inline_sizes::ha687bdbbd05502cffbr
  11:        0x100ac895b - workqueue::WorkerThread<QueueData, WorkData>::start::h13553608466671330882
  12:        0x100ac8044 - workqueue::WorkQueue<QueueData, WorkData>::new::closure.43248
  13:        0x100ac7eaf - task::spawn_named::closure.43242
  14:        0x100ac7dbe - boxed::F.FnBox<A>::call_box::h13516651952116030504
  15:        0x100a9d624 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h9166918206100653573
  16:        0x100a9d092 - thread::Builder::spawn_inner::closure.42472
  17:        0x100a9d00e - rt::unwind::try::try_fn::__rust_abi::h6837061623529591365
  18:        0x100a9cfa9 - rt::unwind::try::try_fn::h6837061623529591365
  19:        0x102987818 - rust_try_inner
  20:        0x102987805 - rust_try
  21:        0x102980d85 - rt::unwind::try::inner_try::h952058f93415498bGjw
  22:        0x100a9cf18 - rt::unwind::try::h15725383742404244903
  23:        0x100a9cd61 - thread::Builder::spawn_inner::closure.42424
  24:        0x100a9d93d - boxed::F.FnBox<A>::call_box::h9288818815509458392
  25:        0x1029847cd - sys::thread::Thread::new::thread_start::hce4e8f4a53df8c160Hv
  26:     0x7fff8e539267 - _pthread_body
  27:     0x7fff8e5391e4 - _pthread_start
thread 'LayoutWorker worker 5/6' panicked at 'Link to containing block not established; perhaps you forgot to call `set_absolute_descendants`?', /Users/Nicholas/Downloads/servo-osx/servo/components/layout/flow.rs:1393
stack backtrace:
   1:        0x1029827e5 - sys::backtrace::write::hab580a18e6ade3dauns
   2:        0x102985e05 - panicking::on_panic::h1844ce5c03c54289BFw
   3:        0x102973922 - rt::unwind::begin_unwind_inner::hbe10c68a88d62d39Nnw
   4:        0x10083ebfc - rt::unwind::begin_unwind::h10098823487077890900
   5:        0x100927d03 - flow::ContainingBlockLink::generated_containing_block_size::h1a5ba2c8a7d5f91f7Gi
   6:        0x10092799b - block::BlockFlow::containing_block_size::h97636cafe1bc91fbHfb
   7:        0x100951e9c - table_row::TableRowFlow.Flow::assign_inline_sizes::hd9086e5a721ee500LPt
   8:        0x100b4be80 - traversal::AssignISizes<'a>.PreorderFlowTraversal::process::h6192444e4c0168e46Uv
   9:        0x100b4af44 - parallel::AssignISizes<'a>.ParallelPreorderFlowTraversal::run_parallel::had59bbd2b3292c4397q
  10:        0x100b513f5 - parallel::assign_inline_sizes::ha687bdbbd05502cffbr
  11:        0x100ac895b - workqueue::WorkerThread<QueueData, WorkData>::start::h13553608466671330882
  12:        0x100ac8044 - workqueue::WorkQueue<QueueData, WorkData>::new::closure.43248
  13:        0x100ac7eaf - task::spawn_named::closure.43242
  14:        0x100ac7dbe - boxed::F.FnBox<A>::call_box::h13516651952116030504
  15:        0x100a9d624 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h9166918206100653573
  16:        0x100a9d092 - thread::Builder::spawn_inner::closure.42472
  17:        0x100a9d00e - rt::unwind::try::try_fn::__rust_abi::h6837061623529591365
  18:        0x100a9cfa9 - rt::unwind::try::try_fn::h6837061623529591365
  19:        0x102987818 - rust_try_inner
  20:        0x102987805 - rust_try
  21:        0x102980d85 - rt::unwind::try::inner_try::h952058f93415498bGjw
  22:        0x100a9cf18 - rt::unwind::try::h15725383742404244903
  23:        0x100a9cd61 - thread::Builder::spawn_inner::closure.42424
  24:        0x100a9d93d - boxed::F.FnBox<A>::call_box::h9288818815509458392
  25:        0x1029847cd - sys::thread::Thread::new::thread_start::hce4e8f4a53df8c160Hv
  26:     0x7fff8e539267 - _pthread_body
  27:     0x7fff8e5391e4 - _pthread_start
libpng warning: IDAT: Too much image data
ERROR:script::dom::htmlscriptelement: error loading script Invalid Header provided
```

screen shot 2015-06-26 at 3 22 21 pm

**Comment by pcwalton** [comment]
@nickdesaulniers Yeah, that's a preexisting issue. Please file a new bug :)

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6487)

**Comment by jdm** [comment]
```
failures:
    acid2_noscroll.html == acid2_ref_broken.html
    background_image_position_a.html == background_image_position_ref.html
    background_repeat_both_a.html == background_repeat_both_b.html
    background_repeat_y_a.html == background_repeat_y_b.html
    background_size_a.html == background_size_ref.html
```

**Comment by pcwalton** [comment]
OK, the tests should be fixed. Now depends on servo/rust-azure#177. r? @glennw

**Comment by glennw** [comment]
@pcwalton Fix the test-tidy failure, then r=me

**Pull request merged**
