### PR TITLE
Moved CompositorMsg enum into compositing crate.

### LINKED ISSUE #8832: Move CompositorMsg enum into compositing crate
It's a message type for messages sent between the compositor and the constellation, which both live in `components/compositing`. There should be no need for it to be declared in the `msg` crate. We should try moving it!

Code: `components/msg/constellation_msg.rs`, `components/compositing/lib.rs`

### PR DESCRIPTION
**Pull request by kimumetal**
moved CompositorMsg enum into compositing crate.
moved from components/msg/constellation_msg.rs
            to components/compositing/lib.rs
fixes #8832

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8898)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you for your PR.

The change in `components/servo/Cargo.lock` will also need to be applied to `ports/gonk/Cargo.lock` and `ports/cef/Cargo.lock`. Try if `./mach cargo-update -p heapsize` does that.

**Comment by vwvww** [comment]
./mach cargo-update -p heapsize automatically changed ports/cef/Cargo.lock,
but ports/gonk/Cargo.lock is not changed. Maybe I can find other ways to make change on ports/gonk/Cargo.lock or modify it manually.

**Comment by vwvww** [comment]
that PCRKim is my another account (I don't know why it was committed by that account) and committed change on ports/cef/Cargo.lock.

**Comment by Wafflespeanut** [comment]
The changes are okay. Squash the commits, btw?

**Comment by vwvww** [comment]
I squashed the commits, but I'm newbie on github and don't know whether my squash was successful or not...

**Comment by KiChjang** [comment]
@vwvww I think you're good to go.

r? @Ms2ger

**Comment by KiChjang** [comment]
@vwvww squash the commits again, please.

**Comment by vwvww** [comment]
I had some problem with squashing, so it took some days to do it. Anyway, I successfully squashed(hope so), and resolved merge conflict with master branch.

**Comment by Ms2ger** [comment]
@bors-servo r+

Thanks again!

**Pull request merged**
