### PR TITLE
Webxr magicleap

### PR DESCRIPTION
**Pull request by asajeffrey**
Adds the magicleap back end for webxr.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because it's back end stuff

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23903)

### CODE REVIEW

**Comment by asajeffrey** [comment]
The first commit is #23902. 

The matching webxr PR is https://github.com/servo/webxr/pull/35.

**Review by Manishearth — APPROVED** [review]
let's land the webxr side first though

**Comment by CYBAI** [comment]
In android builds and linux tidy:

```
merror[E0063]: missing field `xr_discovery` in initializer of `simpleservo::InitOptions`
   --> ports/libsimpleservo/capi/src/lib.rs:136:16
    |
136 |     let opts = InitOptions {
    |                m^^^^^^^^^^^ mmissing `xr_discovery`

merror: aborting due to previous error

For more information about this error, try `rustc --explain E0063`.
error: Could not compile `simpleservo_capi`.
```

**Comment by asajeffrey** [comment]
Hopefully I fixed the android and c builds... @bors-servo r=Manishearth

**Comment by asajeffrey** [comment]
Hmm https://tools.taskcluster.net/groups/Zw7sMDqGQkec5wxBxQD58A/tasks/csyTNPCESimWHdoBKbLY7w/runs/0/logs/public%2Flogs%2Flive.log#L4746
```
[taskcluster:error] Uploading error artifact public/intermittents.log from file repo/intermittents.log with message "Could not read file '/Users/worker/tasks/task_1564771470/repo/intermittents.log'", reason "file-missing-on-worker" and expiry 2020-08-01T17:15:32.588Z
```
@bors-servo retry

**Pull request merged**
