### PR TITLE
Use a streaming base64 encoder in canvas.toDataURL

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22147)

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by nox** [comment]
Seems like I broke something or the encoder is broken.

**Comment by nox** [comment]
https://github.com/PistonDevelopers/image-png/pull/94

**Comment by atouchet** [comment]
png 0.13.2 is now out.

**Comment by nox** [comment]
I will reopen this when the 24,787 blockers are fixed.

**Comment by atouchet** [comment]
image and png were updated in #22973. Is there anything else blocking this?

**Pull request closed without merging**
