### PR TITLE
Fix counter() and counters() serialization.

### PR DESCRIPTION
**Pull request by emilio**
See https://github.com/w3c/csswg-drafts/issues/670 and https://github.com/w3c/web-platform-tests/pull/9862.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20224)

### CODE REVIEW

**Comment by emilio** [comment]
(And / or @upsuper)

**Comment by emilio** [comment]
Don't merge yet since I probably need to update tests or what not.

**Comment by emilio** [comment]
Oh, actually in the computed value gecko already serializes it properly.

**Comment by upsuper** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20224)*

**Comment by upsuper** [comment]
LGTM, but I'd leave the derive part to @nox. I'm not confident enough to review that.

**Comment by nox** [comment]
r=me, I suspect there are other potential uses of `#[css(skip_if)]` but I can find those myself.

**Comment by nox** [comment]
LGTM, land it whenever you want but my own PR is probably going to bitrot that. :p

**Comment by emilio** [comment]
@bors-servo r-

 * This is waiting on a WPT update so the test failures are passes. I'm landing most of the changes in #20236.

**Comment by jdm** [comment]
```

  ▶ Unexpected subtest result in /css/cssom/serialize-values.html:
  └ PASS [expected FAIL] content: counter(par-num)

  ▶ Unexpected subtest result in /css/cssom/serialize-values.html:
  └ PASS [expected FAIL] content: counter(par-num, decimal)
```

**Comment by jdm** [comment]
@bors-servo retry
* #20281

**Pull request merged**
