### PR TITLE
[DO NOT MERGE] Upgrade to the latest version of WebRender

### PR DESCRIPTION
**Pull request by mrobinson**
---

- [x] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because this shouldn't change behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17649)

### CODE REVIEW

**Comment by stshine** [comment]
```
{"status": "FAIL", "group": "default", "message": "/css-transforms-1_dev/html/css-transforms-3d-on-anonymous-block-001.htm fa5bb5231e37f7af23d604438ece1b8a15ee30d7\n/css-transforms-1_dev/html/reference/css-transforms-3d-anonymous-block-ref.htm 2974244757dd3d3a82bb471d136569568bd512d6\nTesting fa5bb5231e37f7af23d604438ece1b8a15ee30d7 == 2974244757dd3d3a82bb471d136569568bd512d6", "stack": null, "subtest": null, "test": "/css-transforms-1_dev/html/css-transforms-3d-on-anonymous-block-001.htm", "line": 16197, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css-transforms-1_dev/html/transform-table-006.htm 861b859af766977b2c6d0ca5844a836fe7c62f08\n/css-transforms-1_dev/html/reference/transform-blank-ref.htm a90b411990a5f2810cb3845d3c221e1b5e7940f9\nTesting 861b859af766977b2c6d0ca5844a836fe7c62f08 == a90b411990a5f2810cb3845d3c221e1b5e7940f9", "stack": null, "subtest": null, "test": "/css-transforms-1_dev/html/transform-table-006.htm", "line": 23377, "action": "test_result", "expected": "PASS"}
```

**Comment by mrobinson** [comment]
We are already tracking these failures at https://github.com/servo/webrender/issues/1463. Once those are fixed, I'll make this PR ready for review and testing.

**Comment by glennw** [comment]
The test failures are bugs / missing features that are being exposed by the fix in https://github.com/servo/webrender/pull/1426. Since the fix is correct in this case, I think it's fine to mark those tests as expected failures (since they were accidentally passing previously) and get this WR update reviewed / merged.

**Comment by mrobinson** [comment]
I've updated the test expectations. The one remaining task is to ensure that rust-azure is using the new version of core-text. The PR for that is here: https://github.com/servo/rust-azure/pull/268.

**Comment by stshine** [comment]
wtf?

@bors-servo retry

**Comment by stshine** [comment]
Tried one of the tests and got backtrace like this:

```
▶ ../../../../../../mach run tex_image_2d_mipmap.html -d                                                          


Unexpected WebGL error: 0x501 (1281) (thread RenderBackend, at /home/stshine/Programs/webrender/webrender_api/src/w
ebgl.rs:642)                                                                                                      
stack backtrace:
   0:     0x556aabda70e4 - backtrace::backtrace::libunwind::trace
                        at /home/stshine/Programs/servo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ba
cktrace-0.3.2/src/backtrace/libunwind.rs:53                                                                       
                         - backtrace::backtrace::trace<closure>
                        at /home/stshine/Programs/servo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ba
cktrace-0.3.2/src/backtrace/mod.rs:42                                                                             
   1:     0x556aabda03cf - backtrace::capture::{{impl}}::new
                        at /home/stshine/Programs/servo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ba
cktrace-0.3.2/src/capture.rs:64                                                                                   
   2:     0x556aa59f8173 - servo::main::{{closure}}
                        at /home/stshine/Programs/servo/ports/servo/main.rs:129
   3:     0x556aabde2ef9 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:550
   4:     0x556aabde2d44 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:511
   5:     0x556aabde2cd9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:495
   6:     0x556aaa5cd4df - webrender_api::webgl::{{impl}}::apply<offscreen_gl_context::platform::with_glx::native_g
l_context::NativeGLContext>                                                                                       
                        at /home/stshine/Programs/servo/ports/servo/<panic macros>:8
   7:     0x556aaa51a0c9 - webrender::webgl_types::{{impl}}::apply_command
                        at /home/stshine/Programs/webrender/webrender/src/webgl_types.rs:87
   8:     0x556aaa50e422 - webrender::render_backend::{{impl}}::build_scene
                        at /home/stshine/Programs/webrender/webrender/src/render_backend.rs:514
   9:     0x556aaa8a5a4d - webrender::render_backend::{{impl}}::run::{{closure}}
                        at /home/stshine/Programs/webrender/webrender/src/render_backend.rs:259
  10:     0x556aaa8a1279 - webrender::profiler::{{impl}}::profile<(),closure>
                        at /home/stshine/Programs/webrender/webrender/src/profiler.rs:154
  11:     0x556aaa50b800 - webrender::render_backend::{{impl}}::run
                        at /home/stshine/Programs/webrender/webrender/src/render_backend.rs:252
  12:     0x556aaa536363 - webrender::renderer::{{impl}}::new::{{closure}}
                        at /home/stshine/Programs/webrender/webrender/src/renderer.rs:1158
  13:     0x556aaa44ed0a - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  14:     0x556aaa623c03 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:364
  15:     0x556aaa5b415a - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  16:     0x556aaa625869 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:454
  17:     0x556aabdea01c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  18:     0x556aaa62444c - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:433
  19:     0x556aaa623625 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
  20:     0x556aaa452efe - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:363
  21:     0x556aaa4880e3 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:652
  22:     0x556aabde196b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:662
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
  23:     0x7f927772d3c3 - start_thread
  24:     0x7f92772609ce - clone
  25:                0x0 - <unknown>
ERROR:servo: Unexpected WebGL error: 0x501 (1281)
```

**Comment by mrobinson** [comment]
I'm seeing this issue locally too. I think it is https://github.com/rust-lang/rust/issues/43102. Locally I am working around it by reverting the most recent rustup.

**Comment by mrobinson** [comment]
This issue is tracked in #17642.

**Comment by mrobinson** [comment]
The WebGL failures should be fixed by https://github.com/servo/webrender/pull/1471 when that lands. Afterward, I'll update the WebRender hash and we can try the bots again.

**Comment by glennw** [comment]
Closing this in favor of https://github.com/servo/servo/pull/17694 (rebased + latest WR hash).

**Pull request closed without merging**
