### PR TITLE
style: add infrastructure to match the :host selector.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20243)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Reviewed 3 of 3 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/selectors/tree.rs, line 37 at r2](https://reviewable.io:443/reviews/servo/servo/20243#-L75iuri6zrKIYIBO5PN:-L75iuri6zrKIYIBO5PO:bcnmfmf) ([raw file](https://github.com/servo/servo/blob/f43ae599fd9f45e319e04bfc71c88ce8fe44f9fb/components/selectors/tree.rs#L37)):*
> ```Rust
>     fn parent_node_is_shadow_root(&self) -> bool;
> 
>     /// The host of the containing shadow root, if any.
> ```

containing shadow host or containing shadow root?

---

*[components/style/servo/selector_parser.rs, line 428 at r1](https://reviewable.io:443/reviews/servo/servo/20243#-L75i_04-TYOTE2yL_mw:-L75i_04-TYOTE2yL_mx:b-3idsly) ([raw file](https://github.com/servo/servo/blob/72d09202f4e5207cee606e122729dd007e6b5ac8/components/style/servo/selector_parser.rs#L428)):*
> ```Rust
> 
>     #[inline]
>     fn is_active_or_hover(pseudo_class: &Self::NonTSPseudoClass) -> bool {
> ```

This removal needs to be with the other commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20243)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/selectors/tree.rs, line 37 at r2](https://reviewable.io:443/reviews/servo/servo/20243#-L75iuri6zrKIYIBO5PN:-L760NYSJJfuVuYMHXTa:b-vr3nvr) ([raw file](https://github.com/servo/servo/blob/f43ae599fd9f45e319e04bfc71c88ce8fe44f9fb/components/selectors/tree.rs#L37)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

containing shadow host or containing shadow root?
</blockquote></details>

It's the containing shadow host, which is the root of the containing shadow root. If you have suggestions to make it clearer I'm all ears :(

---

*[components/style/servo/selector_parser.rs, line 428 at r1](https://reviewable.io:443/reviews/servo/servo/20243#-L75i_04-TYOTE2yL_mw:-L760VIUY6GGqU-dUiG9:byzpxah) ([raw file](https://github.com/servo/servo/blob/72d09202f4e5207cee606e122729dd007e6b5ac8/components/style/servo/selector_parser.rs#L428)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

This removal needs to be with the other commit.
</blockquote></details>

It's not a removal, it only moves to the new NonTSPseudoClass trait instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20243)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/servo/selector_parser.rs, line 428 at r1](https://reviewable.io:443/reviews/servo/servo/20243#-L75i_04-TYOTE2yL_mw:-L760asOS7gsuLROppQq:b-rtyqea) ([raw file](https://github.com/servo/servo/blob/72d09202f4e5207cee606e122729dd007e6b5ac8/components/style/servo/selector_parser.rs#L428)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

It's not a removal, it only moves to the new NonTSPseudoClass trait instead.
</blockquote></details>

Oh, whoops, I see now, sorry :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20243)*

**Comment by emilio** [comment]
Fixed.

r? @SimonSapin

**Comment by SimonSapin** [comment]
Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/selectors/tree.rs, line 37 at r2](https://reviewable.io:443/reviews/servo/servo/20243#-L75iuri6zrKIYIBO5PN:-L7BXt7IUdjoti6Jzowt:b-vtnrj3) ([raw file](https://github.com/servo/servo/blob/f43ae599fd9f45e319e04bfc71c88ce8fe44f9fb/components/selectors/tree.rs#L37)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

It's the containing shadow host, which is the root of the containing shadow root. If you have suggestions to make it clearer I'm all ears :(
</blockquote></details>

No I just meant that the method name and doc-comment said different things. It looks like the comment has a typo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20243)*

**Comment by SimonSapin** [comment]
r=me with the doc-comment fixed

**Comment by emilio** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/selectors/tree.rs, line 37 at r2](https://reviewable.io:443/reviews/servo/servo/20243#-L75iuri6zrKIYIBO5PN:-L7ZqRzr8JQIncrRWIrR:b-x89f84) ([raw file](https://github.com/servo/servo/blob/f43ae599fd9f45e319e04bfc71c88ce8fe44f9fb/components/selectors/tree.rs#L37)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary><blockquote>

No I just meant that the method name and doc-comment said different things. It looks like the comment has a typo.
</blockquote></details>

It's not a typo, the containing shadow host is the host of the containing shadow root.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/20243)*

**Pull request merged**
