### PR TITLE
Implement History back/forward APIs

### LINKED ISSUE #5670: Implement History's back/forward APIs
Spec: https://html.spec.whatwg.org/multipage/browsers.html#the-history-interface, https://html.spec.whatwg.org/multipage/browsers.html#dom-history-back, 
Code: https://github.com/servo/servo/wiki/Adding-a-new-WebIDL-binding

This will just end up mimicing the behaviour of the GoForward/GoBack APIs of HTMLIFrameElement (see components/script/dom/element/htmliframelement.rs)

### PR DESCRIPTION
**Pull request by tomjakubowski**
Unfortunately, not many once-failing tests are now expected to pass; the
history interface tests often depend on things like History#go working.

Resolves #5670

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7250)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you for your PR.

I'd like to see some kind of functional test before landing this, at least.

-S-awaiting-review +S-needs-code-changes +S-needs-tests 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/history.rs, line 37 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7250#-Jwv3T-Lndr4zCW1mng6)** ([raw file](https://github.com/servo/servo/blob/b50520b02d51b6b2b221e0f2ca0a63109298668d/components/script/dom/history.rs#L37)):</sup>
Let's call this `traverse_history_by_delta` and link to <https://html.spec.whatwg.org/multipage/#traverse-the-history-by-a-delta>.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7250)

**Comment by tomjakubowski** [comment]
Where should such a test live? Should I add one in `tests/wpt/web-platform-tests` somewhere?

I'm not even sure if a `history.back()` or `history.forward()
The [`history_back.html`](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/html/browsers/history/the-history-interface/history_back.html) and corresponding `history_forward.html` tests would pass if I implemented `history.pushState`

**Comment by Ms2ger** [comment]
That would be great.

**Comment by jdm** [comment]
Probably somewhere under https://github.com/w3c/web-platform-tests/tree/master/html/browsers/history ?

**Comment by frewsxcv** [comment]
@tomjakubowski Any updates on this?

**Comment by tomjakubowski** [comment]
I got stuck trying to write tests for this, because `pushState` wasn't yet implemented.

**Comment by jdm** [comment]
Closing due to lack of updates. @tomjakubowski if you'd like to continue working on this, feel free to reopen. Sorry we didn't make any useful recommendations for writing tests!

**Pull request closed without merging**
