### PR TITLE
Move script lints to script_plugins

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15584)

### CODE REVIEW

**Comment by jdm** [comment]
What is the motivation here?

**Comment by nox** [comment]
Not recompiling the whole world whenever plugins is changed. Not depending on unused lints from crates that are not `script`.

**Comment by jdm** [comment]
Looks like it's not working right, but when it does, r=me.

**Comment by nox** [comment]
@bors-servo r=jdm

Disabled every unstable feature in `plugins` when `clippy` isn't used.

**Comment by nox** [comment]
@bors-servo r=jdm

Forgot to update the compile tests.

**Comment by nox** [comment]
@bors-servo r=jdm

script_plugins ≠ servo_plugins

**Pull request merged**
