### PR TITLE
Address common source of shutdown panics

### PR DESCRIPTION
**Pull request by jdm**
Remove easy sources of intermittent failures during test shutdown. Might help #14118 and #14117.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14119)

### CODE REVIEW

**Comment by jdm** [comment]
@rzambre Do these patches make #14117 better?

**Comment by rzambre** [comment]
@jdm I tried out the patches but it is alas the same. The out.png file actually gets created and it has the right output image but Servo always terminates with panics. Running ```./mach run -r -x -o out.png http://www.ehow.com``` gives the following output
> ERROR:script::dom::bindings::error: Error at http://www.ehow.com/:1:1 $ is not defined
ERROR:script::dom::bindings::error: Error at http://www.ehow.com/:1:1 $ is not defined
ERROR:script::dom::bindings::error: Error at http://dynamic01.ehowcdn.com/test4/services/modules/js/pagination_ajax,evidon,rev_tag,dm_track,comscore,quantcast,common_footer/cf732fd7/:1:21809 r[a] is undefined
ERROR:script::dom::bindings::error: Error at http://js-agent.newrelic.com/nr-974.min.js:1:8248 n is undefined
Shutting down the Constellation after generating an output file or exit flag specified
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) } (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at ../src/libcore/result.rs:837)
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at ../src/libcore/result.rs:837)
stack backtrace:
   0:        0x10a34be8e - backtrace::backtrace::trace::h16372ee7bf1517e5
   1:        0x10a34c17c - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
   2:        0x10a0138c4 - servo::main::_{{closure}}::h3c01218599dd921e
   3:        0x10b9d6d03 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
   4:        0x10b9d6bd4 - std::panicking::begin_panic::ha6a0d553db9869ff
   5:        0x10b9d6af2 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
   6:        0x10b9d6a57 - rust_begin_unwind
   7:        0x10ba03820 - core::panicking::panic_fmt::he441b2ea2036b98a
   8:        0x10b602ac0 - core::result::unwrap_failed::h88381ff2d9927dee
   9:        0x10b60345d - profile_traits::mem::ProfilerChan::send::h7c5621ed4725ec45
  10:        0x10a583088 - std::panicking::try::do_call::haf3d92fc2a8a22cf
  11:        0x10b9d7d2a - __rust_maybe_catch_panic
  12:        0x10a66e766 - _<F as alloc..boxed..FnBox<A>>::call_box::h3c3214512a55a996
  13:        0x10b9d5bb4 - std::sys::thread::Thread::new::thread_start::h9fa66f6812e81e10
  14:     0x7fff89e8c99c - _pthread_body
  15:     0x7fff89e8c919 - _pthread_start
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }
stack backtrace:
   0:        0x10a34be8e - backtrace::backtrace::trace::h16372ee7bf1517e5
   1:        0x10a34c17c - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
   2:        0x10a0138c4 - servo::main::_{{closure}}::h3c01218599dd921e
   3:        0x10b9d6d03 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
   4:        0x10b9d6bd4 - std::panicking::begin_panic::ha6a0d553db9869ff
   5:        0x10b9d6af2 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
   6:        0x10b9d6a57 - rust_begin_unwind
   7:        0x10ba03820 - core::panicking::panic_fmt::he441b2ea2036b98a
   8:        0x10b602ac0 - core::result::unwrap_failed::h88381ff2d9927dee
   9:        0x10b60345d - profile_traits::mem::ProfilerChan::send::h7c5621ed4725ec45
  10:        0x10a3759e4 - std::panicking::try::do_call::h89962fd2c03af2c0
  11:        0x10b9d7d2a - __rust_maybe_catch_panic
  12:        0x10a39e065 - _<F as alloc..boxed..FnBox<A>>::call_box::h3f1a458da3a01818
  13:        0x10b9d5bb4 - std::sys::thread::Thread::new::thread_start::h9fa66f6812e81e10
  14:     0x7fff89e8c99c - _pthread_body
  15:     0x7fff89e8c919 - _pthread_start
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) } (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at ../src/libcore/result.rs:837)
stack backtrace:
   0:        0x10a34be8e - backtrace::backtrace::trace::h16372ee7bf1517e5
   1:        0x10a34c17c - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
   2:        0x10a0138c4 - servo::main::_{{closure}}::h3c01218599dd921e
   3:        0x10b9d6d03 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
   4:        0x10b9d6bd4 - std::panicking::begin_panic::ha6a0d553db9869ff
   5:        0x10b9d6af2 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
   6:        0x10b9d6a57 - rust_begin_unwind
   7:        0x10ba03820 - core::panicking::panic_fmt::he441b2ea2036b98a
   8:        0x10b602ac0 - core::result::unwrap_failed::h88381ff2d9927dee
   9:        0x10b60345d - profile_traits::mem::ProfilerChan::send::h7c5621ed4725ec45
  10:        0x10a583088 - std::panicking::try::do_call::haf3d92fc2a8a22cf
  11:        0x10b9d7d2a - __rust_maybe_catch_panic
  12:        0x10a66e766 - _<F as alloc..boxed..FnBox<A>>::call_box::h3c3214512a55a996
  13:        0x10b9d5bb4 - std::sys::thread::Thread::new::thread_start::h9fa66f6812e81e10
  14:     0x7fff89e8c99c - _pthread_body
  15:     0x7fff89e8c919 - _pthread_start
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }
called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) } (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(1) }, at ../src/libcore/result.rs:837)
stack backtrace:
   0:        0x10a34be8e - backtrace::backtrace::trace::h16372ee7bf1517e5
   1:        0x10a34c17c - backtrace::capture::Backtrace::new::hcc43c50c4b11c693
   2:        0x10a0138c4 - servo::main::_{{closure}}::h3c01218599dd921e
   3:        0x10b9d6d03 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
   4:        0x10b9d6bd4 - std::panicking::begin_panic::ha6a0d553db9869ff
   5:        0x10b9d6af2 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
   6:        0x10b9d6a57 - rust_begin_unwind
   7:        0x10ba03820 - core::panicking::panic_fmt::he441b2ea2036b98a
   8:        0x10b602ac0 - core::result::unwrap_failed::h88381ff2d9927dee
   9:        0x10b60345d - profile_traits::mem::ProfilerChan::send::h7c5621ed4725ec45
  10:        0x10a3759e4 - std::panicking::try::do_call::h89962fd2c03af2c0
  11:        0x10b9d7d2a - __rust_maybe_catch_panic
  12:        0x10a39e065 - _<F as alloc..boxed..FnBox<A>>::call_box::h3f1a458da3a01818
  13:        0x10b9d5bb4 - std::sys::thread::Thread::new::thread_start::h9fa66f6812e81e10
  14:     0x7fff89e8c99c - _pthread_body
  15:     0x7fff89e8c919 - _pthread_start
ERROR:servo: called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotFound, error: StringError("Bogus destination port.") }) }

**Comment by jdm** [comment]
That's strange - the backtraces seem to show panics occurring in the code that I modified. Either that's not a build that includes the changes in these commits, or the unwrap is coming from ipc-channel internals.

**Pull request merged**
