### PR TITLE
Refactor resource loaders to use send_error utility.

### PR DESCRIPTION
**Pull request by eefriedman**
No substantial functional change.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7984)

### CODE REVIEW

**Comment by jdm** [comment]
This is ready to merge after a rebase. Thanks!
-S-awaiting-review 


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7984)

**Comment by eefriedman** [comment]
Rebased.

**Comment by jdm** [comment]
@bors-servo: retry
* #7785

**Comment by jdm** [comment]
@bors-servo: retry
* #7785

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Pull request merged**
