### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See individual commits for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20786)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo retry

 * Not sure this is expected or not, worth a retry I guess

**Comment by jdm** [comment]
@bors-servo treeclosed=9000
Tree is still closed.

**Comment by emilio** [comment]
@bors-servo retry

 * Looks like stuff is landing now :::)

**Comment by emilio** [comment]
@bors-servo treeclosed-

I think bors just got confused.

**Pull request merged**
