### PR TITLE
Parse trait functions

### LINKED ISSUE #14101: Make parse functions implement from Parse trait in style
There is a [Parse trait](https://github.com/servo/servo/blob/41df7056610e474a9a2efe4c807f480e976d0c1d/components/style/parser.rs#L89) in style crate. This trait will make it easy to write more generic values in the future. And it would be great if we convert parse functions to this implementation. You can find relevant parse functions with dxr[1]
Of course some of them are already implemented from this trait(like [this one](https://dxr.mozilla.org/servo/source/components/style/values/specified/image.rs#320)). Simply ignore that cases.

[1] https://dxr.mozilla.org/servo/search?q="fn+parse("+-ParserContext

### PR DESCRIPTION
**Pull request by impowski**
Moved parse functions to a Parse trait in style. r? @Manishearth

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14101 (github issue number if applicable).

- [x] There are tests for these changes OR
- [X] These changes do not require tests because new functionalities weren't added

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14178)

### CODE REVIEW

**Comment by impowski** [comment]
@jdm Is it fine? I just accidentally changed `components/style/values/specified/mod.rs` I didn't know that I need have write access.

**Comment by jdm** [comment]
Changing it is fine, but your changes conflict with recent changes to the file that already exist on master. You will need to rebase your changes on top of them by following our guide: https://github.com/servo/servo/wiki/Github-workflow

**Comment by KiChjang** [comment]
A more detailed guide for squashing and rebasing exists here https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing

**Review by ghost — APPROVED** [review]
Changes LGTM :)

**Comment by Wafflespeanut** [comment]
Thanks for doing this! It's gonna be quite useful :)

@bors-servo r+

**Pull request merged**
