### PR TITLE
Move setting UserAgent header into http_loader::load,

### LINKED ISSUE #7541: Move setting UserAgent header into http_loader::load
Headers have no meaning for protocols other than HTTP/HTTPS. This will make it easier to implement the [fetch spec](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch) in the future too, if we keep all of our HTTP-related code in one place.

Code: components/net/resource_task.rs, components/net/http_loader.rs

### PR DESCRIPTION
**Pull request by jxs**
closes #7541

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7549)

### CODE REVIEW

**Comment by jdm** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/http_loader.rs, line 546 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7549#-JyxYwWfBluoDBXX9c1e)** ([raw file](https://github.com/servo/servo/blob/2e88850da446ce07b46a3e7c766b2e2b53abab37/components/net/http_loader.rs#L546)):</sup>
No need for this clone.

---

<sup>**[components/net/resource_task.rs, line 237 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7549#-JyxZ2PYpIh2W6mJWroa)** ([raw file](https://github.com/servo/servo/blob/2e88850da446ce07b46a3e7c766b2e2b53abab37/components/net/resource_task.rs#L237)):</sup>
Let's remove this.

---

<sup>**[tests/unit/net/http_loader.rs, line 228 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7549#-JyxZDsbVvJ3NLTt7LHk)** ([raw file](https://github.com/servo/servo/blob/2e88850da446ce07b46a3e7c766b2e2b53abab37/tests/unit/net/http_loader.rs#L228)):</sup>
This differs from the user agent we pass to new_resource_task through this file; let's replace all uses of `"Test-agent"` and `"user_agent"` with a constant value named `DEFAULT_USER_AGENT` instead.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7549)

**Comment by jxs** [comment]
updated!
regarding the clone, that clone is inside a loop block, if i remove it, servo doesn't compile giving used of moved value error

**Comment by jdm** [comment]
Looks great! Now we just need to fix the problem reported by `./mach test-tidy`.
-S-awaiting-review +S-fails-tidy 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7549)

**Comment by jxs** [comment]
oh sorry, forgot to run test-tidy after the fixes.
fixed test-tidy!

**Comment by jdm** [comment]
That's #7625 again. Something is going on here...

**Comment by metajack** [comment]
@bors-servo retry

- spinning up builders to test fix for  #7625

**Pull request merged**
