### PR TITLE
tests for devtools integration with network requests/responses

### LINKED ISSUE #7473: Write automated tests for devtools integration with network requests/responses
We have code in `http_loader.rs` that sends notifications when a network request is sent as well as when a response is received. We now have the ability to write tests that check this since #7139 was merged. These should pass a real Sender value to `new_resource_task`, and compare the properties of the [NetworkEvent](http://mxr.mozilla.org/servo/source/components/devtools_traits/lib.rs#68) messages that should be received (on the corresponding Receiver) against the properties of the request and response objects.

Code: tests/unit/net/http_loader.rs

### PR DESCRIPTION
**Pull request by psdh**
Fixes #7473

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7497)

### CODE REVIEW

**Comment by jdm** [comment]
This is a good start! I'd also like to see tests that we get notifications for two separate sets of requests and responses when a redirection occurs, as well as a test that setting a custom header on a request make it appear in the devtools notification, and the same for a response.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 250 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyDLRm2i-rmOq2CfM1P)** ([raw file](https://github.com/servo/servo/blob/1e51688108131e455a1c7e35ce4e117c6ba21c73/tests/unit/net/http_loader.rs#L250)):</sup>
Let's call these devtools_chan and devtools_port.

---

<sup>**[tests/unit/net/http_loader.rs, line 253 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyDLhnq0iCJdJ-nn6mv)** ([raw file](https://github.com/servo/servo/blob/1e51688108131e455a1c7e35ce4e117c6ba21c73/tests/unit/net/http_loader.rs#L253)):</sup>
This clone isn't necessary.

---

<sup>**[tests/unit/net/http_loader.rs, line 255 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyDM9PPZ8gdJYmmjHr9)** ([raw file](https://github.com/servo/servo/blob/1e51688108131e455a1c7e35ce4e117c6ba21c73/tests/unit/net/http_loader.rs#L255)):</sup>
I propose we make HttpRequest a real struct (so the enum contains `HttpRequest(HttpRequest)`), and we extract this into a `expect_devtools_http_request` function that returns `HttpRequest`. We can then use `assert_eq!` on it to ensure that the content we expect is present.

---

<sup>**[tests/unit/net/http_loader.rs, line 269 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyDMVy9af16hLDLwb8Q)** ([raw file](https://github.com/servo/servo/blob/1e51688108131e455a1c7e35ce4e117c6ba21c73/tests/unit/net/http_loader.rs#L269)):</sup>
Same as above but with `HttpResponse`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7497)

**Comment by psdh** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 269 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyDMVy9af16hLDLwb8Q)** ([raw file](https://github.com/servo/servo/blob/1e51688108131e455a1c7e35ce4e117c6ba21c73/tests/unit/net/http_loader.rs#L269)):</sup>
won't I have to compare HttpResponse with the MockResponse, if I follow this approach?
i.e assert_eq! won't let me compare two different structs. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7497)

**Comment by jdm** [comment]
If we do `let expected = HttpResponse { ... }`, we can compare against that.

**Comment by psdh** [comment]
ah right, but I realized HttpResponse is no real struct, it is a trait in `components/net/http_loader.rs`. I think I'll discuss this on IRC

**Comment by jdm** [comment]
I didn't realize there's an overlap of names here. I'm suggesting creating a new struct in devtools_traits named `HttpResponse` (or maybe `HttpResponseContent`), which is distinct from the trait named `HttpResponse`.

**Comment by psdh** [comment]
@jdm, this last commit is incomplete
I thought pushing a commit with current progress could help clarify this better

**Comment by jdm** [comment]
That looks like what I was imagining :) As for what to compare against, we should be able to create reference values based on the methods available for the `HttpResponse` and `HttpRequest` traits.

**Comment by jdm** [comment]
Getting better!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 4 files at r1, 7 of 7 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

<sup>**[components/devtools/actors/network_event.rs, line 13 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxsBPmv-2EOi-KZzk4)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/components/devtools/actors/network_event.rs#L13)):</sup>
Let's use `DevtoolsHttp[Request|Response]` instead.

---

<sup>**[components/devtools/actors/network_event.rs, line 137 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxsKYaej-NNMczU5On)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/components/devtools/actors/network_event.rs#L137)):</sup>
Let's remove this.

---

<sup>**[components/devtools_traits/lib.rs, line 269 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxsQ9JvNU7_ShzhKIs)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/components/devtools_traits/lib.rs#L269)):</sup>
Let's call this `body`.

---

<sup>**[components/devtools_traits/lib.rs, line 276 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxsT8x2xsRWb74YX7k)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/components/devtools_traits/lib.rs#L276)):</sup>
Let's call this `body`.

---

<sup>**[components/net/http_loader.rs, line 8 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxsdyQG-vmEMzqaPur)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/components/net/http_loader.rs#L8)):</sup>
`DevtoolsHttp[Request|Response]`

---

<sup>**[components/net/http_loader.rs, line 415 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-Jyxt5_QXGpwaMt-rqRQ)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/components/net/http_loader.rs#L415)):</sup>
Let's use a separate `let request = ...` line here or this gets pretty long.

---

<sup>**[components/net/http_loader.rs, line 427 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxtAOihs5Wt29RO6t9)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/components/net/http_loader.rs#L427)):</sup>
Same as above.

---

<sup>**[tests/tests/unit/net/http_loader.rs, line 215 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxtH584J-ohJ84f-rm)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/tests/tests/unit/net/http_loader.rs#L215)):</sup>
Why the mpsc:: here? Also, remove the space after &.

---

<sup>**[tests/tests/unit/net/http_loader.rs, line 227 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxtRKKU0nZz9t_U-C3)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/tests/tests/unit/net/http_loader.rs#L227)):</sup>
I think we should just return `DevtoolsHttpRequest` and panic if we don't get the value we're expecting.

---

<sup>**[tests/tests/unit/net/http_loader.rs, line 231 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxtYgwYTeTUV4lzy_J)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/tests/tests/unit/net/http_loader.rs#L231)):</sup>
Same as earlier.

---

<sup>**[tests/tests/unit/net/http_loader.rs, line 237 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-Jyxt_WEDIrXHEt25zH9)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/tests/tests/unit/net/http_loader.rs#L237)):</sup>
Let's remove this.

---

<sup>**[tests/tests/unit/net/http_loader.rs, line 244 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxtaRTXj6w-ZZbC1uX)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/tests/tests/unit/net/http_loader.rs#L244)):</sup>
Same as earlier; I don't see a reason to return Option here.

---

<sup>**[tests/tests/unit/net/http_loader.rs, line 292 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-Jyxtotw7j05pQfD_0Pj)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/tests/tests/unit/net/http_loader.rs#L292)):</sup>
nit: remove the space after &

---

<sup>**[tests/tests/unit/net/http_loader.rs, line 307 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxtfCjEQahjP-guIx7)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/tests/tests/unit/net/http_loader.rs#L307)):</sup>
Add `#[derive(PartialEq)]` on the struct declaration.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7497)

**Comment by psdh** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[tests/tests/unit/net/http_loader.rs, line 307 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxtfCjEQahjP-guIx7)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/tests/tests/unit/net/http_loader.rs#L307)):</sup>
This doesn't seem to work due to hyper::header::Headers, I cannot add #[derive(PartialEq)] to Headers(right?)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7497)

**Comment by jdm** [comment]
Huh. I suggest making a PR to hyper to add that, since HashMap already implements PartialEq. You can use an [override](http://doc.crates.io/guide.html#overriding-dependencies) to keep working locally using a modified version of hyper.

**Comment by psdh** [comment]
The `hashmap` in `Headers` works on `Item` which in turn works on `OptCell` and 
``` pub struct OptCell<T>(UnsafeCell<Option<T>>); ``` So we'd have to implement PartialEq for UnsafeCell for this to work. Right?

**Comment by jdm** [comment]
You're right; let's write our own equality function, in that case. For each `(key, val)` in each hashmap, ensure that `Some(val)` is present in the other hashmap with the same key.

**Comment by psdh** [comment]
@jdm hyperium/hyper#656 finally got merged. Should I file a new issue to use the latest version of hyper? or is some other procedure to go about this?
I read a `hyper = "0.6" in the `Cargo.toml` for the components/util dir.

**Comment by jdm** [comment]
You could include a commit in this PR that upgrades hyper; just run `./mach cargo-update -p hyper` and commit all of the changes required to make the result compile :)

**Comment by psdh** [comment]
@jdm  |mach cargo-update -p rand --precise 0.3.11| lead to [errors](https://www.irccloud.com/pastebin/FYwQkAWy/)

**Comment by jdm** [comment]
These commands worked fine for me:
```
./mach update-cargo -p hyper
./mach update-cargo -p unicase:0.1.0
```

**Comment by jdm** [comment]
That being said, we've apparently upgrade our other dependencies (including unicase), so if you rebase to master upgrade hyper, it should Just Work.

**Comment by jdm** [comment]
Looking good so far!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 13 of 13 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[components/net/http_loader.rs, line 8 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7497#-JyxsdyQG-vmEMzqaPur)** ([raw file](https://github.com/servo/servo/blob/94f81a252629c0f042123003125dbba590de0042/components/net/http_loader.rs#L8)):</sup>
This still needs to be addressed.

---

<sup>**[tests/unit/net/http_loader.rs, line 282 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7497#-K-1nvKKD7NpZe2MmjIV)** ([raw file](https://github.com/servo/servo/blob/ab694ed906b24f00ec26bf9a8da9678d7bbff638/tests/unit/net/http_loader.rs#L282)):</sup>
Let's include a custom header in the response.

---

<sup>**[tests/unit/net/http_loader.rs, line 285 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7497#-K-1mUU7BuNDY06Jv1Zr)** ([raw file](https://github.com/servo/servo/blob/ab694ed906b24f00ec26bf9a8da9678d7bbff638/tests/unit/net/http_loader.rs#L285)):</sup>
Let's indent like this:
```rust
Ok(MockRequest::new(
       ResponseType::Text(<[_]>::to_vec("Yay!".as_bytes()))))
```

---

<sup>**[tests/unit/net/http_loader.rs, line 294 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7497#-K-1o-_dlk8kRUoGXO6T)** ([raw file](https://github.com/servo/servo/blob/ab694ed906b24f00ec26bf9a8da9678d7bbff638/tests/unit/net/http_loader.rs#L294)):</sup>
Let's include a custom header in the request.

---

<sup>**[tests/unit/net/http_loader.rs, line 307 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7497#-K-1nFi2tKw8hLimdFkt)** ([raw file](https://github.com/servo/servo/blob/ab694ed906b24f00ec26bf9a8da9678d7bbff638/tests/unit/net/http_loader.rs#L307)):</sup>
nit: trailing whitespace

---

<sup>**[tests/unit/net/http_loader.rs, line 311 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7497#-K-1nTGrNhcu-h553RUS)** ([raw file](https://github.com/servo/servo/blob/ab694ed906b24f00ec26bf9a8da9678d7bbff638/tests/unit/net/http_loader.rs#L311)):</sup>
Let's use the typed header instead here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7497)

**Comment by jdm** [comment]
Great work! Please squash these commits together now :)
-S-awaiting-review +S-needs-squash 

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/net/http_loader.rs, line 155 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7497#-K-4-oIWrcx71if9WJv3)** ([raw file](https://github.com/servo/servo/blob/cb46f10d98a0c0836f92ac25c04a97e2589ec02a/tests/unit/net/http_loader.rs#L155)):</sup>
I would rather make this change as part of #7647.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7497)

**Comment by jdm** [comment]
```
./components/net/http_loader.rs:8: use statement is not in alphabetical order

	expected: devtools_traits::HttpRequest as DevtoolsHttpRequest

	found: devtools_traits::{ChromeToDevtoolsControlMsg, DevtoolsControlMsg, NetworkEvent}

./components/net/http_loader.rs:9: use statement is not in alphabetical order

	expected: devtools_traits::HttpResponse as DevtoolsHttpResponse

	found: devtools_traits::HttpRequest as DevtoolsHttpRequest

./components/net/http_loader.rs:10: use statement is not in alphabetical order

	expected: devtools_traits::{ChromeToDevtoolsControlMsg, DevtoolsControlMsg, NetworkEvent}

	found: devtools_traits::HttpResponse as DevtoolsHttpResponse

./tests/unit/net/http_loader.rs:298: Line is longer than 120 characters

./tests/unit/net/http_loader.rs:22: use statement is not in alphabetical order

	expected: std::sync::mpsc::Receiver

	found: std::sync::{Arc, mpsc, RwLock}

./tests/unit/net/http_loader.rs:23: use statement is not in alphabetical order

	expected: std::sync::{Arc, mpsc, RwLock}

	found: std::sync::mpsc::Receiver

The command "./mach test-tidy" exited with 1.
```

**Pull request merged**
