### PR TITLE
Add Gentoo to README.md

### PR DESCRIPTION
**Pull request by zetok**
I didn't include some dependencies that come "by default" (e.g. bzip2).
Not sure whether there might be some additional deps that I have on my system, but aren't listed.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7819)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Lovely! Thank you for documenting this :)

**Comment by mbrubeck** [comment]
@bors-servo retry

#7778

**Comment by jdm** [comment]
@mbrubeck Wrong issue reference?

**Comment by mbrubeck** [comment]
Oops, it was #7785.

**Comment by jdm** [comment]
@bors-servo: retry
* #7785

**Pull request merged**
