### PR TITLE
Interval + CSV time-profiling

### LINKED ISSUE #10886: Time-profiling output to a CSV file upon exit for automated Servo testing
This will allow the user to use the existing -p option to direct the time-profiling output to a CSV file upon termination of Servo. So the -p option can take two types of arguments: either a number of a file name. If it is a number, then the number will be used as the interval for printing out profiling output to the terminal (as it is currently implemented). If it is a file name, the time-profiling data will be printed out to the file upon Servo's termination.

This new addition to the -p option will be essential for running automated Servo tests and runs. The best way to make use of this function is by calling Servo with these options:

./mach run -r -x -o out.png -p out.csv <url>

### PR DESCRIPTION
**Pull request by rzambre**
This PR fixes #10886. The -p option can be followed by either an interval number or a CSV filename.
- In the interval profiling, the profiler output would be spitted out to the terminal periodically.
  Example usage: **./mach run -p 1 http://www.google.com** will print the time-profiling output to the terminal every second.
- In the CSV file profiling, a CSV file will be generate upon termination of servo.
  Example usage: **./mach run -x -o out.png -p out.csv http://www.google.com** will generate out.csv upon termination of Servo.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10995)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed 5 of 5 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10995)*

**Comment by larsbergstrom** [comment]
Can you rebase and squash? If you'd like some help with doing the git magic, please let me know! In particular, you've picked up a bunch of merge commits in there, too, and there should just be a single commit displayed with your changes. This should be good to go after that!

**Comment by rzambre** [comment]
This morning I had noticed that my PR had failed the tidy-test (some trailing spaces) and the etc/ci/check_no_unwrap.sh test (there is an unwrap() in line 498). I have made commits to pass the tidy-test check and also the check_no_unwrap.sh test (I replaced the unwrap with a "match Ok/Err").

I might need help with rebase and squashing though :) My attempt here didn't go through well.

**Comment by larsbergstrom** [comment]
Reviewed 2 of 2 files at r5.
Review status: 3 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10995)*

**Comment by larsbergstrom** [comment]
Ugh, sorry about this, @rzambre! You will have to rebase *again* as something got landed into master that conflicted with it. You can do so by doing the following, assuming that `origin` = `https://github.com/rzambre/servo` and `upstream` = `https://github.com/servo/servo`:

```
git fetch upstream
git rebase -i upstream/master
git push -f origin master
```

**Comment by rzambre** [comment]
No worries @larsbergstrom! This PR has provided me with _invaluable_ git experience :)

@mbrubeck @fitzgen I have tried my best to keep your recent PRs (#11119, #11096 and #10694) in place. From all my testing so far, everything works the way it should but if you do find something amiss, let me know.

**Pull request merged**
