### PR TITLE
Html option element.form#13111

### LINKED ISSUE #13111: Implement HTMLOptionElement#form
Spec: https://html.spec.whatwg.org/multipage/forms.html#dom-option-form
Files: `components/script/dom/htmloptionelement.rs`, `components/script/dom/webidls/HTMLOptionElement.webidl`
Test: None yet; will need to write one located in `tests/wpt/web-platform-tests/html/semantics/forms/the-option-element/`

### PR DESCRIPTION
**Pull request by splav**
Add HTMLOptionElement form attribute support

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13111 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13126)

### CODE REVIEW

**Comment by metajack** [comment]
This does not seem to implement the logic described:

    The form IDL attribute's behaviour depends on whether the option element is in a select element or not. If the option has a select element as its parent, or has an optgroup element as its parent and that optgroup element has a select element as its parent, then the form IDL attribute must return the same value as the form IDL attribute on that select element. Otherwise, it must return null.

This seems to grab the parent, test of that is an opt group, and if so, return its form. Otherwise it returns the parent. Nowhere is select checked for or form invoked on these parents. Also, it seems like we should be returning None if the parent isn't opt group or a select.

**Comment by splav** [comment]
@metajack it checks if the parent is HTMLOptGroupElement, if it is - parent is set to grandparent, else to parent. Then it checks if the node, pointed by parent is HTMLSelectElement and returns it's form. The None is forwarded through all the chain in all other cases. 
May be the logic is a bit confusing and should be changed. Though I'm not sure how.

**Comment by metajack** [comment]
Ok. I have read the code a little more carefully this time, and it does appear to do the right thing. The extra checks I was looking for are just implicit in the and_then calls.

**Comment by splav** [comment]
@metajack updated passing tests expectations.

**Pull request merged**
