### PR TITLE
Add a high-level API for JS typed arrays

### PR DESCRIPTION
**Pull request by jdm**
This largely a Rust-y port of Gecko's API. No codegen support yet, but it's a lot easier to work with typed arrays properly now.

r? @Ms2ger

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6779)

### CODE REVIEW

**Comment by jdm** [comment]
Requires https://github.com/servo/rust-mozjs/pull/180.

**Comment by Ms2ger** [comment]
The first thing I'd ask is whether some of this could live in rust-mozjs; I sometimes dream of a fully safe api around SM.

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: 3 of 9 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

<sup>**[components/canvas_traits/lib.rs, line 126 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAvDgZ7S3LU0DfQnST)** ([raw file](https://github.com/servo/servo/blob/2a8f62f952c3b6ccde6a73393e56af070809df4b/components/canvas_traits/lib.rs#L126)):</sup>
I like issue numbers with my TODOs.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAqrLcKqGqQlm5Xl_g)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L47)):</sup>
I don't imagine this can be private.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 137 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvArTRHMv8bKoLEmpkv)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L137)):</sup>
This is what Gecko does, but why not have `fn new() -> Result<TypedArrayBase<T>, ()>`?

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvArzCm_UCiI8HQUUvv)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L159)):</sup>
This is unsafe; it may invoke UB by creating two objects from the same JS object.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 168 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAsEz5QyTPSTO9TIgP)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L168)):</sup>
Any reason not to do this in `new()`?

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 180 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAsOSgZuj7iFC2Uxb_)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L180)):</sup>
Limit to `T: TypedArrayElement`?

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 250 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAt0sN3O6um8NM9kQi)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L250)):</sup>
GC hazard?

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 292 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAtMDWkIPZ_myxVwOe)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L292)):</sup>
Do we need the macro and trait?

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 331 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAtb1B2sNI_KU1lDAC)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L331)):</sup>
Ditto

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 358 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAtw4bsW0PHGPRN5_d)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L358)):</sup>
Does this cast adjust the length?

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 364 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAu0kgz0VPP-HZmulk)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L364)):</sup>
Ditto for length and UB

---

<sup>**[components/script/dom/imagedata.rs, line 51 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAuxkaX__hR0oplCv-)** ([raw file](https://github.com/servo/servo/blob/eafce45df3bef200b5c619b1cec5281dc67d4a87/components/script/dom/imagedata.rs#L51)):</sup>
Followup to remove the argument?

---

<sup>**[components/script/dom/imagedata.rs, line 54 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAv44q8vvVJ4IVyaGV)** ([raw file](https://github.com/servo/servo/blob/eafce45df3bef200b5c619b1cec5281dc67d4a87/components/script/dom/imagedata.rs#L54)):</sup>
`[]`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6779)

**Comment by jdm** [comment]
The rooting can't live there, unfortunately, due to its reliance on the whole JSReflectable trait stuff and RootedJSTraceableSet.

**Comment by Ms2ger** [comment]
It probably wouldn't be a good idea to move everything except the rooting there. Maybe it could make sense to move most of `trace.rs` to rust-mozjs as well, though…

**Comment by jdm** [comment]
Review status: 2 of 9 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAqrLcKqGqQlm5Xl_g)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L47)):</sup>
Correct. Private type exposed in public type bounds etc.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 168 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAsEz5QyTPSTO9TIgP)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L168)):</sup>
Consider `void setValueCurveAtTime(Float32Array values, double startTime);`, and code like `setValueCurveAtTime(some_float32_array, /* object with getter that neuters some_float32_array */);`
When this constructor moves into the bindings and the DOM methods are passed `value: &Float32Array`, its buffer pointer has been silently invalidated by `startTime`'s getter and we'll now have a UAF.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 292 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAtMDWkIPZ_myxVwOe)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L292)):</sup>
It can be used in the future for SharedArrayBufferViews.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6779)

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r5, 6 of 6 files at r6, 6 of 6 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 110 \[r7\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvT1aUEW_5HReOh1ePa)** ([raw file](https://github.com/servo/servo/blob/5b0eb678c55ec0586d41b29dddbdcf22f00dbd3c/components/script/dom/bindings/typedarray.rs#L110)):</sup>
Replace by `Option<(*mut _, u32)>`?

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 168 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAsEz5QyTPSTO9TIgP)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L168)):</sup>
Bah. How about we make these types entirely opaque, and give them a method that returns a more transparent struct in a Result?

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 188 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvT0qXcADURtnBXTsol)** ([raw file](https://github.com/servo/servo/blob/fdbe8e9a3fba296e88bed3e994c96298e8ae4d43/components/script/dom/bindings/typedarray.rs#L188)):</sup>
Can't tenacious enforce that?

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 442 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvT0fAFncrgVUilc4LW)** ([raw file](https://github.com/servo/servo/blob/fdbe8e9a3fba296e88bed3e994c96298e8ae4d43/components/script/dom/bindings/typedarray.rs#L442)):</sup>
No need for the parens

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6779)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 166 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvAsEz5QyTPSTO9TIgP)** ([raw file](https://github.com/servo/servo/blob/94399d26a6caf2a295159ebdd777723e5fd3725e/components/script/dom/bindings/typedarray.rs#L166)):</sup>
That's a really good idea.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 189 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvT0qXcADURtnBXTsol)** ([raw file](https://github.com/servo/servo/blob/fdbe8e9a3fba296e88bed3e994c96298e8ae4d43/components/script/dom/bindings/typedarray.rs#L189)):</sup>
Paging @Manishearth

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6779)

**Comment by Manishearth** [comment]
Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 194 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvT0qXcADURtnBXTsol)** ([raw file](https://github.com/servo/servo/blob/fdbe8e9a3fba296e88bed3e994c96298e8ae4d43/components/script/dom/bindings/typedarray.rs#L194)):</sup>
Yes, but keep the assert there too.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6779)

**Comment by jdm** [comment]
Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 194 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvT0qXcADURtnBXTsol)** ([raw file](https://github.com/servo/servo/blob/fdbe8e9a3fba296e88bed3e994c96298e8ae4d43/components/script/dom/bindings/typedarray.rs#L194)):</sup>
I looked into this, and I'd prefer not to rely on tenacious since it requires introducing another intermediary type:
```
11:48 <jdm> but that makes the client code pretty clunky
11:48 <jdm> let rooter = TypedArrayRooter::new();
11:48 <jdm> let typed_array = TypedArray::from(foo, &mut rooter);
11:48 <jdm> let inited_typed_array = typed_array.init();
11:48 <jdm> let buffer = inited_typed_array.extract();
11:48 <jdm> buffer.as_slice() //woohoo an actual piece of data!
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6779)

**Comment by jdm** [comment]
@bzbarsky Do you know why the Gecko code uses JS_CallUnbarrieredObjectTracer?

**Comment by bzbarsky** [comment]
Probably because I was told to do that by terrence?  Note that this is only in cases when we're dealing with a stack-based autorooter, right?

**Comment by jdm** [comment]
Yeah, that's the conclusion that mwu came to as well. We may need to do something different here, since apparently our RootedTraceableSet has some different characteristics from the CustomAutoRooter stuff.

**Comment by Ms2ger** [comment]
Reviewed 5 of 7 files at r8.
Review status: 7 of 9 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 182 \[r8\]](https://reviewable.io:443/reviews/servo/servo/6779#-JvnbrG8hBeVWkLzczvU)** ([raw file](https://github.com/servo/servo/blob/d8b33666cd420d1deef427fcf073b90403455d21/components/script/dom/bindings/typedarray.rs#L182)):</sup>
I think we should be able to avoid this unwrap.

---

<sup>**[components/script/dom/bindings/typedarray.rs, line 385 \[r8\]](https://reviewable.io:443/reviews/servo/servo/6779#-Jvnc4kMMGPY41PCu6k1)** ([raw file](https://github.com/servo/servo/blob/d8b33666cd420d1deef427fcf073b90403455d21/components/script/dom/bindings/typedarray.rs#L385)):</sup>
Missing space

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6779)

**Comment by jdm** [comment]
Updated.

**Comment by jdm** [comment]
Note: due to the concerns about unbarriered tracing, I'm intending to implement equivalent support for SM's CustomAutoRooter instead.

**Comment by frewsxcv** [comment]
@jdm Any updates on this?

**Comment by jdm** [comment]
Not since my related mailing list post. No particular point in leaving this open.

**Pull request closed without merging**
