### PR TITLE
Fixes #7907: rendering for unescaped string "<iframe>" in doc

### LINKED ISSUE #7907: Fix rendering for documentation that contains unescaped string "<iframe>"
This is the result of such unescaped HTML: http://doc.servo.org/servo/msg/constellation_msg/enum.MozBrowserEvent.html#variant.OpenWindow
We should modify it to use `<iframe>` in all cases instead.

Code: components/msg/constellation_msg.rs

### PR DESCRIPTION
**Pull request by Qeole**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7911)

### CODE REVIEW

**Comment by jdm** [comment]
Thanks!
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/msg/constellation_msg.rs, line 315 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7911#-K02gWqqpL1xSd0MrGkZ)** ([raw file](https://github.com/servo/servo/blob/191a0417e86c0daf316e8fe8feb79e58a2b7e24f/components/msg/constellation_msg.rs#L315)):</sup>
This will cause a similar problem, so let's escape it too.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7911)

**Comment by Qeole** [comment]
That's right, sorry I didn't spot it. I'm correcting the `<menuitem>`.

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7911)

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Comment by jdm** [comment]
@bors-servo: retry
* #7730

**Comment by Qeole** [comment]
@jdm: Many thanks :) I'll try some other bugs now I think.

**Pull request merged**
