### PR TITLE
Fix incremental reflow of text selection changes

### PR DESCRIPTION
**Pull request by mbrubeck**
r? @emilio or @pcwalton

CC @paulrouget: This fixes a bug in the browser.html URL bar auto-completion.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10347)

### CODE REVIEW

**Comment by pcwalton** [comment]
Why do we force relayout here instead of dirtying the node and doing a regular layout?

**Comment by jdm** [comment]
force_relayout is from an older time. All it does is call document.content_changed(self), which just calls node.dirty().

**Comment by pcwalton** [comment]
Let's switch to explicit dirtying then.

**Comment by mbrubeck** [comment]
@pcwalton:
> Let's switch to explicit dirtying then.

Done.

**Comment by pcwalton** [comment]
Looks good, squash if you like and r=me

**Comment by paulrouget** [comment]
> This fixes a bug in the browser.html URL bar auto-completion.

What bug?

**Comment by mbrubeck** [comment]
@bors-servo r=pcwalton

@paulrouget:
> > This fixes a bug in the browser.html URL bar auto-completion.
>
> What bug?

When the URL is auto-completed, the auto-inserted part is selected, but (sometimes?) Servo does not highlight the selection right away.

**Comment by jdm** [comment]
@bors-servo: retry
* #10364

**Pull request merged**
