### PR TITLE
Add missing connection check for disconnect

### PR DESCRIPTION
**Pull request by dati91**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14428)

### CODE REVIEW

**Comment by jdm** [comment]
This looks fine, but no test results appear to be updated and no new tests are being added.

**Comment by dati91** [comment]
This is just an early return. This will only trigger when you call disconnect twice, but should behave the same, because the lower level do the same check.

**Comment by jdm** [comment]
Fair enough.
@bors-servo: r+

**Pull request merged**
