### PR TITLE
Update cssparser

### PR DESCRIPTION
**Pull request by SimonSapin**
---

- [X] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13190)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Updated selectors in `port/cef/Cargo.lock`.

@bors-servo r=Manishearth

**Comment by Manishearth** [comment]
@bors-servo retry p=10

 - #13165

**Comment by SimonSapin** [comment]
@bors-servo retry

* #13059

**Pull request merged**
