### PR TITLE
Convert parent dictionary values when converting dictionaries to JS

### LINKED ISSUE #26928: ToJSVal for webidl dictionaries ignores the parent field
```
dictionary RTCRtpParameters {
  required sequence<RTCRtpHeaderExtensionParameters> headerExtensions;
  required RTCRtcpParameters rtcp;
  required sequence<RTCRtpCodecParameters> codecs;
};

dictionary RTCRtpSendParameters : RTCRtpParameters {
  required DOMString transactionId;
  required sequence<RTCRtpEncodingParameters> encodings;
};
```
When there is code that calls RTCRtpSender.getParameters() which returns RTCRtpSendParameters, we end up with a JS value that only includes `transactionId` and `encodings`, and none of the fields from `RTCRtpParameters`.

### PR DESCRIPTION
**Pull request by jdm**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #26928
- [x] There are tests for these changes OR

### CODE REVIEW

**Comment by CYBAI** [comment]
```
 0:07.83(B /repo/tests/wpt/mozilla/meta/MANIFEST.json  0  error(B  mozilla/dictionary_to_jsval.html in manifest but removed from source.  (wpt-manifest)(B
 0:07.83(B ERROR(B Manifest /repo/tests/wpt/mozilla/meta/MANIFEST.json is outdated, use |./mach update-manifest| to fix.
```

**Comment by jdm** [comment]
The try run passed apart from the missing test file.

**Comment by jdm** [comment]
Review ping @nox.

**Comment by nox** [comment]
Nice.

@bors-servo r+

**Pull request merged**
