### PR TITLE
 Adding cmdling argument for disabling style share cache, fix #5581

### LINKED ISSUE #5581: Add a command-line option to disable style sharing
The style sharing cache is an important but fragile optimization. Bugs in style sharing are often the cause of layout issues. It can be useful to disable style sharing to test whether this is the case.

We should add an option in [`util::opts`](https://github.com/servo/servo/blob/3fb666cf606f835a9ab9165339e34023ab83a358/components/util/opts.rs) to disable style sharing.  Then add code in [`share_style_if_possible`](https://github.com/servo/servo/blob/3fb666cf606f835a9ab9165339e34023ab83a358/components/layout/css/matching.rs#L562) (or related code) to make it never share styles when this option is set.

### PR DESCRIPTION
**Pull request by pgonda**
Let me know if I should fix anything, or how I could implement a test if needed.  I looked at some testing in servo/ports/command_line.rs but it did not seem to apply.

Thanks!

### CODE REVIEW

**Comment by pgonda** [comment]
My mistake, fixed.

**Comment by pcwalton** [comment]
Looks good, squash and I'll r+

**Comment by Ms2ger** [comment]
I left a few nits on critic, if you'd like to address those.

**Comment by pgonda** [comment]
Is there something I need to do for the 'S-needs-squash' label?

**Comment by jdm** [comment]
Yes, that label means you should squash your commits together (using `fixup`) as described in https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ .

**Comment by pgonda** [comment]
Sorry just learning this squash, So it seems like I have made things worse by spreading out my commits so they are no longer at the top of 'git log'.  Should I make a new branch and copy over only a single commit?

**Comment by jdm** [comment]
That might be for the best at this point; I'm not very good at helping people recover from rebases that have gone awry.

**Comment by pgonda** [comment]
Alright, sorry about this.  Is there anyway to switch this pull request with that new branch or shall I create a new one?

**Comment by pgonda** [comment]
Actually I think i got it!

**Comment by Ms2ger** [comment]
Looks like it worked!

@bors-servo: r+

**Pull request merged**
