### PR TITLE
Use GeckoMedia and only that on platforms that support it

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19363)

### CODE REVIEW

**Comment by ferjm** [comment]
You can probably remove [this](https://github.com/nox/servo/blob/8e75c4d30e373bae40b1f40e85cca39604ab213f/components/script/dom/htmlmediaelement.rs#L40) `#[allow(unused_imports)]` as well by importing them in the appropriate platforms only.

I can't r+ with bors-servo, but in any case,  LGTM.

**Comment by philn** [comment]
What's the difference with the previous approach?

**Comment by nox** [comment]
@philn Previous approach made rustc emit a warning about unreachable code.

**Comment by philn** [comment]
Hah, sorry about that :)

**Pull request merged**
