### PR TITLE
layout: Don't try to vertically align absolutely positioned children of table rows.

### PR DESCRIPTION
**Pull request by pcwalton**
Improves http://reddit.com/r/aww.

r? @mbrubeck

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13738)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r-
Run `./mach update-manifest`.

**Comment by jdm** [comment]
Actually, don't do that. Remove the `<link>` from the reference file, instead.

**Comment by KiChjang** [comment]
@bors-servo retry
* #13360

**Pull request merged**
