### PR TITLE
Add form getters for additional elements; update test expectations

### PR DESCRIPTION
**Pull request by aopicier**
This adds form getters for fieldset, label, object, output, select and
textarea elements.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7760)

### CODE REVIEW

**Comment by aopicier** [comment]
Unfortunately
`[HTMLObjectElement interface: document.createElement("object") must inherit property "form" with the proper type (5)]`
in ` tests/wpt/metadata/html/dom/interfaces.html.ini` still fails. Gecko doesn't pass this test either. @Manishearth, do you happen to have an idea what is going on there?

**Comment by Manishearth** [comment]
This is happening because `typeof document.createElement("object") == "function"`. This is strange, because for every other element, the type is "object".

**Comment by Manishearth** [comment]
...but that doesn't happen for Servo. Not sure what the bug there is.

**Comment by Manishearth** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1208948 for Gecko. Now let's figure out what's going on in Servo.

**Comment by Manishearth** [comment]
The bug is something to do with legacycaller. All similar interface tests for `<object>` will fail.

https://bugzilla.mozilla.org/show_bug.cgi?id=1208948#c3

**Comment by Manishearth** [comment]
@bors-servo r+

I'd also like to refactor the `FormControl` trait so that we no longer need any impl body. Remove the lifetime parameter and add a dependence on `ElementBase`

If we change it to

```
trait FormControl: ElementBase {
 fn as_element(&self) -> &Element {
   ElementCast::to_ref(self)
 }

}
```
make sure all of its othermethods take `&self` instead of `self` (http://doc.servo.org/script/dom/htmlformelement/trait.FormControl.html),
 then making something into a form control simply becomes `impl FormControl for HTMLFooElement {}`.

(This wasn't possible back when `FormControl` was created since we had impls on `&T` instead of `T`, so the trait bound couldn't be expressed easily)

**Comment by Manishearth** [comment]
```
PASS expected FAIL The form attribute must return the fieldset's form owner
/html/semantics/forms/the-label-element/label-attributes.html
```

**Comment by aopicier** [comment]
I'll update the test expectations later today. I will then look at the refactoring you mentioned in a new branch.

**Pull request merged**
