### PR TITLE
net: Convert the storage task to use IPC.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6746)

### CODE REVIEW

**Comment by jdm** [comment]
I've filed #6748 for the other failure, but the sessionstorage one doesn't look great:
```
15:26.27 TEST_START: Thread-TestrunnerManager-3 /webstorage/storage_session_setitem_quotaexceedederr.html
15:26.91 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) Full command: /home/servo/buildbot/slave/linux2/build/target/release/servo --cpu --hard-fail -u Servo/wptrunner -z http://localhost:8000/webstorage/storage_session_setitem_quotaexceedederr.html
(pid:20190) "thread 'StorageManager' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:731"
15:26.91 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "stack backtrace:"
15:26.97 TEST_START: Thread-TestrunnerManager-2 /webstorage/storage_setitem.html
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   1:     0x7f4519690c0e - sys::backtrace::write::hfe027f56cae344aapps"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   2:     0x7f45196942f5 - panicking::on_panic::hcd0100c6199f27b1Cax"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   3:     0x7f451968144e - rt::unwind::begin_unwind_inner::h0544b2c664549c40gQw"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   4:     0x7f4519681e3c - rt::unwind::begin_unwind_fmt::h5a900a56c2bf32ccmPw"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   5:     0x7f4519693ce6 - rust_begin_unwind"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   6:     0x7f45196c5f04 - panicking::panic_fmt::h205f328075c6fc3cneC"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   7:     0x7f45192396c5 - storage_task::StorageManager::set_item::hfc759e6b8e51a6b6Qjh"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   8:     0x7f4519218c23 - storage_task::StorageManager::start::h53339f6b08bdf104Qfh"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   9:     0x7f4519216c99 - boxed::F.FnBox<A>::call_box::h4595495699940709238"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  10:     0x7f4519154859 - rt::unwind::try::try_fn::h2865232542721131979"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  11:     0x7f45196992a8 - rust_try_inner"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  12:     0x7f4519699295 - rust_try"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  13:     0x7f451968e6a7 - rt::unwind::try::inner_try::h63857c7efe7ef4ac9Lw"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  14:     0x7f4519154a61 - boxed::F.FnBox<A>::call_box::h18354446438596922915"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  15:     0x7f4519692e31 - sys::thread::Thread::new::thread_start::hb94dd6e8abd80527WVv"
15:27.08 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  16:     0x7f45178c4181 - start_thread"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  17:     0x7f45170d447c - __clone"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  18:                0x0 - <unknown>"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "thread 'StorageManager' panicked at 'assertion failed: libc::close(self.fd) == 0', /home/servo/.cargo/git/checkouts/ipc-channel-d95a23d1f1577bfc/master/platform/linux/mod.rs:96"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "stack backtrace:"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   1:     0x7f4519690c0e - sys::backtrace::write::hfe027f56cae344aapps"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   2:     0x7f45196942f5 - panicking::on_panic::hcd0100c6199f27b1Cax"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   3:     0x7f451968144e - rt::unwind::begin_unwind_inner::h0544b2c664549c40gQw"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   4:     0x7f45196259b1 - rt::unwind::begin_unwind::h2792297208790152528"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   5:     0x7f451961f95a - platform::linux::UnixSender.Drop::drop::h69f1598da158384fFHa"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   6:     0x7f45192397e0 - storage_task::StorageManager::set_item::hfc759e6b8e51a6b6Qjh"
15:27.09 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   7:     0x7f4519218c23 - storage_task::StorageManager::start::h53339f6b08bdf104Qfh"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   8:     0x7f4519216c99 - boxed::F.FnBox<A>::call_box::h4595495699940709238"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "   9:     0x7f4519154859 - rt::unwind::try::try_fn::h2865232542721131979"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  10:     0x7f45196992a8 - rust_try_inner"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  11:     0x7f4519699295 - rust_try"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  12:     0x7f451968e6a7 - rt::unwind::try::inner_try::h63857c7efe7ef4ac9Lw"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  13:     0x7f4519154a61 - boxed::F.FnBox<A>::call_box::h18354446438596922915"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  14:     0x7f4519692e31 - sys::thread::Thread::new::thread_start::hb94dd6e8abd80527WVv"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  15:     0x7f45178c4181 - start_thread"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  16:     0x7f45170d447c - __clone"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "  17:                0x0 - <unknown>"
15:27.10 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:20190) "thread panicked while panicking. aborting."
15:27.11 CRASH: Thread-TestrunnerManager-3 pid:24088. Test:None. Minidump anaylsed:False. Signature:[/webstorage/storage_session_setitem_quotaexceedederr.html]

15:27.11 TEST_END: Thread-TestrunnerManager-3 CRASH, expected TIMEOUT
```

**Comment by pcwalton** [comment]
Quota exceeded problem. I will investigate but I wouldn't be surprised if it's just that we don't implement quota.

**Comment by jdm** [comment]
Our choices here are to disable the test or figure out why a `send` over an IPCChannel is returning an Err value. Implementing the quota check in order to make the test pass is working around the problem.

**Comment by jdm** [comment]
Note that the `send` that is failing is going from the storage task to the script task. The quota thing shouldn't be an issue here unless we happen to be triggering an OOM situation that ipc-channel is hitting or something.

**Comment by pcwalton** [comment]
Seems to be platform-specific in Linux. I suspect fragmentation/reassembly code.

**Comment by pcwalton** [comment]
The problem here is that we're running out of file descriptors. I'll search for leaks. There's now an open possibility that this is not a bug we can do anything about, though.

**Comment by pcwalton** [comment]
So I fixed a leak in ipc-channel, but the same problem persists. I think what may be happening is that this test sends `setItem()` messages in a loop. Each one of those `SetItem` messages creates a pair of file descriptors to receive the messages. Without any backpressure, the sender can create file descriptors faster than the receiver can respond to the messages and close them, causing file descriptor exhaustion! Fascinating.

**Comment by pcwalton** [comment]
Leak found and fixed.

**Comment by jdm** [comment]
Thanks for investigating that, @pcwalton!

**Pull request merged**
