### PR TITLE
Split out shared networking code into net_traits crate

### LINKED ISSUE #4476: Split out shared networking code into net_traits crate
There are parts of the net crate that are independent of the rest of Servo (like the implementation of the loaders, the forthcoming HTTP cache, the forthcoming cookie code, etc.) and it is really frustrating to recompile the script crate every time the code in net is touched. We can do better than this if we split the bits that script and layout need into a net_traits crate that the net crate depends upon.

### PR DESCRIPTION
**Pull request by gilles-leblanc**
Fixes #4476

### CODE REVIEW

**Comment by jdm** [comment]
Exciting!

**Comment by metajack** [comment]
Assigned @jdm who did the review.

**Comment by Manishearth** [comment]
(needs rebase)

**Comment by gilles-leblanc** [comment]
I've just rebased locally. I'll keep rebasing while the review is ongoing.

**Comment by jdm** [comment]
Lovely!

**Comment by gilles-leblanc** [comment]
The review has been accepted, the commits have been squashed, the code has been rebased on the latest master, I have ran the tests locally.

This is ready to be merged!

**Comment by jdm** [comment]
I'm super excited!

**Comment by jdm** [comment]
```
src/lib.rs:41:29: 41:43 error: unresolved import `net::image_cache_task::ImageCacheTask`. There is no `ImageCacheTask` in `net::image_cache_task`
src/lib.rs:41 use net::image_cache_task::{ImageCacheTask, LoadPlaceholder};
                                          ^~~~~~~~~~~~~~
```
Also, let's fix
```
/home/servo/buildbot/slave/gonk/build/components/net/resource_task.rs:23:5: 23:13 warning: unused import, #[warn(unused_imports)] on by default
/home/servo/buildbot/slave/gonk/build/components/net/resource_task.rs:23 use url::Url;
                                                                             ^~~~~~~~
/home/servo/buildbot/slave/gonk/build/components/servo/lib.rs:118:51: 118:62 warning: use of unstable library feature 'path'
/home/servo/buildbot/slave/gonk/build/components/servo/lib.rs:118                 => url::Url::from_file_path(&*cwd.join(&*url)).unwrap(),
                                                                                                                    ^~~~~~~~~~~
/home/servo/buildbot/slave/gonk/build/components/servo/lib.rs:118:62: 118:62 help: add #![feature(path)] to the crate attributes to silence this warning
```
at the same time.

**Comment by gilles-leblanc** [comment]
@jdm Regarding the second one, it's used in the tests in the same file so the test don't compile if I remove it.

**Comment by gilles-leblanc** [comment]
I'll check into compiling the gonk port.

**Comment by Manishearth** [comment]
Don't bother. I don't think we have the B2G tarball up on a public-facing server, and without that the build is rather painful (and still requires a device, I think). I could pick it up from the build machines and send it to you but I think it's best you wait till @larsbergstrom makes an official tarball.

In the meantime, I'll try to build and fix it locally.

**Comment by Manishearth** [comment]
Oh, hey, we do!

https://servo-rust.s3.amazonaws.com/B2G/B2G.tgz

Download that, unpack it, and follow the instructions in the [readme](https://github.com/servo/servo/blob/master/ports/gonk/README.md). You don't need to run the "Build B2G" steps since you already have the built package.

I'll still try to fix this myself unless you want to; since it's still going to be a lot of downloading and compiling for you.

**Comment by Manishearth** [comment]
Cherry pick https://github.com/servo/servo/commit/00adc98e9f67ff57cb1210e3bca96f4faa212132

**Comment by gilles-leblanc** [comment]
@Manishearth Thanks, that's hugely appreciated. I was going away from the weekend and next week promises to be hectic at work. I was wondering when I was going to be doing this. Thanks again :)

**Comment by gilles-leblanc** [comment]
@jdm Let's give it another shot! I have integrated Manishearth's corrections.

**Pull request closed without merging**
