### PR TITLE
Correct the match urls for the white-space tests.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8185)

### CODE REVIEW

**Comment by Ms2ger** [comment]
CC @eefriedman

**Comment by frewsxcv** [comment]
@bors-servo retry

#7787

**Comment by jdm** [comment]
@bors-servo: retry
* 8189

**Comment by jdm** [comment]
@bors-servo: retry
* #8191 and #7731

**Pull request merged**
