### PR TITLE
Webgl tests

### PR DESCRIPTION
**Pull request by dzbarsky**
The relevant parts are python/servo/test_commands.py - any advice for making this more robust would be appreciated (after running the entire testsuite, there were about 20 hanging servo processes that I had to kill manually to get the results).

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9015)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I have no interest in taking a separate framework for webgl tests. These tests should be submitted to wpt.

**Comment by jdm** [comment]
I'm interested in establishing ASAP if that's actually practical and will be accepted by all parties. If so, we can hold off on this. If not, I would like to actually get our webgl code tested.

**Comment by frewsxcv** [comment]
Looking at `test-tidy` results, if this is on the path to get merged, you'll probably want to add the upstream python code to this blacklist:

https://github.com/servo/servo/blob/master/python/tidy.py#L24-L35

**Comment by jdm** [comment]
Given our attempts to move forward with https://github.com/w3c/web-platform-tests/pull/2449, this doesn't need to remain open right now. Thanks for kicking things off, @dzbarsky!

**Pull request closed without merging**
