### PR TITLE
Build Servo on Travis

### LINKED ISSUE #6962: Build servo on travis
Right now, [travis just executes `mach make-tidy`](https://github.com/servo/servo/blob/master/.travis.yml)

Is there any reason we don't have travis also build servo? It seems like that could reduce some of the churn for pull requests that fail to compile immediately after they get r+'d.

[rust-lang/rust recently updated their travis config to compile stage1](https://github.com/rust-lang/rust/pull/27028)

### PR DESCRIPTION
**Pull request by frewsxcv**
Closes #6962

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7915)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Okay, this is ready to be reviewed. I learned that Travis CI runs on Ubuntu 12.04, which has a relatively old (and compatible) version of libc. I thought about making libc compilation part of the build process but figured that would take too long. I noticed rust-lang/rust uses Docker to build on Travis. I decided to try that and fairly satisfied with how it turned out.

**Comment by jdm** [comment]
:joy_cat:

**Comment by Ms2ger** [comment]
Can you try it with `sudo: 9000`?

**Comment by frewsxcv** [comment]
Is `sudo: 9000` documented somewhere?

**Comment by larsbergstrom** [comment]
No. It lets us try a bigger instance type (and was passed on to us by the kind folks at Travis).

**Comment by frewsxcv** [comment]
Alright, running with that now. Purposely made a new commit to compare runtime duration with the non-9000 build

**Comment by jdm** [comment]
Shaved a whole 13 seconds off the build :)

**Comment by larsbergstrom** [comment]
I'll ask the Travis folks about that :-)

**Comment by frewsxcv** [comment]
Any reason to hold off on merging this until then? i.e. What are the next steps here?

**Comment by larsbergstrom** [comment]
Nope! I'd say squash and r=me.

CC @edunham (since we were talking about some Travis stuff recently)

**Pull request merged**
