### PR TITLE
Update README.md

### LINKED ISSUE #21446: Download linux gstreamer binaries during mach build
Telling people to execute [these steps](https://github.com/servo/servo/blob/master/.travis.yml#L20-L22) manually isn't a great solution if their distribution doesn't have a recent gstreamer available. It would be nice if we could make it Just Work by downloading those binaries automatically, similar to the way we acquire openssl for android builds.

### PR DESCRIPTION
**Pull request by PsiACE**
add `gstreamer` to `dnf install`

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes not fix #21446, but help to compile.

- [x] There are tests for these changes OR
- [x] These changes do not require tests because it only change README.md

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21499)

### CODE REVIEW

**Comment by PsiACE** [comment]
@jdm Please help with this request.

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by jdm** [comment]
@bors-servo retry
* #20734 #13492

**Pull request merged**
