### PR TITLE
Fix slowness in macos copy_dependencies

### LINKED ISSUE #29764: copy_dependencies makes macOS build slow and confusing
The changes to copy all dependencies and rewrite them to relative paths causes my build to take an extra minute beyond what the build claims it took (`Finished dev [unoptimized + debuginfo] target(s) in 2m 49s`), and it displays no output while that happens.

### PR DESCRIPTION
**Pull request by mukilan**
The `copy_dependencies` logic is invoking `change_non_system_libraries_path` with absolute paths to gstreamer *plugin dylibs*.
`change_non_system_libraries_path` skips editing links in servo binary to relocatable dylibs, but the since the plugins have absolute paths, they are treated as 'non-relocable' and it will try to edit the *non-existent* link (since plugins are loaded dynamically) in servo bin . These unnecessary calls to change_link_name is the cause of the slowness identified in #29764 

This PR fixes the issue by ensuring plugin dylibs are not passed to the first call to change_non_system_libraries_path that patches the links in the main servo binary.

With this fix, the time taken by copy_dependencies is reduced to ~3 seconds on my system.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #29764 

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they fix slowness in build step

### CODE REVIEW

**Comment by mukilan** [comment]
I think I can just move the call to change_non_system_libraries_path up to skip the plugins. I'll test it out and update the PR.

**Review by mrobinson — APPROVED** [review]
This seems like a good workaround until we can move this into the packaging step.

**Comment by mukilan** [comment]
@bors-servo r=mrobinson

Thanks for the review!

**Pull request merged**
