### PR TITLE
fix collapsing margins fallthrough calculations

### LINKED ISSUE #18811: Twitter homepage tabs don't fill boxes
Firefox:
screen shot 2017-10-10 at 2 15 23 pm

Servo:
screen shot 2017-10-10 at 2 16 30 pm

### PR DESCRIPTION
**Pull request by bobthekingofegypt**
Margins that should not collapse through where still effecting the layout
of subsequent elements

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #18811 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19386)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo try

 * I'd consider to put those tests outside of the `mozilla/` folder so they get upstreamed and other browsers benefit from them too.

**Comment by bobthekingofegypt** [comment]
I'm not sure why the android build failed there.

@emilio Could you tell me what the convention is for test locations and under what conditions?
I just assumed we were sticking everything in mozilla.

**Comment by emilio** [comment]
@bors-servo retry

 * The build failure looks intermittent.

In general if there's a spec that justifies the test, and the test applies to other browsers (doesn't use anything servo-specific) it should be in the upstream directory.

**Comment by bobthekingofegypt** [comment]
@emilio by upstream folder you mean tests/wpt/web-platform-tests?

**Comment by emilio** [comment]
> @emilio by upstream folder you mean tests/wpt/web-platform-tests?

Yes

**Comment by emilio** [comment]
@bors-servo try

Very sorry for dropping the ball on this one, totally forgot about it.

**Comment by emilio** [comment]
Test results seem relevant, two unexpected passes, two unexpected failures:

```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/CSS2/css1/c5505-mrgn-003.xht", "line": 2684, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/CSS2/margin-padding-clear/margin-collapse-159.xht", "line": 7499, "action": "test_result", "expected": "FAIL"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/margin-padding-clear/margin-collapse-019.xht c6ded7799ea01b2c1468b4b29d10c892fc7738eb\n/css/CSS2/margin-padding-clear/margin-collapse-002-ref.xht ed4434ae09ef1b67111da16389c90ba2cd98db6a\nTesting c6ded7799ea01b2c1468b4b29d10c892fc7738eb == ed4434ae09ef1b67111da16389c90ba2cd98db6a", "stack": null, "subtest": null, "test": "/css/CSS2/margin-padding-clear/margin-collapse-019.xht", "line": 8309, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/margin-padding-clear/margin-collapse-016.xht c6ded7799ea01b2c1468b4b29d10c892fc7738eb\n/css/CSS2/margin-padding-clear/margin-collapse-002-ref.xht ed4434ae09ef1b67111da16389c90ba2cd98db6a\nTesting c6ded7799ea01b2c1468b4b29d10c892fc7738eb == ed4434ae09ef1b67111da16389c90ba2cd98db6a", "stack": null, "subtest": null, "test": "/css/CSS2/margin-padding-clear/margin-collapse-016.xht", "line": 39650, "action": "test_result", "expected": "PASS"}
```

**Comment by jdm** [comment]
@bors-servo retry
* #20796

**Comment by jdm** [comment]
Ack, wrong PR. Sorry :<

**Comment by dralley** [comment]
A working version of this patch, rebased:

```rust
diff --git a/components/layout/block.rs b/components/layout/block.rs
index 4b0999489e..3999b6e1af 100644
--- a/components/layout/block.rs
+++ b/components/layout/block.rs
@@ -1141,6 +1141,7 @@ impl BlockFlow {
             // Add in our block-end margin and compute our collapsible margins.
             let can_collapse_block_end_margin_with_kids = margins_may_collapse ==
                 MarginsMayCollapseFlag::MarginsMayCollapse &&
+                *self.fragment.style.content_block_size() == Size::Auto &&
                 !self
                     .base
                     .flags
diff --git a/components/layout/model.rs b/components/layout/model.rs
index 08f916142e..9cb5e35ec0 100644
--- a/components/layout/model.rs
+++ b/components/layout/model.rs
@@ -177,8 +177,7 @@ impl MarginCollapseInfo {
                 },
                 FinalMarginState::BottomMarginCollapses => {
                     let advance = self.margin_in.collapse();
-                    self.margin_in
-                        .union(AdjoiningMargins::from_margin(block_end_margin));
+                    self.margin_in = AdjoiningMargins::from_margin(block_end_margin);
                     (
                         CollapsibleMargins::Collapse(self.block_start_margin, self.margin_in),
                         advance,
```

**Comment by jdm** [comment]
@dralley What does "working" mean in this case?

**Comment by dralley** [comment]
Working means that it compiles and fixes the test snippet from the issue that is linked from this PR:

https://github.com/servo/servo/issues/18811#issuecomment-335582511

Although that doesn't mean it doesn't break anything else.

**Comment by mrobinson** [comment]
Thank you for your change. The legacy layout system is moving into maintenance mode so it's unlikely that the Servo project will integrate legacy-layout-only changes.

**Pull request closed without merging**
