### PR TITLE
Enable cors/ directory for WPT.

### PR DESCRIPTION
**Pull request by jdm**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9018)

### CODE REVIEW

**Comment by KiChjang** [comment]
```
Ran 3753 tests finished in 870.0 seconds.
  • 3752 ran as expected. 708 tests skipped.
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: *_http://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:90:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Allow origin: [tab]*
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldPass@http://web-platform.test:8000/cors/remote-origin.htm:49:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:56:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: *http://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:89:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://www1.web-platform.test:8000:80
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:75:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: HTTP://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:79:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://www1.web-platform.test:8000%23
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:74:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: null
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:95:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: ://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:64:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://web-platform.test:8000/cors/
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:98:1

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://www1.web-platform.test:8000_/
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:72:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: *\\0
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:84:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: \\0http://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:92:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: -
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:81:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://example.net
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:94:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: '*'
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:85:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: *_*
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:87:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http:/www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:67:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: "*"
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:86:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://www1.web-platform.test:8000,_*
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:76:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://www1.web-platform.test:8000/
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:71:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: \\0*
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:83:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Allow origin: _*__
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldPass@http://web-platform.test:8000/cors/remote-origin.htm:49:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:55:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://www1.web-platform.test:8000\\0
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:77:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: *,_http://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:91:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Allow origin: http://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldPass@http://web-platform.test:8000/cors/remote-origin.htm:49:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:57:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:62:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://www1.web-platform.test:8000/cors/
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:99:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://WWW1.WEB-PLATFORM.TEST:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:80:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Allow origin: [tab]http://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldPass@http://web-platform.test:8000/cors/remote-origin.htm:49:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:60:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: //www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:63:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http:www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:68:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Allow origin: _http://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldPass@http://web-platform.test:8000/cors/remote-origin.htm:49:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:58:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://www1.web-platform.test:8000#
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:73:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: ftp://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:65:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://web-platform.test:8000/cors/remote-origin.htm
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:97:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Allow origin: _http://www1.web-platform.test:8000___[tab]_
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldPass@http://web-platform.test:8000/cors/remote-origin.htm:49:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:59:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: *http://*
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:88:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: HTTP://WWW1.WEB-PLATFORM.TEST:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:78:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:69:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: 
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:96:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http://www1.web-platform.test:8000?
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:70:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: **
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:82:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: http:://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:66:5

  ▶ Unexpected subtest result in /cors/remote-origin.htm:
  │ FAIL [expected PASS] Disallow origin: null_http://www1.web-platform.test:8000
  │   → iframe.contentWindow is null
  │ 
  │ reverseOrigin/<@http://web-platform.test:8000/cors/remote-origin.htm:25:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ reverseOrigin@http://web-platform.test:8000/cors/remote-origin.htm:21:5
  │ shouldFail@http://web-platform.test:8000/cors/remote-origin.htm:50:31
  └ iframe.onload@http://web-platform.test:8000/cors/remote-origin.htm:93:5
```

**Comment by jdm** [comment]
Looks like remote-origin.html sometimes crashes and sometimes runs to completion.

**Comment by jdm** [comment]
Huh, a debug mozjs build yields different behaviour on this test than a non-debug mozjs. How unusual.

**Comment by jdm** [comment]
@bors-servo: retry
* #9091

**Comment by nox** [comment]
@bors-servo r=Manishearth force

Sorry about that.

**Comment by Ms2ger** [comment]
@bors-servo clean r=Manishearth

Sorry!

**Pull request merged**
