### PR TITLE
Enable some mach commands to be run with python3

### PR DESCRIPTION
**Pull request by marmeladema**
This change finally enable the following commands to be run with python3:
* `build`
* `test-unit`
* `package`

As previously explained, `test-tidy` will require more work in the wpt repository directly. Maybe `test-tidy --no-wpt` is achievable relatively quickly though.

For possible remaining bits that might need to be worked on, see https://github.com/servo/servo/issues/23607

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes

### CODE REVIEW

**Comment by marmeladema** [comment]
Friendly ping @SimonSapin :-) Is there any concern about this PR?

**Comment by jdm** [comment]
Review ping @SimonSapin.

**Comment by SimonSapin** [comment]
Sorry for the delay! The diff looks good

@bors-servo try=linux

**Comment by SimonSapin** [comment]
The Tidy+Unit task failed with:

```
$ python3 ./mach build --dev
Python virtualenv is not installed. Please install it prior to running mach.
```

It looks like `python/mach_bootstrap.py` wants to *import* virtualenv (so using the same Python version as itself), not just run a `virtualenv` executable.

Try adding `virtualenv` among the APT packages installed in `etc/taskcluster/docker/base.dockerfile`?

**Comment by SimonSapin** [comment]
> Try adding `virtualenv` among the APT packages installed in `etc/taskcluster/docker/base.dockerfile`?

Actually it looks like I can do this for you. I took the liberty of pushing to your branch.

@bors-servo r=linux

**Comment by SimonSapin** [comment]
Err

@bors-servo r- try=linux

**Comment by SimonSapin** [comment]
https://community-tc.services.mozilla.com/tasks/CKazBdxJSTejY8R7TEPZgA/runs/0/logs/live/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FCKazBdxJSTejY8R7TEPZgA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

```
$ python3 ./mach build --dev
"/repo/python/_virtualenv3.6/bin/python" "-m" "pip" "install" "-I" "-r" "/repo/tests/wpt/web-platform-tests/tools/wptrunner/requirements_firefox.txt" failed with error code 1:
Output:
Traceback (most recent call last):
  File "./mach", line 103, in <module>
    main(sys.argv)
  File "./mach", line 33, in main
    mach = mach_bootstrap.bootstrap(topdir)
  File "/repo/python/mach_bootstrap.py", line 274, in bootstrap
    _activate_virtualenv(topdir, is_firefox)
  File "/repo/python/mach_bootstrap.py", line 204, in _activate_virtualenv
    _process_exec([python, "-m", "pip", "install", "-I", "-r", req_path])
  File "/repo/python/mach_bootstrap.py", line 109, in _process_exec
    shutil.copyfileobj(out, sys.stdout)
  File "/usr/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
TypeError: write() argument must be str, not bytes
```

**Comment by marmeladema** [comment]
Sorry, i kind of forgot about this. I just rebased over master and try to understand whats wrong.

**Comment by marmeladema** [comment]
@SimonSapin or @jdm could you trigger the tests that are using python3? try=linux should be enough

**Comment by marmeladema** [comment]
Sorry to bother you @jdm but could you run it again? I fixed some compatibility problems in some mach bootstrap error code path and i'd like to understand whats the real underlying error

**Comment by marmeladema** [comment]
It appears there is a problem when installing `psutil` module because `Python.h` is missing for Python3. Most likely a package like `libpython3-dev` is missing.

**Comment by marmeladema** [comment]
@jdm i am really sorry, but could you run it again? I should have installed the correct packages now

**Comment by jdm** [comment]
@bors-servo try=linux
No need to be sorry :)

**Comment by marmeladema** [comment]
@jdm could you run it again please? I have no idea how many times i will have to ask you :/

**Comment by marmeladema** [comment]
Could you also try=linux? I don't think wpt will run the `linux_tidy_unit` tests.

**Comment by jdm** [comment]
Ugh, sorry. That was just habit.
@bors-servo try=linux retry

**Comment by marmeladema** [comment]
@SimonSapin `linux` tests have passed :+1:

**Review by SimonSapin — APPROVED** [review]
Nice! Thank you for persevering.

The overall diff looks good. Do you think each commit makes sense individually, or should some of them be squashed?

**Comment by marmeladema** [comment]
> Nice! Thank you for persevering.

Yeah, was quite a journey to get there and most of the work for WPT has not even started ...

> The overall diff looks good. Do you think each commit makes sense individually, or should some of them be squashed?

I think they make sense individually as they each fix a compatibility issue.

**Comment by SimonSapin** [comment]
Sounds good!

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo r-
```
Error running mach:
    ['package', '--dev', '--target', 'aarch64-uwp-windows-msvc', '--uwp=arm64']
The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.
If filing a bug, please include the full output of mach, including this error
message.
The details of the failure are as follows:
RuntimeError: ZipFile() requires mode "r", "w", or "a"
  File "C:\Users\task_1575984934\repo\python\servo\package_commands.py", line 237, in package
    build_uwp(uwp, dev, vs_info['msbuild'])
  File "C:\Users\task_1575984934\repo\python\servo\package_commands.py", line 775, in build_uwp
    archive_deterministically(artifacts_dir, zip_path, prepend_path='servo/')
  File "C:\Users\task_1575984934\repo\python\servo\command_base.py", line 115, in archive_deterministically
    with zipfile.ZipFile(temp_file, 'wb', zipfile.ZIP_DEFLATED) as zip_file:
  File "C:\Users\task_1575984934\python2\lib\zipfile.py", line 729, in __init__
    raise RuntimeError('ZipFile() requires mode "r", "w", or "a"')
```

**Comment by jdm** [comment]
@bors-servo retry

FYI @marmeladema, if there has been no new push since the last try job, the retry command is needed to initiate a new try job.

**Comment by marmeladema** [comment]
Oh ok thanks, i wanted to try on both linux (because its the builds that use python3) and windows (because its the builds that broke earlier).

**Comment by marmeladema** [comment]
Tests have passed for both linux and windows. I think we can try to merge again :+1:

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
* #24715

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Pull request merged**
