### PR TITLE
Dispatch load events for cross origin iframes. Resolves #6672.

### LINKED ISSUE #6672: Cross origin iframes don't trigger a load event in the parent frame element
This happens because BrowsingContext::frame_element called by Document::dispatch_load can't handle cross-origin parent frames.

Probably requires #5242.

### PR DESCRIPTION
**Pull request by jdm**
Splitting it out from #6677.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8558)

### CODE REVIEW

**Comment by jdm** [comment]
Alright, this passes all tests on try.
r? @Ms2ger

**Comment by jdm** [comment]
r? @glennw 
It occurs to me that this is more in your ballpark.

**Comment by glennw** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[components/script/script_task.rs, line 995 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8558#-K3RFYOSvBFK6C2iDkqM:-K3RFYOSvBFK6C2iDkqN:-471396235) ([raw file](https://github.com/servo/servo/blob/723af3063a2ec9128c4e468121344714eef6f268/components/script/script_task.rs#L995)):_
It's feels like it would be easy to mess up the order of pipeline vs. parent pipeline IDs (not just here, but as a general problem).

Is it worth adding a struct that we progressively switch constellation / script messages over to using?

Something like:

struct PipelineInfo {
  id: PipelineId,
  parent: Option<PipelineId>
}

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8558)_

**Comment by glennw** [comment]
@jdm Just one question - otherwise looks good to me.

**Comment by jdm** [comment]
Such a struct doesn't always make sense, since in some cases you always want a parent and it's annoying to introduce `unwrap` into users. I can definitely use a struct variant with meaningful names here.

**Comment by jdm** [comment]
Updated.

**Comment by KiChjang** [comment]
```
Ran 3717 tests finished in 200.0 seconds.
  • 3716 ran as expected. 711 tests skipped.
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /XMLHttpRequest/send-content-type-string.htm:
  │ FAIL [expected PASS] XMLHttpRequest: send() - Content-Type 1
  │   → assert_equals: expected "text/html;charset=UTF-8" but got "NO"
  │ FAIL [expected PASS] XMLHttpRequest: send() - Content-Type 2
  │   → assert_equals: expected "application/xml;charset=UTF-8" but got "NO"
  │ 
  │ request/<@http://web-platform.test:8000/XMLHttpRequest/send-content-type-string.htm:6:11
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ request@http://web-platform.test:8000/XMLHttpRequest/send-content-type-string.htm:2:9
  │ init@http://web-platform.test:8000/XMLHttpRequest/send-content-type-string.htm:10:27
  └ load@http://web-platform.test:8000/XMLHttpRequest/send-content-type-string.htm:0:1
```

**Comment by jdm** [comment]
The new failures are caused by us now running code in the test for the first time, since it's triggered by an onload event for a data: iframe. Marking as expected fail and relanding.

**Pull request merged**
