### PR TITLE
Implement access to CSSStyleRule for stylo

### PR DESCRIPTION
**Pull request by upsuper**
This is the servo part of [bug 1307357](https://bugzilla.mozilla.org/show_bug.cgi?id=1307357) which has been reviewed by @heycam, @Manishearth and @SimonSapin.

r? @heycam 

(`./mach test-tidy` reports several issues on bindings.rs... which I don't think is introduced by my patch... so I have no idea what to do here...)

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14330)

### CODE REVIEW

**Comment by upsuper** [comment]
It seems although `./mach test-tidy` complains, `./mach test-tidy --all` doesn't.

**Comment by upsuper** [comment]
It seems bindings.rs is not synced properly... Fixing...

**Comment by heycam** [comment]
@upsuper delegate+

**Comment by bholley** [comment]
#14337

**Comment by upsuper** [comment]
@bors-servo retry
* #14221

**Comment by upsuper** [comment]
@bors-servo retry
* #14317

**Pull request merged**
