### PR TITLE
Allow multiple webrender external and output image handlers

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23534)

### CODE REVIEW

**Comment by jdm** [comment]
Lots of crashes in webgl tests according to buildbot.

**Comment by ferjm** [comment]
FWIW these crashes do not appear localy. I suspect that they may be happening on CI because registration/unregistration requests are handled by the main loop, which is not very fast, and makes the whole external/output images processing prone to race conditions. Moving registration/unregistration handling to its own dedicated event loop might help.

**Comment by jdm** [comment]
Example of the crashes:
```
  ▶ CRASH [expected OK] /_webgl/conformance2/programs/active-built-in-attribs.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.3.0-devel
  │ 
  │ (servo:119228): GStreamer-WARNING **: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
  │ 0:00:00.015324232 119228 0x5584362d5730 WARN      GST_PLUGIN_LOADING gstplugin.c:793:_priv_gst_plugin_load_file_for_registry: module_open failed: libmms.so.0: cannot open shared object file: No such file or directory
  │ 
  │ (servo:119228): GStreamer-WARNING **: Failed to load plugin '/home/servo/gst/lib/gstreamer-1.0/libgstmms.so': libmms.so.0: cannot open shared object file: No such file or directory
  │ 0:00:00.015490893 119228 0x5584362d5730 WARN      GST_PLUGIN_LOADING gstplugin.c:793:_priv_gst_plugin_load_file_for_registry: module_open failed: libfaad.so.2: cannot open shared object file: No such file or directory
  │ 
  │ (servo:119228): GStreamer-WARNING **: Failed to load plugin '/home/servo/gst/lib/gstreamer-1.0/libgstfaad.so': libfaad.so.2: cannot open shared object file: No such file or directory
  │ internal error: entered unreachable code (thread WebGLThread, at components/canvas_traits/webgl_channel/mpsc.rs:58)
  │ stack backtrace:
  │    0:     0x5584327dea5d - backtrace::backtrace::trace::hebbee589b71fa4b4
  │    1:     0x5584327dd8c2 - backtrace::capture::Backtrace::new::h3b7bdb995a2c2ecf
  │    2:     0x55842f6e46bf - servo::main::{{closure}}::h7767211f6ae29295
  │    3:     0x5584329bee58 - rust_panic_with_hook
  │                         at src/libstd/panicking.rs:478
  │    4:     0x558431da74f4 - std::panicking::begin_panic::h77437327717371bc
  │    5:     0x558431df02d8 - <canvas_traits::webgl_channel::mpsc::WebGLSender<T> as serde::ser::Serialize>::serialize::h1ea926b675b0629f
  │    6:     0x558431df7920 - canvas_traits::webgl_channel::_IMPL_SERIALIZE_FOR_WebGLSender::<impl serde::ser::Serialize for canvas_traits::webgl_channel::WebGLSender<T>>::serialize::hc0e98369c20161c6
  │    7:     0x558431e02d0d - gl_traits::_IMPL_SERIALIZE_FOR_WebrenderImageHandler::<impl serde::ser::Serialize for gl_traits::WebrenderImageHandler>::serialize::ha4b7eeb4f8c7d144
  │    8:     0x558431cef7ed - bincode::serialize_into::h08453bc8292ae6d0
  │    9:     0x558431e24190 - std::thread::local::LocalKey<T>::with::hd5fbcd129f6997b9
  │   10:     0x558431ce7d30 - ipc_channel::ipc::IpcSender<T>::send::he03559d679acb5cf
  │   11:     0x558431d959fa - canvas::webgl_thread::WebGLThread<VR>::handle_update_wr_image::hbf3fcb61f67cc51b
  │   12:     0x558431da6648 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc49770713520676d
  │   13:     0x558431da7551 - std::panicking::try::do_call::h6d9e42ff293cbb6e
  │   14:     0x5584329c90b9 - __rust_maybe_catch_panic
  │                         at src/libpanic_unwind/lib.rs:85
  │   15:     0x558431da7a50 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h774aba78f08ccc10
  │   16:     0x5584329ac59e - call_once<(),FnOnce<()>>
  │                         at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/liballoc/boxed.rs:704
  │   17:     0x5584329c83cf - call_once<(),alloc::boxed::Box<FnOnce<()>>>
  │                         at /rustc/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/liballoc/boxed.rs:704
  │                          - start_thread
  │                         at src/libstd/sys_common/thread.rs:13
  │                          - thread_start
  │                         at src/libstd/sys/unix/thread.rs:79
  │   18:     0x7efc1aef16b9 - start_thread
  │   19:     0x7efc1956a41c - clone
  │   20:                0x0 - <unknown>
```

https://github.com/servo/servo/blob/8e783577d24cac2983fbea1b46d5452ffa5fb44f/components/canvas_traits/webgl_channel/mpsc.rs#L57-L58

**Comment by jdm** [comment]
It's quite surprising that you don't observe these panics locally. This seems like it might be a severe limitation on the implementation, where we try to serialize a WebGL channel which is secretly a non-IPC channel.

**Comment by gterzian** [comment]
> It's quite surprising that you don't observe these panics locally.

Could be simply @ferjm is running locally always in multiprocess mode? I'd say try without, and you'll be using the `mpsc` channel instead of a ipc one.

https://github.com/servo/servo/blob/8e783577d24cac2983fbea1b46d5452ffa5fb44f/components/canvas_traits/webgl_channel/mod.rs#L79

**Comment by ferjm** [comment]
Ugh, I was wrong. I get the panic *after* manually closing the WPT window :\ I was observing the tests pass and hitting Ctrl+C before instead of manually closing the window...

Screenshot 2019-06-18 at 16 34 29

I need to change the design indeed.

> Does (webrender_image_handlers_sender, webrender_image_handlers_recv) need to be an ipc channel exclusively?

IIUC the problem is not the registration channel itself, but the fact that for WebGL I am trying to send a `WebGLSender` through this channel and `WebGLSender` does not implement serialization (on single process). I wanted to register `WebGLSender`s  for the embedder <-> WebGL thread communication (and later `IpcSender<PlayerEvent>`s for the media element case, embedder <-> script communication) to reuse the existing message loops.

**Comment by ferjm** [comment]
I ended up doing this work as part of #23483

**Pull request closed without merging**
