### PR TITLE
Tidy up script::dom::document.SetBody

### PR DESCRIPTION
**Pull request by frewsxcv**
There were a few things that were bothering me with `SetBody`:
- The 'Step 3' comment is in the wrong place
- The logic of 'Step 4' comes before 'Step 3'
- 'Step 5' was not documented

### CODE REVIEW

**Comment by jdm** [comment]
Great cleanup!

**Comment by frewsxcv** [comment]
@jdm I have a fix that works locally. Should I force push or add a separate commit?

**Comment by frewsxcv** [comment]
I force pushed. I was missing the `ref`s in the match branches

**Comment by frewsxcv** [comment]
@jdm it looks like '/XMLHttpRequest/send-redirect-bogus-sync.htm' failed on bors. All the tests pass locally for me. Any insight? It looks like recent PRs also failed this test

**Comment by jdm** [comment]
That's been failing on every PR we tried to merge today, so something's wrong.

**Pull request closed without merging**
