### PR TITLE
[WIP] Sync WebGPU specs to latest

### PR DESCRIPTION
**Pull request by sagudev**
When doing wgpu bump I did it with "minimal" changes to webidl, so this PR tries to catch up with specs more completely.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by gterzian** [comment]
@sagudev What is the status of this one? Rebase and see if we can merge it soon?

**Comment by sagudev** [comment]
> @sagudev What is the status of this one? Rebase and see if we can merge it soon?

My plan is to firstly get https://github.com/servo/servo/pull/31194 and stabilize WebGPU CTS expectations (also cts bump), then put only minimal changes with full webidl change (so mostly surface changes), then start inner changes (buffers need some changes of internal states, ...).

I am currently busy, but I should be able to start working again on my plan in mid-feb.

**Comment by sagudev** [comment]
> > @sagudev What is the status of this one? Rebase and see if we can merge it soon?
> 
> My plan is to firstly get #31194 and stabilize WebGPU CTS expectations (also cts bump), then put only minimal changes with full webidl change (so mostly surface changes), then start inner changes (buffers need some changes of internal states, ...).
> 
> I am currently busy, but I should be able to start working again on my plan in mid-feb.

Just update on this, plan has changed. I am splitting this PR into multiple PRs (you can see linked PRs), the end goal is still to check for whole webidl again, but after we land most of stuff. I will keep this open until all parts of this PR land.

**Comment by mrobinson** [comment]
> Just update on this, plan has changed. I am splitting this PR into multiple PRs (you can see linked PRs), the end goal is still to check for whole webidl again, but after we land most of stuff. I will keep this open until all parts of this PR land.

Since this will never land itself, do you mind closing this one in order to keep the list of PRs cleaner? My hope is to clear out a lot of the one that will never be able to get reviews / land.

**Pull request closed without merging**
