### PR TITLE
Don't panic due to I/O issues in console.log.

### PR DESCRIPTION
**Pull request by jdm**
This attempts to address something that has shown up in zombie mac processes - a long stack showing that a panic occurred inside Console::Log and then we kept panicking over and over.

### CODE REVIEW

**Comment by CYBAI** [comment]
Looks the timeout gets worst in this round of builds 😨

**Comment by jdm** [comment]
I think I may have broken things by using write! instead of writeln!

**Comment by nox** [comment]
So is the fix to just use `writeln` here?

**Comment by dralley** [comment]
Would be pretty fast to find out, I would think.

**Comment by jdm** [comment]
This isn't an important change any more.

**Pull request closed without merging**
