### PR TITLE
fix getElementsByTagName()

### PR DESCRIPTION
**Pull request by kevgs**
#11596

@nox 

This is a first iteration. I need some review.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11705)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer +S-needs-code-changes 

---

Reviewed 10 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/11705#-KKhGOKm9GjqmM9nkg3S:-KKhGOKm9GjqmM9nkg3T:-750884683) (no related file):*
I think we should have new tests that look for `test:AÇ` in a HTML document, no?

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/11705#-KKhGhl0lOcV63WA4rNt:-KKhGhl0lOcV63WA4rNu:1140399702) (no related file):*
I don't think this patch account for:

> When invoked with the same argument, and as long as root’s node document’s type has not changed, the same HTMLCollection object may be returned as returned by an earlier call.

Can you confirm?

---

*[components/script/dom/document.rs, line 1992 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11705#-KKQui_Snv_WFDdwc_Et:-KKQui_Snv_WFDdwc_Eu:915484673) ([raw file](https://github.com/servo/servo/blob/fca3a3a35101c3b92853ec86ee22d2890afcb34f/components/script/dom/document.rs#L1992)):*
> ```Rust
>     // https://dom.spec.whatwg.org/#dom-document-getelementsbytagname
>     fn GetElementsByTagName(&self, qualified_name: DOMString) -> Root<HTMLCollection> {
>         let qualified_name_atom = Atom::from(&*qualified_name);
> ```

Nit: please just do this while you are at it:

```
let qualified_name = Atom::from(qualified_name);
```

We don't try to avoid shadowing in such cases. Converting directly from `DOMString` also means that we don't need to allocate a new `String` if no `Atom` with that name existed previously.

---

*[components/script/dom/htmlcollection.rs, line 117 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11705#-KKQwmeqoLYGWURWHADJ:-KKQwJgsH4EdzdYwmqjk:-59425118) ([raw file](https://github.com/servo/servo/blob/fca3a3a35101c3b92853ec86ee22d2890afcb34f/components/script/dom/htmlcollection.rs#L117)):*
> ```Rust
>     }
> 
>     pub fn match_elements_by_qualified_name(window: &Window, root: &Node, mut qualified_name: DOMString)
> ```

You should just pass an `Atom` here, given we already atomify the qualified name in caller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11705#-:-KKhGeGxSUSfolhaYjoX:403869253)*

**Comment by jdm** [comment]
@kevgs Are you still planning to finish this up?

**Comment by kevgs** [comment]
I would to but I can't because I'm mostly afk now. I'm planning to continue to work on Servo in 2-3 weeks. Sorry for that.

05.07.2016, 00:17, "Josh Matthews" <notifications@github.com>:
> @kevgs Are you still planning to finish this up?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

--
Eugene

**Comment by KiChjang** [comment]
Let us know if you start working on this again. I'll close this PR in the meantime. Thanks for your work!

**Pull request closed without merging**
