### PR TITLE
Update GStreamer binaries for Android. Include required codecs

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

This should finally work for both armv7 and x86. I moved the binaries from Github to S3.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21864)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
error: failed to run custom build command for `servo-media-gstreamer v0.1.0 (https://github.com/servo/media#e700a083)`
process didn't exit successfully: `/repo/target/release/build/servo-media-gstreamer-c45c9a207b7ec1ad/build-script-build` (exit code: 101)
--- stderr
--2018-10-03 13:06:21--  https://github.com/servo/libgstreamer_android_gen/blob/master/out/gst-build-armeabi-v7a.zip?raw=true
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
```

**Comment by SimonSapin** [comment]
#21863 also failed its `android-x86` job with:

```
Downloading GStreamer dependencies
Error running mach:

    ['build', '--target', 'i686-linux-android', '--release']

The error occurred in the implementation of the invoked mach command.

This should never occur and is likely a bug in the implementation of that
command. Consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

OSError: [Errno 2] No such file or directory: '/home/servo/buildbot/slave/android-x86/build/target/gstreamer/gst-build-x86/pkgconfig'

  File "/home/servo/buildbot/slave/android-x86/build/python/servo/build_commands.py", line 436, in build
    for each in os.listdir(pkg_config_path):

**Comment by jdm** [comment]
That was caused by me messing with that builder to deploy https://github.com/servo/saltfs/pull/898. The other mac builds were fine.

**Comment by jdm** [comment]
@bors-servo treeclosed=9000
Sorry, homebrew and/or gstreamer got updated in a way that means that our mac builders are broken.

**Comment by SimonSapin** [comment]
r=me with a code comment that explains (or links to docs somewhere that explain) to how to build and upload a new version of the this tarball.

**Comment by ferjm** [comment]
Something is wrong with the gstreamer dependencies on the mac builder:

```
dyld: Library not loaded: /usr/local/opt/gst-plugins-bad/lib/libgstplayer-1.0.0.dylib
```

**Comment by ferjm** [comment]
@bors-servo retry

- #21205 again?

**Comment by ferjm** [comment]
@bors-servo retry

- bootstrap-android error

**Comment by jdm** [comment]
@bors-servo retry
There were some stuck processes on servo-linux-kvm1. I killed them.

**Comment by jdm** [comment]
This does seem to be impacted by the change in binaries.

**Comment by jdm** [comment]
The previous try run timed out with no more information:
```
xcb_connection_has_error() returned true
pulseaudio: pa_context_connect() failed
pulseaudio: Reason: Connection refused
pulseaudio: Failed to initialize PA contextaudio: Could not init `pa' audio driver
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.mozilla.servo/.MainActivity (has extras) }

command timed out: 1200 seconds without output running ['env', '--unset', 'ANDROID_NDK', '--unset', 'ANDROID_SDK', 'RUST_LOG=debug', './mach', 'test-android-startup', '--release'], attempting to kill
```
Compare to a passing run:
```
xcb_connection_has_error() returned true
pulseaudio: pa_context_connect() failed
pulseaudio: Reason: Connection refused
pulseaudio: Failed to initialize PA contextaudio: Could not init `pa' audio driver
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.mozilla.servo/.MainActivity (has extras) }
Assuming --target i686-linux-android
Success
--------- beginning of system
--------- beginning of main
init
Loading EGL...
EGL loaded
ResourceReader::read(prefs.json)
ResourceReader::read(hsts_preload.json)
ResourceReader::read(rippy.png)
ResourceReader::read(public_domains.txt)
ResourceReader::read(certs)
ALERT: JavaScript is running!
emulator: Requested console port 5580: Inferring adb port 5581.
emulator: Cold boot: requested by the user
emulator: INFO: boot completed
emulator: Discarding the changed state: command-line flag
emulator: WARNING: Discarding the changed state (command-line flag).
program finished with exit code 0
elapsedTime=25.040618
```
We're not even reaching the start of the program, apparently.

**Comment by jdm** [comment]
```
Error running mach:

    ['test-android-startup', '--release']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 31: ordinal not in range(128)

  File "/home/servo/buildbot/slave/android-x86/build/python/servo/testing_commands.py", line 594, in test_android_startup
    print(line.rstrip())
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
```

**Comment by SimonSapin** [comment]
That `print(line.rstrip())` line should probably be `sys.stdout.write(line)` instead.

(`sys.stdout` on Python 2 is a byte stream like `subprocess.Popen(…).stdout`, whereas `print` presumably wants Unicode. `print()` adds a trailing newline, so we shouldn’t strip the existing one if we skip `print()`.)

**Comment by jdm** [comment]
Boooo:
```
Error running mach:

    ['test-android-startup', '--release']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 31: ordinal not in range(128)

  File "/home/servo/buildbot/slave/android-x86/build/python/servo/testing_commands.py", line 594, in test_android_startup
    sys.stdout.write(line)
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
```

**Comment by SimonSapin** [comment]
My Unicode-in-Python-2 must be… rusty. I’m honestly confused why we get a decode error in `encode()` called by the `write()` method of what should be a byte stream, called with what should be bytes.

**Comment by ferjm** [comment]
I managed to reproduce the issue locally by regenerating the binaries again (I am not sure why I wasn't able to reproduce it before... :\). I got this from the logcat: 

```
"/data/app/org.mozilla.servo-nOOw72Qz41OjUAUw_uVE7g==/lib/x86/libgstreamer_android.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
--------- beginning of crash
FATAL EXCEPTION: GLThread 285
Process: org.mozilla.servo, PID: 4791
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/org.mozilla.servo-nOOw72Qz41OjUAUw_uVE7g==/lib/x86/libgstreamer_android.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
	at java.lang.System.loadLibrary(System.java:1669)
	at org.mozilla.servoview.JNIServo.<init>(JNIServo.java:17)
	at org.mozilla.servoview.Servo.<init>(Servo.java:22)
	at org.mozilla.servoview.ServoView.lambda$onGLReady$1$ServoView(ServoView.java:152)
	at org.mozilla.servoview.ServoView$$Lambda$1.run(Unknown Source:4)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
  Force finishing activity org.mozilla.servo/.MainActivity
```

Which lead me to this known and unresolved GStreamer issue https://bugzilla.gnome.org/show_bug.cgi?id=742633

I don't think we need the x86 emulator to playback a/v video any time soon. So in order to unblock a/v playback on real devices, I am going to temporarily remove `libav` from the x86 binaries.

**Comment by ferjm** [comment]
I've documented the workaround at https://github.com/servo/libgstreamer_android_gen/blob/536676168014b60d59ce8a0d1ef4003632d9c941/README.md#known-issues

**Pull request merged**
