### PR TITLE
style: Use a SharedFontList object to store font-family values for Gecko

### PR DESCRIPTION
**Pull request by heycam**
Reviewed by Xidorn and Manish in https://bugzilla.mozilla.org/show_bug.cgi?id=1397626.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18722)

### CODE REVIEW

**Comment by jdm** [comment]
```
---- specified_values::size_of_specified_values stdout ----
	thread 'specified_values::size_of_specified_values' panicked at 'Your changes have decreased the size of font_family SpecifiedValue to 16. Good work! The threshold is currently 24. Please consider removing `boxed="True"` from this longhand.', /home/servo/buildbot/slave/linux-dev/build/tests/unit/stylo/specified_values.rs:48
```

**Comment by upsuper** [comment]
@bors-servo retry
* #18739

**Comment by jdm** [comment]
@bors-servo: retry
* shut down the faulty windows builder

**Pull request merged**
