### PR TITLE
Fix Stylo tests to pass on both Stable and Nightly Rust

### PR DESCRIPTION
**Pull request by SimonSapin**
This is on top of https://github.com/servo/servo/pull/19285.

Rust Nightly has new enum memory layout optimizations: https://github.com/rust-lang/rust/pull/45225

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19316)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r+

Looks fine, thanks!

**Comment by SimonSapin** [comment]
```
  ▶ TIMEOUT [expected PASS] /css/CSS2/csswg-issues/submitted/css2.1/anonymous-boxes-001.xht
  │ 
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 17.3.0-devel

  ▶ TIMEOUT [expected PASS] /2dcontext/text-styles/canvas_text_font_001.htm
  │ 
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 17.3.0-devel

  ▶ TIMEOUT [expected PASS] /css/CSS2/generated-content/after-content-display-008.xht
  │ 
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 17.3.0-devel

  ▶ TIMEOUT [expected PASS] /_mozilla/css/transition_calc_implicit.html
  │ 
  │ VMware, Inc.
  │ softpipe
  └ 3.3 (Core Profile) Mesa 17.3.0-devel
```

I’m fairly confident these failures are intermittent, but not at all that they’re specific to test filenames so I’m hesitant to file them as usual.

**Comment by SimonSapin** [comment]
@jdm, what’s the etiquette here? (See previous comment.)

In the meantime: @bors-servo retry

**Comment by jdm** [comment]
Retrying is ok.

**Pull request merged**
