### PR TITLE
Fix clearance on replaced elements

### LINKED ISSUE #29928: Layout 2020: replaced elements with clearance are broken
```html
<!DOCTYPE html>
<div style="border: solid; width: 100px">
  <div style="float: left; width: 50px; height: 100px; background: cyan"></div>
  <img style="display: block; clear: both; height: 50px; border: solid magenta" src="./image">
  foo bar
</div>
```

| Layout 2013 (good) | Layout 2020 (bad) |
| - | - |
|  |  |

### PR DESCRIPTION
**Pull request by Loirooriol**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #29928

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by mrobinson** [comment]
Huh...very odd that this did not change any tests.

**Comment by Loirooriol** [comment]
I realized I also had to adjoin the end margin, but I still didn't get any pass, so I added a test that requires the 4 changes that I'm doing.

**Review by mrobinson — APPROVED** [review]

**Comment by Loirooriol** [comment]
Safari needs fuzzy matching

**Comment by Loirooriol** [comment]
I guess https://github.com/servo/servo/actions/runs/5379117354 is complaining because of #29921

**Pull request merged**
