### PR TITLE
Use wptrunner for some old-style reftests.

### PR DESCRIPTION
**Pull request by frewsxcv**
Part of #5618

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8152)

### CODE REVIEW

**Comment by jdm** [comment]
```
-!= image_rendering_auto_a.html image_rendering_pixelated_a.html
 == image_rendering_pixelated_a.html image_rendering_pixelated_ref.html
```
That won't work.

**Comment by frewsxcv** [comment]
Hm you're right. I just removed that commit off the latest force push

**Comment by Ms2ger** [comment]
```
/_mozilla/css/white-space-mixed-002.htm
---------------------------------------
FAIL [Parent]
/_mozilla/css/white-space-normal-001.htm
----------------------------------------
FAIL [Parent]
```

**Comment by frewsxcv** [comment]
I'm a little confused by this. Both of those tests fail for me on Chrome and Firefox. I'm also confused why it's showing up when I didn't touch either of those sets of tests. I'll look into it later today or tomorrow if no one else finds out the answer before then

**Comment by frewsxcv** [comment]
https://github.com/servo/servo/commit/c567afe41cd29ca569abafb809fc6a2cffa5e060 is the cause. I'll fix it later

**Comment by frewsxcv** [comment]
Just removed that commit in the latest force push. Ran the wpt tests and they all pass. r?

**Pull request merged**
