### PR TITLE
Run CSS Multicolumn tests automatically

### LINKED ISSUE #13587: Run CSS Multicolumn tests automatically
We have some support for CSS properties from the [Multi-column specification](https://drafts.csswg.org/css-multicol-1/) but we don't run the tests. We should fix that!

1. Add new entries to `tests/wpt/include_css.ini` for the `css-multicol-1_dev` folder under `tests/wpt/css-tests`
2. Add a new `tests/wpt/metadata-css/css-multicol-1_dev/__dir__.ini` file that enables the appropriate preferences (`layout.{column-gap|column-width|column-count|columns}.enabled`) based on [similar files elsewhere](https://dxr.mozilla.org/servo/source/tests/wpt/mozilla/meta/css/__dir__.ini)
3. Run `./mach test-css tests/wpt/css-tests/css-multicol-1_dev/html4/ --log-raw /tmp/testlog`
4. Run `./mach update-css /tmp/testlog`

The resulting PR should include a lot of new ini files added to `tests/wpt/metadata-css/css-multicol-1_dev/` that contain expected test results.

### PR DESCRIPTION
**Pull request by slester**
Implements the CSS multicolumn tests as outlined in issue #13587.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13587 

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they implement tests for other features.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13599)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Thank you very much!

**Comment by jdm** [comment]
Looks like only one change is required - make the expected outcome of multicol-br-inside-avoidcolumn-001.htm (inside`multicol-br-inside-avoidcolumn-001.htm.ini`) platform specific:
```
expected:
  if os == "linux": TIMEOUT
  CRASH
```
```

**Comment by slester** [comment]
All right, these changes have been made! Sorry about that.

**Comment by jdm** [comment]
There's no reason to apologize; inconsistent test expectations are a problem with our test harness, not something that you're responsible for :)
@bors-servo: r+

**Comment by jgraham** [comment]
The manifest files are whitespace-sensitive so you can't have

    if os == "linux": TIMEOUT
      CRASH

but must instead have the same whitespace:


    if os == "linux": TIMEOUT
    CRASH

**Comment by jdm** [comment]
I'm surprised that the code that checks if the manifests change on TravisCI didn't report any error about that...

**Comment by jgraham** [comment]
Different manifests… it could of course but at the moment it doesn't because we don't read expectation metadata for tests we won't run.

**Comment by slester** [comment]
Third time's a charm, hopefully.

**Pull request merged**
