### PR TITLE
layout: Implement per-glyph font fallback.

### LINKED ISSUE #177: TextRun creation must account for text render-ability by FontGroup fonts
If some text in a text run can't be rendered in the first FontGroup font (say, because of language or missing chars), then the next one must be used. This causes a text run split, because of the one Font per TextRun invariant.

The font group is not presently consulted. It should be built for each style context within an inline flow.

### PR DESCRIPTION
**Pull request by pcwalton**
This improves numerous pages, for example Wikipedia and Ars Technica.

Built on #5493.

Closes #177.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5607)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Left a few comments on Critic.

**Comment by pcwalton** [comment]
Addressed the comments. r? @mbrubeck

**Comment by mbrubeck** [comment]
r+, needs squash and rebase

**Comment by jdm** [comment]
```
failures:
    line_height_float_placement_a.html == line_height_float_placement_ref.html
    text_align_complex_a.html == text_align_complex_ref.html
```

**Comment by pcwalton** [comment]
Ugh, Linux-only failures. :(

**Comment by pcwalton** [comment]
I filed #5640 and added some workarounds in the test suite for the `line-height` issues.

**Comment by jdm** [comment]
I defer to someone who knows if those changes make sense.

**Comment by jdm** [comment]
@glennw Can you sign off on https://github.com/servo/servo/pull/5607#issuecomment-91702164?

**Comment by jdm** [comment]
```
failures:
    line_height_float_placement_a.html == line_height_float_placement_ref.html
    text_align_complex_a.html == text_align_complex_ref.html
```

**Comment by pcwalton** [comment]
I can't reproduce this anymore, so...

@bors-servo: retry

**Comment by jdm** [comment]
```
    line_height_float_placement_a.html == line_height_float_placement_ref.html
    text_align_complex_a.html == text_align_complex_ref.html
```

**Comment by pcwalton** [comment]
@bors-servo: r=mbrubeck

I think I found the problem: newlines aren't in Ahem so trigger inconsistent font fallback.

**Pull request merged**
