### PR TITLE
Fix error message for invalid combination of style crate feature flags

### PR DESCRIPTION
**Pull request by SimonSapin**
Instead of ``cannot find value `engine` in this scope`` https://github.com/servo/servo/issues/24284

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24294)

### CODE REVIEW

**Comment by CYBAI** [comment]
Need a `./mach fmt` 👀

**Comment by SimonSapin** [comment]
Oops, fixed.

@bors-servo r=jdm

**Pull request merged**
