### PR TITLE
allow_navigation: use channel to send response

### PR DESCRIPTION
**Pull request by paulrouget**
From the embedder perspective, this makes things easier in term of synchronicity.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17684)

### CODE REVIEW

**Comment by paulrouget** [comment]
@cbrewster do you think this makes sense? We haven't used channels in WindowMethods yet.

**Comment by cbrewster** [comment]
@paulrouget what is the advantage of making the embedder handle the channel? It seems like this would add extra complexity for the embedder.

**Comment by paulrouget** [comment]
@cbrewster it doesn't require the embedder to return the boolean right away. It can be done later. 

For example, if the embedder wants to ask the user, with a prompt, if he agrees to navigate away or not, if we do not use a channel, we have to block `allow_navigation` (if I'm not mistaken, the compositor thread) until the whole prompting mechanism is done.

With a channel, we don't have to block.

Does it make sense?

>  It seems like this would add extra complexity for the embedder.

Yes. But at this stage, we don't try to make the embedding API "simple". We will later work on the cosmetic part of the API to make things easier.

**Comment by cbrewster** [comment]
Sounds reasonable to me.
@bors-servo r+

**Comment by cbrewster** [comment]
@bors-servo delegate+
r=me after rebase

**Comment by paulrouget** [comment]
Rebased. Also fixed cef.

@bors-servo r+

**Pull request merged**
