### PR TITLE
Rename SCRIPT_TASK_ROOT to SCRIPT_THREAD_ROOT

### LINKED ISSUE #9316: Rename SCRIPT_TASK_ROOT to SCRIPT_THREAD_ROOT
Code: `components/script/script_thread.rs`

### PR DESCRIPTION
**Pull request by shssoichiro**
Resolves #9316

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9318)

### CODE REVIEW

**Comment by KiChjang** [comment]
Looks like Travis is failing this PR. I can't look at the output right now, but my guess is SCRIPT_TASK_ROOT is still being referenced somewhere.

**Comment by shssoichiro** [comment]
Looks like Travis is failing here (one of the crates.io dependencies):

     Downloading servo-skia v0.20130412.3
    unable to get packages from source
    Caused by:
      Failed to download package `servo-skia v0.20130412.3` from https://crates.io/api/v1/crates/servo-skia/0.20130412.3/download
    Caused by:
      Couldn't connect to server
    [Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
    Build completed in 95.34s
    The command "./mach build -d --verbose" exited with 101.
    28.68s$ ./mach test-unit
     Downloading aster v0.9.1
    unable to get packages from source

If SCRIPT_TASK_ROOT still is referenced somewhere, I can't find it. I searched the entire project folder recursively, there are no more references to it. The build also works and passes the tests on my local machine, so maybe it's an issue with Travis? The last 4 PRs have failed tests.

**Comment by KiChjang** [comment]
Oh, sorry for that, it's an even worse problem that has nothing to do with this PR. Basically I think crates.io is down, hence it cannot download anything. That, or something's happened with the skia crate, which isn't good news either.

**Pull request merged**
