### PR TITLE
webgl: Restore active texture if it's changed while deleting a texture.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21781)

### CODE REVIEW

**Comment by jdm** [comment]
r? @nox 
You changed the original code from != to == in #21341. Was that intentional?

**Comment by nox** [comment]
Lol, absolutely not. oO

@bors-servo r+

**Comment by nox** [comment]
Wait no, this was actually intended.

**Comment by nox** [comment]
I think I thought this change was required but I probably confused myself, I guess this patch is correct.

**Pull request merged**
