### PR TITLE
Move to latest hyper everywhere, more package updates

### PR DESCRIPTION
**Pull request by Manishearth**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6254)

### CODE REVIEW

**Comment by Manishearth** [comment]
Deferred r=SimonSapin

(waiting on some build system changes before merge)

**Comment by waddlesplash** [comment]
>   Compiling hyper v0.5.2
>  Compiling hyper v0.4.0

Looks like there are still 2 copies of Hyper. :disappointed:

**Comment by Manishearth** [comment]
Yeah I removed that (see the latest lockfile changes).

**Pull request merged**
