### PR TITLE
Save local storage at every change and not just on shutdown

### PR DESCRIPTION
**Pull request by fabricedesre**
Currently local storage is saved to `local_data.json` only at shutdown when the storage thread receives the `StorageThreadMsg::Exit` message. This is not reliable enough in any case, and especially problematic for a young engine like Servo. Data loss ensues...

I kept the exit message in the storage thread even if we are not doing work anymore. I can remove it if needed but it should be useful once we move to a better storage backend than a json file.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because we don't have tests for that persistence layer.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20840)

### CODE REVIEW

**Comment by fabricedesre** [comment]
@Manishearth if you don't have time to look at that, please redirect the review. Thanks!

**Comment by Manishearth** [comment]
Oh, sorry, I just didn't realize this was blocked on me. Will review.

On May 22, 2018 10:09 PM, "Fabrice Desré" <notifications@github.com> wrote:

@Manishearth <https://github.com/Manishearth> if you don't have time to
look at that, please redirect the review. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/servo/servo/pull/20840#issuecomment-391221963>, or mute
the thread

**Comment by Manishearth** [comment]
@bors-servo r+

sorry for the delay

**Comment by jdm** [comment]
@bors-servo retry
* #20796

**Pull request merged**
