### PR TITLE
Move magicleap builds to taskcluster

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23362)

### CODE REVIEW

**Comment by jdm** [comment]
Current problem that I'm not sure how to deal with:
```
[taskcluster 2019-05-10T15:11:26.463Z] === Task Starting ===
[taskcluster 2019-05-10T15:11:27.650Z] Uploading redirect artifact public/logs/live.log to URL https://websocktunnel.tasks.build/servo-macos.mac1.60099/log/fhmPLSlqQeWvWzAoSjOE8w with mime type "text/plain; charset=utf-8" and expiry 2019-05-10T17:26:27.283Z
[taskcluster 2019-05-10T15:11:27.672Z] [mounts] Found existing download for urlcontent:https://github.com/mozilla/sccache/releases/download/0.2.7/sccache-0.2.7-x86_64-apple-darwin.tar.gz (downloads/aHnXuc7uQOG4CB-84GL6nA) with correct SHA256 f86412abbbcce2d3f23e7d33305469198949f5cf807e6c3258c9e1885b4cb57f
[taskcluster 2019-05-10T15:11:27.673Z] [mounts] Creating directory /Users/worker/tasks/task_1556974932/sccache with permissions 0700
[taskcluster 2019-05-10T15:11:27.673Z] [mounts] Extracting tar.gz file downloads/aHnXuc7uQOG4CB-84GL6nA to '/Users/worker/tasks/task_1556974932/sccache'
[taskcluster 2019-05-10T15:11:30.918Z] [mounts] Found existing download for urlcontent:https://servo-deps.s3.amazonaws.com/magicleap/macos-sdk-v0.17.0.tar.gz (downloads/B4kYrSkfR5KdxJRCpW2pXQ) with correct SHA256 e81de47ad963891ac68768d93ab5a36ed3af3a3efebb4dbc4db2e65647d57655
[taskcluster 2019-05-10T15:11:30.918Z] [mounts] Creating directory /Users/worker/tasks/task_1556974932/magicleap with permissions 0700
[taskcluster 2019-05-10T15:11:30.918Z] [mounts] Extracting tar.gz file downloads/B4kYrSkfR5KdxJRCpW2pXQ to '/Users/worker/tasks/task_1556974932/magicleap'
[taskcluster 2019-05-10T15:11:39.627Z] Uploading redirect artifact public/logs/live.log to URL https://queue.taskcluster.net/v1/task/ZCBaiM05S1yUZ4weEyNb8w/runs/0/artifacts/public/logs/live_backing.log with mime type "text/plain; charset=utf-8" and expiry 2020-05-09T15:11:18.808Z
[taskcluster:error] [mounts] /Users/worker/tasks/task_1556974932/magicleap/v0.17.0/VirtualDevice/bin/UIFrontend/Magic Leap Remote.app/Contents/Eclipse/jre/Contents/MacOS/libjli.dylib: making symbolic link for: symlink ../Home/lib/jli/libjli.dylib /Users/worker/tasks/task_1556974932/magicleap/v0.17.0/VirtualDevice/bin/UIFrontend/Magic Leap Remote.app/Contents/Eclipse/jre/Contents/MacOS/libjli.dylib: file exists
```
@SimonSapin any ideas?

**Comment by SimonSapin** [comment]
This message comes from https://github.com/mholt/archiver/blob/5e4ca701b6014549de7fa8734b3c7c5caf98af9e/archiver.go#L324 when https://golang.org/pkg/os/#Symlink returns an error.

Looking at the archive being extracted also gives nothing unexpected:

```
$ tar -tvvzf macos-sdk-v0.17.0.tar.gz|grep libjli.dylib
lrwxr-xr-x  0 jdm    staff        0 Oct 30  2018 v0.17.0/VirtualDevice/bin/UIFrontend/Magic Leap Remote.app/Contents/Eclipse/jre/Contents/MacOS/libjli.dylib -> ../Home/lib/jli/libjli.dylib
-rwxr-xr-x  0 jdm    staff    61704 Sep  7  2018 v0.17.0/VirtualDevice/bin/UIFrontend/Magic Leap Remote.app/Contents/Eclipse/jre/Contents/Home/lib/jli/libjli.dylib
```

@petemoore , have you seen `file exists` errors before, when generic-worker creates a symlink as part of extracting a `.tar.gz` for a directory mount?

**Comment by petemoore** [comment]
> @petemoore , have you seen `file exists` errors before, when generic-worker creates a symlink as part of extracting a `.tar.gz` for a directory mount?

I haven't seen this before, sorry. One thing you could try is mounting the archive as a file rather than a directory, and then extracting it as a task step. The advantage of this is you can control the version of the extraction utility. I suspect if the archive has symbolic links, it might be safer to use a native mac extraction utility than the archiver library that generic-worker uses.

**Comment by petemoore** [comment]
@jdm I'm getting a HTTP 403 when hitting https://servo-deps.s3.amazonaws.com/magicleap/macos-sdk-v0.17.0.tar.gz - do I need to authenticate if calling from outside the worker?

I wanted to test whether the `archiver` command line utility (revision de0d89e255e17c8d75a40122055763e743ab0593) demonstrates the same issue when extracting the archive.

**Comment by SimonSapin** [comment]
I’ve ran the commands above and ended up with a `tmp` directory containing 19416 files worth 1.3 GB. There was no error message.

**Comment by petemoore** [comment]
There definitely seems to be a bug in the mac release of generic-worker 14.1.0. We should expect to see a new task dir created for each task, but we can see here this is not the case:

```
$ cat ~/Downloads/tail | grep -e '\(Created dir\|Running task\)'
2019/05/03 11:29:50 Running task https://tools.taskcluster.net/task-inspector/#BD8bRRQyRHGhA__iEydhDQ/0
2019/05/03 12:07:56 Created dir: /Users/worker/tasks/task_1556885276/generic-worker
2019/05/03 12:07:58 Running task https://tools.taskcluster.net/task-inspector/#cPGC8byaTb6lxOVuPCmgkA/0
2019/05/03 12:08:00 Created dir: /Users/worker/tasks/task_1556885280/generic-worker
2019/05/03 12:09:02 Running task https://tools.taskcluster.net/task-inspector/#FqQA2LJwS6GI5P0K0TGK6g/0
2019/05/03 12:57:05 Created dir: /Users/worker/tasks/task_1556888225/generic-worker
2019/05/03 12:57:06 Running task https://tools.taskcluster.net/task-inspector/#KiGx13qlT9i-z94a4eTH4Q/0
2019/05/03 13:20:38 Created dir: /Users/worker/tasks/task_1556889638/generic-worker
2019/05/03 13:20:55 Running task https://tools.taskcluster.net/task-inspector/#OXpAD5W3TP2Dlj1wpIenQw/0
2019/05/03 13:59:21 Running task https://tools.taskcluster.net/task-inspector/#Z3i-qZKQQtK1_7RwFa_V5Q/0
2019/05/03 14:28:31 Running task https://tools.taskcluster.net/task-inspector/#dltlKJhBTuqru6n7QJC1Pw/0
2019/05/03 15:33:49 Created dir: /Users/worker/tasks/task_1556897629/generic-worker
2019/05/03 15:38:10 Running task https://tools.taskcluster.net/task-inspector/#BPEh2aGaT8KQFRKuImPZyg/0
2019/05/03 15:39:15 Running task https://tools.taskcluster.net/task-inspector/#FMMzL5nAS5uBuUbpg6tBTQ/1
2019/05/03 15:44:27 Created dir: /Users/worker/tasks/task_1556898267/generic-worker
2019/05/03 15:44:43 Running task https://tools.taskcluster.net/task-inspector/#QFQlflGGRkKCy1Papa6Fhg/0
2019/05/03 15:45:42 Running task https://tools.taskcluster.net/task-inspector/#LE5e_4MiQaCb20JKzg2UCA/0
2019/05/03 15:45:51 Created dir: /Users/worker/tasks/task_1556898351/generic-worker
2019/05/03 15:48:35 Running task https://tools.taskcluster.net/task-inspector/#UM6EDcfHRPq0c043tghIDw/0
2019/05/03 15:48:38 Created dir: /Users/worker/tasks/task_1556898518/generic-worker
2019/05/03 15:50:40 Running task https://tools.taskcluster.net/task-inspector/#N5bUd-BASfKfnQwoHL0tOQ/0
2019/05/03 15:51:43 Created dir: /Users/worker/tasks/task_1556898703/generic-worker
2019/05/03 16:29:06 Running task https://tools.taskcluster.net/task-inspector/#ak7jv2JMTM-0afGYHpf-Ig/0
2019/05/03 16:30:09 Created dir: /Users/worker/tasks/task_1556901009/generic-worker
2019/05/03 16:30:38 Created dir: /Users/worker/tasks/task_1556901038/generic-worker
2019/05/03 16:32:23 Running task https://tools.taskcluster.net/task-inspector/#EX3yu5N1RXaX-17MCbMGTw/0
2019/05/03 16:42:04 Running task https://tools.taskcluster.net/task-inspector/#J5W1_Aw5RbSf083fosHFhQ/0
2019/05/03 17:22:33 Running task https://tools.taskcluster.net/task-inspector/#apwrnpxHQIqOEJMQBANK8Q/0
2019/05/03 17:55:17 Running task https://tools.taskcluster.net/task-inspector/#XcjcBcikRduMwfoyJmk_iA/0
2019/05/03 18:43:24 Running task https://tools.taskcluster.net/task-inspector/#M8TOwnxFRQ-bXXipV7eb6g/0
2019/05/03 18:44:09 Running task https://tools.taskcluster.net/task-inspector/#NcibQpgjRTqAxFQ_TPgXxQ/0
2019/05/03 18:46:18 Running task https://tools.taskcluster.net/task-inspector/#RVOrS9nGTby-ZKROC2F5TA/0
2019/05/04 03:37:19 Running task https://tools.taskcluster.net/task-inspector/#OGSwwpwjQN2IgCBoLYw5Gg/0
2019/05/04 03:56:44 Running task https://tools.taskcluster.net/task-inspector/#anyaA7JlQOe7et6k5AQNOw/0
2019/05/04 04:16:55 Running task https://tools.taskcluster.net/task-inspector/#YwFAenWfT1eO2-WdFB0j6w/0
2019/05/04 10:16:11 Running task https://tools.taskcluster.net/task-inspector/#ec0s56-XRV2yriZj6JvT5g/0
2019/05/04 13:02:12 Created dir: /Users/worker/tasks/task_1556974932/generic-worker
2019/05/04 15:07:25 Running task https://tools.taskcluster.net/task-inspector/#Ar1TPc07Sp6Tdscg4UOL6Q/0
2019/05/04 15:08:06 Running task https://tools.taskcluster.net/task-inspector/#WZd6knZNRuCGZj2CbccKvg/0
2019/05/05 10:14:34 Running task https://tools.taskcluster.net/task-inspector/#Esny0CESRlm4W1UuoslU8A/0
2019/05/06 08:34:23 Running task https://tools.taskcluster.net/task-inspector/#aY-ReMHsSmS7h_LjBwUysA/0
2019/05/06 08:55:09 Running task https://tools.taskcluster.net/task-inspector/#DmSuP-5MR9qKD54qZcIsAg/0
2019/05/06 09:34:56 Running task https://tools.taskcluster.net/task-inspector/#QJzfkzdzQYyt5J795EAqyA/0
2019/05/06 10:21:56 Running task https://tools.taskcluster.net/task-inspector/#LaQBhy44RjqeN3mUX9OJVg/0
2019/05/06 15:21:34 Running task https://tools.taskcluster.net/task-inspector/#MrLlLC1iT6G0IUIp3miSjw/0
2019/05/06 15:41:05 Running task https://tools.taskcluster.net/task-inspector/#Zgj_WvlvRhKugA4-4evm4g/0
2019/05/06 16:01:41 Running task https://tools.taskcluster.net/task-inspector/#ecIIyraNQ4KjGINnCJakPA/0
2019/05/06 16:49:30 Running task https://tools.taskcluster.net/task-inspector/#GKZm-aUGT-Oaa-Io26Pa5w/0
2019/05/06 16:49:40 Running task https://tools.taskcluster.net/task-inspector/#VFPknPh-QOSi23lWogpsbw/0
2019/05/06 16:50:04 Running task https://tools.taskcluster.net/task-inspector/#B5gxHf7QRneJDxJYDcl8Yw/0
2019/05/06 17:07:53 Running task https://tools.taskcluster.net/task-inspector/#N6ePlhZZTL2-Dz6mZiGtHA/0
2019/05/06 17:30:37 Running task https://tools.taskcluster.net/task-inspector/#XrijQLcxTES3OymJbi1ufg/0
2019/05/06 18:18:26 Running task https://tools.taskcluster.net/task-inspector/#XPqUzikPQnybmc6wP8AL-w/0
2019/05/06 19:10:00 Running task https://tools.taskcluster.net/task-inspector/#KW0oobw3T-eqZvBTas1QgA/0
2019/05/06 19:10:29 Running task https://tools.taskcluster.net/task-inspector/#Wj_hEjd0Qi6t3B6WIHk-ew/0
2019/05/06 19:10:37 Running task https://tools.taskcluster.net/task-inspector/#HGrAGrLtSO6cVwSvndcwaQ/0
2019/05/06 19:17:19 Running task https://tools.taskcluster.net/task-inspector/#IUVAQHSVRTmWXHDDzB8E-w/0
2019/05/06 19:20:04 Running task https://tools.taskcluster.net/task-inspector/#LEpAa0tmQCSNil6Bcymeiw/0
2019/05/06 21:44:33 Running task https://tools.taskcluster.net/task-inspector/#eyHx60zhQROXDMK_1Ti0Wg/0
2019/05/06 22:18:29 Running task https://tools.taskcluster.net/task-inspector/#eEhBWjwgTkudqowbw3ogAQ/0
2019/05/06 23:25:22 Running task https://tools.taskcluster.net/task-inspector/#PypVGscNTFOaqq3lnHRsnw/0
2019/05/07 01:05:44 Running task https://tools.taskcluster.net/task-inspector/#En9U60hRS6qCJL54Q3AgIA/0
2019/05/07 01:26:45 Running task https://tools.taskcluster.net/task-inspector/#CWYrqDyWRXyfGfGlLZ-1LQ/0
2019/05/07 01:28:01 Running task https://tools.taskcluster.net/task-inspector/#Clwhn4nMTu-0Y_w6LNCLEw/0
2019/05/07 01:40:15 Running task https://tools.taskcluster.net/task-inspector/#U9ixsDqAQiKLH6Hy_BuSKQ/0
2019/05/07 04:20:15 Running task https://tools.taskcluster.net/task-inspector/#BPE7M2QqRSGI5fFmFBpF0Q/0
2019/05/07 04:39:15 Running task https://tools.taskcluster.net/task-inspector/#I0SSfTcgQ1Gs_g6iUr3jZA/0
2019/05/07 10:13:55 Running task https://tools.taskcluster.net/task-inspector/#N4g4NBqqSKGCmGBogXdY4Q/0
2019/05/07 11:21:03 Running task https://tools.taskcluster.net/task-inspector/#K4PH2FmQR8OhMs0yt3UqBw/0
2019/05/07 11:23:58 Running task https://tools.taskcluster.net/task-inspector/#Bl2UqAnnQ6-EsZ32iPuw_w/0
2019/05/07 12:25:47 Running task https://tools.taskcluster.net/task-inspector/#cD2OgewPT1-sHC5C0KtJqg/0
2019/05/07 13:40:42 Running task https://tools.taskcluster.net/task-inspector/#CposwtxqRNKFE-E0854SPw/0
2019/05/07 13:44:43 Running task https://tools.taskcluster.net/task-inspector/#Fs391jtdRsuAhPgg8SeVJw/0
2019/05/07 13:52:52 Running task https://tools.taskcluster.net/task-inspector/#e8t_aPiWQJ-LFiGoteGFvQ/0
2019/05/07 15:35:59 Running task https://tools.taskcluster.net/task-inspector/#bFPbC_JcQDeL3Ds8AlCLdQ/0
2019/05/07 16:08:40 Running task https://tools.taskcluster.net/task-inspector/#UjOK1aqpQWGLOK-lm8EyBw/0
2019/05/07 16:22:58 Running task https://tools.taskcluster.net/task-inspector/#DJs0KQq-TiqsfQMqZWgWYQ/0
2019/05/07 16:39:48 Running task https://tools.taskcluster.net/task-inspector/#BTgqCKnaR8Ctc23QR-CZOQ/0
2019/05/07 17:58:34 Running task https://tools.taskcluster.net/task-inspector/#OWOQIveCQgy-pebHHO5FsQ/0
2019/05/07 18:10:13 Running task https://tools.taskcluster.net/task-inspector/#cG14W0yEQXKVupjHbcxcTg/0
2019/05/07 19:48:27 Running task https://tools.taskcluster.net/task-inspector/#TqsUpjkYRuK9uFKTiQIz6A/0
2019/05/07 19:51:50 Running task https://tools.taskcluster.net/task-inspector/#ILJpvLWpQhqXBZWcgVVk4g/0
2019/05/07 20:58:56 Running task https://tools.taskcluster.net/task-inspector/#H5704YPoSaC5U6uYBt_8Gg/0
2019/05/07 21:00:26 Running task https://tools.taskcluster.net/task-inspector/#RlMorI8tR5OWFxaamTV-ow/0
2019/05/07 21:53:02 Running task https://tools.taskcluster.net/task-inspector/#TyXbUC1JTgSxg1cA9-qQfg/0
2019/05/07 21:53:48 Running task https://tools.taskcluster.net/task-inspector/#Ph9paad5Th2Wl-7r9kTNIg/0
2019/05/07 21:58:43 Running task https://tools.taskcluster.net/task-inspector/#Qbx4llf4TwyhLxnY4Wy8cg/0
2019/05/07 23:24:26 Running task https://tools.taskcluster.net/task-inspector/#eSD0FnJER-i1H_6B2Byv4A/0
2019/05/07 23:24:52 Running task https://tools.taskcluster.net/task-inspector/#SWZJ0HiDShOkb-RQKjFfvg/0
2019/05/08 00:51:27 Running task https://tools.taskcluster.net/task-inspector/#eM0ipRqDR3CCVajbCI_OBQ/0
2019/05/08 01:22:01 Running task https://tools.taskcluster.net/task-inspector/#WDe-z7isT9y3jHADPCet8g/0
2019/05/08 01:39:36 Running task https://tools.taskcluster.net/task-inspector/#AgwNNJlOQHC27u8nlJaktQ/0
2019/05/08 04:07:46 Running task https://tools.taskcluster.net/task-inspector/#ND1nmxV-SPGP0fUV0Vo85g/0
2019/05/08 05:20:13 Running task https://tools.taskcluster.net/task-inspector/#IkHu3jkISXWF1TyrfAgVPg/0
2019/05/08 06:03:12 Running task https://tools.taskcluster.net/task-inspector/#GlOHbthyTW2q7qMg3x5MSA/0
2019/05/08 10:14:28 Running task https://tools.taskcluster.net/task-inspector/#NXNsEL7KSayWhqm4tr-Tcg/0
2019/05/08 14:34:06 Running task https://tools.taskcluster.net/task-inspector/#BxYzb6IgQ9KxvQt0pSjXHg/0
2019/05/08 14:58:39 Running task https://tools.taskcluster.net/task-inspector/#P8XrDnuYSWC7cg1mFjbbzg/0
2019/05/08 16:18:28 Running task https://tools.taskcluster.net/task-inspector/#G1ir98ATSs2tVKcamJLOEA/0
2019/05/08 16:52:29 Running task https://tools.taskcluster.net/task-inspector/#MQYIiGJURBqmx3O0MEZ81Q/0
2019/05/08 17:05:10 Running task https://tools.taskcluster.net/task-inspector/#RvzjGrErRbyVWbb8NJrJAg/0
2019/05/08 17:20:35 Running task https://tools.taskcluster.net/task-inspector/#MgRvVdV6S8KNSyOGvyQ19Q/0
2019/05/08 20:05:12 Running task https://tools.taskcluster.net/task-inspector/#Rde835-PSAGrh914qtfybg/0
2019/05/08 21:38:47 Running task https://tools.taskcluster.net/task-inspector/#O8Lmta4iQg2D9cr28F7DTQ/0
2019/05/08 22:59:28 Running task https://tools.taskcluster.net/task-inspector/#HQWKWi_zQVm_pR4fAIq-RA/0
2019/05/09 01:34:50 Running task https://tools.taskcluster.net/task-inspector/#MxZWnvPHRduh6D3jyhGAnQ/0
2019/05/09 01:56:22 Running task https://tools.taskcluster.net/task-inspector/#AAnBl_1QSq63WBdjpYZagg/0
2019/05/09 04:26:50 Running task https://tools.taskcluster.net/task-inspector/#Wg7UkC1dQsSUD7DQpYONgQ/0
2019/05/09 04:44:10 Running task https://tools.taskcluster.net/task-inspector/#AFDc1X9CTD6czpre17NdFQ/0
2019/05/09 05:39:53 Running task https://tools.taskcluster.net/task-inspector/#Fen3wDtLSLSQASgHmZZt-Q/0
2019/05/09 05:40:43 Running task https://tools.taskcluster.net/task-inspector/#Wd1egFEhQrmP6evkP2r-Cg/0
2019/05/09 06:40:59 Running task https://tools.taskcluster.net/task-inspector/#I1STRL9NTqqIH3zu_pcflQ/0
2019/05/09 10:14:46 Running task https://tools.taskcluster.net/task-inspector/#GfECbGA6QAiu0o2oA23B_w/0
2019/05/09 13:32:12 Running task https://tools.taskcluster.net/task-inspector/#SrVPeuSaTPuxcMO7hb8Xuw/0
2019/05/09 17:26:27 Running task https://tools.taskcluster.net/task-inspector/#deakuGCNQtG8pB1f07y0zA/0
2019/05/09 19:11:08 Running task https://tools.taskcluster.net/task-inspector/#RzTt9A-nSOivkhw59sRWQg/0
2019/05/09 19:28:14 Running task https://tools.taskcluster.net/task-inspector/#Bqj1j6goTamAhbpL3DFiwg/0
2019/05/09 19:43:48 Running task https://tools.taskcluster.net/task-inspector/#D3LmIBwsT8u7w9LFffzCfQ/0
2019/05/09 20:19:12 Running task https://tools.taskcluster.net/task-inspector/#GEyyd6vUSka6tfYm_VXl1Q/0
2019/05/09 20:27:14 Running task https://tools.taskcluster.net/task-inspector/#Hbyn4eLjRC2DLUeURZRduA/0
2019/05/09 22:28:17 Running task https://tools.taskcluster.net/task-inspector/#WNbY46ryRXaq67ljEow_ig/0
2019/05/10 00:43:24 Running task https://tools.taskcluster.net/task-inspector/#FeGXLcSGR22CmNQyA-Ty5Q/0
2019/05/10 01:30:40 Running task https://tools.taskcluster.net/task-inspector/#Jc66ZvvbTmC6IoJ5gsEXJA/0
2019/05/10 01:56:57 Running task https://tools.taskcluster.net/task-inspector/#JFiFKxikRRiwHLzXfH9_Dg/0
2019/05/10 04:05:10 Running task https://tools.taskcluster.net/task-inspector/#LP_vyGf2SNmIM706YNbe0g/0
2019/05/10 04:20:46 Running task https://tools.taskcluster.net/task-inspector/#Xqa5IIONSOeXg9LaYQB7oA/0
2019/05/10 06:06:29 Running task https://tools.taskcluster.net/task-inspector/#MPb69QzoSlmDxYQP5jpT_A/0
2019/05/10 07:00:03 Running task https://tools.taskcluster.net/task-inspector/#F815BNKoSHezR3wEHDdxIg/0
2019/05/10 07:56:55 Running task https://tools.taskcluster.net/task-inspector/#TYiNb6lQRs6tWQGPzHFxZw/0
2019/05/10 08:25:05 Running task https://tools.taskcluster.net/task-inspector/#aDHu4fIbRxmMOxapAkKlog/0
2019/05/10 09:34:58 Running task https://tools.taskcluster.net/task-inspector/#RbffKu9BTwSRK2a-pA583g/0
2019/05/10 11:44:44 Running task https://tools.taskcluster.net/task-inspector/#OtsV6SqWRBqO7bk7aXKmwg/0
2019/05/10 13:22:26 Running task https://tools.taskcluster.net/task-inspector/#OgMaAHkJQgKInfTR65RRFw/0
2019/05/10 13:23:21 Running task https://tools.taskcluster.net/task-inspector/#bgb17E76QYSGfQSEKLUfBQ/0
2019/05/10 14:12:30 Running task https://tools.taskcluster.net/task-inspector/#XDK6F3B3Siu4J9pCbCHS2w/0
2019/05/10 14:33:06 Running task https://tools.taskcluster.net/task-inspector/#AbJVjCpbTxOzxf3pzc09XQ/0
2019/05/10 14:37:45 Running task https://tools.taskcluster.net/task-inspector/#Km9XYzxETnKUgpo7yQBvow/0
2019/05/10 14:43:21 Running task https://tools.taskcluster.net/task-inspector/#e4tEXRl0TwK2FwLjHYoxWw/0
2019/05/10 14:48:29 Running task https://tools.taskcluster.net/task-inspector/#G0__8KWsSKuK4CB9tYjiLA/0
2019/05/10 14:51:52 Running task https://tools.taskcluster.net/task-inspector/#e4tEXRl0TwK2FwLjHYoxWw/1
2019/05/10 15:05:43 Running task https://tools.taskcluster.net/task-inspector/#DWImEo6YTf6RHofZ5xxr5g/0
2019/05/10 15:11:26 Running task https://tools.taskcluster.net/task-inspector/#ZCBaiM05S1yUZ4weEyNb8w/0
2019/05/10 16:23:20 Running task https://tools.taskcluster.net/task-inspector/#T3lHjpKsRIm5SpYk8W2A1Q/0
2019/05/10 17:48:34 Running task https://tools.taskcluster.net/task-inspector/#Q8wp_ncnQFKWFUNbzbnzsA/0
2019/05/10 17:51:16 Running task https://tools.taskcluster.net/task-inspector/#T-BWTcv2TQGo55c8Ur-uww/0
2019/05/10 18:07:25 Running task https://tools.taskcluster.net/task-inspector/#ND7CkOLWSvaEAYzGz4aTRA/0
2019/05/10 19:50:02 Running task https://tools.taskcluster.net/task-inspector/#QrJT4nLIQIuhbjEIBI3ZuQ/0
2019/05/10 20:27:02 Created dir: /Users/worker/tasks/task_1557520022/generic-worker
2019/05/10 21:34:42 Running task https://tools.taskcluster.net/task-inspector/#DP6dgIK2SliQuHMwzVUySQ/0
2019/05/10 22:27:22 Running task https://tools.taskcluster.net/task-inspector/#avHDrL2HR6qT-AR0aZa51w/0
2019/05/11 01:21:44 Running task https://tools.taskcluster.net/task-inspector/#Nnwzbz-XS4O3CB30OsSUlg/0
2019/05/11 05:50:55 Running task https://tools.taskcluster.net/task-inspector/#BZxeVbZLRbS6jr-FnmUB2g/0
2019/05/11 07:37:08 Running task https://tools.taskcluster.net/task-inspector/#fck5OAuoRZSMdIGqrr_WUg/0
2019/05/12 10:14:19 Running task https://tools.taskcluster.net/task-inspector/#SE3A-ZFQS72MuYG3d9_Q7w/0
2019/05/13 17:17:43 Running task https://tools.taskcluster.net/task-inspector/#FrrPxXoRRcqIBI4PO8q3yw/0
2019/05/13 18:08:58 Running task https://tools.taskcluster.net/task-inspector/#JehUUTd5SpC7cFKH3VyP2Q/0
2019/05/13 18:57:44 Running task https://tools.taskcluster.net/task-inspector/#WytudpcoRWep2p-gzd2SBw/0
2019/05/13 19:03:19 Running task https://tools.taskcluster.net/task-inspector/#SNs2XzyBRbetDIMANtkz6A/0
2019/05/13 21:52:12 Created dir: /Users/worker/tasks/task_1557784332/generic-worker
2019/05/13 21:53:06 Running task https://tools.taskcluster.net/task-inspector/#Re7hBbjeSgmHopk3xE5gqQ/0
2019/05/13 21:53:36 Running task https://tools.taskcluster.net/task-inspector/#dBQq21oIRiCvKa-AtG45xg/0
2019/05/13 21:54:02 Running task https://tools.taskcluster.net/task-inspector/#N9CtI5xnT8miVgzBw4Du6Q/0
2019/05/13 21:54:28 Running task https://tools.taskcluster.net/task-inspector/#YVyMGDk3TwSd9tVKq-lDsw/0
2019/05/13 21:54:56 Running task https://tools.taskcluster.net/task-inspector/#Dv5HiApKR8-o7xwclcAghg/0
2019/05/13 21:55:23 Running task https://tools.taskcluster.net/task-inspector/#aKjvGflSS8-fh3AczLFw6Q/0
2019/05/13 21:55:51 Running task https://tools.taskcluster.net/task-inspector/#Z6J2ZdnyS7-xWnPOb2oHFA/0
2019/05/13 23:53:19 Running task https://tools.taskcluster.net/task-inspector/#GSUPZX_nTz6MvWfGBfuOKg/0
2019/05/14 00:35:58 Running task https://tools.taskcluster.net/task-inspector/#A_voxhgvStqkrXGtDoO2hg/0
2019/05/14 01:10:40 Running task https://tools.taskcluster.net/task-inspector/#dGKNZR35StqJK7mbMcoRCA/0
2019/05/14 02:05:41 Running task https://tools.taskcluster.net/task-inspector/#OijDp7J9RT2i2sx9dyofAQ/0
2019/05/14 02:48:44 Running task https://tools.taskcluster.net/task-inspector/#IlUWtwY8RmGlaY1qkdSUAQ/0
2019/05/14 10:14:13 Running task https://tools.taskcluster.net/task-inspector/#aMmjJawSTXaCkHNaoxih6Q/0
```

**Comment by SimonSapin** [comment]
This reminds me: I was surprised a few days ago to see some build task compile much quicker (and many fewer crates) than expected. If they run in the same directory as a previous task, that would explain it!

**Comment by petemoore** [comment]
DeepSpeech are also experiencing the same issue, apologies for this bug.

I'm working on a fix for this in [bug 1551164](https://bugzil.la/1551164). In the meantime, you could either revert to an older version of the worker, or maybe configure it to run just a single task (generic-worker config setting `numberOfTasksToRun`) and run the worker in a loop. My guess is that it is just creating a task user when it starts up, and these workers do not reboot between tasks.

**Comment by jdm** [comment]
It's working! This is ready for review.

**Comment by jdm** [comment]
This error makes me very nervous:
```
error[E0464]: multiple matching crates for `libc`
  --> /Users/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/atty-0.2.11/src/lib.rs:21:1
   |
21 | extern crate libc;
   | ^^^^^^^^^^^^^^^^^^
   |
   = note: candidates:
           crate `libc`: /Users/worker/.rustup/toolchains/nightly-2019-05-14-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-ba9beb64bc1e5758.rlib
           crate `libc`: /Users/worker/.rustup/toolchains/nightly-2019-05-14-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-845f77709e8b62d3.rlib
error[E0463]: can't find crate for `libc`
  --> /Users/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/atty-0.2.11/src/lib.rs:21:1
   |
21 | extern crate libc;
   | ^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to 2 previous errors
```

**Pull request merged**
