### PR TITLE
Update WR (Intel driver workaround, subpixel and other bugfixes).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16917)

### CODE REVIEW

**Comment by glennw** [comment]
I have a sneaking suspicion that the rayon changes in this PR are going to cause a heap of timeouts. But let's try anyway...

**Comment by glennw** [comment]
r? anyone

**Comment by glennw** [comment]
Rebased and updated to tip of WR with fix for #16777.

**Comment by jdm** [comment]
```
  ▶ TIMEOUT [expected PASS] /_mozilla/css/border_radius_elliptical_a.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected PASS] /_mozilla/css/border_radius_shorthand_a.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected PASS] /_mozilla/css/box_shadow_blur_fixed.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ TIMEOUT [expected PASS] /_mozilla/css/filter_opacity_a.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 12.0.1
  └ Shutting down the Constellation after generating an output file or exit flag specified
```

**Comment by glennw** [comment]
@bors-servo r=Wafflespeanut

 * Rebased and updated to tip of WR. I suspect this is still going to timeout, but let's just test and see.

**Comment by glennw** [comment]
@bors-servo try
 * A lot of weird failures - let's see if they occur again on a try run.

**Comment by jdm** [comment]
@glennw That's #16982.

**Comment by glennw** [comment]
@jdm Does that mean we should just retry this with an r+ ?

**Comment by jdm** [comment]
Yep!

**Comment by jdm** [comment]
@bors-servo: try- retry
#16982

**Comment by jdm** [comment]
Travis says:
```
92.19s$ ./mach build -d --verbose

cargo build -v

    Updating git repository `https://github.com/servo/webrender`

error: failed to load source for a dependency on `webrender_traits`

Caused by:

  Unable to update https://github.com/servo/webrender#c003d553

Caused by:

  failed to fetch into /home/travis/build/servo/servo/.cargo/git/db/webrender-c3596abe1cf4f320

Caused by:

  [9/-3] Object not found - no match for id (6902f7d200ad115e5e9a95e08303db15f0f0dbba)

Build FAILED in 0:00:00

The command "./mach build -d --verbose" exited with 101.
```

**Comment by jdm** [comment]
Actually, that looks like https://github.com/servo/servo/issues/16787 so ignore it.

**Comment by glennw** [comment]
@jdm Hmmm. I have not confirmed this, but my guess is that switching the rayon thread count to a maximum of 2 per process is triggering our data race bugs in different ways, that's making our known intermittents appear on different tests :(

I can possibly revert the WR change that I think is causing this (we used to hard code the rayon worker thread count to 4), but that seems like a very fragile fix / hack.

Alternatively, we could consider updating intermittent expectations for a lot of tests, which doesn't seem ideal either.

Any thoughts?

Either way - I'm going to run the tests again locally and see if they repro here, just to rule out anything else in WR causing this. But there's really just a small number of WR bug fixes in this update, nothing that I would expect to cause these issues...

**Comment by hiikezoe** [comment]
A very similar failure happened on my other PR.
https://github.com/servo/servo/pull/16959#issuecomment-302992536

So I think the fail is not this PR fault at all.

**Comment by emilio** [comment]
@glennw note that only one known non-flacky test failed here (see the `filtered-wpt-errorsummary.log` artifact).

And that one is #16982.

@bors-servo retry

**Comment by nox** [comment]
Travis seems unhappy, I hope that wasn't an actual issue.

**Pull request merged**
