### PR TITLE
Fix for issue #6768. Refactor ReadData and BlobBody

### PR DESCRIPTION
**Pull request by pr0hin**
Fix for issue #6768.

Merge common fields of ReadData and BlobBody to avoid passing redundant information to functions.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6944)

### CODE REVIEW

**Comment by jdm** [comment]
Thanks for doing this work @r0e! However, there are a lot of indentation changes that are either incorrect (https://github.com/r0e/servo/commit/00c7a0575e8209ce70edbfe6a3037da9b833d3ee#diff-86a64de2e20a4f0e05816b3c9256087eR92, https://github.com/r0e/servo/commit/00c7a0575e8209ce70edbfe6a3037da9b833d3ee#diff-86a64de2e20a4f0e05816b3c9256087eR108, etc.) or at least quite distracting from the important changes here. Would you be able to undo those changes, or at least split them into a separate commit for easier review?

**Comment by r0e** [comment]
Whoops, I thought Vim's "=G" command would take care of all my indentation errors. Guess it created more problems than it solved... I'll get on it.

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review -S-awaiting-answer +S-awaiting-merge 
Thanks for the patch!

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6944)

**Comment by jdm** [comment]
@bors-servo: retry
* #6818

**Comment by jdm** [comment]
@bors-servo: retry
* #6818

**Comment by jdm** [comment]
@bors-servo: retry
* #6818

**Comment by jdm** [comment]
@bors-servo: retry
* #6818 

I swear we're actually fixing #6818 simultaneously. Until this we're just getting super unlucky in this PR.

**Comment by jdm** [comment]
@bors-servo: retry
* #6818

**Pull request merged**
