### PR TITLE
Add PutForwards to implemented attributes that lacked it

### PR DESCRIPTION
**Pull request by pshaughn**
Added PutForwards to three relLists and one style. The style already had a test; I added tests for relLists, including one relList that we have commented out right now.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes advance #9990 to be caught up with the attributes we have so far; many unimplemented attributes will need PutForwards when implemented.

- [X] There are tests for these changes OR

### CODE REVIEW

**Comment by Manishearth** [comment]
```
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?include=HTML.*:
  └ PASS [expected FAIL] HTMLLinkElement interface: attribute relList
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?include=HTML.*:
  └ PASS [expected FAIL] HTMLAnchorElement interface: attribute relList
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?include=HTML.*:
  └ PASS [expected FAIL] HTMLAreaElement interface: attribute relList


  ▶ Unexpected subtest result in /dom/nodes/attributes.html:
  └ PASS [expected FAIL] Toggling element with inline style should make inline style disappear
  ▶ Unexpected subtest result in /css/cssom/idlharness.html:
  └ PASS [expected FAIL] HTMLElement interface: attribute style

  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by zero degrees is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by positive angle in degrees is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by positive angle in radians is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by positive angle in gradians is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by positive angle in turns is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by negative angle is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by fractional angle is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by maxumum 90 degree angle is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by minimum -90 degree angle is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by positive angle is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by calc is valid
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by calc is valid even if it must be clamped (no computation)
  ▶ Unexpected subtest result in /css/css-fonts/variations/font-style-parsing.html:
  └ PASS [expected FAIL] Font-style (computed): 'oblique' followed by calc is valid even if it must be clamped (with computation)
```

**Comment by jdm** [comment]
@bors-servo retry
* #25588 #24726

**Comment by jdm** [comment]
@bors-servo retry
* #25513

**Pull request merged**
