### PR TITLE
Properly insert text in document when parsing

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14867)

### CODE REVIEW

**Comment by metajack** [comment]
This needs a little bit of comment. It's not clear what this is for unless you read the spec.

r=me with that addressed.

**Comment by nox** [comment]
I forgot to update x5e, so style elements don't get parsed at all when in XHTML now...

Looking into the other failures now.

**Comment by nox** [comment]
Oh nice. The new line number tracking means that every "\n" gets its own Text node because we don't coalesce adjacent Text children when parsing, thus many unrelated test failures.

**Comment by nox** [comment]
https://github.com/Ygg01/xml5ever/pull/24 for the XML issues.

**Pull request merged**
