### PR TITLE
Bump serde to 1.0

### LINKED ISSUE #16556: Update serde to 1.0.0

### PR DESCRIPTION
**Pull request by Eijebong**
Update serde to 1.0

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #16556

- [x] These changes do not require tests because it's a dependency bump

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17325)

### CODE REVIEW

**Comment by Eijebong** [comment]
Should be fixed (I hope !)

**Comment by Eijebong** [comment]
Turns out if you don't declare lifetimes, they don't exist... Who would have guessed that ?

**Comment by jdm** [comment]
Could you provide links to all of the relevant PRs in other repositories?

**Comment by Eijebong** [comment]
Everything is in there https://github.com/servo/servo/issues/16556#issuecomment-303492221

**Comment by SimonSapin** [comment]
I’ve added https://github.com/servo/string-cache/pull/190 which was missing, and published https://crates.io/crates/string_cache/0.6.0.

@Eijebong, https://github.com/servo/webrender/pull/1359#issuecomment-308964750 is now waiting on you, and once that lands you should be able to remove the `[replace]` entries.

Thanks for all your work!

**Comment by SimonSapin** [comment]
@Eijebong I took over in https://github.com/servo/servo/pull/17355, I hope you don’t mind :)

**Comment by Eijebong** [comment]
This can be closed. Thanks @SimonSapin

**Pull request closed without merging**
