### PR TITLE
layout: Implement `pointer-events: none` per SVG 1.1 § 16.6.

### PR DESCRIPTION
**Pull request by pcwalton**
SVG-only values are not yet supported.

r? @mbrubeck

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed on Critic, with one open question.

**Comment by pcwalton** [comment]
@mbrubeck Addressed comment. I had to rebase this over a rustup and Critic didn't seem to like that.

**Comment by mbrubeck** [comment]
Looks good to me.  Can land after the rust update.

**Comment by jdm** [comment]
Ready for squash+rebase.

**Pull request closed without merging**
