### PR TITLE
Merge adjacent text nodes while appending

### LINKED ISSUE #5828: Join adjacent text nodes in tree sink while appending
The "html5 tokenizer" tests at html5test demonstrate that `e.innerHTML = "&lang;&rang;";` produces two text nodes in Servo, not one.

Relevant source at https://github.com/NielsLeenheer/html5test/blob/ce8268b2ec71ebdfa6fc6cefc989ba8e6ce544e5/scripts/6/engine.js#L412-L480 .

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes #5828. r? @jdm or @kmcallister

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5829)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Note: This only handles the `append` case.  I'll file a follow-up issue to merge text nodes in `append_before_sibling` too.  That will let us get rid of `get_or_create` completely.

**Comment by jdm** [comment]
Reviewed files:
- components/script/parse/html.rs @ r1

---

<sup>**[components/script/parse/html.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5829#-JnhN5ndmE_UjYlWQ2S6)** ([raw file](https://github.com/servo/servo/blob/f8070affdbc776a3e2bd8629089215a8f04aa850/components/script/parse/html.rs#L159)):</sup>
You can cast directly from Node->CharacterData instead

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5829)

**Comment by mbrubeck** [comment]
<sup>**[components/script/parse/html.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5829#-JnhN5ndmE_UjYlWQ2S6)** ([raw file](https://github.com/servo/servo/blob/f8070affdbc776a3e2bd8629089215a8f04aa850/components/script/parse/html.rs#L159)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5829)

**Comment by jdm** [comment]
Reviewed files:
- components/script/parse/html.rs @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5829)

**Comment by jdm** [comment]
+S-needs-squash -S-awaiting-review 

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5829)

**Comment by mbrubeck** [comment]
This breaks the following reftests

      * `acid2_noscroll.html == acid2_ref_broken.html`
      * `filter_inline_a.html == filter_inline_ref.html`
      * `text_align_complex_a.html == text_align_complex_ref.html`

`filter_inline_a.html` is broken because of [a comment in a `<style>` element](https://github.com/servo/servo/blob/211ee668fae7f619ac7e09abd776a6f45fc40052/tests/ref/filter_inline_a.html#L7).  Servo doesn't re-parse the `<style>` contents when an existing Text child is modified (#976).

I haven't determined yet whether the other two tests are broken for similar reasons or different ones.

**Comment by mbrubeck** [comment]
mbrubeck/servo@7f7ecc2d1eeb002f69cb7f121a62d1b36a30950e is a sketch of a solution to the `filter_inline_a` breakage.  It does not fix the other two failures, though. :(

**Comment by Ms2ger** [comment]
And commented on critic

**Comment by mbrubeck** [comment]
`text_align_complex_a` is broken because html5ever calls `append_text` separately for each `'\r'`-separated line of text in the `<style>` element, and even if we re-parse after each call, we end up processing the CSS rules in a bad order (since we can't yet unload the results of previous parses).

**Comment by metajack** [comment]
@mbrubeck What's the plan for this?

**Comment by mbrubeck** [comment]
I think this is blocked until other improvements are made to stylesheet handling, like the ability to remove or modify an existing stylesheet.  Closing this for now.

**Pull request closed without merging**
