### PR TITLE
Move PaintListener to gfx_traits, Fixes #8834

### LINKED ISSUE #8834: Move PaintListener to gfx_traits
This trait is only used by `gfx/` and `compositing/`, so it's an easy candidate to move out of the grab-bag `msg/` crate.

Code: `components/msg/compositor_msg.rs`, `components/gfx_traits/lib.rs`, `components/gfx/paint_task.rs`

### PR DESCRIPTION
**Pull request by cnaj**
Adding layers and msg dependency to gfx_traits.

Fixes #8834.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8939)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Looks great, thank you!

@bors-servo r+

**Comment by cnaj** [comment]
Hmm, http://build.servo.org/builders/linux-dev/builds/848 and http://build.servo.org/builders/mac-rel-css/builds/860 look good... Do the tests have a history of timing out, or is it more likely to be my change?

**Comment by jdm** [comment]
There's no way that this changed caused that problem. It's super weird though, and I've never seen it before!

**Comment by jdm** [comment]
@bors-servo: retry
* #8944

**Pull request merged**
