### PR TITLE
Dispatch error events at the window object.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13156)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer 

r=me otherwise.

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/error.rs, line 234 \[r1\]](https://reviewable.io:443/reviews/servo/servo/13156#-KQa19Q5G4FFMGgUiHi1:-KQa19Q5G4FFMGgUiHi2:b-emnqtr) ([raw file](https://github.com/servo/servo/blob/2121d4ea0f1e7ea0cb6dde32a7a802c93f3d4f3f/components/script/dom/bindings/error.rs#L234)):*
> ```Rust
>                     }
>                 },
>                 _ => {
> ```

One of the possible values here signals a pending exception, can that be a problem?

---

*[tests/wpt/web-platform-tests/html/webappapis/scripting/processing-model-2/addEventListener.html, line 16 \[r1\]](https://reviewable.io:443/reviews/servo/servo/13156#-KQa1E675Ffs0MJ0OCxS:-KQa1E675Ffs0MJ0OCxT:bmpw3fr) ([raw file](https://github.com/servo/servo/blob/2121d4ea0f1e7ea0cb6dde32a7a802c93f3d4f3f/tests/wpt/web-platform-tests/html/webappapis/scripting/processing-model-2/addEventListener.html#L16)):*
> ```HTML
>     window.addEventListener('error', t.step_func(function(e){
>         ran = true;
>         assert_true(e.isTrusted, 'isTrusted');
> ```

Could you make a separate commit for this, given it then goes in WPT's history?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13156#-:-KQa1KHXs8BoIUaADb25:bo5djyy)*

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/error.rs, line 234 \[r1\]](https://reviewable.io:443/reviews/servo/servo/13156#-KQa19Q5G4FFMGgUiHi1:-KQa28c1KZ_1wW8KLN5U:brrl0iu) ([raw file](https://github.com/servo/servo/blob/2121d4ea0f1e7ea0cb6dde32a7a802c93f3d4f3f/components/script/dom/bindings/error.rs#L234)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> One of the possible values here signals a pending exception, can that be a problem?
</details>
`ToString` on a primitive should not throw; I guess `panic` would be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13156)*

**Pull request merged**
