### PR TITLE
Improvements, cleanup for script::dom::document

### PR DESCRIPTION
**Pull request by frewsxcv**
- Add whatwg spec links for some Document methods
- Wrap some lines that exceed 100 characters
- Other misc cleanup/refactoring

### CODE REVIEW

**Comment by frewsxcv** [comment]
Just realized this doesn't compile. Hold off on reviewing for now...

**Comment by frewsxcv** [comment]
There were a few issues. I could have probably fixed them but I'm too tired right now so just reverting for now. This is ready for review.

**Comment by frewsxcv** [comment]
Rebased

**Comment by Ms2ger** [comment]
Looks good, you can squash now.

**Comment by frewsxcv** [comment]
squashed

**Pull request closed without merging**
