### PR TITLE
Move remaining users of the legacy networking stack to fetch.

### PR DESCRIPTION
**Pull request by Ms2ger**
Fixes #13931.
Fixes #13714.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13961)

### CODE REVIEW

**Comment by Ms2ger** [comment]
> ```
>   ▶ CRASH [expected OK] /workers/Worker_cross_origin_security_err.htm
>   │ 
>   │ VMware, Inc.
>   │ Gallium 0.4 on softpipe
>   │ 3.3 (Core Profile) Mesa 12.0.1
>   │ Unimplemented scheme for Fetch (thread fetch thread for ftp://example.org/support/WorkerBasic.js, at /Users/servo/buildbot/slave/mac-rel-wpt2/build/components/net/fetch/methods.rs:496)
>   │ stack backtrace:
>   │    0:        0x10923c63e - backtrace::backtrace::trace::h6ac07ced1b846a59
>   │    1:        0x10923c92c - backtrace::capture::Backtrace::new::h1d3339ed08c7f861
>   │    2:        0x108018d74 - servo::main::_{{closure}}::hce6009c73746ec98
>   │    3:        0x1099d55f3 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
>   │    4:        0x10818f694 - std::panicking::begin_panic::hc03e2830c2c89a5f
>   │    5:        0x108276780 - net::fetch::methods::basic_fetch::ha806911f4cd925a5
>   │    6:        0x108272a9a - net::fetch::methods::main_fetch::hb454a78ecbf1c83c
>   │    7:        0x10819053a - std::panicking::try::do_call::h1db0bf7c9a597e4b
>   │    8:        0x1099d661a - __rust_maybe_catch_panic
>   │    9:        0x1081cc206 - _<F as alloc..boxed..FnBox<A>>::call_box::h3a6dba867d2cc296
>   │   10:        0x1099d44a4 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
>   │   11:     0x7fff88879059 - _pthread_body
>   │   12:     0x7fff88878fd6 - _pthread_start
>   │ ERROR:servo: Unimplemented scheme for Fetch
>   │ Pipeline failed in hard-fail mode.  Crashing!
>   └ thread panicked while processing panic. aborting.
> ```

Looks like that's the only problem. I think I'll just change to returning network errors for `ftp` fetches.

r? @jdm, but review the dependent PRs first :)

**Comment by jdm** [comment]
This is good to merge once #13931 merges.

**Comment by Ms2ger** [comment]
@bors-servo r=jdm

Let's land them all at once.

**Pull request merged**
