### PR TITLE
layout: Implement `<table width>` and `<center>`.

### PR DESCRIPTION
**Pull request by pcwalton**
Improves Hacker News.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5980)

### CODE REVIEW

**Comment by jdm** [comment]
I feel like the changes that add servo_center here are missing.

**Comment by mbrubeck** [comment]
`servo_center` is added in the `define_text_align!` macro in properties.rs.mako.

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/block.rs @ r1
- components/layout/inline.rs @ r1
- components/style/properties.mako.rs @ r1
- resources/presentational-hints.css @ r1
- resources/quirks-mode.css @ r1
- resources/servo.css @ r1
- tests/ref/basic.list @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5980)

**Comment by mbrubeck** [comment]
Reviewed files:
- components/style/legacy.rs @ r1
- tests/ref/servo_center_a.html @ r1
- tests/ref/servo_center_ref.html @ r1
- tests/ref/table_width_attribute_a.html @ r1
- tests/ref/table_width_attribute_ref.html @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5980)

**Comment by mbrubeck** [comment]
r+, needs rebase.

**Comment by waddlesplash** [comment]
```
Unexpected Results
==================

/html/rendering/non-replaced-elements/tables/table-width-150percent.html
------------------------------------------------------------------------
PASS expected FAIL [Parent]
```

**Comment by SimonSapin** [comment]
Shouldn’t the `-servo-center` keyword only be allowed in UA stylesheets?

**Pull request merged**
