### PR TITLE
Introduce VirtualMethods::children_changed()

### PR DESCRIPTION
**Pull request by nox**
This virtual method mimics the behaviour of mutation observers and make it more viable than the older child_inserted(), which didn't cover removed nodes and was called as many times as there were inserted nodes.

A few other shortcomings where remove_child() was called directly instead of Node::remove() were also fixed while at it.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6660)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@pcwalton removed the vector allocation in the non-`DocumentFragment` case in 8ab354ac; I expect he'll have something to say about bringing it back.

@bzbarsky: do you have any thoughts on the best approach here?

**Comment by nox** [comment]
@pcwalton I don't see how we can afford to not bring it back if we ever support mutation observers.

Maybe an enum `Zero`, `One(&Node)`, `Many(&RootedVec<JS<Node>>)`?

**Comment by nox** [comment]
Seems like I forgot to fix Node.replaceChild().

**Comment by nox** [comment]
I think we are better off passing around an enumeration representing each kind of changes that can happen to children of a node, instead of 2 vectors and 2 nodes.

With the 2 vectors and 2 nodes, implementors have to handle cases that don't exist, like removing n out of m children of a node, while the only removal cases that exist are removing a single node or all of them.

**Comment by pcwalton** [comment]
Maybe use a `SmallVec`?

**Comment by nox** [comment]
@pcwalton So I should make a RootedSmallVec I guess?

**Comment by nox** [comment]
There is a problem on insertion, because children_changed() isn't called when the nodes are removed from their original parents.

**Comment by nox** [comment]
Misunderstood the problem, children_changed() was called too many times because remove() didn't check whether the suppress observers flag was set or not.

**Comment by jdm** [comment]
I've looked through node.rs and cross-checked the various node manipulation algorithms in the spec against our implementation. It appears as though in the cases in which we execute an algorithm with observers suppressed (and therefore don't call children_changed), we later explicitly call children_changed for the same set of affected nodes. Accordingly, these changes look good to me with a couple small considerations.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 2605 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6660#-Jv4mav_U4osDPAt6KSH)** ([raw file](https://github.com/servo/servo/blob/e0faeef75ef0eaba3800dc8883d6c959f525a0b0/components/script/dom/node.rs#L2605)):</sup>
I'm inclined to recommend struct variants here so we can name these fields clearly.

---

<sup>**[components/script/dom/node.rs, line 2622 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6660#-Jv4nesEHXRmzC73Iela)** ([raw file](https://github.com/servo/servo/blob/e0faeef75ef0eaba3800dc8883d6c959f525a0b0/components/script/dom/node.rs#L2622)):</sup>
nit: move added_nodes to a new line.

Why is removed_node &&?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6660)

**Comment by nox** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 2622 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6660#-Jv4nesEHXRmzC73Iela)** ([raw file](https://github.com/servo/servo/blob/e0faeef75ef0eaba3800dc8883d6c959f525a0b0/components/script/dom/node.rs#L2622)):</sup>
Will move it, but removed_node is a && so that I can call ref_slice() on it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6660)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6660)

**Pull request merged**
