### PR TITLE
Stylo: Add constructors for @font-face descriptors

### PR DESCRIPTION
**Pull request by canova**
Part of https://bugzilla.mozilla.org/show_bug.cgi?id=1340728

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix [Bug #1340728](https://bugzilla.mozilla.org/show_bug.cgi?id=1340728)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15695)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r-

I asked canaltinova to use ServoBundledURI instead

**Comment by canaltinova** [comment]
Updated this PR and bugzilla bug. Sorry for the delay.

**Comment by Manishearth** [comment]
@bors-servo r+

Be sure to remove the servo changes from your bugzilla bug and re-push so that we can land that immediately after this gets copied over.

**Pull request merged**
