### PR TITLE
Implement Element.innerHTML setter

### PR DESCRIPTION
**Pull request by ChrisParis**
This addresses #849.  This PR cannot land until the corresponding PR (https://github.com/servo/html5ever/pull/91) in html5ever lands. I've done some simple testing of this code, but I don't consider it thorougly tested yet. I wanted to start getting feedback about the overall design before I spend more time polishing the details, and testing.

### CODE REVIEW

**Comment by Manishearth** [comment]
I somehow expected a lot more WPT tests to start passing (since a lot of them use `innerHTML`), but they seem to  not use the setter much. Oh well.

**Comment by eddyb** [comment]
IIRC this was needed by both Facebook and Polymer in my experiments, I don't think we need anything significant to get the former to work (the latter would still deal with a handful of custom JS polyfills).

**Comment by Manishearth** [comment]
(Mobile facebook *does* work, btw, though images don't load for some reason. Commenting and stuff doesn't work though)

**Comment by kmcallister** [comment]
Comments added on Critic.

**Comment by jdm** [comment]
@kmcallister: Ball's in your court.

**Comment by jdm** [comment]
This needs a rebase, and presumably can't merge until we do the next rust upgrade.

**Comment by jdm** [comment]
As soon as this is rebased, it's good to merge :)

**Pull request closed without merging**
