### PR TITLE
Refactor http_fetch to reflect the new standard

### PR DESCRIPTION
**Pull request by KiChjang**
Partial #4576. The spec is really getting funky now - it's depending more and more on the DOM objects (e.g. prompting the user for authentication using a `Window` object). I think we can just pass in username and password as properties of the `Request` struct though.

I've also added in the async version for http_request.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8516)

### CODE REVIEW

**Comment by jdm** [comment]
I think the most complicated part here is figuring out the best way to avoid cloning the contents of `response` and `actualResponse` multiple times, since those could mean significant memory usage for large response bodies.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[components/net/fetch/request.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_d2i-mAZ4RlrObKWS:-K3_d2i-mAZ4RlrObKWT:-2054865613) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L154)):_
Let's create a method to encapsulate this common concept.

---

_[components/net/fetch/request.rs, line 215 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_d8e5QffByiQMl7sd:-K3_d8e5QffByiQMl7se:1090565188) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L215)):_
This clone shouldn't be necessary.

---

_[components/net/fetch/request.rs, line 257 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_df8_YjYjeGMCW65r:-K3_df8_YjYjeGMCW65s:1869797219) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L257)):_
I wonder if this should be `Option<&Response>` instead, or we should be using `Rc<RefCell<Response>>` (or maybe just `Rc<Response>`) to avoid cloning the full response contents at various points in this method. Also, we might be able to use `let actual_response;` and avoid the unwrap later.

---

_[components/net/fetch/request.rs, line 369 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_f81G9L-9kF7yFZIU:-K3_f81G9L-9kF7yFZIV:-1218675951) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L369)):_
I think this reads better as the match.

---

_[components/net/fetch/request.rs, line 381 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_fNYwqanu181p627A:-K3_fNYwqanu181p627B:2142228042) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L381)):_
If we write this as `else` and assert, we should be able to avoid the clone in the previous branch.

---

_[components/net/fetch/request.rs, line 390 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_fdK_GQLz70llLDKC:-K3_fdK_GQLz70llLDKD:-2089500635) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L390)):_
nit: unnecessary ()

---

_[components/net_traits/lib.rs, line 107 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_g18a8WsMid61g2SB:-K3_g18a8WsMid61g2SC:-1166793612) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net_traits/lib.rs#L107)):_
vec![]

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516#-:-K3_g3fKxi6h_0YPYltc:1874906263)_

**Comment by KiChjang** [comment]
Whew! Addressed some issues through 1337 h4x, will look at this later again to figure out what to do with the rest.

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[components/net/fetch/request.rs, line 369 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_f81G9L-9kF7yFZIU:-K3aaTqlbGRgJdfeax2D:1428714154) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L369)):_
I wanted to, but the match arm will consume the url. I can do `Ok(ref url)`, but I'll have to clone the inner url in order to be assigned to location_url.

---

_[components/net/fetch/request.rs, line 381 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_fNYwqanu181p627A:-K3dY6WDvQZjyhhuCiLo:618503908) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L381)):_
Might as well use a match statement.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516#-:-K3dYGZKBxNEWM3pRM7x:-1630086903)_

**Comment by KiChjang** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[components/net/fetch/request.rs, line 369 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_f81G9L-9kF7yFZIU:-K3da5gGMzXVR1KRQvia:300269589) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L369)):_
*Nevermind.* Hacking saves the day.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516)_

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[components/net/fetch/request.rs, line 218 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3e5AEelt98GBQEs1fw:-K3e5AEfqY6aPhU-3RKE:877887523) ([raw file](https://github.com/servo/servo/blob/2d0ee6668be5429926bf44c3c175cf185e70d17e/components/net/fetch/request.rs#L218)):_
Can this not be `let url = self.url_list.last().unwrap().clone();`?

---

_[components/net/fetch/request.rs, line 370 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3e4_K7qV4YBS5zgsSh:-K3e4_K8yQ_W5G_euLjM:1055531646) ([raw file](https://github.com/servo/servo/blob/2d0ee6668be5429926bf44c3c175cf185e70d17e/components/net/fetch/request.rs#L370)):_
Ok(ref url) if url.scheme == "data" => return Response::network_error(),
Ok(url) => url,
_ => return Response::network_error(),

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516#-:-K3e5koZZEvOa0FnQQFA:1458266033)_

**Comment by KiChjang** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[components/net/fetch/request.rs, line 257 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_df8_YjYjeGMCW65r:-K3hjjzFrdP35bxXiw9F:-1400944402) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L257)):_
I'm beginning to see that the `actual_response` must at least be an Option<Response> since it's nullable. I'm still trying to see whether it's possible to wrap it around a `RefCell`, a `Rc` or both together.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516)_

**Comment by KiChjang** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[components/net/fetch/request.rs, line 257 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_df8_YjYjeGMCW65r:-K3nDx2xi16AWebwOQO1:-121286886) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L257)):_
Ok, I think it'll be way easier if I can sort of type-cast one type of pointer into another, e.g. from a Box to a &-pointer, or from an Rc pointer to a Box/&-pointer, etc. Can I actually do that?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516)_

**Comment by jdm** [comment]
`Smart pointer<T>` -> `&T` is possible with `&*`.

**Comment by KiChjang** [comment]
Almost there! I just need to fix a couple of ownership issues.

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[components/net/fetch/request.rs, line 345 \[r6\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3snO9J3zqXlFyOdVwZ:-K3snO9J3zqXlFyOdVw_:-152311395) ([raw file](https://github.com/servo/servo/blob/b06693dd4c29ca367205f6fe14fb6a1487e0babf/components/net/fetch/request.rs#L345)):_
These `unwrap()` operations here start throwing me compiler errors saying that I cannot move out of borrowed content. But I do own these Options...

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516#-:-K3sn-mAatJAN-VYB7zc:994710190)_

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[components/net/fetch/request.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_d2i-mAZ4RlrObKWS:-K4-hw_TW1Bvu1Q_3FP7:-1146770398) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L154)):*
In case it was unclear, I meant "get the last element of the url list".

---

*[components/net/fetch/request.rs, line 215 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4-gdGGsYn4LmPWJis2:-K4-gdGGsYn4LmPWJis3:-415565424) ([raw file](https://github.com/servo/servo/blob/55261680f112c9437b0567e2e52bfbbe950c0f70/components/net/fetch/request.rs#L215)):*
I think we can get away with `&self.url_list.last().as_ref().unwrap().scheme`?

---

*[components/net/fetch/request.rs, line 152 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4-ha5aibjkAB0STsc9:-K4-ha5aibjkAB0STscA:-432869984) ([raw file](https://github.com/servo/servo/blob/9c4e008d5cac7dbd335a437b7d7b18cada92f7cb/components/net/fetch/request.rs#L152)):*
Why this change? I thought all invocations of fetch algorithm concepts were synchronous after the initial asynchronous one.

---

*[components/net/fetch/request.rs, line 342 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4-iIcEQehpzhp4AOXA:-K4-iIcEQehpzhp4AOXB:753395594) ([raw file](https://github.com/servo/servo/blob/9c4e008d5cac7dbd335a437b7d7b18cada92f7cb/components/net/fetch/request.rs#L342)):*
Why this change?

---

*[components/net/fetch/request.rs, line 345 \[r6\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3snO9J3zqXlFyOdVwZ:-K4-kVTOKAl9hYo0tj4r:252586748) ([raw file](https://github.com/servo/servo/blob/b06693dd4c29ca367205f6fe14fb6a1487e0babf/components/net/fetch/request.rs#L345)):*
Ah, the problem is that we're dereferencing through the Rc, which is an immutable borrow. We can use Rc::try_unwrap to work around that, as long as there's only one strong reference to `actual_response` here.

---

*[components/net_traits/lib.rs, line 123 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4-i45Q1hkKuX7uM_b7:-K4-i45Q1hkKuX7uM_b8:248255533) ([raw file](https://github.com/servo/servo/blob/9c4e008d5cac7dbd335a437b7d7b18cada92f7cb/components/net_traits/lib.rs#L123)):*
I'm not convinced this is necessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516#-:-K4-l90GXZLy5T7xDXXz:1458266033)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[components/net/fetch/request.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8516#-K3_d2i-mAZ4RlrObKWS:-K4-lzGj9Tgt_EJ5gmwK:955469662) ([raw file](https://github.com/servo/servo/blob/d95a46d45c88d5cf9a4b513cf349b28aff3b3c58/components/net/fetch/request.rs#L154)):*
Ah, then ignore the new fetch_async method and the corresponding `FetchKind` enum.

---

*[components/net/fetch/request.rs, line 342 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4-iIcEQehpzhp4AOXA:-K4-m9JfbsxIPS29UXdN:1076158692) ([raw file](https://github.com/servo/servo/blob/9c4e008d5cac7dbd335a437b7d7b18cada92f7cb/components/net/fetch/request.rs#L342)):*
The spec actually had removed this match arm and instead moved the handling of 304 to `http_network_or_cache_fetch`

---

*[components/net_traits/lib.rs, line 123 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4-i45Q1hkKuX7uM_b7:-K4-mb6SiLepuPJR04Di:-360100975) ([raw file](https://github.com/servo/servo/blob/9c4e008d5cac7dbd335a437b7d7b18cada92f7cb/components/net_traits/lib.rs#L123)):*
I'll revert this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516)*

**Comment by KiChjang** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/net/fetch/request.rs, line 215 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4-gdGGsYn4LmPWJis2:-K455z9JkK5ijTAHiAHl:1393986892) ([raw file](https://github.com/servo/servo/blob/55261680f112c9437b0567e2e52bfbbe950c0f70/components/net/fetch/request.rs#L215)):*
The idea here is that `self.url_list` cannot be taken as an immutable reference, because the `self.http_fetch` call down there is a mutable reference, and both scopes clash with each other.

---

*[components/net/fetch/request.rs, line 152 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4-ha5aibjkAB0STsc9:-K455HC6OrqACAI1Gd8i:-220740999) ([raw file](https://github.com/servo/servo/blob/9c4e008d5cac7dbd335a437b7d7b18cada92f7cb/components/net/fetch/request.rs#L152)):*
`main_fetch` is actually very asynchronous (that's why I had so much trouble implementing it earlier this year). I imagine one the possible solution to that is to generate a channel while waiting for some of the steps to finish.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/net/fetch/request.rs, line 351 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4582l97RJhWqrlDMiC:-K4582l97RJhWqrlDMiD:2142863479) ([raw file](https://github.com/servo/servo/blob/5f66d23edfd1e44ddb53b0a2235a87d023993aca/components/net/fetch/request.rs#L351)):*
I think the `ok()` is unnecesary here.

---

*[components/net/fetch/request.rs, line 352 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4587vAslXiNibH4zd2:-K4587vAslXiNibH4zd3:-1213865979) ([raw file](https://github.com/servo/servo/blob/5f66d23edfd1e44ddb53b0a2235a87d023993aca/components/net/fetch/request.rs#L352)):*
Here too.

---

*[components/net/fetch/request.rs, line 386 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8516#-K458DnHqCeYxn31a4t8:-K458DnHqCeYxn31a4t9:337890906) ([raw file](https://github.com/servo/servo/blob/5f66d23edfd1e44ddb53b0a2235a87d023993aca/components/net/fetch/request.rs#L386)):*
This should be using `*response.borrow_mut() = ...` to update the value inside refcell instead of creating a new one.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516#-:-K458MScRyrjsidLje_j:1458266033)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/net/fetch/request.rs, line 351 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4582l97RJhWqrlDMiC:-K4593jiz3pT9ImK-z0Y:-464103454) ([raw file](https://github.com/servo/servo/blob/5f66d23edfd1e44ddb53b0a2235a87d023993aca/components/net/fetch/request.rs#L351)):*
Nope, wouldn't compile if I remove the `ok()`, because `try_unwrap` returns a `Result`.

---

*[components/net/fetch/request.rs, line 352 \[r7\]](https://reviewable.io:443/reviews/servo/servo/8516#-K4587vAslXiNibH4zd2:-K459B72nnSKLpi7hSKL:-1209553044) ([raw file](https://github.com/servo/servo/blob/5f66d23edfd1e44ddb53b0a2235a87d023993aca/components/net/fetch/request.rs#L352)):*
Ditto above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516)*

**Comment by jdm** [comment]
`unwrap` is a method defined on `Result` too, so I'm not sure what the issue is.

**Comment by KiChjang** [comment]
```
/home/keith/Workspace/servo/components/net/fetch/request.rs:351:76: 351:84 error: no method named `unwrap` found for type `core::result::Result<core::cell::RefCell<net_traits::Response>, alloc::rc::Rc<core::cell::RefCell<net_traits::Response>>>` in the current scope
/home/keith/Workspace/servo/components/net/fetch/request.rs:351         let mut actual_response = Rc::try_unwrap(actual_response.unwrap()).unwrap().into_inner();
                                                                                                                                           ^~~~~~~~
/home/keith/Workspace/servo/components/net/fetch/request.rs:351:76: 351:84 note: the method `unwrap` exists but the following trait bounds were not satisfied: `alloc::rc::Rc<core::cell::RefCell<net_traits::Response>> : core::fmt::Debug`
```

**Comment by jdm** [comment]
Ah, I see - the last line of that is the reason why we can't use `unwrap` directly.

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8516#-:-K45DYeKO2su8oz2M0_G:-317921516)*

**Pull request merged**
