### PR TITLE
Save / restore state when updating opaque framebuffer bindings

### LINKED ISSUE #27286: Hololens 2 rendering issues with Unity and WebXR - Regression?
In the current Firefox Reality in the Microsoft Hololens store, AR session works and rendered as intended.
But the nightly build version ( 13/07 ServoApp_1.1.0.0_x64_arm64 ), has some rendering issues:

- Rendering order.

- Smearing on transparent background.

I took screenshots from the emulator, but as I understood from people with the device, it's the same.

This is how it looks on the store version, you can see that the rendering order is right, and the transparent background is black (as the emulator doesn't show scene mesh by default):
image

This is how the same AR session looks in the nightly build. You can see the smearing of the numbers and other objects. You can also see some errors in rendering order, the hand model should be near the user and not behind the floating table:
image

This is how it looks when I tried to use `WebGLRenderingContext.clear` (`COLOR_BUFFER_BIT` `DEPTH_BUFFER_BIT` and with and without `STENCIL_BUFFER_BIT`) at the frame start. There's no smearing, but the hand is rendered behind the floating table:
image

As far as I know, on AR mode we shouldn't use clear at the frame start, as in Handheld and Video see through devices, it has the camera image. If we use clear at the frame start, we won't see the camera image.

### PR DESCRIPTION
**Pull request by asajeffrey**
This saves and restores the WebGL bindings for texture and framebuffer when beginning a webxr frame.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #27286
- [x] These changes do not require tests because we don't reftest hololens (it would be nice if we did!)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Also updates webxr to pull in https://github.com/servo/webxr/pull/185

**Comment by Manishearth** [comment]
@bors r+

nice catch!

**Comment by jdm** [comment]
```
  ▶ CRASH [expected OK] /_mozilla/webxr/layers.html
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ called `Result::unwrap()` on an `Err` value: InvalidEnum (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/dom/xrwebgllayer.rs:239)
  │    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  │    1: core::fmt::write
  │    2: std::io::Write::write_fmt
  │    3: servo::backtrace::print
  │    4: servo::main::{{closure}}
  │    5: std::panicking::rust_panic_with_hook
  │    6: _rust_begin_unwind
  │    7: core::panicking::panic_fmt
  │    8: core::option::expect_none_failed
  │    9: script::dom::xrwebgllayer::XRWebGLLayer::begin_frame
  │   10: script::dom::xrrenderstate::XRRenderState::with_layers
  │   11: <script::dom::xrsession::XRSession::setup_raf_loop::{{closure}}::xr_raf_callback<F> as script::task::TaskOnce>::run_once
  │   12: <T as script::task::TaskBox>::run_box
  │   13: script::script_thread::ScriptThread::handle_msgs
  │   14: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  │   15: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   17: std::sys::unix::thread::Thread::new::thread_start
  │   18: __pthread_body
  │   19: __pthread_start
  │ [2020-07-18T03:03:35Z ERROR servo] called `Result::unwrap()` on an `Err` value: InvalidEnum
  └ Pipeline failed in hard-fail mode.  Crashing!

  ▶ CRASH [expected OK] /_mozilla/webxr/obtain_frame.html
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ called `Result::unwrap()` on an `Err` value: InvalidEnum (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/dom/xrwebgllayer.rs:239)
  │    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  │    1: core::fmt::write
  │    2: std::io::Write::write_fmt
  │    3: servo::backtrace::print
  │    4: servo::main::{{closure}}
  │    5: std::panicking::rust_panic_with_hook
  │    6: _rust_begin_unwind
  │    7: core::panicking::panic_fmt
  │    8: core::option::expect_none_failed
  │    9: script::dom::xrwebgllayer::XRWebGLLayer::begin_frame
  │   10: <script::dom::xrsession::XRSession::setup_raf_loop::{{closure}}::xr_raf_callback<F> as script::task::TaskOnce>::run_once
  │   11: <T as script::task::TaskBox>::run_box
  │   12: script::script_thread::ScriptThread::handle_msgs
  │   13: profile_traits::mem::ProfilerChan::run_with_memory_reporting
  │   14: std::sys_common::backtrace::__rust_begin_short_backtrace
  │   15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  │   16: std::sys::unix::thread::Thread::new::thread_start
  │   17: __pthread_body
  │   18: __pthread_start
  │ [2020-07-18T03:04:09Z ERROR servo] called `Result::unwrap()` on an `Err` value: InvalidEnum
  └ Pipeline failed in hard-fail mode.  Crashing!
```

**Comment by asajeffrey** [comment]
Sigh, crashes on macos due to surface textures there being `GL_RECTANGLE` not `GL_TEXTURE2D`. @bors-servo r=Manishearth

**Comment by jdm** [comment]
@bors-servo retry
* #27315

**Pull request merged**
