### PR TITLE
stylo: Bump app units version

### PR DESCRIPTION
**Pull request by Manishearth**
r=emilio https://bugzilla.mozilla.org/show_bug.cgi?id=1383492

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17878)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r-
```
error: failed to select a version for `app_units` (required by `style`):

all possible versions conflict with previously selected versions of `app_units`

  version 0.5.0 in use by app_units v0.5.0

  possible versions to select: 0.5.1
```

**Comment by Manishearth** [comment]
oh, right, need a lockfile update on this end

**Pull request merged**
