### PR TITLE
partial-fix #12415: incorrect exposure of Window,Worker in webidl

### PR DESCRIPTION
**Pull request by woshilapin**
---

- [x] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix (partially) #12415 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they don't add any feature

- HTMLParagraphElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlparagraphelement)]
- HTMLParamElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlparamelement)]
- HTMLPreElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlpreelement)]
- HTMLProgressElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlprogresselement)]
- HTMLQuoteElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlquoteelement)]
- HTMLScriptElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlscriptelement)]
- HTMLSelectElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlselectelement)]
- HTMLSourceElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlsourceelement)]
- HTMLSpanElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlspanelement)]
- HTMLStyleElement.webidl [[spec](https://html.spec.whatwg.org/multipage/#htmlstyleelement)]

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12526)

### CODE REVIEW

**Comment by nox** [comment]
@Ms2ger I think your advice to not do it all at once backfired. What do we do?

**Comment by Ms2ger** [comment]
This one needs an update to `tests/wpt/mozilla/tests/mozilla/interfaces.worker.js` too.

**Comment by woshilapin** [comment]
I modified `interfaces.worker.js` accordingly.  Should I relaunched `bors-servo`?

**Pull request merged**
