### PR TITLE
Bump rust-url version: 0.2.16 → 0.2.35

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6286)

### CODE REVIEW

**Comment by jdm** [comment]
This should really include the updates to the various Cargo.lock files, too.

**Comment by jdm** [comment]
@bors-servo: r+
My mistake, those files are already ahead here.

**Comment by frewsxcv** [comment]
Huh. I would have figured Cargo would complain since (prior to this PR) our packages require 0.2.16 and hyper required 0.2.35. If you have any insight into that, I'm curious

**Comment by frewsxcv** [comment]
Answer to my question:

> Caret requirements allow SemVer compatible updates to a specified version, 0.1 and 0.2 are not considered compatible, but 1.0 and 1.1 are for example. If no operator is specified, this is the default requirement (e.g. 1.3 is the same as ^1.3).

http://doc.crates.io/crates-io.html

**Comment by SimonSapin** [comment]
@frewsxcv, because of that Cargo behaviour, you only need to change the requirements in `Cargo.toml` if you’re using a e.g. new feature that was introduced in that version. If you just want to update, `./mach update-cargo -p url` is enough. (It’ll change `Cargo.lock` files.)

**Comment by frewsxcv** [comment]
@SimonSapin Yeah, I learned that after I opened this PR. Thanks for the information

**Pull request merged**
