### PR TITLE
Prepare stylo crates for switching to the 2018 edition

### PR DESCRIPTION
**Pull request by SimonSapin**
This can land when [Gecko requires Rust 1.30](https://bugzilla.mozilla.org/show_bug.cgi?id=1504031). This does not switch the crates yet because the new edition is not yet stable in 1.30.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22083)

### CODE REVIEW

**Comment by SimonSapin** [comment]
CC @emilio

**Comment by SimonSapin** [comment]
This is blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1504031

**Comment by SimonSapin** [comment]
I’ve verified that `(cd components/style && cargo check --features gecko)` works, after copying `../gecko/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/debug/build/style-*/out/gecko/*` to `components/style/gecko/generated/` and applying this diff:

```diff
diff --git a/components/style/Cargo.toml b/components/style/Cargo.toml
index 15e4175160..8e9cbaaf30 100644
--- a/components/style/Cargo.toml
+++ b/components/style/Cargo.toml
@@ -73,6 +73,7 @@ uluru = "0.3"
 unicode-bidi = "0.3"
 unicode-segmentation = "1.0"
 void = "1.0.2"
+nsstring = {path = "../../../gecko/servo/support/gecko/nsstring"}
 
 [build-dependencies]
 lazy_static = "1"
diff --git a/components/style/properties/properties.mako.rs b/components/style/properties/properties.mako.rs
index 072b78cf37..3cd111b8ad 100644
--- a/components/style/properties/properties.mako.rs
+++ b/components/style/properties/properties.mako.rs
@@ -427,7 +427,7 @@ pub const NON_CUSTOM_PROPERTY_ID_COUNT: usize =
 #[allow(dead_code)]
 unsafe fn static_assert_nscsspropertyid() {
     % for i, property in enumerate(data.longhands + data.shorthands + data.all_aliases()):
-    std::mem::transmute::<[u8; ${i}], [u8; ${property.nscsspropertyid()} as usize]>([0; ${i}]); // ${property.name}
+//    std::mem::transmute::<[u8; ${i}], [u8; ${property.nscsspropertyid()} as usize]>([0; ${i}]); // ${property.name}
     % endfor
 }
 % endif

**Comment by emilio** [comment]
Huh, why does static_assert_nscsspropertyid no longer hold?

**Comment by SimonSapin** [comment]
Honestly I’m not sure. Some other errors were files when I rebuilt gecko with the commit that had the same message as your last sync commit in servo, but these persisted. Could there be a difference between using `--feature use_bindgen` v.s. not?

There are 44 errors: https://gist.github.com/rust-play/fa2dcae2579e5daa6cd77a9f057836e4

The differences between expected and actual IDs are all either -8, -6, 4, 8, or 10: https://gist.github.com/rust-play/352434b01b59d3e34f610ddadace3f35, so it looks like the sorting is not the same.

**Comment by SimonSapin** [comment]
Added a commit to fix unrelated infra issue that was uncovered now because of a cache expiration.

@bors-servo r=emilio

**Pull request merged**
