### PR TITLE
Refactor the `call` hook on non-callback interface objects (fixes #10744)

### LINKED ISSUE #10744: Calling DOM constructors without new should throw
Blocks #2185.

Depends on the in-progress SpiderMonkey upgrade. (*Do not attempt this right now.*)

* Spec: <https://www.w3.org/Bugs/Public/show_bug.cgi?id=22808>.
* Code: `components/script/dom/bindings/codegen/CodegenRust.py`.
* Test: `dom/events/Event-constructors.html`.

See <https://hg.mozilla.org/mozilla-central/rev/de377011ed9d>.

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10819)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Nice.

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/bindings/interface.rs, line 187 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10819#-KGBiHWpQ27xFnxWtuMF:-KGBiHWpQ27xFnxWtuMG:-1025542714) ([raw file](https://github.com/servo/servo/blob/47e6babba5dda675a6da61e99c6193e6d476c2cf/components/script/dom/bindings/interface.rs#L187)):*
We should probably consistently use en-US in comments too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10819#-:-KGBitnfhJ6-JrvLxTT1:-490100116)*

**Comment by nox** [comment]
Addressed the nit. r+'ing as discussed on IRC.

@bors-servo r=Ms2ger

**Pull request merged**
