### PR TITLE
Move bindings tests out of the style crate

### PR DESCRIPTION
**Pull request by SimonSapin**
This cuts in almost half the time to run:

```
touch components/style/lib.rs
./mach test-stylo
```

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16935)

### CODE REVIEW

**Comment by emilio** [comment]
r=me, with a reference to https://github.com/rust-lang/cargo/issues/3544 somewhere there

**Review by emilio — APPROVED** [review]

**Comment by SimonSapin** [comment]
Messed up my previous commit.

@bors-servo r=emilio

**Pull request merged**
