### PR TITLE
Fix keyboard on windows issue 12937

### LINKED ISSUE #12937: Text input rendering previous keypress on Windows
In this [video](http://elahn.com.au/uploads/Servo%2019_08_2016%206_19_56%20PM%20%28compressed%29.mp4), I clicked on the input, typed: `mozilla.org[enter][enter]`. Nothing appeared in the input until the 2nd key, 'o' was pressed and with each keypress, the state as of the previous keypress was rendered.

Windows 10 Home x64 with anniversary update on real hardware.

### PR DESCRIPTION
**Pull request by codec-abc**
This is an attempt to fix the behavior of the input elements on Windows to fix #12937. Now, the input fields mostly work for the most part but the backspace key has a weird behavior and there is probably a couple of funkyness elsewhere By the way, I tried to align the keyboard events so we got the same in MacOs & Linux **and** Windows. A couple of things to notes:

1. There are 2 types of events associated with keyboard: Key event (up or down) and Character Input.
2. A character is not necessary created one a key is pressed (like the home key).
3. A character may be created only using a combination of several key. For example, using a Qwerty International layout you have to type `` `  then e to get é. The first key press on ` `` will create no character.
4. In servo, we currently merge the 2 events together, meaning that we store a Character Input event in a field to fire a single event later on when we get a Key event.
5. The order of events seems to be system dependent. For example, let's say that we type the A key on a Qwerty Layout. In Linux and MacOs we will get this:
* Character Input for character A
* Key down event with virtual key code of the key A
* Key up event with virtual key code of the key A
while in Windows we get:
* Key down event with virtual key code of the key A
* Character Input for character A
* Key up event with virtual key code of the key A
6. It seems that glutin make no attempt to reorder the event to make the order independent of the Operating System. I think it would be easier for Servo if it were handled by the library.
7. The Js event generated by Servo seems to be correct when testing on [this page](https://mathiasbynens.be/demo/oninput) but not on Windows (before or after my changes). They may be no more correct in MacOs and Linux after my changes since I tried to align the event to a kind of middle ground. By the way this page may be serve a basic for a good test for input event order.
---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix (partially) #12937.

- [X] There are **NO** tests for these changes because I don't know how to write them and what to write.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16193)

EDIT: I do not like the code I have written because there is quite a lot of platform dependent code in it. It would probably be proper create a file per platform so the logic behind may be encapsulated in those files.

### CODE REVIEW

**Comment by jonathandturner** [comment]
Just gave this a spin.  While yeah, looks like we're getting the keys when we press them, I'm seeing things like backspace no longer work.  It's not immediately obvious to me what's going wrong looking at the code, but I suspect non-printable characters aren't getting the same way they were before and we're missing a step, potentially.

**Comment by codec-abc** [comment]
Yeah, it seems weird since if I remember correctly when I pressed backspace the character was erased but then a square appear right away. Now while I think of it I remember a warning about not using the filter_nonprintable function and looking at the code it seems it is not used on Windows.

**Comment by jonathandturner** [comment]
Yeah, I'd believe that.  When I was looking around before, I didn't see a way to check if the key was printable in the keydown event.  Do you know of one?

**Comment by codec-abc** [comment]
I am not sure If I follow you since in the keydown event you should get the virtual key code (except if I missed something) and could use (almost as it is) the filter_nonprintable function.

**Comment by jonathandturner** [comment]
@codec-abc - Ahh, I misread what approach you were trying to take.  I'm curious if your way works.  If it does, it seems like the right way to do it.

**Comment by codec-abc** [comment]
Go ahead if you want to test it because I will not have time tomorrow.

**Comment by jonathandturner** [comment]
@codec-abc - done: https://github.com/servo/servo/pull/16198

I agree, still not a perfect solution, but this one appears to work decently in practice and may be enough to get us going until we come up with a better solution.

**Comment by codec-abc** [comment]
Thanks! I will close this one since your PR goes a step further and fix more bugs.

**Pull request closed without merging**
