### PR TITLE
Implement Gradle flavors for Android VR compilations

### PR DESCRIPTION
**Pull request by MortimerGoro**
This PR adds support to easily generate Android VR builds. Rust/Java VR dependencies are not added by default.

Default build (No VR support)
```
./mach build --release --android
./mach package --release --android
./mach install --release --android
```

GoogleVR builds (e.g. Daydream)
```
./mach build --release --android --features googlevr
./mach package --release --android --flavor googlevr
./mach install --release --android
```

OculusVR builds (e.g. Gear VR)
```
./mach build --release --android --features oculusvr
./mach package --release --android --flavor oculusvr
./mach install --release --android
```

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18680)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
This is totally awesome! Great work.

@bors-servo r+

**Comment by larsbergstrom** [comment]
@bors-servo retry

Servo-mac3 was getting `too many open files` so I gave it a reboot.

**Comment by KiChjang** [comment]
```
error: cannot find macro `identity_matrix!` in this scope
   --> C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-webvr-0.9.3\src\api\openvr\display.rs:374:20
    |
374 |             *out = identity_matrix!();
    |                    ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by MortimerGoro** [comment]
Windows error fixed

**Pull request merged**
