### PR TITLE
Update WR (font instance API).

### PR DESCRIPTION
**Pull request by glennw**
WR now has a concept of font templates and font instances. This
makes the WR font interfaces closer to Cairo and Gecko, and also
makes some future performance optimizations possible.

A font template is the font family, and data backing the font.
A font instance is a reference to a font template and per-instance
options, such as font size, anti-aliasing settings etc.

To update Servo in a minimally invasive way, I added a new font
cache call, that creates a font instance. This means that when
a font is created, and doesn't exist in the cache there are now
two calls to the font cache thread. We could refactor the font
cache to make this work in one call, which we should do in the
future. However, refactoring the font cache is a large chunk of
work by itself. The extra call is only when a font doesn't already
exist in the font context cache, so it should have minimal
performance impact.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18322)

### CODE REVIEW

**Comment by glennw** [comment]
@bors-servo retry
 * infra

**Comment by glennw** [comment]
I also removed the font cache unit test. It now requires a WR API instance, so it's not really amenable to unit testing in its current state. I think the existing test was of very dubious value, anyway.

**Review by emilio — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo: retry
* #18228

**Pull request merged**
