### PR TITLE
Implement GetActiveAttrib

### PR DESCRIPTION
**Pull request by dzbarsky**
@emilio

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10379)

### CODE REVIEW

**Comment by emilio** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/dom/webglrenderingcontext.rs, line 760 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10379#-KEQCmKI2C2hKukpp7A_:-KEQCmKJFSBwUSpgLOHQ:59502429) ([raw file](https://github.com/servo/servo/blob/c0183f15584e799edd419c6367f5a0321fc8a988/components/script/dom/webglrenderingcontext.rs#L760)):*
I'd prefer this logic to be hoisted to `WebGLProgram`.

Appart from that, `r=me` when the related prs land.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10379)*

**Comment by nox** [comment]
There is no spec link, nor test.

**Comment by emilio** [comment]
@nox: You're right about the spec link, tests are covered in https://github.com/servo/servo/pull/10373

**Comment by nox** [comment]
Ok.

**Comment by emilio** [comment]
Arrg, sorry for missing this, I *really* hate GH not sending any notification when commits are pushed... 

Could you ping me when rebased? (I'll try to be careful and keep looking at it though)

Sorry again! :/

**Comment by dzbarsky** [comment]
@emilio ping :)

**Comment by emilio** [comment]
@bors-servo: r+

Now you just have to get those tests landed to please @nox ;-)

**Comment by emilio** [comment]
@bors-servo: retry
 * https://github.com/servo/servo/issues/8931

**Comment by emilio** [comment]
@bors-servo: retry
   * #8931

**Pull request merged**
