### PR TITLE
Avoid codesize impact of pushing in PropertyDeclaration::parse, take 2

### PR DESCRIPTION
**Pull request by Manishearth**
Trying #14950 with a different approach.

@mbrubeck could you check what the impact of the second commit here is?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15279)

### CODE REVIEW

**Comment by mbrubeck** [comment]
This reduced the size of `PropertyDeclaration::parse` by 20KB, though it increased the total text size of libxul.so.   I'll take a look next to see if I can figure out why the total size went up.

**Comment by mbrubeck** [comment]
Part of the size increase is from this symbol which only appears when the patch is applied, maybe because an inlining decision changed:

```
VM SIZE NAME
------- ----
 73.9Ki _ZN77_$LT$style..properties..PropertyDeclaration$u20$as$u20$core..clone..Clone$G
```

The rest is from dozens of symbols named like this (as reported by `bloaty`).  I don't know where they come from:

```
VM SIZE NAME
------- ----
 11.9Ki ref.1F1
 11.9Ki ref.1F3
 11.9Ki ref.1F5
 11.9Ki ref.1FZ
 11.9Ki ref.1G1
 11.9Ki ref.1G3
```

**Comment by Manishearth** [comment]
D'oh that's because extend_from_slice clones. The only way to get rid of this issue is unsafe code since the compiler doesn't know that `DeclaredValue::Initial` is copyable.

**Comment by nox** [comment]
@Manishearth No, it is [specialised](https://doc.rust-lang.org/src/collections/vec.rs.html#1658-1670).

**Comment by Manishearth** [comment]
@nox Specialization can't fix this. If an enum is clone the copyable variants are still only clone. `DeclaredValue::Initial` can't be `Copy`d because `DeclaredValue::Longhand(..)` can't.

**Comment by nox** [comment]
Ah this is not the whole enum you were talking about? What did you want to do with unsafe code then? How do you guarantee none of the non-`Copy` variants were used?

**Comment by Manishearth** [comment]
Write unsafe code to manually construct `&[Initial, Initial, Initial, ...]`.

There's no issue with non-Copy variants being used, this is codegenned at compile time for Initial/Unset/Inherit.

**Comment by jdm** [comment]
Is this going anywhere?

**Comment by Manishearth** [comment]
Nah, and this has changed significantly since.

**Pull request closed without merging**
