### PR TITLE
style: Import changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21452)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r+

(@asajeffrey took a look at https://github.com/servo/servo/pull/21452/commits/935b5393a9af765798bb0ad9e423fdf7394ec5b6, which was the non-trivial bit).

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1484459 tracks the mozilla-central side of this.

**Comment by emilio** [comment]
```

    ['filter-intermittents', 'wpt-errorsummary.log', '--log-intermittents', 'intermittents.log', '--log-filteredsummary', 'filtered-wpt-errorsummary.log', '--tracker-api', 'default', '--reporter-api', 'default']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

  File "/home/servo/buildbot/slave/linux-rel-css/build/python/servo/testing_commands.py", line 546, in filter_intermittents
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

@bors-servo retry

**Comment by emilio** [comment]
@jdm do you know what that error is about? It's a 500 when trying to run WPT.

**Comment by jdm** [comment]
@bors-servo retry
* https://github.com/servo/intermittent-failure-tracker/issues/5

**Pull request merged**
