### PR TITLE
fixed BaseAudioContext.DecodeAudioData progress callback

### LINKED ISSUE #25840: Intermittent failure in /webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html
The failing test name contains the audio values that change each run, so it's hard to get a stables test result.

### PR DESCRIPTION
**Pull request by khodzha**
Gstreamer backend returns channel as single bit mask (ie 1, 2, 4, 8, 32 etc).
Progress callback was using this mask as plain channel index, thus storing decoded
audio in wrong channel.

(log2 conversion of int to int is subpar at best, but idk how to extract bit position in a clean way without a loop, any suggestions are welcome)

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25840

- [X] There are tests for these changes

### CODE REVIEW

**Comment by ferjm** [comment]
Thanks!

@bors-servo r+

**Comment by khodzha** [comment]
tbh maybe its better to replace plain ints with some kind of tuple struct to distinguish bitmask and channel index?

**Pull request merged**
