### PR TITLE
Add missing CanvasRenderingContext2D global composition operation "clear"

### PR DESCRIPTION
**Pull request by pylbrecht**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #25331 

- [x] There are tests for these changes

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by pylbrecht** [comment]
```
  ▶ FAIL [expected TIMEOUT] /css/css-values/vh-interpolate-px.html
  │   → /css/css-values/vh-interpolate-px.html 905d73d986b751bc4889dbb8a3481f3d0d604673
  │   → /css/css-values/reference/all-green.html ca9048d25067fe2666ee98ffdaee4d41e63aa283
  │   → Screenshot is solid color 0xFF0000 for /css/css-values/vh-interpolate-px.html
  │   → 
  └   → Screenshot is solid color 0x008000 for /css/css-values/reference/all-green.html
```
@jdm, I tried searching this in servo's issues, but did not find anything. Is this one new or how do I find the the issues corresponding to the intermittent failures?

**Comment by jdm** [comment]
I added that failure to #24748. Adding the numbers is only for documentation; it doesn't affect the behaviour of the retry.

**Comment by jdm** [comment]
@bors-servo retry
* #24726 #25513

**Pull request merged**
