### PR TITLE
style: Split stylesheets.rs

### PR DESCRIPTION
**Pull request by emilio**
This file has become quite bloated lately. This commit deletes that file in
favor of a set of submodules.

The only noticeable change apart from code move, is converting deep_clone_foo
methods into a trait.

It also unifies logic related to different style rules in the same place.

There's some missing work, specially related to font-face and counter-style, but
I think this is worth landing in the meantime.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17154)

### CODE REVIEW

**Comment by Manishearth** [comment]
> `+2,298 −1,995`

unacceptable

**Review by Manishearth — APPROVED** [review]

**Comment by emilio** [comment]
> error: Could not compile `webdriver_server`.

wat

@bors-servo retry p=1

**Pull request merged**
