### PR TITLE
style: Optimize serialization of identifiers of length <= 16 🐉🐲

### PR DESCRIPTION
**Pull request by emilio**
Much like we optimize to_ascii_lowercase.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19974)

### CODE REVIEW

**Comment by nox** [comment]
r=me with a green geckotry. Nice dragoning.

**Comment by jdm** [comment]
@bors-servo r-
Fails test-tidy and fails ./mach build.

**Comment by emilio** [comment]
Thanks @jdm, fixed

**Comment by emilio** [comment]
@bors-servo try

 * I'll add a test for the unknown namespace thingie if there isn't one.

**Comment by emilio** [comment]
@bors-servo r=nox

 * Upon reflection servo doesn't support generated content with namespaced attributes...

**Comment by jdm** [comment]
@bors-servo retry
#13479

**Pull request merged**
