### PR TITLE
Optimise Node.childNodes

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6778)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6778)

**Comment by jdm** [comment]
@bors-servo: r-
Sorry, forgot to review the second commit.

---

Review status: 2 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6778)

**Comment by jdm** [comment]
Ok, so I understand how this caching works. I definitely want to see before and after Dromaeo measurements, and these changes _really_ need thorough comments explaining each case and why it's safe to use unwrap when we do. I spent a long time working through each case and I think I've convinced myself that they're mostly correct, but I'd hate to have to do that every single time I need to review changes in the future. I'd also like to see a thorough set of tests that exercise all of these cases and ensure that child NodeLists never end up returning incorrect values.
-S-awaiting-review +S-needs-code-changes +S-awaiting-answer +S-needs-tests 

---

Reviewed 3 of 3 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/nodelist.rs, line 118 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrPSyxaSRq6IEPXIGr)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L118)):</sup>
Some comments in this method would have been useful on my first time looking through it.

---

<sup>**[components/script/dom/nodelist.rs, line 166 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrMiAhlUvjxw55Vrlc)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L166)):</sup>
Let's just use an early return if len.is_empty().

---

<sup>**[components/script/dom/nodelist.rs, line 170 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrOc3Ch1fr2WZH8mGI)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L170)):</sup>
This part of the decision tree could really use an explanation; I assume this is a heuristic, but why and how was it decided?

---

<sup>**[components/script/dom/nodelist.rs, line 187 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrP8rSZKoDMb5ByI3A)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L187)):</sup>
Let's extract this arm into a separate function too.

---

<sup>**[components/script/dom/nodelist.rs, line 194 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrW1oahjtyaBtt6lUC)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L194)):</sup>
What about `<span id="s">a</span>` and `var s = document.getElementById('s'); s.childNodes; s.firstChild.remove()`?

---

<sup>**[components/script/dom/nodelist.rs, line 222 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrY2W4oxTXB5MAyOzh)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L222)):</sup>
Why this choice?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6778)

**Comment by nox** [comment]
Before, after, and Gecko, for the tears: http://dromaeo.com/?id=239572,239573,239574

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/nodelist.rs, line 119 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrPSyxaSRq6IEPXIGr)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L119)):</sup>
Will add some.

---

<sup>**[components/script/dom/nodelist.rs, line 167 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrMiAhlUvjxw55Vrlc)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L167)):</sup>
Ok.

---

<sup>**[components/script/dom/nodelist.rs, line 171 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrOc3Ch1fr2WZH8mGI)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L171)):</sup>
I try to avoid moving around during mutations, assuming it's traversed linearly. The only improvements I could see over a single "sentinel" last_visited are either a big array of all the children or a fancy skip list that has yet to be implemented.

---

<sup>**[components/script/dom/nodelist.rs, line 188 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrP8rSZKoDMb5ByI3A)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L188)):</sup>
Ok.

---

<sup>**[components/script/dom/nodelist.rs, line 195 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrW1oahjtyaBtt6lUC)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L195)):</sup>
I specifically unwrap because such a case should be propagated as ReplaceAll by ChildrenMutation::remove().

---

<sup>**[components/script/dom/nodelist.rs, line 223 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrY2W4oxTXB5MAyOzh)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L223)):</sup>
Same as above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6778)

**Comment by nox** [comment]
AFAICT, there are already many tests that involve childNodes in WPT, they caught many issues in the kind you are scared of, rightly so.

-S-awaiting-answer 

---

Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6778)

**Comment by jdm** [comment]
-S-awaiting-review -S-needs-tests +S-needs-code-changes 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/nodelist.rs, line 195 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6778#-JvrW1oahjtyaBtt6lUC)** ([raw file](https://github.com/servo/servo/blob/30e0417b2a3dd3e181829f133cbc1d84e0e9e064/components/script/dom/nodelist.rs#L195)):</sup>
I would be more comfortable with
```rust
(Some(prev), _, _) => ...
(None, _, _) => unreachable!(),
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6778)

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6778)

**Pull request merged**
