### PR TITLE
Fix invalid WPT metadata.

### PR DESCRIPTION
**Pull request by jdm**
This will fix the WPT nightly sync.

### CODE REVIEW

**Comment by CYBAI** [comment]
```
  ▶ Unexpected subtest result in /webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html:
  │ FAIL [expected PASS] X Rendered audio for channel 5 does not equal [0,0.0626220703125,0.125030517578125,0.18695068359375,0.24810791015625,0.308319091796875,0.3673095703125,0.42486572265625,0.480743408203125,0.53472900390625,0.58660888671875,0.636199951171875,0.68328857421875,0.727691650390625,0.76922607421875,0.8077392578125...] with an element-wise tolerance of {"absoluteThreshold":0.000030517578125,"relativeThreshold":0}.\n\tIndex\tActual\t\t\tExpected\t\tAbsError\t\tRelError\t\tTest threshold\n\t[1]\t3.6732959747314453e-1\t6.2622070312500000e-2\t3.0470752716064453e-1\t4.8658168859649127e+0\t3.0517578125000000e-5\n\t[2]\t6.8329977989196777e-1\t1.2503051757812500e-1\t5.5826926231384277e-1\t4.4650639949963384e+0\t3.0517578125000000e-5\n\t[3]\t9.0373212099075317e-1\t1.8695068359375000e-1\t7.1678143739700317e-1\t3.8340669508039502e+0\t3.0517578125000000e-5\n\t[4]\t9.9780619144439697e-1\t2.4810791015625000e-1\t7.4969828128814697e-1\t3.0216621502152523e+0\t3.0517578125000000e-5\n\t[5]\t9.5236867666244507e-1\t3.0831909179687500e-1\t6.4404958486557007e-1\t2.0889059484187866e+0\t3.0517578125000000e-5\n\t...and 40533 more errors.\n\tMax AbsError of 1.9986611604690552e+0 at index of 12875.\n\t[12875]\t-9.9994289875030518e-1\t9.9871826171875000e-1\t1.9986611604690552e+0\t2.0012262087101997e+0\t3.0517578125000000e-5\n\tMax RelError of Infinity at index of 12348.\n\t[12348]\t9.5105654001235962e-1\t0.0000000000000000e+0\t9.5105654001235962e-1\tInfinity\t3.0517578125000000e-5\n
  │   → assert_true: expected true got false
  │ 
  │ _logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:52:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1867:25
  │ test@http://web-platform.test:8000/resources/testharness.js:548:30
  │ _logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:51:5
  │ _finalize@http://web-platform.test:8000/webaudio/resources/audit.js:217:9
  │ _assert@http://web-platform.test:8000/webaudio/resources/audit.js:230:12
  │ beCloseToArray@http://web-platform.test:8000/webaudio/resources/audit.js:1021:19
  └ @http://web-platform.test:8000/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-multi-channels.html:67:26
```

**Comment by jdm** [comment]
@bors-servo retry
#25840

**Pull request merged**
