### PR TITLE
Bump rayon to 1.0

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20058)

### CODE REVIEW

**Comment by glennw** [comment]
@Manishearth @jdm I assume there's no issues here with bumping this in a way that affects geckolib?

**Comment by CYBAI** [comment]
```
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size/background-size-contain.xht d87faa2319e69c2054cfa1ba338ea91dec81c0c6\n/css/css-backgrounds/background-size/reference/background-size-contain.xht 806039ca213586857b9f9c84c48dc3ab29c2cbd1\nTesting d87faa2319e69c2054cfa1ba338ea91dec81c0c6 == 806039ca213586857b9f9c84c48dc3ab29c2cbd1", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size/background-size-contain.xht", "line": 2968, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size/background-size-cover.xht 2f29c91ea3527fb7fcd173b696d8f3d47f82866c\n/css/css-backgrounds/background-size/reference/background-size-cover.xht 5b6a6be532f61d1f72b1f2aaaa84084f3ee49b95\nTesting 2f29c91ea3527fb7fcd173b696d8f3d47f82866c == 5b6a6be532f61d1f72b1f2aaaa84084f3ee49b95", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size/background-size-cover.xht", "line": 3064, "action": "test_result", "expected": "PASS"}
```

**Comment by glennw** [comment]
@bors-servo try
 * Testing for intermittents

**Comment by Eijebong** [comment]
Woups, pushed the wrong branch

**Comment by jdm** [comment]
```
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-repeat/background-repeat-round-roundup.xht 5055077d2112df0a02a631adb2a4f531e26f700a\n/css/css-backgrounds/background-repeat/reference/background-repeat-round-roundup.xht 989e2f832e789222378246def99c5f89bddc9d9c\nTesting 5055077d2112df0a02a631adb2a4f531e26f700a == 989e2f832e789222378246def99c5f89bddc9d9c", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-repeat/background-repeat-round-roundup.xht", "line": 17889, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-repeat/background-repeat-round.xht 95c9963b60313615f3b33e0ad433c96b913224f6\n/css/css-backgrounds/background-repeat/reference/background-repeat-round.xht dbeeee17069e37c27124a4a450b2b53fcc425fa7\nTesting 95c9963b60313615f3b33e0ad433c96b913224f6 == dbeeee17069e37c27124a4a450b2b53fcc425fa7", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-repeat/background-repeat-round.xht", "line": 17923, "action": "test_result", "expected": "PASS"}
```

**Comment by Eijebong** [comment]
There, fixed the geckobuild

**Comment by jdm** [comment]
```
{"status": "FAIL", "group": "default", "message": "/_mozilla/mozilla/webgl/tex_image_2d_mipmap.html 23b755622cc81841a23cc8431a6546dfb1401c66\n/_mozilla/mozilla/webgl/tex_image_2d_simple_ref.html 06711e6d8ba9520a7c0476d41130022d3e609160\nTesting 23b755622cc81841a23cc8431a6546dfb1401c66 == 06711e6d8ba9520a7c0476d41130022d3e609160", "stack": null, "subtest": null, "test": "/_mozilla/mozilla/webgl/tex_image_2d_mipmap.html", "line": 21430, "action": "test_result", "expected": "PASS"}
```

**Comment by jdm** [comment]
There are identical test failures on linux and mac, so I think we're going to have to investigate those!

**Comment by Eijebong** [comment]
@glennw

**Comment by glennw** [comment]
I'll try to reproduce those failures locally today.

**Comment by glennw** [comment]
Fix for the webgl reftest failure is here - https://github.com/servo/webrender/pull/2447.

Once that merges, we can update the WR hash in this PR.

**Comment by Eijebong** [comment]
@bors-servo try

Updated webrender

**Comment by jdm** [comment]
```
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size-025.html 4073a2ed031124d27f62cd6345cf1bdc6775a017\n/css/css-backgrounds/reference/background-size-025-ref.xht 75236eb22b1254af6110ea9763b48d1fada5beb5\nTesting 4073a2ed031124d27f62cd6345cf1bdc6775a017 == 75236eb22b1254af6110ea9763b48d1fada5beb5", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size-025.html", "line": 22651, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size-027.html 0024c206b1bc33e4ac813ebc89459ae9e43ff5cc\n/css/css-backgrounds/reference/background-size-027-ref.xht 10b5c8141f3140455d638499eb70869bb196564c\nTesting 0024c206b1bc33e4ac813ebc89459ae9e43ff5cc == 10b5c8141f3140455d638499eb70869bb196564c", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size-027.html", "line": 22935, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size/background-size-cover.xht ef47396bd42253f0e71e419ac88d11b6ad8aeac7\n/css/css-backgrounds/background-size/reference/background-size-cover.xht 81c63224a4b2c37e84b07c7fa030b6a4680926b7\nTesting ef47396bd42253f0e71e419ac88d11b6ad8aeac7 == 81c63224a4b2c37e84b07c7fa030b6a4680926b7", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size/background-size-cover.xht", "line": 24407, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/css3-box-shadow.html c3f6f32dc7aef37381b42e6d16ec28f6add94ab3\n/css/css-backgrounds/reference/css3-box-shadow-ref.html f33361d97fc19a71edd938857a7f3333bde263a2\nTesting c3f6f32dc7aef37381b42e6d16ec28f6add94ab3 == f33361d97fc19a71edd938857a7f3333bde263a2", "stack": null, "subtest": null, "test": "/css/css-backgrounds/css3-box-shadow.html", "line": 24635, "action": "test_result", "expected": "PASS"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-018.html", "line": 35302, "action": "test_result", "expected": "FAIL"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size/background-size-contain.xht b6b538f1f42c732091b8d2d320ea7dc67f2d1f0b\n/css/css-backgrounds/background-size/reference/background-size-contain.xht fa63f17b10b94b525ebd77a7085f8ed032c00400\nTesting b6b538f1f42c732091b8d2d320ea7dc67f2d1f0b == fa63f17b10b94b525ebd77a7085f8ed032c00400", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size/background-size-contain.xht", "line": 45657, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/_mozilla/css/border-image-linear-gradient.html 84064b8cd3b4eab7acb7332e766b546ab1ecbcd1\n/_mozilla/css/border-image-linear-gradient-ref.html 08fecc8482e5f91b0a2d6a93c0d9b3cdd08662c1\nTesting 84064b8cd3b4eab7acb7332e766b546ab1ecbcd1 == 08fecc8482e5f91b0a2d6a93c0d9b3cdd08662c1", "stack": null, "subtest": null, "test": "/_mozilla/css/border-image-linear-gradient.html", "line": 49465, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/_mozilla/css/overflow_clipping.html 002b79d6a180272cca1f0c60c558352b366406f0\n/_mozilla/css/overflow_clipping_ref.html 4ab4e360619244c97da324adb1f874f36626ca00\nTesting 002b79d6a180272cca1f0c60c558352b366406f0 == 4ab4e360619244c97da324adb1f874f36626ca00", "stack": null, "subtest": null, "test": "/_mozilla/css/overflow_clipping.html", "line": 49806, "action": "test_result", "expected": "PASS"}
```

**Comment by Eijebong** [comment]
Also that mac-dev failure is weird, it could be related to the syn update but why would it be showing up only now ?

**Comment by glennw** [comment]
For ```background-size-025.html``` and ```background-size-027.html```, we'll probably need to disable these tests, since WPT doesn't currently support fuzziness checks. There are a very small number of pixels that are off by a difference of ```(1.0 / 255.0)``` due to rounding error since they are drawn a different way.

I still need to investigate the other failures.

**Comment by glennw** [comment]
Same for ```background-size-cover.xht``` and ```background-size-contain.xht```

**Comment by glennw** [comment]
```border-image-linear-gradient.html``` looks to be a very small subpixel difference too. 

```overflow_clipping.html``` looks like a genuine regression though.

**Comment by glennw** [comment]
@mrobinson Any ideas / hints what may have changed recently in WR that could cause the ```overflow_clipping.html``` failure here? In the 2nd row, the elements are clipped differently from the reference. It's been a little while since a WR update landed in Servo due to dependency issues, so we may have to bisect back a few weeks.

ref

**Comment by glennw** [comment]
@mrobinson is going to take a look at this tomorrow.

**Comment by mrobinson** [comment]
I've tracked this issue down (still not sure when the bug was introduced) and I should have a WebRender PR fixing it as soon as the bots finish processing a PR that is landing now.

**Comment by mrobinson** [comment]
I posted a fix for this issue here: https://github.com/servo/webrender/pull/2460

**Comment by Eijebong** [comment]
```
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size-025.html 4073a2ed031124d27f62cd6345cf1bdc6775a017\n/css/css-backgrounds/reference/background-size-025-ref.xht 75236eb22b1254af6110ea9763b48d1fada5beb5\nTesting 4073a2ed031124d27f62cd6345cf1bdc6775a017 == 75236eb22b1254af6110ea9763b48d1fada5beb5", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size-025.html", "line": 21315, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size-027.html 0024c206b1bc33e4ac813ebc89459ae9e43ff5cc\n/css/css-backgrounds/reference/background-size-027-ref.xht 10b5c8141f3140455d638499eb70869bb196564c\nTesting 0024c206b1bc33e4ac813ebc89459ae9e43ff5cc == 10b5c8141f3140455d638499eb70869bb196564c", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size-027.html", "line": 21680, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size/background-size-cover.xht ef47396bd42253f0e71e419ac88d11b6ad8aeac7\n/css/css-backgrounds/background-size/reference/background-size-cover.xht 81c63224a4b2c37e84b07c7fa030b6a4680926b7\nTesting ef47396bd42253f0e71e419ac88d11b6ad8aeac7 == 81c63224a4b2c37e84b07c7fa030b6a4680926b7", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size/background-size-cover.xht", "line": 22849, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/css3-box-shadow.html 153d22504086b9cb671714d880a61f8fe7666994\n/css/css-backgrounds/reference/css3-box-shadow-ref.html f33361d97fc19a71edd938857a7f3333bde263a2\nTesting 153d22504086b9cb671714d880a61f8fe7666994 == f33361d97fc19a71edd938857a7f3333bde263a2", "stack": null, "subtest": null, "test": "/css/css-backgrounds/css3-box-shadow.html", "line": 23160, "action": "test_result", "expected": "PASS"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-transforms/transform-input-018.html", "line": 32610, "action": "test_result", "expected": "FAIL"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-size/background-size-contain.xht b6b538f1f42c732091b8d2d320ea7dc67f2d1f0b\n/css/css-backgrounds/background-size/reference/background-size-contain.xht fa63f17b10b94b525ebd77a7085f8ed032c00400\nTesting b6b538f1f42c732091b8d2d320ea7dc67f2d1f0b == fa63f17b10b94b525ebd77a7085f8ed032c00400", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-size/background-size-contain.xht", "line": 44691, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/_mozilla/css/border-image-linear-gradient.html 84064b8cd3b4eab7acb7332e766b546ab1ecbcd1\n/_mozilla/css/border-image-linear-gradient-ref.html 08fecc8482e5f91b0a2d6a93c0d9b3cdd08662c1\nTesting 84064b8cd3b4eab7acb7332e766b546ab1ecbcd1 == 08fecc8482e5f91b0a2d6a93c0d9b3cdd08662c1", "stack": null, "subtest": null, "test": "/_mozilla/css/border-image-linear-gradient.html", "line": 49187, "action": "test_result", "expected": "PASS"}
```

**Comment by jdm** [comment]
```
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-repeat/background-repeat-round-roundup.xht 5055077d2112df0a02a631adb2a4f531e26f700a\n/css/css-backgrounds/background-repeat/reference/background-repeat-round-roundup.xht 989e2f832e789222378246def99c5f89bddc9d9c\nTesting 5055077d2112df0a02a631adb2a4f531e26f700a == 989e2f832e789222378246def99c5f89bddc9d9c", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-repeat/background-repeat-round-roundup.xht", "line": 18928, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-backgrounds/background-repeat/background-repeat-round.xht 95c9963b60313615f3b33e0ad433c96b913224f6\n/css/css-backgrounds/background-repeat/reference/background-repeat-round.xht dbeeee17069e37c27124a4a450b2b53fcc425fa7\nTesting 95c9963b60313615f3b33e0ad433c96b913224f6 == dbeeee17069e37c27124a4a450b2b53fcc425fa7", "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-repeat/background-repeat-round.xht", "line": 19022, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/css-images/gradient-move-stops.html 84a8a1805062a758170c0d696b08a2b22c915386\n/css/css-images/gradient-move-stops-ref.html 37e26dc67ae2cecd0427a91ce9a99bfdad3be786\nTesting 84a8a1805062a758170c0d696b08a2b22c915386 == 37e26dc67ae2cecd0427a91ce9a99bfdad3be786", "stack": null, "subtest": null, "test": "/css/css-images/gradient-move-stops.html", "line": 30337, "action": "test_result", "expected": "PASS"}
```

**Comment by glennw** [comment]
Added some more test expectation changes.

I don't really like the idea of marking this many tests as failing, but they are mostly differences of 1/255 in a very small number of pixels.

I'm not sure there's a better solution than marking them as failing, and looking at them as a follow up to see if there's anything we can do about making these tests pixel-perfect reliably.

@bors-servo try

**Comment by Eijebong** [comment]
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/css-backgrounds/background-repeat/background-repeat-round.xht", "line": 1644, "action": "test_result", "expected": "FAIL"}
```

**Comment by glennw** [comment]
Looks like that test only fails on one platform, not the other. So we'll need an ini file that marks it as a FAIL on one platform only.

**Comment by Eijebong** [comment]
```
{"status": "FAIL", "group": "default", "message": "/css/css-images/gradient-move-stops.html 84a8a1805062a758170c0d696b08a2b22c915386\n/css/css-images/gradient-move-stops-ref.html 37e26dc67ae2cecd0427a91ce9a99bfdad3be786\nTesting 84a8a1805062a758170c0d696b08a2b22c915386 == 37e26dc67ae2cecd0427a91ce9a99bfdad3be786", "stack": null, "subtest": null, "test": "/css/css-images/gradient-move-stops.html", "line": 23476, "action": "test_result", "expected": "PASS"}
```

**Comment by glennw** [comment]
This is tricky to test, as tests like the one above are not failing on my local machine.

@bors-servo try

**Comment by glennw** [comment]
@bors-servo retry
 * "Couldn't get the client port"

**Comment by glennw** [comment]
Success! OK, who wants to sign off on these changes and the added failures?

Each of the failures are due to a very small number of pixels with a difference of 1.0 / 255.0, but unfortunately we can't fuzz these in WPT.

In the future we'll investigate further and see if it's possible to get pixel-perfect results here. I suspect that Servo is providing slightly different display lists in these cases - I verified this in one of the tests, and Gecko is not seeing any similar issues with the recent changes to gradient repeat.

**Pull request merged**
