### PR TITLE
Use helpers.predefined_type for transform property

### PR DESCRIPTION
**Pull request by upsuper**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19104)

### CODE REVIEW

**Comment by upsuper** [comment]
I guess the three people wouldn't be there before I finish other parts of bug 1374178, so I'd just close it and submit all the parts for review together later.

**Review by Manishearth — COMMENTED** [review]
r=me either way

**Comment by upsuper** [comment]
The new PR is #19106.

**Pull request closed without merging**
