### PR TITLE
Generate atom files at build-time

### PR DESCRIPTION
**Pull request by upsuper**
The commits here basically do the following things:
1. move all generated files for gecko into "gecko/generated" so that we can copy all of them around
2. make regen_atoms.py generate file to the out dir rather than in-tree
3. make the build script invoke regen_atoms.py when bindgen feature is enabled

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16762)

### CODE REVIEW

**Comment by upsuper** [comment]
This is something I've promised to do since long ago...

**Review by emilio — APPROVED** [review]

**Comment by emilio** [comment]
(The android failure is intermittently happening today, oh well)

**Comment by emilio** [comment]
You need to fix the `check_bindings.py` script to point to the right bindings file.

**Comment by upsuper** [comment]
@bors-servo r-

There are other tests need to be fixed first.

**Pull request merged**
