### PR TITLE
Pretty print the flow tree to json (Fix #12675)

### LINKED ISSUE #12675: Pretty print the flow tree
When running `./mach run -Z dump-flow-tree`, the output is not very human friendly:

```
│  │  │  ├─ block(7fbf47f05310) sc=stackingcontextid(140459643095216) pos=logicalrect(h ltr, i100px×b100px, @ (i8px,b18.783333333333335px)),  floatspec-in=l 0px r 0px, floatspec-out=l 0px r 0px, overflow=overflow { scroll: rect(100px×100px at (0px,0px)), paint: rect(100px×100px at (0px,0px)) }
│  │  │  │  └─ ↑↑ fragment for block: specificfragmentinfo::generic(4) [] border_box=logicalrect(h ltr, i100px×b100px, @ (i0px,b0px)) damage=store_overflow
│  │  │  ├─ flexflow { block_flow: block(7fbf47fe9310) sc=stackingcontextid(0) pos=logicalrect(h ltr, i10px×b100px, @ (i8px,b34.78333333333333px)),  floatspec-in=l 0px r 0px, ...
```

We can try to wrap the lines like 

```
│  │  │  ├─ block(7fbf47f05310) sc=stackingcontextid(140459643095216) 
│  │  │  │  │                   pos=logicalrect(h ltr, i100px×b100px, @ (i8px,b18.783333333333335px)),  
│  │  │  │  │                   floatspec-in=l 0px r 0px, 
│  │  │  │  │                   floatspec-out=l 0px r 0px, 
│  │  │  │  │                   overflow=overflow { scroll: rect(100px×100px at (0px,0px)), 
│  │  │  │  │                   paint: rect(100px×100px at (0px,0px)) }
│  │  │  │  └─ ↑↑ fragment for block: specificfragmentinfo::generic(4) [] border_box=logicalrect(h ltr i100px×b100px, @ (i0px,b0px)) 
│  │  │  │                                                                damage=store_overflow
```

I'm not sure if we should hack the `Debug::fmt` trait or create a post-processor. The problem with `Debug::fmt` is that it's hard to keep the indentation level. But doing a post process will require us to keep the `Debug::fmt` and the post postprocessor format in sync.

### PR DESCRIPTION
**Pull request by yoyo930021**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12675 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because is debug use no test

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13092)

### CODE REVIEW

**Comment by izgzhen** [comment]
Hmm ... the issue you are trying to solve doesn't look easy to me actually. And I suppose that we can try to add another function emitting JSON object while retaining the old print function. But I am not very sure about the plan. @shinglyu idea?

**Comment by shinglyu** [comment]
This looks OK, but in order not to surprise people who uses this feature, we should wait until we have another tool that can print in the old format. (Maybe a python script that takes the JSON and print as a tree) Then we can merge all the patches at once. 

Also I forgot to mention, we should check if bit of information in the old format is in the new JSON format, if something is missing, we should definitely add that to the JSON output.

**Comment by shinglyu** [comment]
Or we could create a new option in `components/util/opts.rs` called `dump-flow-tree-json`, and don't touch the original `dump-flow-tree`, this will keep the backward compatibility so we can experiment more freely.

**Comment by yoyo930021** [comment]
@shinglyu
I try!

**Comment by nox** [comment]
@yoyo930021 Any news on this?

**Comment by yoyo930021** [comment]
Sorry , no time to do it.
And I meet a few problem.

**Comment by shinglyu** [comment]
This feature can now use the JOSN serialization from #13740. If someone is interested I can point them to the related code.

**Comment by Wafflespeanut** [comment]
Closing based on inactivity :/

**Pull request closed without merging**
