### PR TITLE
Implement HTMLMenuElement

### LINKED ISSUE #24990: Implement HTMLMenuElement
WPT custom-elements/builtin-coverage tries customizing a large number of elements and fails on unimplemented ones, including this.

### PR DESCRIPTION
**Pull request by pshaughn**
Per spec, "The menu element is simply a semantic alternative to ul to express an unordered list of commands (a "toolbar")." We already have the CSS for it in user-agent.css, and this gives us the interface object.

---

- [X] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [X] These changes fix #24990

- [X] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /html/semantics/interfaces.html:
  └ PASS [expected FAIL] Interfaces for menu
  ▶ Unexpected subtest result in /html/semantics/interfaces.html:
  └ PASS [expected FAIL] Interfaces for MENU
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface HTMLMenuElement to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:72:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:2024:25
  │ test@http://web-platform.test:8000/resources/testharness.js:548:30
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:13:1
```

**Comment by pshaughn** [comment]
I changed the "IMPORTANT: Do not change the list below without review from a DOM peer!" list in tests/mozilla/tests/mozilla/interfaces.html and therefore require "review from @jdm or @Ms2ger for that specific change"

**Comment by jdm** [comment]
```
 0:09.49(B INFO(B Diffing old and new manifests /repo/tests/wpt/mozilla/meta/MANIFEST.json
 0:09.66(B WARNING(B Manifest /repo/tests/wpt/mozilla/meta/MANIFEST.json contains correct tests but file hashes changed.
 0:09.66(B ERROR(B Manifest /repo/tests/wpt/mozilla/meta/MANIFEST.json is outdated, use |./mach update-manifest| to fix.
```

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
```
1 unexpected results that are NOT known-intermittents:
  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: typeof IDL attribute

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL get with DOM attribute unset

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to ""

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to " foo "

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to undefined

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to null

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to 7

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to 1.5

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to "5%"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to "+100"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to ".5"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to true

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to false

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to object "[object Object]"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to NaN

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to Infinity

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to -Infinity

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to "\\0"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to object "test-toString"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to object "test-valueOf"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: setAttribute() to "compact"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to ""

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to " foo "

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to undefined

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to null

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to 7

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to 1.5

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to "5%"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to "+100"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to ".5"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to false

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to object "[object Object]"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to NaN

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to Infinity

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to -Infinity

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to "\\0"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to object "test-toString"

  â–¶ Unexpected subtest result in /html/dom/reflection-misc.html:
  â”” PASS [expected FAIL] menu.compact: IDL set to object "test-valueOf"


```

**Pull request merged**
