### PR TITLE
Update osmesa dependency.

### LINKED ISSUE #22063: Intermittent taskcluster build error in osmesa
```
             at libstd/rt.rs:74
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  13: std::rt::lang_start
             at libstd/rt.rs:74
  14: main
  15: __libc_start_main
  16: _start
warning: build failed, waiting for other jobs to finish...
error: build failed

```

cc @nox

### PR DESCRIPTION
**Pull request by jdm**
Fixes #22063.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22067)

### CODE REVIEW

**Comment by Manishearth** [comment]
r=me once the branch is merged

**Comment by jdm** [comment]
@bors-servo retry p=1
* network

**Comment by jdm** [comment]
@bors-servo retry
* cygwin crash

**Pull request merged**
