### PR TITLE
Replace servo-websocket by ws

### LINKED ISSUE #14517: Migrate from rust-websocket to ws-rs
rust-websocket appears to not be maintained anymore. Possibly migrate to ws-rs? This is sorta blocking the rust-openssl bump: https://github.com/servo/servo/pull/14484

https://github.com/cyderize/rust-websocket

https://github.com/housleyjk/ws-rs

### PR DESCRIPTION
**Pull request by Eijebong**
This is heavily based on previous work done in #16012.

Fixes #14517

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21386)

### CODE REVIEW

**Comment by Manishearth** [comment]
```
error: unused `std::result::Result` which must be used
   --> components/net/websocket_loader.rs:136:9
    |
136 |         net_url.set_host(Some(&host));
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D unused-must-use` implied by `-D warnings`
    = note: this `Result` may be an `Err` variant, which should be handled
```

also, I'm cancelling build rn since I need to be able to quickly reconfig buildbot

**Comment by Eijebong** [comment]
Woups  >_<

**Comment by Eijebong** [comment]
```
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSocket blocked port test 6000", "test": "/websockets/Create-blocked-port.any.worker.html", "line": 111606, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/Create-blocked-port.any.worker.html", "line": 111613, "action": "test_result", "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "message": "Test timed out", "stack": null, "subtest": "WebSocket blocked port test 6000", "test": "/websockets/Create-blocked-port.any.html", "line": 158853, "action": "test_result", "expected": "PASS"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/websockets/Create-blocked-port.any.html", "line": 158860, "action": "test_result", "expected": "OK"}
```

So close

**Comment by Eijebong** [comment]
Any idea if it's just the port missing in ws's blacklist or if it's something else ?

**Comment by jdm** [comment]
@bors-servo r-
Temporarily delaying to empty the queue

**Pull request merged**
