### PR TITLE
Use boolean instead of float to avoid nightly warning

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16939)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r=nox

from  #16897

**Comment by jdm** [comment]
```
Checking files for tidiness...

./ports/geckolib/glue.rs:2227: found an empty line following a {
```

**Comment by SimonSapin** [comment]
Everyone who has access, please push futures PR branches to servo/servo where everyone can edit them :)

**Comment by Wafflespeanut** [comment]
Good idea. Given that we can't rely on Github's "Allow edits from maintainers" checkbox.

**Pull request merged**
