### PR TITLE
Webdriver - GetWindowSize/IsEnabled/IsSelected

### PR DESCRIPTION
**Pull request by craftytrickster**
Added handlers for https://github.com/servo/servo/issues/8623:
GetWindowSize
IsEnabled(WebElement)
IsSelected(WebElement) 

I am not sure how to actually verify my webdriver code works, if someone can give advice I would make the necessary changes.

Thanks!

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8661)

### CODE REVIEW

**Comment by jgraham** [comment]
Looks mostly good. Unfortunately there isn't a easy way to test webdriver stuff because there doesn't exist a testsuite for the spec; I usually poke at it manually using the simple client I wrote for wptrunner. You can do this too, if you want; something like:

    cd $SERVO_ROOT
    source python/_virtualenv/bin/activate
    ./mach run [-d|-r] --webdriver 4444 &
    cd tests/wpt/harness/wptrunner/executors
    [i]python
    import webdriver
    session = webdriver.Session("127.0.0.1", 4444); session.start(); session.url = "about:blank";

and then look in `webdriver.py` to see more of the api that you can use. It doesn't fully implement the webdriver spec but it is rather simple to extend if you need. Sorry for the bad answer.

In any case I'll run this through its paces after the next round of fixups.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[components/script/webdriver_handlers.rs, line 251 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8661#-K3szaRj9MH21evjSE1C:-K3szaRj9MH21evjSE1D:-1832025212) ([raw file](https://github.com/servo/servo/blob/e117e02c036914e8a6a9ad49c3b908cee4d89b4e/components/script/webdriver_handlers.rs#L251)):_
Indentation

---

_[components/script/webdriver_handlers.rs, line 259 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8661#-K3t8BVw5pYaMWy-MI0B:-K3t8BVxU50u4mnRgXN0:-1832025212) ([raw file](https://github.com/servo/servo/blob/e117e02c036914e8a6a9ad49c3b908cee4d89b4e/components/script/webdriver_handlers.rs#L259)):_
Indentation

---

_[components/script/webdriver_handlers.rs, line 274 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8661#-K3t8Dhv6Hs5WhFGVxvo:-K3t8Dhwql6_uxQS_3YG:-1832025212) ([raw file](https://github.com/servo/servo/blob/e117e02c036914e8a6a9ad49c3b908cee4d89b4e/components/script/webdriver_handlers.rs#L274)):_
Indentation

---

_[components/webdriver_server/lib.rs, line 366 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8661#-K3t4nenUDci330iEoVj:-K3t4neoajpL3qmeNINl:-94462123) ([raw file](https://github.com/servo/servo/blob/e117e02c036914e8a6a9ad49c3b908cee4d89b4e/components/webdriver_server/lib.rs#L366)):_
This should in fact be a `WindowSizeResponse`, which means you don't need to construct an interior JSON object, just set the width and height properties in the constructor.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8661#-:-K3t8K8chDAmzWVIutzL:-1099599960)_

**Comment by craftytrickster** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/webdriver_handlers.rs, line 286 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8661#-K3vrJP48UoFtkXgy3hU:-K3vrJP48UoFtkXgy3hV:121836182) ([raw file](https://github.com/servo/servo/blob/e117e02c036914e8a6a9ad49c3b908cee4d89b4e/components/script/webdriver_handlers.rs#L286)):*
according to the [spec](https://w3c.github.io/webdriver/webdriver-spec.html#is-element-selected), if it is not an input or option element, I should return false by default, not Err as I am doing here. I will add the extra step to check if it is a regular html element before the else { Err } branch.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8661)*

**Comment by craftytrickster** [comment]
Thanks @jgraham. I made the code changes you suggested. When I have time later I will look at the python test method you mentioned. I guess no repo is safe from the evil clutches of dynamically typed languages,  not even Servo. :smile:

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8661)*

**Comment by jgraham** [comment]
This seems to work fine. Before merging, would it be possible to get something more like an email address in the author field of the commit?

**Comment by craftytrickster** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[components/script/webdriver_handlers.rs, line 286 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8661#-K3vrJP48UoFtkXgy3hU:-K3vssg98t6Arqu0A6hj:-499146009) ([raw file](https://github.com/servo/servo/blob/e117e02c036914e8a6a9ad49c3b908cee4d89b4e/components/script/webdriver_handlers.rs#L286)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8661)*

**Comment by craftytrickster** [comment]
Just added email details to author, should be good to go.

**Pull request merged**
