### PR TITLE
Implement HSTS (preload-only)

### PR DESCRIPTION
**Pull request by samfoo**
Implement HSTS (preload-only) servo/servo#6105
- Downloads the HSTS preload list from the chromium repo (same as gecko), then convert it to a list appropriate for servo.
- Reads the preload list when creating a resource task, and implements STS for those domains.

Still todo:
- Read Strict-Transport-Security headers from servers and add details to the in-memory HSTS list. (note: this requires hyper or servo to implement an STS header struct. Hyper seems like the appropriate location, so I will create an issue/PR there soon). The work for this is nearly done with the exception of adding a new ControlMsg and the new header.
- Persist HSTS list to disk with known hosts (perhaps a different issue should be raised for this?)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6490)

### CODE REVIEW

**Comment by jdm** [comment]
Great work @samfoo! I appreciate the way you've split up the commits. Sorry for the delay in looking at this PR; I've skimmed all of the commits so far, and I'll do a thorough review soon.

**Comment by jdm** [comment]
One significant change I'll request is to switch from including the fetching of the preload list as part of bootstrapping and make it an explicit choice to update the copy that's part of the tree. We should add a mach command to fetch it, and remove the new entry from the gitignore list.

**Comment by samfoo** [comment]
@jdm Sure. Moving the preload from a bootstrap step to an explicit command shouldn't be too big of a change. I'll take a look at making it sometime this week.

**Comment by samfoo** [comment]
Also note that since hyperium/hyper#590 (implementing the Strict-Transport-Security header) is now merged, whenever the next version bump of hyper happens, the non-preload STS implementation can be finished.

**Comment by jdm** [comment]
I've started reviewing this. Apologies for the continued delays!

**Comment by samfoo** [comment]
I've rebased to resolve the conflicts. Let me know if there's something else I can do to help with this.

**Comment by jdm** [comment]
-S-needs-rebase -S-needs-rebase +S-needs-code-changes 
This is such a great PR! Thanks for doing this work :D

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 5 of 5 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 4 of 4 files at r15, 5 of 5 files at r16.
Review status: all files reviewed at latest revision, 24 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/resource_task.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMXG8kwd4WEiGWn1Bk)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/components/net/resource_task.rs#L159)):</sup>
```
read_resource_file(...).ok().and_then(|bytes| {
    from_utf8(bytes).ok().and_then(|content| {
        HSTSList::new_from_preload(content)
    })
})
```

---

<sup>**[components/net/resource_task.rs, line 186 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMb3jsRrLhvrYSn-9q)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/components/net/resource_task.rs#L186)):</sup>
I think we should move all of this HSTS-related code into a new hsts.rs file.

---

<sup>**[components/net/resource_task.rs, line 198 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMXP23fwP0W8Bl_hNT)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/components/net/resource_task.rs#L198)):</sup>
`decode(preload_content).ok()`

---

<sup>**[components/net/resource_task.rs, line 201 \[r5\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMi-WWY10WbFMGaqVK)** ([raw file](https://github.com/servo/servo/blob/78199a5dc284c24e48617600779dab736f9847b4/components/net/resource_task.rs#L201)):</sup>
Let's make this an enum rather than a bool. We can still store a bool internally, though.

---

<sup>**[components/net/resource_task.rs, line 221 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMXvPgpJcM1YiGtOpH)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/components/net/resource_task.rs#L221)):</sup>
I would just use an `if` instead.

---

<sup>**[components/net/resource_task.rs, line 223 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMY70TAv8ciX5KPtqu)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/components/net/resource_task.rs#L223)):</sup>
Can we not mutate the url in place?

---

<sup>**[components/net/resource_task.rs, line 261 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMfWHm2TYM9ODbTAtz)** ([raw file](https://github.com/servo/servo/blob/87107fcb5be5b3538321d91c029d4b563595a60d/components/net/resource_task.rs#L261)):</sup>
Why not just use a mutable iterator and update include_subdomains in place, instead of using a fold?

---

<sup>**[components/net/resource_task.rs, line 311 \[r12\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuN6L4P6k8G8wZPslka)** ([raw file](https://github.com/servo/servo/blob/45dc18666af3e339b511d2023d64a7b8b4badfd5/components/net/resource_task.rs#L311)):</sup>
@SimonSapin, is this necessary?

---

<sup>**[components/net/resource_task.rs, line 341 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMYIcnRSfG0l5y5G2E)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/components/net/resource_task.rs#L341)):</sup>
`if let`
This needs to happen in http_loader.rs instead, though, or we won't upgrade any redirects that occur.

---

<sup>**[components/net/resource_task.rs, line 370 \[r11\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuN5lhmLdpSJDAuDGch)** ([raw file](https://github.com/servo/servo/blob/4d5e019d4a506f08cc79591adbc90d96f2a96acd/components/net/resource_task.rs#L370)):</sup>
`if let`

---

<sup>**[components/net/resource_task.rs, line 424 \[r10\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuN4tg2AP8A__oSAsKH)** ([raw file](https://github.com/servo/servo/blob/7953f8da84cffe0082af567e7bd30fd8151f4926/components/net/resource_task.rs#L424)):</sup>
`if let`

---

<sup>**[components/net/resource_task.rs, line 425 \[r8\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMm_I7mkPXc9E219rF)** ([raw file](https://github.com/servo/servo/blob/06abc735982d414cc80a5666c6f6d86a734dc712/components/net/resource_task.rs#L425)):</sup>
I preferred the previous code which wasn't so clone-happy.

---

<sup>**[python/servo/bootstrap_commands.py, line 226 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMZJlPPvaARfZzWd7Z)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/python/servo/bootstrap_commands.py#L226)):</sup>
grammar nit: ; instead of ,

---

<sup>**[python/servo/bootstrap_commands.py, line 230 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMaVI55xh7Ft4HmvQA)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/python/servo/bootstrap_commands.py#L230)):</sup>
A comment explaining this would be useful.

---

<sup>**[tests/unit/net/resource_task.rs, line 6 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMan62zfg_QzP64O_G)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/tests/unit/net/resource_task.rs#L6)):</sup>
nit: so far we've preferred single line imports on multiple lines than {} split across multiple lines.

---

<sup>**[tests/unit/net/resource_task.rs, line 24 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMb7vqP_PsP06lEzOb)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/tests/unit/net/resource_task.rs#L24)):</sup>
As with the new hsts.rs in net, I think we should have a new test file for it too.

---

<sup>**[tests/unit/net/resource_task.rs, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMbGAzeljk6Tqx3sJR)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/tests/unit/net/resource_task.rs#L26)):</sup>
`assert!(HSTSList::new_from_preload(mock_preload_content).is_some(), "preload list should not have parsed")`

---

<sup>**[tests/unit/net/resource_task.rs, line 29 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMimDcshs1DXSgeLPM)** ([raw file](https://github.com/servo/servo/blob/a92551d1dc08c1083cf88548d0ab21cf675cfc6b/tests/unit/net/resource_task.rs#L29)):</sup>
assert!(entry.is_none(), "able to create HSTSEntry with IPv6 host");

---

<sup>**[tests/unit/net/resource_task.rs, line 35 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMbQDlrbJ4MMzE9Ajc)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/tests/unit/net/resource_task.rs#L35)):</sup>
assert `.is_some()`

---

<sup>**[tests/unit/net/resource_task.rs, line 41 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMiuYDSuy5tzI9MYkQ)** ([raw file](https://github.com/servo/servo/blob/a92551d1dc08c1083cf88548d0ab21cf675cfc6b/tests/unit/net/resource_task.rs#L41)):</sup>
Same as above.

---

<sup>**[tests/unit/net/resource_task.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMbdJp_TbUCwa9Xz0B)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/tests/unit/net/resource_task.rs#L52)):</sup>
[0] instead of .get(0).unwrap()?

---

<sup>**[tests/unit/net/resource_task.rs, line 68 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMgATrVQRAVwKolJqK)** ([raw file](https://github.com/servo/servo/blob/87107fcb5be5b3538321d91c029d4b563595a60d/tests/unit/net/resource_task.rs#L68)):</sup>
A test for adding multiple entries (or adding an entry to one with more than one existing entry) would have caught the earlier bug.

---

<sup>**[tests/unit/net/resource_task.rs, line 118 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMc1GrIZng5J7p6ION)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/tests/unit/net/resource_task.rs#L118)):</sup>
assert_eq

---

<sup>**[tests/unit/net/resource_task.rs, line 129 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMc0M9ztJsEDgtpxNl)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/tests/unit/net/resource_task.rs#L129)):</sup>
assert_eq

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6490)

**Comment by jdm** [comment]
Please leave extracting the HSTS code into new files until the very end in a separate commit; it will be easier for me to notice the changes related to my other comment that way :)

**Comment by samfoo** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/resource_task.rs, line 215 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMfWHm2TYM9ODbTAtz)** ([raw file](https://github.com/servo/servo/blob/87107fcb5be5b3538321d91c029d4b563595a60d/components/net/resource_task.rs#L215)):</sup>
Rust newbie. Fixed.

---

<sup>**[components/net/resource_task.rs, line 223 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMY70TAv8ciX5KPtqu)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/components/net/resource_task.rs#L223)):</sup>
There's a "bug"/implementation detail in Url  such that even though we update the scheme, it doesn't properly update the port internally. This meant that even when upgrading the URL to https, the connection was still attempted on port 80. Re-parsing the URL is a hack to get around this. I'll add a comment explaining it, and think about submitting a fix to rust-url

---

<sup>**[components/net/resource_task.rs, line 341 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMYIcnRSfG0l5y5G2E)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/components/net/resource_task.rs#L341)):</sup>
Excellent point. This same problem exists for host file resolution as well, I believe.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6490)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/resource_task.rs, line 449 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuMYIcnRSfG0l5y5G2E)** ([raw file](https://github.com/servo/servo/blob/8a00ffd5f2bcda9ff6d6c1962fdff79e2ed5f3f8/components/net/resource_task.rs#L449)):</sup>
Yep, see #6416 :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6490)

**Comment by samfoo** [comment]
Still need to move the hsts list to the http_loader, but it's a slightly larger task than the rest.

**Comment by jdm** [comment]
Reviewed 3 of 3 files at r17, 2 of 2 files at r18, 6 of 6 files at r19, 4 of 4 files at r20.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/hsts.rs, line 18 \[r19\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuWSPJo2UYAzeFT4Wys)** ([raw file](https://github.com/servo/servo/blob/a3adf7f9181385234aa3bab3ff0931e3c592ba15/components/net/hsts.rs#L18)):</sup>
Let's use the regexes from resource_task.rs instead of duplicating them.

---

<sup>**[components/net/http_loader.rs, line 89 \[r20\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuWYIJsowMu3fNVtsnp)** ([raw file](https://github.com/servo/servo/blob/6fce43e36182c7a8fda57141be846bafab74b81d/components/net/http_loader.rs#L89)):</sup>
We're going to want this to be an `Arc<Mutex<HSTSList>>`, or we'll be cloning a large vector for every single request.

---

<sup>**[components/net/resource_task.rs, line 26 \[r19\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuWRvPEspmxt0VCw88K)** ([raw file](https://github.com/servo/servo/blob/a3adf7f9181385234aa3bab3ff0931e3c592ba15/components/net/resource_task.rs#L26)):</sup>
nit: these can be merged into one or multiple lines of {} that aren't longer than 100 chars.

---

<sup>**[components/net/resource_task.rs, line 263 \[r20\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuWZONEq-vdZk8la5zh)** ([raw file](https://github.com/servo/servo/blob/6fce43e36182c7a8fda57141be846bafab74b81d/components/net/resource_task.rs#L263)):</sup>
Why not always have an HSTSList, just make it empty?

---

<sup>**[components/net/resource_task.rs, line 363 \[r18\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuWRLI1qcZOeVZoNIAf)** ([raw file](https://github.com/servo/servo/blob/342eef7a34ea24312709a24ec01dbbb9fbaf0195/components/net/resource_task.rs#L363)):</sup>
Let's use the enum in this message, too.

---

<sup>**[tests/unit/net/hsts.rs, line 137 \[r19\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuWYwCzo7ZcM9LIY9jR)** ([raw file](https://github.com/servo/servo/blob/a3adf7f9181385234aa3bab3ff0931e3c592ba15/tests/unit/net/hsts.rs#L137)):</sup>
?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6490)

**Comment by jdm** [comment]
This is very close! I'm excited!

**Comment by samfoo** [comment]
Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/net/resource_task.rs, line 263 \[r20\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuWZONEq-vdZk8la5zh)** ([raw file](https://github.com/servo/servo/blob/6fce43e36182c7a8fda57141be846bafab74b81d/components/net/resource_task.rs#L263)):</sup>
Originally it was because the preload list might not be present or might not be parsed. But perhaps you're right that the logic to pull out something from the option should happen higher up.

---

<sup>**[tests/unit/net/hsts.rs, line 137 \[r19\]](https://reviewable.io:443/reviews/servo/servo/6490#-JuWYwCzo7ZcM9LIY9jR)** ([raw file](https://github.com/servo/servo/blob/a3adf7f9181385234aa3bab3ff0931e3c592ba15/tests/unit/net/hsts.rs#L137)):</sup>
D'oh. I think there was a brainfart/copy paste muck up here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6490)

**Comment by samfoo** [comment]
The reason I haven't used the enum in the ControlMsg is that there then becomes a cyclical dependency on net_traits -> net -> net_traits.

I could move hsts.rs to the net_traits crate, but it's not clear to me what the logical distinction between the two crates is?

---

Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6490)

**Comment by jdm** [comment]
Can you just move the enum to net_traits and thereby use it from both?
-S-awaiting-review 

---

Reviewed 4 of 4 files at r21, 2 of 2 files at r22.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6490)

**Comment by jdm** [comment]
@bors-servo: r+
-S-needs-rebase -S-awaiting-review +S-awaiting-merge 

---

Reviewed 5 of 5 files at r23, 1 of 1 files at r24, 1 of 1 files at r25.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6490)

**Comment by samfoo** [comment]
Hmmm... I've also seen `test_exit` fail, but it seems to be intermittent.

**Comment by jdm** [comment]
This certainly appears to be triggered by this PR's changes, judging by the call stack:
```
	thread 'resource_task::test_exit' panicked at 'assertion failed: OPTIONS.is_null()', /Users/servo/buildbot/slave/mac1/build/components/util/opts.rs:465

stack backtrace:
   1:        0x10a676c55 - sys::backtrace::write::hde88a3e3a343e9f8zms
   2:        0x10a67a2c3 - panicking::on_panic::h8c73c8f1e33f6d60hIw
   3:        0x10a66a112 - rt::unwind::begin_unwind_inner::h781ff1cd39e7f47etqw
   4:        0x10a57a3fc - rt::unwind::begin_unwind::h4242128002453220643
   5:        0x10a57dfd2 - opts::set::hd06e83c6ac9d992fKve
   6:        0x10a57e445 - opts::get::h04208687105ef499xwe
   7:        0x10a57e4dd - resource_files::resources_dir_path::he05cd5cdab487cbfoXe
   8:        0x10a57f15c - resource_files::read_resource_file::hc0b20b6602db3648yYe
   9:        0x10a4b4261 - hsts::preload_hsts_domains::h92559adccc206d1b2ch
  10:        0x10a4b3dfa - resource_task::new_resource_task::h67e112ab75266000FMg
  11:        0x10a335987 - resource_task::test_exit::hcac5b3f963d7f839T7a
  12:        0x10a5f13d0 - boxed::F.FnBox<A>::call_box::h3149614863645239508
  13:        0x10a5f430f - boxed::F.FnBox<A>::call_box::h10615509072376550060
  14:        0x10a5f1bd7 - rt::unwind::try::try_fn::h14032699937619583097
  15:        0x10a67bf98 - rust_try_inner
  16:        0x10a67bf85 - rust_try
  17:        0x10a675475 - rt::unwind::try::inner_try::h9e58480e93edc0cdmmw
  18:        0x10a5f1e08 - boxed::F.FnBox<A>::call_box::h11471023936059757363
  19:        0x10a678ebd - sys::thread::Thread::new::thread_start::hf153915745363fa7wKv
  20:     0x7fff8cbf6267 - _pthread_body
  21:     0x7fff8cbf61e4 - _pthread_start
```

**Comment by jdm** [comment]
Oh, I bet we're running multiple tests in threads in the same binary, so two calls to new_resource_task are now racing (and therefore the global opts::set() calls are racing). It may be time to add a mutex to that.

**Comment by jdm** [comment]
Once #6681 merges we should be able to give this PR ago try at merging.

**Pull request merged**
