### PR TITLE
Fix #9508: Beautify our union enums constructors

### LINKED ISSUE #9508: Beautify our union enums constructors
They should be `NodeOrString::Node` instead of `NodeOrString::eNode`.

Files:
 * components/script/dom/bindings/codegen/CodegenRust.py

### PR DESCRIPTION
**Pull request by alopatindev**
Solves #9508
@jdm Please review. Thanks!

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9543)

### CODE REVIEW

**Comment by jdm** [comment]
I'm actually going to hand this over to @nox, but thanks for doing this!
r? @nox

**Comment by alopatindev** [comment]
Ok, cool. Please note that I wasn't able to run tests neither on master nor on my branch (is that okay, actually?)
```
$ ./mach test
tidy reported no errors.
Error running mach:

    ['test']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

TypeError: test_ref() got an unexpected keyword argument 'kind'

  File "/home/sbar/git/servo/python/servo/testing_commands.py", line 152, in test
    Registrar.dispatch("test-%s" % suite, context=self.context, **kwargs)
  File "/home/sbar/git/servo/python/mach/mach/registrar.py", line 115, in dispatch
    return self._run_command_handler(handler, context=context, **kwargs)
  File "/home/sbar/git/servo/python/mach/mach/registrar.py", line 90, in _run_command_handler
    result = fn(**kwargs)
```
Thanks!

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9543#-:-K9iXE1vPduOB8PN4yLy:-1520982370)*

**Comment by jdm** [comment]
I'll file an issue for that, but generally `./mach test` will run far, far more tests than you ever want and will make your machine unusable for unrealistic periods of time. In this case, the fact that it compiles is enough to demonstrate validity of the change. For future changes, running particular test harnesses and subdirectories could make more sense (eg. `./mach test-wpt`, `./mach test-css`, `./mach test-unit`).

**Comment by alopatindev** [comment]
That was my first rebase, actually. I fixed merge conflict and now I've got a single commit that should be mergeable with master. Hopefully I did it right :) Please check. Thanks

---

Review status: 0 of 112 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9543#-:-K9lLKFQ9oUhb5x1hWIP:-1410409563)*

**Comment by KiChjang** [comment]
The rebase went horribly wrong. You currently have 14 unrelated commits in your PR. See https://github.com/servo/servo/wiki/Github-Workflow for a guide on how to rebase.

**Comment by alopatindev** [comment]
@KiChjang thanks for noticing that! I've removed unrelated commits using `git rebase -i HEAD~15`
Hopefully I didn't make it even worse :)
(But if I actually did—sorry; it's probably easier for me to recreate the PR then)

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9543#-:-K9t3pzNcyjEJK6sfSUY:599574949)*

**Comment by KiChjang** [comment]
Everything looks fine; thanks for addressing this issue!

@bors-servo r+

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #7846

**Pull request merged**
