### PR TITLE
Make WebIDL callbacks permanently rooted

### LINKED ISSUE #14447: WebIDL callbacks should root themselves
The codegen for a WebIDL callback yields `Rc<CallbackType>`. This value isn't safe because its reflector doesn't get added to any stack root list. We should make this behave like promises, which include a permanent root that only is removed when the final Rust promise object is destroyed.

### PR DESCRIPTION
**Pull request by jdm**
This replicates the same model that Promise uses right now, because it requires less thinking than coming up with something else.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14447
- [ ] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14994)

### CODE REVIEW

**Comment by jdm** [comment]
I'm going to run some try tests and think about ways of writing a specific test for callback GC behaviour.

**Comment by Manishearth** [comment]
Looks okay to me, but can we get an r? @fitzgen or @Ms2ger as well?

**Comment by Ms2ger** [comment]
No objections

**Pull request merged**
