### PR TITLE
Use 'alloc' gate only for platforms which use freetype in gfx

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15406)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Oops, `./mach build` does not succeed (on Linux):
```
error: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
 --> /home/servo/buildbot/slave/linux-dev/build/components/gfx/platform/freetype/font_context.rs:5:1
  |
5 | extern crate alloc;
  | ^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(alloc)] to the crate attributes to enable
```

**Comment by saneyuki** [comment]
> Oops, ./mach build does not succeed (on Linux):

Ah, I tried this on macOS. I'll change to use `alloc` gate only in platforms which uses freetype.

**Comment by Ms2ger** [comment]
Build fails on travis

**Comment by Ms2ger** [comment]
tidy...

**Comment by saneyuki** [comment]
> tidy...

Sorry. I forgot it....

**Comment by saneyuki** [comment]
@Ms2ger I fixed tidy error.

**Pull request merged**
