### PR TITLE
Remove some dead code related to the old network stack.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14570)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@bors-servo retry
- buildbot was restarting

**Comment by larsbergstrom** [comment]
@bors-servo retry
- https://github.com/servo/saltfs/issues/553

**Comment by jdm** [comment]
@bors-servo: retry
* network trouble

**Pull request merged**
