### PR TITLE
Implement fetch (partial #4576)

### PR DESCRIPTION
**Pull request by KiChjang**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6129)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/net/fetch/request.rs @ r2

---

<sup>**[components/net/fetch/request.rs, line 187 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6129#-JphdN4f_qf0J81dNyWW)** ([raw file](https://github.com/servo/servo/blob/867ca05619866cabc47244e7b3e4f7e67cc071e9/components/net/fetch/request.rs#L187)):</sup>
I chuckled, but this doesn't add value.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6129)

**Comment by KiChjang** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/fetch/request.rs, line 187 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6129#-JphdN4f_qf0J81dNyWW)** ([raw file](https://github.com/servo/servo/blob/867ca05619866cabc47244e7b3e4f7e67cc071e9/components/net/fetch/request.rs#L187)):</sup>
Oh man, I thought I removed that line :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6129)

**Comment by Manishearth** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 1 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/fetch/request.rs, line 195 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6129#-JpjMO7xgAPCuaXGBD7q)** ([raw file](https://github.com/servo/servo/blob/f1375655e53fafa0736eda5bbc8aef6056592859/components/net/fetch/request.rs#L195)):</sup>
nit: Doc comment please (three slashes)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6129)

**Comment by Manishearth** [comment]
r=me post nit

**Comment by KiChjang** [comment]
r=Manishearth

**Pull request merged**
