### PR TITLE
Remove clipboard crate to due disallowed usage of GPL code

### LINKED ISSUE #7578: rust-clipboard is GPL
At the time of writing, rust-clipboard is licensed GPL, and servo depends on rust-clipboard.

/cc @meh @aweinstock314

### PR DESCRIPTION
**Pull request by larsbergstrom**
Fixes #7578, removing usage of rust-clipboard, which contains a disallowed dependency on GPL code.

r? @metajack 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it's a dependency removal

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12507)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12507#-:-KN2qvNq-upvW1jT4lH-:1236647940)*

**Comment by nox** [comment]
The manifest needs changes.

**Comment by larsbergstrom** [comment]
re-r?

**Pull request merged**
