### PR TITLE
[Issue#5730] Make tidy.py check for links to spec pages.

### PR DESCRIPTION
**Pull request by JayNakrani**
This PR does two things.
- Solve Issue #5730 
- Refactor `tidy.py` to reduce code duplication.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5747)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Left one nit on critic

**Comment by dhananjay92** [comment]
@Ms2ger Just to make sure I understood correctly, "check_whitespace_url_len()" should be renamed to "check_by_line()". Did I get it right?

**Comment by dhananjay92** [comment]
Renamed it.

**Pull request merged**
