### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by SimonSapin**
Adds on top of #6949.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6959)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@bors-servo r-

Please get rid of the merge commit?

**Comment by SimonSapin** [comment]
I did this so to include the commit from #6949 as-is so that it would be auto-merged, and because the new warning was only introduced later in master. (Removing the import before the merge caused a build error.) But I can also rebase the whole thing.

**Comment by SimonSapin** [comment]
Rebased/squashed. r?

**Comment by jdm** [comment]
```
ar: creating ../lib/libicui18n.a
ranlib: ../lib/libicui18n.a: No space left on device
make[6]: *** [../lib/libicui18n.a] Error 1
make[5]: *** [all-recursive] Error 2
make[4]: *** [buildicu] Error 2
make[3]: *** [config/external/icu/target] Error 2
make[2]: *** [compile] Error 2
make[1]: *** [default] Error 2
make: *** [all] Error 2
```
Paging @metajack.

**Comment by metajack** [comment]
Does it take more than 8GB to build?

**Comment by jdm** [comment]
A full mozilla-central debug objdir is only 3.7gb :/

**Comment by metajack** [comment]
I upgraded the instance size. This can be rerun.

**Pull request merged**
