### PR TITLE
HTMLBodyElement 'background' attribute improvements

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9136)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 4 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9136#-:-K74F8MLgeVwbJ-n8SoQ:1236647940)*

**Comment by eefriedman** [comment]
I might be missing something... but don't we have to recalculate the resolved URL if the node is adopted into a different document?

**Comment by nox** [comment]
Ugh. We probably do. The previous code is also wrong in that regard, no?

**Comment by eefriedman** [comment]
Yes, the previous code was wrong as well.

**Comment by nox** [comment]
Could you file an issue please?

**Comment by eefriedman** [comment]
#9142

**Pull request merged**
