### PR TITLE
Support syncing from a clean tree.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9718)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/update/update.py, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9718#-KB7NJAOk1Bq5PZoKT3V:-KB7NJAOk1Bq5PZoKT3W:-367739441) ([raw file](https://github.com/servo/servo/blob/8a903f4c680fc1173a77e6cb467a6d49e9ffd2b1/tests/wpt/update/update.py#L21)):*
Should perhaps only create this if we are actually going to do a sync rather than just a metadata update.

---

*[tests/wpt/update/update.py, line 41 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9718#-KB7N11fMlOVr6C8OIPN:-KB7N11fMlOVr6C8OIPO:-1236421546) ([raw file](https://github.com/servo/servo/blob/8a903f4c680fc1173a77e6cb467a6d49e9ffd2b1/tests/wpt/update/update.py#L41)):*
This is already done in SyncFromUpstream; why did you add it here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9718)*

**Comment by Ms2ger** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/update/update.py, line 41 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9718#-KB7N11fMlOVr6C8OIPN:-KB7yx1zmXObOGRQDNbZ:887806855) ([raw file](https://github.com/servo/servo/blob/8a903f4c680fc1173a77e6cb467a6d49e9ffd2b1/tests/wpt/update/update.py#L41)):*
Because that's too late; `SyncToUpstream` tries to `import` some things from within the sync repo.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9718)*

**Comment by jgraham** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9718)*

**Comment by Ms2ger** [comment]
@bors-servo r=jgraham

Over IRC

**Comment by Ms2ger** [comment]
@bors-servo retry
#9014

**Comment by KiChjang** [comment]
@bors-servo retry
* #9148

**Pull request merged**
