### PR TITLE
Refactor some things related to script loading

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15072)

### CODE REVIEW

**Comment by Ms2ger** [comment]
r=me on the first three commits, not entirely convinced about the fourth yet.

**Comment by Ms2ger** [comment]
r=me on the first four, would like @jdm's thoughts on the fifth (sorry!)

**Comment by nox** [comment]
@bors-servo retry

Travis failed for some unknown reason.

**Comment by jdm** [comment]
That's #15076.
@bors-servo: try- r+

**Pull request merged**
