### PR TITLE
Update to Rust nightly 2016-04-29

### PR DESCRIPTION
**Pull request by mbrubeck**
Patch by @fabricedesre from #11010, updated to fix test-tidy and to not conflict with other PRs in the queue. r? @larsbergstrom

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11017)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo r=larsbergstrom

* Carrying from #11010.

**Comment by Manishearth** [comment]
```
 using PTY: False
error: failed to select a version for `kernel32-sys` (required by `thread-id`):
all possible versions conflict with previously selected versions of `kernel32-sys`
  version 0.2.2 in use by kernel32-sys v0.2.2
  possible versions to select: 0.2.1
```

**Comment by mbrubeck** [comment]
@bors-servo r=larsbergstrom

* Reverted kernel32-sys update, though I'm not sure why it caused the geckolib build to fail.

**Comment by mbrubeck** [comment]
Also a bunch of crash/timeouts in XHR tests on [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/814) with stacks like:

```
  ▶ TIMEOUT [expected OK] /XMLHttpRequest/status-error.htm
  │ 
  │ thread 'http_loader for http://web-platform.test:8000/XMLHttpRequest/resources/status.py?code=410' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
  │ stack backtrace:
  │    1:        0x103849c38 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
  │    2:        0x10384ff15 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
  │    3:        0x10384fb2e - std::panicking::default_hook::hc2c969e7453d080c
  │    4:        0x102fa9732 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h0bad41b0b38a855d
  │    5:        0x103837408 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
  │    6:        0x103838d3e - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
  │    7:        0x103848f07 - rust_begin_unwind
  │    8:        0x103877cd0 - core::panicking::panic_fmt::h257ceb0aa351d801
  │    9:        0x103877fcc - core::panicking::panic::h4bb1497076d04ab9
  │   10:        0x10246bb77 - _<http_loader..NetworkHttpRequestFactory as http_loader..HttpRequestFactory>::create::h10df70e20c1fff49
  │   11:        0x10245ce54 - net::http_loader::obtain_response::hceeddfd9b4f323cf
  │   12:        0x102453274 - net::http_loader::load::h68b5ac4fbf09d0a1
  │   13:        0x10244fc3d - std::sys_common::unwind::try::try_fn::hf5b7421d9f8c74d5
  │   14:        0x103848e9b - __rust_try
  │   15:        0x103848e23 - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  │   16:        0x102450d1d - _<F as std..boxed..FnBox<A>>::call_box::h972ca4ac55970746
  │   17:        0x10384ef98 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  │   18:     0x7fff8face059 - _pthread_body
  │   19:     0x7fff8facdfd6 - _pthread_start
```

**Comment by mbrubeck** [comment]
@bors-servo r=larsberstrom

* reverted some unnecessary updates to try to fix tests; we can test and land these separately later

**Comment by jdm** [comment]
The network thread timeouts are https://github.com/hyperium/hyper/issues/780 .

**Pull request merged**
