### PR TITLE
More drive-by WebGL and canvas fixes

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21723)

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
From other platforms:
```
  ▶ ERROR [expected OK] /_webgl/conformance/textures/image/tex-2d-rgb-rgb-unsigned_short_5_6_5.html
  │   → SecurityError: The operation is insecure.
  │ 
  └ :0:0

  ▶ Unexpected subtest result in /_webgl/conformance/more/functions/readPixelsBadArgs.html:
  └ PASS [expected FAIL] WebGL test #1: testReadPixelsSOPIMG

  ▶ Unexpected subtest result in /_webgl/conformance/more/functions/readPixelsBadArgs.html:
  └ PASS [expected FAIL] WebGL test #2: testReadPixelsSOPCanvas

  ▶ ERROR [expected OK] /_webgl/conformance/textures/image/tex-2d-alpha-alpha-unsigned_byte.html
  │   → SecurityError: The operation is insecure.
  │ 
  └ :0:0

  ▶ ERROR [expected OK] /_webgl/conformance/textures/image/tex-2d-rgba-rgba-unsigned_short_4_4_4_4.html
  │   → SecurityError: The operation is insecure.
  │ 
  └ :0:0

  ▶ ERROR [expected OK] /_webgl/conformance/textures/image/tex-2d-rgb-rgb-unsigned_byte.html
  │   → SecurityError: The operation is insecure.
  │ 
  └ :0:0

  ▶ Unexpected subtest result in /_mozilla/mozilla/promise.html:
  │ FAIL [expected PASS] Native promise from async callback can be resolved
  │   → assert_greater_than_equal: expected a number greater than or equal to 100 but got 99
  │ 
  └ @http://web-platform.test:8000/_mozilla/mozilla/promise.html:64:11

  ▶ Unexpected subtest result in /_webgl/conformance/more/functions/texImage2DHTML.html:
  └ PASS [expected FAIL] WebGL test #1: testTexImage2DNonSOP

  ▶ Unexpected subtest result in /_webgl/conformance/more/functions/texImage2DHTML.html:
  │ FAIL [expected PASS] WebGL test #0: testTexImage2D
  │   → assert_true: testTexImage2D expected true got false
  │ 
  │ reportTestResultsToHarness/<@http://web-platform.test:8000/_webgl/conformance/more/unit.js:947:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1558:20
  │ test@http://web-platform.test:8000/resources/testharness.js:544:9
  │ reportTestResultsToHarness@http://web-platform.test:8000/_webgl/conformance/more/unit.js:946:5
  │ runTests@http://web-platform.test:8000/_webgl/conformance/more/unit.js:233:5
  └ initTests@http://web-platform.test:8000/_webgl/conformance/more/unit.js:972:5

  ▶ ERROR [expected OK] /_webgl/conformance/extensions/oes-texture-float-with-image.html
  │   → SecurityError: The operation is insecure.
  │ 
  └ :0:0

  ▶ OK [expected ERROR] /workers/semantics/multiple-workers/005.html

  ▶ ERROR [expected OK] /_webgl/conformance/textures/misc/tex-image-with-format-and-type.html
  │   → SecurityError: The operation is insecure.
  │ 
  └ :0:0

  ▶ ERROR [expected OK] /_webgl/conformance/textures/image/tex-2d-luminance-luminance-unsigned_byte.html
  │   → SecurityError: The operation is insecure.
  │ 
  └ :0:0

  ▶ ERROR [expected OK] /_webgl/conformance/textures/image/tex-2d-rgba-rgba-unsigned_short_5_5_5_1.html
  │   → SecurityError: The operation is insecure.
  │ 
  └ :0:0
```

**Comment by nox** [comment]
@jdm I fixed the origin test by making `HTMLImageElement::same_origin` which always return true if the image as an URL with scheme `data`, you may want to double check on that. I don't see what could be cross-origin in general about a string containing blobs but maybe I'm wrong about that.

**Pull request merged**
