### PR TITLE
webgl: Fix texturing

### PR DESCRIPTION
**Pull request by emilio**
These two tiny changes were making WebGL textures not work.

It was not seen in our texturing test since it only used one texture, 
we render to a texture by default, and that texture was bound to
`gl::TEXTURE_2D`.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8788)

### CODE REVIEW

**Comment by jdm** [comment]
Could strong typing be useful to avoid problems like the `BindTexture(u32, u32)` mixup in the future?

**Comment by jdm** [comment]
@bors-servo: r-
Actually, can we add a test for this?

**Comment by ecoal95** [comment]
I guess we can.

I'd make a new texturing test using two textures, but that doesn't save
us from other possible errors.

Another option more reliable (IMO), but underperformant, is putting a:

```rust
debug_assert!(gl::get_error() == gl::NO_ERROR);
```

under the giant `match` we have on the webgl paint task. In fact this
way was how I tracked down this bug.

That way any webgl test that does something we dont't expect will crash
in debug mode.

Calling `glGetError` is known to be slow, but I'd guess is a good option
given that most of the web doesn't use WebGL, and it'd be just in debug
mode.

So... That assert with the old texturing test will be enough to prevent
this bug. And the assert itself will prevent a lot more from appearing.

**Comment by Ms2ger** [comment]
Because we don't run tests with `debug_asserts` enabled right now, I'd rather use `assert` until we do.

**Pull request merged**
