### PR TITLE
Use wptrunner for some old-style reftests.

### PR DESCRIPTION
**Pull request by frewsxcv**
Part of #5618

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8010)

### CODE REVIEW

**Comment by Ms2ger** [comment]
+S-needs-code-changes -S-awaiting-review 


---

Reviewed 6 of 6 files at r1, 5 of 5 files at r2, 6 of 6 files at r3, 6 of 6 files at r4, 6 of 6 files at r5, 6 of 6 files at r6, 6 of 6 files at r7, 6 of 6 files at r8, 6 of 6 files at r9, 6 of 6 files at r10, 6 of 6 files at r11, 6 of 6 files at r12, 6 of 6 files at r13, 6 of 6 files at r14, 6 of 6 files at r15, 6 of 6 files at r16, 6 of 6 files at r17, 6 of 6 files at r18, 6 of 6 files at r19.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/wpt/mozilla/meta/MANIFEST.json, line 500 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8010#-K0a4bNRJcwOdgwN6WUY)** ([raw file](https://github.com/servo/servo/blob/6bda13acf4b0dac7561b232e7331f0a28afcd56e/tests/wpt/mozilla/meta/MANIFEST.json#L500)):</sup>
This change ended up in the wrong commit.


---

<sup>**[tests/wpt/mozilla/tests/css/viewport_rule_ref.html, line 1 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8010#-K0a3kFrT1VX1HJwihlb)** ([raw file](https://github.com/servo/servo/blob/92d905a9dc37442113b82a209286eac39aea4cb6/tests/wpt/mozilla/tests/css/viewport_rule_ref.html#L1)):</sup>
This file needs to stay here for `viewport_rule.html`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8010)

**Comment by frewsxcv** [comment]
Let me know how that looks

**Comment by frewsxcv** [comment]
I accidentally deleted a couple files. I added them back in.

**Pull request merged**
