### PR TITLE
#8465: Update node::remove comments to reflect standard 

### PR DESCRIPTION
**Pull request by schuster**
My updates so far for issue #8465. See comments there for more information.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9526)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/node.rs, line 1564 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9526#-K9g91DuF6IcdCxWSYju:-K9g91DuF6IcdCxWSYjv:-1477288304) ([raw file](https://github.com/servo/servo/blob/8bc28aac59c9372302e78b1699ebf4d0423b9644/components/script/dom/node.rs#L1564)):*
This is steps 9-10. Removing steps are implemented through unbind_from_tree. This should probably be written somewhere. Could you add the link to unbind_from_tree in components/script/dom/virtualmethods.rs?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9526#-:-K9g90f28vwndBDnnYQD:1458266033)*

**Comment by schuster** [comment]
@nox Is that where the removing steps should go? Looking through virtualmethods.rs, I see now that there are separate `adopting_steps` and `cloning_steps` functions that come from similar ideas in the DOM spec. It seems like the the best solution would be to add a removing_steps function there and call it immediately after the call to `parent.remove_child` in `Node::remove`. What do you think?

**Comment by nox** [comment]
Cc @Ms2ger

**Comment by Ms2ger** [comment]
Unless there's specific bugs that that would fix, I'd rather keep the design as it is now.

**Comment by nox** [comment]
@Ms2ger Does the second commit look ok to you? r=me if yes.

**Comment by Ms2ger** [comment]
Seems okay

**Pull request merged**
