### PR TITLE
Reduce calls into arbitrary code with the ScriptThread::documents borrow held.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14589)

### CODE REVIEW

**Comment by jdm** [comment]
I think it will be more future-proof to move the DOMRefCell inside the Documents type, rather than playing whack-a-mole with each instance where we borrow it.

**Comment by Ms2ger** [comment]
I guess that would work too. @asajeffrey, thoughts?

**Review by asajeffrey — APPROVED** [review]
Good changes. Ah joy, let isn't associative in rust. @bors-servo r+

**Comment by jdm** [comment]
@bors-servo: r-
Sorry, I just want to make sure we've considered https://github.com/servo/servo/pull/14589#issuecomment-267093093 before merging this.

**Comment by asajeffrey** [comment]
@jdm oops. Would moving the DOMRefCell make documents.iter() clunkier?

**Comment by jdm** [comment]
@asajeffrey In theory I think it could just hold a `Ref<'a, hash_map::Iter<'a, PipelineId, JS<Document>>>` value and continue to work.

**Comment by asajeffrey** [comment]
@jdm true, that's quite a type, but I think it would work.

**Comment by Ms2ger** [comment]
Turns out `iter()` isn't quite that simple; `Ref::map` requires a function `&T -> &U`, not `&'x T -> U<'x>`.

**Comment by asajeffrey** [comment]
Can we land this as-is? This will probably fix the failures with #14312.

**Comment by jdm** [comment]
I want to add a tidy check to prevent any new additions of this pattern first.

**Pull request merged**
