### PR TITLE
Update rust-selectors

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/servo/rust-selectors/pull/30

r? @Ms2ger

This conflicts with the SpiderMonkey upgrade #6150. I’m happy to wait until that lands and rebase.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6427)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Rebase, now that #6150 has landed. r? @Ms2ger

**Comment by Ms2ger** [comment]
Would it make sense to implement those traits on `Node` rather than `&'a Node`?

**Comment by SimonSapin** [comment]
I tried that at first, but e.g. `get_parent` returns `Self`, not `&'a Self`, and I don’t think returning an owned/cloned `Node` is what we want. In Kuchiki on the other hand, the trait is implemented for `NodeRef` which contains an `Rc`, so the ownership of the strong reference is significant and changing the trait to return `&'a Self` wouldn’t work.

**Pull request merged**
