### PR TITLE
Initial support for CSS Custom Properties

### PR DESCRIPTION
**Pull request by SimonSapin**
https://drafts.csswg.org/css-variables/

Missing: 
- `var()` in shorthand property declarations.
- Correct handling of EOF in custom property declarations.

r? @pcwalton

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7518)

### CODE REVIEW

**Comment by pcwalton** [comment]
Looks good, squash if you like then r=me

**Comment by SimonSapin** [comment]
@bors-servo r=pcwalton

Updated unit tests.

**Pull request merged**
