### PR TITLE
Implement beginnings of the History API

### PR DESCRIPTION
**Pull request by cbrewster**
New PR for #11220 since Reviewable was getting slow.
r? @asajeffrey 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).
- [X] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11481)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 1 of 60 files at r1.
Review status: 1 of 57 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11481)*

**Comment by ConnorGBrewster** [comment]
hmm so the `FrameTreeIterator` looks like it doesn't do quite what I need. I will need to rework some of this as the history of child frames in prev/next pipelines are not included in the frame tree, but they will need to be included for the joint session history.

**Comment by ConnorGBrewster** [comment]
@asajeffrey alright this should actually be ready for review whenever you have some open time. I imagine this will probably need a bit of cleanup before actually merging, but it would be nice to have another pair of eyes run over this just to make sure I am not doing something stupidly.

**Comment by asajeffrey** [comment]
My sketch about how to implement the history iterator...

First, we have forward and back iterators for a single frame, just from
```rust
   frame.prev.iter()
   frame.next.iter()
```
both of which implement `Iterator<&FrameEntry>`.

Now, define something like:
```rust
struct MergeIncreasingIterators<I>(Vec<I>);
impl<I> Iterator for MergeIncreasingIterators<I>
    where I: PeekableIterator, I::Item: PartialOrd
{
    type Item = I::Item;
    fn next(&mut self) -> Option<I::Item> {
        self.0.iter()
            .filter_map(|iter| iter.peek().map(|item| (iter, item)))
            .min_by_key(|(iter, item)| item)
            .and_then(|(iter, item)| iter.next())
    }
```
and ditto `MergeDecreasingIterators`.

Implement `PartialOrd` for `FrameEntry` just by comparing timestamps, and plug it all together, and bingo an iterator which merges histories. Er, or something like that.

**Comment by asajeffrey** [comment]
I think this PR would be a lot easier to read if it was split up into it's parts: implement deltas, implement state push, implement joint session histories, etc.

<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> My sketch about how to implement the history iterator...
> 
> 
> 
> First, we have forward and back iterators for a single frame, just from
> 
> ```rust
> 
>    frame.prev.iter()
> 
>    frame.next.iter()
> 
> ```
> 
> both of which implement `Iterator<&FrameEntry>`.
> 
> 
> 
> Now, define something like:
> 
> ```rust
> 
> struct MergeIncreasingIterators<I>(Vec<I>);
> 
> impl<I> Iterator for MergeIncreasingIterators<I>
> 
>     where I: PeekableIterator, I::Item: PartialOrd
> 
> {
> 
>     type Item = I::Item;
> 
>     fn next(&mut self) -> Option<I::Item> {
> 
>         self.0.iter()
> 
>             .filter_map(|iter| iter.peek().map(|item| (iter, item)))
> 
>             .min_by_key(|(iter, item)| item)
> 
>             .and_then(|(iter, item)| iter.next())
> 
>     }
> 
> ```
> 
> and ditto `MergeDecreasingIterators`.
> 
> 
> 
> Implement `PartialOrd` for `FrameEntry` just by comparing timestamps, and plug it all together, and bingo an iterator which merges histories. Er, or something like that.
</details>


---

Reviewed 2 of 60 files at r1, 1 of 4 files at r2, 2 of 11 files at r6, 1 of 3 files at r13.
Review status: 7 of 50 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[components/constellation/constellation.rs, line 229 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJQwQrPUBvHRcHc-Ect:-KJQwQrPUBvHRcHc-Ecu:-834170852) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L229)):*
> ```Rust
> struct FrameEntry {
>     id: PipelineId,
>     context_index: usize,
> ```

Not sure about whether we need this in the `FrameEntry`.

---

*[components/constellation/constellation.rs, line 231 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJQwKtZ-KqSkXXR-ZLk:-KJQwKtZ-KqSkXXR-ZLl:-1727253225) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L231)):*
> ```Rust
>     context_index: usize,
>     reason: EntryReason,
>     time: u64,
> ```

Better to use `Instant` for timestamps?

---

*[components/constellation/constellation.rs, line 247 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJQwuY1RpXZ0XJv2kWg:-KJQwuY1RpXZ0XJv2kWh:1814547728) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L247)):*
> ```Rust
> /// Stores the navigation context for a single frame in the frame tree.
> pub struct Frame {
>     id: FrameId,
> ```

Yay, I've been wanting to make this change for a while!

---

*[components/constellation/constellation.rs, line 268 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJQx91rb_h1rrOZIpDU:-KJQx91rb_h1rrOZIpDV:-1177608637) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L268)):*
> ```Rust
>         // up the navigation change to each parent.
>         self.prev.push(self.current);
>         self.current = FrameEntry::new(pipeline_id, 0, EntryReason::Load);
> ```

I don't really understand `context_index=0` here, should it be `self.current.context_index + 1`?

---

*[components/constellation/constellation.rs, line 283 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJQxwly-yQzBDSFkpxK:-KJQxwly-yQzBDSFkpxL:1675315938) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L283)):*
> ```Rust
> }
> 
> struct HistoryIterator {
> ```

I think I was thinking of doing this differently... I'll add my thoughts as a separate comment.

---

*[components/constellation/constellation.rs, line 284 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJQxd62m-SBZQvKFBJa:-KJQxd62m-SBZQvKFBJb:1427187916) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L284)):*
> ```Rust
> 
> struct HistoryIterator {
>     stack: Vec<(FrameId, Vec<u64>)>,
> ```

What does each stack entry represent?

---

*[components/constellation/constellation.rs, line 1401 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR71bXBDXnYKdwUc5n:-KJR71bY9cX0xa203C5p:1390484539) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L1401)):*
> ```Rust
>                             frame.prev.push(old);
> 
>                             for _ in 0..delta - 1 {
> ```

Equivalently `1.. delta`.

---

*[components/constellation/constellation.rs, line 1423 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR78RbELs8MewvDqjS:-KJR78RbELs8MewvDqjT:1700997001) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L1423)):*
> ```Rust
>                             frame.next.push(old);
> 
>                             for _ in 0..delta - 1 {
> ```

Ditto.

---

*[components/constellation/constellation.rs, line 1503 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR7Xj9vzw6u92REYP1:-KJR7Xj9vzw6u92REYP2:1731241902) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L1503)):*
> ```Rust
> 
>     fn send_popstate_msg(&mut self, pipeline_id: PipelineId, index: usize) {
>         let msg = ConstellationControlMsg::UpdateActiveHistoryEntry(pipeline_id, index);
> ```

Why do we need to inform script about the history index?

---

*[components/script/script_thread.rs, line 2039 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR8P4Hsz-uTMXOHi2f:-KJR8P4Hsz-uTMXOHi2g:-1222499044) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/script/script_thread.rs#L2039)):*
> ```Rust
>     }
> 
>     fn handle_update_active_history_entry(&self, pipeline_id: PipelineId, active_index: usize) {
> ```

I don't really understand why script is involved with this, shouldn't it just be the constellation?

---

*[components/script/script_thread.rs, line 2049 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR8VndEKCdC2FH7V34:-KJR8VndEKCdC2FH7V35:1700997001) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/script/script_thread.rs#L2049)):*
> ```Rust
>     }
> 
>     fn handle_clear_forward_session_history(&self, pipeline_id: PipelineId) {
> ```

Ditto.

---

*[components/script/dom/history.rs, line 52 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR9bDmU8PWBGCQnjHg:-KJR9bDmU8PWBGCQnjHh:-1861921073) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/script/dom/history.rs#L52)):*
> ```Rust
>     // require this check
>     // https://html.spec.whatwg.org/multipage/#fully-active
>     fn is_fully_active(&self) -> ErrorResult {
> ```

This check may be problematic as it only gives a snapshot, by the time you call this and get the result, you might not be fully active. (This is just one instance where the specs have a disconnect with a concurrent implementation.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11481#-:-KJR6GmP6awpAmVx_lVo:-1325453334)*

**Comment by asajeffrey** [comment]
Got part way through reading the PR. There's a lot of stuff here!

**Comment by ConnorGBrewster** [comment]
I would like to split this out into more PRs. I think it would be good for me to go back through all my changes bit by bit since this is so huge. I do like that idea for the iterator a lot, sadly I still don't think it will work due to my issue where the back iter needs to drop the first entry and push the `entry.current`.

<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Got part way through reading the PR. There's a lot of stuff here!
</details>


---

Review status: 7 of 50 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[components/constellation/constellation.rs, line 268 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJQx91rb_h1rrOZIpDU:-KJRJ5IMIt2YXGSVaEaz:1984794790) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L268)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> I don't really understand `context_index=0` here, should it be `self.current.context_index + 1`?
</details>
The `context_index` is is only for mapping state changes in the script thread. This here is for when a new pipeline(or entry) is loaded which implies a new script thread. This means that the `context_index` will be 0 for that given pipeline because there is only one `SessionHistory` entry on the script thread `BrowsingContext`.

---

*[components/constellation/constellation.rs, line 283 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJQxwly-yQzBDSFkpxK:-KJRJqQhyWJDqaiby9FC:-189593077) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L283)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> I think I was thinking of doing this differently... I'll add my thoughts as a separate comment.
</details>
See above

---

*[components/constellation/constellation.rs, line 284 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJQxd62m-SBZQvKFBJa:-KJRJrwyC9qqioFyDIqz:-1039924336) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L284)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> What does each stack entry represent?
</details>
When looking at each entry, the only thing we actually compare is the time each entry occurred at and then we spit out the `FrameId` so each entry represents a `Frame` and the list of when its forward or backward entries occurred.

---

*[components/constellation/constellation.rs, line 1401 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR71bXBDXnYKdwUc5n:-KJRKRFKLvFeP3wP4HzK:791123037) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L1401)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Equivalently `1.. delta`.
</details>
good catch

---

*[components/constellation/constellation.rs, line 1423 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR78RbELs8MewvDqjS:-KJRKWYpTAv5ivEoRkIs:791123037) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L1423)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Ditto.
</details>
good catch

---

*[components/constellation/constellation.rs, line 1503 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR7Xj9vzw6u92REYP1:-KJRKYm7d6Mf2XytdUAo:434009936) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/constellation/constellation.rs#L1503)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Why do we need to inform script about the history index?
</details>
The script thread for this History API has to store `state` https://html.spec.whatwg.org/multipage/browsers.html#dom-history-pushstate. You can call `pushstate` and `replacestate` and it will store a JS value and create a new session history entry. This has to all be done on the script thread. when we navigate we need to tell the script thread to activate the proper entry so `history.state` returns the correct value and so that the `popstate` event with the state value is fired.

---

*[components/script/script_thread.rs, line 2039 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR8P4Hsz-uTMXOHi2f:-KJRL7fL15LvSU3mRmHf:47239993) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/script/script_thread.rs#L2039)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> I don't really understand why script is involved with this, shouldn't it just be the constellation?
</details>
See above. This is mainly because of the History API. It might be better to separate these changes out from this PR and do those later.

---

*[components/script/script_thread.rs, line 2049 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR8VndEKCdC2FH7V34:-KJRLFqkiG9sDCWusujN:160841994) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/script/script_thread.rs#L2049)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Ditto.
</details>
Same as above.

---

*[components/script/dom/history.rs, line 52 \[r13\]](https://reviewable.io:443/reviews/servo/servo/11481#-KJR9bDmU8PWBGCQnjHg:-KJRLJooSUanvZUDDkO7:375030502) ([raw file](https://github.com/servo/servo/blob/5f96e26919f6d1c74512893bec6aeb5c7901aabc/components/script/dom/history.rs#L52)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> This check may be problematic as it only gives a snapshot, by the time you call this and get the result, you might not be fully active. (This is just one instance where the specs have a disconnect with a concurrent implementation.)
</details>
hmmm do you have any ideas on a fix for that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11481#-:-KJRLRXhYaHszKvawSjG:-660587753)*

**Comment by ConnorGBrewster** [comment]
Closing as I will split this into multiple PRs

**Pull request closed without merging**
