### PR TITLE
[DO NOT MERGE] Add a fast path for shaping ASCII text

### PR DESCRIPTION
**Pull request by mbrubeck**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11237)

### CODE REVIEW

**Comment by mbrubeck** [comment]
CC @pcwalton 

On my Linux laptop this is about twice as fast as Harfbuzz text shaping on https://en.wikipedia.org/wiki/Barack_Obama (~12ms versus ~25ms.)  However, this may regress kerning on Mac OS, because `FontHandleMethods::glyph_h_kerning` is not implemented for Core Text fonts.  It could also regress kerning on Freetype for fonts that have a `GPOS` table but no `kern` table, but I don't know if this is a case that we need to worry about.

Looking at the Core Text API, we may need to write our own code to parse the `kern` table on Mac OS.

**Comment by pcwalton** [comment]
> It could also regress kerning on Freetype for fonts that have a GPOS table but no kern table, but I don't know if this is a case that we need to worry about.

Last I looked, this happens a good bit. We'll probably need to parse the `GPOS` table to handle the subset that's isomorphic to `kern`.

**Comment by pcwalton** [comment]
Great to see that this is a sizable performance win!

**Comment by mbrubeck** [comment]
Closing; will open a new PR when kerning support is finished.

**Pull request closed without merging**
