### PR TITLE
Improve DOM interfaces' extended attributes

### PR DESCRIPTION
**Pull request by nox**
Some should have been `[SameObject]` instead of `[Constant]`. The rest of the changes are additional `[Constant]` and `[Pure]` extended attributes on many operations.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7601)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 18 files at r5.
Review status: 2 of 18 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7601)

**Comment by Ms2ger** [comment]
Reviewed 16 of 18 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/webidls/Event.webidl, line 15 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7601#-JzVmRWm2z3tO3hK8G5H)** ([raw file](https://github.com/servo/servo/blob/46f384162fc764f2d7ed94265dd4aeab855e7071/components/script/dom/webidls/Event.webidl#L15)):</sup>
Gotcha! `initEvent` can break this. Try if you can write a test.

---

<sup>**[components/script/dom/webidls/NodeIterator.webidl, line 23 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7601#-JzVngTSV2jqnw2G4Il-)** ([raw file](https://github.com/servo/servo/blob/46f384162fc764f2d7ed94265dd4aeab855e7071/components/script/dom/webidls/NodeIterator.webidl#L23)):</sup>
"Attributes/methods flagged in this way promise that they will keep returning the same value as long as nothing that has `[Affects=Everything]` executes."

These two always return another node.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7601)

**Comment by Ms2ger** [comment]
Reviewed 16 of 18 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/webidls/Event.webidl, line 15 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7601#-JzVmRWm2z3tO3hK8G5H)** ([raw file](https://github.com/servo/servo/blob/46f384162fc764f2d7ed94265dd4aeab855e7071/components/script/dom/webidls/Event.webidl#L15)):</sup>
Gotcha! `initEvent` can break this. Try if you can write a test.

---

<sup>**[components/script/dom/webidls/NodeIterator.webidl, line 23 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7601#-JzVngTSV2jqnw2G4Il-)** ([raw file](https://github.com/servo/servo/blob/46f384162fc764f2d7ed94265dd4aeab855e7071/components/script/dom/webidls/NodeIterator.webidl#L23)):</sup>
"Attributes/methods flagged in this way promise that they will keep returning the same value as long as nothing that has `[Affects=Everything]` executes."

These two always return another node.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7601)

**Comment by nox** [comment]
@Ms2ger Amended.

---

Review status: 16 of 18 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7601)

**Comment by Ms2ger** [comment]
@bors-servo r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7601)

**Comment by nox** [comment]
```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```

@larsbergstrom?

**Comment by larsbergstrom** [comment]
Gah! I won't be around a computer with ssh for another six hours. @metajack
@edunham?

On Sep 19, 2015, at 9:28 AM, Anthony Ramine <notifications@github.com>
wrote:

Agreeing to the Xcode/iOS license requires admin privileges, please
re-run as root via sudo.

@larsbergstrom <https://github.com/larsbergstrom>?

—
Reply to this email directly or view it on GitHub
<https://github.com/servo/servo/pull/7601#issuecomment-141674221>.

**Comment by nox** [comment]
@bors-servo retry

7422

**Pull request merged**
