### PR TITLE
Implement raqote backend for 2D canvas rendering

### PR DESCRIPTION
**Pull request by pylbrecht**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix (part of) #23431

- [ ] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24201)

### CODE REVIEW

**Comment by jdm** [comment]
I think we should merge these changes after squashing the bitshifting commit and rebasing.

**Review by jdm — APPROVED** [review]

**Comment by CYBAI** [comment]
Tidy failure in linux and windows

```rust
error: attempt to shift left with overflow
  --> components/canvas/raqote_backend.rs:636:27
   |
636|         let color: u32 = (self.color.alpha << 8 * 3 |
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[deny(exceeding_bitshifts)]` on by default

error: attempt to shift left with overflow
  --> components/canvas/raqote_backend.rs:637:13
   |
637|             self.color.red << 8 * 2 |
   |            ^^^^^^^^^^^^^^^^^^^^^^^

error: attempt to shift left with overflow
  --> components/canvas/raqote_backend.rs:638:13
   |
638|             self.color.green << 8 * 1 |
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

error: Could not compile `canvas`.
warning: build failed, waiting for other jobs to finish...
```

the mac one failed with #23290 intermittent

**Comment by jdm** [comment]
You'll need to cast those u8 values to u32 before shifting.

**Comment by pylbrecht** [comment]
Thanks, I'm already on it! Building takes some time since the rebase..

**Pull request merged**
