### PR TITLE
Make fetch() API use same-origin credentials by default

### LINKED ISSUE #21146: Make fetch() API use same-origin credentials by default
This merged last year, and we probably didn't update our implementation: https://github.com/whatwg/fetch/pull/585

### PR DESCRIPTION
**Pull request by tigercosmos**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #21146 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21187)

### CODE REVIEW

**Comment by tigercosmos** [comment]
What's wrong with CI?
```
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: protocol error: bad pack header
```

**Comment by jdm** [comment]
The fetch test results will need to be updated; the websocket failures are #20734.

**Comment by tigercosmos** [comment]
@jdm Do you know what probably causes so many TIMEOUT and NOTURN?

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Pull request merged**
