### PR TITLE
Derive Debug for more font-related types

### PR DESCRIPTION
**Pull request by antrik**
Needs to pull in newer ipc-channel and azure.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9070)

### CODE REVIEW

**Comment by nox** [comment]
@antrik What do you use to update the Cargo files? Did you properly use `./mach update-cargo`?

**Comment by antrik** [comment]
So it turns out I broke ipc-message for all platforms using the "inprocess" backend (target_os="android", target_os="windows") with https://github.com/servo/ipc-channel/pull/21, and apparently there is no CI for that... This is rather unsettling.

**Comment by nox** [comment]
Cc @larsbergstrom @metajack.

**Comment by antrik** [comment]
I submitted a fix for ipc-message: https://github.com/servo/ipc-channel/pull/22

I can update this PR once the ipc-message one is in.

**Comment by antrik** [comment]
I submitted a fix for ipc-message: https://github.com/servo/ipc-channel/pull/22

I can update this PR once the ipc-message one is in.

**Comment by nox** [comment]
Could you update it?

**Comment by antrik** [comment]
I got somewhat uncertain after I realised that for some types -- such as FontTemplateData -- deriving Debug is useless, as it will print the entire blob. However, I checked now that it affects only my other PR (which has already been merged, and will thus need a follow-up), but not this one.

Updated now for the fixed ipc-message.

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9070#-:-K74Gy6vFnmMj8O-Jct4:1236647940)*

**Pull request merged**
