### PR TITLE
Get the right pixel density on Android

### LINKED ISSUE #21504: Android: properly set the pixel density
As of now, the pixel density is hard coded: https://github.com/servo/servo/blob/3d99288f2089af3ecb24825ad23b79932a29fdb6/ports/libsimpleservo/src/api.rs#L468

The same way we set the width and height of the window, we should set the density as an `init` parameter.

I think we can use this Android API to get the proper density: https://developer.android.com/reference/android/util/DisplayMetrics

### LINKED ISSUE #21605: Set pixel density to 1 by default for Android Surface.
Let's not assume the android surface is used as a "regular" 2D widget.

Related: #21504

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #21605 and fix #21504

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21774)

### CODE REVIEW

**Comment by jdm** [comment]
Need to update capital.rs as well. r=me otherwise.

**Comment by CYBAI** [comment]
```
error[E0061]: this function takes 9 parameters but 8 parameters were supplied
  --> ports\libsimpleservo\src\capi.rs:94:5
   |
50 | / fn init(
51 | |     gl: Rc<gl::Gl>,
52 | |     args: *const c_char,
53 | |     url: *const c_char,
...  |
80 | |     ).unwrap();
81 | | }
   | |_- defined here
...
94 |       init(gl, args, url, wakeup, readfile, callbacks, width, height)
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 9 parameters
```

**Pull request merged**
