### PR TITLE
Media cache and buffering support

### LINKED ISSUE #22055: Enable buffering and caching media data in gstreamer
```
<jdm> does gsteamer do any caching, or does it throw away the original buffer it receives?
<ferjm> jdm, I believe so, but I think it requires some setup that we are currently not doing. I need to look into the buffering/caching strategy
```

### LINKED ISSUE #22296: Implement HTMLMediaElement buffered attribute
Spec: https://html.spec.whatwg.org/multipage/media.html#dom-media-buffered 

Depends on #22055

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #22055 and fix #22296

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22692)

### CODE REVIEW

**Comment by ferjm** [comment]
Seeking performs so much better with this patches

ezgif-4-d15006f36ead

**Comment by ceyusa** [comment]
looks ok!

r+

**Comment by ferjm** [comment]
@bors-servo retry
- #22716

**Comment by jdm** [comment]
@bors-servo retry
* #22718 #22717

**Pull request merged**
