### PR TITLE
Fix some custom properties bugs

### LINKED ISSUE #7767: EOF in CSS custom property declaration
When the CSS input ends inside of a `{ … }`, `[ … ]`, `( … )` block, `f( … )` function, or quoted string in a custom property value, all open constructs are closed implicitly but the closing markers should be appended to the value. See failing tests in:

* `tests/wpt/mozilla/tests/css/test_variable_serialization_specified.html`
* `tests/wpt/mozilla/tests/css/test_variable_serialization_computed.html`

The code to change is probably in the `parse_declaration_value` and `parse_declaration_value_block` functions in `components/style/custom_properties.rs`.

I’m planning to work on this.

### PR DESCRIPTION
**Pull request by SimonSapin**
Fix #7767.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8343)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@mbrubeck r?

**Comment by mbrubeck** [comment]
Reviewed 14 of 14 files at r1, 2 of 2 files at r2.
Review status: 13 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/style/custom_properties.rs, line 232 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8343#-K2SpbBW7aqn5ZKoaPl9)** ([raw file](https://github.com/servo/servo/blob/b0194d4216a2a5bfd8b54750955b907a8a6d01b1/components/style/custom_properties.rs#L232)):</sup>
Why `CloseSquareBracket`? Should this be `token.serialization_type()` instead?


---

<sup>**[components/style/custom_properties.rs, line 273 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8343#-K2SwQVqeQoE90x9-lwZ)** ([raw file](https://github.com/servo/servo/blob/b0194d4216a2a5bfd8b54750955b907a8a6d01b1/components/style/custom_properties.rs#L273)):</sup>
Maybe add a link to https://drafts.csswg.org/css-syntax/#typedef-declaration-value to explain the delimeter check here?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8343)

**Comment by SimonSapin** [comment]
Review status: 13 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/style/custom_properties.rs, line 232 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8343#-K2SpbBW7aqn5ZKoaPl9)** ([raw file](https://github.com/servo/servo/blob/b0194d4216a2a5bfd8b54750955b907a8a6d01b1/components/style/custom_properties.rs#L232)):</sup>
That was a copy-paste error. Fixed.


---

<sup>**[components/style/custom_properties.rs, line 273 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8343#-K2SwQVqeQoE90x9-lwZ)** ([raw file](https://github.com/servo/servo/blob/b0194d4216a2a5bfd8b54750955b907a8a6d01b1/components/style/custom_properties.rs#L273)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8343)

**Comment by mbrubeck** [comment]
Reviewed 2 of 2 files at r3, 2 of 2 files at r4, 4 of 4 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8343)

**Pull request merged**
