### PR TITLE
mach: automatically use the 'minimal' rustup profile + rustc-dev component

### LINKED ISSUE #25401: build error: can't find crate for `rustc`
`./mach build --dev`

```bash
....
  Compiling data-url v0.1.0
   Completed lock_api v0.3.1 in 0.5s
   Compiling script_plugins v0.0.1 (/Users/grishy/projects/servo/components/script_plugins)
error[E0463]: can't find crate for `rustc`
  --> components/script_plugins/lib.rs:24:1
   |
24 | extern crate rustc;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `script_plugins`.
warning: build failed, waiting for other jobs to finish...
   Completed semver v0.9.0 in 1.1s
   Completed core-foundation-sys v0.6.2 custom-build (run) in 0.8s
   Completed crossbeam-utils v0.6.5 in 1.2s
   Completed futures v0.1.28 in 6.2s
   Completed base64 v0.10.1 in 0.6s
   Completed data-url v0.1.0 in 0.5s
   Completed hex v0.3.2 in 1.8s
   Completed bitflags v1.2.1 custom-build (run) in 1.1s
   Completed itertools v0.8.0 in 1.8s
   Completed num-traits v0.2.4 custom-build (run) in 1.6s
   Completed serde v1.0.103 custom-build (run) in 1.8s
   Completed libc v0.2.62 custom-build (run) in 2.2s
   Completed array-init v0.0.4 in 3.5s
   Completed regex-syntax v0.6.6 in 4.5s
   Completed ucd v0.1.1 in 9.3s
error: build failed
Build FAILED in 0:08:19
```

```bash
➜  servo git:(master) ✗ rustc -V
rustc 1.42.0-nightly (9b98af84c 2019-12-22)
```

### LINKED ISSUE #25402: build error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable
`./mach build -d` (as well as `--release`) give the same error:
```
info: syncing channel updates for 'nightly-2019-12-23-x86_64-unknown-linux-gnu'
info: latest update on 2019-12-23, rust version 1.42.0-nightly (9b98af84c 2019-12-22)
error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly-2019-12-23
Build FAILED in 0:00:01
```
Environment- Ubuntu 19.04

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes https://github.com/servo/servo/issues/25401
Fixes https://github.com/servo/servo/issues/25402

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by SimonSapin** [comment]
Since last review: https://github.com/servo/servo/compare/742def6b3e29857b9ba8b33079a6deba76e027b4...8fc072a375378dcc73d2e348d8e46a4d735e6210

**Pull request merged**
