### PR TITLE
Use mime! macro in fetch methods

### PR DESCRIPTION
**Pull request by KiChjang**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10471)

### CODE REVIEW

**Comment by KiChjang** [comment]
Needs #10470 first, otherwise this will fail compiling.

**Comment by KiChjang** [comment]
Woah, what went wrong on Travis?

**Comment by emilio** [comment]
Looks good to me, way easier to read!

@bors-servo: r+

**Comment by emilio** [comment]
@KiChjang Lockfiles need to be updated, then `r=me`

**Comment by KiChjang** [comment]
@bors-servo retry
* #10392

**Pull request merged**
