### PR TITLE
Flow inlines around floats

### LINKED ISSUE #29825: Layout 2020: Add support for flowing inlines around floating elements
This is the next big feature required for a proper float implementation. Inline layout should flow around floating boxes.

cc @Loirooriol

### PR DESCRIPTION
**Pull request by mrobinson**
This implements the rest of the bulk of float support. Now inline
elements flow around floats and floats can be pushed down by inline
elements before them.

Co-authored-by: Oriol Brufau <obrufau@igalia.com>

Fixes #29825.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
The two failures are addressed in #30245 and #30246.

**Comment by Loirooriol** [comment]
I did some tweaks, mostly editorial, but also addressed a `text-align` problem with this testcase:

```html
<!DOCTYPE html>
<div style="border: solid; width: 100px; text-indent: 0px; text-align: center">
  <div style="float: left; width: 25px; height: 50px; background: magenta"></div>
  <div style="display: inline-block; background: cyan; width: 30px; height: 50px"></div>
</div>
<div style="border: solid; width: 100px; text-indent: 20px; text-align: center">
  <div style="float: left; width: 25px; height: 50px; background: magenta"></div>
  <div style="display: inline-block; background: cyan; width: 30px; height: 50px"></div>
</div>
<div style="border: solid; width: 100px; text-indent: 45px; text-align: center">
  <div style="float: left; width: 25px; height: 50px; background: magenta"></div>
  <div style="display: inline-block; background: cyan; width: 30px; height: 50px"></div>
</div>
<div style="border: solid; width: 100px; text-indent: 46px; text-align: center">
  <div style="float: left; width: 25px; height: 50px; background: magenta"></div>
  <div style="display: inline-block; background: cyan; width: 30px; height: 50px"></div>
</div>
```

**Comment by mrobinson** [comment]
Thanks @Loirooriol. Your changes look good to me. If the change looks good to you now as well, feel free to r+ and merge.

**Review by Loirooriol — APPROVED** [review]

**Pull request merged**
