### PR TITLE
Low hanging Dromaeo fruit

### PR DESCRIPTION
**Pull request by pcwalton**
I took a look at the profile and fixed some obvious issues.

Didn't have time to get actual performance numbers on this.

r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6900)

### CODE REVIEW

**Comment by pcwalton** [comment]
cc @metajack

**Comment by SimonSapin** [comment]
Doesn’t `into_ascii_lowercase` emit deprecation warnings? Since we’ve updated past https://github.com/rust-lang/rust/pull/26914.

`AsciiExt::make_ascii_lowercase` (on `&mut String` without a return value) has the same functionality without copying.

**Comment by pcwalton** [comment]
Fixed comment, added a couple more perf fixes.

**Comment by SimonSapin** [comment]
Looks good to me except that I don’t know what the `[Pure]` annotations mean.

**Comment by Ms2ger** [comment]
Are debug_asserts checked in homu builds?

[The `[Pure]` annotations](https://developer.mozilla.org/en-US/docs/Mozilla/WebIDL_bindings#Pure) seem to be correct.

**Comment by pcwalton** [comment]
They are not presently checked in WPT tests since we started compiling in release mode. I think we could fix that with Cargo profiles, but I would like to do that as a followup since this is an important performance fix.

**Comment by jdm** [comment]
I would like to see Dromaeo before and after numbers for this.

**Comment by nox** [comment]
https://github.com/servo/saltfs/pull/107

**Comment by pcwalton** [comment]
@jdm Here's a link with the performance numbers. There seems to be a lot of noise, but it looks positive overall. https://docs.google.com/spreadsheets/d/1CPBJmvTqNEAAGWFQQzfJ8YKNxEQ7AL2wJ2gagt5Td3o/edit?usp=sharing

**Comment by metajack** [comment]
What's the explanation for the 40-50% regressions? I'm not as concerned about the other ones.

**Comment by pcwalton** [comment]
I'll run again. I suspect it's just that the tests are really noisy.

**Comment by pcwalton** [comment]
One of the 50% regressions is SunSpider, which pretty much has to be noise because it doesn't touch the DOM at all.

**Comment by pcwalton** [comment]
@metajack I did another run and updated the spreadsheet.

It looks like Dromaeo is just too noisy in Servo to really draw any conclusions here.

**Comment by nox** [comment]
Second commit is overseded by #7601.

For the first one, @jdm doesn't want to remove the asserts in release because we can't run the tests in debug mode. What if we introduce an Atom wrapper type signalling that its contents is indeed a valid XML name?

Third commit is nice and could be merged now.

**Comment by pcwalton** [comment]
@jdm, do you concur with @nox' assessment here? Would you be willing to merge the third commit?

**Comment by nox** [comment]
@pcwalton For first commit, you can still improve the asserts themselves by not allocating a lowercase name and traversing it only once.

**Comment by jdm** [comment]
Yes, third commit looks fine.

**Comment by jdm** [comment]
Closing this PR in favour of future work that eventually allows us to move to debug_assert! without losing confidence that we'll actually detect regressions.

**Pull request closed without merging**
