### PR TITLE
Properly handle variadic arguments preceded by default values

### PR DESCRIPTION
**Pull request by nox**
I broke that in #8197.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8498)

### CODE REVIEW

**Comment by nox** [comment]
Cc @jdm

**Comment by jdm** [comment]
@bors-servo: r+
Makes sense. Thanks!

**Comment by nox** [comment]
@bors-servo p=1

Because it's too embarrassing for my own good. =)

**Comment by nox** [comment]
@bors-servo retry

```
23:29 <@larsberg> nox: Manishearth: I don't really understand it, either, but it seems to occur in low-memory situations
23:29 <Manishearth> I mean, I see where it's useful
23:30 <Manishearth> larsberg: wut
23:30 <nox> Should I just retry?
23:30 <Manishearth> nox: yes
```

**Pull request merged**
