### PR TITLE
Moved Location object from Window to Document

### LINKED ISSUE #4840: Location object should live in Document, not Window
Spec: https://html.spec.whatwg.org/multipage/browsers.html#the-location-interface
Code: components/script/dom/window.rs, components/script/dom/document.rs

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #4840

### CODE REVIEW

**Comment by KiChjang** [comment]
Hmm... how can I extract `Rc<Page>` from the `Window` object?

**Comment by jdm** [comment]
Whoops. I guess you'll need a new method like `page_clone` that returns the right type.

**Comment by KiChjang** [comment]
Okay! This should be ready for another review.

**Comment by jdm** [comment]
If you squash them together, I'll merge :)

**Comment by KiChjang** [comment]
Here you go

**Pull request merged**
