### PR TITLE
Initialize the slots of global objects before a possible GC.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8918)

### CODE REVIEW

**Comment by KiChjang** [comment]
Wait one second.

The Travis CI build didn't even commence - perhaps homu is having the same problem?

**Comment by KiChjang** [comment]
```
Ran 3733 tests finished in 880.0 seconds.
  • 3732 ran as expected. 708 tests skipped.
  • 1 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected OK] /_mozilla/mozilla/webgl/bufferData.html
  │ 
  │ thread 'WebGLTask' panicked at 'assertion failed: gl::get_error() == gl::NO_ERROR', /Users/servo/buildbot/slave/mac-rel-wpt/build/components/canvas/webgl_paint_task.rs:176
  │ stack backtrace:
  │    1:        0x108227e78 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x108229f3f - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x1082299e2 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x108215726 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x1075a23c4 - sys_common::unwind::begin_unwind::begin_unwind::h4569555697223706456
  │    6:        0x1075da357 - webgl_paint_task::_<impl>::handle_webgl_message::hb2981b9ed30feedca9r
  │    7:        0x1075dcbde - sys_common::unwind::try::try_fn::try_fn::h16524033226000240316
  │    8:        0x1082272b8 - __rust_try
  │    9:        0x1082243be - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   10:        0x1075ddc31 - boxed::_<impl>::call_box::call_box::h10948343521811825872
  │   11:        0x1082291cd - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   12:     0x7fff84ed8059 - _pthread_body
  │   13:    ALERT: RESULT: ["/_mozilla/mozilla/webgl/bufferData.html",0,null,null,[["bufferData and bufferSubData input array type check (issue #6791)",0,null,null]]]
```

**Comment by jdm** [comment]
@bors-servo: retry
* #8924

**Comment by KiChjang** [comment]
```
Ran 3733 tests finished in 246.0 seconds.
  • 3732 ran as expected. 709 tests skipped.
  • 1 tests timed out unexpectedly
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ TIMEOUT [expected CRASH] /workers/semantics/xhr/001.html
  │ 
  │ thread 'WebWorker for http://web-platform.test:8000/workers/semantics/xhr/001.html#' panicked at 'expected a Window scope', /home/servo/buildbot/slave/linux-rel/build/components/script/dom/bindings/global.rs:73
  │ stack backtrace:
  │    1:     0x5631fa8d1880 - sys::backtrace::tracing::imp::write::h92808652e552bec0MZt
  │    2:     0x5631fa8d46e5 - panicking::log_panic::_<closure>::closure.41184
  │    3:     0x5631fa8d4160 - panicking::log_panic::hc4038fe8a2a609d626x
  │    4:     0x5631fa8bdbe3 - sys_common::unwind::begin_unwind_inner::hd5a3cc6e3320d6b8lSs
  │    5:     0x5631f964eaef - sys_common::unwind::begin_unwind::begin_unwind::h10528527346985475295
  │    6:     0x5631f9a939f9 - dom::xmlhttprequest::_<impl>::new_doc::h3c7a40b41e9a9169mEY
  │    7:     0x5631f9a92a8c - dom::xmlhttprequest::_<impl>::handle_xml::h36b9539d653de1d2nDY
  │    8:     0x5631f98af957 - dom::xmlhttprequest::_<impl>::GetResponseXML::h99eaed5c42cbf28cfiY
  │    9:     0x5631f98af2db - dom::bindings::codegen::Bindings::XMLHttpRequestBinding::get_responseXML::h3d7d04f717088d5cGTd
  │   10:     0x5631f9fe82e6 - CallJitGetterOp
  │   11:     0x5631f968bfe7 - dom::bindings::utils::generic_call::hbcacf4900a536a849Zf
  │   12:     0x5631fa10403c - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jscntxtinlines.h:235
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:502
  │   13:     0x5631fa10552e - _ZN2js6InvokeEP9JSContextRKN2JS5ValueES5_jPS4_NS2_13MutableHandleIS3_EE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:558
  │   14:     0x5631fa108c49 - _ZN2js20InvokeGetterOrSetterEP9JSContextP8JSObjectN2JS5ValueEjPS5_NS4_13MutableHandleIS5_EE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:628
  │   15:     0x5631fa12a0f2 - _ZL10CallGetterP9JSContextN2JS6HandleIP8JSObjectEENS2_IPN2js5ShapeEEENS1_13MutableHandleINS1_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:1614
  │   16:     0x5631fa149e00 - _ZN2js17NativeGetPropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_IP8JSObjectEENS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:1664
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:1878
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:1912
  │   17:     0x5631fa110908 - _ZN2js11GetPropertyEP9JSContextN2JS6HandleIP8JSObjectEES6_NS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.h:1434
  │   18:     0x5631fa0f851b - _ZL9InterpretP9JSContextRN2js8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:260
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2426
  │   19:     0x5631fa103d1c - _ZN2js9RunScriptEP9JSContextRNS_8RunStateE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  │   20:     0x5631fa103f9d - _ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:521
  │   21:     0x5631fa10552e - _ZN2js6InvokeEP9JSContextRKN2JS5ValueES5_jPS4_NS2_13MutableHandleIS3_EE
  │                         at /home/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:558
  └   22:     0x5631fa3cda39 - _Z20JS_CallFunctionValueP9JSContextN2JS6HandleIP8JSObjectEENS2_INS1_5ValueEEERKNS1_16HandleValueArrayENS1_13MutableHandleIS6_EE

  ▶ Unexpected subtest result in /workers/semantics/xhr/001.html:
  │ TIMEOUT [expected PASS] async XMLHttpRequest in dedicated worker
  └   → Test timed out
```

**Comment by jdm** [comment]
@bors-servo: retry
* #8931

**Pull request merged**
