### PR TITLE
Issue #15723: Skip git ignored files in update-manifest.

### LINKED ISSUE #15725: Spurious .DS_Store entries when running ./mach update-manifest on macOS
```diff
diff --git i/tests/wpt/mozilla/meta/MANIFEST.json w/tests/wpt/mozilla/meta/MANIFEST.json
index fc2c7b6818..907e06b8d8 100644
--- i/tests/wpt/mozilla/meta/MANIFEST.json
+++ w/tests/wpt/mozilla/meta/MANIFEST.json
@@ -6633,6 +6633,11 @@
    ]
   },
   "support": {
+   "./.DS_Store": [
+    [
+     {}
+    ]
+   ],
    "./lint.whitelist": [
     [
      {}
@@ -9333,6 +9338,11 @@
      {}
     ]
    ],
+   "mozilla/.DS_Store": [
+    [
+     {}
+    ]
+   ],
    "mozilla/2x2.png": [
     [
      {}
```

### PR DESCRIPTION
**Pull request by kregoslup**
This patch makes "./mach update-manifest" aware of .gitignore.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15725 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because I don't know how to test it, I have tried mocking opening file and checking whether it exists but it's difficult to handle both in py2.7 and py3 and I think it would say too much about `PathFilter` internals. I have also tried mocking `PathFilter` but then I would be duplicating logic in tests. 

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19550)

### CODE REVIEW

**Comment by jdm** [comment]
r? @jgraham 
This touches enough code that I'm unfamiliar with that it would be good to have your eyes on it.

**Comment by nox** [comment]
That change will get upstreamed automatically, right?

**Comment by jdm** [comment]
Yes.

**Comment by jgraham** [comment]
So I think this is the wrong fix. `update()` is called with a `tree` object from the confusingly named `vcs.py` and the `Git` tree class presumably considers `.gitignore` by default and the `FileSystem` tree class imports and uses the `gitignore` module. So, unless I'm missing something, if this patch changes the behaviour, it's either because the existing code is buggy and should be fixed, or because the caller from the servo mach command is passing in the wrong kind of object. In either case the fix should be closer to the source.

**Comment by jdm** [comment]
Note: update-manifest command is at https://github.com/kregoslup/servo/blob/687e6378df1b242cbaa425cc9b7686f63201d708/python/servo/testing_commands.py#L426-L433, which invokes https://github.com/kregoslup/servo/blob/687e6378df1b242cbaa425cc9b7686f63201d708/python/servo/testing_commands.py#L362-L394, which invokes https://github.com/kregoslup/servo/blob/687e6378df1b242cbaa425cc9b7686f63201d708/tests/wpt/run_wpt.py.

**Comment by kregoslup** [comment]
OK, I think I found the bug but I'm not sure, can I ask a few questions? 
Issue happens only in `tests/wpt/mozilla/`, because there is no .gitignore file in there. When https://github.com/servo/servo/blob/687e6378df1b242cbaa425cc9b7686f63201d708/tests/wpt/web-platform-tests/tools/manifest/update.py#L18-L26 update function calls manifest update with a tree object, either `git tree` or `filesystem tree`, PathFilter finds no `.gitignore` in that directory and here https://github.com/servo/servo/blob/687e6378df1b242cbaa425cc9b7686f63201d708/tests/wpt/web-platform-tests/tools/gitignore/gitignore.py#L90-L112 has no extras argument and does not read gitignore file because it does not exists and trivial attribute is set to False because `ignore_path` variable is not None. My question is, which of these solutions do you think would be the best? I'm not sure what's the expected behaviour in this situation.
1. Add .gitignore to `tests/wpt/mozilla/` ?
2. Add looking for additional gitignore files in other directiories?
3. Change PathFilter behaviour to inform or log or set that it hasn't found any gitignore file in tests root directory or set its `trivial` attribute to True?

I think I'll go with 1 and 3, please let me know what do you think about that.

**Comment by jdm** [comment]
Let's add a .gitignore to tests/wpt/mozilla.

**Comment by jdm** [comment]
@kregoslup This PR now contains a single commit that only adds a .gitignore file. Where did the rest of the work go?

**Comment by kregoslup** [comment]
I figured out that the bug was only missing gitignore, so I amended previous commit and added only .gitignore file to path where it was missing. Do you mean that I should add tests?

**Comment by jdm** [comment]
@bors-servo r+
Oh, huh. That works for me!

**Comment by jdm** [comment]
@bors-servo: retry
* #13480

**Pull request merged**
