### PR TITLE
Move HSTS/CookieStorage to Arc<RwLock> from Ipc

### PR DESCRIPTION
**Pull request by samfoo**
servo/servo#7421

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7654)

### CODE REVIEW

**Comment by jdm** [comment]
Looking pretty good!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

<sup>**[components/net/http_loader.rs, line 326 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVkTWYhLyIlYNP1IIW)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/http_loader.rs#L326)):</sup>
nit: &Arc

---

<sup>**[components/net/http_loader.rs, line 335 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVkS54W3T0YJvUaVpS)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/http_loader.rs#L335)):</sup>
nit: &Arc

---

<sup>**[components/net/http_loader.rs, line 351 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVkNljJTarTil6mIGi)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/http_loader.rs#L351)):</sup>
nit: &Arc

---

<sup>**[components/net/http_loader.rs, line 363 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVkM0G00gPluVOwhwc)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/http_loader.rs#L363)):</sup>
nit: &Arc

---

<sup>**[components/net/http_loader.rs, line 504 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVkqDCJt8UyZ1mfZmk)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/http_loader.rs#L504)):</sup>
I think I'd still prefer the `request_must_be_secured` abstraction instead of inlining this here.

---

<sup>**[components/net/resource_task.rs, line 166 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVl6WwenMF5e8wcgKN)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/resource_task.rs#L166)):</sup>
Is this clone necessary?

---

<sup>**[components/net/resource_task.rs, line 167 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlHQRBP1X6MOjN3YS)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/resource_task.rs#L167)):</sup>
This could use `read` instad, right?

---

<sup>**[components/net/resource_task.rs, line 208 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlLD2tZmw946y7pJ4)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/resource_task.rs#L208)):</sup>
Is this clone necessary?

---

<sup>**[tests/unit/net/hsts.rs, line 15 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVl_gohfGCwHUcrVHe)** ([raw file](https://github.com/servo/servo/blob/b511004a616862394318381d7ef5ac3c59c7babe/tests/unit/net/hsts.rs#L15)):</sup>
Why remove this test?

---

<sup>**[tests/unit/net/http_loader.rs, line 180 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVleGxn-zHfDeWM4Ia)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L180)):</sup>
This can be `read`, right?

---

<sup>**[tests/unit/net/http_loader.rs, line 401 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlr2CxpLpQJYgf3p9)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L401)):</sup>
Why's this clone necessary?

---

<sup>**[tests/unit/net/http_loader.rs, line 434 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlziNWYDqVtZ6tEXL)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L434)):</sup>
Unnecessary clone?

---

<sup>**[tests/unit/net/http_loader.rs, line 484 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVmB_B20IXq83WCTaN)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L484)):</sup>
Let's reuse `url`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7654)

**Comment by samfoo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[components/net/resource_task.rs, line 167 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlHQRBP1X6MOjN3YS)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/resource_task.rs#L167)):</sup>
Very confusingly, no. `CookieStorage::cookies_for_url` takes `&mut self`. I haven't investigated why.

---

<sup>**[tests/unit/net/hsts.rs, line 15 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVl_gohfGCwHUcrVHe)** ([raw file](https://github.com/servo/servo/blob/b511004a616862394318381d7ef5ac3c59c7babe/tests/unit/net/hsts.rs#L15)):</sup>
The resource manager is now just responsible for owning the HSTS list. Adding and removing entries is only done on the list, rather than through the manager. This test no longer is really testing anything.

---

<sup>**[tests/unit/net/http_loader.rs, line 180 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVleGxn-zHfDeWM4Ia)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L180)):</sup>
Same as above.

---

<sup>**[tests/unit/net/http_loader.rs, line 401 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlr2CxpLpQJYgf3p9)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L401)):</sup>
Load consumes hsts_list by value. The assertion on the line below needs to use the list again. In this case, cloning an Arc shouldn't matter anyway, right? It's not really cloning the list, just the pointer?

---

<sup>**[tests/unit/net/http_loader.rs, line 434 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlziNWYDqVtZ6tEXL)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L434)):</sup>
Same as above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7654)

**Comment by jdm** [comment]
-S-awaiting-review -S-needs-rebase +S-needs-code-changes 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/resource_task.rs, line 167 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlHQRBP1X6MOjN3YS)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/components/net/resource_task.rs#L167)):</sup>
Oh right, we update the last used time in the cookies that get retrieved.

---

<sup>**[tests/unit/net/http_loader.rs, line 401 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlr2CxpLpQJYgf3p9)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L401)):</sup>
load consumes the result of `hsts_list.clone()`, and `hsts_list` remains unconsumed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7654)

**Comment by samfoo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/http_loader.rs, line 401 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlr2CxpLpQJYgf3p9)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L401)):</sup>
Whoops, you're right! I got a bit carried away there. Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7654)

**Comment by samfoo** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[tests/unit/net/http_loader.rs, line 434 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7654#-JzVlziNWYDqVtZ6tEXL)** ([raw file](https://github.com/servo/servo/blob/61716703aacf7543c2acca0d76ee0fb6a7df398b/tests/unit/net/http_loader.rs#L434)):</sup>
Removed, as above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7654)

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7654)

**Comment by jdm** [comment]
@bors-servo: retry
* #7422

**Pull request merged**
