### PR TITLE
Background serialization of multiple values.

### PR DESCRIPTION
**Pull request by absoludity**
Similar to animation, the serialization of multiple backgrounds should
return the longhands serialization if there are an unequal number of
values for the required properties. This is part of #15398 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15733)

### CODE REVIEW

**Comment by absoludity** [comment]
@upsuper Hi there. There are a couple of things I need feedback on here, related to the fact that not all background properties are required for serialization, unlike animation.

I've ensured the existing tests pass with this change, but there are a couple of tests missing, which I'd like to add, but need to know whether what I've stated in the comments below about the background color, size, origin and clip are correct or not, regarding serialization (as I don't see these explicitly mentioned at https://drafts.csswg.org/cssom/#serialize-a-css-declaration-block ). If you can confirm or correct those comments, I'll add the missing tests and update. Thanks!

**Comment by upsuper** [comment]
It doesn't seem to me there is any difference between `background` and `animation` except `background-color` which only appears in the last item. All of `background-{image,position,size,repeat,origin,clip,attachment,color}` are required to present, and all but `background-color` are required to have identical length in order to have `background` serializable, since `background` shorthand cannot represent the value otherwise.

**Comment by absoludity** [comment]
@upsuper I can do that, but the reason I didn't (and assumed they must be optional for the serialization) is because the existing test:

background_should_always_print_color_and_url_and_repeat_and_attachment_and_position

itself assumes that the size, origin and clip can be absent while still serializing to a shorthand. Here's a diff that has tests from master, but ensures size, origin and clip have identical length when serializing background (with the failure below):

https://gist.github.com/absoludity/0e951bd89cf1ec91507befddfdb26148

Let me know whether I should remove the test, or keep it passing.

**Comment by upsuper** [comment]
I think that test is wrong. You can fix that test via specifying `size`, `origin`, and `clip` to a explicit value rather than `Initial`.

**Comment by absoludity** [comment]
@upsuper . If I add size, origin and clip as explicit values, the test is identical (in nature) to the existing:

background_should_serialize_all_available_properties_when_specified

I think? I'll remove it and push - let me know if that's not right.

**Comment by upsuper** [comment]
In that case, I think we should remove it. It seems this test was added in #12572, and I don't have idea what it really means to check...

**Comment by absoludity** [comment]
@upsuper Great, done (and update implementation now that Options aren't needed).

**Comment by absoludity** [comment]
I've added a second commit with the same treatment of transitions, since it was straight forward (and simplified the one existing transition serialization test while there).

**Comment by upsuper** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/properties/shorthand/box.mako.rs, line 136 at r3](https://reviewable.io:443/reviews/servo/servo/15733#-KdpIUaYRk_YBQ4UAt3G:-KdpIUaZ2nS7gD57s0Qt:b-vlnqbz) ([raw file](https://github.com/servo/servo/blob/e0f6624305e61862dedcd6e6b7076915fc853eb3/components/style/properties/shorthand/box.mako.rs#L136)):*
> ```Rust
>     impl<'a> LonghandsToSerialize<'a>  {
>         fn to_css_declared<W>(&self, dest: &mut W) -> fmt::Result where W: fmt::Write {
>             fn extract_value<T>(x: &DeclaredValue<T>) -> Option< &T> {
> ```

The usages of `extract_value` makes me wonder... why not just have the helper function include the part of getting length? Also it seems this is quite a useful function that various shorthands need, we can name it something like `get_value_length`, and put it in `properties.mako.rs`'s `mod shorthands` so that it can be shared in all these shorthands.

---

*[tests/unit/style/properties/serialization.rs, line 20 at r3](https://reviewable.io:443/reviews/servo/servo/15733#-KdpEux54YSR-eG_fU08:-KdpEux54YSR-eG_fU09:bffghq4) ([raw file](https://github.com/servo/servo/blob/e0f6624305e61862dedcd6e6b7076915fc853eb3/tests/unit/style/properties/serialization.rs#L20)):*
> ```Rust
> use style_traits::ToCss;
> 
> fn property_declaration_block(css_properties: &str) -> PropertyDeclarationBlock {
> ```

Probably call it `parse_declaration_block` or something? As a helper function, rather than a test, it is probably better using a verb phrase as its name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15733)*

**Comment by absoludity** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/properties/shorthand/box.mako.rs, line 136 at r3](https://reviewable.io:443/reviews/servo/servo/15733#-KdpIUaYRk_YBQ4UAt3G:-KdtjVZOPdnxMyat9JP5:bxjj9pn) ([raw file](https://github.com/servo/servo/blob/e0f6624305e61862dedcd6e6b7076915fc853eb3/components/style/properties/shorthand/box.mako.rs#L136)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

The usages of `extract_value` makes me wonder... why not just have the helper function include the part of getting length? Also it seems this is quite a useful function that various shorthands need, we can name it something like `get_value_length`, and put it in `properties.mako.rs`'s `mod shorthands` so that it can be shared in all these shorthands.
</blockquote></details>

Yeah - I thought the same, but I'm not sure it's possible... that is, the ```current extract_value``` function is possible because it takes a reference to a DeclaredValue<T> and returns Option<&T> - without needing to know what T is. If I try to make it instead get_value_length in the same way, the compiler needs to know either what T is or that it implements a trait supporting indexing:

```error: attempted tuple index `0` on type `&T`, but the type was not a tuple or tuple struct```

I assume I *could* do this if there was some type of enum or tuple trait for index operations via a ```where T: foo::IndexTrait```(and ensuring it's implemented on all the SpecifiedValue types involved - as they all seem completly separate), but I don't yet see any way to do this? Ideas or hints? :)
```


---

*[tests/unit/style/properties/serialization.rs, line 20 at r3](https://reviewable.io:443/reviews/servo/servo/15733#-KdpEux54YSR-eG_fU08:-KdtoRNMV1dKRxkWQUZe:b-896fix) ([raw file](https://github.com/servo/servo/blob/e0f6624305e61862dedcd6e6b7076915fc853eb3/tests/unit/style/properties/serialization.rs#L20)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Probably call it `parse_declaration_block` or something? As a helper function, rather than a test, it is probably better using a verb phrase as its name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15733)*
<!-- Sent from Reviewable.io -->

**Comment by upsuper** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/properties/shorthand/box.mako.rs, line 136 at r3](https://reviewable.io:443/reviews/servo/servo/15733#-KdpIUaYRk_YBQ4UAt3G:-Kdx2DJEb-nKzHn-SBuZ:bl25dgi) ([raw file](https://github.com/servo/servo/blob/e0f6624305e61862dedcd6e6b7076915fc853eb3/components/style/properties/shorthand/box.mako.rs#L136)):*
<details><summary><i>Previously, absoludity (Michael Nelson) wrote…</i></summary><blockquote>

Yeah - I thought the same, but I'm not sure it's possible... that is, the ```current extract_value``` function is possible because it takes a reference to a DeclaredValue<T> and returns Option<&T> - without needing to know what T is. If I try to make it instead get_value_length in the same way, the compiler needs to know either what T is or that it implements a trait supporting indexing:

```error: attempted tuple index `0` on type `&T`, but the type was not a tuple or tuple struct```

I assume I *could* do this if there was some type of enum or tuple trait for index operations via a ```where T: foo::IndexTrait```(and ensuring it's implemented on all the SpecifiedValue types involved - as they all seem completly separate), but I don't yet see any way to do this? Ideas or hints? :)


</blockquote></details>

Oh, hmmm, you're right. That's probably more involved than I thought, and the change would be out of scope of this issue. OK, then I guess we can leave it as is for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15733)*

**Pull request merged**
