### PR TITLE
Downgrade selectors not() behavior to level 3

### PR DESCRIPTION
**Pull request by bholley**
https://bugzilla.mozilla.org/show_bug.cgi?id=1348802

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16606)

### CODE REVIEW

**Comment by jdm** [comment]
This is hitting the problem that https://github.com/servo/servo/issues/16602 describes.

**Comment by bholley** [comment]
@Manishearth any idea what's going on here?

**Comment by Manishearth** [comment]
@bors-servo retry

 - infra 😢

**Comment by SimonSapin** [comment]
I think retrying is not gonna help, the builders’s `target` directory are in a state that is broken for compiletest.

Let me try something in #16601…

**Comment by Manishearth** [comment]
Yes, and I blew away  the offending files on the builder a few hours ago

**Comment by SimonSapin** [comment]
> the offending files

Did you try to do it selectively? If so it might be easier to remove the entire `target` dir, on all builders.

**Comment by Manishearth** [comment]
I did it selectively, and a PR landed. The dir got polluted again, probably due to the cargo PR?

**Comment by SimonSapin** [comment]
#16601 last ran on CI 10 hours ago.

> on all builders.

Or at least the six `servo-linux-*` builders. They’re the ones that semi-randomly get assigned `linux-dev` jobs, which is the only one that runs compile tests.

**Comment by Manishearth** [comment]
Ah, fair.

**Pull request merged**
