### PR TITLE
Trigger image.onerror

### LINKED ISSUE #12885: img onload is dispatched instead of onerror on failed requests
Here is an example illustrating the issue:

https://Gozala.jsbin.com/yugoqil

You should see `Load failed!` message but in servo you see `Load complete.` instead. If you look at the source code https://Gozala.jsbin.com/yugoqil/edit?html,js,output you'll see that's because `onload` event handler on `` is called instead of expected `onerror`.

### PR DESCRIPTION
**Pull request by paulrouget**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #12885 (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12921)

### CODE REVIEW

**Comment by paulrouget** [comment]
Test added.

**Comment by Ms2ger** [comment]
@bors-servo r-

Put the test in wpt.

**Comment by paulrouget** [comment]
> Put the test in wpt.

Do I just need to move this test under `tests/wpt/web-platform-tests/`? If so, where do you recommend we to put it?

**Comment by nox** [comment]
What about in `tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/`?

**Comment by paulrouget** [comment]
> What about in tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/?

I see multiple img.onerror tests in there. I'll see why they don't seem to pass.

**Comment by nox** [comment]
Ah silly me it was a try anyway. ¯\_(ツ)_/¯

**Comment by paulrouget** [comment]
I guess that should do it.

**Comment by jdm** [comment]
That test loads an SVG image and only uses `onload`; it now times out with these changes since we can't deal with SVG images. The test result will need to be updated.

**Comment by paulrouget** [comment]
Green.

**Pull request merged**
