### PR TITLE
Fix a bunch of clippy lints

### PR DESCRIPTION
**Pull request by karyon**
This fixes about 130 clippy lints. Let me know if i should split up the commit.

I wasn't sure about some of the changes, especially map_or instead of map(...).unwrap_or(...) and if let instead of single arm match were not always a strict improvement in my opinion, but i'll leave that decision to the reviewer :)

There are about 150 lints left which i thought were clippy bugs or i didn't know how to fix.

cc @Manishearth

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9123)

### CODE REVIEW

**Comment by Manishearth** [comment]
Reviewed 59 of 59 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/devtools/protocol.rs, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9123#-K73Hgy3-dkK0vqvs-qQ:-K73Hgy4oal-IzyLIPQd:276593601) ([raw file](https://github.com/servo/servo/blob/b1ca3d1cdff412c5ae12113c3681f789becebabc/components/devtools/protocol.rs#L17)):*
surprised there wasn't a regular rustc unused lifetime error here

---

*[components/plugins/Cargo.toml, line 15 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9123#-K73JKWbLWd9KZ1KkYoZ:-K73JKWbLWd9KZ1KkYo_:1915279426) ([raw file](https://github.com/servo/servo/blob/db876e9ed93f4618c912551af67ad5f81c8268bd/components/plugins/Cargo.toml#L15)):*
Let it point to the original one, we'll be updating the branch soon

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9123)*

**Comment by karyon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/plugins/Cargo.toml, line 15 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9123#-K73JKWbLWd9KZ1KkYoZ:-K73QXf2WlZskb5zKCcI:-602269577) ([raw file](https://github.com/servo/servo/blob/db876e9ed93f4618c912551af67ad5f81c8268bd/components/plugins/Cargo.toml#L15)):*
yeah, that actually wasn't meant to go into the PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9123)*

**Comment by Manishearth** [comment]
@bors-servo r+

Thanks!

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9123#-:-K73fSIKh2I9JIiUaGoZ:-1544677996)*

**Pull request merged**
