### PR TITLE
layout_2020: Add animations and transitions support

### LINKED ISSUE #25884: Transitions and animations
I don’t know off hand the state of this in Layout 2020, but it’s worth looking at. Might be mostly about copying/porting more of `components/layout_thread` to `components/layout_thread_2020`

### PR DESCRIPTION
**Pull request by mrobinson**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #25884
- [x] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
This change should be ready to land after #26464 and #26477.

**Comment by Manishearth** [comment]
I can review if you want, but i'm assuming you just forgot to ask nox or simon here.

**Comment by mrobinson** [comment]
Thanks for the offer, @Manishearth. I was thinking I'd post this in case anyone wanted to try it out or had any comments, but then ask for a review when the dependencies landed.

**Comment by jdm** [comment]
I'm a fan of how small 2af288a99c8141b00c55a3eeca9d27be31540e2f is.

**Comment by mrobinson** [comment]
Okay. I think this is ready to review.

**Review by jdm — APPROVED** [review]

**Comment by mrobinson** [comment]
@bors-servo retry
 * #25838

**Pull request merged**
