### PR TITLE
Android: com.mozilla to org.mozilla

### PR DESCRIPTION
**Pull request by paulrouget**
We want to be compatible with the GeckoView namespace: https://maven.mozilla.org/maven2?prefix=maven2/org/mozilla/

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21830)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’ve only skimmed the diff but it seems straightforward enough.

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #21795

**Comment by jdm** [comment]
@bors-servo retry
* #21795

**Comment by jdm** [comment]
@SimonSapin Is the new android task operating correctly? I'm not sure how to interpret that log.

**Comment by SimonSapin** [comment]
The task’s script is executed with `bash -e`, so if any command fail the script will stop there and fail. So `bootstrap-android-and-accept-licences.sh` likely exited with a non-zero status code, but I don’t know why it didn’t produce any output…

**Comment by paulrouget** [comment]
Rebased.

@bors-servo r=SimonSapin

**Comment by CYBAI** [comment]
@bors-servo retry

```
{"status": "FAIL", "group": "default", "message": "assert_array_equals: Pages opened during history navigation property 2, expected 2 but got 3", "stack": "start_test_wait</check_result<@http://web-platform.test:8000/html/browsers/history/the-history-interface/traverse_the_history_write_after_load_1.html:19:11\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1561:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1585:20\n", "subtest": "Traverse the history after document.write after the load event", "test": "/html/browsers/history/the-history-interface/traverse_the_history_write_after_load_1.html", "line": 15892, "action": "test_result", "expected": "TIMEOUT"}
{"status": "OK", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/html/browsers/history/the-history-interface/traverse_the_history_write_after_load_1.html", "line": 15893, "action": "test_result", "expected": "TIMEOUT"}
```

**Pull request merged**
