### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22143)

### CODE REVIEW

**Comment by CYBAI** [comment]
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "background_specified_color_size", "test": "/css/css-backgrounds/background-333.html", "line": 116777, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "background_initial_size", "test": "/css/css-backgrounds/background-331.html", "line": 134036, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "background-size_initial", "test": "/css/css-backgrounds/background-size-001.html", "line": 141829, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "background-size_auto", "test": "/css/css-backgrounds/background-size-001.html", "line": 141830, "action": "test_result", "expected": "FAIL"}
{"status": "FAIL", "group": "default", "message": "assert_equals: background-size supporting value expected \"auto auto\" but got \"auto\"", "stack": "@http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:83:13\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1568:20\ntest@http://web-platform.test:8000/resources/testharness.js:544:21\n@http://web-platform.test:8000/css/css-backgrounds/background-size-001.html:82:9\n", "subtest": "background-size_auto_auto", "test": "/css/css-backgrounds/background-size-001.html", "line": 141840, "action": "test_result", "expected": "PASS"}
```

**Comment by emilio** [comment]
@bors-servo r+ p=1

 * Don't want to get too out of sync.

**Comment by jdm** [comment]
@bors-servo retry
* #22135

**Comment by jdm** [comment]
@bors-servo retry
* #22135

**Pull request merged**
