### PR TITLE
Fixed issue #11651 (Do not fire a blur event when calling .focus() on…

### LINKED ISSUE #11651: Do not fire a blur event when calling .focus() on a focused element
```html
<input></input>
<script>
  var input = document.querySelector("input");
  input.addEventListener("blur", e => console.log("blur"));
  input.addEventListener("focus", e => console.log("focus"));
  setTimeout(() => input.focus(), 1000);
  setTimeout(() => input.focus(), 2000);
</script>
```

Output:

```
focus
blur
focus
```

### PR DESCRIPTION
**Pull request by davideGiovannini**
Added check in `HTMLElement.Focus` to avoid requesting focus when the element already has it.
Added check in `Document.commit_focus_transaction` to avoid sending `blur` and `focus` events when clicking on an already focused element.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11651

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11665)

### CODE REVIEW

**Comment by KiChjang** [comment]
This PR could use a test.

**Comment by davideGiovannini** [comment]
I would like to write one, but I need some hints.

**Comment by KiChjang** [comment]
@paulrouget already has a test case listed in #11651. You'll need to use `./mach create-wpt path/to/test/file` to create tests. Refer to https://github.com/servo/servo/blob/master/tests/wpt/README.md for more information.

**Comment by paulrouget** [comment]
@davideGiovannini let me know if you need help to write the test.

**Comment by jdm** [comment]
I haven't started reviewing the changes yet, just making note of my own investigations:
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4259 shows
```
log: focusing
log: focus
log: focused
log: double focused
```
in FF, Safari, and Chrome.

**Comment by paulrouget** [comment]
> http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4259 shows: […]

With this PR, we get the same output.

I used this:

```html
<!DOCTYPE html>
<input>
<script>
  var w = a => console.log(a);
  var e = document.querySelector('input');
  e.addEventListener("focus", function() { w('focus') });
  e.addEventListener("blur", function() { w('blur') });
  w('focusing');
  e.focus();
  w('focused');
  e.focus();
  w('double focused');
</script>
```

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, paulrouget (Paul Rouget) wrote…</i></summary>
> > http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4259 shows: […]
> 
> 
> 
> With this PR, we get the same output.
> 
> 
> 
> I used this:
> 
> 
> 
> ```html
> 
> <!DOCTYPE html>
> 
> <input>
> 
> <script>
> 
>   var w = a => console.log(a);
> 
>   var e = document.querySelector('input');
> 
>   e.addEventListener("focus", function() { w('focus') });
> 
>   e.addEventListener("blur", function() { w('blur') });
> 
>   w('focusing');
> 
>   e.focus();
> 
>   w('focused');
> 
>   e.focus();
> 
>   w('double focused');
> 
> </script>
> 
> ```
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/document.rs, line 601 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11665#-KJpJtYks8j0mY3DTNco:-KJpJtYlu8aj6BHtwS4t:-1526219747) ([raw file](https://github.com/servo/servo/blob/35aa24eb4c4bbb9ee8b6e7bd2c083d4584321f07/components/script/dom/document.rs#L601)):*
> ```Rust
>     /// transaction, or none if no elements requested it.
>     pub fn commit_focus_transaction(&self, focus_type: FocusType) {
>         if self.focused != self.possibly_focused.get().r() {
> ```

Let's invert this conditional and return, to avoid the extra indentation for everything else in the method.

---

*[components/script/dom/htmlelement.rs, line 254 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11665#-KJpKpCapMbRUlxusdSJ:-KJpKpCbqSaQhCT986gU:-580707594) ([raw file](https://github.com/servo/servo/blob/35aa24eb4c4bbb9ee8b6e7bd2c083d4584321f07/components/script/dom/htmlelement.rs#L254)):*
> ```Rust
>         // TODO: Mark the element as locked for focus and run the focusing steps.
>         // https://html.spec.whatwg.org/multipage/#focusing-steps
>         if self.upcast::<Element>().focus_state() {
> ```

I don't think this change is still necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11665#-:-KJpKubkU04wmAe_51-_:1458266033)*

**Comment by davideGiovannini** [comment]
@paulroget Yes please, I'm not familiar with web platform tests and I'm not finding the [documentation](http://testthewebforward.org/docs/testharness-library.html) too helpful

**Comment by paulrouget** [comment]
@davideGiovannini maybe this will help: https://github.com/servo/servo/blob/master/docs/HACKING_QUICKSTART.md#add-a-new-test

Maybe you should create a test called `tests/wpt/mozilla/tests/mozilla/double_focus.html`. You might want to look in this directory to see how tests are written. You don't need an async test for this I believe.

**Comment by KiChjang** [comment]
@davideGiovannini Any progress on adding tests?

**Comment by paulrouget** [comment]
If this lands, I can write the tests in a follow-up issue right away.

**Comment by davideGiovannini** [comment]
Sorry for the delay.
 I tried to write the test, but I encountered some problems and unfortunately I don't think I can resume working on it untill the end of this exam session (mid July).

**Comment by KiChjang** [comment]
I'm going to land this and track the progress of writing a test in #11854.

@bors-servo r+

**Comment by KiChjang** [comment]
@bors-servo retry
* #InfraOnFire

**Comment by KiChjang** [comment]
@bors-servo retry
* #11703

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11693

**Pull request merged**
