### PR TITLE
Update gstreamer on Windows to 1.16.0.

### LINKED ISSUE #23348: libiconv-2.dll is missing from Windows nightly

### PR DESCRIPTION
**Pull request by jdm**
Fixes #23348.

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23484)

### CODE REVIEW

**Comment by jdm** [comment]
I'm hoping this will fix #23348.

**Comment by jdm** [comment]
The build ran on my Windows machine. Let's get this merged!

**Review by ferjm — APPROVED** [review]
r=me as soon as AppVeyor finishes

**Comment by jdm** [comment]
Huh, the appveyor failure here is the exact same failure that occurred when running unit tests on win64. That looks very suspicious.
```
     Running target\debug\deps\main-ef895344ee0b5013.exe
error: test failed, to rerun pass '-p net --test main'
[taskcluster 2019-05-31T18:07:46.212Z]    Exit Code: 3221225781
```

**Comment by jdm** [comment]
I successfully ran `mach test-unit -p net` with a local windows build with gstreamer 1.16.0 installed :(

**Comment by jdm** [comment]
Huh, why would this affect appveyor? I haven't made any changes to its configuration :<

**Comment by jdm** [comment]
I suppose the post-build packaging change could have affected the result somehow...

**Comment by jdm** [comment]
Yep, I broke the DLL copying. I've added a couple assertions to avoid that happening again.

**Comment by jdm** [comment]
Windows CI was green: https://treeherder.allizom.org/#/jobs?repo=servo-try&revision=64fa23fde90bd81507326c8b3124f676cdfc3315

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
