### PR TITLE
Replace use of `debug!` by `warn!` in `constellation.rs`

### LINKED ISSUE #10483: Replace use of debug! by warn! in constellation
The uses of `debug!` are gone in release builds, they should be replaced by `warn!`.

### PR DESCRIPTION
**Pull request by timvandermeij**
Fixes #10483.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10489)

### CODE REVIEW

**Comment by emilio** [comment]
Hum... Probably we don't want to replace all those, there are some of them which are just debug info, like the "constellation got xxx message" ones.

In case we want those in release mode by default (I'm not totally sure about that), at least they should be changed to `info!()` instead of `warn!()`.

Thoughts, @jdm and @asajeffrey? (or anyone else, just mentioning them because they were participating in the corresponding issue).

**Comment by timvandermeij** [comment]
Good point! I was thinking about that myself for a while too, but I didn't know `info!()` existed for debugging messages. I can certainly update the patch to use `info!()` for debugging messages and `warn!()` for actual warnings (indicating failure or other unexpected results), but before I do I'd like to know if you would still like to keep those debugging messages around in the code if they are not suitable for release builds. If not, we can either remove them or somehow only show them in debug builds, which I'm not sure how to achieve actually. I'll change it to whatever you think is best!

**Comment by emilio** [comment]
To only compile them in debug builds you should keep them using `debug!()` (you need to use `RUST_LOG=debug` to see them though, since it can be quite verbose).

Anyways, appart from that this looks great! Thanks! :)

Let's wait for more servo people to hear their opinions :P

**Comment by jdm** [comment]
I don't think we need to think about debug vs. info at this point. Let's just go ahead and revert the changes to messages that aren't actually conditions that should be treated as warnings.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/compositing/constellation.rs, line 573 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10489#-KF61QmQE5vdeaYAgUSI:-KF61QmRYlobRQGqFibw:-1404326478) ([raw file](https://github.com/servo/servo/blob/def159487082b81fe8351f290010922d1d25755d/components/compositing/constellation.rs#L573)):*
Sorry, most of the messages in this function should stay as `debug!`, since they're perfectly normal program execution conditions. Generally, if the message mentions an error condition or a dead/closed pipeline, it should be a warning. If not, debug is fine.

---

*[components/compositing/constellation.rs, line 1106 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10489#-KF626o9LnD4sJWVRZhL:-KF626oA1yiU1FcWFTM-:1472267957) ([raw file](https://github.com/servo/servo/blob/def159487082b81fe8351f290010922d1d25755d/components/compositing/constellation.rs#L1106)):*
This can stay debug.

---

*[components/compositing/constellation.rs, line 1122 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10489#-KF62D3Ew-nS5tBUgZ86:-KF62D3Ew-nS5tBUgZ87:1472267957) ([raw file](https://github.com/servo/servo/blob/def159487082b81fe8351f290010922d1d25755d/components/compositing/constellation.rs#L1122)):*
This can stay debug.

---

*[components/compositing/constellation.rs, line 1478 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10489#-KF63m0qD42yI6YRTxCW:-KF63m0r2_ACSDLoR0Ql:385351243) ([raw file](https://github.com/servo/servo/blob/def159487082b81fe8351f290010922d1d25755d/components/compositing/constellation.rs#L1478)):*
This can be debug.

---

*[components/compositing/constellation.rs, line 1528 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10489#-KF63nDVPfuTS7VyEXGJ:-KF63nDVPfuTS7VyEXGK:1696767392) ([raw file](https://github.com/servo/servo/blob/def159487082b81fe8351f290010922d1d25755d/components/compositing/constellation.rs#L1528)):*
Debug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10489#-:-KF63xt8gcWII1iKFrP_:1857741307)*

**Comment by asajeffrey** [comment]
No huge surprise here, I agree with @jdm, it's just the unexpected cases that should be `warn!`, most messages should stay `debug!`. Sorry about that, I should have been clearer in #10483.

**Comment by timvandermeij** [comment]
I went over all `debug!` uses again and only changed the ones to `warn` that mentioned an error condition or a dead/closed pipeline. Could you check again if all is fine now and if nothing else should be `debug!` anymore?

**Comment by jdm** [comment]
Looks good! Just that one remaining one that you pointed out.
-S-needs-rebase -S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/compositing/constellation.rs, line 657 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10489#-KFEfr3BgVEtRYOzMjk9:-KFEfr3BgVEtRYOzMjkA:-2044947972) ([raw file](https://github.com/servo/servo/blob/1990c61ff4fe2ae1ec6f70d04264365112397993/components/compositing/constellation.rs#L657)):*
This can be debug! too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10489#-:-KFEftMkT8sJhLno_uDa:1020725410)*

**Comment by timvandermeij** [comment]
Done. I also changed https://github.com/servo/servo/blob/master/components/compositing/constellation.rs#L790 and https://github.com/servo/servo/blob/master/components/compositing/constellation.rs#L807 back to `debug!` as those lines are equal to the line mentioned above. Let me know if there is anything else that needs updating.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10489#-:-KFFxf38zB9TreqMPt-w:-1746383326)*

**Pull request merged**
