### PR TITLE
Update CSS tests to revision 0dacccb0ef2fa3ed9446c3c108bde0b0ad5ce7c8

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9369)

### CODE REVIEW

**Comment by nox** [comment]
The manifest is wrong.

**Comment by Ms2ger** [comment]
I have no clue what's wrong; running `--manifest-update` locally does not cause the changes Travis shows. Maybe a mismatch between different copies of the manifest-generating code? @jgraham ?

**Comment by nox** [comment]
I can reproduce it locally.

**Pull request closed without merging**
