### PR TITLE
Refactor resource thread code

### PR DESCRIPTION
**Pull request by izgzhen**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it is refactoring

Related to #11131

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11189)

### CODE REVIEW

**Comment by izgzhen** [comment]
Discussed on IRC with @Manishearth [here](http://logs.glob.uno/?c=mozilla%23servo&s=15+May+2016&e=15+May+2016), thinking that this will improve the maintainability of code.

**Comment by Wafflespeanut** [comment]
If we're going to rename `ControlMsg` to `ResourceMsg`, then we should also update the unit tests for `net`.

**Comment by izgzhen** [comment]
@Wafflespeanut By `./mach test-unit`? I will take a look, thanks!

**Comment by nox** [comment]
Could you add a summary of your changes in your commit message?

**Comment by izgzhen** [comment]
@nox ok

**Comment by nox** [comment]
This adds an intermediate step to request things to the storage thread. AFAICT @Manishearth was suggesting to put all three channels in the same structure and implement a `send` method on it that would dispatch messages to the right thread, not putting storage and filemanager behind the resource thread.

**Comment by izgzhen** [comment]
@nox, thanks for feedback, I remember @Manishearth suggested that but I am not sure whether this design will be changed later on so I put it off. Using `send` looks like a great idea.

**Comment by KiChjang** [comment]
This fails at building unit tests:
```
/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:6:5: 6:46 error: unresolved import `net::resource_thread::new_resource_thread`. There is no `new_resource_thread` in `net::resource_thread`. Did you mean to use `new_resource_threads`? [E0432]

/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:6 use net::resource_thread::new_resource_thread;

                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/travis/build/servo/servo/tests/unit/net/resource_thread.rs:6:5: 6:46 help: run `rustc --explain E0432` to see a detailed explanation

error: aborting due to previous error
```

**Comment by izgzhen** [comment]
@KiChjang Fixed, thank you

**Comment by nox** [comment]
I have a few questions, but otherwise the code looks good.

-S-awaiting-review +S-needs-code-changes +S-awaiting-answer 

<details><summary><i>Previously, izgzhen (Zhen Zhang) wrote…</i></summary>
> @KiChjang Fixed, thank you</details>


---

Reviewed 14 of 14 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 12 of 12 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[components/compositing/constellation.rs, line 850 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyQTlWcFOLNwIxQAoq:-KHyQTlWcFOLNwIxQAor:-1743682080) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/compositing/constellation.rs#L850)):*
> ```Rust
>             }
>         }
>         if let Err(e) = self.resource_threads.storage_thread.send(StorageThreadMsg::Exit) {
> ```

My idea was to do that:

```rust
if let Err(e) = self.resource_manager.send(ResourceMsg::StorageThread(StorageMsg::Exit)) {
    ...
}
```

What do you think of this?

Cc @Ms2ger @Manishearth 

---

*[components/net_traits/lib.rs, line 189 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHxt86x0c2dBJUF4wTA:-KHxt86x0c2dBJUF4wTB:1616090978) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L189)):*
> ```Rust
> 
> #[derive(Clone, Serialize, Deserialize)]
> pub struct ResourceThreads {
> ```

This should be documented, and I think it should rather be named `ResourceManager`.

---

*[components/net_traits/lib.rs, line 191 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPLRNQ6mrI6_IV4k5:-KHyPLRNQ6mrI6_IV4k6:-2127051608) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L191)):*
> ```Rust
> pub struct ResourceThreads {
>     /// Handle to a resource thread
>     /// FIXME: Arc<ResourceThread>
> ```

What is this FIXME about?

---

*[components/net_traits/lib.rs, line 197 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPWtyQsywXBEHZ6Sc:-KHyPWtzR5HajfbXgYhK:1485966192) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L197)):*
> ```Rust
>     /// A channel through which messages can be sent to the storage thread.
>     pub storage_thread: StorageThread,
> }
> ```

Could we make the fields private?

---

*[components/script/dom/window.rs, line 214 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPaCvTKEgrD8tWK6J:-KHyPaCvTKEgrD8tWK6K:33302288) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/script/dom/window.rs#L214)):*
> ```Rust
>     /// Associated resource threads for use by DOM objects like XMLHttpRequest,
>     /// including resource_thread, filemanager_thread and storage_thread
>     #[ignore_heap_size_of = "channels are hard"]
> ```

Remove this, derive `HeapSizeOf` on `ResourceManager` and ignore the channel fields.

---

*[components/script/dom/window.rs, line 345 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPhxjWBJCztXb4JHd:-KHyPhxjWBJCztXb4JHe:1123197194) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/script/dom/window.rs#L345)):*
> ```Rust
>     pub fn storage_thread(&self) -> StorageThread {
>         self.resource_threads.storage_thread.clone()
>     }
> ```

Do we really need to expose these?

---

*[components/script/dom/window.rs, line 1571 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPo7Muq5X2Ep085jM:-KHyPo7Muq5X2Ep085jN:1148138918) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/script/dom/window.rs#L1571)):*
> ```Rust
> impl JSTraceable for ResourceThreads {
>     fn trace(&self, _: *mut JSTracer) { }
> }
> ```

BTW, there is a macro `no_jsmanaged_fields` or something like that that you could use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189#-:-KHyR0bszGJTOnOpvCob:-1270901862)*

**Comment by izgzhen** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/compositing/constellation.rs, line 850 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyQTlWcFOLNwIxQAoq:-KHyz2AqT07DtfiHUN9o:-1518514229) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/compositing/constellation.rs#L850)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> My idea was to do that:
> 
> ```rust
> if let Err(e) = self.resource_manager.send(ResourceMsg::StorageThread(StorageMsg::Exit)) {
>     ...
> }
> ```
> 
> What do you think of this?
> 
> Cc @Ms2ger @Manishearth </details>
I image that this requires us to add another field `StorageThread` to `ResourceMsg` and the `resource_manager.send` will somehow *intercept* and dispatch, which means that some fields might make no sense to inner `resource_thread`. Also, this way makes `resource_manager` looks like an `IpcSender` while it is not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/net_traits/lib.rs, line 189 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHxt86x0c2dBJUF4wTA:-KHz-67elpP7OBjgXnx0:204092199) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L189)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> This should be documented, and I think it should rather be named `ResourceManager`.</details>
However `ResourceManager` is already take by `net::resource_thread::ResourceManager`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/compositing/constellation.rs, line 850 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyQTlWcFOLNwIxQAoq:-KHz-MlktIithwa2DTi5:1377425758) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/compositing/constellation.rs#L850)):*
<details><summary><i>Previously, izgzhen (Zhen Zhang) wrote…</i></summary>
> I image that this requires us to add another field `StorageThread` to `ResourceMsg` and the `resource_manager.send` will somehow *intercept* and dispatch, which means that some fields might make no sense to inner `resource_thread`. Also, this way makes `resource_manager` looks like an `IpcSender` while it is not.</details>
It makes `resource_manager` a proper abstraction over resources of any kind, encapsulating everything that is needed behind private fields. Sounds like an improvement to me.

---

*[components/net_traits/lib.rs, line 189 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHxt86x0c2dBJUF4wTA:-KHz-Z3EpuNGyFuBVsWc:-1722778439) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L189)):*
<details><summary><i>Previously, izgzhen (Zhen Zhang) wrote…</i></summary>
> However `ResourceManager` is already take by `net::resource_thread::ResourceManager`</details>
Ah bummer. :/ @jdm Any idea of a name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/net_traits/lib.rs, line 191 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPLRNQ6mrI6_IV4k5:-KHz-SqxOiAhFG3e8iFB:325068737) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L191)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> What is this FIXME about?</details>
This is about the original change of `resource_thread` field from non-`Arc`d to `Arc`d in `script_thread`. I will elaborate it further in the comment. Thank you

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/net_traits/lib.rs, line 197 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPWtyQsywXBEHZ6Sc:-KHz-vXhleoAgGSo0zjl:-545187859) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L197)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Could we make the fields private?</details>
Ok, I think I need to unify the style of field access now :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/window.rs, line 345 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPhxjWBJCztXb4JHd:-KHz0IRlfdLKirtuv2Wv:-245636032) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/script/dom/window.rs#L345)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Do we really need to expose these?</details>
The old code exposes that so I followed it. I will see if it is really necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/window.rs, line 1571 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPo7Muq5X2Ep085jM:-KHz0XWEC2VUXkunWbBf:314542701) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/script/dom/window.rs#L1571)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> BTW, there is a macro `no_jsmanaged_fields` or something like that that you could use.</details>
Really?! I thought @Manishearth was just stating a hint on IRC rather than telling me a real macro haha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[components/compositing/constellation.rs, line 850 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyQTlWcFOLNwIxQAoq:-KHz14kS4nIk_HCXXM0S:889093874) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/compositing/constellation.rs#L850)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> It makes `resource_manager` a proper abstraction over resources of any kind, encapsulating everything that is needed behind private fields. Sounds like an improvement to me.</details>
I agree with you on using a messaging passing style here, but then we should create another type overtaking current so-called `ResourceMsg` (Ahh naming issue again), do I understand correctly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[components/net_traits/lib.rs, line 189 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHxt86x0c2dBJUF4wTA:-KHz2cxyZ8A44sGMx3vv:-2004513729) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L189)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Ah bummer. :/ @jdm Any idea of a name?</details>
Let me list whatever words come to my mind: IO, Model, Backend, System ... but I think currently we can just make minimal change to the original naming to avoid confusion in this PR, then open another PR tidying up the `net`/`net_traits` part together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[components/net_traits/lib.rs, line 189 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHxt86x0c2dBJUF4wTA:-KHz3pkgF3L8dWD8WhAj:897144972) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L189)):*
<details><summary><i>Previously, izgzhen (Zhen Zhang) wrote…</i></summary>
> Let me list whatever words come to my mind: IO, Model, Backend, System ... but I think currently we can just make minimal change to the original naming to avoid confusion in this PR, then open another PR tidying up the `net`/`net_traits` part together.</details>
Maybe I can peek at Gecko a bit and steal some words

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
@nox See https://github.com/izgzhen/servo/tree/refactor-resource-thread-v2 for some experimental hacks over the mentioned problems

**Comment by izgzhen** [comment]
Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/compositing/constellation.rs, line 850 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyQTlWcFOLNwIxQAoq:-KI0NYlfRCbIOdPEnHeR:-1032150081) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/compositing/constellation.rs#L850)):*
<details><summary><i>Previously, izgzhen (Zhen Zhang) wrote…</i></summary>
> I agree with you on using a messaging passing style here, but then we should create another type overtaking current so-called `ResourceMsg` (Ahh naming issue again), do I understand correctly?
</details>
In the new design I used a trait `IpcSend` and we can simply `send` any implemented stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/window.rs, line 1571 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPo7Muq5X2Ep085jM:-KI0OJ5Vy1WzG6DwAWsZ:1877925111) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/script/dom/window.rs#L1571)):*
<details><summary><i>Previously, izgzhen (Zhen Zhang) wrote…</i></summary>
> Really?! I thought @Manishearth was just stating a hint on IRC rather than telling me a real macro haha
</details>
Using macro is not really a clean work here. I tried to put macro in `net_traits/lib.rs` where the struct is defined, but it is shown to be "unused"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by izgzhen** [comment]
Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/net_traits/lib.rs, line 189 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHxt86x0c2dBJUF4wTA:-KI0Od7voChdtPM4Icnq:1231991560) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/net_traits/lib.rs#L189)):*
<details><summary><i>Previously, izgzhen (Zhen Zhang) wrote…</i></summary>
> Maybe I can peek at Gecko a bit and steal some words
</details>
Now it is `CoreResource`. If it is not good enough is should be relatively easy to change in future since 'core_" can help us identify it :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by Manishearth** [comment]
Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/window.rs, line 1571 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11189#-KHyPo7Muq5X2Ep085jM:-KI0P2I5PD29u50knWWp:-522293104) ([raw file](https://github.com/servo/servo/blob/a3efc65e7ed60a9b2a9bd2c7fa060a35c1adb3c3/components/script/dom/window.rs#L1571)):*
<details><summary><i>Previously, izgzhen (Zhen Zhang) wrote…</i></summary>
> Using macro is not really a clean work here. I tried to put macro in `net_traits/lib.rs` where the struct is defined, but it is shown to be "unused"
</details>
Yeah, you're supposed to use the no_jsmanaged_fields macro. Don't manually implement Trace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189)*

**Comment by nox** [comment]
Rebase and r=me.

-S-awaiting-answer -S-awaiting-review 

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :umbrella: The latest upstream changes (presumably #11265) made this pull request unmergeable. Please resolve the merge conflicts.
</details>


---

Reviewed 16 of 16 files at r6, 20 of 20 files at r7, 1 of 1 files at r8, 20 of 20 files at r9, 21 of 21 files at r10, 13 of 13 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11189#-:-KI8VYGPjJZ4ipYLnpoU:689887889)*

**Comment by nox** [comment]
@bors-servo r-

Homu confused, will r+ again.

**Pull request merged**
