### PR TITLE
Store a pointer to the browsing context in the Document.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9603)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9603#-:-KApHtSAZNpfjv-I77aI:-317921516)*

**Comment by KiChjang** [comment]
@bors-servo retry
* #7791

**Comment by KiChjang** [comment]
@bors-servo retry
* #7791

**Comment by KiChjang** [comment]
@bors-servo rertry
* Git problem

**Comment by KiChjang** [comment]
@bors-servo retry
* Git problem

**Pull request merged**
