### PR TITLE
style: Prevent reframing in Gecko when we don't find a pseudo-element's style context more often.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16207)

### CODE REVIEW

**Comment by emilio** [comment]
cc @bzbarsky

**Comment by bholley** [comment]
Per [1] I'd like to put this on hold for a few days while I try [2]. If it works, we'll have a more general solution here, otherwise we can land this.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1352487#c3
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1352565

**Comment by emilio** [comment]
Superseded by #16967

**Pull request closed without merging**
