### PR TITLE
script: Fix integer-JSID handling in named getters.

### LINKED ISSUE #10686: CGDOMJSProxyHandler_defineProperty handles non-string jsids incorrectly
I'm working on it.

### PR DESCRIPTION
**Pull request by emilio**
On top of #18539, fixes #10686.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18543)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo try

 * Just rebased

**Comment by KiChjang** [comment]
Uh oh, looks like this fixes #18468 as well.

**Comment by emilio** [comment]
Added another commit to properly implement https://heycam.github.io/webidl/#LegacyPlatformObjectGetOwnProperty.

@bors-servo try

r? @nox or @jdm

**Comment by emilio** [comment]
@bors-servo try

 * Horray for more passing tests :)

**Pull request merged**
