### PR TITLE
Improve HTMLMediaElement

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18582)

### CODE REVIEW

**Comment by nox** [comment]
I 100% don't understand the failures.

**Comment by nox** [comment]
Ping @jdm

**Comment by KiChjang** [comment]
Just did a quick review, your 2nd commit's title looks off, AFAICT it's basically ensuring that all tasks should have the same `generation_id` when it was first queued, correct? How does that have anything to do with "ignoring media-related tasks"?

**Comment by nox** [comment]
Because `generation_id` exists to be able to cancel all media-related tasks when running the few first steps of the media load algorithm.

**Review by emilio — APPROVED** [review]

**Pull request merged**
