### PR TITLE
Implement TimeRanges interface

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

Spec: https://html.spec.whatwg.org/multipage/media.html#time-ranges

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22049)

### CODE REVIEW

**Comment by ferjm** [comment]
I think Manish is afk today.

r? @jdm

**Review by jdm — CHANGES_REQUESTED** [review]

**Comment by ferjm** [comment]
Feedback addressed. Thanks!

**Review by jdm — APPROVED** [review]

**Comment by ferjm** [comment]
@bors-servo retry
- #22063

**Comment by jdm** [comment]
@bors-servo retry
* https://github.com/servo/intermittent-failure-tracker/issues/5

**Pull request merged**
