### PR TITLE
style: Sync changes from mozilla central.

### PR DESCRIPTION
**Pull request by emilio**
See individual commits for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23194)

### CODE REVIEW

**Comment by CYBAI** [comment]
Failure in `Travis` and `AppVeyor`:

```rust
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
  --> tests/unit/style/properties/serialization.rs:83:33
   |
83 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:108:33
    |
108 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:133:33
    |
133 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:165:33
    |
165 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:180:33
    |
180 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:190:33
    |
190 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:223:33
    |
223 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:246:33
    |
246 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:275:33
    |
275 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:293:33
    |
293 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:307:33
    |
307 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:317:33
    |
317 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), block_text).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> tests/unit/style/properties/serialization.rs:348:33
    |
348 |                 parse(|c, i| Ok(parse_property_declaration_list(c, i)), shadow_css).unwrap();
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
error: aborting due to 13 previous errors
For more information about this error, try `rustc --explain E0061`.
error: Could not compile `style_tests`.
warning: build failed, waiting for other jobs to finish...
error: build failed
The command "./mach test-unit" exited with 101.
```

Errors in Taskcluster

```rust
error[E0432]: unresolved import `style::values::computed::font::FamilyNameSyntax`
  --> components/gfx/tests/font_context.rs:23:17
   |
23 |     FamilyName, FamilyNameSyntax, FontFamily, FontFamilyList, FontSize,
   |                 ^^^^^^^^^^^^^^^^
   |                 |
   |                 no `FamilyNameSyntax` in `values::computed::font`
   |                 help: a similar name exists in the module: `FontFamilyNameSyntax`

warning: ignoring -C extra-filename flag due to -o flag

error: aborting due to previous error
```

**Comment by emilio** [comment]
@bors-servo r+

 * Fixed style and gfx unit tests.

**Comment by jdm** [comment]
Needs another fmt.

**Comment by emilio** [comment]
@bors-servo r+

Thanks Josh :)

**Comment by jdm** [comment]
@bors-servo retry
Sorry, there was a runaway bluetooth daemon on that mac builder.

**Pull request merged**
