### PR TITLE
Update Rust to 1.15.0-nightly (71c06a56a 2016-12-18)

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14633)

### CODE REVIEW

**Comment by SimonSapin** [comment]
So, that’s two runs with identical failures:

```json
{"status": "FAIL", "stack": null, "subtest": null, "action": "test_result", "test": "/_mozilla/css/border_radius_asymmetric_sizes_a.html", "line": 13216, "message": "/_mozilla/css/border_radius_asymmetric_sizes_a.html 327908e8e5639151bbfceb0c4a78876203042ed1\n/_mozilla/css/border_radius_asymmetric_sizes_ref.html 5a9a64f75ad410d2c74e45ceda1c9efa61203c14\nTesting 327908e8e5639151bbfceb0c4a78876203042ed1 == 5a9a64f75ad410d2c74e45ceda1c9efa61203c14", "expected": "PASS"}
{"status": "PASS", "stack": null, "subtest": null, "action": "test_result", "test": "/_mozilla/css/text_decoration_underline_subpx_a.html", "line": 16535, "message": null, "expected": "FAIL"}
{"status": "FAIL", "stack": null, "subtest": null, "action": "test_result", "test": "/_mozilla/css/word-break-keep-all-005.htm", "line": 30050, "message": "/_mozilla/css/word-break-keep-all-005.htm 553453fad4db496e2aab49f65a8af2ec63909388\n/_mozilla/css/word-break-keep-all-ref-005.htm ec3b8afcf107bfa4cd93ad6b32c9238dfec0356d\nTesting 553453fad4db496e2aab49f65a8af2ec63909388 == ec3b8afcf107bfa4cd93ad6b32c9238dfec0356d", "expected": "PASS"}
```

**Comment by SimonSapin** [comment]
I can reproduce `text_decoration_underline_subpx_a.html` PASS expected FAIL, both on this branch **and on master**. The failure is marked expected on Linux only. I don’t know what happened exactly, but maybe we can just remove it?

I can reliably reproduce the `border_radius_asymmetric_sizes_a.html` failure (on this branch but not on master), but not the `word-break-keep-all-005.htm` one…

Let’s try it once more to see what happens.

@bors-servo try

**Comment by SimonSapin** [comment]
The `border_radius_asymmetric_sizes_a.html` failure is one pixel at rgb(55,155,55) instead of rgb(54,155,54) in a rounded corner. @jgraham Do we support fuzzy reftests in Servo? (Where up to N pixels are allowed to differ by up to some RGB distance.)

**Comment by stshine** [comment]
Looks like some algorithm change inside rustc(Mabye floating point) results one-pixel shifts. This should most possible affects gfx and/or webrender.

**Comment by SimonSapin** [comment]
`border_radius_asymmetric_sizes_a.html` reliably passes for me with rustc 8f02c429a 2016-12-15 and fails with 71c06a56a 2016-12-18, with no code difference in the Servo repo other than `rust-nightly-date`.

https://github.com/rust-lang/rust/compare/8f02c429a...71c06a56a

**Comment by jdm** [comment]
My money's on https://github.com/rust-lang/rust/pull/37429.

**Comment by stshine** [comment]
IMO merge this pull request with test expectations updated should be OK.

**Comment by SimonSapin** [comment]
Screenshots bellow are of `border_radius_asymmetric_sizes_ref.html`, scrolled to the bottom because things are move visible there. Each squareish thing is a single element with borders of different colors on each four sides.

The rendering of these borders in Servo is messed up, but that could be an unrelated WebRender bug. What’s more worrying to me right now is that **the text became bold** just by upgrading the compiler.

Could it be that `#[repr(C)]` is missing on some type used with Freetype or Fontconfig? (Since https://github.com/rust-lang/rust/pull/37429 "struct field reordering" is among the compiler changes.)

----

On Servo master, or this PR downgraded to rustc 8f02c429a 2016-12-15 (they give identical rendering):

nightly-2016-11-28

In this PR (rustc 8f02c429a 2016-12-15):

nightly-2016-12-18

In Firefox:

firefox

**Comment by eddyb** [comment]
FWIW https://github.com/servo/rust-freetype/commit/c796066b996f0c60ff17884a10e821bd3aef08ec fixes the bold problem for me (except for me it's the lack of bold on `<h2>` as opposed to other things being bold).

**Comment by Manishearth** [comment]
@jdm @Ms2ger Doesn't https://github.com/rust-lang/rust/pull/37429 mean that our DOM inheritance thing might need some fixes? We used to rely on the fact that the first field is always the parent. I did update some code to use `&foo.firstfieldname` instead of transmuting at some point but I don't think that's all of it.

**Comment by eddyb** [comment]
@Manishearth You used `#[repr(C)]` with that, right? Riiiight? Anything else is irresponsible.

**Comment by Manishearth** [comment]
We didn't :) Like I said, I tried to get rid of the transmutes at some point, but it's changed a lot since then and I don't even remember.

**Comment by nox** [comment]
@eddyb I plan to do that today or tomorrow, but wasn't going to block rustup on it since the tests pass.

**Pull request merged**
