### PR TITLE
script: Move `style` as Element method

### LINKED ISSUE #19886: Node::style should move to Element after #19881 lands
Right now all the callers do:

```rust
self.upcast::<Node>().style();
```

And I'm glad they do because the code panics if the node is not an element.

So we should just move `Node::style` to `Element` so it can't be misused. We should also add a documentation comment saying when it may be `None` (when the element is in a display: none subtree).

### PR DESCRIPTION
**Pull request by CYBAI**
r? emilio 

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #19886 
- [x] These changes do not require tests because it should not break anything

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19889)

### CODE REVIEW

**Review by emilio — APPROVED** [review]
Looks good!

Given you're not new and have a fair amount of experience submitting patches to the project, I think it's better to leave really `E-easy`s like this for new people to get involved. Just worth having that in mind, it's not a hard rule either :)

**Comment by CYBAI** [comment]
@emilio Yes, you're right. I'll leave `E-easy` for new contributors in the future!  Thanks!

**Pull request merged**
