### PR TITLE
Fix false positive in unrooted_must_root lint.

### PR DESCRIPTION
**Pull request by eefriedman**
Encountered in #8725.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8731)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Whoops...

    ./components/plugins/lints/unrooted_must_root.rs:7: use statement is not in alphabetical order
    	expected: rustc::middle::pat_util::pat_is_binding
    	found: rustc::middle::ty

    ./components/plugins/lints/unrooted_must_root.rs:8: use statement is not in alphabetical order
    	expected: rustc::middle::ty
    	found: rustc::middle::pat_util::pat_is_binding

**Comment by Manishearth** [comment]
r+ post tidy

**Pull request merged**
