### PR TITLE
Remove unused content blocker code.

### PR DESCRIPTION
**Pull request by Ms2ger**
I don't know what it is for, so I believe it would be better to remove it
entirely until and unless we start using it.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15849)

### CODE REVIEW

**Comment by nox** [comment]
@Ms2ger It used to be used. You just made it not be used when you removed the old networking stack, AFAIK.

**Comment by nox** [comment]
Cc @jdm

**Comment by jdm** [comment]
https://github.com/servo/servo/issues/14307

**Comment by Ms2ger** [comment]
I believe that's correct, yes. However, I have no idea what it's for, it's not used *now*, it doesn't have a single word of documentation and AFAIK the standard doesn't mention it at all. Right now it's just ballast that will probably need to be rewritten in #14307 anyway.

**Comment by nox** [comment]
Ok.

@bors-servo r+

**Pull request merged**
