### PR TITLE
Update WR (new groove/ridge border path, mix-blend-mode optimizations)

### PR DESCRIPTION
**Pull request by KiChjang**
Closes #16581.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16582)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo retry
* #16583

**Comment by KiChjang** [comment]
Ok, I'm not sure what's happening anymore, and I can't paste the test results here because it's over the 65536 character limit on GH comments.

**Comment by jdm** [comment]
Have we carefully checked that #16583 did not happen on each previous attempt to merge this?

**Comment by jdm** [comment]
Turns out that #16603 outside of this PR, so we're good to keep merging.

**Comment by jdm** [comment]
All of the webgl tests failing like that is pretty suspicious.

**Comment by glennw** [comment]
The webgl failures occur locally on my Linux machine too - I'll investigate them today.

**Comment by emilio** [comment]
I bet that it's due to https://github.com/servo/webrender/pull/1153 not forcing a GL flush on release builds.

**Comment by glennw** [comment]
@emilio Thanks for the heads up - I'll test that locally now and we can revert that change for now if it causes these failures.

**Comment by glennw** [comment]
@emilio Yep - you're right - https://github.com/servo/webrender/pull/1167.

**Comment by KiChjang** [comment]
Superseded by #16612.

**Pull request closed without merging**
