### PR TITLE
Support new way of doing input source arrays

### LINKED ISSUE #24395: getInputSources API isn't spec-compliant
The WebXR spec calls for XRSession to have a [inputSources](https://immersive-web.github.io/webxr/#xrsession-interface) attribute that returns a FrozenArray. We have a `getInputSources` method that returns a sequence instead, because of https://github.com/servo/servo/issues/10072. I think the best way to deal with this is make our attribute return an `any` WebIDL value, store a cached JSVal that is a frozen JS array.

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes https://github.com/servo/servo/issues/24395

r? @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24397)

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by Manishearth** [comment]
I was doing a local run, pushed expectations

@bors-servo r=jdm

**Comment by Manishearth** [comment]
@bors-servo retry

```
{
    "status": "CRASH", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/fetch/stale-while-revalidate/fetch.html", 
    "line": 162486, 
    "action": "test_result", 
    "expected": "OK"
}

```

**Comment by Manishearth** [comment]
@bors-servo r=jdm

(iirc that's one of the tests that's flakier in debug)

**Comment by jdm** [comment]
Filed #24399 because it was a panic I had never observed before.

**Comment by Manishearth** [comment]
Yep, was holding off on filing till this landed

**Comment by Manishearth** [comment]
Oh, also, I was able to get the ballshooter example working with this (and https://github.com/servo/webxr/pull/67 ) , but it _stopped_ working later and I'm not sure why. Hitting the same BindTexture crash, but there's novisible error causing it. Need to investigate further.

**Comment by jdm** [comment]
I have a patch that makes the BindTexture crash go away by adding `context.Finish()` before returning from XRWebGLLayer::Constructor.

**Comment by Manishearth** [comment]
Sweet, I'll see what happens with that patch tomorrow.

**Pull request merged**
