### PR TITLE
Do not lock if GL thread fails

### PR DESCRIPTION
**Pull request by paulrouget**
This might help sometimes when the GL thread fails.

@jdm as I was mentioning, without this, the whole browser can end up being locked (UI being unresponsive).
With this, Servo stays irresponsive, but the app is not locked.

### CODE REVIEW

**Comment by jdm** [comment]
Ok, this is subtle enough that I'd like to spend a bit of time testing it on the device to make sure there are no surprises. Let's target it for the next release instead of the one for this week.

**Comment by paulrouget** [comment]
We can skip that PR if it's not for v1.2, as it will be part of #27438.

**Comment by paulrouget** [comment]
This happened in #27438

**Pull request closed without merging**
