### PR TITLE
Add an vector version of the Servo logo

### PR DESCRIPTION
**Pull request by Coder206**
This PR is a continuation of #18665. I wanted to make a separate branch on my fork for this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18695)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

Thanks for this. I'm not sure where to use it, but it's nice to have a vector version available for sure.

**Comment by Coder206** [comment]
Source for components making up the SVG

- [Doge](https://github.com/42points/doge_assets/tree/master/assets/Logos/Vector)
- [Rust Logo](https://www.rust-lang.org/logos/rust-logo-blk.svg)

**Comment by jdm** [comment]
@bors-servo: retry
* broken virtualenv

**Comment by jdm** [comment]
@bors-servo: retry
* #18961

**Comment by upsuper** [comment]
Doge's asserts use cc-by-nc-sa. Would it be a problem to use its work like this? I don't see any license information for Servo's asserts...

**Pull request merged**
