### PR TITLE
layout: Make `margin: auto` work properly with tables.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5831)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/block.rs @ r2
- components/layout/fragment.rs @ r2
- components/layout/table_wrapper.rs @ r1
- tests/ref/basic.list @ r1
- tests/ref/table_margin_auto_a.html @ r1
- tests/ref/table_margin_auto_ref.html @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5831)

**Comment by mbrubeck** [comment]
r=mbrubeck, needs rebase

**Comment by mbrubeck** [comment]
<sup>**[components/layout/table_wrapper.rs, line 97 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5831#-Jnw7Va-cG0r7BtIRSXM)** ([raw file](https://github.com/servo/servo/blob/1af3e48c52214662a1502fc8c12dfe9d512d1777/components/layout/table_wrapper.rs#L97)):</sup>
Should this use `self.spacing()`, so it takes border-collapse into account?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5831)

**Comment by pcwalton** [comment]
Yup, it should have used `self.spacing()`. Also rebased. r? @mbrubeck

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/block.rs @ r3
- components/layout/fragment.rs @ r3
- components/layout/table.rs @ r3
- components/layout/table_cell.rs @ r3
- components/layout/table_row.rs @ r3
- components/layout/table_rowgroup.rs @ r3
- components/layout/table_wrapper.rs @ r3
- tests/ref/basic.list @ r3

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5831)

**Pull request merged**
