### PR TITLE
Make Layout 2020/2013 a runtime switch

### LINKED ISSUE #29942: Make the choice to use legacy layout (Layout 2013) a runtime setting
Instead of compiling two different binaries, we should be able to choose the layout engine using a runtime setting.

### PR DESCRIPTION
**Pull request by mrobinson**
This change  makes the choice between Layout 2020 and Layout
2013 a runtime switch. The main part of the patch is removing all layout
related compile-time flags from the style crate. This makes the style crate a
lot simpler, but now Layout 2020 parses a good deal of features that it doesn't
support (table, vertical-align, etc). The good news is that we plan to add
these features to Layout 2020. 

- Compile a single style for both Layout 2020 and Layout 2013
- Remove layout_2020/layout_2013 features
- Update GitHub workflows for single compilation
- Update test results

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #29942
- [x] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
The way this works:
 - `./mach run --release` ← Layout 2020
 - `./mach run --release --legacy-layout` ← Layout 2013

**Comment by sagudev** [comment]
[Got consistent `PASS [expected FAIL] /css/CSS2/margin-padding-clear/margin-collapse-040.xht` on layout-2020](https://github.com/sagudev/servo/actions/runs/5429796200/jobs/9875501452).

**Comment by sagudev** [comment]
> There is still more work that needs to be done here for reporting
results / selecting which tests to run.

Shouldn't https://github.com/servo/servo/pull/29950/commits/88098534aa05a851745475000bcd27f18e679416 get updated commit message or is there still more work needed?

**Comment by mrobinson** [comment]
> > There is still more work that needs to be done here for reporting
> > results / selecting which tests to run.
> 
> Shouldn't [8809853](https://github.com/servo/servo/commit/88098534aa05a851745475000bcd27f18e679416) get updated commit message or is there still more work needed?

Oh, you're right. I've updated the commit message.

**Comment by sagudev** [comment]
>  These changes fix #___ (GitHub issue number if applicable)

Did you forget to fill with https://github.com/servo/servo/issues/29942?

**Review by mukilan — APPROVED** [review]
Great work!

**Comment by mrobinson** [comment]
@bors-servo r=mukilan
 - Really appreciate the review.

**Pull request merged**
