### PR TITLE
Update WR (first phase of z-buffer optimizations / improvements).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14818)

### CODE REVIEW

**Comment by glennw** [comment]
@bors-servo retry
 * Infra? (python OSErr exception)

**Comment by glennw** [comment]
Any suggestions on what may be causing http://build.servo.org/builders/mac-rel-wpt1/builds/1659/steps/test__1/logs/stdio ?

**Comment by jdm** [comment]
Previously seen in #13400, but I don't believe we've ever figured anything out about it.

**Comment by glennw** [comment]
@bors-servo retry
 * 13400

**Comment by jdm** [comment]
@bors-servo: retry
* #13400

**Comment by jdm** [comment]
If this hits #13400 again, I am absolutely blaming the changes in this PR for it.

**Comment by glennw** [comment]
I have no idea how this PR could trigger that intermittent more often :(

**Comment by jdm** [comment]
No other PR is hitting it, so it seems like a pretty clear cause and effect.

**Comment by glennw** [comment]
@jdm I don't disagree, I'm just not sure how to debug it... I can't reproduce locally, I'll try to see if I can repro on a build machine.

**Comment by glennw** [comment]
@jdm Hmm, so we seem to have the same intermittent error occurring in a few different issues (see https://github.com/servo/servo/issues/14152, https://github.com/servo/servo/issues/13662, https://github.com/servo/servo/issues/13400).

According to https://stackoverflow.com/questions/12521705/why-would-killpg-return-not-permitted-when-ownership-is-correct you will get that error from Python on OSX, if you try to kill a process group that has already exited (and gone into zombie state).

There's also this recent commit in mozprocess, which doesn't appear to have made it into a released python package yet - https://github.com/mozilla/gecko-dev/commit/ffb7cb0b99cd118dbaab4e4d3c136deabd69c43c - it is in the same area of the code we are seeing an exception, but doesn't sound exactly the same.

I wonder if the timing differences from this WR update are enough to expose something like that? Still investigating...

**Comment by glennw** [comment]
@jdm Actually, looking at https://github.com/mozilla/gecko-dev/commit/ffb7cb0b99cd118dbaab4e4d3c136deabd69c43c more closely, I think this is exactly what we're hitting (see the changes around line 160, and compare to the callstack at http://build.servo.org/builders/mac-rel-wpt1/builds/1694/steps/test__1/logs/stdio).

Do you know what the process is to get a new tagged version of mozprocess uploaded so that we can update to that version and test with it?

Also, if you agree that the bug fix commit in mozprocess above is likely to fix this bug, are you happy to retry this PR and push through the intermittent until we get an updated mozprocess (given that it's happening in a lot of other issues / PRs as I linked above)?

**Comment by jdm** [comment]
@jgraham Any thoughts on the mozprocess stuff above?

**Comment by jgraham** [comment]
We can get a new mozprocess release for you. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1328823 for that.

**Comment by jdm** [comment]
My fear with pushing through as-is is that we'll inflict the same pain on every subsequent PR.

**Comment by jdm** [comment]
@bors-servo: retry
* #13400

**Comment by glennw** [comment]
@jdm I'm fine with waiting until we get the new mozprocess and trying that - if you want to r- this until then?

**Comment by glennw** [comment]
Rebased and updated to latest WR - just to see if this makes any difference to the intermittent failure. I also have access to another mac that I'm trying to repro this on.

**Comment by glennw** [comment]
OK, I have finally managed to reproduce this locally - I'll test with the updated mozprocess here and see if that helps.

**Comment by jdm** [comment]
@bors-servo: retry
mozprocess has been released, and we should get the newest version implicitly in our virtualenv. Let's see if anything's different!

**Comment by jdm** [comment]
@bors-servo: retry
* #14323

**Comment by jdm** [comment]
Darn, same failure. Hard to tell if that's because we didn't actually get the upgraded version of mozprocess or the fix wasn't enough. Maybe adding it explicitly to requirements.ini would be enough?

**Comment by jgraham** [comment]
I couldn't see anything in the buildbot config that would purge the virtualenv between runs (I assume the mach commands don't do that by default). Maybe try adding an explicit `mach clean` to the steps in the yaml file for the appropriate builder (under `/etc/ci/` in servo/servo).

**Comment by glennw** [comment]
I tried it locally with mozprocess 0.24 and was still able to reproduce it - perhaps less often but still occurring. I'll investigate on Monday to see if I can track down the exact cause.

**Comment by jdm** [comment]
The log for the `git update` step includes the text `Removing python/_virtualenv/`.

**Comment by glennw** [comment]
@jdm OK, I have confirmed the cause of this failure, and it appears to be a race condition that this WR update unfortunately happens to expose.

If a process (group) exits by itself and enters the zombie state, OSX will return the exception that we are seeing.

I've opened a bugzilla bug with more details: https://bugzilla.mozilla.org/show_bug.cgi?id=1329528

I've confirmed that in this case the process is exiting as expected (this is an expected fail) when the bug occurs.

Given that, is it reasonable to mark that test as intermittent / disabled until the mozprocess fix is done and released, so we can land this WR update?

**Comment by jdm** [comment]
I'm ok with disabling the test given that investigation. Thanks!

**Comment by glennw** [comment]
```error: failed to write compressed bytecode: There is not enough space on the disk. (os error 112)```

**Comment by glennw** [comment]
@larsbergstrom Ideas about the above MSVC failure?

**Comment by glennw** [comment]
@bors-servo retry
 * infra - just in case it magically fixed itself.

**Pull request merged**
