### PR TITLE
Miscellaneous fixes to harden the constellation.

### PR DESCRIPTION
**Pull request by asajeffrey**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10295)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Part of #10124 constellation hardening.

**Comment by nox** [comment]
A few nits, feel free to r=me when you address them.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/compositing/constellation.rs, line 714 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10295#-KEAuSrFXd9PQoIJ9tkL:-KEAuSrFXd9PQoIJ9tkM:1490934805) ([raw file](https://github.com/servo/servo/blob/f9f15876cdcf302b1f43a1d660d76d85b696e772/components/compositing/constellation.rs#L714)):*
Nit: please no `unwrap_or_else` for side-effects.

---

*[components/compositing/constellation.rs, line 1498 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10295#-KEAuWd6VnHTwWaRqPnh:-KEAuWd6VnHTwWaRqPni:-78598091) ([raw file](https://github.com/servo/servo/blob/f9f15876cdcf302b1f43a1d660d76d85b696e772/components/compositing/constellation.rs#L1498)):*
Nit: Please no `unwrap_or_else` for side-effects.

---

*[components/compositing/constellation.rs, line 1574 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10295#-KEAubjWZYikJ7lmsjXx:-KEAubjWZYikJ7lmsjXy:789750418) ([raw file](https://github.com/servo/servo/blob/f9f15876cdcf302b1f43a1d660d76d85b696e772/components/compositing/constellation.rs#L1574)):*
Nit: `self.frames.remove(&frame_id).is_none()`

---

*[components/compositing/constellation.rs, line 1575 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10295#-KEAujO4gmc9sVhhZDWy:-KEAujO4gmc9sVhhZDWz:-1792621220) ([raw file](https://github.com/servo/servo/blob/f9f15876cdcf302b1f43a1d660d76d85b696e772/components/compositing/constellation.rs#L1575)):*
I wonder, this could also happen if it receives a nonsensical `frame_id` value, right? So shouldn't this message just be about not finding a frame?

---

*[components/compositing/constellation.rs, line 1606 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10295#-KEAurda2zzCu21NCfOU:-KEAurdbcwGRk4PLlGUu:1523749856) ([raw file](https://github.com/servo/servo/blob/f9f15876cdcf302b1f43a1d660d76d85b696e772/components/compositing/constellation.rs#L1606)):*
Shouldn't this message just be about not finding a pipeline?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10295#-:-KEAuvw3a_vIn02nom7K:1135513355)*

**Comment by asajeffrey** [comment]
I'll submit another PR replacing `unwrap_or_else` by `if let`.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/compositing/constellation.rs, line 1575 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10295#-KEAujO4gmc9sVhhZDWy:-KECT-vCwZJpR0pJcBgc:1324106673) ([raw file](https://github.com/servo/servo/blob/f9f15876cdcf302b1f43a1d660d76d85b696e772/components/compositing/constellation.rs#L1575)):*
Well... the FrameId is only created by new_frame, which adds the id to the frames hash map, then only removed by close_frame. So the debug message is correct (and if we reword this one, we should probably reword all the other ones too, there's quite a lot of them in other PRs!).

---

*[components/compositing/constellation.rs, line 1606 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10295#-KEAurda2zzCu21NCfOU:-KECU07nBzTJz1jT5CRp:1700997001) ([raw file](https://github.com/servo/servo/blob/f9f15876cdcf302b1f43a1d660d76d85b696e772/components/compositing/constellation.rs#L1606)):*
Ditto.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10295#-:-KECWH3TRpbDBUnYhkG6:1660719921)*

**Comment by asajeffrey** [comment]
I should clarify: I can't submit a PR replacing `unwrap_or_else` by `if let` until this PR lands.

**Comment by asajeffrey** [comment]
@bors-servo r=nox

Got the OK on IRC: http://logs.glob.uno/?c=mozilla%23servo#c397095

**Pull request merged**
