### PR TITLE
Updated mozjs_sys to v0.51.3

### LINKED ISSUE #21093: mozjs_sys + target=android-i686: Rust compilation error
`./mach build --target=i686-linux-android -d`

```
rustc 1.28.0-nightly (b68432d56 2018-06-12)
info: component 'rust-std' for target 'i686-linux-android' is up to date
   Compiling mozjs_sys v0.51.2
error[E0605]: non-primitive cast: `u64` as `[u32; 2]`
    --> /home/paul/git/servo/target/i686-linux-android/debug/build/mozjs_sys-6e56c52d2ad6e5a9/out/jsapi.rs:1633:7603
     |
1633 |  # [ repr ( C ) ] # [ derive ( Debug , Copy ) ] pub struct CallArgs { pub argv_ : * mut root::JS::Value , pub argc_ : :: std :: os :: raw :: c_uint , pub _bitfield_1 : root :: __BindgenBitfieldUnit
     |
     |
     = note: an `as` expression can only be used to convert between primitive types. Consider using the `From` trait
```

### PR DESCRIPTION
**Pull request by asajeffrey**
Allows building servo for target `i686-linux-android`.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #21093 
- [X] These changes do not require tests because deperndency update

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21102)

### CODE REVIEW

**Comment by SimonSapin** [comment]
homu says this is pending but buildbot seems to have not be notified at all.

@bors r-

**Comment by asajeffrey** [comment]
Hmm, even force cleaning it doesn't seem to have helped.

**Comment by SimonSapin** [comment]
@bors-servo retry

https://github.com/servo/servo/issues/21108

**Comment by SimonSapin** [comment]
Only the mac job ever started… Pushing yet another trivially-amended commit to try get homu/buildbot more into a known state.

@bors-servo r+

**Pull request merged**
