### PR TITLE
Add CSS Multicolumn support with block fragmentation

### PR DESCRIPTION
**Pull request by SimonSapin**
a

Includes/supersedes #8763.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9170)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 8 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 4 of 14 files at r6.
Review status: 10 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/layout/block.rs, line 761 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7SHmR6ajw5reyEtPdp:-K7SHmR7psQ5t2ffj0_U:-993795427) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/block.rs#L761)):*
Please add to the doc comment to explain the return value.

---

*[components/layout/construct.rs, line 1107 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7ST-JeapcxyQsUA-DM:-K7ST-JeapcxyQsUA-DN:-1138048642) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/construct.rs#L1107)):*
Nit: You could move the two variables above inside the `if` block below.

---

*[components/layout/construct.rs, line 1116 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7SSxLnETk34Qc1pIyk:-K7SSxLoBMwmQze0W1YC:1094603137) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/construct.rs#L1116)):*
Where is `fixed_descendants` used?  (Same question applies to `build_flow_for_table_wrapper` where this code originated.)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9170)*

**Comment by mbrubeck** [comment]
Reviewed 7 of 14 files at r6.
Review status: 17 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/layout/Cargo.toml, line 79 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7Scu-G47swdEM3a3Vv:-K7Scu-HI36yPaCP1R4o:-318486094) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/Cargo.toml#L79)):*
Is this used anywhere?

---

*[components/layout/flow_list.rs, line 35 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7Sc7jHNsFEExxtc0Wu:-K7Sc7jI45VdFWca4DWe:-587719667) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/flow_list.rs#L35)):*
Nit: Change `new_tail` to `new_head`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9170)*

**Comment by mbrubeck** [comment]
Reviewed 3 of 14 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9170)*

**Comment by SimonSapin** [comment]
Rebased

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/layout/block.rs, line 761 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7SHmR6ajw5reyEtPdp:-K7q5wCA-BYPqMPevVZC:439585378) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/block.rs#L761)):*
This is a trait implementation, the return value is documented in the trait definition in `flow.rs`. Should I duplicate that doc-comment here?

---

*[components/layout/Cargo.toml, line 79 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7Scu-G47swdEM3a3Vv:-K7q6vXXRBzoVfBgtZ56:-852893109) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/Cargo.toml#L79)):*
It was at some point while I was preparing this PR, but then I rewrote things differently. Removed.

---

*[components/layout/construct.rs, line 1107 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7ST-JeapcxyQsUA-DM:-K7q8_X2G4_Zyr9K1CCm:-499146009) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/construct.rs#L1107)):*
Done.

---

*[components/layout/construct.rs, line 1116 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7SSxLnETk34Qc1pIyk:-K7q9fJolZrCGNmfoTpH:-2010089419) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/construct.rs#L1116)):*
That’s a good question! I didn’t look too closely when I copied `build_flow_for_table_wrapper`. It’s indeed unused, and other parts of `construct.rs` don’t seem to deal with fixed positioning at all. Maybe this can be removed? I did that in a separate commit.

`construct.rs` deals with absolute positioning during a tree traversal in order to find the containing block of each abspos element, but fixed positioning is simpler in that regard: the containing block is always the same (the initial containing block / viewport).

---

*[components/layout/flow_list.rs, line 35 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7Sc7jHNsFEExxtc0Wu:-K7q7P0KDc_mL2RXaioD:-499146009) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/flow_list.rs#L35)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9170#-:-K7q5sL7HKq4l0UOtcS6:599748763)*

**Comment by SimonSapin** [comment]
```
 Downloading encoding-index-singlebyte v1.20141219.5
unable to get packages from source
```

In crates.io having troubles?

**Comment by SimonSapin** [comment]
7 failures like:

```
  ▶ TIMEOUT [expected OK] /html/semantics/embedded-content/the-img-element/srcset/parse-a-srcset-attribute.html
  │ 
  │ thread 'LayoutWorker worker 27/27' panicked at 'RefCell<T> already borrowed', ../src/libcore/cell.rs:443
  │ stack backtrace:
  │    1:     0x7fe6af424ce0 - sys::backtrace::tracing::imp::write::h92808652e552bec0MZt
  │    2:     0x7fe6af427b45 - panicking::log_panic::_<closure>::closure.41184
  │    3:     0x7fe6af4275c0 - panicking::log_panic::hc4038fe8a2a609d626x
  │    4:     0x7fe6af410fb3 - sys_common::unwind::begin_unwind_inner::hd5a3cc6e3320d6b8lSs
  │    5:     0x7fe6af411668 - sys_common::unwind::begin_unwind_fmt::h7eec50b09af6e91crRs
  │    6:     0x7fe6af424341 - rust_begin_unwind
  │    7:     0x7fe6af455a7f - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:     0x7fe6af455d58 - panicking::panic::hbe2e3a5159c3d178iEK
  │    9:     0x7fe6ae114ab4 - construct::_<impl>::set_flow_construction_result::h9792383650693152545
  │   10:     0x7fe6ae106026 - construct::_<impl>::process::h1788515922904549746
  │   11:     0x7fe6ae101d63 - traversal::_<impl>::process_postorder::h13951435946108322380
  │   12:     0x7fe6ae14656a - parallel::top_down_dom::top_down_dom::h14886232875665109854
  │   13:     0x7fe6ae07fdcf - sys_common::unwind::try::try_fn::try_fn::h2528078259394583905
  │   14:     0x7fe6af424188 - __rust_try
  │   15:     0x7fe6af42055b - sys_common::unwind::try::inner_try::h3990fffe7b775df5TOs
  │   16:     0x7fe6ae0817c9 - boxed::_<impl>::call_box::call_box::h9332087171025244514
  │   17:     0x7fe6af4264a3 - sys::thread::_<impl>::new::thread_start::h05427eb97025f9aae9w
  │   18:     0x7fe6ab2eb181 - start_thread
  │   19:     0x7fe6ad50247c - __clone
  └   20:                0x0 - <unknown>
```

I can’t reproduce them reliably, so this may be a race condition. Which is worrying, since `RefCell` is not thread-safe.

**Comment by SimonSapin** [comment]
I don’t get this specific error locally, but I get another one :( (21 crashes with very similar stack traces.)

```
  ▶ CRASH [expected FAIL] /css-backgrounds-3_dev/html4/background-size-vector-002.htm
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:741
  │ thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
  │ stack backtrace:
  │    1:        0x10be9f2b8 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x10bea137f - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x10bea0e22 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x10be8cb34 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x10be8d01e - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
  │    6:        0x10be9e8d7 - rust_begin_unwind
  │    7:        0x10bec39e0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:        0x10bec3cdc - panicking::panic::hbe2e3a5159c3d178iEK
  │    9:        0x10ac82ed9 - page::_<impl>::window::h6013a10d39979b48yp5
  │   10:        0x10b0ea7c4 - script_thread::_<impl>::drop::h82d1837d1a916459rM6
  │   11:        0x10b0ee208 - sys_common::unwind::try::try_fn::try_fn::h17642862890741418990
  │   12:        0x10be9e6f8 - __rust_try
  │   13:        0x10be9b7fe - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   14:        0x10b0ee7c1 - boxed::_<impl>::call_box::call_box::h9382266553964020789
  │   15:        0x10bea060d - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   16:     0x7fff98c23898 - _pthread_body
  │   17:     0x7fff98c23729 - _pthread_start
  └ thread panicked while panicking. aborting.

**Comment by mbrubeck** [comment]
Reviewed 16 of 16 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[components/layout/block.rs, line 761 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7SHmR6ajw5reyEtPdp:-K7r3DmMp4MXaw8EfXJj:-219080819) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/block.rs#L761)):*
This is an inherent method on `BlockFlow`. Are you thinking of the `Flow::fragment` trait method?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9170)*

**Comment by SimonSapin** [comment]
@bors-servo try

---

Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/layout/block.rs, line 761 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9170#-K7SHmR6ajw5reyEtPdp:-K7xIliTx9wVAOFoIeCH:-1775221129) ([raw file](https://github.com/servo/servo/blob/94a5e4406561a0aa61865d73a478de0524c74247/components/layout/block.rs#L761)):*
Sorry, you’re right. I did not look closely enough and did not remember that `Option<FlowRef>` was returned anywhere other `Flow::fragment`. I expanded the doc-comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9170#-:-K7xJxYNdUYzNo-6Uk8K:-318615280)*

**Comment by mbrubeck** [comment]
Reviewed 5 of 5 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9170)*

**Comment by KiChjang** [comment]
```
Ran 9335 tests finished in 1162.0 seconds.
  • 9333 ran as expected. 55 tests skipped.
  • 2 tests timed out unexpectedly

Tests with unexpected results:
  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/abspos-non-replaced-width-margin-000.htm
  │ 
  │ thread 'LayoutWorker worker 5/6' panicked at 'RefCell<T> already borrowed', ../src/libcore/cell.rs:443
  │ stack backtrace:
  │    1:        0x1036cff88 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x1036d204f - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x1036d1af2 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x1036bd906 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x1036bdcee - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
  │    6:        0x1036cf5a7 - rust_begin_unwind
  │    7:        0x1036f46b0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:        0x1036f49ac - panicking::panic::hbe2e3a5159c3d178iEK
  │    9:        0x1023bed9e - construct::_<impl>::set_flow_construction_result::h9362615947550250617
  │   10:        0x1023b07b0 - construct::_<impl>::process::h17592932530484821616
  │   11:        0x1023ac1f3 - traversal::_<impl>::process_postorder::h11489338087134573740
  │   12:        0x1023f22da - parallel::top_down_dom::top_down_dom::h2552739976810130027
  │   13:        0x102327b22 - sys_common::unwind::try::try_fn::try_fn::h2878804891104217551
  │   14:        0x1036cf3c8 - __rust_try
  │   15:        0x1036cc4ce - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   16:        0x102329527 - boxed::_<impl>::call_box::call_box::h5535962091730664344
  │   17:        0x1036d12dd - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   18:     0x7fff91449059 - _pthread_body
  └   19:     0x7fff91448fd6 - _pthread_start

  ▶ TIMEOUT [expected FAIL] /css21_dev/html4/abspos-replaced-width-margin-000.htm
  │ 
  │ thread 'LayoutWorker worker 5/6' panicked at 'RefCell<T> already borrowed', ../src/libcore/cell.rs:443
  │ stack backtrace:
  │    1:        0x1084ecf88 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x1084ef04f - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x1084eeaf2 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x1084da906 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x1084dacee - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
  │    6:        0x1084ec5a7 - rust_begin_unwind
  │    7:        0x1085116b0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:        0x1085119ac - panicking::panic::hbe2e3a5159c3d178iEK
  │    9:        0x1071dbd9e - construct::_<impl>::set_flow_construction_result::h9362615947550250617
  │   10:        0x1071cd7b0 - construct::_<impl>::process::h17592932530484821616
  │   11:        0x1071c91f3 - traversal::_<impl>::process_postorder::h11489338087134573740
  │   12:        0x10720f2da - parallel::top_down_dom::top_down_dom::h2552739976810130027
  │   13:        0x107144b22 - sys_common::unwind::try::try_fn::try_fn::h2878804891104217551
  │   14:        0x1084ec3c8 - __rust_try
  │   15:        0x1084e94ce - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   16:        0x107146527 - boxed::_<impl>::call_box::call_box::h5535962091730664344
  │   17:        0x1084ee2dd - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   18:     0x7fff91449059 - _pthread_body
  └   19:     0x7fff91448fd6 - _pthread_start
```

**Comment by SimonSapin** [comment]
Rebased. I’ll try to run rr on CI servers or something.

**Comment by SimonSapin** [comment]
@bors-servo r=mbrubeck

Based on a bunch of try runs in #9435 I’m reasonably confident that this bit of code that I had added previously in this PR:

```rust
            self.set_can_be_fragmented(parent.as_ref().map_or(false, |p| {
                p.can_be_fragmented() ||
                p.borrow_data().unwrap().style.as_ref().unwrap().is_multicol()
            }));
```

Is what triggers the occasional `RefCell<T> already borrowed` failure as above. I’ve now replaced `p.borrow_data().unwrap().style` with `parent_style` from earlier in the same method:

```rust
        // Get our parent's style. This must be unsafe so that we don't touch the parent's
        // borrow flags.
        //
        // FIXME(pcwalton): Isolate this unsafety into the `wrapper` module to allow
        // enforced safe, race-free access to the parent style.
        let parent_style = match parent {
            None => None,
            Some(parent_node) => {
                let parent_style = (*parent_node.borrow_data_unchecked().unwrap()).style.as_ref().unwrap();
                Some(parent_style)
            }
        };
```

@pcwalton says that the reason for not touching the parent’s borrow flag is that siblings are going through this method (style computation) in parallel. But:

* That means that using the checked `borrow_data()` method which does touch the borrow flag is a data race
* The panics we observed were in `set_flow_construction_result`, presumably of the parent

**Comment by jdm** [comment]
@bors-servo: retry
* #9303 #9448

**Comment by jdm** [comment]
@bors-servo: retry
* #9063

**Comment by SimonSapin** [comment]
```
  • 128 tests failed unexpectedly
```

All of them reftests.

**Comment by KiChjang** [comment]
@bors-servo retry
* #9460

**Comment by jdm** [comment]
@bors-servo: retry
* #9448

**Pull request merged**
