### PR TITLE
Share more `./mach build` logic with mach check, doc, test-unit

### LINKED ISSUE #23659: Add a CI test that verifies that `mach check` works
We keep breaking it when playing around with cargo features. We should stop breaking it!

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes #23659

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23676)

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by SimonSapin** [comment]
https://tools.taskcluster.net/groups/OrlW70z3RqK_35WGOOGJ0g is green, this is ready to land.

**Comment by CYBAI** [comment]
```
Error running mach:

    ['build', '--android', '--dev']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

AttributeError: 'NoneType' object has no attribute 'startswith'

  File "/repo/python/servo/build_commands.py", line 180, in build
    base_path = path.join(target_path, target)
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
```

```
Error running mach:

    ['build', '--magicleap', '--dev']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

AttributeError: 'NoneType' object has no attribute 'startswith'

  File "/Users/worker/tasks/task_1562049079/repo/python/servo/build_commands.py", line 183, in build
    base_path = path.join(target_path, target)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
```

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
