### PR TITLE
Revert "Auto merge of #17891 - MortimerGoro:webgl_move, r=glennw,emilio"

### PR DESCRIPTION
**Pull request by emilio**
This reverts commit 90f55ea4580e2a15f7d70d0491444f18b972d450, reversing
changes made to 2e60b27a2186a8cba4b952960155dfcf3f47d7db.

Doing that per Josh's request, since it's causing very frequent intermittent OOMs on the android builders.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18114)

### CODE REVIEW

**Comment by emilio** [comment]
cc @MortimerGoro, sorry :(

r? @nox

**Comment by nox** [comment]
RIP

@bors-servo r+

**Comment by MortimerGoro** [comment]
`Doing that per Josh's request, since it's causing very frequent intermittent OOMs on the android builders.`

Wow, what could cause that? any ideas?

**Comment by MortimerGoro** [comment]
@jdm what's the best way to try a lot compilations with the android builders in a new PR? Is there any bors-servo command to test compilations only on android builders?

I never had that OOM in my local rust compilations. I can try to remove a template parameter from the WebGL thread or the webrender dependency in canvas (just needs a small change in WR). It's the only reasons which I think could cause that kind compilation of error. The other code is normal.

**Comment by larsbergstrom** [comment]
@edunham Can we upgrade all the linux cross builders to something with > 8GB of RAM (at least 16 GB)?

**Comment by jdm** [comment]
We continue to have memory errors after reverting this PR; my apologies for assigning the blame incorrectly. You are welcome to re-merge these changes.

**Comment by MortimerGoro** [comment]
@jdm no problem, I created a new PR to re-merge the WebGL redesign ;) https://github.com/servo/servo/pull/18119

**Comment by MortimerGoro** [comment]
Closed the new PR, I didn't see that @nox had already created it

**Pull request merged**
