### PR TITLE
enable css paint api and remove forked duplicates

### LINKED ISSUE #19840: Enable css-paint-api WPT tests and remove forked duplicates
https://github.com/servo/servo/tree/master/tests/wpt/mozilla/tests/mozilla/css-paint-api is a fork we previously made of https://github.com/w3c/web-platform-tests/tree/master/css/css-paint-api. Since we can now use the vendored copy from upstream (https://github.com/servo/servo/tree/master/tests/wpt/web-platform-tests/css/css-paint-api), we should remove any of the duplicated tests in our copy and [enable](https://github.com/servo/servo/blob/master/tests/wpt/include.ini) the originals.

Use `./mach test-wpt tests/wpt/web-platform-tests/css/css-paint-api` and `./mach test-wpt tests/wpt/mozilla/tests/mozilla/css-paint-api` to run the tests in the two directories.

### PR DESCRIPTION
**Pull request by yurket**
1) Move paintWorklet from "Window" to "CSS" according to new specification;
2) Enable WPT css-paint-api tests from upstream and remove forked duplicates from mozilla folder

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #19840
- [X] These changes do not require tests because the change was made in tests it-selves

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20083)

### CODE REVIEW

**Comment by jdm** [comment]
Also I figured out why your manifest changes were so extensive - if you remove the _venv directory from tests/wpt/web-platform-tests (which was created when you ran some tests from that directory directly), it should stop happening.

**Comment by asajeffrey** [comment]
Thanks for doing this!

**Comment by yurket** [comment]
I saw a number of _venv files, but hesitated to ask =\. Ok, So basically `tests/wpt/metadata/MANIFEST.json` should not change at all, because I didn't changed wpt tests, only included them?
I think, I can amend my last commit and force push it, right?
@asajeffrey, @jdm glad to help!

**Comment by yurket** [comment]
@jdm, oh, looks like you already fixed it. Thanks for helping with issue then =)

**Comment by jdm** [comment]
@yurket Looks like we have some tests in https://github.com/yurket/servo/tree/567db5afe55fafaf33f4da1ee8f4a6f9468ccacd/tests/wpt/mozilla/tests/mozilla/worklets that need to be updated to match the new code changes as well.

**Comment by yurket** [comment]
@jdm will fix it

**Comment by yurket** [comment]
@jdb hmm... even patched
```
--- a/tests/wpt/mozilla/tests/mozilla/worklets/test_paint_worklet.html
+++ b/tests/wpt/mozilla/tests/mozilla/worklets/test_paint_worklet.html
@@ -11,7 +11,7 @@
     <script>
         // This reftest will TIMEOUT if loading the paint worklet fails,
         // It will PASS if the worklet draws a green rectangle.
-        window.paintWorklet
+        CSS.paintWorklet
             .addModule("test_paint_worklet.js")
             .then(function() { document.documentElement.classList.remove("reftest-wait"); });
     </script>
```
1 test _mozilla/worklets/test_paint_worklet.html_ still failing 
```
$ ./mach test-wpt tests/wpt/mozilla/tests/mozilla/worklets/
Running 5 tests in web-platform-tests

  ▶ FAIL [expected PASS] /_mozilla/mozilla/worklets/test_paint_worklet.html
  └   → /_mozilla/mozilla/worklets/test_paint_worklet.html 23b755622cc81841a23cc8431a6546dfb1401c66
/_mozilla/mozilla/worklets/test_paint_worklet_ref.html 7949e80732fa0f4afdbae3b1cad96ccd75bb04f6
Testing 23b755622cc81841a23cc8431a6546dfb1401c66 == 7949e80732fa0f4afdbae3b1cad96ccd75bb04f6

Ran 5 tests finished in 12.0 seconds.
  • 4 ran as expected. 0 tests skipped.
  • 1 tests failed unexpectedly

```

**Comment by yurket** [comment]
@jdm, can't figure out why test `tests/wpt/mozilla/tests/mozilla/worklets/test_paint_worklet.html` still failing. Any ideas? Or maybe I should just change expectation for this one?

**Comment by asajeffrey** [comment]
@yurket hmm, rather annoyingly it works at my end:
```
$ ./mach test-wpt /_mozilla/mozilla/worklets/
Running 5 tests in web-platform-tests

Ran 5 tests finished in 7.0 seconds.
  • 5 ran as expected. 0 tests skipped.
```
The changes I made were just to use `CSS.paintWorklet`, e.g.
```
$ git diff tests/wpt/mozilla/tests/mozilla/worklets/test_paint_worklet.html
diff --git a/tests/wpt/mozilla/tests/mozilla/worklets/test_paint_worklet.html b/tests/wpt/mozilla/tests/mozilla/worklets/test_paint_worklet.html
index 1dfe906..5958510 100644
--- a/tests/wpt/mozilla/tests/mozilla/worklets/test_paint_worklet.html
+++ b/tests/wpt/mozilla/tests/mozilla/worklets/test_paint_worklet.html
@@ -11,7 +11,7 @@
     <script>
         // This reftest will TIMEOUT if loading the paint worklet fails,
         // It will PASS if the worklet draws a green rectangle.
-        window.paintWorklet
+        CSS.paintWorklet
             .addModule("test_paint_worklet.js")
             .then(function() { document.documentElement.classList.remove("reftest-wait"); });
     </script>
```
This looks a lot like your edit! Prehaps you're running the test with a different compiled version of Servo? You could try submitting your edited tests and see if the CI system likes them.

**Comment by yurket** [comment]
@asajeffrey I've just rebased and rebuilt servo, but get the same result =\\. Anyway, submitted the changes

**Comment by yurket** [comment]
```
IOError: [Errno 28] No space left on device
```
I'm pretty sure, I can't fix it :D

**Comment by jdm** [comment]
@bors-servo retry
* cleaned up disk space usage

**Comment by asajeffrey** [comment]
Yay!

**Pull request merged**
