### PR TITLE
Make mouse_over_targets a RootedVec

### LINKED ISSUE #5539: Make mouse_over_targets a RootedVec
`Vec<JS<T>>` is unsafe, and we can do better now.

Code: components/script/dom/document.rs

### PR DESCRIPTION
**Pull request by cuzbog**
Fixes #5539

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5567)

### CODE REVIEW

**Comment by boghison** [comment]
@jdm @jgraham What's with the random closing and reopening?

**Comment by jgraham** [comment]
Sometimes critic gets behind the github repo for unknown reasons and then it has to be poked before it will create a review for the commits.

**Comment by boghison** [comment]
@jgraham That's why I like the highfive bot more :D

**Comment by Ms2ger** [comment]
Reviewed on critic

**Comment by boghison** [comment]
@Ms2ger Do I click on resolve issue before a commit or after? (Sorry, I'm new to contributing to Servo)

**Comment by Ms2ger** [comment]
You can leave that to the reviewer

**Comment by boghison** [comment]
@Ms2ger Is ^^ what you meant?

**Comment by boghison** [comment]
I have no idea what I just did :(

**Comment by jdm** [comment]
@boghison Looks like the rebase didn't go smoothly. Once option now is to reset the branch to point at master and cherry-pick each commit as necessary.

**Comment by boghison** [comment]
@jdm I'll do that then, just hope everything is going to look nice now

**Comment by boghison** [comment]
Just doing the reset :)

**Comment by jdm** [comment]
So I'm a bit worried about the change to store a RootedVec in ScriptTask instead of a regular Vec. Have you tried running Servo with these changes?

**Comment by boghison** [comment]
@jdm No, I only tested if it builds, why?

**Comment by jdm** [comment]
Because my suspicion is that there will be assertions when you try to quit Servo.

**Comment by boghison** [comment]
@jdm I see what you mean, my computer went berzerk :(

**Comment by jdm** [comment]
We're going to want to undo the changes from `Vec<JS<T>>` for the field in ScriptTask.

**Comment by jdm** [comment]
This is better, but still not quite correct - the existing code mutates ScriptTask's mouse_over_targets by passing it to the method as an argument; now we just mutate the copy that's stored on the stack and the original is unchanged. 

Also, are the (*) changes necessary?

**Comment by jdm** [comment]
I think it should be possible to see the effect of my last comment by hovering over a link in Servo - before these changes, move the mouse away will cause the hover style to disappear, and I would expect it to stay around now.

**Comment by boghison** [comment]
@jdm I see, so in script_task I am appending the vector, therefore any change will only reflect upon the RootedVec and not ScriptTask's mouse_over_targets, is this correct? I am not sure how to go about this. And regarding the (*), Deref is how we get the Vec from RootedVec, no?

**Comment by jdm** [comment]
Yes, * does explicitly dereference it, but it should work implicitly as well. With regards to updating ScriptTask's member, I would just override it after you have filled the RootedVec.

**Comment by boghison** [comment]
@jdm I am getting `thread 'ScriptTask' panicked at 'assertion failed: collections.set[type_ as usize].remove(&(collection as *const _ as *const _))'` when running servo, could this be because of the changes?

**Comment by jdm** [comment]
Yes, but I don't see why from looking at the changes. What's the backtrace that shows up if you run Servo using `./mach run`?

**Comment by boghison** [comment]
@jdm stack backtrace:
   1:     0x7f997444b8b2 - sys::backtrace::write::h754dbf5d2d3172ebPBA
   2:     0x7f997445e792 - panicking::on_panic::hdb9e837ac064f8afiHJ
   3:     0x7f997442e139 - rt::unwind::begin_unwind_inner::h488386ed3236ccf5lnJ
   4:     0x7f9972d5bc6e - rt::unwind::begin_unwind::h922800575808033075

**Comment by jdm** [comment]
There's more, right?

**Comment by boghison** [comment]
@jdm Not really, my computer just froze again because of this, so I was just desperately trying to kill the process.

**Comment by jdm** [comment]
Ok, my other suggestion would be to run Servo using `--debug`, set a breakpoint on `rust_panic`, run the program, and copy the result of `backtrace` when the panic occurs.

**Comment by boghison** [comment]
@jdm Apparently there are errors with the breakpoints after I run the program:
(gdb) rbreak rust_panic
Breakpoint 1 at 0x1ffeef0
<function, no debug info> rust_panic;
Breakpoint 2 at 0x1ffefe0
<function, no debug info> rt::unwind::rust_panic::exception_cleanup::hcb17a4608a1d2edfbjJ;

after running: 

Error in re-setting breakpoint 1: Warning:
Cannot insert breakpoint 2.
Cannot access memory at address 0x1ffefe0

and then on panic, the same backtrace:
   1:     0x5555575408b2 - sys::backtrace::write::h754dbf5d2d3172ebPBA
   2:     0x555557553792 - panicking::on_panic::hdb9e837ac064f8afiHJ
   3:     0x555557523139 - rt::unwind::begin_unwind_inner::h488386ed3236ccf5lnJ
   4:     0x555555e50c6e - rt::unwind::begin_unwind::h922800575808033075

**Comment by jdm** [comment]
Weeeird.

**Comment by boghison** [comment]
@jdm So what should I do?

**Comment by jdm** [comment]
I'll take a look at the assertion locally to move things along; I'm not certain why your setup seems to differ from other ones.

**Comment by jdm** [comment]
@boghison Ah, I figured out the problem, and it's quite subtle. line 620 in document.rs has `*prev_mouse_over_targets = mouse_over_targets`, which overwrites the RootedVec from the MouseMoveEvent branch in ScriptTask::handle_events with the RootedVecc from Document::handle_mouse_move_event. This move changes the ordering of the vectors' destruction and triggers the assertion. We can fix this here by clearing the original and appending to it; I've filed #5737 to avoid this in the future.

**Comment by boghison** [comment]
Oh, I see it now, thank you so much for looking into this :)

**Comment by boghison** [comment]
Oh, no, I just tested everything on an element with :hover (this reflects on CSS as well, no?), and it stays the same, if I stop hovering over the element, it'll still have the hover style applied :(

**Comment by jdm** [comment]
Want to squash these all together?

**Comment by boghison** [comment]
Sure! :) In a moment...

**Comment by boghison** [comment]
@jdm Done!

**Pull request merged**
