### PR TITLE
Implement HeapSizeOf for Url. Fixes #6912

### LINKED ISSUE #6912: Measure the heap usage of Url
There are a lot of them, and they're stubbed out as 0 in mem.rs right now.

### PR DESCRIPTION
**Pull request by cuzbog**
Fixes #6912

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6932)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good to me, but should this also remove something that previously said that `Url` uses zero heap size?

@jdm, you wrote in #6912 "they [URLs] are stubbed out as 0 in mem.rs right now", but I don’t see `Url` mentioned in `mem.rs` at all before this PR.

**Comment by boghison** [comment]
@SimonSapin It wasn't even included in mem.rs. Maybe another mem.rs? (There are 3 more :D )

**Comment by SimonSapin** [comment]
I checked, none of them mention URLs either :)

**Comment by jdm** [comment]
Right, I added the stub in my unmerged #6874.

**Comment by SimonSapin** [comment]
In that case,

@bors-servo r+

**Pull request merged**
