### PR TITLE
Upgrade core foundation

### PR DESCRIPTION
**Pull request by faern**
This PR is the final one in a chain of PRs that tries to make a breaking change to `core-foundation`. This PR makes sure Servo only use the new, not yet released `core-foundation 0.5.0`. The changes in `core-foundation` and why it is not yet published can be read in the comments on this PR: https://github.com/servo/core-foundation-rs/pull/132
Basically we want all of Servo (and deps) to be ready for a fairly swift upgrade from `core-foundation` `0.4.6` to `0.5.0` once it's released, so we don't end up in some state where we depend on, and have to maintain both, for an extended period of time.

This PR is **not ready for merge** in its current state. The following must be done first:
- [x] Merge https://github.com/servo/core-foundation-rs/pull/132 and publish.
- [x] Merge https://github.com/servo/core-graphics-rs/pull/110 and publish.
- [x] Merge https://github.com/servo/core-text-rs/pull/75 and publish.
- [x] Merge https://github.com/servo/cocoa-rs/pull/181 and publish.
- [x] Merge https://github.com/servo/glutin/pull/142 and publish.
- [x] Merge https://github.com/servo/io-surface-rs/pull/60 and publish.
- [x] Merge https://github.com/servo/skia/pull/148.
- [x] Merge https://github.com/servo/rust-azure/pull/282.
- [x] Merge https://github.com/servo/webrender/pull/2299.
- [x] Merge https://github.com/emilio/rust-offscreen-rendering-context/pull/118 and publish.
- [x] Remove the commit in this PR that temporarily adds patch entries to `Cargo.toml`.
- [x] Update Cargo.lock again to not point to my feature branches.

For some of the dependencies I might accidentally have bumped the version as if it was a breaking change when it in fact wasn't. It was a bit messy to figure out all the details in so many and large crates. But hopefully I did not do the inverse, only bump the patch version where the change actually broke something.

Ping @jdm and @nox who have been the ones commenting on the initial PR.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] These changes do not require tests because they don't change any code, just upgrade dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19759)

### CODE REVIEW

**Comment by faern** [comment]
@jrmuizel Awesome work on the `CFArray` iterator. Made it possible to simplify and get rid of `unsafe` here as well.

**Comment by faern** [comment]
@jdm @glennw This should hopefully be ready for merge finally!
The taskcluster says it fails, but I can't find the log for it.

**Comment by jdm** [comment]
@bors-servo r+
Whee!

**Comment by faern** [comment]
The test that fails in travis (`test_redirected_request_to_devtools`) works on my machine. We'll see what homu says.

**Comment by jdm** [comment]
That's #14774.

**Comment by faern** [comment]
Yay, finally! Thank you @jdm for your feedback and help getting this through :)

**Pull request merged**
