### PR TITLE
Upgrade nodes to custom elements on insertion, even if they're not connected to a Document

### LINKED ISSUE #24992: Using the is= property in innerHTML isn't using the custom element class
This is test case "innerHTML should instantiate a customized build-in element" in WPT custom-elements/builtin-coverage.html.

### LINKED ISSUE #25004: adding a custom element by tHead, tBody, or caption .innerHTML= doesn't fire a constructed event
WPT custom-elements/reactions/HTMLTableElement catches this, with misleading messages (it fails on the `constructed` event before even reaching the part where it expects `connectedCallback`).

Similar tests pass, in which the _table's_ .innerHTML= is being used to make a caption that already has the custom element inside it. The failures happen when the initially-empty caption (etc.) gets its _own_ innerHTML assigned to.

### PR DESCRIPTION
**Pull request by pshaughn**
After comparing tests to specs, I filed https://github.com/whatwg/dom/issues/833 and made this change to match what I believe the spec should be saying to reflect Firefox/Chrome/Safari shared behavior.

I also filed https://github.com/w3c/DOM-Parsing/issues/61 because this change revealed that custom elements created in a template's innerHTML setter weren't behaving themselves and the spec seemed not to reflect reality about them.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #24992 and fix #25004; they are relevant to #25007 but don't fix all the subcases thereof.

- [X] There are tests for these changes

### CODE REVIEW

**Comment by pshaughn** [comment]
I just noticed the commits; I'll squash after I see these results.

**Review by Manishearth — APPROVED** [review]
r=me

**Comment by pshaughn** [comment]
```▶ Unexpected subtest result in /custom-elements/reactions/Document.html:
  │ FAIL [expected PASS] importNode on Document must construct a new custom element when importing a custom element from a template
  │   → assert_array_equals: lengths differ, expected array [] length 0, got ["constructed"] length 1
  │ 
  │ @http://web-platform.test:8000/custom-elements/reactions/Document.html:33:5
  └ test_with_window/</<@http://web-platform.test:8000/custom-elements/resources/custom-elements-helpers.js:19:7```

I think this is a freshly exposed case of #25007; the fact that it has been exposed by this change is informative. I'm going to see if the fix for that makes sens to piggyback onto this.

**Comment by pshaughn** [comment]
Fixed that, I believe; see revised top comment.

**Comment by pshaughn** [comment]
It might be a good idea to see what comes out of https://github.com/whatwg/dom/issues/833 instead of immediately trying to merge this. It could be that every other browser is wrong here.

**Comment by pshaughn** [comment]
These code changes were just based on my opinion of the tests; when the issues mentioned in the initial comment are addressed, the actual code changes needed will be likely to differ from my guesses.

**Pull request closed without merging**
