### PR TITLE
stylo: Don't calculate restyle damage on text nodes

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes (the Servo-side, that is)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12957)

### CODE REVIEW

**Comment by emilio** [comment]
```
  ▶ TIMEOUT [expected PASS] /css-backgrounds-3_dev/html4/background-clip-008.htm
  │ 
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  │ failed to receive response to font request: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread LayoutWorker worker 2/12, at ../src/libcore/result.rs:788)
  │ stack backtrace:
  │    0:     0x7fa9f86304ad - backtrace::backtrace::trace::h22a738598d75d447
  │    1:     0x7fa9f8630b72 - backtrace::capture::Backtrace::new::h1a277804460ccff5
  │    2:     0x7fa9f71769d3 - servo::main::_$u7b$$u7b$closure$u7d$$u7d$::h5d02d94265372533
  │    3:     0x7fa9f8bb5db5 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
  │    4:     0x7fa9f8bb5c82 - std::panicking::begin_panic::hcb11a4dc6d779ae5
  │    5:     0x7fa9f8bb5bb0 - std::panicking::begin_panic_fmt::h310416c62f3935b3
  │    6:     0x7fa9f8bb5b31 - rust_begin_unwind
  │    7:     0x7fa9f8bf368f - core::panicking::panic_fmt::hc5789f4e80194729
  │    8:     0x7fa9f840fa84 - core::result::unwrap_failed::hf5aa69a45c05e51d
  │    9:     0x7fa9f8435e87 - gfx::font_cache_thread::FontCacheThread::find_font_template::h9b98a752ba726588
  │   10:     0x7fa9f84377aa - gfx::font_context::FontContext::layout_font_group_for_style::hcc9bf0ef045ff615
  │   11:     0x7fa9f834bd4e - layout::text::TextRunScanner::scan_for_runs::h657342161e02a5d4
  │   12:     0x7fa9f751c64e - _<layout..construct..FlowConstructor<'a, ConcreteThreadSafeLayoutNode>>::build_flow_for_block_starting_with_fragments::h1fd76c1d1b62f62f
  │   13:     0x7fa9f751a997 - _<layout..construct..FlowConstructor<'a, ConcreteThreadSafeLayoutNode>>::build_flow_for_block_like::h67912ed999290e5f
  │   14:     0x7fa9f7519bad - _<layout..construct..FlowConstructor<'a, ConcreteThreadSafeLayoutNode>>::build_flow_for_block::h73a2d7f4e4e395c8
  │   15:     0x7fa9f74b3fbf - _<layout..construct..FlowConstructor<'a, ConcreteThreadSafeLayoutNode> as layout..traversal..PostorderNodeMutTraversal<ConcreteThreadSafeLayoutNode>>::process::h9c5196d0461c79d0
  │   16:     0x7fa9f74aab6a - _<layout..traversal..RecalcStyleAndConstructFlows<'lc> as style..traversal..DomTraversalContext<N>>::process_postorder::h275508dfcaaba20e
  │   17:     0x7fa9f7502722 - style::parallel::top_down_dom::hbe498c102694394c
  │   18:     0x7fa9f74c929e - std::panicking::try::do_call::h09e8c660e3e8eae6
  │   19:     0x7fa9f8bbe096 - __rust_maybe_catch_panic
  │   20:     0x7fa9f74f0cfa - _<F as alloc..boxed..FnBox<A>>::call_box::h3f3716f285c78ec5
  │   21:     0x7fa9f8bb4162 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  │   22:     0x7fa9f508e183 - start_thread
  │   23:     0x7fa9f4ba537c - clone
  │   24:                0x0 - <unknown>
  └ ERROR:servo: failed to receive response to font request: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
```

**Comment by emilio** [comment]
Seems like an spurious failure (#12872?):

```
ERROR:servo: failed to receive response to font request: IoError(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
```

@bors-servo: retry

**Comment by bholley** [comment]
Per the discussion at https://bugzilla.mozilla.org/show_bug.cgi?id=1296556#c12 , I'm not sure we need the MatchesNoRules stuff anymore. We might need it at some point though, so if you get rid of it please attach it as a patch to bug 1296556 for archival.

**Comment by bholley** [comment]
lgtm. @bors-servo delegate+

**Comment by emilio** [comment]
@bors-servo: r=bholley

 * Relevant changes landed on central.

**Pull request merged**
