### PR TITLE
Migrate mime_classifier top-level string to enum.

### PR DESCRIPTION
**Pull request by frewsxcv**
I made this branch months ago and forgot about it. Instead of just throwing the changes away, I rebased off origin/master and opened this pull request. If these changes aren't desired, no feelings hurt, just close this. If they are desired, let me know if there are any changes you want me to make and I'll also need to rewrite/squash the commits.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13411)

### CODE REVIEW

**Comment by KiChjang** [comment]
My only complaint about these changes is why isn't mime::TopLevel fully used instead? Creating a new type here looks unnecessary.

**Comment by frewsxcv** [comment]
> My only complaint about these changes is why isn't mime::TopLevel fully used instead? Creating a new type here looks unnecessary.

Addressed your complaint in the latest commits.

**Comment by jdm** [comment]
This change looks reasonable to me if squashed!

**Comment by frewsxcv** [comment]
Squashed.

**Pull request merged**
