### PR TITLE
Add transitions for CSS `calc()`.

### LINKED ISSUE #7284: Interpolation of Calc values is broken
In components/style/animation.rs, we have code for interpolating lengths.

The Interpolate impl for LengthOrPercentage and LengthOrPercentageOrAuto (and possibly others, wherever Calc is an enum option) should handle LengthOrPercentage::Calc by interpolating the absolute component and the percentage and then combining them.

E-easy? Happy to mentor.

### PR DESCRIPTION
**Pull request by notriddle**
Closes #7284

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7653)

### CODE REVIEW

**Comment by dzbarsky** [comment]
I'm surprised by the conversion of 100px to calc(100px + 0%). What do other browsers do here? 

As I remember the calc spec, they mentioned keeping values as calc even with a component of 0 would avoid issues with the function not interpolating smoothly, which would seem to imply that this should use the from state for 0-50%, and then switch to the to state.

**Comment by notriddle** [comment]
The main reason for that conversation is to support stuff like transitioning from 100px to 50%. The spec days that should work the same as transitioning from calc(100px + 0%) to calc(0px + 50%).

**Comment by notriddle** [comment]
Wrong button...

**Comment by dzbarsky** [comment]
Ok, I checked and it looks like browsers actually do this conversion thing. r=me

**Comment by dzbarsky** [comment]
I don't think bors listens to me so you'll have to get someone to trigger the merge.

**Pull request merged**
