### PR TITLE
Make the headless compositor disappear

### PR DESCRIPTION
**Pull request by nox**
This is a rebase of @notriddle's #8641.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/servo/servo/9975)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
The biggest thing I'd like to check on this is that the test times on linux-rel for the WPT and CSS tests are similar to the current headless implementation. If so, r+ from me!

**Comment by jdm** [comment]
The problem with #8641 wasn't the rebase; it was the endless stream of baffling test failures that resulted.

**Comment by notriddle** [comment]
Pretty much, yeah. I can rebase easy; the time-consuming part is
bug-hunting. There is no shortage of test failures that only show up with
headless use of the stock compositor.

**Comment by nox** [comment]
Yeah I know, that's why I pushed that branch to this repository directly, so that we don't forget about it because it also helps build times. Or at least that's what I hope and I'll see that in a few minutes.

**Comment by notriddle** [comment]
Unfortunately, the feature is still in the Cargo.toml, even though the Rust files don't use it. You should fix that, if you want to help the build times.

I haven't bothered with it yet, since there are far bigger fish to fry right now, and rather insufficient time to do it in.

**Comment by notriddle** [comment]
That bug is still there. I'm sure it's a resource leak, I just can't find it. And it doesn't show up in video mode, but is quite reproducible in headless mode.

**Comment by nox** [comment]
> Unfortunately, the feature is still in the Cargo.toml, even though the Rust files don't use it. You should fix that, if you want to help the build times.

The build times are gigantically improved even with the feature, as long as `servo-glutin` isn't rebuilt. Running `./mach build-cef` after `./mach build` now takes 4 minutes instead of 16.

**Comment by nox** [comment]
```
  │ thread '<main>' panicked at 'You should have disposed of the pixmap properly with destroy()! This pixmap will leak!', /home/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/platform/linux/surface.rs:196
```

**Comment by nox** [comment]
@notriddle rebased his PR.

**Comment by larsbergstrom** [comment]
Hrm, makes the build-cef faster, but adds 2 minutes to test-wpt and 4 minutes to test-css. I'll try to test locally, but I suspect this is still popping windows.

**Comment by notriddle** [comment]
Isn't that still a net improvement? We've shaved 12 minutes and accumulated
6.

**Comment by larsbergstrom** [comment]
@notriddle We should also be able to shave off the 12 minutes by mirroring the use of cargo features from the servo build into the CEF build (that's what's causing the extra builds now). Removing use of the headless feature entirely, as in this PR, is another way of making the cargo feature usage match.

**Pull request closed without merging**
