### PR TITLE
Worker now fires errorevent when url fetching failed, fixes #4511

### LINKED ISSUE #4511: Load errors for worker resources should dispatch an error event at the worker
According to https://html.spec.whatwg.org/multipage/workers.html#processing-model-11:
```
Attempt to fetch the resource identified by url, from the origin specified by settings object, using parent referrer source as the referrer source (not using the referrer source specified by settings object!), and with the blocking flag set and the force same-origin flag set.

If the attempt fails, then for each Worker or SharedWorker object associated with worker global scope, queue a task to fire a simple event named error at that object. Abort these steps.
```

This should be a Runnable object containing a TrustedWorkerAddress field.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #4511

### CODE REVIEW

**Comment by jdm** [comment]
Left a comment on Critic!

**Comment by jdm** [comment]
Looks good. Can you squash these together, please?

**Comment by KiChjang** [comment]
Squashed.

**Comment by KiChjang** [comment]
Shucks, I just added a newline character in `worker.rs` and squashed that commit as well.

**Pull request merged**
