### PR TITLE
Don't crash when <img> fails to parse its src

### LINKED ISSUE #11992: Youtube causes a panic
Not that youtube should be working anyway, but we shouldn't be panicking there

```
ERROR:constellation::constellation: Panic: called `Result::unwrap()` on an `Err` value: IdnaError
ERROR:constellation::constellation: Backtrace:
frame #0  - 0x0000000108a5309e - backtrace::backtrace::trace::hccde8df28b4db2a2
frame #1  - 0x0000000108a53021 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
frame #2  - 0x0000000107d17236 - _<F as alloc..boxed..FnBox<A>>::call_box::h24a37968568e1cc2
frame #3  - 0x00000001089c2c47 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hf0802d30a2c12199
frame #4  - 0x0000000108c38b54 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
frame #5  - 0x0000000108c51a96 - std::panicking::begin_panic::he426e15a3766089a
frame #6  - 0x0000000108c3a198 - std::panicking::begin_panic_fmt::hdddb415186c241e7
frame #7  - 0x0000000108c516ef - rust_begin_unwind
frame #8  - 0x0000000108c78570 - core::panicking::panic_fmt::hf4e16cb7f0d41a25
frame #9  - 0x0000000107b066a9 - core::result::unwrap_failed::hf81255c6633560f3
frame #10 - 0x0000000107babbdc - _<script..dom..htmlimageelement..HTMLImageElement as script..dom..virtualmethods..VirtualMethods>::attribute_mutated::hcd638d26442e3ffe
frame #11 - 0x0000000107b37938 - script::dom::element::Element::push_attribute::h1471b6b0f0b21238
frame #12 - 0x0000000107b37254 - script::dom::element::Element::push_new_attribute::h8194d0ae4e1a8a94
frame #13 - 0x0000000107afbff2 - script::dom::element::Element::set_attribute::h2dd6822acf689f0a
frame #14 - 0x0000000107b39b16 - script::dom::element::Element::set_string_attribute::h421bed07a514004a
frame #15 - 0x00000001077cc866 - _<script..dom..htmlimageelement..HTMLImageElement as script..dom..bindings..codegen..Bindings..HTMLImageElementBinding..HTMLImageElementMethods>::SetSrc::h6549ab1a65ae07b2
frame #16 - 0x00000001077cc7cf - std::panicking::try::call::he57edb213a93aafb
frame #17 - 0x0000000108c5477b - __rust_try
frame #18 - 0x0000000108c54715 - __rust_maybe_catch_panic
frame #19 - 0x00000001077cc635 - script::dom::bindings::codegen::Bindings::HTMLImageElementBinding::set_src::h61e2db98f3ada3bf
frame #20 - 0x000000010832e1da - CallJitSetterOp
frame #21 - 0x00000001075750ed - script::dom::bindings::utils::call_setter::h4469a2055caddbb9
frame #22 - 0x0000000107574faa - script::dom::bindings::utils::generic_call::h0e13687f0f086f31
```

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #11992

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12003)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo try

Made it more involved to follow the spec.

**Comment by Manishearth** [comment]
@Ms2ger re-r?

**Comment by Manishearth** [comment]
```

Tests with unexpected results:
  ▶ OK [expected CRASH] /html/semantics/embedded-content/the-img-element/update-the-image-data/fail-to-resolve.html

  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-img-element/update-the-image-data/fail-to-resolve.html:
  │ FAIL [expected PASS] <img srcset="//[">
  │   → assert_equals: expected "//[" but got ""
  │ FAIL [expected PASS] <img srcset="//[" src="/images/red.png">
  │   → assert_equals: expected "//[" but got "/images/red.png"
  │ FAIL [expected PASS] <img srcset="//[, /images/red.png">
  │   → assert_equals: expected "//[" but got ""
  │ 
  │ onload/</<@http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/update-the-image-data/fail-to-resolve.html:8:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1397:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ onload/<@http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/update-the-image-data/fail-to-resolve.html:7:5
  └ onload@http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/update-the-image-data/fail-to-resolve.html:6:3

  ▶ CRASH [expected OK] /html/semantics/embedded-content/the-iframe-element/change_parentage.html
  │ 
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  │ ERROR:constellation::constellation: Panic: called `Option::unwrap()` on a `None` value
  │ ERROR:constellation::constellation: Backtrace:
  │ frame #0  - 0x00007ffde53ca37d - backtrace::backtrace::trace::hccde8df28b4db2a2
  │ frame #1  - 0x00007ffde53ca305 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
  │ frame #2  - 0x00007ffde459bd99 - _<F as alloc..boxed..FnBox<A>>::call_box::ha632f6060b791d65
  │ frame #3  - 0x00007ffde53c1188 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::he2b22674ad1748f3
  │ frame #4  - 0x00007ffde54c873c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
  │ frame #5  - 0x00007ffde54e2d51 - std::panicking::begin_panic::he426e15a3766089a
  │ frame #6  - 0x00007ffde54c9faa - std::panicking::begin_panic_fmt::hdddb415186c241e7
  │ frame #7  - 0x00007ffde54e2cee - rust_begin_unwind
  │ frame #8  - 0x00007ffde55192ef - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  │ frame #9  - 0x00007ffde55195c8 - core::panicking::panic::h907815f47e914305
  │ frame #10 - 0x00007ffde43a7bf1 - script::dom::event::Event::new_uninitialized::h05ae188a870e92b9
  │ frame #11 - 0x00007ffde43af86b - script::dom::event::Event::new::h55256c8cbe9ef79e
  │ frame #12 - 0x00007ffde43f7b5c - script::dom::eventtarget::EventTarget::fire_event::h0d5b30039f5820d2
  │ frame #13 - 0x00007ffde4617caa - script::task_source::dom_manipulation::DOMManipulationTask::handle_task::h0ea31f97e475cb7a
  │ frame #14 - 0x00007ffde45a67b3 - script::script_thread::ScriptThread::handle_msg_from_script::h47e979ae1e7fb676
  │ frame #15 - 0x00007ffde45f832f - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hb50cf7fd97943b65
  │ frame #16 - 0x00007ffde45df517 - script::script_thread::ScriptThread::handle_msgs::h1e1abab71191c950
  │ frame #17 - 0x00007ffde459a487 - std::panicking::try::call::h5be47e72fadaa801
  │ frame #18 - 0x00007ffde54ecf4b - __rust_try
  │ frame #19 - 0x00007ffde54eceee - __rust_maybe_catch_panic
  │ frame #20 - 0x00007ffde459b6fd - _<F as alloc..boxed..FnBox<A>>::call_box::h3450ad306eff0e43
  │ frame #21 - 0x00007ffde54e0f14 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  │ frame #22 - 0x00007ffde1114181 - start_thread
  │ frame #23 - 0x00007ffde0c2b47c - __clone
  │ frame #24 - 0x0000000000000000 - <unknown>
  │ 
  └ ERROR:constellation::constellation: Pipeline failed in hard-fail mode.  Crashing!

  ▶ Unexpected subtest result in /html/semantics/embedded-content/the-img-element/update-the-source-set.html:
  └ PASS [expected FAIL] <img src="" data-expect="">
```

Huh, that test is OK expected CRASH _and_ FAIL expected PASS. Will look at in depth tomorrow.

**Comment by jdm** [comment]
We can remove the new test that was added, in that case.

**Comment by Manishearth** [comment]
Oh, I see, it shows up twice because the test doesn't crash anymore, but it still fails. Ready to land then, r?

@jgraham could the output here be improved? If a crashing test is updated so that subtests fail but it no longer crashes, I think we can be clearer than OK expected CRASH + FAIL expected PASS. Perhaps show FAIL expected CRASH?

**Comment by jdm** [comment]
@manishearth The overall test file expected a crash, and it now does not crash or timeout, hence OK. Some subtests now have a chance to run and fail, therefore FAIL. I don't think merging the two concepts is a good idea.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/htmlimageelement.rs, line 183 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12003#-KLqwaUkvx9XjXwA0-Hb:-KLqwaUkvx9XjXwA0-Hc:-1952452383) ([raw file](https://github.com/servo/servo/blob/9b5306f8882d2a3d3dcb5e2e630c207c30f97ddd/components/script/dom/htmlimageelement.rs#L183)):*
> ```Rust
>                         src: src.into(),
>                     });
>                     let script_chan = window.networking_task_source();
> ```

This should be the DOM manipulation task source.

---

*[tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/invalid-src.html, line 10 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12003#-KLqw9mXXCw6r1ldb9hl:-KLqw9mXXCw6r1ldb9hm:1852576462) ([raw file](https://github.com/servo/servo/blob/5d190fe4a402526f4347fe872b3234cd14d32d40/tests/wpt/web-platform-tests/html/semantics/embedded-content/the-img-element/invalid-src.html#L10)):*
> ```HTML
> <script>
> test(function() {
>     document.getElementById("myimg").src = "http://also a broken url";
> ```

This should test for the presence of error and loadend events before finishing the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12003#-:-KLqwhdKUaulDiItg76q:1458266033)*

**Comment by Manishearth** [comment]
I added a Misc dom manip task type, but we are going to be removing these enums anyway and making Runnable better.

**Pull request merged**
