### PR TITLE
Add support for structured logging with tracing

### PR DESCRIPTION
**Pull request by delan**
Previously handled by [env_logger](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/filter/struct.EnvFilter.html), RUST_LOG is now handled by the tracing [EnvFilter](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/filter/struct.EnvFilter.html), whose syntax is more restrictive. In particular, the target name in a filter directive can only contain characters in the class `[\w:-]`, which breaks our [event tracing filters](https://book.servo.org/hacking/debugging.html). This patch renames those event tracing targets as follows:

- `<` → `-from-`
- `>` → `-to-`
- `@` → `:`
- `(Foo)` → `:Foo`

For example, `servoshell<winit@NewEvents(WaitCancelled)` is now `servoshell-from-winit:NewEvents:WaitCancelled`. I’ve updated the book’s [docs about this](https://book.servo.org/hacking/debugging.html#event-tracing) in servo/book#17.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by mrobinson** [comment]
Would it make sense to switch all of Servo from `log` to `tracing`?

**Comment by delan** [comment]
> Would it make sense to switch all of Servo from `log` to `tracing`?

Probably! In fact, by default, `tracing` installs a logger that catches any logging via `log` and [turns it into tracing events](https://crates.io/crates/tracing-log). We’ll need to rework our inter-process crash logging, but that seems very doable.

**Comment by jschwe** [comment]
> Probably! In fact, by default, tracing installs a logger that catches any logging via log and [turns it into tracing events](https://crates.io/crates/tracing-log). We’ll need to rework our inter-process crash logging, but that seems very doable.

On OpenHarmony logging messages is done via `hilog`, while tracing is done via `hitrace`. I think it is similar on Android (logcat and [system tracing](https://developer.android.com/topic/performance/tracing/custom-events-native)).
I believe it is important that we retain the ability to differentiate between what goes to the normal log and what goes to the tracing backend.

The main motivation is that logging is most likely always active, but the tracing receiver only processes messages when the developer actively enabled system tracing, otherwise the events just go to /dev/null.

**Comment by delan** [comment]
Replied in [this comment](https://github.com/servo/servo/issues/33486#issuecomment-2359851826), but not longer pursuing this right now.

**Pull request closed without merging**
