### PR TITLE
Fix serialization of border-image-repeat

### PR DESCRIPTION
**Pull request by upsuper**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15173)

### CODE REVIEW

**Comment by emilio** [comment]
We implement `ToCss` on `Option<T>`? That seems bogus.

@bors-servo r+

A test would be nice for this, but I won't complain too much since we test this stuff for stylo.

**Comment by emilio** [comment]
Nevermind on the `Option<T>` comment

**Comment by upsuper** [comment]
> A test would be nice for this, but I won't complain too much since we test this stuff for stylo.

In general, I do a fix myself when:
1. the fix is trivial, and filing an issue and mentoring some random people may take even more time, and
2. it doesn't require a test, as one is only supported in Gecko product.

Because adding a test... takes much more time :)

**Comment by bholley** [comment]
Yeah, going forward Gecko coverage will test the shared Servo components, so I don't think we need to rewrite standalone tests for all the issues uncovered by the Gecko tests.

**Pull request merged**
