### PR TITLE
Initial overview of webxr initialization

### PR DESCRIPTION
**Pull request by jdm**
Every time I answer technical questions about this code I have to go and re-read a bunch of files to remind myself how they fit together. This is an attempt to capture that knowledge in a form that's easier to review.

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Comment by matlu** [comment]
Thanks for the efforts @jdm 
Can we get this added to the Servo Wiki as well. I believe WebXR & OpenXR will be a popular topic going forward?
@mrobinson Maybe coordiate the Wiki update with the fixes landed from the contributors.

**Comment by mrobinson** [comment]
> Thanks for the efforts @jdm Can we get this added to the Servo Wiki as well. I believe WebXR & OpenXR will be a popular topic going forward? @mrobinson Maybe coordiate the Wiki update with the fixes landed from the contributors.

Good point, @matlu. I've added a link at https://github.com/servo/servo/wiki/Design#webxr to the in-tree documentation, but it would be good to have only a single place for documentation like this.

**Comment by matlu** [comment]
> https://github.com/servo/servo/wiki/Design#webxr

Great first step @mrobinson  but at it is under "Design" you would not know about it without opening up design.
Great if we the main sub headings of Design could be visible in the main Wiki page e.g. like:

Design
   - Architecture
   - Description
   - Script
   - Layout
   - Compositor
   - Implementation Strategy
   - Features
      - WebXR
    - Challenges

**Comment by mrobinson** [comment]
Hi @matlu, I've done a revamp of the front page of the wiki so that the design bits are exploded out and WebXR is listed there now. I think this will make the section a lot more discoverable. It's true that there are many obsolete pages. I wonder if we can come up with a strategy for archiving them somehow.

**Comment by matlu** [comment]
> Hi @matlu, I've done a revamp of the front page of the wiki so that the design bits are exploded out and WebXR is listed there now. I think this will make the section a lot more discoverable. It's true that there are many obsolete pages. I wonder if we can come up with a strategy for archiving them somehow.

Great job Martin. Yes it looks a lot better. As mention left to do is to figure out how the "Search box" for this Github entry works.

As we have discovered when searching for WebXR it will not find our nice new section and instead find an obsolete 6 year old wiki post.

image

**Comment by matlu** [comment]
Maybe we can raise a topic under general on Zulip Chat and once there is some feedback/recommendations create a a new issue.
@mrobinson 

**What is needed I believe is:**
1. Find a few to archieve old and obosolete Wiki entries (maybe they can be moved to a "Legacy Wiki"? 
Looks like there are 370(!) pages?

2. Run a reindexing of https://github.com/servo/servo.wiki.git
(I think this should be done before 1 so at least the new entries will be included in search results).

3. Once obsolete pages have been moved to "Leagacy Wiki/Archived", run a new reindex to avoid getting search results for obsolete stuff.

**Pull request merged**
