### PR TITLE
touchlist dom api #8225

### LINKED ISSUE #8225: Implement Document.createTouchList
Spec: https://w3c.github.io/touch-events/#widl-Document-createTouchList-TouchList-Touch-touches and https://w3c.github.io/touch-events/#idl-def-Document

We started implementing support for touch events on websites recently, and some websites want to use an API that we don't implement yet. We need to add the declaration to the WebIDL (next to `createTouchEvent`), and add the corresponding Rust method to the `Document` implementation that returns a new `TouchList` object. There's an example of doing this in `handle_touch_event`.

Code: components/script/dom/webidls/Document.webidl, components/script/dom/document.rs
Test: `./mach test-wpt tests/wpt/web-platform-tests/touch-events/create-touch-touchlist.html`

### PR DESCRIPTION
**Pull request by k-cross**
Sorry for the wait, I just finished my finals.

Fixes #8225

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9025)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r- force

Actually sorry, the spec link is wrong, it should be https://w3c.github.io/touch-events/#idl-def-document-createtouchlist(touch...).

**Comment by KiChjang** [comment]
```

Ran 3736 tests finished in 209.0 seconds.
  • 3735 ran as expected. 709 tests skipped.
  • 1 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/css/abs-overflow-stackingcontext.html
  └   → /_mozilla/css/abs-overflow-stackingcontext.html d9d9e489bc5b4508c01b06c7ff92f19dcc2ece3c
/_mozilla/css/abs-overflow-stackingcontext_ref.html 38ce16767330b708ec4459a742a7122c37307f64
Testing d9d9e489bc5b4508c01b06c7ff92f19dcc2ece3c == 38ce16767330b708ec4459a742a7122c37307f64
```

**Pull request merged**
