### PR TITLE
Remove is_some() from mime_classifier.rs

### PR DESCRIPTION
**Pull request by pyfisch**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6450)

### CODE REVIEW

**Comment by metajack** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/mime_classifier.rs, line 90 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6450#-JsX6XgD1M8heGwnyI6c)** ([raw file](https://github.com/servo/servo/blob/e59013c857817c14aee3f23b5e22817be7e17e3d/components/net/mime_classifier.rs#L90)):</sup>
nit: None should be on its own line. I'd put the first `.or_else` immediately after the closing brace.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6450)

**Comment by metajack** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6450)

**Comment by metajack** [comment]
-S-awaiting-review +S-needs-squash 

Looks good. Squash and I'll r+.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6450)

**Comment by pyfisch** [comment]
<sup>**[components/net/mime_classifier.rs, line 90 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6450#-JsX6XgD1M8heGwnyI6c)** ([raw file](https://github.com/servo/servo/blob/e59013c857817c14aee3f23b5e22817be7e17e3d/components/net/mime_classifier.rs#L90)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6450)

**Comment by pyfisch** [comment]
squashed

**Comment by metajack** [comment]
@bors-servo r+

-S-awaiting-review -S-needs-squash +S-awaiting-merge 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6450)

**Pull request merged**
