### PR TITLE
Remove Origin::unicode_serialization

### LINKED ISSUE #20701: Remove usage of Unicode serialisation of origins
https://html.spec.whatwg.org/multipage/#ascii-serialisation-of-an-origin

> There used to also be a Unicode serialization of an origin. However, it was never widely adopted.

### PR DESCRIPTION
**Pull request by Eijebong**
Fixes #20701

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21927)

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /url/a-element-origin.html:
  └ PASS [expected FAIL] Parsing origin: <http://\u4f60\u597d\u4f60\u597d> against <http://other.com/>

  ▶ Unexpected subtest result in /url/a-element-origin.html:
  └ PASS [expected FAIL] Parsing origin: <ftp://%e2%98%83> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-origin.html:
  └ PASS [expected FAIL] Parsing origin: <https://%e2%98%83> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-origin-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing origin: <http://\u4f60\u597d\u4f60\u597d> against <http://other.com/>

  ▶ Unexpected subtest result in /url/a-element-origin-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing origin: <ftp://%e2%98%83> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-origin-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing origin: <https://%e2%98%83> against <about:blank>
```

**Comment by Eijebong** [comment]
Fixed expectations

**Comment by jdm** [comment]
@bors-servo retry
* #21067

**Pull request merged**
