### PR TITLE
Bump serde to 0.7

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10049)

### CODE REVIEW

**Comment by nox** [comment]
```
   Compiling plugins v0.0.1 (file:///home/servo/buildbot/slave/gonk/build/components/plugins)
   Compiling webrender v0.1.0 (https://github.com/servo/webrender#0ef2972e)
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:708:23: 708:38 error: unresolved name `gl::gen_queries` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:708         let queries = gl::gen_queries(4);
                                                                                                           ^~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:708:23: 708:38 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:719:25: 719:41 error: unresolved name `gl::TIME_ELAPSED` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:719         gl::begin_query(gl::TIME_ELAPSED, qid);
                                                                                                             ^~~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:719:25: 719:41 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:719:9: 719:24 error: unresolved name `gl::begin_query` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:719         gl::begin_query(gl::TIME_ELAPSED, qid);
                                                                                             ^~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:719:9: 719:24 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:723:23: 723:39 error: unresolved name `gl::TIME_ELAPSED` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:723         gl::end_query(gl::TIME_ELAPSED);
                                                                                                           ^~~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:723:23: 723:39 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:723:9: 723:22 error: unresolved name `gl::end_query` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:723         gl::end_query(gl::TIME_ELAPSED);
                                                                                             ^~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:723:9: 723:22 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:742:46: 742:72 error: unresolved name `gl::QUERY_RESULT_AVAILABLE` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:742         if gl::get_query_object_iv(last_qid, gl::QUERY_RESULT_AVAILABLE) == 1 {
                                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:742:46: 742:72 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:742:12: 742:35 error: unresolved name `gl::get_query_object_iv` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:742         if gl::get_query_object_iv(last_qid, gl::QUERY_RESULT_AVAILABLE) == 1 {
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:742:12: 742:35 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:743:50: 743:66 error: unresolved name `gl::QUERY_RESULT` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:743             gl::get_query_object_ui64v(last_qid, gl::QUERY_RESULT)
                                                                                                                                      ^~~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:743:50: 743:66 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:743:13: 743:39 error: unresolved name `gl::get_query_object_ui64v` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:743             gl::get_query_object_ui64v(last_qid, gl::QUERY_RESULT)
                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:743:13: 743:39 help: run `rustc --explain E0425` to see a detailed explanation
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:752:9: 752:27 error: unresolved name `gl::delete_queries` [E0425]
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:752         gl::delete_queries(&self.gl_queries);
                                                                                             ^~~~~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/webrender-ec406de34643a7ef/master/src/device.rs:752:9: 752:27 help: run `rustc --explain E0425` to see a detailed explanation
   Compiling servo-fontconfig v0.2.0
error: aborting due to 10 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `webrender`.
```

Cc @pcwalton, some cfg attributes are missing.

**Comment by Ms2ger** [comment]
You moved webrender and webrender_traits back from tip; revert that?

**Comment by Ms2ger** [comment]
https://github.com/servo/servo/pull/10055

**Pull request closed without merging**
