### PR TITLE
Freeze old pipeline in iframes

### PR DESCRIPTION
**Pull request by paulrouget**
Fixes https://github.com/servo/servo/issues/8673 and part of https://github.com/servo/servo/issues/8674

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8886)

### CODE REVIEW

**Comment by paulrouget** [comment]
Could someone tell me where I should write a test?

**Comment by Ms2ger** [comment]
Sorry, wrong button.

Add a test under `tests/wpt/mozilla`? If you're using mozbrowser, maybe create a new subdirectory for it. You may need to set prefs, these are in the metadata directory

**Comment by paulrouget** [comment]
I didn't manage to properly test the frozen state of the iframe. This test crashes without this patch though.

**Comment by mbrubeck** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8886)*

**Comment by mbrubeck** [comment]
```
  ▶ CRASH [expected TIMEOUT] /html/browsers/browsing-the-web/navigating-across-documents/002.html
  │ 
  │ thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'ScriptTask: received freeze msg for a
  │                     pipeline ID not associated with this script task. This is a bug.', ../src/libcore/option.rs:335
  │ stack backtrace:
  │    1:        0x10ea2d178 - sys::backtrace::tracing::imp::write::hca66179add43b2e5lLt
  │    2:        0x10ea2f23f - panicking::log_panic::_<closure>::closure.40842
  │    3:        0x10ea2ece2 - panicking::log_panic::h7a04edac7e1f2797HEx
  │    4:        0x10ea1aaf6 - sys_common::unwind::begin_unwind_inner::h39a94087039ae0efnOs
  │    5:        0x10ea1aede - sys_common::unwind::begin_unwind_fmt::h7be0824d83765cd5tNs
  │    6:        0x10ea2c797 - rust_begin_unwind
  │    7:        0x10ea518a0 - panicking::panic_fmt::h871c0ef100fda9e9LFK
  │    8:        0x10dc99bc8 - script_task::_<impl>::handle_msg_from_constellation::h48e9f2652a337bc5D02
  │    9:        0x10dc9539e - script_task::_<impl>::handle_msgs::_<closure>::closure.158717
  │   10:        0x10dc7e39d - script_task::_<impl>::handle_msgs::h09234e46a6f77ec4LP2
  │   11:        0x10dc46017 - sys_common::unwind::try::try_fn::try_fn::h14806146711523557709
  │   12:        0x10ea2c5b8 - __rust_try
  │   13:        0x10ea296be - sys_common::unwind::try::inner_try::h819d2da8e3dc4516VKs
  │   14:        0x10dc47a61 - boxed::_<impl>::call_box::call_box::h13042718455976863970
  │   15:        0x10ea2e4cd - sys::thread::_<impl>::new::thread_start::h328957c252b95d3cOYw
  │   16:     0x7fff84ed8059 - _pthread_body
  │   17:     0x7fff84ed7fd6 - _pthread_start
  └ Pipeline failed in hard-fail mode.  Crashing!
```

**Comment by paulrouget** [comment]
The issue was that the page was getting a freeze message while it was not created yet. Latest commit address this issue.

**Comment by jdm** [comment]
@bors-servo: r+
That solution looks good to me. Thanks!

**Pull request merged**
