### PR TITLE
Make Document store Ranges, and update ranges in Node subclasses

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6817)

### CODE REVIEW

**Comment by dzbarsky** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 861 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6817#-JvMG83SO9iW8wCJJOu1)** ([raw file](https://github.com/servo/servo/blob/48a75fe4a16a9ca78bc3f983ea474ad25492440b/components/script/dom/range.rs#L861)):</sup>
I think I had to disable these because the node algorithms like to set ranges to values that are currently invalid, but will become valid after the end of the algorithm. Thoughts on just removing these lines?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6817)

**Comment by nox** [comment]
I'm doing this differently already, with weak references and a vector per Node. Which way should we go?

**Comment by dzbarsky** [comment]
This is what we talked about before, right? It's still not clear to me what we gain by storing ranged on a per-node basis.

For the Range updating steps in this PR, we need to be able to look up Ranges that start or end with a given node, as well as Ranges whose start or end node's descendant is a given node. This seems pretty complex to implement when Ranges are stored on various nodes.  But if you have ideas for how to do this, let me know!

If we can't figure this out, we should do weak refs and vector per Document, so we can actually follow the spec and do the right thing

**Comment by nox** [comment]
@dzbarsky I introduce an unbinding context which contains the necessary information about the inclusive ancestor that was removed (its index, more or less). Still, I'm going to read through the code in this PR.

**Comment by nox** [comment]
@dzbarsky Did you have the time to look at my other branch? Which way do you think we should go?

**Comment by dzbarsky** [comment]
@nox yeah I looked briefly, let's do it your way. It ended up being nicer than I expected. Not sure if I'll have time to review it in detail in the near future though.

**Pull request closed without merging**
