### PR TITLE
Update Servo user agent strings

### PR DESCRIPTION
**Pull request by atouchet**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Review by sagudev — COMMENTED** [review]
I think last update was done in SM bump (not by me). It would make sense to continue to follow this pattern and because we are following ESR versions, websites should be happy too.

**Comment by atouchet** [comment]
No I did the last version update in #29563 and it tracked the latest Firefox release at the time. I do not believe we've ever bothered to align the user agent strings in Servo with Firefox ESR.

**Comment by atouchet** [comment]
For whatever it's worth I'm not entirely opposed to matching Firefox ESR, I mostly just want to use a version that won't run into website compatibility problems. As far as I'm aware the rest of the various Firefox components used in Servo (ex. Stylo, WebRender) aren't kept in sync with ESR either.

**Comment by atouchet** [comment]
I suppose that using a version number later than the SpiderMonkey version in use could cause potential compatibility issues. I have pushed a commit to switch to the latest ESR version 128.

**Review by sagudev — APPROVED** [review]

**Pull request merged**
