### PR TITLE
Upgrade a bunch of dependencies

### PR DESCRIPTION
**Pull request by mbrubeck**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10944)

### CODE REVIEW

**Comment by perlun** [comment]
@mbrubeck, seems to fail on Travis:

```
   Compiling script_tests v0.0.1 (file:///home/travis/build/servo/servo/tests/unit/script)
   Compiling layout v0.0.1 (file:///home/travis/build/servo/servo/components/layout)

<std macros>:5:8: 5:33 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
<std macros>:5 if ! ( * left_val == * right_val ) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
<std macros>:5:8: 5:33 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:5:8: 5:33 help: run `rustc --explain E0282` to see a detailed explanation

error: aborting due to previous error
Build failed, waiting for other jobs to finish...

error: Could not compile `script_tests`.
To learn more, run the command again with --verbose.
```

**Comment by jdm** [comment]
That's a terrible error message :( At least we know it's in `tests/unit/script`...

**Comment by mbrubeck** [comment]
Added type annotations to fix the script_tests build error.

**Comment by mbrubeck** [comment]
@bors-servo r=frewsxcv

* x11 2.5.0 has a bug on platforms where c_char is u8.  Reverted that for now.

**Comment by mbrubeck** [comment]
Filed Daggerbot/x11-rs#41.

The latest build failure is an infrastructure problem with the Mac builder. Not retrying yet because the builder seems to be in a bad state still.

**Pull request merged**
