### PR TITLE
Implement Document charset

### LINKED ISSUE #7718: Implement Document#charset.
Blocks #2185.

* Spec: <https://dom.spec.whatwg.org/#dom-document-charset>.
* Code: `components/script/dom/document.rs`, `components/script/dom/webidls/Document.webidl`.
* Test: `dom/interfaces.html`, `dom/nodes/DOMImplementation-createDocument.html`, `dom/nodes/DOMImplementation-createHTMLDocument.html`, `dom/nodes/Document-characterSet-normalization.html`, `dom/nodes/Document-constructor.html`, `dom/nodes/Node-properties.html`, `domparsing/DOMParser-parseFromString-html.html`, `domparsing/DOMParser-parseFromString-xml.html`, `html/dom/interfaces.html`, (possibly) `dom/historical.html`                                                  .

### PR DESCRIPTION
**Pull request by KiChjang**
Rebase of #7966.

Fixes #7718.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9036)

### CODE REVIEW

**Comment by vectorijk** [comment]
lgtm @KiChjang

**Comment by nox** [comment]
You should squash the two commits, but I can understand keeping them separate if you want to keep the creds.

**Comment by Ms2ger** [comment]
This is okay, but please do squash.

**Comment by KiChjang** [comment]
@bors-servo retry
* #7846

**Pull request merged**
