### PR TITLE
Use the whitespace flag in each glyph instead of going to the string for whitespace stripping.

### PR DESCRIPTION
**Pull request by pcwalton**
`str::slice_chars` was O(n) and #2 in the profile.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8994)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/gfx/text/text_run.rs, line 146 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8994#-K5eV2wii0V9bNcIqr0_:-K5eV2wii0V9bNcIqr0a:175477616) ([raw file](https://github.com/servo/servo/blob/6614aef5230cb41cb684cd2dc472150935397de6/components/gfx/text/text_run.rs#L146)):*
Or `self.prev_glyph_run.take()`

---

*[components/gfx/text/text_run.rs, line 176 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8994#-K5eVGYbcIy5YEAoE0wS:-K5eVGYbcIy5YEAoE0wT:449665341) ([raw file](https://github.com/servo/servo/blob/6614aef5230cb41cb684cd2dc472150935397de6/components/gfx/text/text_run.rs#L176)):*
`take()`

---

*[components/gfx/text/text_run.rs, line 181 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8994#-K5eVJBsii3iW-dFbfnW:-K5eVJBsii3iW-dFbfnX:5173792) ([raw file](https://github.com/servo/servo/blob/6614aef5230cb41cb684cd2dc472150935397de6/components/gfx/text/text_run.rs#L181)):*
Rm

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8994)*

**Comment by pcwalton** [comment]
Comments addressed.

**Comment by mbrubeck** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8994)*

**Comment by jdm** [comment]
@pcwalton, can you reproduce these locally?

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css21_dev/html4/block-non-replaced-width-007.htm
  └   → /css21_dev/html4/block-non-replaced-width-007.htm eb195905e02d7943de70d2b8ac617e074179e996
/css21_dev/html4/reference/block-non-replaced-width-007-ref.htm 47ad8313feacfb8add7c5d1c014c7975027bf5b7
Testing eb195905e02d7943de70d2b8ac617e074179e996 == 47ad8313feacfb8add7c5d1c014c7975027bf5b7

  ▶ PASS [expected FAIL] /css21_dev/html4/floats-wrap-bfc-002-right-table.htm
```

**Comment by jdm** [comment]
@pcwalton This had test failures. Are you planning to investigate them, or should we close the PR?

**Comment by pcwalton** [comment]
I'll look at them.

**Comment by jdm** [comment]
Filed #9955 to keep track of this. Feel free to reopen it when you end up making progress.

**Pull request closed without merging**
