### PR TITLE
Implement Range#cloneContents

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6625)

### CODE REVIEW

**Comment by jdm** [comment]
This is missing test expectation changes.

**Comment by Ms2ger** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 65 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuNTd7fYAqk_IKSwqIP)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/components/script/dom/range.rs#L65)):</sup>
`&self` is more idiomatic

---

<sup>**[components/script/dom/range.rs, line 69 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuNWIPCqY6cQaOQbud2)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/components/script/dom/range.rs#L69)):</sup>
The spec also has a check for the roots; isn't that necessary? It seems like we might crash if that fails.

---

<sup>**[components/script/dom/range.rs, line 73 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuNVrjjJeBoG68HtxEo)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/components/script/dom/range.rs#L73)):</sup>
No real need for the blocks

---

<sup>**[components/script/dom/range.rs, line 338 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuNXU-eSV_MNJutplfP)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/components/script/dom/range.rs#L338)):</sup>
I guess it doesn't matter whether you pass true or false, since a `CharacterData` node can't have children. Maybe this warrants a comment?

---

<sup>**[components/script/dom/range.rs, line 341 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuNWzCoSQ0fmOPzVVjK)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/components/script/dom/range.rs#L341)):</sup>
Match on `CharacterDataCast::to_ref` rather than `end_node.r().type_id()`; that saves an `unwrap()`.

And use `if let` rather than a match.

---

<sup>**[components/script/dom/range.rs, line 358 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuNZ58O5Eyel6pz1A_J)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/components/script/dom/range.rs#L358)):</sup>
This is the definition of common ancestor container (<https://github.com/whatwg/dom/issues/56>).

---

<sup>**[components/script/dom/range.rs, line 394 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuN_OXi-hKGE-bfPx4r)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/components/script/dom/range.rs#L394)):</sup>
Ditto about if let/cast.

---

<sup>**[components/script/dom/range.rs, line 396 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuN_TRjeuhtqJQBTZIH)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/components/script/dom/range.rs#L396)):</sup>
Add an assertion that the note is correct?

> Note: In this case, first partially contained child is original start node.

---

<sup>**[tests/wpt/web-platform-tests/dom/ranges/Range-cloneContents.html, line 49 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuNTjijAs2MEpHsTSvr)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/tests/wpt/web-platform-tests/dom/ranges/Range-cloneContents.html#L49)):</sup>
Nit: no space

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6625)

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 69 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6625#-JuNWIPCqY6cQaOQbud2)** ([raw file](https://github.com/servo/servo/blob/18fa0a081278902aea4c73f5a0596cdafd026cc6/components/script/dom/range.rs#L69)):</sup>
Will tweak this but we don't need to check the roots, a bp_position return of None signals the nodes aren't connected and we end up walking the ancestors in Node.CompareDocumentPosition anyway.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6625)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Reviewed 4 of 4 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6625)

**Comment by jdm** [comment]
@bors-servo: retry
* #6644

**Pull request merged**
