### PR TITLE
Start accepting correct parameters for the Blob constructor

### PR DESCRIPTION
**Pull request by tbu-**
Touches #8397.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/servo/servo/9977)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I think we should apply my suggestion from https://github.com/w3c/FileAPI/issues/30, and probably have some tests.

**Comment by KiChjang** [comment]
@tbu- I'm not too happy about not communicating with us when the issue is explicitly marked as assigned to another person. Please try to comment on the issue that you want to work on next time.

**Comment by tbu-** [comment]
I'm sorry. I found this issue via http://servo.github.io/servo-starters/ and thought that it looked abandoned (last activity over a month ago), so I thought I'd pick it up.

**Pull request closed without merging**
