### PR TITLE
Partially implement getter of Document

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5921)

### CODE REVIEW

**Comment by nox** [comment]
Blocked by https://github.com/w3c/web-platform-tests/pull/1801.

**Comment by nox** [comment]
The two commits "make id attribute use an atom" should be "make name attribute use an atom", will reword once reviewed.

**Comment by jdm** [comment]
Why is the last commit removing WPT test files?

**Comment by nox** [comment]
Because I'm stupid and fail at git-rm'ing.

**Comment by nox** [comment]
@jdm I restored the tests and removed the expected results as they now pass (with my WPT PR).

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/script/dom/document.rs @ r5
- components/script/dom/htmlappletelement.rs @ r2
- components/script/dom/htmlbodyelement.rs @ r1
- components/script/dom/htmlbuttonelement.rs @ r1
- components/script/dom/htmldialogelement.rs @ r1
- components/script/dom/htmlfieldsetelement.rs @ r1
- components/script/dom/htmlformelement.rs @ r4
- components/script/dom/htmlimageelement.rs @ r3
- components/script/dom/htmlmetaelement.rs @ r1
- components/script/dom/htmlobjectelement.rs @ r1
- components/script/dom/htmloptgroupelement.rs @ r1
- components/script/dom/htmloptionelement.rs @ r1
- components/script/dom/htmlselectelement.rs @ r1
- components/script/dom/macros.rs @ r1, r2
- components/script/dom/virtualmethods.rs @ r2, r4
- components/script/dom/webidls/Document.webidl @ r5
- components/script/dom/webidls/HTMLAppletElement.webidl @ r2
- tests/wpt/metadata/html/dom/documents/dom-tree-accessors/nameditem-01.html.ini @ r5
- tests/wpt/metadata/html/dom/documents/dom-tree-accessors/nameditem-03.html.ini @ r5
- tests/wpt/metadata/html/dom/documents/dom-tree-accessors/nameditem-04.html.ini @ r5
- tests/wpt/metadata/html/dom/documents/dom-tree-accessors/nameditem-06.html.ini @ r5
- tests/wpt/metadata/html/dom/interfaces.html.ini @ r2
- tests/wpt/metadata/html/dom/reflection-obsolete.html.ini @ r2

---

<sup>**[components/script/dom/document.rs, line 93 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5921#-JoeF5RjOCHbjnr6nixx)** ([raw file](https://github.com/servo/servo/blob/ca94e9c364b58c6a665d77e6396112c16752ec8a/components/script/dom/document.rs#L93)):</sup>
nit: std::sync comes after std::ptr

---

<sup>**[components/script/dom/document.rs, line 1607 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5921#-JoeFbfui-bTGP4Uu-FJ)** ([raw file](https://github.com/servo/servo/blob/ca94e9c364b58c6a665d77e6396112c16752ec8a/components/script/dom/document.rs#L1607)):</sup>
Why this block?

---

<sup>**[components/script/dom/webidls/Document.webidl, line 84 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5921#-JoeEzMLdUIs0EAa7l3i)** ([raw file](https://github.com/servo/servo/blob/ca94e9c364b58c6a665d77e6396112c16752ec8a/components/script/dom/webidls/Document.webidl#L84)):</sup>
nit: leave the extra space after the //

---

<sup>**[components/script/dom/webidls/HTMLAppletElement.webidl, line 15 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5921#-JoeEBaURj_FlJ9SjhZm)** ([raw file](https://github.com/servo/servo/blob/9b5564a178fa222ff8f616bc1702e3185082865c/components/script/dom/webidls/HTMLAppletElement.webidl#L15)):</sup>
nit: it's preferable to leave the spacing as-is and just remove the //.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5921)

**Comment by nox** [comment]
<sup>**[components/script/dom/document.rs, line 1607 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5921#-JoeFbfui-bTGP4Uu-FJ)** ([raw file](https://github.com/servo/servo/blob/ca94e9c364b58c6a665d77e6396112c16752ec8a/components/script/dom/document.rs#L1607)):</sup>
Because `elements` borrows `name`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5921)

**Comment by jdm** [comment]
-S-needs-code-changes +S-needs-squash 

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5921)

**Comment by jdm** [comment]
```
/html/dom/documents/dom-tree-accessors/nameditem-06.html
--------------------------------------------------------
FAIL If there are two imgs, nothing should be returned. (id)
```

**Comment by nox** [comment]
@jdm It needs https://github.com/w3c/web-platform-tests/pull/1801, was WPT updated?

**Comment by jdm** [comment]
Whoops; not yet.

**Pull request merged**
