### PR TITLE
[Do not merge] Add steps for windows-dev-yaml

### PR DESCRIPTION
**Pull request by aneeshusa**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because that is #13838 

The new Buildbot configuration that reads steps from the servo repo
is currently failing on Windows, so add steps for a Windows test
builder to allow ironing out the kinks.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13844)

### CODE REVIEW

**Comment by aneeshusa** [comment]
I don't think this needs to actually be merged, I should be able to test things out via try builds.

**Comment by aneeshusa** [comment]
@bors-servo try

- servo/saltfs#517 merged, is deployed and seems to be working

**Comment by aneeshusa** [comment]
@bors-servo retry
- the annoying git

**Comment by larsbergstrom** [comment]
@bors-servo retry
- servo-linux2 out of disk space

**Comment by aneeshusa** [comment]
This produced some successful `windows-dev-yaml` builds, so it looks like the saltfs dynamic steps work on Windows now, too. Watch https://github.com/servo/saltfs/pull/522 for future updates.

**Pull request closed without merging**
