### PR TITLE
Enable sccache

### LINKED ISSUE #17106: Enable sccache for Servo CI
I've been testing sccache with Servo lately, and it's working pretty well for caching crate compilation. Details are available on [this users.rlo thread](https://users.rust-lang.org/t/sccache-for-caching-rust-compilation/10960). I needed to make one change to an upstream crate, and I finally submitted [a PR to update that dependency](https://github.com/servo/servo/pull/17094) which has now been merged.

Unless large chunks of the dependency graph change frequently I would expect a pretty good cache hit rate, which should save a fair amount of time for CI builds. Additionally, once we get S3 buckets configured we can set `[build] ccache = 'sccache'` and use sccache to cache the C++ compilation from the build, which may produce better results than using ccache, since multiple builders can share the same cache.

cc/ @alexcrichton @edunham @larsbergstrom

### PR DESCRIPTION
**Pull request by aneeshusa**
Update buildbot_steps lint to handle env variables.
Enable sccache for all builds.

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #17106  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they update the test commands

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17171)

### CODE REVIEW

**Comment by aneeshusa** [comment]
r? @wafflespeanut for the servo-tidy bits
r? @larsbergstrom for the sccache bits

cc @luser, will this "just work" for cross builds as well?

Requires servo/saltfs#687 and servo/saltfs#688 to be deployed.

**Comment by luser** [comment]
> cc @luser, will this "just work" for cross builds as well?

sccache only caches rlib/staticlib rustc output, and it uses the full rustc commandline as input to the cache key hash, so there should be no problems there.

**Comment by SimonSapin** [comment]
Where is the cache stored? Currently we remove any `.gitignore`’d or untracked file/directory in the repo at the start of every build.

**Comment by aneeshusa** [comment]
The default location depends on the OS, but isn't in the build directory:
```
By default it will use a sensible location for the current platform:
~/.cache/sccache on Linux,
%LOCALAPPDATA%\Mozilla\sccache on Windows,
~/Library/Caches/sccache on OS X.
```

We'll also want to enable the S3 backend at some point for better even caching.

**Comment by luser** [comment]
Do you have more than one builder per architecture? If so you should get S3 storage setup so they can share a cache for better hit rates. It's not very complicated, you just need and S3 bucket configured to be default publicly-readable.

**Comment by larsbergstrom** [comment]
lgtm, but blocked on https://github.com/servo/saltfs/pull/688 rebase + deployment to get the `sccache` binary on the machines.

**Comment by aneeshusa** [comment]
servo/saltfs#688 has been deployed.

@bors-servo try

**Comment by jdm** [comment]
I suspect we need to force an upgrade of sccache on the builders.

**Comment by aneeshusa** [comment]
The build logs are no longer available, let's get some fresh ones.
@bors-servo retry

**Comment by aneeshusa** [comment]
Filed https://github.com/mozilla/sccache/issues/209 to ask for newer static binary releases of sccache.

**Comment by jdm** [comment]
Rebased in #19835.

**Pull request closed without merging**
