### PR TITLE
Update offscreen_gl_context

### PR DESCRIPTION
**Pull request by emilio**
cc: https://github.com/ecoal95/rust-offscreen-rendering-context/pull/46

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9044)

### CODE REVIEW

**Comment by jdm** [comment]
Travis is having trouble finding the new EGL library that's being linked.

**Comment by ecoal95** [comment]
Updated the travis deps it so it should link.

We can wall it behind a feature flag in `offscreen_gl_context`, but if I'm not wrong the student work which is taking care of #7484 or wayland users will need it anyway.

**Comment by ecoal95** [comment]
Heh, I saw this coming from too far away.

@jdm is there any possibility to install EGL in the buildbots? Or is it preferable to hide the link behind a feature flag or similar for now, and see how #7484 goes?

**Comment by jdm** [comment]
@ecoal95 https://github.com/servo/saltfs/blob/master/servo-dependencies.sls#L36

**Comment by KiChjang** [comment]
@bors-servo try

Weird, I could've sworn I've seen your name on saltfs...

**Comment by ecoal95** [comment]
@KiChjang Yes, I have try access. Something is broken I think.

Just for posterity's sake, looking at http://build.servo.org/waterfall I get:

```
web.Server Traceback (most recent call last):
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'sqlalchemy.exc.OperationalError'>: (OperationalError) disk I/O error u'SELECT changes.changeid \nFROM changes ORDER BY changes.changeid DESC\n LIMIT ? OFFSET ?' (40, 0) /usr/lib/python2.7/threading.py:783:__bootstrap /usr/lib/python2.7/threading.py:810:__bootstrap_inner /usr/lib/python2.7/threading.py:763:run --- <exception caught here> --- /usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py:196:_worker /usr/local/lib/python2.7/dist-packages/twisted/python/context.py:118:callWithContext /usr/local/lib/python2.7/dist-packages/twisted/python/context.py:81:callWithContext /usr/local/lib/python2.7/dist-packages/buildbot/db/pool.py:191:__thd /usr/local/lib/python2.7/dist-packages/buildbot/db/changes.py:154:thd /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1449:execute /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1584:_execute_clauseelement /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1698:_execute_context /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1691:_execute_context /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:331:do_execute ]]
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'sqlalchemy.exc.OperationalError'>: (OperationalError) disk I/O error u'SELECT changes.changeid \nFROM changes ORDER BY changes.changeid DESC\n LIMIT ? OFFSET ?' (40, 0) /usr/lib/python2.7/threading.py:783:__bootstrap /usr/lib/python2.7/threading.py:810:__bootstrap_inner /usr/lib/python2.7/threading.py:763:run --- <exception caught here> --- /usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py:196:_worker /usr/local/lib/python2.7/dist-packages/twisted/python/context.py:118:callWithContext /usr/local/lib/python2.7/dist-packages/twisted/python/context.py:81:callWithContext /usr/local/lib/python2.7/dist-packages/buildbot/db/pool.py:191:__thd /usr/local/lib/python2.7/dist-packages/buildbot/db/changes.py:154:thd /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1449:execute /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1584:_execute_clauseelement /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1698:_execute_context /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1691:_execute_context /usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:331:do_execute ]]
```

**Pull request merged**
