### PR TITLE
style: Let overflow parse two values.

### PR DESCRIPTION
**Pull request by emilio**
Per https://github.com/w3c/csswg-drafts/issues/2484.

Bug: 1453148
Reviewed-by: xidorn
MozReview-Commit-ID: D7M3PhnTtD2

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20627)

### CODE REVIEW

**Comment by CYBAI** [comment]
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "overflow is expected to be overflow: scroll hidden;", "test": "/css/cssom/index-002.html", "line": 63106, "action": "test_result", "expected": "FAIL"}
```

**Comment by emilio** [comment]
(Thanks @CYBAI :P)

**Pull request merged**
