### PR TITLE
Upgrade to rustc 1.40.0-nightly (246be7e1a 2019-10-25)

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by jdm** [comment]
script_plugins isn't building correctly.

**Comment by SimonSapin** [comment]
This is because compiler crates used by compiler plugins have been moved out of the `rust-std` component in rustup and into a new `rustc-dev` component. I’ve pushed another commit to install that.

**Comment by jdm** [comment]
The scrupt_plugins for the taskcluster tidy/unit job is still broken.

**Comment by SimonSapin** [comment]
Ah, pre-review testing of PRs was yet another code path in `decision_task.py`. That’s a bit unfortunate.

**Pull request merged**
