### PR TITLE
Add a smoketest to Windows CI

### PR DESCRIPTION
**Pull request by jdm**
This test runs Servo, then loads a page that waits until the onload event and closes the window. If anything crashes while this happens, the smoketest should be classified as a failure.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20217)

### CODE REVIEW

**Comment by atouchet** [comment]
Why is servo-glutin 0.14.2 being used here? Isn't going to re-break the Windows build?

**Comment by jdm** [comment]
Yes. The point is to verify that the smoketest would have picked up the crash; I'll remove the commit before merging.

**Comment by jdm** [comment]
Success!
```
Failed to create window.: OsError("CreateWindowEx function failed: The operation completed successfully. (os error 0)") (thread main, at libcore\result.rs:916)
stack backtrace:
   0:      0x7f7baca1d08 - backtrace::backtrace::trace<closure>
                        at C:\buildbot\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.2\src\backtrace\mod.rs:41
   1:      0x7f7bac9e404 - backtrace::capture::Backtrace::new
                        at C:\buildbot\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.2\src\capture.rs:64
   2:      0x7f7b59813da - servo::main::{{closure}}
                        at c:\buildbot\slave\windows-msvc-dev\build\ports\servo\main.rs:147
   3:      0x7f7bacc5ebd - std::panicking::rust_panic_with_hook
                        at C:\projects\rust\src\libstd\panicking.rs:577
   4:      0x7f7bacc5d21 - std::panicking::begin_panic<alloc::string::String>
                        at C:\projects\rust\src\libstd\panicking.rs:537
   5:      0x7f7bacc5c02 - std::panicking::begin_panic_fmt
                        at C:\projects\rust\src\libstd\panicking.rs:521
   6:      0x7f7bacc5b7a - std::panicking::rust_begin_panic
                        at C:\projects\rust\src\libstd\panicking.rs:497
   7:      0x7f7bacdf7fd - core::panicking::panic_fmt
                        at C:\projects\rust\src\libcore\panicking.rs:71
   8:      0x7f7b599bb27 - core::result::unwrap_failed<glutin::CreationError>
                        at C:\projects\rust\src\libcore\macros.rs:23
   9:      0x7f7b599892e - core::result::Result<glutin::Window, glutin::CreationError>::expect<glutin::Window,glutin::CreationError>
                        at C:\projects\rust\src\libcore\result.rs:809
  10:      0x7f7b5a1dc25 - servo::glutin_app::window::Window::new
                        at c:\buildbot\slave\windows-msvc-dev\build\ports\servo\glutin_app\window.rs:273
  11:      0x7f7b594c44a - servo::glutin_app::create_window
                        at c:\buildbot\slave\windows-msvc-dev\build\ports\servo\glutin_app\mod.rs:23
  12:      0x7f7b59801c6 - servo::main
                        at c:\buildbot\slave\windows-msvc-dev\build\ports\servo\main.rs:164
  13:      0x7f7b59385b4 - std::rt::lang_start::{{closure}}<()>
                        at C:\projects\rust\src\libstd\rt.rs:74
  14:      0x7f7bacc5aad - std::panicking::try::do_call<closure,i32>
                        at C:\projects\rust\src\libstd\panicking.rs:475
  15:      0x7f7bacdbdf2 - panic_unwind::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  16:      0x7f7bacc7f73 - std::rt::lang_start_internal
                        at C:\projects\rust\src\libstd\rt.rs:50
  17:      0x7f7b5938584 - std::rt::lang_start<()>
                        at C:\projects\rust\src\libstd\rt.rs:74
  18:      0x7f7b5981987 - main
  19:      0x7f7bb5e43e9 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  20:      0x7f935ea1842 - BaseThreadInitThunk
Servo exited with return value 101
program finished with exit code 101
```

**Comment by asajeffrey** [comment]
LGTM. The equivalent Mac smoketest is https://github.com/servo/servo/blob/96b9000fa25ca34ad56c8e95c9eabe5636174655/etc/ci/buildbot_steps.yml#L11 which loads the default servo.org web page and renders it to ouptut.png. I don't know if it's worth doing something similar for windows, or if a simple null page is good enough.

It's all certainly better than nothing, which is what we have for Linux due to CI GPU issues, sigh.

You can r=me.

**Comment by asajeffrey** [comment]
Hmm, that error looks suspiciously like the ones we get if we try to smoke test on Linux, caused by not having a GPU on the CI machines.

**Pull request closed without merging**
