### PR TITLE
stylo: Update clip-path and transform-box glue.

### PR DESCRIPTION
**Pull request by CJKu**
Gecko bug1340044 should be land immediately after this PR been merged.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it changes only the declaration type of mTransformBox

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16004)

### CODE REVIEW

**Comment by CJKu** [comment]
@heycam

**Comment by heycam** [comment]
@bors-servo delegate+

But let's reword the commit messages so they look normal for Servo.  I would use:

* `stylo: Update clip-path glue.`
* `stylo: Update transform-box glue.`

**Comment by heycam** [comment]
@bors-servo r=heycam

(It would be cleaner to have the bindings update in a separate commit.)

**Comment by CJKu** [comment]
@bors-servo r=heycam

rebase and try

**Pull request merged**
