### PR TITLE
Simplify Windows build by not setting PKG_CONFIG_PATH

### LINKED ISSUE #23177: Set PKG_CONFIG_PATH automatically when necessary from mach
From #23015 , we found `PKG_CONFIG_PATH` is required for building Servo.
So, I sent another PR (#23175) to add the README note.

We should be able to set the env var automatically from `mach` when there's no existing one.

We can do it like following line

https://github.com/servo/servo/blob/3e81a5afe938570ee4a0321e2c0269ed582e3adf/python/servo/command_base.py#L620

As @ferjm mentioned in [IRC](https://mozilla.logbot.info/servo/20190408#c16183483), we only need to set the `PKG_CONFIG_PATH` environment variable when the `pkg-config` check fails. So, we can do the check once, then set env var if the check fails. If it still fails, then we will throw the error because it might be related to other issues.

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #23177

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24005)

### CODE REVIEW

**Comment by jdm** [comment]
Looks like you made some changes after running test-tidy:
```

[94m./python/servo/command_base.py[0m:[93m241[0m: [91mE302 expected 2 blank lines, found 1[0m

[94m./python/servo/command_base.py[0m:[93m259[0m: [91mE302 expected 2 blank lines, found 1[0m

[94m./python/servo/command_base.py[0m:[93m588[0m: [91mE711 comparison to None should be 'if cond is None:'[0m
```

**Comment by jdm** [comment]
@bors-servo r-
See previous comment.

**Comment by Manishearth** [comment]
r=me with tidy :)

**Pull request merged**
