### PR TITLE
layout_thread: Also reposition elements when reflowing all nodes.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15805)

### CODE REVIEW

**Comment by glennw** [comment]
r=me - not sure if you want to squash or leave as separate commits.

**Comment by emilio** [comment]
@bors-servo r=glennw

 * I know I should add a test for this, but the only reliable way of testing this as of right now is via iframes, and those are not very reliable and end up adding intermittent failures reliably. I'll file an issue to add an API to `TestBinding` to modify page zoom instead, and add the test case from the issue when it's done.

**Comment by emilio** [comment]
@bors-servo r=glennw

 * Fixed geckolib warning that broke the build

**Pull request merged**
