### PR TITLE
Join tokens when stringifying DOMTokenList

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6555)

### CODE REVIEW

**Comment by frewsxcv** [comment]
See individual commit descriptions for more information

**Comment by frewsxcv** [comment]
Related to https://github.com/servo/servo/issues/1717

**Comment by Ms2ger** [comment]
Both commits have the same issue: they return strings with a leading space.

**Comment by frewsxcv** [comment]
Ah, you're right, I'll fix it

**Comment by frewsxcv** [comment]
Fixed in the latest force push

**Comment by Ms2ger** [comment]
Can we share the code too?

**Comment by frewsxcv** [comment]
> Can we share the code too?

Is there a better place to put it than `util::str` as a utility function `join_atoms`? It'd create a dependency in the `util` create on `string_cache`.

**Comment by Ms2ger** [comment]
Mm, that sucks. A better solution would be to make `Atom` implement `AsRef<str>` and then use that in util. I can land it like this if you push back, though :)

**Comment by frewsxcv** [comment]
Force pushed with the changes requested

**Pull request merged**
