### PR TITLE
style: Only expose longhands to rust via iterators.

### PR DESCRIPTION
**Pull request by emilio**
The key here is that we only filter longhands if the shorthand is accessible to
content and vice-versa. This prevents the bug that prevented me to land this
patch before, which was us not expanding properly chrome-only shorthands.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20138)

### CODE REVIEW

**Review by nox — APPROVED** [review]

**Comment by emilio** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=399baeb32221c620fef56c438144f11272bdba21

@bors-servo r=nox

**Comment by emilio** [comment]
@bors-servo r=nox

 * the calc test only enabled some column prefs but not others.

**Pull request merged**
