### PR TITLE
webgl: Add attribute validations and other nits

### PR DESCRIPTION
**Pull request by emilio**
Fixes https://github.com/servo/servo/issues/9958

Depends on a bunch of prs, and needs a test.

r? @jdm

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10224)

### CODE REVIEW

**Comment by emilio** [comment]
Test added.

btw josh, we don't support `HTMLScriptElement.type` and that made me bang my head against the wall for a while asking why my shader didn't compile (invalid type, so it didn't recognise `gl_FragColor`).

**Comment by emilio** [comment]
The PRs landed, so this is ready for review.

I updated the dependencies and reordered commits so every single one should compile.

**Comment by pcwalton** [comment]
Is this ready to go? If so, note that 4 browser.html P1s are blocked on this. If not, I think we should revert the rust-offscreen-rendering-context upgrades in webrender and webrender_traits.

**Comment by nox** [comment]
https://github.com/servo/servo/pull/10297 unblocks the situation.

**Comment by emilio** [comment]
Also #10302 takes in account webrender's breaking change to unblock any webrender update. Sorry for this having become a blocker, expected having this reviewed way sooner.

**Comment by emilio** [comment]
Rebased again :)

**Comment by jdm** [comment]
@bors-servo: r+
Sorry for sitting on this!

---

Reviewed 10 of 10 files at r1, 2 of 2 files at r2, 10 of 10 files at r3, 9 of 9 files at r4, 6 of 6 files at r5, 8 of 8 files at r6, 4 of 4 files at r7, 9 of 9 files at r8, 7 of 7 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/canvas/webgl_paint_thread.rs, line 31 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10224#-KF6ElBS4wXxoCDeyYfW:-KF6ElBTgEFDvAKlMOUG:447934403) ([raw file](https://github.com/servo/servo/blob/713d042a8417f9da52e270dc96f37baeddcc331a/components/canvas/webgl_paint_thread.rs#L31)):*
nit: indent this to match the `w` on the previous line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10224#-:-KF6GflzJXDM47PbTIgK:-200710906)*

**Comment by emilio** [comment]
No problem! I don't mind rebasing as many times as necessary :P 

Glad to see you're cleaning up the review queue :)

@bors-servo: retry

 * https://github.com/servo/servo/issues/10473

**Pull request merged**
