### PR TITLE
Details ui

### PR DESCRIPTION
**Pull request by notriddle**
Requires a patch to rust-selectors, and doesn't currently recalculate the styles correctly (which is needed to make actual toggling work correctly).

Still trying to figure out what it takes to get style recalc to do what this needs.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9586)

### CODE REVIEW

**Comment by notriddle** [comment]
Based on new information, this will instead be blocking on #9567.

**Comment by jdm** [comment]
@notriddle #9567 merged. Is this ready for review?

**Comment by notriddle** [comment]
Just need to rebase.

**Comment by notriddle** [comment]
Okay, I've rebased it.

**Comment by notriddle** [comment]
?

**Comment by jdm** [comment]
Given how many of the changes here relate to the style system, I'm going to defer most of this review to @SimonSapin. The general idea looks good to me, though!

**Comment by notriddle** [comment]
Rebased.

**Comment by notriddle** [comment]
?

**Comment by jdm** [comment]
@SimonSapin Could you either review it or hand it off to somebody else appropriate?

**Comment by notriddle** [comment]
Rebased. @SimonSapin r?

**Comment by SimonSapin** [comment]
Reviewed 5 of 13 files at r1, 2 of 6 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/layout/wrapper.rs, line 1126 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9586#-KDBBro2-jHYdlUi5cLP:-KDBBro2-jHYdlUi5cLQ:-2049752340) ([raw file](https://github.com/servo/servo/blob/051ac43e693471b6f445b965ba2de7a50a7778b0/components/layout/wrapper.rs#L1126)):*
This should probably either check for the HTML namespace as well, or check `.type_id()` instead.

---

*[components/layout/wrapper.rs, line 1142 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9586#-KDBCeKZFSh4TxRigj0z:-KDBCeK_BO-g1LrsW7OB:160841994) ([raw file](https://github.com/servo/servo/blob/051ac43e693471b6f445b965ba2de7a50a7778b0/components/layout/wrapper.rs#L1142)):*
Same as above.

---

*[components/style/selector_impl.rs, line 109 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9586#-KC1SMZ4mbmILkVTQeoh:-KC1SMZ4mbmILkVTQeoi:647282661) ([raw file](https://github.com/servo/servo/blob/95c63c34fe90fcd99cd8fde1d813075d94f8572f/components/style/selector_impl.rs#L109)):*
Please change these to:

```rust
            "-servo-details-summary" if context.in_user_agent_stylesheet => DetailsSummary,
            "-servo-details-content" if context.in_user_agent_stylesheet => DetailsContent,
```

… so the these internal pseudo-elements are not exposed to web content.

---

*[resources/servo.css, line 40 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9586#-KDB8RkQkUU-or6Q1V5X:-KDB8RkQkUU-or6Q1V5Y:-1761470136) ([raw file](https://github.com/servo/servo/blob/051ac43e693471b6f445b965ba2de7a50a7778b0/resources/servo.css#L40)):*
Nit: looks like this changed to `#the-details-and-summary-elements`

---

*[resources/servo.css, line 44 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9586#-KDB8nxZ9RqsJ46QOLRg:-KDB8nxZ9RqsJ46QOLRh:-1729841063) ([raw file](https://github.com/servo/servo/blob/051ac43e693471b6f445b965ba2de7a50a7778b0/resources/servo.css#L44)):*
This conflicts with whatever use author stylesheets might make of `details::before`. The spec uses `list-style: disclosure-closed`, which we do implement. (Or did the spec change recently?)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9586)*

**Comment by notriddle** [comment]
*[components/layout/wrapper.rs, line 1126 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9586#-KDBBro2-jHYdlUi5cLP:-KDCLPbal3Vb9P9BgYyV:-499146009) ([raw file](https://github.com/servo/servo/blob/051ac43e693471b6f445b965ba2de7a50a7778b0/components/layout/wrapper.rs#L1126)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9586)*

**Comment by notriddle** [comment]
*[components/layout/wrapper.rs, line 1142 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9586#-KDBCeKZFSh4TxRigj0z:-KDCLTuGXZ4MejjYA0yS:-499146009) ([raw file](https://github.com/servo/servo/blob/051ac43e693471b6f445b965ba2de7a50a7778b0/components/layout/wrapper.rs#L1142)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9586)*

**Comment by notriddle** [comment]
*[components/style/selector_impl.rs, line 109 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9586#-KC1SMZ4mbmILkVTQeoh:-KDCLWGVDlA54mM-eDie:-499146009) ([raw file](https://github.com/servo/servo/blob/95c63c34fe90fcd99cd8fde1d813075d94f8572f/components/style/selector_impl.rs#L109)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9586)*

**Comment by notriddle** [comment]
*[resources/servo.css, line 40 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9586#-KDB8RkQkUU-or6Q1V5X:-KDCLYAfXFGTe5xgUtK_:-499146009) ([raw file](https://github.com/servo/servo/blob/051ac43e693471b6f445b965ba2de7a50a7778b0/resources/servo.css#L40)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9586)*

**Comment by notriddle** [comment]
*[resources/servo.css, line 44 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9586#-KDB8nxZ9RqsJ46QOLRg:-KDCLdrYFrD1vW9ufPV1:-499146009) ([raw file](https://github.com/servo/servo/blob/051ac43e693471b6f445b965ba2de7a50a7778b0/resources/servo.css#L44)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9586)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9586#-:-KDCpmp-O0EbYevFBVFv:1236647940)*

**Comment by KiChjang** [comment]
17 test failures, oh joy

**Comment by notriddle** [comment]
Fixed 'em.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9586#-:-KDHzXAxNiNr7DasRnE2:1236647940)*

**Pull request merged**
