### PR TITLE
Update web-platform-tests to revision 3b3585e368841b77caea8576fa56cef91c3fbdf0

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13426)

### CODE REVIEW

**Comment by Manishearth** [comment]
```patch
diff --git a/tests/wpt/mozilla/meta/MANIFEST.json b/tests/wpt/mozilla/meta/MANIFEST.json
index fbdcc35..c14e067 100644
--- a/tests/wpt/mozilla/meta/MANIFEST.json
+++ b/tests/wpt/mozilla/meta/MANIFEST.json
@@ -764,18 +764,6 @@
             "url": "/_mozilla/css/blur_a.html"
           }
         ],
-        "css/border_black_groove.html": [
-          {
-            "path": "css/border_black_groove.html",
-            "references": [
-              [
-                "/_mozilla/css/border_black_solid.html",
-                "!="
-              ]
-            ],
-            "url": "/_mozilla/css/border_black_groove.html"
-          }
-        ],
         "css/border_black_ridge.html": [
           {
             "path": "css/border_black_ridge.html",
@@ -2184,18 +2172,6 @@
             "url": "/_mozilla/css/image_rendering_auto_a.html"
           }
         ],
-        "css/image_rendering_pixelated_a.html": [
-          {
-            "path": "css/image_rendering_pixelated_a.html",
-            "references": [
-              [
-                "/_mozilla/css/image_rendering_pixelated_ref.html",
-                "=="
-              ]
-            ],
-            "url": "/_mozilla/css/image_rendering_pixelated_a.html"
-          }
-        ],
         "css/img_block_display_a.html": [
           {
             "path": "css/img_block_display_a.html",
```

**Comment by Ms2ger** [comment]
#13341

**Pull request merged**
