### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21068)

### CODE REVIEW

**Comment by jdm** [comment]
```
./components/script/dom/medialist.rs:17: use statement is not in alphabetical order
	expected: style::media_queries::MediaQuery
	found: style::media_queries::MediaList as StyleMediaList
```

**Comment by emilio** [comment]
One day I'll understand tidy's sorting... :)

@bors-servo r+

**Comment by emilio** [comment]
Seems Flaky?

> error: Could not compile `layout_thread`.

**Comment by jdm** [comment]
Yeah, that machine starts running out of memory every so often and then we have to shut it down.

**Pull request merged**
