### PR TITLE
Kill serde_codegen 💣

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15769)

### CODE REVIEW

**Comment by nox** [comment]
Network issues, waiting for the other builds to finish.

**Comment by edmorley** [comment]
As a head's up, the commit message here contained a non-BMP unicode character ("astral unicode character"), which requires 4 bytes to represent rather than the 3 bytes of BMP unicode, and as such causes issues with MySQL tables using utf8. This is affecting Treeherder pushlog ingestion (https://bugzilla.mozilla.org/show_bug.cgi?id=1115608) - we'll either need to strip out the non-BMP unicode or else switch this particular table to utf8mb4.

Obviously Treeherder should definitely handle this case gracefully, but there are likely other systems that consume the hg.mozilla.org pushlog that may not handle it well either, so please bear it in mind when using more unusual unicode characters in commit messages :-)

**Comment by nox** [comment]
@edmorley How was it not a problem in the past though? This is not the first time I use emojis.

**Comment by edmorley** [comment]
I imagine they were within the BMP (Basic Multilingual Plane) unicode range:
https://en.wikipedia.org/wiki/Plane_(Unicode)

(or else only in the PR description and not the commit message)

**Comment by nox** [comment]
I'm pretty sure [U+1F916 ROBOT FACE](https://github.com/servo/servo/pull/11308) is outside the BMP.

**Comment by nox** [comment]
Oh right, you squash all commits of a PR together, right?

**Comment by SimonSapin** [comment]
> we'll either need to […] switch this particular table to utf8mb4.

Yes. It’s been in MySQL since 2010.

I personally don’t think that “Only use BMP characters” is much more acceptable than “Only use ASCII characters”.

As to PR descriptions, the get included by bors/homu in the message of merge commits.

**Comment by edmorley** [comment]
I agree, it's just unfortunate that:
(a) MySQL makes it way too easy to fall into this trap by defaulting to `latin1` thus making people have to pick a charset themselves - which is easy to get wrong due to their unfortunate naming, the sheer volume of docs online not referencing `utf8mb4`, their not deprecating the BMP-only charsets, and then making people who want to convert jump through hoops to support longer indexes under utf8mb4 (eg `innodb_file_format=barracuda`, `innodb_large_prefix=1`).
(b) Django doesn't support utf8mb4 out of the box (https://code.djangoproject.com/ticket/18392; not helped by MySQL being seen as a 2nd-class citizen by the Django project, compared to PostgreSQL)

As another datapoint, bugzilla.mozilla.org is currently facing similar "utf8 doesn't mean utf8 in MySQL" realisations / hassle converting:
https://bugzilla.mozilla.org/show_bug.cgi?id=1253535
https://bugzilla.mozilla.org/show_bug.cgi?id=1328659

That said, I think the answer is just to give up on MySQL (this is just the last in a long list of annoyances we've had with it) and use PostgreSQL. But not an overnight switch for large existing projects like Treeherder.

**Pull request merged**
