### PR TITLE
Use values::generics::rect::Rect some more

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17036)

### CODE REVIEW

**Comment by nox** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=c664989e6370fca37c09379e2da8cefa81b721df

**Comment by emilio** [comment]
r=me, assuming geckotry comes out green.

**Comment by nox** [comment]
Good thing I did a geckotry run, forgot the `webkit` prefix for `background-size`.

https://treeherder.mozilla.org/#/jobs?repo=try&revision=7e852dba6dd1e58ea4654563420978c6c858bd1f

**Comment by nox** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=8604a41318f2f5da003feb01b072bc01d6891f77

**Comment by nox** [comment]
I had forgotten to call `parse_non_negative` instead of `parse`.

**Comment by nox** [comment]
Geckotry is green.

@bors-servo r=emilio

**Pull request merged**
