### PR TITLE
Partial fix for #12415: expose Canvas interfaces

### PR DESCRIPTION
**Pull request by scotttrinh**
Fix interface exposure per [the specs](https://html.spec.whatwg.org/multipage/scripting.html#2dcontext).

One lingering question I have is if [`CanvasPath`](https://html.spec.whatwg.org/multipage/scripting.html#canvaspath) needs to be added to `interfaces.worker.js` since it _is_ exposed to the `Worker` environment. I tried adding it to the `interfaces.worker.js` list but it failed tests at https://github.com/servo/servo/blob/master/tests/wpt/mozilla/tests/mozilla/interfaces.js#L82 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes contain a partial fix for #12415 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13747)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thanks! `CanvasPath` doesn't need to be in either of the interfaces tests because it has `[NoInterfaceObject]`.

@bors-servo r+

**Comment by scotttrinh** [comment]
@Ms2ger any help as to where I should look to fix this?

**Comment by scotttrinh** [comment]
I see [this](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/workers/semantics/interface-objects/002.worker.js#L11-L18) but I'm having a hard time understanding the test output. Does `expected FAIL` mean that these tests were testing that it was improperly adding those interfaces to the worker environment and so I need to remove them?

**Comment by scotttrinh** [comment]
Just commented them out and those tests pass. Let me know that this is the correct solution and I'll commit and squash!

**Comment by jdm** [comment]
`expected FAIL` means that the tests used to be reliably failing, and now they are passing as intended. We record the results of tests in files like `tests/wpt/metadata/workers/semantics/interface-objects/002.worker.js.ini`, rather than enforcing that every single test must always pass.

**Comment by jdm** [comment]
See https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations for a better explanation.

**Comment by KiChjang** [comment]
You need to update the test expectations in `tests/wpt/metadata/workers/semantics/interface-objects/002.worker.ini`. Previously without your changes, the tests were expected to fail. You'll need to revert the changes that you've made to `interfaces.worker.js`.

**Comment by scotttrinh** [comment]
Thanks for the tips, I can confirm removing the offending lines in `tests/wpt/metadata/workers/semantics/interface-objects/002.worker.ini` results in passing tests.

@KiChjang Let me make sure I follow your direction: the four lines I removed from `interfaces.worker.js` were removed since those interfaces are no longer exposed on the worker interface. Are you saying that I should put them back in?

**Comment by KiChjang** [comment]
@scotttrinh Oh, nevermind, I misread. Ignore the `interfaces.worker.js` stuff, I believe those changes are correct.

**Pull request merged**
