### PR TITLE
compositing: Fix a couple of bugs that prevented iframes from painting after navigation.

### LINKED ISSUE #8081: iframe not painted anymore after navigation (regression c72d0c2)
Since commit c72d0c2ed04f6c5f9fa22a3f576e1df5878f941d, clicking a link in a iframe turns the iframe white.

I believe the iframe is loaded but not painted (we get load events).

### PR DESCRIPTION
**Pull request by jdm**
The first bug was that iframes were not reflowed in their parent DOM when the child page navigated. This is fixed by simply having the constellation notify the appropriate script thread when navigation occurs.

The second bug was that the compositor was unable to adjust the pipeline for existing iframe layers, only new ones. This patch adds logic to do that.

The third bug was that we have ad-hoc reflow calls throughout script/, and we didn't trigger any reflow from the code that dispatches the `load` event for the iframe so the test for the first two issues would always time out. The second commit adds another reflow call to do that, and also bites the bullet and adds a catch-all reflow (which does nothing if there's no dirty nodes in the document) at the return to the event loop.

Closes #8081.

Extension of #9285.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9421)

### CODE REVIEW

**Comment by pcwalton** [comment]
@bors-servo: r+

Thanks so much for looking into this!

**Comment by nox** [comment]
#9045 hit again, and test-css somehow timed out for obscure reasons.

**Comment by jdm** [comment]
#9045 isn't hitting here - that's only in debug mozjs builds.

**Comment by jdm** [comment]
@bors-servo: retry
* #9432

**Comment by jdm** [comment]
Huh. I'm going to try and reproduce #9432 locally, since that's hit every test run.

**Comment by jdm** [comment]
The latest commit fixes #9432.

**Comment by glennw** [comment]
@jdm The last commit looks good to me.

**Pull request merged**
