### PR TITLE
Stylo: add `content: -moz-alt-content`

### PR DESCRIPTION
**Pull request by SimonSapin**
Part of https://bugzilla.mozilla.org/show_bug.cgi?id=1341642

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #_ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15691)

### CODE REVIEW

**Comment by bzbarsky** [comment]
r=me, but I'm not an expert on this code....

**Comment by jdm** [comment]
@bors-servo: retry
* #13480

**Comment by SimonSapin** [comment]
```
{"status": "CRASH", "stack": null, "subtest": null, "action": "test_result", "test": "/css-transforms-1_dev/html/svg-gradientTransform-047.htm", "line": 17226, "message": null, "expected": "PASS"}
```

Hmmm

@bors-servo try

**Comment by SimonSapin** [comment]
```rust
{"status": "NOTRUN", "stack": null, "subtest": "Overall test", "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/texture-size.html", "line": 49921, "message": null, "expected": "PASS"}
{"status": "TIMEOUT", "stack": null, "subtest": null, "action": "test_result", "test": "/webgl/conformance-1.0.3/conformance/textures/texture-size.html", "line": 50110, "message": null, "expected": "OK"}
```

Ok, I have no idea what’s going on.

@Manishearth @jdm  should I file all three of these as new intermittents?

**Comment by nox** [comment]
@SimonSapin AFAIK this test is a bit broken to begin with, see [its current `ini` file](https://github.com/servo/servo/blob/854d720b21dda68034233a25385c4f2564a4a2d5/tests/wpt/metadata/webgl/conformance-1.0.3/conformance/textures/texture-size.html.ini).

**Comment by bzbarsky** [comment]
Actually, this produces incorrect parsing behavior.  See https://github.com/servo/servo/issues/15726

**Pull request merged**
