### PR TITLE
Generalize the style structs

### PR DESCRIPTION
**Pull request by bholley**
This allows geckolib to pass gecko style structs and have the style system write to them directly, provided we implement all the traits.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10155)

### CODE REVIEW

**Comment by bholley** [comment]
CC @pcwalton

**Comment by SimonSapin** [comment]
First knee-jerk reaction: I really dislike the `TSomething` naming pattern. Nowhere else do we use "Hungarian" notation like this. Can we instead call the traits `Thing` and the types that implement them `ServoThing` and `GeckoThing`?

**Comment by bholley** [comment]
Happy to do that, but can we make it a followup? My reason for choosing a new name was to avoid renaming the world all at once. This PR took more than 6 hours to rebase on top of the recent refactor...

**Comment by SimonSapin** [comment]
Sure, that’s fine.

**Comment by SimonSapin** [comment]
Reviewed 47 of 47 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/style/properties.mako.rs, line 171 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdn7oROaVtYW487P8h:-KDdn7oROaVtYW487P8i:-1742641815) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L171)):*
Nit: indent the content of blocks. If the rightwards drift becomes too much, consider splitting some things into a new function.

---

*[components/style/properties.mako.rs, line 181 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdnwKyNyr6dpYgLxZi:-KDdnwKyNyr6dpYgLxZj:430422514) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L181)):*
Could also be `.copy_*_from(&INTITIAL_VALUES)`?

---

*[components/style/properties.mako.rs, line 6259 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdpUsJRTjqBS2UHKfG:-KDdpUsJRTjqBS2UHKfH:-584680106) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L6259)):*
Could these two clone/get methods be a single method that returns `&Arc<…>`, leaving the caller free to clone or deref?

---

*[components/style/properties.mako.rs, line 6605 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdqPMjMYXPiQaFPjsv:-KDdqPMkzPexhthtCSz0:398315194) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L6605)):*
Nit: I usually indent the contents of Mako blocks as I find it helps readability. (The indentation of the generated file doesn’t matter.)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10155)*

**Comment by bholley** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/style/properties.mako.rs, line 171 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdn7oROaVtYW487P8h:-KDdx19CvxhGkn3VzGiQ:-499146009) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L171)):*
Done.

---

*[components/style/properties.mako.rs, line 181 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdnwKyNyr6dpYgLxZi:-KDdw0Gciua3u1RXEJEt:823050348) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L181)):*
Nice idea!

---

*[components/style/properties.mako.rs, line 6259 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdpUsJRTjqBS2UHKfG:-KDdxXVQ7XrPB6R000fl:1849284070) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L6259)):*
We could, but I think it would decrease readability. We already need at least two accessors to handle the mutatable case, and by adding three we can eliminate the cognitive load of references to Arcs, which makes things simpler and more concrete.

Given that this stuff all has an extra layer of abstraction given the codegen, I think concrete and simple are worthwhile goals. And given that this stuff is codegened and then inlined, it doesn't seem likely to cost us much.

I'm ok with changing it if you still think it's preferable though. Let me know.

---

*[components/style/properties.mako.rs, line 6605 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdqPMjMYXPiQaFPjsv:-KDdxM-9vO6MaqHS2DfW:763199418) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L6605)):*
I was trying to improve the readability of generated code where I could, but I guess I can live with this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10155)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 5 of 7 files at r6, 33 of 37 files at r7, 6 of 7 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/properties.mako.rs, line 6605 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdqPMjMYXPiQaFPjsv:-KDe_8ioCwlFapky1lf_:413726098) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L6605)):*
Do you find yourself reading generated code a lot? I suppose that’s where a compiler plugin could do better: if we track "spans" correctly, error messages would indicate locations in actual source files.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10155#-:-KDe_p4KV2w0amz7Gq2Z:1236647940)*

**Comment by bholley** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/properties.mako.rs, line 6605 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10155#-KDdqPMjMYXPiQaFPjsv:-KDeaqv0Sj-iwlk2kPR3:-806058250) ([raw file](https://github.com/servo/servo/blob/05762807acd77ecd5246e77fbdaf661fecd9cfde/components/style/properties.mako.rs#L6605)):*
I did read the generated code quite a bit while learning how everything worked, though certainly less as time went on. Shrug.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10155)*

**Comment by bholley** [comment]
Thanks for the fast review!

**Comment by bholley** [comment]
Filed #10185 for the rename.

**Pull request merged**
