### PR TITLE
Implement fetch metadata headers

### PR DESCRIPTION
**Pull request by simonwuelker**
Implements the `sec-fetch-site`, `sec-fetch-dest`, `sec-fetch-user` and `sec-fetch-site` headers.

Some new failures on wpt materialize now because we seem to mess up *something* related to urls during redirects, causing `sec-fetch-site` headers to be sent when they should not be.

[try run](https://github.com/simonwuelker/servo/actions/runs/11317193682) 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes are a part of https://github.com/servo/servo/issues/33616

- [X] There are tests for these changes

### CODE REVIEW

**Review by mukilan — APPROVED** [review]
LGTM. Thank you!

**Comment by mukilan** [comment]
Looks like the unit test expectations might need to be updated:
```
 thread 'http_loader::test_request_and_response_data_with_network_messages' panicked at components/net/tests/http_loader.rs:319:5:
assertion `left == right` failed
  left: HttpRequest { url: "http://localhost:43861/", method: GET, headers: {"user-agent": "Such Browser. Very Layout. Wow.", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "accept-language": "en-US,en;q=0.5", "sec-fetch-dest": "document", "sec-fetch-mode": "no-cors", "sec-fetch-site": "same-site", "sec-fetch-user": "?1", "accept-encoding": "gzip, deflate, br"}, body: Some([]), pipeline_id: (1234,5678), started_date_time: SystemTime { tv_sec: 1728999028, tv_nsec: 248137398 }, time_stamp: 1728999028, connect_time: 570ns, send_time: 942.931µs, is_xhr: false }
 right: HttpRequest { url: "http://localhost:43861/", method: GET, headers: {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "accept-language": "en-US,en;q=0.5", "user-agent": "Such Browser. Very Layout. Wow.", "accept-encoding": "gzip, deflate, br"}, body: Some([]), pipeline_id: (1234,5678), started_date_time: SystemTime { tv_sec: 1728999028, tv_nsec: 248137398 }, time_stamp: 1728999028, connect_time: 570ns, send_time: 942.931µs, is_xhr: false }
 ```

**Comment by jdm** [comment]
`./mach test-unit` still has two failing tests: https://github.com/servo/servo/actions/runs/11353882759/job/31579898357?pr=33830#step:17:1943

**Comment by simonwuelker** [comment]
> `./mach test-unit` still has two failing tests: https://github.com/servo/servo/actions/runs/11353882759/job/31579898357?pr=33830#step:17:1943

I know, I just didn't get around to fixing those yet, sorry about that. They should pass now.

**Review by mukilan — APPROVED** [review]

**Pull request merged**
