### PR TITLE
format components/net

### PR DESCRIPTION
**Pull request by AnshulMalik**
Issue:: #21373
Format components/net using rustfmt.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21650)

### CODE REVIEW

**Comment by Eijebong** [comment]
Can we not ? T_T

**Comment by Eijebong** [comment]
#21644

**Comment by AnshulMalik** [comment]
I didn't understand @Eijebong, could you please explain?

**Comment by Eijebong** [comment]
I changed a lot of the net code in my PR and I would love to avoid rebasing over yours since it's automated.

**Comment by AnshulMalik** [comment]
ok, no issues

**Pull request closed without merging**
