### PR TITLE
Add support for caseless group name matching in HTML input elements

### LINKED ISSUE #7749: Consider radio button group names in a case-insensitive fashion
We can use [@SimonSapin's rust-caseless](https://github.com/SimonSapin/rust-caseless) crate for this.

The relevant function is `in_same_group()` in htmlinputelement.rs.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #7749

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7777)

### CODE REVIEW

**Comment by KiChjang** [comment]
Aaaaaaaaaaaaaaand I just hit the lucky jackpot with the PR number of 7777!

**Comment by Ms2ger** [comment]
No tests that cover this?

**Comment by KiChjang** [comment]
Remind me again where do I include them?

**Comment by mbrubeck** [comment]
@KiChjang There may be existing tests that cover this in the WPT test suit, which you can run with the `./mach test-wpt` command.  Warning: This takes a very very long time. You might want to search through the tests and only run specific ones that look likely to be affected, and/or use a release build and the `--release` argument.  If this doesn't cause any existing tests to pass, then you could add your own test.  For more info see:

* https://github.com/servo/servo/wiki/Testing
* https://github.com/servo/servo/blob/master/tests/wpt/README.md

**Comment by KiChjang** [comment]
There's a test that specifically tests for the name attribute for radio buttons at `html/semantics/forms/the-input-element/radio-groupname-case.html`. It's currently passing 6 of the 7 tests.

**Comment by jdm** [comment]
```

/html/semantics/forms/the-input-element/radio.html
--------------------------------------------------
PASS expected FAIL radio inputs with name attributes groüp2 and groÜp2 belong to the same radio button group
```

**Comment by jdm** [comment]
Could you squash all these commits together?

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by mbrubeck** [comment]
@bors-servo retry

#7785

**Pull request merged**
