### PR TITLE
Run custom element tests

### PR DESCRIPTION
**Pull request by cbrewster**
I would like to have these enabled so its easier to see newly passing tests in subsequent PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17101)

### CODE REVIEW

**Comment by cbrewster** [comment]
I noticed that there was no metadata for these tests, not even to disable them... Are these not ran by `./mach test-wpt`?

**Comment by jdm** [comment]
Yeah, you need to add an entry to include.ini as well.

**Comment by nox** [comment]
We usually don't just enable tests if we don't actually have commits fixing them in the same PR.

**Comment by nox** [comment]
See for example https://github.com/servo/servo/pull/5839.

**Comment by jdm** [comment]
There is precedent for enabling tests separately from the work that starts addressing them.

**Comment by nox** [comment]
> There is precedent for enabling tests separately from the work that starts addressing them.

Ok! Disregard me then. :)

**Comment by jdm** [comment]
@bors-servo: retry
* #17109

**Pull request merged**
