### PR TITLE
Implement attribute 'fgColor' on 'document'

### PR DESCRIPTION
**Pull request by frewsxcv**
The 'text' attribute was implemented on `<body>` in #7841

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8714)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Is the `TreatNullAs=EmptyString` part tested?

**Comment by frewsxcv** [comment]
Doesn't look like it. I'll add a test sometime today.

**Comment by frewsxcv** [comment]
@Ms2ger are the auto-generated 'null' tests from 'dom/interfaces.html' sufficient? Otherwise I can add some more specific ones

**Comment by Ms2ger** [comment]
I would prefer more specific ones/

**Comment by frewsxcv** [comment]
Sounds good. Out right now, but I'll commit a test later

**Comment by frewsxcv** [comment]
Pushed a few tests. Ready for review again.

**Comment by Ms2ger** [comment]
@bors-servo r+

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8714#-:-K4TIshXabDtgLU8sdsa:1236647940)*

**Pull request merged**
