### PR TITLE
mach bootstrap - activate virtual env

### LINKED ISSUE #24561: `./mach bootstrap` fails on my Ubuntu 18.04 LTS installation
When I run `./mach bootstrap`, it errors out. At first I thought that this might be because I had `python3-virtualenv` installed on my machine, but not `python-virtualenv` (the Python 2 version). But now I have both, and I'm still getting errors.

I am running a relatively fresh install of Ubuntu 18.04 LTS, x86_64, on a UEFI-based system with legacy BIOS features turned off. I just reinstalled Ubuntu about a month ago. I have been pretty busy with development activities on it, though. I have a 6-core, 3-GHz, 8th-gen Core i5 processor, and 16 GB of DDR4-2666 SDRAM.

The error output in my terminal is as follows:

```
Traceback (most recent call last):
  File "./mach", line 103, in <module>
    main(sys.argv)
  File "./mach", line 31, in main
    sys.exit(mach_bootstrap.bootstrap_command_only(topdir))
  File "/home/<username>/Projects/repos/git/GitHub/servo/servo/python/mach_bootstrap.py", line 227, in bootstrap_command_only
    from servo.bootstrap import bootstrap
  File "/home/<username>/Projects/repos/git/GitHub/servo/servo/python/servo/bootstrap.py", line 11, in <module>
    import distro
ImportError: No module named distro
```

It's worth noting that I have at least three different versions of Python installed on my computer, at the Ubuntu system level: 2.7, 3.6, and 3.7.

What other information do you guys need?

Thanks!

### PR DESCRIPTION
**Pull request by JoshMcguigan**
This modifies the `./mach bootstrap` script to activate the python virtual environment, fixing issues on systems that don't have `six` and `distro` pre-installed. 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24561 (also relevant to #24541)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they are in the `./mach bootstrap` script - although this may be something that could be checked in CI - Is there any interest in setting this up?

### CODE REVIEW

**Comment by jdm** [comment]
The question about testing CI on bootstrap is an interesting one! It should be straightforward to create a new taskcluster job that uses a stock ubuntu/debian distribution, runs mach bootstrap, then builds Servo from scratch. That would give us a bit more confidence that the recommended setup path for new contributors is actually usable. I've filed #24570 for that, and we can merge this in the meantime.

**Comment by jdm** [comment]
[This comment](https://github.com/servo/servo/blob/6d488f1be24c1b679931d6d02703f4a10759eb49/python/servo/bootstrap_commands.py#L44-L46) is interesting though.

**Comment by paulrouget** [comment]
@jdm r?

**Comment by JoshMcguigan** [comment]
> [This comment](https://github.com/servo/servo/blob/6d488f1be24c1b679931d6d02703f4a10759eb49/python/servo/bootstrap_commands.py#L44-L46) is interesting though.

Hmm, that is interesting. I wonder if perhaps that comment is out of date? Because `bootstrap_command_only` imports `from servo.bootstrap import bootstrap`.

https://github.com/servo/servo/blob/6d488f1be24c1b679931d6d02703f4a10759eb49/python/mach_bootstrap.py#L227

**Comment by JoshMcguigan** [comment]
Is there anything else you'd like to see on this branch before merging?

**Comment by jdm** [comment]
r? @SimonSapin 
I'm going to redirect the review to someone with more python experience.

**Comment by jdm** [comment]
Review ping @SimonSapin.

**Comment by SimonSapin** [comment]
To be honest I don’t fully understand `mach_bootstrap.py`, and `bootstrap_command_only` in particular feels a bit messy. But that’s all pre-existing, given that situation this change looks reasonable.

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* https://github.com/servo/servo/issues/24611

**Comment by jdm** [comment]
@bors-servo retry
* https://github.com/servo/servo/issues/24611

**Pull request merged**
