### PR TITLE
Fix typo and simplify for PresentationalHintsSynthesizer

### PR DESCRIPTION
**Pull request by aethanyc**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because it only affects build.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16785)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0433]: failed to resolve. Use of undeclared type or module `fmt`
   --> /Users/servo/buildbot/slave/mac-rel-wpt2/build/components/style/stylist.rs:525:29
    |
525 |         where E: TElement + fmt::Debug + PresentationalHintsSynthetizer
    |                             ^^^^^^^^^^ Use of undeclared type or module `fmt`

error[E0405]: cannot find trait `PresentationalHintsSynthetizer` in this scope
   --> /Users/servo/buildbot/slave/mac-rel-wpt2/build/components/style/stylist.rs:525:42
    |
525 |         where E: TElement + fmt::Debug + PresentationalHintsSynthetizer
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

   Compiling bluetooth v0.0.1 (file:///Users/servo/buildbot/slave/mac-rel-wpt2/build/components/bluetooth)
error: cannot continue compilation due to previous error
```

**Comment by aethanyc** [comment]
Can we retry the test? `PresentationalHintsSynthetizer` shouldn't show up on the error log because it's removed by my change.

**Comment by jdm** [comment]
@bors-servo: retry
* That's really spooky.

**Comment by jdm** [comment]
@bors-servo: r-
https://github.com/servo/servo/blob/e8a594b3736f964a6b830879595708224861f4c4/components/style/stylist.rs#L525

**Comment by aethanyc** [comment]
Oh. That part was landed yesterday after I upload my PR. Will fix

**Pull request merged**
