### PR TITLE
Issue #8738: bufferSubData and texImage2D argument sanity checks.

### PR DESCRIPTION
**Pull request by simartin**
Fixes https://github.com/servo/servo/issues/8738

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8948)

### CODE REVIEW

**Comment by frewsxcv** [comment]
*[components/script/dom/webglrenderingcontext.rs, line 931 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8948#-K5LhlNMJ8hIVVFc8qDR:-K5LhlNMJ8hIVVFc8qDS:-2073312984) ([raw file](https://github.com/servo/servo/blob/34f00f1709272208da866d9cb5c80667e26e8aa9/components/script/dom/webglrenderingcontext.rs#L931)):*
could this just be `if self.bound_texture_for(target).is_none() {` ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8948)*

**Comment by simartin** [comment]
*[components/script/dom/webglrenderingcontext.rs, line 931 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8948#-K5LhlNMJ8hIVVFc8qDR:-K5LrN_7lpwNnpGpXPKX:1006948577) ([raw file](https://github.com/servo/servo/blob/34f00f1709272208da866d9cb5c80667e26e8aa9/components/script/dom/webglrenderingcontext.rs#L931)):*
You're right, it's more readable. PR update coming up.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8948)*

**Comment by ecoal95** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/script/dom/webglrenderingcontext.rs, line 931 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8948#-K5LhlNMJ8hIVVFc8qDR:-K5VteEzLVIxaq3iFxS9:527411388) ([raw file](https://github.com/servo/servo/blob/34f00f1709272208da866d9cb5c80667e26e8aa9/components/script/dom/webglrenderingcontext.rs#L931)):*
Good catch here :)

---

*[components/script/dom/webglrenderingcontext.rs, line 84 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8948#-K5Vo0T057XHtdCFh3k7:-K5Vo0T057XHtdCFh3k8:1406853589) ([raw file](https://github.com/servo/servo/blob/63dd4227210757d94bb7a8de9362f7bf512e8081/components/script/dom/webglrenderingcontext.rs#L84)):*
I think the allocated size should be part of the `WebGLBuffer` object itself, something similar to what we do with the `target` field.
What would happen if you re-bind a buffer with data already allocated?

---

*[components/script/dom/webglrenderingcontext.rs, line 401 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8948#-K5VpauNHJF-MVWkZPzC:-K5VpauNHJF-MVWkZPzD:713321246) ([raw file](https://github.com/servo/servo/blob/63dd4227210757d94bb7a8de9362f7bf512e8081/components/script/dom/webglrenderingcontext.rs#L401)):*
We probably should move almost all this logic to `webglbuffer.rs`, to a function with a signature like:

```rust
pub fn buffer_data(&self, target: u32, data: Vec<u8>, usage: u32) -> WebGLResult<()>;
```

Where the new size size should be updated.

And leave this function with just the validations and something like:

```rust
handle_potential_webgl_error!(self.buffer_data(target, data, usage));
```

---

*[components/script/dom/webglrenderingcontext.rs, line 460 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8948#-K5VtUfDszVEZnAdjq3M:-K5VtUfDszVEZnAdjq3N:-1675902261) ([raw file](https://github.com/servo/servo/blob/63dd4227210757d94bb7a8de9362f7bf512e8081/components/script/dom/webglrenderingcontext.rs#L460)):*
Same as above, this logic should be moved to the `WebGLBuffer` object.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8948)*

**Comment by simartin** [comment]
Thanks for the review! I've taken your comments into account and rebased.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8948#-:-K6UD674wj8Thp2Y4gFF:-2105978674)*

**Comment by ecoal95** [comment]
Looks good to me, modulo those little changes :)

-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/script/dom/webglbuffer.rs, line 21 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8948#-K6UHPTbSDR25dMp8PXN:-K6UHPTbSDR25dMp8PXO:1439019811) ([raw file](https://github.com/servo/servo/blob/e65c90b917e6c6805acfb9d6426877223681dbed/components/script/dom/webglbuffer.rs#L21)):*
I'd prefer this to be called `allocated_size` or `capacity`, it looks clearer to me, but it's a matter of taste so if you think it's fine, it can remain this way.

---

*[components/script/dom/webglbuffer.rs, line 79 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8948#-K6UH_Db-ZDgnscgQIs0:-K6UH_Db-ZDgnscgQIs1:319469014) ([raw file](https://github.com/servo/servo/blob/e65c90b917e6c6805acfb9d6426877223681dbed/components/script/dom/webglbuffer.rs#L79)):*
Please send the message to the renderer here instead of doing it in `BufferData`.

---

*[components/script/dom/webglrenderingcontext.rs, line 186 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8948#-K6UIdAUesecByf7sJKa:-K6UIdAUesecByf7sJKb:-253666767) ([raw file](https://github.com/servo/servo/blob/e65c90b917e6c6805acfb9d6426877223681dbed/components/script/dom/webglrenderingcontext.rs#L186)):*
There's a PR to handle this a bit more cleanly (#8970) and avoid repeating us too much, but I'll rebase it if this lands before so no problem :)

---

*[components/script/dom/webglrenderingcontext.rs, line 492 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8948#-K6UIAKr9ahUq0AGpRVb:-K6UIAKsOP34E8ysT_sS:1521523744) ([raw file](https://github.com/servo/servo/blob/e65c90b917e6c6805acfb9d6426877223681dbed/components/script/dom/webglrenderingcontext.rs#L492)):*
This should be `InvalidOperation` instead of `InvalidValue`.

---

*[components/script/dom/webglrenderingcontext.rs, line 501 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8948#-K6UK0mBMPsigBkQff6r:-K6UK0mCuQbPNdCYYg5B:-235978288) ([raw file](https://github.com/servo/servo/blob/e65c90b917e6c6805acfb9d6426877223681dbed/components/script/dom/webglrenderingcontext.rs#L501)):*
Maybe this could use the `byte_array_to_slice` function?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8948#-:-K6UJM0kLnhJ7Lz2qvo-:232142590)*

**Comment by simartin** [comment]
*[components/script/dom/webglrenderingcontext.rs, line 492 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8948#-K6UIAKr9ahUq0AGpRVb:-K6ULKgEaVsUDAg9rBIF:1449441928) ([raw file](https://github.com/servo/servo/blob/e65c90b917e6c6805acfb9d6426877223681dbed/components/script/dom/webglrenderingcontext.rs#L492)):*
You're right, thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8948)*

**Comment by simartin** [comment]
*[components/script/dom/webglrenderingcontext.rs, line 501 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8948#-K6UK0mBMPsigBkQff6r:-K6UMI1krVr55sfKCBnu:-123767392) ([raw file](https://github.com/servo/servo/blob/e65c90b917e6c6805acfb9d6426877223681dbed/components/script/dom/webglrenderingcontext.rs#L501)):*
Did not see this one, thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8948)*

**Comment by simartin** [comment]
Thanks for the review. Update is coming up.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8948#-:-K6UNCunP7KOFZwAslwe:-510865067)*

**Comment by ecoal95** [comment]
@bors-servo: r+

Nice work, thanks @simartin!

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 2 files at r2, 2 of 5 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8948#-:-K6h_yFRBmhRLhCEKtTa:1833295391)*

**Pull request merged**
