### PR TITLE
Update a few dependencies

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24213)

### CODE REVIEW

**Comment by CYBAI** [comment]
👀

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-011.html", 
    "line": 64280, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-005.html", 
    "line": 64977, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-014.html", 
    "line": 65148, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-016.html", 
    "line": 65842, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-009.html", 
    "line": 66887, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-004.html", 
    "line": 69496, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-010.html", 
    "line": 70051, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-006.html", 
    "line": 76623, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-007.html", 
    "line": 100593, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

**Comment by Eijebong** [comment]
Fun stuff. I can't repro those PASS locally. Are they new intermittent ?

**Comment by CYBAI** [comment]
@bors-servo retry

- let's wait and see 😆

**Comment by Eijebong** [comment]
Fine ! I'll update you then. No idea why they're not passing locally though

**Comment by jdm** [comment]
I'm curious to see if the tests pass on macos as well: https://treeherder.allizom.org/#/jobs?repo=servo-auto&revision=6cb7126471197799338b1270d9de50c62f749655

**Comment by jdm** [comment]
Indeed, the tests only pass on Linux for some reason.

**Comment by Eijebong** [comment]
Why does this need code changes ?

**Comment by jdm** [comment]
The test result ini files need to be marked as passing on Linux and failing on other platforms.

**Comment by Eijebong** [comment]
But CI was green everywhere ?

**Comment by jdm** [comment]
The CI result I linked to was from before fb81101672ece134d2b41670dcbf54ac7c12d106.

**Comment by jdm** [comment]
That's a lie, they never got a chance to run and I linked to the wrong CI revision. Ok!
@bors-servo r+

**Comment by CYBAI** [comment]
👀 

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-007.html", 
    "line": 78120, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-text/shaping/shaping-006.html", 
    "line": 85126, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

**Pull request closed without merging**
