### PR TITLE
Promise constructor

### LINKED ISSUE #22982: Promise::new crashes if no compartment has been entered
This sucks, because if the code that calls Promise::new is invoked via some DOM API from JS, it works fine. If it's invoked from code that runs directly from an message from the event loop, it is not, since we do not automatically enter any compartments in that case. It would be very helpful to modify the API in such a way that the caller is forced to enter a compartment.

### PR DESCRIPTION
**Pull request by AZWN**
In this PR, measures are taken that prevent the ```Promise::new``` constructor from being used outside a compartment.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22982 (GitHub issue number if applicable)

- [x] These changes do not require tests because no new functionality is added.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23158)

### CODE REVIEW

**Comment by AZWN** [comment]
@KiChjang I see the tests are passing. Is there still something that needs to be done for this PR?

**Comment by jdm** [comment]
Thanks! Even though these changes do not actually make any of the existing code any safer, it makes the unsafety of the existing code more clear, and makes it easier to recognize when we're adding new cases that could crash in the future.
@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #13480

**Comment by CYBAI** [comment]
@bors-servo retry

```
  ▶ TIMEOUT [expected OK] /url/urlsearchparams-constructor.any.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.3.0-devel
  │ alloc factor 0.010000 0.900000
  └ alloc factor 0.010000 0.900000
```

**Pull request merged**
