### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See individual commits for details.

### CODE REVIEW

**Comment by emilio** [comment]
r? for the layout changes @SimonSapin / @nox 

I need to squash too.

There's no behavior change for now, but I want to land this to make implementing `min()` / `max()` / etc. easier.

**Comment by atouchet** [comment]
@emilio if you are updating selectors could you also bump the version for #24574?

**Comment by emilio** [comment]
@atouchet will do

**Comment by CYBAI** [comment]
```
  ▶ Unexpected subtest result in /css/cssom/border-shorthand-serialization.html:
  └ PASS [expected FAIL] Declaration with border longhands and border-image is not serialized to a border shorthand declaration.
```

**Comment by emilio** [comment]
@bors-servo r=emilio,nox

 * nox reviewed the layout-2020 bits on IRC.

**Comment by CYBAI** [comment]
```
  ▶ TIMEOUT [expected PASS] /css/CSS2/floats-clear/floats-024.xht
  │ 
  │ 
  │ 
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ 18 threads are still running after shutdown (bad).
  ▶ TIMEOUT [expected PASS] /css/CSS2/floats-clear/floats-040.xht
  │ 
  │ 
  │ 
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ 18 threads are still running after shutdown (bad).
  │ 
  │ 
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ 19 threads are still running after shutdown (bad).
  ▶ TIMEOUT [expected FAIL] /css/CSS2/floats-clear/floats-015.xht
  │ 
  │ 
  │ 
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ 18 threads are still running after shutdown (bad).
```

Looks like  #24762 (or #25258?)

**Comment by jdm** [comment]
@bors-servo retry
* #24762

**Comment by emilio** [comment]
@bors-servo r=emilio,nox

 * Huh, what's up with bors?

**Comment by jdm** [comment]
@emilio https://build.servo.org/homu/queue/servo

**Comment by jdm** [comment]
@bots-servo retry

**Pull request merged**
