### PR TITLE
Implement WebIDL attribute PutForwards

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5894)

### CODE REVIEW

**Comment by nox** [comment]
This does not properly put in scope the forwarded attribute Methods trait, looking into it…

**Comment by nox** [comment]
Problem solved.

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/bindings/codegen/CodegenRust.py @ r3
- components/script/dom/bindings/codegen/parser/WebIDL.py @ r1

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 2810 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5894#-JoAMLCUnE2JcjquZnI8)** ([raw file](https://github.com/servo/servo/blob/49aaa57edd3b261844492aaa3278f1be9898e18b/components/script/dom/bindings/codegen/CodegenRust.py#L2810)):</sup>
Let's either make use of this or remove it.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4285 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5894#-JoANkljoDTmH4D3PCW8)** ([raw file](https://github.com/servo/servo/blob/49aaa57edd3b261844492aaa3278f1be9898e18b/components/script/dom/bindings/codegen/CodegenRust.py#L4285)):</sup>
Why can't we use attribute_arguments here?

---

<sup>**[components/script/dom/bindings/codegen/parser/WebIDL.py, line 1002 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5894#-JoAOJj3TBbMWkgf8Xv-)** ([raw file](https://github.com/servo/servo/blob/49aaa57edd3b261844492aaa3278f1be9898e18b/components/script/dom/bindings/codegen/parser/WebIDL.py#L1002)):</sup>
Are these changes imported from Gecko? We have a pretty good track record of keeping WebIDL.py up to date with upstream, and we should make use of their work here.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5894)

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/testbinding.rs @ r1
- components/script/dom/webidls/TestBinding.webidl @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5894)

**Comment by nox** [comment]
<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 2810 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5894#-JoAMLCUnE2JcjquZnI8)** ([raw file](https://github.com/servo/servo/blob/49aaa57edd3b261844492aaa3278f1be9898e18b/components/script/dom/bindings/codegen/CodegenRust.py#L2810)):</sup>
I forgot to throw it away.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4285 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5894#-JoANkljoDTmH4D3PCW8)** ([raw file](https://github.com/servo/servo/blob/49aaa57edd3b261844492aaa3278f1be9898e18b/components/script/dom/bindings/codegen/CodegenRust.py#L4285)):</sup>
Didn't try, just went directly to the simplest code.

---

<sup>**[components/script/dom/bindings/codegen/parser/WebIDL.py, line 1002 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5894#-JoAOJj3TBbMWkgf8Xv-)** ([raw file](https://github.com/servo/servo/blob/49aaa57edd3b261844492aaa3278f1be9898e18b/components/script/dom/bindings/codegen/parser/WebIDL.py#L1002)):</sup>
I didn't know there was an upstream. Where is it? That should be written in the file.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5894)

**Comment by nox** [comment]
@jdm 

The [code](http://mxr.mozilla.org/mozilla-central/source/dom/bindings/Codegen.py#8177) you linked me to is not ideal IMO, it just uses the JSAPI directly and won't let me get fancy once I implement Reflect (#5881). I want to be able to generate a reflected forwarded setter that will just set the attribute directly through Element::AttributeHandlers and whatnot, without even needing to use the getter.

Note that my changes to WebIDL.py could very well be upstream'd. They are nothing more than new checks and a small refactoring.

**Comment by jdm** [comment]
@Ms2ger Does the previous comment sound web-compatible?

**Comment by nox** [comment]
I reached this conclusion from:

 * https://dom.spec.whatwg.org/#concept-reflect
 * https://html.spec.whatwg.org/#reflecting-content-attributes-in-idl-attributes

More generally, I don't see how it would make sense for a reflecting IDL attribute to behave differently from the underlying reflected content attribut.

**Comment by Ms2ger** [comment]
I still believe the spec is crazy, but we should still follow it

**Comment by nox** [comment]
@Ms2ger What do you mean by follow it? In which way do I not follow it?

**Comment by nox** [comment]
@Ms2ger The only moment my assumptions aren't true is if the attribute is only [LenientThis], but in this case nothing at all is called anyway because the setter should stop at steps 5 or 7:

* If validThis is false and the attribute was not specified with the [LenientThis] extended attribute, then throw a TypeError.
* If validThis is false, then return.

Please show me one example where my assumptions break things.

**Comment by Ms2ger** [comment]
Think outside the box :)
```html
<pre>
<script>
function w(s) {
  document.body.firstChild.appendChild(new Text(s + "\n"))
}

var l = document.createElement("link");
w(l.getAttribute("sizes")) // null

l.sizes = "bar";
w(l.getAttribute("sizes")) // bar

Object.defineProperty(l.sizes, "value", {
  get: function() { return "foo" },
  set: function() { w("hi!") }
})
l.sizes = "baz"; // hi!
w(l.getAttribute("sizes")) // bar
</script>
</pre>
```

**Comment by nox** [comment]
I stand corrected, and you stand insane. :P Will dumb down my code.

**Comment by nox** [comment]
@Ms2ger What if I use JS_GetPropertyDescriptor and shortcut everything if they have been left untouched?

**Comment by Ms2ger** [comment]
Ew.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/script/dom/bindings/codegen/CodegenRust.py @ r4
- components/script/dom/bindings/codegen/parser/WebIDL.py @ r4

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 2855 \[r4\]](https://reviewable.io:443/reviews/servo/servo/5894#-JoieP921c8NcuxkpS5l)** ([raw file](https://github.com/servo/servo/blob/0000a9d1adda8c1737869289c1d9ad2361d26452/components/script/dom/bindings/codegen/CodegenRust.py#L2855)):</sup>
nit: no need for the surrounding ()

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5894)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 

---

Reviewed files:
- components/script/dom/bindings/codegen/CodegenRust.py @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5894)

**Pull request merged**
