### PR TITLE
Disable transform-abspos-{002,007}.htm.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11738)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* git timeout

**Comment by emilio** [comment]
@bors-servo: retry

 * OSX directory not empty failure.

**Comment by jdm** [comment]
@bors-servo: retry
* git timeout

**Comment by jdm** [comment]
@bors-servo: retry
* git timeout

**Pull request merged**
