### PR TITLE
Stop generating a parser.out file in the source.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9817)

### CODE REVIEW

**Comment by nox** [comment]
This needs a patch that is applied in update.sh.

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/bindings/codegen/parser/WebIDL.py, line 6442 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9817#-KBm2J4tsk6ZIz07lasI:-KBm2J4tsk6ZIz07lasJ:-159991806) ([raw file](https://github.com/servo/servo/blob/a2d5cea4e7b4318aacedcd90459a4b3fc7b77017/components/script/dom/bindings/codegen/parser/WebIDL.py#L6442)):*
`debug=False`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9817#-:-KBm2LlOyD6gwfbDdMeT:1458266033)*

**Comment by Ms2ger** [comment]
@bors-servo retry
* #9777

**Pull request merged**
