### PR TITLE
Update various crates.

### LINKED ISSUE #14681: Update the version of brotli used in the network code
There is a rare issue that could cause the brotli 1.0.6 crate to fail to decode a valid brotli file downloaded with server-side brotli compression enabled. The bug stemmed from break failing to exit the outer for loop when a series of C gotos were converted into rust switches/loops 

The issue has been resolved in 1.0.7 and 1.0.7 has been successfully tested on over 10 million files with a large variety of brotli compressor settings.

it would be ideal to bump the crate version servo uses from 1.0.6 to 1.0.7 in this file
https://github.com/servo/servo/blob/4eb653817f87e5fb47de34356f558eb76ecbca9f/components/net/Cargo.toml#L14
to the newest here
https://crates.io/crates/brotli

### PR DESCRIPTION
**Pull request by Ms2ger**
Fixes #14681.

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14687)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
  File "/home/servo/buildbot/master/factories.py", line 40, in run
    got_rev, rev
exceptions.Exception: Actual commit (931f7592076404e57f2c2fcefd8bbac404cf967b) differs from requested commit (e4f994eaae6574a1b2ef2c71fb367a7a9c53ca5c)
```

Infra failure?

@bors-servo retry

**Comment by Ms2ger** [comment]
@bors-servo r=emilio

Reverted the rust-url update

**Comment by KiChjang** [comment]
@bors-servo retry
* servo/saltfs#565

**Pull request merged**
