### PR TITLE
Issue #8352: Dispatch mozbrowsershowmodalprompt event for alert().

### PR DESCRIPTION
**Pull request by simartin**
Fixes https://github.com/servo/servo/issues/8352

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8863)

### CODE REVIEW

**Comment by KiChjang** [comment]
```

Ran 3730 tests finished in 861.0 seconds.
  • 3729 ran as expected. 707 tests skipped.
  • 1 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/css/iframe/multiple_external.html
  └   → /_mozilla/css/iframe/multiple_external.html d9d9e489bc5b4508c01b06c7ff92f19dcc2ece3c
/_mozilla/css/iframe/multiple_external_ref.html 131ec8ef710d4c0e87db17a777f80e7f02f0aad0
Testing d9d9e489bc5b4508c01b06c7ff92f19dcc2ece3c == 131ec8ef710d4c0e87db17a777f80e7f02f0aad0
```

**Comment by jdm** [comment]
That's probably an unrelated iframe failure that would be fixed by #8612.

**Comment by simartin** [comment]
It looks like this indeed:

simon$ ./mach test-wpt _mozilla/css/iframe/multiple_external.html
Running 1 tests in web-platform-tests

Ran 1 tests finished in 1.0 seconds.
  • 1 ran as expected. 0 tests skipped.

**Comment by simartin** [comment]
PR rebased.

**Comment by jdm** [comment]
This looks great! We can merge this if it's rebased; sorry for the delay!
-S-awaiting-review 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/dom/window.rs, line 396 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8863#-K5kC07ebmDj9f9lJa7C:-K5kC07ebmDj9f9lJa7D:1699139465) ([raw file](https://github.com/servo/servo/blob/fa94aaf5b333cc7cf611bdaa92eb5a6bccc1c831/components/script/dom/window.rs#L396)):*
`see executorservo.py in wptrunner`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8863#-:-K5kCUQCI8-7ZRNy1MAH:1798888623)*

**Comment by simartin** [comment]
Thanks for the review! I've taken your comment into account and rebased.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8863#-:-K5u5L4FaBXw3lSQa1zm:-864783591)*

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8863#-:-K6-FDAn_bYcbz5MftoY:-317921516)*

**Pull request merged**
