### PR TITLE
Implements "upload listener flag" for XHR

### LINKED ISSUE #24955: GET/HEAD XHR are seeing upload events
WPT xhr/send-entity-body-get-head-async.htm calls .send("TEST") on GET and HEAD XMLHttpRequests. Step 3 of https://xhr.spec.whatwg.org/#the-send()-method should replace that "TEST" with null, and Servo is implementing that step. Later, the lack of a body should mean no events get sent to .upload, yet events incorrectly do.

### PR DESCRIPTION
**Pull request by ghostd**
Implements the ["upload listener flag"](https://xhr.spec.whatwg.org/#upload-listener-flag)

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #24955

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by CYBAI** [comment]
@bors-servo try=wpt

- I tried to read the corresponding specs and it looks good to me! 👀

**Comment by CYBAI** [comment]
Looks like there are more PASS tests! but also some FAIL and TIMEOUT tests. Might need to investigate if they are expected FAIL/TIMEOUT/PASS or not 👀

<details>

```
  â–¶ Unexpected subtest result in /xhr/abort-during-upload.any.html:
  â”‚ FAIL [expected PASS] XMLHttpRequest: abort() while sending data
  â”‚   â†’ assert_equals: expected "upload.loadstart(0,9999,true)" but got "readystatechange(4)"
  â”‚ 
  â”‚ global.assert_xhr_event_order_matches@http://web-platform.test:8000/xhr/resources/xmlhttprequest-event-order.js:74:20
  â”‚ @http://web-platform.test:8000/xhr/abort-during-upload.any.js:11:43
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”‚ @http://web-platform.test:8000/xhr/abort-during-upload.any.js:10:16
  â”‚ @http://web-platform.test:8000/xhr/abort-during-upload.any.js:16:16
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” @http://web-platform.test:8000/xhr/abort-during-upload.any.js:5:12


  â–¶ Unexpected subtest result in /xhr/send-network-error-async-events.sub.htm:
  â”‚ FAIL [expected PASS] XMLHttpRequest: The send() method: Fire a progress event named error when Network error happens (synchronous flag is unset)
  â”‚   â†’ assert_array_equals: lengths differ, expected array ["loadstart", "upload.loadstart", 4, "upload.error", "upload.loadend", "error", "loadend"] length 7, got ["loadstart", 4, "upload.error", "upload.loadend", "error", "loadend"] length 6
  â”‚ 
  â”‚ xhr.onloadend<@http://web-platform.test:8000/xhr/send-network-error-async-events.sub.htm:34:36
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:2018:32


  â–¶ TIMEOUT [expected OK] /xhr/abort-upload-event-abort.any.html
  â”‚ 
  â”‚ error: XDG_RUNTIME_DIR not set in the environment.
  â”” libEGL warning: No hardware driver found, falling back to software rendering

  â–¶ Unexpected subtest result in /xhr/abort-upload-event-abort.any.html:
  â”‚ TIMEOUT [expected PASS] XMLHttpRequest: The abort() method: Fire a progress event named abort on the XMLHttpRequestUpload object
  â””   â†’ Test timed out


  â–¶ TIMEOUT [expected OK] /xhr/abort-upload-event-loadend.any.worker.html
  â”‚ 
  â”‚ error: XDG_RUNTIME_DIR not set in the environment.
  â”” libEGL warning: No hardware driver found, falling back to software rendering

  â–¶ Unexpected subtest result in /xhr/abort-upload-event-loadend.any.worker.html:
  â”‚ TIMEOUT [expected PASS] XMLHttpRequest: The abort() method: Fire a progress event named loadend on the XMLHttpRequestUpload object
  â””   â†’ Test timed out


  â–¶ Unexpected subtest result in /xhr/event-upload-progress.any.worker.html:
  â”” PASS [expected FAIL] Upload events registered too late (http://www1.web-platform.test:8000/xhr/resources/corsenabled.py)

  â–¶ Unexpected subtest result in /xhr/event-upload-progress.any.worker.html:
  â”” PASS [expected FAIL] Upload events registered too late (resources/redirect.py?code=307&location=http://www1.web-platform.test:8000/xhr/resources/corsenabled.py)


  â–¶ Unexpected subtest result in /xhr/abort-during-upload.any.worker.html:
  â”‚ FAIL [expected PASS] XMLHttpRequest: abort() while sending data
  â”‚   â†’ assert_equals: expected "upload.loadstart(0,9999,true)" but got "readystatechange(4)"
  â”‚ 
  â”‚ global.assert_xhr_event_order_matches@http://web-platform.test:8000/xhr/resources/xmlhttprequest-event-order.js:74:20
  â”‚ @http://web-platform.test:8000/xhr/abort-during-upload.any.js:11:43
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”‚ @http://web-platform.test:8000/xhr/abort-during-upload.any.js:10:16
  â”‚ @http://web-platform.test:8000/xhr/abort-during-upload.any.js:16:16
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”‚ @http://web-platform.test:8000/xhr/abort-during-upload.any.js:5:12
  â”” @http://web-platform.test:8000/xhr/abort-during-upload.any.worker.js:9:14


  â–¶ TIMEOUT [expected OK] /xhr/abort-upload-event-loadend.any.html
  â”‚ 
  â”‚ error: XDG_RUNTIME_DIR not set in the environment.
  â”” libEGL warning: No hardware driver found, falling back to software rendering

  â–¶ Unexpected subtest result in /xhr/abort-upload-event-loadend.any.html:
  â”‚ TIMEOUT [expected PASS] XMLHttpRequest: The abort() method: Fire a progress event named loadend on the XMLHttpRequestUpload object
  â””   â†’ Test timed out


  â–¶ Unexpected subtest result in /xhr/abort-event-order.htm:
  â”‚ FAIL [expected PASS] XMLHttpRequest: The abort() method: abort and loadend events
  â”‚   â†’ assert_equals: expected "upload.abort(0,0,false)" but got "abort(0,0,false)"
  â”‚ 
  â”‚ global.assert_xhr_event_order_matches@http://web-platform.test:8000/xhr/resources/xmlhttprequest-event-order.js:74:20
  â”‚ VerifyResult/<@http://web-platform.test:8000/xhr/abort-event-order.htm:40:51
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”‚ VerifyResult@http://web-platform.test:8000/xhr/abort-event-order.htm:38:22
  â”‚ @http://web-platform.test:8000/xhr/abort-event-order.htm:29:25
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”‚ @http://web-platform.test:8000/xhr/abort-event-order.htm:23:22
  â”‚ @http://web-platform.test:8000/xhr/abort-event-order.htm:48:17
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” @http://web-platform.test:8000/xhr/abort-event-order.htm:17:14


  â–¶ Unexpected subtest result in /xhr/event-error-order.sub.html:
  â”‚ FAIL [expected PASS] XMLHttpRequest: event - error (order of events)
  â”‚   â†’ assert_equals: expected "upload.loadstart(0,12,true)" but got "readystatechange(4)"
  â”‚ 
  â”‚ global.assert_xhr_event_order_matches@http://web-platform.test:8000/xhr/resources/xmlhttprequest-event-order.js:74:20
  â”‚ @http://web-platform.test:8000/xhr/event-error-order.sub.html:25:51
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” @http://web-platform.test:8000/xhr/event-error-order.sub.html:23:22


  â–¶ Unexpected subtest result in /xhr/event-upload-progress-crossorigin.any.worker.html:
  â”” PASS [expected FAIL] Upload events registered too late (http://www1.web-platform.test:8000/xhr/resources/corsenabled.py)

  â–¶ Unexpected subtest result in /xhr/event-upload-progress-crossorigin.any.worker.html:
  â”” PASS [expected FAIL] Upload events registered too late (resources/redirect.py?code=307&location=http://www1.web-platform.test:8000/xhr/resources/corsenabled.py)


  â–¶ Unexpected subtest result in /xhr/send-response-event-order.htm:
  â”‚ FAIL [expected PASS] XMLHttpRequest: The send() method: event order when synchronous flag is unset
  â”‚   â†’ assert_equals: expected "upload.loadstart(0,12,true)" but got "upload.progress(12,12,true)"
  â”‚ 
  â”‚ global.assert_xhr_event_order_matches@http://web-platform.test:8000/xhr/resources/xmlhttprequest-event-order.js:74:20
  â”‚ @http://web-platform.test:8000/xhr/send-response-event-order.htm:31:47
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:2002:35


  â–¶ TIMEOUT [expected OK] /xhr/send-response-upload-event-loadstart.htm
  â”‚ 
  â”‚ error: XDG_RUNTIME_DIR not set in the environment.
  â”” libEGL warning: No hardware driver found, falling back to software rendering

  â–¶ Unexpected subtest result in /xhr/send-response-upload-event-loadstart.htm:
  â”‚ TIMEOUT [expected PASS] XMLHttpRequest: The send() method: Fire a progress event named loadstart on the XMLHttpRequestUpload (synchronous flag is unset)
  â””   â†’ Test timed out


  â–¶ TIMEOUT [expected OK] /xhr/abort-upload-event-abort.any.worker.html
  â”‚ 
  â”‚ error: XDG_RUNTIME_DIR not set in the environment.
  â”” libEGL warning: No hardware driver found, falling back to software rendering

  â–¶ Unexpected subtest result in /xhr/abort-upload-event-abort.any.worker.html:
  â”‚ TIMEOUT [expected PASS] XMLHttpRequest: The abort() method: Fire a progress event named abort on the XMLHttpRequestUpload object
  â””   â†’ Test timed out


  â–¶ Unexpected subtest result in /xhr/event-upload-progress-crossorigin.any.html:
  â”” PASS [expected FAIL] Upload events registered too late (http://www1.web-platform.test:8000/xhr/resources/corsenabled.py)

  â–¶ Unexpected subtest result in /xhr/event-upload-progress-crossorigin.any.html:
  â”” PASS [expected FAIL] Upload events registered too late (resources/redirect.py?code=307&location=http://www1.web-platform.test:8000/xhr/resources/corsenabled.py)


  â–¶ Unexpected subtest result in /xhr/event-timeout-order.any.html:
  â”‚ FAIL [expected PASS] XMLHttpRequest: event - timeout (order of events)
  â”‚   â†’ assert_equals: expected "upload.loadstart(0,12,true)" but got "readystatechange(4)"
  â”‚ 
  â”‚ global.assert_xhr_event_order_matches@http://web-platform.test:8000/xhr/resources/xmlhttprequest-event-order.js:74:20
  â”‚ @http://web-platform.test:8000/xhr/event-timeout-order.any.js:10:43
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” @http://web-platform.test:8000/xhr/event-timeout-order.any.js:9:14


  â–¶ Unexpected subtest result in /xhr/event-loadstart-upload.any.html:
  â”‚ FAIL [expected PASS] XMLHttpRequest: The send() method: Fire a progress event named loadstart on upload object (synchronous flag is unset)
  â”‚   â†’ assert_unreached: onloadstart not called. Reached unreachable code
  â”‚ 
  â”‚ client.onreadystatechange<@http://web-platform.test:8000/xhr/event-loadstart-upload.any.js:15:23
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:2002:35


  â–¶ Unexpected subtest result in /xhr/event-timeout-order.any.worker.html:
  â”‚ FAIL [expected PASS] XMLHttpRequest: event - timeout (order of events)
  â”‚   â†’ assert_equals: expected "upload.loadstart(0,12,true)" but got "readystatechange(4)"
  â”‚ 
  â”‚ global.assert_xhr_event_order_matches@http://web-platform.test:8000/xhr/resources/xmlhttprequest-event-order.js:74:20
  â”‚ @http://web-platform.test:8000/xhr/event-timeout-order.any.js:10:43
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” @http://web-platform.test:8000/xhr/event-timeout-order.any.js:9:14


  â–¶ Unexpected subtest result in /xhr/event-upload-progress.any.html:
  â”” PASS [expected FAIL] Upload events registered too late (http://www1.web-platform.test:8000/xhr/resources/corsenabled.py)

  â–¶ Unexpected subtest result in /xhr/event-upload-progress.any.html:
  â”” PASS [expected FAIL] Upload events registered too late (resources/redirect.py?code=307&location=http://www1.web-platform.test:8000/xhr/resources/corsenabled.py)


  â–¶ Unexpected subtest result in /xhr/event-loadstart-upload.any.worker.html:
  â”‚ FAIL [expected PASS] XMLHttpRequest: The send() method: Fire a progress event named loadstart on upload object (synchronous flag is unset)
  â”‚   â†’ assert_unreached: onloadstart not called. Reached unreachable code
  â”‚ 
  â”‚ client.onreadystatechange<@http://web-platform.test:8000/xhr/event-loadstart-upload.any.js:15:23
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:2002:35


  â–¶ Unexpected subtest result in /xhr/send-redirect-post-upload.htm:
  â”‚ FAIL [expected PASS] XMLHttpRequest: The send() method: POSTing to URL that redirects (301)
  â”‚   â†’ assert_array_equals: events firing in expected order and states lengths differ, expected array ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 8, got ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 7
  â”‚ FAIL [expected PASS] XMLHttpRequest: The send() method: POSTing to URL that redirects (302)
  â”‚   â†’ assert_array_equals: events firing in expected order and states lengths differ, expected array ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 8, got ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 7
  â”‚ FAIL [expected PASS] XMLHttpRequest: The send() method: POSTing to URL that redirects (303)
  â”‚   â†’ assert_array_equals: events firing in expected order and states lengths differ, expected array ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 8, got ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 7
  â”‚ FAIL [expected PASS] XMLHttpRequest: The send() method: POSTing to URL that redirects (307 (string))
  â”‚   â†’ assert_array_equals: events firing in expected order and states lengths differ, expected array ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 3", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 9, got ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 3", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 8
  â”‚ FAIL [expected PASS] XMLHttpRequest: The send() method: POSTing to URL that redirects (307 (blob))
  â”‚   â†’ assert_array_equals: events firing in expected order and states lengths differ, expected array ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 3", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 9, got ["xhr onreadystatechange 1", "xhr loadstart 1", "upload loadend 1", "xhr onreadystatechange 2", "xhr onreadystatechange 3", "xhr onreadystatechange 4", "xhr load 4", "xhr loadend 4"] length 8
  â”‚ 
  â”‚ testRedirectPost/</xhr.onloadend<@http://web-platform.test:8000/xhr/send-redirect-post-upload.htm:119:36
  â”‚ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  â”” Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:2002:35
  ▶ Unexpected subtest result in /cors/late-upload-events.htm:
  └ PASS [expected FAIL] Late listeners: No preflight
  ▶ Unexpected subtest result in /cors/late-upload-events.htm:
  └ PASS [expected FAIL] Late listeners: Preflight
```

</details>

**Comment by ghostd** [comment]
Hi @CYBAI 
I fixed the missing 'loadstart' event. It seems some steps are not in the same order in the code than in the specification.

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Pull request merged**
