### PR TITLE
webgl: Track the current program, implement some uniform functions, and nits

### PR DESCRIPTION
**Pull request by emilio**
Was done while implementing sequence arguments.

Depends on #9056.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9107)

### CODE REVIEW

**Comment by jdm** [comment]
@simartin Since you've done some work in the WebGL code before, would you be interested in reviewing these changes?

**Comment by simartin** [comment]
Sure, I can take a look, thanks for suggesting :-)

**Comment by ecoal95** [comment]
Now that #9056 has landed this is ready for review :P 

r? @simartin

**Comment by simartin** [comment]
*[components/canvas/webgl_paint_thread.rs, line 160 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9107#-K7ry00nZmpaQzV3bSy8:-K7ry00nZmpaQzV3bSy9:-1661590640) ([raw file](https://github.com/servo/servo/blob/c97d557720b2ef312b964534bd511d45161a2729/components/canvas/webgl_paint_thread.rs#L160)):*
I fail to understand why you remove Uniform4fv

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9107)*

**Comment by ecoal95** [comment]
`Uniform4fv([x, y, z, u])` is equivalent to `Uniform4f(x, y, z, u)`, so I just defined the first in terms of the second.

**Comment by simartin** [comment]
*[components/canvas/webgl_paint_thread.rs, line 188 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9107#-K7rzCbn86blNxD_SEGC:-K7rzCbn86blNxD_SEGD:-1754252503) ([raw file](https://github.com/servo/servo/blob/e030281b0967e5b8095d08c79b155791e3c30a56/components/canvas/webgl_paint_thread.rs#L188)):*
Wouldn't assert!(error != gl::NO_ERROR, "Unexpected WebGL error: {:x}", error); be more concise and as readable?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9107)*

**Comment by ecoal95** [comment]
Sure! Will change it ASAP (I'm on my phone right no, so no reviewable for me :/)

**Comment by simartin** [comment]
*[components/script/dom/webglrenderingcontext.rs, line 957 \[r3\]](https://reviewable.io:443/reviews/servo/servo/9107#-K7s-oM5EL35PjQ5s3cT:-K7s-oM5EL35PjQ5s3cU:-286726177) ([raw file](https://github.com/servo/servo/blob/e030281b0967e5b8095d08c79b155791e3c30a56/components/script/dom/webglrenderingcontext.rs#L957)):*
data.is_empty() maybe?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9107)*

**Comment by ecoal95** [comment]
Yup! Good catch :P

**Comment by simartin** [comment]
Apart from my minor comment, it looks good to me, thanks!

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9107#-:-K7s1hBq2riP5pbfaVLf:-1905509182)*

**Comment by jdm** [comment]
@simartin Just so you know, you can make multiple comments in the reviewable interface and then click the publish button at the end to publish them all at the same time. That usually results in less email for other people :)

**Comment by ecoal95** [comment]
Not sure what's the best way to do it:

@bors-servo: delegate=simartin

**Comment by KiChjang** [comment]
@ecoal95 Since you're a reviewer now, you can name anyone with r=<name>. You do not need to delegate first before you name them.

**Comment by jdm** [comment]
@bors-servo: retry
* #9148

**Pull request merged**
