### PR TITLE
Remove HTMLFontElement::color parsed attribute value

### PR DESCRIPTION
**Pull request by frewsxcv**
Part of #7863

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8411)

### CODE REVIEW

**Comment by jdm** [comment]
Shouldn't SetColor still be using a macro instead?

**Comment by frewsxcv** [comment]
> Shouldn't SetColor still be using a macro instead?

If you're suggesting that I should use `make_setter!`, that macro sets the `AttrValue` to `AttrValue::Sring`, which is not what you want.

If you're suggesting that I should use `make_color_setter`, that macro does not exist (yet). If you want, I can make it and add it to this PR.

**Comment by eefriedman** [comment]
I have an implementation of the macro in #8404

**Comment by eefriedman** [comment]
Obsoleted by #8404.

**Comment by frewsxcv** [comment]
:cry: :+1:

**Pull request closed without merging**
