### PR TITLE
style: Spring cleanup

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18537)

### CODE REVIEW

**Comment by emilio** [comment]
r? @nox 

(I had time in the flight to do more than watching made in abyss :P)

**Comment by emilio** [comment]
@bors-servo retry

 * git update

**Comment by SimonSapin** [comment]
```
command timed out: 1200 seconds without output running ['env', 'PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig', './mach', 'build', '--release'], attempting to kill
```

@bors-servo retry

**Comment by emilio** [comment]
This is green on Geckotry

**Comment by emilio** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=191fc4ff50ec3192ee856ea2153f94475a059beb

**Pull request merged**
