### PR TITLE
Bug 1414147 - Move fontSmoothingBackgroundColor from nsStyleUserInterface to nsFont, stylo changes.

### PR DESCRIPTION
**Pull request by mstange**
This will need to land in concert with [bug 1414147](https://bugzilla.mozilla.org/show_bug.cgi?id=1414147). Please don't r+ until the patch in that bug has been r+ed.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they are required to make the Gecko build pass

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19105)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0609]: no field `fontSmoothingBackgroundColor` on type `gecko_bindings::structs::root::nsFont`

     --> /home/travis/build/servo/servo/target/geckolib/debug/build/style-3cefbc3746f0a7b0/out/gecko_properties.rs:10558:26

      |

10558 |         self.gecko.mFont.fontSmoothingBackgroundColor = convert_rgba_to_nscolor(&v);

      |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `smoothing`?

error[E0609]: no field `fontSmoothingBackgroundColor` on type `gecko_bindings::structs::root::nsFont`

     --> /home/travis/build/servo/servo/target/geckolib/debug/build/style-3cefbc3746f0a7b0/out/gecko_properties.rs:10563:26

      |

10563 |         self.gecko.mFont.fontSmoothingBackgroundColor = other.gecko.mFont.fontSmoothingBackgroundColor;

      |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `smoothing`?

error[E0609]: no field `fontSmoothingBackgroundColor` on type `gecko_bindings::structs::root::nsFont`

     --> /home/travis/build/servo/servo/target/geckolib/debug/build/style-3cefbc3746f0a7b0/out/gecko_properties.rs:10563:75

      |

10563 |         self.gecko.mFont.fontSmoothingBackgroundColor = other.gecko.mFont.fontSmoothingBackgroundColor;

      |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `smoothing`?

error[E0609]: no field `fontSmoothingBackgroundColor` on type `gecko_bindings::structs::root::nsFont`

     --> /home/travis/build/servo/servo/target/geckolib/debug/build/style-3cefbc3746f0a7b0/out/gecko_properties.rs:10573:50

      |

10573 |         convert_nscolor_to_rgba(self.gecko.mFont.fontSmoothingBackgroundColor)

      |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `smoothing`?

error: aborting due to 4 previous errors

error: Could not compile `style`.
```
This looks like you need to update the gecko bindings that are in-tree at `components/style/gecko/generated/structs.rs`.

**Comment by emilio** [comment]
This just means that you need to update the bindings. If you have a try
run or a release build, you can just copy the `rust_bindings` artifact
into `components/style/gecko/generated/`.

Can help out if you want, thanks for doing this!

**Comment by mstange** [comment]
Thanks for the help! I'll fix this up once I've figured out the test failures on the Gecko patch.

**Comment by mstange** [comment]
This is now ready for review. r? @emilio

**Comment by mstange** [comment]
I grabbed the new structs.rs from [this try push](https://treeherder.mozilla.org/#/jobs?repo=try&revision=7182ced50b2ceac65b93504797e808379dc3758e&selectedJob=142157577) which includes the autoland push with #19113.

**Comment by emilio** [comment]
@bors-servo delegate+

Looks good to me, just comment with `@bors-servo r=emilio` when you want to merge this.

**Comment by emilio** [comment]
@bors-servo r-

Sigh, bors doesn't understand code comments. Anyway, feel free to land it when you please :)

**Comment by mstange** [comment]
Thanks! Let's see if this works:

@bors-servo r=emilio

**Pull request merged**
