### PR TITLE
Use an Atom for Event.type

### PR DESCRIPTION
**Pull request by dzbarsky**
Depends on https://github.com/servo/string-cache/pull/113

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8193)

### CODE REVIEW

**Comment by nox** [comment]
Just two nits.

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/event.rs, line 67 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8193#-K1WB_s2v5lSGG6XZh8p)** ([raw file](https://github.com/servo/servo/blob/3777b562484f18aaae5dc4add457f790f8649d26/components/script/dom/event.rs#L67)):</sup>
Keep the old name and do `atom!("")`.


---

<sup>**[components/script/dom/event.rs, line 172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8193#-K1WBxFdfgazQB9AGRiC)** ([raw file](https://github.com/servo/servo/blob/3777b562484f18aaae5dc4add457f790f8649d26/components/script/dom/event.rs#L172)):</sup>
You shouldn't need the explicit deref nor `as_slice`, AFAICT.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8193)

**Comment by dzbarsky** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/event.rs, line 172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8193#-K1WBxFdfgazQB9AGRiC)** ([raw file](https://github.com/servo/servo/blob/3777b562484f18aaae5dc4add457f790f8649d26/components/script/dom/event.rs#L172)):</sup>
Need the as_slice to convert Atom to str. But the deref is gone now.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8193)

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[components/script/dom/event.rs, line 172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8193#-K1WBxFdfgazQB9AGRiC)** ([raw file](https://github.com/servo/servo/blob/3777b562484f18aaae5dc4add457f790f8649d26/components/script/dom/event.rs#L172)):</sup>
Oh I see. Explicit deref was actually the way to go it seems. See how `Attr::Value` is written, you should be able to do the same.

```rust
fn Value(&self) -> DOMString {
    (**self.value()).to_owned()
}
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8193)

**Comment by nox** [comment]
@jdm Why did you remove S-blocked-on-external? The PR was merged but the dependency not updated.

**Comment by jdm** [comment]
Ah, I tend to use the label only to indicate that the merge state of other PRs.

**Comment by eefriedman** [comment]
Is this ready to be merged?

**Comment by dzbarsky** [comment]
Yep.

**Comment by nox** [comment]
@bors-servo r+

-S-blocked-on-external


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8193)

**Comment by Manishearth** [comment]
(Manually cancelled, tree is closed, re-r+ later, please)

**Comment by dzbarsky** [comment]
Rebased, can someone mark this r+ again?

**Pull request merged**
