### PR TITLE
bump winit version to the 0.26

### PR DESCRIPTION
**Pull request by okias**
Signed-off-by: David Heidelberg <david@ixit.cz>

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by jdm** [comment]
I think there may be changes to Cargo.lock missing? Also https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section is generally easier than updating every Cargo.toml file that references a particular crate.

**Comment by jdm** [comment]
I think the build error comes from having two versions of pin-project-internal present. The older version comes from async-tungstenite, and we're using a much older version. You should try updating that crate to a more recent one.

**Comment by okias** [comment]
> I think the build error comes from having two versions of pin-project-internal present. The older version (0.4.22) comes from async-tungstenite, and we're using a much older version of that (0.7). You should try updating that crate to a more recent one.

internally I did cargo update on whole servo project, but I guess that shouldn't be part of the PR, right? Should I upgrade crates one by one?

**Comment by jdm** [comment]
Yes, it's preferable to do the minimum set of updates required. It makes it easier to track down regressions.

**Comment by jdm** [comment]
The tungestenite upgrade isn't completely straightforward, so I'm preparing a PR to do that separately.

**Comment by jdm** [comment]
I think the build errors that you're seeing are caused by updating the various Cargo.toml files to point to new git locations. Instead of changing all of them, only the patches in the root Cargo.toml should be present.

**Comment by jdm** [comment]
Windows UWP arm64 build is broken:
```
error[E0432]: unresolved import `crate::platform_impl::platform::event_loop::WindowLongPtr`
  --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\window.rs:44:51
   |
44 |         event_loop::{self, EventLoopWindowTarget, WindowLongPtr, DESTROY_MSG_ID},
   |                                                   ^^^^^^^^^^^^^ no `WindowLongPtr` in `platform_impl::platform::event_loop`

error[E0412]: cannot find type `WindowLongPtr` in this scope
   --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:654:58
    |
654 |             (winuser::WS_VISIBLE | winuser::WS_POPUP) as WindowLongPtr,
    |                                                          ^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `WindowLongPtr` in this scope
   --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:676:26
    |
676 |             input_ptr as WindowLongPtr,
    |                          ^^^^^^^^^^^^^ not found in this scope
```

macOS build is broken:
```
warning: unused import: `WindowBuilderExtMacOS`
  --> ports/winit/headed_window.rs:15:48
   |
15 | use winit::platform::macos::{ActivationPolicy, WindowBuilderExtMacOS};
   |                                                ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0599]: no method named `with_activation_policy` found for struct `WindowBuilder` in the current scope
  --> ports/winit/headed_window.rs:58:27
   |
58 |         builder = builder.with_activation_policy(ActivationPolicy::Prohibited)
   |                           ^^^^^^^^^^^^^^^^^^^^^^ method not found in `WindowBuilder`
```

**Pull request closed without merging**
