### PR TITLE
Try to fix incremental_trailing_whitespace_a.html

### PR DESCRIPTION
**Pull request by emilio**
This includes https://github.com/w3c/wptrunner/pull/219

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14285)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Drop the wptrunner change, please.

**Comment by emilio** [comment]
On Sat, Nov 19, 2016 at 06:50:01AM -0800, Servo Greeter wrote:
>       ▶ TIMEOUT [expected PASS] /_mozilla/css/incremental_trailing_whitespace_a.html
>       │ 
>       │ VMware, Inc.
>       │ Gallium 0.4 on softpipe
>       └ 3.3 (Core Profile) Mesa 12.0.1

That's success... :(

**Comment by emilio** [comment]
Ok, the compositor wasn't processing animations in the case the image output was not stable, which was why this test was timing out permanently. Let's see how the infra looks like with the last patch.

@bors-servo try

**Comment by emilio** [comment]
I bet now it's going to perma-fail in automation because of #13865...

**Comment by jdm** [comment]
What do you want to do with this PR, @emilio?

**Comment by emilio** [comment]
This would need more work. The way we decide how to take a screenshot in presence of animations is dubious, but this is not the correct fix for that.

**Pull request closed without merging**
