### PR TITLE
style: Cleanup StyleBuilder. 

### PR DESCRIPTION
**Pull request by emilio**
This is in preparation of a cascade optimization for custom properties.

This fixes various fishiness around our StyleBuilder stuff. In particular,
StyleBuilder::for_derived_style (renamed to for_animation) is only used to
compute specified values, and thus doesn't need to know about rules, visited
style, or other things like that.

The flag propagation that was done in StyleAdjuster is now done in StyleBuilder,
since we know beforehand which ones are always inherited, and it simplified the
callers and the StyleAdjuster code. It also fixed some fishiness wrt which flags
were propagated to anon boxes and text.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19935)

### CODE REVIEW

**Comment by emilio** [comment]
Here's a try run (orange is either known intermittents or known stylo-chrome failures).

https://treeherder.mozilla.org/#/jobs?repo=try&revision=d37a389fe240aced0330f19730744e24e91acb13

**Review by nox — APPROVED** [review]
r=me with green geckotry

**Comment by emilio** [comment]
@bors-servo r=nox

Thanks!

**Comment by emilio** [comment]
@bors-servo retry

```
 error: failed to load source for a dependency on `webrender_api`
Caused by:
  Unable to update https://github.com/servo/webrender#c956e149
Caused by:
  Couldn't rmdir C:\Users\Administrator\.cargo\git\checkouts\webrender-c3596abe1cf4f320\c956e14
```

**Pull request merged**
