### PR TITLE
Run a couple WPT tests on Android on CI

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21242)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
 0:37.72 TEST_START: /_mozilla/mozilla/DOMParser.html
 0:39.23 pid:4903 Entering android_main
 0:39.23 pid:4903 Creating application thread
 0:39.23 pid:4903 ERROR 2018-07-24T21:32:43Z: script::dom::bindings::error: Error at :2:1 timeout is not defined
 0:53.27 TEST_END: TIMEOUT, expected OK
```

So far I did not reproduce this failure on my linux machine. I *think* that the undefined JS variable is the first argument in this call:

https://github.com/servo/servo/blob/65df9cb73a26db2c61100ee8f1ecd13c6a80e225/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/testharness_servodriver.js#L2

… and that it is supposed to be defined here:

https://github.com/servo/servo/blob/65df9cb73a26db2c61100ee8f1ecd13c6a80e225/tests/wpt/web-platform-tests/resources/testharness.js#L2232-L2237

… with `expose()` effectively doing `global_scope["timeout"] = timeout`.

The former script is injected through WebDriver here:

https://github.com/servo/servo/blob/65df9cb73a26db2c61100ee8f1ecd13c6a80e225/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservodriver.py#L220-L225

The latter is part of every test like this:

https://github.com/servo/servo/blob/234951e4b6d66891cd0cc9705f42e3ca16d9e3d5/tests/wpt/mozilla/tests/mozilla/DOMParser.html#L3

**Comment by SimonSapin** [comment]
Although this issue does not reproduce on my linux desktop (`mach test-wpt-android /_mozilla/mozilla/DOMParser.html --release` succeeds), it does reproduce on my linux laptop and on my macbook. Maybe it is timing-related (the desktop has a faster CPU), but adding `time.sleep(1)` before the `execute_async_script(…)` call does not help.

@jdm I’m running out of leads here, I don’t know what to try next.

**Comment by jdm** [comment]
The code you linked seems like a reasonable lead. What about debug output to show what code is actually executing?

**Comment by SimonSapin** [comment]
Mystery solved.

I was assuming that there would be no issue with the test loading `/resources/testharness.js`, but sprinkling some `console.log(something)` lines here and there showed that this is not happening at all on machines where I observe the issue. The test is not loading at all!

wptrunner asks Servo (in this case through WebDriver) to load URLs like `http://web-platform.test:8000/_mozilla/mozilla/DOMParser.html`. It also generates a temporary file with a syntax compatible with `/etc/hosts` that maps the hostname `web-platform.test` and some others to 127.0.01, and sets the `HOST_FILE` environment variable to tell Servo where to find it. However in the case of the Android emulator, the host file does not exist in the environment’s filesystem and environment variables are not propagated. So Servo gets a DNS error while trying to resolve the hostname `web-platform.test` and the document load fails. Additionally, because of https://github.com/servo/servo/issues/21248, that failure is not propagated back to the WebDriver client. The WebDriver command appears to succeed, so wptrunner carries on and only later times out when test results do not arrive.

As to what happens on my Linux desktop machine, DNS resolution in the Android emulator appears to be delegated to the host. And `web-platform.test` is valid on this machine because I had modified `/etc/hosts` by hand weeks ago when wptserve asked me to do so when I tried to use it without `mach`.

So what’s needed is, most likely:

* Adding a mechanism similar to `/sdcard/Android/data/com.mozilla.servo/files/android_params` to allow setting environment variables in the Servo process on Android. (With code at startup that reads a file and calls `std::env::set_var`.)
* Add support in `etc/run_in_headless_android_emulator.py` for the `HOST_FILE` env variable, similar to existing support for `--user-stylesheet`: use `adb push` to make the file available in the emulator’s filesystem, and then use new mechanism to propagate the env variable

**Comment by SimonSapin** [comment]
I ended up adding not a general mechanism for env variables, but a special case for `/sdcard/Android/data/com.mozilla.servo/files/android_hosts`.

I’ve tested this through SSH on `servo-linux-kvm1`, this should be ready to land.

**Comment by SimonSapin** [comment]
```
  Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
```

Flaky network?

@bors-servo retry

**Comment by SimonSapin** [comment]
Same again. https://github.com/pypa/pip/issues/5226#issuecomment-381354940 says:

> osx broke tls for pip < 9.0.3 a few days ago, which is why the emergency releases of pip 9.0.3 where made

On `servo-mac4.servo.org`:

```
server:build servo$ which pip
/usr/bin/pip
server:build servo$ pip --version
pip 8.1.2 from /Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg (python 2.7)
```

CC @edunham, @jdm

**Comment by jdm** [comment]
@bors-servo retry
* #13480

**Comment by jdm** [comment]
@bors-servo retry
* #10656

**Comment by jdm** [comment]
@bors-servo retry
* #21067

**Comment by jdm** [comment]
@bors-servo retry
* Websockets

**Pull request merged**
