### PR TITLE
New tidy rule

### PR DESCRIPTION
**Pull request by aeischeid**
addresses #10683 

I wasn't sure if this was only relevant for for-in loops or not so the regex doesn't check on that at all merely if `iter()` or `iter_mut()` are followed by anything other than whitespace.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11116)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Minor changes before we can land :)

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> Heads up! This PR modifies the following files:
>  * @wafflespeanut: python/tidy/servo_tidy_tests/test_tidy.py, python/tidy/servo_tidy_tests/rust_tidy.rs, python/tidy/servo_tidy/tidy.py</details>


---

Reviewed 2 of 3 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[python/tidy/servo_tidy_tests/rust_tidy.rs, line 34 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11116#-KHRLZ7QJxrtSNyJ4YmJ:-KHRLZ7R9nc4TOk33A2V:-1291196200) ([raw file](https://github.com/servo/servo/blob/57f54833c3b54f2d3f778481d7f41d9fee3e43b9/python/tidy/servo_tidy_tests/rust_tidy.rs#L34)):*
> ```Rust
> 
>         let v = vec![1, 2, 3, 4, 5];
>         //for foo in v.iter() {
> ```

Nit: We don't probably want a comment in our test file. It doesn't hurt, but it's not gonna be of any use :)

---

*[python/tidy/servo_tidy_tests/rust_tidy.rs, line 36 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11116#-KHRLgPLgDZGtkT6Vujj:-KHRLgPLgDZGtkT6Vujk:-727442624) ([raw file](https://github.com/servo/servo/blob/57f54833c3b54f2d3f778481d7f41d9fee3e43b9/python/tidy/servo_tidy_tests/rust_tidy.rs#L36)):*
> ```Rust
>         //for foo in v.iter() {
>         for foo in &v {
>             println!("{}", foo);
> ```

Since it's a test, this could just be `for foo in v.iter() {}`

---

*[python/tidy/servo_tidy_tests/rust_tidy.rs, line 39 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11116#-KHRL_pbU6D8lwS7KsSA:-KHRL_pcjku6M1FuuVVi:-1358475591) ([raw file](https://github.com/servo/servo/blob/57f54833c3b54f2d3f778481d7f41d9fee3e43b9/python/tidy/servo_tidy_tests/rust_tidy.rs#L39)):*
> ```Rust
>         }
> 
>         //for foo in v.iter_mut()
> ```

ditto on comment

---

*[python/tidy/servo_tidy_tests/rust_tidy.rs, line 41 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11116#-KHRLp62vkvckVZFRXXy:-KHRLp62vkvckVZFRXXz:169709252) ([raw file](https://github.com/servo/servo/blob/57f54833c3b54f2d3f778481d7f41d9fee3e43b9/python/tidy/servo_tidy_tests/rust_tidy.rs#L41)):*
> ```Rust
>         //for foo in v.iter_mut()
>         for foo in &mut v {
>             println!("{}", foo);
> ```

ditto on `{}`

---

*[python/tidy/servo_tidy_tests/test_tidy.py, line 74 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11116#-KHRLvuzDtSoEBWPI3XH:-KHRLvuzDtSoEBWPI3XI:1619548934) ([raw file](https://github.com/servo/servo/blob/57f54833c3b54f2d3f778481d7f41d9fee3e43b9/python/tidy/servo_tidy_tests/test_tidy.py#L74)):*
> ```Python
>         self.assertEqual('use &str instead of &String', errors.next()[2])
>         self.assertEqual('operators should go at the end of the first line', errors.next()[2])
>         self.assertEqual('use &x or &mut x instead of x.iter() or x.iter_mut()', errors.next()[2])
> ```

I'm curious, does this return only one error? We have two checks in `rust_tidy.rs`, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11116#-:-KHRNIOnkOIE2iJRdY1k:-51502464)*

**Comment by Wafflespeanut** [comment]
hmph, I'm pretty sure I reviewed the files at r2, but reviewable seemed to have left the comments on r1.

**Comment by jdm** [comment]
The test-tidy on TravisCI is very displeased with this change; presumably because it's catching all instances of `.iter()` even if they're not in a for loop.

**Comment by Wafflespeanut** [comment]
Oops, sorry, missed that. We should go for a regex that checks whether the `iter()` and `iter_mut()` methods are in a `for` loop before suggesting something.

**Comment by aeischeid** [comment]
ah okay. I can make the check so that it only checks on for loops. I wasn't sure if that was how it was supposed to be. I will clean up the test file comments too.

**Comment by jdm** [comment]
Word of warning - the lines that are reported by this new check will need to be fixed before it can merge.

**Comment by aeischeid** [comment]
ok, looks like quite a few lines, maybe a few dozen. I will see what I can do on that.

**Comment by aeischeid** [comment]
here is one caught by the rule that I am not sure what to do with.

what should this look like? 
```
for header in response.headers().iter() {}
```
changes to?
```
for header in &response.headers() {}

**Comment by Wafflespeanut** [comment]
@aeischeid Yep, that's the way :)

**Comment by Wafflespeanut** [comment]
Hm, some types can't be iterated unless we explicitly call `.iter()` on it

**Comment by aeischeid** [comment]
So, do I need to adjust the rule some?

**Comment by Wafflespeanut** [comment]
I'm not sure about going on adjusting the rules. @jdm You have any suggestion here?

**Comment by jdm** [comment]
If there are Servo-specific types that require us to call iter, we will either need to implement the [`IntoIterator` trait](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html) for them, or give up on this idea.

**Comment by jdm** [comment]
Figuring out the list of cases where this transformation does not currently work would be useful.

**Comment by aeischeid** [comment]
Let me know if/how the rule needs to be adjusted. Also, I can rebase this now if that would be helpful.

**Comment by aeischeid** [comment]
Is there a way I could help with "Figuring out the list of cases where this transformation does not currently work"?

**Comment by Wafflespeanut** [comment]
Yep, I think that's what we can do for now. We probably need those types that don't support auto-coercing into an iterator in a `for` loop. All those will be known at compile-time. Once you replace the `item.iter()` stuff with `&item` and run `./mach build`, the compiler will complain about the types that aren't iterator by themselves.

**Comment by Wafflespeanut** [comment]
For a start, the `Headers` type has an [`iter()` method](https://doc.servo.org/hyper/header/struct.Headers.html#method.iter) which throws an iterator, but it doesn't directly implement the [`Iterator` trait](https://doc.servo.org/core/iter/trait.Iterator.html). So, we won't be able to call it as `for header in &headers`. And, since `Headers` is in `hyper` crate, we also won't be able to implement the trait for it.

**Comment by jdm** [comment]
Have you made any progress, @aeischeid? Any questions?

**Comment by Wafflespeanut** [comment]
Closing this based on inactivity...

**Pull request closed without merging**
