### PR TITLE
Extract layout query code into layout/query.rs

### PR DESCRIPTION
**Pull request by nick-thompson**
Fix for #6787. I left the commits split up for ease of review, happy to squash when this gets accepted.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6836)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you for the PR.

@bors-servo r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6836)

**Comment by nick-thompson** [comment]
Happy to help! Do you want those squashed?

**Comment by dzbarsky** [comment]
Sorry for causing you conflicts! When you rebase, could you also pull out the iterators I added and squash?

**Comment by nick-thompson** [comment]
Yep, I'll get to that right now. Finally have some time to finish this up!

**Comment by nick-thompson** [comment]
@dzbarsky I think that's everything? `./mach test` is still running locally, so there may be a bug hiding in there somewhere still, but otherwise I think this is ready for review again.

**Comment by Ms2ger** [comment]
Looking good, but I'd like to ask for one last change: add a documentation comment for the module (`//! ...` between the license header and the `use`s).

**Comment by nick-thompson** [comment]
@Ms2ger how's that? :)

**Comment by Ms2ger** [comment]
Great, thank you!

@bors-servo r+

**Pull request merged**
