### PR TITLE
Use get_mut instead of get-remove-set in XHR send()

### LINKED ISSUE #11811: Use get_mut instead of get-remove-set in XHR send()
In https://github.com/servo/servo/blob/b9b289c4be50402facddd38c2ce2db2f1a05519c/components/script/dom/xmlhttprequest.rs#L637-654, we `.get()` a header, mutate it, `.remove()` it, and then `.set()` the new value. This is due to https://github.com/hyperium/hyper/issues/821, which is now fixed.

The code should be changed to mutate in place, by calling `.get_mut()` and mutating the value directly. This also requires a bump of our hyper version.

Tests in `tests/wpt/web-platform-tests/XMLHttpRequest` should continue to pass (`./mach test-wpt --release --include tests/wpt/web-platform-tests/XMLHttpRequest`, on a release build)

### PR DESCRIPTION
**Pull request by DarinM223**
## Mutates the header directly with get_mut instead of using get(), remove(), and set().

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11811  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because there are existing web tests

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11824)

### CODE REVIEW

**Comment by KiChjang** [comment]
Why are no `Cargo.toml` files updated?

**Comment by nox** [comment]
@DarinM223 Could you bump the Hyper version in the various `Cargo.toml` files that use it?

**Comment by KiChjang** [comment]
r=me after rebase

**Comment by KiChjang** [comment]
@DarinM223 Sorry, bors-servo doesn't listen to you, he's very picky.

@bors-servo r+

**Pull request merged**
