### PR TITLE
Implement crypto.getRandomValues()

### LINKED ISSUE #4666: Implement window.crypto.getRandomValues.
Spec: <https://dvcs.w3.org/hg/webcrypto-api/raw-file/tip/spec/Overview.html#dfn-Crypto-method-getRandomValues>.

This will involve:
* creating a new DOM interface `Crypto` as explained at <https://github.com/servo/servo/wiki/Adding-a-new-WebIDL-binding>;
* implementing a getter on `Window` to create and cache a `Crypto` object (see `navigator` or `location` for examples);
* implementing the `getRandomValues` method;
* probably updating <https://github.com/servo/mozjs> and <https://github.com/servo/rust-mozjs> to expose functions to work with `ArrayBuffer`s;
* enabling the web-platform tests for this feature by adding the WebCryptoAPI directory to `tests/wpt/include.ini`.

### PR DESCRIPTION
**Pull request by ttaubert**
Didn't touch mozjs or rust-mozjs because implementing that in the code generator didn't seem too easy. I'm using the same workaround that the TextDecoder does.

Using the OsRng should be the right choice here? As the OS keeps state for us we wouldn't need to have a global rng instance to keep around.

Fixes #4666.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6505)

### CODE REVIEW

**Comment by Manishearth** [comment]
Is webcrypto supposed to be safe against timing attacks? We might need to audit very carefully and turn off optimizations or something. Or use something like [nadeko](https://github.com/klutzy/nadeko/).

**Comment by ttaubert** [comment]
It is as safe against timing attacks as the underlying crypto library, i.e. OpenSSL. The WebCrypto API is mostly a thin wrapper on top of it, getRandomValues() doesn't need to be constant-time.

**Comment by huonw** [comment]
> Using the OsRng should be the right choice here? As the OS keeps state for us we wouldn't need to have a global rng instance to keep around.

Using `OsRng` will essentially do a syscall for each call to `getRandomValues`, e.g. on most unix platforms it will open `/dev/urandom` for `OsRng::new` and do a read from it for the `fill_bytes` calls (without any buffering). If performance is a concern this may not be the right choice.

**Comment by ttaubert** [comment]
Performance is a concern but having good PRNs too. Should we only have a single instance of OsRng and call that repeatedly? We could of course also use a different one like ChaChaRng but then we'd have to pick a good initial seed and reseed it periodically.

**Comment by Ms2ger** [comment]
I'm not concerned with the perf at this time, fwiw.

**Comment by huonw** [comment]
Just using the raw OS functionality is the conservative/simplest choice: it certainly makes sense as an initial implementation.

**Comment by nox** [comment]
@Ms2ger What's the status of this API? Will TypeMismatchError properly be deprecated and removed from it? I see that @ttaubert made getRandomBytes() take an object, this works for now and lets us throw TypeMismatch, but when ArrayBufferView will be properly implemented, we won't have the occasion to throw it and a TypeError will be thrown by the bindings themselves.

-S-awaiting-review +S-needs-code-changes +S-awaiting-answer 

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, 3 of 4 files at r4, 1 of 1 files at r5.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/crypto.rs, line 27 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6505#-Jt2PQrZS2ZIqP3fVGGw)** ([raw file](https://github.com/servo/servo/blob/653ee066f010d9b33be45951d87de4f4b94708e4/components/script/dom/crypto.rs#L27)):</sup>
This field isn't used, AFAICT.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6505)

**Comment by nox** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6505)

**Comment by ttaubert** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/crypto.rs, line 27 \[r6\]](https://reviewable.io:443/reviews/servo/servo/6505#-Jt2PQrZS2ZIqP3fVGGw)** ([raw file](https://github.com/servo/servo/blob/653ee066f010d9b33be45951d87de4f4b94708e4/components/script/dom/crypto.rs#L27)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6505)

**Comment by ttaubert** [comment]
> I see that @ttaubert made getRandomBytes() take an object, this works for now and lets us throw TypeMismatch, but when ArrayBufferView will be properly implemented, we won't have the occasion to throw it and a TypeError will be thrown by the bindings themselves.

The binding throwing TypeError when something other than an ArrayBufferView is passed is fine. We still have to check for an integer array (so no Float32Array for example) and would throw TypeMismatch if we need to.

**Comment by nox** [comment]
@ttaubert Oh I see, never mind then.

**Comment by Ms2ger** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/crypto.rs, line 27 \[r7\]](https://reviewable.io:443/reviews/servo/servo/6505#-Jt8W2S2azNZnqIph0-b)** ([raw file](https://github.com/servo/servo/blob/da18fe5eed051fe5806cca137dd4143f5bb84830/components/script/dom/crypto.rs#L27)):</sup>
DOMRefCell

---

<sup>**[components/script/dom/crypto.rs, line 51 \[r7\]](https://reviewable.io:443/reviews/servo/servo/6505#-Jt8WBvkLTjs0-oDO5XV)** ([raw file](https://github.com/servo/servo/blob/da18fe5eed051fe5806cca137dd4143f5bb84830/components/script/dom/crypto.rs#L51)):</sup>
Error::Type

---

<sup>**[components/servo/Cargo.lock, line 1079 \[r7\]](https://reviewable.io:443/reviews/servo/servo/6505#-Jt8Wd7leA4zNO9WWUvK)** ([raw file](https://github.com/servo/servo/blob/da18fe5eed051fe5806cca137dd4143f5bb84830/components/servo/Cargo.lock#L1079)):</sup>
Will need to update the other Cargo.locks too.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6505)

**Comment by ttaubert** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/crypto.rs, line 27 \[r7\]](https://reviewable.io:443/reviews/servo/servo/6505#-Jt8W2S2azNZnqIph0-b)** ([raw file](https://github.com/servo/servo/blob/da18fe5eed051fe5806cca137dd4143f5bb84830/components/script/dom/crypto.rs#L27)):</sup>
Done.

---

<sup>**[components/script/dom/crypto.rs, line 51 \[r7\]](https://reviewable.io:443/reviews/servo/servo/6505#-Jt8WBvkLTjs0-oDO5XV)** ([raw file](https://github.com/servo/servo/blob/da18fe5eed051fe5806cca137dd4143f5bb84830/components/script/dom/crypto.rs#L51)):</sup>
Done.

---

<sup>**[components/servo/Cargo.lock, line 1079 \[r7\]](https://reviewable.io:443/reviews/servo/servo/6505#-Jt8Wd7leA4zNO9WWUvK)** ([raw file](https://github.com/servo/servo/blob/da18fe5eed051fe5806cca137dd4143f5bb84830/components/servo/Cargo.lock#L1079)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6505)

**Comment by Ms2ger** [comment]
-S-awaiting-review  +S-needs-squash 
Squash and rebase, please. You'll probably need to update test expectations for WebCrypto too.

---

Reviewed 1 of 1 files at r9, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6505)

**Comment by ttaubert** [comment]
Added Crypto to DedicatedWorkerGlobalScope to fix failing WPT tests.

**Comment by Ms2ger** [comment]
Reviewed 7 of 7 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6505)

**Comment by ttaubert** [comment]
Unsure about the status here, anything I need to do?

**Comment by Ms2ger** [comment]
Yeah, complain at me for not landing it yet :)

@bors-servo r+

**Comment by Ms2ger** [comment]
Doh. Please update tests/wpt/mozilla/tests/mozilla/interfaces.html.

**Comment by ttaubert** [comment]
Oops, sorry. Will update the test.

**Comment by Ms2ger** [comment]
@bors-servo retry
* #6563

**Pull request merged**
