### PR TITLE
test(wpt): regenerate WPT certificate

### PR DESCRIPTION
**Pull request by yvt**
The certificate expired at Oct 12 00:43:32 2022 GMT. This PR regenerates it for another year (valid until Oct 15 13:13:45 2023 GMT).

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

---
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they update date-sensitive files in the test harness

### CODE REVIEW

**Comment by jdm** [comment]
Error syncing changes upstream. Logs saved in error-snapshot-1665840997084.

**Comment by jdm** [comment]
Ha, whoops, apparently I uploaded a personal access token for my account for the wpt-sync robot, rather than servo-wpt-sync.

**Comment by yvt** [comment]
<https://github.com/servo/servo/actions/runs/3256095191/jobs/5346427370#step:7:1115>

```
 1 unexpected results that are NOT known-intermittents:
  ▶ ERROR [expected OK] b'/workers/interfaces/WorkerUtils/importScripts/report-error-setTimeout-redirect-to-cross-origin.sub.any.worker.html'
  │   → expected expression, got ';'
  │ 
  └ https://not-web-platform.test:8443/workers/modules/resources/syntax-error.js:1:4
```

**Comment by jdm** [comment]
Haven't been able to reproduce the overall test failure locally. Let's retry!
@bors-servo retry

**Pull request merged**
