### PR TITLE
Upgrade to rustc 1.24.0-nightly (0a3761e63 2018-01-03)

### LINKED ISSUE #19519: Servo crashes on launch with Rust nightly >= 2017-11-21
Steps to reproduce:

1. Run latest Servo nightly build.
2. It crashes immediately.

Tested in Windows 10 with Browser.html.

### LINKED ISSUE #19635: `./mach check` fails on Fedora 26: src/task_info.c:10:10: fatal error: mach/mach_init.h: No such file or directory
As of e2f534f681fb10d0cf917c19c92b9bb40a9e2ebd I can no longer run `./mach check` on Fedora 26. [Here is the output of `./mach check -v'](https://gist.github.com/jonleighton/56119542b8cc9fbf449210849b554862). The error is:

```
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-o" "/home/turnip/Code/servo/target/debug/build/task_info-5b509507e8510095/out/src/task_info.o" "-c" "src/task_info.c"
cargo:warning=src/task_info.c:10:10: fatal error: mach/mach_init.h: No such file or directory
cargo:warning= #include <mach/mach_init.h>
cargo:warning=          ^~~~~~~~~~~~~~~~~~
cargo:warning=compilation terminated.
```

It comes from the [`support/rust-task_info` crate](https://github.com/servo/servo/tree/master/support/rust-task_info), but I think what has happened is that before e2f534f681fb10d0cf917c19c92b9bb40a9e2ebd, `task_info` wasn't being built (it doesn't show up in the output of `./mach check -v` on the preceding commit). The change in e2f534f681fb10d0cf917c19c92b9bb40a9e2ebd seems to have made it so that `./mach check` does now try to build `task_info`, and so the failure is now showing up.

It appears that the code in the `task_info` crate is targeted at OS X, which would be why it won't build for me. I've tried to do a bit of figuring out about why `./mach check` is now trying to build it when it previously didn't, but I haven't got very far.

`./mach build` seems to work fine, so this just affects the `check` command.

cc @asajeffrey

### LINKED ISSUE #19637: Lots of warnings: the type of this value must be known in this context
Hi folks,

I'm getting *a lot* of warnings like this:

> warning[E0619]: the type of this value must be known in this context
>    --> /home/nekrad/src/moz/servo/target/release/build/script-917cc22c0e8f3269/out/Bindings/XMLHttpRequestEventTargetBinding.rs:1088:74
>      |
> 1088 |     EventTargetBinding::GetConstructorObject(cx, global, >interface_proto.handle_mut());
>      |           > ^^^^^^^^^^
>      |
>      = note: this will be made into a hard error in a future version of the compiler
>
> warning[E0619]: the type of this value must be known in this context
>     --> /home/nekrad/src/moz/servo/target/release/build/script-917cc22c0e8f3269/out/Bindings/XMLHttpRequestEventTargetBinding.rs:1102:51
>      |
> 1102 |                                         interface.handle_mut());
>      |                                                   ^^^^^^^^^^
>      |
>      = note: this will be made into a hard error in a future version of the compiler

What does that mean ?

I'm using a pretty fresh rustc (updated few days ago) - did anything
vital change in the compiler/language ?

--mtx

### LINKED ISSUE #19735: Update to gl_generator 0.8.0
It contains the fix for https://github.com/servo/servo/issues/19519. We need to update it in:

* [ ] gleam
* [ ] glx
* [x] offscreen_gl_context
* [ ] rust-webvr
* [ ] servo-glutin

### PR DESCRIPTION
**Pull request by SimonSapin**
Fixes #19635
Fixes #19637 
Fixes #19735
Fixes #19519

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19683)

### CODE REVIEW

**Comment by jdm** [comment]
This PR needs to update the stable toolchain as well.

**Comment by SimonSapin** [comment]
```
env RUSTFLAGS=-Dwarnings ./mach build-geckolib
[…]
error: unknown codegen option: `incremental`
```

I think this is rather due to using Nigthly Cargo with Stable Rust. `-C incremental` was added in https://github.com/rust-lang/rust/pull/46751 which which will be in Rust 1.24.

I’ll revert ce700f21306b68399bbcd94d51cfaec92926fcb6 for now.

**Comment by SimonSapin** [comment]
#19395 will also fix that, since in rustup each toolchain has its own Cargo.

**Comment by jdm** [comment]
That is merely an instance of #19495.

**Comment by glennw** [comment]
I tested this locally and it still crashes with Illegal Instruction when I run:

```
./target/release/servo tests/html/about-mozilla.html
```

On my machine. The machine in question is Ubuntu 17.10 + Wayland + Intel HD4600.

**Comment by SimonSapin** [comment]
```
env CC=gcc-5 CXX=g++-5 RUSTFLAGS=-Dwarnings ./mach test-unit
[…]
LLVM ERROR: IO failure on output stream.
error: Could not compile `metrics_tests`.
```
```
env ./mach package --dev
[…]
OSError: [Errno 28] No space left on device: '/home/servo/buildbot/slave/linux-dev/build/target/debug/packaging-temp'
```

We probably need to disable incremental for all CI jobs, not just Windows. (Or get servers with larger disks?)

**Comment by jdm** [comment]
Yeah, it's not clear that incremental builds on CI jobs makes sense, and it seems like it will definitely exacerbate the disk space problem.

**Comment by jdm** [comment]
I have cleaned the target directories on servo-linux4.

**Comment by SimonSapin** [comment]
```
  ▶ TIMEOUT [expected PASS] /css/CSS2/normal-flow/min-width-046.xht
```

<details>

```
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ Failed to receive API response: Io(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread Constellation, at /checkout/src/libcore/result.rs:916)
  │ stack backtrace:
  │    0:     0x7fbed65a03dc - backtrace::backtrace::trace::he6c1181715b03fa2
  │    1:     0x7fbed659f302 - backtrace::capture::Backtrace::new::hd1811a0278c2f95b
  │    2:     0x7fbed3af88b8 - servo::main::{{closure}}::ha7dcf7bba475981b
  │    3:     0x7fbed65af705 - std::panicking::rust_panic_with_hook::hd65467d489bb99a6
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7fbed65af51e - std::panicking::begin_panic::h06b05d85af0a01cf
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7fbed65af48a - std::panicking::begin_panic_fmt::hdcdf37dcdaa48dbb
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7fbed65af422 - rust_begin_unwind
  │                         at /checkout/src/libstd/panicking.rs:498
  │    7:     0x7fbed65e2bb0 - core::panicking::panic_fmt::h1bceab3183b318fb
  │                         at /checkout/src/libcore/panicking.rs:71
  │    8:     0x7fbed5ce40bd - core::result::unwrap_failed::hed1a112f448ae1c9
  │    9:     0x7fbed5cd9b7a - webrender_api::api::RenderApiSender::create_api::hf182596f9295fb14
  │   10:     0x7fbed3c07e76 - constellation::pipeline::UnprivilegedPipelineContent::start_all::hc3ddeb7ce48d0662
  │   11:     0x7fbed3c1df16 - <constellation::constellation::Constellation<Message, LTF, STF>>::new_pipeline::hc8ddd98544dc01db
  │   12:     0x7fbed3c3aa47 - <constellation::constellation::Constellation<Message, LTF, STF>>::handle_request_from_compositor::hfabff537d03e9c02
  │   13:     0x7fbed3c406d9 - <constellation::constellation::Constellation<Message, LTF, STF>>::run::h6b719196ea176504
  │   14:     0x7fbed3b83642 - _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h7a2d15315b9db0adE.llvm.51594F29
  │   15:     0x7fbed3c0a4e5 - _ZN3std9panicking3try7do_call17h334403280d97c6e2E.llvm.DCC10A72
  │   16:     0x7fbed65d7cbe - __rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   17:     0x7fbed3b88e7a - <F as alloc::boxed::FnBox<A>>::call_box::h278e6c49b413aedf
  │   18:     0x7fbed65c0277 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h8f49a3821ce4ee9e
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys_common::thread::start_thread::h158502d18950767b
  │                         at /checkout/src/libstd/sys_common/thread.rs:24
  │   19:     0x7fbed65c35c8 - std::sys::unix::thread::Thread::new::thread_start::hafc8f92d56d1a91c
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   20:     0x7fbed2a10183 - start_thread
  │   21:     0x7fbed12d7ffc - clone
  │   22:                0x0 - <unknown>
  │ ERROR:servo: Failed to receive API response: Io(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
  │ IpcSelectionResult::unwrap(): channel 1 closed (thread ResourceManager, at /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.9.0/src/ipc.rs:334)
  │ called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread StorageManager, at /checkout/src/libcore/result.rs:916)
  │ stack backtrace:
  │    0:     0x7fbed65a03dc - backtrace::backtrace::trace::he6c1181715b03fa2
  │    1:     0x7fbed659f302 - backtrace::capture::Backtrace::new::hd1811a0278c2f95b
  │    2:     0x7fbed3af88b8 - servo::main::{{closure}}::ha7dcf7bba475981b
  │    3:     0x7fbed65af705 - std::panicking::rust_panic_with_hook::hd65467d489bb99a6
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7fbed65af51e - std::panicking::begin_panic::h06b05d85af0a01cf
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7fbed65af48a - std::panicking::begin_panic_fmt::hdcdf37dcdaa48dbb
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7fbed5cf2393 - ipc_channel::ipc::IpcSelectionResult::unwrap::h7ed7d23fc9fcbf55
  │    7:     0x7fbed4fc62ea - net::resource_thread::ResourceChannelManager::start::hcf9ca18eb5fdfff1
  │    8:     0x7fbed504bef8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4281a81479486894
  │    9:     0x7fbed4fd970f - _ZN3std9panicking3try7do_call17h722f9e2ede65ad07E.llvm.3D7055DE
  │   10:     0x7fbed65d7cbe - __rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   11:     0x7fbed5027f4d - <F as alloc::boxed::FnBox<A>>::call_box::h46c771b43d6a66a5
  │   12:     0x7fbed65c0277 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h8f49a3821ce4ee9e
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys_common::thread::start_thread::h158502d18950767b
  │                         at /checkout/src/libstd/sys_common/thread.rs:24
  │   13:     0x7fbed65c35c8 - std::sys::unix::thread::Thread::new::thread_start::hafc8f92d56d1a91c
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   14:     0x7fbed2a10183 - start_thread
  │   15:     0x7fbed12d7ffc - clone
  │   16:                0x0 - <unknown>
  │ ERROR:servo: IpcSelectionResult::unwrap(): channel 1 closed
  │ stack backtrace:
  │    0:     0x7fbed65a03dc - backtrace::backtrace::trace::he6c1181715b03fa2
  │    1:     0x7fbed659f302 - backtrace::capture::Backtrace::new::hd1811a0278c2f95b
  │    2:     0x7fbed3af88b8 - servo::main::{{closure}}::ha7dcf7bba475981b
  │    3:     0x7fbed65af705 - std::panicking::rust_panic_with_hook::hd65467d489bb99a6
  │                         at /checkout/src/libstd/panicking.rs:578
  │    4:     0x7fbed65af51e - std::panicking::begin_panic::h06b05d85af0a01cf
  │                         at /checkout/src/libstd/panicking.rs:538
  │    5:     0x7fbed65af48a - std::panicking::begin_panic_fmt::hdcdf37dcdaa48dbb
  │                         at /checkout/src/libstd/panicking.rs:522
  │    6:     0x7fbed65af422 - rust_begin_unwind
  │                         at /checkout/src/libstd/panicking.rs:498
  │    7:     0x7fbed65e2bb0 - core::panicking::panic_fmt::h1bceab3183b318fb
  │                         at /checkout/src/libcore/panicking.rs:71
  │    8:     0x7fbed508b16d - core::result::unwrap_failed::h7a4ff2725e4422b2
  │    9:     0x7fbed50334fb - net::storage_thread::StorageManager::start::h3a11dbe304e591fe
  │   10:     0x7fbed504c852 - std::sys_common::backtrace::__rust_begin_short_backtrace::h99fe0a9c5bf9a2ac
  │   11:     0x7fbed4fd963b - _ZN3std9panicking3try7do_call17h2946da1d6a00c3f5E.llvm.3D7055DE
  │   12:     0x7fbed65d7cbe - __rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:101
  │   13:     0x7fbed5028a16 - <F as alloc::boxed::FnBox<A>>::call_box::hcfed3c2a0c736d51
  │   14:     0x7fbed65c0277 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h8f49a3821ce4ee9e
  │                         at /checkout/src/liballoc/boxed.rs:827
  │                          - std::sys_common::thread::start_thread::h158502d18950767b
  │                         at /checkout/src/libstd/sys_common/thread.rs:24
  │   15:     0x7fbed65c35c8 - std::sys::unix::thread::Thread::new::thread_start::hafc8f92d56d1a91c
  │                         at /checkout/src/libstd/sys/unix/thread.rs:90
  │   16:     0x7fbed2a10183 - start_thread
  │   17:     0x7fbed12d7ffc - clone
  │   18:                0x0 - <unknown>
  └ ERROR:servo: called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
```

</details>

Intermittent?

----

The `./mach run -r -o output.png` job is green though. So it looks like it does not help avoid regress https://github.com/servo/servo/issues/19519. CC @asajeffrey

**Comment by jdm** [comment]
That's #13480.

**Pull request merged**
