### PR TITLE
script: implement autofocus IDL reflection

### PR DESCRIPTION
**Pull request by nolanlawson**
This partially addresses #32169 by implementing the `autofocus` IDL attribute reflection and adding the `HTMLOrSVGElement` mixin.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes partially address #32169
- [x] There are tests for these changes

### CODE REVIEW

**Review by mrobinson — APPROVED** [review]

**Comment by Loirooriol** [comment]
There are more tests passing: https://github.com/servo/servo/runs/24370525828, https://github.com/servo/servo/runs/24370564451

**Comment by nolanlawson** [comment]
Sorry, somehow I messed up running the WPT tests locally. That should fix it ^

**Review by Loirooriol — COMMENTED** [review]
But the autofocus functionality is still not supported, right? So what's the point of implementing the IDL reflection?

**Comment by nolanlawson** [comment]
Right, it's just about getting the WPT tests passing and refactoring to use the right WebIDL mixin.

**Pull request merged**
