### PR TITLE
Move arm64 build to taskcluster.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23414)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I attempted several times to reproduce this build in any environment other than buildbot workers, and gave up every time. Cross-compiling C or C++ code (SpiderMonkey in particular) with our build system is very brittle.

For quicker edit-run-error cycles, I suggest experimenting with a local Docker container. Repeatedly run `docker build -t servo-tmp .` in a directory with a `Dockerfile`, and keep successful intermediate commands in separate `RUN` instructions so that Docker caches their result as container layers.

(This can use up disk space quickly, so consider `docker container prune` and `docker image prune` after you’re done.)

**Comment by SimonSapin** [comment]
The unedited `Dockerfile` below is where I left off last time.

Other resources that might be helpful include:

* Env variables printed for a job such as https://build.servo.org/builders/arm64/builds/14563/steps/compile/logs/stdio
* A several-years-old blog post https://mmatyas.github.io/blog/servo-short-cross-compilation-guide
* The “rootfs” tarballs under https://servo-rust.s3.amazonaws.com/ARM/. I don’t know how they are created. They are installed on `linux-cross-*` workers here:
  - https://github.com/servo/saltfs/blob/c18e786a255679a3f8748adb0adb7fd4320e7a5c/servo-build-dependencies/map.jinja#L3-L18
  - https://github.com/servo/saltfs/blob/c18e786a255679a3f8748adb0adb7fd4320e7a5c/servo-build-dependencies/arm.sls

Good luck!

```Dockerfile
FROM ubuntu:trusty-20181217

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -q && apt-get install -qy --no-install-recommends \
    git \
    ca-certificates \
    python-virtualenv \
    curl
RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y
RUN git clone --depth 1 https://github.com/servo/servo /repo
WORKDIR /repo
ENV PATH="/root/.cargo/bin:$PATH"
RUN ./mach cargo fetch
ARG MACH_TARGET=aarch64-unknown-linux-gnu
RUN ./mach build --dev --target=$MACH_TARGET -p matches
ARG TARGET_NAME=aarch64-linux-gnu
ARG TARGET_DOWNLOAD_NAME=arm64-trusty-libs
ARG TARGET_SYMLINK_NAME=aarch64-unknown-linux-gnu
ARG TARGET_VERSION=v2
RUN apt-get install -y --no-install-recommends \
    make \
    g++ \
    g++-$TARGET_NAME
RUN mkdir $HOME/bin && \
    for bin in \
        elfedit gcov nm addr2line g++ objcopy ar objdump as gcc ranlib c++filt \
        gprof readelf cpp ld size ld.bfd strings strip \
    ; do \
        ln -s /usr/bin/$TARGET_NAME-$bin $HOME/bin/$TARGET_SYMLINK_NAME-$bin \
    ; done
#RUN mkdir /rootfs-$TARGET_DOWNLOAD_NAME-$TARGET_VERSION && ( \
#        export dir=$TARGET_DOWNLOAD_NAME/$TARGET_VERSION; \
#        export file=$TARGET_DOWNLOAD_NAME-$TARGET_VERSION.tgz; \
#        curl https://servo-rust.s3.amazonaws.com/ARM/$dir/$file \
#    ) \
#    | tar xz -C /rootfs-$TARGET_DOWNLOAD_NAME-$TARGET_VERSION
RUN ./mach build --dev --target=$MACH_TARGET -p libz-sys
RUN apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt-get update -q && \
    apt-get upgrade -y
RUN apt-get install -y --no-install-recommends \
    g++-5
RUN apt-get install -y --no-install-recommends \
    clang-4.0
RUN which gcc-5
#ENV CC_aarch64-unknown-linux-gnu=aarch64-linux-gnu-gcc
#RUN ./mach build --dev --target=$MACH_TARGET -p mozjs_sys

**Comment by SimonSapin** [comment]
> The “rootfs” tarballs under https://servo-rust.s3.amazonaws.com/ARM/. I don’t know how they are created.

Last updated in https://github.com/servo/saltfs/pull/268

**Comment by jdm** [comment]
I documented how to generate them in https://github.com/servo/servo/wiki/Preparing-ARM-libraries-for-CI

**Comment by jdm** [comment]
We've already got windows & magicleap arm64 builds on CI. I don't see a good reason to continue to maintain this build due to its complicated setup.

**Comment by SimonSapin** [comment]
Should we remove it from `buildbot_steps.yml`?

**Comment by jdm** [comment]
Yes.

**Pull request closed without merging**
