### PR TITLE
Bump rust-selectors

### PR DESCRIPTION
**Pull request by emilio**
Depends on https://github.com/servo/rust-selectors/pull/65.

I kept the commits splitted in order to simplify reviewing them, but they should arguably be squashed (the intermediate ones are broken builds).

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9453)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Please squash so that each commit compiles. (In this case this maybe everything in one commit.) r=me with that

---

Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 6 of 6 files at r3, 15 of 15 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9453#-:-K99XW8iSXwl7bLhpiqI:374937874)*

**Comment by SimonSapin** [comment]
Also `./mach test-tidy` reports some errors: https://travis-ci.org/servo/servo/jobs/105528079

**Comment by ecoal95** [comment]
Hrrmm...

Happened to me locally right now, but I thought it was just some corruption of the cargo directory or similar:

```
unable to get packages from source
Caused by:
  Failed to unpack package `selectors v0.4.0`
Caused by:
  No such file or directory (os error 2)
```

**Comment by ecoal95** [comment]
For the record:

This is failing because of https://github.com/rust-lang/cargo/issues/2326, so we're either blocked by the cargoup or by another rust-selector's release.

**Comment by nox** [comment]
Superseded by #9510.

**Pull request closed without merging**
