### PR TITLE
Adding Clamp and EnforceRange support for webidl arguments

### LINKED ISSUE #6089: Fix [Clamp] support in CodegenRust
As the title says. I'm working on it.

### PR DESCRIPTION
**Pull request by snf**
I had some doubts on if I should have used a generic function or a macro. So I implemented both and left them in the code so you can help me decide, marked with XXX(reviewer).

@jdm you probably want to review this one.

Fixes #6089

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6096)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed on critic.

**Comment by snf** [comment]
Just checked and we don't have any function that emulates the C/C++/Rust static cast. NumCast will return None if the number exceeds the container range. So we have two options: 1) macro 2) implement it by ourselves 3) other?

**Comment by snf** [comment]
Addressed most of the issues, the only one left is to remove the generic and use the macro if you are ok with that (read previous comment).

**Comment by snf** [comment]
Ok, I implemented a trait AsStaticCast that is like NumCast but without the bound checking and used that with the generic function. Also removed the macro function. Btw I will rebase the branch when we finish the review so I don't break the reviews.

**Comment by snf** [comment]
We can delay this until SMup lands, but the result will be pretty similar if we want to keep the generic.

**Comment by Ms2ger** [comment]
Please rebase on master.

**Comment by Ms2ger** [comment]
Rebased as https://github.com/servo/servo/pull/6582

**Pull request closed without merging**
