### PR TITLE
compositing: Move compositing off the main thread.

### PR DESCRIPTION
**Pull request by pcwalton**
Because the compositor no longer runs on the main thread, it can now use
plain old Rust channels for communication, and the main thread instead
receives the special "proxy" treatment. This change also makes the
compositor entirely optional; in headless mode, no compositor is started
at all.

This change will allow us to support multiple windows, since those must
have separate compositors. It should also improve our event dispatch
latency, since even less runs on the main thread, and we can handle
events while waiting for buffer swaps.

Additionally, this patch refactors many of the task startup functions,
which took too many arguments, to use initialization structures. This
makes the code easier to read.

Closes #4228.

r? @glennw

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/4271)

### CODE REVIEW

**Comment by pcwalton** [comment]
@glennw Glutin has landed while this patch was outstanding. Is there a way to push events to the event queue from another thread with it?

**Comment by glennw** [comment]
@pcwalton Do you just need to wake up the event queue from another thread? You can use the glutin WindowProxy interface for that. If you need something more than just a wakeup event, let me know what's required and I'll add it.

**Comment by metajack** [comment]
Assigning @glennw to this, but looks like @pcwalton needs to make the necessary change and rebase.

**Comment by glennw** [comment]
@pcwalton I think this just needs to be rebased and updated for glutin based on my last comment / question above.

**Comment by metajack** [comment]
@pcwalton Sounds like this should be easy to land.

**Comment by nox** [comment]
Is this PR even relevant with compositor being `IpcSender<_>` now?

**Comment by pcwalton** [comment]
Yes. We will need this in order to support multiple windows, for example.

**Comment by nox** [comment]
@pcwalton Would it help if we split this branch in more commits? I can try to separate this:

> Additionally, this patch refactors many of the task startup functions, which took too many arguments, to use initialization structures. This makes the code easier to read.

**Comment by Ms2ger** [comment]
I think that's worth doing independently of this PR.

**Comment by nox** [comment]
@Ms2ger Yes that's what I was saying.

**Comment by nox** [comment]
Things I remarked so far:

* many messages sent to the compositor should be sent to the main thread directly (everything where the compositor used to just call something on `self.window`);
* the compositor doesn't seem to need to `send_opt()` to the constellation on shutdown, because the compositor doesn't instantiate shutdown ever anymore;
` I have absolutely no idea what to do about the `WindowMethods::prepare_for_compositing()`.

**Comment by glennw** [comment]
@pcwalton Should we close this and re-open it when you have time to look at this again?

**Pull request closed without merging**
