### PR TITLE
Image with height defined in % resizes properly

### LINKED ISSUE #11723: Image with height defined in % is not resized properly
```
<!doctype html>
<html><body>
	<div style="height: 100px;">
		<img style="height: 100%" src="http://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Skoda130Rally.jpg/256px-Skoda130Rally.jpg">
	</div>
</body></html>
```
img

### PR DESCRIPTION
**Pull request by DarinM223**
Checked the html in the github issue and the image looks like it is resized properly in Servo.
## Fixed image resizing when height is specified in percentages.

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11723  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because this issue is marked with has-test?

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11746)

### CODE REVIEW

**Comment by KiChjang** [comment]
Could you add a reftest for this? Using the testcase as presented in the issue should work fine.

**Comment by DarinM223** [comment]
@KiChjang Sorry, I don't really know how to create reftests and I'm having trouble finding resources on creating them... Is the test in the modified commit correct?

**Comment by KiChjang** [comment]
That's incorrect, and it seems like you have photoshopped the actual car image out. Take a look at https://github.com/servo/servo/tree/master/tests/wpt#writing-new-tests. You should have two HTML files, one of it is the test, where you'll have the `style="height: 100%"` defined on the img element, and the other the reference, which is identical to the test, but without the style attribute.

The test works by taking a screenshot of both of these HTML files. If they do not differ, the test succeeds.

**Comment by Ms2ger** [comment]
I'm afraid you can't add any new tests under css-tests; that's a read-only copy of upstream tests. There's a `mozilla/tests` directory you can use instead.

**Comment by mbrubeck** [comment]
@bors-servo r+

Looks great, thanks!

---

Reviewed 4 of 4 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11746#-:-KKNQSBMVeTXLATLvaWc:-724031257)*

**Pull request merged**
