### PR TITLE
webrender: Don't use OpenGL round() for snapping pixels

### LINKED ISSUE #11751: Font issues in WebRender caused by pixel snapping
This test case:
```html
<div style="font: 13px 'Helvetica Neue'; padding: 0.5px;">illisible</div>
```

Renders like this on Linux with WebRender enabled (`./mach run -w`):

illisible

This happens because the glyph positions are snapped to full pixels before rendering, which can change the letter spacing dramatically. @pcwalton mentioned that this could be fixed by instead rounding the fractional part of the glyph position to the nearest quarter pixel, and generating up to four rasterized glyphs per character: one for each possible quarter-pixel offset, with the fractional offset included as "padding" so the rasterized glyph can be positioned on a whole pixel boundary.

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes #11751. See servo/webrender#294 for some details. r? @pcwalton

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11801)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo retry

* #11859

**Comment by mbrubeck** [comment]
The new reftest is failing on Mac; the spacing between some pairs of letters (e.g. the first two) is off by one pixel:

screenshot at 2016-06-27 13-04-02

**Comment by mbrubeck** [comment]
@bors-servo r=pcwalton

Marked the new test as failing on Mac for now, after confirming that it fails the same without this PR. Will file a follow-up for the positioning issues on Mac.

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11574

**Pull request merged**
