### PR TITLE
Supress panics for ProfilerChan sends.

### PR DESCRIPTION
**Pull request by jdm**
This should address #14161.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14165)

### CODE REVIEW

**Comment by nox** [comment]
@jdm In other places we do a `warn!` on such errors, should it be done here too?

Cc @asajeffrey.

**Comment by asajeffrey** [comment]
Yes, including the `warn!` might be useful. In production use, this means the warning will end up in the crash log if there's a later panic.

**Comment by jdm** [comment]
This will fix #14161 as well.

**Comment by jdm** [comment]
@bors-servo: retry
* #14215

**Comment by jdm** [comment]
@bors-servo: retry
* #14217

**Pull request merged**
