### PR TITLE
Tidy: Handle empty files

### PR DESCRIPTION
**Pull request by UK992**
Fix index error `list index out of range`, when file is empty.

r? @Wafflespeanut 

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13107)

### CODE REVIEW

**Comment by UK992** [comment]
What is the purpose of ``./tests/html/tiny_test.html``? Can be removed?

**Comment by Wafflespeanut** [comment]
It can be removed, I guess? (cc @nox or @Ms2ger) - not sure how it got there in the first place.

**Comment by notriddle** [comment]
According to git blame, @mmeyerho  added it in a3225428250a559c25af09f442e07e504d6e49b5.

**Comment by Ms2ger** [comment]
Fine by me to remove.

**Comment by Wafflespeanut** [comment]
Thanks!

@bors-servo r+

**Pull request merged**
