### PR TITLE
Fix two issues of parsing and serialization of mask shorthand

### PR DESCRIPTION
**Pull request by upsuper**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15298)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo try

Seems like this needs tests.

**Comment by upsuper** [comment]
Shorthand mask is currently Gecko-specific, and there are tests inside Gecko so I suppose we don't need further tests.

**Comment by upsuper** [comment]
(Actually these issues are caught by Gecko's tests...)

**Comment by nox** [comment]
I see. Will r+ once Homu is done with the try, I don't want to vex it.

**Comment by nox** [comment]
The unit tests failed:

```
failures:

---- parsing::mask::mask_shorthand_should_not_parse_when_mode_specified_but_image_not stdout ----
	thread 'parsing::mask::mask_shorthand_should_not_parse_when_mode_specified_but_image_not' panicked at 'assertion failed: mask::parse_value(&context, &mut parser).is_err()', /Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/style/parsing/mask.rs:113
stack backtrace:
   1:        0x10a3d0d7c - std::sys::imp::backtrace::tracing::imp::write::h36dcd6719b30e145
   2:        0x10a3d496e - std::panicking::default_hook::{{closure}}::h4ef47a6ed549d2e6
   3:        0x10a3d4513 - std::panicking::default_hook::hd7b4c7a7e16abb43
   4:        0x10a3d4e27 - std::panicking::rust_panic_with_hook::h33761bada49f3713
   5:        0x109bb80f3 - std::panicking::begin_panic::h79533631a1075507
   6:        0x109d82954 - style_tests::parsing::mask::mask_shorthand_should_not_parse_when_mode_specified_but_image_not::h1f81835f40a474c0
   7:        0x10a32ae5e - <F as test::FnBox<T>>::call_box::hfce97b6a3bca902b
   8:        0x10a3d5d0a - __rust_maybe_catch_panic
   9:        0x10a31f098 - std::panicking::try::do_call::h4b6b5a01e5d0f1b4
  10:        0x10a3d5d0a - __rust_maybe_catch_panic
  11:        0x10a325dde - <F as alloc::boxed::FnBox<A>>::call_box::he619e4ac93c39e1b
  12:        0x10a3d4044 - std::sys::imp::thread::Thread::new::thread_start::he1b44499d44cc4a4
  13:     0x7fff8af9f059 - _pthread_body
  14:     0x7fff8af9efd6 - _pthread_start


failures:
    parsing::mask::mask_shorthand_should_not_parse_when_mode_specified_but_image_not
```

**Pull request merged**
