### PR TITLE
Add get/set pref extensions to webdriver server.

### PR DESCRIPTION
**Pull request by jgraham**
This can be used by the test framework to ensure that the correct prefs are
set for a test without restarting the browser

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7548)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/webdriver_server/lib.rs, line 85 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7548#-JyarCwhrQBl8Efp1iHS)** ([raw file](https://github.com/servo/servo/blob/7a8b95149a3b530be3c9744f838eb59766913802/components/webdriver_server/lib.rs#L85)):</sup>
Too long

---

<sup>**[components/webdriver_server/lib.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7548#-JyasaX0IVmZcz1D5tac)** ([raw file](https://github.com/servo/servo/blob/7a8b95149a3b530be3c9744f838eb59766913802/components/webdriver_server/lib.rs#L158)):</sup>
Nested try is very hard to read.

---

<sup>**[components/webdriver_server/lib.rs, line 165 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7548#-JyarJXVDJFU5_18j3CH)** ([raw file](https://github.com/servo/servo/blob/7a8b95149a3b530be3c9744f838eb59766913802/components/webdriver_server/lib.rs#L165)):</sup>
`(x, y)`

---

<sup>**[components/webdriver_server/lib.rs, line 634 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7548#-JyasJN7ZQ6s6pmH_So5)** ([raw file](https://github.com/servo/servo/blob/7a8b95149a3b530be3c9744f838eb59766913802/components/webdriver_server/lib.rs#L634)):</sup>
Better as
```rust
let prefs = parameters.prefs
                      .iter()
                      .map(|item| (item.clone(), get_pref(item).to_json()))
                      .collect::<BTreeMap<_>>();
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7548)

**Comment by metajack** [comment]
Shouldn't there be a third Cargo.lock update or does webdriver_server not get used on Android?

Otherwise looks good.

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7548)

**Comment by jdm** [comment]
It's a cargo feature that doesn't get enabled on android right now, presumably.

**Comment by jgraham** [comment]
I don't know, I just trusted |mach cargo-update|

**Comment by jdm** [comment]
@bors-servo: retry
* #7437

**Pull request merged**
