### PR TITLE
Return appropriate code from bootstrap_gstreamer

### PR DESCRIPTION
**Pull request by Manishearth**
Otherwise it exits with 1

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21734)

### CODE REVIEW

**Review by jankeromnes — COMMENTED** [review]
Looks good! Thanks for the quick fix.

Just to be sure, if something terrible happens (e.g. network unreachable, exception, ...) this will still properly crash and report the error, right?

**Comment by Manishearth** [comment]
Yeah, it should throw an error earlier. That's what the check_call does.
-Manish Goregaokar

**Comment by Manishearth** [comment]
@bors-servo retry

 - `EnvironmentError: Servers failed to start: 127.0.0.1:8889` , may be permabustage, cc @jdm

**Pull request merged**
