### PR TITLE
Use all for the default value of transition-property in transition

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16563)

### CODE REVIEW

**Comment by bholley** [comment]
CC @BorisChiou @birtles @hiikezoe

**Comment by bholley** [comment]
(This likely wants a Gecko try run, because animation stuff is all sorts of special)

**Comment by nox** [comment]
Did this based on those `test_value_storage.html` results:

```
 setting '2s, 1s width' on '-webkit-transition' - didn't expect "", but got it
 setting '1s width, 2s' on '-webkit-transition' - didn't expect "", but got it
```

**Comment by hiikezoe** [comment]
Wow! Nice!  I think this fix is correct.
One nit;  The initial value of transition-property is 'all' [1], so we should use get_initial_specified_value just like other properties.

Thank you!
[1] https://www.w3.org/TR/css3-transitions/#transition-property

**Comment by hiikezoe** [comment]
r=me with that change.

**Comment by nox** [comment]
@hiikezoe There was an issue with my patch where it allowed empty transitions. This is fixed. r?

**Comment by hiikezoe** [comment]
LGTM.

**Comment by nox** [comment]
Yay new passing tests. 

@bors-servo r=hiikezoe

**Pull request merged**
