### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23353)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r-
Travis is complaining.

**Comment by jdm** [comment]
```
./components/style_traits/arc_slice.rs:24: derivable traits list is not in alphabetical order
	expected: Clone, Debug, Eq, PartialEq, ToShmem
	found: Debug, Clone, PartialEq, Eq, ToShmem
```

**Comment by emilio** [comment]
Arrgh, that lint :)

**Pull request merged**
