### PR TITLE
Treat application/xml like text/xml in ParserContext::process_response

### LINKED ISSUE #15850: Treat application/xml like text/xml in ParserContext::process_response
We should be able to support loading documents with the application/xml MIME type, but currently we just show an error instead. This appears in `./mach test-wpt tests/wpt/web-platform-tests/XMLHttpRequest/send-entity-body-document.htm`; we will get more meaningful errors if we make this change.

Code: `components/script/dom/servoparser/mod.rs`

Claiming this for some RGSoC applicants.

### PR DESCRIPTION
**Pull request by cgati**
* components/script/dom/servoparser/mod.rs updated to handle application/xml as text/xml, along with hoisting application/xhtml+xml from the unknown mime types match arm.
* tests updated via mach

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15850  (github issue number if applicable).

- [X] These changes modify results in test files via the automated: `./mach test-wpt tests/wpt/web-platform-tests/dom/nodes --log-raw /tmp/servo && ./mach update-wpt /tmp/servo`
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19182)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Let's see how the tests like it!

**Comment by KiChjang** [comment]
```
  ▶ OK [expected TIMEOUT] /dom/nodes/ParentNode-querySelector-All-xht.xht

  ▶ OK [expected TIMEOUT] /dom/nodes/Element-webkitMatchesSelector.html

  ▶ OK [expected TIMEOUT] /dom/nodes/ParentNode-querySelector-All.html

  ▶ OK [expected TIMEOUT] /dom/nodes/Element-matches.html
```

Excellent! The remaining steps here are to remove the related test expectation ini files located under `tests/wpt/metadata/dom/nodes/`.

**Comment by cgati** [comment]
I had a feeling I didn't quite do this run correctly.

**Comment by cgati** [comment]
@KiChjang Do you have any advice for getting this into a working state?

**Comment by jdm** [comment]
@cgati If you download http://build.servo.org/builders/linux-rel-wpt/builds/6863/steps/test__1/logs/test-wpt.log/text as `wpt-log` and run `./mach update-wpt path/to/wpt-log`, the result should pass our tests.

**Comment by cgati** [comment]
@jdm Cheers! Let's see how this goes.

**Comment by KiChjang** [comment]
@bors-servo r+

Thanks!

**Comment by cgati** [comment]
Ugh, sorry. I noticed I managed to still be behind master and re-based and pushed again. Didn't see you had issued a command to bors.

**Comment by KiChjang** [comment]
No worries, thanks for you work!

@bors-servo r+

**Comment by KiChjang** [comment]
@bors-servo r-

Sorry, there's quite a bit of test expectations updates that seem surprising to me...

**Comment by KiChjang** [comment]
@cgati It looks like your rebasing went wrong; some of the test expectations have been updated on master, but you have overwritten them with your old branch's expectations. Let me issue a try build, and perhaps you can use that to update your test expectations locally (using @jdm's method above).

@bors-servo try

**Comment by cgati** [comment]
@KiChjang Understood. I'm prepared to attempt a fix of my botched rebase and re-gen tests with the previous `wpt-log` file if needed.

**Comment by KiChjang** [comment]
The link to test-wpt.log this time is http://build.servo.org/builders/linux-rel-wpt/builds/6944/steps/test__1/logs/test-wpt.log.

Note that the test expectations for [these tests](http://build.servo.org/builders/linux-rel-wpt/builds/6944/steps/shell__2/logs/intermittents.log) should not be changed.

**Comment by cgati** [comment]
Here goes nothing. I hope I'm not wasting anyone's time here, I appreciate all the guidance on this PR.

**Comment by KiChjang** [comment]
@bors-servo r+

Thanks!

**Comment by cgati** [comment]
@KiChjang @jdm Thanks again, this was a great experience as a new contributor to the project.

**Pull request merged**
