### PR TITLE
Implement inline-table

### LINKED ISSUE #8003: Implement display: inline-table
Currently, the CSS parser parses inline-table, but layout doesn't do anything interesting with it.  We treat it like a block because of https://github.com/servo/servo/blob/69db83476d02d06658ad084a834abc94f7f008d0/components/layout/construct.rs#L1557 .

Probably a good project for someone interested in digging into layout a bit; this shouldn't require any significant architectural changes.

### PR DESCRIPTION
**Pull request by KiChjang**
A lot of what I'm doing here is "monkey-see-monkey-do", so I only have a slight idea of what I'm doing. Mistakes will be made. Don't be gentle on me, and whip me when I do something wrong.

Fixes #8003.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9355)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Travis is dissatisfied

**Comment by Ms2ger** [comment]
I assume you can point to a spec statement for all the code in this PR?

**Comment by frewsxcv** [comment]
Does this result in any CSS WPT tests being fixed?

**Comment by KiChjang** [comment]
I think it should; we'll see.

@bors-servo try

**Comment by KiChjang** [comment]
Wow, I messed up pretty bad - 102 timed out tests and no passes.

**Comment by KiChjang** [comment]
@Ms2ger Here are a couple of scattered pieces of the specs that I've managed to gather:
* https://www.w3.org/TR/CSS21/visuren.html#inline-formatting
* https://www.w3.org/TR/CSS21/visuren.html#inline-level
* https://www.w3.org/TR/CSS21/tables.html#table-display

**Comment by jdm** [comment]
That's... a lot of test failures.

**Comment by KiChjang** [comment]
Huh... I'm not sure what I did that caused so many test failures. @pcwalton do you have any ideas?

**Comment by jdm** [comment]
Closing since it's not clear that this is making forward progress.

**Pull request closed without merging**
