### PR TITLE
Fix some warnings from future Rust Nightlies

### PR DESCRIPTION
**Pull request by SimonSapin**
This is the parts of https://github.com/servo/servo/pull/28201 that can land without actually upgrading the toolchain (which is likely blocked on https://github.com/servo/servo/issues/28101)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@jdm Do you have thoughts on whether some of these never-read struct fields should be removed?

**Comment by jdm** [comment]
r=me, but I would say we should remove all those members instead.

**Comment by SimonSapin** [comment]
Alright, done.

@bors-servo r=jdm

**Comment by SimonSapin** [comment]
@bors-servo retry

I haven’t seen this one before:

```

  ▶ Unexpected subtest result in /webdriver/tests/set_window_rect/set.py:
  │ FAIL [expected PASS] b'test_negative_x_y'
  │   → AssertionError: assert {'height': 740, 'width': 1024, 'x': 0, 'y': 0} == {'height': 740, 'width': 1024, 'x': -8, 'y': None}
  │ 
  │ session = <Session 8e4aae7b-f08a-4e54-bc4e-09e41f2d5abf>
  │ 
  │     def test_negative_x_y(session):
  │         original = session.window.rect
  │     
  │         response = set_window_rect(session, {"x": - 8, "y": - 8})
  │     
  │         os = session.capabilities["platformName"]
  │         # certain WMs prohibit windows from being moved off-screen
  │         if os == "linux":
  │             rect = assert_success(response)
  │             assert rect["x"] <= 0
  │             assert rect["y"] <= 0
  │             assert rect["width"] == original["width"]
  │             assert rect["height"] == original["height"]
  │     
  │         # On macOS, windows can only be moved off the screen on the
  │         # horizontal axis.  The system menu bar also blocks windows from
  │         # being moved to (0,0).
  │         elif os == "mac":
  │             value = assert_success(response)
  │     
  │             # `screen.availTop` is not standardized but all browsers we care
  │             # about on MacOS implement the CSSOM View mode `Screen` interface.
  │             avail_top = session.execute_script("return window.screen.availTop;")
  │     
  │ >           assert value == {"x": -8,
  │                              "y": avail_top,
  │                              "width": original["width"],
  │                              "height": original["height"]}
  │ E           AssertionError: assert {'height': 740, 'width': 1024, 'x': 0, 'y': 0} == {'height': 740, 'width': 1024, 'x': -8, 'y': None}
  │ E             Common items:
  │ E             {'height': 740, 'width': 1024}
  │ E             Differing items:
  │ E             {'x': 0} != {'x': -8}
  │ E             {'y': 0} != {'y': None}
  │ E             Full diff:
  │ E             - {'height': 740, 'width': 1024, 'x': -8, 'y': None}
  │ E             ?                                     ^^       ^^^^
  │ E             + {'height': 740, 'width': 1024, 'x': 0, 'y': 0}
  │ E             ?                                     ^       ^
  │ 
  │ avail_top  = None
  │ original   = {'height': 740, 'width': 1024, 'x': 0, 'y': 0}
  │ os         = 'mac'
  │ response   = <Responsetatus=200 body={"value": {"x": 0, "y": 0, "width": 1024, "height": 740}}>
  │ session    = <Session 8e4aae7b-f08a-4e54-bc4e-09e41f2d5abf>
  │ value      = {'height': 740, 'width': 1024, 'x': 0, 'y': 0}
  │ 
  └ tests/wpt/web-platform-tests/webdriver/tests/set_window_rect/set.py:304: AssertionError

**Pull request merged**
