### PR TITLE
Remove assert that will always be true

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
Actually, it looks as though this was intended to ensure the name is lowercase:

https://github.com/servo/servo/commit/ee2ccc4f872ba33a86057d87a99d1015b3c41cf1#diff-9082d52f79e121265b7ddf64d11fe044L518

**Comment by frewsxcv** [comment]
So if that's the functionality we want, I can replace it with

```
assert!(name.as_slice() == name.to_ascii_lowercase());
```

**Comment by jdm** [comment]
Yes, that looks like a more appropriate assertion.

**Comment by frewsxcv** [comment]
Closing in favor of #5448

**Pull request closed without merging**
