### PR TITLE
Implement about:unicorn.

### PR DESCRIPTION
**Pull request by emosenkis**
This currently does not render anything due to lack of SVG support.

See https://fetch.spec.whatwg.org/#concept-basic-fetch

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8808)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Line is too long

**Comment by KiChjang** [comment]
This fails tidy. Output:
```
./components/net/about_loader.rs:48: Line is longer than 120 characters
```

To avoid this, you can use `./mach test-tidy` to check your source files for style errors.

**Comment by Ms2ger** [comment]
We're not going to implement this.

**Comment by frewsxcv** [comment]
@ms2ger Because of lack of SVG support?

**Comment by Ms2ger** [comment]
Because it's a stupid and unjustified joke.

**Comment by jdm** [comment]
That being said, thanks for taking the time to dive into the networking code, @emosenkis! If you're interested in suggestions for something else to work on, let us know :)

**Pull request closed without merging**
