### PR TITLE
Add documentation of reftest analyzer to wpt README

### PR DESCRIPTION
**Pull request by jgraham**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6265)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo: r+

-S-awaiting-review +S-awaiting-merge 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- tests/wpt/README.md @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6265)

**Comment by jdm** [comment]
@bors-servo: retry
* #6266

**Comment by nox** [comment]
@bors-servo: retry

#6272 disabled the failing test.

**Pull request merged**
