### PR TITLE
Return true in set_property only when declaration block is changed

### PR DESCRIPTION
**Pull request by upsuper**
This is [bug 1344135](https://bugzilla.mozilla.org/show_bug.cgi?id=1344135).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15837)

### CODE REVIEW

**Comment by upsuper** [comment]
The style part has been reviewed by @heycam, but the script part may still need review from @emilio.

r? @emilio

**Comment by nox** [comment]
I don't like the boolean, could you make a new enum with descriptive names for the variants?

**Comment by upsuper** [comment]
I don't think that using enum here adds much value, especially given that `mutate_associated_block` is already using boolean to track change. Probably you can submit a refactor PR to convert all these to use the enum, although I don't think it's worth.

**Comment by upsuper** [comment]
Also it seems code using enum is less optimal than using boolean with `|=`. This isn't a strong reason, though.

**Comment by nox** [comment]
I'll let @emilio decide, but if that shouldn't be done here that should definitely be filed as a follow-up.

**Comment by emilio** [comment]
I think this is fine for now, per the reasons @upsuper commented about above. Other alternative would be something like returning `Result<(), ()>`, and then doing:

```rust
*changed |= pdb.set(...).is_ok();
```

But seems a bit overkill too for this. Fine filling a followup though.

@bors-servo r+

cc @SimonSapin, this is likely to conflict with #15856, though I haven't checked closely.

**Comment by SimonSapin** [comment]
@emilio It does conflict. Don’t worry about it, I’ll deal with it.

**Pull request merged**
