### PR TITLE
style: Add support to the animation shorthand and fix parsing of animation-name

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

Part of #11916.

r? @SimonSapin

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12118)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r=me with one change

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/properties/shorthand/box.mako.rs, line 129 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12118#-KM5Ix4JCZdMqtql8BAr:-KM5Ix4KFidX0DBFkfce:1021862025) ([raw file](https://github.com/servo/servo/blob/1ef32374ecfcdd49164ae093e2bb3df557cc793f/components/style/properties/shorthand/box.mako.rs#L129)):*
> ```Rust
> 
>         loop {
>             try_parse_one!(input, name, animation_name);
> ```

Per https://drafts.csswg.org/css-animations/#typedef-single-animation , `name` should be last (so that keywords valid for other longhands are not interpreted as names).

Please also add a comment saying so, and that `duration` needs to be before `delay` (which it already id) with that URL included in the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12118#-:-KM5Kj2nTLFOfumbKlzp:-873186932)*

**Comment by emilio** [comment]
Thanks for the careful review as always Simon :)

@bors-servo: r=SimonSapin

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/properties/shorthand/box.mako.rs, line 129 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12118#-KM5Ix4JCZdMqtql8BAr:-KM5TjqA4nLnqVuL9BWq:-1666374036) ([raw file](https://github.com/servo/servo/blob/1ef32374ecfcdd49164ae093e2bb3df557cc793f/components/style/properties/shorthand/box.mako.rs#L129)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Per https://drafts.csswg.org/css-animations/#typedef-single-animation , `name` should be last (so that keywords valid for other longhands are not interpreted as names).
> 
> Please also add a comment saying so, and that `duration` needs to be before `delay` (which it already id) with that URL included in the comment.
</details>
Whoops, good catch :)

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12118#-:-KM5U99o_7ldNYe3R9Sh:-1616860060)*

**Comment by jdm** [comment]
@bors-servo: retry
* infra

**Comment by jdm** [comment]
```
  ▶ TIMEOUT [expected PASS] /css-flexbox-1_dev/html/css-flexbox-height-animation-stretch.htm

  ▶ Unexpected subtest result in /css-transitions-1_dev/html/transition-timing-function-001.htm:
  └ PASS [expected FAIL] parse 'steps(3)'
```

**Comment by emilio** [comment]
Updated the test expectations an opened #12328 regarding the flexbox test, which we rendered incorrectly anyway.

I probably need to dedicate some time to #12120, adding a test refresh mode to the constellation or similar I guess, and enabling some private APIs to allow testing animations à lo mochitest in gecko.

I want approval from @jdm or @SimonSapin for landing that last expectation change, I think it's reasonable but I prefer to double-check.

**Comment by SimonSapin** [comment]
Sounds ok to me.

@bors-servo r+

**Pull request merged**
