### PR TITLE
Support required dictionary members (fixes #7216)

### LINKED ISSUE #7216: Implement required dictionary members
The WebIDL file below (part of [Touch Events][2] fails with this error: `WebIDL.WebIDLError: error: Dictionary argument or union argument containing a dictionary not followed by a required argument must be optional, /home/mbrubeck/src/servo/components/script/dom/webidls/Touch.webidl line 24:23`
```
[Constructor(TouchInit touchInitDict)]
                       ^
```

But the [WebIDL spec says][1] (emphasis mine):

>  If the type of an argument is a dictionary type or a union type that has a dictionary type as one of its flattened member types, **and that dictionary type and its ancestors have no required members**, and the argument is either the final argument or is followed only by optional arguments, then the argument MUST be specified as optional. Such arguments are always considered to have a default value of an empty dictionary, unless otherwise specified. 

Since the TouchInit dictionary *does* have required members, it should be allowed as a required argument.

```webidl
dictionary TouchInit {
    required long        identifier;
    required EventTarget target;
             double      clientX = 0;
             double      clientY = 0;
             double      screenX = 0;
             double      screenY = 0;
};

[Constructor(TouchInit touchInitDict)]
interface Touch {
    readonly    attribute long        identifier;
    readonly    attribute EventTarget target;
    readonly    attribute double      screenX;
    readonly    attribute double      screenY;
    readonly    attribute double      clientX;
    readonly    attribute double      clientY;
};
```

[1]: http://heycam.github.io/webidl/#idl-operations
[2]: http://w3c.github.io/touch-events/#touch-interface

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7230)

### CODE REVIEW

**Comment by nox** [comment]
```rust
            requiredValue: {
            let mut rval = RootedValue::new(cx, UndefinedValue());
            match try!(get_dictionary_property(cx, object.handle(), "requiredValue", rval.handle_mut())) {
                true => {
                    match FromJSValConvertible::from_jsval(cx, rval.handle(), ()) {
                        Ok(v) => v,
                        Err(_) => { return Err(()); }
                    }
                },
                false => {
                    return Err(());
                },
            }
            },
```

**Comment by Ms2ger** [comment]
This will throw an uncatcheable exception. The spec probably tells you to throw a `TypeError`, please do that.

**Comment by nox** [comment]
@Ms2ger Done.

```rust
            match try!(get_dictionary_property(cx, object.handle(), "requiredValue", rval.handle_mut())) {
                true => {
                    match FromJSValConvertible::from_jsval(cx, rval.handle(), ()) {
                        Ok(v) => v,
                        Err(_) => { return Err(()); }
                    }
                },
                false => {
                    throw_type_error(cx, "Missing required member \"requiredValue\".");
                    return Err(());
                },
            }
            },
```

**Pull request merged**
