### PR TITLE
Fix 'inline-block' sizing issues

### LINKED ISSUE #3624: Inline-blocks with percentage widths don't work right
Test case:

    <!DOCTYPE html>
    <html>
    <body>
    <div style="display: block; width: 300px;">
        <div style="display: inline-block; width: 100%;">
            Bloobity bloobity bloobity bloobity
            bloobity bloobity bloobity bloobity
            bloobity bloobity bloobity bloobity
            bloobity bloobity bloobity bloobity
            bloobity bloobity bloobity bloobity
            bloobity bloobity bloobity bloobity
            bloobity bloobity bloobity bloobity
            bloobity bloobity bloobity bloobity
        </div>
    </div>
    </body>
    </html>

This breaks Twitter real bad.

### PR DESCRIPTION
**Pull request by mttr**
The first commit fixes #3624, and the second commit fixes a bug uncovered by the first fix and caught by a reftest (according to CSS 2.1, inline-blocks should have the shrink-to-fit algorithm run on them when size is set to 'auto'). The two new reftests included here fail before the fix and pass afterwards.

### CODE REVIEW

**Comment by mbrubeck** [comment]
Review complete, with one minor stylistic change suggested (on Critic).

**Comment by mttr** [comment]
Thanks! That bit of code was really bothering me, and I somehow missed the obvious solution. I'll have the changes in as soon as it finishes compiling/testing.

**Comment by mbrubeck** [comment]
Great! Can squash and land with r=mbrubeck.

**Comment by mttr** [comment]
Squashed/rebased!

**Pull request merged**
