### PR TITLE
refactor(window): reference winit where applicable

### LINKED ISSUE #20299: Use winit where possible instead of glutin
We should use `glutin` only in parts of the code that are hardcoded to GL, and stick to `winit` in other places, like window management and events. That will simplify the process of getting more graphics backends later on. `Glutin` simply re-exports `winit` types, so this is safe to do.

cc @zakorgy , who made those changes as a part of https://github.com/szeged/servo/commit/c38ba12833856af799317cc79a5cdd2e50696d10

### PR DESCRIPTION
**Pull request by kwonoj**
This is nearly first changes to rustlang code and I suspect I could make possible mistakes lot, please point me anything if need to be updated. 🙏 

This PR intends to update codebase per #20299 , mostly followed suggestion around https://github.com/servo/servo/issues/20299#issuecomment-373171416 to update reference to use `winit` where applicable. Confirmed local build / check works correctly for updated references.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #20299 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20303)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good, thanks! There’s just a few more items that are in both glutin and winit and can be imported from the latter: `ElementState`, `Event`, `MouseButton`, `MouseScrollDelta`, `VirtualKeyCode`, `TouchPhase`, `ActivationPolicy`, `WindowBuilderExt`, `MouseCursor`, `VirtualKeyCode` (again)

… I think. I haven’t double-checked all of them, but the compiler should tell you. In general, winit deals with windows and input events while glutin adds OpenGL contexts/apis.

**Comment by kwonoj** [comment]
@SimonSapin Appreciate for suggestion, I've added changes. Now other than `{Api, GlContext, GlRequest}` code uses `winit` directly where applicable.

**Comment by SimonSapin** [comment]
Looks great!

**Comment by kwonoj** [comment]
uh, seems build failure on CI. let me try to amend it as well.

**Comment by SimonSapin** [comment]
Oops I meant to r+, but yeah there are build failures that need to be fixed before this can land. I don’t understand them based on reading the diff, though…

**Comment by kwonoj** [comment]
@SimonSapin I think it's my fault to not correctly move #cfg target for mac specific. I've pushed new changes and checking CI results now 🤞

**Comment by SimonSapin** [comment]
Oh that makes sense. I think we don’t need to wait for Travis.

@bors-servo r+

**Pull request merged**
