### PR TITLE
Implement CSSStyleRule.selectorText.

### LINKED ISSUE #17182: Simplify `an+b` when serializing
When we serialize an `an+b` value, we just print it as `an+b`.

We should be simplifying it as much as possible. This means:

 - Printing out only `b` if `a` is zero
 - Printing out only `an` if `b` is zero
 - Printing `0` if both are zero
 - Not printing `a` if it is 1

Reduced testcase:

```html
<style type="text/css">
  :nth-child(+1n+5){}
</style>
<script type="text/javascript">document.write(document.styleSheets[0].cssRules[0].selectorText</script>
```

(Same for `+1n+0`, `+0n+5`, `+0n-0`, etc)

Relevant code: https://github.com/servo/servo/blob/2da8eb0342f6701b5365116b96113c83a1599b1f/components/selectors/parser.rs#L743

Testing: `tests/wpt/web-platform-tests/cssom/selectorSerialize.html`

### PR DESCRIPTION
**Pull request by jyc**
We parse when assigning using the namespaces of the stylesheet. It isn't
clear if the spec says to do that (Firefox doesn't support the setter at
all, Chrome does, Safari doesn't); the spec issue is here:
https://github.com/w3c/csswg-drafts/issues/1511

Also fix ToCss implementation of AttrSelectorOperator to not pad with
spaces, to conform with CSSOM. This means we have to update some unit
tests that expect operators with spaces around them in attribute
selectors to roundtrip.

See the "attribute selector" section of "Serializing Selectors" here:
https://drafts.csswg.org/cssom/#serializing-selectors

CSSStyleRule.selectorText is specified here:
https://drafts.csswg.org/cssom/#dom-cssstylerule-selectortext

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes is part of a series to fix #17182 

I am running this to identify what tests will fail; as the other PRs in the series are merged, I believe the tests that pass will change as well.

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17538)

### CODE REVIEW

**Comment by jyc** [comment]
Oh, the tests are those from https://github.com/servo/servo/pull/17203 . Will wait for that.

**Comment by jyc** [comment]
Neat! So I believe that once is this landed we should start seeing changes on results in

- https://github.com/servo/servo/pull/17539
- https://github.com/servo/servo/pull/17537
- https://github.com/servo/servo/pull/17501

agh.. this is hard to organize. Wish GitHub had some way to make Pull Requests composed of Pull Requests.

**Comment by jyc** [comment]
@Manishearth if you could review this when you have time, that would be cool! (then could land the other parts). But I think we were still waiting on the other patch to remove spacing around operators in selectors; I've included those changes so that the checks pass here because it looked like that received a 'r-', but I can remove them easily as well.

**Comment by Manishearth** [comment]
Yeah, just include that patch in your PR and fix it up.

**Comment by jyc** [comment]
@Manishearth cool! It is done!

**Comment by jyc** [comment]
Aggh! I remember this error from when this was one PR:

```
{"status": "FAIL", "group": "default", "message": "sheet.cssRules[(sheet.cssRules.length - 1)] is undefined", "stack": "assert_selector_serializes_to@http://web-platform.test:8000/cssom/serialize-namespaced-type-selectors.html:24:17\n@http://web-platform.test:8000/cssom/serialize-namespaced-type-selectors.html:27:17\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20\ntest@http://web-platform.test:8000/resources/testharness.js:497:9\n@http://web-platform.test:8000/cssom/serialize-namespaced-type-selectors.html:26:13\n", "subtest": "Simple type selector", "test": "/cssom/serialize-namespaced-type-selectors.html", "line": 103522, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "sheet.cssRules[(sheet.cssRules.length - 1)] is undefined", "stack": "assert_selector_serializes_to@http://web-platform.test:8000/cssom/serialize-namespaced-type-selectors.html:24:17\n@http://web-platform.test:8000/cssom/serialize-namespaced-type-selectors.html:219:17\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20\ntest@http://web-platform.test:8000/resources/testharness.js:497:9\n@http://web-platform.test:8000/cssom/serialize-namespaced-type-selectors.html:218:13\n", "subtest": "Type selector with namespace equal to default namespace", "test": "/cssom/serialize-namespaced-type-selectors.html", "line": 103570, "action": "test_result", "expected": "PASS"}
```

I think that depends on https://github.com/servo/servo/pull/17501 . The test should actually not be passing right now, seeing as `selectorText` is unimplemented.

I will update the additional unexpected passes and maybe we can update the expectations to bec orrect for the unexpected fail when it should actually be passing, after merging #17501.

**Pull request merged**
