### PR TITLE
Text fragment color merge

### PR DESCRIPTION
**Pull request by notriddle**
The display list item for a line of text has a single color assigned for
it, so text fragments with different colors cannot be merged.

There is no issue number for this, as far as I know. I found this while
trying an internal program that uses red asterisks for required text
fields.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not fix an existing Github issue
- [X] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11914)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/mozilla/tests/css/content_color_ref.html, line 4 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11914#-KLOBWQvrNyeDMKJ_yvD:-KLOBWQwvA7FDNqN8aS2:1831600861) ([raw file](https://github.com/servo/servo/blob/63152ab6c7a59fdb8843e47810ad7b1d2f1f113e/tests/wpt/mozilla/tests/css/content_color_ref.html#L4)):*
> ```HTML
> <title>This test should have a red B and a black A</title>
> <style>
> a{float:left}
> ```

Why is this float necessary?

---

*[tests/wpt/mozilla/tests/css/content_color_ref.html, line 7 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11914#-KLOBZ4Qvlu2483nj2sk:-KLOBZ4Qvlu2483nj2sl:818177598) ([raw file](https://github.com/servo/servo/blob/63152ab6c7a59fdb8843e47810ad7b1d2f1f113e/tests/wpt/mozilla/tests/css/content_color_ref.html#L7)):*
> ```HTML
> span{color:red}
> </style>
> <a>A</a><span>B</span>
> ```

Can we use two spans with ids instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11914#-:-KLOBcx62xpoWedgb2UZ:1458266033)*

**Comment by notriddle** [comment]
*[tests/wpt/mozilla/tests/css/content_color_ref.html, line 4 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11914#-KLOBWQvrNyeDMKJ_yvD:-KLOBwCo0MysHJGmOnds:467205622) ([raw file](https://github.com/servo/servo/blob/63152ab6c7a59fdb8843e47810ad7b1d2f1f113e/tests/wpt/mozilla/tests/css/content_color_ref.html#L4)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Why is this float necessary?
</details>
Without the float, the reference would hit the same bug as the test case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11914)*

**Comment by notriddle** [comment]
*[tests/wpt/mozilla/tests/css/content_color_ref.html, line 7 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11914#-KLOBZ4Qvlu2483nj2sk:-KLOCgTfy0Ik2gLklTSW:-499146009) ([raw file](https://github.com/servo/servo/blob/63152ab6c7a59fdb8843e47810ad7b1d2f1f113e/tests/wpt/mozilla/tests/css/content_color_ref.html#L7)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Can we use two spans with ids instead?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11914)*

**Comment by jdm** [comment]
@bors-servo: r+
Good catch!

**Comment by notriddle** [comment]
:facepalm:

**Pull request merged**
