### PR TITLE
Upgrade cargo to 0.5.0-nightly (657e363 2015-08-19)

### PR DESCRIPTION
**Pull request by SimonSapin**
Pick up https://github.com/rust-lang/cargo/pull/1830

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7049)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7049)

**Comment by jdm** [comment]
```
Submodule 'support/android-rs-glue' (https://github.com/tomaka/android-rs-glue) registered for path 'support/android-rs-glue'
Cloning into 'support/android-rs-glue'...
Submodule path 'support/android-rs-glue': checked out '4ed3cb30b289aa0aa84a00e0d5682bc853108e5a'

thread '<main>' has overflowed its stack
```
...huh

**Comment by SimonSapin** [comment]
I can reproduce this locally on OS X, but not on Linux. This is possibly https://github.com/rust-lang/cargo/issues/1875.

**Comment by SimonSapin** [comment]
Filed https://github.com/rust-lang/cargo/issues/1897

**Pull request merged**
