### PR TITLE
Add support for switching frames with the webdriver API.

### PR DESCRIPTION
**Pull request by jgraham**
This moves webdriver_traits into msg to avoid a circular dependency.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6009)

### CODE REVIEW

**Comment by jdm** [comment]
gonk's Cargo.lock contains merge conflict markers...

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 4 unresolved discussions, some commit checks failed.
Reviewed files:
- components/compositing/Cargo.toml @ r1
- components/compositing/constellation.rs @ r1
- components/compositing/lib.rs @ r1
- components/msg/Cargo.toml @ r1
- components/msg/constellation_msg.rs @ r1
- components/msg/lib.rs @ r1
- components/script/Cargo.toml @ r1
- components/script/dom/window.rs @ r2
- components/script/lib.rs @ r1
- components/script/script_task.rs @ r1
- components/script/webdriver_handlers.rs @ r2
- components/script_traits/Cargo.toml @ r1
- components/script_traits/lib.rs @ r3
- components/servo/Cargo.lock @ r1
- components/webdriver_server/Cargo.toml @ r1
- components/webdriver_server/lib.rs @ r2
- components/webdriver_traits/Cargo.toml @ r1
- components/webdriver_traits/lib.rs @ r1
- ports/cef/Cargo.lock @ r1
- ports/gonk/Cargo.lock @ r1

---

<sup>**[components/script/webdriver_handlers.rs, line 62 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6009#-JpnDWUXkSw8CcZK-ToL)** ([raw file](https://github.com/servo/servo/blob/6b4ce5275a625fe232a4c3ae93dff1a0b79240ed/components/script/webdriver_handlers.rs#L62)):</sup>
This is a pretty long line.

---

<sup>**[components/webdriver_server/lib.rs, line 223 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6009#-JpnE2b6V6h5jQEUnsyC)** ([raw file](https://github.com/servo/servo/blob/6b4ce5275a625fe232a4c3ae93dff1a0b79240ed/components/webdriver_server/lib.rs#L223)):</sup>
use webdriver::common::FrameId?

---

<sup>**[components/webdriver_server/lib.rs, line 237 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6009#-JpnEDvX7MRJCVAAbUYY)** ([raw file](https://github.com/servo/servo/blob/6b4ce5275a625fe232a4c3ae93dff1a0b79240ed/components/webdriver_server/lib.rs#L237)):</sup>
nit: indentation

---

<sup>**[components/webdriver_server/lib.rs, line 393 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6009#-JpnEpYyq6qBtkNDMe8F)** ([raw file](https://github.com/servo/servo/blob/6b4ce5275a625fe232a4c3ae93dff1a0b79240ed/components/webdriver_server/lib.rs#L393)):</sup>
This could use an explanatory comment.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6009)

**Comment by jgraham** [comment]
Review status: all files reviewed, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/webdriver_server/lib.rs, line 223 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6009#-JpnE2b6V6h5jQEUnsyC)** ([raw file](https://github.com/servo/servo/blob/6b4ce5275a625fe232a4c3ae93dff1a0b79240ed/components/webdriver_server/lib.rs#L223)):</sup>
So the reason I didn't do this is to make it clear that this isn't a FrameId from the constellation.  So, I can use the webdriver-specific one in the function body, and hopefully that makes things clear enough. Does that make sense?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6009)

**Comment by jdm** [comment]
Squash, rebase, etc.
-S-awaiting-review +S-needs-squash 

---

Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- components/script/webdriver_handlers.rs @ r4
- components/webdriver_server/lib.rs @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6009)

**Comment by jdm** [comment]
```
failed to select a version for `rustc-serialize` (required by `msg`):
all possible versions conflict with previously selected versions of `rustc-serialize`
  version 0.3.14 in use by rustc-serialize v0.3.14
  possible versions to select: 0.3.13
```

**Comment by jdm** [comment]
Sorry, I didn't notice the update here before it bitrotted.

**Pull request merged**
