### PR TITLE
Allow prefs to be overridden from a file and set WPT-specific prefs from file

### PR DESCRIPTION
**Pull request by msub2**
This adds the ability to pass in a separate prefs file to override prefs.json. It also adds a new `wpt-prefs.json` file in the resources, designed to designate any prefs that should be overridden in Servo's wpt.fyi runs. 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because ___

### CODE REVIEW

**Comment by mrobinson** [comment]
How would wpt.fyi specify that it needs to load the extra preferences file?

**Comment by msub2** [comment]
After this there would be a companion PR to the WPT repo to ensure the Servo runner (https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/executors/executorservo.py) has the flag(s) from this file applied.

**Comment by sagudev** [comment]
> After this there would be a companion PR to the WPT repo to ensure the Servo runner (https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/executors/executorservo.py) has the flag(s) from this file applied.

You can actually just do this in this PR and it will get exported to upstream wpt by editing https://github.com/servo/servo/blob/main/tests/wpt/tests/tools/wptrunner/wptrunner/executors/executorservo.py. Also are we sure this prefs will only be applied for wpt.fyi runs not for `mach test-wpt` runs too. I wonder how firefox does this.

**Comment by jdm** [comment]
I would actually like to start specifying all directiry-level prefs for wpt test runs in the json file instead of in ini files, since it will make our test behaviour more consistent.

**Comment by msub2** [comment]
I believe the current __dir__.ini overrides would be:

- dom.bluetooth.enabled
- dom.gamepad.enabled
- dom.imagebitmap.enabled
- dom.permissions.enabled
- dom.resize_observer.enabled
- dom.serviceworker.enabled
- dom.webvtt.enabled
- dom.webxr.test
- dom.webgl2.enabled

**Comment by jdm** [comment]
Also:
* layout.columns.enabled
* layout.flexbox.enabled

We had a bunch of preferences enabled in meta-legacy-layout that didn't get migrated to meta, apparently:
* dom.worklet.enabled
* dom.worklet.timeout_ms
* dom.webvtt.enabled
* dom.offscreen_canvas.enabled
* dom.permissions.enabled
* dom.bluetooth.enabled
* dom.mutation_observer.enabled
* dom.serviceworker.enabled
* dom.imagebitmap.enabled

Although I now realize that this goes back to my concern that wpt.fyi results should reflect what users experience as much as possible, so I'm talking myself out of moving most of these to wpt-prefs.json.

**Comment by msub2** [comment]
Yeah, I was thinking about that too. Would we want to maybe start with just adding `dom.webxr.test`? It shouldn't affect our own WPT runs since it's already part of a __dir__.ini.

**Comment by jdm** [comment]
Yes, I think that makes sense.

**Comment by msub2** [comment]
I've confirmed this is correctly applying the dom.webxr.test pref in local testing

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
If you set the xrtest pref to false in the ini file for interfaces.html, that test should pass.

**Comment by sagudev** [comment]
> ⛔ Failed to properly merge the upstream pull request ([web-platform-tests/wpt#47769](https://github.com/web-platform-tests/wpt/pull/47769)). Please address any CI issues and try to merge manually.

We should make that PR are blocked until wpt CI is happy too (although in this case it looks like WPTs flake).

**Comment by msub2** [comment]
Hmmm, it seems like this just broke the most recent WPT run 😕

**Comment by msub2** [comment]
I wonder if it's because it pulled a nightly for testing that doesn't have the wpt-prefs.json?

**Comment by mrobinson** [comment]
> > ⛔ Failed to properly merge the upstream pull request ([web-platform-tests/wpt#47769](https://github.com/web-platform-tests/wpt/pull/47769)). Please address any CI issues and try to merge manually.
> 
> We should make that PR are blocked until wpt CI is happy too (although in this case it looks like WPTs flake).

I don't think we should block Servo PRs due to WPT CI issues. We have various WPT reviewers on the project. When things go wrong, maybe we can apply a label to the PR to signal one of the reviewers to fix the WPT usptream PR and land it manually.

**Comment by mukilan** [comment]
This change is causing WPT runs to crash. I've raised #33202 as a quick fix for this.

**Pull request merged**
