### PR TITLE
Fix rust's remutex source code link

### PR DESCRIPTION
**Pull request by CYBAI**
Should I change it to a permalink instead?

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it just fix links in comments

### CODE REVIEW

**Comment by jdm** [comment]
A permalink would make sense.

**Comment by CYBAI** [comment]
Updated to permalinks! Thanks!

**Comment by jdm** [comment]
@bors-servo retry
* #23290 #26726

**Pull request merged**
