### PR TITLE
profile: Make the time and memory profilers run over IPC.

### PR DESCRIPTION
**Pull request by pcwalton**
Uses a couple of extra threads to work around the lack of cross-process
boxed trait objects.

r? @nnethercote

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6629)

### CODE REVIEW

**Comment by nnethercote** [comment]
What follows is me trying to understand all this...

Let's call the memory profiler thread "M".

Old scheme: each thread, T, that does memory reporting has a Sender that 
implements the Reporter trait so that M can send requests to T. When those
requests are received, the Reporter sends a thread-specific message to T to
collect reports.

New scheme: each thread, T, that does memory reporting has an auxiliary 
reporter thread, R. A channel from M to R is established. R just sits waiting
for requests from the memory profiler thread. When those requests are received,
R sends a thread-specific message to T to collect reports.

In both schemes we require a thread-specific intermediary to convert the generic
"collect reports" request from M to the equivalent thread-specific message for 
T. In the old scheme that's the trait, in the new one it's the thread. And in
both schemes these intermediaries end up looking very similar to each other.

Is there any way to use the type system to instead share the generic event 
among multiple threads? I'm imagining some kind of enum inheritance. E.g. have
a ReporterMsg enum with a single variant, CollectReports, and then the layout
task's Msg type would inherit from it, and would the script task's ScriptMsg,
and so on. And M would send messages of type ReporterMsg.

That's probably not possible, but it seems a shame to have an extra reporting 
thread for every measured thread just to repeatedly fulfil this same basic
pattern. But I can't think of anything better, so if you also can't, then r=me.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/layout/layout_task.rs, line 311 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6629#-JuF9PogE6IQ58zPun9V)** ([raw file](https://github.com/servo/servo/blob/695173aaa112b4eb41d85203efe9bd95a7976271/components/layout/layout_task.rs#L311)):</sup>
A naming nit: I've carefully used just `reporter` rather than `memory_reporter` in identifiers because `memory` is redundant -- there aren't any other kinds of reporters -- and just makes things more verbose. (This applies to lots of new identifiers added by this change.)

---

<sup>**[components/profile_traits/mem.rs, line 53 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6629#-JuF83nLnBuvy81WW91d)** ([raw file](https://github.com/servo/servo/blob/695173aaa112b4eb41d85203efe9bd95a7976271/components/profile_traits/mem.rs#L53)):</sup>
This comment isn't quite right now that `Reporter` is a struct rather than a trait. I would like to suggest what it should now read but my brain is hurting. Want to have a crack yourself? :)

---

<sup>**[components/profile_traits/mem.rs, line 68 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6629#-JuF77TFqT9NQONO9xnl)** ([raw file](https://github.com/servo/servo/blob/695173aaa112b4eb41d85203efe9bd95a7976271/components/profile_traits/mem.rs#L68)):</sup>
I'd move this above `pub struct Reporter`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6629)

**Comment by jdm** [comment]
The reason for the threads right now is that it's impossible to select over in-process channels and IPC channels simultaneously. That means that we always need at least one thread to watch for IPC messages and route them to the proper place, much like Gecko has an IPC thread.

**Comment by pcwalton** [comment]
I should compose a better response to your comment, but note that in the future we may be able to `select` over an fixed number of IPC channels (but only IPC channels, not a mixture of in-process and IPC). This is definitely doable on Unix and Windows (via `select` and WFMO respectively, as long as there are fewer than 64 channels you're selecting over), and maybe on Mac OS X—I'll have to investigate.

This may not help very much, though, as most tasks have to select over a combination of in-process and IPC channels.

**Comment by pcwalton** [comment]
I wonder if a workable solution might be to have a generic, per-process IPC-channel-to-sender router that `ipc-channel` manages stored in a global. We could expose a function that allows users of IPC channels to dynamically register "adapters" with it to allow bridging of `IpcSender<T>` to a `Sender<T>`.

**Comment by metajack** [comment]
Where does the 64 channel limitation come from? select() has the ability to handle thousands of fds, though it is limited.

**Comment by pcwalton** [comment]
WFMO has a limitation of 64 on W

**Comment by pcwalton** [comment]
WFMO has a limitation of 64 on Windows. You can't use select over named pipes there.

**Comment by pcwalton** [comment]
The future is now. I've upgraded `ipc-channel` to multiplex all routing communications traffic into a single thread, eliminating the necessity of spawning helper threads.

r? @nnethercote

**Comment by pcwalton** [comment]
or r? @jdm, either one

**Comment by nnethercote** [comment]
This looks good except you haven't addressed my three small comments from my previous review.

**Comment by pcwalton** [comment]
Rebased and updated per comments.

**Comment by nnethercote** [comment]
Reviewed 6 of 6 files at r2.
Review status: 5 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/profile_traits/mem.rs, line 59 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6629#-Jui2Zg9XVsDWWMGpbkZ)** ([raw file](https://github.com/servo/servo/blob/7493dfafde58bdc194b7766861624d0530af7d24/components/profile_traits/mem.rs#L59)):</sup>
Nit: "encapsulate"

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6629)

**Comment by nnethercote** [comment]
r=me

**Comment by jdm** [comment]
@bors-servo: retry
* #6644

**Comment by jdm** [comment]
```
components/profile_traits/Cargo.toml:14: found asterisk instead of minimum version number
components/profile_traits/Cargo.toml:15: found asterisk instead of minimum version number
```

**Comment by jdm** [comment]
```
/XMLHttpRequest/open-url-javascript-window-2.htm
------------------------------------------------
CRASH expected TIMEOUT [Parent]
/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm
------------------------------------------------------------
CRASH expected FAIL [Parent]
/2dcontext/drawing-images-to-the-canvas/drawimage_canvas_5.html
---------------------------------------------------------------
CRASH [Parent]
/2dcontext/drawing-images-to-the-canvas/drawimage_canvas_8.html
---------------------------------------------------------------
CRASH [Parent]
/2dcontext/line-styles/lineto_a.html
------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-N-EN.html
-------------------------------------------------------
CRASH expected FAIL [Parent]
/html/dom/elements/global-attributes/dir_auto-N-L.html
------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-N-R.html
------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-bdi-R.html
------------------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-dir-L.html
------------------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-dir-R.html
------------------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-textarea-R.html
-----------------------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-contained-textarea-L.html
-----------------------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-input-EN-R.html
-------------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-input-N-EN-R.html
---------------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-input-N-R.html
------------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-textarea-N-EN.html
----------------------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-textarea-N-between-Rs.html
------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/dom/elements/global-attributes/dir_auto-textarea-mixed.html
-----------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/dom/elements/global-attributes/lang-xyzzy.html
----------------------------------------------------
CRASH expected FAIL [Parent]
/html/dom/elements/global-attributes/style-01.html
--------------------------------------------------
CRASH [Parent]
/html/dom/elements/global-attributes/dir_auto-input-N-EN-L.html
---------------------------------------------------------------
TIMEOUT [Parent]
/html/rendering/non-replaced-elements/tables/table-border-1.html
----------------------------------------------------------------
CRASH [Parent]
/html/rendering/non-replaced-elements/tables/table-border-2.html
----------------------------------------------------------------
CRASH [Parent]
/html/semantics/embedded-content/the-embed-element/embed-represent-nothing-02.html
----------------------------------------------------------------------------------
CRASH [Parent]
/html/semantics/embedded-content/the-embed-element/embed-represent-nothing-01.html
----------------------------------------------------------------------------------
CRASH [Parent]
/html/semantics/embedded-content/the-embed-element/embed-represent-nothing-03.html
----------------------------------------------------------------------------------
CRASH [Parent]
/html/semantics/forms/the-input-element/image01.html
----------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/grouping-content/the-li-element/grouping-li-reftest-002.html
----------------------------------------------------------------------------
CRASH [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-start-reftest-002.html
----------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-001.html
---------------------------------------------------------------------------------
CRASH [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-start-reftest-001.html
----------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/img_border_percent.xhtml
-----------------------------------------------------------------------------------------------------
TIMEOUT expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-002.html
---------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-003.html
---------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-auto-dir-default.html
------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/grouping-content/the-pre-element/pre-newline-bidi.html
----------------------------------------------------------------------
CRASH [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-missing-pdf.html
---------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-letter-following-1.html
-------------------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-letter-following-2.html
-------------------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-letter-preceding-1.html
-------------------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-wrapped.html
-----------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/html/semantics/text-level-semantics/the-bdi-element/bdi-paragraph-level-container.html
---------------------------------------------------------------------------------------
CRASH expected FAIL [Parent]
/_mozilla/css/abs_float_pref_width.html
---------------------------------------
CRASH [Parent]
/_mozilla/css/class-namespaces.html
-----------------------------------
CRASH [Parent]
/_mozilla/css/absolute_content_height.html
------------------------------------------
CRASH [Parent]
/_mozilla/mozilla/canvas/drawimage_html_image_10.html
-----------------------------------------------------
TIMEOUT [Parent]
```

**Comment by jdm** [comment]
```
 2:16.28 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) Full command: /home/servo/buildbot/slave/linux2/build/target/debug/servo --cpu --hard-fail -u Servo/wptrunner -z http://localhost:8000/XMLHttpRequest/open-url-javascript-window-2.htm
(pid:21104) "thread 'ScriptTask PipelineId(2)' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:731"
 2:16.28 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "stack backtrace:"
 2:16.28 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "thread 'ScriptTask PipelineId(1)' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:731"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "   1:     0x7f3128fd103e - sys::backtrace::write::hfe027f56cae344aapps"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "   2:     0x7f3128fd4715 - panicking::on_panic::hcd0100c6199f27b1Cax"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "   3:     0x7f3128fc187e - rt::unwind::begin_unwind_inner::h0544b2c664549c40gQw"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "   4:     0x7f3128fc226c - rt::unwind::begin_unwind_fmt::h5a900a56c2bf32ccmPw"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "   5:     0x7f3128fd4106 - rust_begin_unwind"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "   6:     0x7f3129006324 - panicking::panic_fmt::h205f328075c6fc3cneC"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "   7:     0x7f312885652e - result::Result<T, E>::unwrap::h11352777269357971417"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at src/libcore/macros.rs:28"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "   8:     0x7f31288563cc - mem::ProfilerChan::send::h6443f011bb63df7aOaa"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at /home/servo/buildbot/slave/linux2/build/components/profile_traits/mem.rs:22"
 2:16.84 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "   9:     0x7f3127571743 - script_task::ScriptTask.ScriptTaskFactory::create::closure.131863"
 2:17.20 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at /home/servo/buildbot/slave/linux2/build/components/script/script_task.rs:445"
 2:17.20 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  10:     0x7f3127570864 - task::spawn_named_with_send_on_failure::closure.131857"
 2:17.20 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at /home/servo/buildbot/slave/linux2/build/components/util/task.rs:31"
 2:17.20 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  11:     0x7f3127570784 - boxed::F.FnBox<A>::call_box::h3410980023480071851"
 2:17.20 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at src/liballoc/boxed.rs:396"
 2:17.20 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  12:     0x7f3126d75450 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h7728176623635406204"
 2:17.20 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at src/liballoc/boxed.rs:412"
 2:17.20 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  13:     0x7f3126d74f02 - thread::Builder::spawn_inner::closure.96648"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at src/libstd/thread/mod.rs:349"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  14:     0x7f3126d74e7e - rt::unwind::try::try_fn::__rust_abi::h3147245345620677859"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at src/libstd/rt/unwind/mod.rs:158"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  15:     0x7f3126d74e19 - rt::unwind::try::try_fn::h3147245345620677859"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  16:     0x7f3128fd96c8 - rust_try_inner"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  17:     0x7f3128fd96b5 - rust_try"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  18:     0x7f3128fcead7 - rt::unwind::try::inner_try::h63857c7efe7ef4ac9Lw"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  19:     0x7f3126d74d78 - rt::unwind::try::h7666379524236618803"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at src/libstd/rt/unwind/mod.rs:130"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  20:     0x7f3126d74bd3 - thread::Builder::spawn_inner::closure.96598"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at src/libstd/thread/mod.rs:349"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  21:     0x7f3126d757cd - boxed::F.FnBox<A>::call_box::h10612843318715210747"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "                        at src/liballoc/boxed.rs:396"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  22:     0x7f3128fd3251 - sys::thread::Thread::new::thread_start::hb94dd6e8abd80527WVv"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  23:     0x7f3125d5c181 - start_thread"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  24:     0x7f312526447c - __clone"
 2:17.21 PROCESS_OUTPUT: Thread-TestrunnerManager-3 (pid:21104) "  25:                0x0 - <unknown>"
```

**Comment by pcwalton** [comment]
Verified that the first few failures don't occur anymore on Linux. This just needed a rebase and an `ipc-channel` upgrade.

**Comment by jdm** [comment]
Almost the same set of tests failed in the last two runs:
```
/dom/ranges/Range-insertNode.html
---------------------------------
TIMEOUT [Parent]
/dom/ranges/Range-mutations.html
--------------------------------
TIMEOUT [Parent]
/dom/ranges/Range-surroundContents.html
---------------------------------------
TIMEOUT [Parent]
/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-auto.html
--------------------------------------------------------------------------
TIMEOUT expected FAIL placeholder: 'img', containerWidthStyle: '400px', containerHeightStyle: '400px', placeholderWidthAttr: '100', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '25%', 
TIMEOUT [Parent]
/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-percentage.html
--------------------------------------------------------------------------------
TIMEOUT expected FAIL placeholder: 'img', containerWidthStyle: '400px', containerHeightStyle: '400px', placeholderWidthAttr: '100', placeholderHeightAttr: '100%', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '25%', 
TIMEOUT [Parent]
/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-fixed.html
---------------------------------------------------------------------------
TIMEOUT expected FAIL placeholder: 'img', placeholderWidthAttr: '50%', placeholderHeightAttr: '100px', svgViewBoxAttr: '0 0 100 200', svgWidthAttr: '200', svgHeightAttr: '25%', 
TIMEOUT [Parent]
```
The only difference was the specific subtest for `svg-in-img-fixed.html`.

**Comment by pcwalton** [comment]
My current theory is that the bots are running out of file descriptors. Evidence: (1) it's only failing on Linux; (2) only on Linux does adding new IPC channels increase the number of file descriptors in use; (3) the Range tests open a ton of iframes; (4) each iframe creates several more IPC channels to the profiler tasks.

**Comment by pcwalton** [comment]
I have verified that the tests that failed before pass locally in a release build.

**Comment by pcwalton** [comment]
Along with the rest of e10s, this is currently blocked either on generating the metadata needed to move our WPT usage to release builds, rust-lang/cargo#1826 (which won't land due to design issues), or removing IPC on Linux.

**Comment by jdm** [comment]
```
/dom/ranges/Range-insertNode.html
---------------------------------
TIMEOUT [Parent]
/dom/ranges/Range-mutations.html
--------------------------------
TIMEOUT [Parent]
/dom/ranges/Range-surroundContents.html
---------------------------------------
TIMEOUT [Parent]
```
?

**Comment by pcwalton** [comment]
We have two WPT failures here. One is the image onload stuff and another is a timeout that turned into a crash. My theory for the latter is that it is a case of e10s perturbing the timing causing a preexisting crash to manifest sooner. I will try to verify that locally. For the former, we know that these tests never really worked right to begin with and depending on the timing of image vs document onload will succeed or fail. I will first try to adjust the expectations and if that continues to fail I will ignore the tests. OK, @jdm?

**Comment by pcwalton** [comment]
Oh, and if my theory for the former is correct, then I will adjust the test expectations and/or ignore as appropriate.

**Pull request merged**
