### PR TITLE
style: Less refcount churn while inserting in the rule tree.

### PR DESCRIPTION
**Pull request by emilio**
There's no need for it since we know no GC is happening while we're doing it.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17294)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo retry

 *LLVM ERROR: Invalid data was encountered while parsing the file

**Comment by julian-seward1** [comment]
This looks like a pretty clear win to me.  See numbers at
https://bugzilla.mozilla.org/show_bug.cgi?id=1372591#c0

**Comment by bholley** [comment]
Looks great to me! Please add some comments explaining why this is ok. r=me with that.

@bors-servo delegate+

**Pull request merged**
