### PR TITLE
Document the use and meaning of the devtools control messages. Fixes …

### PR DESCRIPTION
**Pull request by jdm**
…#6922.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7132)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

Thank you.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/devtools_traits/lib.rs, line 49 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7132#-JwQiO48MxM5VGYpsFat)** ([raw file](https://github.com/servo/servo/blob/5146a26a5e985447c8c5131e50ceb455d4331bcd/components/devtools_traits/lib.rs#L49)):</sup>
Grammar.

---

<sup>**[components/devtools_traits/lib.rs, line 62 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7132#-JwR0d8d6A5NV79d-L0q)** ([raw file](https://github.com/servo/servo/blob/5146a26a5e985447c8c5131e50ceb455d4331bcd/components/devtools_traits/lib.rs#L62)):</sup>
from the docs, it seems surprising that this variant is in the chrome enum; worth explaining?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7132)

**Comment by jdm** [comment]
That second comment inspired me to actually deal with the sprawling mess that the framerate callback stuff had become with the introduction of IPC.

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 8 of 8 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/devtools_traits/lib.rs, line 161 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7132#-JwW7ri__Pu_LHhJh_xv)** ([raw file](https://github.com/servo/servo/blob/e59de756081f0c5f3f0341cd8ded374537b2a22e/components/devtools_traits/lib.rs#L161)):</sup>
You realize I'm going to ask you to document these too, right? :)

---

<sup>**[components/script/devtools.rs, line 210 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7132#-JwWR2vWa15q1g3pqrxo)** ([raw file](https://github.com/servo/servo/blob/e59de756081f0c5f3f0341cd8ded374537b2a22e/components/script/devtools.rs#L210)):</sup>
Does it make sense to move this `unwrap()` outside the closure?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7132)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/devtools_traits/lib.rs, line 153 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7132#-JwbM0AcbWucLMdoAGbx)** ([raw file](https://github.com/servo/servo/blob/c81c3a2f70fdc5affe1a50b7b005b302cd306a50/components/devtools_traits/lib.rs#L153)):</sup>
"i.e., the document"

---

<sup>**[components/devtools_traits/lib.rs, line 159 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7132#-JwbLtueW_kN4uSLpIGV)** ([raw file](https://github.com/servo/servo/blob/c81c3a2f70fdc5affe1a50b7b005b302cd306a50/components/devtools_traits/lib.rs#L159)):</sup>
What are those `f32`s?

---

<sup>**[components/devtools_traits/lib.rs, line 161 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7132#-JwbMFdLVaGMh3GaDK5Q)** ([raw file](https://github.com/servo/servo/blob/c81c3a2f70fdc5affe1a50b7b005b302cd306a50/components/devtools_traits/lib.rs#L161)):</sup>
Nit: "the given pipeline"

---

<sup>**[components/devtools_traits/lib.rs, line 165 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7132#-JwbN6vDO4Mk_RbJBntw)** ([raw file](https://github.com/servo/servo/blob/c81c3a2f70fdc5affe1a50b7b005b302cd306a50/components/devtools_traits/lib.rs#L165)):</sup>
And the boolean is?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7132)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7132)

**Comment by jdm** [comment]
@bors-servo: r-
This failed tidy.

**Pull request merged**
