### PR TITLE
Firefox timeline integration #4957

### PR DESCRIPTION
**Pull request by gurobokum**
Available markers only:

Reflow
DOMEvent
Also need to implement:

Style marker
Paint marker
Javascript marker
frames reply, depends on getting javascript stack
I decided to make pull request before implemented another markers for getting feedback.
mb it would be better to create separated tasks.

Notices:
Marker doesn't fill stack and stackEnd
MemoryActor sends fake data because there is no memory profiler per tab
FramerateActor sends empty Vec, need implement http://mxr.mozilla.org/mozilla-central/source/dom/base/nsGlobalWindow.cpp#5240

### CODE REVIEW

**Comment by pcwalton** [comment]
This is awesome! :zap:

**Comment by jdm** [comment]
This is close! Most of the comments I left on Critic are just improvements for style and clarity!

**Comment by JIoJIaJIu** [comment]
@pcwalton thanks)

I found two bugs in current implementation:

1. Firefox crashed after some time (39.0a2)    
```
DBG-SERVER: Got: {
  "type": "markers",
  "markers": [],
  "from": "timeline2",
  "endTime": 113624885915641
}
2015-04-12 19:19:43: stackwalker.cc:125: INFO: Couldn't load symbols for: /home/jiojiajiu/Downloads/firefox/libxul.so|05928FF38ED146CBCE69F9C13E05D4660
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7ffe10fb5700
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7ffe10fb4f20
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7ffe10fb4f00
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7f7a499770f0
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7f7a61e64c00
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7f7a49977108
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7ffe10fb4ff0
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7f7a6209a280
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x37003600000000
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7f7a49977158
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7ffe10fb5aa0
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0xfffc7f7a6205e240
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7ffe10fb50c0
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7ffe10fb5108
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x207f7a766e24a9
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7f7a00000000
2015-04-12 19:19:43: stackwalker.cc:125: INFO: Couldn't load symbols for: /home/jiojiajiu/Downloads/firefox/libnspr4.so|7A2E702309862298A4EA7091B41577990
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7f7a49977158
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7ffe10fb5aa0
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0xfffc7f7a49342240
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x7ffe10fb4f40
2015-04-12 19:19:43: basic_code_modules.cc:88: INFO: No module at 0x0
...
```

2. Servo panicked after closing crashed firefox
```
<- {"type":"markers","markers":[],"from":"timeline2","endTime":113640119597118}
error: EOF
<- {"type":"markers","markers":[],"from":"timeline2","endTime":113640320068868}
thread 'PullTimelineMarkers' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(32) }', /home/larsberg/rust/src/libcore/result.rs:744
```

**Comment by jdm** [comment]
The Servo panic comes from write_json_packet not dealing with connection errors. The Firefox hang is really interesting! It looks like we should be returning values in milliseconds, and we're currently providing nanoseconds (http://mxr.mozilla.org/mozilla-central/source/browser/devtools/shared/timeline/marker-details.js#119). Maybe that will help?

**Comment by jdm** [comment]
Actually, that's not entirely true - it looks like we want to calculate a high resolution timestamp like https://developer.mozilla.org/en-US/docs/Web/API/Performance/now with fractional milliseconds.

**Comment by JIoJIaJIu** [comment]
@jdm, yes, it looks like you described. Could you create separated task on it, please?
Cause I have a questions: I need use window.performance in devtools crait, should I create one more channel or extend script_channel for getting Performance.now()?

Also about https://critic.hoppipolla.co.uk/showcomment?chain=11699  - I use `&mut self` in Emitter methods

**Comment by jdm** [comment]
Yes, we can use separate issue for the timestamps.

**Comment by jdm** [comment]
Go ahead and squash these together!

**Comment by JIoJIaJIu** [comment]
@jdm done

**Comment by Ms2ger** [comment]
@JIoJIaJIu: look like this cause a "warning: method is never used: `on_refresh_driver_tick`"; what should we do with it?

**Comment by JIoJIaJIu** [comment]
@Ms2ger [Here](https://github.com/servo/servo/blob/b7f59a36461e6c9eb08b8e48760168d3cb26a400/components/devtools/actors/framerate.rs#L70) it should be called once as a callback of [RequestAnimationFrame](http://hg.mozilla.org/mozilla-central/file/0a46652bd992/dom/base/nsGlobalWindow.cpp#l5298) and then it works recursively. 
There is in mozilla firefox [#1](http://hg.mozilla.org/mozilla-central/file/7f343964210b/toolkit/devtools/server/actors/framerate.js#l45) and [#2](http://hg.mozilla.org/mozilla-central/file/7f343964210b/toolkit/devtools/server/actors/framerate.js#l110)
If you will create subtask on me for implementing this it would be nice, cause I decided to make pull request and later fixed parts

**Pull request merged**
