### PR TITLE
Checking the browsing_context before change title

### LINKED ISSUE #10782: `title_changed` is too eager
```html
<!DOCTYPE html>
<title>Foo</title>
<script>
setTimeout(() => {
  var text =
    '<html xmlns="http://www.w3.org/1999/xhtml">' +
    '  <head>' +
    '    <title>Virtual Library</title>' +
    '  </head>' +
    '</html>';

  var parser = new DOMParser();
  var doc = parser.parseFromString(text, "text/xml");
}, 100);
</script>
```

changes the title of the window to "Virtual Library".

### PR DESCRIPTION
**Pull request by askeing**
fix #10782

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10821)

### CODE REVIEW

**Comment by askeing** [comment]
Testing HTML:
```html
<!DOCTYPE html>
<title>Foo</title>
<script>
setTimeout(() => {
  var text =
    '<html xmlns="http://www.w3.org/1999/xhtml">' +
    '  <head>' +
    '    <title>Virtual Library</title>' +
    '  </head>' +
    '</html>';

  var parser = new DOMParser();
  var doc = parser.parseFromString(text, "text/xml");
}, 100);
</script>
```
The title keep `Foo - servo`.

**Comment by shinglyu** [comment]
@askeing You can probably add the test HTML into WPT, see https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests

**Comment by jdm** [comment]
Unfortunately this change can't be verified by automated tests, since it's only the window frame title that changes, which isn't visible to JS.

**Comment by Ms2ger** [comment]
R? @jdm

**Comment by notriddle** [comment]
Isn't the window title exposed through the `<iframe browser>` API? I think you could automatically test it by running this test code in a mozbrower and doing the verification with a fake on the outside.

**Comment by nox** [comment]
What about just calling `title_changed` when the title actually changed instead of calling it so eagerly?

**Comment by jdm** [comment]
@nox I'm not sure what you're proposing. That's what the code tries to do?

**Comment by jdm** [comment]
@notriddle is absolutely right. We can use a test like `tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsershowmodalprompt_event.html` to load an HTML file that creates that DOMParser from the example in #10782. After it's finished parsing it can use `alert("done")` to signal that the test is complete. If the parent page has not observed a `mozbrowsertitlechange` event on the iframe, the test can pass.

**Comment by askeing** [comment]
@jdm, should I open another PR for the test?

**Comment by jdm** [comment]
Adding the commit here would be appropriate.

**Comment by askeing** [comment]
I found the parent page will get `mozbrowsertitlechange` at beginning with `e.detail = ""`, and then get real title `e.detail = "Foo"`.
So I call `assert_not_equals` for checking `e.detail` cannot be `Bar`, which is the title in DOMParser.

Origin:
```bash
$ ./mach test-wpt --debug-build tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html
Running 1 tests in web-platform-tests

Unsupported test type wdspec for product servo
  ▶ Unexpected subtest result in /_mozilla/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html:
  │ FAIL [expected PASS] Check if title_changed is too eager (issue #10782)
  │   → assert_not_equals: got disallowed value "Bar"
  │
  │ @http://web-platform.test:8000/_mozilla/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html:7:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1397:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1421:1

Ran 1 tests finished in 14.0 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 1 tests had unexpected subtest results
```

After modified:
```bash
 ./mach test-wpt --debug-build tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html
Running 1 tests in web-platform-tests

Unsupported test type wdspec for product servo
Ran 1 tests finished in 5.0 seconds.
  • 1 ran as expected. 0 tests skipped.
```

**Comment by jdm** [comment]
-S-needs-tests -S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/document.rs, line 621 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10821#-KGrQULVqW05mXtNYAbO:-KGrQULVqW05mXtNYAbP:1265773010) ([raw file](https://github.com/servo/servo/blob/7273b1edd2870945dea21aa428ad26cd3d4b0db2/components/script/dom/document.rs#L621)):*
`if self.browsing_context().is_some()`

---

*[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html, line 16 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10821#-KGrQaYdra6iNd0awwEZ:-KGrQaYeTxxxVNIa9dj3:788223167) ([raw file](https://github.com/servo/servo/blob/82f5f3b615edc4eb9a4f4af22a8bc56ee46836f8/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html#L16)):*
We should be able to use the regular iframe load event here instead, and use `t.step_func_done()`.

---

*[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event_iframe.html, line 5 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10821#-KGrQnIP9eu4F5jlMm8r:-KGrQnIQ4rt3YEpM5x1E:-1391245119) ([raw file](https://github.com/servo/servo/blob/82f5f3b615edc4eb9a4f4af22a8bc56ee46836f8/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event_iframe.html#L5)):*
Let's get rid of this timeout.

---

*[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event_iframe.html, line 14 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10821#-KGrQqq7Jx2IF8HFHgYB:-KGrQqq7Jx2IF8HFHgYC:940059113) ([raw file](https://github.com/servo/servo/blob/82f5f3b615edc4eb9a4f4af22a8bc56ee46836f8/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event_iframe.html#L14)):*
No need for this.

---

*[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event_iframe.html, line 16 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10821#-KGrQsFsHCcbKfbcTKHI:-KGrQsFsHCcbKfbcTKHJ:-912426046) ([raw file](https://github.com/servo/servo/blob/82f5f3b615edc4eb9a4f4af22a8bc56ee46836f8/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event_iframe.html#L16)):*
We don't need this if we use the load event.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10821#-:-KGrQvzxKiJrGUd0OaXX:-669340187)*

**Comment by askeing** [comment]
*[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html, line 16 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10821#-KGrQaYdra6iNd0awwEZ:-KGuiL8tMwAt-lKU80z_:1535480544) ([raw file](https://github.com/servo/servo/blob/82f5f3b615edc4eb9a4f4af22a8bc56ee46836f8/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html#L16)):*
Does the iframe load event mean listening on `mozbrowserloadend` event?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10821)*

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html, line 16 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10821#-KGrQaYdra6iNd0awwEZ:-KGwPFL9hmCAjF7bPzRT:1620234833) ([raw file](https://github.com/servo/servo/blob/82f5f3b615edc4eb9a4f4af22a8bc56ee46836f8/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsertitlechangedeagerly_event.html#L16)):*
No, just the `load` event.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10821)*

**Comment by jdm** [comment]
@bors-servo: delegate+
Looks good! Squash the commits together into one and go ahead and merge with r=jdm.
-S-awaiting-review +S-needs-squash 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10821#-:-KGx3Z-ADrOOjN6umw_N:1991225266)*

**Comment by jdm** [comment]
@bors-servo: retry
* #10457 #11027

**Comment by askeing** [comment]
`git clone` failed on Windows with following message,
```
Cloning into '.'...
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
program finished with exit code 128
```

**Comment by jdm** [comment]
@bors-servo: retry
* git

**Comment by jdm** [comment]
@bors-servo: retry
* infra

**Comment by mbrubeck** [comment]
@bors-servo retry

* servo/saltfs#363

**Comment by larsbergstrom** [comment]
@bors-servo retry
 - https://github.com/servo/saltfs/pull/365

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * Checking for intermittent

**Comment by mbrubeck** [comment]
> Checking for intermittent

Filed #10821

**Pull request merged**
