### PR TITLE
Update selectors to 0.10, with ToCss serialization.

### PR DESCRIPTION
**Pull request by SimonSapin**
r? @emilio 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12924)

### CODE REVIEW

**Comment by nox** [comment]
Reviewed 20 of 20 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12924)*

**Comment by nox** [comment]
@bors-servo r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12924#-:-KPTM0sLuU9ZfAgS3iRs:bkg9nno)*

**Comment by SimonSapin** [comment]
@bors-servo retry

* #12891
* #11574

**Comment by SimonSapin** [comment]
@bors-servo retry

* #11561

**Comment by SimonSapin** [comment]
@bors-servo retry

* #12891


Hopefully will have an easier time landing after #12942.

**Pull request merged**
