### PR TITLE
stylo: Preserve variants of 2d translate/rotate/scale functions in computed transform

### PR DESCRIPTION
**Pull request by Manishearth**
Necessary for the animation inspector to show the right thing.

r=hiikezoe https://bugzilla.mozilla.org/show_bug.cgi?id=1391145

fixes bug 1391145

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18492)

### CODE REVIEW

**Comment by Manishearth** [comment]
Hmmm

```
{"status": "FAIL", "group": "default", "message": "/css-transforms-1_dev/html/regions-transforms-017.htm fc438eab181efa3338e11df34b41e936b6a9e242\n/css-transforms-1_dev/html/reference/regions-transforms-017-ref.htm f949170eacb6d9aa4a41a742827ea33674b5948b\nTesting fc438eab181efa3338e11df34b41e936b6a9e242 == f949170eacb6d9aa4a41a742827ea33674b5948b", "stack": null, "subtest": null, "test": "/css-transforms-1_dev/html/regions-transforms-017.htm", "line": 15658, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css-transforms-1_dev/html/scalex.htm e65d8398eaf68a3ffe0849bf42cddf6230c84016\n/css-transforms-1_dev/html/reference/scalex-ref.htm afcc28704b3049c0e3b6aeb1023c468d07f7f864\nTesting e65d8398eaf68a3ffe0849bf42cddf6230c84016 == afcc28704b3049c0e3b6aeb1023c468d07f7f864", "stack": null, "subtest": null, "test": "/css-transforms-1_dev/html/scalex.htm", "line": 15784, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css-transforms-1_dev/html/transform-scalex-001.htm 23b755622cc81841a23cc8431a6546dfb1401c66\n/css-transforms-1_dev/html/reference/transform-scalex-ref.htm 3c4e61bbd16d8e58f32cf621cedc716d1497a538\nTesting 23b755622cc81841a23cc8431a6546dfb1401c66 == 3c4e61bbd16d8e58f32cf621cedc716d1497a538", "stack": null, "subtest": null, "test": "/css-transforms-1_dev/html/transform-scalex-001.htm", "line": 21714, "action": "test_result", "expected": "PASS"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css-transforms-1_dev/html/transform3d-backface-visibility-007.htm", "line": 22176, "action": "test_result", "expected": "FAIL"}
{"status": "FAIL", "group": "default", "message": "/css-transforms-1_dev/html/transform3d-perspective-008.htm 23b755622cc81841a23cc8431a6546dfb1401c66\n/css-transforms-1_dev/html/reference/transform-lime-square-ref.htm ea0d0b830335b2af66807ea298a69e4a2e874d08\nTesting 23b755622cc81841a23cc8431a6546dfb1401c66 == ea0d0b830335b2af66807ea298a69e4a2e874d08", "stack": null, "subtest": null, "test": "/css-transforms-1_dev/html/transform3d-perspective-008.htm", "line": 22256, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css-transforms-1_dev/html/transform3d-scale-005.htm fef963ebd3d66408a55f718bc1965088f565eb0a\n/css-transforms-1_dev/html/reference/transform3d-scale-005-ref.htm 23b755622cc81841a23cc8431a6546dfb1401c66\nTesting fef963ebd3d66408a55f718bc1965088f565eb0a == 23b755622cc81841a23cc8431a6546dfb1401c66", "stack": null, "subtest": null, "test": "/css-transforms-1_dev/html/transform3d-scale-005.htm", "line": 22383, "action": "test_result", "expected": "PASS"}
```

**Comment by Manishearth** [comment]
@bors-servo r=hiikezoe

made a mistake with the scale conversions. good tests.

**Comment by Manishearth** [comment]
@bors-servo r=hiikezoe

git push dammit

**Comment by Manishearth** [comment]
@bors-servo retry

 - weird c++ error?

**Comment by nox** [comment]
Doesn't that mean specified and computed values are now extremely similar, btw?

**Comment by Manishearth** [comment]
Yes, in fact for this to be a complete fix they should be exactly the same aside from computed::Length vs specified::Length. However I didn't want to put effort into generic-ifying them right now with the release so close, and was concerned about performance issues with servo. Feel free to make them use a generic `TransformFunction` type.

**Comment by nox** [comment]
Performance issues, which ones?

**Comment by Manishearth** [comment]
Layout has to calculate matrices more often, basically. Additionally, the animation will go through the slower SLERP algorithm more often (however simple animations may be faster).

This is not measured. I'm okay with making them the same, I just think we should measure it if we do (and didn't feel like it was worth it this close to the beta)

**Pull request merged**
