### PR TITLE
Making test-tidy check that = have space after them

### PR DESCRIPTION
**Pull request by jerneyio**
For issue #7460. Need to ensure compatibility with #7390.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7468)

### CODE REVIEW

**Comment by Ms2ger** [comment]
There's a lot of existing failures that will need to be fixed before this can land.

**Comment by JoshTheGoldfish** [comment]
Ok, I'll  go ahead and make those changes. It also looks like it's checking some that it shouldn't, i'll fix these as well.

**Comment by Ms2ger** [comment]
LGTM. Please squash your commits.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for tackling this!

**Pull request merged**
