### PR TITLE
Implement MessageEvent.InitMessageEvent

### LINKED ISSUE #25192: Implement MessageEvent.initMessageEvent
This is expected by WPT html/webappapis/scripting/events/messageevent-constructor.https.html and has IDL in https://html.spec.whatwg.org/multipage/comms.html#the-messageevent-interface

### PR DESCRIPTION
**Pull request by kunalmohan**
InitMessageEvent had to be implemented as required by wpt. For this few keys of struct `MessageEvent` are now wrapped inside DomRefCell wrapper.

---

- [x] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [x] These changes fix #25192  (GitHub issue number if applicable)

- [X] There are tests for these changes

### CODE REVIEW

**Comment by kunalmohan** [comment]
I am facing a problem with the build.
`./mach check` is running successfully, but `./mach build -d` fails with `(signal: 9, SIGKILL: kill)`

**Comment by CYBAI** [comment]
> I am facing a problem with the build.
> `./mach check` is running successfully, but `./mach build -d` fails with `(signal: 9, SIGKILL: kill)`

Do you have enough memory or disk space on your machine 👀?

**Comment by kunalmohan** [comment]
The build is finally successful. I don't think the memory should have been a problem (8GB RAM+ 8GB swap+600GB storage). I rebased my branch on the latest changes and tried `./mach clean` which gave an error (issue #24985 ). I also tried `./mach busted` this time which returned `unknown mach command`. So I gave `./mach build -d` another shot, and it was successful.

**Comment by kunalmohan** [comment]
Sorry, I forgot to update the tests. Is it necessary to run the tests on release build in order to update the tests?

**Comment by jdm** [comment]
Usually you can use the results of a debug build to update the tests, but let's wait and see what gets reported from CI.

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /html/webappapis/scripting/events/messageevent-constructor.https.html:
  └ PASS [expected FAIL] Default event values
  ▶ Unexpected subtest result in /html/webappapis/scripting/events/messageevent-constructor.https.html:
  └ PASS [expected FAIL] initMessageEvent operation
  ▶ Unexpected subtest result in /html/webappapis/scripting/events/messageevent-constructor.https.html:
  └ PASS [expected FAIL] initMessageEvent operation default parameter values

  ▶ Unexpected subtest result in /html/dom/idlharness.worker.html:
  └ PASS [expected FAIL] MessageEvent interface: operation initMessageEvent(DOMString, boolean, boolean, any, USVString, DOMString, MessageEventSource, [object Object])
  ▶ Unexpected subtest result in /html/dom/idlharness.worker.html:
  └ PASS [expected FAIL] MessageEvent interface: new MessageEvent("message", { data: 5 }) must inherit property "initMessageEvent(DOMString, boolean, boolean, any, USVString, DOMString, MessageEventSource, [object Object])" with the proper type
  ▶ Unexpected subtest result in /html/dom/idlharness.worker.html:
  └ PASS [expected FAIL] MessageEvent interface: calling initMessageEvent(DOMString, boolean, boolean, any, USVString, DOMString, MessageEventSource, [object Object]) on new MessageEvent("message", { data: 5 }) with too few arguments must throw TypeError
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
  └ PASS [expected FAIL] MessageEvent interface: operation initMessageEvent(DOMString, boolean, boolean, any, USVString, DOMString, MessageEventSource, [object Object])
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
  └ PASS [expected FAIL] MessageEvent interface: new MessageEvent("message", { data: 5 }) must inherit property "initMessageEvent(DOMString, boolean, boolean, any, USVString, DOMString, MessageEventSource, [object Object])" with the proper type
  ▶ Unexpected subtest result in /html/dom/idlharness.https.html?exclude=(Document|Window|HTML.*):
  └ PASS [expected FAIL] MessageEvent interface: calling initMessageEvent(DOMString, boolean, boolean, any, USVString, DOMString, MessageEventSource, [object Object]) on new MessageEvent("message", { data: 5 }) with too few arguments must throw TypeError
```

**Comment by jdm** [comment]
This is missing changes to tests/wpt/metadata/html/dom/idlharness.https.html.ini and tests/wpt/metadata/html/dom/idlharness.worker.js.ini.

**Comment by kunalmohan** [comment]
https://github.com/servo/servo/issues/25192#issuecomment-563294525
I ran `update-wpt` for the test mentioned in the above comment and only the file present in the commit was changed.
If I run the command for all the  wpt tests a large number of files are getting changed, so should I do that?

**Comment by jdm** [comment]
I recommend running tests/wpt/web-platform-tests/html/dom/idlharness.https.html and tests/wpt/web-platform-tests/html/dom/idlharness.worker.js and running update-wpt on the log for those tests.

**Comment by kunalmohan** [comment]
@jdm 
There is some error occurring while testing tests/wpt/web-platform-tests/html/dom/idlharness.worker.js
After the test ends, trying to close servo window gives the following error in the terminal:
```
0:29.84 INFO Pausing until the browser exits
 7:17.37 pid:16888 assertion failed: `(left == right)`
 7:17.37 pid:16888   left: `2`,
 7:17.37 pid:16888  right: `1`: This runtime still has live children. (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at /home/kunal/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/9b0d063/src/rust.rs:410)
 7:17.37 pid:16888 stack backtrace:
 7:18.28 pid:16888    0: servo::backtrace::print
 7:18.28 pid:16888    1: servo::main::{{closure}}
 7:18.30 pid:16888    2: std::panicking::rust_panic_with_hook
 7:18.30 pid:16888              at src/libstd/panicking.rs:475
 7:18.30 pid:16888    3: rust_begin_unwind
 7:18.30 pid:16888              at src/libstd/panicking.rs:375
 7:18.30 pid:16888    4: std::panicking::begin_panic_fmt
 7:18.30 pid:16888              at src/libstd/panicking.rs:326
 7:18.30 pid:16888    5: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop
 7:18.30 pid:16888    6: _ZN4core3ptr18real_drop_in_place17hc34c57038836aeadE.llvm.10556966945077242064
 7:18.30 pid:16888    7: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
 7:18.30 pid:16888    8: core::ptr::real_drop_in_place
 7:18.30 pid:16888    9: std::sys_common::backtrace::__rust_begin_short_backtrace
 7:18.30 pid:16888   10: _ZN3std9panicking3try7do_call17heded3c5437dd76dfE.llvm.1623674583914297179
 7:18.30 pid:16888   11: __rust_maybe_catch_panic
 7:18.30 pid:16888              at src/libpanic_unwind/lib.rs:78
 7:18.30 pid:16888   12: core::ops::function::FnOnce::call_once{{vtable.shim}}
 7:18.30 pid:16888   13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
 7:18.30 pid:16888              at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63/src/liballoc/boxed.rs:969
 7:18.30 pid:16888   14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
 7:18.30 pid:16888              at /rustc/6d77e45f01079fe3d40180b3e256e414ab379f63/src/liballoc/boxed.rs:969
 7:18.30 pid:16888       std::sys_common::thread::start_thread
 7:18.30 pid:16888              at src/libstd/sys_common/thread.rs:13
 7:18.30 pid:16888       std::sys::unix::thread::Thread::new::thread_start
 7:18.30 pid:16888              at src/libstd/sys/unix/thread.rs:80
 7:18.30 pid:16888   15: start_thread
 7:18.30 pid:16888   16: __clone
 7:18.30 pid:16888 
 7:18.30 pid:16888 [2019-12-18T16:59:50Z ERROR servo] assertion failed: `(left == right)`
 7:18.30 pid:16888   left: `2`,
 7:18.30 pid:16888  right: `1`: This runtime still has live children.

```
And servo still does not close. I think logs are not getting completely updated because of this.

**Comment by jdm** [comment]
Any difference if you run with `--headless`?

**Comment by kunalmohan** [comment]
> Any difference if you run with `--headless`?

This helped. Test ended peacefully.

FYI: There is another error that comes up while the tests are running:
```
0:36.63 pid:18654 Full command: /mnt/sda1/Documents/webpages/rust/servo/target/release/servo --hard-fail -u Servo/wptrunner -z http://web-platform.test:8000/html/dom/idlharness.worker.html -Z replace-surrogates --user-stylesheet /mnt/sda1/Documents/webpages/rust/servo/resources/ahem.css --certificate-path /mnt/sda1/Documents/webpages/rust/servo/tests/wpt/web-platform-tests/tools/certs/cacert.pem
pid:18654 
 0:36.63 pid:18654 
 0:36.63 pid:18654 
 0:39.13 pid:18654 [2019-12-18T17:16:13Z ERROR ws::io] Unable to establish connection to ws://foo/: WS Error <Io(Custom { kind: Other, error: "failed to lookup address information: Temporary failure in name resolution" })>
```

**Pull request merged**
