### PR TITLE
Minor improvements to #[derive(ToCss)]

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17356)

### CODE REVIEW

**Comment by nox** [comment]
r? @emilio 

This PR should be enough to avoid the problem reported by @jyc in #17349.

**Comment by nox** [comment]
Enabled `syn`'s feature `full` in `style_derive`.

@bors-servo r=SimonSapin

**Comment by jdm** [comment]
```
   Compiling style_derive v0.0.1 (file:///home/servo/buildbot/slave/linux-dev/build/components/style_derive)
error[E0432]: unresolved import `syn::visit::Visitor`
  --> /home/servo/buildbot/slave/linux-dev/build/components/style_derive/to_css.rs:99:9
   |
99 |     use syn::visit::Visitor;
   |         ^^^^^^^^^^^^^^^^^^^ Could not find `visit` in `syn`

error[E0433]: failed to resolve. Could not find `visit` in `syn`
   --> /home/servo/buildbot/slave/linux-dev/build/components/style_derive/to_css.rs:113:13
    |
113 |             syn::visit::walk_path(self, path);
    |             ^^^^^^^^^^^^^^^^^^^^^ Could not find `visit` in `syn`

error: cannot continue compilation due to previous error
```

**Comment by nox** [comment]
The required feature was actually `visit`.

@bors-servo r=SimonSapin

**Comment by nox** [comment]
Homu seems stuck...

@bors-servo r=SimonSapin

**Pull request merged**
