### PR TITLE
added dom api #8225

### LINKED ISSUE #8225: Implement Document.createTouchList
Spec: https://w3c.github.io/touch-events/#widl-Document-createTouchList-TouchList-Touch-touches and https://w3c.github.io/touch-events/#idl-def-Document

We started implementing support for touch events on websites recently, and some websites want to use an API that we don't implement yet. We need to add the declaration to the WebIDL (next to `createTouchEvent`), and add the corresponding Rust method to the `Document` implementation that returns a new `TouchList` object. There's an example of doing this in `handle_touch_event`.

Code: components/script/dom/webidls/Document.webidl, components/script/dom/document.rs
Test: `./mach test-wpt tests/wpt/web-platform-tests/touch-events/create-touch-touchlist.html`

### PR DESCRIPTION
**Pull request by k-cross**
accidentally added an interface for touchEvent, i left them but commented out. if you want the deleted i can do that too.

Fixes #8225.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8634)

### CODE REVIEW

**Comment by nox** [comment]
Thanks for your contribution, please remove the commented-out code.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[components/script/dom/document.rs, line 1935 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8634#-K3dKNEmG12cXByqb93P:-K3dKNEmG12cXByqb93Q:375678204) ([raw file](https://github.com/servo/servo/blob/f61a3bc3dacad180d484bccd61c8d7df8acdaed3/components/script/dom/document.rs#L1935)):_
I guess the link is the wrong one on purpose because the correct one is [insanely long](https://w3c.github.io/touch-events/#widl-Document-createTouchList-TouchList-Touch-touches)?

---

_[components/script/dom/document.rs, line 1968 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8634#-K3dKKf9RigJEIX4O_RK:-K3dKKf9RigJEIX4O_RL:1483312879) ([raw file](https://github.com/servo/servo/blob/f61a3bc3dacad180d484bccd61c8d7df8acdaed3/components/script/dom/document.rs#L1968)):_
Please remove it, we don't commit commented-out code.

---

_[components/script/dom/webidls/Document.webidl, line 183 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8634#-K3dKYeWnBishxfIyaUW:-K3dKYeWnBishxfIyaUX:-494177703) ([raw file](https://github.com/servo/servo/blob/f61a3bc3dacad180d484bccd61c8d7df8acdaed3/components/script/dom/webidls/Document.webidl#L183)):_
Please remove.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8634#-:-K3dKgeImXC6Z3XtPxKU:-238877613)_

**Comment by k-cross** [comment]
Ok, I'll be sure to not add commented code again. I also changed the weblink to point to the right location.

**Comment by nox** [comment]
Thanks for your quick fixes, still one more to go and it can be merged.

-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[components/script/dom/document.rs, line 1935 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8634#-K3dKNEmG12cXByqb93P:-K3dc6i996LhjGkQe5K6:-1930160905) ([raw file](https://github.com/servo/servo/blob/f61a3bc3dacad180d484bccd61c8d7df8acdaed3/components/script/dom/document.rs#L1935)):_
You didn't fix the right link. :)

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8634#-:-K3dcCWGdtUJfeRj0cPQ:1748650497)_

**Comment by nox** [comment]
Reviewed 2 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8634)_

**Comment by nox** [comment]
Sorry, reviewed old code…

-S-needs-code-changes 

@bors-servo r+

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8634#-:-K3dcMwcujTefV7K__2Z:-2126415448)_

**Comment by jdm** [comment]
`./mach test-tidy` says
```
./components/script/dom/document.rs:1911: trailing whitespace
./components/script/dom/document.rs:1939: trailing whitespace
```

**Comment by jdm** [comment]
Also:
```

  ▶ Unexpected subtest result in /touch-events/create-touch-touchlist.html:
  └ PASS [expected FAIL] document.createTouchList exists and correctly creates a TouchList from zero Touch objects

  ▶ Unexpected subtest result in /touch-events/create-touch-touchlist.html:
  └ PASS [expected FAIL] document.createTouchList exists and correctly creates a TouchList from a single Touch

  ▶ Unexpected subtest result in /touch-events/create-touch-touchlist.html:
  └ PASS [expected FAIL] document.createTouchList exists and correctly creates a TouchList from two Touch objects
```
That's from `./mach test-wpt tests/wpt/web-platform-tests/touch-events/create-touch-touchlist.html`. We'll need to remove http://mxr.mozilla.org/servo/source/tests/wpt/metadata/touch-events/create-touch-touchlist.html.ini now that all the tests pass.

**Comment by nox** [comment]
And I can't read I guess.

**Comment by nox** [comment]
And:

```
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/node.rs:26:65: 26:78 warning: unused import, #[warn(unused_imports)] on by default
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/node.rs:27:53: 27:70 warning: unused import, #[warn(unused_imports)] on by default
```

**Comment by k-cross** [comment]
I just used the test that was written in the issue and tried to pass that.

Did I not do something correctly? I'm having a hard time finding out what I should do next.

**Comment by jdm** [comment]
Did you see my latest comment? If you remove the ini file, you should see a difference in the output of running that test.

**Comment by k-cross** [comment]
Oh, ok. I'll do that

**Comment by nox** [comment]
Looks ok, but the branch needs a rebase. Please squash everything and remove the merge commit in the middle.

-S-awaiting-review +S-needs-rebase 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8634#-:-K3nT8GB4QYjWAD4mb9L:737763500)_

**Comment by jdm** [comment]
We still need to remove the ini file and push that change to this branch, otherwise the test harness will continue to report unexpected test results.

**Comment by k-cross** [comment]
Ok, I'll do that and commit the change. In class right now but it'll be done today.

**Comment by k-cross** [comment]
I'm not sure if I need to do anything else, I'm okay right? I guess I'll grab another issue when I'm done with finals.

**Comment by jdm** [comment]
@k-cross, yes, the changes are fine. The only comment that's not addressed is @nox's request to [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) the commits into one. If that's causing difficulty, let us know and we can help!

**Comment by nox** [comment]
@k-cross Ping?

**Comment by nox** [comment]
-S-awaiting-review 

---

Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8634#-:-K5RpQ97MrppRWv2qvvI:879583689)*

**Comment by k-cross** [comment]
pong, I'll get them squashed today.

**Comment by nox** [comment]
@k-cross Ping? I can rebase it myself if you want.

**Comment by KiChjang** [comment]
Rebased in #9025

**Pull request closed without merging**
