### PR TITLE
Mozbrowser top level browsing context

### PR DESCRIPTION
**Pull request by asajeffrey**
Got `window.top` and `window.parent` to return the right result inside a `mozbrowser` iframe.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11644)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Uses https://github.com/servo/heapsize/pull/57

**Comment by ConnorGBrewster** [comment]
Everything looks good to me! Squash and r=me

-S-awaiting-review +S-needs-squash 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 6 of 6 files at r1, 5 of 5 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11644#-:-KJcARvLP5JqdUfnmsGc:477783674)*

**Comment by ConnorGBrewster** [comment]
Woops missed a couple things.

+S-needs-code-changes 

<details><summary><i>Previously, ConnorGBrewster (Connor Brewster) wrote…</i></summary>
> Everything looks good to me! Squash and r=me
> 
> -S-awaiting-review +S-needs-squash 
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowser_iframe_child.html, line 8 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11644#-KJcE2e2cECUTEluH7_G:-KJcE2e2cECUTEluH7_H:-8645025) ([raw file](https://github.com/servo/servo/blob/44ddb4243897fdb89badb4931718e480454c6ee2/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowser_iframe_child.html#L8)):*
> ```HTML
>     send_test_results({
>         "id": 'aaee4290-6a78-4932-a1d1-fbbe158fb473',
>         "parent": window.parent == window,
> ```

Should this be `===`?

---

*[tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowser_iframe_grandchild.html, line 8 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11644#-KJcE-2SqKKy2x5LFjZt:-KJcE-2SqKKy2x5LFjZu:-8645025) ([raw file](https://github.com/servo/servo/blob/44ddb4243897fdb89badb4931718e480454c6ee2/tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowser_iframe_grandchild.html#L8)):*
> ```HTML
>         "id": 'a94c0025-08dc-49a6-8f98-fbbaacfdd296',
>         "parent": window.parent !== window,
>         "grandparent": window.parent.parent == window.parent,
> ```

Should this be `===`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11644#-:-KJcE5Xacoi1zBTLZW65:-132256438)*

**Comment by asajeffrey** [comment]
Squashed. @bors-servo r=ConnerGBrewster

**Comment by asajeffrey** [comment]
Argh I meant @ConnorGBrewster not going to edit that now though!

**Comment by asajeffrey** [comment]
Retry
* #11663

**Comment by larsbergstrom** [comment]
@bors-servo retry
   - #11663

**Pull request merged**
