### PR TITLE
Throw a SyntaxError if the WebSocket URL can't be parsed. Fix #6061

### LINKED ISSUE #6061: Throw a SyntaxError if the WebSocket URL can't be parsed.
Blocks #6060.

* Spec: <https://html.spec.whatwg.org/multipage/#dom-websocket>, <https://html.spec.whatwg.org/multipage/#parse-a-websocket-url%27s-components>.
* Code: `components/script/dom/websocket.rs`.
* Test: `/websockets/Create-invalid-urls.htm`.

### PR DESCRIPTION
**Pull request by Nashenas88**
Fix #6061.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6127)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed on critic (though I need to have another look at `parse_web_socket_url`).

**Comment by SimonSapin** [comment]
Looks good! Please squash the commits, and this will be good to go. I’ve also edited your PR message to include "Fix #6061" (rather than just the number) so that GitHub will close the issue automatically when this is merged.

**Comment by Nashenas88** [comment]
Should the S-needs-squash tag get cleared automatically or did I make a mistake?

**Comment by SimonSapin** [comment]
I don’t think our automation is that good yet. But what did you change? I still see 7 commits.

**Comment by Nashenas88** [comment]
I was doing the rebasing incorrectly. I was passing --autosquash without --interactive.

**Pull request merged**
