### PR TITLE
Add RangeError and use it in the constructors for TextEncoder and TextDecoder.

### LINKED ISSUE #5620: Use RangeError for TextEncoder/TextDecoder
Blocks #5601.

* Spec: <https://encoding.spec.whatwg.org/#dom-textdecoder>, <https://encoding.spec.whatwg.org/#dom-textencoder>.
* Code: `components/script/dom/textdecoder.rs`, `components/script/dom/textencoder.rs`, `components/script/dom/bindings/error.rs`.
* Test: possibly `/encoding/api-replacement-encodings.html`, `/encoding/textencoder-constructor-non-utf.html`.

To fix this bug, you'll first need to implement `RangeError` exceptions. This should be analogous to the `TypeError` implementation that already exists in `components/script/dom/bindings/error.rs`. I'd extend `get_error_message` to accept one error number for `TypeError` and one for `RangeError`, and create a second static like `ERROR_FORMAT_STRING` that uses `JSEXN_RANGEERR`.

Then you'll need to return `Err(Error::Range)` in the places that currently have TODO/FIXME comments mentioning "RangeError".

Bonus point for writing additional tests for the case where the encoding argument is not an encoding at all.

### PR DESCRIPTION
**Pull request by aneeshusa**
Fixes #5620, and adds a few extra test cases.

Currently waiting on a few upstream PRs in rust-encoding to land.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5659)

### CODE REVIEW

**Comment by jdm** [comment]
Great work! @Ms2ger has left comments on the Critic review.

**Comment by aneeshusa** [comment]
Fixed the issues. How does Critic know I fixed the issues!? Magic.

**Comment by Ms2ger** [comment]
```
/encoding/api-replacement-encodings.html
----------------------------------------
FAIL Label for "replacement" should be rejected by API: hz-gb-2312
/encoding/textencoder-constructor-non-utf.html
----------------------------------------------
FAIL Non-UTF encodings supported only for decode, not encode: gbk
FAIL UTF encodings are supported for encode and decode: utf-16le
```

Let's bring those expectations back for now.

**Comment by Ms2ger** [comment]
Thanks! Could you squash everything except "Add Rust code for RangeErrors." into one commit?

**Pull request merged**
