### PR TITLE
layout: Don't strip trailing newlines from fragments, since we use their presence to determine the line flush mode.

### PR DESCRIPTION
**Pull request by pcwalton**
Fixes the "jumpiness" seen on the Google home page, Wikipedia, and many
other places.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5816)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed files:
- components/layout/inline.rs @ r1
- tests/html/incremental_inline_line_flush_mode.html @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5816)

**Comment by tdaede** [comment]
This fixes the jumpy text on purple background on github.com, but there is now a box character rendered at the newline.

screenshot from 2015-04-23 14 21 52

**Comment by pcwalton** [comment]
@tdaede Please file a follow-up bug. Maybe we should be using a separate flag on scanned text runs to indicate that a line flush is required instead of preserving the newline, but it's more important to get this landed now.

**Comment by pcwalton** [comment]
OK, I implemented an alternate approach that should fix the Linux text failures.

@tdaede This should fix your bug as well.

r? @mbrubeck

**Comment by jdm** [comment]
```
/html/dom/elements/global-attributes/dir_auto-pre-N-EN.html
-----------------------------------------------------------
FAIL [Parent]
```

**Comment by mbrubeck** [comment]
r+, needs squash.

**Pull request merged**
