### PR TITLE
Add &DomRoot<T> lint check

### LINKED ISSUE #25342: Add lint check for `&Dom<` and `&DomRoot<`
`&Dom<T>` and `&DomRoot<T>` are strictly less expressive than `&T`, so there's no reason to use them.

Code: https://github.com/servo/servo/blob/aa36d5f657eb32b59d994d08b177a02372b4b01c/python/tidy/servo_tidy/tidy.py#L624-L625

### PR DESCRIPTION
**Pull request by lberrymage**
So far, the lint check code appears to work as intended. However, some trait implementations require modification to pass the lint check and I'm not sure how to fix these. Commit 92cf5d5 attempts to correct one of the implementations, but fails to compile with error:
```
  --> components/script/dom/servoparser/xml.rs:76:36
   |
76 |         tree_builder.trace_handles(&tracer);
   |                                    ^^^^^^^ expected struct `dom::bindings::root::Dom`, found struct `dom::node::Node`
   |
   = note: expected struct `dom::bindings::root::Dom<dom::node::Node>`
              found struct `dom::node::Node`
   = note: required for the cast to the object type `dyn html5ever::tree_builder::Tracer<Handle = dom::bindings::root::Dom<dom::node::Node>>`
```
I've tried to debug further but to no avail. I also don't want to mangle too much existing code unnecessarily. Any help is appreciated.

- [ ] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
`./mach test-tidy --all` does, and some are directly related to this PR
- [ ] These changes fix #25342
The fix is a WIP

- [X] There are tests for these changes

Note that I will clean up the commit history before the final PR.

### CODE REVIEW

**Comment by jdm** [comment]
Shoot; that's a complex case to deal with. Let's remove the `&Dom<T>` check for now and file a followup issue. We can keep any code changes, though (except the one causing the compile error, obviously).

**Comment by lberrymage** [comment]
So to clarify, I should keep the check for `&DomRoot<T>` then, right?

**Comment by jdm** [comment]
Yes, please.

**Comment by lberrymage** [comment]
This is me trying to rename the branch acccordingly. GitHub won't let me change the branch to merge, so that's what all this is.

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Pull request merged**
