### PR TITLE
Update azure and its dependencies

### LINKED ISSUE #6088: Replace /usr/bin/find hacks in dependency makefiles with Cargo variables
Some of our dependencies makefiles have hacks like this:

https://github.com/servo/rust-azure/blob/11d7292919a365c55ca6204c465c5eeefcabfe05/makefile.cargo#L62
```Makefile
SKIA_OUTDIR = $(shell find $(OUT_DIR)/../.. -name 'skia-*' -type d)/out
```
… which break when e.g. there is more then one directory matching `skia-*` (multiple versions have been built without `cargo clean`).

Instead, we should be using Cargo’s metadata and `DEP_*` environment variables: http://doc.crates.io/build-script.html#the-links-manifest-key

### PR DESCRIPTION
**Pull request by mbrubeck**
#6088. r? @SimonSapin

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6196)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r+

**Comment by mbrubeck** [comment]
@bors-servo retry

```
/XMLHttpRequest/responsexml-non-well-formed.htm
-----------------------------------------------
TIMEOUT [Parent]
```

**Comment by jdm** [comment]
Specifically that was #5798

**Pull request merged**
