### PR TITLE
Stylo uplifts Part 1

### PR DESCRIPTION
**Pull request by bholley**
@pcwalton indicated his approval for landing stuff for the servo/gecko layout integration into the tree, which will improve maintainability for that effort. Here's an initial batch.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9004)

### CODE REVIEW

**Comment by bholley** [comment]
I'm refactoring components/layout and moving parts of it to components/style, so I just removed the commit we discussed from this queue, and will include it in that refactoring.

**Comment by pcwalton** [comment]
Seems good to me.

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #8157

**Comment by Manishearth** [comment]
@bors-servo retry

 - #9012

**Pull request merged**
