### PR TITLE
Allow border radii to be set via preshints

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes rendering of `<hr>`

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16800)

### CODE REVIEW

**Comment by Manishearth** [comment]
Might be worth converting https://github.com/Manishearth/servo/blob/195e37954f6921e78fc9e7acdca2baa749e11778/ports/geckolib/glue.rs#L1458 into a panic now that we support all preshints

**Comment by emilio** [comment]
@bors-servo r+

Yeah, converting it into a panic as a followup sounds good to me.

**Comment by Manishearth** [comment]
It's one line, I'll just make it a panic here itself

**Pull request merged**
