### PR TITLE
Fixed code_value values

### PR DESCRIPTION
**Pull request by minsumm**
Changed Key::N to KeyN, also changed Equals to Equal, and NumpadEquals to NumpadEqual.

### CODE REVIEW

**Comment by jdm** [comment]
Thanks!

**Comment by Ms2ger** [comment]
@genkku, please associate your commit email address with your github account.

**Comment by genkku** [comment]
I have associated the commit email address with my github account.

**Comment by jdm** [comment]
@genkku Unfortunately this requires a rebase now, as there are merge conflicts.

**Comment by genkku** [comment]
Oh my! This looks messy. I hope I haven't messed up something terribly :)

**Comment by jdm** [comment]
Yeah, that doesn't look quite right; all of the Key::N changes are missing, for one thing. Could you make a new version based on master/origin and force push it to this branch?

**Comment by genkku** [comment]
It seems that during my flailing attempt to transition from essentially bedroom programming to contributing to a project of this size, someone succesfully made the changes to the Key::N values.

However, the Equal and KpEqual values are still different from the spec. Hopefully there are no more problems :-)

**Comment by jdm** [comment]
Heh, whoops. Looks good!

**Pull request merged**
