### PR TITLE
Add move protection to `Root` and friends

### LINKED ISSUE #5724: Write a lint to flag moving Root values
They should not be moved, because that can change the ordering of the values that get unrooted later. It would be nicer to catch this at compile time than runtime.

### PR DESCRIPTION
**Pull request by Manishearth**
fixes #5724, #5737

uses https://github.com/Manishearth/rust-tenacious (can be moved in-tree if needed)

I can make it `Deny` by default too (I'll add a cargo feature to tenacious), though we might want it on
`Warn` until we get some mileage on it.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5855)

### CODE REVIEW

**Comment by Manishearth** [comment]
cc @munksgaard `ExprUseVisitor` was quite useful here.

However, in the case of humpty_dumpty, we need to do the opposite of `ExprUseVisitor` -- we can use it to track consumption (ish) but we'll still need to track branches somehow. Not sure if it will be useful; I couldn't quickly come up with a way that avoided tracking branches.

**Comment by kmcallister** [comment]
Reviewed files:
- components/plugins/Cargo.toml @ r1
- components/plugins/lib.rs @ r1
- components/script/dom/bindings/codegen/CodegenRust.py @ r2
- components/script/dom/bindings/global.rs @ r2
- components/script/dom/bindings/js.rs @ r3
- components/script/dom/bindings/mod.rs @ r2
- components/script/dom/bindings/trace.rs @ r3
- components/script/dom/document.rs @ r2
- components/script/dom/domimplementation.rs @ r2
- components/script/dom/element.rs @ r2
- components/script/dom/eventdispatcher.rs @ r2
- components/script/dom/htmlformelement.rs @ r2
- components/script/dom/htmlinputelement.rs @ r2
- components/script/dom/htmllinkelement.rs @ r3
- components/script/dom/htmlscriptelement.rs @ r2
- components/script/dom/node.rs @ r3
- components/script/dom/text.rs @ r2
- components/script/script_task.rs @ r3
- components/servo/Cargo.lock @ r2
- ports/cef/Cargo.lock @ r2
- ports/gonk/Cargo.lock @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5855)

**Comment by Manishearth** [comment]
@bors-servo r=kmc,munksgaard

(@munksgaard reviewed rust-tenacious)

**Comment by Ms2ger** [comment]
```

/home/servo/buildbot/slave/linux2/build/components/script/dom/element.rs:731:13: 731:17 warning: #[no_move] type `dom::bindings::js::Root<dom::attr::Attr>` moved, #[warn(moved_no_move)] on by default
/home/servo/buildbot/slave/linux2/build/components/script/dom/element.rs:731         for attr in attrs.iter().map(|attr| attr.root()) {
                                                                                         ^~~~
/home/servo/buildbot/slave/linux2/build/components/script/dom/element.rs:731:13: 731:17 warning: #[no_move] type `core::option::Option<dom::bindings::js::Root<dom::attr::Attr>>` moved, #[warn(moved_no_move)] on by default
/home/servo/buildbot/slave/linux2/build/components/script/dom/element.rs:731         for attr in attrs.iter().map(|attr| attr.root()) {
                                                                                         ^~~~
/home/servo/buildbot/slave/linux2/build/components/script/dom/htmlinputelement.rs:844:18: 844:24 warning: #[no_move] type `dom::bindings::js::Root<dom::htmlinputelement::HTMLInputElement>` moved, #[warn(moved_no_move)] on by default
/home/servo/buildbot/slave/linux2/build/components/script/dom/htmlinputelement.rs:844             Some(button) => {
                                                                                                       ^~~~~~
/home/servo/buildbot/slave/linux2/build/components/script/dom/htmlinputelement.rs:844:13: 844:25 warning: #[no_move] type `core::option::Option<dom::bindings::js::Root<dom::htmlinputelement::HTMLInputElement>>` moved, #[warn(moved_no_move)] on by default
/home/servo/buildbot/slave/linux2/build/components/script/dom/htmlinputelement.rs:844             Some(button) => {
                                                                                                  ^~~~~~~~~~~~
```

**Comment by Manishearth** [comment]
ick, I thought I fixed that. Must have lost it in a rebase.

**Comment by Manishearth** [comment]
wha

**Comment by Manishearth** [comment]
ah, works now.

**Pull request merged**
