### PR TITLE
Allow -moz-stack-sizing to work in a single direction only.

### PR DESCRIPTION
**Pull request by pamadini**
https://bugzilla.mozilla.org/show_bug.cgi?id=1364115
https://reviewboard.mozilla.org/r/138434/

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because these properties are not implemented

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16892)

### CODE REVIEW

**Comment by pamadini** [comment]
r=manishearth in https://bugzilla.mozilla.org/show_bug.cgi?id=1364115

**Comment by jdm** [comment]
@bors-servo: r-
Build-cef failed on Travis

**Comment by jdm** [comment]
Bad autocorrect. Build-geckolib.

**Comment by pamadini** [comment]
@jdm Isn't this supposed to land before the Gecko changes?

**Comment by Manishearth** [comment]
Yes, but it has to build independently. You haven't checked in the bindings updates. This is tricky to generate, but I can't do it for you right now because I'm on the phone. Will help later.

**Comment by Manishearth** [comment]
```patch
--- a/components/style/gecko/generated/structs_debug.rs
+++ b/components/style/gecko/generated/structs_debug.rs
@@ -185,9 +185,6 @@ pub mod root {
     pub const NS_FONT_SUB_SUPER_LARGE_SIZE: f64 = 45.;
     pub const NS_FONT_VARIANT_NORMAL: ::std::os::raw::c_uint = 0;
     pub const NS_FONT_VARIANT_SMALL_CAPS: ::std::os::raw::c_uint = 1;
-    pub const NS_STYLE_STACK_SIZING_IGNORE: ::std::os::raw::c_uint = 0;
-    pub const NS_STYLE_STACK_SIZING_STRETCH_TO_FIT: ::std::os::raw::c_uint =
-        1;
     pub const NS_STYLE_AZIMUTH_LEFT_SIDE: ::std::os::raw::c_uint = 0;
     pub const NS_STYLE_AZIMUTH_FAR_LEFT: ::std::os::raw::c_uint = 1;
     pub const NS_STYLE_AZIMUTH_LEFT: ::std::os::raw::c_uint = 2;
@@ -6132,6 +6129,14 @@ pub mod root {
         }
         #[repr(u8)]
         #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
+        pub enum StyleStackSizing {
+            Ignore = 0,
+            StretchToFit = 1,
+            IgnoreHorizontal = 2,
+            IgnoreVertical = 3,
+        }
+        #[repr(u8)]
+        #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
         pub enum StyleTextJustify {
             None = 0,
             Auto = 1,
```

**Comment by Manishearth** [comment]
```patch
diff --git a/components/style/gecko/generated/structs_debug.rs b/components/style/gecko/generated/structs_debug.rs
index 28db4a1..6bb2b59 100644
--- a/components/style/gecko/generated/structs_debug.rs
+++ b/components/style/gecko/generated/structs_debug.rs
@@ -185,9 +185,6 @@ pub mod root {
     pub const NS_FONT_SUB_SUPER_LARGE_SIZE: f64 = 45.;
     pub const NS_FONT_VARIANT_NORMAL: ::std::os::raw::c_uint = 0;
     pub const NS_FONT_VARIANT_SMALL_CAPS: ::std::os::raw::c_uint = 1;
-    pub const NS_STYLE_STACK_SIZING_IGNORE: ::std::os::raw::c_uint = 0;
-    pub const NS_STYLE_STACK_SIZING_STRETCH_TO_FIT: ::std::os::raw::c_uint =
-        1;
     pub const NS_STYLE_AZIMUTH_LEFT_SIDE: ::std::os::raw::c_uint = 0;
     pub const NS_STYLE_AZIMUTH_FAR_LEFT: ::std::os::raw::c_uint = 1;
     pub const NS_STYLE_AZIMUTH_LEFT: ::std::os::raw::c_uint = 2;
@@ -6132,6 +6129,14 @@ pub mod root {
         }
         #[repr(u8)]
         #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
+        pub enum StyleStackSizing {
+            Ignore = 0,
+            StretchToFit = 1,
+            IgnoreHorizontal = 2,
+            IgnoreVertical = 3,
+        }
+        #[repr(u8)]
+        #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
         pub enum StyleTextJustify {
             None = 0,
             Auto = 1,
@@ -29986,7 +29993,7 @@ pub mod root {
         pub mBoxDirection: root::mozilla::StyleBoxDirection,
         pub mBoxOrient: root::mozilla::StyleBoxOrient,
         pub mBoxPack: root::mozilla::StyleBoxPack,
-        pub mStretchStack: bool,
+        pub mStackSizing: root::mozilla::StyleStackSizing,
     }
     #[test]
     fn bindgen_test_layout_nsStyleXUL() {
@@ -30025,10 +30032,10 @@ pub mod root {
                     "Alignment of field: " , stringify ! ( nsStyleXUL ) , "::"
                     , stringify ! ( mBoxPack ) ));
         assert_eq! (unsafe {
-                    & ( * ( 0 as * const nsStyleXUL ) ) . mStretchStack as *
+                    & ( * ( 0 as * const nsStyleXUL ) ) . mStackSizing as *
                     const _ as usize } , 12usize , concat ! (
                     "Alignment of field: " , stringify ! ( nsStyleXUL ) , "::"
-                    , stringify ! ( mStretchStack ) ));
+                    , stringify ! ( mStackSizing ) ));
     }
     #[repr(C)]
     #[derive(Debug)]
diff --git a/components/style/gecko/generated/structs_release.rs b/components/style/gecko/generated/structs_release.rs
index 381709f..fddeff8 100644
--- a/components/style/gecko/generated/structs_release.rs
+++ b/components/style/gecko/generated/structs_release.rs
@@ -185,9 +185,6 @@ pub mod root {
     pub const NS_FONT_SUB_SUPER_LARGE_SIZE: f64 = 45.;
     pub const NS_FONT_VARIANT_NORMAL: ::std::os::raw::c_uint = 0;
     pub const NS_FONT_VARIANT_SMALL_CAPS: ::std::os::raw::c_uint = 1;
-    pub const NS_STYLE_STACK_SIZING_IGNORE: ::std::os::raw::c_uint = 0;
-    pub const NS_STYLE_STACK_SIZING_STRETCH_TO_FIT: ::std::os::raw::c_uint =
-        1;
     pub const NS_STYLE_AZIMUTH_LEFT_SIDE: ::std::os::raw::c_uint = 0;
     pub const NS_STYLE_AZIMUTH_FAR_LEFT: ::std::os::raw::c_uint = 1;
     pub const NS_STYLE_AZIMUTH_LEFT: ::std::os::raw::c_uint = 2;
@@ -6005,6 +6002,14 @@ pub mod root {
         }
         #[repr(u8)]
         #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
+        pub enum StyleStackSizing {
+            Ignore = 0,
+            StretchToFit = 1,
+            IgnoreHorizontal = 2,
+            IgnoreVertical = 3,
+        }
+        #[repr(u8)]
+        #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
         pub enum StyleTextJustify {
             None = 0,
             Auto = 1,
@@ -29515,7 +29522,7 @@ pub mod root {
         pub mBoxDirection: root::mozilla::StyleBoxDirection,
         pub mBoxOrient: root::mozilla::StyleBoxOrient,
         pub mBoxPack: root::mozilla::StyleBoxPack,
-        pub mStretchStack: bool,
+        pub mStackSizing: root::mozilla::StyleStackSizing,
     }
     #[test]
     fn bindgen_test_layout_nsStyleXUL() {
@@ -29554,10 +29561,10 @@ pub mod root {
                     "Alignment of field: " , stringify ! ( nsStyleXUL ) , "::"
                     , stringify ! ( mBoxPack ) ));
         assert_eq! (unsafe {
-                    & ( * ( 0 as * const nsStyleXUL ) ) . mStretchStack as *
+                    & ( * ( 0 as * const nsStyleXUL ) ) . mStackSizing as *
                     const _ as usize } , 12usize , concat ! (
                     "Alignment of field: " , stringify ! ( nsStyleXUL ) , "::"
-                    , stringify ! ( mStretchStack ) ));
+                    , stringify ! ( mStackSizing ) ));
     }
     #[repr(C)]
     #[derive(Debug)]
```

**Comment by pamadini** [comment]
@jdm To create this new commit I used git commit --amend, pull, and then push. I'm not familiar with git so I don't really know if this is adding unnecessary history changes.

**Comment by Manishearth** [comment]
@bors-servo r+

builds for me

**Pull request merged**
