### PR TITLE
Upgrade to rustc 1.38.0-nightly (4b65a86eb 2019-07-15)

### PR DESCRIPTION
**Pull request by SimonSapin**
<del>This uses `MaybeUninit` in Stylo. `MaybeUninit` is stable in Rust 1.36.0, which Firefox [plans](https://wiki.mozilla.org/Rust_Update_Policy_for_Firefox) to require on 2019-06-18.</del>

Update: `MaybeUninit` in Stylo removed from this PR, after https://github.com/rust-lang/rust/pull/62599.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23726)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@emilio Does your sync script support ignoring a given set of commits, but still synchronizing the rest?

**Comment by SimonSapin** [comment]
`MaybeUninit` deprecation warnings were pushed back: https://github.com/rust-lang/rust/pull/62599, so this isn’t blocked anymore.

**Comment by paulrouget** [comment]
Is that Appveyor crash related?

**Comment by SimonSapin** [comment]
Let’s see if it happens on Taskcluster:

@bors-servo try

**Comment by jdm** [comment]
This hit on taskcluster on non-windows platforms too:
```
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: <unknown>
  48: <unknown>
  49: <unknown>
  50: <unknown>
  51: <unknown>
  52: <unknown>
  53: <unknown>
  54: <unknown>
  55: <unknown>
  56: <unknown>
query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.38.0-nightly (4b65a86eb 2019-07-15) running on x86_64-apple-darwin
note: compiler flags: -C debuginfo=2 -C ar=arm-linux-androideabi-ar -C linker=/Users/worker/tasks/task_1563282391/repo/./support/android/fakeld/fake-ld-armv7.sh -C target-feature=+neon --crate-type lib
note: some of the compiler flags provided by cargo are hidden
error: Could not compile `script`.
```

**Comment by jdm** [comment]
Also applies to desktop macOS.

**Comment by SimonSapin** [comment]
I’ve filed https://github.com/rust-lang/rust/issues/62717 and am now trying to narrow the regression range.

**Comment by SimonSapin** [comment]
The work-around suggested by eddyb works on my laptop.

@bors-servo try

**Comment by jdm** [comment]
I am really intrigued that that test appears to be passing consistently with a rust upgrade.

**Comment by SimonSapin** [comment]
All build tasks succeeded on Taskcluster: https://tools.taskcluster.net/groups/GTw_o2HPTce6j-9SavSF2g

**Comment by jdm** [comment]
The test passed on mac as well as linux, which is quite convincing.

**Comment by emilio** [comment]
@jdm that test is quite new, and is what the cssparser upgrade fixes.

**Comment by emilio** [comment]
In particular, https://github.com/servo/rust-cssparser/pull/251 fixes that, and https://phabricator.services.mozilla.com/D37148 added that test to wpt.

**Comment by SimonSapin** [comment]
Updated the test expectation.

**Comment by paulrouget** [comment]
@emilio r? or @jdm r?

**Review by emilio — APPROVED** [review]
r=me

**Pull request merged**
