### PR TITLE
Add missing XRWebGLBinding constructor steps

### LINKED ISSUE #33682: XRWebGLBinding constructor is missing steps
Specification: https://immersive-web.github.io/layers/#dom-xrwebglbinding-xrwebglbinding
Code: https://github.com/servo/servo/blob/05ecb8eddb3989ffcee51df5c2c86887fee8b7e8/components/script/dom/xrwebglbinding.rs#L64

Test; https://github.com/servo/servo/blob/main/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
Current failures: https://github.com/servo/servo/blob/main/tests/wpt/meta/webxr/layers/xrWebGLBinding_constructor.https.html.ini

Useful reference code: https://github.com/servo/servo/blob/05ecb8eddb3989ffcee51df5c2c86887fee8b7e8/components/script/dom/xrwebgllayer.rs#L107

### PR DESCRIPTION
**Pull request by Taym95**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #33682

- [ ] There are tests for these changes OR

### CODE REVIEW

**Comment by jdm** [comment]
@Taym95 did you try running the test locally to verify if any behavior changed?

**Comment by Taym95** [comment]
> @Taym95 did you try running the test locally to verify if any behavior changed?

Yes I did, no behavior changed test still failing, I am trying to see why.

image

```
 0:27.85 TEST_END: TIMEOUT, expected OK - TestRunner hit external timeout (this may indicate a hang)
 ```

**Comment by jdm** [comment]
@msub2 I see the document.body error appearing in the output. I thought you fixed that?

**Comment by msub2** [comment]
Yeah, I believe there's one test still affected by that but I haven't been able to debug yet

**Comment by jdm** [comment]
@Taym95 The following diff addresses the promise rejection error in those tests:
```diff
diff --git a/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html b/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
index b3457cf320..18b7576812 100644
--- a/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
+++ b/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
@@ -74,10 +74,11 @@ function testConstructor(t, gl) {
       });
     });
 }
-xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl",
-  testConstructor, null, 'webgl');
-
-xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl2",
-  testConstructor, null, 'webgl2');
+document.addEventListener('DOMContentLoaded', () => {
+  xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl",
+    testConstructor, null, 'webgl');

+  xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl2",
+    testConstructor, null, 'webgl2');
+});
 </script>
```

**Comment by jdm** [comment]
Oh, we need to enable the `dom.webxr.layers.enabled` pref for the webxr tests as well: https://github.com/servo/servo/blob/main/tests/wpt/meta/webxr/__dir__.ini

**Comment by jdm** [comment]
> @Taym95 The following diff addresses the promise rejection error in those tests:
> 
> ```diff
> diff --git a/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html b/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
> index b3457cf320..18b7576812 100644
> --- a/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
> +++ b/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
> @@ -74,10 +74,11 @@ function testConstructor(t, gl) {
>        });
>      });
>  }
> -xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl",
> -  testConstructor, null, 'webgl');
> -
> -xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl2",
> -  testConstructor, null, 'webgl2');
> +document.addEventListener('DOMContentLoaded', () => {
> +  xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl",
> +    testConstructor, null, 'webgl');
> 
> +  xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl2",
> +    testConstructor, null, 'webgl2');
> +});
>  </script>
> ```

This will also be addressed by #33715.

**Comment by Taym95** [comment]
> > @Taym95 The following diff addresses the promise rejection error in those tests:
> > ```diff
> > diff --git a/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html b/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
> > index b3457cf320..18b7576812 100644
> > --- a/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
> > +++ b/tests/wpt/tests/webxr/layers/xrWebGLBinding_constructor.https.html
> > @@ -74,10 +74,11 @@ function testConstructor(t, gl) {
> >        });
> >      });
> >  }
> > -xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl",
> > -  testConstructor, null, 'webgl');
> > -
> > -xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl2",
> > -  testConstructor, null, 'webgl2');
> > +document.addEventListener('DOMContentLoaded', () => {
> > +  xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl",
> > +    testConstructor, null, 'webgl');
> > 
> > +  xr_promise_test("Ensure that XRWebGLBinding's constructor throws appropriate errors using webgl2",
> > +    testConstructor, null, 'webgl2');
> > +});
> >  </script>
> > ```
> 
> This will also be addressed by #33715.

I will use your patch and update this PR.

**Comment by Taym95** [comment]
I will close this one and create one based on you PR.

**Pull request closed without merging**
