### PR TITLE
Enable xmlhttprequest-timeout-worker-twice.html (fixes #4041)

### LINKED ISSUE #4041: xmlhttprequest-timeout-worker-twice.html is unstable
Failed in <http://build.servo.org/builders/linux2/builds/16/steps/shell/logs/stdio>; is already partially disabled.

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9133)

### CODE REVIEW

**Comment by nox** [comment]
@jdm Our XHR code changed a lot, shouldn't we enable this again?

**Comment by KiChjang** [comment]
@bors-servo retry
* #8769

**Comment by KiChjang** [comment]
```
Ran 3764 tests finished in 214.0 seconds.
  • 3763 ran as expected. 706 tests skipped.
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /_mozilla/mozilla/mime_sniffing_font_context.html:
  │ FAIL [expected PASS] Sniffed font is loaded and applied
  │   → assert_not_equals: got disallowed value 14
  │ 
  │ checkFontLoaded@http://web-platform.test:8000/_mozilla/mozilla/mime_sniffing_font_context.html:38:1
  │ Test.prototype.step_timeout/<@http://web-platform.test:8000/resources/testharness.js:1439:20
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1405:1
```
What is this?

**Pull request merged**
