### PR TITLE
Make Request throw less often (fixes #13457)

### LINKED ISSUE #13457: Make Request throw less often
https://github.com/whatwg/fetch/pull/377

### PR DESCRIPTION
**Pull request by mathieuh**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13457 

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13561)

### CODE REVIEW

**Comment by jdm** [comment]
I filed #13563 for the failure reported here. The real failures are these:
```
  ▶ Unexpected subtest result in /fetch/api/policies/referrer-origin.html:
  │ FAIL [expected PASS] Throw a TypeError referrer is not same-origin with origin
  └   → assert_unreached: Should have rejected: undefined Reached unreachable code

  ▶ Unexpected subtest result in /fetch/api/policies/referrer-origin-worker.html:
  │ FAIL [expected PASS] Throw a TypeError referrer is not same-origin with origin
  └   → assert_unreached: Should have rejected: undefined Reached unreachable code

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's referrer has invalid origin
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"referrer" : "http://test.url"}); }" did not throw
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:28:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1401:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:27:7
```
That may not be all of the affected tests either; those are only the ones that we were previously passing and now fail.

**Comment by KiChjang** [comment]
What's the status of this?

**Comment by jdm** [comment]
Changes are unreviewed, and tests need investigating.

**Comment by mathieuh** [comment]
@KiChjang @jdm Sorry guys, was a bit busy lately, I'll come back on it as soon as I can.

**Comment by jdm** [comment]
@ConnorGBrewster If there are PRs that you're assigned to that you don't want/intend to review, please reassign them!

**Comment by ConnorGBrewster** [comment]
@jdm @mathieuh sorry about the delay! This looks good to me, do these tests need changed to match the new behavior defined in the spec?

**Comment by jdm** [comment]
Yes, we need to make sure that tests under fetch/ reflect the spec changes, since they haven't been updated yet as far as I know.

**Comment by ConnorGBrewster** [comment]
@mathieuh are you planning on finishing the work on this PR? Let me know if you need any help

**Comment by mathieuh** [comment]
@ConnorGBrewster Yes I will, I tried but didn't succeed and asked @nox for help already.

**Comment by nox** [comment]
@jdm I wonder if this patch isn't a bit premature, given the non-throwing test in `/fetch/api/policies/referrer-origin.html` doesn't even pass. How do you want the tests to be updated? Should we just check that no TypeError is thrown and nothing more?

**Comment by jdm** [comment]
I've submitted https://github.com/w3c/web-platform-tests/pull/4341 to update the tests. We should merge these changes after we sync our tests with upstream after it's landed.

**Comment by jdm** [comment]
Now that https://github.com/w3c/web-platform-tests/pull/4341 has merged, we are only waiting on syncing our version of the tests with the upstream ones.

**Comment by jdm** [comment]
This is waiting on #15405.

**Comment by jdm** [comment]
This is impacted by #14507 which is why the referrer origin tests don't pass after this change.

**Comment by KiChjang** [comment]
@bors-servo retry
* #15713

**Comment by KiChjang** [comment]
@bors-servo retry
* #14323

**Pull request merged**
