### PR TITLE
style: Add support for -moz-font-smoothing-background-color.

### PR DESCRIPTION
**Pull request by heycam**
From https://bugzilla.mozilla.org/show_bug.cgi?id=1399834 and reviewed there by Xidorn.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18623)

### CODE REVIEW

**Comment by upsuper** [comment]
`SchedulerGroup` is going to be blacklisted in [bug 1373878](https://bugzilla.mozilla.org/show_bug.cgi?id=1373878), and `ImageValue` is the issue I mentioned in [bug 1400100 comment 8](https://bugzilla.mozilla.org/show_bug.cgi?id=1400100#c8), which I suggested to back out. @nnethercote

**Comment by upsuper** [comment]
If Rust code doesn't need to access internal of `ImageValue`, we can probably blacklist that type as well (treat as opaque).

**Comment by heycam** [comment]
Oh, didn't see your comments here before writing my patch in bug 1403073.  We do need to be able to poke at ImageValues (well, at least at their URLValueData members).

**Pull request merged**
