### PR TITLE
Test for flexbox crasher

### LINKED ISSUE #7316: Flexbox: thread 'LayoutWorker worker 3/3' panicked at 'attempted to divide by zero'
```html
<style>
  div {
    display: flex;
    flex-grow: 1;
  }
</style>

<div>
  <div>
  </div>
</div>
```

```
thread 'LayoutWorker worker 3/3' panicked at 'attempted to divide by zero', /components/util/geometry.rs:169
```

### LINKED ISSUE #7332: Add a test for #7316.
CC @paulrouget

### PR DESCRIPTION
**Pull request by paulrouget**
Closes #7332

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7388)

### CODE REVIEW

**Comment by paulrouget** [comment]
This test will still pass without the crasher fix (#7388) because we don't run the tests with the `-e` flag.

Can we still land this? Or should we still try to find a solution for #7335? Or we just don't write test for experimental features?

**Comment by jdm** [comment]
Once we get an update of wptrunner that includes https://github.com/w3c/wptrunner/pull/141 this can land with changes like https://github.com/jdm/servo/commit/447b5b560c05ee19175523cc5d9184c6f4a4503c .

**Comment by Ms2ger** [comment]
@paulrouget prefs work now: https://github.com/jdm/servo/blob/cssprefs3/tests/wpt/metadata-css/css-flexbox-1_dev/__dir__.ini

**Comment by paulrouget** [comment]
Took me for ever to understand that the `__dir__.ini` should go into the meta directory, not directly in the test directory.

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7388)

**Pull request merged**
