### PR TITLE
Better deduplication for script::dom::attr::AttrValue

### PR DESCRIPTION
**Pull request by frewsxcv**
The current behavior of `AttrValue::from_serialized_tokenlist`
deduplicates tokens that were passed in as the parameter `AttrValue`.

The current deduplication algorithm loops through an entire
Vec for each iteration of the duplicate check loop check; this is O(N^2).

This commit changes the algorithm to utilize an intermediate BTreeSet to
check for duplicates; this is O(NlogN).

### CODE REVIEW

**Comment by frewsxcv** [comment]
If we don't need to retain order of the tokens, I can switch the `Set` to a `HashSet`

**Comment by Ms2ger** [comment]
Did you profile this? It seems like the constant costs of allocating the set would likely outweigh the wins of the improved algorithm in typical workloads.

**Comment by metajack** [comment]
Assigning @glennw. @jdm removed awaiting review, but appears no review is in Critic yet.

**Comment by frewsxcv** [comment]
> Did you profile this? It seems like the constant costs of allocating the set would likely outweigh the wins of the improved algorithm in typical workloads.

I haven't profiled it though I suppose I could if I ever get around to learning how to profile thingamajigs with Rust

**Comment by Ms2ger** [comment]
Anyone object to wontfixing this for now?

**Comment by frewsxcv** [comment]
SGTM

**Pull request closed without merging**
