### PR TITLE
layout: Simplify and improve the correctness of whitespace stripping in text layout, and unify the inline layout paths for pre- and normally-formatted text.

### LINKED ISSUE #2260: Remove Box::new_line_pos
It's pretty inefficient and I don't think it's necessary.

### PR DESCRIPTION
**Pull request by pcwalton**
This fixes a lot of "jumpiness" and removes the `new_line_pos` stuff.

Closes #2260.

r? @mbrubeck
cc @metajack

### CODE REVIEW

**Comment by narfg** [comment]
Great work! I could not look at the code in detail but I can confirm that this fixes #3882, #5203 and #5368.

**Comment by mbrubeck** [comment]
One minor note on Critic; r=mbrubeck with that addressed (no re-r? needed).

**Comment by mbrubeck** [comment]
```
 5:24.62 TEST_END: Thread-TestrunnerManager-7 FAIL, expected PASS
/html/dom/elements/global-attributes/dir_auto-pre-N-EN.html 5c9717c0a02a2695fec12a2014716bd6a5c8e288
/html/dom/elements/global-attributes/dir_auto-pre-N-EN-ref.html 339e7007c81ada084e0d18284e0961b4f1f760da
Testing 5c9717c0a02a2695fec12a2014716bd6a5c8e288 == 339e7007c81ada084e0d18284e0961b4f1f760da
```

**Comment by mbrubeck** [comment]
r+, needs squash

**Comment by pcwalton** [comment]
r=mbrubeck

**Comment by metajack** [comment]
```
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:23:9: 23:78 error: this function takes 4 parameters but 5 parameters were supplied [E0061]
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:23         transform_text(test, mode, true, &mut trimmed_str, &mut new_line_pos);
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:57:9: 57:78 error: this function takes 4 parameters but 5 parameters were supplied [E0061]
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:57         transform_text(test, mode, true, &mut trimmed_str, &mut new_line_pos);
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:91:9: 91:78 error: this function takes 4 parameters but 5 parameters were supplied [E0061]
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:91         transform_text(test, mode, true, &mut trimmed_str, &mut new_line_pos);
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:125:9: 125:78 error: this function takes 4 parameters but 5 parameters were supplied [E0061]
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:125         transform_text(test, mode, true, &mut trimmed_str, &mut new_line_pos);
                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:162:9: 162:79 error: this function takes 4 parameters but 5 parameters were supplied [E0061]
/home/servo/buildbot/slave/linux1/build/tests/unit/gfx/text_util.rs:162         transform_text(test, mode, false, &mut trimmed_str, &mut new_line_pos);
                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 5 previous errors
```

**Pull request merged**
