### PR TITLE
Add support for most of the border-image properties, pass to WR.

### PR DESCRIPTION
**Pull request by glennw**
This adds support for:
 * border-image (images, not gradients yet)
 * border-image-source
 * border-image-slice
 * border-image-repeat (stretch + repeat only for now)

Remaining work:
 * Connect border-image-outset (WR supports this).
 * border-image-width

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15697)

### CODE REVIEW

**Comment by jdm** [comment]
If this could wait for #14962 to merge I would appreciate it.

**Comment by jdm** [comment]
Mako and WebIDL changes look fine.

**Comment by glennw** [comment]
@jdm Yup, no problem waiting on that PR to land first :)

**Comment by glennw** [comment]
@pcwalton OK, #14962  has landed now, so this is ready for review. Also rebased and fixed the tidy error.

**Comment by pcwalton** [comment]
Looks good to me.

**Comment by jdm** [comment]
@bors-servo: retry
* #14323

**Pull request merged**
