### PR TITLE
Combine Page into BrowsingContext

### LINKED ISSUE #11031: Replace Page with BrowsingContext
As far as I know their purpose is identical. Page is our own wishy-washy concept, it's an `Rc<T>` that contains JS-owned data (dangerous!), and it basically delegates to the browsing context anyways.
#5236

### PR DESCRIPTION
**Pull request by cbrewster**
Fixes #11031.

`Page` and `BrowsingContext` have similar use cases and we decided it would be best to join the two.

This is the ground work for actually using session history in the `BrowsingContext` to implement the History API.

r? @jdm

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11044)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@bors-servo try
 * git

**Comment by ConnorGBrewster** [comment]
These test failures seem to be intermittent on my local machine, I am not sure if these are due to my changes or due to the same thing that is causing #11059.

**Comment by jdm** [comment]
If they happen on your local machine, they are likely independent of #11059 and triggered by these changes.

**Comment by ConnorGBrewster** [comment]
@jdm alright, time to do some more digging then!

**Comment by ConnorGBrewster** [comment]
Sometimes when closing the window with `esc` Servo crashes, I believe that is what is making these tests fail. I am not sure what is causing the panic and no back trace is printed.

**Comment by jdm** [comment]
You can use `./mach run --debug` and set a breakpoint on `rust_panic` to help figure out what the backtrace is.

**Comment by ConnorGBrewster** [comment]
@jdm got the bt, and have gone through it. It looks like a non dom object is being sent to `get_dom_class` and then the Result is unwrapped causing a crash. I can't quite peg why this is happening.

```
* thread #20: tid = 0xc336, 0x0000000103396210 servo`rust_panic, stop reason = breakpoint 1.1
  * frame #0: 0x0000000103396210 servo`rust_panic
    frame #1: 0x000000010338ba53 servo`std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25 + 467
    frame #2: 0x000000010338d2ff servo`std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523 + 207
    frame #3: 0x000000010339d4e8 servo`rust_begin_unwind + 56
    frame #4: 0x00000001033cb8a1 servo`core::panicking::panic_fmt::h257ceb0aa351d801 + 129
    frame #5: 0x000000010142e40d servo`core::result::unwrap_failed::he3b8abcf572ca45e + 285 at macros.rs:29
    frame #6: 0x000000010143e7ca servo`_$LT$core..result..Result$LT$T$C$$u20$E$GT$$GT$::unwrap::had477e28babc07bc + 74 at result.rs:723
    frame #7: 0x000000010143e762 servo`script::dom::bindings::inheritance::Castable::is::h64c4cf0d1e00d5bd + 98 at inheritance.rs:21
    frame #8: 0x0000000101abb080 servo`_$LT$dom..bindings..js..Root$LT$T$GT$$GT$::downcast::h87fce2c1d7e567d4 + 80 at js.rs:559
    frame #9: 0x0000000101b90ecb servo`fn$LP$dom..bindings..js..Root$LT$dom..node..Node$GT$$RP$$u20$.$GT$$u20$core..option..Option$LT$dom..bindings..js..Root$LT$dom..element..Element$GT$$GT$::fn_pointer_shim.151690::h1598e1d715179446 + 27
    frame #10: 0x0000000101b90ce1 servo`_$LT$core..iter..FilterMap$LT$I$C$$u20$F$GT$$u20$as$u20$core..iter..Iterator$GT$::next::h768f032cf5d10d39 + 257 at mod.rs:860
    frame #11: 0x0000000101b9096f servo`_$LT$core..iter..Peekable$LT$I$GT$$u20$as$u20$core..iter..Iterator$GT$::next::hc6c0c6ecfa02cb69 + 95 at mod.rs:989
    frame #12: 0x0000000101439266 servo`_$LT$dom..document..Document$u20$as$u20$dom..bindings..codegen..Bindings..DocumentBinding..DocumentMethods$GT$::GetDocumentElement::hfd81200690eef970 + 70 at document.rs:1977
    frame #13: 0x0000000101b3862d servo`script::dom::document::Document::needs_reflow::haa6a98baf8974c67 + 45 at document.rs:372
    frame #14: 0x0000000101b3dac4 servo`script::dom::window::Window::reflow::h2c7a252e1f089941 + 292 at window.rs:1066
    frame #15: 0x0000000101f7e264 servo`script::script_thread::ScriptThread::handle_msgs::haacc9a2f304fe228 + 8452 at script_thread.rs:795
    frame #16: 0x0000000101f2157d servo`script::script_thread::ScriptThread::start::h5f466082d5fe1984 + 29 at script_thread.rs:614
    frame #17: 0x0000000101f21421 servo`_$LT$script_thread..ScriptThread$u20$as$u20$script_traits..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hb2a66ce329461d65 + 49 at script_thread.rs:466
    frame #18: 0x0000000101f21162 servo`profile_traits::mem::ProfilerChan::run_with_memory_reporting::hdef428405c77bd6c + 674 at mem.rs:59
    frame #19: 0x0000000101f0e5ba servo`_$LT$script_thread..ScriptThread$u20$as$u20$script_traits..ScriptThreadFactory$GT$::create::_$u7b$$u7b$closure$u7d$$u7d$::h376836bb503682b7 + 1882 at script_thread.rs:465
    frame #20: 0x0000000101f0af13 servo`util::thread::spawn_named_with_send_on_panic::_$u7b$$u7b$closure$u7d$$u7d$::heb59eb3e917c5b06 + 563
    frame #21: 0x0000000101f0a734 servo`std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h5451e0f5cc8da44b + 116
    frame #22: 0x0000000101f0a6a9 servo`std::sys_common::unwind::try::try_fn::hca2f304c46ad6472 + 73 at mod.rs:127
    frame #23: 0x000000010339d47c servo`__rust_try + 12
    frame #24: 0x000000010339d404 servo`std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd + 116
    frame #25: 0x0000000101f0a5e6 servo`std::sys_common::unwind::try::h9b69ed8320487131 + 150 at mod.rs:123
    frame #26: 0x0000000101f0a412 servo`std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h718fa5631ce7ed57 + 434
    frame #27: 0x0000000101f0b108 servo`_$LT$F$u20$as$u20$std..boxed..FnBox$LT$A$GT$$GT$::call_box::hf74656283ae82dd3 + 104 at boxed.rs:541
    frame #28: 0x00000001033a3579 servo`std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b + 57
    frame #29: 0x00007fff9002f99d libsystem_pthread.dylib`_pthread_body + 131
    frame #30: 0x00007fff9002f91a libsystem_pthread.dylib`_pthread_start + 168
    frame #31: 0x00007fff9002d351 libsystem_pthread.dylib`thread_start + 13
```

**Comment by jdm** [comment]
@ConnorGBrewster I suspect that this is caused by shutting down a pipeline (via `handle_exit_pipeline`) which could end up shutting down the JS runtime and then attempting to reflow the page.

**Comment by jdm** [comment]
Specifically, I bet that https://github.com/servo/servo/pull/11044/files#diff-1879ac6bd5d567e2aa43529d33474677R2002 is no longer true.

**Comment by ConnorGBrewster** [comment]
@jdm hmm any ideas on what would fix this. Right now it clears the session history, does this not do the same thing as setting frame to `None` did before?

**Comment by jdm** [comment]
Re: the last question, `clear_session_history` doesn't clear out the `frame_element` or `children` fields, so there are possibly still connections to the DOM hanging around.

**Comment by ConnorGBrewster** [comment]
@jdm I tried having that clear the session history, frame element, and children. It still panics with the same bt.

**Comment by jdm** [comment]
Update: RUST_LOG=script::dom::bindings::codegen has confirmed my theory that all the JS objects are being GCed by the `self.GC()` in `shut_down_layout`, which is obviously unexpected. The only reason that we don't hit this problem in the case where the root shuts down first is that it exits the event loop after cleaning up, so the code that tries to reflow the page never gets a chance to run.

**Comment by ConnorGBrewster** [comment]
@jdm I cherry-picked my commits on top of e1386cad6fdfd0776f65da6a0ff7a0a8563df667. It still has the issue of the GC freeing everything.

**Comment by ConnorGBrewster** [comment]
Could it be that the only place the document is stored inside a `SessionHistoryEntry` in a `Vec`?

**Comment by jdm** [comment]
I tried adding a document field to `BrowsingContext` and there was no change.

**Comment by ConnorGBrewster** [comment]
@jdm I have done that aswell as adding a window field, could it be how it is stored in the `ScriptThread` that the `BrowsingContext` itself isn't being traced? Also does everything in `BrowsingContext::new` look correct? I don't know enough to know if its correct.

**Comment by jdm** [comment]
Figured it out! I'm going to make a separate pull request that this can be rebased on top of.

**Comment by ConnorGBrewster** [comment]
@jdm :tada: Thanks for looking into that! I really appreciate the help!

**Comment by ConnorGBrewster** [comment]
This should now be ready for review.

**Comment by jdm** [comment]
This is great! I'm so please to see Page totally gone :)
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.</details>


---

Reviewed 9 of 9 files at r1, 14 of 14 files at r2, 12 of 12 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 2 of 2 files at r8, 3 of 3 files at r9, 18 of 18 files at r10, 13 of 13 files at r11, 3 of 3 files at r12, 3 of 3 files at r13.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/script_thread.rs, line 627 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWE2nhzZY1H6Z1Vo1U:-KHWE2nhzZY1H6Z1Vo1V:-1314245829) ([raw file](https://github.com/servo/servo/blob/a4ba34d482f807525a7eb0c13e63d951f51d6239/components/script/script_thread.rs#L627)):*
> ```Rust
>         let mut resizes = vec!();
> 
>         {
> ```

We can get rid of the extra scope now that there's no borrowing.

---

*[components/script/script_thread.rs, line 1398 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWG0KfYr8_RNZHAaz_:-KHWG0KfYr8_RNZHAaza:-1043009008) ([raw file](https://github.com/servo/servo/blob/a4ba34d482f807525a7eb0c13e63d951f51d6239/components/script/script_thread.rs#L1398)):*
> ```Rust
>             chan.send(ConstellationMsg::SetFinalUrl(incomplete.pipeline_id, final_url.clone())).unwrap();
>         }
>         debug!("ScriptThread: loading {} on context {:?}", incomplete.url, incomplete.pipeline_id);
> ```

I think `pipeline` would make more sense here.

---

*[components/script/dom/browsingcontext.rs, line 190 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWJDF4oJQ7r7CBGgCP:-KHWJDF5qd_Kkz1fIOUM:2116561728) ([raw file](https://github.com/servo/servo/blob/a4ba34d482f807525a7eb0c13e63d951f51d6239/components/script/dom/browsingcontext.rs#L190)):*
> ```Rust
>             self.stack.extend(context.children.borrow()
>                                               .iter()
>                                               .cloned()
> ```

Why is this cloned necessary?

---

*[components/script/dom/browsingcontext.rs, line 104 \[r10\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWMHlnJ2PbjQy7ch26:-KHWMHloj5BpWAcPU_YX:-831033652) ([raw file](https://github.com/servo/servo/blob/117e0ed342f59a355b3e7c31c30820b0730eb4bc/components/script/dom/browsingcontext.rs#L104)):*
> ```Rust
>         history.push(SessionHistoryEntry::new(document, document.url().clone(), document.Title()));
>         self.active_index.set(self.active_index.get() + 1);
>     }
> ```

Let's add `assert_eq!(self.active_index.get(), history.len() - 1)`.

---

*[components/script/dom/browsingcontext.rs, line 130 \[r10\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWLcckGOg490yNpdSq:-KHWLcckGOg490yNpdSr:2057760984) ([raw file](https://github.com/servo/servo/blob/117e0ed342f59a355b3e7c31c30820b0730eb4bc/components/script/dom/browsingcontext.rs#L130)):*
> ```Rust
>                              .position(|context| context.id == id);
>         match remove_idx {
>             Some(idx) => Some(Root::from_ref(&*self.children.borrow_mut().remove(idx))),
> ```

Is the Root::from_ref even necessary here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11044#-:-KHWNVV-GWZsiap5a_6X:-731519656)*

**Comment by ConnorGBrewster** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/script_thread.rs, line 627 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWE2nhzZY1H6Z1Vo1U:-KHWaS8L5YXtuSr6suc7:-499146009) ([raw file](https://github.com/servo/servo/blob/a4ba34d482f807525a7eb0c13e63d951f51d6239/components/script/script_thread.rs#L627)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> We can get rid of the extra scope now that there's no borrowing.</details>
Done.

---

*[components/script/script_thread.rs, line 1398 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWG0KfYr8_RNZHAaz_:-KHWaRtx-c8C9MeTJuNb:-499146009) ([raw file](https://github.com/servo/servo/blob/a4ba34d482f807525a7eb0c13e63d951f51d6239/components/script/script_thread.rs#L1398)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> I think `pipeline` would make more sense here.</details>
Done.

---

*[components/script/dom/browsingcontext.rs, line 190 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWJDF4oJQ7r7CBGgCP:-KHWaQvJ_Z0Ow7wsKvu6:-499146009) ([raw file](https://github.com/servo/servo/blob/a4ba34d482f807525a7eb0c13e63d951f51d6239/components/script/dom/browsingcontext.rs#L190)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Why is this cloned necessary?</details>
Done.

---

*[components/script/dom/browsingcontext.rs, line 104 \[r10\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWMHlnJ2PbjQy7ch26:-KHWaRVI6__VErHYuEOc:-499146009) ([raw file](https://github.com/servo/servo/blob/117e0ed342f59a355b3e7c31c30820b0730eb4bc/components/script/dom/browsingcontext.rs#L104)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Let's add `assert_eq!(self.active_index.get(), history.len() - 1)`.</details>
Done.

---

*[components/script/dom/browsingcontext.rs, line 130 \[r10\]](https://reviewable.io:443/reviews/servo/servo/11044#-KHWLcckGOg490yNpdSq:-KHWaASRZWYlvqcrm738:1721510847) ([raw file](https://github.com/servo/servo/blob/117e0ed342f59a355b3e7c31c30820b0730eb4bc/components/script/dom/browsingcontext.rs#L130)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Is the Root::from_ref even necessary here?</details>
The `Vec` stores `JS<BrowsingContext>` and the function returns a `Option<Root<BrowsingContext>>`. I have that to change the `JS` to `Root`. Is that ok? or is there a better way to handle this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11044)*

**Comment by jdm** [comment]
@bors-servo: r+
Yay!

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.</details>


---

Reviewed 2 of 2 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11044#-:-KHWmIURJFJLIVh6Wy-m:-1396490138)*

**Pull request merged**
