### PR TITLE
History interface Go, Back, and Forward

### LINKED ISSUE #5670: Implement History's back/forward APIs
Spec: https://html.spec.whatwg.org/multipage/browsers.html#the-history-interface, https://html.spec.whatwg.org/multipage/browsers.html#dom-history-back, 
Code: https://github.com/servo/servo/wiki/Adding-a-new-WebIDL-binding

This will just end up mimicing the behaviour of the GoForward/GoBack APIs of HTMLIFrameElement (see components/script/dom/element/htmliframelement.rs)

### PR DESCRIPTION
**Pull request by cbrewster**
r? @asajeffrey 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #5670 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

implement go, forward, back

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12552)

### CODE REVIEW

**Comment by asajeffrey** [comment]
```

Tests with unexpected results:
  ▶ Unexpected subtest result in /html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin.html:
  │ FAIL [expected PASS] Restoring window.name on cross-origin history traversal
  │   → f.contentWindow is null
  │ 
  │ steps<@http://web-platform.test:8000/html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin.html:13:17
  │ steps</<@http://web-platform.test:8000/html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin.html:25:72
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1426:20
  │ next<@http://web-platform.test:8000/html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin.html:28:32
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  └ Test.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1426:20

  ▶ Unexpected subtest result in /html/browsers/history/the-location-interface/location_assign_about_blank.html:
  └ PASS [expected FAIL] location.assign with initial about:blank browsing context

  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface History to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:70:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:1:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:6:1

  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.worker:
  │ FAIL [expected PASS] Untitled
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface History to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:71:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1403:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.worker.js:9:1
```
The first fail is the interesting one, the second is good news. The other two are just reminding us to get @jdm or @Ms2ger to bless this PR.

**Comment by ConnorGBrewster** [comment]
Updated test expectations

**Comment by asajeffrey** [comment]
Reviewed 13 of 14 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/webidls/History.webidl, line 10 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12552#-KNIGL0mw6wjgPCr19bQ:-KNIGL0mw6wjgPCr19bR:-2040145258) ([raw file](https://github.com/servo/servo/blob/7273f24c9e866f5b651d488c86a5c00c3d6e0a0b/components/script/dom/webidls/History.webidl#L10)):*
> ```WebIDL
> [Exposed=(Window,Worker)]
> interface History {
>   // readonly attribute unsigned long length;
> ```

It would be nice to support length at some point, not necessarily this PR though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12552)*

**Comment by asajeffrey** [comment]
LGTM, we need @jdm or @Ms2ger to bless it, then you can r=me.

**Comment by jdm** [comment]
History does not belong in worker scopes and shouldn't have any Exposed annotation.

**Comment by asajeffrey** [comment]
IRC conversation: http://logs.glob.uno/?c=mozilla%23servo&s=22+Jul+2016&e=22+Jul+2016#c486162

**Comment by asajeffrey** [comment]
@jdm blesses http://logs.glob.uno/?c=mozilla%23servo&s=22+Jul+2016&e=22+Jul+2016#c486278 so @bors-servo r+

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #12561

**Comment by asajeffrey** [comment]
Oh how ironic, this test is now intermittent, most likely due to the race condition between f.onload and the setTimeout.

**Comment by ConnorGBrewster** [comment]
@asajeffrey sigh.. I wonder if there is a way we can make this pass in both Gecko and Servo regardless of the onload issue

**Comment by ConnorGBrewster** [comment]
Would it be ok to change: https://github.com/ConnorGBrewster/servo/blob/master/tests/wpt/web-platform-tests/html/browsers/browsing-the-web/history-traversal/browsing_context_name_cross_origin.html#L40
```
onload = setTimeout(next, 0);
```
to
```
next;
```
That makes it pass in Servo(as the onload callback is not called for `about:blank`) and I assume Gecko as well.

**Comment by ConnorGBrewster** [comment]
Disabling `browsing_context_name_cross_origin.html` until we can get a fix for it.

**Comment by emilio** [comment]
https://github.com/servo/servo/pull/12563 makes some changes to onload to make it more consistent, would be nice to see if those changes fix any of the races you see here.

**Comment by ConnorGBrewster** [comment]
@emilio I tested locally and haven't hit any intermittent failures! 🎉 I will leave those issues open for a bit to make sure. Thanks!

**Pull request merged**
