### PR TITLE
Extract Response from net_traits/lib.rs

### PR DESCRIPTION
**Pull request by KiChjang**
This puts them in a new file located at `net_traits/response.rs`.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9165)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Add a newline to the end of the new file, and a module-level documentation comment that explains what the scope of this new module is.

**Comment by KiChjang** [comment]
Done.

**Comment by KiChjang** [comment]
@nikkisquared be careful of where you locate the `Response` object now

**Comment by KiChjang** [comment]
Grrrrrr

**Comment by KiChjang** [comment]
@bors-servo retry
* #9124

**Pull request merged**
