### PR TITLE
Extend WebBluetooth with discovery session and dialog

### PR DESCRIPTION
**Pull request by dati91**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because the there are no webbluetooth tests ye.

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11269)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, Wafflespeanut (Ravi Shankar) wrote…</i></summary>
> r? @jdm
</details>


---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/net/bluetooth_thread.rs, line 32 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11269#-KIe07363CHSz2oY9sny:-KIe0737vNAgYfDS6X5E:1173733888) ([raw file](https://github.com/servo/servo/blob/6f214bd00d044cb50acb78fb531f76d1865998f6/components/net/bluetooth_thread.rs#L32)):*
> ```Rust
> const VALUE_ERROR: &'static str = "No characteristic or descriptor found with that id";
> // The discovery session needs some time to find any nearby devices
> const DISCOVERY_TIMEOUT: u64 = 1500;
> ```

Let's call this DISCOVERY_TIMEOUT_MS for clarity.

---

*[components/net/bluetooth_thread.rs, line 382 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11269#-KIe0PE8-Cw0TaVhRz4l:-KIe0PE9YdceHT6SJpbd:804438607) ([raw file](https://github.com/servo/servo/blob/6f214bd00d044cb50acb78fb531f76d1865998f6/components/net/bluetooth_thread.rs#L382)):*
> ```Rust
>                                      rssi: device.get_rssi().ok().map(|p| p as i8),
>                                  });
>                 session.map(|ref s| s.stop_discovery());
> ```

Let's use `if let`.

---

*[components/net/bluetooth_thread.rs, line 386 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11269#-KIe0b-r9-p0eSL_dQeF:-KIe0b-r9-p0eSL_dQeG:1817732912) ([raw file](https://github.com/servo/servo/blob/6f214bd00d044cb50acb78fb531f76d1865998f6/components/net/bluetooth_thread.rs#L386)):*
> ```Rust
>             }
>         }
>         session.map(|ref s| s.stop_discovery());
> ```

Could we avoid the duplication by calling `stop_discovery` before the `for`?

---

*[components/net/bluetooth_thread.rs, line 236 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11269#-KIe1IZluUqOhmNDKDmO:-KIe1IZm0d3Bm-8tQvYM:2022732030) ([raw file](https://github.com/servo/servo/blob/c46fb590dceb818bf735d6fa5102c167ca1c919f/components/net/bluetooth_thread.rs#L236)):*
> ```Rust
>             // The device string format will be "Address|Name".
>             // We need the first part, therefore we reverse the split and use the last item.
>             return device.rsplit("|").map(|s| s.to_string()).collect::<Vec<String>>().pop();
> ```

Isn't this equivalent to calling `first()` on the result of the map?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11269#-:-KIe1besL2o8cvEy4cWV:1458266033)*

**Comment by dati91** [comment]
*[components/net/bluetooth_thread.rs, line 236 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11269#-KIe1IZluUqOhmNDKDmO:-KIh6IpyIasQoT3HNs9C:766669236) ([raw file](https://github.com/servo/servo/blob/c46fb590dceb818bf735d6fa5102c167ca1c919f/components/net/bluetooth_thread.rs#L236)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Isn't this equivalent to calling `first()` on the result of the map?
</details>
`first()` and `get(0)` will give you `Option<&T>`, while `pop()` will give `Option<T>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11269)*

**Comment by jdm** [comment]
Go ahead and squash the review comment changes into the second commit.
-S-awaiting-review +S-needs-code-changes +S-needs-squash 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/net/bluetooth_thread.rs, line 236 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11269#-KIe1IZluUqOhmNDKDmO:-KIheyyPuPw4GHS0a__o:94464823) ([raw file](https://github.com/servo/servo/blob/c46fb590dceb818bf735d6fa5102c167ca1c919f/components/net/bluetooth_thread.rs#L236)):*
<details><summary><i>Previously, dati91 (Attila Dusnoki) wrote…</i></summary>
> `first()` and `get(0)` will give you `Option<&T>`, while `pop()` will give `Option<T>`
</details>
I think this would be clearer as `device.split("|").first().map(|s| s.to_string())`, in that case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11269#-:-KIhfYgviLNjYM2-WX6R:-1149043007)*

**Comment by KiChjang** [comment]
-S-awaiting-review -S-needs-squash +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/net/bluetooth_thread.rs, line 235 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11269#-KIhu0h5QCs7Amjan6xE:-KIhu0h5QCs7Amjan6xF:-154132109) ([raw file](https://github.com/servo/servo/blob/d33a44eeffada483901648beab5e30a325fccd76/components/net/bluetooth_thread.rs#L235)):*
> ```Rust
>                                                            Some(dialog_rows)) {
>             // The device string format will be "Address|Name". We need the first part of it.
>             return device.split("|").collect::<Vec<&str>>().first().map(|s| s.to_string());
> ```

`device.split("|").next().map(|s| s.to_string())`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11269#-:-KIhu99qjkUKJhLdjjNb:-569897477)*

**Pull request merged**
