### PR TITLE
Bug 1357461 - stylo: Cache media query results and only flush and restyle if they changed.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17147)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r=heycam

 * More servo-only build fixes

**Comment by nox** [comment]
I've never been that much in a hurry to see a PR land in my whole life.

**Comment by emilio** [comment]
@bors-servo retry

 * I think it may be intermittent

**Comment by emilio** [comment]
@bors-servo retry


Different test, which seems like a totally unrelated test to this patch.

**Pull request merged**
