### PR TITLE
removed XMLDocument constructor according to spec

### PR DESCRIPTION
**Pull request by creativcoder**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9825)

### CODE REVIEW

**Comment by Ms2ger** [comment]
If this doesn't hit any test failures, someone please file a bug to write a test that would have caught this.

**Comment by KiChjang** [comment]
Looks like there is one:
```
Ran 4608 tests finished in 957.0 seconds.
  • 4607 ran as expected. 1379 tests skipped.
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /dom/interfaces.html:
  └ PASS [expected FAIL] XMLDocument interface: existence and properties of interface object
```

**Comment by nox** [comment]
A wild Gecko/WebKit split appears!

Seems like WebKit exposes a constructor on XMLDocument (maybe inheriting it from Document?) while Gecko doesn't.

**Comment by Ms2ger** [comment]
@creativcoder this is waiting for you to remove the now-passing expectation from `dom/interfaces.html.ini`.

**Pull request merged**
