### PR TITLE
Avoid moves of Gecko style structs

### PR DESCRIPTION
**Pull request by bholley**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10582)

### CODE REVIEW

**Comment by Manishearth** [comment]
r=me once the rustup lands

**Comment by bholley** [comment]
@Manishearth why does this depend on the rustup? Given that the warnings are non-fatal and local to geckolib, I think it's fine to just land this.

**Comment by Manishearth** [comment]
Because it will warn on the arc right now.

r=me then

**Comment by bholley** [comment]
The "no gecko style struct" case never gets hit in my local tree anymore because I've matched them all up, but on master it still doesn't, which caused compile bustage. Fixed.

@bors-servo r=Manishearth

**Pull request merged**
