### PR TITLE
Read firefox path from environment variable for performance test

### PR DESCRIPTION
**Pull request by shinglyu**
This is for Stylo performance testing (at least before we got Talos running)

r?@Manishearth

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because independent from servo itself

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14937)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Since we look for `geckodriver` on the `$PATH`, why not also look for `firefox` on the `$PATH` instead of a separate environment variable? I believe Selenium will automatically do a `$PATH` lookup if you don't pass an explicit `firefox_binary`.

**Comment by Manishearth** [comment]
r=me with path changes if they work (else just land this)

**Comment by shinglyu** [comment]
I made this change for Stylo testing, we need to frequently switching from a custom stylo build and a normal build (nighlty downloaded as a tarball?), and a developer may have a release build for their daily use in `PATH`, so I'd prefer not to find the firefox binary in `PATH`.

**Comment by shinglyu** [comment]
Based on the explanation above, I'm landing this to unblock my next PR.

**Comment by shinglyu** [comment]
Stuck?

@bors-servo: try

**Comment by shinglyu** [comment]
Just fixed some tidy errors.

@bors-servo: r=Manishearth

**Pull request merged**
