### PR TITLE
devtools: Convert the developer tools to run over IPC.

### PR DESCRIPTION
**Pull request by pcwalton**
This was a large, invasive change.

r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6745)

### CODE REVIEW

**Comment by pcwalton** [comment]
Rebased.

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

Sorry the devtools were a pain; thanks for doing this work!

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/devtools/actors/timeline.rs, line 207 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6745#-JvEVJqTKu427Qyz-WOy)** ([raw file](https://github.com/servo/servo/blob/a4f099c1526b18abbee31f84068790c98c4333d1/components/devtools/actors/timeline.rs#L207)):</sup>
I saw a commit in ipc-channel that added try_recv.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6745)

**Comment by jdm** [comment]
I forgot about the comment I left.

**Comment by jdm** [comment]
Test failure was just #6780.

**Comment by pcwalton** [comment]
Comment addressed. r? @jdm

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6745)

**Pull request merged**
