### PR TITLE
Properly generate typedef identities in unions

### LINKED ISSUE #10605: Typdefs are not generated in unions
Suppose I have the following:
```webidl
typedef (A or B or C) Foo;

DOMString bar(Foo or DOMString? qux);
```

The codegen currently does not generate `FooOrString` as expected - it would instead generate `AorBorCorDOMString`, and ignoring the typedef altogether.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #10605.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13201)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* #13165

**Comment by larsbergstrom** [comment]
@bors-servo retry
- infra

**Pull request merged**
