### PR TITLE
Print tidy errors as they happen instead of all-at-once

### PR DESCRIPTION
**Pull request by frewsxcv**
Related to #8969

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8977)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Yeah, this could be a nice workaround until we fix its performance :)

**Comment by jdm** [comment]
Couldn't we do:
```python
for error in errors:
    print ...
else:
    return 0
return 1
```
instead?

**Comment by frewsxcv** [comment]
No

```
In [1]: for i in []:
   ...:     pass
   ...: else:
   ...:     print 'hi'
   ...:
hi
```

**Comment by frewsxcv** [comment]
Also:

```
No

```
In [1]: for i in [1, 2, 3]:
   ...:     pass
   ...: else:
   ...:     print 'hi'
   ...:
hi
```
```

**Comment by frewsxcv** [comment]
So no, it won't work since even if there were errors, it would still trigger the `else` block. @jdm did you have any other thoughts on this?

**Pull request merged**
