### PR TITLE
Update mozjs to use SpiderMonkey artifacts by default if possible

### PR DESCRIPTION
**Pull request by sagudev**
Companion for https://github.com/servo/mozjs/pull/450

Using mozjs_sys artifacts by default.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by sagudev** [comment]
Windows/Mac compilation time went down for 4min (before we were using sccache, so compilation was already pretty fast).

**Comment by wusyong** [comment]
I was looking for places to add notes about the new [curl requirements](https://github.com/servo/mozjs/pull/450#discussion_r1539151420). But it looks like current README.md already asking to use `curl` to install rust toolchains. Do we still want to mention it needs curl?

**Comment by mrobinson** [comment]
> I was looking for places to add notes about the new [curl requirements](https://github.com/servo/mozjs/pull/450#discussion_r1539151420). But it looks like current [README.md](https://github.com/servo/servo?tab=readme-ov-file#linux) already asking to use `curl` to install rust toolchains. Do we still want to mention it needs curl?

If it's installed on Windows by default, I think it's not necessary.

**Review by mrobinson — APPROVED** [review]
Apologies for the large lag in reviewing. This seems totally fine!

**Comment by wusyong** [comment]
@sagudev Thanks for updating! I can now use archive without adding patch in Cargo.toml.
I believe this will help newcomers a lot when building for the first time.

**Comment by sagudev** [comment]
> @sagudev Thanks for updating! I can now use archive without adding patch in Cargo.toml. I believe this will help newcomers a lot when building for the first time.

It will also help me, so thank you for doing all hard work.

**Pull request merged**
