### PR TITLE
refactor(layout_task.rs): move some functions to query.rs

### LINKED ISSUE #8470: Move some LayoutTask methods to query.rs.
We started this in #6836.

Move the `LayoutTask` methods `process_node_geometry_request`, `process_resolved_style_request`, and `process_offset_parent_query` from `components/layout/layout_task.rs` to `components/layout/query.rs`.

In the process, the `&self` argument should be removed.

### PR DESCRIPTION
**Pull request by luthfianto**
Should fixes #8470

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8606)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thanks for your PR. It looks good, except for one small style change I'd like you to make.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[components/layout/layout_task.rs, line 1039 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8606#-K3VWvmO_hgAffS4gZjG:-K3VWvmPwBSwoQVu_ivZ:-1087814180) ([raw file](https://github.com/servo/servo/blob/67af7728dd31e15e162a50587dba7e8969a8a156/components/layout/layout_task.rs#L1039)):_
Please fix the indentation here.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8606#-:-K3VXJXwpH1hBWln3J3c:-134920011)_

**Comment by rilut** [comment]
Do I need to squash the commit or how?

---







_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8606#-:-K3VYPHwXbP2XDya2H9S:427651153)_

**Comment by rilut** [comment]
_[components/layout/layout_task.rs, line 1039 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8606#-K3VWvmO_hgAffS4gZjG:-K3VY7yJq7Lr9kx1e8VB:427651153) ([raw file](https://github.com/servo/servo/blob/67af7728dd31e15e162a50587dba7e8969a8a156/components/layout/layout_task.rs#L1039)):_
Do I need to squash the commit or how?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8606)_

**Comment by Ms2ger** [comment]
Yep, thanks!

@bors-servo r+

**Pull request merged**
