### PR TITLE
Added cleaning of packages to mach.

### PR DESCRIPTION
**Pull request by awlnx**
issue #4898

### CODE REVIEW

**Comment by jdm** [comment]
What happens if you just use `./mach clean` with your changes? I worry that `params` will be None and there will be an exception.

**Comment by awlnx** [comment]
I tested for it with pdb.  Params when not set = [ ]

**Comment by jdm** [comment]
Great! Can you squash these two commits together, in that case?

**Comment by awlnx** [comment]
bingo bongo

**Comment by jdm** [comment]
Fantastic :)

**Pull request closed without merging**
