### PR TITLE
Remove unnecessary unsafe block

### PR DESCRIPTION
**Pull request by deokjinkim**
Remove unused unsafe block.
cc @yichoi

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6261)

### CODE REVIEW

**Comment by jdm** [comment]
I think this was addressed by #6258 already.

**Comment by Manishearth** [comment]
@bors-servo: r-

Temporary r- for ops stuff

**Comment by metajack** [comment]
It was. Closing.

**Pull request closed without merging**
