### PR TITLE
Update filtering in main fetch to the specification.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14515)

### CODE REVIEW

**Comment by Ms2ger** [comment]
```

  ▶ Unexpected subtest result in /eventsource/dedicated-worker/eventsource-constructor-non-same-origin.htm:
  │ FAIL [expected PASS] dedicated worker - EventSource: constructor (act as if there is a network error) (about:blank)
  │   → assert_equals: source.readyState expected 2 but got 0
  │ 
  │ fetchFail/</worker.onmessage/<@http://web-platform.test:8000/eventsource/dedicated-worker/eventsource-constructor-non-same-origin.htm:9:15
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  └ fetchFail/</worker.onmessage@http://web-platform.test:8000/eventsource/dedicated-worker/eventsource-constructor-non-same-origin.htm:7:13

  ▶ Unexpected subtest result in /eventsource/eventsource-constructor-non-same-origin.htm:
  │ FAIL [expected PASS] EventSource: constructor (act as if there is a network error) (about:blank)
  │   → assert_equals: expected 2 but got 0
  │ 
  │ fetchFail/</source.onerror/<@http://web-platform.test:8000/eventsource/eventsource-constructor-non-same-origin.htm:8:15
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1406:20
  └ fetchFail/</source.onerror@http://web-platform.test:8000/eventsource/eventsource-constructor-non-same-origin.htm:7:13
```

Interesting.

**Comment by Ms2ger** [comment]
CC @KiChjang

**Comment by jdm** [comment]
First commit is fine; let's drop the second commit and I'll file an issue in web-platform-tests.

**Comment by jdm** [comment]
Filed https://github.com/w3c/web-platform-tests/issues/4311.

**Comment by Ms2ger** [comment]
@bors-servo retry
???

**Comment by Ms2ger** [comment]
@bors-servo r-

This breaks loading Ahem in css tests, because we do it from a `file:` URL. Not sure how to deal yet.

**Comment by jdm** [comment]
What's the plan here?

**Comment by jdm** [comment]
@Ms2ger Are you planning to return to this?

**Comment by jdm** [comment]
Tracking in #16117.

**Pull request closed without merging**
