### PR TITLE
layout: Improve scrolling behavior for the root element.

### PR DESCRIPTION
**Pull request by pcwalton**
Improves Google search results.

r? @notriddle

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13936)

### CODE REVIEW

**Review by notriddle — APPROVED** [review]
Review progress:
- [X] 53c4845e2109e90df08937bcc62120a5b23688e4
- [X] ae4a3e6d8854d6be0ba5fec6becc929e53c7b446
- [X] 274b277d9115d893bf12bda74fd280356d8faa8e

**Comment by KiChjang** [comment]
@bors-servo retry
* Disk space issues?

**Comment by emilio** [comment]
@bors-servo: retry

 * Checking if intermittent.

**Comment by jdm** [comment]
@pcwalton Are you planning to revisit this, or should we file an issue with a testcase that reproduces the problem it was addressing?

**Comment by nox** [comment]
No answer, we should close this.

**Comment by pcwalton** [comment]
Let's close this for now

**Pull request closed without merging**
