### PR TITLE
Implement Document.referrer

### LINKED ISSUE #12389: Implement Document.referrer
This is required for #10311. We should store an `Option<String>` value in `Document` that is obtained from the `Referer` HTTP header (if present) when the document is created in `ScriptThread::load`.

Spec: https://html.spec.whatwg.org/multipage/dom.html#dom-document-referrer
Code: `components/script/dom/document.rs`, `components/script/script_thread.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/referrer-policy` may show new results with this change.

### PR DESCRIPTION
**Pull request by canova**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12389 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12416)

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /XMLHttpRequest/responsexml-document-properties.htm:
  └ PASS [expected FAIL] referrer

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] Document interface: attribute referrer

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] Document interface: new Document() must inherit property "referrer" with the proper type (36)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] Document interface: document.implementation.createDocument(null, "", null) must inherit property "referrer" with the proper type (36)
```
These test results will need to be updated too.

**Comment by canaltinova** [comment]
Oops, sorry I thought I ran all relevant tests. Updated now! :)

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Pull request merged**
