### PR TITLE
Stop using std::slice::bytes::copy_memory.

### LINKED ISSUE #8929: Remove usage of deprecated std::slice::bytes::copy_memory
```
/Users/alex_gaynor/projects/servo/components/canvas/webgl_paint_task.rs:16:5: 16:35 warning: use of deprecated item: unidiomatic functions not pulling their weight, #[warn(deprecated)] on by default
/Users/alex_gaynor/projects/servo/components/canvas/webgl_paint_task.rs:16 use std::slice::bytes::copy_memory;
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/alex_gaynor/projects/servo/components/canvas/webgl_paint_task.rs:368:13: 368:24 warning: use of deprecated item: unidiomatic functions not pulling their weight, #[warn(deprecated)] on by default
/Users/alex_gaynor/projects/servo/components/canvas/webgl_paint_task.rs:368             copy_memory(&src_slice[..stride], &mut pixels[dst_start .. dst_start + stride]);
                                                                                        ^~~~~~~~~~~

/Users/alex_gaynor/projects/servo/components/compositing/compositor.rs:47:5: 47:35 warning: use of deprecated item: unidiomatic functions not pulling their weight, #[warn(deprecated)] on by default
/Users/alex_gaynor/projects/servo/components/compositing/compositor.rs:47 use std::slice::bytes::copy_memory;
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/alex_gaynor/projects/servo/components/compositing/compositor.rs:1916:13: 1916:24 warning: use of deprecated item: unidiomatic functions not pulling their weight, #[warn(deprecated)] on by default
/Users/alex_gaynor/projects/servo/components/compositing/compositor.rs:1916             copy_memory(&src_slice[..stride],
                                                                                        ^~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by Ms2ger**
Fixes #8929.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8936)

### CODE REVIEW

**Comment by nox** [comment]
```
/home/servo/buildbot/slave/gonk/build/components/canvas/webgl_paint_task.rs:367:53: 367:91 error: use of unstable library feature 'clone_from_slice' (see issue #27750)
/home/servo/buildbot/slave/gonk/build/components/canvas/webgl_paint_task.rs:367             pixels[dst_start .. dst_start + stride].clone_from_slice(&src_slice[..stride]);
                                                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/gonk/build/components/canvas/webgl_paint_task.rs:367:53: 367:91 help: add #![feature(clone_from_slice)] to the crate attributes to enable
```

**Comment by saneyuki** [comment]
This is fixed by #8937

**Pull request closed without merging**
