### PR TITLE
style: A few trivial changes in preparation for document state invalidation.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19744)

### CODE REVIEW

**Comment by upsuper** [comment]
Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[components/style/gecko/selector_parser.rs, line 148 at r1](https://reviewable.io:443/reviews/servo/servo/19744#-L2_Hx8UrpWRRreoRuSL:-L2_Hx8UrpWRRreoRuSM:b-fgy4g4) ([raw file](https://github.com/servo/servo/blob/445a5ce5134a8150d21882cd4c30726265192472/components/style/gecko/selector_parser.rs#L148)):*
> ```Rust
>                     $(NonTSPseudoClass::$s_name(..) => check_flag!($s_flags),)*
>                     // TODO(emilio): Maybe -moz-locale-dir shouldn't be
>                     // content-exposed.
> ```

Right, it probably shouldn't. It could be used as a fingerprint bit. Consider filing a bug for that.

---

*[components/style/gecko/wrapper.rs, line 2136 at r1](https://reviewable.io:443/reviews/servo/servo/19744#-L2_IXS_H3LuvUMACj0t:-L2_IXS_H3LuvUMACj0u:b-tw8bxg) ([raw file](https://github.com/servo/servo/blob/445a5ce5134a8150d21882cd4c30726265192472/components/style/gecko/wrapper.rs#L2136)):*
> ```Rust
>                     Direction::Ltr => !doc_is_rtl,
>                     Direction::Rtl => doc_is_rtl,
>                     Direction::Other(..) => return false,
> ```

`return` seems to be pointless here, just `false` should be enough.

---

*[components/style/invalidation/element/state_and_attributes.rs, line 310 at r3](https://reviewable.io:443/reviews/servo/servo/19744#-L2_IwROV-FQwH1dT3Hy:-L2_IwROV-FQwH1dT3Hz:bl5omst) ([raw file](https://github.com/servo/servo/blob/8512cf8604e3aaf61f44cd1b823ef754ca733f9e/components/style/invalidation/element/state_and_attributes.rs#L310)):*
> ```Rust
>         }
> 
>         should_process_descendants(element)
> ```

I would probably have `should_process_descendants` accept `&ElementData`, so that we can reuse the common logic of when we want to skip descendants even inside this method.

---

*[components/style/invalidation/element/state_and_attributes.rs, line 321 at r3](https://reviewable.io:443/reviews/servo/servo/19744#-L2_JOfhOq7wUrGPpjQ0:-L2_JOfhOq7wUrGPpjQ1:bv7m6zy) ([raw file](https://github.com/servo/servo/blob/8512cf8604e3aaf61f44cd1b823ef754ca733f9e/components/style/invalidation/element/state_and_attributes.rs#L321)):*
> ```Rust
>         if let Some(mut data) = element.mutate_data() {
>             data.hint.insert(RestyleHint::RESTYLE_DESCENDANTS);
>         }
> ```

Wouldn't you want to reuse this as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19744)*

**Comment by upsuper** [comment]
r=me with the comments addressed.

**Comment by emilio** [comment]
Re.

> Wouldn't you want to reuse this as well?

We're probably going to run the document state invalidations on the main thread, so there's no need for stack limits / recursion limits.

**Comment by emilio** [comment]
@bors-servo r=upsuper

 * Rest of comments are addressed, thanks for the review!

**Pull request merged**
