### PR TITLE
Handle HTTP errors for script requests correctly

### LINKED ISSUE #8391: Do not attempt to execute JS from 404 responses
Load the following file in Servo:
```
<!doctype html>
<html>
<head>
	<script src="http://example.org/urlthat404s" onerror="alert('fail');"></script>
	<script src="http://domainthatdoesntexistfdjklajgdklgjfkgjf.org/blah" onerror="alert('fail2');"></script>
	<script>alert('success');</script>
</head>
<body>
<h1>Hello</h1>
</body>
</html>

```
and you'll get
```
ERROR:js::rust: Error at http://example.org/urlthat404s:0:0: expected expression, got '<'

ERROR:script::dom::htmlscriptelement: error loading script failed to lookup address information: Name or service not known
ALERT: fail2
ALERT: success
```
The 404 response contains HTML, and servo attempts to execute this HTML as JS.

In both Firefox and Chrome, 404 responses are not executed, and instead the error event is emitted, as specified by http://www.w3.org/TR/html5/scripting-1.html#execute-the-script-block . In these browsers, three alerts (fail, fail2 and success) are shown.

(BTW, it would be nice if the DNS error message specified the domain that it failed to lookup)

### PR DESCRIPTION
**Pull request by catrope**
Spec says we have to invoke the error handler, not attempt
to execute the response.

Fixes #8391.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8422)

### CODE REVIEW

**Comment by Ms2ger** [comment]
This should definitely have tests, if it doesn't yet

+S-needs-code-changes

@bors-servo try


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/script/dom/htmlscriptelement.rs, line 144 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8422#-K2hGC6PNLhAR2ytd6av)** ([raw file](https://github.com/servo/servo/blob/9f33091d2b546d938fd4cc3b9bd80c129e94a0cd/components/script/dom/htmlscriptelement.rs#L144)):</sup>
I'd like to see a pointer to the spec around here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8422)

**Comment by KiChjang** [comment]
@catrope any updates on this?

**Comment by Wafflespeanut** [comment]
Closing this on inactivity

**Pull request closed without merging**
