### PR TITLE
Implementation of HTTP Redirect Fetch step

### PR DESCRIPTION
**Pull request by nikkisquared**
I've made a first draft of a complete implementation of HTTP Redirect Fetch, most of which is just refactored out of HTTP Fetch. I've also made some minor changes in a few other steps, all collected in the second commit, based on recent changes to the Fetch Standard. Since HTTP Redirect Fetch is so new, I figured now would be a fine time to make those other changes.

The biggest thing on my mind right now is how the spec says[1] "This algorithm will be used by HTML's "navigate" algorithm in addition to HTTP fetch above." This makes me think that this function, as well as HTTP Fetch, need to public, or at least have a public-facing function- since each Fetch function takes an Rc<Request>, which might be weird to require callers to supply.

[1] https://fetch.spec.whatwg.org/#http-redirect-fetch

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9608)

### CODE REVIEW

**Comment by jdm** [comment]
Good work! Only a few small things that need further work.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/net/fetch/methods.rs, line 438 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9608#-KAH-idy5RExN8Vlkdbk:-KAH-idy5RExN8Vlkdbl:-939158129) ([raw file](https://github.com/servo/servo/blob/46cdb82acf00ce3cb5096a228e05930610e7e893/components/net/fetch/methods.rs#L438)):*
We can do `response = request.redirect_mode.get() {` and simplify the cases a bit by removing the assignment from them.

---

*[components/net/fetch/methods.rs, line 570 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9608#-KAH2LU7G57QZSWfiIHH:-KAH2LU7G57QZSWfiIHI:959003403) ([raw file](https://github.com/servo/servo/blob/46cdb82acf00ce3cb5096a228e05930610e7e893/components/net/fetch/methods.rs#L570)):*
This would be easier to read as:
```rust
let status_code = actual_response.status.unwrap();
if ((status_code == ... ||
```

---

*[components/net/fetch/methods.rs, line 571 \[r4\]](https://reviewable.io:443/reviews/servo/servo/9608#-KAH4SrkZBtM3c0tvbUV:-KAH4SrkZBtM3c0tvbUW:53319227) ([raw file](https://github.com/servo/servo/blob/56e55a9a8141d5d6f9919addaf8f3cea725950c9/components/net/fetch/methods.rs#L571)):*
This match doesn't actually match the spec text. We should have a test for this behaviour :D

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9608#-:-KAH4dclflvohnulXDEE:-311500217)*

**Comment by jdm** [comment]
Great work! Go ahead and squash these together!
-S-awaiting-review +S-needs-squash 

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9608#-:-KAhECxw9d5k59ATYMiR:1427590353)*

**Comment by jdm** [comment]
@bors-servo: retry
* #8120

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #7791

**Pull request merged**
