### PR TITLE
Partial fix for #12415: expose interfaces only where necessary

### PR DESCRIPTION
**Pull request by ice9js**
Partial fix for #12415.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [X] These changes do not require tests because they don't affect any features.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12537)

### CODE REVIEW

**Comment by Manishearth** [comment]
r? @nox 


I'm not sure what removing `Exposed` does -- does it mean "inherit"?

If so, r=me

**Comment by Manishearth** [comment]
Okay, it is inherit.

Could you annotate Node and Element so that they are only exposed to Window first? This PR won't work otherwise.

**Comment by ice9js** [comment]
It seems like a lot of stuff depends on Node and Element. Because of that, it won't compile unless I update everything that depends on them.

I'm not sure what I should do, since I was supposed to keep the PR's for this relatively small, but it seems like it will be quite a challenge to do so.

**Comment by Manishearth** [comment]
It's fine to expand the scope of this PR.

**Comment by ice9js** [comment]
I'm rather worried about #12533 because this means we'll overlap. Should I merge @woshilapin 's changes into this PR as well ?

**Comment by Manishearth** [comment]
yep

**Comment by woshilapin** [comment]
Indeed, there will be some overlap at some point. For example, I tried to modify `HTMLScriptElement.webidl` in #12526 but discovered that there will be implication with `Document.webidl` and a bunch of others.  So probably, `HTMLScriptElement.webidl` should a PR for itself because a lot of other modifications will be dependent.  I expect that `Document.webidl` will be a tough PR...

**Comment by Ms2ger** [comment]
It's not "inherit"; it's "only the primary global" (window)

**Comment by Manishearth** [comment]
What was the issue with HTMLScriptElement?

**Comment by Manishearth** [comment]
Ah, if it's not inherit then it's fine to do this piece by piece

**Comment by Ms2ger** [comment]
@bors-servo r-

Except that the tests need to be updated.

**Comment by jdm** [comment]
Specifically:
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.worker:
  │ FAIL [expected PASS] Untitled
  │   → assert_true: HTMLAnchorElement should be defined on the global scope expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:81:7
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1403:20
  │ test@http://web-platform.test:8000/resources/testharness.js:501:9
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:3
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.worker.js:9:1
```

**Comment by ice9js** [comment]
For some reason, I'm unable to get the test to fail :( I'm using the following command to run it, as that's the one that was failing according to the logs:

```
HOST_FILE=../tmp_hosts.txt ./mach test-wpt tests/wpt/mozilla/tests/mozilla/iframe_contentDocument.html
```

**Comment by jdm** [comment]
Tests run in parallel, so that's not the test that was failing. You want `tests/wpt/mozilla/tests/mozilla/interfaces.worker.js` instead.

**Comment by ice9js** [comment]
I tried that one first but it tells me there aren't any tests in there. That's why I thought it might be the other one. I also gave ```tests/wpt/mozilla/tests/mozilla/interfaces.html``` a go but it seems to pass as well. What am I missing ?

screen shot 2016-07-22 at 08 48 25

**Comment by Ms2ger** [comment]
You need to run `./mach test-wpt tests/wpt/mozilla/tests/mozilla/interfaces.worker`, without the `.js`. We should handle that better; sorry.

**Comment by ice9js** [comment]
That doesn't seem to do anything either :(

**Comment by Ms2ger** [comment]
Argh. `./mach test-wpt _mozilla/mozilla/interfaces.worker` works here.

**Comment by ice9js** [comment]
Thanks! I updated the test.

**Comment by KiChjang** [comment]
```
Ran 9977 tests finished in 930.0 seconds.
  • 9976 ran as expected. 132 tests skipped.
  • 1 tests crashed unexpectedly

Tests with unexpected results:
  ▶ CRASH [expected PASS] /css21_dev/html4/border-right-018.htm
  │ 
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ ERROR:servo: called `Result::unwrap()` on an `Err` value: RecvError
  └ thread panicked while processing panic. aborting.
```

**Comment by jdm** [comment]
@bors-servo: retry
* #12553

**Comment by ice9js** [comment]
I got rid of the conflicts.

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r+

**Pull request merged**
