### PR TITLE
Split fn script_chan into 5 different task channel fn

### PR DESCRIPTION
**Pull request by KiChjang**
Partial #7959.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8853)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I'm a little sad that this still uses "chan".

**Comment by jdm** [comment]
I'm fine with these changes, but I'd like to rename the `_chan` suffix to `_task_source` instead.

**Comment by KiChjang** [comment]
Updated.

**Comment by KiChjang** [comment]
```
Ran 3729 tests finished in 284.0 seconds.
  • 3728 ran as expected. 708 tests skipped.
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /XMLHttpRequest/send-entity-body-document.htm:
  │ FAIL [expected PASS] HTML document, shift-jis
  │   → assert_equals: document should be serialized and sent as text/html;charset=UTF-8 (TEST#2) expected "text/html;charset=UTF-8" but got "text/plain;charset=UTF-8"
  │ 
  │ request/<@http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm:18:1
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1381:20
  │ test@http://web-platform.test:8000/resources/testharness.js:495:9
  │ request@http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm:13:1
  │ init@http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm:29:42
  └ load@http://web-platform.test:8000/XMLHttpRequest/send-entity-body-document.htm:0:1
```

**Comment by jdm** [comment]
@bors-servo: retry
* #8865

**Pull request merged**
