### PR TITLE
Make BrowsingContext JS-managed.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7128)

### CODE REVIEW

**Comment by Ms2ger** [comment]
r? @jdm 

Please review carefully; I mostly copy/pasted this together.

**Comment by jdm** [comment]
-S-needs-rebase -S-awaiting-review +S-needs-code-changes 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/browsercontext.rs, line 32 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7128#-Jwr-EyxqiQvBu2opVG1)** ([raw file](https://github.com/servo/servo/blob/0a9fa3141bf437edded4cde7870e12a42514cff1/components/script/dom/browsercontext.rs#L32)):</sup>
Don't need this any more.

---

<sup>**[components/script/dom/browsercontext.rs, line 64 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7128#-Jwr-Q90UCWPHP7jURTi)** ([raw file](https://github.com/servo/servo/blob/0a9fa3141bf437edded4cde7870e12a42514cff1/components/script/dom/browsercontext.rs#L64)):</sup>
We'll need a more informative comment here. I also haven't been able to determine how the JSClass value in ProxyOptions gets used yet.

---

<sup>**[components/script/dom/browsercontext.rs, line 70 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7128#-Jwr6yM9Aqj_ONk07_lH)** ([raw file](https://github.com/servo/servo/blob/0a9fa3141bf437edded4cde7870e12a42514cff1/components/script/dom/browsercontext.rs#L70)):</sup>
I don't think this is necessary, given the operations being performed here.

---

<sup>**[components/script/dom/browsercontext.rs, line 71 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7128#-Jwr7A5829NvF0r33AE-)** ([raw file](https://github.com/servo/servo/blob/0a9fa3141bf437edded4cde7870e12a42514cff1/components/script/dom/browsercontext.rs#L71)):</sup>
I think we can get away with just passing Box::into_raw inline here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7128)

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/browsercontext.rs, line 64 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7128#-Jwr-Q90UCWPHP7jURTi)** ([raw file](https://github.com/servo/servo/blob/0a9fa3141bf437edded4cde7870e12a42514cff1/components/script/dom/browsercontext.rs#L64)):</sup>
I was going to use it for the inner/outer hooks, but those are being removed in <https://bugzilla.mozilla.org/show_bug.cgi?id=1125423>.


---

<sup>**[components/script/dom/browsercontext.rs, line 71 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7128#-Jwr7A5829NvF0r33AE-)** ([raw file](https://github.com/servo/servo/blob/0a9fa3141bf437edded4cde7870e12a42514cff1/components/script/dom/browsercontext.rs#L71)):</sup>
`raw` is used below.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7128)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7128)

**Pull request merged**
