### PR TITLE
Regenerate WPT certs.

### LINKED ISSUE #28672: Many Linux WPT tests time out in Github Actions
https://github.com/servo/servo/runs/4825833746?check_suite_focus=true

This is affecting all PRs in the past few days.

### PR DESCRIPTION
**Pull request by jdm**
The certs expired on Jan 12; this regenerates them for another year. Usually this wouldn't be an issue since upstream WPT regenerates them every month, but we have not had a successful sync since January 2021. Fixes #28672.

### CODE REVIEW

**Comment by negator** [comment]
What does a sync entail?

**Comment by jdm** [comment]
See #28592.

**Pull request merged**
