### PR TITLE
X11 clipboard support

### PR DESCRIPTION
**Pull request by aweinstock314**
Manual re-opening of #5479 (since it seems that GitHub disables re-opening with the same number after a rebase).

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5547)

### CODE REVIEW

**Comment by jdm** [comment]
Just waiting on https://github.com/servo/rust-xlib/pull/36 at this point. @aweinstock314 could you update https://github.com/servo/servo/blob/master/README.md#prerequisites as well?

**Comment by aweinstock314** [comment]
It looks like https://github.com/servo/rust-xlib/pull/36 has gone unmerged for a while, and https://github.com/servo/servo/issues/5566 seems to imply that rust-xlib is unmaintained/in the process of being replaced. Should I revise this to depend on https://github.com/Daggerbot/x11-rs (and submit a PR to x11-rs to add the clipboard-related constants)?

**Comment by jdm** [comment]
Until we actually transition to using rust-xlib everywhere, I'm in favour of continuing to add to it. I didn't notice that https://github.com/servo/rust-xlib/pull/36 was now working on Travis; I'm going to go ahead and merge it.

**Comment by jdm** [comment]
Go ahead and squash this while rebasing!

**Comment by jdm** [comment]
Whoops. test-unit is broken by these changes; we probably need an optional constellation channel instead.

**Comment by aweinstock314** [comment]
I tried that, it won't allow borrowing self (for self.insert_string) since cc is already borrowed.

**Pull request merged**
