### PR TITLE
Implement `animation-fill-mode`

### LINKED ISSUE #26460: Text animation doesn't stop
URL: https://vercel.com/keyboard

Steps to reproduce:

1. Load https://vercel.com/keyboard in Servo.
2. The text animation no longer stops when it's supposed to and the animation keeps looping.

This issue first occurred in the 2020-05-02 nightly build. Tested in Windows 10.

Regression range: https://github.com/servo/servo/compare/6fb75c2b9eb3825932a22b1c7a6d7ce03809fbb2...d08c4fff15cb5f6a8840621e848c9de22fcc3439

### PR DESCRIPTION
**Pull request by mrobinson**
Fixes #26460.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are tests for these changes

### CODE REVIEW

**Comment by mrobinson** [comment]
Note: There is a set of small manual tests in web-platform-tests, but I've added an automated test using Servo's testing time warp functionality.

**Review by jdm — APPROVED** [review]

**Review by emilio — APPROVED** [review]

**Comment by CYBAI** [comment]
Failed in Linux:

```
error[E0433]: failed to resolve: could not find `animation_fill_mode` in `longhands`
  --> components/style/animation.rs:16:35
   |
16 | use crate::properties::longhands::animation_fill_mode::computed_value::single_value::T as AnimationFillMode;
   |                                   ^^^^^^^^^^^^^^^^^^^ could not find `animation_fill_mode` in `longhands`
error[E0433]: failed to resolve: use of undeclared type or module `AnimationFillMode`
   --> components/style/animation.rs:385:31
    |
385 |             self.fill_mode != AnimationFillMode::Backwards &&
    |                               ^^^^^^^^^^^^^^^^^ use of undeclared type or module `AnimationFillMode`
error[E0433]: failed to resolve: use of undeclared type or module `AnimationFillMode`
   --> components/style/animation.rs:386:31
    |
386 |             self.fill_mode != AnimationFillMode::Both
    |                               ^^^^^^^^^^^^^^^^^ use of undeclared type or module `AnimationFillMode`
error[E0433]: failed to resolve: use of undeclared type or module `AnimationFillMode`
   --> components/style/animation.rs:392:31
    |
392 |             self.fill_mode != AnimationFillMode::Forwards &&
    |                               ^^^^^^^^^^^^^^^^^ use of undeclared type or module `AnimationFillMode`
error[E0433]: failed to resolve: use of undeclared type or module `AnimationFillMode`
   --> components/style/animation.rs:393:31
    |
393 |             self.fill_mode != AnimationFillMode::Both
    |                               ^^^^^^^^^^^^^^^^^ use of undeclared type or module `AnimationFillMode`
error[E0412]: cannot find type `AnimationFillMode` in this scope
   --> components/style/animation.rs:189:20
    |
189 |     pub fill_mode: AnimationFillMode,
    |                    ^^^^^^^^^^^^^^^^^ not found in this scope
warning: ignoring -C extra-filename flag due to -o flag
error: aborting due to 6 previous errors
Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `style`.
```

and some more tests pass now 🎉 

```
  ▶ Unexpected subtest result in /css/css-variables/variable-animation-substitute-within-keyframe-fallback.html:
  └ PASS [expected FAIL] Verify color before animation
  ▶ Unexpected subtest result in /css/css-variables/variable-animation-substitute-within-keyframe-multiple.html:
  └ PASS [expected FAIL] Verify color before animation
  ▶ Unexpected subtest result in /css/css-variables/variable-animation-substitute-into-keyframe.html:
  └ PASS [expected FAIL] Verify color before animation
  ▶ Unexpected subtest result in /css/css-variables/variable-animation-substitute-within-keyframe.html:
  └ PASS [expected FAIL] Verify color before animation
  ▶ Unexpected subtest result in /css/cssom/getComputedStyle-animations-replaced-into-ib-split.html:
  └ PASS [expected FAIL] getComputedStyle() should return animation styles for nodes just inserted into the document, even if they're in an IB-split
```

**Review by jdm — CHANGES_REQUESTED** [review]
https://github.com/servo/servo/blob/cd12c38a6d4d074c53f1e5f89aab406e13bb1a56/tests/wpt/mozilla/meta/css/animations/__dir__.ini is missing from the 2020 metadata directory: https://github.com/servo/servo/tree/cd12c38a6d4d074c53f1e5f89aab406e13bb1a56/tests/wpt/mozilla/meta-layout-2020/css/animations

**Comment by mrobinson** [comment]
Okay. I've updated change to include the ini file and have also rebased the layout_2020 test results for this directory. The tests will fail because support for animations in layout 2020 hasn't landed yet.

**Pull request merged**
