### PR TITLE
Remove HAS_DIRTY_SIBLINGS.

### PR DESCRIPTION
**Pull request by bholley**
This isn't doing anything right now, and we're not even setting it properly
in dirty_impl the |dirty_subtree(self)| was causing us to hit the skip case
for step 3.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8042)

### CODE REVIEW

**Comment by bholley** [comment]
(The proper way to handle sibling dirtying is with restyle hints, which I'm working on now)

**Comment by bholley** [comment]
@pcwalton When bors makes me fix merge conflicts, is there a way for me to "carry over review", or do I need to reflag?

**Comment by jdm** [comment]
One of the people with reviewer privileges needs to flag it again, unfortunately.

**Comment by jdm** [comment]
@bors-servo: retry
* #7731

**Comment by bholley** [comment]
@jdm another intermittent?

**Comment by frewsxcv** [comment]
@bors-servo retry

#7785

**Pull request merged**
