### PR TITLE
Ordering guarantees for timers

### PR DESCRIPTION
**Pull request by benschulz**
This is an rough solution to the issue described in #3396. XHRs still do their own thing and an overall clean up is in order. Before I do that, though, I'd really like someone to sign off on the overall idea.

There's one major difference to what jdm layed out #3396: The timers remain with the window/worker and only the earliest expiring one is coordinated with the dedicated timer thread.
That means both the timer thread and the window/worker have to keep track of which timer expires next, which feels a bit wonky. However, the upshot is that there's no need for communication with the timer thread when a pipeline is frozen, thawed or dropped.

Most relvant parts are
- the [`TimerScheduler`](https://github.com/servo/servo/commit/6f5f6619586379982321b5de7583d387df184504#diff-74137a6f50ab38e7a1e4d16920a66ce7R73), which is the new per-constellation timer task and
- the [`ActiveTimers`](https://github.com/servo/servo/commit/6f5f6619586379982321b5de7583d387df184504#diff-86707d952414a2860b78bcf6c1db8e2eR34) which is what's left on the window/worker side.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7450)

### CODE REVIEW

**Comment by jdm** [comment]
Just to avoid radio silence, I've started looking at this several times but have run out time to wrap my head around all the changes. It's pretty dense, unfortunately. I'm going to try using github's split diff view to see if that makes it any easier.

**Comment by benschulz** [comment]
Oh wow, those diffs are pretty worthless. Apparently github does not do `--patience` diffs. :( Anyway, I try to aim for the opposite of dense; so please let me know if there's anything I could do to make things more clear.

**Comment by jdm** [comment]
For the record, I've been looking at this since last commenting, and I plan to complete my review this weekend.

**Comment by jdm** [comment]
Thank you so much for doing this work @benschulz! This is really well put together, and I sincerely apologize for the long delay in reviewing it properly.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

<sup>**[components/compositing/timer_scheduler.rs, line 49 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznDI70NMItoUNhwbfC)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L49)):</sup>
Let's use `let _ = tx.send(());` here; we don't need a loud error if the target thread no longer exists.

---

<sup>**[components/compositing/timer_scheduler.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznEHeaJNPWNfCNtJAI)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L52)):</sup>
Why the +1?

---

<sup>**[components/compositing/timer_scheduler.rs, line 102 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznEVE0cayaq3gYJLtO)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L102)):</sup>
This looks like endless recursion to me.

---

<sup>**[components/compositing/timer_scheduler.rs, line 125 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznMhokit-JOu_DZK_L)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L125)):</sup>
I'm inclined to merge this with the constructor, rather than having a separate method for it.

---

<sup>**[components/compositing/timer_scheduler.rs, line 151 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznMuQkGo-c_dKp5Xa_)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L151)):</sup>
`if let Some(ref timer_port) = timer_port`

---

<sup>**[components/compositing/timer_scheduler.rs, line 205 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznNGi_RD18ivrr7GMW)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L205)):</sup>
Let's go ahead and use `let _ = chan.send(TimerEvent(source, id));` and ignore the error.

---

<sup>**[components/compositing/timer_scheduler.rs, line 218 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznNyFpSFWWKzY4OPeI)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L218)):</sup>
`if let Some(ref timer) = timer {`

---

<sup>**[components/script/timers.rs, line 42 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpOykZl2rp_-WTDCQa)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L42)):</sup>
Document this field? Its purpose is not clear to me without reading the rest of the code.

---

<sup>**[components/script/timers.rs, line 94 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPCxwUY5Rv5JrpUVq)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L94)):</sup>
This looks like endless recursion to me.

---

<sup>**[components/script/timers.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPZw35GNseeaL-uUX)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L139)):</sup>
Why this behaviour?

---

<sup>**[components/script/timers.rs, line 151 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPkiJPGwhR4wwdnFr)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L151)):</sup>
This needs to use the previous code that allocated a vector with a particular capacity to avoid reallocation.

---

<sup>**[components/script/timers.rs, line 171 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpQ7L7QWp9M7SN12OS)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L171)):</sup>
What does this mean, exactly? I've filed https://github.com/whatwg/html/issues/179 about clearing up the spec text, but all the browsers I tried don't differentiate between intervals and timeouts.

---

<sup>**[components/script/timers.rs, line 188 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpQMDVZRHvkpoKFOnG)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L188)):</sup>
?

---

<sup>**[components/script/timers.rs, line 191 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-Jzp_vYN6BTYhxevTiTg)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L191)):</sup>
Let's add a `debug!("ignoring timer fire event {:?} (expected {:?}")`.

---

<sup>**[components/script/timers.rs, line 253 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpThoY3jJ0n9JeoUML)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L253)):</sup>
Instead of this line and the previous if, let's do:
```rust
if let Some(timer) = timers.peek() {
}
```

---

<sup>**[components/script/timers.rs, line 286 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpaB2J-k7rVtGEiAsq)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L286)):</sup>
Let's add a `debug!("invalidating expected timer (was {:?}, now {:?})"` here to make debugging easier.

---

<sup>**[components/script_traits/lib.rs, line 178 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpaXZ6KW-gm3Fw_C_9)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script_traits/lib.rs#L178)):</sup>
to fire timers that are due.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by benschulz** [comment]
Ha, no problem. I appreciate the amount of time it takes to review code. Especially when it's written by an unexperienced (Rust) developer. I also realize that these PRs are small things the core developers could do in a couple of minutes to hours. Of course, these delays do have a negative impact on motivation, but I don't think that should change anything. If anything I think your priorities are correct as they are. **TL;DR**: No need to apologize.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[components/compositing/timer_scheduler.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznEHeaJNPWNfCNtJAI)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L52)):</sup>
Oh boy. I broke it. `due_time`, `current_time` and `park_time` used to all be in milliseconds. Now it's just `park_time`. I think I better add the unit to all variables. Hopefully the following  (and correct :wink:) code is self explanatory(?).

```
park_time_ms = ((due_time_ns - current_time_ns) / (1000 * 1000) + 1) as u32;
```

---

<sup>**[components/compositing/timer_scheduler.rs, line 125 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznMhokit-JOu_DZK_L)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L125)):</sup>
I thought it would be odd to have the constructor of `TimerScheduler` return a `Sender<TimerEventRequest>`. Beyond that, I'm on board. Perhaps I'll name the resulting associated function `start`…

---

<sup>**[components/script/timers.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPZw35GNseeaL-uUX)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L139)):</sup>
I didn't want intervals with a `duration` of `0` hogging the CPU. Rereading the spec, I should probably implement the [nesting level][nl]. At that point this would take care of itself.

[nl]: https://html.spec.whatwg.org/multipage/webappapis.html#timers:timer-nesting-level

---

<sup>**[components/script/timers.rs, line 151 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPkiJPGwhR4wwdnFr)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L151)):</sup>
Will do. Out of curiosity, though, is that "just" to avoid the allocations or is something being moved that should not be moved (which would surprise me)?

---

<sup>**[components/script/timers.rs, line 171 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpQ7L7QWp9M7SN12OS)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L171)):</sup>
Frankly I'm a bit surprised that this is common behaviour. But I'll leave it be until whatwg/html#179 is resolved.

---

<sup>**[components/script_traits/lib.rs, line 178 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpaXZ6KW-gm3Fw_C_9)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script_traits/lib.rs#L178)):</sup>
I'm not a native English speaker, so I have to ask: Does what I wrote make no sense at all or does it mean something I did not intend it to mean? Or is it just terrible style?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[components/compositing/timer_scheduler.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznEHeaJNPWNfCNtJAI)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L52)):</sup>
What if we used typed units? We could define `Nanoseconds` and `Milliseconds` units using http://doc.servo.org/euclid/length/struct.Length.html to avoid this problem (assuming we define a wrapper for precise_time_ns that returns the proper typed unit).

---

<sup>**[components/compositing/timer_scheduler.rs, line 125 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznMhokit-JOu_DZK_L)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L125)):</sup>
Yes, I think that's a good choice, and there's prior art for similar constructors that aren't named new and don't return the associated type.

---

<sup>**[components/script/timers.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPkiJPGwhR4wwdnFr)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L0)):</sup>
This is for GC safety - heap values are used by the JS engine and contain a pointer to an element of this vector. If the vector reallocates, it invalidates all of the prior Heap values.

---

<sup>**[components/script_traits/lib.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpaXZ6KW-gm3Fw_C_9)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script_traits/lib.rs#L0)):</sup>
I understood it, but I think that "due [something]" tends to mean something different than "[something] is due". Specifically, the first form appears to relate to the quality of something ("due process", "due care") rather than something that is expected at a certain time ("payment is due").

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by benschulz** [comment]
Review status: 15 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/compositing/timer_scheduler.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznEHeaJNPWNfCNtJAI)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L52)):</sup>
That's definitely a great idea. I'll put the code in script_traits for now, but that seems wrong. Is there a better place for it?

---

<sup>**[components/script/timers.rs, line 142 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPZw35GNseeaL-uUX)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L142)):</sup>
This is still open. I'll get to it on the weekend.

---

<sup>**[components/script/timers.rs, line 154 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPkiJPGwhR4wwdnFr)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L154)):</sup>
I still have to wrap my head around this. From what I can see, pointers are getting copied from one `Vec` to another in both cases; except in one there's a stopover in another `Vec`.

I'll stare at it some more on the weekend, hopefully I'll grok it then.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by jdm** [comment]
Review status: 15 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/compositing/timer_scheduler.rs, line 52 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JznEHeaJNPWNfCNtJAI)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/compositing/timer_scheduler.rs#L52)):</sup>
Probably utils/ if anywhere, but that's an unfortunate dumping ground. script_traits is fine until we need to use it elsewhere.

---

<sup>**[components/script/timers.rs, line 0 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPkiJPGwhR4wwdnFr)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L0)):</sup>
The difference is that we construct the Heap values in-place in the preallocated vector in the old code, and it's the Heap constructor that stores a pointer. In the new code, any Heap values in the vector when it reallocates will become invalid.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[components/compositing/timer_scheduler.rs, line 123 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7450#-K-07XM_3xu3RgAm1I-G)** ([raw file](https://github.com/servo/servo/blob/f48d66312f8eab6c33ae6494246524bb3d004cc6/components/compositing/timer_scheduler.rs#L123)):</sup>
What's the & doing here?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by benschulz** [comment]
Review status: 10 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/timers.rs, line 142 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7450#-JzpPZw35GNseeaL-uUX)** ([raw file](https://github.com/servo/servo/blob/6f5f6619586379982321b5de7583d387df184504/components/script/timers.rs#L142)):</sup>
Done.

---

<sup>**[components/script_traits/lib.rs, line 214 \[r11\]](https://reviewable.io:443/reviews/servo/servo/7450#-K-EGArcXaueaVHDVNKY)** ([raw file](https://github.com/servo/servo/blob/169df3634c878adb7f94d2a84891ffc26a108a60/components/script_traits/lib.rs#L214)):</sup>
Sorry, I was too trigger-happy. I need a `precise_time_ns` version to make sure that the time between `set_timeout_or_interval` and the callback invocation is at least `timeout` ms.

---

<sup>**[components/util/mem.rs, line 209 \[r9\]](https://reviewable.io:443/reviews/servo/servo/7450#-K-EBr8E92HousETnDlW)** ([raw file](https://github.com/servo/servo/blob/5ba0e0ed16857322130cd575f46ab0aee10720b2/components/util/mem.rs#L209)):</sup>
I don't feel too good about this. Should I switch to sorted vectors and get rid of the BinaryHeap impls for HeapSizeOf and JSTraceable?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by jdm** [comment]
Once again, apologies for the delay; I've been stretched really thin recently. I think we're very close to finishing this work, however!
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 6 of 6 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/timers.rs, line 221 \[r11\]](https://reviewable.io:443/reviews/servo/servo/7450#-K04iI7Lok-TzP8LeDa8)** ([raw file](https://github.com/servo/servo/blob/169df3634c878adb7f94d2a84891ffc26a108a60/components/script/timers.rs#L221)):</sup>
I think it would be valuable to add comments like `// step 6` in relevant parts of these changes (and add a comment linking to https://html.spec.whatwg.org/multipage/#timer-initialisation-steps above the relevant methods)


---

<sup>**[components/script/timers.rs, line 241 \[r11\]](https://reviewable.io:443/reviews/servo/servo/7450#-K04hv5o1tXhVO2WRI6I)** ([raw file](https://github.com/servo/servo/blob/169df3634c878adb7f94d2a84891ffc26a108a60/components/script/timers.rs#L241)):</sup>
FYI: this behaviour seems weird to me but my reading of the spec agrees. I've filed https://github.com/whatwg/html/issues/239 to sort out if we actually want to do this.


---

<sup>**[components/script/timers.rs, line 299 \[r11\]](https://reviewable.io:443/reviews/servo/servo/7450#-K04iDiI6kXMw3POBlXO)** ([raw file](https://github.com/servo/servo/blob/169df3634c878adb7f94d2a84891ffc26a108a60/components/script/timers.rs#L299)):</sup>
Let's call this `clamp_duration` instead. Also, let's add a spec link to https://html.spec.whatwg.org/multipage/#timer-initialisation-steps step 7


---

<sup>**[components/servo/Cargo.lock, line 1412 \[r8\]](https://reviewable.io:443/reviews/servo/servo/7450#-K-ERYb2euZPjZgk22g2)** ([raw file](https://github.com/servo/servo/blob/a5582c6f59d6cbd37aef3c99065902701bcbcf21/components/servo/Cargo.lock#L1412)):</sup>
You'll need to run `./mach cargo-update -p time --precise 0.1.32` to force the other Cargo.lock files to be updated too.


---

<sup>**[components/util/mem.rs, line 209 \[r9\]](https://reviewable.io:443/reviews/servo/servo/7450#-K-EBr8E92HousETnDlW)** ([raw file](https://github.com/servo/servo/blob/5ba0e0ed16857322130cd575f46ab0aee10720b2/components/util/mem.rs#L209)):</sup>
Sure, let's use a sorted vector instead.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by benschulz** [comment]
Seems it's my turn to apologize. ;)

Originally I wanted this PR to fix #3396, but at this point I'd prefer to do that separately.

I think I've addressed all notes so far. So unless you have any more, I'll squash and rebase.


---

Review status: 13 of 19 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by jdm** [comment]
Have at it! Squash and rebase!
-S-awaiting-review +S-needs-squash 


---

Reviewed 2 of 2 files at r12, 3 of 3 files at r13, 2 of 2 files at r14, 1 of 1 files at r16.
Review status: 18 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by jdm** [comment]
@bors-servo: r+
Woohoo!

**Comment by jdm** [comment]
```
/workers/WorkerGlobalScope_setInterval.htm
------------------------------------------
FAIL  WorkerGlobalScope API: setInterval() 
/_mozilla/mozilla/window_setInterval.html
-----------------------------------------
FAIL Untitled
```
```
2:34.98 TEST_START: Thread-TestrunnerManager-18 /workers/WorkerGlobalScope_setInterval.htm
 2:35.35 TEST_END: Thread-TestrunnerManager-18 Harness OK. Subtests passed 0/1. Unexpected 1
 WorkerGlobalScope API: setInterval() 
--------------------------------------
Expected PASS, got FAIL
assert_unreached: Unexpected message event Reached unreachable code
```

**Comment by benschulz** [comment]
> Woohoo!

Premature celebration… that was tempting fate. :P

Repeating timers could not clear themselves, because their `Timer` wasn't in the vector of active timers at the time of execution. I stupidly squashed the [fix](https://github.com/benschulz/servo/commit/97c71bd7930ea1c9acf41e4c340333e53d4e0cdd) and it's not getting picked up by reviewable, sorry. :(

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 1 of 1 files at r15, 20 of 20 files at r17.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7450)

**Comment by jdm** [comment]
@bors-servo: retry
* #7785

**Comment by waddlesplash** [comment]
Woohoo! :confetti_ball: :fireworks: :confetti_ball: :fireworks:

**Comment by frewsxcv** [comment]
The changes in this pull request caused a regression: #8324

**Pull request merged**
