### PR TITLE
Update websocket

### PR DESCRIPTION
**Pull request by SimonSapin**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9660)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* #9550

**Comment by SimonSapin** [comment]
@bors-servo retry

* #9063

**Comment by KiChjang** [comment]
```
Ran 4595 tests finished in 226.0 seconds.
  • 4594 ran as expected. 1372 tests skipped.
  • 1 tests timed out unexpectedly
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ TIMEOUT [expected OK] /websockets/opening-handshake/003.html

  ▶ Unexpected subtest result in /websockets/opening-handshake/003.html:
  │ TIMEOUT [expected PASS] WebSockets: origin
  └   → Test timed out
```
These do not look like intermittents.

**Comment by SimonSapin** [comment]
Code changes: https://github.com/cyderize/rust-websocket/compare/9a7f5b4eb1fbcfbf9131cbff9bab6a5524c37c22...020bb8936139828bf0d30413654173d5abbd6b0d

I’m not really interested in investigating this, I only submitted this PR as a prerequisite to unrelated changes. (Updating websocket for upcoming rust-url breaking changes.)

**Pull request merged**
