### PR TITLE
Complete steps for ChildNode::before

### PR DESCRIPTION
**Pull request by frewsxcv**
I was reading through the node.rs file and noticed that this `before`
method only has three steps, despite the WHATWG website saying there are
six. I implemented the steps as per:

https://dom.spec.whatwg.org/#dom-childnode-before

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6536)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I'm going to want tests :)

**Comment by frewsxcv** [comment]
I would imagine i would write unit tests for this, but it doesn't look like there is a node.rs file in https://github.com/servo/servo/tree/master/tests/unit/script . Should I create one? Should I be creating an integration test that tests this? Other ideas?

**Comment by Ms2ger** [comment]
We use web-platform-tests to test the DOM; see tests/wpt/README.md.

**Comment by frewsxcv** [comment]
Sounds good. I'm getting familiar with the wpt codebase working towards writing tests for this

**Comment by frewsxcv** [comment]
So I just learned that the `ChildNode` interface is specified by WHATWG and not by W3C (and not implemented by any major browser). Should I still add a test to web-platform-tests (since it's a project managed by W3C and they might not want a WHATWG feature). I also learned that no major engines have implemented the `ChildNode` interface. Lesson learned for me: check MDN before implementing

Anyways, I should probably find something more important to work on than fleshing out unused APIs

**Comment by frewsxcv** [comment]
Looks like it should be implemented in Chromium soon

https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/efUPtYm1PP8/MGoTi17AYpcJ

**Comment by frewsxcv** [comment]
Sounds like a good call, thanks for pointing that out @dzbarsky

**Comment by Ms2ger** [comment]
Looks like Chromium will be submitting tests pretty soon; I'll make sure they end up in our tree.

**Comment by Ms2ger** [comment]
https://critic.hoppipolla.co.uk/r/5488

**Comment by frewsxcv** [comment]
Tests added in https://github.com/w3c/web-platform-tests/pull/1974, just waiting for them to get added in-tree

**Comment by Ms2ger** [comment]
That's #6584; will try to get it landed today

**Comment by Ms2ger** [comment]
Will probably be Monday

**Comment by frewsxcv** [comment]
#6584 merged. Things I just did to this branch:

* Rebased off master
* Utilized `Deref` instead of `.r()` in a few places
* Updated WPT test expectations

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 812 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6536#-JuGbLcUtNhTnndMrj9b)** ([raw file](https://github.com/servo/servo/blob/0fb2186306b781f2eb9c2418bf5ec23028cea30d/components/script/dom/node.rs#L812)):</sup>
`....root();`

---

<sup>**[components/script/dom/node.rs, line 830 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6536#-JuGAz0Bv6igACrHcCLE)** ([raw file](https://github.com/servo/servo/blob/0fb2186306b781f2eb9c2418bf5ec23028cea30d/components/script/dom/node.rs#L830)):</sup>
Unfortunately iterators don't work like that. Add the following as tests:
```js
var parent = document.createElement("p")
var a = parent.appendChild(document.createElement("a"));
var b = parent.appendChild(document.createElement("b"));
var c = parent.appendChild(document.createElement("c"));
var d = parent.appendChild(document.createElement("d"));
try {
d.before(b, c)
} catch (ex) { alert(ex.message) }
alert(parent.innerHTML);

var parent = document.createElement("p")
var a = parent.appendChild(document.createElement("a"));
var b = parent.appendChild(document.createElement("b"));
var c = parent.appendChild(document.createElement("c"));
var d = parent.appendChild(document.createElement("d"));
var e = parent.appendChild(document.createElement("e"));
try {
e.before(c, d)
} catch (ex) { alert(ex.message) }
alert(parent.innerHTML);
```

You may also wish `any()` or `all()`

---

<sup>**[components/script/dom/node.rs, line 839 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6536#-JuGbct2kfMmPLCjQ--W)** ([raw file](https://github.com/servo/servo/blob/0fb2186306b781f2eb9c2418bf5ec23028cea30d/components/script/dom/node.rs#L839)):</sup>
You may not need the local `doc`?

---

<sup>**[components/script/dom/node.rs, line 850 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6536#-JuGawD0bC9IPBEkpdw8)** ([raw file](https://github.com/servo/servo/blob/0fb2186306b781f2eb9c2418bf5ec23028cea30d/components/script/dom/node.rs#L850)):</sup>
Could be better as...
```rust
}.root();

// Step 6.
try!(Node::pre_insert(&node, &parent, viable_previous_sibling.r()));

Ok(())
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6536)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/node.rs, line 850 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6536#-JuGawD0bC9IPBEkpdw8)** ([raw file](https://github.com/servo/servo/blob/0fb2186306b781f2eb9c2418bf5ec23028cea30d/components/script/dom/node.rs#L850)):</sup>
`}.root();`

Is it possible to `root` an `Option`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6536)

**Comment by jdm** [comment]
http://doc.servo.org/script/dom/bindings/js/trait.RootedReference.html

**Comment by frewsxcv** [comment]
> http://doc.servo.org/script/dom/bindings/js/trait.RootedReference.html

@jdm Doesn't this implement `r()` and not `root()`? From what I understand, this does the opposite from what I asked about

**Comment by frewsxcv** [comment]
From IRC:

> 11:24 PM <Ms2ger> frewsxcv, yes, it's possible to root() an Option, that's why I suggested it :)

This is the error I get:

```
/Users/coreyf/Development/rust/servo/components/script/dom/node.rs:844:11: 844:17 error: no method named `root` found for type `core::option::Option<dom::bindings::js::JS<dom::node::Node>>` in the current scope
/Users/coreyf/Development/rust/servo/components/script/dom/node.rs:844         }.root();
                                                                                 ^~~~~~
```

Do you have a link to the documentation where I can read where it's implemented?

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6536)

**Comment by frewsxcv** [comment]
From IRC:

```
11:32 PM <Ms2ger> Huh
11:32 PM <Ms2ger> I'm sure it was possible...
11:33 PM <Ms2ger> Where is mwu when you need him
11:34 PM <Ms2ger> Yeah, he removed it
11:34 PM <Ms2ger> That's inane
11:34 PM <Ms2ger> File an issue to bring that back, please
11:35 PM <Ms2ger> frewsxcv, in the meantime, .map(Root::from_rooted)
```

The error after making that change

```
/Users/coreyf/Development/rust/servo/components/script/dom/node.rs:844:11: 844:24 error: type mismatch: the type `fn(&dom::bindings::js::JS<_>) -> dom::bindings::js::Root<_> {dom::bindings::js::JS<T>::root}` implements the trait `for<'r> core::ops::FnOnce<(&'r dom::bindings::js::JS<_>,)>`, but the trait `core::ops::FnOnce<(dom::bindings::js::JS<dom::node::Node>,)>` is required (expected struct `dom::bindings::js::JS`, found &-ptr) [E0281]
/Users/coreyf/Development/rust/servo/components/script/dom/node.rs:844         }.map(JS::root);
                                                                                 ^~~~~~~~~~~~~
/Users/coreyf/Development/rust/servo/components/script/dom/node.rs:844:11: 844:24 error: type mismatch: the type `fn(&dom::bindings::js::JS<_>) -> dom::bindings::js::Root<_> {dom::bindings::js::JS<T>::root}` implements the trait `for<'r> core::ops::FnOnce<(&'r dom::bindings::js::JS<_>,)>`, but the trait `core::ops::FnOnce<(dom::bindings::js::JS<dom::node::Node>,)>` is required (expected struct `dom::bindings::js::JS`, found &-ptr) [E0281]
/Users/coreyf/Development/rust/servo/components/script/dom/node.rs:844         }.map(JS::root);
                                                                                 ^~~~~~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `script`
```

Can we keep the conversation on GitHub (or Reviewable) instead of IRC? It's much easier to follow and refer to

**Comment by Ms2ger** [comment]
Sure. Can you try doing what I suggested in the IRC comment you quote above?

**Comment by frewsxcv** [comment]
Ah sorry, pasted the wrong error (I was trying something else in my previous paste):

```
/Users/coreyf/Development/rust/servo/components/script/dom/node.rs:847:47: 847:70 error: mismatched types:
 expected `core::option::Option<&dom::node::Node>`,
    found `core::option::Option<dom::bindings::js::Root<dom::node::Node>>`
(expected &-ptr,
    found struct `dom::bindings::js::Root`) [E0308]
/Users/coreyf/Development/rust/servo/components/script/dom/node.rs:847         try!(Node::pre_insert(&node, &parent, viable_previous_sibling));
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by frewsxcv** [comment]
For this code:

```rust
        // Step 5.
        let viable_previous_sibling = match viable_previous_sibling {
            Some(ref viable_previous_sibling) => viable_previous_sibling.next_sibling.get(),
            None => parent.first_child.get(),
        }.map(Root::from_rooted);

        // Step 6.
        try!(Node::pre_insert(&node, &parent, viable_previous_sibling));

        Ok(())
```

**Comment by dzbarsky** [comment]
I think you need to do try!(Node::pre_insert(&node, &parent, viable_previous_sibling.r()));

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/node.rs, line 830 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6536#-JuGAz0Bv6igACrHcCLE)** ([raw file](https://github.com/servo/servo/blob/0fb2186306b781f2eb9c2418bf5ec23028cea30d/components/script/dom/node.rs#L830)):</sup>
Is this any closer?

```rust
nodes_nostrings.by_ref().all(|ref n| !n.IsEqualNode(Some(&sibling)))
```

I don't know what to make of  the statement "iterators don't work like that".

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6536)

**Comment by Ms2ger** [comment]
No, the issue is `by_ref`. You keep iterating over the same `Iterator` object, so for the second case, you get
1. `[a, b, c, --> d <--]`, compare to `c`, not a match
2. `[a, b, --> c <--, d]`, compare to `c`, match, continue
3. `[a, --> b <--, c, d]`, compare to `d`, not a match
4. `[--> a <--, b, c, d]`, compare to `d`, not a match
…and it sets the viable previous sibling to `d`.

**Comment by frewsxcv** [comment]
Just pushed with the error fixed that @Ms2ger pointed out above (including a regression test in the WPT suite). Sorry for the delay on this; I'm still on vacation so I haven't been dedicating too much time to the fine art of computering

**Comment by Ms2ger** [comment]
Don't worry, we should all spend more time away from our screens :)

**Comment by frewsxcv** [comment]
I'm thinking it might be easier if I justake the changes to ChildNode::after in conjunction with this. Maybe I'll do that on my flight today and open a new PR that succedes this

**Comment by frewsxcv** [comment]
Once https://github.com/servo/servo/pull/6786 lands, I'll open a new PR that also includes the changes for `ChildNode::after`. I need to wait for #6786 because of https://github.com/w3c/web-platform-tests/pull/2034

**Comment by frewsxcv** [comment]
> Once #6786 lands, I'll open a new PR that also includes the changes for ChildNode::after. 

Opeend #6800

**Pull request closed without merging**
