### PR TITLE
Optimize repetition in workflow configuration

### PR DESCRIPTION
**Pull request by yvt**
Replaces 20 CI jobs (`linux-wpt-{1, 2, ..., 20}`) with one with a build matrix.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

---
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they only affect the CI pipeline

### CODE REVIEW

**Comment by yvt** [comment]
Ah, I just learned that it's generated automatically. It might be helpful to add warnings to those generated files.

**Comment by jdm** [comment]
Ooh, the matrix does look nice. We should definitely incorporate that.

**Comment by yvt** [comment]
Can we remove the `main.yml` auto-generation? All it will do after this change is replacing placeholders (e.g., `${ REPOSITORY_NAME }`) with another placeholders (e.g., `${{ github.event.repository.name }}`).

**Comment by jdm** [comment]
Yeah, the only reason for the auto-generation was to avoid writing out repetitive blocks by hand.

**Comment by yvt** [comment]
The `main.yml` auto-generation has been removed. This is ready for review.

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Pull request merged**
