### PR TITLE
Halve number of processes for test runs.

### PR DESCRIPTION
**Pull request by jdm**
Let's see if this makes the intermittent failure situation improve!

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16176)

### CODE REVIEW

**Comment by glennw** [comment]
@bors-servo try

Let's measure what impact it has on test run time.

**Comment by jdm** [comment]
Linux CSS: before 13m, after 16m
Linux WPT: before 12m, after 18m
Mac WPT-1: before 8m, after 12m
Mac WPT-2: before 19m, after 35m
Mac CSS: before 27m, after 45m

**Comment by jdm** [comment]
Mac WPT2 and Mac CSS are _really_ bad with this change. The rest don't look like big deals.

**Comment by jdm** [comment]
Possibly we just leave the mac builders alone and only have the linux ones, since that's where the OSMesa perf problems hit us?

**Pull request merged**
