### PR TITLE
Net: removed opts::get() usage

### PR DESCRIPTION
**Pull request by oneturkmen**
Removed usage of opts::get() in components/net.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix *partially* #22854 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because these are cleanup/refactoring changes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23520)

### CODE REVIEW

**Review by jdm — CHANGES_REQUESTED** [review]
Let's remove the servo_config dependency from Cargo.toml as well.

**Comment by oneturkmen** [comment]
Travis and AppVeyor both failed due to the missing `servo_config` crate:

>error[E0463]: can't find crate for `servo_config`
  --> components/net/lib.rs:20:1
   |
20 | extern crate servo_config;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to previous error
For more information about this error, try `rustc --explain E0463`.
error: Could not compile `net`.
warning: build failed, waiting for other jobs to finish...
error: build failed
The command "./mach test-unit" exited with 101.

Should I add `servo_config` dependency back to Cargo.toml?

**Comment by jdm** [comment]
Ah, it's used by a unit test. Interesting.

**Comment by jdm** [comment]
Ok, go ahead and re-add the dependency and we can merge these changes.

**Comment by oneturkmen** [comment]
It's the unit tests again. Will adjust them tomorrow.

**Comment by oneturkmen** [comment]
@jdm fyi Travis seem to have finished the build [~4 hours ago](https://travis-ci.com/servo/servo/builds/114675108) - yet it shows "in progress" here.

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
