### PR TITLE
Adding method to detect if image formats should be supported by servo

### PR DESCRIPTION
**Pull request by craftytrickster**
https://github.com/servo/servo/issues/8406

Please let me know if I need to make any changes.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8503)

### CODE REVIEW

**Comment by mbrubeck** [comment]
This looks great, thanks!  r=mbrubeck with one trivial change (see below).

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/unit/net_traits/lib.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8503#-K2z84j3aev60yWhsu9s)** ([raw file](https://github.com/servo/servo/blob/af37d9f1deb711bcab76325a615371ffbccf1fed/tests/unit/net_traits/lib.rs#L7)):</sup>
Could you rename this file from `base` to `image`?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8503)

**Comment by craftytrickster** [comment]
@mbrubeck thanks for taking a look. When I have some time later I will make the changes. Just as a question, do you prefer that I do it as a second commit, or should I just force push and include it in a single commit?

**Comment by Ms2ger** [comment]
Feel free to force push; reviewable should handle that fine.

**Comment by craftytrickster** [comment]
I made the changes to the file name, but unfortunately the CI is failing now.

**Comment by jdm** [comment]
You'll need to run `./mach test-tidy` and fix the reported error, and then `./mach cargo-update -p net_traits_tests` should fix up the other errors.

**Comment by craftytrickster** [comment]
Thanks for the pointer, when I get home I can take a look at it.

**Comment by craftytrickster** [comment]
@jdm, running `./mach cargo-update -p net_traits_tests`, it gave me an error message saying that net_traits_tests were not found. Afterwards, I ran `./mach cargo-update -a results` and pushed the changes to the commit, but I am still failing CI. I am sorry to be a bother, but I am not sure what I need to do here.

**Comment by jdm** [comment]
Oh dear, `cargo-update -a` is never the right thing to do, unfortunately. We're going to need to revert all the changes to the various .lock files and try again.

**Comment by craftytrickster** [comment]
Locally, I deleted the cargo-update -a commit and then did the following:

`.....Inspiron-5521:~/Rust/servo$ ./mach cargo-update -p net_traits_tests`

This is the exact error message I get (I should've included in my other comment)
```
components/servo
package id specification `net_traits_tests` matched no packages
ports/cef
package id specification `net_traits_tests` matched no packages
ports/gonk
package id specification `net_traits_tests` matched no packages
```

**Comment by jdm** [comment]
Confusing! Try `./mach build --android` and `GONKDIR=/tmp ./mach build-gonk` and cancel each one after you see any output?

**Comment by craftytrickster** [comment]
I just tried rebuilding again and I tried your command - it now returned the following message, which seems more promising:

components/servo
      Adding bitflags v0.3.2
ports/cef
package id specification `net_traits_tests` matched no packages
ports/gonk
package id specification `net_traits_tests` matched no packages

**Comment by craftytrickster** [comment]
Thanks @jdm, it worked!

**Comment by craftytrickster** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/unit/net_traits/lib.rs, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8503#-K2z84j3aev60yWhsu9s)** ([raw file](https://github.com/servo/servo/blob/af37d9f1deb711bcab76325a615371ffbccf1fed/tests/unit/net_traits/lib.rs#L7)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8503)

**Comment by mbrubeck** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8503)

**Comment by mbrubeck** [comment]
@bors-servo r+

Thanks again :)

**Pull request merged**
