### PR TITLE
Update webdriver

### PR DESCRIPTION
**Pull request by georgeroman**
Updating `webdriver` raises the following tidy errors, which I'm not sure how to fix:
`` ./Cargo.lock:1: duplicate versions for package `mime` ``
`` ./Cargo.lock:1: duplicate versions for package `mime_guess` ``
`` ./Cargo.lock:1: duplicate versions for package `log` ``
`` ./Cargo.lock:1: Package multipart 0.16.1 depends on blocked package rand. ``
`` ./Cargo.lock:1: Package tungstenite 0.8.1 depends on blocked package rand. ``

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23941)

### CODE REVIEW

**Comment by Eijebong** [comment]
Ouch these dupes... :(

Need to update `mime` and `mime_guess` in `multipart`, get it released and if it's a breaking change update that in `warp` and get that released. Wonder why I didn't see that when I got warp into firefox... Guess it still depends on log 0.3 because of other things...

I'll look into fixing that tomorrow if it's not been done already

**Comment by Eijebong** [comment]
If this is really blocking you can allow those dupes in `servo-tidy.toml`

**Comment by georgeroman** [comment]
Oh, great, I'll probably do that.

**Pull request merged**
