### PR TITLE
Ensure subpath for control point of CanvasRenderingContext2D.quadraticCurveTo()

### PR DESCRIPTION
**Pull request by pylbrecht**
These changes are based on #25444.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #25331

- [x] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /offscreen-canvas/path-objects/2d.path.quadraticCurveTo.ensuresubpath.2.worker.html:
  └ PASS [expected FAIL] If there is no subpath, the first control point is added
```

**Comment by pylbrecht** [comment]
Sorry, missed that file.

**Review by jdm — APPROVED** [review]

**Pull request merged**
