### PR TITLE
Update cssparser.

### PR DESCRIPTION
**Pull request by SimonSapin**
https://github.com/servo/rust-cssparser/pull/91

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9380)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
failed to select a version for `selectors` (required by `util`):
all possible versions conflict with previously selected versions of `selectors`
  version 0.2.2 in use by selectors v0.2.2
  possible versions to select: 0.2.3
```

I can’t reproduce locally and don’t understand how this happens with 0.2.3 in the lock file, but I’ll try to bump the requirement in `Cargo.toml`.

**Comment by SimonSapin** [comment]
I haven’t managed to reproduce this issue on the builder. This worked fine:
```
ssh servo-mac3.servo.org
su servo
cd /Users/servo/buildbot/slave/mac-dev-unit/build
CARGO_HOME=/Users/servo/.cargo SERVO_CACHE_DIR=/Users/servo/.servo ./mach build-geckolib

**Comment by SimonSapin** [comment]
Retry just in case something has changed, and also to make buildbot spin up EC2 builders so that I can investigate another issue.

@bors-servo retry

**Comment by SimonSapin** [comment]
@alexcrichton any idea what the error above could be? The lock file is up to date and 0.2.2 is not mentioned in it.

**Comment by alexcrichton** [comment]
This may either be a bug or indicative of the lock file not being up to date (although if you've confirmed the lock file is up to date it may be the former). Is there a way I could reproduce myself?

**Comment by metajack** [comment]
cc @alexcrichton 

This looks like a cargo bug.

**Comment by alexcrichton** [comment]
This looks like you just need to rebase the branch, the `Cargo.lock` patch applies but there has been changes in the meantime which means that it's basically a corrupt `Cargo.lock`

**Comment by metajack** [comment]
@alexcrichton I don't understand, this builds fine with cargo on 4 other machines, but fails only on this one. Cargo.lock is checked into git so I don't see how it could be corrupted on one machine and not another.

**Comment by alexcrichton** [comment]
I'm not sure other machines are failing, but the [`Cargo.lock` on master](https://github.com/servo/servo/blob/master/ports/geckolib/Cargo.lock) has `selectors 0.2.2` under the `geckoservo` crate yet [the one on @SimonSapin's branch](https://github.com/servo/servo/blob/cssparserup/ports/geckolib/Cargo.lock) does not. This means that @SimonSapin's patch does not modify the `selectors 0.2.2` dependency `geckoservo`.

When I say corrupt I don't mean that the TOML syntax is invalid, I just mean that there are two patches to `Cargo.lock` (both of which apply cleanly) which have made the state of the lock file invalid. The lock file cannot mention both `foo 2.2.2` and `foo 2.2.3` because these versions conflict, but if you take the patch in this PR and apply it to master, that's what you get.

I believe if @SimonSapin rebases this PR and re-runs `cargo update` then it should do the trick.

**Comment by metajack** [comment]
@alexcrichton I appreciate that explanation, and upon double checking I see it is indeed failing on all hte machines in that run. For some reason homu only posted one log.

**Comment by alexcrichton** [comment]
Oh oops I realize now when I said "I'm not sure other machines are failing" I meant to say "I'm not sure why the other machines are failing", sorry if that caused any confusion!

**Comment by SimonSapin** [comment]
> This looks like you just need to rebase the branch, the Cargo.lock patch applies but there has been changes in the meantime which means that it's basically a corrupt Cargo.lock

This makes sense. When trying to reproduce I was using the branch, never a merge of the branch with master. I’ll try that tomorrow.

**Comment by SimonSapin** [comment]
Here is what I did:

* Checkout this PR’s branch, geckolib builds fine
* Fetch upstream and rebase unto upstream/master. Now I can reproduce the issue.
* Run `./mach cargo-update -p selectors`. The same error message shows up for `ports/geckolib`.
* Look at `ports/geckolib/Cargo.lock`. It declares a dependency on `selectors 0.2.2`, but there is not `[[package]]` section for it. Change it manually to 0.2.3.
* Build again, the problem seems to be fixed.

@bors-servo r+

So the moral of the story is:

* CI doesn’t test your PR, it tests a merge of your PR into master. Thanks Alex for pointing this out! When something only happens on CI, rebasing may help.
* A git merge of branches that both have changes to `Cargo.lock` can result in an inconsistent `Cargo.lock` file. I’ll file an issue about making Cargo more robust in that situation.

**Comment by SimonSapin** [comment]
Fixed duplicate dependency introduced in the rebase.

@bors-servo r+

**Comment by SimonSapin** [comment]
Cargo bug: https://github.com/rust-lang/cargo/issues/2302. This needs at least a better error message, if not automatic resolution.

**Pull request merged**
