### PR TITLE
Update darling to 0.9

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23437)

### CODE REVIEW

**Comment by jdm** [comment]
```
+ ./etc/ci/lockfile_changed.sh
diff --git a/Cargo.lock b/Cargo.lock
index 1da3d0aa8..d88ecbabd 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -952,7 +952,7 @@ source = "registry+https://github.com/rust-lang/crates.io-index"
 dependencies = [
  "proc-macro2 0.4.26 (registry+https://github.com/rust-lang/crates.io-index)",
  "quote 0.6.3 (registry+https://github.com/rust-lang/crates.io-index)",
- "syn 0.15.22 (registry+https://github.com/rust-lang/crates.io-index)",
+ "syn 0.15.34 (registry+https://github.com/rust-lang/crates.io-index)",
 ]
 
 [[package]]
```

**Comment by Eijebong** [comment]
Rebased

**Pull request merged**
