### PR TITLE
Make it possible to use a custom AAR to build servoapp

### PR DESCRIPTION
**Pull request by paulrouget**
Fix https://github.com/servo/servo/issues/21402

To use a local AAR, create `support/android/apk/user.properties`:
```
servoViewLocal=/tmp/servo-latest.aar
```

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21404)

### CODE REVIEW

**Comment by paulrouget** [comment]
@MortimerGoro  r?

I reused the mechanism found in FirefoxReality.

**Comment by paulrouget** [comment]
To add to the wiki:

## Working on the user interface without building Servo

We provide nightly builds of a servo library for android, so it's not necessary to do a full build to work on the user interface.

- Download the latest AAR: https://download.servo.org/nightly/android/servo-latest.aar (this is an armv7 build)
- In your local copy of Servo, create a file `support/android/apk/user.properties` and specify the path to the AAR you just downloaded: `servoViewLocal=/tmp/servo-latest.aar`
- open `support/android/apk` with Android Studio
- *important*: in the project list, you should see 2 projects: `servoapp` and `servoview-local`. If you see `servoapp` and `servoview` that means Android Studio didn't correctly read the settings. Re-sync gradle or restart Android Studio
- select the build variant `mainArmv7Debug` or `mainArmv7Release`
- plug your phone
- press the Play button

Alternatively, you can generate the APK with the command line: `./gradlew :servoapp:assembleMainArmv7Release`

The relevant files to tweak the UI are: MainActivity.java and activity_main.xml

**Comment by MortimerGoro** [comment]
@paulrouget LGTM

**Comment by paulrouget** [comment]
https://github.com/servo/servo/issues/21406

**Comment by jdm** [comment]
@bors-servo retry
* #20734

**Pull request merged**
