### PR TITLE
Implement CanvasRenderingContext2D.font property

### PR DESCRIPTION
**Pull request by pylbrecht**
These changes implement the font property of the Canvas 2D API.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix part of #25331

- [x] There are tests for these changes

### CODE REVIEW

**Comment by pylbrecht** [comment]
I just started looking into this, but I opened this PR for tracking progress. Definitely have to wrap my head around how the property's value is parsed as a CSS `<'font'>` as described [in this comment](https://github.com/servo/servo/issues/11681#issuecomment-586763530) first.

**Comment by pylbrecht** [comment]
I've been a bit busy with applications and job interviews lately, but there's a good chance I get to work on this on the weekend!

**Comment by pylbrecht** [comment]
I investigated a bit more and am currently facing a problem:

How should the `font` attribute be stored in the [`CanvasContextState`](https://dxr.mozilla.org/servo/source/components/script/canvas_state.rs#74)?

Currently I use [`style::properties::shorthands::font::parse_value()`](https://doc.servo.org/style/properties/shorthands/font/fn.parse_value.html) to parse the `DOMString` in [`CanvasState::set_font()`](https://github.com/servo/servo/pull/26176/files#diff-587cd504daeade12b5ea90149c65788dR1594), which gives me a [`style::properties::shorthands::font::Longhands`](https://doc.servo.org/style/properties/shorthands/font/struct.Longhands.html). This struct holds all relevant information about the font.

I tried to just add a `font` member to `CanvasContextState` of type `style::properties::shorthands::font::Longhands`, but this results in a lot of issues due to missing trait implementations, which I'm not really comfortable implementing:
```
error[E0277]: the trait bound `style::properties::shorthands::font::Longhands: std::clone::Clone` is not satisfied
   --> components/script/canvas_state.rs:100:5
    |
100 |     font: font::Longhands,
    |     ^^^^^^^^^^^^^^^^^^^^^ the trait `std::clone::Clone` is not implemented for `style::properties::shorthands::font::Longhands`
    |
    = note: required by `std::clone::Clone::clone`
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `trace` found for reference `&style::properties::shorthands::font::Longhands` in the current scope
   --> components/script/canvas_state.rs:84:17
    |
84  | #[derive(Clone, JSTraceable, MallocSizeOf)]
    |                 ^^^^^^^^^^^ method not found in `&style::properties::shorthands::font::Longhands`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `dom::bindings::trace::JSTraceable` defines an item `trace`, perhaps you need to implement it
   --> components/script/dom/bindings/trace.rs:165:1
    |
165 | pub unsafe trait JSTraceable {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `style::properties::shorthands::font::Longhands: malloc_size_of::MallocSizeOf` is not satisfied
  --> components/script/canvas_state.rs:84:30
   |
84 | #[derive(Clone, JSTraceable, MallocSizeOf)]
   |                              ^^^^^^^^^^^^ the trait `malloc_size_of::MallocSizeOf` is not implemented for `style::properties::shorthands::font::Longhands`
   |
   = note: required by `malloc_size_of::MallocSizeOf::size_of`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
How would I work around this?

Right now I'm thinking of introducing a new `FontProperties` struct in [`canvas_state.rs`](https://dxr.mozilla.org/servo/source/components/script/canvas_state.rs) to store `Longhands`' members in `CanvasContextState`. Then I hopefully would be able to just `#[derive ...]` and `#[ignore_malloc_size_of = ...]` on `FontProperties` to get rid of the issues.

I'll try that idea the next days, but I'm open for input, if there's a better way to approach this.

**Comment by jdm** [comment]
Ok, there are a few things here.
1. the MallocSizeOf and JSTraceable errors aren't difficult to get around (You can use `#[ignore_malloc_size_of = ""]` and add a `unsafe_no_jsmanaged_fields!` entry in [this code](https://github.com/servo/servo/blob/e697e6cca70bec57b5ed9512b95c2a72359d6ca1/components/script/dom/bindings/trace.rs#L198))
1. looking more closely at the gecko code, we need to not just parse the CSS value, but also resolve it and obtain computed values (like in [this code](https://searchfox.org/mozilla-central/rev/55a4faa52f72918efa51150d127aebdc057dc6cf/dom/canvas/CanvasRenderingContext2D.cpp#2272-2306)). This will help us, because the types for computed values are cloneable (eg. https://doc.servo.org/style/values/computed/font/struct.FontFamily.html).

To turn the specified parsed values into computed values, I think we need to add a new layout query which will:
1. send a message to the layout thread with the canvas element and the unparsed font value
1. when processing the layout query, parse the font value into the longhands, then use [`ToComputedValue::to_computed_value`](https://doc.servo.org/style/values/computed/trait.ToComputedValue.html) on the longhand values that we need
1. use the font cache thread to load the resolved font and obtain the bytes from the resulting font
1. make the query result be the font bytes, and store those in the CanvasState

Having the font bytes available means we can send them to the canvas rendering thread and use Font::from_bytes from font-kit to create a font that we can pass to raqote.

**Comment by pylbrecht** [comment]
Oh wow, thanks a lot! I would have never figured this out by myself.
I will take a closer look into it the next days.

**Comment by pylbrecht** [comment]
Aside from implementing `process_canvas_font_request()`, I don't really know how to make a `QueryMsg::CanvasFontQuery` from inside the canvas thread.

I didn't have to work across threads so far, so this is new to me.
By reading some code I'm sensing that I need some kind of channel (send/recv), but I'm not sure if there's already something in place to communicate with layout or if I have to add this by myself.

**Comment by jdm** [comment]
Why is the canvas thread triggering the query? We should be able to start it in the script thread when JS invokes SetFont.

**Comment by pylbrecht** [comment]
That's true, I haven't thought about this.. just to check: you mean in `CanvasRenderingContext2DMethods::SetFont()`?

How do I make a query from script to layout then?

**Comment by jdm** [comment]
Take a look at how Window::GetComputedStyle is implemented, since that also performs a layout query.

**Comment by jdm** [comment]
And yes, that is the SetFont that I meant.

**Comment by pylbrecht** [comment]
While looking at https://searchfox.org/mozilla-central/source/dom/canvas/CanvasRenderingContext2D.cpp#2272-2282 and searching Servo's docs, I found [`Window::GetComputedValue()`](https://dxr.mozilla.org/servo/source/components/script/dom/window.rs#1090) and looking at the code of that method brought me to [`CSSStyleDeclaration::get_computed_value()`](https://dxr.mozilla.org/servo/source/components/script/dom/cssstyledeclaration.rs#237).

I want to get the `parentStyle` in `CanvasRenderingContext2D::SetFont()` by leveraging one of these methods, but without any success so far.
`CSSStyleDeclaration::get_computed_value()` is private and in case of `Window::GetComputedValue()` I don't know how to get the `Window` instance of the canvas element in `CanvasRenderingContext2D::SetFont()`.

Does this approach to get the `parentStyle` make any sense?

**Comment by pylbrecht** [comment]
@jdm helped me out on [Matrix](https://chat.mozilla.org/#/room/#servo:mozilla.org), so my question from the previous comment is answered for now.

**Comment by pylbrecht** [comment]
One more thing: [`Window::GetComputedStyle()`](https://doc.servo.org/script/dom/window/struct.Window.html#method.GetComputedStyle) takes a `dom::element::Element` and I don't know how to convert a `CanvasRenderingContext2D` to `Element` to pass it to the method.

**Comment by pylbrecht** [comment]
Working on this feels a little frustrating and since I'm starting a full-time job next week, I will step back from contributing for now. I may come back to work on Servo issues once I accustomed myself to the new schedule, but for now I'll be focusing my efforts on the new job.

**Pull request closed without merging**
