### PR TITLE
GetImageData should return un-premultiplied alpha values

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6970)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Using a `for` loop seems clearer than this `last()` call.

**Comment by Ms2ger** [comment]
Clearly I'm not communicating very well.
```rust
for chunk in data.chunks_mut(4) {
    let alpha = chunk[3] as f32 / 255.;
    chunk[0] = (chunk[0] as f32 / alpha) as u8;
    chunk[1] = (chunk[1] as f32 / alpha) as u8;
    chunk[2] = (chunk[2] as f32 / alpha) as u8;
}
```

**Comment by dzbarsky** [comment]
You're right, that's much clearer.

**Pull request merged**
