### PR TITLE
Correctly handle length-changing mappings in text-transform

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7251)

### CODE REVIEW

**Comment by Ms2ger** [comment]
The `lower-case` change doesn't fix any test?

**Comment by nox** [comment]
@Ms2ger No, do you know of any length-changing lowercase mapping so I add one?

**Comment by nox** [comment]
Didn't find any in SpecialCasing.txt.

**Comment by Ms2ger** [comment]
Looks like U+0130 is the only one where Rust yields two chars: i + 'COMBINING DOT ABOVE' (U+0307); I can only see the difference by increasing the font size quite a bit, though.

**Comment by nox** [comment]
@Ms2ger Will try to make a test for this one. I wanted a case like ß -> SS where even the number of graphemes change.

**Comment by nox** [comment]
Cc @pcwalton.

**Comment by jdm** [comment]
This added a new test to tests/wpt/css-tests/. Is that allowed, @Ms2ger?

**Comment by Ms2ger** [comment]
I already clobbered it in f235d49372ba86d6d01530fe1b9ebdf8bea74468, so no :)

**Pull request merged**
