### PR TITLE
Fix several hangs / panics during pipeline cleanup of in progress loads.

### PR DESCRIPTION
**Pull request by glennw**
This fixes a hang found while testing the jQuery test suite.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6131)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- components/compositing/compositor_task.rs @ r1
- components/gfx/paint_task.rs @ r1
- components/layout/layout_task.rs @ r1
- components/msg/constellation_msg.rs @ r1
- components/script/dom/window.rs @ r1
- components/script/script_task.rs @ r1
- components/util/task.rs @ r1

---

<sup>**[components/script/script_task.rs, line 1089 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6131#-JphgHpfXo-_36AVspFG)** ([raw file](https://github.com/servo/servo/blob/35a570ab66227fb640e64bd50373f1e1a9f51b22/components/script/script_task.rs#L1089)):</sup>
This comment's position is misleading now.

---

<sup>**[components/script/script_task.rs, line 1097 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6131#-JphgbcP3Yliw9bUBm8u)** ([raw file](https://github.com/servo/servo/blob/35a570ab66227fb640e64bd50373f1e1a9f51b22/components/script/script_task.rs#L1097)):</sup>
This is not necessarily the root.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6131)

**Comment by glennw** [comment]
Review status: 6 of 7 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/script_task.rs, line 1089 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6131#-JphgHpfXo-_36AVspFG)** ([raw file](https://github.com/servo/servo/blob/35a570ab66227fb640e64bd50373f1e1a9f51b22/components/script/script_task.rs#L1089)):</sup>
Done.

---

<sup>**[components/script/script_task.rs, line 1097 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6131#-JphgbcP3Yliw9bUBm8u)** ([raw file](https://github.com/servo/servo/blob/35a570ab66227fb640e64bd50373f1e1a9f51b22/components/script/script_task.rs#L1097)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6131)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/script/script_task.rs @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6131)

**Pull request merged**
