### PR TITLE
Update Stylo bindings for new LookAndFeel_ColorID variants.

### PR DESCRIPTION
**Pull request by SimonSapin**
https://bugzilla.mozilla.org/show_bug.cgi?id=1344910

`target.stylo-bindings.zip` from https://treeherder.mozilla.org/#/jobs?repo=try&revision=d35e6682f1c7c3ccdea55522127c132cedc5878f&selectedJob=108852561

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17449)

### CODE REVIEW

**Comment by SimonSapin** [comment]
r? @emilio 

This is more changes than I expected, but maybe that’s ok?

Looks like bug 1344910 which adds these variants was backed out. This PR should land at roughly the same time.

**Comment by SimonSapin** [comment]
CC @jwatt

**Comment by SimonSapin** [comment]
@bors-servo r-

Thanks for the review @emilio. Corresponding Gecko patches are not in autoland yet. @jwatt, let me know when you’re ready.

**Comment by SimonSapin** [comment]
@jwatt Stylo doesn’t build with bindings from https://treeherder.mozilla.org/#/jobs?repo=try&revision=1840ad15d7ca5b86501f08dbd0b0b8231b87e558. Please make another try push rebased on top of a more recent m-c.

**Comment by jwatt** [comment]
Hi. The commit I emailed you was more up-to-date. Can you try that?

https://treeherder.mozilla.org/#/jobs?repo=try&revision=b932f35355ef2376d0b08f85f6ce83bd7e28c6d9

**Comment by SimonSapin** [comment]
Nope, still the same errors like ``unresolved import `gecko_bindings::bindings::Gecko_ConstructStyleChildrenIterator` ``. This change likely landed around the same time https://github.com/servo/servo/pull/17541. Maybe it’s not in central yet? Try on top of https://hg.mozilla.org/integration/autoland ?

**Comment by jwatt** [comment]
Ah, yeah, that hadn't yet merged to inbound. This should work now:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=2abbf9efe32f8aa2eec85a925b3a8d86ae13da03

**Comment by SimonSapin** [comment]
Builds on my machine.

@bors-servo try

**Comment by SimonSapin** [comment]
```
./mach test-stylo

[…]

failures:

---- bindings::root::mozilla::dom::bindgen_test_layout_AllChildrenIterator stdout ----
	thread 'bindings::root::mozilla::dom::bindgen_test_layout_AllChildrenIterator' panicked at 'assertion failed: `(left == right)` (left: `88`, right: `80`): Size of: AllChildrenIterator', /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/style-3913691f712134c6/out/gecko/structs_debug.rs:6448
[…]

---- bindings::root::mozilla::dom::bindgen_test_layout_FlattenedChildIterator stdout ----
	thread 'bindings::root::mozilla::dom::bindgen_test_layout_FlattenedChildIterator' panicked at 'assertion failed: `(left == right)` (left: `48`, right: `40`): Size of: FlattenedChildIterator', /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/style-3913691f712134c6/out/gecko/structs_debug.rs:6400
stack backtrace:
[…]

---- bindings::root::mozilla::dom::bindgen_test_layout_StyleChildrenIterator stdout ----
	thread 'bindings::root::mozilla::dom::bindgen_test_layout_StyleChildrenIterator' panicked at 'assertion failed: `(left == right)` (left: `88`, right: `80`): Size of: StyleChildrenIterator', /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/style-3913691f712134c6/out/gecko/structs_debug.rs:5492
[…]

failures:
    bindings::root::mozilla::dom::bindgen_test_layout_AllChildrenIterator
    bindings::root::mozilla::dom::bindgen_test_layout_FlattenedChildIterator
    bindings::root::mozilla::dom::bindgen_test_layout_StyleChildrenIterator

test result: FAILED. 822 passed; 3 failed; 0 ignored; 0 measured
```

**Comment by emilio** [comment]
You need to rebase on top of autoland, @heycam fixed that, see #17541

**Comment by SimonSapin** [comment]
@jwatt Sounds like you need yet another try push, sorry.

**Comment by jwatt** [comment]
No worries, I really appreciate your help.

https://treeherder.mozilla.org/#/jobs?repo=try&revision=503fbd76fa447c21314433b45f7001ea3f258365

**Comment by SimonSapin** [comment]
This is still failing some `size_of` tests :/ @emilio, any suggestion?

**Comment by jwatt** [comment]
I think @emilio landed everything that needs to be landed here and this can be closed.

Thank you @SimonSapin and @emilio for your help in getting my patches landed. It was a bit painful so much appreciated!

**Pull request closed without merging**
