### PR TITLE
Add border to improve apperance on dark background

### PR DESCRIPTION
**Pull request by ojab**
Before/after comparison on Mac OS X dock w/ dark theme: https://imgur.com/a/atI6l

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11473)

### CODE REVIEW

**Comment by mbrubeck** [comment]
I'm no graphic designer, but my first impression is that this is a little too bold.  Would a soft glow work, like a light-colored drop shadow?

**Comment by ojab** [comment]
Updated the PR, new image is the bottom one: https://imgur.com/a/QJfKN.

**Comment by ojab** [comment]
…and removed border on doge (so only sprocket has border), last one is top one: http://imgur.com/a/JkclL.

**Comment by mbrubeck** [comment]
I think I'd prefer a glow or drop-shadow that is behind the logo, so that it doesn't change the look at all on a white background. Right now it makes the Rust "gear" look a little fuzzy-edged at certain sizes especially on light backgrounds, and creates some odd effects where the white lines stop, like here:

closeup

Here's an example with a white drop-shadow against a dark background:

glow

The same thing might work well with a sharper outline placed behind the image, for a less glowy effect.

**Comment by larsbergstrom** [comment]
I like @mbrubeck's suggestion, provided that it also looks good on a light background.

Adding @zmike, the original creator of the icon, for his thoughts.

**Comment by zmike** [comment]
After examining the issue further and with a number of unmentioned background colors (e.g., black http://i.imgur.com/HstiKls.png), I think this is a good solution:

http://i.imgur.com/KywilZT.png

It's a bit more subtle than the other images posted here, allowing the emphasis to remain on the logo itself rather than having the eyes drawn to the outline effect.

**Comment by jdm** [comment]
We should make a decision here :)

**Comment by mbrubeck** [comment]
As the randomly-selected reviewer, I propose checking in @zmike's version. It's very similar to @ojab's latest, but fixes some minor artifacts and fuzziness.  Any objections?

And by the way, thank you @ojab for filing this issue; any of these are a big improvement on dark backgrounds!

**Comment by ojab** [comment]
@zmike's version is too subtle and barely visible on HiDPI screen w/ native resolution (i. e. not 2x) here, but I assume that it's not so common setup
It looks better in default setup, so I think that it's the right choice.

**Comment by mbrubeck** [comment]
@zmike, want to file a new PR for that?

**Comment by Coder206** [comment]
Please keep me posted on this. I am planning on implementing this on Windows, a requirement is to have it converted to ".ico", so I would like to use this new icon :)

**Pull request closed without merging**
