### PR TITLE
Implement ::selection pseudo-element

### PR DESCRIPTION
**Pull request by emilio**
It only supports `color` and `background`, for now, but it shouldn't be hard to add more properties (like text-shadow).

r? @mbrubeck

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10252)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed 2 of 9 files at r1, 1 of 1 files at r3.
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/layout/construct.rs, line 590 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10252#-KDzuyYxccRnMEHZ1lFe:-KDzuyYxccRnMEHZ1lFf:511371627) ([raw file](https://github.com/servo/servo/blob/3245dd4261ff7507bdc5dd1a208843159a8cb505/components/layout/construct.rs#L590)):*
Should this be `node.selected_style().clone()`?  It can matter even for whitespace fragments, because they need to draw their background when selected.

---

*[components/layout/construct.rs, line 1870 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10252#-KDzvkBL7tgxHJW-QZTW:-KDzvkBMzJeWxUebIMhv:478632471) ([raw file](https://github.com/servo/servo/blob/3245dd4261ff7507bdc5dd1a208843159a8cb505/components/layout/construct.rs#L1870)):*
You can add a `selected_style` field to `InlineFragmentNodeInfo` and read it here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252)*

**Comment by emilio** [comment]
Review status: 2 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/layout/construct.rs, line 590 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10252#-KDzuyYxccRnMEHZ1lFe:-KE--XphsJgtG0WzrKmN:50720977) ([raw file](https://github.com/servo/servo/blob/3245dd4261ff7507bdc5dd1a208843159a8cb505/components/layout/construct.rs#L590)):*
True, sorry, didn't realize `node` was in scope (small screen + massive function + not used to this part of the code...).

Done

---

*[components/layout/construct.rs, line 1870 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10252#-KDzvkBL7tgxHJW-QZTW:-KE--hLRDvu0LJHDHb-i:-499146009) ([raw file](https://github.com/servo/servo/blob/3245dd4261ff7507bdc5dd1a208843159a8cb505/components/layout/construct.rs#L1870)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252)*

**Comment by mbrubeck** [comment]
Reviewed 6 of 9 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/layout/fragment.rs, line 89 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-ZQ0H19yCUEzwf_n-:-KE-ZQ0I7jBL0jataVx_:2089185995) ([raw file](https://github.com/servo/servo/blob/bdc5f49345a520b72099b4d97d036482094937c0/components/layout/fragment.rs#L89)):*
Any ideas for ways we could implement this without making the `Fragment` struct bigger, either now or in follow-up work?  Maybe we could put the selected styles into a new field in the existing `ComputedValues`?  Or compute it on demand based on the Fragment's `inline_context` field? (Are selected elements always in an inline flow?  Hmm, probably not.)

Adding a field to `inline_context` also makes `Fragment` bigger, but there's an existing FIXME about moving that to InlineFlow.

---

*[components/layout/generated_content.rs, line 441 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-SBq8D4I7-pEnCWWo:-KE-SBq8D4I7-pEnCWWp:567009271) ([raw file](https://github.com/servo/servo/blob/3245dd4261ff7507bdc5dd1a208843159a8cb505/components/layout/generated_content.rs#L441)):*
We could change this function to accept a `selected_style` argument.  (It's probably not useful yet, since I don't think we have any way to select generated content, but it will be eventually.)

---

*[components/layout/inline.rs, line 1854 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-fjp-TETLxpXtvx7q:-KE-fjp02G8cueWAD_Yh:100205297) ([raw file](https://github.com/servo/servo/blob/bdc5f49345a520b72099b4d97d036482094937c0/components/layout/inline.rs#L1854)):*
I know I suggested this, but now I'm having second thoughts.  As mentioned above, this makes `Fragment` bigger which we should avoid if possible.  If this is used only for `control_chars_to_fragment` then we could just remove it again, since these bidi control chars are not printable, and get stripped out during text layout.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/layout/fragment.rs, line 89 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-ZQ0H19yCUEzwf_n-:-KE1P5NGXnh9u7yNh2i_:274844065) ([raw file](https://github.com/servo/servo/blob/bdc5f49345a520b72099b4d97d036482094937c0/components/layout/fragment.rs#L89)):*
At first I tried to get it on-demand, but I didn't find any way to get the layout data associated with the node once we're on the display list building phase without passing it inside `Fragment`.

The first option I thought was making `Selection` a real pseudo-element, but after fiddling around with it for a while my impression is that  our existing code for pseudo-elements isn't prepared for a pseudo-element that "wraps" a fragment (and possibly multiple ones) from the parent, and that `::selection` seems to be a really special case for this.

Also, if we did that that way, we'd still need both the `ComputedValues` for `::selection` and those for the node, or a "merge" of those, since `::selection` should only change a few properties.

I haven't done enough layout to see if I'm right or not though, so if you know a way this could work, I'm happy to experiment with it.

Adding the selected styles in the current `ComputedValues` could be good enough, but I'm not sure how it could be done easily.

---

*[components/layout/generated_content.rs, line 441 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-SBq8D4I7-pEnCWWo:-KE1PJD2GGib0T1QnjFG:2046884018) ([raw file](https://github.com/servo/servo/blob/3245dd4261ff7507bdc5dd1a208843159a8cb505/components/layout/generated_content.rs#L441)):*
I thought about it, and I saw that neither Gecko nor Blink allow selecting generated content. It's fine to add the parameter if you prefer it though.

---

*[components/layout/inline.rs, line 1854 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-fjp-TETLxpXtvx7q:-KE1P_AdLo4RAh4s4Z9_:-46811442) ([raw file](https://github.com/servo/servo/blob/bdc5f49345a520b72099b4d97d036482094937c0/components/layout/inline.rs#L1854)):*
Reverting, no problem :P

Anyway, I don't think that makes `Fragment` bigger, since `InlineFragmentNodeInfo` is stored on a `Vec` inside `InlineFragmentContext`, not directly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252)*

**Comment by emilio** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/layout/inline.rs, line 1854 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-fjp-TETLxpXtvx7q:-KE1aFF4kyUuEmf-jCQJ:-1131589302) ([raw file](https://github.com/servo/servo/blob/bdc5f49345a520b72099b4d97d036482094937c0/components/layout/inline.rs#L1854)):*
Pushed the revert commit instead of squashing them, just in case it needs to be re-reverted, I'll squash if r+'d

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252)*

**Comment by mbrubeck** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/layout/fragment.rs, line 89 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-ZQ0H19yCUEzwf_n-:-KE1fgSORXk30J451l6m:-611146624) ([raw file](https://github.com/servo/servo/blob/bdc5f49345a520b72099b4d97d036482094937c0/components/layout/fragment.rs#L89)):*
I don't have any immediate ideas. I'm happy to leave this as a possible follow-up optimization if @pcwalton agrees.

> Also, if we did that that way, we'd still need both the ComputedValues for ::selection and those for the node, or a "merge" of those, since ::selection should only change a few properties.

Yes, I envisioned adding a new style struct for selection properties, with only the handful of supported properties.

> Adding the selected styles in the current ComputedValues could be good enough, but I'm not sure how it could be done easily.

@SimonSapin, any thoughts on this?

---

*[components/layout/generated_content.rs, line 441 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-SBq8D4I7-pEnCWWo:-KE1fRZtpwFOSmtFxT2P:130511080) ([raw file](https://github.com/servo/servo/blob/3245dd4261ff7507bdc5dd1a208843159a8cb505/components/layout/generated_content.rs#L441)):*
Oh, in that case never mind.

---

*[components/layout/inline.rs, line 1854 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-fjp-TETLxpXtvx7q:-KE1fCl9LHdkIZ2QgTvv:1312592044) ([raw file](https://github.com/servo/servo/blob/bdc5f49345a520b72099b4d97d036482094937c0/components/layout/inline.rs#L1854)):*
Oops, you're right. Please un-revert. Sorry. :P

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252)*

**Comment by SimonSapin** [comment]
Review status: 2 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/layout/fragment.rs, line 89 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-ZQ0H19yCUEzwf_n-:-KE1z6RKrI-u96zNF43d:1096448498) ([raw file](https://github.com/servo/servo/blob/bdc5f49345a520b72099b4d97d036482094937c0/components/layout/fragment.rs#L89)):*
I don’t have any immediate ideas either, sorry. How does Gecko do this?

> Adding the selected styles in the current `ComputedValues`

I’m mildly opposed to this as it mixes up unrelated concepts.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252)*

**Comment by emilio** [comment]
Review status: 2 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/layout/fragment.rs, line 89 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10252#-KE-ZQ0H19yCUEzwf_n-:-KE20E8AAC0Oyl2VXQrS:1159672506) ([raw file](https://github.com/servo/servo/blob/bdc5f49345a520b72099b4d97d036482094937c0/components/layout/fragment.rs#L89)):*
Gecko code: https://github.com/mozilla/gecko-dev/blob/e8a838517a32b4c3d6a39acdc6186d8db4641ed7/layout/generic/nsTextFrame.cpp#L3785-L3809

It appears it computes it on demand, the text frame has access to the presentation context, and also to the element it belongs to, and gathers the styles from there.

It'd be equivalent for us to have access to the node and to its style data from the text fragment, which is what I had in mind initially, but doesn't seem easy/safe to convert the opaque node into the `LayoutNode` to get the `PseudoElement` style from there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252)*

**Comment by mbrubeck** [comment]
After #10255 lands this will require an update to `tests/unit/layout/size_of.rs`.

**Comment by mbrubeck** [comment]
This code all looks great to me; my only remaining concern is whether the performance impact is reasonable.  Here are my thoughts:

1. This increases the size of `Fragment`, but only by one word.  Seems reasonable and hard to avoid.
2. If any stylesheet (including a user or user agent stylesheet) contains a univeral `::selection { ... }` rule, then this allocates an extra instance of ServoComputedValues for every node on the page. This struct is very large, and I believe pseudo-element styles never use the style sharing cache, so this could cause a whole lot of memory allocation.  I think we could mitigate this by making style sharing work for pseudo elements.
3. This adds an extra `Arc::clone` call per Fragment during flow construction.  Not sure if it matters or not. Hard to avoid, at least for fragments affected by `::selection` rules (which in many cases could be all fragments; see above).

@pcwalton, any opinion on landing this as-is versus fixing the above issues first (especially number 2)?

-S-awaiting-review +S-needs-decision +S-needs-rebase 

---

Reviewed 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252#-:-KE3jTIiObZZDQpmtqLL:-376096497)*

**Comment by mbrubeck** [comment]
> If any stylesheet (including a user or user agent stylesheet) contains a univeral ::selection { ... } rule, then this allocates an extra instance of ServoComputedValues…

Oh wait, once again this is not as bad as I thought.  I forgot that ServoComputedValues only holds Arcs to the actual style structs, rather than storing them inline.  And it will clone these Arcs rather than copying the structs, almost all of the time.  That's still a number of new allocations and Arc::clone calls, but it's not nearly as much memory as I feared.

**Comment by SimonSapin** [comment]
> If any stylesheet (including a user or user agent stylesheet) contains a univeral `::selection { ... }`

This will likely be the case, won’t it? To set the default colors in the user-agent stylesheet.

**Comment by emilio** [comment]
> This will likely be the case, won’t it? To set the default colors in the user-agent stylesheet.

Since selection only works in textareas and inputs, for now we can reduce the impact using `input::selection, textarea::selection` if this is really problematic.

**Comment by emilio** [comment]
Rebased and updated the test expectations

**Comment by mbrubeck** [comment]
@bors-servo r+

Let's do this!

-S-needs-decision 

---

Reviewed 12 of 12 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10252#-:-KE7g_OvDFZ8Gat04L4H:1318539928)*

**Comment by paulrouget** [comment]
> Since selection only works in textareas and inputs, for now we can reduce the impact using input::selection, textarea::selection if this is really problematic.

Did that ever happen?

**Comment by SimonSapin** [comment]
It looks like the UA stylesheets don’t have any `::selection` rule at all, so selection defaults to invisible. We probably should add one in `resources/servo.css`.

**Comment by mbrubeck** [comment]
On Thu, Mar 31, 2016 at 6:05 AM, Simon Sapin <notifications@github.com>
wrote:

> It looks like the UA stylesheets don’t have any ::selection rule at all,
> so selection defaults to invisible. We probably should add one in
> resources/servo.css.
>

Submitted yesterday, but still waiting in the homu queue:
https://github.com/servo/servo/pull/10299

**Pull request merged**
