### PR TITLE
BindgenUp

### PR DESCRIPTION
**Pull request by emilio**
r? @heycam or @upsuper or @bholley

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15372)

### CODE REVIEW

**Comment by emilio** [comment]
This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1336228

**Review by upsuper — COMMENTED** [review]
Many pointer types are changed to zero-length arrays. Is that intended? What does a zero-length array mean here?

**Comment by emilio** [comment]
Yes, it is intended and it's the correct fix, otherwise static arrays don't work. It means they're incomplete arrays. See https://github.com/servo/rust-bindgen/pull/457 and https://github.com/servo/rust-bindgen/pull/456

**Comment by upsuper** [comment]
As far as it works... lgtm

**Pull request merged**
