### PR TITLE
[DO NOT MERGE] gfx: Remove the Servo display list in favor of the WebRender one.

### PR DESCRIPTION
**Pull request by pcwalton**
Needs to be split up into smaller patches and needs a WR traits upgrade first.

cc @mrobinson @glennw

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14546)

### CODE REVIEW

**Comment by pcwalton** [comment]
Here's an example of what the new display list dump looks like:

http://i.imgur.com/zKse0rH.png

**Comment by mrobinson** [comment]
@Wafflespeanut I'm not sure this is ready to review. @pcwalton has not removed [DO NOT MERGE] from the title.

**Comment by jdm** [comment]
Closing this given the lack of activity.

**Pull request closed without merging**
