### PR TITLE
Codegen: throw type error when encountering an unknown argument

### LINKED ISSUE #24130: Worker postMessage crashes when passed an invalid "*" argument
Steps to reproduce: Take any `worker.js` test, and add a call to `postMessage("test", "*")`.

```
0:03.63 pid:14870 Bad js error number given to get_error_message: 1 at /Users/gregory/.cargo/git/checkouts/rust-mozjs-8611526964119dd6/e30fa41/src/error.rs:47)
 0:05.31 pid:14870 stack backtrace:
 0:05.31 pid:14870    0: __ZN9backtrace9backtrace5trace17hccdcb2b4b2ba91b0E (0x1125938eb)
 0:05.31 pid:14870    1: __ZN9backtrace7capture9Backtrace3new17h1cb465cbd225bc37E (0x112592ae7)
 0:05.31 pid:14870    2: __ZN5servo4main28_$u7b$$u7b$closure$u7d$$u7d$17h96fe2577dc70af5aE (0x10f6f7dab)
 0:05.31 pid:14870    3: __ZN3std9panicking20rust_panic_with_hook17he24eb6798ad54c68E (0x112714ff1)
 0:05.31 pid:14870    4: __ZN3std9panicking18continue_panic_fmt17hc41eddc40bb93eb6E (0x112714a8c)
 0:05.31 pid:14870    5: __ZN3std9panicking15begin_panic_fmt17h2729b2380814cb15E (0x112810f1d)
 0:05.31 pid:14870    6: __ZN5mozjs5error17get_error_message17hb31527a1579e4264E.llvm.13455014667644631213 (0x110b5036c)
 0:05.31 pid:14870    7: __Z26ExpandErrorArgumentsHelperI13JSErrorReportEbP9JSContextPFPK19JSErrorFormatStringPvjES6_jPPKDsN2js18ErrorArgumentsTypeEPT_P13__va_list_tag (0x110c704e6)
 0:05.31 pid:14870    8: __ZN2js19ReportErrorNumberVAEP9JSContextjPFPK19JSErrorFormatStringPvjES5_jNS_18ErrorArgumentsTypeEP13__va_list_tag (0x110c70c04)
 0:05.31 pid:14870    9: __Z24JS_ReportErrorNumberUTF8P9JSContextPFPK19JSErrorFormatStringPvjES4_jz (0x110e009ee)
 0:05.31 pid:14870   10: __ZN5mozjs5error20throw_internal_error17hb9213dbab2d9becdE (0x110b50591)
 0:05.31 pid:14870   11: __ZN101_$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$9call_once17ha0c8878cbd78e8e6E (0x1100eeefb)
 0:05.31 pid:14870   12: __ZN3std9panicking3try7do_call17hdfcf4cbad9e3b375E.llvm.3787173794295391006 (0x10fccd8eb)
 0:05.31 pid:14870   13: ___rust_maybe_catch_panic (0x11271d38e)
 0:05.31 pid:14870   14: __ZN6script3dom8bindings7codegen8Bindings33DedicatedWorkerGlobalScopeBinding33DedicatedWorkerGlobalScopeBinding11postMessage17h755c6d253ca6c94cE (0x1109eb5a3)
 0:05.31 pid:14870   15: _CallJitMethodOp (0x110b50bf3)
 0:05.31 pid:14870   16: __ZN6script3dom8bindings5utils12generic_call17h6f781b937a8fc19cE (0x10fd5fbac)
 0:05.31 pid:14870   17: __ZN6script3dom8bindings5utils14generic_method17hab37e88df98bff41E (0x10fd5fd01)
 0:05.32 pid:14870   18: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE (0x110b77306)
 0:05.32 pid:14870   19: __ZL9InterpretP9JSContextRN2js8RunStateE (0x110b70e82)
 0:05.32 pid:14870   20: __ZN2js9RunScriptEP9JSContextRNS_8RunStateE (0x110b6703f)
 0:05.32 pid:14870   21: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE (0x110b775f1)
 0:05.32 pid:14870   22: __ZN2js4CallEP9JSContextN2JS6HandleINS2_5ValueEEES5_RKNS_13AnyInvokeArgsENS2_13MutableHandleIS4_EE (0x110b77aa5)
 0:05.32 pid:14870   23: __ZN2js9fun_applyEP9JSContextjPN2JS5ValueE (0x110c75679)
 0:05.32 pid:14870   24: __ZN2js23InternalCallOrConstructEP9JSContextRKN2JS8CallArgsENS_14MaybeConstructE (0x110b77306)
 0:05.32 pid:14870   25: __ZL9InterpretP9JSContextRN2js8RunStateE (0x110b70e82)
 0:05.32 pid:14870   26: __ZN2js9RunScriptEP9JSContextRNS_8RunStateE (0x110b6703f)
 0:05.32 pid:14870   27: __ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_16AbstractFramePtrEPS9_ (0x110b785df)
 0:05.32 pid:14870   28: __ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE (0x110b78789)
 0:05.32 pid:14870   29: __ZL8EvaluateP9JSContextN2js9ScopeKindEN2JS6HandleIP8JSObjectEERKNS3_22ReadOnlyCompileOptionsERNS3_10SourceTextIDsEENS3_13MutableHandleINS3_5ValueEEE (0x110c07f21)
 0:05.32 pid:14870   30: __ZN2JS12EvaluateUtf8EP9JSContextRKNS_22ReadOnlyCompileOptionsEPKcmNS_13MutableHandleINS_5ValueEEE (0x110c07a9c)
 0:05.32 pid:14870   31: __ZN5mozjs4rust7Runtime15evaluate_script17he695355cb00036c1E (0x110b4d60f)
 0:05.32 pid:14870   32: __ZN6script3dom17workerglobalscope17WorkerGlobalScope14execute_script17h639cbc6dbd5d8156E (0x10fe0d2d8)
 0:05.32 pid:14870   33: __ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h9bf3a9525120810fE (0x10fd258f2)
 0:05.32 pid:14870   34: __ZN3std9panicking3try7do_call17h148cd25424d2293cE.llvm.3787173794295391006 (0x10fc80aaa)
 0:05.32 pid:14870   35: ___rust_maybe_catch_panic (0x11271d38e)
 0:05.32 pid:14870   36: __ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h93670f359c2654c1E (0x1101f41e5)
 0:05.32 pid:14870   37: __ZN83_$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$9call_once17h98f1a88439d0719cE (0x112704e9d)
 0:05.32 pid:14870   38: __ZN3std3sys4unix6thread6Thread3new12thread_start17ha6c5c29f3ce7787bE (0x11271c8bd)
 0:05.32 pid:14870   39: __pthread_body (0x7fff641892ea)
 0:05.32 pid:14870   40: __pthread_start (0x7fff6418c248)
 0:05.32 pid:14870 [2019-09-03T19:31:48Z ERROR servo] Bad js error number given to get_error_message: 1
 0:
```

I came across this by accident, trying to run a test using the window "origin" argument set to "*" in a worker scope(using a `any.js` test).

### PR DESCRIPTION
**Pull request by gterzian**
FIX #24130

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24137)

### CODE REVIEW

**Comment by gterzian** [comment]
@jdm this fixes the error I noted, and I think it might have introduced other side-effects which I noticed because that commit went through on another test run by accident.

Let's see

@bors-servo try=wpt

**Comment by gterzian** [comment]
Oops, you beat me to it

**Comment by gterzian** [comment]
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: expected true got false", 
    "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:12\nnotThrow@http://web-platform.test:8000/webaudio/resources/audit.js:365:19\n@http://web-platform.test:8000/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html:54:60\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1190:12\n_runNextTask@http://web-platform.test:8000/webaudio/resources/audit.js:1261:67\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1331:12\n@http://web-platform.test:8000/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html:569:13\n", 
    "subtest": "X createIIRFilter with normalized coefficients incorrectly threw TypeError: \"context.createIIRFilter is not a function\".", 
    "test": "/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html", 
    "line": 147356, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_true: expected true got false", 
    "stack": "_logFailed/<@http://web-platform.test:8000/webaudio/resources/audit.js:50:7\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1611:25\ntest@http://web-platform.test:8000/resources/testharness.js:544:30\n_logFailed@http://web-platform.test:8000/webaudio/resources/audit.js:49:5\n_finalize@http://web-platform.test:8000/webaudio/resources/audit.js:215:9\n_assert@http://web-platform.test:8000/webaudio/resources/audit.js:228:12\nnotThrow@http://web-platform.test:8000/webaudio/resources/audit.js:365:19\n@http://web-platform.test:8000/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html:58:62\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1190:12\n_runNextTask@http://web-platform.test:8000/webaudio/resources/audit.js:1261:67\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1331:12\n@http://web-platform.test:8000/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html:569:13\n", 
    "subtest": "X createIIRFilter with unnormalized coefficients incorrectly threw TypeError: \"context.createIIRFilter is not a function\".", 
    "test": "/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html", 
    "line": 147358, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "ERROR", 
    "group": "default", 
    "message": "Could not convert JavaScript argument", 
    "stack": "@http://web-platform.test:8000/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html:64:16\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1190:12\n_runNextTask@http://web-platform.test:8000/webaudio/resources/audit.js:1261:67\nrun@http://web-platform.test:8000/webaudio/resources/audit.js:1331:12\n@http://web-platform.test:8000/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html:569:13\n", 
    "subtest": null, 
    "test": "/webaudio/the-audio-api/the-iirfilternode-interface/iirfilter.html", 
    "line": 147360, 
    "action": "test_result", 
    "expected": "CRASH"
}
```

That's actually progress, I'll update

**Comment by gterzian** [comment]
@jdm r?

**Comment by jdm** [comment]
Indeed!
@bors-servo r+

**Pull request merged**
