### PR TITLE
Improve unit test of DataSlice

### PR DESCRIPTION
**Pull request by izgzhen**
Add three more cases. relevant spec https://w3c.github.io/FileAPI/#slice-method-algo

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

related to #11131

- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11711)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I'm a little unhappy about writing unit tests for this. Can't we write wpt tests?

**Comment by izgzhen** [comment]
@Ms2ger okay, I should have thought that. Sounds good to me

**Pull request closed without merging**
