### PR TITLE
Use unguessable pipeline ids

### PR DESCRIPTION
**Pull request by aneeshusa**
Took a pass at #10542.

Also, we should definitely make the RNG instance once and then cache it, but I'm not sure of the best way to do that. (I could use TLS as was being used for the pipeline namespaces previously, but what's the best place to initialize the RNG?) This is especially important for OsRng because it tried to call getrandom every time `new` is called to see if the syscall is supported.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10808)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Also, this requires a one-line change to webrender_traits, but I wanted to get some feedback before making a PR for that (just need to change the definition of PipelineId there to match this one.) I'm wondering if there's a way to avoid having to duplicate the PipelineId struct, though.

**Comment by asajeffrey** [comment]
We should try to share the RNG. Is there a uuid crate we could use for this?

---

Reviewed 3 of 3 files at r1, 2 of 9 files at r2.
Review status: 3 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/msg/constellation_msg.rs, line 267 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10808#-KFz5Y7cuOGvibtfauaP:-KFz5Y7cuOGvibtfauaQ:1852509874) ([raw file](https://github.com/servo/servo/blob/06e35ff2fbfe0a6d228c8a4d53c735bbd9a15c87/components/msg/constellation_msg.rs#L267)):*
We are assuming no collisions in the bytes generated by the RNG, which is fine but should probably be documented.

---

*[components/msg/constellation_msg.rs, line 282 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10808#-KFz4dNx5h4Sa-XSds4r:-KFz4dNx5h4Sa-XSds4s:-1191878031) ([raw file](https://github.com/servo/servo/blob/06e35ff2fbfe0a6d228c8a4d53c735bbd9a15c87/components/msg/constellation_msg.rs#L282)):*
This is creating a new RNG each time, which may be expensive (think getting entropy from the keyboard expensive).

---

*[components/msg/constellation_msg.rs, line 309 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10808#-KFz5I7rh4KaC4ncCnNg:-KFz5I7suZWMuFs-ozP4:-319221015) ([raw file](https://github.com/servo/servo/blob/06e35ff2fbfe0a6d228c8a4d53c735bbd9a15c87/components/msg/constellation_msg.rs#L309)):*
Does this pass the orphan rule?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10808#-:-KFz6JTzL8UJS7Ibx4C2:1668974462)*

**Comment by jdm** [comment]
There's a uuid crate that we already use in other places in Servo.

**Comment by asajeffrey** [comment]
Just realized a conflict between randomized pipeline ids and repeatability of stress testing: https://github.com/servo/servo/blob/master/components/compositing/constellation.rs#L1859 says "In order to get repeatability, we sort the pipeline ids," which isn't going to work if pipeline ids are unguessable.

**Comment by asajeffrey** [comment]
@aneeshusa are you planning on picking this back up again? Using uuids as pipeline ids seems like the way to go. We'll lose a bit of test repeatability, but I think we can live with that.

**Comment by Ms2ger** [comment]
@aneeshusa ping?

**Comment by aneeshusa** [comment]
Started rebasing this to use the `uuid` crate. I'm getting the error `no method named heap_size_of_children found for type uuid::Uuid in the current scope` - I need to make a PR against the `uuid` crate adding heapsize support behind a Cargo flag, right?

Also @asajeffrey, I definitely agree that we should cache the RNG instance. What's the best place to cache it/way to do that?

**Comment by jdm** [comment]
It's also possible to use `#[ignore_heap_size_of = "no heapsize impl for uuid"]` for the time being to avoid the error.

**Comment by asajeffrey** [comment]
@aneeshusa where to store the RNG for uuid generation depends on where we're going to do the uuid generation. If it's the constellation, we just need one RNG there, but if we want each pipeline to be able to generate sub-pipelines, we'll need to have an RNG per script thread.

**Comment by aneeshusa** [comment]
Updated.

Now requires servo/webrender_traits#56 and servo/webrender#291.

I haven't added the caching yet. The RNG instance should be cached in the script thread, but I'm not sure how to easily get a reference to it from the HTMLIFrameElement so it can be used.

There is also a usage of fake_root_pipeline_id() in tests/unit/net/http_loader.rs that needs to be removed; I'm not exactly sure how to approach this.

**Comment by pcwalton** [comment]
I'll r+ the changes to the dependent crates once @asajeffrey signs off on the design behind this change.

**Comment by emilio** [comment]
Ping? Is this still alive? :)

**Comment by aneeshusa** [comment]
Rebased this and the required PRs; sorry about the delay. I was waiting on some WR changes to be merged, so I could rebase my bitrotted WR changes, so I could rebase this locally and test it.

**Comment by asajeffrey** [comment]
Sorry about the delay. Only one comment, which is about using `rand::thread_rng`. Once it's rebased and squashed, this can be r=me.

---

Reviewed 3 of 11 files at r3, 9 of 9 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/msg/constellation_msg.rs, line 282 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10808#-KFz4dNx5h4Sa-XSds4r:-KMZI_UvOG2IQR3Af9Ze:-1419243635) ([raw file](https://github.com/servo/servo/blob/06e35ff2fbfe0a6d228c8a4d53c735bbd9a15c87/components/msg/constellation_msg.rs#L282)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> This is creating a new RNG each time, which may be expensive (think getting entropy from the keyboard expensive).
</details>
Use `rand::thread_rng` for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10808#-:-KMZJ2jyVqBRR-HH6eyl:-1611125774)*

**Comment by aneeshusa** [comment]
@asajeffrey I wrote about this in `constellation_msg.rs` but I'll recap - we need to have a cryptographically secure RNG, so we [have to use `OsRng`](https://doc.rust-lang.org/rand/rand/index.html#cryptographic-security). Cryptographic security is what provides the key property (actually one of two) of unguessability.

Let me know how I can change the wording to make this more clear, since this is a key part of the design and so I want the reasoning should be easily understood from the comments/commit message.

**Comment by asajeffrey** [comment]
I don't think we need a cryptographically secure RNG, we just need something to make guessing attacks unlikely. I think `thread_rng` is going to be robust enough.

**Comment by asajeffrey** [comment]
I don't really mind about generating an RNG every time, as pipeline id generation doesn't happen that often. You can rebase, squash, and r=me.

**Comment by asajeffrey** [comment]
@aneeshusa ping?

**Comment by aneeshusa** [comment]
I don't have time to finish right now.

**Pull request closed without merging**
