### PR TITLE
Warning police.

### PR DESCRIPTION
**Pull request by jdm**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6949)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6949)

**Comment by SimonSapin** [comment]
#6958 
```
/css21_dev/html4/counter-reset-increment-002.htm
------------------------------------------------
CRASH expected TIMEOUT [Parent]
```

There’s also a remaining warning:
```
/home/servo/buildbot/slave/linux3/build/components/gfx/text/shaping/harfbuzz.rs:30:16: 30:42 warning: unused import, #[warn(unused_imports)] on by default
/home/servo/buildbot/slave/linux3/build/components/gfx/text/shaping/harfbuzz.rs:30 use harfbuzz::{RUST_hb_font_funcs_destroy};
                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Ms2ger** [comment]
@bors-servo retry
* #6958

**Comment by jdm** [comment]
@bors-servo: retry
* #6818

**Pull request closed without merging**
