### PR TITLE
Fix bleeding in FxR by adding Padding support to ServoSurface

### PR DESCRIPTION
**Pull request by paulrouget**
Not ready for review, just need to make sure the CI is happy for now.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23002)

### CODE REVIEW

**Comment by gw3583** [comment]
@paulrouget Yep, that seems reasonable to me.

**Comment by CYBAI** [comment]
Error in `magicleap`:

```
error[E0560]: struct `simpleservo::InitOptions` has no field named `width`
   --> ports/libmlservo/src/lib.rs:120:9
    |
120 |         width: width,
    |         ^^^^^ `simpleservo::InitOptions` does not have this field
    |
    = note: available fields are: `args`, `url`, `coordinates`, `density`, `vr_pointer`, `enable_subpixel_text_antialiasing`

error[E0560]: struct `simpleservo::InitOptions` has no field named `height`
   --> ports/libmlservo/src/lib.rs:121:9
    |
121 |         height: height,
    |         ^^^^^^ `simpleservo::InitOptions` does not have this field
    |
    = note: available fields are: `args`, `url`, `coordinates`, `density`, `vr_pointer`, `enable_subpixel_text_antialiasing`
```

I'm not sure if there's any related filtered WPT tests so let me paste all of them here 👀

Filtered WPT in `mac-rel-css1`:

<details>

```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/rendering/non-replaced-elements/tables/colgroup_valign_bottom.xhtml", 
    "line": 10062, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/rendering/non-replaced-elements/tables/colgroup_valign_top.xhtml", 
    "line": 10123, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/compositing/compositing_simple_div.html f73ffe6a9f3cc5e17430d6ef44420ba47319b0f1\n/css/compositing/compositing_simple_div-ref.html 1f3a75c2c13cafe10d6b98241fc2b1efd9d1d219", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/compositing/compositing_simple_div.html", 
    "line": 20028, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/_mozilla/css/border_radius_zero_sizes_a.html a7f6c6aac49f5837594e098d7da466a13b352df8\n/_mozilla/css/border_radius_zero_sizes_ref.html c0989af36f011e8805f21a8e517b1c4d9cce9df3", 
    "stack": null, 
    "subtest": null, 
    "test": "/_mozilla/css/border_radius_zero_sizes_a.html", 
    "line": 23402, 
    "action": "test_result", 
    "expected": "PASS"
}
```

</details>


Filtered WPT in `linux-rel-wpt`:

<details>

```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/css-backgrounds/background-color-body-propagation-004.html bb144e9256051f1d3d82a0b5b6a548af5a15b917\n/css/reference/blank.html 54a9df64f1476dd12020019d7cf22ac34d727bc0", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-backgrounds/background-color-body-propagation-004.html", 
    "line": 26093, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/compositing/compositing_simple_div.html f73ffe6a9f3cc5e17430d6ef44420ba47319b0f1\n/css/compositing/compositing_simple_div-ref.html 1f3a75c2c13cafe10d6b98241fc2b1efd9d1d219", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/compositing/compositing_simple_div.html", 
    "line": 26535, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/css-transforms/perspective-translateZ-negative.html 0cdf9ee5d3f11a7b603fcb0ba2de2287a90163e9\n/css/css-transforms/reference/perspective-reftest.html a02e9400d3d7808968ca282320a1123ef2a6feb9", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-transforms/perspective-translateZ-negative.html", 
    "line": 33568, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-transforms/transform3d-perspective-004.html", 
    "line": 36581, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/css-transforms/transform3d-rotatex-perspective-002.html 0e3759dd811779763b82fb5ba11ea2b06d379133\n/css/css-transforms/transform3d-rotatex-ref.html 0e3759dd811779763b82fb5ba11ea2b06d379133", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-transforms/transform3d-rotatex-perspective-002.html", 
    "line": 36704, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-transforms/transform3d-perspective-003.html", 
    "line": 36714, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/css-transforms/transform3d-perspective-origin-001.html 0e3759dd811779763b82fb5ba11ea2b06d379133\n/css/css-transforms/transform3d-perspective-origin-ref.html 0e3759dd811779763b82fb5ba11ea2b06d379133\n/css/css-transforms/transform3d-perspective-origin-ref.html 0e3759dd811779763b82fb5ba11ea2b06d379133\n/css/css-transforms/transform3d-rotatex-ref.html 0e3759dd811779763b82fb5ba11ea2b06d379133", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-transforms/transform3d-perspective-origin-001.html", 
    "line": 39454, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/css-transforms/text-perspective-001.html 54a9df64f1476dd12020019d7cf22ac34d727bc0\nabout:blank 54a9df64f1476dd12020019d7cf22ac34d727bc0", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/css-transforms/text-perspective-001.html", 
    "line": 40000, 
    "action": "test_result", 
    "expected": "PASS"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/rendering/non-replaced-elements/tables/colgroup_valign_bottom.xhtml", 
    "line": 40515, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/html/rendering/non-replaced-elements/tables/colgroup_valign_top.xhtml", 
    "line": 40628, 
    "action": "test_result", 
    "expected": "FAIL"
}
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/_mozilla/css/border_radius_zero_sizes_a.html a7f6c6aac49f5837594e098d7da466a13b352df8\n/_mozilla/css/border_radius_zero_sizes_ref.html c0989af36f011e8805f21a8e517b1c4d9cce9df3", 
    "stack": null, 
    "subtest": null, 
    "test": "/_mozilla/css/border_radius_zero_sizes_a.html", 
    "line": 46240, 
    "action": "test_result", 
    "expected": "PASS"
}
```

</details>

**Comment by paulrouget** [comment]
background-color-body-propagation-004 failed.

Hmm, we need a way to have a different background for a WR document and the whole framebuffer.

**Comment by paulrouget** [comment]
We need to clear twice. It would be better if WR could handle that for us, but apparently the clear_color option is not working as expected for now: https://github.com/servo/servo/pull/22973#issuecomment-471774356

**Comment by paulrouget** [comment]
@gw3583 we need a different background color for the framebuffer and the WR documents. The framebuffer needs to be transparent, the background of a WR document needs to be white. Is it ok to do just that right before calling `webrender.render()`:

```rust
gl.clear_color(0.0, 0.0, 0.0, 0.0); // black transparent
gl.clear(COLOR_BUFFER_BIT);
gl.scissor(doc.origin.x, doc.origin.y, doc.size.width, doc.size.height);
gl.clear_color(1.0, 1.0, 1.0, 1.0); // white opaque
gl.enable(SCISSOR_TEST);
gl.clear(COLOR_BUFFER_BIT);
gl.disable(SCISSOR_TEST);
webrender.render();
```

And is it necessary to disable scissor before calling webrender.render()?

**Comment by paulrouget** [comment]
From IRC:

> gw: yes, what you have there looks fine to do - it's probably a good idea to disable scissor before calling wr.render, though I don't think it's actually necessary right now

**Comment by paulrouget** [comment]
(I'll be on PTO for a week, if this turns green, can someone r=jdm this PR?)

**Comment by CYBAI** [comment]
It's green! but sorry that I can only help to try 😂

**Pull request merged**
