### PR TITLE
Stylo - gecko glue code for text-justify

### PR DESCRIPTION
**Pull request by chenpighead**
Implement gecko glue for text-justify property.

Gecko has supported text-justify in [Bug 276079](https://bugzilla.mozilla.org/show_bug.cgi?id=276079), and going to pref-on on Nightly very soon in [Bug 1343512](https://bugzilla.mozilla.org/show_bug.cgi?id=1343512). Let's make it work for stylo.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15839)

### CODE REVIEW

**Comment by chenpighead** [comment]
I assume that this could help remove the changes I've added to stylo-failures.md in [Bug 1343593](https://bugzilla.mozilla.org/show_bug.cgi?id=1343593).

**Comment by emilio** [comment]
@bors-servo r+

Thanks Jeremy! :)

**Comment by chenpighead** [comment]
Please don't merge this yet. Need to deal with stylo build failures like: 
https://treeherder.mozilla.org/#/jobs?repo=try&revision=3075c2f01420c22f29a56444d0f2a07abbd96bf7&selectedJob=82047417

**Comment by BorisChiou** [comment]
You status is S-test-failed, so after you fix your problem, just retry it.

**Comment by chenpighead** [comment]
I thought using helpers.single_keyword in this PR is trivial, then I realized that we treat `distribute` as a alias keyword of `inter-character` in Gecko. It means we parse and store `distribute` as a specified value, but use `inter-character` as its computed value. This kind of keyword-aliasing function seems not supported in helper.mako.rs yet... :(

**Comment by chenpighead** [comment]
This PR is not ready for review yet...

The point is `single_keyword_computed`, which is called by `single_keyword` in helpers.mako.rs, assumes that ComputedValueAsSpecified and creates SpecifiedValue and computed_value accordingly. Looks like I can only use <%helpers:longhand> to write the parsing/serialization by myself. Will upload the PR later.

**Comment by chenpighead** [comment]
Filed [Bug 1345498](https://bugzilla.mozilla.org/show_bug.cgi?id=1345498) for this.

Note that once this PR is merged, the mochitest expections in stylo-failures.md should be updated ASAP to avoid unexpected pass on try. The patch for stylo-failures.md part has been uploaded in [Bug 1345498](https://bugzilla.mozilla.org/show_bug.cgi?id=1345498) as well.

stylo try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=6cae1fc0b48a45d3f3377eb033f7179ca7b3d15b

**Comment by upsuper** [comment]
It seems there are some issues in the code that Servo doesn't build.
```
error[E0004]: non-exhaustive patterns: `distribute` not covered
     --> /home/travis/build/servo/servo/target/debug/build/style-02763c7e4bdd6e08/out/properties.rs:20660:19
      |
20660 |             match *self {
      |                   ^^^^^ pattern `distribute` not covered
```

**Comment by chenpighead** [comment]
Hmmm... this reminds me why I choose to implement this without using helper. I think what we need exactly is a parameter like `extra_gecko_specific`, which I can't find one in the helper. The point is we want `distribute` keyword to just appear in gecko's specified value, but not computed value.

If we put `distribute` in `extra_gecko_values`,  we'll need to implement our own setter in gecko.mako.rs. Otherwise, the computed value `distribute` is auto-generated  and a stylo build error occurs:
> error: no associated item named `Distribute` found for type `gecko_bindings::structs::root::mozilla::StyleTextJustify` in the current scope
 4:15.57     --> /Users/jeremy/gecko-dev/obj-x86_64-apple-darwin16.4.0/toolkit/library/x86_64-apple-darwin/release/build/style-c430bd48b7778d69/out/gecko_properties.rs:9077:21
 4:15.57      |
 4:15.57 9077 |                     structs::StyleTextJustify::Distribute
 4:15.57      |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 4:15.58 
 4:16.15 error: aborting due to previous error

If we put `distribute` in `extra_specified`,  we'll need to handle `distribute` value in Servo as well, but this would be a bit wierd since Servo doesn't support it. Otherwise, we would encounter a Servo build error like this

> error[E0004]: non-exhaustive patterns: `distribute` not covered
     --> /Users/jeremy/servo/target/debug/build/style-55438e23cfc8a60f/out/properties.rs:20633:19
      |
20633 |             match *self {
      |                   ^^^^^ pattern `distribute` not covered

@upsuper any suggestion?

**Comment by chenpighead** [comment]
In the latest version, I put `inter-character` and `distribute` in extra_gecko_values, and implement our own setter in gecko.mako.rs. This should work in both Stylo and Servo. I'd like to further polish the patch if I could get a better suggestion.

**Comment by upsuper** [comment]
You just need something like `extra_specific="${'distribute' if product == 'gecko' else ''}"`.

**Comment by chenpighead** [comment]
It works. Thank you. :)

**Pull request merged**
