### PR TITLE
Add a `-Z replace-surrogates` command-line option.

### PR DESCRIPTION
**Pull request by SimonSapin**
See #6564.

r? @Ms2ger

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6614)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo r=Ms2ger

The additional commit adds a bit to the panic message.

**Comment by larsbergstrom** [comment]
```
Summary
=======

Ran 5021 tests (5015 parents, 6 subtests)
Expected results: 4983
Unexpected results: 28 (FAIL: 14, PASS: 14)
Skipped: 10

Unexpected Results
==================

/css21_dev/html4/color-applies-to-002.htm
-----------------------------------------
FAIL [Parent]
/css21_dev/html4/color-applies-to-001.htm
-----------------------------------------
FAIL [Parent]
/css21_dev/html4/color-applies-to-003.htm
-----------------------------------------
FAIL [Parent]
/css21_dev/html4/color-applies-to-004.htm
-----------------------------------------
FAIL [Parent]
/css21_dev/html4/color-applies-to-005.htm
-----------------------------------------
FAIL [Parent]
/css21_dev/html4/color-applies-to-006.htm
-----------------------------------------
FAIL [Parent]
/css21_dev/html4/color-applies-to-013.htm
-----------------------------------------
FAIL [Parent]
/css21_dev/html4/color-applies-to-015.htm
-----------------------------------------
FAIL [Parent]
/css21_dev/html4/content-177.htm
--------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/display-008.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/display-009.htm
--------------------------------
FAIL [Parent]
/css21_dev/html4/float-applies-to-008.htm
-----------------------------------------
FAIL [Parent]
/css21_dev/html4/font-size-001.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-002.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-005.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-004.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-090.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-089.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-092.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-093.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-100.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-101.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/font-size-102.htm
----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/inline-block-zorder-003.htm
--------------------------------------------
FAIL [Parent]
/css21_dev/html4/inline-formatting-context-004.htm
--------------------------------------------------
FAIL [Parent]
/css21_dev/html4/inline-formatting-context-005.htm
--------------------------------------------------
FAIL [Parent]
/css21_dev/html4/line-height-121.htm
------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/line-height-127.htm
------------------------------------
PASS expected FAIL [Parent]
12:15.16 LOG: MainThread INFO Closing logging queue
12:15.16 LOG: MainThread INFO queue closed
program finished with exit code 1
elapsedTime=744.561454
```

**Comment by larsbergstrom** [comment]
@bors-servo: retry

(note: mac builders were being patched and rebooted and were sometimes not logged in during this, causing reftest-related failures)

**Comment by pcwalton** [comment]
I don't understand how options that the tests don't use are causing failures.

**Comment by Ms2ger** [comment]
@bors-servo retry
* #6619

**Pull request merged**
