### PR TITLE
Upgrade Rust to nightly 2015-08-10

### PR DESCRIPTION
**Pull request by Manishearth**
Still needs snapshot.

Snapshot probably could also work as today's nightly (I wasn't able to download the latest one due to choppy internet), there isn't any plugins churn I know of

r? @larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7195)

### CODE REVIEW

**Comment by Ms2ger** [comment]
r=me

**Comment by Manishearth** [comment]
Successfully compiles on my linux, clean build. With an unclean target dir you may get link errors with IPC.

**Comment by larsbergstrom** [comment]
Snapshot for 7b7fc67dd453c470a48dbdcf64693a93293c9ab0 (August 13) uploaded.

**Comment by Manishearth** [comment]
It seems like you uploaded 87055a68c3194db212456f99ece080728a5fc2f8 (the old snapshot)?

**Comment by larsbergstrom** [comment]
@Manishearth Should be fixed - sorry! My build scripts silently failed and uploaded the old binaries, since there was a change in the arguments to Rust's `configure` related to cross-targeting.

**Comment by Manishearth** [comment]
@bors-servo r=Ms2ger

Aarrrgghhhhh

**Pull request merged**
