### PR TITLE
script: Element.webkitMatchesSelector()

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
spec:
- https://github.com/whatwg/dom/commit/9ac9c1548661a309c15168d71e6fb6af92d4d610
  - https://github.com/whatwg/compat/issues/3

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8183)

### CODE REVIEW

**Comment by saneyuki** [comment]
@Ms2ger r?

**Comment by Ms2ger** [comment]
I'm not too happy about this landing without tests, but I'll let it pass because I already submitted tests upstream.

**Comment by saneyuki** [comment]
@Ms2ger 

Sorry, I was going to ask you about tests and we should wait to merge the test which you submitted.  I should have written the comment about it.

**Pull request merged**
