### PR TITLE
Removed some sources of panic from script thread.

### LINKED ISSUE #11693: Intermittent CRASH in /html/semantics/embedded-content/the-iframe-element/change_parentage.html
This test was just added in #11677. CC @asajeffrey 

      ▶ CRASH [expected OK] /html/semantics/embedded-content/the-iframe-element/change_parentage.html
      │ 
      │ Xlib:  extension &#34;XFree86-VidModeExtension&#34; missing on display &#34;:0&#34;.
      │ ERROR:constellation::constellation: Panic: ScriptThread: received an event message for a layout channel that is not associated with this script thread.This is a bug.
      │ ERROR:constellation::constellation: Backtrace:
      │ frame #0  - 0x00007f81a1b47d3d - backtrace::backtrace::trace::hccde8df28b4db2a2
      │ frame #1  - 0x00007f81a1b47cc5 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
      │ frame #2  - 0x00007f81a0b9e739 - _&lt;F as alloc..boxed..FnBox&lt;A&gt;&gt;::call_box::h89adae1a802be550
      │ frame #3  - 0x00007f81a1b39578 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::he2b22674ad1748f3
      │ frame #4  - 0x00007f81a1e0404c - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
      │ frame #5  - 0x00007f81a1e1e451 - std::panicking::begin_panic::he426e15a3766089a
      │ frame #6  - 0x00007f81a1e058ba - std::panicking::begin_panic_fmt::hdddb415186c241e7
      │ frame #7  - 0x00007f81a1e1e3ee - rust_begin_unwind
      │ frame #8  - 0x00007f81a1e549ef - core::panicking::panic_fmt::hf4e16cb7f0d41a25
      │ frame #9  - 0x00007f81a1e5c0a4 - core::option::expect_failed::hdb92832549f56a85
      │ frame #10 - 0x00007f81a0bab771 - script::script_thread::ScriptThread::handle_msg_from_script::h47e979ae1e7fb676
      │ frame #11 - 0x00007f81a0bf570f - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hb50cf7fd97943b65
      │ frame #12 - 0x00007f81a0bdda59 - script::script_thread::ScriptThread::handle_msgs::h1e1abab71191c950
      │ frame #13 - 0x00007f81a0b9cdb7 - std::panicking::try::call::h78dcd5319adf08fa
      │ frame #14 - 0x00007f81a1e2864b - __rust_try
      │ frame #15 - 0x00007f81a1e285ee - __rust_maybe_catch_panic
      │ frame #16 - 0x00007f81a0b9e09d - _&lt;F as alloc..boxed..FnBox&lt;A&gt;&gt;::call_box::hce043844655ea6a9
      │ frame #17 - 0x00007f81a1e1c614 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
      │ frame #18 - 0x00007f819dc89181 - start_thread
      │ frame #19 - 0x00007f819d7a047c - __clone
      │ frame #20 - 0x0000000000000000 - &lt;unknown&gt;
      │ 
      └ ERROR:constellation::constellation: Pipeline failed in hard-fail mode.  Crashing!

### PR DESCRIPTION
**Pull request by asajeffrey**
**This PR needs some thought!**

It removes some sources of panic from script_thread.rs, caused by pipeline lookup failure. It's incomplete, as there are some uses of `get_browsing_context` elsewhere in the code.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11693 and #11685 (and probably some other intermittents)
- [X] These changes do not require tests because it is fixing intermittent panic

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11695)

### CODE REVIEW

**Comment by asajeffrey** [comment]
cc @Ms2ger, @Manishearth and @mbrubeck

**Comment by asajeffrey** [comment]
Rebased.

**Comment by Ms2ger** [comment]
I feel like this is too ad-hoc in places. I think in general when we get a message with a pipeline id, we should immediately get the browsing context and return, before doing anything else.

Also, why don't we use `find_child_context` everywhere? That would also avoid a panic when the root browsing context is gone.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/script_thread.rs, line 1089 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11695#-KKsHPHker3giHIZrwiM:-KKsHPHker3giHIZrwiN:-1398884615) ([raw file](https://github.com/servo/servo/blob/3c75ac90493cdd9a221848152746d5c0598a9c14/components/script/script_thread.rs#L1089)):*
> ```Rust
>         if let Some(ref context) = self.find_child_context(id) {
>             let window = match context.find(id) {
>                 Some(browsing_context) => browsing_context.active_window(),
> ```

This is the same as `context`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11695#-:-KKsH3dINv22Qgn9OM-J:1467998701)*

**Comment by asajeffrey** [comment]
I'm not sure why this is more ad hoc than what we had before: I just replaced all uses of `get_browsing_context(&context,id)` by a match on `context.find(id)`.

OK, I see what you mean about using `find_child_context` rather than `context.find` on the root context. Is that a separate PR?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/script_thread.rs, line 1089 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11695#-KKsHPHker3giHIZrwiM:-KKyNnkwO1JJMe4C0tFw:1758359711) ([raw file](https://github.com/servo/servo/blob/3c75ac90493cdd9a221848152746d5c0598a9c14/components/script/script_thread.rs#L1089)):*
<details><summary><i>Previously, Ms2ger wrote…</i></summary>
> This is the same as `context`.
</details>
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11695#-:-KKyNsxz6F-6xGML-T_e:-1687186622)*

**Comment by Ms2ger** [comment]
r+ after squash, I guess.

**Comment by asajeffrey** [comment]
@Ms2ger you don't need to sound so excited :)
@bors-servo r=Ms2ger

**Comment by asajeffrey** [comment]
@bors-servo retry
 * etc/ci/manifest_changed.sh failing for some reason.

**Comment by asajeffrey** [comment]
@bors-servo retry

 * etc/ci/manifest_changed.sh

**Comment by asajeffrey** [comment]
@bors-servo retry

 * #11858

**Comment by asajeffrey** [comment]
@bors-servo retry

 * #11859 

(Finally got rout to submitting an issue for that one.)

**Comment by asajeffrey** [comment]
@bors-servo retry

 * #11858

**Pull request merged**
