### PR TITLE
script: When using WebRender, keep the DOM-side scroll positions for elements with `overflow: scroll` up to date, and take them into account when doing hit testing.

### LINKED ISSUE #11648: [hittest] Link hitboxes are not updated after scrolling on duckduckgo
`./mach run -d -w https://duckduckgo.com/\?q\=rust+langauge`
Scroll down and hover over links. The link rectangles are not updated after the scroll.
This happens both inside and outside of browserhtml.
This only happens with webrender.

### PR DESCRIPTION
**Pull request by pcwalton**
Closes #11648.

r? @jdm 
cc @paulrouget

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11680)

### CODE REVIEW

**Comment by jdm** [comment]
This generally looks fine, apart from the suspected breakage of synchronous scrolling APIs. I would also like @glennw to take a look at the gfx_traits changes, since I don't know enough about what's going on there to feel comfortable reviewing it.
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 10 of 10 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/gfx/display_list/mod.rs, line 632 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJpYUYSchYdENhx7FHs:-KJpYUYTfmg2W6chqtsk:-90528595) ([raw file](https://github.com/servo/servo/blob/90932e0c6ff8411686bd14b4f49ecdc255de3b9e/components/gfx/display_list/mod.rs#L632)):*
> ```Rust
>         //
>         // We don't perform this adjustment on the root stacking context because the DOM-side code
>         // has already translated the point for us (e.g. in Document::handle_mouse_move_event()`)
> ```

nit: stray ` here.

---

*[components/layout/layout_thread.rs, line 1302 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJq8qsAHU2deenQ9Qng:-KJq8Rc4FDMA3B-EJ0vp:-691482291) ([raw file](https://github.com/servo/servo/blob/90932e0c6ff8411686bd14b4f49ecdc255de3b9e/components/layout/layout_thread.rs#L1302)):*
> ```Rust
>         }
>         let _ = self.script_chan
>                     .send(ConstellationControlMsg::SetScrollState(self.id, script_scroll_states));
> ```

Since this message is sent to the regular script event queue, I expect that the following code will print false now since we rely on the latest data that's been pushed to the script thread rather than querying the compositor/layout:
```js
var oldScrollTop = element.scrollTop;
element.scrollTop = oldScrollTop + 10;
console.log(oldScrollTop != element.scrollTop)
```

---

*[components/script/dom/window.rs, line 269 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJpcEw-NVG7VXhNPyGC:-KJpcEw-NVG7VXhNPyGD:1052676506) ([raw file](https://github.com/servo/servo/blob/90932e0c6ff8411686bd14b4f49ecdc255de3b9e/components/script/dom/window.rs#L269)):*
> ```Rust
> 
>     /// A list of scroll offsets for each scrollable element.
>     #[ignore_heap_size_of = "TODO(#6909) need to measure HashMap"]
> ```

HeapSize supports HashMap, so this message is incorrect. What's the actual type that's missing an implementation?

---

*[components/script/dom/window.rs, line 373 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJq76ortl-pSkQPfUZA:-KJq76osQqOhddt9hBsb:1585245492) ([raw file](https://github.com/servo/servo/blob/90932e0c6ff8411686bd14b4f49ecdc255de3b9e/components/script/dom/window.rs#L373)):*
> ```Rust
>     ///
>     /// This is only called when WebRender is in use.
>     pub fn add_scroll_offset(&self,
> ```

Let's combine these two methods into a single `set_scroll_offsets(&self, offsets: HashMap<UntrustedNodeAddress, Point2D<f32>>)` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11680#-:-KJqBtv7ytGiMbWiiBv1:110255974)*

**Comment by pcwalton** [comment]
Review status: 10 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/layout/layout_thread.rs, line 1302 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJq8qsAHU2deenQ9Qng:-KJrowiLiszYPODM9cPr:1422427426) ([raw file](https://github.com/servo/servo/blob/90932e0c6ff8411686bd14b4f49ecdc255de3b9e/components/layout/layout_thread.rs#L1302)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Since this message is sent to the regular script event queue, I expect that the following code will print false now since we rely on the latest data that's been pushed to the script thread rather than querying the compositor/layout:
> ```js
> var oldScrollTop = element.scrollTop;
> element.scrollTop = oldScrollTop + 10;
> console.log(oldScrollTop != element.scrollTop)
> ```
</details>
This is basically a symptom of the fact that script-initiated scrolling doesn't work at all in WebRender yet. All of our DOM-initiated scrolls are based on layers, which are not a concept that exists in the WebRender world.

How would you like me to fix this? Do you want me to implement script-initiated scrolling in WebRender before landing this patch? (It'll probably be a large change, larger than this patch itself.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11680)*

**Comment by glennw** [comment]
Review status: 6 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/gfx_traits/lib.rs, line 182 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJrwCdpH6qs1onZRO-e:-KJrwCdqYKb0Wz2fmArU:1233329038) ([raw file](https://github.com/servo/servo/blob/5afc4db51a383b67f096ff31dc7546827aceaa68/components/gfx_traits/lib.rs#L182)):*
> ```Rust
> 
>     /// Returns a new stacking context ID for a special stacking context.
>     fn special_id() -> usize {
> ```

Perhaps call it next_special_id() ?

---

*[components/gfx_traits/lib.rs, line 183 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJrvJCBnv4vRhxkDRWP:-KJrvJCBnv4vRhxkDRWQ:-2003394054) ([raw file](https://github.com/servo/servo/blob/5afc4db51a383b67f096ff31dc7546827aceaa68/components/gfx_traits/lib.rs#L183)):*
> ```Rust
>     /// Returns a new stacking context ID for a special stacking context.
>     fn special_id() -> usize {
>         ((NEXT_SPECIAL_STACKING_CONTEXT_ID.fetch_add(1, Ordering::SeqCst) + 1) << 2) &
> ```

Perhaps add a comment here explaining the left shift. Is it likely in the future that the fragment type enum might be expanded? Perhaps reference this code in a comment from the fragment type enum?

---

*[ports/glutin/window.rs, line 84 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJrtNxAq6-WV9AZymc6:-KJrtNxAq6-WV9AZymc7:1879501134) ([raw file](https://github.com/servo/servo/blob/04b682195d2a75ad5961ec05ec1f7a1503c3f3f3/ports/glutin/window.rs#L84)):*
> ```Rust
>     }
>     builder.with_app_name(String::from("Servo"))
>            .with_transparent_corner_radius(8)
> ```

This seems unrelated to this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11680)*

**Comment by jdm** [comment]
Review status: 6 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/layout/layout_thread.rs, line 1302 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJq8qsAHU2deenQ9Qng:-KJtRNJXjhA9R5-C5szW:-894213133) ([raw file](https://github.com/servo/servo/blob/90932e0c6ff8411686bd14b4f49ecdc255de3b9e/components/layout/layout_thread.rs#L1302)):*
<details><summary><i>Previously, pcwalton (Patrick Walton) wrote…</i></summary>
> This is basically a symptom of the fact that script-initiated scrolling doesn't work at all in WebRender yet. All of our DOM-initiated scrolls are based on layers, which are not a concept that exists in the WebRender world.
> 
> How would you like me to fix this? Do you want me to implement script-initiated scrolling in WebRender before landing this patch? (It'll probably be a large change, larger than this patch itself.)
</details>
I didn't realize that webrender _completely_ broke script-initiated scrolling; that's fun! I propose we add a `script_can_initiate_scroll` function to `script/lib.rs` that checks if webrender is in use, then add `[Func="::script_can_initiate_scroll"]` annotations to the scrolling methods in Window.webidl and Element.webidl. This will help make it clear whether the methods are usable or not given the configuration that's being used for Servo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11680)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, pcwalton (Patrick Walton) wrote…</i></summary>
> r? @glennw for the `gfx_traits` bits
</details>


---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11680#-:-KJtT5Q_CJT-qQmLpInI:1458266033)*

**Comment by pcwalton** [comment]
Review status: 6 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/gfx_traits/lib.rs, line 182 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJrwCdpH6qs1onZRO-e:-KJwTFSp6HHe6fZD9lcL:-499146009) ([raw file](https://github.com/servo/servo/blob/5afc4db51a383b67f096ff31dc7546827aceaa68/components/gfx_traits/lib.rs#L182)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary>
> Perhaps call it next_special_id() ?
</details>
Done.

---

*[components/gfx_traits/lib.rs, line 183 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJrvJCBnv4vRhxkDRWP:-KJwTDzm6TXCLTLNf3MA:-499146009) ([raw file](https://github.com/servo/servo/blob/5afc4db51a383b67f096ff31dc7546827aceaa68/components/gfx_traits/lib.rs#L183)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary>
> Perhaps add a comment here explaining the left shift. Is it likely in the future that the fragment type enum might be expanded? Perhaps reference this code in a comment from the fragment type enum?
</details>
Done.

---

*[components/layout/layout_thread.rs, line 1302 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJq8qsAHU2deenQ9Qng:-KJwTHTRNs9eS1hOnpvn:-499146009) ([raw file](https://github.com/servo/servo/blob/90932e0c6ff8411686bd14b4f49ecdc255de3b9e/components/layout/layout_thread.rs#L1302)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> I didn't realize that webrender _completely_ broke script-initiated scrolling; that's fun! I propose we add a `script_can_initiate_scroll` function to `script/lib.rs` that checks if webrender is in use, then add `[Func="::script_can_initiate_scroll"]` annotations to the scrolling methods in Window.webidl and Element.webidl. This will help make it clear whether the methods are usable or not given the configuration that's being used for Servo.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11680)*

**Comment by pcwalton** [comment]
Review status: 6 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[ports/glutin/window.rs, line 84 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJrtNxAq6-WV9AZymc6:-KJwTarNCR4PU0S5xkJz:1740281843) ([raw file](https://github.com/servo/servo/blob/04b682195d2a75ad5961ec05ec1f7a1503c3f3f3/ports/glutin/window.rs#L84)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary>
> This seems unrelated to this PR?
</details>
Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11680)*

**Comment by jdm** [comment]
r=me with the remaining attributes annotated.
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, pcwalton (Patrick Walton) wrote…</i></summary>
> r? @jdm @glennw
</details>


---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/webidls/Element.webidl, line 100 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11680#-KJwUbKjuWXIfmyFmVt8:-KJwUbKjuWXIfmyFmVt9:1207147939) ([raw file](https://github.com/servo/servo/blob/78a11e441346cd3a3c47eb79d284384be51a75c2/components/script/dom/webidls/Element.webidl#L100)):*
> ```WebIDL
>   [Func="::script_can_initiate_scroll"]
>   void scrollBy(unrestricted double x, unrestricted double y);
>   attribute unrestricted double scrollTop;
> ```

scrollTop and scrollLeft need it as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11680#-:-KJwV1qhIon9efy3ANEw:-1572484272)*

**Comment by glennw** [comment]
@pcwalton The gfx traits related changes look good.

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11693

**Comment by metajack** [comment]
@bors-servo p=2

will help in london

**Pull request merged**
