### PR TITLE
Use struct rather than nsCSSValue::Array to store counter functions in Gecko

### PR DESCRIPTION
**Pull request by upsuper**
This is the Servo side change for [bug 1366735](https://bugzilla.mozilla.org/show_bug.cgi?id=1366735).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17016)

### CODE REVIEW

**Comment by upsuper** [comment]
(Hopefully this can get merged before I go to sleep.)

**Comment by nox** [comment]
When updating bindings, please put the commit doing so *before* anything else. If one bisects and end up on your PR's first commit, things won't build.

**Comment by upsuper** [comment]
It won't build in either order if they bisect into the middle of the two commits. Why would one want to bisect into a merge? Shouldn't a PR considered an atomic change?

**Comment by nox** [comment]
* It would definitely build if https://github.com/servo/servo/pull/17016/commits/4a535996473c6e2346bc9d1d80a13af827dcc58b came first.
 * One should not have commits where some tests don't pass or things don't build anyway.
 * It's non obvious to come up with a Git incantation that only stops on PR merges.

**Comment by nox** [comment]
Oh I see what you mean about the first part, you changed the type of a field? Then the two commits should have been squashed together.

In an ideal world, the bindings would live in a separate crate, and you would do the stylo changes at the same time as a breaking bump of that crate.

**Comment by upsuper** [comment]
It definitely wouldn't build that way. It would complain that `Gecko_SetContentDataArray` is unknown, and `array` is not indexable, etc.

**Comment by upsuper** [comment]
> In an ideal world, the bindings would live in a separate crate, and you would do the stylo changes at the same time as a breaking bump of that crate.

That would simply make landing anything even more painful than now.

**Comment by upsuper** [comment]
@bors-servo r-

I don't think the time is enough today for me to land the Gecko side code.

**Comment by upsuper** [comment]
@bors-servo retry

wat?!

**Pull request merged**
