### PR TITLE
Refactor(bluetooth): replace IPC channel with generic channel in BluetoothManager

### LINKED ISSUE #32411: [bluetooth] Replace IPC channel with GenericChannel
**Describe the new feature:**
With #32339, Servo now has a [generic channel](https://github.com/servo/servo/blob/main/components/shared/base/generic_channel.rs) that can select different channel implementation during runtime. This can help servo to use ipc channel if it's in multiprocess mode, and crossbeam channel if not.

There are lost of places that `ipc::channel` is used. Let's start with Bluetooth crate first since it only has two calls:

- [ ] Replace [`impl BluetoothThreadFactory for IpcSender<BluetoothRequest>`](https://github.com/servo/servo/blob/main/components/bluetooth/lib.rs#L76) with `impl BluetoothThreadFactory for GenericSender<BluetoothRequest>` instead
- [ ] Replace [`GetSelectedBluetoothDevice(Vec<String>, IpcSender<Option<String>>)`](https://github.com/servo/servo/blob/main/components/shared/embedder/lib.rs#L192) with `GetSelectedBluetoothDevice(Vec<String>, GenericSender<Option<String>>)`

Feel free to take one of them above and open the PRs. Or if you are interested in more other crates, open more issues like this. I'll also open some more in the future.

### PR DESCRIPTION
**Pull request by pewsheen**
From #32411

- Replace `impl BluetoothThreadFactory for IpcSender<BluetoothRequest>` with `impl BluetoothThreadFactory for GenericSender<BluetoothRequest>`
- In `ConstellationState` and `InitialConstellationState`
  - Replace member `bluetooth_ipc_sender` with `bluetooth_sender`

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #32411

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Review by wusyong — COMMENTED** [review]
This PR only fix first half of the issue. Perhaps the title should be replace IPC channel with generic channel in BluetoothManager.

**Review by mrobinson — COMMENTED** [review]
I think perhaps we shouldn't use the `GenericChannel` until we need a channel to be either IPC or crossbeam. If that's not the case then it's just an abstraction that makes it a bit harder to understand the code.

**Comment by mrobinson** [comment]
That said: If there are some benefits to always using crossbeam channels while in single-process mode, I would be happy to change my mind.

**Comment by wusyong** [comment]
I'm okay with these. My purpose for this PR and related issues is to create beginner issues.
But I still think it's a performance loss when we use ipc_channel in single process mode.
Perhaps we should enable multiprocess mode by default to actually test it?

**Comment by mrobinson** [comment]
One of the issues with the generic channel implementation is that there's a difference between what things can be sent over a crossbeam channel and what can be sent over an IPC channel. In particular, things sent over IPC channels must be serializable / deserializable. Making it generic in all cases might mean making data structures serializable when they don't actually need to be. I think we should use the generic channel in places that it makes sense -- when there's a good reason we want to make it more abstract, but not in every case. I'll close this for now.

**Pull request closed without merging**
