### PR TITLE
Improve properties.mako.rs file structure, take 2

### PR DESCRIPTION
**Pull request by perlun**
This is a new attempt of #10586, after Simon Sapin's great cleanups in #10749 has landed. I have adjusted the changes to the new structure that was introduced, and also only done a few of the longhand ones. Will certainly continue on this as soon as we have a basic agreement that this style is reasonable.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10774)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/style/properties/build.py, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrTjr6rqSR-CHuhm3P:-KFrTjr6rqSR-CHuhm3Q:565351088) ([raw file](https://github.com/servo/servo/blob/276ed42f7615e46a827197967316fba43b520e37/components/style/properties/build.py#L47)):*
This shouldn’t be necessary. Isn’t `properties_path` the same as `BASE`?

---

*[components/style/properties/data.py, line 137 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrTzVkbksxVexg1hQ-:-KFrTzVllFNuMJtzLR9m:-2019255739) ([raw file](https://github.com/servo/servo/blob/276ed42f7615e46a827197967316fba43b520e37/components/style/properties/data.py#L137)):*
Same comment as for the `to_rust_ident` method below.

---

*[components/style/properties/data.py, line 161 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrTqN56COqO3lOc6uv:-KFrTqN56COqO3lOc6uw:1775891878) ([raw file](https://github.com/servo/servo/blob/276ed42f7615e46a827197967316fba43b520e37/components/style/properties/data.py#L161)):*
This shouldn’t be necessary. Can’t these scopes use `<% from data import to_rust_ident %>`?

---

*[components/style/properties/properties.mako.rs, line 236 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrUDJCnqLfocSxY0wf:-KFrUDJD1aHvJ3_vgISJ:784018450) ([raw file](https://github.com/servo/servo/blob/276ed42f7615e46a827197967316fba43b520e37/components/style/properties/properties.mako.rs#L236)):*
Rather than passing `helpers=self` as an argument, could these helpers be moved to yet another file that would be used through `<%namespace>`? http://docs.makotemplates.org/en/latest/namespaces.html

---

*[components/style/properties/properties.mako.rs, line 242 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrbAIRsbByJFJUS2VD:-KFrbAIRsbByJFJUS2VE:1203468620) ([raw file](https://github.com/servo/servo/blob/276ed42f7615e46a827197967316fba43b520e37/components/style/properties/properties.mako.rs#L242)):*
These comments can be removed. They don’t make much sense now that we implement a number of properties beyond CSS 2.

---

*[components/style/properties/longhand/border.mako.rs, line 5 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrbJ7qTiwxrDLYbBjS:-KFrbJ7rsPh6-drHAV3b:-342514794) ([raw file](https://github.com/servo/servo/blob/276ed42f7615e46a827197967316fba43b520e37/components/style/properties/longhand/border.mako.rs#L5)):*
Is it necessary to specify `arg` as an argument, or is it automatically available as part of the "context"? (In other words: please try to remove this declaration and see what happens.)

---

*[python/tidy/servo_tidy/tidy.py, line 282 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrbiRlkRsVWXJt1nx8:-KFrbiRlkRsVWXJt1nx9:-1111604449) ([raw file](https://github.com/servo/servo/blob/276ed42f7615e46a827197967316fba43b520e37/python/tidy/servo_tidy/tidy.py#L282)):*
Maybe don’t add new lines but just replace the previous one with `endswith(".mako.rs")` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10774)*

**Comment by perlun** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/style/properties/build.py, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrTjr6rqSR-CHuhm3P:-KFuLLFko89dZJWllXgt:709094817) ([raw file](https://github.com/servo/servo/blob/d0489f1160419570b692a8729184ed833c93a433/components/style/properties/build.py#L47)):*
Thanks, good point! You're right; it is. Fixed.

---

*[components/style/properties/properties.mako.rs, line 236 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrUDJCnqLfocSxY0wf:-KFuLT9i0uANcG9MhVh3:-1529859561) ([raw file](https://github.com/servo/servo/blob/d0489f1160419570b692a8729184ed833c93a433/components/style/properties/properties.mako.rs#L236)):*
Yep. I had to move _a bunch_ of stuff as well (things that it depended on) but I think the end result was pretty good, so I am happy about that change.

---

*[components/style/properties/properties.mako.rs, line 242 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrbAIRsbByJFJUS2VD:-KFuLB5ZSMTmn_HftZik:1758359711) ([raw file](https://github.com/servo/servo/blob/d0489f1160419570b692a8729184ed833c93a433/components/style/properties/properties.mako.rs#L242)):*
Fixed.

---

*[components/style/properties/longhand/border.mako.rs, line 5 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrbJ7qTiwxrDLYbBjS:-KFuLFe1x2Q93Ke0XK6O:334074356) ([raw file](https://github.com/servo/servo/blob/d0489f1160419570b692a8729184ed833c93a433/components/style/properties/longhand/border.mako.rs#L5)):*
No, you're right; it can be omitted when you only have that as a single argument.

---

*[python/tidy/servo_tidy/tidy.py, line 282 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrbiRlkRsVWXJt1nx8:-KFuLdwEEiidREU4wmqP:-499146009) ([raw file](https://github.com/servo/servo/blob/d0489f1160419570b692a8729184ed833c93a433/python/tidy/servo_tidy/tidy.py#L282)):*
Done.

---

*[components/style/properties/data.py, line 137 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrTzVkbksxVexg1hQ-:-KFuLm7ejXQv4TPjhS5d:-499146009) ([raw file](https://github.com/servo/servo/blob/d0489f1160419570b692a8729184ed833c93a433/components/style/properties/data.py#L137)):*
Done.

---

*[components/style/properties/data.py, line 161 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10774#-KFrTqN56COqO3lOc6uv:-KFuLmkUIgS3-0aEpWzT:-499146009) ([raw file](https://github.com/servo/servo/blob/d0489f1160419570b692a8729184ed833c93a433/components/style/properties/data.py#L161)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10774)*

**Comment by perlun** [comment]
@SimonSapin, as mentioned on IRC, very good feedback from you here, thanks a lot. I applied all your suggestions (in a separate commit, and rebased them both on top of the current `master`). Please re-check to see if we are now fine with this.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10774#-:-KFuY_dT2L7mKq0W3H6n:1236647940)*

**Comment by SimonSapin** [comment]
@bors-servo p=10

This is blocking @bholley

**Comment by edunham** [comment]
Buildbot deploy to roll out https://github.com/servo/saltfs/pull/325 may affect this build, as noted on the mailing list. Sorry about the interruption!

**Comment by edunham** [comment]
@bors-servo retry

* infra

**Pull request merged**
