### PR TITLE
Allow `nightly-x86_64-pc-windows-gnu` to fail on AppVeyor.

### PR DESCRIPTION
**Pull request by frewsxcv**
Been failing for a while. Doesn't seem helpful to have it result in every PR getting a ❌

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14139)

### CODE REVIEW

**Comment by frewsxcv** [comment]
cc @Ms2ger @larsbergstrom

**Comment by frewsxcv** [comment]
Regarding `allow_failures`: https://www.appveyor.com/docs/build-configuration/

**Comment by frewsxcv** [comment]
If these changes are desired, it might make sense to wait for AppVeyor to finish testing before reviewing.

**Comment by larsbergstrom** [comment]
I thought that @metajack has been working on fixing https://github.com/servo/servo/issues/13939 ?

**Comment by frewsxcv** [comment]
Any reason to hold off on this change until Jack's stuff is ready?

**Comment by frewsxcv** [comment]
https://github.com/servo/servo/pull/14143 appears to be working, so closing.

**Pull request closed without merging**
