### PR TITLE
Remove stabilized features

### LINKED ISSUE #8706: Remove compiler warnings on attributes gating stable features
When building servo using the latest rust version, we have compiler warnings about unnecessary `#![feature]` attributes because they have since been stabilized in rust 1.6.

Code: `components/profile/lib.rs` (slice_splits), `components/net/lib.rs` (path_ext)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #8706.

cc @KiChjang

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8713)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Fixes #8709

**Comment by KiChjang** [comment]
Actually it fixes #8706

**Comment by Wafflespeanut** [comment]
@frewsxcv um, this is for #8706

**Pull request merged**
