### PR TITLE
docs: alphabetize glossary entries

### PR DESCRIPTION
**Pull request by kveretennicov**
Moves "Script" after "Renderer".

---

- [X] These changes do not require tests because it's a trivial documentation edit

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14914)

### CODE REVIEW

**Comment by kveretennicov** [comment]
AppVeyour apparently failed due to quota exceeded (https://ci.appveyor.com/project/servo/servo/build/1.0.12417/job/7rl5jyb3v7sr9bjr/messages):

> Build execution time has reached the maximum allowed time for your plan (90 minutes).

Travis and Homu failures are cryptic to me (I'm completely new to Servo build/CI), but don't look related to the PR content.

**Comment by KiChjang** [comment]
@kveretennicov I'm sorry to say that your guess is wrong :). The PR is failing due to Homu alone. Travis CI and AppVeyor do not gate PRs.

@bors-servo retry

**Pull request merged**
