### PR TITLE
Implemented `GetCachedMessages`

### PR DESCRIPTION
**Pull request by tamird**
Rebase of #4175, closes #4175. r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6168)

### CODE REVIEW

**Comment by jdm** [comment]
Ooh, thanks! I'll take a look through this on Monday!

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes +S-needs-rebase 

---

Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.
Reviewed files:
- components/devtools/actors/console.rs @ r1
- components/devtools_traits/lib.rs @ r1
- components/script/devtools.rs @ r1
- components/script/script_task.rs @ r1

---

<sup>**[components/devtools/actors/console.rs, line 90 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBtVKQWvTudDF-EZlm)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/devtools/actors/console.rs#L90)):</sup>
I 'd prefer to leave the message type string match in this code, and only send the script task an enum value.

---

<sup>**[components/devtools_traits/lib.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBtmyxNnkxVHjEsxw8)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/devtools_traits/lib.rs#L159)):</sup>
No need for the Message suffix on these variants. I'd also prefer to leave these definitions in devtools/ and use simpler types when possible for sending between the script and devtools tasks. For example, we could re-use the ConsoleMessage type directly above this.

---

<sup>**[components/devtools_traits/lib.rs, line 182 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBteeE6mNEd1W8cnnm)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/devtools_traits/lib.rs#L182)):</sup>
Vec<String>, I believe.

---

<sup>**[components/script/devtools.rs, line 144 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBue2LPL-ack64lR0B)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/script/devtools.rs#L144)):</sup>
Let's just return an empty vector here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6168)

**Comment by tamird** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/devtools/actors/console.rs, line 90 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBtVKQWvTudDF-EZlm)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/devtools/actors/console.rs#L90)):</sup>
Sounds good.

---

<sup>**[components/devtools_traits/lib.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBtmyxNnkxVHjEsxw8)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/devtools_traits/lib.rs#L159)):</sup>
How can we use a simpler type here? These definitions are from https://developer.mozilla.org/en-US/docs/Tools/Web_Console/remoting.

How do you decide where to move these types? I moved them because it saved me an import statement and they aren't currently used. The ConsoleMessage type above doesn't conform to what we need here (there seems to be a bit of a mess here, since there is also ConsoleMsg, yet another type).

---

<sup>**[components/script/devtools.rs, line 144 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBue2LPL-ack64lR0B)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/script/devtools.rs#L144)):</sup>
We could, but I wanted the commented out code to continue to be carried forward in case type changes are made (i.e. it will still compile).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6168)

**Comment by tamird** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/devtools_traits/lib.rs, line 182 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBteeE6mNEd1W8cnnm)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/devtools_traits/lib.rs#L182)):</sup>
Right, but a vec of what?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6168)

**Comment by jdm** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/devtools_traits/lib.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBtmyxNnkxVHjEsxw8)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/devtools_traits/lib.rs#L159)):</sup>
You're right; I was confused. These can stay where they are.

---

<sup>**[components/devtools_traits/lib.rs, line 182 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBteeE6mNEd1W8cnnm)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/devtools_traits/lib.rs#L182)):</sup>
Github ate my angle brackets: `Vec<String>`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6168)

**Comment by tamird** [comment]
Review status: 1 of 6 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/devtools/actors/console.rs, line 90 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqBtVKQWvTudDF-EZlm)** ([raw file](https://github.com/servo/servo/blob/c4d2d4c23467c6b1046669857074f4a6fdfe065b/components/devtools/actors/console.rs#L90)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6168)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- components/devtools/actors/console.rs @ r2
- components/devtools_traits/Cargo.toml @ r2
- components/devtools_traits/lib.rs @ r2
- components/script/devtools.rs @ r2
- components/servo/Cargo.lock @ r2

---

<sup>**[components/devtools/actors/console.rs, line 91 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqDBSjkPwX_D_EUAjas)** ([raw file](https://github.com/servo/servo/blob/d97fe5cd87e2678e540a60a87131fced5fa23983/components/devtools/actors/console.rs#L91)):</sup>
I'd prefer to move this into one or two separate bindings, so we just get something like `for str_type in &msg_types` instead.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6168)

**Comment by tamird** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/devtools/actors/console.rs, line 91 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6168#-JqDBSjkPwX_D_EUAjas)** ([raw file](https://github.com/servo/servo/blob/d97fe5cd87e2678e540a60a87131fced5fa23983/components/devtools/actors/console.rs#L91)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6168)

**Comment by jdm** [comment]
Go ahead and squash these together!
-S-awaiting-review +S-needs-squash -S-needs-rebase 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/devtools/actors/console.rs @ r3

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6168)

**Comment by tamird** [comment]
Done!

---

Review status: all files reviewed, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6168)

**Pull request merged**
