### PR TITLE
Do not return an error for non-GET data: requests (fixes #13293)

### LINKED ISSUE #13293: Remove method restricting on fetches of data URLs
https://github.com/whatwg/fetch/commit/c4cb4f4a5fa90a72f1000449495aec04f6c8c96b

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16311)

### CODE REVIEW

**Comment by KiChjang** [comment]
Huh, https://github.com/w3c/web-platform-tests/issues/3738 has been fixed a while ago. Did we not have a WPT update to catch those changes?

**Comment by nox** [comment]
Judging from https://github.com/w3c/web-platform-tests/blob/23cd07d4685d81024b7440e042f8bbdb33e7ddec/XMLHttpRequest/data-uri.htm, no.

**Comment by jdm** [comment]
I've been holding off on syncing until we figure out what to do with the big csswg import.

**Comment by KiChjang** [comment]
@bors-servo retry

* #16313

**Pull request merged**
