### PR TITLE
Remove unneeded dict sorting functions in CodegenRust.py

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9200)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r-

This changes the order as noticed by @Ms2ger. I can't read.

**Comment by frewsxcv** [comment]
@bors-servo r-

This changes the sort order

**Comment by frewsxcv** [comment]
@nox I force pushed a change that doesn't change the sort order, but still removes the functions. If it's no longer a desired change, feel free to close this

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2024 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9200#-K7g426F_11u2QlcMTHc:-K7g426F_11u2QlcMTHd:1662648895) ([raw file](https://github.com/servo/servo/blob/e6e13a9cb0543f02c75a4947bfe45256b77bc4c1/components/script/dom/bindings/codegen/CodegenRust.py#L2024)):*
You should still use `key=operator.itemgetter(0)` (or a lambda that looks less weird) to really not sort according to the values.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9200#-:-K7g4B186bjZwDdb08vr:1458266033)*

**Comment by frewsxcv** [comment]
Done

**Comment by Ms2ger** [comment]
@bors-servo retry
* #9014

**Comment by KiChjang** [comment]
```
Ran 9335 tests finished in 360.0 seconds.
  • 9334 ran as expected. 55 tests skipped.
  • 1 tests passed unexpectedly

Tests with unexpected results:
  ▶ PASS [expected FAIL] /css21_dev/html4/floats-wrap-bfc-002-right-table.htm
```
An intermittent pass?

**Comment by frewsxcv** [comment]
@bors-servo retry

#9014

**Pull request merged**
