### PR TITLE
Fix missing libraries for Windows

### LINKED ISSUE #12125: Windows Nightly blockers
The below bugs are the ones that are required to at least have a first linked nightly build of Servo on Windows.
- [x] #11307 - Hot spinning on Windows shutdown
- [x] #11967 - Add Windows MSI packaging and publishing of the nigthtly build
- [x] #11969 - Add an icon to Windows
- [x] #12231 - Upload failing due to bad `s3cmd` invocation
- [x] #12523 - Windows tarball missing files
- [x] #13257 - Very slow to load or just white screen launched from installer
- [x] #13371 - implement font rendering on Windows
- [x] #15255 - Windows servo UI missing elements
- [x] #15428 - Windows nightly hangs when loading pages
- [x] #15698 - Windows Servo renders reddit text squished
- [x] #12937 - Keyboard input dropouts

### PR DESCRIPTION
**Pull request by birkoffe**
Fix #12125

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12848)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@metajack Are these OK to distribute?

Emilio, I haven't fixed this to date because there are licensing issues if you include the full set of libraries. I *think* the right thing to do is to remove the ffmpeg support entirely, replacing it with mp4parse-rust.

That said, if this fixes the Windows MSI short-term, I don't mind landing this!

**Comment by metajack** [comment]
@larsbergstrom Those are all fine. The only thing that wasn't obvious was libbluray, but looks like it is circumvention-free according to http://www.videolan.org/developers/libbluray.html

**Pull request merged**
