### PR TITLE
Implement Storage::SupportedPropertyNames

### PR DESCRIPTION
**Pull request by leaexplores**
Hi guys,

This is a rough draft for issue #7670 .

It includes :
- SupportedPropertyNames implementation
- WPT with Object.supportedpropertynames with Local Storage and Session Storage.

The following link help me understood the issue :
http://www.w3.org/TR/webstorage/#the-storage-interface
https://html.spec.whatwg.org/multipage/infrastructure.html#supported-property-names

Thanks for looking into it.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7693)

### CODE REVIEW

**Comment by nox** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 113 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7693#-Jzijpf-7L5Pn4EWwql7)** ([raw file](https://github.com/servo/servo/blob/a10f4d3a5aa591bf6a6c1e14013b0b07f21b003f/components/net/storage_task.rs#L113)):</sup>
Why do you send `Option<Vec<DOMString>>` and not just a `Vec<DOMString>`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by ddrmanxbxfr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 113 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7693#-Jzijpf-7L5Pn4EWwql7)** ([raw file](https://github.com/servo/servo/blob/a10f4d3a5aa591bf6a6c1e14013b0b07f21b003f/components/net/storage_task.rs#L113)):</sup>
I wanted to stay consistent with the current interface in storage task. 

All the empty elements are handled using Options types instead of casting them to empty string or vec![].

It kinda make sense as we have pattern matching available in rust and it's explicit.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 122 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7693#-Jztu3EsHelh3aePE03Y)** ([raw file](https://github.com/servo/servo/blob/a10f4d3a5aa591bf6a6c1e14013b0b07f21b003f/components/net/storage_task.rs#L122)):</sup>
Align the `.unwrap()` with `.send(`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by nox** [comment]
-S-awaiting-answer +S-needs-code-changes 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 113 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7693#-Jzijpf-7L5Pn4EWwql7)** ([raw file](https://github.com/servo/servo/blob/a10f4d3a5aa591bf6a6c1e14013b0b07f21b003f/components/net/storage_task.rs#L113)):</sup>
I'm not convinced, see `length()` two methods above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by ddrmanxbxfr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 113 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7693#-Jzijpf-7L5Pn4EWwql7)** ([raw file](https://github.com/servo/servo/blob/a10f4d3a5aa591bf6a6c1e14013b0b07f21b003f/components/net/storage_task.rs#L113)):</sup>
https://github.com/ddrmanxbxfr/servo/blob/StorageSupportedAttributes/components/net_traits/storage_task.rs#L22

Length indeed provides a default value. However, key, setitem, getitem, removeitem all provides Option response as empty elements.

If we move to a Vec<DomString> when we have a empty element from IPCSender shall we send vec![] as default value ?

If yes, i'll unwrap the ipc object and provide a default value.

Thanks.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 113 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7693#-Jzijpf-7L5Pn4EWwql7)** ([raw file](https://github.com/servo/servo/blob/a10f4d3a5aa591bf6a6c1e14013b0b07f21b003f/components/net/storage_task.rs#L113)):</sup>
`vec![]` doesn't allocate anything, so you can just use `IpcSender<Vec<DOMString>>` and it will be fine.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by ddrmanxbxfr** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 113 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7693#-Jzijpf-7L5Pn4EWwql7)** ([raw file](https://github.com/servo/servo/blob/a10f4d3a5aa591bf6a6c1e14013b0b07f21b003f/components/net/storage_task.rs#L113)):</sup>
It's cool, removing the option thing :).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by ddrmanxbxfr** [comment]
@nox ping?

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 122 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7693#-K-eSGLqT2xgID_j0ytN)** ([raw file](https://github.com/servo/servo/blob/026467b07fdbabd48921566918b6b7d4d42d82ed/components/net/storage_task.rs#L122)):</sup>
You shouldn't be unwrapping here, but using:

```rust
data.get(&origin).map_or(vec![], |entry| entry.keys().cloned().collect()))
```

See the similar piece of code in length().


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by ddrmanxbxfr** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/net/storage_task.rs, line 122 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7693#-K-eSGLqT2xgID_j0ytN)** ([raw file](https://github.com/servo/servo/blob/026467b07fdbabd48921566918b6b7d4d42d82ed/components/net/storage_task.rs#L122)):</sup>
Indeed. Avoids to panic. Fixed.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by nox** [comment]
@bors-servo r+


---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7693)

**Comment by ddrmanxbxfr** [comment]
I'll rebase against master and see if test ref still fails on my desktop.

**Comment by jdm** [comment]
@bors-servo: r+
Don't worry, that was just #7730.

**Pull request merged**
