### PR TITLE
WIP: Fixes #11407: Implement Window.status

### LINKED ISSUE #11407: Implement Window.status
Blocks #2968.

Test expectations should be [updated](https://github.com/servo/servo/blob/master/tests/wpt/README.md#updating-test-expectations) for `./mach test-wpt tests/wpt/web-platform-tests/html/dom/interfaces.html`.

---
Spec: https://html.spec.whatwg.org/multipage/browsers.html#dom-window-status ([webidl](https://html.spec.whatwg.org/multipage/browsers.html#the-window-object:dom-window-status))
Code: `components/script/dom/webidl/Window.webidl` `components/script/dom/window.rs`

### PR DESCRIPTION
**Pull request by catchmrbharath**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #11407 (github issue number if applicable).

Either:
- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11434)

### CODE REVIEW

**Comment by catchmrbharath** [comment]
@Ms2ger mentioned in IRC that the tests won't work because of problems in codegen. I am reverting the test change back to FAIL.

I am not sure how to test these changes though. Any ideas ? @jdm

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes +C-needs-test 

<details><summary><i>Previously, catchmrbharath wrote…</i></summary>
> @Ms2ger mentioned in IRC that the tests won't work because of problems in codegen. I am reverting the test change back to FAIL.
> 
> 
> 
> I am not sure how to test these changes though. Any ideas ? @jdm 
</details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/window.rs, line 835 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11434#-KIg9D2lx79KWrNEalDc:-KIg9D2lx79KWrNEalDd:1689783281) ([raw file](https://github.com/servo/servo/blob/80e3e1166b0f56ff4b03e65144577fca41e5722b/components/script/dom/window.rs#L835)):*
> ```Rust
> 
>     fn Status(&self) -> DOMString {
>         self.status.borrow_mut().clone()
> ```

Just `.borrow()` is enough here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11434#-:-KIg9H5ld5Foun3scVRv:680524730)*

**Comment by ConnorGBrewster** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/window.rs, line 834 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11434#-KIh0VXf-UdqWg9N8rO3:-KIh0VXf-UdqWg9N8rO4:353722032) ([raw file](https://github.com/servo/servo/blob/80e3e1166b0f56ff4b03e65144577fca41e5722b/components/script/dom/window.rs#L834)):*
> ```Rust
>     }
> 
>     fn Status(&self) -> DOMString {
> ```

A comment should be added above this with a link to the spec: https://html.spec.whatwg.org/multipage/#dom-window-status

---

*[components/script/dom/window.rs, line 838 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11434#-KIh0eVsD6gJASM2N5Sr:-KIh0eVsD6gJASM2N5Ss:15540204) ([raw file](https://github.com/servo/servo/blob/80e3e1166b0f56ff4b03e65144577fca41e5722b/components/script/dom/window.rs#L838)):*
> ```Rust
>     }
> 
>     fn SetStatus(&self, status: DOMString) {
> ```

Same thing as above (same spec link aswell)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11434)*

**Comment by nox** [comment]
-C-needs-test -S-awaiting-review +C-has-test +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/wpt/web-platform-tests/html/browsers/the-window-object/browser-interface-elements/status.html, line 6 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11434#-KIlU61gEWey5hEaMsS4:-KIlU61gEWey5hEaMsS5:-1810562753) ([raw file](https://github.com/servo/servo/blob/001328fdffec8595f45519a285b8ae9fdad1caae/tests/wpt/web-platform-tests/html/browsers/the-window-object/browser-interface-elements/status.html#L6)):*
> ```HTML
> <script src="/resources/testharness.js"></script>
> <script src="/resources/testharnessreport.js"></script>
> <link rel="help" href="https://html.spec.whatwg.org/multipage/browsers.html#dom-window-status">
> ```

Nit: remove `browsers.html` from the link.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11434#-:-KIlUD0Z5XG0H2ae11If:-575406448)*

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11434#-:-KIlUyQD6f2j_cM8ndDW:1458266033)*

**Comment by catchmrbharath** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/wpt/web-platform-tests/html/browsers/the-window-object/browser-interface-elements/status.html, line 6 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11434#-KIlU61gEWey5hEaMsS4:-KIlVJ3FiSW8dz12QjY7:-1724046522) ([raw file](https://github.com/servo/servo/blob/001328fdffec8595f45519a285b8ae9fdad1caae/tests/wpt/web-platform-tests/html/browsers/the-window-object/browser-interface-elements/status.html#L6)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Nit: remove `browsers.html` from the link.
</details>
You mean remove the whole link?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11434)*

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/wpt/web-platform-tests/html/browsers/the-window-object/browser-interface-elements/status.html, line 6 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11434#-KIlU61gEWey5hEaMsS4:-KIlWMZcCRVI0cJcKSr3:303891522) ([raw file](https://github.com/servo/servo/blob/001328fdffec8595f45519a285b8ae9fdad1caae/tests/wpt/web-platform-tests/html/browsers/the-window-object/browser-interface-elements/status.html#L6)):*
<details><summary><i>Previously, catchmrbharath (Bharath Mankalale) wrote…</i></summary>
> You mean remove the whole link?
</details>
No, remove `browsers.html`, so that the link is the same as in the Rust code comment. The links with the filenames can change, while the others aren't supposed to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11434#-:-KIlWYmHaHv2R0bWcmn4:1458266033)*

**Comment by nox** [comment]
@bors-servo r+

Thanks for your contribution!

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11434#-:-KIlY9wdamsIZM4PCmlj:-1667711250)*

**Pull request merged**
