### PR TITLE
Fix #6315 Set default render mode on tests to cpu

### LINKED ISSUE #6315: `./mach test` and `./mach test-ref` should run just the CPU tests by default
The GPU-based reftests are not currently being supported or tested on our builders, and cause confusion when people accidentally run them.

I suspect something around here will need to be changed:
https://github.com/servo/servo/blob/master/python/servo/testing_commands.py#L137

### PR DESCRIPTION
**Pull request by ghost**
#6315

Set 'mach test-ref' default render mode to cpu and added a cli argument to 'mach test' to be able to select the render-mode, also renamed the 'kind' argument from 'test-ref' to '--render-mode' for coherence with reftest.rs

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6360)

### CODE REVIEW

**Comment by fbau123** [comment]
The proble is that it tries to call `./mach test-ref --kind cpu` but I renamed that argument to `--render-mode` so it is more descriptive and more coherent with other parts of the code, should I change it back?

**Comment by Ms2ger** [comment]
Yeah, that's probably best.

**Comment by Ms2ger** [comment]
@bors-servo: r+

Thank you!

**Pull request merged**
