### PR TITLE
Implement referrer policy delivery by header

### LINKED ISSUE #11860: Implement referrer policy delivery via header
See https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-header for details. 

Reference https://github.com/servo/servo/issues/10311 for servo referrer policy implementation thus far; tests generated in https://github.com/w3c/web-platform-tests/pull/3118.

### PR DESCRIPTION
**Pull request by aravind-pg**
Adds a new `Option<ReferrerPolicy>` field to Document and sets it appropriately in `ScriptThread::load` if a Referrer-Policy header is present.

r? @jdm

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11860
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12441)

### CODE REVIEW

**Comment by jdm** [comment]
Great work!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1, 8 of 8 files at r2, 26 of 26 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/script_thread.rs, line 1713 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMdjNEormtv4e_XqDVT:-KMdjNEormtv4e_XqDVU:1912407131) ([raw file](https://github.com/servo/servo/blob/5de7db2849c1d2e722cf4222da700885df509dcf/components/script/script_thread.rs#L1713)):*
> ```Rust
>         };
> 
>         use hyper::header::ReferrerPolicy as ReferrerPolicyHeader;
> ```

Let's add this with the other imports at the top of the file.

---

*[components/script/script_thread.rs, line 1715 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMdjSHbsUGBYRhbvIlu:-KMdjSHbsUGBYRhbvIlv:-607518530) ([raw file](https://github.com/servo/servo/blob/5de7db2849c1d2e722cf4222da700885df509dcf/components/script/script_thread.rs#L1715)):*
> ```Rust
>         use hyper::header::ReferrerPolicy as ReferrerPolicyHeader;
>         let referrer_policy = if let Some(headers) = metadata.headers {
>             match headers.get::<ReferrerPolicyHeader>() {
> ```

````
headers.get::<ReferrerPolicyHeader>().map(|h| match *h {
    ReferrerPolicyHeader::NoReferrer => ReferrerPolicy::NoReferrer,
    //etc
})
```

---

*[components/script/dom/document.rs, line 1662 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMdjsr0OREbLhgC7bXy:-KMdjsr1xQAat0prd4Bb:-1641701006) ([raw file](https://github.com/servo/servo/blob/5de7db2849c1d2e722cf4222da700885df509dcf/components/script/dom/document.rs#L1662)):*
> ```Rust
>         // Once other delivery methods are implemented, make the unset case really
>         // unset (i.e. None).
>         let referrer_policy = if referrer_policy.is_some() {
> ```

`let referrer_policy = referrer_policy.or(Some(ReferrerPolicy::NoReferrer));`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12441#-:-KMdl8p0tDHIbVCOAjTG:-1417728540)*
<!-- Sent from Reviewable.io -->

**Comment by aravind-pg** [comment]
Review status: 34 of 36 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/script_thread.rs, line 1713 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMdjNEormtv4e_XqDVT:-KMdxxhZq8apVLeb0oBL:2039046557) ([raw file](https://github.com/servo/servo/blob/5de7db2849c1d2e722cf4222da700885df509dcf/components/script/script_thread.rs#L1713)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Let's add this with the other imports at the top of the file.
</details>
Done. Do you think it yould nice to add a `use ReferrerPolicy::*;` locally to make things more readable? Bit noisy at present.

---

*[components/script/script_thread.rs, line 1715 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMdjSHbsUGBYRhbvIlu:-KMdyLnx4UIf9WclQOtq:-600404004) ([raw file](https://github.com/servo/servo/blob/5de7db2849c1d2e722cf4222da700885df509dcf/components/script/script_thread.rs#L1715)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> ````
> headers.get::<ReferrerPolicyHeader>().map(|h| match *h {
>     ReferrerPolicyHeader::NoReferrer => ReferrerPolicy::NoReferrer,
>     //etc
> })
> ```
</details>
Great suggestion, done.

---

*[components/script/dom/document.rs, line 1662 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMdjsr0OREbLhgC7bXy:-KMdyXL-eD4nTUzNNuHD:-284748874) ([raw file](https://github.com/servo/servo/blob/5de7db2849c1d2e722cf4222da700885df509dcf/components/script/dom/document.rs#L1662)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> `let referrer_policy = referrer_policy.or(Some(ReferrerPolicy::NoReferrer));`
</details>
Nice, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12441)*

**Comment by aravind-pg** [comment]
Incidentally, is there any interest in renaming `NoRefWhenDowngrade` `NoReferrerWhenDowngrade`? Right it now it sticks out a bit as being somewhat inconsistent with the other variants.

**Comment by jdm** [comment]
I agree, renaming that variant would make it more consistent.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/script_thread.rs, line 1713 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMdjNEormtv4e_XqDVT:-KMe6C9XIv89MIcx-Xut:1982670286) ([raw file](https://github.com/servo/servo/blob/5de7db2849c1d2e722cf4222da700885df509dcf/components/script/script_thread.rs#L1713)):*
<details><summary><i>Previously, aravind-pg (Aravind Gollakota) wrote…</i></summary>
> Done. Do you think it yould nice to add a `use ReferrerPolicy::*;` locally to make things more readable? Bit noisy at present.
</details>
I could go either way. I think it's fine as-is.

---

*[components/script/script_thread.rs, line 1725 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMe69AXHbK77F_vL0cL:-KMe69AXHbK77F_vL0cM:-255094659) ([raw file](https://github.com/servo/servo/blob/0488d5dd476021a3e7bca39f71a7dcb5d0289d51/components/script/script_thread.rs#L1725)):*
> ```Rust
>                     ReferrerPolicy::Origin,
>                 ReferrerPolicyHeader::OriginWhenCrossOrigin =>
>                     ReferrerPolicyHeader::OriginWhenCrossOrigin,
> ```

This doesn't look like it compiles :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12441#-:-KMe6UuGxouGaD9f_bvr:1979839934)*

**Comment by aravind-pg** [comment]
Whoops! Will fix later today

**Comment by aravind-pg** [comment]
Rebased, renamed the variant and fixed the compile-error typo.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/script_thread.rs, line 1713 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMdjNEormtv4e_XqDVT:-KMhDPhFQkmxVfh_jzyf:81697249) ([raw file](https://github.com/servo/servo/blob/5de7db2849c1d2e722cf4222da700885df509dcf/components/script/script_thread.rs#L1713)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> I could go either way. I think it's fine as-is.
</details>
I'll just leave it as-is then.

---

*[components/script/script_thread.rs, line 1725 \[r4\]](https://reviewable.io:443/reviews/servo/servo/12441#-KMe69AXHbK77F_vL0cL:-KMhDaQ41OWTPodZDf-A:1758359698) ([raw file](https://github.com/servo/servo/blob/0488d5dd476021a3e7bca39f71a7dcb5d0289d51/components/script/script_thread.rs#L1725)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> This doesn't look like it compiles :)
</details>
Fixed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12441#-:-KMhDiF2Kq-HLAVtgAds:1499312609)*

**Comment by jdm** [comment]
@bors-servo: r+
Yay!

---

Reviewed 30 of 30 files at r5, 8 of 8 files at r6, 26 of 26 files at r7, 6 of 6 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12441#-:-KMjYfsnAlwpplGm51sI:-1396490138)*

**Pull request merged**
