### PR TITLE
style: Add a document state invalidator.

### PR DESCRIPTION
**Pull request by emilio**
Don't use it yet (since I was working from a Servo tree). Will hook it up and improve in the Gecko bug.

Right now it takes a `StyleRuleCascadeData`, which means that if all the origins in the document have state selectors we could do just one walk over the tree and not multiple, that will be improved.

Other than that, this is completely untested of course, but I prefer to land it, given I don't think it's complex, and work on the Gecko integration separately. The reason for this is that I also plan to fix the `<slot>` bugs, which will change `StyleRuleCascadeData` and such, and I want the two bugs to conflict as little as possible.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19747)

### CODE REVIEW

**Comment by upsuper** [comment]
Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/style/data.rs, line 266 at r3](https://reviewable.io:443/reviews/servo/servo/19747#-L2bXhg-OdX7F7bckqJz:-L2bUrs2zapdKW_nvGkd:bqax1wk) ([raw file](https://github.com/servo/servo/blob/74fef390112ab2301613d6d683214e551a078dae/components/style/data.rs#L266)):*
> ```Rust
>         let mut xbl_stylists = SmallVec::<[_; 3]>::new();
>         // FIXME(emilio): This is wrong, needs to account for ::slotted rules
>         // that may apply to elements down the tree.
> ```

I don't understand this FIXME. Could you elaborate it? Specifically, what case in your mind would be incorrectly handled because of this?

---

*[components/style/invalidation/element/document_state.rs, line 25 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bk3EJZdA7lTyJ8r5t:-L2bk3EJZdA7lTyJ8r5u:b-claowk) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L25)):*
> ```Rust
> /// changes.
> pub struct DocumentStateInvalidationProcessor<'a, E: TElement> {
>     rules: &'a StyleRuleCascadeData,
> ```

Wouldn't you need to iterate over cascade data from all origins and all bindings? It doesn't seem to me a single `StyleRuleCascadeData` is enough here.

---

*[components/style/invalidation/element/document_state.rs, line 57 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bj7aTBOGaMhk-L7P3:-L2bj7aUcg_4xXS7Ua_O:bge1kyc) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L57)):*
> ```Rust
>     fn collect_invalidations(
>         &mut self,
>         _element: E,
> ```

Maybe add a `debug_assert!` that `element.is_root()`?

---

*[components/style/invalidation/element/document_state.rs, line 88 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bcc3OkeBkrwaM6Is9:-L2bcc3PIOTpJgIV1DSf:boltoxg) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L88)):*
> ```Rust
>             None => return false,
>         };
>         state_and_attributes::should_process_descendants(&data)
> ```

```rust
match element.borrow_data() {
    Some(d) => state_and_attributes::should_process_descendants(&d),
    None => false,
}
```
or maybe just
```rust
element.borrow_data()
    .map(|d| state_and_attributes::should_process_descendants(&d))
    .unwrap_or(false)
```
?

(I actually wanted to raise this in #19744 as well).

---

*[components/style/servo/selector_parser.rs, line 381 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bkL2YKHoD9J0ElSVQ:-L2bkL2YKHoD9J0ElSVR:bomvgu8) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/servo/selector_parser.rs#L381)):*
> ```Rust
>     type NonTSPseudoClass = NonTSPseudoClass;
> 
>     type ExtraMatchingData = InvalidationMatchingData;
> ```

Given you are adding this to Servo as well... I don't see any point of having `ExtraMatchingData` at all now.

Consider either leaving it null type, and mark `DocumentStateInvalidator` Gecko-only, or replacing the `extra_data` field with something like `invalidation_matching_data`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/style/invalidation/element/document_state.rs, line 25 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bk3EJZdA7lTyJ8r5t:-L2dXrKLW7aW-Xn2095R:b1l6jyq) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L25)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Wouldn't you need to iterate over cascade data from all origins and all bindings? It doesn't seem to me a single `StyleRuleCascadeData` is enough here.
</blockquote></details>

The idea is to call this for each bound element, so we only invalidate what's needed on the trees where it's needed.

We still need to call this three times for the root with UA / User / Author cascade datas, but that's what I say I want to improve before hooking it up.

---

*[components/style/invalidation/element/document_state.rs, line 57 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bj7aTBOGaMhk-L7P3:-L2dY9a4wpIHDABo5Y8Q:b-ers2f2) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L57)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Maybe add a `debug_assert!` that `element.is_root()`?
</blockquote></details>

Per the above, element may not be the root if it's from an XBL binding.

---

*[components/style/invalidation/element/document_state.rs, line 88 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bcc3OkeBkrwaM6Is9:-L2dYJhK3qs_yhDnaLS3:b-fp6vlf) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L88)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

```rust
match element.borrow_data() {
    Some(d) => state_and_attributes::should_process_descendants(&d),
    None => false,
}
```
or maybe just
```rust
element.borrow_data()
    .map(|d| state_and_attributes::should_process_descendants(&d))
    .unwrap_or(false)
```
?

(I actually wanted to raise this in #19744 as well).
</blockquote></details>

I usually prefer the early return, but I agree in this case there's not too much of a point for it, so will change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/style/data.rs, line 266 at r3](https://reviewable.io:443/reviews/servo/servo/19747#-L2bXhg-OdX7F7bckqJz:-L2dZzN7OAMMYh-7aSpL:b9l21mo) ([raw file](https://github.com/servo/servo/blob/74fef390112ab2301613d6d683214e551a078dae/components/style/data.rs#L266)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

I don't understand this FIXME. Could you elaborate it? Specifically, what case in your mind would be incorrectly handled because of this?
</blockquote></details>

https://bugzilla.mozilla.org/show_bug.cgi?id=1429846 is the case that doesn't work right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by upsuper** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/style/invalidation/element/document_state.rs, line 25 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bk3EJZdA7lTyJ8r5t:-L2dakHfJBZl7xM7_5Du:bcfgaud) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L25)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

The idea is to call this for each bound element, so we only invalidate what's needed on the trees where it's needed.

We still need to call this three times for the root with UA / User / Author cascade datas, but that's what I say I want to improve before hooking it up.
</blockquote></details>

Sounds like you will be invalidating elements in binding tree multiple times for nested bindings? In addition, wouldn't you need to call this for each binding base as well? That really sounds like a lot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/style/invalidation/element/document_state.rs, line 25 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bk3EJZdA7lTyJ8r5t:-L2deolzu2j4QAPOMe6V:bl7k5o) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L25)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Sounds like you will be invalidating elements in binding tree multiple times for nested bindings? In addition, wouldn't you need to call this for each binding base as well? That really sounds like a lot.
</blockquote></details>

Hmm, nested bindings are fun indeed...  In most of the cases these selectors won't exist though, so we'll invalidate style only on the subtrees where they could be affected...

I don't think we'd end up with much more work compared to matching the selectors unconditionally on the whole DOM tree...

Anyway, I'll figure out the best way, maybe doing some profiling on the bug where I integrate them. It's just a matter of changing this for a `&'a [StyleRuleCascadeData]`, so I'd still prefer to land this as is for now until I figure that out.

---

*[components/style/servo/selector_parser.rs, line 381 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bkL2YKHoD9J0ElSVQ:-L2deUAa4O7DhGx7bqto:b-dt48o0) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/servo/selector_parser.rs#L381)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

Given you are adding this to Servo as well... I don't see any point of having `ExtraMatchingData` at all now.

Consider either leaving it null type, and mark `DocumentStateInvalidator` Gecko-only, or replacing the `extra_data` field with something like `invalidation_matching_data`.
</blockquote></details>

I just left it because I don't think selectors should know about invalidation, but I guess that point is moot because we already have AllLinksVisitedAndUnvisited for this... So will do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by upsuper** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[components/style/invalidation/element/document_state.rs, line 25 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bk3EJZdA7lTyJ8r5t:-L2dgglGEmjTL9TXEpdk:b-dbug9u) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L25)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

Hmm, nested bindings are fun indeed...  In most of the cases these selectors won't exist though, so we'll invalidate style only on the subtrees where they could be affected...

I don't think we'd end up with much more work compared to matching the selectors unconditionally on the whole DOM tree...

Anyway, I'll figure out the best way, maybe doing some profiling on the bug where I integrate them. It's just a matter of changing this for a `&'a [StyleRuleCascadeData]`, so I'd still prefer to land this as is for now until I figure that out.
</blockquote></details>

OK, but please leave a comment somewhere mentioning this issue just in case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/style/servo/selector_parser.rs, line 381 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bkL2YKHoD9J0ElSVQ:-L2dh4uC_QKhqO0LW2hP:b7q7vsh) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/servo/selector_parser.rs#L381)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

I just left it because I don't think selectors should know about invalidation, but I guess that point is moot because we already have AllLinksVisitedAndUnvisited for this... So will do that.
</blockquote></details>

Actually maybe ExtraMatchingData is just fine. We may want to stash other non-invalidation stuff there (I'd have moved the pseudo-matching function if we didn't need the special-case in matches-complex-selector). Would you be fine with keeping the name? Otherwise I can change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by upsuper** [comment]
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/style/servo/selector_parser.rs, line 381 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bkL2YKHoD9J0ElSVQ:-L2di_XNE-MU6QlyQ_lX:bhb1dfd) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/servo/selector_parser.rs#L381)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

Actually maybe ExtraMatchingData is just fine. We may want to stash other non-invalidation stuff there (I'd have moved the pseudo-matching function if we didn't need the special-case in matches-complex-selector). Would you be fine with keeping the name? Otherwise I can change it.
</blockquote></details>

I agree that selectors shouldn't know about invalidation, but doesn't that indicate it's more reasonable to move `InvalidationMatchingData` into `MatchingContext` rather than having it being an associated type in `SelectorImpl`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by emilio** [comment]
Review status: 9 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/style/invalidation/element/document_state.rs, line 25 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bk3EJZdA7lTyJ8r5t:-L2djEp1FbOQbbHMH4we:b-896fix) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/invalidation/element/document_state.rs#L25)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

OK, but please leave a comment somewhere mentioning this issue just in case.
</blockquote></details>

Done.

---

*[components/style/servo/selector_parser.rs, line 381 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bkL2YKHoD9J0ElSVQ:-L2djF_4uzMLoOsNr5qi:b2evdek) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/servo/selector_parser.rs#L381)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

I agree that selectors shouldn't know about invalidation, but doesn't that indicate it's more reasonable to move `InvalidationMatchingData` into `MatchingContext` rather than having it being an associated type in `SelectorImpl`?
</blockquote></details>

I agree, but `selectors` doesn't have a clue about `DocumentState`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by upsuper** [comment]
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[components/style/servo/selector_parser.rs, line 381 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bkL2YKHoD9J0ElSVQ:-L2dkIMdRu90gqF25reO:b-hyeax3) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/servo/selector_parser.rs#L381)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

I agree, but `selectors` doesn't have a clue about `DocumentState`.
</blockquote></details>

OK, so `DocumentState` is part of the `style` crate and we don't want `selectors` crate to reference it... We don't expose `ElementState` to `selectors` either.

I would probably suggest, then, that we have `ExtraMatchingData` implement `Default`, and use `Default::default()` for initialization. It doesn't seem to make much sense to do `Option<DocumentState>`, since an empty document state is enough for when we are not using it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by upsuper** [comment]
Review status: 6 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/style/data.rs, line 266 at r3](https://reviewable.io:443/reviews/servo/servo/19747#-L2bXhg-OdX7F7bckqJz:-L2doo1_JAfIeVtfJsdL:b-hkwvt0) ([raw file](https://github.com/servo/servo/blob/74fef390112ab2301613d6d683214e551a078dae/components/style/data.rs#L266)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

https://bugzilla.mozilla.org/show_bug.cgi?id=1429846 is the case that doesn't work right now.
</blockquote></details>

OK I probably understand now. So we need to find the shadow root in of the element in the flattened tree and take stylesheets of that into consider as well. Do I understand it right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by upsuper** [comment]
Reviewed 2 of 2 files at r6, 1 of 1 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/invalidation/element/document_state.rs, line 86 at r6](https://reviewable.io:443/reviews/servo/servo/19747#-L2dpV90DAmUJM1M-ZOo:-L2dpV91qCrNWh1PW6TY:bxqj7uv) ([raw file](https://github.com/servo/servo/blob/1d51a9297097b75080473f9d005d24cbc6ace24f/components/style/invalidation/element/document_state.rs#L86)):*
> ```Rust
>         match element.borrow_data() {
>             Some(d) => state_and_attributes::should_process_descendants(&d),
>             None => return false,
> ```

`return` is unnecessary... but I guess it's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by upsuper** [comment]
r=me with or without the `return` bit fixed.

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/style/data.rs, line 266 at r3](https://reviewable.io:443/reviews/servo/servo/19747#-L2bXhg-OdX7F7bckqJz:-L2dpznhEYyW0AqiTBCh:bbqvr1u) ([raw file](https://github.com/servo/servo/blob/74fef390112ab2301613d6d683214e551a078dae/components/style/data.rs#L266)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

OK I probably understand now. So we need to find the shadow root in of the element in the flattened tree and take stylesheets of that into consider as well. Do I understand it right?
</blockquote></details>

Well, that's for matching ::slotted, yes, which is kind of annoying. For invalidation you need to use the stylesheets of the shadow root you're on, since slotted would match on the <slot>.

On this patch, we store the slotted rule invalidation data separately, and that means that each_applicable_non_document_style_rule_data doesn't find it for the parents of the slot.

The fix is merging back the invalidation maps, so we look at slotted rules for all elements in the shadow root.

---

*[components/style/invalidation/element/document_state.rs, line 86 at r6](https://reviewable.io:443/reviews/servo/servo/19747#-L2dpV90DAmUJM1M-ZOo:-L2dpxIN_T6GbJZQxZYJ:b-o79niv) ([raw file](https://github.com/servo/servo/blob/1d51a9297097b75080473f9d005d24cbc6ace24f/components/style/invalidation/element/document_state.rs#L86)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

`return` is unnecessary... but I guess it's fine.
</blockquote></details>

Err, indeed, will remove.

---

*[components/style/servo/selector_parser.rs, line 381 at r5](https://reviewable.io:443/reviews/servo/servo/19747#-L2bkL2YKHoD9J0ElSVQ:-L2dpOmgnEmvgLcU0vz1:be8i6w9) ([raw file](https://github.com/servo/servo/blob/6ad37c3e397b60d64cb3be7e620c243e06cbd3e1/components/style/servo/selector_parser.rs#L381)):*
<details><summary><i>Previously, upsuper (Xidorn Quan) wrote…</i></summary><blockquote>

OK, so `DocumentState` is part of the `style` crate and we don't want `selectors` crate to reference it... We don't expose `ElementState` to `selectors` either.

I would probably suggest, then, that we have `ExtraMatchingData` implement `Default`, and use `Default::default()` for initialization. It doesn't seem to make much sense to do `Option<DocumentState>`, since an empty document state is enough for when we are not using it.
</blockquote></details>

Did that, keeping the wrapping struct since it's cleaner at the callsites.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by emilio** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/style/data.rs, line 266 at r3](https://reviewable.io:443/reviews/servo/servo/19747#-L2bXhg-OdX7F7bckqJz:-L2dr-u6PRq7KfhuxJ4q:bv3geu9) ([raw file](https://github.com/servo/servo/blob/74fef390112ab2301613d6d683214e551a078dae/components/style/data.rs#L266)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary><blockquote>

Well, that's for matching ::slotted, yes, which is kind of annoying. For invalidation you need to use the stylesheets of the shadow root you're on, since slotted would match on the <slot>.

On this patch, we store the slotted rule invalidation data separately, and that means that each_applicable_non_document_style_rule_data doesn't find it for the parents of the slot.

The fix is merging back the invalidation maps, so we look at slotted rules for all elements in the shadow root.
</blockquote></details>

s/since slotted would match on the/since invalidation needs to reach the <slot>.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/19747)*

**Comment by emilio** [comment]
Oh gosh, that was supposed to be `<slot>`. Anyway :)

**Comment by emilio** [comment]
Err, thought I had pushed the return bit.

@bors-servo r=upsuper

**Comment by emilio** [comment]
@bors-servo r=upsuper

 * fixed `selectors` unit tests.

**Pull request merged**
