### PR TITLE
WPT tests now show debug ouput for passing tests as well

### LINKED ISSUE #12808: Include stdout/stderr output in default filtered view from failed WPT tests
This would fix the common case of people adding `println!()` and getting confused when they don't see any change in the output. Usually we need to add `--log-mach -` to see the result, but you always need someone more experienced to tell you that if you're new.

### PR DESCRIPTION
**Pull request by nikhilshagri**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix (partially) #12808 

@jdm I thought it would be better to make a PR for my local changes anyway, since you wanted it :)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15124)

### CODE REVIEW

**Comment by jgraham** [comment]
I guess I don't exactly know what you want, but this seems like a pretty surprising change; the point of the grouping formatter was to have as little output as possible. Maybe a simpler alternative would be just to switch to using `--log-mach` by default locally and use this one only in CI?

**Comment by jdm** [comment]
@jgraham The default formatter is in an interesting position. On one hand, minimizing the output for passing tests is often valuable. On the other hand, we regularly have contributors adding println! and debug! to code that executes during a passing test and becoming confused when no output appears. --log-mach is completely undiscoverable, so I lean towards addressing that problem. Maybe we could change the default based on whether a singles test is being run versus multiple ones.

**Comment by jgraham** [comment]
That seems very possible. Just change the default in `tests/wpt/run.py` according to `len(kwargs.get(tests), []) == 1` or something.

**Comment by jdm** [comment]
@cynicaldevil Want to revert the changes in this PR and make the one suggested in the previous comment instead?

**Comment by cynicaldevil** [comment]
Sure, I'll do it tomorrow.

**Comment by cynicaldevil** [comment]
Updated the PR.

**Comment by jdm** [comment]
Huh, that doesn't get overridden by https://github.com/cynicaldevil/servo/blob/3fd5122930e2d009769ac455e0d5ce4768b5a0af/tests/wpt/run.py#L32-L34 ?

**Comment by cynicaldevil** [comment]
Using print messages I found that `wptrunner.setup_logging()` does create two logger objects, but only the second one is used. If I commented out https://github.com/cynicaldevil/servo/blob/3fd5122930e2d009769ac455e0d5ce4768b5a0af/tests/wpt/run.py#L34 and ran a single test, I found that aside from some stderr messages and test metadata, everything was being printed.

**Comment by jdm** [comment]
What if we make the code clearer by moving the other logger into an else branch?

**Comment by cynicaldevil** [comment]
@jdm done.

**Comment by mbrubeck** [comment]
@bors-servo r-

* Trying to get homu un-stuck

**Comment by emilio** [comment]
Let's try syncing homu

**Comment by Ms2ger** [comment]
@cynicaldevil please find me on IRC when you can? Thanks

**Pull request merged**
