### PR TITLE
Disable Android CI builds

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
So long, Android!

**Comment by CYBAI** [comment]
This PR only removes the android CI builds so I believe this is an intermittent.
But, I'm not sure if there's an existing one for it 👀?

```
  ▶ FAIL [expected PASS] /css/CSS2/positioning/left-056.xht
  │   → /css/CSS2/positioning/left-056.xht 0b7dd821d6234d26c19bbf09815a358695c6f015
  └   → /css/CSS2/reference/ref-black-96px-square-no-red.xht 2d20aca73fe80e40c4fdf131b58467f209c0a571
```

**Comment by jdm** [comment]
Looking at the test-wpt.log in https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer-structured.xhtml shows that it's #23290.

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by Darkspirit** [comment]
In the future this could be revived by #23691.

**Comment by jdm** [comment]
More importantly, reviving it will require:
* Upgrading the NDK to v20
* Writing surfman integration code that we're not bothering to write in #25853

**Comment by Darkspirit** [comment]
SM 71 has NDK 20 patches: [bug 1577220](https://bugzilla.mozilla.org/show_bug.cgi?id=1577220) (Upgrade from NDK 17b to 20)

**Pull request merged**
