### PR TITLE
Allow Firefox to be able to connect to devtools again

### PR DESCRIPTION
**Pull request by nox**
This doesn't fix the performance tab, but at least lets Firefox initialise the devtools window.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10158)

### CODE REVIEW

**Comment by Ms2ger** [comment]
```
./components/devtools/lib.rs:78: mod declaration is not in alphabetical order
	expected: timeline
	found: thread
```

r+ with that fixed.

**Comment by nox** [comment]
```
10:30 <•Ms2ger> r+ it? I don't have the tab anymore
```

@bors-servo r=Ms2ger

**Comment by nox** [comment]
Y U NO REUSE

**Pull request merged**
