### PR TITLE
Instructions for building with the MSVC toolchain

### LINKED ISSUE #13206: Adding Documentation for MSVC
In the light of #12916's completion, it's important to let the contributors know how to setup their Windows environments for Servo. 

Files to modify: Anything with documentation (ie, README.md)

cc @larsbergstrom

### PR DESCRIPTION
**Pull request by larsbergstrom**
Adding instructions to build using the MSVC toolchain.

r? @vvuk 

---

- [x ] `./mach build -d` does not report any errors
- [x ] `./mach test-tidy` does not report any errors
- [x ] These changes fix #13206 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13621)

### CODE REVIEW

**Comment by Coder206** [comment]
@larsbergstrom Do you know if it's possible to get Visual C++ Build Tools to work instead of having to install full Visual Studio?

**Comment by larsbergstrom** [comment]
@Coder206 I do not know - I have not tried yet on a clean machine. All of the ones I have right now have several copies of Visual Studio installed on them :-)

**Comment by larsbergstrom** [comment]
or r? @metajack

**Pull request merged**
