### PR TITLE
workers implementation merged with new repository implementation

### PR DESCRIPTION
**Pull request by shreyabastikar**

### CODE REVIEW

**Comment by jdm** [comment]
@shreyabastikar Thanks! One problem is that the commit author email address needs to be associated with your github account, too, or it will break our automated build infrastructure.

**Comment by shreyabastikar** [comment]
Hi,

I am sorry! I did not understand. I have a github account on my gmail
address shreyabastikar@gmail.com. I have used this email address previously
as well for creating pull requests. Do you want me to commit this using
Ronak's repository?

Thanks & Regards,
Shreya Bastikar

**Comment by jdm** [comment]
The commit author is your NCSU email address, according to https://github.com/shreyabastikar/servo/commit/49ca48223080c3f66941476d82430d1b52600809.patch . The github account email does not appear to be public, which could break our automation.

**Comment by jdm** [comment]
I've left comments on Critic. There are what look to be some unintentional indentation changes, and some values that don't need to be passed around in the new message. The meat of the changes look good, however!

**Comment by metajack** [comment]
Note that the email address doesn't need to be public. If it's associated and private, that works fine.

**Comment by jdm** [comment]
Rebased in #4854.

**Pull request closed without merging**
