### PR TITLE
stylo: Bug 1343153 - Use servo css-parser for ParseEasing

### PR DESCRIPTION
**Pull request by BorisChiou**
These patches fix [Bug 1343153](https://bugzilla.mozilla.org/show_bug.cgi?id=1343153).

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix Bug 1343153
- [X] These changes do not require tests because gecko has enough test cases for web animations.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16055)

### CODE REVIEW

**Comment by nox** [comment]
Shouldn't the second and last commits be squashed together? How does the second commit build without the last one?

**Comment by BorisChiou** [comment]
OK, Let me squash them. Thanks

**Pull request merged**
