### PR TITLE
Handle devtools clients disconnecting better

### LINKED ISSUE #27509: Panic after closing devtools panel

### PR DESCRIPTION
**Pull request by jdm**
These changes fix many opportunities for the devtools server to panic if a client disconnects early. Now that it's easy to have multiple clients connected simultaneously, this also makes it easier for server code to distinguish between different clients and ensure that one client disconnecting doesn't affect another client that's still connected.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #27509
- [x] These changes do not require tests because the devtools server is a wild west.

### CODE REVIEW

**Comment by Manishearth** [comment]
```
./components/devtools/lib.rs:130: derivable traits list is not in alphabetical order
```

**Comment by jdm** [comment]
@bors-servo retry
* #21067

**Pull request merged**
