### PR TITLE
Make resource requests cancelable (issue 4974)

### PR DESCRIPTION
**Pull request by marcusklaas**
My attempt at tackling issue https://github.com/servo/servo/issues/4974. Note that even though it should be possible to cancel requests now, it is not actually used anywhere yet.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5826)

### CODE REVIEW

**Comment by jdm** [comment]
Thanks for this PR @marcusklaas! There are two main issues with the code right now:
* the hashmap in the resource manager never has elements removed from it
* we need to ensure that we send a `Done(Err)` result any time a cancelled request returns early, which will allow consumers to know that there are no more messages pending.

I think we can solve both of these problems together by creating an AutoResponseCleanup value that has a destructor that:
* sends a message to the resource task to remove the appropriate value from the hashmap
* calls start_sending/sends a Done(Err) value/does nothing as appropriate (we can trigger different states based on how we progress through the response

Does that make sense?

**Comment by jdm** [comment]
Reviewed files:
- components/net/about_loader.rs @ r1
- components/net/data_loader.rs @ r1
- components/net/file_loader.rs @ r1
- components/net/http_loader.rs @ r1
- components/net/image_cache_task.rs @ r1
- components/net/resource_task.rs @ r1
- components/net_traits/lib.rs @ r1
- components/script/dom/xmlhttprequest.rs @ r1
- components/script/script_task.rs @ r1
- tests/unit/net/data_loader.rs @ r1
- tests/unit/net/resource_task.rs @ r1

---

<sup>**[components/net/file_loader.rs, line 39 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5826#-Jo-qTjArfWjUOHKyMCY)** ([raw file](https://github.com/servo/servo/blob/58d7e37bf53f0fb69b1bf22837e827915c6090bd/components/net/file_loader.rs#L39)):</sup>
We should be checking for cancellation in here, too.

---

<sup>**[components/net/http_loader.rs, line 354 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5826#-Jo-quiLyx3gcFUSkBDr)** ([raw file](https://github.com/servo/servo/blob/58d7e37bf53f0fb69b1bf22837e827915c6090bd/components/net/http_loader.rs#L354)):</sup>
We should be checking for cancellation in here, too.

---

<sup>**[components/net/resource_task.rs, line 251 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5826#-Jo-r3RYQGK06EKBtC9D)** ([raw file](https://github.com/servo/servo/blob/58d7e37bf53f0fb69b1bf22837e827915c6090bd/components/net/resource_task.rs#L251)):</sup>
We should just silently drop this request if it's not in the hashmap.

---

<sup>**[components/net/resource_task.rs, line 290 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5826#-Jo-rDDSXaBMj4cmkIIY)** ([raw file](https://github.com/servo/servo/blob/58d7e37bf53f0fb69b1bf22837e827915c6090bd/components/net/resource_task.rs#L290)):</sup>
resource_sender.map

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5826)

**Comment by marcusklaas** [comment]
Thank you for feedback and patience Josh! I understand the issues, but it's not exactly clear to me where this `AutoResponseCleanup` value would work, and where it would live, specifically. 

Please forgive my ignorance, but can't we just remove the relevant item from the hash map when we receive a cancel control message. This would solve the first issue, no?

**Comment by jdm** [comment]
Well, we also need to remove the item when the response is complete, regardless if it was canceled or not.

**Comment by jdm** [comment]
@marcusklaas With respect to where it would live, the struct definition and its methods can live in resource_task.rs. I envision it being used like so:

```rust
let mut response_cleanup = AutoResponseCleanup::new(...);
...
// send request
response_cleanup.note_request_sent();
// if response_cleanup is destroyed after this point via an early return, it will avoid calling start_sending
...
// read complete response
response_cleanup.note_response_complete()
// if response_cleanup is destroyed after this point, it will not send a `Done` message, since one has already been sent
```
The destructor would look something like:
```rust
impl Drop for AutoResponseCleanup {
    fn drop(&mut self) {
        // if start_sending has not been called {
            let tx = start_sending(...);
            tx.send(Done(Err));
        } else if // response incomplete {
            self.stored_progress_chan.send(Done(Err));
        }
        self.resource_task.send(Cleanup(self.id));
    }
}
```

Is that more clear?

**Comment by marcusklaas** [comment]
Apologies for the delay in addressing these issues. I very much intend to finish this in the next couple of days.

**Comment by jdm** [comment]
Not a problem!

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes +S-fails-tidy 

We still need to add the auto removal and Done message sending as described previously.

---

Reviewed files:
- components/net/file_loader.rs @ r2
- components/net/http_loader.rs @ r2
- components/net/resource_task.rs @ r2

---

<sup>**[components/net/file_loader.rs, line 36 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5826#-JobsYhzbpOW4jqTEAYZ)** ([raw file](https://github.com/servo/servo/blob/8e2eb8d6cba1bc472e48e493319b22cf2bc29d28/components/net/file_loader.rs#L36)):</sup>
I would prefer an enum value for clarity.

---

<sup>**[components/net/http_loader.rs, line 363 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5826#-JobsqAF7TbNdIZPBujn)** ([raw file](https://github.com/servo/servo/blob/8e2eb8d6cba1bc472e48e493319b22cf2bc29d28/components/net/http_loader.rs#L363)):</sup>
Enum for clarity.

---

<sup>**[components/net/resource_task.rs, line 251 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5826#-Jobt7JJIQoy-15zLcix)** ([raw file](https://github.com/servo/servo/blob/8e2eb8d6cba1bc472e48e493319b22cf2bc29d28/components/net/resource_task.rs#L251)):</sup>
Use `if let` instead of `map` when the return value isn't being used.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5826)

**Comment by marcusklaas** [comment]
This has bitrotten terribly and I don't think I can bring this to a proper end any more.. Shall I close this PR?

Sorry for taking up your time, @jdm! :worried:

**Comment by jdm** [comment]
Not a problem! This helped expose complexities in the design, so it served a useful purpose :)

**Pull request closed without merging**
