### PR TITLE
Fix #3936 – {Window,WorkerGlobalScope}.set{Timeout,Interval}(DOMString)

### LINKED ISSUE #3936: Implement {Window,WorkerGlobalScope}.set{Timeout,Interval}(DOMString).
Tested by at least `workers/WorkerGlobalScope_setTimeout.htm` and `workers/WorkerGlobalScope_setInterval.htm`.

### PR DESCRIPTION
**Pull request by guillaumebort**

### CODE REVIEW

**Comment by guillaumebort** [comment]
I can't solve the latest issue:

```rust
borrowed value does not live long enough:
let global = global_object_for_js_object(this).root()
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Of course the solution seems to store the intermediate value first, but I can't because of the lint `#[deny(unrooted_must_root)]`.

Do you see any other solution for this?

**Comment by jdm** [comment]
Huh, ok. Let's ignore my request for the separate local value, in that case.

**Comment by jdm** [comment]
These can be rebased and squashed into one commit now :)

**Comment by guillaumebort** [comment]
Ready!

**Comment by jdm** [comment]
Thanks for sticking with this!

**Comment by jdm** [comment]
One example of a number of crashes:
```
 1:12.08 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) ""
 1:12.08 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "task 'ScriptTask' panicked at 'called `Result::unwrap()` on an `Err` value: FailureUnknown', /home/larsberg/rust/src/libcore/result.rs:789"
 1:12.08 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "stack backtrace:"
 1:12.19 TEST_END: Thread-TestrunnerManager-1 TIMEOUT
 1:12.19 TEST_START: Thread-TestrunnerManager-1 /XMLHttpRequest/xmlhttprequest-timeout-overrides.html
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "   1:     0x7f47fc2562c0 - rt::backtrace::imp::write::h83394c9d811f80f16Ss"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "   2:     0x7f47fc259310 - failure::on_fail::h66ce8c5cd14ce043Tet"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "   3:     0x7f47fc275450 - unwind::begin_unwind_inner::h4d92541238adf4bcPad"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "   4:     0x7f47fc2750d0 - unwind::begin_unwind_fmt::hd0f802b9c1361fb6h8c"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "   5:     0x7f47fc275090 - rust_begin_unwind"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "   6:     0x7f47fc2a86f0 - panicking::panic_fmt::h2110c8a227c1cd0dwil"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "   7:     0x7f47fb558360 - result::Result<T, E>::unwrap::h3393280924469118036"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "   8:     0x7f47fb556530 - timers::TimerManager::fire_timer::h8404035512456134325"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "   9:     0x7f47fb5564b0 - dom::window::JSRef<'a, Window>.WindowHelpers::handle_fire_timer::h0b9340f6a6ba0d02hPv"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  10:     0x7f47fb633eb0 - script_task::ScriptTask::handle_fire_timer_msg::hcfb9593295152c50HyA"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  11:     0x7f47fb62ef50 - script_task::ScriptTask::handle_msg_from_script::hea5b0d05f57ba6d1buA"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  12:     0x7f47fb60bed0 - script_task::ScriptTask::handle_msgs::h5c2eeff32df51049elA"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  13:     0x7f47fb60be80 - script_task::ScriptTask::start::h452b52f12c4a0a903kA"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  14:     0x7f47fac008b0 - script_task::ScriptTask.ScriptTaskFactory::create::closure.10209"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  15:     0x7f47fbd84f10 - rtinstrument::instrument::h3733598bd9cf0da1L1e"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  16:     0x7f47fabfcd20 - task::spawn_named_with_send_on_failure::closure.10108"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  17:     0x7f47fabf2950 - task::TaskBuilder<S>::try_future::closure.9928"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  18:     0x7f47fad53270 - task::NativeSpawner.Spawner::spawn::closure.2478"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  19:     0x7f47fc275fe0 - rust_try_inner"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  20:     0x7f47fc275fd0 - rust_try"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  21:     0x7f47fc273500 - unwind::try::h537628c5bb6502f7rZc"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  22:     0x7f47fc2733a0 - task::Task::run::ha64607f767ea68e7h5b"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  23:     0x7f47fad52fb0 - task::NativeSpawner.Spawner::spawn::closure.2404"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  24:     0x7f47fc2745b0 - thread::thread_start::h25d825d1e964c603nqc"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  25:     0x7f47f99c80c0 - start_thread"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  26:     0x7f47f91d7f89 - __clone"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "  27:                0x0 - <unknown>"
 1:12.21 PROCESS_OUTPUT: Thread-TestrunnerManager-4 (pid:14457) "Pipeline failed in hard-fail mode.  Crashing!"
 1:12.24 CRASH: Thread-TestrunnerManager-4 pid:4191. Test:None. Minidump anaylsed:False. Signature:[/XMLHttpRequest/xmlhttprequest-timeout-aborted.html]

 1:12.24 TEST_END: Thread-TestrunnerManager-4 CRASH, expected TIMEOUT
```

```
/XMLHttpRequest/xmlhttprequest-timeout-aborted.html
---------------------------------------------------
CRASH expected TIMEOUT [Parent]
/html/semantics/embedded-content/the-iframe-element/iframe_sandbox_allow_script.html
------------------------------------------------------------------------------------
CRASH expected TIMEOUT [Parent]
/html/webappapis/scripting/processing-model-2/compile-error-in-setInterval.html
-------------------------------------------------------------------------------
FAIL expected NOTRUN window.onerror - compile error in setInterval
FAIL expected NOTRUN window.onerror - compile error in setInterval (column)
OK expected TIMEOUT [Parent]
/html/webappapis/scripting/processing-model-2/compile-error-in-setTimeout.html
------------------------------------------------------------------------------
FAIL expected NOTRUN window.onerror - compile error in setTimeout
FAIL expected NOTRUN window.onerror - compile error in setTimeout (column)
OK expected TIMEOUT [Parent]
/html/webappapis/scripting/processing-model-2/runtime-error-in-setInterval.html
-------------------------------------------------------------------------------
FAIL expected NOTRUN window.onerror - runtime error in setInterval
FAIL expected NOTRUN window.onerror - runtime error in setInterval (column)
OK expected TIMEOUT [Parent]
/html/webappapis/scripting/processing-model-2/runtime-error-in-setTimeout.html
------------------------------------------------------------------------------
FAIL expected NOTRUN window.onerror - runtime error in setTimeout
FAIL expected NOTRUN window.onerror - runtime error in setTimeout (column)
OK expected TIMEOUT [Parent]
/old-tests/submission/Opera/script_scheduling/079.html
------------------------------------------------------
CRASH expected TIMEOUT [Parent]
```

**Comment by guillaumebort** [comment]
Thanks, I will have a look.

**Comment by guillaumebort** [comment]
Ok I've updated the *ini files. Some tests that were expected to TIMEOUT because of the failing implementing of `setTimeout` and `setInterval` now FAIL or CRASH.

**Comment by jdm** [comment]
Before we merge changes that mark tests as expected to crash, I'd like to make sure we understand why the crash occurs. In this case, I missed the change at https://github.com/servo/servo/commit/1f62a6ad14d044720ecd14410a1b54cf3e70d278?diff=unified#diff-86707d952414a2860b78bcf6c1db8e2eR190 . Unwrapping here is not what we want, since obviously execution can fail sometimes.

**Comment by guillaumebort** [comment]
Ah yes that's right. What would be the good way on handling error? I noticed that everywhere else they are just printed on the console. Should I do the same for now? In this case I think that the tests will still fail (since these tests check the window.onerror behaviour), but they should just FAIL instead of CRASH.

**Comment by jdm** [comment]
The previous code just dropped it on the floor silently using `let _ =`, so let's keep that.

**Comment by guillaumebort** [comment]
Ok no more tests are expected to crash.

**Comment by jdm** [comment]
Great! We'll merge this after the Rust upgrade PR is merged.

**Pull request merged**
