### PR TITLE
Switch back to pinning Rust by Nightly date instead of commit hash…

### PR DESCRIPTION
**Pull request by SimonSapin**
… this time using a `rust-toolchain` file compatible with rustup: https://github.com/rust-lang-nursery/rustup.rs/#the-toolchain-file

And upgrade to rustc 1.21.0-nightly (c11f689d2 2017-08-29)

----

Now if both `system-rust` and `system-cargo` are set to `true` in `.servobuild`’s `[tools]` section, and the corresponding `rustc` and `cargo` binaries are in fact rustup’s wrappers, then rustup will use the correct version based on `rust-toolchain`.

CC https://github.com/servo/servo/issues/11361

Unlike https://github.com/servo/servo/pull/17927, this does not make mach use rustup directly. That should wait until https://github.com/rust-lang-nursery/rustup.rs/issues/1099 is fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18325)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@paulrouget Would this help you?

**Comment by SimonSapin** [comment]
Note that rustup does not automatically install the specified version if it’s missing. Instead it fails with an error like:

```
error: override toolchain 'nightly-2017-08-30' is not installed
info: caused by: the toolchain file at '/home/simon/servo2/rust-toolchain' specifies an uninstalled toolchain
```

The fix is to run `rustup install $(cat rust-toolchain)`. (Maybe there should be a `rustup` sub-command for that?)

**Comment by paulrouget** [comment]
So this would add a `rust-toolchain` file in servo?

That would help a lot. At the moment, I have to find manually which rustup nightly match the servo rustc build.

**Comment by SimonSapin** [comment]
Yes, this PR adds `rust-toolchain` to replace `rust-commit-hash` (which previously replaced `rust-nightly-date`).

Since [version 1.5.0](https://users.rust-lang.org/t/rustup-1-5-0-released/11529), rustup uses that file to determine which toolchain to use.

**Comment by SimonSapin** [comment]
@bors-servo p=1

The next nightly broke something, I’ll do another rustup on top of this.

**Comment by SimonSapin** [comment]
@bors-servo retry

```
exceptions.Exception: Actual commit (b4393ef386b35e004ec1d595d1358c98eba5a0f7) differs from requested commit (53e5fe578dc3cb2883cb28981ba70b78f34aea4a)
```

**Comment by stshine** [comment]
Awesome!

**Pull request merged**
