### PR TITLE
Parse size attribute of HTMLInputElemnt correctly

### LINKED ISSUE #8773: <input> with no specified value or size has incorrect width
```
$ cat /tmp/hi.html
<input>
```

Chrome (and Firefox):

screen shot 2015-12-01 at 8 07 30 pm

Servo:

screen shot 2015-12-01 at 8 07 36 pm

[Relevant section of spec](https://html.spec.whatwg.org/multipage/#the-input-element-as-a-text-entry-widget:the-input-element-5)

### PR DESCRIPTION
**Pull request by TheKK**
Should fix #8773

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9119)

### CODE REVIEW

**Comment by eefriedman** [comment]
You can rearrange the order of the match statement to avoid duplicated code.

A reftest would be nice.

**Comment by TheKK** [comment]
Sure, I'll try and learn how testing works.

**Comment by jdm** [comment]
@TheKK http://testthewebforward.org/docs/reftests.html and http://mxr.mozilla.org/servo/source/tests/wpt/README.md#99

**Comment by frewsxcv** [comment]
Feel free to take the tests I mentioned in the original issue: ﻿https://github.com/servo/servo/issues/8773

**Comment by Ms2ger** [comment]
Sorry, we're no longer accepting new tests under `tests/ref`. See `tests/wpt/README.md`.

**Comment by eefriedman** [comment]
@TheKK Please squash the commits.  Make sure the commit message for the squashed commit contains "fixes #8773".

@Ms2ger this seems to be hitting #8535 (weird manifest changes); is it okay to merge as is?  If not, suggestions?

**Comment by Ms2ger** [comment]
Ugh. Just land the manifest changes, I guess.

Do remove my FIXME comment though, please.

**Comment by eefriedman** [comment]
@TheKK As Ms2ger said, you can also delete the comment referring to this bug.  (`// FIXME(Ms2ger): this is nonsense! Invalid values also end up as a text field`)

**Comment by TheKK** [comment]
Oh, my bad. I read it as "Do not remove" :p

**Comment by KiChjang** [comment]
@bors-servo retry
* #9163

**Comment by KiChjang** [comment]
@bors-servo retry
* #9124

**Comment by TheKK** [comment]
Just wondering. What happened after you tell the bot to rebuild with a certain issue number?

**Comment by KiChjang** [comment]
@TheKK it's simply a way for us to track intermittent errors. We link it to an existing issue so that we know all of the instances where the intermittent errors happened.

**Comment by TheKK** [comment]
Thanks for explain. I thought the bot will magically skip the tests mentioned by these issues.

**Pull request merged**
