### PR TITLE
Yet another batch of arbitrary improvements to our WebGL stuff

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21701)

### CODE REVIEW

**Comment by jdm** [comment]
Uh oh.
```
  ▶ TIMEOUT [expected OK] /_webgl/conformance/reading/read-pixels-test.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.1.0-devel
  │ DESCRIPTION: Checks that ReadPixels works as expected.
  │ 
  │ checking: in range
  │ PASS color pixel at 0, 0 should be about 51,153,102,255, was = 51,153,102,255
  │ PASS color pixel at 1, 0 should be about 51,153,102,255, was = 51,153,102,255
  │ PASS color pixel at 0, 1 should be about 51,153,102,255, was = 51,153,102,255
  │ PASS color pixel at 1, 1 should be about 51,153,102,255, was = 51,153,102,255
  │ 
  │ checking: off top left
  │ PASS color pixel at 0, 0 should be about 19,72,0,198, was = 19,72,0,198
  │ PASS color pixel at 1, 0 should be about 19,72,0,198, was = 19,72,0,198
  │ PASS color pixel at 0, 1 should be about 19,72,0,198, was = 19,72,0,198
  │ PASS color pixel at 1, 1 should be about 51,153,102,255, was = 51,153,102,255
  │ 
  │ checking: off bottom right
  │ PASS color pixel at 0, 0 should be about 51,153,102,255, was = 51,153,102,255
  │ FAIL color pixel at 1, 0 should be about 19,72,0,198, was = 51,153,102,255
  │ FAIL color pixel at 0, 1 should be about 19,72,0,198, was = 51,153,102,255
  │ FAIL color pixel at 1, 1 should be about 19,72,0,198, was = 51,153,102,255
  │ 
  │ checking: completely off top
  │ PASS color pixel at 0, 0 should be about 19,72,0,198, was = 19,72,0,198
  │ PASS color pixel at 1, 0 should be about 19,72,0,198, was = 19,72,0,198
  │ PASS color pixel at 0, 1 should be about 19,72,0,198, was = 19,72,0,198
  │ PASS color pixel at 1, 1 should be about 19,72,0,198, was = 19,72,0,198
  │ 
  │ checking: completely off bottom
  │ FAIL color pixel at 0, 0 should be about 19,72,0,198, was = 51,153,102,255
  │ FAIL color pixel at 1, 0 should be about 19,72,0,198, was = 51,153,102,255
  │ FAIL color pixel at 0, 1 should be about 19,72,0,198, was = 51,153,102,255
  │ FAIL color pixel at 1, 1 should be about 19,72,0,198, was = 51,153,102,255
  │ 
  │ checking: completely off left
  │ PASS color pixel at 0, 0 should be about 19,72,0,198, was = 19,72,0,198
  │ PASS color pixel at 1, 0 should be about 19,72,0,198, was = 19,72,0,198
  │ PASS color pixel at 0, 1 should be about 19,72,0,198, was = 19,72,0,198
  │ PASS color pixel at 1, 1 should be about 19,72,0,198, was = 19,72,0,198
  │ 
  │ checking: completeley off right
  │ FAIL color pixel at 0, 0 should be about 19,72,0,198, was = 51,153,102,255
  │ FAIL color pixel at 1, 0 should be about 19,72,0,198, was = 51,153,102,255
  │ FAIL color pixel at 0, 1 should be about 19,72,0,198, was = 51,153,102,255
  │ FAIL color pixel at 1, 1 should be about 19,72,0,198, was = 51,153,102,255
  │ PASS getError was expected value: NO_ERROR : there should be no GL errors
  │ 
  │ check invalid format or type
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as DEPTH_COMPONENT
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as DEPTH_STENCIL
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as 0x8229
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as RGBA4
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as LUMINANCE
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as LUMINANCE_ALPHA
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as 0x1903
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as 0x8228
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as 0x8d99
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as 0x84fa
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as UNSIGNED_SHORT
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as SHORT
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as BYTE
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as UNSIGNED_INT
  │ FAIL getError expected: INVALID_ENUM. Was INVALID_OPERATION : Should not be able to read as 0x8368
  │ 
  │ check invalid combinations of format/type
  │ PASS getError was expected value: NO_ERROR : Should be able to read as RGBA / UNSIGNED_BYTE
  │ PASS getError was expected value: INVALID_OPERATION : Should not be able to read as RGB / UNSIGNED_BYTE
  │ PASS getError was expected value: INVALID_OPERATION : Should not be able to read as RGB / UNSIGNED_SHORT_5_6_5
  │ PASS getError was expected value: INVALID_OPERATION : Should not be able to read as RGBA / UNSIGNED_SHORT_5_5_5_1
  │ PASS getError was expected value: INVALID_OPERATION : Should not be able to read as RGBA / UNSIGNED_SHORT_4_4_4_4
  │ PASS getError was expected value: INVALID_OPERATION : Should not be able to read as ALPHA / UNSIGNED_BYTE
  │ 
  └ check reading with lots of drawing
```

**Comment by jdm** [comment]
I am chuckling.
```
  ▶ TIMEOUT [expected OK] /_webgl/conformance/canvas/rapid-resizing.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 18.1.0-devel
  │ ERROR 2018-09-13T19:48:52Z: script::dom::webglrenderingcontext: Couldn't create WebGLRenderingContext: preserveDrawingBuffer is not supported yet
  │ ERROR 2018-09-13T19:48:53Z: script::dom::webglrenderingcontext: Couldn't create WebGLRenderingContext: preserveDrawingBuffer is not supported yet
  │ DESCRIPTION: Verifies that rapidly resizing the canvas works correctly.
  │ 
  │ Regression test for Chromium <a href='http://crbug.com/299371'>Issue 299371</a> and <a href='http://crbug.com/557848'>Issue 557848</a>
  │ 
  │ requestAnimationFrame
  │ Testing preserveDrawingBuffer = true
  │ FAIL Unable to fetch WebGL rendering context for Canvas
  │ FAIL context does not exist
  │ Testing preserveDrawingBuffer = false
  │ PASS context exists
  │ PASS program is non-null.
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  │ PASS upper right should be green
  │ PASS lower left should be green
  │ PASS lower right should be green
  │ PASS upper left should be green
  └ PASS upper right should be green

  ▶ Unexpected subtest result in /_webgl/conformance/canvas/rapid-resizing.html:
  └ NOTRUN [expected PASS] Overall test
```

**Comment by nox** [comment]
@bors-servo retry

Network issues it seems.

**Pull request merged**
