### PR TITLE
remove unused static collection type in htmlcollection.rs

### PR DESCRIPTION
**Pull request by vectorijk**
ref #7042 

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7219)

### CODE REVIEW

**Comment by dzbarsky** [comment]
Thanks for the PR!
You can turn the enum into a struct now since there's only 1 possibility. That will eliminate all the pointless match statements.

**Comment by vectorijk** [comment]
@dzbarsky I have turned enum into struct. However, it has conflicts cause I checked out from 233a769c67738942a0ac47c15465e36891883c3b and confilct with 45145108daa6af7e834a7c23530857c504b54b9c

```diff
diff --git a/components/script/dom/htmlcollection.rs b/components/script/dom/htmlcollection.rs
index bd1bb29..acf5a3d 100644
--- a/components/script/dom/htmlcollection.rs
+++ b/components/script/dom/htmlcollection.rs
@@ -27,8 +27,10 @@ pub trait CollectionFilter : JSTraceable {
 pub struct Collection(JS<Node>, Box<CollectionFilter+'static>);
 
 #[dom_struct]
+#[derive(HeapSizeOf)]
 pub struct HTMLCollection {
     reflector_: Reflector,
+    #[ignore_heap_size_of = "Contains a trait object; can't measure due to #6870"]
     collection: Collection,
 }
 
@@ -54,7 +56,7 @@ impl HTMLCollection {
 
     fn all_elements(window: &Window, root: &Node,
                     namespace_filter: Option<Namespace>) -> Root<HTMLCollection> {
-        #[derive(JSTraceable)]
+        #[derive(JSTraceable, HeapSizeOf)]
         struct AllElementFilter {
             namespace_filter: Option<Namespace>
         }
```

I think change name of `Collection` in `pub struct HTMLCollection` cause conflict and need to be solved.

**Comment by jdm** [comment]
That looks like the right solution to me.

**Comment by vectorijk** [comment]
@dzbarsky @jdm rebased

**Comment by Ms2ger** [comment]
Thank you.

`#[allow(unrooted_must_root)]` is wrong; you should keep the `#[must_root]` annotation.

**Comment by vectorijk** [comment]
@Ms2ger  done.

**Comment by Ms2ger** [comment]
Excellent, thank you!

@bors-servo r+

**Comment by vectorijk** [comment]
@Ms2ger rebased. r?

**Comment by Ms2ger** [comment]
Sorry about that, let's try again.

@bors-servo r+

**Pull request merged**
