### PR TITLE
Implement weak-referenceable JS-managed objects

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8147)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 4 of 9 files at r3.
Review status: 4 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4472 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2HXM38_DmgKJZMLwHz)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/codegen/CodegenRust.py#L4472)):</sup>
Neither "box" nor "ptr" means anything.


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4475 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2HaiI6pne-hG1GpEOs)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/codegen/CodegenRust.py#L4475)):</sup>
Assert that it was >= 1 before?


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4480 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Habc-Q05CdOHqe7bq)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/codegen/CodegenRust.py#L4480)):</sup>
drop()?


---

<sup>**[components/script/dom/bindings/weakref.rs, line 5 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Hbn10u-QgDqsPA4HF)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L5)):</sup>
Add more docs about how it works.


---

<sup>**[components/script/dom/bindings/weakref.rs, line 30 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2HbUXawjn3NINVl9WS)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L30)):</sup>
Would it make sense to move the finalization code into a function here?


---

<sup>**[components/script/dom/bindings/weakref.rs, line 33 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Ha6_1_iIgK3R-ubqS)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L33)):</sup>
Where the pointee contributes one reference?


---

<sup>**[components/script/dom/bindings/weakref.rs, line 80 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Hbwqp-X2aAln-6lvU)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L80)):</sup>
Make this private?


---

<sup>**[components/script/dom/bindings/weakref.rs, line 109 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2HcDnFJDJYsJSvTo82)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L109)):</sup>
Assert it wasn't zero


---

<sup>**[components/script/dom/bindings/weakref.rs, line 121 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Hccfixta8uKjAzebe)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L121)):</sup>
I don't understand what this is for.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8147)

**Comment by nox** [comment]
Review status: 4 of 9 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4472 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2HXM38_DmgKJZMLwHz)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/codegen/CodegenRust.py#L4472)):</sup>
Sure, suggest better names. :)


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4475 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2HaiI6pne-hG1GpEOs)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/codegen/CodegenRust.py#L4475)):</sup>
Ok.


---

<sup>**[components/script/dom/bindings/weakref.rs, line 30 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2HbUXawjn3NINVl9WS)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L30)):</sup>
I don't think so, this way it lives only in codegen and can't be misused. The function would be on WeakBox and I don't think that's a good idea.


---

<sup>**[components/script/dom/bindings/weakref.rs, line 33 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Ha6_1_iIgK3R-ubqS)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L33)):</sup>
The pointee?


---

<sup>**[components/script/dom/bindings/weakref.rs, line 80 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Hbwqp-X2aAln-6lvU)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L80)):</sup>
No, I intend to use it.


---

<sup>**[components/script/dom/bindings/weakref.rs, line 121 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Hccfixta8uKjAzebe)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L121)):</sup>
It's a wrapper to a weak reference, I don't plan to make WeakRef clean itself. That's the job of this structure. I plan to have other wrappers in the future, for vectors and whatnot.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8147)

**Comment by Ms2ger** [comment]
Reviewed 1 of 9 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4757 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2vFomfstx25JKQW1bG)** ([raw file](https://github.com/servo/servo/blob/7daa1430a9d1204a9c1d863978d913facfadbe7f/components/script/dom/bindings/codegen/CodegenRust.py#L4757)):</sup>
`assert descriptor.weakReferenceable`.


---

<sup>**[components/script/dom/bindings/weakref.rs, line 33 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Ha6_1_iIgK3R-ubqS)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L33)):</sup>
The DOM object.


---

<sup>**[components/script/dom/bindings/weakref.rs, line 121 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Hccfixta8uKjAzebe)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L121)):</sup>
I still don't see the point, but whatever.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8147)

**Comment by nox** [comment]
-S-needs-rebase 


---

Review status: 2 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4475 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2HaiI6pne-hG1GpEOs)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/codegen/CodegenRust.py#L4475)):</sup>
Done.


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4480 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Habc-Q05CdOHqe7bq)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/codegen/CodegenRust.py#L4480)):</sup>
Done.


---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4757 \[r4\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2vFomfstx25JKQW1bG)** ([raw file](https://github.com/servo/servo/blob/7daa1430a9d1204a9c1d863978d913facfadbe7f/components/script/dom/bindings/codegen/CodegenRust.py#L4757)):</sup>
Done.


---

<sup>**[components/script/dom/bindings/weakref.rs, line 33 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8147#-K2Ha6_1_iIgK3R-ubqS)** ([raw file](https://github.com/servo/servo/blob/2a2fba649d898b3377abe0412747ff7c791ae5a0/components/script/dom/bindings/weakref.rs#L33)):</sup>
Or the reflector? ;) Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8147)

**Comment by Ms2ger** [comment]
@bors-servo r+


---

Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8147)

**Comment by jdm** [comment]
@bors-servo: retry
* #8435

**Pull request merged**
