### PR TITLE
Update SpiderMonkey

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10756)

### CODE REVIEW

**Comment by nox** [comment]
android:
```
Unexpected dynamic symbols in binary: _ZNSt4priv11_GetFacetIdEPKSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE, _ZN12JSPrincipals4dumpEv, _ZN8JSTracer16asCallbackTracerEv, _ZNSt10_UnderflowIcSt11char_traitsIcEE7_M_doitEPSt13basic_filebufIcS1_E, _ZNSt13_Filebuf_base7_M_openEPKci, _ZNSt13_Filebuf_base8_M_closeEv, _ZNSt13_Filebuf_base8_M_unmapEPvl, _ZSt24__stl_throw_length_errorPKc, _ZNSt13_Filebuf_base8_M_writeEPci, _ZNSt13_Filebuf_base7_M_seekEli, _ZNSt13_Filebuf_base12_M_page_sizeE, _ZNKSt6locale12_M_get_facetERKNS_2idE, _ZNSt8ios_base16_M_throw_failureEv, _ZNKSt6locale12_M_use_facetERKNS_2idE, _ZNSt13_Filebuf_baseC1Ev, _ZNKSt5ctypeIcE8scan_notENSt10ctype_base4maskEPKcS4_, _ZN2JS12AutoGCRooter5traceEP8JSTracer, _ZNSt13_Filebuf_base12_M_file_sizeEv
```

linux-rel:
```
  ▶ Unexpected subtest result in /html/browsers/browsing-the-web/scroll-to-fragid/scroll-to-id-top.html:
  └ PASS [expected FAIL] Fragment Navigation: TOP is a valid element id, which overrides navigating to top of the document
```

mac-rel-wpt:
```
  ▶ FAIL [expected PASS] /_mozilla/mozilla/sslfail.html
  └   → /_mozilla/mozilla/sslfail.html 9d627658adfcf6a768983b0fbae728aa4edab3e0
/_mozilla/mozilla/sslfail-ref.html 0a7088f19a748be896762e4a5cbb67467342f6e8
Testing 9d627658adfcf6a768983b0fbae728aa4edab3e0 == 0a7088f19a748be896762e4a5cbb67467342f6e8
```

**Comment by Ms2ger** [comment]
Reviewed 17 of 24 files at r1, 1 of 1 files at r2, 3 of 3 files at r4, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[components/script/Cargo.toml, line 48 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFyhHnDTX1RKGqEs98I:-KFyhHnDTX1RKGqEs98J:2098156361) ([raw file](https://github.com/servo/servo/blob/70556b687612aa706ea7c5db307eac5dd5ece055/components/script/Cargo.toml#L48)):*
Revert

---

*[components/script/dom/imagedata.rs, line 42 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFyiF3o7m4eGLB0tmaC:-KFyiF3o7m4eGLB0tmaD:-963224432) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/imagedata.rs#L42)):*
For all those, can we assert that the new ourparam is false after the call?

---

*[components/script/dom/window.rs, line 1198 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFyiSiYc8pb4F5XB-CK:-KFyiSiYc8pb4F5XB-CL:781899508) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/window.rs#L1198)):*
`window`, not `inner`

---

*[components/script/dom/bindings/utils.rs, line 318 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFyjNF7T56UG488VYyY:-KFyjNF7T56UG488VYyZ:-1187731479) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/bindings/utils.rs#L318)):*
I think I'd rather turn those off.

---

*[components/script/dom/bindings/utils.rs, line 353 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFylnDgN1rg_ZCCK_2N:-KFylnDgN1rg_ZCCK_2O:-859419202) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/bindings/utils.rs#L353)):*
Note to self: learn more about barriers.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1502 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFylzhiGu_c-pUJXwST:-KFylzhiGu_c-pUJXwSU:879831972) ([raw file](https://github.com/servo/servo/blob/1eec5d9f7222dd3f7020b51e18ed6df3386b18f9/components/script/dom/bindings/codegen/CodegenRust.py#L1502)):*
Note to self: check this

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 3206 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFymP0HBaBeVM1QVFH8:-KFymP0HBaBeVM1QVFH9:1892679726) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/bindings/codegen/CodegenRust.py#L3206)):*
Followup?

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 4336 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFym_63IXR3erobCBAE:-KFym_63IXR3erobCBAF:1670981003) ([raw file](https://github.com/servo/servo/blob/1eec5d9f7222dd3f7020b51e18ed6df3386b18f9/components/script/dom/bindings/codegen/CodegenRust.py#L4336)):*
Check.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 4357 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFymaXefgT_L_AuzRsa:-KFymaXefgT_L_AuzRsb:1670981003) ([raw file](https://github.com/servo/servo/blob/1eec5d9f7222dd3f7020b51e18ed6df3386b18f9/components/script/dom/bindings/codegen/CodegenRust.py#L4357)):*
Check.

---

*[components/util/Cargo.toml, line 25 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFymi25t9ePv56_ooDM:-KFymi27JcWCEqdI7bD6:2098156361) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/util/Cargo.toml#L25)):*
Revert

---

*[ports/cef/Cargo.toml, line 74 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFymlkkibBayrg8Vp8r:-KFymlkllX-na1pkMUFc:2098156361) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/ports/cef/Cargo.toml#L74)):*
Revert

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10756)*

**Comment by Ms2ger** [comment]
Reviewed 10 of 10 files at r11.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/utils.rs, line 353 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFylnDgN1rg_ZCCK_2N:-KGCKWtubGbJlFhQ-pi-:-453713776) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/bindings/utils.rs#L353)):*
I learned about barriers, and this seems fine.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2397 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL0smnShFVZKQewQC:-KGCL0smnShFVZKQewQD:-1015058986) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2397)):*
Assert that the entry actually is null before this.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2440 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL4VhHIbPlTWlS3p_:-KGCL4VhHIbPlTWlS3pa:-1015058986) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2440)):*
Assert that the entry actually is null before this.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2480 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL5r1Ftdcz7xf7fLp:-KGCL5r1Ftdcz7xf7fLq:-243463217) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2480)):*
Assert that the entry actually is null before this.

Can we have a helper function to reduce the duplicated code? Or replace the array by a proper type that encapsulates the barriers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10756)*

**Comment by nox** [comment]
This failure is an intermittent (#10457).

---

Review status: 8 of 23 files reviewed at latest revision, 12 unresolved discussions.

---

*[components/script/dom/imagedata.rs, line 42 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFyiF3o7m4eGLB0tmaC:-KGHiYMewP9a0PXSQf0e:-499146009) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/imagedata.rs#L42)):*
Done.

---

*[components/script/dom/window.rs, line 1198 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFyiSiYc8pb4F5XB-CK:-KGHiwX69oNQ2yIaZpjv:-499146009) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/window.rs#L1198)):*
Done.

---

*[components/script/dom/bindings/utils.rs, line 318 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFyjNF7T56UG488VYyY:-KGHiy5e-G8m77j51UN3:-2064280810) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/bindings/utils.rs#L318)):*
We already expect `Atomics` in `_mozilla/mozilla/interfaces.html`, do you want me to disable that?

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1502 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFylzhiGu_c-pUJXwST:-KGHcceh2L-8vaMvKRFw:1697486558) ([raw file](https://github.com/servo/servo/blob/1eec5d9f7222dd3f7020b51e18ed6df3386b18f9/components/script/dom/bindings/codegen/CodegenRust.py#L1502)):*
Assertions start to fail if 

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 3206 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFymP0HBaBeVM1QVFH8:-KGHclc4PhK2Cj_hpnq1:1355695487) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/bindings/codegen/CodegenRust.py#L3206)):*
Yeah I plan to file one.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 4336 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFym_63IXR3erobCBAE:-KGHcpkCmvrIYVdEYhMS:-1748788785) ([raw file](https://github.com/servo/servo/blob/1eec5d9f7222dd3f7020b51e18ed6df3386b18f9/components/script/dom/bindings/codegen/CodegenRust.py#L4336)):*
JSPROP_READONLY cannot actually be used here, assertions start to fail specifically about this.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2397 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL0smnShFVZKQewQC:-KGHcGw_0Waj7bBPwmfs:-964945838) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2397)):*
It cannot not be null, otherwise this code wouldn't even be reached.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2440 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL4VhHIbPlTWlS3p_:-KGHjLddqtGdqphHCO4-:-499146009) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2440)):*
Done.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2480 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL5r1Ftdcz7xf7fLp:-KGHcTtG_7Oy-RDWWZq8:-1700756844) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2480)):*
It was already like this, do you mind if I just file a follow-up issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10756#-:-KGHjP26WdNOfLytcEH0:-811644700)*

**Comment by notriddle** [comment]
If it's ready to merge, could you please change the title of this PR?

**Comment by nox** [comment]
It isn't, Windows support is inexistent.

**Comment by Ms2ger** [comment]
Reviewed 5 of 9 files at r12, 10 of 10 files at r13.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/utils.rs, line 318 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFyjNF7T56UG488VYyY:-KGI30rNKc-LysoI4ZxN:607952491) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/bindings/utils.rs#L318)):*
Eh, I guess not in this pr, then.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2397 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL0smnShFVZKQewQC:-KGI3BpniMBC8uc-MO1m:-1938241109) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2397)):*
`debug_assert` if you think that's better; I'm somewhat paranoid when it comes to GC integration

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2480 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL5r1Ftdcz7xf7fLp:-KGI3ML1KrhYQSv4UhZx:-1649715922) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2480)):*
Fine by me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10756)*

**Comment by nox** [comment]
@vvuk Any idea where that could come from? http://build.servo.org/builders/windows/builds/298/steps/compile/logs/stdio

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r15, 1 of 1 files at r18, 4 of 10 files at r23, 6 of 6 files at r25.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 3206 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFymP0HBaBeVM1QVFH8:-KGq87iVdhSdJTKN-erb:896982072) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/bindings/codegen/CodegenRust.py#L3206)):*
Please do so now.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 4336 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFym_63IXR3erobCBAE:-KGq8teeKZtmkCbqjyoV:-807811112) ([raw file](https://github.com/servo/servo/blob/1eec5d9f7222dd3f7020b51e18ed6df3386b18f9/components/script/dom/bindings/codegen/CodegenRust.py#L4336)):*
Are you sure? I think this particular one is wrong; it certainly doesn't match Gecko.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2397 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL0smnShFVZKQewQC:-KGq7yh2PiWv6agkqLzp:1315683645) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2397)):*
Please do this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10756)*

**Comment by Ms2ger** [comment]
Reviewed 2 of 2 files at r26.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/workerglobalscope.rs, line 230 \[r26\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGqVxYaCkPd1aRgJPl6:-KGqVxYaCkPd1aRgJPl7:-1962584384) ([raw file](https://github.com/servo/servo/blob/a8da58810c5e993330a33a7e86f5b33be2bc9bdd/components/script/dom/workerglobalscope.rs#L230)):*
`as_str()`

---

*[components/script/dom/workerglobalscope.rs, line 323 \[r26\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGqVuNdcdYgE98V1i4_:-KGqVuNevJRxdpoe5nf4:-1962584384) ([raw file](https://github.com/servo/servo/blob/a8da58810c5e993330a33a7e86f5b33be2bc9bdd/components/script/dom/workerglobalscope.rs#L323)):*
`as_str()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10756)*

**Comment by Ms2ger** [comment]
Reviewed 1 of 1 files at r27.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 3206 \[r10\]](https://reviewable.io:443/reviews/servo/servo/10756#-KFymP0HBaBeVM1QVFH8:-KGr8XWtBnnrqiN3XiSg:1688243844) ([raw file](https://github.com/servo/servo/blob/f5233b18b79b88857f79939b8ce12fbe0b779b81/components/script/dom/bindings/codegen/CodegenRust.py#L3206)):*
Please mention the issue number here.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2397 \[r11\]](https://reviewable.io:443/reviews/servo/servo/10756#-KGCL0smnShFVZKQewQC:-KGr8ZtL95g1L2ZgKAwr:1236636853) ([raw file](https://github.com/servo/servo/blob/88a9daf2445baf0bb297c984a5f481a239fcb9a5/components/script/dom/bindings/codegen/CodegenRust.py#L2397)):*
Again, I want you to add this assertion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10756)*

**Comment by Ms2ger** [comment]
Three cheers for this guy!

@bors-servo r+

---

Reviewed 1 of 1 files at r28.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10756#-:-KGr9k6-oHQJS6wLVb7z:-1404041427)*

**Comment by nox** [comment]
Three cheers? Ok...

@bors-servo p=3

**Comment by nox** [comment]
@Ms2ger I found the issue, I had just forgot to add `JSPROP_RESOLVING` in `interface::define_on_global_object`.

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #10924

**Comment by jdm** [comment]
@bors-servo: retry
#10924

**Pull request merged**
