### PR TITLE
style: Properly track whether negative values of calc() are allowed

### PR DESCRIPTION
**Pull request by emilio**
r? @SimonSapin 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes OR

In order to clamp them at computed value time.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13121)

### CODE REVIEW

**Comment by SimonSapin** [comment]
https://drafts.csswg.org/css-values/#calc-range
> **the used value** resulting from an expression must be clamped to the range allowed in the target context.

(Emphasis added.) So `to_computed_value` is not the place to do the clamping.

I’d suggest adding a method on the computed-value-types that layout can call. And maybe make some fields private to force it to go through that method?

**Comment by emilio** [comment]
For the record, I opened a spec issue about this. https://github.com/w3c/csswg-drafts/issues/434

**Comment by SimonSapin** [comment]
Apparently this matches WebKit and Blink: https://github.com/w3c/csswg-drafts/issues/434#issuecomment-243935412

@bors-servo r+

**Comment by emilio** [comment]
This was still wrong, my fault.

**Pull request merged**
