### PR TITLE
Stylo uplifts Part 2

### PR DESCRIPTION
**Pull request by bholley**
A bunch of random things that we might as well merge into the tree.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9515)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ports/geckolib/glue.rs, line 105 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9515#-K9bu4XsLiwHggLSAeeG:-K9bu4XtkzxxUrtc9Mi7:-904745107) ([raw file](https://github.com/servo/servo/blob/581aa3e06e9481e357f46ac6a819f5392136671b/ports/geckolib/glue.rs#L105)):*
Maybe use a non -HTTP url like `about:none` to avoid making requests to example.org?

---

*[ports/geckolib/glue.rs, line 125 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9515#-K9bw3F1uOiHMmK-54uj:-K9bw3F1uOiHMmK-54uk:37379185) ([raw file](https://github.com/servo/servo/blob/33b0eb3c6dd9180d5e9d43a6830add352ca170f1/ports/geckolib/glue.rs#L125)):*
IIRC `Stylesheet` derives `PartialEq` for unit tests. This is not an identity check, it’s "deep" equality and is relatively expensive.

For an identity check, you’ll want something like:

```rust
fn same_arc<T>(a: &Arc<T>, b: &Arc<T>) -> bool {
    let raw_a: *const T = &**a;
    let raw_b: *const T = &**b;
    raw_a == raw_b
}
```

---

*[ports/geckolib/glue.rs, line 134 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9515#-K9bwwHtlf1AhVwjgB0f:-K9bwwHtlf1AhVwjgB0g:-1099397866) ([raw file](https://github.com/servo/servo/blob/33b0eb3c6dd9180d5e9d43a6830add352ca170f1/ports/geckolib/glue.rs#L134)):*
Nit: you could change `with_arc_stylesheet` to return the return value of the closure, to avoid the temporary variable.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9515)*

**Comment by jdm** [comment]
There's `arc_ptr_eq` in util: http://doc.servo.org/util/fn.arc_ptr_eq.html

**Comment by bholley** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ports/geckolib/glue.rs, line 105 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9515#-K9bu4XsLiwHggLSAeeG:-K9e8FYkWyfylVOViE_a:-499146009) ([raw file](https://github.com/servo/servo/blob/581aa3e06e9481e357f46ac6a819f5392136671b/ports/geckolib/glue.rs#L105)):*
Done.

---

*[ports/geckolib/glue.rs, line 125 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9515#-K9bw3F1uOiHMmK-54uj:-K9e8Lc4gr5TdF0WC2O2:-499146009) ([raw file](https://github.com/servo/servo/blob/33b0eb3c6dd9180d5e9d43a6830add352ca170f1/ports/geckolib/glue.rs#L125)):*
Done.

---

*[ports/geckolib/glue.rs, line 134 \[r6\]](https://reviewable.io:443/reviews/servo/servo/9515#-K9bwwHtlf1AhVwjgB0f:-K9e8H_BCgTjNbvETuhc:823050361) ([raw file](https://github.com/servo/servo/blob/33b0eb3c6dd9180d5e9d43a6830add352ca170f1/ports/geckolib/glue.rs#L134)):*
Nice idea.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9515)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9515#-:-K9fhNnMBioAuMbQpDM1:1236647940)*

**Comment by jdm** [comment]
@bors-servo: retry
* #9009

**Pull request merged**
