### PR TITLE
Invoke specialized callback behaviour for OnErrorEventHandler.

### PR DESCRIPTION
**Pull request by jdm**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8430)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed 7 of 8 files at r1.
Review status: 7 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/script/dom/eventtarget.rs, line 41 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8430#-K2hBq1J0bR7IuBoH_Yj)** ([raw file](https://github.com/servo/servo/blob/c18d9513f3a46f25939e74b618fd29d3e2b852e4/components/script/dom/eventtarget.rs#L41)):</sup>
Any reason to keep these typedefs?


---

<sup>**[components/script/dom/eventtarget.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8430#-K2hDWduZ2jZ6tTGEdDH)** ([raw file](https://github.com/servo/servo/blob/c18d9513f3a46f25939e74b618fd29d3e2b852e4/components/script/dom/eventtarget.rs#L124)):</sup>
Can you get me some spec links?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8430)

**Comment by jdm** [comment]
Your very simple requests caused me to add a couple extra assertions to the new test, and that ended up sending me down a rabbit hole of discovery about the various ways that the test was not testing what it thought it was, and additionally how the code for uncompiled event handlers was subtly incorrect in the forward-to-window case!

**Comment by Ms2ger** [comment]
You're welcome :)

**Comment by Ms2ger** [comment]
Se we're still eagerly compiling? File an issue on that.


---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[components/script/dom/eventtarget.rs, line 150 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8430#-K2vbrfPsj8eK3baKkce)** ([raw file](https://github.com/servo/servo/blob/0db6a9dab03d733bad3c666299200f5b930f214c/components/script/dom/eventtarget.rs#L150)):</sup>
File an issue for this too.


---

<sup>**[components/script/dom/eventtarget.rs, line 266 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8430#-K2vaWK64b--StPwKlgb)** ([raw file](https://github.com/servo/servo/blob/0db6a9dab03d733bad3c666299200f5b930f214c/components/script/dom/eventtarget.rs#L266)):</sup>
How about just putting the `&'static [*const c_char]` in the local bindings, and calling `as_ptr()`/`len()` below?


---

<sup>**[components/script/dom/htmlbodyelement.rs, line 156 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8430#-K2w1V0zHGWoXOlo33wO)** ([raw file](https://github.com/servo/servo/blob/0db6a9dab03d733bad3c666299200f5b930f214c/components/script/dom/htmlbodyelement.rs#L156)):</sup>
This seems fishy. Do we really not have a better way to solve this?


---

<sup>**[tests/wpt/web-platform-tests/html/webappapis/scripting/events/onerroreventhandler-frame.html, line 25 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8430#-K2vyLO_bz9IUrni6iCT)** ([raw file](https://github.com/servo/servo/blob/0db6a9dab03d733bad3c666299200f5b930f214c/tests/wpt/web-platform-tests/html/webappapis/scripting/events/onerroreventhandler-frame.html#L25)):</sup>
Put this all in `parent.t1.step(function() { ... })`; ditto below.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8430)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8430)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-squash 


---

Reviewed 1 of 1 files at r3.
Review status: 12 of 13 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8430)

**Comment by eefriedman** [comment]
```
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/eventtarget.rs:14:5: 14:55 error: unresolved import `dom::bindings::global::global_object_for_reflector`. There is no `global_object_for_reflector` in `dom::bindings::global` [E0432]
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/eventtarget.rs:14 use dom::bindings::global::global_object_for_reflector;
                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-dev/build/components/script/dom/eventtarget.rs:14:5: 14:55 help: run `rustc --explain E0432` to see a detailed explanation
```

**Pull request merged**
