### PR TITLE
Warning patrol

### PR DESCRIPTION
**Pull request by jdm**
This greens up every build except the android one.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17872)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo r-

I'd like @mbrubeck or someone else familiar to the CEF architecture to review the 2nd commit.

**Comment by jdm** [comment]
@KiChjang Why? It's an unused variable since 9591d1eda55a01e45db38af5ffc36ac696445e49.

**Comment by KiChjang** [comment]
@jdm Thanks for linking that up! However, there may be other intended usages of `rendering_thread` that I am not aware of, and I'm being conservative when removing code that may be used.

**Comment by emilio** [comment]
That code is used nowhere. There's no point of keeping it in tree. If someone ever wants to add an option for that back it's pretty easy to do so.

r=me, we can remove the extra struct field in `cef_options_t` as a followup.

@bors-servo r+

**Comment by emilio** [comment]
Err, `cef_settings_t`.

**Comment by emilio** [comment]
If you're interested, the option was used introduced in https://github.com/servo/servo/pull/4193

**Comment by emilio** [comment]
Seems like it _could_ be used to set the `layout.threads` pref. However, that option was introduced in the time when rust had green threads, so using `128` by default would be insane.

Anyway, I'm fine with removing dead code. If someone ever tries to maintain the CEF port again and needs it it's super-easy to add back.

**Pull request merged**
