### PR TITLE
Implement Range.getClientRects and Range.getBoudingClientRect (Work in progress)

### LINKED ISSUE #8982: [devtools.html] Range.getBoundingClientRect support
In meta-issue #8973 to get devtools.html loading, we noticed `getBoundingClientRect` is not supported yet.

CodeMirror (which we use as an editor throughout various parts of our tools) relies on this for various metrics and expects it to be available.

### PR DESCRIPTION
**Pull request by jaysonsantos**
Hi guys, I did this pull request so you can check if I am heading on the right track.
This should fix #8982 when done.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10828)

### CODE REVIEW

**Comment by Manishearth** [comment]
r? @KiChjang 

might not get time for this till next week

**Comment by frewsxcv** [comment]
*[components/script/dom/range.rs, line 910 \[r13\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGXqO6eDUu7_LrG5zXM:-KGXqO6eDUu7_LrG5zXN:-1152740480) ([raw file](https://github.com/servo/servo/blob/22601fb9f6401345ec118e06aa014cc00f17f250/components/script/dom/range.rs#L910)):*
personally, I'd do:

```
let node = match node {
    Some(node) => node,
    None => return;
};

...
```

So it's not one giant indented block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10828)*

**Comment by KiChjang** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r8, 1 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[components/script/dom/range.rs, line 30 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGYuqeTkTI3C4NAC5fQ:-KGYuqeUrDNPYdJERKP8:807088125) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L30)):*
nit: Remove the braces.

---

*[components/script/dom/range.rs, line 909 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGZ-lPt03HmScxfnddm:-KGZ-lPuLfailHwX6auD:-987920349) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L909)):*
Is the third `&Range` argument necessary? You can simply use `self`.

---

*[components/script/dom/range.rs, line 920 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGYx_m7CMXm2BCC-mKL:-KGYx_m8PGGA-7imWfSy:976382644) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L920)):*
This is very imperative-styled, we should instead make a new method in `DOMRectList` that returns its underlying `Vec<JS<DOMRect>>` and use an iterator over this vec instead.

---

*[components/script/dom/range.rs, line 929 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGZ-y3QMJxCa-4SXy17:-KGZ-y3RNfGWl9HzVzFG:942220172) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L929)):*
Are these 3 lines necessary?

---

*[components/script/dom/range.rs, line 978 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGYys2-4FJPh94VJey9:-KGYys2-4FJPh94VJeyA:1547891652) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L978)):*
Step annotations here would be nice.

---

*[components/script/dom/range.rs, line 979 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGYz-JtcYbgIrCwsJ1D:-KGYz-JtcYbgIrCwsJ1E:648623425) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L979)):*
> Otherwise, return a static DOMRect object describing the smallest rectangle that includes the first rectangle in list and all of the remaining rectangles of which the height or width is not zero.

This does not look like it is following the spec.

---

*[tests/wpt/web-platform-tests/dom/ranges/Range-getBoundingClientRect.html, line 17 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGYyNfr-ZlB8FRcGRUc:-KGYyNfr-ZlB8FRcGRUd:411444988) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/tests/wpt/web-platform-tests/dom/ranges/Range-getBoundingClientRect.html#L17)):*
Are these random values or magic values?

---

*[tests/wpt/web-platform-tests/dom/ranges/Range-getClientRects.html, line 20 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGYyTCE1gC18sJwIT79:-KGYyTCE1gC18sJwIT7A:-916406261) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/tests/wpt/web-platform-tests/dom/ranges/Range-getClientRects.html#L20)):*
Same here, random or magic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10828)*

**Comment by jaysonsantos** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[components/script/dom/range.rs, line 909 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGZ-lPt03HmScxfnddm:-KGfVHVd-3Cw6FJrZKj-:481174427) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L909)):*
It will say that I need to move self to be able to access it.

---

*[components/script/dom/range.rs, line 929 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGZ-y3QMJxCa-4SXy17:-KGfVo8-iq9lCT6v-TM9:-1813050946) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L929)):*
The same, the compiler will say that I need to `move` to use it here. 

---

*[components/script/dom/range.rs, line 979 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGYz-JtcYbgIrCwsJ1D:-KGfVxjFNg1NOtRlJ2Rf:-1217766985) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L979)):*
No, this is the latest point that I will look into

---

*[tests/wpt/web-platform-tests/dom/ranges/Range-getBoundingClientRect.html, line 17 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGYyNfr-ZlB8FRcGRUc:-KGfW_mvSM2oBSLlEnLe:741568195) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/tests/wpt/web-platform-tests/dom/ranges/Range-getBoundingClientRect.html#L17)):*
I looked on the return values of chrome. Do you have any suggestions to make it?

---

*[tests/wpt/web-platform-tests/dom/ranges/Range-getClientRects.html, line 20 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGYyTCE1gC18sJwIT79:-KGfWfDCvFj4coZMXa31:1135289273) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/tests/wpt/web-platform-tests/dom/ranges/Range-getClientRects.html#L20)):*
The same as the other

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10828)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[components/script/dom/range.rs, line 909 \[r14\]](https://reviewable.io:443/reviews/servo/servo/10828#-KGZ-lPt03HmScxfnddm:-KGk8A7vg_TlXcavVdXY:1170228199) ([raw file](https://github.com/servo/servo/blob/5581d76f34a0fb24606a970bf35a533de4532dca/components/script/dom/range.rs#L909)):*
Then i don't see the reason why this is an inner function. You can move this outside and take a `&self` parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10828)*

**Comment by jdm** [comment]
Looks like that rebase didn't work quite right...

**Comment by KiChjang** [comment]
@jaysonsantos Is this still being worked on?

**Comment by jaysonsantos** [comment]
Hey @KiChjang sorry for the late response. I wasn't able to understand the architecture of servo and the specs and I didn't have time these days. I think it is better to let someone that already know it and I will get an easier issue later.

**Comment by KiChjang** [comment]
Okay, no problem!

**Pull request closed without merging**
