### PR TITLE
Write reflow results, even with no root node.

### LINKED ISSUE #8240: Layout queries do silly things when the document element is removed
```html
<!DOCTYPE html>
<div>...</div>
<script>
console.log(document.body.firstChild.offsetWidth);
document.documentElement.remove();
var el = document.createElement("div");
console.log(el.offsetWidth);
</script>
```
yields (784, 784); dropping the `remove()` call yields (784, 0).

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #8240 

Test in w3c/csswg-test#928.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8256)

### CODE REVIEW

**Comment by frewsxcv** [comment]
This fails tidy

```
./components/layout/layout_task.rs:1157: Line is longer than 120 characters
```

**Comment by notriddle** [comment]
Fixed the tidy errors.

**Comment by notriddle** [comment]
What do I have to do to get w3c/csswg-test#928 reviewed? I'm tired of rebasing.

**Comment by eefriedman** [comment]
@bors-servo r+

I was going to wait for the test to be reviewed, but since it's taking forever, I'll just r+ this now.

Not sure our handling of empty documents is precisely correct in terms of rendering (do we have to do something here to clear the display list?), but we don't need to solve that here.

**Comment by jdm** [comment]
@bors-servo: retry
* #8416

**Pull request merged**
