### PR TITLE
Minor cleanup of flow::Flow children iterators.

### PR DESCRIPTION
**Pull request by frewsxcv**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10187)

### CODE REVIEW

**Comment by frewsxcv** [comment]
I did notice [this comment](https://github.com/frewsxcv/servo/blob/c5b75a94feec3af541141c64d9a3cfd141713e45/components/layout/flow.rs#L67-L68). Should I be concerned?

**Comment by pcwalton** [comment]
r- on the first commit. These methods must not be virtual as they're called all over the place.

**Comment by KiChjang** [comment]
I think the renaming from `imm_child_iter()` to `children_iter()` and `child_iter()` to `children_iter_mut()` makes sense though.

**Comment by nox** [comment]
I concur.

**Comment by frewsxcv** [comment]
I agree, though a bit busy right now to take care of it. Someone want to create an E-Easy Issue for the renaming?

**Comment by KiChjang** [comment]
Filed #10286.

**Pull request closed without merging**
