### PR TITLE
implement missing steps from "prepare a script" algorithm

### LINKED ISSUE #4089: Missing steps from the "prepare a script" algorithm
Some parts of the [prepare a script](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element:prepare-a-script) algorithm from the HTML specification are not yet implemented.  See the "TODO" items in [`HTMLScriptElementHelpers::prepare`](https://github.com/servo/servo/blob/51aa2fde10daa8c98f5407e35b8abf01bd364788/components/script/dom/htmlscriptelement.rs#L113-L208).

* [ ]  Step 10. If the element is flagged as "parser-inserted", but the element's node document is not the Document of the parser that created the element, then abort these steps.
* [ ] Step 11. If scripting is disabled for the script element, then the user agent must abort these steps at this point. The script is not executed.
* [x] Step 12. If the script element has an `event` attribute and a `for` attribute, then run these substeps... (#4176).
* [ ] Step 13. If the script element has a `charset` attribute, then let the script block's character encoding for this script element be the result of getting an encoding from the value of the `charset` attribute.
* [ ] Step 14 and 15. Add support for the `defer` and `async` attributes. (For now, we fetch all scripts synchronously and execute them immediately.)  See also #4088.

### PR DESCRIPTION
**Pull request by psdh**
Fixes #4089

### CODE REVIEW

**Comment by jdm** [comment]
Commented on Critic!

**Comment by psdh** [comment]
Code changed :)

**Comment by jdm** [comment]
Nearly there!

**Comment by jdm** [comment]
Squash!

**Pull request merged**
