### PR TITLE
Fail on unrecognized debug option

### PR DESCRIPTION
**Pull request by g-k**
Refs: https://github.com/servo/servo/issues/7142

Ran some basic functional tests:

```
 $ ./mach run -d -Z bubble-widths,disable-canvas-aa,trace-layout tests/ref/blur_ref.html
 $ ./mach run -d -Z help
Usage: /Users/greg/servo/target/debug/servo debug option,[options,...]
    where options include

Options:
    bubble-widths                       Bubble intrinsic widths separately like other engines.
    disable-text-aa                     Disable antialiasing of rendered text.
    disable-canvas-aa                   Disable antialiasing on the HTML canvas element.
    dump-flow-tree                      Print the flow tree after each layout.
    dump-display-list                   Print the display list after each layout.
    dump-display-list-json              Print the display list in JSON form.
    dump-display-list-optimized         Print optimized display list (at paint time).
    relayout-event                      Print notifications when there is a relayout.
    profile-tasks                       Instrument each task, writing the output to a file.
    show-compositor-borders             Paint borders along layer and tile boundaries.
    show-fragment-borders               Paint borders along fragment boundaries.
    show-parallel-paint                 Overlay tiles with colors showing which thread painted them.
    show-parallel-layout                Mark which thread laid each flow out with colors.
    paint-flashing                      Overlay repainted areas with a random color.
    trace-layout                        Write layout trace to an external file for debugging.
    validate-display-list-geometry      Display an error when display list geometry escapes overflow region.
    disable-share-style-cache           Disable the style sharing cache.
    parallel-display-list-building      Build display lists in parallel.
    replace-surrogates                  Replace unpaires surrogates in DOM strings with U+FFFD. See https://github.com/servo/servo/issues/6564
    gc-profile                          Log GC passes and their durations.

$ ./mach run -d -Z blah
error: unrecognized debug option: blah
Servo exited with return value 1
```

Didn't check that setting debug flags actually did anything.
Haven't written much Rust so this feels more verbose than necessary.
Added `disable-canvas-aa` to debug options help.

Should DebugOptions struct derive Clone like Opts does?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7165)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

Thank you for your PR. It looks good, but I have some style nits.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/util/opts.rs, line 249 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7165#-JwVyo46A4I1cK2H7cVJ)** ([raw file](https://github.com/servo/servo/blob/1daa9ae58823edc7610a10fa999a035466f06d6e/components/util/opts.rs#L249)):</sup>
This would perhaps make more sense as an implementation of the `std::default::Default` trait.

---

<sup>**[components/util/opts.rs, line 388 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7165#-JwVz4Y_zgI1Zc7bcgzw)** ([raw file](https://github.com/servo/servo/blob/1daa9ae58823edc7610a10fa999a035466f06d6e/components/util/opts.rs#L388)):</sup>
I'd make this an associated function `DebugOptions::new`. 

---

<sup>**[components/util/opts.rs, line 414 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7165#-JwVzL75I-wv5KOY6at7)** ([raw file](https://github.com/servo/servo/blob/1daa9ae58823edc7610a10fa999a035466f06d6e/components/util/opts.rs#L414)):</sup>
The nice thing about Rust is that you don't actually need to allocate the new `String` here. You can probably just write `&str` in the return type; if not, it'll be something like `fn new<'a>(debug_string: &'a str) -> Result<DebugOptions, &'a str> {}`.

---

<sup>**[components/util/opts.rs, line 418 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7165#-JwVzGrgB07qymrYKfS3)** ([raw file](https://github.com/servo/servo/blob/1daa9ae58823edc7610a10fa999a035466f06d6e/components/util/opts.rs#L418)):</sup>
Shouldn't need a `return` here.

---

<sup>**[components/util/opts.rs, line 584 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7165#-JwVzneihImV_L9jq4Gc)** ([raw file](https://github.com/servo/servo/blob/1daa9ae58823edc7610a10fa999a035466f06d6e/components/util/opts.rs#L584)):</sup>
This makes me wonder whether we should just store the `DebugOptions` struct in here, rather than copying all the members. Don't do that in this PR, though.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7165)

**Comment by g-k** [comment]
Addressed most of the nits, but removing the `return` throws:

```
/Users/greg/servo/components/util/opts.rs:283:9: 283:11 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
/Users/greg/servo/components/util/opts.rs:283         Ok(debug_options);
                                                      ^~
/Users/greg/servo/components/util/opts.rs:283:9: 283:11 help: run `rustc --explain E0282` to see a detailed explanation
error: aborting due to previous error
```

Should I download a newer nightly of rust?

**Comment by jdm** [comment]
That's because the `;` hides the return value, so it should be removed too.

**Comment by g-k** [comment]
Aha, I wonder if anyone else makes that mistake and it'd be worth adding to `rustc --explain E0282`.

**Comment by g-k** [comment]
Forgot to functional test running without debug options with `./mach run` and `./mach run https://github.com/servo/servo` earlier.

**Comment by Ms2ger** [comment]
Thank you! Please squash the commits and ping me so I can merge.

-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7165)

**Pull request merged**
