### PR TITLE
Geckolib: Implement list-style-type

### PR DESCRIPTION
**Pull request by bholley**
Corresponding Gecko patch: https://bugzilla.mozilla.org/show_bug.cgi?id=1269933

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11018)

### CODE REVIEW

**Comment by bholley** [comment]
CC @heycam 

Note that bullets don't seem to render for me yet, but I think that's probably related to anon boxes / PEs. As far as I can tell this makes us cascade the property correctly.

**Comment by mbrubeck** [comment]
@bors-servo r+

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11018#-:-KGxgXTNxnokwwD_NGKh:1236647940)*

**Comment by jdm** [comment]
@bors-servo: retry
* git

**Comment by jdm** [comment]
@bors-servo: retry
* git

**Pull request merged**
