### PR TITLE
Pin clippy to a working revision.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9183)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+

We usually handle this by pushing to the servo branch on clippy.

Note that that branch has some of the lint defaults tweaked to get better results on servo, this commit doesn't have those. But it's not too important.

**Comment by jdm** [comment]
@bors-servo: retry
* #9163

**Pull request merged**
