### PR TITLE
Give up on hoisting ElementData into the frame and eliminate the concept of consuming styles

### PR DESCRIPTION
**Pull request by bholley**
Servo PR for the work in https://bugzilla.mozilla.org/show_bug.cgi?id=1325734

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14907)

### CODE REVIEW

**Comment by bholley** [comment]
> LLVM ERROR: IO failure on output stream

@jdm Is this #14723? If so, what should I do about it?

**Comment by bholley** [comment]
Let's see if that weird LLVM error is gone before putting this in the queue.

@bors-servo try

**Comment by emilio** [comment]
The LLVM error has been seen in other PRs and went away retrying.

@bors-servo r+

**Comment by bholley** [comment]
Awesome, thanks Emilio!

**Comment by bholley** [comment]
@bors-servo p=1

We'll want this in the next incubator merge.

**Pull request merged**
