### PR TITLE
Handle apostrophes for whatwg URL tidy check

### LINKED ISSUE #27366: test-tidy cuts off whatwg URLs that include apostrophes
https://html.spec.whatwg.org/multipage/semantics.html#get-an-element's-target
https://html.spec.whatwg.org/multipage/links.html#get-an-element's-noopener

### PR DESCRIPTION
**Pull request by CYBAI**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #27366 
- [x] These changes do not require tests because it will improve the tidy check for WHATWG URL

### CODE REVIEW

**Comment by CYBAI** [comment]
hmm, I will see a flake8 error locally. Let me see if it will throw the error in TC :/

```
Checking files for tidiness...
  Progress: 100% (1/1)Traceback (most recent call last):
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/lib/python2.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/lib/python2.7/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/lib/python2.7/site-packages/flake8/main/application.py", line 347, in _run
    self.initialize(argv)
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/lib/python2.7/site-packages/flake8/main/application.py", line 328, in initialize
    self.find_plugins(config_finder)
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/lib/python2.7/site-packages/flake8/main/application.py", line 159, in find_plugins
    self.check_plugins.load_plugins()
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/lib/python2.7/site-packages/flake8/plugins/manager.py", line 415, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/lib/python2.7/site-packages/flake8/plugins/manager.py", line 302, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/lib/python2.7/site-packages/flake8/plugins/manager.py", line 413, in load_plugin
    return plugin.load_plugin()
  File "/Volumes/Transcend/codespace/mozilla/servo/python/_virtualenv2.7/lib/python2.7/site-packages/flake8/plugins/manager.py", line 164, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to 'module' object has no attribute 'break_around_binary_operator'.

tidy reported no errors.
```

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by CYBAI** [comment]
There's no such error like https://github.com/servo/servo/pull/27377#issuecomment-662809699 in TC; I might need to see how to fix it for my local environment.

```
+ ./mach test-tidy --no-progress --all
 0:06.99(B INFO(B Diffing old and new manifests /repo/tests/wpt/mozilla/meta/MANIFEST.json
 0:07.55(B INFO(B Diffing old and new manifests /repo/tests/wpt/webgl/meta/MANIFEST.json
 0:08.26(B INFO(B Diffing old and new manifests /repo/tests/wpt/metadata/MANIFEST.json
Checking the config file...
Checking the wpt manifest file...
Checking directories for correct file extensions...
Running the WPT lint on ./tests/wpt/web-platform-tests/...
Running the WPT lint on ./tests/wpt/mozilla/tests/...
Checking files for tidiness...
Running the dependency licensing lint...
```

**Comment by jdm** [comment]
@bors-servo retry
* #25513 #26895

**Pull request merged**
