### PR TITLE
style: Add a "start_end()" method to LogicalMargin

### PR DESCRIPTION
**Pull request by stshine**
Add a `LogicalMargin::start_end()` method that receives a `Direction' parameter. This is useful for some layout that is symmetric in inline and block directions, like flexbox.

Part of #14123.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because refactoring

r? @SimonSapin

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14136)

### CODE REVIEW

**Comment by stshine** [comment]
Sadly that I failed to find a better name after months :)

**Comment by SimonSapin** [comment]
I’m ok with adding a new method that takes a direction parameter, for future code where this direction will be a variable. I think `start_end` is a better name for this method. (This name by itself is ambiguous, but taking a `direction` argument clarifies it IMO.)

But I think this method should not replace the existing `inline_start_end` and `block_start_end` methods. When the direction is fixed for a particular call, this new method is more verbose and requires a extra `use` import that was not necessary before. In other words… please revert most of this PR. Sorry to say this after you’ve done all this work.

**Comment by stshine** [comment]
I have no problem on the rework, while my main concern is the accidental complexity we may add. A new comer may be confused by the three methods with nearly identical behavior, and IMHO we should try to maintain a minimal interface, and the extra `use` is not a big issue compare to this.

Looking forward to your thoughts on this.

**Comment by SimonSapin** [comment]
It’s true that I haven’t been a newcomer to Servo for some time, but I don’t see how "`.block_start_end()` short for `.start_end(Direction::Block)`" (and similarly for inline) is confusing.

> we should try to maintain a minimal interface, and the extra `use` is not a big issue compare to this.

I have the exact opposite opinion. These methods are used many times, so making usage more convenient is worth maintaining a couple of one-liner convenience methods.

**Comment by stshine** [comment]
Alright, I agree your perspective has its rationality. I will rebase and follow your comments later.

**Comment by stshine** [comment]
Comments addressed. @SimonSapin Thanks for review!

**Comment by SimonSapin** [comment]
@bors-servo r+

Thanks!

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/14136#-:-KWDSV0R29ozE2AqtTxi:b-pjnt64)*

**Comment by emilio** [comment]
@bors-servo retry

 * https://github.com/servo/servo/issues/12797

**Pull request merged**
