### PR TITLE
Update rust-layers to get 2d transform + clipping support.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7141)

### CODE REVIEW

**Comment by glennw** [comment]
Needed for #6643.

r? @metajack

**Comment by jdm** [comment]
```
   Compiling embedding v0.0.1 (file:///home/servo/buildbot/slave/linux2/build/ports/cef)
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:363
stack backtrace:
Could not compile `embedding`.
```
I don't understand that error. I also have never seen the timeout in the CSS tests before. Can you reproduce it locally on linux?

**Comment by glennw** [comment]
I'm unable to reproduce the CEF failure locally (./mach build-cef --release works fine for me). I am running the css tests locally now to see if I can reproduce the timeouts.

**Comment by glennw** [comment]
@jdm Both the CEF build and the CSS tests pass locally on my machine with this branch.

**Comment by glennw** [comment]
@bors-servo retry

(possibly a build machine hiccup as I can't reproduce either of these locally)

**Pull request merged**
