### PR TITLE
Update string_cache to 0.2.26

### PR DESCRIPTION
**Pull request by KiChjang**
---

- [ ] `./mach build -d` does not report any hahahas
- [ ] `./mach test-tidy` does not report any hahahas
- [ ] These changes fix #hahaha (github issue number if applicable).

- [ ] There are tests for these changes OR hahaha
- [ ] These changes do not require tests because hahahaha

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13090)

### CODE REVIEW

**Comment by KiChjang** [comment]
```
failures:

---- size_of::size_div stdout ----
	thread 'size_of::size_div' panicked at 'Your changes have increased the stack size of commonly used DOM struct HTMLDivElement from 352 to 384. These structs are present in large quantities in the DOM, and increasing the size may dramatically affect our memory footprint. Please consider choosing a design which avoids this increase. If you feel that the increase is necessary, update to the new size in tests/unit/script/size_of.rs.', /home/servo/buildbot/slave/linux-dev/build/tests/unit/script/size_of.rs:45
stack backtrace:
   1:     0x7fdbab68e853 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7fdbab69294c - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7fdbab691967 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7fdbab692178 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7fdbab692012 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7fdbab691f40 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7fdbaade1086 - script_tests::size_of::size_div::h2239ef3589344ff8
                        at /home/servo/buildbot/slave/linux-dev/build/tests/unit/script/size_of.rs:8
   8:     0x7fdbab61af2b - _<F as alloc..boxed..FnBox<A>>::call_box::h6d40ac6ff8180289
   9:     0x7fdbab6140bf - std::panicking::try::do_call::hf4aa30d569353639
  10:     0x7fdbab69a436 - __rust_maybe_catch_panic
  11:     0x7fdbab61a8ea - _<F as alloc..boxed..FnBox<A>>::call_box::h116d9064e2ce57af
  12:     0x7fdbab6906e2 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  13:     0x7fdba90e6183 - start_thread
  14:     0x7fdba8bfd37c - clone
  15:                0x0 - <unknown>

---- size_of::size_htmlelement stdout ----
	thread 'size_of::size_htmlelement' panicked at 'Your changes have increased the stack size of commonly used DOM struct HTMLElement from 352 to 384. These structs are present in large quantities in the DOM, and increasing the size may dramatically affect our memory footprint. Please consider choosing a design which avoids this increase. If you feel that the increase is necessary, update to the new size in tests/unit/script/size_of.rs.', /home/servo/buildbot/slave/linux-dev/build/tests/unit/script/size_of.rs:44
stack backtrace:
   1:     0x7fdbab68e853 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7fdbab69294c - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7fdbab691967 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7fdbab692178 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7fdbab692012 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7fdbab691f40 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7fdbaade0d26 - script_tests::size_of::size_htmlelement::h24af54779ba939c5
                        at /home/servo/buildbot/slave/linux-dev/build/tests/unit/script/size_of.rs:8
   8:     0x7fdbab61af2b - _<F as alloc..boxed..FnBox<A>>::call_box::h6d40ac6ff8180289
   9:     0x7fdbab6140bf - std::panicking::try::do_call::hf4aa30d569353639
  10:     0x7fdbab69a436 - __rust_maybe_catch_panic
  11:     0x7fdbab61a8ea - _<F as alloc..boxed..FnBox<A>>::call_box::h116d9064e2ce57af
  12:     0x7fdbab6906e2 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  13:     0x7fdba90e6183 - start_thread
  14:     0x7fdba8bfd37c - clone
  15:                0x0 - <unknown>

---- size_of::size_element stdout ----
	thread 'size_of::size_element' panicked at 'Your changes have increased the stack size of commonly used DOM struct Element from 336 to 368. These structs are present in large quantities in the DOM, and increasing the size may dramatically affect our memory footprint. Please consider choosing a design which avoids this increase. If you feel that the increase is necessary, update to the new size in tests/unit/script/size_of.rs.', /home/servo/buildbot/slave/linux-dev/build/tests/unit/script/size_of.rs:43
stack backtrace:
   1:     0x7fdbab68e853 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7fdbab69294c - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7fdbab691967 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7fdbab692178 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7fdbab692012 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7fdbab691f40 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7fdbaade09c6 - script_tests::size_of::size_element::h30780666dc953a0b
                        at /home/servo/buildbot/slave/linux-dev/build/tests/unit/script/size_of.rs:8
   8:     0x7fdbab61af2b - _<F as alloc..boxed..FnBox<A>>::call_box::h6d40ac6ff8180289
   9:     0x7fdbab6140bf - std::panicking::try::do_call::hf4aa30d569353639
  10:     0x7fdbab69a436 - __rust_maybe_catch_panic
  11:     0x7fdbab61a8ea - _<F as alloc..boxed..FnBox<A>>::call_box::h116d9064e2ce57af
  12:     0x7fdbab6906e2 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  13:     0x7fdba90e6183 - start_thread
  14:     0x7fdba8bfd37c - clone
  15:                0x0 - <unknown>

---- size_of::size_span stdout ----
	thread 'size_of::size_span' panicked at 'Your changes have increased the stack size of commonly used DOM struct HTMLSpanElement from 352 to 384. These structs are present in large quantities in the DOM, and increasing the size may dramatically affect our memory footprint. Please consider choosing a design which avoids this increase. If you feel that the increase is necessary, update to the new size in tests/unit/script/size_of.rs.', /home/servo/buildbot/slave/linux-dev/build/tests/unit/script/size_of.rs:46
stack backtrace:
   1:     0x7fdbab68e853 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7fdbab69294c - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7fdbab691967 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7fdbab692178 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7fdbab692012 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7fdbab691f40 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7fdbaade13e6 - script_tests::size_of::size_span::h5d099da60fec3cdf
                        at /home/servo/buildbot/slave/linux-dev/build/tests/unit/script/size_of.rs:8
   8:     0x7fdbab61af2b - _<F as alloc..boxed..FnBox<A>>::call_box::h6d40ac6ff8180289
   9:     0x7fdbab6140bf - std::panicking::try::do_call::hf4aa30d569353639
  10:     0x7fdbab69a436 - __rust_maybe_catch_panic
  11:     0x7fdbab61a8ea - _<F as alloc..boxed..FnBox<A>>::call_box::h116d9064e2ce57af
  12:     0x7fdbab6906e2 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  13:     0x7fdba90e6183 - start_thread
  14:     0x7fdba8bfd37c - clone
  15:                0x0 - <unknown>
```
wat

**Comment by emilio** [comment]
@KiChjang: We removed the `[unsafe_no_drop_flag]` annotations here, maybe the drop flags are still added or we're not using a new enough version of rust?

**Comment by Manishearth** [comment]
That sounds like it's the case. We should rustup first

**Comment by nox** [comment]
I'm doing a rustup already, see #13055.

**Pull request merged**
