### PR TITLE
HoloLens app - winrt/immersive rewrite

### PR DESCRIPTION
**Pull request by paulrouget**
This is a complete rewrite of the app in C++ winrt. It includes a immersive view (use D3D and doesn't render any servo content yet).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23790)

### CODE REVIEW

**Comment by jdm** [comment]
@AngelOrtiz1007 Could you take a look at this new WinRT rewrite and provide feedback on:
* does it match your understanding of the requirements of the C++/CX->WinRT conversion?
* do you find the new code readable?
* are there any parts of the new app that could be rewritten for better clarity of purpose?

**Comment by angelortiz1007** [comment]
Will review.

**Comment by paulrouget** [comment]
> Will review.

You'll find that it's very much in "draft" mode. In your review can you differentiate what is just plain wrong, and what is "kinda wrong but it will work" (things that can be addressed later)?

Thanks :)

> jdm: does it match your understanding of the requirements of the C++/CX->WinRT conversion?

I disabled the CX extension. So this is full winrt.

**Comment by angelortiz1007** [comment]
Paul, I agree with your approach.  I will triage what I find.  Goal will be (summary):

 

1.	Compare the old version with the new version and look for C++/Cxx extensions and see if they’ve been converted correctly to WinRT.


2.	Review for what could be wrong, but OK for now.

 

Overall goal is to make certain entire ported code is WinRT complaint.

**Comment by angelortiz1007** [comment]
Paul,

 

Few questions…

1.	Did you modify the existing VS2017 solution or create a blank winrt project and then port the files over?
2.	When you say you “disabled CX extensions…” in the files by replacing ^ with const or other VS2017 solution settings (what solution setting?)

 

Thanks,

Angel

**Comment by angelortiz1007** [comment]
Paul,
The C++/CXX to  Winrt conversion/port looks good.  I went line by line looking for "^" and making sure const & was used appropriately.  

Below is a summary of what I reviewed with some minor comments.  There is one where objects are being passed by reference in what appears to be an asynch operation. If the object is being initialized by the asynch operation it should be fine.  If the object was previously initialized and could potentially be modified underneath another operation that is using it, there could be an issue.  You'll know better than I.

App.xaml in hololens appears to be WinRT compliant.  This file is created by default when you create a new winrt project.

app.h - looks good.  In the new implementation, it seems like the following was removed in the .h file and used/initialized in the .cpp which I don't see as a problem.
private:
    OpenGLESPage ^ mPage;
    OpenGLES mOpenGLES;

----
pch.h - File appears to have the correct/minimal winrt header files which are listed below.  The additional headers which are application speific where not verified:
#include <windows.h>
#include <unknwn.h>
#include <restrictederrorinfo.h>
#include <hstring.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.Activation.h>
#include <winrt/Windows.UI.Xaml.h>
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Data.h>
#include <winrt/Windows.UI.Xaml.Interop.h>
#include <winrt/Windows.UI.Xaml.Markup.h>
#include <winrt/Windows.UI.Xaml.Navigation.h>
---
OpenGLES.h - looks good.
WinRT related.  Suggest change to be:
private:
  EGLDisplay mEglDisplay = nullptr;
  EGLContext mEglContext = nullptr;
  EGLConfig  mEglConfig = nullptr;
  
  
OPenGLES.cpp - (OpenGLES()) Original version contained log("OpenGLES::OpenGLES()"); Good to add back.

OpenGLES.cpp - (OpenGLES::Initialize()) has some minor logic change which appears to be OK and not WinRT specific. Minor formatting changes probalby good idea, but NOT WinRT specific.

OPenGLES.cpp - (OpenGLES::CreateSurface(SwapChainPanel const &panel)) previously checked for  if (!panel).  Probably good idea to have to make certain panel is not null and then used.

Non WinRT - maybe check for return value from surfaceCreationProperties.Insert(EGLNativeWindowTypeProperty, panel); in both CreateSurface() methods.

Non WinRT - Maybe cleanup/determine if other overloaded CreateSurfance() method is needed.
----
immersiveView.h - New file not in older C++/Cxx implementation
probably a good idea to assign the following to nullptr to make certain they are initialized to nullptr and for later checks where we have if(m_main != nullptr)
  std::unique_ptr<Immersive::ImmersiveMain> m_main = nullptr;
  std::shared_ptr<DX::DeviceResources> m_deviceResources = nullptr;
  
ImmersiveMain.h - similar comment for variables of type std::unique_ptr and std::shared_ptr to be set to nullptr.

The following comments that operations are done asynchronously.  If it is done asynchronously could there be a risk that during the asynch operation the references passed in have changed for another operation/thread that may be using it?

They are not part of the concurrency/asynchrounous operations listed in https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency, but wanted to raise the question.  Also, it appears the variables are being initialized.

Perhaps pass by value?

private:
  // Asynchronously creates resources for new holographic cameras.
  void OnCameraAdded(
      winrt::Windows::Graphics::Holographic::HolographicSpace const &sender,
      winrt::Windows::Graphics::Holographic::
          HolographicSpaceCameraAddedEventArgs const &args);
		  
Possibly OnSuspending() method too.
		  
immersiveView.cpp - new file not in older C++/Cxx implementation. Looks OK. Logic needs to be verified.
               

***** End of Comments ************

**Comment by paulrouget** [comment]
> Did you modify the existing VS2017 solution or create a blank winrt project and then port the files over?

Blank winrt project.

> When you say you “disabled CX extensions…” in the files by replacing ^ with const or other VS2017 solution settings (what solution setting?)

No, it means that "Consume Windows Runtime Extension" option is off (no `/ZW` option passed to the compiler) making it impossible to have CX code.

I'll address your comments and also try to migrate to `co_await` and `apartment_context` for the async code.

**Comment by angelortiz1007** [comment]
Thanks for detailing your steps.  Just wanted to confirm.

 

Here is a link for threading that a new party coming in may like to read in reference to your async migration to co_wait/apartment_context.

 

https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/apartment-context

**Comment by angelortiz1007** [comment]
I Changed the url in the project to point to www.google.com.  There are several output statements with warnings coming from RUST library and others coming from hlservo.  These are more - I believe - app fixes/cleanup over winrt changes. I'll try to get them listed too.  

Example:
RUST: WARN - constellation::constellation - Trying to get an event-loop from an unknown BC group
RUST: WARN - constellation::constellation - Visibility change for closed browsing context PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }.

….

Exception thrown at 0x00007FFB47FAA839 in ServoApp.exe: Microsoft C++ exception: unsigned __int64 at memory location 0x000000852EAFE460.

**Comment by paulrouget** [comment]
>  If it is done asynchronously could there be a risk that during the asynch operation the references passed in have changed for another operation/thread that may be using it?

Nope. Normally all the variables that could be changed are guarded with a mutex.

> Perhaps pass by value?

Can't do that in these case as these functions are part of an interface. But this is common practice for these functions.

I addressed your reviews, also cleanup the code a bit, and added some more commits.

**Comment by paulrouget** [comment]
Waiting on #23801

**Comment by angelortiz1007** [comment]
To answer original question from Josh M.  See response in-line.

**Comment by paulrouget** [comment]
> During runtime in the VS2017 output window you will see some exceptions coming from the application and log warnings/errors coming from RUST. 

Right. We will address these in followups.

I think we good to go.

r? @jdm

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Pull request merged**
