### PR TITLE
Implement meta referrer policy delivery (2)

### LINKED ISSUE #10311: Implement referrer policy
See https://w3c.github.io/webappsec-referrer-policy/

Necessary for https://github.com/servo/servo/issues/10309#issuecomment-203929226

### PR DESCRIPTION
**Pull request by rebstar6**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [X] These changes fix #10311 (github issue number if applicable).

Either:
- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11422)

### CODE REVIEW

**Comment by rebstar6** [comment]
@nox - new PR for https://github.com/servo/servo/pull/11238

**Comment by nox** [comment]
@rebstar6 To further ease our reviewing round-trips, I took the testing part and made a separate, see #11429.

**Comment by rebstar6** [comment]
@nox cool - just got rid of those commits here and added in one taking out the expected failures. Should be good for review :)

**Comment by nox** [comment]
Excuse me @rebstar6, think you could make a new PR again? ^^' Reviewable is not really able to forget all the files that you initially added for the tests if the first revisions.

**Comment by rebstar6** [comment]
Haha can do - https://github.com/servo/servo/pull/11468

**Pull request closed without merging**
