### PR TITLE
Upgrade mach to 0.6; stop vendoring mach.

### PR DESCRIPTION
**Pull request by frewsxcv**
When I originally rewrote Servo's mach bootstrapping (using virtualenv
w/ requirements.txt in #7103), I didn't specify mach as a requirement
because a new version hadn't been published in a while. Now that 0.6
is out, I asked the mach maintainers to publish a new version on PyPI,
so now we can fetch it like the other Python dependencies.

Fixes https://github.com/servo/servo/issues/10728.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10976)

### CODE REVIEW

**Comment by frewsxcv** [comment]
cc @metajack

**Comment by frewsxcv** [comment]
From what I can tell there is no mach changelog, so I made a diff of the changes in the upgrade:

https://gist.github.com/frewsxcv/67c19788508225df88c558194f1c29e5

**Comment by KiChjang** [comment]
@bors-servo retry
* the annoying git

**Comment by frewsxcv** [comment]
> * the annoying git

**Comment by metajack** [comment]
Great work @frewsxcv!

**Pull request merged**
