### PR TITLE
Skip licensing check for CSSWG test package

### PR DESCRIPTION
**Pull request by jdm**
I'm attempting to make the dependencyci check green again.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17117)

### CODE REVIEW

**Comment by aneeshusa** [comment]
The source tarball includes a LICENSE file, so I think it would be better to get that fact reflected.
@SimonSapin and @gsnedders: you're listed on PyPi as package owners, can one of you update PyPI to list the license? (It looks like the Artistic License 2.0.)

**Comment by gsnedders** [comment]
@aneeshusa ergh, the Trove classifiers only have "Artistic License", which is ambiguous as to whether it's 1.0 or 2.0… Does how I've changed it suffice?

**Comment by aneeshusa** [comment]
@gsnedders Yes, it looks like that info has propagated to the PyPI JSON API (https://pypi.python.org/pypi/Template-Python/0.1.post1/json, see the `"license"` key), so once it shows up on Libraries.io (https://libraries.io/pypi/Template-Python), dependencyci should see that and be green again. I'm not sure how long that might take/if we have to poke them. Thanks for updating it on PyPI!

**Comment by jdm** [comment]
Libraries.io has updated with the new license, so this shouldn't be necessary any more. Thanks @aneeshusa!

**Pull request closed without merging**
