### PR TITLE
fix Windows build issue

### LINKED ISSUE #18055: Install/build on Windows 10 not working
Hi all i've just reformated my machine.
I followed the instructions on the readme, (including installing Visual Studio 2017) 
and now i get 
```
PS G:\workspace\servo> .\mach.bat build --dev
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26430.16
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
looking for rustc at G:\workspace\servo\.servo\rust\599be0d18f4c6ddf36366d2a5a2ca6dc65886896\rustc-nightly-x86_64-unknown\rustc\bin\rustc.exe
Downloading Rust compiler...
Download failed (404): Not Found - https://s3.amazonaws.com/rust-lang-ci/rustc-builds/599be0d18f4c6ddf36366d2a5a2ca6dc65886896/rustc-nightly-x86_64-unknown.tar.gz
PS G:\workspace\servo>
```
any idea why?

### PR DESCRIPTION
**Pull request by tigercosmos**
It is not able to build on Windows by following README.
As AppVeyor CI use VS 2015, it seems the script is designed for VS 2015.

I try three environment:
- [ ] Windows10 + VS2017
>not work at the beginning
- [ ] Windows10 + VS1017 with 2015 tool
> PR #18145 can solve download `rustc` problem, but build failed.
- [x] Windows10 + VS2015
> Work pretty well.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #18055 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18157)

### CODE REVIEW

**Comment by atouchet** [comment]
Is #16307 an incomplete solution? I believe it should be possible to build with VS 2017.

**Comment by tigercosmos** [comment]
Yes, I think so. I tested in clean environment with windows10 and VS2017. Maybe need some package not mentioned in readme.

**Comment by atouchet** [comment]
@jdm I think you mean @larsbergstrom

**Comment by larsbergstrom** [comment]
Sorry for the delay on these! I will test these on Saturday.

I would expect Servo to build cleanly in VS2015 and VS2017, largely due to the work of @UK992. The main edge cases I'd expect are trying to build within a non-cmd.exe shell (powershell, cygwin, etc.) or with some more interesting environment variables set. I'll try to dig into what's going on this weekend when I have time to sit down with it. Sorry again for the delay!

**Comment by tigercosmos** [comment]
It's very weird. I try again on a new PC with VS2017 & Win10. No #18145 happens, and it works. I even not install 2015 tools. But this time I install many components (not just README mentioned). I guess some components are critical.

**Comment by larsbergstrom** [comment]
Yeah, I've confirmed on a clean machine & VM that VS 2017 is sufficient to build Servo, so I am closing this. I will look at the other issues you've raised now...

**Comment by tigercosmos** [comment]
@larsbergstrom  Could you tell me which window10 version is used and what VS2017 components installed. I am still very confused, because in many times I have tried, I only success once, and I don't know why.

**Comment by larsbergstrom** [comment]
I'm on Windows 10 Home, version 1703, build 15063.540.

I installed Visual Studio 2017, custom installation adding Visual C++.

**Pull request closed without merging**
