### PR TITLE
use newer wix in CI

### PR DESCRIPTION
**Pull request by sagudev**
Here is changelog: https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Review by mrobinson — COMMENTED** [review]
I wonder if we can start pulling this in via choco or winget? I think these both allow specifying a version.

**Comment by sagudev** [comment]
> wonder if we can start pulling this in via choco

Well it would be nice if this was part of bootstrap.

**Comment by sagudev** [comment]
It's available via choco: https://community.chocolatey.org/packages/wixtoolset

**Review by mrobinson — COMMENTED** [review]
I think the addition of wix to the choco configuration is great. The only issue is that bootstrap isn't run for the CI. You could still install wix via choco though, so that the CI is more similar to developer machines.

**Comment by sagudev** [comment]
I forgot that try builds via bors are useless as they use master files.

**Comment by sagudev** [comment]
Try run on windows: https://github.com/sagudev/servo/actions/runs/6207064721/job/16851930976#step:13:1 package step is run successfully; fails on upload as it's on my fork.

**Review by mrobinson — APPROVED** [review]
Thanks for this!

**Pull request merged**
