### PR TITLE
Implementing JSTraceable for IpcReceiver

### PR DESCRIPTION
**Pull request by ghost**
The `trace` method is demanded by PR #6829 and so, I thought of keeping it neat :)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6837)

### CODE REVIEW

**Comment by pcwalton** [comment]
(Assuming that @jdm actually did review the first one)

**Comment by Wafflespeanut** [comment]
An accident...

**Comment by metajack** [comment]
Why the r-?

**Comment by pcwalton** [comment]
@metajack Requested by PR submitter

**Comment by Wafflespeanut** [comment]
@metajack Because, I accidentally included my first commit here. It was supposed to be fixed in #6829

**Comment by jdm** [comment]
This is missing an import of IpcReceiver. I suggest just including this in #6829 instead.

**Comment by Wafflespeanut** [comment]
very well. (sorry about that)...

**Pull request closed without merging**
