### PR TITLE
layout: Make table cells' minimum inline sizes override explicitly specified widths if the latter are too small.

### PR DESCRIPTION
**Pull request by pcwalton**
Improves ebay.com.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7274)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed 14 of 14 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7274)

**Comment by Ms2ger** [comment]
Anyone who can point me at a spec?

**Comment by pcwalton** [comment]
Intrinsic widths have no spec, but are needed for Web compatibility. The closest is http://dbaron.org/css/intrinsic/#outer-intrinsic-min, but the language seems wrong (not Web compatible) in this case.

**Pull request merged**
