### PR TITLE
Making map+clone more succinct with cloned

### PR DESCRIPTION
**Pull request by craftytrickster**
https://github.com/servo/servo/issues/7906

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7949)

### CODE REVIEW

**Comment by nox** [comment]
One nit and this is good to go.

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/net/storage_task.rs, line 111 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7949#-K0Gn7-vh5bvKSZ7I4kH)** ([raw file](https://github.com/servo/servo/blob/2deb41ecd04ff075b226a4ec797721d420850022/components/net/storage_task.rs#L111)):</sup>
The indentation looks weird, what about this:
```rust
let key = data.get(&origin)
              .and_then(|&(_, ref entry)| entry.keys().nth(index as usize))
              .cloned();
sender.send(key).unwrap();
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7949)

**Comment by craftytrickster** [comment]
I made the indentation change, please let me know if you need anything else.

**Comment by nox** [comment]
Looks good, thanks! 

@bors-servo r+


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7949)

**Comment by frewsxcv** [comment]
Ignore the failure, our build system is temporarily broken

**Comment by frewsxcv** [comment]
@bors-servo retry

* buildbot was broken

**Pull request merged**
