### PR TITLE
Don't double-apply transform and other effect styles for text (fixes #11300)

### LINKED ISSUE #11300: Text within rotated div is displayed incorrectly
rotate

```
<!DOCTYPE html>
<html><body style="font-size: 4em; padding: 1em;">
    <div style="transform: rotateZ(45deg); border: 1px solid red; display: inline-block;">Servo</div>
</body></html>
```

### PR DESCRIPTION
**Pull request by vvuk**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [X] These changes fix #11300 

Either:
- [X] There are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11421)

### CODE REVIEW

**Comment by pcwalton** [comment]
@bors-servo: r+

Sweet!

**Comment by mbrubeck** [comment]
Looks like two manifest entries are out of (alphabetical) order:
```
diff --git a/tests/wpt/mozilla/meta/MANIFEST.json b/tests/wpt/mozilla/meta/MANIFEST.json
index 564faac..36122ad 100644
--- a/tests/wpt/mozilla/meta/MANIFEST.json
+++ b/tests/wpt/mozilla/meta/MANIFEST.json
@@ -5049,7 +5049,7 @@
             "path": "css/text_node_effects.html",
             "references": [
               [
-                "/_mozilla/css/text_node_effects_ref.html",
+                "/_mozilla/css/text_node_opacity_ref.html",
                 "=="
               ]
             ],
@@ -11873,7 +11873,7 @@
           "path": "css/text_node_effects.html",
           "references": [
             [
-              "/_mozilla/css/text_node_effects_ref.html",
+              "/_mozilla/css/text_node_opacity_ref.html",
               "=="
             ]
           ],
```

**Comment by mbrubeck** [comment]
[test-wpt](http://build.servo.org/builders/linux-rel/builds/1251/steps/test_1/logs/stdio):
```
Ran 4839 tests finished in 357.0 seconds.
  • 4838 ran as expected. 1232 tests skipped.
  • 1 tests failed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /_mozilla/css/text_node_effects.html
  └   → /_mozilla/css/text_node_effects.html 64720f8e5b3e2cba520e17b6463df18ccfe11b66
/_mozilla/css/text_node_effects_ref.html 504920195a62057d36cedf48e7cd26c662f61b08
Testing 64720f8e5b3e2cba520e17b6463df18ccfe11b66 == 504920195a62057d36cedf48e7cd26c662f61b08
```
[test-css](http://build.servo.org/builders/linux-rel/builds/1251/steps/test_3/logs/stdio):
```
Ran 9969 tests finished in 949.0 seconds.
  • 9944 ran as expected. 129 tests skipped.
  • 2 tests failed unexpectedly
  • 23 tests passed unexpectedly

Tests with unexpected results:
  ▶ FAIL [expected PASS] /css-transforms-1_dev/html/regions-transforms-019.htm
  └   → /css-transforms-1_dev/html/regions-transforms-019.htm 0dc5507a9e6d86af09736eb3c7f5619ddc7b112e
/css-transforms-1_dev/html/reference/regions-transforms-019-ref.htm 153ad1833f4179f2acae10f21a1c70a8e7670cf2
Testing 0dc5507a9e6d86af09736eb3c7f5619ddc7b112e == 153ad1833f4179f2acae10f21a1c70a8e7670cf2

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-abspos-002.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-abspos-007.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-applies-to-002.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-origin-003.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-origin-006.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-origin-005.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-origin-004.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-propagate-inherit-boolean-001.htm

  ▶ FAIL [expected PASS] /css-transforms-1_dev/html/transform-transformable-inline-block.htm
  └   → /css-transforms-1_dev/html/transform-transformable-inline-block.htm 28561413de7a0bc469cbfd3afb77a5b44c5000bf
/css-transforms-1_dev/html/reference/transform-transformable-inline-block-ref.htm d9d9e489bc5b4508c01b06c7ff92f19dcc2ece3c
Testing 28561413de7a0bc469cbfd3afb77a5b44c5000bf == d9d9e489bc5b4508c01b06c7ff92f19dcc2ece3c

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translate-001.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translate-002.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translate-004.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translate-005.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translate-003.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatex-002.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatex-003.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatex-005.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatex-001.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatey-003.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatey-001.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatex-004.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatey-002.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatey-004.htm

  ▶ PASS [expected FAIL] /css-transforms-1_dev/html/transform-translatey-005.htm
```

**Comment by pcwalton** [comment]
Is this ready for review again?

**Comment by vvuk** [comment]
Yep yep, ready for re-review.  Only change from previous was to the tests, I botched those :p

**Comment by nox** [comment]
Superseded by #14078.

**Pull request closed without merging**
