### PR TITLE
Fix some WebAudio WPTs

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21506)

### CODE REVIEW

**Comment by ferjm** [comment]
@bors-servo retry

* #21513

**Comment by jdm** [comment]
@ferjm Are you still working on this?

**Comment by ferjm** [comment]
Oh, I forgot about this one :D. Some of this has already been fixed. But there are still two valid fixes here. I'll rebase. Thanks

**Comment by CYBAI** [comment]
Looks unrelated:

```
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/_webgl/conformance/extensions/ext-shader-texture-lod.html", "line": 140277, "action": "test_result", "expected": "OK"}
```

**Comment by ferjm** [comment]
I only rebased and regenerated the test expectations, so I am carrying over Manish's r+ from https://github.com/servo/servo/pull/21506#issuecomment-415791974

@bors-servo r=Manishearth

**Pull request merged**
