### PR TITLE
Script elements now fire async error events (fixes #4506)

### LINKED ISSUE #4506: Fire asynchronous error events for script element events
According to https://html.spec.whatwg.org/multipage/scripting.html#prepare-a-script:

```
If the element has a src content attribute, run these substeps:
* Let src be the value of the element's src attribute.
* If src is the empty string, queue a task to fire a simple event named error at the element, and abort these steps.
* Resolve src relative to the element.
* If the previous step failed, queue a task to fire a simple event named error at the element, and abort these steps
```

This should be a Runnable object that contains a `Trusted<HTMLScriptElement>` value.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #4506

### CODE REVIEW

**Comment by saneyuki** [comment]
We cannot accept the current your patch because your patch doesn't satisfy the following clause:

> queue a task to fire a simple event.

This need to use [`Trusted<T>`](http://doc.servo.org/script/dom/bindings/refcounted/struct.Trusted.html) like [this](https://github.com/servo/servo/blob/e3a4d493117ffd09ce75270b36012845ebb9c08c/components/script/dom/htmlscriptelement.rs#L233).

**Comment by KiChjang** [comment]
Added a new commit that address the issue @saneyuki mentioned

**Comment by jdm** [comment]
Squash!

**Comment by KiChjang** [comment]
Squashed.

**Pull request merged**
