### PR TITLE
readme: add build status badges

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Preview can be seen here:

https://github.com/matthiaskrgr/servo/tree/readme#the-servo-parallel-browser-engine-project

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10482)

### CODE REVIEW

**Comment by perlun** [comment]
Awesome - thanks Matthias!

**Comment by jdm** [comment]
Thank you for submitting this and linking to the demo! I'm not convinced that this is very useful for Servo, however, since we have automation that prevents code from merging if any part of the build or test process fails on any supported platform. The fact that the appveyor builds are failing right now is a problem with the appveyor setup, rather than an indication that Servo can't be built on Windows in its current state.

**Comment by matthiaskrgr** [comment]
Hmm.
Part of the motivation of this patch was that master  branch was actually failing on travis a few hours ago.
https://travis-ci.org/servo/servo/builds

Besides it might be good for users to see that the project cares about stability and that the master branch is in buildable state.

I can hide the appveyor badge if you want.

**Comment by jdm** [comment]
Yeah, the travis situation was an unfortunate mismatch between what runs in `.travis.yml` and what runs in https://github.com/servo/saltfs/blob/master/buildbot/master/master.cfg . I remain on the fence about this, so I'll defer to others.

**Comment by notriddle** [comment]
There's always options:

[Builds always passing!](http://build.servo.org:54856/queue/servo)

**Comment by nox** [comment]
Reassigning to @jdm.

**Comment by jdm** [comment]
Well, given how often recently we've had failures that are legitimate and indicative of real problems, I'm going to go ahead and merge this. Hopefully they'll stop being necessary soon :)

@bors-servo: r+

**Comment by KiChjang** [comment]
@bors-servo retry
* #10392

**Pull request merged**
