### PR TITLE
Enable Request API and Response API tests

### PR DESCRIPTION
**Pull request by jeenalee**
This will enable the Request API and Response API tests, which will be useful for PR #12700 and the future PR regarding the Response API. 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12722)

### CODE REVIEW

**Comment by KiChjang** [comment]
Needs more test expectation updates:

```
Ran 6830 tests finished in 863.0 seconds.
  • 6825 ran as expected. 1998 tests skipped.
  • 2 tests timed out unexpectedly
  • 3 tests unexpectedly okay
  • 3 tests had unexpected subtest results

Tests with unexpected results:
  ▶ OK [expected CRASH] /fetch/api/request/request-error.html

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's mode is no-cors and method is not simple
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"mode" : "no-cors", "method" : "PUT"}); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:42:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:41:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] Request should not get its content-type from the init request if init headers are provided
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:66:30
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:65:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's cache mode is only-if-cached and mode is not same-origin
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"mode" : "cors", "cache" : "only-if-cached"}); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:53:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:52:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's mode is no-cors and integrity is not empty
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"mode" : "no-cors", "integrity" : "not  an empty string"}); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:47:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:46:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's referrer has invalid origin
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"referrer" : "http://test.url"}); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:27:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:26:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's method is forbidden
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"method" : "TRACE"}); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:37:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:36:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] Bad referrerPolicy init parameter value
  │   → assert_throws: function "function () { new Request("", options); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ FAIL [expected PASS] Bad mode init parameter value
  │   → assert_throws: function "function () { new Request("", options); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ FAIL [expected PASS] Bad credentials init parameter value
  │   → assert_throws: function "function () { new Request("", options); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ FAIL [expected PASS] Bad cache init parameter value
  │   → assert_throws: function "function () { new Request("", options); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ FAIL [expected PASS] Bad redirect init parameter value
  │   → assert_throws: function "function () { new Request("", options); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:92:11
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:89:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:88:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's method is invalid
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"method" : "IN VALID"}); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:32:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:31:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] Request should get its content-type from the body if none is provided
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:74:30
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:73:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's mode is navigate
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"mode" : "navigate"}); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:17:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:16:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] Request should get its content-type from the init request
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:59:30
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:58:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] Input URL has credentials
  │   → assert_throws: Expect TypeError exception function "function () { new Request("http://user:pass@test.url"); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:12:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:11:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] Request should get its content-type from init headers if one is provided
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:81:30
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:80:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's window is not null
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"window" : "http://test.url"}); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:2:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:1:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] RequestInit's referrer is invalid
  │   → assert_throws: Expect TypeError exception function "function () { new Request("", {"referrer" : "http://:not a valid URL"}); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:22:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:21:7

  ▶ Unexpected subtest result in /fetch/api/request/request-error.html:
  │ FAIL [expected PASS] Input URL is not valid
  │   → assert_throws: Expect TypeError exception function "function () { new Request("http://:not a valid URL"); }" threw object "ReferenceError: Request is not defined" ("ReferenceError") expected object "TypeError" ("TypeError")
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-error.html:7:9
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-error.html:6:7

  ▶ OK [expected CRASH] /fetch/api/request/request-init-001.sub.html

  ▶ Unexpected subtest result in /fetch/api/request/request-init-001.sub.html:
  │ FAIL [expected PASS] Check method init value of GET and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check method init value of HEAD and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check method init value of POST and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check method init value of PUT and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check method init value of DELETE and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check method init value of OPTIONS and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check method init value of head and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrer init value of /relative/ressource and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrer init value of http://web-platform.test:8000/relative/ressource?query=true#fragment and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrer init value of http://web-platform.test:8000/ and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrer init value of about:client and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrer init value of  and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrerPolicy init value of  and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrerPolicy init value of no-referrer and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrerPolicy init value of no-referrer-when-downgrade and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrerPolicy init value of origin and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrerPolicy init value of origin-when-cross-origin and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check referrerPolicy init value of unsafe-url and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check mode init value of same-origin and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check mode init value of no-cors and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check mode init value of cors and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check credentials init value of omit and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check credentials init value of same-origin and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check credentials init value of include and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check cache init value of default and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check cache init value of no-store and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check cache init value of reload and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check cache init value of no-cache and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check cache init value of force-cache and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check redirect init value of follow and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check redirect init value of error and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check redirect init value of manual and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check integrity init value of  and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check integrity init value of AZERTYUIOP1234567890 and associated getter
  │   → Request is not defined
  │ FAIL [expected PASS] Check window init value of null and associated getter
  │   → Request is not defined
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-init-001.sub.html:72:17
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-init-001.sub.html:69:11

  ▶ OK [expected CRASH] /fetch/api/request/request-headers.html

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Request should get its content-type from the body if none is provided
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:123:30
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:122:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Adding invalid no-cors request header "Content-Type: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid no-cors request header "Potato: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid no-cors request header "proxy: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid no-cors request header "proxya: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid no-cors request header "sec: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid no-cors request header "secb: KO"
  │   → Request is not defined
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:82:15
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:81:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:80:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Request should get its content-type from the init request
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:108:30
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:107:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Adding valid request header "Content-Type: OK"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid request header "Potato: OK"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid request header "proxy: OK"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid request header "proxya: OK"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid request header "sec: OK"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid request header "secb: OK"
  │   → Request is not defined
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:60:15
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:59:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:58:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Adding invalid request header "Accept-Charset: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "accept-charset: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "ACCEPT-ENCODING: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Accept-Encoding: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Access-Control-Request-Headers: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Access-Control-Request-Method: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Connection: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Content-Length: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Cookie: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Cookie2: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Date: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "DNT: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Expect: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Host: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Keep-Alive: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Origin: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Referer: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "TE: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Trailer: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Transfer-Encoding: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Upgrade: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Via: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Proxy-: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "proxy-a: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "Sec-: KO"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding invalid request header "sec-b: KO"
  │   → Request is not defined
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:67:15
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:66:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:65:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Check that no-cors request constructor is filtering headers provided as part of request parameter
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:101:23
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:100:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Request should get its content-type from init headers if one is provided
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:130:30
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:129:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Check that no-cors request constructor is filtering headers provided as init parameter
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:95:23
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:94:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Adding valid no-cors request header "Accept: OK"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid no-cors request header "Accept-Language: OK"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid no-cors request header "content-language: OK"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid no-cors request header "content-type: application/x-www-form-urlencoded"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid no-cors request header "content-type: application/x-www-form-urlencoded;charset=UTF-8"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid no-cors request header "content-type: multipart/form-data"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid no-cors request header "content-type: multipart/form-data;charset=UTF-8"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid no-cors request header "content-TYPE: text/plain"
  │   → Request is not defined
  │ FAIL [expected PASS] Adding valid no-cors request header "CONTENT-type: text/plain;charset=UTF-8"
  │   → Request is not defined
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:75:15
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:74:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:73:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Request should not get its content-type from the init request if init headers are provided
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:115:30
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:114:7

  ▶ Unexpected subtest result in /fetch/api/request/request-headers.html:
  │ FAIL [expected PASS] Check that request constructor is filtering headers provided as init parameter
  │   → Value is not valid
  │ 
  │ @http://web-platform.test:8000/fetch/api/request/request-headers.html:89:23
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ @http://web-platform.test:8000/fetch/api/request/request-headers.html:88:7

  ▶ TIMEOUT [expected CRASH] /fetch/api/request/request-disturbed.html
  │ 
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  └ ERROR:script::dom::bindings::error: Error at http://web-platform.test:8000/fetch/api/request/request-disturbed.html:5:11 Request is not defined

  ▶ TIMEOUT [expected CRASH] /fetch/api/request/request-structure.html
  │ 
  │ Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
  └ ERROR:script::dom::bindings::error: Error at http://web-platform.test:8000/fetch/api/request/request-structure.html:1:11 Request is not defined
```

**Comment by jdm** [comment]
If you click on the link to the failed build, the copy the test-wpt.log link and append `/text` to it, then download the resulting URL, you can use that file as the argument to `./mach update-wpt`.

**Comment by jdm** [comment]
The merge conflicts mean this needs a rebase, unfortunately.

**Pull request merged**
