### PR TITLE
Allow user to choose between GL and ES2

### PR DESCRIPTION
**Pull request by jdm**
Rebase of #8869. Requires https://github.com/servo/rust-layers/pull/232.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9781)

### CODE REVIEW

**Comment by jdm** [comment]
rust-layers merged, so this is good to go.

**Comment by pcwalton** [comment]
@jdm OK for me to review this?

**Comment by jdm** [comment]
@pcwalton Sure!

**Comment by glennw** [comment]
@jdm r=me when rebased.

**Comment by jdm** [comment]
@bors-servo: retry
* rolling appveyor builds

**Comment by jdm** [comment]
@bors-servo: retry
* #9723

**Pull request merged**
