### PR TITLE
Implement ElementClick wd command

### PR DESCRIPTION
**Pull request by georgeroman**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24090)

### CODE REVIEW

**Review by jdm — CHANGES_REQUESTED** [review]

**Review by jdm — APPROVED** [review]

**Comment by georgeroman** [comment]
@jdm Is this ready for merging?

**Comment by CYBAI** [comment]
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "AssertionError: javascript error (500): JS evaluation raised an exception", 
    "stack": "session = <Session 1f42a8a2-3e79-4849-bcc9-b7e17b9c0dee>\n\n    def test_element_in_collection(session):\n        session.url = inline(\"<div></div>\")\n        divs = session.find.css(\"div\")\n    \n        response = execute_script(session, \"\"\"\n            let div = document.querySelector(\"div\");\n            div.reference = div;\n            return [div];\n            \"\"\")\n>       value = assert_success(response)\n\ndivs       = [<Element 7733c369f4894450a776e665557100d7>]\nresponse   = <Response status=500 error=<JavascriptErrorException http_status=500>>\nsession    = <Session 1f42a8a2-3e79-4849-bcc9-b7e17b9c0dee>\n\ntests/wpt/web-platform-tests/webdriver/tests/execute_script/cyclic.py:61: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response status=500 error=<JavascriptErrorException http_status=500>>\nvalue = None\n\n    def assert_success(response, value=None):\n        \"\"\"\n        Verify that the provided webdriver.Response instance described\n        a valid success response as defined by `dfn-send-a-response` and\n        the provided response value.\n    \n        :param response: ``webdriver.Response`` instance.\n        :param value: Expected value of the response body, if any.\n        \"\"\"\n>       assert response.status == 200, str(response.error)\nE       AssertionError: javascript error (500): JS evaluation raised an exception\nE         \nE       assert 500 == 200\nE        +  where 500 = <Response status=500 error=<JavascriptErrorException http_status=500>>.status\n\nresponse   = <Response status=500 error=<JavascriptErrorException http_status=500>>\nvalue      = None\n\ntests/wpt/web-platform-tests/webdriver/tests/support/asserts.py:67: AssertionError", 
    "subtest": "test_element_in_collection", 
    "test": "/webdriver/tests/execute_script/cyclic.py", 
    "line": 1338, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Comment by georgeroman** [comment]
Hmm, this is the same tests that strangely failed on Mac in https://github.com/servo/servo/pull/23725. It now also fails on Linux, that's weird, especially since this PR should have no influence on it.

**Pull request merged**
