### PR TITLE
form-associated custom elements and their ElementInternals

### LINKED ISSUE #24988: Implement attachInternals and ElementInternals
WPT custom-elements/HTMLElement-attachInternals, custom-elements/ElementInternals-NotSupportedError, custom-elements/form-associated/form-disabled-callback, and all of custom-elements-form-associated/ElementInternals* expect attachInternals to exist, and to return an ElementInternals where appropriate

### LINKED ISSUE #25015: Form-associated custom element behavior issues
Most of the WPT custom-elements/form-associated tests fail for lack of ElementInternals. The few that don't look questionable by https://wpt.fyi/results/custom-elements/form-associated?label=master&label=experimental&aligned ; Servo's failures are consistent with Firefox and Safari's.

### LINKED ISSUE #25017: customElements.define isn't checking disabledFeatures and formAssociated when expected
WPT custom-elements/CustomElementRegistry has various tests that set up call-trace proxies around a custom class and then call customElements.define to see which fields are accessed. In general, `disabledFeatures` and `formAssociated` are expected to be accessed but aren't. A quick grep of servo's codebase suggests these strings might not even be in it.

https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-api specifies getting them, in substeps 14-6 and 14-12 of the define method.

### PR DESCRIPTION
**Pull request by pshaughn**
Form-associated elements are now working.

Remaining test failures in custom-elements/form-associated/ are:
* https://github.com/whatwg/html/pull/4658 hasn't made it into the standard yet, and ElementInternals-accessibility is all about that functionality.
* ElementInternals-setFormValue hits many race conditions with our iframe order of operations. Isolating just the "submit this form with these custom elements, look at the query" part, the payload of each test actually does pass! Running the tests as written, we end up with different tests overwriting each other's elements and getting very confused. One problem is the about:blank double-load-event thing, but fixing that doesn't fix everything. 
* ElementInternals-validation doesn't work because we don't have form validation in general; I've commented the relevant stubs.
* ElementInternals-form-disabled-callback fails on #25713.

fix #24988 fix #25015 fix #25017

### CODE REVIEW

**Comment by pshaughn** [comment]
I made an incidental change to a shared test .js file that might have repercussions.
@bors-servo try=wpt

**Comment by pshaughn** [comment]
Just the usual new-exposed-functionality-exists tests I invariably forget to update the metadata for on my first try.

**Comment by pshaughn** [comment]
https://github.com/web-platform-tests/wpt/pull/21747 just merged; I'll adjust for it in the morning.

**Comment by pshaughn** [comment]
I'll also add a _mozilla version of the setFormValue test that works serially and doesn't race iframe loads against promise reactions.

**Comment by mrobinson** [comment]
Closing this in favor of #31980.

**Pull request closed without merging**
