### PR TITLE
Added direct link to Visual Studio Community

### PR DESCRIPTION
**Pull request by BojanKogoj**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18348)

### CODE REVIEW

**Comment by atouchet** [comment]
I don't think this is really necessary. There's already a direct download link on the main page.

**Comment by BojanKogoj** [comment]
@atouchet fair point, although it wasn't obvious to me that that was community edition

**Comment by asajeffrey** [comment]
Is there a consensus about this?

**Comment by jdm** [comment]
This seems like a reasonable choice to me.

**Pull request merged**
