### PR TITLE
Bump env_logger to 0.5 and log to 0.4 in every servo crate

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20465)

### CODE REVIEW

**Comment by jdm** [comment]
One more set of passing tests in request-consume.html :P

**Comment by jonleighton** [comment]
@Eijebong on master I can no longer see debug output with `RUST_LOG=debug`

**Comment by Eijebong** [comment]
I'll have a look tonight

**Pull request merged**
