### PR TITLE
[FIX] Bug fix #6756

### LINKED ISSUE #6756: Use jsstring_to_str in handle_evaluate_js
The FIXME in `handle_evaluate_js` about using `jsstring_to_str` is now possible to fix, since [to_string](https://github.com/servo/rust-mozjs/blob/master/src/jsval.rs#L348) now exists.

Code: components/script/devtools.js

### PR DESCRIPTION
**Pull request by khflab**
fixes #6756 waiting for review.

Signed-off-by: Kayo Hamid kayo@bvcupons.com.br

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6902)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
@jdm I suggest we also remove [one other `//FIXME` comment in the same file](http://mxr.mozilla.org/servo/source/components/script/devtools.rs#47) instead of doing it in #6755. I mean, should we keep that issue just for removing a single comment?

**Comment by jdm** [comment]
@bors-servo: r+
Thanks @khflab!

**Comment by khflab** [comment]
@Wafflespeanut I created this issue [6941](https://github.com/servo/servo/issues/6941) to see what to do with this FIXME

**Comment by Wafflespeanut** [comment]
@khflab Sorry, I thought we could do that in this PR itself. Since it got merged, I went ahead and fixed it in #6920. Besides, why file a duplicate issue? :)

**Comment by khflab** [comment]
Because is a easy hack for newcomers like me.

**Comment by jdm** [comment]
In this case it was literally just removing a comment; I think we can find many other appropriate hacks for newcomers like you :)

**Pull request merged**
