### PR TITLE
Fix geckolib breakage caused by 1.16

### PR DESCRIPTION
**Pull request by Manishearth**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16072)

### CODE REVIEW

**Comment by SimonSapin** [comment]
What broke? How?

**Comment by upsuper** [comment]
Unused `#[macro_use]`. Actually the whole `lazy_static` is now unused in geckolib.

**Comment by Manishearth** [comment]
We `-Dwarnings`, and rust 1.16 warns about unused extern crates with macro_use where the macro_use is unused.

**Comment by SimonSapin** [comment]
> We `-Dwarnings`

Ah ok. I was worried that Rust stable had had a regression…

**Pull request merged**
