### PR TITLE
Remove `Constellation::child_processes`.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/servo/servo/issues/11459.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14536)

### CODE REVIEW

**Comment by frewsxcv** [comment]
cc @Ms2ger @asajeffrey

**Comment by Ms2ger** [comment]
Do we need the `ChildProcess` type at all?

**Comment by KiChjang** [comment]
cc @pcwalton

**Pull request merged**
