### PR TITLE
Add a loading indicator in transient mode

### LINKED ISSUE #24549: In Transcient mode (Hololens), add a loading indicator
Some demos take a pretty long time to load and we only see a blank screen. A floating throbber will do.

### PR DESCRIPTION
**Pull request by paulrouget**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24549 (GitHub issue number if applicable)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Comment by CYBAI** [comment]
@bors-servo retry

```
  ▶ Unexpected subtest result in /css/css-text/white-space/trailing-space-position-001.html:
  │ FAIL [expected PASS] CSS Test: Positions of trailing collapsible spaces 4
  │   → assert_equals: expected 0 but got -0
  │ 
  │ @http://web-platform.test:8000/css/css-text/white-space/trailing-space-position-001.html:37:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1908:25
  │ test@http://web-platform.test:8000/resources/testharness.js:544:30
  └ @http://web-platform.test:8000/css/css-text/white-space/trailing-space-position-001.html:35:3
```

**Pull request merged**
