### PR TITLE
Implement :placeholder-shown (fixes #10561)

### LINKED ISSUE #10561: Implement the :placeholder-shown pseudo class
At the moment, it's plain black.

It needs to be `opacity: 0.54`.

Relevant:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1069012
- https://bugzilla.mozilla.org/show_bug.cgi?id=556145
- https://lists.w3.org/Archives/Public/www-style/2013Jan/0283.html

(browserhtml P2 as I think we can work around this for now)

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11572)

### CODE REVIEW

**Comment by nox** [comment]
Err, forgot textarea...

**Comment by nox** [comment]
Just realised that textarea doesn't support placeholder in Servo yet anyway, so this is ready to be merged.

**Comment by nox** [comment]
Fixed the geckolib failure.

**Comment by SimonSapin** [comment]
Reviewed 2 of 6 files at r1, 4 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/htmlinputelement.rs, line 721 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11572#-KJaesniFZD2OP54O38_:-KJaesniFZD2OP54O38a:-1620471889) ([raw file](https://github.com/servo/servo/blob/ff899dc7033449aa01ee61b5e6c28a8760860325/components/script/dom/htmlinputelement.rs#L721)):*
> ```Rust
>         let has_value = !self.textinput.borrow().is_empty();
>         let el = self.upcast::<Element>();
>         el.set_placeholder_shown_state(has_placeholder && !has_value);
> ```

Shouldn’t this logic involve "the element has focus" too? Can it be de-duplicated with whatever code decides to show the placholder or not?

---

*[ports/geckolib/wrapper.rs, line 355 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11572#-KJaePplRB-czgWscXTv:-KJaePpm4M97hVQ3j5Wl:1594883174) ([raw file](https://github.com/servo/servo/blob/ff899dc7033449aa01ee61b5e6c28a8760860325/ports/geckolib/wrapper.rs#L355)):*
> ```Rust
>     fn get_state(&self) -> ElementState {
>         unsafe {
>             ElementState::from_bits_truncate(Gecko_ElementState(self.element) as u16)
> ```

@bholley @heycam @emilio, This changes `ElementState`’s representation from `u8` to `u16`. Do you need to change something on the Gecko side for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11572)*

**Comment by emilio** [comment]
It seems to me that there shouldn't be a problem with the gecko side of this PR.

Gecko uses a 64 bit integer to represent state, and in the servo case we crop it to an `u8`. So probably at some point we might need to expand it more, but it should keep working as it was with this patch.

**Comment by SimonSapin** [comment]
Alright, thanks Emilio.

(Discussed my other comment with @nox on IRC.)

@bors-servo r+

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11561

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #11574

**Pull request merged**
