### PR TITLE
Fix the magicleap CI build

### PR DESCRIPTION
**Pull request by asajeffrey**
This is a WIP PR to diagnose and fix the magicleap build in CI.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because it's fixing the build

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22150)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Landed https://github.com/servo/saltfs/pull/915 which installs makedepend.

@bors-servo try=magicleap

**Comment by jdm** [comment]
`make[1]: /Users/servo/magicleap/v0.17.0/tools/toolchains/bin/aarch64-linux-android-clang: Permission denied`

**Comment by asajeffrey** [comment]
Hmm, that would probably be caused by https://github.com/servo/saltfs/blob/bcc78d578b094e06af93911388e4e0d314adb303/servo-build-dependencies/mac-magicleap.sls#L18
```
{{ common.servo_home }}/magicleap:
  file.directory:
    - user: servo
    - group: staff
    - dir_mode: 755
    - file_mode: 644
    - makedirs: True
    - recurse:
      - user
      - group
- mode
```
the second time this is run, this will remove execute permission from the binaries, sigh.

Could just remove `mode` from the recursion?

**Comment by asajeffrey** [comment]
Yay, https://github.com/servo/saltfs/pull/916 and a bit of manual intervention results in:
```
# ls -l /Users/servo/magicleap/v0.17.0/tools/toolchains/bin/
total 323072
-rwxr-xr-x  1 servo  staff    900828 Sep  6 22:33 aarch64-linux-android-addr2line
-rwxr-xr-x  1 servo  staff    931540 Sep  6 22:33 aarch64-linux-android-ar
-rwxr-xr-x  1 servo  staff   1399084 Sep  6 22:33 aarch64-linux-android-as
-rwxr-xr-x  1 servo  staff    739060 Sep  6 22:33 aarch64-linux-android-c++
-rwxr-xr-x  1 servo  staff    896608 Sep  6 22:33 aarch64-linux-android-c++filt
-rwxr-xr-x  1 servo  staff       188 Sep  6 22:33 aarch64-linux-android-clang
-rwxr-xr-x  1 servo  staff       192 Sep  6 22:33 aarch64-linux-android-clang++
-rwxr-xr-x  1 servo  staff    739060 Sep  6 22:33 aarch64-linux-android-cpp
-rwxr-xr-x  1 servo  staff   4413296 Sep  6 22:33 aarch64-linux-android-dwp
-rwxr-xr-x  1 servo  staff     36152 Sep  6 22:33 aarch64-linux-android-elfedit
-rwxr-xr-x  1 servo  staff    739060 Sep  6 22:33 aarch64-linux-android-g++
-rwxr-xr-x  1 servo  staff    734964 Sep  6 22:33 aarch64-linux-android-gcc
-rwxr-xr-x  1 servo  staff    734964 Sep  6 22:33 aarch64-linux-android-gcc-4.9
-rwxr-xr-x  1 servo  staff    734964 Sep  6 22:33 aarch64-linux-android-gcc-4.9.x
-rwxr-xr-x  1 servo  staff     32312 Sep  6 22:33 aarch64-linux-android-gcc-ar
-rwxr-xr-x  1 servo  staff     32312 Sep  6 22:33 aarch64-linux-android-gcc-nm
-rwxr-xr-x  1 servo  staff     32312 Sep  6 22:33 aarch64-linux-android-gcc-ranlib
-rwxr-xr-x  1 servo  staff    377332 Sep  6 22:33 aarch64-linux-android-gcov
-rwxr-xr-x  1 servo  staff    421508 Sep  6 22:33 aarch64-linux-android-gcov-tool
-rwxr-xr-x  1 servo  staff    968420 Sep  6 22:33 aarch64-linux-android-gprof
-rwxr-xr-x  1 servo  staff   1982456 Sep  6 22:33 aarch64-linux-android-ld
-rwxr-xr-x  1 servo  staff   1982456 Sep  6 22:33 aarch64-linux-android-ld.bfd
-rwxr-xr-x  1 servo  staff   6920628 Sep  6 22:33 aarch64-linux-android-ld.gold
-rwxr-xr-x  1 servo  staff    909040 Sep  6 22:33 aarch64-linux-android-nm
-rwxr-xr-x  1 servo  staff   1083700 Sep  6 22:33 aarch64-linux-android-objcopy
-rwxr-xr-x  1 servo  staff   1530468 Sep  6 22:33 aarch64-linux-android-objdump
-rwxr-xr-x  1 servo  staff    931548 Sep  6 22:33 aarch64-linux-android-ranlib
-rwxr-xr-x  1 servo  staff    448032 Sep  6 22:33 aarch64-linux-android-readelf
-rwxr-xr-x  1 servo  staff    900880 Sep  6 22:33 aarch64-linux-android-size
-rwxr-xr-x  1 servo  staff    900884 Sep  6 22:33 aarch64-linux-android-strings
-rwxr-xr-x  1 servo  staff   1083700 Sep  6 22:33 aarch64-linux-android-strip
-rwxr-xr-x  1 servo  staff  47219428 Sep  6 22:33 clang
-rwxr-xr-x  1 servo  staff  47219428 Sep  6 22:33 clang++
-rwxr-xr-x  1 servo  staff   3978432 Sep  6 22:33 clang-format
-rwxr-xr-x  1 servo  staff  23524124 Sep  6 22:33 clang-tidy
-rwxr-xr-x  1 servo  staff        94 Sep  6 22:33 gdb
-rwxr-xr-x  1 servo  staff   9867224 Sep  6 22:33 gdb-orig
```
@bors-servo retry

**Comment by asajeffrey** [comment]
Hmm, still building blurdroid.

**Comment by jdm** [comment]
Yeah, I discovered that when doing a build locally as well with this patch applied.

**Comment by asajeffrey** [comment]
Rebased. Try making bluetooth opt-in rather than opt-out. @bors-servo try=magicleap

**Comment by asajeffrey** [comment]
Still building blurdroid? OK, let's try making it off-by-default in servo and libsimpleservo. (We'd have to re-enable it in mach.) @bors-servo try=magicleap

**Comment by asajeffrey** [comment]
Unused extern crates apparently.
```
error: unused extern crate
 --> ports/libmlservo/src/lib.rs:5:1
  |
5 | extern crate egl;
  | ^^^^^^^^^^^^^^^^^ help: remove it
  |
  = note: `-D unused-extern-crates` implied by `-D warnings`

error: `extern crate` is not idiomatic in the new edition
 --> ports/libmlservo/src/lib.rs:8:1
  |
8 | extern crate servo;
  | ^^^^^^^^^^^^^^^^^^^ help: convert it to a `use`

error: unused extern crate
 --> ports/libmlservo/src/lib.rs:9:1
  |
9 | extern crate smallvec;
  | ^^^^^^^^^^^^^^^^^^^^^^ help: remove it

error: aborting due to 3 previous errors
```

**Comment by asajeffrey** [comment]
Hmm, maybe try=magicleap isn't working after all :/

**Comment by asajeffrey** [comment]
Squashed. @bors-servo try=magicleap

**Review by jdm — APPROVED** [review]

**Comment by asajeffrey** [comment]
@bors-servo retry
 * #22161

**Comment by jdm** [comment]
@bors-servo retry
* #13480

**Pull request merged**
