### PR TITLE
Add CSSOM 'Extensions to the HTMLImageElement Interface' in WebIDL.

### PR DESCRIPTION
**Pull request by frewsxcv**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10523)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Not sure why, but eh.

@bors-servo r+

**Comment by KiChjang** [comment]
```
Ran 4656 tests finished in 1070.0 seconds.
  • 4655 ran as expected. 1361 tests skipped.
  • 1 tests crashed unexpectedly

Tests with unexpected results:
  ▶ CRASH [expected TIMEOUT] /html/browsers/history/the-location-interface/assign_before_load.html
```

**Pull request merged**
