### PR TITLE
Write a macro or syntax extension to generate OpenType tags

### LINKED ISSUE #4556: Write a macro or syntax extension to generate OpenType tags
OpenType features have four-character "tags" like `liga` or `kern`.  In harfbuzz a tag is represented as four bytes packed into a `u32`, like in [this example](https://github.com/servo/servo/blob/cf616b90a236f88058dbad74b568b4d4379d2829/components/gfx/text/shaping/harfbuzz.rs#L53-L54).  This code would be more readable if we had a [macro or syntax extension](http://doc.rust-lang.org/guide-macros.html) so that we could write something more like `hb_tag!("liga")` or maybe `hb_tag!('l', 'i', 'g', 'a')`.

### PR DESCRIPTION
**Pull request by gilles-leblanc**
Fixes #4556

### CODE REVIEW

**Comment by mbrubeck** [comment]
Oops, I didn't notice that we already had a `true_type_tag` function.  Not sure why I thought this had to be a macro.  Do we still need this, or should we just use `true_type_tag` everywhere?

**Comment by gilles-leblanc** [comment]
I would say the macro prevents a function call and the instantiation of 4 variables so it's probably a bit faster. 

I would go with the macro. If you wish I can also switch the code to use the ```true_type_tag``` and remove the macro. ```true_type_tag``` isn't used right now.

**Comment by mbrubeck** [comment]
Sure, let's remove `true_type_tag` and use the macro everywhere.  The compiler might be able to optimize the function into a constant, but with the macro we don't have to count on it.

**Comment by gilles-leblanc** [comment]
@Manishearth and @mbrubeck Following the acceptance of the code review on critic I rebased on master and merged my 3 commits into one and push again. 

This pull request can be merged.

**Pull request closed without merging**
