### PR TITLE
Update web-platform-tests

### PR DESCRIPTION
**Pull request by jdm**
This includes all of the post-csswg merge, but does not start running those tests.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16491)

### CODE REVIEW

**Comment by SimonSapin** [comment]
So we’re adding another copy of CSSWG tests without removing the previous 3 copies?

**Comment by jdm** [comment]
Yes, because I want to update the web-platform-tests without having to wait on figuring out what to do about the new CSS tests. Also, what are the other two copies that you're talking about?

**Comment by jdm** [comment]
http://build.servo.org/builders/mac-rel-wpt1/builds/3402/steps/test__1/logs/test-wpt.log (stdio)
http://build.servo.org/builders/linux-rel-wpt/builds/3475/steps/test__1/logs/test-wpt.log (stdio)
http://build.servo.org/builders/mac-rel-wpt2/builds/3476/steps/test/logs/test-wpt.log (stdio)
needs a `./mach update-manifest`
`./mach test-tidy --all` failed

**Comment by SimonSapin** [comment]
We have in the repo the output of CSSWG’s build system, where most tests are in three different "formats". For example:

```
tests/wpt/css-tests/css21_dev/html4/absolute-non-replaced-height-001.htm
tests/wpt/css-tests/css21_dev/xhtml1/absolute-non-replaced-height-001.xht
tests/wpt/css-tests/css21_dev/xhtml1print/absolute-non-replaced-height-001.xht
```

But I they’re in git history regardless of what we do now, and I assume the growth is checkout size is only temporary. (We’ll eventually run CSS tests from `tests/wpt/web-platform-tests` and remove `tests/wpt/css-tests`.) So never mind :)

**Comment by nox** [comment]
I couldn't force push to it, so I made a new PR.

**Pull request closed without merging**
