### PR TITLE
Handle font load errors in FontContext

### PR DESCRIPTION
**Pull request by cyndis**
Thread font load errors from platform font loading code to
FontContext::get_layout_font_group_for_style, and cache the failure
result, instead of panicing the thread when a font fails to load.

Before this patch, a failed font load would panic a LayoutTask,
causing a cascade of panics, eventually aborting the whole engine
during a panic within panic.

On my Arch Linux machine almost every page would crash in this manner,
including e.g. reddit.com and cnn.com. Mosf of the requested fonts would
load fine but some single variant of Helvetica would fail always. Not sure
how to create a test for this as it seems pretty system-specific.

Cheers,
cyndis

### CODE REVIEW

**Comment by jdm** [comment]
Nice! These changes make sense to me, but someone more familiar with the setup of our font-loading code should probably take a look. I nominate @glennw.

**Comment by glennw** [comment]
This looks good to me after Ms2ger's comments are addressed. Thanks!

**Comment by cyndis** [comment]
Thanks for reviewing! I changed the 'if let's to a .map() and a match.

**Comment by jdm** [comment]
Go ahead and squash these!

**Comment by cyndis** [comment]
Squashed

**Pull request closed without merging**
