### PR TITLE
  Run our reftests with wptrunner rev4

### PR DESCRIPTION
**Pull request by initsecret**
moved tests from ref to wpt, to enable use of wptrunner.
#5618

Thanks,

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6925)

### CODE REVIEW

**Comment by s142857** [comment]
all the tests are running,but not updating manifest
tests1
tests2

**Comment by s142857** [comment]
i solved the issue

**Comment by jdm** [comment]
What did you do to solve it?

**Comment by s142857** [comment]
i put wrong path before, im such a noob, i included only mozilla//css/csswg

**Comment by s142857** [comment]
now i put include _mozilla/

**Comment by s142857** [comment]
can you please merge these commits

**Comment by s142857** [comment]
creating new request

**Pull request closed without merging**
