### PR TITLE
Implement SampleCoverage

### PR DESCRIPTION
**Pull request by dzbarsky**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy --faster` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11324)

### CODE REVIEW

**Comment by jdm** [comment]
There are tests but no test result changes? That doesn't sound likely.

**Comment by emilio** [comment]
@jdm: We don't support multisampling yet, so adding this function is a no-op right now.

**Comment by emilio** [comment]
@bors-servo: retry

 * https://github.com/servo/servo/issues/11348

**Comment by emilio** [comment]
@bors-servo: retry

 * git

**Pull request merged**
