### PR TITLE
Remove integrity metadata checking with "no-cors"

### LINKED ISSUE #18345: Remove integrity check for no-cors requests
The Fetch specification has been updated to allow non-empty integrity strings for requests that are marked as no-cors: https://github.com/whatwg/fetch/pull/584

We should remove the corresponding check in our implementation:
https://dxr.mozilla.org/servo/rev/3dceb111587178cdff60041d76a2544f275e6371/components/script/dom/request.rs#326-329

Unfortunately, there's no automated test available for this yet because we are having trouble updating our copy of the upstream tests. However, you can try it yourself by running a page that evaluates this JS: `new Request("", {"mode" : "no-cors", "integrity" : "not  an empty string"});`.

### PR DESCRIPTION
**Pull request by rustjson**
Deleted `integrity metadata` check and its tests case according to this: https://github.com/whatwg/fetch/pull/584

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #18345 

I've deleted the tests of this case, but we probably should add `a success one` for this, since I have no idea about the folder and name, I will wait for whatwg provider it and copy from them.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18369)

### CODE REVIEW

**Comment by nox** [comment]
@RustJason Thanks for your contribution! Unfortunately it can't be accepted as is, with that merge commit on the branch. Please remove it.

**Comment by RustJason** [comment]
@nox Done!

**Comment by RustJason** [comment]
ping @nox

**Comment by KiChjang** [comment]
Fixed by #18617.

**Pull request closed without merging**
