### PR TITLE
webgl: Implement the pending texImage2D overload, and add more validation

### PR DESCRIPTION
**Pull request by emilio**
This is a large-ish refactor of the Texture2D code, but it should be
easier to read and of course more correct.

I tried to annotate every error condition with a spec paragraph.

I made just a reftest to ensure this works as intended, since I expect #10373 to land pretty soon.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10443)

### CODE REVIEW

**Comment by jdm** [comment]
I won't insist on the strong types idea if you want to get this merged quickly, but I'd like it filed as a follow up if that's the case.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 5 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 208 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBh6omR6cC5l_obxb2:-KFBh6omR6cC5l_obxb3:-1992764184) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L208)):*
`is generated if data_type`

---

*[components/script/dom/webglrenderingcontext.rs, line 236 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBhKu2we4olY92trdf:-KFBhKu2we4olY92trdg:-1985503806) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L236)):*
`internal_format`

---

*[components/script/dom/webglrenderingcontext.rs, line 253 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBhMcBFZE1bdSW8UIS:-KFBhMcBFZE1bdSW8UIT:-1985503806) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L253)):*
`internal_format`

---

*[components/script/dom/webglrenderingcontext.rs, line 285 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBhecpy_GPJ5_YZMZT:-KFBhecpy_GPJ5_YZMZU:-256241284) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L285)):*
nit: let's move this on the previous line and unindent the next two lines.

---

*[components/script/dom/webglrenderingcontext.rs, line 290 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBhi1ifK_xuULi_wjx:-KFBhi1judJASbP42bS7:1837340219) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L290)):*
nit: let's move this on the previous line and unindent the next two.

---

*[components/script/dom/webglrenderingcontext.rs, line 1462 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBj2DYOY_8BcrURzTG:-KFBj2DYOY_8BcrURzTH:-522196770) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L1462)):*
It might be nice to ensure this via types, as mentioned earlier.

---

*[components/script/dom/webglrenderingcontext.rs, line 1610 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFf3qu_FPR5lF4XXYeM:-KFf3quauRdHwZgHJ50b:-582500633) ([raw file](https://github.com/servo/servo/blob/50964a060fd9bd0f8f863ca95941b06136bf7076/components/script/dom/webglrenderingcontext.rs#L1610)):*
I'm tempted to say that `validate_tex_image_parameters` should return a new structure with strongly typed data that avoids the need for lines like this.

---

*[components/script/dom/webglrenderingcontext.rs, line 1649 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFf4Pa_Jk7f6PbNnOIC:-KFf4Pa_Jk7f6PbNnOID:2133788778) ([raw file](https://github.com/servo/servo/blob/50964a060fd9bd0f8f863ca95941b06136bf7076/components/script/dom/webglrenderingcontext.rs#L1649)):*
s/pixels/data/.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10443#-:-KFf54nyD7oTX6GR--RL:-2000595678)*

**Comment by emilio** [comment]
Agreed this should probably take more advantage of rust's type system.

I can't dive into it right now, but I'll get the issue filled. I'd like to take some time to think in an elegant design for this.

As a quick-think something like the following could work:

```rust
trait AsGLError {
    fn as_gl_error(&self) -> WebGLError;
}

trait Validator {
    type Input;
    type Error: std::error::Error + AsGLError;
    type Validated;

    // NB: if something from Self::Input should be used afterwards, it should be returned in Self::Validated,
    // this prevents accessing invalid data completely.
    fn validate(Self::Input) -> Result<Self::Validated, Self::Error>;
}

// e.g.
struct TexImage2DValidator;
struct TexImage2DParams {
    width: i32,
    data: Vec<u8>,
    // ...
}
impl Validator for TexImage2DValidator {
    type Input = TexImage2DParams;
    type Error = TexImage2DError;
    type Validated = TexImage2DValidParams;

    fn validate(params: TexImage2DParams) -> Result<Self::Validated, Self::Error> { ... }
}
```

Does such an API look good to you?

It's a post-shower though, so maybe it's not too acurate. I also think it might get simplified with something like:

```rust
trait Validable {
    type Valid;
    type Error: std::error::Error + AsGLError;
    fn validate(self) -> Result<Self::Valid, Self::Error>;
}

impl Validable for TexImage2DParams { ... }
```

Anyways, will link to this (or copy it in the issue) so this can be discussed further.

This can also allow us to split a few chunks of the code in other modules, making `webglrenderingcontext.rs` a bit nicer to read, and have more useful error messages :)

EDIT: Opened #10693 (will fill with details now)

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 208 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBh6omR6cC5l_obxb2:-KFfAv2fRolsVAXOH9sM:-499146009) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L208)):*
Done.

---

*[components/script/dom/webglrenderingcontext.rs, line 236 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBhKu2we4olY92trdf:-KFfB0X2i80Brcj3fpsy:-499146009) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L236)):*
Done.

---

*[components/script/dom/webglrenderingcontext.rs, line 285 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBhecpy_GPJ5_YZMZT:-KFfBCfjiJL5PCz5HdBN:-499146009) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L285)):*
Done.

---

*[components/script/dom/webglrenderingcontext.rs, line 290 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFBhi1ifK_xuULi_wjx:-KFfBCIcd3OJqydCGAyu:-499146009) ([raw file](https://github.com/servo/servo/blob/dc0321661bb55c21e7b20f855d5397354310a824/components/script/dom/webglrenderingcontext.rs#L290)):*
Done.

---

*[components/script/dom/webglrenderingcontext.rs, line 1610 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFf3qu_FPR5lF4XXYeM:-KFfBFW3REDe27ALEq5L:-1855566631) ([raw file](https://github.com/servo/servo/blob/50964a060fd9bd0f8f863ca95941b06136bf7076/components/script/dom/webglrenderingcontext.rs#L1610)):*
Humm... I partially agree with that, on one hand, one might argue for performance in WebGL-related code.

On the other hand, the perf impact of this would be almost negligible if we take into account IPC roundtrips, so I agree it could be worth it.

I can't dive into it right now, so I'll file the issue for now and leave a comment here.

---

*[components/script/dom/webglrenderingcontext.rs, line 1649 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFf4Pa_Jk7f6PbNnOIC:-KFfBsvNZh6eaVWYCdG5:-551648318) ([raw file](https://github.com/servo/servo/blob/50964a060fd9bd0f8f863ca95941b06136bf7076/components/script/dom/webglrenderingcontext.rs#L1649)):*
Done (also changed above)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10443#-:-KFfC7qSiu1LaQ5EW0PS:-1139784193)*

**Comment by emilio** [comment]
I think I got them all!

I'm going to add details to the issue so I don't forget about it, I think in general it can be a big win for a relatively small performance cost.

@bors-servo: try

**Comment by jdm** [comment]
Almost there!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 4 of 5 files at r6, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 214 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFokDFAVtEY4Gf7gu2z:-KFokDFBqSDxuDOE4VL2:1494752153) ([raw file](https://github.com/servo/servo/blob/1ad7f73caf3965621238cceebb19fe3a8203ed8f/components/script/dom/webglrenderingcontext.rs#L214)):*
"uniform type is compatible with the uniform type"?

---

*[components/script/dom/webglrenderingcontext.rs, line 326 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFokSPhsqf4eScpwOuu:-KFokSPiD-GutwafQlio:1177112441) ([raw file](https://github.com/servo/servo/blob/1ad7f73caf3965621238cceebb19fe3a8203ed8f/components/script/dom/webglrenderingcontext.rs#L326)):*
"and the texture and the texture"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10443#-:-KFolGWl6jyagLcnsgv3:1573484854)*

**Comment by emilio** [comment]
Addressed the review comments, also I addressed some bugs I found on the tests that were uncovered by this PR (basically the initialisation couldn't run since it relies on texImage2D).

Some of the tests are still relying on `readPixels`, so I'm going to see how a try run goes.

@bors-servo: try

---

Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/webglrenderingcontext.rs, line 214 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFokDFAVtEY4Gf7gu2z:-KFovh5-vnro0qyd8yzx:1298427805) ([raw file](https://github.com/servo/servo/blob/1ad7f73caf3965621238cceebb19fe3a8203ed8f/components/script/dom/webglrenderingcontext.rs#L214)):*
Oh, I don't know how to english, dammit.

Done

---

*[components/script/dom/webglrenderingcontext.rs, line 326 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10443#-KFokSPhsqf4eScpwOuu:-KFow-LJ7mvvRyyIi_TC:-499146009) ([raw file](https://github.com/servo/servo/blob/1ad7f73caf3965621238cceebb19fe3a8203ed8f/components/script/dom/webglrenderingcontext.rs#L326)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10443#-:-KFow13fgGjFmrARH4MQ:2136849529)*

**Comment by emilio** [comment]
Updated test expectations for tests that now run. `texImage2D` used in the setup made the `successfullyParsed` variable not being resetted, and thus the test unfortunately passed.

@bors-servo: try

**Comment by jdm** [comment]
Not sure what happened to the homu results, but the waterfall shows only known intermittent test failures.

**Comment by emilio** [comment]
@jdm: Does it look good to you then?

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 1 of 2 files at r9, 1 of 1 files at r10, 5 of 5 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10443#-:-KFz98UsnZzA8drcO2eW:-317921516)*

**Pull request merged**
