### PR TITLE
Add style check and test for else braces

### LINKED ISSUE #12234: Automatically report "else {" that is not on the same line as the previous }
Our style guide says that `} else {` is preferred over
```rust
}
else {
```
We should add a check to `regex_rules` in `tidy.py` that looks for the regex `^\s*else {` (ie. a line that starts with optional whitespace followed by `else {`).

Code: `python/tidy/serv_tidy/tidy.py`
Test: `./mach test-tidy --self-test` (add a new test to `rust_tidy.rs` and `test_tidy.py`)

### PR DESCRIPTION
**Pull request by TravisDean**
Added a regex check to enforce project style guidelines. Added unit check. Catches:

```
}
else {
```

when it should be
`} else {`

---

- [ ] `./mach build -d` does not report any errors (no core files changed)
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12234 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12243)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
Looks good! Now that this lint is in, there are some places in code that need to be updated so that this check passes.
```
./components/compositing/compositor.rs:2265: else braces should be on the same line
./components/gfx/paint_context.rs:1792: else braces should be on the same line
./components/net_traits/image/base.rs:89: else braces should be on the same line
./components/script/webdriver_handlers.rs:378: else braces should be on the same line
./components/script/dom/htmlmediaelement.rs:138: else braces should be on the same line
./components/script/dom/xmlhttprequest.rs:1133: else braces should be on the same line
./components/script/dom/xmlhttprequest.rs:1147: else braces should be on the same line
```

**Comment by TravisDean** [comment]
Should I do that as a new PR?

**Comment by ConnorGBrewster** [comment]
@TravisDean add it to this PR, as without it this PR won't pass our CI infra and cannot be merged.

**Comment by TravisDean** [comment]
I wasn't sure of the best way to fix components/net_traits/image/base.rs:89 or components/gfx/paint_context.rs:1792, so tell me if it should be done another way.

**Comment by ConnorGBrewster** [comment]
Almost there! Just a couple of nits.
After the nits, can you squash these commits, so that we don't have a commit that doesn't pass tidy.
-S-awaiting-review +S-needs-code-changes +S-needs-squash 

---

Reviewed 3 of 3 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/gfx/paint_context.rs, line 1791 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12243#-KLrzfRTQpEgB29UHczy:-KLrzfRU797FFRV-xCvb:-144939018) ([raw file](https://github.com/servo/servo/blob/2f12da34ca54681cf94ddfdbca8bee400300281d/components/gfx/paint_context.rs#L1791)):*
> ```Rust
>             mAlpha: 1f64 as AzFloat,
>             mCompositionOp: CompositionOp::Over as u8,
>             mAntialiasMode: match antialias { true => AntialiasMode::Subpixel as u8,
> ```

Lets revert this and just expand the if/else to a couple more lines.

---

*[components/script/dom/htmlmediaelement.rs, line 136 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12243#-KLrzz0OG33HsiJLIjZE:-KLrzz0P8Souyu5c9lwW:1302818618) ([raw file](https://github.com/servo/servo/blob/2f12da34ca54681cf94ddfdbca8bee400300281d/components/script/dom/htmlmediaelement.rs#L136)):*
> ```Rust
>             // Step 5
>             elem.fire_simple_event("error");
>         } else { // => "If the media data cannot be fetched at all..."
> ```

Move this down 1 line so it has its own line.

---

*[components/script/dom/xmlhttprequest.rs, line 1131 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12243#-KLs-7NjVg1r-cSjnWjY:-KLs-7NjVg1r-cSjnWjZ:907665386) ([raw file](https://github.com/servo/servo/blob/2f12da34ca54681cf94ddfdbca8bee400300281d/components/script/dom/xmlhttprequest.rs#L1131)):*
> ```Rust
>                 if self.response_type.get() == XMLHttpRequestResponseType::_empty {
>                     return None;
>                 } else { // Step 6
> ```

Same as above, move this down 1 line into the else branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12243#-:-KLs-S91BFf3dG2Hf7Q2:455053477)*

**Comment by TravisDean** [comment]
Hopefully this is correct. I had to force push to get the squash to be accepted.

**Comment by ConnorGBrewster** [comment]
Looks good! Thank you for doing this!
@bors-servo r+

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12243#-:-KLs5I2f78wVS7W4OvjV:1503800522)*

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * infra?

**Pull request merged**
