### PR TITLE
Change the path for SSL configs in browser_kwargs

### LINKED ISSUE #22252: Error running test-wpt on Windows
```
[vcvarsall.bat] Environment initialized for: 'x64'
 0:03.09 INFO Updating test manifest D:\Workspace\servo\tests\wpt\metadata\MANIFEST.json
 8:58.48 INFO Updating test manifest D:\Workspace\servo\tests\wpt\mozilla\meta\MANIFEST.json
 9:23.93 INFO Updating test manifest D:\Workspace\servo\tests\wpt\webgl\meta\MANIFEST.json
10:30.65 INFO Using 8 client processes
10:33.95 SUITE_START: web-platform-test - running 1 tests
10:33.95 INFO Running reftest tests
10:33.99 INFO Closing logging queue
10:34.00 INFO queue closed
Error running mach:

    ['test-wpt', 'tests\\wpt\\web-platform-tests\\html\\dom\\documents\\dom-tree-accessors\\document.getElementsByName\\document.getElementsByName-liveness.html']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

TypeError: 'NoneType' object has no attribute '__getitem__'

  File "D:\Workspace\servo\python\servo\testing_commands.py", line 375, in test_wpt
    ret = self.run_test_list_or_dispatch(kwargs["test_list"], "wpt", self._test_wpt, **kwargs)
  File "D:\Workspace\servo\python\servo\testing_commands.py", line 415, in run_test_list_or_dispatch
    return correct_function(**kwargs)
  File "D:\Workspace\servo\python\servo\testing_commands.py", line 401, in _test_wpt
    return self.wptrunner(run_file, **kwargs)
  File "D:\Workspace\servo\python\servo\testing_commands.py", line 447, in wptrunner
    return run_globals["run_tests"](**kwargs)
  File "D:\Workspace\servo\tests\wpt\run.py", line 47, in run_tests
    success = wptrunner.run_tests(**kwargs)
  File "D:\Workspace\servo\tests\wpt\web-platform-tests\tools\wptrunner\wptrunner\wptrunner.py", line 226, in run_tests
    **kwargs)
  File "D:\Workspace\servo\tests\wpt\web-platform-tests\tools\wptrunner\wptrunner\browsers\servo.py", line 36, in browser_kwargs
    "ca_certificate_path": config.ssl_config["ca_cert_path"],
```

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #22252.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22253)

### CODE REVIEW

**Comment by KiChjang** [comment]
Ok, so clearly this is a platform-specific problem, and I'll need some logic to detect if the current OS is windows or not.

**Comment by jgraham** [comment]
I"m not sure what's going on here, but this is a pretty odd-looking change. If you are passing in the correct `ssl_type` then the path should be set correcty. Therefore I wonder if the config isn't set up to use `ssl_type` of `pregenerated` and that's the underlying issue?

**Comment by jdm** [comment]
I propose that we set `kwargs['ssl_type'] = 'pregenerated'` in https://github.com/servo/servo/blob/0375cbcbc0bbd2224a68f37c5ab68b380c51467f/tests/wpt/run.py#L51 and see if that works without any other changes.

**Comment by KiChjang** [comment]
Trying that without the patch applied here results in:
```
The details of the failure are as follows:

TypeError: coercing to Unicode: need string or buffer, NoneType found

  File "D:\Workspace\servo\python\servo\testing_commands.py", line 376, in test_wpt
    ret = self.run_test_list_or_dispatch(kwargs["test_list"], "wpt", self._test_wpt, **kwargs)
  File "D:\Workspace\servo\python\servo\testing_commands.py", line 416, in run_test_list_or_dispatch
    return correct_function(**kwargs)
  File "D:\Workspace\servo\python\servo\testing_commands.py", line 402, in _test_wpt
    return self.wptrunner(run_file, **kwargs)
  File "D:\Workspace\servo\python\servo\testing_commands.py", line 448, in wptrunner
    return run_globals["run_tests"](**kwargs)
  File "D:\Workspace\servo\tests\wpt\run.py", line 31, in run_tests
    set_defaults(kwargs)
  File "D:\Workspace\servo\tests\wpt\run.py", line 80, in set_defaults
    wptcommandline.check_args(kwargs)
  File "D:\Workspace\servo\tests\wpt\web-platform-tests\tools\wptrunner\wptrunner\wptcommandline.py", line 493, in check_args
    require_arg(kwargs, "ca_cert_path", lambda x:os.path.exists(x))
  File "D:\Workspace\servo\tests\wpt\web-platform-tests\tools\wptrunner\wptrunner\wptcommandline.py", line 31, in require_arg
    if name not in kwargs or not value_func(kwargs[name]):
  File "D:\Workspace\servo\tests\wpt\web-platform-tests\tools\wptrunner\wptrunner\wptcommandline.py", line 493, in <lambda>
    require_arg(kwargs, "ca_cert_path", lambda x:os.path.exists(x))
  File "C:\Python27\lib\genericpath.py", line 26, in exists
    os.stat(path)
```

i.e. the ca_cert_path is not found in kwargs.

**Comment by KiChjang** [comment]
@jdm @jgraham I think this should do the trick, please have a look and see if it's the correct fix.

**Pull request closed without merging**
