### PR TITLE
Allowed services support

### PR DESCRIPTION
**Pull request by zakorgy**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because there are no webbluetooth test api implementation yet.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11580)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, zakorgy (zakorgy) wrote…</i></summary>
> r? @jdm 
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/net_traits/bluetooth_scanfilter.rs, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11580#-KJM_jF1ZhPdzYl_hSvO:-KJM_jF2Mg8hb2_l2Ib_:1570881027) ([raw file](https://github.com/servo/servo/blob/5be785e359dcfe217a10aaf0c724faa0c4d4f1dd/components/net_traits/bluetooth_scanfilter.rs#L23)):*
> ```Rust
>     fn get_services_set(&self) -> HashSet<String> {
>         let mut set = HashSet::new();
>         self.0.iter().map(|m| set.insert(m.clone())).collect::<Vec<_>>();
> ```

This makes more sense as
```rust
for m in self.0.iter() {
    set.insert(m.clone());
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11580#-:-KJMf6VZ9G8q2GV0wM95:1458266033)*

**Comment by jdm** [comment]
Please squash, and then this can merge.

**Comment by zakorgy** [comment]
@jdm ?

**Comment by dati91** [comment]
This fail seems unrelated to this patch

**Comment by KiChjang** [comment]
@bors-servo retry
* #9087

**Pull request merged**
