### PR TITLE
Trigger WindowEvent::Resize when resizing in headless mode

### LINKED ISSUE #15621: Resize event is not fired when resizing window in headless mode
Compare:
```html
<script>
window.onresize = function() { console.log("resize event"); }
window.resizeTo(200, 200);
console.log("called resizeTo");
</script>
```
```
$ ./mach run foo.html
called resizeTo
resize event
```
```
$ ./mach run foo.html --headless
called resizeTo
```

### PR DESCRIPTION
**Pull request by alanhoff**
When resizing in headless mode a resize event is now fired

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15621 

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15818)

### CODE REVIEW

**Comment by alanhoff** [comment]
@jdm I believe this code fixes #15621, now I need some help on how I should add tests.

**Comment by jdm** [comment]
If you follow [these instructions](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests), you can add a new test in tests/wpt/mozilla/tests/mozilla using the [testharness.js](http://web-platform-tests.org/writing-tests/testharness-api.html) API (you probably want to use `async_test`).

**Comment by alanhoff** [comment]
@jdm @SimonSapin ready for review

**Comment by jdm** [comment]
We should add an assert that window.clientWidth and clientHeight equal the new dimension inside of the event handler, too.

**Comment by alanhoff** [comment]
@jdm I just submitted the tests you asked for. Everything is working correctly :-)

**Review by jdm — DISMISSED** [review]
This ends up testing that clientWidth == clientHeight, and uses a descriptive label of "200". We should use two separate uses of assert_equals instead.

**Comment by alanhoff** [comment]
@jdm oh that was some ugly mistake – by reading the examples I thought that `assert_equals` would compare equality across all `arguments`.

So, it turns out that both `clientWidth` and `clientHeight` are `undefined` and that makes me think that they're not being set at all during the window's lifecycle. Having said that I think it's a separated issue (one that I'm also interested in solving) that deserves an equally separated PR. What do you think?

Also, do you have ideias why [this build](https://travis-ci.org/servo/servo/jobs/207835074#L1446) is failing?

**Comment by jdm** [comment]
Oops, I meant innerWidth/innerHeight; clientWidth/clientHeight is a property of Element objects, not Window.

**Comment by jdm** [comment]
The travis build is failing because you have modified a test file without updating the manifest (I know, it's rather annoying). You will need to run `./mach update-manifest` every time and commit the changes to MANIFEST.json before pushing after modifying the test file.

**Comment by alanhoff** [comment]
@jdm Now it makes sense and tests are passing, thx for the tips.
Ready for review

**Comment by alanhoff** [comment]
@jdm any updates about this pr? :-)

**Comment by jdm** [comment]
Sorry, I've been on vacation. I will look at my review queue (including this PR) starting Wednesday.

**Comment by nox** [comment]
```
  ▶ TIMEOUT [expected OK] /_mozilla/mozilla/resizeTo.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  └ 3.3 (Core Profile) Mesa 12.0.1

  ▶ Unexpected subtest result in /_mozilla/mozilla/resizeTo.html:
  │ TIMEOUT [expected PASS] onresize
  └   → Test timed out
```

**Comment by alanhoff** [comment]
@jdm @nox I need guidance on what went wrong with the `homu` test and how to fix it

**Comment by KiChjang** [comment]
@alanhoff Are you able to reproduce the test failures locally on your machine?

**Comment by jdm** [comment]
Does the test pass locally with --no-pause-after-test? That flag ensures that the test is run in a headless environment.

**Comment by alanhoff** [comment]
@jdm it completes without error

```
./mach test tests/wpt/mozilla/tests/mozilla/resizeTo.html --no-pause-after-test
Running 1 tests in web-platform-tests

Ran 1 tests finished in 53.0 seconds.
  • 1 ran as expected. 0 tests skipped.

Tests completed in 57.49s
```

**Comment by alanhoff** [comment]
@KiChjang I don't know exactly the commend that the test runner used to yield that error, could you help me with that?

**Comment by jdm** [comment]
I'm not sure why the test take almost 60s for you, but when I run `./mach test tests/wpt/mozilla/tests/mozilla/resizeTo.html --no-pause-after-test` locally it takes about 5s for me. I'm really confused about why the build machines are timing out :<

**Comment by nox** [comment]
@alanhoff Do you need help with this?

**Comment by jdm** [comment]
@nox I need help figuring out why the test works locally and times out on the build machines.

**Comment by dralley** [comment]
Since Glutin is going away and the issues with this PR were never fixed, it can be closed :(

This is still a problem however, even with the Surfman + Winit PR branch, so the issue should stay open.

**Pull request closed without merging**
