### PR TITLE
More Cargo.toml updates

### PR DESCRIPTION
**Pull request by atouchet**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by SimonSapin** [comment]
@atouchet In future PRs, could you write a few words in the PR title or description about what the updates are? Thanks!

**Comment by atouchet** [comment]
Sure. This was just a continuation of some formatting changes so I didn't think it was important to add more detail.

**Comment by SimonSapin** [comment]
Stating that a PR contains only formatting changes and no meaningful change would be useful information

**Pull request merged**
