### PR TITLE
Fix for #6542 - <img> top-padding adds margin

### PR DESCRIPTION
**Pull request by dwins**
I wrote this patch that makes the test from #6542 render as expected but I am not confident it is actually the right fix.  Should the padding be included in the 'ascent' metric for images, or am I just introducing a bug that happens to offset the one I'm trying to fix?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6565)

### CODE REVIEW

**Comment by pcwalton** [comment]
Yeah, this looks like the right fix.

The test you linked to looks unrelated, however. Could you add a reftest? Thanks!

**Comment by dwins** [comment]
Ok, I added a reftest.

**Comment by pcwalton** [comment]
Thanks!

**Comment by jdm** [comment]
```
/css21_dev/html4/absolute-non-replaced-max-height-003.htm
---------------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/absolute-non-replaced-max-height-011.htm
---------------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/floats-040.htm
-------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/min-height-112.htm
-----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/min-height-111.htm
-----------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/position-absolute-002.htm
------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/top-offset-percentage-001.htm
----------------------------------------------
PASS expected FAIL [Parent]
```
Upside - you fixed a bunch of tests that used to fail!

**Comment by jdm** [comment]
All of those ini files can actually be deleted now. When there's no ini, the test is expected to pass.

**Comment by dwins** [comment]
I thought that might be the case, should have clarified before pushing. Anyway the inis are gone now.

**Pull request merged**
