### PR TITLE
Invert worker type selection logic for taskcluster.

### LINKED ISSUE #23105: Untrusted decision tasks are erroring out
```
Traceback (most recent call last):
  File "/repo/etc/taskcluster/decisionlib.py", line 265, in find_or_create
    task_id = Task.find(index_path)
  File "/repo/etc/taskcluster/decisionlib.py", line 238, in find
    task_id = SHARED.index_service.findTask(full_index_path)["taskId"]
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/index.py", line 138, in findTask
    return self._makeApiCall(self.funcinfo["findTask"], *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/client.py", line 262, in _makeApiCall
    response = self._makeHttpRequest(entry['method'], _route, payload)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/client.py", line 534, in _makeHttpRequest
    superExc=None
taskcluster.exceptions.TaskclusterRestFailure: Indexed task has expired
---
* method:     findTask
* errorCode:  ResourceNotFound
* statusCode: 404
* time:       2019-03-26T19:21:25.199Z
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "etc/taskcluster/decision_task.py", line 634, in <module>
    main(task_for=os.environ["TASK_FOR"])
  File "etc/taskcluster/decision_task.py", line 84, in main
    tidy_untrusted()
  File "etc/taskcluster/decision_task.py", line 141, in tidy_untrusted
    .with_dockerfile(dockerfile_path("build"))
  File "/repo/etc/taskcluster/decisionlib.py", line 741, in with_dockerfile
    .find_or_create("docker-image." + digest)
  File "/repo/etc/taskcluster/decisionlib.py", line 271, in find_or_create
    task_id = self.create()
  File "/repo/etc/taskcluster/decisionlib.py", line 231, in create
    SHARED.queue_service.createTask(task_id, queue_payload)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/queue.py", line 169, in createTask
    return self._makeApiCall(self.funcinfo["createTask"], *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/client.py", line 262, in _makeApiCall
    response = self._makeHttpRequest(entry['method'], _route, payload)
  File "/usr/local/lib/python3.6/dist-packages/taskcluster/client.py", line 534, in _makeHttpRequest
    superExc=None
taskcluster.exceptions.TaskclusterRestFailure: Client ID task-client/ZvbQNnmiTYOs0bPmUFJFCA/0/on/us-east-1/i-06b0ac416a60bf524/until/1553629267.092 does not have sufficient scopes and are missing the following scopes:

{
  "AnyOf": [
    {
      "AnyOf": [
        "queue:create-task:highest:aws-provisioner-v1/servo-docker-worker",
        "queue:create-task:very-high:aws-provisioner-v1/servo-docker-worker",
        "queue:create-task:high:aws-provisioner-v1/servo-docker-worker",
        "queue:create-task:medium:aws-provisioner-v1/servo-docker-worker",
        "queue:create-task:low:aws-provisioner-v1/servo-docker-worker",
        "queue:create-task:very-low:aws-provisioner-v1/servo-docker-worker",
        "queue:create-task:lowest:aws-provisioner-v1/servo-docker-worker"
      ]
    },
    {
      "AnyOf": [
        "queue:create-task:aws-provisioner-v1/servo-docker-worker",
        {
          "AllOf": [
            "queue:define-task:aws-provisioner-v1/servo-docker-worker",
            "queue:task-group-id:taskcluster-github/ZvbQNnmiTYOs0bPmUFJFCA",
            "queue:schedule-task:taskcluster-github/ZvbQNnmiTYOs0bPmUFJFCA/FpuQopmhSSega1EFJooOuw"
          ]
        }
      ]
    }
  ]
}

You have the scopes:
[
  "assume:project:servo:decision-task/base",
  "assume:project:taskcluster:mozilla-github-repository",
  "assume:repo:github.com/servo/servo:pull-request",
  "notify:email:*",
  "notify:irc-channel:*",
  "notify:irc-user:*",
  "queue:create-artifact:ZvbQNnmiTYOs0bPmUFJFCA/0",
  "queue:create-task:aws-provisioner-v1/github-worker",
  "queue:create-task:aws-provisioner-v1/github-worker-windows",
  "queue:create-task:aws-provisioner-v1/win2012r2",
  "queue:create-task:highest:aws-provisioner-v1/servo-docker-untrusted",
  "queue:reclaim-task:ZvbQNnmiTYOs0bPmUFJFCA/0",
  "queue:resolve-task:ZvbQNnmiTYOs0bPmUFJFCA/0",
  "queue:route:checks",
  "queue:route:garbage.*",
  "queue:route:index.garbage.*",
  "queue:route:notify.email.*",
  "queue:route:notify.irc-channel.*",
  "queue:route:notify.irc-user.*",
  "queue:route:statuses",
  "queue:route:tc-treeherder-staging.v2._/servo-prs.*",
  "queue:route:tc-treeherder.v2._/servo-prs.*",
  "queue:scheduler-id:taskcluster-github",
  "secrets:get:garbage/*",
  "secrets:set:garbage/*"
]

This request requires you to satisfy this scope expression:

              "AllOf": [
                "queue:define-task:aws-provisioner-v1/servo-docker-worker",
                "queue:task-group-id:taskcluster-github/ZvbQNnmiTYOs0bPmUFJFCA",
                "queue:schedule-task:taskcluster-github/ZvbQNnmiTYOs0bPmUFJFCA/FpuQopmhSSega1EFJooOuw"
              ]
            }
          ]
        }
      ]
    }
  ]
}

---
* method:     createTask
* errorCode:  InsufficientScopes
* statusCode: 403
* time:       2019-03-26T19:21:25.398Z
```

https://mozilla.logbot.info/servo/20190326#c16137186-c16137256

### PR DESCRIPTION
**Pull request by jdm**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23105
- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23106)

### CODE REVIEW

**Comment by jdm** [comment]
I'm going to see what the CI results for this are before trying to merge it.

**Comment by SimonSapin** [comment]
Sorry, I think I misspoke on IRC. Literally inverting the logic by reversing the order of the `or`’s operands doesn’t seem ideal : `self.worker_type` is never falsy, so this line is effectively `.with_worker_type(self.worker_type)`.

Maybe instead we should set `CONFIG.docker_image_buil_worker_type` to `None` for untrusted tasks (and fix the typo). That way, whenever we start testing on Android emulators on Packet.net again, we can still have that config make docker images build on EC2, leaving the more scarce worker(s) for tasks that actually need it.

**Comment by jdm** [comment]
That change does seem like an improvement over the previous attempt.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23110

**Pull request merged**
