### PR TITLE
Implement MIME sniffing

### PR DESCRIPTION
**Pull request by jdm**
This rebases and integrates #4209, removing the sniffer task (turns out it wasn't a great idea), and adds a `--sniff-mime-types` command line flag to enable sniffing for file:// and http:// resources. Tested against a random picture file on my harddrive. The actual MIME sniffing implementation can be extracted into a separate library separately.

### CODE REVIEW

**Comment by jdm** [comment]
Fixes #3144.

**Comment by jdm** [comment]
@jgraham Critic is missing.

**Comment by jdm** [comment]
@metajack Would you like to review this? I reviewed the actual sniffing implementation in the first commit, so it's just the network integration in the subsequent commits that needs reviewing.

**Comment by metajack** [comment]
@jdm Yes, I'll review.

**Comment by metajack** [comment]
Reviewed in Critic.

**Comment by jdm** [comment]
```

/XMLHttpRequest/getresponseheader-chunked-trailer.htm
-----------------------------------------------------
TIMEOUT expected FAIL XMLHttpRequest: getResponseHeader() and HTTP trailer
TIMEOUT [Parent]
/XMLHttpRequest/response-data-gzip.htm
--------------------------------------
CRASH [Parent]
/XMLHttpRequest/send-conditional.htm
------------------------------------
PASS expected FAIL XMLHttpRequest: send() - conditional requests (tag)
PASS expected FAIL XMLHttpRequest: send() - conditional requests (date)
/XMLHttpRequest/progress-events-response-data-gzip.htm
------------------------------------------------------
TIMEOUT expected FAIL XMLHttpRequest: progress events and GZIP encoding
TIMEOUT [Parent]
```

**Comment by jdm** [comment]
@bors-servo: retry
* #5207

**Pull request merged**
