### PR TITLE
Update version of `nix`, and `ron`

### PR DESCRIPTION
**Pull request by fabricedesre**
A pot-pourri of crate updates to reduce duplicates.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because no feature change

### CODE REVIEW

**Review by jdm — APPROVED** [review]
Thanks!

**Comment by sagudev** [comment]
> Quotes, if present, are stripped from cookie values when parsing.

from https://github.com/SergioBenitez/cookie-rs/blob/master/CHANGELOG.md#general-changes-and-fixes-2

And that might not be according to specs https://github.com/abarth/http-state/blob/155e45c6168e6de2eb727193010fd12e3c789185/tests/data/parser/value0003-test

**Comment by fabricedesre** [comment]
What do we want to do for the `cookie-rs` update?
- Wait to see if the maintainer answers in https://github.com/SergioBenitez/cookie-rs/issues/150 and/or https://github.com/SergioBenitez/cookie-rs/pull/141#issuecomment-1705504978
- Fork `cookie-rs` to the servo org and revert https://github.com/SergioBenitez/cookie-rs/commit/b62b4ed0c79258e33e41259b9512cb2f706ee486
- Not update cookie-rs and live with the dupe.

cc @mrobinson

**Comment by mrobinson** [comment]
It would be great to unblock this, so my suggestion is to include everything here, but the cookie upgrade. I think that cookie will only be upgradeable once we resolve the situation with quoted cookie values.

**Comment by fabricedesre** [comment]
> It would be great to unblock this, so my suggestion is to include everything here, but the cookie upgrade. I think that cookie will only be upgradeable once we resolve the situation with quoted cookie values.

done in latest forced push.

**Comment by atouchet** [comment]
cookie 0.18 is now out.

**Pull request merged**
