### PR TITLE
Update WPT test expectations for --release builds

### PR DESCRIPTION
**Pull request by mbrubeck**
r? @pcwalton or @larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6720)

### CODE REVIEW

**Comment by pcwalton** [comment]
WPT doesn't think we're in debug mode, evidently! @larsbergstrom

**Comment by mbrubeck** [comment]
Pushed a new change that fixes this.  r? @pcwalton or @larsbergstrom or @jgraham.

**Pull request merged**
