### PR TITLE
Enable debug info on release builds

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9520)

### CODE REVIEW

**Comment by jdm** [comment]
Wow:
```
  ▶ TIMEOUT [expected CRASH] /dom/nodes/CharacterData-surrogates.html
  │ 
  │ thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at '
  │ 
  │ Would split a surrogate pair in CharacterData API.
  │ If you see this in real content, please comment with the URL
  │ on https://github.com/servo/servo/issues/6873
  │ 
  │ ', /home/servo/buildbot/slave/linux-rel/build/components/script/dom/characterdata.rs:216
  │ stack backtrace:
  │    1:     0x7f041d301000 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
  │    2:     0x7f041d303f6b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
  │    3:     0x7f041d303bd6 - panicking::default_handler::h7ae2e4523ef4c187IFy
  │    4:     0x7f041d2edaac - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
  └    5:     0x7f041beec8c4 - sys_common::unwind::begin_unwind::h10912278613523307238

  ▶ TIMEOUT [expected CRASH] /html/semantics/embedded-content/the-img-element/update-the-image-data/fail-to-resolve.html
  │ 
  │ thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidIpv6Address', ../src/libcore/result.rs:746
  │ stack backtrace:
  │    1:     0x7f186ac1a000 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
  │    2:     0x7f186ac1cf6b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
  │    3:     0x7f186ac1cbd6 - panicking::default_handler::h7ae2e4523ef4c187IFy
  │    4:     0x7f186ac06aac - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
  │    5:     0x7f186ac07198 - sys_common::unwind::begin_unwind_fmt::hd62d57279546b0f2Jft
  │    6:     0x7f186ac19651 - rust_begin_unwind
  │    7:     0x7f186ac4af5f - panicking::panic_fmt::h27f7225e08792f40qYL
  └    8:     0x7f1869bb82e9 - result::unwrap_failed::h8223682987862385440

  ▶ TIMEOUT [expected CRASH] /workers/semantics/xhr/001.html
  │ 
  │ thread 'WebWorker for http://web-platform.test:8000/workers/semantics/xhr/001.html#' panicked at 'expected a Window scope', /home/servo/buildbot/slave/linux-rel/build/components/script/dom/bindings/global.rs:61
  │ stack backtrace:
  │    1:     0x7ffcb992e000 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
  │    2:     0x7ffcb9930f6b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
  │    3:     0x7ffcb9930bd6 - panicking::default_handler::h7ae2e4523ef4c187IFy
  │    4:     0x7ffcb991aaac - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
  └    5:     0x7ffcb85198c4 - sys_common::unwind::begin_unwind::h10912278613523307238

  ▶ Unexpected subtest result in /workers/semantics/xhr/001.html:
  │ TIMEOUT [expected PASS] async XMLHttpRequest in dedicated worker
  └   → Test timed out
```
So some crashes now get reported as timeouts instead with debug turned on, and those backtraces are also pretty terrible.

**Comment by Manishearth** [comment]
>   │ thread 'WebWorker for http://web-platform.test:8000/workers/semantics/xhr/001.html#' panicked at 'expected a Window scope', /home/servo/buildbot/slave/linux-rel/build/components/script/dom/bindings/global.rs:61

This is because our `responseXML` impl calls `global.as_window()`, which will crash in a worker. However, since `responseXML` returns a `Document` (we can't have that in a worker), and since the test expects it to be `null`, it looks like there's a spec bug here.

**Comment by jdm** [comment]
@Manishearth Sure, that's not a new error - #8931

**Comment by larsbergstrom** [comment]
Should I give this another try, now that some of the XML-in-worker stuff is fixed?

**Comment by jdm** [comment]
I don't expect any change in behaviour - the previous run showed that for some reason wptrunner starts reporting crashes as timeouts when we use a debug build, so we either need to update the expected results or make wptrunner stop doing that.

**Comment by larsbergstrom** [comment]
Aha, thanks, then I'll just close this.

**Pull request closed without merging**
