### PR TITLE
Android build system improvements

### PR DESCRIPTION
**Pull request by mbrubeck**
This PR adds a `mach install` command (a convenient way to run `adb install`), and does some minor code cleanup.

It also fixes parallelism in the OpenSSL build.  For [complicated reasons](http://make.mad-scientist.net/papers/jobserver-implementation/), a sub-Make will not inherit `-j` options from its parent process unless it is invoked directly from another Makefile.  This means we should run make from openssl.makefile rather than openssl.sh.

r? @larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8891)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8891)*

**Comment by mbrubeck** [comment]
```
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
```

Hmm, this is what my patch was supposed to fix.

```
../libssl.so: error: undefined reference to 'ERR_put_error'
../libssl.so: error: undefined reference to 'sk_dup'
../libssl.so: error: undefined reference to 'EVP_SignFinal'
```

Not sure what broke here.  Investigating…

**Comment by mbrubeck** [comment]
I think this broke because the `make` commands are no longer running with all the environment variables set within `openssl.sh`.

**Comment by mbrubeck** [comment]
@bors-servo r=larsbergstrom

Even after fixing some errors in my patch, it seems the OpenSSL build system is simply broken when running with -j higher than 1.  I reverted my change to the OpenSSL build, and am landing the other three changes.

**Pull request merged**
