### PR TITLE
Fixes #8154 Convert match to `if let` in handle_window_event 

### LINKED ISSUE #8154: Convert match to `if let` in handle_window_event
We match on `Window::glutin_key_to_script_key` but only care about an Ok result. This means we can rewrite it as an `if let` statement instead.

Code: ports/glutin/window.rs

### PR DESCRIPTION
**Pull request by A-deLuna**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8161)

### CODE REVIEW

**Comment by jdm** [comment]
Looks great! In future, commit messages that describe the change ("Convert a match to an `if let`. Resolves #8154") are generally appreciated.

**Comment by A-deLuna** [comment]
Noted, will do that the next time. Thanks for the feedback.

**Pull request merged**
