### PR TITLE
Fix formatting for variable in doc-comment within codegen

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8059)

### CODE REVIEW

**Comment by frewsxcv** [comment]
screen shot 2015-10-17 at 2 19 13 pm

**Comment by frewsxcv** [comment]
Disclaimer: I haven't tested this because I can't generate the docs for some reason and I don't feel like debugging why it's not working

**Comment by jdm** [comment]
@bors-servo: r+
Good find!

**Comment by frewsxcv** [comment]
@jdm On second glance at this, those named parameters in that I am fixing here are all `name`. That's probably wrong, right?

**Comment by frewsxcv** [comment]
Should the first instance of `%(name)s` be `%(derivedTrait)s`?

**Comment by jdm** [comment]
I think the PR is fine as it is.

**Pull request merged**
