### PR TITLE
Embedding: revenge of cargo

### PR DESCRIPTION
**Pull request by zmike**
Adds a bunch more embedding interfaces/callbacks/functionality

@larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6175)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- components/compositing/compositor.rs @ r5, r13, r14, r21
- components/compositing/compositor_task.rs @ r13, r14
- components/compositing/constellation.rs @ r6, r13, r23
- components/compositing/headless.rs @ r14
- components/compositing/windowing.rs @ r14, r16
- components/msg/constellation_msg.rs @ r14
- components/net/lib.rs @ r16
- components/net/net_error_list.rs @ r16
- components/script/script_task.rs @ r14
- components/servo/lib.rs @ r24
- components/util/opts.rs @ r24
- ports/cef/browser.rs @ r8, r19, r20, r25, r26
- ports/cef/browser_host.rs @ r9, r10, r11
- ports/cef/Cargo.lock @ r16
- ports/cef/core.rs @ r3, r20, r24
- ports/cef/eutil.rs @ r2
- ports/cef/frame.rs @ r25
- ports/cef/interfaces/cef_browser_process_handler.rs @ r1
- ports/cef/lib.rs @ r4
- ports/cef/types.rs @ r17
- ports/cef/window.rs @ r3, r7, r8, r12, r14, r15, r16, r18, r22
- ports/cef/wrappers.rs @ r3
- ports/glutin/Cargo.toml @ r16
- ports/glutin/lib.rs @ r16
- ports/glutin/window.rs @ r14, r16
- ports/gonk/src/main.rs @ r16
- ports/gonk/src/window.rs @ r14, r16

---

<sup>**[components/compositing/constellation.rs, line 687 \[r14\]](https://reviewable.io:443/reviews/servo/servo/6175#-JqLJvcnIqGxuh508sEe)** ([raw file](https://github.com/servo/servo/blob/b2cae5492e25e0c805cd8c725c160fbcdd224169/components/compositing/constellation.rs#L687)):</sup>
You can just say something like `!self.mut_frame(frame_id).next.is_empty()` instead of the `if` expression for these two.

---

<sup>**[components/net/net_error_list.rs, line 3 \[r16\]](https://reviewable.io:443/reviews/servo/servo/6175#-JqLKhVJFKMR68tEuK6X)** ([raw file](https://github.com/servo/servo/blob/ace596828c93f5b3c153d0392c84fdedb0496b1f/components/net/net_error_list.rs#L3)):</sup>
Is this cool to just relicense like this? How was this file generated / created?

---

<sup>**[ports/cef/window.rs, line 369 \[r4\]](https://reviewable.io:443/reviews/servo/servo/6175#-JqLHR5yQJQ-W-TauCJy)** ([raw file](https://github.com/servo/servo/blob/efa59882eebc626a4cf128a63cd38c964d198e61/ports/cef/window.rs#L369)):</sup>
The only difference I can see between these two blocks of code is whether you are using an empty vector or the `utf16_chars.as_slice()` value. Could this code be refactored to avoid all the duplication?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6175)

**Comment by larsbergstrom** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- components/compositing/constellation.rs @ r27
- components/net/net_error_list.rs @ r27
- components/servo/Cargo.lock @ r27
- ports/cef/interfaces/cef_browser.rs @ r27
- ports/cef/interfaces/cef_render_handler.rs @ r27
- ports/cef/macros.rs @ r27
- ports/cef/render_handler.rs @ r27
- ports/cef/window.rs @ r27
- ports/gonk/Cargo.lock @ r27

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6175)

**Comment by zmike** [comment]
IT BEGINS AGAIN!!!!

**Comment by larsbergstrom** [comment]
Review status: 25 of 26 files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- components/script/script_task.rs @ r28
- ports/glutin/window.rs @ r28

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6175)

**Pull request merged**
