### PR TITLE
Implement CSS Device Adaption Level 1

### PR DESCRIPTION
**Pull request by luniv**
Spec: http://dev.w3.org/csswg/css-device-adapt/

Currently, the actual viewport is used by the layout task as part of the reflow, and the compositor uses the zoom constraints. I'm not sure if anywhere else currently needs access to the constraints (i.e. there's no CSSOM as far as I can tell).

I did not implement sections 9 (viewport <META>) or 10 (handling 'auto' for 'zoom').

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5361)

### CODE REVIEW

**Comment by metajack** [comment]
Assigning to @mbrubeck.

**Comment by mbrubeck** [comment]
I can review this, but I'd also like feedback from @SimonSapin on the `FromCss` trait.

**Comment by mbrubeck** [comment]
Sorry for taking so long to review this.  The code looks great!  I left a handful of comments in Critic.  Also, this will need to be rebased, sorry.

**Comment by mbrubeck** [comment]
My review is complete.  This all looks good to me, but I'm still hoping that @SimonSapin can take a quick look at the code, especially for any stylistic or architectural issues.

**Comment by metajack** [comment]
Reassigning to @SimonSapin while we wait for his feedback.

**Comment by luniv** [comment]
Should I squash the various fix-up commits now then?

**Comment by jdm** [comment]
That will break the Critic tool; best to leave that until after the review is complete.

**Comment by luniv** [comment]
Re-based to take in account #5553 (CSS rule iterators)

**Comment by SimonSapin** [comment]
I’ve filed some minor issues on Critic.

**Comment by SimonSapin** [comment]
r=me on `components/style` changes with these issues addressed.

**Comment by luniv** [comment]
I've completed my changes based on @SimonSapin's critic comments:
* Used the css_keyword_enum! macro
* Removed the FromCss trait
* Renamed NumberOrPercentageOrAuto to Zoom and moved it to viewport.rs
* Created an explicit ordering fn for cascading precedence (and reverted changes to Origin)
* etc...

However, since I've re-based and squashed everything, I'm pretty sure Critic is going to be very confused. Should I just push anyway?

**Comment by SimonSapin** [comment]
*Sigh*. Was is necessary to rebase and squash?

Anyway, if it’s done just push it and I’ll try to track issues manually.

**Comment by luniv** [comment]
Sorry. I had forgotten about Critic until after I had done the squashing :(

**Comment by SimonSapin** [comment]
Reviewed files:
- components/style/lib.rs @ r1
- components/style/parser.rs @ r1
- components/style/selector_matching.rs @ r3
- components/style/stylesheets.rs @ r5
- components/style/values.rs @ r4
- components/style/viewport.rs @ r2

---

<sup>**[components/style/viewport.rs, line 20 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5361#-JoTikphNQysn6xoQYp6)** ([raw file](https://github.com/servo/servo/blob/a46ba99aeae8f1ae5a56c9ebf94ef390626720d8/components/style/viewport.rs#L20)):</sup>
Please add a comment here: `FIXME: replace this with std::intrinsics::discriminant_value after the Rust upgrade`.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5361)

**Comment by luniv** [comment]
<sup>**[components/style/viewport.rs, line 20 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5361#-JoTikphNQysn6xoQYp6)** ([raw file](https://github.com/servo/servo/blob/a46ba99aeae8f1ae5a56c9ebf94ef390626720d8/components/style/viewport.rs#L20)):</sup>
I'm assuming you meant on the ViewportDescriptorKind enum below?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5361)

**Comment by SimonSapin** [comment]
<sup>**[components/style/viewport.rs, line 20 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5361#-JoTikphNQysn6xoQYp6)** ([raw file](https://github.com/servo/servo/blob/a46ba99aeae8f1ae5a56c9ebf94ef390626720d8/components/style/viewport.rs#L20)):</sup>
Ah, yes, I put this comment in the wrong place, sorry. When we upgrade to a Rust that has it, use `discriminant_value` on `ViewportDescriptor`instead of the `kind()` method, and use the returned `u32` instead of `ViewportDescriptorKind`.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5361)

**Comment by SimonSapin** [comment]
@mbrubeck Looks good to me in `components/style`. Was there anything else?

**Comment by mbrubeck** [comment]
Nope!  Let's get this landed right after the Rust update. Thank you @luniv for sticking with this through a much longer-than-usual review process!  I hope the Rust update doesn't cause too many more merge conflicts to resolve.

**Comment by SimonSapin** [comment]
```
/Users/servo/buildbot/slave/mac2/build/components/compositing/compositor.rs:988:13: 988:28 error: unresolved import `std::num::Float`. There is no `Float` in `std::num`
/Users/servo/buildbot/slave/mac2/build/components/compositing/compositor.rs:988         use std::num::Float;
                                                                                            ^~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `compositing`.
```

Looks like this needs some more changes beyond rebase conflicts to build with the Rust upgrade, sorry!

**Comment by SimonSapin** [comment]
@luniv You may want to comment on the PR when pushing changes, we don’t get notified otherwise!

**Comment by jdm** [comment]
```
failures:
    iframe/hide_layers1.html == iframe/hide_layers_ref.html
    viewport_rule.html == viewport_rule_ref.html
```
hide_layers1.html is #5950, but the other is new.

**Comment by luniv** [comment]
@SimonSapin Oh OK, thanks for the heads up.

Looks like the actual HTML files for the ref test got lost in the shuffle. I've added them back (and moved adding the ref test to a separate commit)

**Comment by mbrubeck** [comment]
Reviewed files:
- tests/ref/viewport_rule.html @ r8
- tests/ref/viewport_rule_ref.html @ r8

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5361)

**Pull request merged**
