### PR TITLE
Shut down the media stack when shutting down the constellation

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19225)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo try

This looks like it does nothing, but thanks to https://github.com/servo/gecko-media/issues/69 it actually does.

**Comment by nox** [comment]
Linking fails with:

```
  = note: /home/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/0299b45/src/top.rs:302: error: undefined reference to 'GeckoMedia_Initialize'
          /home/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/0299b45/src/top.rs:310: error: undefined reference to 'GeckoMedia_Shutdown'
          /home/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/0299b45/src/top.rs:323: error: undefined reference to 'GeckoMedia_ProcessEvents'
          /home/servo/.cargo/git/checkouts/gecko-media-6bedb392a81eb7cf/0299b45/src/top.rs:316: error: undefined reference to 'GeckoMedia_CanPlayType'
```

I have no idea why.

**Comment by nox** [comment]
At least, it's consistent and failed on *all* platforms. Could it be a Servo-specific argument passed to cargo, rustc or the linker that makes the operation fail?

**Comment by nox** [comment]
I misread, it only fails on Linux.

**Comment by jdm** [comment]
While it's broken on linux, this also introduced a new source of intermittent failure in tests on macOS:
```
  ▶ TIMEOUT [expected PASS] /_mozilla/css/table_caption_top_a.html
  │ 
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ VMware, Inc.
  │ softpipe
  │ 3.3 (Core Profile) Mesa 17.3.0-devel
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ mozilla::detail::MutexImpl::~MutexImpl: pthread_mutex_destroy failed: Resource busy
  │ thread panicked while processing panic. aborting.
  └ thread panicked while processing panic. aborting.
```

**Comment by nox** [comment]
Cfg-gating too hard for me.

@bors-servo try

**Comment by nox** [comment]
> thread panicked while processing panic. aborting.

Not a very useful message, but at least there are no linking issues anymore. I'll try to catch panics in gecko-media and see what happens.

**Comment by nox** [comment]
@jdm r?

**Pull request merged**
