### PR TITLE
Upgrade to Spidermonkey 39 (rebased)

### PR DESCRIPTION
**Pull request by michaelwu**
This is https://github.com/servo/servo/pull/6150 but I'm afraid of finding out what reviewable will do when there's such a big rebase. I'll force push back to that PR/branch once we're ready.

Wpt passes on OSX and Linux here. The commit at "Store proto list in an Array object" and after are all the new changes I made to make tests pass.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6374)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Reviewed on critic

**Comment by michaelwu** [comment]
I have this rebased, but haven't pushed the rebase because of critic.

**Comment by michaelwu** [comment]
I merged a bunch of reviewed things together and pushed them to #6150 . The only remaining item left is addressed in the latest commit https://github.com/servo/servo/commit/4124e88d356fa9915ea410b8c14c9e3b5fe9b399 .

**Comment by michaelwu** [comment]
https://github.com/servo/servo/pull/6150 landed.

**Pull request closed without merging**
