### PR TITLE
Upgrade to rustc 1.2.0-nightly (6e7fcc44a 2015-06-13)

### PR DESCRIPTION
**Pull request by Manishearth**
See #6376

r? @Ms2ger

Snaps don't exist yet, putting up the @larsbergstrom signal. The snap need not exactly match this commit, anything in the vicinity, or just master, should work really. (yay stability)

There's no particular reason behind this rustup except that I want to keep Servo running on almost-master as much as possible.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6377)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Review status: 8 of 12 files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/layout/animation.rs @ r3
- components/layout/inline.rs @ r3
- components/plugins/lib.rs @ r2
- components/plugins/lints/str_to_string.rs @ r2
- components/plugins/lints/unrooted_must_root.rs @ r2
- components/plugins/utils.rs @ r2
- components/script/dom/element.rs @ r3
- components/style/properties.mako.rs @ r3

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6377)

**Comment by larsbergstrom** [comment]
@Manishearth Snapshots are online.

**Comment by SimonSapin** [comment]
@bors-servo retry

```
/dom/nodes/Document-createElement-namespace.html
------------------------------------------------
TIMEOUT expected CRASH [Parent]

**Pull request merged**
