### PR TITLE
remove ScriptListener

### PR DESCRIPTION
**Pull request by vectorijk**
Fix issue #7175 and for code review

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7191)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-answer 

Thank you for your PR. I have one question below.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/script_task.rs, line 1289 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7191#-JwbqJUd4rHmrMS6yW4U)** ([raw file](https://github.com/servo/servo/blob/9ab2083e91041fb733ccd1a1c02fd573f287dee3/components/script/script_task.rs#L1289)):</sup>
I don't understand why we need these `RefMut::map` calls.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7191)

**Comment by vectorijk** [comment]
<sup>**[components/script/script_task.rs, line 1289 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7191#-JwbqJUd4rHmrMS6yW4U)** ([raw file](https://github.com/servo/servo/blob/9ab2083e91041fb733ccd1a1c02fd573f287dee3/components/script/script_task.rs#L1289)):</sup>
cause `self.compositor` return type is `DOMRefCell<IpcSender<ScriptToCompositorMsg>>` and `self.compositor.borrow_mut()` return type is`RefMut<'_, IpcSender<ScriptToCompositorMsg>>`.  So I use `RefMut::map` to get `IpcSender<T>`. Do you have better way to get it?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7191)

**Comment by jdm** [comment]
We can just dereference `RefMut<T>` via * to get `&mut T`.

**Comment by vectorijk** [comment]
@jdm Okay, Got it~ I might try dereference `RefMut<T>` via `*` before. But I gave up this method cause I didn't use correct parentheses. And I will revise this for code review later.

**Comment by vectorijk** [comment]
<sup>**[components/script/script_task.rs, line 1289 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7191#-JwbqJUd4rHmrMS6yW4U)** ([raw file](https://github.com/servo/servo/blob/9ab2083e91041fb733ccd1a1c02fd573f287dee3/components/script/script_task.rs#L1289)):</sup>
Okay, I changed that.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7191)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/script_task.rs, line 1289 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7191#-JwbqJUd4rHmrMS6yW4U)** ([raw file](https://github.com/servo/servo/blob/9ab2083e91041fb733ccd1a1c02fd573f287dee3/components/script/script_task.rs#L1289)):</sup>
Thanks. Could you try without the explicit dereferencing too (i.e., `self.compositor.borrow_mut().send(ScriptToCompositorMsg::Exit).unwrap();`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7191)

**Comment by vectorijk** [comment]
<sup>**[components/script/script_task.rs, line 1289 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7191#-JwbqJUd4rHmrMS6yW4U)** ([raw file](https://github.com/servo/servo/blob/9ab2083e91041fb733ccd1a1c02fd573f287dee3/components/script/script_task.rs#L1289)):</sup>
@Ms2ger Sure.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7191)

**Comment by vectorijk** [comment]
@Ms2ger @jdm rebased it.

**Comment by Ms2ger** [comment]
Thank you!

@bors-servo r+

**Pull request merged**
