### PR TITLE
Stop using position_elem.

### PR DESCRIPTION
**Pull request by Ms2ger**
It is unstable and not really better than the stable alternative.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6499)

### CODE REVIEW

**Comment by nox** [comment]
```
/home/servo/buildbot/slave/gonk/build/components/script/dom/eventtarget.rs:336:38: 336:46 error: mismatched types:
 expected `usize`,
    found `&dom::eventtarget::EventListenerEntry`
```

**Comment by Ms2ger** [comment]
I swear I built this <.<

**Comment by Ms2ger** [comment]
Fixed

**Pull request merged**
