### PR TITLE
Support cloning steps for textarea/input 

### LINKED ISSUE #13282: Support cloning steps for textarea/input
https://github.com/whatwg/html/pull/1784

### PR DESCRIPTION
**Pull request by tigercosmos**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13282 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21015)

### CODE REVIEW

**Comment by tigercosmos** [comment]
```
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/dom/nodes/ParentNode-querySelector-All-xht.xht", "line": 63338, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/dom/nodes/Element-webkitMatchesSelector.html", "line": 63930, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/dom/nodes/ParentNode-querySelector-All.html", "line": 64327, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/dom/nodes/Element-matches.html", "line": 137064, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/html/semantics/forms/the-textarea-element/cloning-steps.html", "line": 139499, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/dom/nodes/Node-cloneNode.html", "line": 154566, "action": "test_result", "expected": "OK"}
```

**Comment by jdm** [comment]
Presumably it doesn't like calling `textinput.borrow()` while `textinput.borrow_mut()` is still active :)

**Comment by tigercosmos** [comment]
r? @jdm 
`the-textarea-element/cloning-steps.html` could be passed now.

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by tigercosmos** [comment]
Waiting for the remain tests. This timeout might not caused by this PR.
```
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/CSS2/box-display/delete-inline-in-blocks-beginning-001.xht", "line": 13849, "action": "test_result", "expected": "PASS"}
```

**Comment by jdm** [comment]
I have a retry lined up, since that's #13480.

**Comment by jdm** [comment]
@bors-servo retry
* #13480

**Pull request merged**
