### PR TITLE
Bump itertools, image, flate2 and caseless

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20143)

### CODE REVIEW

**Review by nox — CHANGES_REQUESTED** [review]

**Comment by jdm** [comment]
And test-unit fails:
```
error[E0599]: no associated item named `Default` found for type `flate2::Compression` in the current scope
   --> components/net/tests/http_loader.rs:397:53
    |
397 |         let mut e = DeflateEncoder::new(Vec::new(), Compression::Default);
    |                                                     ^^^^^^^^^^^^^^^^^^^^ associated item not found in `flate2::Compression`
error[E0599]: no associated item named `Default` found for type `flate2::Compression` in the current scope
   --> components/net/tests/http_loader.rs:427:48
    |
427 |         let mut e = GzEncoder::new(Vec::new(), Compression::Default);
    |                                                ^^^^^^^^^^^^^^^^^^^^ associated item not found in `flate2::Compression`
error: aborting due to 2 previous errors
error: Could not compile `net`.
```

**Comment by Eijebong** [comment]
Everything should be ok now

**Review by nox — APPROVED** [review]

**Pull request merged**
