### PR TITLE
Replace IPC channel with GenericChannel in Bluetooth

### LINKED ISSUE #32411: [bluetooth] Replace IPC channel with GenericChannel
**Describe the new feature:**
With #32339, Servo now has a [generic channel](https://github.com/servo/servo/blob/main/components/shared/base/generic_channel.rs) that can select different channel implementation during runtime. This can help servo to use ipc channel if it's in multiprocess mode, and crossbeam channel if not.

There are lost of places that `ipc::channel` is used. Let's start with Bluetooth crate first since it only has two calls:

- [ ] Replace [`impl BluetoothThreadFactory for IpcSender<BluetoothRequest>`](https://github.com/servo/servo/blob/main/components/bluetooth/lib.rs#L76) with `impl BluetoothThreadFactory for GenericSender<BluetoothRequest>` instead
- [ ] Replace [`GetSelectedBluetoothDevice(Vec<String>, IpcSender<Option<String>>)`](https://github.com/servo/servo/blob/main/components/shared/embedder/lib.rs#L192) with `GetSelectedBluetoothDevice(Vec<String>, GenericSender<Option<String>>)`

Feel free to take one of them above and open the PRs. Or if you are interested in more other crates, open more issues like this. I'll also open some more in the future.

### PR DESCRIPTION
**Pull request by lwz23**
This PR replaces the IPC channel with `GenericChannel` in the Bluetooth component, as requested in issue #32411. 

---
Fixes #32411

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #32411

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because they involve internal channel replacement and existing tests already cover the affected areas.

### CODE REVIEW

**Review by mrobinson — COMMENTED** [review]
I have some doubts about this one. I'm not sure it is super useful to obscure whether or not the channel goes across the process boundary. It is really useful to know that, for example, an IPC channel is being used and has a much higher overhead.

**Comment by wusyong** [comment]
@lwz23 sorry for the late reply. We have a similar PR in #32416 and we decided it's probably not useful to add this.

**Comment by lwz23** [comment]
@wusyong Ok, I also see this PR. And it says "This PR only fix first half of the issue. Perhaps the title should be replace IPC channel with generic channel in BluetoothManager." so I thought I complete the whole two tasks. If it can't be merged it doesn't matter, I just want to be familar with this project and try other more complex task :)

**Comment by lwz23** [comment]
I've also noticed that IPC channels are used in modules other than bluetooth. Is there a need to replace this with generic channel and release PR?

**Comment by mrobinson** [comment]
> I've also noticed that IPC channels are used in modules other than bluetooth. Is there a need to replace this with generic channel and release PR?

For now, if I understand correctly, the plan is to use the `GenericChannel` when a piece of code communicates with both IPC channels and crossbeam channels.

**Pull request closed without merging**
