### PR TITLE
Update heartbeats-simple to 0.3.0

### PR DESCRIPTION
**Pull request by connorimes**
Updated heartbeats-simple dependency for native changes:
-Collapse libraries into one.
-Remove overriding of some default CMake behavior.
-Windows compatibility with compiler flags, locking, and sleeping in example (thanks Jack Moffitt and Vladimir Vukicevic).

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it's just a dependency update

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11785)

### CODE REVIEW

**Comment by metajack** [comment]
r=me but I'm pretty sure this needs more Cargo.lock changes.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11785#-:-KKi_YuV7rwyv40JgrYX:-287756033)*

**Comment by metajack** [comment]
As in, I would expect ports/cef/Cargo.lock to need updating as well at a minimum.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11785#-:-KKi_dK_gGORTi0HmLYJ:-1343730933)*

**Comment by connorimes** [comment]
You are correct, thank you.

**Comment by jdm** [comment]
@bors-servo: retry
* #11703

**Pull request merged**
