### PR TITLE
Implementing canvas drawImage API for HTML Canvas elements as image sour...

### PR DESCRIPTION
**Pull request by dmarcos**
...ce

### CODE REVIEW

**Comment by jdm** [comment]
Solid work, @dmarcos! It's all quite readable :)

**Comment by jdm** [comment]
You'll also need to run the WPT tests and update the test expectations; http://mxr.mozilla.org/servo/search?string=drawimage gives some idea of the existing test coverage.

**Comment by dmarcos** [comment]
@jdm I'm going to take care of the WPT tests. What do you think about landing drawImage for HTML canvas first and extend to the other SourceImage types as follow up patches?

**Comment by jdm** [comment]
I'm definitely in favour of doing it separately.

**Comment by dmarcos** [comment]
@jdm I have a problem with the WPT test where drawImage is called with the same canvas as source and destination.

```./mach run --debug http://localhost:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.self.1.html```

 Servo gets stuck when sending the message ```CanvasMsg::DrawImage```: 


https://github.com/dmarcos/servo/commit/8b8d93728f082dc980c73823d4767401283e694b#diff-73749ed78090d6d7ef64586d558e0850R223

No crash, no error message... just stuck. I can stop with the debugger at the line above but cannot go any go further and the [function ```draw_image``` that deals with the operation] (https://github.com/dmarcos/servo/commit/8b8d93728f082dc980c73823d4767401283e694b#diff-3d07e51ce90b1ea2877fb870f957a000R152) in  ```canvas_paint_task.rs``` is never called. Any idea on what's going on?

**Comment by jdm** [comment]
Yeah, the canvas task sends a message to its own event loop and then blocks on the response without returning to the event loop. That's... fun. We might need to make a separate DrawImageSelf command to deal with that special case for now.

**Comment by dmarcos** [comment]
@jdm I updated the WPT tests expectations. Everything looks good except for one test:

```./mach test tests/wpt/web-platform-tests/2dcontext/drawing-images-to-the-canvas/2d.drawImage.wrongtype.html```

It tests the error that the code generated from webidl should return. I don't know what I should do on this case.

I made a ```draw_image_self``` function to deal with the case when the source and destination images are the same canvas. When writing the method I identified some commonalities with ```put_image_data``` and ```get_image_data``` so I refactored a little bit and made them more legible. I hope I'm not getting too much out of my turf.

**Comment by dmarcos** [comment]
@jdm I addressed your review comments. Let me know if you want me to do anything else?

**Comment by dmarcos** [comment]
@jdm Do you think we should keep tests/html/test_canvas_drawimage.html? It's been useful to me to quickly check my implementation on a visual way and also a convenient way to compare with other rendering engines.

**Comment by jdm** [comment]
Yes, it's not a problem to keep it around if it's useful.

**Comment by dmarcos** [comment]
@jdm In the last commit I also broke down the original ```tests/html/test_canvas_drawimage.html``` in multiple ref tests (https://github.com/dmarcos/servo/commit/361de34b2e3c06b8948ec6c18e6b0797c1a59f15#diff-ea832de641ea257570462ec45efe782cR12)

**Comment by samlh** [comment]
Just a drive-by question:
Is it possible to get a deadlock by CanvasTask A copying from CanvasTask B and vice-versa simultaneously, or is there some form of synchronization? I suppose that some form of synchronization is needed to make sure the drawing and the copies happen in the right order from the script task's perspective, anyway, but I can't find how that is enforced currently.

**Comment by samlh** [comment]
One option: have the script task send both the copy-from and copy-to messages to the respective tasks, each containing the respective communication sender or receiver to use. I admit I don't quite understand the design here, though, so I may be missing something.

**Comment by dmarcos** [comment]
@samlh Do you have a test case in mind that you think might trigger a deadlock? I can give it a run and see what happens. Is this what you mean?

```js
ctx1.drawImage(ctx2, 0, 0);
ctx2.drawImage(ctx1, 0, 0);

**Comment by dmarcos** [comment]
I made a quick test and we effectively end up on deadlock on this case:

```js
ctx1.drawImage(ctx2, 0, 0);
ctx2.drawImage(ctx1, 0, 0);
```

**Comment by samlh** [comment]
Yup, exactly. I think if you run it in a loop, it may also make the issue more likely. Also, I wonder about:
ctx1.dostuff (x10)
ctx2.drawImage(ctx1, 0, 0)
ctx1.dostuff (x10)
I think it will currently grab an indeterminate state from ctx1, likely a bit after the drawImage call.

In general, this sounds like you need to put matching messages in both task queues simultaneously from the script task, so that things are synchronized appropriately.

**Comment by jdm** [comment]
Mmmm, good find.

**Comment by dmarcos** [comment]
@jdm I moved the message to read pixels from the source canvas  from the message handler to content. This solves the problem but I don't know if it's acceptable from the point of view of performance. It there a better way to handle this?

https://github.com/dmarcos/servo/commit/cb70ab5e28ce13011636c065e9118a79e8ec7ac8

**Comment by jdm** [comment]
I'm willing to live with it for now and file an issue about improving it.

**Comment by samlh** [comment]
I agree that your change ought to resolve the synchronization problem.

The solution space here is large, of course:
- Copy via the script task (status quo). Pros: simple. Cons: requires the script task wait for the source canvas to render.
- If you want more parallelism you could send pairs of messages, with a channel solely intended to pass the data across. That way, each canvas task can do its own thing until the destination needs the source data, at which point it can block on the source canvas task getting around to the "send" message. Pros: the script task is no longer blocked on the source canvas task. Cons: complex, may have too much overhead (creating the dedicated channel to transfer the data).
- Use one canvas task for all canvases. Pros: no overhead for copying, no synchronization needed. Cons: no parallelism, less elegant.

I have no opinion on what is ideal, but as @jdm said, a follow up issue makes a lot of sense.

**Comment by dmarcos** [comment]
Thanks @samlh 

@jdm I pushed the changes to the branch. Any other changes you would like to make this merge worth it?

**Comment by jdm** [comment]
I started on the review yesterday, but I've been distracted by some high-priority Gecko work. I promise I'll get back to it soon :)

**Comment by jdm** [comment]
@samlh: that was a helpful read; thanks!

**Comment by jdm** [comment]
Sorry, lots of new comments, but your changes are definitely moving in the right direction! I think we can still improve the clarity in a few spots.

**Comment by dmarcos** [comment]
@jdm Thanks for spending time on this! I think I addressed all your comments. Anything else besides rebasing and squashing?

**Comment by jdm** [comment]
Great job! Nothing left but those :)

**Comment by dmarcos** [comment]
@jdm Done, Rebased and squashed!

**Comment by dmarcos** [comment]
@jdm There was a missing use declaration in canvasrenderingcontext2d.rs that got lost after rebasing. I forgot to commit it. I just pushed it to the branch. I guess you have to r+ the commit again. Sorry for the inconvenience.

**Comment by jdm** [comment]
```
/html/dom/interfaces.html
-------------------------
PASS expected FAIL CanvasRenderingContext2D interface: operation createLinearGradient(double,double,double,double)
PASS expected FAIL CanvasRenderingContext2D interface: operation createRadialGradient(double,double,double,double,double,double)
```

**Comment by dmarcos** [comment]
@jdm I'm sorry! The implementation of createLinearGradient and my patch collided in several points and those 'FAIL' expectations were brought to live during rebase. I just took them out. I'll be more careful next time.

**Comment by dmarcos** [comment]
@jdm I don't understand what's going on here. I'm getting a fail (http://build.servo.org/builders/linux2/builds/1133/steps/shell_1/logs/stdio) on the test below but it runs as expected on my machine:

```./mach test-wpt tests/wpt/web-platform-tests/2dcontext/drawing-images-to-the-canvas/2d.drawImage.null.html``` 

I had updated the expectations on my commit:

https://github.com/dmarcos/servo/commit/0ec5490c6683becbbd286b6caffb18b3bdf979b8#diff-bcd1554a6d7f190640acddf9e2f0fb88R1

What should I do here?

**Comment by jdm** [comment]
The ini file is named wrong - it needs a capital I in drawImage.

**Comment by dmarcos** [comment]
@jdm Thanks! I just renamed the filed and push it to the branch. I hope this sticks

That explains it why it was running on my osx machine. The automated tests run on a linux env that is case sensitive.

**Comment by jdm** [comment]
Yep, that would do it.

**Pull request closed without merging**
