### PR TITLE
Use Url.join instead of UrlParser.base_url(...).parse (#9002)

### PR DESCRIPTION
**Pull request by magopian**
Fix issue #9002

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9019)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good, thanks!

@bors-servo r+

**Comment by magopian** [comment]
So, there's two remaining occurences of `UrlParse` in the codebase:
`components/script/dom/url.rs`
`components/script/dom/urlhelper.rs`

Not sure those should go, and if they should, not sure how to do that.

**Comment by nox** [comment]
These two can stay, they aren't just a join operation after all.

**Comment by jdm** [comment]
That is a nice readability improvement!

**Comment by magopian** [comment]
Thanks a lot for the help and the kind words, loving it. And I need to say, the whole onboarding experience with servo was a real please! :heart: :bouquet: :wine_glass:

**Pull request merged**
