### PR TITLE
Use encoding-rs instead of rust-encoding

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19073)

### CODE REVIEW

**Review by mbrubeck — APPROVED** [review]
r=mbrubeck

**Comment by SimonSapin** [comment]
Added a `to_ascii_lowercase()` call in `TextDecoder::Encoding` which matches spec, and updated some tests from expected fail to expected pass.

@bors-servo r=mbrubeck.

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /XMLHttpRequest/send-receive-utf16.htm:
  └ PASS [expected FAIL] UTF-16 with BOM, no encoding in content-type

  ▶ Unexpected subtest result in /url/toascii.window.html:
  │ FAIL [expected PASS] xn--1ug.example (using <a>)
  │   → assert_equals: expected "" but got "xn--1ug.example"
  │ 
  │ runTests/</<@http://web-platform.test:8000/url/toascii.window.js:42:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  │ test@http://web-platform.test:8000/resources/testharness.js:511:9
  │ runTests/<@http://web-platform.test:8000/url/toascii.window.js:30:7
  │ runTests@http://web-platform.test:8000/url/toascii.window.js:29:6
  │ request.onload<@http://web-platform.test:8000/url/toascii.window.js:7:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1529:17

  ▶ Unexpected subtest result in /url/toascii.window.html:
  │ FAIL [expected PASS] xn--1ug.example (using URL)
  │   → assert_throws: function "() => makeURL("url", hostTest.input)" did not throw
  │ 
  │ runTests/</<@http://web-platform.test:8000/url/toascii.window.js:39:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  │ test@http://web-platform.test:8000/resources/testharness.js:511:9
  │ runTests/<@http://web-platform.test:8000/url/toascii.window.js:30:7
  │ runTests@http://web-platform.test:8000/url/toascii.window.js:29:6
  │ request.onload<@http://web-platform.test:8000/url/toascii.window.js:7:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1529:17

  ▶ Unexpected subtest result in /url/toascii.window.html:
  │ FAIL [expected PASS] xn--1ug.example (using URL.host)
  │   → assert_equals: expected "x" but got "xn--1ug.example"
  │ FAIL [expected PASS] xn--1ug.example (using URL.hostname)
  │   → assert_equals: expected "x" but got "xn--1ug.example"
  │ FAIL [expected PASS] xn--1ug.example (using <a>.host)
  │   → assert_equals: expected "x" but got "xn--1ug.example"
  │ FAIL [expected PASS] xn--1ug.example (using <a>.hostname)
  │   → assert_equals: expected "x" but got "xn--1ug.example"
  │ 
  │ runTests/</</<@http://web-platform.test:8000/url/toascii.window.js:56:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  │ test@http://web-platform.test:8000/resources/testharness.js:511:9
  │ runTests/</<@http://web-platform.test:8000/url/toascii.window.js:50:9
  │ runTests/<@http://web-platform.test:8000/url/toascii.window.js:49:8
  │ runTests@http://web-platform.test:8000/url/toascii.window.js:29:6
  │ request.onload<@http://web-platform.test:8000/url/toascii.window.js:7:5
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1489:20
  └ Test.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1529:17

  ▶ Unexpected subtest result in /url/url-origin.html:
  └ PASS [expected FAIL] Origin parsing: <http://\u4f60\u597d\u4f60\u597d> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-origin.html:
  └ PASS [expected FAIL] Origin parsing: <http://./> against <about:blank>

  ▶ Unexpected subtest result in /url/url-origin.html:
  └ PASS [expected FAIL] Origin parsing: <http://../> against <about:blank>

  ▶ Unexpected subtest result in /url/url-origin.html:
  └ PASS [expected FAIL] Origin parsing: <ftp://%e2%98%83> against <about:blank>

  ▶ Unexpected subtest result in /url/url-origin.html:
  └ PASS [expected FAIL] Origin parsing: <https://%e2%98%83> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing: <http://./> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing: <http://../> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing: <http://[::1.2.3.4x]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/a-element-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing: <http://[::1.2.3.]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/a-element-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing: <http://[::1.2.]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/a-element-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing: <http://[::1.]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://./> against <about:blank>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://../> against <about:blank>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://[::1.2.3.4x]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://[::1.2.3.]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://[::1.2.]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://[::1.]> against <http://other.com/>

  ▶ Unexpected subtest result in /html/browsers/history/the-location-interface/location-origin-idna.sub.window.html:
  └ PASS [expected FAIL] Test that location.origin returns ASCII

  ▶ Unexpected subtest result in /url/a-element-origin-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing origin: <http://./> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-origin-xhtml.xhtml:
  └ PASS [expected FAIL] Parsing origin: <http://../> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-origin.html:
  └ PASS [expected FAIL] Parsing origin: <http://./> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element-origin.html:
  └ PASS [expected FAIL] Parsing origin: <http://../> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element.html:
  └ PASS [expected FAIL] Parsing: <http://./> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element.html:
  └ PASS [expected FAIL] Parsing: <http://../> against <about:blank>

  ▶ Unexpected subtest result in /url/a-element.html:
  └ PASS [expected FAIL] Parsing: <http://[::1.2.3.4x]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/a-element.html:
  └ PASS [expected FAIL] Parsing: <http://[::1.2.3.]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/a-element.html:
  └ PASS [expected FAIL] Parsing: <http://[::1.2.]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/a-element.html:
  └ PASS [expected FAIL] Parsing: <http://[::1.]> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <http://example.net/>.host = '[::1.2.3.4x]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <http://example.net/>.host = '[::1.2.3.4x]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <http://example.net/>.host = '[::1.2.3.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <http://example.net/>.host = '[::1.2.3.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <http://example.net/>.host = '[::1.2.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <http://example.net/>.host = '[::1.2.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <http://example.net/>.host = '[::1.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <http://example.net/>.host = '[::1.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <http://example.net/>.hostname = '[::1.2.3.4x]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <http://example.net/>.hostname = '[::1.2.3.4x]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <http://example.net/>.hostname = '[::1.2.3.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <http://example.net/>.hostname = '[::1.2.3.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <http://example.net/>.hostname = '[::1.2.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <http://example.net/>.hostname = '[::1.2.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] URL: Setting <http://example.net/>.hostname = '[::1.]'

  ▶ Unexpected subtest result in /url/url-setters.html:
  └ PASS [expected FAIL] <a>: Setting <http://example.net/>.hostname = '[::1.]'

```

**Comment by SimonSapin** [comment]
Some more expectation changes

@bors-servo r=mbrubeck

**Pull request merged**
