### PR TITLE
style: Move all the style sharing code outside matching.rs

### PR DESCRIPTION
**Pull request by emilio**
This is just a code health change. I want to move it away to keep matching.rs as
simple as possible.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16972)

### CODE REVIEW

**Comment by bholley** [comment]
@bors-servo delegate+

r=me assuming this is just moving code around. If there are actual changes let me know what they are.

**Comment by emilio** [comment]
Yeah, there are no changes, removed some arguments that predated the presence of `element` inside the `SharingStyleCandidate`.

**Comment by emilio** [comment]
@bors-servo r=bholley p=10

 * Ultra-easy to bitrot

**Pull request merged**
