### PR TITLE
Update SpiderMonkey to m-c bcf4ff0c3eef.

### PR DESCRIPTION
**Pull request by Ms2ger**
This currently breaks Servo on Android, because there are a number of interdependent changes that cannot easily land serially in a way that keeps it working throughout. We expect to fix this in the near future.

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12255)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review 

---

Reviewed 3 of 3 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/callback.rs, line 198 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12255#-KLuCTPBgHxWHywpqwVK:-KLuCTPBgHxWHywpqwVL:677194780) ([raw file](https://github.com/servo/servo/blob/0eb1b06afca84a026b1f8c9c6bb66d97ce49d82d/components/script/dom/bindings/callback.rs#L198)):*
> ```Rust
>             unsafe {
>                 let _ac = JSAutoCompartment::new(self.cx, *self.exception_compartment);
>                 // XXX JS_ReportPendingException(self.cx);
> ```

Why?

---

*[components/script/dom/bindings/error.rs, line 127 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12255#-KLuCUPnSgca_y_oA0TK:-KLuCUPnSgca_y_oA0TL:677194780) ([raw file](https://github.com/servo/servo/blob/0eb1b06afca84a026b1f8c9c6bb66d97ce49d82d/components/script/dom/bindings/error.rs#L127)):*
> ```Rust
>     if JS_IsExceptionPending(cx) {
>         let _ac = JSAutoCompartment::new(cx, obj);
>         // XXX JS_ReportPendingException(cx);
> ```

Why?

---

*[components/script/dom/bindings/interface.rs, line 154 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12255#-KLuCxmuslkrUd8Wo3uJ:-KLuCxmuslkrUd8Wo3uK:-394225251) ([raw file](https://github.com/servo/servo/blob/0eb1b06afca84a026b1f8c9c6bb66d97ce49d82d/components/script/dom/bindings/interface.rs#L154)):*
> ```Rust
> 
>     /// Create a new `NonCallbackInterfaceObjectClass` structure.
>     pub const fn new(ops: &'static ClassOps,
> ```

If you make `InterfaceConstructorBehavior` wrap a `ClassOps` instead, the only needed change is `ops: &'static InterfaceConstructorBehavior`.

---

*[components/script/dom/bindings/interface.rs, line 190 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12255#-KLuCpxzaOwfe51C8y7V:-KLuCpxzaOwfe51C8y7W:1144705148) ([raw file](https://github.com/servo/servo/blob/0eb1b06afca84a026b1f8c9c6bb66d97ce49d82d/components/script/dom/bindings/interface.rs#L190)):*
> ```Rust
>     call: JSNative,
>     construct: JSNative,
> }
> ```

Could you instead just make that wrap a `ClassOps`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12255#-:-KLuDHXw_yNl_F6GnS-H:879583689)*

**Comment by larsbergstrom** [comment]
Given that you have backed out the stlport stuff:
https://github.com/servo/mozjs/commit/8767998afaff1e953261e4146a0a228b8eee78a5

I think from looking at:
https://dxr.mozilla.org/mozilla-central/source/build/autoconf/android.m4#151-156

That what we need to do in the moz.build is:
`USE_LIBS += ['c++_static']`

BUT we might also need `c++abi unwind android_support`.

**Comment by larsbergstrom** [comment]
In theory, we can install the alternative libraries by doing:
```
build/tools/make-standalone-toolchain.sh --stl=libc++ --platform="android-18" --toolchain=arm-linux-androideabi-4.9 --install-dir=/Users/larsberg/ndk-standalone --ndk-dir=/Users/larsberg/android-ndk-r12b --arch=arm
```

And then make the following change to mozjs to pick up the other library:
```
[larsberg@larsberg mozjs]$ git diff
diff --git a/build.rs b/build.rs
index df9bcda..328d30b 100644
--- a/build.rs
+++ b/build.rs
@@ -31,6 +31,10 @@ fn main() {
         println!("cargo:rustc-link-lib=winmm");
         println!("cargo:rustc-link-lib=psapi");
     }
-    println!("cargo:rustc-link-lib=stdc++");
+    if target.contains("android") {
+        println!("cargo:rustc-link-lib=c++_static");
+    } else {
+        println!("cargo:rustc-link-lib=stdc++");
+    }
     println!("cargo:outdir={}", out_dir);
 }
```

Unfortunately, this now results in:
```
/Users/larsberg/ndk-standalone/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -landroid_support
```

It appears to be a problem because the `make_standalone_toolchain.sh` script does not properly copy all of the dependencies of the linker stub `libc++_static.a` into the proper directory.

@froydnj Suggests that we do something similar to Firefox and avoid creating a standalone directory at all, reaching straight into the NDK toolchain directories. That *does* appear to be a solution that is more likely to work (and remove an often-missed setup step from https://github.com/servo/servo/wiki/Building-for-Android !), but requires quite a bit of build system surgery. I'm working on it.

**Comment by larsbergstrom** [comment]
@froydnj I just spent the evening trying to reproduce the configure scripts reproduction of:
1) translating target triples to google-android-target triples to find gcc
2) similar hackery to get a valid `--sysroot`
And I think I have that working.

However, the `libc++_static.a` is in, e.g., `./sources/cxx-stl/llvm-libc++/libs/armeabi/libc++_static.a`, and it's not at all clear to me how to get that on the library include path. Is there some special magic I should be doing here?

**Comment by Ms2ger** [comment]
That's `$cxx_libs` in `android.m4`; not sure how to get that out of there. (Note that changing `android.m4` requires re-running `autoconf2.13` on `old-configure.in`.)

**Comment by larsbergstrom** [comment]
@Ms2ger You're right! I probably need to reproduce the behavior in:
https://dxr.mozilla.org/mozilla-central/source/build/autoconf/android.m4?q=android.m4&redirect_type=direct#139-161

Kinda annoying, as I *think* this means that I need to duplicate it in fake-ld.sh (to construct the linker line) and several separate build.rs files. Maybe I should do the detection / env var setting in the python code in mach, so that it's at least only in one place? I'm not sure there's a good solution, with various bits of build hackery scattered across a handful of build systems.

I'll probably go with the "bash my head against it until it works" solution to get the SMUP landed, but figuring out a better way to deal with Android NDK detection would be nice in general. It's already in a pretty... fragile... state.

**Comment by larsbergstrom** [comment]
In good news, I've got a build that now links against `c++_static` and properly resolves those symbols.

In bad news, since many of our other dependencies still link against `stlport`, we now have ~90 undefined symbols of the form `_ZNSt9basic_iosIcSt11char_traitsIcEE4initEPSt15basic_streambufIcS1_E`.

Hopefully, this is just a matter of rebuilding the whole tree with magically repointed include directories. WHAT COULD POSSIBLY GO WRONG? :-)

**Comment by larsbergstrom** [comment]
@froydnj Have you ever seen the following error (about a bunch of missing really basic C symbols)? I've got *most* of our native deps compiling w/ the LLVM libc++ and no standalone NDK (freetype, SM, azure, skia, openssl), but angle is still giving me some fits:

```
error: failed to run custom build command for `angle v0.1.0 (https://github.com/servo/angle?branch=servo#d0a2db05)`
Process didn't exit successfully: `/Users/larsberg/servo/target/debug/build/angle-7062634bbf237306/build-script-build` (exit code: 101)
--- stdout
arm-linux-androideabi-g++ src/glslang-c.cpp -o /Users/larsberg/servo/target/arm-linux-androideabi/debug/build/angle-7062634bbf237306/out/src/glslang-c.o -c --sysroot /Users/larsberg/android-ndk-r12b/platforms/android-18/arch-arm -I/Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include -Wall -std=gnu++11 -DANGLE_TRANSLATOR_STATIC -DANGLE_ENABLE_GLSL -DLIBGLESV2_EXPORT_H_ -DANGLE_EXPORT="" -Iinclude -Isrc -O3 -Wall -DCOMPONENT_BUILD  -fPIC

--- stderr
In file included from /Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:107:0,
                 from /Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/string:438,
                 from include/GLSLANG/ShaderLang.h:31,
                 from src/glslang-c.cpp:1:
/Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/cwctype:88:9: error: '::iswblank' has not been declared
 using ::iswblank;
         ^
In file included from /Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/string:438:0,
                 from include/GLSLANG/ShaderLang.h:31,
                 from src/glslang-c.cpp:1:
/Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:132:9: error: '::vfwscanf' has not been declared
 using ::vfwscanf;
         ^
/Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:133:9: error: '::vswscanf' has not been declared
 using ::vswscanf;
         ^
/Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:134:9: error: '::vwscanf' has not been declared
 using ::vwscanf;
         ^
/Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:150:9: error: '::wcstof' has not been declared
 using ::wcstof;
         ^
/Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:151:9: error: '::wcstold' has not been declared
 using ::wcstold;
         ^
/Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:155:9: error: '::wcstoll' has not been declared
 using ::wcstoll;
         ^
/Users/larsberg/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libcxx/include/cwchar:159:9: error: '::wcstoull' has not been declared
 using ::wcstoull;
         ^
make: *** [/Users/larsberg/servo/target/arm-linux-androideabi/debug/build/angle-7062634bbf237306/out/src/glslang-c.o] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f", "makefile.cargo",
                            &format!("-j{}" , env :: var ( "NUM_JOBS" ) .
                                     unwrap (
                                     ))]).status().unwrap().success()', /Users/larsberg/servo/.cargo/git/checkouts/angle-017278ddf8240375/servo/build.rs:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.

[Warning] Could not generate notification! Optional Python module 'pyobjc' is not installed.
Build completed in 0:03:55
```

**Comment by larsbergstrom** [comment]
The plan for now is to disable Android (https://github.com/servo/saltfs/pull/450), get this landed, and come back to it after the msvc support has also landed.

@nox @Ms2ger Please finish reviews and squash this for landing, after I get the salt change approved and deployed.

**Comment by Ms2ger** [comment]
OK, I'll wrap it up tomorrow.

**Comment by larsbergstrom** [comment]
servo/saltfs#450 has landed and been rolled out, so you should be good to go here. Thanks!

**Comment by Ms2ger** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[components/script/dom/bindings/error.rs, line 127 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12255#-KLuCUPnSgca_y_oA0TK:-KNlBlf4eA0Ite66483t:-497468049) ([raw file](https://github.com/servo/servo/blob/0eb1b06afca84a026b1f8c9c6bb66d97ce49d82d/components/script/dom/bindings/error.rs#L127)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Why?
</details>
Fixed

---

*[components/script/dom/bindings/interface.rs, line 154 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12255#-KLuCxmuslkrUd8Wo3uJ:-KNlBpGg9zEkHO1OwdBM:-1478300612) ([raw file](https://github.com/servo/servo/blob/0eb1b06afca84a026b1f8c9c6bb66d97ce49d82d/components/script/dom/bindings/interface.rs#L154)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> If you make `InterfaceConstructorBehavior` wrap a `ClassOps` instead, the only needed change is `ops: &'static InterfaceConstructorBehavior`.
</details>
Not done, because it caused a segfault. Might be worth trying to fix it after this lands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12255)*

**Comment by froydnj** [comment]
@larsbergstrom Sorry for not responding sooner!  Gmail failed to highlight your message as important. 😞 

This is what Gecko does for `-I` and `-l` flags:

http://dxr.mozilla.org/mozilla-central/source/build/autoconf/android.m4#170

It looks like your command line got truncated somehow, so I can't tell if you have all those `-I` flags, but my guess is that you're missing the `-I$NDK/android/support/include` bit somewhere.

**Pull request merged**
