### PR TITLE
Fix restyling on viewport resize.

### PR DESCRIPTION
**Pull request by emilio**
Fixes https://github.com/servo/servo/issues/12835

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12838)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo: try

Apparently the syntax:

```rust
if cfg!(whatever) {
    self.field_only_existing_if_cfg_whatever = foo;
}
```

broke with the rustup. cc @eddyb

**Comment by eddyb** [comment]
@emilio That never worked, `if false` doesn't make typeck ignore the field access.

**Comment by emilio** [comment]
FTR, yeah, @eddyb is right, and I'm stupid for misremembering having built this on release locally.

**Comment by SimonSapin** [comment]
r=me with s/red/green/ if you’ve seen the test fail

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 12 of 12 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/wpt/mozilla/tests/css/dirty_viewport.html, line 7 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12838#-KPILkrdzXzXZ_7Awy2h:-KPILkre2JGQWtco40C6:b-t1xhuw) ([raw file](https://github.com/servo/servo/blob/2767c73e185a483445a77acf6f18d07188e1e5ec/tests/wpt/mozilla/tests/css/dirty_viewport.html#L7)):*
> ```HTML
> <iframe seamless src="dirty_viewport_inner.html" width="500" height="500"></iframe>
> <script>
>   window.onload = function() {
> ```

Did this test fail without the code changes?

---

*[tests/wpt/mozilla/tests/css/dirty_viewport_ref.html, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12838#-KPILT_rF-Rnhf_hyEEn:-KPILT_stzjXh5f6BLHp:b8ee58c) ([raw file](https://github.com/servo/servo/blob/2767c73e185a483445a77acf6f18d07188e1e5ec/tests/wpt/mozilla/tests/css/dirty_viewport_ref.html#L4)):*
> ```HTML
> <style>
>   div {
>     background: red;
> ```

Nit: red is generally used to indicate a test failure. (On success, it the red is hidden/behind something else). Please change this to green.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12838#-:-KPINA5Wp4uZ8BpPXh6w:brb21ic)*

**Comment by emilio** [comment]
@bors-servo: r=SimonSapin

---

Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/mozilla/tests/css/dirty_viewport.html, line 7 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12838#-KPILkrdzXzXZ_7Awy2h:-KPJW-7HWXw1235_MjpM:b-hbztv3) ([raw file](https://github.com/servo/servo/blob/2767c73e185a483445a77acf6f18d07188e1e5ec/tests/wpt/mozilla/tests/css/dirty_viewport.html#L7)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Did this test fail without the code changes?
</details>
Yep, that's the first thing I tested, but just in case I double-checked :P

---

*[tests/wpt/mozilla/tests/css/dirty_viewport_ref.html, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12838#-KPILT_rF-Rnhf_hyEEn:-KPJW3h3R9OYiIQpvg_y:b-896fix) ([raw file](https://github.com/servo/servo/blob/2767c73e185a483445a77acf6f18d07188e1e5ec/tests/wpt/mozilla/tests/css/dirty_viewport_ref.html#L4)):*
<details><summary><i>Previously, SimonSapin (Simon Sapin) wrote…</i></summary>
> Nit: red is generally used to indicate a test failure. (On success, it the red is hidden/behind something else). Please change this to green.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12838#-:-KPJW5SPLJkrglL40302:bw9z4zb)*

**Pull request merged**
