### PR TITLE
Perf timing dom props

### PR DESCRIPTION
**Pull request by g-k**
I think this is closer to what https://github.com/servo/servo/issues/7045 describes, but it panics trying to load a page (trace: https://gist.github.com/g-k/a9911467889cdb6fdbf9) and all reftests fail.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7242)

### CODE REVIEW

**Comment by Ms2ger** [comment]
The issue is the `set_ready_state` call in `Document::new()`, which happens before we've had a chance to hook up the window.

**Comment by g-k** [comment]
Ah! That makes sense.  I removed that call and it fixed the panics, but I'm not sure where to set the loading time. Should I add a call to `set_ready_state` after all `Document::new` calls or is there a cleaner way to do that?

**Comment by Ms2ger** [comment]
I've looked at this for a bit, but the specs are a mess; I'm not quite sure what's the best approach here.

**Comment by Manishearth** [comment]
@Ms2ger updates?

**Comment by g-k** [comment]
I think this is ready for another look.

I rebased and changed the performance timing constructor to take `Root<Document>`  instead of `JS<Document>` to satisfy the unrooted_must_root lint check.

**Comment by Ms2ger** [comment]
The field should be `JS<Document>`, and the argument should be `&Document`.

**Comment by g-k** [comment]
Rebased.

**Comment by jdm** [comment]
I presume @ms2ger won't mind me stealing this to get it out of review limbo.
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 3 files at r1, 1 of 1 files at r7, 1 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[components/script/dom/document.rs, line 185 \[r9\]](https://reviewable.io:443/reviews/servo/servo/7242#-K2s1cnrsM8YPO0JvdOv)** ([raw file](https://github.com/servo/servo/blob/144a7544482f2459fd776d7b8bd16919144d31e8/components/script/dom/document.rs#L185)):</sup>
This can be http://w3c.github.io/navigation-timing/#widl-PerformanceTiming-domLoading now.


---

<sup>**[components/script/dom/document.rs, line 506 \[r9\]](https://reviewable.io:443/reviews/servo/servo/7242#-K2s2L28sVJTEExpgeK_)** ([raw file](https://github.com/servo/servo/blob/144a7544482f2459fd776d7b8bd16919144d31e8/components/script/dom/document.rs#L506)):</sup>
The spec for PerformanceTiming (which is different than PerformanceNavigationTiming), says we should be using ms since the epoch, rather than the result of performance.now(). I recommend `time::get_time().sec * 1000`.

Additionally, http://w3c.github.io/navigation-timing/#widl-PerformanceTiming-domComplete says that we need to ensure that the values are only stored once if a state is reached multiple times.


---

<sup>**[components/script/dom/performancetiming.rs, line 57 \[r9\]](https://reviewable.io:443/reviews/servo/servo/7242#-K2s4ZaNQpc0_NwoHzZO)** ([raw file](https://github.com/servo/servo/blob/144a7544482f2459fd776d7b8bd16919144d31e8/components/script/dom/performancetiming.rs#L57)):</sup>
These spec links can be updated.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7242)

**Comment by jdm** [comment]
Looks great! One last piece of cleanup and this will be ready to go. Please squash all the commits into one, too!
-S-awaiting-review +S-needs-squash 


---

Reviewed 1 of 3 files at r1, 1 of 1 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[components/script/dom/document.rs, line 518 \[r11\]](https://reviewable.io:443/reviews/servo/servo/7242#-K2vlo7PMZgdhu9OB67g)** ([raw file](https://github.com/servo/servo/blob/ee6ca427e6937d2205646bc9f168550d8f103e3c/components/script/dom/document.rs#L518)):</sup>
Let's add a `update_with_current_time(marker: &Cell<u64>)` function that does this check and updates the value, then call that from each place in these methods that duplicates this logic.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7242)

**Comment by jdm** [comment]
Only one question left about the spec link changes!
-S-awaiting-review -S-needs-squash +S-needs-code-changes 


---

Reviewed 3 of 3 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/script/dom/performancetiming.rs, line 50 \[r12\]](https://reviewable.io:443/reviews/servo/servo/7242#-K31O9PAY41SCBFXOpsj)** ([raw file](https://github.com/servo/servo/blob/3891a42a817c8535e5cd66d3b64d4f183895aeee/components/script/dom/performancetiming.rs#L50)):</sup>
Why this change? Specs under /TR/ are strictly less interesting to us as implementors.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7242)

**Comment by g-k** [comment]
Ah, the http://w3c.github.io/ links were 404ing last night.  I'll change
them back.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!


---

Reviewed 3 of 3 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7242)

**Pull request merged**
