### PR TITLE
gfx: Fix Core Text font instantiation for Web fonts on Mac.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @metajack

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6981)

### CODE REVIEW

**Comment by metajack** [comment]
Is there a reason to create it lazily always? Or was it just done for code cleanup?

-S-awaiting-review +S-awaiting-answer 

---

Reviewed 7 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6981)

**Comment by pcwalton** [comment]
I figured I'd create it lazily because it can't hurt to do so and it reduces code duplication to unify the code paths into the one path that e10s requires we keep around.

**Comment by metajack** [comment]
r=me when bors is back up

**Pull request merged**
