### PR TITLE
Implement basic <media> infrastructure

### PR DESCRIPTION
**Pull request by jdm**
This gets us to the point where we can start playing with actually integrating rust-media to process the data received by the network request, as currently it's just ignored.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8454)

### CODE REVIEW

**Comment by jdm** [comment]
Note: the diff isn't as bad as the diffstat makes it appear, because I enabled all of the skipped WPT.

**Comment by jdm** [comment]
9f22305 will be omitted in favour of #8430.

**Comment by eefriedman** [comment]
From tidy:

```
./components/script/dom/htmlmediaelement.rs:10: use statement is not in alphabetical order
	expected: dom::bindings::codegen::Bindings::HTMLMediaElementBinding::HTMLMediaElementConstants::*
	found: dom::bindings::codegen::Bindings::HTMLMediaElementBinding::HTMLMediaElementMethods
./components/script/dom/htmlmediaelement.rs:11: use statement is not in alphabetical order
	expected: dom::bindings::codegen::Bindings::HTMLMediaElementBinding::HTMLMediaElementMethods
	found: dom::bindings::codegen::Bindings::HTMLMediaElementBinding::HTMLMediaElementConstants::*
./components/script/dom/htmlmediaelement.rs:375: missing space before {
./components/script/dom/htmlmediaelement.rs:491: method declared in webidl is missing a comment with a specification link
./components/script/dom/htmlmediaelement.rs:495: method declared in webidl is missing a comment with a specification link
./components/script/dom/mediaerror.rs:33: method declared in webidl is missing a comment with a specification link
./components/script/dom/webidls/MediaError.webidl:6: link to WHATWG may break in the future, use this format instead: https://html.spec.whatwg.org/multipage/#mediaerror
```

**Comment by eefriedman** [comment]
(I'm skipping reviewing 479ce84; I'm assuming all the changes are part of #8430.)


---

Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 107 of 107 files at r3, 9 of 9 files at r4, 20 of 20 files at r5, 2 of 2 files at r6, 8 of 8 files at r7, 9 of 9 files at r8, 2 of 2 files at r9, 4 of 4 files at r10.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlmediaelement.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mu_PI2g2Kc3RufxxZ)** ([raw file](https://github.com/servo/servo/blob/85d486de78d4293a431f695e3834099304628d80/components/script/dom/htmlmediaelement.rs#L38)):</sup>
Missing spec link.


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 42 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2muba6_5TGLGolSJQE)** ([raw file](https://github.com/servo/servo/blob/85d486de78d4293a431f695e3834099304628d80/components/script/dom/htmlmediaelement.rs#L42)):</sup>
Missing spec link.


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 35 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mx0FYHOhMu201Sg3w)** ([raw file](https://github.com/servo/servo/blob/2111c85e608f45354a38e8c24e2b4b77692b9ece/components/script/dom/htmlmediaelement.rs#L35)):</sup>
Is using Trusted here really safe?  There isn't anything preventing the media element from being detached from the document and garbage-collected.


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 57 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mvnppoifvOA755A-w)** ([raw file](https://github.com/servo/servo/blob/2111c85e608f45354a38e8c24e2b4b77692b9ece/components/script/dom/htmlmediaelement.rs#L57)):</sup>
This seems confusing at best; could you just store a separate bool to suppress the data_available callbacks?


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 70 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mwKlmSmrmzygz6D53)** ([raw file](https://github.com/servo/servo/blob/2111c85e608f45354a38e8c24e2b4b77692b9ece/components/script/dom/htmlmediaelement.rs#L70)):</sup>
Doesn't HAVE_METADATA mean you have enough data to actually determine the metadata?  The payload could be as little as one byte.  (A TODO would be sufficient for now.)


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 278 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mzHYI5qm8B4fjAzay)** ([raw file](https://github.com/servo/servo/blob/6c1829882e3295a4307266cca4aeca579b94f028/components/script/dom/htmlmediaelement.rs#L278)):</sup>
This can just be `self.Autoplay()`.


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 596 \[r6\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mzs85LakIgaCnh3Cc)** ([raw file](https://github.com/servo/servo/blob/9f22305d771a12e58769484a54a8e5e61a2f9569/components/script/dom/htmlmediaelement.rs#L596)):</sup>
This seems extremely indirect; why not just call `internal_pause_steps()`?


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 375 \[r10\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2n01lcUpu7lUkJhsTN)** ([raw file](https://github.com/servo/servo/blob/aea5f9ec0f7e531565dc632e66fb68ca72609914/components/script/dom/htmlmediaelement.rs#L375)):</sup>
Space before brace.  Also, the string comparison is a bit inefficient.


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 510 \[r10\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2n0gERHyba5oUk_iK8)** ([raw file](https://github.com/servo/servo/blob/aea5f9ec0f7e531565dc632e66fb68ca72609914/components/script/dom/htmlmediaelement.rs#L510)):</sup>
You might want to explicitly note here that "The attribute's missing value default is user-agent defined".


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8454)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlmediaelement.rs, line 35 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mx0FYHOhMu201Sg3w)** ([raw file](https://github.com/servo/servo/blob/2111c85e608f45354a38e8c24e2b4b77692b9ece/components/script/dom/htmlmediaelement.rs#L35)):</sup>
Each Trusted value acts as a global root that prevents GC, which is the [whole point of them](http://doc.servo.org/servo/script/dom/bindings/refcounted/struct.Trusted.html).


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 278 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mzHYI5qm8B4fjAzay)** ([raw file](https://github.com/servo/servo/blob/6c1829882e3295a4307266cca4aeca579b94f028/components/script/dom/htmlmediaelement.rs#L278)):</sup>
The text at https://html.spec.whatwg.org/multipage/embedded-content.html#ready-states:autoplaying-flag seems a bit more complicated than that.


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 596 \[r6\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mzs85LakIgaCnh3Cc)** ([raw file](https://github.com/servo/servo/blob/9f22305d771a12e58769484a54a8e5e61a2f9569/components/script/dom/htmlmediaelement.rs#L596)):</sup>
The spec: https://html.spec.whatwg.org/multipage/embedded-content.html#playing-the-media-resource:media-element-75


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8454)

**Comment by eefriedman** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlmediaelement.rs, line 35 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mx0FYHOhMu201Sg3w)** ([raw file](https://github.com/servo/servo/blob/2111c85e608f45354a38e8c24e2b4b77692b9ece/components/script/dom/htmlmediaelement.rs#L35)):</sup>
Err, of course, sorry.  I haven't had to mess with Trusted yet.


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 278 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mzHYI5qm8B4fjAzay)** ([raw file](https://github.com/servo/servo/blob/6c1829882e3295a4307266cca4aeca579b94f028/components/script/dom/htmlmediaelement.rs#L278)):</sup>
I just meant "as opposed to writing out `self.upcast::<Element>().has_attribute(&Atom::from_slice("autoplay"))`".


---

<sup>**[components/script/dom/htmlmediaelement.rs, line 596 \[r6\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mzs85LakIgaCnh3Cc)** ([raw file](https://github.com/servo/servo/blob/9f22305d771a12e58769484a54a8e5e61a2f9569/components/script/dom/htmlmediaelement.rs#L596)):</sup>
Oh, sorry, I misread await_stable_state.  That makes sense.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8454)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlmediaelement.rs, line 278 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2mzHYI5qm8B4fjAzay)** ([raw file](https://github.com/servo/servo/blob/6c1829882e3295a4307266cca4aeca579b94f028/components/script/dom/htmlmediaelement.rs#L278)):</sup>
Whoops, I was looking at an earlier revision in Reviewable where this appeared to be a comment about `//TODO step N (autoplay logic)`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8454)

**Comment by eefriedman** [comment]
Review status: 15 of 108 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlmediaelement.rs, line 505 \[r10\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2nGOObSFYDoFUyuN-I)** ([raw file](https://github.com/servo/servo/blob/aea5f9ec0f7e531565dc632e66fb68ca72609914/components/script/dom/htmlmediaelement.rs#L505)):</sup>
"src" is a URL attribute, so this needs to use `make_url_getter!`.  (The wpt tests for url attributes don't currently work correctly on servo, so there will be test failures.)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8454)

**Comment by Ms2ger** [comment]
I'd like to look at this PR before landing at some point.

**Comment by jdm** [comment]
Just rebased; no comments addressed.

**Comment by jdm** [comment]
Now requires https://github.com/servo/string-cache/pull/139.

**Comment by jdm** [comment]
Still only rebased.

**Comment by jdm** [comment]
Review status: 1 of 103 files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/dom/htmlmediaelement.rs, line 375 \[r10\]](https://reviewable.io:443/reviews/servo/servo/8454#-K2n01lcUpu7lUkJhsTN:-K9nXdhq8UOnB7IDRWqV:-2100824488) ([raw file](https://github.com/servo/servo/blob/aea5f9ec0f7e531565dc632e66fb68ca72609914/components/script/dom/htmlmediaelement.rs#L375)):*
I'll leave the string comparison thing for #9101.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8454)*

**Comment by jdm** [comment]
All review comments addressed.

**Comment by jdm** [comment]
r? @KiChjang 
Redirecting the review given that @eefriedman hasn't been particularly active recently.

**Comment by KiChjang** [comment]
-S-awaiting-review +S-needs-code-changes 
Don't forget to rebase!

---

Reviewed 1 of 9 files at r4, 1 of 4 files at r10, 7 of 17 files at r11, 2 of 3 files at r12, 1 of 1 files at r16.
Review status: 11 of 107 files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlmediaelement.rs, line 60 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAezYBPQGhQDjkdDvTf:-KAezYBPQGhQDjkdDvTg:991220003) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L60)):*
These look like magical numbers to me. Is there perhaps a convenience method in Metadata that allows us to check the status codes instead?

---

*[components/script/dom/htmlmediaelement.rs, line 70 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAf0GeRFy93NBxIq76r:-KAf0GeRFy93NBxIq76s:-1590650119) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L70)):*
I don't quite understand which arm of the media data processing steps that this is following.

---

*[components/script/dom/htmlmediaelement.rs, line 102 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAf3iVXRLoTn2vMd8uu:-KAf3iVYPHQrNzm9vpr3:-1435534660) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L102)):*
Step annotations would be nice on this, and link to https://html.spec.whatwg.org/multipage/embedded-content.html#loading-the-media-resource:media-data-11.

---

*[components/script/dom/htmlmediaelement.rs, line 196 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAf4eycVONYEhv6pV7K:-KAf4eycVONYEhv6pV7L:1221820258) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L196)):*
The spec has changed on these steps.

---

*[components/script/dom/htmlmediaelement.rs, line 279 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAf7T_SvQUpMpmRP0_l:-KAf7T_SvQUpMpmRP0_m:646424609) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L279)):*
Add a TODO here about resolving playing promises.

---

*[components/script/dom/htmlmediaelement.rs, line 285 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAf7i7GMz6xSCO6gwkQ:-KAf7i7GMz6xSCO6gwkR:1291557904) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L285)):*
This is missing the part where the spec says "the media element's node document's active sandboxing flag set does not have the sandboxed automatic features browsing context flag set".

---

*[components/script/dom/htmlmediaelement.rs, line 289 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAf82oE6TFtw_UO6hZT:-KAf82oF-vkKphdEXG7y:-2011140786) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L289)):*
TODO for the resolving playing promises part, and step annotations. Also, it's missing step 5 (Set the autoplaying flag to false).

---

*[components/script/dom/htmlmediaelement.rs, line 296 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAf8TQSDehaiu1HWml9:-KAf8TQSDehaiu1HWmlA:321805503) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L296)):*
Step 2 of the ready-states algorithm ("If the media element has a current media controller, then report the controller state for the media element's current media controller.") is missing. A TODO is fine for now.

---

*[components/script/dom/htmlmediaelement.rs, line 343 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfAr3aw4WHFIkNLv1L:-KAfAr3aw4WHFIkNLv1M:1783165274) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L343)):*
This should be step 3, and should be run in parallel.

---

*[components/script/dom/htmlmediaelement.rs, line 395 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfJ2A4VJP-3L7Ytt31:-KAfJ2A5LW7yK1UJg3IF:-932146282) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L395)):*
Just an update - we currently do have a way to create a potentially CORS request under `net_traits/request.rs`.

---

*[components/script/dom/htmlmediaelement.rs, line 442 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfJxCaUcFyo33pLp_J:-KAfJxCbh1jp77r7cRKW:-1336778570) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L442)):*
This is now step 7. Step 6 is about resolving pending play promises with `NotSupportedError`.

---

*[components/script/dom/htmlmediaelement.rs, line 452 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfKIi_aIphEMZFmPAV:-KAfKIi_aIphEMZFmPAW:-151711687) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L452)):*
Gotta reject the pending play promises with `AbortError` as well.

---

*[components/script/dom/htmlmediaelement.rs, line 456 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfKWDSwlscq3KPOFD_:-KAfKWDSwlscq3KPOFDa:-1543350779) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L456)):*
This seems a bit verbose; an if-expression should be good enough.

---

*[components/script/dom/htmlmediaelement.rs, line 474 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfL11FaqF3jXiE5Q1D:-KAfL11JZNQ-umx34mrZ:-1669156115) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L474)):*
No need to check whether the ready_state is already HAVE_NOTHING first?

---

*[components/script/dom/htmlmediaelement.rs, line 476 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfL8FiqNanJFb9T9Pe:-KAfL8FiqNanJFb9T9Pf:227617854) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L476)):*
Missing annotation for step 4.5.

---

*[components/script/dom/htmlmediaelement.rs, line 547 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfMWnuopWT7XhAUCAP:-KAfMWnuopWT7XhAUCAQ:-1101585034) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L547)):*
This whole method needs to be updated to account for the new step 1-3, which deals with the promise values.

---

*[components/script/dom/htmlmediaelement.rs, line 618 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfNH29QCknRIvpQdbc:-KAfNH2ARAsOPXfuv7rQ:-671480301) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L618)):*
Not sure what I'm looking at with this spec link.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8454#-:-KAfOmHEXKaW1F5XBTiT:-266394782)*

**Comment by KiChjang** [comment]
Review status: 11 of 107 files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlmediaelement.rs, line 354 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfgJvK402F6qwMXSVG:-KAfgJvLZe7cCmR21rQo:1600159248) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L354)):*
`let absolute_url = base_url.join(&src).map_err(|_| ());`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8454)*

**Comment by jdm** [comment]
Review status: 11 of 107 files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlmediaelement.rs, line 343 \[r17\]](https://reviewable.io:443/reviews/servo/servo/8454#-KAfAr3aw4WHFIkNLv1L:-KGT_hU8poxioq9387mt:243442605) ([raw file](https://github.com/servo/servo/blob/7a124b11ecb43d57023d9f0a3e1e118b33e11696/components/script/dom/htmlmediaelement.rs#L343)):*
Filed https://github.com/whatwg/html/issues/1144 .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/8454)*

**Comment by jdm** [comment]
All review comments should have been reviewed. The rebase was surprisingly painful given that the vast majority of the changes take place in a new file introduced in this PR.

**Comment by jdm** [comment]
Note - this is basically implementing the specification as of mid-February. I haven't looked closely to see what changes have appeared since then. I'd prefer to leave that as a followup, given the difficulty of rebasing this.

**Comment by KiChjang** [comment]
Fails tidy:
```
$ ./mach test-tidy --no-progress

Checking files for tidiness...

./components/script/dom/htmlmediaelement.rs:202: link to WHATWG may break in the future, use this format instead: https://html.spec.whatwg.org/multipage/#internal-pause-steps

./components/script/dom/htmlmediaelement.rs:36: use statement is not in alphabetical order

	expected: task_source::dom_manipulation::DOMManipulationTask

	found: task_source::TaskSource

./components/script/dom/webidls/MediaError.webidl:1: emacs file variables present
```

**Comment by KiChjang** [comment]
-S-awaiting-review +S-needs-code-changes 

Almost there! This is good to land after fixing tidy and my small nits.

---

Reviewed 2 of 107 files at r3, 4 of 107 files at r18, 1 of 5 files at r19, 2 of 107 files at r21, 1 of 9 files at r22, 3 of 8 files at r25, 1 of 4 files at r28, 2 of 3 files at r29, 1 of 1 files at r30.
Review status: 11 of 104 files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlmediaelement.rs, line 99 \[r30\]](https://reviewable.io:443/reviews/servo/servo/8454#-KGkQHBrqDIL4m8j1Gff:-KGkQHBrqDIL4m8j1Gfg:54079753) ([raw file](https://github.com/servo/servo/blob/5c7bd4a2e8c9bd4b91f5ebb17514068f305509c8/components/script/dom/htmlmediaelement.rs#L99)):*
Woah, I have no idea what the hell is going on here. I understand that this is following the spec you mentioned here, but the `data_available` function also has a link to the media data processing steps list.

---

*[components/script/dom/htmlmediaelement.rs, line 202 \[r30\]](https://reviewable.io:443/reviews/servo/servo/8454#-KGkRvW6gqrplCSfJkHZ:-KGkRvW6gqrplCSfJkH_:1032210331) ([raw file](https://github.com/servo/servo/blob/5c7bd4a2e8c9bd4b91f5ebb17514068f305509c8/components/script/dom/htmlmediaelement.rs#L202)):*
Better remove this embedded-content.html, otherwise tidy will complain.

---

*[components/script/dom/htmlmediaelement.rs, line 641 \[r30\]](https://reviewable.io:443/reviews/servo/servo/8454#-KGVCN6s8MWHOYEb87oD:-KGVCN6tnhSECxB6QJ9V:-1766715308) ([raw file](https://github.com/servo/servo/blob/5c7bd4a2e8c9bd4b91f5ebb17514068f305509c8/components/script/dom/htmlmediaelement.rs#L641)):*
Step 6 here instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/8454#-:-KGkWQ9lLp1ssWpcqOLb:875888756)*

**Comment by KiChjang** [comment]
@bors-servo r+

Youtube on servo, youtube on servo, youtube on servo... YOUTUBE ON SERVO!!!

---

Reviewed 2 of 2 files at r31.
Review status: 11 of 104 files reviewed at latest revision, 24 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/8454#-:-KGne4tE5tAe71SEOv5a:1763836015)*

**Comment by jdm** [comment]
@bors-servo: retry
* git

**Comment by jdm** [comment]
@bors-servo: retry
* #10457

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * #10457

**Pull request merged**
