### PR TITLE
M1503: Extend the developer tools support - Initial steps

### PR DESCRIPTION
**Pull request by hsvalava**
Fixing ConsoleMsg for console.log messages in the Developer Tools web console.

### CODE REVIEW

**Comment by hsvalava** [comment]
This is the initial step of the student project for extending developer tools support as mentioned here: https://github.com/servo/servo/wiki/More-developer-tools-student-project

**Comment by jdm** [comment]
@hsvalava This looks great! Have you tested it to make sure it works as expected?

**Comment by hsvalava** [comment]
Hi Josh, 
I tested console.log from the Firefox console, and it works (screenshot attached). The message is printed, and the file name and line number are dummy values for now.
servo_console_log

**Comment by jdm** [comment]
Thanks for the proof :) I've left one comment on the Critic tool; be sure to click the 'sign in' link there so you get future updates by email.

**Comment by jdm** [comment]
Great! Could you squash your commits together now?

**Comment by hsvalava** [comment]
Hi Josh,
I squashed my commits together (git rebase -i --autosquash <mozilla>/master) but the push is getting rejected (non-fast forward updates). Am I supposed to force push the changes?

**Comment by jdm** [comment]
Yep, it's one of the few times that force pushing is encouraged :)

**Comment by hsvalava** [comment]
Done :)

**Comment by hsvalava** [comment]
Some test (./mach test-wpt --processes 4) failed.
Looks like it's run out of memory, or is it something else?
(pid:3754) "ERROR:net::image::base: stb_image failed: stbi_load_from_memory failed"
OSError: [Errno 12] Cannot allocate memory

**Comment by jdm** [comment]
Grumble. That's a new intermittent failure that we haven't figured out.

**Comment by hsvalava** [comment]
Thanks Josh! :)

**Pull request merged**
