### PR TITLE
Update parking_lot to 0.6

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21216)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0599]: no method named `raw_read` found for type `servo_arc::Arc<lock_api::rwlock::RwLock<parking_lot::RawRwLock, ()>>` in the current scope
  --> components/style/shared_lock.rs:77:18
   |
77 |         self.arc.raw_read();
   |                  ^^^^^^^^
error[E0599]: no method named `raw_write` found for type `servo_arc::Arc<lock_api::rwlock::RwLock<parking_lot::RawRwLock, ()>>` in the current scope
  --> components/style/shared_lock.rs:90:18
   |
90 |         self.arc.raw_write();
   |                  ^^^^^^^^^
   |
   = help: did you mean `try_write`?
error[E0599]: no method named `raw_unlock_read` found for type `servo_arc::Arc<lock_api::rwlock::RwLock<parking_lot::RawRwLock, ()>>` in the current scope
   --> components/style/shared_lock.rs:112:29
    |
112 |         unsafe { self.0.arc.raw_unlock_read() }
    |                             ^^^^^^^^^^^^^^^
    |
    = help: did you mean `force_unlock_read`?
error[E0599]: no method named `raw_unlock_write` found for type `servo_arc::Arc<lock_api::rwlock::RwLock<parking_lot::RawRwLock, ()>>` in the current scope
   --> components/style/shared_lock.rs:127:29
    |
127 |         unsafe { self.0.arc.raw_unlock_write() }
    |                             ^^^^^^^^^^^^^^^^
    |
    = help: did you mean `force_unlock_write`?
   Compiling script_traits v0.0.1 (file:///home/travis/build/servo/servo/components/script_traits)
error: aborting due to 4 previous errors
For more information about this error, try `rustc --explain E0599`.
error: Could not compile `style`.
warning: build failed, waiting for other jobs to finish...
error: build failed
The command "./mach test-unit" exited with 101.
```

**Comment by Eijebong** [comment]
There, fixed it. Ping @Amanieu to check that those changes are ok

**Comment by Amanieu** [comment]
This looks fine.

**Comment by jdm** [comment]
cc @emiluo

**Review by emilio — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* #20734

**Comment by jdm** [comment]
@bors-servo retry
* web service broke

**Pull request merged**
