### PR TITLE
Fix warnings in the fetch code.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Review on Reviewable](https://reviewable.io/reviews/servo/servo/9940)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/net/fetch/methods.rs, line 322 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9940#-KCQtzOK4lfViBbiuOou:-KCQtzOK4lfViBbiuOov:-1792527346) ([raw file](https://github.com/servo/servo/blob/31bdcbe7258cfa796b88505f5e29d75920e5c708/components/net/fetch/methods.rs#L322)):*
Is there a replacement for http_fetch_async?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9940)*

**Comment by Ms2ger** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/net/fetch/methods.rs, line 322 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9940#-KCQtzOK4lfViBbiuOou:-KCQvxLJopldbH0O46t0:1516384857) ([raw file](https://github.com/servo/servo/blob/31bdcbe7258cfa796b88505f5e29d75920e5c708/components/net/fetch/methods.rs#L322)):*
Not sure if it would ever be called directly; it's simple enough to add back if we ever need it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9940)*

**Comment by asajeffrey** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9940)*

**Pull request merged**
