### PR TITLE
fixes #7390 : tidy now check the order of mod declarations even whith attribute

### LINKED ISSUE #7390: Ensure lists of modules are in alphabetical order
For lists like
```rust
mod foo;
pub mod bar;
mod zap;
```
We should verify that they are sorted alphabetically by module name and report an error if not.

Code: python/tidy.py

### PR DESCRIPTION
**Pull request by mylainos**
Update tidy.py to check if mod declarations are in alphabetical order.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7446)

### CODE REVIEW

**Comment by Mylainos** [comment]
Should I correct the order of the mod statements ?

**Comment by jdm** [comment]
It will be impossible to merge these changes without fixing the errors that it reports. If you're willing to do that, then please do! A separate commit would be best.

**Comment by Mylainos** [comment]
How can I attach the commit with this pull request ?

**Comment by jdm** [comment]
Just make a commit in the same branch and push.

**Comment by metajack** [comment]
r=me once we have a commit that fixes problems this tool discovers.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7446)

**Comment by Mylainos** [comment]
The commit was not added so I created a new PR https://github.com/servo/servo/pull/7680 sorry for the inconvenience

**Comment by jdm** [comment]
Perfect!

**Pull request closed without merging**
