### PR TITLE
Add pinch zoom gesture for touch-screen devices

### PR DESCRIPTION
**Pull request by mbrubeck**
r? @glennw 

Notes:
- Our layer system doesn't yet support zooming `<iframe mozbrowser>` separately, so this can only zoom the root window.
- There are some issues that cause some tiles to disappear while zooming. I hope this will be fixed by WebRender.
- Sorry this is mostly in one giant commit. I did the refactoring and adding new functionality in tandem, and didn't really end up with logical or compilable intermediate commits. Hopefully the new code is easier to read than the old stuff.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8975)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Also, if you're testing this on Android, you may want override android_glue to include tomaka/android-rs-glue#72

**Comment by glennw** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/compositing/touch.rs, line 153 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8975#-K5dHdfat0zJkkKurQrJ:-K5dHdfat0zJkkKurQrK:-1675066646) ([raw file](https://github.com/servo/servo/blob/b3970ad0f361a1fb790b148f9f1d251c5de2be4f/components/compositing/touch.rs#L153)):*
touchend -> touchup

---

*[components/compositing/touch.rs, line 203 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8975#-K5dHrQjxsZul5Q-pOGr:-K5dHrQjxsZul5Q-pOGs:-1470703090) ([raw file](https://github.com/servo/servo/blob/b3970ad0f361a1fb790b148f9f1d251c5de2be4f/components/compositing/touch.rs#L203)):*
; isn't needed

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8975)*

**Comment by glennw** [comment]
@mbrubeck Couple of very minor nits, then r=me.

**Comment by mbrubeck** [comment]
@bors-servo r=glennw

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8975#-:-K5fxv4QgLrg3AfRUwkn:1544781357)*

**Pull request merged**
