### PR TITLE
Move ConstantSpec, NonNullJSNative and define_constants from utils to interface

### LINKED ISSUE #9412: Move ConstantSpec, NonNullJSNative and define_constants from utils to interface
These are only used in `script::dom::bindings::interface`.

Files:
 * components/script/dom/bindings/interface.rs
 * components/script/dom/bindings/utils.rs

### PR DESCRIPTION
**Pull request by nxnfufunezn**
Fixes #9412 
r? @nox

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9413)

### CODE REVIEW

**Comment by nox** [comment]
Just a few nits.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/interface.rs, line 20 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9413#-K8nzzRij0C8em3ku-pD:-K8nzzRij0C8em3ku-pE:1598355075) ([raw file](https://github.com/servo/servo/blob/95dde420f6d34f5ce0989b894c1c568dceacd8bc/components/script/dom/bindings/interface.rs#L20)):*
Please reorder this so that everything is in alphanumeric order, with reasonable line lengths.

---

*[components/script/dom/bindings/interface.rs, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9413#-K8nzwHDOMu-vCxM7hdZ:-K8nzwHDOMu-vCxM7hd_:-9289265) ([raw file](https://github.com/servo/servo/blob/95dde420f6d34f5ce0989b894c1c568dceacd8bc/components/script/dom/bindings/interface.rs#L23)):*
Nit: just use `libc::c_uint`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9413#-:-K8o-VcehQvIGiQJl0Zy:-1368026440)*

**Comment by nxnfufunezn** [comment]
*[components/script/dom/bindings/interface.rs, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9413#-K8nzwHDOMu-vCxM7hdZ:-K8o5oi-8FaigTBMbdgZ:787925532) ([raw file](https://github.com/servo/servo/blob/95dde420f6d34f5ce0989b894c1c568dceacd8bc/components/script/dom/bindings/interface.rs#L23)):*
there was libc::c_char usage somewhere..

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9413)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/interface.rs, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9413#-K8nzwHDOMu-vCxM7hdZ:-K8o8fo4y--UryKBfSjN:-1310289924) ([raw file](https://github.com/servo/servo/blob/95dde420f6d34f5ce0989b894c1c568dceacd8bc/components/script/dom/bindings/interface.rs#L23)):*
I know, so you should leave `use libc;` as it was before and write `libc::c_uint` instead of just `c_uint`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9413)*

**Comment by nxnfufunezn** [comment]
*[components/script/dom/bindings/interface.rs, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9413#-K8nzwHDOMu-vCxM7hdZ:-K8oAhUXbq5QzOEqKoxi:677588487) ([raw file](https://github.com/servo/servo/blob/95dde420f6d34f5ce0989b894c1c568dceacd8bc/components/script/dom/bindings/interface.rs#L23)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9413)*

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9413#-:-K8oCpHjK3942fX8eoUJ:1236647940)*

**Pull request merged**
