### PR TITLE
WebXR Layers update WebIDL

### PR DESCRIPTION
**Pull request by asajeffrey**
Updates the WebXR Layers WebIDL. Implements the "update the pending layers state" algorithm from the layer spec.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] There are updated tests for these changes

### CODE REVIEW

**Comment by CYBAI** [comment]
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface XRLayer to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:77:18
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1977:25
  │ test@http://web-platform.test:8000/resources/testharness.js:535:30
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:7
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:13:16
```

**Comment by asajeffrey** [comment]
Change to interfaces.html okayed by @jdm https://chat.mozilla.org/#/room/#servo:mozilla.org/$vsyxKtUTmCUgGzu0nKVJYaZ3Lj9T9n0vh7V9PzuPzGc

@bors-servo r=Manishearth,jdm

**Pull request merged**
