### PR TITLE
Remove dependency on util::opts from canvas crate

### PR DESCRIPTION
**Pull request by djc**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it's a small refactoring.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12490)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Nice cleanup!

**Comment by jdm** [comment]
@bors-servo: r-
Can we update the Cargo.toml and run `./mach cargo-update -p canvas`?

**Comment by djc** [comment]
@jdm update which `Cargo.toml` how? Bump the version number in canvas' one?

**Comment by jdm** [comment]
Remove the dependency on util.

**Comment by djc** [comment]
@jdm it still needs `util` for `util::thread::spawn_named`.

**Comment by jdm** [comment]
@bors-servo: r+
My mistake.

**Comment by Ms2ger** [comment]
Testing...

**Comment by jdm** [comment]
@bors-servo: retry
* #12516

**Pull request merged**
