### PR TITLE
Update ipc-channel for another fix in large transfers

### PR DESCRIPTION
**Pull request by antrik**
This pulls in 78c1be46ccc199d00d96e5dc225e8b130c5a565a , which might
help with some intermittent failures.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/servo/servo/9948)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9948#-:-KCUJ5gz6SnpOfpIvHDZ:1236647940)*

**Comment by antrik** [comment]
I don't understand what happened here. Are the CIs fighting each other or something?...

**Comment by metajack** [comment]
Not sure what hapepened. Appveyor reports it was canceled. I'm going to retry.

**Pull request merged**
