### PR TITLE
Make `path_matches` match the spec (fixes cookies)

### PR DESCRIPTION
**Pull request by Manishearth**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8752)

### CODE REVIEW

**Comment by Manishearth** [comment]
Wikipedia, Facebook (mobile/nonmobile), and HTTPS Github login work again.

**Comment by metajack** [comment]
It is frightening that wpt doesn't test this at all.

This will also need at least a unit test so this doesn't happen again.

**Comment by Manishearth** [comment]
Yeah, I'm going to file a less-easy bug for writing cookie tests in a minute. Do you think we should add the tests immediately in this PR instead?

**Comment by metajack** [comment]
I thought we already had tons of unit tests for the matching. If that's the case, I'm proposing we add one that would catch this particular case to this PR. I'm fine with wpt tests being added in a followup.

**Comment by Manishearth** [comment]
Added tests. Verified that some of them fail on an older build.

**Comment by metajack** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8752#-:-K4OVeVenmmspqfyb_I3:1236647940)*

**Pull request merged**
