### PR TITLE
do not force resource_path on android

### PR DESCRIPTION
**Pull request by paulrouget**
I want to be able to configure the resource path via `set_resources_path`.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18702)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo:
* #18715 #18723

**Comment by paulrouget** [comment]
@bors-servo: retry

#18715 #18723

**Comment by paulrouget** [comment]
@bors-servo retry

* 18338

**Comment by paulrouget** [comment]
@bors-servo retry

#18338

**Comment by jdm** [comment]
@bors-servo: retry
* missing ccache??

**Pull request merged**
