### PR TITLE
Organize reftest list alphabetically and make the tidy script check it

### LINKED ISSUE #5092: Organize reftest list alphabetically and make the tidy script check it
http://mxr.mozilla.org/servo/source/tests/ref/basic.list
http://mxr.mozilla.org/servo/source/python/tidy.py

### PR DESCRIPTION
**Pull request by gilles-leblanc**
Reftest list check is checked using Python's default string comparison.
Also added a notice in the tidy script when there are no errors.

Fixes #5092

### CODE REVIEW

**Comment by Ms2ger** [comment]
@gilles-leblanc: looks like it's been bitrotted already; could you rebase before critic picks this up?

**Comment by gilles-leblanc** [comment]
@Ms2ger I will do it tonight EST (don't have access right now) so critic can pick it up correctly. I'm not seeing the critic link so I'm guessing it skips pull requests that have pending merge conflicts?

One thing to note is that since I sorted the entire basic.list file, every change to that file in the meantime will necessitate a rebase to reorder the newly added elements. And since the entire file has changed, I can't easily merge, I have to manually look at all the commits and then reapply each change manually.

**Comment by SimonSapin** [comment]
GitHub integration with Critic is sometimes buggy and fails to pick up a PR. A work around is to close it and opening it again.

As Gilles said, the changes to the reftests list files are likely to bitrot again quickly. So let’s review as-is, and when we’re happy with the `tidy.py` changes (I filed a few issues on Critic) close the tree to rebase and land this.

**Comment by gilles-leblanc** [comment]
@SimonSapin Sorry for the delay for the modifications.

**Comment by gilles-leblanc** [comment]
I've made the latest changes following the code review. If everything is ok I'll get the latest versions of the .list files, order them and submit a rebased pull request.

**Comment by SimonSapin** [comment]
Looks good, I’m doing a rebase now so we can land it ASAP.

**Comment by SimonSapin** [comment]
Merged in #5172. Thanks again!

**Pull request closed without merging**
