### PR TITLE
servo: Update Glutin to version 0.4.20 to pick up performance and user experience improvements.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @emilio

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11235)

### CODE REVIEW

**Comment by emilio** [comment]
The cocoa version in ports/cef/Cargo.toml will have to be updated. And bitflags *might* need to be added to the tidy exception list if it isn't already (cc #11191).

**Comment by emilio** [comment]
r=me with that fixed

**Comment by nox** [comment]
Superseded by #11191.

**Pull request closed without merging**
