### PR TITLE
Share more code for primary style resolution.

### PR DESCRIPTION
**Pull request by emilio**
This will make the code Bobby is writing to get a cached primary style much less invasive.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18482)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo try

 * Just in case, though Gecko is green.

**Comment by bholley** [comment]
I'm pulling this into my stack in https://bugzilla.mozilla.org/show_bug.cgi?id=1397976

**Comment by bholley** [comment]
This seems stalled, and we don't really need it anyway.

@bors-servo try-

**Pull request closed without merging**
