### PR TITLE
Fix magicleap debugmozjs

### LINKED ISSUE #22069: Link errors building debugmozjs magicleap
Lots of missing stl symbols from linking against a debugmozjs build for magicleap, e.g.
```
...
/Users/ajeffrey/MagicLeap/mlsdk/v0.17.0/lumin/stl/libc++-lumin/include/istream:1582: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::size() const'
/Users/ajeffrey/MagicLeap/mlsdk/v0.17.0/lumin/stl/libc++-lumin/include/istream:1582: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::max_size() const'
/Users/ajeffrey/MagicLeap/mlsdk/v0.17.0/lumin/stl/libc++-lumin/include/istream:1590: undefined reference to `std::__1::basic_ios<char, std::__1::char_traits<char> >::setstate(unsigned int)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Oh joy.

### LINKED ISSUE #23074: debugmozjs build is broken
https://github.com/servo/servo/blob/ba929208e46639ca57eabb274cd98d37108ee365/components/script/script_runtime.rs#L682-L696 is not built by default and doesn't compile since #22923.

### PR DESCRIPTION
**Pull request by asajeffrey**
These changes get magicleap servo to compile with `--debugmozjs`.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #23074 and fix #22069 
- [X] These changes do not require tests because we're not building debugmozjs servo for magicleap

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23318)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Shouldn't merge until https://github.com/servo/mozjs/pull/180 does.

**Comment by asajeffrey** [comment]
This build relies on bintools 2.26, so needs an update to the magicleap SDK.

**Comment by asajeffrey** [comment]
Rebased. This PR is now ready for review. r? @jdm

**Comment by CYBAI** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/buildbot/process/buildstep.py", line 322, in startStep
    result = yield self.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/servo/buildbot/master/factories.py", line 39, in run
    got_rev, rev
exceptions.Exception: Actual commit (6af0f4deee8eefecae4065f0f495d93cc3f3ad06) differs from requested commit (fdbab412ef79f90390ee67a1db3f613be8a54ad0)
```

**Comment by asajeffrey** [comment]
Lets see if that was just transitory
```
exceptions.Exception: Actual commit (6af0f4deee8eefecae4065f0f495d93cc3f3ad06) differs from requested commit (fdbab412ef79f90390ee67a1db3f613be8a54ad0)
```
@bors-servo retry

**Comment by asajeffrey** [comment]
Nope, it wasn't :/

**Comment by asajeffrey** [comment]
Rebased. @bors-servo r=jdm

**Comment by jdm** [comment]
```
mabu: error: /Users/servo/buildbot/slave/magicleap/build/support/magicleap/Servo2D/Servo2D.mabu:33: redefining setting 'CXXFLAGS'
mabu: error: one or more project(s) failed to load
```
Interesting?

**Comment by asajeffrey** [comment]
Sigh, rebasing sometimes doesn't do the right thing, #23267 got fixed twice.

@bors-servo r=jdm

**Comment by jdm** [comment]
@bors-servo retry
* #22276

**Pull request merged**
