### PR TITLE
Use OS-agnostic filesystem paths in Python

### PR DESCRIPTION
**Pull request by frewsxcv**
This will eventually need to be done for #1908

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7568)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by SimonSapin** [comment]
I’m pretty sure that `/` works as a path separator on Windows.

**Comment by frewsxcv** [comment]
> I’m pretty sure that / works as a path separator on Windows.

That might be the case, but I think by default, most of the Python utilities like `os.listdir(".")` or `os.walk(".")` will use `\` with paths on Windows, so probably better to stay consistent

**Comment by Ms2ger** [comment]
Are we upstream for `mach_bootstrap.py`?

**Comment by frewsxcv** [comment]
If by that you mean, 'is there an associated upstream file for mach_bootstrap.py', in which case I assume the answer is 'no' but I might be wrong.

**Comment by metajack** [comment]
I originally modified the one from mozilla-central, but it would take a little bit of comparison to determine if these changes are relevant there.

**Pull request merged**
