### PR TITLE
Add `--build` and `--emulator-x86` to `./mach bootstrap-android` 

### PR DESCRIPTION
**Pull request by SimonSapin**
This allows not downloading dependencies that are not needed for a particular task.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21912)

### CODE REVIEW

**Comment by jdm** [comment]
```
---------------------------------------
Accept? (y/N): License android-sdk-preview-license:
---------------------------------------
To get started with the Android SDK Preview, you must agree to the following terms and conditions. As described below, please note that this is a preview version of the Android SDK, subject to change, that you use at your own risk. The Android SDK Preview is not a stable release, and may contain errors and defects that can result in serious damage to your computer systems, devices and data.

This is the Android SDK Preview License Agreement (the "License Agreement").

1. Introduction

Error running mach:

    ['bootstrap-android', '--accept-all-licences', '--build', '--emulator-x86']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 73: ordinal not in range(128)

  File "/home/servo/buildbot/slave/android-x86/build/python/servo/bootstrap_commands.py", line 187, in bootstrap_android
    print(line, end="")
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
yes: standard output: Broken pipe
```
from the android-x86 job.

**Comment by SimonSapin** [comment]
Amended to add:

```diff
diff --git a/python/servo/bootstrap_commands.py b/python/servo/bootstrap_commands.py
index a16981f2d8..6361fa8189 100644
--- a/python/servo/bootstrap_commands.py
+++ b/python/servo/bootstrap_commands.py
@@ -184,7 +184,7 @@ class MachCommands(CommandBase):
                 line += byte
                 if byte == b'\n' or byte == b'\r':
                     if line != previous_line:
-                        print(line, end="")
+                        print(line.decode("utf-8", "replace"), end="")
                         sys.stdout.flush()
                     previous_line = line
                     line = b""

**Comment by jdm** [comment]
@bors-servo retry
* network issue

**Pull request merged**
