### PR TITLE
Implement Node#isDefaultNamespace and Node#lookupNamespaceURI (fixes #1826)

### LINKED ISSUE #1826: Implement Node.{lookupPrefix, lookupNamespaceURI, isDefaultNamespace}
Spec at <http://dom.spec.whatwg.org/#locate-a-namespace-prefix> and below.

Probably wait for #1737 to happen first. Blocks #1655.

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6561)

### CODE REVIEW

**Comment by Ms2ger** [comment]
+S-needs-code-changes 

Still need to review the test.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 1917 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiQ7Yncnd7q2_0-QAO)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1917)):</sup>
No need for the type annotation

---

<sup>**[components/script/dom/node.rs, line 1928 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiQXX3Yvg0JAruW092)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1928)):</sup>
Reformat this somehow

---

<sup>**[components/script/dom/node.rs, line 1931 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiScv7f_XX_SWqoD8J)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1931)):</sup>
Indentation

---

<sup>**[components/script/dom/node.rs, line 1933 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiQdQDiqOx012oaWtl)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1933)):</sup>
Atomize outside the loop

---

<sup>**[components/script/dom/node.rs, line 1944 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiRnY8Z4W_HQfaUkUN)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1944)):</sup>
Recursion sucks for stack space; we should probably transform this into an iterative algorithm

---

<sup>**[components/script/dom/node.rs, line 1952 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiS2GymmX2WbRBHcJ0)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1952)):</sup>
`document_element`

---

<sup>**[components/script/dom/node.rs, line 1959 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiSCMflX4DmYMcLWSf)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1959)):</sup>
GetParentElement; I believe this is observably buggy with a Comment node that's a child of a Document node.

---

<sup>**[components/script/dom/node.rs, line 2525 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiOKFAptHmbbkiSmK8)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L2525)):</sup>
`is_empty()`

---

<sup>**[components/script/dom/node.rs, line 2532 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiPxT7BKiXhrFAviIz)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L2532)):</sup>
`ElementMethods::GetNamespaceURI` has the same code; please share it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6561)

**Comment by dzbarsky** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 1928 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiQXX3Yvg0JAruW092)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1928)):</sup>
I pulled the function out, WDYT?

---

<sup>**[components/script/dom/node.rs, line 1944 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiRnY8Z4W_HQfaUkUN)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1944)):</sup>
I tried to rewrite it as a loop but ran into lifetime errors

---

<sup>**[components/script/dom/node.rs, line 1959 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiSCMflX4DmYMcLWSf)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1959)):</sup>
Yeah, it was.  Added a test.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6561)

**Comment by Ms2ger** [comment]
+S-needs-code-changes 

---

Reviewed 2 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 1924 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6561#-Jtlbs9NT_ZjBaamZ2Vk)** ([raw file](https://github.com/servo/servo/blob/6b787e12eea802162b31f3c8fde68a8b5e0043ea/components/script/dom/node.rs#L1924)):</sup>
`prefix: &Option<Atom>`

---

<sup>**[components/script/dom/node.rs, line 1926 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6561#-Jtlc8bXlmIyL0SbawRR)** ([raw file](https://github.com/servo/servo/blob/6b787e12eea802162b31f3c8fde68a8b5e0043ea/components/script/dom/node.rs#L1926)):</sup>
No clone()

---

<sup>**[components/script/dom/node.rs, line 1928 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiQXX3Yvg0JAruW092)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1928)):</sup>
Much better

---

<sup>**[components/script/dom/node.rs, line 1943 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtlblaMEZa0KnhQpZts)** ([raw file](https://github.com/servo/servo/blob/6b787e12eea802162b31f3c8fde68a8b5e0043ea/components/script/dom/node.rs#L1943)):</sup>
`prefix.as_ref().map(Atom::from_slice)`

---

<sup>**[components/script/dom/node.rs, line 1944 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtiRnY8Z4W_HQfaUkUN)** ([raw file](https://github.com/servo/servo/blob/34cf348b3b43b32cb738c5b1de05bed9f0ca4f15/components/script/dom/node.rs#L1944)):</sup>
Let's leave it for now.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6561)

**Comment by dzbarsky** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 1926 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6561#-Jtlc8bXlmIyL0SbawRR)** ([raw file](https://github.com/servo/servo/blob/6b787e12eea802162b31f3c8fde68a8b5e0043ea/components/script/dom/node.rs#L1926)):</sup>
/Users/dzbarsky/mozilla/servo/components/script/dom/node.rs:1925:24: 1925:38 error: cannot move out of borrowed content
/Users/dzbarsky/mozilla/servo/components/script/dom/node.rs:1925                 match (*attr.prefix(), *prefix) {
                                                                                        ^~~~~~~~~~~~~~
/Users/dzbarsky/mozilla/servo/components/script/dom/node.rs:1925:40: 1925:47 error: cannot move out of borrowed content
/Users/dzbarsky/mozilla/servo/components/script/dom/node.rs:1925                 match (*attr.prefix(), *prefix) {
                                                                                                        ^~~~~~~
(It's complaining about both of the parts of the match).
Adding clones will fix it, but maybe we can do something with Some(ref __) ?

---

<sup>**[components/script/dom/node.rs, line 1943 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtlblaMEZa0KnhQpZts)** ([raw file](https://github.com/servo/servo/blob/6b787e12eea802162b31f3c8fde68a8b5e0043ea/components/script/dom/node.rs#L1943)):</sup>
Not sure we can get rid of the clone.
I get errors like so:

error: type mismatch: the type `fn(&str) -> string_cache::atom::Atom {string_cache::atom::Atom::from_slice}` implements the trait `for<'r> core::ops::FnOnce<(&'r str,)>`, but the trait `core::ops::FnOnce<(&collections::string::String,)>` is required (expected struct `collections::string::String`, found str) [E0281]
/Users/dzbarsky/mozilla/servo/components/script/dom/node.rs:1943                 let prefix_atom = prefix.as_ref().map(Atom::from_slice);

But even if I fix this by using |prefix.map(|s| Atom::from_slice(&s));|, this will move prefix so the call to locate_namespace on parent fails the borrow checker.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6561)

**Comment by Ms2ger** [comment]
Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 1926 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtqyxMUjsA1tj1Vq61P)** ([raw file](https://github.com/servo/servo/blob/d44847a5a011e8b5cee8089f2b4a443e8fc4bb88/components/script/dom/node.rs#L1926)):</sup>
`Some(ref prefix)` here and `*prefix` below will let you get rid of the clone.

---

<sup>**[components/script/dom/node.rs, line 1943 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6561#-JtlblaMEZa0KnhQpZts)** ([raw file](https://github.com/servo/servo/blob/6b787e12eea802162b31f3c8fde68a8b5e0043ea/components/script/dom/node.rs#L1943)):</sup>
`prefix.as_ref().map(|s| Atom::from_slice(s))` should work

---

<sup>**[tests/wpt/web-platform-tests/dom/nodes/Node-lookupNamespaceURI.html, line 56 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6561#-Jtt-uR5csg44bCXGGTp)** ([raw file](https://github.com/servo/servo/blob/d44847a5a011e8b5cee8089f2b4a443e8fc4bb88/tests/wpt/web-platform-tests/dom/nodes/Node-lookupNamespaceURI.html#L56)):</sup>
Test `fooElem.lookupNamespaceURI('xmlns')` after setting the xmlns attributes

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6561)

**Comment by Ms2ger** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6561)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-squash 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6561)

**Pull request merged**
