### PR TITLE
Changes on comments in servo/lib.rs

### LINKED ISSUE #8872: Convert the comments in Servo's library to doc comments
There are a lot of comments in the first few lines of `servo/lib.rs`, which should actually be doc comments, especially because that's the start page of our [Servo docs](https://doc.servo.org/), which needs some introduction. We could also move the doc comments from the `impl Browser` to its own `struct` definition, as its context is specific to `Browser`. Its current [presence in the methods](https://doc.servo.org/servo/struct.Browser.html#methods) is kinda creepy.

### PR DESCRIPTION
**Pull request by kimumetal**
1. converted the first comments in servo/lib.rs into doc comments.
2. moved doc comment of impl Browser to pub struct Browser.
   resolves #8872

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8901)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
It's nice, only one change left.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/servo/lib.rs, line 18 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8901#-K54anWh9xe-ars-990N:-K54anWiSii0pMZQD2md:-115936376) ([raw file](https://github.com/servo/servo/blob/fd7c895094e98a0a940841f8608ddf1a970e2c93/components/servo/lib.rs#L18)):*
This should actually be a [module-level](https://doc.rust-lang.org/book/documentation.html#documenting-modules) doc comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8901#-:-K54avKhITE3Od3bm1TV:1946890544)*

**Comment by vwvww** [comment]
I'm newbie on rust and servo, so I did not know about the difference between typical doc-command and module-level doc-command. Thanks! I changed the code.

**Comment by Wafflespeanut** [comment]
No worries, the changes look great! (thanks!) - someone will r+ soon :)

**Pull request merged**
