### PR TITLE
Downgrade to rustc nightly-2017-11-14

### LINKED ISSUE #19519: Servo crashes on launch with Rust nightly >= 2017-11-21
Steps to reproduce:

1. Run latest Servo nightly build.
2. It crashes immediately.

Tested in Windows 10 with Browser.html.

### PR DESCRIPTION
**Pull request by asajeffrey**
This is causing nightly servo to crash with hardware acceleration.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes work around #19519
- [X] These changes do not require tests because testing requires AWS instances with GPUs.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19574)

### CODE REVIEW

**Comment by asajeffrey** [comment]
r? @SimonSapin 
cc @glennw @jdm

**Comment by SimonSapin** [comment]
I’d like to have something in CI to make sure we don’t regress this again.

**Comment by asajeffrey** [comment]
#19575 is the issue for running on CI with GPUs.

**Comment by asajeffrey** [comment]
Added a minimal smoke test to one of the mac builders.

@bors-servo try

**Comment by asajeffrey** [comment]
Argh, unrelated CI failure? @bors-servo retry

**Comment by jdm** [comment]
@bors-servo: retry
* #19495

**Comment by SimonSapin** [comment]
I’ve edited the PR message so that merging this does not close https://github.com/servo/servo/issues/19519. This is not a fix, only a temporary work-around. We’ll still need to find and file the compiler bug.

**Comment by jdm** [comment]
@bors-servo: retry
* #19592

**Comment by jdm** [comment]
@bors-servo: retry
* #19592

**Comment by jdm** [comment]
@bors-servo: retry
* ##19495

**Comment by jdm** [comment]
@bors-servo retry
* #19593

**Comment by asajeffrey** [comment]
@bors-servo: retry

 *   #19495

**Comment by SimonSapin** [comment]
Downgrading Cargo broke some other things :/ https://github.com/servo/servo/issues/19635

**Comment by SimonSapin** [comment]
> Added a minimal smoke test to one of the mac builders.

Using `-o` is the case that does *not* cause #19519’s crash, isn’t it?

**Comment by asajeffrey** [comment]
@SimonSapin I believe `-o` doesn't imply `-x`, and still uses the GPU. The mac builders have GPUs, which is why we can run it there.

**Pull request merged**
