### PR TITLE
Update metadeps to remove duplicate error-chain crate

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18821)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
configure: error: in `/home/servo/buildbot/slave/arm32/build/target/release/build/backtrace-sys-ef6211128d6f7e04/out':
configure: error: C compiler cannot create executables
See `config.log' for more details.
thread 'main' panicked at 'failed with: exit code: 77', /home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.11/build.rs:136:8
```

Looks unrelated.

@bors-servo retry

**Comment by SimonSapin** [comment]
Same error message again, on the same machine.

**Comment by jdm** [comment]
Investigating in https://github.com/servo/saltfs/issues/683.

**Comment by jdm** [comment]
@bors-servo: retry
* going to try to debug on the build machines

**Comment by jdm** [comment]
We need https://github.com/servo/saltfs/pull/732 to be deployed before this can merge.

**Comment by SimonSapin** [comment]
Same error again.

**Comment by jdm** [comment]
Yeah, the deploy did not successfully occur, hence https://github.com/servo/saltfs/issues/734.

**Pull request merged**
