### PR TITLE
Add WebGL shader validation and translation

### PR DESCRIPTION
**Pull request by emilio**
r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7442)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 
Looking good so far!

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/webglshader.rs, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7442#-Jxuif7DClwHezZVK8EC)** ([raw file](https://github.com/servo/servo/blob/149301471b3165bafd6d0647f9e7e9be16ee65f6/components/script/dom/webglshader.rs#L112)):</sup>
Let's combine these messages.

---

<sup>**[components/script/dom/webglshader.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7442#-JxuizNqjaj2Ylk68q-9)** ([raw file](https://github.com/servo/servo/blob/149301471b3165bafd6d0647f9e7e9be16ee65f6/components/script/dom/webglshader.rs#L158)):</sup>
Should this reset the compile state too?

---

<sup>**[components/script/dom/webglshader.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7442#-Jxuj3FK_7JQQ67BN71u)** ([raw file](https://github.com/servo/servo/blob/149301471b3165bafd6d0647f9e7e9be16ee65f6/components/script/dom/webglshader.rs#L159)):</sup>
It's unclear to me if this comment is useful in practice.

---

<sup>**[tests/ref/webgl-context/tex_image_2d_simple.html, line 25 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7442#-JxujOusaFIVB-GdAwxZ)** ([raw file](https://github.com/servo/servo/blob/149301471b3165bafd6d0647f9e7e9be16ee65f6/tests/ref/webgl-context/tex_image_2d_simple.html#L25)):</sup>
What's the purpose of these changes?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7442)

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[tests/ref/webgl-context/tex_image_2d_simple.html, line 25 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7442#-JxujOusaFIVB-GdAwxZ)** ([raw file](https://github.com/servo/servo/blob/149301471b3165bafd6d0647f9e7e9be16ee65f6/tests/ref/webgl-context/tex_image_2d_simple.html#L25)):</sup>
Sorry, just read the commit message that explains this.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7442)

**Comment by ecoal95** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/webglshader.rs, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7442#-Jxuif7DClwHezZVK8EC)** ([raw file](https://github.com/servo/servo/blob/149301471b3165bafd6d0647f9e7e9be16ee65f6/components/script/dom/webglshader.rs#L112)):</sup>
Merged in `CompileShader`.

---

<sup>**[components/script/dom/webglshader.rs, line 158 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7442#-JxuizNqjaj2Ylk68q-9)** ([raw file](https://github.com/servo/servo/blob/149301471b3165bafd6d0647f9e7e9be16ee65f6/components/script/dom/webglshader.rs#L158)):</sup>
I don't think so, actually we only use it as a marker (I've taken a look right now to the gecko code and the equivalent is just a bool, and doesn't change when setting the shader source).

I haven't seen in the WebGL spec nor in the OpenGL docs anything related to the behavior it should have calling `shaderSource` again, so I think we can assume it doesn't change...

I plan to use it as a marker to detect errors at linking time (at `linkProgram`), and I guess it's perfectly valid to link a correctly-compiled shader even when you called again `shaderSource`.

Anyways I will dig around this in the next PR :P

---

<sup>**[components/script/dom/webglshader.rs, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7442#-Jxuj3FK_7JQQ67BN71u)** ([raw file](https://github.com/servo/servo/blob/149301471b3165bafd6d0647f9e7e9be16ee65f6/components/script/dom/webglshader.rs#L159)):</sup>
Ok, removing :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7442)

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for the PR!

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7442)

**Comment by ecoal95** [comment]
Updated angle to use size_t instead of u64 :package:

**Pull request merged**
