### PR TITLE
Add url parameter to the servosrc gstreamer plugin

### LINKED ISSUE #24836: GStreamer plugin url parameter
The GStreamer plugin should be able to view more than just the three.js cloth demo.

### PR DESCRIPTION
**Pull request by asajeffrey**
Support a `url` parameter for the gstreamer plugin.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #24836
- [x] These changes do not require tests because adding features to a port

### CODE REVIEW

**Review by ferjm — APPROVED** [review]

**Comment by ferjm** [comment]
@bors-servo retry

- #22276

**Comment by jdm** [comment]
@bors-servo retry
#24726

**Pull request merged**
