### PR TITLE
style: Kill SharedStyleContext::default_computed_values.

### PR DESCRIPTION
**Pull request by emilio**
This is on top of https://github.com/servo/servo/pull/15928.

Now that cascade() gets a Device ref, we can use the default computed values
from there to avoid propagating that state all over the place.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15931)

### CODE REVIEW

**Review by mbrubeck — APPROVED** [review]
r=mbrubeck after #15928 lands

**Review by mbrubeck — APPROVED** [review]
r=me

**Comment by emilio** [comment]
@bors-servo retry

 * Generic exception

**Pull request merged**
