### PR TITLE
Stylo: Bug 1350175 - Support getting line / column number of CSS rules

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1350175

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16835)

### CODE REVIEW

**Comment by upsuper** [comment]
You need to fix this first:
```
error[E0063]: missing field `source_location` in initializer of `style::font_face::FontFaceRuleData`
  --> /home/travis/build/servo/servo/tests/unit/gfx/font_cache_thread.rs:23:26
   |
23 |     let font_face_rule = FontFaceRuleData {
   |                          ^^^^^^^^^^^^^^^^ missing `source_location`
```

You need to run `./mach test-unit -p style` on servo to try.

**Comment by upsuper** [comment]
Oh actually that's in gfx's test... anyway, you need to fix it. And it's probably worth a try run first.

**Comment by ferjm** [comment]
Hmm, weird, I run `./mach test-unit -p style` locally and it worked without any test failure. The try run is here https://treeherder.mozilla.org/#/jobs?repo=try&revision=fa9e9a0e7fba5b2d25c0244a0de89c29f09c7eff

**Comment by ferjm** [comment]
Ah, nevermind, with `./mach test-unit` I see the failure.

**Comment by jdm** [comment]
Yeah, you want `./mach test-unit -p gfx` instead.

**Comment by ferjm** [comment]
@upsuper I think this is ready to land. Thanks!

**Pull request merged**
