### PR TITLE
Register/unregister memory reporters in a better place.

### PR DESCRIPTION
**Pull request by nnethercote**
By doing this on either side of the call to the relevant tasks' start()
method, we don't need to store the mem::ProfilerChan or the reporter
name in the task itself.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6608)

### CODE REVIEW

**Comment by nnethercote** [comment]
7-day review ping.

**Comment by jdm** [comment]
I nominate @glennw to review.

**Comment by nnethercote** [comment]
The previous version removed slightly too much plumbing. I've added it back in.

**Pull request merged**
