### PR TITLE
Allow simultaneous playback of audio and video for getUserMedia

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23476)

### CODE REVIEW

**Comment by ceyusa** [comment]
You just won me the PR!!! 
Just let me add above it a commit for the only audio.

**Comment by ceyusa** [comment]
> @ceyusa: key Insufficient privileges: Not in reviewers

Ok :(

but r+ fmpov

**Comment by ceyusa** [comment]
> Build execution time has reached the maximum allowed time for your plan (100 minutes).

??

**Comment by jdm** [comment]
It happens sometimes.

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
