### PR TITLE
Add Accept header to HTTP loader

### LINKED ISSUE #5399: "Not Acceptable" error when fetching ReactJS test server
After running `grunt test --debug` and watching the server start, I see:
```
Error: Not Acceptable
    at Object.exports.error (/Users/jdm/src/react/node_modules/grunt-contrib-connect/node_modules/connect/lib/utils.js:63:13)
    at /Users/jdm/src/react/node_modules/grunt-contrib-connect/node_modules/connect/lib/middleware/directory.js:112:38
    at ReaddirReq.Req.done (/Users/jdm/src/react/node_modules/populist/node_modules/graceful-fs/graceful-fs.js:143:5)
    at ReaddirReq.done (/Users/jdm/src/react/node_modules/populist/node_modules/graceful-fs/graceful-fs.js:90:22)
    at Object.oncomplete (fs.js:108:15)
```
Something about our HTTP fetch is disliked by the server.

Blocks #5398

### PR DESCRIPTION
**Pull request by bdero**
The value of the header is: `text/html;q=0.9,*/*;q=0.8`

Closes #5399

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5424)

### CODE REVIEW

**Comment by metajack** [comment]
Assigning @kmcallister. Some review has been done but it's not complete in Critic.

**Comment by jdm** [comment]
@Ms2ger:
Firefox: `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`
Chrome: `Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`
Safari: `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`

**Comment by Ms2ger** [comment]
Let's match Firefox/Safari, then.

**Comment by jdm** [comment]
We we actually want to claim we support xml or xhtml, though?

**Comment by kmcallister** [comment]
Probably not.

**Comment by Ms2ger** [comment]
I don't see why not

**Comment by kmcallister** [comment]
I don't think it matters much either way.  We can parse XHTML 1 as HTML. Almost nobody's going to send XHTML 2.

SVG is generally `image/svg+xml`. If a server sends it as `application/xml` then our logic for navigating to an image won't fire. But that doesn't seem like a big deal at this stage, and I'm not sure the `Accept` header would make any difference.

**Comment by Manishearth** [comment]
This PR might need to be updated to work with XHR, we create a new header set there.

(can't check from phone)

**Comment by kmcallister** [comment]
Just needs a decision / @Ms2ger approval on the XML issue.

**Comment by jdm** [comment]
@bdero Could you adjust the changes to match the full Firefox header, and only set it if the Accept header is not already present? Sorry this turned out to be more politically fraught than I originally anticipated :)

**Comment by Ms2ger** [comment]
Matching literally seems like the best way to avoid compat issues.

**Comment by jdm** [comment]
@bdero Still planning to finish this up?

**Comment by bdero** [comment]
Whoops, yes, I'll fix this.

**Comment by bdero** [comment]
Alright, here's what Servo's sending out now:



Which looks the same as Firefox 35.0.1:
```http_accept
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```

Ready for another round.

**Comment by jdm** [comment]
<sup>**[components/net/http_loader.rs, line 176 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5424#-JnbafvG1RhOLbJpdbdc)** ([raw file](https://github.com/servo/servo/blob/d34f2d76da922dcdb33497431bd48097a839454e/components/net/http_loader.rs#L176)):</sup>
Let's only set the header if it's not already present, so that consumers in the future can set custom ones (such as video elements or images).

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5424)

**Comment by bdero** [comment]
<sup>**[components/net/http_loader.rs, line 177 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5424#-JnbafvG1RhOLbJpdbdc)** ([raw file](https://github.com/servo/servo/blob/d34f2d76da922dcdb33497431bd48097a839454e/components/net/http_loader.rs#L177)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5424)

**Comment by jdm** [comment]
Reviewed files:
- components/net/http_loader.rs @ r3

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5424)

**Comment by jdm** [comment]
-S-awaiting-review +S-awaiting-merge 
Looks good!

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5424)

**Comment by jdm** [comment]
@bors-servo: r+

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5424)

**Pull request merged**
