### PR TITLE
Cleanup and comments in components/servo

### PR DESCRIPTION
**Pull request by brson**
Trying to make the code more pleasurable.

### CODE REVIEW

**Comment by Manishearth** [comment]
Needs rebase

**Comment by brson** [comment]
Rebased.

**Comment by jdm** [comment]
From the android builder:
```
main.rs:160:9: 160:13 error: unresolved import `libc::c_int`. Did you mean `self::libc`?
main.rs:160     use libc::c_int;
                    ^~~~
main.rs:177:44: 177:48 error: unresolved import `libc::funcs::posix88::unistd::pipe`. Maybe a missing `extern crate libc`?
main.rs:177         use libc::funcs::posix88::unistd::{pipe, dup2};
                                                       ^~~~
main.rs:177:50: 177:54 error: unresolved import `libc::funcs::posix88::unistd::dup2`. Maybe a missing `extern crate libc`?
main.rs:177         use libc::funcs::posix88::unistd::{pipe, dup2};
                                                             ^~~~
main.rs:178:13: 178:17 error: unresolved import `libc::funcs::posix88::stdio::fdopen`. Maybe a missing `extern crate libc`?
main.rs:178         use libc::funcs::posix88::stdio::fdopen;
                        ^~~~
main.rs:179:13: 179:17 error: unresolved import `libc::funcs::c95::stdio::fgets`. Maybe a missing `extern crate libc`?
main.rs:179         use libc::funcs::c95::stdio::fgets;
                        ^~~~
main.rs:164:41: 164:45 error: unresolved import `libc::consts::os::posix88::STDERR_FILENO`. Maybe a missing `extern crate libc`?
main.rs:164         use libc::consts::os::posix88::{STDERR_FILENO, STDOUT_FILENO};
                                                    ^~~~
main.rs:164:56: 164:60 error: unresolved import `libc::consts::os::posix88::STDOUT_FILENO`. Maybe a missing `extern crate libc`?
main.rs:164         use libc::consts::os::posix88::{STDERR_FILENO, STDOUT_FILENO};
                                                                   ^~~~
error: aborting due to 7 previous errors
Could not compile `servo`.
```
The mac failure appears to be a new intermittent reftest failure.

**Comment by jdm** [comment]
Although if you could run the `text_transform_lowercase_a.html` reftest locally, that would be appreciated.

**Comment by brson** [comment]
I added a patch to fix the android build and tested the suggested reftest locally.

**Comment by jdm** [comment]
```
<android_glue macros>:8:46: 8:60 error: unresolved name `super::main`
<android_glue macros>:8 android_glue:: android_main2 ( app , move || super:: $ main (  ) ) ; } } )
                                                                     ^~~~~~~~~~~~~~
<android_glue macros>:1:1: 8:75 note: in expansion of android_start!
main.rs:170:5: 170:26 note: expansion site
main.rs:198:34: 198:57 error: failed to resolve. Use of undeclared type or module `android_glue`
main.rs:198                         Ok(s) => android_glue::write_log(s),
                                             ^~~~~~~~~~~~~~~~~~~~~~~
main.rs:198:34: 198:57 error: unresolved name `android_glue::write_log`
main.rs:198                         Ok(s) => android_glue::write_log(s),
                                             ^~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Could not compile `servo`.
```

**Comment by metajack** [comment]
@larsbergstrom Assigned to you to figure out next steps.

**Pull request closed without merging**
