### PR TITLE
Refactor attribute handling to avoid marshalling attributes from Gecko into Servo

### PR DESCRIPTION
**Pull request by bholley**
This marshaling is slow, because Gecko stores attributes as UTF-16 and does not atomize them in all cases, and it turns out that the need for them in Servo is pretty minimal. With some refactoring across servo and rust-selectors we can fix this.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11886)

### CODE REVIEW

**Comment by bholley** [comment]
This isn't ready for review yet, but I want to test the rust-selectors changes.

@bors-servo try

**Comment by ConnorGBrewster** [comment]
Tidy failure:
```

Checking files for tidiness...

./components/script/Cargo.toml:60: Line is longer than 120 characters

./components/style/Cargo.toml:36: Line is longer than 120 characters

./components/layout/Cargo.toml:34: Line is longer than 120 characters

./components/script_layout_interface/Cargo.toml:29: Line is longer than 120 characters

./tests/unit/style/Cargo.toml:16: Line is longer than 120 characters

./ports/geckolib/Cargo.toml:39: Line is longer than 120 characters
```

**Comment by bholley** [comment]
Ugh, forgot to cargo-update from the old git ref.

@bors-servo try

**Comment by SimonSapin** [comment]
r=me with one change.

What was the fix still needed that you mentioned on IRC?

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 4 of 4 files at r7, 4 of 4 files at r8, 17 of 17 files at r9, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/Cargo.toml, line 39 \[r9\]](https://reviewable.io:443/reviews/servo/servo/11886#-KLuxAD9YCfI0XhMY1j-:-KLuxAD9YCfI0XhMY1j0:127356947) ([raw file](https://github.com/servo/servo/blob/3b16a2b72bd9f2c3af5ba483ab02e08ca45f6a17/components/style/Cargo.toml#L39)):*
> ```TOML
> rand = "0.3"
> rustc-serialize = "0.3"
> selectors = {version = "0.7", features = ["heap_size", "unstable"]}
> ```

This undoes some of https://github.com/servo/servo/pull/11816 , but it looks like the features are not actually needed unconditionally. Was this a rebase accident? Please change this line to `selectors = "0.7"`, and use `#[cfg(feature = "servo")]` in the crate if needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11886#-:-KLuzi5X8xEMOIo9Zpo-:1717172573)*

**Comment by bholley** [comment]
Yes, that was just a rebase error - thanks for catching. I'm going to wait for #12263 to be merged to avoid colliding.

**Comment by bholley** [comment]
@bors-servo p=1

bitrots easily ;-)

**Comment by Manishearth** [comment]
I rebased my stylo work to servo master, and it seems like the corresponding commits for this have not yet arrived in the master branch of gecko-dev, or anywhere else.

I found them in https://bugzilla.mozilla.org/show_bug.cgi?id=1283620 -- could we maintain a separate branch which always builds with servo on Github? i.e. whenever you update a bindings file and it lands, just cherry-pick the relevant gecko commits onto that branch. We can sync it when the commit lands in m-c.

**Comment by bholley** [comment]
> could we maintain a separate branch which always builds with servo on Github?

Well, it's really a symmetric problem right? If we have a logical changeset that's split across the two repos, it may land first on s/s _or_ m-c. In either case, you need to cherry-pick the corresponding changeset for one repo if you want to build tip on the other. Trying to maintain a "live" revision of one repo that builds with the tip of the other is also fraught - either you need one person always paying attention to every landing, or you need multiple people maintaining the branches, leading to coordination problems.

The best way I've come up with is to maintain two branches which are known to work with each other, which are the stylo branches. This is obviously not great, because sometimes I get behind and don't get the chance to fast-forward the branches and pick up all the changes (like what happened this week). But until we fix the repo problem, I'm not sure there's a better way. Luckily, that's happening now. :-)

**Comment by Manishearth** [comment]
Well, AIUI things land faster in Servo, and we could just hold off on starting the land process in Gecko until it gets r+d in servo. Or vice versa.

The "known good" branches should work if we're syncing enough. At the same time, I'm not very fond of landing changes on a Servo master when the changes can't actually be tested -- this is why I'm proposing an extra stylo_tip gecko-dev branch which everyone puts their commits on, with regular rebases and force-pushes.

**Pull request merged**
