### PR TITLE
4873 - Support the image map processing for <img ismap/> inside an <a/>

### PR DESCRIPTION
**Pull request by shinglyu**
This implements issue 4873

### CODE REVIEW

**Comment by jdm** [comment]
Exciting!

**Comment by shinglyu** [comment]
The critic review bot didn't kick in?

**Comment by Manishearth** [comment]
@mbrubeck could you  review the layout bits? Thanks.

**Comment by shinglyu** [comment]
@jdm: `ismap_suffix.as_ref().map(|s| &s)` returns a `&&collections::string::String`, not a `&str`. How can I fix it?

**Comment by Ms2ger** [comment]
`ismap_suffix.as_ref().map(|s| &**s)`

**Comment by shinglyu** [comment]
@Ms2ger : Thanks!

**Comment by jdm** [comment]
This looks good! Squash it all together and I'll merge it :)

**Comment by shinglyu** [comment]
Squashed! Thanks!

**Comment by shinglyu** [comment]
This solved #4873

**Pull request merged**
