### PR TITLE
Fix GC borrow hazards triggered by LoadBlocker::terminate

### LINKED ISSUE #34108: LoadBlocker::terminate is a common trigger for GC borrow hazards
The load blocker API requires a mutable borrow, which usually means the caller needs to mutably borrow a RefCell to obtain it. Since terminate also can trigger a GC in certain infrequent cases, this is both risky and over-cautious.

### PR DESCRIPTION
**Pull request by taniishkaaa**
Fixes GC borrow hazards triggered by LoadBlocker::terminate

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #34108 
- [X] There are tests for these changes

### CODE REVIEW

**Review by jdm — APPROVED** [review]
This is great! Thank you!

**Comment by taniishkaaa** [comment]
Do I allow [this](https://github.com/servo/servo/actions/runs/11661314686/job/32465383834?pr=34122)?

**Comment by jdm** [comment]
Oh, interesting. That's subtle! Let's stick with the code that you wrote instead of my suggestion.

**Comment by taniishkaaa** [comment]
> Oh, interesting. That's subtle! Let's stick with the code that you wrote instead of my suggestion.

Alright, no problem!

**Comment by Loirooriol** [comment]
Seems to break ranges: https://github.com/servo/servo/actions/runs/11669312577

```
    OK [expected ERROR] /dom/ranges/Range-cloneContents.html
    OK [expected ERROR] /dom/ranges/Range-deleteContents.html
    OK [expected ERROR] /dom/ranges/Range-extractContents.html
    OK [expected ERROR] /dom/ranges/Range-insertNode.html
    OK [expected ERROR] /dom/ranges/Range-surroundContents.html
```

**Comment by taniishkaaa** [comment]
> Seems to affect Range tests: https://github.com/servo/servo/actions/runs/11669312577
> 
> ```
>     OK [expected ERROR] /dom/ranges/Range-cloneContents.html
>     OK [expected ERROR] /dom/ranges/Range-deleteContents.html
>     OK [expected ERROR] /dom/ranges/Range-extractContents.html
>     OK [expected ERROR] /dom/ranges/Range-insertNode.html
>     OK [expected ERROR] /dom/ranges/Range-surroundContents.html
> ```

Should I remove the respective files to update test expectations?

**Comment by Loirooriol** [comment]
I don't know if it's expected or not to affect these tests. But if so, you can update the expectations like

```
./mach build -r
./mach test-wpt --release --headless --log-raw /tmp/servo.log /dom/ranges/Range-cloneContents.html /dom/ranges/Range-deleteContents.html /dom/ranges/Range-extractContents.html /dom/ranges/Range-insertNode.html /dom/ranges/Range-surroundContents.html
./mach update-wpt /tmp/servo.log
 ```

**Pull request merged**
