### PR TITLE
Clean more build artificats

### PR DESCRIPTION
**Pull request by jdm**
This is the latest attempt in the war against disk space usage on the build machines.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20107)

### CODE REVIEW

**Comment by emilio** [comment]
Looks like it needs some chmod love.

**Comment by tigercosmos** [comment]
need to be
```
chmod +x ./etc/ci/clean_build_artifacts.sh
./etc/ci/clean_build_artifacts.sh
```

**Pull request merged**
