### PR TITLE
Freetype fixes

### PR DESCRIPTION
**Pull request by nnethercote**
Because #6198 wasn't quite right.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6202)

### CODE REVIEW

**Comment by metajack** [comment]
Everything looks good except that Cargo.lock update.

**Comment by nnethercote** [comment]
I just clobbered and rebuilt `master` and I *still* get the "net" addition to Cargo.lock :(

**Comment by Manishearth** [comment]
This might be a leftover lockfile change that someone forgot to commit -- the builders won't notice it.

I think it's fine to merge as-is.

**Pull request merged**
