### PR TITLE
Fix Windows UI and font squishing

### LINKED ISSUE #15255: Windows servo UI missing elements
When I open a recent Servo for Windows nightly, the UI shows this at the top:

servo_ui_chrome

Instead of the expected browser.html chrome.

### LINKED ISSUE #15698: Windows Servo renders reddit text squished
As of https://github.com/servo/servo/pull/15681, the Windows build can now render reddit again (along with some other sites on the showcase that were failing).  Yay!

There seems to be an issue rendering reddit with the current master, which displays reddit text like this:

reddit_with_patch

### PR DESCRIPTION
**Pull request by sophiajt**
This PR:

* updates the browserhtml dep (fixes https://github.com/servo/servo/issues/15255)
* updates the Windows font metric calculation (fixes https://github.com/servo/servo/issues/15698, based on codec-abc https://github.com/servo/servo/pull/15937#issuecomment-286513712)
* may address https://github.com/servo/servo/issues/15933.  With this PR, I was not able to repro

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because change are to UI/visual results of font drawing

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16034)

### CODE REVIEW

**Comment by samlh** [comment]
> These changes do not require tests because change are to UI/visual results of font drawing

Hrm, isn't that something a reftest could cover?

Perhaps more problematic - are tests being run on Windows in CI?

**Comment by jdm** [comment]
We do not run any tests on our windows builders yet.

**Comment by jonathandturner** [comment]
Yeah, I definitely think we could flesh out the testing a bit, but I'm of the mind of "let's get Windows stood up and in the nightlies... *then* when we have more eyes on it, we'll have people help us keep pushing quality forward"

Seeing the higher order bit being just getting Windows out there.

**Comment by nox** [comment]
@jonathandturner I removed the mention of @codec-abc in the PR description because such mentions then trigger an email notification every time the merge commit is pushed to new GH repositories, please don't mention in there and only in comments instead.

**Comment by metajack** [comment]
@bors-servo r+

I was sad there was no documentation on struct FontMetrics in gfx/font.rs. Could you file this?

**Comment by metajack** [comment]
@jonathandturner Thanks for knocking these out!

**Pull request merged**
