### PR TITLE
Split Servo into multiple processes, and introduce simple sandboxing

### PR DESCRIPTION
**Pull request by pcwalton**
The sandboxing will be incomplete until the resource task is rewritten. However, it's a good start—no GPU access in the content process, for example.

Do not merge until after the Rust upgrade.

r? @jdm (overall design)
r? @kmcallister (Linux sandbox)
r? @zwarich (Mac stuff)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/4735)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Also would like to make sure that this works on Android & Gonk before merging this, as I mentioned in the weekly meeting :)

**Comment by jdm** [comment]
Reviewed everything but the two commits implementing sandboxing, which are presumably going to https://github.com/pcwalton/gaol/.

**Comment by metajack** [comment]
Assigning to @SimonSapin, though it looks like @pcwalton just needs to fix a few things and rebase.

**Comment by SimonSapin** [comment]
The code left to review is the sandbox, which I don’t really understand. Reassigning to @kmcallister.

@pcwalton, could you clarify if https://github.com/pcwalton/gaol/ should be used, like Josh suggests?

**Comment by kmcallister** [comment]
I think the plan is to use gaol, and I've reviewed the Linux sandbox portion of that.

**Comment by l0kod** [comment]
From the [Site Isolation Summit](https://www.youtube.com/playlist?list=PL9ioqAuyl6UJmC0hyI-k1wYW08O71lBn8), Chrome [site isolation](https://www.chromium.org/developers/design-documents/site-isolation) is evolving the [process-per-site-instance](https://www.chromium.org/developers/design-documents/process-models) to a new security model with [Out-of-Process IFrames](https://www.chromium.org/developers/design-documents/oop-iframes) (OOPIF): protect sites from each other.

**Comment by pcwalton** [comment]
This is blocked on the rustup because I want to switch to serde.

**Comment by metajack** [comment]
I assume this is now blocked on e10s landing?

**Comment by pcwalton** [comment]
Yes. I've got a redone version of this patch locally that's waiting on all
the e10s pieces to land.

**Comment by jdm** [comment]
Closed in favour of #6884.

**Pull request closed without merging**
