### PR TITLE
Upgrade to SpiderMonkey 67

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23587)

### CODE REVIEW

**Comment by jdm** [comment]
The mac homebrew failures are very mysterious and have been observed in other PRs as well.

**Review by asajeffrey — APPROVED** [review]
OK, looked through, the changes look sensible. There is extra complexity caused by SM task queues, which means we now have three kinds of job queues: those from SM, those from Servo, and the implicit ones caused by message queuing between threads. Sigh. Not much we can do about this.

Once the changes to mozjs and rust-mozjs land, you can r=me.

**Comment by asajeffrey** [comment]
Oh, and just to make the PR chain easier to follow, this depends on https://github.com/servo/rust-mozjs/pull/465

**Comment by jdm** [comment]
Linux:
```
/root/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/97f4613/mesa-src/configure: line 23721: test: : integer expression expected
/root/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/97f4613/mesa-src/configure: line 23727: test: : integer expression expected
configure: error: LLVM 3.3.0 or newer is required for gallium
thread 'main' panicked at 'failed with: exit code: 1', /root/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/97f4613/build.rs:61:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: build_script_build::run
   8: build_script_build::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  12: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  13: main
  14: __libc_start_main
  15: _start
```

Windows arm64:
```
  = note: lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(winheap.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src6.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src_gc0.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src18.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src22.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src7.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src11.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src13.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src15.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src16.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src20.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src14.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src21.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src12.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src10.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src_gc1.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_js_src8.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(TimeStamp_windows.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(jsutil.obj): machine type x64 conflicts with arm64
          lld-link: error: libmozjs_sys-c0632cd2dfdbc6c1.rlib(Unified_cpp_memory_build0.obj): machine type x64 conflicts with arm64
          lld-link: error: too many errors emitted, stopping now (use /errorlimit:0 to see all errors)
```

**Comment by jdm** [comment]
Sigh. When there is no `llvm` package installed in the docker image, the linux builds complain that `llvm-objdump` can't be found. When the `llvm` package is installed in the docker image, the linux builds complain that llvm >3.0 is required for osmesa.

**Comment by asajeffrey** [comment]
That is very odd, because the `clang` package for bionic brings in clang-6.0. https://packages.ubuntu.com/bionic/clang, and transitively llvm-6.0. Could this be caused by paths, that osmesa is failing to find an llvm on its search path? https://packages.ubuntu.com/bionic/amd64/llvm-6.0/filelist

**Comment by jdm** [comment]
Given:
```
/root/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/97f4613/mesa-src/configure: line 23721: test: : integer expression expected
/root/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/97f4613/mesa-src/configure: line 23727: test: : integer expression expected
configure: error: LLVM 3.3.0 or newer is required for gallium
```
I suspect it's actually failing to obtain a version number at all.

**Comment by asajeffrey** [comment]
The bionic version of `llvm-config` lives in `/usr/lib/llvm-6.0/bin/llvm-config`

**Comment by jdm** [comment]
Mmm, that probably explains it. osmesa's build is picking up /usr/bin/llvm-config.

**Comment by asajeffrey** [comment]
Can we use `update-alternatives` to pick an llvm version? c.f. https://kwangyulseo.com/2014/02/05/using-multiple-llvm-versions-on-ubuntu/

**Comment by jdm** [comment]
Looks like I was just missing the llvm-dev package as well.

**Comment by asajeffrey** [comment]
Ah, the dependencies are clang - clang-6.0 - llvm-dev-6.0, but that doesn't bring in llvm-dev.

**Pull request merged**
