### PR TITLE
Update WebIDL.py

### PR DESCRIPTION
**Pull request by Manishearth**
I'm working on getting [attributes on types landed in upstream webidl](https://bugzilla.mozilla.org/show_bug.cgi?id=1359269). In preparation for that, I'd like to update WebIDL.py and deal with all the conflicts first so that updating for that bug is easier.

(This PR doesn't need to be reviewed and landed right now, I can just roll it into the PR for implementing attributes on types, but I suspect it would be easier to land this first)

Probably should squash before landing, the steps are separated out for ease of review.

r? @nox @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22934)

### CODE REVIEW

**Comment by Manishearth** [comment]
This has not been built and tested yet, working on it

**Comment by Manishearth** [comment]
Works now. I reverted https://bugzilla.mozilla.org/show_bug.cgi?id=1368949 since nothing we use needs it yet and also implementing it in our codegen seemed tricky. I'll file a bug later.

**Comment by nox** [comment]
Rather than undoing upstream stuff, could we rather just assert that we don't have nested dictionaries in CodegenRust.py?

**Comment by Manishearth** [comment]
No, we rely on it hitting the following `isAny` branch to codegen correctly.

**Comment by nox** [comment]
What? "the following `isAny` branch"? I don't want to have to remember that we reverted something from upstream, so please make CodegenRust.py cope with the new things that are parsed but that we don't support yet.

**Comment by nox** [comment]
Ah you made a patch ok. Well I guess that's fine, but I've always tried to minimise the amount of patches and that would be better as a check in CodegenRust.py.

r=me once everything is squashed and there is a single commit remaining.

**Comment by Manishearth** [comment]
@bors-servo r=nox

thanks!

I may eventually upstream some of our patches in some form, so that they're reduced to at worst having a difference between Codegen.py and CodegenRust.py.

**Comment by Manishearth** [comment]
@bors-servo retry


timeout on tidy task, and network issue (?) on android:

```
* What went wrong:
A problem occurred configuring root project 'apk'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download fastutil.jar (it.unimi.dsi:fastutil:7.2.0)
      > Could not get resource 'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.jar'.
         > Connection reset
   > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.2.0)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.jar'.
         > Connection reset
```

**Comment by Manishearth** [comment]
@bors-servo retry

 - needs https://github.com/servo/servo/pull/22954 to land

**Pull request merged**
