### PR TITLE
Remove trailing whitespace on Python files

### PR DESCRIPTION
**Pull request by frewsxcv**
Trailing whitespace was found using flake8

This is working towards making flake8 part of the tidy process: #6236

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6260)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 2 of 3 files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- python/servo/build_commands.py @ r1
- python/servo/devenv_commands.py @ r1

---

<sup>**[python/mozlog/mozlog/structured/formatters/html/xmlgen.py, line 11 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6260#-JqoeEjL9APeM_cibnA8)** ([raw file](https://github.com/servo/servo/blob/f6fe1953343a417b62fb310a380af7c6973849b0/python/mozlog/mozlog/structured/formatters/html/xmlgen.py#L11)):</sup>
This file is taken from upstream (it lives in gecko), so it would be better to fix it there and then import a new version

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6260)

**Comment by jgraham** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- python/mozlog/mozlog/structured/formatters/html/xmlgen.py @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6260)

**Comment by SimonSapin** [comment]
Perhaps files we take from some upstream should be exempt from tidy checks?

**Comment by frewsxcv** [comment]
> Perhaps files we take from some upstream should be exempt from tidy checks?

Is there an easy way to determine which files those are or should I just whitelist certain directories?

**Comment by SimonSapin** [comment]
`tidy.py` already has a blacklist: https://github.com/servo/servo/blob/f6fe195334/python/tidy.py#L23-L38

**Comment by metajack** [comment]
@frewsxcv mozlog was from upstream for example. There's no list, but we should get in the habit of updating tidy's whitelist on upstream code drops.

**Comment by frewsxcv** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[python/mozlog/mozlog/structured/formatters/html/xmlgen.py, line 11 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6260#-JqoeEjL9APeM_cibnA8)** ([raw file](https://github.com/servo/servo/blob/f6fe1953343a417b62fb310a380af7c6973849b0/python/mozlog/mozlog/structured/formatters/html/xmlgen.py#L11)):</sup>
It does not look like Gecko accept pull requests, and the contribution process looks non-trivial, so I unfortunately will probably not contribute upstream due to personal time constraints. I am going to plan on not running flake8 on third party dependency libraries anyways

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6260)

**Comment by Manishearth** [comment]
I'll put up a patch for this.

**Comment by frewsxcv** [comment]
> I'll put up a patch for this.

Thanks :)

**Comment by Manishearth** [comment]
@bors-servo: r-

Temporary r- for ops stuff

**Comment by frewsxcv** [comment]
I am going to take this opportunity to undo my changes to ` python/mozlog/mozlog/structured/formatters/html/xmlgen.py` since it is a third party library I shouldnt touch

**Comment by frewsxcv** [comment]
Done

**Comment by Manishearth** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1170591

**Comment by SimonSapin** [comment]
@bors-servo retry

```
Unexpected Results
==================

/css21_dev/html4/absolute-replaced-height-021.htm
-------------------------------------------------
FAIL [Parent]

**Comment by Manishearth** [comment]
```
Unexpected Results
==================

/css21_dev/html4/background-root-103.htm
----------------------------------------
FAIL [Parent]
```

**Pull request merged**
