### PR TITLE
Mako task

### LINKED ISSUE #12958: Remove the mako zip file and use proper python dependencies
```
<emilio> SimonSapin: btw, do you remember why do we have the mako zip file in-tree? Couldn't we pull it as a dependency like we do with everything else?
<•SimonSapin> emilio: because we didn’t have any other Python code in the tree at the time, and that seemed less fragile than requiring virtualenv
<•SimonSapin> but now that we have a virtualenv we could very well install Mako there
<•SimonSapin> and remove the zip file
<emilio> SimonSapin: I see, I'll fill an issue about that, thanks!
<•SimonSapin> make sure to pin some required version number
```

Should be easy enough, though I'm not too versed in our python infra. @Wafflespeanut would you be interested in mentoring this if nobody does it on their own?

### PR DESCRIPTION
**Pull request by tvladyslav**
Remove mako zip

---

- [X] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [X] These changes fix #12958 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

r? @SimonSapin

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13097)

### CODE REVIEW

**Comment by crypto-universe** [comment]
test-tidy still fails.
I decided to move changes to separate branch. That is why totally new PR.
@Wafflespeanut, @SimonSapin is it OK now?

**Comment by Wafflespeanut** [comment]
`test-tidy` doesn't seem to fail in Travis. Can you please show your output? Also, which platform are you on? Windows?

**Comment by crypto-universe** [comment]
@Wafflespeanut Ubuntu linux. 
When I run `test-tidy`, it executes till 21% and then fails with message:
```
IndexError: list index out of range

File "/home/cryptouniverse/GIT/servo/python/servo/testing_commands.py", line 316, in test_tidy
return tidy.scan(not all_files, not no_progress)
File "/home/cryptouniverse/GIT/servo/python/tidy/servo_tidy/tidy.py", line 841, in scan
for error in errors:
File "/home/cryptouniverse/GIT/servo/python/tidy/servo_tidy/tidy.py", line 748, in collect_errors_for_files
for error in check(filename, lines):
File "/home/cryptouniverse/GIT/servo/python/tidy/servo_tidy/tidy.py", line 142, in check_license
if lines[0].startswith("#!") and lines[1].strip():
```

**Comment by Wafflespeanut** [comment]
That expression raises an exception only when the file is empty. Can you narrow it down to the file path? (by adding a `print` statement inside `check_license`)

**Comment by Wafflespeanut** [comment]
Strange. I pulled from your branch and tidy seems to run fine for me.

**Comment by crypto-universe** [comment]
How to be with appveyor test failure?
```
test writing_modes::initial_writing_mode_is_empty ... ok
Traceback (most recent call last):
  File "C:\projects\servo\tests\unit\style\properties\..\..\..\..\components\style\properties\build.py", line 13, in <module>
    from mako import exceptions
ImportError: No module named mako
```
Looks like mako was not imported.

**Comment by emilio** [comment]
Yes, you need to load the correct python from the `_virtualenv` path in `components/style/build.rs`, otherwise this can't merge as-is.

**Comment by Wafflespeanut** [comment]
Hm, is this specific to Windows? Usually, when we're inside `virtualenv`, calling `python` will execute `_virtualenv/bin/python`.

**Comment by UK992** [comment]
@crypto-universe  adding:
``` rust
if Command::new("python2.7.exe").arg("--version").output().is_ok() {
    return "python2.7.exe".to_owned();
}
```
before: [./tests/unit/style/properties/scaffolding.rs#L35](https://github.com/servo/servo/blob/master/tests/unit/style/properties/scaffolding.rs#L35)
solve the problem.

also please clean up this line [./components/style/properties/build.py#L10](https://github.com/servo/servo/blob/master/components/style/properties/build.py#L10)

**Comment by Wafflespeanut** [comment]
Great find! @UK992 :)

**Comment by crypto-universe** [comment]
@UK992 Thanks!

**Comment by crypto-universe** [comment]
`tidy` fails because of ./components/style/python/_virtualenv/lib/python2.7/site-packages/pip/_vendor/html5lib/filters/__init__.py
It is empty.

**Comment by Wafflespeanut** [comment]
How could it be `python/virtualenv` instead of `python/_virtualenv`? Tidy ignores only the latter, because that's the path we use for `virtualenv`.

**Comment by crypto-universe** [comment]
@Wafflespeanut By the way, is it worth to try new version of Mako? 1.0.4 instead of 0.9.1 . I am a fan of up to date software :)

**Comment by crypto-universe** [comment]
@Wafflespeanut There is an underscore, double checked. Maybe some copy-paste problem. Correct path to problematic file is
`./components/style/python/_virtualenv/lib/python2.7/site-packages/pip/_vendor/html5lib/filters/__init__.py`

**Comment by Wafflespeanut** [comment]
Let's land this with the version of Mako that was initially consistent with the code in Servo. We'll go for updating it later in a follow-up PR (if there aren't any breaking changes in the new version).

Regarding the empty file, tidy should've definitely ignored the `_virtualenv` directory (not sure why you're getting the error). That said, let's wait for the CI build results :)

**Comment by UK992** [comment]
Well, ``_virtualenv`` folder should be in ``./python/`` dir, not in ``./components/style/python/``.
Delete ``./components/style/python/_virtualenv/`` folder and recreate virtual environment.

**Comment by crypto-universe** [comment]
@UK992 You are right. Looks like that folder was accidentally created during my experiments.

**Comment by SimonSapin** [comment]
@bors-servo r+

Thanks!

**Comment by Wafflespeanut** [comment]
@bors-servo r-

Requires appropriate squashing before merge!

**Comment by crypto-universe** [comment]
@Wafflespeanut how to squash these 3 commits?

**Comment by Wafflespeanut** [comment]
The first commit introduces changes to `build.rs`, but then the second one reverts those (hence, they both should be squashed). It'd also be much better if you could move the `build.py` changes to the first commit, and leave the changes related to Windows in the last commit.

**Comment by crypto-universe** [comment]
@Wafflespeanut That will require a new branch and new PR. I'll do that. This PR can be closed.

**Comment by Wafflespeanut** [comment]
No, you can just force push to this branch?

**Comment by crypto-universe** [comment]
Let's try :)

**Pull request merged**
