### PR TITLE
Fix file-type input element

### PR DESCRIPTION
**Pull request by izgzhen**
A simple fix to put `inputElem.files` online

Part of #11131

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11931)

### CODE REVIEW

**Comment by Manishearth** [comment]
Oh, I see, you had already added support, but the interface tests didn't pass because the support only worked when you had selected the file. 😄 

@bors-servo r+

**Comment by Manishearth** [comment]
Whole bunch of PASS expected FAILs:

```

Tests with unexpected results:
  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: attribute files

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: document.createElement("input") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("text") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("hidden") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("search") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("tel") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("url") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("email") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("password") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("date") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("month") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("week") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("time") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("datetime-local") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("number") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("range") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("color") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("checkbox") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("radio") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("submit") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("image") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("reset") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] HTMLInputElement interface: createInput("button") must inherit property "files" with the proper type (9)

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=hidden

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=text

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=search

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=tel

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=url

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=email

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=password

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=datetime

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=date

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=month

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=week

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=time

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=datetime-local

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=number

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=range

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=color

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=checkbox

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=radio

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=submit

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=image

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=reset

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=button

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/files.html:
  └ PASS [expected FAIL] files for input type=file

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/hidden.html:
  └ PASS [expected FAIL] files attribute must return null for hidden

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/text.html:
  └ PASS [expected FAIL] files attribute must return null for text

  ▶ Unexpected subtest result in /html/semantics/forms/the-input-element/text.html:
  └ PASS [expected FAIL] files attribute must return null for search
```

**Comment by izgzhen** [comment]
Oh, nice, I thought only FileAPI cover that ... I will fix this

**Comment by izgzhen** [comment]
Done

**Comment by izgzhen** [comment]
@bors-servo retry

Issue #11574

**Pull request merged**
