### PR TITLE
Create a top-level "third_party" directory

### PR DESCRIPTION
**Pull request by mrobinson**
This directory now contains third_party software that is vendored into
the Servo source tree. The idea is that it would eventually hold
webrender and other crates from mozilla-central as well with a standard
patch management approach for each.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because this should not change behavior.

### CODE REVIEW

**Comment by mrobinson** [comment]
@emilio: Followup to the conversation in the TSC meeting today. This is the proposal for managing vendored dependencies in Servo. There is a top-level `third_party` directory; in this PR it only contains pre-existing vendored dependencies. Eventually this would have a directory for `style`, `selectors`, and `webrender` though.

**Review by atbrakhi — APPROVED** [review]

**Comment by mrobinson** [comment]
@bors-servo retry
 - Network issues

**Pull request merged**
