### PR TITLE
form element accessed by index

### LINKED ISSUE #11405: Implement HTMLFormElement Element getter
This is just a getter that returns the form element at the given index. `HTMLFormControlsCollection.IndexedGetter` should be used.

---
Spec: https://html.spec.whatwg.org/multipage/forms.html#dom-form-item
Code: `components/script/dom/webidl/HTMLFormElement.webidl` `components/script/dom/htmlformelement.rs` `components/script/dom/htmlformcontrolscollection.rs`

### PR DESCRIPTION
**Pull request by mrmiywj**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11405 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11657)

### CODE REVIEW

**Comment by emilio** [comment]
This is just a partial review. Probably @Ms2ger has a lot more to say here, or to correct if any of my review comments aren't accurate.

-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :umbrella: The latest upstream changes (presumably #11548) made this pull request unmergeable. Please resolve the merge conflicts.
</details>


---

Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlformelement.rs, line 237 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11657#-KJoqwbLXEg6ByG76bMN:-KJoqwbLXEg6ByG76bMO:1040218678) ([raw file](https://github.com/servo/servo/blob/6759949042eea10e05d941783e7e556227f074ee/components/script/dom/htmlformelement.rs#L237)):*
> ```Rust
>     fn IndexedGetter(&self, index: u32, found: &mut bool) -> Option<Root<Element>> {
>         let elements = self.Elements();
>         (*elements).IndexedGetter(index, found)
> ```

I *think* this explicit dereferene might not be needed, but leave it if it is.

---

*[components/script/dom/webidls/HTMLFormElement.webidl, line 20 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11657#-KJopXiiN5gn_rzPnwgs:-KJopXij0Iqb7nDVoNjN:705174946) ([raw file](https://github.com/servo/servo/blob/6759949042eea10e05d941783e7e556227f074ee/components/script/dom/webidls/HTMLFormElement.webidl#L20)):*
> ```WebIDL
>   [SameObject] readonly attribute HTMLFormControlsCollection elements;
>   readonly attribute unsigned long length;
>   getter Element? (unsigned long index);
> ```

I'm not totally sure, does this change the semantics to return `null` instead of `undefined` for out of bounds elements?

---

*[tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/form-indexed-element.html, line 10 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11657#-KJopx0GXHbU4wBubZyn:-KJopx0GXHbU4wBubZyo:-1542664303) ([raw file](https://github.com/servo/servo/blob/6759949042eea10e05d941783e7e556227f074ee/tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/form-indexed-element.html#L10)):*
> ```HTML
> <div id="test">
> <form id=form>
> <table>
> ```

Is there an specific reason for the `<table>`? It seems just stylistic.

---

*[tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/form-indexed-element.html, line 22 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11657#-KJopn5yrpeCnQyU7Svs:-KJopn5yrpeCnQyU7Svt:-102196647) ([raw file](https://github.com/servo/servo/blob/6759949042eea10e05d941783e7e556227f074ee/tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/form-indexed-element.html#L22)):*
> ```HTML
>   var form = document.getElementById("form");
>   assert_equals(form[0], document.getElementById("r1"));
>   assert_equals(form[1], document.getElementById("r2"));
> ```

anyway, this also needs at least a test for `form[2]` being `undefined`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11657#-:-KJopAGeoZPm_QJdYXWf:1269312134)*

**Comment by emilio** [comment]
`s/out of bounds elements/out of bounds indices/` before.

Ah, and thanks for your contribution! :)

**Comment by Ms2ger** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/script/dom/webidls/HTMLFormElement.webidl, line 20 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11657#-KJopXiiN5gn_rzPnwgs:-KJow0Okrp8yTzPIHkYl:-1430711950) ([raw file](https://github.com/servo/servo/blob/6759949042eea10e05d941783e7e556227f074ee/components/script/dom/webidls/HTMLFormElement.webidl#L20)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> I'm not totally sure, does this change the semantics to return `null` instead of `undefined` for out of bounds elements?
</details>
This is unavoidable for now.

---

*[tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/form-indexed-element.html, line 22 \[r5\]](https://reviewable.io:443/reviews/servo/servo/11657#-KJopn5yrpeCnQyU7Svs:-KJow6tfDJR6-3XT5pZu:1757822091) ([raw file](https://github.com/servo/servo/blob/6759949042eea10e05d941783e7e556227f074ee/tests/wpt/web-platform-tests/html/semantics/forms/the-form-element/form-indexed-element.html#L22)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> anyway, this also needs at least a test for `form[2]` being `undefined`.
</details>
As well as `form[-1]`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11657)*

**Comment by mrmiywj** [comment]
Closed due to [#11697](https://github.com/servo/servo/pull/11697)

**Pull request closed without merging**
