### PR TITLE
Re-export crates needed to use the Servo Rust API

### PR DESCRIPTION
**Pull request by meh**
This helps out on using the Servo API from a Rust project.

Right now I have to explicitly declare all the crates contained in `components` to use them.

Unsure about re-exporting `euclid`, `url` and `layers`, but they are required to use the API and it helps out avoiding version-collisions if you happen to use the wrong version in your own project.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7448)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Have you tried this? Last time I checked, `pub extern crate` doesn’t do what you’d expect, it’s the same as `extern crate`.

Also be aware that we’re making absolutely no promise of API stability, especially in the inner crates. We *will* make breaking changes sooner or later.

**Comment by SimonSapin** [comment]
To expand on API stability: clearly we need a better story here, we just haven’t given it much thought yet.

To perhaps help guide that: what do you need from `components/*` crate? Is there a small subset that we could stabilize (eventually)?

**Comment by meh** [comment]
I'm testing now if it actually works.

I am aware you're not making any promises about API stability, I'm fine with that.

And I'm basically using every component, I'm reimplementing the `Browser` and `Window` stuff myself.

**Comment by meh** [comment]
@SimonSapin ok I did some changes, now my project compiles and works using just `servo` as dependency.

**Comment by frewsxcv** [comment]
@meh In case you missed it, your last push fails the lint checker (see travis output for more info)

**Comment by meh** [comment]
I did miss that, thanks, I wish GitHub sent emails when this happened :rage4:

**Comment by SimonSapin** [comment]
Alright, as long as you’re aware of the API instability, this change is not costing us much. If it make your life easier let’s take it.

r? @jdm for the webdriver changes

**Comment by jdm** [comment]
@bors-servo: r+
Webdriver changes are fine with me.

**Pull request merged**
