### PR TITLE
Remove compositor dependency on net crate.

### LINKED ISSUE #5551: Make the compositor stop depending on the net crate
There's only one dependency left: http://mxr.mozilla.org/servo/source/components/compositing/constellation.rs#23 . It should be simple to move this trait into net_traits/lib.rs and remove the last dependency; this will make building after modifying net/ super speedy!

### PR DESCRIPTION
**Pull request by aneeshusa**
Move the ImageCacheTaskClient trait and impl to net_traits. Fixes #5551.

### CODE REVIEW

**Comment by Manishearth** [comment]
```
   Compiling net v0.0.1 (file:///home/servo/buildbot/slave/linux1/build/components/servo)
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:553:26: 553:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:553         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:553:32: 553:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:553:32: 553:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:585:26: 585:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:585         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:585:32: 585:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:585:32: 585:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:603:26: 603:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:603         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:603:32: 603:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:603:32: 603:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:628:26: 628:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:628         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:628:32: 628:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:628:32: 628:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:656:26: 656:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:656         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:656:32: 656:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:656:32: 656:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:686:26: 686:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:686         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:686:32: 686:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:686:32: 686:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:732:26: 732:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:732         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:732:32: 732:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:732:32: 732:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:788:26: 788:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:788         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:788:32: 788:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:788:32: 788:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:825:26: 825:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:825         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:825:32: 825:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:825:32: 825:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:861:26: 861:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:861         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:861:32: 861:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:861:32: 861:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:891:26: 891:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:891         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:891:32: 891:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:891:32: 891:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:919:26: 919:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:919         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:919:32: 919:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:919:32: 919:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:947:26: 947:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:947         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:947:32: 947:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:947:32: 947:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:975:26: 975:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:975         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:975:32: 975:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:975:32: 975:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:998:26: 998:32 error: type `net_traits::image_cache_task::ImageCacheTask` does not implement any method in scope named `exit`
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:998         image_cache_task.exit();
                                                                                                        ^~~~~~
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:998:32: 998:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
/home/servo/buildbot/slave/linux1/build/components/net/image_cache_task.rs:998:32: 998:32 help: candidate #1: use `net_traits::image_cache_task::ImageCacheTaskClient`
error: aborting due to 15 previous errors
Could not compile `net`.

```

**Comment by aneeshusa** [comment]
When I run './mach build' on my branch it runs fine - how can I reproduce the failure / fix whatever is wrong? Not sure exactly what I need to do here.

**Comment by jdm** [comment]
@aneeshusa You would need to pull the latest revision from master and rebase your branch on top of it (`git checkout master; git pull origin master; git rebase master remove-compositor-dependency-on-net`) to see the same build errors.

**Comment by jdm** [comment]
Well, assuming `origin` is pointing at the servo/servo repository, rather than your fork.

**Comment by aneeshusa** [comment]
Just rebased on master and reran mach build - everything compiled successfully, no failures.

**Comment by jdm** [comment]
Aha! They moved to the unit tests crate - use `./mach test-unit` to see them.

**Comment by aneeshusa** [comment]
Alright, I fixed the units tests. However, I rebased on master, and hoppipolla-critic-bot says not to rewrite history - should I make a new PR or just force update the branch?

**Comment by Ms2ger** [comment]
Just force-update, we'll deal this time.

**Pull request merged**
