### PR TITLE
Update binding files

### PR DESCRIPTION
**Pull request by upsuper**
From tip of autoland.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17919)

### CODE REVIEW

**Comment by upsuper** [comment]
This removes tons of lines from structs binding files, likely because of behavior change mentioned in rust-lang-nursery/rust-bindgen#834.

**Comment by heycam** [comment]
@bors-servo r+

I didn't check the structs file changes closely at all; will just assume if Firefox compiles it's fine.

**Comment by upsuper** [comment]
Firefox doesn't need those files. Only Servo CI needs them. `mach build-geckolib` seems to work fine at least locally.

**Comment by upsuper** [comment]
```
thread 'bindings::root::__bindgen_test_layout_UnionMember_open0_OwningNonNull_open1_nsINode_close1_close0_instantiation' panicked at 'assertion failed: `(left == right)` (left: `8`, right: `16`): Size of template specialization: root :: mozilla :: dom :: UnionMember', /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/style-50230c48b8c253a8/out/gecko/structs_debug.rs:35456
thread 'bindings::root::__bindgen_test_layout_UnionMember_open0_nsString_close0_instantiation' panicked at 'assertion failed: `(left == right)` (left: `8`, right: `16`): Size of template specialization: root :: mozilla :: dom :: UnionMember', /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/style-50230c48b8c253a8/out/gecko/structs_debug.rs:35478
```

Looks like we have some trouble... cc @emilio

**Pull request merged**
