### PR TITLE
layout: Make overflow calculation take relative percentages into account.

### PR DESCRIPTION
**Pull request by pcwalton**
This necessitated changing overflow to be calculated by the parent flow
if relatively positioned children are present. That is because the
overflow regions cannot be calculated without knowing relative offsets,
which themselves cannot be calculated without knowing the parent size
(because of percentages). To accomplish this without sacrificing
parallelism in the non-relative case, this patch splits overflow into
"early" and "late" computation. Late overflow computation cannot be
parallelized across children, while early overflow computation can.

Makes the "Apple Music" text show up over the full-bleed promotional
background on apple.com.

r? @SimonSapin -- would appreciate a look over the iframe test case that was changed.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7313)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed 13 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7313)

**Comment by mbrubeck** [comment]
r=mbrubeck with tidy errors fixed

**Comment by SimonSapin** [comment]
`tests/ref/iframe/size_attributes_vertical_writing_mode.html` is messed up in many interesting ways. #7355 makes it more reasonable. I recommend reverting the change in this PR to that file, rebasing on top of #7355, and adding another test for relative positioning in vertical-lr mode that goes something like:

```html
<!DOCTYPE html>
<style>
html { height: 250px }
body { writing-mode: vertical-lr }
div { width: 100px; height: 100px }
</style>
<div style="background: blue"></div>
<div style="background: green; position: relative; top: 10px; left: 20px"></div>

**Comment by SimonSapin** [comment]
The reference should use `position: relative; top: 10px; left: 20px` but not `writing-mode` the translation caused by relpos should be the same regardless of writing mode.

**Comment by pcwalton** [comment]
Removed the changes to that iframe test case.

**Comment by mbrubeck** [comment]
```
/css21_dev/html4/abs-pos-non-replaced-vlr-069.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/abs-pos-non-replaced-vlr-177.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/abs-pos-non-replaced-vlr-193.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/abs-pos-non-replaced-vrl-176.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/abs-pos-non-replaced-vrl-192.htm
-------------------------------------------------
PASS expected FAIL [Parent]
/css21_dev/html4/absolute-replaced-width-015.htm
------------------------------------------------
PASS expected FAIL [Parent]
```

**Pull request merged**
