### PR TITLE
RootCollection: Start using RootedVec instead of SmallVec32.

### LINKED ISSUE #5504: Crash when browsing http://slashdot.org/.
Servo crashes when trying to browse http://slashdot.org/:

```
$ ./mach run http://slashdot.org/
ERROR:js::rust: Error at http://slashdot.org/:25: ReferenceError: $ is not defined

thread 'ScriptTask' panicked at 'assertion failed: !(*roots).spilled()', /tmp/servo/servo/components/script/dom/bindings/js.rs:635
stack backtrace:
   1:        0x10f5c03ad - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x10f5d442d - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x10f5a0769 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x10e25cfce - rt::unwind::begin_unwind::h2797280513286754739
   5:        0x10e2aff6f - dom::bindings::js::RootCollection::root::h3239ad8aa54bc4deMfb
   6:        0x10e2dd3c9 - dom::bindings::js::Root<T>::new::h727169610020182828
   7:        0x10e726cfe - dom::bindings::js::JS<T>::root::closure.93155
   8:        0x10e726c33 - thread_local::Key<T>::with::h15884240205487578153
   9:        0x10e726b32 - dom::bindings::js::JS<T>::root::h9350584273792268961
  10:        0x10e72f080 - dom::element::JSRef<'a, Element>.AttributeHandlers::get_attributes::closure.93258
  11:        0x10e72f01d - iter::Map<I, F>.Iterator::next::closure.93255
  12:        0x10e72ef66 - option::Option<T>::map::h9720892859428496766
  13:        0x10e72eee7 - iter::Map<I, F>.Iterator::next::h11522442428743043808
  14:        0x10e72ee73 - iter::_&'a mut I.Iterator::next::h8426565455805106695
  15:        0x10e72ebe3 - iter::FilterMap<I, F>.Iterator::next::h8356250314958242076
  16:        0x10e72e469 - vec::Vec<T>.FromIterator<T>::from_iter::h9563925045015085784
  17:        0x10e72e0de - iter::IteratorExt::collect::h5109994512190187326
  18:        0x10e72de39 - dom::element::JSRef<'a, Element>.AttributeHandlers::get_attributes::h07cffaab52f90fdeDmb
  19:        0x10e6dc182 - dom::element::JSRef<'a, Element>.AttributeHandlers::get_attribute::h84d13d85f31d84dePlb
  20:        0x10e75266e - dom::element::JSRef<'a, Element>.VirtualMethods::bind_to_tree::h38243912c2d9417fOdc
  21:        0x10e7782ca - dom::virtualmethods::VirtualMethods::bind_to_tree::h12638062833845395755
  22:        0x10e7afce5 - dom::htmllinkelement::JSRef<'a, HTMLLinkElement>.VirtualMethods::bind_to_tree::hb81156070d9a2304kwj
  23:        0x10e7d92e0 - dom::node::JSRef<'a, Node>.PrivateNodeHelpers::node_inserted::hb191a42019f12daermo
  24:        0x10e7e7dcc - dom::node::Node::insert::fire_observer_if_necessary::h7c8b9e7d49076347Rpp
  25:        0x10e7e54be - dom::node::Node::insert::h1c8dfc24a21cb7aeiop
  26:        0x10e7e23ab - dom::node::Node::pre_insert::h0efc1e3cbdebd294whp
  27:        0x10e50681f - dom::node::JSRef<'a, Node>.NodeMethods::AppendChild::hdecd87c1fae093c3oPp
  28:        0x10e50643e - dom::bindings::codegen::Bindings::NodeBinding::appendChild::__rust_abi
  29:        0x10e38f343 - dom::bindings::codegen::Bindings::NodeBinding::appendChild::h0c210702386b7a1bCPk
  30:        0x10f5febab - CallJitMethodOp
  31:        0x10e5089ea - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::__rust_abi
  32:        0x10e38ef27 - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::hd09def13dc7d8ac3FZk
  33:        0x10ead3f72 - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  34:        0x10eacdb5c - _ZN2js9InterpretEP9JSContextPNS_10StackFrameENS_10InterpModeE
  35:        0x10eac6086 - _ZN2js9RunScriptEP9JSContextP8JSScriptPNS_10StackFrameE
  36:        0x10ead4739 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeEPNS_10StackFrameEPS9_
  37:        0x10ead4874 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  38:        0x10ea5e03d - _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKtmPNS_5ValueE
  39:        0x10ea5e27c - JS_EvaluateUCScript
  40:        0x10e7c05c7 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::closure.94897
  41:        0x10e7c03e7 - rust::with_compartment::h14538346473171005238
  42:        0x10e7c0303 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::h8343629566505271552
  43:        0x10e7bf61f - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::execute::hb9a18f04689454c49Pk
  44:        0x10e7bc6fd - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::prepare::ha663be7e8d9a5b267Ik
  45:        0x10e7c3bc7 - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.VirtualMethods::bind_to_tree::hcfa535582be9e756H7k
  46:        0x10e7d92e0 - dom::node::JSRef<'a, Node>.PrivateNodeHelpers::node_inserted::hb191a42019f12daermo
  47:        0x10e7e7dcc - dom::node::Node::insert::fire_observer_if_necessary::h7c8b9e7d49076347Rpp
  48:        0x10e7e54be - dom::node::Node::insert::h1c8dfc24a21cb7aeiop
  49:        0x10e7e23ab - dom::node::Node::pre_insert::h0efc1e3cbdebd294whp
  50:        0x10e5060a0 - dom::node::JSRef<'a, Node>.NodeMethods::InsertBefore::h8d6f5ec89060a3b01Op
  51:        0x10e505c7d - dom::bindings::codegen::Bindings::NodeBinding::insertBefore::__rust_abi
  52:        0x10e38f2e3 - dom::bindings::codegen::Bindings::NodeBinding::insertBefore::h54de8a35b65a15a0sLk
  53:        0x10f5febab - CallJitMethodOp
  54:        0x10e5089ea - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::__rust_abi
  55:        0x10e38ef27 - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::hd09def13dc7d8ac3FZk
  56:        0x10ead3f72 - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  57:        0x10eacdb5c - _ZN2js9InterpretEP9JSContextPNS_10StackFrameENS_10InterpModeE
  58:        0x10eac6086 - _ZN2js9RunScriptEP9JSContextP8JSScriptPNS_10StackFrameE
  59:        0x10ead4739 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeEPNS_10StackFrameEPS9_
  60:        0x10ead4874 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  61:        0x10ea5e03d - _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKtmPNS_5ValueE
  62:        0x10ea5e27c - JS_EvaluateUCScript
  63:        0x10e7c05c7 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::closure.94897
  64:        0x10e7c03e7 - rust::with_compartment::h14538346473171005238
  65:        0x10e7c0303 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::h8343629566505271552
  66:        0x10e7bf61f - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::execute::hb9a18f04689454c49Pk
  67:        0x10e7bc6fd - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::prepare::ha663be7e8d9a5b267Ik
  68:        0x10e7c3bc7 - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.VirtualMethods::bind_to_tree::hcfa535582be9e756H7k
  69:        0x10e7d92e0 - dom::node::JSRef<'a, Node>.PrivateNodeHelpers::node_inserted::hb191a42019f12daermo
  70:        0x10e7e7dcc - dom::node::Node::insert::fire_observer_if_necessary::h7c8b9e7d49076347Rpp
  71:        0x10e7e54be - dom::node::Node::insert::h1c8dfc24a21cb7aeiop
  72:        0x10e7e23ab - dom::node::Node::pre_insert::h0efc1e3cbdebd294whp
  73:        0x10e5060a0 - dom::node::JSRef<'a, Node>.NodeMethods::InsertBefore::h8d6f5ec89060a3b01Op
  74:        0x10e505c7d - dom::bindings::codegen::Bindings::NodeBinding::insertBefore::__rust_abi
  75:        0x10e38f2e3 - dom::bindings::codegen::Bindings::NodeBinding::insertBefore::h54de8a35b65a15a0sLk
  76:        0x10f5febab - CallJitMethodOp
  77:        0x10e5089ea - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::__rust_abi
  78:        0x10e38ef27 - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::hd09def13dc7d8ac3FZk
  79:        0x10ead3f72 - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  80:        0x10eacdb5c - _ZN2js9InterpretEP9JSContextPNS_10StackFrameENS_10InterpModeE
  81:        0x10eac6086 - _ZN2js9RunScriptEP9JSContextP8JSScriptPNS_10StackFrameE
  82:        0x10ead4739 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeEPNS_10StackFrameEPS9_
  83:        0x10ead4874 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  84:        0x10ea5e03d - _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKtmPNS_5ValueE
  85:        0x10ea5e27c - JS_EvaluateUCScript
  86:        0x10e7c05c7 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::closure.94897
  87:        0x10e7c03e7 - rust::with_compartment::h14538346473171005238
  88:        0x10e7c0303 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::h8343629566505271552
  89:        0x10e7bf61f - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::execute::hb9a18f04689454c49Pk
  90:        0x10e7bc6fd - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::prepare::ha663be7e8d9a5b267Ik
  91:        0x10e911359 - parse::html::servohtmlparser..Sink.TreeSink::complete_script::closure.98603
  92:        0x10e9112db - option::Option<T>::map::h4823584091535465418
  93:        0x10e82f878 - parse::html::servohtmlparser..Sink.TreeSink::complete_script::hcc9ad2586b58a3efHEw
  94:        0x10e8100ce - tree_builder::rules::super..TreeBuilder<Handle, Sink>.TreeBuilderStep::step::h15753392582135408227
  95:        0x10e8017bc - tree_builder::TreeBuilder<Handle, Sink>::process_to_completion::h17394548604650618013
  96:        0x10e8001ce - tree_builder::TreeBuilder<Handle, Sink>.TokenSink::process_token::h16838172824630258104
  97:        0x10e7ff3b2 - tokenizer::Tokenizer<Sink>::process_token::h4223826186911339883
  98:        0x10e8399a6 - tokenizer::Tokenizer<Sink>::emit_current_tag::h3743473990165524377
  99:        0x10e7f8874 - tokenizer::Tokenizer<Sink>::step::h5755909512975338631
  100:        0x10e7f5d3b - tokenizer::Tokenizer<Sink>::run::h4132648654899320302
 ... <frames omitted>
thread 'ScriptTask' panicked at 'assertion failed: unrooted == rooted.js_ptr', /tmp/servo/servo/components/script/dom/bindings/js.rs:646
stack backtrace:
   1:        0x10f5c03ad - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x10f5d442d - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x10f5a0769 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x10e25cfce - rt::unwind::begin_unwind::h2797280513286754739
   5:        0x10e3a5a66 - dom::bindings::js::RootCollection::unroot::h13002791494889358609
   6:        0x10e3a57a0 - dom::bindings::js::Root<T>.Drop::drop::h13717543120224900946
   7:        0x10e3a5755 - dom..bindings..js..Root<dom..document..Document>::glue_drop.85216::h2bb7d1b9a7addd14
   8:        0x10e7d91d8 - dom::node::JSRef<'a, Node>.PrivateNodeHelpers::node_inserted::hb191a42019f12daermo
   9:        0x10e7e7dcc - dom::node::Node::insert::fire_observer_if_necessary::h7c8b9e7d49076347Rpp
  10:        0x10e7e54be - dom::node::Node::insert::h1c8dfc24a21cb7aeiop
  11:        0x10e7e23ab - dom::node::Node::pre_insert::h0efc1e3cbdebd294whp
  12:        0x10e50681f - dom::node::JSRef<'a, Node>.NodeMethods::AppendChild::hdecd87c1fae093c3oPp
  13:        0x10e50643e - dom::bindings::codegen::Bindings::NodeBinding::appendChild::__rust_abi
  14:        0x10e38f343 - dom::bindings::codegen::Bindings::NodeBinding::appendChild::h0c210702386b7a1bCPk
  15:        0x10f5febab - CallJitMethodOp
  16:        0x10e5089ea - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::__rust_abi
  17:        0x10e38ef27 - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::hd09def13dc7d8ac3FZk
  18:        0x10ead3f72 - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  19:        0x10eacdb5c - _ZN2js9InterpretEP9JSContextPNS_10StackFrameENS_10InterpModeE
  20:        0x10eac6086 - _ZN2js9RunScriptEP9JSContextP8JSScriptPNS_10StackFrameE
  21:        0x10ead4739 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeEPNS_10StackFrameEPS9_
  22:        0x10ead4874 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  23:        0x10ea5e03d - _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKtmPNS_5ValueE
  24:        0x10ea5e27c - JS_EvaluateUCScript
  25:        0x10e7c05c7 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::closure.94897
  26:        0x10e7c03e7 - rust::with_compartment::h14538346473171005238
  27:        0x10e7c0303 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::h8343629566505271552
  28:        0x10e7bf61f - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::execute::hb9a18f04689454c49Pk
  29:        0x10e7bc6fd - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::prepare::ha663be7e8d9a5b267Ik
  30:        0x10e7c3bc7 - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.VirtualMethods::bind_to_tree::hcfa535582be9e756H7k
  31:        0x10e7d92e0 - dom::node::JSRef<'a, Node>.PrivateNodeHelpers::node_inserted::hb191a42019f12daermo
  32:        0x10e7e7dcc - dom::node::Node::insert::fire_observer_if_necessary::h7c8b9e7d49076347Rpp
  33:        0x10e7e54be - dom::node::Node::insert::h1c8dfc24a21cb7aeiop
  34:        0x10e7e23ab - dom::node::Node::pre_insert::h0efc1e3cbdebd294whp
  35:        0x10e5060a0 - dom::node::JSRef<'a, Node>.NodeMethods::InsertBefore::h8d6f5ec89060a3b01Op
  36:        0x10e505c7d - dom::bindings::codegen::Bindings::NodeBinding::insertBefore::__rust_abi
  37:        0x10e38f2e3 - dom::bindings::codegen::Bindings::NodeBinding::insertBefore::h54de8a35b65a15a0sLk
  38:        0x10f5febab - CallJitMethodOp
  39:        0x10e5089ea - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::__rust_abi
  40:        0x10e38ef27 - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::hd09def13dc7d8ac3FZk
  41:        0x10ead3f72 - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  42:        0x10eacdb5c - _ZN2js9InterpretEP9JSContextPNS_10StackFrameENS_10InterpModeE
  43:        0x10eac6086 - _ZN2js9RunScriptEP9JSContextP8JSScriptPNS_10StackFrameE
  44:        0x10ead4739 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeEPNS_10StackFrameEPS9_
  45:        0x10ead4874 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  46:        0x10ea5e03d - _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKtmPNS_5ValueE
  47:        0x10ea5e27c - JS_EvaluateUCScript
  48:        0x10e7c05c7 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::closure.94897
  49:        0x10e7c03e7 - rust::with_compartment::h14538346473171005238
  50:        0x10e7c0303 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::h8343629566505271552
  51:        0x10e7bf61f - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::execute::hb9a18f04689454c49Pk
  52:        0x10e7bc6fd - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::prepare::ha663be7e8d9a5b267Ik
  53:        0x10e7c3bc7 - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.VirtualMethods::bind_to_tree::hcfa535582be9e756H7k
  54:        0x10e7d92e0 - dom::node::JSRef<'a, Node>.PrivateNodeHelpers::node_inserted::hb191a42019f12daermo
  55:        0x10e7e7dcc - dom::node::Node::insert::fire_observer_if_necessary::h7c8b9e7d49076347Rpp
  56:        0x10e7e54be - dom::node::Node::insert::h1c8dfc24a21cb7aeiop
  57:        0x10e7e23ab - dom::node::Node::pre_insert::h0efc1e3cbdebd294whp
  58:        0x10e5060a0 - dom::node::JSRef<'a, Node>.NodeMethods::InsertBefore::h8d6f5ec89060a3b01Op
  59:        0x10e505c7d - dom::bindings::codegen::Bindings::NodeBinding::insertBefore::__rust_abi
  60:        0x10e38f2e3 - dom::bindings::codegen::Bindings::NodeBinding::insertBefore::h54de8a35b65a15a0sLk
  61:        0x10f5febab - CallJitMethodOp
  62:        0x10e5089ea - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::__rust_abi
  63:        0x10e38ef27 - dom::bindings::codegen::Bindings::NodeBinding::genericMethod::hd09def13dc7d8ac3FZk
  64:        0x10ead3f72 - _ZN2js12InvokeKernelEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
  65:        0x10eacdb5c - _ZN2js9InterpretEP9JSContextPNS_10StackFrameENS_10InterpModeE
  66:        0x10eac6086 - _ZN2js9RunScriptEP9JSContextP8JSScriptPNS_10StackFrameE
  67:        0x10ead4739 - _ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeEPNS_10StackFrameEPS9_
  68:        0x10ead4874 - _ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
  69:        0x10ea5e03d - _ZN2JS8EvaluateEP9JSContextNS_6HandleIP8JSObjectEENS_14CompileOptionsEPKtmPNS_5ValueE
  70:        0x10ea5e27c - JS_EvaluateUCScript
  71:        0x10e7c05c7 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::closure.94897
  72:        0x10e7c03e7 - rust::with_compartment::h14538346473171005238
  73:        0x10e7c0303 - dom::window::JSRef<'a, T>.ScriptHelpers::evaluate_script_on_global_with_result::h8343629566505271552
  74:        0x10e7bf61f - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::execute::hb9a18f04689454c49Pk
  75:        0x10e7bc6fd - dom::htmlscriptelement::JSRef<'a, HTMLScriptElement>.HTMLScriptElementHelpers::prepare::ha663be7e8d9a5b267Ik
  76:        0x10e911359 - parse::html::servohtmlparser..Sink.TreeSink::complete_script::closure.98603
  77:        0x10e9112db - option::Option<T>::map::h4823584091535465418
  78:        0x10e82f878 - parse::html::servohtmlparser..Sink.TreeSink::complete_script::hcc9ad2586b58a3efHEw
  79:        0x10e8100ce - tree_builder::rules::super..TreeBuilder<Handle, Sink>.TreeBuilderStep::step::h15753392582135408227
  80:        0x10e8017bc - tree_builder::TreeBuilder<Handle, Sink>::process_to_completion::h17394548604650618013
  81:        0x10e8001ce - tree_builder::TreeBuilder<Handle, Sink>.TokenSink::process_token::h16838172824630258104
  82:        0x10e7ff3b2 - tokenizer::Tokenizer<Sink>::process_token::h4223826186911339883
  83:        0x10e8399a6 - tokenizer::Tokenizer<Sink>::emit_current_tag::h3743473990165524377
  84:        0x10e7f8874 - tokenizer::Tokenizer<Sink>::step::h5755909512975338631
  85:        0x10e7f5d3b - tokenizer::Tokenizer<Sink>::run::h4132648654899320302
  86:        0x10e7f5ad2 - tokenizer::Tokenizer<Sink>::feed::h615498099196617593
  87:        0x10e7f5934 - dom::servohtmlparser::ServoHTMLParser.Parser::parse_chunk::h6723cba5d45ce8b5fTq
  88:        0x10e911dc7 - parse::html::parse_html::parse_progress::h60e12c5a990aa1c3TNw
  89:        0x10e70f87a - parse::html::parse_html::heafd9576be5e06fdOMw
  90:        0x10e95f49a - script_task::ScriptTask::load::h7215b0af80196610Oay
  91:        0x10e95808b - script_task::ScriptTask::handle_page_fetch_complete::h90839fffb5ba8e4d46x
  92:        0x10e954d30 - script_task::ScriptTask::handle_msg_from_script::h98e13e7af95efd145Px
  93:        0x10e92eada - script_task::ScriptTask::handle_msgs::he2fe88569fb891518Fx
  94:        0x10e92d1b1 - script_task::ScriptTask::start::hfe80c4f5f38d008cYFx
  95:        0x10dbf0bee - script_task::ScriptTask.ScriptTaskFactory::create::closure.10864
  96:        0x10dbf0441 - task::spawn_named_with_send_on_failure::closure.10860
  97:        0x10dbf034b - thunk::Thunk<'a, (), R>::new::closure.10857
  98:        0x10dbf0246 - thunk::F.Invoke<A, R>::invoke::h2548772933537349105
  99:        0x10db6b840 - thunk::Thunk<'a, A, R>::invoke::h7736621623150784202
  100:        0x10db6c5a9 - thread::Builder::spawn_inner::closure.7148
 ... <frames omitted>
thread panicked while panicking. aborting.
Error running mach:

    ['run', 'http://slashdot.org/']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

CalledProcessError: Command '[u'components/servo/target/debug/servo', 'http://slashdot.org/']' returned non-zero exit status -4

  File "/tmp/servo/servo/python/servo/post_build_commands.py", line 117, in run
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
$ 
```

### PR DESCRIPTION
**Pull request by ghost**
Partially fixes #5504.

Props to @ehegnes and @jdm for the help!

### CODE REVIEW

**Comment by jdm** [comment]
I've left comments on the Critic review! Be sure to click the 'sign in' there so you get email updates in the future.

**Comment by jagtalon** [comment]
@jdm fixed up the issues!

**Comment by jdm** [comment]
Looks great! Go ahead and squash!

**Comment by jagtalon** [comment]
Sweet!

**Comment by jagtalon** [comment]
@jdm squashed!

**Pull request merged**
