### PR TITLE
Fix parent climb hierarchy in send_frame_tree

### LINKED ISSUE #17246: bhtml no longer showing navigation/url bar
Just built the latest Servo and noticed that we're not showing the bhtml chrome any more once you click on a link in the gallery:

screen shot 2017-06-09 at 11 17 21

### PR DESCRIPTION
**Pull request by cbrewster**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #17246 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17248)

### CODE REVIEW

**Comment by cbrewster** [comment]
Mozbrowser strikes again! Is it worth adding a reftest?
r? @asajeffrey

**Comment by jonathandturner** [comment]
@asajeffrey - this is a different fix than you recommended.  Same effect, I take it?

**Comment by cbrewster** [comment]
@jonathandturner yeah they behave the same. @asajeffrey's version sets `browsing_context_id` on every iteration, mine waits until we reach the top of the hierarchy to set it.

**Pull request merged**
