### PR TITLE
Change Response's statusText default value from 'Ok' to an empty string

### LINKED ISSUE #22238: Change Response's statusText default value
https://github.com/whatwg/fetch/pull/836

Instead of an `OK` default, it should be the empty string instead.

Code: https://github.com/servo/servo/blob/07e334ae55623518516ddae6d758cf7650142398/components/script/dom/webidls/Response.webidl#L30
Tests: `./mach test-wpt tests/wpt/web-platform-tests/fetch/api/response/response-init-001.html`

### PR DESCRIPTION
**Pull request by georgeroman**
Closes #22238 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22244)

### CODE REVIEW

**Comment by jdm** [comment]
If you rebase, the test should show different results now.

**Comment by nox** [comment]
Pretty sure this needs expectation changes.

**Comment by nox** [comment]
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Check Response's clone with default values, without body", "test": "/fetch/api/response/response-clone.html", "line": 71008, "action": "test_result", "expected": "FAIL"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": "Check default value for statusText attribute", "test": "/fetch/api/response/response-init-001.html", "line": 75363, "action": "test_result", "expected": "FAIL"}
```

**Comment by jdm** [comment]
The code that deals with blob responses in scheme_fetch will need to provide an OK value per https://fetch.spec.whatwg.org/#scheme-fetch .

**Comment by jdm** [comment]
@bors-servo retry
* #22295

**Pull request merged**
