### PR TITLE
Fixed some clippy warnings by replacing 'match' with 'if'

### PR DESCRIPTION
**Pull request by komutumu**
This PR fixes clippy warnings that arose from the use of 'match' with a suggestion to use 'if'.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes are part of #31500 
- [X] These changes do not require tests because it doesn't touch functionality.

### CODE REVIEW

**Comment by jahielkomu** [comment]
Hello @mrobinson 
Please kindly review and revert.

Please allow me ask;
```match``` provided an option that served as a default for any value that hadn't been explicitly matched by the preceding patterns using ```_ => {}``` however, in the elimination of that in favor of ``` if ``` no else block has been created since the default pattern was implementing nothing, so I ask won't this cause any kind of redundancy?

**Comment by eerii** [comment]
Hi @jahielkomu! As you said the issue with the `match` statements was that they only checked for one variant and didn't do anything for the others. That's why they can safely be converted into an `if let` that is equivalent. Because there was nothing done for the other variants, no `else` is needed in this case. This actually reduces redundancy as you don't need to explicitly handle all cases like before, just the one you care about.

**Comment by jahielkomu** [comment]
> Hi @jahielkomu! As you said the issue with the `match` statements was that they only checked for one variant and didn't do anything for the others. That's why they can safely be converted into an `if let` that is equivalent. Because there was nothing done for the other variants, no `else` is needed in this case. This actually reduces redundancy as you don't need to explicitly handle all cases like before, just the one you care about! :)

Yes, this makes sense...thanks @eerii. 
I think I meant unhandled cases but you rightly bring out the point that there is no need for concern.

**Comment by eerii** [comment]
Yes, in this case the unhandled cases are not doing anything so they can be omitted safely.

**Review by mrobinson — APPROVED** [review]

**Pull request merged**
