### PR TITLE
Allow multiple sequential webdriver sessions

### LINKED ISSUE #11253: Support webdriver sessions
At the moment we don't support multiple webdriver sessions.

cc @jgraham

### PR DESCRIPTION
**Pull request by asajeffrey**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [X] These changes fix #11253

Either:
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because the wdspec tests are in wpt/webdriver

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11306)

### CODE REVIEW

**Comment by asajeffrey** [comment]
r? jgraham

**Comment by asajeffrey** [comment]
@jgraham?

**Comment by jgraham** [comment]
The issue here is that I can't really tell if this is the desired behaviour to align with other implementations. @andreastt might have some insight.

**Comment by asajeffrey** [comment]
@jgraham this was my reading of the spec, but I don't know what the other implementations do.

**Comment by asajeffrey** [comment]
We either should land this or rewrite the servo wdspec driver in wptrunner to start up a fresh servo instance each time. At the moment we can only run 1 wdspec test!

**Comment by jgraham** [comment]
I think making the change in wptrunner is the right thing to do in the short term.

Sorry, I didn't realise you were so blocked on this.

**Comment by asajeffrey** [comment]
@jgraham ok I'll have a look at rewriting wptrunner to spawn a separate servo instance per test.

**Comment by andreastt** [comment]
@asajeffrey Sorry it took me so long to get around to this, but I was at a conference all of last week.

This patch looks mostly fine to me, except that we should navigate on creating- and deleting sessions.

<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> @jgraham ok I'll have a look at rewriting wptrunner to spawn a separate servo instance per test.
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/webdriver_server/lib.rs, line 286 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11306#-KJa3SggR8gh4J45TY1H:-KJa3SghdKKHayLnShcH:-650396388) ([raw file](https://github.com/servo/servo/blob/10caeadbc1e591d898843c1b8f54361306a44d81/components/webdriver_server/lib.rs#L286)):*
> ```Rust
>                     session.id.to_string(),
>                     Json::Object(capabilities))));
>             try!(self.handle_get(&GetParameters { url: String::from("about:blank") }));
> ```

Creating a new session should not change the current document.

---

*[components/webdriver_server/lib.rs, line 296 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11306#-KJa30wG-wP7rB-EWbkK:-KJa2uV3dhqcw-gHGmb7:1190737385) ([raw file](https://github.com/servo/servo/blob/10caeadbc1e591d898843c1b8f54361306a44d81/components/webdriver_server/lib.rs#L296)):*
> ```Rust
> 
>     fn handle_delete_session(&mut self) -> WebDriverResult<WebDriverResponse> {
>         try!(self.handle_get(&GetParameters { url: String::from("about:blank") }));
> ```

I don’t think you should change the current document when the session is deleted. The browser should be left in the state it was in.

In theory deleting a session should cause the browser process to quit and I can’t see this is handled here, but is probably outside the scope of this patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11306#-:-KJa3_Czj3XMSZccyDnA:1892445100)*

**Comment by andreastt** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11306)*

**Comment by asajeffrey** [comment]
@andreastt this PR is to allow one servo instance to handle multiple sequential sessions, without quitting when the session is closed. The current code base quits the servo instance when the session is terminated, if that's the behaviour that's desired we can just close this PR.

**Comment by andreastt** [comment]
@asajeffrey Yes, that is the desired behaviour and it’s a bug that Marionette/Firefox does not do this right now when calling _Delete Session_.

(I just pointed this out in https://github.com/mozilla/geckodriver/pull/70#issuecomment-223974034 too.)

**Comment by asajeffrey** [comment]
Closing this PR in favour of fixing the servo wdspec driver.

**Pull request closed without merging**
