### PR TITLE
Fix WebSocket test issues.

### PR DESCRIPTION
**Pull request by Ms2ger**
Second try.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6358)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Let's see if this passes...

@bors-servo: r=jgraham

**Comment by Ms2ger** [comment]
@larsbergstrom: didn't we fix the file descriptor issue on osx?

**Comment by larsbergstrom** [comment]
@Ms2ger hrm, this looks different - given that it's a port-related issue, I suspect this test got approved and started running at the same time I was doing a test run of the SM upgrade :-)

**Comment by jdm** [comment]
@bors-servo: retry
* #6394

**Pull request merged**
