### PR TITLE
Reenable "Use one Python virtual environment for all mach commands"

### PR DESCRIPTION
**Pull request by frewsxcv**
Address the issues brought up by https://github.com/servo/servo/pull/7103

The revert requires an upgrade to wptrunner (for the mozlog 3.0 compatibility) because the latest wptrunner depends on [this](https://github.com/w3c/wpt-tools/pull/27))

/cc @Ms2ger @metajack

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7117)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Ms2ger did a WPT upgrade today, so I just force pushed to remove the WPT upgrade I had in this PR (and rebase off master). Also, if anyone wants to see the changes, I recommend the "Split" view diff view (or just look at the previous PR)

**Comment by frewsxcv** [comment]
Rebased

**Comment by frewsxcv** [comment]
Rebased

**Comment by metajack** [comment]
Reviewed 23 of 23 files at r1, 51 of 51 files at r2, 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7117)

**Comment by frewsxcv** [comment]
test-wpt failure looks unrelated

test-css looks like some sort of issue with wptrunner. looking into it now

**Comment by frewsxcv** [comment]
I asked @jgraham about this on IRC and they mentioned that `tests/wpt/css-tests/tools/` might need to be updated to the latest `wpt-tools`. I just did that locally and can confirm that test-css works again. Where do I file this upstream? I'm not familiar with the CSS WPT test suite.

**Comment by metajack** [comment]
Do we need a wpt upgrade now?

**Comment by frewsxcv** [comment]
Yeah, I'll open a new PR for that soon

**Comment by frewsxcv** [comment]
WPT CSS update landed in https://github.com/servo/servo/issues/7505

I just rebased off master and `test-css` seems to work fine now, so this should be ready for a retry

**Comment by frewsxcv** [comment]
```
/XMLHttpRequest/send-authentication-basic-setrequestheader.htm
--------------------------------------------------------------
PASS expected FAIL XMLHttpRequest: send() - "Basic" authenticated request using setRequestHeader()
```

Oh, this now passes for some reason...

I guess I'll update the expectations then

**Comment by frewsxcv** [comment]
It seems as though updating some of these dependencies results in fixing #7113, which is good

**Comment by frewsxcv** [comment]
Expectations updated

**Pull request merged**
