### PR TITLE
Fixes trailing whitespaces and license errors in ports/cef

### PR DESCRIPTION
**Pull request by psdh**

### CODE REVIEW

**Comment by jdm** [comment]
@pcwalton What's the story on making these edits to files that are automatically generated by the CEF translation? Is it not worth running tidy against ports/cef?

**Comment by larsbergstrom** [comment]
@zmike, do you have opinions on jdm's question above?

**Comment by pcwalton** [comment]
So, I'm not a lawyer, but I don't think we are allowed to remove the license headers from CEF header files. They were present in the original and the license states that you must reproduce those headers. Regarding the trailing newlines, those files were generated with the translator tool and so the translator tool should be updated. See the `servo` branch here: https://github.com/pcwalton/chromium-embedded-framework

**Comment by jdm** [comment]
Ok, looks like this PR is not the way forward, in that case.

**Pull request closed without merging**
