### PR TITLE
style: Cleanup a bit Stylist and SelectorMap.

### PR DESCRIPTION
**Pull request by emilio**
Bug: 1390255
Reviewed-by: heycam

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18087)

### CODE REVIEW

**Comment by emilio** [comment]
(Forgot to push)

**Comment by emilio** [comment]
@bors-servo r=heycam

 * Unit tests

**Comment by jdm** [comment]
```
warning: unused macro definition
  --> /home/servo/buildbot/slave/linux-dev/build/tests/unit/stylo/sanity_checks.rs:13:1
   |
13 | / macro_rules! check_enum_value {
14 | |     ($a:expr, $b:expr) => {
15 | |         unsafe {
16 | |             mem::transmute::<[u32; $a as usize],
...  |
19 | |     }
20 | | }
   | |_^
   |
   = note: #[warn(unused_macros)] on by default

warning: unused macro definition
  --> /home/servo/buildbot/slave/linux-dev/build/tests/unit/stylo/sanity_checks.rs:24:1
   |
24 | / macro_rules! check_enum_value_non_static {
25 | |     ($a:expr, $b:expr) => {
26 | |         assert_eq!($a.0 as usize, $b as usize);
27 | |     }
28 | | }
   | |_^
   |
   = note: #[warn(unused_macros)] on by default

error[E0425]: cannot find value `Servo_StyleSet_Clear` in this scope
  --> /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/stylo_tests-a4d6c62a29deb877/out/check_bindings.rs:49:7
   |
49 |     [ Servo_StyleSet_Clear, bindings::Servo_StyleSet_Clear ];
   |       ^^^^^^^^^^^^^^^^^^^^ did you mean `Servo_StyleSet_Drop`?
   |
help: possible candidate is found in another module, you can import it into scope
   | use style::gecko_bindings::bindings::Servo_StyleSet_Clear;

error: aborting due to previous error(s)

error: Could not compile `stylo_tests`.
```

**Comment by emilio** [comment]
@bors-servo r=heycam 

 * bindings, sigh

**Comment by emilio** [comment]
(Thanks @jdm :))

**Comment by emilio** [comment]
@bors-servo r=heycam

 * Bors completely forgot this.

**Comment by emilio** [comment]
@bors-servo r=heycam

 * The rustc update uncovered a warning...

**Pull request merged**
