### PR TITLE
Refactor Error enum usage to consistently be qualified

### LINKED ISSUE #7869: Consistently use the Error enum instead of its constructors
Instead of:

```rust
use dom::bindings::error::Error::HierarchyRequest;
```

We want:

```rust
use dom::bindings::error::Error;
```

The places where the constructors are used unqualified obviously need to be fixed.

### PR DESCRIPTION
**Pull request by anthgur**
Closes #7869

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7882)

### CODE REVIEW

**Comment by Manishearth** [comment]
The comments refer to the Javascript error names, so most of them should stay as `FooError`

**Comment by Manishearth** [comment]
Thanks for the pull request!

Looks good to me, just a couple of nits about error names in comments and you should be good to go!

**Comment by anthgur** [comment]
@Manishearth awesome, that makes sense, thanks for the feedback!

**Comment by anthgur** [comment]
I'm going to rebase this to remove the comment change noise.

**Comment by Ms2ger** [comment]
Thanks you! I have one nit remaining.

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 953 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7882#-K-wKMabbNZRhZ0o4s8C)** ([raw file](https://github.com/servo/servo/blob/517ee9f5dd18b3da0cf7b921a713d846d616fb35/components/script/dom/canvasrenderingcontext2d.rs#L953)):</sup>
Just "InvalidStateError" here, please.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7882)

**Comment by nox** [comment]
@bors-servo r=Ms2ger


---

Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7882)

**Pull request merged**
