### PR TITLE
Fix 5120 rename layout util

### PR DESCRIPTION
**Pull request by iamdanfox**
A simple rename/refactor (https://github.com/servo/servo/issues/5120)

My first servo contribution!

### CODE REVIEW

**Comment by pcwalton** [comment]
Why not just `data.rs` instead of `layout_data.rs`? `layout/layout_data.rs` repeats the name `layout`.

**Comment by iamdanfox** [comment]
Done.

Now that `mod util` is gone, we could also get rid of the `extern crate "util" as servo_util;` renaming that @metajack spotted.  Does that make the diff to long for one PR or shall I just jam it in?

**Comment by pcwalton** [comment]
Needs a rebase now

**Comment by jdm** [comment]
Feel free to get rid of the servo_util rename too!

**Comment by iamdanfox** [comment]
I think this PR is pretty much done: `util.rs` has been split up and we don't have the `servo_util` renaming anymore.

I didn't re-sort any of the import lists for fear of causing hundreds of merge conflicts (see [layout_task.rs][1]) - hope this is ok!

[1]:https://github.com/iamdanfox/servo/blob/fix-5120-rename-layout-util/components/layout/layout_task.rs#L56-L65

**Comment by jdm** [comment]
Thanks!

**Pull request merged**
