### PR TITLE
add `unwrap` to `send/recv` calls

### LINKED ISSUE #4744: Audit send()/recv() calls.
We lost a lot of error handling in #4719. We should restore it.

### PR DESCRIPTION
**Pull request by xojoc**
Fixes #4744

### CODE REVIEW

**Comment by Ms2ger** [comment]
```
image_cache_task.rs:426:44: 426:52 error: type `()` does not implement any method in scope named `unwrap`
image_cache_task.rs:426         self.send(Msg::WaitForStore(chan)).unwrap();
```
@xojoc, could you fix that and maybe run `./mach test-unit`?

**Comment by Ms2ger** [comment]
@xojoc: thanks! Could you squash the commits?

**Comment by xojoc** [comment]
It's the first time I'm doing this, following: https://github.com/servo/servo/wiki/Github-&-Critic-PR-handling-101. Please tell me if I didn't do something correctly.

**Comment by jdm** [comment]
Uh oh, that definitely didn't turn out correctly. I recommend resetting your branch to the same as master, then cherry-picming your commit (466857224fb626b13e528d9ac6fc2d3548c81ac6) on top of that.

**Pull request closed without merging**
