### PR TITLE
Update WR (windows font fixes, ridge/groove borders, scrolling improvements).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14668)

### CODE REVIEW

**Comment by glennw** [comment]
@bors-servo retry
 * #14162
 * #14247

**Comment by glennw** [comment]
r? anyone

**Comment by KiChjang** [comment]
@bors-servo retry
* Actual commit is different?!?!?!

**Comment by glennw** [comment]
@bors-servo r=jdm
 * infra?

**Comment by jdm** [comment]
@bors-servo: retry
* perhaps time has fixed it

**Comment by KiChjang** [comment]
@bors-servo retry
* servo/saltfs#565

**Pull request merged**
