### PR TITLE
Compute and upload nightly package checksum files

### PR DESCRIPTION
**Pull request by aneeshusa**
This will require a companion PR to servo/download.servo.org to add links to the checksum files from the main page.

---

- [ ] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes help with servo/download.servo.org#14 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16540)

### CODE REVIEW

**Comment by aneeshusa** [comment]
This will need to be redone after #16565.

**Comment by sviter** [comment]
#16565 has been merged

**Comment by jdm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
