### PR TITLE
Use kwargs in mako to reduce all the parameters

### PR DESCRIPTION
**Pull request by bholley**
This should keep things more manageable.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10627)

### CODE REVIEW

**Comment by bholley** [comment]
Wait, something isn't quite right here - I'll investigate after dinner.

**Comment by bholley** [comment]
Ok fixed - I've now verified that the generated code does not change at all with these patches. Should be ready for review.

**Comment by SimonSapin** [comment]
This is much nicer, thanks!

r=me with some Python simplifications noted inline.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/style/properties.mako.rs, line 87 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10627#-KFPArQGum0FMJL6rWYW:-KFPArQGum0FMJL6rWYX:650020630) ([raw file](https://github.com/servo/servo/blob/e415e790027586dbf080d98977a5cdbbfff07389/components/style/properties.mako.rs#L87)):*
This can be `self.derived_from = (derived_from or "").split()`

---

*[components/style/properties.mako.rs, line 182 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10627#-KFPB8YX_O1A9YD5Cdea:-KFPB8YX_O1A9YD5Cdeb:1912646409) ([raw file](https://github.com/servo/servo/blob/e415e790027586dbf080d98977a5cdbbfff07389/components/style/properties.mako.rs#L182)):*
I think these two lines can be `products = kwargs.pop("products", "gecko,servo")`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10627#-:-KFPCEJVn3-xRhmsJoNv:1580413137)*

**Comment by bholley** [comment]
Thanks for the review!

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10627#-:-KFPtV9XpVVOIMwBVbLP:-588504495)*

**Pull request merged**
