### PR TITLE
Implement <hr> 'color' attribute

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8419)

### CODE REVIEW

**Comment by eefriedman** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/script/dom/htmlhrelement.rs, line 51 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8419#-K2dKgXD6FtaB06qbjaO)** ([raw file](https://github.com/servo/servo/blob/b94f29f003d0e3d12b81bfa85a9697aa34240fb0/components/script/dom/htmlhrelement.rs#L51)):</sup>
`impl HTMLHRLayoutHelpers for LayoutJS<HTMLHRElement>` etc.


---

<sup>**[components/script/dom/htmlhrelement.rs, line 73 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8419#-K2dKtjgKm21rLHD73vn)** ([raw file](https://github.com/servo/servo/blob/b94f29f003d0e3d12b81bfa85a9697aa34240fb0/components/script/dom/htmlhrelement.rs#L73)):</sup>
`AttrValue::from_legacy_color()`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8419)

**Comment by frewsxcv** [comment]
Comments have been addressed

**Comment by frewsxcv** [comment]
@bors-servo retry

https://github.com/servo/servo/issues/8416

**Pull request merged**
