### PR TITLE
Use euclid from crates.io

### PR DESCRIPTION
**Pull request by emilio**
Sorry for not doing it yesterday, I couldn't.

cc @metajack @SimonSapin

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6423)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 104 of 104 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6423)

**Comment by metajack** [comment]
@ecoal95 The build failed:
```
/home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-49a578ae84e64b98/master/src/platform/with_egl/native_gl_context.rs:122:22: 122:41 error: mismatched types:
 expected `*mut libc::types::common::c95::c_void`,
    found `*const libc::types::common::c95::c_void`
(values differ in mutability) [E0308]
/home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-49a578ae84e64b98/master/src/platform/with_egl/native_gl_context.rs:122             display: self.native_display                                                                                                                                                              ^~~~~~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-49a578ae84e64b98/master/src/platform/with_egl/native_gl_context.rs:122:22: 122:41 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `offscreen_gl_context`.
```

**Comment by ecoal95** [comment]
Dang it, I couldn't cross-compile with the layers feature because of #6384, I assumed it was ok.

Give me a second.

**Comment by ecoal95** [comment]
@metajack Should be good to go, hopefully (https://github.com/ecoal95/rust-offscreen-rendering-context/commit/d7df284c19993b0187c76c31ca15b613f86aecf4)

**Comment by metajack** [comment]
@bors-servo r+

-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 104 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6423)

**Comment by ecoal95** [comment]
Since it failed again, I went back to https://github.com/ecoal95/rust-offscreen-rendering-context/commit/e79da8f61ad468087beb546bca4d7267b77edd9f

I think I'll try to update layers to use automatic bindings as suggested in a egl-rs commit by @glennw to fix the issue, and if that's not an option I'll go back to use egl-rs as `layers` does.

**Comment by SimonSapin** [comment]
Yay! Thanks for the PR @ecoal95

**Pull request merged**
