### PR TITLE
 Use workspace.default-members to specify default crates for cargo build

### PR DESCRIPTION
**Pull request by SimonSapin**
… and 'cargo test', etc. Include Servo and its unit tests, but not Stylo because that would try to compile the style crate with incompatible feature flags: https://github.com/rust-lang/cargo/issues/4463

`workspace.default-members` was added in https://github.com/rust-lang/cargo/pull/4743. Older Cargo versions ignore it.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19476)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: treeclosed=9000
Going to try restarting buildbot on a couple builders.

**Comment by SimonSapin** [comment]
Rebased without conflict. (Maybe GitHub uses a different automatic conflict resolution algorithm than my git client?)

@bors-servo r=nox

**Comment by jdm** [comment]
@bors-servo: retry
* "couldn't compile style"?

**Comment by SimonSapin** [comment]
That means the rustc process terminated with a non-zero (unsuccessful) exit code. However there is no error message from rustc. Maybe rustc segfaulted? I can’t reproduce though :/ Let’s see if it happens reliably.

@bors-servo retry

(Note that this PR includes a compiler upgrade.)

**Comment by SimonSapin** [comment]
(I just pushed a change (`python/**` in the last commit) to hopefully fix the `./mach build-geckolib` failure that was shown on Travis-CI. But that’s probably unrelated to the `./mach build` failure on Buildbot, about which I have no idea at this point.)

**Comment by jdm** [comment]
You may want to investigate on one of the build machines.

**Comment by SimonSapin** [comment]
Ah, I’ve managed to reproduce: this failure only happens when compiling in release mode. (I previously tested debug because compile times.) Passing `-v` to Cargo is informative:

```
  process didn't exit successfully: `rustc --crate-name style […]` (signal: 8, SIGFPE: erroneous arithmetic operation)
```

I’ve filed https://github.com/rust-lang/rust/issues/46519

**Comment by SimonSapin** [comment]
Upgraded the compiler again to pick up https://github.com/rust-lang/rust/pull/46521, no other change.

@bors-servo r=nox

**Comment by SimonSapin** [comment]
```
--- stderr
error: Connection to server timed out
make[2]: *** [CMakeFiles/ogg.dir/gecko/src/media/libogg/src/ogg_alloc.c.o] Error 2
make[1]: *** [CMakeFiles/ogg.dir/all] Error 2
make: *** [all] Error 2
```

I also get this when running `./mach test-unit` on my machine:

```
rustdoc: Option 'document-private-items' given more than once
```

**Comment by SimonSapin** [comment]
Added:

```diff
--- a/python/servo/testing_commands.py
+++ b/python/servo/testing_commands.py
@@ -254,6 +254,9 @@ class MachCommands(CommandBase):
         env = self.build_env()
         env["RUST_BACKTRACE"] = "1"
 
+        # Work around https://github.com/rust-lang/cargo/issues/4790
+        del env["RUSTDOCFLAGS"]
+
         if "msvc" in host_triple():
             # on MSVC, we need some DLLs in the path. They were copied
             # in to the servo.exe build dir, so just point PATH to that.
```

Maybe the "server timed out" was flaky network?

@bors-servo r=nox

**Pull request merged**
