### PR TITLE
Trim header values in GetResponseHeader

### LINKED ISSUE #24917: Trailing whitespace in XHR response headers is exposed
WPT test xhr/headers-normalize-response asks the server to send back a custom header ending in a space or tab, and unexpectedly can see that trailing space or tab in the returned header. I don't know which code is responsible: this may need a call on whether to strip immediately when storing the headers from the network HTTP response, or to keep the spaces/tabs at that time and strip them when returning them to Javascript getResponseHeader.

Regarding WPT results, Firefox and Safari pass these subtests and fail different subtests which Servo does pass (Servo's doing the right thing on NUL bytes).

### PR DESCRIPTION
**Pull request by Eijebong**
Fixes #24917

### CODE REVIEW

**Comment by jdm** [comment]
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: expected (string) \"\u00e2\u0080\u00a6\" but got (object) null", 
    "stack": "client.onreadystatechange/<@http://web-platform.test:8000/xhr/getresponseheader-special-characters.htm:20:15\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25\nclient.onreadystatechange@http://web-platform.test:8000/xhr/getresponseheader-special-characters.htm:16:16\n", 
    "subtest": "XMLHttpRequest: getResponseHeader() funny characters", 
    "test": "/xhr/getresponseheader-special-characters.htm", 
    "line": 79435, 
    "action": "test_result", 
    "expected": "PASS"
}

{
    "status": "FAIL", 
    "group": "default", 
    "message": "assert_equals: x-custom-header-bytes expected (string) \"\u00e2\u0080\u00a6\" but got (object) null", 
    "stack": "check_response_header/<@http://web-platform.test:8000/cors/response-headers.htm:27:13\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1984:25\ntest@http://web-platform.test:8000/resources/testharness.js:548:30\ncheck_response_header@http://web-platform.test:8000/cors/response-headers.htm:19:5\n@http://web-platform.test:8000/cors/response-headers.htm:34:1\n", 
    "subtest": "getResponseHeader: x-custom-header bytes", 
    "test": "/cors/response-headers.htm", 
    "line": 107030, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Comment by Eijebong** [comment]
Fun... Looks like `HeaderValue::to_str` rejects those fun names. I guess I'l do `str::from_utf8` instead

**Comment by Eijebong** [comment]
Unrelated:
```
{
    "status": "FAIL", 
    "group": "default", 
    "message": "/css/CSS2/cascade/html-attribute-009.xht 54a9df64f1476dd12020019d7cf22ac34d727bc0\n/css/CSS2/reference/filler-text-below-green.xht 268d9d413cb04490f99e4dd283264e467efc5fc1", 
    "stack": null, 
    "subtest": null, 
    "test": "/css/CSS2/cascade/html-attribute-009.xht", 
    "line": 1331, 
    "action": "test_result", 
    "expected": "PASS"
}
```

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Pull request merged**
