### PR TITLE
Update js.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10710)

### CODE REVIEW

**Comment by asajeffrey** [comment]
It looks like the changes are:

* the js github hash
* moving stuff out of unsafe blocks

Did I miss anything?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10710#-:-KFkqB6w4DEpMSjuivLx:1990320240)*

**Comment by KiChjang** [comment]
Actually, it's moving stuff INTO unsafe boxes.

**Comment by asajeffrey** [comment]
Oh my goodness, there's one extra `unsafe` right up at the top, all those `unsafe`s aren't actually being removed.

Making code more unsafe seems like not the direction we should be moving in. Is there some context I'm missing?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10710#-:-KFlKFRcWvv2SGc8MPNQ:1843107902)*

**Comment by KiChjang** [comment]
Yes, the `Runtime::new()` fn now is marked as unsafe, so everything is a big blob of unsafe now.

**Comment by asajeffrey** [comment]
Maybe `new_rt_and_cx` should be marked as unsafe?

**Comment by nox** [comment]
@asajeffrey Yes, anything that calls `Runtime::new` should be unsafe.

**Comment by Ms2ger** [comment]
Done.

r? @nox

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 3 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10710#-:-KFsG8iaqGYQMIn1SR6D:1236647940)*

**Pull request merged**
