### PR TITLE
constellation: Don't ignore inconsistent frame-tree states when determining when to take a screenshot.

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Return a significative error instead.

I think this is the cause of most iframe-related intermittents: we stop
iterating early, so we don't detect frames that aren't closed now.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11739)

### CODE REVIEW

**Comment by emilio** [comment]
I plan to do a few try runs to see if this fixes any intermittent. Let's see.

r? @asajeffrey 

@bors-servo: try

**Comment by emilio** [comment]
@bors-servo: retry

 * Weird mac directory not empty errors... Not sure if it'd be fixed retrying.

**Comment by emilio** [comment]
The initial code was incorrect (we already weren't bailing out, and I don't know how to read code). This code returns a `ReadyToSave::InconsistentFrameTreeState` if we find an unexpected pipeline missing. 

I'm curious to see if this ever causes a timeout.

@bors-servo: try

 * Previous failure was git things.

**Comment by jdm** [comment]
@bors-servo: retry
* mac folder not empty

**Comment by jdm** [comment]
@bors-servo: retry
* git timeout

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * mac folder not empty

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * mac folder not empty

**Comment by KiChjang** [comment]
@bors-servo retry
* The annoying git

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * git

**Comment by larsbergstrom** [comment]
@bors-servo retry
- git

**Comment by ConnorGBrewster** [comment]
@emilio @asajeffrey any news on this?

**Comment by emilio** [comment]
@ConnorGBrewster I think this would need a few more try runs to ensure it indeed fixes iframes' incremental layout bugs.

Appart from that, I think it's worth to have it since it avoids an extra hash table lookup in the pipelines map, though I'm not sure if that's good enough to merge this.

@bors-servo: try

**Comment by emilio** [comment]
Ahh, merges... I'm rebasing this now.

**Comment by ConnorGBrewster** [comment]
Tidy:
```
./components/constellation/constellation.rs:1527: Line is longer than 120 characters
```

**Comment by emilio** [comment]
@bors-servo: try

Sorry for the spam :/

**Comment by ConnorGBrewster** [comment]
Which intermittents is this after?

**Comment by asajeffrey** [comment]
Sorry about the delay, this was a casualty of MozLondon.

I'm going to echo @ConnorGBrewster: can you say which intermittents this will fix? Looking through the code, I can't see what behaviour will be different, since the only difference is when the already-closed frames are filtered out. Currently they're filtered out by the iterator, with your patch they're filtered out by the consumer of the iterator. I may be missing something, can you give us a scenario where there's a difference?

**Comment by emilio** [comment]
Yes, so the point is to try tackling the intermittents where we have iframes that render nothing, presumably because we take the screenshot too early.

And yes, *almost* everything is getting refiltered as before, except...

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/constellation/constellation.rs, line 1864 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11739#-KL3SbxZACBzqGpduudF:-KL3SbxZACBzqGpduudG:1212008436) ([raw file](https://github.com/servo/servo/blob/09866e39ad7dc242df794606b279ce41581dd834/components/constellation/constellation.rs#L1864)):*
> ```Rust
>                 FrameTreeIteratorItem::PipelineNotFound(frame_id, frame) => {
>                     warn!("Pipeline {:?} for frame {:?} not found", frame.current, frame_id);
>                     return ReadyToSave::InconsistentFrameTreeState;
> ```

These lines, where instead of skipping the frames and assuming everything is ok, we return a state that isn't `ReadyToSave::Ready`, so we don't take the screenshot yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11739#-:-KL3SEw4diz46KYej55m:691530997)*

**Comment by asajeffrey** [comment]
Ah,  I see.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/constellation/constellation.rs, line 261 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11739#-KLIONrFeahg7yDJRbCi:-KLIONrFeahg7yDJRbCj:-42972310) ([raw file](https://github.com/servo/servo/blob/09866e39ad7dc242df794606b279ce41581dd834/components/constellation/constellation.rs#L261)):*
> ```Rust
> }
> 
> enum FrameTreeIteratorItem<'a> {
> ```

Rather than a whole new type, it might be better to use `Result<&'a Frame, ()>`? (Or some other error type if you prefer.)

Or leave `FrameTreeIterator` alone, and add a recursive method that checks to make sure all frame lookups succeed? (We're into code readability here, not issues about correctness / efficiency.)

---

*[components/constellation/constellation.rs, line 1864 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11739#-KL3SbxZACBzqGpduudF:-KLIOICM9Y7QXpPJ9ES4:796148481) ([raw file](https://github.com/servo/servo/blob/09866e39ad7dc242df794606b279ce41581dd834/components/constellation/constellation.rs#L1864)):*
<details><summary><i>Previously, emilio (Emilio Cobos Álvarez) wrote…</i></summary>
> These lines, where instead of skipping the frames and assuming everything is ok, we return a state that isn't `ReadyToSave::Ready`, so we don't take the screenshot yet.
</details>
Ah, I see the idea now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11739#-:-KLIOlcjOTB57XXxIX59:1479211346)*

**Comment by jdm** [comment]
It may be worth reenabling #10760 with this change, as that was seen to be a blank iframe.

**Comment by emilio** [comment]
@jdm: agreed, will do on my next push.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/constellation/constellation.rs, line 261 \[r4\]](https://reviewable.io:443/reviews/servo/servo/11739#-KLIONrFeahg7yDJRbCi:-KLJauX56tRdpdCOZ6Oe:1098075227) ([raw file](https://github.com/servo/servo/blob/09866e39ad7dc242df794606b279ce41581dd834/components/constellation/constellation.rs#L261)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Rather than a whole new type, it might be better to use `Result<&'a Frame, ()>`? (Or some other error type if you prefer.)
> 
> Or leave `FrameTreeIterator` alone, and add a recursive method that checks to make sure all frame lookups succeed? (We're into code readability here, not issues about correctness / efficiency.)
</details>
What about adding a filter over this iterator, that just yields the `(pipeline, frame)` pair? So we would have a method like `infallible_frame_tree_iter()` or something, that filters over this one to yield a more convenient value when you just don't care about the inconsistent frame tree states.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11739#-:-KLJbQ9kBEkkX0jVcdbs:734229899)*

**Comment by emilio** [comment]
Refactored it, I think it's more legible now, and also re-enabled `sslfail.html`.

Also fixed a bug on `revoke_paint_permission` in which we'll accidentally revoke paint permission to all the pipelines associated to a frame.

re-r? @asajeffrey 

@bors-servo: try

**Comment by ConnorGBrewster** [comment]
The reftest still shows `/_mozilla/mozilla/sslfail.html` as a blank iframe :(

**Comment by emilio** [comment]
Yup, I should arguably hide myself :/

Anyway, I think part of these changes are good to land, at least since they ignore the extra pipeline lookup, and the error handling associated with it, and also it fixes the bug of us calling `revoke_paint_permission` on everything.

I'd like feedback from @asajeffrey before keeping working on it though.

**Comment by asajeffrey** [comment]
I'm flying to NYC at the moment, I'll comment when I arrive!

**Comment by asajeffrey** [comment]
Oops, dropped the ball on this one.

How about if we restore `FrameTreeIterator` back to the way it was, but add a `FrameIdTreeIterator` which iterates through the `FrameId`s rather than the `Frame`s? Then the code that cares about lookup failures can do the frameid lookup themselves.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11739#-:-KMPSMrP6LvGdZTgI1YS:2064254347)*

**Comment by asajeffrey** [comment]
@emilio is this still active?

**Comment by emilio** [comment]
I need to find more time to work on it, closing in the meantime since it's not super hi-pri.

**Comment by asajeffrey** [comment]
OK, cc me if you submit a new PR!

**Pull request closed without merging**
