### PR TITLE
Added wpt tests for same-origin iframe parentage.

### PR DESCRIPTION
**Pull request by asajeffrey**
Added some wpt tests to make sure same-origin iframes have the right parentage.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11476)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> r? @jdm 
</details>


---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 3 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ204H6stptV0ocSfLn:-KJ204H6stptV0ocSfLo:2108702656) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L3)):*
> ```JavaScript
> function get_test_results(id) {
>     async_test(function(test) {
>         var timer = window.setInterval(loop, 100);
> ```

`setInterval(test.step_func(loop), 100)`

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 6 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ22-Wx2XoCU4QF-XGH:-KJ22-Wx2XoCU4QF-XGI:-1069257620) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L6)):*
> ```JavaScript
> 	function loop() {
> 	    var xhr = new XMLHttpRequest();
> 	    xhr.open('GET', '/_mozilla/mozilla/iframe/stash.py?id=' + id);
> ```

I this this can be 'stash.py' without any path.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 16 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ2-adMG3hoSc6QTY9Y:-KJ2-adNxN787pSEgsC0:2022793018) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L16)):*
> ```JavaScript
> 	    });
> 	    xhr.send();
> 	}
> ```

nit: remove the tabs in this file.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 24 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ2-mqAPQHriL1iYjTl:-KJ2-mqAPQHriL1iYjTm:-344687178) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L24)):*
> ```JavaScript
>     for (result in results) { ok = ok && results[result]; }
>     var xhr = new XMLHttpRequest();
>     xhr.open('POST', '/_mozilla/mozilla/iframe/stash.py?id=' + results.id);
> ```

We should be able to use 'stash.py' without any explicit path.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 24 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20r1yR_cLFkOlV5e4:-KJ20r1yR_cLFkOlV5e5:-1376884966) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L24)):*
> ```JavaScript
>     for (result in results) { ok = ok && results[result]; }
>     var xhr = new XMLHttpRequest();
>     xhr.open('POST', '/_mozilla/mozilla/iframe/stash.py?id=' + results.id);
> ```

If we make this a synchronous XHR we don't need the looping timer.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 25 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ2-jF-WshZZbNn0QBc:-KJ2-jF-WshZZbNn0QBd:-2076570491) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L25)):*
> ```JavaScript
>     var xhr = new XMLHttpRequest();
>     xhr.open('POST', '/_mozilla/mozilla/iframe/stash.py?id=' + results.id);
>     xhr.send(ok? "OK": "FAIL: " + JSON.stringify(results));;
> ```

nit: remove the extra ; and add a space before ?

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_child.html, line 9 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20gq86gc8rVrhVEu0:-KJ20gq86gc8rVrhVEu1:569378138) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_child.html#L9)):*
> ```HTML
>         "id": '08782f28-e313-47ae-8cd7-419f3e194b0a',
> 	"parent": window.parent != window,
> 	"grandparent": window.parent.parent == window.parent,
> ```

Should these be ===?

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_child.html, line 10 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20NwPXTM4WjbX20pk:-KJ20NwPXTM4WjbX20pl:2042555288) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_child.html#L10)):*
> ```HTML
> 	"parent": window.parent != window,
> 	"grandparent": window.parent.parent == window.parent,
> 	"top": window.top == window.parent,
> ```

nit: tabs

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_grandchild.html, line 9 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20laE__y9fXyleUiE:-KJ20laE__y9fXyleUiF:2042555288) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_grandchild.html#L9)):*
> ```HTML
> 	"parent": window.parent != window,
> 	"grandparent": window.parent.parent != window.parent,
> 	"top": window.top == window.parent.parent,
> ```

nit: tabs

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ22ifbeTH6kwV3nWxp:-KJ22ifbeTH6kwV3nWxq:1911632413) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html#L13)):*
> ```HTML
>     get_test_results('17381dae-9c3e-4661-9f2b-28eb07a5f2fc');
>     get_test_results('08782f28-e313-47ae-8cd7-419f3e194b0a');
>     get_test_results('66de8d44-7da7-47c7-9a52-41cba4f22bfe');
> ```

These should be in an onload handler for the iframe.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20ZRDIdOTUmynNEN6:-KJ20ZREtT84H9tHXahT:2042555288) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html#L17)):*
> ```HTML
>         "id": '17381dae-9c3e-4661-9f2b-28eb07a5f2fc',
> 	"parent": window.parent == window,
> 	"top": window.top == window,
> ```

nit: tabs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11476#-:-KJ22pUhQo-Bk-HuoPP3:1458266033)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 3 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ204H6stptV0ocSfLn:-KJ6Iaj807a-QTzRw_if:-499146009) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L3)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> `setInterval(test.step_func(loop), 100)`
</details>
Done.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 6 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ22-Wx2XoCU4QF-XGH:-KJ6Ic2phyzYwLe-qhu7:-499146009) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L6)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> I this this can be 'stash.py' without any path.
</details>
Done.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 16 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ2-adMG3hoSc6QTY9Y:-KJ6InUveoNLnjse0UcV:-655769881) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L16)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> nit: remove the tabs in this file.
</details>
Done. Grr, emacs.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 24 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ2-mqAPQHriL1iYjTl:-KJ6Ir-EmKqpqsdVyLxr:-499146009) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L24)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> We should be able to use 'stash.py' without any explicit path.
</details>
Done.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 24 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20r1yR_cLFkOlV5e4:-KJ6IwuoocQ-B9ZtPRxy:-2142256920) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L24)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> If we make this a synchronous XHR we don't need the looping timer.
</details>
True, but I prefer async code where possible.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js, line 25 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ2-jF-WshZZbNn0QBc:-KJ6J9lYU7gUVFRK3sQa:-499146009) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/iframe_harness.js#L25)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> nit: remove the extra ; and add a space before ?
</details>
Done.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_child.html, line 9 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20gq86gc8rVrhVEu0:-KJ6JoEv_UK6En0cd7Yq:-499146009) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_child.html#L9)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> Should these be ===?
</details>
Done.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_child.html, line 10 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20NwPXTM4WjbX20pk:-KJ6JpHlcutkYDdNwyZU:-499146009) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_child.html#L10)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> nit: tabs
</details>
Done.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_grandchild.html, line 9 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20laE__y9fXyleUiE:-KJ6Jr1QO3TRkFnEyT5m:-499146009) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_grandchild.html#L9)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> nit: tabs
</details>
Done.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ22ifbeTH6kwV3nWxp:-KJ6JwM56TyZHlbM9Saz:606745701) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html#L13)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> These should be in an onload handler for the iframe.
</details>
Should they? We're polling `stash.py` anyway, checking a bit early doesn't actually cause any problems does it?

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ20ZRDIdOTUmynNEN6:-KJ6KAHkQqSrMHHU1a99:-499146009) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html#L17)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> nit: tabs
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11476)*

**Comment by jdm** [comment]
-S-awaiting-review 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ22ifbeTH6kwV3nWxp:-KJ6j9OQK8MmvGj-vTej:-775372554) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html#L13)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Should they? We're polling `stash.py` anyway, checking a bit early doesn't actually cause any problems does it?
</details>
This suggestion was based on the premise that sync XHR would be in use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11476#-:-KJ6jNMa-E3mAX0GPueK:879583689)*

**Comment by asajeffrey** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11476#-KJ22ifbeTH6kwV3nWxp:-KJ6nYzgbgHS8I7DwJjU:-1980321004) ([raw file](https://github.com/servo/servo/blob/49b0d6d25c85300f1163fa4558caeedef6f1c65d/tests/wpt/mozilla/tests/mozilla/iframe/same_origin_parentage.html#L13)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> This suggestion was based on the premise that sync XHR would be in use.
</details>
Ah I see, all the more reason to use async XHR :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11476)*

**Comment by asajeffrey** [comment]
Squashed.

**Comment by jdm** [comment]
@bors-servo: r+

<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Squashed.
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11476#-:-KJH-GgmCZRY69yW7ke2:-317921516)*

**Comment by asajeffrey** [comment]
@bors-servo retry

* #11563

**Pull request merged**
