### PR TITLE
Issue #10441: Added caching support to mach bootstrap

### PR DESCRIPTION
**Pull request by autrilla**
As suggested on the issue, files are stored as `.part` and moved to the original name when done.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10442)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
This looks great! Just a few nits.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[python/servo/bootstrap_commands.py, line 32 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10442#-KEjPAvdByiEOgpzf0W3:-KEjPAvdByiEOgpzf0W4:-2044529256) ([raw file](https://github.com/servo/servo/blob/bf5a51e189ec5c666e38dea394ceb3cf377093bd/python/servo/bootstrap_commands.py#L32)):*
Nit: `start_byte` would be meaningful?

---

*[python/servo/bootstrap_commands.py, line 34 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10442#-KEjP6-hNKtDbg-ih5bq:-KEjP6-i6QN7b5rxPDEA:1868333676) ([raw file](https://github.com/servo/servo/blob/bf5a51e189ec5c666e38dea394ceb3cf377093bd/python/servo/bootstrap_commands.py#L34)):*
Nit: `"Resuming download: %s..."` or `"Resuming download of %s..."`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10442#-:-KEjLjkckbRcvKqIWiWj:447544346)*

**Comment by autrilla** [comment]
That makes sense, I went ahead and made those changes. Should I squash the commits?

**Comment by Wafflespeanut** [comment]
Yes, and we'll land this :)

**Comment by Wafflespeanut** [comment]
Thanks for doing this :)

@bors-servo r+

**Pull request merged**
