### PR TITLE
Sanitise web fonts

### LINKED ISSUE #3030: Sanitize web fonts
For security purposes we should do that. (Or long-term rewrite the parser in Rust.)

### PR DESCRIPTION
**Pull request by nox**
Fixes #3030. Original work by @kmcallister.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7634)

### CODE REVIEW

**Comment by jdm** [comment]
```
+ ./configure --with-zlib=/home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/fontsan-d3cbc03c2b9e68ec/out/fake-zlib-install CFLAGS=-fPIC -include /home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/fontsan-d3cbc03c2b9e68ec/out/fake-zlib-install/include/zlib.h CXXFLAGS=-fPIC -include /home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/fontsan-d3cbc03c2b9e68ec/out/fake-zlib-install/include/zlib.h LDFLAGS=-L /home/servo/buildbot/slave/gonk/build/target/arm-linux-androideabi/debug/build/fontsan-d3cbc03c2b9e68ec/out/fake-zlib-install/lib
configure: error: in `/home/servo/.cargo/git/checkouts/fontsan-0cbd0044c518b5ef/master/ots':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
thread '<main>' panicked at 'assertion failed: Command::new("./scripts/build-ots.sh").status().unwrap().success()', /home/servo/.cargo/git/checkouts/fontsan-0cbd0044c518b5ef/master/build.rs:9
```

**Comment by nox** [comment]
https://github.com/servo/fontsan/pull/5

**Comment by nox** [comment]
@bors-servo retry

@larsbergstrom It's probably going to fail again, will you be able to get me the config.log file before it gets away?

**Comment by nox** [comment]
We don't pass --sysroot to the Android toolchain, that's why it doesn't build. Any idea how ANDROID_SYSROOT should be computed in fontsan?

**Comment by mbrubeck** [comment]
> We don't pass --sysroot to the Android toolchain, that's why it doesn't build. Any idea how ANDROID_SYSROOT should be computed in fontsan?

For the OpenSSL build, we set ANDROID_SYSROOT in [openssl.sh][1].  Maybe we could move this code into the [mach build command][2] so it's available for all packages.

[1]: https://github.com/servo/servo/blob/61be58a87ff78be6278173d65e8933413041bd00/support/android/openssl.sh#L128
[2]: https://github.com/servo/servo/blob/61be58a87ff78be6278173d65e8933413041bd00/python/servo/build_commands.py#L221

**Comment by frewsxcv** [comment]
Any updates?

**Comment by jdm** [comment]
Closing due to lack of updates.

**Pull request closed without merging**
