### PR TITLE
Fix compiler warnings in net unit tests

### PR DESCRIPTION
**Pull request by marcusklaas**
This closes issue https://github.com/servo/servo/issues/5709.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5734)

### CODE REVIEW

**Comment by jdm** [comment]
```
$ ./mach test-tidy
tests/unit/net/mime_classifier.rs:14: tab on line
tests/unit/net/mime_classifier.rs:15: tab on line
tests/unit/net/mime_classifier.rs:17: tab on line
tests/unit/net/mime_classifier.rs:19: tab on line
tests/unit/net/mime_classifier.rs:47: trailing whitespace
```

**Comment by marcusklaas** [comment]
Aaah, will take of those things promptly.

**Comment by jdm** [comment]
Reviewed files:
- tests/unit/lib.rs @ r1
- tests/unit/net/image_cache_task.rs @ r1
- tests/unit/net/mime_classifier.rs @ r1

---

<sup>**[tests/unit/net/mime_classifier.rs, line 60 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5734#-Jn6na4JjfI0ND8R2523)** ([raw file](https://github.com/servo/servo/blob/8746a31818fa6a5b522e9c5550859a1d0473e70d/tests/unit/net/mime_classifier.rs#L60)):</sup>
If we use {:?} here, I think we can just use `filename` instead of `filename_string`.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5734)

**Comment by marcusklaas** [comment]
I updated the pull request, but by amending my initial commit. Apparently reviewable doesn't like this. Should I just have added new commits?

**Comment by jdm** [comment]
My understanding is that reviewable is supposed to support that. @larsbergstrom?

**Comment by jdm** [comment]
Actually it looks like reviewable handled it just fine!

**Comment by jdm** [comment]
Reviewed files:
- tests/unit/net/mime_classifier.rs @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5734)

**Comment by marcusklaas** [comment]
Cool, I just got this by reading @hoppipolla-critic-bot's comment in this thread.

**Pull request merged**
