### PR TITLE
Add support for more array-like types in is_array_like

### PR DESCRIPTION
**Pull request by georgeroman**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23669)

### CODE REVIEW

**Review by ferjm — APPROVED** [review]
r=me with the nits addressed, please. Thanks!

**Comment by georgeroman** [comment]
@ferjm I added the requested changes.

**Comment by ferjm** [comment]
Thanks!

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Pull request merged**
