### PR TITLE
Snap rectangles to nearest pixels consistently.

### LINKED ISSUE #7152: Underlines less than 1px high are sometimes invisible due to rounding
In the test case below, about a third of the list items are painted with no visible underline.  The display list items for the missing underlines look like this:

`Rect(28px×0.6833333333333333px at (48px,255.78333333333333px))`

This rect is invisible after rounding because its top and bottom coordinates (255.7833px and 256.4667px) both round to the same whole pixel value (256px).

This test case reproduces the bug on my Linux box, though the behavior varies depending on the exact fonts installed in the system.  Zooming in or out can cause the bug to appear or disappear, depending again on the font.

```
<html>
  <head>
    <style>
      li {
        font: 14px "Times New Roman";
        text-decoration: underline;
      }
    </style>
  </head>
  <body>
    <ul>
      <li>Hello</li> <li>Hello</li> <li>Hello</li> <li>Hello</li>
      <li>Hello</li> <li>Hello</li> <li>Hello</li> <li>Hello</li>
      <li>Hello</li> <li>Hello</li> <li>Hello</li> <li>Hello</li>
      <li>Hello</li> <li>Hello</li> <li>Hello</li> <li>Hello</li>
      <li>Hello</li> <li>Hello</li> <li>Hello</li> <li>Hello</li>
    </ul>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by mbrubeck**
Snapping the top-left and bottom-right corners separately can cause a rectangle to change size or even become empty when offset by a subpixel amount.  Instead, this patch snaps the top-left corner, then snaps the size to a whole pixel amount, so any rectangle of a given original size will always have the same snapped size.

Fixes #7152. r? @pcwalton or @glennw

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7161)

### CODE REVIEW

**Comment by pcwalton** [comment]
I'd expect CSS tests to pass due to this, but if you've run them that's fine

**Comment by pcwalton** [comment]
```
/css21_dev/html4/position-relative-035.htm ------------------------------------------ PASS expected FAIL [Parent]
```

**Comment by mbrubeck** [comment]
@bors-servo retry

> /css21_dev/html4/position-relative-035.htm

I suspect this is intermittent, since it is still failing on the Mac builder, and I've seen unexpected PASS from this test on my personal Linux box, even without this patch.  I'll file an issue if this retry proves me right.

**Comment by mbrubeck** [comment]
@bors-servo r=pcwalton

Adjusted test expectation.

**Pull request merged**
