### PR TITLE
Support 'font-style: oblique'.

### PR DESCRIPTION
**Pull request by deokjinkim**
'oblique' font-style is not supported now.
When I checked freetype.h, same macro is used for italic and oblique.

  /\*    FT_STYLE_FLAG_ITALIC ::                                            _/
  /_      Indicates that a given face style is italic or oblique.          */

So, when font style is 'oblique', enable flag for italic.
With tests/html/test_italic_bold.html, it works well.

### CODE REVIEW

**Comment by Ms2ger** [comment]
No tests?

**Comment by deokjinkim** [comment]
tests/html/test_italic_bold.html file includes 'font-style: oblique'.
When I test it, it works well.

**Comment by jdm** [comment]
A reftest comparing a font using italic and the same font using oblique would make sense. Automated tests are always preferable to manual tests.

**Comment by deokjinkim** [comment]
@jdm Thank you for your advice. And I have a question about it.
Do you mean I have to run "./mach test-ref" before PR, otherwise run "./mach test"? 
When I run "./mach test-ref", it shows same result between "with my commit" and "without my commit".

failures:
    acid2_noscroll.html == acid2_ref_broken.html
    clip_a.html == clip_ref.html
    linebreak_simple_a.html == linebreak_simple_b.html
    vertical-lr-blocks.html == vertical-lr-blocks_ref.html

test result: FAILED. 207 passed; 4 failed; 0 ignored; 0 measured

**Comment by jdm** [comment]
@deokjinkim Right, I'm suggesting that you write a new reftest which compares a piece of text. In the reference page it uses `font-style: italic`, in the other page it uses `font-style: oblique`.

**Comment by deokjinkim** [comment]
@jdm I added reftest code for font-style and rebase it.

**Pull request merged**
