### PR TITLE
added dispatching for mousedown and mouseup events, fixes #5705

### LINKED ISSUE #5705: Dispatch mousedown and mouseup events
We currently dispatch click events, but not the mousedown and mouseup events that precede them.

Spec: https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3-Events.html#event-type-mousedown
Code: components/script/script_task.rs (see empty branches in handle_event), components/script/dom/document.rs (see handle_click_event)

### PR DESCRIPTION
**Pull request by pgonda**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5725)

### CODE REVIEW

**Comment by jdm** [comment]
@pgonda What's the order of events that the test reports?

**Comment by pgonda** [comment]
This does the Mousedown, click, then mouse up.  Should that be resolved in this commit?  I have already started digging into the problem but haven't not found anything yet.

**Comment by jdm** [comment]
Yes, we should try to implement spec-compliant behaviour from the start :)

**Comment by pgonda** [comment]
I have been debugging and digging though code but I have having a hard time finding where these events originate?  Any tips?

**Comment by jdm** [comment]
I searched for "MouseDown" and looked through the results for `send`, then stumbled across http://mxr.mozilla.org/servo/source/ports/glutin/window.rs#225 .

**Comment by pgonda** [comment]
r+?

**Comment by jdm** [comment]
I'll make sure to review this by the end of tomorrow.

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/document.rs @ r1
- components/script/script_task.rs @ r1
- components/servo/Cargo.lock @ r1
- ports/glutin/window.rs @ r2
- tests/html/test_mouse_down_mouse_up_click.html @ r1

---

<sup>**[components/script/dom/document.rs, line 619 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnv3_O2Rmje3XOCwP4w)** ([raw file](https://github.com/servo/servo/blob/8aaa341caa7cbfdfcbf537706e941ccbe0c48a2b/components/script/dom/document.rs#L619)):</sup>
This particular spec link doesn't make sense here.

---

<sup>**[components/script/dom/document.rs, line 628 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnv3EO8YlKwj-QW3OFR)** ([raw file](https://github.com/servo/servo/blob/8aaa341caa7cbfdfcbf537706e941ccbe0c48a2b/components/script/dom/document.rs#L628)):</sup>
There's a lot of duplication between these two methods and handle_mouse_click as well. I would like to minimize the code we add to support these events, since they have a lot in common :)

---

<sup>**[components/script/script_task.rs, line 1259 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnv3wd4FFvjNQOTXIS6)** ([raw file](https://github.com/servo/servo/blob/8aaa341caa7cbfdfcbf537706e941ccbe0c48a2b/components/script/script_task.rs#L1259)):</sup>
We should be able to reduce the duplication between these three match arms, too.

---

<sup>**[ports/glutin/window.rs, line 250 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnv5JXyH_4JlcEIeXPf)** ([raw file](https://github.com/servo/servo/blob/8aaa341caa7cbfdfcbf537706e941ccbe0c48a2b/ports/glutin/window.rs#L250)):</sup>
nit: } else {

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5725)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5725)

**Comment by pgonda** [comment]
<sup>**[components/script/script_task.rs, line 1259 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnv3wd4FFvjNQOTXIS6)** ([raw file](https://github.com/servo/servo/blob/8aaa341caa7cbfdfcbf537706e941ccbe0c48a2b/components/script/script_task.rs#L1259)):</sup>
I am wondering how to do this, I see alot of these arms set the _maker, but I dont see it being use?  Also all these arms retrieve a document, should that be extracted into a method also?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5725)

**Comment by jdm** [comment]
<sup>**[components/script/script_task.rs, line 1259 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnv3wd4FFvjNQOTXIS6)** ([raw file](https://github.com/servo/servo/blob/8aaa341caa7cbfdfcbf537706e941ccbe0c48a2b/components/script/script_task.rs#L1259)):</sup>
The marker's constructor and destructor execute code; it doesn't need to do anything else. I would pass the button and point to a generic handle_mouse_event method on document, along with an enum representing down/up/click. All of the arms can share the same code, in that case.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5725)

**Comment by pgonda** [comment]
<sup>**[components/script/script_task.rs, line 1259 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnv3wd4FFvjNQOTXIS6)** ([raw file](https://github.com/servo/servo/blob/8aaa341caa7cbfdfcbf537706e941ccbe0c48a2b/components/script/script_task.rs#L1259)):</sup>
That was my plan too! Thanks

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5725)

**Comment by pgonda** [comment]
updated, squashed and merged!

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/script/dom/document.rs @ r3
- components/script/script_task.rs @ r3
- components/servo/Cargo.lock @ r3
- ports/glutin/window.rs @ r3

---

<sup>**[components/script/dom/document.rs, line 546 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnx6VQpLLrjwVIdLwvk)** ([raw file](https://github.com/servo/servo/blob/550e0ed73260ac45ff89390d299b1e2cdab6e4fd/components/script/dom/document.rs#L546)):</sup>
This should only apply for the click event.

---

<sup>**[components/script/dom/document.rs, line 550 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnx3l4MuwG7jKyd-Y53)** ([raw file](https://github.com/servo/servo/blob/550e0ed73260ac45ff89390d299b1e2cdab6e4fd/components/script/dom/document.rs#L550)):</sup>
We shouldn't be messing with the focus except for click events.

---

<sup>**[components/script/dom/document.rs, line 580 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jnx3ocO8sPgPrx1k3nR)** ([raw file](https://github.com/servo/servo/blob/550e0ed73260ac45ff89390d299b1e2cdab6e4fd/components/script/dom/document.rs#L580)):</sup>
Let us leave the focus alone except for click events.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5725)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/script/dom/document.rs @ r4
- components/script/script_task.rs @ r4

---

<sup>**[components/script/dom/document.rs, line 546 \[r4\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jo5vdVsN6M_2MJ-JiTs)** ([raw file](https://github.com/servo/servo/blob/4ba4606b084862ac731d23270978906e7b383ba4/components/script/dom/document.rs#L546)):</sup>
Let's use `if let`

---

<sup>**[components/script/dom/document.rs, line 585 \[r4\]](https://reviewable.io:443/reviews/servo/servo/5725#-Jo5vgFxsGi3B1SMwFqS)** ([raw file](https://github.com/servo/servo/blob/4ba4606b084862ac731d23270978906e7b383ba4/components/script/dom/document.rs#L585)):</sup>
if let

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5725)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed files:
- components/script/dom/document.rs @ r5

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5725)

**Pull request merged**
