### PR TITLE
Implementing StorageEvent interface

### PR DESCRIPTION
**Pull request by snf**
Needed for #5196

### CODE REVIEW

**Comment by jdm** [comment]
In future, please follow the instructions of @hoppipolla-critic-bot and avoid force pushing :)

**Comment by jdm** [comment]
Looks pretty good! Just a few changes necessary; I left comments on Critic.

**Comment by jdm** [comment]
Squash!

**Comment by jdm** [comment]
Ye olde test-content is still failing:
```
thread '/home/servo/buildbot/slave/linux1/build/tests/content/test_interfaces.html' panicked at 'ALERT: TEST-UNEXPECTED-FAIL | StorageEvent is in [object Object]: If this is failing: DANGER, are you sure you want to expose the new interface StorageEvent to all webpages as a property on the window? Do not make a change to this file without review from jdm or Ms2ger for that specific change!', ../../tests/contenttest.rs:129
```
It just requires adding the StorageEvent interface to the list in test_interfaces.html.

**Comment by snf** [comment]
Updated the tests and checked they worked this time (and already squashed).

**Pull request merged**
