### PR TITLE
Update mozjs

### PR DESCRIPTION
**Pull request by sagudev**
Requires:
https://github.com/servo/mozjs/pull/268
https://github.com/servo/rust-mozjs/pull/535
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by sagudev** [comment]
```
In file included from Unified_cpp_js_src15.cpp:38:
  C:/Users/task_1615566412/.cargo/git/checkouts/mozjs-953f58dcd23dbdae/931e6f3/mozjs/js/src/vm/DateTime.cpp(537,13): warning: unused function 'IsOlsonCompatibleWindowsTimeZoneId' [-Wunused-function]
  static bool IsOlsonCompatibleWindowsTimeZoneId(const char* tz) {
              ^
  In file included from Unified_cpp_js_src_gc1.cpp:20:
  C:/Users/task_1615566412/.cargo/git/checkouts/mozjs-953f58dcd23dbdae/931e6f3/mozjs/js/src/gc/Nursery.cpp(1158,20): error: use of undeclared identifier '_getpid'
              size_t(getpid()),
                     ^
  C:/Users/task_1615566412/.cargo/git/checkouts/mozjs-953f58dcd23dbdae/931e6f3/mozjs/js/src/gc/Nursery.cpp(42,18): note: expanded from macro 'getpid'
  #  define getpid _getpid
                   ^
  1 warning generated.
  1 error generated.
```

**Comment by sagudev** [comment]
Probably caused by: https://hg.mozilla.org/mozilla-central/rev/b8eca46fe979123d3195fcddda42bd0155de9072

**Comment by sagudev** [comment]
Hpefully fixed in: https://github.com/sagudev/mozjs/commit/90bd6a8ed2b7ce6e4b738b05aa672cd791329116

**Comment by sagudev** [comment]
There is also a lot of `Unhandled rejection with value: object "TypeError: Promise.prototype.then called on incompatible Module"`

**Comment by sagudev** [comment]
I currently keep TLA disabled.
@jdm Could you do bors try again?

**Comment by sagudev** [comment]
```
▶ Unexpected subtest result in /wasm/jsapi/table/constructor-reftypes.tentative.any.html:
  └ PASS [expected FAIL] b'initialize externref table with default value'
```

**Comment by jdm** [comment]
You should do this:
```
wget https://community.taskcluster-artifacts.net/MSdZBL-gSo6A2neAxodDzA/0/public/test-wpt.log
./mach update-wpt test-wpt.log
git add tests/wpt/metadata
git commit -m "Update test results."
```

**Comment by jdm** [comment]
Ah, you will need to update the mozjs_sys revision to pick up 90bd6a8ed2b7ce6e4b738b05aa672cd791329116.

**Comment by sagudev** [comment]
> You should do this:
> 
> ```
> wget https://community.taskcluster-artifacts.net/MSdZBL-gSo6A2neAxodDzA/0/public/test-wpt.log
> ./mach update-wpt test-wpt.log
> git add tests/wpt/metadata
> git commit -m "Update test results."
> ```

Not all test newly passed, thats why I do not want to do it, https://community-tc.services.mozilla.com/tasks/MSdZBL-gSo6A2neAxodDzA/runs/0/logs/public/filtered-wpt-errorsummary.log

**Comment by jdm** [comment]
Yeah, but the same tests fails in Firefox: https://searchfox.org/mozilla-central/source/testing/web-platform/meta/wasm/jsapi/table/constructor.any.js.ini

**Comment by sagudev** [comment]
What does that mean?
```
./mach update-wpt test-wpt.log
Processing log 1/1
Test not found /css/css-color/color-mix-basic-001.tentative.html, skipping
Test not found /html/semantics/scripting-1/the-script-element/moving-between-documents-during-evaluation.html, skipping
Test not found /xhr/request-content-length.any.html, skipping
Test not found /resource-timing/resource_timing_content_length.html, skipping
Test not found /xhr/request-content-length.any.worker.html, skipping
Test not found /html/rendering/widgets/input-time-content-size.html, skipping
Test not found /html/rendering/widgets/input-date-content-size.html, skipping
```

**Comment by jdm** [comment]
> What does that mean?
> 
> ```
> ./mach update-wpt test-wpt.log
> Processing log 1/1
> Test not found /css/css-color/color-mix-basic-001.tentative.html, skipping
> Test not found /html/semantics/scripting-1/the-script-element/moving-between-documents-during-evaluation.html, skipping
> Test not found /xhr/request-content-length.any.html, skipping
> Test not found /resource-timing/resource_timing_content_length.html, skipping
> Test not found /xhr/request-content-length.any.worker.html, skipping
> Test not found /html/rendering/widgets/input-time-content-size.html, skipping
> Test not found /html/rendering/widgets/input-date-content-size.html, skipping
> ```

Usually it means that there were some tests in the log that don't exist in your tree because it's older than the test run. It doesn't matter here.

**Comment by sagudev** [comment]
> 
> 
> > What does that mean?
> > ```
> > ./mach update-wpt test-wpt.log
> > Processing log 1/1
> > Test not found /css/css-color/color-mix-basic-001.tentative.html, skipping
> > Test not found /html/semantics/scripting-1/the-script-element/moving-between-documents-during-evaluation.html, skipping
> > Test not found /xhr/request-content-length.any.html, skipping
> > Test not found /resource-timing/resource_timing_content_length.html, skipping
> > Test not found /xhr/request-content-length.any.worker.html, skipping
> > Test not found /html/rendering/widgets/input-time-content-size.html, skipping
> > Test not found /html/rendering/widgets/input-date-content-size.html, skipping
> > ```
> 
> Usually it means that there were some tests in the log that don't exist in your tree because it's older than the test run. It doesn't matter here.

OK. Can you now do full bors try.

**Comment by jdm** [comment]
That's #28259, so we're good to start merging everything!

**Comment by sagudev** [comment]
Ready for merge!

**Comment by sagudev** [comment]
@jdm ?

**Pull request merged**
