### PR TITLE
Derive ToComputedValue

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16973)

### CODE REVIEW

**Review by emilio — APPROVED** [review]

**Comment by Manishearth** [comment]
Yassssss

**Comment by Manishearth** [comment]
I wish we had this back when I did all the from_computed_value work. Briefly considered it. But this was pre-1.15.

**Comment by nox** [comment]
Well I'm glad you didn't, at least I have some code to remove.

**Pull request merged**
