### PR TITLE
Make tidy check for "*" in toml files

### PR DESCRIPTION
**Pull request by cuzbog**
This checks every .toml file for an asterisk and prints an error if found.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6648)

### CODE REVIEW

**Comment by boghison** [comment]
You guys are gonna have to guide me through updating the versions

**Comment by jdm** [comment]
@boghison You can use the Cargo.lock file as a guide - take the current A.B.C version for each matching package, and replace the "*" with "A.B".

**Comment by boghison** [comment]
Hmm, I am getting these errors:
"error: no method named `fmt` found for type `logical_geometry::WritingMode` in the current scope" in components/util/logical_geometry.rs:170
and "the trait `core::fmt::Debug` is not implemented for the type `task_state::TaskState` " in components/util/task_state.rs:60.

**Comment by boghison** [comment]
Oops, never mind ^^, I got the bitflags version wrong

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1, 23 of 23 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/layout/Cargo.toml, line 66 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6648#-JugHT1uow8MCQLPzDj1)** ([raw file](https://github.com/servo/servo/blob/f61ddde3d947678e15d9be242a5b7447ab84f45c/components/layout/Cargo.toml#L66)):</sup>
0.3

---

<sup>**[python/tidy.py, line 153 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6648#-JugIY7S_xzgXJRXxG0h)** ([raw file](https://github.com/servo/servo/blob/f61ddde3d947678e15d9be242a5b7447ab84f45c/python/tidy.py#L153)):</sup>
"found asterisk instead of minimum version number"

---

<sup>**[python/tidy.py, line 162 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6648#-JugIQe_fd2n3TKr5bcL)** ([raw file](https://github.com/servo/servo/blob/f61ddde3d947678e15d9be242a5b7447ab84f45c/python/tidy.py#L162)):</sup>
This comment isn't true any more, right?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6648)

**Comment by boghison** [comment]
@jdm I've edited the files.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 
Please rebuild once more and push the changes; the change to Servo.lock should disappear!

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6648)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6648)

**Pull request merged**
