### PR TITLE
layout: Take in account max and min inline size for inline fragments

### PR DESCRIPTION
**Pull request by emilio**
Improves MDN.

r? @mbrubeck or @pcwalton

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10557)

### CODE REVIEW

**Comment by emilio** [comment]
```
Tests with unexpected results:
  ▶ PASS [expected FAIL] /css21_dev/html4/max-width-110.htm
```

Cool, I'll update the expectations and this should be ready to merge.

**Comment by pcwalton** [comment]
This is great, thank you!

**Pull request merged**
