### PR TITLE
Move buildbot step to yaml

### PR DESCRIPTION
**Pull request by shinglyu**
This is a step of https://github.com/servo/saltfs/issues/316

After this patch lands, we'll PR the saltfs code to read from this yaml file, and dynamically generate test steps at runtime.

cc @aneeshusa @edunham

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10849)

### CODE REVIEW

**Comment by nox** [comment]
I'm confused. Since the YAML change, how does Buildbot know the difference between a compile step and a test step?

**Comment by aneeshusa** [comment]
@nox Heuristics, based on the command given to mach. (e.g. **build**-cef vs **test**-wpt).
One of the goals of switching to YAML was to decrease the complexity of changing build steps to make it easier, so I used heuristics instead of hardcoding many things. This allows for a simple list of strings, instead of requiring each line to be a dictionary with type: Compile, etc. keys.

Also, Test and Compile steps have essentially the same behavior, so in practice the difference is moot. The most visible difference right now is what they're labeled on the Buildbot display, which should improve with servo/saltfs#337.

**Comment by aneeshusa** [comment]
Can you update this to include the changes from servo/saltfs#341?

**Comment by nox** [comment]
@aneeshusa AFAIK buildbot stops on a compile step failing to succeed, while it doesn't on a test step.

**Comment by aneeshusa** [comment]
@nox You're right, I completely overlooked that. Seems like I learn something new about Buildbot every day!

**Comment by shinglyu** [comment]
@aneeshusa I just force pushed a version with https://github.com/servo/saltfs/pull/341

**Comment by aneeshusa** [comment]
@bors-servo r+

@shinglyu Thanks! Let me know if you have any questions while making the other PR.

**Pull request merged**
