### PR TITLE
form submission for <textarea> and <select>

### LINKED ISSUE #7849: Implement form submission for <select>
According to https://html.spec.whatwg.org/multipage/forms.html#constructing-the-form-data-set we're supposed to include the selected `<option>` values from `<select>` (see step 3.5). We should implemented the `//Unimplemented` piece in `get_form_dataset` related to `HTMLSelectElement`, by adding a method to `HTMLSelectElement` that fetches the required values in a vector of DOMString, and appends a `FormDatum` value for each one according to the specification in 3.5.

code: components/script/dom/htmlselecteelement.rs, components/script/dom/htmlformelement.rs

### LINKED ISSUE #7850: Implement form submission for <textarea>
According to https://html.spec.whatwg.org/multipage/forms.html#constructing-the-form-data-set we're supposed to include `<textarea>` values. There's no explicit step for this, but it's covered under 3.4 and 3.9 (and mentioned in the note at the bottom). We should implemented the `//Unimplemented` piece in `get_form_dataset` related to `HTMLTextareaElement`; we can use the `Value` method for now, and I'll file a follow up issue for ensuring that we address the specific concerns mentioned at https://html.spec.whatwg.org/multipage/forms.html#the-textarea-element:concept-textarea-raw-value-7 .

code: components/script/dom/htmltextareaelement.rs, components/script/dom/htmlformelement.rs

### PR DESCRIPTION
**Pull request by 6112**
Fixes #7849.
Fixes #7850.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7919)

### CODE REVIEW

**Comment by jdm** [comment]
@nox, would you review this?

**Comment by nox** [comment]
Sure.

**Comment by nox** [comment]
Thanks for your contribution! See remarks on Reviewable.

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlformelement.rs, line 255 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7919#-K03iJxzaUWHBMp7S8mv)** ([raw file](https://github.com/servo/servo/blob/1dd55f1dcc2a39cc9a60eaed7f130b67552192d6/components/script/dom/htmlformelement.rs#L255)):</sup>
This is an anti-pattern, do this instead:

```rust
if let Some(datum) = input.get_form_datum(submitter) {
    data_set.push(datum);
}
```


---

<sup>**[components/script/dom/htmlformelement.rs, line 269 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7919#-K03kQ36xpc-O6uUNNJn)** ([raw file](https://github.com/servo/servo/blob/1dd55f1dcc2a39cc9a60eaed7f130b67552192d6/components/script/dom/htmlformelement.rs#L269)):</sup>
There should be no space after the negation operator.


---

<sup>**[components/script/dom/htmlformelement.rs, line 272 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7919#-K03icDnMyZ-gcze55j7)** ([raw file](https://github.com/servo/servo/blob/1dd55f1dcc2a39cc9a60eaed7f130b67552192d6/components/script/dom/htmlformelement.rs#L272)):</sup>
Reuse `name` here.


---

<sup>**[components/script/dom/htmlselectelement.rs, line 67 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7919#-K03itKVuURN70KOequB)** ([raw file](https://github.com/servo/servo/blob/1dd55f1dcc2a39cc9a60eaed7f130b67552192d6/components/script/dom/htmlselectelement.rs#L67)):</sup>
Here you can instead do:

```rust
if let Some(option) = HTMLOptionElementCast::to_ref(&child) {
    ...
}
```


---

<sup>**[components/script/dom/htmlselectelement.rs, line 68 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7919#-K03j7o-M1HJd56CvxhL)** ([raw file](https://github.com/servo/servo/blob/1dd55f1dcc2a39cc9a60eaed7f130b67552192d6/components/script/dom/htmlselectelement.rs#L68)):</sup>
Upcast the option to `Node` (`let node = NodeCast::from_ref(option);`) and use the method `get_disabled_state()` on that.

@jdm Does our IDL getter for the `disabled` attribute properly accounts for the disabled state in `NodeFlags`? It doesn't seem so. Should it?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7919)

**Comment by jdm** [comment]
Mmm, I knew that `Disabled` thing sounded familiar: https://github.com/servo/servo/issues/4765#issuecomment-72014390

**Comment by nox** [comment]
One last nitpick. Btw @6112, why are there no test expectations changes?

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/htmlselectelement.rs, line 68 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7919#-K03j7o-M1HJd56CvxhL)** ([raw file](https://github.com/servo/servo/blob/1dd55f1dcc2a39cc9a60eaed7f130b67552192d6/components/script/dom/htmlselectelement.rs#L68)):</sup>
Err, silly me, you can just do `child.get_enabled_state()` here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7919)

**Comment by 6112** [comment]
As for the test expectations, I'm not quite sure what you mean. I'm very new here, and mostly clueless about the tests.

**Comment by jdm** [comment]
@nox I'm not sure how much automated testing exists for form submission right now; http://mxr.mozilla.org/servo/search?string=.submit doesn't reveal very many likely tests.

**Comment by eefriedman** [comment]
#7923 has a test for this.

**Comment by nox** [comment]
-S-awaiting-review 


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7919)

**Comment by nox** [comment]
Looks good. Let me try it before, given there are no expectation changes.

@bors-servo try


---

Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7919)

**Comment by jdm** [comment]
@nox?

**Comment by nox** [comment]
@jdm We want #7923 first.

**Comment by jdm** [comment]
#7923 merged!

**Comment by Manishearth** [comment]
This looks like it just needs an r+?

**Comment by nox** [comment]
Mmmh, yes.

@bors-servo r+

**Comment by KiChjang** [comment]
```
Ran 3728 tests finished in 860.0 seconds.
  • 3727 ran as expected. 707 tests skipped.
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /html/semantics/forms/form-submission-0/url-encoded.html:
  └ PASS [expected FAIL] textarea.simple
```
Looking nice here!

**Comment by frewsxcv** [comment]
@6112 Need any help updating the text expectations?

**Comment by 6112** [comment]
@frewsxcv Is there anything I need to do except remove the `expected: FAIL` line in `tests/wpt/metadata/html/semantics/forms/form-submission-0/url-encoded.html.ini`?

**Comment by KiChjang** [comment]
@6112 if you've done that already, you'll need to squash your commits and then push.

**Comment by nox** [comment]
The file `tests/wpt/metadata/html/semantics/forms/form-submission-0/url-encoded.html.ini` should be completely removed given there are no remaining failing tests.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7919#-:-K5RSxVL7rZ-gUPpoPvg:1020781963)*

**Comment by KiChjang** [comment]
@6112 You're almost there! Is there anything that we can do to help?

**Comment by 6112** [comment]
Thanks for reminding me, @KiChjang . I'd forgotten about this.

**Comment by nox** [comment]
@bors-servo r+

Perfect, thanks! Sorry didn't notice earlier that you had rebased.

---

Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7919#-:-K6o-CvY4MQF7GaZ1YXx:933273585)*

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #8769

**Comment by jdm** [comment]
@bors-servo: retry
* forced

**Pull request merged**
