### PR TITLE
Remove some use of FFI in gecko_string_cache

### PR DESCRIPTION
**Pull request by SimonSapin**
Now that nsIAtom’s mLength and mString can both be accessed directly on the struct, fewer operations need to call into C++ code.

These functions are not used anymore and can be removed from the Gecko side:
- `Gecko_GetAtomAsUTF16`
- `Gecko_AtomEqualsUTF8IgnoreCase`
- `Gecko_AtomEqualsUTF8` (looks like this one was already unused before this PR)

r? @emilio 

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not new require tests because no behavior change

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12906)

### CODE REVIEW

**Comment by emilio** [comment]
Thanks!

**Comment by SimonSapin** [comment]
@bors-servo retry

> EnvironmentError: http server on port 8000 failed to start

**Comment by SimonSapin** [comment]
@bors-servo retry

* #12891

**Pull request merged**
