### PR TITLE
Issue9185 experimental PR (for travis only)

### PR DESCRIPTION
**Pull request by njskalski**
As named, this experimental, far from ready for review.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9231)

### CODE REVIEW

**Comment by KiChjang** [comment]
Does `./mach build -d` not work for you?

**Comment by askalski** [comment]
you are right.

**Comment by askalski** [comment]
but how to run locally travis?

**Comment by KiChjang** [comment]
Travis cannot be run locally, it's only ran when you open a PR. Are you interested in building your code on different platforms?

**Comment by jdm** [comment]
If it's running the same tests that concerns you, you can see everything that gets executed at http://mxr.mozilla.org/servo/source/.travis.yml

**Pull request closed without merging**
