### PR TITLE
Add port blocking for tftp, netbios-ns, snmp, rtsp, h323gatestat, h32…

### PR DESCRIPTION
**Pull request by ghostd**
…3hostcall, pptp, sane-port

Spec update: https://github.com/whatwg/fetch/pull/1148

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by CYBAI** [comment]
More tests pass now 🎉 

<details>

```
  ▶ OK [expected TIMEOUT] b'/fetch/api/request/request-bad-port.any.html'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected TIMEOUT] b'Request on bad port 1720 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 1723 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 2049 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 3659 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 4045 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 5060 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 5061 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6000 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6665 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6666 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6667 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6668 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6669 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6697 should throw TypeError.'
  ▶ OK [expected TIMEOUT] b'/fetch/api/request/request-bad-port.any.worker.html'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected TIMEOUT] b'Request on bad port 1720 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 1723 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 2049 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 3659 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 4045 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 5060 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 5061 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6000 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6665 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6666 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6667 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6668 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6669 should throw TypeError.'
  ▶ Unexpected subtest result in /fetch/api/request/request-bad-port.any.worker.html:
  └ PASS [expected NOTRUN] b'Request on bad port 6697 should throw TypeError.'
```

</details>

**Comment by ghostd** [comment]
I rebased and fixed the .ini files.

**Pull request merged**
