### PR TITLE
fixed an issue related with .DS_Store

### LINKED ISSUE #15581: error: invalid character in pkgid `.DS_Store_tests`: `.` for MacOS
If a `.DS_Store` directory exists in certain test paths on MacOS (Sierra 10.12.3), `$ ./mach test-unit` results in:
```
error: invalid character in pkgid `.DS_Store_tests`: `.`
```

```
$ ./mach build -d && ./mach test-unit
    Finished dev [unoptimized + debuginfo] target(s) in 0.4 secs
Build Completed in 0:00:11
error: invalid character in pkgid `.DS_Store_tests`: `.`

$ rm .DS_Store
$ ./mach build -d && ./mach test-unit
    Finished dev [unoptimized + debuginfo] target(s) in 0.3 secs
Build Completed in 0:00:09
error: invalid character in pkgid `.DS_Store_tests`: `.`

$ rm tests/.DS_Store
$ ./mach build -d && ./mach test-unit
    Finished dev [unoptimized + debuginfo] target(s) in 0.6 secs
Build Completed in 0:00:15
error: invalid character in pkgid `.DS_Store_tests`: `.`

$ rm tests/unit/.DS_Store
$ ./mach build -d && ./mach test-unit
    Finished dev [unoptimized + debuginfo] target(s) in 0.6 secs
Build Completed in 0:00:13
[tests run now...]
```

### PR DESCRIPTION
**Pull request by framlog**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15581.

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15665)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
I'm not familiar with Mac foo, sadly. r? @SimonSapin @jdm or someone else.

**Comment by SimonSapin** [comment]
Looks good, thanks!

@bors-servo r+

**Comment by UnICorN21** [comment]
Oh, seems that I forget the brackets. Sorry.

**Pull request merged**
