### PR TITLE
Use jsapi::JSClass to make DOMJSClass instead of jsapi::Class

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
Fix https://github.com/servo/servo/issues/13031

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13049)

### CODE REVIEW

**Comment by saneyuki** [comment]
@nox r?

**Comment by Ms2ger** [comment]
`ProxyTraps` is within our control; maybe it would be easier to change that to use `JSFreeOp` too?

**Comment by saneyuki** [comment]
@Ms2ger 

> ProxyTraps is within our control; maybe it would be easier to change that to use JSFreeOp too?


rust-mozjs's jsglue.cpp defines [`ProxyTrap.finalize()` takes `JSFreeOp`](https://github.com/servo/rust-mozjs/blob/a4a693bf41fc67e839f3a5e8219d872f5c675b5f/src/jsglue.cpp#L88), but in rust side (glue.rs) defines [it takes `FreeOp`](https://github.com/servo/rust-mozjs/blob/a4a693bf41fc67e839f3a5e8219d872f5c675b5f/src/glue.rs#L144). Why do we have this difference? 

If this difference is meaningless now, it would be easy to change `ProxyTrap.finalize()` to take `JSFreeOp`.

**Comment by nox** [comment]
`ProxyTraps` is under our control, but not the underlying `js::Wrapper` superclass that really wants the `JSFreeOp`.

**Comment by nox** [comment]
@saneyuki Could you explain why these `finalize` shenanigans are needed?

**Comment by saneyuki** [comment]
@nox 

- `ProxyTrap.finalize` requires `finalize` which has  `Option<unsafe extern fn(fop: *mut FreeOp, proxy: *mut JSObject)>`
- `JSClassOps.finalize` requires `finalize` which has `type JSFinalizeOp = Option<unsafe extern fn(fop: *mut JSFreeOp, obj: *mut JSObject)>;`
- `finalize()` does not use the `fop` 1st argument. So we don't have any problem to make it generic `T` to use finalize for both of `ProxyTrap.finalize` and `JSClassOps.finalize`.
   - So I made `finalize` shenanigans in the current patch.
- ...But if we change `ProxyTrap.finalize` signature like @Ms2ger suggested, we don't have to make `finalize` generic shenanigans.

**Comment by saneyuki** [comment]
depends on https://github.com/servo/rust-mozjs/pull/295

**Comment by nox** [comment]
@saneyuki Somehow I inversed `JSFreeOp` and `FreeOp` when I was trying to think about it, making everything more confusing that it was supposed to be.

**Comment by nox** [comment]
Carried in #13062 as part of my attempt to rustup, thanks @saneyuki!

**Pull request closed without merging**
