### PR TITLE
Make the parser accept @font-face rules without font-family or src.

### LINKED ISSUE #16165: parse_font_face_block should not reject a @font-face rule when it lacks font-family or src
`parse_font_face_block` currently rejects a `@font-face` rule if it lacks `font-family` or `src` descriptor. The spec says that makes the rule invalid, but it doesn't make it clear how to handle invalid rule (see w3c/csswg-drafts#1133).

All modern browsers agree on that the parser should accept such invalid rule, so I suppose the spec would follow this way as well. That said, Servo should change the behavior to match other browsers.

(This is the reason why many `@font-face`-related mochitests are still failing even after [bug 1345696](https://bugzilla.mozilla.org/show_bug.cgi?id=1345696).)

cc @SimonSapin

### PR DESCRIPTION
**Pull request by SimonSapin**
Fix #16165.

Also, it turns out that the CSSFontFaceRule IDL specified in the css-fonts spec is not web-compatible. Instead browsers implement a .style attribute like in CSSStyleRule: https://github.com/w3c/csswg-drafts/issues/825

This in turn requires preserving data about which descriptors were set or not (distinguishing unset from set to a value that happens to be the initial value), so this commit also makes every field `Option<_>`.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16224)

### CODE REVIEW

**Comment by SimonSapin** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=7fb7d36493bc0f435476c769fdcccfd92f31e10b

**Comment by SimonSapin** [comment]
Servo failures:

```
  ▶ Unexpected subtest result in /css-conditional-3_dev/html/001.htm:
  └ PASS [expected FAIL] Inserting @font-face inside @supports works

  ▶ Unexpected subtest result in /css-conditional-3_dev/html/001.htm:
  └ PASS [expected FAIL] Inserting an @supports inside a style rule should fail
```

The first has a typo: `font-familly`. Without `font-family`, the rule would previously be rejected and the test fail. The second is in the same test file, and relies on global state left by the previous test. I’ve updated the expectations.

@bors-servo try

---

Gecko failures:

```
TEST-UNEXPECTED-FAIL | layout/style/test/test_descriptor_storage.html | failures in this test - expected 1 failures but got 14
TEST-UNEXPECTED-FAIL | layout/style/test/test_descriptor_syntax_errors.html | failures in this test - expected 1 failures but got 8
TEST-UNEXPECTED-FAIL | layout/style/test/test_font_face_parser.html | failure pattern `@font-face` in this test - expected 447 failures but got 83
```

Both "expected 1" were uncaught JS exceptions that aborted the whole test file. Now we’re at least running subtests.

**Comment by SimonSapin** [comment]
Something got lost between buildbot and homu, but http://build.servo.org/grid looks green.

@bors-servo try, with an additional commit that fixes some Gecko failures

**Comment by Manishearth** [comment]
@bors-servo treeclosed=100000

vcssync will break if we land something right now

**Comment by upsuper** [comment]
Reviewed 7 of 7 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/style/font_face.rs, line 210 at r2](https://reviewable.io:443/reviews/servo/servo/16224#-KgmUqoPNsCVMWu7WPTR:-KgmUqoQeHbkio5K2U-1:b7vqz8m) ([raw file](https://github.com/servo/servo/blob/b43e2fb0dfeb06717f75f579d268d6228056c071/components/style/font_face.rs#L210)):*
> ```Rust
>                 // Leave unset descriptors to eCSSUnit_Null,
>                 // FontFaceSet::FindOrCreateUserFontEntryFromFontFace does the defaulting
>                 // to initial values.
> ```

I guess you can probably remove this comment. The comment in `font_face_descriptors!` should be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/16224)*

**Comment by upsuper** [comment]
r=me

**Comment by SimonSapin** [comment]
Stylo expectation changes:

```diff
diff --git a/layout/style/test/stylo-failures.md b/layout/style/test/stylo-failures.md
index 912b43b..ca0f69f 100644
--- a/layout/style/test/stylo-failures.md
+++ b/layout/style/test/stylo-failures.md
@@ -118,9 +118,8 @@ to mochitest command.
   * ... `'content`: various value as list-style-type in counter functions [13]
 * test_default_computed_style.html: support of getDefaultComputedStyle [1]
 * @font-face support bug 1290237
-  * test_descriptor_storage.html [1]
-  * test_descriptor_syntax_errors.html [1]
-  * test_font_face_parser.html `@font-face` [447]
+  * test_descriptor_storage.html [14]
+  * test_font_face_parser.html `@font-face` [81]
 * @namespace support:
   * test_namespace_rule.html [17]
 * test_dont_use_document_colors.html: support of disabling document color [21]
```

**Pull request merged**
