### PR TITLE
More clippy fixes

### PR DESCRIPTION
**Pull request by Manishearth**
Elided almost all the lifetimes and removed needless returns. Mostly done by sed + manual fixes.

r? @nox

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7536)

### CODE REVIEW

**Comment by Manishearth** [comment]
The last commit is just because I'm not 100% sure on how trait objects work with elision, and I'd rather not make layout elide some random lifetime in unsafe code.

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1, 33 of 33 files at r2, 4 of 4 files at r3, 14 of 14 files at r4, 1 of 1 files at r5, 9 of 9 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/gfx/text/text_run.rs, line 167 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7536#-JyMXNo659lA5TQQ30G2)** ([raw file](https://github.com/servo/servo/blob/e94df1ed5c3ccf76cd616e1146e2944f852477ac/components/gfx/text/text_run.rs#L167)):</sup>
Remove the local

---

<sup>**[components/layout/construct.rs, line 1562 \[r6\]](https://reviewable.io:443/reviews/servo/servo/7536#-JyMYQYhpeYF7zkaQFj7)** ([raw file](https://github.com/servo/servo/blob/89962d576976cc3b561649f6a0421f8c988e1939/components/layout/construct.rs#L1562)):</sup>
Indentation

---

<sup>**[components/script/dom/eventdispatcher.rs, line 17 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7536#-JyMWrnVpj3zmRFr-Yro)** ([raw file](https://github.com/servo/servo/blob/54c036cd66f6c9a59610fb804d57a63ab7aad19f/components/script/dom/eventdispatcher.rs#L17)):</sup>
Indentation

---

<sup>**[components/script/dom/htmlinputelement.rs, line 359 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7536#-JyMWxrOkHkc48pn5fLt)** ([raw file](https://github.com/servo/servo/blob/54c036cd66f6c9a59610fb804d57a63ab7aad19f/components/script/dom/htmlinputelement.rs#L359)):</sup>
Indentation

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7536)

**Comment by Manishearth** [comment]
Done

---

Review status: 49 of 53 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7536)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Reviewed 4 of 4 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7536)

**Pull request merged**
