### PR TITLE
Implement basic framework for static and interactive validation on forms

### PR DESCRIPTION
**Pull request by KiChjang**
This came along when I was trying to do #3648. I was about to do form validation as well, but then I saw it was actually intended to be a student project. Hopefully I didn't step on too many toes on this one; I did leave most of the important bits out (the fun bits I believe, e.g. interactive validation doesn't actually interactively validate anything right now).

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8747)

### CODE REVIEW

**Comment by Manishearth** [comment]
Reviewed 8 of 10 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[components/script/dom/htmlformelement.rs, line 174 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4TkiLE05lyiOQR1yzo:-K4TkiLE05lyiOQR1yzp:-432098845) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L174)):*
We should also add event handler setters for this event on all form controls

---

*[components/script/dom/htmlformelement.rs, line 177 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4Tm8_VXYNPb7OvI0UW:-K4Tm8_WpR2bnmJsIzYA:515205260) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L177)):*
We really should have a separate "fire a simple event" method. I often forget if this one sets trusted or not.

---

*[components/script/dom/htmlformelement.rs, line 203 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4TmbqCyA5D6NI2gtOo:-K4TmbqD3M4S3PUUO7P-:-428806913) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L203)):*
don't think so

---

*[components/script/dom/htmlformelement.rs, line 208 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4TmhWEHOSufWCRjVHU:-K4TmhWEHOSufWCRjVHV:-1138453263) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L208)):*
we do this twice?

---

*[components/script/dom/htmlformelement.rs, line 253 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4TncZ9ksNhjAgJxpPj:-K4TncZ9ksNhjAgJxpPk:-684055672) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L253)):*
use a match here

---

*[components/script/dom/htmlformelement.rs, line 266 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4U4WCdJHZ1FBqBgC6H:-K4U4WCdJHZ1FBqBgC6I:-2000756845) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L266)):*
mention the form owner PR here (`FIXME(#3553)`)

---

*[components/script/dom/htmlformelement.rs, line 270 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4U4pHl9kSW0KvYoFh4:-K4U4pHl9kSW0KvYoFh5:-743957309) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L270)):*
this unwrap will choke on text nodes

Use an if let instead, and ignore non-Element nodes entirely

---

*[components/script/dom/htmlformelement.rs, line 272 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4U58BcyeUxuOy9mh8H:-K4U58BcyeUxuOy9mh8I:-109373673) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L272)):*
why datalist?

Perhaps we should add methods `candidate_for_validation()` and `satisfies_constraints()` to form elements via `FormControl`? This function becomes much cleaner then.

---

*[components/script/dom/htmlformelement.rs, line 276 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4U6YEUe3vat3oITbAC:-K4U6YEUe3vat3oITbAD:1153249728) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L276)):*
Did you mean Ok() here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8747)*

**Comment by Manishearth** [comment]
Reviewed 2 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8747)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/htmlformelement.rs, line 174 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4TkiLE05lyiOQR1yzo:-K4UOR4bNKU5d0myFCIr:1142119520) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L174)):*
Hmm, yes. I'm probably going to leave a comment here.

---

*[components/script/dom/htmlformelement.rs, line 177 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4Tm8_VXYNPb7OvI0UW:-K4UOZBHrN6iahP4qRHt:-74425965) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L177)):*
Comment here for refactoring as well.

---

*[components/script/dom/htmlformelement.rs, line 208 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4TmhWEHOSufWCRjVHU:-K4UNjBGU7TCCEftKCz8:1972525190) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L208)):*
Whoops, I didn't see this. I asked @SimonSapin and he indicated that the procedure of resolving a URL is the same as parsing it (at least to my understanding). I'm going to instead call this step 9-10.

---

*[components/script/dom/htmlformelement.rs, line 272 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4U58BcyeUxuOy9mh8H:-K4UNFNLYOCvmbGiArUQ:-245605766) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L272)):*
Spec says so: https://html.spec.whatwg.org/multipage/forms.html#the-datalist-element:barred-from-constraint-validation.

If that's the case, then I will unimplement this method and let it be an exercise to students.

---

*[components/script/dom/htmlformelement.rs, line 276 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4U6YEUe3vat3oITbAC:-K4UJcz1gN2YlYPdDJd3:-209765047) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L276)):*
This is within the `filter_map` context, so returning `None` would skip the current `field` and move on to the next.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8747)*

**Comment by KiChjang** [comment]
Added comments in the code reflecting the issues discussed. I also left my name there so that anyone who picks this up can contact me if they wanted to know more details about what happened (let's also update the student project wiki to point to this PR).

**Comment by Manishearth** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/htmlformelement.rs, line 272 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4U58BcyeUxuOy9mh8H:-K4WJbVNM5G5wFF-DGYB:-352209640) ([raw file](https://github.com/servo/servo/blob/debeb13fb17ac15dfbe75184953168212e1e3acd/components/script/dom/htmlformelement.rs#L272)):*
Ah, I see. Leaving it there sounds okay, but I agree that some of this should be unimplemented.

---

*[components/script/dom/htmlformelement.rs, line 173 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4WJwDnPViF8rz7pUnW:-K4WJwDnPViF8rz7pUnX:1876368703) ([raw file](https://github.com/servo/servo/blob/90b04445cf848b68b4ce61484e96f65c15bb5fac/components/script/dom/htmlformelement.rs#L173)):*
You can do it as part of this PR, or make an easy bug once this lands :smile: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8747)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/htmlformelement.rs, line 173 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4WJwDnPViF8rz7pUnW:-K4WVkHXfJpr0Y1EIKa8:1579339884) ([raw file](https://github.com/servo/servo/blob/90b04445cf848b68b4ce61484e96f65c15bb5fac/components/script/dom/htmlformelement.rs#L173)):*
I lean towards making an easy issue, or simply letting someone from the student projects take care of it. Either way, I'm going to open an issue to track these once it lands.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8747)*

**Comment by KiChjang** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/htmlformelement.rs, line 173 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4WJwDnPViF8rz7pUnW:-K4W_G9B8qod9wLAHCKK:-1549169699) ([raw file](https://github.com/servo/servo/blob/90b04445cf848b68b4ce61484e96f65c15bb5fac/components/script/dom/htmlformelement.rs#L173)):*
Filed as #8777.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8747)*

**Comment by Manishearth** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/htmlformelement.rs, line 270 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8747#-K4eaGdrid2LW6_LGD9g:-K4eaGdrid2LW6_LGD9h:-1435179005) ([raw file](https://github.com/servo/servo/blob/5c6798e005219c2aa43071cace1465fa53c3f794/components/script/dom/htmlformelement.rs#L270)):*
This comment really applies to the entire function here, since the satisfied_constraints stuff will happen below

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8747)*

**Comment by KiChjang** [comment]
Done! Hopefully the instructions I left are clear...

**Comment by Manishearth** [comment]
Looks good.

@jdm Does this do too much of the proposed student project?

r=me otherwise

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8747#-:-K4h_5KIQw4cYehuyAA4:-1017554562)*

**Comment by frewsxcv** [comment]
What's the status of this? Looks like @Manishearth already approved this

**Comment by jdm** [comment]
I'm fine with most of these changes, but I'm less keen on the big block of commented code at https://github.com/servo/servo/pull/8747/files#diff-db2031d1f23ecf1a921fc100cfed753dR273 . I'd prefer to merge this with that removed.

**Comment by KiChjang** [comment]
Done.

**Pull request merged**
