### PR TITLE
Inline pseudo elements layout#12367

### LINKED ISSUE #12367: Margins of inline pseudo elements(:before and :after) are ignored.
Minimal case:
```
<!DOCTYPE html><html><head><style type="text/css">
  span:before { content:"a"; margin-right:5em; }
  span:after { content:"c"; margin-left:5em; }
</style></head>
<body><span>b</span></body>
</html>
```
Servo:
servo_inline_pseudo_margins
Firefox:
firefox_inline_pseudo_margins

If there are no objections, I would like to try to investigate it myself.
Any thoughts/ideas are welcome.

### PR DESCRIPTION
**Pull request by splav**
This PR fixes ignored paddings and margins for inline pseudo elements.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12367 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12669)

### CODE REVIEW

**Comment by splav** [comment]
This is a first version, another part is missing - in the following case the green zone is calculated incorrectly and a line is broken:

```
<!DOCTYPE html>
<html><head><style type="text/css">
  span:before {
    content:"a";
    margin-right:5em;
  }
  span:after {
    content:"c";
    margin-left:5em;
  }
  span {
    margin-left:4em;
    margin-right:4em;
  }
</style></head>
<body><div style="position: absolute; top: 20px;"><span>b</span></div></body>
</html>
```

**Comment by jdm** [comment]
Want to review this, @notriddle?

**Comment by notriddle** [comment]
Yeah, that sounds like something I could help with.

**Comment by splav** [comment]
@notriddle may be change to something like this:

```
<style type="text/css">
  span:before { content:"a"; margin-right:5em; }
  span:after { content:"c"; margin-left:5em; }
  #first { margin-left:4em; margin-right:4em; }
  #second:before { margin-left:4em; }
  #second:after { margin-right:4em; }
</style>
<body>
    |<span id=first>b</span>|<br>
    |<span id=second>b</span>|
</body>
```

and 

```
<style type="text/css">
  span:before { content:"a"; padding-right:5em; }
  span:after { content:"c"; padding-left:5em; }
  #first { padding-left:4em; padding-right:4em; }
  #second:before { padding-left:4em; }
  #second:after { padding-right:4em; }
</style>

<body>
    |<span id=first>b</span>|<br>
    |<span id=second>b</span>|
</body>
```

**Comment by notriddle** [comment]
The modified version of the test looks good.

The big problem that the modify function tries to solve is that the style of the base element is copied verbatim to the pseudo-element. I think that was actually fixed in the style code awhile back. Let's try it.

@bors-servo try

**Comment by notriddle** [comment]
The passes look good, since they're part of your PR. I'm not sure about the failures, because there aren't any pseudo elements in either of those tests to trigger your code changes.

**Comment by notriddle** [comment]
Reverting c1243fe, the one that prevents text fragments from being merged, fixes the test failures. Reverting f787f3a, the one that stops pseudo-element styles from being reset, does not. (I ran the failing tests on my box to check them.)

**Comment by splav** [comment]
@notriddle OK, thank you. I'll investigate what's going on in failed tests. And also in the case with absolutely positioned div, I've posted before.

**Comment by notriddle** [comment]
@bors-servo try

Let's see how #12760 affected the test results.

**Comment by splav** [comment]
@notriddle according to logs the only failing tests are 4 PASS [expected FAIL] ones. I've made a rebase to more recent master just in case and added test expectations change commit. Everything seems to be fine.

**Comment by splav** [comment]
Timeout in one test - /html/browsers/browsing-the-web/navigating-across-documents/014.html

**Comment by jdm** [comment]
@bors-servo: retry
* #12797

**Comment by splav** [comment]
Rebased to current master.

**Pull request merged**
