### PR TITLE
Update rust-mozjs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12954)

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@nox: I fixed tidy issues.

**Comment by GuillaumeGomez** [comment]
Retry please (windows tests didn't start apparently?)?

**Comment by GuillaumeGomez** [comment]
Is this intermittent?

**Comment by emilio** [comment]
Nope, and I think those are suspicious enough to deserve a bit of investigation. They're most likely caused by this changeset.

**Comment by nox** [comment]
Please post here a generated binding so we can compare the output, and please add some unions with dictionaries to `TestBinding` so these paths are tested.

**Comment by GuillaumeGomez** [comment]
A generated file: https://gist.github.com/GuillaumeGomez/227ee9b8b3a4d7f23b1193be7fe1a2c4

However I don't understand what you want:

> and please add some unions with dictionaries to `TestBinding` so these paths are tested.

**Comment by nox** [comment]
Which part do you not understand?

This patch makes Servo cope with unions including a dictionary type, so I want `TestBinding` (see TestBinding.webidl) to include some stuff with such unions.

**Comment by GuillaumeGomez** [comment]
I added @Ms2ger's suggestion.

**Comment by GuillaumeGomez** [comment]
Appveyor error is: "error: failed to build archive: bad archive: permission denied". Intermittent failure?

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlcanvaselement.rs, line 163 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12954#-KPvxMhCCvZK-m-0VhH2:-KPvxMhCCvZK-m-0VhH3:b3xfq64) ([raw file](https://github.com/servo/servo/blob/b35729b6e0e16ec4134a1acbb0a24a7bb0a36f0a/components/script/dom/htmlcanvaselement.rs#L163)):*
> ```Rust
> 
>             let attrs = if let Some(webgl_attributes) = attrs {
>                 if let Ok(ConversionResult::Success(ref attrs)) = unsafe {
> ```

You didn't throw in the case of `ConversionResult::Failure` here.

---

*[components/script/dom/bindings/conversions.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12954#-KPvxZd9AtDsEmsYEKOb:-KPvxZd9AtDsEmsYEKOc:b-ypon40) ([raw file](https://github.com/servo/servo/blob/b35729b6e0e16ec4134a1acbb0a24a7bb0a36f0a/components/script/dom/bindings/conversions.rs#L87)):*
> ```Rust
>                          -> Result<ConversionResult<Finite<T>>, ()> {
>         let result = match FromJSValConvertible::from_jsval(cx, value, option) {
>             Ok(ConversionResult::Success(v)) => v,
> ```

Missing throw on failure here.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 5307 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12954#-KPvxiczFowBXW2hB2HJ:-KPvxiczFowBXW2hB2HK:bk93345) ([raw file](https://github.com/servo/servo/blob/b35729b6e0e16ec4134a1acbb0a24a7bb0a36f0a/components/script/dom/bindings/codegen/CodegenRust.py#L5307)):*
> ```Python
>             initParent = ("parent: match try!(%s::%s::new(cx, val)) {\n"
>                           "            ConversionResult::Success(v) => v,\n"
>                           "            _ => return Err(()),\n"
> ```

Missing throw here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12954#-:-KPvxnmnWIUWWpDummBm:bo47p9t)*

**Comment by GuillaumeGomez** [comment]
*[components/script/dom/htmlcanvaselement.rs, line 163 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12954#-KPvxMhCCvZK-m-0VhH2:-KPw6ErYr793Y6d3xVuf:bpq7gpq) ([raw file](https://github.com/servo/servo/blob/b35729b6e0e16ec4134a1acbb0a24a7bb0a36f0a/components/script/dom/htmlcanvaselement.rs#L163)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> You didn't throw in the case of `ConversionResult::Failure` here.
</details>
Because in case of errors, it returns None instead of an error so I tried to keep the same logic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12954)*

**Comment by GuillaumeGomez** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/conversions.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12954#-KPvxZd9AtDsEmsYEKOb:-KPw6Pp44g8MX9SaEald:b2nreh6) ([raw file](https://github.com/servo/servo/blob/b35729b6e0e16ec4134a1acbb0a24a7bb0a36f0a/components/script/dom/bindings/conversions.rs#L87)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Missing throw on failure here.
</details>
Same as above.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 5307 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12954#-KPvxiczFowBXW2hB2HJ:-KPw6S0L-XKUtUswVxrv:b2nreh6) ([raw file](https://github.com/servo/servo/blob/b35729b6e0e16ec4134a1acbb0a24a7bb0a36f0a/components/script/dom/bindings/codegen/CodegenRust.py#L5307)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Missing throw here.
</details>
Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12954)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmlcanvaselement.rs, line 163 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12954#-KPvxMhCCvZK-m-0VhH2:-KPw6eGVrxwfmE8yl6KQ:bgv4m58) ([raw file](https://github.com/servo/servo/blob/b35729b6e0e16ec4134a1acbb0a24a7bb0a36f0a/components/script/dom/htmlcanvaselement.rs#L163)):*
<details><summary><i>Previously, GuillaumeGomez (Guillaume Gomez) wrote…</i></summary>
> Because in case of errors, it returns None instead of an error so I tried to keep the same logic.
</details>
When the trait returns `Err(())`, it threw something. So you need to throw on `ConversionResult::Failure` too otherwise it makes no sense.

---

*[components/script/dom/bindings/conversions.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12954#-KPvxZd9AtDsEmsYEKOb:-KPw6ocDAEMhQ7A8DFCk:b-816h6l) ([raw file](https://github.com/servo/servo/blob/b35729b6e0e16ec4134a1acbb0a24a7bb0a36f0a/components/script/dom/bindings/conversions.rs#L87)):*
<details><summary><i>Previously, GuillaumeGomez (Guillaume Gomez) wrote…</i></summary>
> Same as above.
</details>
Same.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 5307 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12954#-KPvxiczFowBXW2hB2HJ:-KPw6pO3bmaIQQPlS81X:b-816h6l) ([raw file](https://github.com/servo/servo/blob/b35729b6e0e16ec4134a1acbb0a24a7bb0a36f0a/components/script/dom/bindings/codegen/CodegenRust.py#L5307)):*
<details><summary><i>Previously, GuillaumeGomez (Guillaume Gomez) wrote…</i></summary>
> Same as above.
</details>
Same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12954)*

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12954#-:-KPwGgR75vcUINFmvCiC:bkg9nno)*

**Pull request merged**
