### PR TITLE
Resets selection in textinput when its content is changed

### PR DESCRIPTION
**Pull request by saurvs**
Fixes https://github.com/servo/servo/issues/10005.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10015)

### CODE REVIEW

**Comment by jdm** [comment]
This fix looks good. Can we [add a test](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) to tests/wpt/web-platform-tests/html/semantics/forms/textfieldselection/ that verifies the behaviour of `selectionStart` and `selectionEnd` after resetting the value of the input field containing a selection (using [the specification](https://html.spec.whatwg.org/multipage/forms.html#dom-input-value) as a guide)?

**Comment by saurvs** [comment]
@jdm Yes.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes -S-needs-tests 

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/wpt/web-platform-tests/html/semantics/forms/textfieldselection/selection-after-content-change.html, line 11 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10015#-KCzlvS6in-PBPJCw1QC:-KCzlvS6in-PBPJCw1QD:-1875289996) ([raw file](https://github.com/servo/servo/blob/d30da3537d8d29f85a15373f6abc1cc5b043c4f2/tests/wpt/web-platform-tests/html/semantics/forms/textfieldselection/selection-after-content-change.html#L11)):*
Let's assert the correct values of selectionStart and selectionEnd here.

---

*[tests/wpt/web-platform-tests/html/semantics/forms/textfieldselection/selection-after-content-change.html, line 12 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10015#-KCzlzj2rjmWRUKoUpCP:-KCzlzj2rjmWRUKoUpCQ:-1766950255) ([raw file](https://github.com/servo/servo/blob/d30da3537d8d29f85a15373f6abc1cc5b043c4f2/tests/wpt/web-platform-tests/html/semantics/forms/textfieldselection/selection-after-content-change.html#L12)):*
Let's use a non-empty value, then assert that selectionStart and selectionEnd are both set to the end of the string.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10015#-:-KCzm6tBOZCDVAgNYH9k:-1157434331)*

**Comment by saurvs** [comment]
@jdm I've made the change.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10015#-:-KD--TlC-lpGmvBjyYyt:-1746383326)*

**Comment by jdm** [comment]
@bors-servo: r-
Sorry, needs to be rebased first.

**Comment by jdm** [comment]
For the record, there's no need to close the PR and delete the branch. You can rebase the branch on top of the latest changes from the master branch and force push the result.

**Comment by saurvs** [comment]
@jdm Sorry about this, but I wasn't able to resolve rebase conflicts in my fork. I've opened a new PR with the same commit https://github.com/servo/servo/pull/10035.

**Pull request closed without merging**
