### PR TITLE
Fixes the problem with canvas not being rendered when displayed as block level elements

### PR DESCRIPTION
**Pull request by dmarcos**

### CODE REVIEW

**Comment by jdm** [comment]
@glennw Does this make sense?

**Comment by glennw** [comment]
@jdm The spec references I can find say that canvas is "sometimes" considered to be a replaced element (https://html.spec.whatwg.org/multipage/rendering.html appears to be relevant). This change seems reasonable to me, although we should update the comment above this function.

**Comment by dmarcos** [comment]
@glennw I just updated the comment. If you have something in mind that would be more helpful just let me know and I'll change it.

**Comment by glennw** [comment]
@dmarcos Thanks! I forgot to mention in my last comment, would you be able to add a simple ref test to make sure this doesn't regress in the future?

**Comment by dmarcos** [comment]
@glennw I added the ref test. How can I run it to verify that the results of the test and the reference match?

**Comment by glennw** [comment]
If you add an entry to the basic.list file, and then run ./mach test-ref --kind=cpu this will run your test (and all the other ref tests). You can verify yours was run by checking the log output. Also note that tests need to be listed in alphabetical order in that file :)

**Comment by dmarcos** [comment]
@glennw Thanks! Is it possible to run just one test? On OSX If I run them all zillion of windows start to pop up that steal the mouse and keyboard focus and my laptop becomes unusable :)

I pushed the ref test to the PR and added it to the basic.list file. Anything else do you want me to do?

**Comment by dmarcos** [comment]
@glennw Thanks! Is it possible to run just one test? On OSX If I run them all zillion of windows start to pop up that steal the mouse and keyboard focus and my laptop becomes unusable :)

I pushed the ref test to the PR and added it to the basic.list file. Anything else do you want me to do?

**Comment by jdm** [comment]
I believe that `./mach test tests/ref/canvas_as_block_element_a.html` is supposed to allow running a particular reftest, or `./mach test-ref canvas_as_block_element`.

**Pull request closed without merging**
