### PR TITLE
Support build.rustflags in .servobuild

### PR DESCRIPTION
**Pull request by vvuk**
Add ability to specify rustflags in .servobuild.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14251)

### CODE REVIEW

**Comment by emilio** [comment]
CI is read with a `KeyError`, so I think this may need something else. Also, could you add a description for it in `servobuild.example`?

**Comment by Ms2ger** [comment]
It might be useful to print a message to the console if this changes anything.

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
Is there a way to see what tests failed on check intermittents?

**Pull request merged**
