### PR TITLE
Make shadow values share more code

### PR DESCRIPTION
**Pull request by upsuper**
Make `text-shadow` reuse `Shadow` type directly.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because refactor

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17199)

### CODE REVIEW

**Comment by Manishearth** [comment]
r=me

BUT, we can share more code -- do the same thing I did with SVGPaint, and move shadow into `values::generics` as `Shadow<T>`. Specified is `Shadow<specified::Color>`, computed is `Shadow<computed::Color>`, interpolate is `Shadow<IntermediateColor>`. Use the same kind of `convert` fn from the other thing to make the conversions easy.

**Comment by upsuper** [comment]
Probably. But that aren't going to help my color refactor patch, so I prefer just leave it as-is for now :)

**Comment by upsuper** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=28aa076a448fdae79bcafbb570615085b92891d6

**Comment by Manishearth** [comment]
Works. Try to fix that once the color stuff lands, or ask nox :P

@bors-servo r+

**Pull request merged**
