### PR TITLE
Implement pattern fill style for canvas.

### PR DESCRIPTION
**Pull request by hyowon**
Issue #6056
Depends on servo/rust-azure#160

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6157)

### CODE REVIEW

**Comment by hyowon** [comment]
cc @jdm 
cc @yichoi

**Comment by nox** [comment]
Review status: all files reviewed, 7 unresolved discussions, all commit checks successful.
Reviewed files:
- components/canvas_traits/lib.rs @ r1
- components/script/dom/bindings/trace.rs @ r1
- components/script/dom/canvaspattern.rs @ r1
- components/script/dom/canvasrenderingcontext2d.rs @ r2
- components/script/dom/webidls/CanvasRenderingContext2D.webidl @ r1
- tests/wpt/metadata/2dcontext/compositing/2d.composite.globalAlpha.imagepattern.html.ini @ r3
- tests/wpt/metadata/2dcontext/compositing/2d.composite.uncovered.pattern.copy.html.ini @ r3
- tests/wpt/metadata/2dcontext/compositing/2d.composite.uncovered.pattern.destination-atop.html.ini @ r3
- tests/wpt/metadata/2dcontext/compositing/2d.composite.uncovered.pattern.destination-in.html.ini @ r3
- tests/wpt/metadata/2dcontext/compositing/2d.composite.uncovered.pattern.source-in.html.ini @ r3
- tests/wpt/metadata/2dcontext/compositing/2d.composite.uncovered.pattern.source-out.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.animated.gif.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.basic.image.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.basic.type.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.crosscanvas.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.broken.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.string.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.undefined.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.modify.image1.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.modify.image2.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.basic.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord1.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord2.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.outside.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.orientation.image.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.basic.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.coord1.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.coord2.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.coord3.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.outside.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeatx.basic.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeatx.outside.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeaty.basic.html.ini @ r3
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeaty.outside.html.ini @ r3
- tests/wpt/metadata/2dcontext/shadows/2d.shadow.pattern.transparent.1.html.ini @ r3

---

<sup>**[components/canvas_traits/lib.rs, line 297 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqH9PiB3Jv8EynxfCgk)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/canvas_traits/lib.rs#L297)):</sup>
Are the explicit values actually needed?

---

<sup>**[components/script/dom/canvaspattern.rs, line 10 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHA4qvBJsyljaYhkMH)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/script/dom/canvaspattern.rs#L10)):</sup>
Nit: superfluous braces.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 12 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHIxUo9DKcBRGzSl0p)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/script/dom/canvasrenderingcontext2d.rs#L12)):</sup>
I would just import Error and qualify its constructors, that's what is done in most other DOM implementations AFAICT.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 980 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHIsXAGLiDIQ2XRSVH)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/script/dom/canvasrenderingcontext2d.rs#L980)):</sup>
SyntaxError, says the specification.

---

<sup>**[tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHMOd-8xFcwLa3hnVG)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini#L4)):</sup>
Why does this test fail?

---

<sup>**[tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.string.html.ini, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHMPIpdaPnR5sAHyWk)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.string.html.ini#L4)):</sup>
Same remark about failing test.

---

<sup>**[tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.undefined.html.ini, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHMTklowLcQ33qUH2F)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.undefined.html.ini#L4)):</sup>
Same remark about failing test.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6157)

**Comment by hyowon** [comment]
Review status: 34 of 36 files reviewed, 7 unresolved discussions, some commit checks failed.

---

<sup>**[components/canvas_traits/lib.rs, line 297 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqH9PiB3Jv8EynxfCgk)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/canvas_traits/lib.rs#L297)):</sup>
No, they seem to not need the explicit values.

---

<sup>**[components/script/dom/canvaspattern.rs, line 10 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHA4qvBJsyljaYhkMH)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/script/dom/canvaspattern.rs#L10)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 12 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHIxUo9DKcBRGzSl0p)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/script/dom/canvasrenderingcontext2d.rs#L12)):</sup>
I tried to search using Error in other files.
But this kind of using Error seems to be common.
I'm sorry but could you show me an example?

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 980 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHIsXAGLiDIQ2XRSVH)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/script/dom/canvasrenderingcontext2d.rs#L980)):</sup>
Done.

---

<sup>**[tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHMOd-8xFcwLa3hnVG)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini#L4)):</sup>
Canvas pattern tests have not been performed properly in the meantime.
These new failed tests are to check invalid parameters in CreatePattern. 
Actually I have no idea where I can catch them and return errors.
I am a newbie. I'll try to fix it if you give me some advice,
or is it a bad idea to leave them as another issue?

---

<sup>**[tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.string.html.ini, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHMPIpdaPnR5sAHyWk)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.string.html.ini#L4)):</sup>
Ditto.

---

<sup>**[tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.undefined.html.ini, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHMTklowLcQ33qUH2F)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.undefined.html.ini#L4)):</sup>
Ditto.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6157)

**Comment by hyowon** [comment]
@nox Thank you for your review! :D

**Comment by nox** [comment]
```
$ ./mach test-tidy
components/script/dom/canvaspattern.rs:40: (much) overlong line
components/script/dom/canvasrenderingcontext2d.rs:830: (much) overlong line
```

**Comment by nox** [comment]
Review status: all files reviewed, 3 unresolved discussions, some commit checks failed.
Reviewed files:
- components/script/dom/canvaspattern.rs @ r4
- components/script/dom/canvasrenderingcontext2d.rs @ r4

---

<sup>**[components/canvas_traits/lib.rs, line 297 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqH9PiB3Jv8EynxfCgk)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/canvas_traits/lib.rs#L297)):</sup>
Remove them then, if they are not useful. :)

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 12 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHIxUo9DKcBRGzSl0p)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/script/dom/canvasrenderingcontext2d.rs#L12)):</sup>
Apparently I'm wrong and more often constructors themselves are imported in scope. Oh well.

---

<sup>**[tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHMOd-8xFcwLa3hnVG)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini#L4)):</sup>
The createPattern method used to not exist at all, so obviously the tests passed before. Not a bad idea to leave them as another issue, I was just being curious.

It's quite weird because CodegenRust should have generated code that reject such values. I would like to take a look at the generated code but I didn't manage to build Servo with your rust-azure fork.

Please just file a follow-up issue or I'll do it myself.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6157)

**Comment by nox** [comment]
Two general remarks:

* How did you manage to build and run the tests with the rust-azure PR? I get:
```
/Users/nox/src/servo/components/canvas/canvas_paint_task.rs:82:28: 82:78 error: this function takes 3 parameters but 2 parameters were supplied [E0061]
/Users/nox/src/servo/components/canvas/canvas_paint_task.rs:82         let draw_options = DrawOptions::new(self.state.draw_options.alpha, 0);
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/nox/src/servo/components/canvas/canvas_paint_task.rs:178:27: 178:51 error: this function takes 3 parameters but 2 parameters were supplied [E0061]
/Users/nox/src/servo/components/canvas/canvas_paint_task.rs:178             draw_options: DrawOptions::new(1.0, 0),
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~
```

* I think we generally prefer if there are no commits where tests could end up with unexpected results, the test commit should be squashed with its predecessor.

**Comment by hyowon** [comment]
Building servo with my rust-azure is being broken because servo/rust-azure@faba68 was already merged but the relevant patch #6065 is in progress.

So I've been working with a temporary branch 'my_commits' in hyowon/rust-azure.
Please checkout the 'my_commits' branch for rust-azure if you want to build and test this PR.
Sorry for the inconvenience.

---

Review status: all files reviewed, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/canvas_traits/lib.rs, line 297 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqH9PiB3Jv8EynxfCgk)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/canvas_traits/lib.rs#L297)):</sup>
Done.

---

<sup>**[components/script/dom/canvasrenderingcontext2d.rs, line 12 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHIxUo9DKcBRGzSl0p)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/components/script/dom/canvasrenderingcontext2d.rs#L12)):</sup>
That's no problem. :)

---

<sup>**[tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini, line 4 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6157#-JqHMOd-8xFcwLa3hnVG)** ([raw file](https://github.com/servo/servo/blob/9b32b80a5e6ce2219fc753bb5d5a21f0a617614d/tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini#L4)):</sup>
I've filed a new issue #6194.
Thank you in advance for spending your time on looking at this.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6157)

**Comment by nox** [comment]
```
components/script/dom/canvasrenderingcontext2d.rs:830: (much) overlong line
```

:)

**Comment by nox** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- components/canvas_traits/lib.rs @ r5
- components/script/dom/canvaspattern.rs @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6157)

**Comment by hyowon** [comment]
The 830 line in components/script/dom/canvasrenderingcontext2d.rs has only '}'.
I didn't even modify the line. It's weird. :(

**Comment by nox** [comment]
The problem is probably line 827.

**Comment by hyowon** [comment]
I've fixed it after rebase.

**Comment by nox** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/script/dom/bindings/trace.rs @ r6
- components/script/dom/canvasrenderingcontext2d.rs @ r6

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6157)

**Comment by Manishearth** [comment]
@bors-servo: r-

This apparently depends on another PR. Sorry.

**Comment by nox** [comment]
@hyowon If you rebase after #6206 is merged, the three failing tests will pass. :)

**Comment by hyowon** [comment]
@nox Great! Thank you.
I rebased and removed the failing tests, but still waiting for the review servo/rust-azure#160.

**Comment by nox** [comment]
@hyowon You're welcome. Feel free to squash all the commits together while the rust-azure PR gets taken care of (it's nicer for the expected test results to be with the changes themselves if we ever need to bisect).

**Comment by nox** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html.ini @ r7
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.string.html.ini @ r7
- tests/wpt/metadata/2dcontext/fill-and-stroke-styles/2d.pattern.image.undefined.html.ini @ r7

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6157)

**Comment by hyowon** [comment]
Squashed all reviewed commits.

**Comment by hyowon** [comment]
For the review comment from servo/rust-azure#160
r? @pcwalton

**Comment by nox** [comment]
I've updated azure in #6348.

**Comment by nox** [comment]
-S-awaiting-review 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/canvas/canvas_paint_task.rs @ r8

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6157)

**Comment by hyowon** [comment]
Thank you nox! I'll squash and rebase commits after landing #6348.

**Comment by nox** [comment]
@hyowon #6348 landed.

**Comment by hyowon** [comment]
@nox All done!

**Comment by nox** [comment]
@bors-servo: r+

-S-awaiting-review -S-needs-squash +S-awaiting-merge 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/canvas/canvas_paint_task.rs @ r9
- components/canvas_traits/lib.rs @ r9
- components/script/dom/bindings/trace.rs @ r9
- components/script/dom/canvasrenderingcontext2d.rs @ r9
- components/script/dom/webidls/CanvasRenderingContext2D.webidl @ r9

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6157)

**Comment by hyowon** [comment]
@nox Please retry~

**Pull request merged**
