### PR TITLE
Support font-style in geckolib

### PR DESCRIPTION
**Pull request by mbrubeck**
r? @bholley

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11240)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Note: I couldn't get bindgen to output bindings for the `NS_STYLE_FONT_STYLE_` aliases of these constants, but apparently these [may be deprecated someday](https://dxr.mozilla.org/mozilla-central/rev/a884b96685aa13b65601feddb24e5f85ba861561/layout/style/nsStyleConsts.h#585) anyway, so I just went with the original names from `gfxFontConstants.h`.

**Comment by emilio** [comment]
@mbrubeck: Yeah, bindgen only gets numerical macros... Generic macros are hard, at least.

**Comment by mbrubeck** [comment]
@bors-servo retry

* #11100

**Pull request merged**
