### PR TITLE
Fix initial value of align-content and justify-content

### PR DESCRIPTION
**Pull request by mbrubeck**
This fixes a trivial mistake in #15533, caused by me misreading the spec. r? @Manishearth

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15594)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r-

wait, spec says that the initial values are stretch and flex-start?

**Comment by mbrubeck** [comment]
https://drafts.csswg.org/css-align/#propdef-align-content

> Name: 	`align-content`, `justify-content`
> Initial: 	normal

**Comment by Manishearth** [comment]
Ah. Please update the spec links, then 😄 . r=me

**Comment by mbrubeck** [comment]
cc #15583

**Pull request merged**
