### PR TITLE
Bug #10181 - Implement *-reverse flex-directions

### PR DESCRIPTION
**Pull request by shinglyu**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10987)

### CODE REVIEW

**Comment by shinglyu** [comment]
I ran the test 
```
./mach test-css tests/wpt/css-tests/css-flexbox-1_dev/html/
```
but got a LOT of timeouts
```
Ran 612 tests finished in 2425.0 seconds.
  • 78 ran as expected. 0 tests skipped.
  • 534 tests timed out unexpectedly
```

**Comment by danlrobertson** [comment]
I get the following on my server with no timeouts or failures. I get a lot of timeouts when I run test-css on my laptop though.

```
 ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/order-with-column-reverse.htm
```

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/layout/flex.rs, line 120 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10987#-KGqorV6ji1lyeTuuZqL:-KGqorV7MbdAR2PRdL5-:-1940037278) ([raw file](https://github.com/servo/servo/blob/f66961a2f81be006ebe7b4737107fc329f914f10/components/layout/flex.rs#L120)):*
Would this be more readable if this were collapsed into one match statement?

```rust

let (main_mode, is_reverse) = match fragment.style.get_position().flex_direction {
    flex_direction::T::row => (Mode::Inline, false),
    flex_direction::T::row_reverse => (Mode::Inline, true),
    ...
```

Just a thought...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10987#-:-KGqqw8ditFuLCgHLgAS:-2069202136)*

**Comment by jdm** [comment]
@shinglyu Are you using a debug or release build? Are there still timeouts if you run with `test-css --release`?

**Comment by shinglyu** [comment]
I didn't specify the build, so I guess it uses the debug build. I'll try it on release build on a more powerful machine.

**Comment by shinglyu** [comment]
Running 612 tests in web-platform-tests

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flex-flexitem-percentage-prescation.htm

  ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/order-with-column-reverse.htm

Unsupported test type wdspec for product servo
Ran 612 tests finished in 96.0 seconds.
  • 610 ran as expected. 0 tests skipped.
  • 2 tests passed unexpectedly

-------------
Let me check those two unexpected passing tests.

**Comment by danlrobertson** [comment]
> ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/order-with-column-reverse.htm

Is definitely expected given the contents of this PR.

> ▶ PASS [expected FAIL] /css-flexbox-1_dev/html/flex-flexitem-percentage-prescation.htm

Not sure what is going on here. I don't get this on my box.

**Comment by shinglyu** [comment]
`flex-flexitem-percentage-prescation.htm` on master branch build looks good (with `--pref layout.flex.enabled --pref layout.flex-direction.enabled`). I'm not sure why it's not passing before. I'll mark the two as passing.

Also I think the `order-with-row-reverse.htm` should pass too? I'll check it.

**Comment by mbrubeck** [comment]
@bors-servo delegate+

r=mbrubeck with one review comment addressed (below).

<details><summary><i>Previously, larsbergstrom (Lars Bergstrom) wrote…</i></summary>
> r? @mbrubeck </details>


---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/layout/flex.rs, line 284 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10987#-KHN7KW6EpV7_HmRm6bB:-KHN7KW6EpV7_HmRm6bC:-1710681679) ([raw file](https://github.com/servo/servo/blob/f66961a2f81be006ebe7b4737107fc329f914f10/components/layout/flex.rs#L284)):*
> ```Rust
>                 inline_child_start = inline_child_start - even_content_inline_size;
>             }
>         }
> ```

It would be nice if the `if` and `else` cases shared more code. Maybe add aa `direction` variable that is either `1` or `-1`, and initialize it along with `inline_child_start`.  Then you could have a single loop that ends with `inline_child_start = inline_child_start + even_content_inline_size * direction;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10987#-:-KHN8YxrQQPDwyCaKZE-:2032198471)*

**Comment by shinglyu** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/layout/flex.rs, line 284 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10987#-KHN7KW6EpV7_HmRm6bB:-KHOqNw0QAU54ZupEi9j:-283747628) ([raw file](https://github.com/servo/servo/blob/f66961a2f81be006ebe7b4737107fc329f914f10/components/layout/flex.rs#L284)):*
<details><summary><i>Previously, mbrubeck (Matt Brubeck) wrote…</i></summary>
> It would be nice if the `if` and `else` cases shared more code. Maybe add aa `direction` variable that is either `1` or `-1`, and initialize it along with `inline_child_start`.  Then you could have a single loop that ends with `inline_child_start = inline_child_start + even_content_inline_size * direction;`</details>
I end up using an `if...else` in the `for` loop, the `base.position.start.i` line also needs to be handled differently, so this willl make me use two flags, which I believe is dirty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10987)*

**Comment by mbrubeck** [comment]
@bors-servo r+

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.</details>


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10987#-:-KHQKnqzG0C8WS_PUwmU:1236647940)*

**Comment by danlrobertson** [comment]
I get a failure on my box too. I doubt this PR should affect this test... Did it change the outcome of this test on your machine?

<details><summary><i>Previously, highfive wrote…</i></summary>
>       ▶ FAIL [expected PASS] /css-flexbox-1_dev/html/flex-flexitem-percentage-prescation.htm
>       └   → /css-flexbox-1_dev/html/flex-flexitem-percentage-prescation.htm 549dc2995e7de786feb6065fc8fc76b53746d920
>     /css-flexbox-1_dev/html/reference/flex-flexitem-percentage-prescation-ref.htm 516cbcf7b447cf7d5a568a4f8b57f030555e6525
>     Testing 549dc2995e7de786feb6065fc8fc76b53746d920 == 516cbcf7b447cf7d5a568a4f8b57f030555e6525
>     </details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10987#-:-KHQl3kzdW2Zo3bubMT_:813358546)*

**Comment by mbrubeck** [comment]
That test is currently marked as failing on Linux only, but I have gotten unexpected PASS results on my Linux box.  It might be font-related.

**Comment by shinglyu** [comment]
This is indeed a font problem. I opened it in Reftest analyzer and the font looks different from my Linux Mint machine. There is a subtle font aliasing effect between the "r" and "b".

**Comment by shinglyu** [comment]
The test is relatively simple, it should have passed even without this patch. I will mark it as conditionally failing on Linux as before, and file a separate issue for it.

**Comment by shinglyu** [comment]
@mbrubeck I'm r+ing myself since I am only disabled the failing test. Hope you don't mind.

**Pull request merged**
