### PR TITLE
Properly expect a syntax error with :scope selectors in Element.closest

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14080)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Spec change deferring this feature: https://github.com/w3c/csswg-drafts/commit/9b7faa30f2f42b04eb96b32ee8152f856c9edc08

**Comment by upsuper** [comment]
Note that `:scope` is not removed or deferred from Selectors Level 4, and both Gecko (pre-Stylo) and Blink support that pseudo-class, so it is incorrect to mark it not parsable.

**Pull request merged**
