### PR TITLE
Reconstruct flows when text/font styles change

### LINKED ISSUE #6501: Some CSS text properties are not incremental layout safe
The following properties are used during text run construction and glyph shaping, which happens during flow construction.  When incremental layout is enabled, changes to these styles have no effect:

* text-rendering
* word-spacing
* letter-spacing
* text-transform
* font (and related longhands)

For example, hovering over the text in this example does not apply the expected letter-spacing:

```html
<html>
  <head>
    <style>
      p:hover { letter-spacing: 1em; }
    </style>
  </head>
  <body>
    <p>Hello, world!</p>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by mbrubeck**
These styles are used during text shaping.  When they change, we need to re-run shaping and construct new flows.

Fixes #6501. r? @pcwalton

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7656)

### CODE REVIEW

**Comment by pcwalton** [comment]
Looks good, feel free to add a reftest and r=me

**Comment by pcwalton** [comment]
```
Unexpected Results
================== 
/css21_dev/html4/first-letter-dynamic-002.htm
 ---------------------------------------------
FAIL [Parent]
```

**Comment by mbrubeck** [comment]
Updated to fix `first-letter-dynamic-002.htm` by adding the list and counter properties to `compute_damage`.  r? @pcwalton

**Pull request merged**
