### PR TITLE
Iterate over resize messages without building up Vec

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8480)

### CODE REVIEW

**Comment by Ms2ger** [comment]
```
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'DOMRefCell<T> already borrowed', src/libcore/option.rs:333
```

But that's not exactly a surprise, since you removed a comment that pointed that out.

**Comment by frewsxcv** [comment]
@Ms2ger Why was this closed?

**Comment by eefriedman** [comment]
Because the change you're proposing is impossible.  "Gather them first to avoid a double mut borrow on self."

**Comment by frewsxcv** [comment]
Why wouldn't

```diff
diff --git a/components/script/script_task.rs b/components/script/script_task.rs
index 12d3580..c017fab 100644
--- a/components/script/script_task.rs
+++ b/components/script/script_task.rs
@@ -737,14 +737,16 @@ impl ScriptTask {
     /// Handle incoming control messages.
     fn handle_msgs(&self) -> bool {
         // Handle pending resize events.
-        let page = self.page.borrow();
-        if let Some(page) = page.as_ref() {
-            // Only process a resize if layout is idle.
-            let resizes = page.iter()
-                              .map(|p| p.window())
-                              .filter_map(|window| window.steal_resize_event().map(|size| (window, size)));
-            for (window, size) in resizes {
-                self.handle_event(window.pipeline(), ResizeEvent(size));
+        {
+            let page = self.page.borrow();
+            if let Some(page) = page.as_ref() {
+                // Only process a resize if layout is idle.
+                let resizes = page.iter()
+                                  .map(|p| p.window())
+                                  .filter_map(|window| window.steal_resize_event().map(|size| (window, size)));
+                for (window, size) in resizes {
+                    self.handle_event(window.pipeline(), ResizeEvent(size));
+                }
             }
         }
```

address this issue?

**Comment by jdm** [comment]
Because `self.page` is borrowed while `handle_event` runs, which presumably ends up attempting to mutably borrow `self.page`?

**Comment by frewsxcv** [comment]
> which presumably ends up attempting to mutably borrow self.page?

It wasn't immediately obvious that `handle_event` mutably borrows `self.page`. Should there be an assert in there; something like `assert!(self.page.try_borrow_mut())`?

**Pull request closed without merging**
