### PR TITLE
Add headless rendering mode, and run WPT tests with Webrender enabled.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12989)

### CODE REVIEW

**Comment by glennw** [comment]
DO NOT MERGE!

(This PR is for testing on the build machines)

**Comment by glennw** [comment]
@aneeshusa @metajack @larsbergstrom This is failing to build on the linux builders (says it can't find libedit to link to in the travis logs).

Any idea why this would happen? I thought libedit would be installed on all ubuntu base machines. I created a local 14.04.5 ubuntu VM, and managed to build successfully without having to install libedit.

I could try to just add libedit to the dependencies list in saltfs, but it seems like it might be something else, since I didn't have that problem on a local VM.

Any ideas?

**Comment by glennw** [comment]
cc @edunham too for any ideas on the question above.

**Comment by larsbergstrom** [comment]
Hrm, yeah, the package for libedit-dev definitely got added to the Travis images:
https://github.com/travis-ci/travis-ci/issues/3581

I do notice that the files are in an architecture-specific path:
https://packages.debian.org/jessie/amd64/libedit2/filelist
https://packages.debian.org/jessie/amd64/libedit-dev/filelist

i.e.,
```
/usr/lib/x86_64-linux-gnu/libedit.a
/usr/lib/x86_64-linux-gnu/libedit.so
```

Can you ensure that Travis is passing the right thing? I don't see the full link args. I wonder if we should change the `--verbose` argument to mach to pass `-vv` to cargo so we always get more link info...

**Comment by larsbergstrom** [comment]
Try run results is a different failure:
```
--- stderr
configure: error: Gallium R300 requires libdrm >= 2.4.66
thread 'main' panicked at 'failed with: exit code: 1', /home/servo/.cargo/git/checkouts/osmesa-src-ed2f4797e32a9816/master/build.rs:32
stack backtrace:
   1:     0x7fc6ffb8bfb9 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7fc6ffb90a0c - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7fc6ffb8fece - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7fc6ffb90538 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7fc6ffb903d2 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7fc6ffb90300 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7fc6ffb84595 - build_script_build::run::h51e1a95477074626
                        at /home/servo/.cargo/git/checkouts/osmesa-src-ed2f4797e32a9816/master/build.rs:8
   8:     0x7fc6ffb84114 - build_script_build::main::hdb10ef502e468ae2
                        at /home/servo/.cargo/git/checkouts/osmesa-src-ed2f4797e32a9816/master/build.rs:9
   9:     0x7fc6ffb984f6 - __rust_maybe_catch_panic
  10:     0x7fc6ffb8f632 - std::rt::lang_start::h352a66f5026f54bd
  11:     0x7fc6ffb84623 - main
  12:     0x7fc6fef78f44 - __libc_start_main
  13:     0x7fc6ffb80688 - <unknown>
  14:                0x0 - <unknown>
```

**Comment by larsbergstrom** [comment]
```
--- stderr
Package libva was not found in the pkg-config search path.
Perhaps you should add the directory containing `libva.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libva' found
Package libva was not found in the pkg-config search path.
Perhaps you should add the directory containing `libva.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libva' found
/home/servo/.cargo/git/checkouts/osmesa-src-ed2f4797e32a9816/master/mesa-12.0.1/bin/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [/home/servo/.cargo/git/checkouts/osmesa-src-ed2f4797e32a9816/master/mesa-12.0.1/aclocal.m4] Error 127
thread 'main' panicked at 'failed with: exit code: 2', /home/servo/.cargo/git/checkouts/osmesa-src-ed2f4797e32a9816/master/build.rs:34
stack backtrace:
   1:     0x7f13945abed3 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7f13945b0efc - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7f13945b03be - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7f13945b0a28 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7f13945b08c2 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7f13945b07f0 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7f13945a41b8 - build_script_build::run::h51e1a95477074626
   8:     0x7f13945a3f28 - build_script_build::main::hdb10ef502e468ae2
   9:     0x7f13945b89e6 - __rust_maybe_catch_panic
  10:     0x7f13945afb22 - std::rt::lang_start::h352a66f5026f54bd
  11:     0x7f139399bf44 - __libc_start_main
  12:     0x7f13945a3618 - <unknown>
  13:                0x0 - <unknown>
```

**Comment by glennw** [comment]
OK, this appears to be correctly building OSMesa and running the tests in software rendering mode now. The failures are (mostly) expected differences - I will be investigating the list of failures and providing updated test expectations. I think the test run under WR is also *much* slower, but I am working on a fix for this as well. Hopefully once those two issues are resolved we can enable WR2 on CI.

**Comment by glennw** [comment]
Reminder to myself - look into the scrollTo differences and see if that hack can be removed now.

**Comment by samlh** [comment]
The test times seem to match the previous times exactly: 😄

linux wpt before: 15:36
linux wpt after: 14:14
linux css before: 13:03
linux css after: 13:31

mac wpt before: 42:11
mac wpt after: 41:28
mac css before: 25:42
mac css after: 25:41

It looks like there are a few tests left to fix or mark as expected failures, however.

**Comment by glennw** [comment]
@samlh Great, thanks for checking the times! I did some work on making them faster today, so that's good to know the timing won't regress :) I'll work on fixing / updating tests for the remaining failures on Monday and then we should be just about there.

**Comment by glennw** [comment]
:+1: :boom: :metal:

**Comment by glennw** [comment]
Closing in order to open a fresh PR for review.

**Pull request closed without merging**
