### PR TITLE
Split chan and receiver_port into script and compositor flavors

### PR DESCRIPTION
**Pull request by KiChjang**
Partial #8356. Currently this doesn't build because of a lint denying me to user unsafe code, which unfortunately the select! macro falls under. Not sure what to do there.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8478)

### CODE REVIEW

**Comment by jdm** [comment]
See if `#[allow(unsafe_code)]` above `fn run` fixes it?

**Comment by Ms2ger** [comment]
Can you use "sender" and "receiver" rather than "chan" and "port" when you're renaming things?

**Comment by Ms2ger** [comment]
Looks good; please squash into one commit and ping me.

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r+

**Pull request merged**
