### PR TITLE
add (un)premultiply tables for canvas {Get,Put}ImageData operations

### PR DESCRIPTION
**Pull request by froydnj**
Pretty straightforward use of lookup tables to replace a bunch of expensive float operations.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8086)

### CODE REVIEW

**Comment by jdm** [comment]
Let's move it out of script/dom/ into dom/; the ideal is that the only files in dom/ are implementing specific web APIs. Otherwise this looks fine!

**Comment by jdm** [comment]
@froydnj Also, are we sure that the table doesn't get inlined? `pub static` would be guaranteed to avoid that.

**Comment by froydnj** [comment]
> Let's move it out of script/dom/ into dom/; the ideal is that the only files in dom/ are implementing specific web APIs.

Which `dom/` directory are you talking about here?  The only `dom/` directory I see is `components/script/dom/`, so I am a little confused where else I should put the new file.

**Comment by jdm** [comment]
Erk, I meant out of `script/dom/` and into `script/`.

**Comment by froydnj** [comment]
The `pub static` thing is a good point; changed.  Too much C++, not enough Rust.

Maybe there should be a lint check or a warning for `const` non-scalar objects?

**Comment by froydnj** [comment]
OK, so the previous push had green tests, but this push (which essentially did `s/const/static/`) is broken.  Looking at the failing tests, it does look like they might be affected by this change, but I am also confused why the tests were green prior.  Did a different set of tests get run, or are the failing tests known intermittents?

**Comment by jdm** [comment]
Oh, travis only builds Servo; it doesn't run any tests.

**Comment by jdm** [comment]
Also note that the reported tests are PASS expected FAIL, i.e. the result was known to be wrong previously, and these changes have corrected the underlying problem. Please update the appropriate ini files :)

**Comment by froydnj** [comment]
\o/ for optimizations *and* correctness!

**Comment by Ms2ger** [comment]
How did we fail them before? Rounding issues?

**Comment by froydnj** [comment]
> How did we fail them before? Rounding issues?

Not sure, #5030 doesn't seem to explain why they were XFAIL'd.  `putImageData(getImageData())` seems likely to suffer from rounding issues; `putImageData` on non-solid data...maybe there were some rounding issues there too?

**Comment by nox** [comment]
@froydnj Could you squash the two last commits together before someone r+ it? I don't like commits which aren't with their expectation changes.

**Comment by froydnj** [comment]
> @froydnj Could you squash the two last commits together before someone r+ it? I don't like commits which aren't with their expectation changes.

Sure.

**Pull request merged**
