### PR TITLE
style: Cleanup the animated value setup.

### PR DESCRIPTION
**Pull request by emilio**
We have three different enums to represent slightly different things. Reuse them
properly, and kill some code in the animated_properties module while at it.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18604)

### CODE REVIEW

**Comment by emilio** [comment]
r? @nox 

cc @hiikezoe @BorisChiou

**Comment by emilio** [comment]
(@BorisChiou and @hiikezoe, please feel free to review too!)

**Comment by emilio** [comment]
@bors-servo try

 * Fixed up tidy

**Comment by emilio** [comment]
This is green on Geckotry too (font-size clamping issue is #18609):

https://treeherder.mozilla.org/#/jobs?repo=try&revision=0de6823d64043d8a805070debdff07c4f6987dc7

**Comment by nox** [comment]
Looks good, looks green, looks like it should land!

@bors-servo r+

**Comment by emilio** [comment]
@bors-servo r-

Per conversation with @hiikezoe, let's wait until https://bugzil.la/1402219 is resolved.

**Comment by emilio** [comment]
@bors-servo try

 * Rebased

**Comment by emilio** [comment]
@bors-servo r=nox

 * https://treeherder.mozilla.org/#/jobs?repo=try&revision=78c6232a3771e232e1a172ca4699403c4d5afb55

**Pull request merged**
