### PR TITLE
stylo: querySelector{,All} optimizations.

### PR DESCRIPTION
**Pull request by emilio**
Bug: 1410624

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19108)

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0425]: cannot find function `Gecko_GetElementsWithId` in module `bindings`
   --> components/style/gecko/wrapper.rs:116:35
    |
116 |             let array = bindings::Gecko_GetElementsWithId(self.0, id.as_ptr());
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^ did you mean `Gecko_GetElementSnapshot`?

error: aborting due to previous error

error: Could not compile `style`.

```

**Comment by emilio** [comment]
Sigh, will never learn to update the bindings.

**Comment by jdm** [comment]
```
   Compiling stylo_tests v0.0.1 (file:///home/servo/buildbot/slave/linux-dev/build/tests/unit/stylo)
error[E0308]: mismatched types
  --> /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/stylo_tests-54775c72401fcd0a/out/check_bindings.rs:72:38
   |
72 |     [ Servo_SelectorList_QueryFirst, bindings::Servo_SelectorList_QueryFirst ];
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ incorrect number of function parameters
   |
   = note: expected type `unsafe extern "C" fn(&style::gecko_bindings::structs::nsINode, &style::gecko_bindings::structs::RawServoSelectorList, bool) -> *const style::gecko_bindings::structs::Element {servo_function_signatures::glue::Servo_SelectorList_QueryFirst}`
              found type `unsafe extern "C" fn(&style::gecko_bindings::structs::nsINode, &style::gecko_bindings::structs::RawServoSelectorList) -> *const style::gecko_bindings::structs::Element {style::gecko_bindings::bindings::Servo_SelectorList_QueryFirst}`

error[E0308]: mismatched types
  --> /home/servo/buildbot/slave/linux-dev/build/target/geckolib/debug/build/stylo_tests-54775c72401fcd0a/out/check_bindings.rs:73:36
   |
73 |     [ Servo_SelectorList_QueryAll, bindings::Servo_SelectorList_QueryAll ];
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ incorrect number of function parameters
   |
   = note: expected type `unsafe extern "C" fn(&style::gecko_bindings::structs::nsINode, &style::gecko_bindings::structs::RawServoSelectorList, *mut style::gecko_bindings::structs::nsSimpleContentList, bool) {servo_function_signatures::glue::Servo_SelectorList_QueryAll}`
              found type `unsafe extern "C" fn(&style::gecko_bindings::structs::nsINode, &style::gecko_bindings::structs::RawServoSelectorList, *mut style::gecko_bindings::structs::nsSimpleContentList) {style::gecko_bindings::bindings::Servo_SelectorList_QueryAll}`

error: aborting due to 2 previous errors

error: Could not compile `stylo_tests`.
```

**Comment by emilio** [comment]
Arrg, updated all the bindings now (before I cherrypicked the non-existent function in a gecko tree)

@bors-servo r=xidorn,bz

**Pull request merged**
