### PR TITLE
Add Partial Implementation of style DOM traits for Gecko, and some basic glue to let Gecko call into Servo

### PR DESCRIPTION
**Pull request by bholley**
The wrapper stuff is partially-complete, modulo some unimplemented methods. The glue code is just a toy for now. Regardless, I think it's worth getting some of this stuff in-tree to minimize breakage.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9284)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Please try to avoid using `transmute` for casts between raw pointer.

**Comment by bholley** [comment]
@SimonSapin r?

**Comment by SimonSapin** [comment]
As Ms2ger said, please avoid `transmute` and friends whenever possible. Some types can be implicitly coerced into "weaker" types based on context (e.g. passing `&T` to a method that takes `*const T`). In more cases the `as` operator can do an explicit cast. The list of all cases is at http://doc.rust-lang.org/nomicon/coercions.html and http://doc.rust-lang.org/nomicon/casts.html , while http://doc.rust-lang.org/nomicon/transmutes.html describes some of the interesting ways that `transmute` can introduce undefined behavior.

Additionally, `transmute` parameter type *and* return type are generic and do not need to be explicit in a call. Type inference can introduce "action at a distance" that can be dangerous when seemingly unrelated code is refactored.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[ports/geckolib/bindings.rs, line 1 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7vzw77Bf6yFsUxRIK3:-K7vzw77Bf6yFsUxRIK4:733707517) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/bindings.rs#L1)):*
Is this generated from a .h file? Where is that file?

Does this comment mean this file should not be edited directly? If so, how can it be regenerated?

---

*[ports/geckolib/wrapper.rs, line 62 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w7BbhZM044xZNFlR8:-K7w7BbhZM044xZNFlR9:616649280) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L62)):*
This can be `n as *const RawGeckoNode as *mut RawGeckoNode`. (Two `as` are needed because this is "adding" mutability.)

---

*[ports/geckolib/wrapper.rs, line 67 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w7n6f2L8SdLgiq86Y:-K7w7n6f2L8SdLgiq86Z:1021835989) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L67)):*
`Gecko_GetNodeData(self.node) as *mut _`

---

*[ports/geckolib/wrapper.rs, line 73 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w82H8pJIvh6PrG4fa:-K7w82H8pJIvh6PrG4fb:1143573010) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L73)):*
Nit: these can be `#[derive(Copy, Clone)]` on the struct.

---

*[ports/geckolib/wrapper.rs, line 99 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w8ZP5FwvEu1yzALuk:-K7w8ZP5FwvEu1yzALul:1514571591) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L99)):*
If I understand this code correctly, this codes interprets `&GeckoNode` as `&usize` and relies on `self.node` being the first field. (rustc can in theory reorder fields of non-`#[repr(C)]` structs.) This can be written safely `self.node as usize`.

---

*[ports/geckolib/wrapper.rs, line 106 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wC0F54qzRF-ll-Q9V:-K7wC0F6teaqq0ueOyPH:210267249) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L106)):*
`GeckoNode::from_raw(n.0 as *mut _)`

---

*[ports/geckolib/wrapper.rs, line 122 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wDn463GqzyfKAicAY:-K7wDn463GqzyfKAicAZ:-1698777594) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L122)):*
(There’s an `unimplemented!()` macro that does this.)

---

*[ports/geckolib/wrapper.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wCL6SeVUE24L5gFEj:-K7wCL6SeVUE24L5gFEk:772334374) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L135)):*
`let opaque = ptr as *mut ServoNodeData;`

---

*[ports/geckolib/wrapper.rs, line 162 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wDO45xTK5rZM6znkK:-K7wDO45xTK5rZM6znkL:1516823312) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L162)):*
`from_raw(self.node as *mut _)`

---

*[ports/geckolib/wrapper.rs, line 280 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wELUTFrWd0zLbtkRc:-K7wELUTFrWd0zLbtkRd:1499333801) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L280)):*
`from_raw(self.document as *mut _)`

---

*[ports/geckolib/wrapper.rs, line 327 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wEejD5luNKphOZzkU:-K7wEejD5luNKphOZzkV:253362298) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L327)):*
`from_raw(self.element as *mut _)`

---

*[ports/geckolib/wrapper.rs, line 345 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wFaRcSlHdvT1yFJXE:-K7wFaRd0T3rHTGAkXmK:-503847625) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L345)):*
`ElementState::from_bits_truncate(Gecko_ElementState(self.element))`

---

*[ports/geckolib/wrapper.rs, line 477 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wH-2tbVWPVSe5okJ4:-K7wH-2tbVWPVSe5okJ5:741801632) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L477)):*
Some of this can probably move to rust-selectors.

---

*[ports/geckolib/wrapper.rs, line 501 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wF-7AuXGzKBekGiXs:-K7wF-7AuXGzKBekGiXt:1111268184) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L501)):*
`transmute` can be removed with `(ptr as *const u8).as_ref()` at the beginning.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9284#-:-K7w9b7pYmKmdUtV-dkM:-487050858)*

**Comment by bholley** [comment]
Thanks for the explanation! I've removed all of the transmutes in geckolib, and also removed a few from components/layout/wrapper.rs while I was at it. :-)

---

Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[ports/geckolib/bindings.rs, line 1 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7vzw77Bf6yFsUxRIK3:-K7wQ1rjdbpELICfC7vU:-655227989) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/bindings.rs#L1)):*
Yes. The .h file is in the gecko stylo branch: https://github.com/bholley/gecko-dev/blob/stylo/layout/servo/ExternalAPI.h

The file is generated by rust-bindgen. We have a script to regenerate it in the servo stylo branch: https://github.com/bholley/servo/blob/stylo/ports/geckolib/regen_bindings.rs

But that script is not very general, so I left it in the branch instead of checking it in. I could check it in if you want, but realistically someone needs to be pretty involved with what we're doing to properly regenerate the bindings at this point.

I would comment the file better, but that would get overwritten each time we regenerated the bindings. :-(

---

*[ports/geckolib/wrapper.rs, line 62 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w7BbhZM044xZNFlR8:-K7w_3DOFAgHNaq6r_Qb:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L62)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 67 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w7n6f2L8SdLgiq86Y:-K7w_4KXc774vLxZ_jNh:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L67)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 73 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w82H8pJIvh6PrG4fa:-K7w_8Ym9JsOs4B6sEKA:263332471) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L73)):*
When I tried that before, Rust issued warnings about deriving Clone on structs with raw pointers. Trying it again they don't appear though. I wonder why.

---

*[ports/geckolib/wrapper.rs, line 99 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w8ZP5FwvEu1yzALuk:-K7waYh76Qm_TmtSTBWC:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L99)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 106 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wC0F54qzRF-ll-Q9V:-K7waZO-FWOugqwNgGD3:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L106)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 122 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wDn463GqzyfKAicAY:-K7wbu9dDUZ83aKMHZIA:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L122)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wCL6SeVUE24L5gFEj:-K7waqeFstfeA8YJRqZh:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L135)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 162 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wDO45xTK5rZM6znkK:-K7warIiEo7GpTCdcAeH:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L162)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 280 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wELUTFrWd0zLbtkRc:-K7warwj1aEqNoJOeV2S:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L280)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 327 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wEejD5luNKphOZzkU:-K7wasZguGMY056dQJHQ:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L327)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 345 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wFaRcSlHdvT1yFJXE:-K7watBindIuohd9KV8-:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L345)):*
Done.

---

*[ports/geckolib/wrapper.rs, line 477 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wH-2tbVWPVSe5okJ4:-K7wbvURC0nfPGxvM071:188452576) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L477)):*
Agreed, but let's not worry about that for now.

---

*[ports/geckolib/wrapper.rs, line 501 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7wF-7AuXGzKBekGiXs:-K7wauHccVLPHKEsp7RF:-499146009) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L501)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9284#-:-K7wPt35WClr37kMZisd:726838047)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ports/geckolib/bindings.rs, line 1 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7vzw77Bf6yFsUxRIK3:-K7xLTqcMbcpku9Rnabi:-864129207) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/bindings.rs#L1)):*
Ok. This was mostly out of curiosity. This is fine for now, but you may want to have a README file eventually.

---

*[ports/geckolib/wrapper.rs, line 73 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w82H8pJIvh6PrG4fa:-K7xL-ryH9PYkhtSXO9q:-1388042999) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L73)):*
How long ago was this? I think this warning was made silent by default at some point.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9284#-:-K7xLiINi3rpdmc7VqK2:1236647940)*

**Comment by bholley** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ports/geckolib/wrapper.rs, line 73 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9284#-K7w82H8pJIvh6PrG4fa:-K7xN50QuV1LuyPIYOLa:1086322273) ([raw file](https://github.com/servo/servo/blob/c468b49297c699d3387086701b0c757ac0b7db9e/ports/geckolib/wrapper.rs#L73)):*
That's probably it. This was probably in November or December when I wrote the code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9284)*

**Pull request merged**
