### PR TITLE
now using external ref_slice instead of the std version fixed #8695

### LINKED ISSUE #8695: Remove warnings on using deprecated std::slice::ref_slice
Recent versions of Rust have moved the `std::slice` module out of the standard library and instead put them into a new crate called [`ref_slice`](https://crates.io/crates/ref_slice). As a consequence, when building servo now, we get a lot of warning messages of the following form:
```
/home/keith/Workspace/servo/components/script/dom/node.rs:64:5: 64:26 warning: use of deprecated item: unclear whether belongs in libstd, #[warn(deprecated)] on by default
/home/keith/Workspace/servo/components/script/dom/node.rs:64 use std::slice::ref_slice;
                                                                 ^~~~~~~~~~~~~~~~~~~~~
```

Code: `components/script/dom/node.rs`, `components/script/dom/websocket.rs`
Documentation/crate-to-use: https://github.com/steveklabnik/ref_slice

### PR DESCRIPTION
**Pull request by jasonwilliams**
Fixes #8695.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8787)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo r-

I just noticed that this didn't update all three `Cargo.lock` files.  You can fix this by running `./mach cargo-update -p script`.

**Comment by Jayflux** [comment]
Thanks @mbrubeck  done now

**Comment by KiChjang** [comment]
Thanks for making this PR! Seeing all those warnings disappear is really nice.

**Comment by KiChjang** [comment]
Oh whoops, the PR failed tidy. Here's the output:
```
./components/script/lib.rs:56: extern crate statement is not in alphabetical order

	expected: ref_slice

	found: log

./components/script/dom/websocket.rs:35: use statement is not in alphabetical order

	expected: std::ptr

	found: std::sync::{Arc, Mutex}

./components/script/dom/websocket.rs:36: use statement is not in alphabetical order

	expected: std::sync::{Arc, Mutex}

	found: std::ptr
```

**Comment by Jayflux** [comment]
Thanks @KiChjang ive made those changes now

**Pull request merged**
