### PR TITLE
Rename check_no_unwrap.sh to check_no_panic.sh

### LINKED ISSUE #10930: Rename check_no_unwrap.sh to check_no_panic.sh
The `etc/ci/check_no_unwrap.sh` script checks that we don't call `unwrap()`, but after #10902 will also check for `panic!()`. It should be renamed to `etc/ci/check_no_panic.sh` to reflect the expanded scope.

We'll also need to update the `etc/ci/buildbot_steps.yml` file.

Blocked on servo/saltfs#316, #10902.

### PR DESCRIPTION
**Pull request by zeusintuivo**
- [X] rename etc/ci/check_no_unwrap.sh to etc/ci/check_no_panic.sh  
- [X] Replaced check_no_unwrap for check_no_panic
- [X] Rebased against Origin Mozilla/Master
- [X] Ran the build and tidy below without errors

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #10930 (github issue number if applicable).

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12384)

### CODE REVIEW

**Comment by KiChjang** [comment]
This is a duplicate of #10942. If the status of #10942 wasn't clear, it is being blocked from merging into master because of servo/saltfs#316.

**Comment by zeusintuivo** [comment]
Except this PR is passing.

**Comment by jdm** [comment]
Yes, because we control the travis CI environment from .travis.yml. The steps are different for our non-travis build machines.

**Comment by jdm** [comment]
I'm going to close this in favour of #10942. Thanks for trying to solve it, however!

**Pull request closed without merging**
