### PR TITLE
ImageMaps: Implemented support for parsing coord attribute to a shape…

### PR DESCRIPTION
**Pull request by shravan-achar**
Image Maps: Implemented support for parsing coord attribute to a shape object. Implemented a hit_test method that checks if a given point is within the area. Test cases for constructors and hit_test method included. 

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

… object in HTMLAreaElement

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13971)

### CODE REVIEW

**Comment by jdm** [comment]
@shravan-achar Why'd you close the PR?

**Comment by shravan-achar** [comment]
I had to close it since the CI failed due to merge errors. I am opening another PR now.

**Comment by KiChjang** [comment]
@shravan-achar You don't need to close PRs just to handle a rebase. You can first fetch from upstream master, rebase against it, and then force-push your branch to your remote. Does that make sense?

**Comment by shravan-achar** [comment]
I did that but also closed the PR. I didnt know I didnt have to close it. I get it now. Sorry :(

**Pull request closed without merging**
