### PR TITLE
stylo: `all` shorthand should not apply to internal properties

### PR DESCRIPTION
**Pull request by Manishearth**
r=xidorn https://bugzilla.mozilla.org/show_bug.cgi?id=1404057

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18734)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo retry

 - infra

**Comment by Manishearth** [comment]
@bors-servo retry

 - infra

you have to push a new commit to fix this one

**Comment by upsuper** [comment]
@bors-servo retry
* #18739

**Pull request merged**
