### PR TITLE
Draft. Change PaintContext rects to TypedRects #7023

### PR DESCRIPTION
**Pull request by mskrzypkows**
I created draft. I'm not sure if we need any units conversion in PaintContext. There is also strange 'clear' method, we use PagePx origin and ScreenPx size is it OK?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7696)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Thanks for the patch!  Here are a few comments...

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[components/gfx/display_list/mod.rs, line 486 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7696#-K-Kd-0AmqAM9hNsCzgX)** ([raw file](https://github.com/servo/servo/blob/55a3c0ce29a541757d9f869c5aafbe92bf99139e/components/gfx/display_list/mod.rs#L486)):</sup>
This could be `let tile_size = paint_context.screen_rect.as_f32().to_untyped();`


---

<sup>**[components/gfx/paint_context.rs, line 95 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7696#-K-KdCG1IaXmkKUpy_3e)** ([raw file](https://github.com/servo/servo/blob/55a3c0ce29a541757d9f869c5aafbe92bf99139e/components/gfx/paint_context.rs#L95)):</sup>
This should return a `ScaleFactor<PagePx, ScreenPx>`.  This could also benefit from servo/euclid#105 (requires updating the version of euclid used by Servo).


---

<sup>**[components/gfx/paint_context.rs, line 244 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7696#-K-Kdq4GG4WjAtcBmhwp)** ([raw file](https://github.com/servo/servo/blob/55a3c0ce29a541757d9f869c5aafbe92bf99139e/components/gfx/paint_context.rs#L244)):</sup>
Should `page_rect` be `screen_rect` here?

Also, I'm surprised that we are combining these different coordinates like this without scaling them. This may be a bug in the existing code.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7696)

**Comment by mskrzypkows** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/gfx/paint_context.rs, line 95 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7696#-K-KdCG1IaXmkKUpy_3e)** ([raw file](https://github.com/servo/servo/blob/55a3c0ce29a541757d9f869c5aafbe92bf99139e/components/gfx/paint_context.rs#L95)):</sup>
As I see newest version (0.2) is already used. Will there be update to other?
If I change ```screen_pixels_per_px``` to return ```ScaleFactor``` then I have to change implementation of ```to_nearest_pixel``` in geometry.rs, to use ```ScaleFactor```, right?


---

<sup>**[components/gfx/paint_context.rs, line 244 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7696#-K-Kdq4GG4WjAtcBmhwp)** ([raw file](https://github.com/servo/servo/blob/55a3c0ce29a541757d9f869c5aafbe92bf99139e/components/gfx/paint_context.rs#L244)):</sup>
I'll change to ```screen_rect```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7696)

**Comment by mbrubeck** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/gfx/paint_context.rs, line 95 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7696#-K-KdCG1IaXmkKUpy_3e)** ([raw file](https://github.com/servo/servo/blob/55a3c0ce29a541757d9f869c5aafbe92bf99139e/components/gfx/paint_context.rs#L95)):</sup>
I have now published euclid 0.2.1.

Yes, if you change this then the `to_nearest_pixel` should change to take ScaleFactor.  Feel free to leave this for a separate PR if you'd like.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7696)

**Comment by mbrubeck** [comment]
Oops, I didn't notice that my earlier attempt to publish euclid 0.2.1 failed.  Now it has been published successfully, and you can run `./mach cargo-update -p euclid` to update it in all of our Cargo.lock files.

**Comment by mskrzypkows** [comment]
OK, thanks :-)

**Comment by jdm** [comment]
Oops, this was rebased but also had build errors according to the travis log:
```
/home/travis/build/servo/servo/components/gfx/paint_context.rs:1647:46: 1647:59 error: mismatched types:

 expected `f32`,

    found `euclid::scale_factor::ScaleFactor<util::geometry::PagePx, util::geometry::ScreenPx, f32>`

(expected f32,

    found struct `euclid::scale_factor::ScaleFactor`) [E0308]

/home/travis/build/servo/servo/components/gfx/paint_context.rs:1647         Point2D::new(self.x.to_nearest_pixel(pixels_per_px) as AzFloat,

                                                                                                                 ^~~~~~~~~~~~~
```

**Comment by mskrzypkows** [comment]
Yes, I know that there are build errors, it's because my changes need update in ```app_unit``` module, ```to_nearest_pixel``` method should take ```ScaleFactor<PagePx, ScreenPx, f32>``` as argument. I don't know how to modify app_unit, because ```PagePx``` and ```ScreenPx``` are defined in ```util::geometry``` module which is not available from ```app_unit```. How can I use ```PagePx``` and ```ScreenPx``` from ```app_unit```?

**Comment by jdm** [comment]
It sounds like perhaps we should define PagePx and ScreenPx in app_unit instead.

**Comment by mbrubeck** [comment]
If you'd like to land the work you've done so far, you could split the changes that depend on app_unit into a separate commit to be merged later.

**Comment by mskrzypkows** [comment]
OK, I'll push another version.

**Comment by mskrzypkows** [comment]
Rebased, @mbrubeck what do you think? Could you do a review?

**Comment by mbrubeck** [comment]
Reviewed 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7696)

**Comment by mbrubeck** [comment]
@bors-servo r+

Thanks!

**Comment by mbrubeck** [comment]
@bors-servo retry

#7787

**Pull request merged**
