### PR TITLE
Implements enough WebGL spec to draw a triangle

### PR DESCRIPTION
**Pull request by dmarcos**
This is WIP. still have to clean up the code a little bit but I wanted to show the progress. I got really excited when I saw my first triangle on screen `./mach run tests/ref/webgl-context/triangle.html`

firsttriangle

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5820)

### CODE REVIEW

**Comment by dmarcos** [comment]
@pcwalton @jdm This is ready for review. You can see what the patch does by running ```./mach run tests/html/test_webgl_triangle.html```

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/mod.rs @ r1
- components/script/dom/webglbuffer.rs @ r1
- components/script/dom/webglobject.rs @ r1
- components/script/dom/webglprogram.rs @ r1
- components/script/dom/webglrenderingcontext.rs @ r5
- components/script/dom/webglshader.rs @ r1
- components/script/dom/webgluniformlocation.rs @ r1
- components/script/dom/webidls/WebGLBuffer.webidl @ r1
- components/script/dom/webidls/WebGLObject.webidl @ r1
- components/script/dom/webidls/WebGLProgram.webidl @ r1
- components/script/dom/webidls/WebGLRenderingContext.webidl @ r8

---

<sup>**[components/script/dom/webglbuffer.rs, line 31 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zS_1HqxnwlJ7z262)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglbuffer.rs#L31)):</sup>
nit: indentation

---

<sup>**[components/script/dom/webglbuffer.rs, line 35 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zTHrEMpzXx7WDErp)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglbuffer.rs#L35)):</sup>
nit: indentation

---

<sup>**[components/script/dom/webglprogram.rs, line 31 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zQcDCLF2NbP04TXD)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglprogram.rs#L31)):</sup>
nit: indentation

---

<sup>**[components/script/dom/webglprogram.rs, line 35 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zRIS6nvq4B6Wi2HC)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglprogram.rs#L35)):</sup>
nit: indentation

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 71 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zDkJO7iHIIBg7eAD)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L71)):</sup>
Could you add spec links to all of the methods in this file?

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 73 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6wqRUst6k6koPCVlQ)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L73)):</sup>
Panicking if we get a null value here seems like the wrong behaviour.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 77 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6x3zc05ekqhU3LYfj)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L77)):</sup>
No need for -> ()

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 78 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6wwj0knslm8X0EIpJ)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L78)):</sup>
Handle null.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 83 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6x1Bxe7Q1fgtU6HIV)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L83)):</sup>
No need for -> ()

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 97 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6xMZtfK9O-ihquu2Q)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L97)):</sup>
size_of::<f32>() instead of 4

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 111 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6xTCPW8VZitq_16iA)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L111)):</sup>
No need for -> ()

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 115 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6xXzLhC_63R64X7Zg)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L115)):</sup>
Let's use `if let` instead of is_none/unwrap. 

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 141 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6xlnUswPsZ5OAq0Fl)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L141)):</sup>
No need for -> ()

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 145 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6xro7Gq8CRJCgG68I)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L145)):</sup>
nit: remove the space before )

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 147 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6xpT96JpD9I65doAH)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L147)):</sup>
Handle null.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 157 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6xwv8vkdzwd9chXQw)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L157)):</sup>
Prefer `if let` or `match/return` to is_none/unwrap.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 167 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6y7cdx88FyfkUmoiN)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L167)):</sup>
if let or match instead of is_none/unwrap

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 181 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6yMGzoSutIFHvaHDm)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L181)):</sup>
Handle null.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 185 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6yNlF-3flfoSgQ2Qo)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L185)):</sup>
No need for -> ()

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 189 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6yP7RdauW6g0AHngo)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L189)):</sup>
if let or match/return.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 190 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6yVL9MGvZmf6-MlI2)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L190)):</sup>
Let's split this across multiple lines.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 195 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6yabtv2ghRPnV9iuB)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L195)):</sup>
No need for -> ()

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 196 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6yf7wpR8-xV0RH5U2)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L196)):</sup>
match/return

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 208 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6yxmQKI7ybAYQYrnO)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L208)):</sup>
No need for -> ()

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 209 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6z-N5H2Feo1GzCl2I)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L209)):</sup>
Handle null.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 214 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6z1qtto5164QVsfTX)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L214)):</sup>
No need for -> ()

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 225 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6z8EIAgG8yTHu9bvA)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L225)):</sup>
No need for -> ()

---

<sup>**[components/script/dom/webglshader.rs, line 31 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zNAWuzssHHSu7RJ-)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglshader.rs#L31)):</sup>
nit: indentation

---

<sup>**[components/script/dom/webglshader.rs, line 35 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zOAqvoiIVw8wmRmj)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglshader.rs#L35)):</sup>
nit: indentation

---

<sup>**[components/script/dom/webgluniformlocation.rs, line 31 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zZCBSQ3hjUC3dqSt)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webgluniformlocation.rs#L31)):</sup>
nit: indentation

---

<sup>**[components/script/dom/webgluniformlocation.rs, line 35 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6z_4b-_tzJK6sDEW3)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webgluniformlocation.rs#L35)):</sup>
nit: indentation

---

<sup>**[components/script/dom/webidls/WebGLBuffer.webidl, line 1 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zeOs-kKmTrHKqpIP)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLBuffer.webidl#L1)):</sup>
I don't think this is true.

---

<sup>**[components/script/dom/webidls/WebGLBuffer.webidl, line 4 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-42IuUQ7QFmr0Llj)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLBuffer.webidl#L4)):</sup>
Link to the spec?

---

<sup>**[components/script/dom/webidls/WebGLObject.webidl, line 1 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7--nnzzSd51WPsYHG)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLObject.webidl#L1)):</sup>
Add a header, link to the spec?

---

<sup>**[components/script/dom/webidls/WebGLProgram.webidl, line 1 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-1VmI8SA2Arllm5H)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLProgram.webidl#L1)):</sup>
Untrue.

---

<sup>**[components/script/dom/webidls/WebGLProgram.webidl, line 4 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-5VmiJXLpTFVazvF)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLProgram.webidl#L4)):</sup>
Link to the spec?

---

<sup>**[components/script/dom/webidls/WebGLShader.webidl, line 1 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-PGNrFPdI732v51h)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLShader.webidl#L1)):</sup>
Nope.

---

<sup>**[components/script/dom/webidls/WebGLShader.webidl, line 4 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-Pv_kbZ5Dr7lnfkW)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLShader.webidl#L4)):</sup>
Link to the spec?

---

<sup>**[components/script/dom/webidls/WebGLUniformLocation.webidl, line 1 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-ReGJb3oapWU7qo1)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLUniformLocation.webidl#L1)):</sup>
Add a header, link to the spec.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5820)

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/webidls/WebGLShader.webidl @ r1
- components/script/dom/webidls/WebGLUniformLocation.webidl @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5820)

**Comment by jdm** [comment]
@glennw Would you like to review the non-DOM parts of the WebGL canvas changes here?

**Comment by glennw** [comment]
@jdm Sure

**Comment by glennw** [comment]
Reviewed files:
- components/canvas/canvas_msg.rs @ r5
- components/canvas/webgl_paint_task.rs @ r6
- tests/html/test_webgl_triangle.html @ r7

---

<sup>**[components/canvas/webgl_paint_task.rs, line 98 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo72tyJhFyg0ZIR5et1)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/canvas/webgl_paint_task.rs#L98)):</sup>
vertext -> vertex

---

<sup>**[components/canvas/webgl_paint_task.rs, line 227 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo73L1Hf8MD8721LUCm)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/canvas/webgl_paint_task.rs#L227)):</sup>
vertext -> vertex

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5820)

**Comment by dmarcos** [comment]
@jdm I think I addressed all the comments. On critic it was easy to see the % of addressed comments. Is there anything similar on reviewable? Do I have to click on acknowledge for every comment?

**Comment by jdm** [comment]
I believe the unacknowledged comments are there for me to ensure that they have been acknowledged; I agree that this is one area that Critic currently has the advantage.

**Comment by dmarcos** [comment]
@jdm Should I go ahead and squash?

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/canvas/webgl_paint_task.rs @ r9
- components/script/dom/webglbuffer.rs @ r9
- components/script/dom/webglprogram.rs @ r9
- components/script/dom/webglrenderingcontext.rs @ r9
- components/script/dom/webglshader.rs @ r9
- components/script/dom/webgluniformlocation.rs @ r9
- components/script/dom/webidls/WebGLBuffer.webidl @ r9, r10
- components/script/dom/webidls/WebGLObject.webidl @ r9, r10
- components/script/dom/webidls/WebGLProgram.webidl @ r9, r10
- components/script/dom/webidls/WebGLRenderingContext.webidl @ r9
- components/script/dom/webidls/WebGLShader.webidl @ r9, r10
- components/script/dom/webidls/WebGLUniformLocation.webidl @ r9, r10

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 71 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6zDkJO7iHIIBg7eAD)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L71)):</sup>
I know the spec is less useful than the w3c/whatwg ones, but we can get a bit more specific by using section numbers like https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.9

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 73 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo6wqRUst6k6koPCVlQ)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webglrenderingcontext.rs#L73)):</sup>
Let's use
let program_id = match program {
    Some(program) => program.get_id(),
    None => return,
};
here and elsewhere.

---

<sup>**[components/script/dom/webidls/WebGLBuffer.webidl, line 4 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-42IuUQ7QFmr0Llj)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLBuffer.webidl#L4)):</sup>
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.4

---

<sup>**[components/script/dom/webidls/WebGLObject.webidl, line 1 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7--nnzzSd51WPsYHG)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLObject.webidl#L1)):</sup>
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.3

---

<sup>**[components/script/dom/webidls/WebGLProgram.webidl, line 4 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-5VmiJXLpTFVazvF)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLProgram.webidl#L4)):</sup>
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.6

---

<sup>**[components/script/dom/webidls/WebGLShader.webidl, line 4 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-Pv_kbZ5Dr7lnfkW)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLShader.webidl#L4)):</sup>
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.6

---

<sup>**[components/script/dom/webidls/WebGLUniformLocation.webidl, line 1 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-ReGJb3oapWU7qo1)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLUniformLocation.webidl#L1)):</sup>
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.6

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5820)

**Comment by jdm** [comment]
<sup>**[components/script/dom/webidls/WebGLUniformLocation.webidl, line 6 \[r8\]](https://reviewable.io:443/reviews/servo/servo/5820#-Jo7-ReGJb3oapWU7qo1)** ([raw file](https://github.com/servo/servo/blob/9ade7404bd915c8bc1467659e0426853941af5b9/components/script/dom/webidls/WebGLUniformLocation.webidl#L6)):</sup>
Whoops, 5.10.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5820)

**Comment by dmarcos** [comment]
@jdm Done!

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed files:
- components/script/dom/webglrenderingcontext.rs @ r11
- components/script/dom/webidls/WebGLBuffer.webidl @ r11
- components/script/dom/webidls/WebGLObject.webidl @ r11
- components/script/dom/webidls/WebGLProgram.webidl @ r11
- components/script/dom/webidls/WebGLShader.webidl @ r11
- components/script/dom/webidls/WebGLUniformLocation.webidl @ r11

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5820)

**Comment by jdm** [comment]
Sorry, I forgot about squashing. Go ahead!

**Comment by dmarcos** [comment]
@jdm Squashed and ready to go!

**Comment by dmarcos** [comment]
@jdm This is strange. I had moved the ref test to ```tests/html/...```. Buildbot is testing an old commit:
https://github.com/servo/servo/commit/057ba260f26cb1f538c7ca3d73faf5c17d0df0ec instead of the latest one I pushed https://github.com/dmarcos/servo/commit/9ac9860479d5edebd0294d22989e2737d4ee2b17

**Comment by dmarcos** [comment]
@jdm Oh I see. The test that is failing is unrelated to these changes:
http://build.servo.org/builders/mac1/builds/1845/steps/shell_2/logs/stdio
```/_mozilla/mozilla/interfaces.html``` What should I do?

**Comment by Ms2ger** [comment]
```
Interfaces exposed on the window
--------------------------------
Expected PASS, got FAIL
assert_true: If this is failing: DANGER, are you sure you want to expose the new interface WebGLObject to all webpages as a property on the window? Do not make a change to this file without review from jdm or Ms2ger for that specific change!
```

**Comment by jdm** [comment]
You'll need to modify that test to include the new WebIDL interfaces this PR adds.

**Comment by dmarcos** [comment]
@jdm Done! https://github.com/servo/servo/pull/5820/files#diff-60cb8e34e787f23f73e256c83d621c8eL179

I got the test passing locally: https://pastebin.mozilla.org/8832211

**Pull request merged**
