### PR TITLE
Bump Rust to 2016-04-06

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10173)

### CODE REVIEW

**Comment by nox** [comment]
No dependency required a bump?

**Comment by larsbergstrom** [comment]
Android:
```
   Compiling glutin_app v0.0.1 (file:///home/servo/buildbot/slave/android/build/ports/glutin)
/home/servo/buildbot/slave/android/build/ports/glutin/window.rs:30:5: 30:25 warning: unused import, #[warn(unused_imports)] on by default
/home/servo/buildbot/slave/android/build/ports/glutin/window.rs:30 use std::os::raw::c_void;
                                                                       ^~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/android/build/ports/glutin/window.rs:39:24: 39:33 warning: unused import, #[warn(unused_imports)] on by default
/home/servo/buildbot/slave/android/build/ports/glutin/window.rs:39 use util::opts::{self, RenderApi};
                                                                                          ^~~~~~~~~
   Compiling layout v0.0.1 (file:///home/servo/buildbot/slave/android/build/components/layout)
main.rs:35:5: 35:14 warning: unused import, #[warn(unused_imports)] on by default
main.rs:35 use gleam::gl;
               ^~~~~~~~~
main.rs:36:28: 36:37 warning: unused import, #[warn(unused_imports)] on by default
main.rs:36 use offscreen_gl_context::{GLContext, NativeGLContext};
                                      ^~~~~~~~~
main.rs:36:39: 36:54 warning: unused import, #[warn(unused_imports)] on by default
main.rs:36 use offscreen_gl_context::{GLContext, NativeGLContext};
                                                 ^~~~~~~~~~~~~~~
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Aborted (core dumped)
Could not compile `servo`.

To learn more, run the command again with --verbose.
[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
Build completed in 585.33s
program finished with exit code 101
elapsedTime=592.030544

```

ARM32:
```
   Compiling euclid v0.6.4
/home/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/euclid-0.6.4/src/lib.rs:29:1: 29:19 error: can't find crate for `test` [E0463]
/home/servo/.cargo/registry/src/github.com-88ac128001ac3a9a/euclid-0.6.4/src/lib.rs:29 extern crate test;
                                                                                       ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `euclid`.

To learn more, run the command again with --verbose.
[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
looking for rustc at /home/servo/.servo/rust/2016-03-24/rustc-nightly-x86_64-unknown-linux-gnu/rustc/bin/rustc
Downloading Rust compiler...
Extracting Rust compiler...
Rust compiler ready.
Downloading Host rust library for target arm-unknown-linux-gnueabihf...
Extracting Rust stdlib for target arm-unknown-linux-gnueabihf...
Rust arm-unknown-linux-gnueabihf libs ready.
Downloading Host rust library for target x86_64-unknown-linux-gnu...
Extracting Rust stdlib for target x86_64-unknown-linux-gnu...
Rust x86_64-unknown-linux-gnu libs ready.
Build completed in 220.05s
program finished with exit code 101
elapsedTime=234.463321
```

**Comment by larsbergstrom** [comment]
CC @brson @alexcrichton - cross builds to Android core dump with an LLVM assert in this rustup from March 18th to March 24th.

**Comment by alexcrichton** [comment]
This may be somewhat related to https://github.com/rust-lang/rust/issues/32360, although I'm not sure.

Also cc @eddyb, looks like lots of the MIR trans changes landed in that windows?

**Comment by eddyb** [comment]
@larsbergstrom Do you have a backtrace? My wild guess is that our casting of imports from multiple sources is biting us here, e.g. something is trying to modify attributes on a cast function pointer instead of the function declaration itself.

**Comment by larsbergstrom** [comment]
Eddyb is hoping this might be https://github.com/rust-lang/rust/pull/32503

**Comment by nox** [comment]
I've bumped the nightly to a more recent one, but now it is blocked on https://github.com/Manishearth/rust-tenacious/pull/16.

**Comment by nox** [comment]
@bors-servo r-

@Manishearth You didn't publish tenacious 0.1.2 yet.

**Comment by dotdash** [comment]
That failure is rust-lang/rust#32518 -- I should have a PR for that up soonish.

**Comment by nox** [comment]
New nightly is out! Updated patch for 2016-03-30.

@bors-servo r=Manishearth

**Comment by dotdash** [comment]
This is https://github.com/rust-lang/rust/issues/32523

**Comment by nox** [comment]
I doubt it will work, but who knows…

@bors-servo r+

**Comment by nox** [comment]
LGTM.

@bors-servo r+

**Comment by jdm** [comment]
```
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```

**Comment by eddyb** [comment]
@jdm [My comment from 9 days ago](https://github.com/servo/servo/pull/10173#issuecomment-201057587) was for the Android LLVM assertion, which is the same still (rust-lang/rust#32503 was for the ARM32 issue or some other thing).

Without a backtrace from a debugger (setting `RUST_BACKTRACE=1` doesn't help, sadly) and maybe even some debug logs from a compiler built with `--enable-assertions` (are the nightlies there yet, @alexcrichton?), it's hard to say anything for sure.

**Comment by alexcrichton** [comment]
Nightlies have LLVM assertions enabled bug not rustc assertions I believe.

**Comment by nox** [comment]
But why did everything started to fail on ARM, 9 days ago?

**Comment by eddyb** [comment]
Android LLVM assertion is likely rust-lang/rust#32740, with rust-lang/rust#32742 as a fix.
Any way the fix could be checked before it gets into a nightly, or even merged?
If there's a stranger edge case, I don't want to delay Servo further.

**Comment by larsbergstrom** [comment]
@bors-servo retry
- Disabled appveyor

**Comment by larsbergstrom** [comment]
@bors-servo retry
 - network failure?

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #8931

**Pull request merged**
