### PR TITLE
Make the HoloLens UI look better

### PR DESCRIPTION
**Pull request by paulrouget**
Throbber, icons, tooltips, alignment, etc...

Based on top of #24125

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24126)

### CODE REVIEW

**Comment by paulrouget** [comment]
- Proper icons (from Firefox Desktop)
- Reload/Stop collapse into one button
- Throbber when page is loading

**Comment by jdm** [comment]
Does the browser still recognize voice commands like "back" and "refresh" with these changes?

**Comment by paulrouget** [comment]
> Does the browser still recognize voice commands like "back" and "refresh" with these changes?

Nope. I'll see how to fix that.

**Comment by paulrouget** [comment]
> Does the browser still recognize voice commands like "back" and "refresh" with these changes?

Now it does.

**Comment by paulrouget** [comment]
Erf, pushed too many changes.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Comment by jdm** [comment]
@bors-servo retry
* #23290 #21696

**Comment by CYBAI** [comment]
@bors-servo retry

- UWP build OOM

**Pull request merged**
