### PR TITLE
Ignore `<meta name=viewport>` if `@viewport` is ignored

### LINKED ISSUE #8373: github.com doesn't fill up the browser window
OS: Arch Linux 
Kernel: GNU/Linux 4.2.5-1 x86_64
Window Manager: Awesome

servo

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #8373

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8538)

### CODE REVIEW

**Comment by jdm** [comment]
We should add an entry to prefs.json, too.

**Comment by notriddle** [comment]
[There already is an entry in prefs.json.](
https://github.com/servo/servo/blob/master/resources/prefs.json#L11)

**Comment by mbrubeck** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8538)

**Comment by mbrubeck** [comment]
```
FAIL [expected PASS] /css21_dev/html4/background-root-101.htm
```

**Comment by jdm** [comment]
@bors-servo: retry
* #8487

**Comment by frivoal** [comment]
Hello. Spec co-editor for @viewport here. Just curious (and confused). What's this about? When do you ignore @viewport?

**Comment by eefriedman** [comment]
There's a preference which controls whether @viewport rules are processed.  The intent is that mobile browsers will enable processing @viewport rules, and desktop browsers will disable it.  Web compatibility at its finest. :)

**Comment by frivoal** [comment]
Hmm, that's actually problematic. metia viewport needs to work this way, but @viewport is explicitely designed so that it would apply to both desktop and mobile and things in between.

There's two points that matter here:
1) @viewport can be useful on desktops
2) not including @viewport on desktops is harmful

1) When a site isn't responsive, or only responsive down to a certain size, @viewport can be used to indicate the smallest acceptable width. ```@viewport { min-width: 400px; }```. Desktop browsers, just like mobile ones, can (and should) respond to that.

2) If we don't include @viewport in desktop browsers early on, there's a risk a non trivial amount of website will put something like this in their stylesheet: ```@viewport { width:320px;}```. This will make the site responsive on mobile (even if the number of pixels is slightly wrong for some devices, it's not that far off), but would be terrible on desktops. And if enough sites do that, it becomes impossible to start supporting @viewport on desktops later, due to backward compat.

What authors should be doing to make their sites responsive is ```@viewport {width:auto}``` which is a no-op on desktop since auto is the intial value and it is not overridden by stylesheets, or ```@viewport {min-width: 320px;}``` which overrides the 980 px (or whatever) default viewport of mobile browsers, and causes no harm on desktops.

I strongly encourage you to follow microsoft here, and to activate @viewport on all platform.

On my side, I'll make sure there's a big warning in the spec talking about this. I though there was one already, but I can't find it now, so apparently misremembered.

In the meanwhile, here's a quick and dirty test case that should pass in desktop and mobile browsers alike. (I'll convert that to a clean TC whenever I get some time, unless you want to do so first).

http://output.jsbin.com/gusahiguyu

This passes in Edge.

**Comment by frivoal** [comment]
Specification updated with the relevant warning:
https://drafts.csswg.org/css-device-adapt/#atviewport-rule

**Comment by Ms2ger** [comment]
FWIW, I think this was one of the features that was behind the catch-all "experimental" flag; it's not clear to me whether the implementation is good enough to enable be default, independent of mobile/desktop. Having a serious test suite for us to run would help, though.

**Comment by frivoal** [comment]
Having a flag for it is good at this stage, but that doesn't change the fact that it should work both on desktop and mobile or neither, not being turned on independently.

As for the test suite, I hear you. I just don't have the resources to focus on it now. If you write some, I will make sure they get reviewed in a timely manner.

**Pull request merged**
