### PR TITLE
Use absolute paths in the event handlers macros

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18314)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r-

 * Let's wait a second. r=me when all the autoland bustage is fixed

**Comment by jdm** [comment]
@bors-servo: retry
* #18228

**Comment by jdm** [comment]
@bors-servo: retry
* #18228

**Comment by jdm** [comment]
@bors-servo: retry
* #18228

**Comment by jdm** [comment]
@bors-servo: retry
* #18228

**Comment by jdm** [comment]
@bors-servo: retry
* #18328

**Comment by emilio** [comment]
Homu seems stuck.

**Comment by emilio** [comment]
@bors-servo r-

 * Please re-push and r+, because homu seems pretty drunk

**Pull request merged**
