### PR TITLE
implement console.group(), console.groupEnd()

### LINKED ISSUE #9274: Implement console.group() / console.groupEnd() / console.groupCollapsed()
Calling `console.group()` and an indentation level to further logs.

For example:

``` js
console.log(1);
console.group()
console.log(2);
console.log(3);
console.group();
console.log(4);
console.log(5);
console.groupEnd();
console.log(6);
console.groupEnd();
console.log(7);
```

will output:

```
1
..2
..3
....4
....5
..6
7
```

See:
- https://developer.mozilla.org/en-US/docs/Web/API/Console/group
- https://developer.mozilla.org/en-US/docs/Web/API/Console/groupEnd
- https://developer.mozilla.org/en-US/docs/Web/API/Console/groupCollapsed

### PR DESCRIPTION
**Pull request by ajnirp**
Fixes #9274

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9276)

### CODE REVIEW

**Comment by wenderen** [comment]
rebased

**Comment by jdm** [comment]
I doubt we want to apply the indentation to the message before sending it to the devtools client, but I haven't looked carefully at this code yet. Have you tried out the changes with the Firefox webconsole connected?

**Comment by paulrouget** [comment]
Also, please add `groupCollapsed`.

**Comment by jdm** [comment]
Note, instructions for interacting with the Firefox devtools exist [in the wiki](https://github.com/servo/servo/wiki/Devtools).

**Comment by asajeffrey** [comment]
Some comments on reviewable...

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/devtools/lib.rs, line 339 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9276#-K9na8cIz8jCVf29rYcl:-K9na8cJ0GzVoeLjqrNA:-806651404) ([raw file](https://github.com/servo/servo/blob/d0dad6ae6dcc8306f983515feffca1b1e06669ca/components/devtools/lib.rs#L339)):*
This is adding 2 spaces per indent level, and the indent level is incremented/decremented by 2 on each Group/GroupEnd, so there's 4 spaces per event. Is this intended?

---

*[components/devtools/lib.rs, line 352 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9276#-K9naPRtWHV7595lwenk:-K9naPRtWHV7595lwenl:-825215852) ([raw file](https://github.com/servo/servo/blob/d0dad6ae6dcc8306f983515feffca1b1e06669ca/components/devtools/lib.rs#L352)):*
There should be a way to do this without copying the indent string.

---

*[components/devtools_traits/lib.rs, line 220 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9276#-K9nbUKsWq_W7lqMgyJy:-K9nbUKsWq_W7lqMgyJz:995316803) ([raw file](https://github.com/servo/servo/blob/d0dad6ae6dcc8306f983515feffca1b1e06669ca/components/devtools_traits/lib.rs#L220)):*
It's a bit odd that Group and GroupEnd are considered to be LogLevels. Is this what devtools does?

---

*[components/script/dom/console.rs, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9276#-K9nb6gmXWDWQ0u5OCo0:-K9nb6gmXWDWQ0u5OCo1:-1461076805) ([raw file](https://github.com/servo/servo/blob/d0dad6ae6dcc8306f983515feffca1b1e06669ca/components/script/dom/console.rs#L47)):*
Should all messages be printed to stdout, irrespective of log level?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9276#-:-K9ndIIFfxE0hH06BaMB:-1820283168)*

**Comment by jdm** [comment]
@wenderen Are you planning to continue working on this?

**Comment by asajeffrey** [comment]
@wenderen is this PR still open?

**Comment by wenderen** [comment]
@jdm @asajeffrey It is. I'm very sorry but I cannot work on this because of a lack of free time. Please assign this to someone else if need be.

**Comment by asajeffrey** [comment]
@wenderen OK, thanks for letting us know!

**Pull request closed without merging**
