### PR TITLE
Use skia and deps from crates.io.

### PR DESCRIPTION
**Pull request by SimonSapin**
This makes the initial download for skia go from a 300 MB git repository to a 5 MB tarball. This should help with issues like #6132 and #7687.

Fix https://github.com/servo/skia/issues/70

This builds, but the at the moment causes a number of tidy errors for duplicated crates.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8757)

### CODE REVIEW

**Comment by metajack** [comment]
This adds a lot of dupe dependencies. xml-rs only on gonk for some reason. the others seem to be on all the Cargo.locks.

---

Reviewed 24 of 24 files at r1.
Review status: 21 of 24 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/servo/Cargo.lock, line 316 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4PMGPBgJi-ofOlglpD:-K4PMGPBgJi-ofOlglpE:-2007409609) ([raw file](https://github.com/servo/servo/blob/a14e7f9cb35e2638c784b8ba091aa6317236b1a7/components/servo/Cargo.lock#L316)):*
now we have two core-foundations. 0.1.0 is included just before this one.

---

*[components/servo/Cargo.lock, line 343 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4PMPLniUV9eh_IDmoZ:-K4PMPLoqyOC1EQNEUrf:1450366360) ([raw file](https://github.com/servo/servo/blob/a14e7f9cb35e2638c784b8ba091aa6317236b1a7/components/servo/Cargo.lock#L343)):*
dupe core-graphics too

---

*[components/servo/Cargo.lock, line 723 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4PMdkWiLbcCXr_XyjI:-K4PMdkWiLbcCXr_XyjJ:916289045) ([raw file](https://github.com/servo/servo/blob/a14e7f9cb35e2638c784b8ba091aa6317236b1a7/components/servo/Cargo.lock#L723)):*
two gl_generators. although this one may be intentional?

---

*[components/servo/Cargo.lock, line 856 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4PMitA1uzXA0J_3sK6:-K4PMitA1uzXA0J_3sK7:1655609453) ([raw file](https://github.com/servo/servo/blob/a14e7f9cb35e2638c784b8ba091aa6317236b1a7/components/servo/Cargo.lock#L856)):*
two heapsizes

---

*[components/servo/Cargo.lock, line 991 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4PMoD-48__3CRDEp_a:-K4PMoD-48__3CRDEp_b:-996725322) ([raw file](https://github.com/servo/servo/blob/a14e7f9cb35e2638c784b8ba091aa6317236b1a7/components/servo/Cargo.lock#L991)):*
dupe khronos apis

---

*[ports/gonk/Cargo.lock, line 2069 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4PNkCeM8LW_QZcKPxG:-K4PNkCeM8LW_QZcKPxH:1564279116) ([raw file](https://github.com/servo/servo/blob/a14e7f9cb35e2638c784b8ba091aa6317236b1a7/ports/gonk/Cargo.lock#L2069)):*
dupe xml-rsx

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8757#-:-K4PO-52RZwKPGt4P3c6:-192419428)*

**Comment by SimonSapin** [comment]
Should be good after updating to https://github.com/ecoal95/rust-offscreen-rendering-context/pull/44

**Comment by SimonSapin** [comment]
@metajack All of the duplicate dependencies were detected by tidy, which is now happy :)

**Comment by mbrubeck** [comment]
ports/cef/Cargo.lock still has some duplicates for some reason.

---

Reviewed 2 of 9 files at r2.
Review status: 19 of 26 files reviewed at latest revision, 9 unresolved discussions.

---

*[ports/cef/Cargo.lock, line 244 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4YqR-oqOnN1XgEAh_X:-K4YqR-pbY56i2eSibEI:-395913322) ([raw file](https://github.com/servo/servo/blob/9237ae3035205af569247c6d1188b0e599c7fddf/ports/cef/Cargo.lock#L244)):*
Duplicate cocoa. Not sure how this one slipped past tidy.

---

*[ports/cef/Cargo.lock, line 317 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4YqWbIXaMLTnzKfmDs:-K4YqWbJ_NCc0geP3fU8:334654471) ([raw file](https://github.com/servo/servo/blob/9237ae3035205af569247c6d1188b0e599c7fddf/ports/cef/Cargo.lock#L317)):*
Duplicate core-foundation.

---

*[ports/cef/Cargo.lock, line 343 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4YqXsWFw4o6MJuSMx9:-K4YqXsXAArE5Gi0pu70:-171500497) ([raw file](https://github.com/servo/servo/blob/9237ae3035205af569247c6d1188b0e599c7fddf/ports/cef/Cargo.lock#L343)):*
Duplicate core-graphics.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8757#-:-K4Yqdvid4Hzc5nZ-75H:-458952843)*

**Comment by mbrubeck** [comment]
Reviewed 6 of 9 files at r2.
Review status: 25 of 26 files reviewed at latest revision, 10 unresolved discussions.

---

*[ports/cef/Cargo.toml, line 72 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8757#-K4YrD9hLYlL0pELgdfy:-K4YrD9hLYlL0pELgdfz:600836858) ([raw file](https://github.com/servo/servo/blob/9237ae3035205af569247c6d1188b0e599c7fddf/ports/cef/Cargo.toml#L72)):*
This toml file has a bunch of outdated or `"*"` dependencies should be updated.  Or maybe they can just be removed, since it should depend on these transitively rather than directly?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8757)*

**Comment by SimonSapin** [comment]
Ah, I was looking at `./mach test-tidy`, but it seems to ignore everything under ports/cef/

**Comment by mbrubeck** [comment]
Reviewed 1 of 9 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8757)*

**Comment by metajack** [comment]
> Ah, I was looking at ./mach test-tidy, but it seems to ignore everything under ports/cef/

Please file a bug for this! It should only be ignoring ports/cef for certain things, but definitely not for cargo.lock checks.

**Comment by SimonSapin** [comment]
My second commit fixes this: https://github.com/servo/servo/commit/b8a3a646919b871620aeedffe48b97ac4fe4b0df

**Comment by metajack** [comment]
Even better!

**Comment by frewsxcv** [comment]
> Please file a bug for this! It should only be ignoring ports/cef for certain things, but definitely not for cargo.lock checks.

Relevant discussion: https://github.com/servo/servo/issues/7202

**Comment by benbucksch** [comment]
Thank you

**Pull request merged**
