### PR TITLE
Update to gleam 0.5

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20732)

### CODE REVIEW

**Comment by nox** [comment]
What the hell that's literally the test I marked as failing.

**Comment by nox** [comment]
I'm dumb, confused myself with the WR bump PR.

**Comment by nox** [comment]
Cc @glennw @emilio @mrobinson @jdm 

If anyone of you can r+ this, please do it.

Note that this supersedes #20714.

**Review by jdm — APPROVED** [review]
Lots of good improvements here!

**Pull request merged**
