### PR TITLE
Dockerfile WIP for testing

### PR DESCRIPTION
**Pull request by edunham**
cc @aneeshusa 

This represents much less difficulty than I believe the correctly completed solution would entail, so either I'm totally wrong about how hard it is to naively Dockerize the build environment or this is totally wrong. Maybe both.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17552)

### CODE REVIEW

**Comment by aneeshusa** [comment]
Two comments at first glance
- When I was working on this before, I just ran a salt highstate in the Dockerfile instead of e.g. making a servo user, installing xvfb, etc. by hand to avoid duplicating the states.
- IIRC `mach` will download rust itself, so I don't think we need to install rust in the Dockerfile.

**Comment by edunham** [comment]
@aneeshusa I'm reluctant to pull the entire salt repo and attempt to apply the relevant states from within the Dockerfile because if we ever use pillar values in the states that the Docker container needs, it'll either need human interaction to add it to the salt master or will just plain break. If working from Salt is essential, we can later switch to publishing a public base image from Servo builds that's created from Salt and then just pull that image in -- but that system is more complex than we need to start out with to get TaskCluster set up.

I'll check what happens running mach without installing Rust first.

**Comment by aneeshusa** [comment]
You can pass a `--local` flag to `salt-call` to work completely masterlessly (and point `--file-roots` to a local copy of the `saltfs` tree). Additionally, we can pass custom pillars via the `--pillar-roots` flag. Both of these are used in the `.travis/dispatch.sh` file for our tests on Travis - the end result will probably look like the `salt_call` function in that file or the `mach bootstrap` implementation in servo/servo.

Working from Salt isn't essential, but I think it would be less work in the long term. I'm happy to get something working for Taskcluster :) Here's some old version of the WIP Dockerfile I used to have in servo/saltfs#561:

```
FROM ubuntu@sha256:edf05697d8ea17028a69726b4b450ad48da8b29884cd640fec950c904bfb50ce

ARG SALT_ROOT=/tmp/salt-bootstrap

COPY ./ "${SALT_ROOT}"

RUN : \
 && sudo apt-get update \
 && sudo apt-get -y install --no-install-recommends \
         ca-certificates \
         curl \
 && "${SALT_ROOT}/.travis/install_salt.sh" linux \
 && sudo salt-call \
        --local \
        --id="${SALT_NODE_ID}" \
        --config-dir="${SALT_ROOT}/.travis" \
        --file-root="${SALT_ROOT}" \
        --retcode-passthrough \
        --force-color \
        state.apply docker,servo-build-dependencies \
        pillar='{"fully_managed": False}' \
 && rm -rf "${SALT_ROOT}" \
 && rm -rf "/var/cache/salt" \
 && sudo apt-get autoremove --purge -y \
 && sudo apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && :

USER servo
WORKDIR /home/servo
CMD ["bash"]
```

**Comment by aneeshusa** [comment]
I resurrected my old saltfs PR at servo/saltfs#706.

**Comment by aneeshusa** [comment]
Closing in favor of the saltfs PR.

**Pull request closed without merging**
