### PR TITLE
Re: Add new Servo Logo (continuing #25749)

### PR DESCRIPTION
**Pull request by malqinneh**
- Using new filename structure for logo assets (lower case, underscore, resolution)
- Revised filenames for logo assets
- Removed duplicate assets

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because because they replace old logo assets with new ones

### CODE REVIEW

**Comment by atouchet** [comment]
Is there any difference between servo64.png/servo-64.png and servo.png/servo-1024.png? If those are identical images maybe it would be better to update the image references in the code rather than include duplicate copies.

**Comment by malqinneh** [comment]
> Is there any difference between servo64.png/servo-64.png and servo.png/servo-1024.png? If those are identical images maybe it would be better to update the image references in the code rather than include duplicate copies.
> 
> Otherwise looks good to me. I didn't take a look at the .icns file as I'm not familiar with the standards for macOS icons.

.icns should support up to 1024x1024. I converted 1024.png asset to .icns format and updated (for maximum resolution).

**Comment by paulrouget** [comment]
AFAICT, resources/servo_100.png, resources/servo_1000.png and resources/servo_500.png are never used.

Can you also rebased your commits on top of a more recent master?

**Comment by malqinneh** [comment]
> AFAICT, resources/servo_100.png, resources/servo_1000.png and resources/servo_500.png are never used.

All common sizes of the logo are currently uploaded (in case they're needed at some point), including the 100, 500, and 1000 variants. Do you wish that I remove these?

> Can you also rebased your commits on top of a more recent master?

Yes

**Comment by paulrouget** [comment]
>  Do you wish that I remove these?

Yes. We can always reuse the 1024px version and rescale it if we need later.

> I added you as a contributor to the repo (along with Alex)

You don't need to do that.

>  I also realized I should have created a separate branch for my logo updates instead of merging them directly to master

It's on your master. Not servo's.

> Can you let me know if you can 'rebase' on my behalf? I think I can do it but for anything beyond creating pull-requests, would want to be careful :)

You can mess up as much as you want :) No need to worry. The servo repository and your repository are separated. You cannot affect servo's repo.

This PR is using your master branch. So rebase your changes on top of servo's master and push them to your master branch.

What software do you use to do your changes? git command line?

**Comment by malqinneh** [comment]
> This PR is using your master branch. So rebase your changes on top of servo's master and push them to your master branch.
> 
> What software do you use to do your changes? git command line?

No, I use Git's Desktop app. Can you please confirm that the following prompt is correct and that I can proceed safely?

Screen Shot 2020-02-27 at 10 30 36 AM

**Comment by malqinneh** [comment]
> This PR is using your master branch. So rebase your changes on top of servo's master and push them to your master branch.
> 
> What software do you use to do your changes? git command line?

No, I use Git's Desktop app. Can you please confirm that the following prompt is correct and that I can proceed safely?

Screen Shot 2020-02-27 at 10 30 36 AM

**Comment by jdm** [comment]
That looks correct!

**Comment by malqinneh** [comment]
> That looks correct!

Thank you! Done ✅

**Comment by paulrouget** [comment]
Don't forget to push your rebased branch. You will need to force push.

**Comment by malqinneh** [comment]
> Don't forget to push your rebased branch. You will need to force push.

It asked me to do a merge and delete an asset but I think it 'Pushed'. Did it go through OK?

**Comment by CYBAI** [comment]
I saw there's a merge commit (fd4306c) which makes your PR include some irrelevant commits from other merged PRs. (You can check the commits in [commits tab](https://github.com/servo/servo/pull/25846/commits))

In this situation, I will recommend you to create another branch from latest master and then cherry-pick valid commits and then force pushed it.

For example,

```sh
$ git switch -c new-logo
$ git cherry-pick d09bc64
$ git cherry-pick b04df87
$ # pick other valid commits for this PR
$ # if commits are in a range, you can also pick
```

Ref: https://stackoverflow.com/a/9339460

Hope it will help! 👀

**Comment by malqinneh** [comment]
> I saw there's a merge commit ([fd4306c](https://github.com/servo/servo/commit/fd4306cf34d15229995f4d541c6e4b2f38d57e6b)) which makes your PR include some irrelevant commits from other merged PRs. (You can check the commits in [commits tab](https://github.com/servo/servo/pull/25846/commits))
> 
> In this situation, I will recommend you to create another branch from latest master and then cherry-pick valid commits and then force pushed it.
> 
> For example,
> 
> ```shell
> $ git switch -c new-logo
> $ git cherry-pick d09bc64
> $ git cherry-pick b04df87
> $ # pick other valid commits for this PR
> $ # if commits are in a range, you can also pick
> ```
> 
> Ref: https://stackoverflow.com/a/9339460
> 
> Hope it will help! 👀

Apologies for the late reply here - will look into this. Thank you!

**Pull request closed without merging**
