### PR TITLE
Implement Named constructors and the Image constructor for HTMLImageElement

### PR DESCRIPTION
**Pull request by klusark**
I'm not sure if I like how I mostly just duplicated the code in CodegenRust.py, so that might need to be refactored.

Instead of just calling it Image, we might want to call it ConstructorImage, to make it clear that it's a constructor. Anyone have an opinion on that?

There seems to be a bug in the HTMLImageElement getter/setter as the value is 0 regardless of what I do. This seems to be unrelated to my commits, so I'll investigate that separately.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6110)

### CODE REVIEW

**Comment by Manishearth** [comment]
The `width` IDL attribute is a reflector, and there are additional constraints on the `width` content attr, which is what's happening here. The internal implementation works with the bounding box.

https://html.spec.whatwg.org/multipage/embedded-content.html#attr-dim-width

There still may be a mistake here though, we should look closely.

**Comment by Manishearth** [comment]
Scratch that, our implementation is correct.

https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-width

That's what I get for clicking the wrong link and not noticing that `img` wasn't mentioned

**Comment by KiChjang** [comment]
Remember to close #2540 along the way

**Comment by Ms2ger** [comment]
Reviewed on critic

**Comment by klusark** [comment]
I'm not sure about the test I added. Is it comprehensive enough? I'm not really sure what else I could add to it.

**Comment by frewsxcv** [comment]
It looks like one of the lines is beyond 120 characters

https://travis-ci.org/servo/servo/builds/63910947

**Comment by Ms2ger** [comment]
Sorry I've been dragging my feet. I've added more comments on critic.

**Comment by Ms2ger** [comment]
Please rebase on master.

**Comment by klusark** [comment]
I rebased it, but I haven't addressed the review comments yet.

**Comment by klusark** [comment]
That should resolve all the comments now. If it's good now I'll squash it into two commits. One for NamedConstructor support and one for adding the named constructor to Image

**Comment by Ms2ger** [comment]
+S-needs-code-changes 
Thanks! I'm afraid I have a few more comments still, but it's looking pretty good!

---

Reviewed 1 of 2 files at r2, 3 of 5 files at r7, 1 of 2 files at r8, 1 of 1 files at r9.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/utils.rs, line 203 \[r9\]](https://reviewable.io:443/reviews/servo/servo/6110#-JsR8ve2EuxlW2OtVR_J)** ([raw file](https://github.com/servo/servo/blob/17e3c4960ef4763afe48271b1c2d0485880b4a04/components/script/dom/bindings/utils.rs#L203)):</sup>
I don't think we need the `Option<>` around the entries here.

---

<sup>**[components/script/dom/bindings/utils.rs, line 218 \[r9\]](https://reviewable.io:443/reviews/servo/servo/6110#-JsRBO-lS62uW7Cfm_MG)** ([raw file](https://github.com/servo/servo/blob/17e3c4960ef4763afe48271b1c2d0485880b4a04/components/script/dom/bindings/utils.rs#L218)):</sup>
This code is here twice now

---

<sup>**[components/script/dom/bindings/utils.rs, line 228 \[r9\]](https://reviewable.io:443/reviews/servo/servo/6110#-JsRCKQdpuFIZt3r2AlG)** ([raw file](https://github.com/servo/servo/blob/17e3c4960ef4763afe48271b1c2d0485880b4a04/components/script/dom/bindings/utils.rs#L228)):</sup>
Also translate
```c++
      if (!JS_DefineProperty(cx, namedConstructor, "prototype",
                             proto,
                             JSPROP_PERMANENT | JSPROP_READONLY,
                             JS_STUBGETTER, JS_STUBSETTER)) {
        return nullptr;
      }
```

---

<sup>**[components/script/dom/bindings/utils.rs, line 274 \[r9\]](https://reviewable.io:443/reviews/servo/servo/6110#-JsR9qMKKnHLSlerLOoB)** ([raw file](https://github.com/servo/servo/blob/17e3c4960ef4763afe48271b1c2d0485880b4a04/components/script/dom/bindings/utils.rs#L274)):</sup>
Please move this back to its original place

---

<sup>**[components/script/dom/htmlimageelement.rs, line 13 \[r9\]](https://reviewable.io:443/reviews/servo/servo/6110#-JsR8UGtwEYaF_JVhdYH)** ([raw file](https://github.com/servo/servo/blob/17e3c4960ef4763afe48271b1c2d0485880b4a04/components/script/dom/htmlimageelement.rs#L13)):</sup>
Nit: no {}s

---

<sup>**[tests/wpt/metadata/html/dom/interfaces.html.ini, line 9024 \[r9\]](https://reviewable.io:443/reviews/servo/servo/6110#-JsR8HyTwsK32GPbE2WG)** ([raw file](https://github.com/servo/servo/blob/17e3c4960ef4763afe48271b1c2d0485880b4a04/tests/wpt/metadata/html/dom/interfaces.html.ini#L9024)):</sup>
Why does this fail?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6110)

**Comment by klusark** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[tests/wpt/metadata/html/dom/interfaces.html.ini, line 9024 \[r9\]](https://reviewable.io:443/reviews/servo/servo/6110#-JsR8HyTwsK32GPbE2WG)** ([raw file](https://github.com/servo/servo/blob/17e3c4960ef4763afe48271b1c2d0485880b4a04/tests/wpt/metadata/html/dom/interfaces.html.ini#L9024)):</sup>
I'm trying to verify if this still fails, but now around half the web platform tests are failing for me, even on master...

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6110)

**Comment by Ms2ger** [comment]
Reviewed 4 of 4 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/codegen/CodegenRust.py, line 4565 \[r11\]](https://reviewable.io:443/reviews/servo/servo/6110#-Js_W1YciyhAkjXNIIbT)** ([raw file](https://github.com/servo/servo/blob/675a305e3e00e8827a41422a31528e13d6da8fb1/components/script/dom/bindings/codegen/CodegenRust.py#L4565)):</sup>
I don't think this override is necessary

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6110)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 
Nearly there! Thank you so much.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6110)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-squash 

\o/

---

Reviewed 1 of 1 files at r12.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6110)

**Pull request merged**
