### PR TITLE
Avoid a null-dereference using debug mozjs builds. This matches the e…

### PR DESCRIPTION
**Pull request by jdm**
…quivalent code upstream in Gecko.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8827)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Where would the null deref occur here?

**Comment by jdm** [comment]
```
Process 26668 stopped
* thread #6: tid = 0x3d59ee, 0x000000010285e78c servo`JSCompartment::runtimeFromAnyThread(this=0x0000000000000000) const + 12 at jscompartment.h:201, stop reason = EXC_BAD_ACCESS (code=1, address=0x40)
    frame #0: 0x000000010285e78c servo`JSCompartment::runtimeFromAnyThread(this=0x0000000000000000) const + 12 at jscompartment.h:201
   198 	    // Note: Unrestricted access to the zone's runtime from an arbitrary
   199 	    // thread can easily lead to races. Use this method very carefully.
   200 	    JSRuntime *runtimeFromAnyThread() const {
-> 201 	        return runtime_;
   202 	    }
   203
   204 	    /*
(lldb) bt
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
* thread #6: tid = 0x3d59ee, 0x000000010285e78c servo`JSCompartment::runtimeFromAnyThread(this=0x0000000000000000) const + 12 at jscompartment.h:201, stop reason = EXC_BAD_ACCESS (code=1, address=0x40)
  * frame #0: 0x000000010285e78c servo`JSCompartment::runtimeFromAnyThread(this=0x0000000000000000) const + 12 at jscompartment.h:201
    frame #1: 0x000000010286f362 servo`js::CompartmentChecker::check(this=0x000000011c5f7620, c=0x000000010905ce00) + 50 at jscntxtinlines.h:66
    frame #2: 0x000000010285cd2b servo`js::CompartmentChecker::check(this=0x000000011c5f7620, obj=0x00000001177007b0) + 59 at jscntxtinlines.h:81
    frame #3: 0x0000000102993413 servo`void js::CompartmentChecker::check<js::NativeObject*>(this=0x000000011c5f7620, handle=Handle<js::NativeObject *> at 0x000000011c5f75f8) + 51 at jscntxtinlines.h:91
    frame #4: 0x00000001029933ba servo`void js::assertSameCompartment<JS::Handle<js::NativeObject*>, JS::Handle<js::NativeObject*> >(cx=0x0000000108f049b0, t1=0x000000011c5f7890, t2=0x000000011c5f7898) + 122 at jscntxtinlines.h:180
    frame #5: 0x0000000102919e81 servo`InitializePropertiesFromCompatibleNativeObject(cx=0x0000000108f049b0, dst=js::HandleNativeObject at 0x000000011c5f7898, src=js::HandleNativeObject at 0x000000011c5f7890) + 81 at jsobj.cpp:1885
    frame #6: 0x0000000102919e1d servo`JS_InitializePropertiesFromCompatibleNativeObject(cx=0x0000000108f049b0, dst=JS::HandleObject at 0x000000011c5f7978, src=JS::HandleObject at 0x000000011c5f7970) + 77 at jsobj.cpp:1953
    frame #7: 0x000000010125f1e3 servo`script::dom::bindings::codegen::Bindings::DocumentBinding::Wrap(cx=0x0000000108f049b0, scope=GlobalRef at 0x000000011c5f7de0, object=0x1d1d1d1d1d1d1d1d) + 2947 at DocumentBinding.rs:3895
    frame #8: 0x000000010160f5eb servo`script::dom::bindings::reflector::reflect_dom_object<script::dom::document::Document>(obj=0x1d1d1d1d1d1d1d1d, global=GlobalRef at 0x000000011c5f7eb0, wrap_fn=0x000000010125e660) + 139 at reflector.rs:19
    frame #9: 0x000000010160f3f5 servo`script::dom::document::Document::new(window=0x000000011d45a000, url=Option<url::Url> at 0x000000011c5f8188, doctype=HTMLDocument, content_type=Option<util::str::DOMString> at 0x000000011c5f8168, last_modified=Option<collections::string::String> at 0x000000011c5f8150, source=FromParser, doc_loader=DocumentLoader at 0x000000011c5f8110) + 965 at document.rs:1525
    frame #10: 0x00000001019b26a1 servo`script::script_task::ScriptTask::load(self=0x000000011c5ff848, metadata=Metadata at 0x000000011c5f9590, incomplete=InProgressLoad at 0x000000011c5f9470) + 7761 at script_task.rs:1684
    frame #11: 0x000000010191c77a servo`script::script_task::ScriptTask::handle_page_fetch_complete(self=0x000000011c5ff848, id=PipelineId at 0x000000011c5f9f08, subpage=Option<msg::constellation_msg::SubpageId> at 0x000000011c5f9f00, metadata=Metadata at 0x000000011c5f9d78) + 890 at script_task.rs:1463
    frame #12: 0x000000010191c35a servo`fnfn(root=0x0000000108d4e570) + 442 at script_task.rs:601
    frame #13: 0x000000010191c16f servo`script::thread::local::LocalKey<T>::with<closure,core::option::Option<script::dom::servohtmlparser::ParserRoot>>(self=0x00000001049a51f8, f=closure at 0x000000011c5fa3e0) + 527 at local.rs:217
    frame #14: 0x000000010179303b servo`script::script_task::ScriptTask::page_fetch_complete(id=PipelineId at 0x000000011c5fa8f0, subpage=Option<msg::constellation_msg::SubpageId> at 0x000000011c5fa8e8, metadata=Metadata at 0x000000011c5fa760) + 187 at script_task.rs:599
    frame #15: 0x0000000101791fad servo`script::dom::servohtmlparser::ParserContext.AsyncResponseListener::headers_available(self=0x000000011d44b018, metadata=Metadata at 0x000000011c5fb130) + 397 at servohtmlparser.rs:261
    frame #16: 0x0000000101def99a servo`net_traits::ResponseAction::process(self=ResponseAction at 0x000000011c5fb548, listener=&mut AsyncResponseListener at 0x000000011c5fb538) + 330 at lib.rs:192
    frame #17: 0x00000001019bf306 servo`script::network_listener::ListenerRunnable<T>.Runnable::handler(self=0x0000000114c48540) + 502 at network_listener.rs:48
    frame #18: 0x000000010191dc26 servo`script::script_task::ScriptTask::handle_msg_from_script(self=0x000000011c5ff848, msg=MainThreadScriptMsg at 0x000000011c5fbd28) + 1206 at script_task.rs:1031
    frame #19: 0x000000010199db40 servo`fnfn + 400 at script_task.rs:881
    frame #20: 0x000000010199d6c3 servo`script::script_task::ScriptTask::profile_event<closure,core::option::Option<bool>>(self=0x000000011c5ff848, category=NetworkEvent, f=closure at 0x000000011c5fc6d8) + 931 at script_task.rs:963
    frame #21: 0x00000001019702fe servo`script::script_task::ScriptTask::handle_msgs(self=0x000000011c5ff848) + 8094 at script_task.rs:873
    frame #22: 0x000000010191a2b1 servo`script::script_task::ScriptTask::start(self=0x000000011c5ff848) + 33 at script_task.rs:733
    frame #23: 0x000000010191a265 servo`fnfn + 37 at script_task.rs:530
    frame #24: 0x0000000101919fd1 servo`script::mem::ProfilerChan::run_with_memory_reporting<closure,fn(self=0x000000011c5ffa10, f=closure at 0x000000011c5ff160, reporter_name=String at 0x000000011c5ff148, channel_for_reporter=Box<ScriptChan> at 0x000000011c5ff138, msg=0x00000001015a6bb0) -> script::script_task::CommonScriptMsg,script::script_task::CommonScriptMsg,Box<ScriptChan>> + 577 at mem.rs:60
    frame #25: 0x0000000101904660 servo`fnfn + 2432 at script_task.rs:529
    frame #26: 0x0000000101903a38 servo`fnfn + 104 at task.rs:52
    frame #27: 0x0000000101903424 servo`fnfn + 116 at mod.rs:273
    frame #28: 0x0000000101903399 servo`script::sys_common::unwind::try::try_fn<closure>(opt_closure=0x000000011c600490) + 73 at mod.rs:163
    frame #29: 0x00000001030545f9 servo`__rust_try + 9
    frame #30: 0x00000001030516ff servo`sys_common::unwind::try::inner_try::hdd63401dff52b04dFIs + 111
    frame #31: 0x00000001019032d6 servo`script::sys_common::unwind::try<closure>(f=closure at 0x000000011c6006b8) + 150 at mod.rs:133
    frame #32: 0x000000010190310f servo`fnfn + 431 at mod.rs:273
    frame #33: 0x0000000101903c58 servo`script::boxed::F.FnBox<A>::call_box(self=0x000000011804f000, args=<unavailable>) + 104 at boxed.rs:542
    frame #34: 0x000000010305658e servo`sys::thread::_$LT$impl$GT$::new::thread_start::h146dc2a2095e243ajVw + 142
    frame #35: 0x00007fff91225899 libsystem_pthread.dylib`_pthread_body + 138
    frame #36: 0x00007fff9122572a libsystem_pthread.dylib`_pthread_start + 137
    frame #37: 0x00007fff91229fc9 libsystem_pthread.dylib`thread_start + 13
```

**Comment by jdm** [comment]
We have no compartment when we run JS_InitializePropertiesFromCompatibleNativeObject.

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 2294 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8827#-K4xMNqS8R0cuAcfcFuF:-K4xMNqS8R0cuAcfcFuG:-1011438851) ([raw file](https://github.com/servo/servo/blob/c5756354070b0e5aba65da21b0abb4a491106fb6/components/script/dom/bindings/codegen/CodegenRust.py#L2294)):*
At least in `DocumentBinding::Wrap`, there are now two `JSAutoCompartment`s withing the scope of this one that should probably be removed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8827#-:-K4xMqZ8shm1ovHhYDrJ:1458266033)*

**Comment by jdm** [comment]
Checked the output of WindowBinding.rs, DocumentBinding.rs, and BlobBinding.rs as representative output. In terms of compartments entered, they appear equivalent to their Gecko counterparts.

**Comment by Ms2ger** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8827#-:-K4yG1OhULYZyKDlgP-V:1236647940)*

**Comment by jdm** [comment]
@bors-servo: retry
* infrastructure

**Pull request merged**
