### PR TITLE
Geckolib: minor robustness fixes

### PR DESCRIPTION
**Pull request by bholley**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11058)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11058#-:-KH734WhUNCV7WOxKUu4:1236647940)*

**Comment by bholley** [comment]
Minor tweak. @bors-servo r=mbrubeck,bholley

**Comment by bholley** [comment]
And one more. @bors-servo r=mbrubeck,bholley

**Comment by emilio** [comment]
@bors-servo: retry
 * Random windows failure

The failure is:

```
Running virtualenv with interpreter /usr/bin/python2.7
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [2/-1] Failed to read data: The server returned an invalid or unrecognized response
```

Probably just a bad network, but just in case cc @larsbergstrom ^

**Pull request merged**
