### PR TITLE
Update to rustc 1.17.0-nightly (8c72b7651 2017-03-11)

### PR DESCRIPTION
**Pull request by SimonSapin**
This fixes the DOM node size regression introduced by a previous Rust update: https://github.com/servo/servo/issues/15704

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15911)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@nox r?
@bors-servo try

**Comment by emilio** [comment]
@bors-servo retry 

 * Generic exception

**Comment by SimonSapin** [comment]
The exception was:

>  File "/home/servo/buildbot/master/factories.py", line 40, in run
>    got_rev, rev
> exceptions.Exception: Actual commit (5b0bb6ba9e105c4f2294e494ae2715ecf26aeca5) differs from requested commit (9d8da8dddb2cde3503041072da1dfccfc9ad6bbd)

@nox, this looks like a buildbot bug (?) you showed me on another issue recently. Did you find out what caused it?

**Comment by aneeshusa** [comment]
@SimonSapin, this is a check I [added to saltfs](https://github.com/servo/saltfs/pull/531) because Buildbot will silently fail to checkout the right commit and instead build + test an unrelated commit. It stops the build if it detects this has occurred; the best remediation for now is just to try the build again. Please submit a PR if you have a suggestion for a better error message!

**Comment by SimonSapin** [comment]
@aneeshusa Thanks for adding this check. Indeed the build should be marked as unsuccessful when that happens. My question was, how can it happen in the first place?

**Comment by aneeshusa** [comment]
The `Git` step built in to Buildbot is buggy. We have `retryFetch=True` since our build machines have trouble `git fetch`ing often. In the [Buildbot source](https://github.com/buildbot/buildbot/blob/c385ad4310c4c09aac0841726a9a09d2e3f00898/master/buildbot/steps/source/git.py#L395), this causes the builder to retry the fetch a second time. However, on both runs, `abandonOnFailure` is set to False for the git reset command which checks out the new commit since we have `retryFetch=True` ([source](https://github.com/buildbot/buildbot/blob/c385ad4310c4c09aac0841726a9a09d2e3f00898/master/buildbot/steps/source/git.py#L385)). This appears to cause the silent error masking, and in my opinion, `abandonOnFailure` should be forced to True on the retry.

**Pull request merged**
