### PR TITLE
Support navigation keys

### PR DESCRIPTION
**Pull request by Manishearth**
Rather useful.

If most people have these keys on their keyboard, I'd prefer to remove the backspace navigation handler. I've never used it on purpose, but it gets hit often by accident when an input widget isn't focused (either due to a misclick or debug build lag).

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10122)

### CODE REVIEW

**Comment by metajack** [comment]
+1 for getting rid of backspace. We should also have something that is not a media key to bind to back, but that can be handled in another PR once we have some idea what the key binding should be.

**Comment by asajeffrey** [comment]
Looks good. Has a fix for ContextMenu which is correct but unrelated.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/keyboardevent.rs, line 620 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10122#-KDUCKt1Gpr298jzIYGH:-KDUCKt1Gpr298jzIYGI:2036831202) ([raw file](https://github.com/servo/servo/blob/b25d9de03d1cd51235bc08af5935e2371a8d88c4/components/script/dom/keyboardevent.rs#L620)):*
Should this be a separate PR?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10122#-:-KDUCXR97jlIf_wAl4Pw:-793270197)*

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/keyboardevent.rs, line 620 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10122#-KDUCKt1Gpr298jzIYGH:-KDUJQxYfXFMMCbBNZRo:-725239132) ([raw file](https://github.com/servo/servo/blob/b25d9de03d1cd51235bc08af5935e2371a8d88c4/components/script/dom/keyboardevent.rs#L620)):*
It's a minor change, so I batched it up. Though we could make an easy bug out of this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10122)*

**Comment by samlh** [comment]
Just for future reference I usually use Alt-Left and Alt-Right for back and forward respectively on Windows. I do not have navigation keys, but I do have a back mouse button.

I see Safari uses CMD + [ and CMD + ], however, so the only shortcuts available on all current browsers are Backspace and Shift + Backspace.

**Comment by Manishearth** [comment]
Ah, alt-left / alt-right sound like a good fix. We can file an easy bug for this.

**Comment by paulrouget** [comment]
Can these be caught in JS and preventDefault'ed?

**Comment by jdm** [comment]
It looks like they operate the same as the existing backspace code.

**Comment by Manishearth** [comment]
Yep.

**Comment by asajeffrey** [comment]
Hmm, the failure is css21_dev/html4/units-002.htm, which doesn't seem to be a known intermittent.

**Comment by jdm** [comment]
@bors-servo: retry
* #8815

**Comment by Manishearth** [comment]
@bors-servo retry

 - appveyor borked

**Pull request merged**
