### PR TITLE
style: Get rid of gecko_size_type.

### PR DESCRIPTION
**Pull request by emilio**
It's a hack, should die.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19966)

### CODE REVIEW

**Comment by emilio** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=faa6f3bbe94bc5c5b835d3aa8f02d3bd333de2a7

Is the try run, let's see if I haven't messed up.

**Comment by emilio** [comment]
I did indeed mess up, since I overlooked the `ToComputedValue` implementations. Indeed I even fixed a style sharing issue.

https://treeherder.mozilla.org/#/jobs?repo=try&revision=d49ad62ceb6430020ebbdc8dba4b24b7b27db347

**Comment by nox** [comment]
r=me with the green geckotry, nice work.

**Comment by ionutgoldan** [comment]
Performance improvements noticed, thanks to this!

== Change summary for alert #11496 (as of Wed, 07 Feb 2018 01:02:13 GMT) ==

Improvements:

  7%  Stylo Servo_DeclarationBlock_SetPropertyById_Bench osx-10-10 opt      536,227.96 -> 497,745.25
  7%  Stylo Servo_DeclarationBlock_SetPropertyById_WithInitialSpace_Bench osx-10-10 opt 537,683.83 -> 499,260.92
  6%  Stylo Servo_DeclarationBlock_SetPropertyById_Bench windows10-64 opt   438,529.71 -> 410,087.83
  6%  Stylo Servo_DeclarationBlock_SetPropertyById_WithInitialSpace_Bench windows10-64 opt 439,534.08 -> 411,964.83
  4%  Stylo Servo_DeclarationBlock_SetPropertyById_Bench windows7-32 opt    602,626.50 -> 579,663.75

For up to date results, see: https://treeherder.mozilla.org/perf.html#/alerts?id=11496

**Comment by bholley** [comment]
Whoa, that's awesome. @emilio, does that make sense to you? I don't know what gecko_size_type was or what it did.

**Comment by bholley** [comment]
It's possible that these wins might instead be attributable to #19956, which landed on the same day, and seems more likely to have affected these benchmarks?

**Comment by emilio** [comment]
Yeah, this PR removes some extra indirection and branches, but unless the property is `width` or something like that it should have no effect on that. #19956 seems like a better candidate :)

**Comment by emilio** [comment]
Actually the properties that those are benchmarking is `width` so it seems plausible that it's due to this PR.

**Comment by nox** [comment]
Probably a combination of the two. `gecko_size_type` existing reduced the opportunities for my PR to do good things.

**Pull request merged**
