### PR TITLE
Replace libpng and stb_image with PistonDevelopers/image

### LINKED ISSUE #3368: Switch to Piston's image library
[rust-image](https://github.com/PistonDevelopers/rust-image) appears to support everything we require from an image library right now, and it's native rust code. It would be nice to scrap stb-image and rust-png if possible, but we should definitely take some measurements to sure what the performance is like before and after switching.

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes #3368. r? @glennw 

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7933)

### CODE REVIEW

**Comment by waddlesplash** [comment]
Less unsafe code being used! :clap: :clap: :clap:

**Comment by glennw** [comment]
One question - the piston docs say only baseline jpeg is supported, but I added a reftest a while ago that checks for progressive jpeg decoding. Do all the reftests pass ok? Perhaps the piston docs are out of date. Apart from that question, r=me.

**Comment by mbrubeck** [comment]
Oops, forgot to do a full test run. Indeed, the progressive JPEG test fails.  (This is PistonDevelopers/image#451.)

Perhaps we should keep stb_image as a fallback for now and use it if `image` returns an UnsupportedError...  Or we can wait to land this until `image` has more complete format support.

**Comment by mbrubeck** [comment]
Updated to get rid of libpng, and to use stb_image for jpegs until `image` supports progressive jpeg. The try run shows a cross-compile failure in the `gif` crate (PistonDevelopers/image-gif#2) and a handful of failures in test-ref and test-css.

**Comment by mbrubeck** [comment]
The `gif` link error on gonk is happening because `ports/gonk/fake-ld.sh` is passing the `-pie` option when linking a dylib. (It should be passed only when linking an executable.)

**Comment by waddlesplash** [comment]
Note that image-png uses flate2 which is C -- there is an issue open over there to replace it with something pure-Rust, but as of now there is nothing which passes all the tests.

Maybe Servo should have an "audit stuff using C and check for / switch to Rust stuff instead" tracking issue?

**Comment by Ms2ger** [comment]
Time to turn `fake-ld.sh` into a python script

**Comment by nwin** [comment]
@waddlesplash: We are only using flate2 for encoding.

**Comment by mbrubeck** [comment]
Updated with changes to completely get rid of libpng, and fix build/test errors.  r? @glennw

**Comment by mbrubeck** [comment]
`!=` reftests were failing because of a bug in the new PNG writing code in the harness. Fixed now.

**Comment by frewsxcv** [comment]
For what it's worth, this PR caused a regression and Google News now panics: https://github.com/servo/servo/issues/8093

**Pull request merged**
