### PR TITLE
Cleanup some unneeded let bindings

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8304)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[ports/cef/window.rs, line 472 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8304#-K2CNIKq3IoixboyjWzi)** ([raw file](https://github.com/servo/servo/blob/f02885e993b4e4c8f4b5c941701c7340f8545644/ports/cef/window.rs#L472)):</sup>
This does not look correct.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8304)

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[ports/cef/window.rs, line 472 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8304#-K2CNIKq3IoixboyjWzi)** ([raw file](https://github.com/servo/servo/blob/f02885e993b4e4c8f4b5c941701c7340f8545644/ports/cef/window.rs#L472)):</sup>
I was guessing here, what's the problem? (Is there a way to compile the CEF port on OSX?)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8304)

**Comment by eefriedman** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[ports/cef/window.rs, line 472 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8304#-K2CNIKq3IoixboyjWzi)** ([raw file](https://github.com/servo/servo/blob/f02885e993b4e4c8f4b5c941701c7340f8545644/ports/cef/window.rs#L472)):</sup>
Among other things, the variable `frame_url` isn't defined anywhere.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8304)

**Comment by jdm** [comment]
`./mach build-cef`

**Comment by dzbarsky** [comment]
OK it actually builds now

**Comment by Ms2ger** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[ports/cef/window.rs, line 472 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8304#-K2CNIKq3IoixboyjWzi)** ([raw file](https://github.com/servo/servo/blob/f02885e993b4e4c8f4b5c941701c7340f8545644/ports/cef/window.rs#L472)):</sup>
You no longer update `servoframe.url`. Just revert these changes, please.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8304)

**Comment by dzbarsky** [comment]
Ok done

**Comment by Ms2ger** [comment]
Needs a rebase now.

**Comment by dzbarsky** [comment]
Rebased.

**Pull request merged**
