### PR TITLE
Add Servo3D immersive demo for magicleap

### LINKED ISSUE #22402: Immersive mode for magicleap
Implement immersive mode WebVR/XR for magicleap.

### PR DESCRIPTION
**Pull request by asajeffrey**
An immersive mode demo for magicleap.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors (apart from dupes, sigh)
- [X] These changes fix #22402 (GitHub issue number if applicable)
- [X] These changes do not require tests because it's a new platform

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23546)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Sigh, dupes:
```
./Cargo.lock:1: duplicate versions for package `winapi`
	The following packages depend on version 0.2.8 from 'crates.io':
		iovec
		kernel32-sys
		mio
		miow
		ws2_32-sys
	The following packages depend on version 0.3.6 from 'crates.io':
		ansi_term
		atty
		backtrace
		clipboard-win
		dirs
		dwrote
		dwrote
		font-kit
		glutin
		glutin
		glutin_egl_sys
		libloading
		memmap
		memmap
		msdos_time
		net2
		offscreen_gl_context
		parking_lot_core
		parking_lot_core
		parking_lot_core
		rand
		rand
		rand
		rand_jitter
		rand_os
		remove_dir_all
		same-file
		servo
		servo_allocator
		simpleservo
		tempfile
		time
		walkdir
		winapi-util
		wincolor
		winit
		winit
./Cargo.lock:1: duplicate versions for package `winit`
	The following packages depend on version 0.18.0 from 'crates.io':
		glutin
	The following packages depend on version 0.19.1 from 'crates.io':
		glutin
./Cargo.lock:1: duplicate versions for package `glutin`
	The following packages depend on version 0.19.0 from 'crates.io':
		servo-skia
	The following packages depend on version 0.21.0 from 'crates.io':
		rust-webvr
		servo
```

**Comment by asajeffrey** [comment]
Deduped. Thanks @Eijebong!

**Review by Manishearth — APPROVED** [review]
r=me, haven't looked too closely at the cpp but it seems fine.

**Comment by CYBAI** [comment]
In Android ARM build:

```rust
error[E0061]: this function takes 3 parameters but 4 parameters were supplied
   --> ports/libsimpleservo/jniapi/src/lib.rs:109:44
    |
109 |         gl_glue::egl::init().and_then(|gl| simpleservo::init(opts, gl, wakeup, callbacks))
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters

error[E0560]: struct `simpleservo::InitOptions` has no field named `vr_pointer`
   --> ports/libsimpleservo/jniapi/src/lib.rs:699:9
    |
699 |         vr_pointer: if vr_pointer.is_null() {
    |         ^^^^^^^^^^ `simpleservo::InitOptions` does not have this field
    |
    = note: available fields are: `args`, `url`, `coordinates`, `density`, `embedder_callbacks`, `enable_subpixel_text_antialiasing`

error: aborting due to 2 previous errors
```

In Linux Tidy and Windows build:

```rust
+ ./mach build --dev --libsimpleservo
    Downloading  crates ...
     Downloaded  cbindgen v0.8.0
      Compiling  simpleservo v0.0.1 (/repo/ports/libsimpleservo/api)
      Compiling  rust-webvr v0.11.4
      Compiling  cbindgen v0.8.0
      Compiling  webvr v0.0.1 (/repo/components/webvr)
      Compiling  compositing v0.0.1 (/repo/components/compositing)
      Compiling  simpleservo_capi v0.0.1 (/repo/ports/libsimpleservo/capi)
      Compiling  canvas v0.0.1 (/repo/components/canvas)
      Compiling  constellation v0.0.1 (/repo/components/constellation)
      Compiling  libservo v0.0.1 (/repo/components/servo)
   error[E0560]  : struct `simpleservo::InitOptions` has no field named `vr_pointer` 
      -->  ports/libsimpleservo/capi/src/lib.rs:99:9 
       | 
99     |          vr_pointer: if opts.vr_pointer.is_null() { 
       |             ^^^^^^^^^^     `simpleservo::InitOptions` does not have this field 
       | 
       =   note : available fields are: `args`, `url`, `coordinates`, `density`, `embedder_callbacks`, `enable_subpixel_text_antialiasing` 

   error[E0061]  : this function takes 3 parameters but 4 parameters were supplied 
       -->  ports/libsimpleservo/capi/src/lib.rs:110:5 
        | 
110     |      simpleservo::init(opts, gl, wakeup, callbacks).unwrap(); 
        |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     expected 3 parameters 

   error  : aborting due to 2 previous errors 

  Some errors have detailed explanations: E0061, E0560. 
  For more information about an error, try `rustc --explain E0061`. 
  error:  Could not compile `simpleservo_capi`.
```

**Comment by asajeffrey** [comment]
Yeah, my changes to libsimpleservo didn't get reflected in the other embeddings.

**Comment by asajeffrey** [comment]
Oh that's right, `ports/glutin`, I remember that.

**Comment by asajeffrey** [comment]
Squashed. @Manishearth r'd on IRC https://mozilla.logbot.info/servo/20190613#c16393689

@bors-servo r=Manishearth

**Comment by asajeffrey** [comment]
Hmm, the build never finished, let's try again.@bors-servo r=Manishearth

**Comment by jdm** [comment]
https://treeherder.allizom.org/#/jobs?repo=servo-auto&revision=98d3dbb3776d128f7738cba9953e121a14003f56 has failures from last time.

**Comment by asajeffrey** [comment]
I think I fixed those in the most recent force-push.

**Comment by asajeffrey** [comment]
And that last fix broke test-tidy. Of course it did. @bors-servo r=Manishearth

**Pull request merged**
