### PR TITLE
implement and use From<bool> for enum and back

### PR DESCRIPTION
**Pull request by apopiak**
as discussed in the #servo channel on IRC:

implement and use  `From<bool>` for `EventBubbles` (and back direction)
implement and use `From<bool>` for `EventCancelable` (and back direction)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10066)

### CODE REVIEW

**Comment by jdm** [comment]
Does using `something.into()` instead of `bool::from(something)` work?

**Comment by asajeffrey** [comment]
This code looks a lot nicer than the old version! I'll have a better look at it tomorrow.

**Comment by asajeffrey** [comment]
OK, this is a big improvement. The only niggle I'd have is that some linebreaks in the code could now be changed, since it's much shorter than it used to be.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10066#-:-KDARrk5bo00whq9Wuxt:-680091127)*

**Comment by asajeffrey** [comment]
@jdm I think it's a matter of taste whether to use `x.into()` or `T::from(x)`. I actually prefer `T::from(x)` even though it's longer, just because it's more explicit and doesn't require the reader to do as much type inference in their head.

**Comment by jdm** [comment]
Fair enough!

**Comment by asajeffrey** [comment]
@apopiak would you like to change the linebreaks, or just leave it as is? Not exactly a deal-breaker.

**Comment by apopiak** [comment]
I think I'd prefer merging as is, but could have another look if necessary.

**Comment by asajeffrey** [comment]
No, that's fine, thanks for the work!

@bors-servo: r+

**Pull request merged**
