### PR TITLE
added lets encrypt authority x3 to trusted roots pem

### LINKED ISSUE #15087: servoexperiments.com gives an ssl error
nightly gives SSL routines: ssl3_get_server_certificate - certificate verify failed
my local build gives DEBUG:net::connector: Verification error: WebPKIError(UnknownIssuer)

In FF, the certificate hierarchy is:
* DST Root CA X3
    * Let's Encrypt Authority X3

When I look at the certificate chain in connector.rs, I see the Let's Encrypt Authority certificate, so I'll see if we have the appropriate root in our cert roots file.

### PR DESCRIPTION
**Pull request by avadacatavra**
servo gave an ssl error on servoexperiments.com because it didn't have the Let's Encrypt X3 authority (https://letsencrypt.org/certificates/)

---

- [X ] `./mach build -d` does not report any errors
- [X ] `./mach test-tidy` does not report any errors
- [ X] These changes fix #15087 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ X] These changes do not require tests because webpage couldn't load before, can now :)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15104)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo r+

The added chunk is https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt

Should X4 be also added?

**Comment by avadacatavra** [comment]
@SimonSapin X4 is a backup, so we should only add it if they can't use X3:

> Under normal circumstances, certificates issued by Let’s Encrypt will come from “Let’s Encrypt Authority X3”. The other intermediate, “Let’s Encrypt Authority X4”, is reserved for disaster recovery and will only be used should we lose the ability to issue with “Let’s Encrypt Authority X3”.

**Pull request merged**
