### PR TITLE
Upgrade to rustc 1.34.0-nightly (097c04cf4 2019-02-24)

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22937)

### CODE REVIEW

**Comment by CYBAI** [comment]
Complained by Travis about tidy

<details>

```
tidy reported no errors.
info: downloading component 'rustfmt'
info: installing component 'rustfmt'
Diff in /home/travis/build/servo/servo/components/script_plugins/unrooted_must_root.rs at line 121:
     ) {
         let item = match cx.tcx.hir().get_by_hir_id(id) {
             hir::Node::Item(item) => item,
-            _ => cx.tcx.hir().expect_item_by_hir_id(cx.tcx.hir().get_parent_item(id)),
+            _ => cx
+                .tcx
+                .hir()
+                .expect_item_by_hir_id(cx.tcx.hir().get_parent_item(id)),
         };
         if item.attrs.iter().all(|a| !a.check_name("must_root")) {
             for ref field in def.fields() {
Diff in /home/travis/build/servo/servo/components/selectors/parser.rs at line 1959:
                 let name = match input.next_including_whitespace()? {
                     &Token::Ident(ref name) => name.clone(),
                     t => {
-                        return Err(location
-                            .new_custom_error(SelectorParseErrorKind::NoIdentForPseudo(t.clone())));
+                        return Err(location.new_custom_error(
+                            SelectorParseErrorKind::NoIdentForPseudo(t.clone()),
+                        ));
                     },
                 };
 
Diff in /home/travis/build/servo/servo/components/style/values/specified/calc.rs at line 180:
             ) => {
                 return NoCalcLength::parse_dimension(context, value, unit)
                     .map(CalcNode::Length)
-                    .map_err(|()| location.new_custom_error(StyleParseErrorKind::UnspecifiedError));
+                    .map_err(|()| {
+                        location.new_custom_error(StyleParseErrorKind::UnspecifiedError)
+                    });
             },
             (
                 &Token::Dimension {
Diff in /home/travis/build/servo/servo/components/style/values/specified/calc.rs at line 190:
             ) => {
                 return Angle::parse_dimension(value, unit, /* from_calc = */ true)
                     .map(CalcNode::Angle)
-                    .map_err(|()| location.new_custom_error(StyleParseErrorKind::UnspecifiedError));
+                    .map_err(|()| {
+                        location.new_custom_error(StyleParseErrorKind::UnspecifiedError)
+                    });
             },
             (
                 &Token::Dimension {
Diff in /home/travis/build/servo/servo/components/style/values/specified/calc.rs at line 200:
             ) => {
                 return Time::parse_dimension(value, unit, /* from_calc = */ true)
                     .map(CalcNode::Time)
-                    .map_err(|()| location.new_custom_error(StyleParseErrorKind::UnspecifiedError));
+                    .map_err(|()| {
+                        location.new_custom_error(StyleParseErrorKind::UnspecifiedError)
+                    });
             },
             (&Token::Percentage { unit_value, .. }, CalcUnit::LengthPercentage) |
             (&Token::Percentage { unit_value, .. }, CalcUnit::Percentage) => {
Diff in /home/travis/build/servo/servo/components/style/values/specified/color.rs at line 274:
                 if ident.len() != 3 && ident.len() != 6 {
                     return Err(location.new_custom_error(StyleParseErrorKind::UnspecifiedError));
                 }
-                return parse_hash_color(ident.as_bytes())
-                    .map_err(|()| location.new_custom_error(StyleParseErrorKind::UnspecifiedError));
+                return parse_hash_color(ident.as_bytes()).map_err(|()| {
+                    location.new_custom_error(StyleParseErrorKind::UnspecifiedError)
+                });
             },
             ref t => {
                 return Err(location.new_unexpected_token_error(t.clone()));
Diff in /home/travis/build/servo/servo/components/style/values/specified/length.rs at line 614:
                         !context.parsing_mode.allows_unitless_lengths() &&
                         !allow_quirks.allowed(context.quirks_mode)
                     {
-                        return Err(location.new_custom_error(StyleParseErrorKind::UnspecifiedError));
+                        return Err(
+                            location.new_custom_error(StyleParseErrorKind::UnspecifiedError)
+                        );
                     }
                     return Ok(Length::NoCalc(NoCalcLength::Absolute(AbsoluteLength::Px(
                         value,
Diff in /home/travis/build/servo/servo/components/style/values/specified/time.rs at line 93:
             Ok(&Token::Dimension {
                 value, ref unit, ..
             }) if clamping_mode.is_ok(ParsingMode::DEFAULT, value) => {
-                return Time::parse_dimension(value, unit, /* from_calc = */ false)
-                    .map_err(|()| location.new_custom_error(StyleParseErrorKind::UnspecifiedError));
+                return Time::parse_dimension(value, unit, /* from_calc = */ false).map_err(|()| {
+                    location.new_custom_error(StyleParseErrorKind::UnspecifiedError)
+                });
             },
             Ok(&Token::Function(ref name)) if name.eq_ignore_ascii_case("calc") => {},
             Ok(t) => return Err(location.new_unexpected_token_error(t.clone())),
Run `./mach fmt` to fix the formatting
The command "./mach test-tidy --no-progress --all" exited with 1.
```

</details>

**Comment by SimonSapin** [comment]
It’s somewhat worrying that rustfmt apparently keeps changing its mind about style decisions :/

@bors-servo r=nox

**Comment by SimonSapin** [comment]
@bors-servo retry

Timeout

**Pull request merged**
