### PR TITLE
Pass --no-patch by default to update_css

### LINKED ISSUE #10884: mach update-css has confusing semantics
I ran the following, after changing some code that caused tests that previously passed to fail:

```
$ ./mach update-css /tmp/foo
```

Then I tried with `git diff`. It didn't show me anything; I assumed the command hadn't worked. It was only when @jdm told me to `git show` that I realized it had behind-the-scenes creates a new commit with the `.ini` file changes in.

This is a confusing behavior and IMHO a bad default. _If_ we really want it to automagically commit code (which I think is questionable to begin with), it should at least not just keep silent about it. The `git commit` output should be shown if we retain the current behavior. (but I'd vote for just leaving the files dirty since that'd be how I'd guess it would work by just looking at it from the outside.)

Looked a bit but I couldn't immediately find where in this code this happens.

### PR DESCRIPTION
**Pull request by CorcovadoMing**
fix #10884 according to #9666

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10892)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Please claim the issue for yourself before working on it, so that we can avoid duplicated efforts :)

**Comment by CorcovadoMing** [comment]
@Wafflespeanut This is my first PR to servo, sorry about it

**Comment by Wafflespeanut** [comment]
Thanks for doing this :)

@bors-servo r+

**Comment by larsbergstrom** [comment]
Hrm, unclear why homu did not merge this.

Also suspicious that http://build.servo.org/builders/windows/builds/308 (which was successful) was not reported.

**Comment by larsbergstrom** [comment]
I believe that what happened here is there was an intermittent GH outage that caused the merge to fail. This now requires re-testing.

**Comment by Wafflespeanut** [comment]
@larsbergstrom Thanks for the cleanup! :)

**Pull request merged**
