### PR TITLE
Add fix / hack for compositor repainting tiles on scroll layers that have stale clipping results.

### LINKED ISSUE #7153: Items in scrollable layers can be clipped incorrectly.
The code that clips items is here:

https://github.com/servo/servo/blob/master/components/layout/display_list_builder.rs#L925

An example of what happens:

* A scroll layer has height 2000, with visible height of 768.
* The first tile paints at 512x512 correctly.
* The second tile paints at 512x512 and correctly clips items in the code above that are outside the 768 pixel enclosing rect.
* When you scroll, the compositor doesn't ask for the 2nd tile to be repainted, as it hasn't changed.

This means that items clipped during the first render never get added to the display list as you scroll.

We could potentially force a repaint, but isn't this what the display port code should be handling? Perhaps we should just remove the clipping above and rely on the display port clipping?

cc @pcwalton

### PR DESCRIPTION
**Pull request by glennw**
Needed for #6643. Fixes #7153.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7183)

### CODE REVIEW

**Comment by pcwalton** [comment]
Hmm, I wonder if it'd be easier to just get rid of the clip entirely for overflow:scroll layers (or set the clip to maximum). They aren't "clipped" as far as gfx is concerned, because the compositor manages their clipping. What do you think?

**Comment by glennw** [comment]
@pcwalton My initial idea was to just set clip = ClippingRegion::max() in the overflow:scroll case, but this doesn't work - as other child display lists / stacking contexts still result in the items being clipped. Unless there is some other way you were thinking of doing it?

**Comment by pcwalton** [comment]
I'm not sure why other child display lists or stacking contexts would result in the items being clipped any differently than usual. DL construction is a bottom-up process, so I'm not sure I see how the fact that a child stacking context is underneath an overflow:scroll flow would result in a clipping rectangle any different from a child stacking context directly underneath the `<body>`, say. I must be missing something…

**Comment by glennw** [comment]
That's true - I'll check the exact rect in that case that causes the clipping issue...

**Comment by glennw** [comment]
@pcwalton My original test case was incorrect - changed to a much simpler fix.

**Pull request merged**
