### PR TITLE
Notify devtools about new worker globals

### PR DESCRIPTION
**Pull request by thiagopnts**
This is for #4704. I'm not sure if this is the best approach, so I'm open to suggestions.

### CODE REVIEW

**Comment by jdm** [comment]
Good start! I've left some comments on Critic about ways I think we can improve this design, but it's basically what I was expecting :)

**Comment by thiagopnts** [comment]
@jdm I did some changes to address the issues from Critic!

**Comment by jdm** [comment]
There are a couple new Critic issues, but it's close!

**Comment by thiagopnts** [comment]
@jdm I made a new commit on this

**Comment by jdm** [comment]
Looks good! These changes notify the devtools about the new worker global when it's a top-level worker, and I'll file a couple follow-up issues to support sub-workers and making use of the currently-ignored receiver and allowing devtools to actually communicate with the new global.

**Comment by jdm** [comment]
Go ahead and rebase the changes, and you can squash them all into one commit.

**Comment by thiagopnts** [comment]
@jdm All done!

**Comment by thiagopnts** [comment]
Also, I want to keep working on the next issues related to this!

**Comment by jdm** [comment]
Great :)

**Comment by jdm** [comment]
This needs to be rebased, unfortunately - the Actor interface changed the type of one of the arguments to handle_message.

**Comment by thiagopnts** [comment]
@jdm rebased!

**Pull request closed without merging**
