### PR TITLE
script: Make timer events e10s-safe.

### LINKED ISSUE #8235: TimerEventRequest is completely un-e10s-safe (blocks e10s from landing)
Boxed trait objects sent from script to compositor. This is a big no-no.

### PR DESCRIPTION
**Pull request by pcwalton**
Closes #8235.

r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8237)

### CODE REVIEW

**Comment by pcwalton** [comment]
Until this lands e10s cannot land.

**Comment by Ms2ger** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 232 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8237#-K1hzhBX3R7z1VV2O2YZ)** ([raw file](https://github.com/servo/servo/blob/ac618ecafd16df2421cf804a6ca35e565ad03c3e/components/script/dom/dedicatedworkerglobalscope.rs#L232)):</sup>
Does this leak all workers until process exit?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8237)

**Comment by jdm** [comment]
This should not change the lifetime of workers from the status quo (which will, in fact, leak until the ActiveTimers value is dropped). Addressing that issue should happen separately.

**Comment by jdm** [comment]
```
./ports/gonk/Cargo.lock:259: conflicting versions for package "serde_macros"
	expected maximum version "0.6.1"
	but, "compositing" demands "0.5.3"
	try upgrading with ./mach cargo-update -p serde_macros:0.5.3
```

**Comment by pcwalton** [comment]
No idea what the error means. @larsbergstrom ?

**Comment by jdm** [comment]
Plausibly the gonk Cargo.lock isn't up to date, so it ends up pulling in the latest version of something that isn't specified?

**Comment by metajack** [comment]
Isn't tidy supposed to catch that, or do we not run that check on gonk?

**Comment by jdm** [comment]
Tidy only looks for incompatible entries in lock files; there is no inter-file comparison.

**Comment by jdm** [comment]
I just checked and the lock files are fine on master, and I can't see why this PR would affect that since no toml files are modified, however :(

**Comment by jdm** [comment]
Oh wait, there are lock file changes that upgrade serde, which presumably is incompatible with the version of rustc we're currently using.

**Comment by metajack** [comment]
@jdm I meant that if the lockfile after build is different than the lockfile it started with. That is supposed to catch out of date Cargo.locks

**Comment by jdm** [comment]
Pretty sure that check wouldn't be reached if the build failed...

**Comment by metajack** [comment]
@jdm Well if the lockfile was out of date, then there was a build that passed with it.

@pcwalton Can you fix this up?

**Pull request closed without merging**
