### PR TITLE
[WIP] Move all table layout calculations from table_wraper.rs to table.rs

### PR DESCRIPTION
**Pull request by KiChjang**
There's no reason why tables are calculated in different files. This PR moves all of them to be under `table.rs`, which is more in accordance with the CSS 3 table spec. `table_wrapper.rs` now is pretty much empty; in a later PR, I plan to follow the spec fully and propagate the caption width minimum to the table accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20910)

### CODE REVIEW

**Comment by KiChjang** [comment]
<details>
```
{"status": "FAIL", "group": "default", "message": "/css/CSS2/borders/border-applies-to-013.xht 4a0a3391c5f89d8d1b755cf120c6c4aad5e15a46\n/css/CSS2/borders/border-applies-to-001-ref.xht 9071e187f05acfa53fd0c19fd66377f4775b1317\nTesting 4a0a3391c5f89d8d1b755cf120c6c4aad5e15a46 == 9071e187f05acfa53fd0c19fd66377f4775b1317", "stack": null, "subtest": null, "test": "/css/CSS2/borders/border-applies-to-013.xht", "line": 3094, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/backgrounds/background-position-applies-to-007.xht 0584e0e2d36d869a0cac23226deca7925bdd864f\n/css/CSS2/backgrounds/background-position-applies-to-001-ref.xht 6685a94f896d98e87608d0421570f1b05da04b70\nTesting 0584e0e2d36d869a0cac23226deca7925bdd864f == 6685a94f896d98e87608d0421570f1b05da04b70", "stack": null, "subtest": null, "test": "/css/CSS2/backgrounds/background-position-applies-to-007.xht", "line": 3226, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/backgrounds/background-position-applies-to-013.xht 0584e0e2d36d869a0cac23226deca7925bdd864f\n/css/CSS2/backgrounds/background-position-applies-to-001-ref.xht 6685a94f896d98e87608d0421570f1b05da04b70\nTesting 0584e0e2d36d869a0cac23226deca7925bdd864f == 6685a94f896d98e87608d0421570f1b05da04b70", "stack": null, "subtest": null, "test": "/css/CSS2/backgrounds/background-position-applies-to-013.xht", "line": 3309, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/borders/border-color-applies-to-013.xht 4a0a3391c5f89d8d1b755cf120c6c4aad5e15a46\n/css/CSS2/borders/border-applies-to-001-ref.xht 9071e187f05acfa53fd0c19fd66377f4775b1317\nTesting 4a0a3391c5f89d8d1b755cf120c6c4aad5e15a46 == 9071e187f05acfa53fd0c19fd66377f4775b1317", "stack": null, "subtest": null, "test": "/css/CSS2/borders/border-color-applies-to-013.xht", "line": 4619, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/box-display/display-015.xht 3eb76b621d364d4ad915f2383a1a6b3a3bceb41f\n/css/CSS2/box-display/display-002-ref.xht 114485495c161f1b25a9facbd62bbd5bafd91f4a\nTesting 3eb76b621d364d4ad915f2383a1a6b3a3bceb41f == 114485495c161f1b25a9facbd62bbd5bafd91f4a", "stack": null, "subtest": null, "test": "/css/CSS2/box-display/display-015.xht", "line": 9813, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/box-display/display-012.xht 6fa577f5ec3c0e171f2938cda307dea395edff75\n/css/CSS2/box-display/display-012-ref.xht cd7583d00cf28f87ebdfbc3dfb5e4abc2db46da2\nTesting 6fa577f5ec3c0e171f2938cda307dea395edff75 == cd7583d00cf28f87ebdfbc3dfb5e4abc2db46da2", "stack": null, "subtest": null, "test": "/css/CSS2/box-display/display-012.xht", "line": 10213, "action": "test_result", "expected": "PASS"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css/CSS2/css21-errata/s-11-1-1b-002.html", "line": 10285, "action": "test_result", "expected": "FAIL"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-applies-to-003.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-applies-to-003.xht", "line": 10389, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/box-display/display-006.xht ec24f4fa9e32926dff70c56d96eb67611b7b6eb0\n/css/CSS2/box-display/display-001-ref.xht 4dfe872bb8ee9e95438ae17807f3b39bac6c43fa\nTesting ec24f4fa9e32926dff70c56d96eb67611b7b6eb0 == 4dfe872bb8ee9e95438ae17807f3b39bac6c43fa", "stack": null, "subtest": null, "test": "/css/CSS2/box-display/display-006.xht", "line": 10538, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/box-display/display-014.xht ec24f4fa9e32926dff70c56d96eb67611b7b6eb0\n/css/CSS2/box-display/display-001-ref.xht 4dfe872bb8ee9e95438ae17807f3b39bac6c43fa\nTesting ec24f4fa9e32926dff70c56d96eb67611b7b6eb0 == 4dfe872bb8ee9e95438ae17807f3b39bac6c43fa", "stack": null, "subtest": null, "test": "/css/CSS2/box-display/display-014.xht", "line": 10768, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-applies-to-004.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-applies-to-004.xht", "line": 10969, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-type-applies-to-015.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-type-applies-to-015.xht", "line": 11089, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-applies-to-002.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-applies-to-002.xht", "line": 11098, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-applies-to-015.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-applies-to-015.xht", "line": 11120, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/css21-errata/s-11-1-1b-006.html d1b09b1c6bdb7c185be4e8028bf2e373f8a7e17a\n/css/CSS2/css21-errata/s-11-1-1b-005-ref.html 89cf785d27af3ee2e3a1214eecb575fa711aaf13\nTesting d1b09b1c6bdb7c185be4e8028bf2e373f8a7e17a == 89cf785d27af3ee2e3a1214eecb575fa711aaf13", "stack": null, "subtest": null, "test": "/css/CSS2/css21-errata/s-11-1-1b-006.html", "line": 11162, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-type-applies-to-002.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-type-applies-to-002.xht", "line": 11226, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-type-applies-to-013.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-type-applies-to-013.xht", "line": 11273, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/box-display/display-008.xht c06f23cc7beb7cdebaf0fc58a2a364e22737c129\n/css/CSS2/box-display/display-008-ref.xht e4614e3ffa5ae0138bbbdf026cb00aa367b8ac67\nTesting c06f23cc7beb7cdebaf0fc58a2a364e22737c129 == e4614e3ffa5ae0138bbbdf026cb00aa367b8ac67", "stack": null, "subtest": null, "test": "/css/CSS2/box-display/display-008.xht", "line": 11276, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-type-applies-to-001.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-type-applies-to-001.xht", "line": 11464, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-type-applies-to-003.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-type-applies-to-003.xht", "line": 11751, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-applies-to-007.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-applies-to-007.xht", "line": 12021, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-applies-to-001.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-applies-to-001.xht", "line": 12080, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-applies-to-013.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-applies-to-013.xht", "line": 12991, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/box-display/display-009.xht c06f23cc7beb7cdebaf0fc58a2a364e22737c129\n/css/CSS2/box-display/display-008-ref.xht e4614e3ffa5ae0138bbbdf026cb00aa367b8ac67\nTesting c06f23cc7beb7cdebaf0fc58a2a364e22737c129 == e4614e3ffa5ae0138bbbdf026cb00aa367b8ac67", "stack": null, "subtest": null, "test": "/css/CSS2/box-display/display-009.xht", "line": 13173, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/css21-errata/s-11-1-1b-007.html 0d2c1eef4d87313c71d0924f7bb26edbc731e155\n/css/CSS2/css21-errata/s-11-1-1b-007-ref.html 99a3d0e5ce94022300ee65bed0e7242828d96818\nTesting 0d2c1eef4d87313c71d0924f7bb26edbc731e155 == 99a3d0e5ce94022300ee65bed0e7242828d96818", "stack": null, "subtest": null, "test": "/css/CSS2/css21-errata/s-11-1-1b-007.html", "line": 13707, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-type-applies-to-007.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-type-applies-to-007.xht", "line": 14082, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/lists/list-style-type-applies-to-004.xht c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5\n/css/reference/single_square_list_marker.xht 6f94744064a72ccc9622f55b780ab1b7eb5ff71a\nTesting c1aeaf93dff6bf5e656c95bb5c576d3b3cf0fdc5 == 6f94744064a72ccc9622f55b780ab1b7eb5ff71a", "stack": null, "subtest": null, "test": "/css/CSS2/lists/list-style-type-applies-to-004.xht", "line": 14413, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-decoration-applies-to-008.xht 73694126630587710f2de5c2c8a1d6c71defa16b\n/css/reference/pass_if_filler_text_underlined.html d77d9f6dfbba679849a6f16056b6e49f818837ea\nTesting 73694126630587710f2de5c2c8a1d6c71defa16b == d77d9f6dfbba679849a6f16056b6e49f818837ea", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-decoration-applies-to-008.xht", "line": 15405, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-008.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-008.xht", "line": 15828, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-012.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-012.xht", "line": 15899, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-decoration-applies-to-009.xht 73694126630587710f2de5c2c8a1d6c71defa16b\n/css/reference/pass_if_filler_text_underlined.html d77d9f6dfbba679849a6f16056b6e49f818837ea\nTesting 73694126630587710f2de5c2c8a1d6c71defa16b == d77d9f6dfbba679849a6f16056b6e49f818837ea", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-decoration-applies-to-009.xht", "line": 15920, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-011.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-011.xht", "line": 16119, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-decoration-applies-to-006.xht 73694126630587710f2de5c2c8a1d6c71defa16b\n/css/reference/pass_if_filler_text_underlined.html d77d9f6dfbba679849a6f16056b6e49f818837ea\nTesting 73694126630587710f2de5c2c8a1d6c71defa16b == d77d9f6dfbba679849a6f16056b6e49f818837ea", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-decoration-applies-to-006.xht", "line": 16173, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-decoration-applies-to-015.xht 73694126630587710f2de5c2c8a1d6c71defa16b\n/css/reference/pass_if_filler_text_underlined.html d77d9f6dfbba679849a6f16056b6e49f818837ea\nTesting 73694126630587710f2de5c2c8a1d6c71defa16b == d77d9f6dfbba679849a6f16056b6e49f818837ea", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-decoration-applies-to-015.xht", "line": 16302, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-decoration-applies-to-007.xht 73694126630587710f2de5c2c8a1d6c71defa16b\n/css/reference/pass_if_filler_text_underlined.html d77d9f6dfbba679849a6f16056b6e49f818837ea\nTesting 73694126630587710f2de5c2c8a1d6c71defa16b == d77d9f6dfbba679849a6f16056b6e49f818837ea", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-decoration-applies-to-007.xht", "line": 16316, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-decoration-applies-to-014.xht 73694126630587710f2de5c2c8a1d6c71defa16b\n/css/reference/pass_if_filler_text_underlined.html d77d9f6dfbba679849a6f16056b6e49f818837ea\nTesting 73694126630587710f2de5c2c8a1d6c71defa16b == d77d9f6dfbba679849a6f16056b6e49f818837ea", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-decoration-applies-to-014.xht", "line": 16459, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-decoration-applies-to-010.xht 73694126630587710f2de5c2c8a1d6c71defa16b\n/css/reference/pass_if_filler_text_underlined.html d77d9f6dfbba679849a6f16056b6e49f818837ea\nTesting 73694126630587710f2de5c2c8a1d6c71defa16b == d77d9f6dfbba679849a6f16056b6e49f818837ea", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-decoration-applies-to-010.xht", "line": 16471, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-decoration-applies-to-011.xht 73694126630587710f2de5c2c8a1d6c71defa16b\n/css/reference/pass_if_filler_text_underlined.html d77d9f6dfbba679849a6f16056b6e49f818837ea\nTesting 73694126630587710f2de5c2c8a1d6c71defa16b == d77d9f6dfbba679849a6f16056b6e49f818837ea", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-decoration-applies-to-011.xht", "line": 16473, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/white-space-collapsing-bidi-001.xht e37a788329314d819c0ae2764a4e1abc72fe123b\n/css/CSS2/text/white-space-collapsing-bidi-001-ref.xht 7ff1fd5f57a78e5c85b7d5b1dca5c24ad619da3c\nTesting e37a788329314d819c0ae2764a4e1abc72fe123b == 7ff1fd5f57a78e5c85b7d5b1dca5c24ad619da3c", "stack": null, "subtest": null, "test": "/css/CSS2/text/white-space-collapsing-bidi-001.xht", "line": 16476, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-010.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-010.xht", "line": 16521, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-014.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-014.xht", "line": 16620, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-007.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-007.xht", "line": 17015, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-009.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-009.xht", "line": 17220, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/white-space-normal-003.xht 23a49579e31748a59ace14715bdd226cbe0624e2\n/css/CSS2/text/white-space-normal-003-ref.xht acaea871e81d3dc2efb5fee8963ba4dfcaa3794a\nTesting 23a49579e31748a59ace14715bdd226cbe0624e2 == acaea871e81d3dc2efb5fee8963ba4dfcaa3794a", "stack": null, "subtest": null, "test": "/css/CSS2/text/white-space-normal-003.xht", "line": 17428, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-006.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-006.xht", "line": 17561, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-015.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-015.xht", "line": 17643, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/text-transform-applies-to-013.xht df9ed079ac4136698b7c9ad42a200368d275cf43\n/css/reference/pass_if_letter_uppercase.html c0b5f8583b3af093c880f1e462b36433b5e6e9e8\nTesting df9ed079ac4136698b7c9ad42a200368d275cf43 == c0b5f8583b3af093c880f1e462b36433b5e6e9e8", "stack": null, "subtest": null, "test": "/css/CSS2/text/text-transform-applies-to-013.xht", "line": 17823, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/text/white-space-normal-004.xht 0cb28f2e4df5bf932ba7da8ed58bb2a8fa2b2f44\n/css/CSS2/text/white-space-normal-003-ref.xht acaea871e81d3dc2efb5fee8963ba4dfcaa3794a\nTesting 0cb28f2e4df5bf932ba7da8ed58bb2a8fa2b2f44 == acaea871e81d3dc2efb5fee8963ba4dfcaa3794a", "stack": null, "subtest": null, "test": "/css/CSS2/text/white-space-normal-004.xht", "line": 18232, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/box-display/display-011.xht 3eb76b621d364d4ad915f2383a1a6b3a3bceb41f\n/css/CSS2/box-display/display-002-ref.xht 114485495c161f1b25a9facbd62bbd5bafd91f4a\nTesting 3eb76b621d364d4ad915f2383a1a6b3a3bceb41f == 114485495c161f1b25a9facbd62bbd5bafd91f4a", "stack": null, "subtest": null, "test": "/css/CSS2/box-display/display-011.xht", "line": 26137, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/css/CSS2/box-display/containing-block-030.xht 165e3ff31f8f22927ea07f94d8fb36ca83603371\n/css/CSS2/box-display/containing-block-030-ref.xht 15c0948a2bf33940e31285c37380966be02fb6e5\nTesting 165e3ff31f8f22927ea07f94d8fb36ca83603371 == 15c0948a2bf33940e31285c37380966be02fb6e5", "stack": null, "subtest": null, "test": "/css/CSS2/box-display/containing-block-030.xht", "line": 27102, "action": "test_result", "expected": "PASS"}
{"status": "ERROR", "group": "default", "message": "subtle is undefined", "stack": null, "subtest": null, "test": "/WebCryptoAPI/wrapKey_unwrapKey/wrapKey_unwrapKey.https.worker.html", "line": 39147, "action": "test_result", "expected": "OK"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/html/syntax/parsing/html5lib_tests10.html?run_type=uri", "line": 108603, "action": "test_result", "expected": "OK"}
```

**Comment by emilio** [comment]
Table wrappers are a concept well defined in the spec. It's definitely not the same to fiddle with a table wrapper than with a table flow itself. Mind elaborate on the reasoning for the change?

**Comment by KiChjang** [comment]
@emilio It's because of pcwalton's comment [here](https://github.com/servo/servo/issues/16324#issuecomment-296822112) and that the [CSS 3 Table spec](https://www.w3.org/TR/css-tables-3/#table-wrapper-box) says that the only purpose of a table wrapper is to calculate the table captions that the table may own.

**Comment by KiChjang** [comment]
Given the test failures, I have half a mind to just rewrite this according to CSS Table 3 spec first, before getting this merged.

**Comment by KiChjang** [comment]
Closing this while I figure out what the best way forward is.

**Pull request closed without merging**
