### PR TITLE
Tidy can now check for version conflicts...

### LINKED ISSUE #7133: `make tidy` should ensure that we do not have two versions of the same package in Cargo.lock
While permitted by Cargo, it's always an error in Servo to have multiple versions of the same package. `make tidy` should check each of the Cargo.lock files to ensure that no dependency is included twice at different versions.

### PR DESCRIPTION
**Pull request by ghost**
fixes #7133

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7438)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
While this sort of fixes what the issue suggests, the suggestions are quite unhelpful.

screenshot

For now, glutin demands "gl_generator 0.0.26" and hence, that command shouldn't have any effect for that. So, we gotta wait until glutin updates its Cargo.toml. Then, we shall include the function [here](https://github.com/servo/servo/blob/cac20df2a56da7d533780622edb50346e4bb662e/python/tidy.py#L429)

**Comment by mbrubeck** [comment]
Maybe it should just print which packages depend on the older version, if it has that information?  Frequently the solution is to upgrade that intermediate package, or submit a patch to it.

**Comment by Wafflespeanut** [comment]
Update based on @mbrubeck's suggestion...

screenshot

Again, this doesn't work yet! We have to include `check_lock` in the [checking_functions](https://github.com/Wafflespeanut/servo/blob/ed6bfa168288e62708372efa08d6433cfbd36cb8/python/tidy.py#L431)

**Comment by Wafflespeanut** [comment]
Update based on @mbrubeck's suggestion (/cc @larsbergstrom)...

screenshot

Again, this doesn't work yet! We have to include `check_lock` in the [checking_functions](https://github.com/Wafflespeanut/servo/blob/ed6bfa168288e62708372efa08d6433cfbd36cb8/python/tidy.py#L431)

**Comment by larsbergstrom** [comment]
@wafflespeanut This looks fantastic! I'm really excited by this. Is the "expected maximum version" the largest number seen so far? So, if you had three versions of gl_generator at 0.0.24, 0.0.26, and 0.0.27, there would be two errors for the 0.0.24 and 0.0.26?

In any case, I'm really happy with how this is coming out for preventing multiple conflicting packages from being brought in. cc @alexcrichton to show him the awesome.

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7438)

**Comment by Wafflespeanut** [comment]
Thanks. And yeah, there would be two errors on 0.0.24 and 0.0.26 :)

**Comment by metajack** [comment]
So what's needed to land this?

Also, so happy to see this!

**Comment by jdm** [comment]
I'm hestitant to merge this code without it actually being called anywhere. Maybe we could just exceptions for the current cases that are broken and forbid any new ones from being added?

**Comment by Wafflespeanut** [comment]
Done! :)

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by Wafflespeanut** [comment]
Thank you! :)

**Pull request merged**
