### PR TITLE
Implement HTMLTableElement#createTBody

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7089)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you for your PR.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmltableelement.rs, line 92 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7089#-JwBkrWMdcwoL2lvFML3)** ([raw file](https://github.com/servo/servo/blob/a82f87580d9db2d42e8181efbfcf801e6f4c155f/components/script/dom/htmltableelement.rs#L92)):</sup>
Feel free to make this return `HTMLTableSectionElement`, even though that's not what the spec says.

---

<sup>**[components/script/dom/htmltableelement.rs, line 101 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7089#-JwBl1haFWpTY15mf80m)** ([raw file](https://github.com/servo/servo/blob/a82f87580d9db2d42e8181efbfcf801e6f4c155f/components/script/dom/htmltableelement.rs#L101)):</sup>
Indentation is weird; maybe brace the closure.

---

<sup>**[components/script/dom/htmltableelement.rs, line 103 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7089#-JwBk9L97T27_Uj9-Orh)** ([raw file](https://github.com/servo/servo/blob/a82f87580d9db2d42e8181efbfcf801e6f4c155f/components/script/dom/htmltableelement.rs#L103)):</sup>
Maybe use `and_then`.

---

<sup>**[components/script/dom/htmltableelement.rs, line 106 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7089#-JwBkUBz513vqgj_sj6N)** ([raw file](https://github.com/servo/servo/blob/a82f87580d9db2d42e8181efbfcf801e6f4c155f/components/script/dom/htmltableelement.rs#L106)):</sup>
Just `r()` (on `RootedReference`).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7089)

**Comment by dzbarsky** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/htmltableelement.rs, line 106 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7089#-JwBkUBz513vqgj_sj6N)** ([raw file](https://github.com/servo/servo/blob/a82f87580d9db2d42e8181efbfcf801e6f4c155f/components/script/dom/htmltableelement.rs#L106)):</sup>
Oh I thought that was gone after smup. Looks like it's back or something.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7089)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-awaiting-merge 

@bors-servo r+

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7089)

**Comment by Ms2ger** [comment]
```
/html/dom/interfaces.html
-------------------------
PASS expected FAIL HTMLTableElement interface: operation createTBody()
PASS expected FAIL HTMLTableElement interface: document.createElement("table") must inherit property "createTBody" with the proper type (10)
```

**Pull request merged**
