### PR TITLE
Fix HTMLMediaElement seek race condition

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

This depends on https://github.com/servo/media/pull/289 and it's blocked by the servo-media update issue mentioned [here](https://github.com/servo/servo/pull/23842#issuecomment-515007529)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23853)

### CODE REVIEW

**Comment by ferjm** [comment]
@SimonSapin does the last commit ignoring the duplicated url crate and a couple of its dependencies look ok to you?

**Comment by ceyusa** [comment]
r+

**Pull request merged**
