### PR TITLE
Update WR (reduce GPU allocations for render targets)

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18669)

### CODE REVIEW

**Comment by jdm** [comment]
r=me

**Comment by glennw** [comment]
There is one test failure here. A change in the latest update to reduce the size of allocated render targets exposes an unrelated issue regarding snapping of composite / blend primitives. I opened a WR issue for this https://github.com/servo/webrender/issues/1776 and marked the test as failing, for now.

r? @jdm with that change?

**Comment by emilio** [comment]
Looks reasonable, as long as the intention is to fix it :)

@bors-servo r+

**Comment by glennw** [comment]
We reverted the change in WR causing that test failure, for other reasons. So this is a normal WR update now, with various fixes for clips.

@bors-servo r=jdm,emilio

**Comment by jdm** [comment]
```
  ▶ CRASH [expected PASS] /css21_dev/html4/inline-formatting-context-015.htm

  ▶ CRASH [expected PASS] /css21_dev/html4/inline-formatting-context-013.htm

  ▶ CRASH [expected PASS] /css21_dev/html4/inline-formatting-context-011.htm
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 17.2.0-devel
  └ Shutting down the Constellation after generating an output file or exit flag specified

  ▶ CRASH [expected PASS] /css21_dev/html4/inline-formatting-context-022.htm
```

**Comment by glennw** [comment]
@bors-servo retry
 * I can't reproduce this locally, and the logs have no backtraces that I can see. Let's see if it's intermittent.

**Pull request merged**
