### PR TITLE
Update webxr

### PR DESCRIPTION
**Pull request by Manishearth**
Brings in hand input

### CODE REVIEW

**Comment by CYBAI** [comment]
```
Checking files for tidiness...
./Cargo.lock:1: duplicate versions for package `libloading`
	The following packages depend on version 0.5.2 from 'crates.io':
	The following packages depend on version 0.6.1 from 'crates.io':
Running the dependency licensing lint...
```

**Comment by Manishearth** [comment]
Hmmm. I'm okay with allowing that, but i can also undo the dep bump in the patch (it's a proactive dep bump and not strictly required). We'll have to redo it when we switch back to openxrs master. Thoughts?

**Review by asajeffrey — APPROVED** [review]
Oh that's annoying re libloading. You can r=me anyway.

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Pull request merged**
