### PR TITLE
Fix #5495

### LINKED ISSUE #5495: console.log should print all its arguments
There's no spec, but I think it's what [all other browsers do](https://developer.mozilla.org/en-US/docs/Web/API/Console/log).

### PR DESCRIPTION
**Pull request by cuzbog**
This adds support for multiple message in the console, fixes #5495

### CODE REVIEW

**Comment by Manishearth** [comment]
Thanks!

**Comment by boghison** [comment]
No problem! :)

**Comment by Manishearth** [comment]
Rolled up into #5519 because of CI brokenness

**Comment by Ms2ger** [comment]
Rebased as https://github.com/servo/servo/pull/5522

**Pull request closed without merging**
