### PR TITLE
[WIP] Update WR (various optimizations, color image support).

### PR DESCRIPTION
**Pull request by gw3583**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21412)

### CODE REVIEW

**Comment by gw3583** [comment]
This contains the minimal API changes on WR master for the next Servo update.

The current state is that it fails tidy (log below) and crashes on startup (I think due to the different ipc-channel versions that are present).

Nonetheless, it might be a useful starting point for working out what dependencies need to be updated. 

```
Checking the config file...
Checking the wpt manifest file...
Checking directories for correct file extensions...
Checking files for tidiness...
./Cargo.lock:1: duplicate versions for package `ipc-channel`
        The following packages depend on version 0.10.0 from 'crates.io':
                bluetooth
                bluetooth_traits
                canvas
                canvas_traits
                compositing
                constellation
                devtools
                devtools_traits
                embedder_traits
                gfx
                layout
                layout_thread
                layout_traits
                libservo
                metrics
                metrics_tests
                net
                net_traits
                profile
                profile_tests
                profile_traits
                script
                script_layout_interface
                script_traits
                webdriver_server
                webvr
                webvr_traits
        The following packages depend on version 0.11.0 from 'crates.io':
                webrender_api
./Cargo.lock:1: duplicate versions for package `crossbeam-epoch`
        The following packages depend on version 0.3.1 from 'crates.io':
                crossbeam-deque
        The following packages depend on version 0.5.2 from 'crates.io':
                crossbeam-channel
./Cargo.lock:1: duplicate versions for package `crossbeam-utils`
        The following packages depend on version 0.2.2 from 'crates.io':
                crossbeam-deque
                crossbeam-epoch
        The following packages depend on version 0.5.0 from 'crates.io':
                crossbeam-channel
                crossbeam-epoch
./Cargo.lock:1: Package crossbeam-channel 0.2.4 depends on blocked package rand.
  Progress: 100% (2/2)
```

**Comment by jdm** [comment]
All of those duplicates come from https://github.com/servo/ipc-channel/pull/183 and the new version of ipc-channel. #21325 is in the process of being negotiated to address that.

**Comment by pyfisch** [comment]
See also #21725

**Comment by jdm** [comment]
This is happening in #21725.

**Pull request closed without merging**
