### PR TITLE
Update servo-media

### PR DESCRIPTION
**Pull request by Manishearth**
Ensuring the gl failures in https://github.com/servo/servo/pull/23377 are not caused by this

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23416)

### CODE REVIEW

**Comment by Manishearth** [comment]
Hm

**Comment by CYBAI** [comment]
@bors-servo retry

- `[Errno 104] Connection reset by peer` in arm builds
- in `macOS x64: WPT chunk 6 / 6 + extra`
```
  ▶ FAIL [expected PASS] /css/css-flexbox/flexbox_flex-N-N-auto-shrink.html
  └   → /css/css-flexbox/flexbox_flex-N-N-auto-shrink.html 940369d01c9675121e9f79a5b3d541d3e322de04
/css/css-flexbox/flexbox_flex-N-N-auto-shrink-ref.html 76a565523e314736722897ae5f33d39fb14d4d6d
```

**Pull request merged**
