### PR TITLE
Move `ParseErrorReporter` from `msg` to `style`

### LINKED ISSUE #9246: Move ParseErrorReporter to style.
It's defined in `msg` but only used by `style`, `script`, and `layout`. It belongs in `style`.

Code: `components/msg/lib.rs`, `components/style/parser.rs`.

### PR DESCRIPTION
**Pull request by apopiak**
close #9246

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9254)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@bors-servo r+

Thank you!

**Comment by bholley** [comment]
I've got a PR in #9261 that subsumes this one, and also entirely removes the msg dependency entirely. Can we just land that directly?

**Comment by bholley** [comment]
@apopiak - Really sorry that we collided here! Just some missed communication which we'll try to do better in the future. :\

This patch is really well-done, and so I really hope you keep hacking on Servo and helping to make it awesome. :-)

**Comment by bholley** [comment]
Closed via #9261.

**Pull request closed without merging**
