### PR TITLE
Parallel layout optimizations

### PR DESCRIPTION
**Pull request by mbrubeck**
This takes some of the optimizations made to parallel styling in #16971 and applies them to parallel layout.  Specifically:

* Reduce the chunk size, to increase chances for parallelism on trees with small fan-out.
* Reduce allocations by using SmallVec.
* Reduce task switching by processing up to one chunk of children within the same rayon task as the parent.

This cuts the "Primary Layout Pass" time in **half** on the MySpace page from [tp5n], and on my other real-world test pages it is a small improvement or close to no change.

[tp5n]: https://wiki.mozilla.org/Buildbot/Talos/Tests#tp5n_pages_set

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because they affect performance only

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17192)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
IIRC we moved from 16 to 64 originally because 16 murdered the CPU and was really poor performance on mobile?

**Comment by mbrubeck** [comment]
> IIRC we moved from 16 to 64 originally because 16 murdered the CPU and was really poor performance on mobile?

We switched in #6347 from chunks of 1 to chunks of 64 to improve performance on ARM.

It's true, the smaller chunk size in this PR can increase the number of tasks in some cases.  On the other hand, the "process first chunk on the same task" optimization can *reduce* the number of tasks—by a large factor in some cases (deep trees with low fan-out).

**Comment by mbrubeck** [comment]
One significant change from #16971 is not included in this PR:  Parallel layout still processes all nodes at one level of the tree before spawning any tasks to process their children, and coalesces all of the children at each level into the same work units.

In contrast, #16971 changed parallel style to spawn tasks for each node's children separately, as soon as that node was processed.  According to [bug 1366347](https://bugzilla.mozilla.org/show_bug.cgi?id=1366347#c0) this was the most important change for MySpace.  If it has similar effects in parallel layout, there may be more gains to be found here.

**Comment by mbrubeck** [comment]
> #16971 changed parallel style to spawn tasks for each node's children separately

I made this change to parallel layout locally, and it didn't improve performance measurably for my test cases, so it might not be worth the added code.  Layout doesn't have anything like the style sharing cache that requires us to try to group nodes by their parent.

**Comment by pcwalton** [comment]
At this point I'm inclined to take ARMv8 as our baseline for parallel layout, because it has much better multicore synchronization support. All my measures were on ARMv7, so we'd need to redo those.

**Comment by pcwalton** [comment]
@bors-servo: r+

Did this make parallel layout faster than sequential on that page?

**Comment by larsbergstrom** [comment]
cc @rzambre for re-testing when you do the Android perf runs :-)

**Pull request merged**
