### PR TITLE
net/storage_task.rs: Fix remove_item

### LINKED ISSUE #5548: StorageManager panicking on slashdot.org
```
$ ./mach run http://slashdot.org/       
ERROR:js::rust: Error at http://slashdot.org/:25: ReferenceError: $ is not defined

thread 'StorageManager' panicked at 'called `Option::unwrap()` on a `None` value', /Users/larsberg/rust/src/libcore/option.rs:362
stack backtrace:
   1:        0x1073d6ded - sys::backtrace::write::h22d7886ea3e34df8JDA
   2:        0x1073eae6d - panicking::on_panic::hcde1662b6a2f62e2LsJ
   3:        0x1073b71a9 - rt::unwind::begin_unwind_inner::hc0862f0ae0b66b7chbJ
   4:        0x1073b762e - rt::unwind::begin_unwind_fmt::hce9ab1c081fbc798S9I
   5:        0x1073ea6fd - rust_begin_unwind
   6:        0x10740d3b5 - panicking::panic_fmt::hc7d3b6a3960519fdHZs
   7:        0x10740ca87 - panicking::panic::h4158d1652bbc7938TXs
   8:        0x10606eda5 - option::Option<T>::unwrap::h3301369630804163101
   9:        0x10618fada - storage_task::StorageManager::remove_item::hb6ac0603fe5c82eeuYf
  10:        0x106187ea7 - storage_task::StorageManager::start::h51a40ea5d5e9d37fORf
  11:        0x1061877ef - storage_task::StorageTask.StorageTaskFactory::new::closure.26606
  12:        0x10618771e - task::spawn_named::closure.26602
  13:        0x10618766e - thunk::Thunk<'a, (), R>::new::closure.26599
  14:        0x1061875ae - thunk::F.Invoke<A, R>::invoke::h8712563139474070488
  15:        0x106066dc0 - thunk::Thunk<'a, A, R>::invoke::h12771924919246353326
  16:        0x106067b29 - thread::Builder::spawn_inner::closure.16154
  17:        0x106067aae - rt::unwind::try::try_fn::__rust_abi::h8243538247422857478
  18:        0x106067a49 - rt::unwind::try::try_fn::h8243538247422857478
  19:        0x1073eceb8 - rust_try_inner
  20:        0x1073ecea5 - rust_try
  21:        0x106066f0b - rt::unwind::try::h1185134201880303421
  22:        0x106065acc - thread::Builder::spawn_inner::closure.16004
  23:        0x106068b67 - thunk::Thunk<'a, (), R>::new::closure.16172
  24:        0x106068a5c - thunk::F.Invoke<A, R>::invoke::h4236836237872994162
  25:        0x1073d9ce2 - sys::thread::thread_start::hc1f580397175540a22E
  26:     0x7fff8a2d6267 - _pthread_body
  27:     0x7fff8a2d61e4 - _pthread_start
```

Error can be replicated in this branch https://github.com/servo/servo/pull/5543.
You can find more information about it below https://github.com/servo/servo/issues/5504#issuecomment-90166616

### PR DESCRIPTION
**Pull request by ghost**
Use `and_then` and remove `unwrap` instead of using a `map` as described in https://github.com/servo/servo/issues/5548#issuecomment-90254644.

Fixes #5548

### CODE REVIEW

**Comment by jdm** [comment]
@jagtalon Could you add a content test for this in tests/content?

**Comment by jagtalon** [comment]
@jdm sure thing!

**Comment by jagtalon** [comment]
@jdm I'm having a bit of trouble with the test--do I find exactly what is causing the StorageManager and put it in the test or do I save the whole of Slashdot / GotG in the repo?

**Comment by jagtalon** [comment]
Oh I understand what's causing it now. Looks like it's localStorage. Will make the test that just has that.

**Comment by jagtalon** [comment]
@jdm this seems to work--tell me what you think!

**Comment by jdm** [comment]
Looks great!

**Pull request merged**
