### PR TITLE
Issue5600 ignore bom of textencoder

### PR DESCRIPTION
**Pull request by yodalee**
issue #5600
I use a bool to represent the ignoreBOM flag.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5615)

### CODE REVIEW

**Comment by jdm** [comment]
I think we should implement the functionality described in step 2.2 of https://encoding.spec.whatwg.org/#concept-td-serialize at the same time.

**Comment by yodalee** [comment]
My fault OwO

**Comment by yodalee** [comment]
Wait, where does this `serialized stream algorithm` take place? It should talk about a function or something, but it doesn't describe the function in spec.

**Comment by jdm** [comment]
It's referred to by step 5.2 and 5.3.2 ("serialized") from https://encoding.spec.whatwg.org/#dom-textdecoder-decode .

**Comment by yodalee** [comment]
I'm curious what should we use to represent a `stream` in the spec. It seems `Vec<u8>` may meet the  requirement, but facing the input encoded with utf16, it may not a good choice.

**Comment by jdm** [comment]
I think the `&[u8]` slice that we construct fills the role of the stream.

**Comment by yodalee** [comment]
I try to implement a serialize function, but not sure whether I do it correct or not OAO.

**Comment by jdm** [comment]
That does look like it implements the algorithm described in https://encoding.spec.whatwg.org/#concept-td-serialize . However, I think we can simplify it by taking an `&[u8]` argument and returning `&[u8]`, since all the BOM-skipping code does it skip some leading characters from the buffer (and we could then call this from Decode). Does that make sense?

**Comment by yodalee** [comment]
You mean just take the &[u8] and directly modify to it?
```
fn serialize(self, stream: &[u8]) -> &[u8] {
for char in stream {
  // check is character is skip, remove them from stream.
}
return stream;
```

**Comment by yodalee** [comment]
I have to admit I don't know how to write in `&[u8] -> &[u8]`, I think my brain is not rusty enough OAO

**Comment by jdm** [comment]
Maybe http://doc.servo.org/collections/primitive.slice.html will help? Slices can be re-sliced to return a subsection of the original slice.

**Comment by jdm** [comment]
We could probably also just use iterators like skip_while: http://doc.servo.org/core/iter/trait.IteratorExt.html#method.skip_while

**Comment by yodalee** [comment]
This is really funny. Can we simply write this?
```
fn serialize(self, stream: &[u8]) -> &[u8] {
  match self.encoding.name() {
    "utf-8" | "utf-16be" | "utf-16le" if (!self.ignoreBOM && !self.BOMseen) => {
      self.BOMseen = true;
      stream.slice_from(1)
  },
  _ => stream

**Comment by yodalee** [comment]
Something like this:
https://gist.github.com/yodalee/4b5d3ee4bf7fe8145464

**Comment by jdm** [comment]
Yes, that looks like it would accomplish the goal. My one main concern is that we're comparing a u8 against a u16 value, which will never be true - I'm not sure why Rust isn't complaining about that.

**Comment by yodalee** [comment]
During my build it give a warning that condition never happen. Maybe we need to change stream to `&[u16]`?

**Comment by jdm** [comment]
I would just match against stream.get(0) and stream.get(1).

**Comment by yodalee** [comment]
It reminds me that we should skip 1 character or 2? Since we have match 0 and 1, maybe the return stream should be `&stream[2..]`. I cannot determine this by the spec.

**Comment by jdm** [comment]
Yes, we should skip the whole BOM that we compare against.

**Comment by jdm** [comment]
Hmm, can we call the new serialize method from someplace? :)

**Comment by yodalee** [comment]
You mean from `textdecoder`? or some other place.

**Comment by jdm** [comment]
Yes; the spec in https://encoding.spec.whatwg.org/#dom-textdecoder-decode refers to "return output, serialized" which links to the serialize algorithm.

**Comment by yodalee** [comment]
I implement partial of decode function. I wanna ask that:
* In step 1: what does the `new encoding` in `set decoder to a new encoding's decoder` come from? Based on the input string or something else?
* Also in step 1. What is the stream in `set stream to a new stream` means. In current status, we didn't implement the `stream` that associate to `TextDecoder`. Should I add one?
* In step 5: I think this can be implemented as: if stream length is zero and streaming flag is set, then return empty string. Otherwise try to decode the stream and return the result if there is no error.
* There are some question in this commit, the self in `impl TextDecoderMethods` is not mutable. So the implementation to modify `self.BOMSeen = false` won't work Orz.

**Comment by yodalee** [comment]
I will close this and transfer to @Shinglyu

**Comment by jdm** [comment]
* Yes.
* I don't think we need any special concept of a stream right now. We already have a buffer gets decoded.
* I agree.
* The bom_seen field should be a `Cell<bool>`; we can't directly mutate field values without using a wrapper like Cell or RefCell.

I apologize for not responding sooner!
*

**Pull request closed without merging**
