### PR TITLE
Support WebDriver takeScreenshot command.

### PR DESCRIPTION
**Pull request by jgraham**
This adds support for compositing to a PNG without actually quiting
the browser.

Cargo bits need to be updated after the upstream changes to rust-png land.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5884)

### CODE REVIEW

**Comment by jdm** [comment]
Reviewed files:
- components/compositing/compositor.rs @ r1
- components/compositing/compositor_task.rs @ r1
- components/compositing/constellation.rs @ r1
- components/compositing/headless.rs @ r1
- components/msg/Cargo.toml @ r1
- components/msg/constellation_msg.rs @ r1
- components/msg/lib.rs @ r1
- components/script/script_task.rs @ r1
- components/servo/Cargo.lock @ r1
- components/webdriver_server/Cargo.toml @ r1
- components/webdriver_server/lib.rs @ r1

---

<sup>**[components/compositing/compositor.rs, line 191 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGP2_k9qLsIdAPh71e)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/compositing/compositor.rs#L191)):</sup>
This option deserves documentation, so we should probably document the others and the overall type as well.

---

<sup>**[components/compositing/compositor.rs, line 1148 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGP_5h7F_lFZ1ZuvEw)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/compositing/compositor.rs#L1148)):</sup>
Would it make more sense to take an `Option<Sender<png::Image>>` argument instead of having all of these `return None` branches?

---

<sup>**[components/compositing/compositor.rs, line 1219 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGQ6lxLw1N1Y74pKBV)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/compositing/compositor.rs#L1219)):</sup>
This can just be a free function, and I think that will be clearer too.

---

<sup>**[components/compositing/compositor_task.rs, line 221 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGQP5p4Gek58i1KvX6)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/compositing/compositor_task.rs#L221)):</sup>
This is very zen.

---

<sup>**[components/msg/constellation_msg.rs, line 238 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGRBGU-vaQz2X_ZClK)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/msg/constellation_msg.rs#L238)):</sup>
/// for docs (and the one above

---

<sup>**[components/webdriver_server/lib.rs, line 11 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGRQMBujj_LVJ_4a-J)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/webdriver_server/lib.rs#L11)):</sup>
I believe this is gone in the Rust upgrade that is coming down the pipes. I'd like to find a different solution.

---

<sup>**[components/webdriver_server/lib.rs, line 47 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGRsLvMsF7gbnwpAHM)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/webdriver_server/lib.rs#L47)):</sup>
std::thread::sleep_ms?

---

<sup>**[components/webdriver_server/lib.rs, line 161 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGSe8D65M9x_XnhoVs)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/webdriver_server/lib.rs#L161)):</sup>
for _ in &[0..iterations] {

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5884)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes +S-needs-rebase 

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5884)

**Comment by jgraham** [comment]
<sup>**[components/compositing/compositor.rs, line 1148 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGP_5h7F_lFZ1ZuvEw)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/compositing/compositor.rs#L1148)):</sup>
I sort of felt like this was a better separation of concerns because it doesn't bake sending the PNG over a channel into this function. But I can do it the other way if you prefer.

---

<sup>**[components/webdriver_server/lib.rs, line 11 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5884#-JoGRQMBujj_LVJ_4a-J)** ([raw file](https://github.com/servo/servo/blob/0bb69db080cc766879a29b61e0f1a2b050a79f32/components/webdriver_server/lib.rs#L11)):</sup>
Yeah it is; after the rustup I can use std::thread::sleep_ms as you point out below. But afaict from the docs, that doesn't exist in the current version of rustc. Although, perhaps I should verify that rather than trusting them.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5884)

**Comment by jdm** [comment]
Reviewable is confusing me but I have marked those two as addressed, based on your feedback.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5884)

**Comment by jdm** [comment]
-S-needs-rebase -S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/compositing/compositor.rs @ r2
- components/compositing/compositor_task.rs @ r2
- components/compositing/constellation.rs @ r2
- components/compositing/headless.rs @ r2
- components/msg/constellation_msg.rs @ r2
- components/script/script_task.rs @ r2
- components/servo/Cargo.lock @ r2
- components/webdriver_server/lib.rs @ r2

---

<sup>**[components/webdriver_server/lib.rs, line 166 \[r2\]](https://reviewable.io:443/reviews/servo/servo/5884#-JobmIJrZQWrlWtp7m78)** ([raw file](https://github.com/servo/servo/blob/93acf659b13c208e1df21e38fd4f02e6bc16900d/components/webdriver_server/lib.rs#L166)):</sup>
interval?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5884)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 

---

Reviewed files:
- components/compositing/compositor.rs @ r3
- components/compositing/compositor_task.rs @ r3
- components/compositing/constellation.rs @ r3
- components/msg/constellation_msg.rs @ r3
- components/script/script_task.rs @ r3
- components/servo/Cargo.lock @ r3
- components/webdriver_server/Cargo.toml @ r3
- components/webdriver_server/lib.rs @ r3

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5884)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review -S-needs-rebase -S-needs-squash 

---

Reviewed files:
- components/compositing/compositor.rs @ r4
- components/compositing/compositor_task.rs @ r4
- components/compositing/constellation.rs @ r4
- components/compositing/headless.rs @ r4
- components/msg/constellation_msg.rs @ r4
- components/msg/lib.rs @ r4
- components/script/script_task.rs @ r4
- components/servo/Cargo.lock @ r4
- components/webdriver_server/lib.rs @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5884)

**Pull request merged**
