### PR TITLE
Implement the HTML background attribute

### LINKED ISSUE #5835: Support background attribute on body element
http://www2.warnerbros.com/spacejam/movie/jam.htm

This requires special handling in synthesize_presentational_hints_for_legacy_attributes .

### PR DESCRIPTION
**Pull request by evilpie**
Fixes #5835

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5851)

### CODE REVIEW

**Comment by evilpie** [comment]
I doubt you will merge it like that. get_background should probably be moved from HTMLBodyElementHelpers to something that is layout specific. If there was some way to get the document base inside legacy.rs everything would be a lot easier.

**Comment by SimonSapin** [comment]
<sup>**[components/script/dom/htmlbodyelement.rs, line 86 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5851#-Jnw2fl-ZV4rMAAjLHXq)** ([raw file](https://github.com/servo/servo/blob/3ab2a077495c6961e81a5ab7e9b1d63f532e2811/components/script/dom/htmlbodyelement.rs#L86)):</sup>
Can this `.clone()` be avoided? Maybe the method would have to return `std::cell::Ref<Option<Url>>`.

---

<sup>**[components/script/dom/htmlbodyelement.rs, line 135 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5851#-JnvsUMIUzmaV80addjs)** ([raw file](https://github.com/servo/servo/blob/3ab2a077495c6961e81a5ab7e9b1d63f532e2811/components/script/dom/htmlbodyelement.rs#L135)):</sup>
Use `.ok()` to get an `Option` from a `Result`.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5851)

**Comment by SimonSapin** [comment]
@Ms2ger, what do you think is the right way to access an element’s base URL from `legacy.rs`?

**Comment by Ms2ger** [comment]
There shouldn't be anything in `legacy.rs`. We don't support `base`, so I guess `document_from_node(element).url()` or something like that.

**Comment by waddlesplash** [comment]
@evilpie Any update on this? If you're unable to continue, I might be able to spare some time to complete it...

**Comment by evilpie** [comment]
I am going to continue working on this soon.

**Comment by SimonSapin** [comment]
> There shouldn't be anything in `legacy.rs`.

If I understand correctly, you mean that this should use the new infrastructure for presentational hints where the work happens in `components/script/dom/element.rs` rather than in `legacy.rs`, as in #5988. Is that right?

**Comment by SimonSapin** [comment]
@Ms2ger ↑

**Comment by evilpie** [comment]
Sorry, I am not quite sure how to use Ref<>.

**Comment by evilpie** [comment]
I rebased this again. I still not sure how to use Ref<>.

**Comment by metajack** [comment]
@SimonSapin ping

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlbodyelement.rs, line 102 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5851#-Jnw2fl-ZV4rMAAjLHXq)** ([raw file](https://github.com/servo/servo/blob/3ab2a077495c6961e81a5ab7e9b1d63f532e2811/components/script/dom/htmlbodyelement.rs#L102)):</sup>
On further reading, this is used to create a `BackgroundImage` which wants to own an `Url` anyway, so removing the clone here would only move it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5851)

**Pull request merged**
