### PR TITLE
Update XR code to support null layers and new spec changes

### PR DESCRIPTION
**Pull request by Manishearth**
Last time we landed an incomplete PR (https://github.com/servo/servo/pull/22649) that corrected the promise model but left XR sessions in panicky states.

This updates the code to not panic all the time, and also includes changes from https://github.com/immersive-web/webxr/pull/458

r? @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22699)

### CODE REVIEW

**Comment by Manishearth** [comment]
That was actually https://github.com/servo/servo/issues/22702

r? @jdm

**Comment by Manishearth** [comment]
Done

**Comment by jdm** [comment]
```
Checking files for tidiness...
./resources/prefs.json:None: Unordered key (found dom.webxr.enabled before dom.webvr.event_polling_interval)
./components/script/dom/vrdisplay.rs:777: found an empty line following a {
./components/script/dom/webidls/XRRenderState.webidl:17: no newline at EOF
```

**Comment by jdm** [comment]
r=me with tidy passing.

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo r-
```
./resources/prefs.json:None: Unordered key (found dom.webxr.enabled before dom.webvr.test)
```

**Comment by Manishearth** [comment]
@bors-servo retry

max run time exceeded on WPT

**Pull request merged**
