### PR TITLE
Add -moz-user-* CSS longhands for Gecko

### PR DESCRIPTION
**Pull request by KiChjang**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy --faster` does not report any errors
- [x] These changes do not require tests because stylo

r? @bholley

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11222)

### CODE REVIEW

**Comment by metajack** [comment]
Why are we implementing these in Servo?

**Comment by KiChjang** [comment]
This is for stylo, which produces the CSS properties for Gecko. I have explicitly marked these properties to only be produced when building geckolib.

**Comment by metajack** [comment]
Is there a bug with @highfive? It shows that you modified script and profile, but GitHub shows only things in style. I suspected it was for stylo, but asked when I saw it made changes outside of style.

cc @jdm

**Comment by KiChjang** [comment]
No, it was because I messed up the first git commit when I first opened this PR. I accidentally amended the master branch commit from where I branched off.

**Comment by metajack** [comment]
Ah, thanks for the explanation, and sorry for the noise!

**Comment by KiChjang** [comment]
No worries! It's better to be certain of what's happening here than accidentally polluting the commit history.

**Comment by bholley** [comment]
Awesome, thank you! @bors-servo r+

**Comment by frivoal** [comment]
Hi, I am the editor of the [CSS-UI-4 specification](https://drafts.csswg.org/css-ui-4/), which defines user-select.
If I understand correctly, this patch is only at the syntax level, and only for use within Gecko, not for Servo, right? If yes, I suppose all is good.

If you do plan on using this in servo, I would suggest:

* implementing user-select according to [the spec](https://drafts.csswg.org/css-ui-4/#content-selection), and reporting back if you think there's anything wrong with it. It is meant both to be sane (when possible) and take web compat into account.

* Implementing it directly unprefixed (for sanity) and -webkit- prefixed (for web compat). Don't -servo- prefix it (because why would you), and don't -moz- prefix it, unless you find that to be necessary for web compat, in which case I would love to hear about it and put it into the spec

* Not implementing the other properties (-moz-user-input, -moz-user-modify, -moz-user-focus) unless you have evidence that there's a web compat need for them, and if you do find that, reporting to the CSSWG with some details about that compat need would be very much appreciated.

**Comment by bholley** [comment]
Thanks! Yeah this stuff is all gecko-only as we try to hook Servo's style system up to Gecko and make it pass the test suite.

At some point in the future, we will go through the list of gecko-only properties, and determine which ones are necessary for web-compatibility. But that's a ways out at the moment. :-)

**Pull request merged**
