### PR TITLE
Update html5ever to 0.8

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13813)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo p=100

I have a pile of things blocked on this.

**Comment by KiChjang** [comment]
```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'assertion failed: bpos.to_usize() >= mbc.pos.to_usize() + mbc.bytes', ../src/libsyntax/codemap.rs:707
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Could not compile `servo`.
```
Rust ICE. Fun!

**Comment by SimonSapin** [comment]
This ICE is fixed in today’s nightly, rustup coming up.

**Comment by SimonSapin** [comment]
Rebased on top of rustup https://github.com/servo/servo/compare/h5eup

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13813#-:-KVdcWtCD5w1kyUxgWg7:bkg9nno)*

**Pull request merged**
