### PR TITLE
added missing dom nodes to match arm

### PR DESCRIPTION
**Pull request by creativcoder**
Added mentioned dom nodes to match arm. Please review PR.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8017)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Since this is going to cause tests to pass (that we previously expected to fail), you're going to need to update the test expectations for this. https://github.com/servo/servo/tree/master/tests/wpt#updating-test-expectations

Long story short:

```
./mach build --release
./mach test-wpt --release --log-raw /tmp/servo.log
./mach update-wpt /tmp/servo.log
```

The last command will cause a new git commit to be created with the updated expectations

**Comment by frewsxcv** [comment]
Also, in the future, can you comment on the GitHub issue you're going to work on to prevent multiple people from claiming the same issue? Thanks

https://github.com/servo/servo/issues/7995

**Comment by nox** [comment]
@creativcoder Ping?

**Comment by creativcoder** [comment]
@nox Hi, am unable to do ./mach build . The initial dependencies for mach build like llvm, is taking a lot of time to download. I live in a remote location, so network's kind of bad here.

**Comment by jdm** [comment]
Ok! We'll let someone else give the original issue a try, in that case. Thanks for your efforts!

**Pull request closed without merging**
