### PR TITLE
Update our implementation of DOMTokenList

### PR DESCRIPTION
**Pull request by ngsankha**
#8511

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8525)

### CODE REVIEW

**Comment by nox** [comment]
Thanks for your contribution. You don't seem to have fixed the serialisation, am I wrong?

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/script/dom/domtokenlist.rs, line 142 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8525#-K3EQQWvr8sMQylchNtc)** ([raw file](https://github.com/servo/servo/blob/20a655740daa1ae52a7ad20c4f12b85fdbcccc4a/components/script/dom/domtokenlist.rs#L142)):</sup>
You should use `attribute()` and work on its `AttrValue`, instead of using `get_tokenlist_attribute()` and `set_atomic_tokenlist_attribute()`.

I don't see the code for the validation steps in step 3.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8525)

**Comment by nox** [comment]
@sankha93 Ping?

**Comment by sankha93** [comment]
@nox Sorry, I was a bit busy. Will get back on this today.

**Comment by nox** [comment]
No problem, just triaging. :)

**Comment by nox** [comment]
@sankha93 Want me to take it over? Not hurried, just checking.

**Comment by nox** [comment]
See #9353.

**Pull request closed without merging**
