### PR TITLE
Read smaps in the memory profiler on Linux

### PR DESCRIPTION
**Pull request by nnethercote**
Here's example -m output after these changesets are applied:

```
_size (MiB)_: _category_
     2798.61: vsize
      136.80: resident
      142.89: resident-according-to-smaps
       97.84: - anonymous (rw-p)
       23.98: - /home/njn/moz/servo/components/servo/target/servo (r-xp)
        6.58: - [heap] (rw-p)
        5.36: - other
        3.51: - /usr/lib/x86_64-linux-gnu/dri/i965_dri.so (r-xp)
        1.33: - /lib/x86_64-linux-gnu/libc-2.19.so (r-xp)
        0.93: - /home/njn/moz/servo/components/servo/target/servo (r--p)
        0.76: - /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20 (r-xp)
        0.74: - /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0 (r-xp)
        0.50: - /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (r-xp)
        0.50: - /lib/x86_64-linux-gnu/libglib-2.0.so.0.4200.1 (r-xp)
        0.45: - /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0 (r-xp)
        0.43: - /lib/x86_64-linux-gnu/libm-2.19.so (r-xp)
       30.85: system-heap-allocated
        4.91: jemalloc-heap-allocated
        6.11: jemalloc-heap-active
      120.00: jemalloc-heap-mapped
```

The `resident-according-to-smaps` line is new, as are all the indented lines beneath it. This is useful particularly because it shows how much memory is taken up by code, e.g. the line ending in `servo (r-xp)` shows that the `servo` executable's code alone takes up 24 MiB of physical memory.

### CODE REVIEW

**Comment by nnethercote** [comment]
I rebased the patch for the rustup (including a changed `regex` dependency) and followed Ms2ger's instructions on IRC to update hoppipolla. Hopefully I didn't mess that up.

**Comment by jdm** [comment]
Everyone played hot potato with this because they didn't know what smaps were, but here we are.

**Comment by nnethercote** [comment]
Thank you for the review. I've pushed a new changeset that addresses the comments. I'd like to squash it with the preceding patch (and fix a typo in the preceding patch's commit log) before it gets merged. Please let me know when I should do that (presumably with a `push -f`?)

**Comment by jdm** [comment]
Yep, go ahead and do those things, along with a rebase. No need to attempt to rebase the Critic review after this.

**Comment by nnethercote** [comment]
Updated changesets are ready for merging.

**Comment by Ms2ger** [comment]
@larsbergstrom: gonk failed, could you figure it out?

**Comment by Ms2ger** [comment]
Oh, I see it. @nnethercote, you'll need to apply the changes to `components/servo/Cargo.lock` to `ports/{cef,gonk}/Cargo.lock` as well.

**Comment by nnethercote** [comment]
I updated the Cargo.lock file. Should be good to go now.

**Comment by larsbergstrom** [comment]
Needs the ports/Gonk/Cargo.lock file, too. Sorry!

**Comment by jdm** [comment]
```
/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.15/src/re.rs:582:58: 582:70 error: wrong number of type arguments: expected 2, found 1 [E0243]
/home/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.15/src/re.rs:582     fn reg_replace<'a>(&'a mut self, caps: &Captures) -> Cow<'a, str>;
                                                                                                                                                ^~~~~~~~~~~~
```

**Comment by jdm** [comment]
Isn't it great when Cargo mysteriously decides to pick up a more recent version of a dependency?

**Comment by nnethercote** [comment]
mbrubeck identified that I'd updated the wrong dependencies lists in the Gonk and CEF Cargo.lock files. Hopefully it's right this time.

**Pull request merged**
