### PR TITLE
Hack workaround for X11 + threading issue.

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5748)

### CODE REVIEW

**Comment by glennw** [comment]
r? @pcwalton or @metajack 

This is far more apparent with the image cache refactor I'm working on - because it issues far fewer paint messages as images load. However, I've verified that it's also occurring on master as well - it's just not as obvious due to how many paint messages back up as images load.

**Comment by pcwalton** [comment]
Is it not fine to use `XInitThreads()` instead? How do we currently call X from multiple threads?

**Comment by glennw** [comment]
We do call XInitThreads already. I think it's more likely an X11 bug rather than something we are doing wrong, but it definitely gets stuck in the paint task upload function often without this hack.

**Comment by pcwalton** [comment]
r=me if you file an issue and link to it the comment.

**Pull request merged**
