### PR TITLE
(WIP) Switch from headers_ext 0.0.4 to headers 0.2.0

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22767)

### CODE REVIEW

**Comment by nox** [comment]
Makes no sense to me that I cannot reproduce those failures locally.

@bors-servo try

**Comment by nox** [comment]
I don't understand why that only fails on Linux and not macOS.

**Comment by jdm** [comment]
I will see if I can reproduce the failure under rr.

**Comment by nox** [comment]
Thanks @jdm!

**Comment by jdm** [comment]
Let's mark this as failing on Linux and move forward.

**Comment by atouchet** [comment]
@jdm was 420a899 merged? Should this be reopened?

**Comment by jdm** [comment]
Filed #23566 to track it.

**Pull request closed without merging**
