### PR TITLE
Fix wrong initial values in various single keyword properties

### PR DESCRIPTION
**Pull request by canova**
In `single_properties` helper, first values set as initial value. But it seems like a problem here because it's not clear to anyone who don't know the working mechanism of this helper or it can be easily forgotten. Maybe we should make it explicit. I was fixing Bug 1331516 but expanded to cover all single keyword properties.

Also discovered that mask-repeat's initial value is [wrong](https://bugzilla.mozilla.org/show_bug.cgi?id=1346193) in gecko.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] This PR started to fix [Bug 1331516](https://bugzilla.mozilla.org/show_bug.cgi?id=1331516) but expanded to cover all single keyword properties afterwards.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15908)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r+

Though I concur we should definitely have a `default="foo"` mechanism instead of relying on this.

**Comment by nox** [comment]
@bors-servo retry

Git weirdness.

**Comment by canaltinova** [comment]
Reverted the mask-position change per https://bugzilla.mozilla.org/show_bug.cgi?id=1346193#c1
@emilio could you r+ again?

**Pull request merged**
