### PR TITLE
Don't try to unwrap the result of requestAnimationFrame callback

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6880)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/window.rs, line 504 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6880#-JvnYml6eHvma6PrJY7o)** ([raw file](https://github.com/servo/servo/blob/43553527b5c2c60e4a832e697c33f0226f3de795/components/script/dom/window.rs#L504)):</sup>
While you're here, this needs an issue.

---

<sup>**[tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html, line 2 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6880#-JvnYtUzcVMz3gnUE7Dg)** ([raw file](https://github.com/servo/servo/blob/43553527b5c2c60e4a832e697c33f0226f3de795/tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html#L2)):</sup>
Add a title

---

<sup>**[tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html, line 9 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6880#-JvnYSzT2GA36kkPHX2Y)** ([raw file](https://github.com/servo/servo/blob/43553527b5c2c60e4a832e697c33f0226f3de795/tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html#L9)):</sup>
I'd like to at least test throwing two exceptions like this; that could trigger SM assertions if we get it wrong.

---

<sup>**[tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html, line 14 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6880#-JvnYPPRfR-n0rNiemeF)** ([raw file](https://github.com/servo/servo/blob/43553527b5c2c60e4a832e697c33f0226f3de795/tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html#L14)):</sup>
There's no such function.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6880)

**Comment by dzbarsky** [comment]
"I'd like to at least test throwing two exceptions like this; that could trigger SM assertions if we get it wrong." - I'm not sure what this means. Are you suggesting calling rAF(function() {throw new Error()}) before throwing the Error? Or testing DOMExceptions?

**Comment by Ms2ger** [comment]
Can you add a test that `window.onerror` is invoked per <http://lists.w3.org/Archives/Public/public-web-perf/2015Aug/0000.html>? Not sure if it'll pass in Servo, but it'd be useful at some point.

---

Reviewed 4 of 4 files at r1.
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/window.rs, line 504 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6880#-JvnYml6eHvma6PrJY7o)** ([raw file](https://github.com/servo/servo/blob/43553527b5c2c60e4a832e697c33f0226f3de795/components/script/dom/window.rs#L504)):</sup>
While you're here, this needs an issue.

---

<sup>**[tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html, line 2 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6880#-JvnYtUzcVMz3gnUE7Dg)** ([raw file](https://github.com/servo/servo/blob/43553527b5c2c60e4a832e697c33f0226f3de795/tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html#L2)):</sup>
Add a title

---

<sup>**[tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html, line 9 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6880#-JvnYSzT2GA36kkPHX2Y)** ([raw file](https://github.com/servo/servo/blob/43553527b5c2c60e4a832e697c33f0226f3de795/tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html#L9)):</sup>
I'd like to at least test throwing two exceptions like this; that could trigger SM assertions if we get it wrong.

---

<sup>**[tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html, line 14 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6880#-JvnYPPRfR-n0rNiemeF)** ([raw file](https://github.com/servo/servo/blob/43553527b5c2c60e4a832e697c33f0226f3de795/tests/wpt/mozilla/tests/mozilla/window_requestAnimationFrame.html#L14)):</sup>
There's no such function.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6880)

**Comment by dzbarsky** [comment]
The test now crashes due to https://github.com/servo/servo/issues/7115, but we should land this to fix the original issue.

**Comment by Ms2ger** [comment]
```
/_mozilla/mozilla/window_requestAnimationFrame.html
---------------------------------------------------
NOTRUN Test throwing an error inside requestAnimationFrame callback
TIMEOUT expected CRASH [Parent]
```

**Comment by dzbarsky** [comment]
@Ms2ger should we just mark that test as timeout on linux? Not sure what to do here

**Comment by Ms2ger** [comment]
I'd like to know why it times out, and it seems to time out on mac too

**Comment by dzbarsky** [comment]
Does it time out? It crashes for me locally.

**Comment by dzbarsky** [comment]
Crash may be fixed by https://github.com/servo/servo/pull/7220

**Comment by dzbarsky** [comment]
When running the test, Servo reports an error on line 9, which causes the timeout.  The issue is that the error is not properly suppressed, but this is better than a crash and we have an issue on file to solve this.

**Comment by jdm** [comment]
@bors-servo: r+
Makes sense to me.

**Pull request merged**
