### PR TITLE
Pass through channel settings in AudioNode constructor

### PR DESCRIPTION
**Pull request by Manishearth**
Most audionodes let you pass in channel count/etc settings in their
constructors, and have different defaults. Using the `create_node`
argument added in https://github.com/servo/media/pull/124 , this passes
that information through.

r? @ferjm.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21674)

### CODE REVIEW

**Review by ferjm — APPROVED** [review]
Looks good. r=me

Thanks!

**Comment by jdm** [comment]
```
Checking files for tidiness...
./Cargo.lock:1:duplicate versions for package `num-rational`
The following packages depend on version 0.1.42 from 'crates.io':
		image
The following packages depend on version 0.2.1 from 'crates.io':
		gstreamer
./Cargo.lock:1:duplicate versions for package `byte-slice-cast`
The following packages depend on version 0.1.0 from 'crates.io':
		servo-media-audio
The following packages depend on version 0.2.0 from 'crates.io':
		servo-media-gstreamer
./components/script/dom/audiodestinationnode.rs:9:use statement is not in alphabetical order
expected: dom::bindings::codegen::Bindings::AudioNodeBinding::AudioNodeOptions
found: dom::bindings::codegen::Bindings::AudioNodeBinding::{ChannelCountMode, ChannelInterpretation}

```

**Comment by Manishearth** [comment]
Opened https://github.com/PistonDevelopers/image/pull/809 for the image crate, but that may take time, so I'll whitelist it

https://github.com/servo/media/pull/126 for the servo-media one.

**Pull request merged**
