### PR TITLE
Bumped version of rust-mozjs.

### PR DESCRIPTION
**Pull request by asajeffrey**
Bump version of rust-mozjs to 0.1.4.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because version bump

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15276)

### CODE REVIEW

**Comment by asajeffrey** [comment]
cc @jdm

**Comment by jdm** [comment]
@bors-servo: retry
* #15281

**Comment by asajeffrey** [comment]
@bors-servo: retry
* https://github.com/servo/saltfs/issues/585

**Pull request merged**
