### PR TITLE
Start enabling automated webdriver tests

### PR DESCRIPTION
**Pull request by georgeroman**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23443)

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo delegate+
This can merge after the next successful WPT sync, which will include https://github.com/web-platform-tests/wpt/pull/17047.

**Comment by jdm** [comment]
```
STDERR: [2019-06-05 18:36:26,926] [INFO] mod_pywebsocket.standalone.WebSocketServer: Create socket on: (2, 1, 6, '', ('127.0.0.1', 8889))
STDERR: [2019-06-05 18:36:26,926] [INFO] mod_pywebsocket.standalone.WebSocketServer: Create socket on: (2, 1, 6, '', ('127.0.0.1', 8888))
STDERR: [2019-06-05 18:36:26,927] [INFO] mod_pywebsocket.standalone.WebSocketServer: Bind on: (2, 1, 6, '', ('127.0.0.1', 8888))
STDERR: [2019-06-05 18:36:26,927] [INFO] mod_pywebsocket.standalone.WebSocketServer: Listen on: (2, 1, 6, '', ('127.0.0.1', 8888))
STDERR: [2019-06-05 18:36:26,928] [INFO] mod_pywebsocket.standalone.WebSocketServer: Bind on: (2, 1, 6, '', ('127.0.0.1', 8889))
STDERR: [2019-06-05 18:36:26,928] [INFO] mod_pywebsocket.standalone.WebSocketServer: Listen on: (2, 1, 6, '', ('127.0.0.1', 8889))
STDERR: [2019-06-05 18:36:26,934] [DEBUG] mod_pywebsocket.standalone.WebSocketServer: SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)')
Running 4 tests in web-platform-tests

STDERR: [2019-06-05 18:36:26,945] [DEBUG] mod_pywebsocket.standalone.WebSocketServer: SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)')
Max restarts exceeded
Unsupported test type wdspec for product servodriver
Max restarts exceeded
Max restarts exceeded

Ran 0 tests finished in 6.0 seconds.
  • 0 ran as expected. 0 tests skipped.
```
That's not a good sign!

**Comment by georgeroman** [comment]
I've done some investigations and the previous test failed because [here](https://github.com/servo/servo/blob/347d8bdf727d6b43ba7f94b744c9115bc6226aff/tests/wpt/web-platform-tests/tools/webdriver/webdriver/client.py#L421) it is possible to send a new session request having an empty body, which would have triggered an error in `webdriver_server` since legacy parameters were not supported.

**Comment by georgeroman** [comment]
I opened an issue for this: https://github.com/web-platform-tests/wpt/issues/17210.

**Comment by jdm** [comment]
@bors-servo retry
* #23368 23290

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Pull request merged**
