### PR TITLE
Fix parsing and serialization of font-family

### LINKED ISSUE #15059: font-family parsing-serialization is not idempotent with quotes
See the following code:
```html
<!DOCTYPE html>
<p style='font-family: \"times new roman'></p>
<script>
alert(document.querySelector('p').style.fontFamily);
</script>
```

It shows `"times new roman` which is a different value from `\"times new roman`.

### PR DESCRIPTION
**Pull request by SimonSapin**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #15059 (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15183)

### CODE REVIEW

**Comment by jdm** [comment]
The try results won't mean anything until #15164 merges.

**Review by upsuper — APPROVED** [review]
LGTM. I'm not confident enough on reviewing Servo code, though, so you may want someone else to rubberstamp it.

**Comment by SimonSapin** [comment]
@bors-servo retry

* #15239

**Pull request merged**
