### PR TITLE
WIP Update glutin to 0.22

### PR DESCRIPTION
**Pull request by Manishearth**
I'm not actively working on this, but I did some of the work so if
anyone wants to build off of this, feel free! 0.22 is a _major_ change.

### CODE REVIEW

**Comment by asajeffrey** [comment]
As a heads-up, surfmanup will probably get rid of glutin (but keep winit).

**Comment by dralley** [comment]
That change ^ is ongoing in this PR https://github.com/servo/servo/pull/25853

**Comment by dralley** [comment]
This PR can be closed

**Comment by jdm** [comment]
Indeed!

**Comment by asajeffrey** [comment]
We are still using winit, so updating winit to the latest would be great!

**Pull request closed without merging**
