### PR TITLE
Add test for URL-encoded form submission.

### PR DESCRIPTION
**Pull request by eefriedman**
This turned out to be a little more complicated than I was hoping...
but I can't really think of a better way to do this.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7923)

### CODE REVIEW

**Comment by jdm** [comment]
Why's the iframe loading a CSS file?

**Comment by eefriedman** [comment]
It doesn't really matter what the content is; it just needs to be some same-origin document which doesn't contain any scripts.

**Comment by eefriedman** [comment]
Switched the iframe to an HTML file.

**Comment by eefriedman** [comment]
Rebased.

**Comment by frewsxcv** [comment]
Needs to be rebased again

**Comment by eefriedman** [comment]
Rebased again; sorry about the noise.

**Comment by eefriedman** [comment]
@Ms2ger Ping.

**Comment by eefriedman** [comment]
Rebased again.

It's now been over one month since I submitted this PR.

**Comment by nox** [comment]
Looks good to me but it must be rebased.

**Pull request merged**
