### PR TITLE
Add destructors to some WebGL objects, remove duplicated glutin dependency and try to enable the webgl reftests

### PR DESCRIPTION
**Pull request by emilio**
The first commit allows to cleanup the gl resources of the webgl task earlier if they aren't being used.
Right now all resources were cleaned up when the context was destroyed, so I think this is
a slightly better approach.

The second commit bumps rust-offscreen-rendering-context to remove the duplicated glutin dependency.

The third one tries to reenable the webgl reftests.
Since the errored builds are deleted, It's the only way I can try to troubleshoot it.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8291)

### CODE REVIEW

**Comment by ecoal95** [comment]
I don't know how the part of migrating tests to wpt/mozilla is going, probably should move them there instead of re-enabling them in test/ref?

**Comment by ecoal95** [comment]
@jdm I added two commits moving the reftests to mozilla/wpt. The 6 tests are passing for me, tell me if you want me to remove them though :)

**Comment by jdm** [comment]
These changes basically look fine to me. We just need to fix the `test-tidy` errors and assuage my curiosity :)

**Comment by ecoal95** [comment]
@jdm That just loads the gl symbols calling the corresponding API (glx/cgl/egl...). It does the same that the line you mentioned, but without creating a gl context itself. I did that just in order to not depend on a glutin context to load the symbols.

It's messy why we have a headless mode via feature and a headless mode via flag, and why they're handled differently, but...

**Comment by ecoal95** [comment]
I updated the PR so it should pass tidy now :)

**Comment by jdm** [comment]
```
main.rs:57:9: 57:22 error: unresolved name `gl::load_with` [E0425]
main.rs:57         gl::load_with(|addr| GLContext::get_proc_address(addr) as *const _);
                   ^~~~~~~~~~~~~
```

**Comment by ecoal95** [comment]
Seems legit, for android servo omits it too (http://mxr.mozilla.org/servo/source/ports/glutin/window.rs#155)...

Maybe we're statically linking OpenGL there? In that case I'll omit it on android too

**Comment by ecoal95** [comment]
@jdm I just did that. 

By the way seems that the tests pass fine on mac, but crash on the linux buildbot, how could I see the backtrace or something? I can't reproduce any single time, and I'm also on linux.

**Comment by jdm** [comment]
Actually the same two tests displayed failures on both linux and mac:
```
/2dcontext/drawing-images-to-the-canvas/drawimage_canvas_7.html
---------------------------------------------------------------
TIMEOUT [Parent]
/_mozilla/css/hide_after_create.html
------------------------------------
FAIL [Parent]
```

**Comment by jdm** [comment]
According to http://build.servo.org/builders/linux-rel/builds/163/steps/shell_1/logs/stdio, some tests display errors like "(pid:27430) "ERROR:script::dom::webglrenderingcontext: Couldn't create WebGLRenderingContext: glx::ChooseFBConfig"". Unfortunately we don't have any mechanism on the builders to automatically report stack traces when segfaults occur :(

**Comment by jdm** [comment]
Oh right, I think that problem is why we disabled the webgl reftests originally :(

**Comment by jdm** [comment]
#7931

**Comment by ecoal95** [comment]
Yes, I think those are intermittent ant shouldn't be related (timeouts in canvas tests are common because they use to be slow for debug builds).

I'd want to debug the webgl tests on linux, or if that's not easy, at least leaving them enabled on mac (have we got something like `flacky_linux` for wpt tests?).

Yeah I saw that issue. The errors that are displayed into the console are because the context creation didn't succeed (that could be explained by a bunch of different factors). Those worry me, but not so much as the segfault shown in the issue.

Unfortunately without access to a stack trace and without possibility to replicate it locally I have no way to debug them.

**Comment by ecoal95** [comment]
What's the linux buildbot environment like?

**Comment by jdm** [comment]
Did you see the stack trace from the other issue? We do have the ability to disable tests on particular platforms, too.

**Comment by ecoal95** [comment]
Check this out, I think this might be the cause: https://github.com/ecoal95/rust-offscreen-rendering-context/commit/aae6e57969c553973c43ce5e4246831ccc2868f0

I find it really weird that it fails on `XOpenDisplay` with null as an argument (which opens the default display), but it's the only cause I could think of after seeing that stack trace.

May you do a try build? (the tests should still fail, but not segfaulting at least). I'm not sure why the X server reports that there's no display though.

**Comment by eefriedman** [comment]
The changes don't seem to help; still just crashes (see http://build.servo.org/builders/linux-rel/builds/164/steps/shell_1/logs/stdio).

**Comment by ecoal95** [comment]
Still crashing on linux, now I have no damn idea about what's going on... The mac failure seems like an unrelated timeout, so I think we're fine disabling these tests on linux for now, if we can't do better debugging.

How would I disable a reftest for a given platform? I guess is something like `if os != "linux" PASS`, but I'm not totally sure.

**Comment by ecoal95** [comment]
BTW @eefriedman thanks for your help! :)

**Comment by jdm** [comment]
See http://mxr.mozilla.org/servo/source/tests/wpt/metadata/XMLHttpRequest/send-entity-body-document.htm.ini#3 .

**Comment by ecoal95** [comment]
@jdm Done :P

**Pull request merged**
