### PR TITLE
Implement Worker#terminate() (fixes #4427).

### LINKED ISSUE #4427: Implement Worker.terminate
Spec: https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-worker-interface:dom-worker-terminate
Tests: workers/Worker_terminate_event_queue.htm, workers/constructors/Worker/terminate.html 
Code: components/script/dom/worker.rs

### PR DESCRIPTION
**Pull request by KiChjang**
Adds support for terminating DOM workers. A closing flag was added to
WorkerGlobalScope per the spec.

Rebased #6652, with some comments addressed.
Fixes #4427.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9688)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 244 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCZHdrkb0326Vc9bhVv:-KCZHdrkb0326Vc9bhVw:1706084442) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/dedicatedworkerglobalscope.rs#L244)):*
While moving this after the fallible network operation is now safer, it means that the main thread cannot continue execution until the network operation is complete. That's not going to fly, unfortunately. I propose the main thread create an `Arc<Mutex<Option<*mut JSRuntime>>>` and pass it to the DedicatedWorkerGlobalScope constructor, rather than doing this SharedRt channel dance.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 409 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCY07ntqXURwboRDRN0:-KCY07nuuLyXIirPdoC4:852130649) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/dedicatedworkerglobalscope.rs#L409)):*
I'm not sure this comment adds anything.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 415 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCY0-z51anoM4GdpGS4:-KCY0-z51anoM4GdpGS5:-397321080) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/dedicatedworkerglobalscope.rs#L415)):*
`assert!(worker.is::<DedicatedWorkerGlobalScope>())`

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 424 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCYvRfF2_oTG_7zuSnC:-KCYvRfF2_oTG_7zuSnD:-192878808) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/dedicatedworkerglobalscope.rs#L424)):*
This check is redundant, since we have a check in Worker::handle_message.

---

*[components/script/dom/worker.rs, line 116 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCYw_qbmmNyvugaWWaH:-KCYw_qbmmNyvugaWWaI:1627847996) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/worker.rs#L116)):*
s/task/thread/

---

*[components/script/dom/worker.rs, line 178 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCYxMgJ4w6Ls--S9Da8:-KCYxMgJ4w6Ls--S9Da9:-667511596) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/worker.rs#L178)):*
nit: remove this newline

---

*[components/script/dom/bindings/global.rs, line 269 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCY-ZOsGM1Hh4xF1zb4:-KCY-ZOsGM1Hh4xF1zb5:153794106) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/bindings/global.rs#L269)):*
We should update this comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9688#-:-KCZIlXxMwWAVZ9Jgtze:1458266033)*

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 244 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCZHdrkb0326Vc9bhVv:-KC_a0gat54XaEpGRvGT:193400708) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/dedicatedworkerglobalscope.rs#L244)):*
Why not just move this before the fetching?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9688)*

**Comment by jdm** [comment]
Because the runtime pointer becomes invalid in the case where the fetch has an error, which then needs to be handled carefully. I'd rather make it bulletproof without having to think about it.

**Comment by KiChjang** [comment]
Review status: 7 of 13 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 244 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCZHdrkb0326Vc9bhVv:-KD83oW-L3RgSRZEhbcE:849459886) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/dedicatedworkerglobalscope.rs#L244)):*
I'm not sure how this would work. If I understood correctly, the main thread means the Worker that creates the DedicatedWorkerGlobalScope. Passing the `Arc<Mutex<Option<*mut JSRuntime>>>` is trivial, but it's not possible to mutate the inner JSRuntime because JSRuntime does not implement Send, and the JSRuntime in DedicatedWorkerGlobalScope is created in a separate thread.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9688)*

**Comment by jdm** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 244 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9688#-KCZHdrkb0326Vc9bhVv:-KDAZzo52FeHI1t57rwN:1147887802) ([raw file](https://github.com/servo/servo/blob/df0dade663c86a2af21ea3a89c0a243b3431a603/components/script/dom/dedicatedworkerglobalscope.rs#L244)):*
We can use SharedRt to work around the lack of Send, so `Arc<Mutex<Option<SharedRt>>>` instead should do the trick.

---

*[components/script/dom/worker.rs, line 120 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9688#-KDAZbJtIK-eaOBJMcqA:-KDAZbJtIK-eaOBJMcqB:667435673) ([raw file](https://github.com/servo/servo/blob/323c5513f17276f6b708dd4c77ab412364132669/components/script/dom/worker.rs#L120)):*
Hmm, for the main thread we do want the DOM manipulation task source, since that's where postMessage is sent. Perhaps for worker globals that should just redirect to script_chan() under the hood.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9688)*

**Comment by KiChjang** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: 10 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/dom/worker.rs, line 120 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9688#-KDAZbJtIK-eaOBJMcqA:-KDBJRuWMmqeTXyNh5rP:255733971) ([raw file](https://github.com/servo/servo/blob/323c5513f17276f6b708dd4c77ab412364132669/components/script/dom/worker.rs#L120)):*
Should this instead follow the model in window.rs, where the dom_struct stores a dom_manipulation_task_source?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9688#-:-KDBJo20xv4J39VqPLqb:1458266033)*

**Comment by jdm** [comment]
Review status: 10 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[components/script/dom/worker.rs, line 120 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9688#-KDAZbJtIK-eaOBJMcqA:-KECuWV9d6ZdLkWXmaw0:-640591668) ([raw file](https://github.com/servo/servo/blob/323c5513f17276f6b708dd4c77ab412364132669/components/script/dom/worker.rs#L120)):*
I don't think it's worth storing something in WorkerGlobalScope/DedicatedWorkerGlobalScope called `dom_manipulation_task_source` when the specification declares that workers don't have one.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9688)*

**Comment by KiChjang** [comment]
Review status: 7 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/dom/worker.rs, line 120 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9688#-KDAZbJtIK-eaOBJMcqA:-KEjKlwvgyPLyTQ6ogY8:88728150) ([raw file](https://github.com/servo/servo/blob/323c5513f17276f6b708dd4c77ab412364132669/components/script/dom/worker.rs#L120)):*
Huh, it's not as simple as redirecting to script_chan() under the hood. I thought of bubbling the message up the chain until it hits a Window global, but then I also saw `WorkerScriptMsg` already has a `DOMMessage` variant. I'd like to file a follow-up issue to look further into this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9688)*

**Comment by jdm** [comment]
Review status: 7 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[components/script/dom/worker.rs, line 120 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9688#-KDAZbJtIK-eaOBJMcqA:-KEm-WDHTEOsNKzjIIKe:-1932051088) ([raw file](https://github.com/servo/servo/blob/323c5513f17276f6b708dd4c77ab412364132669/components/script/dom/worker.rs#L120)):*
Ok, we can leave this and file a followup issue for making use of the DOM manipulation task instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9688)*

**Comment by KiChjang** [comment]
Filed #10460.

**Comment by jdm** [comment]
Almost there!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 232 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9688#-KEm-wYgWmftNGbYH_se:-KEm-wYgWmftNGbYH_sf:-256678110) ([raw file](https://github.com/servo/servo/blob/7dc2afd600c99ab491c6a201759d54ef68c0ad02/components/script/dom/dedicatedworkerglobalscope.rs#L232)):*
This could just be `*main_thread_rt.lock().unwrap() = Some(SharedRt::new(&runtime));` and avoid the extra scope. Let's also move this back to where it used to be created.

---

*[components/script/dom/dedicatedworkerglobalscope.rs, line 272 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9688#-KEm1Je_VEfa1YAbZCRb:-KEm1Je_VEfa1YAbZCRc:-422233729) ([raw file](https://github.com/servo/servo/blob/7dc2afd600c99ab491c6a201759d54ef68c0ad02/components/script/dom/dedicatedworkerglobalscope.rs#L272)):*
Let's add an accessor to `WorkerGlobalScope` to get the JSRuntime pointer here instead.

---

*[components/script/dom/worker.rs, line 182 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9688#-KEm2iINvLMa1CrGRZ4A:-KEm2iIOJKaOzPZ4VbrT:-685291286) ([raw file](https://github.com/servo/servo/blob/7dc2afd600c99ab491c6a201759d54ef68c0ad02/components/script/dom/worker.rs#L182)):*
I'm tempted to say that we shouldn't try to handle failures when locking the mutex here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9688#-:-KEm35Jw6TefSo5xwFau:1573484854)*

**Comment by KiChjang** [comment]
Review status: 10 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/script/dom/worker.rs, line 182 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9688#-KEm2iINvLMa1CrGRZ4A:-KEmGoW0g9luyyerxGmu:1728337827) ([raw file](https://github.com/servo/servo/blob/7dc2afd600c99ab491c6a201759d54ef68c0ad02/components/script/dom/worker.rs#L182)):*
Gah, I wanted to consume both the Arc and the Mutex here instead, but self is immutably borrowed so I can't do anything about it. Do I need to modify the codegen/webIDL file in order to get a self or &mut self?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9688)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/worker.rs, line 182 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9688#-KEm2iINvLMa1CrGRZ4A:-KEmjhSxR22W05bN9Ser:-1363400415) ([raw file](https://github.com/servo/servo/blob/7dc2afd600c99ab491c6a201759d54ef68c0ad02/components/script/dom/worker.rs#L182)):*
Anything besides `&self` in methods for DOM objects isn't safe, since there could be arbitrary numbers of references to them that could be invoked if they call back into JS. If you really want to consume it, put it inside of an Option in a DOMRefCell and set it to None.

I don't really understand why we're trying to make any guarantees about the shared runtime here, though. Why does it matter if there's another copy hanging around?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9688#-:-KEmkv6Tw7MZuCnmDc0z:1458266033)*

**Comment by KiChjang** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/worker.rs, line 182 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9688#-KEm2iINvLMa1CrGRZ4A:-KEmlur65JmboZuBoET5:1054890882) ([raw file](https://github.com/servo/servo/blob/7dc2afd600c99ab491c6a201759d54ef68c0ad02/components/script/dom/worker.rs#L182)):*
If we aren't locking it and we aren't consuming the mutex, how would we gain access to the underlying runtime?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9688)*

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/worker.rs, line 182 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9688#-KEm2iINvLMa1CrGRZ4A:-KEmrT7hVDOfzA00wwFz:1524970753) ([raw file](https://github.com/servo/servo/blob/7dc2afd600c99ab491c6a201759d54ef68c0ad02/components/script/dom/worker.rs#L182)):*
I didn't mean we shouldn't unlock it; I meant that I think calling `unwrap` on the result of unlocking is totally fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9688)*

**Comment by KiChjang** [comment]
Brainfarted. But comments addressed now.

**Comment by jdm** [comment]
@bors-servo: r+

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9688#-:-KEmzxPKHWlQMAVYLHBO:-317921516)*

**Pull request merged**
