### PR TITLE
Implement WebIDL sequence arguments

### LINKED ISSUE #544: Implement WebIDL sequences
It looks like these can just be vectors; nothing really special here.

### PR DESCRIPTION
**Pull request by emilio**
And use it for `WebGLRenderingContext#uniform1fv`.

Blocked on https://github.com/servo/rust-mozjs/pull/226

Fixes #544

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9056)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9056#-:-K6Dj6TPEyAMDRWfTFky:1236647940)*

**Comment by nox** [comment]
```
/home/travis/build/servo/servo/target/debug/build/script-7d4eb0076eebd90a/out/Bindings/WebGLRenderingContextBinding.rs:3394:32: 3394:64 error: the trait `js::conversions::FromJSValConvertible` is not implemented for the type `collections::vec::Vec<f32>` [E0277]
/home/travis/build/servo/servo/target/debug/build/script-7d4eb0076eebd90a/out/Bindings/WebGLRenderingContextBinding.rs:3394     let arg1: Vec<f32> = match FromJSValConvertible::from_jsval(cx, args.get(1), ()) {
                                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by nox** [comment]
```
./components/script/dom/bindings/codegen/CodegenRust.py:562: E302 expected 2 blank lines, found 1
./components/script/dom/bindings/codegen/CodegenRust.py:731: E703 statement ends with a semicolon
```

**Comment by ecoal95** [comment]
Rebased and updated rust-mozjs to the latest version.

**Comment by ecoal95** [comment]
Updated the first commit with tests, though it's blocked on https://github.com/servo/rust-mozjs/pull/230 now.

I'll move the commits in the middle to another PR.

**Comment by ecoal95** [comment]
Updated mozjs and removed the commits in the middle.

**Comment by nox** [comment]
Shouldn't the two commits be in the other order?

**Comment by ecoal95** [comment]
@nox True, I implemented it using overrides, that was why they were not ordered properly. Done :P

**Comment by ecoal95** [comment]
@nox: ping (there are prs blocked on this one)

**Comment by nox** [comment]
@ecoal95 Sorry for the delay.

Could you split the second commit in two, first moving around the conversion behaviour stuff, and second actually implementing the sequence arguments?

**Comment by ecoal95** [comment]
No problem, I know you're busy with the SMup and a lot of other stuff :P

Just splitted the commit in as many independent parts as possible.

**Comment by nox** [comment]
@bors-servo r+

-S-needs-rebase 

---

Reviewed 5 of 5 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9056#-:-K7quOB55eRQ82PaA9K6:1167841897)*

**Pull request merged**
