### PR TITLE
Improve system font selection under Freetype

### PR DESCRIPTION
**Pull request by dan-robertson**
Corrected the implementations for `boldness` and `stretchiness` for the Freetype platform. The old implementation for `boldness` was incorrect for fonts which are lighter than normal and the old implementation for `stretchiness` was incomplete and returned a default value.

Improved the metric used to pick a font close to a given style.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [x] These changes have tests here: `tests/html/font_selection.html`

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19026)

### CODE REVIEW

**Comment by emilio** [comment]
Is there any chance to test this? This looks fine to me, but a test would be nice...

**Comment by dan-robertson** [comment]
I agree. There is a test for e.g. `font-stretch` but they are html and not automated. They also presume that e.g. Helvetica is installed on the system and that assumption may not be true on all linux systems. It would be nice to have some test based on a font from the web or packaged with servo but, as far as I can tell, `@font-face` declarations specify the boldness and stretch (rather than specifying a family and then having another style specify weight/stretch).

Another problem is that the effect of these changes may only appear as which specific face in a family of system fonts gets chosen and the code which makes the choice will take the first exact match, so for example if one wants font A at normal weight, the old code may get lucky and consider "A-regular" before "A-light" and choose the right font, or it may get unlucky and pick "A-light" instead. Thus it is hard to tell if the new code is performing correctly or is consistently lucky. I'm welcome to suggestions but I'm just not really sure what a test would look like and how it may be written in a way that doesn't depend on what fonts a user has installed.

Perhaps some environment variables could be set to tell Freetype to search some extra directory for fonts but this feels like it would need some invasive changes for little gain. Maybe some tests could be written that just assume that a well-known font is installed in lots of variations, e.g. DejaVu Sans.

**Comment by dan-robertson** [comment]
I added a manual test which should allow the results of the changes to be seen. This showed that the code which actually chooses a font gives quite poor results so I've changed that too so that it makes some more reasonable choices.

**Pull request closed without merging**
