### PR TITLE
Remove webdriver use of SubpageId

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8009)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/webdriver_handlers.rs, line 111 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8009#-K0aWoYLP7G6MEjueo4P)** ([raw file](https://github.com/servo/servo/blob/cb9de8713cbb870b1b561450dfafad0530272f0b/components/script/webdriver_handlers.rs#L111)):</sup>
`let frame_id = window.map(|x| x.map(|x| x.r().pipeline()));`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8009)

**Comment by glennw** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/webdriver_handlers.rs, line 111 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8009#-K0aWoYLP7G6MEjueo4P)** ([raw file](https://github.com/servo/servo/blob/cb9de8713cbb870b1b561450dfafad0530272f0b/components/script/webdriver_handlers.rs#L111)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8009)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8009)

**Comment by jdm** [comment]
@bors-servo: retry
* #7785

**Pull request merged**
