### PR TITLE
Say farewell to in-tree HeapSizeOf

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9532)

### CODE REVIEW

**Comment by Manishearth** [comment]
Reviewed 82 of 82 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9532)*

**Comment by Manishearth** [comment]
```diff
diff --git a/ports/gonk/Cargo.lock b/ports/gonk/Cargo.lock
index b5ff8e6..09893b8 100644
--- a/ports/gonk/Cargo.lock
+++ b/ports/gonk/Cargo.lock
@@ -906,6 +906,8 @@ dependencies = [
  "fnv 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
  "gfx 0.0.1",
  "gfx_traits 0.0.1",
+ "heapsize 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)",
+ "heapsize_plugin 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
  "ipc-channel 0.2.0 (git+https://github.com/servo/ipc-channel)",
  "layout_traits 0.0.1",
  "libc 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)",
```

**Comment by nox** [comment]
@bors-servo r=Manishearth

Missing stuff in lock files.

**Pull request merged**
