### PR TITLE
Update mozjs to 89

### PR DESCRIPTION
**Pull request by sagudev**
Trying to catch Firefox release.
Depends on https://github.com/servo/rust-mozjs/pull/543

### CODE REVIEW

**Comment by sagudev** [comment]
@jdm mac failed on packaging app.

**Comment by sagudev** [comment]
After reviewing tests, it looks tha most of them become PASS, but it looks like something is wrong with promises.

**Comment by sagudev** [comment]
```
  ▶ Unexpected subtest result in /html/semantics/scripting-1/the-script-element/module/dynamic-import/dynamic-imports-script-error.html:
  │ FAIL [expected PASS] b'import() must reject with the same error object for each import when there is a evaluation error'
  │   → assert_equals: The error objects must be equal expected object "Error: Unevaluated or errored module returned by module resolve hook" but got object "Error: Unevaluated or errored module returned by module resolve hook"
```

**Comment by jdm** [comment]
The module tests in particular look like there's a problem with those changes in this PR.

**Comment by sagudev** [comment]
Changes were required because of https://bugzilla.mozilla.org/show_bug.cgi?id=1668330:

- https://hg.mozilla.org/mozilla-central/rev/be113df2bd10
- https://hg.mozilla.org/mozilla-central/rev/2690ae6050e4

**Comment by sagudev** [comment]
> "Error: Unevaluated or errored module returned by module resolve hook" but got object "Error: Unevaluated or errored module returned by module resolve hook"

But wait "`Error: Unevaluated or errored module returned by module resolve hook`"
           = "`Error: Unevaluated or errored module returned by module resolve hook`"

**Comment by sagudev** [comment]
> ```
>   ▶ Unexpected subtest result in /html/semantics/scripting-1/the-script-element/module/dynamic-import/dynamic-imports-script-error.html:
>   │ FAIL [expected PASS] b'import() must reject with the same error object for each import when there is a evaluation error'
>   │   → assert_equals: The error objects must be equal expected object "Error: Unevaluated or errored module returned by module resolve hook" but got object "Error: Unevaluated or errored module returned by module resolve hook"
> ```

Expected error is `Error`. 
These Errors come from https://searchfox.org/mozilla-central/search?q=Unevaluated+or+errored&path= 
There is also `Unhandled rejection` error in this test and in some other test there are problems with promises.

**Comment by sagudev** [comment]
On `./mach test-wpt html/semantics/scripting-1/the-script-element/module/dynamic-import/dynamic-imports-script-error.html`
Expected:
slika
What its currently:
slika

**Comment by sagudev** [comment]
Probably missing some error handling like:
https://hg.mozilla.org/mozilla-central/rev/be113df2bd10#l4.363

**Comment by sagudev** [comment]
Very suspicious: https://bugzilla.mozilla.org/show_bug.cgi?id=1536094
Which creates:
- https://hg.mozilla.org/mozilla-central/rev/c578a7dd691c
- https://hg.mozilla.org/mozilla-central/rev/ddba49efbd9f
- https://hg.mozilla.org/mozilla-central/rev/ba4c269cea68

**Comment by Redfire75369** [comment]
According to a GJS developer, @ewlsh in #spidermonkey:mozilla.org matrix.
> It looks like they just haven't updated their code for the TLA changes to the promises API
> You can look at GJS' mozjs91 MR if you want to get a sense of how to adjust API usage + handle dynamics

I believe they are referring to this MR: <https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/632>
Even more specifically, this looks like the commit that implemented those changes: <https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/632/diffs?commit_id=e4ed245f13a703968b7e2f5acadc36a54452e22a#158c25371cf55a8db28e9b6c41a3ee4840d2cf8d>.

**Comment by sagudev** [comment]
Due to not having time I'm closing this PR.

**Pull request closed without merging**
