### PR TITLE
fix getElementsByTagName()

### LINKED ISSUE #11596: Properly implement the getElementsByTagName method on Document and Element
These two methods don't pass the tests that use non-HTML elements.

See the two tests "Element in non-HTML namespace, prefix, uppercase name" and "Element in non-HTML namespace, prefix, lowercase name".

We should think about how to implement efficiently the step 2 of [the spec](https://dom.spec.whatwg.org/#concept-getelementsbytagname).

See methods `Document::GetElementsByTagName`, `Element::GetElementsByTagName`, `HTMLCollection::by_tag_name` and `HTMLCollection::by_atomic_tag_name`.

These two last methods should be documented and probably renamed to something a bit more descriptive.

Files:
- components/script/dom/document.rs
- components/script/dom/element.rs
- components/script/dom/htmlcollection.rs
- tests/wpt/metadata/dom/nodes/Document-getElementsByTagName.html.ini
- tests/wpt/metadata/dom/nodes/Element-getElementsByTagName.html.ini
- tests/wpt/web-platform-tests/dom/nodes/Document-Element-getElementsByTagName.js
- tests/wpt/web-platform-tests/dom/nodes/Document-getElementsByTagName.html
- tests/wpt/web-platform-tests/dom/nodes/Element-getElementsByTagName.html

### PR DESCRIPTION
**Pull request by kevgs**
This is a continue of work started at https://github.com/servo/servo/pull/11705

Added test, fixed code for better use of Atom.

Fixes #11596.

r? @nox 

> When invoked with the same argument, and as long as root’s node document’s type has not changed, the same HTMLCollection object may be returned as returned by an earlier call.

This is implemented in document.rs with tag_map field.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12844)

### CODE REVIEW

**Comment by nox** [comment]
+S-needs-code-changes +S-awaiting-answer 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/document.rs, line 2069 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12844#-KP33Xf_ZIlYr_N_tfEf:-KP33Xf_ZIlYr_N_tfEg:bapsfz5) ([raw file](https://github.com/servo/servo/blob/d3d9c0312e48f8a71eddc23dd0811231f519d721/components/script/dom/document.rs#L2069)):*
> ```Rust
>     fn GetElementsByTagName(&self, qualified_name: DOMString) -> Root<HTMLCollection> {
>         let qualified_name = Atom::from(qualified_name);
>         match self.tag_map.borrow_mut().entry(qualified_name.clone()) {
> ```

You don't need to clone the name here, instead in the `Vacant` arm, do:

```rust
let result = HTMLCollection::match_elements_by_qualified_name(
    &self.window, self.upcast(), entry.key().clone());
```

---

*[components/script/dom/htmlcollection.rs, line 116 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12844#-KP3412CdsjGlbLIgmlb:-KP3412DJeDsr0xvbmOv:b-z28ofl) ([raw file](https://github.com/servo/servo/blob/d3d9c0312e48f8a71eddc23dd0811231f519d721/components/script/dom/htmlcollection.rs#L116)):*
> ```Rust
>     }
> 
>     pub fn match_elements_by_qualified_name(window: &Window, root: &Node, qualified_name: Atom)
> ```

Please just rename that to `by_qualified_name`.

---

*[components/script/dom/htmlcollection.rs, line 119 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12844#-KP34AXsRV5z4fXwsJIP:-KP34AXsRV5z4fXwsJIQ:b-x5vfoh) ([raw file](https://github.com/servo/servo/blob/d3d9c0312e48f8a71eddc23dd0811231f519d721/components/script/dom/htmlcollection.rs#L119)):*
> ```Rust
>                                             -> Root<HTMLCollection> {
>         #[derive(JSTraceable, HeapSizeOf)]
>         struct TagNameFilter {
> ```

Nit: for consistency, rename that `QualifiedNameFilter`.

---

*[components/script/dom/htmlcollection.rs, line 140 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12844#-KP34xQwe9GvDiduT_jA:-KP34xQwe9GvDiduT_jB:bgrzn7z) ([raw file](https://github.com/servo/servo/blob/d3d9c0312e48f8a71eddc23dd0811231f519d721/components/script/dom/htmlcollection.rs#L140)):*
> ```Rust
>             ascii_lower_qualified_name: ascii_lower_qualified_name,
>         };
>         HTMLCollection::create(window, root, box filter)
> ```

Where do you discriminate steps 2 and 3 from [the spec](https://dom.spec.whatwg.org/#concept-getelementsbytagname) here?

---

*[components/script/dom/htmlcollection.rs, line 150 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12844#-KP34cKFac3oNag-6g3w:-KP34cKFac3oNag-6g3x:b-ton40d) ([raw file](https://github.com/servo/servo/blob/d3d9c0312e48f8a71eddc23dd0811231f519d721/components/script/dom/htmlcollection.rs#L150)):*
> ```Rust
>                 qualified_name.find(":") == Some((prefix as &str).len()) &&
>                 qualified_name.ends_with(elem.local_name() as &str),
>         }
> ```

Why do you look at the prefix at all? To what does that correspond in the spec?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12844#-:-KP34mgwgBV47SlY4anp:b-q861xj)*

**Comment by kevgs** [comment]
> Why do you look at the prefix at all? To what does that correspond in the spec?

We can't just compare element`s local name with qualified name because sometimes qualified name is prefix + ':' + local name. https://dom.spec.whatwg.org/#concept-element-qualified-name

> Where do you discriminate steps 2 and 3 from the spec here?

You`re right. I have a bug here. But reading through spec I found a mismatch.

> Otherwise, returns a HTMLCollection of all descendant elements whose qualified name is qualifiedName. (Matches case-insensitively against elements in the HTML namespace within an HTML document.)

> Thus, in an HTML document, document.getElementsByTagName("FOO") will match <FOO> elements that are not in the HTML namespace, and <foo> elements that are in the HTML namespace, but not <FOO> elements that are in the HTML namespace.

Case insensitive compare and lowercasing qualified name before compare is not the same thing. I quess the right thing is lowercasing as written [here](https://dom.spec.whatwg.org/#concept-element-qualified-name) but I think spec should be fixed.

**Comment by nox** [comment]
> We can't just compare element`s local name with qualified name because sometimes qualified name is prefix + ':' + local name. https://dom.spec.whatwg.org/#concept-element-qualified-name

Got it.

> Case insensitive compare and lowercasing qualified name before compare is not the same thing. I quess the right thing is lowercasing as written here but I think spec should be fixed.

The sentence you copied is from a non-normative note and when the DOM spec talks about case-insensitivity it means ASCII case-insensitivity. ASCII case-insensitivity comparison and comparison after ASCII lowercasing are the same things.

**Comment by nox** [comment]
-S-awaiting-answer -S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/htmlcollection.rs, line 122 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12844#-KPHYLVpstSNBaXKhL9W:-KPHYLVpstSNBaXKhL9X:bt3oas4) ([raw file](https://github.com/servo/servo/blob/9d6eb182be1c6f373be502c6b8f4a7477d09d749/components/script/dom/htmlcollection.rs#L122)):*
> ```Rust
>         if qualified_name == atom!("*") {
>             #[derive(JSTraceable, HeapSizeOf)]
>             struct QualifiedNameFilter {
> ```

If you disambiguate this way, please give each filter a name that makes sense.

For this one it could be:

```rust
struct AllFilter;
```

---

*[components/script/dom/htmlcollection.rs, line 133 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12844#-KPHYaf101Y4b86u_V_Z:-KPHYaf101Y4b86u_V__:bxriva9) ([raw file](https://github.com/servo/servo/blob/9d6eb182be1c6f373be502c6b8f4a7477d09d749/components/script/dom/htmlcollection.rs#L133)):*
> ```Rust
> 
>         // case 2
>         if root.is_in_html_doc() {
> ```

You can't do that here, because `root` could change tree after the collection was created, not being in an HTML document anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12844#-:-KPHXxQmJXr0h_0t5DqQ:b493f4j)*

**Comment by kevgs** [comment]
> You can't do that here, because root could change tree after the collection was created, not being in an HTML document anymore.

I do not understand that at all. How root could change if it passed immutable in by_qualified_name?

**Comment by nox** [comment]
`root` is an element, and any node can be removed from their tree or adopted into another document.

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/htmlcollection.rs, line 122 \[r3\]](https://reviewable.io:443/reviews/servo/servo/12844#-KPI5VL8gC-C5x5Y5UfZ:-KPI5VL8gC-C5x5Y5Uf_:b-92t4b7) ([raw file](https://github.com/servo/servo/blob/809768e66e44b2e5c5a2c2127d4234a03356e7bf/components/script/dom/htmlcollection.rs#L122)):*
> ```Rust
>         if qualified_name == atom!("*") {
>             #[derive(JSTraceable, HeapSizeOf)]
>             struct AllFilter {
> ```

Make it a unit struct:

```rust
struct AllFilter;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12844#-:-KPI5avDliwIjrZVMd0x:bo47p9t)*

**Comment by kevgs** [comment]
> `root` is an element, and any node can be removed from their tree or adopted into another document.

Ok. But I still do not understand. I'm assuming that tree won't change while by_qualified_name() is running. Isn't it true?

**Comment by nox** [comment]
It's wrong. That method returns a `HTMLCollection`. These collections are live and reflect changes made on the tree.

> If a collection is live, then the attributes and methods on that object must operate on the actual underlying data, not a snapshot of the data.

**Comment by nox** [comment]
@kevgs Need help with this?

**Comment by kevgs** [comment]
Yes. I have no idea how to replase root.is_in_html_doc().

**Comment by nox** [comment]
You need to merge the two different kind of collections into a single one, that checks whether `root` is in an HTML document when filtering nodes.

**Comment by kevgs** [comment]
Sorry, but it looks like I have neither time nor skill to accomplish this task. Hope this uncompleted patch will help someone to fix that issue.

**Comment by jdm** [comment]
Thanks for letting us know!

**Comment by mskrzypkows** [comment]
*[components/script/dom/htmlcollection.rs, line 140 at r1](https://reviewable.io:443/reviews/servo/servo/12844#-KP34xQwe9GvDiduT_jA:-KUWbeoP76n9khsczp-z:b-3tj1dr) ([raw file](https://github.com/servo/servo/blob/d3d9c0312e48f8a71eddc23dd0811231f519d721/components/script/dom/htmlcollection.rs#L140)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> Where do you discriminate steps 2 and 3 from [the spec](https://dom.spec.whatwg.org/#concept-getelementsbytagname) here?
</details>
As I understand, discrimination of steps 2 and 3 is done by ```if root.is_in_html_doc()``` but is wrong as you said above. How to distinguish them when ```root``` can change? I need some way to decide which step has to be done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12844)*

**Comment by nox** [comment]
@mskrzypkows You need to use that function in the filter itself, and not use it to return different filters.

**Pull request closed without merging**
