### PR TITLE
Merge similar arms in AnimationValue::from_declaration 🐉🐲

### PR DESCRIPTION
**Pull request by nox**
This slims that function by 12KB according to bloaty.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20025)

### CODE REVIEW

**Comment by nox** [comment]
r? @emilio 

https://treeherder.mozilla.org/#/jobs?repo=try&revision=2fa0d8db3fc9e7937a57e853fc7f87ecec0ab950

**Review by emilio — APPROVED** [review]
r=me, it's not like this code wasn't ugly in the first place :)

**Comment by jdm** [comment]
@bors-servo retry
* windows builder should be in better shape

**Pull request merged**
