### PR TITLE
Fix and document build on CentOS 7.4

### PR DESCRIPTION
**Pull request by marmistrz**
Fix and document build on CentOS 7.4

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable). **N/A**

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because no code is changed

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19545)

### CODE REVIEW

**Comment by marmistrz** [comment]
This PR is a continuation of https://github.com/servo/gecko-media/pull/125

**Comment by jdm** [comment]
@bors-servo: retry
* #19599

**Comment by tigercosmos** [comment]
not squash?

**Pull request merged**
