### PR TITLE
Force HTMLStyleElement to create a new CSSStyleSheet when re-parsing.

### PR DESCRIPTION
**Pull request by jyc**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] These changes do not require tests because I'm pushing to find out what test results this changes; this is part of a series of PRs to fix bug #17182

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17259)

### CODE REVIEW

**Comment by jyc** [comment]
Oops, the commit message actually has some text left over from when this was still part of the other PR. I will remove that right now, sorry.

**Comment by jyc** [comment]
No code changed, though, just removing the text about `./mach update-wpt`.

**Comment by jdm** [comment]
There were no test result changes caused by this code change.

**Comment by jyc** [comment]
I see! That's kind of interesting, I guess that means that the only things that depended on this behavior actually depended on the other parts of the original PR as well.

**Comment by jdm** [comment]
It likely means that there are no tests that obtain the CSSOM data of a `<style>` element, then modify its text children (using traditional DOM node APIs rather that SetData), then verify that the CSSOM data reflects the change that was made.

**Comment by jyc** [comment]
Added a quick test that passes on Firefox, Chrome, Safari, and Edge, but not on Servo before this commit.

**Comment by emilio** [comment]
Thanks for the fix!

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/semantics.html:
  └ PASS [expected FAIL] @namespace x 'http://www.w3.org/XML/1998/namespace'; [x|lang='A' i] <div {http://www.w3.org/XML/1998/namespace}lang="a"> in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/semantics.html:
  └ PASS [expected FAIL] @namespace x 'a'; [x|foo='' i] <div {A}foo=""> in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/semantics.html:
  └ PASS [expected FAIL] @namespace x 'A'; [x|foo='' i] <div {a}foo=""> in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/semantics.html:
  └ PASS [expected FAIL] @namespace x 'http://www.w3.org/XML/1998/namespace'; [x|lang='A' i] <div {http://www.w3.org/XML/1998/namespace}lang="a"> in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/semantics.html:
  └ PASS [expected FAIL] @namespace x 'a'; [x|foo='' i] <div {A}foo=""> in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/semantics.html:
  └ PASS [expected FAIL] @namespace x 'A'; [x|foo='' i] <div {a}foo=""> in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/semantics.html:
  └ PASS [expected FAIL] @namespace x 'http://www.w3.org/XML/1998/namespace'; [x|lang='A' i] <div {http://www.w3.org/XML/1998/namespace}lang="a"> in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/semantics.html:
  └ PASS [expected FAIL] @namespace x 'a'; [x|foo='' i] <div {A}foo=""> in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/semantics.html:
  └ PASS [expected FAIL] @namespace x 'A'; [x|foo='' i] <div {a}foo=""> in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='BAR'] /* sanity check (valid) */ in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' I] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo=bar i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo="bar" i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'i ] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' i ] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' /**/ i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' i /**/ ] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'/**/i/**/] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo=bar/**/i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'\ti\t] /* \\t */ in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'\ni\n] /* \\n */ in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'\ri\r] /* \\r */ in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' \\i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' \\69] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo~='bar' i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo^='bar' i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo$='bar' i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo*='bar' i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo|='bar' i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [|foo='bar' i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [*|foo='bar' i] in standards mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='BAR'] /* sanity check (valid) */ in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' I] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo=bar i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo="bar" i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'i ] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' i ] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' /**/ i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' i /**/ ] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'/**/i/**/] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo=bar/**/i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'\ti\t] /* \\t */ in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'\ni\n] /* \\n */ in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'\ri\r] /* \\r */ in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' \\i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' \\69] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo~='bar' i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo^='bar' i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo$='bar' i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo*='bar' i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo|='bar' i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [|foo='bar' i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [*|foo='bar' i] in quirks mode

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='BAR'] /* sanity check (valid) */ in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' I] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo=bar i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo="bar" i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'i ] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' i ] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' /**/ i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' i /**/ ] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'/**/i/**/] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo=bar/**/i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'\ti\t] /* \\t */ in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'\ni\n] /* \\n */ in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar'\ri\r] /* \\r */ in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' \\i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo='bar' \\69] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo~='bar' i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo^='bar' i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo$='bar' i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo*='bar' i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [foo|='bar' i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [|foo='bar' i] in XML

  ▶ Unexpected subtest result in /selectors/attribute-selectors/attribute-case/syntax.html:
  └ PASS [expected FAIL] [*|foo='bar' i] in XML
```

**Comment by jyc** [comment]
These tests currently pass in Firefox and went from failing to passing in Servo from the change in this commit. In `syntax.html`, the tests that already pass seem to be using `querySelector`, and those that assert that the invalid rules aren't parsed (they appear not to be parsed just because we are using the old `sheet` object).

After this commit, all the tests pass, which corresponds to Firefox's behavior. Going to try removing the expected failures

**Comment by jdm** [comment]
Yes, that's what `PASS [expected FAIL]` means.

**Pull request merged**
