### PR TITLE
Allow script timeouts to be optional and associate timeouts with session state

### PR DESCRIPTION
**Pull request by andreastt**
These changes let WebDriver script timeouts be optional and associated all timeout state with the session. Because the durations are currently associated with the handler which is never reset, they bleed across to any subsequent WebDriver sessions.

See each individual commit for more information.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because _Servo needs more work before it can pass the WPT WebDriver tests_

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15246)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/webdriver_server/lib.rs, line 709 at r2](https://reviewable.io:443/reviews/servo/servo/15246#-KbRFYKjRS0RNxvoYcZs:-KbRFYKk3Pe03Ln6KkAL:b-ad3o33) ([raw file](https://github.com/servo/servo/blob/a2330af11ed490b04e148e44de308af25cdfbc6a/components/webdriver_server/lib.rs#L709)):*
> ```Rust
>             .ok_or(WebDriverError::new(ErrorStatus::SessionNotCreated, "")));
> 
>         // TODO(ato): Conversation is wrong. The script timeout can be null, and the numeric
> ```

You introduced a typo s/conversation/conversion/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15246)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/webdriver_server/lib.rs, line 709 at r2](https://reviewable.io:443/reviews/servo/servo/15246#-KbRFYKjRS0RNxvoYcZs:-KbRI8-OJeMAJjpKytER:b-m552d1) ([raw file](https://github.com/servo/servo/blob/a2330af11ed490b04e148e44de308af25cdfbc6a/components/webdriver_server/lib.rs#L709)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

You introduced a typo s/conversation/conversion/
</blockquote></details>

The conversation truly is wrong! (-:

Anyway, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15246)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15246)*

**Pull request merged**
