### PR TITLE
Get rid of dom::bindings::global

### PR DESCRIPTION
**Pull request by nox**
Globals in that PR are now represented by the fake IDL interface `GlobalScope`.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13596)

### CODE REVIEW

**Comment by nox** [comment]
Cc @jdm @Ms2ger

**Comment by jdm** [comment]
For the record, when I glanced through a few of the first and last commits the other day, I was very much in favour of these changes.

**Comment by nox** [comment]
@jdm To be honest, I was expecting the opposite. Woooo! :D

**Review by Ms2ger — CHANGES_REQUESTED** [review]
LGTM, I guess.

**Comment by Ms2ger** [comment]
@bors-servo delegate+

LGTM assuming only changes were rebasing and fixing my comments.

**Pull request merged**
