### PR TITLE
NCSU Project : Implement private browsing

### PR DESCRIPTION
**Pull request by rajadhva**
Initial Steps : 
We have created the fields and enum as mentioned in the steps 3, 4 and 5. 
Added a method to Constellation that can process the "is this pipeline private" request and send an appropriate reply.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10160)

### CODE REVIEW

**Comment by jdm** [comment]
Good start!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[components/compositing/constellation.rs, line 1505 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDckS8FYx-vyeHLnlcb:-KDckS8FYx-vyeHLnlcc:1010015106) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/compositing/constellation.rs#L1505)):*
This function should either return a boolean or accept a `Sender<bool>` argument and use it, but not both.

---

*[components/compositing/constellation.rs, line 1505 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcmFX0s8FNHLAHNWIy:-KDcmFX0s8FNHLAHNWIz:1424023009) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/compositing/constellation.rs#L1505)):*
We'll need an `#allow(dead_code)` annotation to avoid warnings about unused methods.

---

*[components/compositing/constellation.rs, line 1505 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcmKaibwFNPjtu0S4q:-KDcmKaibwFNPjtu0S4r:-2119132854) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/compositing/constellation.rs#L1505)):*
No need for this to be `&mut self` since it doesn't mutate anything. `&self` is fine.

---

*[components/compositing/constellation.rs, line 1507 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcm0ct9uQTgz1jhbQg:-KDcm0ct9uQTgz1jhbQh:-178198489) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/compositing/constellation.rs#L1507)):*
This doesn't check ancestors. Use the `parent_info` field of `Pipeline` for that.

---

*[components/compositing/pipeline.rs, line 61 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcmVzqOhuuk4MQPVjc:-KDcmVzqOhuuk4MQPVjd:-1216477849) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/compositing/pipeline.rs#L61)):*
`is_private` is fine.

---

*[components/net_traits/lib.rs, line 402 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDco_J0VwqnT9mjcPdx:-KDco_J0VwqnT9mjcPdy:-851645501) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/net_traits/lib.rs#L402)):*
nit: Let's remove this extra newline.

---

*[components/net_traits/lib.rs, line 405 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcocaZgLU0SAZV091p:-KDcocaZgLU0SAZV091q:-257470721) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/net_traits/lib.rs#L405)):*
s/Indicates/Queries/

---

*[components/script/dom/htmliframeelement.rs, line 253 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcoqq6A59abyjNvY1C:-KDcoqq6A59abyjNvY1D:922806425) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/script/dom/htmliframeelement.rs#L253)):*
There's no setting involved; this method only checks for the presence of some attributes.

---

*[components/script/dom/htmliframeelement.rs, line 254 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcok5g5bj-hLBStqh7:-KDcok5g5bj-hLBStqh8:96834070) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/script/dom/htmliframeelement.rs#L254)):*
Let's call this `privatebrowsing`.

---

*[components/script/dom/htmliframeelement.rs, line 260 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcp1goqaJLlpRSwRQF:-KDcp1gpLTLcgCAQLLS3:-322048369) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/script/dom/htmliframeelement.rs#L260)):*
Let's uncomment this, and check `self.Mozbrowser()` instead of mozbrowser_enabled.

---

*[components/script/dom/htmliframeelement.rs, line 470 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcpKZvu8kiM5I-KOLt:-KDcpKZvu8kiM5I-KOLu:-272643375) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/script/dom/htmliframeelement.rs#L470)):*
We can remove this.

---

*[components/script_traits/lib.rs, line 403 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcpMdIiO8X2YhU1WvX:-KDcpMdIiO8X2YhU1WvY:1344135268) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/script_traits/lib.rs#L403)):*
`/// Whether this iframe should be considered private`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10160#-:-KDcpZJO4lWndDKbyAcC:-750456695)*

**Comment by jdm** [comment]
Be sure to address the remaining review comments from previous iterations as well!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/compositing/constellation.rs, line 1519 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10160#-KE1uDunt0cMSg7D45YO:-KE1uDunt0cMSg7D45YP:-927658733) ([raw file](https://github.com/servo/servo/blob/7c77aebc91330c55256531959bad9fd110606b85/components/compositing/constellation.rs#L1519)):*
We could write this more concisely as:
```rust
let mut pipeline_id = Some(pipeline_id);
while let Some(pipeline) = pipeline_id.map(|id| self.pipeline(id)) {
    if pipeline.is_private {
        return true;
    }
    pipeline_id = pipeline.parent_info.map(|(parent_pipeline_id, _) parent_pipeline_id);
}
return false;
```

---

*[components/script/dom/htmliframeelement.rs, line 470 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10160#-KE1v2Xrasg3SoSc-Kkk:-KE1v2XsWVb8GCOKzLgN:-878175629) ([raw file](https://github.com/servo/servo/blob/7c77aebc91330c55256531959bad9fd110606b85/components/script/dom/htmliframeelement.rs#L470)):*
This really doesn't belong here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10160#-:-KE1v6skKGZD_v0HL9hJ:-2125088179)*

**Comment by srm912** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/script/dom/htmliframeelement.rs, line 260 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10160#-KDcp1goqaJLlpRSwRQF:-KE8fyKNpVedb57hULqn:407926868) ([raw file](https://github.com/servo/servo/blob/1770ae46c43a8da5c13528a5f46d94cd038bde71/components/script/dom/htmliframeelement.rs#L260)):*
Checking for the element `mozprivatebrowsing` throws the following error:
/servo/components/script/dom/htmliframeelement.rs:255:42: 255:62 error: no rules expected the token `"mozprivatebrowsing"`
/servo/components/script/dom/htmliframeelement.rs:255             element.has_attribute(&atom!("mozprivatebrowsing"));

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10160)*

**Comment by jdm** [comment]
You can use Atom::from("mozprivatebrowsing") instead of atom! and it should work.

**Comment by jdm** [comment]
Looks good! Only minor comments left; go ahead and [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) the commits together when addressing them so we can merge this quickly :)

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/compositing/constellation.rs, line 1505 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10160#-KEIp131D1wxUM5cfvTi:-KEIp132UXab_Y_tP4ow:1068933138) ([raw file](https://github.com/servo/servo/blob/7c77aebc91330c55256531959bad9fd110606b85/components/compositing/constellation.rs#L1505)):*
If we remove this, we get an annoying warning about unused code when building Servo, right?

---

*[components/compositing/constellation.rs, line 1506 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10160#-KEIpJTtwLHqTFhGqURg:-KEIpJTuhONLoriPwpbJ:426432546) ([raw file](https://github.com/servo/servo/blob/44b736251c73293a234294f29604c96bf3f188c4/components/compositing/constellation.rs#L1506)):*
This seems like it repeats the comment right above the method name.

---

*[components/compositing/constellation.rs, line 1507 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10160#-KEIp9_Ma3hM59mN9Edq:-KEIp9_NbHwFz5-mCvGB:1767662707) ([raw file](https://github.com/servo/servo/blob/44b736251c73293a234294f29604c96bf3f188c4/components/compositing/constellation.rs#L1507)):*
Since there's no Sender involved in this method anymore, this comment doesn't make much sense.

---

*[components/net_traits/lib.rs, line 14 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10160#-KEIpPpNMEdCh4WipVqZ:-KEIpPpNMEdCh4WipVq_:1502773857) ([raw file](https://github.com/servo/servo/blob/dad407479da8084382a262d1e5cdafc78bd778af/components/net_traits/lib.rs#L14)):*
I don't think we want to remove this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10160#-:-KEIpf7DKv4Dyup5uHsZ:-41194213)*

**Comment by srm912** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[components/compositing/constellation.rs, line 1505 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10160#-KEIp131D1wxUM5cfvTi:-KEIvtzKjcWmXLSWqVva:662227728) ([raw file](https://github.com/servo/servo/blob/7c77aebc91330c55256531959bad9fd110606b85/components/compositing/constellation.rs#L1505)):*
Yes it gives an unused code warning. Do I add it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10160)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/compositing/constellation.rs, line 1505 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10160#-KEIp131D1wxUM5cfvTi:-KEIzAKCBub0qVY2Tx6q:677251276) ([raw file](https://github.com/servo/servo/blob/7c77aebc91330c55256531959bad9fd110606b85/components/compositing/constellation.rs#L1505)):*
Yes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10160#-:-KEIzITIV_NKcc3iUtsJ:1057630165)*

**Comment by jdm** [comment]
```
/home/travis/build/servo/servo/components/compositing/constellation.rs:1670:62: 1670:70 error: no method named `pipeline` found for type `&constellation::Constellation<LTF, STF>` in the current scope
/home/travis/build/servo/servo/components/compositing/constellation.rs:1670         while let Some(pipeline) = pipeline_id.map(|id| self.pipeline(id)) {
                                                                                                                                         ^~~~~~~~
```
Sorry, #10082 changed the code so we'll need to use `while let Some(pipeline) = pipeline_id.and_then(self.pipelines.get(&id))` instead.

**Comment by jdm** [comment]
So, I gave you incorrect code that didn't compile. On the other hand, it's a bit disappointing that you didn't try to compile the code before submitting it again :) I've rebased this in #10399 just so we can move the process along a bit quicker.

**Pull request closed without merging**
