### PR TITLE
style: Stop allowing unused_unsafe.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19199)

### CODE REVIEW

**Comment by jdm** [comment]
The atom_macro changes don't work in stable rustc, unfortunately.

**Comment by nox** [comment]
That's because the macro needs more braces.

```rust
macro_rules! atom {
    ("") => { #[allow(unsafe_code)] unsafe { ... } };
}
```


```rust
macro_rules! atom {
    ("") => { { #[allow(unsafe_code)] unsafe { ... } } };
}
```

**Comment by emilio** [comment]
I fixed that up. r? @nox

**Pull request merged**
