### PR TITLE
Re-expose webrender debugger feature in components/servo

### LINKED ISSUE #20324: Expose webrender debugger as a feature in components/servo
Would it be possible to expose a crate feature in components/servo that just re-exposes webrender's debugger?

### PR DESCRIPTION
**Pull request by Moggers**
---

- [x] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
```
Checking files for tidiness...
./Cargo.lock:1: duplicate versions for package `base64`
	The following packages depend on version 0.3.1 from 'crates.io':
		webrender
	The following packages depend on version 0.6.0 from 'crates.io':
		hyper
		net
		script
		webdriver_server
./Cargo.lock:1: duplicate versions for package `bytes`
	The following packages depend on version 0.3.0 from 'crates.io':
		ws
	The following packages depend on version 0.4.6 from 'crates.io':
		ws
./Cargo.lock:1: duplicate versions for package `ws`
	The following packages depend on version 0.6.0 from 'crates.io':
		debugger
	The following packages depend on version 0.7.3 from 'crates.io':
		webrender
./Cargo.lock:1: duplicate versions for package `image`
	The following packages depend on version 0.17.0 from 'crates.io':
		webrender
	The following packages depend on version 0.18.0 from 'crates.io':
		compositing
		net_traits
		script
		webdriver_server
```

What should I do about this?

- [x] These changes fix #20324  (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because: Not sure actually, do I need to write integration tests to make sure it builds with the feature enabled?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20328)

### CODE REVIEW

**Comment by jdm** [comment]
To address that someone needs to update https://github.com/servo/webrender/blob/master/webrender/Cargo.toml#L39 to 0.6.0 and update the version of webrender that's in use in Servo.

**Comment by Moggers** [comment]
I've updated components/debugger ws dependency to 0.7.3.

**Comment by Moggers** [comment]
I've opened an issue for the dependency versions on the webrender repo.

https://github.com/servo/webrender/issues/2538

**Comment by Moggers** [comment]
Test-tidy issue should be resolved now.

**Comment by jdm** [comment]
We're still one revision behind 46b7fb3d58cc89b1c8683524d0829ef266c8b73c in webrender, unfortunately.

**Comment by jdm** [comment]
You'll need to rebase on master, start the build, then commit the changes to Cargo.lock.

**Pull request merged**
