### PR TITLE
Update some URLs.

### PR DESCRIPTION
**Pull request by Ms2ger**
The HTML spec's division into pages is not stable, so it is safer to use the
URL without a specific page (which will redirect).

### CODE REVIEW

**Comment by frewsxcv** [comment]
> The HTML spec's division into pages is not stable

Ah, I wasn't aware of this. Good to know. I updated the wiki to mention this: https://github.com/servo/servo/wiki/Relevant-spec-links

> r? @frewsxcv

I don't have review permissions....yet :)

**Comment by Manishearth** [comment]
> I don't have review permissions....yet :)

It's fine to review stuff on Critic if you think you're capable -- anyone can.

**Pull request merged**
