### PR TITLE
Upgrade wptrunner

### PR DESCRIPTION
**Pull request by jdm**
This should allow us to start running and writing new webdriver tests.

Note, this currently undoes the viewport-related change from #11953. @Manishearth what do you want to do here?

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because our test instrastructure will test it

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12223)

### CODE REVIEW

**Comment by jdm** [comment]
Let's be sure not to merge this until we address the reverted change from #11953.

**Comment by Ms2ger** [comment]
Please reinstate the resolution change; I'll upstream it.

**Comment by jdm** [comment]
Done.

**Comment by Ms2ger** [comment]
r=me unless you want someone else to look at it first

**Comment by jdm** [comment]
I have another branch that's more up to date than this one.

**Pull request closed without merging**
