### PR TITLE
Use Rect::inner_rect from euclid

### PR DESCRIPTION
**Pull request by pyfisch**
Update euclid.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19942)

### CODE REVIEW

**Review by emilio — APPROVED** [review]
Looks great, thanks!

**Comment by emilio** [comment]
There are a couple of tests which are failing the assertions in euclid's inner_rect. All seem to come from `Fragment::stacking_relative_content_box`... Fun

**Comment by pyfisch** [comment]
rebased & fixed

**Review by emilio — APPROVED** [review]
Well, the fix is not removing the stacking_relative_content_box callers, which is a bit unorthodox. I can't think why would that assertion fire, mind explaining if you've debugged it?

Anyway this is great, thanks so much!

**Comment by jdm** [comment]
@bors-servo retry
* #19033

**Pull request merged**
