### PR TITLE
Use a glmemory bufferpool

### LINKED ISSUE #25121: GStreamer plugin wrong memory type
With #25048, the plugin sometimes fails due to receiving regular memory rather than GL memory to fill. This is caused by the plugin not setting up a buffer pool (which in GStreamer is the source's responsibility, not the sink's).

### PR DESCRIPTION
**Pull request by asajeffrey**
This ensures the gstreamer plugin is always using GLMemory.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #25121
- [x] These changes do not require tests because

### CODE REVIEW

**Comment by asajeffrey** [comment]
The first commit is #25048.

**Comment by asajeffrey** [comment]
#25048 has landed, so this is ready for review. r? @ferjm

**Comment by jdm** [comment]
@bors-servo retry
* #24726 #24762

**Pull request merged**
