### PR TITLE
add support for mask_position_parse/serial

### LINKED ISSUE #14955: Implement parsing/serialization for mask-position-{x,y}
The spec doesn't have this yet, neither does MDN. But the syntax is basically identical to `background-position-{x,y}`, so it can share the logic of `background-position`.

Files for `mask-position-{x,y}`: https://github.com/servo/servo/blob/master/components/style/properties/longhand/svg.mako.rs
`mask-position` should become a shorthand and be moved to https://github.com/servo/servo/blob/master/components/style/properties/shorthand/mask.mako.rs in this change.

`background-position-{x,y}` is in https://github.com/servo/servo/blob/master/components/style/properties/longhand/background.mako.rs

### PR DESCRIPTION
**Pull request by mrmiywj**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14955  (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15383)

### CODE REVIEW

**Comment by mrmiywj** [comment]
It is the squashed commits of https://github.com/servo/servo/pull/15092.

**Comment by mrmiywj** [comment]
PTAL @canaltinova

**Comment by canaltinova** [comment]
I don't have a permission for this PR, we need to wait for someone to approve this. Thanks for working on it! It was great amount of work!

Btw, log history in other PR doesn't matter for squash. You could still rebase it and force push it to your branch. This is fine too though.

**Comment by KiChjang** [comment]
Indeed, `git rebase -i` should have allowed you to squash as well, instead of opening a new PR branch. Thanks for working on this!

@bors-servo r=canaltinova

**Comment by canaltinova** [comment]
@bors-servo retry
- #15388

**Pull request merged**
