### PR TITLE
Fix broken env_logger documentation link in HACKING_QUICKSTART

### PR DESCRIPTION
**Pull request by jsanders**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8775)

### CODE REVIEW

**Comment by frewsxcv** [comment]
@jsanders Our build system is struggling with your latest commit for unknown reasons (and is causing our build queue to not get any shorter). Can you `git commit --amend`, `git push -f`, and then reopen this?

**Comment by frewsxcv** [comment]
I just noticed your branch is called `patch-1`, which probably means you used the GitHub editor, which probably means doing the steps in my previous comment is not convenient. If this doesn't get resolved by tomorrow, I'll go ahead and cherry-pick your commit and open a new PR

**Comment by jsanders** [comment]
Weird! Sorry for the trouble, I'll just do a normal PR instead of using the editor (maybe that was the issue?).

**Comment by frewsxcv** [comment]
I merged it in #8794

**Comment by jsanders** [comment]
Oh nice, thanks. Sorry I just now saw this.

**Pull request closed without merging**
