### PR TITLE
Implement AtomicRefCell and use it for layout/style node data

### PR DESCRIPTION
**Pull request by bholley**
See the rationale at https://bugzilla.mozilla.org/show_bug.cgi?id=1305141

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13520)

### CODE REVIEW

**Comment by bholley** [comment]
I split this out of the other style data work I was doing. CC @SminSapin @emilio @heycam @Manishearth @pcwalton

**Comment by emilio** [comment]
Just curious, do you have some numbers before and after this patch series?

Not that I want to prevent its landing (this is awesome indeed), just wondered if it might make sense compile this potentially-unneeded synchronization out in release. Not anything we want to worry about now of course, but just for reference.

**Comment by SimonSapin** [comment]
It is possible to do something similar to `Ref::map` by using [`OwningRef`](https://kimundi.github.io/owning-ref-rs/owning_ref/index.html) with `parking_lot::RwLockReadGuard`. I don’t know if it’s worth it.

**Comment by Manishearth** [comment]
Yeah, I agree that we can handle `Ref::map` in this case too.

Also agree about the numbers. This definitely should be an improvement, but it's good to know how expensive the lock actually was and if future similar optimizations should be done.

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 4 of 4 files at r4, 12 of 12 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/style/atomic_refcell.rs, line 29 at r2](https://reviewable.io:443/reviews/servo/servo/13520#-KSv42LUiXGtE79soEoX:-KSv42LVBZNL193dxwZl:bptcbk3) ([raw file](https://github.com/servo/servo/blob/e1f62be76abf650d793397574bc61cab53eecdc9/components/style/atomic_refcell.rs#L29)):*
> ```Rust
>         AtomicRefCell(RwLock::new(value))
>     }
>     pub fn borrow(&self) -> AtomicRef<T> {
> ```

nit: needs doc comments saying that these panic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/13520#-:-KSv50xTp7Rnz7YZ6Kt0:b-nz51wh)*

**Comment by Manishearth** [comment]
Since this is no longer blocking, do we need to actually wrap `RwLock` here? That contains an extra `pthread_rwlock_t`, which isn't really necessary if you have an `AtomicIsize` field.

That cost should be negligible though, so ease of implementation might make it better to stick to this.

**Comment by bholley** [comment]
> Just curious, do you have some numbers before and after this patch series?

No, pcwalton and I decided it wasn't worth the trouble to do right now, since ReleaseAcquire atomic operations cost the same as Relaxed operations on x86, and we do relaxed operations all over the place without worrying too much about it (i.e. Arc refcounting).

We can profile this once we get our incremental restyle architecture more settled, and optimize things as needed. I've got a lot of code in my queue that I want to keep getting into the pipe.

> just wondered if it might make sense compile this potentially-unneeded synchronization out in release

There is no synchronization - it's just an atomic refcount: https://github.com/Amanieu/parking_lot/blob/152907087a4feedb350f915b0e779414ab030414/src/raw_rwlock.rs#L28


> Since this is no longer blocking, do we need to actually wrap RwLock here? That
> contains an extra pthread_rwlock_t, which isn't really necessary if you have an AtomicIsize field.

No it doesn't - it's just an AtomicUsize. That's the whole reason for using parking_lot here.

**Comment by Manishearth** [comment]
> No it doesn't - it's just an AtomicUsize. That's the whole reason for using parking_lot here.

Yeah, deleted the comment immediately after posting because I realized this 😄

**Comment by emilio** [comment]
This looks good to me, since the extra atomic increments seem to be an accepted cost. Please rename `ArcRefCell` to `AtomicRefCell` in the commit descriptions, then r=me.

**Comment by bholley** [comment]
Thanks!

I didn't know about owning_ref - it does indeed look like exactly what I was looking for, but I think it's probably not worth the hour or so it would take me to rework these patches to use OwningRef<_, Arc<T>> rather than returning Arc<T> directly. I'll introduce OwningRef machinery to AtomicRefCell if we end up needing it.

@bors-servo r=emilio

**Pull request merged**
