### PR TITLE
Add basic unit test for `preload_hsts_domains`.

### LINKED ISSUE #6789: Add a unit test that ensures that hsts_preload.json can be decoded and is non-empty
This should be a new test added to `tests/unit/net/hsts.rs` that calls `preload_hsts_domains` from `components/net/hsts.rs` and checks the return value.

### PR DESCRIPTION
**Pull request by notriddle**
Closes #6789.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6793)

### CODE REVIEW

**Comment by jdm** [comment]
Thanks! Have you checked that the test fails if you add invalid JSON to the file?

**Comment by notriddle** [comment]
Just did, and it fails right.

**Comment by jdm** [comment]
@bors-servo: r+
Fantastic!

**Comment by jdm** [comment]
@bors-servo: retry
* #6818

**Pull request merged**
