### PR TITLE
Implement CSS Transition Events

### PR DESCRIPTION
**Pull request by saurvs**
Fixes https://github.com/servo/servo/issues/10245

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10393)

### CODE REVIEW

**Comment by jdm** [comment]
This is part #10245, but the most important part of that issue is actually dispatching the events when transitions complete. I'm not sure that we should implement the interface until we actually use it.

**Comment by saurvs** [comment]
Should the dispatching be done from the `update_animation_state` function in `components/layout/animation.rs` ?

**Comment by jdm** [comment]
@saurvs Are you planning to implement the logic for dispatching the events as well?

**Comment by jdm** [comment]
Closing due to lack of response. Feel free to reopen if you decide to keep working on it!

**Comment by saurvs** [comment]
@jdm I am so sorry I didn't check back to see if I replied. I honetly had comnented something along the lines that I'd like to work on it but it would take time as I was not familiar with the parts of the code that needed to be modified; I think my internet connection timedout out after I hit the comment button and it never got sent. I'm sorry again for not checking.

**Comment by jdm** [comment]
Ok, no problem. I'll mark the issue as assigned to you again, in that case.

**Pull request closed without merging**
