### PR TITLE
Implement <template>

### PR DESCRIPTION
**Pull request by nox**
All tests using iframes can't currently pass, same for innerHTML-related tests with <template> elements. The latter contradicts the spec, see the links below.

Apart from this, they work, AFAICT.

https://github.com/servo/html5ever/issues/164
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27314

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7531)

### CODE REVIEW

**Comment by nox** [comment]
Cc @Manishearth

**Comment by nox** [comment]
I fixed the innerHTML bugs following https://github.com/w3c/DOM-Parsing/issues/1.

**Comment by Ms2ger** [comment]
Reviewed 2 of 2 files at r1, 19 of 19 files at r2, 15 of 15 files at r3, 9 of 12 files at r4.
Review status: 23 of 26 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmltemplateelement.rs, line 57 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7531#-JyNFsDc5tEGLm6xoEY5)** ([raw file](https://github.com/servo/servo/blob/c1f6e3f1b1504cfa4b63d706312132236986e773/components/script/dom/htmltemplateelement.rs#L57)):</sup>
I think this is wrong. Consider
```js
var doc1, doc2;
var templateA = doc1.createElement("template");
var templateB = doc1.createElement("template");
doc2.adoptNode(templateA)
assert_equals(templateA.content.ownerDocument, templateB.content.ownerDocument);
```
and I suspect there's a bug with the temporary document used for fragment parsing too.

Oh, hm, the spec handles this.

---

<sup>**[components/script/dom/htmltemplateelement.rs, line 72 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7531#-JyNLsl3AyruHRrojzTn)** ([raw file](https://github.com/servo/servo/blob/4ea53c7895e6cf45e0d257338ca37d12f5a03ac3/components/script/dom/htmltemplateelement.rs#L72)):</sup>
Link to <ttps://html.spec.whatwg.org/multipage/#template-adopting-steps> (which will be added momentarily).

---

<sup>**[components/script/dom/node.rs, line 1426 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7531#-JyNBW4q6ugIuppq_w9b)** ([raw file](https://github.com/servo/servo/blob/1c1c0a569e7551a85719d7dee97947476a980174/components/script/dom/node.rs#L1426)):</sup>
It's really scary to have unsuspecting code running while nodes in the same tree have different node documents.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7531)

**Comment by nox** [comment]
@Ms2ger I put back the merged loops in Node::adopt(), because that's how I specified how adopting steps should be run in https://github.com/whatwg/dom/pull/66. If you really want me to split them, and I don't think it's necessary given there is only one use of them in HTML for template, I would like the spec to be changed to two loops first.

**Comment by Ms2ger** [comment]
I do really want you to split them.

**Comment by nox** [comment]
@Ms2ger Done and reported upstream. https://github.com/whatwg/dom/pull/71

**Comment by nox** [comment]
@Ms2ger I find that quite pointless though, bind_to_tree and unbind_to_tree do the exact same thing.

**Comment by Ms2ger** [comment]
You didn't split them.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 12 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7531)

**Comment by nox** [comment]
@Ms2ger Oops, forgot to push.

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/node.rs, line 1429 \[r6\]](https://reviewable.io:443/reviews/servo/servo/7531#-Jyfql6RZiapTptnukmn)** ([raw file](https://github.com/servo/servo/blob/88ec69ddd52918e286ca501641f565901e861a97/components/script/dom/node.rs#L1429)):</sup>
We probably don't want to call this if the document didn't change.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7531)

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[components/script/dom/htmltemplateelement.rs, line 60 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7531#-JyNFsDc5tEGLm6xoEY5)** ([raw file](https://github.com/servo/servo/blob/c1f6e3f1b1504cfa4b63d706312132236986e773/components/script/dom/htmltemplateelement.rs#L60)):</sup>
It's correct thanks to the adopting steps.

---

<sup>**[components/script/dom/node.rs, line 1429 \[r6\]](https://reviewable.io:443/reviews/servo/servo/7531#-Jyfql6RZiapTptnukmn)** ([raw file](https://github.com/servo/servo/blob/88ec69ddd52918e286ca501641f565901e861a97/components/script/dom/node.rs#L1429)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7531)

**Comment by Ms2ger** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7531)

**Comment by nox** [comment]
@bors-servo r=Ms2ger

Fixed test expectations.

**Comment by nox** [comment]
@bors-servo retry

#7422

**Pull request merged**
