### PR TITLE
Split doc generation into its own task

### PR DESCRIPTION
**Pull request by SimonSapin**
This task reached its 60 minutes timeout in
https://community-tc.services.mozilla.com/tasks/YByC2V7uQq2lQv40TVi5KQ/runs/1/logs/live/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FYByC2V7uQq2lQv40TVi5KQ%2Fruns%2F1%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L6276

### CODE REVIEW

**Comment by SimonSapin** [comment]
No need to force, I’ve rebased #24681 on top of this

**Comment by jdm** [comment]
I noticed that too late, unfortunately.

**Pull request merged**
