### PR TITLE
Properly sign UWP package

### LINKED ISSUE #25362: Can't install UWP Nightly because of missing certificate
Sideloading is not possible without manually installing the certificate.
Probably regressed by #25309: https://github.com/servo/servo/commit/b3d0388d83f883954b9165ef378a46fb3226bb4f#diff-99c45e2e6d2483a397f820708c4398eeR12
(`AppxPackageSigningEnabled=false`).

last good: https://servo-builds.s3.dualstack.us-west-2.amazonaws.com/nightly/uwp/2019-12-16T09:10:08Z-ServoApp_1.0.0.0_Test.zip
first bad: https://servo-builds.s3.dualstack.us-west-2.amazonaws.com/nightly/uwp/2019-12-17T09:09:58Z-ServoApp_1.0.0.0_Test.zip

### PR DESCRIPTION
**Pull request by paulrouget**
Supersede #25661
Fix #25362

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #25362 (GitHub issue number if applicable)

### CODE REVIEW

**Comment by paulrouget** [comment]
I've downloaded the artifact and I can install it.

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* #24622

**Comment by jdm** [comment]
@bors-servo retry
* #25522

**Pull request merged**
