### PR TITLE
Keep same timestamp when replacing frame state

### PR DESCRIPTION
**Pull request by cbrewster**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14664)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
Any ideas for a way to write a test for this? @asajeffrey

**Comment by asajeffrey** [comment]
A test would be in an iframe, load docs A then B then C, then go back, refresh, go back, go forwards. You should end up at B, but if the jsh order is messed up, you'll end up at C.

**Comment by cbrewster** [comment]
Superseded by #14312

**Comment by asajeffrey** [comment]
Might be worth doing this anyway a) because #14312 isn't the easiest PR to land, and b) to add a test.

**Pull request closed without merging**
