### PR TITLE
Update bootstrap.py to support Ubuntu 22.04

### PR DESCRIPTION
**Pull request by sagudev**

### CODE REVIEW

**Comment by jdm** [comment]
Error syncing changes upstream. Logs saved in error-snapshot-1661595719458.

**Comment by sagudev** [comment]
> Error syncing changes upstream. Logs saved in error-snapshot-1661595719458.

Er, what?

**Comment by jdm** [comment]
That happens every time there's an empty PR description.

**Comment by jdm** [comment]
Error syncing changes upstream. Logs saved in error-snapshot-1661613513908.

**Pull request merged**
