### PR TITLE
Revert "Update glutin"

### PR DESCRIPTION
**Pull request by notriddle**
This reverts commit ff7524af0940ed841f3344f5dd78f6c1751cfd42. [It breaks stuff](https://gist.github.com/notriddle/3c0dff9b4dc3a1a7b82f)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9115)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Hi. Reverting a commit that breaks stuff is fair enough, but as that commit’s author I would have appreciated hearing about it so that I could look into the underlying issue. A comment in the PR that introduced that commit would have been fine. Thanks!

**Comment by larsbergstrom** [comment]
@SimonSapin Sorry about that! Will do in the future. We were kinda in "omg all the linux is broken" panic mode in #servo and I failed to close the loop there.

**Comment by SimonSapin** [comment]
No worries. Interesting that the update landed in the first place if it was so broken. Maybe that X11 error only occurs in some environments? I’ve filed https://github.com/tomaka/glutin/issues/697 by the way.

**Pull request merged**
