### PR TITLE
Update WR (optimizations, local clip rect).

### PR DESCRIPTION
**Pull request by glennw**
* PBO optimization for GPU cache updates.
* Alpha rectangle optimizations.
* Local clip rect improvements.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17420)

### CODE REVIEW

**Comment by glennw** [comment]
@bors-servo retry
 * infra exception

**Comment by glennw** [comment]
@bors-servo 
 * Mac builders seem broken, trying once more.

**Comment by glennw** [comment]
Updated test expectations with a new PASS.

@bors-servo try

**Comment by jdm** [comment]
r=me when tests pass.

**Pull request merged**
