### PR TITLE
fix for Layout memory reporter uses pre-redirect url

### LINKED ISSUE #6872: Layout memory reporter uses pre-redirect url
For example, if I look at the output for http://google.com the script reporter says "url(https://www.google.ca/?gfe_rd=cr&ei=kqK7Va3eD-eM8Qeyo4PwBQ)" while layout says "url(http://google.com/)".

### PR DESCRIPTION
**Pull request by KiChjang**
Rebase of #7612.

Fixes #6872.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8903)

### CODE REVIEW

**Comment by nox** [comment]
Apart from my question to @jdm, this looks good and I'll r+ if he is OK with this patch.

-S-awaiting-review +S-awaiting-answer 

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/layout/layout_task.rs, line 123 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8903#-K5BPIUbbh-XIF3SQPWU:-K5BPIUbbh-XIF3SQPWV:1463328850) ([raw file](https://github.com/servo/servo/blob/2ee446de5d987c911f91dafa499d8a9f7df61995/components/layout/layout_task.rs#L123)):*
@jdm wanted an `Option<Url>` inside here, and an initial value of `None`,  because the document URL should be set only once (in Layout), did that change? @jdm, care to chime in?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8903#-:-K5BPXEpEvbiPClK-hsj:183681656)*

**Comment by jdm** [comment]
I think this solution is ok. We can change it later if it turns out it causes problems or is confusing.

**Pull request merged**
