### PR TITLE
Make Tidy check ports/cef and ports/glutin

### LINKED ISSUE #5034: Make tidy check ports/gonk and ports/glutin
Code: python/tidy.py

### PR DESCRIPTION
**Pull request by psdh**
Fixes #5034

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Does running `./mach test-tidy` report any errors with your changes? I would expect that many of the files in ports/cef have, for example, trailing whitespace that needs to be fixed.

**Comment by psdh** [comment]
Fixing those errors in #5044

**Comment by jdm** [comment]
Let's check ports/glutin and ports/gonk, but ignore ports/cef.

**Comment by metajack** [comment]
Assigning to @kmcallister to figure out next steps.

**Pull request closed without merging**
