### PR TITLE
Move util::range into its own crate

### LINKED ISSUE #9695: Move util::range to gfx
Files:
 * components/gfx/display_list/mod.rs
 * components/gfx/paint_context.rs
 * components/gfx/lib.rs
 * components/gfx/text/glyph.rs
 * components/gfx/text/shaping/harfbuzz.rs
 * components/gfx/text/text_run.rs
 * components/layout/display_list_builder.rs
 * components/layout/fragment.rs
 * components/layout/inline.rs
 * components/layout/lib.rs
 * components/layout/text.rs
 * components/util/lib.rs
 * components/util/range.rs

### PR DESCRIPTION
**Pull request by schuster**
Fixes #9695

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9717)

### CODE REVIEW

**Comment by schuster** [comment]
I'm not sure how to interpret this test failure - is the problem that Cargo.lock changed? I think that's expected in this case, right?

**Comment by jdm** [comment]
@schuster: we have multiple Cargo.lock files that need to be changed simultaneously. `./mach build-cef` and `GONKDIR=/tmp ./mach build-gonk`will cause them to be updated appropriately.

**Comment by nox** [comment]
No need to build these. Just run `./mach cargo-update -p gfx -p layout`.

**Comment by nox** [comment]
Please squash.

**Comment by schuster** [comment]
Oops, sorry. I'll take a look at what's going wrong and fix it.

**Comment by KiChjang** [comment]
@schuster You most probably need a rebase, and everything should work fine.

**Comment by jdm** [comment]
```
cargo build -v

    Updating registry `https://github.com/rust-lang/crates.io-index`

    Updating git repository `https://github.com/glennw/webrender_traits`

    Updating git repository `https://github.com/servo/ipc-channel`

    Updating git repository `https://github.com/glennw/webrender`

    Updating git repository `https://github.com/ecoal95/rust-offscreen-rendering-context`

    Updating git repository `https://github.com/servo/rust-layers`

    Updating git repository `https://github.com/servo/gaol`

    Updating git repository `https://github.com/TyOverby/bincode`

    Updating git repository `https://github.com/Manishearth/rust-tenacious`

    Updating git repository `https://github.com/servo/rust-azure`

    Updating git repository `https://github.com/servo/rust-freetype`

    Updating git repository `https://github.com/Ygg01/xml5ever`

    Updating git repository `https://github.com/servo/rust-mozjs`

    Updating git repository `https://github.com/ecoal95/angle`

    Updating git repository `https://github.com/servo/mozjs`

    Updating git repository `https://github.com/huonw/simd`

failed to select a version for `heapsize` (required by `range`):

all possible versions conflict with previously selected versions of `heapsize`

  version 0.3.3 in use by heapsize v0.3.3

  possible versions to select: 0.3.0
```
Run `./mach update-cargo -p heapsize` and it should be good.

**Comment by Ms2ger** [comment]
@schuster hey, any chance you'd have time to finish this?

**Comment by schuster** [comment]
I think some of you have seen me on IRC today, so yes, I am trying to finish this. Just running into some issues with cargo (probably my own misunderstanding, not real bugs). I'm going to sit down and finish it tonight.

**Comment by Wafflespeanut** [comment]
Good to know :)

**Comment by schuster** [comment]
Ok, this push should do it (currently waiting on the Travis build). I think I ran into an instance of #2090 (thanks to @mbrubeck for referring me to it), but I was able to work around it.

**Comment by frewsxcv** [comment]
Thanks!

**Comment by jdm** [comment]
@bors-servo: retry
* #8120

**Pull request merged**
