### PR TITLE
Bump various FFI crates to get jobserver support

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18939)

### CODE REVIEW

**Comment by jdm** [comment]
I predict this will hit the same problem as #18821.

**Comment by nox** [comment]
I removed `backtrace-sys` which fails in #18821 already.

@bors-servo r=jdm

**Comment by nox** [comment]
```
command timed out: 1200 seconds without output running ['env', 'PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig', './mach', 'build', '--release'], attempting to kill
```

What

**Pull request merged**
