### PR TITLE
Support WebAudio on Windows

### LINKED ISSUE #23631: Windows GStreamer DLL packaging needs to include more plugins
From an email with friends at Centricular:
```
> https://github.com/servo/servo/blob/8e783577d24cac2983fbea1b46d5452ffa5fb44f/python/servo/build_commands.py#L737-L759
>

That lists all the libraries that Servo links to, but it doesn't list
the plugins that are loaded at runtime. For UWP you'll need to add
those as assets alongside the libraries. I grepped the servo/media
source:

grep -rie gst::ElementFactory::make * | sed -ne 's/.*gst::ElementFactory::make("\([^"]*\)".*/\1/p' | sort | uniq

This yielded the following elements:

appsink
appsrc
audioconvert
audioresample
audiotestsrc
autoaudiosink
capsfilter
decodebin
deinterleave
glsinkbin
opusenc
proxysink
proxysrc
queue
rtpopuspay
rtpvp8pay
videoconvert
videotestsrc
vp8enc
webrtcbin

These correspond to the following plugins:

gstapp
gstaudioconvert
gstaudioresample
gstaudiotestsrc
gstautodetect
gstcoreelements
gstplayback
gstinterleave
gstopengl
gstopus (*)
gstproxy
gstrtp
gstvideoconvert
gstvideotestsrc
gstvpx (*)
gstwebrtc (*)
```
And:
```
I forgot to mention another thing: autovideosink, autoaudiosink
(gstautodetect), and decodebin (gstplayback) will autodetect which
elements can / should be used for the pipeline and load them
dynamically. So you'll also need at least wasapisink (gstwasapi),
glimagesink (gstopengl) and avdec_{h264,vp8,aac,opus,*} (gstlibav). 
```

### LINKED ISSUE #23698: webaudio doesn't work in UWP
https://www.joshmatthews.net/osc.html doesn't play anything in the servo UWP app with a stock build. There are some suspicious exceptions reported in the VS output window, but the app continues running. I'm going to see if there's any change when using the binaries from the UWP port of gstreamer.

### PR DESCRIPTION
**Pull request by jdm**
These changes improve the GStreamer experience on Windows in several ways:
* we package the set of plugins and their dependencies that Servo requires for media support
* we explicitly load those plugins when starting the media engine rather than relying on an existing gstreamer installation

These changes do not affect the experience on non-Windows platforms, but the path is clear to do so in order to fix problems like #23519. With these changes I can successfully hear a tone when loading https://joshmatthews.net/osc.html in both a desktop build and a UWP build.

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23631 and fix #23698
- [x] These changes do not require tests because no tests on windows ;_;

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23712)

### CODE REVIEW

**Comment by jdm** [comment]
These changes depend on https://github.com/servo/media/pull/274, but they are blocked on updating the script/media integration after https://github.com/servo/media/pull/271.

r? @ferjm

**Review by ferjm — APPROVED** [review]
I opened #23714 for the media update.

r=me once that one is merged.

Thanks!

**Comment by jdm** [comment]
Needs some fix for x86 windows packaging:
```
Packaging gstreamer DLLs
ERROR: could not find required GStreamer DLL: bz2.dll
ERROR: could not find required GStreamer DLL: ffi-7.dll
ERROR: could not find required GStreamer DLL: gio-2.0-0.dll
ERROR: could not find required GStreamer DLL: glib-2.0-0.dll
ERROR: could not find required GStreamer DLL: gmodule-2.0-0.dll
ERROR: could not find required GStreamer DLL: gobject-2.0-0.dll
ERROR: could not find required GStreamer DLL: graphene-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstapp-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstaudio-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstbase-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstcodecparsers-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstcontroller-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstfft-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstgl-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstpbutils-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstplayer-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstreamer-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstriff-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstrtp-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstsctp-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstsdp-1.0-0.dll
ERROR: could not find required GStreamer DLL: gsttag-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstvideo-1.0-0.dll
ERROR: could not find required GStreamer DLL: gstwebrtc-1.0-0.dll
ERROR: could not find required GStreamer DLL: intl-8.dll
ERROR: could not find required GStreamer DLL: nice-10.dll
ERROR: could not find required GStreamer DLL: orc-0.4-0.dll
ERROR: could not find required GStreamer DLL: z-1.dll
```

**Comment by jdm** [comment]
Yikes, the x86 mingw DLLs have different names. I thought that was just something that changed from previous gstreamer versions:
```
avcodec-58.dll				libgstphotography-1.0-0.dll
avfilter-7.dll				libgstplayer-1.0-0.dll
avformat-58.dll				libgstreamer-1.0-0.dll
avutil-56.dll				libgstriff-1.0-0.dll
gdbus.exe				libgstrtp-1.0-0.dll
gdk-pixbuf-csource.exe			libgstrtsp-1.0-0.dll
gdk-pixbuf-query-loaders.exe		libgstrtspserver-1.0-0.dll
ges-launch-1.0.exe			libgstsctp-1.0-0.dll
gio-querymodules.exe			libgstsdp-1.0-0.dll
glib-compile-schemas.exe		libgsttag-1.0-0.dll
gsettings.exe				libgsturidownloader-1.0-0.dll
gst-device-monitor-1.0.exe		libgstvalidate-1.0-0.dll
gst-discoverer-1.0.exe			libgstvideo-1.0-0.dll
gst-inspect-1.0.exe			libgstwebrtc-1.0-0.dll
gst-launch-1.0.exe			libgthread-2.0-0.dll
gst-play-1.0.exe			libharfbuzz-0.dll
gst-shell				libhogweed-4.dll
gst-typefind-1.0.exe			libintl-8.dll
gst-validate-1.0.exe			libjpeg-8.dll
gst-validate-launcher			libjson-glib-1.0-0.dll
gst-validate-media-check-1.0.exe	libkate-1.dll
gst-validate-rtsp-server-1.0.exe	libmms-0.dll
gst-validate-transcoding-1.0.exe	libmp3lame-0.dll
json-glib-format.exe			libmpg123-0.dll
json-glib-validate.exe			libnettle-6.dll
libFLAC-8.dll				libnice-10.dll
libSoundTouch-1.dll			libogg-0.dll
liba52-0.dll				liboggkate-1.dll
libass-9.dll				libopencore-amrnb-0.dll
libbz2.dll				libopencore-amrwb-0.dll
libcairo-2.dll				libopenh264.dll
libcairo-gobject-2.dll			libopenjp2.dll
libcairo-script-interpreter-2.dll	libopus-0.dll
libcroco-0.6-3.dll			liborc-0.4-0.dll
libcrypto-1_1.dll			liborc-test-0.4-0.dll
libdca-0.dll				libpango-1.0-0.dll
libdv-4.dll				libpangocairo-1.0-0.dll
libdvdnav-4.dll				libpangoft2-1.0-0.dll
libdvdread-4.dll			libpangowin32-1.0-0.dll
libexpat-1.dll				libpixman-1-0.dll
libffi-7.dll				libpng16-16.dll
libfontconfig-1.dll			librsvg-2-2.dll
libfreetype-6.dll			librtmp-1.dll
libfribidi-0.dll			libsbc-1.dll
libgcc_s_sjlj-1.dll			libsoup-2.4-1.dll
libgdk_pixbuf-2.0-0.dll			libspandsp-2.dll
libges-1.0-0.dll			libspeex-1.dll
libgio-2.0-0.dll			libsrt.dll
libglib-2.0-0.dll			libsrtp.dll
libgmodule-2.0-0.dll			libssl-1_1.dll
libgmp-10.dll				libstdc++-6.dll
libgnutls-30.dll			libtag.dll
libgnutlsxx-28.dll			libtasn1-6.dll
libgobject-2.0-0.dll			libtheora-0.dll
libgomp-1.dll				libtheoradec-1.dll
libgraphene-1.0-0.dll			libtheoraenc-1.dll
libgstadaptivedemux-1.0-0.dll		libtiff-5.dll
libgstallocators-1.0-0.dll		libtiff-5.dll.duplicate1
libgstapp-1.0-0.dll			libturbojpeg-0.dll
libgstaudio-1.0-0.dll			libusrsctp-1.dll
libgstbadaudio-1.0-0.dll		libvisual-0.4-0.dll
libgstbase-1.0-0.dll			libvo-aacenc-0.dll
libgstbasecamerabinsrc-1.0-0.dll	libvorbis-0.dll
libgstcheck-1.0-0.dll			libvorbisenc-2.dll
libgstcodecparsers-1.0-0.dll		libvorbisfile-3.dll
libgstcontroller-1.0-0.dll		libwavpack-1.dll
libgstfft-1.0-0.dll			libwebrtc_audio_processing-0.dll
libgstgl-1.0-0.dll			libwinpthread-1.dll
libgstinsertbin-1.0-0.dll		libx264-148.dll
libgstisoff-1.0-0.dll			libxml2-2.dll
libgstmpegts-1.0-0.dll			libz-1.dll
libgstnet-1.0-0.dll			swresample-3.dll
libgstpbutils-1.0-0.dll
```

**Comment by jdm** [comment]
Same with the plugin DLLs:
```
libgsta52dec.dll		libgstlibvisual.dll
libgstaccurip.dll		libgstmatroska.dll
libgstadder.dll			libgstmidi.dll
libgstadpcmdec.dll		libgstmms.dll
libgstadpcmenc.dll		libgstmpegpsdemux.dll
libgstaiff.dll			libgstmpegpsmux.dll
libgstalaw.dll			libgstmpegtsdemux.dll
libgstalpha.dll			libgstmpegtsmux.dll
libgstalphacolor.dll		libgstmpg123.dll
libgstamrnb.dll			libgstmulaw.dll
libgstamrwbdec.dll		libgstmultifile.dll
libgstapetag.dll		libgstmultipart.dll
libgstapp.dll			libgstmxf.dll
libgstasf.dll			libgstnetsim.dll
libgstasfmux.dll		libgstnice.dll
libgstassrender.dll		libgstnle.dll
libgstaudiobuffersplit.dll	libgstogg.dll
libgstaudioconvert.dll		libgstopengl.dll
libgstaudiofx.dll		libgstopenh264.dll
libgstaudiofxbad.dll		libgstopenjpeg.dll
libgstaudiolatency.dll		libgstopus.dll
libgstaudiomixer.dll		libgstopusparse.dll
libgstaudiomixmatrix.dll	libgstoverlaycomposition.dll
libgstaudioparsers.dll		libgstpango.dll
libgstaudiorate.dll		libgstpcapparse.dll
libgstaudioresample.dll		libgstplayback.dll
libgstaudiotestsrc.dll		libgstpng.dll
libgstaudiovisualizers.dll	libgstpnm.dll
libgstauparse.dll		libgstproxy.dll
libgstautoconvert.dll		libgstrawparse.dll
libgstautodetect.dll		libgstrealmedia.dll
libgstavi.dll			libgstremovesilence.dll
libgstbayer.dll			libgstreplaygain.dll
libgstbz2.dll			libgstresindvd.dll
libgstcairo.dll			libgstrfbsrc.dll
libgstcamerabin.dll		libgstrsvg.dll
libgstclosedcaption.dll		libgstrtmp.dll
libgstcoloreffects.dll		libgstrtp.dll
libgstcompositor.dll		libgstrtpmanager.dll
libgstcoreelements.dll		libgstrtsp.dll
libgstcoretracers.dll		libgstrtspclientsink.dll
libgstcutter.dll		libgstsbc.dll
libgstd3d.dll			libgstsctp.dll
libgstdashdemux.dll		libgstsdpelem.dll
libgstdebug.dll			libgstsegmentclip.dll
libgstdebugutilsbad.dll		libgstshapewipe.dll
libgstdecklink.dll		libgstsiren.dll
libgstdeinterlace.dll		libgstsmooth.dll
libgstdirectsound.dll		libgstsmoothstreaming.dll
libgstdirectsoundsrc.dll	libgstsmpte.dll
libgstdtls.dll			libgstsoundtouch.dll
libgstdtmf.dll			libgstsoup.dll
libgstdtsdec.dll		libgstspandsp.dll
libgstdv.dll			libgstspectrum.dll
libgstdvbsuboverlay.dll		libgstspeed.dll
libgstdvdlpcmdec.dll		libgstspeex.dll
libgstdvdread.dll		libgstsrt.dll
libgstdvdspu.dll		libgstsrtp.dll
libgstdvdsub.dll		libgstsubenc.dll
libgsteffectv.dll		libgstsubparse.dll
libgstencoding.dll		libgsttaglib.dll
libgstequalizer.dll		libgsttcp.dll
libgstfieldanalysis.dll		libgsttheora.dll
libgstflac.dll			libgsttimecode.dll
libgstflv.dll			libgsttypefindfunctions.dll
libgstflxdec.dll		libgstudp.dll
libgstfreeverb.dll		libgstvideobox.dll
libgstfrei0r.dll		libgstvideoconvert.dll
libgstgaudieffects.dll		libgstvideocrop.dll
libgstgdkpixbuf.dll		libgstvideofilter.dll
libgstgdp.dll			libgstvideofiltersbad.dll
libgstgeometrictransform.dll	libgstvideoframe_audiolevel.dll
libgstges.dll			libgstvideomixer.dll
libgstgio.dll			libgstvideoparsersbad.dll
libgstgoom.dll			libgstvideorate.dll
libgstgoom2k1.dll		libgstvideoscale.dll
libgsthls.dll			libgstvideotestsrc.dll
libgsticydemux.dll		libgstvoaacenc.dll
libgstid3demux.dll		libgstvolume.dll
libgstid3tag.dll		libgstvorbis.dll
libgstimagefreeze.dll		libgstvpx.dll
libgstinter.dll			libgstwasapi.dll
libgstinterlace.dll		libgstwavenc.dll
libgstinterleave.dll		libgstwavpack.dll
libgstisomp4.dll		libgstwavparse.dll
libgstivtc.dll			libgstwebrtc.dll
libgstjpeg.dll			libgstwebrtcdsp.dll
libgstjpegformat.dll		libgstwinks.dll
libgstkate.dll			libgstwinscreencap.dll
libgstladspa.dll		libgstx264.dll
libgstlame.dll			libgstxingmux.dll
libgstlegacyrawparse.dll	libgsty4mdec.dll
libgstlevel.dll			libgsty4menc.dll
libgstlibav.dll
```

**Comment by jdm** [comment]
I'm going to remove the x86 windows build rather than try to accommodate this - I originally added it as an easy test for Windows cross-compilation and under the assumption that the HoloLens 2 emulator would only run x86, but that was incorrect. Since we now have Windows arm64 cross-compilation on CI, the x86 build does not serve a useful purpose.

**Pull request merged**
