### PR TITLE
Implement the "progressevent" argument to Document::createEvent

### PR DESCRIPTION
**Pull request by ziyunli**
Fixes https://github.com/servo/servo/issues/10740

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10844)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Thanks! @bors-servo r+

**Comment by frewsxcv** [comment]
https://github.com/w3c/web-platform-tests/pull/2897

For now, just mark that test as failing. If you need help doing that, let me know.

**Comment by sliz1** [comment]
@frewsxcv hopefully I get this right https://github.com/servo/servo/pull/10844/commits/889579c6ded1e019576a9203fd933466a2bced1c#diff-22b597d596193bd83d76037987389809R1 :D

**Comment by frewsxcv** [comment]
Looks great, thanks!

@bors-servo r+

**Pull request merged**
