### PR TITLE
Use the ParserContext along with the Parser

### PR DESCRIPTION
**Pull request by ghost**
This changes the `parse` function's signature to include `ParserContext`, so that we don't introduce another trait just for the sake of the context. Instead, we can safely ignore the context whenever we don't need it.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] These changes do not require tests because it's a refactor

r? @SimonSapin or @emilio or @Manishearth

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14373)

### CODE REVIEW

**Comment by emilio** [comment]
Looks good I guess, I'm kind of sad to see all those `_context` arguments, but I think it's good to be consistent, and arguably the approach I described over in #14370 is slightly harder to reason about.

@bors-servo r+

**Comment by Wafflespeanut** [comment]
Thanks! :)

**Comment by Wafflespeanut** [comment]
@bors-servo r-

Oops. I've missed something.

**Comment by Wafflespeanut** [comment]
Forgot to update the tests...

    error: aborting due to 472 previous errors

**Comment by emilio** [comment]
Heh, good luck with those, most should be from macros so shouldn't be that much, hopefully.

r=me when those are fixed.

**Comment by Manishearth** [comment]
I don't really agree with this. It's pretty easy to introduce two traits where one trait delegates to another when there's no context.

But it's fine, I guess.

**Comment by Wafflespeanut** [comment]
> I don't really agree with this. It's pretty easy to introduce two traits where one trait delegates to another when there's no context.

Yes, that's what @emilio [had suggested](https://github.com/servo/servo/pull/14370#discussion_r89668608) earlier. I thought it'd be better to have an unused argument in the function instead of introducing another trait. We're complicating things by introducing more things, which could otherwise be solved by a refactor.

**Comment by Wafflespeanut** [comment]
Looks like the latest merge has affected my PR. Hmph.

**Pull request merged**
