### PR TITLE
Update WR (minimal use of new transaction API).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19814)

### CODE REVIEW

**Comment by glennw** [comment]
r? @jdm or @emilio 

The non-transaction API in WR is deprecated and removed. So even though we're not actually using transactions properly in Servo, we need to wrap up WR API calls in a transaction now.

**Review by emilio — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* #19818

**Comment by jdm** [comment]
@bors-servo treeclosed+
Just controlling some variables to help clean up our CI.

**Pull request merged**
