### PR TITLE
Add missing `Expose=Window` IDL attribute on `HTMLCollection`.

### PR DESCRIPTION
**Pull request by frewsxcv**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14029)

### CODE REVIEW

**Comment by KiChjang** [comment]
#12415

**Comment by jdm** [comment]
This is the default, isn't it?

**Comment by KiChjang** [comment]
Yes, according to Ms2ger's [comment](https://github.com/servo/servo/issues/12415#issuecomment-250143688).

**Comment by frewsxcv** [comment]
Hadnt seen that issue before.

It's explicitly mentioned in the spec, which is why I added it. Seems unfortunate to stray from the spec.

**Pull request closed without merging**
