### PR TITLE
Partial implementation of transform animations spec.

### PR DESCRIPTION
**Pull request by glennw**
Also tidy up some of the ComputedMatrix code.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6280)

### CODE REVIEW

**Comment by glennw** [comment]
r? @pcwalton 

This doesn't support transitions that require matrix decomposition and interpolation yet - I need to implement quite a bit of support code in rust-geom to support that.

But it implements most of the interpolation spec, and supports simple transforms using transitions.

Transitions that require matrix decomposition just return from from frame currently and don't animate.

**Comment by nox** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- components/layout/display_list_builder.rs @ r1
- components/layout/model.rs @ r1
- components/style/animation.rs @ r1
- components/style/properties.mako.rs @ r1
- components/style/values.rs @ r1

---

<sup>**[components/style/animation.rs, line 776 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6280#-Jr2DQHVwbfM4ViaHNBe)** ([raw file](https://github.com/servo/servo/blob/f3be7a6eae1ab97b4f722a8ed9000dd93aabf588/components/style/animation.rs#L776)):</sup>
Out of curiosity, where does the spec says the "from" values are to be used when an interpolation cannot be done?

---

<sup>**[components/style/animation.rs, line 809 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6280#-Jr2Csj_Dboc5S4OYHjS)** ([raw file](https://github.com/servo/servo/blob/f3be7a6eae1ab97b4f722a8ed9000dd93aabf588/components/style/animation.rs#L809)):</sup>
The spec says perspective(infinity). Is 0 just our representation of infinity? That sounds counter-intuitive.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6280)

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer 

---

Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6280)

**Comment by glennw** [comment]
Review status: 4 of 5 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/style/animation.rs, line 776 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6280#-Jr2DQHVwbfM4ViaHNBe)** ([raw file](https://github.com/servo/servo/blob/f3be7a6eae1ab97b4f722a8ed9000dd93aabf588/components/style/animation.rs#L776)):</sup>
That is not part of the spec. The reason I've done it this was is that the code for matrix interpolation is quite a significant chunk of isolated work in rust-geom. Using the 'from' list for now means that these cases retain the exact same behaviour as they currently have (i.e. they are effectively ignored and appear unimplemented), but allows the rest of the transforms to work with transitions. Once I complete the matrix interpolation work and get rust-geom updated, I can just drop in that code where the TODO comments are and it will all work.

So, what this PR gives is a superset of what we have (behaviour remains the same for matrix interpolation transforms as it currently is, but it adds support for the simple subset of transforms).

---

<sup>**[components/style/animation.rs, line 809 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6280#-Jr2Csj_Dboc5S4OYHjS)** ([raw file](https://github.com/servo/servo/blob/f3be7a6eae1ab97b4f722a8ed9000dd93aabf588/components/style/animation.rs#L809)):</sup>
Good catch - fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6280)

**Comment by nox** [comment]
Squash and I'll r+ it. :) Good work.

-S-awaiting-answer -S-awaiting-review +S-needs-squash 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/style/animation.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6280)

**Comment by glennw** [comment]
@nox Squashed now. Thanks for the review :)

**Comment by nox** [comment]
@bors-servo: r+

-S-awaiting-review -S-needs-squash +S-awaiting-merge 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6280)

**Pull request merged**
