### PR TITLE
Match compound selectors left-to-right (second try)

### PR DESCRIPTION
**Pull request by bholley**
https://bugzilla.mozilla.org/show_bug.cgi?id=1373800

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17439)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo retry

 * git update failed (?)

**Comment by jdm** [comment]
Mysteriously timed out while building.

**Comment by jdm** [comment]
That's #17450.

**Pull request merged**
