### PR TITLE
Switch to our own websocket fork

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15798)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@nox for posterity, can you write here why we’re forking?

**Comment by nox** [comment]
Maintainer is AWOL and it needs a hyper bump.

**Comment by nox** [comment]
I removed the `audio-video-metadata` bump that brings the Apache-2.0-only dependency.

@bors-servo r=Ms2ger

**Pull request merged**
