### PR TITLE
Implement Range#extractContents

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6695)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 502 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6695#-JuouKcWBMRjwTTEWMkk)** ([raw file](https://github.com/servo/servo/blob/41f29d123674741cc3d1d8d7f65f0c071ff249c4/components/script/dom/range.rs#L502)):</sup>
Share some code around here.

---

<sup>**[components/script/dom/range.rs, line 569 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6695#-JuovXBXs-YnVuovK5NH)** ([raw file](https://github.com/servo/servo/blob/41f29d123674741cc3d1d8d7f65f0c071ff249c4/components/script/dom/range.rs#L569)):</sup>
Now I'm wondering whether the children of `common_ancestor` can change in steps 12-16.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6695)

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 502 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6695#-JuouKcWBMRjwTTEWMkk)** ([raw file](https://github.com/servo/servo/blob/41f29d123674741cc3d1d8d7f65f0c071ff249c4/components/script/dom/range.rs#L502)):</sup>
Wasn't sure what you meant here, I shared this section with cloneContents. Which also fixed some test failures, any idea why?

---

<sup>**[components/script/dom/range.rs, line 569 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6695#-JuovXBXs-YnVuovK5NH)** ([raw file](https://github.com/servo/servo/blob/41f29d123674741cc3d1d8d7f65f0c071ff249c4/components/script/dom/range.rs#L569)):</sup>
Maybe? I also tried computing the children right before iterating them but it didn't change the test results.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6695)

**Comment by dzbarsky** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/range.rs, line 502 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6695#-JuouKcWBMRjwTTEWMkk)** ([raw file](https://github.com/servo/servo/blob/41f29d123674741cc3d1d8d7f65f0c071ff249c4/components/script/dom/range.rs#L502)):</sup>
Nevermind, I'm pretty sure I fixed this earlier but forgot to update expectations.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6695)

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-squash 

lgtm

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6695)

**Comment by jdm** [comment]
```

/dom/interfaces.html
--------------------
PASS expected FAIL Range interface: operation extractContents()
PASS expected FAIL Range interface: document.createRange() must inherit property "extractContents" with the proper type (21)
PASS expected FAIL Range interface: detachedRange must inherit property "extractContents" with the proper type (21)
```

**Pull request merged**
