### PR TITLE
Consistently use content-type sniffing with all protocols.

### PR DESCRIPTION
**Pull request by eefriedman**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8037)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/net/file_loader.rs, line 62 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8037#-K1vpdLBfkA2Pc8HarP9)** ([raw file](https://github.com/servo/servo/blob/4e176129615a0cc903328318a8ba1dc8e8b982ae/components/net/file_loader.rs#L62)):</sup>
Remove this unwrap?


---

<sup>**[components/net/file_loader.rs, line 70 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8037#-K1vpIbb-ehSleY-WV74)** ([raw file](https://github.com/servo/servo/blob/4e176129615a0cc903328318a8ba1dc8e8b982ae/components/net/file_loader.rs#L70)):</sup>
Remove this unwrap?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8037)

**Comment by eefriedman** [comment]
Updated.

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8037)

**Comment by jdm** [comment]
```
/home/servo/buildbot/slave/linux-dev/build/tests/unit/net/data_loader.rs:24:5: 24:77 error: this function takes 3 parameters but 2 parameters were supplied [E0061]
/home/servo/buildbot/slave/linux-dev/build/tests/unit/net/data_loader.rs:24     load(LoadData::new(Url::parse(url).unwrap(), None), Channel(start_chan));
                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by eefriedman** [comment]
Updated.

**Pull request merged**
