### PR TITLE
Taskcluster: run tidy on PRs

### PR DESCRIPTION
**Pull request by SimonSapin**
Taskcluster: run tasks for PRs from everyone

These tasks should be untrusted, since they run before review. The `repo:github.com/servo/servo:pull-request` role determines what scopes (permissions) those tasks have.

https://tools.taskcluster.net/auth/roles/repo%3Agithub.com%2Fservo%2Fservo%3Apull-request

~For more paranoia, we could run these tasks on entirely separate worker types (machine pools). For now, maybe being careful to to give scopes for any kind of write access is hopefully enough.~

There seems to be no way to disable the "docker-in-docker" feature, which could allow tasks to escalate to root on the host worker. So this uses a separate `servo-docker-untrusted` worker type. To manage cost, these workers are configured with `minCapacity: 0` and to shut down after 2 minutes idle. (This is a trade-off with the latency of spinning up new AWS EC2 instances.)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22597)

### CODE REVIEW

**Comment by SimonSapin** [comment]
In PR "synchronize" events (on pushes to the source branch), the `event.pull_request.merge_commit_sha` key seems to contain the hash of the **previous** merge commit. Possibly because the new merge commit is created asynchronously? But by the time we run `git fetch --depth 1 refs/pull/22597/merge`, the new merge commit is there with a different hash.

**Comment by SimonSapin** [comment]
For a new PR, that key is just empty. See `payload.env.GIT_SHA` in https://tools.taskcluster.net/groups/fAm4wMXMTzaaYm75JUBdaw/tasks/fAm4wMXMTzaaYm75JUBdaw/details, for https://github.com/servo/servo/pull/22614.

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by jdm** [comment]
```
Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
etc/taskcluster/decision_task.py     120      4    97%   76-83, 134
etc/taskcluster/decisionlib.py       268      0   100%
etc/taskcluster/mock.py               32      0   100%
----------------------------------------------------------------
TOTAL                                420      4    99%
```

**Comment by SimonSapin** [comment]
Added a line in `mock.py`

**Comment by SimonSapin** [comment]
And a debugging script that I forgot to commit earlier.

**Comment by jdm** [comment]
```
./etc/taskcluster/simulate_github_events.py:1: incorrect license
```

**Comment by SimonSapin** [comment]
@bors-servo r-

The PR task is failing now: https://tools.taskcluster.net/groups/HSIq-rY-QwyfhvvBMCB47A/tasks/HSIq-rY-QwyfhvvBMCB47A/runs/0/logs/public%2Flogs%2Flive.log#L545

**Comment by jdm** [comment]
```
Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
etc/taskcluster/decision_task.py     121      0   100%
etc/taskcluster/decisionlib.py       270      2    99%   221, 270
etc/taskcluster/mock.py               34      0   100%
----------------------------------------------------------------
TOTAL                                425      2    99%
```

**Pull request merged**
