### PR TITLE
mach filter-intermittents: add progress and --json output mode

### PR DESCRIPTION
**Pull request by delan**
filter-intermittents takes a while, because it needs to look up each failure against the tracker api (or GitHub api), so it would be nice to know how long we’ll need to wait when running it interactively. The output is also pretty-printed in a format that’s not the easiest to analyse.

This patch adds some progress output (on stderr, one line with \\r), plus a --json output format as follows:

[{"test": "/path/to/foo", "output": "..."}, {"test": "/path/to/bar", "output": "..."}, ...]

---

- [ ] ~~`./mach build -d` does not report any errors~~
- [ ] ~~`./mach test-tidy` does not report any errors~~
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they affect mach filter-intermittents only

### CODE REVIEW

**Review by CYBAI — APPROVED** [review]
Thank you!

**Comment by CYBAI** [comment]
as I don't have r+ permission, might need your help to r=cybai 🙏 thanks!

**Comment by delan** [comment]
r=cybai

**Pull request merged**
