### PR TITLE
Improve spec-compliance of script loading and execution during document startup

### PR DESCRIPTION
**Pull request by tschneidereit**
Including proper support for async and deferred scripts.

r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7979)

### CODE REVIEW

**Comment by jdm** [comment]
\o/

**Comment by Ms2ger** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/document.rs, line 1006 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0RQBcs5hUbH8Tu3TuF)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1006)):</sup>
`if let` would probably be better here.


---

<sup>**[components/script/dom/document.rs, line 1015 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0RQNpWv9jx4zpIA5ZK)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1015)):</sup>
`get_rooted()` (also below).


---

<sup>**[components/script/dom/document.rs, line 1017 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0RQH-bs0vxfWTN4kK5)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1017)):</sup>
Should not need `.r()` on these two lines, I think.


---

<sup>**[components/script/dom/document.rs, line 1037 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0RQRDuebSJJ3XQt2Sq)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1037)):</sup>
```rust
let script = match self.pending_parsing_blocking_script.get_rooted() {
    None => return false,
    Some(script) => script,
};
<!-- Reviewable comment -K0RQRDuebSJJ3XQt2Sr:-547629811 -->

---

<sup>**[components/script/dom/document.rs, line 1061 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0RRWe33A61uGvv23wY)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1061)):</sup>
Why re-root this?
<!-- Reviewable comment -K0RRWe4wJjZ9dKEx-vy:1308094368 -->

---

<sup>**[components/script/dom/document.rs, line 1072 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0RRcpr7FahCD6H0IBG)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1072)):</sup>
This is not part of step 3; I wonder if we forget to dispatch `DOMContentLoaded` in some cases with this change. If so, write a test (if none fail because of ti).
<!-- Reviewable comment -K0RRcpsSZnFkRExdG-Y:-1818767902 -->

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)
<!-- Sent from Reviewable.io -->

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/document.rs, line 1057 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0RdyIS5dBewO3SySVq)** ([raw file](https://github.com/servo/servo/blob/cf65db0c865311697d9f39a4bb7b8ff6287d367d/components/script/dom/document.rs#L1057)):</sup>
`if deferred_scripts.is_empty() {`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/document.rs, line 1060 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0ReIOMNqz0IbD6LJTN)** ([raw file](https://github.com/servo/servo/blob/cf65db0c865311697d9f39a4bb7b8ff6287d367d/components/script/dom/document.rs#L1060)):</sup>
`while let Some(deferred_script) = deferred_scripts.first())`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/document.rs, line 1060 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0ReIOMNqz0IbD6LJTN)** ([raw file](https://github.com/servo/servo/blob/cf65db0c865311697d9f39a4bb7b8ff6287d367d/components/script/dom/document.rs#L1060)):</sup>
Nevermind. This won't work because it gets mutably borrowed within each loop iteration


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by frewsxcv** [comment]
<sup>**[components/script/dom/document.rs, line 1060 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0ReIOMNqz0IbD6LJTN)** ([raw file](https://github.com/servo/servo/blob/cf65db0c865311697d9f39a4bb7b8ff6287d367d/components/script/dom/document.rs#L1060)):</sup>
TIL about [Vec::drain](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html?search=#method.drain), which could be appropriate here, but whatever


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by tschneidereit** [comment]
Addressed review comments so far, fixed some regressions and update test expectations for `old-tests/submission/Opera/script_scheduling/*`.

This now hits #6612 in three additional tests. All of those are to be expected until that issue is fixed, though.


---

Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/document.rs, line 1061 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0RRWe33A61uGvv23wY)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1061)):</sup>
`deferred_scripts` contains `JS<HTMLScriptElement`, so I have to root the scripts.


---

<sup>**[components/script/dom/document.rs, line 1072 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K0RRcpr7FahCD6H0IBG)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1072)):</sup>
Thanks, good catch.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by tschneidereit** [comment]
Rebased on current master.

**Comment by jdm** [comment]
What are the new WPT crashes?

**Comment by jdm** [comment]
```
/old-tests/submission/Opera/script_scheduling/034.html
------------------------------------------------------
OK expected CRASH [Parent]
/old-tests/submission/Opera/script_scheduling/035.html
------------------------------------------------------
OK expected CRASH [Parent]
/old-tests/submission/Opera/script_scheduling/039.html
------------------------------------------------------
OK expected CRASH [Parent]
```
Confusing.

**Comment by jdm** [comment]
Oh, that's debug only.

**Comment by tschneidereit** [comment]
@jdm, I fixed the expectations, so tests should be good now.

**Comment by nox** [comment]
@bos-servo try force

**Comment by tschneidereit** [comment]
@Ms2ger, the two failing CSS tests are #7625, so this should be ready.

**Comment by Ms2ger** [comment]
r? @jdm 


---

Reviewed 3 of 7 files at r3.
Review status: 3 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/document_loader.rs, line 43 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1562qINcYlNCvYasIk)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/document_loader.rs#L43)):</sup>
Why make it public? Anyway, needs docs.


---

<sup>**[components/script/dom/document.rs, line 1001 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K154z5CWUjyx6xEkA99)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/dom/document.rs#L1001)):</sup>
Return an enum for readability, I think.


---

<sup>**[components/script/dom/document.rs, line 1993 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K155cF-QXN6IiKh3MFu)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/dom/document.rs#L1993)):</sup>
File a followup to get rid of the enum; it should have been two separate structs anyway.


---

<sup>**[components/script/dom/htmlscriptelement.rs, line 122 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K155mKUMhhgA3EpE-Nl)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/dom/htmlscriptelement.rs#L122)):</sup>
Derive `JSTraceable`, that's safer.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by tschneidereit** [comment]
Rebased and addressed review comments.


---

Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/document_loader.rs, line 43 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1562qINcYlNCvYasIk)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/document_loader.rs#L43)):</sup>
This change is silly and largely vestigial. Will revert.


---

<sup>**[components/script/dom/htmlscriptelement.rs, line 122 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K155mKUMhhgA3EpE-Nl)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/dom/htmlscriptelement.rs#L122)):</sup>
Done, but I had to apply `no_jsmanaged_fields!` to `Metadata`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 4 of 7 files at r3, 4 of 4 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/document.rs, line 994 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_PB2PLINeNDimqWTE)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L994)):</sup>
Can we add spec links and steps to this method?


---

<sup>**[components/script/dom/document.rs, line 1030 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_PN2tD7o8zlEZa1-w)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1030)):</sup>
-d


---

<sup>**[components/script/dom/document.rs, line 1031 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_PoZa5jEdiBWliNSX)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1031)):</sup>
Is there a spec link for this?


---

<sup>**[components/script/dom/document.rs, line 1078 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_QFP7CI5G2XXK9CTZ)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1078)):</sup>
it's


---

<sup>**[components/script/dom/document.rs, line 132 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_U8zZRlin8QIbYJ92)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/dom/document.rs#L132)):</sup>
s/triggered/dispatched/


---

<sup>**[components/script/dom/document.rs, line 1042 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_TvLeWAD3VBAixqNl)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/dom/document.rs#L1042)):</sup>
"Also triggered by script_task" doesn't really clarify matters for me :/


---

<sup>**[components/script/dom/document.rs, line 1034 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_VNsLi4WdrSPrKdaa)** ([raw file](https://github.com/servo/servo/blob/32f165f52021afed8bf8b30928c9851944047faf/components/script/dom/document.rs#L1034)):</sup>
`if self.maybe_execute_parser_blocking_script() == ParserBlockedByScript::Blocked {`?


---

<sup>**[components/script/dom/htmlscriptelement.rs, line 336 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_Rqd4opWS3yboH6ny)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/htmlscriptelement.rs#L336)):</sup>
async comment is incorrect here.


---

<sup>**[components/script/dom/htmlscriptelement.rs, line 344 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_S2hDia8gcX8VE6xG)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/htmlscriptelement.rs#L344)):</sup>
isn't async


---

<sup>**[components/script/dom/htmlscriptelement.rs, line 381 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_SWspdRzsM5-Aj41J)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/htmlscriptelement.rs#L381)):</sup>
`let load = self.load.borrow_mut().take().unwrap();`


---

<sup>**[components/script/dom/htmlscriptelement.rs, line 122 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K155mKUMhhgA3EpE-Nl)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/dom/htmlscriptelement.rs#L122)):</sup>
I would move this to trace.rs.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by tschneidereit** [comment]
@jdm, thanks for the fast review.


---

Review status: 5 of 9 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/document.rs, line 994 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_PB2PLINeNDimqWTE)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L994)):</sup>
Not really :/ The spec has these steps dispersed across various tasks, with no central place binding them together. Note that the individual functions called here do have spec links.


---

<sup>**[components/script/dom/document.rs, line 1031 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_PoZa5jEdiBWliNSX)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1031)):</sup>
I added the closest thing to the right link there is. It's not exactly right because this is supposed to be driven by the event loop - which we don't have in the way the spec would like us to.


---

<sup>**[components/script/dom/document.rs, line 1078 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_QFP7CI5G2XXK9CTZ)** ([raw file](https://github.com/servo/servo/blob/339328077feac73489f1dc02f33ca4e78add05ee/components/script/dom/document.rs#L1078)):</sup>
Fixed in an earlier rev.


---

<sup>**[components/script/dom/document.rs, line 1042 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7979#-K1_TvLeWAD3VBAixqNl)** ([raw file](https://github.com/servo/servo/blob/493cca1cc83441d1546ac4459d9c418c6d089214/components/script/dom/document.rs#L1042)):</sup>
Fair. The good news is that triggering it in `script_task` isn't even the right thing to do, so I removed it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by jdm** [comment]
Squash this stuff in whatever way feels most natural, or just let me know if squashing will be too annoying and we can merge.
-S-awaiting-review +S-needs-squash 


---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by tschneidereit** [comment]
Thanks, done.


---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7979)

**Comment by jdm** [comment]
@bors-servo: r+
\o/

**Pull request merged**
