### PR TITLE
Initialize block_container_inline_size for non-block root flows

### LINKED ISSUE #14945: Layout of CSS FPS selection screen is half as wide as it should be
http://keithclark.co.uk/labs/css-fps/
Servo:
screen shot 2017-01-10 at 12 46 15 pm
Firefox:
screen shot 2017-01-10 at 12 46 51 pm

### LINKED ISSUE #14948: Root element with table display doesn't account for CSS width and height
```html
<html style="display: table; width: 100%; height: 100%; border: 1px solid black">
<body>
  <h1>CSS FPS</h1>
</body>
</html>
```
Servo:
screen shot 2017-01-10 at 1 28 26 pm
Firefox:
screen shot 2017-01-10 at 1 28 41 pm

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes #14948. Fixes #14945.  Needs a try run.  r? @notriddle

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15271)

### CODE REVIEW

**Comment by notriddle** [comment]
Would you please make a test case for flex, too?

**Comment by mbrubeck** [comment]
> Would you please make a test case for flex, too?

Done.

**Comment by notriddle** [comment]
It passed [linux-rel-css](http://build.servo.org/builders/linux-rel-css/builds/2095) and [linux-rel-wpt](http://build.servo.org/builders/linux-rel-wpt/builds/2107), and it looks correct.

@bors-servo +

**Pull request merged**
