### PR TITLE
Add insert_adjacent methods into Element

### LINKED ISSUE #10205: Implement insertAdjacentElement and insertAdjacentText
https://dom.spec.whatwg.org/#dom-element-insertadjacentelement
https://dom.spec.whatwg.org/#dom-element-insertadjacenttext

Files:
 * components/script/dom/element.rs
 * components/script/webidls/Element.webidl

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #10205

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10219)

### CODE REVIEW

**Comment by frewsxcv** [comment]
*[components/script/dom/element.rs, line 1212 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDppIto3zviPJ3Tvwc9:-KDppIto3zviPJ3TvwcA:423839240) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1212)):*
Alternatively, you could do something like this:

```rust
let child = self.GetNextElementSibling().map(|c| c.upcast::Node());
try!(Node::pre_insert(element, &parent, child));
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219)*

**Comment by nox** [comment]
A small misunderstanding and a few nits.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[components/script/dom/element.rs, line 1172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrOulC-sFDNCTjV1b4:-KDrOulDuASYN8lQXR3H:-1755305416) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1172)):*
`element` should be named `node`.

---

*[components/script/dom/element.rs, line 1172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrUv5RIhxICjgQMVkC:-KDrUv5Sv4sdhDIlTA1Q:2064217973) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1172)):*
You will want to use `self` as a `Node` too for many operations in this algorithm so you should probably start it by:

```rust
let self_node = self.upcast::<Node>();
```

---

*[components/script/dom/element.rs, line 1172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrUwYByTeiwlTOZvgF:-KDrUwYByTeiwlTOZvgG:74313056) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1172)):*
Spec link: https://dom.spec.whatwg.org/#insert-adjacent

---

*[components/script/dom/element.rs, line 1173 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrP6CtLUCp2mXVshiX:-KDrP6CtLUCp2mXVshiY:908468189) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1173)):*
This should return `Fallible<Option<Root<Node>>>`, and also this line should be aligned with the `(` above. `Node` is the most specific type that can hold onto both `Element` and `Text`.

---

*[components/script/dom/element.rs, line 1183 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrPYIGjdYaASf_XUpP:-KDrPYIGjdYaASf_XUpQ:1986997040) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1183)):*
```rust
if let Some(parent) = self_node.GetParentNode() {
    Node::pre_insert(node, &parent, Some(self_node)).map(Some)
} else {
    Ok(None)
}
```

---

*[components/script/dom/element.rs, line 1196 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrRp_cUzK2hy-ieQGB:-KDrRp_cUzK2hy-ieQGC:-1769828988) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1196)):*
```rust
Node::pre_insert(node, self_node, &self_node.GetFirstChild().r()).map(Some)
```

---

*[components/script/dom/element.rs, line 1201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrRqWwBc2Sbae7xfD5:-KDrRqWwBc2Sbae7xfD6:2103233027) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1201)):*
For consistency I would just call `pre_insert` directly again.

```rust
Node::pre_insert(node, self_node, None).map(Some)
```

---

*[components/script/dom/element.rs, line 1217 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrSo523yc8oZ8OnH5J:-KDrSo523yc8oZ8OnH5K:-180967758) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1217)):*
`Element::GetNextElementSibling` is not the right method, that returns the element's next element sibling, you want the node's next sibling, be it itself an element, a text node, or whatever else.

```rust
if let Some(parent) = self_node.GetParentNode() {
    Node::pre_insert(node, &parent, self_node.GetNextElementSibling().r())
} else {
    Ok(None)
}
```

---

*[components/script/dom/element.rs, line 1677 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrTQVCU6RgfrWoezrz:-KDrTQVCU6RgfrWoezs-:-322182740) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1677)):*
```rust
let inserted_node = try!(self.insert_adjacent(where_, element.upcast()));
Ok(inserted_node.downcast::<Element>().unwrap())
```

---

*[components/script/dom/element.rs, line 1682 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrU0XhjQjowHRmDvs6:-KDrTyRqGiUyElwyipAm:701671922) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1682)):*
This should return `ErrorResult` and be properly aligned with the `(` above.

---

*[components/script/dom/element.rs, line 1685 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrTzeK4BavadVn0J6E:-KDrTzeK4BavadVn0J6F:-972258660) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1685)):*
Please separate into two steps like in the spec.

```rust
// Step 1.
let text = Text::new(data, &document_from_node(self));

// Step 2.
self.insert_adjacent(where_, text.upcast()).map(|_| ())
```

---

*[components/script/dom/webidls/Element.webidl, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrU21BBbTUT8cahu-S:-KDrU21BBbTUT8cahu-T:-485102249) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/webidls/Element.webidl#L76)):*
This is wrong, that method returns `void`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219#-:-KDrV-_QxjvZvuebZ1st:865906344)*

**Comment by GuillaumeGomez** [comment]
*[components/script/dom/element.rs, line 1217 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrSo523yc8oZ8OnH5J:-KDrfGcTcgUJazJM4tfW:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1217)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219)*

**Comment by GuillaumeGomez** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[components/script/dom/element.rs, line 1172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrOulC-sFDNCTjV1b4:-KDrbZf6Nw4ba95711d1:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1172)):*
Done.

---

*[components/script/dom/element.rs, line 1172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrUv5RIhxICjgQMVkC:-KDrb_U-ztDcoyQw8rmO:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1172)):*
Done.

---

*[components/script/dom/element.rs, line 1172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrUwYByTeiwlTOZvgF:-KDrbaXe53Y38tGs2JPe:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1172)):*
Done.

---

*[components/script/dom/element.rs, line 1173 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrP6CtLUCp2mXVshiX:-KDrbbBmb4YYPSxfD3mn:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1173)):*
Done.

---

*[components/script/dom/element.rs, line 1183 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrPYIGjdYaASf_XUpP:-KDrfssnU6W1rD69NzIX:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1183)):*
Done.

---

*[components/script/dom/element.rs, line 1196 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrRp_cUzK2hy-ieQGB:-KDrflhlY6VBs9Nvgi3H:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1196)):*
Done.

---

*[components/script/dom/element.rs, line 1201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrRqWwBc2Sbae7xfD5:-KDriQjUkqBd83_pVile:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1201)):*
Done.

---

*[components/script/dom/element.rs, line 1677 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrTQVCU6RgfrWoezrz:-KDreplHlvENiMlNYjNG:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1677)):*
Done.

---

*[components/script/dom/element.rs, line 1682 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrU0XhjQjowHRmDvs6:-KDrdMA8PvXbNvMrr-Un:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1682)):*
Done.

---

*[components/script/dom/element.rs, line 1685 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrTzeK4BavadVn0J6E:-KDrdLfuWxxDf2f1ZxDB:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/element.rs#L1685)):*
Done.

---

*[components/script/dom/webidls/Element.webidl, line 76 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrU21BBbTUT8cahu-S:-KDriP426yDLzfj53rnf:-499146009) ([raw file](https://github.com/servo/servo/blob/e3a57a0311d458c3021981575842f697750b3061/components/script/dom/webidls/Element.webidl#L76)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219)*

**Comment by nox** [comment]
One change and a few final nits. These calls on multiple lines makes the `.map(Some)` part stand less.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/element.rs, line 1181 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrjKg-pxpRAd0DipiA:-KDrjKg-pxpRAd0DipiB:489995723) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1181)):*
Nit: no need to do this on multiple lines.

---

*[components/script/dom/element.rs, line 1189 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrjPSV3gm_csHqK759:-KDrjPSV3gm_csHqK75A:489995723) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1189)):*
Nit: no need to do this on multiple lines.

---

*[components/script/dom/element.rs, line 1194 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrjXZ9VwCOZa7ytxIY:-KDrjXZ9VwCOZa7ytxIZ:489995723) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1194)):*
Nit: no need to do this on multiple lines.

---

*[components/script/dom/element.rs, line 1200 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrkDZ9f2UnL1xqmimG:-KDrkDZ9f2UnL1xqmimH:489995723) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1200)):*
Nit: no need to do this on multiple lines.

---

*[components/script/dom/element.rs, line 1668 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrjjLOwxqhJRDdJJF5:-KDrjjLPKoJFkUTB4I1H:-2093318166) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1668)):*
You want to unwrap the downcasting, because it's not supposed to fail ever.

Please do this without an `if let`:

```rust
let inserted_node = try!(self.insert_adjacent(where_, element.upcast()));
Ok(inserted_node.map(|node| Root::downcast(node).unwrap()))
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219#-:-KDrkHT9hqs-MZ2nE-kL:458720182)*

**Comment by GuillaumeGomez** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[components/script/dom/element.rs, line 1181 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrjKg-pxpRAd0DipiA:-KDrqoQnVM1P3EXy9pDQ:-499146009) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1181)):*
Done.

---

*[components/script/dom/element.rs, line 1189 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrjPSV3gm_csHqK759:-KDrqktwsP0tzE0ROVe5:-499146009) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1189)):*
Done.

---

*[components/script/dom/element.rs, line 1194 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrjXZ9VwCOZa7ytxIY:-KDrquQu0_VF3-nZPcq7:-499146009) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1194)):*
Done.

---

*[components/script/dom/element.rs, line 1200 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrkDZ9f2UnL1xqmimG:-KDrqiClfz3aQCR05m49:-499146009) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1200)):*
Done.

---

*[components/script/dom/element.rs, line 1668 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDrjjLOwxqhJRDdJJF5:-KDrqa4oGy4dn7hC442V:-499146009) ([raw file](https://github.com/servo/servo/blob/a6ada61fe1c3e936c248ce708c8f35119f072815/components/script/dom/element.rs#L1668)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219)*

**Comment by nox** [comment]
-S-awaiting-review 

@bors-servo try

I think there are new passing tests already. If the try succeeds, it means it lacks tests.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219#-:-KDrsHJ5WsUHQlguSTM2:-915526914)*

**Comment by nox** [comment]
The AppVeyor failure can be ignored, but all the WPT tests passed, which means this lacks tests.

You can look at the ones for `insertAdjacentHTML` in tests/wpt/web-platform-tests/domparsing/insert-adjacent.html. Good luck, and as usual don't hesitate to ping me.

**Comment by nox** [comment]
-C-needs-test -S-awaiting-review -S-needs-tests +S-needs-code-changes 

Thanks for writing the tests.

---

Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/element.rs, line 1178 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDsd3ZMPCt9xhYKCOrA:-KDsd3ZMPCt9xhYKCOrB:809795064) ([raw file](https://github.com/servo/servo/blob/8e3e3049257bbb532a8c53f9d6fb44b11e31f362/components/script/dom/element.rs#L1178)):*
You want the parent node's of `self_node`, not `node`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219#-:-KDsdHDQDLyqyiFkm4ho:-15591342)*

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 2 files at r6, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 33 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssLY--9Lkeo7Wedg2:-KDssLY--9Lkeo7Wedg3:273107012) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L33)):*
No, define `div` in it.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 39 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssNCDZ5IABjLvMjKK:-KDssNCDZ5IABjLvMjKL:-210765779) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L39)):*
Define `div` again here.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 40 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssR02J0x7vRfgjxx6:-KDssR02J0x7vRfgjxx7:319676221) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L40)):*
You don't seem to use that variable, you should probably do:

```js
assert_equals(el[possiblePositions[position]], t);
```

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 52 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDst-UbPgYVNbsO4zmO:-KDst-UbPgYVNbsO4zmP:-1364293733) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L52)):*
That's badly named. This is an element, not a document. Please rename to `el`.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 53 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssiSisY3WbKWMoSDD:-KDssiSisY3WbKWMoSDE:-1939823824) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L53)):*
`HIERARCHY_REQUEST_ERR`

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 58 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssrJDd-OTK95hXxtN:-KDssrJDd-OTK95hXxtO:-1783161087) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L58)):*
Please rename to `el`.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 59 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDst2VFHbJRr5GUnJ8V:-KDssmBKndvAT8hefQ4O:-1939823824) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L59)):*
`HIERARCHY_REQUEST_ERR`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219#-:-KDstObUYx-fKFetNlqA:1458266033)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 33 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssLY--9Lkeo7Wedg2:-KDstfDkr6qXCfpR54zv:-451067126) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L33)):*
Oh wait never mind, I see now, that's for the label.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 39 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssNCDZ5IABjLvMjKK:-KDstlKldjaiGQ4E6x5Y:185527847) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L39)):*
Actually no, we don't use `div` here.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 42 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDsttm31V3xgG6FnWF5:-KDsttm31V3xgG6FnWF6:1528117229) ([raw file](https://github.com/servo/servo/blob/054793df9baa4cfb4cb536dcb5ff4a84f9d7c7da/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L42)):*
```js
'insertAdjacentText(' + position + ', ' + texts[position] + ' )'
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219)*

**Comment by GuillaumeGomez** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 40 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssR02J0x7vRfgjxx6:-KDsuCxxWBu9HI5kBsF6:-1651558637) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L40)):*
That would be incorrect since insertAdjacentText returns nothing (I remove t variable).

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 52 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDst-UbPgYVNbsO4zmO:-KDsuTjRiCe2n42dlqf6:-499146009) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L52)):*
Done.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 53 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssiSisY3WbKWMoSDD:-KDsuZzADwdgYFjakyBP:-499146009) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L53)):*
Done.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 58 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDssrJDd-OTK95hXxtN:-KDsu_zorBnEgLYIJ8YN:-499146009) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L58)):*
Done.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 59 \[r8\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDst2VFHbJRr5GUnJ8V:-KDsuaFNNMhtqhwOrbvf:-499146009) ([raw file](https://github.com/servo/servo/blob/b52f6e57d0a1cf162815385ed37454b0846e3480/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L59)):*
Done.

---

*[tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html, line 42 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10219#-KDsttm31V3xgG6FnWF5:-KDsuU8c_IFRw3-CctKR:-499146009) ([raw file](https://github.com/servo/servo/blob/054793df9baa4cfb4cb536dcb5ff4a84f9d7c7da/tests/wpt/web-platform-tests/dom/nodes/insert-adjacent.html#L42)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219)*

**Comment by nox** [comment]
@bors-servo r+

Thanks!

---

Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10219#-:-KDsvLLvJ4XMyn5Oe3Y6:-1544677996)*

**Pull request merged**
