### PR TITLE
Bump rust-url from 2.1.0 to 2.1.1

### LINKED ISSUE #26287: Investigate failure of URL parsing tests
Follow up from https://github.com/servo/servo/pull/26231

The PR marks some tests as FAIL, see https://github.com/servo/servo/pull/26231/files#diff-6c940171cdc241cde1caf796556840caR132

Actually that file contained a bunch of existing test failures already, related to things other than the use of `location`, and those could be investigated as well. 

For discussion, see https://github.com/servo/servo/pull/26231#issuecomment-618413191

### PR DESCRIPTION
**Pull request by utsavoza**
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix (partially) #26287 
- [x] There are tests for these changes

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by utsavoza** [comment]
Is there a way to avoid closing the issue, if a PR only partially fixes it?

**Comment by jdm** [comment]
Oh, using `fix (partially) #12345` in the description does that. Otherwise we can reopen manually.

**Comment by jdm** [comment]
@bors-servo retry
* #26466

**Pull request merged**
