### PR TITLE
HACKING_QUICKSTART: Fixed typo

### PR DESCRIPTION
**Pull request by perlun**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10107)

### CODE REVIEW

**Comment by paulrouget** [comment]
I like "turorial".

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Comment by perlun** [comment]
> I like "turorial".

Yeah, it sounded sophisticated. :wink: 

> Thanks!

Sure. Just happened to find it while lurking around, setting up my dev environment. Any trivial Rust issues I can start working on? Just something small for starters, preferably Rust (but Travis-related stuff is also OK since I use it a lot at work).

(I looked at http://servo.github.io/servo-starters/ already, so I guess I should just look there more carefully. :stuck_out_tongue:)

**Comment by mbrubeck** [comment]
@bors-servo retry

#9777

**Pull request merged**
