### PR TITLE
Remove testharnessreport-servodriver.js

### PR DESCRIPTION
**Pull request by georgeroman**
[`testharnessreport-servodriver.js`](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/testharnessreport-servodriver.js) is now obsolete: https://github.com/web-platform-tests/wpt/issues/18618.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24091)

### CODE REVIEW

**Comment by jdm** [comment]
@georgeroman If you have not pushed a new revision, then you need to use `retry` to do another run. However, why do you expect there to be any different results? Or did you forget to push a new revision?

**Comment by georgeroman** [comment]
No, I didn't push a new revision. I just ran the tests locally and they pass so I wanted to make sure that these errors are not intermittent.

**Comment by georgeroman** [comment]
It looks like `testharnessreport-servodriver.js` is still needed as a lot of tests fail without it (I couldn't figure out yet the exact reason for this).

**Pull request closed without merging**
