### PR TITLE
Support remaining text-decoration related properties in geckolib

### PR DESCRIPTION
**Pull request by heycam**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy --faster` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because mostly it's geckolib-only, and the servo-relevant changes should be covered by existing tests

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. 

---

Not sure if there's a better way to do the loop in the text-decoration(-line) longhand parsing, having all of the guts in the loop condition is a bit awkward.

r? @mbrubeck

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11412)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo r+

<details><summary><i>Previously, highfive wrote…</i></summary>
> warning **Warning** warning
> 
> * These commits modify style code, but no tests are modified. Please consider adding a test!
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11412#-:-KIcXqb5FdaVZrCsFzj-:1236647940)*

**Comment by KiChjang** [comment]
@bors-servo retry
* infra

**Comment by mbrubeck** [comment]
@bors-servo retry

infra

**Comment by mbrubeck** [comment]
@bors-servo retry

Seriously, buildbot?

**Comment by mbrubeck** [comment]
@bors-servo r-

http://build.servo.org/builders/linux-rel/builds/1252:
```
  ▶ PASS [expected FAIL] /css21_dev/html4/c71-fwd-parsing-003.htm
```

**Comment by heycam** [comment]
It looks like that test is now correct passing.

**Comment by mbrubeck** [comment]
> It looks like that test is now correct passing.

Yup, you can just remove the .ini file and then land this with r=mbrubeck.

**Pull request merged**
