### PR TITLE
Update rust by example link

### PR DESCRIPTION
**Pull request by radek3911**
rustbyexample.com shows 404

---
- [x] These changes do not require tests because this just updates a text file

### CODE REVIEW

**Comment by yvt** [comment]
`rustbyexample.com` is apparently being domain-hijacked, so we might want to replace this link asap.

The upstream issue of `rustbyexample.com` returning 404: https://github.com/rust-lang/rust-by-example/issues/1454

**Review by takkuumi — COMMENTED** [review]
checked

**Review by takkuumi — APPROVED** [review]
checked

**Review by Florian-Schoenherr — APPROVED** [review]

**Review by KiChjang — APPROVED** [review]

**Pull request merged**
