### PR TITLE
clippy: Fix clippy Problems in components/scripts

### PR DESCRIPTION
**Pull request by six-shot**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes are part of #31500 (GitHub issue number if applicable)

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Review by mrobinson — CHANGES_REQUESTED** [review]
Please remove the changes to `Cargo.lock` from your PR. These are unrelated to the fixes for clippy.

**Comment by six-shot** [comment]
Changes to cargo?? I didn’t touch the file sir

**Comment by six-shot** [comment]
But I’ll remove the changes

**Comment by mrobinson** [comment]
> Changes to cargo?? I didn’t touch the file sir

This file can change if you, at some point, ran `cargo update` for whatever reason. For Servo, you shouldn't ever run `cargo update` unless you are trying to update a dependency.

**Review by mrobinson — CHANGES_REQUESTED** [review]
Tidy is failing:

```
Diff in /home/runner/work/servo/servo/components/script/script_thread.rs at line 311:
             _ => return None,
         };
         match script_msg {
-            CommonScriptMsg::Task(_category, _boxed, pipeline_id, _task_source) => {
-                *pipeline_id
-            },
+            CommonScriptMsg::Task(_category, _boxed, pipeline_id, _task_source) => *pipeline_id,
             _ => None,
         }
     }
Diff in /home/runner/work/servo/servo/components/script/script_thread.rs at line 2364:
                 )
             },
             WebDriverScriptCommand::FocusElement(element_id, reply) => {
-                webdriver_handlers::handle_focus_element(
-                    &documents,
-                    pipeline_id,
-                    element_id,
-                    reply,
-                )
+                webdriver_handlers::handle_focus_element(&documents, pipeline_id, element_id, reply)
             },
             WebDriverScriptCommand::ElementClick(element_id, reply) => {
-                webdriver_handlers::handle_element_click(
-                    &documents,
-                    pipeline_id,
-                    element_id,
-                    reply,
-                )
+                webdriver_handlers::handle_element_click(&documents, pipeline_id, element_id, reply)
             },
             WebDriverScriptCommand::GetActiveElement(reply) => {
                 webdriver_handlers::handle_get_active_element(&documents, pipeline_id, reply)
Run `./mach fmt` to fix the formatting
```

Please make sure to run `./mach fmt` before uploading your change.

**Comment by six-shot** [comment]
Yeah I’m sorry I’m formatting now that’s y I unchecked the requirements

**Review by mrobinson — APPROVED** [review]

**Pull request merged**
