### PR TITLE
style: Avoid hashing the precomputed hash atoms already have.

### PR DESCRIPTION
**Pull request by emilio**
This shaves a fair amount of time of stylist rebuild.

Most of the extra remaining overhead are memory allocations...

I'll try to get those sorted out next, though fixing that may overlap quite a
bit with the work Cameron is doing in bug 1382925.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17993)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/17993#-:-Kqw_h881caGowmHaMQl:bkg9nno)*

**Comment by emilio** [comment]
@bors-servo r=SimonSapin

 * Removed the `cfg(feature = "gecko")` that prevented the precomputed_hash trait from being imported.

**Pull request merged**
