### PR TITLE
Split paint task messages from ScriptMsg

### PR DESCRIPTION
**Pull request by g-k**
Refs: https://github.com/servo/servo/issues/8592

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8598)

### CODE REVIEW

**Comment by jdm** [comment]
@KiChjang Want to take a swing at reviewing this?

**Comment by KiChjang** [comment]
Sure!

**Comment by KiChjang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[components/compositing/constellation.rs, line 628 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8598#-K3TjPd7MuN_7Rkb_Jhq:-K3TjPd7MuN_7Rkb_Jhr:-869308540) ([raw file](https://github.com/servo/servo/blob/05354cea76ee034e6e369748ee6f893e42327760/components/compositing/constellation.rs#L628)):_
We might want to have some ways of distinguishing between `Failure` messages that are fired from the script. Two ways I can think of: pass an additional string parameter to `handle_failure_msg` or move the `debug!`macro up here and to the branch handling `ScriptMsg::Failure` above.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8598)_

**Comment by KiChjang** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8598)_

**Comment by KiChjang** [comment]
I see that you have made a new commit to address the previous issues @g-k , but you'll need to rebase this branch onto master before it can be merged, and also squash your commits. See https://github.com/servo/servo/wiki/Github-&-Critic-PR-handling-101.

Essentially what needs to happen is:
```
git remote add mozilla git@github.com:servo/servo.git
git fetch mozilla
git rebase mozilla/master
```
This rebases your branch onto servo's master. Now, onto squashing commits:
```
git rebase -i HEAD~2
```
Delete the second line's "pick" and type "f" into it. Finally force-push your branch:
```
git push -f
```

**Comment by g-k** [comment]
Thanks @KiChjang!  I rebased and autosquashed but have a build failing with 

```
error: the trait `serde::ser::Serialize` is not implemented for the type `std::sync::mpsc::Sender<msg::constellation_msg::PaintMsg>`
```

 and 

```
error: mismatched types:
 expected `msg::constellation_msg::ConstellationChan<msg::constellation_msg::PaintMsg>`,
    found `std::sync::mpsc::Sender<msg::constellation_msg::PaintMsg>`
(expected struct `msg::constellation_msg::ConstellationChan`,
    found struct `std::sync::mpsc::Sender`) [E0308]
```

errors.  Should painter_chan have type `msg::constellation_msg::ConstellationChan<msg::constellation_msg::PaintMsg>` or `std::sync::mpsc::Sender<msg::constellation_msg::PaintMsg>`?

**Comment by eefriedman** [comment]
@g-k https://github.com/servo/servo/pull/8598/files#diff-f4724c64bbfdec08f0ff93b3fc660d96R75 .

**Comment by g-k** [comment]
Thanks @eefriedman! don't know how I missed that.

**Comment by g-k** [comment]
Rebased.

**Comment by KiChjang** [comment]
Almost there! Once you address the comments, ask @jdm to r+.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/compositing/constellation.rs, line 285 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8598#-K3zunitGb0pdolBHYKp:-K3zunitGb0pdolBHYKq:-1448658873) ([raw file](https://github.com/servo/servo/blob/022d6d3bc22e55edfaa5a7562548d2fc8887fb30/components/compositing/constellation.rs#L285)):*
nit: Do we still need this comment here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8598#-:-K3zux1ydRupRS7siYGZ:-1762738807)*

**Comment by g-k** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/compositing/constellation.rs, line 285 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8598#-K3zunitGb0pdolBHYKp:-K4-8cq-ePU2-22VWZ02:1489398921) ([raw file](https://github.com/servo/servo/blob/022d6d3bc22e55edfaa5a7562548d2fc8887fb30/components/compositing/constellation.rs#L285)):*
I don't think so. Removed!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8598)*

**Comment by KiChjang** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8598#-:-K4-LT_iwVROeU8RRveH:1236647940)*

**Comment by jdm** [comment]
@bors-servo: retry
* #8676

**Comment by KiChjang** [comment]
\o/

**Pull request merged**
