### PR TITLE
Use iterators for iterating through CSS rules

### PR DESCRIPTION
**Pull request by luniv**

### CODE REVIEW

**Comment by jdm** [comment]
As someone who doesn't know much about the code in question, these changes look very nice for code clarity!

**Comment by pcwalton** [comment]
Could you use a `SmallVec` for the stack? This is performance critical code and I'm concerned about allocations.

**Comment by luniv** [comment]
Done. Used a SmallVec2, since I imagine the normal case would be just one level of nesting (e.g. a @media rule).

**Comment by larsbergstrom** [comment]
Please rebase this PR and then reopen. It has been temporarily closed to avoid generating excessive work for GitHub's servers.

**Comment by luniv** [comment]
I've re-based the branch, but not sure how to (or if I even can) reopen this PR.

**Comment by jdm** [comment]
Github doesn't allow reopening after rebasing, apparently. It's a confusing system.

**Pull request closed without merging**
