### PR TITLE
Implement HTMLCanvasElement#toDataURL

### PR DESCRIPTION
**Pull request by dzbarsky**
Confirmed that dumping the output of toDataUrl on toDataURL.png.primarycolours.html gives the same results as Firefox (including padding)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8200)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 31 of 31 files at r1.
Review status: 30 of 31 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 264 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8200#-K1XX6SLPTDVcKnFCyus)** ([raw file](https://github.com/servo/servo/blob/b36c856b29d5ad3d9ecf069a9375c60a242eeb88/components/script/dom/htmlcanvaselement.rs#L264)):</sup>
Let's name this _type so it's a bit clearer.


---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 276 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8200#-K1XWsQv9b6BoXMD1rHT)** ([raw file](https://github.com/servo/servo/blob/b36c856b29d5ad3d9ecf069a9375c60a242eeb88/components/script/dom/htmlcanvaselement.rs#L276)):</sup>
Panicking when we're using a webgl canvas seems like the wrong thing to do.


---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 292 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8200#-K1XWI5bUQTGIJQdVmQ3)** ([raw file](https://github.com/servo/servo/blob/b36c856b29d5ad3d9ecf069a9375c60a242eeb88/components/script/dom/htmlcanvaselement.rs#L292)):</sup>
Let's use `format!` here instead.


---

<sup>**[components/script/dom/webidls/HTMLCanvasElement.webidl, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8200#-K1XXD1rwr3zTnUP9yOE)** ([raw file](https://github.com/servo/servo/blob/b36c856b29d5ad3d9ecf069a9375c60a242eeb88/components/script/dom/webidls/HTMLCanvasElement.webidl#L23)):</sup>
Rather than adding a new method, I would be tempted to uncomment this line and comment out the `any... arguments` if they're causing a problem (with an appropriate issue filed).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8200)

**Comment by dzbarsky** [comment]
Review status: 0 of 31 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 276 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8200#-K1XWsQv9b6BoXMD1rHT)** ([raw file](https://github.com/servo/servo/blob/b36c856b29d5ad3d9ecf069a9375c60a242eeb88/components/script/dom/htmlcanvaselement.rs#L276)):</sup>
True. Firefox bails for webgl, we can do the same here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8200)

**Comment by dzbarsky** [comment]
Review status: 0 of 31 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 292 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8200#-K1XWI5bUQTGIJQdVmQ3)** ([raw file](https://github.com/servo/servo/blob/b36c856b29d5ad3d9ecf069a9375c60a242eeb88/components/script/dom/htmlcanvaselement.rs#L292)):</sup>
Oops forgot about this, will fix.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8200)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 31 of 31 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 276 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8200#-K1XWsQv9b6BoXMD1rHT)** ([raw file](https://github.com/servo/servo/blob/b36c856b29d5ad3d9ecf069a9375c60a242eeb88/components/script/dom/htmlcanvaselement.rs#L276)):</sup>
Bails in what way? https://www.khronos.org/registry/webgl/conformance-suites/1.0.2/conformance/canvas/to-data-url-test.html passes in Firefox for me.


---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 265 \[r3\]](https://reviewable.io:443/reviews/servo/servo/8200#-K1Xk0bd9VCHQWVYvY4Z)** ([raw file](https://github.com/servo/servo/blob/ed4455f0db8803a70f0e68ea3c860847ff689f4c/components/script/dom/htmlcanvaselement.rs#L265)):</sup>
nit: let's have one argument per line.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8200)

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[components/script/dom/htmlcanvaselement.rs, line 276 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8200#-K1XWsQv9b6BoXMD1rHT)** ([raw file](https://github.com/servo/servo/blob/b36c856b29d5ad3d9ecf069a9375c60a242eeb88/components/script/dom/htmlcanvaselement.rs#L276)):</sup>
I think I was looking at the IPC renderer stuff. I agree that this works in Firefox. Unfortunately my GL-fu is too weak to do this properly (the stupid way is to draw the webgl canvas into a 2d context and getImageData). But we could probably use a framebuffer and call readPixels or something. I'll file a followup.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8200)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8200)

**Pull request merged**
