### PR TITLE
Expose the source map URL on a style sheet

### PR DESCRIPTION
**Pull request by tromey**
This changes Servo to track the source map URL of a style sheet.  This
parallels a change going in to Gecko:
https://bugzilla.mozilla.org/show_bug.cgi?id=1388855

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix N/A - but see the bug in Bugzilla (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

Note also that there are tests going into M-C as well as part of bug 1388855.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18073)

### CODE REVIEW

**Comment by tromey** [comment]
I rebased it.

**Comment by tromey** [comment]
Rebased again.

**Comment by tromey** [comment]
Rebased again.

**Comment by SimonSapin** [comment]
Oops, sorry for the delay and multiple rebases.

Looks good.

@bors-servo r+

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18073#-:-KrkIZXF-k6QzxWxhKVB:bcr1lq8)*

**Pull request merged**
