### PR TITLE
Initial Step for OSS Project - M1503 - Integrate XML parser

### PR DESCRIPTION
**Pull request by Jigar24**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8234)

### CODE REVIEW

**Comment by eefriedman** [comment]
Welcome!

In general, if there's something wrong with your branch, don't close the pull request; you can just force-push any necessary changes to Ronak6892:xml, and the PR will update automatically.

**Comment by Jigar24** [comment]
Hello,

I have some merge conflicts in my branch and I resolved them in my forked repository but they still exists here. So I am working on resolving them. After that I will create a new pull request.
Thanks

**Comment by eefriedman** [comment]
Please leave the pull request open; if you need help with git, please ask on IRC (#servo on irc.mozilla.org).

**Comment by Manishearth** [comment]
For the record if you keep this pull request open, you can resolve merge conflicts and force-push to the same branch to update the pull request.

Also, try to rebase, not merge :smile:

**Pull request closed without merging**
