### PR TITLE
Renderrenderrenderrender: Now for embedding!

### PR DESCRIPTION
**Pull request by zmike**
A collection of commits which improves embedding integration and rendering.

@larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6125)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- components/compositing/compositor.rs @ r6, r7
- components/compositing/windowing.rs @ r7
- components/servo/Cargo.lock @ r16
- ports/cef/browser.rs @ r5, r10, r11
- ports/cef/browser_host.rs @ r12, r15
- ports/cef/core.rs @ r4, r5, r14
- ports/cef/interfaces/cef_browser.rs @ r1
- ports/cef/interfaces/cef_render_handler.rs @ r3
- ports/cef/macros.rs @ r2
- ports/cef/render_handler.rs @ r7
- ports/cef/window.rs @ r4, r7, r8, r9, r12, r13, r15
- ports/glutin/window.rs @ r7
- ports/gonk/Cargo.lock @ r16
- ports/gonk/src/window.rs @ r7

---

<sup>**[ports/cef/browser.rs, line 113 \[r10\]](https://reviewable.io:443/reviews/servo/servo/6125#-JphPGygct85XX5cFvv5)** ([raw file](https://github.com/servo/servo/blob/602e7cb8364815b0a67f249d0d86ff5cc627defd/ports/cef/browser.rs#L113)):</sup>
nit: can you outdent this line by 4 spaces to be under the `l` in `let`?

---

<sup>**[ports/cef/window.rs, line 179 \[r10\]](https://reviewable.io:443/reviews/servo/servo/6125#-JphPmZuZbUNXx5WFU4b)** ([raw file](https://github.com/servo/servo/blob/602e7cb8364815b0a67f249d0d86ff5cc627defd/ports/cef/window.rs#L179)):</sup>
It would be worth a comment here explaining what you mentioned in the commit message about the platform-specific differences here (we tend to document in-tree instead of just in-commit message).

---

<sup>**[ports/cef/window.rs, line 259 \[r16\]](https://reviewable.io:443/reviews/servo/servo/6125#-JphRDPT9SG29UcRNZzY)** ([raw file](https://github.com/servo/servo/blob/a12321405aac1401127730da1c5e57ecd41b8974/ports/cef/window.rs#L259)):</sup>
Please open an issue in the tracker for this

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6125)

**Comment by zmike** [comment]
Comments addressed.

**Comment by larsbergstrom** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- ports/cef/browser.rs @ r17
- ports/cef/window.rs @ r17

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6125)

**Comment by larsbergstrom** [comment]
```
failed to run custom build command for `x11 v1.1.0`
Process didn't exit successfully: `/Users/servo/buildbot/slave/mac1/build/components/servo/target/debug/build/x11-c15b07a09395e8a8/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"x11\"` did not exit successfully: exit code: 1\n--- stderr\nPackage x11 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `x11.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'x11\' found\n"', /Users/larsberg/rust/src/libcore/result.rs:729
stack backtrace:
   1:        0x1043844ef - sys::backtrace::write::h6990067d88907b48zVr
   2:        0x10438cec4 - panicking::on_panic::he976cdbadffd9e1bEVv
   3:        0x104348ed5 - rt::unwind::begin_unwind_inner::ha519446d83876aa8nDv
   4:        0x104349d0c - rt::unwind::begin_unwind_fmt::h15c2d4adf8e8ecdatCv
   5:        0x10438c6bc - rust_begin_unwind
   6:        0x1043df495 - panicking::panic_fmt::haa553fbfab6eff2cNKy
   7:        0x1042fa5d3 - result::Result<T, E>::unwrap::h433998647731156453
   8:        0x1042fa376 - main::h319e68eb64359d51faa
   9:        0x104412278 - rust_try_inner
  10:        0x104412265 - rust_try
  11:        0x10438d948 - rt::lang_start::h62b79b4f7043bc7a9Pv
  12:        0x1042fcf1e - main
```

**Comment by zmike** [comment]
No idea why this failed or how to fix it.

**Comment by jdm** [comment]
The problem is https://github.com/alexcrichton/pkg-config-rs/blob/master/src/lib.rs#L152 . @alexcrichton do you have a suggestion for how we can use x11-rs while cross-compiling?

**Comment by alexcrichton** [comment]
@jdm this is likely a problem that x11-rs itself will need to deal with. You can see if the build works by just setting the environment variable `PKG_CONFIG_ALLOW_CROSS=1`, but that means that the cross-compiled build to android will link against the host's libraries, which probably won't work. The x11-rs package will either need to say `links = "x11"` and then you provide a Cargo override saying where those libraries are located for android, or you need to make sure that android doesn't depend on this crate.

**Comment by larsbergstrom** [comment]
@alexcrichton Do you have an example of the latter? I'm assuming we will have to do that for every submodule we use that moves to pkg-config.

I was looking at http://doc.crates.io/build-script.html#the-links-manifest-key but it wasn't clear to me how to make those changes on a per-feature basis for each of the libraries in https://github.com/Daggerbot/x11-rs/blob/cb7aa1a7daf9ed50bacc2466e0da722c128c7ac4/x11/Cargo.toml - presumably the idea is that we create a .rs file per library, only enable it if the feature is enabled, and have explicit code in there to call out to try and find the library in the cross-compilation search path if we are cross-compiling, and otherwise fall back to pkg-config? Or are you thinking of some other setup?

**Comment by larsbergstrom** [comment]
@alexcrichton I think the problem here is actually that glutin has a linux-target-only dependency on X11, but on linux host cross-compiling for android target, that dependency is still getting pulled in. See:
https://github.com/servo/glutin/blob/servo/Cargo.toml#L30-L57

If we remove @zmike's last commit (b5050c78), which adds the x11 entry to Cargo.lock that cargo was adding, we still get the same error. What are we doing wrong?

**Comment by larsbergstrom** [comment]
hrm, maybe it's rust-layers pulling in x11 on cross-compiles and not glutin? It looks like we picked up @daggerbot's change https://github.com/servo/rust-layers/commit/dfe2307537a7d9b6bcc768bba337656168e1f0ab, which is not a target-specific dependency on x11 and maybe that's what's breaking us...

**Comment by larsbergstrom** [comment]
Yup, once https://github.com/servo/rust-layers/pull/164 lands we should be able to get that, remove the b505c78 change and land this.

**Comment by larsbergstrom** [comment]
omg
```
Submodule 'support/android-rs-glue' (https://github.com/tomaka/android-rs-glue) registered for path 'support/android-rs-glue'
Cloning into 'support/android-rs-glue'...
Submodule path 'support/android-rs-glue': checked out 'dc8aef3e1b8f1acd141986cfab492e3f57d2d5f6'
    Updating git repository `https://github.com/servo/rust-layers`
failed to select a version for `pkg-config` (required by `openssl-sys`):
all possible versions conflict with previously selected versions of `pkg-config`
  version 0.3.3 in use by pkg-config v0.3.3
  possible versions to select: 0.3.4
Build completed in 0.83s
program finished with exit code 101
elapsedTime=3.301274
```

sigh.

**Comment by larsbergstrom** [comment]
maybe try `./mach update-cargo -p pkg-config`? I have to leave for the day soon, r=me if that magically makes cargo happy.

**Comment by larsbergstrom** [comment]
looks like it needs a rebase?

**Comment by zmike** [comment]
Rebased...

**Comment by larsbergstrom** [comment]
hrm, still says " We can’t automatically merge this pull request. "

**Comment by zmike** [comment]
Says it's up to date here.

**Comment by larsbergstrom** [comment]
```
/home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_glx/native_gl_context.rs:97:22: 97:57 error: mismatched types:
 expected `*mut x11::xlib::_XDisplay`,
    found `*mut libc::types::common::c95::c_void`
(expected enum `x11::xlib::_XDisplay`,
    found enum `libc::types::common::c95::c_void`) [E0308]
/home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_glx/native_gl_context.rs:97             display: self.native_display as *mut Display,
                                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_glx/native_gl_context.rs:97:22: 97:57 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `offscreen_gl_context`.

To learn more, run the command again with --verbose.
Build completed in 228.21s
program finished with exit code 101
elapsedTime=230.326099
```

Awesome.

**Comment by larsbergstrom** [comment]
yup, x11 hard dependency in one of our subdependencies again :-/

**Comment by larsbergstrom** [comment]
I'll try and figure out who the awesome package is and do the usual again:
https://github.com/servo/rust-layers/commit/327bbe38aa1825adf0b1292d7718645ad36a3f38

**Comment by larsbergstrom** [comment]
Once https://github.com/ecoal95/rust-offscreen-rendering-context/pull/4 lands we should be able to pick that up and be past this failure.

**Comment by larsbergstrom** [comment]
@Daggerbot That sounds great, thanks!

@zmike Can you do `./mach update-cargo -p x11` and push up the extra commit for me to r+? That should provide an easy workaround for this issue.

**Comment by zmike** [comment]
Done

**Comment by larsbergstrom** [comment]
yay.
```
/Users/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_cgl/native_gl_context.rs:4:31: 4:46 error: unresolved import `core_foundation::bundle::CFBundleGetBundleWithIdentifier`. Maybe a missing `extern crate core_foundation`?
/Users/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_cgl/native_gl_context.rs:4 use core_foundation::bundle::{CFBundleGetBundleWithIdentifier, CFBundleGetFunctionPointerForName};
                                                                                                                                                                      ^~~~~~~~~~~~~~~
/Users/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_cgl/native_gl_context.rs:4:64: 4:79 error: unresolved import `core_foundation::bundle::CFBundleGetFunctionPointerForName`. Maybe a missing `extern crate core_foundation`?
/Users/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_cgl/native_gl_context.rs:4 use core_foundation::bundle::{CFBundleGetBundleWithIdentifier, CFBundleGetFunctionPointerForName};
                                                                                                                                                                                                       ^~~~~~~~~~~~~~~
/Users/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_cgl/native_gl_context.rs:5:5: 5:20 error: unresolved import `core_foundation::base::TCFType`. Maybe a missing `extern crate core_foundation`?
/Users/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_cgl/native_gl_context.rs:5 use core_foundation::base::TCFType;
                                                                                                                                            ^~~~~~~~~~~~~~~
/Users/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_cgl/native_gl_context.rs:6:5: 6:20 error: unresolved import `core_foundation::string::CFString`. Maybe a missing `extern crate core_foundation`?
/Users/servo/.cargo/git/checkouts/rust-offscreen-rendering-context-902f85b061901132/master/src/platform/with_cgl/native_gl_context.rs:6 use core_foundation::string::CFString;
                                                                                                                                            ^~~~~~~~~~~~~~~
error: aborting due to 4 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `offscreen_gl_context`.

To learn more, run the command again with --verbose.
Build completed in 152.90s
```

**Comment by ecoal95** [comment]
That was my fault, a cargo-update will make it work now.

By the way, should we specify x11 = "*" in the deps as we do with libc etc, to make these changes only depend of servo?

**Comment by larsbergstrom** [comment]
@ecoal95 Thanks for the quick fix! I do think wildcards make sense for version dependencies like that, since you don't have a minimum and with the x11 FFI types "leaking out" Servo sort of needs to force a common version across all submodules.

@zmike Can you `./mach update-cargo -p offscreen_gl_context` and push up a new commit for us to try?

**Comment by zmike** [comment]
Executing Order 66.

**Comment by larsbergstrom** [comment]
hahahahaha, but at least we can fix this one ourselves
```
/home/servo/buildbot/slave/linux2/build/ports/glutin/window.rs:691:5: 693:6 error: method `prepare_for_composite` has 1 parameter but the declaration in trait `compositing::windowing::WindowMethods::prepare_for_composite` has 3 [E0050]
/home/servo/buildbot/slave/linux2/build/ports/glutin/window.rs:691     fn prepare_for_composite(&self) -> bool {
/home/servo/buildbot/slave/linux2/build/ports/glutin/window.rs:692         true
/home/servo/buildbot/slave/linux2/build/ports/glutin/window.rs:693     }
/home/servo/buildbot/slave/linux2/build/ports/glutin/window.rs:691:5: 693:6 help: run `rustc --explain E0050` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `glutin_app`.
```

**Comment by zmike** [comment]
It's...possible...? Except that it's also ARM DAYYYYYYYYY

**Comment by larsbergstrom** [comment]
I have a fix locally, but am testing to make sure there are no more gotchas. Will open a PR against your PR so you can PR while you PR.

**Comment by larsbergstrom** [comment]
@zmike opened https://github.com/zmike/servo/pull/2; seems to work locally in my Linux VM.

**Comment by zmike** [comment]
Err I already pushed the fix before you PRed my PR?

**Comment by zmike** [comment]
HAHAHAHAHA

**Comment by larsbergstrom** [comment]
```
note: /usr/bin/ld: /home/servo/buildbot/slave/linux1/build/components/servo/target/debug/deps/libglutin-bf8dbe3e22b31c8a.rlib(glutin-bf8dbe3e22b31c8a.o): undefined reference to symbol 'XF86VidModeSetViewPort'
//usr/lib/x86_64-linux-gnu/libXxf86vm.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Could not compile `servo`.
```

**Comment by larsbergstrom** [comment]
@bjz it looks like gl_generator is not including libXxf86vm.so to the link lines - any idea what we're doing wrong here?

**Comment by larsbergstrom** [comment]
Or are we just supposed to add a linux-only `#[link="Xxf86vm"] extern {}` somewhere for this binding?

**Comment by larsbergstrom** [comment]
Hrm, strange, it's actually in the generated code:
```
./git/checkouts/glutin-666c1766c69e6584/master/src/x11/ffi.rs:#[link(name = "Xxf86vm")]
```
But it's not ending up in the link commandline :-/

**Comment by larsbergstrom** [comment]
Aha, on that builder it's building with `SERVO_HEADLESS=1`, which means that the `window` feature is not enabled, which means we won't get that `#[link...]` line, but also that we shouldn't be picking up that binding. Hrm.

**Comment by larsbergstrom** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- components/compositing/compositor.rs @ r18
- components/servo/Cargo.lock @ r24
- ports/cef/browser.rs @ r20
- ports/cef/browser_host.rs @ r18
- ports/cef/Cargo.lock @ r24
- ports/cef/lib.rs @ r21
- ports/cef/window.rs @ r21
- ports/glutin/Cargo.toml @ r21
- ports/glutin/lib.rs @ r21
- ports/glutin/window.rs @ r25
- ports/gonk/Cargo.lock @ r24
- ports/gonk/src/window.rs @ r18

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6125)

**Comment by larsbergstrom** [comment]
Aha! I believe that with the new x11, we need to set not only the `x11` feature, but also the `xf86vmode` feature: https://github.com/Daggerbot/x11-rs/blob/master/x11/build.rs#L10

**Comment by larsbergstrom** [comment]
OK, I think if we merge https://github.com/servo/glutin/pull/28 and pick up a reference to it in this PR, we're good. Servo appears to build both with/without headless mode enabled with that fix.

**Comment by zmike** [comment]
@larsbergstrom I HAVE COMPLETED THE UPDATE AND AM AWAITING TEST RESULTS

**Comment by larsbergstrom** [comment]
@zmike I HAVE HEARD THE SIXTH TIME IS THE CHARM

**Comment by zmike** [comment]
@larsbergstrom I THINK THAT'S ONLY WHEN COUNTING SETS ON BENCH

**Comment by alexcrichton** [comment]
@larsbergstrom 

These questions may have already been answered as this was merged, but...

> Do you have an example of the latter?

Ah yes I was thinking specifically of target-specific dependencies (as you pointed out), by having all platforms but android depend on the x11 libraries (if android doesn't need them)

> I think the problem here is actually that glutin has a linux-target-only dependency on X11, but on linux host cross-compiling for android target, that dependency is still getting pulled in.

Interesting! How come glutin is being compiled for this host?

**Comment by larsbergstrom** [comment]
@alexcrichton 

> Interesting! How come glutin is being compiled for this host? 

From what I can tell, almost none of our dependencies have yet switched to platform-specific Cargo dependency links and instead use `#[cfg(target_os=...)]` blocks in their lib.rs file. This particular problem was that glutin just had a dependency on x11, which used to do nothing on platforms where it would not be used, but the move to pkg-config broke that. The x11 package has since been updated to make that cleaner, but I suspect we should start transitioning all of our platform-specific dependencies to use the Cargo features, if only to avoid seeing `rust-core-foundation` show up when cross-compiling for Android :-)

**Comment by alexcrichton** [comment]
@larsbergstrom ah ok that makes sense. Currently the main use-case I know of for platform-specific dependencies is precisely this, just avoiding compilation of native dependencies. Note that you may run into https://github.com/rust-lang/cargo/issues/1007 where the current syntax may unfortunately be a little verbose.

**Pull request merged**
