### PR TITLE
Update azure and avoid stdc++ linking hacks on gonk

### PR DESCRIPTION
**Pull request by michaelwu**
This fix seems to work here. Hopefully it also works with the automation.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5796)

### CODE REVIEW

**Comment by jdm** [comment]
```
note: /home/servo/buildbot/slave/gonk/build/ports/gonk/target/arm-linux-androideabi/debug/deps/libazure-cc187b961189251d.rlib(r-azure-DrawEventRecorder.o):DrawEventRecorder.cpp:function std::ostream::write(char const*, int): error: undefined reference to 'std::uncaught_exception()'
/home/servo/buildbot/slave/gonk/build/ports/gonk/target/arm-linux-androideabi/debug/deps/libazure-cc187b961189251d.rlib(r-azure-RecordedEvent.o):RecordedEvent.cpp:function mozilla::gfx::RecordedPathCreation::RecordToStream(std::ostream&) const: error: undefined reference to 'std::uncaught_exception()'
/home/servo/buildbot/slave/gonk/build/ports/gonk/target/arm-linux-androideabi/debug/deps/libazure-cc187b961189251d.rlib(r-azure-RecordedEvent.o):RecordedEvent.cpp:function mozilla::gfx::RecordedPathCreation::RecordToStream(std::ostream&) const: error: undefined reference to 'std::uncaught_exception()'
/home/servo/buildbot/slave/gonk/build/ports/gonk/target/arm-linux-androideabi/debug/deps/libazure-cc187b961189251d.rlib(r-azure-RecordedEvent.o):RecordedEvent.cpp:function mozilla::gfx::RecordedPathCreation::RecordToStream(std::ostream&) const: error: undefined reference to 'std::uncaught_exception()'
collect2: error: ld returned 1 exit status
```

**Comment by michaelwu** [comment]
Added a new commit to fix our stlport includes.

**Comment by michaelwu** [comment]
This requires $GONKDIR/abi to be available on the build machine. I have no idea how the builds are setup.

**Comment by jdm** [comment]
```
note: /home/servo/buildbot/slave/gonk/build/ports/gonk/target/arm-linux-androideabi/debug/deps/libazure-cc187b961189251d.rlib(r-azure-DrawEventRecorder.o):DrawEventRecorder.cpp:function std::ostream::write(char const*, int): error: undefined reference to 'std::uncaught_exception()'
/home/servo/buildbot/slave/gonk/build/ports/gonk/target/arm-linux-androideabi/debug/deps/libazure-cc187b961189251d.rlib(r-azure-RecordedEvent.o):RecordedEvent.cpp:function mozilla::gfx::RecordedPathCreation::RecordToStream(std::ostream&) const: error: undefined reference to 'std::uncaught_exception()'
/home/servo/buildbot/slave/gonk/build/ports/gonk/target/arm-linux-androideabi/debug/deps/libazure-cc187b961189251d.rlib(r-azure-RecordedEvent.o):RecordedEvent.cpp:function mozilla::gfx::RecordedPathCreation::RecordToStream(std::ostream&) const: error: undefined reference to 'std::uncaught_exception()'
/home/servo/buildbot/slave/gonk/build/ports/gonk/target/arm-linux-androideabi/debug/deps/libazure-cc187b961189251d.rlib(r-azure-RecordedEvent.o):RecordedEvent.cpp:function mozilla::gfx::RecordedPathCreation::RecordToStream(std::ostream&) const: error: undefined reference to 'std::uncaught_exception()'
collect2: error: ld returned 1 exit status
```

**Comment by jdm** [comment]
This also breaks the android builder:
```
note: /home/servo/ndk-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lstlport
```

**Comment by larsbergstrom** [comment]
Did a completely clean gonk build (blew away my cargo repo) locally to test this, and the stdc++ link lines still present were:
```
larsberg@ubuntu:~/servo$ find . -name '*.rs' | xargs grep -e "\"stdc++\"" | grep link                                                                     
./.cargo/git/checkouts/rust-azure-03a3575c638f374d/master/src/linkhack.rs:#[link(name = "stdc++")]
./.cargo/git/checkouts/rust-azure-03a3575c638f374d/master/src/linkhack.rs:#[link(name = "stdc++")]
./.cargo/git/checkouts/rust-mozjs-ab9bfe6e592bc16c/master/src/linkhack.rs:#[link(name = "stdc++")]
./.cargo/git/checkouts/rust-mozjs-ab9bfe6e592bc16c/master/src/linkhack.rs:#[link(name = "stdc++")]
./.cargo/git/checkouts/rust-mozjs-ab9bfe6e592bc16c/master/src/glue.rs:#[link(name = "stdc++")]
./.cargo/git/checkouts/rust-harfbuzz-7808d225c82545c4/master/src/linkhack.rs:#[link(name = "stdc++")]
./.cargo/git/checkouts/rust-harfbuzz-7808d225c82545c4/master/src/linkhack.rs:#[link(name = "stdc++")]
```

**Comment by larsbergstrom** [comment]
We will probably want to wait for the in-progress rust upgrade to land, as rust-mozjs and rust-harfbuzz have already been updated to 1.0.

**Comment by larsbergstrom** [comment]
The rust upgrade has landed, so work on this can be rebased and begun again, also pushing the stdc++ ->stlport changes into rust-harfbuzz and rust-mozjs.

**Comment by michaelwu** [comment]
I landed a working version of this fix as part of #6150

**Pull request closed without merging**
