### PR TITLE
Update WR and shaders (initial subpixel AA work).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14122)

### CODE REVIEW

**Comment by glennw** [comment]
@emilio This fails tidy at the moment with the rayon update in WR. What's the plan for updating rayon?

**Comment by emilio** [comment]
@glennw I took care of all the dependencies, so `./mach cargo-update -p jpeg-decoder` should get rid of the old rayon version.

r=me with that if you whish :)

**Pull request merged**
