### PR TITLE
Update CSS tests to revision f3fcc824c64126b77c8c9856e89989b66c3a7e5d

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9656)

### CODE REVIEW

**Comment by jdm** [comment]
Why disable the manifest check?

**Comment by Ms2ger** [comment]
@bors-servo retry
* #9012

**Comment by jdm** [comment]
@bors-servo: retry
* service interruption

**Comment by jdm** [comment]
```
  ▶ FAIL [expected PASS] /css-text-3_dev/html/text-transform-capitalize-014.htm
  └   → /css-text-3_dev/html/text-transform-capitalize-014.htm b89dfd66ef20553565f4e7f15bcbe42a1506735d
/css-text-3_dev/html/reference/text-transform-capitalize-014-ref.htm 3f3f18282cb8d48a862cd4d688f3150718c0cd00
Testing b89dfd66ef20553565f4e7f15bcbe42a1506735d == 3f3f18282cb8d48a862cd4d688f3150718c0cd00

  ▶ FAIL [expected PASS] /css-text-3_dev/html/text-transform-capitalize-018.htm
  └   → /css-text-3_dev/html/text-transform-capitalize-018.htm dcb3176c253bec002e4cd2db1abfe023ee6614bb
/css-text-3_dev/html/reference/text-transform-capitalize-018-ref.htm 01f68d78f3c9a36b162a6a3cd413f2d554667ff3
Testing dcb3176c253bec002e4cd2db1abfe023ee6614bb == 01f68d78f3c9a36b162a6a3cd413f2d554667ff3

  ▶ FAIL [expected PASS] /css-text-3_dev/html/text-transform-upperlower-028.htm
  └   → /css-text-3_dev/html/text-transform-upperlower-028.htm 2295aaf97e437eaa0597710d73d44031c856cf2e
/css-text-3_dev/html/reference/text-transform-upperlower-028-ref.htm e66da2b1666362ae5f5e3de7924034254a428890
Testing 2295aaf97e437eaa0597710d73d44031c856cf2e == e66da2b1666362ae5f5e3de7924034254a428890

  ▶ FAIL [expected PASS] /css-text-3_dev/html/text-transform-upperlower-029.htm
  └   → /css-text-3_dev/html/text-transform-upperlower-029.htm 699aaf30767f8c6e4f1c5fba3b4e3cd32019cb8d
/css-text-3_dev/html/reference/text-transform-upperlower-029-ref.htm 33921958affd6eaebd40b3a5f194a5d9cc23baf0
Testing 699aaf30767f8c6e4f1c5fba3b4e3cd32019cb8d == 33921958affd6eaebd40b3a5f194a5d9cc23baf0

  ▶ FAIL [expected PASS] /css-text-3_dev/html/text-transform-upperlower-101.htm
  └   → /css-text-3_dev/html/text-transform-upperlower-101.htm 7e02b9c673b825c190ef0977e303ea3642fce4e5
/css-text-3_dev/html/reference/text-transform-upperlower-101-ref.htm 5935d324f2966d4343d96d0bb83166544a489c08
Testing 7e02b9c673b825c190ef0977e303ea3642fce4e5 == 5935d324f2966d4343d96d0bb83166544a489c08
```

**Comment by Ms2ger** [comment]
I suspect the issue here is that we split a two-byte sequence into separate chunks when parsing; #9677 might fix that.

**Comment by jdm** [comment]
@ms2ger What do you want to do here?

**Comment by Ms2ger** [comment]
I was hoping https://github.com/servo/servo/pull/9730 would go through. I suppose I'll just have to disable a bunch of these tests.

**Comment by jdm** [comment]
Ok, I'll take a look at the new revisions there and we can hold off making a decision here for a bit longer.

**Comment by jdm** [comment]
Nevermind, I misinterpreted the status there.

**Pull request closed without merging**
