### PR TITLE
Make another webgl test have a longer timeout.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23876)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Try again... @bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* network issue

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Pull request merged**
