### PR TITLE
Initialize trusted-ness of DOM events properly

### LINKED ISSUE #3740: Initialize trusted-ness of DOM events properly
* DispatchEvent needs to set trusted to false (https://dom.spec.whatwg.org/#dom-eventtarget-dispatchevent)
* Internal code that creates events needs to ensure that they're trusted by default (https://dom.spec.whatwg.org/#concept-event-fire) (ie. load event, click events, etc.)
* EventTarget needs a helper method that can dispatch an event without modifying its trusted-ness which can be called by dispatch_event_with_target
* Events created by script should be untrusted by default (https://dom.spec.whatwg.org/#dom-event-istrusted and https://dom.spec.whatwg.org/#concept-event-initialize)
* Any initialization by internal code needs to make sure that it doesn't call methods that force trustedness to false

### PR DESCRIPTION
**Pull request by gilles-leblanc**
Fixes #3740

### CODE REVIEW

**Comment by jdm** [comment]
Sorry for the delay; the Rust upgrade got in the way. I've left comments on Critic.

**Comment by gilles-leblanc** [comment]
No problem, I had read the meeting notes and I was aware of the reason.

**Comment by jdm** [comment]
@Manishearth Could you comment on https://critic.hoppipolla.co.uk/showcomment?chain=10259 ?

**Comment by gilles-leblanc** [comment]
If we're unsure I'll change it like you said. You know more about HTML specifications than I do. @Manishearth could please you have a quick check before I do?

**Comment by Manishearth** [comment]
Done.

**Comment by gilles-leblanc** [comment]
Thanks.

**Comment by gilles-leblanc** [comment]
I addressed the final review comments and submitted a new commit.

**Comment by gilles-leblanc** [comment]
I've addressed the latest review comments. I'll wait for the ok (or additional comments) before rebasing/merging conflicts.

**Comment by jdm** [comment]
Squash and rebase! Thanks for doing this work!

**Comment by gilles-leblanc** [comment]
Done. Rebased, squashed, forced pushed.

Thanks to you @jdm and to @Manishearth  for taking the time to do the review !

**Pull request merged**
