### PR TITLE
Implement cancellable runnables, and make image load events cancellab…

### LINKED ISSUE #7731: Intermittent Option::unwrap() panic in  /dom/nodes/Document-createElement-namespace.html
```
3:35.82 TEST_START: Thread-TestrunnerManager-1 /dom/nodes/Document-createElement-namespace.html
3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) Full command: /Users/servo/buildbot/slave/mac-rel-wpt/build/target/release/servo --cpu --hard-fail -u Servo/wptrunner -z http://localhost:8000/dom/nodes/Document-createElement-namespace.html --user-stylesheet /Users/servo/buildbot/slave/mac-rel-wpt/build/resources/ahem.css
(pid:13632) "thread 'ScriptTask PipelineId(0)' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:365"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "stack backtrace:"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "   1:        0x108b107b0 - sys::backtrace::tracing::imp::write::h88885f5c2d394b3flbt"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "   2:        0x108b0f913 - panicking::on_panic::h7a7974779bbfef81TZw"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "   3:        0x108b000e2 - sys_common::unwind::begin_unwind_inner::h879cfd5a30161a9evas"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "   4:        0x108b0060e - sys_common::unwind::begin_unwind_fmt::h86e9e878cb969fb5B9r"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "   5:        0x108b0f197 - rust_begin_unwind"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "   6:        0x108b351a0 - panicking::panic_fmt::h74e66b6fcc9eaf3cwZK"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "   7:        0x108b30d2c - panicking::panic::he6e1bfb72056e4793XK"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "   8:        0x107b69e41 - dom::window::Window::get_cx::h0ca1665a8f918635Irh"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "   9:        0x107df1173 - dom::event::Event::new_uninitialized::h01057e8259df5c71eJS"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  10:        0x107dda968 - dom::event::Event::new::h452f23c3aa82337buJS"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  11:        0x107e62341 - dom::htmlimageelement::ImageResponseHandlerRunnable.Runnable::handler::h6a9e726ff89f4fef49Y"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  12:        0x107f55df3 - script_task::ScriptTask::handle_msg_from_script::h92612835436a05f5xen"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  13:        0x107f719a8 - script_task::ScriptTask::handle_msgs::closure.151864"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  14:        0x107f5f162 - script_task::ScriptTask::handle_msgs::hfc1dfd86d8826f59tZm"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  15:        0x107f4b567 - boxed::F.FnBox<A>::call_box::h13207957566832505401"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  16:        0x107b23832 - sys_common::unwind::try::try_fn::h2178713618348901180"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  17:        0x108b0efd8 - __rust_try"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  18:        0x108b0c3a0 - sys_common::unwind::try::inner_try::h30a7e5c7446717a0T6r"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  19:        0x107b239d7 - boxed::F.FnBox<A>::call_box::h14260401093029468028"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  20:        0x108b1147d - sys::thread::Thread::new::thread_start::h6e92c6728040a269Mxw"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  21:     0x7fff8cbf6267 - _pthread_body"
 3:36.31 PROCESS_OUTPUT: Thread-TestrunnerManager-1 (pid:13632) "  22:     0x7fff8cbf61e4 - _pthread_start"
 3:50.85 TEST_END: Thread-TestrunnerManager-1 TIMEOUT, expected OK
```

This comes from Window::get_cx:
```
231     pub fn get_cx(&self) -> *mut JSContext {
232         self.js_runtime.borrow().as_ref().unwrap().cx()
233     }
```
We have an image load notification occurring which is trying to dispatch a DOM event after we've already torn down the JS runtime (or haven't created it, but that seems unlikely).

### PR DESCRIPTION
**Pull request by jdm**
…le. Resolves #7731.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8138)

### CODE REVIEW

**Comment by nox** [comment]
Seems good; just one nit and question. If you could rewrite the commit message to a short title and a body it would be perfect.

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/window.rs, line 69 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8138#-K1GVoZrQEAXXSKOCReJ)** ([raw file](https://github.com/servo/servo/blob/ea15377ebf6b54aa1c48d86586c7485b3041ec6c/components/script/dom/window.rs#L69)):</sup>
Nit: that space.


---

<sup>**[components/script/script_task.rs, line 170 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8138#-K1GX3IqdiNdfhtlb4nT)** ([raw file](https://github.com/servo/servo/blob/ea15377ebf6b54aa1c48d86586c7485b3041ec6c/components/script/script_task.rs#L170)):</sup>
Couldn't we avoid the nested boxes, somehow?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8138)

**Comment by jdm** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/script_task.rs, line 170 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8138#-K1GX3IqdiNdfhtlb4nT)** ([raw file](https://github.com/servo/servo/blob/ea15377ebf6b54aa1c48d86586c7485b3041ec6c/components/script/script_task.rs#L170)):</sup>
I can't figure out how, since Runnable::handler requires `self: Box<Self>` and I can't call it without `inner` being boxed.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8138)

**Comment by jdm** [comment]
Nit fixed. Let's kill off an annoying intermittent test failure!

**Pull request merged**
