### PR TITLE
Bring back run_with_memory_reporting in serviceworkerglobalscope

### PR DESCRIPTION
**Pull request by creativcoder**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [X] These changes do not require tests because its a refactor.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12557)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/serviceworkerglobalscope.rs, line 181 \[r1\]](https://reviewable.io:443/reviews/servo/servo/12557#-KNXNNBWrwSdAmn7h_kz:-KNXNNBXF6TzYRbxf1om:-654037143) ([raw file](https://github.com/servo/servo/blob/5010553983e5bcaf74378fd1889b19f1d8ab68b5/components/script/dom/serviceworkerglobalscope.rs#L181)):*
> ```Rust
>             });
> 
>             let reporter_name = format!("ServiceWorker-reporter-{}", random::<u64>());
> ```

The previous name for this reporter was `service-worker-reporter`, could you name it back like that and rename `service-worker-reporter` in `components/script/dom/dedicatedworkerglobalscope.rs` to `dedicated-service-worker-reporter`?

Thanks for your contribution!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12557#-:-KNXNOoNVpiq1zrFSMRy:1458266033)*

**Comment by creativcoder** [comment]
@nox this has been updated.

**Comment by KiChjang** [comment]
@bors-servo retry
* wat

**Comment by creativcoder** [comment]
```
Ran 6801 tests finished in 818.0 seconds.
  • 6800 ran as expected. 1998 tests skipped.
  • 1 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /html/browsers/history/the-history-interface/001.html:
  │ FAIL [expected PASS] pushState should not actually load the new URL
  │   → assert_true: expected true got undefined
  │ 
  │ tests12/<@http://web-platform.test:8000/html/browsers/history/the-history-interface/001.html:283:13
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1402:20
  │ test@http://web-platform.test:8000/resources/testharness.js:500:9
  └ tests12@http://web-platform.test:8000/html/browsers/history/the-history-interface/001.html:282:9
```
This seems unrelated to the changes made in this PR. @KiChjang Is that an intermittent ?

**Comment by KiChjang** [comment]
@bors-servo retry
* #12580

**Pull request merged**
