### PR TITLE
Removed our copy of Utf16Encoder in favor of the built-in equivalent

### PR DESCRIPTION
**Pull request by rarbor-old**
I am fairly certain I didn't break anything. I removed the code in question, cleaned, rebuilt, and tested. Issue #4725

### CODE REVIEW

**Comment by hgentry** [comment]
Condensed.

**Comment by jdm** [comment]
Oh, did you build with `./mach build-cef`? This code isn't build by default.

**Comment by hgentry** [comment]
I did not. Never heard of it. I'll take a look

**Comment by hgentry** [comment]
A different file, one I didn't touch, fails with build-cef. Should I go ahead and fix the unresolved import? Everything else build-cef does works.

build.rs:4:5: 4:22 error: unresolved import `std::old_io::File`. Could not find `old_io` in `std`
build.rs:4 use std::old_io::File;

**Comment by jdm** [comment]
Uh oh, that sounds like you ended up acquiring a newer version of one of our dependencies. Could you rebase these changes on top of master and try again? I think that problem may have already been fixed.

**Comment by SimonSapin** [comment]
@hgentry The old_io thing is an unrelated problem that was my fault. Sorry! It should be fixed in #4794, which you should get by rebasing on top of master as @jdm said.

**Comment by hgentry** [comment]
It looks to me that rustc doesn't actually recognize the unicode crate at the moment. Am I missing something? 

unresolved import `unicode::str::Utf16Encoder`. Maybe a missing `extern crate unicode`?
window.rs:14 use unicode::str::Utf16Encoder;

**Comment by jdm** [comment]
Did you add a `extern crate unicode` to the list in lib.rs?

**Comment by hgentry** [comment]
...I did now. I'm still not 100% on rust. -_-

**Comment by jdm** [comment]
Great! If you could squash these commits together into one, I'd be happy to merge them.

**Comment by Ms2ger** [comment]
This is now #4890. Thanks!

**Pull request closed without merging**
