### PR TITLE
Various UWP GStreamer improvements

### LINKED ISSUE #23742: ServoApp can't launch when packaged with UWP GStreamer binaries
With https://github.com/jdm/servo/commit/8dd3f878939d3d11756d7b980669834274d0b5fd applied, launching the UWP Servo app triggers a panic when it can't load any of the GStreamer plugins. They all depend on vcruntime140_app.dll and msvcrt_app.dll which aren't present in the generated AppX.

### PR DESCRIPTION
**Pull request by jdm**
There are a number of positive changes in these commits:
* we successfully load GStreamer plugins in ARM64 UWP builds
* we correctly link the ARM64 ANGLE libraries when appropriate
* it is no longer necessary to manually set the LIB environment variable on Windows
* we automatically download and link against UWP-friendly GStreamer binaries when building with `--uwp`
* the use of vcruntime140.dll, msvcp140.dll and api-ms-win-crt-runtime-l1-1-0.dll in the UWP application has been removed and the build does not repackage them
* the set of base supporting GStreamer DLLs has been expanded to allow the gstlibav plugin to load correctly

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23742
- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23863)

### CODE REVIEW

**Comment by ferjm** [comment]
LGTM. Thanks!

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #22955

**Pull request merged**
