### PR TITLE
Implement Body.bgColor and Document.bgColor

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5868)

### CODE REVIEW

**Comment by nox** [comment]
s/background/bgColor/ once it's reviewed.

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/document.rs @ r2
- components/script/dom/htmlbodyelement.rs @ r2
- components/script/dom/webidls/Document.webidl @ r2
- components/script/dom/webidls/HTMLBodyElement.webidl @ r2
- tests/wpt/metadata/html/dom/interfaces.html.ini @ r2
- tests/wpt/metadata/html/dom/reflection-sections.html.ini @ r2
- tests/wpt/metadata/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/document-color-02.html.ini @ r2
- tests/wpt/metadata/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/document-color-03.html.ini @ r2
- tests/wpt/metadata/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/document-color-04.html.ini @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5868)

**Comment by Ms2ger** [comment]
@bors-servo: retry
* #5798

**Pull request merged**
