### PR TITLE
Use DOM width/height for canvas display list item.

### LINKED ISSUE #10705: Initial canvas creation relies on DOM width and height attributes, but layout relies on computed width and height
Tests like `texture-size-limit.html` in the webgl suite use `<canvas id="example" width="32" height="32" style="width: 40px; height: 40px;"></canvas>` and this screws us up in a delightful fashion, since `HTMLCanvasElement::get_size` uses `Width()` and `Height()`. This is a cause of assertions where the pixel data retrieved from webgl doesn't match the stride * height that layout expects.

cc @emilio

### PR DESCRIPTION
**Pull request by jdm**
Fixes #10705.

r? @glennw

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10727)

### CODE REVIEW

**Comment by jdm** [comment]
It's possible that we should be using the computed width and height for the stretch_size, rather than the stacking-relative content box. What would be a good testcase for that?

**Comment by jdm** [comment]
Actually, this may be more @pcwalton's ballpark.

r? @pcwalton and see previous question.

**Comment by Ms2ger** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[tests/wpt/mozilla/tests/css/canvas_scale.html, line 3 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10727#-KFmYYGccxka8NBskRim:-KFmYYGccxka8NBskRin:-455029382) ([raw file](https://github.com/servo/servo/blob/bc7a94aafa55743c6b70ee84278f31fffa8bd24d/tests/wpt/mozilla/tests/css/canvas_scale.html#L3)):*
that…

---

*[tests/wpt/mozilla/tests/css/canvas_scale.html, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10727#-KFmYiNHU15mdfP9zYTC:-KFmYiNHU15mdfP9zYTD:-2014462789) ([raw file](https://github.com/servo/servo/blob/bc7a94aafa55743c6b70ee84278f31fffa8bd24d/tests/wpt/mozilla/tests/css/canvas_scale.html#L13)):*
Reftests should generally not have anything red if they pass.

---

*[tests/wpt/mozilla/tests/css/canvas_scale.html, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10727#-KFmYwG_U8M5JIC25q01:-KFmYwGa7CPhCnkT4l2w:504653037) ([raw file](https://github.com/servo/servo/blob/bc7a94aafa55743c6b70ee84278f31fffa8bd24d/tests/wpt/mozilla/tests/css/canvas_scale.html#L13)):*
I don't think the inline style on the `div` is necessary

---

*[tests/wpt/mozilla/tests/css/canvas_scale.html, line 14 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10727#-KFmY_cWRXPyZ2AH-8Nl:-KFmY_cWRXPyZ2AH-8Nm:-1812596656) ([raw file](https://github.com/servo/servo/blob/bc7a94aafa55743c6b70ee84278f31fffa8bd24d/tests/wpt/mozilla/tests/css/canvas_scale.html#L14)):*
Nit: put this line in a `div` too.

---

*[tests/wpt/mozilla/tests/css/canvas_scale.html, line 14 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10727#-KFmYseuPCUtOI02NdOr:-KFmYseuPCUtOI02NdOs:-1572174697) ([raw file](https://github.com/servo/servo/blob/bc7a94aafa55743c6b70ee84278f31fffa8bd24d/tests/wpt/mozilla/tests/css/canvas_scale.html#L14)):*
`#00FF` may not have been intended.

---

*[tests/wpt/mozilla/tests/css/canvas_scale.html, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10727#-KFmZ0kbjKgxodtIZ8tg:-KFmZ0kbjKgxodtIZ8th:-604481062) ([raw file](https://github.com/servo/servo/blob/bc7a94aafa55743c6b70ee84278f31fffa8bd24d/tests/wpt/mozilla/tests/css/canvas_scale.html#L17)):*
20x20 / 16x16

---

*[tests/wpt/mozilla/tests/css/canvas_scale.html, line 20 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10727#-KFmZ0-aQLIqGh8v9Fcs:-KFmZ0-aQLIqGh8v9Fct:5173792) ([raw file](https://github.com/servo/servo/blob/bc7a94aafa55743c6b70ee84278f31fffa8bd24d/tests/wpt/mozilla/tests/css/canvas_scale.html#L20)):*
Rm

---

*[tests/wpt/mozilla/tests/css/canvas_scale_ref.html, line 12 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10727#-KFmZ4yExCT6H6ktI2TY:-KFmZ4yExCT6H6ktI2TZ:1524168223) ([raw file](https://github.com/servo/servo/blob/bc7a94aafa55743c6b70ee84278f31fffa8bd24d/tests/wpt/mozilla/tests/css/canvas_scale_ref.html#L12)):*
Use `div` rather than `br` for consistency.

---

*[tests/wpt/mozilla/tests/css/canvas_scale_ref.html, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10727#-KFmZAQQGEY5P-9msF07:-KFmZAQQGEY5P-9msF08:-791029173) ([raw file](https://github.com/servo/servo/blob/bc7a94aafa55743c6b70ee84278f31fffa8bd24d/tests/wpt/mozilla/tests/css/canvas_scale_ref.html#L13)):*
Nit: use `#RRGGBB` to match the test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10727)*

**Comment by Ms2ger** [comment]
Oh, and the test should go upstream

**Comment by jdm** [comment]
The inline style on the div is necessary due to #10726.

**Comment by jdm** [comment]
I've addressed the review comments, but I haven't yet found an appropriate part of the specification that would map to where to add this test upstream. I've looked for every instance of `output bitmap` and `intrinsic size` in the `<canvas>` and `2d rendering context` sections, as well as CSS' definition of `paint source`.

**Comment by Ms2ger** [comment]
`html/rendering/replaced-elements/embedded-content-rendering-rules/` would be fine

**Comment by jdm** [comment]
```
  ▶ CRASH [expected FAIL] /css-flexbox-1_dev/html/flexbox-basic-canvas-horiz-001.htm
  │ 
  │ thread 'PaintWorker' panicked at 'assertion failed: (data.len() as i32) >= stride * size.height', /Users/servo/.cargo/git/checkouts/rust-azure-97bcec2370a94878/master/src/azure_hl.rs:710
  │ stack backtrace:
  │    1:        0x107a1e218 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
  │    2:        0x107a244f5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
  │    3:        0x107a2410e - std::panicking::default_hook::h08ad3bb09872855b
  │    4:        0x10738bbbf - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::heda6930908f06acc
  │    5:        0x107a0bdf8 - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
  │    6:        0x106c42c24 - std::sys_common::unwind::begin_unwind::h51df842978a11a26
  │    7:        0x10715d992 - azure::azure_hl::DrawTarget::create_source_surface_from_data::hff8d4d6dfe1b29ec
  │    8:        0x106e211c5 - gfx::paint_context::PaintContext::draw_image::ha2fe22b05b23a9c0
  │    9:        0x106e33502 - gfx::display_list::DisplayItem::draw_into_context::he113844733ffa618
  │   10:        0x106e33364 - gfx::display_list::DisplayList::draw_item_at_index_into_context::h67a2d41500a19eda
  │   11:        0x106e4a92b - gfx::paint_thread::WorkerThread::main::h9b9e5853d5716090
  │   12:        0x106e48850 - std::sys_common::unwind::try::try_fn::hccead59819239409
  │   13:        0x107a1d47b - __rust_try
  │   14:        0x107a1d403 - std::sys_common::unwind::inner_try::h4e97625a08807651
  │   15:        0x106e48e1b - _<F as alloc..boxed..FnBox<A>>::call_box::h37bba8686619f570
  │   16:        0x107a23578 - std::sys::thread::Thread::new::thread_start::h74af400293164137
  │   17:     0x7fff8face059 - _pthread_body
  │   18:     0x7fff8facdfd6 - _pthread_start
  │ Thread "PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }" panicked with an unwrap of `RecvError` (backtrace skipped)
  └ Pipeline failed in hard-fail mode.  Crashing!

  ▶ CRASH [expected FAIL] /css-flexbox-1_dev/html/flexbox-basic-canvas-vert-001.htm
  │ 
  │ thread 'PaintWorker' panicked at 'assertion failed: (data.len() as i32) >= stride * size.height', /Users/servo/.cargo/git/checkouts/rust-azure-97bcec2370a94878/master/src/azure_hl.rs:710
  │ stack backtrace:
  │    1:        0x10d914218 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
  │    2:        0x10d91a4f5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
  │    3:        0x10d91a10e - std::panicking::default_hook::h08ad3bb09872855b
  │    4:        0x10d281bbf - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::heda6930908f06acc
  │    5:        0x10d901df8 - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
  │    6:        0x10cb38c24 - std::sys_common::unwind::begin_unwind::h51df842978a11a26
  │    7:        0x10d053992 - azure::azure_hl::DrawTarget::create_source_surface_from_data::hff8d4d6dfe1b29ec
  │    8:        0x10cd171c5 - gfx::paint_context::PaintContext::draw_image::ha2fe22b05b23a9c0
  │    9:        0x10cd29502 - gfx::display_list::DisplayItem::draw_into_context::he113844733ffa618
  │   10:        0x10cd29364 - gfx::display_list::DisplayList::draw_item_at_index_into_context::h67a2d41500a19eda
  │   11:        0x10cd4092b - gfx::paint_thread::WorkerThread::main::h9b9e5853d5716090
  │   12:        0x10cd3e850 - std::sys_common::unwind::try::try_fn::hccead59819239409
  │   13:        0x10d91347b - __rust_try
  │   14:        0x10d913403 - std::sys_common::unwind::inner_try::h4e97625a08807651
  │   15:        0x10cd3ee1b - _<F as alloc..boxed..FnBox<A>>::call_box::h37bba8686619f570
  │   16:        0x10d919578 - std::sys::thread::Thread::new::thread_start::h74af400293164137
  │   17:     0x7fff8face059 - _pthread_body
  │   18:     0x7fff8facdfd6 - _pthread_start
  │ Thread "PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }" panicked with an unwrap of `RecvError` (backtrace skipped)
  └ Pipeline failed in hard-fail mode.  Crashing!
```

**Pull request merged**
