### PR TITLE
Add a simple method to emulate a platform UA (e.g. pretend a desktop build is an android UA).

### PR DESCRIPTION
**Pull request by glennw**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7246)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7246)

**Comment by larsbergstrom** [comment]
r=me with the tidy change (components/util/opts.rs:446: (much) overlong line)

**Comment by glennw** [comment]
(Fixed the unit tests)

@bors-servo r=larsbergstrom

**Pull request merged**
