### PR TITLE
Issue #10368: Implemented Uniform4iv and Uniform4i

### PR DESCRIPTION
**Pull request by autrilla**
Uniform4iv can make use of Uniform4i, so I implemented both.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10369)

### CODE REVIEW

**Comment by emilio** [comment]
Looks good, but needs a PR to wr_traits :)

-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/webglrenderingcontext.rs, line 978 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10369#-KEN7UYfiGR5R9sQ5d7m:-KEN7UYfiGR5R9sQ5d7n:979191886) ([raw file](https://github.com/servo/servo/blob/6f711a44eeab7795471ca2bffae838506285d5ea/components/script/dom/webglrenderingcontext.rs#L978)):*
This variant isn't actually in webrender_traits, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10369#-:-KEN7_Ncq0u-igwzajeM:-1218728442)*

**Comment by autrilla** [comment]
*[components/script/dom/webglrenderingcontext.rs, line 978 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10369#-KEN7UYfiGR5R9sQ5d7m:-KEN8IaWiTtZzY0MYSvm:879590041) ([raw file](https://github.com/servo/servo/blob/6f711a44eeab7795471ca2bffae838506285d5ea/components/script/dom/webglrenderingcontext.rs#L978)):*
afaict they are not. Should I issue a PR there too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10369)*

**Comment by emilio** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/dom/webglrenderingcontext.rs, line 978 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10369#-KEN7UYfiGR5R9sQ5d7m:-KENACxpreKz0-p1ryPR:1331650107) ([raw file](https://github.com/servo/servo/blob/6f711a44eeab7795471ca2bffae838506285d5ea/components/script/dom/webglrenderingcontext.rs#L978)):*
Yes! If not servo won't build :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10369)*

**Comment by emilio** [comment]
Once https://github.com/servo/webrender_traits/pull/32 lands, you can run `./mach cargo-update -p webrender_traits` to update to the new `webrender_traits`, and this'll be ready to land then :)

**Pull request merged**
