### PR TITLE
11485 make dom methods taking mut js content unsafe

### LINKED ISSUE #11485: Make DOM methods taking a `*mut JSContext` unsafe
For example, `HTMLCanvasElement::GetContext`.

Files:
- components/script/dom/bindings/codegen/CodegenRust.py

### PR DESCRIPTION
**Pull request by fflorent**
This is a rebased version of PR #11595

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #11485

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because: no code logic was changed

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14096)

### CODE REVIEW

**Comment by fflorent** [comment]
NB: I get a warning stating that `TryToConvertObj` is unused. The patch doesn't remove any call site for this method. Does my patch indirectly remove such a call site or is this a known warning?

Florent

**Comment by emilio** [comment]
> NB: I get a warning stating that TryToConvertObj is unused. The patch doesn't remove any call site for this method. Does my patch indirectly remove such a call site or is this a known warning?

That's pre-existing, so I wouldn't bother about it :)

**Comment by fflorent** [comment]
> That's pre-existing, so I wouldn't bother about it :)

Alright, thanks emilio!

**Comment by nox** [comment]
I think it would be better to just produce unsafe functions on `unsafe=True`, rather than adding a new `unsafe_fn` flag. I checked the three remaining `unsafe=True` functions and I think they should be unsafe altogether too.

**Comment by fflorent** [comment]
> I think it would be better to just produce unsafe functions on unsafe=True, rather than adding a new unsafe_fn flag. I checked the three remaining unsafe=True functions and I think they should be unsafe altogether too.

If I am not wrong, that flag already exists (see the arguments of the first `__init__` function).

Florent

**Comment by nox** [comment]
> If I am not wrong, that flag already exists (see the arguments of the first __init__ function).

Yes I know, I'm saying it should be redefined to generate unsafe functions, not functions with unsafe bodies.

**Comment by fflorent** [comment]
@nox Alright, I think I got it. Is my last commit what you asked for?

Florent

**Comment by nox** [comment]
Not exactly, I want `unsafe_fn` to become `unsafe`.

**Comment by fflorent** [comment]
@nox what about the updated commit?

**Comment by nox** [comment]
This seems perfect! Could you squash all commits together?

**Comment by fflorent** [comment]
@nox Done!

Florent

**Comment by fflorent** [comment]
@nox So is it OK to merge?

Florent

**Comment by nox** [comment]
Yes I was just waiting for the squash. :)

@bors-servo r+

**Pull request merged**
