### PR TITLE
Remove WebVR

### PR DESCRIPTION
**Pull request by asajeffrey**
Removes support for WebVR. WebXR is our future!

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because how do you test

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
wooooo

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /_mozilla/mozilla/interfaces.html:
  │ FAIL [expected PASS] Interfaces exposed on the window
  │   → assert_true: If this is failing: DANGER, are you sure you want to expose the new interface GamepadPose to all webpages as a property on the global? Do not make a change to this file without review from jdm or Ms2ger for that specific change! expected true got false
  │ 
  │ test_interfaces/<@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:76:18
  │ Test.prototype.step@http://web-platform.test:8000/resources/testharness.js:1958:25
  │ test@http://web-platform.test:8000/resources/testharness.js:548:30
  │ test_interfaces@http://web-platform.test:8000/_mozilla/mozilla/interfaces.js:2:7
  └ @http://web-platform.test:8000/_mozilla/mozilla/interfaces.html:13:16
```

```
error[E0432]: unresolved import `simpleservo::VRInitOptions`
  --> ports/libsimpleservo/capi/src/lib.rs:21:59
   |
21 |     MediaSessionPlaybackState, MouseButton, PromptResult, VRInitOptions,
   |                                                           ^^^^^^^^^^^^^
   |                                                           |
   |                                                           no `VRInitOptions` in the root
   |                                                           help: a similar name exists in the module: `InitOptions`
error[E0560]: struct `simpleservo::InitOptions` has no field named `vr_init`
   --> ports/libsimpleservo/capi/src/lib.rs:442:9
    |
442 |         vr_init: if opts.vr_pointer.is_null() {
    |         ^^^^^^^ `simpleservo::InitOptions` does not have this field
    |
    = note: available fields are: `args`, `url`, `coordinates`, `density`, `xr_discovery` ... and 3 others
error: aborting due to 2 previous errors
```
```
  ▶ CRASH [expected OK] /webvr/webvr-supported-by-feature-policy.html
  │ 
  │ thread 'main' panicked at 'Error setting preference: dom.webvr.enabled=true: NoSuchPref("dom.webvr.enabled")', components/config/opts.rs:982:5
```

**Comment by Manishearth** [comment]
Lets stick the Gamepad types behind a new preference for now

**Comment by asajeffrey** [comment]
@bors-servo retry
 - #25513

**Pull request merged**
