### PR TITLE
Update serde to 0.9

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15588)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo try

Something tells me this is not going to work on first try.

**Comment by SimonSapin** [comment]
Reviewed 6 of 6 files at r1, 64 of 64 files at r2.
Review status: 46 of 71 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15588)*

**Comment by nox** [comment]
It's time.

**Comment by asajeffrey** [comment]
Once this lands, we can land #15618.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r3, 49 of 73 files at r5, 24 of 24 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15588#-:-KdHOF6LtJj13lwIkoKb:bkg9nno)*

**Comment by nox** [comment]
@bors-servo retry

Git git bad.

**Comment by nox** [comment]
@bors-servo retry

I feature bad.

**Comment by nox** [comment]
@bors-servo r=SimonSapin

I also Homu bad.

**Comment by nox** [comment]
@bors-servo r=SimonSapin

Outdated lock file...

**Comment by nox** [comment]
This is #15583, I'm waiting for the other jobs to finish so that retry doesn't have to do everything again.

**Pull request merged**
