### PR TITLE
Introduce a new flag and use it to be more permissive about cousin sharing

### PR DESCRIPTION
**Pull request by bholley**
https://bugzilla.mozilla.org/show_bug.cgi?id=1387116

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17980)

### CODE REVIEW

**Comment by ionutgoldan** [comment]
Looks like this brought a noticeable improvement:

== Change summary for alert #8585 (as of August 05 2017 09:41 UTC) ==

Improvements:

  7%  tp6_amazon summary windows10-64 opt 1_thread e10s stylo     688.38 -> 637.00
  7%  tp6_amazon summary windows10-64 pgo 1_thread e10s stylo     628.58 -> 585.25

For up to date results, see: https://treeherder.mozilla.org/perf.html#/alerts?id=8585

**Comment by ionutgoldan** [comment]
If this improvement somehow wasn't expected, please don't hesitate to email me at ionut.goldan@softvision.ro

**Comment by emilio** [comment]
This kind of wasn't expected, but there should've been a regression before from https://bugzilla.mozilla.org/show_bug.cgi?id=1381821

**Pull request merged**
