### PR TITLE
Update backtrace-sys, gamma-lut, heartbeats-simple, hyper, mac, truetype, unicode-bidi

### PR DESCRIPTION
**Pull request by mbrubeck**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15616)

### CODE REVIEW

**Comment by mbrubeck** [comment]
```
  ▶ Unexpected subtest result in /XMLHttpRequest/getresponseheader-case-insensitive.htm:
  └ PASS [expected FAIL] XMLHttpRequest: getResponseHeader() case-insensitive matching

  ▶ Unexpected subtest result in /cors/response-headers.htm:
  └ PASS [expected FAIL] getResponseHeader: Expose Access-Control-Expose-Headers (x-custom-header-comma)

  ▶ Unexpected subtest result in /cors/response-headers.htm:
  └ PASS [expected FAIL] getResponseHeader: Combined testing of cors response headers

  ▶ Unexpected subtest result in /cors/response-headers.htm:
  └ PASS [expected FAIL] getResponse: don't expose x-nonexposed
```

**Comment by mbrubeck** [comment]
@bors-servo r=jdm

* updated test expectations

**Comment by jdm** [comment]
@bors-servo: retry
#15583

**Pull request merged**
