### PR TITLE
Fixed serialize_list to no longer append an additional space at the e…

### LINKED ISSUE #7404: serialize_list should not append a space at the end of the list
for example, element.style['border-width'] should return |0px 0px 0px 0px| not |0px 0px 0px 0px |
The code to blame is serialize_list in cssstyledeclaration.rs (http://mxr.mozilla.org/servo/source/components/script/dom/cssstyledeclaration.rs#54) and the problem is that it folds over the list and adds a space after every list element. Instead, it should join the declaration values with a space.

### PR DESCRIPTION
**Pull request by GyrosOfWar**
…nd of the string.

Fixes #7404

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7429)

### CODE REVIEW

**Comment by jdm** [comment]
Let's write a test for this! The ones in http://mxr.mozilla.org/servo/source/tests/wpt/mozilla/tests/mozilla/ should provide a good model, and then you'll need to run `./mach test-wpt --update-manifest` to ensure that http://mxr.mozilla.org/servo/source/tests/wpt/mozilla/meta/MANIFEST.json is updated appropriately.

**Comment by jdm** [comment]
-S-awaiting-review 

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7429)

**Comment by GyrosOfWar** [comment]
Do you want me to amend the tests to the first commit? Also, thanks for the review, this is fun.

**Comment by jdm** [comment]
Sure, amending is fine here.

**Comment by dzbarsky** [comment]
Excellent, thank you!
Out of curiosity, why do you need the type annotation on the Vec?

**Comment by GyrosOfWar** [comment]
I actually don't anymore, thanks for the hint. As for the merge conflicts, I think that's the result of me not knowing that you need to `git push -f` when using --amend on commits (I did a pull because git told me to and that probably messed something up a little).

**Comment by jdm** [comment]
Oh, it looks like this commit now includes some other commits that are already in the tree. I suggest resetting to a known-good revision and applying your changes on top of it again, then force pushing that to this branch.

**Comment by jdm** [comment]
This looks fine to me; just waiting on a final rebase :)

**Comment by GyrosOfWar** [comment]
How do I rebase?

**Comment by Ms2ger** [comment]
Assuming `upstream` refers to the `servo/servo` repo, and `origin` to your fork (check with `git remote -v`), do
```sh
git checkout serialize_list_space_fix
git fetch upstream
git rebase -i upstream/master
git push -f origin serialize_list_space_fix
```

**Comment by jdm** [comment]
Ugh, sorry about bitrotting you immediately after rebasing. Please rebase again and leave a comment so we get a notification that it's ready!

**Comment by GyrosOfWar** [comment]
Rebased it again. Should be fine to merge now, I think.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

**Pull request merged**
