### PR TITLE
Add Github Actions workflow for mac/linux/windows builds

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by Darkspirit** [comment]
7 months ago I played a bit with Github Actions, but right now I can only find this snippet:
* https://github.com/servo/servo/compare/master...Darkspirit:runner Self-hosted Github runners are not ephermal/secure, only Gitlab does it right.
* I think Github runners failed because too much junk was preinstalled and [14 GB SSD](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) didn't seem to be enough.

**Comment by Darkspirit** [comment]
https://github.com/Darkspirit/servo/commit/dadfb8a6f1abb571e1d21961050b1d8845dc7aaa
https://github.com/Darkspirit/servo/runs/1465411408

**Comment by jdm** [comment]
Well, that's certainly making better progress than my attempts to use docker!

**Comment by Darkspirit** [comment]
Omg, it's [green](https://github.com/Darkspirit/servo/runs/1465411408). :O
> Finished dev [unoptimized + debuginfo] target(s) in 36m 36s
> Warning:  Could not generate notification! 
> Build Completed in 0:36:38

**Comment by jdm** [comment]
Now building on top of https://github.com/Darkspirit/servo/commit/dadfb8a6f1abb571e1d21961050b1d8845dc7aaa, I'm attempting to get two chunked WPT test runs working.

**Comment by jdm** [comment]
As of 9daccfc, the Linux CI can complete 1/20 WPT chunks in ~14m. The release build step takes 40-50m before the tests can start running.

**Comment by jdm** [comment]
First successful macOS CI build! It also took 42 minutes, but 8 minutes of that was doing all the homebrew setup.

**Comment by jdm** [comment]
Every test is failing with output like:
```
n_test 

│ → result = self.do_test(test) 

│ → File "/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 108, in do_test 

│ → self.proc.run() 

│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 983, in run 

│ → self.proc = self.Process([self.cmd] + self.args, **args) 

│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 153, in __init__ 

│ → subprocess.Popen.__init__(self, args, **kwargs) 

│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__ 

│ → self._execute_child(args, executable, preexec_fn, close_fds, 

│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child 

│ → raise child_exception_type(errno_num, err_msg, err_filename) 

└ → OSError: [Errno 8] Exec format error: '/Users/runner/work/servo/servo/target/release/servo' 



STDERR: ['/Users/runner/work/servo/servo/target/release/servo', '--hard-fail', '-u', 'Servo/wptrunner', '-z', 'http://web-platform.test:8000/html/browsers/windows/browsing-context-names/choose-_top-002.html', '-Z', 'replace-surrogates', '--user-stylesheet', '/Users/runner/work/servo/servo/resources/ahem.css', '--pref', 'dom.imagebitmap.enabled=true', '--certificate-path', '/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/certs/cacert.pem'] 

▶ ERROR [expected OK] b'/html/browsers/windows/browsing-context-names/choose-_top-002.html' 

│ → Traceback (most recent call last): 

│ → File "/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 293, in run_test 

│ → result = self.do_test(test) 

│ → File "/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 108, in do_test 

│ → self.proc.run() 

│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 983, in run 

│ → self.proc = self.Process([self.cmd] + self.args, **args) 

│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 153, in __init__ 

│ → subprocess.Popen.__init__(self, args, **kwargs) 

│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__ 

│ → self._execute_child(args, executable, preexec_fn, close_fds, 

│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child 

│ → raise child_exception_type(errno_num, err_msg, err_filename) 

└ → OSError: [Errno 8] Exec format error: '/Users/runner/work/servo/servo/target/release/servo' 


STDERR: ['/Users/runner/work/servo/servo/target/release/servo', '--hard-fail', '-u', 'Servo/wptrunner', '-z', 'http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/decode/image-decode-image-document.html', '-Z', 'replace-surrogates', '--user-stylesheet', '/Users/runner/work/servo/servo/resources/ahem.css', '--pref', 'dom.imagebitmap.enabled=true', '--certificate-path', '/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/certs/cacert.pem'] 
[302/1315] /html/semantics/embedded-content/the-img-element/decode/image-decode-image-document.html 
STDERR: ['/Users/runner/work/servo/servo/target/release/servo', '--hard-fail', '-u', 'Servo/wptrunner', '-z', 'http://web-platform.test:8000/html/browsers/windows/browsing-context-names/choose-default-002.html', '-Z', 'replace-surrogates', '--user-stylesheet', '/Users/runner/work/servo/servo/resources/ahem.css', '--pref', 'dom.imagebitmap.enabled=true', '--certificate-path', '/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/certs/cacert.pem'] 
▶ ERROR [expected OK] b'/html/browsers/windows/browsing-context-names/choose-default-002.html' 
│ → Traceback (most recent call last): 
│ → File "/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 293, in run_test 
│ → result = self.do_test(test) 
│ → File "/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 108, in do_test 
│ → self.proc.run() 
│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 983, in run 
│ → self.proc = self.Process([self.cmd] + self.args, **args) 
│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 153, in __init__ 
│ → subprocess.Popen.__init__(self, args, **kwargs) 
│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__ 
│ → self._execute_child(args, executable, preexec_fn, close_fds, 
│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child 
│ → raise child_exception_type(errno_num, err_msg, err_filename) 
└ → OSError: [Errno 8] Exec format error: '/Users/runner/work/servo/servo/target/release/servo' 

STDERR: ['/Users/runner/work/servo/servo/target/release/servo', '--hard-fail', '-u', 'Servo/wptrunner', '-z', 'http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/decode/image-decode-path-changes.html', '-Z', 'replace-surrogates', '--user-stylesheet', '/Users/runner/work/servo/servo/resources/ahem.css', '--pref', 'dom.imagebitmap.enabled=true', '--certificate-path', '/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/certs/cacert.pem'] 
▶ ERROR [expected OK] b'/html/semantics/embedded-content/the-img-element/decode/image-decode-path-changes.html' 
│ → Traceback (most recent call last): 
│ → File "/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 293, in run_test 
│ → result = self.do_test(test) 
│ → File "/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 108, in do_test 
│ → self.proc.run() 
│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 983, in run 
│ → self.proc = self.Process([self.cmd] + self.args, **args) 
│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 153, in __init__ 
│ → subprocess.Popen.__init__(self, args, **kwargs) 
│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__ 
│ → self._execute_child(args, executable, preexec_fn, close_fds, 
│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child 
│ → raise child_exception_type(errno_num, err_msg, err_filename) 
└ → OSError: [Errno 8] Exec format error: '/Users/runner/work/servo/servo/target/release/servo' 

STDERR: ['/Users/runner/work/servo/servo/target/release/servo', '--hard-fail', '-u', 'Servo/wptrunner', '-z', 'http://web-platform.test:8000/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/align.html', '-Z', 'replace-surrogates', '--user-stylesheet', '/Users/runner/work/servo/servo/resources/ahem.css', '--pref', 'dom.imagebitmap.enabled=true', '--certificate-path', '/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/certs/cacert.pem'] 
▶ ERROR [expected OK] b'/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/align.html' 
│ → Traceback (most recent call last): 
│ → File "/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 293, in run_test 
│ → result = self.do_test(test) 
│ → File "/Users/runner/work/servo/servo/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 108, in do_test 
│ → self.proc.run() 
│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 983, in run 
│ → self.proc = self.Process([self.cmd] + self.args, **args) 
│ → File "/Users/runner/work/servo/servo/python/_virtualenv3.9/lib/python3.9/site-packages/mozprocess/processhandler.py", line 153, in __init__ 
│ → subprocess.Popen.__init__(self, args, **kwargs) 
│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__ 
│ → self._execute_child(args, executable, preexec_fn, close_fds, 
│ → File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child 
│ → raise child_exception_type(errno_num, err_msg, err_filename) 
└ → OSError: [Errno 8] Exec format error: '/Users/runner/work/servo/servo/target/release/servo' 
```
which is pretty weird.

**Comment by jdm** [comment]
```
godot:release jdm$ ls -la servo
-rwxr-xr-x@ 1 jdm  staff  92990952 Dec  4 14:26 servo
godot:release jdm$ ./servo
-bash: ./servo: cannot execute binary file
godot:release jdm$ file servo
servo: data
```
The output of xxd suggests the entire file is made of null bytes, which is just wild.

**Comment by jdm** [comment]
Very curious. Running a smoketest from the build job shows that the servo binary is sensible (`target/release/servo: Mach-O 64-bit executable x86_64`), but after we put it inside a tar and upload it as an artifact, something about that process corrupts it and it's no longer valid when downloading the artifact.

**Comment by jdm** [comment]
An example artifact that the workflow generates is https://joshmatthews.net/release-binary-macos.zip.

**Comment by jdm** [comment]
This looks like it might be https://github.com/actions/upload-artifact/issues/151.

**Comment by jdm** [comment]
WPT tests on macos complete, but something like the last 200 tests time out in runs using 2 or 1 test process. My initial guess is a low system file handle limit.

**Comment by jdm** [comment]
Adding a `--timeout-multiplier=4` to the `--processes=1` run appeared to help:
```
2020-12-09T19:19:24.6993130Z 1 unexpected results that are NOT known-intermittents:
2020-12-09T19:19:24.6995020Z   ▶ TIMEOUT [expected OK] b'/navigation-timing/unload-event-same-origin-check.html'
2020-12-09T19:19:24.6995960Z 
2020-12-09T19:19:24.6997400Z   ▶ Unexpected subtest result in /navigation-timing/unload-event-same-origin-check.html:
2020-12-09T19:19:24.6999140Z   │ TIMEOUT [expected PASS] b'Previous document cross origin'
2020-12-09T19:19:24.7000280Z   └   → Test timed out
2020-12-09T19:19:24.7000750Z 
2020-12-09T19:19:24.7002300Z   ▶ Unexpected subtest result in /navigation-timing/unload-event-same-origin-check.html:
2020-12-09T19:19:24.7003920Z   └ NOTRUN [expected FAIL] b'Previous document same origin'
2020-12-09T19:19:24.7005010Z 
2020-12-09T19:19:24.7006450Z   ▶ Unexpected subtest result in /navigation-timing/unload-event-same-origin-check.html:
2020-12-09T19:19:24.7008020Z   └ NOTRUN [expected PASS] b'No previous document'
2020-12-09T19:19:24.7008610Z 
2020-12-09T19:19:24.7009990Z   ▶ Unexpected subtest result in /navigation-timing/unload-event-same-origin-check.html:
2020-12-09T19:19:24.7011710Z   └ NOTRUN [expected FAIL] b'Same origin previous document with same origin redirect'
2020-12-09T19:19:24.7012410Z 
2020-12-09T19:19:24.7013800Z   ▶ Unexpected subtest result in /navigation-timing/unload-event-same-origin-check.html:
2020-12-09T19:19:24.7015480Z   └ NOTRUN [expected FAIL] b'No previous document with same origin redirect'
2020-12-09T19:19:24.7016140Z 
2020-12-09T19:19:24.7017690Z   ▶ Unexpected subtest result in /navigation-timing/unload-event-same-origin-check.html:
2020-12-09T19:19:24.7019390Z   └ NOTRUN [expected PASS] b'No previous document with cross origin redirect'
2020-12-09T19:19:24.7020060Z 
2020-12-09T19:19:24.7021470Z   ▶ Unexpected subtest result in /navigation-timing/unload-event-same-origin-check.html:
2020-12-09T19:19:24.7023200Z   └ NOTRUN [expected PASS] b'No previous document with cross origin redirect with partial TAO'
2020-12-09T19:19:24.7023920Z 
2020-12-09T19:19:24.7025330Z   ▶ Unexpected subtest result in /navigation-timing/unload-event-same-origin-check.html:
2020-12-09T19:19:24.7027030Z   └ NOTRUN [expected PASS] b'No previous document with cross origin redirect with TAO'
```

All of the CSS test timeouts disappeared, and now it's a single navigation-timing test that timed out. Of course, the test run took 3h 37m.

**Comment by jdm** [comment]
`--timeout-multiplier=2` has 14 CSS reftests that time out.

**Comment by jdm** [comment]
3 CSS timeouts with `--timeout-multiplier=3`.

**Comment by jdm** [comment]
Two CSS timeouts with `--timeout-multiplier=4` and `--processes=2`, total time 2.5 hours:
```
2 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected PASS] b'/css/css-transforms/transform-origin-003.html'
  │   → TestRunner hit external timeout (this may indicate a hang)
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ 34 threads are still running after shutdown (bad).


  ▶ TIMEOUT [expected PASS] b'/css/css-transforms/transform-table-004.html'
  │   → TestRunner hit external timeout (this may indicate a hang)
  │ 
  │ Shutting down the Constellation after generating an output file or exit flag specified
  │ 9 threads are still running after shutdown (bad).
  │ Shutting down the Constellation after generating an output file or exit flag specified
  └ 34 threads are still running after shutdown (bad).
```

**Comment by jdm** [comment]
With `--processes=3` and `--timeout-multiplier=8`, there were two non-CSS timeouts, total time just under 2.5 hours.

**Comment by jdm** [comment]
I'm going to try running a workflow with all chunks on linux and macos and see what breaks.

**Comment by jdm** [comment]
I forgot to build with debug assertions enabled, so that's going to throw off some test results (there's at least 1 `OK expected CRASH`).

**Comment by jdm** [comment]
Also the step that uploads logs should be made to run regardless if the run fails or not.

**Comment by jdm** [comment]
Windows builds are blocked by #27545.

**Comment by jdm** [comment]
Moving to python3 exclusively on Windows will require a mozjs upgrade, since mozilla-central now supports python3.

**Comment by jdm** [comment]
```
 INFO: Creating Python 3 environment
  INFO: ['C:/Users/runneradmin/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/c6c7b53/mozjs\\third_party\\python\\virtualenv', 'C:\\Users\\runneradmin\\.cargo\\git\\checkouts\\mozjs-fa11ffc7d4f1cc2d\\c6c7b53\\mozjs\\third_party\\python\\virtualenv', 'c:\\hostedtoolcache\\windows\\Python\\3.7.9\\x64\\python37.zip', 'c:\\hostedtoolcache\\windows\\Python\\3.7.9\\x64\\DLLs', 'c:\\hostedtoolcache\\windows\\Python\\3.7.9\\x64\\lib', 'c:\\hostedtoolcache\\windows\\Python\\3.7.9\\x64']
  INFO: created virtual environment CPython3.7.9.final.0-64 in 1263ms
  INFO:   creator CPython3Windows(dest=D:\a\servo\servo\target\release\build\mozjs_sys-7f8ef43f60afb82d\out\build\_virtualenvs\init_py3, clear=False, global=False)
  INFO:   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\runneradmin\AppData\Local\pypa\virtualenv)
  INFO:     added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
  INFO:   activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
  INFO: Traceback (most recent call last):
  INFO:   File "C:\Users\runneradmin\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\c6c7b53\mozjs\python\mozbuild\mozbuild\virtualenv.py", line 771, in <module>
  INFO:     manager.populate()
  INFO:   File "C:\Users\runneradmin\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\c6c7b53\mozjs\python\mozbuild\mozbuild\virtualenv.py", line 463, in populate
  INFO:     handle_package(package)
  INFO:   File "C:\Users\runneradmin\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\c6c7b53\mozjs\python\mozbuild\mozbuild\virtualenv.py", line 381, in handle_package
  INFO:     submanager.populate(sitecustomize=sitecustomize)
  INFO:   File "C:\Users\runneradmin\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\c6c7b53\mozjs\python\mozbuild\mozbuild\virtualenv.py", line 463, in populate
  INFO:     handle_package(package)
  INFO:   File "C:\Users\runneradmin\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\c6c7b53\mozjs\python\mozbuild\mozbuild\virtualenv.py", line 398, in handle_package
  INFO:     f.write("%s\n" % os.path.relpath(path, python_lib))
  INFO:   File "c:\hostedtoolcache\windows\Python\3.7.9\x64\lib\ntpath.py", line 562, in relpath
  INFO:     path_drive, start_drive))
  INFO: ValueError: path is on mount 'C:', start on mount 'D:'
```
Sigh.

**Comment by jdm** [comment]
Also the time it takes to build dependencies that involve native compilation on Windows is... not great:
* `Completed tinyfiledialogs v3.3.9 custom-build (run) in 964.1s`
* `Completed libz-sys v1.1.2 custom-build (run) in 1024.0s`
* `Completed harfbuzz-sys v0.5.0 custom-build (run) in 396.5s`

**Comment by jdm** [comment]
The build for 946da39d1b9a4d2ff7510aa36f8a2110975977c3 successfully linked, then failed during pre-packaging due to some assumptions about the gstreamer DLLs. Since all three platforms are building, it might be good to merge that basic mac/linux/windows build workflow so we notice if it regresses.

**Comment by jdm** [comment]
The Windows build runs out of disk space while building the unit tests. Interesting.

**Comment by jdm** [comment]
Note to self: it appears building on C drive instead of D drive is a possibility if necessary: https://github.com/actions/virtual-environments/issues/1341#issuecomment-669204383

**Comment by jdm** [comment]
```
memory allocation of 738197504 bytes failed
error: could not compile `script`.
```
The normal build is fine, while test-unit fails with this while building script. Sigh.

**Comment by jdm** [comment]
Looks like it OOMs on debug builds but not release builds. I love when workarounds present themselves.

**Comment by jdm** [comment]
These changes are ready for review.

**Comment by jdm** [comment]
The windows pull request job failed because github.sha refers to a merge commit that doesn't actually exist on the branch we fetch: https://github.community/t/github-sha-isnt-the-value-expected/17903/2
Sigh.

**Comment by sagudev** [comment]
actions/checkout@v2 ≈ 1m
Copy to C drive ≈ 5m

**Comment by jdm** [comment]
I'm just going to go ahead and merge this work.
@bors-servo r+

**Pull request merged**
