### PR TITLE
Refactor geckolib atoms regen script

### PR DESCRIPTION
**Pull request by ghost**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] These changes do not require tests because it's a refactor

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13476)

### CODE REVIEW

**Comment by emilio** [comment]
This looks good to me, though can we use `str.format()` instead of the `%` operator, so it works in both python2 and python3? I know we're not probably making the switch anytime soon, but...

**Comment by Wafflespeanut** [comment]
I was lazy about having double curly braces everywhere. I've made the changes now :smile:

**Comment by emilio** [comment]
Neat, thanks!

@bors-servo: r+

**Comment by Manishearth** [comment]
Pushed, and included missing stuff from the regen

@bors-servo r+

**Pull request merged**
