### PR TITLE
No need to cancel the task. The thread is ending.

### LINKED ISSUE #24635: uwp: cancel_current_task() throws at shutdown
Looks like a recent regression.

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #24635

### CODE REVIEW

**Comment by paulrouget** [comment]
For the record: `cancel_current_task()` mark the task as ending. We don't need to rely on this as we already have our own flag (`mLooping`).

**Comment by jdm** [comment]
@bors-servo retry
* network issues

**Comment by jdm** [comment]
@bors-servo retry
* #23290 #24675

**Comment by jdm** [comment]
@bors-servo retry
* #23290 #24611

**Comment by CYBAI** [comment]
👆 #16783

**Pull request merged**
