### PR TITLE
layout: Handle inline margins in `layout_for_block_content_size()`

### LINKED ISSUE #33779: Handle inline margins in `layout_for_block_content_size()`
This is missing the inline margins:

https://github.com/servo/servo/blob/61a930402d5ac1f03530d7506960b8a04cfb974a/components/layout_2020/flexbox/layout.rs#L2523-L2525

We are correctly handling the block ones:

https://github.com/servo/servo/blob/61a930402d5ac1f03530d7506960b8a04cfb974a/components/layout_2020/flexbox/layout.rs#L2563-L2566

### PR DESCRIPTION
**Pull request by taniishkaaa**
Adds inline margins to `layout_for_block_content_size()` in `components/layout_2020/flexbox/layout.rs`

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #33779 
- [X] There are tests for these changes

### CODE REVIEW

**Comment by Loirooriol** [comment]
> These changes do not require tests because they do not modify functionality.

These changes do modify functionality, and need test coverage (but probably there is some existing test that will pass).

**Comment by taniishkaaa** [comment]
> > These changes do not require tests because they do not modify functionality.
> 
> These changes do modify functionality, and need test coverage (but probably there is some existing test that will pass).

oh sorry, I'll edit that

**Comment by atbrakhi** [comment]
Nice, @taniishkaaa we just need to [update](https://book.servo.org/hacking/testing.html#updating-web-test-expectations) the test expectations now.

**Comment by taniishkaaa** [comment]
> Nice, @taniishkaaa we just need to [update](https://book.servo.org/hacking/testing.html#updating-web-test-expectations) the test expectations now.

I'm on it!

**Comment by taniishkaaa** [comment]
> Nice, @taniishkaaa we just need to [update](https://book.servo.org/hacking/testing.html#updating-web-test-expectations) the test expectations now.

So, the following files are causing the error according to the log:
[tests/wpt/meta/css/cssom-view/MediaQueryList-extends-EventTarget.html.ini](https://github.com/servo/servo/blob/main/tests/wpt/meta/css/cssom-view/MediaQueryList-extends-EventTarget.html.ini#L1)
[tests/wpt/meta/css/css-flexbox/flex-basis-item-margins-001.html.ini](https://github.com/servo/servo/blob/main/tests/wpt/meta/css/css-flexbox/flex-basis-item-margins-001.html.ini)
[tests/wpt/meta/resize-observer/change-layout-in-error.html.ini](https://github.com/servo/servo/blob/main/tests/wpt/meta/resize-observer/change-layout-in-error.html.ini)
do you want me to only modify the files to `PASS` or remove them altogether as per the documentation?

**Comment by atbrakhi** [comment]
I won't touch any other files. According to the [wpt results](https://github.com/servo/servo/pull/33780#issuecomment-2404985397), only one test has an unexpected result: `/css/css-flexbox/flex-basis-item-margins-001.html`. We should delete the `.ini` file for that test

**Comment by taniishkaaa** [comment]
> I won't touch any other files. According to the [wpt results](https://github.com/servo/servo/pull/33780#issuecomment-2404985397), only one test has an unexpected result: `/css/css-flexbox/flex-basis-item-margins-001.html`. We should delete the `.ini` file for that test

cool, thanks!

**Review by atbrakhi — APPROVED** [review]

**Review by Loirooriol — APPROVED** [review]
But in the description you can just say the default "✅ There are tests for these changes". It's weird to say it's likely when we know there is a test.

**Comment by taniishkaaa** [comment]
> But in the description you can just say the default "✅ There are tests for these changes". It's weird to say it's likely when we know there is a test.

Done!

**Pull request merged**
