### PR TITLE
Use serde in devtools

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10285)

### CODE REVIEW

**Comment by edunham** [comment]
@bors-servo retry

Infra downtime for https://github.com/servo/saltfs/issues/281 interrupted the build

**Comment by jdm** [comment]
test-tidy doesn't like `#[something="something"]`; it wants spaces around the =.

**Comment by nox** [comment]
@jdm Damn.

**Pull request merged**
