### PR TITLE
style: Don't assume siblings are alive in the rule tree when removing ourselves from the child list.

### PR DESCRIPTION
**Pull request by emilio**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There are tests for these changes OR

We can't assume all our siblings are alive because they may very well be in the
free list too.

This tempts to happen when the rule nodes are destroyed as part of the last GC,
the one that runs in the root destructor.

Also, properly put the next sibling back into the list when the rules are GCd.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14167)

### CODE REVIEW

**Comment by jdm** [comment]
The failure was #11100.

**Comment by emilio** [comment]
Actually, simon is going to be away tomorrow. This can wait if needed, but blocks #8600 (or at least appears in the test failures), so... r? @Manishearth

**Comment by emilio** [comment]
@bors-servo force

 * (the queue is empty but this is not on it, sigh)

**Pull request merged**
