### PR TITLE
Update web-platform-tests to revision e8bfc205e36ad699601212cd50083870bad9a75d

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14202)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Note this partially reverts #14126.

**Comment by jdm** [comment]
Keep in mind that we've disabled the other similar cors and redirection tests in that directory because of strange timeouts on build machines (locally they worked fine).

**Comment by jdm** [comment]
@bors-servo: retry
* #14229 #13776

**Pull request merged**
