### PR TITLE
Update WR (reference frames for fixed position elements).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15804)

### CODE REVIEW

**Comment by glennw** [comment]
WR needs to know whether a transform / perspective element exists. This is required because the containing block of ```position: fixed``` elements is the nearest parent with a transform set (see https://drafts.csswg.org/css-transforms-2/#perspective-property).

This update changes the transform / perspective properties to be Options that are passed through to WR, in order to enable correct positioning for fixed elements under a transform root.

**Comment by pcwalton** [comment]
I wonder if it would be better to Box the matrices (or maybe just perspective?) now, to avoid copies. Most stacking contexts don't have a 3D transform set...

**Pull request merged**
