### PR TITLE
Fix line-breaking with white-space: pre-wrap/pre-line; 

### LINKED ISSUE #12369: white-space: pre-wrap and pre-line cause infinite loop
Test case:
```html
<!doctype html>
<html>
<style>
div {
   width: 70px;
   white-space: pre-wrap; // or pre-line
}
</style>
<div>This is a loooooooong line
Line 2
</div>
</html>
```

fatal runtime error: out of memory
Servo exited with return value -4

### PR DESCRIPTION
**Pull request by emilio**
Not sure if this is the appropriate fix, but we'll know soon.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12369 

- [x] There are tests for these changes OR

r? @mbrubeck

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12370)

### CODE REVIEW

**Comment by jdm** [comment]
Why testharness tests instead of reftests?

**Comment by emilio** [comment]
Because this is fixing a OOM, we already have reftests for those properties
AFAIK (though I can certainly write a new one that tests a single word
overflowing the line).

**Pull request merged**
