### PR TITLE
Fix gpu ref tests (fixes #4683). Also add --test argument stubs.

### LINKED ISSUE #4683: GPU mode reftests fail on Linux
When both `-g` and `-r mesa` are passed to `servo` on Linux (as in reftests), Skia segfaults. I believe this started since the switch to Glutin (#4672).

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9ddfe700 (LWP 24542)]
0x0000555556a6eac3 in SkNativeSharedGLContext::createGLContext(int, int) ()
(gdb) where
#0  0x0000555556a6eac3 in SkNativeSharedGLContext::createGLContext(int, int) ()
#1  0x0000555556a6e3cd in SkNativeSharedGLContext::init(int, int) ()
#2  0x0000555556a6d681 in AzCreateSkiaSharedGLContext ()
#3  0x0000555556a69091 in azure::azure_hl::DrawTarget::new_with_fbo (backend=Skia, 
    native_graphics_context=0x7fff9ddfdae8, size=..., format=B8G8R8A8) at src/azure_hl.rs:432
#4  0x0000555555ce4ee9 in gfx::paint_task::WorkerThread::optimize_and_paint_tile (self=0x7fff9ddfdab0, 
    tile=0x7fff9ddfd970, stacking_context=..., scale=1) at paint_task.rs:523
#5  0x0000555555cd2483 in gfx::paint_task::WorkerThread::main (self=0x7fff9ddfdab0) at paint_task.rs:499
#6  0x0000555555cd1cd5 in fn"fn"(15339) () at paint_task.rs:440
#7  0x0000555556e05f92 in task::Task::spawn::closure.5731 ()
#8  0x0000555556e0879c in rust_try_inner ()
#9  0x0000555556e08786 in rust_try ()
#10 0x0000555556e06033 in unwind::try::hf0141b63ff6a0a11Tyc ()
#11 0x0000555556e05e3c in task::Task::run::hcbcff3a8c16a161bfKb ()
#12 0x0000555556e05a88 in task::Task::spawn::closure.5707 ()
#13 0x0000555556e06f45 in thread::thread_start::h5cd59b116a732721w1b ()
#14 0x00007ffff6468314 in start_thread () from /usr/lib/libpthread.so.0
#15 0x00007ffff750324d in clone () from /usr/lib/libc.so.6
```

CC @glennw

### PR DESCRIPTION
**Pull request by glennw**

### CODE REVIEW

**Comment by SimonSapin** [comment]
The `reftest.rs` change looks fine, but what is `--test` and my add it now if it does nothing?

**Comment by glennw** [comment]
The --test change is so that we can pass --test=wpt that from wptrunner, and then in the future we'll be able to adjust servo's behaviour without having to upstream cmd line arg changes to WPT. It's there now so we can make the change to wptrunner (servo fails to run if it sees an argument it doesn't recognise).

**Comment by SimonSapin** [comment]
What kind of adjustment would we want to make? Changing behavior while under test seems to defeat the point of testing.

Regardless, the code comments and `--help` message should be something like "Ignored - passed by wptrunner" rather than talk about a "test mode" which is not a thing that exists yet.

Also, please split the two changes into separate commits.

**Comment by glennw** [comment]
We already pass several test specific flags from wptrunner, e.g. "run in headless mode". The idea is to move those from wptrunner to inside servo so we can modify them if needed without changing wptrunner.

I may have to change how the reftest+gpu fix works, so I'll close this and re-open 2 PRs once updated.

**Comment by SimonSapin** [comment]
Random idea: would it make sense to have wptrunner run a wrapper script rather than the servo binary directly?

**Pull request closed without merging**
