### PR TITLE
CI: build Linux amd64 --media-stack=dummy

### PR DESCRIPTION
**Pull request by ghost**
Include `--media-stack=dummy` in CI, as discussed in https://github.com/servo/servo/pull/24829.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because it's build infra

### CODE REVIEW

**Comment by jdm** [comment]
Rather than a separate build job that happens once per day, please add a --dev build with the dummy media stack to the list at https://github.com/servo/servo/blob/904fcb4317ffd0f1ed6d0400cdb768fedacfda3d/etc/taskcluster/decision_task.py#L212.

**Comment by tuncer** [comment]
Done

**Comment by jdm** [comment]
Looks good! Please squash the commits into one.

**Comment by tuncer** [comment]
Collapsed commits

**Comment by tuncer** [comment]
Before we merge this: is there a need to make sure there's no gstreamer in the build env, before executing the task? I mean, it's run after `build --dev -p servo-gst-plugin`, so I assume gstreamer is installed, in constrast to `linux_tidy_unit_untrusted`, where we first bootstrap gstreamer. That said, since we're explicitly selecting the dummy backend, it shouldn't matter. Thoughts?

**Comment by jdm** [comment]
I don't think it's worth the effort to build it in an environment that doesn't have gstreamer available.

**Comment by tuncer** [comment]
Test failure in _macOS x64: WPT chunk 02 / 20_ looks unrelated:

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58:
    ordinal not in range(128)
[...]task_1579029530/repo/python/servo/testing_commands.py",
    line 575, in filter_intermittents
```

**Comment by jdm** [comment]
@bors-servo retry
* #25513

**Pull request merged**
