### PR TITLE
Implement Worker.prototype.terminate().

### PR DESCRIPTION
**Pull request by Ms2ger**
Rebased #5846

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6652)

### CODE REVIEW

**Comment by metajack** [comment]
@Ms2ger This is getting long in the tooth.

**Comment by Ms2ger** [comment]
@jdm, I think I changed this enough that you should review it now.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/bindings/global.rs, line 267 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6652#-Jw2RDjkOUrnfDX10NwJ)** ([raw file](https://github.com/servo/servo/blob/ce47bf41ba79c703eab7e3e58611ab83fb99e97a/components/script/dom/bindings/global.rs#L267)):</sup>
We should be able to use CurrentGlobalOrNull instead of stashing something in the runtime private slot.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 179 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6652#-Jw2U0sriydzefYCwQtz)** ([raw file](https://github.com/servo/servo/blob/ce47bf41ba79c703eab7e3e58611ab83fb99e97a/components/script/dom/dedicatedworkerglobalscope.rs#L179)):</sup>
The SharedRt will be invalid at this point.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 199 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6652#-Jw2U9NmaMJ9VEQaljSE)** ([raw file](https://github.com/servo/servo/blob/ce47bf41ba79c703eab7e3e58611ab83fb99e97a/components/script/dom/dedicatedworkerglobalscope.rs#L199)):</sup>
As mentioned above, I don't think we need this.

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 203 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6652#-Jw2UPKg9vooW4Wif_-3)** ([raw file](https://github.com/servo/servo/blob/ce47bf41ba79c703eab7e3e58611ab83fb99e97a/components/script/dom/dedicatedworkerglobalscope.rs#L203)):</sup>
Is the cast still necessary here?

---

<sup>**[components/script/dom/dedicatedworkerglobalscope.rs, line 391 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6652#-Jw2X28xgvIdsIQ1QbxU)** ([raw file](https://github.com/servo/servo/blob/ce47bf41ba79c703eab7e3e58611ab83fb99e97a/components/script/dom/dedicatedworkerglobalscope.rs#L391)):</sup>
Should we have similar checks in the methods of WorkerGlobalScope?

---

<sup>**[components/script/dom/worker.rs, line 55 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6652#-Jw2XAl7mEVCRb3Flm1u)** ([raw file](https://github.com/servo/servo/blob/ce47bf41ba79c703eab7e3e58611ab83fb99e97a/components/script/dom/worker.rs#L55)):</sup>
Document these?

---

<sup>**[components/script/dom/worker.rs, line 136 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6652#-Jw2ZAJJiBMnSHtm6XR2)** ([raw file](https://github.com/servo/servo/blob/ce47bf41ba79c703eab7e3e58611ab83fb99e97a/components/script/dom/worker.rs#L136)):</sup>
Let's make an is_closing method that hides this.

---

<sup>**[components/script/dom/worker.rs, line 299 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6652#-Jw2YijVnFnkgPCfI7dU)** ([raw file](https://github.com/servo/servo/blob/ce47bf41ba79c703eab7e3e58611ab83fb99e97a/components/script/dom/worker.rs#L299)):</sup>
no_jsmanaged_fields? Maybe toss it in trace.rs, too?

---

<sup>**[components/script/dom/workerglobalscope.rs, line 166 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6652#-Jw2YolfX03nCzIAaLM9)** ([raw file](https://github.com/servo/servo/blob/ce47bf41ba79c703eab7e3e58611ab83fb99e97a/components/script/dom/workerglobalscope.rs#L166)):</sup>
nit: nix this newline

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6652)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6652)

**Comment by frewsxcv** [comment]
Any updates on this?

**Comment by frewsxcv** [comment]
Anyone opposed to closing this?

**Pull request closed without merging**
