### PR TITLE
Normalize `use` item lists in layout/.

### PR DESCRIPTION
**Pull request by nnethercote**
Currently they're generally broken into two separate lists, and many
items are out of order even within the two lists. This changeset sorts
them all. It also sorts the module list in components/layout/lib.rs.

### CODE REVIEW

**Comment by nnethercote** [comment]
As for why all these files have their use items in two groups... it feels like
maybe the first group is meant to be more specific layout stuff, and the second
group is more general library stuff, like `std` and `util`. Here's an example
from components/layout/table_rowgroup.rs.
```
use block::{BlockFlow, ISizeAndMarginsComputer};
use context::LayoutContext;
use flow::{FlowClass, Flow};
use fragment::{Fragment, FragmentBorderBoxIterator};
use layout_debug;
use style::computed_values::border_spacing;
use table::{ChildInlineSizeInfo, ColumnComputedInlineSize, ColumnIntrinsicInlineSize};
use table::{InternalTable, TableLikeFlow};
use wrapper::ThreadSafeLayoutNode;

use geom::{Point2D, Rect};
use util::geometry::Au;
use util::logical_geometry::LogicalRect;
use std::fmt;
use style::properties::ComputedValues;
use std::sync::Arc;
```
But even that isn't consistently applied, e.g. there are `style` imports in
both halves.

Whatever the grouping is, I suspect it's not worth the trouble -- it's the kind
of thing that's really difficult to maintain. Having said that, I fully admit
to interfering in code I barely understand, so please tell me to butt out if
I'm missing something important :)

**Comment by nnethercote** [comment]
> These commits modify unsafe code.

That's not true. I suspect @highfive is just grepping for "unsafe". If it instead grepped for "\<unsafe\>" (or "\bunsafe\b", depending on your regexp syntax) it wouldn't have raised this false positive.

**Comment by Ms2ger** [comment]
FWIW, I tend to split them into imports from

1. the same crate
2. other crates in the Servo repo
3. crates from cargo deps
4. crates shipped with the compiler (I guess that's just std and core now)

**Comment by jdm** [comment]
I follow @Ms2ger's orderings as well.

**Comment by pcwalton** [comment]
The style I've been following in layout is "this crate, blank line, external crates". External crates include other Servo crates, external Rust repos, and the standard libraries. However, I don't feel strongly about this and am happy to change.

**Comment by nnethercote** [comment]
A single obvious style seems preferable to multiple non-obvious styles. Just sayin'.

**Comment by jdm** [comment]
We should decide on a style, make tidy.py check for it, and update everything at once. Until then, no need to keep this open.

**Comment by frewsxcv** [comment]
Also, there have been talks in the community about rustfmt, so that would automate this sort of thing anyways.

**Pull request closed without merging**
