### PR TITLE
Cancelable network requests!

### LINKED ISSUE #4974: Make network requests cancelable
Right now it is possible to "cancel" a network request by freeing the Receiver that corresponds to the network response (ie. when the Receiver goes out of scope), since that causes the network thread to panic when it tries to send on the closed channel. This won't be enough when we move to an event-based system instead of using channels - the network thread will just keep sending events to the target thread, and the target thread has no way to inform the network thread that the response is not wanted.

I propose the following:
* create a new `ResourceId` type that wraps an integer
* add a new optional `Sender<ResourceId>` argument to the `Load` message in `ControlMsg` in `resource_task.rs`
* in the load handler for `ResourceTask`, generate a new resource id for each load that requires it, and send it on the provided `Sender` if it exists
* for loads with a resource id, create a new channel and store the sender in a vector in `ResourceTask`, and pass the receiver to the loader factory
* in each loader implementation, use the new optional receiver to check if a load is supposed to be cancelled at key points (after headers are received and before each read of the response) 
* add a new `Cancel` message to `ControlMsg` in `resource_task.rs` which takes a `ResourceId`, finds the corresponding entry in the vector and sends a message on corresponding termination sender

### PR DESCRIPTION
**Pull request by ghost**
fixes #4974

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7844)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
This is incomplete!

**Comment by jdm** [comment]
Curious time to open a pull request, in that case :)

**Comment by Wafflespeanut** [comment]
@jdm Though I've stolen some of the ideas from #5826, it's still incomplete and the build doesn't succeed (so, please ignore the errors if you find any). I have a few questions...

- I'm not sure I can find all the key points where we should check for cancellation (for now, I've added those in loading/handling loops - places which I thought might need this, but I'm not sure)
- We cannot have a `Sender` in `ControlMsg` because it doesn't impl serialization. We could make use of `ipc_channel`, but it doesn't return a proper error (see below)
- 


---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/resource_task.rs, line 183 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K-jo0scrk_UKocD9PVt)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/resource_task.rs#L183)):</sup>
This is plain wrong! (ignore it, I somehow missed to see this). We shouldn't remove it, as we'll then index the wrong sender in the future. We could go for an `Option<Sender...>` (as I've said below)


---

<sup>**[components/net/resource_task.rs, line 208 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K-jpNsFiYPID4ViMo3U)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/resource_task.rs#L208)):</sup>
This is where `IpcReceiver` doesn't help (if we ever plan to go for it).  We can't differentiate between both the cases represented by the enum. I thought of routing the `IpcReceiver` into a `Receiver`, but the method consumes the old `IpcReceiver` and so, we can't possibly have it here. Having it outside appears rather ugly, and I'm also not sure whether that method would be efficient.


---

<sup>**[components/net/resource_task.rs, line 224 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K-jpxaxGeIDOMFd2H33)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/resource_task.rs#L224)):</sup>
... could be `Vec<Option<Sender<CancelLoad>>>` so that we can mark the senders as `None` once we send the cancel request.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
@jdm Rust keeps me awake during my weekends :)

**Comment by Wafflespeanut** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/data_loader.rs, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K-m9vpUUb1Kt7PH2Gk0)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/data_loader.rs#L26)):</sup>
Oh, and I've left this, because I can't see where I should be checking for cancel requests here :/


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by jdm** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/data_loader.rs, line 26 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K-m9vpUUb1Kt7PH2Gk0)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/data_loader.rs#L26)):</sup>
I would check right before sending the actual data.


---

<sup>**[components/net/file_loader.rs, line 65 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K01oEo9mYbxIGzr99Eg)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/file_loader.rs#L65)):</sup>
Careful - when we detect a cancelled channel, we need to make sure that we have sent the initial start message and a `Done(Err(Canceled))` final message before returning. We should try creating a stack guard with a destructor that does this for us, if possible.


---

<sup>**[components/net/resource_task.rs, line 169 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K02DWCR88BV0gqTPpOj)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/resource_task.rs#L169)):</sup>
Let's call this `id_sender`.


---

<sup>**[components/net/resource_task.rs, line 183 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K-jo0scrk_UKocD9PVt)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/resource_task.rs#L183)):</sup>
Removing is good, otherwise we'll end up with a monotonically-increasing vector over the lifetime of the browser.


---

<sup>**[components/net/resource_task.rs, line 208 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K-jpNsFiYPID4ViMo3U)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/resource_task.rs#L208)):</sup>
This shouldn't need to be `IpcReceiver`, since it's only used internally in the same process.


---

<sup>**[components/net/resource_task.rs, line 224 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K-jpxaxGeIDOMFd2H33)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/resource_task.rs#L224)):</sup>
We should store a `HashMap<ResourceId, Sender<CancelLoad>>` instead, to allow for removal.


---

<sup>**[components/net/resource_task.rs, line 260 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K02C9HvbA2Kewcjx3ZL)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/resource_task.rs#L260)):</sup>
Let's call this `id_sender` instead.


---

<sup>**[components/net/resource_task.rs, line 274 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K02CLgMU_rzOP97z8E7)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net/resource_task.rs#L274)):</sup>
This should ignore the error with `let _ =`.


---

<sup>**[components/net_traits/lib.rs, line 230 \[r1\]](https://reviewable.io:443/reviews/servo/servo/7844#-K02CfPvvMlHj3_Gm9kW)** ([raw file](https://github.com/servo/servo/blob/64105fe510d502baac9d80909bd5f65fada349d3/components/net_traits/lib.rs#L230)):</sup>
This doesn't build, right? Doesn't this need to be an `IpcSender`?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
@jdm We still have some trouble with the setup. Firstly, the `CancellationListener` gets [consumed along the way](https://github.com/servo/servo/blob/dd21ff59db18569fbf3ff05213b495c9082b5ef7/components/net/resource_task.rs#L311), which is why I thought of going for an `Option<&Receiver<CancelLoad>>` (since we can send the reference around anywhere). But, it demands a lifetime, which [conflicts with that of the box](https://github.com/servo/servo/blob/dd21ff59db18569fbf3ff05213b495c9082b5ef7/components/net/resource_task.rs#L268). Any ideas how I can proceed further? Is `CancelLoad` fine, or are there any other ways I can send a cancel message?

(also, have a look at my current changes)

**Comment by jdm** [comment]
What problem are you trying to solve, exactly? The CancellationListener is different Receiver value, and the item that gets stored in the HashMap is the corresponding Sender, right? The code looks to me like everything should just work if we return `cancel_receiver` inside the `map` call, rather than `&cancel_receiver`.

**Comment by Wafflespeanut** [comment]
This isn't done yet! I've just rebased and updated the tests (unit tests are on the way)...

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/net/resource_task.rs, line 191 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7844#-K1_KZ3XN-X_v7bu7Nw9)** ([raw file](https://github.com/servo/servo/blob/3854491e2e1c11a7b6c17d1fbe2c5b590240a4c8/components/net/resource_task.rs#L191)):</sup>
nit: new line here.


---

<sup>**[tests/unit/net/data_loader.rs, line 25 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7844#-K1_KverH1hPoygpSC9A)** ([raw file](https://github.com/servo/servo/blob/3854491e2e1c11a7b6c17d1fbe2c5b590240a4c8/tests/unit/net/data_loader.rs#L25)):</sup>
I don't think this comment adds anything.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/net/data_loader.rs, line 25 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7844#-K1_KverH1hPoygpSC9A)** ([raw file](https://github.com/servo/servo/blob/3854491e2e1c11a7b6c17d1fbe2c5b590240a4c8/tests/unit/net/data_loader.rs#L25)):</sup>
Oops, forgot to remove that one :)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/unit/net/resource_task.rs, line 182 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7844#-K1uCKHhd_-lgrSwUXY8)** ([raw file](https://github.com/servo/servo/blob/abcd8b5358f16b19333d237174b38693273b4b26/tests/unit/net/resource_task.rs#L182)):</sup>
Only now do I come to think this test is just stupid. Didn't you ask me to test the cancel listener in`send_data` and return a `Done(Err(...))` message?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by jdm** [comment]
Reviewed 2 of 2 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/net/resource_task.rs, line 219 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7844#-K1vn2wMxv6B9iko5jKN)** ([raw file](https://github.com/servo/servo/blob/abcd8b5358f16b19333d237174b38693273b4b26/components/net/resource_task.rs#L219)):</sup>
I don't understand the motivation behind this change.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/net/resource_task.rs, line 219 \[r5\]](https://reviewable.io:443/reviews/servo/servo/7844#-K1vn2wMxv6B9iko5jKN)** ([raw file](https://github.com/servo/servo/blob/abcd8b5358f16b19333d237174b38693273b4b26/components/net/resource_task.rs#L219)):</sup>
Yep, sorry. It sucks. I thought this might solve the problem of detecting whether the sender's already been canceled, but then it doesn't distinguish between the absence of a sender and the destruction of a sender. I'm working on it :)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
Oh my... *(sigh)*

**Comment by jdm** [comment]
-S-needs-rebase -S-awaiting-answer -S-awaiting-review +S-needs-code-changes 


---

Reviewed 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[components/net/http_loader.rs, line 728 \[r6\]](https://reviewable.io:443/reviews/servo/servo/7844#-K27_OcAnKtNudd66pQU)** ([raw file](https://github.com/servo/servo/blob/17887ef8b45abc0bf239118261ad8815efec2336/components/net/http_loader.rs#L728)):</sup>
Let's remove the unwrap here.


---

<sup>**[components/net/resource_task.rs, line 191 \[r6\]](https://reviewable.io:443/reviews/servo/servo/7844#-K27_hLG0aKbephyPRUa)** ([raw file](https://github.com/servo/servo/blob/17887ef8b45abc0bf239118261ad8815efec2336/components/net/resource_task.rs#L191)):</sup>
Let's remove the unwrap here.


---

<sup>**[components/net/resource_task.rs, line 291 \[r6\]](https://reviewable.io:443/reviews/servo/servo/7844#-K27aFqL-PyYWQajjpWM)** ([raw file](https://github.com/servo/servo/blob/17887ef8b45abc0bf239118261ad8815efec2336/components/net/resource_task.rs#L291)):</sup>
Let's remove the unwrap here.


---

<sup>**[tests/unit/net/resource_task.rs, line 180 \[r6\]](https://reviewable.io:443/reviews/servo/servo/7844#-K27bDPkSn6rUvdKoYf0)** ([raw file](https://github.com/servo/servo/blob/17887ef8b45abc0bf239118261ad8815efec2336/tests/unit/net/resource_task.rs#L180)):</sup>
This causes us to test something else than cancellation, unfortunately: http://mxr.mozilla.org/servo/source/components/net/resource_task.rs#251 . We could set up a TCP server on a particular port and make an HTTP connection to that, instead: https://github.com/servo/servo/commit/f52276d2ccf2b59de7dc9548d305ff4900952886#diff-9191332a78da32d4f24b94156d11ae20L170


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
hmm, vaving a test [something like this](https://gist.github.com/Wafflespeanut/ea4d9d5117939367a5e7) seems to work, but I can't make it work with `TcpListener`. Am I right that the test stalls because the TcpListener doesn't respond to the request?

**Comment by jdm** [comment]
Spawn a thread, accept the conncection, then close it? http://mxr.mozilla.org/servo/source/components/devtools/lib.rs#396

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 9 of 9 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/net/resource_task.rs, line 190 \[r7\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2CZGAPKpJlHz9yQ7hJ)** ([raw file](https://github.com/servo/servo/blob/d46f06f0fd3f4f6e9b4f7324b0b86d574f962c60/tests/unit/net/resource_task.rs#L190)):</sup>
We don't need to do any host replacement here; we can just contact 127.0.0.1:$port directly.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
@jdm The backtrace is also not helpful, because I can't seem to find where "os error" occurs :/

    ---- resource_task::test_cancelled_listener stdout ----
    	thread 'resource_task::test_cancelled_listener' panicked at 'assertion failed: `(left == right)` (left: `"os error"`, right: `"load cancelled"`)', /media/Windows/Mozilla/servo/tests/unit/net/resource_task.rs:199
    stack backtrace:
       1:     0x7f921d976040 - sys::backtrace::tracing::imp::write::h23bfa7a49ed99d87Klt
       2:     0x7f921d978685 - panicking::log_panic::_<closure>::closure.39180
       3:     0x7f921d9780f5 - panicking::log_panic::h846e3da4ec5bd0b1Wlx
       4:     0x7f921d9673c3 - sys_common::unwind::begin_unwind_inner::h04ad996baf6f81c7bds
       5:     0x7f921d967a78 - sys_common::unwind::begin_unwind_fmt::h44d552a66c65968bhcs
       6:     0x7f921d618fbb - resource_task::test_cancelled_listener::hc5574a0d1bc8efb7A1b
                            at /media/Windows/Mozilla/servo/components/servo/<std macros>:8
       7:     0x7f921d918896 - boxed::_<impl>::call_box::call_box::h1520729919878957002
       8:     0x7f921d91ae18 - boxed::_<impl>::call_box::call_box::h17282746878263628964
       9:     0x7f921d919184 - sys_common::unwind::try::try_fn::try_fn::h14061410362995320864
      10:     0x7f921d975578 - __rust_try
      11:     0x7f921d9720eb - sys_common::unwind::try::inner_try::h25c781202f1ad3a1J9r
      12:     0x7f921d91931e - boxed::_<impl>::call_box::call_box::h7646584381128873602
      13:     0x7f921d977173 - sys::thread::_<impl>::new::thread_start::h89508aa1f401717d8Dw
      14:     0x7f921c014181 - start_thread
      15:     0x7f921c82e47c - __clone
      16:                0x0 - <unknown>

**Comment by jdm** [comment]
-S-awaiting-review +S-awaiting-answer 


---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/net/resource_task.rs, line 187 \[r8\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2IOyjbkYw-vXX7q-fN)** ([raw file](https://github.com/servo/servo/blob/7c627ad51c5ce162c3cbe3e698f04b399358b4c4/tests/unit/net/resource_task.rs#L187)):</sup>
What about
```rust
let mut conns = vec![];
for stream in listener.incoming() {
    conns.push(stream);
}
```
Perhaps this is closing the connection as soon as it's initiated.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
@jdm I seem to experience an *anomaly*. Whenever I make a change and run the test, (i.e) whenever it compiles and runs the test for the first time, the test passes. Further re-runs almost always fail! I know this sounds crazy, but I've ran the test quite a lot of times, and the same thing happens.

I guess this has something to do with the rate at which the response is received and evaluated. Because, we're making use of channels to get the `ResourceId`, which we wrap it inside a cancel message and send it back to resource task - before which the data chunk appears to be loaded and sent back to us as a `Payload` (or, maybe I'm drunk)

**Comment by jdm** [comment]
-S-needs-rebase -S-awaiting-review -S-awaiting-answer +S-needs-code-changes 


---

Reviewed 7 of 7 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/unit/net/resource_task.rs, line 192 \[r10\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2Xg9vTnbWnixrkagHc)** ([raw file](https://github.com/servo/servo/blob/4c6a2e40ba2c5faf54ddbacc856f6085944c66d2/tests/unit/net/resource_task.rs#L192)):</sup>
We can actually use `let stream_result = listener.accept();` and just take one connection.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
@jdm

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/unit/net/resource_task.rs, line 214 \[r11\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2Yo0mlFuqEkTFqxdgX)** ([raw file](https://github.com/servo/servo/blob/8c6ceb442ffeccf6359342b2b27e3382f8b32192/tests/unit/net/resource_task.rs#L214)):</sup>
I think I see the issue - the cancel message is asynchronous, so there's no guarantee that the cancellation has occurred by the time we tell the server to resume sending its body. We could send a GetCookiesForUrl message (which has a synchronous receiver) after the cancellation to ensure that it's finished processing.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
@jdm You were right about the synchronous receivers, that we finally have a working test! What's next? :)

**Comment by jdm** [comment]
The last missing piece here is that the entries for non-cancelled requests are never removed from the hashmap in the resource manager, so we'll slowly leak memory over time.
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 5 of 5 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
@jdm I think this would work, but I'm not sure about the readability. Feel free to pinch me :)


---

Review status: 7 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/net/resource_task.rs, line 311 \[r13\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2rN7sh5pJiV-T4lQ1c)** ([raw file](https://github.com/servo/servo/blob/6eded932c782a7e75f7cc2eb39945bae0981daa8/components/net/resource_task.rs#L311)):</sup>
This is where I'm concerned about the readability and elegance. Is this okay?


---

<sup>**[components/net/resource_task.rs, line 339 \[r13\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2rNlcqVVZBRToE6zSV)** ([raw file](https://github.com/servo/servo/blob/6eded932c782a7e75f7cc2eb39945bae0981daa8/components/net/resource_task.rs#L339)):</sup>
Also this is what I can think of, but it makes the resource manager wait till it gets the message when it removes the ResourceId from the hashmap. Is it the right way?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 4 of 4 files at r13.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/net/resource_task.rs, line 238 \[r13\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2rPjKdnARsXk3VHilk)** ([raw file](https://github.com/servo/servo/blob/6eded932c782a7e75f7cc2eb39945bae0981daa8/components/net/resource_task.rs#L238)):</sup>
Let's make this a destructor instead, so it's impossible to leak these resources.


---

<sup>**[components/net/resource_task.rs, line 339 \[r13\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2rNlcqVVZBRToE6zSV)** ([raw file](https://github.com/servo/servo/blob/6eded932c782a7e75f7cc2eb39945bae0981daa8/components/net/resource_task.rs#L339)):</sup>
This will make the resource task block until the complete response is received, which is not what we want :) Let's add a new message to ControlMsg and have CancellationListener store a sender to communicate with the main event loop of the resource task.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 5 of 5 files at r14.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[components/net/resource_task.rs, line 208 \[r14\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2roJ2c3eK6Z0fy7r9N)** ([raw file](https://github.com/servo/servo/blob/eebc285e51e322c8fb849f8309eda5728ed762a7/components/net/resource_task.rs#L208)):</sup>
Let's make this:
```rust
struct CancellableResource {
    receiver: Receiver<CancelLoad>,
    resource_id: ResourceId,
    resource_task: ResourceTask,
}
```
and just have a single `Option<CancellableResource>` in `CancellationListener`.


---

<sup>**[components/net/resource_task.rs, line 249 \[r14\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2rohjEq8ncSyvahD10)** ([raw file](https://github.com/servo/servo/blob/eebc285e51e322c8fb849f8309eda5728ed762a7/components/net/resource_task.rs#L249)):</sup>
"Ensure the resource manager stops tracking this request now that it's terminated."


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by Wafflespeanut** [comment]
Your suggestion looks really elegant! Thanks! :)


---

Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/net/resource_task.rs, line 202 \[r15\]](https://reviewable.io:443/reviews/servo/servo/7844#-K2uwKf_GusXRjyLnDjw)** ([raw file](https://github.com/servo/servo/blob/c4cf72db6e69cda90f4ad98933da95cead7da243/components/net/resource_task.rs#L202)):</sup>
I think we don't need a struct just for sending a cancellation message. We can achieve the same with a tuple, because we're creating them as cancel senders & receivers anyway. What do you say?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Comment by jdm** [comment]
@bors-servo: r+


---

Reviewed 2 of 2 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7844)

**Pull request merged**
