### PR TITLE
Multiple gecko backouts

### PR DESCRIPTION
**Pull request by moz-servo-sync**
@bors-servo r+ force treeclosed=9001

Backed out changeset f5041651b877 (bug 17452) as requested by glob. r=backout

Backs out https://github.com/servo/servo/pull/17452

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17473)

---

Backed out changeset de9bb450199d  on request from glob

Backs out https://github.com/servo/servo/pull/17452

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@edunham @Manishearth Do either of you have any idea why this was not approved? e.g., does homu not parse commands if they are in the initial comment? The `moz-servo-sync` user is definitely in the reviewers list for servo/servo in `cfg.toml` on servo-master1 and I restarted the service.

**Comment by jdm** [comment]
Yes, homu commands are ignored in the initial PR description.

**Comment by larsbergstrom** [comment]
Thanks, @jdm!

@globau Can you please change the PR creation code to put the bits with the approval into a comment in the PR? If that's too hard, we can look into changing the homu code, too.

**Comment by globau** [comment]
https://hg.mozilla.org/hgcustom/version-control-tools/rev/024c6a80914e

**Comment by globau** [comment]
@larsbergstrom looks like the tree was closed, but this PR hasn't been processed.  could it be because it's missing p=9001 from the bors command?

**Comment by KiChjang** [comment]
@globau Looking at http://build.servo.org/homu/queue/servo, it looks like your observation is correct, though I'm not sure if it requires 9002 instead of 9001.

**Comment by KiChjang** [comment]
Ah, looks like the maximum priority is 9001, and can't go any higher. Perhaps set treeclosed to 9000 instead?

**Pull request merged**
