### PR TITLE
Remove pipeline visibility checks

### LINKED ISSUE #22986: HTMLIframeElement.set_visible is unused
This means that all of the checks around pipeline visibility in Servo are currently redundant, since set_visible is the only method that sends the constellation the SetVisible message.

### PR DESCRIPTION
**Pull request by AZWN**
This includes the following changes/clean-ups:

- Remove ```is_visible``` field from ```Pipeline``` struct
- Remove ```SetVisible``` script message, and related message sending/handling.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22986

- [x] These changes do not require tests because the issue description states having a passing build is enough for a pull request.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23007)

### CODE REVIEW

**Comment by jdm** [comment]
We should not remove the Pipeline::notify_visibility API as part of this work.

**Comment by AZWN** [comment]
Ok, then I was too eager haha. I restored the Pipeline::notify_visibility API.

**Comment by jdm** [comment]
Looks great! Could you [squash](https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/) the commits into one single one, please?

**Review by jdm — APPROVED** [review]

**Comment by AZWN** [comment]
I squashed the commits. Is there something more that needs to be done?

**Comment by jdm** [comment]
@bors-servo r+
Nope!

**Pull request merged**
