### PR TITLE
Remove dependency on regex_macros

### PR DESCRIPTION
**Pull request by SimonSapin**
This reduces the amount of code using unstable features that we depend on.
The hand-written IP address parser is probably just as fast.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8653)

### CODE REVIEW

**Comment by jdm** [comment]
```
./components/net/hsts.rs:7: use statement is not in alphabetical order

	expected: std::net::{Ipv4Addr, Ipv6Addr}

	found: std::str::{from_utf8}

./components/net/hsts.rs:8: use statement is not in alphabetical order

	expected: std::str::{from_utf8}

	found: std::net::{Ipv4Addr, Ipv6Addr}
```

**Comment by jdm** [comment]
Otherwise this is fine with me.

**Comment by SimonSapin** [comment]
Fixed

**Comment by jdm** [comment]
```
---- resource_task::test_parse_hostsfile_with_invalid_ipv6_addresses stdout ----
	thread 'resource_task::test_parse_hostsfile_with_invalid_ipv6_addresses' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `2`)', /Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/resource_task.rs:140
stack backtrace:
   1:        0x10b3d14d8 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s
   2:        0x10b3d2fdf - panicking::log_panic::_<closure>::closure.38923
   3:        0x10b3d2aac - panicking::log_panic::h87af6096e0b6fa7c4Uw
   4:        0x10b3c3ef6 - sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r
   5:        0x10b3c42de - sys_common::unwind::begin_unwind_fmt::he992719329bdd2c6x7r
   6:        0x10ab92d67 - resource_task::test_parse_hostsfile_with_invalid_ipv6_addresses::h0833a4853336be88vQb
   7:        0x10b3627cb - boxed::_<impl>::call_box::call_box::h1439439458556714188
   8:        0x10b364f1d - boxed::_<impl>::call_box::call_box::h8069092559954270103
   9:        0x10b363122 - sys_common::unwind::try::try_fn::try_fn::h11324081254561251759
  10:        0x10b3d09a8 - __rust_try
  11:        0x10b3ce32e - sys_common::unwind::try::inner_try::hc13d8e198528cd0fZ4r
  12:        0x10b3632d2 - boxed::_<impl>::call_box::call_box::h6022582708213645161
  13:        0x10b3d23ad - sys::thread::_<impl>::new::thread_start::h906ddce3a93d4852ksw
  14:     0x7fff91449059 - _pthread_body
  15:     0x7fff91448fd6 - _pthread_start

---- resource_task::test_parse_hostsfile_with_valid_ipv6_addresses stdout ----
	thread 'resource_task::test_parse_hostsfile_with_valid_ipv6_addresses' panicked at 'assertion failed: `(left == right)` (left: `12`, right: `9`)', /Users/servo/buildbot/slave/mac-dev-ref-unit/build/tests/unit/net/resource_task.rs:129
stack backtrace:
   1:        0x10b3d14d8 - sys::backtrace::tracing::imp::write::h662793599f713c74T5s
   2:        0x10b3d2fdf - panicking::log_panic::_<closure>::closure.38923
   3:        0x10b3d2aac - panicking::log_panic::h87af6096e0b6fa7c4Uw
   4:        0x10b3c3ef6 - sys_common::unwind::begin_unwind_inner::h1e338bc64cf56d9dr8r
   5:        0x10b3c42de - sys_common::unwind::begin_unwind_fmt::he992719329bdd2c6x7r
   6:        0x10ab92b17 - resource_task::test_parse_hostsfile_with_valid_ipv6_addresses::h5ef6137ba1c2dfbdVOb
   7:        0x10b3627cb - boxed::_<impl>::call_box::call_box::h1439439458556714188
   8:        0x10b364f1d - boxed::_<impl>::call_box::call_box::h8069092559954270103
   9:        0x10b363122 - sys_common::unwind::try::try_fn::try_fn::h11324081254561251759
  10:        0x10b3d09a8 - __rust_try
  11:        0x10b3ce32e - sys_common::unwind::try::inner_try::hc13d8e198528cd0fZ4r
  12:        0x10b3632d2 - boxed::_<impl>::call_box::call_box::h6022582708213645161
  13:        0x10b3d23ad - sys::thread::_<impl>::new::thread_start::h906ddce3a93d4852ksw
  14:     0x7fff91449059 - _pthread_body
  15:     0x7fff91448fd6 - _pthread_start


failures:
    resource_task::test_parse_hostsfile_with_invalid_ipv6_addresses
    resource_task::test_parse_hostsfile_with_valid_ipv6_addresses
```

**Comment by SimonSapin** [comment]
The original regex for IPv6 includes a `/\d{1,3}` suffix which looks like a subnet notation (and unit tests test accordingly), but the rest of the code doesn’t seem to do any address range computation. I’m inclined to change the test here.

CC @gilles-leblanc https://github.com/servo/servo/commit/0faa55d2ce22ae542d14604d8bdc91e0a89c77a1#commitcomment-14562450

**Comment by SimonSapin** [comment]
@bors-servo retry

* #8228 (possibly)

**Comment by jdm** [comment]
It's more likely #7437.

**Comment by SimonSapin** [comment]
@bors-servo r=Ms2ger

Rebased, conflict resolved automatically by kdiff3

**Comment by jdm** [comment]
@bors-servo: retry
* #8311

**Pull request merged**
