### PR TITLE
Send request's integrity metadata via RequestBuilder

### LINKED ISSUE #24906: CORS integrity WPT test failures (Servo is being too permissive)
WPT test fetch/api/basic/integrity is acting like everything it sees is valid, including the test cases that are supposed to be invalid.

### PR DESCRIPTION
**Pull request by pshaughn**
RequestBuilder wasn't reinflating integrity_metadata along with other request fields, so main_fetch never saw that an integrity checksum was requested. Integrity checking seems to have otherwise been working; with this change, the entire WPT test for it passes (other than the SharedWorker test, which would probably pass if we had SharedWorker)

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #24906

- [X] There are tests for these changes

### CODE REVIEW

**Comment by CYBAI** [comment]
This will need to be updated 👀

```
  ▶ ERROR [expected OK] /fetch/api/basic/integrity.sub.any.sharedworker.html
  │   → SharedWorker is not defined
  │ 
  └ @http://web-platform.test:8000/fetch/api/basic/integrity.sub.any.sharedworker.html:8:1
```

and I suspect this is an intermittent 🤔

```
  ▶ CRASH [expected OK] /FileAPI/url/url-format.any.worker.html
  │ 
  │ 
  │ 
  │ 
  │ called `Result::unwrap()` on an `Err` value: Io(Custom { kind: ConnectionReset, error: "All senders for this socket closed" }) (thread WebWorker for http://web-platform.test:8000/FileAPI/url/url-format.any.worker.js, at components/script/dom/globalscope.rs:1291)
  │ stack backtrace:
  │    0: servo::backtrace::print
  │    1: servo::main::{{closure}}
  │    2: std::panicking::rust_panic_with_hook
  │              at src/libstd/panicking.rs:476
  │    3: rust_begin_unwind
  │              at src/libstd/panicking.rs:380
  │    4: core::panicking::panic_fmt
  │              at src/libcore/panicking.rs:85
  │    5: core::option::expect_none_failed
  │              at src/libcore/option.rs:1198
  │    6: script::dom::globalscope::GlobalScope::promote
  │    7: script::dom::globalscope::GlobalScope::get_blob_url_id
  │    8: script::dom::blob::Blob::get_blob_url_id
  │    9: script::dom::url::URL::CreateObjectURL
  │   10: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  │   11: _ZN3std9panicking3try7do_call17hf3aebb9b3a2f1958E.llvm.16428511656612885158
  │   12: __rust_maybe_catch_panic
  │              at src/libpanic_unwind/lib.rs:86
  │   13: script::dom::bindings::codegen::Bindings::URLBinding::URLBinding::createObjectURL
  │   14: <unknown>
  │   15: <unknown>
  │   16: <unknown>
  │   17: _ZL13EnterBaselineP9JSContextRN2js3jit12EnterJitDataE
  │              at /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/jit/BaselineJIT.cpp:111
  │       _ZN2js3jit21EnterBaselineAtBranchEP9JSContextPNS_16InterpreterFrameEPh
  │              at /root/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/jit/BaselineJIT.cpp:189
  │   18: <unknown>
  │ 
  │ [2020-01-30T00:59:24Z ERROR servo] called `Result::unwrap()` on an `Err` value: Io(Custom { kind: ConnectionReset, error: "All senders for this socket closed" })
  └ Pipeline failed in hard-fail mode.  Crashing!
```

**Comment by pshaughn** [comment]
The first was me not realizing this test had a third case to it and deleting the entire metadata file; the second is indeed intermittent.

**Pull request merged**
