### PR TITLE
Allow another wording of apache2/MIT (used by gaol)

### PR DESCRIPTION
**Pull request by edunham**
r? @larsbergstrom 

need this for https://github.com/servo/servo/issues/10636

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10715)

### CODE REVIEW

**Comment by UK992** [comment]
How about these headers in https://github.com/servo/servo/blob/master/support/rust-task_info/src/ ? 
test-tidy complain about incorrect licence

**Comment by edunham** [comment]
@UK992 the issue for fixing this the right way rather than the fast way is open at  https://github.com/servo/servo/issues/10716 :)

**Comment by edunham** [comment]
I've gone ahead and pushed 0.0.3 to pypi to unblock some other PRs

**Pull request merged**
