### PR TITLE
Cleanup URLSearchParams

### PR DESCRIPTION
**Pull request by nox**
It now uses rust-url for its serializer.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6192)

### CODE REVIEW

**Comment by nox** [comment]
I have some other URL-related changes but I've seen some other people implement things in that area, so I thought I should submit this first ASAP.

@Manishearth r?

**Comment by Manishearth** [comment]
Review status: 3 of 4 files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- components/script/dom/urlsearchparams.rs @ r1
- components/script/dom/xmlhttprequest.rs @ r1
- components/servo/Cargo.lock @ r1

---

<sup>**[components/script/dom/urlsearchparams.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6192#-JqJXJKJcPa6aFpl7eed)** ([raw file](https://github.com/servo/servo/blob/1d019e54391b7fbb0d505be49c77d9b594223f59/components/script/dom/urlsearchparams.rs#L56)):</sup>
This fixme can be fixed now. Just `init.list.borrow().clone()` should work

---

<sup>**[components/script/dom/urlsearchparams.rs, line 108 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6192#-JqJZidotp8ioPInDex_)** ([raw file](https://github.com/servo/servo/blob/1d019e54391b7fbb0d505be49c77d9b594223f59/components/script/dom/urlsearchparams.rs#L108)):</sup>
filter_map would lead to more readable code here, however it causes an extra allocation. (we can keep it the way it is)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6192)

**Comment by Manishearth** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- components/script/Cargo.toml @ r1
- components/script/dom/urlsearchparams.rs @ r1
- components/script/dom/xmlhttprequest.rs @ r1
- components/servo/Cargo.lock @ r1

---

<sup>**[components/script/dom/urlsearchparams.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6192#-JqJXJKJcPa6aFpl7eed)** ([raw file](https://github.com/servo/servo/blob/1d019e54391b7fbb0d505be49c77d9b594223f59/components/script/dom/urlsearchparams.rs#L56)):</sup>
This fixme can be fixed now. Just `init.list.borrow().clone()` should work

---

<sup>**[components/script/dom/urlsearchparams.rs, line 108 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6192#-JqJZidotp8ioPInDex_)** ([raw file](https://github.com/servo/servo/blob/1d019e54391b7fbb0d505be49c77d9b594223f59/components/script/dom/urlsearchparams.rs#L108)):</sup>
filter_map would lead to more readable code here, however it causes an extra allocation. (we can keep it the way it is)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6192)

**Comment by nox** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/urlsearchparams.rs, line 56 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6192#-JqJXJKJcPa6aFpl7eed)** ([raw file](https://github.com/servo/servo/blob/1d019e54391b7fbb0d505be49c77d9b594223f59/components/script/dom/urlsearchparams.rs#L56)):</sup>
I tried, but it didn't work. I simplified the *map part though.

---

<sup>**[components/script/dom/urlsearchparams.rs, line 108 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6192#-JqJZidotp8ioPInDex_)** ([raw file](https://github.com/servo/servo/blob/1d019e54391b7fbb0d505be49c77d9b594223f59/components/script/dom/urlsearchparams.rs#L108)):</sup>
I will keep it this way, I use mem::swap() to mess with RootedVec values, it's not to extra-allocate here. :P

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6192)

**Comment by Manishearth** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/script/dom/urlsearchparams.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6192)

**Pull request merged**
