### PR TITLE
Converting all URIs to URLs

### PR DESCRIPTION
**Pull request by Coder206**
This addresses the fix for #11450

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11532)

### CODE REVIEW

**Comment by KiChjang** [comment]
This contains fixes to the `tests/` directory as well, which I think is not intended.

**Comment by Coder206** [comment]
@KiChjang Is it possible to select certain files for the PR merge?

**Comment by KiChjang** [comment]
No, but it's possible to revert your changes on the `tests/` files.

**Comment by Coder206** [comment]
@KiChjang I am just starting out, do you know the steps to doing this?

**Comment by KiChjang** [comment]
`git checkout HEAD^ -- tests` and then `git commit --amend -C HEAD` should do the trick.

**Comment by Coder206** [comment]
@KiChjang Thanks for all your help! I appreciate it! :)

**Comment by Coder206** [comment]
@KiChjang I made the changes.

**Comment by KiChjang** [comment]
It doesn't seem like you've pushed anything to your branch; we can't see your changes.

**Comment by Coder206** [comment]
@KiChjang Hang on, I just forgot the last code snippet.

**Comment by Coder206** [comment]
@KiChjang There we go!

**Comment by KiChjang** [comment]
I'm still seeing changes in the `tests/` directory.

**Comment by Coder206** [comment]
@KiChjang That's odd. I think I am going to pull down my PR request and rework this fix.

**Pull request closed without merging**
