### PR TITLE
Changed performance interface's timing to an attribute

### LINKED ISSUE #23330: Performance interface's timing member should be an attribute
Per https://w3c.github.io/navigation-timing/#extensions-to-the-performance-interface we should have a `timing` attribute in our WebIDL interface, not a method.

Code: `components/script/dom/webidls/Performance.webidl`, `components/script/dom/performance.rs`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/navigation-timing/`

### PR DESCRIPTION
**Pull request by bcamp**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #23330 (GitHub issue number if applicable)

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23773)

### CODE REVIEW

**Comment by jdm** [comment]
`tests/wpt/mozilla/window_performance.html` is now panicking when calling Performance::Timing.

**Comment by jdm** [comment]
More specifically, the panic occurs because in [this code](https://github.com/servo/servo/blob/c57e9bb93834aedf9a22bebc45589b3d622b9e98/components/script/dom/performance.rs#L365-L372) there is no navigation timing entry that has been reported when a page like this is loaded:
```html
<script>
console.log(navigation.timing)
</script>
```
This occurs because we only register performance entries when a response is complete, rather than when the first bytes are received (https://github.com/servo/servo/blob/c57e9bb93834aedf9a22bebc45589b3d622b9e98/components/script/dom/servoparser/mod.rs#L789-L818). I think we need to update all of the resource timing code to submit twice - when the first bytes are received, and then update the existing entry when all of the final timings are available.

We could:
* add a ResourceFetchTiming argument to the Result passed in [process_response](https://github.com/servo/servo/blob/master/components/net_traits/lib.rs#L207)
* call [submit_resource_timing](https://github.com/servo/servo/blob/c57e9bb93834aedf9a22bebc45589b3d622b9e98/components/script/dom/servoparser/mod.rs#L830) after [creating the document parser](https://github.com/servo/servo/blob/c57e9bb93834aedf9a22bebc45589b3d622b9e98/components/script/dom/servoparser/mod.rs#L708)
* make [Performance::queue_entries](https://github.com/servo/servo/blob/c57e9bb93834aedf9a22bebc45589b3d622b9e98/components/script/dom/performance.rs#L222) return the index of the added performance entry in `self.entries`
* add a `update_entry` method to `Performance` that accepts an index and a &PerformanceEntry value and overwrites the corresponding entry in `self.entries`
* call the new `update_entry` API from [process_response_eof](https://github.com/servo/servo/blob/c57e9bb93834aedf9a22bebc45589b3d622b9e98/components/script/dom/servoparser/mod.rs#L818)

**Comment by bcamp** [comment]
Just updating to say that I'm working on an implementation of your proposed solution. Should have an update some time this week.

**Comment by jdm** [comment]
@bcamp Are you still working on this? :)

**Comment by bcamp** [comment]
My bad, this completely slipped my mind as work and school have been consuming my time. I don't think I'll be able to get to this in a timely manner (as already displayed).

**Pull request closed without merging**
