### PR TITLE
make it possible to disable default keybindings

### PR DESCRIPTION
**Pull request by paulrouget**
For browser.html, we want to let the top level webpage handle these keybindings.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8121)

### CODE REVIEW

**Comment by jdm** [comment]
This feels like an inefficient way to go about this to me. Have you tried adding key listeners to browser.html and calling `preventDefault` for the bindings you want Servo to ignore?

**Comment by paulrouget** [comment]
> This feels like an inefficient way to go about this to me. Have you tried adding key listeners to browser.html and calling preventDefault for the bindings you want Servo to ignore?

Aren't DOM events not even created at this point?

Should we propagate the events and later on check if `preventDefault` was called?

Also - is zooming with ctrl-scroll really a thing we need?

**Comment by jdm** [comment]
We prevent backspace from navigating the page when a text input is focused on a page; all key events are first sent to the focused script task, processed, and if they're not prevented they're returned to the compositor for further processing. I would be ok with removing zooming via the mousewheel if it makes your life easier.

**Comment by paulrouget** [comment]
> We prevent backspace from navigating the page when a text input is focused on a page; all key events are first sent to the focused script task, processed, and if they're not prevented they're returned to the compositor for further processing

I see. What about escape?

**Comment by paulrouget** [comment]
If we can `preventDefault()` the quit-on-escape-key behavior and remove the ctrl-scroll binding, that would be enough for me.

I'll look at how to do that.

**Comment by jdm** [comment]
That would require updating http://mxr.mozilla.org/servo/source/ports/glutin/window.rs#173 to match the others, and ensuring that `handle_key` has a way to indicate that the app should exit.

**Pull request merged**
