### PR TITLE
Use image metadata to lay out images

### LINKED ISSUE #7047: Use image metadata to lay out images before the complete image data is available
The [immeta library](https://github.com/netvl/immeta.git) can provide metadata about an image given a buffer. We should use this to retrieve the dimensions of an image as soon as possible while the image is downloading.

### PR DESCRIPTION
**Pull request by jmr0**
Fixes #7047.

cc: @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9208)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Code reviewed, it looks pretty sweet. Only one niggle, which is that metadata width/height are being kept as u32, in px. Is there a sensible way of tracking units for metadata?

---

Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/msg/constellation_msg.rs, line 334 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9208#-K8yQR9V-tcdI6B6jddr:-K8yQR9V-tcdI6B6jdds:-1392161651) ([raw file](https://github.com/servo/servo/blob/e4215952c201592076b13a3b1c960e3307344bb6/components/msg/constellation_msg.rs#L334)):*
Should image metadata width/height be kept in a type that specifies units?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9208#-:-K8yTYP-JTDAwmqEe1eY:-769993296)*

**Comment by jmr0** [comment]
Great to hear! Are you thinking of something like a Pixel type to abstract the u32 choice? In that case it might be worthwhile changing Image's width/height from u32 as well

**Comment by asajeffrey** [comment]
On reflection, that issue is orthogonal to your PR, so I think we are good to go.

@jdm: Can you delegate review privilege to me?

**Comment by jdm** [comment]
Ah, looks like this requires running `./mach cargo-update -p immeta` to ensure that all of the Cargo.lock files in the tree are properly updated with the new package.

**Comment by jmr0** [comment]
Gave that a try and ended up bumping components/servo but got this message for the other packages:

    components/servo
        Updating registry `https://github.com/rust-lang/crates.io-index`
        Updating immeta v0.2.3 -> v0.2.4
          Adding libc v0.1.12
    ports/cef
    package id specification `immeta` matched no packages
    ports/geckolib
    package id specification `immeta` matched no packages
    ports/gonk
    package id specification `immeta` matched no packages

Not sure that's any better

**Comment by Ms2ger** [comment]
Try some other crate, say `./mach cargo-update -p js`

**Comment by asajeffrey** [comment]
Over in irc, @larsbergstrom and @jdm suggested `GONKDIR=/tmp ./mach build-gonk` to rebuild the `Cargo.lock` file.

**Comment by jmr0** [comment]
Tried @Ms2ger's suggestion and was able to rebuild Cargo.lock files for immeta after that -- much appreciated!

**Comment by jdm** [comment]
@bors-servo: retry
* #9063

**Comment by jdm** [comment]
@bors-servo: retry
* #8815

**Pull request merged**
