### PR TITLE
Move websocket creation to resource task

### PR DESCRIPTION
**Pull request by nfallen**
This is a pull request for part of https://github.com/servo/servo/issues/6638

It includes the following changes:
-The websocket networking code (ie. making a connection, receiving data, and sending data) has been extracted out of components/script/dom/websocket.rs and into the new file components/net/websocket_loader.rs. 
-websocket.rs now communicates with the resource task (components/net/resource_task.rs) to instruct it to initiate a new websocket connection
- websocket_loader.rs now provides an API sent over an IPCChannel that allows websocket.rs to receive feedback about this process and to subsequently send and receive data

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8867)

### CODE REVIEW

**Comment by jdm** [comment]
This looks really great! There are a couple changes we can make for efficiency, but I'm really happy with how this PR turned out :D
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[components/net/resource_task.rs, line 180 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8867#-K4y2Gqg9WWszQpoG1l0:-K4y2Gqg9WWszQpoG1l1:1480423072) ([raw file](https://github.com/servo/servo/blob/93861c952e70a78ec93c3cebb7993fc99497468d/components/net/resource_task.rs#L180)):*
I'm not clear on what this is asking.

---

*[components/net/resource_task.rs, line 359 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8867#-K4y2OoQpOhJf6gu_VW5:-K4y2OoQpOhJf6gu_VW6:657771371) ([raw file](https://github.com/servo/servo/blob/93861c952e70a78ec93c3cebb7993fc99497468d/components/net/resource_task.rs#L359)):*
No need for `mut` here.

---

*[components/net/websocket_loader.rs, line 45 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8867#-K4y2nopyYEG6E36Qm5m:-K4y2nopyYEG6E36Qm5n:975852244) ([raw file](https://github.com/servo/servo/blob/93861c952e70a78ec93c3cebb7993fc99497468d/components/net/websocket_loader.rs#L45)):*
Let's call this `connect` instead.

---

*[components/net/websocket_loader.rs, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8867#-K4y3CKig0Ly0tskx0ev:-K4y3CKig0Ly0tskx0ew:-990755736) ([raw file](https://github.com/servo/servo/blob/93861c952e70a78ec93c3cebb7993fc99497468d/components/net/websocket_loader.rs#L57)):*
Instead of creating these senders and receivers here and immediately sending them, we could create them in the DOM constructor and send the resource_action_receiver and resource_event_sender values as part of the initial connection request.

---

*[components/net/websocket_loader.rs, line 120 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8867#-K4y5QUBkktbps1CCIXC:-K4y5QUBkktbps1CCIXD:-1092781639) ([raw file](https://github.com/servo/servo/blob/93861c952e70a78ec93c3cebb7993fc99497468d/components/net/websocket_loader.rs#L120)):*
Let's use `while let Ok(dom_action) = resource_action_receiver.recv() {` instead.

---

*[components/script/dom/websocket.rs, line 143 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8867#-K4y5qi6dM8uN3rH7SIm:-K4y5qi6dM8uN3rH7SIn:1069735091) ([raw file](https://github.com/servo/servo/blob/93861c952e70a78ec93c3cebb7993fc99497468d/components/script/dom/websocket.rs#L143)):*
I don't think we need the `Arc<Mutex<` anymore.

---

*[components/script/dom/websocket.rs, line 239 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8867#-K4y6m9n6XIHG1AMLFx6:-K4y6m9n6XIHG1AMLFx7:-320864799) ([raw file](https://github.com/servo/servo/blob/93861c952e70a78ec93c3cebb7993fc99497468d/components/script/dom/websocket.rs#L239)):*
We should be able to store this in self.sender immediatlely, rather than holding on to it for the `ConnectionEstablishedTask` later.

---

*[components/servo/Cargo.lock, line 1159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8867#-K4y7KWV7jXad7zu1xxb:-K4y7KWV7jXad7zu1xxc:-1087589000) ([raw file](https://github.com/servo/servo/blob/93861c952e70a78ec93c3cebb7993fc99497468d/components/servo/Cargo.lock#L1159)):*
We'll need to run `./mach update-cargo -p net` in order to automatically update ports/cef/Cargo.lock and ports/gonk/Cargo.lock with these changes, too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8867#-:-K4y7S3oARgArCgZZWn_:1557193457)*

**Comment by nfallen** [comment]
Made a new commit with the updates so you can see the changes more easily, but I can squash the commits when the PR is ready!

**Comment by jdm** [comment]
One last change required - please squash the commits together while doing so, and I'll merge it :)
-S-awaiting-review +S-needs-code-changes +S-needs-squash 

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/net/websocket_loader.rs, line 45 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8867#-K4y2nopyYEG6E36Qm5m:-K5-4zVceu7Ml__KkgV8:606449838) ([raw file](https://github.com/servo/servo/blob/93861c952e70a78ec93c3cebb7993fc99497468d/components/net/websocket_loader.rs#L45)):*
`connect`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8867#-:-K5-5fUx-8b4VQoYVJLM:-22018180)*

**Pull request merged**
