### PR TITLE
Use reference frames explicitly for fixed positioning

### PR DESCRIPTION
**Pull request by mrobinson**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [x] There are tests for these changes because they should not change behavior.
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20767)

### CODE REVIEW

**Comment by gw3583** [comment]
```
{"status": "FAIL", "group": "default", "message": "assert_equals: expected Element node <html><head><meta charset=\"utf-8\">\n<title>Ensure that the... but got Element node <a id=\"link\" href=\"http://mozilla.org\">This is some link ...", "stack": "@http://web-platform.test:8000/_mozilla/mozilla/scrollBy.html:23:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:548:9\n@http://web-platform.test:8000/_mozilla/mozilla/scrollBy.html:10:5\n", "subtest": "Ensure that the window.scrollBy function affects scroll position as expected", "test": "/_mozilla/mozilla/scrollBy.html", "line": 123654, "action": "test_result", "expected": "PASS"}
```

Not sure if this is an intermittent, but it seems like it's related to the changes in this patch.

**Comment by mrobinson** [comment]
@gw3583 Looks like the issue was that I was assigning nodes to the root reference frame instead of the root scroll node. I've fixed this and made changes to ensure that this mistake is much harder to make. Here is the interdiff for the new version of the branch: https://gist.github.com/mrobinson/ea4879f787faeef0306c0f1202752a65

**Comment by mrobinson** [comment]
@bors-servo try

The bot failure looks like an unrelated network failure.

**Comment by mrobinson** [comment]
The test failure is `/fetch/range/sw.https.window.html`. I'm fairly certain this is not related to my change. @gw3583 Sorry for the delay here, but this should be ready to review.

**Comment by mrobinson** [comment]
@bors-servo retry
 * #20084 
 * #15570

**Comment by mrobinson** [comment]
I don't really see a bug that matches these intermittent WebSocket failures (apart from perhaps #20734, but without the initial error). I'm going to retry this and then open a bug if it does manage to land.

**Pull request merged**
