### PR TITLE
layout: Don't rerun selector matching unless we need to when resizing the window.

### PR DESCRIPTION
**Pull request by pcwalton**
2.1x improvement on resizing on Reddit.

r? @jdm

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5936)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/layout/layout_task.rs @ r1
- components/script/dom/window.rs @ r1
- components/script/script_task.rs @ r1
- components/style/selector_matching.rs @ r1

---

<sup>**[components/script/dom/window.rs, line 575 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5936#-JoVZJOTcEyu-tOfD94B)** ([raw file](https://github.com/servo/servo/blob/2e4d2eb6a9fd135ee19475664a608789880f37b6/components/script/dom/window.rs#L575)):</sup>
Why remove this?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5936)

**Comment by pcwalton** [comment]
Comment addressed. r? @jdm

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 
Squash!

---

Reviewed files:
- components/layout/layout_task.rs @ r2
- components/script/dom/window.rs @ r2
- components/script/script_task.rs @ r2
- components/style/selector_matching.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5936)

**Pull request merged**
