### PR TITLE
Grammatically correct the statement of bluetooth directory

### PR DESCRIPTION
**Pull request by meetmangukiya**
---

- [ ] `./mach build -d` does not report any errors -- *Didn't check because it is doc update*
- [ ] `./mach test-tidy` does not report any errors -- *Didn't check because it is doc update*
- [ ] These changes fix #__ (github issue number if applicable). -- *Didn't care to file a issue, but I can if it is needed*

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because : It is a documentation update

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14090)

### CODE REVIEW

**Comment by meetmangukiya** [comment]
If not relevant, feel free to close it. In that case I'm sorry for the inconvenience :worried:

**Comment by emilio** [comment]
@bors-servo r+

It's fine, thanks for the fixup! :

**Comment by emilio** [comment]
@bors-servo retry

 * https://github.com/servo/servo/issues/12797

**Comment by meetmangukiya** [comment]
Seems like failed again :worried: 
Wonder how could a doc file change makes tests to fail :thinking:

**Comment by jdm** [comment]
@bors-servo: retry
* #13480

**Comment by meetmangukiya** [comment]
This doesn't quite count as contribution, looking forward to contributing more. :)

A got a question, is servo for people into research? Is this a place for students like me (first year IT engineering)?

**Comment by jdm** [comment]
I'm not sure exactly what you're asking, but we are happy to collaborate with anybody interested in contributing code to an experimental web browser.

**Pull request merged**
