### PR TITLE
Remove the script listener thread.

### PR DESCRIPTION
**Pull request by Ms2ger**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy --faster` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

Either:
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because refactoring

Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11410)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r+

<details><summary><i>Previously, highfive wrote…</i></summary>
> warning **Warning** warning
> 
> * These commits modify script code, but no tests are modified. Please consider adding a test!
</details>


---

Reviewed 8 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11410#-:-KIb7XkM_8JUIDIQdxIR:1236647940)*

**Comment by Ms2ger** [comment]
@bors-servo p=1

Blocks #11375

**Pull request merged**
