### PR TITLE
[Issue#5582] Add Desktop Notifications for Long builds.

### PR DESCRIPTION
**Pull request by JayNakrani**
Supported for Linux & Windows platforms.

If it fails to generate the desktop notification, it simply gives a soft warning on the terminal.

This PR is solving Issue #5582.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5664)

### CODE REVIEW

**Comment by jdm** [comment]
Reviewed files:
- python/servo/build_commands.py @ r1

---

<sup>**[python/servo/build_commands.py, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5664#-JmsJIQ4P77aCgMesomk)** ([raw file](https://github.com/servo/servo/blob/40aa2efd0c8d591016e2e901f604c111151cd1ff/python/servo/build_commands.py#L21)):</sup>
Common style is lowercase method names.

---

<sup>**[python/servo/build_commands.py, line 22 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5664#-JmsIuW0w9HZY8HETXn-)** ([raw file](https://github.com/servo/servo/blob/40aa2efd0c8d591016e2e901f604c111151cd1ff/python/servo/build_commands.py#L22)):</sup>
Let's invert this check and early return, so the rest of the function can be unindented one level.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5664)

**Comment by dhananjay92** [comment]
<sup>**[python/servo/build_commands.py, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5664#-JmsJIQ4P77aCgMesomk)** ([raw file](https://github.com/servo/servo/blob/40aa2efd0c8d591016e2e901f604c111151cd1ff/python/servo/build_commands.py#L21)):</sup>
Done. Pushed new commit with these changes.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5664)

**Comment by larsbergstrom** [comment]
Adding a test comment to see if it fixes: https://reviewable.io/reviews/servo/servo/5664

**Comment by dhananjay92** [comment]
@larsbergstrom I didn't get your comment! Are you just testing Reviewable's setup? Or do you want me to change something in the code?!

**Comment by larsbergstrom** [comment]
@dhananjay92 I apologize for the vague comment and for the delay on your review! We are testing a new reviewing infrastructure (reviewable) and for some reason it isn't showing the new commit you added to incorporate the suggestions by @jdm.

Would you mind if I try closing and re-opening this PR? It should hopefully not change anything (though it will generate some additional e-mail).

**Comment by dhananjay92** [comment]
Oh, okay. I thought you might be testing it.
Yeah, sure. Go ahead. I don't mind if you close and Re-open it again! :smile:

**Comment by larsbergstrom** [comment]
@dhananjay92 The folks at Reviewable have tracked it down to an issue with GitHub's servers and are looking into it. I apologize again for the delay in landing this work! If waiting while they investigate starts to bug you, please let us know and I (or @jdm) can finish up the review manually and land it ASAP.

**Comment by dhananjay92** [comment]
@larsbergstrom It's alright. I have no problem in waiting till the issue is resolved. Not like I am in hurry!  I am working on solving Issue #5663. So that'll keep me busy for a while!

**Comment by larsbergstrom** [comment]
@dhananjay92 Can you try rebasing your fix (check out your branch, `git fetch upstream`, `git rebase upstream/master`, `git push -f origin DesktopNotif`)? The Reviewable folks think that if you rebase and force push an update it may get around the particular patch that's causing GitHub to generate a server error. GitHub doesn't have a fix for it yet, unfortunately.

**Comment by dhananjay92** [comment]
@larsbergstrom Done. In my another pull #5696, second commit (which I had pushed after creating PR) did show up on Reviewable. May be looking at it will help.

**Comment by larsbergstrom** [comment]
@dhananjay92 Indeed, after rebase they both show up - thanks!

@jdm should be able to finish the review now :-)

**Comment by jdm** [comment]
Reviewed files:
- python/servo/build_commands.py @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5664)

**Comment by jdm** [comment]
@dhananjay92 Go ahead and squash these commits together :)

**Comment by dhananjay92** [comment]
@jdm Squashed them.

**Comment by jdm** [comment]
I do not believe your "pre" results are actually reflective of a test run without your changes. For example, all of the "PASS expected FAIL" results that mention HTMLMetaElement or meta.name show that your changes are present. Please checkout master, rebuild, and run the tests again for comparison?

**Comment by dhananjay92** [comment]
Builds failed because the code wasn't handling `DBusException`. I changed it to handle all types of  exceptions.

**Pull request merged**
