### PR TITLE
fix 6058: --devtools panics if there is no console actor

### LINKED ISSUE #6058: --devtools panics if there is no console actor
This was mentioned in a comment here https://github.com/servo/servo/issues/5971#issuecomment-102053416. Basically, running servo with the --devtools flag leads to a crash. 

When I run `./mach run http://google.com --devtools` I get: 

```
stack backtrace:

   1:        0x11060620f - sys::backtrace::write::h6990067d88907b48zVr
   2:        0x110609be4 - panicking::on_panic::he976cdbadffd9e1bEVv
   3:        0x1105f56c5 - rt::unwind::begin_unwind_inner::ha519446d83876aa8nDv
   4:        0x1105f5efc - rt::unwind::begin_unwind_fmt::h15c2d4adf8e8ecdatCv
   5:        0x11060949c - rust_begin_unwind
   6:        0x11062e945 - panicking::panic_fmt::haa553fbfab6eff2cNKy
   7:        0x10e80064f - option::Option<T>::expect::h2190493558643449847
   8:        0x10e800528 - collections::hash::map::HashMap<K, V, S>.Index<&'a Q>::index::h11570370938463914438
   9:        0x10e7fad25 - run_server::find_console_actor::h36bbabe37c10d21agJd
  10:        0x10e7edd07 - run_server::handle_network_event::h3503e9b8696ae0364Jd
  11:        0x10e7e0b99 - run_server::h865311e4cea3d37e6yd
  12:        0x10e7dfa33 - start_server::closure.13443
  13:        0x10e7df8dc - task::spawn_named::closure.13437
  14:        0x10e7df805 - boxed::F.FnBox<A>::call_box::h2076594675215285636
  15:        0x10e7aa51b - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h7459643712465505719
  16:        0x10e7a9b7b - thread::Builder::spawn_inner::closure.12797
  17:        0x10e7a9afe - rt::unwind::try::try_fn::__rust_abi::h742564627405228215
  18:        0x10e7a9a99 - rt::unwind::try::try_fn::h742564627405228215
  19:        0x11060b8d8 - rust_try_inner
  20:        0x11060b8c5 - rust_try
  21:        0x10e7a8f5a - rt::unwind::try::h12091752746280580590
  22:        0x10e7a8d04 - thread::Builder::spawn_inner::closure.12690
  23:        0x10e7aa85d - boxed::F.FnBox<A>::call_box::h15314979547732952471
  24:        0x11060856d - sys::thread::Thread::new::thread_start::h5fcf8fe12ec3c274mYu
  25:     0x7fff84fd3267 - _pthread_body
  26:     0x7fff84fd31e4 - _pthread_start
```

So the problem is that HashMap[“any_value”] will panic! if the lookup fails. The bigger problem seems to be that when [`find_console_actor`](https://github.com/servo/servo/blob/master/components/devtools/lib.rs#L275-L283) is initially called, `actor_pipelines` is empty, so any lookup will fail. 

@jdm noted that this is likely a regression from https://github.com/servo/servo/pull/5947

Given that this is related to the issue I am working on, I would be happy to take a crack at fixing this if it is fairly easy.

### PR DESCRIPTION
**Pull request by eleweek**
Fixes #6058

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6189)

### CODE REVIEW

**Comment by metajack** [comment]
@eleweek What happens now? It looks like your patch just does nothing in this case. It's hard to tell if that's the behavior we want, although I agree the panic should be gone.

-S-awaiting-review +S-awaiting-answer 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- components/devtools/lib.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6189)

**Comment by jdm** [comment]
-S-awaiting-answer +S-needs-code-changes 

---

Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[components/devtools/lib.rs, line 254 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6189#-JqkHPvH5OqHzUNJwvRG)** ([raw file](https://github.com/servo/servo/blob/9c532efa6f688c4033dbaee411ca3adaf220550a/components/devtools/lib.rs#L254)):</sup>
```rust
let console_actor_name = match console_actor_name {
    Some(name) => name,
    None => return,
};
```

---

<sup>**[components/devtools/lib.rs, line 290 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6189#-JqkHYKEa_lsbtybUN4n)** ([raw file](https://github.com/servo/servo/blob/9c532efa6f688c4033dbaee411ca3adaf220550a/components/devtools/lib.rs#L290)):</sup>
Same as above.

---

<sup>**[components/devtools/lib.rs, line 314 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6189#-JqkHgVcDaEh1U9h19p6)** ([raw file](https://github.com/servo/servo/blob/9c532efa6f688c4033dbaee411ca3adaf220550a/components/devtools/lib.rs#L314)):</sup>
`if let Some(console_actor_name) = console_actor_name {`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6189)

**Comment by eddyb** [comment]
This merges for me on top of `smupgrade3` but while it fix the startup panic, it still panics when connecting to it. Not sure if the SpiderMonkey upgrade has anything to do with it.

**Comment by jdm** [comment]
Rebased in #6540. Thanks @eleweek!

**Pull request closed without merging**
