### PR TITLE
Fix htmllabelelement click to activate correct element

### PR DESCRIPTION
**Pull request by rebstar6**
Address https://github.com/servo/servo/issues/9928

Pass on label click to the label element's labeled control

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10019)

### CODE REVIEW

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-tests 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/htmllabelelement.rs, line 66 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10019#-KCw9RJH9nDbMh9zC7ke:-KCw9RJH9nDbMh9zC7kf:-1639964968) ([raw file](https://github.com/servo/servo/blob/617224717cfba2556cecb7c4439faacd35a66622/components/script/dom/htmllabelelement.rs#L66)):*
We should use `if let` here instead of `map.

---

*[tests/html/test-htmllabelelement.html, line 1 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10019#-KCw9awxV0o-fGza5Ry0:-KCw9awxV0o-fGza5Ry1:-1830435213) ([raw file](https://github.com/servo/servo/blob/617224717cfba2556cecb7c4439faacd35a66622/tests/html/test-htmllabelelement.html#L1)):*
I would prefer to see this [added](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) as an automated test in `tests/wpt/web-platform-tests/html/semantics/forms/the-label-element/`. We can query if checkboxes and radio buttons are checked, and for the enabled button case we can load it in an iframe and check the iframe's location after the form has been submitted. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10019#-:-KCwABVlI62CEGTcB4NW:2129832587)*

**Comment by Manishearth** [comment]
We can't add it as a regular WPT test in that folder; the activation behavior of a label is unspecced. https://html.spec.whatwg.org/multipage/forms.html#the-label-element:activation-behaviour-2


However, it can go into the `mozilla/` wpt tests just fine.

**Comment by rebstar6** [comment]
Sure, I'll add a test in at tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html

**Comment by rebstar6** [comment]
Test will fail! Can someone verify that my logic is right for 'fifth' and 'seventh'? When I click on the label, if the 1st element is a disabled radio button or submit button, it is still getting selected (even though disabled).

The disabled logic does seem to be working for the disabled checkbox case. Is this a known issue?

**Comment by jdm** [comment]
The logic in the test looks right to me. It would be easier to read if each test created the elements as necessary and added them to the document, rather than creating them all up front.

**Comment by jdm** [comment]
If necessary we could merge these changes with an ini file that contains the expected failing test results, and file a follow up for investigating it. Otherwise you're welcome to dive in and figure out why it's possible to click on disabled radio buttons and submit buttons!

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html, line 7 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10019#-KDUmENnnniURBMTFJe1:-KDUmENnnniURBMTFJe2:1595470465) ([raw file](https://github.com/servo/servo/blob/a382a42d0a7b0743bda1c7d1e7f42b30b8b263cc/tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html#L7)):*
Rather than having all these HTML elements included in the test up front, we should programmatically create them via `document.createElement` and `document.createTextNode`, then use `appendChild` to create the required element hierarchy. There can be a simple `<div id="test"></div>` that hosts the elements, and it can be cleared after each test with `document.querySelector("#test").innerHTML = ''`.

---

*[tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html, line 46 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10019#-KDUmic2JJSgGtGG19RC:-KDUmic3p27qKlkbpUH0:1927776977) ([raw file](https://github.com/servo/servo/blob/a382a42d0a7b0743bda1c7d1e7f42b30b8b263cc/tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html#L46)):*
These functions and variables could be defined inside the tests that make use of them.

---

*[tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html, line 63 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10019#-KDUmuZRuwt_nRyIMxu1:-KDUmuZRuwt_nRyIMxu2:-1308534565) ([raw file](https://github.com/servo/servo/blob/a382a42d0a7b0743bda1c7d1e7f42b30b8b263cc/tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html#L63)):*
nit: let's remove all the tabs from this file.

---

*[tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html, line 157 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10019#-KDUmp_EM7-30DI5JP_j:-KDUmp_EM7-30DI5JP_k:1179116247) ([raw file](https://github.com/servo/servo/blob/a382a42d0a7b0743bda1c7d1e7f42b30b8b263cc/tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html#L157)):*
We should get rid of all these extra newlines.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10019#-:-KDUmwx6291HXE9ol8HH:1458266033)*

**Comment by rebstar6** [comment]
no need to review yet - more changes coming!

**Comment by rebstar6** [comment]
Alright, to update on the failing tests - 
If you look at tests/wpt/web-platform-tests/html/semantics/disabled-elements/, all of these elements (checkboxes, radio buttons, submits, etc) can't be focused on if disabled (thus cant be clicked). If I just run the html from the automated test, I can verify that I can't click directly on any of the disabled elements. However, the click will still flow through if I click on the label associated with that element.

Probably the easiest option is to only run the activation steps from the label if the element is not disabled (just pushed). Not sure if that's the best strategy though. This also doesn't explain why checkboxes werent being clicked, but the others were. tbd.

**Comment by jdm** [comment]
I agree that that's the simplest solution. Looking at the spec, the [synthetic click activation steps](https://html.spec.whatwg.org/multipage/interaction.html#run-synthetic-click-activation-steps) do not include any specific handling for disabled/immutable/etc., but individual `input` element types have text like ["If the element is not mutable, it has no activation behaviour."](https://html.spec.whatwg.org/multipage/forms.html#checkbox-state-(type=checkbox)) which I would expect to take care of the problem we're observing. Since `HTMLInputElement::pre_click_activation` checks `self.mutable()`, I'm still confused why the incorrect behaviour occurs.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/htmllabelelement.rs, line 68 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10019#-KDZpP36_KBo65e3K_Vf:-KDZpP36_KBo65e3K_Vg:1970293909) ([raw file](https://github.com/servo/servo/blob/5be376ce7d1c91593219c1098d0d512e7999ae6c/components/script/dom/htmllabelelement.rs#L68)):*
I'd like to figure out the reason why this change is necessary.

---

*[tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html, line 136 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10019#-KDZphxDOKZnY0lvB3bZ:-KDZphxDOKZnY0lvB3b_:-1553364351) ([raw file](https://github.com/servo/servo/blob/5be376ce7d1c91593219c1098d0d512e7999ae6c/tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html#L136)):*
We can use
```js
async_test(function(t) {
    var loaded = false;
    var iframe = document.getElementById('foo');
    iframe.onload = t.step_func(function() {
        if (!loaded) {
            loaded = true;
            iframe.contentDocument.getElementById('tenth').click();
        } else {
            t.done();
        }
    });
}, "label click should flow down to form");
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10019#-:-KDZqINzPNktOYC2Tgd3:1458266033)*

**Comment by rebstar6** [comment]
A bunch of test changes in the most recent push - still up front creation, though completely different approach, which I think makes the tests themselves clearer. Either way, let me know if you prefer each element created instead in each test.

This should address all comments to this point other than investigating why we are seeing the disabled click issue (which I'll look into in the next few days).

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html, line 38 \[r7\]](https://reviewable.io:443/reviews/servo/servo/10019#-KD__pm1gnA807jLv0U9:-KD__pm1gnA807jLv0UA:-1178610198) ([raw file](https://github.com/servo/servo/blob/6e07dcdf021e1e54b8e08248048616c9a43e1000/tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html#L38)):*
Sorry, this doesn't read like an improvement to me :) The benefit of creating each set of elements inside of each test is that it's easy to tell what's used in a particular test, as well as control accidental state leaks between tests. Another option would be using `div.innerHTML = '<label><input type='checkbox' disabled><input type='checkbox'></label>';` in each test, if that's more palatable.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10019#-:-KD_aN2PizWJxqNn_sFs:1458266033)*

**Comment by rebstar6** [comment]
@jdm hah, bummer, I was kinda digging it. Ok, pushed another version - just look at the 1st 2 tests for 2 different approaches. Option 1 uses all javascript functions within the test itself. Option 2 sets the html in the test itself. Ignore the rest, I will convert them when we pick a favorite format.

I think I'm partial to option 2, fwiw, but didn't want to redo everything and then wind up changing them all again anyway :)

**Comment by jdm** [comment]
I agree, option 2 seems more readable. Thanks!

**Comment by jdm** [comment]
That test is 10x more readable now. Thanks!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html, line 114 \[r9\]](https://reviewable.io:443/reviews/servo/servo/10019#-KDvFOfBfyU_4Ncsq_zL:-KDvFOfBfyU_4Ncsq_zM:-1307452825) ([raw file](https://github.com/servo/servo/blob/8799b468e890946e36a3f0be28595e133471578e/tests/wpt/mozilla/tests/mozilla/htmllabel-activation.html#L114)):*
This can be `disabledSubmit.onclick = assert_unreached("disabled submit should not have been activated");` and no need for the assert_false later.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10019#-:-KDvG4aFBsdGAdQx1jCI:1615712388)*

**Comment by rebstar6** [comment]
Looks like the disabled issue is in this line here:
http://mxr.mozilla.org/servo/source/components/script/dom/htmlinputelement.rs#866

When I click on the label, in all case (disabled or not), the handle_event function is called with a 'click' event type. Radio buttons have this extra condition in there that causes update_checked_state to be called regardless of if the item is disabled (thus that's getting selected).

If I comment this line out, my test passes without the extra logic in htmllabelelement to only run activation if the item is not disabled. Not sure that we can just take it out though - any idea what cases this code is meant to be handling?

**Comment by jdm** [comment]
That code dates back to the original implementation of radio/checkbox controls that I did in 2014. That was before any notion of activation and activatable elements existed in the code, and it looks like that line just (poorl) replicates the behaviour of the relevant branch in `pre_click_activation`. I say take out that `if let` and we'll see what the testsuite thinks of the result. Good detective work!

**Comment by rebstar6** [comment]
Ok fingers crossed!

**Comment by jdm** [comment]
Not sure what homu is still doing, but all tests appear to have passed on the [waterfall](http://build.servo.org/waterfall).

**Comment by jdm** [comment]
Looks great! Could you squash these into two commits - one for the code changes, and one for the new test?
-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10019#-:-KE3RWib4G66Cj7h0h7H:565539048)*

**Comment by rebstar6** [comment]
WOAH. That did not rebase well. Ugh, hold up, lemme see if I can fix it.

**Comment by rebstar6** [comment]
Phew, rebase crisis averted.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks! :dancer:

**Pull request merged**
