### PR TITLE
Cache results of HTMLCollection::create

### PR DESCRIPTION
**Pull request by dzbarsky**
The first commit doesn't actually improve speed, it just caches the HTMLCollection itself.  This matches what other browsers do and although not required by the spec, content may rely on things like 

```
document.getElementsByTagName("table").foo=3
alert(document.getElementsByTagName("table").foo)
```

The second commit caches the actual elements found, until the HTMLCollection becomes dirty.  This is broken because the dirty flag is currently not set anywhere, but it shouldn't be too hard to add some sets to document and call those when nodes are added/removed/modified/etc.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6927)

### CODE REVIEW

**Comment by dzbarsky** [comment]
Dromaeo tests improve from 12 runs/s to 8-9K runs/s. I think LICM will optimize out the whole benchmark though.

**Comment by jdm** [comment]
Really sorry for the extreme delay in reviewing this. It was surprisingly pleasant to do so! We'll definitely need to add the code to dirty collections before this can merge, however.

-S-needs-rebase +S-needs-code-changes 

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[components/script/dom/htmlcollection.rs, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6927#-JyAxE4ylQwzicHzqMMS)** ([raw file](https://github.com/servo/servo/blob/84ff2b86929bd8653d8b6d6c4994664c73a3e5ff/components/script/dom/htmlcollection.rs#L23)):</sup>
nit: move these up with the other dom::bindings::codegen imports.

---

<sup>**[components/script/dom/htmlcollection.rs, line 257 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6927#-JyB--e5-KEvKM48StR-)** ([raw file](https://github.com/servo/servo/blob/3a96ecfae7433223b5a4d1e5f7af773c26e188b0/components/script/dom/htmlcollection.rs#L257)):</sup>
Can we extract this to a helper method we can call from all of these methods instead of duplicating it in each place?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6927)

**Comment by nox** [comment]
Doesn't the first commit means that instantiated collections and their roots will never be collected until Document is?

**Comment by nox** [comment]
I think the first commit should be split in two: one for the caching in Document, the other for the new enum CollectionType.

**Comment by jdm** [comment]
I suppose we could empty the hashmap when a signal to reduce memory usage is received, or give each collection a TTL counter or something.

**Comment by nox** [comment]
@jdm That doesn't work either., the various collections on `Document` are `[SameObject]`, so they shouldn't be recreated.

**Comment by dzbarsky** [comment]
@asajeffrey I never got a chance to finish this up but it sounds like you may be looking into this now

**Comment by asajeffrey** [comment]
@dzbarsky My version of the same thing is https://github.com/asajeffrey/servo/tree/versioned_dom

**Comment by asajeffrey** [comment]
So far I only cached document.getElementsByTagName, but this method now gets a 1000x speedup on Dromaeo dom-query.

**Comment by dzbarsky** [comment]
Cool, thats pretty much the same speed-up I saw. I like the versioning idead! I skimmed your commits very briefly so apologies if I missed it, but how do you handle version number wrap-around? You could fix that by invalidating the caches if you hit the max-value or something.  (And welcome to Servo!)

**Comment by asajeffrey** [comment]
Yes, version number overflow is on my mind. I think we're safe allowing
wrap around, as the only way this could mess is up is if someone created a
collection, then waited a few days before accessing it, and happened to hit
exactly the wrapped version number. This is a rather informal argument
though.

A.

**Comment by dzbarsky** [comment]
Abandoning in favor of versioned_dom

**Pull request closed without merging**
