### PR TITLE
Set user interactions for tasks

### LINKED ISSUE #26026: Can't enter immersive babylon goalie demo: "SecurityError: The operation is insecure."
```
joshmatthews@joshmatthews-fcmd6r servo-master % ./mach run https://servo.org/hl-home/
Babylon.js v4.2.0-alpha.5 - WebGL1
[2020-03-24T20:57:15Z ERROR canvas::canvas_data] Unimplemented canvas2d.fillText. Values received: Goalie Trainer, 512, 496.5, None.
[2020-03-24T20:57:15Z ERROR canvas::canvas_data] Unimplemented canvas2d.fillText. Values received: Easy, 512, 554.25, None.
[2020-03-24T20:57:15Z ERROR canvas::canvas_data] Unimplemented canvas2d.fillText. Values received: Hard, 512, 634.25, None.
SecurityError: The operation is insecure.
The operation is insecure.
```
This is what appears when I click the button to enter immersive mode after loading https://servo.org/hl-home/bbjs/#PPM311#63 on desktop macOS.

### PR DESCRIPTION
**Pull request by paulrouget**
fix #26026 

I need help here. Retrieving the interaction flag from the promise handle crashes.

```rust
let interaction = GetPromiseUserInputEventHandlingState(promise);
```

```
Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }"
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/paul/.cargo/git/checkouts/backtrace-rs-96ebaf1bcb788384/91a0aa4/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/paul/.cargo/git/checkouts/backtrace-rs-96ebaf1bcb788384/91a0aa4/src/backtrace/mod.rs:66
   1: <servo::backtrace::Print as core::fmt::Debug>::fmt
             at ports/glutin/backtrace.rs:49
   2: <&mut W as core::fmt::Write>::write_fmt
   3: std::io::Write::write_fmt
             at /rustc/45ebd5808afd3df7ba842797c0fcd4447ddf30fb/src/libstd/io/mod.rs:1427
   4: servo::backtrace::print
             at ports/glutin/backtrace.rs:17
   5: servo::install_crash_handler::handler
             at ports/glutin/main2.rs:68
   6: <unknown>
   7: _ZN2JS37GetPromiseUserInputEventHandlingStateENS_6HandleIP8JSObjectEE
             at /Users/paul/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/2392ebc/mozjs/js/src/vm/JSObject.h:106
```

### CODE REVIEW

**Comment by jdm** [comment]
There's a null promise object being passed in enqueue_promise_job. I'm doing a debugmozjs build to try to figure out why.

**Comment by jdm** [comment]
@paulrouget Judging by gecko and spidermonkey code, passing a null promise object is a valid state so I pushed a change that avoids the crash. I can successfully start immersive mode in the tennis demo on desktop now.

**Comment by paulrouget** [comment]
@jdm r?

**Pull request merged**
