### PR TITLE
Update euclid to 0.3

### PR DESCRIPTION
**Pull request by Manishearth**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8241)

### CODE REVIEW

**Comment by mbrubeck** [comment]
@bors-servo r+

Note: The extra version of glutin was added because of ecoal95/rust-offscreen-rendering-context#30 but is only used on Windows currently, and I don't think it'll cause any conflicts even there. Long-term, we should move Servo back to upstream glutin...

**Comment by metajack** [comment]
The other question I had was about cocoa on gonk.


---

Reviewed 24 of 24 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[ports/gonk/Cargo.lock, line 215 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8241#-K1jGghIvNXDG9eu52kC)** ([raw file](https://github.com/servo/servo/blob/ce5586f74ad87a62f4a8ee97f60c2d012bae19c4/ports/gonk/Cargo.lock#L215)):</sup>
Why does gonk depend on cocoa??


---

<sup>**[ports/gonk/Cargo.lock, line 674 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8241#-K1jGpfAEWD-EYHLTGrr)** ([raw file](https://github.com/servo/servo/blob/ce5586f74ad87a62f4a8ee97f60c2d012bae19c4/ports/gonk/Cargo.lock#L674)):</sup>
This is a dupe dependency, here and elsewhere where it got added.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8241)

**Comment by Manishearth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[ports/gonk/Cargo.lock, line 215 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8241#-K1jGghIvNXDG9eu52kC)** ([raw file](https://github.com/servo/servo/blob/ce5586f74ad87a62f4a8ee97f60c2d012bae19c4/ports/gonk/Cargo.lock#L215)):</sup>
Because glutin does. Lockfiles aren't concerned with platform deps.


---

<sup>**[ports/gonk/Cargo.lock, line 674 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8241#-K1jGpfAEWD-EYHLTGrr)** ([raw file](https://github.com/servo/servo/blob/ce5586f74ad87a62f4a8ee97f60c2d012bae19c4/ports/gonk/Cargo.lock#L674)):</sup>
This is because of rust-offscreen-rendering-context using the crates dep instead of our fork. As it should.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8241)

**Comment by ecoal95** [comment]
@mbrubeck It should be fixed in https://github.com/ecoal95/rust-offscreen-rendering-context/pull/33.
Sorry about that, I missed it on the review.

**Pull request merged**
