### PR TITLE
harfbuzz-sys update

### PR DESCRIPTION
**Pull request by paulrouget**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18410)

### CODE REVIEW

**Comment by paulrouget** [comment]
@mbrubeck r?

**Comment by paulrouget** [comment]
@bors-servo retry

* #18346

**Comment by mbrubeck** [comment]
@bors-servo retry

* infra?

**Comment by mbrubeck** [comment]
These might be actual behavior changes caused by servo/rust-harfbuzz#78:

```
  ▶ PASS [expected FAIL] /css-text-3_dev/html/word-break-break-all-008.htm

  ▶ FAIL [expected PASS] /css-text-3_dev/html/word-break-break-all-007.htm
  └   → /css-text-3_dev/html/word-break-break-all-007.htm 95da652e9d0cdadddf6e9bafaf1731634148d0ad
/css-text-3_dev/html/reference/word-break-break-all-ref-007.htm d192e2ee5ae282f00d2da7baf2995dea2d5ef85d
Testing 95da652e9d0cdadddf6e9bafaf1731634148d0ad == d192e2ee5ae282f00d2da7baf2995dea2d5ef85d

  ▶ FAIL [expected PASS] /css-text-3_dev/html/word-break-normal-bo-000.htm
  └   → /css-text-3_dev/html/word-break-normal-bo-000.htm b1818170ff108bd50214e99c2b4b67a2f4704e9f
/css-text-3_dev/html/reference/word-break-normal-bo-ref-000.htm 1b833a5263158622e7bf32f854f5e5a5f009420d
Testing b1818170ff108bd50214e99c2b4b67a2f4704e9f == 1b833a5263158622e7bf32f854f5e5a5f009420d

  ▶ FAIL [expected PASS] /css-text-3_dev/html/word-break-normal-hi-000.htm
  └   → /css-text-3_dev/html/word-break-normal-hi-000.htm ebe9ce78534f2ffe9f03a450a0963f0ae8b9a933
/css-text-3_dev/html/reference/word-break-normal-hi-ref-000.htm 0f747c946f460cb80065f9e4d5baad2f3ed259da
Testing ebe9ce78534f2ffe9f03a450a0963f0ae8b9a933 == 0f747c946f460cb80065f9e4d5baad2f3ed259da
```

**Comment by mbrubeck** [comment]
`test-css` failed on Mac with a different error:

```
  ▶ FAIL [expected PASS] /css-text-3_dev/html/word-break-normal-bo-000.htm
  └   → /css-text-3_dev/html/word-break-normal-bo-000.htm 5924dfb037ea00360d59ed709909d759eafb1948
/css-text-3_dev/html/reference/word-break-normal-bo-ref-000.htm 2c48ccbe00b5d470da2ad0a5fde778d46ee879e6
Testing 5924dfb037ea00360d59ed709909d759eafb1948 == 2c48ccbe00b5d470da2ad0a5fde778d46ee879e6
```

I think that all these tests were "accidentally passing" before through a combination of lack of fonts and out of date harfbuzz. Feel free to update the test metadata and file a follow-up bug about the failures.

**Comment by paulrouget** [comment]
I cannot reproduce locally. I'm blindly updating the manifest see if it works.

**Comment by paulrouget** [comment]
@mbrubeck any idea what went wrong?

**Comment by paulrouget** [comment]
@bors-servo retry

I can't reproduce the build failures locally.

**Comment by paulrouget** [comment]
@mbrubeck I can't reproduce the failure locally. Do you know if it's failing to compile because of the servo/rust-harfbuzz#79 or servo/rust-harfbuzz#80 ?

**Comment by jdm** [comment]
```
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css-text-3_dev/html/word-break-break-all-007.htm", "line": 13802, "action": "test_result", "expected": "FAIL"}
{"status": "FAIL", "group": "default", "message": "/css-text-3_dev/html/word-break-break-all-008.htm 85d61c419cd6708197e352364dce716dd2ead0a1\n/css-text-3_dev/html/reference/word-break-break-all-ref-008.htm 9ca1d270e6fdcca72951b5e0d2044ee7cb950321\nTesting 85d61c419cd6708197e352364dce716dd2ead0a1 == 9ca1d270e6fdcca72951b5e0d2044ee7cb950321", "stack": null, "subtest": null, "test": "/css-text-3_dev/html/word-break-break-all-008.htm", "line": 13832, "action": "test_result", "expected": "PASS"}
{"status": "PASS", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/css-text-3_dev/html/word-break-normal-hi-000.htm", "line": 13911, "action": "test_result", "expected": "FAIL"}
```

**Comment by mbrubeck** [comment]
That matches the Mac results from last time; it looks like several of these test failures (`all-007`, `all-008`, and `normal-hi-000`) need to be marked platform-specific.

**Comment by paulrouget** [comment]
Ok. Now it's working.

Can someone r+ this?

**Pull request merged**
