### PR TITLE
[Do Not Merge] Make DOM Manipulation events cancellable

### LINKED ISSUE #11703: Intermittent crash in /html/semantics/embedded-content/the-iframe-element/change_parentage.html (Option::unwrap on a None value)
```
▶ CRASH [expected OK] /html/semantics/embedded-content/the-iframe-element/change_parentage.html
  │ 
  │ Xlib:  extension &#34;XFree86-VidModeExtension&#34; missing on display &#34;:0&#34;.
  │ ERROR:constellation::constellation: Panic: called `Option::unwrap()` on a `None` value
  │ ERROR:constellation::constellation: Backtrace:
  │ frame #0  - 0x00007f71d010466d - backtrace::backtrace::trace::hccde8df28b4db2a2
  │ frame #1  - 0x00007f71d01045f5 - backtrace::capture::Backtrace::new::h42f95930bb8c5ee8
  │ frame #2  - 0x00007f71cf15adc9 - _&lt;F as alloc..boxed..FnBox&lt;A&gt;&gt;::call_box::h89adae1a802be550
  │ frame #3  - 0x00007f71d00f5ea8 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::he2b22674ad1748f3
  │ frame #4  - 0x00007f71d03c07cc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
  │ frame #5  - 0x00007f71d03dabd1 - std::panicking::begin_panic::he426e15a3766089a
  │ frame #6  - 0x00007f71d03c203a - std::panicking::begin_panic_fmt::hdddb415186c241e7
  │ frame #7  - 0x00007f71d03dab6e - rust_begin_unwind
  │ frame #8  - 0x00007f71d041116f - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  │ frame #9  - 0x00007f71d0411448 - core::panicking::panic::h907815f47e914305
  │ frame #10 - 0x00007f71cef7cc81 - script::dom::event::Event::new_uninitialized::h05ae188a870e92b9
  │ frame #11 - 0x00007f71cef84b3b - script::dom::event::Event::new::h7a12c706eaf845bc
  │ frame #12 - 0x00007f71cefcb95c - script::dom::eventtarget::EventTarget::fire_event::h0d5b30039f5820d2
  │ frame #13 - 0x00007f71cf1cd7fa - script::task_source::dom_manipulation::DOMManipulationTask::handle_task::h0ea31f97e475cb7a
  │ frame #14 - 0x00007f71cf1652c5 - script::script_thread::ScriptThread::handle_msg_from_script::h47e979ae1e7fb676
  │ frame #15 - 0x00007f71cf1b1d9f - script::script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::hb50cf7fd97943b65
  │ frame #16 - 0x00007f71cf19a0e9 - script::script_thread::ScriptThread::handle_msgs::h1e1abab71191c950
  │ frame #17 - 0x00007f71cf159447 - std::panicking::try::call::h78dcd5319adf08fa
  │ frame #18 - 0x00007f71d03e4dcb - __rust_try
  │ frame #19 - 0x00007f71d03e4d6e - __rust_maybe_catch_panic
  │ frame #20 - 0x00007f71cf15a72d - _&lt;F as alloc..boxed..FnBox&lt;A&gt;&gt;::call_box::hce043844655ea6a9
  │ frame #21 - 0x00007f71d03d8d94 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  │ frame #22 - 0x00007f71cc242181 - start_thread
  │ frame #23 - 0x00007f71cbd5947c - __clone
  │ frame #24 - 0x0000000000000000 - &lt;unknown&gt;
```

### PR DESCRIPTION
**Pull request by cbrewster**
I can't reproduce the intermittent failure on #11703 so I am running some tests using buildbot.
If this does fix the intermittent, this is blocked on #12292.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11703 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12296)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
That test fails for me on master, so it should be unrelated to the changes made here. I feel decently confident that these changes fix #11703; however, I would like to see if I can get a test case for this.

**Comment by ConnorGBrewster** [comment]
After attempting to make a test case, I have found it is very hard to get this specific panic to happen. It seems like it is very timer sensitive.

**Comment by ConnorGBrewster** [comment]
I have not found a way to write a test to reproduce this (although I have found many other panics along the way). Any ideas would be appreciated. The test should somehow fire a DOMManipulation event to a target whose script thread is shut down.

**Comment by KiChjang** [comment]
Looks like the last try run has been killed by the OS.

**Comment by KiChjang** [comment]
Can we reduce the change_parentage test down into a minimal case where the bug before this patch can deterministically happen?

**Comment by ConnorGBrewster** [comment]
@KiChjang I have not been able to do so, I can't even get `change_parentage` to crash locally after 400+ test runs.

**Comment by ConnorGBrewster** [comment]
Closing in favor of #12404 as it makes all tasks cancellable.

**Pull request closed without merging**
