### PR TITLE
Only expose Storage and StorageEvent in window globals.

### LINKED ISSUE #15436: Only expose Storage/StorageEvent in Window
Currently we have `Exposed=(Window,Worker)` in the storage-related webidl files. We should only expose these in the Window global, which will allow us to update the `Constructor` methods to accept a `&Window` argument instead of the generic `&GlobalScope`.

Code: `components/script/dom/webidls/Storage.webidl`, `components/script/dom/webidls/StorageEvent.webidl`, `components/script/dom/storage.rs`, `components/script/dom/storageevent.rs`
Test: remove the interface names from the list in `tests/wpt/mozilla/tests/interfaces.worker.js`, and run `./mach test-wpt /_mozilla/mozilla/interfaces.worker.html --no-pause-after-test`.

### PR DESCRIPTION
**Pull request by kekkyojin**
This patch removes Worker scope from Storage and StorageEvent WebIDL definition. This way it is possible to construct the objects passing Window instead of GlobalScope. It also removes some tests as they would run out of the scope.

It removes Worker from the WebIDL files defining the Storage and StorageEvent interfaces, as they should not be exposed in that scope.

In Rust source code, this patch replaces "GlobalScope" with "Window" on the contructors. It also modifies constructor calling code in order to pass Window instead of the previously used GlobalScope.

There has been removed these interfaces from the Worker tests.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #15436 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15461)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Looks good! Thanks for doing this cleanup!

**Comment by kekkyojin** [comment]
Oh! Yeah. I modified the interface. It seems to me that the Travis generated a new identifier for the interface, as I see in the test failure log.

Is that new identifier the one should be used in MANIFEST.json?

**Comment by jdm** [comment]
Bah, that's an annoying new feature. If you run `./mach manifest-update` and commit the results then it should work.

**Comment by KiChjang** [comment]
Squash!

**Comment by jdm** [comment]
In case you're unfamiliar with squashing, [here is an explanation](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

**Comment by kekkyojin** [comment]
Replaced by PR 15474 as I was unable to squash my local branch. Sorry for the inconveniences.

**Pull request closed without merging**
