### PR TITLE
Fail cleanly instead of panicking for incorrect option arguments

### PR DESCRIPTION
**Pull request by MovingtoMars**
Related #9927

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10221)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+

thanks!

**Comment by Manishearth** [comment]
```
Checking files for tidiness...

./components/util/opts.rs:638: Line is longer than 120 characters

./components/util/opts.rs:643: Line is longer than 120 characters

./components/util/opts.rs:647: Line is longer than 120 characters

./components/util/opts.rs:663: Line is longer than 120 characters

./components/util/opts.rs:670: Line is longer than 120 characters

./components/util/opts.rs:674: Line is longer than 120 characters
```

please fix this and run `./mach test-tidy` before pushing; thanks!

**Comment by MovingtoMars** [comment]
Sorry, just fixed!

**Comment by KiChjang** [comment]
Is this fixed by #10221?

**Pull request merged**
