### PR TITLE
Replace initial about:blank loads

### LINKED ISSUE #14720: Iframes always load with about:blank in history
If the iframe has a `src` attribute, once the website loads in the iframe, the `about:blank` should be replaced in the session history.

https://html.spec.whatwg.org/multipage/embedded-content.html#process-the-iframe-attributes
> Similarly, if the nested browsing context's session history contained only one Document when the process the iframe attributes algorithm was invoked, and that was the about:blank Document created when the nested browsing context was created, then any navigation required of the user agent in that algorithm must be completed with replacement enabled. 

Sample:

iframe.html:
```
<iframe src="https://www.servo.org"></iframe>
```
```
/mach run -d iframe.html
```

Traverse the history backwards using the keyboard shortcut and the iframe will traverse back to `about:blank`.

### PR DESCRIPTION
**Pull request by cbrewster**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach build-geckolib` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #14720 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20579)

### CODE REVIEW

**Comment by cbrewster** [comment]
@asajeffrey I'm going through each of the failures, they seem to be due to other issues. I'll update the test expectations with links to their relevant issues.

**Comment by cbrewster** [comment]
Updated test expectation. New `TIMEOUT`s are due to #20604

**Comment by asajeffrey** [comment]
```
{"status": "FAIL", "group": "default", "message": "assert_equals: Name is first-contentful-paint expected \"first-contentful-paint\" but got \"first-paint\"", "stack": "observer</<@http://web-platform.test:8000/_mozilla/mozilla/paint_timing.html:11:5\nobserver<@http://web-platform.test:8000/_mozilla/mozilla/paint_timing.html:9:3\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1501:20\nTest.prototype.step_func_done/<@http://web-platform.test:8000/resources/testharness.js:1541:17\n", "subtest": "Performance entries observer", "test": "/_mozilla/mozilla/paint_timing.html", "line": 103759, "action": "test_result", "expected": "PASS"}
```

**Comment by asajeffrey** [comment]
IRC conversation with @avadacatavra https://mozilla.logbot.info/servo/20180411#c14594227

**Comment by asajeffrey** [comment]
Oh great, I can't replicate the failure at my end. Let's retry it and see if it's an intermittent failure.

@bors-servo retry

**Comment by asajeffrey** [comment]
Looks like it was intermittent #20625.

**Pull request merged**
