### PR TITLE
Merge code from Draw* and Draw*Instanced methods

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21335)

### CODE REVIEW

**Review by emilio — APPROVED** [review]

**Comment by nox** [comment]
```
{"status": "FAIL", "group": "default", "message": "assert_equals: Expected value for element id is 'box2' expected Element node <div id=\"box2\" class=\"box\"></div> but got Element node <html><head>\n<title>CSSOM View Module test:CaretPosition<...", "stack": "@http://web-platform.test:8000/css/cssom-view/CaretPosition-001.html:32:3\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\ntest@http://web-platform.test:8000/resources/testharness.js:545:9\n@http://web-platform.test:8000/css/cssom-view/CaretPosition-001.html:31:1\n", "subtest": "Element at (400, 100)", "test": "/css/cssom-view/CaretPosition-001.html", "line": 28619, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_equals: expected 0 but got 200", "stack": "steps<.handler@http://web-platform.test:8000/html/browsers/browsing-the-web/scroll-to-fragid/scroll-to-id-top.html:20:7\nrunNextStep/listener<@http://web-platform.test:8000/html/browsers/browsing-the-web/scroll-to-fragid/scroll-to-id-top.html:32:9\nTest.prototype.step@http://web-platform.test:8000/resources/testharness.js:1538:20\nTest.prototype.step_func/<@http://web-platform.test:8000/resources/testharness.js:1562:20\n", "subtest": "Fragment Navigation: TOP is a valid element id, which overrides navigating to top of the document", "test": "/html/browsers/browsing-the-web/scroll-to-fragid/scroll-to-id-top.html", "line": 45266, "action": "test_result", "expected": "PASS"}
```

Pretty sure those are intermittent, but I want to retry before filing the issues.

@bors-servo retry

**Comment by nox** [comment]
> 15:09 &lt;•jdm> I am really worried about how all of our automated tests related to hit testing and scrolling are suddenly having intermittent failures in the past couple days
> 15:10 &lt;•jdm> it started 4 days ago; there's been #21283, #21295, #21312, #21321, and now nox has hit three more in a single PR today

**Pull request merged**
