### PR TITLE
Don’t run tasks on new TC for GitHub push events (for now)

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
@bors p=1

This (or at least the last commit) will help test the new Taskcluster deployment without disrupting CI.

**Comment by nox** [comment]
@bors-servo r+

So declarative.

**Comment by SimonSapin** [comment]
Fixed a trailing slash in the new TC root URL.

@bors-servo r=nox

**Comment by jdm** [comment]
@bors-servo retry
* restarted servo-tc-mac7

**Pull request merged**
