### PR TITLE
Fix PaintContext page_rect due to display list origin

### LINKED ISSUE #11662: box-shadow is not rendered correctly within position: fixed div
```html
<!doctype html>
<html><body>
	<div style="width: 100%; position: fixed; top: 100px; left: 0;">
		<div style="background: lightgrey; height: 40px; box-shadow: 0 0 30px 30px darkblue;"></div>
	</div>
</body></html>
```
sh

### PR DESCRIPTION
**Pull request by splav**
Fix PaintContext page_rect due to non zero display list origin.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #11662 (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11850)

### CODE REVIEW

**Comment by splav** [comment]
Though I'm not sure that the fix is correct - I think it is. The other method that uses page_rect is clear, and it seems that it also requires shifted rect. 
I'm sure there should be tests changes for this, but I'm new, please give me some directions.

**Comment by glennw** [comment]
@splav Thanks for the commit!

I know it's only a one line change but it's been a long time since I looked at this code, so I'm not sure if this is the "right" fix either.

Could you expand a bit on what this fixes and perhaps provide a test case to explain the issue?

**Comment by splav** [comment]
@glennw sorry for long answer - I was out of internet access for a while. 
The original ticket can be a satisfactory test case. Though I'm not sure how to test the clear method.
The thing is PaintContext takes the page_rect argument. It's origin is used in two methods - clear and create_draw_target_for_blur_if_necessary. The error is in the second one (https://github.com/servo/servo/blob/master/components/gfx/paint_context.rs#L1572). It calculates the intersection of tile rect and the box bounding rect, inflates it for correct seemess blur.
It the ticket case the layer origin for fixed positioned box is negative(thanks for blur side inflation, may be it is an error too, can't imagine a good reason for that) and the element's box coordinate system has 0,0 origin.
So the intersecton rect is wrong. The two possible fixes are shift the page_rect(the origin is 0,0 than, that corresponds to page rect coordinate system) or may be shift the static element layer and it's tiles that may have mush more side effects.

**Comment by glennw** [comment]
@splav OK, I think this is a reasonable fix. Before merging, we'll need to add a ref test though - would you be able to convert the test case in the provided bug into a reftest to make sure we don't regress on this?

**Comment by jdm** [comment]
Sorry, the MANIFEST.json is missing a necessary change. Run `./mach update-manifest` to have it added automatically.

**Comment by splav** [comment]
@jdm thanks! Is there any wiki page on adding tests?

**Comment by izgzhen** [comment]
@splav https://github.com/servo/servo/wiki/Testing and https://github.com/servo/servo/blob/master/tests/wpt/README.md might be helpful to you.

**Comment by splav** [comment]
@izgzhen may bad, somehow missed the last part... Thank you.

**Comment by jdm** [comment]
@glennw This PR is waiting on your review.

**Pull request merged**
