### PR TITLE
Implement the table section IDL attributes for HTML tables

### PR DESCRIPTION
**Pull request by dzbarsky**
Rebasing this old PR. Still need to write tests but at least it compiles.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8745)

### CODE REVIEW

**Comment by eefriedman** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/htmltableelement.rs, line 102 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8745#-K4Oo-qNwpe5aivoRZgK:-K4Oo-qOihEcnIhveg51:-1810008164) ([raw file](https://github.com/servo/servo/blob/cd5550807973a18756b21afd542a7423bf56ad62/components/script/dom/htmltableelement.rs#L102)):*
This can legitimately fail: if the table is nested inside the thead, this will throw a HierarchyRequestError.

Not sure if we're supposed to do that check before or after removing the existing thead.

---

*[components/script/dom/htmltableelement.rs, line 116 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8745#-K4OmpQPTnJNcxeyQ6vj:-K4OmpQPTnJNcxeyQ6vk:-1630295347) ([raw file](https://github.com/servo/servo/blob/cd5550807973a18756b21afd542a7423bf56ad62/components/script/dom/htmltableelement.rs#L116)):*
I'm not sure what the recommended way to do Atom->DOMString conversion is at the moment; it's been fluctuating a bit.  @asajeffrey ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8745)*

**Comment by KiChjang** [comment]
What's the status of this?

**Comment by dzbarsky** [comment]
The status is that it needs to address review comments and add tests but I haven't had time to work on it =/ If someone feels a desire to pick this up, I would appreciate it.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8745#-:-K8f5iv3La4c3PQFGrIk:-575390645)*

**Comment by jdm** [comment]
Closed due to lack of updates, and filed #9769 to keep track of this. Thanks @dzbarsky!

**Pull request closed without merging**
