### PR TITLE
Update submodules and don't call setrlimit on Android

### LINKED ISSUE #6432: Startup fails on android: Unable to load native library libmain.so after spidermonkey upgrade
#6150 caused Servo to crash at startup on Android with `java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.native_activity/rust.glutin.MainActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/data/com.example.native_activity/lib/libmain.so`.

dlerror returns `Cannot load library: reloc_library[1331]:  3020 cannot locate '_ZN2js6detail16ScrambleHashCodeEj'`.

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @mbrubeck 

Fixes #6432.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7051)

### CODE REVIEW

**Comment by mbrubeck** [comment]
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7051)

**Comment by metajack** [comment]
@bors-servo p=10

Fast tracking since it is blocking time sensitive work.

**Comment by mbrubeck** [comment]
```
/home/servo/.cargo/git/checkouts/ipc-channel-d95a23d1f1577bfc/master/platform/linux/mod.rs:700:5: 700:20 error: call to unsafe function requires unsafe function or block [E0133]
/home/servo/.cargo/git/checkouts/ipc-channel-d95a23d1f1577bfc/master/platform/linux/mod.rs:700     libc::unlink(c)
                                                                                                   ^~~~~~~~~~~~~~~
```

**Comment by larsbergstrom** [comment]
Oh, poof. I need to get a linux machine to test on when my next h/w upgrade cycle comes. I'll try to get a fix in ipc-channel and find a working VM to test it on and then redo the PR.

**Comment by larsbergstrom** [comment]
re-r? @mbrubeck 

Only change is an updated ipc channel to pick up https://github.com/pcwalton/ipc-channel/pull/5

**Comment by larsbergstrom** [comment]
oh, gah, wait, I need to rebase; bitrotted.

**Comment by larsbergstrom** [comment]
OK, rebased. Note that somebody else picked up the rust-mozjs update already, so all this one needs lockfile-wise now is ipc-channel.

**Pull request merged**
