### PR TITLE
Remove some duplicate dependencies

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23568)

### CODE REVIEW

**Review by asajeffrey — APPROVED** [review]
Yay! Fewer dupes!

**Comment by jdm** [comment]
Rolling the dice: r? @nox

**Comment by atouchet** [comment]
Note: There is similar work done to update rayon in #23630.

**Comment by nox** [comment]
Nice.

@bors-servo r+

**Pull request merged**
