### PR TITLE
De-deplicate is_cors_safelisted_request_header helper functions

### LINKED ISSUE #25235: is_cors_safelisted_request_header is implemented twice, with differences
script/dom/headers.rs has one that takes name:&str and value:&[u8], which is called from the DOM Request constructor only when a request init's mode is explicitly set to no-cors. 

net/fetch/methods.rs has one that takes name:&HeaderName and value:&HeaderValue, which is called routinely as part of the "main fetch" algorithm.

Due to the different data types, unifying them isn't as simple as I'd like it to be, but it's obviously the right thing to do. Neither is currently implementing the full specification logic, possibly due to specification changes since they were written.

### PR DESCRIPTION
**Pull request by pshaughn**
Separate is_cors_safelisted_request_header implementations in script::dom::request and net::fetch::methods have been merged to a single implementation in net_traits::request, with additional logic for spec requirements that weren't previously there. This doesn't pass all the failing tests, but it doesn't fail any passing ones either and it reduces confusion about what's supposed to happen where.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #25235 and some but not all subcases in #25175

- [X] There are tests for these changes, in that the WPT CORS tests that did already pass still do

### CODE REVIEW

**Comment by pshaughn** [comment]
It turns out this did pass a few failing tests I hadn't tried, and after seeing that I looked back at the spec, saw a rule I missed, and made it pass more of them. I think everything else that went wrong in that test run was intermittents of some sort, but I stand to be proven wrong.

**Comment by jdm** [comment]
Yes, there were a bunch of known intermittent failures in the non-cors test results.

**Comment by CYBAI** [comment]
```
Diff in /repo/components/net_traits/request.rs at line 554:
 ) -> bool {
     let name: &str = name.as_ref();
     let value: &[u8] = value.as_ref();
-    if value.len()>128 { return false; }
(B+    if value.len() > 128 {
(B+        return false;
(B+    }
(B     match name {
         "accept" => is_cors_safelisted_request_accept(value),
         "accept-language" | "content-language" => is_cors_safelisted_language(value),
clang-format not installed. Skipping CPP formatting.
Run `./mach fmt` to fix the formatting
```

**Comment by pshaughn** [comment]
Ready to retry; there are still some failing cases but I think I've gotten as far as I can on this without needing changes to how we use the hyper HeaderMap itself.

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Comment by jdm** [comment]
@bors-servo retry
* #24762

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Pull request merged**
