### PR TITLE
(Do not merge) Try to debug rustc ICE

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13832)

### CODE REVIEW

**Comment by asajeffrey** [comment]
@nox: do you have a description of the ICE you're trying to debug?

**Comment by jdm** [comment]
```
   Compiling util_tests v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/util)
   Compiling profile_tests v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/profile)
   Compiling net_traits_tests v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/net_traits)
   Compiling net_tests v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/net)
   Compiling gfx_tests v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/gfx)
   Compiling layout_tests v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/layout)
   Compiling script_tests v0.0.1 (file:///Users/servo/buildbot/slave/mac-dev-unit/build/tests/unit/script)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: bpos.to_usize() >= mbc.pos.to_usize() + mbc.bytes', ../src/libsyntax/codemap.rs:707
stack backtrace:
   1:        0x10eae1d78 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x10eaef60f - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x10eaecabd - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x10eaed156 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x10e560fa4 - std::panicking::begin_panic::hc03e2830c2c89a5f
   6:        0x10e5c2f51 - syntax::codemap::CodeMap::bytepos_to_file_charpos::h3e1ecefe8c872433
   7:        0x10e5bfdf2 - syntax::codemap::CodeMap::lookup_char_pos::hfba960093e9845af
   8:        0x10ab536be - rustc_trans::mir::MirContext::scope_metadata_for_loc::hf4ec7e4a54af690a
   9:        0x10ab534fa - rustc_trans::mir::MirContext::debug_loc::h081d6b2d00268062
  10:        0x10ab578a4 - rustc_trans::mir::block::<impl rustc_trans::mir::MirContext<'bcx, 'tcx>>::trans_block::he67d3259f79e4177
  11:        0x10ab55966 - rustc_trans::mir::trans_mir::h2fb44ecb31cfdffa
  12:        0x10aaf7baa - rustc_trans::base::trans_closure::h941de14309416d66
  13:        0x10ab75c11 - rustc_trans::trans_item::TransItem::define::ha4a18b94a3d46bf3
  14:        0x10aafb10e - rustc_trans::base::trans_crate::h9b06de31ed8799d1
  15:        0x10a9867e1 - rustc_driver::driver::phase_4_translate_to_llvm::hc3883ea2c4750179
  16:        0x10a9bf9d8 - rustc_driver::driver::compile_input::{{closure}}::h9162a2fa292aeb3f
  17:        0x10a9b70b2 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h1928c4704cfe9c61
  18:        0x10a984486 - rustc_driver::driver::phase_3_run_analysis_passes::he578df6b8805151c
  19:        0x10a9722da - rustc_driver::driver::compile_input::h5b63ccd49eeeb98b
  20:        0x10a9991a9 - rustc_driver::run_compiler::h98c7274e7cb1d11d
  21:        0x10a8d7ff8 - std::panicking::try::do_call::h99ed0da044e497c3
  22:        0x10eaefbca - __rust_maybe_catch_panic
  23:        0x10a8f6fff - <F as alloc::boxed::FnBox<A>>::call_box::hbdd5a14cd8e33b97
  24:        0x10eaebd84 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  25:     0x7fff93411059 - _pthread_body
  26:     0x7fff93410fd6 - _pthread_start

Build failed, waiting for other jobs to finish...
error: Could not compile `net_tests`.
```

**Pull request closed without merging**
