### PR TITLE
Add required depenedency for the list on Archlinux

### PR DESCRIPTION
**Pull request by SimonSapin**
https://gist.github.com/awalGarg/67943e11486562132cdd
http://logs.glob.uno/?c=mozilla%23servo#c373354

Would it be feasible to test these lists on CI?

r? @Manishearth

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9765)

### CODE REVIEW

**Comment by Manishearth** [comment]
@bors-servo r+

About CI: no idea, emulating arch seems hard.

**Comment by KiChjang** [comment]
I'm using Arch as well, but I haven't ran into such issues... perhaps I already have the package installed? I'll check when I reboot back into Arch.

**Comment by KiChjang** [comment]
Okay, confirmed that I had glu installed all along, so I might have installed this dependency before building servo.

**Pull request merged**
