### PR TITLE
Added support for using --features argument with --android

### LINKED ISSUE #8173: Support using --features argument with --android in mach
Currently you can't run a command like:
<pre>
./mach build -d --features "energy-profiling" --android
</pre>
Instead we need to run:
<pre>
./mach build -d --features "energy-profiling" --target=arm-linux-androideabi
</pre>
It's not a big deal, but would be a nice addition to support features when specifying android.

### PR DESCRIPTION
**Pull request by nxnfufunezn**
Fixes #8173 
r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8176)

### CODE REVIEW

**Comment by jdm** [comment]
Matt's a fine assignee; just give him time.

**Comment by connorimes** [comment]
I think you should add a `help` parameter to the `CommandArgument` like the others.

**Comment by mbrubeck** [comment]
Looks good! Left one additional comment below.

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[python/servo/build_commands.py, line 159 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8176#-K1_raeVLhszlt1l9hKi)** ([raw file](https://github.com/servo/servo/blob/354e75a447c8afc7757d0340c03119de853110f5/python/servo/build_commands.py#L159)):</sup>
If `features` is None, we should set it to `[]` by default so that code below can append to it.  You can do this like `features = features or []`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8176)

**Comment by eefriedman** [comment]
(FYI, you just deleted the branch; you should be able to reopen the pull request once you fix that.)

**Comment by nxnfufunezn** [comment]
ping @mbrubeck

**Comment by nxnfufunezn** [comment]
ops! changed that !

**Comment by mbrubeck** [comment]
Looks good, thanks!  Please squash these commits together and force-push, and then they can land with r=mbrubeck.

**Comment by nxnfufunezn** [comment]
r=mbrubeck

**Pull request merged**
