### PR TITLE
Add an vector version of the Servo logo

### PR DESCRIPTION
**Pull request by Coder206**
Hello! 

I hope you are doing well! I wanted to contribute a vector image version of the current Servo doge logo and would love to hear your feedback about it. 

Thank you very much. 

cc @larsbergstrom 
cc @jankeromnes
cc @nt1m

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18665)

### CODE REVIEW

**Comment by nt1m** [comment]
:+1:

**Comment by Coder206** [comment]
I simplified the logo by shaping the doge image to fit in the logo of Rust so that only two layers are required.

**Comment by nt1m** [comment]
You might want to run the SVG through SVGO: https://jakearchibald.github.io/svgomg/

**Comment by Coder206** [comment]
@KiChjang I wanted to let you know that I moved this PR to #18695 and that PR was given a new assignee.

**Pull request closed without merging**
