### PR TITLE
Make some callback-related code unsafe

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19864)

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by nox** [comment]
Wtf. Retrying again because queue is empty anyway.

@bors-servo retry

**Comment by Manishearth** [comment]
It's that same infra failure. I got rid of it by re-highstating the server, but I don't think that's enough.

@edunham thoughts?

**Comment by jdm** [comment]
@bors-servo retry
* buildbot became confused

**Pull request merged**
