### PR TITLE
Add some machinery to allow us to disable CSS properties/values per-product

### PR DESCRIPTION
**Pull request by bholley**
Here's an initial stab at solving the issues @SimonSapin brought up in #10408.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10461)

### CODE REVIEW

**Comment by bholley** [comment]
CC @mauricioc

**Comment by bholley** [comment]
CC @heycam 

The explicit tracking of keyword information in the data structure is also intended to allow us to auto-generate conversions from servo to gecko computed values for keyword properties. Still working on a patch for that, but I'm optimistic it'll work.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10461#-:-KEq290c2udXSuAgVijv:1236647940)*

**Pull request merged**
