### PR TITLE
Refactor WebGL implementation to move logic inside the DOM interfaces

### PR DESCRIPTION
**Pull request by emilio**
This improves the encapsulation and consistency in our WebGL
implementation.

Also allows to implement new methods such as `getShaderSource()`.

It will also allow us to use `delete()` in the destructors of them (note
that we will probably want to keep track of them from the context before).

Some concerns:

**Trait method repetition**:
I'm aware that the traits `WebGL{Buffer,Renderbuffer,Framebuffer,Texture}Helpers` are basically the same, but `delete()` and `id()` methods are everywhere. I've thought something like:

``` rust
pub trait WebGLIdentifiable {
    type WebGLId; // id is sometimes i32 (see WebGLUniformLocation)
    fn id(&self) -> Self::WebGLId;
}

pub trait WebGLBindable {
    fn bind(&self);
}

pub trait WebGLDeletable {
    fn delete(&self);
}
```

But I'd want to know your opinion first.

**`renderer` repetition**:
Thought of moving the field: `renderer: Sender<CanvasMsg>` to `WebGLObject`, but I think it makes it way more complicated to read, and also a bit unnecessary, at least IMO (`WebGLObject` will never interact with the field directly). It would also mean that all `WebGLObject`s should have one, which is true at this moment, but maybe not with WebGL 2, for example.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6380)

### CODE REVIEW

**Comment by nox** [comment]
DOM changes are blocked until #6150 lands.

**Comment by Ms2ger** [comment]
Please rebase on master.

**Comment by ecoal95** [comment]
Rebased, also added the `getError` call :P

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

<sup>**[components/canvas_traits/lib.rs, line 133 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYot7LIXu97AqloQ4N)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/canvas_traits/lib.rs#L133)):</sup>
I'm inclined to remove this and use `Option<WebGLError>` wherever necessary.

---

<sup>**[components/script/dom/webglbuffer.rs, line 38 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYlw9MzgG0bz-d165i)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglbuffer.rs#L38)):</sup>
```rust
let result = receiver.recv().unwrap();
result.map(...)
```

---

<sup>**[components/script/dom/webglframebuffer.rs, line 38 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYmO2DqNMAEKslhW8S)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglframebuffer.rs#L38)):</sup>
Same as previous.

---

<sup>**[components/script/dom/webglprogram.rs, line 46 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYmcPIsaSzIUpxZ3sg)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglprogram.rs#L46)):</sup>
Same as previously.

---

<sup>**[components/script/dom/webglprogram.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYmnYYgqrpTPFqbq_6)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglprogram.rs#L90)):</sup>
Differentiate

---

<sup>**[components/script/dom/webglrenderbuffer.rs, line 38 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYoHSzA9mazBrL2CxA)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderbuffer.rs#L38)):</sup>
Same as previously.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 31 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYoQdFg9vtdcJJFLqT)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L31)):</sup>
nit: move this above std::mem.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 36 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYoTchTC21h0un9nhr)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L36)):</sup>
nit: no space before :

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 56 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYp1Sjs1-xlE0e5rR2)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L56)):</sup>
`Option<WebGLError>`

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 235 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYpJZbKWkrV1r6JQk4)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L235)):</sup>
Let's split this out as
```rust
let cmd = CanvasWebGLMsg::BindFramebuffer(target, WebGLFramebufferBindingRequest::Default);
self.renderer.send(CanvasMsg::WebGL(cmd)).unwrap();
```

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 443 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYss92SfJFF6h1cr8_)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L443)):</sup>
`shader.map(|shader| shader.source())`

---

<sup>**[components/script/dom/webglshader.rs, line 24 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtGQu4rfWTP_JCzKV)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L24)):</sup>
Yes, since layout will never be touching this.

---

<sup>**[components/script/dom/webglshader.rs, line 27 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtKWoGFrKpZPOEb34)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L27)):</sup>
Evaluate, maybe?

---

<sup>**[components/script/dom/webglshader.rs, line 49 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtPZTTnA6OIHkNEUp)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L49)):</sup>
Same as previously.

---

<sup>**[components/script/dom/webglshader.rs, line 85 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtY927-q6m1Zw5pX4)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L85)):</sup>
Change it how?

---

<sup>**[components/script/dom/webglshader.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtabx83tOU7Tcvdh5)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L90)):</sup>
tr?

---

<sup>**[components/script/dom/webglshader.rs, line 119 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtkD0JD7hxwlzO7cU)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L119)):</sup>
Is the * necessary?

---

<sup>**[components/script/dom/webgltexture.rs, line 38 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtrivojWTLyUeGiCv)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webgltexture.rs#L38)):</sup>
Same as previously.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6380)

**Comment by ecoal95** [comment]
Review status: 3 of 12 files reviewed at latest revision, 17 unresolved discussions, some commit checks pending.

---

<sup>**[components/canvas_traits/lib.rs, line 133 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYot7LIXu97AqloQ4N)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/canvas_traits/lib.rs#L133)):</sup>
Done.

---

<sup>**[components/script/dom/webglframebuffer.rs, line 38 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYmO2DqNMAEKslhW8S)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglframebuffer.rs#L38)):</sup>
Done.

---

<sup>**[components/script/dom/webglprogram.rs, line 46 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYmcPIsaSzIUpxZ3sg)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglprogram.rs#L46)):</sup>
Done.

---

<sup>**[components/script/dom/webglprogram.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYmnYYgqrpTPFqbq_6)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglprogram.rs#L90)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderbuffer.rs, line 38 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYoHSzA9mazBrL2CxA)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderbuffer.rs#L38)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 31 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYoQdFg9vtdcJJFLqT)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L31)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 36 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYoTchTC21h0un9nhr)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L36)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 56 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYp1Sjs1-xlE0e5rR2)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L56)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 235 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYpJZbKWkrV1r6JQk4)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L235)):</sup>
Done.

---

<sup>**[components/script/dom/webglrenderingcontext.rs, line 443 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYss92SfJFF6h1cr8_)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglrenderingcontext.rs#L443)):</sup>
We can't do that, that would return an `Option<Option<DOMString>>`.

---

<sup>**[components/script/dom/webglshader.rs, line 24 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtGQu4rfWTP_JCzKV)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L24)):</sup>
Done.

---

<sup>**[components/script/dom/webglshader.rs, line 27 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtKWoGFrKpZPOEb34)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L27)):</sup>
Done.

---

<sup>**[components/script/dom/webglshader.rs, line 49 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtPZTTnA6OIHkNEUp)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L49)):</sup>
Done.

---

<sup>**[components/script/dom/webglshader.rs, line 85 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtY927-q6m1Zw5pX4)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L85)):</sup>
This was before implementing `getError`.  At that point I thought that the `getError` call would need to interact with gl, which was false.

Removed

---

<sup>**[components/script/dom/webglshader.rs, line 90 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtabx83tOU7Tcvdh5)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L90)):</sup>
Wrong, good catch :P

---

<sup>**[components/script/dom/webglshader.rs, line 119 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtkD0JD7hxwlzO7cU)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webglshader.rs#L119)):</sup>
Nope, you're right :P

---

<sup>**[components/script/dom/webgltexture.rs, line 38 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6380#-JtYtrivojWTLyUeGiCv)** ([raw file](https://github.com/servo/servo/blob/f00f97578db2f8c5eac7ec3057610ceddd47254e/components/script/dom/webgltexture.rs#L38)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6380)

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge -S-needs-rebase 

---

Reviewed 9 of 9 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6380)

**Pull request merged**
