### PR TITLE
Move collapse through margin to the top of block flow

### LINKED ISSUE #12824: A collapse thorugh block flow should have the collapsed margin on its top edge
When a block flow is collapse through (i.e. no content, padding, border so top and bottom margin collapsed), its collapsed margin should appear at the top (block start) edge. But currently servo shows it in the bottom edge. This can be visualized by adding a `position:absolute` color box in the flow.

### PR DESCRIPTION
**Pull request by shinglyu**
Based on the spec, a collapse through box should be put on the top edge of the flow. This fixed ~110 reftests

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12824  (github issue number if applicable).

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13175)

### CODE REVIEW

**Comment by stshine** [comment]
Another bug fix with 100+ tests pass. Congratulations. 
The flex-flexitem-percentage-prescation.htm does not pass on  build server though; you need to remove it.

**Comment by shinglyu** [comment]
Fixed the tidy error I missed.

**Comment by shinglyu** [comment]
Disable the `flex-flexitem-percentage-prescation.htm` again.

**Comment by shinglyu** [comment]
Marking the `run-in-listitem-between-*.html` as FAIL again.

**Comment by shinglyu** [comment]
Hmm, not sure if want to set `if os == "mac": FAIL` or just `FAIL` on all platform, runs OK on my linux.

**Comment by notriddle** [comment]
If it passes on your Linux, and it passes on CI's Linux, then just say `if os == "mac": FAIL`

**Comment by shinglyu** [comment]
I found the linux builder: http://build.servo.org/builders/linux-rel/builds/3036
The two also failed, marking them as FAIL on all platforms.

**Pull request merged**
