### PR TITLE
Implement Element#closest

### LINKED ISSUE #4603: Implement Element#closest.
Blocks #2185.

* Spec: <https://dom.spec.whatwg.org/#dom-element-closest>.
* Code: `components/script/dom/element.rs`.
* Test: `dom/nodes/Element-closest.html`.

### PR DESCRIPTION
**Pull request by jimrhoskins**
fixes #4603
- Add definition to the Element.webidl and implementation to element.rs.
- Create inclusive_ancestors helper in NodeHelpers
- Update test expectations

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/4621)

### CODE REVIEW

**Comment by jimrhoskins** [comment]
There are 6 tests still not passing in `dom/nodes/Element-closest.html`. My guess is that these are selectors that are not correctly handled by the `matches` code currently. I am having trouble finding other tests that exercise these particular selectors outside of the tests for `closest()`. I couldn't find any issues regarding those test either.

**Comment by jdm** [comment]
Yes, it looks to me like the failing tests all involve CSS selectors that Servo does not support right now.

**Comment by jdm** [comment]
I left comments in Critic; there are a couple stylistic nits, but this is a really nicely-written implementation :)

**Comment by jdm** [comment]
Squash and we'll merge this :)

**Comment by jimrhoskins** [comment]
So squashed! thanks for the review!

**Comment by jdm** [comment]
Some more WPT tests that now pass:
```

/dom/interfaces.html
--------------------
PASS expected FAIL Element interface: operation closest(DOMString)
PASS expected FAIL Element interface: element must inherit property "closest" with the proper type (22)
PASS expected FAIL Element interface: calling closest(DOMString) on element with too few arguments must throw TypeError
/html/dom/interfaces.html
-------------------------
PASS expected FAIL Element interface: document.createElement("noscript") must inherit property "closest" with the proper type (22)
PASS expected FAIL Element interface: calling closest(DOMString) on document.createElement("noscript") with too few arguments must throw TypeError
```

**Comment by jimrhoskins** [comment]
Pushed and squashed the updated test expectations for /html/dom/interfaces.html and /dom/interfaces.html

**Comment by jimrhoskins** [comment]
Ran the failing test, it works for me. I'm guessing it was a fluke failure.

**Comment by jdm** [comment]
Yes, that's a known intermittent failure.

**Pull request closed without merging**
