### PR TITLE
Removed references to DOMSettableTokenList

### PR DESCRIPTION
**Pull request by kevgs**
PR to #11578

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11606)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

Thanks for your contribution!

<details><summary><i>Previously, highfive wrote…</i></summary>
> Heads up! This PR modifies the following files:
>  * @kichjang: components/script/dom/webidls/HTMLElement.webidl, components/script/dom/webidls/HTMLTableCellElement.webidl, components/script/dom/webidls/HTMLIFrameElement.webidl, components/script/dom/webidls/HTMLAnchorElement.webidl, components/script/dom/webidls/HTMLLinkElement.webidl, components/script/dom/webidls/HTMLAreaElement.webidl, components/script/dom/webidls/HTMLOutputElement.webidl
</details>


---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/servo/servo/11606#-KJPugsXLSQIPJs2HaGm:-KJPugsXLSQIPJs2HaGn:-1267753256) (no related file):*
The two tests of which you modified the expectations should be changed accordingly too.

* tests/wpt/web-platform-tests/dom/interface-objects.html
* tests/wpt/web-platform-tests/dom/interfaces.html

---

*[components/script/dom/webidls/HTMLAnchorElement.webidl, line 17 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11606#-KJPtZh7hoDlTx3CC07D:-KJPtZh7hoDlTx3CC07E:1419269076) ([raw file](https://github.com/servo/servo/blob/6581e3504a60aa1e7c363cc93b1036b4a174c166/components/script/dom/webidls/HTMLAnchorElement.webidl#L17)):*
> ```WebIDL
>   attribute DOMString target;
>   //         attribute DOMString download;
>   //[PutForwards=value] attribute DOMSettableTokenList ping;
> ```

This should become:

```webidl
attribute USVString ping;
```

---

*[components/script/dom/webidls/HTMLAreaElement.webidl, line 12 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11606#-KJPtd6IUBxnOVA9WlNH:-KJPtd6IUBxnOVA9WlNI:1419269076) ([raw file](https://github.com/servo/servo/blob/6581e3504a60aa1e7c363cc93b1036b4a174c166/components/script/dom/webidls/HTMLAreaElement.webidl#L12)):*
> ```WebIDL
>   //         attribute DOMString target;
>   //         attribute DOMString download;
>   //[PutForwards=value] attribute DOMSettableTokenList ping;
> ```

This should become:

```webidl
attribute USVString ping;
```

---

*[components/script/dom/webidls/HTMLElement.webidl, line 32 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11606#-KJPtwh6hnrby7FH5A4u:-KJPtwh6hnrby7FH5A4v:1615267165) ([raw file](https://github.com/servo/servo/blob/6581e3504a60aa1e7c363cc93b1036b4a174c166/components/script/dom/webidls/HTMLElement.webidl#L32)):*
> ```WebIDL
>   //readonly attribute DOMString accessKeyLabel;
>   //         attribute boolean draggable;
>   //[PutForwards=value] readonly attribute DOMSettableTokenList dropzone;
> ```

This should become:

```webidl
[SameObject, PutForwards=value] readonly attribute DOMTokenList dropzone;
```

---

*[components/script/dom/webidls/HTMLLinkElement.webidl, line 14 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11606#-KJPu7uHzS-Am1SJ_V51:-KJPu7uHzS-Am1SJ_V52:-140689896) ([raw file](https://github.com/servo/servo/blob/6581e3504a60aa1e7c363cc93b1036b4a174c166/components/script/dom/webidls/HTMLLinkElement.webidl#L14)):*
> ```WebIDL
>            attribute DOMString hreflang;
>            attribute DOMString type;
>   //[PutForwards=value] readonly attribute DOMSettableTokenList sizes;
> ```

This should become:

```webidl
[SameObject, PutForwards=value] readonly attribute DOMTokenList sizes;
```

---

*[components/script/dom/webidls/HTMLOutputElement.webidl, line 7 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11606#-KJPuLZbtuQNH1wWRLzZ:-KJPuLZbtuQNH1wWRLz_:1136049353) ([raw file](https://github.com/servo/servo/blob/6581e3504a60aa1e7c363cc93b1036b4a174c166/components/script/dom/webidls/HTMLOutputElement.webidl#L7)):*
> ```WebIDL
> // https://html.spec.whatwg.org/multipage/#htmloutputelement
> interface HTMLOutputElement : HTMLElement {
>   //[PutForwards=value] readonly attribute DOMSettableTokenList htmlFor;
> ```

This should become:

```
[SameObject, PutForwards=value] readonly attribute DOMTokenList htmlFor;
```

---

*[components/script/dom/webidls/HTMLTableCellElement.webidl, line 10 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11606#-KJPuTISzEHGgeI5rBGr:-KJPuTISzEHGgeI5rBGs:362536908) ([raw file](https://github.com/servo/servo/blob/6581e3504a60aa1e7c363cc93b1036b4a174c166/components/script/dom/webidls/HTMLTableCellElement.webidl#L10)):*
> ```WebIDL
>              attribute unsigned long colSpan;
>   //         attribute unsigned long rowSpan;
>   //[PutForwards=value] readonly attribute DOMSettableTokenList headers;
> ```

This should become:

```webidl
attribute DOMString headers;
```

---

*[tests/wpt/web-platform-tests/dom/historical.html, line 21 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11606#-KJPuysda-46mgDMArSE:-KJPuysda-46mgDMArSF:-2007770223) ([raw file](https://github.com/servo/servo/blob/6581e3504a60aa1e7c363cc93b1036b4a174c166/tests/wpt/web-platform-tests/dom/historical.html#L21)):*
> ```HTML
>   "DOMLocator",
>   "DOMObject",
>   "DOMSettableTokenList",
> ```

This should be restored, that's the list of nuked interfaces, and `DOMSettableTokenList` indeed got nuked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11606#-:-KJPv5O-D-VEdrXXS-3q:688548257)*

**Comment by kevgs** [comment]
I need to implement setters and getters for a new fields, right?

**Comment by nox** [comment]
No, just keep the fields commented as they were before, but with the correct type.

**Comment by kevgs** [comment]
If this crash related to OSX I barely can fix it because I have only Ubuntu.

**Comment by nox** [comment]
@bors-servo r+

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :umbrella: The latest upstream changes (presumably #11615) made this pull request unmergeable. Please resolve the merge conflicts.
</details>


---

Reviewed 7 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11606#-:-KJVCVfwX9QDouAZgcTB:1236647940)*

**Pull request merged**
