### PR TITLE
Add a mach command to upgrade wptrunner

### PR DESCRIPTION
**Pull request by wilcus**
https://github.com/servo/servo/issues/7491

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7494)

### CODE REVIEW

**Comment by jdm** [comment]
@wilmoz This looks great, but currently there is no signal to the user if any of the steps fail to execute properly. We should be checking the return value of each step and returning 1, and return 0 if everything worked as expected. This is why I mentioned `git remote add` specifically in the second sentence in #7491.

**Comment by wilmoz** [comment]
@jdm i tried in my shell and the output (error) appeared. i'll make the changes to return 0 or 1

**Comment by Manishearth** [comment]
If `git init` succeeds, perhaps we should be removing the `.git` folder (so that it doesn't get checked in accidentally)?

**Comment by jdm** [comment]
That doesn't appear to be an issue; it doesn't even show up when I run `git status`.

**Comment by jdm** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[python/servo/devenv_commands.py, line 151 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7494#-JyB0GFa8A2pv86x9ldQ)** ([raw file](https://github.com/servo/servo/blob/e657cda3dce5781b4179fd2d50dce4e6ad217e54/python/servo/devenv_commands.py#L151)):</sup>
I would prefer something like
```rust
code = subprocess.call(...)
if code:
    return code
```
And be sure to test what happens if you run this command twice?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7494)

**Comment by wilmoz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[python/servo/devenv_commands.py, line 151 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7494#-JyB0GFa8A2pv86x9ldQ)** ([raw file](https://github.com/servo/servo/blob/e657cda3dce5781b4179fd2d50dce4e6ad217e54/python/servo/devenv_commands.py#L151)):</sup>
Something like this?
```python
code1 = subprocess.call(...)  #first process
code2 = subprocess.call(...)  #second process
...
if (code1 or code2 ...) == 128:
    return 128
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7494)

**Comment by Manishearth** [comment]
Should it be `code !== 0`?

**Comment by jdm** [comment]
I'm specifically interested in returning after each command if it failed, rather than having a general catch-all at the end.

**Comment by wilmoz** [comment]
@jdm except for the case "git remote add"? According to the second sentence of https://github.com/servo/servo/issues/7491

**Comment by jdm** [comment]
Correct. The other option is to remove the `.git` directory at the end, which will allow us to check the `git remote add` like all the other commands.

**Comment by wilmoz** [comment]
@Manishearth in python
```python
if number:
   print ("ok")
```
number need to be different to 0 to print
Or do you try to say something different?

**Comment by Manishearth** [comment]
I'm saying that all error cases are when `call()` returns a nonzero exit status.

**Comment by wilmoz** [comment]
@Manishearth you are right. that was a draft.

**Comment by jdm** [comment]
@bors-servo: r+
Looks good. Thanks for the PR!

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7494)

**Pull request merged**
