### PR TITLE
Refactored image cache task - details below.

### PR DESCRIPTION
**Pull request by glennw**
- Simpler image cache API for clients to use.
- Significantly fewer threads.
  - One thread for image cache task (multiplexes commands, decoder threads and async resource requests).
  - 4 threads for decoder worker tasks.
- Removed ReflowEvent hacks in script and layout tasks.
  - Image elements pass a Trusted<T> to image cache, which is used to dirty nodes via script task. Previous use of Untrusted addresses was unsafe.
  - Image requests such as background-image on layout / paint threads trigger repaint only rather than full reflow.
- Add reflow batching for when multiple images load quickly.
  - Reduces the number of paints loading wikipedia from ~95 to ~35.
- Reasonably simple to add proper prefetch support in a follow up PR.
- Async loaded images always construct Image fragments now, instead of generic.
  - Image fragments support the image not being present.
- Simpler implementation of synchronous image loading for reftests.
- Removed image holder.
- image.onload support.
- image NaturalWidth and NaturalHeight support.
- Updated WPT expectations.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5767)

### CODE REVIEW

**Comment by jdm** [comment]
This is an incredible feature list.

**Comment by larsbergstrom** [comment]
Reviewed files:
- components/compositing/constellation.rs @ r1
- components/gfx/paint_task.rs @ r1
- components/layout/construct.rs @ r1
- components/layout/context.rs @ r1
- components/layout/display_list_builder.rs @ r1
- components/layout/fragment.rs @ r1
- components/layout/layout_task.rs @ r1
- components/layout/wrapper.rs @ r1
- components/layout_traits/lib.rs @ r1
- components/net/image_cache_task.rs @ r1
- components/net_traits/image/holder.rs @ r1
- components/net_traits/image_cache_task.rs @ r1
- components/net_traits/lib.rs @ r1
- components/net_traits/local_image_cache.rs @ r1
- components/servo/lib.rs @ r1
- tests/unit/net/image_cache_task.rs @ r1
- tests/unit/net/mod.rs @ r1

---

<sup>**[components/layout/context.rs, line 165 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5767#-JnOSfPZu88K6TXQKrHw)** ([raw file](https://github.com/servo/servo/blob/5e3525f7b28dbf79410988203b4f7669041d0e0c/components/layout/context.rs#L165)):</sup>
nit: indentation

---

<sup>**[components/layout/context.rs, line 172 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5767#-JnOSmKo84CwBfr9MGiu)** ([raw file](https://github.com/servo/servo/blob/5e3525f7b28dbf79410988203b4f7669041d0e0c/components/layout/context.rs#L172)):</sup>
nit: indentation

---

<sup>**[components/layout/fragment.rs, line 338 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5767#-JnOTxgO_LZBXQ973yAB)** ([raw file](https://github.com/servo/servo/blob/5e3525f7b28dbf79410988203b4f7669041d0e0c/components/layout/fragment.rs#L338)):</sup>
Can you please check with @SimonSapin if this is the correct value? IIRC, images default to 300x300 - http://dev.w3.org/csswg/css2/visudet.html#inline-replaced-width

---

<sup>**[components/layout/fragment.rs, line 352 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5767#-JnOU1u4i6PwRBSuMd9I)** ([raw file](https://github.com/servo/servo/blob/5e3525f7b28dbf79410988203b4f7669041d0e0c/components/layout/fragment.rs#L352)):</sup>
Same as above on default image size.

---

<sup>**[components/layout/layout_task.rs, line 457 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5767#-JnOUFTF5Ul7eYcFMpXD)** ([raw file](https://github.com/servo/servo/blob/5e3525f7b28dbf79410988203b4f7669041d0e0c/components/layout/layout_task.rs#L457)):</sup>
nit: grammar - "early out"?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5767)

**Comment by larsbergstrom** [comment]
@jdm Can you review the DOm bits?

**Comment by jdm** [comment]
Yep!

**Comment by SimonSapin** [comment]
<sup>**[components/layout/fragment.rs, line 338 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5767#-JnOTxgO_LZBXQ973yAB)** ([raw file](https://github.com/servo/servo/blob/5e3525f7b28dbf79410988203b4f7669041d0e0c/components/layout/fragment.rs#L338)):</sup>
I think this method and some related things should be renamed. "Original size" is not a concept that I know of. What’s probably intended is *intrinsic size*: the size of an image by itself independently of the layout of any element where it’s used. Images from "raster" formats like PNG always have an intrinsic size (the number of pixels), but images in general not necessarily. In SVG may or may not have it, or have it in just one dimension, or only have an intrinsic ratio. Gradients never have it.

See http://dev.w3.org/csswg/css-images-3/#sizing-terms for terminology.

300x150 px is the *default object size* for replaced elements like ``, but it’s only used as a last resort when the image have neither an intrinsic size nor a *specified size* (`width` and `height` properties). See the details of the algorithm in http://dev.w3.org/csswg/css-images-3/#default-sizing

(That algorithm is the same as in CSS2, but generalized to various kinds of images: replaced elements, backgrounds, etc.)

So, all of this to say that the 300px default should probably **not** be part of this method, which should probably return an `Option`. But I don’t have all the context of how it’s used.

---

<sup>**[components/layout/fragment.rs, line 352 \[r1\]](https://reviewable.io:443/reviews/servo/servo/5767#-JnOU1u4i6PwRBSuMd9I)** ([raw file](https://github.com/servo/servo/blob/5e3525f7b28dbf79410988203b4f7669041d0e0c/components/layout/fragment.rs#L352)):</sup>
See my comment above.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5767)

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/bindings/trace.rs @ r1
- components/script/dom/canvasrenderingcontext2d.rs @ r1
- components/script/dom/htmlimageelement.rs @ r1
- components/script/dom/htmlobjectelement.rs @ r1
- components/script/dom/webidls/HTMLImageElement.webidl @ r1
- components/script/dom/window.rs @ r1
- components/script/script_task.rs @ r1
- components/script_traits/lib.rs @ r1
- tests/wpt/metadata/html/dom/interfaces.html.ini @ r1
- tests/wpt/metadata/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-auto.html.ini @ r2
- tests/wpt/metadata/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-fixed.html.ini @ r2
- tests/wpt/metadata/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-percentage.html.ini @ r2
- tests/wpt/metadata/html/semantics/embedded-content/the-img-element/relevant-mutations.html.ini @ r1
- tests/wpt/mozilla/meta/mozilla/img_width_height.html.ini @ r3
- tests/wpt/mozilla/tests/mozilla/img_width_height.html @ r3

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5767)

**Comment by glennw** [comment]
@SimonSapin I updated the method to return 300x150 in this case (this path is only hit when the image is not loaded, and doesn't have an intrinsic size yet). Would it be reasonable to leave the terminology as is, and file an issue about it to follow up (it definitely is wrong, as you've mentioned above)? This PR is already large enough and I'd rather avoid more changes if possible.

**Comment by SimonSapin** [comment]
Yeah, no need to block this PR on that, but I don think this is the wrong place for the 300x150 default. Maybe it doesn’t matter until we support SVG, I’m not sure.

**Comment by glennw** [comment]
@SimonSapin Yep, I think you're right. I restored it to the original behaviour, returning 0 for intrinsic size when the image isn't loaded. This also matches the behaviour before this commit, where an image fragment isn't created but a generic fragment of zero size was created.

**Comment by glennw** [comment]
@jdm Is the last commit reasonable? In rare cases the script task exits before handling the destruction of a Trusted<T> and was panicking in reftests intermittently. I changed it to ok() rather than unwrap(), assuming that if the script task is gone, it doesn't really matter. Is that reasonable?

**Comment by jdm** [comment]
We may end up leaking memory, but I don't have any better ideas. I prefer the `let _ = foo` style rather than `.ok()`, though.

**Comment by glennw** [comment]
@jdm Updated the PR to match the style you mentioned. I think that address all of the comments so far.

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/bindings/refcounted.rs @ r7
- tests/wpt/metadata/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-auto.html.ini @ r5
- tests/wpt/metadata/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-fixed.html.ini @ r4
- tests/wpt/metadata/html/rendering/replaced-elements/svg-embedded-sizing/svg-in-img-percentage.html.ini @ r5

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5767)

**Comment by larsbergstrom** [comment]
Reviewed files:
- components/layout/context.rs @ r2
- components/layout/fragment.rs @ r5
- components/layout/layout_task.rs @ r2
- components/net/image_cache_task.rs @ r5
- components/script/dom/bindings/refcounted.rs @ r7

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5767)

**Comment by glennw** [comment]
@larsbergstrom Squashed and rebased.

**Comment by glennw** [comment]
@jdm Is this good to go from your perspective?

**Comment by jdm** [comment]
Yes.

**Pull request merged**
