### PR TITLE
Always use a WebGLVertexArrayObject to handle vertex attribs

### PR DESCRIPTION
**Pull request by nox**
This lets us clean up how buffers are reference-counted.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21307)

### CODE REVIEW

**Comment by nox** [comment]
A next nice step would be to make the `vertex_attribs` field just be a boxed slice where the items themselves use interior mutability.

**Comment by nox** [comment]
@bors-servo retry

`/_mozilla/mozilla/hit_test_multiple_sc.html` seems intermittent.

**Review by emilio — APPROVED** [review]

**Comment by nox** [comment]
https://github.com/servo/servo/pull/10776#discussion_r207181101

@bors-servo r=emilio

**Pull request merged**
