### PR TITLE
Various fixes to make github less error-prone

### PR DESCRIPTION
**Pull request by Manishearth**
r? @Ms2ger

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7719)

### CODE REVIEW

**Comment by Manishearth** [comment]
I run this with the userscript:

```
window.history = {};
CanvasRenderingContext2D.prototype.fillText = function(a,b,c) {alert(a);alert(b);alert(c);}
document.domain="";
dqs = Document.prototype.querySelector;
Document.prototype.querySelector = function(a) {
    alert("doc.qS: "+a);
    if (a == ':target') {
        return null;
    }
    ret = dqs.apply(this, [a]);
    alert("doc.qS over");
    return ret;
}
delete window.WebSocket;
```

WebSocket is broken because we coerce `[]` in its constructor to `""`, which then causes a `SyntaxError`. `querySelector` is broken because we don't support `:target`, though [I'm working on that](https://github.com/servo/rust-selectors/pull/49).

`window.history` isn't easy to fix now since we don't really have the browsing context framework. I haven't yet looked at `document.domain` or `filltext()`.

**Comment by Ms2ger** [comment]
Please squash into logical commits that pass tests for review.

**Comment by Manishearth** [comment]
Done

**Comment by nox** [comment]
Reviewed 1 of 2 files at r2, 8 of 8 files at r3.
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/wpt/metadata/html/semantics/forms/form-control-infrastructure/form.html.ini, line 3 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7719#-JzyiEQT4HTYIrw58FKN)** ([raw file](https://github.com/servo/servo/blob/982e55ac1c157aa0484a34d8cb33c12b7bb7eef3/tests/wpt/metadata/html/semantics/forms/form-control-infrastructure/form.html.ini#L3)):</sup>
Please file a follow-up issue for those that remain.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7719)

**Comment by Ms2ger** [comment]
@bors-servo r+

Do file that issue.

**Pull request merged**
