### PR TITLE
Fix formsubmitter methods for buttons

### LINKED ISSUE #11014: Can't log into Twitter
Not sure why.

### LINKED ISSUE #11015: Can't log into Facebook
Not sure why.

### PR DESCRIPTION
**Pull request by cbrewster**
Fixes #11015
Fixes #11014

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11020)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
I am typing this ins Servo!

**Comment by ConnorGBrewster** [comment]
Test comment from Servo!!

**Comment by jdm** [comment]
@bors-servo: retry
* git

**Pull request merged**
