### PR TITLE
X11 clipboard support

### PR DESCRIPTION
**Pull request by aweinstock314**
Relevant to issue #5376

Depends on pull request https://github.com/servo/rust-xlib/pull/36

Also depends on an external repository https://github.com/aweinstock314/rust-x11-clipboard, should this be moved into servo's github namespace?

### CODE REVIEW

**Comment by jdm** [comment]
```
$ ./mach test-tidy
components/script/textinput.rs:130: trailing whitespace
```

**Comment by jdm** [comment]
Why's the rust-xlib dependency needed in script?

**Comment by pcwalton** [comment]
r-

This is going to prevent sandboxing, since it accesses X from within the script task.

**Comment by jdm** [comment]
Reviewed on Critic!

**Comment by aweinstock314** [comment]
In response to https://critic.hoppipolla.co.uk/showcomment?chain=11501 :

It could be recreated on-demand, but that would involve creating/closing the X11 Display/window each time. I hadn't measured to see if that's a performance issue in practice, it just seemed like the sort of thing that ought to be cached.

**Comment by jdm** [comment]
Two small style nits left, then we'll need to wait on the rust-xlib PR.

**Comment by larsbergstrom** [comment]
Please rebase this PR and then reopen. It has been temporarily closed to avoid generating excessive work for GitHub's servers.

**Pull request closed without merging**
