### PR TITLE
style: Recascade the document instead of using the dirty_on_viewport_size_change bit

### PR DESCRIPTION
**Pull request by emilio**
This allows us to simplify a lot of code.

On top of #18267.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18268)

### CODE REVIEW

**Comment by emilio** [comment]
After this, we should remove `HasViewportPercentage`.

**Comment by emilio** [comment]
@bors-servo retry

 * Infra

**Comment by jdm** [comment]
@bors-servo: retry
* #18228

**Comment by jdm** [comment]
@bors-servo: retry
* ##18228

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 10 of 10 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/18268#-:-Ksi-oiXRAHqEqAOTo_g:bkg9nno)*

**Comment by jdm** [comment]
@bors-servo retry
#18228

**Comment by jdm** [comment]
@bors-servo retry
#18228

**Comment by jdm** [comment]
@bors-servo: retry
* #18228

**Pull request merged**
