### PR TITLE
Use the same build environment and features for CEF, Servo, Gonk, Geckolib

### LINKED ISSUE #11112: Running build-cef after build rebuilds the world yet again
Probably related to the RUST_FLAGS tweaks we do in mach.

### PR DESCRIPTION
**Pull request by mbrubeck**
- Remove unnecessary dependencies and features from top-level Cargo.tomls.  The features for each crate will be computed based on the union of features specified in the dependency graph.  Specifying the same ones again just adds more ways for them to get out of sync.
- Move all cargo build environment variables into CommandBase

Fixes #11112. r? @metajack

(Not included: CI test to make sure #11112 doesn't regress again.)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11122)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

The CommandBase stuff is a really nice cleanup.

<details><summary><i>Previously, highfive wrote…</i></summary>
> warning **Warning** warning
> 
> * These commits modify script code, but no tests are modified. Please consider adding a test!</details>


---

Reviewed 2 of 2 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11122#-:-KHS6pKROnqjK6B1YMxr:-1974747894)*

**Comment by mbrubeck** [comment]
@bors-servo r=metajack

* Fixed a Python error that broke the arm32 build

**Comment by jdm** [comment]
```
main.rs:22:1: 22:27 error: can't find crate for `android_glue` [E0463]
main.rs:22 extern crate android_glue;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mbrubeck** [comment]
@bors-servo r=larsbergstrom p=0

* Fix the android build

**Comment by mbrubeck** [comment]
I notice with this change, build-cef on buildbot is no longer rebuilding the whole dependency graph, but it is still rebuilding the `style` crate and everything that depends on it:

http://build.servo.org/builders/mac-rel-wpt/builds/947/steps/compile_1/logs/stdio

I suspect this is because some file timestamp is causing Cargo to re-run style's build script (maybe a `.pyc` file).  If so, we could fix this by having the build script print an appropriate `cargo:rerun-if-changed` line.

**Comment by metajack** [comment]
Doesn't cargo look at .gitignore? Perhaps we're just missing a gitignore rule?

**Comment by mbrubeck** [comment]
> Doesn't cargo look at .gitignore? Perhaps we're just missing a gitignore rule?

Cargo doesn’t use git to walk crates within the servo repo, because it does’t find the `.git` directory, because it’s not at the same level as any `Cargo.toml` file.  When Cargo workspaces (RFC 1525) are implemented and we start using them I think that will fix this, and things like this will Just Work™.

**Pull request merged**
