### PR TITLE
Treat 'undefined' passed to an optional argument as "missing"

### LINKED ISSUE #8813: Treat 'undefined' passed to an optional argument as "missing"
* [Failing test](https://github.com/servo/servo/blob/master/tests/wpt/metadata/html/dom/documents/dom-tree-accessors/document.title-07.html.ini)
* https://people.mozilla.org/~jorendorff/es6-draft.html#sec-tostring
* https://dom.spec.whatwg.org/#dom-domimplementation-createhtmldocument

Servo:

```
> document.implementation.createHTMLDocument(undefined).title
"undefined"
```

Firefox:

```
> document.implementation.createHTMLDocument(undefined).title
""
```

Chrome:

```
> document.implementation.createHTMLDocument(undefined).title
""
```

Is this a spec issue?

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes #8813

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8849)

### CODE REVIEW

**Comment by KiChjang** [comment]
I'm kind of curious why this only checks for `undefined` against the case where there is no `defaultValue`. Shouldn't it also check whether arguments with a `defaultValue` have an `undefined` passed onto them?

**Comment by KiChjang** [comment]
I've opened #8854 which addresses the same issue but with a differing implementation. Please let me know which one is better!

**Comment by frewsxcv** [comment]
This might get superseded by #8854

**Comment by frewsxcv** [comment]
Closing in favor of #8854

**Pull request closed without merging**
