### PR TITLE
Send storage event

### PR DESCRIPTION
**Pull request by snf**
Addresses #5196

### CODE REVIEW

**Comment by snf** [comment]
I think all the issues are solved now.

**Comment by jdm** [comment]
One slight comment nit left!

**Comment by snf** [comment]
Done!, squash?

**Comment by jdm** [comment]
Yep!

**Comment by snf** [comment]
Done!

**Comment by jdm** [comment]
Can you squash the test changes too?

**Comment by snf** [comment]
Better!

**Pull request merged**
