### PR TITLE
style: Remove -moz-border-*-colors.

### PR DESCRIPTION
**Pull request by emilio**
Bug: 1429723
Reviewed-by: xidorn
MozReview-Commit-ID: 3P6f7rFcDa6

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19833)

### CODE REVIEW

**Comment by CYBAI** [comment]
From `filtered-wpt-errorsummary.log`:
```
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/html/syntax/parsing/html5lib_ruby.html?run_type=uri", "line": 86087, "action": "test_result", "expected": "OK"}
```

From `intermittents.log`:
```
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/_mozilla/css/iframe/hide_after_load.html", "line": 19895, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "/_mozilla/mozilla/simple_scroll_to_fragment.html 2d5103c1d79069b6628ffe931d05456e5b9244b2\n/_mozilla/mozilla/simple_scroll_to_fragment_ref.html 7949e80732fa0f4afdbae3b1cad96ccd75bb04f6\nTesting 2d5103c1d79069b6628ffe931d05456e5b9244b2 == 7949e80732fa0f4afdbae3b1cad96ccd75bb04f6", "stack": null, "subtest": null, "test": "/_mozilla/mozilla/simple_scroll_to_fragment.html", "line": 29588, "action": "test_result", "expected": "PASS"}
{"status": "FAIL", "group": "default", "message": "assert_greater_than_equal: expected a number greater than or equal to 100 but got 99", "stack": "@http://web-platform.test:8000/_mozilla/mozilla/promise.html:64:11\n", "subtest": "Native promise from async callback can be resolved", "test": "/_mozilla/mozilla/promise.html", "line": 104484, "action": "test_result", "expected": "PASS"}
{"status": "CRASH", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/_mozilla/webgl/conformance-1.0.3/conformance/glsl/bugs/long-expressions-should-not-crash.html", "line": 108798, "action": "test_result", "expected": "TIMEOUT"}
{"status": "TIMEOUT", "group": "default", "message": null, "stack": null, "subtest": null, "test": "/_mozilla/webgl/conformance-1.0.3/conformance/glsl/misc/shader-with-non-reserved-words.html", "line": 141699, "action": "test_result", "expected": "OK"}
```

**Comment by jdm** [comment]
That's #13479.

**Comment by jdm** [comment]
@bors-servo retry
#13479.

**Comment by emilio** [comment]
The only non-intermittent failure there (the first), is the "connection reset by peer" one (#13480).

**Pull request merged**
