### PR TITLE
add get_raw_layout_value (HTMLInputElementHelpers)

### LINKED ISSUE #8107: Text cursor appears in wrong position for password inputs
Perhaps it's something about multibyte characters? It usually falls behind the actual character display and doesn't appear to catch up.

### PR DESCRIPTION
**Pull request by fiji-flo**
This resolves #8107
Previously the index of the insetion point for a password input was
calculated using the scrambled string based on the edit point in the
raw string. That could lead to a wrong position of the caret. This
commit changes this behavior to calculate the insertion point using
the raw string.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8265)

### CODE REVIEW

**Comment by eefriedman** [comment]
The current version of this patch implementation implicitly encodes the implementation detail that the number of bullets is equal to the number of Unicode scalar values in the original text.  This might not be true forever: we might decide, for example, that it's better to count grapheme clusters, or Servo might be ported to some platform where password inputs are displayed differently.

Better to do the translation explicitly: instead of exposing the raw value of the input to layout, make get_insertion_point_for_layout translate the insertion point appropriately.  (Also, add comments in both places pointing out the connection.)

**Comment by Ms2ger** [comment]
Maybe we should have a single function that returns `(String, usize)`?

**Comment by fiji-flo** [comment]
@eefriedman thanks for the input. I'm working on the translation in `get_insertion_point_for_layout` I'll keep you posted.

@Ms2ger merging `get_insertion_point_for_layout` and `get_value_for_layout` could be something nice. But since it does not really help fixing this I would consider this another issue.

**Comment by fiji-flo** [comment]
I moved the translation to `get_insertion_point_for_layout` or more precisely to  `get_insertion_point_index_for_layout` which now returns the index rather than a text point.

If this is an ok change I would suggest to also adopt this for text area and replace `get_absolute_insertion_point_for_layout` with `get_absolute_insertion_point_index_for_layout` to be consistent. Otherwise I could change `get_insertion_point_index_for_layout` back to `get_insertion_point_for_layout` and to the additional translation from the insertion point index to the corresponding char index in the scrambled string. As this is an unnecessary conversion right now I chose this simpler approach.

**Comment by eefriedman** [comment]
It's a bit unfortunate that there aren't any tests here.  Granted, it might be a bit tricky to write a reftest...


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/script/dom/htmlinputelement.rs, line 173 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8265#-K2EUYsGxTnQE6El_aot)** ([raw file](https://github.com/servo/servo/blob/c26b80cf4fce09755d3b97b982d4a1125e1c6c1d/components/script/dom/htmlinputelement.rs#L173)):</sup>
Complete sentence: start with capital letter, end with period.


---

<sup>**[components/script/dom/htmlinputelement.rs, line 197 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8265#-K2EUco3ONBrDK7UjtV6)** ([raw file](https://github.com/servo/servo/blob/c26b80cf4fce09755d3b97b982d4a1125e1c6c1d/components/script/dom/htmlinputelement.rs#L197)):</sup>
Complete sentence.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8265)

**Comment by fiji-flo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/script/dom/htmlinputelement.rs, line 173 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8265#-K2EUYsGxTnQE6El_aot)** ([raw file](https://github.com/servo/servo/blob/c26b80cf4fce09755d3b97b982d4a1125e1c6c1d/components/script/dom/htmlinputelement.rs#L173)):</sup>
My bad. Old habit.


---

<sup>**[components/script/dom/htmlinputelement.rs, line 197 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8265#-K2EUco3ONBrDK7UjtV6)** ([raw file](https://github.com/servo/servo/blob/c26b80cf4fce09755d3b97b982d4a1125e1c6c1d/components/script/dom/htmlinputelement.rs#L197)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8265)

**Comment by fiji-flo** [comment]
Sorry for the split comment, I'm new to reviewable. I can look into writing a ref test, but it will take some time. I can also do it in a follow up issue.

**Comment by eefriedman** [comment]
@bors-servo r+

Per discussion on IRC, reftesting this is going to be difficult at best because the insertion point isn't exposed to script.

**Pull request merged**
