### PR TITLE
Upload buildbot perf data to S3.

### PR DESCRIPTION
**Pull request by asajeffrey**
Upload performance data to S3.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because this is test infrastructure

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19450)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Depends on https://github.com/servo/saltfs/pull/760

**Comment by asajeffrey** [comment]
We'd talked about putting this into `./mach upload-nightly`, but the problem is that `boto3` doesn't support the equivalent of `aws s3 sync`.

**Review by jdm — APPROVED** [review]

**Comment by asajeffrey** [comment]
@bors-servo retry

Not sure what caused that test failure,

**Comment by asajeffrey** [comment]
@bors-servo retry
* #19354

**Comment by jdm** [comment]
@bors-servo: retry
* #19496

**Pull request merged**
