### PR TITLE
Use FnvHasher in http_loader::load

### PR DESCRIPTION
**Pull request by nox**
Should help with #11100.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14284)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I doubt it'll help, this code is only used for unit tests now.

**Comment by nox** [comment]
I don't know, the other usage of RNG in there is using Uuid. Removing the default hasher at the very least cannot hurt, right?

**Comment by Ms2ger** [comment]
Are you looking at the first comment of the linked issue? That's from before the current situation.

**Pull request merged**
