### PR TITLE
Support inline sessions (with spatial tracking!)

### LINKED ISSUE #24186: Support inline sessions in WebXR
We currently only support immersive sessions.

This may be easier to do once https://github.com/servo/webxr/issues/30 is solved.

Diorama sessions are currently not supported by the spec, so this may not be that hard to support.

This also includes support for https://immersive-web.github.io/webxr/#dom-xrrenderstate-inlineverticalfieldofview

### PR DESCRIPTION
**Pull request by Manishearth**
This assumes that your WebXR backend can tolerate being spawned multiple times in inline mode. Currently there is only one backend that allows inline mode (headless), and it works there. This can be improved with https://github.com/servo/servo/issues/35499 .

Todo:

 - [ ] Add a default inline device to webxr so that there is always a tracking-free inline session available (followup: https://github.com/servo/servo/issues/35495)
 - [x] WPT update
 - [ ] Make inline with spatial tracking a feature request (followup: https://github.com/servo/servo/issues/24270)

fixes https://github.com/servo/servo/issues/24186

Depends on https://github.com/servo/webxr/pull/100

### CODE REVIEW

**Review by asajeffrey — APPROVED** [review]
LGTM, it can land once the changes to webxr are merged.

**Comment by Manishearth** [comment]
```
1 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected OK] /webaudio/the-audio-api/the-audioworklet-interface/audioworkletnode-construction.https.html
  │ 
  │ 
  │ 
  │ 
  │ [2019-12-06T01:19:39Z ERROR script::dom::bindings::error] Error at https://web-platform.test:8443/resources/testharnessreport.js:4:1 setup is not defined
  │ [2019-12-06T01:19:39Z ERROR script::dom::bindings::error] Error at https://web-platform.test:8443/webaudio/resources/audit.js:27:13 Cannot proceed. testharness.js is not loaded.
  └ [2019-12-06T01:19:39Z ERROR script::dom::bindings::error] Error at https://web-platform.test:8443/webaudio/the-audio-api/the-audioworklet-interface/audioworkletnode-construction.https.html:13:19 Audit is not defined
```

@bors-servo retry

**Comment by Manishearth** [comment]
Hmm, stuff is timing out

**Comment by Manishearth** [comment]
We seem to be hitting timeouts because perform_updates isn't getting called the second time we simulate a device, so the XR main thread isn't getting hit. I'm not sure of this.

**Comment by Manishearth** [comment]
The timeouts were due to a couple things

 - Spec bug https://github.com/immersive-web/webxr/pull/939 , fixed in the last commit here
 - https://github.com/servo/webxr/pull/103 , making us never close XR sessions and making it expensive to run multiple
 - https://github.com/servo/webxr/pull/104 probably wasn't a direct cause of anything but I stumbled across it and we should fix it

Once https://github.com/servo/webxr/pull/104 lands we should be able to land this

**Comment by Manishearth** [comment]
There may be some timeouts on the bounded ref space and feature policy tests (I think that's a debug mode thing, so not sure), but everything else should pass now.

**Comment by jdm** [comment]
```
  ▶ ERROR [expected TIMEOUT] /webxr/xrView_oneframeupdate.https.html
  │   → uncaught exception: unknown (can't convert to string)
  │ 
  │ assert_matrix_approx_equals@https://web-platform.test:8443/webxr/resources/webxr_test_asserts.js:88:5
  └ onFrame@https://web-platform.test:8443/webxr/xrView_oneframeupdate.https.html:53:11
  ▶ TIMEOUT [expected OK] /webxr/xrSession_requestAnimationFrame_timestamp.https.html
  │ 
  │ 
  │ 
  └ 
  ▶ Unexpected subtest result in /webxr/xrSession_requestAnimationFrame_timestamp.https.html:
  │ TIMEOUT [expected FAIL] XRFrame getViewerPose updates on the next frame for non-immersive
  └   → Test timed out
```
On both mac and linux.

**Comment by Manishearth** [comment]
Hmm, can't repro locally on Linux, but might try with a release build.
Probably has to do with the error in the first one.

**Comment by Manishearth** [comment]
The timestamp test is supposed to be broken, but it's not supposed to time out :/

**Comment by Manishearth** [comment]
I could also just fix the timestamp test but I might instead mark it as an expected failure and fix it separately.

**Comment by Manishearth** [comment]
@bors-servo retry

```
7 unexpected results that are NOT known-intermittents:
  â–¶ TIMEOUT [expected PASS] /css/CSS2/linebox/border-padding-bleed-002.xht


  â–¶ TIMEOUT [expected FAIL] /css/CSS2/linebox/anonymous-inline-inherit-001.html


  â–¶ TIMEOUT [expected PASS] /css/CSS2/linebox/fractional-line-height.html


  â–¶ TIMEOUT [expected PASS] /css/CSS2/linebox/border-padding-bleed-001.xht


  â–¶ TIMEOUT [expected PASS] /css/CSS2/csswg-issues/submitted/css2.1/anonymous-boxes-001.xht


  â–¶ TIMEOUT [expected FAIL] /css/CSS2/linebox/baseline-block-with-overflow-001.html


  â–¶ TIMEOUT [expected FAIL] /css/CSS2/linebox/empty-inline-003.xht
  â”‚ 
  â”‚ 
  â”‚ 
  â”” 

```

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by Manishearth** [comment]
@bors-servo retry

```
  ▶ TIMEOUT [expected PASS] /css/CSS2/box-display/insert-inline-in-blocks-middle-002.xht
```

**Comment by Manishearth** [comment]
Probably https://github.com/servo/servo/issues/24762

**Comment by Manishearth** [comment]
@bors-servo retry

```
1 unexpected results that are NOT known-intermittents:
  ▶ TIMEOUT [expected ERROR] /html/browsers/sandboxing/sandbox-allow-scripts.html
  │ 
  │ _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
  │ 
  │ 
  │ 
  │ [2019-12-12T01:07:51Z ERROR script::dom::bindings::error] Error at :0:0 SecurityError: The operation is insecure.
  └ [2019-12-12T01:07:51Z ERROR script::dom::bindings::error] Error at :0:0 uncaught exception: unknown (can't convert to string)
```

**Comment by Manishearth** [comment]
@bors-servo retry

network hiccup?

**Pull request merged**
