### PR TITLE
Parse -moz-alt-content as a whole content value (fixes #15726)

### LINKED ISSUE #15726: -moz-alt-content parsing is wrong
It's only allowed as a single value for the `content` property, like `none`.  This is causing stylo test failures on layout/style/test/test_property_syntax_errors.html:

TEST-UNEXPECTED-FAIL | layout/style/test/test_property_syntax_errors.html | invalid value '-moz-alt-content 'foo'' not accepted for 'content' property - got "-moz-alt-content \"foo\"", expected ""

etc.

@SimonSapin

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16947)

### CODE REVIEW

**Comment by nox** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=06eff3bfa78e72d64de4470a4edc4cf39c816235

**Comment by Wafflespeanut** [comment]
Nice! @bors-servo r+

**Comment by wafflespeanut** [comment]
Bitrotted by #16967

**Comment by nox** [comment]
@bors-servo retry

```
hdiutil: create failed - error -5341
```

**Pull request merged**
