### PR TITLE
New html page for testing DOM binding performance #5760

### PR DESCRIPTION
**Pull request by mskrzypkows**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6146)

### CODE REVIEW

**Comment by jdm** [comment]
Great start! I'd be interested in the timings you see for both debug and release builds after making these changes!
-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 1 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[tests/html/test_dom_performance.html, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr3JSyfSx-37fSTuRq)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L23)):</sup>
Let's add another test here that calls label.nodeType, which will let us compare the speed of returning a string vs. a number.

---

<sup>**[tests/html/test_dom_performance.html, line 36 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr2mLZxt2WXjqraeRo)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L36)):</sup>
This should be calling something like window.alert instead.

---

<sup>**[tests/html/test_dom_performance.html, line 43 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr3TNyUiOMVIBcaaO5)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L43)):</sup>
This should be calling something like document.adoptNode(label);

---

<sup>**[tests/html/test_dom_performance.html, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr2Rk1nHsTXlC-gNYt)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L57)):</sup>
Let's use Date.now() for these instead.

---

<sup>**[tests/html/test_dom_performance.html, line 59 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr2WtZYw6BLKfb5D9H)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L59)):</sup>
I suspect we'll want to convert these into nanoseconds rather than milliseconds.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6146)

**Comment by saneyuki** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/html/test_dom_performance.html, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr2Rk1nHsTXlC-gNYt)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L57)):</sup>
For benchmarking, I think `window.performance.now()` is more better.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6146)

**Comment by mskrzypkows** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/html/test_dom_performance.html, line 36 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr2mLZxt2WXjqraeRo)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L36)):</sup>
Maybe window.blur() would be better because alert will open new window.

---

<sup>**[tests/html/test_dom_performance.html, line 57 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr2Rk1nHsTXlC-gNYt)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L57)):</sup>
As I see, servo's  ```performance.now()``` gives wrong value, not in milliseconds as is mentioned in: https://developer.mozilla.org/en-US/docs/Web/API/Performance/now so I'll use ```Date.now()```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6146)

**Comment by jdm** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/html/test_dom_performance.html, line 31 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr2mLZxt2WXjqraeRo)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L31)):</sup>
That's fair; using HTMLElement.blur will allow us to compare against other engines too (Servo doesn't implement window.blur() yet). Just use `var label = document.getElementById("lb");` outside of the loop and `label.blur()` each iteration.

---

<sup>**[tests/html/test_dom_performance.html, line 55 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr2Rk1nHsTXlC-gNYt)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L55)):</sup>
Actually, just use performance.now() and I'll make sure that we merge #5697 ASAP.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6146)

**Comment by mskrzypkows** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/html/test_dom_performance.html, line 55 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6146#-Jpr2Rk1nHsTXlC-gNYt)** ([raw file](https://github.com/servo/servo/blob/0f4b6146f4139d9ed56b0f8dbf50839557926544/tests/html/test_dom_performance.html#L55)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6146)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 
Great! Go ahead and squash these commits!

---

Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6146)

**Pull request merged**
