### PR TITLE
first pass at implementing duplicate check

### LINKED ISSUE #12283: Check for duplicates and sorting in prefs.json/package-prefs.json
Follow-up from #12205.

We should add code to tidy (`python/tidy/servo_tidy/tidy.py`) that checks if a JSON object a) has no duplicate keys and b) has its keys in sorted order. Both can be achieved with Python's `json` module, using a [custom `object_pairs_hook`](https://docs.python.org/2/library/json.html#repeated-names-within-an-object) since out of the box Python is more lenient than the RFC and allows duplicates. We should apply this to both the `resources/prefs.json` and `resources/package-prefs.json` files.

Another piece of this might include checking for duplicates at runtime in the Rust prefs parser (`pub fn read_prefs_from_file` in `components/utils/prefs.rs`), but that can also be done separately. This would warrant an extra Rust test for this behavior.

### PR DESCRIPTION
**Pull request by santagada**
This is a work in progress trying to implement duplication checks in rust.

My main question for help is what should the Result<,> second parameter be? Should I create a struct that has the Error trait that nows how to print the name of the duplicated line?

Any other comments are nice and also some tests. Please don't be too harsh as this is one of my firsts pieces of rust code.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #12283 (github issue number if applicable).

- [x] There are tests for these changes OR

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13270)

### CODE REVIEW

**Comment by santagada** [comment]
@aneeshusa you had thoughts on the original PR implementing this, I tried to address all your comments but maybe I did all wrong so please take a look.

**Comment by SimonSapin** [comment]
#12283 talks about doing this in `tidy.py`, not in Rust code.

r? @aneeshusa

**Comment by santagada** [comment]
ping

**Comment by jdm** [comment]
The intention was to do this in tidy.py rather than Rust code. Sorry that there was no explicit review here for so long; I think this was accomplished by #14092.

**Comment by Wafflespeanut** [comment]
ehm, actually, we have the duplication check for quite a while (since #12318). It went unnoticed until now.

**Comment by Wafflespeanut** [comment]
@aneeshusa Did you have something in mind with regards to having duplicate check in Rust during runtime? You'd [mentioned](https://github.com/servo/servo/issues/12283#issuecomment-246115755) this even after #12318 did that in tidy.

**Pull request closed without merging**
