### PR TITLE
Use raqote for canvas 2D rendering

### LINKED ISSUE #23431: Use raqote for 2D canvas rendering
While working on #22957, @jdm mentioned the possiblity to use [https://github.com/jrmuizel/raqote](https://github.com/jrmuizel/raqote) as a canvas rendering backend.
As stated in [https://github.com/servo/servo/issues/22957#issuecomment-493991851](https://github.com/servo/servo/issues/22957#issuecomment-493991851), this issue is for tracking progress of the conversion to raqote.

Remaining missing pieces:
* [x] LinearGradient/RadialGradient (https://docs.rs/raqote/0.6.4/raqote/struct.Gradient.html)
* [x] ColorBurn support (https://github.com/jrmuizel/raqote/issues/81)
* [x] Path::transformed_copy_to_buiilder (https://github.com/jrmuizel/raqote/issues/82)
* [x] Shadows (https://github.com/jrmuizel/raqote/issues/83)
* [x] `snapshot` API (might just be `SourceSurface::Raqote(self.snapshot_data_owned())`
* [x] `ellipse` path API

### PR DESCRIPTION
**Pull request by pylbrecht**
---

- [x] `./mach build -d --features raqote_backend` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #23431

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23601)

### CODE REVIEW

**Comment by pylbrecht** [comment]
I openend this PR to track my progress.

**Comment by pylbrecht** [comment]
I ran into some problems while trying to implement `GenericPathBuilder` for `raqote::PathBuilder`:
Unfortunately I missed the fact that `raqote::PathBuilder`'s methods require a `&mut self` when creating `GenericPathBuilder`. I was just paying attention to azure's code, which is happy with just `&self`.
I feel the solution to this is changing the `GenericPathBuilder` trait (and adapting the implementation for `azure::PathBuilder`, if want to preserve successful builds for both azure and raqote). Is there an easier way to fix this?

**Comment by jdm** [comment]
The other option is using RefCell, which can call borrow_mut to obtain a &mut value.

**Comment by pylbrecht** [comment]
I'm currently facing similar issues implementing `GenericDrawTarget` for `raqote::DrawTarget` as I did while implementing `GenericPathBuilder` for `raqote::PathBuilder`:
Some methods of `raqote::DrawTarget` take a `&mut self`, where `GenericDrawTarget` takes just `&self`.

Changing the interface of `GenericDrawTarget` to take `&mut self` results in many errors in `CanvasData`'s methods, which themselves call methods on the `drawtarget` member.
It's usually in the form of the one below:
```
error[E0502]: cannot borrow `*self.drawtarget` as mutable because it is also borrowed as immutable
   --> components/canvas/canvas_data.rs:663:9
    |
663 |         self.drawtarget.push_clip(&self.path());
    |         ^^^^^^^^^^^^^^^^---------^^----^^^^^^^^
    |         |               |          |
    |         |               |          immutable borrow occurs here
    |         |               immutable borrow later used by call
    |         mutable borrow occurs here

error: aborting due to previous error
```
I fiddled with this for some time now, but I'm not getting anywhere without some help.
How do I get around this ownership issue?

**Comment by jdm** [comment]
```
let path = self.path();
self.drawtarget.push_clio(&path);
```

**Comment by pylbrecht** [comment]
I tried that before and it resulted in the same error:
```
error[E0502]: cannot borrow `*self.drawtarget` as mutable because it is also borrowed as immutable
   --> components/canvas/canvas_data.rs:664:9
    |
663 |         let path = self.path();
    |                    ---- immutable borrow occurs here
664 |         self.drawtarget.push_clip(&path);
    |         ^^^^^^^^^^^^^^^^---------^^^^^^^
    |         |               |
    |         |               immutable borrow later used by call
    |         mutable borrow occurs here

error: aborting due to previous error
```
I feel it may be easier to discuss this on IRC, but I can't say for sure when I'll manage to be there during (your) work hours. Currently my "contribution time" is mostly limited to the weekends.

**Comment by pylbrecht** [comment]
Update: I pushed the latest changes (46caa122b34b87d6c62677860a43880aec9bdb45), which make some of `GenericDrawTarget`'s methods take `&mut self`, so I can implement the trait for raqote (some methods of `raqote::DrawTarget` require `&mut self`).
Unfortunately this results in some ownership issues, which I wasn't able to figure out by myself.

@jdm agreed to help me out by looking over these changes, when he's free, but I guess anyone's opinion is welcome. My Rust skills are still on a beginner level, so these issues might be a no-brainer.

**Comment by jdm** [comment]
@pylbrecht I resolved the remaining errors stemming from the mutability changes, and I dealt with the warning about the raqote GenericPathBuilder implementation recursively calling itself. This required adding a bit of indirection via an Option to support the fact that raqote::PathBuilder::finish consumes the calling object, unlike azure.

**Comment by pylbrecht** [comment]
@jdm, thank you! I'll try to comprehend your changes, so I get an idea of how to approach such errors by myself in the future. Thanks again for your quick response!

**Comment by jdm** [comment]
Closing since #23936 is the most up to date version of this work.

**Pull request closed without merging**
