### PR TITLE
Partial fix for #12415: expose interfaces of some HTML Elements

### PR DESCRIPTION
**Pull request by mskrzypkows**
Fix for interfaces:
HTMLHeadingElement.webidl
HTMLHRElement.webidl
HTMLHtmlElement.webidl
HTMLHyperlinkElementUtils.webidl
HTMLIFrameElement.webidl
HTMLImageElement.webidl
HTMLInputElement.webidl
HTMLLabelElement.webidl
HTMLLegendElement.webidl
HTMLLIElement.webidl

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12415

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12617)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Excellent, thank you!

**Comment by mskrzypkows** [comment]
Should I remove the test? Do my changes really make it pass?

**Comment by jdm** [comment]
It's a test that looks at properties of objects in workers, so it seems reasonable, yes.

**Comment by mskrzypkows** [comment]
unexpected-self-properties.html removed

**Comment by Ms2ger** [comment]
Er, you removed the test itself; only the expectation (`.ini`) file should be removed.

**Comment by mskrzypkows** [comment]
OK, I'll bring it back :-)

**Comment by Ms2ger** [comment]
Thank you kindly

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo: retry
* #12561

**Pull request merged**
