### PR TITLE
Issue #8113: Support file, about and data schemes as form action.

### PR DESCRIPTION
**Pull request by simartin**
Fix https://github.com/servo/servo/issues/8113 by supporting those schemes as form action and unit test the "about:blank" case

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8293)

### CODE REVIEW

**Comment by jdm** [comment]
Great work, especially on figuring out a way to test it :) I've got some suggestions to improve that below.
-S-awaiting-review +S-needs-code-changes 


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[components/script/dom/htmlformelement.rs, line 210 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8293#-K27lbtw9xFiOEqR3hLz)** ([raw file](https://github.com/servo/servo/blob/bb4d33fcdc75be0b283527a4030718e725257f2d/components/script/dom/htmlformelement.rs#L210)):</sup>
Let's do:
```rust
// https://html.spec.whatwg.org/multipage/#submit-get-action
("file", _) | ("about", _) | ("data", FormMethod::FormGet) |
("ftp", _) | ("javascript", _) => (),
```


---

<sup>**[tests/ref/basic.list, line 23 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8293#-K27lwlk6EO9Zk6dBP6U)** ([raw file](https://github.com/servo/servo/blob/bb4d33fcdc75be0b283527a4030718e725257f2d/tests/ref/basic.list#L23)):</sup>
I don't think this test needs to be a reftest. Further suggestions below!


---

<sup>**[tests/ref/form_submit_about.html, line 8 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8293#-K27nTyIdWDijr9-vWWt)** ([raw file](https://github.com/servo/servo/blob/bb4d33fcdc75be0b283527a4030718e725257f2d/tests/ref/form_submit_about.html#L8)):</sup>
I propose a WPT test (`./mach create-wpt tests/wpt/mozilla/tests/mozilla/form_submit_about.html`) which contains an `<iframe>`. The page in the iframe should contain a form that submits itself, targeted at about:blank. The test page can watch the iframe's onload and pass if there are two load events. Does that make sense?


---

<sup>**[tests/ref/form_submit_about_ref.html, line 1 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8293#-K27nRchBeEhKyyXfT6Y)** ([raw file](https://github.com/servo/servo/blob/bb4d33fcdc75be0b283527a4030718e725257f2d/tests/ref/form_submit_about_ref.html#L1)):</sup>
We can remove this file.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8293)

**Comment by simartin** [comment]
<sup>**[tests/ref/form_submit_about.html, line 8 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8293#-K27nTyIdWDijr9-vWWt)** ([raw file](https://github.com/servo/servo/blob/bb4d33fcdc75be0b283527a4030718e725257f2d/tests/ref/form_submit_about.html#L8)):</sup>
It makes perfect sense however I've failed so far unfortunately, and it looks to me like there might be another issue in Servo... Creating a test as you suggested, the iframe's onload is called only once, while it's called twice (as it should be) with Firefox or Chrome...


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8293)

**Comment by simartin** [comment]
Will resolve once the discussion with jdm on testing is complete


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8293)

**Comment by jdm** [comment]
@simartin What is the target of the form that gets submitted? What if you make a blank.html in the same directory and use that as the target? Does the missing onload event occur?

**Comment by simartin** [comment]
In that case the onload event occurs... I guess there's something special with about:blank; I'll try with about:failure, that I understand will load failure.html

**Comment by eefriedman** [comment]
The thing that's special about about:blank is that it's cross-origin... getting the load event to fire correctly depends on getting cross-origin wrappers working.

**Comment by jdm** [comment]
Actually cross-origin iframe load events are part of #6677.

**Comment by simartin** [comment]
@jdm Thanks for the reference. So either we go with the initial way of testing that I proposed and close this ticket (and we move to wpt-testing when #6677 is fixed), or we defer closure until #6677 is closed. What would you suggest as next step?

**Comment by jdm** [comment]
#8558 is ready for review, so I'd like to merge that and then get the test using `about:blank` working.

**Comment by simartin** [comment]
Awesome! I'll keep an eye on #8558 and resume writing a wpt along with this patch.

**Comment by simartin** [comment]
The fix for https://github.com/servo/servo/pull/8558 has been merged, hence resuming work on this issue

**Comment by jdm** [comment]
:dancer:

**Comment by simartin** [comment]
wpt test added as suggested

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8293#-:-K4Zdtp65l2Bf8UCUFAg:-1168645735)*

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for finishing this up!

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8293#-:-K4ZjWe2AHJPMPbP_6Hd:-1700168947)*

**Comment by jdm** [comment]
@bors-servo: retry
* #8802 and #8769

**Pull request merged**
