### PR TITLE
remove try! and replace it with '?'

### PR DESCRIPTION
**Pull request by srinivasreddy**
remove try! and replace it with '?'

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11742)

### CODE REVIEW

**Comment by nox** [comment]
Cc @jdm.

**Comment by Ms2ger** [comment]
I don't see how this is an improvement... this definitely should be discussed in advance.

**Comment by ConnorGBrewster** [comment]
If we do go one way or the other, we should make sure the code base stays consistent.

**Comment by emilio** [comment]
For what it's worth, I prefer the `try!` syntax, it's more explicit, and it isn't really a pain to type. Nontheless it can be discussed, and of course should be consistent (I think a tidy lint wouldn't be hard in one or another direction).

**Comment by nox** [comment]
Our dependencies at some point are going to use them, so we better get used to it now, IMO.

**Comment by jdm** [comment]
I haven't seen a compelling reason to start using ? in Servo's code. We can revisit this if the syntax becomes stable, or would improve the clarity or maintainability of some code in particular, but until then I don't think it's worth rewriting existing code or using it in new code.

**Comment by srinivasreddy** [comment]
Thanks.

**Comment by jdm** [comment]
Thanks for proposing the change :)

**Comment by srinivasreddy** [comment]
You are welcome. :)

**Pull request closed without merging**
