### PR TITLE
Partially enable referrer-policy tests with some modifications

### PR DESCRIPTION
**Pull request by nox**
This is a part of @rebstar6's work on #11422, with only her test fixes and the enabling of them, to ease review on the actual implementation.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11429)

### CODE REVIEW

**Comment by mbrubeck** [comment]
The mac-rel-css build hit an infrastructure issue, but [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/1269/steps/test_1/logs/stdio) shows a large number of timeouts in the referrer-policy tests.

**Comment by nox** [comment]
I had forgotten an async xhr in common.js, this is fixed now.

@bors-servo r=jdm

**Comment by nox** [comment]
Damn it, this failed again. http://build.servo.org/builders/linux-rel/builds/1266

Weirdly I can't reproduce locally. :(

**Comment by nox** [comment]
I think the paths were incorrect in `tests/wpt/mozilla/tests/mozilla/referrer-policy/spec_json.js` but this is a wild guess. Trying.

@bors-servo try

**Comment by nox** [comment]
@jdm These errors make no sense:

```
  │ ERROR:js::rust: Error at http://www1.web-platform.test:8000/_mozilla/mozilla/referrer-policy/generic/subresource/document.py:3:9: document.referrer is undefined
```

The only place where there is a `document.referrer` at line 3 of a script is in the original document template.

**Comment by jdm** [comment]
No, it should be used in the new template too, as far as I know. The other PR includes the referrer property in the document webidl.

**Comment by nox** [comment]
@jdm Yes but our modified template doesn't use it at line 3, which is why it's looking quite weird to me.

I even changed the modified template to use an intermediate value.

See https://github.com/servo/servo/pull/11429/files#diff-ecaadabdf778879bb4bd7a7f926c364e, how could that trigger such an "document.referrer is undefined" error?

**Comment by nox** [comment]
@jdm OMG.

This works:
```
./mach test-wpt /referrer-policy/
```

This works:
```
./mach test-wpt /_mozilla/mozilla/referrer-policy/
```

This doesn't work:
```
./mach test-wpt /referrer-policy/ /_mozilla/mozilla/referrer-policy/
```

So we are sharing some state or something like that, somewhere. Any clue where that could come from?

**Comment by nox** [comment]
With:

```diff
--- i/tests/wpt/web-platform-tests/referrer-policy/generic/template/document.html.template
+++ w/tests/wpt/web-platform-tests/referrer-policy/generic/template/document.html.template
@@ -5,6 +5,7 @@
   </head>
   <body>
     <script>
+      you_are_broken();
       var result = {
         location: document.location.toString(),
         referrer: document.referrer.length > 0 ? document.referrer : undefined,
```

When running:
```
./mach test-wpt /referrer-policy/ /_mozilla/mozilla/referrer-policy/
```

All the _mozilla tests fail with:
```
  │ ERROR:js::rust: Error at http://www1.web-platform.test:8000/_mozilla/mozilla/referrer-policy/generic/subresource/document.py:1:7: you_are_broken is not define
```

**Comment by nox** [comment]
So the tests were failing because all tests run in the same Python process. I renamed 'subresource' to 'mozresource' and everything passes now.

@bors-servo r=jdm

**Comment by emilio** [comment]
@bors-servo: retry 

 * https://github.com/servo/servo/issues/11276

**Comment by jdm** [comment]
@bors-servo: retry
* #11276

**Comment by jdm** [comment]
I wonder if the extra set of new tests causes cors-redirect.html to run at the same time as some other tests that cause a bunch of file handles to be consumed, leading to the timeout each time?

**Comment by jdm** [comment]
This will need to wait until #11447 merges before we try again.

**Comment by jdm** [comment]
@bors-servo: retry
* #11276

**Pull request merged**
