### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23456)

### CODE REVIEW

**Comment by jdm** [comment]
Sorry, this is hitting #23458 and we'll need to create a new magic leap SDK before this can merge.

**Comment by CYBAI** [comment]
```
{
    "status": "PASS", 
    "group": "default", 
    "message": null, 
    "stack": null, 
    "subtest": null, 
    "test": "/css/filter-effects/filters-test-brightness-003.html", 
    "line": 89150, 
    "action": "test_result", 
    "expected": "FAIL"
}
```

**Pull request merged**
