### PR TITLE
Implement heading/paragraph obsolete 'align' attribute

### PR DESCRIPTION
**Pull request by frewsxcv**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8536)

### CODE REVIEW

**Comment by eefriedman** [comment]
Looks fine... except that the attributes don't actually work.

**Comment by frewsxcv** [comment]
Huh. Shouldn't it be working from [these lines](https://github.com/frewsxcv/servo/blob/html-heading-paragraph-obsolete-align-attribute/resources/presentational-hints.css#L40-L43)?

**Comment by eefriedman** [comment]
servo doesn't support `:matches()` at the moment; see https://github.com/servo/rust-selectors/issues/48 .

**Comment by frewsxcv** [comment]
Maybe we should replace `matches` with what the HTML spec explicitly suggests?

https://html.spec.whatwg.org/multipage/rendering.html#tables-2

**Comment by eefriedman** [comment]
I would guess the HTML standard will replace the longer rule with a `:matches` rule when someone gets around to it... but sure, we can change our stylesheet for now.

**Comment by nox** [comment]
A nit and LGTM.

Why blocked on external?

+S-needs-code-changes 


---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/script/dom/htmlheadingelement.rs, line 64 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8536#-K3EP5lexi3x7Cc_8k2F)** ([raw file](https://github.com/servo/servo/blob/be232fd30a36c4e251e0a056e0f5abdc02f1ed1a/components/script/dom/htmlheadingelement.rs#L64)):</sup>
No need for virtual methods here.


---

<sup>**[components/script/dom/htmlparagraphelement.rs, line 50 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8536#-K3EP8CaN65hifC306SX)** ([raw file](https://github.com/servo/servo/blob/be232fd30a36c4e251e0a056e0f5abdc02f1ed1a/components/script/dom/htmlparagraphelement.rs#L50)):</sup>
Ditto.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8536)

**Comment by frewsxcv** [comment]
> Why blocked on external?

I thought the policy was to not implement reflection attributes if the features aren't working

**Comment by frewsxcv** [comment]
If people are fine with me moving forward on this, I'll address @nox's comments.

**Comment by frewsxcv** [comment]
No point in keeping this open. More important that `matches` gets implemented first

**Pull request closed without merging**
