### PR TITLE
fixes test-wpt cannot be run from anywhere but the root

### LINKED ISSUE #7085: test-wpt cannot be run from anywhere but the root
Steps to reproduce:
- `cd tests/wpt`
- `../../mach test-wpt`

This is because the paths in `python/servo/testing_commands.py` are relative and we should be appending them to the root path instead.

### PR DESCRIPTION
**Pull request by wilcus**
Fixes #7085 

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7159)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Excellent! It also looks like the `path.join` on lines 345 and 347 will also need to get updated in case the user does not have a virtual environment set up yet. The same goes for line 246 for the path to the HOSTS file

**Comment by wilmoz** [comment]
@frewsxcv ok i change it

**Pull request merged**
