### PR TITLE
Work around deprecation warnings caused by autocfg $RUSTFLAGS handling

### PR DESCRIPTION
**Pull request by SimonSapin**
See https://github.com/servo/servo/issues/24446

### CODE REVIEW

**Comment by nox** [comment]
Lol.

@bors-servo r+

**Comment by SimonSapin** [comment]
All Windows tasks failed to create a virtualenv:

```
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
```

… which appears unrelated to this PR.

**Comment by SimonSapin** [comment]
https://pypi.org/project/cffi/#files currently says that `cffi-1.13.0-cp27-cp27m-win32.whl` was uploaded “about an hour ago” while `cffi-1.13.0.tar.gz` was uploaded “about 4 hours ago”. It seems likely that our builds usually find a pre-compiled CFFI, but this one happened just at the time where it wasn’t available and our Windows AMI doesn’t have everything needed to compile CPython 2.7 extension modules from source.

@bors-servo retry

**Comment by jdm** [comment]
The same error occurred on the windows nightly runs.

**Comment by SimonSapin** [comment]
Added a commit to patch the `autocfg` crate

**Comment by CYBAI** [comment]
@bors-servo retry

- #21067
- #23290

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Comment by CYBAI** [comment]
@bors-servo retry

- #23290

**Comment by jdm** [comment]
@bors-servo retry
* Network issue

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
