### PR TITLE
Implement SetNamedItem and SetNamedItemNS

### PR DESCRIPTION
**Pull request by mathieuh**
@nox Can you add the "it needs tests" tag or so?

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9061)

### CODE REVIEW

**Comment by eefriedman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/attr.rs, line 201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9061#-K6LLIgptx4Habi_mR2w:-K6LLIgptx4Habi_mR2x:-1333620564) ([raw file](https://github.com/servo/servo/blob/31fd4e3401118be8a789940ae29946babf2f4321/components/script/dom/attr.rs#L201)):*
This looks wrong; if the existing assertions trigger, you're probably doing things in the wrong order.

---

*[components/script/dom/namednodemap.rs, line 92 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9061#-K6LLmQicWMFvzCPbuzn:-K6LLmQjai5L2oRK7kT8:1901395080) ([raw file](https://github.com/servo/servo/blob/31fd4e3401118be8a789940ae29946babf2f4321/components/script/dom/namednodemap.rs#L92)):*
We should only call `attribute_mutated` once when an attribute is mutated like this.  Better for performance, and avoids potential weird behavior in edge cases.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9061)*

**Comment by nox** [comment]
@mathieuh I've just realised that you should in fact implement [Element.setAttributeNode](https://dom.spec.whatwg.org/#dom-element-setattributenode) and call that from `Element.setAttributeNodeNS`, `NamedNodeMap.setNamedItem` and `NamedNodeMap.setNamedItemNS`.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/namednodemap.rs, line 92 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9061#-K6LLmQicWMFvzCPbuzn:-K6LZVYwU5JJatTKghZ3:-370572376) ([raw file](https://github.com/servo/servo/blob/31fd4e3401118be8a789940ae29946babf2f4321/components/script/dom/namednodemap.rs#L92)):*
I don't think so. I introduced `attribute_mutated` to later use them for mutation observers. In the case of setAttributeNode, there will be 0, 1 or 2 of them.

Out of curiosity, what weird behaviour are you thinking about?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9061#-:-K6LZiq-sgRgwUB5nzZn:-191714659)*

**Comment by eefriedman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/namednodemap.rs, line 92 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9061#-K6LLmQicWMFvzCPbuzn:-K6Lfdlf6Z0drel2LGVb:1396069220) ([raw file](https://github.com/servo/servo/blob/31fd4e3401118be8a789940ae29946babf2f4321/components/script/dom/namednodemap.rs#L92)):*
There are a few attributes for which removing, then setting, the attribute has side-effects which are different from just setting it.   For example, when SetNamedItem is called on an iframe, we only want to go through the "process the iframe attributes" steps once.  Or for an input of type file, setting the type attribute to file shouldn't reset the input's state.

At least, I think that's how it should work?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9061)*

**Comment by mathieuh** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/attr.rs, line 201 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9061#-K6LLIgptx4Habi_mR2w:-K6hsXPj19JsH0nR_QsX:-2014238784) ([raw file](https://github.com/servo/servo/blob/31fd4e3401118be8a789940ae29946babf2f4321/components/script/dom/attr.rs#L201)):*
The old assertion was never triggered because attributes never gain a new owner in the current code. @nox says he wrote it preemptively but that it might not fit in the end.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9061)*

**Comment by nox** [comment]
```javascript
div = document.createElement("div");
div.setAttribute("foo", "bar");
mo = new MutationObserver(function (records) { alert(records.length) }); mo.observe(div, {"attributes": true, "attributeOldValue": true});
attr = document.createAttribute("foo");
attr.value = "qux";
div.setAttributeNode(attr);
```

That alerts "1" in both Safari and Firefox, so I guess the spec is wrong for that function…

**Comment by mathieuh** [comment]
I've added the implementation of SetAttributeNode and SetAttributeNodeNS.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9061#-:-K6ifbySwiV9dnTKvbSR:-214990024)*

**Comment by eefriedman** [comment]
Someone needs to file a bug against the DOM specification (https://github.com/whatwg/dom/issues); hopefully, we can get the specification clarified quickly.

Also, I'd like to see a test for the ordering of the attribute list (the return value of `element.attributes.item(0)` after SetAttributeNode on an element with multiple attributes).

**Comment by nox** [comment]
@eefriedman I'm taking care of making a patch for the spec.

**Comment by nox** [comment]
https://github.com/whatwg/dom/pull/139

**Comment by nox** [comment]
```

./components/script/dom/element.rs:1270: method declared in webidl is missing a comment with a specification link
./components/script/dom/element.rs:1299: method declared in webidl is missing a comment with a specification link
```

**Comment by nox** [comment]
Spec has been fixed. Attributes shouldn't be reordered anymore and the hooks should be triggered only once.

**Comment by mathieuh** [comment]
I updated the code to match the new spec.

**Comment by KiChjang** [comment]
Fails tidy:
```
./components/script/dom/element.rs:1322: method declared in webidl is missing a comment with a specification link
```

And also fails to build:
```
/home/travis/build/servo/servo/target/debug/build/script-7d4eb0076eebd90a/out/Bindings/AttrBinding.rs:689:1: 693:2 error: conflicting implementations for trait `core::cmp::PartialEq` [E0119]
/home/travis/build/servo/servo/target/debug/build/script-7d4eb0076eebd90a/out/Bindings/AttrBinding.rs:689 impl PartialEq for Attr {
/home/travis/build/servo/servo/target/debug/build/script-7d4eb0076eebd90a/out/Bindings/AttrBinding.rs:690     fn eq(&self, other: &Attr) -> bool {
/home/travis/build/servo/servo/target/debug/build/script-7d4eb0076eebd90a/out/Bindings/AttrBinding.rs:691         self as *const Attr == &*other
/home/travis/build/servo/servo/target/debug/build/script-7d4eb0076eebd90a/out/Bindings/AttrBinding.rs:692     }
/home/travis/build/servo/servo/target/debug/build/script-7d4eb0076eebd90a/out/Bindings/AttrBinding.rs:693 }
/home/travis/build/servo/servo/components/script/dom/bindings/mod.rs:158:9: 158:64 note: in this expansion of include!
/home/travis/build/servo/servo/target/debug/build/script-7d4eb0076eebd90a/out/Bindings/AttrBinding.rs:689:1: 693:2 help: run `rustc --explain E0119` to see a detailed explanation
/home/travis/build/servo/servo/components/script/dom/namednodemap.rs:25:1: 29:2 note: note conflicting implementation here
/home/travis/build/servo/servo/components/script/dom/namednodemap.rs:25 impl PartialEq for Attr {
/home/travis/build/servo/servo/components/script/dom/namednodemap.rs:26     fn eq(&self, other: &Attr) -> bool {
/home/travis/build/servo/servo/components/script/dom/namednodemap.rs:27         self as *const Attr == &*other
/home/travis/build/servo/servo/components/script/dom/namednodemap.rs:28     }
/home/travis/build/servo/servo/components/script/dom/namednodemap.rs:29 }
error: aborting due to previous error
```

**Comment by mathieuh** [comment]
Merge conflicts resolved.

**Comment by KiChjang** [comment]
It seems that you still haven't addressed the tidy issues and the build issues. Travis CI still fails at your latest commit.

**Comment by mathieuh** [comment]
@KiChjang I fixed it.

**Comment by eefriedman** [comment]
Code looks fine; still needs tests.

**Comment by mathieuh** [comment]
@eefriedman Tests added, there were already some btw.

**Comment by jdm** [comment]
```
 ▶ Unexpected subtest result in /dom/nodes/attributes.html:
  └ PASS [expected FAIL] setAttributeNode, if it fires mutation events, should fire one with the new node when resetting an existing attribute (outer shell)

  ▶ Unexpected subtest result in /dom/nodes/attributes.html:
  └ PASS [expected FAIL] setAttributeNode called with an Attr that has the same name as an existing one should not change attribute order

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] Element interface: document.createElement("noscript") must inherit property "setAttributeNode" with the proper type (19)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] Element interface: calling setAttributeNode(Attr) on document.createElement("noscript") with too few arguments must throw TypeError

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] Element interface: document.createElement("noscript") must inherit property "setAttributeNodeNS" with the proper type (20)

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] Element interface: calling setAttributeNodeNS(Attr) on document.createElement("noscript") with too few arguments must throw TypeError
```

**Comment by nox** [comment]
@mathieuh fixed the test expectations.

**Pull request merged**
