### PR TITLE
implement webglcontextevent

### LINKED ISSUE #10742: Implement the "webglcontextevent" argument to Document::createEvent
Blocks #2185, #10734.

This will involve writing a `new_uninitialized` function on `WebGLContextEvent` and calling it from `Document::CreateEvent`.

* Spec: <https://dom.spec.whatwg.org/#dom-document-createevent>.
* Code: `components/script/dom/document.rs`, `components/script/dom/webglcontextevent.rs`.
* Test: `dom/nodes/Document-createEvent.html`.

### PR DESCRIPTION
**Pull request by tylersouthwick**
fixes #10742

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10805)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r+

**Comment by jdm** [comment]
@bors-serso r-
`./mach test-tidy` doesn't pass yet according to TravisCI.

**Comment by Ms2ger** [comment]
So it seems:
```
./components/script/dom/document.rs:81: use statement is not in alphabetical order

	expected: dom::window::{ReflowReason, Window}

	found: dom::webglcontextevent::WebGLContextEvent

./components/script/dom/webglcontextevent.rs:44: extra space before :
```

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r+

**Pull request merged**
