### PR TITLE
Support WorkerOptions for Worker

### PR DESCRIPTION
**Pull request by CYBAI**
I'd like to start working on updating SW related codes and I found it will have some algorithms related to module workers. And I found parts of the spec update is related to [fetch a module worker script graph](https://html.spec.whatwg.org/multipage/#fetch-a-module-worker-script-tree), maybe it's worth being a separate PR?

---
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix part of #23308 
- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23309)

### CODE REVIEW

**Comment by nox** [comment]
As usual, good work @CYBAI!

**Comment by nox** [comment]
Well, if I don't tell the bot anything it's not going to land any time soon… It kinda shows that I'm just back from PTO hah.

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #23354 #22212

**Comment by CYBAI** [comment]
@bors-servo retry

- #13480

**Comment by CYBAI** [comment]
ok, I guess I need to wait for #23359 🤔

```
Exception: Your system's gstreamer libraries are out of date (we need at least 1.12). If you're unable to install them, let us know by filing a bug!
```

**Comment by CYBAI** [comment]
Rebased 🙇

**Comment by CYBAI** [comment]
@bors-servo retry

```
  ▶ FAIL [expected PASS] /css/CSS2/css1/c71-fwd-parsing-000.xht
  └   → /css/CSS2/css1/c71-fwd-parsing-000.xht b51dea21ab706ac31cace72ed3d4e41ef86ad14e
/css/CSS2/css1/c71-fwd-parsing-000-ref.xht 8f1c7e0efd50de543d5195f3eaf416ca062c042f
```

**Pull request merged**
