### PR TITLE
Update to 2020/8/15 rustc.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by jdm** [comment]
Sadly rustfmt is missing again, so this will have to wait until https://rust-lang.github.io/rustup-components-history/ shows it's available.

**Comment by CYBAI** [comment]
rustfmt shows up again from 8/13 nightly.

**Comment by jdm** [comment]
```
info: downloading component 'rust-src'
info: installing component 'rust-src'
...
error: `rust-src` component not found. Run `rustup component add rust-src`.
note: run with `RUST_BACKTRACE=1` for a backtrace
```
That's not good.

**Comment by jdm** [comment]
#27619

**Pull request closed without merging**
