### PR TITLE
Rename the variants of the SubmittedFrom and ResetFrom enums to be less repetitive

### LINKED ISSUE #11557: SubmittedFrom, ResetFrom variants have repetitive names
`components/script/dom/htmlformelement.rs` has
```rust
pub enum SubmittedFrom {
    FromFormSubmitMethod,
    NotFromFormSubmitMethod
}

pub enum ResetFrom {
    FromFormResetMethod,
    NotFromFormResetMethod
}
```

The suffixes are not particularly useful and should be removed.

### PR DESCRIPTION
**Pull request by rafaqtro**
delete suffixes for variants SubmittedFrom, ResetFrom

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #11557 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11605)

### CODE REVIEW

**Comment by KiChjang** [comment]
Just a side note - please fill in the PR template next time, it would make the process faster by linking it correctly to the relevant GitHub issue. Thanks!

**Comment by KiChjang** [comment]
The patch looks good, but please squash and we'll happily merge this!

**Comment by rafaqtro** [comment]
Sorry @KiChjang , i'll keep that in mind for the next PR, thanks for the help.

**Pull request merged**
