### PR TITLE
Trace and finalize BrowsingContext

### PR DESCRIPTION
**Pull request by jdm**
This is a prerequisite for merging #11044, and is an important correctness fix on its own.

r? @Ms2ger

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11113)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> warning **Warning** warning
> 
> * These commits modify **unsafe code**. Please review it carefully!
> * These commits modify script code, but no tests are modified. Please consider adding a test!</details>


---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/browsingcontext.rs, line 283 \[r3\]](https://reviewable.io:443/reviews/servo/servo/11113#-KHQTx-ZeI_adbgdy_Z0:-KHQTx-ZeI_adbgdy_Z1:-1488055287) ([raw file](https://github.com/servo/servo/blob/6165a524c9f86dcc0d58c510566c396756fb066f/components/script/dom/browsingcontext.rs#L283)):*
> ```Rust
> unsafe extern fn trace(trc: *mut JSTracer, obj: *mut JSObject) {
>     let this = GetProxyExtra(obj, 0).to_private() as *const BrowsingContext;
>     if this.is_null() { return; } // GC during obj creation
> ```

```rust
if this.is_null() {
    // GC during object creation.
    return;
}
```

---

*[components/script/dom/bindings/js.rs, line 111 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11113#-KHQTMxGaWK_2f5myxBH:-KHQTMxGaWK_2f5myxBI:1690463915) ([raw file](https://github.com/servo/servo/blob/452530d05e0e3ddc9f16b66d2afa84d7c183d4b5/components/script/dom/bindings/js.rs#L111)):*
> ```Rust
>     fn trace(&self, trc: *mut JSTracer) {
>         trace_reflector(trc,
>                         &format!("for {} on heap", unsafe { type_name::<T>() }),
> ```

I think this is going to be too expensive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11113#-:-KHQUCdsRBYCWUwQq1gH:1458266033)*

**Comment by Ms2ger** [comment]
@bors-servo r+

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.</details>


---

Reviewed 4 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11113#-:-KHTxq-uV1e_3x22n46Q:1236647940)*

**Comment by KiChjang** [comment]
@bors-servo retry

* The annoying git

**Comment by Ms2ger** [comment]
```
/home/servo/buildbot/slave/linux-rel/build/components/script/dom/bindings/js.rs:113:14: 113:23 error: unresolved name `trace_str` [E0425]
/home/servo/buildbot/slave/linux-rel/build/components/script/dom/bindings/js.rs:113             &trace_str[..]
                                                                                                 ^~~~~~~~~
```
@bors-servo r-

**Pull request merged**
