### PR TITLE
Various layout cleanup.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6650)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6650)

**Comment by Ms2ger** [comment]
@bors-servo retry
* #6644

**Comment by jdm** [comment]
@bors-servo: retry
* #6656

**Pull request merged**
