### PR TITLE
Add UWP port - bis

### PR DESCRIPTION
**Pull request by paulrouget**
This is #23658 with some fixes:
- removed nspr from DLL dependencies (was breaking VS build)
- exclude symbols from header file (was breaking VS build)
- rebased

Before merging:
- please check the rebased commit that introduces the `--uwp` option (things moved around since https://github.com/servo/servo/commit/7c85dc09b59e653caf60cb18d3b3fdea2ba4d4ae)
- should we wait until the WR fix lands upstream?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23696)

### CODE REVIEW

**Comment by paulrouget** [comment]
@jdm r?

**Comment by paulrouget** [comment]
tidy is really unhappy. Gonna fix that.

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
One issue I keep seeing - building twice in a row with --uwp causes a lot (but not all) of servo's dependencies to be rebuilt, even though no changes occurred. I'm trying to figure out what's causing that.

**Comment by jdm** [comment]
I can no longer reproduce the build issue from the previous comment.

**Pull request merged**
