### PR TITLE
Fix #6242 testbinding add specialoperations

### LINKED ISSUE #6242: Add special operations to TestBinding.webidl
http://heycam.github.io/webidl/#idl-special-operations

TestBinding.webidl is supposed to exercise all of the different parts of our WebIDL binding code generation, but it doesn't generate any code related to special operations. It needs named getters/setters, indexed getters/setters, a stringifier, and a deleter. There are examples of these in other WebIDL files (search for strings like "getter", "setter", "deleter", etc.)

code: components/script/dom/webidls/TestBinding.webidl

### PR DESCRIPTION
**Pull request by ghost**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6284)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- components/script/dom/mod.rs @ r2
- components/script/dom/testbindingproxy.rs @ r2
- components/script/dom/webidls/TestBindingProxy.webidl @ r1

---

<sup>**[components/script/dom/testbindingproxy.rs, line 7 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6284#-Jr2OyXUyHkthtQWhKZM)** ([raw file](https://github.com/servo/servo/blob/4018a118d62130ee3b3651e45e4676b4baa50c85/components/script/dom/testbindingproxy.rs#L7)):</sup>
Nit: remove braces.

---

<sup>**[components/script/dom/testbindingproxy.rs, line 14 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6284#-Jr2P-AEgukiVGqJfKSp)** ([raw file](https://github.com/servo/servo/blob/4018a118d62130ee3b3651e45e4676b4baa50c85/components/script/dom/testbindingproxy.rs#L14)):</sup>
Nit: the global field is useless.

---

<sup>**[components/script/dom/webidls/TestBindingProxy.webidl, line 6 \[r2\]](https://reviewable.io:443/reviews/servo/servo/6284#-Jr2Oml59lxms2wbQ-RY)** ([raw file](https://github.com/servo/servo/blob/4018a118d62130ee3b3651e45e4676b4baa50c85/components/script/dom/webidls/TestBindingProxy.webidl#L6)):</sup>
Nit: this is not true, please rephrase.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6284)

**Comment by nox** [comment]
-S-awaiting-review +S-awaiting-answer 

---

Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.
Reviewed files:
- components/script/dom/testbindingproxy.rs @ r3
- components/script/dom/webidls/TestBindingProxy.webidl @ r3

---

<sup>**[components/script/dom/testbindingproxy.rs, line 12 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6284#-Jr5-jLC9zk12aunJbpf)** ([raw file](https://github.com/servo/servo/blob/bc7117ef386aec428ff3f6bc7ea7c105e1f8aa08/components/script/dom/testbindingproxy.rs#L12)):</sup>
I just noticed that this is called reflector_ in all other structures and I have no idea why. Will r+ or tell you to change it once someone tells me if it's important or not. @jdm? @Manisheart?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6284)

**Comment by nox** [comment]
-S-awaiting-answer +S-needs-code-changes 

---

Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/testbindingproxy.rs, line 12 \[r3\]](https://reviewable.io:443/reviews/servo/servo/6284#-Jr5-jLC9zk12aunJbpf)** ([raw file](https://github.com/servo/servo/blob/bc7117ef386aec428ff3f6bc7ea7c105e1f8aa08/components/script/dom/testbindingproxy.rs#L12)):</sup>
@Manishearth just told me it's to avoid clashing with the reflector() method, please rename to reflector_.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6284)

**Comment by nox** [comment]
Squash everything and I'll r+ it. :)

-S-awaiting-review +S-needs-squash 

---

Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.
Reviewed files:
- components/script/dom/testbinding.rs @ r4
- components/script/dom/testbindingproxy.rs @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6284)

**Comment by fbau123** [comment]
Done!

**Comment by nox** [comment]
@bors-servo: r+

-S-awaiting-review -S-needs-squash +S-awaiting-merge 

---

Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6284)

**Comment by nox** [comment]
```
/XMLHttpRequest/timeout-cors-async.htm
--------------------------------------
PASS expected FAIL XMLHttpRequest: timeout event and cross-origin request
/html/webappapis/scripting/processing-model-2/compile-error-cross-origin.html
-----------------------------------------------------------------------------
NOTRUN expected FAIL window.onerror - compile error in 
NOTRUN expected FAIL window.onerror - compile error in <script src=//www1...> (column)
TIMEOUT [Parent]
/_mozilla/mozilla/interfaces.html
---------------------------------
FAIL Interfaces exposed on the window
```

You need to patch the second list in /_mozilla/mozilla/interfaces.html and add TestBindingProxy in it.

**Comment by nox** [comment]
The two other failing tests are probably intermittent.

**Comment by nox** [comment]
@bors-servo: r+

-S-awaiting-review +S-awaiting-merge 

---

Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.
Reviewed files:
- tests/wpt/mozilla/tests/mozilla/interfaces.html @ r6

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6284)

**Pull request merged**
