### PR TITLE
Implement alert dialogs

### LINKED ISSUE #10812: Implement alert dialogs and support mozbrowsershowmodalprompt API
Now that we have support for the [tinyfiledialogs](https://github.com/jdm/tinyfiledialogs-rs) library, we can make use of it by invoking it from `Window::Alert`. There are a few parts to this:
* make the dialog box pop up
* send a synchronous message to the constellation instructing it to process an alert command
* if there is no parent for the pipeline requesting the alert, respond with a request for the originating script thread to show the dialog box
* otherwise, send a request to the root pipeline to trigger a mozbrowsershowmodalprompt event on the iframe that contains the pipeline that requested it
* when the root script thread responds that the event was dispatched, notify the original script thread that the action was completed
* do not display a dialog box

Code: `components/script/dom/window.rs`, `components/script/Cargo.toml`, `components/compositing/constellation.rs`, `components/script_traits/lib.rs`
Test: [write one](https://github.com/servo/servo/blob/master/tests/wpt/README.md#writing-new-tests) that demonstrates an iframe element receiving the appropriate event in `tests/wpt/mozilla/tests/mozilla/mozbrowser`

### PR DESCRIPTION
**Pull request by cbrewster**
fix #10812

Implements alert dialogs using tinyfiledialogs

r? @jdm

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10840)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@jdm this should be ready for review. It looks like a test is already present for this: `tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsershowmodalprompt_event.html`.

Let me know if you had a different test in mind.

**Comment by jdm** [comment]
This breaks the windows build; use of tinyfiledialogs needs to be gated on macos and linux, unfortunately.

**Comment by jdm** [comment]
Good start!
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 4 of 10 files at r1, 4 of 8 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/compositing/constellation.rs, line 1068 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYWC55dpjXyQlut8mS:-KGYWC55dpjXyQlut8mT:-1900780561) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1068)):*
I don't think `mut` is necessary.

---

*[components/compositing/constellation.rs, line 1071 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYWWgC10P_wAhRAPWm:-KGYWWgDZ0UzVr49ILc-:-2140952785) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1071)):*
We're actually going to need to obtain the root pipeline, not just the immediate parent. We should be sure to write a test for a mozbrowser that loads a document that contains an iframe that triggers an alert.

---

*[components/compositing/constellation.rs, line 1080 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYXiiqwvkldFwIiCf5:-KGYXiiqwvkldFwIiCf6:1353658771) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1080)):*
The "script tick" message doesn't make sense here.

---

*[components/compositing/constellation.rs, line 1082 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYXJGbLcoIQo_aWHAA:-KGYXJGcvfSfhvLDrp2b:-905732080) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1082)):*
We shouldn't ignore the alert if the mozbrowser pref isn't enabled. We should fall back to the same behaviour as if it's a root pipeline requesting it.

---

*[components/compositing/constellation.rs, line 1085 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYXt41uBhFTiEq_bvt:-KGYXt41uBhFTiEq_bvu:-1150853644) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1085)):*
Rather than sending a new instruction to the original pipeline, this is where we should send a synchronous response to the original pipeline indicating that it should display a dialog.

---

*[components/compositing/constellation.rs, line 1088 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYXm1H3R2-LR63i2xI:-KGYXm1H3R2-LR63i2xJ:-1165696661) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1088)):*
"script tick" doesn't make sense here.

---

*[components/script/dom/window.rs, line 428 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYUnS61zMlVpvWI_L6:-KGYUnS7eFJKLJ1JhEby:-451817925) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/script/dom/window.rs#L428)):*
The `Alert` method needs to block until we finish executing the required actions. The constellation probably needs to send a response indicating whether we still need to show a dialog or not.

---

*[components/script_traits/lib.rs, line 153 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYVYVo1OJJmUydp6AT:-KGYVYVpH9Zm0i7SSiwr:1657720680) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/script_traits/lib.rs#L153)):*
`to trigger an alert dialog box`

---

*[components/script_traits/script_msg.rs, line 85 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYY9oi0Mg7zuacjKpq:-KGYY9oi0Mg7zuacjKpr:1914807163) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/script_traits/script_msg.rs#L85)):*
This shouldn't be necessary with the earlier changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10840#-:-KGYY5-JXaHzACY9mbhI:-750456695)*

**Comment by ConnorGBrewster** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[components/compositing/constellation.rs, line 1068 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYWC55dpjXyQlut8mS:-KGYlHBtf40-QkksAHa3:-1939415131) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1068)):*
I had to leave it as `mut` as `handle_send_error` requires it.

---

*[components/compositing/constellation.rs, line 1071 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYWWgC10P_wAhRAPWm:-KGYlZRr3taxHzn_EcOn:-175832768) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1071)):*
Does this test not already exist? `tests/wpt/mozilla/tests/mozilla/mozbrowser/mozbrowsershowmodalprompt_event.html`

---

*[components/compositing/constellation.rs, line 1080 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYXiiqwvkldFwIiCf5:-KGYlql0PkY1M0Rz-A7z:-499146009) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1080)):*
Done.

---

*[components/compositing/constellation.rs, line 1082 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYXJGbLcoIQo_aWHAA:-KGYyYeV5WkNLDqPyDzh:-499146009) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1082)):*
Done.

---

*[components/compositing/constellation.rs, line 1085 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYXt41uBhFTiEq_bvt:-KGYyY0FyQvQ3Y62pUTq:-499146009) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1085)):*
Done.

---

*[components/compositing/constellation.rs, line 1088 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYXm1H3R2-LR63i2xI:-KGYlrh4dSQf89GyuKse:-499146009) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1088)):*
Done.

---

*[components/script/dom/window.rs, line 428 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYUnS61zMlVpvWI_L6:-KGYyWU2SAUCTSTmILOi:-499146009) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/script/dom/window.rs#L428)):*
Done.

---

*[components/script_traits/lib.rs, line 153 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYVYVo1OJJmUydp6AT:-KGYyVJxN-z4jgN2QTvU:-499146009) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/script_traits/lib.rs#L153)):*
Done.

---

*[components/script_traits/script_msg.rs, line 85 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYY9oi0Mg7zuacjKpq:-KGYlHxu3Zg6MFOCVrt9:-499146009) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/script_traits/script_msg.rs#L85)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10840)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 3 of 5 files at r4.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/compositing/constellation.rs, line 1071 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYWWgC10P_wAhRAPWm:-KG_CPj6aW8DeQYtUqnk:-1223263217) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1071)):*
That only tests one immediate child frame. We should enhance that test to verify the behaviour when there's an iframe that contains another iframe.

---

*[components/compositing/constellation.rs, line 1071 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10840#-KG_HsrgOkzhHrkEPnU_:-KG_HsrgOkzhHrkEPnUa:1546140140) ([raw file](https://github.com/servo/servo/blob/984e8815ca87abda1a59174e64043d35f6d864e7/components/compositing/constellation.rs#L1071)):*
I would not expect this subpage_id to work correctly in cases of multiple layers of nested iframes, since it represents a particular iframe inside of a particular pipeline. We'll need to walk up the tree of pipeline parents like `trigger_mozbrowsererror` does; it's probably worth abstracting that into a form that can be shared by both methods.

---

*[components/script/dom/window.rs, line 348 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10840#-KG_D8cLhTktZ7cSFL4L:-KG_D8cLhTktZ7cSFL4M:1613713769) ([raw file](https://github.com/servo/servo/blob/984e8815ca87abda1a59174e64043d35f6d864e7/components/script/dom/window.rs#L348)):*
No need for this to be a member function of Window. It can be freestanding in the same file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10840#-:-KG_IZJnmfTaIKGetqtQ:1458266033)*

**Comment by ConnorGBrewster** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/compositing/constellation.rs, line 1071 \[r3\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGYWWgC10P_wAhRAPWm:-KGbcajg2UdV7C2r1bfe:-499146009) ([raw file](https://github.com/servo/servo/blob/59146dbdda29d7d939bf85742db57d7be8b6fae3/components/compositing/constellation.rs#L1071)):*
Done.

---

*[components/compositing/constellation.rs, line 1071 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10840#-KG_HsrgOkzhHrkEPnU_:-KGbaVpX7kBV35MXybq9:-499146009) ([raw file](https://github.com/servo/servo/blob/984e8815ca87abda1a59174e64043d35f6d864e7/components/compositing/constellation.rs#L1071)):*
Done.

---

*[components/script/dom/window.rs, line 348 \[r4\]](https://reviewable.io:443/reviews/servo/servo/10840#-KG_D8cLhTktZ7cSFL4L:-KGbV7zxVkEXOG00sg4Y:-499146009) ([raw file](https://github.com/servo/servo/blob/984e8815ca87abda1a59174e64043d35f6d864e7/components/script/dom/window.rs#L348)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10840)*

**Comment by ConnorGBrewster** [comment]
Rebased

**Comment by jdm** [comment]
Great work! This is really close :)
-S-awaiting-review -S-needs-tests +S-needs-code-changes 

---

Reviewed 1 of 5 files at r4, 8 of 11 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/compositing/constellation.rs, line 1081 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGrPA9GB_cszlNPEWr1:-KGrPA9GB_cszlNPEWr2:1399225094) ([raw file](https://github.com/servo/servo/blob/81adf3826128c40a6a33b69404c5c0283e39968b/components/compositing/constellation.rs#L1081)):*
Let's return with a warning if `root_pipeline != ancestor_info.0`, since that would mean that a pipeline in a non-current frame is trying to show an alert.

---

*[components/compositing/constellation.rs, line 1980 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGrNUd3ct3EFzSglLp7:-KGrNUd3ct3EFzSglLp8:-862873576) ([raw file](https://github.com/servo/servo/blob/81adf3826128c40a6a33b69404c5c0283e39968b/components/compositing/constellation.rs#L1980)):*
Let's call this method `get_root_pipeline_and_containing_parent`, with a comment like `/// For a given pipeline, determine the iframe in the root pipeline that transitively contains it. There could be arbitrary levels of nested iframes in between them.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10840#-:-KGrPnNQpN63f7TpyoKZ:837191082)*

**Comment by ConnorGBrewster** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/compositing/constellation.rs, line 1081 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGrPA9GB_cszlNPEWr1:-KGreFWZgkk5I8F1M-8q:-499146009) ([raw file](https://github.com/servo/servo/blob/81adf3826128c40a6a33b69404c5c0283e39968b/components/compositing/constellation.rs#L1081)):*
Done.

---

*[components/compositing/constellation.rs, line 1980 \[r6\]](https://reviewable.io:443/reviews/servo/servo/10840#-KGrNUd3ct3EFzSglLp7:-KGreG-SZKl3t8XxoVAW:-499146009) ([raw file](https://github.com/servo/servo/blob/81adf3826128c40a6a33b69404c5c0283e39968b/components/compositing/constellation.rs#L1980)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10840)*

**Comment by jdm** [comment]
@bors-servo: delegate+
Looks good. Please squash the commits together and merge with r=jdm!
-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10840#-:-KGrh6YUIJLt1tNVyWzE:-357795612)*

**Comment by nox** [comment]
@bors-servo r-

Temporary r- just so that smup doesn't rebuild the world again.

**Comment by ConnorGBrewster** [comment]
@bors-servo r=jdm
 * Updated tinyfiledialogs

**Comment by KiChjang** [comment]
@bors-servo 
* the annoying git

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * git

**Pull request merged**
