### PR TITLE
Make layout task fields private

### PR DESCRIPTION
**Pull request by hfaulds**
For https://github.com/servo/servo/issues/8471

The second commit I'm slightly less sure about but with `chan` made private this warning was shown:

```
components/layout/layout_task.rs:152:5: 152:21 warning: struct field is never used: `chan`, #[warn(dead_code)] on by default
```

There might be some cleanup around `layout_chan` in https://github.com/hfaulds/servo/blob/make-layout-task-fields-private/components/layout/layout_task.rs#L244-L261 as well but that was a bit beyond me.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8485)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you, this is great! One more thing you could do below.

-S-awaiting-review +S-needs-code-changes 


---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/layout/layout_task.rs, line 244 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8485#-K2vs28pPwi4UsqqNFff)** ([raw file](https://github.com/servo/servo/blob/5e7bf9cd9c1c781fd107af37f8a8b6cf9742dbc8/components/layout/layout_task.rs#L244)):</sup>
There's one small simplification you could still do: remove the `layout_chan` local variable, and use `sender` directly in `run_with_memory_reporting` below.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8485)

**Comment by hfaulds** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[components/layout/layout_task.rs, line 244 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8485#-K2vs28pPwi4UsqqNFff)** ([raw file](https://github.com/servo/servo/blob/5e7bf9cd9c1c781fd107af37f8a8b6cf9742dbc8/components/layout/layout_task.rs#L244)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8485)

**Comment by Ms2ger** [comment]
Thanks again!

-S-awaiting-review +S-awaiting-merge 

@bors-servo r+


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8485)

**Pull request merged**
