### PR TITLE
Update WR (box shadows + per-corner radii, elliptical clips).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18956)

### CODE REVIEW

**Comment by glennw** [comment]
@bors-servo retry
 * infra issue?

**Comment by jdm** [comment]
That problem will be solved by #18961.

**Comment by jdm** [comment]
```
  ▶ PASS [expected FAIL] /css-backgrounds-3_dev/html4/css-box-shadow-001.htm
```

**Comment by jdm** [comment]
That's #13509. Everything else passed.

**Comment by jdm** [comment]
@bors-servo: retry
* #13480

**Pull request merged**
