### PR TITLE
Added Store Command to ImageCache Task

### PR DESCRIPTION
**Pull request by srm09**
Implemented last bullet of [Image conformance student project: Initial Steps](https://github.com/servo/servo/wiki/Image-load-conformance-student-project)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10767)

### CODE REVIEW

**Comment by srm912** [comment]
@jdm In the `store_decode_image` routine, should the `PendingLoad` have an `ImageListener`?

**Comment by jdm** [comment]
Thanks for doing this! I wish I could point you at unit tests for this, but they don't exist yet. Please run `./mach test-tidy` and fix what it reports, too.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/net/image_cache_thread.rs, line 398 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu1Z659DR1WBQKBPHR:-KFu1Z659DR1WBQKBPHS:-1450690894) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net/image_cache_thread.rs#L398)):*
No need for the `let result` here.

---

*[components/net/image_cache_thread.rs, line 598 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu1coFqaOirR8Pd6k1:-KFu1coGmJWo6zsjHePE:-965522074) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net/image_cache_thread.rs#L598)):*
No need to clone the URL.

---

*[components/net/image_cache_thread.rs, line 598 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu484SKeSIapCUOWNr:-KFu484SKeSIapCUOWNs:-1070344222) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net/image_cache_thread.rs#L598)):*
Let's assert that `cache_result` is `CacheResult::Miss`.

---

*[components/net/image_cache_thread.rs, line 600 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu3QxApN7gGHD9mArf:-KFu3QxBwd-42kcLe2wN:-1354760493) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net/image_cache_thread.rs#L600)):*
We can use `self.progress_sender.send` instead.

---

*[components/net/image_cache_thread.rs, line 601 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu3VBcNVam8j4guKAu:-KFu3VBcNVam8j4guKAv:282571292) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net/image_cache_thread.rs#L601)):*
We'll need to send a ResponseComplete notification as well. No need for the `: ResponseAction`, though.

---

*[components/net_traits/image_cache_thread.rs, line 165 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu4Dm_uvpw8Y03zMlm:-KFu4Dm_uvpw8Y03zMln:1294299421) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net_traits/image_cache_thread.rs#L165)):*
`/// Decode the given image bytes and cache the result for the given URL.`

---

*[components/net_traits/image_cache_thread.rs, line 166 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu4Y_K6x7sJIq80PC2:-KFu4Y_K6x7sJIq80PC3:-928983313) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net_traits/image_cache_thread.rs#L166)):*
Let's call this `store_complete_image_bytes`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10767#-:-KFu4fDQIFmVM9_sTshR:1633459935)*

**Comment by jdm** [comment]
No, we shouldn't need an image listener for this instance. Thanks for checking!

**Comment by srm912** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/net/image_cache_thread.rs, line 601 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu3VBcNVam8j4guKAu:-KG0oEVdY1wbnR4vhynv:1240214915) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net/image_cache_thread.rs#L601)):*
Unsure about this change, since this causes the `loaded_bytes` to be unused, which entails that the image data is left unused. Is my implementation correct in this case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10767)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/net/image_cache_thread.rs, line 601 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu3VBcNVam8j4guKAu:-KG1z6q_rR0j_uuSAyAT:1759765272) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net/image_cache_thread.rs#L601)):*
The previous code was correct. The key words were "as well" :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10767#-:-KG2-PVs2jid3q4B_yYi:1458266033)*

**Comment by srm912** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/net/image_cache_thread.rs, line 601 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu3VBcNVam8j4guKAu:-KGExJ6U5CAvSARqobLK:1582758247) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net/image_cache_thread.rs#L601)):*
Hahaha!! I kinda missed them!! :) So does this mean, two `ResourceLoadInfo` messages need to be sent out. One with`DataAvailable` and another with `ResponseComplete`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10767)*

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/net/image_cache_thread.rs, line 601 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10767#-KFu3VBcNVam8j4guKAu:-KGFeC47AIx3GhhLgY_1:1798441257) ([raw file](https://github.com/servo/servo/blob/c83be39af50107cd11ebe2852880b7dc08402dfe/components/net/image_cache_thread.rs#L601)):*
Correct.

---

*[components/net/image_cache_thread.rs, line 605 \[r5\]](https://reviewable.io:443/reviews/servo/servo/10767#-KGFeXq8yWdfW23uschA:-KGFeXq8yWdfW23uschB:802542953) ([raw file](https://github.com/servo/servo/blob/b80c7b4e9edb117e28faee3a9052e77c306524e7/components/net/image_cache_thread.rs#L605)):*
Pretty sure this doesn't compile as written... add a `let`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10767#-:-KGFeeJQPMDUe7fRdGBh:1458266033)*

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10767#-:-KGHglgEQb9VeYeDhVQB:-1746383326)*

**Pull request merged**
