### PR TITLE
Move util::persistent_list to layout

### LINKED ISSUE #9694: Move util::persistent_list to layout
Files:
 * components/layout/floats.rs
 * components/layout/lib.rs
 * components/util/lib.rs
 * components/util/persistent_list.rs

### PR DESCRIPTION
**Pull request by timvandermeij**
Fixes #9694.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9713)

### CODE REVIEW

**Comment by nox** [comment]
```
./components/layout/floats.rs:11: use statement is not in alphabetical order
	expected: style::logical_geometry::{LogicalRect, LogicalSize, WritingMode}
	found: persistent_list::PersistentList
```

You need to reorder the imports in components/layout/floats.rs

**Comment by timvandermeij** [comment]
I have pushed a new commit where the import is now in the right order. `./mach test-tidy` passes locally for me, so hopefully it's better this way!

**Comment by nox** [comment]
@bors-servo retry

Git snafu.

**Pull request merged**
