### PR TITLE
Update WR (groove/ridge borders, mix-blend-mode opts)

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16612)

### CODE REVIEW

**Comment by glennw** [comment]
This will need squashing before merging - I just want to try and see if the webgl failures are now resolved on CI.

**Comment by glennw** [comment]
This passes CI now - a few minor API changes, and a couple of new test passes.

r? @emilio or anyone

**Comment by jdm** [comment]
@bors-servo: retry
* #16616

**Pull request merged**
