### PR TITLE
Fix #8502 by not printing the message which is known to be repeated m…

### LINKED ISSUE #8502: Investigate weird WPT suite timeout
https://github.com/servo/servo/pull/8147#issuecomment-156189674

### PR DESCRIPTION
**Pull request by jdm**
…illions of times.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8679)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@bors-servo retry
* #8676

**Comment by jdm** [comment]
@bors-servo: retry
* #8311

**Comment by jdm** [comment]
@bors-servo: retry
* #8676

**Pull request merged**
