### PR TITLE
fix #8461

### LINKED ISSUE #8461: Navigating back and forth leads to a panic
Similar to #8324

1. `./mach run -d http://news.ycombinator.com`
2. Click a link
3. `<backspace>`
4. Click a link
5. :boom:

[log](https://gist.githubusercontent.com/frewsxcv/2cbfa3e118bcaf568bbd/raw/85312cc36c77365baf00663b9bcf57ef6e6c8b20/gistfile1.txt)

### PR DESCRIPTION
**Pull request by peterkort**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9471)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r+
Good catch! Thanks!

**Comment by jdm** [comment]
@bors-servo: retry
* #7791

**Comment by KiChjang** [comment]
@bors-servo retry
* #9163

**Comment by KiChjang** [comment]
@bors-servo retry
* #8157, #9033

**Comment by KiChjang** [comment]
@bors-servo retry
* #9448

**Comment by KiChjang** [comment]
@bors-servo retry
* #7846

**Comment by Ms2ger** [comment]
Sorry for the bother; that was me preparing to do some work on our infrastructure. I'll retry this PR in a little bit.

**Comment by jdm** [comment]
@bors-servo: retry
* #7791

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #9504

**Comment by KiChjang** [comment]
@bors-servo retry
* #8191

**Comment by larsbergstrom** [comment]
@bors-servo retry
- https://github.com/servo/saltfs/issues/199

(out of disk space on build master)

**Pull request merged**
