### PR TITLE
Update fetch attributes to match the new spec

### PR DESCRIPTION
**Pull request by KiChjang**
This should make fetch match the spec more closely.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9675)

### CODE REVIEW

**Comment by KiChjang** [comment]
@nikkisquared Travis CI is complaining about the unit tests, specifically the line where it asserts the `ResponseType` to be `Basic`.

How is it possible? According to my fetch spec reading, during main fetch, the `ResponseTainting` should be set to `Opaque` because `request.mode` is `NoCORS`, so the resulting `ResponseType` should also be `Opaque`.

**Comment by jdm** [comment]
A more descriptive commit message might be nice here.

**Comment by jdm** [comment]
Nice improvements! There's one big issue around origins that I want to make sure we get right before merging, however.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/net/fetch/methods.rs, line 56 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9675#-KBUtdu18a3f64yPSLay:-KBUtdu18a3f64yPSLaz:994784255) ([raw file](https://github.com/servo/servo/blob/ef99a1c8f65f8728991cf863cef2f98a2157579b/components/net/fetch/methods.rs#L56)):*
This makes me uncomfortable, since it's unsafe by default. I'd prefer to either leave the origin alone or add an `unimplemented!()` to make it clear what's going on.

---

*[components/net_traits/request.rs, line 124 \[r2\]](https://reviewable.io:443/reviews/servo/servo/9675#-KBUuxPcVzWODkRDh6B4:-KBUuxPcVzWODkRDh6B5:1705622238) ([raw file](https://github.com/servo/servo/blob/88afe38092b9bb6320d01c94a9a239e8be284933/components/net_traits/request.rs#L124)):*
Due to my comment about not modifying the origin in the Client case, I think it's important to reinstate this argument to force callers to consider the origin in use. We could accept an Option value and use the Client  origin if an explicit URL origin isn't present.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9675#-:-KBUvIaIV647206ZAFdt:-1756883023)*

**Comment by jdm** [comment]
@bors-servo: r+
Thanks!

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9675#-:-KBY5C7nXVIi5mS3feU8:-1746383326)*

**Pull request merged**
