### PR TITLE
Issue #4933

### PR DESCRIPTION
**Pull request by nithinmurali**
implemented reparent_child and remove_from_parent ,  it is passing all tests also ; please review PR

### CODE REVIEW

**Comment by jdm** [comment]
Great work! I left some comments on Critic :)

**Comment by nithinmurali** [comment]
when i am changing code should i reset existing commits ? or just make changes and commit them ?

**Comment by jdm** [comment]
Please make additional commits. You can squash them once the changes are all approved and we're going to merge them.

**Comment by jdm** [comment]
Still planning to work on this, @nithinmurali?

**Comment by nithinmurali** [comment]
yes! sorry for the delay  :/

**Comment by jdm** [comment]
Not a problem! I just like to make sure that we take over any PRs that are abandoned by the original authors. A couple small changes and this will be ready to merge :)

**Comment by jdm** [comment]
@nithinmurali There are unaddressed comments in the Critic review; are you planning to continue working on this?

**Comment by metajack** [comment]
@pcwalton Assigned you to take next steps. It looks like we'll need to make the changes and get this landed ourselves.

**Comment by pcwalton** [comment]
Moved to #5482.

**Pull request closed without merging**
