### PR TITLE
Report CSS errors to script task for further processing.

### PR DESCRIPTION
**Pull request by jdm**
This was a missing piece from #8838.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8987)

### CODE REVIEW

**Comment by jdm** [comment]
This has a build error, apparently. I'll fix that.

**Comment by Ms2ger** [comment]
Fixed the tidy error for you

**Comment by jdm** [comment]
r? @glennw 
I'm just choosing randomly at this point. None of this code is really owned by anybody besides me.

**Comment by glennw** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/reporter.rs, line 17 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8987#-K79D86T8ARAjFYaEqbi:-K79D86T8ARAjFYaEqbj:-2131971726) ([raw file](https://github.com/servo/servo/blob/faa17b446f0c4f2e71dbd2955d03505947538f9c/components/script/reporter.rs#L17)):*
I don't know this code very well at all - why does it need to be Arc<Mutex<>> instead of just cloning the sender?

---

*[components/script/script_task.rs, line 1697 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8987#-K79D1VUoM13mzAmLp3_:-K79D1VUoM13mzAmLp3a:-420555923) ([raw file](https://github.com/servo/servo/blob/faa17b446f0c4f2e71dbd2955d03505947538f9c/components/script/script_task.rs#L1697)):*
Is there a particular reason to move this line from where it was?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8987)*

**Comment by jdm** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/reporter.rs, line 17 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8987#-K79D86T8ARAjFYaEqbi:-K79FYY-TaNR3f-VpLJY:126077147) ([raw file](https://github.com/servo/servo/blob/faa17b446f0c4f2e71dbd2955d03505947538f9c/components/script/reporter.rs#L17)):*
The error reporter needs to be Sync right now for reasons that aren't quite clear to me.

---

*[components/script/script_task.rs, line 1697 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8987#-K79D1VUoM13mzAmLp3_:-K79FiSeA8ug909sTSEb:2121476065) ([raw file](https://github.com/servo/servo/blob/faa17b446f0c4f2e71dbd2955d03505947538f9c/components/script/script_task.rs#L1697)):*
Previously, any CSS error messages that occurred before the "load" event were ignored by the devtools because it didn't know about the associated pipeline. This change corrects that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8987)*

**Comment by glennw** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[components/script/reporter.rs, line 17 \[r2\]](https://reviewable.io:443/reviews/servo/servo/8987#-K79D86T8ARAjFYaEqbi:-K79H2k154EibNr-3llz:-643704101) ([raw file](https://github.com/servo/servo/blob/faa17b446f0c4f2e71dbd2955d03505947538f9c/components/script/reporter.rs#L17)):*
Could we add a comment in the code to this effect?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8987)*

**Comment by glennw** [comment]
@jdm Looks good to me after adding a comment about the Sync requirement (or just skip that if you don't think it's necessary).

**Pull request merged**
