### PR TITLE
Make all interface objects share the same funToString

### LINKED ISSUE #9280: Make all interface objects share the same funToString in codegen
We should add a `&'static [u8]` field to the `NonCallbackInterfaceObjectClass` struct and find that at run-time to convert the interface objects to strings.

Files:
 * components/script/dom/bindings/codegen/CodegenRust.py
 * components/script/dom/bindings/interface.rs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #9280

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10096)

### CODE REVIEW

**Comment by nox** [comment]
-S-awaiting-review +S-fails-tidy +S-needs-code-changes 

Almost perfect.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/interface.rs, line 13 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10096#-KDNNXMAONYAfT2_vLSW:-KDNNXMAONYAfT2_vLSX:1499473399) ([raw file](https://github.com/servo/servo/blob/4915c90d04253ebd08de1b942619962a5e50405e/components/script/dom/bindings/interface.rs#L13)):*
```
./components/script/dom/bindings/interface.rs:13: missing space after ,
```

---

*[components/script/dom/bindings/interface.rs, line 83 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10096#-KDNNap__fgHI_ZDHvyj:-KDNNap__fgHI_ZDHvyk:899475348) ([raw file](https://github.com/servo/servo/blob/4915c90d04253ebd08de1b942619962a5e50405e/components/script/dom/bindings/interface.rs#L83)):*
Call it `fun_to_string_hook`, similarly to `has_instance_hook`.

---

*[components/script/dom/bindings/interface.rs, line 86 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10096#-KDNO1WRULAJYDnibu5A:-KDNO1WRULAJYDnibu5B:1154383269) ([raw file](https://github.com/servo/servo/blob/4915c90d04253ebd08de1b942619962a5e50405e/components/script/dom/bindings/interface.rs#L86)):*
Coerce into `*const libc::c_char`.

---

*[components/script/dom/bindings/interface.rs, line 102 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10096#-KDNNgAlu1rD8BiHhhsE:-KDNNgAlu1rD8BiHhhsF:1130674978) ([raw file](https://github.com/servo/servo/blob/4915c90d04253ebd08de1b942619962a5e50405e/components/script/dom/bindings/interface.rs#L102)):*
Nit: Uppercasee at start and period at end.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1899 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10096#-KDNNoNorIc5p3By-mN6:-KDNNoNorIc5p3By-mN7:345981401) ([raw file](https://github.com/servo/servo/blob/4915c90d04253ebd08de1b942619962a5e50405e/components/script/dom/bindings/codegen/CodegenRust.py#L1899)):*
Nit: reuse `name` here.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1900 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10096#-KDNNtRS0TBszREWSDhm:-KDNNtRS0TBszREWSDhn:1511702401) ([raw file](https://github.com/servo/servo/blob/4915c90d04253ebd08de1b942619962a5e50405e/components/script/dom/bindings/codegen/CodegenRust.py#L1900)):*
Nit: call this `representation`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10096#-:-KDNNYnJh3sLHQ0bonYm:-1471888375)*

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by nox** [comment]
-S-awaiting-review -S-fails-tidy +S-needs-code-changes 

One last change.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/bindings/interface.rs, line 84 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10096#-KDNlqSDb61Lfg4G43Z8:-KDNlqSDb61Lfg4G43Z9:-967439666) ([raw file](https://github.com/servo/servo/blob/d06598b2d730dca006eadf7c0601c8527313552c/components/script/dom/bindings/interface.rs#L84)):*
Nit: newline before `obj` and the return type.

---

*[components/script/dom/bindings/interface.rs, line 88 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10096#-KDNlbp90K8ChGgj0j6x:-KDNlbp90K8ChGgj0j6y:-1383471684) ([raw file](https://github.com/servo/servo/blob/d06598b2d730dca006eadf7c0601c8527313552c/components/script/dom/bindings/interface.rs#L88)):*
In this function, please assert that `js_class` isn't null, that `representation` ends with `'\0'` and that the return value of `JS_NewStringCopyZ` isn't null.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10096#-:-KDNln0iESw5uuc5YaAq:552770006)*

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/10096#-:-KDNtpIbXdg2Oe2Sj9Xf:1236647940)*

**Pull request merged**
