### PR TITLE
Update to latest rust-cssparser.

### PR DESCRIPTION
**Pull request by metajack**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6835)

### CODE REVIEW

**Comment by metajack** [comment]
r? @pcwalton 

This is to land your cssparser changes in Servo.

**Comment by jdm** [comment]
```


/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex4.html
----------------------------------------------------------------------
FAIL Canvas test: 2d.fillStyle.parse.invalid.hex4
/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex8.html
----------------------------------------------------------------------
FAIL Canvas test: 2d.fillStyle.parse.invalid.hex8
```

**Comment by Ms2ger** [comment]
Looks like the upstream tests need updating for the newly allowed syntax.

**Comment by metajack** [comment]
@ms2ger Tests updated. r?

I'm not sure why `--manifest-update` added the deletions it did; I didn't touch anything about those tests.

**Comment by Ms2ger** [comment]
Squash

**Comment by metajack** [comment]
@bors-servo r=Ms2ger

Rebased.

**Pull request merged**
