### PR TITLE
Implement the table section IDL attributes for HTML tables

### LINKED ISSUE #10506: Implement <table>.createTHead()
https://html.spec.whatwg.org/multipage/tables.html#dom-table-createthead

### PR DESCRIPTION
**Pull request by yoava333**
a pull request that solves #9769.
I fixed on review note, and couldn't reproduce the second one.

Fixes #10506.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/servo/servo/9980)

### CODE REVIEW

**Comment by ecoal95** [comment]
Three more tests passing, please update the expectations :)

```
Tests with unexpected results:
  ▶ Unexpected subtest result in /dom/nodes/getElementsByClassName-20.htm:
  └ PASS [expected FAIL] get elements in document then add element to collection

  ▶ Unexpected subtest result in /dom/nodes/getElementsByClassName-22.htm:
  └ PASS [expected FAIL] move item in collection order

  ▶ Unexpected subtest result in /dom/nodes/getElementsByClassName-25.htm:
  └ PASS [expected FAIL] verify spacing is handled correctly
```

**Comment by ecoal95** [comment]
The changes look good to me in general.

I haven't looked thoroughly through the spec yet, but I think we need more tests for this, since the only failing tests are interface tests and some other less-deeply-related tests.

@Ms2ger or @jdm should be able to correct me or confirm it.

**Comment by jdm** [comment]
Yes writing tests for each of the attributes is important.

**Comment by Ms2ger** [comment]
Tests should be added directly to our copy of the web-platform-tests under `tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/`. It's probably best to use the `./mach create-wpt` command to create them.

**Comment by yoava333** [comment]
I've rebased the code & updated the tests

**Comment by nox** [comment]
Thanks for your contribution! Almost there.

-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 3 files at r1, 3 of 3 files at r2, 3 of 4 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[components/script/dom/htmltableelement.rs, line 35 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIMqV-rtN8WmdJHj3o:-KDIMqV-rtN8WmdJHj3p:-923292213) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L35)):*
Define that in `HTMLTableElement::TBodies`.

---

*[components/script/dom/htmltableelement.rs, line 74 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIJ5-YIa3yniaawWfq:-KDIJ5-YIa3yniaawWfr:897443878) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L74)):*
```rust
self.upcast::<Node>().children().map(Root::downcast).find(|section| {
    section.upcast::<Element>().local_name() == atom
})
```

---

*[components/script/dom/htmltableelement.rs, line 83 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIJjrfgFEyJ9yiywOV:-KDIJjrfgFEyJ9yiywOW:-1315155274) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L83)):*
Nit: broken indentation.

---

*[components/script/dom/htmltableelement.rs, line 83 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIJlliwycj5rI96CUE:-KDIJlliwycj5rI96CUF:1727700533) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L83)):*
Nit: Put the where clause on its own line aligned with the others.

---

*[components/script/dom/htmltableelement.rs, line 86 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIK5PohAKu1v3JFtDz:-KDIK5PohAKu1v3JFtE-:-1104618685) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L86)):*
Make a short-circuiting return statement and unindent everything else.

---

*[components/script/dom/htmltableelement.rs, line 90 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDILl6ugJhuYOorkCeN:-KDILl6ugJhuYOorkCeO:-2141988264) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L90)):*
Nit: this is the same code as `delete_first_section_of_type`, so just call it.

---

*[components/script/dom/htmltableelement.rs, line 99 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIL7Ub0QBwNh-3DOjO:-KDIL7Ub0QBwNh-3DOjP:-1681666249) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L99)):*
Make the predicate take a `Node` and just do `let reference_node = node.children().find(reference_predicate);`.

---

*[components/script/dom/htmltableelement.rs, line 102 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIKfIFZ1X6JrrID73k:-KDIKfIFZ1X6JrrID73l:849666479) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L102)):*
Use `except` or `unwrap` instead of an explicit assertion.

---

*[components/script/dom/htmltableelement.rs, line 114 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDILb9C_05UB6zl20O9:-KDILb9C_05UB6zl20OA:2015130486) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L114)):*
Use a short-circuiting return statement.

---

*[components/script/dom/htmltableelement.rs, line 120 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDILyFVQopbkKcbfxB9:-KDILyFVQopbkKcbfxBA:-1323319330) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L120)):*
Nit: `&section` instead of `section.r()`.

---

*[components/script/dom/htmltableelement.rs, line 123 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDILsElBKLu4EE-sHiF:-KDILsElBKLu4EE-sHiG:527684079) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L123)):*
Use `except` or `unwrap`.

---

*[components/script/dom/htmltableelement.rs, line 190 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIM942S58AVHQ-f6oZ:-KDIM942S58AVHQ-f6o_:1649240831) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L190)):*
Nit: I would rather have you indent it like this:

```rust
self.set_first_section_of_type(&atom!("thead"), thead, |node| {
    !n.is::<HTMLTableCaptionElement>() && !n.is::<HTMLTableColElement>()
})
```

---

*[components/script/dom/htmltableelement.rs, line 216 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIMRlLTssIJSAynMHP:-KDIMRlLTssIJSAynMHQ:843362952) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L216)):*
Nit: same remark as in `SetTHead`, make a block for the closure so that you don't have to indent it to the infinity. You can also use short-circuiting and bind the local name to a variable in the case of `HTMLTableSectionElement` for readability.

---

*[tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tFoot.html, line 7 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDINBrBv5TQymrXwFwf:-KDINBrBv5TQymrXwFwg:-1363485407) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tFoot.html#L7)):*
Nit: please indent this correctly.

---

*[tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html, line 7 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDINq_hVE6JugYaHxIL:-KDINq_ipgpxlEYtDKP3:-1363485407) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html#L7)):*
Nit: please indent this correctly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9980#-:-KDIIp1RI3KKTJVS6PsW:927789805)*

**Comment by yoava333** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[components/script/dom/htmltableelement.rs, line 74 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIJ5-YIa3yniaawWfq:-KDPUgomeJwHJhPrrGzE:-1986091613) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L74)):*
the expression you prescribed doesn't compile, fixing it results in an expression as long the previous one. 

---

*[tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html, line 7 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDINq_hVE6JugYaHxIL:-KDJubmfYCRK5XzVa7Nx:1075296118) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html#L7)):*
I cannot, otherwise between each node i'll have a text node and that's a bit noisy for test, what do you think?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9980)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[components/script/dom/htmltableelement.rs, line 83 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIJjrfgFEyJ9yiywOV:-KDIKs7DWYJ-SirMrLvM:1245510951) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L83)):*
Indentation is still broken.

---

*[tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html, line 7 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDINq_hVE6JugYaHxIL:-KDTekERAg1M88PFhMC_:-1141839028) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html#L7)):*
Oh I see. I guess that's fine then.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9980)*

**Comment by eefriedman** [comment]
I would suggest adding a testcase like the following; it currently crashes with your patch.

```html
<table>
<thead id=y>
<td>
<table id=x>
<script>
var x = document.getElementById("x");
var y = document.getElementById("y");
x.tHead = y;
</script>
```

**Comment by yoava333** [comment]
@eefriedman added the test case, and fixed the bug by returning the error.

**Comment by nox** [comment]
-S-awaiting-review +S-needs-code-changes 

A few old and new nits.

---

Reviewed 2 of 3 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmltableelement.rs, line 90 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDILl6ugJhuYOorkCeN:-KEH6iLAC7l52WTIoxEj:1355881117) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L90)):*
This nit wasn't addressed yet.

---

*[components/script/dom/htmltableelement.rs, line 73 \[r7\]](https://reviewable.io:443/reviews/servo/servo/9980#-KEH6oT7DITxyNAYw6f1:-KEH6oT7DITxyNAYw6f2:-1980442572) ([raw file](https://github.com/servo/servo/blob/e343c2b19035611228ae36cf0a9adf4f9ef9f8c4/components/script/dom/htmltableelement.rs#L73)):*
You didn't make `P` take a `Node` yet.

---

*[components/script/dom/htmltableelement.rs, line 92 \[r7\]](https://reviewable.io:443/reviews/servo/servo/9980#-KEH6xBjR77uOhxpS6N5:-KEH6xBjR77uOhxpS6N6:1024581064) ([raw file](https://github.com/servo/servo/blob/e343c2b19035611228ae36cf0a9adf4f9ef9f8c4/components/script/dom/htmltableelement.rs#L92)):*
This can't fail. Please just use `unwrap` or `expect` on the result of `InsertBefore`.

---

*[components/script/dom/htmltableelement.rs, line 111 \[r7\]](https://reviewable.io:443/reviews/servo/servo/9980#-KEH7FQxX6C9NgVMwMLn:-KEH7FQxX6C9NgVMwMLo:-688364722) ([raw file](https://github.com/servo/servo/blob/e343c2b19035611228ae36cf0a9adf4f9ef9f8c4/components/script/dom/htmltableelement.rs#L111)):*
Why did you remove the `unreachable!` call here?

---

*[tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html, line 48 \[r7\]](https://reviewable.io:443/reviews/servo/servo/9980#-KEH7ZU0z2hXueXrSohJ:-KEH7ZU0z2hXueXrSohK:-826618679) ([raw file](https://github.com/servo/servo/blob/e343c2b19035611228ae36cf0a9adf4f9ef9f8c4/tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html#L48)):*
Please report the correct exception here instead of `null`.

---

*[tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html, line 52 \[r7\]](https://reviewable.io:443/reviews/servo/servo/9980#-KEH7WS3Apky6sxvD4kE:-KEH7WS3Apky6sxvD4kF:-826618679) ([raw file](https://github.com/servo/servo/blob/e343c2b19035611228ae36cf0a9adf4f9ef9f8c4/tests/wpt/web-platform-tests/html/semantics/tabular-data/the-table-element/tHead.html#L52)):*
Please report the correct exception here instead of `null`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9980#-:-KEH7axbFcuWMh_zAJIs:1078563130)*

**Comment by KiChjang** [comment]
@yoava333 Is this still being worked on?

**Comment by yoava333** [comment]
@KiChjang yes, bit of busy week, will continue in a couple of days.

**Comment by yoava333** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[components/script/dom/htmltableelement.rs, line 99 \[r5\]](https://reviewable.io:443/reviews/servo/servo/9980#-KDIL7Ub0QBwNh-3DOjO:-KF-gFih15D3ODvP_C4B:1567988687) ([raw file](https://github.com/servo/servo/blob/6d556152291851a744ef186e8f82d29633d6b973/components/script/dom/htmltableelement.rs#L99)):*
We talked about this on IRC, and agreed this change is not needed.

---

*[components/script/dom/htmltableelement.rs, line 73 \[r7\]](https://reviewable.io:443/reviews/servo/servo/9980#-KEH6oT7DITxyNAYw6f1:-KF-I2eQAOpWsiL03Z33:-336788287) ([raw file](https://github.com/servo/servo/blob/e343c2b19035611228ae36cf0a9adf4f9ef9f8c4/components/script/dom/htmltableelement.rs#L73)):*
I didn't make P take a Node because the function needs a 

---

*[components/script/dom/htmltableelement.rs, line 92 \[r7\]](https://reviewable.io:443/reviews/servo/servo/9980#-KEH6xBjR77uOhxpS6N5:-KF-Bo_i_Qp0C_UI7uyJ:381930258) ([raw file](https://github.com/servo/servo/blob/e343c2b19035611228ae36cf0a9adf4f9ef9f8c4/components/script/dom/htmltableelement.rs#L92)):*
I thought so too. but eefriedman pointed out that this can fail, and I've added the test case to the commit.
https://github.com/servo/servo/pull/9980#issuecomment-201143986

---

*[components/script/dom/htmltableelement.rs, line 111 \[r7\]](https://reviewable.io:443/reviews/servo/servo/9980#-KEH7FQxX6C9NgVMwMLn:-KF-DLwESEXUdTdZIjj3:975344493) ([raw file](https://github.com/servo/servo/blob/e343c2b19035611228ae36cf0a9adf4f9ef9f8c4/components/script/dom/htmltableelement.rs#L111)):*
by mistake, when I made the change for InsertBefore I saw that this is a flow that InsertBefore is called, but you are right, it's not possible to get an error there. So I restored the unreachable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9980)*

**Comment by emilio** [comment]
Review status: 3 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[components/script/dom/htmltableelement.rs, line 92 \[r7\]](https://reviewable.io:443/reviews/servo/servo/9980#-KEH6xBjR77uOhxpS6N5:-KF15idD3ilxnJ_hjt3o:-925661833) ([raw file](https://github.com/servo/servo/blob/e343c2b19035611228ae36cf0a9adf4f9ef9f8c4/components/script/dom/htmltableelement.rs#L92)):*
`try!(node.InsertBefore(..))` then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9980)*

**Comment by yoava333** [comment]
@emilio done

**Comment by nox** [comment]
Just needs a rebase and then r=me.

-S-awaiting-review 

---

Reviewed 5 of 6 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/9980#-:-KF9wSCkbtdjqkdMroZS:-316694382)*

**Pull request merged**
