### PR TITLE
Adding sync method to update attr from inline style updates

### PR DESCRIPTION
**Pull request by SimonSapin**
**Do not merge yet.**

Rebase of #9410

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10926)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
error: Unable to update https://github.com/emilio/angle?branch=servo#eefe3506

Caused by:
  failed to clone into: C:/buildbot/slave/windows/build/.cargo\git\db\angle-7cd76ec19448e619

Caused by:
  [2/-1] Failed to read data: The server returned an invalid or unrecognized response
```

@bors-servo retry

* Network failure?

**Comment by SimonSapin** [comment]
@craftytrickster I can reproduce these locally :/ ↑

**Comment by craftytrickster** [comment]
I've placed this back into the original PR

**Pull request closed without merging**
