### PR TITLE
Make NamedNodeMap's named properties unenumerable

### PR DESCRIPTION
**Pull request by nox**
https://dom.spec.whatwg.org/#dom-htmlcollection-item

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9067)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I'm curious if this is the design we want. Are there any interfaces with some name properties enumerable and some unenumerable? What does Gecko do?

**Comment by nox** [comment]
@Ms2ger Gecko does some strange things, but @annevk (or maybe @heycam) confirmed that there are no interfaces defined like that in the platform. I opened an issue against WebIDL to discuss this.

https://github.com/heycam/webidl/issues/82

**Comment by nox** [comment]
@bors-servo retry

Git snafu.

**Comment by nox** [comment]
@bors-servo retry

Git broken for real?

**Comment by Wafflespeanut** [comment]
@bors-servo retry

git updating problem...

**Comment by Wafflespeanut** [comment]
Hmm, no, the logs show something else...

    Upon execvpe git ['git', '--version'] in environment id 140445980094544
    :Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 403, in _fork
        path, uid, gid, executable, args, environment)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 453, in _execChild
        os.execvpe(executable, args, environment)
      File "/usr/lib/python2.7/os.py", line 353, in execvpe
        _execvpe(file, args, env)
      File "/usr/lib/python2.7/os.py", line 380, in _execvpe
        func(fullname, *argrest)
    OSError: [Errno 2] No such file or directory

**Comment by larsbergstrom** [comment]
@bors-servo retry
- https://github.com/servo/saltfs/pull/222

**Comment by KiChjang** [comment]
```

Ran 4601 tests finished in 236.0 seconds.
  • 4597 ran as expected. 1376 tests skipped.
  • 4 tests had unexpected subtest results

Tests with unexpected results:
  ▶ Unexpected subtest result in /dom/nodes/Document-getElementsByTagName.html:
  └ PASS [expected FAIL] hasOwnProperty, getOwnPropertyDescriptor, getOwnPropertyNames

  ▶ Unexpected subtest result in /dom/nodes/Element-getElementsByTagName.html:
  └ PASS [expected FAIL] hasOwnProperty, getOwnPropertyDescriptor, getOwnPropertyNames

  ▶ Unexpected subtest result in /dom/nodes/attributes.html:
  └ PASS [expected FAIL] Own property correctness with basic attributes

  ▶ Unexpected subtest result in /dom/nodes/attributes.html:
  └ PASS [expected FAIL] Own property correctness with non-namespaced attribute before same-name namespaced one

  ▶ Unexpected subtest result in /dom/nodes/attributes.html:
  └ PASS [expected FAIL] Own property correctness with namespaced attribute before same-name non-namespaced one

  ▶ Unexpected subtest result in /dom/nodes/attributes.html:
  └ PASS [expected FAIL] Own property correctness with two namespaced attributes with the same name-with-prefix

  ▶ Unexpected subtest result in /html/dom/documents/dom-tree-accessors/document.forms.html:
  └ PASS [expected FAIL] document.forms iteration
```
Is this intended?

**Comment by jdm** [comment]
If you rebase this and address my single comment, I'll hop on this!

**Comment by nox** [comment]
@bors-servo retry

Just Git things.

**Pull request merged**
