### PR TITLE
Thread vslatestinstalled feature to the top

### PR DESCRIPTION
**Pull request by Manishearth**
I've been building with this to get pure-VS 2019 to work. Ideally we don't need any extra flags, but for now at least worth getting into master so I don't have to cherry pick this all the time.

r? @jdm

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
@bors-servo retry
* #24726

**Comment by jdm** [comment]
@bors-servo retry
#24726

**Comment by jdm** [comment]
@bors-servo retry
* network

**Comment by Manishearth** [comment]
@bors-servo retry

 - reftest intermittent

**Pull request merged**
