### PR TITLE
style: Adjust float if the element is positioned per CSS 2.1 section 9.7

### PR DESCRIPTION
**Pull request by emilio**
We've found crashes related to this in Gecko.

r? @simonsapin or @heycam

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15730)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo try

 * I _hope_ we have tests for this.

**Comment by emilio** [comment]
So we don't seem to, given those failures seem intermittent.

I'll write a wpt test. Also, I guess I'll look at any code that could deal with this in layout to simplify it.

**Comment by emilio** [comment]
Seems like the layout code that deals with this (in `components/layout/construct.rs`) ignores the float value for absolutely positioned elements already, so I don't think I can simplify it further.

This should be ready for review.

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/15730#-:-KdqjAZeRIx-gmSpYeyM:bkg9nno)*

**Comment by SimonSapin** [comment]
```
bash ./etc/ci/manifest_changed.sh
diff --git a/tests/wpt/mozilla/meta/MANIFEST.json b/tests/wpt/mozilla/meta/MANIFEST.json
index 63e821e..9ecaa48 100644
--- a/tests/wpt/mozilla/meta/MANIFEST.json
+++ b/tests/wpt/mozilla/meta/MANIFEST.json
@@ -20902,7 +20902,7 @@
    "support"
   ],
   "css/float-abspos.html": [
-   "d5e1649c88102f27da5fe1ac16715cfee7f70f84",
+   "d34a9ce0be290bc3c46aa80eb136a91460957346",
    "testharness"
   ],
   "css/float_clearance_a.html": [
program finished with exit code 1

**Comment by emilio** [comment]
@bors-servo r=SimonSapin

Arg, forgot that I can't do last-minute fixups to the tests without updating the manifest, sigh.

**Comment by emilio** [comment]
Fun:

> IOError: CRC check failed 0xc78a87b != 0x61f360b5L

@bors-servo retry

**Comment by bzbarsky** [comment]
@emilio I assume we don't need mOriginalFloat bits because these structs will never land in nsRuleNode::ComputeDisplayData or nsStyleDisplay::CalcDifference?

**Comment by emilio** [comment]
@bzbarsky yeah, that was my analysis (arguably post-landing, I just realised we had that bit in Gecko) at https://bugzilla.mozilla.org/show_bug.cgi?id=1342738#c3

**Comment by heycam** [comment]
> I assume we don't need mOriginalFloat bits because these structs will never land in nsRuleNode::ComputeDisplayData or nsStyleDisplay::CalcDifference?

The structs will land in CalcDifference, but we only compare mOriginalFloat to return a NeutralChange hint, which stylo doesn't need to care about.

**Pull request merged**
