### PR TITLE
Add a sessionavailable event that allows content to enter an XR session without a user gesture

### PR DESCRIPTION
**Pull request by asajeffrey**
This allows servo to implement immersive web apps. https://immersive-web.github.io/webxr/#application-launch

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because I'm not sure we should have a WPT for something this non-standard.

### CODE REVIEW

**Comment by asajeffrey** [comment]
Should I add a test in the `mozilla` test directory?

**Comment by jdm** [comment]
That sounds reasonable.

**Review by jdm — APPROVED** [review]
An automated test would be nice.

**Comment by asajeffrey** [comment]
Added a test. @bors-servo r=jdm

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
```
./tests/wpt/mozilla/tests/webxr/sessionavailable.html:13: tab on line
./tests/wpt/mozilla/tests/webxr/sessionavailable.html:14: tab on line
./tests/wpt/mozilla/tests/webxr/sessionavailable.html:15: tab on line
./tests/wpt/mozilla/tests/webxr/sessionavailable.html:16: tab on line
```

**Comment by asajeffrey** [comment]
Grr, thank you emacs. @bors-servo r=jdm

**Pull request merged**
