### PR TITLE
Implement DOMPoint.fromPoint

### LINKED ISSUE #23710: Implement DOMPoint.fromPoint
Implement DOMPoint.fromPoint as the spec says: https://drafts.fxtf.org/geometry/#dom-dompointreadonly-frompoint

### PR DESCRIPTION
**Pull request by saschanaz**
Implements DOMPoint.fromPoint and fixes codegen to use default value when an optional dictionary member got `undefined`.

PS: The codegen change is about:

```webidl
dictionary MyDictionary {
  optional short myMember = 0;
  short anotherMember;
}

[Exposed=Window, Constructor]
interface MyInterface {
  void myMethod(optional MyDictionary myDict);
}; 
```

```js
// The following two must behave same
new MyInterface().myMethod({ myMember: undefined, anotherMember = 0 });
new MyInterface().myMethod({ anotherMember = 0 });
```

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #23710 

- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23711)

### CODE REVIEW

**Comment by saschanaz** [comment]
I think the codegen change will affect other tests... Can someone allow me @bors-servo test=wpt ?

**Comment by CYBAI** [comment]
@bors-servo try=wpt

(I can only help you to try 😂)

**Comment by saschanaz** [comment]
@CYBAI How did you get the access? Are you in Mozilla?

**Comment by CYBAI** [comment]
> @CYBAI How did you get the access?

You might need to send a PR to the `saltfs` repo and ask members' approval.
My `try` permission was added at servo/saltfs#775 by @emilio.

> Are you in Mozilla?

Nope, I'm contributor :)

**Comment by saschanaz** [comment]
Thanks! Opened https://github.com/servo/saltfs/pull/971, although I don't know there is a documented qualification...

**Comment by saschanaz** [comment]
This PR somehow fixed an harness failure on https://w3c-test.org/webaudio/the-audio-api/the-audioparam-interface/k-rate-oscillator.html and found 6 more tests, 3 failing. Not sure how this fixed the error, can I open JS console or attach external JS debuggers on Servo to investigate this? @CYBAI?

**Comment by CYBAI** [comment]
While you do code changes to WPT files, @servo-wpt-sync will open an upstream PR for the changes.

Personally, I think it's a little annoying to open and close upstream WPT PRs only with consoles so there's a related issue in servo-automation/upstream-wpt-sync-webhook#27.

I'm not sure if the codegen somehow fixes the `webaudio` tests. Maybe need some investigation. 👀

**Comment by jdm** [comment]
It is possible to attach the Firefox JS console to Servo (but not the JS debugger): https://github.com/servo/servo/wiki/Devtools

**Comment by CYBAI** [comment]
Oops, I misunderstood what @saschanaz said! Thanks @jdm!

**Comment by saschanaz** [comment]
Okay, now I got it.

0. Servo don't implement `OfflineAudioContext.numberOfChannels` so it returns `undefined`
1. The test passes `context.numberOfChannels` value as a dictionary argument
2. Our codegen currently incorrectly converts explicit `undefined` number value as `NaN` and thus causes IndexSizeError.
3. That error shadows some tests, and those are now explicitly failing

**Comment by saschanaz** [comment]
Multiple tests now switches their status from ERROR to OK. Can I autofix those ini files rather than manually writing correct values?

**Comment by saschanaz** [comment]
Had to update them manually because of crashing on Windows 🤔

**Comment by ferjm** [comment]
> Okay, now I got it.
> 
>     1. Servo don't implement `OfflineAudioContext.numberOfChannels` so it returns `undefined`
> 

FWIW there is no `OfflineAudioContext.numberOfChannels` property defined by the [spec](https://webaudio.github.io/web-audio-api/#OfflineAudioContext). This looks like a test bug to me. [This line](https://github.com/web-platform-tests/wpt/blob/7c50c216081d6ea3c9afe553ee7b64534020a1b2/webaudio/the-audio-api/the-audioparam-interface/k-rate-oscillator.html#L35) should be:

```rust
context, {numberOfInputs: context.destination.channelCount});
```

**Comment by CYBAI** [comment]
@bors-servo try=wpt
 
> PS: Oh, it seems the list is not updated yet..

Yes, you will need to wait someone deploy the change 👀

**Comment by saschanaz** [comment]
>FWIW there is no OfflineAudioContext.numberOfChannels property defined by the spec. This looks like a test bug to me. This line should be:

Good catch, but maybe we can just remove it as Chrome passes all tests without that property?

**Comment by ferjm** [comment]
> > FWIW there is no OfflineAudioContext.numberOfChannels property defined by the spec. This looks like a test bug to me. This line should be:
> 
> Good catch, but maybe we can just remove it as Chrome passes all tests without that property?

Chrome seems to be missing some tests as well https://wpt.fyi/results/webaudio/the-audio-api/the-audioparam-interface/k-rate-oscillator.html?label=master&label=experimental

**Comment by saschanaz** [comment]
Filed https://github.com/web-platform-tests/wpt/issues/17659.

**Comment by ferjm** [comment]
Thanks. You can directly fix the test in Servo's tree (within this PR) and it will be synchronized upstream.

**Comment by saschanaz** [comment]
Oh, in that case, I'm pushing the change now!

**Comment by saschanaz** [comment]
And please trigger try=wpt 🙏

**Comment by ferjm** [comment]
Fixed the HTTP 500 issue.

@bors-servo try=wpt

**Comment by jdm** [comment]
@Manishearth These changes seem related to the investigations you did into dictionaries recently.

**Comment by Manishearth** [comment]
We shouldn't fix codegen here, we should use `optional DomPointInit init = null`

Webidl maintains a distinction between null/defaulted and undefined for this.

**Comment by saschanaz** [comment]
@Manishearth It's not about dictionary itself, it's about dictionary fields, where `undefined` should be same as non-defined.

**Comment by Manishearth** [comment]
Right, but it's not clear that dictionaries themselves have a default value if all fields are optional. From other discussions it _seems_ like arguments and dictionary members behave the same way around this.

**Comment by saschanaz** [comment]
>but it's not clear that dictionaries themselves have a default value if all fields are optional

Hmm, I think you mean #23703, where the defaulting is explicit.

**Comment by Manishearth** [comment]
Right, null works too, but that syntax is more clear.

**Comment by saschanaz** [comment]
Do you think the codegen change here is good then? I think the `= {}` thing can be done as a followup.

**Comment by Manishearth** [comment]
No, you should not have codegen changes here, you should use `null`. The `{}` issue is purely cosmetic, you can get that effect with `null` already, it just looks weird.

**Comment by saschanaz** [comment]
@Manishearth Err... That change is not about `= null` or `= {}`, it's about:

```webidl
dictionary MyDictionary {
  optional short myMember = 0;
}

[Exposed=Window, Constructor]
interface MyInterface {
  void myMethod(optional MyDictionary myDict);
}; 
```

```js
// The following two must behave same
new MyInterface().myMethod({ myMember: undefined });
new MyInterface().myMethod({});
```

**Comment by Manishearth** [comment]
Your change makes the following two things behave the same:

```js
DOMPoint.fromPoint();
DOMPoint.fromPoint({});
```

this is supposed to be the case for fromPoint, but not in general, you need to specify `= {}` or `= null` in the IDL to make this work. There should not be codegen changes here.

**Comment by saschanaz** [comment]
>Your change makes the following two things behave the same:
>```js
>DOMPoint.fromPoint();
>DOMPoint.fromPoint({});
>```

This PR is changing `getMemberConversion` part but that's not about member conversion, no?

**Comment by Manishearth** [comment]
https://mozilla.logbot.info/servo/20190705#c16440383

In fact it seems like we should be rejecting trailing optional dictionaries that _don't_ have `= {}` in the IDL

**Comment by saschanaz** [comment]
>In fact it seems like we should be rejecting trailing optional dictionaries that don't have = {} in the IDL

Yup, that what #23703 is.

**Comment by saschanaz** [comment]
Um, in other words, introducing `= {}` won't fix the problem I fixed here.

**Comment by Manishearth** [comment]
What error do you get when you remove the codegen changes and add null?

**Comment by jdm** [comment]
For future reference in case some changes are reverted:
* TransitionEventInit
* DOMMatrixInit
* DOMPoint
* OfflineAudioContext
* StorageEvent

**Comment by saschanaz** [comment]
>What error do you get when you remove the codegen changes and add null?

`DOMPoint.fromPoint({ x: undefined })` behaves like `DOMPoint.fromPoint({ x: NaN })` and test fails.

**Comment by Manishearth** [comment]
Hmmm

**Comment by saschanaz** [comment]
As far as I see, the codegen currently consider `undefined` as a valid *dict member* value and tries converting it as `unrestricted double`, while it should instead ignore it and defaults to `0`. Notice *dict member* not dict...

**Comment by Manishearth** [comment]
Oh, I understand now. I misread `rval` as being for the type and couldn't see the context on my phone.

Yeah this fix makes sense. We should still have an `=null` here, though.

**Review by Manishearth — APPROVED** [review]
r=me with the `= null`

**Comment by Manishearth** [comment]
Oh, please squash your commits as well.

**Pull request merged**
