### PR TITLE
tidy.py: remove duplicate code patterns in `check_rust(file_name, lines)`

### PR DESCRIPTION
**Pull request by dsprenkels**
This is an attempt at a reasonable fix for #8733.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9073)

### CODE REVIEW

**Comment by frewsxcv** [comment]
*[python/tidy.py, line 391 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9073#-K6b3Se20ec6Zj0r49_I:-K6b3Se20ec6Zj0r49_J:41971297) ([raw file](https://github.com/servo/servo/blob/5dbfce24e7eda7a4ba0d58a32cf85fe1e47c9ed8/python/tidy.py#L391)):*
`if match.group(1) != '=':`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9073)*

**Comment by Wafflespeanut** [comment]
Nice work! Currently, some nits (will take a deeper look soon)...

-S-awaiting-review +S-needs-code-changes

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[python/tidy.py, line 327 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9073#-K6b7s46--9cD-dp87fY:-K6b7s46--9cD-dp87fZ:-631577128) ([raw file](https://github.com/servo/servo/blob/5dbfce24e7eda7a4ba0d58a32cf85fe1e47c9ed8/python/tidy.py#L327)):*
Instead of indexing the tuple, let's make this `rule, msg, filter_func` for more readability, and add a `None` to the tuple, so that we just do

``` python
for rule, msg, filter_func in ...
    if filter_func and ...
```

---

*[python/tidy.py, line 335 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9073#-K6bAGrg183fz0bn5cG1:-K6bAGrhKPl6MNmFdq4g:-2140028328) ([raw file](https://github.com/servo/servo/blob/5dbfce24e7eda7a4ba0d58a32cf85fe1e47c9ed8/python/tidy.py#L335)):*
Since we're slicing everything (see below), this could also be the same.

---

*[python/tidy.py, line 352 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9073#-K6b8SYOSSdNzZPdGKH6:-K6b8SYPH0qOUQgKyJIk:-64978226) ([raw file](https://github.com/servo/servo/blob/5dbfce24e7eda7a4ba0d58a32cf85fe1e47c9ed8/python/tidy.py#L352)):*
This kind of slicing doesn't make any sense sometimes. Maybe add a comment, something like, "to filter the imports from the `use` keyword and trailing semicolon"

(I'm surprised there wasn't a comment about this)

---

*[python/tidy.py, line 371 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9073#-K6b9MFFoKgTzp68H83t:-K6b9MFGxa9xFPmYeWmH:167261163) ([raw file](https://github.com/servo/servo/blob/5dbfce24e7eda7a4ba0d58a32cf85fe1e47c9ed8/python/tidy.py#L371)):*
ditto on commenting about the weird slicing...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9073#-:-K6b7itTvE5RjrRIWNEa:-1824449936)*

**Comment by dsprenkels** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[python/tidy.py, line 327 \[r1\]](https://reviewable.io:443/reviews/servo/servo/9073#-K6b7s46--9cD-dp87fY:-K6cSsXJ57aR1vG_J5iK:2021898465) ([raw file](https://github.com/servo/servo/blob/5dbfce24e7eda7a4ba0d58a32cf85fe1e47c9ed8/python/tidy.py#L327)):*
Good point, but I think I'll use a no-op function, so that we don't even have to check if filter_funct is None.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9073)*

**Comment by Wafflespeanut** [comment]
:lgtm: Thanks for doing this :)
-S-awaiting-review 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9073#-:-K6qgJBNcFD3DX3oaeKp:1382303309)*

**Comment by Wafflespeanut** [comment]
Squash it and we'll land it :)

**Pull request merged**
