### PR TITLE
Handle !important in keyframe

### PR DESCRIPTION
**Pull request by hiikezoe**
https://bugzilla.mozilla.org/show_bug.cgi?id=1400926

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18572)

### CODE REVIEW

**Comment by hiikezoe** [comment]
This has been already reviewed by Emilio on the bugzilla, but I'd like him to re-check it again here since I might be misunderstanding about what the 'wrap' means in the bugzilla comment https://bugzilla.mozilla.org/show_bug.cgi?id=1400926#c29

r? @emilio

**Comment by emilio** [comment]
Looks great, thanks hiro!

**Review by emilio — APPROVED** [review]

**Pull request merged**
