### PR TITLE
Improve support of limited unsigned long attributes

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5923)

### CODE REVIEW

**Comment by nox** [comment]
Blocked by https://github.com/w3c/web-platform-tests/pull/1802.

**Comment by nox** [comment]
The WPT PR was wrong and this one is thus now ready to go.

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/script/dom/attr.rs @ r1
- components/script/dom/element.rs @ r1
- components/script/dom/htmlinputelement.rs @ r1
- components/script/dom/htmltablecellelement.rs @ r3
- components/script/dom/htmltextareaelement.rs @ r1
- components/script/dom/macros.rs @ r1
- components/script/dom/webidls/HTMLInputElement.webidl @ r1
- components/script/dom/webidls/HTMLTableCellElement.webidl @ r3
- components/script/dom/webidls/HTMLTextAreaElement.webidl @ r1
- tests/wpt/metadata/html/dom/interfaces.html.ini @ r1
- tests/wpt/metadata/html/dom/reflection-embedded.html.ini @ r1
- tests/wpt/metadata/html/dom/reflection-forms.html.ini @ r1
- tests/wpt/metadata/html/dom/reflection-tabular.html.ini @ r1
- tests/wpt/metadata/html/rendering/bindings/the-textarea-element-0/cols-zero.html.ini @ r1
- tests/wpt/metadata/html/rendering/bindings/the-textarea-element-0/rows-zero.html.ini @ r1

---

<sup>**[components/script/dom/attr.rs, line 57 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5923#-JoeMl4qgc31-45cms4_)** ([raw file](https://github.com/servo/servo/blob/650fdbaec82a50d58c133659634fca0bba16bb82/components/script/dom/attr.rs#L57)):</sup>
Spec link, if possible.

---

<sup>**[components/script/dom/attr.rs, line 67 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5923#-JoeMmOns5nbmkD0Pzwo)** ([raw file](https://github.com/servo/servo/blob/650fdbaec82a50d58c133659634fca0bba16bb82/components/script/dom/attr.rs#L67)):</sup>
Spec link, if possible.

---

<sup>**[components/script/dom/htmltablecellelement.rs, line 5 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5923#-JoeJyBRNWgBKtXaXjvB)** ([raw file](https://github.com/servo/servo/blob/650fdbaec82a50d58c133659634fca0bba16bb82/components/script/dom/htmltablecellelement.rs#L5)):</sup>
nit: keep this with the other dom::bindings::codegen import.

---

<sup>**[components/script/dom/macros.rs, line 158 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5923#-JoeMsWFDhXqTh60F6bI)** ([raw file](https://github.com/servo/servo/blob/650fdbaec82a50d58c133659634fca0bba16bb82/components/script/dom/macros.rs#L158)):</sup>
Spec link, if possible.

---

<sup>**[components/script/dom/macros.rs, line 179 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5923#-JoeMu2jVkuNswMwYrTe)** ([raw file](https://github.com/servo/servo/blob/650fdbaec82a50d58c133659634fca0bba16bb82/components/script/dom/macros.rs#L179)):</sup>
Spec link, if possible.

---

<sup>**[components/script/dom/webidls/HTMLInputElement.webidl, line 38 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5923#-JoeNlpcjcyRYbVGaRIE)** ([raw file](https://github.com/servo/servo/blob/650fdbaec82a50d58c133659634fca0bba16bb82/components/script/dom/webidls/HTMLInputElement.webidl#L38)):</sup>
nit: retain the whitespace, only remove the leading //

---

<sup>**[components/script/dom/webidls/HTMLTableCellElement.webidl, line 8 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5923#-JoeNqNY77gLX8KH41wF)** ([raw file](https://github.com/servo/servo/blob/650fdbaec82a50d58c133659634fca0bba16bb82/components/script/dom/webidls/HTMLTableCellElement.webidl#L8)):</sup>
nit: retain whitespace

---

<sup>**[components/script/dom/webidls/HTMLTextAreaElement.webidl, line 11 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5923#-JoeNsKVB4v2AkGGHpse)** ([raw file](https://github.com/servo/servo/blob/650fdbaec82a50d58c133659634fca0bba16bb82/components/script/dom/webidls/HTMLTextAreaElement.webidl#L11)):</sup>
nit: retain whitespace

---

<sup>**[components/script/dom/webidls/HTMLTextAreaElement.webidl, line 23 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5923#-JoeNt8_eFrbbWS10iOj)** ([raw file](https://github.com/servo/servo/blob/650fdbaec82a50d58c133659634fca0bba16bb82/components/script/dom/webidls/HTMLTextAreaElement.webidl#L23)):</sup>
nit: retain whitespace

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5923)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-squash 

---

Reviewed files:
- components/script/dom/attr.rs @ r4
- components/script/dom/htmltablecellelement.rs @ r4
- components/script/dom/webidls/HTMLInputElement.webidl @ r4
- components/script/dom/webidls/HTMLTableCellElement.webidl @ r4
- components/script/dom/webidls/HTMLTextAreaElement.webidl @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5923)

**Pull request merged**
