### PR TITLE
Split up ScriptMsg into three variants, WorkerScriptMsg, ScriptMsg...

### PR DESCRIPTION
**Pull request by wldcordeiro**
... and MainThreadScriptMsg, works towards closing #3734

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5175)

### CODE REVIEW

**Comment by jdm** [comment]
Hmm, I'm not sure what happened here, but the other commits you made aren't being picked up by our review tool, Critic. I left comments on that review, and I prefer that design over the one here - I believe the change to ScriptChan that I've requested will clean up many of the same issues that your subsequent changes did, and give us better type-safety too (ie. allowing us to remove the wildcard branch from the dedicated worker event loop).

**Comment by wldcordeiro** [comment]
@jdm So you prefer the design that was in 5ef3631?

**Comment by jdm** [comment]
Yep! I think a bunch of the verbosity will disappear with the ScriptChan change.

**Comment by wldcordeiro** [comment]
@jdm Alright I'm going to revert to that commit and then pull the upstream changes for the PR. Should have it in tomorrow.

**Comment by wldcordeiro** [comment]
One thing I'm still not 100% sure on is what variants belong to which enums. This is how my three look currently. 

```rust
pub enum CommonScriptMsg {
    /// Fires a JavaScript timeout
    /// TimerSource must be FromWindow when dispatched to ScriptTask and
    /// must be FromWorker when dispatched to a DedicatedGlobalWorkerScope
    FireTimer(TimerSource, TimerId),
    /// Generic message that encapsulates event handling.
    RunnableMsg(Box<Runnable+Send>),
    /// A DOM object's last pinned reference was removed (dispatched to all tasks).
    RefcountCleanup(TrustedReference),
    /// The final network response for a page has arrived.
    PageFetchComplete(PipelineId, Option<SubpageId>, LoadResponse),
}

pub enum MainThreadScriptMsg {
    /// Acts on a fragment URL load on the specified pipeline (only dispatched
    /// to ScriptTask).
    TriggerFragment(PipelineId, String),
    /// Begins a content-initiated load on the specified pipeline (only
    /// dispatched to ScriptTask).
    TriggerLoad(PipelineId, LoadData),
    /// Notifies the script that a window associated with a particular pipeline
    /// should be closed (only dispatched to ScriptTask).
    ExitWindow(PipelineId),
    /// Common Variants to all ScriptMsg types
    Common(CommonScriptMsg),
}

pub enum WorkerScriptMsg {
    /// Message sent through Worker.postMessage (only dispatched to
    /// DedicatedWorkerGlobalScope).
    DOMMessage(StructuredCloneData),
    /// Common Variants to all ScriptMsg types
    Common(CommonScriptMsg),
}
```
There are places where ScriptChan's send are used but with things like `TriggerLoad` which if they're part of the MainThreadScriptMsg will cause errors because ScriptChan's send expects a CommonScriptMsg. 

Thanks for all the help @jdm

**Comment by jdm** [comment]
PageFetchComplete belongs to MainThreadScriptMsg, but the rest look right. It looks like the script_chan method on Window should return NonWorkerScriptChan instead, to alleviate the particular problem you refer to.

**Comment by jdm** [comment]
Additionally, Window should store a NonWorkerScriptChan to help facilitate that :)

**Comment by metajack** [comment]
@wldcordeiro How's this coming along?

**Comment by metajack** [comment]
Assigning @jdm since he did the initial review.

**Comment by wldcordeiro** [comment]
Sorry for the delay I've been rather busy. I'm going to close this PR because I'm taking a different approach to this and don't want to dirty the commit history. Expect another PR soon.

**Pull request closed without merging**
