### PR TITLE
Stop using JS<T> in layout.

### PR DESCRIPTION
**Pull request by tetsuharuohzeki**
#4571

### CODE REVIEW

**Comment by saneyuki** [comment]
This remains of some import `JS<T>` in layout crate (but they are almost used for type annotations). If we remove them, we need to add implement some methods for `LayoutJS<T>`. e.g.:

* [`JS<Node>::from_trusted_node_address()`](https://github.com/servo/servo/blob/3897547bc2ef85b8c1797ae6c915121c36873cac/components/script/dom/bindings/js.rs#L148))
* `BarCast::to_js()` that returns `LayoutJS<T>`
* and others.

However, this pull request hasn't implement them yet. I hesitate to implement them because it might be excessive.

@Ms2ger @jdm: how do you think about it?

**Comment by jdm** [comment]
@saneyuki I don't think those changes would be excessive.

**Comment by saneyuki** [comment]
@jdm ok. I'll make them.

**Comment by saneyuki** [comment]
squashed!

**Comment by jdm** [comment]
This failed because of a problem with Cargo picking up a newer version of the mod_path library than we can build. We're investigating.

**Pull request merged**
