### PR TITLE
Combining FileReaderEvent and Process into an enum; r=jdm

### PR DESCRIPTION
**Pull request by ghost**
This one's for #6752. The build was successful for this change. I'll commit the next one for `perform_annotated_read_operation` in a moment...

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/6761)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
@jdm My local build succeeds, though I'm not sure of my changes. r?

**Comment by Wafflespeanut** [comment]
Oh, and I've bunched some imports into a single line, because they looked very much much alike :)

**Comment by jdm** [comment]
This is generally what I was looking for, but I think there are still some improvements we can make.
-S-awaiting-review +S-needs-code-changes 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/filereader.rs, line 418 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6761#-Jv5S1jMe8tXoDGFofWP)** ([raw file](https://github.com/servo/servo/blob/cd072300f40e2db63dff3758629ba98d656b0e69/components/script/dom/filereader.rs#L418)):</sup>
This method is redundant, so let's remove it :)

---

<sup>**[components/script/dom/filereader.rs, line 422 \[r1\]](https://reviewable.io:443/reviews/servo/servo/6761#-Jv5SDtLXJXu5_S4GbNd)** ([raw file](https://github.com/servo/servo/blob/cd072300f40e2db63dff3758629ba98d656b0e69/components/script/dom/filereader.rs#L422)):</sup>
What about merging this with FileReaderEvent::handler?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6761)

**Comment by Wafflespeanut** [comment]
@jdm r?

**Comment by jdm** [comment]
@bors-servo: r+
-S-awaiting-review +S-awaiting-merge 

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/6761)

**Comment by Wafflespeanut** [comment]
@jdm Thanks! :)

**Pull request merged**
