### PR TITLE
Implement HTMLMediaElement.loop Attribute

### LINKED ISSUE #22290: Implement HTMLMediaElement.loop attribute
Spec: https://html.spec.whatwg.org/multipage/media.html#attr-media-loop
Code: `components/script/dom/htmlmediaelement.rs`, `components/script/dom/webidls/HTMLMediaElement.webidl`
Tests: `./mach test-wpt tests/wpt/web-platform-tests/html/semantics/embedded-content/media-elements/audio_loop_base.html`

### PR DESCRIPTION
**Pull request by swarnimarun**
Work done for Implementing HTMLMediaElement.loop Attribute,
- Uncomment `loop` attribute from webidl
- Add make_bool macros for Loop and SetLoop functions
- Update the required tests

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #22290

- [x] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23236)

### CODE REVIEW

**Comment by swarnimarun** [comment]
I am deeply sorry for the late PR.
Currently, there aren't any errors but I am not able to identify what else needs to be done to fix this issue, so that audio_loop_base test runs.

**Comment by swarnimarun** [comment]
Also I didn't know where to mention it but I believe that the Fixme comment here, https://github.com/servo/servo/blob/328244684a8b1f98d515d5f40655b9cf7347affd/components/script/dom/htmlmediaelement.rs#L291

Refers to the can-autoplay-flag, which seems to be the purpose of autoplaying from it's use, https://github.com/servo/servo/blob/328244684a8b1f98d515d5f40655b9cf7347affd/components/script/dom/htmlmediaelement.rs#L1015 ,and should begin with true as per the specs, https://html.spec.whatwg.org/multipage/media.html#can-autoplay-flag.

So it's probably an arbitary comment.

Extremely sorry if it should not be mentioned here.

**Review by ferjm — CHANGES_REQUESTED** [review]
Thanks for the PR! The code looks good, but we need to change the test expectations a little bit before merging it.

I needed to check locally to see why the `audio_loop_base.html` cause the code looks ok. It appears that we are having troubles reproducing short mp3 files. So I wouldn't worry about it for now. I'll file a follow-up issue to investigate this.

Please, revert the changes done to `tests/wpt/metadata/html/semantics/embedded-content/media-elements/audio_loop_base.html.ini` and update the test expectations for `tests/wpt/metadata/html/dom/interfaces.https.html.ini`.

**Comment by ferjm** [comment]
> Also I didn't know where to mention it but I believe that the Fixme comment here,
> 
> [servo/components/script/dom/htmlmediaelement.rs](https://github.com/servo/servo/blob/328244684a8b1f98d515d5f40655b9cf7347affd/components/script/dom/htmlmediaelement.rs#L291)
> 
> Line 291 in [3282446](/servo/servo/commit/328244684a8b1f98d515d5f40655b9cf7347affd)
>  // FIXME(nox): Why is this initialised to true? 
> 
> Refers to the can-autoplay-flag, which seems to be the purpose of autoplaying from it's use,
> 
> [servo/components/script/dom/htmlmediaelement.rs](https://github.com/servo/servo/blob/328244684a8b1f98d515d5f40655b9cf7347affd/components/script/dom/htmlmediaelement.rs#L1015)
> 
> Line 1015 in [3282446](/servo/servo/commit/328244684a8b1f98d515d5f40655b9cf7347affd)
>  self.autoplaying.set(true); 
> ,and should begin with true as per the specs, https://html.spec.whatwg.org/multipage/media.html#can-autoplay-flag.
> 
> So it's probably an arbitary comment.
> 
> Extremely sorry if it should not be mentioned here.

No need to apologize :). This is a good place to mention it. A new issue would have also worked.

Indeed, it seems that we can remove this comment from the code. This is likely a spec related question instead. cc @nox

Thanks for raising up the issue.

**Comment by ferjm** [comment]
> I needed to check locally to see why the `audio_loop_base.html` cause the code looks ok. It appears that we are having troubles reproducing short mp3 files. So I wouldn't worry about it for now. I'll file a follow-up issue to investigate this.

I filed #23241

**Comment by swarnimarun** [comment]
Ok thanks. Will fix up the tests ASAP.

**Comment by swarnimarun** [comment]
> Please, revert the changes done to `tests/wpt/metadata/html/semantics/embedded-content/media-elements/audio_loop_base.html.ini` and update the test expectations for `tests/wpt/metadata/html/dom/interfaces.https.html.ini`.

Rebased and updated the test expectations for HTMLMediaElement in `interfaces.https`

**Comment by ferjm** [comment]
Thanks!

@bors-servo r+

**Comment by CYBAI** [comment]
@bors-servo retry

```
  ▶ FAIL [expected PASS] /css/CSS2/syntax/at-charset-042.xht
  └   → /css/CSS2/syntax/at-charset-042.xht 142a99007818eaad451b21601c1bfd04e79e8486
/css/CSS2/syntax/at-charset-001-ref.xht 0c2e5215e1346ac2422396dc1d3ca7f950906e29
```

**Comment by atouchet** [comment]
Aren't the passing tests supposed to be removed?

**Comment by CYBAI** [comment]
> Aren't the passing tests supposed to be removed?

They will be removed in next Sync WPT PR :)

**Comment by atouchet** [comment]
> They will be removed in next Sync WPT PR :)

It doesn't look like they were.

**Pull request merged**
