### PR TITLE
layout: Ensure abs-pos elements establish block formatting contexts

### LINKED ISSUE #13495: Navigation items at the top of nbc.com overlap one another horizontally
The text is all smushed together—layout considers the floats to have the wrong widths. Each item seems to have `float: left` and the elements inside form stacking contexts in various ways.

### PR DESCRIPTION
**Pull request by paulrouget**
Updating #16310

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13495 (GitHub issue number if applicable)

- [x] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by paulrouget** [comment]
We need this to get the BabylonJS demos UI to work properly.

**Comment by jdm** [comment]
@bors-servo retry
#23290

**Comment by CYBAI** [comment]
@bors-servo retry

- #24611 
- #24622

**Comment by CYBAI** [comment]
@bors-servo retry

-  #24726

**Pull request merged**
