### PR TITLE
Refactor, cleanup HSTS related code.

### PR DESCRIPTION
**Pull request by frewsxcv**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10666)

### CODE REVIEW

**Comment by frewsxcv** [comment]
I recommend looking at each commit individually, especially https://github.com/servo/servo/pull/10666/commits/7290dc57d096ad93cad94fc4ba746938c4fc39dc.

cc @samfoo since they wrote most of this stuff.

**Comment by SimonSapin** [comment]
Travis reports one tidy error:

```
./tests/unit/net/hsts.rs:6: use statement is not in alphabetical order
	expected: net::hsts::{HstsList, HstsEntry}
	found: net::hsts::secure_url
```

**Comment by SimonSapin** [comment]
r=me with that fixed

**Pull request merged**
