### PR TITLE
Refactor dispatch_event according to the spec (fixes #9178)

### LINKED ISSUE #9178: Document/Refactor steps for dispatch_event in eventdispatcher.rs
The spec may have changed after it was last modified, so refactoring may be necessary

Code: `components/script/dom/eventdispatcher.rs`
Spec: https://dom.spec.whatwg.org/#concept-event-dispatch

### PR DESCRIPTION
**Pull request by nox**
Two new functions invoke and invoke_inner are introduced and some invariants documented.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9787)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo retry

It seems like the spec is missing the step about checking the "stop immediate propagation" after each call of `handleEvent` in "invoke inner".

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r+

**Comment by nox** [comment]
@bors-servo retry #9092

…

**Comment by nox** [comment]
Yet again the same intermittent failures.

@bors-servo retry

**Pull request merged**
