### PR TITLE
Rename js crate to mozjs

### PR DESCRIPTION
**Pull request by asajeffrey**
This PR renames the `js` dependency to `mozjs', ready for when https://github.com/servo/rust-mozjs/pull/377 lands.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because refactoring

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19138)

### CODE REVIEW

**Comment by asajeffrey** [comment]
cc @fitzgen

**Review by jdm — APPROVED** [review]

**Comment by asajeffrey** [comment]
Sigh, forgot to check in the `Cargo.lock` file. @bors-servo r=jdm

**Pull request merged**
