### PR TITLE
Implement srcObject logic for Blob media providers

### PR DESCRIPTION
**Pull request by ferjm**
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23103)

### CODE REVIEW

**Comment by CYBAI** [comment]
AppVeyor failed with timeout and Travis complained about WPT manifest 👀

```
 0:09.30 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/mozilla/meta/MANIFEST.json
 0:09.41 /home/travis/build/servo/servo/tests/wpt/mozilla/meta/MANIFEST.json  0  error  mozilla/movie_5.mp4 in manifest but removed from source.  (wpt-manifest)
 0:09.41 ERROR Manifest /home/travis/build/servo/servo/tests/wpt/mozilla/meta/MANIFEST.json is outdated, use |./mach update-manifest| to fix.
 0:09.41 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/metadata/MANIFEST.json
 0:15.47 WARNING Manifest /home/travis/build/servo/servo/tests/wpt/metadata/MANIFEST.json contains correct tests but file hashes changed.
 0:15.60 ERROR Manifest /home/travis/build/servo/servo/tests/wpt/metadata/MANIFEST.json is outdated, use |./mach update-manifest| to fix.
 0:15.60 INFO Diffing old and new manifests /home/travis/build/servo/servo/tests/wpt/webgl/meta/MANIFEST.json
```

**Comment by CYBAI** [comment]
I saw there's a forced push after @jdm labeled the `S-needs-rebase` so I removed it 🙇

**Comment by ferjm** [comment]
r? @Manishearth 

I realize that this might not be very useful for the MediaStream case, as we are using the `fetch_request` path for blobs as well. I guess we would need to generalize and replicate some of the logic of the [FetchResponseListener implementation for HTMLMediaElementFetchListener](https://github.com/servo/servo/blob/master/components/script/dom/htmlmediaelement.rs#L2074) for the MediaStream and MediaSource cases.

**Comment by Manishearth** [comment]
@bors-servo r+

looks good!

**Comment by CYBAI** [comment]
@bors-servo retry

- #13480

**Pull request merged**
