### PR TITLE
Bug 4236: Moved anchorelement click event to activation behaviour

### PR DESCRIPTION
**Pull request by shinglyu**
Fixed bug #4236

### CODE REVIEW

**Comment by shinglyu** [comment]
The old code won't compile (due to glutin update, I guess), so I rebased to the latest master. Sorry for breaking the Critic review.

**Comment by shinglyu** [comment]
Hi @jdm, please help me enalbe the Critix tracking, many thanks!

**Comment by jdm** [comment]
Done :)

**Comment by shinglyu** [comment]
@jdm: Thanks! All the comments are addressed :)

**Comment by jdm** [comment]
Looks great! Go ahead and squash.

**Comment by shinglyu** [comment]
Done!

**Pull request merged**
