### PR TITLE
Update image.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/14929)

### CODE REVIEW

**Comment by nox** [comment]
This needs to be rebased. Will open PR on image to update to byteorder 1.0.0.

**Comment by nox** [comment]
Oh, @mbrubeck did it already. https://github.com/PistonDevelopers/image/pull/605

**Comment by nox** [comment]
https://github.com/PistonDevelopers/image/issues/609

**Comment by Ms2ger** [comment]
Done, please review.

**Comment by Ms2ger** [comment]
Mac seems to be really unhappy about this one.

**Comment by nox** [comment]
Pushed a new image/png/deflate bump.

@bors-servo r=mbrubeck

**Pull request merged**
