### PR TITLE
Derive the Debug trait for WebIDL-generated enums.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9678)

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo retry
* #9680

**Comment by KiChjang** [comment]
@bors-servo retry
* #7846

**Comment by KiChjang** [comment]
@bors-servo retry
* #8120

**Comment by Wafflespeanut** [comment]
@bors-servo retry

#9092

**Comment by Wafflespeanut** [comment]
@bors-servo retry

#7846

**Pull request merged**
