### PR TITLE
Expose Worker interfaces only to Worker

### PR DESCRIPTION
**Pull request by johannhof**
Partial #12415. Let me know if you suspect some other tests may be affected by this.

r? @Ms2ger

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [x] There (sorta) are tests for these changes

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12457)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thanks for the PR! One nit: please use `Exposed=Worker` rather than `Exposed=(Worker)`.

I'll let the bot check if any other tests are affected. @bors-servo try

**Comment by Ms2ger** [comment]
http://build.servo.org/builders/linux-rel/builds/2181 says
```
Tests with unexpected results:
  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] WorkerGlobalScope interface: existence and properties of interface object

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] WorkerNavigator interface: existence and properties of interface object

  ▶ Unexpected subtest result in /html/dom/interfaces.html:
  └ PASS [expected FAIL] WorkerLocation interface: existence and properties of interface object
```

Update those expectations, and r=me. (Let me know if you want help with that.)

**Comment by johannhof** [comment]
@Ms2ger does that look correct?

**Comment by Ms2ger** [comment]
Sorry for the delay; this looks great to me. Could you squash the three commits into one?

**Comment by johannhof** [comment]
Sure!

**Comment by johannhof** [comment]
@Ms2ger done :)

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r+

**Pull request merged**
