### PR TITLE
style: Sync changes from mozilla-central.

### PR DESCRIPTION
**Pull request by emilio**
See each individual commit for details.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21897)

### CODE REVIEW

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1497607

**Comment by emilio** [comment]
@bors-servo r+

Moar passes.

**Comment by emilio** [comment]
@bors-servo retry 

 * Builder OOM?

**Comment by Manishearth** [comment]
```
error[E0063]: missing field `color` in initializer of `webrender_api::ImageDisplayItem`
   --> tests/unit/metrics/paint_time.rs:121:9
    |
121 |         ImageDisplayItem {
    |         ^^^^^^^^^^^^^^^^ missing `color`

error: aborting due to previous error
```

**Comment by Manishearth** [comment]
nope, because I"m an idiot.

thanks!

**Pull request merged**
