### PR TITLE
Branding: s/servo/firefox reality/

### LINKED ISSUE #24108: Replace Servo branding in UWP app with Firefox Reality
We should remove references to Servo (ServoApp in title, servo:// url handler) from the app and replace them with Firefox Reality instead. We should also create some store asset icons that make use of the FxR logo.

### PR DESCRIPTION
**Pull request by paulrouget**
- Used images from https://github.com/MozillaReality/FirefoxReality
- Used description from https://play.google.com/store/apps/details?id=org.mozilla.vrbrowser
- Changed protocol handler url scheme from "servo://" to "fxr://"
- Default page for now is about:blank

Fix #24108

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/24125)

### CODE REVIEW

**Comment by paulrouget** [comment]
Splash screen:



Title and icons (ignore the navigation bar icons, that's a different PR):

**Comment by jdm** [comment]
```
         Adding payload file 'Assets\Wide310x150Logo.scale-200.png' from 'C:\Users\task_1567592625\repo\support\hololens\ServoApp\ARM64\Debug\Assets\Wide310x150Logo.scale-200.png'.
     2>Package.appxmanifest(19,99): error APPX3207: App manifest references the square 310x310 logo image 'Assets\LargeTile.scale-400.png' which is larger than the maximum image file size. It must be no larger than 204,800 bytes. [C:\Users\task_1567592625\repo\support\hololens\ServoApp\ServoApp.vcxproj]
     2>Done Building Project "C:\Users\task_1567592625\repo\support\hololens\ServoApp\ServoApp.vcxproj" (default targets) -- FAILED.
```

**Comment by jdm** [comment]
@angelortiz1007 Fun fact, your work to build the appx package on CI has prevented a regression :)

**Pull request merged**
