### PR TITLE
Made the clipboard-related functionality in TextInput more testable. Add...

### PR DESCRIPTION
**Pull request by aweinstock314**
...ed test_clipboard_paste to the "test-unit" suite.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5800)

### CODE REVIEW

**Comment by jdm** [comment]
The changes in style/ and the Cargo.lock look wrong to me.

**Comment by jdm** [comment]
Reviewed files:
- components/script/clipboard_provider.rs @ r2
- components/script/dom/document.rs @ r1
- components/script/dom/htmlinputelement.rs @ r1
- components/script/dom/htmltextareaelement.rs @ r1
- components/script/dom/keyboardevent.rs @ r1
- components/script/lib.rs @ r1
- components/script/textinput.rs @ r1
- components/servo/Cargo.lock @ r3
- tests/unit/script/Cargo.toml @ r3
- tests/unit/script/lib.rs @ r3
- tests/unit/script/textinput.rs @ r1
- tests/unit/style/Cargo.toml @ r3
- tests/unit/style/lib.rs @ r3

---

<sup>**[components/script/dom/keyboardevent.rs, line 79 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLGwz84Uqx3vCLkwhl)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/dom/keyboardevent.rs#L79)):</sup>
I would much rather force callers to provide a Key value here and make get_key return a non-optional value.

---

<sup>**[components/script/dom/keyboardevent.rs, line 138 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLDyRyvx1v66oLWigT)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/dom/keyboardevent.rs#L138)):</sup>
These should be part of a `KeyboardEventHelpers` trait that's implemented on `JSRef<KeyboardEvent>` instead.

---

<sup>**[components/script/dom/keyboardevent.rs, line 150 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLH5yENhSSTbAVJNhw)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/dom/keyboardevent.rs#L150)):</sup>
Use |= for all of these.

---

<sup>**[components/script/textinput.rs, line 286 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLEUI6spAre8E8sBvo)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/textinput.rs#L286)):</sup>
nit: { should go on the previous line

---

<sup>**[components/script/textinput.rs, line 290 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLGCmbhYXffSGeo3h_)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/textinput.rs#L290)):</sup>
nit: } else {

---

<sup>**[components/script/textinput.rs, line 295 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLGEnqkBxfgKsq3m8F)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/textinput.rs#L295)):</sup>
nit: { on previous line

---

<sup>**[components/script/textinput.rs, line 297 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLGPCqcmS21LcWkeu7)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/textinput.rs#L297)):</sup>
We should really match on the Key value instead of the string value now that it's available.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5800)

**Comment by aweinstock314** [comment]
<sup>**[components/script/dom/keyboardevent.rs, line 79 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLGwz84Uqx3vCLkwhl)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/dom/keyboardevent.rs#L79)):</sup>
One of the calls to `new` is from `Constructor` right below it, which doesn't seem to have a `Key` in its arguments (and I'm not sure how to handle the case where synthesizing a `Key` from the string that it does receive as its argument fails).

---

<sup>**[components/script/dom/keyboardevent.rs, line 150 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLH5yENhSSTbAVJNhw)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/dom/keyboardevent.rs#L150)):</sup>
I've tried that, and gotten the error message "error: binary assignment operation `|=` cannot be applied to type `msg::constellation_msg::KeyModifiers`". Is there a seperate trait that needs to be implemented on ```bitflags!``` to get the augmented assignment operators?

---

<sup>**[components/script/textinput.rs, line 297 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLGPCqcmS21LcWkeu7)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/textinput.rs#L297)):</sup>
Part of the match statement is a "c if c.len() == 1" clause, used for inserting. Should this be handled something along the lines of ```if key_value(key, mods).len() == 1 { ... } else match key { ... }```?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5800)

**Comment by jdm** [comment]
Reviewed files:
- components/script/textinput.rs @ r4

---

<sup>**[components/script/dom/keyboardevent.rs, line 79 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLGwz84Uqx3vCLkwhl)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/dom/keyboardevent.rs#L79)):</sup>
Ah, I see. Ok, I guess we have to stick with Option, but let's try to create a Key value in the constructor if we can.

---

<sup>**[components/script/textinput.rs, line 294 \[r3\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoLGPCqcmS21LcWkeu7)** ([raw file](https://github.com/servo/servo/blob/a8cc23490f2424ba777ebbdd64e4807765020b72/components/script/textinput.rs#L294)):</sup>
Let's instead add an is_printable function that returns true for the letters/numbers that would match the single-character key strings.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5800)

**Comment by jdm** [comment]
Reviewed files:
- components/script/dom/keyboardevent.rs @ r5
- components/script/textinput.rs @ r5

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5800)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5800)

**Comment by jdm** [comment]
-S-awaiting-review +S-needs-code-changes 

---

Reviewed files:
- components/script/dom/keyboardevent.rs @ r6
- components/script/textinput.rs @ r7

---

<sup>**[components/script/dom/keyboardevent.rs, line 116 \[r7\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoVGqPe3DHk_F2F-1Ve)** ([raw file](https://github.com/servo/servo/blob/7e09d700faa83c6b2a79949aae3afc3adaeeb1eb/components/script/dom/keyboardevent.rs#L116)):</sup>
let key = key_from_string(&init.key).map(|(key, _)| key);

---

<sup>**[components/script/dom/keyboardevent.rs, line 344 \[r7\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoVGy20Dgw3OtvRFaoV)** ([raw file](https://github.com/servo/servo/blob/7e09d700faa83c6b2a79949aae3afc3adaeeb1eb/components/script/dom/keyboardevent.rs#L344)):</sup>
What's the point of the KeyModifiers return? It's not used anywhere. Also, does this function need to be public?

---

<sup>**[components/script/dom/keyboardevent.rs, line 442 \[r7\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoVH89mV116fG-5KrHz)** ([raw file](https://github.com/servo/servo/blob/7e09d700faa83c6b2a79949aae3afc3adaeeb1eb/components/script/dom/keyboardevent.rs#L442)):</sup>
"Unidentified" should just be None instead.

---

<sup>**[components/script/dom/keyboardevent.rs, line 487 \[r7\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoVHL-IzahbZLAKWvMy)** ([raw file](https://github.com/servo/servo/blob/7e09d700faa83c6b2a79949aae3afc3adaeeb1eb/components/script/dom/keyboardevent.rs#L487)):</sup>
If this function takes the location value as an argument these could be differentiated.

---

<sup>**[components/script/dom/keyboardevent.rs, line 511 \[r7\]](https://reviewable.io:443/reviews/servo/servo/5800#-JoVHSkH79UuPrxvSMxx)** ([raw file](https://github.com/servo/servo/blob/7e09d700faa83c6b2a79949aae3afc3adaeeb1eb/components/script/dom/keyboardevent.rs#L511)):</sup>
Same as above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5800)

**Comment by jdm** [comment]
-S-awaiting-review 

---

Reviewed files:
- components/script/dom/keyboardevent.rs @ r8

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5800)

**Pull request merged**
