### PR TITLE
Enable windows unit tests

### LINKED ISSUE #25961: Windows unit test failure on windows server 2019 (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```
     Running target\debug\deps\main-e43e241d9ae06d42.exe
error: test failed, to rerun pass '-p net --test main'
Caused by:
  process didn't exit successfully: `C:\Users\task_1584122006\repo\target\debug\deps\main-e43e241d9ae06d42.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```

### PR DESCRIPTION
**Pull request by jdm**
Fixes #25961.

### CODE REVIEW

**Comment by paulrouget** [comment]
oh nice!

@bors-servo r+

**Comment by jdm** [comment]
@bors-servo retry
* #23290

**Pull request merged**
