### PR TITLE
Update web-platform-tests

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16528)

### CODE REVIEW

**Comment by nox** [comment]
```
± ./mach update-wpt --no-patch test-wpt.log
DEBUG:manifest:Opening manifest at /Users/nox/src/servo/tests/wpt/metadata/MANIFEST.json
DEBUG:manifest:Opening manifest at /Users/nox/src/servo/tests/wpt/mozilla/meta/MANIFEST.json
Warning: Duplicate heading /html/semantics/text-level-semantics/the-wbr-element/wbr-element.html
Error running mach:

    ['update-wpt', '--no-patch', 'test-wpt.log']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

KeyError

  File "/Users/nox/src/servo/python/servo/testing_commands.py", line 503, in update_wpt
    return run_globals["update_tests"](**kwargs)
  File "/Users/nox/src/servo/tests/wpt/update.py", line 25, in update_tests
    rv = update.run_update(logger, **kwargs)
  File "/Users/nox/src/servo/tests/wpt/./update/__init__.py", line 25, in run_update
    return updater.run()
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/update/update.py", line 151, in run
    rv = update_runner.run()
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/update/base.py", line 65, in run
    rv = step(self.logger).run(step_index, self.state)
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/update/base.py", line 36, in run
    self.create(state)
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/update/update.py", line 97, in create
    runner.run()
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/update/base.py", line 65, in run
    rv = step(self.logger).run(step_index, self.state)
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/update/base.py", line 36, in run
    self.create(state)
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/update/metadata.py", line 40, in create
    boolean_properties=state.boolean_properties)
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/metadata.py", line 57, in update_expected
    boolean_properties=boolean_properties)
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/metadata.py", line 151, in update_from_logs
    updater.update_from_log(f)
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/metadata.py", line 231, in update_from_log
    reader.each_log(log_reader, self.action_map)
  File "/Users/nox/src/servo/python/_virtualenv/lib/python2.7/site-packages/mozlog/reader.py", line 48, in each_log
    action_map[item["action"]](item)
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/metadata.py", line 262, in test_status
    test_cls = wpttest.manifest_test_cls[test.test_type]
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/manifestupdate.py", line 146, in test_type
    return self.get("type", None)
  File "/Users/nox/src/servo/tests/wpt/harness/wptrunner/wptmanifest/backends/conditional.py", line 234, in get
    raise KeyError
```

Cc @jgraham @gsnedders

**Comment by nox** [comment]
I won.

@bors-servo try

**Comment by nox** [comment]
Err, forgot to revert some debugging code in the test harness...

**Comment by nox** [comment]
@jdm You bitrotted this in #16492 and now this needs to be synced with upstream again, I don't know how to do that.

**Comment by jgraham** [comment]
Can't you just rebase onto @jdm's changes and wait until the next sync to upstream those bits?

**Comment by nox** [comment]
Mmmh, I guess I can.

**Comment by jdm** [comment]
Shoot, I didn't realize that this PR contained identical changes to #16492 already. Sorry for messing it up.

**Comment by nox** [comment]
Git cannot even cope with it when rebasing...

**Comment by nox** [comment]
```
  ▶ CRASH [expected OK] /html/browsers/windows/nested-browsing-contexts/window-parent-null.html
  │ 
  │ VMware, Inc.
  │ Gallium 0.4 on softpipe
  │ 3.3 (Core Profile) Mesa 17.2.0-devel
  │ called `Option::unwrap()` on a `None` value (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(3) }, at /checkout/src/libcore/option.rs:329)
  │ stack backtrace:
  │    0:     0x7f6d7b1655fd - backtrace::backtrace::trace::h1899890371f726ff
  │    1:     0x7f6d7b165c02 - backtrace::capture::Backtrace::new::hb8a21c7c3bfbd0d6
  │    2:     0x7f6d79258d07 - servo::main::{{closure}}::h87fd196640a55f67
  │    3:     0x7f6d7b1eaf5d - std::panicking::rust_panic_with_hook
  │                         at /checkout/src/libstd/panicking.rs:550
  │    4:     0x7f6d7b1eadf4 - std::panicking::begin_panic<collections::string::String>
  │                         at /checkout/src/libstd/panicking.rs:511
  │    5:     0x7f6d7b1ead29 - std::panicking::begin_panic_fmt
  │                         at /checkout/src/libstd/panicking.rs:495
  │    6:     0x7f6d7b1eacb7 - std::panicking::rust_begin_panic
  │                         at /checkout/src/libstd/panicking.rs:471
  │    7:     0x7f6d7b2170ed - core::panicking::panic_fmt
  │                         at /checkout/src/libcore/panicking.rs:69
  │    8:     0x7f6d7b217024 - core::panicking::panic
  │                         at /checkout/src/libcore/panicking.rs:49
  │    9:     0x7f6d79c278bc - <script::dom::bindings::js::LayoutJS<script::dom::node::Node> as script::dom::node::LayoutNodeHelpers>::iframe_pipeline_id::ha1e7ff7ed65df15a
  │   10:     0x7f6d7970d783 - <layout::construct::FlowConstructor<'a, ConcreteThreadSafeLayoutNode>>::build_fragment_for_block::h7ca9f803e2852b38
  │   11:     0x7f6d796b68fb - <layout::construct::FlowConstructor<'a, ConcreteThreadSafeLayoutNode> as layout::traversal::PostorderNodeMutTraversal<ConcreteThreadSafeLayoutNode>>::process::h5362e1bef081a996
  │   12:     0x7f6d796f34eb - style::traversal::DomTraversal::handle_postorder_traversal::hd37c6c9bba78fbac
  │   13:     0x7f6d7972f0d6 - layout_thread::LayoutThread::handle_reflow::hc8b7a204194af853
  │   14:     0x7f6d79726343 - layout_thread::LayoutThread::handle_request_helper::hf29593d5253ed13e
  │   15:     0x7f6d79721b61 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::h60536d9d61f4565d
  │   16:     0x7f6d796c7c76 - std::panicking::try::do_call::h60436304a89e650c
  │   17:     0x7f6d7b1f1f9a - panic_unwind::__rust_maybe_catch_panic
  │                         at /checkout/src/libpanic_unwind/lib.rs:98
  │   18:     0x7f6d796e24b4 - <F as alloc::boxed::FnBox<A>>::call_box::hc083d71cf24535fb
  │   19:     0x7f6d7b1e9ab4 - alloc::boxed::{{impl}}::call_once<(),()>
  │                         at /checkout/src/liballoc/boxed.rs:650
  │                          - std::sys_common::thread::start_thread
  │                         at /checkout/src/libstd/sys_common/thread.rs:21
  │                          - std::sys::imp::thread::{{impl}}::new::thread_start
  │                         at /checkout/src/libstd/sys/unix/thread.rs:84
  │   20:     0x7f6d7711d183 - start_thread
  │   21:     0x7f6d76c34bec - clone
  │   22:                0x0 - <unknown>
  │ ERROR:servo: called `Option::unwrap()` on a `None` value
  └ Pipeline failed in hard-fail mode.  Crashing!
```

Does that ring a bell @jdm?

**Comment by jdm** [comment]
It's a new test introduced in this batch. I think we should file it as intermittent and investigate after merging.

**Comment by jdm** [comment]
@bors-servo: retry
* #16574

**Pull request merged**
