### PR TITLE
Slightly clean up the final URL creation in canvas.toDataURL

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/21850)

### CODE REVIEW

**Comment by nox** [comment]
Sometimes, I can be pretty dumb.

https://github.com/alicemaz/rust-base64/pull/56

**Comment by jdm** [comment]
@bors-servo retry
* oom

**Comment by CYBAI** [comment]
@bors-servo retry

```
{"action": "test_groups", "line": 19, "groups": ["default"]}
{"status": "TIMEOUT", "group": "default", "line": 739, "subtest": null, "action": "test_result", "test": "/eventsource/dedicated-worker/eventsource-eventtarget.worker.html", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 740, "subtest": null, "action": "test_result", "test": "/eventsource/format-field-data.htm", "message": null, "stack": null, "expected": "OK"}
{"status": "TIMEOUT", "group": "default", "line": 742, "subtest": null, "action": "test_result", "test": "/eventsource/dedicated-worker/eventsource-close2.htm", "message": null, "stack": null, "expected": "OK"}
```

**Pull request merged**
