### PR TITLE
Issue #9095: Send a notification when a file load is cancelled.

### PR DESCRIPTION
**Pull request by simartin**
Fixes https://github.com/servo/servo/issues/9095

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9121)

### CODE REVIEW

**Comment by simartin** [comment]
Note that I did not find any obvious way of testing but I'll try to figure something out

**Comment by jdm** [comment]
Yes, we have no actual code that makes use of the network cancellation code yet.

**Comment by jdm** [comment]
@bors-servo: r+
Thanks! Sorry about the long delay!

**Comment by jdm** [comment]
@bors-servo: retry
* #9163

**Pull request merged**
