### PR TITLE
Issue #6791: Allow more array types in bufferData and bufferSubData.

### PR DESCRIPTION
**Pull request by simartin**
Fix https://github.com/servo/servo/issues/6791

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8831)

### CODE REVIEW

**Comment by simartin** [comment]
I believe the test is meaningful however it did not fail before, we might want it out... Let me know

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8831#-:-K4j6hIPnJ4KBLjEMW7A:1795641257)*

**Comment by eefriedman** [comment]
This is almost right... except that this will explode in debug builds: JS_GetUint8ArrayData has an assertion checking that you don't just blindly call it on an array which isn't of type u8.

Can you just use `ptr`?

**Comment by simartin** [comment]
Thanks for your review and the tip. PR updated accordingly.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8831#-:-K4rhEZF56ANzlQipWOe:1313438033)*

**Comment by eefriedman** [comment]
Can you double-check that this rendering using bufferData still works correctly with this patch?  I think there are some tests in tree, but I'm not sure they're enabled at the moment.

**Comment by simartin** [comment]
@eefriedman I just compared the output of the following (changing highp to mediump since the former is not supported on my Mac for some reason) with and without this patch, and it's the same:
   ./mach run tests/html/test_webgl_triangle.html

**Pull request merged**
