### PR TITLE
Implement tag name selector for FindElement and related WebDriver commands

### PR DESCRIPTION
**Pull request by georgeroman**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] There are tests for these changes

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23585)

### CODE REVIEW

**Comment by georgeroman** [comment]
Hmm, this is weird, these tests are passing locally.

**Comment by jdm** [comment]
What operating system are you using?

**Comment by georgeroman** [comment]
I'm using Arch Linux.

**Comment by jdm** [comment]
@georgeroman What's the plan for this PR?

**Comment by georgeroman** [comment]
Once I'm finished with the current work on returning arrays and objects from `ExecuteScript` I will come back to it and dive deeper into what might cause the tests fail on the CI.

**Comment by georgeroman** [comment]
I rebased this, it will hopefully pass the tests now.

**Comment by georgeroman** [comment]
I suspect that something is going wrong with the way the fixture `html` files are provided:
https://github.com/servo/servo/blob/812bf8d816d29ecf132ff15a2da6a83c690e2e48/tests/wpt/web-platform-tests/webdriver/tests/find_elements/find.py#L48

Could I add some debug prints and then test them in the CI server?

**Comment by jdm** [comment]
Sure! Add yourself to https://github.com/servo/saltfs/blob/master/homu/files/cfg.toml so we can grant you access to do try runs when you need to.

**Comment by georgeroman** [comment]
For some reason, the HTTP testing server is not started for the process that runs the failing tests: https://build.servo.org/builders/linux-rel-wpt/builds/12860/steps/shell__6/logs/stdio

**Comment by georgeroman** [comment]
It looks like the issue was a missing `HOST_FILE` variable in the test environment. With it in place, a lot of new tests are now passing and a few are now failing.

**Comment by jdm** [comment]
https://build.servo.org/builders/linux-rel-wpt/builds/12890/steps/shell__5/logs/filtered-wdspec-errorsummary.log has a lot of passing tests.

**Comment by georgeroman** [comment]
Yeah, that's great, but I'll probably try running the tests one more time just to make sure there is no intermittent failure.

**Pull request merged**
