### PR TITLE
Add simple document load tracking infrastructure

### PR DESCRIPTION
**Pull request by jdm**
This implements a simple load-tracking system and tracks stylesheet loads as an example of how it fits together. This is a simplified and rebased version of #3714; I do not believe that the main thrust of hsivonen's comments (related to tracking navigation in browsing contexts) affect this part of the work. 

r? @Ms2ger

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5804)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Rebase before critic picks it up?

**Comment by jdm** [comment]
Done.

**Comment by jdm** [comment]
@Ms2ger Rebased.

**Pull request merged**
