### PR TITLE
Upgrade to rustc 1.6.0-nightly (1805bba39 2015-11-26)

### PR DESCRIPTION
**Pull request by SimonSapin**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8698)

### CODE REVIEW

**Comment by SimonSapin** [comment]
https://github.com/huonw/simd/pull/15

**Comment by KiChjang** [comment]
```
Ran 6931 tests finished in 1530.0 seconds. • 6929 ran as expected. 8 tests skipped.
• 2 tests timed out unexpectedly
Tests with unexpected results:
▶ TIMEOUT [expected FAIL] /css-flexbox-1_dev/html/flexbox-basic-iframe-horiz-001.htm
▶ TIMEOUT [expected FAIL] /css-flexbox-1_dev/html/flexbox-basic-iframe-vert-001.htm
```

**Comment by jdm** [comment]
@bors-servo: retry
* #8676 and #8616

**Pull request merged**
