### PR TITLE
Implement WebSocket#binaryType

### LINKED ISSUE #7098: Implement WebSocket#binaryType.
Blocks #6060 

* Spec: <https://html.spec.whatwg.org/multipage/#dom-websocket-binarytype>.
* Code: `components/script/dom/{websocket.rs,webidl/WebSocket.rs}`.
* Test: various under `tests/wpt/web-platform-tests/websockets/`, `tests/wpt/web-platform-tests/html/dom/interfaces.html`.

### PR DESCRIPTION
**Pull request by tomjakubowski**
Closes #7098

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7214)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Thank you for your PR!

-S-awaiting-review +S-needs-code-changes +S-needs-squash 

---

Reviewed 1 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/websocket.rs, line 52 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7214#-JwfXWp8_zGPY9EXv_cX)** ([raw file](https://github.com/servo/servo/blob/973132c346804c5b3f38b929ffb92e77335dd939/components/script/dom/websocket.rs#L52)):</sup>
Nit: `ptr` comes before `sync`

---

<sup>**[components/script/dom/websocket.rs, line 441 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7214#-JwfXeQlHpG8oc52sKoY)** ([raw file](https://github.com/servo/servo/blob/973132c346804c5b3f38b929ffb92e77335dd939/components/script/dom/websocket.rs#L441)):</sup>
If `data.len()` is more than 2^32, this will overwrite unallocated memory. Please store `data.len() as u32` in a local, and cast back to `usize` here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7214)

**Comment by tomjakubowski** [comment]
@Ms2ger addressed your comments and squashed

**Comment by Ms2ger** [comment]
Thank you!

@bors-servo r+

**Comment by Ms2ger** [comment]
Looks like you missed one more:
```
/html/dom/interfaces.html
-------------------------
PASS expected FAIL WebSocket interface: attribute binaryType
```

**Comment by tomjakubowski** [comment]
Whoops. Re-pushed.

**Pull request merged**
