### PR TITLE
Make #[dom_struct] a proc_macro attribute

### PR DESCRIPTION
**Pull request by nox**
The rustup is needed for https://github.com/rust-lang/rust/pull/40039.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15715)

### CODE REVIEW

**Comment by nox** [comment]
@jdm Something tells me you are not going to like this...

**Comment by nox** [comment]
Oh yes of course, this is going to get bitrot all the time.

**Comment by jdm** [comment]
What's the error message if the import is missing?

**Comment by SimonSapin** [comment]
Can we use an absolute path like `#[::dom_struct::dom_struct]`, so that no import is needed?

Or `#[::dom_struct]`, with `components/script/lib.rs` change like so:

```rust
extern crate dom_struct as dom_struct_crate;
pub use dom_struct_crate::dom_struct;
```

**Comment by nox** [comment]
That dom_struct is undefined, and it suggests to import it with its path printed.

**Comment by nox** [comment]
I guess yes but I would rather just keep the import.

**Pull request merged**
