### PR TITLE
Introduce VirtualMethods::attribute_mutated()

### PR DESCRIPTION
**Pull request by nox**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7452)

### CODE REVIEW

**Comment by nox** [comment]
Amended because of #7412.

**Comment by jdm** [comment]
I'm not keen on the debug_assert changes since we only run tests in release mode right now.

**Comment by nox** [comment]
@jdm Will remove commit.

**Comment by jdm** [comment]
I like this refactoring. I'd also like to get @Ms2ger's opinion.

**Comment by Ms2ger** [comment]
Will try to finish reviewing today.

**Comment by Ms2ger** [comment]
I hope it won't be too much trouble to match my comments and the code; I reviewed most of it on a train.

```diff
     pub fn get_attribute(&self, namespace: &Namespace, local_name: &Atom) -> Option<Root<Attr>> {
         let mut attributes = RootedVec::new();
         self.get_attributes(local_name, &mut attributes);
-        attributes.r().iter()
+        attributes.r().
+        iter()
```

Not an improvement. (Fixed in another commit? Please fix that.)

```diff
+                };
+                // https://github.com/rust-lang/rust/issues/21114
+                is_js
```

Ugh.

```diff
+                self.attrs.borrow().iter().map(|attr| attr.root())
```

Can we create a method that returns that iterator?

```diff
+            attr.namespace() == namespace && attr.local_name() == local_name
```

The local_name check is much more likely to fail, so check it first.


```
    after_remove_attr() (i.e. when removing an href attribute from a base element).
```

I think you mean "e.g." ("for example") rather than "i.e." ("that is").

```diff
+    pub fn uint(&self) -> Option<u32> {
```

With the helper traits gone, it's no longer a pain to document these.

```diff
+        mem::swap(&mut *self.value.borrow_mut(), &mut value);
```

Feels more like a `mem::replace`.

```diff
-        self.do_set_attribute(qname.local, value, name, qname.ns, prefix, |_| false)
+        let in_empty_ns = qname.ns == ns!("");
+        let attr = Attr::new(&window, qname.local, value, name, qname.ns, prefix, Some(self));
+        self.attrs.borrow_mut().push(JS::from_rooted(&attr));
```

I kinda liked having a single place where we pushed into `attrs`.

```diff
-    pub fn do_set_attribute<F>(&self,
+    fn set_first_matching_attribute<F>(&self,
```

Reviewing tends to be easier if you split renames into their own commit.

```diff
+                                       find: F)
+                                       where F: Fn(&Attr)
+                                       -> bool {
```

```rust
                                       find: F)
    where F: Fn(&Attr) -> bool
{
```

Your formatting is extremely confusing. I thought you'd managed to stick a `where` clause between arguments and return type.

```diff
+        if let Some(attr) = attr {
+            attr.set_value(value, self);
+        } else {
```

Seems like a case for `match`.

```diff
             let attr = (*self.attrs.borrow())[idx].root();
-            if attr.r().namespace() == &ns!("") {
-                vtable_for(&NodeCast::from_ref(self)).before_remove_attr(attr.r());
-            }
-
             self.attrs.borrow_mut().remove(idx);
```

```rust
let attr = self.attrs.borrow_mut().remove(idx);
```

```diff
-            &atom!("style") => {
+            &atom!(style) => {
```

Did that really need to pollute this commit?

```diff
+                static FORWARDED_EVENTS: &'static [&'static str] =
+                    &["onfocus", "onload", "onscroll", "onafterprint", "onbeforeprint",
```

Followup: this should use atoms.

(And I already found two other pre-existing bugs in this code, yay!)

```diff
+        if *attr.local_name() == atom!(disabled) {
+            let node = NodeCast::from_ref(self);
+            match mutation {
+                AttributeMutation::Set(Some(_)) => {}
```

I guess this is correct, but now I want a test for this case.

```diff
+            let children = node.children().filter(|node| {
+                if found_legend {
+                    true
+                } else if node.is_htmllegendelement() {
+                    found_legend = true;
```

I tend to prefer using those methods only with pure closures, but I guess this is fine.

```diff
-            _ => ()
+            _ => {},
```

I prefer `()`.

```diff
+        if attr.local_name() == &atom!(data) && mutation != AttributeMutation::Removed {
+            self.process_data_url();
         }
```

Please keep the `match`.

```diff
+        if attr.local_name() == &atom!(disabled) {
+            let options = NodeCast::from_ref(self).children().filter(|child| {
+                child.is_htmloptionelement()
+            });
```

Ditto. Also elsewhere.

Why pass the `Attr` to `attribute_mutated` at all? Wouldn't it be better to pass the value in the enum, and the local name explicitly? `mutation.new_value(attr)` is pretty awkward.

**Comment by nox** [comment]
> ```
> after_remove_attr() (i.e. when removing an href attribute from a base element).
> ```
> I think you mean "e.g." ("for example") rather than "i.e." ("that is").

There are no other examples of this, but I will rename it.

**Comment by nox** [comment]
> Why pass the Attr to attribute_mutated at all? Wouldn't it be better to pass the value in the enum, and the local name explicitly? mutation.new_value(attr) is pretty awkward.

I find `mutation.new_value(attr)` the opposite of awkward, this is my favourite part of the whole refactoring. Passing the value in the enum would mean borrowing it or cloning it from the set attribute and I didn't want that, in many cases we don't even access it.

**Comment by nox** [comment]
Review status: 0 of 31 files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/attr.rs, line 92 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8JpSDEM18ylsQTa0k)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/attr.rs#L92)):</sup>
> With the helper traits gone, it's no longer a pain to document these.

Will do.

---

<sup>**[components/script/dom/element.rs, line 829 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8JKLsmuMRaHna22cv)** ([raw file](https://github.com/servo/servo/blob/2e1927e76f94fa601e8fcffc5d2b347f1ce8b221/components/script/dom/element.rs#L829)):</sup>
> Can we create a method that returns that iterator?

Will make a private one.

---

<sup>**[components/script/dom/element.rs, line 830 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8JRDoiuFi4Xfgl9b7)** ([raw file](https://github.com/servo/servo/blob/2e1927e76f94fa601e8fcffc5d2b347f1ce8b221/components/script/dom/element.rs#L830)):</sup>
> The local_name check is much more likely to fail, so check it first.

Will do.

---

<sup>**[components/script/dom/element.rs, line 833 \[r2\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8JCpS91B9ArlKTDZv)** ([raw file](https://github.com/servo/servo/blob/51418fc348f683e9a3f96747865a0400e26240fe/components/script/dom/element.rs#L833)):</sup>
> Not an improvement. (Fixed in another commit? Please fix that.)

This is not in one of my commits.

---

<sup>**[components/script/dom/element.rs, line 912 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8Mrdc2wMWCTYtBT5T)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/element.rs#L912)):</sup>
> I kinda liked having a single place where we pushed into `attrs`.

I guess I could make a push_new_attr() method that calls Attr::new(), pushes it and handles the virtual method.

---

<sup>**[components/script/dom/element.rs, line 1457 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8K69zYNqEEuH9Cg3y)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/element.rs#L1457)):</sup>
> Did that really need to pollute this commit?

This is quite the nit, I didn't even expected those would be on the same indent level, and most lines around it changed anyway. Do I really need to address this?

---

<sup>**[components/script/dom/htmlbodyelement.rs, line 141 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8KPdZStLyUEqfBFwH)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlbodyelement.rs#L141)):</sup>
> Followup: this should use atoms.

Will file.

---

<sup>**[components/script/dom/htmlbuttonelement.rs, line 143 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8KYMRLwwb5ZgWvKDY)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlbuttonelement.rs#L143)):</sup>
> I guess this is correct, but now I want a test for this case.

Will write one.

---

<sup>**[components/script/dom/htmlfieldsetelement.rs, line 93 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MR19NkLg_KYh8eKk)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlfieldsetelement.rs#L93)):</sup>
Note to self: put back match here.

---

<sup>**[components/script/dom/htmlfieldsetelement.rs, line 109 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8Kg_rLYEIi1eM76-n)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlfieldsetelement.rs#L109)):</sup>
> I tend to prefer using those methods only with pure closures, but I guess this is fine.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 65 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MOfSOWxkXRbp7BNT)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlfontelement.rs#L65)):</sup>
Note to self: put back match here.

---

<sup>**[components/script/dom/htmliframeelement.rs, line 384 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8KphYPEzbTGOTbZqt)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmliframeelement.rs#L384)):</sup>
> I prefer `()`.

```
± git grep -F "=> {}" | wc -l
      188
± git grep -F "_ => ()" | wc -l
      118
```

---

<sup>**[components/script/dom/htmlimageelement.rs, line 305 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MMuOUnaXBm20ZrjG)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlimageelement.rs#L305)):</sup>
Note to self: put back match here.

---

<sup>**[components/script/dom/htmlobjectelement.rs, line 106 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8LUWl1PNV5YIoMySz)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlobjectelement.rs#L106)):</sup>
> Please keep the `match`.

Will do.

---

<sup>**[components/script/dom/htmloptionelement.rs, line 136 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MH3oUqfhakUBNkz5)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmloptionelement.rs#L136)):</sup>
Note to self: put back match here.

---

<sup>**[components/script/dom/htmlscriptelement.rs, line 537 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8M5ptixb03yCoj3cd)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlscriptelement.rs#L537)):</sup>
Note to self: put back match here.

---

<sup>**[components/script/dom/htmltablerowelement.rs, line 67 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MD8mDEa8WfTybGl-)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmltablerowelement.rs#L67)):</sup>
Note to self: put back match here.

---

<sup>**[components/script/dom/htmltablesectionelement.rs, line 66 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MDw0txXHV3gpbdlj)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmltablesectionelement.rs#L66)):</sup>
Note to self: put back match here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7452)

**Comment by nox** [comment]
Review status: 0 of 31 files reviewed at latest revision, 19 unresolved discussions, all commit checks successful.

---

<sup>**[components/script/dom/attr.rs, line 92 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8JpSDEM18ylsQTa0k)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/attr.rs#L92)):</sup>
Done.

---

<sup>**[components/script/dom/attr.rs, line 243 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8jqYG2QS1zLpL8BVU)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/attr.rs#L243)):</sup>
> Feels more like a `mem::replace`.

Feels like a `mem::swap`, to use mem::replace I would need to either mutably borrow the value twice, or to bind it to a mutable local variable in an inner block to make sure it is relinquished afterwards.

---

<sup>**[components/script/dom/element.rs, line 829 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8JKLsmuMRaHna22cv)** ([raw file](https://github.com/servo/servo/blob/2e1927e76f94fa601e8fcffc5d2b347f1ce8b221/components/script/dom/element.rs#L829)):</sup>
Actually I can't, the iterator is behid a Ref<_>.

---

<sup>**[components/script/dom/element.rs, line 830 \[r3\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8JRDoiuFi4Xfgl9b7)** ([raw file](https://github.com/servo/servo/blob/2e1927e76f94fa601e8fcffc5d2b347f1ce8b221/components/script/dom/element.rs#L830)):</sup>
Done.

---

<sup>**[components/script/dom/element.rs, line 912 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8Mrdc2wMWCTYtBT5T)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/element.rs#L912)):</sup>
Done.

---

<sup>**[components/script/dom/htmlfieldsetelement.rs, line 93 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MR19NkLg_KYh8eKk)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlfieldsetelement.rs#L93)):</sup>
Done.

---

<sup>**[components/script/dom/htmlfontelement.rs, line 65 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MOfSOWxkXRbp7BNT)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlfontelement.rs#L65)):</sup>
Done.

---

<sup>**[components/script/dom/htmlimageelement.rs, line 305 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MMuOUnaXBm20ZrjG)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlimageelement.rs#L305)):</sup>
Done.

---

<sup>**[components/script/dom/htmlobjectelement.rs, line 106 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8LUWl1PNV5YIoMySz)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlobjectelement.rs#L106)):</sup>
Done.

---

<sup>**[components/script/dom/htmloptionelement.rs, line 136 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MH3oUqfhakUBNkz5)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmloptionelement.rs#L136)):</sup>
Done.

---

<sup>**[components/script/dom/htmlscriptelement.rs, line 537 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8M5ptixb03yCoj3cd)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmlscriptelement.rs#L537)):</sup>
Done.

---

<sup>**[components/script/dom/htmltablerowelement.rs, line 67 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MD8mDEa8WfTybGl-)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmltablerowelement.rs#L67)):</sup>
Done.

---

<sup>**[components/script/dom/htmltablesectionelement.rs, line 66 \[r4\]](https://reviewable.io:443/reviews/servo/servo/7452#-Jy8MDw0txXHV3gpbdlj)** ([raw file](https://github.com/servo/servo/blob/d61e8842b175b7dab68abe9a28e5611dd785e152/components/script/dom/htmltablesectionelement.rs#L66)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/7452)

**Comment by nox** [comment]
And finally a test to check that disabled set twice does the right thing.

**Comment by jdm** [comment]
I think the API is unbalanced right now - either we should add an `old_value` method to `AttributeMutation` or both the before and after values should be present in the enum variant. I'm inclined towards the second option.

**Comment by nox** [comment]
`AttributeMutation::old_value()` would need to clone the old value in both cases of "attribute is removed" and "attribute is changed" because in the former it is behind the `RefCell` in `Attr` and in the later we only borrow it. This is exactly why I made `new_value()` only, returning a `Ref`.

**Comment by nox** [comment]
And given no consumer in the `VirtualMethods` chain can steal the old or the new attribute value, it's a pointless clone to make in my opinion.

**Comment by jdm** [comment]
Further discussion with @nox convinced me that my ideas were not as ergonomic as I believed. Having `new_value` take an `&Attr` argument still feels like a wart to me, but I don't have any better ideas. I say we leave this design as it is and revisit it later if it causes frustration.

**Comment by jdm** [comment]
```


/_mozilla/mozilla/enabled_disabled_selectors.html
-------------------------------------------------
FAIL JS tests (Option)
/html/semantics/selectors/pseudo-classes/disabled.html
------------------------------------------------------
FAIL ':disabled' should match only disabled elements
FAIL ':disabled' should not match elements whose disabled attribute has been removed
FAIL ':disabled' should also match elements whose disabled attribute has been set
FAIL ':disabled' should also match elements whose disabled attribute has been set twice
FAIL ':disabled' should also match disabled elements whose type has changed
FAIL ':disabled' should not match elements not in the document
```

**Comment by nox** [comment]
Failed rebase, probably, I had ran these tests before. :( Will look at.

**Comment by nox** [comment]
I had broken HTMLOptGroup. I added a line in the associated test to better improve it.

**Pull request merged**
