### PR TITLE
Implement WebGLRenderingContext.getActiveUniform()

### PR DESCRIPTION
**Pull request by saurvs**
Fixes https://github.com/servo/servo/issues/10397

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10433)

### CODE REVIEW

**Comment by emilio** [comment]
Thanks! Looks great, but you still have to update some more lockfiles :)

`./mach cargo-update -p webrender_traits` should do it if i'm not wrong.

**Comment by saurvs** [comment]
I did that, but it re-added `byteorder 0.4.2`, and there's also `byteorder 0.5.1`, so `./mach test-tidy` complains.

**Comment by saurvs** [comment]
I think we need to upgrade every crate servo depends on to `byteorder 0.5.1`

**Comment by emilio** [comment]
@saurvs: we can add it to the exception list if there's a lot of crates, but updating the others might be preferred.

**Comment by saurvs** [comment]
Well there are 7 crates `bincode image immeta ipc-channel jpeg-decoder wayland-window websocket`, so I guess I can open PR's for them and see if they're updated soon.

**Comment by emilio** [comment]
Some of them are not from the servo org, so... What if we open a tracking issue, add it to the exception list temporarily, open a bunch of PRs to update it, and when that issue gets solved (that is, all those PRs merged), we remove it from the exception list?

@jdm Would you agree with this? Or should we open PRs and wait?

**Comment by saurvs** [comment]
Oh yeah, I just tried bumping the version for `byteorder` in `image`, and it looks like `0.5` breaks a lot. So I guess it might take a while to update all the crates.

**Comment by jdm** [comment]
Yeah, if it's blocking us from other useful work we can add an exception for it.

**Comment by saurvs** [comment]
Ok done.

**Comment by emilio** [comment]
Filled https://github.com/servo/servo/issues/10437 to keep track of this.

@bors-servo: r+

**Pull request merged**
