### PR TITLE
Make css-properties.json checking a proper unit test.

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10855)

### CODE REVIEW

**Comment by jdm** [comment]
Needs a `./mach cargo-update -p style_tests`.

**Comment by jdm** [comment]
```
---- properties::properties_list_json stdout ----

	thread 'properties::properties_list_json' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:746

stack backtrace:

   1:     0x7ff230edfc20 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8

   2:     0x7ff230ee4aeb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90

   3:     0x7ff230ee46dc - std::panicking::default_hook::h08ad3bb09872855b

   4:     0x7ff230ed2c4f - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b

   5:     0x7ff230ed3c18 - std::sys_common::unwind::begin_unwind_fmt::h57ea3fbee1a40196

   6:     0x7ff230edee71 - rust_begin_unwind

   7:     0x7ff230f1ac1f - core::panicking::panic_fmt::ha6b3c19493c123b3

   8:     0x7ff23060287b - core::result::unwrap_failed::he41fdbb4a3e1914b

                        at ../src/libcore/macros.rs:29

   9:     0x7ff230602694 - _<std..result..Result<T, E>>::unwrap::h7dc65f4101dfcb66

                        at ../src/libcore/result.rs:687

  10:     0x7ff230601c73 - style_tests::properties::properties_list_json::hf2491e8e54ec32a0

                        at /home/travis/build/servo/servo/tests/unit/style/properties.rs:16

  11:     0x7ff230e67fc6 - _<F as std..boxed..FnBox<A>>::call_box::h70afdbb50723dc50

  12:     0x7ff230e6a70b - std::sys_common::unwind::try::try_fn::h84d8f5327fa145ba

  13:     0x7ff230ededfb - __rust_try

  14:     0x7ff230eded8d - std::sys_common::unwind::inner_try::h4e97625a08807651

  15:     0x7ff230e6aa8a - _<F as std..boxed..FnBox<A>>::call_box::h588f35c7f2016768

  16:     0x7ff230ee3194 - std::sys::thread::Thread::new::thread_start::h74af400293164137

  17:     0x7ff22f91d181 - start_thread

  18:     0x7ff22f43447c - __clone

  19:                0x0 - <unknown>

failures:

    properties::properties_list_json

test result: FAILED. 30 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```

**Comment by SimonSapin** [comment]
`./mach cargo-update -p style_tests` in this branch is a no-op. `style_tests` only exists in one of the lock files.

I’ve fixed the `json.exists()` logic, this should fix the panic above.

**Comment by SimonSapin** [comment]
Fixed tidy errors.

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10855#-:-KGSDea6OdQ9TANFyY8E:1236647940)*

**Pull request merged**
