### PR TITLE
Implement [Unscopable] (fixes #11583)

### LINKED ISSUE #11583: Implement [Unscopable]
Latest smup made that implementable.

http://heycam.github.io/webidl/#Unscopable

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11620)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :sunny: Test successful - [android](http://build.servo.org/builders/android/builds/1309), [arm32](http://build.servo.org/builders/arm32/builds/1399), [arm64](http://build.servo.org/builders/arm64/builds/1385), [linux-dev](http://build.servo.org/builders/linux-dev/builds/1408), [linux-rel](http://build.servo.org/builders/linux-rel/builds/1471), [mac-dev-unit](http://build.servo.org/builders/mac-dev-unit/builds/1451), [mac-rel-css](http://build.servo.org/builders/mac-rel-css/builds/1435), [mac-rel-wpt](http://build.servo.org/builders/mac-rel-wpt/builds/1488), [windows](http://build.servo.org/builders/windows/builds/1117)
</details>


---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/bindings/interface.rs, line 249 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11620#-KJersOK53V_Du4iF5E8:-KJersOK53V_Du4iF5E9:79258749) ([raw file](https://github.com/servo/servo/blob/64c1e007bbde437dc9ddccdee960859f5083ce39/components/script/dom/bindings/interface.rs#L249)):*
> ```Rust
>         let unscopable_symbol = GetWellKnownSymbol(cx, SymbolCode::unscopables);
>         assert!(!unscopable_symbol.is_null());
>         let unscopable_id = RootedId::new(cx, RUST_SYMBOL_TO_JSID(unscopable_symbol));
> ```

Please try to add a few empty lines in this block

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 5121 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11620#-KJesC3zo6-MJ7awi00u:-KJesC3zo6-MJ7awi00v:1277456304) ([raw file](https://github.com/servo/servo/blob/64c1e007bbde437dc9ddccdee960859f5083ce39/components/script/dom/bindings/codegen/CodegenRust.py#L5121)):*
> ```Python
> 
>         haveUnscopables = (len(unscopableNames) != 0 and
>                            descriptor.interface.hasInterfacePrototypeObject())
> ```

Please don't use `hasInterfacePrototypeObject`; make this `if unscopableNames:` under the `if not descriptor.interface.isCallback():` block.

---

*[components/script/dom/webidls/ChildNode.webidl, line 11 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11620#-KJesQN1CQz94MbboxKw:-KJesQN1CQz94MbboxKx:76269631) ([raw file](https://github.com/servo/servo/blob/64c1e007bbde437dc9ddccdee960859f5083ce39/components/script/dom/webidls/ChildNode.webidl#L11)):*
> ```WebIDL
> [NoInterfaceObject]
> interface ChildNode {
>   [Throws, Unscopable]
> ```

I'd like all of those to be tested.  (idlharness?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11620#-:-KJesZVN92UJFakHkCTD:1458266033)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/script/dom/bindings/interface.rs, line 249 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11620#-KJersOK53V_Du4iF5E8:-KJeto5VF-JfzF--U84y:-499146009) ([raw file](https://github.com/servo/servo/blob/64c1e007bbde437dc9ddccdee960859f5083ce39/components/script/dom/bindings/interface.rs#L249)):*
<details><summary><i>Previously, Ms2ger wrote…</i></summary>
> Please try to add a few empty lines in this block
</details>
Done.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 5121 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11620#-KJesC3zo6-MJ7awi00u:-KJeuZUgkymCFmjJiDrc:-499146009) ([raw file](https://github.com/servo/servo/blob/64c1e007bbde437dc9ddccdee960859f5083ce39/components/script/dom/bindings/codegen/CodegenRust.py#L5121)):*
<details><summary><i>Previously, Ms2ger wrote…</i></summary>
> Please don't use `hasInterfacePrototypeObject`; make this `if unscopableNames:` under the `if not descriptor.interface.isCallback():` block.
</details>
Done.

---

*[components/script/dom/webidls/ChildNode.webidl, line 11 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11620#-KJesQN1CQz94MbboxKw:-KJeyMHu8uRFzDs6LVeW:-499146009) ([raw file](https://github.com/servo/servo/blob/64c1e007bbde437dc9ddccdee960859f5083ce39/components/script/dom/webidls/ChildNode.webidl#L11)):*
<details><summary><i>Previously, Ms2ger wrote…</i></summary>
> I'd like all of those to be tested.  (idlharness?)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11620)*

**Comment by Ms2ger** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/wpt/web-platform-tests/dom/nodes/remove-unscopable.html, line 18 \[r2\]](https://reviewable.io:443/reviews/servo/servo/11620#-KJf0EMLTyU8ML3DWkKF:-KJf0EMLTyU8ML3DWkKG:626097259) ([raw file](https://github.com/servo/servo/blob/2419cb9a72435888b6f22294fa5d056c551d9c3a/tests/wpt/web-platform-tests/dom/nodes/remove-unscopable.html#L18)):*
> ```HTML
>     "append"
> ];
> for (i in unscopables) {
> ```

`var i`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11620)*

**Comment by Ms2ger** [comment]
@bors-servo r+

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11620#-:-KJf5KHDIB9qE96JGvx-:1236647940)*

**Pull request merged**
