### PR TITLE
Add support for navigating by a delta

### PR DESCRIPTION
**Pull request by cbrewster**
This adds support for passing a delta with `NavigationDirection`. This will be used with `history.go`

r? @asajeffrey 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because I am unsure how to write a test for this

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11616)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Reviewed 5 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/constellation/constellation.rs, line 1287 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11616#-KJXZtLe4CivTHrALaCN:-KJXZtLe4CivTHrALaCO:1335089486) ([raw file](https://github.com/servo/servo/blob/f2ee10c94b4f899e757258c1632961d44ab9d309/components/constellation/constellation.rs#L1287)):*
> ```Rust
>                             return warn!("Invalid navigation delta");
>                         }
>                         let mut new_current = frame.current;
> ```

Can we do this a bit more simply? Something like:
```rust
   let new_next_len = frame.next.len() - detta;
   frame.prev.push(frame.current);
   frame.prev.extend(frame.next.drain(new_next_len..).rev());
   frame.current = frame.next.pop().unwrap();
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11616)*

**Comment by ConnorGBrewster** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/constellation/constellation.rs, line 1287 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11616#-KJXZtLe4CivTHrALaCN:-KJcDepxlzSENpCmCwla:-499146009) ([raw file](https://github.com/servo/servo/blob/f2ee10c94b4f899e757258c1632961d44ab9d309/components/constellation/constellation.rs#L1287)):*
<details><summary><i>Previously, asajeffrey (Alan Jeffrey) wrote…</i></summary>
> Can we do this a bit more simply? Something like:
> ```rust
>    let new_next_len = frame.next.len() - detta;
>    frame.prev.push(frame.current);
>    frame.prev.extend(frame.next.drain(new_next_len..).rev());
>    frame.current = frame.next.pop().unwrap();
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11616)*

**Comment by asajeffrey** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r5.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11616)*

**Comment by KiChjang** [comment]
@bors-servo retry

* #11613

**Pull request merged**
