### PR TITLE
Implement distance for shadow list.

### PR DESCRIPTION
**Pull request by hiikezoe**
https://bugzilla.mozilla.org/show_bug.cgi?id=1387973
---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18102)

### CODE REVIEW

**Comment by hiikezoe** [comment]
- #18105 
@bors-servo retry

**Comment by jdm** [comment]
The android issues are unrelated to this PR. You can retry it normally.
@bors-servo: try-

**Comment by hiikezoe** [comment]
Good to know. :)
@bors-servo r=boris

**Pull request merged**
