### PR TITLE
Clean up the `Au` API

### LINKED ISSUE #5943: Clean up util::geometry API
* The naming is inconsistent: https://github.com/servo/servo/pull/5935#issuecomment-98880814
* `frac` and `subpx` seem to mean the same thing
* Some items are free functions and some are `Au` methods, for no apparent reason. Sometimes both exist and are redundant.

### PR DESCRIPTION
**Pull request by SimonSapin**
Fix #5943.

r? @mbrubeck

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5951)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Reviewed files:
- components/gfx/display_list/mod.rs @ r2
- components/gfx/filters.rs @ r2
- components/gfx/font_context.rs @ r2
- components/gfx/paint_context.rs @ r2
- components/gfx/paint_task.rs @ r3
- components/gfx/platform/freetype/font.rs @ r2
- components/gfx/platform/macos/font.rs @ r2
- components/gfx/text/glyph.rs @ r2
- components/gfx/text/shaping/harfbuzz.rs @ r2
- components/gfx/text/text_run.rs @ r1
- components/layout/block.rs @ r1
- components/layout/display_list_builder.rs @ r3
- components/layout/fragment.rs @ r3
- components/layout/inline.rs @ r2
- components/layout/layout_task.rs @ r2
- components/layout/model.rs @ r2
- components/layout/table.rs @ r2
- components/layout/table_wrapper.rs @ r2
- components/script/dom/htmlanchorelement.rs @ r2
- components/script/dom/htmlimageelement.rs @ r1
- components/script/dom/window.rs @ r2
- components/script/script_task.rs @ r2
- components/style/legacy.rs @ r3
- components/style/media_queries.rs @ r2
- components/style/properties.mako.rs @ r3
- components/style/values.rs @ r2
- components/util/geometry.rs @ r5

---

<sup>**[components/gfx/font_context.rs, line 39 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5951#-Jo_3yOprSMFFa6qhlVU)** ([raw file](https://github.com/servo/servo/blob/5f0c55cefb0c24a235ddbba05176c40f4799d007/components/gfx/font_context.rs#L39)):</sup>
`AzFloat` is an alias for `f32`.  Please change this to `to_f32_px` and remove the cast.

---

<sup>**[components/gfx/font_context.rs, line 45 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5951#-Jo_44zWI3ApSOhaLlKu)** ([raw file](https://github.com/servo/servo/blob/5f0c55cefb0c24a235ddbba05176c40f4799d007/components/gfx/font_context.rs#L45)):</sup>
Change this to `to_f32_px` and remove the cast.

---

<sup>**[components/gfx/paint_context.rs, line 838 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5951#-Jo_4J1R9Tl7wboheLjh)** ([raw file](https://github.com/servo/servo/blob/5f0c55cefb0c24a235ddbba05176c40f4799d007/components/gfx/paint_context.rs#L838)):</sup>
Change `to_f64_px() as AzFloat` to `to_f32_px()` throughout this file.

---

<sup>**[components/gfx/paint_context.rs, line 1107 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5951#-Jo_9F_FeTg0Fd0mFs0Y)** ([raw file](https://github.com/servo/servo/blob/5f0c55cefb0c24a235ddbba05176c40f4799d007/components/gfx/paint_context.rs#L1107)):</sup>
Should be `to_f32_px_azure_point` or maybe `to_azfloat_px_point`.

---

<sup>**[components/gfx/paint_context.rs, line 1121 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5951#-Jo_9T-FULDNY-Wj6z8-)** ([raw file](https://github.com/servo/servo/blob/5f0c55cefb0c24a235ddbba05176c40f4799d007/components/gfx/paint_context.rs#L1121)):</sup>
Should be `to_f32_px_azure_rect` or maybe `to_azfloat_px_rect`.

---

<sup>**[components/gfx/paint_task.rs, line 550 \[r5\]](https://reviewable.io:443/reviews/servo/servo/5951#-Jo_9YRi-dFVK9_IQSOA)** ([raw file](https://github.com/servo/servo/blob/5f0c55cefb0c24a235ddbba05176c40f4799d007/components/gfx/paint_task.rs#L550)):</sup>
Use `to_f32_px()`, no cast.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5951)

**Comment by mbrubeck** [comment]
Found some pre-existing issues in gfx.  They don't need to block landing this, but please either fix them or file a follow-up.  Thanks!

**Comment by mbrubeck** [comment]
Reviewed files:
- components/gfx/display_list/mod.rs @ r7
- components/gfx/font_context.rs @ r6
- components/gfx/paint_context.rs @ r7
- components/gfx/paint_task.rs @ r6

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5951)

**Comment by jdm** [comment]
The retry was for #5928.

**Pull request merged**
