### PR TITLE
 Update backtrace to 0.3.46

### PR DESCRIPTION
**Pull request by nox**
https://github.com/rust-lang/backtrace-rs/pull/299 landed so we can stop patching backtrace in our tree.

### CODE REVIEW

**Comment by jdm** [comment]
Looks like we now actually pick up the panics from #25838 correctly?

**Comment by nox** [comment]
Sorry I fail to connect your comment and the linked issue to the failures. Do you mean that those new timeouts and whatnot are good news?

**Comment by jdm** [comment]
@bors-servo retry
Let's see if it's consistent.

**Comment by CYBAI** [comment]
>  Let's see if it's consistent.

Looks like sadly yes?

<details>

```
5 unexpected results that are NOT known-intermittents:
  â–¶ CRASH [expected PASS] /css/css-paint-api/geometry-border-image-005.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ Shutting down the Constellation after generating an output file or exit flag specified
  â”‚ called `Option::unwrap()` on a `None` value (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/script_thread.rs:1126)
  â”‚    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  â”‚    1: core::fmt::write
  â”‚    2: std::io::Write::write_fmt
  â”‚    3: servo::backtrace::print
  â”‚    4: servo::main::{{closure}}
  â”‚    5: std::panicking::rust_panic_with_hook
  â”‚    6: rust_begin_unwind
  â”‚    7: core::panicking::panic_fmt
  â”‚    8: core::panicking::panic
  â”‚    9: std::thread::local::LocalKey<T>::with
  â”‚   10: <script::dom::worklet::Worklet as core::ops::drop::Drop>::drop
  â”‚   11: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  â”‚   12: script::dom::bindings::codegen::Bindings::WorkletBinding::WorkletBinding::_finalize
  â”‚   13: _ZN2js2gc5Arena8finalizeI8JSObjectEEmP8JSFreeOpNS0_9AllocKindEm
  â”‚   14: _ZL19FinalizeTypedArenasI8JSObjectEbP8JSFreeOpPPN2js2gc5ArenaERNS4_15SortedArenaListENS4_9AllocKindERNS3_11SliceBudgetE
  â”‚   15: _ZN2js2gc10ArenaLists18foregroundFinalizeEP8JSFreeOpNS0_9AllocKindERNS_11SliceBudgetERNS0_15SortedArenaListE
  â”‚   16: _ZN2js2gc9GCRuntime17finalizeAllocKindEP8JSFreeOpRNS_11SliceBudgetE
  â”‚   17: _ZN11sweepaction18SweepActionForEachI13ContainerIterIN7mozilla7EnumSetIN2js2gc9AllocKindEyEEES7_E3runERNS5_11SweepAction4ArgsE
  â”‚   18: _ZN11sweepaction19SweepActionSequence3runERN2js2gc11SweepAction4ArgsE
  â”‚   19: _ZN11sweepaction18SweepActionForEachIN2js2gc19SweepGroupZonesIterEP9JSRuntimeE3runERNS2_11SweepAction4ArgsE
  â”‚   20: _ZN11sweepaction19SweepActionSequence3runERN2js2gc11SweepAction4ArgsE
  â”‚   21: _ZN11sweepaction18SweepActionForEachIN2js2gc15SweepGroupsIterEP9JSRuntimeE3runERNS2_11SweepAction4ArgsE
  â”‚   22: _ZN2js2gc9GCRuntime19performSweepActionsERNS_11SliceBudgetE
  â”‚   23: _ZN2js2gc9GCRuntime16incrementalSliceERNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonERNS0_13AutoGCSessionE
  â”‚   24: _ZN2js2gc9GCRuntime7gcCycleEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE
  â”‚   25: _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE
  â”‚   26: _ZN2js2gc9GCRuntime2gcE18JSGCInvocationKindN2JS8GCReasonE
  â”‚   27: _ZN9JSRuntime14destroyRuntimeEv
  â”‚   28: _ZN2js14DestroyContextEP9JSContext
  â”‚   29: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop
  â”‚   30: _ZN4core3ptr13drop_in_place17h7560d1b523e40b05E.llvm.751501371373097516
  â”‚   31: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  â”‚   32: core::ptr::drop_in_place
  â”‚   33: std::sys_common::backtrace::__rust_begin_short_backtrace
  â”‚   34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  â”‚   35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  â”‚   36: std::sys::unix::thread::Thread::new::thread_start
  â”‚   37: AssociationsManager::_map
  â”‚   38: AssociationsManager::_map
  â”‚ [2020-03-25T12:11:15Z ERROR servo] called `Option::unwrap()` on a `None` value
  â”‚ Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }"
  â”‚    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  â”‚    1: core::fmt::write
  â”‚    2: std::io::Write::write_fmt
  â”‚    3: servo::backtrace::print
  â”‚    4: servo::install_crash_handler::handler
  â””    5: AssociationsManager::_map


  â–¶ CRASH [expected PASS] /css/css-paint-api/geometry-border-image-003.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ Shutting down the Constellation after generating an output file or exit flag specified
  â”‚ called `Option::unwrap()` on a `None` value (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/script_thread.rs:1126)
  â”‚    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  â”‚    1: core::fmt::write
  â”‚    2: std::io::Write::write_fmt
  â”‚    3: servo::backtrace::print
  â”‚    4: servo::main::{{closure}}
  â”‚    5: std::panicking::rust_panic_with_hook
  â”‚    6: rust_begin_unwind
  â”‚    7: core::panicking::panic_fmt
  â”‚    8: core::panicking::panic
  â”‚    9: std::thread::local::LocalKey<T>::with
  â”‚   10: <script::dom::worklet::Worklet as core::ops::drop::Drop>::drop
  â”‚   11: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  â”‚   12: script::dom::bindings::codegen::Bindings::WorkletBinding::WorkletBinding::_finalize
  â”‚   13: _ZN2js2gc5Arena8finalizeI8JSObjectEEmP8JSFreeOpNS0_9AllocKindEm
  â”‚   14: _ZL19FinalizeTypedArenasI8JSObjectEbP8JSFreeOpPPN2js2gc5ArenaERNS4_15SortedArenaListENS4_9AllocKindERNS3_11SliceBudgetE
  â”‚   15: _ZN2js2gc10ArenaLists18foregroundFinalizeEP8JSFreeOpNS0_9AllocKindERNS_11SliceBudgetERNS0_15SortedArenaListE
  â”‚   16: _ZN2js2gc9GCRuntime17finalizeAllocKindEP8JSFreeOpRNS_11SliceBudgetE
  â”‚   17: _ZN11sweepaction18SweepActionForEachI13ContainerIterIN7mozilla7EnumSetIN2js2gc9AllocKindEyEEES7_E3runERNS5_11SweepAction4ArgsE
  â”‚   18: _ZN11sweepaction19SweepActionSequence3runERN2js2gc11SweepAction4ArgsE
  â”‚   19: _ZN11sweepaction18SweepActionForEachIN2js2gc19SweepGroupZonesIterEP9JSRuntimeE3runERNS2_11SweepAction4ArgsE
  â”‚   20: _ZN11sweepaction19SweepActionSequence3runERN2js2gc11SweepAction4ArgsE
  â”‚   21: _ZN11sweepaction18SweepActionForEachIN2js2gc15SweepGroupsIterEP9JSRuntimeE3runERNS2_11SweepAction4ArgsE
  â”‚   22: _ZN2js2gc9GCRuntime19performSweepActionsERNS_11SliceBudgetE
  â”‚   23: _ZN2js2gc9GCRuntime16incrementalSliceERNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonERNS0_13AutoGCSessionE
  â”‚   24: _ZN2js2gc9GCRuntime7gcCycleEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE
  â”‚   25: _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE
  â”‚   26: _ZN2js2gc9GCRuntime2gcE18JSGCInvocationKindN2JS8GCReasonE
  â”‚   27: _ZN9JSRuntime14destroyRuntimeEv
  â”‚   28: _ZN2js14DestroyContextEP9JSContext
  â”‚   29: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop
  â”‚   30: _ZN4core3ptr13drop_in_place17h7560d1b523e40b05E.llvm.751501371373097516
  â”‚   31: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  â”‚   32: core::ptr::drop_in_place
  â”‚   33: std::sys_common::backtrace::__rust_begin_short_backtrace
  â”‚   34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  â”‚   35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  â”‚   36: std::sys::unix::thread::Thread::new::thread_start
  â”‚   37: AssociationsManager::_map
  â”‚   38: AssociationsManager::_map
  â”‚ [2020-03-25T12:11:20Z ERROR servo] called `Option::unwrap()` on a `None` value
  â”‚ Stack trace
  â”‚    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  â”‚    1: core::fmt::write
  â”‚    2: std::io::Write::write_fmt
  â”‚    3: servo::backtrace::print
  â”‚    4: servo::install_crash_handler::handler
  â””    5: AssociationsManager::_map


  â–¶ CRASH [expected PASS] /css/css-paint-api/invalid-image-paint-error.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ Shutting down the Constellation after generating an output file or exit flag specified
  â”‚ called `Option::unwrap()` on a `None` value (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/script_thread.rs:1126)
  â”‚    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  â”‚    1: core::fmt::write
  â”‚    2: std::io::Write::write_fmt
  â”‚    3: servo::backtrace::print
  â”‚    4: servo::main::{{closure}}
  â”‚    5: std::panicking::rust_panic_with_hook
  â”‚    6: rust_begin_unwind
  â”‚    7: core::panicking::panic_fmt
  â”‚    8: core::panicking::panic
  â”‚    9: std::thread::local::LocalKey<T>::with
  â”‚   10: <script::dom::worklet::Worklet as core::ops::drop::Drop>::drop
  â”‚   11: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  â”‚   12: script::dom::bindings::codegen::Bindings::WorkletBinding::WorkletBinding::_finalize
  â”‚   13: _ZN2js2gc5Arena8finalizeI8JSObjectEEmP8JSFreeOpNS0_9AllocKindEm
  â”‚   14: _ZL19FinalizeTypedArenasI8JSObjectEbP8JSFreeOpPPN2js2gc5ArenaERNS4_15SortedArenaListENS4_9AllocKindERNS3_11SliceBudgetE
  â”‚   15: _ZN2js2gc10ArenaLists18foregroundFinalizeEP8JSFreeOpNS0_9AllocKindERNS_11SliceBudgetERNS0_15SortedArenaListE
  â”‚   16: _ZN2js2gc9GCRuntime17finalizeAllocKindEP8JSFreeOpRNS_11SliceBudgetE
  â”‚   17: _ZN11sweepaction18SweepActionForEachI13ContainerIterIN7mozilla7EnumSetIN2js2gc9AllocKindEyEEES7_E3runERNS5_11SweepAction4ArgsE
  â”‚   18: _ZN11sweepaction19SweepActionSequence3runERN2js2gc11SweepAction4ArgsE
  â”‚   19: _ZN11sweepaction18SweepActionForEachIN2js2gc19SweepGroupZonesIterEP9JSRuntimeE3runERNS2_11SweepAction4ArgsE
  â”‚   20: _ZN11sweepaction19SweepActionSequence3runERN2js2gc11SweepAction4ArgsE
  â”‚   21: _ZN11sweepaction18SweepActionForEachIN2js2gc15SweepGroupsIterEP9JSRuntimeE3runERNS2_11SweepAction4ArgsE
  â”‚   22: _ZN2js2gc9GCRuntime19performSweepActionsERNS_11SliceBudgetE
  â”‚   23: _ZN2js2gc9GCRuntime16incrementalSliceERNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonERNS0_13AutoGCSessionE
  â”‚   24: _ZN2js2gc9GCRuntime7gcCycleEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE
  â”‚   25: _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE
  â”‚   26: _ZN2js2gc9GCRuntime2gcE18JSGCInvocationKindN2JS8GCReasonE
  â”‚   27: _ZN9JSRuntime14destroyRuntimeEv
  â”‚   28: _ZN2js14DestroyContextEP9JSContext
  â”‚   29: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop
  â”‚   30: _ZN4core3ptr13drop_in_place17h7560d1b523e40b05E.llvm.751501371373097516
  â”‚   31: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  â”‚   32: core::ptr::drop_in_place
  â”‚   33: std::sys_common::backtrace::__rust_begin_short_backtrace
  â”‚   34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  â”‚   35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  â”‚   36: std::sys::unix::thread::Thread::new::thread_start
  â”‚   37: AssociationsManager::_map
  â”‚   38: AssociationsManager::_map
  â”‚ [2020-03-25T12:11:25Z ERROR servo] called `Option::unwrap()` on a `None` value
  â”‚ servo(41974,0x70001757c000) malloc: *** error for object 0x14b66a126580: pointer being freed was not allocated
  â”‚ *** set a breakpoint in malloc_error_break to debug
  â”‚ Stack trace
  â”‚    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  â”‚    1: core::fmt::write
  â”‚    2: std::io::Write::write_fmt
  â”‚    3: servo::backtrace::print
  â”‚    4: servo::install_crash_handler::handler
  â””    5: AssociationsManager::_map


  â–¶ TIMEOUT [expected FAIL] /css/css-paint-api/background-image-tiled.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ Shutting down the Constellation after generating an output file or exit flag specified
  â”‚ called `Option::unwrap()` on a `None` value (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/script_thread.rs:1126)
  â”‚    0: <servo::backtrace::Print as core::fmt::Debug>::fmt
  â”‚    1: core::fmt::write
  â”‚    2: std::io::Write::write_fmt
  â”‚    3: servo::backtrace::print
  â”‚    4: servo::main::{{closure}}
  â”‚    5: std::panicking::rust_panic_with_hook
  â”‚    6: rust_begin_unwind
  â”‚    7: core::panicking::panic_fmt
  â”‚    8: core::panicking::panic
  â”‚    9: std::thread::local::LocalKey<T>::with
  â”‚   10: <script::dom::worklet::Worklet as core::ops::drop::Drop>::drop
  â”‚   11: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  â”‚   12: script::dom::bindings::codegen::Bindings::WorkletBinding::WorkletBinding::_finalize
  â”‚   13: _ZN2js2gc5Arena8finalizeI8JSObjectEEmP8JSFreeOpNS0_9AllocKindEm
  â”‚   14: _ZL19FinalizeTypedArenasI8JSObjectEbP8JSFreeOpPPN2js2gc5ArenaERNS4_15SortedArenaListENS4_9AllocKindERNS3_11SliceBudgetE
  â”‚   15: _ZN2js2gc10ArenaLists18foregroundFinalizeEP8JSFreeOpNS0_9AllocKindERNS_11SliceBudgetERNS0_15SortedArenaListE
  â”‚   16: _ZN2js2gc9GCRuntime17finalizeAllocKindEP8JSFreeOpRNS_11SliceBudgetE
  â”‚   17: _ZN11sweepaction18SweepActionForEachI13ContainerIterIN7mozilla7EnumSetIN2js2gc9AllocKindEyEEES7_E3runERNS5_11SweepAction4ArgsE
  â”‚   18: _ZN11sweepaction19SweepActionSequence3runERN2js2gc11SweepAction4ArgsE
  â”‚   19: _ZN11sweepaction18SweepActionForEachIN2js2gc19SweepGroupZonesIterEP9JSRuntimeE3runERNS2_11SweepAction4ArgsE
  â”‚   20: _ZN11sweepaction19SweepActionSequence3runERN2js2gc11SweepAction4ArgsE
  â”‚   21: _ZN11sweepaction18SweepActionForEachIN2js2gc15SweepGroupsIterEP9JSRuntimeE3runERNS2_11SweepAction4ArgsE
  â”‚   22: _ZN2js2gc9GCRuntime19performSweepActionsERNS_11SliceBudgetE
  â”‚   23: _ZN2js2gc9GCRuntime16incrementalSliceERNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonERNS0_13AutoGCSessionE
  â”‚   24: _ZN2js2gc9GCRuntime7gcCycleEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE
  â”‚   25: _ZN2js2gc9GCRuntime7collectEbNS_11SliceBudgetERKN7mozilla5MaybeI18JSGCInvocationKindEEN2JS8GCReasonE
  â”‚   26: _ZN2js2gc9GCRuntime2gcE18JSGCInvocationKindN2JS8GCReasonE
  â”‚   27: _ZN9JSRuntime14destroyRuntimeEv
  â”‚   28: _ZN2js14DestroyContextEP9JSContext
  â”‚   29: <mozjs::rust::Runtime as core::ops::drop::Drop>::drop
  â”‚   30: _ZN4core3ptr13drop_in_place17h7560d1b523e40b05E.llvm.751501371373097516
  â”‚   31: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  â”‚   32: core::ptr::drop_in_place
  â”‚   33: std::sys_common::backtrace::__rust_begin_short_backtrace
  â”‚   34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  â”‚   35: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  â”‚   36: std::sys::unix::thread::Thread::new::thread_start
  â”‚   37: AssociationsManager::_map
  â”‚   38: AssociationsManager::_map
  â”‚ [2020-03-25T12:11:15Z ERROR servo] called `Option::unwrap()` on a `None` value
  â”‚ 18 threads are still running after shutdown (bad).
  â”‚ servo(41918,0x7fffa9364380) malloc: *** error for object 0x7f9643357a00: pointer being freed was not allocated
  â”‚ *** set a breakpoint in malloc_error_break to debug
  â”” thread panicked while processing panic. aborting.


  â–¶ TIMEOUT [expected FAIL] /css/css-paint-api/one-custom-property-animation.https.html
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ 
  â”‚ [2020-03-25T12:11:20Z ERROR script::dom::bindings::error] Error at https://web-platform.test:8443/css/css-paint-api/one-custom-property-animation.https.html:42:5 CSS.registerProperty is not a function
  â”‚ Shutting down the Constellation after generating an output file or exit flag specified
  â”‚ called `Option::unwrap()` on a `None` value (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }, at components/script/script_thread.rs:1126)
  â”” Stack trace for thread "ScriptThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(1) }"
```

</details>

**Comment by jdm** [comment]
I'm not sad about that - it means that we're actually reporting real results from those tests now.

**Comment by jdm** [comment]
Specifically, we've seen these panics intermittently in the past: #25258

**Comment by nox** [comment]
@jdm So I should just update the expectations and be done with it?

**Comment by jdm** [comment]
I would say yes.

**Comment by nox** [comment]
So for the failures in "Servo: macOS x64: WPT chunk 06 / 20", in [the first round](https://community-tc.services.mozilla.com/tasks/I2-8HYXJTUC6R90eD7LSBg/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FI2-8HYXJTUC6R90eD7LSBg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) we got:

* CRASH [expected FAIL] /css/css-paint-api/background-image-tiled.https.html
* CRASH [expected PASS] /css/css-paint-api/geometry-background-image-002.https.html
* TIMEOUT [expected PASS] /css/css-paint-api/non-registered-property-value.https.html
* TIMEOUT [expected FAIL] /css/css-paint-api/geometry-with-float-size.https.html
* TIMEOUT [expected PASS] /css/css-paint-api/paint-function-arguments.https.html
* TIMEOUT [expected PASS] /css/css-paint-api/invalid-image-paint-error.https.html
* TIMEOUT [expected PASS] /css/css-paint-api/parse-input-arguments-016.https.html
* TIMEOUT [expected PASS] /css/css-paint-api/parse-input-arguments-019.https.html
* CRASH [expected PASS] /css/css-paint-api/setTransform-002.https.html
* CRASH [expected FAIL] /css/css-paint-api/style-background-image.https.html

In [the second](https://community-tc.services.mozilla.com/tasks/WJ5bstgoTumf2Lr_d7wsTA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FWJ5bstgoTumf2Lr_d7wsTA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log), we got:

* CRASH [expected PASS] /css/css-paint-api/geometry-border-image-005.https.html
* CRASH [expected PASS] /css/css-paint-api/geometry-border-image-003.https.html
* CRASH [expected PASS] /css/css-paint-api/invalid-image-paint-error.https.html
* TIMEOUT [expected FAIL] /css/css-paint-api/background-image-tiled.https.html
* /css/css-paint-api/one-custom-property-animation.https.html

So yes it is consistent that there are panics and whatnot, but the failures themselves are all intermittent and I want to cry.

Many of them I couldn't reproduce locally and sometimes I got TIMEOUT instead of CRASH.

**Comment by nox** [comment]
It just occurred to me that I once again didn't look at the right section in the test results, so disregard that.

**Comment by MeFisto94** [comment]
Actually the new backtrace version should be able to load more debugging symbols than my fork, but it shouldn't "see" new panics, I think.

But then there were more changes to backtrace, so the only way to really verify this is by looking at the individual issues and checking if they are correct fails.

Anyway: This Fixes #24984, don't forget to close the issue once this is merged.

**Pull request closed without merging**
