### PR TITLE
Support line-height in geckolib

### PR DESCRIPTION
**Pull request by mbrubeck**
r? @bholley

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11445)

### CODE REVIEW

**Comment by bholley** [comment]
I need to start culling stuff before PTO. @heycam can you review?

**Comment by emilio** [comment]
r=me with that question answered/nit addressed if needed.

-S-awaiting-review +S-awaiting-answer 

<details><summary><i>Previously, bors-servo wrote…</i></summary>
> :v: @heycam can now approve this pull request
</details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/style/properties/longhand/inherited_text.mako.rs, line 18 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11445#-KIohHYud7Uj5idygs78:-KIohHYvuhRFCkpEzjGp:228249574) ([raw file](https://github.com/servo/servo/blob/1389fbe6ff1054ccc1565a39e682fffefec9c304/components/style/properties/longhand/inherited_text.mako.rs#L18)):*
> ```Rust
>     pub enum SpecifiedValue {
>         Normal,
>         % if product == "gecko":
> ```

Well, I can't say I really like this, but I can't think of anything better without introducing yet another generic type around, so...

---

*[ports/geckolib/properties.mako.rs, line 741 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11445#-KIohxMy9dgcScpVoU9Z:-KIohxMy9dgcScpVoU9_:-1593393205) ([raw file](https://github.com/servo/servo/blob/1389fbe6ff1054ccc1565a39e682fffefec9c304/ports/geckolib/properties.mako.rs#L741)):*
> ```Rust
>     fn copy_line_height_from(&mut self, other: &Self) {
>         debug_assert_unit_is_safe_to_copy(self.gecko.mLineHeight.mUnit);
>         self.gecko.mLineHeight.mUnit = other.gecko.mLineHeight.mUnit;
> ```

Hum... can't you do `self.gecko.mLineHeight = other.gecko.mLineHeight`?

If you can't maybe this should be a good thing to factor out (though if it's just used here and you want to land it it's fine for me).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11445#-:-KIoixyqWyNzZrOkvQrK:908880241)*

**Comment by mbrubeck** [comment]
@bors-servo r=emilio

> Hum... can't you do `self.gecko.mLineHeight = other.gecko.mLineHeight`?
>
> If you can't maybe this should be a good thing to factor out (though if it's just used here and you want to land it it's fine for me).

We can't do that because nsStyleCoord isn't Copy. We can't just implement Copy or Clone and then reassign, because we also need to check whether it's refcounted. Long-term we can implement refcounting using Clone and Drop. For new I factored out the debug assertion into a new method.

**Comment by jdm** [comment]
@bors-servo: retry
* #8815

**Comment by emilio** [comment]
@bors-servo: retry 
 * git

**Pull request merged**
