### PR TITLE
Add Servo_GetStyleFoo functions to get style structs from GeckoComputedValues

### PR DESCRIPTION
**Pull request by heycam**
r?@bholley

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10848)

### CODE REVIEW

**Comment by bholley** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/style/properties/data.py, line 112 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10848#-KGJfGXskgCKR8iWJhdO:-KGJfGXt2MsDaTi20h4l:2060900265) ([raw file](https://github.com/servo/servo/blob/9f224d40423499d04489296b6321db3367467cba/components/style/properties/data.py#L112)):*
This seems like the wrong place for this.

If we want to remove nsStyle* from the naming, here's what I'd propose:
* Replace the gecko_ffi_name kwarg with a gecko_name kwarg that takes things of the form "Display" rather than "nsStyleDisplay". If omitted, the __init__ method can just assume that it's equivalent to |name|.
* Compute gecko_ffi_name from gecko_name.

---

*[ports/geckolib/properties.mako.rs, line 15 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10848#-KGJgqLMCiF3M9LErhhQ:-KGJgqLN96hKGfYHYiaJ:412382258) ([raw file](https://github.com/servo/servo/blob/9f224d40423499d04489296b6321db3367467cba/ports/geckolib/properties.mako.rs#L15)):*
Instead of doing this, I think we should just add these style structs to components/style, since we'll need it eventually anyway. Simon said it was fine to do that and not make it conditional on product.

---

*[ports/geckolib/properties.mako.rs, line 117 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10848#-KGJitphCxPv5LSnm7pW:-KGJitphCxPv5LSnm7pX:-1195579862) ([raw file](https://github.com/servo/servo/blob/9f224d40423499d04489296b6321db3367467cba/ports/geckolib/properties.mako.rs#L117)):*
I think we can actually remove all the stuff that's conditional on having a gecko_ffi_name (several places in this file), which will allow us to fold this into the other impl block.

---

*[ports/geckolib/properties.mako.rs, line 430 \[r1\]](https://reviewable.io:443/reviews/servo/servo/10848#-KGJjOTUoRtXwGMouUew:-KGJjOTUoRtXwGMouUex:-1660070988) ([raw file](https://github.com/servo/servo/blob/9f224d40423499d04489296b6321db3367467cba/ports/geckolib/properties.mako.rs#L430)):*
Generally rust uses 4-space indents, even for continuations I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10848)*

**Comment by bholley** [comment]
Looks good modulo that one nit. Don't forget to update the spreadsheet with the newly-added style structs and newly-supported properties.

---

Reviewed 26 of 26 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ports/geckolib/properties.mako.rs, line 221 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10848#-KGLUlVZMcQHte5YN-SP:-KGLUlV_-Uo8-AzPSEQG:-1293460035) ([raw file](https://github.com/servo/servo/blob/645b5905844c3315083d955bf098fbeb3ea9b4cf/ports/geckolib/properties.mako.rs#L221)):*
This change should be reverted, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10848#-:-KGLV9Z3SBQR1PsnDRuE:-552020434)*

**Comment by heycam** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ports/geckolib/properties.mako.rs, line 221 \[r2\]](https://reviewable.io:443/reviews/servo/servo/10848#-KGLUlVZMcQHte5YN-SP:-KGLVtGWkZ8wvb5AiOoB:1253024292) ([raw file](https://github.com/servo/servo/blob/645b5905844c3315083d955bf098fbeb3ea9b4cf/ports/geckolib/properties.mako.rs#L221)):*
Yes it should.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10848)*

**Pull request merged**
