### PR TITLE
Enable Custom Elements by Default

### LINKED ISSUE #9372: Implement Custom Elements
Implement Custom Elements in Servo

https://w3c.github.io/webcomponents/spec/custom/

Related to #9370

### PR DESCRIPTION
**Pull request by cbrewster**
---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #9372 (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because enabling pref flag.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/18317)

### CODE REVIEW

**Comment by cbrewster** [comment]
Added `CustomElementRegistry` as an exposed interface.

**Comment by cbrewster** [comment]
Forgot `update-manifest`
@bors-servo r=jdm

**Comment by heycam** [comment]
@bors-servo r=jdm

(Trying to kickstart homu.)

**Comment by motss** [comment]
Nice. Well done Servo team! 🎉

**Pull request merged**
