### PR TITLE
Don't set root font size when styling NAC

### PR DESCRIPTION
**Pull request by Manishearth**
try at https://treeherder.mozilla.org/#/jobs?repo=try&revision=ad4acc4941dd91d10e3646ecd7fa03576fc75342

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17057)

### CODE REVIEW

**Comment by jdm** [comment]
Test-tidy failed.

**Comment by Manishearth** [comment]
@bors-servo r=emilio

 - infra exception

**Pull request merged**
