### PR TITLE
Derive the most trivial ToCss implementations 🌋

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17152)

### CODE REVIEW

**Comment by nox** [comment]
r? @emilio
@bors-servo try
https://treeherder.mozilla.org/#/jobs?repo=try&revision=0c11c62296da8a3df79dca8c818b4a2f5c9532b2

**Review by emilio — APPROVED** [review]
r=me, with a green GeckoTry :)

**Comment by nox** [comment]
Fixed the unused imports.

https://treeherder.mozilla.org/#/jobs?repo=try&revision=b91fadf89ee943713d65bb80b39660e83c6b4dec

**Comment by nox** [comment]
Gecko try run is happy.

@bors-servo r=emilio

**Pull request merged**
