### PR TITLE
[new] Input line height reftest

### PR DESCRIPTION
**Pull request by iamajoe**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10648)

### CODE REVIEW

**Comment by Sendoushi** [comment]
Done for https://github.com/servo/servo/issues/10532 and part of this request: https://github.com/servo/servo/pull/10553

**Comment by pcwalton** [comment]
I think this needs another change in the `MANIFEST.json`... `mach create-wpt` does this for you.

**Comment by KiChjang** [comment]
Or you can just paste this diff into `MANIFEST.json`:
```
$ bash etc/ci/manifest_changed.sh

diff --git a/tests/wpt/mozilla/meta/MANIFEST.json b/tests/wpt/mozilla/meta/MANIFEST.json

index 35c0b2c..906700a 100644

--- a/tests/wpt/mozilla/meta/MANIFEST.json

+++ b/tests/wpt/mozilla/meta/MANIFEST.json

@@ -9325,6 +9325,18 @@

           "url": "/_mozilla/css/input_insertion_point_empty_a.html"

         }

       ],

+      "css/input_line_height.html": [

+        {

+          "path": "css/input_line_height.html",

+          "references": [

+            [

+              "/_mozilla/css/input_line_height_ref.html",

+              "=="

+            ]

+          ],

+          "url": "/_mozilla/css/input_line_height.html"

+        }

+      ],

       "css/input_placeholder.html": [

         {

           "path": "css/input_placeholder.html",
```

**Comment by Sendoushi** [comment]
I'll check the `MANIFEST` again. `create-wpt` was giving me errors so I proceeded manually.

**Comment by Sendoushi** [comment]
I'll close this because it is now merged with the other PR.

**Pull request closed without merging**
