### PR TITLE
Remove stacking context nesting from WebRender display construction

### PR DESCRIPTION
**Pull request by mrobinson**
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because they should not produce any behavior changes.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13873)

### CODE REVIEW

**Comment by mrobinson** [comment]
@glennw r?

Here is the other half of the previous WebRender PR.

**Comment by mrobinson** [comment]
This failure seems to be #13605, so I think all the tests are passing.

**Comment by glennw** [comment]
@mrobinson r=me when rebased.

**Comment by jdm** [comment]
@bors-servo: retry
* #13605

**Comment by jdm** [comment]
@bors-servo: retry
* #13605

**Comment by jdm** [comment]
@bors-servo: r-
#13605 seems to be perma-timing out with this change.

**Comment by jdm** [comment]
Wait, why is disabling the test that started timing out on every run the appropriate action here?

**Comment by glennw** [comment]
My reasoning was:

* We semi-regularly disable tests that are causing intermittent CI failures (the test in question has caused several CI failures in the last two weeks before this PR).
* The expected test result was FAIL due to pre-existing race conditions, so it wasn't providing a particularly useful result anyway.
* The permanent timeout appears unrelated to this change itself - I could not reproduce it on two local machines with this change.

Is that fair enough?

**Comment by jdm** [comment]
Yep!

**Pull request merged**
