### PR TITLE
Rollup of 7 pull requests

### PR DESCRIPTION
**Pull request by nox**
- Successful merges: #16885, #16886, #16932, #16939, #16948, #16986, #16995
- Failed merges:

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/17004)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: r-
Test-wpt fails.

**Comment by emilio** [comment]
> :::: no merge commits allowed, please rebase your commits over the upstream master branch

Fun

**Comment by nox** [comment]
```
Downloading Host rust library for target x86_64-unknown-linux-gnu...
Looks like there's a connectivity issue, check your Internet connection. [Errno 104] Connection reset by peer
```

Why must we suffer like that?!

@bors-servo retry

**Pull request merged**
