### PR TITLE
Remove parsed attribute 'bgcolor' field HTMLTableElement

### PR DESCRIPTION
**Pull request by frewsxcv**
https://github.com/servo/servo/issues/7863

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9111)

### CODE REVIEW

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/9111#-:-K71NnhDUwkOvuo4zzdi:1236647940)*

**Comment by KiChjang** [comment]
@bors-servo retry
* #8769

**Pull request merged**
