### PR TITLE
Return ErrorStatus from webdriver_handlers

### PR DESCRIPTION
**Pull request by georgeroman**
With `webdriver 0.40`, `ErrorStatus` implements `Deserialize`. Now we can accommodate for multiple errors occuring in `webdriver_handlers`.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23951)

### CODE REVIEW

**Comment by georgeroman** [comment]
Hmm, it looks like [`find_node_by_unique_id`](https://github.com/servo/servo/blob/9b4b02275e52330538acba9248457a07b680d967/components/script/webdriver_handlers.rs#L56) fails to find staled elements, as they are reported as not found. Is there a workaround to iterate through all of the elements in a document, including the ones that have been discarded?

**Comment by jdm** [comment]
> Hmm, it looks like [`find_node_by_unique_id`](https://github.com/servo/servo/blob/9b4b02275e52330538acba9248457a07b680d967/components/script/webdriver_handlers.rs#L56) fails to find staled elements, as they are reported as not found. Is there a workaround to iterate through all of the elements in a document, including the ones that have been discarded?

Right, find_node_by_unique_id only traverses the elements of the active document, which by definition will not find any [stale](https://w3c.github.io/webdriver/#dfn-is-stale) elements. Maybe it's enough to assume that if find_node_by_unique_id returns None then it's a stale element reference?

**Comment by jdm** [comment]
Another option would be to store a HashSet of unique IDs ever created in ScriptThread and use that to determine if a element is stale or if there is no such node at all.

**Review by jdm — APPROVED** [review]
These changes generally look fine. I would recommend going with the hashset approach and making find_node_by_unique_id return Result so you can differentiate between stale and nonexistent elements.

**Comment by georgeroman** [comment]
I have one question regarding the HashSet approach. I looked over [`script_thread.rs`](https://github.com/servo/servo/blob/master/components/script/script_thread.rs) and I'm not really sure how to go about keeping track of the newly added nodes. Is using a [`MutationObserver`](https://github.com/servo/servo/blob/ec2ca08e8e047ba7a23d31d8ad3c37d502efb76a/components/script/dom/mutationobserver.rs#L67) a good choice to do this?

**Comment by jdm** [comment]
Rather than a mutation observer, I was imagining that get_unique_id would add an entry to the hash set when it generates an id.

**Comment by jdm** [comment]
@bors-servo  retry
* #23290

**Pull request merged**
