### PR TITLE
Update WR (opaque rect optimization, stacking context culling).

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16113)

### CODE REVIEW

**Comment by glennw** [comment]
@mrobinson This contains the most recent WR update, and has the two failing viewport tests that we discussed.

I've added one expected failure for one of the border tests, which was previously being incorrectly detected as a pass.

There might be a couple of other new passes in the CSS tests, but this should be usable as a base to fix up the viewport tests.

**Comment by mrobinson** [comment]
@glennw Okay. I've created a branch with the viewport fixes here: https://github.com/mrobinson/servo/tree/wr-update . You should be able to cherry-pick that patch and this PR should be good to go. r=me when you are ready.

**Comment by mrobinson** [comment]
@glennw Sorry. I didn't realize that I had to update the manifest file as well. I've updated the patch in my branch with the new manifest entry.

**Comment by glennw** [comment]
@mrobinson OK, I think I've cherry picked the updated patch correctly - if you want to double check and r+ it :)

**Comment by mrobinson** [comment]
Looks good to me!

**Comment by mrobinson** [comment]
Looks like /css-transforms-1_dev/html/transform-abspos-006.htm and /css-values-3_dev/html/calc-border-radius-1.htm and passing now. I can confirm those are passing locally as well.

**Comment by nox** [comment]
The commits in that branch should be squashed together, the first one doesn't pass the test modified in the second.

**Pull request merged**
