### PR TITLE
Enable css-fonts WPT tests

### PR DESCRIPTION
**Pull request by jonleighton**
See https://github.com/servo/servo/pull/19928#issuecomment-362354270

Note that some of these tests require you to install the fonts found in
tests/wpt/web-platform-tests/css/fonts.

r? @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/19930)

### CODE REVIEW

**Comment by jonleighton** [comment]
As discussed in IRC, this will need the relevant fonts to be installed on the builders. Let me know if I can do anything to help on that front.

Also, I can only test this on Linux. I wonder if there might be platform differences? (The original bug I was trying to fix only occurs on Linux...)

**Comment by jdm** [comment]
I bet the timeouts are caused by Servo not supporting `document.fonts.ready`.

@bors-servo r+

**Comment by jonleighton** [comment]
Sorry, my branch was not up to date with master (updating it now). That's the cause of the `font-feature-settings-serialization-001.html` one (which has been added recently). I don't know the cause of the other failure though...

**Comment by jonleighton** [comment]
@jdm I think this should merge now. `font-variant-ligatures-11.html` was passing for me because on my system, all of the special glyphs were rendering as a square "glyph not found" box, and therefore the test matched the ref. I manually added a metadata file to mark it failing.

**Comment by jonleighton** [comment]
FWIW the reason we didn't run into missing font issues is due to https://github.com/w3c/web-platform-tests/issues/9374

**Comment by jdm** [comment]
Nice find.

**Pull request merged**
