### PR TITLE
Properly propagate changes when range or trees are mutated

### PR DESCRIPTION
**Pull request by nox**
Does the same thing as #6817, but storing Range instances directly in their start and end containers.

Cc @dzbarsky

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8506)

### CODE REVIEW

**Comment by dzbarsky** [comment]
Cool, seems reasonable.

**Comment by eefriedman** [comment]
```
test size_of::size_characterdata ... FAILED
test size_of::size_div ... FAILED
test size_of::size_element ... FAILED
test size_of::size_htmlelement ... FAILED
test size_of::size_node ... FAILED
test size_of::size_span ... FAILED
test size_of::size_text ... FAILED
```

(Still waiting on the wpt results)

**Comment by nox** [comment]
Oh right forgot about those, thanks @eefriedman.

**Comment by jdm** [comment]
That's #7437, by the way.

**Comment by nox** [comment]
@dzbarsky r?

**Comment by dzbarsky** [comment]
I found the names really confusing. Made suggestions for some of them, but also not sure for a few. Otherwise, looks good

**Comment by dzbarsky** [comment]
Reviewed 10 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 9 of 9 files at r5, 16 of 16 files at r6.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[components/script/dom/bindings/weakref.rs, line 214 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G5RvoR2ISGCEyFExp:-K6G5RvoR2ISGCEyFExq:-2006450208) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/bindings/weakref.rs#L214)):*
this name is kind of weird. seems more like a "map"

---

*[components/script/dom/bindings/weakref.rs, line 254 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G5houAVSL7evOXnYL:-K6G5houAVSL7evOXnYM:-1509797752) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/bindings/weakref.rs#L254)):*
"underlying"

---

*[components/script/dom/node.rs, line 1610 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G6nDK36dDWHPB6wL5:-K6G6nDK36dDWHPB6wL6:1960055363) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/node.rs#L1610)):*
This sounds like premature optimization...are multiple nested ranges actually common? Fine to leave this way I guess

---

*[components/script/dom/node.rs, line 2401 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G7jmuZr8cI8y4t0Np:-K6G7jmvKRZX_X0rhI2U:-729620580) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/node.rs#L2401)):*
Don't think "drain" is the right word here. How about "reparent" or "move_anchor_to_parent" or "anchor_at_parent" or something?

---

*[components/script/dom/range.rs, line 872 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G8u1UZiuMvwjqTuc0:-K6G8u1VzJlCvPGD5LEF:49549761) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L872)):*
how about "shift_offsets_by" and use it for both a positive and negative delta?

---

*[components/script/dom/range.rs, line 884 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G9-mMDaYD08deHHiC:-K6G9-mMDaYD08deHHiD:-1742223608) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L884)):*
See previous comment

---

*[components/script/dom/range.rs, line 913 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G93_MqfnMeygpA_tJ:-K6G93_MqfnMeygpA_tK:1729725147) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L913)):*
Similar, probably want reparent or something.

---

*[components/script/dom/range.rs, line 997 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GBDojsrBJRAfmzW-V:-K6GBDojsrBJRAfmzW-W:2041178720) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L997)):*
why "_above"?

---

*[components/script/dom/range.rs, line 1043 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAXVsPOy10fkhNfbT:-K6GAXVsPOy10fkhNfbU:-1282753861) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1043)):*
increment_split_indices? increment_split_offsets? can't think of a good name here

---

*[components/script/dom/range.rs, line 1059 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAKdCIH7gcftP8P2u:-K6GAKdDzt-SZwTp92aI:1543902474) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1059)):*
set_offset?

---

*[components/script/dom/range.rs, line 1063 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GB-QTqM8K3nblREIU:-K6GB-QUbTl79ZDVq44Y:2112377758) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1063)):*
why the "_above"? I'm actually not sure what it meant in any of the cases I suggested replacements

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8506)*

**Comment by dzbarsky** [comment]
(I'm also not a peer so you'll need someone else to take a look at this too)

**Comment by nox** [comment]
Thanks for the review! Replied to your comments. Will fix the typo.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[components/script/dom/bindings/weakref.rs, line 214 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G5RvoR2ISGCEyFExp:-K6GCeOZ0s7jrqO5MArF:1052510926) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/bindings/weakref.rs#L214)):*
It's not a map if it also clears the vector out of weak references.

---

*[components/script/dom/bindings/weakref.rs, line 254 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G5houAVSL7evOXnYL:-K6GE52NTO0sBRS0zQ8M:-814111896) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/bindings/weakref.rs#L254)):*
Hah, thanks. :)

---

*[components/script/dom/node.rs, line 1610 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G6nDK36dDWHPB6wL5:-K6GCkJTvv5NIman8mgt:1798590305) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/node.rs#L1610)):*
Why wouldn't there be multiple ranges? Let the users be fancy if they want, IMO.

---

*[components/script/dom/node.rs, line 2401 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G7jmuZr8cI8y4t0Np:-K6GCvHwPsLvNtt6MAJ5:-2072944422) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/node.rs#L2401)):*
I called it drain because after the call, self's list of ranges is empty. I think "reparent" would be wrong, it's not children that you move, but ranges. Ranges don't have a parent.

---

*[components/script/dom/range.rs, line 872 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G8u1UZiuMvwjqTuc0:-K6GCzBxhB9Z5Z2qCjes:1802845741) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L872)):*
I would like to avoid that, I don't like mixing signed and unsigned values.

---

*[components/script/dom/range.rs, line 913 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G93_MqfnMeygpA_tJ:-K6GEeMuKVu-_-9StuBg:-1204180904) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L913)):*
There is nothing to reparent here.

---

*[components/script/dom/range.rs, line 997 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GBDojsrBJRAfmzW-V:-K6GDNwbuDIt8V6WsELS:1307590266) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L997)):*
Because we move only ranges' boundary points `(point_node, point_offset)`  where `point_node == self` and `point_offset > offset`.

---

*[components/script/dom/range.rs, line 1043 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAXVsPOy10fkhNfbT:-K6GDzr1YQtcXtcNLtOY:638840638) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1043)):*
What is a "split index"? A "split offset"?

---

*[components/script/dom/range.rs, line 1059 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAKdCIH7gcftP8P2u:-K6GDoOgteoLW4pNOqJI:-1868005072) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1059)):*
`set_offset_above` would be fine I guess. What's wrong with clamp?

---

*[components/script/dom/range.rs, line 1063 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GB-QTqM8K3nblREIU:-K6GDsoAAw0w07c0wZ2c:1789017486) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1063)):*
As explained above, it only moves points which are above the given one.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8506#-:-K6GETxPg4XAf9nY7Ovl:18783462)*

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[components/script/dom/node.rs, line 2401 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6G7jmuZr8cI8y4t0Np:-K6GHNBduA24VE0vugJr:594289362) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/node.rs#L2401)):*
Ah, that's fair. I guess drain is a rust thing.

---

*[components/script/dom/range.rs, line 1043 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAXVsPOy10fkhNfbT:-K6GGvHKIOPD-kqFKwtz:1367010793) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1043)):*
yeah, a split offset. if we could capture why we need to increment in the name that would be nice

---

*[components/script/dom/range.rs, line 1059 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAKdCIH7gcftP8P2u:-K6GGbiz97u50VMkrspY:-1009199006) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1059)):*
I guess clamp is fine, that above part confused me.

---

*[components/script/dom/range.rs, line 1063 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GB-QTqM8K3nblREIU:-K6GG4k6rbVdI0hFVchv:676962275) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1063)):*
I think my discomfort with all these names stems from the fact that the direction isn't really "above", it's "later in tree order". I understand that "above" comes from "index is more than __", so maybe the name can incorporate "exceeding_offset" or "max_offset" or "after_offset" or even just "after"? Perhaps someone else will have a great suggestion, I don't want to block this if neither of us can think of good names.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8506)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/range.rs, line 1043 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAXVsPOy10fkhNfbT:-K6GHiFOY3vpvRFeuabU:887489550) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1043)):*
What does it mean to split an offset?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8506)*

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/range.rs, line 1043 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAXVsPOy10fkhNfbT:-K6GJO3lcn9GcxVo58pE:1025729769) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1043)):*
You're moving the offset because you split the text node at that offset, right? maybe this should be "increment_offset_for_split_text"?

I was actually just thinking, if we inline this function we don't even need to name it and all the steps are together.  Can we just call update from Text#split and pass in the closure from there?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8506)*

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/range.rs, line 1043 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAXVsPOy10fkhNfbT:-K6GKRYBJT4GQhi9w7hj:-1256962009) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1043)):*
Or even a closure that takes in a range and have a wrapper around update that can deal?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8506)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/range.rs, line 1043 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAXVsPOy10fkhNfbT:-K6Gk3dRq1BmK_zJUaHc:-674131709) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1043)):*
Ranges are complex, my intent was to leak as little as possible about their implementations in other modules, that's why I made all these methods on this type.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8506)*

**Comment by dzbarsky** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/range.rs, line 1043 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAXVsPOy10fkhNfbT:-K6GoLko7CXC4soP4N8s:1289616670) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1043)):*
I'd buy that for move_to_text_child_at and any functions that change the start/end node (Because then we have to change the range arrays, etc._ but this function and functions that only affect the offsets are very straightforward manipulations and follow the spec directly, so they're not really leaking anything.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8506)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/script/dom/range.rs, line 1043 \[r5\]](https://reviewable.io:443/reviews/servo/servo/8506#-K6GAXVsPOy10fkhNfbT:-K6IA_8f4-h17x3BmNqr:789523156) ([raw file](https://github.com/servo/servo/blob/3f157a43c1627010be27c47f178d4bba3e4be472/components/script/dom/range.rs#L1043)):*
Well, if the closure takes a range, that means callers can do whatever they want, like putting them in a different vector, so you would have to trust callers more than with these methods.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8506)*

**Comment by dzbarsky** [comment]
I mean callers can already do whatever they want with the ranges...but whatever. It was just a suggestion. You can land it like this if you really its better.

@bors-servo r+

**Comment by dzbarsky** [comment]
@bors-servo r- force 

will wait for you to say it's ready, looks like you haven't pushed yet.

**Comment by nox** [comment]
I fixed the typo in "underlying".

@bors-servo r=dzbarsky

**Pull request merged**
