### PR TITLE
Compose animation with servo's hashmap

### PR DESCRIPTION
**Pull request by hiikezoe**
This is a PR for https://bugzilla.mozilla.org/show_bug.cgi?id=1340958

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors

- [X] These changes do not require tests because it's for stylo.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/16005)

### CODE REVIEW

**Comment by hiikezoe** [comment]
All patches in this PR have been reviewed by @heycam and @BorisChiou.

**Comment by heycam** [comment]
@bors-servo retry

* #15705

**Pull request merged**
