### PR TITLE
Get rid of a bunch of explicit derefs

### PR DESCRIPTION
**Pull request by dzbarsky**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8305)

### CODE REVIEW

**Comment by Ms2ger** [comment]
-S-awaiting-review +S-needs-code-changes 
R? @Ms2ger


---

Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[components/script/dom/uievent.rs, line 51 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8305#-K2BYpyJVgCv1fdTyID1)** ([raw file](https://github.com/servo/servo/blob/fadf503f2646870dc1fe24cca4f88ee91a85bbe9/components/script/dom/uievent.rs#L51)):</sup>
Indent.


---

<sup>**[components/script/script_task.rs, line 871 \[r1\]](https://reviewable.io:443/reviews/servo/servo/8305#-K2BYYLOvcbucxlODbV7)** ([raw file](https://github.com/servo/servo/blob/fadf503f2646870dc1fe24cca4f88ee91a85bbe9/components/script/script_task.rs#L871)):</sup>
Indent


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/8305)

**Comment by dzbarsky** [comment]
Thanks, I looked through the diff before submitting, but I'm always impressed by your ability to catch those

**Comment by jdm** [comment]
@bors-servo: retry
* #7787

**Pull request merged**
