### PR TITLE
Add slow path for hit testing of iframe behind positioned content layer

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes browser.html blocker #8759. r? @pcwalton

This adds a slow path for cases where the compositor's layer-based hit testing is incorrect.  If the script task discovers that a mouse event should have been dispatched to an iframe, it bounces the event back to the constellation to be forwarded to the correct pipeline.

This isn't terribly slow (on the slow path, it adds one extra round-trip message between script and constellation), but if we want to optimize this better we could instead replace the compositor's layer hit testing with display list hit testing in the paint task.  This would be a more complicated change that I think we should save for a follow-up.

This only fixes mouse input for now.  A basically-identical change will be needed for touch-screen input, whether we stick with this approach or switch to the paint task.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8785)

### CODE REVIEW

**Comment by pcwalton** [comment]
Just had one nit, otherwise looks good.

**Comment by mbrubeck** [comment]
@bors-servo r=pcwalton

Fixed review nit and tidy failures; rebased.

**Comment by KiChjang** [comment]
```
   Compiling layout v0.0.1 (file:///home/servo/buildbot/slave/gonk/build/ports/gonk)
/home/servo/buildbot/slave/gonk/build/components/layout/display_list_builder.rs:1798:22: 1798:57 warning: unnecessary parentheses around `for` head expression, #[warn(unused_parens)] on by default
/home/servo/buildbot/slave/gonk/build/components/layout/display_list_builder.rs:1798         for index in (0..self.fragments.fragments.len()) {
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/input.rs:9:5: 9:31 error: unresolved import `script_traits::MouseButton`. There is no `MouseButton` in `script_traits` [E0432]
src/input.rs:9 use script_traits::MouseButton;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/input.rs:9:5: 9:31 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to previous error
Could not compile `b2s`.
```

**Comment by mbrubeck** [comment]
@bors-servo r=pcwalton

Fixed import path in ports/gonk

**Pull request merged**
