### PR TITLE
[Draft] Lay out floats and handle clearance in layout 2020, but don't flow text around them yet.

### PR DESCRIPTION
**Pull request by pcwalton**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by pcwalton** [comment]
(sorry about forgetting to rustfmt)

**Comment by pcwalton** [comment]
I…did not expect that to pass!

**Comment by mrobinson** [comment]
These changes were landed as part of #29757.

**Pull request closed without merging**
