### PR TITLE
Update rust-url

### PR DESCRIPTION
**Pull request by KiChjang**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9498)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@bors-servo retry
- #9504

**Comment by jdm** [comment]
```
  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://GOO\u200b\u2060\ufeffgoo.com> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://www.foo\u3002bar.com> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://\uff27\uff4f.com> against <http://other.com/>

  ▶ Unexpected subtest result in /url/url-constructor.html:
  └ PASS [expected FAIL] Parsing: <http://\uff10\uff38\uff43\uff10\uff0e\uff10\uff12\uff15\uff10\uff0e\uff10\uff11> against <http://other.com/>
```

**Comment by nox** [comment]
Nice.

**Comment by nox** [comment]
@KiChjang Need expectation changes.

**Comment by KiChjang** [comment]
@bors-servo retry
* #9012

**Comment by KiChjang** [comment]
@bors-servo retry
* #9163

**Pull request merged**
