### PR TITLE
Fix ridiculous DOM proxy getter performance

### LINKED ISSUE #12357: document.firstChild is way slower in Servo than Gecko
```html
<script>
var n = document;
var start = new Date();
var count = 1000000;
for (var i = 0; i < count; i++) {
  var a = n.firstChild;
}
var stop = new Date();
console.log('firstChild getter: ' + ((stop - start) / count * 1e6) + 'ns');                   
</script>
```
Results:
```
Gecko:
firstChild getter: 25ns

Servo:
firstChild getter: 515ns
```

### PR DESCRIPTION
**Pull request by jdm**
This implements the missing shadowing checks that were causing us to take many slow paths when dealing with proxy objects. Verified by running `tests/html/binding_perf.html` before and after and observing a 12x improvement.

---
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #12357
- [X] These changes do not require tests because we can't test performance yet.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12980)

### CODE REVIEW

**Comment by jdm** [comment]
Oh, this PR requires https://github.com/servo/rust-mozjs/pull/289.

**Comment by nox** [comment]
r=me with comments addressed and SM updated.

-S-awaiting-review +S-needs-code-changes 

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/proxyhandler.rs, line 31 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12980#-KPqKCedTNU4XJyzu2Tr:-KPqKCeerz5Xj8M3eoWM:b-j2wws3) ([raw file](https://github.com/servo/servo/blob/7ebf42e1bf08b8511288d93402635181ddd4b571/components/script/dom/bindings/proxyhandler.rs#L31)):*
> ```Rust
> pub unsafe extern "C" fn shadow_check_callback(cx: *mut JSContext,
>                                                object: HandleObject,
>                                                id: HandleId) -> DOMProxyShadowsResult {
> ```

Nit: we usually put `-> ReturnType` on a new line.

---

*[components/script/dom/bindings/proxyhandler.rs, line 51 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12980#-KPqKFGRzA3mWkyNc8uL:-KPqKFGRzA3mWkyNc8uM:b134u89) ([raw file](https://github.com/servo/servo/blob/7ebf42e1bf08b8511288d93402635181ddd4b571/components/script/dom/bindings/proxyhandler.rs#L51)):*
> ```Rust
> 
> /// Initialize the infrastructure for DOM proxy objects.
> pub fn init() {
> ```

This should be unsafe, no? What happens if that's called at the wrong moment, say, before SM was initialised at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12980#-:-KPqKH4wqMljiV7JagPi:b-a27fgj)*

**Comment by nox** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12980)*

**Comment by jdm** [comment]
Bah, updating rust-mozjs is blocked on #12954.

**Comment by jdm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/proxyhandler.rs, line 51 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12980#-KPqKFGRzA3mWkyNc8uL:-KPrjljK6XYumXqRdHVj:b-arrw4s) ([raw file](https://github.com/servo/servo/blob/7ebf42e1bf08b8511288d93402635181ddd4b571/components/script/dom/bindings/proxyhandler.rs#L51)):*
<details><summary><i>Previously, nox (Anthony Ramine) wrote…</i></summary>
> This should be unsafe, no? What happens if that's called at the wrong moment, say, before SM was initialised at all?
</details>
SetDOMProxyInformation sets three global variables: https://dxr.mozilla.org/mozilla-central/rev/24763f58772d45279a935790f732d80851924b46/js/src/jsfriendapi.cpp#1251

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12980)*

**Comment by nox** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/script/dom/bindings/proxyhandler.rs, line 51 \[r2\]](https://reviewable.io:443/reviews/servo/servo/12980#-KPqKFGRzA3mWkyNc8uL:-KPvwicfoAjvxk0pj8hj:bekzizk) ([raw file](https://github.com/servo/servo/blob/7ebf42e1bf08b8511288d93402635181ddd4b571/components/script/dom/bindings/proxyhandler.rs#L51)):*
<details><summary><i>Previously, jdm (Josh Matthews) wrote…</i></summary>
> SetDOMProxyInformation sets three global variables: https://dxr.mozilla.org/mozilla-central/rev/24763f58772d45279a935790f732d80851924b46/js/src/jsfriendapi.cpp#1251
</details>
Can't everything go wrong if you call that in the middle of nowhere when JS is running, then? If yes, please make it unsafe.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12980)*

**Comment by nox** [comment]
@jdm The other PR merged, you can now update rust-mozjs in this one.

**Comment by nox** [comment]
@bors-servo r+

---

Reviewed 6 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/12980#-:-KQ0T3CQradtLziAsWo9:bkg9nno)*

**Pull request merged**
