### PR TITLE
Update webrender

### LINKED ISSUE #11327: WebRender crashes 'thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325'
Crash almost always can be reproduced with:
1.  ./mach run -d -w https://www.stgraber.org/2016/03/11/lxd-2-0-blog-post-series-012/
2. Maximize window
3. Scroll to the bottom & to the top multiple times
4. Open `LXD 2.0: Introduction to LXD [1/12]` link
5. If there is no crash yet, go back and repeat from step 2
Backtrace is rather large, you can find it [here](https://gist.github.com/ojab/0064129b71662fd928b39f1ec9191b89). First backtrace:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:        0x1081df9e8 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:        0x1081e5f35 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:        0x1081e5b4e - std::panicking::default_hook::hc2c969e7453d080c
   4:        0x1075fc949 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h07189f4b5f921f62
   5:        0x1075fc7e3 - _<std..thread..LocalKey<T>>::with::hc9520a1ebaa4392a
   6:        0x1075fc63a - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::he1c0430821142638
   7:        0x1081cd5b2 - std::panicking::rust_panic_with_hook::hfe203e3083c2b544
   8:        0x1081e64f6 - std::panicking::begin_panic::h4889569716505182
   9:        0x1081ceea8 - std::panicking::begin_panic_fmt::h484cd47786497f03
  10:        0x1081e614f - rust_begin_unwind
  11:        0x10820d940 - core::panicking::panic_fmt::h257ceb0aa351d801
  12:        0x10820dc3c - core::panicking::panic::h4bb1497076d04ab9
  13:        0x106ae4436 - _<std..option..Option<T>>::unwrap::h083bbee6cfa65d14
  14:        0x106add1aa - webrender::frame::RenderTarget::collect_and_sort_visible_batches::h8cc896fe94f09f0a
  15:        0x106b20ddb - webrender::frame::Frame::collect_and_sort_visible_batches::he7fb6acb67dc42fe
  16:        0x106b1fd1b - webrender::frame::Frame::build::h807c40a76c69b1d9
  17:        0x106bdbd69 - webrender::render_backend::RenderBackend::render::h40070fff4375c1da
  18:        0x106bda66f - webrender::render_backend::RenderBackend::run::_$u7b$$u7b$closure$u7d$$u7d$::hf5d545a45e0cfb0b
  19:        0x106bda2f5 - webrender::profiler::TimeProfileCounter::profile::h8ac1a98e225e8737
  20:        0x106b5b797 - webrender::render_backend::RenderBackend::run::h9987749de8e4e926
  21:        0x106c8e22d - webrender::renderer::Renderer::new::_$u7b$$u7b$closure$u7d$$u7d$::h96fbc31f4259f2b6
  22:        0x106c8df57 - _<std..panic..AssertUnwindSafe<F> as std..ops..FnOnce<()>>::call_once::h48de513d93782848
  23:        0x106c8deae - std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h267db1b61aa4ff4b
  24:        0x106c8e8c4 - std::panicking::try::call::h0e156d498a229c0e
  25:        0x1081e96bb - __rust_try
  26:        0x1081e9655 - __rust_maybe_catch_panic
  27:        0x106c8db9d - std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::h9829450ef183fc5f
  28:        0x106c8da6f - _<std..thread..LocalKey<T>>::with::h2db1204ea9affc27
  29:        0x106c8d89f - std::panicking::try::he24c0ce01f62d6c2
  30:        0x106c8d77e - std::panic::catch_unwind::hf90c422d5e9eacd3
  31:        0x106c8d5ee - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hc50221be19342b19
  32:        0x106c8eb07 - _<F as std..boxed..FnBox<A>>::call_box::h37243a76710238a4
  33:        0x1081e4e98 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  34:     0x7fff9a32899c - _pthread_body
  35:     0x7fff9a328919 - _pthread_start
thread 'thread 'LayoutWorker worker 1/6thread '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorLayoutWorker worker 6/6LayoutWorker worker 4/6thread '' panicked at 'LayoutWorker worker 3/6thread 'LayoutWorker worker 2/6' panicked at '' panicked at 'cal
led `Result::unwrap()` on an `Err` value: RecvError', thread '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', called `Result::unwrap()` on an `Err` value: RecvErrorLayoutWorker worker 5/6../src/libcore/result.rs' panicked at '', called `Result::unw
rap()` on an `Err` value: RecvError', ../src/libcore/result.rs:785:../src/libcore/result.rs', 785:
../src/libcore/result.rs:stack backtrace:
785../src/libcore/result.rs

called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore/result.rs:785
:785
785
```
No crash if run without enabling WebRender.

### PR DESCRIPTION
**Pull request by Manishearth**
Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data:
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy --faster` does not report any errors
- [x] These changes fix #11327

Either:
- [ ] There are tests for these changes OR
- [x] These changes do not require tests because it's a dependency update

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11353)

### CODE REVIEW

**Comment by ConnorGBrewster** [comment]
@bors-servo retry
 * infra

**Comment by Manishearth** [comment]
servo-mac1 is borked

**Pull request merged**
