### PR TITLE
Build docs and upload to doc.servo.org on Taskcluster, add support for trychoosers

### PR DESCRIPTION
**Pull request by SimonSapin**
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22381)

### CODE REVIEW

**Comment by jdm** [comment]
@SimonSapin So http://doc.servo.org/ no longer contains any content. Is that expected?

**Comment by SimonSapin** [comment]
That is not exactly expected of course, but it is explained by the "live" test that I did of pushing with the secret token, before adding the `CNAME` file and others from `etc/doc.servo.org`. I expect it’ll be fixed when this PR lands (or next time the daily job runs on Buildbot), but I’ll fix it manually in the meantime.

**Comment by SimonSapin** [comment]
Fixed. (By manually pushing the bundle from https://tools.taskcluster.net/groups/CLusKdi3Ss-Pwm0sFPQDlw/tasks/OKd0IWpkR9KepHzj_ltd1g/runs/0/artifacts.)

**Pull request merged**
