### PR TITLE
Implement viewport functions for window #1718

### PR DESCRIPTION
**Pull request by farodin91**
@jdm r?
closes #6875

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/7500)

### CODE REVIEW

**Comment by jdm** [comment]
For future reference, it's perfectly acceptable to squash and then force push the result to the original branch so we don't need a separate PR :)

**Comment by jdm** [comment]
@bors-servo: r+
Thanks for sticking through the review process :)

**Comment by farodin91** [comment]
How can i reset the original branch to upstream/master?

**Comment by jdm** [comment]
`git reset --hard remotes/upstream/master` will reset the current branch.

**Comment by farodin91** [comment]
Thanks

**Comment by jdm** [comment]
```
src/window.rs:10:5: 10:23 error: unused import
src/window.rs:10 use euclid::rect::Rect;
                     ^~~~~~~~~~~~~~~~~~
src/main.rs:5:9: 5:23 note: lint level defined here
src/main.rs:5 #![deny(unused_imports)]
                      ^~~~~~~~~~~~~~
src/window.rs:307:30: 307:43 warning: found non-foreign-function-safe member in struct marked #[repr(C)]: found Rust type `isize` in foreign module, while `libc::c_int` or `libc::c_long` should be used, #[warn(improper_ctypes)] on by default
src/window.rs:307     fn gnw_perform(win: *mut ANativeWindow, op: c_int, ...) -> c_int;
                                               ^~~~~~~~~~~~~
src/window.rs:802:30: 802:34 error: unused variable: `size`
src/window.rs:802     fn set_inner_size(&self, size: Size2D<u32>) {
                                               ^~~~
src/main.rs:6:9: 6:25 note: lint level defined here
src/main.rs:6 #![deny(unused_variables)]
                      ^~~~~~~~~~~~~~~~
src/window.rs:806:28: 806:33 error: unused variable: `point`
src/window.rs:806     fn set_position(&self, point: Point2D<i32>) {
                                             ^~~~~
src/main.rs:6:9: 6:25 note: lint level defined here
src/main.rs:6 #![deny(unused_variables)]
                      ^~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Could not compile `b2s`.
```

**Pull request merged**
