### PR TITLE
Make `mach test-tidy --no-wpt` compatible with Python3

### PR DESCRIPTION
**Pull request by marmeladema**
Make `mach test-tidy --no-wpt` compatible with Python3
See also #23607

After this pull request, all python files (except WPT) will be checked for Python3 syntax compatibility.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by Manishearth** [comment]
try + r+ sometimes confuses homu, sadly

**Comment by marmeladema** [comment]
@Manishearth did it work? How can I check if the build is scheduled?

**Comment by Manishearth** [comment]
Yours already passed.

https://treeherder.allizom.org/#/jobs?repo=servo-try&revision=0eb4bf24b868c2e638d472a5f3c8587a6a2fca25

I did an r- because homu was backed up on _other_ PRs

**Comment by Manishearth** [comment]
we can re-r+ this now if you think it's ready

@bors-servo try-

**Comment by marmeladema** [comment]
Yes i think its ready.

**Pull request merged**
