### PR TITLE
update.sh downloads all *.py tests from mozilla central

### PR DESCRIPTION
**Pull request by AgostonSzepessy**
components/script/dom/bindings/codegen/parser/update.sh downloads all *.py tests from https://dxr.mozilla.org/mozilla-central/source/dom/bindings/parser/tests

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9890)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Do we run those tests already?

**Comment by nox** [comment]
@Ms2ger Should we version them in the repository? Also I have no idea if we currently run them.

@AgostonSzepessy What happens if the transfer fails at some point? Shouldn't we download them in a temporary directory and then move that into the working tree?

**Comment by AgostonSzepessy** [comment]
@nox What about this instead?

```
wget -r -np -l1 -A py -nd https://dxr.mozilla.org/mozilla-central/source/dom/bindings/parser/tests -P /tmp/tests

if [ $? -eq 0 ]
then
	mv tests tests-old
	mv /tmp/tests ./

	if [ $? -eq 0 ]
	then
		rm -r tests-old
	else
		echo 'Failed moving /tmp/tests to ./tests'
		mv tests-old tests
	fi
else
	echo 'Failed downloading tests'
fi
```

**Comment by Ms2ger** [comment]
The one-liner made me a bit queasy, with all the unreadable arguments, but I'll vehemently object to any shell script with conditionals :)

**Comment by AgostonSzepessy** [comment]
@nox  @Ms2ger What about this? This script doesn't have any conditionals:

```
wget -r -np -l1 -A py -nd https://dxr.mozilla.org/mozilla-central/source/dom/bindings/parser/tests -P /tmp/tests

# delete backups of old tests
rm -r tests-old
# backup old tests and replace them with new ones
mv tests tests-old
mv /tmp/tests ./tests
```

**Comment by nox** [comment]
@Ms2ger doesn't like my requestion at all, so I'm just going to accept this as-is.

@bors-servo r+

**Comment by nox** [comment]
@bors-servo r-

Oops, didn't notice but we need to sync run-tests.py too.

**Comment by Ms2ger** [comment]
And we should probably also run the script; are there really no test updates?

**Comment by AgostonSzepessy** [comment]
@nox @Ms2ger Do I need ot update runtests.py so that it calls the update script?

**Comment by Ms2ger** [comment]
No, but the test files should be commited into this repo.

**Comment by nox** [comment]
File `components/script/dom/bindings/codegen/parser/WebIDL.py.orig` should not be versioned.

**Comment by KiChjang** [comment]
I'm going to chip in and ask to squash the "Deleted WebIDL.py.orig" commit.

**Comment by nox** [comment]
Please squash the commits together and rebase on master.

**Comment by KiChjang** [comment]
Here's a link to help you get started with squashing https://github.com/servo/servo/wiki/Github-workflow.

**Comment by nox** [comment]
This is wrong, you versioned HTML files in place of the proper tests.

**Comment by AgostonSzepessy** [comment]
Sorry, I'm confused. The script downloaded those. What should I do with those files then?

**Comment by jdm** [comment]
The script fetched URLs like https://dxr.mozilla.org/mozilla-central/source/dom/bindings/parser/tests/test_any_null.py which contain the full HTML source for looking at the file contents in the DXR browser. We should instead be fetching the raw file contents (eg. https://hg.mozilla.org/mozilla-central/raw-file/master/dom/bindings/parser/tests/test_any_null.py).

**Comment by Ms2ger** [comment]
@indygreg: please see `update.sh`; is that the best way to pull down a directory from m-c?

**Comment by nox** [comment]
The rest is ok.

**Comment by indygreg** [comment]
Yes, that's the correct way to download the archive of a subdirectory from hg.mozilla.org. Please don't point any high traffic clients at that API, however: requests can be computationally expensive.

**Comment by Ms2ger** [comment]
Thanks!

@bors-servo r=nox

**Pull request merged**
