### PR TITLE
Random fixups

### PR DESCRIPTION
**Pull request by zmike**
Attempt to not panic as much if the resources/ dir is not where it's expected to be.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5992)

### CODE REVIEW

**Comment by Ms2ger** [comment]
I'm not sure about this. The UA style sheets are an essential part of the browser; you can't just run without them.

**Comment by zmike** [comment]
Then I guess it should at least print an error instead of just panicking with no info?

**Comment by pcwalton** [comment]
I agree with both of you; print an error, say what's wrong, and exit gracefully instead of proceeding silently.

**Comment by zmike** [comment]
Seems reasonable. Done.

**Comment by larsbergstrom** [comment]
Reviewed files:
- components/style/selector_matching.rs @ r5
- components/util/resource_files.rs @ r3
- ports/cef/core.rs @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/servo/5992)

**Pull request merged**
