### PR TITLE
Turn on unused-extern-crates warning.

### PR DESCRIPTION
**Pull request by zbynekwinkler**
As discussed in #9256. It should solve second half of the issue.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/10706)

### CODE REVIEW

**Comment by nox** [comment]
We might want to wait?

https://github.com/rust-lang/rust/issues/30849

**Comment by metajack** [comment]
@bors-servo try

Code looks fine, but let's run it through CI to see how many false positives we get.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10706#-:-KFjCFz52J6ToJ_6nP5j:-922284460)*

**Comment by jdm** [comment]
```
   Compiling util v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/util)
/home/servo/buildbot/slave/linux-rel/build/components/util/lib.rs:22:1: 22:23 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/util/lib.rs:22 extern crate bitflags;
                                                                     ^~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/util/lib.rs:31:1: 31:26 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/util/lib.rs:31 extern crate lazy_static;
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
   Compiling style_traits v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/style_traits)
   Compiling profile v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/profile)
/home/servo/buildbot/slave/linux-rel/build/components/profile/lib.rs:14:1: 14:29 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/profile/lib.rs:14 extern crate alloc_jemalloc;
                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Compiling webrender v0.1.0 (https://github.com/servo/webrender#46dd3f0f)
   Compiling msg v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/msg)
/home/servo/buildbot/slave/linux-rel/build/components/msg/lib.rs:11:1: 11:23 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/msg/lib.rs:11 extern crate bitflags;
                                                                    ^~~~~~~~~~~~~~~~~~~~~~
   Compiling gfx_traits v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/gfx_traits)
   Compiling devtools_traits v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/devtools_traits)
/home/servo/buildbot/slave/linux-rel/build/components/gfx_traits/lib.rs:19:1: 19:19 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/gfx_traits/lib.rs:19 extern crate util;
                                                                           ^~~~~~~~~~~~~~~~~~
   Compiling canvas_traits v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/canvas_traits)
/home/servo/buildbot/slave/linux-rel/build/components/canvas_traits/lib.rs:20:1: 20:35 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/canvas_traits/lib.rs:20 extern crate offscreen_gl_context;
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/canvas_traits/lib.rs:22:1: 22:19 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/canvas_traits/lib.rs:22 extern crate util;
                                                                              ^~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/devtools_traits/lib.rs:19:1: 19:23 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/devtools_traits/lib.rs:19 extern crate bitflags;
                                                                                ^~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/devtools_traits/lib.rs:27:1: 27:19 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/devtools_traits/lib.rs:27 extern crate util;
                                                                                ^~~~~~~~~~~~~~~~~~
   Compiling devtools v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/devtools)
   Compiling canvas v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/canvas)
/home/servo/buildbot/slave/linux-rel/build/components/canvas/lib.rs:17:1: 17:21 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/canvas/lib.rs:17 extern crate layers;
                                                                       ^~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/devtools/lib.rs:27:1: 27:18 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/devtools/lib.rs:27 extern crate log;
                                                                         ^~~~~~~~~~~~~~~~~
   Compiling net_traits v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/net_traits)
/home/servo/buildbot/slave/linux-rel/build/components/net_traits/lib.rs:21:1: 21:26 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/net_traits/lib.rs:21 extern crate lazy_static;
                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/style/lib.rs:23:1: 23:23 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/style/lib.rs:23 extern crate bitflags;
                                                                      ^~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/style/lib.rs:32:1: 32:26 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/style/lib.rs:32 extern crate lazy_static;
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/style/lib.rs:36:1: 36:22 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/style/lib.rs:36 extern crate matches;
                                                                      ^~~~~~~~~~~~~~~~~~~~~
   Compiling net v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/net)
   Compiling script_traits v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/script_traits)
   Compiling gfx v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/gfx)
/home/servo/buildbot/slave/linux-rel/build/components/gfx/lib.rs:27:1: 27:23 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/gfx/lib.rs:27 extern crate bitflags;
                                                                    ^~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/gfx/lib.rs:53:1: 53:26 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/gfx/lib.rs:53 extern crate lazy_static;
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
   Compiling layout_traits v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/layout_traits)
/home/servo/buildbot/slave/linux-rel/build/components/script/lib.rs:34:1: 34:23 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/script/lib.rs:34 extern crate bitflags;
                                                                       ^~~~~~~~~~~~~~~~~~~~~~
   Compiling compositing v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/compositing)
/home/servo/buildbot/slave/linux-rel/build/components/script/dom/htmliframeelement.rs:16:48: 16:56 warning: unused import, #[warn(unused_imports)] on by default
/home/servo/buildbot/slave/linux-rel/build/components/script/dom/htmliframeelement.rs:16 use dom::bindings::error::{Error, ErrorResult, Fallible};
                                                                                                                                        ^~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/script/dom/htmllinkelement.rs:11:5: 11:67 warning: unused import, #[warn(unused_imports)] on by default
/home/servo/buildbot/slave/linux-rel/build/components/script/dom/htmllinkelement.rs:11 use dom::bindings::codegen::Bindings::WindowBinding::WindowMethods;
                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Compiling webdriver_server v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/webdriver_server)
   Compiling glutin_app v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/ports/glutin)
/home/servo/buildbot/slave/linux-rel/build/components/webdriver_server/lib.rs:18:1: 18:18 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/webdriver_server/lib.rs:18 extern crate log;
                                                                                 ^~~~~~~~~~~~~~~~~
   Compiling layout v0.0.1 (file:///home/servo/buildbot/slave/linux-rel/build/components/layout)
/home/servo/buildbot/slave/linux-rel/build/components/layout/lib.rs:25:1: 25:23 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/layout/lib.rs:25 extern crate bitflags;
                                                                       ^~~~~~~~~~~~~~~~~~~~~~
/home/servo/buildbot/slave/linux-rel/build/components/layout/lib.rs:52:1: 52:20 warning: unused extern crate [-W unused-extern-crates]
/home/servo/buildbot/slave/linux-rel/build/components/layout/lib.rs:52 extern crate serde;
                                                                       ^~~~~~~~~~~~~~~~~~~
main.rs:24:1: 24:20 warning: unused extern crate [-W unused-extern-crates]
main.rs:24 extern crate gleam;
           ^~~~~~~~~~~~~~~~~~~
main.rs:30:1: 30:18 warning: unused extern crate [-W unused-extern-crates]
main.rs:30 extern crate log;
           ^~~~~~~~~~~~~~~~~
main.rs:31:1: 31:35 warning: unused extern crate [-W unused-extern-crates]
main.rs:31 extern crate offscreen_gl_context;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by zwn** [comment]
I have added guards to the false positives. What is left should be the actual thing.

**Comment by zwn** [comment]
The last commit takes care of the unused crates. I think am all done here (unless you have some suggestions).

**Comment by Ms2ger** [comment]
`alloc_jemalloc` is a false positive too.

**Comment by zwn** [comment]
I'll fold it into the false positives commit then.

**Comment by zwn** [comment]
@Ms2ger Done.

**Comment by nox** [comment]
Please squash the commits together, a bisection ending up in the middle of your PR would have failing tests.

-S-awaiting-review +S-needs-squash 

---

Reviewed 1 of 1 files at r1, 5 of 8 files at r2, 1 of 1 files at r3, 18 of 19 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/10706#-:-KFsGhzY3C_ChF06_Dy6:-1914208929)*

**Comment by Ms2ger** [comment]
Rather than squashing, I'd suggest reordering the commits so that the "Turn on unused-extern-crates warning." comes after the two other commits.

**Comment by zwn** [comment]
Reorder done.

**Comment by jdm** [comment]
Looks like you'll need to run `./mach cargo-update -p [crate]` where [crate] is each of the crates that had a TOML file modified, in order to keep our multiple Cargo.lock files in sync.

**Comment by zwn** [comment]
Can I somehow verify locally that I have done the right thing?

**Comment by zwn** [comment]
I have folded the update of the lock files into the commit modifying the toml files (hope that is ok).

**Comment by zwn** [comment]
Can anyone help with the android stuff? I don't have the environment set up and I know close to nothing about android. I guess some of the extern crates should have been guarded by cfg(android).

**Comment by jdm** [comment]
Yes, that would be the correct way to sort it out. Specifically, the use of the `log` crate in main.rs with `target_os = "android"`.

**Comment by zwn** [comment]
Reworked to consider also android build.

**Pull request merged**
