### PR TITLE
Update to cargo-0.18.0-nightly (fa1b12a 2017-02-07)

### PR DESCRIPTION
**Pull request by SimonSapin**
Initial PR title and message: <s>Update to rustc 1.17.0-nightly (11bc48a15 2017-03-06) and cargo 0.17.0-nightly (385e243 2017-01-27).</s>

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/15852)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Let’s try to isolate the failure in https://github.com/servo/servo/pull/15565#issuecomment-284471246

@bors-servo try

**Comment by SimonSapin** [comment]
Yup, same:

```
bash -l ./mach test-unit
[…]
   Compiling layout_tests v0.0.1 (file:///C:/buildbot/slave/windows-gnu-dev/build/tests/unit/layout)
    Finished dev [unoptimized + debuginfo] target(s) in 51.84 secs
     Running C:\buildbot\slave\windows-gnu-dev\build\target\debug\deps\gfx_tests-07dc130213a68c25.exe
error: test failed
program finished with exit code 127
```

**Comment by SimonSapin** [comment]
Let’s see with only rust updated, not cargo.

@bors-servo try

**Comment by nox** [comment]
I killed jobs, here is [`windows-gnu-dev`](http://build.servo.org/builders/windows-gnu-dev/builds/1181).

**Comment by nox** [comment]
It didn't break, so the culprit is `cargo`, not `rustc`/

**Comment by nox** [comment]
https://github.com/rust-lang/cargo/compare/385e243...5db6d64

**Comment by nox** [comment]
Killed all jobs but [`windows-gnu-dev`](http://build.servo.org/builders/windows-gnu-dev/builds/1193).

**Comment by nox** [comment]
https://github.com/rust-lang/cargo/commit/de2aa263afa759b0ef49fdff56354ca2ebff81b9 worked.

**Comment by nox** [comment]
[`windows-gnu-dev`](http://build.servo.org/builders/windows-gnu-dev/builds/1195)

**Comment by nox** [comment]
https://github.com/rust-lang/cargo/commit/3c32fc5577c6622b60b161b313a9c832b69e512f failed too.

**Comment by nox** [comment]
I'm dumb and forgot that `git log` gives results in reverse chronological order, so I was retrying with commits that will be sure to fail...

**Comment by nox** [comment]
Trying on range https://github.com/rust-lang/cargo/compare/385e243...ad92930

@bors-servo try

**Comment by nox** [comment]
Git issues now, why not.

**Comment by nox** [comment]
[`windows-gnu-dev`](http://build.servo.org/builders/windows-gnu-dev/builds/1199)

**Comment by nox** [comment]
It worked, trying range https://github.com/rust-lang/cargo/compare/ad92930...35e4b2.

@bors-servo try

**Comment by nox** [comment]
The Windows build fail, and that Linux failure doesn't look good at all. No idea what is going on.

**Comment by nox** [comment]
Trying on range https://github.com/rust-lang/cargo/compare/de2919f...35e4b2c.

@bors-servo try

**Comment by nox** [comment]
[`windows-gnu-dev`](http://build.servo.org/builders/windows-gnu-dev/builds/1201)

**Comment by nox** [comment]
Worked with https://github.com/rust-lang/cargo/commit/de2919fd32f1d4f599bb59ac78ea4f01f3a33e46!

**Comment by nox** [comment]
[`windows-gnu-dev`](http://build.servo.org/builders/windows-gnu-dev/builds/1203)

**Comment by nox** [comment]
Failed with https://github.com/rust-lang/cargo/commit/fa1b12aa7ae188c430108383e570119328b5a023!

Culprit is in https://github.com/rust-lang/cargo/compare/de2919f...fa1b12a.

**Comment by nox** [comment]
Git issues again.

@bors-servo clean retry

**Comment by nox** [comment]
Git...

@bors-servo clean try

**Comment by nox** [comment]
@bors-servo retry

I'm bad at this.

**Comment by nox** [comment]
`windows1` is broken.

```
fatal: Unable to create 'c:/buildbot/slave/windows-gnu-dev/build/.git/index.lock': File exists.
```

**Comment by nox** [comment]
I shut it down.

@bors-servo retry

**Comment by nox** [comment]
@aneeshusa I'm so bad I stopped the wrong build machine. Could you bring back online `windows1` and see what's wrong with `windows2`?

**Comment by nox** [comment]
[`windows-gnu-dev`](http://build.servo.org/builders/windows-gnu-dev/builds/1214)

**Comment by nox** [comment]
Worked with https://github.com/rust-lang/cargo/commit/ef00a5352d4c2eb6fa42c28b9e966299eb84feb2.

**Comment by nox** [comment]
Culprit is either https://github.com/rust-lang/cargo/pull/3664 or https://github.com/rust-lang/cargo/pull/3651, in range https://github.com/rust-lang/cargo/compare/ef00a5352d4c2eb6fa42c28b9e966299eb84feb2...fa1b12aa7ae188c430108383e570119328b5a023.

**Comment by nox** [comment]
[`windows-gnu-dev`](http://build.servo.org/builders/windows-gnu-dev/builds/1215)

**Comment by nox** [comment]
Works with https://github.com/rust-lang/cargo/commit/ce9ddf3480f3028de9d406119863448b82301096, so the culprit is https://github.com/rust-lang/cargo/pull/3651.

**Comment by alexcrichton** [comment]
The change in https://github.com/rust-lang/cargo/pull/3651 was related to `LD_LIBRARY_PATH` handling when running executables (the `PATH` variable on Windows). Previously Cargo would automatically put all paths printed out by build scripts into `LD_LIBRARY_PATH` but this caused many bugs with system libraries were duplicated. Typically if a system directory is expected by `LD_LIBRARY_PATH` it's configured ahead of time (before Cargo is called), so that change is only augmenting `LD_LIBRARY_PATH` with paths in the build dir.

Do servo tests rely on a DLL in a system directory to be in `PATH`, when the dll isn't already in `PATH`? It'd be helpful to drill into which DLL is missing, although unfortunately I don't know of a great way to do that. I've used `objdump -p foo.exe | grep -i dll` in the past, but if it doesn't reproduce locally that may be difficult to simulate on the bots.

**Comment by nox** [comment]
Thanks for the quick reply @alexcrichton.

I pushed the hash of the culprit PR in case someone wants to reproduce it locally (just fetch that PR and try to build it).

**Comment by alexcrichton** [comment]
The required DLLs of that test (at least locally) appear to be:

```
        DLL Name: ADVAPI32.dll
        DLL Name: GDI32.dll
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: SHELL32.dll
        DLL Name: USER32.dll
        DLL Name: USERENV.dll
        DLL Name: WS2_32.dll
        DLL Name: libstdc++-6.dll
        DLL Name: LIBEAY32.dll
        DLL Name: SSLEAY32.dll
```

Most of those are pretty standard so the DLLs except for the last three. The libstdc++ dll is typically located in `C:\msys64\mingw64\bin` which I [see is in `PATH`](http://build.servo.org/builders/windows-gnu-dev/builds/1159/steps/test/logs/stdio). The last two, libeay32 and ssleay32 are OpenSSL dlls, and at least locally they're also located in `C:\msys64\mingw64\bin`. 

That then brings up the question of why is this failing? Or is it not failing due to dll issues?

So debugging this a little more locally it looks like the *wrong* `libstdc++-6.dll` is being loaded. Presumably mach (I think?) is placing the `.servo/...` rustc bin dir in `PATH`, and because that's a MinGW compiler it contains `libstdc++-6.dll` next to it. This one is quite old though and different from the one you're actually linking to, `C:\msys64\mingw64\bin\libstdc++-6.dll`.

So previously Cargo would insert `C:\msys64\mingw64\bin` into `PATH` at the beginning but it is now not currently doing so (assuming that the user has configured that). The two crates that print out this path, libz and openssl-sys, ironically don't actually link to libstdc++ at all, so it was just being picked up by accident!

To fix this some possible solutions could be:

* Don't use MinGW *host* compilers, only MSVC ones. These don't ship with any odd DLLs and you shouldn't run into any conflicts. Note that you'll want to install the MinGW target though which will allow you to still compile libraries (also the MSVC target so you can run plugins).
* Change the location of rustc in `PATH` or make sure that dir doesn't show up in `PATH` at all (the .servo downloaded compiler). That'll make sure the bad dll isn't accidentally picked up.


That's unfortunately all I can think of :(

**Comment by SimonSapin** [comment]
We can probably change `mach` to not use `PATH` at all. Instead, run Cargo with an absolute path to its executable, and give it `RUSTC` and `RUSTDOC` environment variables with similar absolute paths.

**Comment by nox** [comment]
@alexcrichton Doesn't that mean that the MinGW host compiler is useless now? Is @retep998 correct when qualifying this as a breaking change?

**Comment by alexcrichton** [comment]
@SimonSapin I believe that would work, yeah.

@nox perhaps, I personally find cross-compiling from MSVC to MinGW far more useful, but there are many opinions here. I do not have an opinion on @retep998's comment.

**Comment by SimonSapin** [comment]
(I’ve edited this PR to be only about Cargo and filed #15911 separately for the compiler update.)

**Comment by larsbergstrom** [comment]
I'm not 100% sure (it's been 10 years or so), but one thing that we might also be able to do is use the `file` element in the application manifest cargo.exe.manifest to point to the relative path where the installed file is:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

IIRC, this comes before `PATH` entries in the `LoadLibrary` search order.

**Comment by nox** [comment]
> Don't use MinGW host compilers, only MSVC ones.

How hard would it be to do that @larsbergstrom?

**Comment by alexcrichton** [comment]
@larsbergstrom oh that'd work perfectly if we could do that, in that case it'd basically be the same thing as rpath we use for other platforms. Mind filing a rust-lang/rust issue with that info?

**Comment by nox** [comment]
@larsbergstrom Did you file an issue in the end?

**Comment by larsbergstrom** [comment]
@nox I did not manage to track down the details on how that stuff worked yet (it's on my backlog!). But, @metajack turned off mingw builds so you should be unblocked.

**Comment by nox** [comment]
True, but we need to reenable mingw builds at some point given Tor rely on them for Firefox.

**Pull request closed without merging**
