### PR TITLE
Release selectors 0.24.0 and servo_arc 0.2.0

### LINKED ISSUE #29105: Please make a release of selectors which already has cssparser 0.29
The cssparser crate made an API break for 0.29, with the removal of the `AtRuleType` enum.  `selectors` is already updated for this.  Could we please have a release?  I'd like to update both crates in librsvg :smiley:

### PR DESCRIPTION
**Pull request by delan**
This patch extends #29361, bumping selectors to 0.24.0 and servo_arc to 0.2.0.

We’ll need to publish them too, in order to close #29105.

---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #29105 (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [x] These changes do not require tests because there are no functional changes

### CODE REVIEW

**Comment by mukilan** [comment]
Will crates.io allow publishing crates which have optional path dependencies with no version specification? Will we need to patch selectors to remove those from crates.io before publishing?

**Comment by delan** [comment]
Hmm, good point, it looks like the answer is no:

```
% cargo publish -p selectors --dry-run 
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `to_shmem` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```

Based on rust-lang/cargo#4544, we’ll either need to publish dummy versions of to_shmem and to_shmem_derive, or publish them fully.

**Comment by delan** [comment]
I’ve published dummy versions of [to_shmem](https://crates.io/crates/to_shmem) and [to_shmem_derive](https://crates.io/crates/to_shmem_derive) (0.0.0), and updated this patch accordingly.

**Review by jdm — APPROVED** [review]

**Comment by delan** [comment]
```
% cargo publish -p servo_arc          
    Updating crates.io index
   Packaging servo_arc v0.2.0 (/home/delan/code/servo/components/servo_arc)
   Verifying servo_arc v0.2.0 (/home/delan/code/servo/components/servo_arc)
   Compiling nodrop v0.1.14
   Compiling stable_deref_trait v1.2.0
   Compiling servo_arc v0.2.0 (/home/delan/code/servo/target/package/servo_arc-0.2.0)
    Finished dev [unoptimized + debuginfo] target(s) in 1.23s
    Packaged 6 files, 61.5KiB (17.2KiB compressed)
   Uploading servo_arc v0.2.0 (/home/delan/code/servo/components/servo_arc)
    Updating crates.io index
     Waiting on `servo_arc` to propagate to crates.io index (ctrl-c to wait asynchronously)
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index

% cargo publish -p selectors          
    Updating crates.io index
   Packaging selectors v0.24.0 (/home/delan/code/servo/components/selectors)
   Verifying selectors v0.24.0 (/home/delan/code/servo/components/selectors)
   Compiling libc v0.2.139
   Compiling cfg-if v1.0.0
   Compiling ppv-lite86 v0.2.17
   Compiling proc-macro2 v1.0.51
   Compiling siphasher v0.3.10
   Compiling getrandom v0.1.16
   Compiling quote v1.0.23
   Compiling unicode-ident v1.0.6
   Compiling syn v1.0.107
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling dtoa v0.4.8
   Compiling log v0.4.17
   Compiling convert_case v0.4.0
   Compiling matches v0.1.10
   Compiling itoa v1.0.5
   Compiling stable_deref_trait v1.2.0
   Compiling smallvec v1.10.0
   Compiling byteorder v1.4.3
   Compiling nodrop v0.1.14
   Compiling bitflags v1.3.2
   Compiling precomputed-hash v0.1.1
   Compiling servo_arc v0.2.0
   Compiling dtoa-short v0.3.3
   Compiling phf_shared v0.8.0
   Compiling phf_shared v0.10.0
   Compiling fxhash v0.2.1
   Compiling phf v0.8.0
   Compiling getrandom v0.2.8
   Compiling rand_core v0.6.4
   Compiling rand_core v0.5.1
   Compiling rand_pcg v0.2.1
   Compiling rand_chacha v0.2.2
   Compiling rand_chacha v0.3.1
   Compiling rand v0.7.3
   Compiling rand v0.8.5
   Compiling phf_generator v0.8.0
   Compiling phf_generator v0.10.0
   Compiling phf_codegen v0.8.0
   Compiling selectors v0.24.0 (/home/delan/code/servo/target/package/selectors-0.24.0)
   Compiling phf_macros v0.10.0
   Compiling cssparser v0.29.6
   Compiling cssparser-macros v0.6.0
   Compiling derive_more v0.99.17
   Compiling phf v0.10.1
    Finished dev [unoptimized + debuginfo] target(s) in 8.18s
    Packaged 16 files, 208.7KiB (44.1KiB compressed)
   Uploading selectors v0.24.0 (/home/delan/code/servo/components/selectors)
    Updating crates.io index
     Waiting on `selectors` to propagate to crates.io index (ctrl-c to wait asynchronously)
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
```

**Comment by jdm** [comment]
@bors-servo retry
* #29389

**Pull request merged**
