### PR TITLE
Pipeline visibility logic change

### LINKED ISSUE #13191: The pipeline visibility logic is wrong
By visibility, I'm talking about `pipeline.visible`, introduced in #10225.

The way it works today is:
- if iframe.setVisibility() is called, all the inner *current* pipelines are updated
- if a new inner pipeline is created, its visible property is inherited from its parent

This is wrong. This breaks if current pipeline is updated. It should work that way:
- if iframe.setVisibility() is called, all the inner pipelines are updated (not just the current ones)
- if a new inner pipeline is created, its visible property is inherited from the previous pipeline, or if none, from its parent

### PR DESCRIPTION
**Pull request by jmr0**
cc @paulrouget @jdm 

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #13191 (github issue number if applicable).

- [X] There are tests for these changes OR
- [ ] These changes do not require tests because _____

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/13227)

### CODE REVIEW

**Comment by paulrouget** [comment]
Thanks a lot for taking care of this!

The notion of "previous"/"old" pipeline is not always clear. For example, on reload, a new pipeline is created and the current pipeline is dismissed (see #13167). What's the meaning of old/previous in this case?

Because this might be confusing, I would recommend to pass the `visible:bool` to `new_pipeline()` instead of `old_pipeline`, and let the caller figure out if the new pipeline is visible or not (reload will use the visibility of the pipeline it's replacing, navigate will use the previous-in-history pipeline, init load will use its parent pipeline).

As usual, I'm not a reviewer, I'll let someone else comment on this.

**Comment by jdm** [comment]
I found @paulrouget's comments valuable to help focus on the intended effects of these changes, but I actually disagree with his conclusion. I think providing what is effectively a source pipeline to `new_pipeline` is cleaner; I don't want each caller to have to figure out what visibility should be passed. Accordingly, I'm happy to merge these changes once they're rebased. Thank you for dealing with this!

**Review by jdm — APPROVED** [review]

**Comment by paulrouget** [comment]
Works for me :)

**Comment by jmr0** [comment]
Thanks @paulrouget and @jdm

**Pull request merged**
