### PR TITLE
Improvements to Documents' browsing contexts.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9714)

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo: retry
* #9120

**Comment by KiChjang** [comment]
@bors-servo retry
* git problem

**Comment by KiChjang** [comment]
@bors-servo retry
* Infrastructure problem

**Comment by KiChjang** [comment]
@bors-servo retry
* #8191, #9120

**Comment by KiChjang** [comment]
@bors-servo retry
* #9278, #9120

**Comment by KiChjang** [comment]
@bors-servo retry
* #8127

**Pull request merged**
