### PR TITLE
Fix typos in markdown files

### PR DESCRIPTION
**Pull request by myersg86**
Fixes a number of typographical errors across markdown documentation files.

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #___ (GitHub issue number if applicable)

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because ___

### CODE REVIEW

**Comment by jdm** [comment]
Please revert the changes to files under tests/wpt/web-platform-tests. Those are vendored from an upstream repository and we sync with them occasionally.

**Comment by myersg86** [comment]
@jdm thanks for the tip. Your wish is my command! 

Changes to `tests/wpt/web-platform-tests` have been reverted. :magic_wand: :tada:

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Pull request merged**
