### PR TITLE
Disable canvas_over_area.html due to frequent timeouts, pending furth…

### PR DESCRIPTION
**Pull request by jdm**
…er investigation for #8311.

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/8690)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
  ▶ CRASH [expected PASS] /css21_dev/html4/margin-right-applies-to-015.htm
```

**Comment by jdm** [comment]
@bors-servo: retry
* #7437

**Pull request merged**
