### PR TITLE
WebBluetooth Android support

### PR DESCRIPTION
**Pull request by dati91**
Add android support for Webbluetooth.
Also adjust to the changed device api.

---

- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [X] These changes do not require tests because there is no test api yet.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/12875)

### CODE REVIEW

**Comment by dati91** [comment]
This patch depend on the [devices android support pr](https://github.com/servo/devices/pull/15).
After it lands i will update the Cargo.toml and lock files.

**Comment by dati91** [comment]
CC @jdm @larsbergstrom

**Comment by jdm** [comment]
The Rust code changes look fine to me; @larsbergstrom should take a look at the Android manifest and java changes, however.

**Pull request merged**
