### PR TITLE
Upgrade to rustc 1.26.0-nightly (5508b2714 2018-03-18)

### PR DESCRIPTION
**Pull request by Eijebong**
This fixes a bug in the compiler that made the compiler not output any
colors in errors on archlinux with a 256 colors term.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/20301)

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’m not opposed to upgrading, but does this really fix color output? https://github.com/rust-lang/rust/issues/45728 is still open and https://github.com/rust-lang/rust/tree/master/src/libterm says the last commit that touched this directory was in December.

**Comment by Eijebong** [comment]
Yes they are :) https://github.com/rust-lang/rust/pull/48588

**Comment by mbrubeck** [comment]
The Windows build timed out after 90 minutes (!) on both buildbot and appveyor.  Windows builds must be hitting a hang or an *extremely* large perf regression in the compiler.

**Comment by Eijebong** [comment]
Unfortunately I don't have any windows machine, so I can't check this myself

**Comment by Eijebong** [comment]
https://github.com/rust-lang/rust/issues/49072 Might be related

**Comment by SimonSapin** [comment]
I couldn’t reproduce this slowdown on my windows machine (this PR built from `mach clean` in 28 minutes), but let’s try today’s Nightly now that it has a fix for https://github.com/rust-lang/rust/issues/49072?

**Comment by Eijebong** [comment]
That's a lot of timeouts

**Comment by SimonSapin** [comment]
They seem to have similar output:

```rust
  │ 2018-03-19 11:42:44.116 servo[25185:3327950660] Metadata.framework [Error]: couldn't get the client port
  │ Stack trace for thread "main"
  │ stack backtrace:
  │    0:        0x11142ef7e - backtrace::backtrace::trace::h3b0511a6df1ae4a5
  │    1:        0x11142dc7c - backtrace::capture::Backtrace::new::h21529f7f40cbaa83
  │    2:        0x10ed6abde - servo::install_crash_handler::handler::h3481f04a32a26851
  │    3:     0x7fff8eba8f19 - _sigtramp
  │    4:        0x1108fc817 - blurmac::framework::cb::centralmanager::hadb9108858bf58fa
  │    5:        0x1108f980c - blurmac::adapter::BluetoothAdapter::init::h12fc899509447924
  │    6:        0x1108e1b04 - device::bluetooth::BluetoothAdapter::init::h1a035bb7d14c2cdf
  │    7:        0x1108ba2a5 - _$LT$ipc_channel..ipc..IpcSender$LT$bluetooth_traits..BluetoothRequest$GT$$u20$as$u20$bluetooth..BluetoothThreadFactory$GT$::new::hc520f3f584afd53d
  │    8:        0x10edceae4 - servo::create_constellation::h6108e2b6a6c5115e
  │    9:        0x10ed6bbe6 - servo::main::h8d22c640247e7ed1
  │   10:        0x10ed75b05 - std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h053a9ba0604d8d0e
  │   11:        0x111445497 - std::panicking::try::do_call::h6fbdff9290bdadf9 (.llvm.12444387374658511544)
  │   12:        0x111460cbe - __rust_maybe_catch_panic
  │   13:        0x111447d81 - std::rt::lang_start_internal::h3a60217bd973f81e
  └   14:        0x10ed6cecb - main
```

**Comment by jdm** [comment]
The most useful way forward would be for someone with a mac to try to reproduce the problem, or else log into a mac builder and investigate it there.

**Pull request closed without merging**
