### PR TITLE
Rewrite NodeChildrenIterator to return Temporary.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo/5456)

### CODE REVIEW

**Comment by saneyuki** [comment]
@Ms2ger I commented.

**Comment by jdm** [comment]
```
/dom/events/Event-propagation.html
----------------------------------
CRASH [Parent]
/dom/nodes/CharacterData-remove.html
------------------------------------
CRASH [Parent]
/dom/nodes/Document-doctype.html
--------------------------------
CRASH [Parent]
/dom/nodes/Document-getElementsByTagName.html
---------------------------------------------
CRASH [Parent]
/dom/nodes/Document-getElementsByTagNameNS.html
-----------------------------------------------
CRASH [Parent]
/dom/nodes/DocumentType-remove.html
-----------------------------------
CRASH [Parent]
/dom/nodes/MutationObserver-attributes.html
-------------------------------------------
ERROR [Parent]
/dom/nodes/Element-getElementsByTagName.html
--------------------------------------------
CRASH [Parent]
/dom/nodes/Element-getElementsByTagNameNS.html
----------------------------------------------
CRASH [Parent]
/dom/nodes/Element-remove.html
------------------------------
CRASH [Parent]
/dom/nodes/Node-childNodes.html
-------------------------------
CRASH [Parent]
/dom/nodes/Node-lookupPrefix.xhtml
----------------------------------
CRASH [Parent]
/dom/nodes/Node-insertBefore.html
---------------------------------
CRASH [Parent]
/dom/nodes/Node-normalize.html
------------------------------
CRASH [Parent]
/dom/nodes/Node-properties.html
-------------------------------
CRASH [Parent]
/dom/nodes/Node-removeChild.html
--------------------------------
CRASH [Parent]
/dom/nodes/Node-replaceChild.html
---------------------------------
CRASH [Parent]
/dom/nodes/case.html
--------------------
CRASH [Parent]
/dom/traversal/TreeWalker-basic.html
------------------------------------
CRASH [Parent]
/html/dom/documents/dom-tree-accessors/document.body-getter.html
----------------------------------------------------------------
CRASH [Parent]
/html/dom/documents/dom-tree-accessors/document.head-02.html
------------------------------------------------------------
CRASH [Parent]
/html/dom/documents/dom-tree-accessors/document.head-01.html
------------------------------------------------------------
CRASH [Parent]
/html/dom/documents/dom-tree-accessors/document.title-03.html
-------------------------------------------------------------
CRASH [Parent]
/html/dom/documents/dom-tree-accessors/document.title-04.xhtml
--------------------------------------------------------------
CRASH [Parent]
/html/dom/documents/dom-tree-accessors/document.title-05.html
-------------------------------------------------------------
CRASH [Parent]
/html/dom/documents/dom-tree-accessors/document.title-08.html
-------------------------------------------------------------
CRASH [Parent]
/html/dom/interfaces.html
-------------------------
CRASH [Parent]
/html/infrastructure/urls/terminology-0/document-base-url.html
--------------------------------------------------------------
CRASH expected TIMEOUT [Parent]
/html/semantics/document-metadata/the-title-element/title.text-03.html
----------------------------------------------------------------------
CRASH [Parent]
/html/semantics/document-metadata/the-title-element/title.text-04.xhtml
-----------------------------------------------------------------------
CRASH [Parent]
/html/semantics/scripting-1/the-script-element/async_008.htm
------------------------------------------------------------
CRASH [Parent]
/html/semantics/scripting-1/the-script-element/async_006.htm
------------------------------------------------------------
CRASH [Parent]
/html/semantics/scripting-1/the-script-element/async_007.htm
------------------------------------------------------------
CRASH [Parent]
/html/semantics/tabular-data/the-table-element/createTBody.html
---------------------------------------------------------------
CRASH [Parent]
/old-tests/submission/Opera/script_scheduling/091.html
------------------------------------------------------
CRASH [Parent]
/old-tests/submission/Opera/script_scheduling/092.html
------------------------------------------------------
CRASH [Parent]
/2dcontext/shadows/canvas_shadows_002.htm
-----------------------------------------
FAIL [Parent]
```
```
failures:
    /Users/servo/buildbot/slave/mac2/build/tests/content/test_document_head.html
    /Users/servo/buildbot/slave/mac2/build/tests/content/test_document_implementation.html
    /Users/servo/buildbot/slave/mac2/build/tests/content/test_node_cloneNode.html
    /Users/servo/buildbot/slave/mac2/build/tests/content/test_node_insertBefore.html
    /Users/servo/buildbot/slave/mac2/build/tests/content/test_node_isEqualNode.html
    /Users/servo/buildbot/slave/mac2/build/tests/content/test_node_normalize.html
    /Users/servo/buildbot/slave/mac2/build/tests/content/test_proxy_setter.html
    /Users/servo/buildbot/slave/mac2/build/tests/content/test_title.html
```
```
failures:
    append_style_a.html == append_style_b.html
```

**Comment by metajack** [comment]
Assigned @jdm (thought @saneyuki) did the review, since I'm not sure if @saneyuki has r+ privs.

**Comment by Manishearth** [comment]
@metajack @saneyuki does have r+ privs, fwiw

**Comment by jdm** [comment]
```
/dom/nodes/Element-matches.html
-------------------------------
CRASH [Parent]
/dom/nodes/Node-normalize.html
------------------------------
CRASH [Parent]
/dom/nodes/ParentNode-querySelector-All.html
--------------------------------------------
CRASH [Parent]
```
Interestingly we're hitting spillage on the RootCollection again for the first one.

**Comment by jdm** [comment]
```
failures:
    /home/servo/buildbot/slave/linux1/build/tests/content/test_node_cloneNode.html
```

**Pull request closed without merging**
