### PR TITLE
Always request new XR frames

### PR DESCRIPTION
**Pull request by Manishearth**
Currently we only request XR frames when there is a rAF callback queued up.

This is incorrect, see https://immersive-web.github.io/webxr/#xr-animation-frame

With this change we always request updated frame state regardless of whether or not the user has queued up callbacks.

In addition to being spec-correct, this means that we can reliably listen for events in the OpenXR backend in the rAF loop itself, instead of having to set up a second spinning loop for when the rAF is inactive. This lets us implement visibility states for openxr without having to worry about the user never receiving the wakeup call because the rAF loop isn't pumping.

See also: https://github.com/immersive-web/webxr/issues/877

r? @asajeffrey

### CODE REVIEW

**Comment by Manishearth** [comment]
I need to test this, don't merge yet

**Comment by Manishearth** [comment]
This works.

**Comment by asajeffrey** [comment]
With this change, are we now allowing multiple calls to wait for animation frame for each call to present an animation frame? We might want to document this, for device back ends that assume they come in pairs.

**Comment by Manishearth** [comment]
No, I don't think so? There will only ever be one queued up call to r_a_f at a time, since we queue it up when we finish processing the last XRAF.

**Comment by asajeffrey** [comment]
Also, should we only present the animation frame of there have been some WebGL calls which drew to the XR framebuffer?

**Comment by Manishearth** [comment]
@asajeffrey I thought the answer was "no" but it seems like we want it to be "yes"

https://github.com/immersive-web/webxr/issues/877

**Comment by Manishearth** [comment]
We are calling wfaf irrespective of callbacks. We're not calling it _multiple times_ in between frames

**Comment by asajeffrey** [comment]
I'm wondering if we should be calling wfaf irrespective of what we hear from script? At the moment we're only calling wfaf inf we get an RAF message from script.

https://github.com/immersive-web/webxr/issues/877#issuecomment-542423391 makes me think that the pattern should be (w_f_a_f* render_a_f)*, since we should only be calling render_a_f if there's been some "relevant" WebGL.

**Comment by Manishearth** [comment]
No, we don't want the device to queue up frames when script isn't ready.
This PR means that there's a nice back and forth where script requests an
af when it's done with the previous one.

**Comment by asajeffrey** [comment]
@Manishearth and I had a zoom meeting. It's OK for script to continue to drive webxr, if script goes into an infinite loop, then webxr will freeze, serves script right :) So we can expect heartbeat RequestAF messages from script to webxr, even if there's no rAF callbacks registered. If the WebGL content hasn't been updated (as per https://github.com/immersive-web/webxr/issues/877#issuecomment-542423391) then there shouldn't be a RenderAF message sent by script. So the normal message pattern is (RequestAF RenderAF)* but in the case where there's no updates to the WebGL content it's (RequestAF+ RenderAF)*.

**Comment by asajeffrey** [comment]
Oh yes, and you can r=me on the PR :)

**Pull request merged**
