### PR TITLE
Clipboard Event API

### LINKED ISSUE #31024: Implement Clipboard API and events
Needed for https://github.com/servo/servo/issues/30822

Spec: https://www.w3.org/TR/clipboard-apis/

Besides the web api, I assume this will involve integrating with the embedding layer, see for a starting point: https://github.com/servo/servo/blob/527119aebb4e0c05e3ba17c5ba2e2741d51489a9/ports/servoshell/keyutils.rs#L4

### PR DESCRIPTION
**Pull request by rathod-sahaab**
---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [x] These changes fix #31024  (GitHub issue number if applicable)

- [ ] There are tests for these changes

# Tracking

source: [DataTransferItem's documentation](https://html.spec.whatwg.org/multipage/dnd.html#the-datatransferitem-interface)

Are read/write, read, protected mode part of drag and drop event or DataTranferItem's properties? need to read documentation and usage.

---

Legends, indicates what's still needed to be done in order or dependency

1. S: struct
2. I: Implementation (constructors)
3. M: Methods

- Bindings implementation
    - [ ] DataTranferItem - I
    - [ ] DataTransferItemList - S
    - [ ] DataTransfer - S
    - [ ] ClipboardEventInit - S
    - [ ] ClipboardEvent - S

### CODE REVIEW

**Comment by gterzian** [comment]
Thanks a lot for the contrib @rathod-sahaab ! Let me know when it is ready for review, or if you need any assistance.

**Comment by rathod-sahaab** [comment]
@gterzian will only be able to make significant progress during the weekend 😅

**Comment by mrobinson** [comment]
@rathod-sahaab Are you still working on this change?

**Comment by mrobinson** [comment]
@rathod-sahaab I'm going to close this PR. It looks like it's in an early state. I don't want to discourage you from working on it, so please feel free to open a new PR when your work is further along or you are ready to keep working on it. We are just trying to avoid too many open and stale PRs. Thank you!

**Pull request closed without merging**
