### PR TITLE
Call WPT lint directly in tidy, fixes #9189

### LINKED ISSUE #9189: Tidy should stop calling the WPT lint using subprocess
Instead of the subprocess call (in `check_wpt_lint_errors`), we should change the working directory to `tests/wpt/web-platform-tests`, so that we can just import the lint's `main` function, and do the checks directly. This will be very helpful for a future plan to improve tidy's performace (once w3c/wpt-tools#45 is fixed)

Code: `python/tidy.py` and `tests/wpt/web-platform-tests/tools/lint/lint.py`

### PR DESCRIPTION
**Pull request by PythonNut**
This should be fairly straightforward. :)

[Review on Reviewable](https://reviewable.io/reviews/servo/servo/9277)

### CODE REVIEW

**Comment by Wafflespeanut** [comment]
Mmm, beautiful! :)

@bors-servo r+

Thanks!

**Comment by PythonNut** [comment]
Actually, I made a slight mistake refactoring, and `lint.main()` is called twice. Let me fix that.

**Comment by PythonNut** [comment]
Sorry about that.

**Comment by Wafflespeanut** [comment]
@bors-servo r-

um, I don't see any difference between [`700e35d`](https://github.com/PythonNut/servo/commit/700e35d01c9fbde53c4d2aaeec775d629850181c) and [`fcd33e2`](https://github.com/PythonNut/servo/commit/fcd33e2b7038f29c2227008ec8bb37796ece4361)?

**Comment by PythonNut** [comment]
>   ▶ Unexpected subtest result in `/html/infrastructure/terminology/plugins/text-plain.html`:
  └ PASS [expected FAIL] A user agent must not consider the type `text/plain` as having a registered plugin.

I'm not familiar with this testing framework. I went looking for references to that file in the `test-wpt.log`, but I couldn't find anything useful.

How can I look into resolving this?

**Comment by jdm** [comment]
@bors-servo: retry
* #9286

**Comment by jdm** [comment]
It's just an unexpected, intermittent test result that's unrelated to these changes.

**Pull request merged**
