### PR TITLE
Add only one architecture per apk

### LINKED ISSUE #22192: Building with webvr enabled gives runtime link error for libc++_shared.so
after running:

```
./mach build --release --android --features googlevr
./mach package -r -f googlevr
```

Servo fails to load on a Pixel 2, crashing with the error that libc++_shared.so is missing.

Inspecting the APK, under lib/ there are three folders: arm64-v8a, armeabi-v7a, and x86. Regular servo builds only have the second one. The other two only contain libgvr.so (whereas the second one contains libsimpleservo, libgvr, libgstreamer, and libc++_shared).

The following patch fixes this error, but I don't think it's the real fix

```patch
--- a/support/android/apk/servoapp/build.gradle
+++ b/support/android/apk/servoapp/build.gradle
@@ -119,6 +119,11 @@ android {
           }
       }
     }
+
+    packagingOptions {
+        exclude 'lib/arm64-v8a/libgvr.so'
+        exclude 'lib/x86/libgvr.so'
+    }
 }
```

cc @paulrouget @MortimerGoro

### PR DESCRIPTION
**Pull request by paulrouget**
Fix #22192

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/22196)

### CODE REVIEW

**Comment by paulrouget** [comment]
We do it for the AAR but not for the APK.

**Comment by Manishearth** [comment]
(android is busted)

**Pull request merged**
