### PR TITLE
WebXR sessions track draw texture

### PR DESCRIPTION
**Pull request by asajeffrey**
Send the XR framebuffer texture to the XR session.
 
---

- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes do not require tests because we don't have webxr reftests

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo/23857)

### CODE REVIEW

**Comment by asajeffrey** [comment]
The matching webxr changes are https://github.com/servo/webxr/pull/31

**Review by Manishearth — APPROVED** [review]

**Comment by jdm** [comment]
```

  ▶ Unexpected subtest result in /webxr/xrSession_prevent_multiple_exclusive.https.html:
  └ PASS [expected FAIL] Test prevention of multiple simultaneous immersive sessions

  ▶ OK [expected ERROR] /webxr/xrSession_input_events_end.https.html

  ▶ ERROR [expected TIMEOUT] /webxr/xrBoundedReferenceSpace_updates.https.html
  │   → fakeDeviceController.setBoundsGeometry is not a function
  │ 
  └ undefined:undefined:undefined
```
  ▶ OK [expected ERROR] /webxr/xrSession_end.https.html

  ▶ Unexpected subtest result in /webxr/xrSession_end.https.html:
  │ FAIL [expected NOTRUN] end event fires when non-immersive session ends
  └   → promise_test: Unhandled rejection with value: undefined

**Comment by asajeffrey** [comment]
Oh, have I accidentally fixed some broken tests? I'll update the expectations when I'm in front of a computer.

**Pull request merged**
