### PR TITLE
[WIP] Install ragel in linux CI.

### PR DESCRIPTION
**Pull request by jdm**
This is a possible workaround for #24611.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Isn’t Harfbuzz used on all platforms?

**Comment by jdm** [comment]
Yes, but this is just an experiment from the github editing UI to see what happens.

**Comment by jdm** [comment]
I'll try to remember to do that next time.

**Comment by SimonSapin** [comment]
We would also have needed to install Ragel on Windows, but it looks like https://www.colm.net/open-source/ragel/ doesn’t provide binaries.

**Pull request closed without merging**
