### PR TITLE
Implement [Func]

### PR DESCRIPTION
**Pull request by nox**
First part of #11292, this just includes support of `[Func]`.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo/11308)

### CODE REVIEW

**Comment by nox** [comment]
I've added a few commits that conditionally-define `HTMLIFrameElement.mozbrowser`.

**Comment by jdm** [comment]
Nice work! I appreciated how the commits were broken up.
-S-awaiting-review +S-needs-code-changes 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 5 of 5 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 5 of 5 files at r9, 2 of 2 files at r10, 6 of 6 files at r11, 3 of 3 files at r12, 17 of 17 files at r13, 1 of 1 files at r14, 2 of 2 files at r15, 3 of 3 files at r16, 5 of 5 files at r17, 1 of 1 files at r18, 1 of 1 files at r19, 1 of 1 files at r20, 5 of 5 files at r21, 2 of 2 files at r22, 6 of 6 files at r23, 3 of 3 files at r24, 1 of 1 files at r25, 17 of 17 files at r26, 1 of 1 files at r27, 2 of 2 files at r28, 3 of 3 files at r29, 5 of 5 files at r30, 1 of 1 files at r31, 1 of 1 files at r32, 1 of 1 files at r33, 5 of 5 files at r34, 2 of 2 files at r35, 6 of 6 files at r36, 3 of 3 files at r37, 4 of 4 files at r38, 3 of 3 files at r39.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1336 \[r1\]](https://reviewable.io:443/reviews/servo/servo/11308#-KIi1Ph-1xDuWI-WwrgG:-KIi1Ph-1xDuWI-WwrgH:-590267503) ([raw file](https://github.com/servo/servo/blob/b530e9968a9a24ae5067cd9957caa984887404e1/components/script/dom/bindings/codegen/CodegenRust.py#L1336)):*
> ```Python
>     assert pref is None or isinstance(pref, str)
>     assert func is None or isinstance(func, str)
>     if pref is not None:
> ```

`if pref:`

---

*[components/script/dom/bindings/codegen/CodegenRust.py, line 1340 \[r39\]](https://reviewable.io:443/reviews/servo/servo/11308#-KIi75QhvwDZPI-cBvCe:-KIi75Qig5q7bpgmrA63:-873523214) ([raw file](https://github.com/servo/servo/blob/7d5ffecb36cc6fd8b50b2db14ba932c2e6e608b1/components/script/dom/bindings/codegen/CodegenRust.py#L1340)):*
> ```Python
>     if pref is not None:
>         return 'Condition::Pref("%s")' % pref
>     if func is not None:
> ```

`if func:`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11308#-:-KIi78IbOEAlpoYhF4Uw:-1536068809)*

**Comment by jdm** [comment]
As far as I can see, we're not actually testing the new properties and methods that were added to TestBinding. We should add them to the interface_member_exposed.html test.
-S-awaiting-review +S-needs-tests 

<details><summary><i>Previously, highfive wrote…</i></summary>
> New code was committed to pull request.
</details>


---

Reviewed 17 of 17 files at r40, 1 of 1 files at r41, 2 of 2 files at r42, 3 of 3 files at r43, 5 of 5 files at r44, 1 of 1 files at r45, 1 of 1 files at r46, 1 of 1 files at r47, 5 of 5 files at r48, 2 of 2 files at r49, 6 of 6 files at r50, 3 of 3 files at r51.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/servo/11308#-:-KIj5XGbG4td03c7yzue:-169763407)*

**Comment by nox** [comment]
@jdm I added the test you wanted.

**Pull request merged**
